### ISSUE TITLE
对小程序的支持程度

### ISSUE THREAD

**Issue by weiyunpeng** [NervJS/taro#10]
不知道Taro 对小程序支持到哪种程度，所有小程序组件和api都支持么？还是只支持部分组件和api

**Comment by yuche** [comment]
如果你不需要转多端的话，那就是支持所有组件和所有 API。

**Comment by luckyadam** [comment]
+1
Taro 组件以及 api 标准都源自微信小程序，你可以完全把 Taro 用作小程序的开发框架

**Comment by julytian** [comment]
有没有具体的例子demo@luckyadam

**Comment by xdlrt** [comment]
支持小程序所有的事件类型吗？

**Comment by luckyadam** [comment]
@julytian 有的~
https://github.com/NervJS/taro-todo
这是我们的demo示例~

**Comment by luckyadam** [comment]
@xdlrt 支持的~

**Comment by baronliu** [comment]
比如支持cover-view等组件吗，我看你们文档里并没有体现，有些api和组件没有在文档中

**Comment by yuche** [comment]
文档里的组件是H5版本的，只做小程序不用在意。
