### ISSUE TITLE
是否可以使用UI库？

### ISSUE THREAD

**Issue by yongqi-zhang** [NervJS/taro#100]
是否可以使用小程序或者React相关得UI库，怎么使用呢？

**Comment by tourze** [comment]
同问这个问题，能支持的话，对现有项目迁移会有很大好处。

**Comment by zjsxfly** [comment]
同问，如果没有UI，很多轮子需要重新造

**Comment by luckyadam** [comment]
正在考虑如何支持

**Comment by kenberkeley** [comment]
+1

**Comment by luckyadam** [comment]
已加入开发计划
https://github.com/NervJS/taro/blob/master/PLANS.md
