### ISSUE TITLE
Taro 现在支持mobx6.x 不？

### ISSUE THREAD

**Issue by luozyiii** [NervJS/taro#10019]
### 这个特性解决了什么问题？
我查看了你们的文档 现在还停留在4.8 版本，希望可以更新一下

### 这个 API 长什么样？
我不希望使用装饰器的语法来编写mobx

**Comment by tu6ge** [comment]
@Chen-jj 这种描述不清楚的问题，建议关闭

**Comment by tu6ge** [comment]
@luozyiii 建议你看看 [提问的艺术](https://blog.csdn.net/weixin_32819579/article/details/102704571) ,学习后，重新发起你的问题
