### ISSUE TITLE
钉钉初始化项目无法运行

### ISSUE THREAD

**Issue by Victorldh** [NervJS/taro#10018]
### 相关平台
微信小程序

**小程序基础库: ExtSDKVersion: "1.25.7" SDKVersion: "1.25.2"**
**使用框架: React**

### 复现步骤
安装3.3.0版本taro，初始化项目后直接根据官方文档运行，打包后在钉钉开发者平台运行报错

### 期望结果
可以支持支持钉钉小程序的编译

### 实际结果
 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### 环境信息
```
Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.0 => 3.3.0 
      @tarojs/mini-runner: 3.3.0 => 3.3.0 
      @tarojs/react: 3.3.0 => 3.3.0 
      @tarojs/runtime: 3.3.0 => 3.3.0 
      @tarojs/taro: 3.3.0 => 3.3.0 
      @tarojs/webpack-runner: 3.3.0 => 3.3.0 
      babel-preset-taro: 3.3.0 => 3.3.0 
      eslint-config-taro: 3.3.0 => 3.3.0 
      react: ^17.0.0 => 17.0.2 

```

**Comment by Chen-jj** [comment]
@Victorldh 提供一下 Demo

**Comment by Chen-jj** [comment]
Taro v3.1.0 才开始支持钉钉小程序插件 [@tarojs/plugin-platform-alipay-dd](https://github.com/NervJS/taro-plugin-platform-alipay-dd)，且它有以下版本要求：

## 版本要求

### Taro 3.3.8+

请使用 `@tarojs/plugin-platform-alipay-dd` 插件的 `~0.1.0` 版本

### Taro 3.1 & 3.2

请使用 `@tarojs/plugin-platform-alipay-dd` 插件的 `~0.0.5` 版本
