### ISSUE TITLE
windows系统打包报错

### ISSUE THREAD

**Issue by lpc-g** [NervJS/taro#10026]
### 相关平台
H5

**浏览器版本: Chrome 92.0.4515.131**
**使用框架: React**

### 复现步骤
windows 系统打包 h5 会报错 Cannot find module './taro-view-core.entry.js'
同样的代码在mac打包就没这个报错信息

### 期望结果
打包完部署项目正常运行

### 实际结果
windows 打包部署完报错

### 环境信息
```
👽 Taro v3.3.1

production环境变量

  Taro CLI 3.3.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.20.0 - D:\Download\nvm\nodejs\node.EXE
      npm: 6.14.8 - D:\Download\nvm\nodejs\npm.CMD   
```

**Comment by ZakaryCode** [comment]
未能复现到该问题，可升级版本后重试
