### ISSUE TITLE
希望支持无障碍相关属性

### ISSUE THREAD

**Issue by Leon-z** [NervJS/taro#10025]
### 这个特性解决了什么问题？
小程序侧已经支持了无障碍属性，taro在传递时过滤了这些属性，希望能支持无障碍开发

注1：具体需求参见工业和信息化部关于印发《互联网应用适老化及无障碍改造专项行动方案》的通知
注2：微信小程序关于无障碍的支持 https://developers.weixin.qq.com/miniprogram/dev/component/aria-component.html

### 这个 API 长什么样？
跟微信小程序[无障碍文档](https://developers.weixin.qq.com/miniprogram/dev/component/aria-component.html)推荐是一致的

**Comment by Chen-jj** [comment]
@Leon-z 无障碍属性较多，Taro 默认在模板中加入的话会令包体积增大，而且也不是各个项目都会用到。这里更好的办法是，开发者根据自己的需要，使用 `@tarojs/plugin-inject` 插件，自定义地添加这些属性。
