### ISSUE TITLE
关注公众号组件事件错误

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro#1004]
**问题描述**

https://developers.weixin.qq.com/miniprogram/dev/component/official-account.html

**复现步骤**

![image](https://user-images.githubusercontent.com/16408873/47994114-54a96b80-e12c-11e8-8276-ced2c732cb61.png)

![image](https://user-images.githubusercontent.com/16408873/47994069-3f344180-e12c-11e8-98d0-ed8ca8ee6b1a.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 1.1.0
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [ weapp]

**Comment by luckyadam** [comment]
close via ef22e7a77766a3a2b01446277e8f06abed962ddd

**Comment by luckyadam** [comment]
1.1.1 版本已发，可以升级到 1.1.1 试试
