### ISSUE TITLE
redux connector 需要加上componentWillReceiveProps

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#1005]
由于connect有第二个参数 props
```js
@connect((state, props)=>({
   // xxx
}))
```
所以connect的值可以同时由props+redux state一起计算

但是因为connector中没有componentWillReceiveProps时重新计算connect 导致组建刷新后由props + redux state计算的属性无法更新

**Comment by luckyadam** [comment]
可以来个 PR ~

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/4b3a25462bc8916f0b0515a24e5101b42d7276ca
