### ISSUE TITLE
[eslint] 从 this.props 而来的函数名必须要以 `on` 开头

### ISSUE THREAD

**Issue by imruxin** [NervJS/taro#1006]
如下图所示，晚上找了好久还是不清楚在哪里修改这个东西？

![image](https://user-images.githubusercontent.com/5736012/48006504-8e8c6900-e150-11e8-9710-0f73e3120c47.png)

Taro version：1.1.1
编辑器：vs code  1.28.2 (1.28.2)

**Comment by yuche** [comment]
在你的 `.eslintrc` 的 rules 中禁用掉就可以了，下个版本可以用 `dispatch`。

```
  rules: {
    'taro/this-props-function': 0
  },
```

**Comment by DiamondYuan** [comment]
如果不想全部关闭，在页面里加一行
/*eslint "taro/this-props-function": 0,*/
