### ISSUE TITLE
3.3.3版本Picker设置rangkey属性依然返回undefined

### ISSUE THREAD

**Issue by lemonSll** [NervJS/taro#10060]
### 相关平台
H5

**浏览器版本: 版本 92.0.4515.131（正式版本） （64 位）**
**使用框架: Vue 2**

### 复现步骤
npm run dev:h5

### 期望结果
不要为undefined

### 实际结果
设置rangkey为undefined
![image](https://user-images.githubusercontent.com/44395984/129685894-84e52bc3-7163-4159-ab7a-410e372a91cb.png)
![image](https://user-images.githubusercontent.com/44395984/129685948-93a9c904-8186-4c5c-9653-0a0a0580566b.png)
![image](https://user-images.githubusercontent.com/44395984/129685993-abd973c1-89ec-4c77-abb2-067c7445db57.png)

### 环境信息
```
  Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lemonSll** [comment]
麻烦能快点修复吗,项目已经上线了
两种设置方式都不行
![image](https://user-images.githubusercontent.com/44395984/129686678-4fae56ac-08ba-4e63-b756-4e9814b208ea.png)

**Comment by wangjun521** [comment]
这个不应该是range-key="name" 么?

**Comment by DingLQ** [comment]
range-key="text"
rangeKey="text"
一起加上就有用了

**Comment by jiaozitang** [comment]
taro vue 组件属性遵从小程序规范（全小写，kebab-case）。Picker设置rangkey属性的正确写法如下：
```
<picker mode="selector" range-key="name" :range="selector" @change="onChange">
          <view class="picker">
            当前选择：{{selectorChecked}}
          </view>
        </picker>
```

完整代码示例地址：https://github.com/jiaozitang/taro-demo/tree/h5-demo-picker-vue2
