### ISSUE TITLE
微信小程序在页面中使用onUnload方法,不会触发该方法

### ISSUE THREAD

**Issue by jytx** [NervJS/taro#10076]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/jytx/testdemo](https://github.com/jytx/testdemo)
**小程序基础库: 2.19.2**
**使用框架: Vue 2**

### 复现步骤
1.index页面点击按钮
2.跳转到index2页面
3.关闭index2页面

### 期望结果
关闭index2后,会正常触发onUnload方法,打印出日志

### 实际结果
关闭index2后,没有触发onUnload

### 环境信息
```
👽 Taro v3.3.2


  Taro CLI 3.3.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.2 => 3.3.2 
      @tarojs/mini-runner: 3.3.2 => 3.3.2 
      @tarojs/runtime: 3.3.2 => 3.3.2 
      @tarojs/taro: 3.3.2 => 3.3.2 
      @tarojs/webpack-runner: 3.3.2 => 3.3.2 
      babel-preset-taro: 3.3.2 => 3.3.2 
      eslint-config-taro: 3.3.2 => 3.3.2 
```

---
### 补充信息
虽然正常情况下可以使用destroy方法来实现监听销毁,但是想要在Vue.mixin中增加destroy则不行,因为页面中存在很多其他组件,在销毁页面时同样会触发该方法。
目前测试在node_modules/@tarojs/runtime/dist/runtime.esm.js 文件的onUnload方法中增加代码:

onUnload() {
            unmounting = true;
            Current.app.unmount(this.$taroPath, () => {
                unmounting = false;
                safeExecute(this.$taroPath, 'onUnload');
                instances.delete(this.$taroPath);
                if (pageElement) {
                    pageElement.ctx = null;
                }
                if (prepareMountList.length) {
                    prepareMountList.forEach(fn => fn());
                    prepareMountList = [];
                }
            });
        },

则可以调用页面中的onUnload方法,这个是代码漏了么?还是有其他额外的处理?

**Comment by Chen-jj** [comment]
@jytx 用 Vue 的生命周期。

```js
destroyed () {
  console.log('onUnload');
}
```

**Comment by jytx** [comment]
> @jytx 用 Vue 的生命周期。
> 
> ```js
> destroyed () {
>   console.log('onUnload');
> }
> ```

如果只是部分页面监听销毁可以使用destroyed,但是目前需求是通过mixin中全局监听onUnload事件来获取关闭页面的事件,使用destroyed时会同时触发页面中组件的destroyed方法
