### ISSUE TITLE
页面内一个view标签内有4个带class的标签会报错

### ISSUE THREAD

**Issue by bb-bin** [NervJS/taro#10077]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/bb-bin/test.git](https://github.com/bb-bin/test.git)
**小程序基础库: 2.19.1**
**使用框架: Vue 3**

### 复现步骤
打开注释

### 期望结果
页面内一个view标签内有4个带class的标签不报错

### 实际结果
报错

### 环境信息
```
👽 Taro v3.3.2


  Taro CLI 3.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@bb-bin 和这个 [commit](https://github.com/vuejs/vue-next/commit/c0db807844194a227f6d0dad6cc3e1e8f148770f) 有关，可以先把 Vue 降级到 3.1.4 。

```
"vue": "3.1.4"
"@vue/compiler-sfc": "3.1.4"
```

**Comment by Chen-jj** [comment]
先开着吧，Taro 还是要改的
