### ISSUE TITLE
钉钉小程序编译报错在开发工具上启动失败

### ISSUE THREAD

**Issue by aofong** [NervJS/taro#10075]
### 相关平台
支付宝小程序

### 复现仓库
[https://gitee.com/aofong/taro3demo](https://gitee.com/aofong/taro3demo)
**小程序基础库: Lyra Version: 6.0.14**
**使用框架: React**

### 复现步骤
1  拉取示例代码
2  执行 yarn dev:dd 指令
3  钉钉开发工具打开编译后的项目

### 期望结果
可以正常运行

#### 编译错误

```
编译  发现入口  src/app.js
编译  发现页面  src/pages/index/index.jsx
⚠️  编译警告. 2021-8-18 6:01:22 ├F10: PM┤

./node_modules/@tarojs/plugin-platform-alipay-dd/dist/runtime.js 9:56-69
" '@tarojs/plugin-platform-alipay/dist/runtime-utils' does not contain an export named 'noPromiseApis'.
```

#### 开发工具错误
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

### 环境信息
```
Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /var/folders/kz/89v1l75n3ylgtv2h74xd7zhc0000gn/T/yarn--1629281376408-0.9870242833913025/node
      Yarn: 1.22.4 - /var/folders/kz/89v1l75n3ylgtv2h74xd7zhc0000gn/T/yarn--1629281376408-0.9870242833913025/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.3 => 3.3.3 
      @tarojs/components: 3.3.3 => 3.3.3 
      @tarojs/mini-runner: 3.3.3 => 3.3.3 
      @tarojs/react: 3.3.3 => 3.3.3 
      @tarojs/runtime: 3.3.3 => 3.3.3 
      @tarojs/taro: 3.3.3 => 3.3.3 
      @tarojs/webpack-runner: 3.3.3 => 3.3.3 
      babel-preset-taro: 3.3.3 => 3.3.3 
      eslint-config-taro: 3.3.3 => 3.3.3 
      eslint-plugin-taro: 3.3.3 => 3.3.3 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: ^17.0.2 => 17.0.2 
```

**Comment by maimai123** [comment]
![image](https://user-images.githubusercontent.com/15125340/130383298-ae31e844-9402-47c9-940c-3076a9adac89.png)
我这个是什么原因啊 启动倒是成功的 但是用钉钉小程序打开项目就是这样的

**Comment by maimai123** [comment]
> ### 相关平台
> 支付宝小程序
> 
> ### 复现仓库
> https://gitee.com/aofong/taro3demo
> **小程序基础库: Lyra Version: 6.0.14**
> **使用框架: React**
> 
> ### 复现步骤
> 1 拉取示例代码
> 2 执行 yarn dev:dd 指令
> 3 钉钉开发工具打开编译后的项目
> 
> ### 期望结果
> 可以正常运行
> 
> ### 实际结果
> #### 编译错误
> ```
> 编译  发现入口  src/app.js
> 编译  发现页面  src/pages/index/index.jsx
> ⚠️  编译警告. 2021-8-18 6:01:22 ├F10: PM┤
> 
> ./node_modules/@tarojs/plugin-platform-alipay-dd/dist/runtime.js 9:56-69
> " '@tarojs/plugin-platform-alipay/dist/runtime-utils' does not contain an export named 'noPromiseApis'.
> ```
> 
> #### 开发工具错误
> ```
> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> ```
> 
> ### 环境信息
> ```
> Taro v3.3.3
> 
> 
>   Taro CLI 3.3.3 environment info:
>     System:
>       OS: macOS 11.5.2
>       Shell: 5.8 - /bin/zsh
>     Binaries:
>       Node: 12.18.3 - /var/folders/kz/89v1l75n3ylgtv2h74xd7zhc0000gn/T/yarn--1629281376408-0.9870242833913025/node
>       Yarn: 1.22.4 - /var/folders/kz/89v1l75n3ylgtv2h74xd7zhc0000gn/T/yarn--1629281376408-0.9870242833913025/yarn
>       npm: 6.14.6 - /usr/local/bin/npm
>     npmPackages:
>       @tarojs/cli: 3.3.3 => 3.3.3 
>       @tarojs/components: 3.3.3 => 3.3.3 
>       @tarojs/mini-runner: 3.3.3 => 3.3.3 
>       @tarojs/react: 3.3.3 => 3.3.3 
>       @tarojs/runtime: 3.3.3 => 3.3.3 
>       @tarojs/taro: 3.3.3 => 3.3.3 
>       @tarojs/webpack-runner: 3.3.3 => 3.3.3 
>       babel-preset-taro: 3.3.3 => 3.3.3 
>       eslint-config-taro: 3.3.3 => 3.3.3 
>       eslint-plugin-taro: 3.3.3 => 3.3.3 
>       nerv-devtools: ^1.5.7 => 1.5.7 
>       nervjs: ^1.5.7 => 1.5.7 
>       react: ^17.0.2 => 17.0.2 
> ```

你的问题解决了吗？

**Comment by aofong** [comment]
@maimai123 没有

**Comment by maimai123** [comment]
> @maimai123 没有

那...用原生开发钉钉小程序了吗？

**Comment by Chen-jj** [comment]
已修复钉钉小程序插件 [@tarojs/plugin-platform-alipay-dd](https://github.com/NervJS/taro-plugin-platform-alipay-dd)，请注意它有以下版本要求：

## 版本要求

### Taro 3.3.8+

请使用 `@tarojs/plugin-platform-alipay-dd` 插件的 `~0.1.0` 版本

### Taro 3.1 & 3.2

请使用 `@tarojs/plugin-platform-alipay-dd` 插件的 `~0.0.5` 版本
