### ISSUE TITLE
Taro3 Vue无法触发touchstart、touchcancel事件

### ISSUE THREAD

**Issue by x3852** [NervJS/taro#10074]
### 相关平台
微信小程序

**小程序基础库: 2.19.1**
**使用框架: Vue 2**

### 复现步骤
<button @touchstart="onTouchstart">按钮</button>
export default {
 methods: {
  onTouchstart(){
  //touchstart事件无法触发
  console.log('touchstart')
  }
 }
}

### 期望结果
touchstart可以触发

### 实际结果
touchstart无法触发

### 环境信息
```
  Taro CLI 3.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.3 - C:\Program Files\nodejs\npm.CMD
```

**Comment by yijinc** [comment]
最新版本还是碰到这个问题

**Comment by Chen-jj** [comment]
@yijinc 重新提一下 issue，并附上 demo 咯

**Comment by yijinc** [comment]
找到原因了
vue jsx 事件是 `onTouchstart `
react 事件 是 `onTouchStart `
大小写问题😂
