### ISSUE TITLE
canvas className 打包后丢失

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#1008]
**问题描述**
canvas className 打包后丢失

打包前

```jsx
 <canvas
   canvas-id='canvas'
   className='canvas'
/>
```

打包后

![image](https://user-images.githubusercontent.com/7480381/48038844-667f2300-e1ad-11e8-83e4-53f75cfccab0.png)

**期望行为**
正常

**系统信息**

 - 操作系统: [macOS 10.13.3]
 - Taro 版本 [v.1.1.0]
 - Node.js 版本 [v8.11.3]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
`Canvas` 大写

**Comment by youngluo** [comment]
😄
