### ISSUE TITLE
怎么设置本地png图片怎么在map中作为marker不转为base64 

### ISSUE THREAD

**Issue by liuxuerong** [NervJS/taro#10091]
### 这个特性解决了什么问题？
小程序的地图自定义的标记使用本地图片在安卓和ios不显示，只有模拟器显示

### 这个 API 长什么样？
无

**Comment by TomVista** [comment]
图片放到 ``yourPtah/images`` 下

配置 ``root/config/index``
```
copy: {
    patterns: [
      {
        from: 'yourPtah/images',
        to: `dist/${process.env.TARO_ENV}/images` // 对应小程序静态资源地址
      },
    ]
  },
```
得到下面这样一个目录
```
mini-root
...
-images
 -icon.png
```

在mark中使用 绝对路径 ``images/icon.png``

**Comment by konka-king** [comment]
可以 通过 imageUrlLoaderOption 配置 ，超过 大小的图片 不转为 base64
