### ISSUE TITLE
使用getBackgroundAudioManager后，ios端input拼音会重置

### ISSUE THREAD

**Issue by saopao** [NervJS/taro#10096]
### 相关平台
微信小程序

**小程序基础库: 2.19.1**
**使用框架: React**

### 复现步骤
基本信息：微信版本8.0.10，基础调试库版本2.19.1，机型为所有ios手机，输入法为ios原生输入法。

涉及组件或api：Taro.getBackgroundAudioManager，原生Input标签。

流程：音频播放页使用Taro.getBackgroundAudioManager支持后台播放api，音频播放过程中，在input输入数字、字母等暂时没问题，但是输入拼音打字的话，会在0.5秒的时间里重置输入的拼音，然后继续输入数字或字母，input标签的onChange事件就无法生效了。如果说getBackgroundAudioManager这个api触发了同步操作导致重置了输入拼音这个操作，那也不至于input标签的onChange时间失效啊。所以想请问下官方，这是问题是什么导致的？应该怎么解决呢？谢谢~

### 期望结果
期望音频文件在后台播放时，input组件输入拼音打字正常

### 实际结果
音频文件在后台播放时，input组件输入拼音停顿0.5秒后会重置拼音

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8
      @tarojs/components: 3.2.8 => 3.2.8
      @tarojs/mini-runner: 3.2.8 => 3.2.8
      @tarojs/react: 3.2.8 => 3.2.8
      @tarojs/runtime: 3.2.8 => 3.2.8
      @tarojs/taro: 3.2.8 => 3.2.8
      @tarojs/webpack-runner: 3.2.8 => 3.2.8
      babel-preset-taro: 3.2.8 => 3.2.8
      eslint-config-taro: 3.2.8 => 3.2.8
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

**Comment by Chen-jj** [comment]
@saopao 试试原生写法有没有相同问题
