### ISSUE TITLE
swiper Cannot read property 'disconnect' of undefined

### ISSUE THREAD

**Issue by wujiantao123** [NervJS/taro#10090]
### 相关平台
H5

**浏览器版本: 版本 92.0.4515.131（正式版本） (arm64)**
**使用框架: React**

### 复现步骤
A页面（有swiper）渲染完成，跳转到B页面，返回A时出错

### 期望结果
没有错误

### 实际结果
TypeError: Cannot read property 'disconnect' of undefined
    at e.disconnectedCallback (51.js:2)
    at safeCall (app.js:2)
    at app.js:2
    at app.js:2
    at Object.jmp (app.js:2)
    at HTMLElement.t.disconnectedCallback (app.js:2)
    at cj (app.js:2)
    at dk (app.js:2)
    at m.unstable_runWithPriority (app.js:2)
    at gg (app.js:2) undefined

### 环境信息
```
$ taro info
👽 Taro v3.3.1


  Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.13.0 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/cli: ^3.3.3 => 3.3.3
      @tarojs/components: 3.3.2 => 3.3.2
      @tarojs/mini-runner: 3.3.2 => 3.3.2
      @tarojs/react: 3.3.2 => 3.3.2
      @tarojs/runtime: 3.3.2 => 3.3.2
      @tarojs/taro: 3.3.2 => 3.3.2
      @tarojs/webpack-runner: 3.3.2 => 3.3.2
      babel-preset-taro: 3.3.2 => 3.3.2
      eslint-config-taro: 3.3.2 => 3.3.2
      react: ^17.0.0 => 17.0.2
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10

```

**Comment by Chen-jj** [comment]
3.3.6 已修复
