### ISSUE TITLE
是否支持webview？

### ISSUE THREAD

**Issue by emmaplus** [NervJS/taro#101]
在部分页面使用h5写的时候，小程序中需要使用webview，而在h5中可直接使用

**Comment by luckyadam** [comment]
支持

**Comment by buhe** [comment]
没看见组件中有 webview

**Comment by yuche** [comment]
@buhe 小程序原生有的组件直接用就是了，哪怕文档里没有或者 typing 里没有都没关系

**Comment by buhe** [comment]
小程序里面是 web-view 这种，我用是 WebView 还是 web-view 呢？

**Comment by zacksleo** [comment]
@buhe  WebView

**Comment by AibiTi** [comment]
TS，WebView 报红线。

**Comment by luckyadam** [comment]
@AibiTi 确实，@tarojs/components 缺少了 WebView 的声明文件，可以提个 PR 么

**Comment by xgqfrms** [comment]
# WebView

https://nervjs.github.io/taro/docs/components/open/web-view.html

> full-page iframe bug

```jsx
<WebView src={url} onMessage={this.handleMessage} />

```
