### ISSUE TITLE
scroll-view开启下拉刷新，但是无法触发

### ISSUE THREAD

**Issue by YongHengFu** [NervJS/taro#10113]
### 相关平台
微信小程序

**小程序基础库: 2.19.2**
**使用框架: Vue 3**

### 复现步骤
scroll-view开启下拉刷新，但是无法触发

    <scroll-view
      :scroll-y="true"
      :refresher-enabled="true"
      :refresher-threshold="5"
      style="height: 600px"
      :refresher-triggered="refreshState"
      @refresherRefresh="refresh"
    >

.........

    const refresh = (e) => {
      Taro.showToast({
        title: '开始刷新',
        icon: 'none',
        duration: 1000
      })
      console.log(e)
    }

### 期望结果
能够触发@refresherRefresh

### 实际结果
无法触发@refresherRefresh

### 环境信息
```
� Taro v3.3.2


  Taro CLI 3.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - E:\Install\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\FuYH\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - E:\Install\nodejs\npm.CMD

```

**Comment by YongHengFu** [comment]
下拉的圆点能出来，但是绑定的方法无法触发
![image](https://user-images.githubusercontent.com/77085439/130635752-1d63273d-f5ed-42ae-835b-e13d8ce0ee38.png)

**Comment by YongHengFu** [comment]
以下方法全部无法触发，但是onScroll可以正常触发
![image](https://user-images.githubusercontent.com/77085439/130636084-b27e6396-9969-4d91-8c4c-33f04d0ef284.png)

**Comment by YongHengFu** [comment]
对了，我在项目中使用了html标签
`  plugins: ['@tarojs/plugin-html'],`

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/130718023-da527989-21a6-489e-9985-0d1fcfbeaba1.png)

**Comment by YongHengFu** [comment]
使用的就是@符号
`@refresherRefresh="refresh"`

**Comment by Chen-jj** [comment]
`@refresher-refresh`

**Comment by YongHengFu** [comment]
`@refresher-refresh` 还是无法触发呀大佬

**Comment by YongHengFu** [comment]
@Chen-jj 
‘@scroll’可以正常触发，`@refresher-refresh`不行

**Comment by Chen-jj** [comment]
> `@refresher-refresh` 还是无法触发呀大佬

回复错了。

---

Taro 文档写得好清楚了，`@` 代替 `bind`

![image](https://user-images.githubusercontent.com/11807297/130718930-0e1737ae-bdd3-4f43-9429-6547f83abaf0.png)

**Comment by YongHengFu** [comment]
抱歉，光看Taro的组件文档了，没考虑到大小写的敏感性，`@refresherrefresh`就可以了，感谢大佬！
![image](https://user-images.githubusercontent.com/77085439/130719251-099fa5b7-3450-401d-bb44-28bec73b6557.png)
