### ISSUE TITLE
react native 希望支持动态设置首页(第一个打开的页面)

### ISSUE THREAD

**Issue by gaoxianglyx** [NervJS/taro#10116]
### 这个特性解决了什么问题？
当我们从native跳转到RN页面，会给bundle添加参数，希望在RN侧根据参数来跳转不同的页面
但是在taro里面始终是跳转的app.config.js中注册的第一个页面
我尝试在app.js的componentWillMount调用Taro.navigateTo跳转，是无效的，需要手动延迟才能跳转

### 这个 API 长什么样？
可以在app.js中，能拿到props(props中包含了通过native打开RN时带的参数)的位置，设置加载的页面

**Comment by iChengbo** [comment]
@gaoxianglyx  可以将 `app.config.js` 中注册的第一个页面 当做`中间页`，在 `componentDidMount` 中解析参数，然后通过 Taro.redirectTo 跳转至想要展示的页面
```js
class IndexPage extends Taro.Component {
  componentDidMount() {
      // 1、解析参数
      // 2、跳转
     Taro.redirectTo({ url: 'xxxxxx' })
  }
  render() {
    return null;
  }
}
```

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-react-native/issues/143

**Comment by gaoxianglyx** [comment]
> @gaoxianglyx 可以将 `app.config.js` 中注册的第一个页面 当做`中间页`，在 `componentDidMount` 中解析参数，然后通过 Taro.redirectTo 跳转至想要展示的页面
> 
> ```js
> class IndexPage extends Taro.Component {
>   componentDidMount() {
>       // 1、解析参数
>       // 2、跳转
>      Taro.redirectTo({ url: 'xxxxxx' })
>   }
>   render() {
>     return null;
>   }
> }
> ```

感谢，我在componentDidMount和componentWillMount周期都测试过
无法用在同步任务中使用Taro. redirectTo跳转
只能延迟一段时间（我的机型大概50ms）后，跳转才能生效，
这个方案也不可行，无法保证所有机型都能在一个固定的延迟后跳转

**Comment by iChengbo** [comment]
@gaoxianglyx  加个 async componentDidMount, await 获取初始化参数，然后再跳转呢？

**Comment by gaoxianglyx** [comment]
> @gaoxianglyx 加个 async componentDidMount, await 获取初始化参数，然后再跳转呢？
加async也不可行，楼上58哥们儿的是官方解决方案，经测试可以走通

**Comment by gaoxianglyx** [comment]
> [wuba#143](https://github.com/wuba/taro-react-native/issues/143)
> 
> 试试这个方案

成功了，起飞
