### ISSUE TITLE
Taro3.x   vue3 支持微信小程序的全局onError错误捕获吗?

### ISSUE THREAD

**Issue by Axpoii** [NervJS/taro#10112]
### 这个特性解决了什么问题？
原生小程序未捕获到的错误，都会走到全局的onError，但在vue3的createApp里注册onError并不生效。

### 这个 API 长什么样？
全局的onError可以捕获到错误

**Comment by TomVista** [comment]
用taro.onError 代替把,需要自行补充一下ts类型
```
onError(String error)
小程序发生脚本错误或 API 调用报错时触发。也可以使用 wx.onError 绑定监听。

参数：与 wx.onError 一致

```
