### ISSUE TITLE
微信小程序 第一次进入列表，componentdidmount执行获取数据，返回列表重新进入详情 不执行componentdidmount

### ISSUE THREAD

**Issue by 616151371** [NervJS/taro#10126]
### 这个特性解决了什么问题？
微信小程序 第一次进入列表，componentdidmount执行获取数据，返回列表重新进入详情 不执行componentdidmount

### 这个 API 长什么样？
重新进入详情页，执行componentdidmount

**Comment by Chen-jj** [comment]
请选择 bug report 的 issue 模板重新提交
