### ISSUE TITLE
最新版本3.3.4,  启动项目报错 ReferenceError ENABLE_INNER_HTML is not defined

### ISSUE THREAD

**Issue by wylyzyk** [NervJS/taro#10124]
### 相关平台
H5

**浏览器版本: Chrome92**
**使用框架: React**

### 复现步骤
- npm安装最新版 taro/cli
- taro init myApp
     拉取模板选择 gitee/ github
-  cd myApp
-  启动项目 yarn dev:h5

> 报错 ReferenceError  ENABLE_INNER_HTML is not defined

### 期望结果
页面正常渲染 Hello, world!

### 实际结果
ReferenceError  ENABLE_INNER_HTML is not defined

### 环境信息
```
👽 Taro v3.3.4


  Taro CLI 3.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\xxx\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Ashira97** [comment]
taro版本3.3.12 引入taro-ui时遇到这个错误
