### ISSUE TITLE
vite支持

### ISSUE THREAD

**Issue by JakeWoki** [NervJS/taro#10125]
### 这个特性解决了什么问题？
加快打包时间

### 这个 API 长什么样？
使用vite构建项目

**Comment by jinglun2019** [comment]
还是没有计划吗

**Comment by aolsx** [comment]
vite 开发&打包速度很快 为何不支持呢？

**Comment by Silentdoer** [comment]
希望到时候也是支持vite创建的vue3项目模板，比如是main.ts而非app.ts

**Comment by GideonSenku** [comment]
有预期时间点吗？

**Comment by yaaliuzhipeng** [comment]
3.6 canary4.0都发布了，还没支持vite。所以是准备将支持vite计划改到3.7版本吗？

**Comment by aolsx** [comment]
+1

**Comment by social-uni** [comment]
预计哪个版本会支持vite，可否公开下

**Comment by youmengme** [comment]
预计哪个版本会支持vite，可否公开下

**Comment by Chen-jj** [comment]
预计是 v3.7，关于实现细节的讨论在：https://github.com/NervJS/taro-rfcs/pull/18，分支在 https://github.com/NervJS/taro/tree/feat/3.7-vite

最近事情较多，迭代速度较为缓慢

**Comment by AkashiGakki** [comment]
预计3.7什么时候发布啊

**Comment by jesse-tang-93** [comment]
期待 3.7 上 vite 。 webpack 实在是太慢了 o(╥﹏╥)o

**Comment by ZakaryCode** [comment]
@reed-fea 负责的小伙伴说会在国庆之后

https://github.com/NervJS/taro/issues/14600#issue-1910960042

**Comment by pengxianggui** [comment]
> @reed-fea 负责的小伙伴说会在国庆之后，可以关注 feat/3.7 分支的情况
> 
> [#14600 (comment)](https://github.com/NervJS/taro/issues/14600#issue-1910960042)

已经快12月了, 3.7还没发布呢..

**Comment by cloydlau** [comment]
feat/3.7 分支已经7个月没更新了

**Comment by coyzeng** [comment]
希望能加快进度，期待

**Comment by iwansf** [comment]
奉劝各位一句 taro 顶多是一个小程序框架，非支持H5 ， 不要把时间压在这种kpi作品中 你有那个时间使用原生 来开发多端足够富裕

**Comment by Miofly** [comment]
@这个还没有发布吗

**Comment by transtone** [comment]
https://github.com/NervJS/taro/tree/feat/3.7-vite 这个分支最后一次更新已经是10月前了。估计是没什么心思在这上面了。

**Comment by muzaisimao** [comment]
> https://github.com/NervJS/taro/tree/feat/3.7-vite 这个分支最后一次更新已经是10月前了。估计是没什么心思在这上面了。

Taro 4.0 支持 Vite了, 已经发布 Beta 版可以试用了.
https://mp.weixin.qq.com/s?__biz=MzU3NDkzMTI3MA==&mid=2247486026&idx=1&sn=64b852442e66fbd30545acba02db8e8b

**Comment by ianzone** [comment]
> > https://github.com/NervJS/taro/tree/feat/3.7-vite 这个分支最后一次更新已经是10月前了。估计是没什么心思在这上面了。
> 
> Taro 4.0 支持 Vite了, 已经发布 Beta 版可以试用了. https://mp.weixin.qq.com/s?__biz=MzU3NDkzMTI3MA==&mid=2247486026&idx=1&sn=64b852442e66fbd30545acba02db8e8b

官方模板都跑不起来。
