### ISSUE TITLE
h5的swiper增加circular属性之后第一页图片一直闪屏

### ISSUE THREAD

**Issue by webyushao** [NervJS/taro#10151]
### 相关平台
微信小程序

### 复现仓库
[https://git.longhu.net/lzyx/rivendell](https://git.longhu.net/lzyx/rivendell)
**小程序基础库: 2.17.0**
**使用框架: Vue 2**

### 复现步骤
进入页面，

### 期望结果
正常轮播

### 实际结果
第一张图片闪屏

### 环境信息
```
Taro CLI 3.3.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
      npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.3 => 3.3.3
      @tarojs/mini-runner: 3.3.3 => 3.3.3
      @tarojs/runtime: 3.3.3 => 3.3.3
      @tarojs/taro: 3.3.3 => 3.3.3
      @tarojs/webpack-runner: 3.3.3 => 3.3.3
      babel-preset-taro: 3.3.3 => 3.3.3
      eslint-config-taro: 3.3.3 => 3.3.3
```

---
### 补充信息
<swiper
          :autoplay="true"
          :interval="3000"
          :duration="1000"
          class="carousel"
          circular
          @change='swiperChange'
        >
          <swiper-item
            v-for="(item, index) in goodsDetail.goodImageList"
            :key="index">
            
            <image :src='item' class='slide-image' style='width: 100%; height: 100%'/>
          </swiper-item>
        </swiper>

**Comment by liweijian1** [comment]
解决了吗，我也遇到了

**Comment by webyushao** [comment]
还没



在 2021-09-15 15:04:04，"liweijian" ***@***.***> 写道：

解决了吗，我也遇到了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dolphin0618** [comment]
不断的刷新dom，开启disable cache轮播图片会重复加载

**Comment by ZakaryCode** [comment]
> 这个问题是必现的，而且很容易发现，因为一般 swiper 会用于显示 banner，而 banner 一般显示在首页的显目位置，简直闪瞎了

测试的时候请关掉“禁用缓存”

**Comment by webyushao** [comment]
请问禁用缓存是什么意思？

**Comment by webyushao** [comment]
> > 这个问题是必现的，而且很容易发现，因为一般 swiper 会用于显示 banner，而 banner 一般显示在首页的显目位置，简直闪瞎了
> 
> 测试的时候请关掉“禁用缓存”

请问禁用缓存是什么意思？

**Comment by yang131323** [comment]
> > 这个问题是必现的，而且很容易发现，因为一般 swiper 会用于显示 banner，而 banner 一般显示在首页的显目位置，简直闪瞎了
> 
> 测试的时候请关掉“禁用缓存”

这样只是解决了图片重复请求的问题，问题的本质是swiper dom一直再刷新，这样非常影响页面性能；图片走缓存没有请求，但是整个swiper一直在重复渲染，没有解决swiper的问题

**Comment by songwenhui** [comment]
这个问题有解决吗？

**Comment by toFrankie** [comment]
+10086

**Comment by jiangjiaxing** [comment]
问题解决了吗
