### ISSUE TITLE
父子传值不了 子组件无法接受父组件的传值 文档也没写

### ISSUE THREAD

**Issue by dreamsBig** [NervJS/taro#10159]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:dreamsBig/myApp.git](git@github.com:dreamsBig/myApp.git)
**小程序基础库: 2.19.2**
**使用框架: React**

### 复现步骤
简单的父子组件传值 父组件无法接收子组件传值

### 期望结果
解决父子传值，并告诉方法

### 实际结果
解决父子传值，并告诉方法

### 环境信息
```
Taro CLI 1.2.0-beta.9 environment info:

```

**Comment by luckyadam** [comment]
麻烦使用最新版本

**Comment by dreamsBig** [comment]
好的
