### ISSUE TITLE
Taro 3.3.3  Taro.navigateTo没有触发页面更新, 只有地址栏发生了变化

### ISSUE THREAD

**Issue by mengxin-FE** [NervJS/taro#10158]
### 相关平台
H5

**浏览器版本: chrome70**
**使用框架: React**

### 复现步骤
taro init react-redux模板项目

在pages/index.jsx中编写

componentDidMount (){
      Taro.navigateTo({
        url: '../games/index/index',
      })
  }

### 期望结果
页面URL变化，页面更新

### 实际结果
仅URL发生了变化，页面没有更新

### 环境信息
```
Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\ProgramFiles\NodeJS\node.EXE
      Yarn: 1.22.11 - C:\Users\chenwm\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.6 - D:\ProgramFiles\NodeJS\npm.CMD
```

**Comment by Chen-jj** [comment]
之前为了解决频繁跳转会导致多个页面同时出现的问题，为跳转方法做了 500ms 节流：#10004 

这种情况暂时可以通过设置一个延时来解决：

```js
componentDidMount () {
  setTimeout(() => {
    Taro.navigateTo({
      url: '/pages/games/index',
      })
  }, 550)
}
```
