### ISSUE TITLE
taro-component 的一系列问题

### ISSUE THREAD

**Issue by SzHeJason** [NervJS/taro#1016]
**问题描述**
在使用 `ts` 写组件的时候遇到了很多问题 都有解决方案 但是体验不好 下面列一个清单 有机会的话我也会提交PR

- [x] picker[mode=date] 返回值不一样 一个数组(H5) 一个字符串(wxapp)
- [x] 对于事件的 `d.ts` 文档不够完善需要用户自己扩展,主要是 `detail` 是一个简单的 `Object` 类型
- [x] H5 下 Swipe 在复杂场景下面无法使用 例如 循环遍历 SwipeItem ，另 current-item-id 属性没有加上
- [x] ITouchEvent 的 `d.ts` 对于 `changedTouches` 的描述有误
- [x] `onLongClick` 事件没有在 `H5` 上面支持
- [x] picker[mode=date] 对于 `start` 和 `end` 的处理不正确(H5)

其中 `3` 和 `4` 只是编程体验问题 能加上固然最好

**系统信息**

 - 操作系统: MacOS
 - Taro 版本: 1.1.0
 - Node.js 版本: 10.0.0

**Comment by jinjinjin0731** [comment]
ok~ 尽快修复~

**Comment by jinjinjin0731** [comment]
ok
