### ISSUE TITLE
vue3 jsx 没有编译对应的h5标签

### ISSUE THREAD

**Issue by zybieku** [NervJS/taro#10160]
### 相关平台
H5

**浏览器版本: Chrome 91**
**使用框架: Vue 3**

### 复现步骤
1- 使用taro官方的模板，选择 vue3 nutui    
2-  打开index.vue  
     在setup中return jsx语法

``` 
    return () => (
      <view class="login">
        <view class="header">
          <image src={bg_login_header} class="header_bg"></image>
          <image src={ic_logo} class="logo"></image>
          <text class="title">测试</text>
          <text class="title_type">测试</text>
        </view>
        <nut-button class="login-btn" type="primary" onClick={handleClick}>
          登录
        </nut-button>
      </view>
    );
``` 

### 期望结果
view -> taro-view-core  
text     ->taro-text -core  
image  -> taro-image-core   

### 实际结果
view 在h5渲染的还是view   
image 渲染的还是  image    
没有div 也没有img  
导致页面显示不正常    

### 环境信息
```
Taro CLI 3.3.5 environment info:
    System:
      OS: window 10
     
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.5 => 3.3.5 
      @tarojs/mini-runner: 3.3.5 => 3.3.5 
      @tarojs/runtime: 3.3.5 => 3.3.5 
      @tarojs/taro: 3.3.5 => 3.3.5 
      @tarojs/webpack-runner: 3.3.5 => 3.3.5 
      babel-preset-taro: 3.3.5 => 3.3.5 
      eslint-config-taro: 3.3.5 => 3.3.5 
```

---
### 补充信息
vue3中配合composable 抽离逻辑 return jsx 真的比react还方便，期望可以支持

**Comment by Ttou** [comment]
已知问题，可以参考这个[项目](https://gitee.com/jh_shot/taro-legacy-template)，主要是改 `dist-h5-vue.js` 和 `config/index.js`，等官方改了就可以不用这些配置了

**Comment by zybieku** [comment]
收到，谢谢，已解决 ！
template模式 正常， 我自己用template语法 给用到的组件再封装一次，再用jsx调用也是可以的
还可以做一些自己定制的操作

**Comment by Ttou** [comment]
@zybieku 出于兼容性的考虑

**Comment by ZakaryCode** [comment]
3.5+ 版本中，通过 `postcss-html-transform` 提供默认配置
