### ISSUE TITLE
请问下有没有 一个可以自定义hooks的方法

### ISSUE THREAD

**Issue by zhouzyc** [NervJS/taro#10169]
### 这个特性解决了什么问题？
我使用的版本是1.3.x，
现在业务需要使用分享朋友圈功能，
hooks中无法找到onShareTimeline使用方法，
请问有没有办法让我自定义一个hooks，
或者其他办法能在hooks中用原生wx.onShareTimeline

### 这个 API 长什么样？
期望实现分享朋友圈

**Comment by Chen-jj** [comment]
@zhouzyc 可以参考其它生命周期方法去实现一个，然后提 PR 咯
