### ISSUE TITLE
支持wx.openCustomerServiceChat

### ISSUE THREAD

**Issue by chenzhaozheng** [NervJS/taro#10177]
### 这个特性解决了什么问题？
微信客服功能
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/service-chat/wx.openCustomerServiceChat.html

### 这个 API 长什么样？
Taro.openCustomerServiceChat({
  extInfo: {url: ''},
  corpId: '',
  success(res) {}
})

**Comment by chenzhaozheng** [comment]
![image](https://user-images.githubusercontent.com/5388869/132206576-e7189da8-2d84-4556-87c8-896eccfd0509.png)
升级到了3.3.6了，还是没找到该方法是因为什么原因呢？
![image](https://user-images.githubusercontent.com/5388869/132206630-94b259aa-79ef-426f-aa3b-e1ca5c0bc42b.png)

**Comment by Chen-jj** [comment]
只是没有类型，可以用的，类型可以给我们提个 PR 咯

**Comment by chenzhaozheng** [comment]
我还以为一起更新了，嗯嗯

**Comment by chenzhaozheng** [comment]
> 只是没有类型，可以用的，类型可以给我们提个 PR 咯

https://github.com/NervJS/taro/issues/10226
