### ISSUE TITLE
百度小程序 onRegionChange 不生效

### ISSUE THREAD

**Issue by songwenhui** [NervJS/taro#10185]
### 相关平台
百度小程序

### 复现仓库
[https://github.com/songwenhui/taro-test.git](https://github.com/songwenhui/taro-test.git)
**小程序基础库: 3.320.33**
**使用框架: React**

### 复现步骤
拖动地图onRegionChange方法未执行

### 期望结果
onRegionChange方法应该执行

### 实际结果
onRegionChange方法未执行

### 环境信息
```
👽 Taro v3.3.5


  Taro CLI 3.3.5 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
```

**Comment by Chen-jj** [comment]
百度的 `bindRegionChange` 和微信、支付宝的实现有点不一样。后两个小程序中，会触发两次，`type` 分别是 `begin` 和 `end` 。

因此在百度中，当事件的 `type` 为 `bindregionchange` 时，Taro 需要映射为 `end`。
