### ISSUE TITLE
不支持 yarn workspaces

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#1018]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
当项目启用 yarn workspaces 时, 所有的 npm 包都上移到根目录 node_modules. 此时编译结果中 `dist/npm/*` 放在了错误的目录, 程序中引用路径也变成了 `../../../npm/` 这样.

**复现步骤**
[复现问题的步骤]
1. 新建一个 mono 项目
package.json
```json
{
    "workspaces": {
        "packages": [
            "packages/*"
        ]
    }
}
```
2. 把 taro 生成的项目复制到 `./packages/demo` 里.
3. 运行 `yarn`, 此时 packages 目录下各子项目的 npm 都会集中在 `./node_modules` 一个文件夹里.
4. 在 `./packages/demo` 中运行 `taro build --type weapp --watch`

生成的结果为:
```
.
├── dist
│   └── npm
├── node_modules
├── packages
│   ├── demo
│   │   ├── dist
│   │   │   └── app.js
```

app.js 里会出现这样的引用 `require("../../../dist/npm/@tarojs/async-await/index.js")`

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. OSX]
 - Taro 版本 [e.g. v.1.1.1]
 - Node.js 版本 [e.g. v11.0.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by cncolder** [comment]
我觉得标签 enhancement 不合适, npm 依赖应该永远和其他文件打包在一起, 以 node_modules 来判断相对路径是不对的.

一个临时的解决方案:

yarn workspaces 配置
```json
    "workspaces": {
        "packages": [
            "packages/*"
        ],
        "nohoist": [
            "@myscope/miniprogram/**"
        ]
    },
```

其中 `@myscope/miniprogram` 是你的小程序包名称, 也就是 `./packages/miniprogram/package.json` 里面的 name 字段.

这样一来运行 yarn install, 其他子项目的 node_modules 都上移到根目录, 只有 miniprogram 的 node_modules 单独留在 `./packages/miniprogram/node_modules` 下面.

**Comment by luckyadam** [comment]
已经支持，在 `config/index.js` 的 `weapp` 中增加配置如下

```js
const config = {
  weapp: {
    npm: {
      dir: '../dist'
    }
  }
}
```

**Comment by cncolder** [comment]
已解决, 只是感觉上有点不对, 但是可用.

**Comment by cncolder** [comment]
这个解决方案不兼容 taro-ui

**Comment by luckyadam** [comment]
@cncolder 收到，我看下

**Comment by WingGao** [comment]
目前还有问题，用的是lerna来组织代码，然后生成了如下目录
```
.
├── npm
│   ├── .......
├── node_modules
├── packages
│   ├── demo
│   │   ├── dist
│   │   │   └── app.js
```
然后小程序里被翻译成了
```js
require("../../../node_modules/@tarojs/async-await/index.js");
```
报错`can't find module : ../../../node_modules/@tarojs/async-await/index.js `

**Comment by Stupidism** [comment]
@WingGao  请问有解决方案了吗

**Comment by WingGao** [comment]
@Stupidism  目前通过软连接到src下来支持（因为taro对于外部js处理比较诡异）
```
.
├── npm
│   ├── .......
├── node_modules
├── packages
│   ├── pak1
│   │   ├── a.tsx
│   ├── demo-app
│   │   ├── src
│   │   │   ├── @mypack
│   │   │   │  ├── pak1 --> ../../../pak1 （软连接）
│   │   │   ├── app.tsx
```
然后修改config: 
```js
//config/index.js
...
  alias: {
    // 如果是ts，确保目录内没有编译过的js文件
    '@mypack': path.resolve(__dirname,'../src/@mypack')
  },
...
```
在taro的其他文件里就正常写就行，比如
```ts
// app.tsx
import MyFunc from '@mypack/pak1'
...
```
**但是注意**，在`pak1`里如果要引用其他`packages`下的包比如
```ts
// pak1/b.ts
import MyFun2 from '@mypack/pak2'  // !不支持，要修改taro-cli代码
```
具体修改如下 https://github.com/WingGao/taro/commit/3d4f256c0d1a2cf77171666e381234d07229711f
，或者直接修改安装的`taro-cli`对于文件也可以。

**Comment by SolidZORO** [comment]
@WingGao 感觉这样还是很 hack，不好统一处理。

我也是 monorepo，发现 `npm` 目录 copy 行为有点不确定，有些包是可以被引入进来的，有些不行。具体是通过什么判断的？能否有一个手动配置的白名单？ @luckyadam

**Comment by SolidZORO** [comment]
我最后还是写了个 `symlink.js` 文件，每次都跑在 dev:weapp 前面跑。开销还是蛮小的。大概是这样。因为这里是 monorepo，而且是 typescript 的 monorepo，我发现即便是我把文件丢进了 npm 目录，其实是 *.ts，这样微信是不认的，所以只好通过 symlink。

```javascript
const path = require('path');
const fs = require('fs');

const sourceDirPath = path.resolve(__dirname, '../_leaa-common/src');
const distDirPath = './src';

// prettier-ignore
const symlinkPaths = [
  'graphqls',
  // 'entrys',
];

symlinkPaths.forEach(path => {
  const sourcePath = `${sourceDirPath}/${path}`;
  const distPath = `${distDirPath}/${path}`;

  if (fs.existsSync(distPath)) {
    fs.unlinkSync(distPath);
  }

  console.log(`SYMLINK: ${sourcePath} --> ${distPath}`);

  fs.symlinkSync(sourcePath, distPath);
});

```

**Comment by SolidZORO** [comment]
具体文件和上下文： https://github.com/SolidZORO/leaa/blob/master/packages/leaa-miniprogram/symlink.js
