### ISSUE TITLE
想问下怎么实现SSR？

### ISSUE THREAD

**Issue by strange-fish** [NervJS/taro#10181]
### 这个特性解决了什么问题？
目前有需求将h5端改造成SSR，但官方目前好像没有实现的方案？

### 这个 API 长什么样？
希望可以提供具体实现或者新增一个SSR模式

**Comment by TomVista** [comment]
vue+node 可以直接用这个方案 [vue-server-renderer](https://ssr.vuejs.org/zh/guide/#%E5%AE%89%E8%A3%85)

react 我不熟,不过估计也有node 服务器的方案,

其他非node服务器,我没在生产环境上过,不太清楚,等待大佬拯救世界

**Comment by SyMind** [comment]
@strange-fish 你好，目前我正在做这方面的尝试，一个 Taro 插件，将 Next.js 作为 Taro 的一个目标 platform，以支持 SSR。

项目在这里：https://github.com/SyMind/tarojs-plugin-platform-nextjs

**Comment by TomVista** [comment]
https://docs.taro.zone/docs/prerender

**Comment by SyMind** [comment]
@TomVista 这是用于小程序端的预渲染，并非用于 Web 端的 SSR 方案。
