### ISSUE TITLE
官方模板无法编译成小程序端

### ISSUE THREAD

**Issue by txzh007** [NervJS/taro#10194]
### 相关平台
微信小程序

**小程序基础库: 2.19.2**
**使用框架: Vue 3**

### 复现步骤
taro init  xxx
选择 taro-nutUI模板
npm run dev:h5 (成功)
npm run dev:weapp(提示编译成功,小程序开发平台无法编译)

### 期望结果
编译成果可以预览小程序端

### 实际结果
小程序开发工具 预览时卡死

### 环境信息
```
👽 Taro v3.3.4


  Taro CLI 3.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.20.5 - C:\Program Files\nodejs\npm.CMD


```

**Comment by richard1015** [comment]
taro 3.3.5 + nutui 3.1.4  weapp 无法启动问题  ，辛苦先降级nutui 到 3.1.3 版本，这边正在紧急修复，今天发版

**Comment by richard1015** [comment]
已修复 ，请升级到 @nutui/nutui-taro@3.1.5
