### ISSUE TITLE
运行npm run dev:weapp报错UnhandledPromiseRejectionWarning: TypeError: Class extends

### ISSUE THREAD

**Issue by junxiaz** [NervJS/taro#10198]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
npm run dev:weapp

### 期望结果
项目正常运行

### 实际结果
myApp@1.0.0 dev:weapp
npm run build:weapp -- --watch

myApp@1.0.0 build:weapp
taro build --type weapp "--watch"

👽 Taro v3.0.11

(node:11492) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time
(node:11492) UnhandledPromiseRejectionWarning: TypeError: Class extends
value undefined is not a constructor or null
at Object. (D:\code\大大汽修小程序\qixiu_wxapp\node_modules_@tarojs_cli@3.0.11@@tarojs\cli\src\presets\platforms\weapp.ts:5:31)
at Module._compile (D:\code\大大汽修小程序\qixiu_wxapp\node_modules_pirates@4.0.1@pirates\lib\index.js:99:24)
at Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
e_modules_pirates@4.0.1@pirates\lib\index.js:104:7)
at Module.load (internal/modules/cjs/loader.js:1001:32)
at Function.Module._load (internal/modules/cjs/loader.js:900:14)
at Module.require (internal/modules/cjs/loader.js:1043:19)
at require (internal/modules/cjs/helpers.js:77:18)
at apply (D:\code\大大汽修小程序\qixiu_wxapp\node_modules_@tarojs_service@3.3.5@@tarojs\service\dist\utils\index.js:56:56)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled
with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11492) [DEP0018] DeprecationWarning: Unhandled promise rejections
are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
Taro CLI 3.3.0 environment info:
System:
OS: Windows 10
Binaries:
Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
npm: 7.21.1 - ~\AppData\Roaming\npm\npm.CMD
```

---
### 补充信息
ps:即使全局安装的@tarojs/cli与项目保持一致3.0.11或者最新的3.3.5依然报这个错误
奇怪的是依然能够重新初始化项目

**Comment by junxiaz** [comment]
通过将npm版本降低，降低成6.14.4之后运行成功的，但是对于问题发生的根本原因依然一知半解，现在成功运行的taro环境是
 Taro v3.3.0
(node:11776) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time
  Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - ~\AppData\Roaming\npm\npm.CMD

**Comment by Chen-jj** [comment]
提供一下 demo

**Comment by Iongtao** [comment]
我也遇到了同样的问题， 只有在run dev:weapp编译的时候出现这个问题 热重载又会好

**Comment by Iongtao** [comment]
> 通过将npm版本降低，降低成6.14.4之后运行成功的，但是对于问题发生的根本原因依然一知半解，现在成功运行的taro环境是 Taro v3.3.0 (node:11776) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time Taro CLI 3.3.0 environment info: System: OS: Windows 10 Binaries: Node: 12.16.0 - C:\Program Files\nodejs\node.EXE npm: 6.14.4 - ~\AppData\Roaming\npm\npm.CMD

只有降低node版本才有用吗

**Comment by BoomBooA** [comment]
我也遇到了，发现是一个正则表达式引起的

**Comment by junxiaz** [comment]
换成mac电脑初始化同一项目，使用同样的node、npm版本，但运行项目时还是报出同样的错误提示，依然没找到具体原因！！！

**Comment by junxiaz** [comment]
> > 通过将npm版本降低，降低成6.14.4之后运行成功的，但是对于问题发生的根本原因依然一知半解，现在成功运行的taro环境是 Taro v3.3.0 (node:11776) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time Taro CLI 3.3.0 environment info: System: OS: Windows 10 Binaries: Node: 12.16.0 - C:\Program Files\nodejs\node.EXE npm: 6.14.4 - ~\AppData\Roaming\npm\npm.CMD
> 
> 只有降低node版本才有用吗

上次在window电脑上是这样解决掉的，现在在mac上不知道如何解决了

**Comment by junxiaz** [comment]
> 我也遇到了，发现是一个正则表达式引起的

正则！？

**Comment by junxiaz** [comment]
mac解决过程总结(仅供参考，能力有限并不知其所以然)：
package.json中所有3.0.11统一替换成3.0.29（其实这次更改使用的方法至少升级到3.0.29才可以，索性就先升级了）
全局安装的tarojs/cli也升级成3.0.29
执行cnpm i => npm run dev:weapp
会提示设置framework（根据提示在config/index.js中设置framework:'react'）
然后编译成功！！！
此时环境：
项目tarojs/cli 3.0.29
全局tarojs/cli 3.0.29
node -v 12.16.0
npm -v 6.14.4

**Comment by BoomBooA** [comment]
> > 我也遇到了，发现是一个正则表达式引起的
> 
> 正则！？

嗯，当时是有一个校验文件名的正则表达式；没办法，我只能用其他方法实现了。
当时有更新过 Taro 到最新版本，但是没效果...
