### ISSUE TITLE
差评，开发体验不好！！

### ISSUE THREAD

**Issue by AibiTi** [NervJS/taro#102]
> Taro 是一套遵循 React 语法规范的 多端开发 解决方案。

看到这些 <b><s>坑</s></b> 错误，心好累，整个人都不好。说好的 “遵循 React 语法规范”，现在呢？

![e](https://user-images.githubusercontent.com/40224479/41329825-7b045980-6f02-11e8-8e10-ad2aee15b811.png)

![w](https://user-images.githubusercontent.com/40224479/41329831-82d11310-6f02-11e8-9c69-6ddbdd51c3f2.png)

![q](https://user-images.githubusercontent.com/40224479/41329834-8581a75a-6f02-11e8-97e4-23af19454aee.png)

![3](https://user-images.githubusercontent.com/40224479/41330269-1101035a-6f05-11e8-9e0b-ef452f705bcd.png)

![4](https://user-images.githubusercontent.com/40224479/41330272-17eb95c2-6f05-11e8-9979-9845b9b188ef.png)

![a](https://user-images.githubusercontent.com/40224479/41333185-75c9fc2a-6f13-11e8-9557-62984758c873.png)

**Comment by yuche** [comment]
后面两个在做支持，第一个没办法。

Taro 是一个约定优于配置的框架，在必要的情况应该给开发者一些约束，我并不认为无脑跪舔开发者是一个好的框架。

**Comment by zacksleo** [comment]
大部分坑应该归功于小程序吧 😞

**Comment by kdong007** [comment]
是的 小程序限制的不能动态生成节点 这个真不是taro或reat的错 只能怪腾讯太坑爹

相比mpvue和wepy 用类react的风格已经让你工作量轻松很多了 

而且taro可以在动态list生成的componet里让每个component自己去拥有和处理自己的state 这非常流弊了

你去写写wepy或者mpvue让你体会一下什么叫比吃屎还恶心

**Comment by kominsan** [comment]
楼主还是年轻啊 我写JAVA的 你知不知道按照阿里的JAVA规范 打一个log就有八条规则要遵守
按照楼主的逻辑 阿里的JAVA就不是JAVA了

**Comment by Lizhooh** [comment]
小程序略坑，小程序的自定义组件，大量参考 vue 的设计，但是对于属性来说既然不是用 props，而用 properties 。它不知道这写很费力吗。

**Comment by loveholly** [comment]
这哥们一上来就开喷，完全不是来讨论问题的啊

**Comment by ChiaJune** [comment]
不知道为啥，看到这种issue，脑壳青痛。

**Comment by AibiTi** [comment]
@loveholly 这算是喷？

**Comment by AibiTi** [comment]
@kdong007 我之前就是用 Wepy 的，体验还好，限制不多，你这形容也太假了吧。

**Comment by kdong007** [comment]
@AibiTi 你来个列表每个component自己管理10个state wepy恶心死你 果断弃坑来用taro

**Comment by colmugx** [comment]
菜不好吃不怪厨师怪送餐员系列

**Comment by AibiTi** [comment]
现在 **taro v1.0.0** 版本之后，离真正的 React 开发体验还差多少？ @yuche

**Comment by yuche** [comment]
@AibiTi 
这个取决于你如何定义「开发体验」和你对 React 的熟悉程度了。

如果你想写像 `react-motion` 那样的代码，例如把通过 `this.props` 传递的 JSX 元素当成一个对象处理，或者动态地修改组件构造器本身，在执行 `ref` 函数和生命周期方法之间写逻辑，那肯定是做不到的。真正的 React 和 Taro 最大的不同就是 React 各项的值是直到运行时才能知道。如果从这个纬度来说，除非小程序把他的 virtual-dom 接口开放出来，否则 Taro 永远都达不到 React 的开发体验。

但从另外一个方面讲，Taro 能让你在小程序中复用在 React 中的一些常用模式，也能得到编辑器和一些静态语言对 JSX 的补全和类型检查。从开发者技术栈的迁移成本和工具链的角度来讲，我认为 Taro 和 React 的体验并不差得太多。

**Comment by tiancheng2000** [comment]
大家别想多了，楼主是想来秀下avatar的😉

**Comment by leadream** [comment]
上来就差评，是给钱了么？

**Comment by oto456** [comment]
@kdong007 哥们，谢谢你，去用了下mpvue和wepy，果然真的比这个好用多了。谢谢你的推荐。

**Comment by kdong007** [comment]
@oto456 你去wepy看看issue就懂了 digest已经被刷屏多久了他们都不管 我们刚弃坑wepy 
就连他们的computed也能让你喝一壶的

**Comment by shiny** [comment]
![image](https://user-images.githubusercontent.com/117487/45680716-32549200-bb6e-11e8-8be7-ba15946cd656.png)

**Comment by wakaryry** [comment]
有些规则约束不是很正常的莫。
而且并没有限制住你的生产力啊。
