### ISSUE TITLE
npm引入有问题

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#1021]
**问题描述**
近期项目里有些功能，需要引入一些npm包来实现，然后发现在引npm包的时候有一个问题，
引进来的npm包，这个包内部再引用了其他包的话，其他的包并没有引用成功。￼￼￼

*复现步骤**

```js
npm install websocket-nats

// 在页面引用
import NATS from 'websocket-nats';
console.log(NATS);
```

**期望行为**
npm引用时，能想npm包本身正常引用时的行为，内部的引用也相应地引用成功。

**报错信息**
![11_39_10__11_07_2018](https://user-images.githubusercontent.com/22128204/48109344-0f974d80-e282-11e8-8b6a-5f965c7b0984.jpg)
![11_39_18__11_07_2018](https://user-images.githubusercontent.com/22128204/48109351-13c36b00-e282-11e8-8d68-bd09c51d7da6.jpg)
![11_39_40__11_07_2018](https://user-images.githubusercontent.com/22128204/48109352-1625c500-e282-11e8-81c9-708432eb689d.jpg)

**系统信息**

 - Taro 版本 [1.1.0]

**Comment by xingBri** [comment]
把websocket更改为小程序的websocket应该是可以用的，主要是他代码中引用的其他库，npm并没有相应 地引用。

**Comment by luckyadam** [comment]
这些引用的包都是 node 的原生 api 。。

**Comment by xingBri** [comment]
明白，所以是引用了node原生api的包打包到小程序就不能引用是吗？😂

**Comment by luckyadam** [comment]
@xingBri 是的啊，可以看看有没有别的替代的方案

**Comment by skymoonya** [comment]
@luckyadam 我也遇到了这个问题，我有一个私库引用了buffer这个库，是用的`"buffer": "^5.2.1"`这个buffer也不能打包
