### ISSUE TITLE
自定义组件，内联CSS变量被错误转换

### ISSUE THREAD

**Issue by shaodushu** [NervJS/taro#10220]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/shaodushu/taro-style](https://github.com/shaodushu/taro-style)
**小程序基础库: 2.19.3**
**使用框架: React**

### 复现步骤
1.yarn dev:weapp

### 期望结果
内联CSS变量正常转换

![期望的结果](https://github.com/shaodushu/taro-style/raw/master/static/1630913782.jpg)

### 实际结果
内联CSS变量被错误转换

![实际的结果](https://github.com/shaodushu/taro-style/raw/master/static/1630913935.jpg)

### 环境信息
```
shaodushu@DESKTOP-4OR0GHQ:~/Code/taro-style$ taro info
👽 Taro v3.3.6

{ _: [ 'info' ], options: {}, isHelp: false }

  Taro CLI 3.3.6 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.6 => 3.3.6 
      @tarojs/mini-runner: 3.3.6 => 3.3.6 
      @tarojs/react: 3.3.6 => 3.3.6 
      @tarojs/runtime: 3.3.6 => 3.3.6 
      @tarojs/taro: 3.3.6 => 3.3.6 
      @tarojs/webpack-runner: 3.3.6 => 3.3.6 
      babel-preset-taro: 3.3.6 => 3.3.6 
      eslint-config-taro: 3.3.6 => 3.3.6 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
@tarojs/plugin-html插件会在taro info 下报错

shaodushu@DESKTOP-4OR0GHQ:~/Code/taro-style$ taro info
👽 Taro v3.3.6

{ opts: undefined }
(node:28101) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'platform' of undefined
    at Object.fn (/home/shaodushu/Code/taro-style/node_modules/@tarojs/plugin-html/src/index.ts:88:46)
    at Kernel.<anonymous> (/home/shaodushu/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:202:48)
    at Generator.next (<anonymous>)
    at /home/shaodushu/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/shaodushu/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:4:12)
    at /home/shaodushu/.config/yarn/global/node_modules/@tarojs/service/dist/Kernel.js:200:33
    at eval (eval at create (/home/shaodushu/.config/yarn/global/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:16:17)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/home/shaodushu/.config/yarn/global/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yuanyazhen** [comment]
解决了吗？同遇到这个问题

**Comment by TheKonka** [comment]
最新版本已无此问题
