### ISSUE TITLE
uploadFile是否支持h5？同样的代码小程序没事。在h5端调用接口连后台都到不了，直接报400

### ISSUE THREAD

**Issue by Pinchuan** [NervJS/taro#10221]
### 相关平台
H5

**浏览器版本: chrome 92.0.4**
**使用框架: React**

### 复现步骤
使用Taro.uploadFile上传图片，小程序没有问题，但是h5就报400

### 期望结果
期望h5能和小程序一样能够正常上传文件

### 实际结果
目前h5不支持上传

### 环境信息
```
 Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    "taro-code": "^3.3.0"
```
![image](https://user-images.githubusercontent.com/20009993/132185828-4f8cf382-20f8-444e-8f3d-b055ad143011.png)
![image](https://user-images.githubusercontent.com/20009993/132185921-4cf81801-0285-4536-be93-77004bdba76b.png)
上传图片的功能，在小程序端和h5端都有，使用同一个接口。
调用接口在小程序端没有问题，但在h5上就报错。后端打了断点接口根本没有到后台，在浏览器就已经被阻止了
看了一下上传的参数也没有问题，不知道是哪的原因?
望官方尽快解决这个bug。

**Comment by LuXinZ** [comment]
后端跨域配置错误了吧

**Comment by Pinchuan** [comment]
> 后端跨域配置错误了吧

跟后台没有关系啊，小程序也是调用同样的后端接口，taro这个api的兼容有问题

**Comment by ZakaryCode** [comment]
后端跨域问题，可以先检查接口的参数配置

**Comment by hanwenbo** [comment]
> 后端跨域问题，可以先检查接口的参数配置

很显然这是bug   @ZakaryCode  检查下吧 不要关闭问题
