### ISSUE TITLE
Taro 3.3.6 react 调用showShareImageMenu失败

### ISSUE THREAD

**Issue by zmm2tysu** [NervJS/taro#10236]
### 这个特性解决了什么问题？
分享图片给朋友

### 这个 API 长什么样？
Taro.showShareImageMenu能正常调用

Taro CLI  v3.3.6

**Comment by zmm2tysu** [comment]
Taro v3.3.6

![image](https://user-images.githubusercontent.com/20849786/132440426-4b350211-84af-45cb-944d-7f9befe8ef2c.png)

**Comment by zmm2tysu** [comment]
另，issue能不能我自己关？上次提的那个有问题没解决就关了，再在原issue底下回复也不及时了

**Comment by Chen-jj** [comment]
API 可以用的，只是没有补上类型。类型可以给我们 PR 哈
