### ISSUE TITLE
h5路由模式设置成browser，添加了二级目录（设置了publicPath以及router里面的basename）后页面访问空白

### ISSUE THREAD

**Issue by long-hai-yang** [NervJS/taro#10247]
### 相关平台
H5

### 复现仓库
[https://github.com/long-hai-yang/taro-test.git](https://github.com/long-hai-yang/taro-test.git)
**浏览器版本: Chrome 93**
**使用框架: Vue 3**

### 复现步骤
只要在config/index.js里面h5的router模式设置成browser，并且设置了二级目录（设置了publicPath以及router里面的basename）后页面访问空白。

路由模式设置成hash能正常访问，或者publicPath使用默认的“”/”，basename不设置才能正常访问

### 期望结果
期望h5路由模式设置成browser，添加了二级目录（设置了publicPath以及router里面的basename）后页面能正常访问

### 实际结果
h5路由模式设置成browser，添加了二级目录（设置了publicPath以及router里面的basename）后页面访问显示空白

### 环境信息
```
👽 Taro v3.3.2


  Taro CLI 3.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
```

**Comment by SakuOtonashi** [comment]
```
{
  ...,
  h5: {
    publicPath: '/path/to',
    staticDirectory: 'static',
    router: {
      mode: 'browser',
      basename: '/path/to'
    },
    ...
  },
  ...
}
```
`/path/to`可以，`/path/to/`就不行

**Comment by lhkg1988** [comment]
publicPath设置成/path/to/      ， basename设置成/path/to

**Comment by seiwhale** [comment]
@long-hai-yang 请问这个是怎么解决的

**Comment by lhkg1988** [comment]
> @long-hai-yang 请问这个是怎么解决的

taro升级到3.3.16
