### ISSUE TITLE
关于子组件componentWillReceiveProps不执行的问题

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#1024]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

**问题描述**
[问题描述：子组件在接收父组件props时并没有触发componentWillReceiveProps]

**复现步骤**
[复现问题的步骤]

// 这里可以贴代码
father.js
import Taro, { Component } from '@tarojs/taro';
import { View, Image, Text, Input, Button } from '@tarojs/components';
import Son from '../son/son'

export default class Test extends Component {
    constructor() {
        super(...arguments);
    }
    render() {
        return <Son title='今天是11月07日' />
    }
}
son.js
import Taro, { Component } from '@tarojs/taro';
import { View, Image, Text, Input, Button } from '@tarojs/components';

export default class Son extends Component {
    constructor() {
        super(...arguments);
    }
    componentWillReceiveProps() {
        console.log(this.props);
    }
    render() {
        let { title = '默认标题' } = this.props;
        return <View>标题是:{title}</View>
    }
}
```

**期望行为**
[期望打印出son组件的props]

**报错信息**

[并无报错]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v10.9.0]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
组件初始化阶段不会触发 componentWillReceiveProps，更新阶段才会。看你的代码父组件 mounted 后不曾 setState 过，自组件不触发 componentWillReceiveProps 是正确的。
