### ISSUE TITLE
h5 下 createAnimation 创建的样式 权重与小程序不一致

### ISSUE THREAD

**Issue by hannq** [NervJS/taro#10245]
### 相关平台
H5

**浏览器版本: Microsoft Edge 91**
**使用框架: React**

### 微信小程序下 createAnimation 样式权重是 行内style
![微信小程序下createAnimation](https://qianmi-resources.oss-cn-hangzhou.aliyuncs.com/github-issue/taro/Snipaste_2021-09-08_20-02-22.png)

h5下 createAnimation 样式权重是 属性选择器
![h5下createAnimation](https://qianmi-resources.oss-cn-hangzhou.aliyuncs.com/github-issue/taro/Snipaste_2021-09-08_20-04-56.png)

h5 下权重过低，建议是否可以**追加**权重 或者 `!important`

### 期望结果
h5下 createAnimation 覆盖原有样式

### 实际结果
h5下 createAnimation 权重过低，无法覆盖原有样式

### 环境信息
```
👽 Taro v3.3.7


  Taro CLI 3.3.7 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
    npmPackages:
      @tarojs/components: 3.3.7 => 3.3.7 
      @tarojs/mini-runner: 3.3.7 => 3.3.7 
      @tarojs/react: 3.3.7 => 3.3.7 
      @tarojs/runtime: 3.3.7 => 3.3.7 
      @tarojs/taro: 3.3.7 => 3.3.7 
      @tarojs/webpack-runner: 3.3.7 => 3.3.7 
      babel-preset-taro: 3.3.7 => 3.3.7 
      eslint-config-taro: 3.3.7 => 3.3.7 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.3.5

```

**Comment by hannq** [comment]
临时改了下 `@tarojs/taro-h5/src/api/createAnimation/index.js` 加了 `!important`，勉强能能用，希望官方解决下
![临时fix](https://qianmi-resources.oss-cn-hangzhou.aliyuncs.com/github-issue/taro/Snipaste_2021-09-09_15-14-17.png);

**Comment by Chen-jj** [comment]
@hannq 直接提 PR 咯
