### ISSUE TITLE
node_modules 中的依赖无法解析多端文件

### ISSUE THREAD

**Issue by L-value** [NervJS/taro#10248]
### 相关平台
微信小程序

**小程序基础库: 2.0.0**
**使用框架: React**

### 复现步骤
https://taro-docs.jd.com/taro/docs/envs#%E8%AE%A9-node_modules-%E4%B8%AD%E7%9A%84%E4%BE%9D%E8%B5%96%E4%B9%9F%E8%83%BD%E8%A7%A3%E6%9E%90%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6
参照官方文档在MultiPlatformPlugin中配置include，但是引入node module中的对应默认模块无法解析其中的多端文件
直接项目中是可以识别的

### 期望结果
nodemodule中对应npm包也可以识别多端文件

### 实际结果
对应npm包无法识别多端文件

### 环境信息
```
Taro CLI 3.3.7 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.13 => 3.2.13 
      @tarojs/mini-runner: 3.2.13 => 3.2.13 
      @tarojs/react: 3.2.13 => 3.2.13 
      @tarojs/service: 3.2.13 => 3.2.13 
    npmGlobalPackages:
      typescript: 4.4.2
```

**Comment by L-value** [comment]
如果项目里的多端文件是可以识别的
但是nodemodules里的就不行

**Comment by L-value** [comment]
MultiPlatformPlugin 本身也不会遍历nodemodule里所有包，加了include也没用啊

**Comment by Chen-jj** [comment]
https://docs.taro.zone/docs/next/envs#%E8%AE%A9-node_modules-%E4%B8%AD%E7%9A%84%E4%BE%9D%E8%B5%96%E4%B9%9F%E8%83%BD%E8%A7%A3%E6%9E%90%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6
