### ISSUE TITLE
使用 boundingClientRect 在 useReady 中获得元素的 rect 有时会为 null 的问题

### ISSUE THREAD

**Issue by tgioer** [NervJS/taro#10242]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/taroify/taro336-rect](https://github.com/taroify/taro336-rect)
**小程序基础库: 2.19.3**
**使用框架: React**

## 使用 boundingClientRect 在 useReady 中获得元素的 rect 有时会为 null 的问题

```tsx
function GetRect() {
  const rootRef = useRef<TaroElement>()
  const {objects} = useContext(RectContext)

  useReady(() => {
    createSelectorQuery()
      .select("#"   rootRef.current?.uid)
      .boundingClientRect((rect) => {
        console.log(rootRef.current, rect)
      })
      .exec()
  })

  return (
    <View ref={rootRef}>
      {
        objects.map(num => (<Text key={num}>Num：{num}</Text>))
      }
    </View>
  )
}

```

这个问题在微信小程序中会存在一定的随机性问题，大概率的发生方式是：

* 清空编译缓存再编译
* 创建多个组件

```tsx
export default function Index() {
  return (
    <RectContext.Provider
      value={{
        objects: [1, 2, 3, 4, 5, 6, 7]
      }}
    >
      <View className="index">
        <GetRect/>
        <GetRect/>
        <GetRect/>
        <GetRect/>
        <GetRect/>
        <GetRect/>
        <GetRect/>
        <GetRect/>
        <GetRect/>
      </View>
    </RectContext.Provider>
  )
}
```

### weapp 中的效果

![weapp](https://raw.githubusercontent.com/taroify/taro336-rect/main/images/rect.gif)

### 期望结果
期望的结果是在 useReady 获得 rect 不为 null。

### 实际结果
期望的结果是在 useReady 获得 rect为 null。

### 环境信息
```
� Taro v3.3.6


  Taro CLI 3.3.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - C:\Programs\nodejs\node-v14.17.1-win-x64\node.EXE
      Yarn: 1.22.11 - C:\Programs\nodejs\node\yarn.CMD
      npm: 6.14.13 - C:\Programs\nodejs\node-v14.17.1-win-x64\npm.CMD

```

**Comment by AbstractMan** [comment]
+1，在3.0.14版本中也出现了该问题

**Comment by LuXinZ** [comment]
把onReady 放在index 页面中, 或者 nextTick 进行模拟,. 尝试一下

**Comment by tgioer** [comment]
> 把onReady 放在index 页面中, 或者 nextTick 进行模拟,. 尝试一下

试过了，有随机性。

**Comment by tgioer** [comment]
> 把onReady 放在index 页面中, 或者 nextTick 进行模拟,. 尝试一下

按正常来说，不管用不用 nextTick ，都不应该出现这个问题。

**Comment by Chen-jj** [comment]
@tgioer 没有复现。。

debug 一下小程序的 `onReady` 吧，看看 `onReady` 是不是先于 `useReady` 触发，在 `onReady` 里用原生 API 获取一下试试能不能成功。

https://github.com/NervJS/taro/blob/aefff41d4ef013329a9d5692fca157ea8813a227/packages/taro-runtime/src/dsl/common.ts#L143-L150

**Comment by tgioer** [comment]
等我新示例

**Comment by konka-king** [comment]
我也遇到了这个情况，直接通过微信开发者工具的编译按钮重新编译，在useReady 里，有时候 boundingClientRect 返回 是null ，有时候正常获取到元素信息

**Comment by tgioer** [comment]
> 我也遇到了这个情况，直接通过微信开发者工具的编译按钮重新编译，在useReady 里，有时候 boundingClientRect 返回 是null ，有时候正常获取到元素信息。
> 
> 若 在useEffect里面使用 nextTick 获取 表现 正常

目前我也是 useEffect  在里面nextTick 这种方式

**Comment by tgioer** [comment]
```tsx
export default function useMounted(cb: () => any) {
  useEffect(
    () => nextTick(cb),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  )
}

```
