### ISSUE TITLE
如何在React中取到原生小程序组件的实例?

### ISSUE THREAD

**Issue by Tonysmark** [NervJS/taro#10246]
### 这个特性解决了什么问题？
原本官方文档中提到的 
const { page } = getCurrentInstance()
page.selectComponent('#mychart-dom-area')
在新版本中被弃用, 并且源码中指明需要使用 createRef 来重构
那么请问我要如何在 createRef 方式来引用一个 微信原生组件呢?
另外一点是, 我在写原生组件的时候, class 会消失不见
![图片](https://user-images.githubusercontent.com/22767695/132553039-1d18539d-d0b9-4af9-9162-1637b7e95edd.png)
![图片](https://user-images.githubusercontent.com/22767695/132552994-a1d5c833-73ae-4884-8515-160057968352.png)

### 这个 API 长什么样？
希望能在官方文档中讲明白怎么去获取一个原生组件的实例

**Comment by Chen-jj** [comment]
哪里说这种写法被弃用？

```js
const { page } = getCurrentInstance()
page.selectComponent('#mychart-dom-area')
```

**Comment by Tonysmark** [comment]
> 哪里说这种写法被弃用？
> 
> ```js
> const { page } = getCurrentInstance()
> page.selectComponent('#mychart-dom-area')
> ```

![image](https://user-images.githubusercontent.com/22767695/134280740-82e5a063-4d65-4a92-982a-3aa9ef2aa7b2.png)

下图是官方源码中的部分实例
![image](https://user-images.githubusercontent.com/22767695/134280947-ca1948e2-cea1-4eb5-9c40-32cb16e5f8b7.png)

**Comment by ff-wyf** [comment]
这个问题有解决方案了么？

**Comment by Chen-jj** [comment]
这是 `taro-with-weapp` 的代码，是说使用【反向转换】功能时，原生代码中的 `selectComponent` 用法要修改：

![image](https://user-images.githubusercontent.com/22767695/134280947-ca1948e2-cea1-4eb5-9c40-32cb16e5f8b7.png)

---

正常应用这样使用就行：

```js
const { page } = getCurrentInstance()
page.selectComponent('#mychart-dom-area')
```

这是因为没有添加此类型而已，不影响使用：

![image](https://user-images.githubusercontent.com/22767695/134280740-82e5a063-4d65-4a92-982a-3aa9ef2aa7b2.png)
