### ISSUE TITLE
SwiperItem console.warn 

### ISSUE THREAD

**Issue by qiuziz** [NervJS/taro#1026]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

使用组件SwiperItem，控制台打印console.warn

**复现步骤**
[复现问题的步骤]

组件版本：1.0.7和1.1.1
之前用的1.0.7 升级后还是打印警告

直接使用官方实例
![image](https://user-images.githubusercontent.com/13669987/48115952-8858d280-e29f-11e8-8de1-8922ac6e9b7d.png)

[或者可以直接贴源代码，能贴文字就不要截图]

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
不要打印警告（有点强迫症，看着警告很难受- -）

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/13669987/48115904-5ba4bb00-e29f-11e8-970a-6ed0262d5790.png)

**系统信息**

 - 操作系统: macOS 10.13.4 (17E202)
 - Taro 版本👽 Taro v1.2.0-alpha.3
 - Node.js 版本 v10.1.0
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

在编译时没有加wx:key

**Comment by yuche** [comment]
我按照你截图这个代码并不能复现这个情况，你是不是写了循环？

**Comment by qiuziz** [comment]
@yuche 对的 忘记这个了 我是用数组map的 那这里怎么处理呢

**Comment by yuche** [comment]
你自己加一个 `key` 属性啊

**Comment by yuche** [comment]
指示器是啥

**Comment by qiuziz** [comment]
@yuche 
![image](https://user-images.githubusercontent.com/13669987/48121007-c0b3dd00-e2ae-11e8-8d16-9a8c0539073c.png)

这个点

**Comment by yuche** [comment]
https://www.google.com.hk/search?q=%E5%BE%AE%E4%BF%A1+%E6%8C%87%E7%A4%BA%E5%99%A8+%E6%A0%B7%E5%BC%8F&oq=%E5%BE%AE%E4%BF%A1+%E6%8C%87%E7%A4%BA%E5%99%A8+%E6%A0%B7%E5%BC%8F&aqs=chrome..69i57.5477j0j7&sourceid=chrome&ie=UTF-8

**Comment by qiuziz** [comment]
@yuche 谢谢 原来这里是微信官方组件

第一次做小程序，就用Taro做上线项目了 ：）慌
