### ISSUE TITLE
PickerViewColumn 类名(className) 添加后编译并未添加上

### ISSUE THREAD

**Issue by zhouyint** [NervJS/taro#10264]
### 相关平台
支付宝小程序

**小程序基础库:  2.7.0**
**使用框架: React**

### 复现步骤
https://taro-docs.jd.com/taro/docs/components/forms/picker-view/
官方链接 给PickerViewColumn 添加类名 编译支付宝小程序 后 查看一下编译文件就会发现class并未添加上去

### 期望结果
类名添加成功

### 实际结果
编译后并未添加上className

### 环境信息
```
👽 Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zhouyint** [comment]
不修复就算了 真的是

**Comment by moyafaxi** [comment]
@Chen-jj 这边测试了一下，支付宝 picker-view-column class 是支持设置的。https://github.com/NervJS/taro/pull/11821
