### ISSUE TITLE
工具链 编辑器或IDE

### ISSUE THREAD

**Issue by guider** [NervJS/taro#1028]
现在的脚手架项目使用vscode 打开 eslint会有各种错误， 能否有个插件list 方便上手。

**Comment by yuche** [comment]
什么叫插件 list？

**Comment by guider** [comment]
@yuche 
 例如 是用vscode 推荐的插件 以及配置 。

**Comment by LuckyJoker** [comment]
vscode中eslint运行正常。如果有错误，不是taro的问题。

**Comment by yuche** [comment]
你原始的 vscode 加一个 eslint 插件就可以

**Comment by guider** [comment]
@yuche 
 首先 感谢你的回答 ，我 的想法是官方给个最佳实践 毕竟很多人都是从Vue 转过来的 如果有个最佳实践当然最好了

**Comment by guider** [comment]
> vscode中eslint运行正常。如果有错误，不是taro的问题。

我知道这样是可以解决 。 我期望的是官方出个最佳实践

**Comment by yuche** [comment]
Taro 推荐 [standard](https://github.com/standard/standard) 风格。

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/spec-for-taro.html

**Comment by guider** [comment]
@luckyadam 
 @yuche yucheyuche 非常感谢两位。 这就去研读
