### ISSUE TITLE
引入@tarojs/plugin-html插件会导致部分Taro CLI命令报错

### ISSUE THREAD

**Issue by RYTON0305** [NervJS/taro#10284]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/RYTON0305/taro-vue3-nut-template](https://github.com/RYTON0305/taro-vue3-nut-template)
**小程序基础库: 2.19.4**
**使用框架: Vue 3**

### 复现步骤
Taro   Vue 3项目中引入@tarojs/plugin-html插件后调用Taro CLI命令taro info、taro create、taro doctor等报错

### 期望结果
引入插件后正常使用Taro CLI命令

### 实际结果
命令行报错(node:43560) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'platform' of undefined

### 环境信息
```
👽 Taro v3.3.7


  Taro CLI 3.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

**Comment by nierongcheng** [comment]
同样的问题……

**Comment by Wynnfan** [comment]
> mac + 1

看了下代码，是上个月merge一个pr，modifyRunnerOpts 这个函数里opts没有platform属性导致的

**Comment by Wynnfan** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
我们看看

**Comment by yaodongyi** [comment]
为毛3.3.17还有这个问题，呐尼
![image](https://user-images.githubusercontent.com/31060569/147208321-578f944f-bc57-4479-ac67-ee2875436e2f.png)
