### ISSUE TITLE
@tarojs/plugin-html 插件转译地图map标签，导致其无法使用

### ISSUE THREAD

**Issue by JRainboww** [NervJS/taro#10280]
### 相关平台
微信小程序

**小程序基础库: 2.19.4**
**使用框架: Vue3**

### 复现步骤
config/index.js 配置该插件
```
  plugins: ["@tarojs/plugin-html"],

```

代码部分
```  
  <map
      id="map"
      style="width: 100%; height: 300px"
      longitude="113.324520"
      latitude="23.099994"
      scale="14"
      :show-location="true"
    />
```

编译后
```
<text class="h5-map" id="map"></text>
```

### 期望结果
@tarojs/plugin-html 不转译地图map标签

### 实际结果
将地图map标签 转译为 text标签，导致地图无法使用

### 环境信息
```
  Taro CLI 3.3.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\sobey\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
```

**Comment by JRainboww** [comment]
![image](https://user-images.githubusercontent.com/29792013/133365954-ce68a6ec-baf1-4893-a20b-4bb137f94d5a.png)
由于html中map标签使用情况很少，插件源码中能否移除对小程序地图map标签的转译。或者添加注释功能，使其不转译。

**Comment by sheshihui** [comment]
像是也可以通过修改config/index.js中的plugins，用对应的modifyElements方法来将 map标签排除掉。
![image](https://user-images.githubusercontent.com/8956123/133868743-310067f5-8c59-48ec-8d4c-2310769df827.png)
