### ISSUE TITLE
redux不重新渲染

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#1029]
![image](https://user-images.githubusercontent.com/3361732/48118547-8dba1b00-e2a7-11e8-8f89-916c10d307fa.png)

初始化数据 load返回list=[]空数组，页面不会重新渲染，
暂时初始化state={list:null}代替，作为临时结局了方案

**Comment by luckyadam** [comment]
前后两次数据一致，我认为确实不应该触发重新渲染，你可以再加一个标记来作为判断
