### ISSUE TITLE
Taro升级到3.3.7后，input组件动态绑定focus属性，不能触发聚焦状态

### ISSUE THREAD

**Issue by hdcljt** [NervJS/taro#10293]
### 相关平台
微信小程序

**小程序基础库: 2.19.2**
**使用框架: Vue 3**

### 复现步骤
Input.vue 组件
<input
    :focus="inputFocus"
    :autoFocus="inputFocus"
    :value="inputValue"
/>

触发聚焦组件中修改状态
<cover-view @tap="toInput"></cover-view>

const toInput = () => {
    emits('inputFocus', true)
}

### 期望结果
修改inputFocus状态时，input组件focus属性动态改变

### 实际结果
没有双向绑定

### 环境信息
```
👽 Taro v3.3.7


  Taro CLI 3.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\npm-global\yarn.CMD
      npm: 7.21.0 - ~\npm-global\npm.CMD
```

**Comment by Chen-jj** [comment]
@hdcljt 提供一下完整 demo

**Comment by hdcljt** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
