### ISSUE TITLE
scrollview 因为页面 dom 结构变化回到顶部

### ISSUE THREAD

**Issue by Przeblysk** [NervJS/taro#10298]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Przeblysk/taro3-scroll-view-bug](https://github.com/Przeblysk/taro3-scroll-view-bug)
**小程序基础库: 2.19.5**
**使用框架: React**

### 复现步骤
1. 滚动 scrollview 的内容
2. 点击 show button

### 期望结果
scrollview 不会回到顶部

### 实际结果
scrollview 会因为 dom 变动自动回到顶部

### 环境信息
```
👽 Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
      npm: 7.17.0 - ~/.nvm/versions/node/v14.15.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.3 => 3.3.3
      @tarojs/mini-runner: 3.3.3 => 3.3.3
      @tarojs/react: 3.3.3 => 3.3.3
      @tarojs/runtime: 3.3.3 => 3.3.3
      @tarojs/taro: 3.3.3 => 3.3.3
      @tarojs/webpack-runner: 3.3.3 => 3.3.3
      babel-preset-taro: 3.3.3 => 3.3.3
      eslint-config-taro: 3.3.3 => 3.3.3
      react: ^17.0.0 => 17.0.2
    npmGlobalPackages:
      typescript: 4.1.3
```

**Comment by MoveZZG** [comment]
#9602 首先这是taro的一个bug，如果上述hack可以解决最好， 不过这也有个问题，具体可以看下issue内容。

### 问题出现的原因
1. 同级节点的更新会导致ScrollView重新渲染，而taro为scrollView显示的设置了初始值，包括scroll-top="0"，这使得节点更新时，scrollView会直接回到初始位置。
### 解决方案
1. 避免操作同级DOM更新
2. 显式设置scrollTop，同时避免在滚动的时候出现更新DOM的操作。

**Comment by Chen-jj** [comment]
楼上正解，文档里也有提到这个问题：[删除楼层节点需要谨慎处理](https://docs.taro.zone/blog/2021-02-08-taro-jxpp#11-%E5%88%A0%E9%99%A4%E6%A5%BC%E5%B1%82%E8%8A%82%E7%82%B9%E9%9C%80%E8%A6%81%E8%B0%A8%E6%85%8E%E5%A4%84%E7%90%86)

Taro DOM 序列化后，同层节点是一个数组 `[a, b, c, d]`。

新增节点，可以这样：

```js
this.setData({
  cn[4]: e
})
// 最终得到 [a, b, c, d, e]
```

修改节点也很轻松：

```js
this.setData({
  cn[2]: e
})
// 最终得到 [a, b, e, d]
```

删除节点就麻烦了，小程序没有提供一种 `setData` 的方式，让 `[a, b, c, d]` 直接变成 `[a, b, d]`。

所以只能更新整个数组：

```js
this.setData({
  cn: `[a, b, d]`
})
// 最终得到 [a, b, d]
```

这也就导致了楼主问题。

我们也想过使用链表去代替数组，不过这需要小程序平台支持类似 `wxs` 的东西，之后会进行尝试。

**Comment by Przeblysk** [comment]
感谢开发团队的解疑

**Comment by zhanshihua** [comment]
怎么解决的 遇到了同样的问题 scorllView没有同级元素也会回到顶部 而且手动设置scorllTop在某些安卓机上还是会回到顶部

**Comment by wj0990** [comment]
> 怎么解决的 遇到了同样的问题 scorllView没有同级元素也会回到顶部 而且手动设置scorllTop在某些安卓机上还是会回到顶部

@zhanshihua 那个问题你有解决掉吗

**Comment by Yzzzed** [comment]
> > 怎么解决的 遇到了同样的问题 scorllView没有同级元素也会回到顶部 而且手动设置scorllTop在某些安卓机上还是会回到顶部
> 
> @zhanshihua 那个问题你有解决掉吗

我碰到一种情况，嵌套层级太多了导致的，[全局配置项 baseLevel](https://docs.taro.zone/docs/optimized#1-%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE%E9%A1%B9-baselevel)，在ScrollerView外层加上CustomWrapper包裹可以解决。你碰到的问题有可能跟我的一样。

**Comment by CodeLanHY** [comment]
CustomWrapper包裹一下和ScrollView同层级会导致元素增删的就可以解决，增删元素Taro运行时bug，会整层执行 setData导致scroll-view 重新应用初始 scroll-top=0
