### ISSUE TITLE
taro   typescript 无法正常使用compressVideo

### ISSUE THREAD

**Issue by CYchenyan** [NervJS/taro#10299]
### 相关平台
微信小程序

**小程序基础库: 2.10.4**
**使用框架: React**

### 复现步骤
 Taro.compressVideo({
      src: video.tempFilePath,
      quality: 'high',
      bitrate: 1827.65,
      fps: 30,
      resolution: 0.7,
      success: (res) => {
        console.log('res>>>>>>>......', res);
        startUploadVideo({
          ...video,
          tempFilePath: res.tempFilePath,
          size: res.size * 1024,
        });
      },
      fail: (res) => {
        console.log('compress fail>>>>>>>......', res);
      },

    });

### 期望结果
压缩成功

### 实际结果
TS2339: Property 'compressVideo' does not exist on type 'typeof Taro'.

ignore type 类型检查后，依然报错：
Uncaught (in promise) thirdScriptError
global[key] is not a function
TypeError: global[key] is not a function

### 环境信息
```
 Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.7 => 3.3.7 
      @tarojs/components: 3.3.7 => 3.3.7 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.3.7 => 3.3.7 
      babel-preset-taro: 3.3.7 => 3.3.7 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: 17.0.2 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 3.4.5

```

**Comment by Chen-jj** [comment]
@CYchenyan 类型问题可以给我们提个 PR 咯，改这个地方：https://github.com/NervJS/taro/tree/next/packages/taro/types/api

**Comment by CYchenyan** [comment]
大哥，只有空了提咯

**Comment by ZakaryCode** [comment]
fixed in https://github.com/NervJS/taro/commit/9b25db9251aa717721b9e16f5637d041b5f0c54d
