### ISSUE TITLE
taro升级版本后报错

### ISSUE THREAD

**Issue by qianyihao123** [NervJS/taro#10306]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: Vue 3**

### 复现步骤
1. 原来项目taro-cli为3.0.24
2. 由3.0.24升级至3.3.4后报错

### 期望结果
正常

### 实际结果
"export 'normalizeStyle' (imported as '_normalizeStyle') was not found in 'vue'

### 环境信息
```
👽 Taro v3.3.4

production

  Taro CLI 3.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - E:\nvm\nodejs\node.EXE
      npm: 6.14.15 - E:\nvm\nodejs\npm.CMD
```

**Comment by iswsg** [comment]
taro cli升级后，项目中相关的taro依赖库要相应跟着升级

**Comment by qianyihao123** [comment]
@iswsg 同样也升级了相关依赖 ，但是依旧会报错 。我创建一个新项目后 ，把文件都拷贝过来这才没有问题。不知道我在升级的过程中，是哪一步出错了

**Comment by luckyadam** [comment]
需要把依赖和 lock file 删掉，再安装

**Comment by Chen-jj** [comment]
版本号带了 `^` 或 `~`，又存在 lockfile 时，你以为升级了，可能没有真的升级。lockfile 里可以看到真正安装的版本。

所以，楼上正解。
