### ISSUE TITLE
taro 3.X Input 组件首次渲染时，传入 focus 属性报错

### ISSUE THREAD

**Issue by shushu2013** [NervJS/taro#10303]
### 相关平台
H5

### 复现仓库
[https://github.com/shushu2013/taro-input-focus-example](https://github.com/shushu2013/taro-input-focus-example)

**浏览器版本: Safari 14.1.2 (16611.3.10.1.6) / Chrome 版本 93.0.4577.63（正式版本）**
**使用框架: React**

### 复现步骤
1、运行 taro-input-focus-example 项目
```
$ yarn
$ npm run dev:h5
```

2、点击『搜索』按钮，切换成 Input 组件

3、控制台报错，Input 不能获取到焦点

### 期望结果
不报错，Input 能获取到聚焦

### 实际结果
控制台报错，Input 不能获取到焦点

### 环境信息
```
👽 Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v16.6.0/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
    npmPackages:
      @tarojs/components: ^3.3.3 => 3.3.8 
      @tarojs/mini-runner: ^3.3.3 => 3.3.8 
      @tarojs/react: ^3.3.3 => 3.3.8 
      @tarojs/runtime: ^3.3.3 => 3.3.8 
      @tarojs/taro: ^3.3.3 => 3.3.8 
      @tarojs/webpack-runner: ^3.3.3 => 3.3.8 
      babel-preset-taro: ^3.3.3 => 3.3.8 
      eslint-config-taro: 3.0.9 => 3.0.9 
      react: ^17.0.2 => 17.0.2 

```
![企业微信截图_6935cf97-c0b4-47fb-97ed-662d76825210](https://user-images.githubusercontent.com/6076072/133434920-c2368d86-d77f-4fa1-99a3-9ced70a2b815.png)
![企业微信截图_1be285ba-5206-4110-88fa-26f3088a3f36](https://user-images.githubusercontent.com/6076072/133434931-817e8944-e72a-4e53-8115-548a35ead00e.png)

**Comment by ZakaryCode** [comment]
未能复现该问题，可以升级版本后再试
