### ISSUE TITLE
使用mobx报错， @tarojs/mobx引入Provider报错：Cannot call a class as a function

### ISSUE THREAD

**Issue by 3sang** [NervJS/taro#10301]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:3sang/taro_proj.git](git@github.com:3sang/taro_proj.git)
**小程序基础库: 2.9.4**
**使用框架: React**

### 复现步骤
打开项目后 npm run dev:weapp即可

### 期望结果
使用mobx

### 实际结果
不知道为什么出bug

### 环境信息
```
👽 Taro v3.3.4


  Taro CLI 3.3.4 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.npm-global/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.13 => 3.2.13 
      @tarojs/mini-runner: 3.2.13 => 3.2.13 
      @tarojs/react: 3.2.13 => 3.2.13 
      @tarojs/runtime: 3.2.13 => 3.2.13 
      @tarojs/taro: 3.2.13 => 3.2.13 
      @tarojs/webpack-runner: 3.2.13 => 3.2.13 
      babel-preset-taro: 3.2.13 => 3.2.13 
      eslint-config-taro: 3.2.13 => 3.2.13 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
源头应该是是app.js引入了Provider。但不是很明白为什么这样引入会出错。

尝试项目升级到taro最新版本3.3.7观察是否还有这个问题，但是直接升级@tarojs/taro 是不够的，会报错，官网的文档里没有找到如果3.x旧版本想要升级到3.x的最新版本应该怎么做（不知道是不是我找的不够仔细？）

<img width="475" alt=") TypeError Cannot call a class as" src="https://user-images.githubusercontent.com/37074792/133416096-9165a127-a453-46eb-b384-3a17ddf790b3.png">

**Comment by 3sang** [comment]
已解决，
原参考文档http://taro-docs.jd.com/taro/docs/mobx 确实会报错
![image](https://user-images.githubusercontent.com/37074792/133562038-88850a84-d4d1-4fe6-a21d-659edba43d2a.png)

后面终于翻到了这个讲迁移的文档https://taro-docs.jd.com/taro/docs/migration/
这一部分讲到了taro不会再维护taro-mobx，相关依赖自行引入，于是自行下载mobx-react@6.1.4 （ mobx@4.8.0供参考)
![image](https://user-images.githubusercontent.com/37074792/133562038-88850a84-d4d1-4fe6-a21d-659edba43d2a.png)

现代码可正确运行：
`
import Taro from '@tarojs/taro'
import { Provider } from 'mobx-react'
import { Component } from 'react'
import store from './store'
import './app.less'

class App extends Component {

  // 项目启动显示的时候触发
  componentDidShow () {}

  // 项目切换后台时触发
  componentDidHide () {}

  componentDidCatchError () {}

  // this.props.children 是将要会渲染的页面
  render () {
    return (
      <Provider store={store}>
        {this.props.children}
      </Provider>
    )
  }
}

export default App
`

**Comment by zjjjjjjjjjjd** [comment]
...搞了半天
