### ISSUE TITLE
升级Taro3.3.8后eslint-loader无法定位页面

### ISSUE THREAD

**Issue by Benjaminbai** [NervJS/taro#10304]
<img width="340" alt="3 2 8pk" src="https://user-images.githubusercontent.com/23426556/133542800-9d4b8c73-fd6f-430b-bef1-9bd25932af29.png">
### 相关平台
H5

**浏览器版本: Version 93.0.4577.63 (Official Build) (x86_64)**
**使用框架: React**

### 复现步骤
1. 老版本taro3.2.8，安装eslint-loader正常
2. 新版本taro3.3.8，安装eslint-loader后出现无法定位具体文件的问题
3. 
<img width="509" alt="3 2 8" src="https://user-images.githubusercontent.com/23426556/133542872-b82f6c36-3230-41a4-b7bb-f94b332a2ca2.png">
<img width="566" alt="3 3 8" src="https://user-images.githubusercontent.com/23426556/133542884-951ef5bd-39d5-4a86-9c90-4c703c8753d8.png">
<img width="350" alt="3 3 8pk" src="https://user-images.githubusercontent.com/23426556/133542900-16993c91-fd1f-4620-b335-eb945b77adfd.png">
<img width="340" alt="3 2 8pk" src="https://user-images.githubusercontent.com/23426556/133542800-9d4b8c73-fd6f-430b-bef1-9bd25932af29.png">
### 期望结果
新版本也能兼容eslint-loader

### 实际结果
新版本无法兼容eslint-loader

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.8 => 3.3.8 
      @tarojs/components: 3.3.8 => 3.3.8 
      @tarojs/mini-runner: 3.3.8 => 3.3.8 
      @tarojs/react: 3.3.8 => 3.3.8 
      @tarojs/runtime: 3.3.8 => 3.3.8 
      @tarojs/taro: 3.3.8 => 3.3.8 
      @tarojs/webpack-runner: 3.3.8 => 3.3.8 
      babel-preset-taro: 3.3.8 => 3.3.8 
      eslint-config-taro: 3.3.8 => 3.3.8 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

**Comment by Chen-jj** [comment]
@Benjaminbai 报错信息有指明哪个页面报错吧。

**Comment by Benjaminbai** [comment]
> @Benjaminbai 报错信息有指明哪个页面报错吧。
只会定位在app.config.ts, 而且这个文件并没有报错信息里的内容

**Comment by Benjaminbai** [comment]
@Chen-jj hi，就只会定位在app.config.ts, 而且这个文件并没有报错信息里的内容，我demo测试的也是同一条eslint rule，结果却差异很大

**Comment by Chen-jj** [comment]
@Chen-jj 是不是 loader 时机不对，eslint 分析的是被 babel 处理后的代码

**Comment by Benjaminbai** [comment]
@Chen-jj 大佬分析的有道理，我再顺着这个思路尝试解决，大佬666，taro yyds
