### ISSUE TITLE
VM817:18 WXMLRT_$gwx:./base.wxml:template:285:16: Template `tmpl_0_div` not found.

### ISSUE THREAD

**Issue by quarkcms** [NervJS/taro#10325]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/quarkcms/quark-app](https://github.com/quarkcms/quark-app)
**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
我是根据官方的教程，使用了antd-mobile的库，报了这个警告。使用的是 antd-mobile@next

### 期望结果
正常运行

### 实际结果
VM817:18 WXMLRT_$gwx:./base.wxml:template:285:16: Template `tmpl_0_div` not found.

### 环境信息
```
  Taro CLI 3.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by quarkcms** [comment]
试用了一下官方的实例：https://github.com/NervJS/taro-antd-mobile，也跑不起来。

**Comment by quarkcms** [comment]
升级到最新版，解决了

**Comment by Tonysmark** [comment]
> 升级到最新版，解决了

升级哪一个?
