### ISSUE TITLE
自定义组件传递数据在weapp和swan中不一样

### ISSUE THREAD

**Issue by xliyq** [NervJS/taro#1032]
**问题描述**

我通过实现自定义组件后再微信小程序和百度小程序展现效果不一致，通过截取数据后发现组件的props值不一致
![image](https://user-images.githubusercontent.com/5515880/48120297-ba246600-e2ac-11e8-8b59-a970cf213fd9.png)

**代码**
```js
// 这里可以贴代码
 return <Feed
                  key={item}
                  feed_source_img={item.feed_source_img}
                  feed_source_name={item.feed_source_name}
                  feed_source_txt={item.feed_source_txt}
                  question={item.question}
                  answer_ctnt={item.answer_ctnt}
                  good_num={item.good_num}
                  comment_num={item.comment_num}
                />
```

**期望行为**
在swan 中能够正确的获取props的值
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: windows10
 - Taro 版本 v1.1
 - Node.js 版本v8.9.3
 - 报错平台 weapp swan

**Comment by luckyadam** [comment]
我提交了一个 commit https://github.com/NervJS/taro-zhihu-sample/commit/82f577c18f71e69b33551dda8bab64a4b5f52297
