### ISSUE TITLE
官方能否出个多端通配的图表库，目前现有主流的 echarts-for-weixin 只能微信中使用，无法通配多端

### ISSUE THREAD

**Issue by tilkofjin** [NervJS/taro#10320]
### 这个特性解决了什么问题？
解决多端图表类渲染不统一问题

### 这个 API 长什么样？
类似 echarts 的Api 经由 Taro 进行二次整体封装，能开箱即用，多端通配即可！

**Comment by tilkofjin** [comment]
按照官方文档进行依赖细分，编译成功且生成了我想要的js文件，但微信开发工具中报错，结果页面报错
![image](https://user-images.githubusercontent.com/24365622/134038021-092121f9-3802-42d1-a13f-e926355ba2ee.png)
我的config配置如下
![image](https://user-images.githubusercontent.com/24365622/134038492-397fa17a-605f-401d-aaa4-7b4f689b97a9.png)

**Comment by ZakaryCode** [comment]
参考 https://github.com/wuba/taro-visualization/tree/main/packages/taro-charts
