### ISSUE TITLE
官方文档搜索功能无法使用

### ISSUE THREAD

**Issue by whiteGreat** [NervJS/taro#10329]
### 这个特性解决了什么问题？
https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.5.1)%3B%20Browser%20(lite)%3B%20docsearch%20(1.0.0-alpha.28)%3B%20docsearch-react%20(1.0.0-alpha.28)%3B%20docusaurus%20(2.0.0-alpha.69)%3B%20autocomplete-core%20(1.0.0-alpha.28)&x-algolia-api-key=3f32982103f4e75dadd86900d26a9315&x-algolia-application-id=BH4D9OD16A

### 这个 API 长什么样？
https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.5.1)%3B%20Browser%20(lite)%3B%20docsearch%20(1.0.0-alpha.28)%3B%20docsearch-react%20(1.0.0-alpha.28)%3B%20docusaurus%20(2.0.0-alpha.69)%3B%20autocomplete-core%20(1.0.0-alpha.28)&x-algolia-api-key=3f32982103f4e75dadd86900d26a9315&x-algolia-application-id=BH4D9OD16A

**Comment by honlyHuang** [comment]
已经修复

**Comment by bnhjk76** [comment]
2021-09-28官方文档搜索还是不好使 @honlyHuang

**Comment by honlyHuang** [comment]
> 2021-09-28官方文档搜索还是不好使 @honlyHuang

你使用的地址，发一下咯，我这边试了 https://taro-docs.jd.com 和 https://docs.taro.zone 都是好使的
