### ISSUE TITLE
组件的引用路径，能使用import {xxx} from '@/dir/main' 方式吗？

### ISSUE THREAD

**Issue by kusion** [NervJS/taro#1033]
目前用脚手架生成出来的框架结构，在引用组件路径时，都是采用相对路径，如：from '../../dir/main'，请问是否有方式改造成为以"@"符号起的根目录方式引用吗？如: import {xxx} from '@/dir/main'

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/82

**Comment by yuche** [comment]
在 #82 追踪这个问题吧
