### ISSUE TITLE
微信小程序接入视频号直播

### ISSUE THREAD

**Issue by LaughingZhu** [NervJS/taro#10333]
### 这个特性解决了什么问题？
从小程序直接跳转到视频号中看直播，微信官方是出了这个api的
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/channels-live.html

### 这个 API 长什么样？
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/channels-live.html

**Comment by qsjc** [comment]
这种可以自己加环境判断调用wx的api  taro官方有没有 无所谓的

**Comment by LaughingZhu** [comment]
> 这种可以自己加环境判断调用wx的api taro官方有没有 无所谓的

是吗，我试试看

**Comment by fanzuwang** [comment]
请问怎么接入
