### ISSUE TITLE
vant-weapp 无法绑定 readonly，class 等以关键字命名的属性到组件

### ISSUE THREAD

**Issue by HyperLife1119** [NervJS/taro#10337]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/HyperLife1119/taro-issue](https://github.com/HyperLife1119/taro-issue)
**小程序基础库: 2.19.4**
**使用框架: Vue 3**

### 复现步骤
编译到微信小程序查看结果

相关代码：
```html
<van-field :readonly="true" :value="msg" label="姓名" maxlength="30" />
<van-button class="my-cls" type="primary">按钮</van-button>
<van-datetime-picker type="datetime" :filter="filter" />
```

### 期望结果
1. van-field 组件绑定了 readonly 属性为 true，van-field 应不能进行编辑
2. van-button 组件绑定了 class 属性，编译后应该保留 class 属性
3. van-datetime-picker 组件绑定 filter 属性，van-datetime-picker 应该可以使用传递过来的过滤器函数。[详见](https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker)

### 实际结果
1. van-field 组件绑定了 readonly 属性为 true，van-field 仍然可以编辑
2. van-button 组件绑定了 class 属性，编译后 class 属性丢失
3. van-datetime-picker 组件绑定了 filter 属性，但实际并没有把 filter 函数传递给 van-datetime-picker 组件

### 环境信息
```
👽 Taro v3.3.7


  Taro CLI 3.3.7 environment info:      
    System:
      OS: Windows 10
    Binaries:
      Node: 16.1.0 - D:\Node.js\node.EXE
      npm: 7.21.0 - D:\Node.js\npm.CMD 
```

**Comment by HyperLife1119** [comment]
@Chen-jj

**Comment by HyperLife1119** [comment]
为什么没人理这个 issue 呢？ @Chen-jj

**Comment by Chen-jj** [comment]
遗漏了，我们看看

**Comment by HyperLife1119** [comment]
有结果了吗？🤔

**Comment by HyperLife1119** [comment]
有结果了吗？ @Chen-jj

**Comment by Chen-jj** [comment]
> van-field 组件绑定了 readonly 属性为 true，van-field 仍然可以编辑

断点进入 Vue3 patch DOM 的部分，可以发现对于 `readonly` 这个保留词，Vue 在设置 attribute 时，会设置空字符串，相当于：`dom.setAttribute('readonly', '')`。因此你只能手动调用 `setAttribute`，而不通过 Vue 去设置。

![image](https://user-images.githubusercontent.com/11807297/145364631-9268b924-0800-4932-8f5e-ef39fce89718.png)

![image](https://user-images.githubusercontent.com/11807297/145364743-84676503-798b-4f31-8718-dd3921960fdc.png)

```html
<template>
  <view class="index">
    <van-field ref="field" :value="msg" label="姓名" maxlength="30" />
  </view>
</template>

<script lang="ts">
import { ref, onMounted } from 'vue'

export default {
  setup() {
    const field = ref()
    onMounted(() => {
      // 手动 setAttribute
      const el = field.value
      el.setAttribute('readonly', true)
    })
    return {
      field
    }
  }
}
</script>
```

**Comment by HyperLife1119** [comment]
那 class 和 filter 的情况呢？

**Comment by Chen-jj** [comment]
> van-button 组件绑定了 class 属性，编译后 class 属性丢失

这点下一个版本修复

**Comment by Chen-jj** [comment]
> van-datetime-picker 组件绑定了 filter 属性，但实际并没有把 filter 函数传递给 van-datetime-picker 组件

实际上 Taro 是有把该函数进行 setData 的：

![image](https://user-images.githubusercontent.com/11807297/145401091-2f02ef46-b884-4c9e-85cf-f90725dc1a5d.png)

但可能小程序没有很好地适配这种 setData 写法，令到最终这个 filter 是 `undefined`。

试了一下，只有这样 setData，才能正确设置 function：

![image](https://user-images.githubusercontent.com/11807297/145401524-3263e3cb-73b3-4c19-af9f-e99afb77f542.png)

因此开发者可以这样绕过此问题（下个版本开始支持）：

```html
<template>
  <view class="index">
    <van-datetime-picker type="datetime" :filter="filter" />
  </view>
</template>

<script lang="ts">
import { ref } from 'vue'
import Taro from '@tarojs/taro'

export default {
  setup() {
    const filter = ref()
    return {
      msg,
      filter
    }
  },
  onReady () {
    Taro.nextTick(() => {
      console.log('nexttick: ', )
      this.filter = (type: string, options: number[]) => {
        if (type === 'minute') {
          return options.filter(option => option % 5 === 0);
        }
        return options;
      };
    })

  }
}
</script>
```

**Comment by HyperLife1119** [comment]
thank you

**Comment by smoothdvd** [comment]
@Chen-jj React里怎么修复这个问题？

**Comment by Chen-jj** [comment]
> @Chen-jj React里怎么修复这个问题？

React 里的 hack 写法：https://github.com/NervJS/taro/issues/8495#issuecomment-1179526364

**Comment by xavieryang2011** [comment]
calendar组件里面的formatter函数没法传递，这个怎么解决？

**Comment by HyperLife1119** [comment]
vant-weapp 的 formatter 参数不能传入 null 或 undefined，该 issue 提供的解决方案不适用。目前只能手动去修改 vant-weapp 的组件源码来解决该问题。
