### ISSUE TITLE
Taro 文档顶部导航栏 UI 问题

### ISSUE THREAD

**Issue by Confettis** [NervJS/taro#10341]
### 相关平台
微信小程序

**小程序基础库: 0.0.0**
**使用框架: React**

### 复现步骤
打开 https://docs.taro.zone/docs/README

### 期望结果
样式正常显示

### 实际结果
顶部导航栏样式有问题

![Snipaste_2021-09-24_21-29-16](https://user-images.githubusercontent.com/80667818/134684238-7d5b70bb-11f5-45ae-bed7-9c3d041ccba6.png)

### 环境信息
```

👽 Taro v3.3.7


  Taro CLI 3.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.7.0 - E:\nvm\nodejs\node.EXE
      Yarn: 1.22.11 - E:\nvm\nodejs\yarn.CMD
      npm: 7.21.0 - E:\nvm\nodejs\npm.CMD
```

---
### 补充信息
Chrome：版本 95.0.4638.17（正式版本）dev （64 位）

**Comment by Chen-jj** [comment]
文档 CI 有点问题，还没跟新到最新版本，尽快修复

**Comment by honlyHuang** [comment]
我们把菜单折叠了，您这边看看您的电脑下是否还有问题
![image](https://user-images.githubusercontent.com/3080820/134797751-a6de2c4e-57db-4f95-a92f-e534d14620fb.png)
