### ISSUE TITLE
页面文件支持config

### ISSUE THREAD

**Issue by bingtsingw** [NervJS/taro#10348]
### 这个特性解决了什么问题？
每个页面都要单独一个page.config.ts文件

### 这个 API 长什么样？
在页面函数的静态属性上配置config
```
function Index() {
  return (
      <View className='index'>
        <Text>1</Text>
      </View>
    )
}

Index.config = {
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTextStyle: 'black',
    navigationBarTitleText: '首页',
    backgroundColor: '#eeeeee',
    backgroundTextStyle: 'light'
}

export default Index
```

### 相关issue
https://github.com/NervJS/taro/issues/7062
https://github.com/NervJS/taro/issues/9824
https://github.com/NervJS/taro/issues/7937

以前的版本好像支持过这个特性
https://github.com/NervJS/taro/issues/3054#issuecomment-498527838

**Comment by Chen-jj** [comment]
Taro v3.4 开始支持，新增两个编译时宏函数，文档：

- [defineAppConfig](https://docs.taro.zone/docs/app-config#defineappconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
- [definePageConfig](https://docs.taro.zone/docs/page-config#definepageconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
