### ISSUE TITLE
编译的时候不成功报错，不知道为什么要下载这个文件

### ISSUE THREAD

**Issue by aiewing** [NervJS/taro#1034]
在终端输入npm run dev:h5的时候编译，就会报错

gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://r.cnpmjs.org/node/v11.0.0/node-v11.0.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/aiewing/Desktop/Taro/myApp/node_modules/node-gyp/lib/install.js:214:14)
gyp ERR! stack     at Request.emit (events.js:187:15)
gyp ERR! stack     at Request.onRequestResponse (/Users/aiewing/Desktop/Taro/myApp/node_modules/request/request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:20)
gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/aiewing/Desktop/Taro/myApp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/aiewing/Desktop/Taro/myApp/node_modules/node-sass
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

**系统信息**

 - 操作系统: [OSX]
 - Taro 版本 [1.0.0]
 - Node.js 版本 [v9.0.0]
 - 报错平台 [h5]

**Comment by cncolder** [comment]
应该是 `node-sass` 没装上, 换成淘宝源试下. 项目根目录放个 `.npmrc` 文件.

```rc
# NPM Taobao registry
registry=https://registry.npm.taobao.org

# Taobao node binary mirrors
fse_binary_host_mirror=https://npm.taobao.org/mirrors/fsevents
sass_binary_site=http://cdn.npm.taobao.org/dist/node-sass
```
