### ISSUE TITLE
生成的h5端和app端是否支持音视频播放？

### ISSUE THREAD

**Issue by xuzhibin** [NervJS/taro#1037]
生成的h5端和app端是否支持音视频播放？

**Comment by jinjinjin0731** [comment]
[视频支持](https://nervjs.github.io/taro/docs/components/media/video.html)
[音频支持](https://nervjs.github.io/taro/docs/components/media/audio.html)

目前的支持程度是这样的哈， RN 端最近几天会增加 Video 组件

**Comment by xuzhibin** [comment]
谢谢，之前也看过文档，只是想知道rn端有没升级更新

**Comment by jinjinjin0731** [comment]
嗯 RN 视频最近会新增  音频正在加中
