### ISSUE TITLE
编译小程序后自带了window对象，导致ECharts插件注册事件失败

### ISSUE THREAD

**Issue by johnlucita** [NervJS/taro#10374]
### 相关平台
微信小程序

**小程序基础库: 2.19.5**
**使用框架: Vue 3**

### 复现步骤
小程序   引用echarts-taro3-vue组件

### 期望结果
小程序是封装了window对象的，因此大多通用的组件都会采用类似typeof window !== 'undefined' && !!window.addEventListener;这样的判断条件来区分事件绑定方式是使用addEventListener或者attachEvent，可否在编译小程序时去除window对象，以保证小程序端代码执行准确

### 实际结果
Taro编译的小程序中判断条件typeof window !== 'undefined' && !!window.addEventListener;返回true，导致组件注册事件走了平台代码，错误信息参考https://github.com/Cecilxx/echarts-taro3-vue/issues/5

### 环境信息
```
Taro CLI 3.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
使用echarts-taro3-vue组件在小程序端绘制图表

**Comment by wujianping334455** [comment]
遇到同样的问题，echarts 一直报el.addEventListener is not a function，3.2.0以下版本都没有问题，升到3.3.12就有问题了。没有仔细查阅，不知道到底是哪个版本改了window

**Comment by Chen-jj** [comment]
> Taro框架自带了window对象，这与ECharts的判断条件(var isDomLevel2 = typeof window !== 'undefined' && !!window.addEventListener;)起了冲突，导致判断错误，走了平台分支导致的

正解。

因此手动修改 `isDomLevel2` 的值即可：

```js
// echarts-taro3-vue/src/components/ec-canvas/echarts.js Line:1801

// 修改前：
var isDomLevel2 = typeof window !== 'undefined' && !!window.addEventListener;

// 修改后：
var isDomLevel2 = process.env.TARO_ENV === 'h5'
```
