### ISSUE TITLE
初始化RN报错 Cannot find module 'xdl'

### ISSUE THREAD

**Issue by coolperbs** [NervJS/taro#1038]
**问题描述**
1.typescript + sass
2.百度，微信，支付宝，H5跑起来都没有问题
3.跑RN会报如图错误
![wx20181108-132800](https://user-images.githubusercontent.com/8486549/48179438-26a96e80-e35a-11e8-8306-b5c3243ff5cd.png)

**Comment by luckyadam** [comment]
应该是项目依赖的问题，可以进入 .rn_temp 目录再重装下
