### ISSUE TITLE
取消 Taro 这个类型的全局声明

### ISSUE THREAD

**Issue by biluochun** [NervJS/taro#10381]
### 相关平台
微信小程序

**小程序基础库: 任意**
**使用框架: React**

### 复现步骤
无

### 期望结果
在使用TypeScript时，当文件用到 Taro 相应的api时，比如：`Taro.navigateBack(....)`
Ts 应该报错 'Taro is undefined'

### 实际结果
Ts没报错，但是却在运行时报错 'Taro is undefined'。

### 环境信息
```
 Taro CLI 3.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.23.0-20200615.1913 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
没有明白是如何使用的

**Comment by biluochun** [comment]
> 你没有 import Taro 么

没有 import 。因为ts认为Taro是个全局变量。

**Comment by biluochun** [comment]
这个问题偶尔会带来困扰，因为ts的本意是编译时检测类型，提前报出异常。

非全局变量Taro，被声明成全局变量，会导致编码和编译过程无法暴露出这个异常。

**Comment by ZakaryCode** [comment]
https://github.com/NervJS/taro/pull/10635
