### ISSUE TITLE
ESLint 出错，好烦啊！~~~

### ISSUE THREAD

**Issue by AibiTi** [NervJS/taro#104]
ESLint 出错，好烦啊！~~~ 

组件上的事件，`onClick` ESLint **猛**报错，点击**有效果**。`onclick` ESLint 又不 **猛** 报错，点击**没效果**。

<s><b>是我的 VScode 问题，还是什么问题？</b></s> 看了一下 ESLint 规则配置源码，逻辑好像反了。醉~。

![b](https://user-images.githubusercontent.com/40224479/41333636-1be8653c-6f15-11e8-8cf2-ef610658f9d1.png)

![a](https://user-images.githubusercontent.com/40224479/41333634-1a9e18ca-6f15-11e8-90e5-968e9f825dc5.png)

![d](https://user-images.githubusercontent.com/40224479/41333929-28fa449c-6f16-11e8-8673-498c0bfb62fb.png)

附上 ESLint 配置：

```js
{
    "extends": [
        "taro"
    ],
    "parser": "babel-eslint",
    "rules": {
        "no-unused-vars": [
            "warn",
            {
                "varsIgnorePattern": "Taro"
            }
        ],
        "import/no-commonjs": 0
    }
}
```

**Comment by yuche** [comment]
抱歉昨天刚加了这个规则，写反了条件判断😂，也没来得及加测试用例。

https://github.com/NervJS/taro/commit/b40c873c0c17cab6e3c3019b42814fc5b5718f33
修复了这个问题并加了若干用例。
