### ISSUE TITLE
Uncaught ReferenceError: my is not defined

### ISSUE THREAD

**Issue by supercgj** [NervJS/taro#1040]
**问题描述**

百度智能小程序开发工具，打开使用如下命令
①taro init myApp
②npm run build:swan
命令生成的 dist文件夹，
百度智能小程序开发者工具控制台报错 “Uncaught ReferenceError: my is not defined”

**复现步骤**

1. taro init myApp
2. npm run build:swan
3. 使用百度智能小程序开发者工具，打开生成的dist文件夹

**期望行为**
和微信开发者工具表现一直即可。

**报错信息**

index.js:674 Uncaught ReferenceError: my is not defined
    at index.js:674
    at Array.forEach (<anonymous>)
    at processApis (index.js:673)
    at initNativeApi (index.js:703)
    at Object.<anonymous> (index.js:704)
    at app.js:1674
    at e (index.js:1)
    at index.js:1
    at index.js:3
    at e (index.js:1)

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.1]
 - Node.js 版本 [e.g. v8.11.2]
 - 报错平台 [swan]

**补充信息**
npm run build:weapp 编译成功，在微信小程序开发者工具打开正常，无报错。
npm run build:swan    编译成功，在百度小程序开发者工具打开异常，有报错。
百度小程序开发者工具：
   编译工具版本：2.12.8  
   调试基础库：2.0.17  
   开发者工具版本：1.14.5

**Comment by luckyadam** [comment]
抱歉，1.1.3 版本有个提交存在问题，已经修复
d1a468858fb9cc09997adf73428fdcb065212593

**Comment by supercgj** [comment]
谢谢~
