### ISSUE TITLE
路由跳转新路径不带参数(也没有开头?)时会携带旧页面路径中的参数

### ISSUE THREAD

**Issue by SakuOtonashi** [NervJS/taro#10409]
### 相关平台
H5

### 复现仓库
[https://github.com/SakuOtonashi/taro-bug.git](https://github.com/SakuOtonashi/taro-bug.git)
**浏览器版本: Chrome 94**
**使用框架: React**

### 复现步骤
必现，navigateTo/reLaunch都是这样。如果新路径没有参数但是末尾有?时就不会携带旧页面路径中的参数
比如旧路径 /pages/index/index?code=123
    跳转到 /pages/home/home ，页面路径变成 /pages/home/home?code=123
    跳转到 /pages/home/home? ，页面路径变成 /pages/home/home?
在线查看 https://sakuotonashi.github.io/taro-bug/dist/#/pages/index/index?code=123

### 期望结果
跳转到 /pages/home/home ，页面路径就是 /pages/home/home

### 实际结果
跳转到 /pages/home/home ，页面路径变成 /pages/home/home?code=123

### 环境信息
```
👽 Taro v3.3.9


  Taro CLI 3.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by yatoo1993** [comment]
h5遇到这个问题了，有办法解决吗？目前解决是把参数设置空值

**Comment by Simpma** [comment]
我也遇到这个问题了，求比较好的解决方法
