### ISSUE TITLE
h5在运行时报'_$router' of undefined异常

### ISSUE THREAD

**Issue by yujiaming890321** [NervJS/taro#1041]
**问题描述**

h5编译没有问题。
在运行时组件初始化时报'_$router' of undefined异常
相同代码在微信小程序可以正常编译运行。

**报错信息**

![image](https://user-images.githubusercontent.com/13047250/48183055-72fbab00-e368-11e8-8385-73a756bc354e.png)

![image](https://user-images.githubusercontent.com/13047250/48183033-61b29e80-e368-11e8-8233-d92d05bbfa2e.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.1.3]
 - Node.js 版本 [v8.9.3]
 - 报错平台 [h5]

**补充信息**

**Comment by marunzhou** [comment]
我也遇到了这个问题，后来在每个js 的 constructor 中添加上 super(...arguments); 才可以成功运行
