### ISSUE TITLE
微信小程序 subpackages 分包不生成

### ISSUE THREAD

**Issue by meshikai2014** [NervJS/taro#1042]
**问题描述**

![image](https://user-images.githubusercontent.com/7982589/48183638-5b252680-e36a-11e8-9098-f08902f70d0e.png)

不生成分包
![image](https://user-images.githubusercontent.com/7982589/48183679-8576e400-e36a-11e8-93d1-b8c46dd6abbb.png)

**系统信息**

 - 操作系统: [e.g. Windows 8]
 - Taro 版本 [e.g. v1.1.1]
 - Node.js 版本 [e.g. v6.1.0]
 - 报错平台 [ weapp]

**Comment by luckyadam** [comment]
写 `subPackages` 吧
