### ISSUE TITLE
qq小程序生成了wxss文件

### ISSUE THREAD

**Issue by Jkanon** [NervJS/taro#10439]
### 相关平台
QQ 小程序

**小程序基础库: 1.39.0**
**使用框架: React**

### 复现步骤
升级到3.3.10，开发编译qq小程序，qq小程序工具报错存在相同的wxss和qss文件，无法正常预览

### 期望结果
不需要wxss

### 实际结果
生成qss同时也生成了wxss文件

### 环境信息
```
👽 Taro v3.3.10


  Taro CLI 3.3.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@Jkanon 没有复现，请提供一下 demo

**Comment by Jkanon** [comment]
> @Jkanon 没有复现，请提供一下 demo

这边测试了一下，是在分包且开启optimizeMainPackage配置的时候会出现

**Comment by Chen-jj** [comment]
提供一下 demo 咯
