### ISSUE TITLE
将TimePicer父组件切换display: none和block时 会触发onChange事件 此时的e.detail.value数组的每一项都是0

### ISSUE THREAD

**Issue by lupingW** [NervJS/taro#10437]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/wangluping/taro_bug/tree/master/](https://gitee.com/wangluping/taro_bug/tree/master/)
**小程序基础库: 2.19.5**
**使用框架: React**

### 复现步骤
切换TimePicker父容器的display属性 打印TimePicker上onchange方法是否调用 和调用的值

### 期望结果
切换父组件display时 不调用onchange

### 实际结果
调用了

### 环境信息
```
👽 Taro v3.3.9


  Taro CLI 3.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\node\node.EXE
      npm: 6.14.14 - D:\node\npm.CMD
```

---
### 补充信息
https://gitee.com/wangluping/taro_bug.git

**Comment by jiaozitang** [comment]
@lupingW 因为 display block none 会导致 选择器 DOM 节点重新渲染，因此会导致 onChange 事件触发，用 visibility hidden visible 代替 display block none 控制选择器的显示隐藏试试。

**Comment by lupingW** [comment]
> @lupingW 因为 display block none 会导致 选择器 DOM 节点重新渲染，因此会导致 onChange 事件触发，用 visibility hidden visible 代替 display block none 控制选择器的显示隐藏试试。

大佬 仓库代码少了一行 我提交了 麻烦再看看

**Comment by lupingW** [comment]
> @lupingW 因为 display block none 会导致 选择器 DOM 节点重新渲染，因此会导致 onChange 事件触发，用 visibility hidden visible 代替 display block none 控制选择器的显示隐藏试试。
https://static.didapinche.com/vf/v/019cq41l1h2021-10-18%2010-37-46.mp4 这是视频

**Comment by jiaozitang** [comment]
@lupingW 用 visibility 代替 display 来控制组件的显示隐藏试试，我看到你仓库的代码并没有修改哦

![image](https://user-images.githubusercontent.com/18493352/137698089-6c989b06-6c14-4a1f-8966-f4b9da8a0d39.png)
