### ISSUE TITLE
cssLoaderOption期望增加exportLocalsConvention选项

### ISSUE THREAD

**Issue by hasnum-stack** [NervJS/taro#10440]
### 这个特性解决了什么问题？
cssModule时可以使用 style.listItem 而不是 style['list-item']

### 这个 API 长什么样？
cssLoaderOption:{
exportLocalsConvention:camelCase
}

**Comment by Chen-jj** [comment]
这样设置 Taro 编译配置即可：

```js
cssLoaderOption:{
  localsConvention: 'camelCase'
}
```

小程序的编译时：`@tarojs/mini-runner` 使用的 `css-loader` 版本是 3.x，但 `css-loader` 4.x 的时候才把这个配置项移动为 `modules. exportLocalsConvention `

![image](https://user-images.githubusercontent.com/11807297/137661551-c49e085c-7398-43e1-97b6-bc70846144b9.png)
