### ISSUE TITLE
百度小程序“login 联合登录 / 手机号授权内嵌组件”，Taro3.x不支持

### ISSUE THREAD

**Issue by oyvfhp** [NervJS/taro#10452]
### 相关平台
百度小程序

**小程序基础库: 3.41.1**
**使用框架: React**

### 复现步骤
https://smartprogram.baidu.com/docs/develop/component/login/
在Taro2.x下是可以正常使用<login></login>的，taro3.x直接显示为空白。

Taro2.x环境下：
![image](https://user-images.githubusercontent.com/4404279/137829300-3441dc27-aafe-474d-ad49-ece8ea984139.png)

Taro3.x环境下：
![image](https://user-images.githubusercontent.com/4404279/137829332-8adcfced-6ce5-4633-89cd-9695d549a3b8.png)

### 期望结果
显示百度登陆的<login></login>相关信息

### 实际结果
空白

### 环境信息
```
  Taro CLI 3.3.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.11.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.10 => 3.3.10 
      @tarojs/mini-runner: 3.3.10 => 3.3.10 
      @tarojs/react: 3.3.10 => 3.3.10 
      @tarojs/runtime: 3.3.10 => 3.3.10 
      @tarojs/taro: 3.3.10 => 3.3.10 
      @tarojs/webpack-runner: 3.3.10 => 3.3.10 
      babel-preset-taro: 3.3.10 => 3.3.10 
      eslint-config-taro: 3.3.10 => 3.3.10 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
当前功能属于百度小程序的内嵌组件，主要解决正常的授权模式授权通过率较低，使用当前的内嵌组件登陆方式有助于提高授权通过率。

**Comment by oyvfhp** [comment]
@Chen-jj  麻烦您帮看下，这个功能使用对提升百度小程序授权登陆成功率有很高的提升。

**Comment by sheodon** [comment]
请问这个插件怎么使用呀？

**Comment by oyvfhp** [comment]
> 请问这个插件怎么使用呀？

百度官方有文档的。
