### ISSUE TITLE
vue3 <script <setup>语法糖里面的方法与<script>混用时，在<script>onShow，onPullDownRefresh等生命周期内，build的时读取不到，dev时没问题 

### ISSUE THREAD

**Issue by CaicoLeung** [NervJS/taro#10456]
### 相关平台
微信小程序

**小程序基础库: 2.19.6**
**使用框架: Vue 3**

### 复现步骤
```javascript
<script lang="ts">
export default {
  onShow() {
    this.store.dispatch("requestShopCartList");
    this.store.dispatch("requestPalletCartList");
  }
};
</script>

<script lang="ts" setup>
import { computed, ref, watch } from "vue";
import GoodsCart from "#/tarbar/shopcart/GoodsCart.vue";
import PalletCart from "#/tarbar/shopcart/PalletCart.vue";
import { useStore } from "#/store";
import Taro from "@tarojs/taro";

const store = useStore();
</script>
```

### 期望结果
onShow内部可以访问this, 获取setup内部的变量

### 实际结果
this为undefined

### 环境信息
```
taro CLI 3.3.9 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.10 => 3.3.10
      @tarojs/mini-runner: 3.3.10 => 3.3.10
      @tarojs/runtime: 3.3.10 => 3.3.10
      @tarojs/taro: 3.3.10 => 3.3.10
      @tarojs/webpack-runner: 3.3.10 => 3.3.10
      babel-preset-taro: 3.3.10 => 3.3.10
      eslint-config-taro: 3.3.10 => 3.3.10
```

**Comment by b2nil** [comment]
用 `expose` 呢，比如： `expose({ store })`

**Comment by zanderpu** [comment]
遇到了同样的问题，写了好多代码，最后build出来发现出错了

**Comment by DoveAz** [comment]
可以自己写一些hooks, 我觉得用起来还可以
```javascript
export function useDidShow(callback) {
  onMounted(callback)
  Current.page.onShow = callback
}
export function usePullDownRefresh(callback) {
  Current.page.onPullDownRefresh = callback
}
export function useReachBottom(callback) {
  Current.page.onReachBottom = callback
}
export function useQuery() {
  return omitBy(Current.router.params, (v, k) => /^\$/.test(k))
}
```

**Comment by AsherSun** [comment]
> 可以自己写一些hooks, 我觉得用起来还可以
> 
> ```js
> export function useDidShow(callback) {
>   onMounted(callback)
>   Current.page.onShow = callback
> }
> export function usePullDownRefresh(callback) {
>   Current.page.onPullDownRefresh = callback
> }
> export function useReachBottom(callback) {
>   Current.page.onReachBottom = callback
> }
> export function useQuery() {
>   return omitBy(Current.router.params, (v, k) => /^\$/.test(k))
> }
> ```

`Current` 是从哪里引入的？
这样引入的嘛？`import {Current} from '@tarojs/taro`
为什么我这样引入，找不到`Current`

**Comment by DoveAz** [comment]
> > 可以自己写一些hooks, 我觉得用起来还可以
> > ```js
> > export function useDidShow(callback) {
> >   onMounted(callback)
> >   Current.page.onShow = callback
> > }
> > export function usePullDownRefresh(callback) {
> >   Current.page.onPullDownRefresh = callback
> > }
> > export function useReachBottom(callback) {
> >   Current.page.onReachBottom = callback
> > }
> > export function useQuery() {
> >   return omitBy(Current.router.params, (v, k) => /^\$/.test(k))
> > }
> > ```
> 
> `Current` 是从哪里引入的？ 这样引入的嘛？`import {Current} from '@tarojs/taro` 为什么我这样引入，找不到`Current`

是的 就是这样引入的，至于找不到，我就不知道了

**Comment by Chen-jj** [comment]
duplicate #9779

Taro v3.4+ 开始支持小程序生命周期的 Composition API。

**Comment by panhezeng** [comment]
onMounted(() => {
  const taroInstance = Taro.getCurrentInstance();
  const router = taroInstance.router!;
  Taro.nextTick(() => {
    // console.log("nextTick", !!getElement());
  });
  Taro.eventCenter.on(router.onReady, () => {
    // console.log("onReady", !!getElement());
  });
  Taro.eventCenter.on(router.onShow, () => {
    // console.log("onShow", !!getElement());
  });
});

也可以用这个暂时模拟，在 <script setup lang="ts"> 实现 onShow 之类的方法，而且可以获得 setup 变量

**Comment by zj-wukewei** [comment]
> duplicate #9779
> 
> Taro v3.4+ 开始支持小程序生命周期的 Composition API。
  大概什么时候发布版本
