### ISSUE TITLE
Taro 3.3.10 编译 H5 没有 tree shaking

### ISSUE THREAD

**Issue by zousandian** [NervJS/taro#10466]
### 相关平台
H5

### 复现仓库
[https://github.com/zousandian/taro3test](https://github.com/zousandian/taro3test)
**浏览器版本: chrome 62**
**使用框架: React**

### 复现步骤
使用 taro init 默认模版，没有引入 taro-ui，编译H5体积都高达900多K
```
taro init test
cd test
npm install && npm run build:h5
```

![image](https://user-images.githubusercontent.com/6047274/138061575-09277638-ef6d-4d07-9c3f-1c43779427ed.png)

### 期望结果
按照 taro 文章的说法，应该是优化过 tree shaking 的
https://taro-docs.jd.com/taro/blog/2019-02-28-taro-h5-optimize

### 实际结果
H5 编译 tree shaking 没有生效

### 环境信息
```
👽 Taro v3.3.10


  Taro CLI 3.3.10 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.10 => 3.3.10
      @tarojs/mini-runner: 3.3.10 => 3.3.10
      @tarojs/react: 3.3.10 => 3.3.10
      @tarojs/runtime: 3.3.10 => 3.3.10
      @tarojs/taro: 3.3.10 => 3.3.10
      @tarojs/webpack-runner: 3.3.10 => 3.3.10
      babel-preset-taro: 3.3.10 => 3.3.10
      eslint-config-taro: 3.3.10 => 3.3.10
      react: ^17.0.0 => 17.0.2
    npmGlobalPackages:
      typescript: 4.0.2
```

**Comment by LuoQaxa** [comment]
@tarojs/components 就算没有引入也被打包到项目中，在taro-loader 处理app.tsx时，直接引入了
![image](https://user-images.githubusercontent.com/19726459/143268009-038212d7-76ae-434d-bfe5-a2f5dc312791.png)

**Comment by bobsam** [comment]
确实是在这个版本开始，tree shaking开始丢了。。

**Comment by bobsam** [comment]
确实是在这个版本开始，tree shaking开始丢了。。

**Comment by bobsam** [comment]
@ZakaryCode 打小程序的tree-shaking是不是也没有了，我发现包体都大了一些。。。

**Comment by ZakaryCode** [comment]
> @ZakaryCode 打小程序的tree-shaking是不是也没有了，我发现包体都大了一些。。。

不至于，如果验证有问题可以单独再提个 issue
