### ISSUE TITLE
Safari 浏览器下，从页面跳转到另一个网址，浏览器回退后，url 正确变化了，页面显示的内容不是该 url 对应的页面内容了

### ISSUE THREAD

**Issue by shushu2013** [NervJS/taro#10464]
### 相关平台
H5

Safari 上会有此 bug
Chrome 上是正常的

### 复现仓库
[https://github.com/shushu2013/taro-h5-bugs-example](https://github.com/shushu2013/taro-h5-bugs-example)
**浏览器版本: Safari浏览器 版本14.1.2 (16611.3.10.1.6)**
**使用框架: React**

### 复现步骤
```
$ git clone https://github.com/shushu2013/taro-h5-bugs-example.git

$ cd taro-h5-bugs-example

$ yarn

$ npm run dev:h5
```

1、进入首页，点击『进入详情页』按钮

![企业微信截图_8e2440b4-8f3a-49bd-893f-f651cef6e07a](https://user-images.githubusercontent.com/6076072/138051728-46985589-847e-4af9-b1a2-198f9e6570b1.png)

2、进入详情页，再点击 `https://www.baidu.com` 链接，跳转到百度首页

![企业微信截图_ee85447c-2697-49d7-9fa2-3442c51933b7](https://user-images.githubusercontent.com/6076072/138051846-f12c46aa-32b9-495b-a568-ab6eeac94e5f.png)

3、浏览器回退，此时 url 是详情页的 url，但是显示的不是『详情页』的内容，而是『首页』页面的内容

![企业微信截图_ecbbfd94-2df8-4463-9cec-d34e5291a416](https://user-images.githubusercontent.com/6076072/138051880-e3a8c648-e8d2-41ac-8bfc-e3d29b5ca5ba.png)

### 期望结果
回退后，页面内容显示正常

### 实际结果
回退后，页面内容显示不正常

### 环境信息
```
👽 Taro v3.3.10


  Taro CLI 3.3.10 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v16.6.0/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.10 => 3.3.10
      @tarojs/mini-runner: 3.3.10 => 3.3.10
      @tarojs/react: 3.3.10 => 3.3.10
      @tarojs/runtime: 3.3.10 => 3.3.10
      @tarojs/taro: 3.3.10 => 3.3.10
      @tarojs/webpack-runner: 3.3.10 => 3.3.10
      babel-preset-taro: 3.3.10 => 3.3.10
      eslint-config-taro: 3.3.10 => 3.3.10
      react: ^17.0.0 => 17.0.2

```

**Comment by shushu2013** [comment]
@Chen-jj 这个问题能做个兼容吗

查下来是 Safari 浏览器回退，会使用缓存中的数据，Back-Forward Cache 机制
参考 https://blog.csdn.net/hyb1234hi/article/details/79876491

解决方案是，监听页面 pageshow 事件，如果使用缓存中的数据，重新 reload 页面
``` 
window.addEventListener('pageshow', function (e) {
    if (e.persisted) {
      window.location.reload()
    }
  })
```

**Comment by Chen-jj** [comment]
@shushu2013 可以先在 app.js 增加这段监听逻辑试试的，目测 reload 会对前进后退的页面状态产生一点影响
