### ISSUE TITLE
目录也有保留字？？（introduction）

### ISSUE THREAD

**Issue by HuangHongRui** [NervJS/taro#1046]
**问题描述**
为何当目录名为： **introduction** 时，会导致无法渲染该目录下的index文件？

**复现步骤**
[解决问题的步骤]
- 把目录名换了

**报错信息**
![image](https://user-images.githubusercontent.com/26321899/48194203-4e62fb80-e387-11e8-806a-3e80b8580e09.png)

**Comment by luckyadam** [comment]
无法复现，请再尝试一下，或者提供下相关代码

**Comment by luckyadam** [comment]
请问还有问题么
