### ISSUE TITLE
安装最新版本1.1.4报错

### ISSUE THREAD

**Issue by tianlu1677** [NervJS/taro#1047]
#环境是mac, npm 6.2.0

$ npm install -g @tarojs/cli
```
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tarojs/transformer-wx@1.1.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@tarojs/cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-11-08T11_08_04_018Z-debug.log
```

**Comment by yuche** [comment]
现在 npm 出现了一些问题，有些包没能成功发布，稍微网络正常我们把未发布的包全发布就能解决这个问题。

现在可以先安装 `1.1.3`

**Comment by luckyadam** [comment]
已经 OK 了，可以重新试下

**Comment by relaxfinger** [comment]
安装报错，mac 10.15.1， node 12.13.1 ，npm 6.13.1

命令：
 npm i -g @tarojs/cli

结果：
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated eslint-plugin-typescript@0.12.0: Deprecated: Use @typescript-eslint/eslint-plugin instead
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tarojs/taroize@1.3.26.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@tarojs/cli'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/relaxfinger/.npm/_logs/2019-11-27T07_37_25_531Z-debug.log

**Comment by Garfield550** [comment]
1.3.26 刚出，等待 npm 源同步。
