### ISSUE TITLE
h5路由支持一个页面对应多个路由

### ISSUE THREAD

**Issue by CroatiaParanoia** [NervJS/taro#10470]
### 这个特性解决了什么问题？
项目部署在服务子路由中。当服务以 /m 开头 表示不需要身份授权， 以 /mp 开头表示需要身份授权（先走后端服务处理授权逻辑， 再返回index.html） ，此时构建的单一路由无法满足需求， 需要构建出一个页面， 对应两个或者多个路由别名。

比如当配置 publicPath 为 '/m' 开头时， 则无法匹配到 `/mp` 开头的路由， 反之亦然。

所以需要一个页面配置多个路由别名， 这样 `/m` 或者 `/mp` 的都可以匹配到同一个页面。（或者其他的路由规则）

### 这个 API 长什么样？
config/index.js 

h5.router.customRoutes = Record<string, string | string[]>

**Comment by CroatiaParanoia** [comment]
关联 PR https://github.com/NervJS/taro/pull/10471

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/config-detail#h5routercustomroutes)

**Comment by CroatiaParanoia** [comment]
> [参考文档](https://nervjs.github.io/taro/docs/next/config-detail#h5routercustomroutes)

感谢🙏
