### ISSUE TITLE
组件中哪个事件对应页面的onShow

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro#1048]
**问题描述**

组件中哪个事件对应页面的onShow

![image](https://user-images.githubusercontent.com/16408873/48206403-516ee380-e3a9-11e8-9d19-97b846febdbe.png)

**Comment by nyrf** [comment]
componentDidShow

**Comment by jiangzeyin** [comment]
> componentDidShow

打开一个新页面，再关闭页面。第一个页面中的组件不会收的 componentDidShow 事件

**Comment by nyrf** [comment]
你要是接收什么？我从api加载数据，开始是放在componentWillMount里，进入下一页再返回不会重新加载数据，但放在componentDidShow里是可以的，这个对应的应该是onShow的，你如果要重新加载数据，把相关逻辑放在这个里面就可以的

**Comment by briefguo** [comment]
函数式组件的onShow生命周期怎么实现呢？使用useEffect的时候，页面返回的时候，useEffect是不走的吗？
