### ISSUE TITLE
componentDidCatchError多平台失效

### ISSUE THREAD

**Issue by YuanQuan** [NervJS/taro#10495]
### 相关平台
React Native
H5

**使用框架: React**

### 复现步骤
在app.ts文件中修改如下
componentDidCatchError(err) {
        console.error(error)
}

render() {
aa();//这里手动出错
        return this.props.children
    }

### 期望结果
componentDidCatchError 可以捕捉到错误

### 实际结果
没有触发componentDidCatchError

### 环境信息
```
 Taro v3.3.10


  Taro CLI 3.3.10 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.1 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.18.1 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.10 => 3.3.10 
      @tarojs/components: 3.3.10 => 3.3.10 
      @tarojs/mini-runner: 3.3.10 => 3.3.10 
      @tarojs/react: 3.3.10 => 3.3.10 
      @tarojs/runtime: 3.3.10 => 3.3.10 
      @tarojs/taro: 3.3.10 => 3.3.10 
      @tarojs/webpack-runner: 3.3.10 => 3.3.10 
      babel-preset-taro: 3.3.10 => 3.3.10 
      eslint-config-taro: 3.3.10 => 3.3.10 
      react: ^17.0.0 => 17.0.2 
      react-native: ^0.64.0 => 0.64.2 

```

**Comment by zhiqingchen** [comment]
RN

app.ts 中
```
componentDidCatchError
```
用于设置
```
global.ErrorUtils.setGlobalHandler
```

页面组件的 componentDidCatch 也无法触发
https://github.com/NervJS/taro/issues/9987

**Comment by zhiqingchen** [comment]
需要捕获子组件的异常，可以使用
componentDidCatch

见 https://github.com/NervJS/taro/pull/8191 讨论

**Comment by yandeqiang** [comment]
咱们这个问题解决了吗？next 版本上没有看到这方面代码。

**Comment by ZakaryCode** [comment]
componentDidCatchError 是旧版本生命周期，3.0+ 版本中可以使用 `componentDidCatch` 或 `getDerivedStateFromError` 捕获错误，或者通过 `onError` 监听错误事件。
