### ISSUE TITLE
海外 node-sass 无法安装

### ISSUE THREAD

**Issue by lengzhang** [NervJS/taro#1049]
在海外运行 `Taro init` 会提示 `Error: 404 response downloading https://r.cnpmjs.org/node/v8.11.4/node-v8.11.4-headers.tar.gz`

在 `.npmrc` 里删除 `sass_binary_site=https://r.cnpmjs.org/node-sass/` 可以解决因为做了代理无法下载 `node-sass` 的问题

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/0a2f8d830f25357f4ebcda0ec001192dbb8a9a4d
