### ISSUE TITLE
CoverImage组件无法使用

### ISSUE THREAD

**Issue by fuzik-sirui** [NervJS/taro#105]
`
import { View, Map, CoverView, CoverImage } from '@tarojs/components'
render () {
   return (
      <CoverImage src='../../assets/images/home-head.png'></CoverImage>
   )
}
`
![image](https://user-images.githubusercontent.com/24428630/41333518-aed1e13a-6f14-11e8-8ffe-42f6de862d96.png)
编译报错了
![image](https://user-images.githubusercontent.com/24428630/41333538-bf689570-6f14-11e8-804c-23848abe06b1.png)
预览报错

**Comment by luckyadam** [comment]
import 引入时你是不是写的  `./@tarojs/components`

**Comment by luckyadam** [comment]
问题定位了，即将修复

**Comment by yuche** [comment]
装个新版本应该可以用了
