### ISSUE TITLE
如何自定义环境变量打包

### ISSUE THREAD

**Issue by yezongyang** [NervJS/taro#1050]
NODE_ENV 一般就是development 和 production, 但是部署其实可能有test, staging, prod多种，怎么样写各种的配置变量呢， 比如vue-cli3 https://cli.vuejs.org/guide/mode-and-env.html#modes

**Comment by luckyadam** [comment]
NODE_ENV=test taro build --type weapp --watch
类似这样

**Comment by yezongyang** [comment]
NODE_ENV 可以这样简单处理，但是如果我在h5项目里，在不同的部署环境配置不同的变量呢，比如 publicPath,  websocket url 这种业务环境变量

**Comment by yezongyang** [comment]
不知道您是否看了vue-cli3的那种环境变量配置，一种是构建的两种环境（development, production），一种是部署的环境（dev, test, stage, prod）,  对于构建的环境只是针对构建时的优化， 而部署环境就会涉及到业务变量了。

用webpack 的时候好像都没多少人反馈这种需求哈，不知道为啥

**Comment by luckyadam** [comment]
@yezongyang  这种还是看自己业务是否需要吧~

**Comment by wsz7777** [comment]
个人感觉这种需求还是挺有用的。。。一方面不是所有开发者都可以很牛逼或者开发环境很棒，自动化测试的内容可以在gitlab ci里面去跑，另一方面构建模式和部署环境的确应当分开
