### ISSUE TITLE
Taro.showToast的option中的icon，应当有一个错误或者异常的图标。

### ISSUE THREAD

**Issue by yangyixuan** [NervJS/taro#10516]
### 这个特性解决了什么问题？
Taro.showToast的option中的icon，有错误或异常的图标。

### 这个 API 长什么样？
和微信小程序官方的API一样。

**Comment by ZakaryCode** [comment]
fixed in https://github.com/NervJS/taro/commit/d95a28b25338403a491bc19cfd5b76afd89e5d84
