### ISSUE TITLE
ref：组件依赖引用

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#1052]
`import Taro, {Component} from '@tarojs/taro';
import {View} from '@tarojs/components';

class Parent extends Component {

  componentDidMount() {
    this.doStart();
  }

  doStart() {
    if(this.child1.isCanPlay()) {

    } else if(this.child2.isCanPlay()) {

    } else {
      // 加入队列
    }
  }

  getOtherChild(slotPos) {
    return slotPos === '0' ? this.child2.getLastObj() : this.child1.getLastObj();
  }

  render() {
    return (
      <Block>
        <Child ref={obj => this.child1 = obj} slotPos='0' onGetChild={this.getOtherChild} />
        <Child ref={obj => this.child2 = obj} slotPos='1' onGetChild={this.getOtherChild} />
      </Block>
    );
  }
}

class Child extends Component {

  lastObj = {};

  getLastObj = () => this.lastObj;

  isCanPlay() {
    // 一堆判断
    if(isBool) {
      const otherChildObj = this.props.onGetChild(this.props.slotPos);

      return true;
    }
    return false;
  }

  render() {
    return (
      <View>child{this.props.slotPos}</View>
    )
  };
}`
version：1.1.4
otherChildObj取不到值

**Comment by Chen-jj** [comment]
问题不是出在 ref 上，组件实例是已经拿到了。
问题在于，自组件调用父组件传入的函数，Taro 是利用微信小程序提供的组件事件 **TriggerEvent**，去做的。因此 `this.props.onGetChild()` 会被编译成 `TriggerEvent('onGetChild')` 的形式。而 TriggerEvent 调用是拿不到该父组件函数的返回值的，这是问题所在。

**Comment by agulado** [comment]
@Chen-jj 请问有什么变相实现的方案吗？子组件调用父组件函数，且能拿到返回值。

**Comment by Chen-jj** [comment]
@agulado 子组件调用父组件函数，父组件 `setState` 通过 props 再传下去。或者使用 redux 等状态管理工具。

**Comment by agulado** [comment]
@Chen-jj 嗯……说来复杂。
我是在子组件map数据，创建AtTag，map过程中调用父组件的方法，根据数据得到是否active
我先试试，看看是不是在父组件就先把数据map一遍，再传给子组件。多谢～
