### ISSUE TITLE
Taroify 一个使用 React 和 Taro 开发的 Vant 组件库

### ISSUE THREAD

**Issue by ickg5** [NervJS/taro#10534]
### 这个特性解决了什么问题？
<p align="center">
  <img alt="logo" src="https://img.yzcdn.cn/vant/logo.png" width="120" style="margin-bottom: 10px;">
</p>
<h3 align="center">轻量、可靠的小程序 UI 组件库</h3>

## 介绍

Taroify 是移动端组件库 [Vant](https://github.com/youzan/vant) 的 Taro 版本，两者基于相同的视觉规范，提供一致的 API 接口，助力开发者快速搭建小程序应用。

### 通过 npm 安装使用（推荐）

* 通过 npm 安装

```bash
npm i @taroify/core -S --production
```

* 通过 yarn 安装

```bash
yarn add @taroify/core --production
```

### 这个 API 长什么样？
* [项目地址](https://github.com/mallfoundry/taroify)
* [文档地址](https://taroify.gitee.io/taroify.com/introduce/)
* [更新日志](https://taroify.gitee.io/taroify.com/changelog/)

**Comment by luckyadam** [comment]
perfect，已 star
