### ISSUE TITLE
button的openType为feedback时，支付宝无法跳转页面，没有反应。

### ISSUE THREAD

**Issue by blue-fatty** [NervJS/taro#10538]
### 相关平台
微信小程序

**小程序基础库: 最新**
**使用框架: React**

### 复现步骤
```javascript
<Button openType='feedback'>异常反馈</Button>
```

### 期望结果
出现支付宝自带的异常反馈页面

### 实际结果
点击没效果

### 环境信息
```
Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - D:\APP-1\install\node\node.EXE
      Yarn: 1.22.10 - C:\Users\AppData\Roaming\npm\yarn.CMD
      npm: 7.11.2 - D:\APP-1\install\node\npm.CMD
```

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/204718531-a697dc20-efc6-47c6-9cba-393752274dd7.png)

https://opendocs.alipay.com/mini/component/button#open-type%20%E6%9C%89%E6%95%88%E5%80%BC

支付宝小程序 `openType`有效值中无 `feedback`
