### ISSUE TITLE
如何引用微信原生组件？

### ISSUE THREAD

**Issue by DaZiYuan** [NervJS/taro#10535]
### 这个特性解决了什么问题？
如何引用微信的 share-element？
usingComponents: {
    'share-element': '这写什么'
  }

### 这个 API 长什么样？
文档只写了如何引用第三方，我想引用原生的组件

**Comment by DaZiYuan** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html

**Comment by luckyadam** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html

这个组件暂时没有支持，可以自己使用 https://github.com/NervJS/taro-plugin-inject 插件拓展出这个组件

**Comment by DaZiYuan** [comment]
> > https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html
> 
> 这个组件暂时没有支持，可以自己使用 https://github.com/NervJS/taro-plugin-inject 插件拓展出这个组件

我前两天看过文档，没弄明白，有vue3的demo吗，看工程可能直观点···

**Comment by Chen-jj** [comment]
duplicate #11466

**Comment by fujiazhang** [comment]
> > > https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html
> > 
> > 
> > 这个组件暂时没有支持，可以自己使用 https://github.com/NervJS/taro-plugin-inject 插件拓展出这个组件
> 
> 我前两天看过文档，没弄明白，有vue3的demo吗，看工程可能直观点···

兄弟你解决了吗

**Comment by DaZiYuan** [comment]
记不得了，应该是放弃折腾这个功能了


> > > > https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html
> > > 
> > > 
> > > 这个组件暂时没有支持，可以自己使用 https://github.com/NervJS/taro-plugin-inject 插件拓展出这个组件
> > 
> > 
> > 我前两天看过文档，没弄明白，有vue3的demo吗，看工程可能直观点···
> 
> 兄弟你解决了吗
