### ISSUE TITLE
希望可以自定义 webpack loader

### ISSUE THREAD

**Issue by DiamondYuan** [NervJS/taro#1054]
我想写一个 svg loader 自动把svg转换成base64.

**Comment by twocucao** [comment]
强烈要求这个功能

**Comment by luckyadam** [comment]
这个功能得等到 cli 重构才能支持，应该在 12 月

**Comment by DiamondYuan** [comment]
> 这个功能得等到 cli 重构才能支持，应该在 12 月

到时候支持的是 webpack 的loader吗？

**Comment by luckyadam** [comment]
@DiamondYuan 还不是，cli 换成 webpack 周期比较久，还不能确定

**Comment by cjwddz** [comment]
请问这个问题解决了吗？

**Comment by shenghanqin** [comment]
请等待后续更新。目前开发分支中已经有webpack的跟进了。

**Comment by smackgg** [comment]
@luckyadam taro3.0 next 好像还是不支持自定义 loader？
