### ISSUE TITLE
Taro 3x 版本如何进行单元测试

### ISSUE THREAD

**Issue by masteroy** [NervJS/taro#10545]
### 这个特性解决了什么问题？
镜像问题：[Taro 3x 版本该如何进行jest单元测试？ ](https://github.com/NervJS/taro/issues/8632)

官方人员提到在“Q1 内能推出一个完整的单测方案”，请问有进展吗？
参考社区的解决方案，大概有以下：
1. 参考taro-testing-library，对于3x版本使用react-testing-library代替，但无参考案例，实际使用报各种错误。
2. 参考 [taro-dojo](https://github.com/Kevin170113664/taro-dojo) 该demo只能在3.0.10上跑，在最新版的taro上面会报错 `ReferenceError: ENABLE_INNER_HTML is not defined`

我们之前在taro 1x 和 taro 2x 上都构建了完整的单元测试，计划要升级到taro 3x但被单元测试这块卡住了，欢迎讨论如何构建完整的单元测试方案。

### 这个 API 长什么样？
能够构建完整的单元测试方案

**Comment by luckyadam** [comment]
可以参考 taro-dojo ，升级到 Taro 最新版本

**Comment by ZakaryCode** [comment]
[Jest 参考文档](https://nervjs.github.io/taro/docs/next/external-libraries/#jest)

**Comment by lihe6666** [comment]
> [Jest 参考文档](https://nervjs.github.io/taro/docs/next/external-libraries/#jest)

这文档和没写一样，没有完整的单元测试就等于残废品
