### ISSUE TITLE
升级3.3.12编译h5报错

### ISSUE THREAD

**Issue by yclnycl** [NervJS/taro#10558]
### 相关平台
H5

**浏览器版本: Chrome 已是最新版本 版本 95.0.4638.69（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
直接运行dev h5打开首页无法加载页面, route.js报错没有路由生成

### 期望结果
正常编译呈现页面

### 实际结果
![image](https://user-images.githubusercontent.com/25178232/139847728-e366a77c-4f48-49c4-9b92-92842d34da85.png)
![image](https://user-images.githubusercontent.com/25178232/139847813-80451500-3c8f-4610-a83d-aede6ea75ee3.png)

### 环境信息
```
👽 Taro v3.3.12


  Taro CLI 3.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
项目依赖是否也升级到了 3.3.12

**Comment by yclnycl** [comment]
> 项目依赖也升级到了 3.3.12



> 项目依赖是否也升级到了 3.3.12

升级了,使用taro update self 和 taro update project 命令并且 npm i重新安装过了 保证依赖都是3.3.12

**Comment by yclnycl** [comment]
经过调时发现在h5访问到某一页面动态引入组件的时候会报错
![image](https://user-images.githubusercontent.com/25178232/140921655-38b8c803-b45e-4406-a32a-39358a42e2d3.png)
请问这个import语法做了什么,和webpack的动态import是一个东西吗
在import这个页面之后会报一个config未找到的错误,是在import编译期加载什么变量未找到吗

**Comment by yclnycl** [comment]
@luckyadam

**Comment by Chen-jj** [comment]
@yclnycl 提供一下 demo？

**Comment by yclnycl** [comment]
> @yclnycl 提供一下 demo？

我看了下import的语法,确认了是页面中的变量空指针,最后发现h5下的taro.getApp()方法返回undefined

复现demo https://github.com/yclnycl/taro_h5_demo

**Comment by yclnycl** [comment]
有结果了吗

**Comment by yclnycl** [comment]
@luckyadam

**Comment by yclnycl** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@yclnycl H5 的 `getApp` 修复了，升级到最新版再试试吧，3.3.14 是好的：

![image](https://user-images.githubusercontent.com/11807297/142964422-894e8cbc-d121-4e24-9f3e-bcbb34dd6e44.png)
