### ISSUE TITLE
能不能把runtime文件打包到分包中，主包是原生的

### ISSUE THREAD

**Issue by longfei59418888** [NervJS/taro#10556]
### 这个特性解决了什么问题？
希望以分包的形式，加到其他小程序

### 这个 API 长什么样？
无

**Comment by luckyadam** [comment]
文件的输出目录是可以自己配置 webpack 来修改的

**Comment by longfei59418888** [comment]
> 文件的输出目录是可以自己配置 webpack 来修改的

它大包出来的 app.js 里面引用了runtime 环境，我想把runtime环境搞到 每个页面去，不是在 app.js 里面引用

**Comment by Chen-jj** [comment]
看看这个咯：https://docs.taro.zone/docs/next/taro-in-miniapp#%E6%8A%8A-taro-%E9%A1%B9%E7%9B%AE%E4%BD%9C%E4%B8%BA%E4%B8%80%E4%B8%AA%E5%AE%8C%E6%95%B4%E5%88%86%E5%8C%85
