### ISSUE TITLE
redex中数据已经更新，子组件render无法拿到正确的值，但render会正常触发，

### ISSUE THREAD

**Issue by ivan-My** [NervJS/taro#1055]
此问题H5中没有，小程序中有次问题，不知道是哪里写错了？？
![image](https://user-images.githubusercontent.com/33918064/48245554-59209d80-e426-11e8-89b6-5a5cbadb835d.png)

![image](https://user-images.githubusercontent.com/33918064/48245579-83725b00-e426-11e8-9794-377910722398.png)

值名称为tabIndex,

**Comment by luckyadam** [comment]
能不能贴一下相关代码

**Comment by ivan-GM** [comment]
> 能不能贴一下相关代码


就是子组件获取不到reudx中更新的值，还是老值。我试了从父组件传递过来，是正常的

**Comment by ivan-GM** [comment]
![Uploading image.png…]()

**Comment by luckyadam** [comment]
还是贴一下相关代码吧

**Comment by zw130633** [comment]
子组件不用装饰器，用普通方式 connect 是可以的

**Comment by shenghanqin** [comment]
请给出更完整的示例代码。
