### ISSUE TITLE
WebkitLineClamp 编译解析错误

### ISSUE THREAD

**Issue by qiuziz** [NervJS/taro#1056]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

 <Text style={{WebkitLineClamp: WebkitLineClampList[index] || 3}}>{comment.comment}</Text>

-webkit-line-clamp在行内样式编译解析错误，缺少前面的短横线
试了下 -webkit开头样式在行内用大写方式写的话，解析缺少前面的-

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
<Text style={{WebkitLineClamp: 3}}>test</Text>
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

正确编译解析

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

![image](https://user-images.githubusercontent.com/13669987/48246139-29bf6000-e429-11e8-8e04-4ce8172cae6f.png)
![image](https://user-images.githubusercontent.com/13669987/48246144-2e841400-e429-11e8-87e8-a971e7a5a148.png)

**系统信息**

 - 操作系统: macOS 10.13.4 (17E202)
 - Taro 版本 Taro v1.2.0-alpha.3
 - Node.js 版本 v10.1.0
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

***react解析***

![image](https://user-images.githubusercontent.com/13669987/48246197-69864780-e429-11e8-9210-035ab90c2b9b.png)
![image](https://user-images.githubusercontent.com/13669987/48246186-5ffcdf80-e429-11e8-8a6d-368c94fd87b9.png)

**Comment by qiuziz** [comment]
@luckyadam 是的

刚看了你的回复，我以为是用的`yarn`导致的，但我换了npm还是一样的结果

我clone了一份别人的项目，地址在这 [here](https://github.com/EasyTuan/taro-msparis)

然后我在登录页加了上面的
```js
<Text style={{WebkitLineClamp: 3}}>test</Text>
```

截图如下：

![image](https://user-images.githubusercontent.com/13669987/48254858-0eaf1900-e446-11e8-878e-b2f5d39c8241.png)

我看了下我的项目和这个项目 发现
这是@EasyTuan的`package.json`
![image](https://user-images.githubusercontent.com/13669987/48254908-33a38c00-e446-11e8-9bb1-eb176e2b1009.png)

这是我的
![image](https://user-images.githubusercontent.com/13669987/48254927-3e5e2100-e446-11e8-85e4-1bd09660ed18.png)

是这里的依赖要升级吗，我在用Taro做公司的产品，怕升级会产生很多问题

**Comment by luckyadam** [comment]
升级到最新的 1.1.4 吧，是 OK 的

**Comment by luckyadam** [comment]
请问问题还存在么

**Comment by qiuziz** [comment]
@luckyadam 升级到最新版1.1.7 这个问题已经解决了 你们修复速度还是挺快的的哈 thx
