### ISSUE TITLE
input 设置 focus或者 auto-focus，进入页面后无法自动聚焦

### ISSUE THREAD

**Issue by 491467928** [NervJS/taro#10579]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/wwxxll/taro-test](https://gitee.com/wwxxll/taro-test)
**小程序基础库: 2.20.1**
**使用框架: Vue 3**

### 复现步骤
进入有设置focus的input的页面即可

### 期望结果
进入页面后input获得焦点，弹出输入键盘

### 实际结果
没有获得焦点

### 环境信息
```
 Taro CLI 3.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
Taro版本是3.3.12

**Comment by Chen-jj** [comment]
@491467928 和 Vue3 的逻辑有冲突而导致。

注意 Vue3 `shouldSetAsProp` 这个方法：

https://github.com/vuejs/vue-next/blob/e7b0a9d3cffc938d3add7dcde02d0991f60c6ec9/packages/runtime-dom/src/patchProp.ts#L33-L60

Vue3 判断 `focus` 这个属性在 `el` 中，就把它作为 dom property 设置了，其实 Taro 希望它能作为 attribute 设置。
