### ISSUE TITLE
Taro Vue H5 页面跳转是否支持页面过渡动画，能否提供实现思路？

### ISSUE THREAD

**Issue by 15380831711** [NervJS/taro#10573]
### 这个特性解决了什么问题？
打包成APP时，仿原生页面跳转过渡动画。

### 这个 API 长什么样？
Taro.navigateTo({
    animate: true,
})

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/app-config#animation)
