### ISSUE TITLE
载入本地图片错误

### ISSUE THREAD

**Issue by meishijie** [NervJS/taro#106]
import banner from '../banner.png'
下面是
`<Image src={banner}  />`

渲染层网络层错误：
VM554:2 Failed to load local image resource /pages/index/pages%C2%BAnner.png 
 the server responded with a status of 404 (HTTP/1.1 404 Not Found)

这个本地图片咋回事？

**Comment by luckyadam** [comment]
请看看图片路径是否正确

**Comment by meishijie** [comment]
尝试了在每个可能的文件夹里放了这张图片，还是载入不了。。。

**Comment by luckyadam** [comment]
能不能截图一下看看目录结构，以及图片的引用代码

**Comment by meishijie** [comment]
![image](http://btsousou.cn:8080/1.png)
![image](http://btsousou.cn:8080/2.png)

**Comment by luckyadam** [comment]
`@tarojs/cli` 版本多少，我这里不能复现

**Comment by meishijie** [comment]
0.0.45
是不是要更新版本？

**Comment by yuche** [comment]
是

**Comment by luckyadam** [comment]
@meishijie 更新到最新版本吧，之前在 windows 下引用图片是有点问题

**Comment by meishijie** [comment]
升级过后已经好了。谢谢！

**Comment by AKACC** [comment]
@luckyadam 现在使用1.2.0仍然出现这样的问题，前几天还是正常的，突然就不行了

VM2460:5 Failed to load local image resource /pages/.../somepic.png 
 the server responded with a status of 404 (HTTP/1.1 404 Not Found)

**Comment by JohnSmith0602** [comment]
@luckyadam 我在 mac 端下用的 1.2.3 版，碰到一个很奇怪的问题：

同一个文件夹下，引用 a 文件可以正确加载，引用 b 文件就会报引用404。即便用 yarn dev 重启后还是这样。

Failed to load local image resource ../images/logo.png 
the server responded with a status of 404 (HTTP/1.1 404 Not Found)

**Comment by JohnSmith0602** [comment]
和楼上一样，也是最开始引用时（确定）是正常的，这几天就怎么都不行了。而且我试着更改文件名，新的文件名都引用不到。只有最早的几个图片（在 tabbar 中被引用过）可以被加载到。

**Comment by AKACC** [comment]
@JohnSmith0602 @luckyadam 我发现有时候编译的时候，除了page底下的image文件夹会被复制到dist里，其他都没有。想要快速解决就手动将图片复制到dist相同路径即可。
