### ISSUE TITLE
h5页面跳转navigateTo不走complete回调

### ISSUE THREAD

**Issue by 15380831711** [NervJS/taro#10602]
### 相关平台
H5

### 复现仓库
[https://github.com/15380831711/tarovue3demo](https://github.com/15380831711/tarovue3demo)
**浏览器版本: Chrome**
**使用框架: Vue 2**

### 复现步骤
调用 Taro.navigateTo 进新页面 complete 回调不触发，离开页面时才触发。

### 期望结果
进新页面后触发 complete 回调。

### 实际结果
进新页面后未触发 complete 回调

### 环境信息
```
👽 Taro v3.3.12


  Taro CLI 3.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - E:\ProgramFiles\node-v14.17.3-win-x64\node.EXE
      Yarn: 1.22.10 - E:\ProgramFiles\node-v14.17.3-win-x64\yarn.CMD
      npm: 6.14.13 - E:\ProgramFiles\node-v14.17.3-win-x64\npm.CMD  
```

---
### 补充信息
@tarojs/router@3.3.0 这个版本正常。

**Comment by ZakaryCode** [comment]
demo 没有办法打开哦

**Comment by 15380831711** [comment]
上传了一个官方demo，vue3有同样的问题，taro用的最新版本。

**Comment by ZakaryCode** [comment]
> 上传了一个官方demo，vue3有同样的问题，taro用的最新版本。

好滴，晚点一起看看
