### ISSUE TITLE
【小程序】组件iconfont无法使用

### ISSUE THREAD

**Issue by Murphycx94** [NervJS/taro#1060]
我是在app.js中引入了下载到本地的iconfont文件

**app.js**
``` javascript
import './assets/iconfont/iconfont.css'
```
在page中是可以正常使用的
比如

**page/home/index.js**
``` html
<View className="iconfont icon-previous"></View>
``` 
就能渲染出一个返回箭头 <-

但是在component组件中使用同样的代码无法渲染
我看了一下样式好像是根本没有生效
.iconfont相关样式没有显示出来，貌似组件不能用app.js引用的全局样式，只有page文件中可以用

我单独在自定义组件（navbar.js）中引用了iconfont文件，是可以生效的
但是会有个问题，navbar编译完之后的wxss文件巨大（我这边打包完是29KB，就这么一个wxss），可以看出它是包含了iconfont文件
如果我有多个组件需要用到iconfont那成本太大了吧？

PS: 我使用的是阿里提供iconfont文件，下载到本地使用的
http://at.alicdn.com/t/font_619713_zb4f4ok1iw9.css

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/component-style.html

**Comment by Murphycx94** [comment]
> https://nervjs.github.io/taro/docs/component-style.html
> 组件可以受全局样式影响

OK，知道了，谢谢咯

**Comment by liuyunzyj** [comment]
@luckyadam 无法引用在线的iconfont?

**Comment by liuyunzyj** [comment]
https://user-images.githubusercontent.com/40293335/63144146-22665c00-c024-11e9-89c6-d41626338361.png

**Comment by liuyunzyj** [comment]
https://user-images.githubusercontent.com/40293335/63144186-4fb30a00-c024-11e9-9637-e819fb052c9d.png
https://user-images.githubusercontent.com/40293335/63144267-b506fb00-c024-11e9-86fb-fec85a7c0fa0.png
