### ISSUE TITLE
h5的编译配置中设置publicPath和router的basename，跳转页面时，例如A->B->C，在C页面点击返回，路由地址是B页面的地址，但是显示的内容却是A页面的内容，配置为空时就能正常返回

### ISSUE THREAD

**Issue by lhkg1988** [NervJS/taro#10616]
### 相关平台
H5

**浏览器版本: Chrome 95.0.4638.69 **
**使用框架: React**

### 复现步骤
浏览器访问：https://mobile-stage.gaojihealth.cn/benefitapp/pages/main/index?channelId=o2owxh5hy&token=qWR2TL04o12J0swNxPJaXeJo%2FgGcHNbYY550YW8RZqvSXViem7%2B7WHeFJMgIY5PIZjmtUeYol1g%3D

### 期望结果
期望能正常返回

### 实际结果
跳转页面时，例如A->B->C，在C页面点击返回，路由地址是B页面的地址，但是显示的内容却是A页面的内容

### 环境信息
```
👽 Taro v3.3.10


  Taro CLI 3.3.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - D:\User\hliu\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

**Comment by lhkg1988** [comment]
加了basename就不行，点返回页面显示就乱了

**Comment by luckyadam** [comment]
> 加了basename就不行，点返回页面显示就乱了

升级到最新版本看看行不行

**Comment by lhkg1988** [comment]
> > 加了basename就不行，点返回页面显示就乱了
> 
> 升级到最新版本看看行不行

刚试了，也不行
