### ISSUE TITLE
h5的router.customRoutes 自定义路由映射需要支持不同的后缀

### ISSUE THREAD

**Issue by tan2009216028** [NervJS/taro#10617]
### 这个特性解决了什么问题？
通过h5的router.customRoutes 自定义路由映射可以支持不同的后缀，有些不一样的服务器或者第三方服务器入口需要出现如index.html或者index.shtml等，目前的自定义路由规则不支持，如下面配置
router: {
    customRoutes: {
       "/pages/app/index "/index.html"
    }
}

### 这个 API 长什么样？
希望支持自定义路由后面可以映射自定义规则，如index、index.html、index.shtml等都支持

router: {
    customRoutes: {
       "/pages/app/index "/index.html"
    }
}

**Comment by ZakaryCode** [comment]
已经支持
