### ISSUE TITLE
taro3事件委托部分情况不能获取dataset

### ISSUE THREAD

**Issue by yang131323** [NervJS/taro#10610]
### 这个特性解决了什么问题？
背景说明：假设现在需要提供一个公共组件给外部使用，组件支持自定义按钮（可能会有多个），组件内部为了能够统一处理按钮的点击，会在所有按钮的上层添加一个事件，监听所有按钮触发的事件，同时自定义的按钮可能会有多级嵌套，按钮相关的数据都以data-形式放在自定义按钮的顶层，这时候点击e.target可能拿到的是内部的dom，而不是绑定data-数据的dom；更具体点，sku弹层就是我们要做的组件，底部按钮就是外部可以自定的内容，按钮假设是两层，`<View data-*><Text>立即购买</Text></View>`，这时候如果点击在text上，（e.target）获取不到data-*的值，e.currentTarget在组件上层也获取不到

### 这个 API 长什么样？
类似于h5的closest函数，可以往上找到最近的某个元素，然后取到它

**Comment by ZakaryCode** [comment]
Duplicate of #11530
