### ISSUE TITLE
根据教程使用原生模板会产生很多警告， [Vue warn]: Failed to resolve component: wxparse

### ISSUE THREAD

**Issue by 491467928** [NervJS/taro#10639]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/wwxxll/taro-test/tree/nativcComponet/](https://gitee.com/wwxxll/taro-test/tree/nativcComponet/)
**小程序基础库: 2.20.1**
**使用框架: Vue 3**

### 复现步骤
根据官网里Taro使用原生模块的步骤，运行起来，控制台里会显示警告

### 期望结果
不出现告警

### 实际结果
出现告警信息
vendors.js?t=wechat&s=1636683634182&v=5dee686f3238c427af7b49bb0e142a9b:8792 [Vue warn]: Failed to resolve component: wxparse
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index tid="pages/index/index?$taroTimestamp=1636686186319" > 
  at <App>

### 环境信息
```
Taro CLI 3.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

**Comment by guojianlan** [comment]
一样用github的源跑不动
![image](https://user-images.githubusercontent.com/9145416/141440059-28bbb279-664b-4121-867a-13175b9beed4.png)

**Comment by 491467928** [comment]
> 一样用github的源跑不动 ![image](https://user-images.githubusercontent.com/9145416/141440059-28bbb279-664b-4121-867a-13175b9beed4.png)

我的问题和你的不一样，我的不是报错，只是警告

**Comment by Chen-jj** [comment]
@491467928 报错信息写得比较清楚了：

```
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

意思大概是这个组件不属于 Vue 内部能识别的 H5 原生标签，所以会把它作为 Vue 组件来解析，如果你觉得他是一个合法的原生标签，配置一下 Vue 的 `compilerOptions.isCustomElement` ，就不会把它作为 Vue 组件解析了。

Taro 也可以搜集 `usingComponents` 里用到的组件去修改这个 vue-loader 的配置，但目前还没有做。你可以用 WebpackChain 去修改此配置，有兴趣的话也欢迎给我们提 PR 进行优化。

**Comment by guojianlan** [comment]
@Chen-jj 截图的问题是什么意思?

**Comment by Chen-jj** [comment]
> @Chen-jj 截图的问题是什么意思?

你的问题倒是没遇到过，新建个 issue，附上 demo，我们看看的

**Comment by guojianlan** [comment]
> > @Chen-jj 截图的问题是什么意思?
> 
> 你的问题倒是没遇到过，新建个 issue，附上 demo，我们看看的

demo?就是安装个cli,然后init project,再启动项目NODE_ENV=production taro build --type weapp --watch ,报错了
```bash
npm install -g mirror-config-china
npm install -g @tarojs/cli
taro init xxx
```
![image](https://user-images.githubusercontent.com/9145416/141444200-62a1de8f-dd98-4183-96ff-6f0bb22d889b.png)

**Comment by 491467928** [comment]
@Chen-jj 请问下如何用用WebpackChain 去修改此配置呢

**Comment by 491467928** [comment]
@Chen-jj ,已经解决了，十分谢谢

**Comment by zj-wukewei** [comment]
> https://gitee.com/wwxxll/taro-test/tree/nativcComponet/
请问你是如何解决的
