### ISSUE TITLE
input 表单不支持file 文件上传?

### ISSUE THREAD

**Issue by lihe6666** [NervJS/taro#1063]
我查看文档并没有看到 input 表单如何上传文件。

**Comment by jinjinjin0731** [comment]
麻烦看一下文档的咯[Taro.uploadFile(OBJECT)](https://nervjs.github.io/taro/docs/native-api.html#tarouploadfileobject)   H5 input 支持 file 属性，需要自行引入 SDK 做业务处理

**Comment by tourze** [comment]
我自己测试，需要使用 <input type="file" /> （注意是小写input），然后自己手动拿file list再处理。。。
其实这个真的应该官方做好兼容。。。H5跟小程序的差异越来越大了

**Comment by jinjinjin0731** [comment]
一个是调用小程序原生上传，一个是调用wx sdk ，sdk 这部分涉及到授权问题，这个如果这边封装的话，那么开发者就要遵循这个规则来写，还可能碰到各种问题，与其这样放开这个不是更加好？   
第二问题， 大写的 Input  没用拿到数据吗，请问下是什么版本，麻烦一个代码片段咯
@tourze

**Comment by tourze** [comment]
@jinjinjin0731 
刚测试，1.1.0-beta.13使用大写 <Input id='upload-file' type='file' accept='image/*' /> ，能正常使用input type=file了。

**Comment by JasonYan2015** [comment]
v1.2.4
在pc上好使
在真机上能出发选择文件和拍照 但是不触发组件的onChange事件，不能上传
使用小写的input原生组件的时候就可以正常触发和上传
