### ISSUE TITLE
良心云，ECS 服务器 4核8g5m，1900元/3年

### ISSUE THREAD

**Issue by aliyun11** [NervJS/taro#10630]
### 这个特性解决了什么问题？
传送门：https://curl.qcloud.com/AfDope6j
老用户，重新注册qq就可以白嫖了
![image](https://user-images.githubusercontent.com/93562479/141222885-f3815f4c-c9c5-4058-8cd8-11a0ecf75854.png)

### 这个 API 长什么样？
传送门：https://curl.qcloud.com/AfDope6j
老用户，重新注册qq就可以白嫖了
![image](https://user-images.githubusercontent.com/93562479/141222885-f3815f4c-c9c5-4058-8cd8-11a0ecf75854.png)

**Comment by luoboding** [comment]
鄙视
