### ISSUE TITLE
Taro 编译配置 SCSS 引入全局样式报错

### ISSUE THREAD

**Issue by Confettis** [NervJS/taro#10638]
### 相关平台
微信小程序

**小程序基础库: 2.20.2**
**使用框架: React**

### 复现步骤
- 配置文件添加相关配置

```js
scss: {
    resource: ['src/styles/variable.scss', 'src/styles/mixins.scss'],
    projectDirectory: path.resolve(__dirname, '..')
  },
```

- 在其他样式文件中直接使用 scss 变量

### 期望结果
其他样式文件无需引入即可使用全局样式

### 实际结果
报错：

```bash
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
```

### 环境信息
```
  Taro CLI 3.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - F:\nodejs\node.EXE
      Yarn: 1.22.17 - F:\nodejs\npm_global\yarn.CMD
      npm: 8.1.0 - F:\nodejs\npm.CMD
```

**Comment by tourze** [comment]
scss: {
    resource: ['src/styles/variable.scss', 'src/styles/mixins.scss'],
    projectDirectory: path.resolve(__dirname, '..')
  },
  
  修改为
  
  sass: {
    resource: ['src/styles/variable.scss', 'src/styles/mixins.scss'],
    projectDirectory: path.resolve(__dirname, '..')
  },

**Comment by lplsirlu** [comment]
更新variable.scss文件或者mixins.scss文件，全局变量不更新，要重新build一次，有没有更好的方法
