### ISSUE TITLE
希望能够根据project.kwai.json在编译快手小程序时生产project.config.json

### ISSUE THREAD

**Issue by hellozqy** [NervJS/taro#10636]
### 这个特性解决了什么问题？
希望能够根据project.kwai.json在编译快手小程序时生产project.config.json

### 这个 API 长什么样？
希望能够根据project.kwai.json在编译快手小程序时生产project.config.json

**Comment by Chen-jj** [comment]
@hellozqy 可以参考 Taro 仓库中其他小程序平台的插件，给 Taro 快手平台的插件增加一个属性即可，然后 PR 的。

**Comment by Chen-jj** [comment]
`project.ks.json`
