### ISSUE TITLE
copy.patterns  无效，无法迁移原生开发的代码 文件目录

### ISSUE THREAD

**Issue by leo2128** [NervJS/taro#10633]
### 这个特性解决了什么问题？
兼容字节原生小程序代码 和 taro编译后的代码

### 这个 API 长什么样？
希望能够兼容原生字节小程序代码 和 taro编译后的代码。

**Comment by ZakaryCode** [comment]
未验证到对应问题，如存在可提交新的 issue 并附上完整示例
