### ISSUE TITLE
taro 3.3.3升级到3.3.10后，taroAPI无法使用  

### ISSUE THREAD

**Issue by ywanhzy** [NervJS/taro#10656]
### 相关平台
微信小程序

**小程序基础库: 2.19.2**
**使用框架: React**

### 复现步骤
3.3.3 升级到3.3.10   
vendors.js:1 TypeError: O.a.getLocation is not a function 
vendors.js:1 TypeError: O.a.canIUse is not a function  
taroAPI无法使用  都报错

### 期望结果
正常运行

### 实际结果
报错

### 环境信息
```
👽 Taro v3.3.1

env: production

  Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.10 => 3.3.10 
      @tarojs/components: 3.3.10 => 3.3.10 
      @tarojs/mini-runner: 3.3.10 => 3.3.10 
      @tarojs/react: 3.3.10 => 3.3.10 
      @tarojs/runtime: 3.3.10 => 3.3.10 
      @tarojs/taro: 3.3.10 => 3.3.10 
      @tarojs/webpack-runner: 3.3.10 => 3.3.10 
      babel-preset-taro: 3.3.10 => 3.3.10 
      eslint-config-taro: 3.3.10 => 3.3.10 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^17.0.1 => 17.0.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 4.2.4
```

**Comment by imwangming** [comment]
你可以直接使用wx下的方法啊。例如wx. getLocation

**Comment by konka-king** [comment]
不知道 你 加没加 导入 import Taro from "@tarojs/taro";

**Comment by ywanhzy** [comment]
> 你可以直接使用wx下的方法啊。例如wx. getLocation

不止这个api  所有的都是    taro3.3.3版本都是正常的

**Comment by ywanhzy** [comment]
> 不知道 你 加没加 导入 import Taro from "@tarojs/taro";

有的    Taro3.3.3版本正常的

**Comment by Chen-jj** [comment]
CLI 和依赖版本保持一致

**Comment by ywanhzy** [comment]
> CLI 和依赖版本保持一致

👽 Taro v3.3.14

env: production

  Taro CLI 3.3.14 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.14 => 3.3.14 
      @tarojs/components: 3.3.14 => 3.3.14 
      @tarojs/mini-runner: 3.3.14 => 3.3.14 
      @tarojs/react: 3.3.14 => 3.3.14 
      @tarojs/runtime: 3.3.14 => 3.3.14 
      @tarojs/taro: 3.3.14 => 3.3.14 
      @tarojs/webpack-runner: 3.3.14 => 3.3.14 
      babel-preset-taro: 3.3.14 => 3.3.14 
      eslint-config-taro: 3.3.14 => 3.3.14 
      react: ^17.0.1 => 17.0.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 4.0.3

CLI 和依赖版本保持一致  也是报同样的错误      唯独用3.3.3版本就是正常的   不知道哪里出问题了

**Comment by hyongzheng** [comment]
后面解决了吗？

**Comment by ywanhzy** [comment]
> 

用3.4的最新版本正常
