### ISSUE TITLE
Taro的TARO_ENV_TYPE改成了枚举后，ENV_TYPE在使用时报【类型“TARO_ENV_TYPE”上不存在属性“WEAPP”】

### ISSUE THREAD

**Issue by bobsam** [NervJS/taro#10652]
### 相关平台
微信小程序

**小程序基础库: 2.20**
**使用框架: React**

### 复现步骤
PS：这是3.3.14版本！！！
直接ts使用 Taro.getEnv() === Taro.ENV_TYPE.WEAPP 时报错

### 期望结果
不报错

### 实际结果
实际是报错了

### 环境信息
```
 Taro CLI 3.3.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 7.21.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.8.3
```

**Comment by Chen-jj** [comment]
看来类型改得有问题，我们看看的

**Comment by ZakaryCode** [comment]
和枚举没有关系，改版后的 Taro 类型并不会挂载任何实体类，所以 enum 类型无法直接引用。针对该问题，将在下一个版本修复，可参考以下写法：

```ts
if (Taro.getEnv() === TaroGeneral.ENV_TYPE.WEAPP) {
  // TODO
}
```

**Comment by bobsam** [comment]
@Chen-jj @ZakaryCode 你们要是把 Taro.ENV_TYPE.WEAPP 这种调用方式去掉的话，麻烦发一个breakchange好吧？！现在用了你们的新版本，居然这种调用返回了undefined！！！

**Comment by wuhaohuang** [comment]
> ```ts
> TaroGeneral
> ```

TaroGeneral 在哪导入？
