### ISSUE TITLE
不同的端构建不同的目录 dist-wechat、/dist-alipay、/dist-swan

### ISSUE THREAD

**Issue by bluefox1688** [NervJS/taro#1066]
能否为不同的端构建不同的目录，例如 /dist-wechat、/dist-alipay、/dist-swan，且 watch 文件变化进行热更新。
这种特别适合多端同时调试

**Comment by tourze** [comment]
+1

**Comment by strawferry** [comment]
let outputRoot = "dist";
if(process.env.npm_config_argv.indexOf("h5")  > 0){
  outputRoot = "dist_h5";
}else if(process.env.npm_config_argv.indexOf("weapp")  > 0){
  outputRoot = "dist_we";
}else if(process.env.npm_config_argv.indexOf("swan")  > 0){
  outputRoot = "dist_swan";
}else if(process.env.npm_config_argv.indexOf("alipay")  > 0){
  outputRoot = "dist_al";
}


const config = {
  projectName: 'TraoDemo',
  date: '2018-11-30',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: outputRoot,

**Comment by strawferry** [comment]
可以自己在 config/index.js 文件里稍微这样修改,暂且能用,哈哈哈
let outputRoot = "dist";

if(process.env.npm_config_argv.indexOf("h5")  > 0){
  outputRoot = "dist_h5";
}else if(process.env.npm_config_argv.indexOf("weapp")  > 0){
  outputRoot = "dist_we";
}else if(process.env.npm_config_argv.indexOf("swan")  > 0){
  outputRoot = "dist_swan";
}else if(process.env.npm_config_argv.indexOf("alipay")  > 0){
  outputRoot = "dist_al";
}


const config = {
  outputRoot: outputRoot,
}

**Comment by Garfield550** [comment]
1.3.0-beta.5 已经支持 https://github.com/NervJS/taro/issues/2947#issue-440404914

@luckyadam 老李，这个可以关闭了。

**Comment by cncolder** [comment]
@Garfield550 你说反了, 是原本支持, 在 1.3.0-beta.5 中又移除了.

https://github.com/NervJS/taro/commit/b9b749f

**Comment by Garfield550** [comment]
> @Garfield550 你说反了, 是原本支持, 在 1.3.0-beta.5 中又移除了.
> 
> [b9b749f](https://github.com/NervJS/taro/commit/b9b749f)

1.3.5-beta.5 开始恢复之前的编译操作，文件会直接编译到 config 中配置的 outputRoot 目录下，如果需要多端同时调试，可以修改配置为

```js
outputRoot: `dist/${process.env.TARO_ENV}`
```

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/58932238-87d0dd80-8795-11e9-98cf-6051d56caf84.png)
我难不成还能骗你们吗

**Comment by cncolder** [comment]
是我理解反了.

1.3.0-beta.4 会自动编译到各端目录下, 无需配置.

**Comment by Garfield550** [comment]
> 是我理解反了.
> 
> 1.3.0-beta.4 会自动编译到各端目录下, 无需配置.

老李发 beta 5 的那天，在挨个群里通知了一下，因为有人不知道 beta 4 的改动，说编译失败。

**Comment by shenghanqin** [comment]
@bluefox1688 我理解的是最新版本可以支持这个特性的，请尝试。
