### ISSUE TITLE
Vue DevTools 插件导致 @click 及 NutUI 组件的事件失效

### ISSUE THREAD

**Issue by iceDays** [NervJS/taro#10677]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/iceDays/dev-tools-demo](https://gitee.com/iceDays/dev-tools-demo)
**小程序基础库: 2.20.2**
**使用框架: Vue 3**

### 复现步骤
$ taro init myApp  # 选择 NutUI
$ yarn add --dev @tarojs/plugin-vue-devtools
在 Taro 编译配置中配置使用 @tarojs/plugin-vue-devtools：

### 期望结果
不影响 NutUi 的事件 以及 Icon 显示

### 实际结果
安装 Vue DevTools  后, 
- @click 事件失效
- NutUi 的事件失效
- Icon 无法显示

### 环境信息
```
👽 Taro v3.3.14


  Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.7 - d:\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.15 - d:\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
最新版本应该已经修复了

<img width="1735" alt="image" src="https://user-images.githubusercontent.com/11807297/171371927-62701801-5118-4a94-9e16-4b8ce4477e6e.png">
