### ISSUE TITLE
使用browser模式跳转路由，立刻点返回，路由变了，视图没变

### ISSUE THREAD

**Issue by yaoshuaibing** [NervJS/taro#10678]
### 相关平台
H5

**浏览器版本: 95.0.4638.69（正式版本） （64 位）**
**使用框架: Vue 2**

### 复现步骤
在borwser模式下，点击按钮跳转一个新页面，立马点击浏览器的返回，或者手机的物理按键返回，路由变了，视图不更新。

### 期望结果
期望视图跟随路由同时更新

### 实际结果
路由变化了，视图没变。

### 环境信息
```
 Taro CLI 3.3.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\yaoshuaibing\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
在app.js 
 window.addEventListener("popstate", () => {
            const id = Taro.getCurrentInstance().router.path;
            const ele = document.getElementById(id);
            if ((ele.style.display = "none")) {
                Array.from(document.getElementsByClassName("taro_page")).forEach((el) => {
                    el.style.display = "none";
                });
            }
            ele.style.display = "block";
        });j
监听回退，判断是否视图更新，即可

**Comment by ZakaryCode** [comment]
需要升级到 3.3.15+ 版本
