### ISSUE TITLE
dev和build环境下的逻辑乱套，并且无法获取模板中的缓存值

### ISSUE THREAD

**Issue by 594904292** [NervJS/taro#1067]
**问题描述**
在同一个域名下，h5应用需要从模板中一个变量"ownerBusinessId","33"，在dev和build环境下读取数据缓存出现了不同的情况；
通过window.localStorage获取
1，在条件process.env.TARO_ENV === 'h5'模式下可以获取； 
2,  在build下无法进行process.env.TARO_ENV === 'h5' 的逻辑； 

通过Taro.getStorageSync获取
1，获取不到模板中设定的key为"ownerBusinessId"的值； 
2,  可以获取到Taro.setStorageSync('testid', 'taro')设定的testid值为taro； 
**复现步骤**
[复现问题的步骤]
1. 模板中添加
 <script language="JavaScript">
      var storage=window.localStorage;
      localStorage.setItem("ownerBusinessId","33") ;
  </script>
2. app.js根据环境判断是否读取这个"ownerBusinessId"缓存值

[或者可以直接贴源代码，能贴文字就不要截图]

模板中的JS
```js
 <script language="JavaScript">
      var storage=window.localStorage;
      localStorage.setItem("ownerBusinessId","33") ;
  </script>
```

APP中读取ownerBusinessId逻辑JS
```js
if (process.env.TARO_ENV === 'weapp') {
  Taro.setStorageSync('showmodel', 'weapp');
} else if (process.env.TARO_ENV === 'h5') {
  Taro.setStorageSync('showmodel', 'h5');

  var storage = window.localStorage;
  console.log('window.localStorage:' + storage.ownerBusinessId);//dev模式下能获取,build无法获取

  const resaa = Taro.getStorageInfoSync();
  console.log('keys:' + resaa.keys);

  const data = Taro.getStorageSync('ownerBusinessId');
  console.log('Taro.getStorageSync id:' + data); //错误获取不到值33

  Taro.setStorageSync('ownerBusinessId', storage.id);

  console.log("Taro.setStorageSync('testid', 'taro')");
  Taro.setStorageSync('testid', 'taro');
  const testdata = Taro.getStorageSync('testid'); //正确，通守setStorageSync赋的值可以获取
  console.log('Taro.getStorageSync testid:' + testdata);
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
希望在h5模式下能获取到模板中的值

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/13557492/48297695-0f00f000-e4ea-11e8-827d-f0df77ae3b7b.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
编译模式把console.log语句全清了，无法调试； 
在build模式下无法进行h5的判断逻辑，全走了weapp模式

**Comment by luckyadam** [comment]
表现正常，无法复现

**Comment by luckyadam** [comment]
原生 localStorage api 设置的值无法通过 Taro.getStorage 取到~

**Comment by jinjinjin0731** [comment]
hello ~ 这个在群里已经回复你咯，这个 issue 可以关了吗~
