### ISSUE TITLE
RN下新建页面，push后报错

### ISSUE THREAD

**Issue by zhiqingchen** [NervJS/taro#10688]
### 相关平台
React Native

![image](https://user-images.githubusercontent.com/1876158/142585825-1943b00e-8dd8-4fab-9f66-11c2abe6d5b3.png)

**使用框架: React**

### 复现步骤
新建一个页面，调用
Taro.navigateTo

### 期望结果
打开页面

### 实际结果
 ERROR  The action 'PUSH' with payload {"name":"pagesFormRateIndex","params":{}} was not handled by any navigator.

Do you have a screen named 'pagesFormRateIndex'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/5.x/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.

This is a development-only warning and won't be shown in production.

### 环境信息
```
👽 Taro v3.3.11


  Taro CLI 3.3.11 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.12.0 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
      npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.12 => 3.3.12
      @tarojs/components: 3.3.12 => 3.3.12
      @tarojs/mini-runner: 3.3.12 => 3.3.12
      @tarojs/react: 3.3.12 => 3.3.12
      @tarojs/runtime: 3.3.12 => 3.3.12
      @tarojs/taro: 3.3.12 => 3.3.12
      @tarojs/webpack-runner: 3.3.12 => 3.3.12
      babel-preset-taro: 3.3.12 => 3.3.12
      eslint-config-taro: 3.3.12 => 3.3.12
      react: ^17.0.2 => 17.0.2
      react-native: ^0.66.1 => 0.66.1
    npmGlobalPackages:
      typescript: 4.2.3
```

**Comment by zhiqingchen** [comment]
待排查，临时解决方案：

```
yarn dev:rn --reset-cache
```

**Comment by kinger906** [comment]
问题解决了吗？我这边也报同样的错 Taro版本是3.4.2

**Comment by zhiqingchen** [comment]
> 问题解决了吗？我这边也报同样的错 Taro版本是3.4.2

`yarn dev:rn --reset-cache` 重启下试试

**Comment by LiXiaoLongsgithub** [comment]
@zhiqingchen 你好，我也遇到了这个问题。
yarn dev:rn --reset-cache重启后还是不行。
![image](https://user-images.githubusercontent.com/39393823/158753468-1c64289d-c60e-4674-af3c-82f5640b58f4.png)

**Comment by zhiqingchen** [comment]
> @zhiqingchen 你好，我也遇到了这个问题。
> 
> yarn dev:rn --reset-cache重启后还是不行。
> 
> ![image](https://user-images.githubusercontent.com/39393823/158753468-1c64289d-c60e-4674-af3c-82f5640b58f4.png)
> 
> 

你这个应该用switchtab

**Comment by LiXiaoLongsgithub** [comment]
@zhiqingchen 谢谢，谢谢。刚接触Taro，耽误你时间了。

**Comment by zhiqingchen** [comment]
不客气
