### ISSUE TITLE
新建vue3项目时出错

### ISSUE THREAD

**Issue by Eusen** [NervJS/taro#10687]
### 相关平台
H5

**浏览器版本: -**
**使用框架: Vue 3**

### 复现步骤
npm i -g @tarojs/cli

taro init vue3-test

👽 Taro v3.3.14

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！ test
? 请选择框架 Vue3
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板源 Github（最新）
√ 拉取远程模板仓库成功！
? 请选择模板 vue3-NutUI（使用 NutUI3.0 的模板）

✔ 创建项目: vue2-test
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\babel.config.js
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\global.d.ts
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\package.json
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\project.config.json
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\project.tt.json
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\tsconfig.json
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\config\dev.js
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\config\index.js
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\config\prod.js
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\src\app.config.ts
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\src\app.scss
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\src\app.ts
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\src\index.html
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\src\pages\index\index.config.ts
✔ 创建文件: C:\Users\Super\Workspace\Taro\vue2-test\src\pages\index\index.vue

√ cd vue2-test, 执行 git init
× 安装项目依赖失败，请自行重新安装！
Error: Command failed: yarn install
warning @tarojs/components > omit.js > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
error Couldn't find any versions for "@tarojs/plugin-html" that matches "3.3.14"

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn install'
}
创建项目 vue2-test 成功！
请进入项目目录 vue2-test 开始工作吧！😝

### 期望结果
期望能正常工作

### 实际结果
"@tarojs/plugin-html" 没有对应的版本 "3.3.14"，
目前更换为 3.3.13 可以正常安装，
但是在小程序上没有效果，代码中的 img 标签没有正确转化为 image

### 环境信息
```
👽 Taro v3.3.14


  Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - C:\Users\Super\.nvm\v14.17.4\node.EXE
      Yarn: 1.22.17 - C:\Users\Super\.nvm\v14.17.4\yarn.CMD
      npm: 6.14.14 - C:\Users\Super\.nvm\v14.17.4\npm.CMD
```

**Comment by Chen-jj** [comment]
@Eusen 本地 npm 或 yarn 源的问题，自己改一下源吧
