### ISSUE TITLE
小程序，通过js增加点击事件

### ISSUE THREAD

**Issue by zx0722** [NervJS/taro#10683]
### 这个特性解决了什么问题？
为元素增加事件监听

### 这个 API 长什么样？
小程序获取元素，为元素增加事件监听

**Comment by Chen-jj** [comment]
现在就支持的，你完全可以当是 Web 环境，`document.createElement` 创建节点，`addEventListener` 创建事件监听。不想用这些原生 API 还可以用 jQuery：https://docs.taro.zone/docs/jquery-like#on
