### ISSUE TITLE
如何禁用h5自动打开浏览器

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#1069]
**问题描述**
想禁用浏览器自动打开, 但是发现两处配置均不生效.

**复现步骤**
1. `yarn dev:h5`

```js
    h5: {
        devServer: {
            open: false,
        },
        /**
         * @param {webpackChain} chain
         * @param {webpack} webpack
         */
        webpackChain(chain, webpack) {
            chain.devServer.set('open', false)
        },
    },
```

**期望行为**
自动打开浏览器的功能应该源于 webpack 吧? 是这里的配置被后续处理覆盖了吗?

**报错信息**

**系统信息**

 - 操作系统: OSX
 - Taro 版本 v.1.1.64
 - Node.js 版本 v11
 - 报错平台 [h5]

**补充信息**

**Comment by Littly** [comment]
感谢反馈~  已提交 127839f  下个版本修复
