### ISSUE TITLE
[编译配置]enableExtract不生效

### ISSUE THREAD

**Issue by ken-alx** [NervJS/taro#10715]
### 相关平台
H5

### 复现仓库
[https://github.com/ken-bug-reporter/taro-css-extract.git](https://github.com/ken-bug-reporter/taro-css-extract.git)
**浏览器版本: chrome 95**
**使用框架: Vue 3**

### 复现步骤
1、H5的配置项
 enableExtract: true,
        miniCssExtractPluginOption: {
            filename: '[name].[hash].css',
            chunkFilename: '[name].[hash].css'
        },

2、执行 npm run build:h5
3、css文件并没有从js中拆分出来

### 期望结果
单独打包成一个css文件

### 实际结果
不存在css文件，依然将css打包至app.js中

### 环境信息
```
Taro CLI 3.3.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.14 => 3.3.14
      @tarojs/components: 3.3.14 => 3.3.14
      @tarojs/mini-runner: 3.3.14 => 3.3.14
      @tarojs/runtime: 3.3.14 => 3.3.14
      @tarojs/taro: 3.3.14 => 3.3.14
      @tarojs/webpack-runner: 3.3.14 => 3.3.14
      babel-preset-taro: 3.3.14 => 3.3.14
      eslint-config-taro: 3.3.14 => 3.3.14
    npmGlobalPackages:
      typescript: 4.4.2
```

**Comment by SilentTiger** [comment]
我用的 "@tarojs/components": "3.3.19"，打开 enableExtract 之后 h5 的编译结果确实生成了 app.css 文件，但是 @tarojs/components 的部分样式仍然是用 js 直接插入到 style 标签里的。
看起来就是打包的时候样式没有抽干净。
如下图所示，head 中生成了很多 style 标签，编译出的 css 其实下面有单独用 link 加载。
![image](https://user-images.githubusercontent.com/764862/151689679-2827411c-439b-418a-8937-93f56f06dc91.png)

**Comment by SilentTiger** [comment]
![image](https://user-images.githubusercontent.com/764862/151690550-325eade2-e5b8-4687-ba27-29b5d970d48e.png)

如上图所示，355 行针对 enableExtract 的值在 styleLoader 和 extractCssLoader之间二选一了，所以 enableExtract 为 true 的时候确实有 css 文件生成，因为用了 extractCssLoader。但是 334行的 topStyleLoader 并没有被 enableExtract 影响，所以 topStyleLoader 引入的样式不管 enableExtract 是不是 true，都是以 style 标签的形式引入了。应该就是这里的问题了。

@ZakaryCode

**Comment by SilentTiger** [comment]
![image](https://user-images.githubusercontent.com/764862/151691479-9394577c-c2f3-4d05-b3b5-220ea3569932.png)

我在我自己的项目里面加上这两行配置暂时解决了我的问题，weui 相关的样式经过这样配置之后就都进到 css 文件里面了，但看起来页面上仍然有 js 生成的 style 标签，可能别的地方还有问题。

**Comment by ZakaryCode** [comment]
taro 模块相关 css 确实是会跳过 extractCss 逻辑，通过 js 插入，如果需要屏蔽这部分逻辑可以自行配置

> ![image](https://user-images.githubusercontent.com/764862/151691479-9394577c-c2f3-4d05-b3b5-220ea3569932.png)
