### ISSUE TITLE
swiper在有设置tabbar的情况下宽度计算不对

### ISSUE THREAD

**Issue by KaierChou** [NervJS/taro#1071]
**问题描述**
swiper在有设置tabbar的情况下宽度计算不对. 不设置tabbar则没问题.

**复现步骤**
![error](https://user-images.githubusercontent.com/24623866/48303540-42716800-e546-11e8-9771-d007b224795f.png)
![ok](https://user-images.githubusercontent.com/24623866/48303563-9419f280-e546-11e8-920d-ea90932831ec.png)

**期望行为**
fix it

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [ v.1.1.4]
 - Node.js 版本 [10.7]
 - 报错平台 [h5]

**Comment by jinjinjin0731** [comment]
里面是个啥。。。  麻烦提供一个可复现的代码片段咯~

**Comment by jinjinjin0731** [comment]
样式呢。 样式文件有设置吗

**Comment by KaierChou** [comment]
> 样式呢。 样式文件有设置吗
没做任何更改和新增.

我就是怕是自己的项目样式的问题,所以才init一个新的项目试验看看..结果还是那样

**Comment by jinjinjin0731** [comment]
ok 我明天看一下。

**Comment by poorel** [comment]
> ok 我明天看一下。

补充：自然滚动会白屏，手动滚动之后再让其自然滚动 swiper会卡死

**Comment by zantop** [comment]
同遇到了上述问题

**Comment by q773592519** [comment]
同遇到了上述问题

**Comment by jinjinjin0731** [comment]
已修复
