### ISSUE TITLE
@tarojs/runtime 热更新时报错

### ISSUE THREAD

**Issue by nicainev** [NervJS/taro#10722]
### 相关平台
微信小程序

**小程序基础库: 2.19.2**
**使用框架: React**

### 复现步骤
开发编辑代码时，热重载报错，Cannot set property '$taroTimestamp' of undefined
    at Ui.onLoad (.._src_dsl_common.ts:106)，导致热更新不能成功

### 期望结果
预期可以直接在开发者工具中运行最新代码

### 实际结果
报错导致热重载失败，必须得手动编译一遍

### 环境信息
```
Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
提供一下 demo

**Comment by nicainev** [comment]
demo需要哪些信息？我还没有个人的appid，公司项目不好泄露。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro] @tarojs/runtime 热更新时报错 (Issue #10722)





 
提供一下 demo
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rquanx** [comment]
直接初始化出来的项目也热更不了

![image](https://user-images.githubusercontent.com/36622981/143273171-f9a3d54c-9e27-4202-9f0c-f676ed2f8b56.png)

**Comment by rquanx** [comment]
怀疑是因为脚本被拦截了

![image](https://user-images.githubusercontent.com/36622981/143276547-912ec83d-9e6a-4a08-a42a-a5ff6fa8d2bf.png)

**Comment by rquanx** [comment]
options是undefined

![image](https://user-images.githubusercontent.com/36622981/143281869-717bcfe8-a8a2-4b85-965e-4abe19860759.png)

**Comment by rquanx** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
看来开发者工具热更新时，在 onLoad 触发是没有传递 options 参数。可以在 `dist/taro.js` 中为 onLoad 的 options 参数设置一个默认值试试还有没有其它问题。Taro 下个版本会为 options 增加默认值。

![image](https://user-images.githubusercontent.com/36622981/143281869-717bcfe8-a8a2-4b85-965e-4abe19860759.png)

**Comment by rquanx** [comment]
默认值试过了，加了不会报错，但是热更新无效，页面不会更新
![image](https://user-images.githubusercontent.com/36622981/143779302-aadeaad6-8593-40d3-9dd6-0c8429c0d3e4.png)

**Comment by wong2** [comment]
同遇到

**Comment by GreatAuk** [comment]
+1

**Comment by niyingg** [comment]
同遇到热更新不起作用，代码变动就报 Cannot set property '$taroTimestamp' of undefined,要手动编译，请问解决了吗?
小程序基础库: 2.21.0
使用框架: React
taro 3.3.16

**Comment by Chen-jj** [comment]
> @Chen-jj 默认值试过了，加了不会报错，但是热更新无效，页面不会更新 ![image](https://user-images.githubusercontent.com/36622981/143779302-aadeaad6-8593-40d3-9dd6-0c8429c0d3e4.png)

@rquanx JS 热重载失败是因为 Webpack 对 modules 有缓存：

```js
// dist/runtime.js (webpack runtime.js)
function __webpack_require__(moduleId) {
  // Check if module is in cache
  if(installedModules[moduleId]) {
    return installedModules[moduleId].exports;
  }
  // ......
}
```

可惜微信小程序没有暴露热更新的监听方法，否则可以统一处理 Webpack 缓存。

**目前，开发者如果需要使用 JS 的热更新，可以在页面文件最后加上以下代码：**

```js
// 清除 Webpack 相关缓存
if (process.env.NODE_ENV !== 'production') {
  const cache = __webpack_require__.c
  Object.keys(cache).forEach(item => {
    if (item.indexOf('pages/index/index') !== -1) delete cache[item]
  })
}
```

Taro 后续会考虑增加一个配置，为开发者自动加上上述代码以兼容微信小程序的热更新。

最后，JS 只有 Page 页面文件修改后才会触发热更新，依赖的组件修改后则不会触发热更新。（使用原生代码也测试过，应该是微信小程序的热更新还不支持监听页面依赖的文件）

**Comment by cnxzq** [comment]
react 下遇到了同样问题 ，暂时手动改了这个文件

`node_modules\@tarojs\runtime\dist\runtime.esm.js`

```js
function createPageConfig(component, pageName, data, pageConfig) {
// ... 省略部分代码
    const config = {
        onLoad(options, cb) {
        // 改成上面代码成下面这句
        onLoad(options={}, cb) {
```

**Comment by Chen-jj** [comment]
Taro v3.4 会加入 `mini.hot` 配置，能自动加上这段兼容代码：https://docs.taro.zone/docs/next/mini-troubleshooting#%E7%83%AD%E9%87%8D%E8%BD%BD

**Comment by wong2** [comment]
感谢，现在要如何使用带了这个功能的 v3.4 ？看npm的beta版本还是老的

**Comment by Chen-jj** [comment]
> 感谢，现在要如何使用带了这个功能的 v3.4 ？看npm的beta版本还是老的

@wong2 v3.4 下个版本可能在下周发，目前就先手动在页面底部加上我上面提到的 Webpack 缓存清理代码咯

**Comment by Chen-jj** [comment]
> 感谢，现在要如何使用带了这个功能的 v3.4 ？看npm的beta版本还是老的

@wong2 v3.4 下个版本可能在下周发，目前就先手动在页面底部加上我上面提到的 Webpack 缓存清理代码咯

**Comment by wong2** [comment]
ok

**Comment by yuanhaozzz** [comment]
![image](https://user-images.githubusercontent.com/30517662/183358756-65594a43-16ee-4c4c-95e6-109832fa326e.png)
把热重载关掉就不报错了 - -

**Comment by zhoulujun** [comment]
这个问题，3.6.11，使用nutui， compiler: {
    type: 'webpack5',
    prebundle: {
      enable: false,
    },
  },
还是不能热更新

**Comment by SxmAyuyu** [comment]
3.6.17依旧不能热重载

**Comment by shaohuahuang** [comment]
> 这个问题，3.6.11，使用nutui， compiler: { type: 'webpack5', prebundle: { enable: false, }, }, 还是不能热更新

我用的3.6.20也不能热重载

**Comment by shaohuahuang** [comment]
@Chen-jj 热重载的问题还是存在

**Comment by kemplaw** [comment]
still not work

**Comment by GreatAuk** [comment]
开发几年了，好像就没有用过热更新，都是全量刷新页面。这个问题只是个别人有吗？

**Comment by ikeepo** [comment]
4.0.8好像还是不行，提示ts: Object literal may only specify known properties, and 'hot' does not exist in type 'IMiniAppConfig<"webpack5">'. ？？？还是我搞错了？

**Comment by vaynevayne** [comment]
就说有人成功过吗？

**Comment by gezichenshan** [comment]
> 我看到uniapp 可以，但是taro （3.6.34）不行，随着页面变多，修改里层的页面简直是噩梦。

可以“普通模式”处点击“添加编译模式”。就能停留在当前页
