### ISSUE TITLE
taro小程序端编译日志输出加入日志级别控制功能

### ISSUE THREAD

**Issue by sjhleo** [NervJS/taro#10731]
### 这个特性解决了什么问题？
编译时打印日志太多，比较重要的是一些编译报错的日志，目前日志信息太多，如果不注意看报错信息就被刷没了。

### 这个 API 长什么样？
希望可以在启动时添加输出日志级别参数。官方可以考虑支持么，目前使用的版本是1.3.45（如果不行的话，我们可以提pr，调整printLog方法的实现）

**Comment by Chen-jj** [comment]
欢迎 PR 呀~

**Comment by sjhleo** [comment]
> 
请问1.3.45版本是哪个分支打出的，我看目前v1.3分支的代码与项目使用的1.3.45代码有出入，pr提到哪个分支呢
