### ISSUE TITLE
如何设置histroy的路由mode?

### ISSUE THREAD

**Issue by li405744717** [NervJS/taro#1073]

**Comment by Littly** [comment]
h5路由的重构版本将会提供hash/browser模式的选择，位于router2.0分支。目前这个版本处于测试阶段，测试通过后会发布~

**Comment by LOWINC** [comment]
@Littly   现在可以使用 history模式了吗 ？

**Comment by luckyadam** [comment]
@LOWINC 1.2 正式版本可以

**Comment by isNeilLin** [comment]
> @LOWINC 1.2 正式版本可以

请问在哪里配置？

**Comment by Littly** [comment]
文档在此：https://nervjs.github.io/taro/docs/config-detail.html#h5router

**Comment by isNeilLin** [comment]
@Littly  谢谢！
