### ISSUE TITLE
@tarojs/webpack-runner 升级 webpack 5

### ISSUE THREAD

**Issue by panhezeng** [NervJS/taro#10732]
### 这个特性解决了什么问题？
很多第三方插件库，已经升级 webpack 5，并且不向下兼容。

### 这个 API 长什么样？
期望 @tarojs/webpack-runner dependencies   "webpack": "4.46.0" to  "webpack": "^5.0.0"

**Comment by panhezeng** [comment]
基于webpack 5 的 vue cli v5 已经进入候选版本，即将发布正式版。
https://github.com/vuejs/vue-cli/releases

基于webpack 5 , vue 3 的 quasar v2 也早就发布了

**Comment by panhezeng** [comment]
Webpack 5 发布(2020-10-10) ，已经发布一年多了

**Comment by Chen-jj** [comment]
近期会进行升级~

**Comment by bobsam** [comment]
@Chen-jj 请问有vite的支持计划吗？

**Comment by gjc9620** [comment]
期待能用esbuild实现

**Comment by panhezeng** [comment]
> 近期会进行升级~

希望能和3.4一起发布

**Comment by Chen-jj** [comment]
3.5 已支持
