### ISSUE TITLE
在 h5 环境上获得空标签的 View 组件的 rect width 为 0

### ISSUE THREAD

**Issue by tgioer** [NervJS/taro#10749]
### 相关平台
H5

### 复现仓库
[https://github.com/taroify/taro3315-viewrect](https://github.com/taroify/taro3315-viewrect)
**浏览器版本: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36**
**使用框架: React**

### 复现步骤

```tsx
export default function Index() {
  const viewRef = useRef<HTMLDivElement>()
  const divRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    console.log("view rect", viewRef.current?.getBoundingClientRect())
  }, [])

  useEffect(() => {
    console.log("div rect", divRef.current?.getBoundingClientRect())
  }, [])

  return (
    <>
      <View ref={viewRef}/>
      <div ref={divRef}/>
    </>
  )
}
```

### 在 H5 上的效果

<img src="https://raw.githubusercontent.com/taroify/taro3315-viewrect/main/viewrect.png" width="800" />

### 期望结果
能获得到 width 的宽度

### 实际结果
获得到 width 的宽度为 0

### 环境信息
```
� Taro v3.3.15


  Taro CLI 3.3.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - C:\Programs\nodejs\node-v14.17.1-win-x64\node.EXE
      Yarn: 1.22.11 - C:\Programs\nodejs\node\yarn.CMD
      npm: 6.14.13 - C:\Programs\nodejs\node-v14.17.1-win-x64\npm.CMD

```

**Comment by Chen-jj** [comment]
@tgioer 用 `useReady`，`useEffect` 第一次触发的时机太早了，只是 React 完成了 `<taro-view-core>` 的渲染，创建了其 DOM 节点。但还需要 Stencil 完成该 WebComponent 的创建，才算真正渲染完成。

```js
useReady(() => {
  console.log("view rect", viewRef.current?.getBoundingClientRect())
}, [])
```

**Comment by tgioer** [comment]
> 

使用 useEffect(()=> nextTick())

呢？
