### ISSUE TITLE
Taro开发函数式组件时使用wxs，callMethod调用不生效？

### ISSUE THREAD

**Issue by da-xiu** [NervJS/taro#10744]
### 这个特性解决了什么问题？
频繁页面交互问题

### 这个 API 长什么样？
https://developers.weixin.qq.com/miniprogram/dev/framework/view/interactive-animation.html中callMethod

**Comment by luckyadam** [comment]
Taro 版本多少

**Comment by da-xiu** [comment]
你好，版本号2.2.13

**Comment by da-xiu** [comment]
我是按照https://github.com/NervJS/taro/issues/2959来操作，但是最后一步实现调用taro组件方法时，未能成功

**Comment by Runc2333** [comment]
![Image](https://github.com/user-attachments/assets/67895ea0-9a7e-4007-93c0-8614b08c963d)

![Image](https://github.com/user-attachments/assets/a89ed631-8005-4555-9952-c35f83d3a512)

给后续踩坑的朋友指路，可以通过在组件上绑定自定义事件，在wxs里通过ownerInstance.selectComponent选中绑定了事件的组件，获取dataset，然后触发taro的eh（event handler）方法，构造一个对象触发绑定的自定义事件即可。


核心在获取绑定了事件的组件的sid（taro通过sid来确定事件应该分发给哪个组件），currentTarget.dataset.sid需要和你绑定了自定义事件的sid一致。

**Comment by tsinglemon** [comment]
> 结合楼上同志 [[Runc2333](https://github.com/Runc2333) ](https://github.com/NervJS/taro/issues/10744#issuecomment-2599141551) 的做法，给组件添加自定义方法，然后在wxs触发


**背景**

用wxs监听swiper滑动事件，正常只能在wxs处理，然后通过callMethod调用逻辑层方法。
由于在taro里的callMethod失效，所以可以在组件自定义事件间接调用页面方法。


**目标**

既可以让wxs在渲染层处理高频操作，又可以回调原有组件的自定义事件处理逻辑层的状态。


**具体步骤**

 0. 使用wxs需要先在src/config/index.ts里配置
```ts
{
  mini: {  
    experimental: { 
      compileMode: true 
    } 
  } 
} 
```

1. 在页面组件自定义一个事件
```jsx
// index.tsx

// compileMode 开启编译模式
<View compileMode>
	// 导入wxs
	<Script src='../../utils/wxs/scroll.wxs' module='tools' />
	<Swiper
		// swiper自身的事件
		onTransition={tools.onSwiperTransition}
		// 自定义的事件，由wxs里的onSwiperTransition方法触发
		onTransition_wxs={ (e) => { console.log(e) } }
	>
	</Swiper>
</View>
```

2. 在wxs里通过taro的 `eh` (event handler)，指定当前组件并携带detail参数触发自定义事件
```jsx
// scroll.wxs
module.exports.onSwiperTransition = function (event, ownerInstance) {

  // ”eh“ 是taro的
  ownerInstance.callMethod('eh', {
    // 指定调用哪个组件
    target: event.target, 
    // 指定事件名。为了与原事件名区分开，需加上自定义后缀 ”_wxs“ 
    type: event.type + '_wxs', 
    // 自定义携带参数
    detail: {
      isMove: true
    }
  })
  
}
```
