### ISSUE TITLE
启动Android应用壳子报错  Metro Bundler Server 是正常启动的

### ISSUE THREAD

**Issue by Jasonzzh** [NervJS/taro#10750]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
先编译预览模式 npm run dev:rn  然后启动安卓应用壳子 react-native run-android

### 期望结果
成功打开app

### 实际结果
唤起了模拟器  但是安装app失败

### 环境信息
```
� Taro v3.3.1


  Taro CLI 3.3.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - D:\nodejs\npm.CMD
```

---
### 补充信息
Android 启动报错信息
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\codeTest\taro-native-shell\android\settings.gradle' (C:\Users\Administrator\.gradle\caches\6.9\scripts\6qag3w8j5bsrbuely8fjkd0pw).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 542ms

    at makeError (D:\codeTest\taro-native-shell\node_modules\execa\index.js:174:9)
    at D:\codeTest\taro-native-shell\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (D:\codeTest\taro-native-shell\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\codeTest\taro-native-shell\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by zhiqingchen** [comment]
https://docs.gradle.org/6.9/release-notes.html

JDK版本过高

建议JDK 11
