### ISSUE TITLE
h5端引入moment.js，会调用不同文件夹下的moment.js，且引入语言包不能使用

### ISSUE THREAD

**Issue by zhuibo66** [NervJS/taro#10754]
### 相关平台
H5

**浏览器版本:  Chrome 96.0.4664.45**
**使用框架: React**

### 复现步骤
在主入口文件：添加如下代码

#### 第一种引入方式（不行的，但是在其他项目正常）

```javascript
import moment from 'moment';
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
console.log(moment().format('ddd'));
```

输出的结果还是英文的星期几，所以就比较疑惑，因为在其他的项目中都是用这样的方式引入的，一点问题都没有，所以进一步调试，我找到了项目中的`node_modules`文件夹下的`moment`的包，分别在`monent.js`和`zh-cn.js`（在moment里面有两个这样的文件，我都给加上了），分别加上了console.log的调试，具体的结果如下：

![image](https://user-images.githubusercontent.com/69130137/143672800-565a952d-8bc2-4e91-a83a-d0250ad520d7.png)

从结果看出来，taro在打包的时候，好像是打包了两次moment.js，而我根据网上搜索到相关资料，就是在`moment.js`里面其实放着两份代码，一份是es5，一份是es6的， 然后通过`moment.js`项目底下的`package.json`文件中的`main`和`jsnext:main`这两个字段来决定打包的是es5还是es6，我也尝试过把其中的`jsnext:main`的字段去掉后，确实打包也正常了，语言也能正常显示了。

但是总不能都这样改把，目前我是用下面的这样方式引入，正常是正常了，但是就不太明白，为啥又正常，为啥别的项目用第一种就可以了（试过好几个项目都是第一种的引入方式）。

#### 第二种引入方式（可行的，但是不理解为啥可以了）

```javascript
import moment from 'moment';
import 'moment/dist/locale/zh-cn';
moment.locale('zh-cn');
console.log(moment().format('ddd'));
```

所以，希望官方能帮忙看下，到底是什么原因导致的，麻烦了，谢谢了。

### 期望结果
输出中文的星期几

### 实际结果
输出英文的星期几

### 环境信息
```
  Taro CLI 3.3.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - D:\nodejs\yarn.CMD
      npm: 6.14.13 - D:\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@zhuibo66 使用 webpack chain 去修改 webpack 的 `resolve.mainFields` 配置 应该就可以了，

H5 默认的 `resolve.mainFields` 配置：

https://github.com/NervJS/taro/blob/e02a78fbf70aa7ec51c1147d2997bd88225f098b/packages/taro-webpack-runner/src/config/base.conf.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L22

**Comment by zhuibo66** [comment]
> 

经过在开发环境下测试，具体更改代码如下：

文件地址：项目根目录/config/dev.js

```javascript
module.exports = {
    env: {
        NODE_ENV: '"development"'
    },
    defineConstants: {},
    mini: {},
    h5: {
        resolve: {
            mainFields: ['main:h5', 'browser', 'module', 'main', 'jsnext:main']
        }
    }
};
```

还是没有解决问题，不知道是什么情况，还请官方再帮忙看下，是什么原因？谢谢。

**Comment by skyliwq** [comment]
我也遇到过这个问题 没有解决！

**Comment by zhuibo66** [comment]
> > @zhuibo66 使用 webpack chain 去修改 webpack 的 `resolve.mainFields` 配置 应该就可以了，
> > H5 默认的 `resolve.mainFields` 配置：
> > https://github.com/NervJS/taro/blob/e02a78fbf70aa7ec51c1147d2997bd88225f098b/packages/taro-webpack-runner/src/config/base.conf.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L22
> 
> 经过在开发环境下测试，具体更改代码如下：
> 
> 文件地址：项目根目录/config/dev.js
> 
> ```js
> module.exports = {
>     env: {
>         NODE_ENV: '"development"'
>     },
>     defineConstants: {},
>     mini: {},
>     h5: {
>         resolve: {
>             mainFields: ['main:h5', 'browser', 'module', 'main', 'jsnext:main']
>         }
>     }
> };
> ```
> 
> 还是没有解决问题，不知道是什么情况，还请官方再帮忙看下，是什么原因？谢谢。

目前已经解决了，根据 @Chen-jj 的提示，之前还以为可以直接添加`resolve`配置项，后来看下框架里面的，是没有特别处理这个`resolve`的字段，怪我自己没认真看文档，我的锅。刚好也顺带了解了下`webpack-chain`，感谢，感谢。

```javascript
module.exports = {
    env: {
        NODE_ENV: '"development"'
    },
    defineConstants: {},
    mini: {},
    h5: {
        webpackChain(chain, webpack) {
            // webpackChain作用时机：taro处理后，webpack调用前
            // 法一
            // chain.resolve.mainFields.delete('jsnext:main').add('jsnext:main');
            // 法二
            chain.resolve.mainFields.clear();
            chain.merge({
                resolve: {
                    mainFields: ['main:h5', 'browser', 'module', 'main']
                }
            });
            return chain;
        }
    }
};
```
