### ISSUE TITLE
是否有方案能将uniapp项目转为taro项目，或者两者混合开发？

### ISSUE THREAD

**Issue by airqj** [NervJS/taro#10755]
### 这个特性解决了什么问题？
老项目是用uniapp写的，大概有几十个页面。
现在想将其迁移到taro。
看了一下文档，都是taro与原生小程序的混合开发，不知道是否有uniapp与taro混合开发的方案？

### 这个 API 长什么样？
能够实现uniapp与taro的混合开发

**Comment by Sherlock-Luo** [comment]
等你来实现

**Comment by tourze** [comment]
没有混合开发方案，不过可以迁移到taro。
我记得只要将uni. 替换为wx. 就可以完成大部分工作了，自己写个脚本生成 *.config.js
如果用到uni的条件编译，也要对应改改。

**Comment by airqj** [comment]
> 没有混合开发方案，不过可以迁移到taro。 我记得只要将uni. 替换为wx. 就可以完成大部分工作了，自己写个脚本生成 *.config.js 如果用到uni的条件编译，也要对应改改。

眼下也只能这样了，试试看。非常感谢
