### ISSUE TITLE
关于微信小程序隐私协议的配置

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro#10751]
### 这个特性解决了什么问题？
目前因为编译出来的代码包含 `<live-pusher `之类的标签，小程序后台提审时会认为用了该功能，所以要求填写相关的隐私协议。但是实际上没有用，用户看到多余的隐私协议会不太好。

### 这个 API 长什么样？
编译时过滤掉不需要的 标签

**Comment by Chen-jj** [comment]
标签是按需引入的，没有使用到 `LivePusher` 的时候，base.wxml 里是不会存在 `<live-pusher>` 的

**Comment by ccqgithub** [comment]
> 标签是按需引入的，没有使用到 `LivePusher` 的时候，base.wxml 里是不会存在 `<live-pusher>` 的

base.wxml 里面有的

**Comment by Chen-jj** [comment]
那就是哪里用到了咯

**Comment by ccqgithub** [comment]
> 那就是哪里用到了咯

没有哦，我自己写的代码，真的没用过，而且搜索也搜不到~
是不是 直接 import Taro from "@tarojs/taro"， 这样会引入？

**Comment by Chen-jj** [comment]
你新建一个项目，看 base.wxml 只有若干默认的组件和使用到的组件就能证明是按需的了。

这样会引入 xxx 的模板：`import { xxx } from '@tarojs/components'`

这样会引入所有模板：`require('@tarojs/components')`

**Comment by ccqgithub** [comment]
> 你新建一个项目，看 base.wxml 只有若干默认的组件和使用到的组件就能证明是按需的了。
> 
> 这样会引入 xxx 的模板：`import { xxx } from '@tarojs/components'`
> 
> 这样会引入所有模板：`require('@tarojs/components')`

多谢解答，是引用了`taro-code`，里面调用了`require('@tarojs/components')`，然后配置加载esm包就好了：
```
{
  mini: {
   webpackChain(chain) {
      chain.resolve.mainFields.prepend("module");
    },
  }
}
```
