### ISSUE TITLE
【3.3.15】H5端设置tabBar的selectColor和backgroundColor无效，默认显示为weui的样式

### ISSUE THREAD

**Issue by Sherlock-Luo** [NervJS/taro#10758]
### 相关平台
H5

**浏览器版本: Chrome 版本 92.0.4515.159（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
1.taro init myapp
2.选择默认，我测试了默认模板和taro-hook这两个模板
3.设置tabBar的selectColor和backgroundColor无效

### 期望结果
selectColor和backgroundColor设置有效

### 实际结果
无效，默认显示.weui-tabbar__item.weui-bar__item_on .weui-tabbar__icon, .weui-tabbar__item.weui-bar__item_on .weui-tabbar__icon>i, .weui-tabbar__item.weui-bar__item_on .weui-tabbar__label {
    color: #09bb07;
}和.weui-tabbar {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    position: absolute;
    z-index: 500;
    bottom: 0;
    width: 100%;
    background-color: #f7f7fa;
}

### 环境信息
```
 Taro CLI 3.3.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\localhost\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
未能复现到该问题，可以提供完整的demo看看🤔

> 也可以自助排查，3.3.15以下的版本不支持该操作，请检查所有依赖是否升级到 3.3.15+

**Comment by Sherlock-Luo** [comment]
@ZakaryCode https://github.com/NervJS/taro/issues/10736 我和这条issues一样的

**Comment by Sherlock-Luo** [comment]
![image](https://user-images.githubusercontent.com/88224240/143869134-0c62a535-5ea7-4f06-adda-dd71a0028d6f.png)

**Comment by ZakaryCode** [comment]
原来是配置哦，以为是API，下一个版本修复咯～

> 重复 issue 先关了
