### ISSUE TITLE
小程序引入第三方库的组件，render 中使用组件元素标签时 ts 告警

### ISSUE THREAD

**Issue by zoux** [NervJS/taro#1076]
按文档引入第三库有赞的 button 组件为例：
usingComponents: {
      'van-button': '../../libs/vant-weapp/dist/button/index'
    }

render 函数中如下使用时，ts 告警：
\<van-button type='primary'\>主要按钮\</van-button\>

告警内容如下：
Property 'van-button' does not exist on type 'JSX.IntrinsicElements'.

现在为了忽略告警，代码如下所示：
{
          // @ts-ignore
          \<van-button type='primary'\>主要按钮\</van-button\>
        }

请问有更好的解决方式，或者正确的使用方式是什么？

**Comment by DiamondYuan** [comment]
添加 global.d.ts
```
declare namespace JSX {
  interface IntrinsicElements {
    van-button: any;
  }
}
```
