### ISSUE TITLE
Taro.previewImageAPI可以支持H5环境下手势放大缩小

### ISSUE THREAD

**Issue by HEYAN123** [NervJS/taro#10769]
### 这个特性解决了什么问题？
Taro.previewImageAPI可以支持H5环境下手势放大缩小

### 这个 API 长什么样？
Taro.previewImageAPI可以支持H5环境下手势放大缩小，拖拽等，可以和小程序环境下效果一致

**Comment by ZakaryCode** [comment]
duplicate #8274
