### ISSUE TITLE
安卓下不展示富文本内容 无报错

### ISSUE THREAD

**Issue by Jasonzzh** [NervJS/taro#10768]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
      <View className={styles["content"]}>
        <RichText
          nodes={`<p
          class="MsoNormal"
          align="left"
          style="text-align:left;text-indent:21.0pt;"
        >
          <span>我们将尽快审核所涉问题，一般情况下，在验证您的用户身份后的三十天内回复。</span>
        </p>`}
        />
      </View>

### 期望结果
正确展示内容

### 实际结果
空白

### 环境信息
```
� Taro v3.3.1


  Taro CLI 3.3.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - D:\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
需设置宽高。

todo：字体大小Android与iOS不一致
