### ISSUE TITLE
小程序这个可能没法用，生成的包大

### ISSUE THREAD

**Issue by asreday** [NervJS/taro#1077]
直接一个index.js什么没写压缩出来后就45K，如果有十几页面的话，或者多几个组件，基本就满了2M了，如何解决呢

**Comment by jinjinjin0731** [comment]
放子包啊

**Comment by farzer** [comment]
说法有点夸张吧，现在就有十多个页面，差不多三十个组件，现在是1M多

**Comment by luckyadam** [comment]
啥都没写何以见得有 45k

**Comment by asreday** [comment]
> 啥都没写何以见得有 45k

我是看到index.js文件引入npm>@tarojs>taro-weapp>dist>index.js，如果每创建一个页面，会不会生成一个这样的js

**Comment by yuche** [comment]
> > 啥都没写何以见得有 45k
> 
> 我是看到index.js文件引入npm>@tarojs>taro-weapp>dist>index.js，如果每创建一个页面，会不会生成一个这样的js

当然不会，相同的代码是公用的
