### ISSUE TITLE
如何为taro项目代码生成注释文档？

### ISSUE THREAD

**Issue by pialin** [NervJS/taro#10778]
### 相关平台
微信小程序

**小程序基础库: 2.21.0**
**使用框架: React**

### 复现步骤
无

### 期望结果
找到一个为taro项目生成注释文档的范例。

### 实际结果
没有找到类似的范例

### 环境信息
```
Taro CLI 3.3.15 environment info:
System:
     OS: Windows 10
Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
     npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
由于taro代码使用了订制的webpack runner，并存在一些特定的环境变量，React项目的常用的文档库包括"react-styleguidist"和”storybook“等都不能直接引用taro的webpack配置进行编译，官方能不能提供一个类似的文档库配置范例，便于taro开发者进行文档注释的编写和导出？ 十分感谢！

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro-docs/docs/external-libraries#storybook)
