### ISSUE TITLE
taro3.X启动项目报错

### ISSUE THREAD

**Issue by Jorgor** [NervJS/taro#10781]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
npm run dev:weapp

### 期望结果
正常启动项目

### 实际结果
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../remove'
Require stack:
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\node_modules\fs-extra\lib\empty\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\node_modules\fs-extra\lib\index.js    
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\dist\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\index.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\cli.js
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\bin\taro
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\helper\node_modules\fs-extra\lib\empty\index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\helper\\node_modules\\fs-extra\\lib\\empty\\index.js',
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\helper\\node_modules\\fs-extra\\lib\\index.js',
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\helper\\dist\\index.js',       
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\helper\\index.js',
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\Kernel.js',     
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\dist\\index.js',      
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\node_modules\\@tarojs\\service\\index.js',
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\dist\\cli.js',
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\@tarojs\\cli\\bin\\taro'
  ]
}

### 环境信息
```
Taro CLI 3.3.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by konka-king** [comment]
标题说 taro3.X ， 环境却是 Taro CLI 2.2.13  ？

**Comment by Jorgor** [comment]
> 标题说 taro3.X ， 环境却是 Taro CLI 2.2.13 ？
谢，改了

**Comment by luckyadam** [comment]
没有复现哦，重新安装下最新版 CLI 试试
