### ISSUE TITLE
Taro v3.3.15 Taro.navigateBack 返回上一页，url 变化了，页面内容不是 url 对应的页面内容

### ISSUE THREAD

**Issue by shushu2013** [NervJS/taro#10785]
### 相关平台
H5

### 复现仓库
[https://github.com/shushu2013/taro-h5-bugs-example](https://github.com/shushu2013/taro-h5-bugs-example)

**浏览器版本: Chrome 版本 96.0.4664.55（正式版本） (arm64)**

**使用框架: React**

### 复现步骤
```
$ git clone https://github.com/shushu2013/taro-h5-bugs-example.git

$ cd taro-h5-bugs-example

$ yarn

$ npm run dev:h5
```
1、启动后，打开的是首页 `pages/index/index`

2、点击下方 导航栏『我的』按钮，切到 `pages/mine/index` 页面

3、此时，刷新一下浏览器（不刷新，重现不了这个问题），刷新浏览器后，还是在『我的』页面

4、点击页面上的『进入测试页』按钮

5、进入测试页 `pages/test/index` 后，再点击『Go Back』按钮

6、此时正常回到了 `pages/mine/index` 页面，页面内容也是正常的

7、点击下方 导航栏『首页』按钮，切到 `pages/index/index` 页面

8、再点击下方 导航栏『我的』按钮，切到 `pages/mine/index` 页面

9、此时重复步骤 4 ~ 6，到步骤 6 后，发现浏览器 url 是变化了，但是页面内容不是 `pages/mine/index` 页面的内容
而是变成了首页的内容

![taro-back-bug (1)](https://user-images.githubusercontent.com/6076072/144081069-7b79c907-92f3-4f98-bc08-302896e6a3c9.gif)

### 期望结果
Taro.navigateBack 返回上一页，页面显示正常

### 实际结果
页面显示不对

### 环境信息
```
👽 Taro v3.3.15


  Taro CLI 3.3.15 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v16.6.0/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.15 => 3.3.15 
      @tarojs/mini-runner: 3.3.15 => 3.3.15 
      @tarojs/react: 3.3.15 => 3.3.15 
      @tarojs/runtime: 3.3.15 => 3.3.15 
      @tarojs/taro: 3.3.15 => 3.3.15 
      @tarojs/webpack-runner: 3.3.15 => 3.3.15 
      babel-preset-taro: 3.3.15 => 3.3.15 
      eslint-config-taro: 3.3.15 => 3.3.15 
      react: ^17.0.0 => 17.0.2 
```

**Comment by ZakaryCode** [comment]
可以在 #10808 合入之后再看看，这个版本没有复现这个问题

**Comment by jianhao2010303** [comment]
问题+1

**Comment by Chen-jj** [comment]
升级到 3.3.16 再试试

**Comment by caizhongren** [comment]
升级到3.3.20还是没有解决
我用的是vue3 在h5 端 这个先给解决下吧
