### ISSUE TITLE
无法兼容扩展运算符

### ISSUE THREAD

**Issue by siulunchien** [NervJS/taro#10795]
### 相关平台
H5

### 复现仓库
[https://gitee.com/siulunkan/compatible.git](https://gitee.com/siulunkan/compatible.git)
**浏览器版本: Safari 11.1.0**
**使用框架: Vue 3**

### 复现步骤
打开页面

### 期望结果
页面能正常显示

### 实际结果
页面空白

### 环境信息
```
Taro CLI 3.3.15 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.15 => 3.3.15 
      @tarojs/mini-runner: 3.3.15 => 3.3.15 
      @tarojs/runtime: 3.3.15 => 3.3.15 
      @tarojs/taro: 3.3.15 => 3.3.15 
      @tarojs/webpack-runner: 3.3.15 => 3.3.15 
      babel-preset-taro: 3.3.15 => 3.3.15 
      eslint-config-taro: 3.3.15 => 3.3.15 
    npmGlobalPackages:
      typescript: 4.1.3
```

---
### 补充信息
初步估计是 扩展运算符 在一些低端机型上不支持，package.json 的 browserslist 是默认的，babel.config.js 的 targets 也是默认的。编译后一些版本比较低的机型无法正常运行。

**Comment by Chen-jj** [comment]
@siulunchien 根据实际情况配置一下 `babel-preset-taro` 的 `targets` 和 `useBuildIns` 咯：https://docs.taro.zone/docs/babel-config#targets
