### ISSUE TITLE
Taro2.X的版本是否可以扩展微信HTTP2.0的支持

### ISSUE THREAD

**Issue by huoyonghong** [NervJS/taro#10790]
### 这个特性解决了什么问题？
网络请求增加对  HTTP2.0  的支持

### 这个 API 长什么样？
支持微信小程序官网所拓展的新增字段：
enableHttp2
enableQuic
enableCache
......

完整的扩展字段请参照微信小程序公众平台API文档所罗列的字段：https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html#%E5%8F%82%E6%95%B0

**Comment by Chen-jj** [comment]
API 参数透传的，直接用即可。

**Comment by MemoryNoodles** [comment]
> API 参数透传的，直接用即可。

从返回的数据上看是不支持。 不管是真机还是模拟器
