### ISSUE TITLE
taro3 react H5 快速来回切换tabBar，无法保证定位当前页面

### ISSUE THREAD

**Issue by jianhao2010303** [NervJS/taro#10792]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**浏览器版本: Chrome  96**
**使用框架: React**

### 复现步骤
taro3 react H5 快速来回切换tabBar，无法保证定位当前页面

### 期望结果
taro3 react H5 快速来回切换tabBar，无法保证定位当前页面

### 实际结果
taro3 react H5 快速来回切换tabBar定位准确

### 环境信息
```
  Taro CLI 3.3.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - D:\Node\node.EXE
      Yarn: 1.22.11 - D:\Node\node_global\yarn.CMD
      npm: 6.14.15 - D:\Node\npm.CMD
```

---
### 补充信息
版本中说修正了此问题，但实际使用依然如此。

**Comment by ZakaryCode** [comment]
未能在该版本中复现到问题，如果存在可以提供详细的 demo

**Comment by jianhao2010303** [comment]
重新install，现在测试ok
