### ISSUE TITLE
请加入自定义环境变量功能

### ISSUE THREAD

**Issue by vonweb** [NervJS/taro#108]
现在在代码中不能使用process.env来获取自定义的环境变量，请支持自定义环境变量，
另外增强一下webpack功能的支持吧，本地已经有8080服务了，taro还是使用8080端口

**Comment by luckyadam** [comment]
是支持的，我稍后补全一下配置的文档~

**Comment by luckyadam** [comment]
文档已补上 `https://nervjs.github.io/taro/config-detail.html#defineConstants`

**Comment by lkspc** [comment]
@luckyadam 页面里面 `process.env` 是个空对象呢？

**Comment by luckyadam** [comment]
@lkspc H5 里确实有问题，我们今天修复下
