### ISSUE TITLE
列表渲染二维数组函数编译过后丢失

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#1081]
![image](https://user-images.githubusercontent.com/24502330/48316188-36a3a580-e61b-11e8-9ce1-0597db43ed07.png)

编译之后的文件如下，并且报错column未定义
![image](https://user-images.githubusercontent.com/24502330/48316203-56d36480-e61b-11e8-9da4-0042e7ce476a.png)

**Comment by luckyadam** [comment]
不能在 render 中定义函数，返回 jsx，暂时还没有支持这种写法

**Comment by yuche** [comment]
老哥，发字符串不要发截图，另外带上你的版本。

你这段代码没有复杂表达式循环内也没有语句所以不用生成新的匿名数组，所以他就直接编译成 wxml了。

**Comment by yuche** [comment]
你直接用 this.props.list 写循环就好了。

https://github.com/NervJS/taro/blob/master/packages/eslint-plugin-taro/docs/no-stateless-function.md

**Comment by yuche** [comment]
Duplicate of #131
