### ISSUE TITLE
showToast的error 在h5下显示正确的图标

### ISSUE THREAD

**Issue by jianhao2010303** [NervJS/taro#10823]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**浏览器版本: Chrome 96**
**使用框架: React**

### 复现步骤
  Taro.showToast({
          icon: 'error',
          title: statusText
   })

### 期望结果
在h5下显示错误图标

### 实际结果
显示success图标

### 环境信息
```
 Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - D:\Node\node.EXE
      Yarn: 1.22.11 - D:\Node\node_global\yarn.CMD
      npm: 6.14.15 - D:\Node\npm.CMD
```

**Comment by GreatAuk** [comment]
![image](https://user-images.githubusercontent.com/20253809/144823247-1664d6b1-a13f-4f47-8395-d404a696a70a.png)
`showToast` 的 `icon` 不支持 'error' 吧

**Comment by jianhao2010303** [comment]
支持了，昨天发的3.3.16支持了
