### ISSUE TITLE
ext.json文件 和字体文件不会自动拷贝小程序dist目录下 ？

### ISSUE THREAD

**Issue by fjzhuxu** [NervJS/taro#1082]
ext.json文件 和字体文件不会自动拷贝小程序dist目录下 ？
在config/index.js文件添加了拷贝配置但是好像没有效果
  copy: {  
      patterns: [
        { from: 'src/ext.json', to: 'dist/ext.json' } ,
        { from: 'src/asset/fonts/', to: 'dist/asset/fonts/' } // 指定需要 copy 的文件
      ]   
    },
都要对文件修改下 才会拷贝过去  字体文件 都是移动到别的文件夹 在移动回来 才拷贝过去的

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/334d440de96ac92197fa45d0ba9e254cbe2b4157
