### ISSUE TITLE
安装@tarojs/plugin-mini-cli插件之后，执行upload命令，会提示找不到 ctx.onBuildComplete的方法

### ISSUE THREAD

**Issue by Vickshine** [NervJS/taro#10835]
### 相关平台
微信小程序

**小程序基础库: 2.21.0**
**使用框架: React**

### 复现步骤
1.安装@tarojs/plugin-mini-ci 库；
2.配置插件；
3.运行upload命令，node_modules/@tarojs/plugin-mini-cli/dist/index.js文件，line 44：
 ctx.onBuildComplete需要替换为 ctx.onBuildFinish方法才可以正常编译运行成功

### 期望结果
运行upload命令成功

### 实际结果
运行upload命令失败

### 环境信息
```
👽 Taro v3.4.0-beta.0

validFiles []

  Taro CLI 3.4.0-beta.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.0.0 - E:\node\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.10.0 - E:\node\npm.CMD
```

---
### 补充信息
希望尽快修复此插件问题

**Comment by lizong9527** [comment]
需要将`@tarojs/cli`升级到3.3.10版本及其以上， `onBuildComplete `钩子是在这个版本加入的
![image](https://user-images.githubusercontent.com/91171298/145218115-530502c0-8094-46fa-8a94-d5fd02b8dc15.png)

**Comment by Vickshine** [comment]
这个是我的项目中packages.json中的依赖，我的"@tarojs/cli": "^3.4.0-beta.0",是最新版本
`"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@tarojs/components": "3.4.0-beta.0",
		"@tarojs/plugin-framework-react": "^3.4.0-beta.0",
		"@tarojs/react": "3.4.0-beta.0",
		"@tarojs/runtime": "3.4.0-beta.0",
		"@tarojs/taro": "3.4.0-beta.0",
		"preact": "^10.6.2",
		"react": "^17.0.0",
		"react-dom": "^17.0.0"
	},
	"devDependencies": {
		"@babel/core": "^7.8.0",
		"@tarojs/cli": "^3.4.0-beta.0",
		"@tarojs/mini-runner": "3.4.0-beta.0",
		"@tarojs/plugin-mini-ci": "^3.3.15",
		"@tarojs/webpack-runner": "3.4.0-beta.0",
		"@types/react": "^17.0.2",
		"@types/webpack-env": "^1.13.6",
		"babel-preset-taro": "3.4.0-beta.0",
		"eslint": "^6.8.0",
		"eslint-config-taro": "3.4.0-beta.0",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-react-hooks": "^4.2.0",
		"stylelint": "9.3.0"
	}`

**Comment by Chen-jj** [comment]
没有复现，建议检查一下 node_modules 的拓扑是否正确。

![image](https://user-images.githubusercontent.com/11807297/146297431-4c18ff33-decb-463b-955a-05af3c026082.png)

![image](https://user-images.githubusercontent.com/11807297/146298418-beb73e1a-14b9-4dfb-aac8-8a1ee185dbdd.png)

**Comment by Vickshine** [comment]
刚才重新验证了一下，是ok的了，不纠结了，解决问题为主。但之前使用upload命令上传包时的确是提示找不到onBuildComplete方法，当时我打印了ctx，onBuild开头的方法只有onBuildStart和onBuildFinish。这也是为什么开头我提的问题是把ctx.onBuildComplete需要替换为 ctx.onBuildFinish方法才可以正常编译运行成功。
![image](https://user-images.githubusercontent.com/35124269/146304024-74b8b285-44ca-4f4f-a21b-8e6afc85849a.png)
