### ISSUE TITLE
使用原生组件[Vue warn]: Failed to resolve and [Component] slot is not found.

### ISSUE THREAD

**Issue by panhezeng** [NervJS/taro#10838]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/panhezeng/taro-vue-template](https://github.com/panhezeng/taro-vue-template)
**小程序基础库: 2.2.1**
**使用框架: Vue 3**

### 复现步骤
```js
export default {
  navigationBarTitleText: "示例",
  usingComponents: {
    "example-view":
      "../../components/wechat-miniprogram/example-view/example-view",
  },
};
```

### 期望结果
没有警告

### 实际结果
有警告
![image](https://user-images.githubusercontent.com/354878/145011485-54bf8522-4239-429a-ad2f-ddc6e655193c.png)

### 环境信息
```
 Taro CLI 3.3.16 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.2.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/components: 3.3.16 => 3.3.16 
      @tarojs/mini-runner: 3.3.16 => 3.3.16 
      @tarojs/runtime: 3.3.16 => 3.3.16 
      @tarojs/taro: 3.3.16 => 3.3.16 
      @tarojs/webpack-runner: 3.3.16 => 3.3.16 
      babel-preset-taro: 3.3.16 => 3.3.16 
      eslint-config-taro: 3.3.16 => 3.3.16
```

**Comment by Chen-jj** [comment]
@panhezeng 截图说得很清楚了，配一下就好，与 Taro 无关

![image](https://user-images.githubusercontent.com/11807297/145063924-d26abc22-0c0c-4a0f-b19c-cc09f6165186.png)

**Comment by panhezeng** [comment]
taro 怎么修改vue loader option?

https://v3.cn.vuejs.org/api/application-config.html#compileroptions-iscustomelement

我用这个方法不行

![image](https://user-images.githubusercontent.com/354878/145136737-27adacc8-06b0-456c-aaf9-45031224d9df.png)


我用webpack 也不行，说是没有这个loader

![image](https://user-images.githubusercontent.com/354878/145136893-e08ce8f8-08cd-45dc-a765-0867504e6d57.png)

**Comment by panhezeng** [comment]
> @panhezeng 截图说得很清楚了，配一下就好，与 Taro 无关
> 
> ![image](https://user-images.githubusercontent.com/11807297/145063924-d26abc22-0c0c-4a0f-b19c-cc09f6165186.png)

我尝试了两种配置方式，都没成功

**Comment by panhezeng** [comment]
谢谢，已经解决了

node_modules/@tarojs/mini-runner/dist/webpack/vue.js

![image](https://user-images.githubusercontent.com/354878/145139287-ef4630ab-b413-42e4-8c67-8b64f3427a0c.png)

```js
     chain.module
        .rule("vue")
        .use("vueLoader")
        .tap((options) => {
          options.compilerOptions.isCustomElement = (tag) =>
            tag.startsWith("wm-");
          return options;
        });
```

```js

export default {
  navigationBarTitleText: "示例",
  usingComponents: {
    "wm-example-view":
      "../../components/wechat-miniprogram/example-view/example-view",
  },
};

```

```js
<wm-example-view />
```

希望能加到使用原生组件的文档部分。

**Comment by panhezeng** [comment]
个人建议， node_modules/@tarojs/mini-runner/dist/webpack/vue.js  的 .use("vueLoader") 还是按之前的惯例写成 .use('vue-loader') 比较好，毕竟其他地方关于通过 webpack chain 修改 vue loader， 都是 .use('vue-loader') 这种写法。

**Comment by Chen-jj** [comment]
> 个人建议， node_modules/@tarojs/mini-runner/dist/webpack/vue.js 的 .use("vueLoader") 还是按之前的惯例写成 .use('vue-loader') 比较好，毕竟其他地方关于通过 webpack chain 修改 vue loader， 都是 .use('vue-loader') 这种写法。

感谢建议~Taro 3.4 会将 vue-loader 的编译配置暴露出来：https://docs.taro.zone/docs/next/vue3#compileroptions
