### ISSUE TITLE
微信小程序中requestTask.abort()方法不存在

### ISSUE THREAD

**Issue by gushisan** [NervJS/taro#10837]
### 相关平台
微信小程序

**小程序基础库: 2.21.0**
**使用框架: React**

### 复现步骤
const requestTask = Taro.request({
            url: 'XXXXXX'
          })
          requestTask.abort();

### 期望结果
abort方法可用

### 实际结果
TypeError: requestTask.abort is not a function

### 环境信息
```
Taro CLI 3.2.5 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.2.12 => 3.3.16 
      @tarojs/components: ^3.2.12 => 3.3.16 
      @tarojs/mini-runner: ^3.2.12 => 3.3.16 
      @tarojs/react: ^3.2.12 => 3.3.16 
      @tarojs/runtime: ^3.2.12 => 3.3.16 
      @tarojs/taro: ^3.2.12 => 3.3.16 
      @tarojs/webpack-runner: ^3.2.12 => 3.3.16 
      babel-preset-taro: ^3.2.12 => 3.3.16 
      eslint-config-taro: ^3.2.12 => 3.3.16 
      react: ^17.0.0 => 17.0.2 
```

**Comment by Chen-jj** [comment]
@gushisan CLI 和依赖保持一致。

如果还有问题，断点进去看看。

Taro 是支持 abort 的：

https://github.com/NervJS/taro/blob/de2b891e0842e71710d5c3054e314794ed940f47/packages/shared/src/native-apis.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L185-L193

![image](https://user-images.githubusercontent.com/11807297/146004196-bb94b3e7-fe4c-43f0-8359-8c2a8b403d5e.png)

**Comment by shmily-jianjian** [comment]
加了拦截器就会失效
