### ISSUE TITLE
Picker组件弹出时，h5端位置显示不符合预期。（微信小程序端显示是正常的底部显示）

### ISSUE THREAD

**Issue by ruoqiang** [NervJS/taro#1083]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. Go to [this](http://taroh5.pxteam.cn/#/pages/record-car/record-car)
2. 然后点击界面上的日期

[或者可以直接贴源代码，能贴文字就不要截图]
关键jsx
```js
<View className='time span picker'><Picker className='date' mode='date' onChange={this.onDateChange}> <View className='picker'>{this.state.dateSel}</View></Picker></View>
                    <View className='text span'>至</View>
                    <View className='time span picker'><Picker className='date' mode='date' onChange={this.onDateChangeTwo}> <View className='picker'>{this.state.dateSel2}</View></Picker></View>
                    </View>

```

**期望行为**
h5端也能像微信一样 选择弹框显示在页面底部

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.1.4
 - Node.js 版本 v8.9.4
 - 报错平台 h5

**Comment by ruoqiang** [comment]
追加一个小问题：
mode='date' 时h5端的日期选择后的格式也不对直接为21080211 微信小程序下格式显示正确 为2018-02-11
这个需要一个统一的格式属性设置吗？

**Comment by jinjinjin0731** [comment]
ok,  返回值应该要对齐小程序的,  我晚上看一下~

**Comment by jinjinjin0731** [comment]
hello~ 你的网站页面挂了~ 看不到复现的情况，可以把线上的修复一下吗~ @ruoqiang

**Comment by ruoqiang** [comment]
> > hello~ 你的网站页面挂了~ 看不到复现的情况，可以把线上的修复一下吗~ @ruoqiang
> 
> 好的谢谢，看到了。
> 我昨天升级到了tato1.1.7后,再去打包h5然后访问就直接报错了
[我上传了一个截图](http://staticsource.pxteam.cn/20181115113747.png)

**Comment by ruoqiang** [comment]
请看这里的错误显示情况 [图片](http://staticsource.pxteam.cn/20181115113747.png)
