### ISSUE TITLE
Taro3.3.12版本后Vue2 H5 input组件v-model失效

### ISSUE THREAD

**Issue by 15380831711** [NervJS/taro#10836]
### 相关平台
H5

### 复现仓库
[https://github.com/15380831711/tarovue2demo.git](https://github.com/15380831711/tarovue2demo.git)
**浏览器版本: Chrome **
**使用框架: Vue 2**

### 复现步骤
使用taro命令行创建vue2最新taro版本工程，页面添加input组件，并添加v-model，观察双向绑定数据变化！

### 期望结果
正常双向绑定

### 实际结果
只绑定了第一次的输入。

### 环境信息
```
  Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - D:\ProgramFiles\node\node.EXE
      Yarn: 1.22.10 - D:\ProgramFiles\node\yarn.CMD
      npm: 6.14.11 - D:\ProgramFiles\node\npm.CMD  
```

**Comment by 15380831711** [comment]
请问下3.3.17，v-model 问题修复了没，都不敢随便升级了

**Comment by 15380831711** [comment]
经排查：@tarojs/components 3.3.12 是正常的，后面的版本貌似都有问题。
初步判断是@stencil/core版本升级导致，把它的版本还原到2.4.0，重新编译@tarojs/components，发现v-model是正常的。

**Comment by ZakaryCode** [comment]
确实是有问题，升级之后没有更新 target 上的值，可以使用 input 事件替代 v-model 修复该问题 😅
