### ISSUE TITLE
VirtualList引入在RN直接报错

### ISSUE THREAD

**Issue by MilkteaBoy-code** [NervJS/taro#10849]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
import VirtualList from '@tarojs/components/virtual-list'

          <VirtualList
            height={400} /* 
            列表的高度 */
            width='100%' /* 列表的宽度 */
            itemData={this.state.list} /* 渲染列表的数据 */
            itemCount={this.state.list.length} /*  渲染列表的长度 */
            itemSize={140}
            // onScrollToLower={() => this.getNextList('1110')}
            // onScrollToUpper={() => this.getNextList('1110')}
            // lowerThreshold={1000}
            // data={this.state.list}
          >
            {TextItem}
            {/* {Row} */}
      </VirtualList> 

 Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

  • Run `react-native link @react-native-async-storage/async-storage` in the project root.

  • Rebuild and restart the app.

  • Run the packager with `--reset-cache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
👽 Taro v3.3.14


  Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.10.0 - E:\Environment\node\node-v12.10.0-win-x64\node.EXE
      Yarn: 1.22.10 - E:\Environment\node\node-v12.10.0-win-x64\yarn.CMD
      npm: 6.10.3 - E:\Environment\node\node-v12.10.0-win-x64\npm.CMD
```

**Comment by zhiqingchen** [comment]
```jsx
import { VirtualList } from "@tarojs/components";
```

**Comment by ihwf** [comment]
> ```js
> import { VirtualList } from "@tarojs/components";
> ```

这样就跟其他平台不统一了
