### ISSUE TITLE
在组件库中使用Taro.makePhoneCall，项目中引入组件库使用时，报错_tarojs_taro__WEBPACK_IMPORTED_MODULE_2__.default.makePhoneCall is not a function

### ISSUE THREAD

**Issue by lhkg1988** [NervJS/taro#10865]
### 相关平台
H5

**浏览器版本: Chrome 96**
**使用框架: React**

### 复现步骤
组件库是用taro-ui一样的，使用rollup的方式build，在项目中直接使用没问题，但是放在组件库中使用就报这个问题，Taro.request也有相同的问题

### 期望结果
能正常调用

### 实际结果
Uncaught TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_2__.default.makePhoneCall is not a function

### 环境信息
```
👽 Taro v3.3.16

Taro CLI 3.3.16 environment info:
System:
OS: Windows 10
Binaries:
Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - D:\User\hliu\AppData\Roaming\npm\yarn.CMD
npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lhkg1988** [comment]
在项目中直接用Taro.makePhoneCall就没问题，放在组件库中，再在项目中使用就报_tarojs_taro__WEBPACK_IMPORTED_MODULE_2__.default.makePhoneCall is not a function，中间多了一层default，default里面确实没有makePhoneCall这个方法，makePhoneCall这个方法是和default同层的方法

**Comment by lhkg1988** [comment]
> 能否提供一个组件库的 demo

https://www.npmjs.com/package/cowell      用这个，里面有个CbButton

**Comment by lhkg1988** [comment]
执行taro build --type weapp --environment test -- --watch --modules  命令起本地服务也会报错：TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_7___default.a.getSystemInfoSync is not a function

**Comment by lhkg1988** [comment]
不知道是不是我哪里配置的问题

**Comment by ZakaryCode** [comment]
这应该是打包的问题，错误识别了 Taro 提供的 API 🤔

由于没有详细的工程没办法直接看到问题，可以考虑两个方向，一是使用 require 引用 Taro 的接口，或者看下 `mainFields` 配置，H5 使用 Taro 的入口应该是 `main:h5`

**Comment by SkyeSun** [comment]
> 在项目中直接用Taro.makePhoneCall就没问题，放在组件库中，再在项目中使用就报_tarojs_taro__WEBPACK_IMPORTED_MODULE_2__.default.makePhoneCall is not a function，中间多了一层default，default里面确实没有makePhoneCall这个方法，makePhoneCall这个方法是和default同层的方法

老哥这个问题解决了吗？我用 rollup 打包在 h5 中也出现了这个问题。

**Comment by lhkg1988** [comment]
> > 在项目中直接用Taro.makePhoneCall就没问题，放在组件库中，再在项目中使用就报_tarojs_taro__WEBPACK_IMPORTED_MODULE_2__.default.makePhoneCall is not a function，中间多了一层default，default里面确实没有makePhoneCall这个方法，makePhoneCall这个方法是和default同层的方法
> 
> 老哥这个问题解决了吗？我用 rollup 打包在 h5 中也出现了这个问题。

组件代码里用这种方式引入，不要用import    const Taro = require('@tarojs/taro');

**Comment by lhkg1988** [comment]
> 组件代码里用这种方式引入，不要用import const Taro = require('@tarojs/taro');

**Comment by lhkg1988** [comment]
> > 在项目中直接用Taro.makePhoneCall就没问题，放在组件库中，再在项目中使用就报_tarojs_taro__WEBPACK_IMPORTED_MODULE_2__.default.makePhoneCall is not a function，中间多了一层default，default里面确实没有makePhoneCall这个方法，makePhoneCall这个方法是和default同层的方法
> 
> 老哥这个问题解决了吗？我用 rollup 打包在 h5 中也出现了这个问题。

组件代码里用这种方式引入， const Taro = require('@tarojs/taro');    不要用import的方式

**Comment by SkyeSun** [comment]
> 

好的 试了一下 确实是可以的 感谢老哥！

**Comment by ZakaryCode** [comment]
rollup 配置 `external: ['@tarojs/taro-h5']` 也是可以的
