### ISSUE TITLE
微信小程序中使用<Textarea>组件时使用'autoFocus'属性时报错

### ISSUE THREAD

**Issue by CooperCao00** [NervJS/taro#10870]
### 相关平台
微信小程序

**小程序基础库: 2.21.1**
**使用框架: React**

### 复现步骤
1. taro-cli创建项目
2. 修改package.json, dependencies中加入 `"@tarojs/plugin-html": "3.3.10"`
3. 安装依赖包启动项目
4. import { Textarea } from '@tarojs/components';
5. 使用Textarea组件， 使用autoFocus属性： `<Textarea autoFocus></Textarea>`
6. 报错。

### 期望结果
可以正常使用Textarea组件的autoFocus属性。

### 实际结果
在plugin-html包的v3.3.10及以上版本都无法使用autoFocus属性。

### 环境信息
```
👽 Taro v3.3.16


  Taro CLI 3.3.16 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

---
### 补充信息
已经发现了这个bug的原因：
在taro-plugin-html/src/constant.ts文件中line：20
```
if(key.toLowerCase() in dir) {
  const res = dir[key]
  // ...其他代码
}
```
key值字符串转小写后并没有赋值给自身导致dir[key]时key依然为'autoFocus'，实际上key值应该为'autofocus'，使得res为undefined，再导致后续的错误。

**Comment by Chen-jj** [comment]
@CooperCao00 有位老哥提交了 PR，但还有些小问题，待他修复咯。
