### ISSUE TITLE
@tarojs/components提供的Canvas组件不支持type

### ISSUE THREAD

**Issue by lanjingling0510** [NervJS/taro#10882]
### 这个特性解决了什么问题？
canvas v2在抖音小程序功能正常

### 这个 API 长什么样？
@tarojs/components提供的Canvas组件支持type

**Comment by yuicer** [comment]
taro v3.3.16

在抖音小程序中，使用如下代码时会出现错误，type=2d 的设置未被挂载在最后的 ttml canvas 属性上，这个问题会导致无法在抖音小程序上使用 v2 版本的 canvas。希望能帮忙修复这个问题，有需要可以提供 demo 仓库

```
import { Canvas } from '@tarojs/components';
<Canvas id='test2' type='2d'></Canvas>
```
![image](https://user-images.githubusercontent.com/23371475/145778842-09993c01-6aa7-450a-a81b-070376751a44.png)
@Chen-jj

**Comment by yuicer** [comment]
或者这里通过 plugin 的形式可以去修改最后的属性挂载吗

**Comment by yuicer** [comment]
@Chen-jj  抱歉这么晚打扰，请问 3.3.17 这个版本会什么时候发布呢。有个项目催的很紧

**Comment by Chen-jj** [comment]
@yuicer 明天或后天的，着急的话可以用 `@tarojs/plugin-inject` 为 Canvas 注入 `type` 属性即可
