### ISSUE TITLE
taro input 组件api

### ISSUE THREAD

**Issue by ggg1it** [NervJS/taro#10890]
### 这个特性解决了什么问题？
请问 原声小程序中的input 组件中的 bindconfirm 事件 在taro input 中是没有得到使用吗

### 这个 API 长什么样？
bindconfirm 在taro input 中使用这个api

**Comment by konka-king** [comment]
https://docs.taro.zone/docs/components/forms/input#:~:text=detail%20%3D%20%7Bvalue%3A%20value%7D-,onConfirm,-BaseEventOrigFunction%3CinputValueEventDetail%3E


您说的是这个？
