### ISSUE TITLE
state和prop重名 state会覆盖props

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#109]
```
class Test extends Taro.Component{
    state={
      val:999
    }
    render(){
        return <View>{this.props.val}</View>
    }
}
```

<Test val={50}/>

模拟器上显示为999

如果把Test的val改成val2就显示正常
```
state = {
    val2:999
}
```

**Comment by yuche** [comment]
的确有这个问题，由于我们是自己做的组件化方案，不管 `props` 还是 `state`都会打入到小程序 `Page`的 `data` 中。我们暂时准备做一个 ESLint 规则，先提示开发者不要这么写。

前些日子微信小程序更新了新的能力，我们应该会基于微信小程序的组件化重构 Taro 的组件化方案。到时这个问题应该就不存在了。很多限制也不会存在（例如在自定义组件里写 `this.props.children`，通过 props 传递 JSX）。

**Comment by nyrf** [comment]
现在能用一样的名字不？

**Comment by kid1412621** [comment]
貌似官网都没相关信息

**Comment by yuche** [comment]
> 貌似官网都没相关信息

eslint 和编译应该都会报错的的
