### ISSUE TITLE
scroll-view

### ISSUE THREAD

**Issue by yaoshuaibing** [NervJS/taro#10912]
### 相关平台
微信小程序

**小程序基础库: 最新的版本**
**使用框架: Vue 2**

### 复现步骤
scroll-view 里面快速向下滚动，再向上快速返回，获取的scrollTop不准确，有时候误差能达到80多px，再h5没复现到。

### 期望结果
期望结果是scrollTop是准确的

### 实际结果
快速滚动，不准确

### 环境信息
```
Taro CLI 3.3.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\yaoshuaibing\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by yaoshuaibing** [comment]
忘记声明了，是在@scroll 事件里面获取的

**Comment by Chen-jj** [comment]
1. 试试原生 scroll-view 有没有问题
2. 提供一下 demo
