### ISSUE TITLE
vue  h5 从3.3.12升级到3.3.16报错

### ISSUE THREAD

**Issue by lemonSll** [NervJS/taro#10913]
### 相关平台
H5

**浏览器版本: Chrome   版本 96.0.4664.110（正式版本） （64 位）**
**使用框架: Vue 2**

### 复现步骤
项目从3.3.12升级到3.3.13以上所有的版本    列表的渲染都会报错

The node before which the new node is to be inserted is not a child of this node
![image](https://user-images.githubusercontent.com/44395984/146304527-27618cec-aee8-4a9c-b6e2-3a37e44d7605.png)

退回到3.3.12就正常,百度说是因为v-if使用的问题,但是项目包很多个页面了,总不能把所有的v-if都改掉哇
请问一下这个是什么问题啊

### 期望结果
不报错,.可以正常使用

### 实际结果
报错,列表无法渲染

### 环境信息
```
Taro CLI 3.3.16 environment info:
    System:
      OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    npmPackages:
      @tarojs/components: 3.3.16 => 3.3.16
      @tarojs/mini-runner: 3.3.16 => 3.3.16
      @tarojs/runtime: 3.3.16 => 3.3.16
      @tarojs/taro: 3.3.16 => 3.3.16
      @tarojs/webpack-runner: 3.3.16 => 3.3.16
      babel-preset-taro: 3.3.16 => 3.3.16
      eslint-config-taro: 3.3.16 => 3.3.16
```

**Comment by ZakaryCode** [comment]
有demo么，给个看看

**Comment by ZakaryCode** [comment]
未能复现，先关了咯
