### ISSUE TITLE
3.3.17版本h5环境调用 getSystemInfoSync 方法获取到的statusBarHeight值为NaN

### ISSUE THREAD

**Issue by bluescurry** [NervJS/taro#10924]
### 相关平台
H5

**浏览器版本: Chrome 最新版本**
**使用框架: React**

### 复现步骤
Taro.getSystemInfoSync()

### 期望结果
statusBarHeight为""

### 实际结果
statusBarHeight为NaN
![image](https://user-images.githubusercontent.com/19237129/146512233-157ea476-02c1-4c4d-a1ae-94ac004597bd.png)

### 环境信息
```
👽 Taro v3.3.17

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.17 environment info:
    System:
      OS: macOS 11.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.17 => 3.3.17
      @tarojs/components: 3.3.17 => 3.3.17
      @tarojs/mini-runner: 3.3.17 => 3.3.17
      @tarojs/react: 3.3.17 => 3.3.17
      @tarojs/runtime: 3.3.17 => 3.3.17
      @tarojs/taro: 3.3.17 => 3.3.17
      @tarojs/webpack-runner: 3.3.17 => 3.3.17
      babel-preset-taro: 3.3.17 => 3.3.17
      eslint-config-taro: 3.3.17 => 3.3.17
      react: ^17.0.1 => 17.0.2
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10
```

---
### 补充信息
版本选不了3.3.17所以选择3.3.16

**Comment by ZakaryCode** [comment]
statusBarHeight 是个数字类型哦，H5 不支持获取它所以会返回为 `NaN`

**Comment by bluescurry** [comment]
> statusBarHeight 是个数字类型哦，H5 不支持获取它所以会返回为 `NaN`

3.3.16版本返回了空，还按之前版本处理的返回可以吗，这样我们只要判空就可以了

**Comment by bluescurry** [comment]
@ZakaryCode Taro 3.4.0版本h5端返回的 statusBarHeight 还是NaN啊，这个是不打算改了是吗，需要开发者自己兼容吗

**Comment by shanzheng1991** [comment]
> @ZakaryCode Taro 3.4.0版本h5端返回的 statusBarHeight 还是NaN啊，这个是不打算改了是吗，需要开发者自己兼容吗
![image](https://user-images.githubusercontent.com/38523920/219851925-f3b08cd2-0457-4dfd-b1b0-1d75208ff7da.png)

官网还是不支持，请问你是否已经找到办法解决？

**Comment by vaynevayne** [comment]
有设备信息大全的json吗?
