### ISSUE TITLE
【Taro小程序组件传参properties[propName]为null报错】

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#1093]
**问题描述**
[问题描述：小程序给组件传递参数，参数包括函数和对象，函数默认为null]

**复现步骤**
[复现问题的步骤]
1. 引用组件报错

[或者可以直接贴源代码，能贴文字就不要截图]
引用-------
 <Filter
            config={filterConfig}
            // tab
            onRangeSearch={this.tabItemClick.bind(this)}
            // type
            onTypeItemClick={this.typeItemClick.bind(this)}
            onTypeSure={this.typeSure.bind(this)}
            // area
            onAreAItemClick={this.areaAItemClick.bind(this)}
            onAreBItemClick={this.areaBItemClick.bind(this)}
            onAreaSure={this.areaSure.bind(this)}
            // price
            onPriceItemClick={this.priceItemClick.bind(this)}
            onPriceChange={this.priceChange.bind(this)}
            onPriceSure={this.priceSure.bind(this)}
            // more
            onMoreItemClick={this.moreItemClick.bind(this)}
            onClearRange={this.clearMoreSelect.bind(this)}
            onMoreSure={this.moreSure.bind(this)}
            // sort
            onSortItemClick={this.sortItemClick.bind(this)}
            onSortSure={this.sortSure.bind(this)}
          />
组件------
Filter.defaultProps = {
    config: {
        tabData: [
            { name: '类型', key: 'type' },
            { name: '区域', key: 'area' },
            { name: '售价', key: 'price' },
            { name: '更多', key: 'more' },
            { key: 'sort' }
        ],
        areaA: [],
        areaB: [],
        typeList: [],
        priceList: [],
        minPrice: '',
        maxPrice: '',
        moreList: [],
        sortList: [],
        sType: '',
        label: '万'
    },
    onRangeSearch: null,
    onTypeItemClick: null,
    onTypeSure: null,
    onAreAItemClick: null,
    onAreBItemClick: null,
    onAreaSure: null,
    onPriceItemClick: null,
    onPriceBlur: null,
    onPriceChange: null,
    onPriceSure: null,
    onSortItemClick: nu![Uploading e97adfc55ee2ad8074acf5bfc2dfb0b.png…]()

ll,
    onSortSure: null

}
**期望行为**
[不报错]

**报错信息**
![e97adfc55ee2ad8074acf5bfc2dfb0b](https://user-images.githubusercontent.com/42051272/48390572-b590ff00-e73d-11e8-8ace-d5e2182e0fa1.png)
![626496b3dc4aee78ed5effd20d33bcb](https://user-images.githubusercontent.com/42051272/48390579-bfb2fd80-e73d-11e8-9c90-b63d4cc58a82.png)

![1542082990 1](https://user-images.githubusercontent.com/42051272/48390875-035a3700-e73f-11e8-81be-27e008132df5.jpg)

![f17841d9e0278b4acffbe7cdf6d1f02](https://user-images.githubusercontent.com/42051272/48390655-14567880-e73e-11e8-8a87-5683613b764d.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.4]
 - Node.js 版本 [e.g. v10.9.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
判断properties[propName]是否为null

[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
@farzer 不要给 props 传 null，用其他值代替

**Comment by luckyadam** [comment]
@VFiee 你这个问题是 cli 和项目相关的 Taro 依赖版本不统一，可以统一升级到最新版本
