### ISSUE TITLE
@tarojs/webpack-runner 计划什么时候支持 webpack 5？

### ISSUE THREAD

**Issue by az031120103** [NervJS/taro#10933]
### 这个特性解决了什么问题？
公司 h5 项目除了 Taro-h5 其他已经全部改造为微前端应用（用了 webpack 5 module federation 插件）
后续新的 h5 项目也打算用 Taro 开发了，所以此诉求非常迫切。

### 这个 API 长什么样？
https://github.com/NervJS/taro/blob/next/packages/taro-webpack-runner/package.json

{
    "dependencies": {
        "webpack": "^5.0.0",
        ...
    }
    ...
}

**Comment by Chen-jj** [comment]
Q1 会跟进的~

**Comment by Chen-jj** [comment]
Taro v3.5 开始支持
