### ISSUE TITLE
[Taro React Native]编译样式文件问题

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#1094]
**问题描述**
[问题描述：Taro react native 端编译样式文件生成的样式目标文件夹错误]

**复现步骤**
[复现问题的步骤]
1. src目录新建styles文件夹并新建base.less文件【文件要有样式】
2. 在app.js 引用styles文件的base.less
3. 编译RN
4.styles文件夹内没有生成样式文件
5.src目录下生成app_styles.js文件

**期望行为**
[期望styles文件夹生成对应的样式文件]

**报错信息**
![1542076026 1](https://user-images.githubusercontent.com/42051272/48386936-b1111a00-e72e-11e8-85cc-85cc91f2fee8.jpg)
[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.4]
 - Node.js 版本 [e.g. v10.9.0]

 - 报错平台 [RN]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
styles文件夹内没有生成样式文件是正常的，因为 RN 端当前的样式编译规则是，以JS 为入口，所有该 JS 引入的样式，全部整合进一个样式文件，并遵循同一的命名规则，如：app.js => app_styles.js
