### ISSUE TITLE
scroll-view的滚动事件因为节流导致丢失了一些事件

### ISSUE THREAD

**Issue by MMhui** [NervJS/taro#10944]
### 这个特性解决了什么问题？
吸顶tab的渐变和滚动距离绑定，需要实时获取到scrollTop，但是scroll-view有节流会丢失一部分事件，尤其是快速返回到顶部的时候总是丢失最后的一些事件

### 这个 API 长什么样？
微信小程序官方scroll-view组件API上没写但是实际上是支持关闭节流的 throttle="{{ false }}"

**Comment by Chen-jj** [comment]
使用 `@tarojs/plugin-inject` 注入一下 throttle 属性先试一试？

**Comment by MMhui** [comment]
> 使用 `@tarojs/plugin-inject` 注入一下 throttle 属性先试一试？

多谢，有效，可用
plugins: [
    [
      '@tarojs/plugin-inject',
      {
        // 配置项
        components: {
          'scroll-view': {
            throttle: false,
            bindscroll: 'eh',
            'scroll-y': ''
          }
        }
      }
    ]
  ],
就是 @tarojs/plugin-inject 这个注入组件属性的时候是覆盖了原来的而不是新增/修改一个，是我写法有问题吗

**Comment by MMhui** [comment]
> 使用 `@tarojs/plugin-inject` 注入一下 throttle 属性先试一试？

有一些效果，但是还是没有完全实时，这种功能还是使用原生小程序组件开发了

**Comment by ZakaryCode** [comment]
这一类需求可以考虑通过 enhanced 来实现，通过 [ScrollViewContext](https://developers.weixin.qq.com/miniprogram/dev/api/ui/scroll/ScrollViewContext.html) 来设置 `scrollTop` 可以避开该问题

**Comment by zsytssk** [comment]
我现在在做滚动到页面底部加载新的内容，发现每次滚动到页面底部的scrollTop不一样，应该是这个throttle导致的。onScrollToLower应该也是同样的原因，有时候行有时候不行的。建议官方加一个throttle参数，这是最快捷的处理方法。

**Comment by zsytssk** [comment]
> 

按照你说的改了，是可以的

**Comment by zsytssk** [comment]
> 使用 `@tarojs/plugin-inject` 注入一下 throttle 属性先试一试？


按照你说的改了，是可以的
