### ISSUE TITLE
3.3.17自定义路由不能手输路径跳转自定义配置路由

### ISSUE THREAD

**Issue by yangjian84** [NervJS/taro#10947]
### 相关平台
H5

### 复现仓库
[https://github.com/yangjian84/taro-h5-router-test.git](https://github.com/yangjian84/taro-h5-router-test.git)
**浏览器版本: Chrom96.0.4664.110**
**使用框架: React**

### 复现步骤
一、自定义路由不能实现手动输入地址跳转，只能通过Taro.navigate方法跳转

https://user-images.githubusercontent.com/60739864/147028889-19a22145-5e2b-4cf8-b291-82a68f898687.mov

### 期望结果
一、自定义路由能实现手动输入跳转

### 实际结果
一、自定义路由不能实现手动输入跳转

### 环境信息
```
👽 Taro v3.3.17


  Taro CLI 3.3.17 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.17 => 3.3.17 
      @tarojs/mini-runner: 3.3.17 => 3.3.17 
      @tarojs/react: 3.3.17 => 3.3.17 
      @tarojs/runtime: 3.3.17 => 3.3.17 
      @tarojs/taro: 3.3.17 => 3.3.17 
      @tarojs/webpack-runner: 3.3.17 => 3.3.17 
      babel-preset-taro: 3.3.17 => 3.3.17 
      eslint-config-taro: 3.3.17 => 3.3.17 
      react: ^16.10.0 => 16.14.0 

```

**Comment by ZakaryCode** [comment]
示例项目没有权限，不太明确具体问题（手动输入地址是可以的，应该是其他问题导致）

**Comment by yangjian84** [comment]
@ZakaryCode 仓库开放了

**Comment by ZakaryCode** [comment]
customRoutes 配置错误，参考[文档](https://taro-docs.jd.com/taro/docs/2.x/config-detail#h5routercustomroutes)

**Comment by yangjian84** [comment]
```
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  mini: {},
  h5: {
    router: {
      mode: 'hash',
      customRoutes: {
        '/pages/detail/index': '/pages/detail/test1',
        '/pages/detail/index': '/pages/detail/test2'
      }
    }
  }
}
```
按文档配置前面是存在路由，后面是不存在路由，
无法实现多个不存在路由映射到一个存在路由上，
@ZakaryCode

**Comment by ZakaryCode** [comment]
> customRoutes: {
>         '/pages/detail/index': '/pages/detail/test1',
>         '/pages/detail/index': '/pages/detail/test2'
>       }

这样写

```json
...
customRoutes: {
  '/pages/detail/index': ['/pages/detail/test1', 'pages/detail/test2']
},
...
```

**Comment by yangjian84** [comment]
```
      customRoutes: {
        '/pages/index/index': '/index/index',
      }
```
https://user-images.githubusercontent.com/60739864/147327894-7a531e6b-4a9e-4a58-9e92-e3ec08ee5916.mov
我想让页面初始直接跳转到/index/index不要pages，不能实现
@ZakaryCode
