### ISSUE TITLE
Taro升到3.3.17后，h5上Taro.showModal里面cancelText,cancelColor都变成必填的了，没有就报错

### ISSUE THREAD

**Issue by lhkg1988** [NervJS/taro#10949]
### 相关平台
H5

**浏览器版本: Chrome 96**
**使用框架: React**

### 复现步骤
Taro升到3.3.17后，h5上Taro.showModal里面cancelText,cancelColor都变成必填的了，没有就报错
![7d1249fa0541a3e57dcac421028c7e3](https://user-images.githubusercontent.com/7578173/147042684-822e7cff-8c08-44ed-b275-9ed8e67e365b.png)

### 期望结果
保持原来版本的样子，可以正常调用

### 实际结果
会报错

### 环境信息
```
👽 Taro v3.3.17

Taro CLI 3.3.17 environment info:
System:
OS: Windows 10
Binaries:
Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - D:\User\hliu\AppData\Roaming\npm\yarn.CMD
npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by bobsam** [comment]
@ZakaryCode 今天会发版解决？我看了一下 我们本地处理不好做

**Comment by Mr-sgreen** [comment]
> @ZakaryCode 今天会发版解决？我看了一下 我们本地处理不好做

可以先临时劫持下taro弹窗的函数，然后在劫持函数里面判断下有没有传，没有手动传下 或者回退下Taro的版本，taro好像平均都是10天左右一个版本估计没这么快

**Comment by bobsam** [comment]
> > @ZakaryCode 今天会发版解决？我看了一下 我们本地处理不好做
> 
> 可以先临时劫持下taro弹窗的函数，然后在劫持函数里面判断下有没有传，没有手动传下 或者回退下Taro的版本，taro好像平均都是10天左右一个版本估计没这么快

难搞啊。。。还是希望官方发吧，感觉不止这个那么简单
