### ISSUE TITLE
3.3.17 showModal:fail parameter error: parameter.cancelText should be String instead of Undefined'}

### ISSUE THREAD

**Issue by Mr-sgreen** [NervJS/taro#10957]
### 相关平台
H5

### 复现仓库
[https://github.com/Mr-sgreen/taro-bug](https://github.com/Mr-sgreen/taro-bug)
**浏览器版本: Chrome 96.0.4664.110**
**使用框架: Vue 3**

### 复现步骤
  Taro.showModal({
    title: '温馨提示',
    content: '记得按时吃饭',
    showCancel: false,
    confirmColor: '#276FF5',
    confirmText: '知道了',
  });

### 期望结果
正常弹出Modal

### 实际结果
无法弹出Modal，查看控制台报错： showModal:fail parameter error: parameter.cancelText should be String instead of Undefined

### 环境信息
```
  Taro CLI 3.3.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.5 - E:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - E:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
1.猜测要么是ts的定义文件没更新为不允许为undefined
2.要么是内部代码没处理好，要么是我npm版本太低？导致编译出错？

**Comment by Mr-sgreen** [comment]
同样报错的字段还有：
cancelColor
confirmColor
confirmText

**Comment by Mr-sgreen** [comment]
之前好像是如果不传cancelText默认是为 ’取消‘ 的

**Comment by Mr-sgreen** [comment]
官网的文档目前
cancelText
cancelColor
confirmColor
confirmText
这几个字段也是显示非必填

**Comment by bobsam** [comment]
@ZakaryCode @Chen-jj 目前React也有类似的问题

**Comment by ZakaryCode** [comment]
重复错误 #10949
