### ISSUE TITLE
h5端chrome模拟器中iphone6--8等375*667尺寸中ScrollView组件onScrollToLower事件不执行了

### ISSUE THREAD

**Issue by ruoqiang** [NervJS/taro#1097]
**问题描述**
ScrollView组件onScrollToLower在h5端iphone6尺寸的模拟器滚动条滚到底部的时候不执行了，然而其他尺寸（320*568，414*736等）以及微信小程序端却是可以正常执行的

```html关键jsx代码
<ScrollView className='ScrollView' scrollY onScrollToLower={this.onScrollToLower.bind(this)}>
....
...
....
<ScrollView>

```
```js关键js代码
 onScrollToLower(e) {
        console.log('e', e);
        console.log('onScrollToLower');
        setTimeout(() => {
            this.loadMore()
        }, 100)
    }
<ScrollView>

```
**期望行为**
h5端375*667尺寸模拟器下，滚动条滚到底部触发onScrollToLower事件

**报错信息**
滚到底部后console.log('e', e);根本不执行

**系统信息**

 - 操作系统: [Windows 10 chrome版本 68.0.3440.75（正式版本） （64 位）]
 - Taro 版本 [ v1.1.4]
 - Node.js 版本 [v8.9.4]
 - 报错平台 [h5]

**Comment by jinjinjin0731** [comment]
请问下你样式的高度是多少？

**Comment by ruoqiang** [comment]
动态计算出来的高度，为了排除干扰，我特意把高度写死200px。结果还是一样

**Comment by ruoqiang** [comment]
> 请问下你样式的高度是多少？
动态计算出来的高度，为了排除干扰，我特意把高度写死200px。结果还是一样

**Comment by jinjinjin0731** [comment]
可以给个复现的 demo 么。我这里按照你提供的代码片段，以及高度400px 并未出现你说的情况

**Comment by ruoqiang** [comment]
> 请问下你样式的高度是多少？

我发现在什么情况下出现这个问题了。。
请看这里[http://taroh5.pxteam.cn/](http://taroh5.pxteam.cn/)
主要代码
`
 onScrollToLower() {
        console.log('onScrollToLower')
    }
`
`<ScrollView className='ScrollView' scrollY onScrollToLower={this.onScrollToLower.bind(this)} lowerThreshold={20}>`

我这边在iphone模拟器375宽度下
滚动底部 console.log('onScrollToLower')这里没有打印出来，其他尺寸就是可以打印

**Comment by ruoqiang** [comment]
> > 请问下你样式的高度是多少？
> 
> 我发现在什么情况下出现这个问题了。。
> 请看这里http://taroh5.pxteam.cn/
> 主要代码
> `onScrollToLower() { console.log('onScrollToLower') }`
> `<ScrollView className='ScrollView' scrollY onScrollToLower={this.onScrollToLower.bind(this)} lowerThreshold={20}>`
> 
> 我这边在iphone模拟器375宽度下
> 滚动底部 console.log('onScrollToLower')这里没有打印出来，其他尺寸就是可以打印

然后我把上面那个图片的容器整体删除掉，只留下一个一个滚动容器，，在375尺寸下就可以触发onScrollToLower事件了
结论：我猜测，ScrollView组件在375尺寸下，只能放在页面顶部才可以触发onScrollToLowe事件

**Comment by jinjinjin0731** [comment]
确实，你的的确有这个问题，你试一下升级到最新版本有没有这个情况，我这边也用你这么长的列表试一下，尝试复现

**Comment by ruoqiang** [comment]
> 确实，你的的确有这个问题，你试一下升级到最新版本有没有这个情况，我这边也用你这么长的列表试一下，尝试复现

昨天下午刚升级的，把record-img这个元素删除就可以触发滚到底部事件了。你顶部加个元素试一下

**Comment by jinjinjin0731** [comment]
ok 我等下试一下

**Comment by jinjinjin0731** [comment]
hello ,抱歉忘记回复了在 最新版中，这个问题还存在吗
