### ISSUE TITLE
Input confirmType= send不生效

### ISSUE THREAD

**Issue by codeLose** [NervJS/taro#10978]
### 相关平台
支付宝小程序

**小程序基础库: 2.6.6**
**使用框架: React**

### 复现步骤
使用支付宝原生input confirmType= send 键盘为发送 生效
![IMG_4481](https://user-images.githubusercontent.com/23007643/147440199-cea64b2b-d927-4d4e-9e15-e31a9b0df051.JPG)

<input class="input" confirm-type="send" focus="{{focus}}" onFocus="onFocus" onBlur="onBlur" placeholder="input something" />

### 期望结果
confirmType= send

### 实际结果
软键盘为换行

### 环境信息
```
 Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.2 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^16.10.0 => 16.14.0 

```

**Comment by codeLose** [comment]
使用支付宝原生 不适用taro confirmType= send生效 且头部没有done按钮

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/12036#issuecomment-1328166185

same reason
