### ISSUE TITLE
为什么我会频繁出现 Component is not found in path 这样的错误呢？

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro#1098]
然后只要手动编辑一下那个组件（随便怎么编辑 ）再保存一下就能找到了~

我的文件结构差不多就是这样：

src
├── app.js
├── app.scss
├── assets
│   └── images
│       ...
├── config
│   ├── Config.js
│   └── index.js
├── fashionipo-services
│   ├── ...
├── fashionipo-shared-taro
│   ├── common
│   │   ├── BaseComponent.js
│   │   └── index.js
│   ├── components
│   │   ├── float-layout
│   │   │   ├── FloatLayout.js
│   │   │   ├── FloatLayout.scss
│   │   │   └── index.js
│   │   ├── hoc
│   │   │   ├── index.js
│   │   │   └── withUtils.js
│   │   ├── index.js
│   │   ├── input-number
│   │   │   ├── InputNumber.js
│   │   │   ├── InputNumber.scss
│   │   │   └── index.js
│   │   ├── number-field
│   │   │   ├── NumberField.js
│   │   │   ├── NumberField.scss
│   │   │   └── index.js
│   │   ├── options-field
│   │   │   ├── OptionsField.js
│   │   │   ├── OptionsField.scss
│   │   │   └── index.js
│   │   ├── responsive-image
│   │   │   ├── ResponsiveImage.js
│   │   │   ├── ResponsiveImage.scss
│   │   │   └── index.js
│   │   └── tabs
│   │       ├── Badge.scss
│   │       ├── Tabs.js
│   │       ├── Tabs.scss
│   │       └── index.js
│   └── styles
│       └── _mixins.scss
├── features
│   ├── home
│   │   ├── activity
│   │   │   ├── Article.js
│   │   │   ├── Article.scss
│   │   │   ├── Posts.js
│   │   │   ├── Posts.scss
│   │   │   ├── index.js
│   │   │   └── index.scss
│   │   └── home
│   │       ├── Activities.js
│   │       ├── Activities.scss
│   │       ├── ActivityCard.js
│   │       ├── ActivityCard.scss
│   │       ├── Banner.js
│   │       ├── Banner.scss
│   │       ├── MainActivity.js
│   │       ├── MainActivity.scss
│   │       ├── index.js
│   │       └── index.scss
│   ├── market
│   │   ├── market
│   │   │   ├── Products.js
│   │   │   ├── Products.scss
│   │   │   ├── index.js
│   │   │   └── index.scss
│   │   └── product
│   │       ├── BuyPicker.js
│   │       ├── BuyPicker.scss
│   │       ├── Related.js
│   │       ├── Related.scss
│   │       ├── Specs.js
│   │       ├── Specs.scss
│   │       ├── index.js
│   │       └── index.scss
│   └── user
│       └── user
│           ├── OrderCard.js
│           ├── OrderCard.scss
│           ├── OrderList.js
│           ├── OrderList.scss
│           ├── index.js
│           └── index.scss
├── index.html
├── pages
│   └── index
│       ├── index.js
│       └── index.scss
├── shared
│   └── components
│       ├── activity-timer
│       │   ├── ActivityTimer.js
│       │   ├── ActivityTimer.scss
│       │   └── index.js
│       ├── hash-tags
│       │   ├── HashTags.js
│       │   ├── HashTags.scss
│       │   └── index.js
│       ├── index.js
│       ├── product-list
│       │   ├── ProductList.js
│       │   ├── ProductList.scss
│       │   └── index.js
│       ├── product-name
│       │   ├── ProductName.js
│       │   ├── ProductName.scss
│       │   └── index.js
│       ├── product-price
│       │   ├── ProductPrice.js
│       │   ├── ProductPrice.scss
│       │   └── index.js
│       └── section-title
│           ├── SectionTitle.js
│           ├── SectionTitle.scss
│           └── index.js
├── styles
│   ├── _custom.scss
│   ├── _icons.scss
│   ├── _media.scss
│   ├── _mixins.scss
│   ├── _variables.scss
│   ├── ddin.scss
│   ├── fashionicon.scss
│   ├── global.scss
│   └── ripples.scss
├── taro-ui-styles
│   ├── mixins
│   │   ├── index.scss
│   │   └── libs
│   │       ├── absolute-center.scss
│   │       ├── active.scss
│   │       ├── alignhack.scss
│   │       ├── border.scss
│   │       ├── clearfix.scss
│   │       ├── disabled.scss
│   │       ├── flex.scss
│   │       ├── hairline.scss
│   │       ├── line.scss
│   │       ├── overlay.scss
│   │       ├── placeholder.scss
│   │       ├── shade.scss
│   │       └── tint.scss
│   └── theme
│       └── default.scss
└── templates
    ├── Container.js
    ├── Container.scss
    └── index.js

**Comment by jswxwxf** [comment]
npm -6.4.1
Taro v1.0.7

**Comment by jswxwxf** [comment]
<img width="751" alt="2018-11-13 2 05 29" src="https://user-images.githubusercontent.com/1768767/48394239-b92c8200-e74d-11e8-953c-ef7eac02208c.png">

现在又报这样的错，可是这个目录明明生成了的。

<img width="851" alt="2018-11-13 2 10 44" src="https://user-images.githubusercontent.com/1768767/48394323-0b6da300-e74e-11e8-9c40-97a0532239e2.png">

**Comment by foreverpw** [comment]
+1

**Comment by RukaiYu** [comment]
+1100101010

**Comment by Wuguanghua** [comment]
+1

**Comment by jswxwxf** [comment]
我之前发生这样的错误是因为我用了很多嵌套的类似于 redux 里的 @connect 这样的注解式的 HOC，这样会报这个错，把这些嵌套注解式的 HOC 写成函数式的比如 connect(Component) 就没有问题了，不知道你们是不是也是这样的用法。

**Comment by pollux2015** [comment]
我也是  非常频繁

**Comment by zjxpcyc** [comment]
+1

**Comment by saviourdog** [comment]
+11

**Comment by flyingalex** [comment]
我遇到这个情况一般是因为写的代码有问题，taro不告诉你哪里错了，要自己去找
