### ISSUE TITLE
h5过渡动画开启后，tabbar 页面被撑高

### ISSUE THREAD

**Issue by jianhao2010303** [NervJS/taro#10981]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**浏览器版本: chrome96**
**使用框架: React**

### 复现步骤
在config.js中开启h5动画（min-height: 100vh）把tabbar页面默认撑高。

### 期望结果
min-height: 100vh 不影响tabbar页面。

### 实际结果
tabbar页面会出现滚动条。

### 环境信息
```
  Taro CLI 3.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - D:\Node\node.EXE
      Yarn: 1.22.11 - D:\Node\node_global\yarn.CMD
      npm: 6.14.15 - D:\Node\npm.CMD
```

**Comment by jianhao2010303** [comment]
在非tabbar页面刷新，返回方法后，页面叠加形成穿透样式。

**Comment by jianhao2010303** [comment]
第三个问题： 无法关闭h5过渡动画，请问这个怎么解决？

**Comment by ZakaryCode** [comment]
> 第三个问题： 无法关闭h5过渡动画，请问这个怎么解决？

app.config 配置 `animation: false`

**Comment by ZakaryCode** [comment]
> ### 复现步骤
> 在config.js中开启h5动画（min-height: 100vh）把tabbar页面默认撑高。

浏览器限制，没办法解决，毕竟 h5 中页面高度是包括 tabbar 高度的

**Comment by ZakaryCode** [comment]
> 在非tabbar页面刷新，返回方法后，页面叠加形成穿透样式。

没太理解到你的意思？是指页面叠加，还是动画时页面透明页面穿透？

- 刷新导致的页面叠加问题没有复现到，但是社区有人提到，应该是版本依赖未对齐导致
- 动画页面穿透可以手动配置 taro_page 样式解决

**Comment by jianhao2010303** [comment]
升级3.3.19路由问题好了。
