### ISSUE TITLE
input组件的 input.d.ts  类型约束 type类型缺少 psssword字段

### ISSUE THREAD

**Issue by 422720735** [NervJS/taro#10991]
### 这个特性解决了什么问题？
   <Input type='password' password placeholder='这是一个密码输入框'/>  这是官方介绍组件用法 是有 type=''password' 约束

### 这个 API 长什么样？
 /** input 的类型
   * @default "text"
   * @supported weapp, h5, rn
   * @rn 部分支持
   */
  type?: 'text' | 'number' | 'idcard' | 'digit' | 'pssword'

**Comment by jianhao2010303** [comment]
input 的password会触发浏览器未在form表单中的警告。

**Comment by ZakaryCode** [comment]
当前通过 `password` 参数启用密码类型，而非 type。
