### ISSUE TITLE
getDerivedStateFromProps这些新生命周期api目前有打算跟上吗

### ISSUE THREAD

**Issue by suiyi8760** [NervJS/taro#11]
激动人心的项目，react阵营终于有了自己的小程序框架，支持rn转换后比mpvue强多了，不过目前react项目都在逐步切换到新生命周期api，想了解下aotu的大大们怎么看

**Comment by luckyadam** [comment]
有！有计划支持到 React 的新 API

**Comment by yuche** [comment]
实际上支持这些新 API 对我们框架开发者是一种福利，研究 React 内部机制和生命周期以及他们背后的逻辑是一件非常有意思的事情。而且 React 16 的更新有一些生命周期和 API 的确能帮助开发者写出更健壮的代码。

所以你问我支持不支持，我说支持。

**Comment by javaLuo** [comment]
另外，是时候开发一套UI组件库了

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/apis/about/tarocomponent.html#static-getderivedstatefromprops
