### ISSUE TITLE
3.3.18 taro路由问题

### ISSUE THREAD

**Issue by sanmmm** [NervJS/taro#11004]
### 相关平台
H5

### 复现仓库
[https://github.com/sanmmm/taro_report](https://github.com/sanmmm/taro_report)
**浏览器版本: chrome  96.0.4664.110**
**使用框架: React**

### 复现步骤
测试版本为： 3.3.18

1.  设置basename, 访问  /basename 没有重定向到默认的 /basename/pages/index/index 页
2.  访问 /basename/pages/index/index?a=1，通过useRouter 获取不到params

### 期望结果
如上

### 实际结果
如上

### 环境信息
```

  Taro CLI 3.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
> 1. 设置basename, 访问  /basename 没有重定向到默认的 /basename/pages/index/index 页

- 该问题未能复现到，可以升级解决

> 2. 访问 /basename/pages/index/index?a=1，通过useRouter 获取不到params

- browser 模式确实有这个问题，下一个版本修复

**Comment by Phlen** [comment]
hash模式下，首页的自定义路由也没有生效；比如 设置: '/pages/index/index': '/'; 浏览器打开 xxx/#/; 默认跳转到 xxx/#/pages/index/index了
