### ISSUE TITLE
如何预览pdf文件？

### ISSUE THREAD

**Issue by xueyida** [NervJS/taro#1100]
在pc端可以使用iframe标签实现pdf预览，taro中不能使用html标签，即使用了iframe标签也不能展示出pdf的内容

**Comment by yuche** [comment]
pc 端预览 pdf 文件是需要浏览器支持的，chrome 这样的新浏览器可以，老浏览器就不行了。
小程序你得用 openDocument 之类的方法。

Taro 这样的框架主要是包一层给你解决视图方面的问题，操纵系统功能之类得看相关平台是否支持这个功能。

**Comment by xueyida** [comment]
@yuche 在ios手机的浏览器上iframe可以使用，在android上会自行下载，查到有用PDF.js准备试一下

**Comment by JakeWoki** [comment]
@xueyida 后来怎么解决的？h5集成PDF.js就可以，小程序openDocument会打开新界面，如果不打开新界面，而且不占满全屏要怎么做？

**Comment by BunnyShing** [comment]
> @xueyida 后来怎么解决的？h5集成PDF.js就可以，小程序openDocument会打开新界面，如果不打开新界面，而且不占满全屏要怎么做？PDF.js编译小程序过不去

在小程序使用web-view（但这种方式感觉容易被微信审核驳回）或者依靠后端把pdf切成图片，再输出给前端以图片显示，但是这种方式需要后端支持
