### ISSUE TITLE
微信小程序头像昵称填写功能 

### ISSUE THREAD

**Issue by KevenGarnet** [NervJS/taro#11007]
### 这个特性解决了什么问题？
解决open-data组件失效后，用户头像昵称的获取。
文档链接：https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=116405874355UHBf&version=&token=1370566002&lang=zh_CN

### 这个 API 长什么样？
button组件支持一下就好了

**Comment by Apigflying** [comment]
同求

**Comment by wenxiuYang** [comment]
+1

**Comment by AdvancedCat** [comment]
PR https://github.com/NervJS/taro/pull/11402
