### ISSUE TITLE
 React Navigation 升级到 6.x

### ISSUE THREAD

**Issue by zhiqingchen** [NervJS/taro#11017]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
无

### 期望结果
6.x

### 实际结果
5.x

### 环境信息
```
👽 Taro v3.3.15


  Taro CLI 3.3.15 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.12.0 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
      npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.15 => 3.3.15
      @tarojs/components: 3.3.15 => 3.3.15
      @tarojs/mini-runner: 3.3.15 => 3.3.15
      @tarojs/react: 3.3.15 => 3.3.15
      @tarojs/runtime: 3.3.15 => 3.3.15
      @tarojs/taro: 3.3.15 => 3.3.15
      @tarojs/webpack-runner: 3.3.15 => 3.3.15
      babel-preset-taro: 3.3.15 => 3.3.15
      eslint-config-taro: 3.3.15 => 3.3.15
      react: ^17.0.2 => 17.0.2
      react-native: ^0.66.0 => 0.66.3
    npmGlobalPackages:
      typescript: 4.2.3
```

**Comment by Anoninz** [comment]
这里文档没有更新，还在提示 5.x。
我看文档去配置都没生效...
https://taro-docs.jd.com/docs/react-native-remind#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE

**Comment by zhiqingchen** [comment]
> 这里文档没有更新，还在提示 5.x。 我看文档去配置都没生效... https://taro-docs.jd.com/docs/react-native-remind#%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE

文档已修正，如不生效可尝试清缓存重启 yarn dev:rn --reset-cache

具体参考pr https://github.com/NervJS/taro/pull/11344

**Comment by Anoninz** [comment]
> 文档已修正

我看官方文档还没有更新？是没有部署吗？

> 三、导航
> React Native 导航是封装的 React-Navigation 5.x，为了更好的方便业务自定义，支持全局与页面配置中透传React Navigation的配置，但注意以下导航相关设置Taro 3.x 生效。

另外 defineAppConfig 好像还没增加 rnConfig 的类型提示。
