### ISSUE TITLE
当配置路由基准路径(h5.router.basename)时,打开多个页面(Taro.navigateTo),回退页面会显示第一个页面,浏览器输入框内的地址确是上一地址

### ISSUE THREAD

**Issue by xiao-xiansheng** [NervJS/taro#11010]
### 相关平台
H5

### 复现仓库
[git@github.com:xiao-xiansheng/taro-router-back-demo.git](git@github.com:xiao-xiansheng/taro-router-back-demo.git)
**浏览器版本: 微信浏览器,微信开发者工具 RC V1.05.2112141,Chrome 96**
**使用框架: React**

### 复现步骤
第一步访问:/h5Gas/pages/index/index
第二步点击页面上的跳转按钮进入第二个页面
第三步点击页面上的跳转按钮进入第三个页面
第四步点击回退
此时页面显示的是第一个页面的信息,浏览器地址确是正确的

### 期望结果
当在第三页面点击浏览器回退按钮时,应该回到第二个页面

### 实际结果
回到第一个页面

### 环境信息
```
Taro v3.3.7


  Taro CLI 3.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD  
```

---
### 补充信息
当配置了基准路由时(h5.router.basename),不管打开多少个页面回退的话,都会显示第一个页面
浏览器地址是正确的,但是页面显示不正确
处理POP操作的时候  路由控制页面显示不正确

**Comment by xiao-xiansheng** [comment]
taro/packages/taro-router/src/router/index.ts 
`const pageConfig = config.routes.find` 没有考虑配置了h5.router.basename的情况导致title丢失
`if (action === 'POP') {` 判断里面没有考虑配置了h5.router.basename的情况导致回退会回到第一个页面
@ZakaryCode

**Comment by ZakaryCode** [comment]
> 

与此无关，另外旧版本有相关联问题，新版本一斤修复，可以更新尝试
