### ISSUE TITLE
babel  taro 预设   useBuiltIns:'usage' 

### ISSUE THREAD

**Issue by hetao1024768** [NervJS/taro#11022]
### 相关平台
H5

**浏览器版本: Chrome 96**
**使用框架: Vue 3**

### 复现步骤
taro init myApp
选择Vue3 nutui
babel 配置文件修改 taro 预设 添加 useBuiltIns: 'usage'
yarn dev:h5 或者 yarn dev:weapp 问题重现

### 期望结果
期望正常运行demo

### 实际结果
打包中关于corejs的问题

### 环境信息
```
issue helper上面版本选择不了3.3.19

👽 Taro v3.3.19


  Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
> ### 复现步骤
> taro init myApp 选择Vue3 nutui babel 配置文件修改 taro 预设 添加 useBuiltIns: 'usage' yarn dev:h5 或者 yarn dev:weapp 

未能通过该流程复现问题 🤔
