### ISSUE TITLE
taroV3.3中使用taro-ui

### ISSUE THREAD

**Issue by dinglino1** [NervJS/taro#11021]
### 这个特性解决了什么问题？
能否在taro-ui能不能同步更新一下文档，使用的taro3.3版本的只能装taro-ui:^3.0.0-alpha.10
第一次用taro框架，导致我编译一直报错误，不知道什么原因导致的。这个问题浪费了我好长时间

### 这个 API 长什么样？
希望在taro-ui中说明一下

**Comment by konka-king** [comment]
taro-ui 已经被抛弃了（至少看起来是这样），现在推的是 nutui , 有 vue 和 react 2个版本
