### ISSUE TITLE
windows开发 小程序组件事件绑定无效

### ISSUE THREAD

**Issue by DantesSword** [NervJS/taro#1103]
提示 Do not have goMenu handler in current page: pages/home/index. Please make sure that goMenu handler has been defined in pages/home/index, or pages/home/index has been added into app.json

![image](https://user-images.githubusercontent.com/12396816/48402394-880c7b80-e766-11e8-87e5-5be97cce8e96.png)

**Comment by DantesSword** [comment]
mac上可以正常开发    
win7无效

**Comment by luckyadam** [comment]
麻烦贴一下编译后的 app.json 代码，以及你的文件目录结构截图
