### ISSUE TITLE
Taro-h5  路由支持动画 导致 页面内的 position: fixed 失效

### ISSUE THREAD

**Issue by ctocto** [NervJS/taro#11038]
### 相关平台
H5

### 复现仓库
[https://github.com/ctocto/taro-bug-demo.git](https://github.com/ctocto/taro-bug-demo.git)
**浏览器版本: Chrome 96**
**使用框架: React**

### 复现步骤
升级到 Taro 3.3.19 ， Taro-h5 路由支持过渡动画。但是导致页面内的position:fixed 失效。

场景：页面内有一个 浮动的快捷功能按钮。

### 期望结果
position:fixed 窗口定位正常;

或者

该如何实现此类需求

### 实际结果
祖先元素(.taro_page) transform 属性值不为 none ，导致 position:fixed 失效

### 环境信息
```
Taro v3.3.19


  Taro CLI 3.3.19 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.19 => 3.3.19 
      @tarojs/components: 3.3.19 => 3.3.19 
      @tarojs/mini-runner: 3.3.19 => 3.3.19 
      @tarojs/react: 3.3.19 => 3.3.19 
      @tarojs/runtime: 3.3.19 => 3.3.19 
      @tarojs/taro: 3.3.19 => 3.3.19 
      @tarojs/webpack-runner: ^3.3.19 => 3.3.19 
      babel-preset-taro: 3.3.19 => 3.3.19 
      eslint-config-taro: 3.3.19 => 3.3.19 
      react: ^17.0.2 => 17.0.2 
    npmGlobalPackages:
      typescript: 3.0.3
```

**Comment by ZakaryCode** [comment]
如果需要用到 fixed 建议关掉动画，参考[文档](https://docs.taro.zone/docs/next/app-config#animation)

**Comment by linhaobin** [comment]
遇到相同问题，建议在过渡完之后，移除 transform 样式

**Comment by dolphin0618** [comment]
同样问题，页面都飞了

**Comment by ctocto** [comment]
我尝试`ReactDom.createPortal` api 来解决问题。不确定适用于所有场景。

具体实现：https://github.com/ctocto/taro-bug-demo/blob/master/src/components/withPositionFixed.js

高阶组建包裹需要`position：fixed`的组建就好了：`withPositionFixed(HighButton)`

[仓库](https://github.com/ctocto/taro-bug-demo.git) 有使用demo
