### ISSUE TITLE
redux connect 绑定存在bug，若在父级组件中使用@connec映射 store中的数据，那么子组件当中再次使用connect映射store就无法得到结果，除非删除父级组件中的映射才可以

### ISSUE THREAD

**Issue by powerlau** [NervJS/taro#1104]
**问题描述**
redux connect 绑定存在bug，若在父级组件中使用@connec映射 store中的数据，那么子组件当中再次使用connect映射store就无法得到结果，除非删除父级组件中的映射才可以

**复现步骤**
[复现问题的步骤]

index.js (import 了一个自定义组件Cmp)，同时在render当中使用

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import Cmp from './cmp'

import { add, minus, asyncAdd } from '../../actions/counter'

import './index.scss'


@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add () {
    dispatch(add())
  },
  dec () {
    dispatch(minus())
  },
  asyncAdd () {
    dispatch(asyncAdd())
  }
}))
class Index extends Component {

    config = {
    navigationBarTitleText: '首页'
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.props.add}>+</Button>
        <Button className='dec_btn' onClick={this.props.dec}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View><Text>{this.props.counter.num}</Text></View>
        <View><Text>Hello, World</Text></View>
        <Cmp />
      </View>
    )
  }
}

export default Index
```

```js

cmp.js（自定义组件）
`import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'

@connect(({ counter }) => ({
  counter
}), (dispatch) => ({

}))
class Cmp extends Component {
    render() {
        return <View>{this.props.counter.num}</View>
    }
}
```

**期望行为**
当在index.js当中 按加减按钮，index.js当中的 this.props.counter.num应当和cmp.js当中的this.props.counter.num保持一致才对，然而点击加减按钮改变的只有index.js当值的 num，而cmp.js没有任何变化，除非index.js 代码当中不去映射counter，那么cmp组件才能得到结果，否则cmp当中的num值一直为0

**报错信息**

**系统信息**

 - 操作系统:  windows 10
    "@tarojs/async-await": "^1.1.4",
    "@tarojs/components": "^1.1.4",
    "@tarojs/redux": "^1.1.4",
    "@tarojs/redux-h5": "^1.1.4",
    "@tarojs/router": "^1.1.4",
    "@tarojs/taro": "^1.1.4",
    "@tarojs/taro-alipay": "^1.1.4",
    "@tarojs/taro-h5": "^1.1.4",
    "@tarojs/taro-swan": "^1.1.4",
    "@tarojs/taro-weapp": "^1.1.4",
    "nervjs": "^1.3.5",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"

**Comment by luckyadam** [comment]
确实存在这个问题，目前的解决方案是，在服组件 connect，然后传下去

**Comment by zhangjie1314** [comment]
我也遇到这个问题了 😂

**Comment by ivan-GM** [comment]
我也出现这个问题了，当时提出来，没描述清楚。。。

**Comment by zw130633** [comment]
@luckyadam 我上周也发现这个问题了，只是忙的没来得及提 Issues。目前除了从父组件传参，还有一个解决办法，就是子组件不用装饰器，用普通方式 connect 也是可以的，这个方案比传参要好多了

**Comment by powerlau** [comment]
> @luckyadam 我上周也发现这个问题了，只是忙的没来得及提 Issues。目前除了从父组件传参，还有一个解决办法，就是子组件不用装饰器，用普通方式 connect 也是可以的，这个方案比传参要好多了

使用 export default connect(mapStateToProps, mapDispatchToProps)(component) 这种方式么？我没在taro里面这没用过，原来这样taro也能用啊

**Comment by luckyadam** [comment]
@zw130633 收到，我们看看~

**Comment by ivan-GM** [comment]
希望这个问题赶紧这个问题，父组件用装饰器写connect，子组件不用，感觉很别扭。。。😂

**Comment by zw130633** [comment]
> > @luckyadam 我上周也发现这个问题了，只是忙的没来得及提 Issues。目前除了从父组件传参，还有一个解决办法，就是子组件不用装饰器，用普通方式 connect 也是可以的，这个方案比传参要好多了
> 
> 使用 export default connect(mapStateToProps, mapDispatchToProps)(component) 这种方式么？我没在taro里面这没用过，原来这样taro也能用啊

是的，我就是在子组件里这样写的

**Comment by shenghanqin** [comment]
@powerlau 你可以帮忙试试看最新版本吗？
