### ISSUE TITLE
componentWillUnmount不会正确执行

### ISSUE THREAD

**Issue by 549193902** [NervJS/taro#11058]
### 相关平台
H5

**浏览器版本: edge**
**使用框架: React**

### 复现步骤
第一次打开任意页面(或页面强制刷新一次)，navigateTo进入第二个页面，第一个页面componentWillUnmount不会执行。
    componentDidShow() {
        const onHideEventId = this.$instance.router.onHide;
        eventCenter.on(onHideEventId, this.componentWillUnmount);
    }
监听可以触发，不是子组件

### 期望结果
能和之后的跳转一样，能正常触发componentWillUnmount

### 实际结果
不能触发卸载

### 环境信息
```
Taro v3.3.19


  Taro CLI 3.3.19 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/components: 3.3.19 => 3.3.19 
      @tarojs/mini-runner: 3.3.19 => 3.3.19 
      @tarojs/react: 3.3.19 => 3.3.19 
      @tarojs/runtime: 3.3.19 => 3.3.19 
      @tarojs/taro: 3.3.19 => 3.3.19 
      @tarojs/webpack-runner: 3.3.19 => 3.3.19 
      babel-preset-taro: 3.3.19 => 3.3.19 
      eslint-config-taro: 3.3.19 => 3.3.19 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
```

**Comment by ZakaryCode** [comment]
这是正常的，页面跳转不会触发卸载事件。

**Comment by 549193902** [comment]
谢谢~~，从后端转过来的，抱歉。 但是之后跳转都会触发。，也试过用componentDidHide， navigateBack返回页面也不会触发，有什么方法可以确保页面切换出时必定触发的方法吗

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/hooks#usedidshow)
