### ISSUE TITLE
请问H5能配置动态路由吗？

### ISSUE THREAD

**Issue by CaanDoll** [NervJS/taro#11059]
### 这个特性解决了什么问题？
支持多种多样的路由

### 这个 API 长什么样？
在自定义路由里配置动态路由

```javascript
h5: {
    router: {
      customRoutes: {
        '/pages/index/index': '/:id/index',
      }
    }
  }
```

**Comment by ZakaryCode** [comment]
目前不可以，后续优化支持

**Comment by ZakaryCode** [comment]
已经实现，可以升级体验

**Comment by Benjaminbai** [comment]
> 已经实现，可以升级体验

请问如何使用？
假如我在页面中直接使用Taro.createRouter(),行的通么？

**Comment by yoyo837** [comment]
> 

看一下文档, 要跨端通用, 统一调用, 可能还需要二次封装一下方法.

**Comment by Benjaminbai** [comment]
> > 
> 
> 看一下文档, 要跨端通用, 统一调用, 可能还需要二次封装一下方法.

大佬，请问H5，想从接口中获取菜单配置，有什么方案么？
<img width="416" alt="image" src="https://user-images.githubusercontent.com/23426556/222326914-bfc4d6d4-2392-4487-b24a-9da45302e753.png">
这是我的想法，但是报错
<img width="767" alt="image" src="https://user-images.githubusercontent.com/23426556/222327065-d92b0ee7-39eb-40a8-a936-66234260b19d.png">
