### ISSUE TITLE
taro.downloadFile的onProgressUpdate报错

### ISSUE THREAD

**Issue by tgwstyle** [NervJS/taro#11063]
### 相关平台
微信小程序

**小程序基础库: 2.18.1**
**使用框架: React**

### 复现步骤
1.找到一个文件连接
2.使用Taro.downloadFile在
const downloadTask = Taro.downloadFile()
downloadTask .onProgressUpdate(ret => {
     console.log(ret)
})

### 期望结果
能在回调函数中返回进度信息

### 实际结果
downloadTask .onProgressUpdate is not a function

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.4 - E:\node\node.EXE
      Yarn: 1.22.5 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - E:\node\npm.CMD

```

**Comment by AdvancedCat** [comment]
目前 Taro.downloadFile 返回一个 promise 对象：
`const xPromise = Taro.downloadFile({...})`

同时挂载了 progress 和 abort 方法。可以使用 xPromise.progress 获取进度信息：
`xPromise.progress(ret => {
console.log(ret)
})`

我们会继续跟进该问题。
