### ISSUE TITLE
输入框H5输入身份证和小数限制错误

### ISSUE THREAD

**Issue by Twining** [NervJS/taro#1107]
**问题描述**
身份证和小数的限制在H5中依旧可以输入中文和字母还有符号

**复现步骤**
[复现问题的步骤]
type='idcard'
type='digit'

**期望行为**
输入框限制正确

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.7
 - Node.js 版本 v10.13.0
 - 报错平台 h5

**Comment by jinjinjin0731** [comment]
这两个 type 在 H5 不支持，后续看一下如何兼容一下吧

**Comment by jinjinjin0731** [comment]
该问题升级到最新版即可解决，真机体验即可(浏览器可能不行哦)
