### ISSUE TITLE
开发环境根据提示设置NODE_ENV=production, 没有开启代码压缩

### ISSUE THREAD

**Issue by AdonLee** [NervJS/taro#11077]
### 相关平台
微信小程序

**小程序基础库: 2.11.1**
**使用框架: React**

### 复现步骤
set NODE_ENV=production && taro build --type weapp --watch

### 期望结果
开启代码压缩

### 实际结果
没有开启代码压缩

### 环境信息
```
Taro CLI 3.3.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
```

**Comment by AdvancedCat** [comment]
这样设置有何应用场景吗？
Taro编译时，--watch 的参数会覆盖 NODE_ENV=production 的设置。

**Comment by AdonLee** [comment]
> 

开发环境没压缩包太大， 小程序发不了测试，也预览不了

**Comment by AdvancedCat** [comment]
可以这样呀：`taro build --type weapp --watch --env production`

**Comment by AdonLee** [comment]
> 

![image](https://user-images.githubusercontent.com/5396468/151291308-306dd329-3d59-4d4f-a43f-a84f666138c8.png)

**Comment by ZakaryCode** [comment]
```sh
NODE_ENV=production taro build --type weapp --watch
```

**Comment by ZakaryCode** [comment]
> ### 复现步骤
> set NODE_ENV=production && taro build --type weapp --watch

这样写设置的并不是这一次运行的环境变量

**Comment by AdonLee** [comment]
> > ### 复现步骤
> > set NODE_ENV=production && taro build --type weapp --watch
> 
> 这样写设置的并不是这一次运行的环境变量

这是windows的写法，cli提示这么用的，具体你可以看看源码

**Comment by ZakaryCode** [comment]
会提示这句话就说明设置失败了啊 😂

**Comment by xavierror** [comment]
```json
"scripts": {
  "dev:weapp": "NODE_ENV=production taro build --type weapp --watch",
}
```

**Comment by LingF** [comment]
`set NODE_ENV=production&& taro build --type weapp --watch` 去掉&&前的空格可以设置成功
