### ISSUE TITLE
useDidshow 报错 vue3

### ISSUE THREAD

**Issue by Mo-zixin** [NervJS/taro#11074]
### 相关平台
H5

### 复现仓库
[https://github.com/jdf2e/nutui-demo/tree/master/taro](https://github.com/jdf2e/nutui-demo/tree/master/taro)
**浏览器版本: chrome 97**
**使用框架: Vue 3**

### 复现步骤
<script setup>
 import {useDidShow} from '@tarojs/taro'
 useDidShow(()=>{
   console.log('show');
 })
</script>

### 期望结果
正常使用

### 实际结果
无法使用 

### 环境信息
```
Taro v3.3.20


  Taro CLI 3.3.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\WindowApps\Professional\nodejs\node.EXE
      Yarn: 1.22.15 - C:\WindowApps\Professional\yarn\bin\yarn.CMD
      npm: 6.14.15 - C:\WindowApps\Professional\nodejs\npm.CMD
```

**Comment by Mo-zixin** [comment]
![image](https://user-images.githubusercontent.com/67213177/148790979-fe45733e-8c49-43ca-8ee2-964fa77264e7.png)

**Comment by b2nil** [comment]
Taro 升级到 3.4 才行

**Comment by ZakaryCode** [comment]
duplicate #9779

Taro v3.4+ 开始支持小程序生命周期的 Composition API。
