### ISSUE TITLE
Taro.chooseLocation h5的返回依然报错

### ISSUE THREAD

**Issue by jianhao2010303** [NervJS/taro#11076]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**浏览器版本: chrome97**
**使用框架: React**

### 复现步骤
Taro.chooseLocation h5的返回按钮点击，报错。

### 期望结果
Taro.chooseLocation h5的返回按钮点击正常关闭。

### 实际结果
Taro.chooseLocation h5的返回按钮点击，报错。

### 环境信息
```
  Taro CLI 3.3.20 environment info:   
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - D:\Node\node.EXE
      npm: 8.1.2 - D:\Node\npm.CMD   
```

**Comment by ZakaryCode** [comment]
未能复现到该问题，错误抛出并不会导致页面关闭失败
