### ISSUE TITLE
自定义组件引用 `taro-ui` 报错

### ISSUE THREAD

**Issue by nuintun** [NervJS/taro#1108]
**问题描述**
自定义组件引用 `taro-ui` 编译和监听后 `weapp` 报错

**复现步骤**
自定义组件

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 1.1.5
 - Node.js 11.10
 - 报错平台 weapp

**补充信息**
![_20181114102816](https://user-images.githubusercontent.com/1730277/48456058-8b504780-e7f8-11e8-84cc-6532763a9286.png)
![_20181114103226](https://user-images.githubusercontent.com/1730277/48456070-9b682700-e7f8-11e8-9fff-037b3987f29b.png)

**Comment by luckyadam** [comment]
taro-ui 安装的哪个版本

**Comment by nuintun** [comment]
@luckyadam 1.3.5, 1.4.0 都测试了，一样

**Comment by nuintun** [comment]
@luckyadam 现在报错调试非常不友好，建议开发阶段生成 map 便于调试。

**Comment by luckyadam** [comment]
我试了一下，没有复现啊，是咋引入的 taro-ui
编译时有没有报错

**Comment by nuintun** [comment]
@luckyadam 

```js
import { Component } from '@tarojs/taro';
import { View, Image } from '@tarojs/components';
import { AtIcon } from 'taro-ui';
```

在 `src/components` 自定义组件出的问题。

**Comment by luckyadam** [comment]
我试了一下，没有复现这种情况哦，你重新编一下试试，然后看看编译时有没有报错等信息
另外 cli 升级到 1.1.7 吧，1.1.5 有些问题

**Comment by nuintun** [comment]
@luckyadam 我先升级测试下~

**Comment by nuintun** [comment]
@luckyadam 还是报错，我整理个 DEMO 吧。

**Comment by luckyadam** [comment]
好的~

**Comment by nuintun** [comment]
@nuintun https://github.com/nuintun/taro

**Comment by luckyadam** [comment]
@nuintun 这是 taro cli 处理文件引用的一个问题，没有支持

```javascript
import { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';
export { default as ListItem } from './list-item';
```

这种写法

你暂时还是把  list 和 list-item 拆成两个独立的组件文件来进行引用吧

**Comment by nuintun** [comment]
@luckyadam 

```js
import { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';
import ListItem from './list-item';

export default class List extends Component {
  static ListItem = ListItem;

  render() {
    return <View className="list">{this.props.children}</View>;
  }
}
```
这种写法也不支持？

**Comment by nuintun** [comment]
@luckyadam 

```js
<View className="extraIcon">
  {arrow === 'down' && <AtIcon value="chevron-down" {...iconStyle} />}
  {arrow === 'up' && <AtIcon value="chevron-up" {...iconStyle} />}
  {arrow === 'right' && <AtIcon value="chevron-right" {...iconStyle} />}
</View>
```

这种 `...spread` 表达式也支持下吧！

**Comment by luckyadam** [comment]
@nuintun 

> @luckyadam
> 
> ```js
> import { Component } from '@tarojs/taro';
> import { View } from '@tarojs/components';
> import ListItem from './list-item';
> 
> export default class List extends Component {
>   static ListItem = ListItem;
> 
>   render() {
>     return <View className="list">{this.props.children}</View>;
>   }
> }
> ```
> 
> 这种写法也不支持？

这种写法不支持，你还是把他们拆成独立组件吧

**Comment by luckyadam** [comment]
> @luckyadam
> 
> ```js
> <View className="extraIcon">
>   {arrow === 'down' && <AtIcon value="chevron-down" {...iconStyle} />}
>   {arrow === 'up' && <AtIcon value="chevron-up" {...iconStyle} />}
>   {arrow === 'right' && <AtIcon value="chevron-right" {...iconStyle} />}
> </View>
> ```
> 
> 这种 `...spread` 表达式能不能也支持下，现在写组件简直要崩溃。。。

`...spread` 是因为小程序不支持，所以我们也无法支持

**Comment by yuche** [comment]
`...spread` 已支持
