### ISSUE TITLE
升级3.3.20后h5自定义路由失效

### ISSUE THREAD

**Issue by Phlen** [NervJS/taro#11086]
### 相关平台
H5

**浏览器版本: chrome 97**
**使用框架: React**

### 复现步骤
原项目在3.3.16版本下运行正常，升级到3.3.20后，h5自定义路由失效
配置demo:
router: {
      basename: '/',
      mode: 'hash',
      customRoutes: {
        "/pages/index/index": "/",
      }

taro init 新项目即可复现

### 期望结果
h5自定义路由正常

### 实际结果
h5自定义路由失效

### 环境信息
```
  Taro CLI 3.2.10 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.20 => 3.3.20
      @tarojs/components: 3.3.20 => 3.3.20
      @tarojs/mini-runner: 3.3.20 => 3.3.20
      @tarojs/react: 3.3.20 => 3.3.20
      @tarojs/runtime: 3.3.20 => 3.3.20
      @tarojs/taro: 3.3.20 => 3.3.20
      @tarojs/webpack-runner: 3.3.20 => 3.3.20
      babel-preset-taro: 3.3.20 => 3.3.20
      eslint-config-taro: 3.3.20 => 3.3.20
      react: ^17.0.0 => 17.0.2
```

**Comment by Phlen** [comment]
是首页的自定义路由失效，其他页面可以

**Comment by ZakaryCode** [comment]
自定义路由并非失效，而是首页在设定为 `/` 但并没有设置 `entryPagePath`，导致页面会自动跳转到设置路径的首页，可以通过在项目内添加该配置规避该问题。

> [参考文档](http://taro-docs.jd.com/taro/docs/next/app-config#entrypagepath)
