### ISSUE TITLE
自定义tabbar不生效

### ISSUE THREAD

**Issue by 491467928** [NervJS/taro#11088]
### 相关平台
微信小程序

**小程序基础库: 2.20.1**
**使用框架: Vue 3**

### 复现步骤
src目录下新建custom-tab-bar目录，下面新建index.vue和index.config.ts文件，index.vue里写好了UI和逻辑，app.config.ts里配置好tabBar属性，其中的custom属性设置为了true

### 期望结果
正常显示tabbar

### 实际结果
没有显示tabbar

### 环境信息
```
 Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
编译后的目录里查看custom-bar-tab目录下只有index.js，index.js.map，index.wxss，没有index.wxml文件

**Comment by 868618** [comment]
解决了吗我的也是这个问题

**Comment by 491467928** [comment]
> 解决了吗我的也是这个问题

没有，看来3.3.19还是不支持自定义tabbar

**Comment by Vinsurs** [comment]
刚试了下 ，确实没有wxml出来, 我用的taro版本3.4.0；react是一直支持的

**Comment by shenmengnana** [comment]
可以用原生的写法，copy进dist目录

**Comment by Chen-jj** [comment]
已修复
