### ISSUE TITLE
react native 平台支持 defineAppConfig 与 definePageConfig 编译宏

### ISSUE THREAD

**Issue by zhiqingchen** [NervJS/taro#11089]
### 这个特性解决了什么问题？

新增 defineAppConfig 与 definePageConfig 编译宏**

### 这个 API 长什么样？

> 再次感谢 [@b2nil](https://github.com/b2nil) 同学为 Taro 新增了此特性。 文档地址：[defineAppConfig](https://docs.taro.zone/docs/next/app-config#defineappconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)、[definePageConfig](https://docs.taro.zone/docs/next/page-config#definepageconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
> 

#### **defineAppConfig**

开发者可以使用 `defineAppConfig` 包裹 App 配置对象，以获得全局配置的**类型提示**和**自动补全**，如：

```tsx
// app.config.ts
export default defineAppConfig({
  pages: ['pages/index/index'],
  window: {
    navigationBarTitleText: 'WeChat'
  }
})
```

#### **definePageConfig**

使用 `definePageConfig` 包裹 Page 配置对象，同样可以获得页面配置的**类型提示**和**自动补全**，如：

```tsx
// page.config.ts
export default definePageConfig({
  navigationBarTitleText: '首页'
})
```

除此之外，**开发者可以不提供页面的配置文件，直接在页面逻辑文件中使用 `definePageConfig` 定义页面配置**。

如在 React 中：

```tsx
// page.tsx
definePageConfig({
  navigationBarTitleText: '首页'
})

export default function Index () {}
```

在 Vue 中：

```html
<script>
definePageConfig({
  navigationBarTitleText: '首页'
})

export default {}
</script>
```

**Comment by gezichenshan** [comment]
@zhiqingchen 想问一下， definePageConfig在.vue文件中报'defineAppConfig' is not defined.eslint[no-undef](https://eslint.org/docs/rules/no-undef)的问题怎么解决。

**Comment by JiaLe1** [comment]
// app.config.ts
export const text = '标题'

export default defineAppConfig({
  pages: ['pages/index/index'],
  window: {
    navigationBarTitleText: text
  }
})

index.ts
import { text } from './app.config.ts'

console.log(text);

// defineAppConfig is not defined

支持 app.config.ts 内变量定义， 不支持外部导入变量？

**Comment by doseeing** [comment]
> @zhiqingchen 想问一下， definePageConfig在.vue文件中报'defineAppConfig' is not defined.eslint[no-undef](https://eslint.org/docs/rules/no-undef)的问题怎么解决。

这一般是由于eslint没有找到defineAppConfig的定义造成的，可以在eslintrc中声明全局变量
```
{
    "globals": {
        "defineAppConfig": "readonly"
    }
}
```

参考：https://stackoverflow.com/questions/34820817/eslints-no-undef-rule-is-calling-my-use-of-underscore-an-undefined-variable
