### ISSUE TITLE
如果路由匹配到没有定义的路由，怎么能集中处理导向错误页面？

### ISSUE THREAD

**Issue by julianfox0119** [NervJS/taro#11098]
### 这个特性解决了什么问题？
目前没有找到这个配置只有走了正确的路由定义才能正确显示页面，如果路由不正确，就是白屏，这个怎么集中处理不在路由表里的路径呢？

### 这个 API 长什么样？
如果本身有这个功能请提供一个例子，谢谢。

**Comment by ZakaryCode** [comment]
[参考文档](http://taro-docs.jd.com/taro/docs/next/apis/base/weapp/app-event/onPageNotFound)
