### ISSUE TITLE
Taro.canvasToTempFilePath 报错！

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1109]
```
    const canvasId = this.context.canvasId;
    this.context.draw(false,
      setTimeout(() => {
        Taro.canvasToTempFilePath(
          {
            canvasId: canvasId,
            success: function (res) {
              console.log('success', canvasId, res.tempFilePath);
            },
            fail: function (res) {
              console.log('fail', canvasId, res);
            }
            , complete: function (res) {
              Taro.hideLoading();
            }
          },this.$scope);
      }, 200));
```
![image](https://user-images.githubusercontent.com/43346131/48456178-074a8f80-e7f9-11e8-9504-2f328150a5be.png)

os: mac 
"@tarojs/taro": "1.0.7",

**Comment by JoMartinezZhu** [comment]
![image](https://user-images.githubusercontent.com/43346131/48456871-90fb5c80-e7fb-11e8-9d2f-2601af871b0e.png)
使用了原生的就OK了！目前只测试了画一个canvas 生成一张图片！

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by luckyadam** [comment]
@JoMartinezZhu 哦哦，应该按照 issue 模板提 bug，这样清晰些
这是版本问题
升级到 1.1.6 就可以了

**Comment by JoMartinezZhu** [comment]
> @JoMartinezZhu 哦哦，应该按照 issue 模板提 bug，这样清晰些
> 这是版本问题
> 升级到 1.1.6 就可以了
我怎么又遇到版本问题了！大概 一个月前 也遇到版本问题，更新到了1.0.7！

**Comment by luckyadam** [comment]
嗯，有一些 bug 是不断迭代修复的嘛

**Comment by luckyadam** [comment]
升级到 1.1.7 ~ 1.1.6 发出去的包有问题
