### ISSUE TITLE
linaria转换错误

### ISSUE THREAD

**Issue by SidneyLann** [NervJS/taro#11103]
### 相关平台
微信小程序

**小程序基础库: 3.4.0**
**使用框架: React**

### 复现步骤
"linaria": "2.3.1", Picker组件转换后range属性为空数组[]， 不用linaria转换时数组不为空。

### 期望结果
"linaria": "2.3.1", Picker组件转换后range属性数组不为空。

### 实际结果
"linaria": "2.3.1", Picker组件转换后range属性为空数组[]

### 环境信息
```
 Taro v3.4.0


 Taro CLI 3.4.0 environment info:
   System:
     OS: Windows 7
   Binaries:
     Node: 13.12.0 - D:\DEV\nodejs\node.EXE
     Yarn: 1.22.17 - D:\DEV\nodejs\yarn.CMD
     npm: 6.14.4 - D:\DEV\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@SidneyLann 提供一下完整代码

**Comment by SidneyLann** [comment]
import React from 'react'
import { styled } from 'linaria/react'
import { Picker } from '@tarojs/components'

const Picker0 = styled( Picker ) < { cssWidth: string } > `
  width: ${props => props.cssWidth};
`

class SelectInput extends React.Component {
    onChange = ( event ) => {
        const idx = event.detail.value;
        const item = this.props.options[idx];
        this.props.onChange( item );
    }

    render() {
        const options = this.props.options;
        const itemKey = this.props.itemKey;
        const valueKey = this.props.valueKey;
        let index = 0;
        let optionLabel = '';
        if ( options.length > 0 ) {
            index = options.findIndex( item => item[valueKey] == this.props.value );
            if ( index >= 0 ) optionLabel = options[index][itemKey]
        }

        let cssWidth = this.props.cssWidth
        cssWidth ? cssWidth > 0 ? cssWidth = cssWidth + 'px' : cssWidth ='80%'' : cssWidth = '100%'

        return (
            <Picker0 cssWidth={cssWidth}
                range={options}
                rangeKey={itemKey}
                value={index}
                onChange={this.onChange}
                mode={this.props.mode}
                disabled={this.props.disabled}
            >
                {this.props.label} 
            </Picker0>
        )
    }
}

export default SelectInput

**Comment by SidneyLann** [comment]
上面的代码会导致range为[], 如果改为<Picker ...>……</Picker>, range就有值。

**Comment by SidneyLann** [comment]
上面的代码会导致range为[], 如果改为<Picker ...>……</Picker>, range就有值。
