### ISSUE TITLE
集成环信 SDK 的时候报错了

### ISSUE THREAD

**Issue by zeshaoaaa** [NervJS/taro#1110]
**问题描述**
我们需要环信IM SDK，但是[环信小程序](https://github.com/easemob/webim-weixin-xcx)可以运行的代码，导入到 taro 之后就不能正常运行了

**复现步骤**
[复现问题的步骤]
1. 打开[环信小程序](https://github.com/easemob/webim-weixin-xcx)
2. 复制 sdk 和 utils 目录到 [集成了环信sdk 的 taro 项目](https://github.com/zeshaoaaa/taro-easemob.git)
3. 运行 taro 项目

**期望行为**
正常运行

**报错信息**

![image](https://user-images.githubusercontent.com/13615002/48456806-54c7fc00-e7fb-11e8-899c-e17507462912.png)

**系统信息**

 - 操作系统: OS X
 - Taro 版本 1.1.5
 - Node.js 版本 10.11
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zhangxiaochunxy** [comment]
请问这个issue是被解决了吗？为什么关闭了？

**Comment by CPPAlien** [comment]
@zeshaoaaa 请问下啥解决办法？

**Comment by lk-chan** [comment]
> 
> 
> @zhangxiaochunxy 不知道呢，不过我找到了一个解决方案

请问下用什么办法解决的？我也遇到同样的问题，在taro引用环信im时报错_

**Comment by shenghanqin** [comment]
@zhangxiaochunxy 是不是模块加载不一致？微信接收的是CommonJS。
