### ISSUE TITLE
Taro v3 vue H5 Taro.navigateBack 返回页面栈不正确

### ISSUE THREAD

**Issue by caizhongren** [NervJS/taro#11112]
### 相关平台
H5

**浏览器版本: Chrome 97**
**使用框架: Vue 3**

### 复现步骤
eg: 三个页面 a->b->c->navigateBack  应该回到b页面的 现状回到a页面 但是b页面的dom结构还在  使用Taro.getCurrentPages获取到的页面栈是正确的 但是Taro.getCurrentInstance().router 不正确

### 期望结果
Taro.navigateBack()返回的页面栈和视图保持正确

### 实际结果
目前显示不正确

### 环境信息
```
👽 Taro v3.3.20


  Taro CLI 3.3.20 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.20 => 3.3.20 
      @tarojs/mini-runner: 3.3.20 => 3.3.20 
      @tarojs/runtime: 3.3.20 => 3.3.20 
      @tarojs/taro: ^3.3.20 => 3.3.20 
      @tarojs/webpack-runner: 3.3.20 => 3.3.20 
      babel-preset-taro: 3.3.14 => 3.3.14 
      eslint-config-taro: 3.3.20 => 3.3.20 

```

---
### 补充信息
与此bug效果一致 https://github.com/NervJS/taro/issues/10785

**Comment by ZakaryCode** [comment]
未检测到该问题，请确定cli和项目版本一致性。

**Comment by weishenlan** [comment]
我遇到相同的问题

**Comment by Zmingg** [comment]
相同问题，步骤：小程序页面a  -> webview -> 小程序页面b
navigateBack 后发现重新打开新的webview，且路由混乱
![WeChatWorkScreenshot_b1d3c165-a762-4523-a13e-154f516643db](https://user-images.githubusercontent.com/25217908/158765727-993c0dfa-69fd-4d21-a228-9eb20a4a8399.png)

**Comment by Zmingg** [comment]
相同问题
步骤： 小程序页面A navigrateTo-> webview  wx.miniProgram.navigateTo->  小程序页面B
然后 navigateBack，发现路由混乱，似乎是重新加载了webview，需要手动返回两次。
但执行navigateBack {detal: 2}却直接返回到页面A
![image](https://user-images.githubusercontent.com/25217908/158766038-1eef7ffd-9688-4903-94ee-6af24fcb3579.png)

**Comment by wenxiuYang** [comment]
相同问题 +1

**Comment by robinma** [comment]
从首页 
`Taro.redirectTo({
    url: "/pages/createcomp/index",
  });`

到createcomp/index页面后，不能正确返回

`Taro.navigateBack({
      delta: 1,
    });`

**Comment by robinma** [comment]
遇到不能返回问题，后来发现是我写错了。。

调用navigateTo后，才可以使用 navigateBack

**Comment by zouminhua-1** [comment]
遇到通用的问题，请问有解决方案吗
