### ISSUE TITLE
`@tarojs/components` 库 vue 框架 h5 组件的 `jsx` 支持及全局注册

### ISSUE THREAD

**Issue by b2nil** [NervJS/taro#11111]
### 这个特性解决了什么问题？
目前由于 `@tarojs/components` 库 vue 框架 h5 组件均采用注册全局组件的方式，给大多数使用模板语法的开发者使用，因此未将这些组件暴露出来供单独引用。虽然方便了大多数用户，但也导致了两个问题：
- 给使用 jsx 语法的开发者造成不便，因为要额外处理小程序和 h5 平台的差异，如 `view`, `taro-view` #10160
- 所有组件都注册成了全局组件，但有些组件并不一定会用到，造成冗余

### 这个 API 长什么样？
1. 针对 jsx 语法， 采用 react 框架 h5 组件的处理方式，全部导出暴露给开发者单独引用
2. 提供一个注册全局组件的用户选项，让开发者选择注册哪些组件，用户选项通过 `loader-meta` 注入， 类似于：
```ts
// taro-components/h5/vue3/index.js
export allGeneratedComponents
const allComponents = {...}
const registerGlobalComps = (userOptions: Record<string, any>) => {  
    for (const key in userOptions) {
      const component = allComponents[key]
      app.component(key, component)
    }
}

export function initVue3Components (app，userOpts) {
  // 默认全部注册
  registerGlobalComps(userOpts || allComponents)
}
```

**Comment by wenston** [comment]
请问用Taro写小程序（vue）支持自定义组件的全局注册吗？如果支持，应该怎么做？

**Comment by b2nil** [comment]
@wenston
自定义组件如果是 `vue` 语法写的，就采用  `vue` 语法，在 `app.ts/js` 入口文件中注册，具体语法可查阅 `vue` 文档。
如果是小程序原生语法写的，可在全局配置文件 `app.config.js/ts` 中通过 `usingComponents` 注册，具体可查阅各个小程序的文档或 `taro` 的文档。

**Comment by ZakaryCode** [comment]
> * 所有组件都注册成了全局组件，但有些组件并不一定会用到，造成冗余

所有组件都是懒加载的，实际不会对用户体验造成影响

当然可以参考小程序端实现 collectComponents 收集使用的组件，并自动注册对应平台

> 但是这会导致在应用加载时需要加载所有自定义组件，应当交由开发者自行选择
