### ISSUE TITLE
PickerView 新增 immediate-change 属性

### ISSUE THREAD

**Issue by idootop** [NervJS/taro#11129]
### 这个特性解决了什么问题？
微信小程序基础库 2.21.1 开始可以使 immediate-change 这个配置，解决 PickerView 选择延时回调的问题。
具体用法参考：https://developers.weixin.qq.com/miniprogram/dev/component/picker-view.html

### 这个 API 长什么样？
```typescript
interface PickerViewProps extends StandardProps {

  ...

  /** 是否在手指松开时立即触发 change 事件。若不开启则会在滚动动画结束后触发 change 事件。
   * @supported weapp
   * @default false
   */
  immediateChange?: boolean
}
```

**Comment by ZakaryCode** [comment]
可以直接用的 😂

**Comment by idootop** [comment]
> 可以直接用的 😂

我现在是用[@tarojs/plugin-inject](https://github.com/NervJS/taro-plugin-inject)给`PickerView`加上了`immediate-change`属性，然后在`global.d.ts`里手动声明了下`PickerViewProps`
