### ISSUE TITLE
swiper在H5端报错

### ISSUE THREAD

**Issue by foreverForCode** [NervJS/taro#11126]
### 相关平台
H5

### 复现仓库
[https://github.com/](https://github.com/)
**浏览器版本: 版本 97.0.4692.71**
**使用框架: React**

### 复现步骤
![图片](https://cdn0-next.banchengyun.com/1/miniprogram/img/d2bdca9a32787a743f471b6c9c2650c6e0206de7dongdong.png)

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
升级下版本
