### ISSUE TITLE
希望可以支持pnpm

### ISSUE THREAD

**Issue by haoziqaq** [NervJS/taro#11128]
### 这个特性解决了什么问题？
我是Varlet组件库的作者，最近计划开发Varlet Vue3 Taro版本，由于Varlet是一个pnpm的monorepo，目前也有很多库的作者都已经迁移到了pnpm，希望Taro团队可以对pnpm进行第一方支持

### 这个 API 长什么样？
pnpm monorepo项目可以正常运行

**Comment by haoziqaq** [comment]
这是我的仓库地址，希望可以得到支持
https://github.com/varletjs/varlet

**Comment by Chen-jj** [comment]
嗯嗯，我们有规划迁移 pnpm 的~大概会在 Q2 开始进行

**Comment by haoziqaq** [comment]
好的(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月18日(周二) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NervJS/taro] 希望可以支持pnpm (Issue #11128)




 
嗯嗯，我们有规划迁移 pnpm 的~大概会在 Q2 开始进行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AdvancedCat** [comment]
@haoziqaq  是被尤大点名表扬的 Varlet 吗 😀 赞！赞！

**Comment by haoziqaq** [comment]
@AdvancedCat 哈哈哈，别臊我啦，明年开年就打算开始做taro版本，到时候有疑惑估计还要来麻烦你们，不要嫌我们烦

**Comment by lamovv** [comment]
mark
关注pnpm支持进展

**Comment by Chen-jj** [comment]
3.5-beta 最新版已支持~
