### ISSUE TITLE
求助 组件props报错

### ISSUE THREAD

**Issue by mgsers** [NervJS/taro#1113]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

```js
// 父组件
<Gender gender="male"></Gender>

// 子组件
export default class Gender extends Component {
  constructor(props) {
    super(props)
  }

  selectGender(type) {
    console.log(type, this.props)
  }

  render() {
    const genderType = this.props.gender
    console.log(this.props)
    return (
      <Bubble>
        <Text>您的性别是？</Text>
        <View className="gender-select-box">
          <View className={`male ${genderType === 'male' ? 'selected' : ''}`} 
                onClick={ this.selectGender.bind(this, 'male') }>
            <Text className="gender-text">男</Text>
          </View>
          <View className={`female ${genderType === 'female' ? 'selected' : ''}`} 
                onClick={ this.selectGender.bind(this, 'female') }>
            <Text className="gender-text">女</Text>
          </View>
        </View>
      </Bubble>
    )
  }
}

```

**报错信息**

子组件取不到props值

![2018-11-14 11 39 48](https://user-images.githubusercontent.com/12532248/48458627-1da91900-e802-11e8-85a8-d1d5597854a7.png)

**系统信息**

 - 操作系统: [e.g. MacOS 10.14]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.9.3]
 - 报错平台 [小程序]

**Comment by mgsers** [comment]
#### 目前通过 defaultProps 解决了这个错误，但是 defaultProps 要强制性设置的吗？
![2018-11-14 12 39 23](https://user-images.githubusercontent.com/12532248/48460556-74b2ec00-e80a-11e8-816d-82fc0adf282b.png)

**Comment by nyrf** [comment]
参考 https://nervjs.github.io/taro/docs/best-practice.html#给组件设置-defaultprops 这里，

**Comment by mgsers** [comment]
@luckyadam 嗯，解决了，谢谢
