### ISSUE TITLE
引入小程序原生插件代码包报错

### ISSUE THREAD

**Issue by ZhuRuiHeng** [NervJS/taro#11136]
### 这个特性解决了什么问题？
解决物流显示问题，目前小程序提供了物流组件可以直接查询物流信息

### 这个 API 长什么样？
  在app.config.js引入就会报错
plugins: {
     "logisticsPlugin": {
     "version": "2.1.11",
       "provider": "wx9ad912bf20548d92"
     }
  },

报错信息
VM278:5 app.js错误:
 TypeError: Function.prototype.apply was called on WeakMap.prototype.get, which is a string and not a function

**Comment by Chen-jj** [comment]
@ZhuRuiHeng  问题反馈请使用对应的 Issue 模板并附上 Demo，信息不全，没有办法帮你

**Comment by Chen-jj** [comment]
@ZhuRuiHeng  问题反馈请使用对应的 Issue 模板并附上 Demo，信息不全，没有办法帮你

**Comment by ZhuRuiHeng** [comment]
已解决是qs版本的问题，使用"qs": "^5.0.0",版本解决了问题
