### ISSUE TITLE
无法动态更新__webpack_public_path__

### ISSUE THREAD

**Issue by easonzhuyi** [NervJS/taro#11145]
### 这个特性解决了什么问题？
这个功能可以解决产物在某种条件下优化cdn

### 这个 API 长什么样？
保持和webpack原生功能一致

`import Taro, { Component } from '@tarojs/taro';

__webpack_public_path__ = 'https://cdn.io/';

class App extends Component {
  config = {
    pages: preval`
      module.exports=(function() {
        if (process.env.TARO_ENV === 'h5') {
          return [
             'pages/home/index',
          ]
        }
      })()
    `,
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    },
    functionalPages: true,
    debug: true
  }

  componentDidShow() {
  }

  componentDidHide() { }

  componentDidCatchError() { }

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    console.log()
    return (
      <Index />
    )
  }
}

Taro.render(<App />, document.getElementById('app'))
`

**Comment by ZakaryCode** [comment]
具体打包的平台是？

**Comment by ZakaryCode** [comment]
h5 是可用的

**Comment by Chen-jj** [comment]
@easonzhuyi 小程序也没有问题。是因为你拼写错了吧。

```js
// app.jsx
import { Component } from 'react'

__webpack_public_path__ = 'https://cdn.io/'

class App extends Component {}
```

```jsx
// pages/index/index.jsx
import { Component } from 'react'
import { Image} from '@tarojs/components'
import city from './city.jpeg'

export default class Index extends Component {
  render () {
    return <Image src={city}></Image>
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/150680839-60049f3b-03b9-48b8-9721-f9c2d07395f5.png)

![image](https://user-images.githubusercontent.com/11807297/150680865-de19a9b1-2869-468a-b163-16bfcb8ba474.png)

![image](https://user-images.githubusercontent.com/11807297/150680933-7d2d5572-6f70-4149-8d1c-57fd24e992b2.png)
