### ISSUE TITLE
引入react-native模块的情况下编译小程序报错

### ISSUE THREAD

**Issue by beehoo** [NervJS/taro#11146]
### 相关平台
微信小程序

**小程序基础库: 2.20.0**
**使用框架: React**

### 复现步骤
目前的项目需要同时兼容小程序和react-native，所以代码里有地方import了react-native的模块。react-native运行没有问题，但编译成小程序就直接报错编译失败。相关的import语句注释掉又可以了。报错信息如下：

./node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

### 期望结果
在RN代码编译成小程序的时候可以不用特意去注释掉react-native相关的import语句

### 实际结果
引入react-native模块后无法编译成小程序运行，得手动注释掉相关import语句

### 环境信息
```
Taro CLI 3.3.20 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 8.1.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.20 => 3.3.20
      @tarojs/components: 3.3.20 => 3.3.20
      @tarojs/mini-runner: 3.3.20 => 3.3.20
      @tarojs/react: 3.3.20 => 3.3.20
      @tarojs/runtime: 3.3.20 => 3.3.20
      @tarojs/taro: 3.3.20 => 3.3.20
      @tarojs/webpack-runner: 3.3.20 => 3.3.20
      babel-preset-taro: 3.3.20 => 3.3.20
      eslint-config-taro: 3.3.20 => 3.3.20
      react: ^17.0.2 => 17.0.2
      react-native: ^0.66.0 => 0.66.4
    npmGlobalPackages:
      typescript: 2.2.1
```

**Comment by zhiqingchen** [comment]
这样是肯定会报错的。

跨平台开发，不同平台的差异部分，需要跨兼容的，建议使用

https://docs.taro.zone/docs/envs

提供的方法

**Comment by beehoo** [comment]
> 这样是肯定会报错的。
> 
> 跨平台开发，不同平台的差异部分，需要跨兼容的，建议使用
> 
> https://docs.taro.zone/docs/envs
> 
> 提供的方法

谢谢~已改成对应的地方判断加require了
