### ISSUE TITLE
使用typescript初始化项目出现问题

### ISSUE THREAD

**Issue by Eamonnzhang** [NervJS/taro#1116]
**问题描述**
按照taro-cli构建了基于typescript的项目，vscode打开项目之后提示一个类型检测错误

**复现步骤**
1. 利用taro-cli创建项目，选择typescript
2. 打开pages/index/index.tsx
3. vscode提示54行报错
报错代码：
```js
asyncAdd() {
      dispatch(asyncAdd() )//dispatch函数里的asyncAdd() 被标红
    }
```

**期望行为**
期望正常初始化项目后不报错

**报错信息**
```js
[ts]
类型“(dispatch: any) => void”的参数不能赋给类型“AnyAction”的参数。
  类型“(dispatch: any) => void”中缺少属性“type”。 [2345]
(alias) asyncAdd(): (dispatch: any) => void
import asyncAdd
```
![image](https://user-images.githubusercontent.com/9126544/48461757-391b2080-e810-11e8-84a6-8117b19e0484.png)

**系统信息**

 - 操作系统: MacOS 10.14.1
 - Taro 版本 v1.1.4
 - Node.js 版本 v8.9.4
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
暂时先改成
```typescript
dispatch(asyncAdd() as any)
```
