### ISSUE TITLE
新框架编译提示index.js错误

### ISSUE THREAD

**Issue by SangFall5** [NervJS/taro#1117]
**问题描述**
安装最新版taro 1.1.5时，npm run dev:weapp 时提示index.js:27出错

**报错信息**
![tim 20181114152657](https://user-images.githubusercontent.com/35206897/48466759-bf8c2e00-e821-11e8-93c2-b3df625d9208.png)

**Comment by nyrf** [comment]
https://github.com/NervJS/taro/issues/1114 修复了，不过没发新版

**Comment by luckyadam** [comment]
发布了 1.1.6

**Comment by gmars** [comment]
升级了taro -v还是1.1.5为啥

**Comment by SangFall5** [comment]
> 升级了taro -v还是1.1.5为啥

要升级taro

**Comment by SangFall5** [comment]
> 升级了taro -v还是1.1.5为啥

我是先
```taro update self
# npm
npm i -g @tarojs/cli@latest
```
后
```
npm install -g @tarojs/cli
```
就可以了

**Comment by SangFall5** [comment]
升级了1.1.6还是报一样的错
![tim 20181114160213](https://user-images.githubusercontent.com/35206897/48468397-acc82800-e826-11e8-9ad1-6304b183f7c6.png)

**Comment by cheese-git** [comment]
少了属性名 weapp

**Comment by SangFall5** [comment]
> 少了属性名 weapp
> 
> ![image](https://user-images.githubusercontent.com/11363971/48468688-8bb40700-e827-11e8-8bd7-68b75f8b1bb9.png)

加上属性名之后运行还是出错

![tim 20181114161027](https://user-images.githubusercontent.com/35206897/48468824-f49b7f00-e827-11e8-9e9b-422cda277cba.png)

**Comment by gmars** [comment]
weapp各种错误～～

**Comment by cheese-git** [comment]
嗯，1.1.5 版本加上 weapp 属性是能用的，1.1.6 的确实不行，原因我还在找 😂

**Comment by fjc0k** [comment]
打开 `package.json`，找到 `@tarojs/taro`，看它后面的版本，比如是 `^1.1.4`，那么

```bash
npm i @tarojs/cli@1.1.4 -D

# 或者

yarn add @tarojs/cli@1.1.4 -D
```

然后，就解决了。

**Comment by luckyadam** [comment]
抱歉，请升级到 1.1.7 解决了上述问题~

**Comment by cheese-git** [comment]
> 抱歉，请升级到 1.1.7 解决了上述问题~

火速试了一下，redux 模板还是不行 😂 不过加上 weapp 属性就好了 👍

**Comment by SangFall5** [comment]
> > 抱歉，请升级到 1.1.7 解决了上述问题~
> 
> 火速试了一下，redux 模板还是不行 😂 不过加上 weapp 属性就好了 👍

OK了  👍
