### ISSUE TITLE
Taro.chooseMedia（Taro3.4.0 支付宝、百度小程序此api不可用）

### ISSUE THREAD

**Issue by cncaihong** [NervJS/taro#11178]
### 相关平台
支付宝、百度小程序

**小程序基础库:  百度 3.400.5 ； 支付宝 2.7.6**
**使用框架: React**

### 复现步骤
1、页面元素绑定方法： `<Button  onClick={this.openAlbum}>从相册选择</Button>`
2、方法定义：

         openAlbum = () => {
            let bool = Taro.canIUse('chooseMedia');
            // 百度、支付宝小程序输出 false
            console.log('canIUse chooseMedia', bool);

            try {
                // Taro.chooseMedia 百度、支付宝小程序不支持
                Taro.chooseMedia({
                    count: 1,
                    mediaType: ['image'],
                    sourceType: ['album'],
                    sizeType: ['original'],
                    success: (res) => {
                        // {tempFiles: [{tempFilePath: '',size: '', fileType: 'image'}], type: 'image'}
                        console.log(res);
                    },
                    fail: (res) => {
                        console.log('Taro.chooseMedia fail message: ', res);
                   }
                });
            } catch(e) {
                console.log('error :', e);
            } 
        }

### 期望结果
微信、支付宝、百度小程序均可打开系统相册

### 实际结果
微信小程序可以正常打开相册，其他两个报错，信息如下：
error : TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_7___default.a.chooseMedia is not a function
at TaroElement.<anonymous> (photo_des.js:68)
    at TaroElement.dispatchEvent (taro.js:5051)
    at dispatch (taro.js:5533)
    at taro.js:5549
    at Object.ah [as unstable_batchedUpdates] (app.js:4159)
    at Hooks.batchedEventUpdates (taro.js:490)
    at u.eventHandler [as eh] (taro.js:5541)
    at e.value (index.js:1)
    at index.js:1
    at t.value (index.js:1)

### 环境信息
```
👽 Taro v3.4.0


  Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.0 => 3.4.0 
      @tarojs/mini-runner: 3.4.0 => 3.4.0 
      @tarojs/react: 3.4.0 => 3.4.0 
      @tarojs/runtime: 3.4.0 => 3.4.0 
      @tarojs/taro: 3.4.0 => 3.4.0 
      @tarojs/webpack-runner: 3.4.0 => 3.4.0 
      babel-preset-taro: 3.4.0 => 3.4.0 
      eslint-config-taro: 3.4.0 => 3.4.0 
      react: ^17.0.0 => 17.0.2
```

**Comment by Chen-jj** [comment]
@cncaihong 支付宝和百度没有 `chooseMedia` API。

支付宝有 `chooseImage` `chooseVideo`。

百度有 `chooseImage` `chooseAlbum` `chooseVideo`。
