### ISSUE TITLE
taro中引入uuid打包后安卓系统会报错“secure random number generation not supported by this browser”

### ISSUE THREAD

**Issue by ijuaner** [NervJS/taro#11177]
### 相关平台
字节跳动小程序

**小程序基础库: 2.37.0.0**
**使用框架: Vue 3**

### 复现步骤
项目中引入了uuid，打包后苹果系统没有问题，安卓系统会报错如下：secure random number generation not supported by this browser

### 期望结果
正常调用uuid.v4()

### 实际结果
调用uuid后报错“secure random number generation not supported by this browser”

### 环境信息
```
Taro v3.4.0


  Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.0 => 3.4.0 
      @tarojs/components: 3.4.0 => 3.4.0 
      @tarojs/mini-runner: 3.4.0 => 3.4.0 
      @tarojs/runtime: 3.4.0 => 3.4.0 
      @tarojs/taro: 3.4.0 => 3.4.0 
      @tarojs/webpack-runner: 3.4.0 => 3.4.0 
      babel-preset-taro: 3.4.0 => 3.4.0 
      eslint-config-taro: 3.4.0 => 3.4.0
```

**Comment by Chen-jj** [comment]
@ijuaner 和 Taro 无关。你需要 debug 一下 uuid 这个包，看里面用到了什么 Web 环境的东西，而它在字节小程序安卓逻辑层是不支持的从而导致此报错。

![image](https://user-images.githubusercontent.com/11807297/150681190-842d2ea8-2991-4fb1-ba8e-c6403b0e3ace.png)
