### ISSUE TITLE
使用鸿蒙插件@tarojs/plugin-platform-harmony打包到开发板，应用闪退白屏。

### ISSUE THREAD

**Issue by zihao114** [NervJS/taro#11172]
### 相关平台
快应用

### 复现仓库
[https://gitee.com/zihao_cc/taro-to-harmony.git](https://gitee.com/zihao_cc/taro-to-harmony.git)
**小程序基础库: api7**
**使用框架: React**

### 复现步骤
使用命令taro build --type harmony 打包成harmony项目代码。使用DevEco Studio创建openharmony项目。设置openharmony签名。打包成hap包。放入rk3568开发板sdcard中。

### 期望结果
页面正常展示

### 实际结果
白屏、应用闪退

### 环境信息
```
👽 Taro v3.5.0-canary.0


  Taro CLI 3.5.0-canary.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

**Comment by xuanzebin** [comment]
请升级 taro 到 4.0.0-beta.82 版本，并参考文档：https://docs.taro.zone/docs/next/harmony 进行最新的鸿蒙开发
