### ISSUE TITLE
swiper组件的circular属性在真机上表现和模拟器上不一致

### ISSUE THREAD

**Issue by EdivenH** [NervJS/taro#11188]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**小程序基础库: 2.21.3**
**使用框架: React**

### 复现步骤
模拟器

最后一个 swiper-item样式  `transform: translate(-100%, 0px) translateZ(0px);`

真机

最后一个swiper-item样式  `transform: translate(200%, 0px) translateZ(0px);`

### 期望结果
真机表现一致

### 实际结果
表现不一致

### 环境信息
```
👽 Taro v3.4.0


  Taro CLI 3.4.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@EdivenH 使用原生 Demo 先测试一下，区分是原生还是 Taro 的问题。
