### ISSUE TITLE
preact onShow onShareAppMessage onReachBottom等事件都不能触发

### ISSUE THREAD

**Issue by xiaof520** [NervJS/taro#11180]
### 相关平台
微信小程序

**小程序基础库: 2.21.3**
**使用框架: React**

### 复现步骤
function safeExecute(path, lifecycle, ...args) {
    const instance = instances.get(path);
    if (instance == null) {
        return;
    }
    
    const func = getHooks().getLifecycle(instance, lifecycle);
    console.log(func)
    if (isArray(func)) {
        const res = func.map(fn => fn.apply(instance, args));
        return res[0];
    }
    if (!isFunction(func)) {
       
        return;
    }
    return func.apply(instance, args);
}
定位到这 ，func 结果都是未定义

### 期望结果
能正常触发

### 实际结果
不能触发

### 环境信息
```
Taro v3.4.0


  Taro CLI 3.4.0 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/components: 3.4.0 => 3.4.0 
      @tarojs/mini-runner: 3.4.0 => 3.4.0 
      @tarojs/runtime: 3.4.0 => 3.4.0 
      @tarojs/taro: 3.4.0 => 3.4.0 
      @tarojs/webpack-runner: 3.4.0 => 3.4.0 
      babel-preset-taro: 3.4.0 => 3.4.0 
      eslint-config-taro: 3.4.0 => 3.4.0 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
```

---
### 补充信息
如果可以麻烦先告诉我修复方法

**Comment by puzzlephp** [comment]
react 正常

**Comment by Chen-jj** [comment]
@puzzlephp 没有复现

```js
export default class Index extends Component {
  componentDidShow () {
    console.log('show: ', )
  }
  onShareAppMessage () {
    console.log('onshare: ', )
    return {
      title: 'cjj'
    }
  }
  render () {
    return (
      <View>
        <Button>从相册选择</Button>
      </View>
    )
  }
}
```

```js
export default function Index () {
  useDidShow(() => console.log('show: ', ))
  useShareAppMessage(() => {
    console.log('share: ', )
    return {
      title: 'yb'
    }
  })
  return (
    <View>
      <Button>从相册选择</Button>
    </View>
  )
}
```

**Comment by puzzlephp** [comment]
抱歉，再试了一次， 使用react-redux  时才会出现， template  中react-redux 也不行，， @Chen-jj

**Comment by puzzlephp** [comment]
我试试改preact-redux

**Comment by puzzlephp** [comment]
页面组件使用 @connect会影响

**Comment by Chen-jj** [comment]
提供一下 demo

**Comment by xiaof520** [comment]
[https://github.com/NervJS/taro-project-templates/tree/master/redux](url) 初始化选preact 使用这个模板，使用react-redux的connect就会出现，页面不使用connect，就正常

**Comment by GZWZC** [comment]
是connect(HOC(component))吗？

**Comment by xiaof520** [comment]
connect(mapStateToProps)(component) ，react下是正常

**Comment by Chen-jj** [comment]
排查发现是因为 `PReact.memo` 与 `React.memo` 实现方式不一样而导致。
