### ISSUE TITLE
framework preact 模式下 video的control属性为false时无效，react模式正常

### ISSUE THREAD

**Issue by banbantx** [NervJS/taro#11197]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/banbantx/taro-preact/tree/master](https://github.com/banbantx/taro-preact/tree/master)
**小程序基础库: 2.20.0**
**使用框架: preact**

### 复现步骤
yarn dev:weapp
编译项目，在微信小程序打开即可复现。

### 期望结果
video 默认的控制菜单始终为隐藏状态

### 实际结果
默认始终显示 video 的controls

### 环境信息
```
👽 Taro v3.4.0


  Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.0 => 3.4.0 
      @tarojs/mini-runner: 3.4.0 => 3.4.0 
      @tarojs/runtime: 3.4.0 => 3.4.0 
      @tarojs/taro: 3.4.0 => 3.4.0 
      @tarojs/webpack-runner: 3.4.0 => 3.4.0 
      babel-preset-taro: 3.4.0 => 3.4.0 
      eslint-config-taro: 3.4.0 => 3.4.0 
```

**Comment by Chen-jj** [comment]
感谢反馈，原因是 PReact 对值为 `false` 的属性，会直接调用 `element.removeAttribute`：

https://github.com/preactjs/preact/blob/1b6fbc723020f66b74581e9eea067f74380eb1f9/src/diff/props.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L136-L143

因此需要想办法绕过此逻辑

**Comment by w88975** [comment]
@Chen-jj 
多久能把这些preact的bug发一个版呢, 目前是自己fork的分支改的, 但还是希望能跟着官方版本走
小程序那块体积超出了, 切换到preact省了不少打包大小
谢谢大佬
