### ISSUE TITLE
[feature] 建议支持 render props

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#1119]
建议支持 render props 写法

**Comment by youngluo** [comment]
@yuche 能否支持这种写法？

```
this.props.children(state)
```

**Comment by yuche** [comment]
不能，children 和未来其它的 render props 都是不可操作的，他们都是 slot 的 alias

**Comment by youngluo** [comment]
不能通过组件传递数据吗？比如这种
```
<Comp renderChildren={ (state) => <View /> }  />
```

**Comment by yuche** [comment]
如果 render props 是一个函数那么就可能在里面定义语句和使用复杂表达式，函数本身也有自己的作用域。这个特性只有我们支持了 render 函数之外定义 JSX 才能会考虑去实现。例如：

```jsx
renderHeader = (user) => {
  const title = `Welcome, ${user}!`
  return <Header title={title} />
}

render () {
 return this.renderHeader('Wallace!')
}
```

我们大概会规划在 1.3.0（1.2.0 是原生小程序转 Taro），因为基于作用域的转换是对目前现有转换方式的重构，当我们写了足够的测试用例，确保不会影响目前已有的功能才会上线此特性。如果没有紧急或特别的需求下个月某个时候应该能支持到。

**Comment by youngluo** [comment]
@yuche 感谢

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/6ac53b29665c797a6342db931906de4523a04010
