### ISSUE TITLE
Taro3 用RN创建的工程 无法编译到H5、微信等其他平台

### ISSUE THREAD

**Issue by WhiteSean** [NervJS/taro#11193]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
yarn dev:h5

### 期望结果
通过编译

### 实际结果
编译报错：
启动  开发者工具-项目目录  /Users/sean/miniapp/cross-platform/taro-3-demo/dist

编译  发现入口  src/app.ts
编译  发现页面  src/pages/index/index.tsx
编译  发现页面  src/pages/demo/index.tsx
🙅   编译失败. 2022-1-25 2:03:54 ├F10: PM┤

./node_modules/react-native/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/sean/miniapp/cross-platform/taro-3-demo/node_modules/react-native/index.js: Unexpected token, expected "{" (14:7)

  12 |
  13 | // Components
> 14 | import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
     |        ^
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
  17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';

### 环境信息
```

  Taro CLI 3.3.19 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.15.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.19 => 3.3.19 
      @tarojs/components: 3.3.19 => 3.3.19 
      @tarojs/mini-runner: 3.3.19 => 3.3.19 
      @tarojs/react: 3.3.19 => 3.3.19 
      @tarojs/runtime: 3.3.19 => 3.3.19 
      @tarojs/taro: 3.3.19 => 3.3.19 
      @tarojs/webpack-runner: 3.3.19 => 3.3.19 
      babel-preset-taro: 3.3.19 => 3.3.19 
      eslint-config-taro: 3.3.19 => 3.3.19 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.66.0 => 0.66.4 
    npmGlobalPackages:
      typescript: 4.1.3

```

**Comment by ZakaryCode** [comment]
引用的 RN 组件需要通过多端代码排除掉。

> https://nervjs.github.io/taro/docs/envs

**Comment by ZakaryCode** [comment]
验证了下 RN 模板并没有问题，可以检查是否引入了 RN 专属的模板，通过多端代码判断一下。

> 参考文档: https://nervjs.github.io/taro/docs/envs

**Comment by WhiteSean** [comment]
> 验证了下 RN 模板并没有问题，可以检查是否引入了 RN 专属的模板，通过多端代码判断一下。
> 
> > 参考文档: https://nervjs.github.io/taro/docs/envs

昨天taro init 重新选择rn模板 把之前的流程又重新执行了一遍，没问题，各端都能编译，但是两周前创建的模板就是有问题。猜测模板工程代码有更新吧

**Comment by ZakaryCode** [comment]
> > 验证了下 RN 模板并没有问题，可以检查是否引入了 RN 专属的模板，通过多端代码判断一下。
> > > 参考文档: https://nervjs.github.io/taro/docs/envs
> 
> 昨天taro init 重新选择rn模板 把之前的流程又重新执行了一遍，没问题，各端都能编译，但是两周前创建的模板就是有问题。猜测模板工程代码有更新吧

没有，看报错并不是模板的代码导致的
