### ISSUE TITLE
react && redux devtools support

### ISSUE THREAD

**Issue by jincan39** [NervJS/taro#112]
跑了下 [sample](https://github.com/NervJS/taro-redux-sample),redux和react浏览器插件未能正常使用 是跟nerv-devtools不兼容么？

**Comment by yuche** [comment]
看了一下这个 sample 没有引入 `nerv-devtools`，也没有在 redux 加上 `redux-devtools` 的中间件。按照相关文档看一下并引入应该都可以支持。
