### ISSUE TITLE
eslint-plugin-taro 版本没有更新到3.4.1

### ISSUE THREAD

**Issue by bobsam** [NervJS/taro#11201]
### 相关平台
微信小程序

**小程序基础库: 无**
**使用框架: React**

### 复现步骤
将所有的taro相关的依赖包更新到3.4.1，即可出现错误

### 期望结果
期望结果是 eslint-plugin-taro 是可升级到3.4.1版本

### 实际结果
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-taro@3.4.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bob/.npm/_logs/2022-01-26T02_58_48_901Z-debug-0.log

### 环境信息
```
  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.8.3
```

**Comment by konka-king** [comment]
https://docs.taro.zone/docs/migration#eslint-%E5%92%8C%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

官方文档说是已经废弃了？

我用的是。eslint-config-taro  3.4.1

**Comment by Chen-jj** [comment]
废弃了，这是 Taro 1，2 用的，那时对语法有各种限制。现在 Taro 3 模板项目使用的只有 `eslint-config-taro` 这个 preset。里面是各种常用 preset 的集合而已。
