### ISSUE TITLE
修改moduleName后无法通过Taro Playground调试app

### ISSUE THREAD

**Issue by beehoo** [NervJS/taro#11205]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
我在config/index.js里修改了rn配置里的appName，也根据文档修改了对应的ios和android文件。目前在ios和android模拟器上都可以正常运行，但是通过taro playground扫码无法运行app。请问是否还有对应的文件需要修改？

报错信息：

Invariant Violation: "taroDemo" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

### 期望结果
在taro playground上可以正常运行

### 实际结果
报错无法运行

### 环境信息
```
Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 8.1.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1
      @tarojs/components: 3.4.1 => 3.4.1
      @tarojs/mini-runner: 3.4.1 => 3.4.1
      @tarojs/react: 3.4.1 => 3.4.1
      @tarojs/runtime: 3.4.1 => 3.4.1
      @tarojs/taro: 3.4.1 => 3.4.1
      @tarojs/webpack-runner: 3.4.1 => 3.4.1
      babel-preset-taro: 3.4.1 => 3.4.1
      eslint-config-taro: 3.4.1 => 3.4.1
      react: ^17.0.2 => 17.0.2
      react-native: ^0.66.0 => 0.66.4
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2
    npmGlobalPackages:
      typescript: 2.2.1
```

**Comment by zhiqingchen** [comment]
是的，Playground默认调试的是 taroDemo。修改后无法调试。

**Comment by zhiqingchen** [comment]
Playground还未支持修改appname的功能。

**Comment by zhiqingchen** [comment]
Playground 完全开源，也可修改后编译自己的Playground。

**Comment by beehoo** [comment]
> Playground 完全开源，也可修改后编译自己的Playground。

明白了，谢谢~

**Comment by drizzlesconsin** [comment]
https://github.com/NervJS/taro-project-templates/blob/908346f07c6bea3df45e89e7e61715589ea91623/react-native/config/index.js#L68

将 `config/index.js` 的 `rn.appName` 改成 `taroDemo` 可解决。

**Comment by jsonchou** [comment]
taro playground 根本就跑不起来。

**通过xCode真机可以运行成功。**

``` js
<key>CFBundleDisplayName</key>
<string>myApp</string>

editTemplate.js
const DEFAULT_RN_PROJECT_NAME = 'myApp';

editTemplate.ts
const DEFAULT_RN_PROJECT_NAME = 'myApp'

projectName: "myApp",

rn: {
    appName: "myApp",
}

AppDelegate.m
moduleName:@"myApp"

MainActivity.java
return "myApp";
```

修改之后，仍旧报这个错误。

非常怀疑，这个项目，在初始化init上，都无法运行成功。

https://nervjs.github.io/taro-docs/docs/react-native/#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-appname

文档里面写的，是说，不能自定义，只能**taroDemo**？

**Comment by jsonchou** [comment]
BUNDLE  ./index

 LOG  Running "taroDemo" with {"rootTag":11,"initialProps":{}}
 ERROR  Invariant Violation: "taroDemo" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.


整个工程，根本就没有taroDemo，这个单词，还是报错。
