### ISSUE TITLE
H5编译后页面报错 Uncaught Error: React Refresh runtime should not be included in the production bundle.

### ISSUE THREAD

**Issue by ablikim915** [NervJS/taro#11203]
### 相关平台
H5

**浏览器版本: 97.0.4692.71（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
此项目本来是只编译微信小程序用的，目前有新需求，需要h5版本的，所以。步骤：
1.yarn dev:h5
2.本地服务启动成功
3.页面空白，控制台报标题上的错误

### 期望结果
h5版本能正常跑起来

### 实际结果
页面空白，控制台报错；

### 环境信息
```
👽 Taro v3.2.8

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by ZakaryCode** [comment]
未能复现到该问题，可以提供最低复现示例用于排查，或者尝试升级项目解决问题

**Comment by ablikim915** [comment]
> 未能复现到该问题，可以提供最低复现示例用于排查，或者尝试升级项目解决问题

这是公司的项目，不方便提供代码。
目前发现`react-refresh `这个依赖包报错，里面没有代码。
![image](https://user-images.githubusercontent.com/15664144/151127311-b59a9b6b-fe8a-46d9-b945-260332b37888.png)

我刚`react-refresh-runtime.development.js`中的代码拷贝到`react-refresh-runtime.production.min.js`文件中，还把顶部的判断修改成这样就不报错了。
```jsx
if (process.env.NODE_ENV === "production") {}
```
> 目前版本号也升级到最新的`3.4.1`了，还是一样报错。

**Comment by ablikim915** [comment]
我跑的是 `yarn dev:h5` 这个指令，结果 `react-refresh` 依赖包拿到的 `NODE_ENV` 是 `production` 。

![image](https://user-images.githubusercontent.com/15664144/151141370-c7c8eb39-98c2-40eb-82c8-7f7cbe700931.png)

我在指令中改 `NODE_ENV`和 `mode` 都无效。`yarn dev:h5` 指令中你们又跑了 `npm run build:h5`，这个指令可能在cli源码里，强设置`NODE_ENV`值为 `production`。

![image](https://user-images.githubusercontent.com/15664144/151141967-b3cd675c-4233-453d-a907-c29e6a4d5160.png)

**Comment by ZakaryCode** [comment]
由于没有具体项目对照来看，只能猜测应该是 babel 配置的问题导致的，可以检测相关配置，找一个空项目对照看一看

**Comment by ZakaryCode** [comment]
如果没有进一步信息，过几天会关掉这个问题

**Comment by ablikim915** [comment]
> 

我的babel配置是这样的，没有额外的配置项
![image](https://user-images.githubusercontent.com/15664144/151298388-0386d396-a4ff-4fef-ac7f-fadcf5801684.png)


> 如果没有进一步信息，过几天会关掉这个问题

好的 我再搭建个新项目对比看一下吧

**Comment by ablikim915** [comment]
现在好了。
刚创建了新项目，跑起来没问题，然后自己项目中的src目录和其他配置文件，一个个迁到新项目中，最后所有文件都一样也能跑得起来，然后回到自己项目中，删除node_modules，清除yarn缓存，重新安装依赖包后也能跑起来了。
> 其实昨天我也试过同样的方法，删依赖、清缓存、重装依赖，不知道为什么今天就好了，也没有改过什么配置。

麻烦大佬了 @ZakaryCode

**Comment by ZakaryCode** [comment]
听起来应该是lock导致的版本错误问题😂

**Comment by ablikim915** [comment]
咳～ 这问题又出现了，现在taro版本为3.4.1，node_modules和yarn.lock文件都删了，清除yarn缓存，所有依赖包重新下载还是不行。只是本地服务出现这种情况，build出来后的包用live-serve打开没问题。 @ZakaryCode 大佬再帮忙看一下可以吗。

**Comment by ablikim915** [comment]
#8926

**Comment by ablikim915** [comment]
修好了,
`"dev:h5": "npm run build:h5 -- --watch --mode development"`
这指令后面加了 `--mode development`

**Comment by ZhengKehang** [comment]
我还是有问题

**Comment by coder-layne** [comment]
我遇到类似的问题，发现是将生成配置文件 `config/dev.js` 中的 `env.NODE_ENV` 字段删除了，增加配置后恢复正常
```
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  mini: {},
  h5: {}
}
```
