### ISSUE TITLE
微信小程序平台编译失败

### ISSUE THREAD

**Issue by Alexerx** [NervJS/taro#1120]
**问题描述**
微信小程序编译不成功

**复现步骤**
npm run dev:weapp

**期望行为**
正常编译

**报错信息**

![adsf](https://user-images.githubusercontent.com/22076610/48468981-67a4f580-e828-11e8-8681-77363382828c.png)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.1.6
 - Node.js 版本 v10.13.0
 - 报错平台 weapp

**Comment by gatinul** [comment]
操作系统：macOs10.13.6
taro版本：v1.1.6
node版本：8.10.0
同样编译小程序同样报错

**Comment by luckyadam** [comment]
升级到 1.1.7 ~ 1.1.6 发出去的包有问题

**Comment by xpal7512** [comment]
同样的问题，升级到1.1.7后解决了。

**Comment by gatinul** [comment]
> 升级到 1.1.7 ~ 1.1.6 发出去的包有问题

1.1.7版本的redux模板脚手架 貌似有问题 下载后 直接执行 `npm run dev:weapp` 报错如下：

👽 Taro v1.1.7

/Applications/workspace/taro/HAuser/config/index.js:27
  {
  ^
