### ISSUE TITLE
ios原生输入法，输入拼音时，如果页面state有更新，拼音会被重置掉。

### ISSUE THREAD

**Issue by h025** [NervJS/taro#11208]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/h025/taro-issue](https://github.com/h025/taro-issue)
**小程序基础库: 2.22.0**
**使用框架: React**

### 复现步骤
```javascript
import { Component } from 'react'
import { View, Input } from '@tarojs/components'

const inputStyle = `
  box-sizing: border-box;
  width: 80vw;
  height: 40px;
  border: 1px solid #000;
  padding: 5px 10px;
  margin-top: 15px;
  margin-left: 10vw;
`;

const countStyle = `
  margin-top: 30px;
  text-align: center;
`;

export default class Index extends Component {

  state = {
    value: '',
    count: 0
  }

  componentDidMount () {
    setInterval(() => {
      this.setState({
        count: this.state.count + 1
      })
    }, 1000)
  }

  onInput = (e) => {
    this.setState({
      value: e.detail.value
    })
  }

  render () {
    return (
      <View>
        <View style={countStyle}>{this.state.count}</View>
        <Input
          style={inputStyle}
          value={this.state.value}
          onInput={this.onInput}
         />
      </View>
    )
  }
}

```

### 期望结果
ios原生输入法能正常输入汉字

### 实际结果
使用拼音输入法时，拼音总是被重置

### 环境信息
```
Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.2 - D:\Program\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - D:\Program\nodejs\npm.CMD
```

**Comment by AdvancedCat** [comment]
React中，Input会编译为FC(函数组件)，会在每次setState后重新渲染，而value值在小程序文档中是初始值的定义，所以输入的值会被重置。
解决办法就是避免Input的重新渲染，比如 React.memo 或 useMemo：
```js
const MyInput = React.memo(function MyInput({style, value, onInput}) {
  return (
    <Input
      style={style}
      value={value}
      onInput={onInput}
    />
  )
})

// 调用
<MyInput
      style={inputStyle}
      value={this.state.value}
      onInput={this.onInput}
/>
```
希望能帮到你！

**Comment by h025** [comment]
> React中，Input会编译为FC(函数组件)，会在每次setState后重新渲染，而value值在小程序文档中是初始值的定义，所以输入的值会被重置。 解决办法就是避免Input的重新渲染，比如 React.memo 或 useMemo：
> 
> ```js
> const MyInput = React.memo(function MyInput({style, value, onInput}) {
>   return (
>     <Input
>       style={style}
>       value={value}
>       onInput={onInput}
>     />
>   )
> })
> 
> // 调用
> <MyInput
>       style={inputStyle}
>       value={this.state.value}
>       onInput={this.onInput}
> />
> ```
> 
> 希望能帮到你！

感谢回复！目前已确实使用react.memo方法解决了问题！
同时，这个问题只是出现在ios原生输入法中，安卓或者Iios第三方输入法都没有问题！我试了小程序原生开发里，也不会有这个问题，所以想知道taro官方是否有更好的，能从根本上解决这个问题 (感谢taro团队)！
毕竟react.memo react官方特意表明这只是优化方式，不要用来试图阻止组件渲染！

**Comment by AdvancedCat** [comment]
ios原生输入法会在input输入框内呈现你的输入过程，而第三方输入法一般是在键盘顶部先呈现输入过程，然后确认后一次性呈现到input框中；你可以多试几个输入法，目前看只要是在input框内呈现输入过程的都会有问题。
同理在微信开发者工具中，使用第三方输入法一样是有问题的。

这个问题的原因还是input被重新渲染了，导致输入候选内容丢失。

**Comment by imwangming** [comment]
将Input在单独封装成一个组件，对应的state也写在那里

**Comment by h025** [comment]
> 将Input在单独封装成一个组件，对应的state也写在那里

写demo时候确实可以简单的加封一个组件解决，但实际业务里，input会处于比较深的组件内，当父组件被更新input也会被迫一块更新，所以还是需要React.memo实时判断props 阻止重新渲染！

**Comment by axetroy** [comment]
> React中，Input会编译为FC(函数组件)，会在每次setState后重新渲染，而value值在小程序文档中是初始值的定义，所以输入的值会被重置。 解决办法就是避免Input的重新渲染，比如 React.memo 或 useMemo：
> 
> ```js
> const MyInput = React.memo(function MyInput({style, value, onInput}) {
>   return (
>     <Input
>       style={style}
>       value={value}
>       onInput={onInput}
>     />
>   )
> })
> 
> // 调用
> <MyInput
>       style={inputStyle}
>       value={this.state.value}
>       onInput={this.onInput}
> />
> ```
> 
> 希望能帮到你！

试了，函数组件下并不管用，已经确保不会再次渲染（函数组件没有被再次执行），依旧出现问题

**Comment by zhengtan2003** [comment]
> Reference
没想到这个问题能这么久

**Comment by zhengtan2003** [comment]
没想到这个问题能这么久，还好不写小程序了
