### ISSUE TITLE
H5开启下拉刷新后页面无法向上滚动

### ISSUE THREAD

**Issue by soakit** [NervJS/taro#11206]
### 相关平台
H5

### 复现仓库
[https://github.com/soakit/taro-demo/tree/fix-pullrefresh3.4.1](https://github.com/soakit/taro-demo/tree/fix-pullrefresh3.4.1)
**浏览器版本: Chrome/Safari latest**
**使用框架: React**

### 复现步骤
打开h5页面，向下滚动
此时无法向上滚动，chrome模拟是正常的，真机上无法滑动

### 期望结果
正常滑动

### 实际结果
向下滑动后无法再向上滑动

### 环境信息
```
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.4.4
```

---
### 补充信息
造成此原因就是因为这个[code](https://github.com/NervJS/taro/blob/054e4db574a5b52b3771e6798b5f1815c8200523/packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx#L60)写死的。
用这个来判定是否在顶部(scrollTop是否为0)。

**Comment by bobsam** [comment]
Similar problem #11144

**Comment by ZakaryCode** [comment]
> Similar problem #11144

这并不是同一个问题， #11144 大概率是由于 cli 和组件库版本不一致导致的，需要 demo 才能进一步确定信息。

**Comment by Youngwellcool** [comment]
还是会有问题，.taro_router与.rmc-pull-to-refresh-content-wrapper设置了min-height=100vh，在某些浏览器的可用高度不等于100vh的情况，比如企业微信和safari浏览器，设置100vh，分别为724px，716px，但是他们的真实可用高度分别为690px，635px，于是，页面就会出现滚动条，下拉后，页面会就无法向上滚动了

**Comment by Youngwellcool** [comment]
.taro_router与.rmc-pull-to-refresh-content-wrapper的min-height是不是应该设置为Taro.getSystemInfoSync().windowHeight呢？
