### ISSUE TITLE
react-native模板下启动ios有困难

### ISSUE THREAD

**Issue by wcxz520** [NervJS/taro#11209]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
taro init选择react-native模板

情况1：
yarn build:rn --platform ios

error Could not find "Podfile.lock". Did you run "pod install" in iOS directory?

情况2：
yarn upgradePeerdeps

[!] Invalid `Podfile` file: 767: unexpected token at ''.

情况3：
cd ios

pod install

[!] Invalid `Podfile` file: 767: unexpected token at ''.

### 期望结果
不报错，最终执行yarn ios能出现模拟器。

### 实际结果
依赖报错

### 环境信息
```
❯ taro info                   
Debugger listening on ws://127.0.0.1:50802/c97e7499-b255-4049-9113-db81dd13e023
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1 
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.66.0 => 0.66.4
```

**Comment by zhiqingchen** [comment]
是不是改动过podfile了，贴一下podfile内容

**Comment by wcxz520** [comment]
> 

好的~

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'taroDemo' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

**Comment by wcxz520** [comment]
> 是不是改动过podfile了，贴一下podfile内容

好的~

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'taroDemo' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

**Comment by wcxz520** [comment]
> 是不是改动过podfile了，贴一下podfile内容

**Comment by zhiqingchen** [comment]
使用 3.4.1 进行 react-native 模板初始化，未发现异常。

可参考文章检查问题：
https://docs.taro.zone/blog/2021-10-14-Taro-React-Native-update#react-native-%E5%BC%80%E5%8F%91%E6%A8%A1%E6%9D%BF

或先尝试仅初始化RN环境，看看自身开发环境是否有异常
https://reactnative.dev/docs/0.66/environment-setup

**Comment by wcxz520** [comment]
> 



> 使用 3.4.1 进行 react-native 模板初始化，未发现异常。
> 
> 可参考文章检查问题： https://docs.taro.zone/blog/2021-10-14-Taro-React-Native-update#react-native-%E5%BC%80%E5%8F%91%E6%A8%A1%E6%9D%BF
> 
> 或先尝试仅初始化RN环境，看看自身开发环境是否有异常 https://reactnative.dev/docs/0.66/environment-setup

![image](https://user-images.githubusercontent.com/52689177/151515664-68e07317-1123-4e5b-9a31-dc1783fbda84.png)

好的，我看看

还是想请问下，你是和我一样的模板嘛？
"templateInfo": {
    "name": "react-native",
    "typescript": true,
    "css": "sass"
  },

 ios里面有没有podfile.lock这个文件有没有关系的？ 我也无法pod install...

**Comment by zhiqingchen** [comment]
一样的，

`yarn upgradePeerdeps`

会执行 pod install 生成 podfile.lock 的

**Comment by wcxz520** [comment]
> 一样的，
> 
> `yarn upgradePeerdeps`
> 
> 会执行 pod install 生成 podfile.lock 的

好吧，我就是想执行这个生成文件，可惜我`yarn upgradePeerdeps`到最后pod install就会报` [!] Invalid Podfile file: 767: unexpected token at ''.`
第一次开发rn，没安全感~ 那我就只能看看环境问题了。
谢谢~
