### ISSUE TITLE
小程序调用第三方库编译报错Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by carltian** [NervJS/taro#11213]
### 相关平台
支付宝小程序

**小程序基础库: 2.7.2**
**使用框架: React**

### 复现步骤
执行yarn dev:alipay 就报错

### 期望结果
正常使用三方库

### 实际结果
🙅   编译失败. 2022/1/27 上午10:39:12

./node_modules/@gistack/fantasy-core/react/features/Modal.ts 11:7
Module parse failed: Unexpected token (11:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| } from '../../react';
| 
> export interface ModalPropsType {
|     // eslint-disable-next-line @typescript-eslint/no-explicit-any
|     [index: string]: any;

监听文件修改中...

./node_modules/@gistack/fantasy-core/react/features/Modal.ts 11:7
Module parse failed: Unexpected token (11:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| } from '../../react';
| 
> export interface ModalPropsType {
|     // eslint-disable-next-line @typescript-eslint/no-explicit-any
|     [index: string]: any;
 @ ./src/sample/features/modal/ModalFeature.ts 9:0-63 26:22-27
 @ ./src/sample/config/redux.ts
 @ ./node_modules/babel-loader/lib!./src/app.tsx
 @ ./src/app.tsx,./node_modules/@gistack/fantasy-core/react/index.ts 2:7
Module parse failed: Unexpected token (2:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export * from '../core';
> export type { FtsWidgetsType, FtsComponentPropsType } from './core/types';
| 
| export { default as Routes } from './classes/Routes';
 @ ./src/sample/config/redux.ts 2:0-61 8:13-27
 @ ./node_modules/babel-loader/lib!./src/app.tsx
 @ ./src/app.tsx

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 环境信息
```
  Taro CLI 3.3.18 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1 
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.5.2
```

---
### 补充信息
使用taro-ui模板生成的

**Comment by Chen-jj** [comment]
看着像是这个包有些 TS语法，配置一下 babel-loader 去处理一下试试吧：https://docs.taro.zone/docs/config-detail#minicompileinclude

**Comment by kunkuntang** [comment]
请问h5有这个 compile.include 吗？
