### ISSUE TITLE
自动导入 .env 中的环境变量

### ISSUE THREAD

**Issue by arniu** [NervJS/taro#11219]
### 这个特性解决了什么问题？
目前注入环境变量要么动手写，要么在代码中写死，不很方便。

### 这个 API 长什么样？
参考 [create-react-app](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env) 的做法，自动导入 `TARO_` 开头的环境变量。

**Comment by xlcodes** [comment]
同问，希望可以支持.env环境变量自动注入

**Comment by bigmeow** [comment]
这个做成插件倒是简单，我有写插件： https://github.com/bigmeow/taro-plugin-environment#readme
但是插件的读取时机还是太晚了， 读取后的值只能在src代码里、以及其他taro插件里使用， 因为它本身作为一个插件，在插件被被加载执行时才开始读区。
希望是先读取.env  ==> 然后插件加载
这样读取的环境变量我随时可以在 config/index.js 里通过 process.env.xxx  直接使用

taro 的同学有建议吗

**Comment by heng1025** [comment]
可以使用 [dotenv](https://www.npmjs.com/package/dotenv)

**Comment by SilentFlute** [comment]
#9838

**Comment by SilentFlute** [comment]
可以参考这个`issue`: #9838

**Comment by ZakaryCode** [comment]
fix in #12840
