### ISSUE TITLE
微信小程序的 button 现在还没有 bindchooseavatar 事件的监听

### ISSUE THREAD

**Issue by heimeiyaodagongzai** [NervJS/taro#11228]
### 这个特性解决了什么问题？
能通过 button 的 openType="chooseAvatar"  来选择头像

### 这个 API 长什么样？
button 编译出来有 bindchooseavatar 的事件监听

**Comment by konka-king** [comment]
@Chen-jj  大佬 帮忙看下

https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=116405874355UHBf&version=&lang=zh_CN&token=

https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/userProfile.html
