### ISSUE TITLE
request的onHeadersReceived is not a function

### ISSUE THREAD

**Issue by YTGhost** [NervJS/taro#11224]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/YTGhost/taro-onHeadersReceived](https://github.com/YTGhost/taro-onHeadersReceived)
**小程序基础库: 2.22.0**
**使用框架: Vue 2**

### 复现步骤
微信开发者工具打开重现链接中的项目后，即可在控制台看到报错

### 期望结果
onHeadersReceived能被正常回调

### 实际结果
_tarojs_taro__WEBPACK_IMPORTED_MODULE_5___default.a.request(...).onHeadersReceived is not a function

### 环境信息
```
Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - D:\nodejs\yarn.CMD
      npm: 6.14.13 - D:\nodejs\npm.CMD
```

**Comment by AdvancedCat** [comment]
Taro封装了request api，返回的是promise对象，非RequestTask对象。
