### ISSUE TITLE
项目初始化运行报错编译错误

### ISSUE THREAD

**Issue by The-Pursuit-of-Happyness** [NervJS/taro#1122]
**问题描述**
项目初始化完成后，安装依赖，运行报错

**复现步骤**
[复现问题的步骤]
1. taro init myApp
![image](https://user-images.githubusercontent.com/17919630/48483097-77830080-e84d-11e8-9122-1662af6d7713.png)

2. 进入项目后，安装依赖 yarn
![image](https://user-images.githubusercontent.com/17919630/48483161-a9946280-e84d-11e8-86c8-b9aa0f9492da.png)

3. 到对应文件，发现代码错误
![image](https://user-images.githubusercontent.com/17919630/48483208-caf54e80-e84d-11e8-910c-85039934a9e1.png)

4. 修正后运行，报错
![image](https://user-images.githubusercontent.com/17919630/48483287-faa45680-e84d-11e8-8b06-fe232d0ea46d.png)

```js
// 这里可以贴代码

```

**期望行为**
正常运行

**报错信息**
![image](https://user-images.githubusercontent.com/17919630/48483323-16a7f800-e84e-11e8-9001-6357ac0b98d6.png)
![image](https://user-images.githubusercontent.com/17919630/48483341-2293ba00-e84e-11e8-877a-8e471184511c.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**Comment by ChuHingYee** [comment]
如果紧急的话，可以手动补充那个对象的key: weapp:{}    :)

**Comment by nyrf** [comment]
更新最新1.1.7就好了

**Comment by luckyadam** [comment]
抱歉，已经修复，可以先按 @ChuHingYee 这个哥们说的处理~

**Comment by luckyadam** [comment]
@lsqy 收到，我们后续加上配置文件自动校验以规避这类问题

**Comment by The-Pursuit-of-Happyness** [comment]
> 如果紧急的话，可以手动补充那个对象的key: weapp:{} :)

你说的这个加在哪个地方？

**Comment by luckyadam** [comment]
@The-Pursuit-of-Happyness 报错的不是 config/index.js 文件么，加在这个文件里

**Comment by The-Pursuit-of-Happyness** [comment]
> @The-Pursuit-of-Happyness 报错的不是 config/index.js 文件么，加在这个文件里

我检测了一下，我昨天是直接把
![image](https://user-images.githubusercontent.com/17919630/48525040-8e613b80-e8bd-11e8-9255-675c3b8dbf17.png)
这里的  },  删除了，然后这块不报错了，今天看了你们说的，其实这个地方，不用加啥weapp key,根本原因是这里多了一个 } 
![image](https://user-images.githubusercontent.com/17919630/48525115-d5e7c780-e8bd-11e8-8a5e-57d08a10480c.png)
删除了之后就可以正常运行了

**Comment by lsqy** [comment]
@luckyadam 这么晚了还回复，辛苦了

**Comment by luckyadam** [comment]
已修复，1.1.8
