### ISSUE TITLE
taro.component.d.ts 不能通过tsc检测

### ISSUE THREAD

**Issue by imnot2** [NervJS/taro#11237]
### 相关平台
微信小程序

**小程序基础库: 2.19.4**
**使用框架: React**

### 复现步骤
1. 使用react   ts开发小程序
2. 在git commit时使用tsc 进行类型检查
3. 控制台报错，找不到vue相关的定义

### 期望结果
使用react ts，在tsc检测时，忽略掉vue相关的错误

### 实际结果
tsc检测时，提示taro.component.d.ts这个文件里面有错误

common/temp/node_modules/.pnpm/@tarojs taro@3.3.19/node_modules/@tarojs/taro/types/taro.component.d.ts(2,23): error TS2688: Cannot find type definition file for 'vue'.

common/temp/node_modules/.pnpm/@tarojs taro@3.3.19/node_modules/@tarojs/taro/types/taro.component.d.ts(90,45): error TS2503: Cannot find namespace 'Vue'.

common/temp/node_modules/.pnpm/@tarojs taro@3.3.19/node_modules/@tarojs/taro/types/taro.component.d.ts(90,66): error TS2304: Cannot find name 'Vue'.

### 环境信息
```
> "taro info"

👽 Taro v3.3.19


  Taro CLI 3.3.19 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.19 => 3.3.19 
      @tarojs/components: 3.3.19 => 3.3.19 
      @tarojs/mini-runner: 3.3.19 => 3.3.19 
      @tarojs/plugin-platform-alipay: 3.3.19 => 3.3.19 
      @tarojs/plugin-platform-jd: 3.3.19 => 3.3.19 
      @tarojs/plugin-platform-qq: 3.3.19 => 3.3.19 
      @tarojs/plugin-platform-swan: 3.3.19 => 3.3.19 
      @tarojs/plugin-platform-tt: 3.3.19 => 3.3.19 
      @tarojs/plugin-platform-weapp: 3.3.19 => 3.3.19 
      @tarojs/react: 3.3.19 => 3.3.19 
      @tarojs/runtime: 3.3.19 => 3.3.19 
      @tarojs/taro: 3.3.19 => 3.3.19 
      @tarojs/webpack-runner: 3.3.19 => 3.3.19 
      babel-preset-taro: 3.3.19 => 3.3.19 
      react: 17.0.2 => 17.0.2 
      taro-ui: 3.0.0-alpha.10 => 3.0.0-alpha.10 

```

**Comment by ZakaryCode** [comment]
duplicate #11097
