### ISSUE TITLE
自定义组件不支持传非文本格式内容

### ISSUE THREAD

**Issue by frank7755** [NervJS/taro#1123]
**问题描述**
自定义组件不支持传非文本格式内容。

```js
// 这里可以贴代码
    <List>
          <ListItem
            thumb={payWay1}
            title="同乐支付"
            extraText={
              <View>
                13.6万 <Text>56.3%</Text>
              </View>
            }
          />
    </List>
```

**期望行为**
希望支持上面的写法

**报错信息**
![default](https://user-images.githubusercontent.com/16550396/48525208-3a0a8b80-e8be-11e8-8f9f-178b44588144.png)

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/1119
