### ISSUE TITLE
componentDidMount多次触发

### ISSUE THREAD

**Issue by Qiu800820** [NervJS/taro#1124]
**问题描述**
H5环境中通过url携带参数中包含中文进入下级页面，下级页面中的componentDidMount会触发2次

**复现步骤**
[进入查询车辆违章页面](https://traffic.sxwinstar.net/illegal/#/pages/search/uncertified)
输入车牌号级发动机号。
发现下级页面中的componentDidMount会触发两次

**期望行为**
只触发一次

**报错信息**

无报错

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5]

**补充信息**
![image](https://user-images.githubusercontent.com/7494629/48525185-1d6e5380-e8be-11e8-8e6a-9e50b0c875a2.png)
查看堆栈信息，发现是url改变触发onPopstate 从而有两次History.push导致
onPopstate 代码中有个ignoredUrl判断 发现ignoredUrl是未urlencode的链接  而nextUrl是urlencode编码后的链接

最终将中文参数进行urlencode解决。

**Comment by Littly** [comment]
更新到最新版试试，应该不存在这个问题了。
