### ISSUE TITLE
webpack的 devServer.overlay 属性期望可配置

### ISSUE THREAD

**Issue by ablikim915** [NervJS/taro#11247]
### 这个特性解决了什么问题？
webpack-runner 源码中发现 devServer.overlay 属性被写死的。在本地开发中，每次刷新页面，错误信息覆盖全屏，每次都手动关闭，比较麻烦。

### 这个 API 长什么样？
期望开发者自己可以配置devServer.overlay属性

**Comment by ZakaryCode** [comment]
> webpack-runner 源码中发现 devServer.overlay 属性被写死的。

这个说法并不正确，该配置是可以通过开发者自由配置的

> 在本地开发中，每次刷新页面，错误信息覆盖全屏，每次都手动关闭，比较麻烦。

猜测你说的应该是 react-error-overlay 提示的错误信息，屏蔽方法可参考 [这里](https://stackoverflow.com/questions/46589819/disable-error-overlay-in-development-mode)

**Comment by ablikim915** [comment]
> 猜测你说的应该是 react-error-overlay 提示的错误信息，屏蔽方法可参考 [这里](https://stackoverflow.com/questions/46589819/disable-error-overlay-in-development-mode)

通过css隐藏了错误提示窗口，谢谢你。
