### ISSUE TITLE
使用@tarojs/plugin-html时运行taro doctor报: Taro 3 不再依赖 @tarojs/plugin-html，可以卸载

### ISSUE THREAD

**Issue by we125182** [NervJS/taro#11253]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/we125182/taro-demo.git](https://github.com/we125182/taro-demo.git)
**小程序基础库: 2.19.1**
**使用框架: Vue 2**

### 复现步骤
项目根目录执行： taro doctor

### 期望结果
正确提示。@tarojs/plugin-html是正常依赖

### 实际结果
👽 Taro v3.4.1

✔ 诊断完成

检查 Taro 配置 (/02-code/wx/taro/taro-3.4/config/index.js)，请到文档查看详情：https://nervjs.github.io/taro/docs/next/config-detail。
  [✓] 没有发现问题

检查依赖
  [!] Taro 3 不再依赖 @tarojs/plugin-html，可以卸载

检查推荐内容
  [!] 没有检查到常见的测试依赖(jest/mocha/ava/tape/jesmine/karma), 配置测试可以帮助提升项目质量
      可以参考 https://github.com/NervJS/taro-ui-sample 项目, 其中已经包含了完整的测试配置与范例
  [!] 没有检查到 Readme (readme/readme.md/readme.markdown), 编写 Readme 可以方便其他人了解项目

检查 ESLint (以下为 ESLint 的输出)
  [✓] 没有发现问题

### 环境信息
```
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1 
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
```

**Comment by konka-king** [comment]
我第一次知道这个命令 😄 

👽 Taro v3.4.1

✔ 诊断完成

检查 Taro 配置 (/Users/dev_2/Documents/zcq/t/Travel-Service-User-Miniapp/config/index.js)，请到文档查看详情：https://nervjs.github.io/taro/docs/next/config-detail。
  [✓] 没有发现问题

检查依赖
  [✗] 使用到的依赖 /Users/dev_2/Documents/zcq/t/Travel-Service-User-Miniapp/node_modules/babel-eslint/lib/index.js 还没有安装
  [!] Taro 3 不再依赖 @tarojs/plugin-framework-react，可以卸载

检查推荐内容
  [!] 没有检查到常见的测试依赖(jest/mocha/ava/tape/jesmine/karma), 配置测试可以帮助提升项目质量
      可以参考 https://github.com/NervJS/taro-ui-sample 项目, 其中已经包含了完整的测试配置与范例
  [!] 没有检查到 Readme (readme/readme.md/readme.markdown), 编写 Readme 可以方便其他人了解项目

检查 ESLint (以下为 ESLint 的输出)

**Comment by konka-king** [comment]
我才知道还有这个命令 😄

👽 Taro v3.4.1

✔ 诊断完成

检查 Taro 配置 (/Users/dev_2/Documents/t/config/index.js)，请到文档查看详情：[https://nervjs.github.io/taro/docs/next/config-detail。](https://nervjs.github.io/taro/docs/next/config-detail%E3%80%82)
[✓] 没有发现问题

检查依赖
[✗] 使用到的依赖 /Users/dev_2/Documents/t/node_modules/babel-eslint/lib/index.js 还没有安装
[!] Taro 3 不再依赖 @tarojs/plugin-framework-react，可以卸载

检查推荐内容
[!] 没有检查到常见的测试依赖(jest/mocha/ava/tape/jesmine/karma), 配置测试可以帮助提升项目质量
可以参考 https://github.com/NervJS/taro-ui-sample 项目, 其中已经包含了完整的测试配置与范例
[!] 没有检查到 Readme (readme/readme.md/readme.markdown), 编写 Readme 可以方便其他人了解项目

检查 ESLint (以下为 ESLint 的输出)
