### ISSUE TITLE
redux connect 之后 mapStateToProps问题

### ISSUE THREAD

**Issue by juhuaxia** [NervJS/taro#1125]
有一个loading 组件， 他自己有一个reducer管理state。 
然后我在一个页面引入。 在这个页面进行获取数据的action里面，先dispatch show.
然后在请求返回的回调里面，dispatch hide. 然后我再dispatch页面数据到页面的reducer里面。
这时候会出现问题
spinner 组件的connect里面的 show是false了，但是spinner被reredner里面的props还是true

**注意下面2段代码的区别在于 dispatch({type: HIDE_SPINNER}) 的顺序**
下面这样的dispatch的顺序，子组件loading  在render中获取到的props 为”show“时候的true，但是在子组件connect里面确实正确的false
```js
// 异步的action
export function asyncAdd () {

  return dispatch => {
      dispatch({type: SHOW_SPINNER})
      setTimeout(() => {
        dispatch({type: HIDE_SPINNER})
        dispatch(add())
      }, 2000)
    }
}
````

如果写成下面这样就是正确的。 即 子组件的connect 里的mapStateToProps里面的show ，跟 redner 里面的props获取到的show 都为 false
```js
// 异步的action
export function asyncAdd () {

  return dispatch => {
      dispatch({type: SHOW_SPINNER})
      setTimeout(() => {
        dispatch(add())
        dispatch({type: HIDE_SPINNER})
      }, 2000)
    }
}
```

**Comment by shenghanqin** [comment]
@juhuaxia 请看看最新版本是不是解决了这个问题。
