### ISSUE TITLE
theme.json配置的图片，没有编译到微信小程序

### ISSUE THREAD

**Issue by candyxxc** [NervJS/taro#11267]
### 相关平台
微信小程序

**小程序基础库: 2.21.2**
**使用框架: React**

### 复现步骤
在src目录下新建images/tabbar/a.png b.png
在theme.json配置图片路径

### 期望结果
theme.json配置的图片也能编译到微信小程序

### 实际结果
无

### 环境信息
```
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.5.4
```
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/33587424/153796070-0c787ead-b067-41af-94dc-27096f4a6183.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/33587424/153796092-310a27c4-1e48-4f84-bc4a-83a5f420f52e.png">

**Comment by konka-king** [comment]
正常用到的图片 才会被编译进去吧，没编译进去的是不是代码里面就没有用到？

**Comment by candyxxc** [comment]
> 正常用到的图片 才会被编译进去吧，没编译进去的是不是代码里面就没有用到？

噢。。。没有被编译到的是写在theme.json里面了

**Comment by wangjunjia** [comment]
你试试这个 https://docs.taro.zone/docs/config-detail#copy ，配置文件里用到的图片需要 copy 的。

**Comment by Chen-jj** [comment]
楼上正解
