### ISSUE TITLE
@tarojs/cli所依赖的包，有些已经落后很多版本了，能否做一个升级

### ISSUE THREAD

**Issue by sharon2sun** [NervJS/taro#11262]
### 这个特性解决了什么问题？
我们长期(两年多)收到Dependabot alerts说security vulnerabilities in your dependencies。
比如taro中fbjs是 "^1.0.0"，实际fbjs已经到3.0.4。fbjs里面又依赖了很多包，报了多个high level security issue。
还有webpack-dev-server，ejs，postcss，mini-css-extract-plugin，download-git-repo，latest-version等。

### 这个 API 长什么样？
升级到可兼容的高版本

**Comment by Chen-jj** [comment]
我们尽快梳理一下的~

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/172545641-ec86d05c-9aed-4633-87df-14de7ee5ef46.png)


是的导致一些自有的私有库冲突了

**Comment by yoyo837** [comment]
+prettier

**Comment by ZEJIA-LIU** [comment]
3.6.3 版本已经对依赖进行了整理和升级

**Comment by ZEJIA-LIU** [comment]
您好，我已收到您的邮件，我会尽快给你回复，如有急事，请致电13825803202，谢谢。
