### ISSUE TITLE
taro3 或者 4 有支持 angular 或者 ionic 的计划吗？

### ISSUE THREAD

**Issue by zuohuadong** [NervJS/taro#11274]
### 这个特性解决了什么问题？
使用 ionic 或者 angular 开发小程序。

### 这个 API 长什么样？
兼容

**Comment by HyperLife1119** [comment]
https://github.com/wszgrcy/angular-miniprogram

**Comment by zuohuadong** [comment]
@HyperLife1119  这个目前没 UI 框架。
如果 taro 能支持  angular 的话，复用生态显然更好一些。

**Comment by AdvancedCat** [comment]
首先需要有一个Angular带头大哥；然后完成编译时、运行时以及组件库；

有兴趣可新开discussions进一步讨论。
