### ISSUE TITLE
app.config.ts下配置tabBar，底部导航不存在

### ISSUE THREAD

**Issue by zhaoqi-nb** [NervJS/taro#11288]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/zhaoqi-nb/taro-react-test](https://github.com/zhaoqi-nb/taro-react-test)
**小程序基础库: 2.21**
**使用框架: React**

### 复现步骤
项目启动npm run dev:weapp，能自动根据tabBar自动生成导航不，Taro版本 v3.4.1

### 期望结果
底部导航出现

### 实际结果
底部导航不存在

### 环境信息
```
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      npm: 8.5.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
```

**Comment by zhaoqi-nb** [comment]
是还要自己写custom-tab-bar相关的文件嘛？

**Comment by zhaoqi-nb** [comment]
`  pages: [
    'pages/index/index',
    'pages/imagepage/index',
    'pages/wd/index',
    'pages/musicpage/index',
  ]`
这块必须把pages/index/index放在第一个嘛，我把其他的放第一个，底部导航就不生效呢；
pages/index/index放第一个可以正常显示，
有大佬解释一下嘛

**Comment by konka-king** [comment]
哎，我想回答，又不想回答，您问的问题都太基础了

**Comment by crazyonebyone** [comment]
> ` pages: [ 'pages/index/index', 'pages/imagepage/index', 'pages/wd/index', 'pages/musicpage/index', ]` 这块必须把pages/index/index放在第一个嘛，我把其他的放第一个，底部导航就不生效呢； pages/index/index放第一个可以正常显示， 有大佬解释一下嘛
小程序的机制问题，tabBar第一个必须是pages里面的第一个哦
