### ISSUE TITLE
多张页面纵向排列合并在一起了, page没有正常display:none

### ISSUE THREAD

**Issue by jinglun2019** [NervJS/taro#11292]
### 相关平台
H5

**浏览器版本:  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.72 MQQBrowser/6.2 TBS/045947 Mobile Safari/537.36**
**使用框架: React**

### 复现步骤
偶发,极少遇到,不能稳定复现,好在我录了视频

https://user-images.githubusercontent.com/57926735/154390275-ac54c0de-616b-4ed1-8d1f-c9dc89237de0.mp4

### 期望结果
只显示一张页面

### 实际结果
显示了多张页面

### 环境信息
```
 Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD

```

**Comment by jinglun2019** [comment]
感觉跟这个bug有点像https://github.com/NervJS/taro/issues/10271
但是我的this.props.children并没有分支条件


function WebApp({ children }: React.PropsWithChildren<never>) {
  return (
    <SWRConfig
      value={{
        revalidateOnFocus: false,
      }}
    >
      {children}
    </SWRConfig>
  )
}
export default process.env.TARO_ENV === 'weapp' ? WeApp : WebApp

**Comment by ZakaryCode** [comment]
这个是旧版本的问题，可以更新修复

**Comment by Neno-Chen** [comment]
你好，请问最后是哪个版本修复这个问题
