### ISSUE TITLE
rn无法使用scss全局样式中的变量

### ISSUE THREAD

**Issue by xing-ou** [NervJS/taro#11291]
### 相关平台
React Native

### 复现仓库
[https://github.com/xing-ou/TaroBugDemo](https://github.com/xing-ou/TaroBugDemo)

**使用框架: React**

### 复现步骤
添加全局样式（通过app.scss或者sass: {resource: ['..../common.scss']}也是一样的）
```js
  rn: {
    sass: {
      data: '$aaa: blue;'
    }
....
}
```
然后使用index.scss中
```css
.title {
 color: $aaa;
}
```

### 期望结果
期望rn能够访问全局样式中的变量
小程序和h5都能正常使用

### 实际结果
color: $aaa; 
        ^^^^^^^
undefined variable

### 环境信息
```


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1
      @tarojs/components: 3.4.1 => 3.4.1
      @tarojs/mini-runner: 3.4.1 => 3.4.1
      @tarojs/react: 3.4.1 => 3.4.1
      @tarojs/runtime: 3.4.1 => 3.4.1
      @tarojs/taro: 3.4.1 => 3.4.1
      @tarojs/webpack-runner: 3.4.1 => 3.4.1
      babel-preset-taro: 3.4.1 => 3.4.1
      eslint-config-taro: 3.4.1 => 3.4.1
      react: ^17.0.2 => 17.0.2
      react-native: ^0.66.0 => 0.66.4
```

**Comment by shinken008** [comment]
放错地方了：https://taro-docs.jd.com/taro/docs/config-detail#sass

**Comment by supermaverickws** [comment]
@shinken008 有支持 RN 的 taro UI 库么？

**Comment by xing-ou** [comment]
> 放错地方了：https://taro-docs.jd.com/taro/docs/config-detail#sass

抱歉，没看清楚，非常感谢，把这个关闭吧

**Comment by shinken008** [comment]
> @shinken008 有支持 RN 的 taro UI 库么？

taro ui beta 版本，在测试，可以尝试一下，有问题再修  哈哈
