### ISSUE TITLE
taro的onshow不执行

### ISSUE THREAD

**Issue by ClimbYU** [NervJS/taro#11290]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/ClimbYU/taroTest](https://github.com/ClimbYU/taroTest)
**小程序基础库: 2.11.2**
**使用框架: Vue 2**

### 复现步骤
从A页面点击跳转到B页面，然后点击左上角返回到A页面，此时的A页面内的onshow生命周期不执行，但在原生的微信小程序内可以执行

### 期望结果
期望与微信小程序的效果一致： 页面出现在前台时执行，及在页面每次出现时都会去执行

### 实际结果
实际结果taro只在页面初始化时才执行，其他任何场景都不执行

### 环境信息
```

👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
    npmGlobalPackages:
      typescript: 4.2.4
```

---
### 补充信息
使用的是typescript进行开发

**Comment by wangjunjia** [comment]
用这个试试，import { useDidShow } from '@tarojs/taro'

**Comment by tjeeay** [comment]
遇到同样的问题，2月份的问题现在还没有解决吗？@Taro

**Comment by Chen-jj** [comment]
@ClimbYU @tjeeay 这是基于 Vue2 Class Component 而出现的问题，鉴于 `vue-property-decorator` 这个库缺乏维护且用户不多，Taro 暂时没有计划去支持，建议使用 optional 语法。
