### ISSUE TITLE
taro3.4.1 插件开发 模块补充 ts报错

### ISSUE THREAD

**Issue by adajoy** [NervJS/taro#11305]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/adajoy/plugin-taro](https://github.com/adajoy/plugin-taro)
**小程序基础库: 2.19.1**
**使用框架: React**

### 复现步骤
shims.d.ts中写入以下内容
```ts
import Taro from '@tarojs/taro';

declare module '@tarojs/taro' {
  function f(): string;
}
export {};
```
ts报错Cannot augment module 'Taro' with value exports because it resolves to a non-module entity.

### 期望结果
能够正常扩展taro对象

### 实际结果
ts错误

### 环境信息
```
  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1 
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.9 => 3.0.0-alpha.10
```

**Comment by noyobo** [comment]
```ts
declare module '@tarojs/taro' {
  interface TaroStatic {
    aaaaaa(): void;
  }
}
```

<img width="460" alt="wecom-temp-3fa33026f99f179c26943a4fda8a986f" src="https://user-images.githubusercontent.com/1292082/154627714-8cceb630-4560-4728-87e7-ca158ae533b7.png">
<img width="590" alt="wecom-temp-8df3dba12e93282489f40c22c5356efa" src="https://user-images.githubusercontent.com/1292082/154627725-9bd0cd54-e586-490f-8972-79b1210c4bf8.png">

**Comment by adajoy** [comment]
是不是要更新下文档 https://taro-docs.jd.com/taro/docs/platform-plugin-how#%E7%B1%BB%E5%9E%8B
