### ISSUE TITLE
抖音小程序内置组件渲染问题

### ISSUE THREAD

**Issue by OneKissAndOneShot** [NervJS/taro#11307]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/OneKissAndOneShot/taro-tt-problem/tree/master](https://github.com/OneKissAndOneShot/taro-tt-problem/tree/master)
**小程序基础库: 2.43.0.0**
**使用框架: React**

### 复现步骤
1、npm run dev:tt 

2、审查元素pay-button标签丢失

3、打开dist/pages/index.ttml 中增加<pay-button />  渲染正常

### 期望结果
标签正常显示

### 实际结果
标签丢失

### 环境信息
```
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.10 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
另外，编译之后希望 在dist目录中生成对应端的 package.json文件该怎么操作

**Comment by wangjunjia** [comment]
字节跳动小程序没有这内置组件，https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/component/all
如果使用第三方组件可以这样，https://docs.taro.zone/docs/hybrid

**Comment by wangjunjia** [comment]
@OneKissAndOneShot 找到了这个 https://github.com/NervJS/taro-plugin-inject
