### ISSUE TITLE
Taro 生命周期 与 React 生命周期 的 componentWillReceiveProps 触发时期不同

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1130]
Taro 生命周期 函数 componentWillReceiveProps 在 第一次 挂载时就会触发！而
React 生命周期 函数 componentWillReceiveProps 在 第一次以后 props 变化时 触发！
时 Taro 故意为之，有其意义 嘛？

子组件：
![image](https://user-images.githubusercontent.com/43346131/48529278-4a763280-e8cd-11e8-9d48-981291843815.png)
![image](https://user-images.githubusercontent.com/43346131/48529369-b6f13180-e8cd-11e8-938f-8d43296cc6b3.png)
**系统信息**

 - 操作系统: [e.g. Mac]
 - Taro 版本 [e.g. v1.0.7]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
升级到最新版本试试

**Comment by zw130633** [comment]
我现在是 1.1.4 ，也有这个问题，已经影响我处理业务逻辑了，怎么办

**Comment by zw130633** [comment]
现在临时加了一个计数器，当 componentWillReceiveProps 第一次执行时不做业务逻辑处理，当第二次执行时再做处理

**Comment by zw130633** [comment]
刚才又试了很多次，发现有的时候一开始执行一次，有的时候一开始执行两次。。。。。加计时器也不好使了

**Comment by Chen-jj** [comment]
所谓的初次挂载，是 componentDidMount 触发前的一次渲染。之后再接收 props 就会触发 componentWillReceiveProps，从你的 log 来看是没有问题的，因为 componentDidMount 已经触发过。
可以把可以稳定复现的父子组件的写法发一下再看看。怀疑是哪一步在渲染后触发到 props 改变。
