### ISSUE TITLE
安装项目依赖失败

### ISSUE THREAD

**Issue by xuzhibin** [NervJS/taro#1131]
**问题描述**
创建项目时，安装项目依赖失败

**复现步骤**
[复现问题的步骤]
1. taro init todoList

```bash
 /Volumes/sdcard/Work/Code/taro  taro init todoList
👽 Taro v1.1.7

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

? 请输入项目介绍！ todolist
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板

```

**期望行为**
如何处理

**报错信息**

⠋ 执行安装项目依赖 cnpm install, 需要一会儿... 
✖ 安装项目依赖失败，请自行重新安装！
[npminstall:get] retry GET https://registry.npm.taobao.org/esutils/%3E%3D2.0.2%20%3C3.0.0 after 100ms, retry left 4, error: ResponseError: socket hang up (req "error"), GET https://registry.npm.taobao.org/esutils/%3E%3D2.0.2%20%3C3.0.0 -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":34,"closeSocketCount":16,"errorSocketCount":0,"timeoutSocketCount":11,"requestCount":109,"freeSockets":{"registry.npm.taobao.org:443::::::::true::::::::":6,"cdn.npm.taobao.org:443::::::::true::::::::":9},"sockets":{"registry.npm.taobao.org:443::::::::true::::::::":3},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/chalk/%3E%3D1.1.3%20%3C2.0.0 after 100ms, retry left 4, error: ResponseError: read ECONNRESET (req "error"), GET https://registry.npm.taobao.org/chalk/%3E%3D1.1.3%20%3C2.0.0 -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":34,"closeSocketCount":17,"errorSocketCount":0,"timeoutSocketCount":11,"requestCount":109,"freeSockets":{"registry.npm.taobao.org:443::::::::true::::::::":6,"cdn.npm.taobao.org:443::::::::true::::::::":9},"sockets":{"registry.npm.taobao.org:443::::::::true::::::::":2},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/js-tokens/%3E%3D3.0.0%20%3C4.0.0%7C%7C%3E%3D4.0.0%20%3C5.0.0 after 100ms, retry left 4, error: ResponseError: read ECONNRESET (req "error"), GET https://registry.npm.taobao.org/js-tokens/%3E%3D3.0.0%20%3C4.0.0%7C%7C%3E%3D4.0.0%20%3C5.0.0 -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":37,"closeSocketCount":26,"errorSocketCount":0,"timeoutSocketCount":19,"requestCount":132,"freeSockets":{"registry.npm.taobao.org:443::::::::true::::::::":6,"cdn.npm.taobao.org:443::::::::true::::::::":3},"sockets":{"cdn.npm.taobao.org:443::::::::true::::::::":1,"registry.npm.taobao.org:443::::::::true::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/ansi-colors/%3E%3D3.0.0%20%3C4.0.0 after 100ms, retry left 4, error: ResponseError: socket hang up (req "error"), GET https://registry.npm.taobao.org/ansi-colors/%3E%3D3.0.0%20%3C4.0.0 -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":108,"closeSocketCount":97,"errorSocketCount":0,"timeoutSocketCount":59,"requestCount":671,"freeSockets":{"cdn.npm.taobao.org:443::::::::true::::::::":2,"registry.npm.taobao.org:443::::::::true::::::::":5},"sockets":{"cdn.npm.taobao.org:443::::::::true::::::::":2,"registry.npm.taobao.org:443::::::::true::::::::":2},"requests":{}})
headers: {}
[weui@1.1.3] download ShasumNotMatchError: real sha1:9f08a6935089b3480edf968de2d5a75addebb909 not equal to remote:0f0899bb61bb2ec603b2648367a8139298f81514 (weui@1.1.3) (/Users/xuzhibin/.npminstall_tarball/w/e/u/i/weui/1.1.3-0f0899bb61bb2ec603b2648367a8139298f81514.tgz), fail count: 1
[weui@1.1.3] download ShasumNotMatchError: real sha1:786ca4c112ce7a09d8949d9ec64d9d3eb169fa73 not equal to remote:0f0899bb61bb2ec603b2648367a8139298f81514 (weui@1.1.3) (/Users/xuzhibin/.npminstall_tarball/w/e/u/i/weui/1.1.3-0f0899bb61bb2ec603b2648367a8139298f81514.tgz), fail count: 2
[weui@1.1.3] download ShasumNotMatchError: real sha1:0a252cd4bc96b4eaa6ce3243ba916f814ea1653b not equal to remote:0f0899bb61bb2ec603b2648367a8139298f81514 (weui@1.1.3) (/Users/xuzhibin/.npminstall_tarball/w/e/u/i/weui/1.1.3-0f0899bb61bb2ec603b2648367a8139298f81514.tgz), fail count: 3
ShasumNotMatchError: real sha1:0a252cd4bc96b4eaa6ce3243ba916f814ea1653b not equal to remote:0f0899bb61bb2ec603b2648367a8139298f81514 (weui@1.1.3) (/Users/xuzhibin/.npminstall_tarball/w/e/u/i/weui/1.1.3-0f0899bb61bb2ec603b2648367a8139298f81514.tgz)
    at ReadStream.readstream.on (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:395:21)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npminstall version: 2.15.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/xuzhibin/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

创建项目 todoList 成功！
请进入项目目录 todoList 开始工作吧！😝

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1763232/48531219-616d5280-e8d6-11e8-95c1-ac7d6dbe2527.png">

**系统信息**

- 操作系统: [e.g. mac 10.14]
- Taro 版本 [e.g. v.1.1.7]
- Node.js 版本 [e.g. v10.13.0]

**Comment by luckyadam** [comment]
换 cnpm 或者把源换成国内源，再安装试试

**Comment by xuzhibin** [comment]
换为淘宝源可以了
