### ISSUE TITLE
还需要继续支持 nervjs 吗？

### ISSUE THREAD

**Issue by arniu** [NervJS/taro#11313]
### 这个特性解决了什么问题？
nervjs 已经两年多没更新了，关键是有人会用 taro 来开发非它不可的应用吗？

nervjs 已经躺平了，指望 tarojs 来拖着似乎也不合适。

### 这个 API 长什么样？
停止支持 nervjs。

**Comment by Chen-jj** [comment]
的确是这么想的，特别支持 preact 之后小型类 react 库这方面已有补充。之前文档中已把 nerv 下掉了
