### ISSUE TITLE
wxml-to-canvas 无法使用

### ISSUE THREAD

**Issue by yaodongyi** [NervJS/taro#11321]
### 这个特性解决了什么问题？
微信扩展插件，实现wxml转canvas，生成海报！

### 这个 API 长什么样？
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/component-plus/wxml-to-canvas.html

```
[ subpages/practiceRecord/share/index.json 文件内容错误] subpages/practiceRecord/share/index.json: ["usingComponents"]
["wxml-to-canvas"]: "wxml-to-canvas" 未找到(env: macOS,mp,1.05.2201240; lib: 2.22.0)
```

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/31060569/154850603-5865c648-4c68-4936-8860-8abdfe72782a.png">

看了文档 方式二：
<img width="429" alt="image" src="https://user-images.githubusercontent.com/31060569/154850630-caf0f9e9-2c16-4e85-a2d6-9ba4f5e4db1f.png">
出现问题：
<img width="563" alt="image" src="https://user-images.githubusercontent.com/31060569/154850650-747fad04-860c-4860-8f57-54755bf70f8f.png">

### 相当惆怅
我看到晚期也有人提过这个issues，但是好像是太久没人能够解决，关掉了～～～

**Comment by WAWZ** [comment]
可以把wxml-to-canvas 转成taro 代码

**Comment by astudentat** [comment]
所以。。这个插件就是完全用不了吗

**Comment by kingzez** [comment]
> 所以。。这个插件就是完全用不了吗

我转成 taro3了，可以试试这个 https://www.npmjs.com/package/taro-wxml-to-canvas

**Comment by lidakai** [comment]
> > 所以。。这个插件就是完全用不了吗
> 
> @astudentat 我转成 taro3了，可以试试这个 https://www.npmjs.com/package/taro-wxml-to-canvas


有demo吗？

**Comment by zhangyuanliang** [comment]
> > 所以。。这个插件就是完全用不了吗
> 
> @astudentat 我转成 taro3了，可以试试这个 https://www.npmjs.com/package/taro-wxml-to-canvas

这是react版本的，vue不能用
