### ISSUE TITLE
如何使用SuccessCallbackResult做类型限制？框架没有导出这个类型

### ISSUE THREAD

**Issue by xiao252** [NervJS/taro#11325]
### 相关平台
微信小程序

**小程序基础库: 2.21.2**
**使用框架: React**

### 复现步骤
@tarojs\taro\types\api\network\request.d.ts

中的SuccessCallbackResult类型怎么引用？

### 期望结果
SuccessCallbackResult类型的导出

### 实际结果
SuccessCallbackResult类型的导出

### 环境信息
```
Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.0 - F:\nvm\node\node.EXE
      Yarn: 1.22.10 - F:\nvm\node\yarn.CMD
      npm: 6.14.8 - F:\nvm\node\npm.CMD
```

**Comment by konka-king** [comment]
Taro.request.SuccessCallbackResult

**Comment by xiao252** [comment]
> Taro.request.SuccessCallbackResult

Taro v3.3.16 哦
