### ISSUE TITLE
小程序中 通过数组map生成多个子组件 通过ref获取不到所有的子组件实例

### ISSUE THREAD

**Issue by qiuziz** [NervJS/taro#1133]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

在父组件中map生成多个子组件，通过ref获取所有子组件实例，但最后只拿到第一个子组件实例，无法拿到所有的子组件实例

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
a = [];

data = [{name: 1}, {name: 2}, {name:3}];

refsCreate = (node) => {
    if (!node) return;
    this.aaa[node.props.name] = node;
  }

render() {
  const items =this.data.map((name, index) => {
      return (
        <View className="keys-item-fixed"
          key={index}
          data-key={index}>
          <IndexItem ref={this.refsCreate} name={name} />
        </View>
      )
    })
 return (
 <View>
         {items}
        </View>
)
}

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

能获取到所有子组件实例

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: macOS 10
 - Taro 版本 1.1.7
 - Node.js 版本 10.1.0
 - 报错平台weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

![image](https://user-images.githubusercontent.com/13669987/48532962-844f3500-e8dd-11e8-933c-de01ff14a7b0.png)
看了下cli的源码中关于ref的编译，似乎只会返回一个组件实例

**Comment by luckyadam** [comment]
确实~ 还没有支持 map 循环，这部分实现有点难度，因为编译时还不知道循环会有多少个，得好好想一想方案~

**Comment by qiuziz** [comment]
希望尽快支持下~

现在在写索引选择器这个组件，有需要获取所有子组件实例的需求，在小程序中是有getRelationNodes这个方法获取所有关联的子组件

暂时只能在组件里面根据业务写不同的模板 但是这样不够通用

**Comment by jswxwxf** [comment]
我也遇到这个问题了，请问什么时候可以解决啊？

**Comment by yuche** [comment]
安装最新的版本可以做到循环中使用 ref。

**Comment by jswxwxf** [comment]
好的
