### ISSUE TITLE
addInterceptor添加拦截器,那么如何删除拦截器呢?

### ISSUE THREAD

**Issue by laolaolulu** [NervJS/taro#11339]
### 这个特性解决了什么问题？
addInterceptor添加拦截器,那么如何删除拦截器呢?

### 这个 API 长什么样？
addInterceptor添加拦截器,那么如何删除拦截器呢?

**Comment by Breeze1114** [comment]
把代码删掉？

**Comment by ZakaryCode** [comment]
cleanInterceptors
