### ISSUE TITLE
Textarea 输入内容，导致页面崩溃。3.3.16开始出现该问题，将taro版本升级到 3.4.1 时，该问题仍存在

### ISSUE THREAD

**Issue by wenxiuYang** [NervJS/taro#11335]
### 相关平台
H5

### 复现仓库
[https://github.com/wenxiuYang/taro-demo](https://github.com/wenxiuYang/taro-demo)
**浏览器版本: 98.0.4758.102 (正式版本) （64 位） (cohort: Stable) **
**使用框架: React**

### 复现步骤
打开 【pages/index/index】，在 Textarea 中输入内容，页面崩溃。只有重新编译，重新在浏览器中打开新标签页才能正常浏览页面

### 期望结果
Textarea 可以正常输入文本

### 实际结果
Textarea 不能输入文本

### 环境信息
```

Taro CLI 3.3.16 environment info:
 System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - D:\Nodejs\node.EXE
      Yarn: 1.22.17 - D:\Nodejs\yarn.CMD
      npm: 6.14.12 - D:\Nodejs\npm.CMD

```

**Comment by wangjunjia** [comment]
不要轻易尝试运行此项目，风扇起飞了

**Comment by ZakaryCode** [comment]
fix in #11443
