### ISSUE TITLE
react-native android 模拟器 expo 应用显示 something went wrong

### ISSUE THREAD

**Issue by MYQ1996** [NervJS/taro#1134]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
![image](https://user-images.githubusercontent.com/17963690/48534900-76e97900-e8e4-11e8-90cb-6d80cd0d1574.png)
![image](https://user-images.githubusercontent.com/17963690/48534966-a7c9ae00-e8e4-11e8-8c4a-13d24bd63033.png)

**复现步骤**
[复现问题的步骤]
1. 使用expo来运行
2. ios可以实现
3. 安卓报错

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [10.12.6 (16G1510)]
 - Taro 版本 [1.1.4]
 - Node.js 版本 [v10.8.0]
 - 报错平台 [android]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by MYQ1996** [comment]
如果发现这个问题，那么就是expo的兼容性问题了
链接: https://pan.baidu.com/s/1z00Rfwil851fZew3RLO7lQ 提取码: eqw1 
使用Exponent-2.9.2 就可以解决这个问题

**Comment by Pines-Cheng** [comment]
感谢提供参考～

**Comment by Pines-Cheng** [comment]
https://github.com/react-community/create-react-native-app/issues/81
