### ISSUE TITLE
字节小程序新增pay-button组件，需要taro官方支持

### ISSUE THREAD

**Issue by slxgsy** [NervJS/taro#11341]
### 这个特性解决了什么问题？
字节小程序交易模版提供了一个入口组件pay-button，该组件是小程序基础库内置组件，可直接使用。
组件的使用模式可以分为已下单和未下单，未下单即立即抢购，已下单根据使用场景可以细分为继续支付、申请退款、退款中、退款完成、退款失败。

### 这个 API 长什么样？
Taro官方编译后能正常支持pay-button组件功能。
字节小程序原生代码：
<pay-button ​
    order-status="{{0}}" ​
    order-id="xxx" ​
    bind:pay="handleContinutePay" ​
 />

**Comment by wangjunjia** [comment]
@slxgsy 这个 pay-button 组件有字节小程序的文档吗？我怎么没有看到呀

**Comment by slxgsy** [comment]
> 



> @slxgsy 这个 pay-button 组件有字节小程序的文档吗？我怎么没有看到呀

我有跟字节的技术沟通，对外的文档还没有更新这个组件。字节那边是通过飞书文档给了我们这个组件的使用介绍，但是我们还不能对外发出来。

**Comment by wangjunjia** [comment]
@slxgsy 这个试试 https://github.com/NervJS/taro-plugin-inject

**Comment by slxgsy** [comment]
> @slxgsy 这个试试 https://github.com/NervJS/taro-plugin-inject

最后是把字节的原生组件封装成自定组件，通过usingComponents的方式引入页面中。目前测试是可以正常使用。后续再继续看有没有其他办法。

**Comment by tinatianzhu** [comment]
> > @slxgsy 这个试试 https://github.com/NervJS/taro-plugin-inject
> 
> 最后是把字节的原生组件封装成自定组件，通过usingComponents的方式引入页面中。目前测试是可以正常使用。后续再继续看有没有其他办法。
请问
![image](https://user-images.githubusercontent.com/37437496/191902693-fd477f5a-4960-4a04-9809-b7ba62aed2e4.png)
 "ttPlugins": {
    "dependencies": {
      "microapp-trade-plugin": {
        "version": "1.1.2",
        "isDynamic": true
      }
    }
  }
这个怎么配置的在taro中

**Comment by pfsj-xk** [comment]
什么时候支持上

**Comment by mingw-ay** [comment]
> > @slxgsy 这个试试 https://github.com/NervJS/taro-plugin-inject
> 
> 最后是把字节的原生组件封装成自定组件，通过usingComponents的方式引入页面中。目前测试是可以正常使用。后续再继续看有没有其他办法。

请问怎么把pay-button封装成自定义组件呢？
