### ISSUE TITLE
3.4.2版本  uploadFile 未携带cookie

### ISSUE THREAD

**Issue by Hicbik** [NervJS/taro#11357]
### 相关平台
H5

**浏览器版本: 微信开发者工具**
**使用框架: React**

### 复现步骤
uploadFile发送文件未携带cookie

### 期望结果
携带cookie

### 实际结果
未携带

### 环境信息
```
� Taro v3.4.2


  Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\shiyi\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
upload源代码 缺少 ` xhr.withCredentials = true; `

**Comment by ZakaryCode** [comment]
该问题没有关联,请检查域名下是否存在 cookie

> 另外,`xhr.withCredentials = true`会在 v3.5+ 补上
