### ISSUE TITLE
[FeatureRequest] 特定平台代码及资源支持

### ISSUE THREAD

**Issue by zacksleo** [NervJS/taro#1135]
目前可以通过`Taro.getEnv()`获取当前环境，但是还不够用

### 组件

例如一个 `FabButton` 组件, 默认使用 `FabButton.js` 命名，或者 `components/FabButton/index.js`,
如果针对特定平台进行实现，可以使用以下形式：

| 平台  | 命名1  | 命名2  | 备注  | 
|---|---|---|---|
| 默认  | FabButton.js  |  components/FabButton/index.js |   | 
| 百度 |  FabButton.swan.js | components/FabButton/index.alipay.js  |   |   
|  支付宝 | FabButton.alipay.js  |  components/FabButton/index.web.js |   |   
| Web | FabButton.web.js  |  components/FabButton/index.alipay.js |   |  
|  ReactNative| FabButton.rn.js  |  components/FabButton/index.rn.js |   |   
|  ios | FabButton.ios.js  |  components/FabButton/index.rn.js | reactnative分支 |   
|  android | FabButton.android.js  |  components/FabButton/index.rn.js | reactnative分支 |   

使用方法， `import 'FabButton.js'`, 编译时自动根据目标平台，进行代码替换，将  `demo.{平台代码}.js` 替换为 `demo.js`

### 资源

如果不同平台需要引用不同的样式，同样使用以上规则，将 `demo.{平台代码}.css`, `demo.{平台代码}.png` 等等 替换为 `demo.css, demo.png`

使用方法： `import './demo.js'`

### 备注

代码中 import 引用时，文件名不包含平台后缀，特别情况下，例如，存在 `FabButton.js` 和 `FabButton.rn.js`, 以及 `button.png` 和 `button.rn.png`, 在两个js文件中, 引用图片时均使用` import './button.png'`,  在其他地方引用 FabButton 时，使用 `import  'path/to/FabButton'`

## 参考资料：

+ [特定平台代码](https://reactnative.cn/docs/platform-specific-code/)

+ [图片](https://reactnative.cn/docs/images/)

**Comment by tourze** [comment]
这种做法，我记得rn最早是这样支持的。。。但是到现在他们都已经放弃了。。。
我个人觉得如果是要不同平台不同渲染结果，还是老实自己在jsx里面做判断比较好

**Comment by luckyadam** [comment]
我觉得还是可以考虑一下

@zacksleo 你也可以用 https://nervjs.github.io/taro/docs/envs.html 来搞一搞

**Comment by thewei** [comment]
@tourze 他们什么时候放弃了这个做法? ？？

**Comment by zacksleo** [comment]
同问，[官方文档](https://facebook.github.io/react-native/docs/platform-specific-code)写的好好的

**Comment by tourze** [comment]
这个特性taro貌似已经实现了

**Comment by yuche** [comment]
已经实现了，具体可以看： https://nervjs.github.io/taro/docs/envs.html
