### ISSUE TITLE
Picker组件的mode为region时，不支持官方的leve设定

### ISSUE THREAD

**Issue by mumuwooo** [NervJS/taro#11368]
### 这个特性解决了什么问题？
官方2.21.1的版本里支持了level 的有效值设置

### 这个 API 长什么样？
希望taro可以跟进一下这个需求，虽然我知道自定义regionData也可以解决地区联动限制层级的问题

**Comment by kungege** [comment]
any progress?

**Comment by TheKonka** [comment]
Duplicate of #13047
