### ISSUE TITLE
是否支持使用ant design的UI库？

### ISSUE THREAD

**Issue by dengxue0** [NervJS/taro#1136]
**问题描述**
是否支持使用ant design的UI库？

**复现步骤**
[复现问题的步骤]
1. 在taro项目中使用npm安装了ant design UI库
2. 导入了相关组件import { Tag } from 'antd'，并且调用<Tag>一个标签</Tag>

**期望行为**
可以支持ant design UI库

**报错信息**
![image](https://user-images.githubusercontent.com/21215992/48538383-478c3980-e8ef-11e8-8743-1a87229411da.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.1.7]
 - Node.js 版本 [v8.11.1]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
不支持。因为 `antd` 不是按 Taro 规范写的，只能等社区或 `antd` 去支持 Taro。
