### ISSUE TITLE
app.config.ts 或page.config.ts中backgroundColor属性不生效

### ISSUE THREAD

**Issue by fullee** [NervJS/taro#11374]
### 相关平台
微信小程序

**小程序基础库: 2.22.0**
**使用框架: React**

### 复现步骤
app.config.ts
```
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#FFFFFF",
    navigationBarTitleText: "xxx",
    navigationBarTextStyle: "black",
    backgroundColor: "#f0edf1" // 加入这一行没有效果
  },
```

page.config.ts
```
export default {
  navigationBarTitleText: "首页",
  // enablePullDownRefresh: true
  backgroundColor: "#f0edf1" // 这一行无效
};

```

### 期望结果
微信小程序是支持这个属性的backgroundColor

### 实际结果
微信小程序是支持这个属性的backgroundColor

### 环境信息
```
$ taro info
� Taro v3.3.20


  Taro CLI 3.3.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.0 - E:\usr\nodejs\node.EXE
      npm: 6.14.15 - E:\usr\nodejs\npm.CMD

```

**Comment by konka-king** [comment]
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/page.html

您是指窗口的背景色吗，我这边测试是有效的，安卓手机页面固定看不出来效果，苹果手机有橡皮筋效果可以看出来

**Comment by fullee** [comment]
> konka-king

您的意思是安卓不支持这个属性吗

**Comment by konka-king** [comment]
> @konka-king
> 
> 您的意思是安卓不支持这个属性吗

不是，支持的，这个是下拉刷新的背景色，安卓页面开启enablePullDownRefresh下拉就能看到效果
https://developers.weixin.qq.com/community/develop/doc/000c2a3967cf207ad4e9c37165b800?highLine=backgroundColor
https://developers.weixin.qq.com/community/develop/doc/00040829d304d0c30acc437ce57000?highLine=backgroundColor

**Comment by fullee** [comment]
页面默认颜色有没有配置选项



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月12日 12:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NervJS/taro] app.config.ts 或page.config.ts中backgroundColor属性不生效 (Issue #11374) |

@konka-king

您的意思是安卓不支持这个属性吗

不是，支持的，这个是下拉刷新的背景色，安卓页面开启enablePullDownRefresh下拉就能看到效果
https://developers.weixin.qq.com/community/develop/doc/000c2a3967cf207ad4e9c37165b800?highLine=backgroundColor
https://developers.weixin.qq.com/community/develop/doc/00040829d304d0c30acc437ce57000?highLine=backgroundColor

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by konka-king** [comment]
> 页面默认颜色有没有配置选项
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年03月12日 12:37 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [NervJS/taro] app.config.ts 或page.config.ts中backgroundColor属性不生效 (Issue #11374) | @konka-king 您的意思是安卓不支持这个属性吗 不是，支持的，这个是下拉刷新的背景色，安卓页面开启enablePullDownRefresh下拉就能看到效果 https://developers.weixin.qq.com/community/develop/doc/000c2a3967cf207ad4e9c37165b800?highLine=backgroundColor https://developers.weixin.qq.com/community/develop/doc/00040829d304d0c30acc437ce57000?highLine=backgroundColor — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

小程序每个页面最外层都是一个`<page>`直接在页面 的 css 里面 加个 page 选择器 ，里面设置背景色就行
![image](https://user-images.githubusercontent.com/22173084/158020994-4d2a7e8d-6a3e-443d-aa59-da8a7cf1267f.png)

**Comment by JakeWoki** [comment]
app.config.ts的window的backgroundColor，小程序苹果安卓都无效
