### ISSUE TITLE
ts 模板项目eslint报错

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro#1137]
**问题描述**
模板项目pages/index/index.tsx eslint报错

**报错信息**

<img width="500" alt="eslint_error" src="https://user-images.githubusercontent.com/8776592/48539258-96d36980-e8f1-11e8-899d-26ad94292e79.png">

**系统信息**

 - 操作系统: [macOS 10.14]
 - Taro 版本 [1.1.7]
 - Node.js 版本 [v8.11.1]
 - 报错平台 [ weapp]

**Comment by yujiaming890321** [comment]
遇到过相同问题
解决方案 .eslint 
```js
{
    "extends": ["taro", "plugin:taro/all"],
    "rules": {
        "no-unused-vars": ["error", { "varsIgnorePattern": "Taro" }],
        "react/jsx-filename-extension": [
            1,
            { "extensions": [".js", ".jsx", ".tsx"] }
        ]
    },
    "parser": "babel-eslint"
}
```
taro 是 [eslint-config-taro](https://www.npmjs.com/package/eslint-config-taro)
plugin:taro/all 是 [eslint-plugin-taro](https://www.npmjs.com/package/eslint-plugin-taro)

**Comment by yujiaming890321** [comment]
遇到相同问题..

**Comment by yujiaming890321** [comment]
目前解决方案就是加上分号。

**Comment by yuche** [comment]
这个其实 Taro 没有办法，如果你用 ESlint 来检查 TS 内容实际上是 [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) 的问题。这个 parser 现在还处于实验性不稳定的状态，如果你有问题可以去那提 issue。

**Comment by callmewhy** [comment]
加上分号 `export default Index as ComponentClass` 也会报 `unexpected token` 的 error。能关掉 eslint 默认的 lint 吗，只开启 taro 的一些 lint

**Comment by futantan** [comment]
Any progress or suggestion about this?

**Comment by futantan** [comment]
我目前的做法是：
`eslintrc` 中修改
```
"parser": "typescript-eslint-parser"
```
在 `package.json` script 中添加 `"lint": "eslint src/ --ext .tsx --ext .ts"`
这样的目的是让 eslint 去处理 ts 和 tsx 文件。
