### ISSUE TITLE
https://issue.taro.zone/ 这个页面可以提供一个白色界面吗，黑色不容易看清

### ISSUE THREAD

**Issue by fullee** [NervJS/taro#11375]
### 这个特性解决了什么问题？
更方便提交issue，利于社区发展

### 这个 API 长什么样？
无

**Comment by AdvancedCat** [comment]
输入框下面的提示信息吗？我感觉还好，如果真的影响阅读，可以先在Element里手动调整一下字色呢

**Comment by fullee** [comment]
![e13d7ac6d0c7b519f89d224376ed097](https://user-images.githubusercontent.com/11188837/156866715-7d932265-9b3c-4af3-b5ed-54ac38026431.jpg)

下面的字直接看不清
