### ISSUE TITLE
H5 v-if 报错

### ISSUE THREAD

**Issue by collincheng** [NervJS/taro#11379]
### 相关平台
H5

### 复现仓库
[https://gitee.com/zhenglinhai/taro-demo.git](https://gitee.com/zhenglinhai/taro-demo.git)
**浏览器版本: Chrome  98.0.4758.109**
**使用框架: Vue 3**

### 复现步骤
这个仓库写了一个简单的demo 跑 dev:h5就行

### 期望结果
不报错

### 实际结果
报错了

### 环境信息
```
Taro CLI 3.4.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/runtime: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
```

**Comment by collincheng** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/49746060/156486489-19d5b3fd-33e9-48ab-9637-4f2be69c7e03.png">
v-if 插入节点失败

**Comment by xinpingwang** [comment]
## 临时规避方式

将 template 内最外层的 `view` 修改为 `div` 标签：
```vue
<template>
  <div class="index">
    <view v-if="id === 1">
      <text>{{ msg }}</text>
    </view>
    <!-- H5中插入节点报错了 -->
    <view v-if="id === 2">
      <text>111</text>
    </view>
  </div>
</template>
```

## 问题原因分析

根据报错信息提示，`insertBefore` 指定的相对节点是一个 `comment` 节点，并且该节点已不存在于当前的 parent 节点内：

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/41824968/162609359-d8100bc3-4c06-45ad-b802-61e3dc5498cb.png">

对比**原代码**和**上述临时规避方式中的代码**在 `id` 的值变化前渲染生成的 DOM，使用 `view` 标签时，没有 `<!--v-if-->` 节点

<img width="287" alt="image" src="https://user-images.githubusercontent.com/41824968/162610077-40d96c78-fa53-429d-8746-a07806e6fbf6.png"> <img width="284" alt="image" src="https://user-images.githubusercontent.com/41824968/162610115-18cb454c-664d-425a-a6a0-cc92f22df806.png">

进一步分析 `view` 组件的代码，在组件完成渲染后会将节点内的 `comment` 节点移除，进一步证实了上述差异产生的原因：
https://github.com/NervJS/taro/blob/93493fa939e376b10b7a80e641d2174451c3dca0/packages/taro-components/src/components/view/view.tsx#L64-L69

通过分析该文件的提交记录，是由 https://github.com/NervJS/taro/pull/10510 修复 https://github.com/NervJS/taro/issues/10365 时引入的新问题

**Comment by dongj0316** [comment]
同样的问题

**Comment by Chen-jj** [comment]
看来不能处理 vue 的 comment 节点，我们回归测试一下。
