### ISSUE TITLE
百度小程序预渲染失败

### ISSUE THREAD

**Issue by simons2333** [NervJS/taro#11376]
### 相关平台
百度小程序

**小程序基础库: 3.420.5**
**使用框架: React**

### 复现步骤
执行 taro build --type swan 或  taro build --type swan  --blended

### 期望结果
百度小程序正常生成预渲染结果

### 实际结果
2022/3/2 下午12:07:02 页面 app 预渲染失败：
ReferenceError [Error]: inst is not defined

2022/3/2 下午12:07:02 页面 pages/home/index 预渲染失败：
TypeError [Error]: page.onLoad is not a function

### 环境信息
```
 Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.2 => 3.4.2 
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/react: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      bbj-taro-runtime:  3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
      react: ^17.0.2 => 17.0.2 

```

---
### 补充信息
阿里小程序打包也报错

**Comment by Chen-jj** [comment]
@simons2333 麻烦提供一下 Demo，复现步骤也描述得详细一点

**Comment by saralee2012** [comment]
请问下百度预渲染失败的问题已经解决么 taro3.6.4版本设置prerender还是报page.onLoad is not a function

**Comment by Fental** [comment]
Taro版本3.6.35，设置prerender依然报错：page.onLoad is not a function
相关Taro同学能否看一看，这个issue到现在已经3年多了，为什么一直没有人跟进解决？
