### ISSUE TITLE
ScrollView  文档中相关事件名称大小写问题

### ISSUE THREAD

**Issue by wjkang** [NervJS/taro#11371]
### 相关平台
微信小程序

**小程序基础库: 2.21.3**
**使用框架: Vue 3**

### 复现步骤
比如文档中写的是onRefresherRefresh，onScrollToLower。vue3使用 tsx ，这样写 onRefresherrefresh，onScrolltolower才会生效

### 期望结果
文档中写清楚

### 实际结果
文档中未标明

### 环境信息
```
Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.17.0 - H:\node\node.EXE
      Yarn: 1.17.3 - H:\node\node_global\yarn.CMD
```

**Comment by Chen-jj** [comment]
@wjkang 可以参考这个回答：https://stackoverflow.com/questions/53413800/vue-jsx-event-handlers

![image](https://user-images.githubusercontent.com/11807297/158070645-5b5de411-faeb-4c7b-9729-86ba3de4b0f8.png)

Taro 文档的 JSX 是描述 React 的，Vue 的 JSX 语法对于事件的确是需要 onCamelcase，因为小程序的事件都是小写。
