### ISSUE TITLE
usePullDownRefresh 不能正常触发

### ISSUE THREAD

**Issue by talentjeff** [NervJS/taro#11385]
### 相关平台
H5

**浏览器版本: chrome 98.0.4758.102**
**使用框架: React**

### 复现仓库
https://github.com/talentjeff/usePullDownRefresh_bug

### 复现步骤
A页面设置enablePullDownRefresh: true， 使用usePullDownRefresh监听下拉动作。
从其他任意页面通过Taro.navigateTo跳转到A页面
在A页面下拉

### 期望结果
触发usePullDownRefresh

### 实际结果
未触发usePullDownRefresh

### 环境信息
```
👽 Taro v3.3.19

undefined

  Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
出现bug时，如果刷新A页面，又可以正常触发usePullDownRefresh
用的taro是3.4.2，不知道为什么bug模板里不能选
重现链接链接稍后补

**Comment by talentjeff** [comment]
复现DEMO已补充
https://github.com/talentjeff/usePullDownRefresh_bug

**Comment by ZakaryCode** [comment]
旧版本问题，可以升级修复该问题
