### ISSUE TITLE
初始化项目时使用Redux模板，运行会出错（SyntaxError: Unexpected token，code ELIFECYCLE）

### ISSUE THREAD

**Issue by nboss** [NervJS/taro#1138]
**问题描述**
初始化项目时使用Redux模板，运行会出错，执行不下去

**复现步骤**
1.taro init taroApp
2. 请输入项目介绍！ taro demo
3. 是否需要使用 TypeScript ？ No
4. 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
5. 请选择模板 Redux 模板  
6.cd taroApp
7.npm run dev:weapp

第5步选了Redux模板，执行
npm run dev:weapp/h5
npm run build:weapp/h5
都会出错，其它没试

**期望行为**
能够正常编译执行

**报错信息**
SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taroApp@1.0.0 build:weapp: `taro build --type weapp "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taroApp@1.0.0 build:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-15T07_53_21_432Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taroApp@1.0.0 dev:weapp: `npm run build:weapp -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taroApp@1.0.0 dev:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-15T07_53_21_506Z-debug.log

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本: v1.1.7
 - Node.js 版本: 10.13.0
 - 报错平台: h5, weapp

**Comment by Zoom2016** [comment]
我也有这个问题，还特地对比了 不同css预处理器 和 不同模板，最后试出来，只要是选择redux模板，config\index.js文件内容错误，上对比图
![_20181115181415](https://user-images.githubusercontent.com/24583558/48546082-56301c00-e902-11e8-9569-cf7e53ebc015.png)

**Comment by luckyadam** [comment]
已修复，配置你可以先自行补上~
