### ISSUE TITLE
webpack-chain这么难用，为什么不开放个 configureWebpack ?

### ISSUE THREAD

**Issue by agileago** [NervJS/taro#11388]
### 这个特性解决了什么问题？
比如我想增加一个 ts-loader的配置，或者说直接修改一下webpack的配置，还得查半天webpack-chain的文档，也看不到具体的最后的webpack的配置， 希望增加一个类似 vue-cli的 configureWebpack 的配置直接修改webpack的配置

### 这个 API 长什么样？
配置中增加：configureWebpack: config => {}

**Comment by yujingwyh** [comment]
学习了半天，最简单的办法就是直接开启调试，看下chain里都有啥...

**Comment by Chen-jj** [comment]
可以用 `taro inspect --help` 查看 Webpack 的配置。易用性方面我们再考虑下~

**Comment by agileago** [comment]
修改配置一般都是找到原对象直接改了，这还得先去找webpack-chain，怎么找到这个对象然后怎么改，心累

**Comment by Chen-jj** [comment]
> 修改配置一般都是找到原对象直接改了，这还得先去找webpack-chain，怎么找到这个对象然后怎么改，心累

主要是有 webpack-chain 的学习成本，熟悉后 `chain.merge` 还是很强大的。

**Comment by agileago** [comment]
哈哈，这就跟rxjs很强大，前提你要花很大精力学会
