### ISSUE TITLE
新建小程序插件 打包出错  not contain an export named 'createNativeComponentConfig'

### ISSUE THREAD

**Issue by i2kai** [NervJS/taro#11381]
### 相关平台
微信小程序

**小程序基础库: 2.22.1**
**使用框架: Vue 2**

### 复现步骤
新建  小程序插件 执行 taro build --plugin weapp 打包命令 
出现下面错误:
./src/plugin/views/index/index.vue 13:21-48
" '@tarojs/plugin-framework-vue2/dist/runtime' does not contain an export named 'createNativeComponentConfig'.

./src/plugin/components/avatar/avatar.vue 13:21-48
" '@tarojs/plugin-framework-vue2/dist/runtime' does not contain an export named 'createNativeComponentConfig'.

### 期望结果
打包运行不会出现错误

### 实际结果
出错

### 环境信息
```
👽 Taro v3.4.2


  Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - D:\nodeJS\node.EXE
      Yarn: 1.22.11 - C:\Users\i2kai\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - D:\nodeJS\npm.CMD

```

---
### 补充信息
新建  小程序插件 执行 taro build --plugin weapp 打包命令 
出现下面错误:
./src/plugin/views/index/index.vue 13:21-48
" '@tarojs/plugin-framework-vue2/dist/runtime' does not contain an export named 'createNativeComponentConfig'.

./src/plugin/components/avatar/avatar.vue 13:21-48
" '@tarojs/plugin-framework-vue2/dist/runtime' does not contain an export named 'createNativeComponentConfig'.

**Comment by Chen-jj** [comment]
vue 还没支持编译为小程序插件的，正在跟进中

**Comment by i2kai** [comment]
> 



> vue 还没支持编译为小程序插件的，正在跟进中

好的。谢谢啊
