### ISSUE TITLE
支持vue3类组件

### ISSUE THREAD

**Issue by agileago** [NervJS/taro#11392]
### 这个特性解决了什么问题？
vue3是支持类组件的, 但现在taro-runtime不支持类组件

https://github.com/vuejs/core/blob/5898629d723e82b68e9b17b91bf8b1a8390a3912/packages/runtime-core/src/vnode.ts#L517

### 这个 API 长什么样？
支持类组件

**Comment by agileago** [comment]
@Chen-jj    https://github.com/NervJS/taro/blob/de55da7a845e9c09ba65528e74c7310e5082c2d5/packages/taro-plugin-vue3/src/runtime/connect.ts#L97

这里为啥要copy一遍， 如果是类组件，他的选项对象在 `__vccOpts` 上面的，这样会导致类组件渲染不出来

**Comment by agileago** [comment]
我提个pr？

**Comment by Chen-jj** [comment]
@agileago 印象中使用 `Object.assign` 进行阻隔，是因为 Vue 运行时会给 PageComponent 加属性什么的，不新建一个对象会影响新页面挂载。

可以使用 [isClassComponent](https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-core/src/component.ts#L975-L977) 进行判断，如果是 class 组件则直接赋值给 PageComponent。

欢迎 PR~
