### ISSUE TITLE
scrollView下拉刷新动画错位

### ISSUE THREAD

**Issue by undeadfrost** [NervJS/taro#11394]
### 相关平台
微信小程序

**小程序基础库: 2.22.1**
**使用框架: React**

### 复现步骤
点击隐藏显示，下拉刷新后在点击隐藏显示

``import { View, Button, ScrollView, Image } from '@tarojs/components'
import { useState } from 'react'

export default function Test() {
  const [show, setShow] = useState(false)

  return (
    <View>
      <ScrollView
        style={{ width: '100%', height: 400, display: !show ? 'block' : ' none' }}
        scrollY
        refresherEnabled
        refresherBackground='green'
      >
        <View>22222</View>
        <View>22222</View>
        <View>22222</View>
        <View>22222</View>
      </ScrollView>
      {
        show && (
          <ScrollView style={{ width: '100%', height: 400 }} scrollY refresherEnabled>
            <View>11111</View>
            <View>11111</View>
            <View>11111</View>
            <View>11111</View>
          </ScrollView>
        )
      }
      <Button onClick={() => setShow(!show)}>{show ? '隐藏' : '显示'}</Button>
    </View>
  )
}
``
![企业微信20220304-161048](https://user-images.githubusercontent.com/24819204/156724703-ddc5548b-8d8e-4895-9ddd-d64b7db5ef4f.png)

### 期望结果
在切换显示与隐藏中下拉刷新动画可以正常显示

### 实际结果
切换显示隐藏后，动画位置偏移

### 环境信息
```
👽 Taro v3.3.16


  Taro CLI 3.3.16 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    npmPackages:
      @tarojs/components: 3.3.16 => 3.3.16 
      @tarojs/mini-runner: 3.3.16 => 3.3.16 
      @tarojs/react: 3.3.16 => 3.3.16 
      @tarojs/runtime: 3.3.16 => 3.3.16 
      @tarojs/taro: 3.3.16 => 3.3.16 
      @tarojs/webpack-runner: 3.3.16 => 3.3.16 
      babel-preset-taro: 3.3.16 => 3.3.16 
      eslint-config-taro: 3.3.16 => 3.3.16 
      react: ^17.0.0 => 17.0.2 

```

**Comment by Chen-jj** [comment]
感觉和微信小程序的模板 diff 有关，暂时可以通过增加一层 `View` 来解决：

```js
export default function Test() {
  const [show, setShow] = useState(false)

  return (
    <View>
      <View>
      <ScrollView
        style={{ width: '100%', height: 400, display: !show ? 'block' : ' none' }}
        scrollY
        refresherEnabled
        refresherBackground='green'
      >
        <View>22222</View>
        <View>22222</View>
        <View>22222</View>
        <View>22222</View>
      </ScrollView>
      </View>
      <View>
      {
        show && (
          <ScrollView style={{ width: '100%', height: 400 }} scrollY refresherEnabled>
            <View>11111</View>
            <View>11111</View>
            <View>11111</View>
            <View>11111</View>
          </ScrollView>
        )
      }
      </View>
      <Button onClick={() => setShow(!show)}>{show ? '隐藏' : '显示'}</Button>
    </View>
  )
}
```

[为什么增加 View 可以解决](https://docs.taro.zone/docs/optimized#1-%E5%88%A0%E9%99%A4%E6%A5%BC%E5%B1%82%E8%8A%82%E7%82%B9%E8%A6%81%E8%B0%A8%E6%85%8E%E5%A4%84%E7%90%86)

后续会把数组形式的 childNodes 改为对象形式，应该可以解决这个问题。

**Comment by undeadfrost** [comment]
> 感觉和微信小程序的模板不同，暂时可以通过增加`View`来解决：
> 
> ```js
> 导出 默认 函数 Test ( )  { 
>   const  [ show ,  setShow ]  =  useState ( false ) 
> 
>   return  ( 
>     < View > 
>       < View > 
>       < ScrollViewstyle 
>         = { { width : '100%' , height : 400 , display : ! show ? ' block ' : '无' } } scrollY    
>         
>         refresherEnabled 
>         refresherBackground = 'green' 
>       > 
>         <查看> 22222 < /查看> 
>         <查看> 22222 < /查看> 
>         <查看> 22222 < /查看> 
>         <查看> 22222 < /查看> 
>       < / ScrollView > 
>       < /查看> 
>       <查看> 
>       {
>         显示 && ( 
>           <ScrollView  style = { {  width : '100%' ,  height : 400  } }  scrollY refresherEnabled  > < 
>             View > 11111 < / View > < 
>             View > 11111 < / View > < 
>             View > 11111 < / View > < 
>             View > 11111 < / View视图> 
>           < / ScrollView > 
>         )
>       } 
>       < / View > 
>       < Button  onClick = { ( )  =>  setShow ( ! show ) } > { show ? '隐藏' : '显示' } < / Button > 
>     < / View > 
>   ) 
> }
> ```
> 
> [增加视图 可以解决](https://docs.taro.zone/docs/optimized#1-%E5%88%A0%E9%99%A4%E6%A5%BC%E5%B1%82%E8%8A%82%E7%82%B9%E8%A6%81%E8%B0%A8%E6%85%8E%E5%A4%84%E7%90%86)
> 
> 解决方法将这个形式的 childNodes 改为对象形式，应该可以解决问题。

这样确实可以了，感谢！<Block>这个标签也是同样效果吗？我试了下是可以
