### ISSUE TITLE
taro3.4 打包h5 引入html5.css报错

### ISSUE THREAD

**Issue by adajoy** [NervJS/taro#11390]
### 相关平台
H5

### 复现仓库
[https://github.com/adajoy/taro-h5-build-error](https://github.com/adajoy/taro-h5-build-error)
**浏览器版本: chrome98**
**使用框架: React**

### 复现步骤
使用taro3.4初始化项目 在app.ts中import '@tarojs/taro/html5.css' 使用build:h5命令打包

### 期望结果
打包成功

### 实际结果
Module not found: Can't resolve '@tarojs/taro/html5.css'

### 环境信息
```
  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/react: 3.4.2 => 3.4.2 
      @tarojs/runtime: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
      react: ^17.0.0 => 17.0.2
```

**Comment by Chen-jj** [comment]
@adajoy 使用 require 代替 import 引入咯，在 H5 不需要这个样式文件。

```js
if (process.env.TARO_ENV !== 'h5') {
  require('@tarojs/taro/html5.css')
}
```

**Comment by yoyo837** [comment]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/6134547/172603282-846cd067-4fee-4f26-889e-7f72119e08df.png">


影响了nutui按钮颜色

**Comment by yoyo837** [comment]
应该是加载顺序的问题，
