### ISSUE TITLE
Taro Vue3 使用 Canvas 组件时无法触发对应的响应事件 （Taro版本3.4.2）

### ISSUE THREAD

**Issue by xiaohai2271** [NervJS/taro#11398]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/xiaohai2271/taro-vue3-canvas-issue-demo](https://github.com/xiaohai2271/taro-vue3-canvas-issue-demo)
**小程序基础库: 2.14.1**
**使用框架: Vue 3**

### 复现步骤
编译打开小程序。点击、长按小程序中的 canvas 组件，

### 期望结果
预期控制台输出打印对应的事件消息，

### 实际结果
实际并无相应的信息输出

### 环境信息
```
👽 Taro v3.4.2


  Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 17.4.0 - D:\Program\nodejs\node.EXE
      Yarn: 1.22.10 - D:\Program\nodejs\npm_global\yarn.CMD
      npm: 8.4.1 - D:\Program\nodejs\npm_global\npm.CMD

```

**Comment by Chen-jj** [comment]
@xiaohai2271 你的事件名写错了：

![image](https://user-images.githubusercontent.com/11807297/158013997-660824f7-f1f3-4b13-814f-df6e56a87ab8.png)

https://docs.taro.zone/docs/vue-overall#%E4%BA%8B%E4%BB%B6

**Comment by xiaohai2271** [comment]
@Chen-jj 非常感谢，确实是这个问题
