### ISSUE TITLE
英文版官方主页无法查看文档问题

### ISSUE THREAD

**Issue by CoulTuring** [NervJS/taro#114]
在https://taro.aotu.io/ 点击 docs 跳转至 github 项目主页，根本没有文档入口。

建议英文版官网提供一个进入文档的入口，哪怕跳转到 https://nervjs.github.io/taro/
毕竟英文版网站的访问量也很大。

**Comment by zacksleo** [comment]
英文版文档没必要吧, 国外开发小程序的不多啊

**Comment by kdong007** [comment]
擦 我还说taro文档怎么这么不好找呢。。。。 英文系统😢😢😢
