### ISSUE TITLE
taro3.4.2编译后在钉钉小程序开发工具里打开项目报错

### ISSUE THREAD

**Issue by 491467928** [NervJS/taro#11413]
### 相关平台
钉钉小程序

**使用框架: Vue 3**

### 复现步骤
新建一个项目，taro3.4.2 vue3 nutui,然后安装钉钉编译插件@tarojs/plugin-platform-alipay-dd，然后根据官方教程设置plugin，然后taro build --type dd，等编译好后，用钉钉小程序开发工具打开dist目录，在钉钉小程序的开发工具控制台里会出现报错，无法正常加载页面

Failed to compile
c:\mycode\t34\dist\vendors.js: Unexpected token (2331:124)
Please set enableNodeModuleBabelTransform to true or add "c:/mycode/t34/dist/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform

### 期望结果
正常运行

### 实际结果
报错

### 环境信息
```
 Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@491467928 3.4.3 没有复现:

![image](https://user-images.githubusercontent.com/11807297/158015270-350f7797-a96d-437e-8da6-735d3e33e47c.png)

**Comment by emaoxiongzhang** [comment]
> ### 相关平台
> 钉钉小程序
> 
> **使用框架: Vue 3**
> 
> ### 复现步骤
> 新建一个项目，taro3.4.2 vue3 nutui,然后安装钉钉编译插件@tarojs/plugin-platform-alipay-dd，然后根据官方教程设置plugin，然后taro build --type dd，等编译好后，用钉钉小程序开发工具打开dist目录，在钉钉小程序的开发工具控制台里会出现报错，无法正常加载页面
> 
> Failed to compile c:\mycode\t34\dist\vendors.js: Unexpected token (2331:124) Please set enableNodeModuleBabelTransform to true or add "c:/mycode/t34/dist/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform
> 
> ### 期望结果
> 正常运行
> 
> ### 实际结果
> 报错
> 
> ### 环境信息
> ```
>  Taro CLI 3.4.2 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
>       npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
> ```

请问解决了，我也是这个问题
啥也没干就按照了钉钉小程序插件，钉钉build了一下
`d:\Web\FrontEnd\*****\dist\vendors.js: Unexpected token (2331:124)
Please set enableNodeModuleBabelTransform to true or add "d:/Web/FrontEnd/*****/dist/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform`

**Comment by 491467928** [comment]
> @491467928 3.4.3 没有复现:
> 
> ![image](https://user-images.githubusercontent.com/11807297/158015270-350f7797-a96d-437e-8da6-735d3e33e47c.png)

3.4.3，只要是taro build --type dd ，这个问题依然存在，这个issue里和我是一样的问题[https://github.com/NervJS/taro/issues/11133](url)

**Comment by 491467928** [comment]
@Chen-jj 

3.4.3依然有这个问题，只要是用taro build --type [dd,参照这个issue里的问题](https://github.com/NervJS/taro/issues/11133)

**Comment by Chen-jj** [comment]
#11133
