### ISSUE TITLE
Taro 3 版本 Map组件无法触发onClick或onTap事件。 

### ISSUE THREAD

**Issue by sdn785618859** [NervJS/taro#11416]
### 相关平台
微信小程序

**小程序基础库: 2.22.0**
**使用框架: React**

### 复现步骤
1.代码如下： 
           <Map
                latitude={39.954548}
                longitude={116.186951}
                style={{ height: '100vh', width: '100vw' }}
                onClick={() => {
                    Taro.showToast({
                        title: 'title11',
                        icon: 'success',
                        duration: 2000
                    });
                }}
            >
            </Map>
2.微信开发者工具中第二次点击才可以触发事件，但返回的是上一次点击的结果，真机预览无法触发事件。

### 期望结果
可以正常触发onClick或onTap

### 实际结果
没有触发onClick或onTap

### 环境信息
```
 Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
```

**Comment by konka-king** [comment]
微信小程序 本人 亲测，开发者工具和真机 效果均正常，可以触发onClick 事件

**Comment by Chen-jj** [comment]
+1 没有复现，可以新建一个项目对比一下

**Comment by 1102712387** [comment]
我在3.4.3 版本也遇到了，楼主找到原因或解决方法了吗？

**Comment by 1102712387** [comment]
已找到解决方法 正确的用法：@tap="ontap"

期望结果

**Comment by zhEmail** [comment]
怎么解决的  我也遇到了同样的问题  只不过是第一次不生效 之后生效
