### ISSUE TITLE
编译出现 @tarojs/taro/html.css 找不到 taro 版本>=3.4.0 都有该问题，3.3.18没有问题

### ISSUE THREAD

**Issue by soeasyjx** [NervJS/taro#11415]
### 相关平台
H5

**浏览器版本: Chrome 99.0.4844.51（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
安装依赖 cnpm i
运行命令 npm run dev:h5

### 期望结果
编译正常

### 实际结果
 Failed to compile.

./src/pages/index/index.jsx
Module not found: Can't resolve '@tarojs/taro/html.css' in '/Users/jiangxin/test_project/taro/taro_demo1/src/pages/index'

### 环境信息
```
Taro v3.4.0


  Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v14.16.1/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.0 => 3.4.0 
      @tarojs/components: 3.4.0 => 3.4.0 
      @tarojs/mini-runner: 3.4.0 => 3.4.0 
      @tarojs/react: 3.4.0 => 3.4.0 
      @tarojs/runtime: 3.4.0 => 3.4.0 
      @tarojs/taro: 3.4.0 => 3.4.0 
      @tarojs/webpack-runner: 3.4.0 => 3.4.0 
      babel-preset-taro: 3.4.0 => 3.4.0 
      eslint-config-taro: 3.4.0 => 3.4.0 
      react: ^17.0.2 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.2.4
```

**Comment by Chen-jj** [comment]
duplicate #11390

**Comment by Chen-jj** [comment]
@soeasyjx 使用 require 代替 import 引入咯，在 H5 不需要这个样式文件。

```js
if (process.env.TARO_ENV !== 'h5') {
  require('@tarojs/taro/html.css')
}
```

**Comment by gitboyzcf** [comment]
> [@soeasyjx](https://github.com/soeasyjx) 使用 require 代替 import 引入咯，在 H5 不需要这个样式文件。
> 
> if (process.env.TARO_ENV !== 'h5') {
>   require('@tarojs/taro/html.css')
> }

```js
if (process.env.TARO_ENV !== "h5") {
  require('@tarojs/taro/html.css');
}

```

这样写在微信小程序中运行报错，会被编译成html.css.js是怎么回事
<img width="786" height="281" alt="image" src="https://github.com/user-attachments/assets/c9be147a-c1c6-4e94-94b0-b688cad38d30" />


"@tarojs/taro": "4.1.5",
"pinia": "^3.0.3",
"vue": "^3.0.0"
