### ISSUE TITLE
支付宝小程序键盘弹起输入时底部绝对定位元素也会跟着弹起

### ISSUE THREAD

**Issue by TheKonka** [NervJS/taro#11430]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/konka-king/alipay-pickerview](https://github.com/konka-king/alipay-pickerview)
**小程序基础库: 支付宝小程序开发者工具2.7.2版本**
**使用框架: React**

### 复现步骤
页面有Input 或者 Textarea 输入框，底部有一个fixed 定位元素，点击输入框弹起手机键盘，底部fixed定位元素也会跟着弹起

本人已测试支付宝小程序原生写法，没有出现此问题。

### 期望结果
底部fixed定位元素不弹起

### 实际结果
底部fixed定位元素弹起

### 环境信息
```
👽 Taro v3.4.3


  Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.3.0 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/components: 3.4.3 => 3.4.3 
      @tarojs/mini-runner: ^3.4.3 => 3.4.3 
      @tarojs/react: 3.4.3 => 3.4.3 
      @tarojs/runtime: 3.4.3 => 3.4.3 
      @tarojs/taro: 3.4.3 => 3.4.3 
      @tarojs/webpack-runner: 3.4.3 => 3.4.3 
      babel-preset-taro: 3.4.3 => 3.4.3 
      eslint-config-taro: 3.4.3 => 3.4.3 
      react: ^17.0.0 => 17.0.2 
```

**Comment by konka-king** [comment]
![Screenshot_20220311-094602](https://user-images.githubusercontent.com/22173084/157786184-50284d6d-2d19-4685-a126-7cc8d1fb54ca.png)
![Screenshot_20220311-094609](https://user-images.githubusercontent.com/22173084/157786243-fc965541-5297-4b2d-88fd-3513ac96cd26.png)

**Comment by TheKonka** [comment]
给 `input` 组件加上 `enableNative` 属性即可解决
