### ISSUE TITLE
自定义tabbar无法使用

### ISSUE THREAD

**Issue by maopixin** [NervJS/taro#11437]
### 相关平台
微信小程序

**小程序基础库: 2.22.1**
**使用框架: Vue 2**

### 复现仓库
[https://github.com/maopixin/taro-tab-bar](https://github.com/maopixin/taro-tab-bar)

### 复现步骤
自定义tabbar，打包以后custom-tab-bar目录下没有index.wxml
然后自定义tabbar就无法生效

### 期望结果
自定义tabbar正常加载

### 实际结果
自定义tabbar没有加载

### 环境信息
```
👽 Taro v3.4.3


  Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.24.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.3 => 3.4.3 
      @tarojs/mini-runner: 3.4.3 => 3.4.3 
      @tarojs/runtime: 3.4.3 => 3.4.3 
      @tarojs/taro: 3.4.3 => 3.4.3 
      @tarojs/webpack-runner: 3.4.3 => 3.4.3 
      babel-preset-taro: 3.4.3 => 3.4.3 
      eslint-config-taro: 3.4.3 => 3.4.3 
```

---
### 补充信息
3.4.2版本可以正常使用
而且使用.vue文件定义tabbar不行
于是我使用wxml文件定义，然后3.4.2可用
升级到3.4.3后 就无法使用了

定义tabbar
![定义tabbar](https://user-images.githubusercontent.com/30068481/157852827-d573d286-02c3-4690-b2d4-49b0e9f8970a.png)

3.4.2打包后
![3.4.2打包后](https://user-images.githubusercontent.com/30068481/157852593-f173512b-1b61-4308-a59e-044ec253fb42.png)

3.4.3打包后
![3.4.3打包后](https://user-images.githubusercontent.com/30068481/157852659-a8673804-aef0-4d86-8465-50b26bad20f7.png)

**Comment by IDCjaja** [comment]
vue 文件定义的自定义 tabbar 可以实现了吗

**Comment by maopixin** [comment]
> vue 文件定义的自定义 tabbar 可以实现了吗

没有尝试，我在3.4.2版本先用的vue方式的，但是没有成功。
这个tabbar非常麻烦，不想再搞了，你可以试试，反正3.4.4 wxml方式是可以的。
