### ISSUE TITLE
【feature】希望Taro提供H5的getLocation功能

### ISSUE THREAD

**Issue by Ghewww** [NervJS/taro#11431]
### 这个特性解决了什么问题？
通过代码和文档发现目前H5不支持getLocation API，不清楚目前没有支持的原因，希望支持。
代码如下：https://github.com/NervJS/taro/blob/next/packages/taro-h5/src/api/location/index.ts#L15

### 这个 API 长什么样？
与小程序一样，支持Taro.getLocation({})调用

**Comment by SyMind** [comment]
@ZakaryCode 我也有这个问题，为什么位置相关的方法，在h5中仅支持微信公众号？我们看起来是可以对其进行支持的。

**Comment by SyMind** [comment]
@Ghewww 如有时间的话，欢迎pr。

**Comment by FE92star** [comment]
> 

事实上h5原生的[Geolocation](https://developer.mozilla.org/zh-CN/docs/Web/API/Geolocation)对象就支持获取设备地理位置，相当于要把这个h5对象调用集成到Taro.getLocation的API中

**Comment by tourze** [comment]
如果能提供一个在运行时覆盖Taro自带API的办法，这种问题就没那么多咯

**Comment by SyMind** [comment]
@tourze 或许可以说一说你具体的想法。

**Comment by Ghewww** [comment]
@SyMind 好~感谢提醒

**Comment by tourze** [comment]
> @tourze 或许可以说一说你具体的想法。

例如：
```js
import Taro from '@tarojs/taro';

Taro.getLocation = console.error;
Taro.login = () => {
    console.warn('H5环境不支持login方法')
};

```
现在 @tarojs/taro 导出的对象是不能修改的

**Comment by ZakaryCode** [comment]
> @ZakaryCode 我也有这个问题，为什么位置相关的方法，在h5中仅支持微信公众号？我们看起来是可以对其进行支持的。

早期实现，已经不可考 😂
确实是可以新增一下支持

**Comment by ZakaryCode** [comment]
> 如果能提供一个在运行时覆盖Taro自带API的办法，这种问题就没那么多咯

其实直接覆盖就行，不过通过 Taro 插件覆盖 H5 提供的 API 目前还不支持，后续可以考虑

**Comment by CaiDingxian** [comment]
巧了，我也遇到这个问题，已提交PR
