### ISSUE TITLE
3.4.3 使用 @tarojs/plugin-react-devtools 插件 会导致  usePullDownRefresh 报错

### ISSUE THREAD

**Issue by wreido** [NervJS/taro#11449]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/wreido/issu-test](https://github.com/wreido/issu-test)
**小程序基础库: 2.10.4**
**使用框架: React**

### 复现步骤
使用 @tarojs/plugin-react-devtools 插件 就会出现

### 期望结果
@tarojs/plugin-react-devtools 插件 不会导致 usePullDownRefresh报错

### 实际结果
使用@tarojs/plugin-react-devtools 插件  usePullDownRefresh报错

### 环境信息
```
Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.6.3
```

**Comment by Chen-jj** [comment]
duplicate #11235

Taro v3.5 修复
