### ISSUE TITLE
怎么实现，只编译对应坏境的文件

### ISSUE THREAD

**Issue by shijunti19** [NervJS/taro#11444]
### 这个特性解决了什么问题？
项目文件的大小和多端代码杂乱问题

### 这个 API 长什么样？
可不可以实现这种需求
index文件夹下index.tt.vue和index.weapp.vue，我按照坏境分类命名文件，然后生成微信小程序就只编译index.weapp.vue，抖音小程序就只编译index.weapp.vue，从而实现对应客户端的文件大大缩小了，目前是一大堆的if判断来实现多端。杂乱无章

**Comment by konka-king** [comment]
https://docs.taro.zone/docs/envs
