### ISSUE TITLE
image 编译成 react-native   不支持base64 图片么？

### ISSUE THREAD

**Issue by supermaverickws** [NervJS/taro#11456]
### 这个特性解决了什么问题？
image 编译成 react-native   不支持base64 图片么？

**Comment by zhiqingchen** [comment]
需要提供更多信息。rn是支持base64图片的

**Comment by supermaverickws** [comment]
const ImageBase64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAAAwCAIAAABSYzXUAAAOf0lEQVR42u1aC0xUVxomrK6uxhCNxqa1qZHUjWYbu20aGxuN2dTU2BhXt812N200ur0IAkURQcAHReRdxOHhDDMMr2FgGGZgYJgHzAwvARmRh1brC2mLj/pWfFRU3O9yxjO34wh3xsqa7JycTM4993B0vu/+//f9545Xvae9As3LA4GHBk/z0OChwdNeCg11NXWKVEXu5lwhI5QES0qTSmuraj3gjikNNSU1khBJuaDcUGnAJQhQZakwo5VpPfiOEQ2IAyCuK9M5zBvUBsx7YmKMaEAuQhw4vYWYKI4r9kA8FjRAD0guerYhFKATHojHggZostt3X83WVFfXJxDcCQt7wjD3QkN/3LcPM2NNg17fUlLSbbE0/H9GAxC/GRV1NSamQ6XC2FpZeTk2diA8/GUz4UhDVlYvwzwJCfl1795LMtlRk6nx/0obEAfgwGESTCAmxpQGgaAvIOARmCDd1/+Ut1/HnwI63tjSviim7W9xbeszWgo0jQ5OSa/SO+xj1Bjddkq15oakip4IxYlPJRcWHbg6OenhhMTHC7OvFevbXDbTpWmijeNFARMlITNksYuV6V/py7NHWI9chDhwmGzXaJCdnK7vqkl7LBr/SDTxV8mMK7LFfcqvjuizfx9tQATI5T0pKf1fbLrlxRx+tk8MsKr1Dc/WDYCe5CJ1tpp/3WC21GdUde5QHl+Ve36x8MqkpEde8U+844dmpd1bKrq8trDvnYybmBmf8HhqymCBrt2lryeLXSJkvIC+xWLWKTMU330mDvLJ2+arkUY5XY9Hr9lodJhsNJkw73T9ZdmSJ0IvoF9vMXfqMvoVnw2KfQbyfI9ron43if40sQ2gb4/rXx147VPm1nLm5izmFGFidVwXzVfAETEhT5DTKhq5iE8cfFt+bPa+O0AcKE9PfQAOPs/7eafy+wPVHdiTtnDFD1iAaMDn+1nX+X83QI9QAA0Gtdg+aapVCwMlwdMKts8zagpfKBosZoQCaDhssO/fYKk9ow58IJl2u2DeIWPhi9IAICZtOjw9xEouER+pqT/P9D9mCwimKzBoMC7ul83p3d5+h1/b3L50T9s6QcueouYKPV95/6bkNJBdI+1HFhphmbTGimUfZF1DakKs8KfBoBKBA2noLCffrk5XmrQyZ9MkrTzZbW3oMIjAwT2pk/2bzLoLpSsf5Uzq1ia/EA0JxU2AG+DaA7yqkeYlb6bjP8wQxGMe04dL3+BjCyO734lsH7/RissZIVaTZfR/G0898EX2d3pXpO1AcCAjjUtgw4V0pCb+NCDzgIaSxBUkMuR7l8kTliM10QUV4lDRxnE6xX6uU7odEUGcEnIR4gAc3N261alTQuYBDRdLVpDIuCRfdlG+HKmJLjhZETokGtep2+8+DZ991wpAIch05t/7WikNH+5uKyvrTE/v8/HrweXnzH1Q4u//+IMQW9YCi3yQwtMNlCtqD2K8X9OZXNFNb0EJKPru0VCavAo0EBnQyuIxJh1abdJXkDVKwVpJ8FSTscqhbgD0pG74KS3teW71fOkq0EBk4Kg2HmPSodUHTbb9+5RrByVTm01VbtLgu+0Q0IyXNdOZWaHtlIYQEQtcoaYB4zdDrfBXkZG3wMRc5hxZsCTknFh8Sqsdxdt8nPMLwMWnb/oAAXp90Tlya4Xkok/yICUDhME4SbRW/jQU7V5IhUGRsoZwAMuEz9zNM4kwIEqQtaDhbtiba0ULqTD0K9YQDmCZ2M/cmTZhsJiRtVgNd4MGfV09QVNXZ8vaxdUNXLNEPGugsAXjL9NtEQPQZ4d0kQW+TC+xvGFhd0CSStXhtCQErMQa0Q7FLjW0EQHH5etp9/EZWnrSbHEZphz/Ccg5ABrj/PC3CQ35kfOrixMg3WDCVMt6OXW2P+wTWeZSe5wzATmnfvgPB/LfJjTcyp/fU50A6QYTTSZ2/7Nqf9in+hH3d04DggBQzg6zu8MoaTPlAIJMJj/YxVqp7HJb/oEeQK7JmgXbuqKjbyBN0RIEJWFi4oWiomMOJSGYgF8iiM8X3MIAJpUlta6JcrOl9JSrGBkq8wB6QdQ7w4KspxlJ6OeN+NBIIzEuz1hPlXzkeuLZ1m7IA+g3C9j9G816mpGGhN6IjxOaSIzPla+nSj5yPeGcBkgCoFy2t5XOLE+wC8OKxDYC+riNh6cG27MEbBJdg0KPLe7qmvLzj6MgDwx8SPkAN7Gxl/PyTuj1duGBMJgsDXCrAB0JikzOSb9DaFgivOwqDZr8HQBXkbIa4+qiPXYaGC8YpOI9S8EHPOtwXjJhUi0Mcmn/45odAPe8gt3/WPUeSgM6DNLl4qXgA5512MKaMHlaHeQyDQARUG4RH6Qz8yMPUYi/LWQFY0d+M6XkaZ1hp8o/u8Xx2EPRlZb209atdykffn5DO3dez84+q9HYwotGgM7ERthq6XlyCavqKg3wRQC3qvBbjGGWKAd5EXN1ykwkK5YP/wlPjyC9QIxL+8MXAdxjVez+MEuUg9t5c4/oMpGsMEbWslWFQi8Q4zINcyMc9XmCv10YSrVsVvkops1hzetbrHSNSPVcpwTQs7J6iaTTDnpAUklJ99z9rFbHq49SeSAd/tUlmCQh0wEuLBCSPh5/SoMq82vcLc/YgDHIoNEAqXBp/weS6QCXtUAWMx5/SkOvit2/t3wDm6BE42g0QCpcpmFigJXqMGk06aNDLZW6Rsz4BFmpcoIbumDmZl5+pqamVSQ6jQTFlZC/bmerhH/sv2IwHERMUBoiy07wxwguiH3wt81hI0yexM1I0Aw2oxqrhhf4DquIlFLCs8EFAdk7eez+PdokbkaCZmAS9GA8kMfubzVIKSWu0YCkDzRrTfYZVGQUZVzCHTlUFSRHkY4Kw6UnC6JdWPh9Skp/cPCDZSEs6L5RLCUREbffSHxAaFguvsh/Q9Rlw8KwxiEj0YoaIYJL+d6PqYqg898fdRmQhUl1yEj2itpixuUv8o+piqC7SQN35p9p9rwPa4Rqed72di5PRE5Iz6tsdPvIN7usB6DPjHsE5QATf460RYPv3kGoPQKIzyasAjNe1UVxwxlpMqWB1gfQjOEFe1gVSVjO1Qk+DYkesB6tjgPcD3MmUxpofQDNYJWjmt0fpTVXJ1ygAVnFgQYUEDBOQB8iMWdb+zpBi77uN3epeEBXeH4ZJLR0TZdDQQC/RDQZLgtu6l+J1wkNf4yzZa2oqJuo3uXyHix4bsUAMfDztqAukCdzMxIp2eBQUTnLYhbZVCR4GhsoYW/xpwFiACPUYKnt1iZzMxIp2eBQUTlflS16qiLTcOuu9C2XaVgSyz7aUt4P9deZLTQUvhEd5PMnKAVmpP4KfOcJbhfqfsMc99ACPBEaxsUPORQiMMExMVdhtJTKI9xahNQBhdHvsoqVtJJyULjzPUgCJBq1W9HuD8117K9JdMoMcpckKD6N1AE3Ctn9L5SupBzcKHwPkgCJRu12tejDJjO7f6cug9wlCco1GgAlAF2TwisDlOsaJm2yV3bcTPW8FlB8BshOTnpI/WiQ/LStgDc1YubNtLs2sTU32mhIGCKFCFQEnio8fIBrtCAqqA0RPchaqgMBtDRjx37eBGhx4BToMOghLpY01HfkbmVuOE8azqgCaGmGMcKCAP1QPAU6DHqIiyUN9R25+0NluMs0aIwNqMugEKOeWiOlvBttLynSSkc/0cuuPkKAVte2fHTgCvVC72ddVxpbNxT1YrxDeZwbHOgInWeNr0RyErXh5s33uZSkBPydNaACORESkprgl4yaAu6JhcVkJLUFEQZysMFLGIZf9aA4oC8YkJrgl9qNBdwTi0aLkdQWRBjIwYbLR3sAFDSgIhv5/8RV5jBJM5+vAQIAa4K6x3Zwoj76buYN7/gh9CnJD1EwJ1X0cGkmNCzLuTTCnshLmZnndu26hkyVxfgA2WgmdSNzPzT0HokS2F/u66DK3Ai4Jrt0C9byFwaiyYgDAP2c903mE5URcE0c6V7r/tu3ZHnTlEArXKnTYzWUDjQOQFiktJnn1/hEfAmwMrKzfBaHlp4kNIi1h/m9cWuQbLPlmWy/yXEMs42p3MgMDGvJg8RdJlFMqPib17i6jUKP6ATPdit/vu3QQjQR2gC/RGQA6B82iKENqNS4uo1Cz7bAPRoI1otj22Cc1gpaSGGM1J9a0gTZoNZoQfQhlxwqchGe+klJjxSG0bXnLxnsYd8X+T+59DOAYYleIN/7SV70EmHQ7Gy/SQeY8VzouV2dn+qSpe6qSWMP9QoXXCr5BHYITz34IKcXTntPdcILvYu265imETS8t/MQpBjFMzrKbNQNK5NaM5VN9a63/ZpO0EDk4XlrRNqOBZnsqzeeccNtMEXwrPTdDmnVmvqcPVsdOIhhohEoyF0o5oXCM2VlnUbj6GENUwTPSt/t2MTArD9bzjhwMOqbBhdoeBlNWmP1TR/wSR70Lz4LZSYygMnd5d+vyj0/J/0OfNQaab8bP4oh5xOgQRo2e7iCM9EfA+iUmbLYxU9PvP+QGb0VVQj39JccOIIVKD+ssEx21CkrVoMUNNyRzkZGani6P7Qaun1FtpieePeWb3jRnwSMTYtTHSU/ioE+w7bCDuHyy4IfUyu73XjPw211OqVSsA41mjjIh/w+Y/jgaDyUAEygeqitUdDFKlVHbu4PSUnnIyJuc0sT0sEKChS4ZKzBSlI2ttYpzynXISkNin3I7zNYRyQaDyUAE1CI1loF///t/5iGV7ChEqystMIKp6b+vHPnde6P52iHRUYtiTwGewZuFIourbZt1F84emhwv8F6gZWiomNZWb3IVAgXp8TQwh6hA4awMiHhYnp6n0DQJxafAlXcjq3gsD00vGjDs48IyM8/DqABN3BHfDybzUbo+/b96KHhZTXoeVXVITCEghFPPVIWoiElpR9UcTtkBuHloeGVax4aPDR4mocGDw2e5qHhlWz/BchZWz/GCLenAAAAAElFTkSuQmCC"


布局
<Image src={ImageBase64} />

报错
![image](https://user-images.githubusercontent.com/61172354/158514891-49ba0a33-55c8-4768-8b5d-080696d7f897.png)

**Comment by supermaverickws** [comment]
@zhiqingchen 
3.4.2 版
"@tarojs/taro-rn": "3.4.2",

**Comment by supermaverickws** [comment]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/61172354/158516259-bebd2527-7671-44a3-be76-72fd756c91c0.png">

@zhiqingchen

**Comment by zhiqingchen** [comment]
尝试了下，是可以的
```
import { Image } from "@tarojs/components";
const ImageBase64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAAAwCAIAAABSYzXUAAAOf0lEQVR42u1aC0xUVxomrK6uxhCNxqa1qZHUjWYbu20aGxuN2dTU2BhXt812N200ur0IAkURQcAHReRdxOHhDDMMr2FgGGZgYJgHzAwvARmRh1brC2mLj/pWfFRU3O9yxjO34wh3xsqa7JycTM4993B0vu/+//f9545Xvae9As3LA4GHBk/z0OChwdNeCg11NXWKVEXu5lwhI5QES0qTSmuraj3gjikNNSU1khBJuaDcUGnAJQhQZakwo5VpPfiOEQ2IAyCuK9M5zBvUBsx7YmKMaEAuQhw4vYWYKI4r9kA8FjRAD0guerYhFKATHojHggZostt3X83WVFfXJxDcCQt7wjD3QkN/3LcPM2NNg17fUlLSbbE0/H9GAxC/GRV1NSamQ6XC2FpZeTk2diA8/GUz4UhDVlYvwzwJCfl1795LMtlRk6nx/0obEAfgwGESTCAmxpQGgaAvIOARmCDd1/+Ut1/HnwI63tjSviim7W9xbeszWgo0jQ5OSa/SO+xj1Bjddkq15oakip4IxYlPJRcWHbg6OenhhMTHC7OvFevbXDbTpWmijeNFARMlITNksYuV6V/py7NHWI9chDhwmGzXaJCdnK7vqkl7LBr/SDTxV8mMK7LFfcqvjuizfx9tQATI5T0pKf1fbLrlxRx+tk8MsKr1Dc/WDYCe5CJ1tpp/3WC21GdUde5QHl+Ve36x8MqkpEde8U+844dmpd1bKrq8trDvnYybmBmf8HhqymCBrt2lryeLXSJkvIC+xWLWKTMU330mDvLJ2+arkUY5XY9Hr9lodJhsNJkw73T9ZdmSJ0IvoF9vMXfqMvoVnw2KfQbyfI9ron43if40sQ2gb4/rXx147VPm1nLm5izmFGFidVwXzVfAETEhT5DTKhq5iE8cfFt+bPa+O0AcKE9PfQAOPs/7eafy+wPVHdiTtnDFD1iAaMDn+1nX+X83QI9QAA0Gtdg+aapVCwMlwdMKts8zagpfKBosZoQCaDhssO/fYKk9ow58IJl2u2DeIWPhi9IAICZtOjw9xEouER+pqT/P9D9mCwimKzBoMC7ul83p3d5+h1/b3L50T9s6QcueouYKPV95/6bkNJBdI+1HFhphmbTGimUfZF1DakKs8KfBoBKBA2noLCffrk5XmrQyZ9MkrTzZbW3oMIjAwT2pk/2bzLoLpSsf5Uzq1ia/EA0JxU2AG+DaA7yqkeYlb6bjP8wQxGMe04dL3+BjCyO734lsH7/RissZIVaTZfR/G0898EX2d3pXpO1AcCAjjUtgw4V0pCb+NCDzgIaSxBUkMuR7l8kTliM10QUV4lDRxnE6xX6uU7odEUGcEnIR4gAc3N261alTQuYBDRdLVpDIuCRfdlG+HKmJLjhZETokGtep2+8+DZ991wpAIch05t/7WikNH+5uKyvrTE/v8/HrweXnzH1Q4u//+IMQW9YCi3yQwtMNlCtqD2K8X9OZXNFNb0EJKPru0VCavAo0EBnQyuIxJh1abdJXkDVKwVpJ8FSTscqhbgD0pG74KS3teW71fOkq0EBk4Kg2HmPSodUHTbb9+5RrByVTm01VbtLgu+0Q0IyXNdOZWaHtlIYQEQtcoaYB4zdDrfBXkZG3wMRc5hxZsCTknFh8Sqsdxdt8nPMLwMWnb/oAAXp90Tlya4Xkok/yICUDhME4SbRW/jQU7V5IhUGRsoZwAMuEz9zNM4kwIEqQtaDhbtiba0ULqTD0K9YQDmCZ2M/cmTZhsJiRtVgNd4MGfV09QVNXZ8vaxdUNXLNEPGugsAXjL9NtEQPQZ4d0kQW+TC+xvGFhd0CSStXhtCQErMQa0Q7FLjW0EQHH5etp9/EZWnrSbHEZphz/Ccg5ABrj/PC3CQ35kfOrixMg3WDCVMt6OXW2P+wTWeZSe5wzATmnfvgPB/LfJjTcyp/fU50A6QYTTSZ2/7Nqf9in+hH3d04DggBQzg6zu8MoaTPlAIJMJj/YxVqp7HJb/oEeQK7JmgXbuqKjbyBN0RIEJWFi4oWiomMOJSGYgF8iiM8X3MIAJpUlta6JcrOl9JSrGBkq8wB6QdQ7w4KspxlJ6OeN+NBIIzEuz1hPlXzkeuLZ1m7IA+g3C9j9G816mpGGhN6IjxOaSIzPla+nSj5yPeGcBkgCoFy2t5XOLE+wC8OKxDYC+riNh6cG27MEbBJdg0KPLe7qmvLzj6MgDwx8SPkAN7Gxl/PyTuj1duGBMJgsDXCrAB0JikzOSb9DaFgivOwqDZr8HQBXkbIa4+qiPXYaGC8YpOI9S8EHPOtwXjJhUi0Mcmn/45odAPe8gt3/WPUeSgM6DNLl4qXgA5512MKaMHlaHeQyDQARUG4RH6Qz8yMPUYi/LWQFY0d+M6XkaZ1hp8o/u8Xx2EPRlZb209atdykffn5DO3dez84+q9HYwotGgM7ERthq6XlyCavqKg3wRQC3qvBbjGGWKAd5EXN1ykwkK5YP/wlPjyC9QIxL+8MXAdxjVez+MEuUg9t5c4/oMpGsMEbWslWFQi8Q4zINcyMc9XmCv10YSrVsVvkops1hzetbrHSNSPVcpwTQs7J6iaTTDnpAUklJ99z9rFbHq49SeSAd/tUlmCQh0wEuLBCSPh5/SoMq82vcLc/YgDHIoNEAqXBp/weS6QCXtUAWMx5/SkOvit2/t3wDm6BE42g0QCpcpmFigJXqMGk06aNDLZW6Rsz4BFmpcoIbumDmZl5+pqamVSQ6jQTFlZC/bmerhH/sv2IwHERMUBoiy07wxwguiH3wt81hI0yexM1I0Aw2oxqrhhf4DquIlFLCs8EFAdk7eez+PdokbkaCZmAS9GA8kMfubzVIKSWu0YCkDzRrTfYZVGQUZVzCHTlUFSRHkY4Kw6UnC6JdWPh9Skp/cPCDZSEs6L5RLCUREbffSHxAaFguvsh/Q9Rlw8KwxiEj0YoaIYJL+d6PqYqg898fdRmQhUl1yEj2itpixuUv8o+piqC7SQN35p9p9rwPa4Rqed72di5PRE5Iz6tsdPvIN7usB6DPjHsE5QATf460RYPv3kGoPQKIzyasAjNe1UVxwxlpMqWB1gfQjOEFe1gVSVjO1Qk+DYkesB6tjgPcD3MmUxpofQDNYJWjmt0fpTVXJ1ygAVnFgQYUEDBOQB8iMWdb+zpBi77uN3epeEBXeH4ZJLR0TZdDQQC/RDQZLgtu6l+J1wkNf4yzZa2oqJuo3uXyHix4bsUAMfDztqAukCdzMxIp2eBQUTnLYhbZVCR4GhsoYW/xpwFiACPUYKnt1iZzMxIp2eBQUTlflS16qiLTcOuu9C2XaVgSyz7aUt4P9deZLTQUvhEd5PMnKAVmpP4KfOcJbhfqfsMc99ACPBEaxsUPORQiMMExMVdhtJTKI9xahNQBhdHvsoqVtJJyULjzPUgCJBq1W9HuD8117K9JdMoMcpckKD6N1AE3Ctn9L5SupBzcKHwPkgCJRu12tejDJjO7f6cug9wlCco1GgAlAF2TwisDlOsaJm2yV3bcTPW8FlB8BshOTnpI/WiQ/LStgDc1YubNtLs2sTU32mhIGCKFCFQEnio8fIBrtCAqqA0RPchaqgMBtDRjx37eBGhx4BToMOghLpY01HfkbmVuOE8azqgCaGmGMcKCAP1QPAU6DHqIiyUN9R25+0NluMs0aIwNqMugEKOeWiOlvBttLynSSkc/0cuuPkKAVte2fHTgCvVC72ddVxpbNxT1YrxDeZwbHOgInWeNr0RyErXh5s33uZSkBPydNaACORESkprgl4yaAu6JhcVkJLUFEQZysMFLGIZf9aA4oC8YkJrgl9qNBdwTi0aLkdQWRBjIwYbLR3sAFDSgIhv5/8RV5jBJM5+vAQIAa4K6x3Zwoj76buYN7/gh9CnJD1EwJ1X0cGkmNCzLuTTCnshLmZnndu26hkyVxfgA2WgmdSNzPzT0HokS2F/u66DK3Ai4Jrt0C9byFwaiyYgDAP2c903mE5URcE0c6V7r/tu3ZHnTlEArXKnTYzWUDjQOQFiktJnn1/hEfAmwMrKzfBaHlp4kNIi1h/m9cWuQbLPlmWy/yXEMs42p3MgMDGvJg8RdJlFMqPib17i6jUKP6ATPdit/vu3QQjQR2gC/RGQA6B82iKENqNS4uo1Cz7bAPRoI1otj22Cc1gpaSGGM1J9a0gTZoNZoQfQhlxwqchGe+klJjxSG0bXnLxnsYd8X+T+59DOAYYleIN/7SV70EmHQ7Gy/SQeY8VzouV2dn+qSpe6qSWMP9QoXXCr5BHYITz34IKcXTntPdcILvYu265imETS8t/MQpBjFMzrKbNQNK5NaM5VN9a63/ZpO0EDk4XlrRNqOBZnsqzeeccNtMEXwrPTdDmnVmvqcPVsdOIhhohEoyF0o5oXCM2VlnUbj6GENUwTPSt/t2MTArD9bzjhwMOqbBhdoeBlNWmP1TR/wSR70Lz4LZSYygMnd5d+vyj0/J/0OfNQaab8bP4oh5xOgQRo2e7iCM9EfA+iUmbLYxU9PvP+QGb0VVQj39JccOIIVKD+ssEx21CkrVoMUNNyRzkZGani6P7Qaun1FtpieePeWb3jRnwSMTYtTHSU/ioE+w7bCDuHyy4IfUyu73XjPw211OqVSsA41mjjIh/w+Y/jgaDyUAEygeqitUdDFKlVHbu4PSUnnIyJuc0sT0sEKChS4ZKzBSlI2ttYpzynXISkNin3I7zNYRyQaDyUAE1CI1loF///t/5iGV7ChEqystMIKp6b+vHPnde6P52iHRUYtiTwGewZuFIourbZt1F84emhwv8F6gZWiomNZWb3IVAgXp8TQwh6hA4awMiHhYnp6n0DQJxafAlXcjq3gsD00vGjDs48IyM8/DqABN3BHfDybzUbo+/b96KHhZTXoeVXVITCEghFPPVIWoiElpR9UcTtkBuHloeGVax4aPDR4mocGDw2e5qHhlWz/BchZWz/GCLenAAAAAElFTkSuQmCC"


          <Image src={ImageBase64} />
```

**Comment by supermaverickws** [comment]
@zhiqingchen  外面嵌套层 Form 试试？我嵌套Form 就不能了
`<Form><Image src={ImageBase64} /></Form>`

**Comment by zhiqingchen** [comment]
> @zhiqingchen 外面嵌套层 Form 试试？我嵌套Form 就不能了 `<Form><Image src={ImageBase64} /></Form>`

那是 Form 组件的问题，后续修复

**Comment by supermaverickws** [comment]
@zhiqingchen 
rn 的  Form 下 会调用 deppDiveIntoChildren 方法里的  React.cloneElement(child, { ...child.props }, this.deppDiveIntoChildren(child.props.children))
而 React.cloneElement 方法第三个参数是 children.
第三参数最终调用的 React.Children.toArray(children) 传入null 的话会返回空 的 数据对象
![image](https://user-images.githubusercontent.com/61172354/158533002-91d09a63-1339-41b7-9471-031fc2f9090c.png)

![image](https://user-images.githubusercontent.com/61172354/158533272-9fa09969-c4d7-4880-bdf4-6a20ca5c81c4.png)

![image](https://user-images.githubusercontent.com/61172354/158533488-94e5bfac-3373-4d17-b854-d97c86a4ab16.png)

**Comment by supermaverickws** [comment]
@zhiqingchen 好的。修复完毕的话。你可以关闭此提问。谢谢。
