### ISSUE TITLE
ios Input build 模式下中文输入异常

### ISSUE THREAD

**Issue by maodapeng1** [NervJS/taro#1146]
**问题描述**
ios Input build 模式下中文输入异常,dev模式没问题

**复现步骤**
[复现问题的步骤]

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.7]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by maodapeng1** [comment]
ios 9下还存在异常情况

系统信息

操作系统: [e.g. ios.9]
Taro 版本 [e.g. v.1.1.7]
Node.js 版本 [e.g. v11.0.0]
报错平台 [h5]

**Comment by jinjinjin0731** [comment]
ios Input build 没有问题。  ios9 你已经录了视频给我看了下~ 我排查到原因后 艾特你

**Comment by jinjinjin0731** [comment]
更新到最新版看下？

**Comment by jinjinjin0731** [comment]
无人回复关了。 有问题再提个新 issue 咯
