### ISSUE TITLE
Taro v3.3.19 build H5 设置env development编译报错

### ISSUE THREAD

**Issue by WilsonLau0755** [NervJS/taro#11467]
### 相关平台
H5

**浏览器版本: chrome**
**使用框架: Vue 3**

### 复现步骤
1、taro init初始化项目，选择Gitee中获取的默认模板进行项目初始化
2、在项目中taro build --type h5 --env development进行项目编译

### 期望结果
正常完成项目编译

### 实际结果
🙅   Failed to compile.

js/app.js from Terser
TypeError: t.replace is not a function
    at Array.forEach (<anonymous>)

### 环境信息
```
  Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.11.1 - C:\nvm\nodejs\node.EXE
      npm: 8.0.0 - C:\nvm\nodejs\npm.CMD

```

---
### 补充信息
仅编译H5时加上--env development会报错。

**Comment by wuhuaizai** [comment]
同样遇到了这个问题

**Comment by wuhuaizai** [comment]
> ### 相关平台
> H5
> 
> **浏览器版本: chrome** **使用框架: Vue 3**
> 
> ### 复现步骤
> 1、taro init初始化项目，选择Gitee中获取的默认模板进行项目初始化 2、在项目中taro build --type h5 --env development进行项目编译
> 
> ### 期望结果
> 正常完成项目编译
> 
> ### 实际结果
> 🙅 Failed to compile.
> 
> js/app.js from Terser TypeError: t.replace is not a function at Array.forEach ()
> 
> ### 环境信息
> ```
>   Taro CLI 3.3.19 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Node: 16.11.1 - C:\nvm\nodejs\node.EXE
>       npm: 8.0.0 - C:\nvm\nodejs\npm.CMD
> ```
> 
> ### 补充信息
> 仅编译H5时加上--env development会报错。

找到解决方法了，config下的配置文件里把env相关配置去掉就可以了，真累，debug完全靠猜。

**Comment by gezichenshan** [comment]
@wuhuaizai 尝试去掉env了也依然报同样的错误。

**Comment by WilsonLau0755** [comment]
> > ### 相关平台
> > H5
> > **浏览器版本: chrome** **使用框架: Vue 3**
> > ### 复现步骤
> > 1、taro init初始化项目，选择Gitee中获取的默认模板进行项目初始化 2、在项目中taro build --type h5 --env development进行项目编译
> > ### 期望结果
> > 正常完成项目编译
> > ### 实际结果
> > 🙅 Failed to compile.
> > js/app.js from Terser TypeError: t.replace is not a function at Array.forEach ()
> > ### 环境信息
> > ```
> >   Taro CLI 3.3.19 environment info:
> >     System:
> >       OS: Windows 10
> >     Binaries:
> >       Node: 16.11.1 - C:\nvm\nodejs\node.EXE
> >       npm: 8.0.0 - C:\nvm\nodejs\npm.CMD
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 补充信息
> > 仅编译H5时加上--env development会报错。
> 
> 找到解决方法了，config下的配置文件里把env相关配置去掉就可以了，真累，debug完全靠猜。

完全去掉env里面的配置？是将config -> dev.js 和 prod.js中的env下面的配置删掉吗？那不就没有了环境变量？没有环境变量那要--dev development这个命令干啥，直接npm run build:h5本来就能运行成功。
