### ISSUE TITLE
相同路由间跳转有bug

### ISSUE THREAD

**Issue by liuzeyuwjy** [NervJS/taro#11468]
### 相关平台
H5

### 复现仓库
[https://gitlab.devops.cmft/grds/front/jinke/micro-base.git](https://gitlab.devops.cmft/grds/front/jinke/micro-base.git)
**浏览器版本: chrome、任意浏览器**
**使用框架: React**

### 复现步骤
首先访问页面A（/modules/pages/goodsDetail/goodsDetail?skuWareCode=111），在A页面内跳转相同路径的页面B（/modules/pages/goodsDetail/goodsDetail?skuWareCode=222），此时白屏
经过对html查看，页面B对应的元素（div id="/modules/pages/goodsDetail/goodsDetail?stamp=2"）出现后瞬间就被清除了，而页面A对应的（div id="/modules/pages/goodsDetail/goodsDetail?stamp=1" style="display:none;"）被隐藏了，导致白屏
Taro版本从3.3.3一直到3.3.20都试了，都会出现这个问题，升级前是3.0.24，没有问题，因为做小程序插件升级到3.3.xx，发现了这个情况

### 期望结果
能够正常跳转与显示

### 实际结果
不正常

### 环境信息
```
� Taro v3.3.20


  Taro CLI 3.3.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - D:\tools\node-v12\node.EXE
      Yarn: 1.22.5 - D:\tools\yarn\bin\yarn.CMD 
      npm: 6.14.8 - D:\tools\node-v12\npm.CMD 
```

**Comment by ZakaryCode** [comment]
这是一个旧版本问题，3.3.20 不存在。

> 示例项目无法访问，描述方法不能复现该问题

**Comment by liuzeyuwjy** [comment]
> 这是一个旧版本问题，3.3.20 不存在。
> 
> > 示例项目无法访问，描述方法不能复现该问题

访问https://m.jf.10086.cn/hd/#/modules/pages/goodsDetail/goodsDetail?skuWareCode=11087701，点击下面的同类推荐区域，可以看到，我这边做了中转页，才勉强正常跳转的

**Comment by liuzeyuwjy** [comment]
> 这是一个旧版本问题，3.3.20 不存在。
> 
> > 示例项目无法访问，描述方法不能复现该问题

如果您想看复现效果，我可以把有问题的页面发上去

**Comment by ZakaryCode** [comment]
按照流程无法复现该问题，请核对版本后重试

> 如无更多信息，issue 将被关闭
