### ISSUE TITLE
taro能否实现样式独立化?

### ISSUE THREAD

**Issue by Herryjoeson** [NervJS/taro#1147]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
在h5中有默认的dom节点class叫taro_page taro_router,我在某一个页面修改了背景颜色，他会作用于所有的界面，能不能修改的样式只针对当前这个页面，而不是全局的

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
.taro_router {
    background: #f5f5f5;
    .taro_page {
        background: #f5f5f5;
    }
}

```

**Comment by js-newbee** [comment]
你在在页面最外层的 View 标签上加样式就行了。

你给 .taro_page 加背景色跟给微信小程序的 page 标签加背景色没啥区别，都是全局的修改

**Comment by shenghanqin** [comment]
h5建议开启Css module
