### ISSUE TITLE
 react-native  组件 某state更新再次 触发Form  render 方法后， 二次 点击 submit  收集的值变位空

### ISSUE THREAD

**Issue by supermaverickws** [NervJS/taro#11473]
### 这个特性解决了什么问题？
 react-native  组件 某state更新后  Form  二次 触发 submit 收集的值变位空

原因是。外面组件state 更新后，好像触发了 Form 组件的 bindValueChangeEvent 方法。
如果外面没有把第一次收集的值 设置到 value 属性里。 就会重置 Form 组件的 formValues 里对应的值。
如果加个是否 value !== undifend  判断的话，就正常，
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/61172354/158938920-0ffbfda0-2d85-4cac-bcae-2ac5067fb854.png">

**Comment by supermaverickws** [comment]
@zhiqingchen

**Comment by zhiqingchen** [comment]
可否提供相应复现代码片段

**Comment by zhiqingchen** [comment]
表单项value变更，不应该更新一下对应属性？

**Comment by supermaverickws** [comment]
@zhiqingchen  你试试 输入任意数据后点击按钮提交两次。
 第一次正常。第二次值就变为空了
```
function TestFormSubmitTwice(){
    const [input, setInput] = useState();
  
    return <Form onSubmit={value => {
        setInput(value.detail.value?.code || "无")
        Taro.showToast({ title : JSON.stringify(value.detail.value || "无数据")})
    }}>
        <Label>{input}</Label>
       <Input  name="code" placeholder={"请输入"} />
       <Button
                        type="primary"
                        formType="submit"
                        >
                        {"提交, 第二次提交时， code值被重置"}
                    </Button>
    </Form>
  }
```

**Comment by supermaverickws** [comment]
@zhiqingchen 
你输入任意值后。点击按钮 提交两次 。
第一次 正常。 第二次就变为空了
```
export default function TestFormSubmitTwice(){
    const [input, setInput] = useState();
  
    return <Form onSubmit={value => {
        setInput(value.detail.value?.code || "无")
        Taro.showToast({ title : JSON.stringify(value.detail.value || "无数据")})
    }}>
        <Label>{input}</Label>
       <Input  name="code" placeholder={"请输入"} />
       <Button
                        type="primary"
                        formType="submit"
                        >
                        {"提交, 第二次提交时， code值被重置"}
                    </Button>
    </Form>
  }
```

**Comment by zhiqingchen** [comment]
建议加上value属性

```jsx
import { useState } from 'react'
import {Form, Label, Button, Input} from '@tarojs/components'
import Taro from '@tarojs/taro'

export default function TestFormSubmitTwice() {
  const [input, setInput] = useState();
  const [v, setV] = useState('')

  return (
    <Form
      onSubmit={value => {
        setInput(value.detail.value?.code || "无");
        Taro.showToast({
          title: JSON.stringify(value.detail.value || "无数据")
        });
      }}
    >
      <Label>{input}</Label>
      <Input name="code" value={v} onInput={({detail}) => {
        setV(detail.value)
      }} placeholder="请输入"
      />
      <Button type="primary" formType="submit">
        提交, 第二次提交时， code值被重置
      </Button>
    </Form>
  );
}

```

**Comment by supermaverickws** [comment]
@zhiqingchen 可以加这个属性。
但是感觉没必要加。 input 组件太多的话。每个都要写重复的value。
而源码里面只要判断下是否是 undined 就行。

**Comment by supermaverickws** [comment]
@zhiqingchen 但是最终要考虑app端、小程序端、H5 端 Form 组件行为一致性。

**Comment by supermaverickws** [comment]
如果其他端也是同样的逻辑。可以不加。然后你可以关闭此提问。
如果其他端不是此逻辑的话。建议还是修复下。

**Comment by zhiqingchen** [comment]
你提的是对的，只是这么改有个小问题，可能有设置value为undefined的场景。

**Comment by zhiqingchen** [comment]
建议你先打patch解决自身业务问题，此处改动还需要再思考下🤔。

**Comment by supermaverickws** [comment]
好的。

**Comment by supermaverickws** [comment]
你看这样是不是可以。
你可以再加一个 集合属性。 缓存input组件的 name-value
每次判断是否和上一个value 是否相同。相同就忽略。不同就更新
就是每次变动，做下diff 操作。 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/61172354/159396435-9f470ed0-370b-4108-8297-b1cd7a35cf5b.png">

**Comment by zhiqingchen** [comment]
还是判断 undefined 吧

**Comment by supermaverickws** [comment]
行

**Comment by zhiqingchen** [comment]
@supermaverickws 有遇到生产环境下，收集不到form的数据吗

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/pull/11547

**Comment by taoWcode** [comment]
这个问题看似没有解决，在RN中form表单获取到的值，经常部分丢失。目前使用的taro 3.4.4版本。@zhiqingchen

**Comment by taoWcode** [comment]
我的问题跟上面还不是相似的，我的是多个Input，经常会有几个值丢失，不是刷新state更新为null的情况，是不是改出问题了

**Comment by zhiqingchen** [comment]
release 还是 debug

**Comment by taoWcode** [comment]
是debug，目前看是，input onblur事件触发后，之前有值的再次触发onblur后，就会被设置为空值@zhiqingchen

**Comment by taoWcode** [comment]
搞错了。目前定位下来，这个再次onblur后值为空，是input的问题

**Comment by taoWcode** [comment]
搞错了。目前定位下来，这个再次onblur后值为空，是input的问题

**Comment by taoWcode** [comment]
目前看Input没有绑定onChange或者onInput，在onfocus时，设置值为空值。这个returnValue
this.onFocus = () => {
            const { onFocus = noop } = this.props;
            // event.detail = { value, height }
            const { returnValue } = this.state;
            this.tmpValue = returnValue || '';
            onFocus({
                target: { value: this.tmpValue || '' },
                detail: { value: this.tmpValue || '' }
            });
        };

**Comment by zhiqingchen** [comment]
> 

如果是其他问题，另外提供issue吧

**Comment by taoWcode** [comment]
哈哈，我这边只是提醒下，这个issue的表单使用者也可能遇到这个问题。
