### ISSUE TITLE
taro中使用react recoil 编译成京东小程序报错：regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by zhichaoren517** [NervJS/taro#11485]
### 相关平台
京东小程序

**小程序基础库: 京东开发者工具 1.10.0**
**使用框架: React**

### 复现步骤
taro项目中使用react recoil ，编译成京东小程序，只要使用recoil，必现。编译成微信小程序、h5正常运行

### 期望结果
正常

### 实际结果
app.js:2410 Uncaught ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (app.js:2410)
    at Object.node_modulesRecoilEsRecoilJs (app.js:12742)
    at __webpack_require__ (runtime.js:99)
    at Object.node_modulesBabelLoaderLibIndexJsSrcAppTsx (app.js:188)
    at __webpack_require__ (runtime.js:99)
    at Module.srcAppTsx (app.js:12986)
    at __webpack_require__ (runtime.js:99)
    at checkDeferredModules (runtime.js:61)
    at Array.webpackJsonpCallback [as push] (runtime.js:46)
    at app.js:31
(anonymous)	@	app.js:2410
node_modulesRecoilEsRecoilJs	@	app.js:12742
__webpack_require__	@	runtime.js:99
node_modulesBabelLoaderLibIndexJsSrcAppTsx	@	app.js:188
__webpack_require__	@	runtime.js:99
srcAppTsx	@	app.js:12986
__webpack_require__	@	runtime.js:99
checkDeferredModules	@	runtime.js:61
webpackJsonpCallback	@	runtime.js:46
(anonymous)	@	app.js:31
require	@	NAService.js:29928
(anonymous)	@	appservice:2326

### 环境信息
```
hao5@ZBMAC-C02DV1B71  ~/Desktop/code/omni_channel_store   feature/test-page ±✚  taro info
👽 Taro v3.4.3


  Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.15.4/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.4/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1
      @tarojs/mini-runner: 3.4.1 => 3.4.1
      @tarojs/react: 3.4.1 => 3.4.1
      @tarojs/runtime: 3.4.1 => 3.4.1
      @tarojs/taro: 3.4.1 => 3.4.1
      @tarojs/webpack-runner: 3.4.1 => 3.4.1
      babel-preset-taro: 3.4.1 => 3.4.1
      eslint-config-taro: 3.4.1 => 3.4.1
      react: ^17.0.0 => 17.0.2
    npmGlobalPackages:
      typescript: 4.1.3
```

**Comment by s744007195** [comment]
请问咋解决了

**Comment by hky301** [comment]
vue3，引入pinia，编译成京东小程序，也会这个报个错，请问你这个怎么解决的呢
