### ISSUE TITLE
dynamic-import-weapp haven been supported ! but if import url have variable compile will error  

### ISSUE THREAD

**Issue by gowago** [NervJS/taro#11506]
### 相关平台
微信小程序

**小程序基础库: 2.23.1**
**使用框架: Vue 3**

### 复现步骤
const path  = ''examplecComponentsFileName' ;
const AsyncComp = defineAsyncComponent(() => import(`../../components/${path}.vue`));

### 期望结果
动态 import 可以识别url 里面的变量

### 实际结果
小程序编译无法识别

### 环境信息
```
 Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
vue3  异步加载组件 dymic import 里面 的url 变量 h5 可以编译成功但是小程序编译报错
编译警告 Critical dependency: the request of a dependency is an expression

**Comment by Chen-jj** [comment]
暂不支持的

**Comment by ZakaryCode** [comment]
小程序动态加载可以参考[文档](https://nervjs.github.io/taro-docs/docs/babel-config#dynamic-import-node)这里

**Comment by gowago** [comment]
小程序动态加载是支持的也编程成功了  但是import url 里面有变量 小程序编译就回报错
