### ISSUE TITLE
taro-vue3使用useReachBottom在切换页面返回后会多次执行

### ISSUE THREAD

**Issue by vipterry** [NervJS/taro#11504]
### 相关平台
H5

### 复现仓库
[https://github.com/vipterry/taro-reach-bottom.git](https://github.com/vipterry/taro-reach-bottom.git)
**浏览器版本: Chrome 99**
**使用框架: Vue 3**

### 复现步骤
进入首页后，下拉到底部，点击“个人中心”，然后点击返回按钮，这个时候重复下拉到底部，会多次执行（来回多少次就会触发多少次执行）

### 期望结果
只触发一次

### 实际结果
触发N次

### 环境信息
```
Taro CLI 3.4.2 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
      npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.2 => 3.4.2 
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/runtime: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
```

**Comment by vipterry** [comment]
![image](https://user-images.githubusercontent.com/7145196/159683154-31f59c7b-ca7a-4f31-a545-e96fb9def1f7.png)

**Comment by ZakaryCode** [comment]
多次触发是合理的，如果需要限制触发次数可以自己配置截流。使用[lodash](https://lodash.com/docs/4.17.15#throttle)或者自己实现都可以。

**Comment by vipterry** [comment]
> 多次触发是合理的，如果需要限制触发次数可以自己配置截流。使用[lodash](https://lodash.com/docs/4.17.15#throttle)或者自己实现都可以。

这里是一次性触发了的，不是限流的问题

**Comment by vipterry** [comment]
1、根据小程序的逻辑，navigateBack 从B返回页面A，A的onload是不会被触发的

**Comment by vipterry** [comment]
问题排查思路：

**Comment by vipterry** [comment]
问题排查思路：
1、根据小程序的逻辑，navigateBack 从B返回页面A，A的onload是不会被触发的。
2、当H5环境的下，以上条件的，onload被触发导致重复绑定。
![image](https://user-images.githubusercontent.com/7145196/159837688-dbf6bb1d-e76c-40e9-b7b8-d27a3f454149.png)

**Comment by vipterry** [comment]
继续提问题，由于每个页面都会调用一次，bindPageScroll进行绑定，从代码上看，有尝试移除，但是此时pageScrollFn保存的是下一个页面的函数，移除又怎么可能会成功呢？ 所以问题就是出在这里。。。
![image](https://user-images.githubusercontent.com/7145196/160098699-3ec9aee1-6a17-43b5-bbe2-2aa0d13da9e9.png)
![image](https://user-images.githubusercontent.com/7145196/160098961-05d2a72e-4d16-4ea7-9992-fa9cf6230835.png)
