### ISSUE TITLE
没有手动获取摄像头和麦克风，但是在微信小程序发布的时候显示获取麦克风和摄像头

### ISSUE THREAD

**Issue by qingyggg** [NervJS/taro#11500]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/Mols2027/reamx-mp-fronted.git](https://gitee.com/Mols2027/reamx-mp-fronted.git)
**小程序基础库: 2.23.1**
**使用框架: React**

### 复现步骤
打包尝试发布一下

### 期望结果
在微信小程序发布的时候不应该显示获取麦克风和摄像头

### 实际结果
在微信小程序发布的时候显示获取麦克风和摄像头

### 环境信息
```

  Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\zhong\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
仓库develop分支

**Comment by Shawn-zhao** [comment]
同样遇到这个问题，求官方感觉解决

**Comment by lwyj123** [comment]
求赶紧解决

**Comment by Chen-jj** [comment]
@qingyggg 楼主的问题升级 taro-ui 到最新版本即可解决，目前 taro-ui 的最新版本是 `3.1.0-beta.2`，具体可以使用命令 `npm info taro-ui` 查看。

@Shawn-zhao @lwyj123 两位可以检查一下是否使用了 taro-ui，如果使用了则把它升级到最新版本。如还有问题就提供一下 demo 吧。
