### ISSUE TITLE
{"errMsg":"request:fail timeout"} react-native post 请求报错

### ISSUE THREAD

**Issue by supermaverickws** [NervJS/taro#11502]
### 这个特性解决了什么问题？
react-native http POST请求一直报错。
查看源码发现原因如下。
下面是我的 header.
```
 header: {
            'Content-Type': 'application/json;charset=UTF-8'
          },
```
下面是源码里 。 源码里是 写死的  == 'application/json'。

[<img width="868" alt="image" src="https://user-images.githubusercontent.com/61172354/159615412-aad26da9-424b-409e-82e9-34a2e0bb5a3f.png">](https://user-images.githubusercontent.com/61172354/159615412-aad26da9-424b-409e-82e9-34a2e0bb5a3f.png)]

**Comment by supermaverickws** [comment]
@zhiqingchen 
你可以优化下。或者直接关闭此提问。
我提出来方便后来人查问题。

**Comment by zhiqingchen** [comment]
👌，后续安排修复，同时欢迎 修复pr。
