### ISSUE TITLE
Taro.request 500错误无法拦截

### ISSUE THREAD

**Issue by nanhupatar** [NervJS/taro#11518]
### 相关平台
H5

### 复现仓库
[https://github.com/TigerHee/taro-request](https://github.com/TigerHee/taro-request)
**浏览器版本:  Chrome 62**
**使用框架: React**

### 复现步骤
Taro.request 500错误，直接走的是fail,和小程序不同。小程序类似404，500，502等请求都会success

### 期望结果
如何保持一致

### 实际结果
h5拦截器与小程序不一致

### 环境信息
```
  Taro CLI 3.4.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/react: 3.4.2 => 3.4.2 
      @tarojs/router: ^3.4.3 => 3.4.2 
      @tarojs/runtime: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
      react: ^17.0.0 => 17.0.2 
```

**Comment by nanhupatar** [comment]
https://docs.taro.zone/docs/apis/network/request/

**Comment by nanhupatar** [comment]
类似错误 https://github.com/NervJS/taro/issues/3017

**Comment by nanhupatar** [comment]
[](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html#_3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)只要成功接收到服务器返回，无论 statusCode 是多少，都会进入 success 回调。请开发者根据业务逻辑对返回值进行判断。

**Comment by nanhupatar** [comment]
> 只要成功接收到服务器返回，无论 statusCode 是多少，都会进入 success 回调。请开发者根据业务逻辑对返回值进行判断。
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html

**Comment by nanhupatar** [comment]
并且如果是500错误 ，err也无法查看到response的内容

**Comment by qing-zhi** [comment]
H5平台 Taro.request 500错误，直接走的是fail,和小程序不同。小程序类似404，500，502等请求都会success

**Comment by nanhupatar** [comment]
是走的错误，但是无法查看到response





------------------ 原始邮件 ------------------
发件人: qing-zhi ***@***.***&gt;
发送时间: 2022年4月19日 17:42
收件人: NervJS/taro ***@***.***&gt;
抄送: 叫我小胡同学 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [NervJS/taro] Taro.request 500错误无法拦截 (Issue #11518)





 
H5平台 Taro.request 500错误，直接走的是fail,和小程序不同。小程序类似404，500，502等请求都会success

**Comment by moell-peng** [comment]
我使用的 3.4.3 也出现这样的问题，希望小程序和H5触发 success 和 fail 表现一致。

```javascript
const option = {
    ...
    fail: (res) => {
      console.log(res)
    },
    success: (response) => {
      console.log("success", response)
    }
  }

Taro.request(option)
```
服务端返回 403 等状态码：
H5: 执行fail
微信小程序: 执行success

**Comment by ZakaryCode** [comment]
duplicate #9983

**Comment by az031120103** [comment]
遇到同样的问题，请问解决了没有？

**Comment by lyndonliu89757** [comment]
开发者说了，自己封装。。。
