### ISSUE TITLE
taro使用official-account，编译后，在微信小程序不显示该组件

### ISSUE THREAD

**Issue by wuyuancai4357** [NervJS/taro#11522]
### 相关平台
微信小程序

**小程序基础库: 2.21.2**
**使用框架: Vue 2**

### 复现步骤
扫描二维码进入小程序，没有出现引导关注公众号组件

### 期望结果
扫码进入小程序出现该组件

### 实际结果
该组件没有任何反应

### 环境信息
```

  Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
需要在用户扫小程序码后进入小程序引导用户关注公众号

**Comment by Chen-jj** [comment]
@wuyuancai4357 看 wxml 是成功渲染了的，可以用原生页面测试一下试试。

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/11807297/160399616-1748e650-df6c-470a-ae07-3dcf49647a25.png">

**Comment by wuyuancai4357** [comment]
这些情景值都试过，vue2+taro编译后结构里都没有这个标签，小程序和公众号都是同一主体 @ @Chen-jj

**Comment by wuyuancai4357** [comment]
好的，是命中什么值渲染出来的？ @Chen-jj

**Comment by wuyuancai4357** [comment]
代码能参考一下吗 @Chen-jj

**Comment by Chen-jj** [comment]
只是在开发者工具有渲染出来，真机没有环境就没测试了。

**Comment by wuyuancai4357** [comment]
用的是taro组件还是微信组件？

**Comment by Chen-jj** [comment]
taro，就 vue template 里普通写一个 <official-account></official-account>

**Comment by wuyuancai4357** [comment]
出来了，今天百度了一天，根本没有想过会是taro版本问题，非常感谢~ @Chen-jj
