### ISSUE TITLE
css *选择器报错

### ISSUE THREAD

**Issue by scrapstation** [NervJS/taro#11527]
### 相关平台
微信小程序

**小程序基础库: 2.22.0**
**使用框架: React**

### 复现步骤
.order-items-card {
  margin: 20px;
  padding: 20px;
  background-color: #fff;
  border-radius: 20px;
  > *:not(:first-child) {
    border: 1px solid red;
    margin-top: 20px;
  }
  .order-item {
    display: flex;
    flex-wrap: wrap;
  }
}

### 期望结果
正常运行

### 实际结果
 error at token "*"
  10 | }
  11 | 
> 12 | .order-items-card > *:not(:first-child) {
     |                    ^
  13 |   border: 1rpx solid red;
  14 |   margin-top: 20rpx;
  15 | }
at

### 环境信息
```
Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by OneKissAndOneShot** [comment]
不支持* 选择器

**Comment by scrapstation** [comment]
https://taro-docs.jd.com/taro/docs/use-h5#%E4%B8%8D%E6%94%AF%E6%8C%81%E9%83%A8%E5%88%86-css-%E9%80%89%E6%8B%A9%E5%99%A8
