### ISSUE TITLE
Taro.showToast 在百度小程序中不显示文字

### ISSUE THREAD

**Issue by nicejob** [NervJS/taro#1153]
**问题描述**
Taro.showToast 在百度小程序中不显示文字，icon 可以选择显示不显示，但是文字始终无效。

```js
Taro.showToast({
            content: '提示文字',
            icon: 'none',
            duration: 1500
        })

```

**期望行为**
显示文字

**报错信息**

不显示文字，且没有任何报错信息

**系统信息**

 - 操作系统: OS X 10.14(18A391)
 - Taro 版本 1.1.8
 - Node.js 版本 v10.1.0
 - 报错平台 [百度小程序 swan]

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/48656777-87286200-ea64-11e8-8614-2a297575bd37.png)
