### ISSUE TITLE
ScrollView 中添加 Swiper，设置ScrollView 高度为满屏高度时候  Swiper高度错误  H5

### ISSUE THREAD

**Issue by meshikai2014** [NervJS/taro#1154]
![image](https://user-images.githubusercontent.com/7982589/48604862-24788d00-e9b6-11e8-8dcf-dc2f57faad50.png)

![image](https://user-images.githubusercontent.com/7982589/48604612-563d2400-e9b5-11e8-918f-5bb8b8dd5e9d.png)

![image](https://user-images.githubusercontent.com/7982589/48604406-c0a19480-e9b4-11e8-91c7-70583faffd32.png)
把这个去掉 一切恢复正常

**Comment by jinjinjin0731** [comment]
swiper 的样式呢，内部元素都是 100%的

**Comment by meshikai2014** [comment]
> 的样式呢，内部元素都是100%的

没有设置  image的高度 
![image](https://user-images.githubusercontent.com/7982589/48603830-bd0d0e00-e9b2-11e8-8082-340a349f03a4.png)
![image](https://user-images.githubusercontent.com/7982589/48603885-e9c12580-e9b2-11e8-918b-d983c7f721a4.png)
![image](https://user-images.githubusercontent.com/7982589/48603911-fa719b80-e9b2-11e8-8cc8-e3899d34c6b3.png)

**Comment by jinjinjin0731** [comment]
这是你样式写的时候的问题了，。。

**Comment by meshikai2014** [comment]
> 这是你样式写的时候的问题了，。。

这个我是 将 Swiper放到了 ScrollView  中  ，然后 设置了 ScrollView 的 高度 。Swiper的高度就自动变了。

**Comment by jinjinjin0731** [comment]
Swiper 组件的 class 有加高度相关的属性吗，没有不就是继承了父元素也就是  ScrollView 的 高度
