### ISSUE TITLE
希望暴露出入口配置功能，可以使用react18的createroot功能。目前升级到18之后 无法使用改功能

### ISSUE THREAD

**Issue by LengJunT** [NervJS/taro#11557]
### 这个特性解决了什么问题？
可以进一步提高react的性能，对整个应用的性能有一定的提高。
https://react.docschina.org/docs/react-dom-client.html#createroot

### 这个 API 长什么样？
{
isCreateroot: true
}

**Comment by Chen-jj** [comment]
我们近期跟进一下的

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/discussions/11610
