### ISSUE TITLE
关于React

### ISSUE THREAD

**Issue by codthing** [NervJS/taro#11559]
### 这个特性解决了什么问题？
目前正在考虑市面上开发微信小程序的第三方框架，请问这个Taro架构支持React的全新属性吗？支持全新的React18吗？例如Hooks、并发渲染等等，对React的支持度到哪种程度？需要注意一些什么问题？

### 这个 API 长什么样？
我期望的API是，React、NextJS等怎么开发，Taro就怎么开发，做到开发没有区别，剩下的交给你们底层去处理，对开发者友好。

**Comment by pangnate** [comment]
想知道这些问题，我感觉先去爬爬文档，自己写个demo比较快

**Comment by AdvancedCat** [comment]
目前Taro3.4版本内使用的是React17版本，所以Hooks、并发渲染(是batchUpdate吗？)应该都是支持的。

至于React 18，它在路上了 --> https://github.com/NervJS/taro/discussions/11610

**Comment by codthing** [comment]
@AdvancedCat 
good job

**Comment by geekact** [comment]
> 并发渲染(是batchUpdate吗？)

@AdvancedCat 并发渲染是指 concurrent rendering，需要额外支持。比如一些状态库需要配合 useSyncExternalStore 才行能适配react18，否则在React18下数据有可能被 tearing（撕裂）

**Comment by AdvancedCat** [comment]
@geekact 哇，好深奥。大佬可否提供类似的demo场景，方便我用来测试呢？

**Comment by geekact** [comment]
@AdvancedCat 研究如何测试并发渲染好几天了，可以参考我在react状态库中的一个并发测试 https://github.com/foca-js/foca/blob/master/test/concurrent.test.tsx#L62 。（写法感觉不够巧妙）

这是一个繁重的render测试，react-redux@7是未兼容react18的版本，所以useDeferredValue被撕裂了。
升级到react-redux@rc 则恢复正常。
