### ISSUE TITLE
Cannot read property 'ExpoUpdates' of undefined

### ISSUE THREAD

**Issue by Symous** [NervJS/taro#11558]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
react-native Android平台打开如下页面（基本逻辑为调用蓝牙）即报错：
```js
import { View } from '@tarojs/components'
import Taro from '@tarojs/taro';
import { useEffect } from 'react'

export default () => {
  useEffect(() => {
    Taro.openBluetoothAdapter();
  }, [])
  return <View></View>
}
```

Cannot read property 'ExpoUpdates' of undefined

### 期望结果
正常运行；

### 实际结果
报错；

### 环境信息
```
👽 Taro v3.4.4


  Taro CLI 3.4.4 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.0.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.4 => 3.4.4 
      @tarojs/mini-runner: 3.4.4 => 3.4.4 
      @tarojs/plugin-framework-react: 3.4.4 => 3.4.4 
      @tarojs/react: 3.4.4 => 3.4.4 
      @tarojs/rn-runner: ^3.4.4 => 3.4.4 
      @tarojs/runtime: 3.4.4 => 3.4.4 
      @tarojs/taro: 3.4.4 => 3.4.4 
      @tarojs/taro-rn: ^3.4.4 => 3.4.4 
      @tarojs/webpack-runner: 3.4.4 => 3.4.4 
      babel-preset-taro: 3.4.4 => 3.4.4 
      eslint-config-taro: 3.4.4 => 3.4.4 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.4 => 0.67.4 
    npmGlobalPackages:
      typescript: 3.4.5
```

**Comment by Symous** [comment]
只要调用`Taro`，即报上述错误；

**Comment by ZakaryCode** [comment]
应该是 expo-asset 的问题 🤔

最近升级版本时也碰到了类似的问题，[锁了版本](https://github.com/NervJS/taro/blob/775f6bcbd76e0fd4a03f62dbe2d75b268f2b8022/packages/taro-components-rn/package.json#L34)解决了该问题

**Comment by Symous** [comment]
@ZakaryCode 感谢回复，我锁了expo-asset还是不行，又出现了新的错误：
![image](https://user-images.githubusercontent.com/13534034/161245083-09092845-8832-49b3-8e97-9f261ff9427e.png)

我使用的是官方文档的[taro-native-shell](https://taro-docs.jd.com/taro/docs/react-native#%E5%90%AF%E5%8A%A8%E5%BA%94%E7%94%A8) 。

**Comment by Symous** [comment]
@ZakaryCode 感谢回复，我锁了expo-asset还是不行，又出现了新的错误：
![image](https://user-images.githubusercontent.com/13534034/161245083-09092845-8832-49b3-8e97-9f261ff9427e.png)

我使用的是官方文档的[taro-native-shell](https://taro-docs.jd.com/taro/docs/react-native#%E5%90%AF%E5%8A%A8%E5%BA%94%E7%94%A8) 。

**Comment by zhiqingchen** [comment]
这是metro server挂了，可重启下，yarn dev:rn --reset-cache

**Comment by zhiqingchen** [comment]
openBluetoothAdapter 在taro rn 中并不支持
