### ISSUE TITLE
小程序 Taro.onError 没有触发，无法捕获JS错误

### ISSUE THREAD

**Issue by uujx** [NervJS/taro#11552]
### 相关平台
字节跳动小程序

**小程序基础库: 1.9.58.4**
**使用框架: React**

### 复现步骤
1. 小程序入口文件 app.js 中，在 useEffect 中添加 Taro.onError(e => console.log(e));
2. 代码中手动制造 JS 错误

### 期望结果
onError触发，打印 error message

### 实际结果
onError没有触发，没有打印 error message

### 环境信息
```
Taro CLI 3.3.20 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.3 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.3 => 3.4.3 
      @tarojs/components: 3.4.3 => 3.4.3 
      @tarojs/mini-runner: 3.4.3 => 3.4.3 
      @tarojs/plugin-platform-tt: 3.4.3 => 3.4.3 
      @tarojs/react: 3.4.3 => 3.4.3 
      @tarojs/runtime: 3.4.3 => 3.4.3 
      @tarojs/taro: 3.4.3 => 3.4.3 
      @tarojs/webpack-runner: 3.4.3 => 3.4.3 
      babel-preset-taro: 3.4.3 => 3.4.3 
      eslint-config-taro: 3.4.3 => 3.4.3 
      react: 16.14.0 => 16.14.0 
    npmGlobalPackages:
      typescript: 4.4.4
```

**Comment by Chen-jj** [comment]
Taro v3.5 开始支持

**Comment by wuweikd** [comment]
3.6.5 版本，支付宝小程序开发者工具，手动`throw new Error("测试");`，

```
Taro.onError((e) => {
  console.warn('onError!:', e)
})
```
Taro.onError不能捕获错误

**Comment by doudou673** [comment]
现在解决了吗？

**Comment by Casey-ckx** [comment]
所以现在解决了吗

**Comment by Casey-ckx** [comment]
> Taro v3.5 开始支持

我试了一下 3.6都没有捕获成功 对于小程序js报错收集这块我们有诉求但是不知道有什么方式可以收集

**Comment by Chen-jj** [comment]
> 3.6.5 版本，支付宝小程序开发者工具，手动`throw new Error("测试");`，
> 
> ```
> Taro.onError((e) => {
>   console.warn('onError!:', e)
> })
> ```
> 
> Taro.onError不能捕获错误

@wuweikd 测试了一下，支付宝开发者工具是监听不了的，真机可以，应该是开发者工具自身问题导致。

**Comment by Casey-ckx** [comment]
收到，谢谢。

**Comment by Chen-jj** [comment]
> > Taro v3.5 开始支持
> 
> 我试了一下 3.6都没有捕获成功 对于小程序js报错收集这块我们有诉求但是不知道有什么方式可以收集

试了 3.6.18，可以监听成功：

![image](https://github.com/NervJS/taro/assets/11807297/fe0acbc4-07ed-475e-93e7-820063323670)

![image](https://github.com/NervJS/taro/assets/11807297/350922b7-154c-4fcd-aa4c-41b9f402ad7a)

**Comment by xavieryang2011** [comment]
报错那加了4s延时，不加延时是不是也不行啊
