### ISSUE TITLE
编译h5各种报错真的服了 一次没成功过  都怀疑这东西到底能不能用

### ISSUE THREAD

**Issue by jiansir** [NervJS/taro#1156]
该问题别人也提到好多次了吧  这么多人遇到几乎同样的问题  给出的答案结果一个都不能用  至今未看到有人根据你们的回答成功过  真的是服了 
![1542355809 1](https://user-images.githubusercontent.com/29774269/48606253-247a8c00-e9ba-11e8-84d5-8e87722b3dbc.jpg)

**Comment by jinjinjin0731** [comment]
大哥  你这个版本 0.0.68，你稍微看一下 更新文档，现在什么版本了

**Comment by jinjinjin0731** [comment]
package.json 和 taro 版本能对上不
