### ISSUE TITLE
React Native Android模板不是开箱即用的吗？各种插件未安装配置

### ISSUE THREAD

**Issue by Symous** [NervJS/taro#11564]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
1. taro init RNApp；
2. 选择react native模板；
3. npm run dev:rn；
4. react-native run-android;

运行后提示各种原生插件提示未找到，比如react-native-screens、react-native-safe-area-context等都需要手动安装一遍。
![image](https://user-images.githubusercontent.com/13534034/161367219-14452282-5a9c-41fb-871c-f852c4ed815a.png)

检查了依赖目录，发现node_modules中其实已经包含了各种原生端插件，但是在Android目录下没有链接成功，在Android目录下也无法看到相关插件。
![image](https://user-images.githubusercontent.com/13534034/161367229-2a1f3ef8-2d58-463e-8b7c-2730483aeebf.png)

### 期望结果
直接运行成功；

### 实际结果
各种插件没有链接成功；

### 环境信息
```
👽 Taro v3.4.4


  Taro CLI 3.4.4 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.0.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.4 => 3.4.4
      @tarojs/components: 3.4.4 => 3.4.4
      @tarojs/mini-runner: 3.4.4 => 3.4.4
      @tarojs/plugin-framework-react: 3.4.4 => 3.4.4
      @tarojs/react: 3.4.4 => 3.4.4
      @tarojs/rn-runner: 3.4.4 => 3.4.4
      @tarojs/runtime: 3.4.4 => 3.4.4
      @tarojs/taro: 3.4.4 => 3.4.4
      @tarojs/taro-rn: 3.4.4 => 3.4.4
      @tarojs/webpack-runner: 3.4.4 => 3.4.4
      babel-preset-taro: 3.4.4 => 3.4.4
      eslint-config-taro: 3.4.4 => 3.4.4
      react: ^17.0.2 => 17.0.2
      react-native: ^0.67.3 => 0.67.4
    npmGlobalPackages:
      typescript: 3.4.5
```

**Comment by Symous** [comment]
后续手动安装完各种插件后跑起来后，又遇到了map组件（AIRMAP）始终无法找到的问题，经过反复卸载重装终于在原生中成功安装了react-native-maps，这么看坑真不少啊...没点相关开发经验根本搞不定这个模板。请问是react-native模板还没完全完善吗，可以用于实际生产开发吗？

**Comment by zhiqingchen** [comment]
没看文档操作。
要先 yarn upgradePeerdeps

**Comment by Symous** [comment]
@zhiqingchen 建议[官方文档React Native端开发流程](https://taro-docs.jd.com/taro/docs/react-native#%E5%90%AF%E5%8A%A8%E5%BA%94%E7%94%A8) 加入使用 react-native模版的相关说明，目前文档内还是引导新手使用taro-native-shell进行开发。

**Comment by zhiqingchen** [comment]
👌

**Comment by Symous** [comment]
@zhiqingchen 不知道为何运行`yarn upgradePeerdeps`报错如下：

![image](https://user-images.githubusercontent.com/13534034/162425410-cccd5437-2e70-4a44-b350-1f960527f842.png)

应该不是网络的we问题，别的插件都可以正常安装。

**Comment by zhiqingchen** [comment]
执行有问题的话，可以手动执行
install-peer那段

**Comment by zhiqingchen** [comment]
> @zhiqingchen 建议[官方文档React Native端开发流程](https://taro-docs.jd.com/taro/docs/react-native#%E5%90%AF%E5%8A%A8%E5%BA%94%E7%94%A8) 加入使用 react-native模版的相关说明，目前文档内还是引导新手使用taro-native-shell进行开发。

@Symous 
https://docs.taro.zone/docs/react-native
