### ISSUE TITLE
input 组件 TS 语法错误

### ISSUE THREAD

**Issue by robinv8** [NervJS/taro#11562]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
设置 plachholder 颜色文档中对应 api 不支持，使用 placeholderTextColor 但ts 语法错误

### 期望结果
可以设置 plachholder 颜色

### 实际结果
使用 taro 提供的 api 无法设置颜色，只能使用 rn 官方提供的 placeholderTextColor，但有 TS 语法错误

### 环境信息
```
Taro CLI 3.4.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.3 => 3.4.3 
      @tarojs/components: 3.4.3 => 3.4.3 
      @tarojs/mini-runner: 3.4.3 => 3.4.3 
      @tarojs/react: 3.4.3 => 3.4.3 
      @tarojs/runtime: 3.4.3 => 3.4.3 
      @tarojs/taro: 3.4.3 => 3.4.3 
      @tarojs/webpack-runner: 3.4.3 => 3.4.3 
      babel-preset-taro: 3.4.3 => 3.4.3 
      eslint-config-taro: 3.4.3 => 3.4.3 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.4 => 0.67.4 
```

**Comment by robinv8** [comment]
taro 文档中[相关 api](https://taro-docs.jd.com/taro/docs/components/forms/input#api-%E6%94%AF%E6%8C%81%E5%BA%A6) `placeholderStyle` 、`placeholderClass `，如果再添加 RN 特有 api `placeholderTextColor` 不太符合多端统一的原则，是否可以通过检测 `placeholderClass` 或者 `placeholderStyle` 是否存在 `color` 来达到设置 placeholder 颜色的目的

**Comment by zhiqingchen** [comment]
因为 rn 的 input placeholder 只能支持到color，所以支持 placeholderStyle 和 placeholderClass 也无法做到统一。

个人建议
1. 补充`placeholderTextColor ` 的 TS  声明，难以兼容的场景是可以这样处理，@supported rn。
2. 同时也可以兼容支持 `placeholderStyle ` 中的 `color` 属性。
3. `placeholderClass ` 还需要有从样式文件中转化后再取得 color 属性，建议看实现难度，考虑是否支持。

**Comment by robinv8** [comment]
好的，我来处理
