### ISSUE TITLE
Taro.interceptors.logInterceptor 在真机上无效

### ISSUE THREAD

**Issue by yangjisen** [NervJS/taro#11576]
### 相关平台
微信小程序

### 复现仓库

**小程序基础库: 2.23.2**
**使用框架: Vue 3**

### 复现步骤
Taro.addInterceptor(Taro.interceptors.logInterceptor)

### 期望结果
可以正常打印请求调试内容

### 实际结果
真机上无法打印,开发者工具可以打印

### 环境信息
```
  Taro CLI 3.4.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD

```

**Comment by ko-yuki** [comment]
同样，build之后在真机上没有打印请求日志，有解决方案吗

**Comment by ko-yuki** [comment]
taro 3.5.6 版本
production环境
无论在真机还是模拟器上面都无法打印请求日志，官方文档默认配置是打开console的，也尝试过手动配置还是没有用
terser配置：https://github.com/terser/terser#compress-options
`{
    jsMinimizer: 'terser',
    terser: {
        enable: true,
        config: {
            compress: {
                drop_console: false
            }
        }
    }
}`

**Comment by zjjjjjjjjjjd** [comment]
从3.5更新到3.6就不行了
