### ISSUE TITLE
微信小程序支持分包异步化了,像taro.js,vendor.js这几个文件是否可以放到一个独立的分包里?

### ISSUE THREAD

**Issue by airqj** [NervJS/taro#11573]
### 这个特性解决了什么问题？
解决主包过大的问题

### 这个 API 长什么样？
希望可以实现在app.js中加载taro.js/vendor.js这几个文件
如: require('subPackages/packagesCommon/taro.js',taro => {})

**Comment by DD21207** [comment]
求助，能否实现该功能

**Comment by Chen-jj** [comment]
taro.js/vendor.js这几个文件是一开始就要用到的，不适合做分包异步化。倒是多个分包的公共依赖可以放到一个异步分包中，而不是各个分包都拥有一份。
