### ISSUE TITLE
picker更改range后, pickerValue不归0

### ISSUE THREAD

**Issue by blueskink** [NervJS/taro#1157]
**问题描述**

picker更改range后, pickerValue不归0。比如选择第3个数据项后，把range长度改为2，这时picker选中数据项还在第三个上（此时为空）, 直接点击确认，event.detail.value的值超出range范围，引起后续错误。

**复现步骤**
[复现问题的步骤]
1. 选择第三数据项
2. range更改为长度2的数组
3. 打开picker

```js
// 这里可以贴代码

```

**期望行为**
更改range后，能复位到选择项为1.

*系统信息**
- Taro 版本 [e.g. v.1.0.3]
- 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
大概知道什么原因了 尽快修复这个问题
