### ISSUE TITLE
Taro是否可以直接运行react组件或后续是否有计划可以支持？

### ISSUE THREAD

**Issue by 920601358** [NervJS/taro#11581]
### 这个特性解决了什么问题？
项目中有一些组件是用react来编写好的，Taro是否有相关的方法，可以直接把react组件渲染出来？如果没有，请问是否有支持的计划？

### 这个 API 长什么样？
Taro.renderReactComponent({ child: ... })

**Comment by AdvancedCat** [comment]
@920601358  小程序环境中，这要看react组件内部调用的能力是否在Taro运行时支持的能力范围内，你可以尝试将写好的react组件直接在Taro中使用，将需要完善的能力汇总提报给我们，之后会进一步完善运行时能力。
