### ISSUE TITLE
taro3 react H5 快速来回切换tabBar，在首次，网速慢，资源未加载出来的情况下页面重复

### ISSUE THREAD

**Issue by putongdehaochi** [NervJS/taro#11583]
### 相关平台
H5

**浏览器版本: crome99**
**使用框架: React**

### 复现步骤
随便找一个小程序 ， 网速调成3g  ， 清空缓存并硬性重新加载 。 网速慢的时候 ， tabbar 会先加载出来 ， 页面还没加载成功 ， 此时切换会导致同一路由出现相同页面 。Taro 3.4.3

### 期望结果
首屏渲染的时候加 loading

### 实际结果
tabbar预先加载 , 页面未加载前点击导致页面重复

### 环境信息
```
Taro CLI 3.4.3 environment info:
```

**Comment by ZakaryCode** [comment]
未能复现该问题，预期提交最小化可复现demo
