### ISSUE TITLE
ios webvew加载H5空白

### ISSUE THREAD

**Issue by mythshuazi** [NervJS/taro#11592]
### Discussed in https://github.com/NervJS/taro/discussions/11591

<div type='discussions-op-text'>

<sup>Originally posted by **mythshuazi** April  7, 2022</sup>
使用场景：
1.公众号推文中图片点击跳转小程序
2.首次打开进入小程序，webview能正确加载对应的H5地址
3.返回到推文，再次点击图片跳转小程序，此时是空白
至此一直重复2、3步骤一直为空白</div>

**Comment by Tz2318387771** [comment]
@15873944157 解决了吗

**Comment by Tz2318387771** [comment]
解决了吗 @15873944157
