### ISSUE TITLE
关于配置文件

### ISSUE THREAD

**Issue by looch** [NervJS/taro#116]
可以增加类似**webpack**的 `resolve.alias` 特性吗？

```js
{
    alias: {
      '@': resolve('src')
    },
}
```
然后就不用
```js
import Welcome from '.../../../../components/welcome'
```
了。。。

直接
```js
import Welcome from '@/components/welcome'
```

我看了一下配置文件里的 `defineConstants` 属性，貌似只能在`app.js`里做替换

插一句：wepy、mpvue都有使用过，最后才发现**taro**，真的是大爱！！！希望更加完善！！！

**Comment by luckyadam** [comment]
可以的，webpack 的配置已经开发，我稍后添加一下文档~
感谢支持~ Taro 一定会更加完善起来
