### ISSUE TITLE
[feat] 开发提示优化

### ISSUE THREAD

**Issue by JaxXu** [NervJS/taro#1160]
开发中会经常遇到该提示
```
[Taro warn] 请给组件提供一个 `defaultProps` 以提高初次渲染性能！
```
这个提示是在引用自定义组件的时候会提示的吧。
我现在给所有自定义组件都加上defaultProps了，还是提示。
这里能不能加一个名称来标识一下是那个组件没加默认defaultProps

thanks.

**Comment by luodanyalian** [comment]
请问这个解决了吗？

**Comment by shenghanqin** [comment]
我最近几个月写微信小程序和抖音小程序，都没有碰到这个问题。还请再看看新版本有木有？
