### ISSUE TITLE
Taro.uploadFile在h5上传失败

### ISSUE THREAD

**Issue by kaichong** [NervJS/taro#11609]
### 相关平台
H5

**浏览器版本: chrome 100**
**使用框架: Vue 2**

### 复现步骤
上传至ali oss，在chrome 文件大概大于10M会出现上传失败，小于10m能正常上传，查看了taro upload源码，由于是用的 filePath参数，过程中再由blob转为了file对象。或许是导致了浏览器识别为不同的文件。在多台电脑chrome试了都上传不了，但是chrome无痕模式和Firefox上传正常。
```
 const blob = new Blob([file], {
    type: file.type
  })
  const filePath = URL.createObjectURL(blob)
```

### 期望结果
在h5能做到兼容正常上传大文件。

### 实际结果
在chrome上传大于10m图片视频失败

### 环境信息
```
�👽 Taro v3.4.4


  Taro CLI 3.4.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
这是一个神奇的问题。chrome正常模式上传大文件失败，无痕模式下正常。bug可能是出在Taro.uploadFile的api是传入blob对象再进行convertObjectUrlToBlob 转为file对象，可能导致浏览器识别为不同的文件，但是在h5是可以不需要这么操作的。希望能做到兼容。

**Comment by ZakaryCode** [comment]
该问题比较难定位，欢迎 PR 修复

> 另外考虑到该接口在小程序端本身也是有 [10M 限制](https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/component-plus/uploader.html)，兼容意义不大，故不作为 issue 处理
