### ISSUE TITLE
小程序节点超过15层之后，text嵌套text没有进行渲染

### ISSUE THREAD

**Issue by gzh2626** [NervJS/taro#11618]
### 相关平台
微信小程序

**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
1、嵌套15层view
2、text嵌套text

### 期望结果
节点正常展示

### 实际结果
节点无法显示

### 环境信息
```
👽 Taro v3.3.17

labels-- {}
ctxOptions---- {}

  Taro CLI 3.3.17 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      @tarojs/components: 3.3.17 => 3.3.17 
      @tarojs/mini-runner: 3.3.17 => 3.3.17 
      @tarojs/react: 3.3.17 => 3.3.17 
      @tarojs/runtime: 3.3.17 => 3.3.17 
      @tarojs/taro: 3.3.17 => 3.3.17 
      @tarojs/webpack-runner: 3.3.17 => 3.3.17 
      babel-preset-taro: 3.3.17 => 3.3.17 
      eslint-config-taro: 3.3.17 => 3.3.17 
      react: 17.0.2 => 17.0.2 
      react-native: ^0.66.4 => 0.66.4 
```

**Comment by gzh2626** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/22905094/162877520-2d4e903b-d296-4b9f-a704-7e57b8e25cf5.png">

**Comment by gzh2626** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/22905094/162877552-7adc9fe3-1876-40e9-9492-a289836d1192.png">

**Comment by gzh2626** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/22905094/162877590-6299b53b-1864-41d6-9b57-b66a87a5d3ae.png">

**Comment by AdvancedCat** [comment]
递归模板的嵌套层级 baseLevel = 16，你可以通过修改baseLevel来调整嵌套层级
https://nervjs.github.io/taro-docs/docs/config-detail#minibaselevel

**Comment by Chen-jj** [comment]
@gzh2626 你的代码截图只有一部分，没办法复现。如果还有问题，麻烦提供一下完整 demo
