### ISSUE TITLE
无法获取原生微信小程序onShow里的参数

### ISSUE THREAD

**Issue by spirke** [NervJS/taro#1161]
签约微信代扣，进入微信代扣小程序，如果签约成功，就会跳转回来原小程序，是否成功由onShow里的参数决定，目前无法获取到onShow里的参数（res）。
原生小程序样例代码：
App({
    onShow(res) {
        if (res.scene === 1038) { // 场景值1038：从被打开的小程序返回
            const { appId, extraData } = res.referrerInfo
            if (appId == 'wxbd687630cd02ce1d') { // appId为wxbd687630cd02ce1d：从签约小程序跳转回来
                if (typeof extraData == 'undefined'){
                    // TODO
                    // 客户端小程序不确定签约结果，需要向商户侧后台请求确定签约结果
                    return;
                }
                if(extraData.return_code == 'SUCCESS'){
                    // TODO
                    // 客户端小程序签约成功，需要向商户侧后台请求确认签约结果
                    var contract_id = extraData.contract_id
                    return;
                } else {
                    // TODO
                    // 签约失败
                    return;
                }
            }
        }
    }
})

**Comment by spirke** [comment]
在app.tsx内componentDidShow获取this.$router.params就行了

**Comment by robinjl** [comment]
android 无法获取信息
