### ISSUE TITLE
Failed to parse declaration "line-height: 1"

### ISSUE THREAD

**Issue by hao-li** [NervJS/taro#11620]
### 相关平台
React Native

### 复现仓库
[https://github.com/hao-li/taro-problem-sample](https://github.com/hao-li/taro-problem-sample)

**使用框架: React**

### 复现步骤
1. git clone git@github.com:hao-li/taro-problem-sample.git -b taro-3
2. cd taro-problem-sample
3. yarn
4. yarn dev:rn
5. use Taro Playground App to scan printed qrcode

### 期望结果
Taro Playground App 正常加载页面

### 实际结果
`yarn dev:rn` 的终端提示
```
error: src/pages/index/index.scss: Failed to parse declaration "line-height: 1"
```

### 环境信息
```
👽 Taro v3.4.4


  Taro CLI 3.4.4 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.4 => 3.4.4
      @tarojs/components: 3.4.4 => 3.4.4
      @tarojs/mini-runner: 3.4.4 => 3.4.4
      @tarojs/plugin-framework-react: 3.4.4 => 3.4.4
      @tarojs/react: 3.4.4 => 3.4.4
      @tarojs/rn-runner: 3.4.4 => 3.4.4
      @tarojs/runtime: 3.4.4 => 3.4.4
      @tarojs/taro: 3.4.4 => 3.4.4
      @tarojs/taro-rn: 3.4.4 => 3.4.4
      @tarojs/webpack-runner: 3.4.4 => 3.4.4
      babel-preset-taro: 3.4.4 => 3.4.4
      eslint-config-taro: 3.4.4 => 3.4.4
      react: ^17.0.2 => 17.0.2
      react-native: ^0.67.3 => 0.67.4
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2
```

---
### 补充信息
1. 实际版本是 3.4.4，[issue 提交页面](https://issue.taro.zone/)版本选择列表中最高只有 3.3.16
2. 环境中做了这个小修改：https://github.com/NervJS/taro-ui/issues/1459#issuecomment-1095843681
3. 之前有同样问题出现过，但是没看到解决：https://github.com/NervJS/taro/issues/8618

**Comment by shinken008** [comment]
line-height: 1， 这种无单位的设置将会解析失败，因为这种写法根据 font-size 的倍数计算的行高，font-size 在 RN 里面样式编译的时候可能读不到，比如有多个样式值，所以显式的通过配置的 line-height 像素而非倍速这种做法 。

当前直接 Failed to parse 导致 app crash 也是有点问题的，我们可能会通过 stylelint 的方式提示 warning，并在 parse 的时候忽略这个值，避免 crash。

**Comment by hao-li** [comment]
@shinken008 原来如此，感谢回复
[文档](https://docs.taro.zone/docs/react-native-remind#text-%E6%96%87%E6%9C%AC18)中说`line-height`的取值为`number`，还以为只能无单位纯数字，建议也更新一下文档的说明
<img width="988" alt="image" src="https://user-images.githubusercontent.com/11334645/163363359-7cf2ca90-0982-4d19-b357-e5adff1306a1.png">
