### ISSUE TITLE
taro 钉钉小程序 启动报错

### ISSUE THREAD

**Issue by zwfgit** [NervJS/taro#11642]
### 相关平台
钉钉小程序

### 复现仓库
[https://gitee.com/zwfengs/taro-vue3.git](https://gitee.com/zwfengs/taro-vue3.git)

**使用框架: Vue 3**

### 复现步骤
npm run dev:dd

### 期望结果
正常启动

### 实际结果
启动不了

### 环境信息
```
👽 Taro v3.3.16


  Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.0 - D:\soft\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\zwf\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.4 - D:\soft\nodejs\npm.CMD
```

**Comment by zwfgit** [comment]
![image](https://user-images.githubusercontent.com/9571042/163512191-d9d72b79-7b60-4778-b002-aeed5eac4c22.png)

**Comment by zwfgit** [comment]
> 报告什么错误，发一下日志
> 
> 钉钉我稍微有搞过，我看看

![image](https://user-images.githubusercontent.com/9571042/163512324-dc961b02-fd42-46a7-aee3-ae5fa2d7356e.png)
![image](https://user-images.githubusercontent.com/9571042/163512339-9f2126b2-427f-427d-be11-26154bfce0e0.png)

**Comment by zwfgit** [comment]
> 报告什么错误，发一下日志
> 
> 钉钉我稍微有搞过，我看看

拉取下代码直接编译，编译通过，但是钉钉上执行报错

**Comment by Chen-jj** [comment]
@zwfgit 开发者工具要选择钉钉模式。。

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11807297/163843438-680b1fdd-d80d-4516-b962-2b69f1634529.png">

**Comment by zwfgit** [comment]
> @zwfgit 开发者工具要选择钉钉模式。。
> 
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/11807297/163843438-680b1fdd-d80d-4516-b962-2b69f1634529.png">

谢谢，已解决
