### ISSUE TITLE
taro3.4.6 vue3 编译后 支付宝小程序开发工具报错

### ISSUE THREAD

**Issue by cys19970903** [NervJS/taro#11655]
### 相关平台
支付宝小程序

### 复现步骤
taro 3.4.6 vue3 nutui，执行命令taro build --type alipay后，支付宝小程序开发工具报错：
index.html:3 e:\svsp\svsp-customer-miniprogram\dist\alipay\vendors.js: Unexpected token (2450:124)
Please set enableNodeModuleBabelTransform to true or add "e:/svsp/svsp-customer-miniprogram/dist/alipay/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform 。

按照提示设置enableNodeModuleBabelTransform为true后依然报错。

### 期望结果
正常运行

### 实际结果
报已下错误：Please set enableNodeModuleBabelTransform to true or add "e:/svsp/svsp-customer-miniprogram/dist/alipay/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform 。

### 环境信息
```
  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - D:\dev\nodejs\node.EXE
      Yarn: 1.22.18 - D:\dev\node\npm_global\yarn.CMD
      npm: 8.5.0 - D:\dev\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
duplicate #11133
