### ISSUE TITLE
微前端整合

### ISSUE THREAD

**Issue by nvsky** [NervJS/taro#11654]
### 这个特性解决了什么问题？
有taro与qiankun的整合方案么

### 这个 API 长什么样？
qiankum

**Comment by FE92star** [comment]
这种结合，我认为是没有必要的，taro的初衷是一个跨端跨框架的解决方案，主要针对应用级别的方向，微前端属于工程方向的，有点偏离。同时如果与qiankun或者其他生态的框架结合，导致的问题是彼此之间的快速兼容，总有一方需要妥协，这样反而限制了框架的发展，得不偿失。
