### ISSUE TITLE
云开发模板报错

### ISSUE THREAD

**Issue by Leeero** [NervJS/taro#11663]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
Taro v3.3.0

? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 wxcloud（云开发模板）

进入clint目录下执行：npm install && npm run dev:weapp 在代码未做任何修改的前提下报错如下：

编译  发现入口  src/app.ts
编译  发现页面  src/pages/index/index.ts
🙅   编译失败. 2022-4-17 9:27:56 ├F10: PM┤

./src/pages/index/index.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /code/zhuandian/client/src/pages/index/index.ts: Unexpected token, expected "," (22:12)

  20 |   render () {
  21 |     return (
> 22 |       <View className='index'>
     |             ^
  23 |         <Login/>
  24 |       </View>
  25 |     )

### 期望结果
云开发模板正常开发编译

### 实际结果
报错

### 环境信息
```
Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.0 => 3.3.0
      @tarojs/components: 3.3.0 => 3.3.0
      @tarojs/mini-runner: 3.3.0 => 3.3.0
      @tarojs/react: 3.3.0 => 3.3.0
      @tarojs/runtime: 3.3.0 => 3.3.0
      @tarojs/taro: 3.3.0 => 3.3.0
      @tarojs/webpack-runner: 3.3.0 => 3.3.0
      babel-preset-taro: 3.3.0 => 3.3.0
      eslint-config-taro: 3.3.0 => 3.3.0
      react: ^17.0.0 => 17.0.2
```

---
### 补充信息
无需demo代码

**Comment by Chen-jj** [comment]
@Leeero 升级到最新版本再试试

**Comment by Leeero** [comment]
> 

尝试过了的。就是3.4.6的最新版本cli报错后，回滚到3.3.0版本后发现依旧同样的报错。

**Comment by honlyHuang** [comment]
已经修复。新建一个项目或者把`./src/pages/index/index.ts`改成`./src/pages/index/index.tsx`即可
