### ISSUE TITLE
[feature] Taro.Component 实例暴露一个属性以判断这是一个组件还是页面

### ISSUE THREAD

**Issue by fjc0k** [NervJS/taro#1166]
## API

类似这样 `this.$isPage`，并将之加入 TypeScript 类型定义。

## 应用场景

创建项目级别的基本组件，供公共组件及页面继承扩展，如此可在基本组件里判断是否是页面，并注入相关业务逻辑，譬如登录状态、数据埋点之类。

## 补充

以上的应用场景在我看来更好的应该是分成基本组件和基本页面两个类，分别去继承，不过，加上 `$isPage` 可能对其他一些应用场景会更有意义。😀

**Comment by Chen-jj** [comment]
[文档地址](https://nervjs.github.io/taro/docs/best-practice.html#%E4%BD%BF%E7%94%A8-this-componenttype-%E6%9D%A5%E5%88%A4%E6%96%AD%E5%BD%93%E5%89%8D-tarocomponent-%E6%98%AF%E9%A1%B5%E9%9D%A2%E8%BF%98%E6%98%AF%E7%BB%84%E4%BB%B6)
