### ISSUE TITLE
taro previewImage 组件增加onClose参数

### ISSUE THREAD

**Issue by snowones** [NervJS/taro#11665]
### 这个特性解决了什么问题？
监听图片预览结束。场景，当previewImage调用时，通过success调用jsb隐藏端上的返回按钮，希望关闭preview后可以恢复按钮显示，无法自己监控preview结束

### 这个 API 长什么样？
onclose:()=>{
//....
}

**Comment by ZakaryCode** [comment]
对应平台是？

**Comment by snowones** [comment]
> 

目前程序是同时打包为H5和字节跳动小程序，需求的主要场景是H5情况下

**Comment by ZakaryCode** [comment]
这里是 API 调用，增加参数也不具备通用型，暂不考虑增加该特性，不利于维护

**Comment by ZakaryCode** [comment]
> 监听图片预览结束。场景，当previewImage调用时，通过success调用jsb隐藏端上的返回按钮，希望关闭preview后可以恢复按钮显示，无法自己监控preview结束

可以通过[监听 DOM 变化](https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver)达成相同的效果
