### ISSUE TITLE
外部的customer hook无法正常识别 使用不符合预期

### ISSUE THREAD

**Issue by OriX0** [NervJS/taro#11679]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/OriX0/taro_hooks_unable](https://github.com/OriX0/taro_hooks_unable)
**小程序基础库: 2.23.4**
**使用框架: React**

### 复现步骤
用微信开发者工具打开该代码片段
切换点击 推荐/最新   看console.log  即可发现不符合预期

外部hooks 
hooks 作用 给 React.useState 增加了一个 getter 方法，以获取当前最新值。 （拷贝ahooks）

```TSX
import type { Dispatch, SetStateAction } from 'react';
import { useState, useRef, useCallback } from 'react';

type GetState<S> = () => S;

export const useGetState = <S>(
  initialState: S | (() => S),
): [S, Dispatch<SetStateAction<S>>, GetState<S>] => {
  const [state, setState] = useState<S>(initialState);
  /* useRef 用于保存实时状态 */
  const stateRef = useRef<S>(state);
  stateRef.current = state;

  console.log('useGetState内获取到的state',state);
  const getState = useCallback<GetState<S>>(() => stateRef.current, []);

  return [state, setState, getState];
};

```

实际代码段

> - 两个使用useGetState
> - 下面有两个div 推荐/最新 点击切换排序 

```
 const [orderType, setOrderType, getOrderType] = useGetState('推荐');

  const [otherUse,setOtherUse,getOtherUser] = useGetState('一个离谱的值');

  const handleOrderTypeClick = (orderTypeValue) => {
    setOrderType(orderTypeValue);
    console.log(
      "点击传过来的值为--",
      orderTypeValue,
      "getOrderType实时获取的值为--",
      getOrderType()
    );
  };
```

### 期望结果
外部customer hook正常使用 且不会共享使用

### 实际结果
无法正常使用，且共享使用

### 环境信息
```
  Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@OriX0 没懂无法正常使用和共享使用是什么意思。

放普通 React Playground 里结果和 Taro 是一致的。

如果你是想 `setOrderType` 的同一个 tick 中 `getOrderType` 的值马上更新，是不行的。印象中 ref 是 render 后才设置更新的，详细时机你可以 debug 进 react 里看看。

**Comment by AdvancedCat** [comment]
这个跟 fiber.mode 有关系，mode决定了react是执行同步调度还是异步调度。react源码：https://github.com/facebook/react/blob/392808a1f7fa2909492a742116ba8b549e862d70/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L441
在taro中还是以异步调度为主。

**Comment by OriX0** [comment]
我知道setState的更新是异步的，所以我使用了ahooks 的useGetState，用ref去记录最新的值。在其他项目里使用都是正常的，就是在taro里获取不到最新的值

**Comment by OriX0** [comment]
> 这个跟 fiber.mode 有关系，mode决定了react是执行同步调度还是异步调度。react源码：https://github.com/facebook/react/blob/392808a1f7fa2909492a742116ba8b549e862d70/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L441 在taro中还是以异步调度为主。

这个我知道呀- - 但是和这个没关系 我现在是用的customer hooks 而不是直接的setState呀 - - 用的ahooks 的useGetState 原理就是ref记录最新的传入的state的值，然后返回ref.current

**Comment by OriX0** [comment]
> @OriX0 没懂无法正常使用和共享使用是什么意思。
> 
> 放普通 React Playground 里结果和 Taro 是一致的。
> 
> 如果你是想 `setOrderType` 的同一个 tick 中 `getOrderType` 的值马上更新，是不行的。setState 更新是异步的。
> 
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/11807297/165048292-aff983b3-c2f2-4372-aa4f-d5a196428eb9.png">

我知道setState的更新是异步的，所以我使用了ahooks 的useGetState，用ref去记录最新的值。在其他项目里使用都是正常的，就是在taro里获取不到最新的值

**Comment by Chen-jj** [comment]
你可以找个 react playground 试一试
