### ISSUE TITLE
taro_1.default.createSelectorQuery is not a function Call Stack  node_modules/echarts-taro3-react/lib/ec-canvas/index.js:174:16

### ISSUE THREAD

**Issue by wanjingzhang** [NervJS/taro#11673]
### 相关平台
H5

### 复现仓库
[https://github.com/Cecilxx/echarts-taro3-react/issues/27](https://github.com/Cecilxx/echarts-taro3-react/issues/27)
**浏览器版本: Version 100.0.4896.88 (Official Build) (64-bit)**
**使用框架: React**

### 复现步骤
echarts-taro3-react 无法使用

### 期望结果
正常渲染出表格

### 实际结果
抱错了

### 环境信息
```
👽 Taro v3.4.4


  Taro CLI 3.4.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\admin3\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by wanjingzhang** [comment]
> 

怎么解决呢

**Comment by ZakaryCode** [comment]
> 怎么解决呢

这并不是 Taro 的问题，需要第三方库自行调整

**Comment by qs12580** [comment]
同错误 解决了吗
