### ISSUE TITLE
开启vue3响应性语法糖

### ISSUE THREAD

**Issue by transtone** [NervJS/taro#11678]
### 这个特性解决了什么问题？
配置之后能支持响应性语法糖  $ref() 的写法

### 这个 API 长什么样？
https://staging-cn.vuejs.org/guide/extras/reactivity-transform.html#plain-webpack-vue-loader

**Comment by springeye** [comment]
taro更新到最新,依然不生效，配置的如下
```js
  plugins: ['@tarojs/plugin-html', ['@tarojs/plugin-framework-vue3', {
    vueLoaderOption: {
      reactivityTransform: true  // 开启vue3响应性语法糖
    }
  }]],
```
