### ISSUE TITLE
taro vue3项目使用pinia或者vuex 编译成京东小程序报错：regeneratorRuntime is not defined 

### ISSUE THREAD

**Issue by hky301** [NervJS/taro#11674]
### 相关平台
京东小程序

**小程序基础库: 京东开发者工具 1.10.0**
**使用框架: Vue 3**

### 复现步骤
taro vue3项目使用pinia或者vuex 编译成京东小程序报错

### 期望结果
正常

### 实际结果
vendors.js:68 Uncaught ReferenceError: regeneratorRuntime is not defined
    at vendors.js:68
    at vendors.js:68
    at Object.node_modulesVueDevtoolsApiLibEsmProxyJs (vendors.js:68)
    at __webpack_require__ (runtime.js:99)
    at Object.node_modulesVueDevtoolsApiLibEsmIndexJs (vendors.js:64)
    at __webpack_require__ (runtime.js:99)
    at Object.node_modulesVuexDistVuexEsmBrowserJs (vendors.js:1635)
    at __webpack_require__ (runtime.js:99)
    at Object.srcStoreTs (app.js:231)
    at __webpack_require__ (runtime.js:99)

### 环境信息
```
👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.16 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@hky301 提供一下 demo

**Comment by hky301** [comment]
@Chen-jj  taro init  选择vue3+pinia的模板

**Comment by hky301** [comment]
@Chen-jj https://github.com/hky301/taro-with-pinia-demo，用官方脚手架，选择的vue3+pinia模板

**Comment by hky301** [comment]
@Chen-jj [taro-with-pinia-demo](https://github.com/hky301/taro-with-pinia-demo)  用官方脚手架，选择的vue3+pinia模板

**Comment by Chen-jj** [comment]
@hky301 是因为 pinia 这个包使用了 `async` 语法，而 Taro 的 babel-loader 没有处理 `.mjs` 后缀的依赖，所以导致了此问题。

暂时可以手动增加一个 babel-loader 配置来解决，后续会修改 taro-pinia 的模板

<img width="649" alt="image" src="https://user-images.githubusercontent.com/11807297/164185866-f3fd5049-073a-4f98-b11e-33ce154edda8.png">

**Comment by hky301** [comment]
@Chen-jj 我这边加了还是报错的，
![image](https://user-images.githubusercontent.com/19945587/164351243-e1b33009-eb0b-4dbb-ab23-7890efe226ed.png)
