### ISSUE TITLE
vue3  @touchstart @touchmove 在钉钉无效

### ISSUE THREAD

**Issue by zwfgit** [NervJS/taro#11686]
### 相关平台
钉钉小程序

### 复现仓库
[https://gitee.com/zwfengs/taro-vue3.git](https://gitee.com/zwfengs/taro-vue3.git)

**使用框架: Vue 3**

### 复现步骤
npm run dev:dd

### 期望结果
滑动输出console

### 实际结果
无反应

### 环境信息
```
👽 Taro v3.3.16


  Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.0 - D:\soft\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\zwf\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.4 - D:\soft\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@zwfgit 3.4.7 没有复现，升级下再试试

![image](https://user-images.githubusercontent.com/11807297/165093668-3303f213-cf00-4697-b2bb-6ee18bda9af6.png)


<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11807297/165093632-e6a2b8ea-ee98-4755-8a0f-76855507a76a.png">
