### ISSUE TITLE
支付宝使用button弹起获取会员基础信息弹框，同意之后，不能触发onGetAuthorize，导致不能成功授权？

### ISSUE THREAD

**Issue by codefengg** [NervJS/taro#11685]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/codefengg/taro-alipay-authorize-test.git](https://github.com/codefengg/taro-alipay-authorize-test.git)
**小程序基础库: 1.25.4**
**使用框架: Vue 3**

### 复现步骤
点击 支付宝授权按钮，弹出授权框之后，点击同意，没有触发onGetAuthorize方法。

### 期望结果
支付宝小程序用户同意授权之后，可以调用onGetAuthorize方法。

### 实际结果
支付宝小程序用户同意授权之后，没有调用onGetAuthorize方法。

### 环境信息
```
� Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
taro版本为3.4.1，支付宝ide的版本为2.7.2

**Comment by MarshallYang** [comment]
应该直接在onGetAuthorize里面调用getOpenUserinfo就行了吧。

**Comment by codefengg** [comment]
> 应该直接在onGetAuthorize里面调用getOpenUserinfo就行了吧。

问题是同意授权后，触发不了onGetAuthorize

**Comment by codefengg** [comment]
代码片段:

**Comment by codefengg** [comment]
代码片段：
![image](https://user-images.githubusercontent.com/47591966/164964853-b28b846d-3b28-4580-b3e3-d048c8337c35.png)
![image](https://user-images.githubusercontent.com/47591966/164964865-346bb69b-bab1-433a-b5cc-ed35b452c8fb.png)

**Comment by Chen-jj** [comment]
@codefengg 事件绑定错了，改为这样吧：

`@getauthorize="handleGetUserInfo"` 或 `:onGetauthorize="handleGetUserInfo"`

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/11807297/165092237-07e3572f-8968-4638-ad1a-17b611148c45.png">

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/11807297/165092272-1d2ce32a-a4a5-4407-89ab-78042e3d9110.png">

**Comment by donaf** [comment]
> 代码片段： ![image](https://user-images.githubusercontent.com/47591966/164964853-b28b846d-3b28-4580-b3e3-d048c8337c35.png) ![image](https://user-images.githubusercontent.com/47591966/164964865-346bb69b-bab1-433a-b5cc-ed35b452c8fb.png)

你这里需要填scope

**Comment by donaf** [comment]
```
   <button open-type="getAuthorize" scope="phoneNumber" @getAuthorize="getAuthorizeByAlipay" type="primary">支付宝授权登录</button>
```
