### ISSUE TITLE
Taro.showToast的duration属性无效，无论设置多长时间，都会一闪而过。

### ISSUE THREAD

**Issue by wangrongding** [NervJS/taro#11684]
### 相关平台
微信小程序

**小程序基础库: 2.23.2**
**使用框架: Vue 3**

### 复现步骤
如果执行顺序为：  
  Taro.showLoading  =>   Taro.showToast   =>    Taro.hideLoading   
那么中间的Taro.showToast无论设置duration为多少，都会随着hideLoading的执行而一起关闭。

### 期望结果
showToast   不受   hideLoading    的影响

### 实际结果
showToast  受   hideLoading  影响

### 环境信息
```
👽 Taro v3.4.2


  Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - D:\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\admin\AppData\Local\Yarn\bin\yarn.CMD
      npm: 8.1.3 - D:\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
应该是小程序自身的问题，可以使用原生的测试一下

**Comment by konka-king** [comment]
![image](https://user-images.githubusercontent.com/22173084/173285635-b7eaf4d2-8eea-4055-8b42-19725672b3f6.png)
这个原因吧？

**Comment by yijinc** [comment]
2.22.1 以上版本 toast 和 loading 相关接口可以相互混用，新增 noConflict 参数，
目前 taro 未对这个属性做 ts支持，已提pr [13282](https://github.com/NervJS/taro/pull/13282)
