### ISSUE TITLE
安装 @tarojs/cli 严重缓慢

### ISSUE THREAD

**Issue by Jewill** [NervJS/taro#11688]
### 这个特性解决了什么问题？
全局安装 @tarojs/cli 缓慢

### 这个 API 长什么样？
能在 5-10 分钟内完成 @tarojs/cli 的完整安装。

目前在安装其他依赖全局依赖时速度很快，可以排除网络问题。

**Comment by Chen-jj** [comment]
最近提了个 PR https://github.com/NervJS/taro/pull/11672 删了写冗余依赖，可以下个版本再试试的。
