### ISSUE TITLE
支付宝插件ref没办法获取

### ISSUE THREAD

**Issue by wgt464649654** [NervJS/taro#11692]
### 相关平台
微信小程序

### 复现仓库
[https://gitlab.wywk.cn/web-team/weapp-yclub/-/blob/feature/dianjiu/taro/src/components/calendar/component/index.wxss](https://gitlab.wywk.cn/web-team/weapp-yclub/-/blob/feature/dianjiu/taro/src/components/calendar/component/index.wxss)
**小程序基础库: 2.7.9**
**使用框架: React**

### 复现步骤
支付宝ref能获取到节点的实例方法，但是taro获取的是taroElement，没办法拿到实例
<student-verify
    ref='saveRef'
/>

### 期望结果
能拿到插件的实例

### 实际结果
能拿到插件的实例

### 环境信息
```
👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.16 - D:\Program Files\nodejs\npm.CMD👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.16 - D:\Program Files\nodejs\npm.CMD
```

**Comment by AdvancedCat** [comment]
请清晰描述问题背景，是微信小程序还是支付宝小程序？
您提供的demo链接无法打开，请上传至github，谢谢。

**Comment by Chen-jj** [comment]
duplicate #13125
