### ISSUE TITLE
手动增加一个 babel-loader 配置来解决，还是报Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by hky301** [NervJS/taro#11691]
### 相关平台
京东小程序

**小程序基础库: 京东开发者工具1.10.0**
**使用框架: Vue3**

### 复现步骤
pinia 这个包使用了 async 语法，而 Taro 的 babel-loader 没有处理 .mjs 后缀的依赖，所以导致了此问题。

暂时可以手动增加一个 babel-loader 配置来解决，还是报Uncaught ReferenceError: regeneratorRuntime is not defined
config/index.js

mini: {
    webpackChain(chain) {
      chain.merge({
        module: {
          rule: {
            mjsScript: {
              test: /\.mjs$/,
              use: {
                babelLoader: {
                  loader: require.resolve('babel-loader')
                }
              }
            }
          }
        }
      })
    },
    postcss: {
      pxtransform: {
        enable: true,
        config: {

        }
      },
      url: {
        enable: true,
        config: {
          limit: 1024 // 设定转换尺寸上限
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    }
  },

### 期望结果
正常

### 实际结果
vendors.js:90 Uncaught ReferenceError: regeneratorRuntime is not defined

### 环境信息
```
👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.16 - D:\Program Files\nodejs\npm.CMD👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.16 - D:\Program Files\nodejs\npm.CMD
```

**Comment by SyMind** [comment]
看起来像是没有引入 babel-polyfill，或引入 regenerator-runtime。

**Comment by hky301** [comment]
@SyMind babel-polyfill 怎么引入呢

**Comment by SyMind** [comment]
https://babeljs.io/docs/en/babel-polyfill

**Comment by Chen-jj** [comment]
@hky301 像我在第一个 issue 里回答你那样加上 babel-loader 就可以了，现在新建一个 vue3-pinia 项目也没有问题：

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11807297/165058125-eb8583b3-b13d-4929-aea4-5c64dc8981d1.png">

**Comment by hky301** [comment]
> @hky301 像我在第一个 issue 里回答你那样加上 babel-loader 就可以了，现在新建一个 vue3-pinia 项目也没有问题：
> 
> <img alt="image" width="1765" src="https://user-images.githubusercontent.com/11807297/165058523-455d9d24-4af0-49f4-b420-152d60ddbcff.png">

编译成微信小程序没问题的，京东小程序报错的

**Comment by hky301** [comment]
@Chen-jj 编译成微信小程序没问题的，京东小程序报错的

**Comment by Chen-jj** [comment]
就是京东小程序

**Comment by yedongze** [comment]
> 就是京东小程序

我这边测试Taro 3.5.2 init  vue3 + pinia 在京东小程序上也是直接报错 regeneratorRuntime is not defined
