### ISSUE TITLE
Taro React Native CSS Modules 中使用多个 className 类似 classnames 的拼接问题

### ISSUE THREAD

**Issue by SolidZORO** [NervJS/taro#11699]
### 这个特性解决了什么问题？
本来想尝试写个类似 classnames 的 lib 兼容 RN ，磨平一下 H5 和 RN，才发现 RN 里面的 classNames  Styles Object 拼接是在 babel runtime 完成的。

比如这样写是可以正常 work 的：

```jsx
import styles from './styles.module.less';

<Text className={{ ...styles['t1'], ...styles['t2'] }}>A TEXT</Text>
```

但是我把 styles object 提前抽出来写成变量，再传回 className，然后这样写就不 work 了：

```jsx
import styles from './styles.module.less';

const stylesObj = { ...styles['t1'], ...styles['t2'] };

<Text className={stylesObj}>A TEXT</Text>
```

### 这个 API 长什么样？
不知道这个有没有优化的可能，看了一下 @shinken008  大大写的 https://github.com/wuba/taro-react-native/pull/129/files  ，感觉想要支持的可能性不大。

**Comment by zhiqingchen** [comment]
版本信息？

**Comment by SolidZORO** [comment]
不好意思，忘提供了。


```
👽 Taro v3.4.7


  Taro CLI 3.4.7 environment info:
    System:
      OS: macOS 11.6.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.13.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.7 => 3.4.7 
      @tarojs/mini-runner: ^3.4.7 => 3.4.7 
      @tarojs/plugin-framework-react: ^3.4.7 => 3.4.7 
      @tarojs/react: 3.4.7 => 3.4.7 
      @tarojs/rn-runner: ^3.4.7 => 3.4.7 
      @tarojs/runtime: 3.4.7 => 3.4.7 
      @tarojs/taro: 3.4.7 => 3.4.7 
      @tarojs/taro-rn: 3.4.7 => 3.4.7 
      @tarojs/webpack-runner: ^3.4.7 => 3.4.7 
      babel-preset-taro: ^3.4.7 => 3.4.7 
      eslint-config-taro: ^3.4.7 => 3.4.7 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.3 => 0.67.4 
    npmGlobalPackages:
      typescript: 4.6.3
```


我刚在看相关的资料，发现了 https://github.com/NervJS/taro/tree/next/packages/babel-plugin-transform-react-jsx-to-rn-stylesheet 这个 插件，已经 90% 实现了我想要的功能，可惜不支持 CSS modules。

**Comment by shinken008** [comment]
还有10%功能就是你上面说的那个问题？

**Comment by SolidZORO** [comment]
@shinken008 嗯，不过这个感觉已经足够好了，起码 `<Text className={['s1', 's2'], { s3: true }}>TEXT</Text>` 这种都可以实现了。我看看自己能不能改一下让他支持 CSS modules，如果改不了，那只能考虑 BEM 方案了，只是感觉…… 又回到了上古时代。

**Comment by zhiqingchen** [comment]
> 我把 styles object 提前抽出来写成变量，再传回 className，然后这样写就不 work 了

这个问题是有做过类似的兼容，不 work 的话，就是bug了。

**Comment by shinken008** [comment]
可能是个bug，改成这样呢

const stylesObj = { ...styles.t1, ...styles.t2 };

**Comment by shinken008** [comment]
看测试用例是好的，提供一个浮现的 demo 看看

<img width="400" alt="image" src="https://user-images.githubusercontent.com/14921035/164677435-b9c244b5-564c-4780-ad46-db33eb4156b5.png">

**Comment by SolidZORO** [comment]
@shinken008 测试 其实 ['t1'] 和 .t1 没区别。



我还做了如下测试了一下。 标 ✅ 的是生效的。

```jsx
// m1 这种是 CSS Modules
// g1 这种不是 Modules


 const s1Obj = { ...styles.m1, ...styles.m2 };
const s2Obj = { ...styles['m1'], ...styles['m2'] };

        <Text className={(`${styles.m1}`, `${styles.m2}`)}>T-01</Text>
        <Text className={`${styles.m1} ${styles.m2}`}>T-02</Text>
        <Text className={[styles.m1, styles.m2]}>T-03</Text>

        <Text className={{ ...styles.m1, ...styles.m2 }}>T-04 ️✅</Text>
        <Text className={{ ...styles['m1'], ...styles['m2'] }}>T-05 ️✅</Text>

        <Text className={s1Obj}>T-06</Text>
        <Text className={s2Obj}>T-07</Text>

        <Text style={s1Obj}>T-10 ✅</Text> // 换成 style 就可以了
        <Text style={s2Obj}>T-11 ✅</Text> // 换成 style 就可以了

        <Text>----------------------</Text>

        <Text className="g1 g2">T-20 ️✅</Text>
        <Text className="g1">T-21 ️✅</Text>
        <Text className={[`g1`, `g2`]}>T-22 ️✅</Text>
        <Text className={[`g1`, `g2`, { g3: true }]}>T-23 ️✅</Text>
```

**Comment by SolidZORO** [comment]
> 看测试用例是好的，提供一个复现的 demo 看看
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/14921035/164677435-b9c244b5-564c-4780-ad46-db33eb4156b5.png">

嗯，看起来是好的，我也换成了 scss 后缀测试了，还是有问题。 Taro RN 的线上复现有什么平台可以用吗？我写一个试试。

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-react-native-release 用这个进行打包

参考 https://github.com/wuba/Taro-Mortgage-Calculator/blob/master/.github/workflows/main.yml


https://github.com/wuba/taro-playground 用这个扫描查看

**Comment by SolidZORO** [comment]
@zhiqingchen 我刚在把 taro-playground 这个 repo 下回来试了一下，就按照上的写法，直接引用生效，解构就不行了，两个解构也不行。另外就是这个打包复现流程太复杂，我就先不搞了。

<img width="622" alt="image" src="https://user-images.githubusercontent.com/661587/164693281-e6962c03-81bc-4d25-be63-ac96a1bd0317.png">

**Comment by zhiqingchen** [comment]
> @zhiqingchen 我刚在把 taro-playground 这个 repo 下回来试了一下，就按照上的写法，直接引用生效，解构就不行了，两个解构也不行。另外就是这个打包复现流程太复杂，我就先不搞了。
> 
> 
> 
> <img width="622" alt="image" src="https://user-images.githubusercontent.com/661587/164693281-e6962c03-81bc-4d25-be63-ac96a1bd0317.png">
> 
> 
> 
> 
> 
> 

可以直接提供可复现repo

**Comment by SolidZORO** [comment]
@shinken008  我是了你的最新 RP https://github.com/NervJS/taro/pull/11705 发现多个赋值行了，但是只是赋值的行，Fn 表达式直接放进 className 就不行了。

我最开始的想磨平的是 `import cx from 'classnames';` 这样一个 lib，H5 那边通常都是 `className={cx(styles['m1'], styles['m2'])}` 这种写法的，要是多一个赋值 const 放在外面感觉有点怪。

可否加多一个这种直接写在 className={} 中的 Fn 写法的 test 到测试用例里面？

<img width="618" alt="image" src="https://user-images.githubusercontent.com/661587/164884876-a6d0f200-e243-48bc-90cd-78449f25fdd3.png">

**Comment by shinken008** [comment]
em... 这改写就行了

**Comment by shinken008** [comment]
em... 这改下就行

**Comment by jsonchou** [comment]
大佬们，目前有啥进展吗？

```
<View className={s.blue}>t1</View>   // 支持
<View className={cn([s.blue])}>t2</View>   // 不支持
<View className={cn([s.blue,s.main1])}>t3</View>   // 不支持
```

版本：
@tarojs/rn-style-transformer  3.5.5
