### ISSUE TITLE
this.$scope 怎么替换

### ISSUE THREAD

**Issue by zhengjianghao** [NervJS/taro#11708]
说是没有自定义组件，但是组件内部写的canvas获取不到 Taro.canvasToTempFilePath。 写在父组件的canvas可以获取.

现在问题是组件内如何获取到当前上下文，或者Taro.canvasToTempFilePath 如何拿到组件内部的canvas。、

还是说目前只能把canvas写在外部

**Comment by Chen-jj** [comment]
请按规范新建 issues
