### ISSUE TITLE
Taro3.4.7 重A 页面进入 需要下拉刷新的 B 页面，使用 usePullDownRefresh 下拉无效

### ISSUE THREAD

**Issue by tilkofjin** [NervJS/taro#11702]
### 相关平台
H5

### 复现仓库
[https://github.com/tilkofjin/TaroPullDownRefreshBugDemo](https://github.com/tilkofjin/TaroPullDownRefreshBugDemo)
**浏览器版本:      chrome 100.0.4896.127**
**使用框架: React**

### 复现步骤
B页面配置好 enablePullDownRefresh： true，从A 页面点击跳转至B页面，使用下拉刷新功能无效。浏览器直接输入B页面路径，并在B页面刷新页面后，下拉刷新有效

### 期望结果
从任何页面进入只要配置了enablePullDownRefresh： true，都可以使用下拉刷新功能

### 实际结果
只有在路由地址直接在配置好下拉刷新的当前页，刷新页面后才有效

### 环境信息
```
👽 Taro v3.4.7


  Taro CLI 3.4.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\S\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by tingyuxuan2302** [comment]
同遇到类似问题，貌似是改那个下拉刷新无法上滑的bug导致的

**Comment by ZakaryCode** [comment]
这是一个旧版本问题，可以升级解决
