### ISSUE TITLE
输出小程序时不读取 .browserslistrc 文件配置

### ISSUE THREAD

**Issue by Inori-Lover** [NervJS/taro#1170]
**问题描述**
在项目根目录下添加 .browserslistrc 以期望去掉样式转换中对flex-box的-ms-前缀，指定内容如下：
```ini
# safari 用于保留多行省略号
safari>=6
# ios 兼容指定
ios>=9
# 安卓兼容指定
android>=4.4
# 安卓5 或以上都是以chrome为内核
and_chr>=56
ie > 11
edge > 12
```
但只有通过官网提到的config里边书写browsers数组才能起效

**复现步骤**
[复现问题的步骤]
1. 使用scss&redux模板初始化项目
2. 添加 .browserslistrc 文件，内容如上述指定
3. 添加flex相关样式至任意scss
3. 执行 `npm run build:weapp` 进行构建

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
构建小程序时也如同构建h5一般读取 .browserslistrc 配置，这里只提出了postcss 相关，但是在babel等插件估计也是没有读取？

**报错信息**
~

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.1.4
 - Node.js 版本 v10.13.0
 - 报错平台 weapp

**Comment by shenghanqin** [comment]
@Inori-Lover @luckyadam  这个问题不知道是不是在beta版本有更好的解决？
