### ISSUE TITLE
taro 3.4.5 及以后的版本存在重大bug

### ISSUE THREAD

**Issue by konka-king** [NervJS/taro#11703]
### 相关平台
支付宝小程序

**小程序基础库: 2.23.2**
**使用框架: React**

### 复现步骤
https://github.com/NervJS/taro/commit/6ead8693f450ef5072b1175b413f092191d79eb9

可见于这个commit 

比如支付宝扫码，此时  key== item == 'scan' ，apiItem = apiDiff[item] == undefined , 导致扫码无结果返回

其他相关api 也是类似 失效了

3.4.4 是正常的

### 期望结果
扫码有返回

### 实际结果
扫码无返回

### 环境信息
```
👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - D:\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\08143\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - D:\nodejs\npm.CMD
```

**Comment by AdvancedCat** [comment]
你是如何调用scan的？  `Taro.scan()`  or  `Taro.scanCode()` ?

正确的应该用 `Taro.scanCode()` 进行调用

**Comment by konka-king** [comment]
> 你是如何调用scan的？ `Taro.scan()` or `Taro.scanCode()` ?
> 
> 正确的应该用 `Taro.scanCode()` 进行调用

当然是 scanCode 

https://github.com/konka-king/alipay-pickerview

我demo放上去了，点击按钮就扫码，success 属性方法 接收不到回调参数

**Comment by AdvancedCat** [comment]
问题已定位，将合并至下个patch版本
