### ISSUE TITLE
react native开发  production环境下Taro.navigateTo失效，develop环境下没问题

### ISSUE THREAD

**Issue by carltian** [NervJS/taro#11707]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
我的打包步骤
1、执行 yarn build:rn
2、执行 cd android && ./gradlew assembleRelease
完成打包

```
<Button onClick={() => { 
                    // Taro.navigateTo({ url: '/pages/report/index' });
                    Taro.navigateTo({
                        url: '/pages/report/index',
                        events: {
                        },
                        complete: function (res) {
                            Taro.showModal({
                                title: `提示`,
                                content: `${JSON.stringify(res)}`,
                                success: function (res) {
                                  if (res.confirm) {
                                    console.log('用户点击确定')
                                  } else if (res.cancel) {
                                    console.log('用户点击取消')
                                  }
                                }
                              })
                        }
                      })
                 }} >点击跳转</Button>
```

### 期望结果
product 环境下能跳转

### 实际结果
无法跳转

### 环境信息
```

  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.1 => 3.4.1 
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.3 => 0.67.4 
    npmGlobalPackages:
      typescript: 4.5.2
```

---
### 补充信息
文件目录如下
```
├── android
├── ios
├── config
├── global.d.ts
├── package.json
├── project.config.json
├── webmap // webview 地图页面
├── src
│   ├── app.config.ts
│   ├── app.rn.less // 针对RN的单独样式
│   ├── app.less
│   ├── app.ts
│   ├── assets
│   ├── components // 封装的一些多端组件
│   ├── index.html
│   ├── pages
│   └── utils
├── tsconfig.json
└── yarn.lock
```
![6D7B6256EDA608DECA921B6AFE65732A](https://user-images.githubusercontent.com/39288695/164953607-cae5cb8d-b1a3-4625-8fc9-a69409e94b7e.jpg)

**Comment by carltian** [comment]
有提示但是没跳转

**Comment by zhiqingchen** [comment]
yarn build:rn --platform android --qr

然后使用
https://github.com/wuba/taro-playground

扫描试试呢

**Comment by zhiqingchen** [comment]
未复现，尝试

yarn build:rn --reset-cache

**Comment by carltian** [comment]
> ```
> yarn build:rn --platform android --qr
> ```
> 
> 然后使用 https://github.com/wuba/taro-playground
> 
> 扫描试试呢

使用该方式出现报错
Error: Unable to resolve module ./index from /Users/putian/Desktop/work/projects/taro-app-pds/.:

None of these files exist:

index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
index/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
at ModuleResolver.resolveDependency (/Users/putian/Desktop/work/projects/taro-app-pds/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
at DependencyGraph.resolveDependency (/Users/putian/Desktop/work/projects/taro-app-pds/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
at /Users/putian/Desktop/work/projects/taro-app-pds/node_modules/metro/src/lib/transformHelpers.js:129:24
at Server._resolveRelativePath (/Users/putian/Desktop/work/projects/taro-app-pds/node_modules/metro/src/Server.js:1072:12)
at async Server.requestProcessor [as _processBundleRequest] (/Users/putian/Desktop/work/projects/taro-app-pds/node_modules/metro/src/Server.js:428:37)
at async Server._processRequest (/Users/putian/Desktop/work/projects/taro-app-pds/node_modules/metro/src/Server.js:380:9)

**Comment by carltian** [comment]
> 未复现，尝试
> 
> ```
> yarn build:rn --reset-cache
> ```

此方法可行，难道真的是缓存问题？

**Comment by carltian** [comment]
yarn build:rn --reset-cache
打包生成bundle后  进行apk包生成可行
