### ISSUE TITLE
错误日志：tt.onError callback function this.appHacks.onError is not a function

### ISSUE THREAD

**Issue by handsomelive** [NervJS/taro#11712]
### 相关平台
字节跳动小程序

**小程序基础库: 2.49.0.4**
**使用框架: React**

### 复现步骤
无

### 期望结果
无此类错误

### 实际结果
此类错误巨多

### 环境信息
```

👽 Taro v3.3.1

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
    npmPackages:
      @tarojs/cli: ^3.3.16 => 3.3.16 
      @tarojs/components: 3.2.7 => 3.2.7 
      @tarojs/mini-runner: 3.2.7 => 3.2.7 
      @tarojs/react: 3.2.7 => 3.2.7 
      @tarojs/runtime: 3.2.7 => 3.2.7 
      @tarojs/taro: 3.2.7 => 3.2.7 
      @tarojs/webpack-runner: 3.2.7 => 3.2.7 
      babel-preset-taro: 3.2.7 => 3.2.7 
      eslint-config-taro: 3.2.7 => 3.2.7 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
```

**Comment by Chen-jj** [comment]
请提供详细复现步骤

**Comment by xiaoxiath** [comment]
> ### 相关平台
> 字节跳动小程序
> 
> **小程序基础库: 2.49.0.4** **使用框架: React**
> 
> ### 复现步骤
> 无
> 
> ### 期望结果
> 无此类错误
> 
> ### 实际结果
> 此类错误巨多
> 
> ### 环境信息
> ```
> 
> 👽 Taro v3.3.1
> 
> Browserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> 
> Why you should do it regularly:
> https://github.com/browserslist/browserslist#browsers-data-updating
> 
>   Taro CLI 3.3.1 environment info:
>     System:
>       OS: macOS 10.15.5
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
>       Yarn: 1.22.10 - /usr/local/bin/yarn
>       npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
>     npmPackages:
>       @tarojs/cli: ^3.3.16 => 3.3.16 
>       @tarojs/components: 3.2.7 => 3.2.7 
>       @tarojs/mini-runner: 3.2.7 => 3.2.7 
>       @tarojs/react: 3.2.7 => 3.2.7 
>       @tarojs/runtime: 3.2.7 => 3.2.7 
>       @tarojs/taro: 3.2.7 => 3.2.7 
>       @tarojs/webpack-runner: 3.2.7 => 3.2.7 
>       babel-preset-taro: 3.2.7 => 3.2.7 
>       eslint-config-taro: 3.2.7 => 3.2.7 
>       react: ^17.0.0 => 17.0.2 
>       taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
> ```

`@dp/tea-sdk-common`的问题，升级下最新版本
