### ISSUE TITLE
开源基于Lerna管理跨端小程序统一的MonoRepo单体式仓库 单仓多包 Taro技术栈

### ISSUE THREAD

**Issue by DreamPWJ** [NervJS/taro#11710]
已经开源https://github.com/DreamPWJ/mini-monorepo

**Comment by konka-king** [comment]
您可以封装一下 request

**Comment by DreamPWJ** [comment]
> 您可以封装一下 request

有代码示例吗？

**Comment by konka-king** [comment]
> > 您可以封装一下 request
> 
> 有代码示例吗？

善用搜索引擎
https://www.cnblogs.com/BySee1423/p/14470276.html

**Comment by DreamPWJ** [comment]
已经开源https://github.com/DreamPWJ/mini-monorepo   @konka-king [konka-king](https://github.com/konka-king)

**Comment by AdvancedCat** [comment]
这个属于技术类的最佳实践，与Taro issue无关。

**Comment by DreamPWJ** [comment]
> 这个属于技术类的最佳实践，与Taro issue无关。

给加到咱们的最佳实战里吧

**Comment by AdvancedCat** [comment]
你可以另起issue，陈述一下对taro相关的预期收益。
