### ISSUE TITLE
支付宝扫码打开小程序怎么获取数据

### ISSUE THREAD

**Issue by konka-king** [NervJS/taro#11724]
### 这个特性解决了什么问题？
 useRouter()  获取不到

### 这个 API 长什么样？
 useRouter()  能获取到

**Comment by AdvancedCat** [comment]
@konka-king 都自问自答了，可以尝试自问自修啊 😄

**Comment by AdvancedCat** [comment]
Taro提供的 useRouter 主要用于获取页面链接的查询参数，比如通过 `Taro.navigateTo({url:'../index/index?a=1&b=2'})`, 你可以通过 useRouter 获取到页面参数 `{a: '1', b: '2'}`。同理，使用 `Taro.getCurrentInstance().router` 也是如此。

但是，通过扫描二维码启动小程序，要获取二维码中的参数，则需要从 onLaunch 生命周期中获得，通常它长这样：
`alipays://platformapi/startapp?appId=1999&query=number%3D1&page=x%2Fy%2Fz`
[参见支付宝文档](https://opendocs.alipay.com/mini/framework/app-detail#onLaunch(object%3A%20Object)%20%E5%8F%8A%20onShow(object%3A%20Object))

Taro App组件支持 onLaunch 生命周期。

综上，`useRouter` 符合预期。
