### ISSUE TITLE
[react-native]setNavigationBarTitle、reLaunch和 showShareMenu 提示暂不支持

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#1172]
**问题描述**
使用setNavigationBarTitle、reLaunch和 showShareMenu 在react-native端提示不支持

**复现步骤**
[复现问题的步骤]
1.在页面中使用setNavigationBarTitle、reLaunch或者 showShareMenu 
2. 运行react-native端代码
3. 链接react native debugger
4. 控制台打印不支持

[或者可以直接贴源代码，能贴文字就不要截图]
暂时不支持 downloadFile!!!
![ff74c54adf7cd4da2f8f4d903cf0fd9](https://user-images.githubusercontent.com/42051272/48686166-9be82f80-ebf5-11e8-8a12-3a1adf43aac1.png)

**期望行为**
上述能够支持

**报错信息**
没有报错

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.1.8]
 - Node.js 版本 [e.g. v10.9.0]
 - 报错平台 [react-native]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
setNavigationBarTitle 1.0.4 已经支持，如果提示不支持，可能是你的 @tarojs/taro-router-rn 依赖版本太低。
reLaunch 和 showShareMenu RN 端不支持哦，具体可以看文档。
