### ISSUE TITLE
QQ小程序button组件open-type 的合法值有更新

### ISSUE THREAD

**Issue by ggpcn** [NervJS/taro#11722]
### 这个特性解决了什么问题？
腾讯QQ小程序增加了若干open-type 的合法值，详见https://q.qq.com/wiki/develop/miniprogram/component/form/button.html

### 这个 API 长什么样？
比如目前QQ小程序支持添加频道的open-type有效值openGuildProfile，taro暂时还未支持，希望能够同步补全目前缺失的值。

**Comment by AdvancedCat** [comment]
button组件的open-type属性是透传的，并未枚举。可以提供一下你的demo

**Comment by AdvancedCat** [comment]
button组件的open-type属性是透传的，并未枚举。可以提供一下你的demo

**Comment by ggpcn** [comment]
> button组件的open-type属性是透传的，并未枚举。可以提供一下你的demo

您好，我使用的Taro 3.4.7
<button type="button" openType="openGuildProfile" guild-id="123456" style="border: 0;height: 50px;"><span
            style="float: left;margin-left: 2px;font-size: 15px;color: #666666;line-height: 50px;">加入官频</span><i
            class="nutui-iconfont nut-icon-arrow-right"
            style="font-size: 18px;float:right;margin-right:5px;color: #9799A4;line-height: 50px;"></i>
        </button>

比如这段代码，button中的guild-id无法在小程序中传递，导致腾讯获取不到频道ID。

**Comment by AdvancedCat** [comment]
@ggpcn  我懂了，其实只要能支持传递 guild-id 参数即可。欢迎提PR哦

**Comment by ggpcn** [comment]
> @ggpcn 我懂了，其实只要能支持传递 guild-id 参数即可。欢迎提PR哦

对对，就是大佬理解的这个意思，如果可以的话，恳求大佬直接添加一下，我水平优先，还在摸索学习阶段。

**Comment by AdvancedCat** [comment]
等待有兴趣的小伙伴认领，无人认领，我会在明天添加该属性。谢谢！
