### ISSUE TITLE
dev环境和prod的环境变量defineConstants目前无法使用

### ISSUE THREAD

**Issue by meiqinLiu** [NervJS/taro#11737]
### 相关平台
支付宝小程序

**小程序基础库: 2.5.6**
**使用框架: React**

### 复现步骤
config/index.js  里面配置的环境变量 defineConstants，可以读取的到，但是我想区分dev环境和prod环境，在config/dev.js 和config/prod.js 里面配置的 defineConstants的环境变量读取不到

### 期望结果
区分dev环境和prod环境，能够读取在config/dev.js 和config/prod.js 里面配置的 defineConstants的环境变量

### 实际结果
config/dev.js 和config/prod.js 里面配置的 defineConstants的环境变量还没有办法读取

### 环境信息
```
👽 Taro v3.3.7

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.3 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
支付宝小程序里才会出现？

**Comment by 17610869083** [comment]
我也遇到这种情况了，是在微信小程序里面

**Comment by AdvancedCat** [comment]
尝试先升级Taro到最新版，如果仍有问题，可以提供一个最小可复现demo.
thanks all.

**Comment by TheKonka** [comment]
最新版本支付宝和微信小程序测试正常，没有复现问题
