### ISSUE TITLE
支付宝小程序 支付宝中扫码拿不到信息

### ISSUE THREAD

**Issue by sutootototo2002** [NervJS/taro#11732]
### 相关平台
微信小程序

**小程序基础库: 0.0.32**
**使用框架: React**

### 复现步骤
1、首先在支付宝小程序后台生成普通扫码链接
2、用支付宝小程序扫码 看是否能拿到参数 Taro2.0可以,3.0改了
      2.0 :this.$router.params.qrCode
      3.0:getCurrentInstance().router

### 期望结果
拿到参数

### 实际结果
拿不到

### 环境信息
```
👽 Taro v3.4.2


  Taro CLI 3.4.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/react: 3.4.2 => 3.4.2 
      @tarojs/runtime: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
      react: ^17.0.0 => 17.0.2 

```

---
### 补充信息
👽 Taro v3.4.2

  Taro CLI 3.4.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.2 => 3.4.2 
      @tarojs/mini-runner: 3.4.2 => 3.4.2 
      @tarojs/react: 3.4.2 => 3.4.2 
      @tarojs/runtime: 3.4.2 => 3.4.2 
      @tarojs/taro: 3.4.2 => 3.4.2 
      @tarojs/webpack-runner: 3.4.2 => 3.4.2 
      babel-preset-taro: 3.4.2 => 3.4.2 
      eslint-config-taro: 3.4.2 => 3.4.2 
      react: ^17.0.0 => 17.0.2

**Comment by AdvancedCat** [comment]
same as #11724

**Comment by AdvancedCat** [comment]
Look here https://github.com/NervJS/taro/issues/11724#issuecomment-1112316897
