### ISSUE TITLE
不应存在无使用的组件：custom-wrapper.json

### ISSUE THREAD

**Issue by joriewong** [NervJS/taro#11745]
### 相关平台
微信小程序

**小程序基础库: 2.23.3**
**使用框架: React**

### 复现步骤
业务代码不引用custom-wrapper组件，编译到微信小程序，编译产物含有custom-wrapper相关文件，代码质量扫描提示custom-wrapper组件未使用

### 期望结果
代码质量扫描不产生警告

### 实际结果
代码质量扫描提示custom-wrapper组件未使用

### 环境信息
```
👽 Taro v3.4.8


  Taro CLI 3.4.8 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 8.3.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.4.3 => 3.4.3
      @tarojs/components: 3.4.3 => 3.4.3
      @tarojs/mini-runner: 3.4.3 => 3.4.3
      @tarojs/plugin-framework-react: 3.4.3 => 3.4.3
      @tarojs/react: 3.4.3 => 3.4.3
      @tarojs/runtime: 3.4.3 => 3.4.3
      @tarojs/taro: 3.4.3 => 3.4.3
      @tarojs/webpack-runner: 3.4.3 => 3.4.3
      babel-preset-taro: 3.4.3 => 3.4.3
      eslint-config-taro: 3.4.3 => 3.4.3
      react: ^17.0.0 => 17.0.2
```

**Comment by Athrun-Judah** [comment]
请问你最后是怎么解决的呢

**Comment by joriewong** [comment]
@Athrun-Judah 临时选了个场景使用了[CustomWrapper](https://docs.taro.zone/docs/components/custom-wrapper)组件。

**Comment by Athrun-Judah** [comment]
> @Athrun-Judah 临时选了个场景使用了[CustomWrapper](https://docs.taro.zone/docs/components/custom-wrapper)组件。

好的谢谢，我试一试

**Comment by aehyok** [comment]
难道就不解决了嘛？

**Comment by Rabithua** [comment]
同样的问题，强迫症犯了

![image](https://user-images.githubusercontent.com/34543831/188359117-e847d61e-6b38-4f33-9cc0-619a6d485f47.png)

**Comment by yunlinlin** [comment]
请问有人解决了吗？
这好像是Taro编译结束后自动加上去的两个组件，会不会拖累性能啊？

**Comment by wenlittleoil** [comment]
请问这个问题解决了吗，怎么关闭了

**Comment by JinHaocong** [comment]
为什么我的项目微信开发者工具代码质量还是会报错
![image](https://github.com/NervJS/taro/assets/100753463/3526ce81-1b8f-4173-81a2-0629535485b2)

**Comment by wang1212** [comment]
还未解决
