### ISSUE TITLE
Teleport / Portal 支持？

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro#11751]
### 这个特性解决了什么问题？
Vue 的 `Teleport` 和 React 的 `Portal` 组件需求性挺强的，对于弹窗多的小程序很必要。

本质上它们都是通过操作DOM API来实现 （比如 document.insertBefore）， 现在的 Taro3 实现了类似的DOM API，应该已经可以实现这类功能了？

可以通过ref取到`TaroElement`, 然后传给`Teleport`

```vue
const teleportRef = inject('teleportRef')

<Teleport :to="teleportRef">
   ....
</>
```

现在尝试了下会报这个错误：

```
Cannot read property '__treeManager__' of undefined
```

### 这个 API 长什么样？
```vue
const teleportRef = inject('teleportRef')

<Teleport :to="teleportRef">
   ....
</>
```

**Comment by odex21** [comment]
如果尝试更新teleport里面的dom，就会导致
```
Cannot read property '__treeManager__' of undefined
```

我隐约记得前几个月测试的时候是ok的，不知道是vue更新了还是taro更新了，现在又不行了😭

**Comment by Chen-jj** [comment]
问题在于小程序环境要实现跨页面的全局组件，这点还是不好实现，需要再想想

**Comment by ccqgithub** [comment]
> 问题在于小程序环境要实现跨页面的全局组件，这点还是不好实现，需要再想想

我觉得小程序没必要实现跨页面？Portal啥的只需要传当前页面的node ref就行了，毕竟小程序不会同时显示两个页面。

**Comment by LeoFeng23** [comment]
mark一下，Teleport这个希望能得到支持，目前弹窗太多了，嵌套弹窗之后各个端的fixed定位问题真的很让人头疼，如果能支持Teleport，然后把所有弹窗都变成平级应该就没这么多问题了

**Comment by LeoFeng23** [comment]
又或者是对弹窗的场景单独优化？部分支持teleport？

**Comment by AdvancedCat** [comment]
> mark一下，Teleport这个希望能得到支持，目前弹窗太多了，嵌套弹窗之后各个端的fixed定位问题真的很让人头疼，如果能支持Teleport，然后把所有弹窗都变成平级应该就没这么多问题了

我写了个demo，使用了 vue3  teleport，但仅限于在页面内使用，是否满足你们的诉求？
@ccqgithub @LeoFeng23 

https://github.com/AdvancedCat/taro-vue-teleport
