### ISSUE TITLE
[ WXSS 文件编译错误] ./app.wxss  unexpected "\" at pos 11754

### ISSUE THREAD

**Issue by aliuq** [NervJS/taro#11757]
### 相关平台
微信小程序

**小程序基础库: 2.24.1**
**使用框架: Vue 3**

### 复现步骤
引入第三方css样式库，以 `class="demo\:test"` 为例，编译时报错

wxml 
`class="demo test"` 

wcss 
```css
.demo\:test {
  color: red;
}
```

<img width="511" alt="image" src="https://user-images.githubusercontent.com/11707934/166749183-60b38635-258d-4a33-aec4-74fd51c445ed.png">

### 期望结果
`class="demo\:test"` 

### 实际结果
`class="demo test"` 

### 环境信息
```
👽 Taro v3.4.8


  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.1 - C:\scoop_soft\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 1.22.10 - C:\scoop_soft\apps\yarn\current\global\node_modules\.bin\yarn.CMD
      npm: 6.14.16 - C:\scoop_soft\apps\nvm\current\nodejs\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
类名可以这样写么：`.demo\:test`

**Comment by aliuq** [comment]
> 类名可以这样写么：`.demo\:test`

可以的，比如`class="hover:bg-blue-500 dark:text-gray-300"`

**Comment by Chen-jj** [comment]
但看你的截图小程序就是不支持这样写

**Comment by aliuq** [comment]
> 但看你的截图小程序就是不支持这样写

对的，这是小程序不支持的问题

**Comment by Chen-jj** [comment]
那 Taro 也没办法喔
