### ISSUE TITLE
初始化 React Native 模板后，运行白页TypeError: undefined is not an object (evaluating 'this.__callReactNativeMicrotasks

### ISSUE THREAD

**Issue by zhiqingchen** [NervJS/taro#11760]
### 相关平台
React Native

**使用框架: React**

### 复现步骤

- taro init
- 选择 react-native
- yarn upgradePeerdeps

### 期望结果
正常运行

### 实际结果
![image](https://user-images.githubusercontent.com/1876158/166881153-4afb81e4-ad7b-41c5-93bc-6b855a4f19b3.png)

![image](https://user-images.githubusercontent.com/1876158/166881086-d9fdf31f-a98c-4dbd-a49c-940a1609f6a7.png)

D:\shouji\mya\node_modules\react-native\Libraries\Core\ExceptionsManager.js:149 TypeError: Cannot read property '__callReactNativeMicrotasks' of undefined

### 环境信息
```
👽 Taro v3.4.3


  Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
      npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.3 => 3.4.3
      @tarojs/components: 3.4.3 => 3.4.3
      @tarojs/mini-runner: 3.4.3 => 3.4.3
      @tarojs/react: 3.4.3 => 3.4.3
      @tarojs/runtime: 3.4.3 => 3.4.3
      @tarojs/taro: 3.4.3 => 3.4.3
      @tarojs/webpack-runner: 3.4.3 => 3.4.3
      babel-preset-taro: 3.4.3 => 3.4.3
      eslint-config-taro: 3.4.3 => 3.4.3
      react: ^17.0.2 => 17.0.2
      react-native: ^0.67.3 => 0.67.3
```

**Comment by zhiqingchen** [comment]
解决方案

在 package.json 中锁定 @babel/traverse 版本

```json
{
  "resolutions": {
    "@babel/traverse": "7.17.9"
  }
}
```

**Comment by zhiqingchen** [comment]
```
yarn dev:rn --reset-cache
```

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-project-templates/commit/12cfa82d878d9d8c616951fd22d8e1c8597c9d0a

**Comment by zhiqingchen** [comment]
![image](https://user-images.githubusercontent.com/1876158/170455527-037ba8f1-a4aa-4e81-9c0a-0c0cf7fe53d0.png)

**Comment by zhiqingchen** [comment]
2022-06-02 17:59:09.194 17888-18825/com.x.x E/ReactNativeJS: TypeError: this.createDescriptor is not a function. (In 'this.createDescriptor(syntax.descriptors[descName], 'AtruleDescriptor', descName, name)', 'this.createDescriptor' is undefined)

**Comment by zhiqingchen** [comment]
问题原因

https://github.com/babel/minify/pull/1032

**Comment by Panda-K** [comment]
麻烦问下，我现在用Taro 3.4.12，初始化 React Native 模板后，运行白页 还是会有TypeError: undefined is not an object (evaluating 'this.__callReactNativeMicrotasks这个问题。

**Comment by Panda-K** [comment]
这是配置文件：
{
  "name": "GoodTest",
  "version": "1.0.0",
  "private": true,
  "description": "this is good",
  "templateInfo": {
    "name": "react-native",
    "typescript": false,
    "css": "none"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch --qr",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch",
    "android": "react-native run-android --no-packager",
    "ios": "react-native run-ios --no-packager",
    "start": "npm run dev:rn --",
    "podInstall": "pod-install",
    "upgradePeerdeps": "install-peerdeps @tarojs/taro-rn@3.4.12 -o -Y && install-peerdeps @tarojs/components-rn@3.4.12 -o -Y && install-peerdeps @tarojs/router-rn@3.4.12 -o -Y && pod-install"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.4.12",
    "@tarojs/react": "3.4.12",
    "@tarojs/runtime": "3.4.12",
    "@tarojs/taro": "3.4.12",
    "@tarojs/taro-rn": "3.4.12",
    "@tarojs/plugin-framework-react": "3.4.12",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "^0.67.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.4.12",
    "@tarojs/mini-runner": "3.4.12",
    "@tarojs/rn-runner": "3.4.12",
    "@tarojs/webpack-runner": "3.4.12",
    "@types/react": "^17.0.2",
    "@types/react-native": "^0.67.0",
    "@types/webpack-env": "^1.13.6",
    "babel-preset-taro": "3.4.12",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.4.12",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "install-peerdeps": "^3.0.3",
    "pod-install": "^0.1.23",
    "stylelint": "9.3.0"
  },
  "resolutions": {
    "babel-plugin-minify-dead-code-elimination": "0.5.2",
    "@types/react": "17.0.45"
  }
}

**Comment by zhiqingchen** [comment]
1. 确认下依赖的版本`yarn why babel-plugin-minify-dead-code-elimination`
2. 清除缓存启动 `yarn dev:rn --reset-cache`

https://github.com/NervJS/taro/issues/11760#issuecomment-1118262000
