### ISSUE TITLE
怎样手动热更新一个虚拟模块？

### ISSUE THREAD

**Issue by aliuq** [NervJS/taro#11761]
### 相关平台
H5

**浏览器版本: Chrome 100 **
**使用框架: Vue 3**

### 复现步骤
有一个在`app.ts`文件内的虚拟模块，在其他页面操作时，会自动更新这个虚拟模块，但是浏览器和小程序没有热更新，请问下，如何手动执行热更新，我尝试了`module.hot`和`import.meta.webpackHot`都不行

### 期望结果
能够正常进行热更新

### 实际结果
虚拟模块没有热更新

### 环境信息
```
👽 Taro v3.4.8


  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.1 - C:\scoop_soft\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 1.22.10 - C:\scoop_soft\apps\yarn\current\global\node_modules\.bin\yarn.CMD
      npm: 6.14.16 - C:\scoop_soft\apps\nvm\current\nodejs\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
给个 demo 看看怎么写的咯

**Comment by aliuq** [comment]
> 给个 demo 看看怎么写的咯

之前出现问题以为是没有触发热更新，实际上是因为虚拟模块的占位符没有被改变，导致前端没有更新，手动热更新应该是更改虚拟模块的占位符内容就可以触发热更新
