### ISSUE TITLE
TextArea上的属性和字节小程序Textarea的属性已发现很多不同步

### ISSUE THREAD

**Issue by xycd1996** [NervJS/taro#11776]
### 这个特性解决了什么问题？
能够让Textarea属性同步支持字节小程序
confirm-type
show-confirm-bar
bindconfirm
bindlinechange
等等

### 这个 API 长什么样？
能够让Textarea属性同步支持字节小程序
confirm-type
show-confirm-bar
bindconfirm
bindlinechange

**Comment by AdvancedCat** [comment]
欢迎小伙伴PR。(可assign给自己)

基本思路
1. 梳理需要补充支持的属性；
2. 字节端插件[components文件](https://github.com/NervJS/taro/blob/next/packages/taro-tt/src/components.ts) 的Textarea组件添加这几个属性的支持；
3. 撰写测试用例，做好自测；
