### ISSUE TITLE
我想要为小程序端实现vue-router功能，思路和逻辑是否正确？

### ISSUE THREAD

**Issue by social-uni** [NervJS/taro#11779]
### 这个特性解决了什么问题？
目前taro3是不支持vue-router的，我想要在小程序端让其支持vue-router。
以下是我的思路

实现思路，
1. pages里面只有一个主页面,pages/index
2. 在小程序端模拟history，所有界面的变化都通过pages/index？页面的后缀参数实现
3. 监听后缀参数的变化，实现路由功能，请问官方，这种思路是否可行呢

求助
或者请问官方有什么其他思路吗，我想要尝试尽量在小程序端实现完整真实的vue-router

### 这个 API 长什么样？
支持vue-router

**Comment by social-uni** [comment]
我发现taro3是可以支持动态组件的，router-view就是通过动态组件实现的，所以我认为taro3已经具备了支持vue-router的能力。

未来的期望，在用户端隐藏掉pages文件，使用和web一样的解构，用户在app.vue里面编写内容。

通过编译，打包后将其转成pages/index/index.vue，整个项目只有这么一个页面。

其他页面都在这个页面通过路由模拟实现。

**Comment by AdvancedCat** [comment]
目前Taro支持router已经在做了，目前react-router已经跑通了，在做vue-router的测试。RFC也将在这几天放出，欢迎提意见。

你的思路是ok的，但是小程序是多页面架构，推动开发者去做违背小程序官方定义的事情是不合理的。所以，需要实现每个页面单独维护history&location，需要考虑的是在运行时加入完整history实现，同时也要兼顾多页面切换时history上下文正确切换。

**Comment by social-uni** [comment]
> 目前Taro支持router已经在做了，目前react-router已经跑通了，在做vue-router的测试。RFC也将在这几天放出，欢迎提意见。
> 
> 你的思路是ok的，但是小程序是多页面架构，推动开发者去做违背小程序官方定义的事情是不合理的。所以，需要实现每个页面单独维护history&location，需要考虑的是在运行时加入完整history实现，同时也要兼顾多页面切换时history上下文正确切换。

您好，请问现在正在测试的vue-router能实现这种功能吗，给某些页面定义一些通用的头部和底部

```
<template>
  <div>
    <div>头部</div>

    <div>
      <div>路由</div>
      <div>
        <router-view></router-view>
      </div>
    </div>

    <div>
      底部
    </div>
  </div>
</template>
```

**Comment by AdvancedCat** [comment]
> > 目前Taro支持router已经在做了，目前react-router已经跑通了，在做vue-router的测试。RFC也将在这几天放出，欢迎提意见。
> > 你的思路是ok的，但是小程序是多页面架构，推动开发者去做违背小程序官方定义的事情是不合理的。所以，需要实现每个页面单独维护history&location，需要考虑的是在运行时加入完整history实现，同时也要兼顾多页面切换时history上下文正确切换。
> 
> 您好，请问现在正在测试的vue-router支持这种功能吗，给某些页面定义一些通用的头部和底部
> 
> ```
> <template>
>   <div>
>     <div>头部</div>
> 
>     <div>
>       <div>路由</div>
>       <div>
>         <router-view></router-view>
>       </div>
>     </div>
> 
>     <div>
>       底部
>     </div>
>   </div>
> </template>
> ```

目前还在测试单页面内的路由case，你提的case也会进行模拟测试，可以提供一些你关心的完整的case

**Comment by social-uni** [comment]
> > > 目前Taro支持router已经在做了，目前react-router已经跑通了，在做vue-router的测试。RFC也将在这几天放出，欢迎提意见。
> > > 你的思路是ok的，但是小程序是多页面架构，推动开发者去做违背小程序官方定义的事情是不合理的。所以，需要实现每个页面单独维护history&location，需要考虑的是在运行时加入完整history实现，同时也要兼顾多页面切换时history上下文正确切换。
> > 
> > 
> > 您好，请问现在正在测试的vue-router支持这种功能吗，给某些页面定义一些通用的头部和底部
> > ```
> > <template>
> >   <div>
> >     <div>头部</div>
> > 
> >     <div>
> >       <div>路由</div>
> >       <div>
> >         <router-view></router-view>
> >       </div>
> >     </div>
> > 
> >     <div>
> >       底部
> >     </div>
> >   </div>
> > </template>
> > ```
> 
> 目前还在测试单页面内的路由case，你提的case也会进行模拟测试，可以提供一些你关心的完整的case

希望可以支持单页面的tabbar，谢谢

**Comment by AdvancedCat** [comment]
vue-router 跑通了，单页面tabbar也ok了

**Comment by social-uni** [comment]
> vue-router 跑通了，单页面tabbar也ok了

666，期待

**Comment by AdvancedCat** [comment]
@social-uni 
不知是否有兴趣参与到这个feature的开发？如有兴趣请邮件联系我

**Comment by lf7817** [comment]
单页的话主包体积不是很容易超吗
