### ISSUE TITLE
增加Page的render报错感知

### ISSUE THREAD

**Issue by heymie** [NervJS/taro#11771]
### 这个特性解决了什么问题？
当页面render报错(导致页面白屏的)时，开发者能够捕捉到或感知到错误

### 这个 API 长什么样？
当前React的错误边界(https://react.docschina.org/docs/error-boundaries.html) 已正常在Taro3.x中工作，页面可以捕捉到其所使用的自定义组件的render报错，但是页面自身的render报错无法被感知。
Taro源码中有看到PageWrapper对页面级别进行了错误隔离，保证应用不受页面错误而崩溃。
是否可以在PageWrapper的componentDidCatch中，将错误暴露到 Taro.onError中，方便开发者收集错误。

**Comment by Chen-jj** [comment]
https://docs.taro.zone/docs/react-error-handling#%E6%8D%95%E8%8E%B7%E9%A1%B5%E9%9D%A2%E7%BB%84%E4%BB%B6%E8%87%AA%E8%BA%AB%E7%9A%84%E9%94%99%E8%AF%AF
