### ISSUE TITLE
[Fatal] 产物中出现摄像头及麦克风接口导致微信误识别隐私要求

### ISSUE THREAD

**Issue by lwyj123** [NervJS/taro#11780]
### 相关平台
微信小程序

**小程序基础库: 2.24.1**
**使用框架: React**

### 复现步骤
1. build:weapp
2. 准备发布

### 期望结果
如果没有使用摄像头或麦克风相关权限。用户隐私保护指引中不应该出现相关的条例。

### 实际结果
使用 Taro 的代码中没有使用任何摄像头和麦克风的接口。build 出的产物中带有相关的内容导致被识别出。

### 环境信息
```
  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.15.1 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
https://developers.weixin.qq.com/community/develop/doc/000ece06e602482cdafc5473f53400

另外我尝试直接删除 dist 里面相关的我能找到的接口，能解决麦克风的问题，所以确实是 taro 本身导致的而不是我代码的原因。但摄像头的我没找到解法。

由于隐私问题没法发布。

**Comment by Chen-jj** [comment]
> 另外我尝试直接删除 dist 里面相关的我能找到的接口，能解决麦克风的问题

@lwyj123 发一下对应部分的代码？

**Comment by lwyj123** [comment]
> > 另外我尝试直接删除 dist 里面相关的我能找到的接口，能解决麦克风的问题
> 
> @lwyj123 发一下对应部分的代码？

Dist 产物里面搜这几个接口
![image](https://user-images.githubusercontent.com/9214496/167334889-3603263b-44e9-45de-aa37-9744a735b5cf.png)
具体删的哪几个我忘了，我记得 template 里面有几个用了相关标签`<live-pusher>`

**Comment by Garfield550** [comment]
Dup #11500

**Comment by Chen-jj** [comment]
taro-ui 版本是？

**Comment by Chen-jj** [comment]
升级 taro-ui 后再试试。

**Comment by lwyj123** [comment]
@Chen-jj 一直使用的最新的 taro-ui
> dist/base.wxml
![image](https://user-images.githubusercontent.com/9214496/167532051-2201468e-bd21-43bf-97c0-ff1b781db18e.png)
这部分代码不是 taro 的代码么。看起来和 taro-ui 无关。
![image](https://user-images.githubusercontent.com/9214496/167532142-82cbaaed-ccca-40f3-8798-48de045dc0c6.png)

**Comment by lwyj123** [comment]
解决了。查了所有的的页面和处理。发现是有个依赖库的代码里面不知道是怎么打包的，对 @taro/components 的引入是完整 require 而不是按需导致的。我直接 fork 依赖库改了，现在没这个问题了。

**Comment by pisyell** [comment]
> 解决了。查了所有的的页面和处理。发现是有个依赖库的代码里面不知道是怎么打包的，对 @taro/components 的引入是完整 require 而不是按需导致的。我直接 fork 依赖库改了，现在没这个问题了。

哪个依赖库可否告知一下。

**Comment by lwyj123** [comment]
@pisyell 我自己在网上找的一个 taro 的组件。具体问题你得按照你的情况自行排查。具体哪个依赖库你和我的不一定重合而且我现在已经忘了。

**Comment by beilunyang** [comment]
@pisyell  我这边是`taro3-virtual-list`这个第三方组件导致的，可参考下

**Comment by CJLJustin** [comment]
mark一下，taro-cropper这个第三方组件对 @taro/components 的引入也是完整 require的，会导致微信小程序用户隐私协议中出现麦克风权限

**Comment by scwlwj** [comment]
有用，也是第三方组件完整引入@taro/components 导致的。已解决。升级依赖版本
