### ISSUE TITLE
请问RN端如何动态的隐藏/展示底部的tabbar?

### ISSUE THREAD

**Issue by silsuer** [NervJS/taro#11788]
### 这个特性解决了什么问题？
我们在两年前就使用了Taro进行APP的开发, 最近遇到了需求,需要在页面中动态的展示/隐藏底部的导航栏,在文档中没有找到类似的API

### 这个 API 长什么样？
和小程序端保持一致,使用Taro.hideTabbar就好

**Comment by zhiqingchen** [comment]
缺乏 taro info对应信息
