### ISSUE TITLE
更新到3.4.8后，vant uploader上传图片后，没有onAfterRead事件返回。

### ISSUE THREAD

**Issue by lihengdao** [NervJS/taro#11784]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/SummerSnake/taro-shop](https://github.com/SummerSnake/taro-shop)
**小程序基础库: 1.18.0**
**使用框架: React**

### 复现步骤
更新到3.4.8后，vant uploader上传图片后，没有onAfterRead事件返回。

### 期望结果
有结果返回

### 实际结果
返回图片地址

### 环境信息
```
  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\PCLOUD\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@lihengdao 之前哪个版本是可以的呢？
