### ISSUE TITLE
taro3   react-hooks   ts   redux 配置 redux 的 Provider 在小程序的根节点上报错 

### ISSUE THREAD

**Issue by yanzulee** [NervJS/taro#11793]
### 相关平台
微信小程序

**小程序基础库: 2.23.4**
**使用框架: React**

### 复现步骤
根据文档配置redux，provider标签报错

### 期望结果
根据文档配置redux，provider标签不报错

### 实际结果
根据文档配置redux，provider标签报错

### 环境信息
```
Taro CLI 1.3.45 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.2 => 3.3.2 
      @tarojs/components: 3.3.2 => 3.3.2 
      @tarojs/taro: 3.3.2 => 3.3.2 
      @tarojs/webpack-runner: 3.3.2 => 3.3.2 
      eslint-config-taro: 3.3.2 => 3.3.2 
      react: ^17.0.2 => 17.0.2 
```
![image](https://user-images.githubusercontent.com/49908097/167561539-6b790e7a-f70f-48ed-82f9-5e9fd2835400.png)

**Comment by qietuzi** [comment]
https://github.com/NervJS/taro/issues/9989，修改文件后缀为 tsx

**Comment by Json-Answer** [comment]
> #9989
> 
> 修改文件后缀为 tsx
但是这样会报错
![image](https://user-images.githubusercontent.com/76937649/173047071-c393e849-ace6-4b50-abf2-513456ef6601.png)

**Comment by jsLWQ** [comment]
总算找到答案了，研究了半天

**Comment by maimai123** [comment]
> 

解决了吗  我也是改成tsx报错找不到app.ts
