### ISSUE TITLE
iphone7、ios10.3.1，v1.1.4 微信小程序白屏 

### ISSUE THREAD

**Issue by zw130633** [NervJS/taro#1179]
**问题描述**
iphone7、ios10.3.1，v1.1.4 微信小程序白屏 

**报错信息**
![image](https://user-images.githubusercontent.com/12950369/48700194-5ee86100-ec26-11e8-9a4e-361fc3de4ee4.png)

![image](https://user-images.githubusercontent.com/12950369/48700210-6d367d00-ec26-11e8-9f00-b1b096f6167f.png)

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v1.1.4]
 - Node.js 版本 [e.g. v8.9.0]
 - 报错平台 [weapp]

**Comment by zw130633** [comment]
这个问题还挺着急的，还请各位大佬帮忙看看吧！

**Comment by zw130633** [comment]
这个问题跟 #517 的问题类似，但是报错信息不一样，而且小程序代码也没超过 1M

**Comment by luckyadam** [comment]
Taro 的相关依赖也是 1.1.4 的么，看一下~

**Comment by zw130633** [comment]
"@tarojs/async-await": "^1.1.4",
    "@tarojs/components": "^1.1.4",
    "@tarojs/redux": "^1.1.4",
    "@tarojs/redux-h5": "^1.1.4",
    "@tarojs/router": "^1.1.4",
    "@tarojs/taro": "^1.1.4",
    "@tarojs/taro-h5": "^1.1.4",
    "@tarojs/taro-weapp": "^1.1.4",
"@tarojs/plugin-babel": "^1.1.4",
    "@tarojs/plugin-csso": "^1.1.4",
    "@tarojs/plugin-less": "^1.1.4",
    "@tarojs/plugin-sass": "^1.1.4",
    "@tarojs/plugin-uglifyjs": "^1.1.4",
    "@tarojs/webpack-runner": "^1.1.4",
"eslint-config-taro": "^1.1.4",
"eslint-plugin-taro": "^1.1.4"

**Comment by luckyadam** [comment]
远程调试下看看？能不能提供更多的错误信息

**Comment by zw130633** [comment]
错误信息还有很多，但是除了开头部分，后面的错误信息都一样，都是 app-service.js require 的错误（除了行号不一样）。远程调试可以啊，多谢！

**Comment by zw130633** [comment]
目前这个错误只在 iphone7 并且系统为 ios10.3.1 的机型上发现了，开发工具和 iphone6、6s 上都是正常的，其它机型还没有测试

**Comment by zw130633** [comment]
出问题的微信版本为 iOS 6.6.5

**Comment by Chen-jj** [comment]
@zw130633 方便提供一个剪除掉业务逻辑后，可以稳定复现的代码？

**Comment by zw130633** [comment]
在所有代码都没有改动的情况下，我重新 install 了 node_modules，然后再次进行测试没问题了。这样的话这个白屏问题是解决了。在测试过程中我也减掉所有业务代码测试过，发现 taro + dva 模式下，什么业务代码都不写，打包以后的代码是 800k-900k，体积有些大，能帮忙看看吗？代码地址是：https://github.com/zw130633/taro-dva-empty。然后虽然白屏问题解决了，但是在某些机型上会有首次打开闪退的情况，这个应该跟代码体积有关吧，现在打包以后的代码体积是2M多（包含很多本地图片），如果我把代码做好优化，比如图片全部使用网络图片和分包加载处理的话，是不是就不会有闪退情况了？

**Comment by Chen-jj** [comment]
不可能吧，你 taro init 一个项目，看 dist 目录，也就 100k 多点。
建议本地图片超过 1k 的放 cdn，使用分包机制。后面 Taro 在小程序侧会使用 Webpack 打包，包大小也会减少。但你什么都不写就 800-900k 得自己好好看看了。
感觉闪退和包大小关系不大，和内存占用有关，这个你找个稳定复现的机型删减一些逻辑，慢慢调一下吧。

**Comment by zw130633** [comment]
我 800-900k 的代码就是在那个示例代码的基础上把仅有的、并且不多的业务逻辑全部删除，然后把 taro 的相关依赖升级到了 v1.1.4

**Comment by zw130633** [comment]
我们公司现在的第一个 taro 项目， taro+dva 项目代码已经完成多一半了，用不了多久就能提测了

**Comment by Chen-jj** [comment]
你感受一下，taro-dva/dist
![629a2cfb-beb0-c93f-0866-53fa0755d593](https://user-images.githubusercontent.com/11807297/48774630-bd384100-ed05-11e8-8548-5190322ca199.jpg)
如果你说你没有把这个项目放图片的 assets 文件夹（900k+）删掉，那是 1M

**Comment by zw130633** [comment]
是的，有图片在里面，我犯了很低级的错误，真是不好意思！
