### ISSUE TITLE
百度小程序 页面配置文件 index.config.ts中使用usingSwanComponents方式引入动态库 不编译

### ISSUE THREAD

**Issue by yuconora** [NervJS/taro#11794]
### 相关平台
百度小程序

### 复现仓库
[https://github.com/yuconora/tarotest.git](https://github.com/yuconora/tarotest.git)
**小程序基础库: 3.440.10**
**使用框架: React**

### 复现步骤
1. 新建一个项目 在app.config.ts 中配置 动态库（这里使用[one-stop-interaction 一站式互动](https://smartprogram.baidu.com/docs/develop/extended/component-content/interaction/)组件做个示例）

```json
{
  .....
  "dynamicLib": {
    // 'myDynamicLib' 是个可自定义的别名。
    "myDynamicLib": {
      // provider 是要引用的动态库的名字，在此为 'swan-interaction'。
      "provider": "swan-interaction",
    },
  },
}
```

2. 在页面 index.config.ts 中配置 comment-list 

```ts
export default {
  "usingSwanComponents": {
    "comment-list": "dynamicLib://myDynamicLib/comment-list"
  }
};
```
3. 在index.tsx 中引入 comment-list

```tsx
function Index() {
  return <comment-list />
}
```
4. 执行脚本命令 dev:swan

### 期望结果
正确编译出 comment-list 组件

### 实际结果
页面里面不含 comment-list 组件

### 环境信息
```
  Taro CLI 3.4.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 
      Yarn: 1.22.18 
      npm: 8.5.5

```

---
### 补充信息
百度小程序总喜欢玩一些新花样 动态库引用规范竟然有两种。。。

看了一下源码 在 taro-mini-runner 里面
    https://github.com/NervJS/taro/blob/a510b90c406984262c45a8f7ea720de4b51dc09e/packages/taro-mini-runner/src/plugins/MiniPlugin.ts#L669

这个地方加一个条件 就可以编译出来了

```js
const usingComponents = fileConfig.usingComponents || fileConfig.usingSwanComponents;
```
居家办公网络太差，代码拉不下来。。。哪位看到了提交一个补丁测试一下吧

**Comment by FE92star** [comment]
好的，我来看看，我网好～

**Comment by FE92star** [comment]
这里涉及到全局的配置，需要再加一个百度小程序特有属性usingSwanComponents配置
