### ISSUE TITLE
[Feature Request] css-in-js support

### ISSUE THREAD

**Issue by luankefei** [NervJS/taro#118]
后续能否支持css-in-js方案？整个项目都是js，岂不美滋滋？💅💅🏻
例如：glamor、styled-components、styled-jsx等

**Comment by luckyadam** [comment]
计划支持

**Comment by looch** [comment]
css-in-js +1

**Comment by kdong007** [comment]
+1

**Comment by xialvjun** [comment]
微信小程序没有提供操作 WXSS 的 JS API，所以那些运行时（而不是编译时）生成 style 标签的 css-in-js 库（例如 emotion）是没可能应用的，是吧

**Comment by looch** [comment]
硬编码进去，还有style插入。两种方案。

**Comment by bryan77523** [comment]
ok

**Comment by limichange** [comment]
🚧

**Comment by CareyToboo** [comment]
`styled-components` +1

**Comment by ericyang89** [comment]
styled-components +1

**Comment by l-hammer** [comment]
styled-components +1

**Comment by qwIvan** [comment]
茲茲

**Comment by yangzhe1003** [comment]
styled-components +1

**Comment by shaodushu** [comment]
styled-components +1

**Comment by luweiCN** [comment]
styled-components +1

**Comment by tourze** [comment]
+1

**Comment by zzswang** [comment]
+1

**Comment by grusirna** [comment]
+1

**Comment by zidian257** [comment]
+1

**Comment by Lizhooh** [comment]
有没有进展啊，希望能支持 emotion

 https://github.com/emotion-js/emotion

**Comment by NgeKaworu** [comment]
+1

**Comment by xnng** [comment]
+1

**Comment by eugle** [comment]
2020年了，还没有任何进展 吗？？

**Comment by AntoninSorrento** [comment]
+1

**Comment by jaypeng2015** [comment]
styled-components +1

**Comment by yuche** [comment]
https://taro-docs.jd.com/taro/next/docs/css-in-js.html

**Comment by loveklmn** [comment]
> https://taro-docs.jd.com/taro/next/docs/css-in-js.html

已变更为  https://taro-docs.jd.com/taro/docs/css-in-js

**Comment by SidneyLann** [comment]
RN下还是做不到
