### ISSUE TITLE
Taro中如何监听捕获阶段的onClick事件

### ISSUE THREAD

**Issue by hecr** [NervJS/taro#11807]
### 相关平台
微信小程序

**小程序基础库: 2.24.1**
**使用框架: React**

### 复现步骤
<View  onClickCapture={()=>{console.log("hello")}}>Hello</View>

### 期望结果
点击Hello时, 控制台输出"hello"

### 实际结果
点击Hello时, 控制台没有输出"hello"

### 环境信息
```
Taro CLI 3.4.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - D:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
在React中，使用的是onClickCapture; 在微信小程序中，使用的是capture-bind:tap，在Taro中使用什么方式达到类似的效果？

**Comment by Chen-jj** [comment]
目前还没支持小程序事件捕获

**Comment by hecr** [comment]
好的， 谢谢！ 目前有计划支持这个特性吗？

**Comment by Chen-jj** [comment]
还没有的

**Comment by lanrenbulan** [comment]
目前还没计划支持capture吗，有什么方案代替吗

**Comment by toFrankie** [comment]
H5 也不支持事件捕获？
