### ISSUE TITLE
build fail: app.wxss from CssoWebpackPlugin

### ISSUE THREAD

**Issue by longhaoteng** [NervJS/taro#11805]
### 相关平台
微信小程序

**小程序基础库: x.x.x**
**使用框架: Vue 3**

### 复现步骤
taro init test

? 请输入项目介绍！ test

? 请选择框架 Vue3

? 是否需要使用 TypeScript ？ Yes

? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass

? 请选择模板源 Github（最新）

✔ 拉取远程模板仓库成功！

? 请选择模板 vue3-vuex

taro build --type weapp

启动  开发者工具-项目目录  /test/dist

生成  工具配置  /test/dist/project.config.json

编译  发现入口  src/app.ts

编译  发现页面  src/pages/index/index.vue

🙅   编译失败. 2022/5/13 22:07:25

app.wxss from CssoWebpackPlugin
You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at async Promise.all (index 0)
    at async Promise.all (index 3)

### 期望结果
build成功

### 实际结果
build失败

### 环境信息
```
👽 Taro v3.4.9

  Taro CLI 3.4.9 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.0.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.9 => 3.4.9
      @tarojs/mini-runner: 3.4.9 => 3.4.9
      @tarojs/runtime: 3.4.9 => 3.4.9
      @tarojs/taro: 3.4.9 => 3.4.9
      @tarojs/webpack-runner: 3.4.9 => 3.4.9
      babel-preset-taro: 3.4.9 => 3.4.9
      eslint-config-taro: 3.4.9 => 3.4.9
```

**Comment by Chen-jj** [comment]
@longhaoteng 没有复现，如还有问题则提供一下完整 Demo 咯

<img width="836" alt="image" src="https://user-images.githubusercontent.com/11807297/168527280-d4ec0931-2dd9-4911-95ff-92d7f6c68bee.png">

<img width="782" alt="image" src="https://user-images.githubusercontent.com/11807297/168527295-68c3bf41-3e48-4255-83aa-eaf07b2b8f38.png">

**Comment by longhaoteng** [comment]
@Chen-jj  `node` 版本问题，`18.0.0` 版本能复现，降低版本就能构建成功了

**Comment by moonRider** [comment]
> @Chen-jj `node` 版本问题，`18.0.0` 版本能复现，降低版本就能构建成功了

我 node 版本 16.13.2 存在同样的问题

**Comment by wenmingtang** [comment]
`export NODE_OPTIONS=--no-experimental-fetch`

再 build

**Comment by Jeff-Tian** [comment]
我在 Windows 11 用 node 18.12.1、taro 3.6.2 也遇到这个问题了，试了降低 node 版本不管用，`  "overrides": {
    "source-map": "0.7.4"
  }` 也不管用。

最后在配置里禁用了 `csso`，终于可以编译了。

https://github.com/Jeff-Tian/weapp/commit/368ba202313c34aefa5064bd3a7eecac0d60830e#diff-2d42f3640c8da718d341ac31f43fa50d0b9bab9a67723fe8abce70c639b73b5c：

```diff
module.exports = {
  env: {
    NODE_ENV: '"production"',
  },
  defineConstants: {},
  mini: {
    enableSourceMap: false,
    terser: {
      enable: true,
      config: {
        // 配置项同 https://github.com/terser/terser#minify-options
      }
    },
    csso: {
-      enable: true,
+      enable: false,
      config: {
        // 配置项同 https://cssnano.co/docs/what-are-optimisations/
      }
    }
  },
  h5: {
    enableSourceMap: true,
  },
}
```

**Comment by dzhiqin** [comment]
我也遇到这个问题了，是因为引入的字体文件体积太大导致的。
