### ISSUE TITLE
执行npm run build:h5的时候CPU爆增

### ISSUE THREAD

**Issue by GZWZC** [NervJS/taro#11811]
### 相关平台
H5

### 复现仓库
[https://github.com](https://github.com)
**浏览器版本: LINUX**
**使用框架: React**

### 复现步骤
在linux里执行npm run build:h5完后，CPU爆增导致服务器挂掉

### 期望结果
linux里能打包成功

### 实际结果
CPU爆增，打包不成功，服务器其他服务也挂掉
jenkins报错

Process leaked file descriptors. See https://www.jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
SSH: Current build result is [FAILURE], not going to run.

可以如何优化？

### 环境信息
```
> taro info

👽 Taro v3.3.7

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.7 => 3.3.7 
      @tarojs/components: 3.3.7 => 3.3.7 
      @tarojs/mini-runner: 3.3.7 => 3.3.7 
      @tarojs/react: 3.3.7 => 3.3.7 
      @tarojs/runtime: 3.3.7 => 3.3.7 
      @tarojs/taro: 3.3.7 => 3.3.7 
      @tarojs/webpack-runner: 3.3.7 => 3.3.7 
      babel-preset-taro: 3.3.7 => 3.3.7 
      eslint-config-taro: 3.3.7 => 3.3.7 
      react: ^17.0.0 => 17.0.2 
```

**Comment by GZWZC** [comment]
linux服务器空闲中与打包中的截图。机器配置：8核16G
<img width="843" alt="image" src="https://user-images.githubusercontent.com/16217142/168531929-9f7912e7-425e-48f0-8263-288b03b98524.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/16217142/168531939-c2c19926-24cf-4809-8c55-89ba67106c27.png">

**Comment by GZWZC** [comment]
macbook pro空闲中与打包中的截图。
机器配置：
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
处理器：1.4 GHz 四核Intel Core i5
内存：8 GB 2133 MHz LPDDR3
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/16217142/168532313-ff20b23b-30e8-404b-b0b2-01f7bf2b6593.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/16217142/168532325-cc5efcd6-ef13-4e58-bfab-400e796ba872.png">

**Comment by ZakaryCode** [comment]
应该是监听过多文件导致 CPU 占用率增加，尝试在 Loaders 中排除不必要的文件可以优化编译性能。

> 另外，在 3.5 新增了 [prebundle](https://nervjs.github.io/taro-docs/docs/next/prebundle) 特性也会大幅减少监听文件从而提升编译性能，可以尝试看看
