### ISSUE TITLE
vscode 编译器一直提示 View 等 taro 提供的标签类型错误

### ISSUE THREAD

**Issue by soeasyjx** [NervJS/taro#11814]
### 相关平台
H5

**浏览器版本: Chrome 101**
**使用框架: React**

### 复现步骤
打开 vscode 编译器 就报 TS类型错误，造成组件不会有类型提示信息，不影响最终开发

### 期望结果
不报类型错误等信息了

### 实际结果
 vscode 编译器 就报 TS类型错误

### 环境信息
```
👽 Taro v3.4.9

  Taro CLI 3.4.9 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 3.2.0 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.10.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.9 => 3.4.9 
      @tarojs/components: 3.4.9 => 3.4.9 
      @tarojs/mini-runner: 3.4.9 => 3.4.9 
      @tarojs/plugin-framework-react: 3.4.9 => 3.4.9 
      @tarojs/react: 3.4.9 => 3.4.9 
      @tarojs/runtime: 3.4.9 => 3.4.9 
      @tarojs/taro: 3.4.9 => 3.4.9 
      @tarojs/webpack-runner: 3.4.9 => 3.4.9 
      babel-preset-taro: 3.4.9 => 3.4.9 
      eslint-config-taro: 3.4.9 => 3.4.9 
      react: ^17.0.0 => 17.0.2 
      react-native: ^0.67.3 => 0.67.4 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.2.4
```

---
### 补充信息
好像是跟 vue 的类型有关系
<img width="846" alt="aa" src="https://user-images.githubusercontent.com/17918538/168711978-d3f5881f-d591-4fdb-a78a-0eb60ae6d1a6.png">

**Comment by Chen-jj** [comment]
翻一下之前的 issues

**Comment by soeasyjx** [comment]
手动删除 node_modules 里的@type/vue 类型，并且手动注释@vue/runtime-dom/dist/runtime-dom.d.ts 下的 global 类型

说明这个问题没有解决啊，需要使用着都手动处理么

**Comment by soeasyjx** [comment]
> 翻一下之前的 issues

手动删除 node_modules 里的@type/vue 类型，并且手动注释@vue/runtime-dom/dist/runtime-dom.d.ts 下的 global 类型

说明这个问题没有解决啊，需要使用着都手动处理么

**Comment by Chen-jj** [comment]
在之前的 issue 已经回复，并且最新版已解决

**Comment by soeasyjx** [comment]
> 3.4.9

我用的版本是 v3.4.9  在上面我已经给出使用环境信息

**Comment by Chen-jj** [comment]
提供一下 demo咯

**Comment by mefengl** [comment]
@soeasyjx 如果你可以用npm的话，
1. 删掉和yarn相关的文件（类似.yarn，yarn.lock）
2. 删掉package.lock.json（保留package.json）
3. 删掉node_modules
4. 命令行npm install
5. npm run dev:weapp之类的命令应该不会报错了。

**Comment by wenxiuYang** [comment]
我也遇到一样的问题了， 也是最新版本3.4.9， 请问这个有解决吗

**Comment by zhiqingchen** [comment]
试试 package.json 加上

```json
"resolutions": {
    "@types/react": "17.0.45"
  }
```

**Comment by geekact** [comment]
@wenxiuYang  升级插件或者新项目出现的概率很大，昨天刚解决，参考这个方案：https://github.com/foca-js/foca/issues/16#issuecomment-1139454561

**Comment by wenxiuYang** [comment]
> @wenxiuYang 升级插件或者新项目出现的概率很大，昨天刚解决，参考这个方案：[foca-js/foca#16 (comment)](https://github.com/foca-js/foca/issues/16#issuecomment-1139454561)
> 
> 等taro正式支持`react@18`之的时候，这个问题可以自动修复

好嘞， 谢谢 :) , 但是这个方法在我这里并不适用， 目前临时的解决办法： https://github.com/NervJS/taro/issues/11097#issuecomment-1097497205
