### ISSUE TITLE
配置 svga-loader 依旧无法加载 svga 格式的文件

### ISSUE THREAD

**Issue by gonglixin980926** [NervJS/taro#11828]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/gonglixin980926/myTaroApp](https://github.com/gonglixin980926/myTaroApp)
**小程序基础库: 2.42.2**
**使用框架: React**

### 复现步骤
yarn build:weapp

### 期望结果
成功打包

### 实际结果
./src/assets/success.svga 1:1
Module parse failed: Unexpected character '�' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 环境信息
```
  Taro CLI 3.4.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.5 => 3.4.5 
      @tarojs/mini-runner: 3.4.5 => 3.4.5 
      @tarojs/plugin-framework-react: 3.4.5 => 3.4.5 
      @tarojs/react: 3.4.5 => 3.4.5 
      @tarojs/runtime: 3.4.5 => 3.4.5 
      @tarojs/taro: 3.4.5 => 3.4.5 
      @tarojs/webpack-runner: 3.4.5 => 3.4.5 
      babel-preset-taro: 3.4.5 => 3.4.5 
      eslint-config-taro: 3.4.5 => 3.4.5 
      react: ^17.0.0 => 17.0.2 
```

**Comment by gonglixin980926** [comment]
如果这样配置 webpack
```
      chain.merge({
        module: {
          rule: {
            test: /\.svga$/,
            use: 'svga-loader',
          },
        },
      });
```
就会展示以下错误

`/Users/allen/Desktop/person/myTaroApp/node_modules/webpack-chain/src/Rule.js:67
    if (!omit.includes('include') && 'include' in obj) {
                                               ^

TypeError: Cannot use 'in' operator to search for 'include' in svga-loader
    at Rule.merge (/Users/allen/Desktop/person/myTaroApp/node_modules/webpack-chain/src/Rule.js:67:48)
    at /Users/allen/Desktop/person/myTaroApp/node_modules/webpack-chain/src/Module.js:32:25
    at Array.forEach (<anonymous>)
    at module.exports.merge (/Users/allen/Desktop/person/myTaroApp/node_modules/webpack-chain/src/Module.js:31:29)
    at /Users/allen/Desktop/person/myTaroApp/node_modules/webpack-chain/src/Config.js:166:19
    at Array.forEach (<anonymous>)
    at module.exports.merge (/Users/allen/Desktop/person/myTaroApp/node_modules/webpack-chain/src/Config.js:164:15)
    at webpackChain (/Users/allen/Desktop/person/myTaroApp/config/index.js:45:13)
    at /Users/allen/Desktop/person/myTaroApp/node_modules/@tarojs/mini-runner/src/index.ts:18:5
    at Generator.next (<anonymous>)
    at fulfilled (/Users/allen/Desktop/person/myTaroApp/node_modules/@tarojs/mini-runner/dist/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Chen-jj** [comment]
@gonglixin980926 看报错是 webpack-chain 语法问题，检查一下对应语法？

**Comment by gonglixin980926** [comment]
> @gonglixin980926 看报错是 webpack-chain 语法问题，检查一下对应语法？

https://taro-docs.jd.com/taro/docs/guide#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%96%E8%AF%91
我是按照上面 taro 的文档进行配置的，想问下为啥按照这个文档配置的也不可以？
可以看下我的 git 仓库

**Comment by Chen-jj** [comment]
@gonglixin980926 少了一层 `name` 我们改下文档。

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/11807297/169735702-18a8a422-30c9-4578-9859-cc4ce1973b8b.png">

**Comment by gonglixin980926** [comment]
> @gonglixin980926 少了一层 `name` 我们改下文档。
> 
> <img alt="image" width="1786" src="https://user-images.githubusercontent.com/11807297/169735702-18a8a422-30c9-4578-9859-cc4ce1973b8b.png">

好的，这个 name 是自定义的么

**Comment by Chen-jj** [comment]
是的

**Comment by gonglixin980926** [comment]
> 是的
```
      chain.merge({
        module: {
          rule: {
            svgaLoader: {
              test: /\.svga$/,
              use: {
                useLoader: {
                  loader: 'svga-loader'
                  }
                }
              },
          },
        },
      });
```
刚试了下，按上面这种方式配置的可以生效，
加了 name 按原文档配置也无法生效

**Comment by Chen-jj** [comment]
@gonglixin980926 按 webpack-chain 文档为准吧，我们改下 Taro 文档
