### ISSUE TITLE
使用WeUI扩展中的mp-uploader时，选择好图片后没有调用组件的upload方法

### ISSUE THREAD

**Issue by smoothdvd** [NervJS/taro#11835]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/smoothdvd/taro-weui-mp-uploader](https://github.com/smoothdvd/taro-weui-mp-uploader)
**小程序基础库: 2.24.2**
**使用框架: React**

### 复现步骤
1. 点击“ ”号图标
2. 选择一张图片

### 期望结果
选择图片后调用upload方法

### 实际结果
upload方法没有被调用

### 环境信息
```
👽 Taro v3.4.9


  Taro CLI 3.4.9 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    npmPackages:
      @tarojs/components: 3.4.9 => 3.4.9 
      @tarojs/mini-runner: 3.4.9 => 3.4.9 
      @tarojs/plugin-framework-react: 3.4.9 => 3.4.9 
      @tarojs/react: 3.4.9 => 3.4.9 
      @tarojs/runtime: 3.4.9 => 3.4.9 
      @tarojs/taro: 3.4.9 => 3.4.9 
      @tarojs/webpack-runner: 3.4.9 => 3.4.9 
      babel-preset-taro: 3.4.9 => 3.4.9 
      eslint-config-taro: 3.4.9 => 3.4.9 
      react: ^17.0.0 => 17.0.2 
```

**Comment by smoothdvd** [comment]
看来是和这个问题一样: #9650

**Comment by Chen-jj** [comment]
@smoothdvd 把这个限制去掉是否可以？https://github.com/NervJS/taro/blob/5e57252a81409389b85b8786db5d3d9d92246161/packages/taro-react/src/props.ts#L125

**Comment by smoothdvd** [comment]
@Chen-jj 我增加了一段esle if
```
else if (isFunction(value)) {
        console.log('name in function', name);
        console.log('value in function', value);
        console.log('oldValue in function', oldValue);
        dom.setAttribute(name, value);
        console.log(dom);
    }
```
发现dom里已经成功设置了属性upload的值为一个函数
<img width="317" alt="Screen Shot 2022-05-25 at 11 35 09 AM" src="https://user-images.githubusercontent.com/22420/170174449-11b054ce-e0f0-4b23-9d01-51152632e1fe.png">

但最后在组件里的upload属性值仍是null
<img width="475" alt="Screen Shot 2022-05-25 at 11 34 45 AM" src="https://user-images.githubusercontent.com/22420/170174661-3364d0f2-ff61-4d31-9c89-37f3333c3e75.png">

请问是不是哪里还有过滤的代码？

**Comment by Chen-jj** [comment]
setData 有设置上函数么？

**Comment by smoothdvd** [comment]
@Chen-jj 
```
<mp-uploader
  select={() => console.log('select')}
  upload={() => Promise.resolve(console.log('select'))}
  extClass='uploader'
  files={this.state.files}
  maxSize={20 * 1024 * 1024}
  maxCount={9}
  title='失联人照片'
  tips='最多可上传9张照片，每张照片不大20MB。'
  onFail={(e) => console.log(e)}
  delete
  onSuccess={this.onUploadSuccess}
  onDelete={this.onUploadDelete}
/>
```

**Comment by Chen-jj** [comment]
> @Chen-jj 我增加了一段esle if
> 
> ```
> else if (isFunction(value)) {
>         console.log('name in function', name);
>         console.log('value in function', value);
>         console.log('oldValue in function', oldValue);
>         dom.setAttribute(name, value);
>         console.log(dom);
>     }
> ```
> 
> 发现dom里已经成功设置了属性upload的值为一个函数 <img alt="Screen Shot 2022-05-25 at 11 35 09 AM" width="317" src="https://user-images.githubusercontent.com/22420/170174449-11b054ce-e0f0-4b23-9d01-51152632e1fe.png">
> 
> 但最后在组件里的upload属性值仍是null <img alt="Screen Shot 2022-05-25 at 11 34 45 AM" width="475" src="https://user-images.githubusercontent.com/22420/170174661-3364d0f2-ff61-4d31-9c89-37f3333c3e75.png">
> 
> 请问是不是哪里还有过滤的代码？

这是微信小程序的问题，给他们反馈了，我再看看能不能绕过：

https://developers.weixin.qq.com/community/develop/doc/0000a889ed8f50e44b3efe89156400

**Comment by Chen-jj** [comment]
参考 #9650，可以这样绕过：

```js
export default class Index extends Component {
  el = React.createRef()

  onReady () {
    this.el.current.setAttribute('formatter', this.formatter)
  }

  formatter () {
    return function (day) {
      console.log('formatter', day)
    }
  }

  render () {
    return (
      <View>
        <van-calendar ref={this.el} formatter={null} show={true} />
      </View>
    )
  }
}
```
