### ISSUE TITLE
Taro.getSetting()在真机测试时，报error: 1, errorMessage: "API 不存在"

### ISSUE THREAD

**Issue by bobokingbao** [NervJS/taro#11838]
### 相关平台
钉钉小程序

**使用框架: Vue 3**

### 复现步骤
执行如下代码       
 Taro.getSetting({
          success: function (res) {
            console.log(res);
            // res.authSetting = {
            //   "scope.userInfo": true,
            //   "scope.userLocation": true
            // }
          },
        });

### 期望结果
在钉钉小程序IDE中和真机调试中都取得正确的值

### 实际结果
在钉钉小程序IDE中可以取得正常的值，但是在真机调试中报出了“error: 1, errorMessage: "API 不存在"的错误

### 环境信息
```
� Taro v3.3.19


  Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
使用原生语法试试，看着是钉钉小程序的问题

**Comment by bobokingbao** [comment]
用原生的可以，感觉是我使用的钉钉SDK的版本和Taro的版本之间没有匹配上。
钉钉小程序IDE调试的时候显示的编译环境如下：
dingtalk/SDKVersion: 1.25.7
​Lyra Version: 6.1.27

**Comment by bobokingbao** [comment]
我调试了虾，Taro正常的将语法编译成了钉钉的a.setting()的方法，IDE模拟器没问题。
然后，我真机测试时，直接运行不加断点就报出了那个错误。但是当我debug的时候一步步走的时候没报错，但是success，和fail的返回函数都没进去。
感觉更像时我手机的问题，先暂时关闭这个issue，等以后再调查。
