### ISSUE TITLE
Taro 显示更新成功 但是，查看的时候还是原来的版本

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1183]
Taro 1.0.7 更新到最新，显示 版本更新成功了，但是Taro --version 还是显示 1.0.7

**Comment by nyrf** [comment]
我以前也遇到过，后来发现我是yarn和npm都安装过一遍，我把这两个安装的全删了，重新用npm安装后，后来再没遇到过，你可以先把原来的删后再安装，以后应该不会再有这种情况了

**Comment by yuche** [comment]
yarn remove 和 npm remove 再装，如果你用 yarn，cnpm，npm 混合使用过就有这种情况
