### ISSUE TITLE
支持解析 package.json 里的 browser 属性

### ISSUE THREAD

**Issue by mefengl** [NervJS/taro#11832]
### 这个特性解决了什么问题？
「因为 Taro 不支持解析 package.json 里的 browser 属性，导致所有使用了该特性的包都可能无法在 Taro 里正常运行。不幸的是，axios 就是其中之一。」
--来自[taro-axios](https://github.com/fjc0k/taro-axios)的readme

### 这个 API 长什么样？
支持解析 package.json 里的 browser 属性，从而能使用axios不报错。

**Comment by Chen-jj** [comment]
> 因为 Taro 不支持解析 package.json 里的 browser 属性

@mefengl 目前小程序和 H5 的 Webpack 配置中，mainFields 都是配置支持了 `browser` 的。这个问题应该不存在了，你可以直接引用 `axios` 试试。但稍微看了下 `taro-axios`，它里面有设置针对小程序网络 API 的 Adapter，目测你直接使用 `axios` 还是要手动设置 Adapter。
