### ISSUE TITLE
3.5.0更新失败

### ISSUE THREAD

**Issue by ajuner** [NervJS/taro#11847]
### 相关平台
微信小程序

**小程序基础库: default**
**使用框架: React**

### 复现步骤
没有更新脚手架  直接在原有项目上更新

1. 打开example下的custom-tabbar-react项目
2. 按文章步骤升级3.5.0-beta.0
3. 报错
![image](https://user-images.githubusercontent.com/53512912/170408040-7ae71508-9691-4d84-ad9b-09c82b07d9d0.png)

### 期望结果
正常启动

### 实际结果
失败

### 环境信息
```
  Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\caiju\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
CLI 也要更新一下

**Comment by ajuner** [comment]
还有个问题，esbuild执行的时候有没有配置的入口
我在页面中引用 ../custom组件的时候  只有 /custom/index.tt.tsx  /custom/index.weapp.tsx  /custom/index.alipay.tsx
并没有 /custom/index.tsx的文件导致报错

**Comment by ajuner** [comment]
![image](https://user-images.githubusercontent.com/53512912/170409400-fcebd62d-e162-42a7-8d7d-0c93945580bd.png)
cli更新了  还是报错

**Comment by Chen-jj** [comment]
> 我在页面中引用 ../custom组件的时候 只有 /custom/index.tt.tsx /custom/index.weapp.tsx /custom/index.alipay.tsx
并没有 /custom/index.tsx的文件导致报错

感谢反馈，这种情况之前没有考虑到，我们回归一下。

`custom-tabbar` 我看看是什么问题，晚点回复

**Comment by weilaiqishi** [comment]
确实确实  启动失败 esbuild报的错

**Comment by weilaiqishi** [comment]
我怀疑没有测试在windows平台上的兼容性。。。  esbuild预编译依赖好像因为路径问题报错了
![image](https://user-images.githubusercontent.com/22250972/171035796-dd330774-9eb1-4231-af80-41ed64e62c5b.png)

我尝试改了`@tarojs/webpack5-runner/dist/prebundle/bundle.js`里面路径处理成双斜杠就能正常打包了
![image](https://user-images.githubusercontent.com/22250972/171035886-554b785a-8541-4b15-aa0d-87ffb0041daa.png)

 期望能回归一下
@Chen-jj

**Comment by ajuner** [comment]
debug中还遇到一些问题一起记录下，我也做了修改路径的处理后是可以了
但是会提示一个找不到.taro/remote下的错误，需要手动创建remote文件夹后webpack正常启动
小程序中提示prebundle中的js没找到发现prebundle文件夹为空
![image](https://user-images.githubusercontent.com/53512912/171140391-fff3aaed-eb73-4642-8322-93617ad59d9a.png)
另外热更新速度比原来快了十几秒真的非常期待了

**Comment by Chen-jj** [comment]
> 但是会提示一个找不到.taro/remote下的错误，需要手动创建remote文件夹后webpack正常启动 小程序中提示prebundle中的js没找到发现prebundle文件夹为空 

@ajuner 这个问题能提供一下 demo 么？

**Comment by ajuner** [comment]
不太好定位，是老项目的升级出的问题，到第三步webpack没打到remote里，新项目没问题，打算慢慢迁移找下问题
![1654002289(1)](https://user-images.githubusercontent.com/53512912/171180043-60f3c1cc-0bc1-4f61-b0b1-07fc6482dffd.png)

**Comment by Chen-jj** [comment]
@ajuner 可以看看 prebundle 了哪些依赖，然后尝试 [exclude](https://docs.taro.zone/docs/config-detail#compilerprebundleexclude) 掉看看。

**Comment by ajuner** [comment]
所有都exclude了  还是有错 😭

**Comment by ajuner** [comment]
定位到了
用了dotenv把NODE_ENV设置成了production
但是config文件里面设置的NODE_ENV是development
修改后能正常打包了  但又有新的问题
![image](https://user-images.githubusercontent.com/53512912/171319855-70368c38-57de-44fd-9c32-0f43bdd948eb.png)

**Comment by ajuner** [comment]
mini-html-parser2 这个包有问题打包后会报错  exclude后就行了

**Comment by Chen-jj** [comment]
> 我怀疑没有测试在windows平台上的兼容性。。。 esbuild预编译依赖好像因为路径问题报错了 

Windows 路径问题已修复：https://github.com/NervJS/taro/commit/8099c28df61c033c86e3e819dff3d59400f21bde

**Comment by Chen-jj** [comment]
@ajuner `custom-tabbar-react` 我升级了一下，验证了是能正常跑的，可以对比一下此 commit: https://github.com/NervJS/taro/commit/1fc21cdc19e42369b7f0321e5112207c8985ca0d。猜测是依赖问题
