### ISSUE TITLE
dumi 支持

### ISSUE THREAD

**Issue by tiyunchen** [NervJS/taro#11841]
### 这个特性解决了什么问题？
我们在开发一个taro的组件库，但是我们希望能够利用dumi的实时预览和api props 生成能力，目前我们解决了组件渲染问题，也就是我们的代码不报错了，但是，有些组件不能被渲染，eg:  Image 就不能被渲染出来，Input 组件也不能渲染出来。
我们是通过
![image](https://user-images.githubusercontent.com/24793416/170161698-0e837bd5-3f48-49a6-905f-b72b470ffbc0.png)
这个来解决渲染问题，

希望这个图片组件能够被正常渲染
![image](https://user-images.githubusercontent.com/24793416/170161960-8c8afa15-d2ec-493d-934b-4e56fb61b900.png)

### 这个 API 长什么样？
希望有个基于dumi的文档库例子，或提供教程

**Comment by Chen-jj** [comment]
@tiyunchen 和 StoryBook 或其它 H5 项目一样，需要修改一些 Webpack 配置和引入 WebComponents 的启动代码。文档：https://docs.taro.zone/docs/external-libraries#storybook

**Comment by tiyunchen** [comment]
![image](https://user-images.githubusercontent.com/24793416/170204971-fed8d078-9e68-43b7-926a-ae1e35891ca3.png)
![image](https://user-images.githubusercontent.com/24793416/170205025-5425d102-0c53-41a3-90f7-a00c1b4575de.png)
![image](https://user-images.githubusercontent.com/24793416/170205094-fe232022-2148-4f00-8fdb-fe59ce9b77db.png)
我报了这个问题，这是什么原因？
