### ISSUE TITLE
usingComponents怎么用

### ISSUE THREAD

**Issue by 553082694** [NervJS/taro#11856]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
全局配置 ./src/app.config.js
usingComponents: {
        'loading': 'components/Loading/index'
 }

自定义组件 ./src/components/Loading/index.jsx
export default class Loading extends React.Component {
    render() {
        return (
            <View className='yft-toast'>
                loading
            </View>
        )
    }
}

### 期望结果
正常使用

### 实际结果
Component is not found in path "components/Loading/index" (using by "comp")(env: macOS,mp,1.05.2204250; lib: 2.17.0)
e @ VM758 WAService.js:2
e @ VM758 WAService.js:2
e @ VM758 WAService.js:2
e @ VM758 WAService.js:2
gt @ VM758 WAService.js:2
Tt @ VM758 WAService.js:2
value @ VM758 WAService.js:2
nn @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
cn @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
c.emit @ VM758 WAService.js:2
emit @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
c.emit @ VM758 WAService.js:2
emit @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
c @ VM13 asdebug.js:1
l @ VM13 asdebug.js:1
(anonymous) @ VM13 asdebug.js:1
f @ VM13 asdebug.js:1
g @ VM13 asdebug.js:1
(anonymous) @ VM13 asdebug.js:1
_ws.onmessage @ VM13 asdebug.js:1
VM758 WAService.js:2 Component is not found in path "components/Loading/index" (using by "custom-wrapper")(env: macOS,mp,1.05.2204250; lib: 2.17.0)
e @ VM758 WAService.js:2
e @ VM758 WAService.js:2
e @ VM758 WAService.js:2
gt @ VM758 WAService.js:2
Tt @ VM758 WAService.js:2
value @ VM758 WAService.js:2
nn @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
cn @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
c.emit @ VM758 WAService.js:2
emit @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
c.emit @ VM758 WAService.js:2
emit @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
(anonymous) @ VM758 WAService.js:2
c @ VM13 asdebug.js:1
l @ VM13 asdebug.js:1
(anonymous) @ VM13 asdebug.js:1
f @ VM13 asdebug.js:1
g @ VM13 asdebug.js:1
(anonymous) @ VM13 asdebug.js:1
_ws.onmessage @ VM13 asdebug.js:1
VM758 WAService.js:2 Component is not found in path "components/Loading/index" (using by "pages/HomeScreen/index")(env: macOS,mp,1.05.2204250; lib: 2.17.0)

### 环境信息
```
👽 Taro v3.4.3


  Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.5/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    npmPackages:
      @tarojs/components: 3.3.7 => 3.3.7 
      @tarojs/mini-runner: 3.3.7 => 3.3.7 
      @tarojs/react: 3.3.7 => 3.3.7 
      @tarojs/runtime: 3.3.7 => 3.3.7 
      @tarojs/taro: 3.3.7 => 3.3.7 
      @tarojs/webpack-runner: 3.3.7 => 3.3.7 
      babel-preset-taro: 3.3.7 => 3.3.7 
      eslint-config-taro: 3.3.7 => 3.3.7 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
```

**Comment by Chen-jj** [comment]
@553082694 提供一下复现仓库吧
