### ISSUE TITLE
rn模板生成的项目里的命令upgradePeerdeps，和yarn强制绑定了，无法使用npm、pnpm等管理工具

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [NervJS/taro#11854]
### 相关平台
React Native

### 复现仓库
[https://github.com/111/111](https://github.com/111/111) （这个仓库乱写的，因为这问题可直接通过taro生成）

**使用框架: React**

### 复现步骤
1. `taro init myApp` 【依次选React 、Typescript、Sass、react-native】(基本是一路默认，最后选了 react-native )
2. 待文件创建成功后，进入目录，执行 `pnpm i`  ,  （我选的包管理工具是pnpm）
3. 接着执行 `pnpm upgradePeerdeps` ,就能看到输出里，有个地方硬编码为了yarn

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/104620424/170806402-13c156ae-a7ff-4042-83b5-3a5b2ab08111.png">

### 期望结果
期待可以自由选择包管理工具

### 实际结果
猜测可能是官方硬编码为了yarn，导致无法使用npm， pnpm等包管理工具

### 环境信息
```
👽 Taro v3.4.10


  Taro CLI 3.4.10 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/Library/pnpm/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.10 => 3.4.10 
      @tarojs/components: 3.4.10 => 3.4.10 
      @tarojs/mini-runner: 3.4.10 => 3.4.10 
      @tarojs/plugin-framework-react: 3.4.10 => 3.4.10 
      @tarojs/react: 3.4.10 => 3.4.10 
      @tarojs/rn-runner: 3.4.10 => 3.4.10 
      @tarojs/runtime: 3.4.10 => 3.4.10 
      @tarojs/taro: 3.4.10 => 3.4.10 
      @tarojs/taro-rn: 3.4.10 => 3.4.10 
      @tarojs/webpack-runner: 3.4.10 => 3.4.10 
      babel-preset-taro: 3.4.10 => 3.4.10 
      eslint-config-taro: 3.4.10 => 3.4.10 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.3 => 0.67.4 
```

**Comment by shinken008** [comment]
https://github.com/NervJS/taro-project-templates/blob/c28cf4eee42ae131665915303ede01b7230ecd88/react-native/package.json.tmpl#L34

生成的模板里面，install-peerdeps 脚本 `install-peerdeps @tarojs/taro-rn@3.4.1 -o -Y `，Y指yarn，可指定其他包管理工具，参考 install-peerdeps 包

https://www.npmjs.com/package/install-peerdeps

**Comment by hu-tu-yi-shi** [comment]
谢谢
