### ISSUE TITLE
编译为微信小程序后，原 react 中 children 无法传参。

### ISSUE THREAD

**Issue by fanxinjie** [NervJS/taro#11865]
### 相关平台
微信小程序

**小程序基础库: v3.4.7**
**使用框架: React**

### 复现步骤
关于 taro 编译为微信原生的场景，目前编译为原生组件仅支持 react，那么 react 中 children 在编译后如何传参呢？目前微信小程序内默认 slot 是拿不到数据的。

### 期望结果
默认子 dom 在 自定义组件内可以获取到

### 实际结果
默认子 dom 在 自定义组件内不可以获取到

### 环境信息
```
👽 Taro v3.4.7


  Taro CLI 3.4.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      eslint-config-taro: 3.3.16 => 3.3.16 
    npmGlobalPackages:
      typescript: 4.5.4
```

**Comment by Chen-jj** [comment]
@fanxinjie 没有理解什么意思，麻烦提供一下 demo

**Comment by fanxinjie** [comment]
@Chen-jj 抱歉，是我没有考虑周到。

复现 demo 地址：https://github.com/fanxinjie/belended-taro-component。

使用 **taro-react 框架**，在官方给出的 demo 基础上新增 button 组件，且**希望通过 props.children 获取 微信原生页面使用时传入的 slot 默认子节点。**


### taro 项目内实现
```jsx
import React from 'react';
import Taro from '@tarojs/taro'
import { View, Slot } from '@tarojs/components'

export default function (props) {
  console.log('props', props)
  return (
    <View>
      <View>Button demo</View>
      {props.children}
    </View>
  )
}
```


### 原生微信使用写法

如：[当前可以获取到数据的写法](https://github.com/fanxinjie/belended-taro-component/blob/master/miniapp/pages/index/index.wxml#L20)

index.wxml
```wxml
 <CusButton props="{{buttonProps}}" />
```
index.js
```js
buttonProps = {
  type: 'primary',
  children: 'props show'
}
```

### 期望的使用方式

期望默认获取到 slot ，而不是通过 props.children 字段传参。例如下面例子，在 taro打包出的组件内获取不到 <view>slot show </view> 节点的。

如：[期望的写法](https://github.com/fanxinjie/belended-taro-component/blob/master/miniapp/pages/index/index.wxml#L22)

index.wxml
```wxml
<CusButton props="{{buttonProps}}" >
  <view>slot show </view>
</CusButton>
```
index.js
```js
buttonProps = {
  type: 'primary',
}
```

**Comment by fanxinjie** [comment]
@chenchen
大佬，目前有进展吗~

**Comment by qianlongdoit** [comment]
mark

**Comment by taikongfeizhu** [comment]
> ### 相关平台
> 微信小程序
> 
> **小程序基础库: v3.4.7** **使用框架: React**
> 
> ### 复现步骤
> 关于 taro 编译为微信原生的场景，目前编译为原生组件仅支持 react，那么 react 中 children 在编译后如何传参呢？目前微信小程序内默认 slot 是拿不到数据的。
> 
> ### 期望结果
> 默认子 dom 在 自定义组件内可以获取到
> 
> ### 实际结果
> 默认子 dom 在 自定义组件内不可以获取到
> 
> ### 环境信息
> ```
> 👽 Taro v3.4.7
> 
> 
>   Taro CLI 3.4.7 environment info:
>     System:
>       OS: macOS 10.14.6
>       Shell: 5.3 - /bin/zsh
>     Binaries:
>       Node: 14.17.0 - /usr/local/bin/node
>       Yarn: 1.21.1 - /usr/local/bin/yarn
>       npm: 6.14.13 - /usr/local/bin/npm
>     npmPackages:
>       eslint-config-taro: 3.3.16 => 3.3.16 
>     npmGlobalPackages:
>       typescript: 4.5.4
> ```

老哥，这个问题解决了吗？

**Comment by Chen-jj** [comment]
原生传子元素到 Taro 组件中，这种情况之前没有考虑到，所以暂时还没支持

**Comment by Chen-jj** [comment]
v3.6.7 开始支持
