### ISSUE TITLE
Uncaught ReferenceError: ENABLE_INNER_HTML is not defined

### ISSUE THREAD

**Issue by 946629031** [NervJS/taro#11877]
### 相关平台
H5

### 复现仓库
[https://github.com/noUrl](https://github.com/noUrl)
**浏览器版本: chrome 101.0.4951.64**
**使用框架: React**

### 复现步骤
1.在一个普通webpack项目中，`npm i @tarojs/taro`

2.在一个业务页面中
```js
import Taro from '@tarojs/taro'

    Taro.request({
      url: 'test.php', //仅为示例，并非真实的接口地址
      data: {
        x: '11',
        y: '22'
      },
      header: {
        'content-type': 'application/json' // 默认值
      },
      method: 'GET',
      success: function (res) {
        console.log(res.data)
      }
    })
```

3.打开项目，并访问该页面，然后你就会得到报错

### 期望结果
能够正常发起网络请求

### 实际结果
Chrome console 面板报错
```js
runtime.esm.js:3792 

Uncaught ReferenceError: ENABLE_INNER_HTML is not defined
    at TaroNodeImpl.bind (runtime.esm.js:3792:1)
    at new TaroNode (runtime.esm.js:1651:1)
    at new TaroElement (runtime.esm.js:2331:1)
    at new TaroDocument (runtime.esm.js:3873:1)
    at _createInstance (instantiation.js:27:1)
    at Object.resolveInstance (instantiation.js:47:1)
    at resolver.js:75:1
    at Object.resolve (resolver.js:99:1)
    at container.js:335:1
    at Container../node_modules/inversify/lib/container/container.js.Container._get (container.js:326:1)
```

### 环境信息
```
Taro v3.4.10


  Taro CLI 3.4.10 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.10 => 3.4.10
      @tarojs/components: 3.4.10 => 3.4.10
      @tarojs/mini-runner: 3.4.10 => 3.4.10
      @tarojs/plugin-framework-react: 3.4.10 => 3.4.10
      @tarojs/react: 3.4.10 => 3.4.10
      @tarojs/runtime: 3.4.10 => 3.4.10
      @tarojs/taro: 3.4.10 => 3.4.10
      @tarojs/webpack-runner: 3.4.10 => 3.4.10
      babel-preset-taro: 3.4.10 => 3.4.10
      eslint-config-taro: 3.4.10 => 3.4.10
      react: ^17.0.0 => 17.0.2
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.2


"@tarojs/taro": "^3.4.10",
npm: 6.14.16
node 14.19.0

```

**Comment by Jeff-Tian** [comment]
我也碰到这个问题了。https://github.com/Jeff-Tian/weapp

**Comment by Chen-jj** [comment]
> 我也碰到这个问题了。https://github.com/Jeff-Tian/weapp
> 
> <img alt="image" width="1018" src="https://user-images.githubusercontent.com/3367820/179904837-967c648e-5440-4222-aa64-f9dfc7e21353.png">

https://docs.taro.zone/docs/external-libraries#jest

**Comment by Jeff-Tian** [comment]
谢谢，问题已解决！

**Comment by ApeWhoLovesCode** [comment]
您好，请问是怎么配置的吗，我配置jest.config无效，复现demo: https://github.com/ApeWhoLovesCode/test-react-taro

**Comment by Jeff-Tian** [comment]
> 您好，请问是怎么配置的吗，我配置jest.config无效，复现demo: https://github.com/ApeWhoLovesCode/test-react-taro

按照大佬的提示配置后就好了。

https://github.com/Jeff-Tian/weapp/commit/c0826792d815e6b9b75ac8dfb256e7d5841656b0#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R1-R10

**Comment by ApeWhoLovesCode** [comment]
> > 您好，请问是怎么配置的吗，我配置jest.config无效，复现demo: https://github.com/ApeWhoLovesCode/test-react-taro
> 
> 按照大佬的提示配置后就好了。
> 
> [Jeff-Tian/weapp@c082679#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R1-R10](https://github.com/Jeff-Tian/weapp/commit/c0826792d815e6b9b75ac8dfb256e7d5841656b0#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R1-R10)

我看您的修改，应该是jest.confi.js文件里面的配置是与taro有关的，我也配置了这个文件，但是它好像是没起到作用的。
