### ISSUE TITLE
子组件获取props值有问题

### ISSUE THREAD

**Issue by xuangu** [NervJS/taro#1187]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
在父组件中并发多次setState时，在子组件的render方法中获取父组件传进来的props大概率出现异常情况
**复现步骤**
[复现问题的步骤]
1. 在父组件的componentDidMount同时发出四个异步网络请求，每个网络请求回来后根据响应数据setState
2. 每次setState引发父组件的render方法，并且在render方法中拿到的都是更新后的数据
3. 将更新后的数据传给子组件的props，引发子组件的render方法
4. 在子组件的render方法中大概率获取父组件传递的props的值异常。

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
父组件代码：
  componentDidMount() {
    console.log('begin fetch data')
    this.fetchData1();
    this.fetchData2();
    this.fetchData3();
    this.fetchData4();
  }

  fetchData1() {
    request(params1).then((res) => {
      this.setState({data1: res})
    })
  }
  其余三个请求类似
  
  render() {
    const {data1, data2, data3, data4} = this.state;
    <SubComponent
      data1={data1}
      data2={data2}
      data3={data3}
      data4={data4}
    />
  }

子组件代码
  render() {
     console.log(this.props.data1, this.props.data2, this.props.data3, this.props.data4 )
 }

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
期望每次在子组件中拿到的都是父组件最新的值
**报错信息**
大概率情况下在子组件中拿不到父组件中的值（有时多刷几次会好），是个概率问题。
[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/6736095/48764574-f7481980-ecea-11e8-8401-b544cf44a2e9.png)

**系统信息**

 - 操作系统: [e.g. macOS10.14]
 - Taro 版本 [e.g. v.1.1.8]
 - Node.js 版本 [e.g. v10.4.1]
 - 报错平台 [swan]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
因为项目中也用了Taro的Redux，在每次网络请求回来后，都会通过redux去dispatch数据，然后更新全局store中的state，在父组件render函数中拿到的state数据也是对的，但就是往子组件传的时候，会大概率出问题，多刷几次会好，所以怀疑是多次setState时，Taro在进行diff时，出了问题，或者是因为往子组件传递的JSON数据结构比较复杂，Taro在拷贝数据时，由于浅拷贝丢了数据。

**Comment by nyrf** [comment]
props传object类型时是会有问题 有点和https://github.com/NervJS/taro/issues/1065这个类似，我睦最新的提交已经修复了，不过还没发布新版。

**Comment by Chen-jj** [comment]
@xuangu 复现不了，你提供下可稳定复现的完整代码吧。request 用 setTimeout 代替，数据用模拟数据

**Comment by xuangu** [comment]
> props传object类型时是会有问题 有点和 #1065 这个类似，我睦最新的提交已经修复了，不过还没发布新版。
这个啥时候发新版呀？

**Comment by Chen-jj** [comment]
@xuangu 你先把你出错的代码发一下，不一定是同一个问题

**Comment by xuangu** [comment]
> @xuangu 你先把你出错的代码发一下，不一定是同一个问题

好的，稍等晚点我发出来，代码有点乱，需要整理一下。麻烦了
