### ISSUE TITLE
支付宝设置分包后，路由无法跳转。

### ISSUE THREAD

**Issue by Link-X** [NervJS/taro#11871]
### 相关平台
支付宝小程序

**小程序基础库: 默认配置**
**使用框架: React**

### 复现步骤
###最小化仓库
https://github.com/Link-X/alipay-sub.git
```javascript
// 文件目录结构
-- src
    -- pages
         -- index
    -- subpackages
          --manage
             -- test-page
// 跳转方式
// 点击后
Taro.navigateTo({
  url: "/subpackages/manage/test-page/index"
});
// app.config
export default {
  pages: ["pages/index/index"],
  subpackages: [
    {
      root: "subpackages/manage",
      pages: ["test-page/index"],
    }
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black"
  }
};

```

### 期望结果
支付宝小程序也能正常跳转

### 实际结果
微信小程序正常跳转到子包路由
支付宝小程序控制台报错
Error: framework error: can not find page: subpackages/manage/test-page/index when execute navigateTo for url /subpackages/manage/test-page/index

### 环境信息
```
Taro v3.4.10


  Taro CLI 3.4.10 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.10 => 3.4.10 
      @tarojs/components: 3.4.10 => 3.4.10 
      @tarojs/mini-runner: 3.4.10 => 3.4.10 
      @tarojs/plugin-framework-react: 3.4.10 => 3.4.10 
      @tarojs/react: 3.4.10 => 3.4.10 
      @tarojs/runtime: 3.4.10 => 3.4.10 
      @tarojs/taro: 3.4.10 => 3.4.10 
      @tarojs/webpack-runner: 3.4.10 => 3.4.10 
      babel-preset-taro: 3.4.10 => 3.4.10 
      eslint-config-taro: 3.4.10 => 3.4.10 
      react: ^17.0.2 => 17.0.2 
      taro-ui: 3.1.0-beta.2 => 3.1.0-beta.2 
```

**Comment by Link-X** [comment]
> Taro.navigateTo({ url: "/pages/subpackages/manage/test-page/index" });
> 
> 所有页面都要放在pages下面 哦！

支付宝不支持分包么？

**Comment by konka-king** [comment]
> > Taro.navigateTo({ url: "/pages/subpackages/manage/test-page/index" });
> > 所有页面都要放在pages下面 哦！
> 
> 支付宝不支持分包么？

我前面说错了

https://docs.taro.zone/docs/guide#%E5%88%86%E5%8C%85

具体看这个 subpackages 改成 subPackages 应该就好了

**Comment by Link-X** [comment]
> > > Taro.navigateTo({ url: "/pages/subpackages/manage/test-page/index" });
> > > 所有页面都要放在pages下面 哦！
> > 
> > 
> > 支付宝不支持分包么？
> 
> 支持，我前面说错了
> 
> https://docs.taro.zone/docs/guide#%E5%88%86%E5%8C%85
> 
> 具体看这个 subpackages 改成 subPackages 应该就好了

破案了，非常感谢大佬的解惑。

后面如果有一样遇到问题的。把subpackages 改成 subPackages。第二个单词首字母大写，就可以兼容支付宝分包了。话说文档那行注释真的很难看到...

**Comment by Link-X** [comment]
解决

**Comment by Link-X** [comment]
> 非tarobug
