### ISSUE TITLE
抖音小程序showtoast icon为error时显示错误

### ISSUE THREAD

**Issue by zwqdev** [NervJS/taro#11879]
### 相关平台
字节跳动小程序

**小程序基础库: 2.49**
**使用框架: React**

### 复现步骤
Taro.showToast(icon: 'error')

### 期望结果
显示error图标

### 实际结果
显示成功图标

### 环境信息
```
Taro v3.4.8


  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\00100301\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@zwqdev 直接 tt.showtoast 试试

**Comment by occultskyrong** [comment]
> @zwqdev 直接 tt.showtoast 试试

肯定不行啊，抖音的文档写的 icon 可选值只有  `success,loading, none,fail`

> https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/api/interface/interfeedback/tt-show-toast/

就没有 `error` 这个选项

应该需要taro框架在编译的时候，抖音的把 `error` 转换成 `fail` 

哈哈哈，抖音抄都抄错了。。刺激

**Comment by zwqdev** [comment]
@Chen-jj 我知道可以呀，只是提醒这个API有兼容性问题

**Comment by Chen-jj** [comment]
@zwqdev 好的，和支付宝小程序类似，Taro 需要在框架层抹平差异。先使用 `fail` 代替咯，也欢迎 PR ~
