### ISSUE TITLE
关于CustomWrapper下无法使用原生组件

### ISSUE THREAD

**Issue by ksora94** [NervJS/taro#11887]
### 这个特性解决了什么问题？
当customWrapper包裹原生组件时，无法修改其usingComponents配置，导致小程序出现原生组件未定义的报错。

目前未在文档中找到相关修改方式。希望能够增加这一功能，提升customWrapper组件使用的灵活性。

### 这个 API 长什么样？

1. 在项目根目录或合适位置增加customWrapper配置文件，比如customWrapper.config.ts，能够覆盖现有配置。
2. ~~为customWrapper组件增加props，可以动态传入usingComponents等配置~~（可能得编译多个customWrapper组件，不太合适）

**Comment by ksora94** [comment]
突然意识到如果支持这个功能，customWrapper包裹下的原生组件与父组件通信可能不太好处理了？或许不是增加一个配置文件这么简单。

**Comment by Barrierml** [comment]
微信和支付宝都是支持的
