### ISSUE TITLE
能否支持 unplugin-auto-import 自动引入？

### ISSUE THREAD

**Issue by aliuq** [NervJS/taro#11899]
### 这个特性解决了什么问题？
解决小程序开发过程中繁琐的 API import 语句

### 这个 API 长什么样？
通过提供一个 `metadata.json`  API 列表，并在 `unplugin-auto-import` resolvers 下添加一个适配的方法，虽然类型声明能够自动构建，但还是希望官方大大能够支持

**Comment by J1angyue** [comment]
taro 是否已经支持了 unplugin-auto-import/webpack，plugins要怎么配置啊？

**Comment by yoyo837** [comment]
Duplicate of #14214
