### ISSUE TITLE
[RN] Taro.getStorage  then  catch 方法不执行 android手机[huawei META9]

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#1189]
**问题描述**
[RN] Taro.getStorage  then  catch 方法不执行

**复现步骤**
[复现问题的步骤]
1. Taro.getStorage({key:'key'}).then(res=>{ console.log(res) }).catch(err=>{console.error(err)})
2. RN环境中运行

```js
Taro.getStorage({key:'key'}).then(res=>{ console.log(res) }).catch(err=>{console.error(err)})

```

**期望行为**
执行then或者catch方法

**报错信息**
没有报错,函数不执行[IOS]手机正常

**系统信息**

 - 操作系统: [e.g.  huawei META 9]
 - Taro 版本 [e.g. v.1.1.8]
 - Node.js 版本 [e.g. v10.9.0]
 - 报错平台 [RN]

**Comment by Bless-L** [comment]
刚跑了一下，目测是因为没有安装@tarojs/taro-rn这个包。这个应该在默认模板里就有的，问题修复中
