### ISSUE TITLE
H5 版本的 SwiperItem 不支持 array 类型的子元素

### ISSUE THREAD

**Issue by Leechael** [NervJS/taro#1190]
**问题描述**
H5 版本的 SwiperItem 不支持 array 类型的子元素

**复现步骤**

```js
<Swiper>
  <SwiperItem>
    { aList.map((s, k) => (<Text key="k">{s}</Text>)) }
  </SwiperItem>
</Swiper>
```

**期望行为**
小程序版本的 SwiperItem 是支持 SwiperItem 里面嵌套 Array 类型的子元素，H5 版本的 SwiperItem 也应该支持这一行为。

**报错信息**

抛出错误：`Uncaught (in promise) TypeError: Cannot read property 'className' of undefined`，定位到问题在的位置是这里：https://github.com/NervJS/taro/blob/master/packages/taro-components/src/components/swiper/swiper.js#L470

**Comment by jinjinjin0731** [comment]
感谢修改的 PR 已修复
