### ISSUE TITLE
vue3 setup 函数 触发两次

### ISSUE THREAD

**Issue by gowago** [NervJS/taro#11903]
### 相关平台
H5

**浏览器版本: Chrome  100**
**使用框架: Vue 3**

### 复现步骤
1 A页面路由跳转到b页面
2 B页面重定向到A页面  

### 期望结果
setup 函数触发一次

### 实际结果
`<script setup> `A页面setup内函数加载两次

### 环境信息
  Taro CLI 3.4.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.5 - D:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@gowago 麻烦提供一下可复现 demo

**Comment by ZakaryCode** [comment]
缺少可复现问题信息，issue 将被关闭
