### ISSUE TITLE
request的onHeadersReceived is not a function

### ISSUE THREAD

**Issue by Shen120** [NervJS/taro#11904]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Shen120/taro-request-bug.git](https://github.com/Shen120/taro-request-bug.git)
**小程序基础库: 2.23.4**
**使用框架: React**

### 复现步骤
更改src>utils>request.ts的Host，然后发起请求，就能复现，

### 期望结果
能够正常使用onHeadersReceived 

### 实际结果
报错 not a function

### 环境信息
```
Taro v3.4.11


  Taro CLI 3.4.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\scc\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
提issue的时候，里面的版本选项无法选择3.4.11

**Comment by Shen120** [comment]
https://github.com/NervJS/taro/issues/11224
我看见在3.4.8版本下已经修复，但是我这边还是不正常

**Comment by AdvancedCat** [comment]
My mistake and i will fix it soon.

**Comment by Shen120** [comment]
> My mistake and i will fix it soon.

great！Baby

**Comment by Shen120** [comment]
@AdvancedCat When to update?

**Comment by AdvancedCat** [comment]
Will publish into next patch.
