### ISSUE TITLE
picker组件需要支持国际化（取消和确认没办法修改）

### ISSUE THREAD

**Issue by XuLessReigns** [NervJS/taro#11918]
### 这个特性解决了什么问题？
支持国际化

### 这个 API 长什么样？
支持语言配置或者文案配置

**Comment by Chen-jj** [comment]
H5 还是小程序？H5 还能开放配置。小程序就没办法了，因为小程序控件自身并不支持配置。

**Comment by XuLessReigns** [comment]
h5和小程序都希望有~， 现在国际化页面使用了下拉框picker，有什么临时方案可以解决的吗

**Comment by ZakaryCode** [comment]
Duplicate of #12489
