### ISSUE TITLE
RN端cssModule不能用className,只能用style代替

### ISSUE THREAD

**Issue by WhiteSean** [NervJS/taro#11912]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
cssModule使用className即可重现

### 期望结果
希望cssModule能支持使用className

### 实际结果
不支持className

### 环境信息
```

  Taro CLI 3.3.19 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.10 => 3.4.10 
      @tarojs/components: 3.4.10 => 3.4.10 
      @tarojs/react: 3.4.10 => 3.4.10 
      @tarojs/runtime: 3.4.10 => 3.4.10 
      @tarojs/taro: 3.4.10 => 3.4.10 
      babel-preset-taro: 3.4.10 => 3.4.10 
      eslint-config-taro: ^3.2.12 => 3.4.11 
      react: ^17.0.0 => 17.0.2 
      react-native: ^0.67.3 => 0.67.4 
    npmGlobalPackages:
      typescript: 4.1.3
```

**Comment by shinken008** [comment]
请提供复现代码或者demo

**Comment by WhiteSean** [comment]
> 请提供复现代码或者demo
只要拿个支持cssModule的RN工程，写个样式就能复现
 <View className={styles['container']}>
      <View>Home 1212</View>

      <View onClick={onTest}>点击按钮</View>
    </View>

**Comment by shinken008** [comment]
https://taro-docs.jd.com/taro/docs/css-modules

```js
rn: {
    postcss: {
      cssModules: {
        enable: true
      }
    }
  }
  ```

**Comment by shinken008** [comment]
如何使用：以 module.xx结尾的样式
```js
import styles from './index.module.scss'

<View className={styles.green}>css module</View>
```

**Comment by WhiteSean** [comment]
> 如何使用：以 module.xx结尾的样式
> 
> ```js
> import styles from './index.module.scss'
> 
> <View className={styles.green}>css module</View>
> ```

这个是近期支持的吗，我14天之前就是这样写的，是不行的

**Comment by shinken008** [comment]
不是最近支持的，确认下配置开启了？我刚试了是好的

Taro CLI 3.4.12 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.12 => 3.4.12 
      @tarojs/components: 3.4.12 => 3.4.12 
      @tarojs/mini-runner: 3.4.12 => 3.4.12 
      @tarojs/react: 3.4.12 => 3.4.12 
      @tarojs/rn-runner: 3.4.12 => 3.4.12 
      @tarojs/runtime: 3.4.12 => 3.4.12 
      @tarojs/taro: 3.4.12 => 3.4.12 
      @tarojs/taro-rn: 3.4.12 => 3.4.12 
      @tarojs/webpack-runner: 3.4.12 => 3.4.12 
      babel-preset-taro: 3.4.12 => 3.4.12 
      eslint-config-taro: 3.4.12 => 3.4.12 
      react: ^17.0.0 => 17.0.2 
      react-native: ~0.68.1 => 0.68.2 
    npmGlobalPackages:
      typescript: 4.5.5

**Comment by WhiteSean** [comment]
> 不是最近支持的，确认下配置开启了？我刚试了是好的
> 
> Taro CLI 3.4.12 environment info: System: OS: macOS 12.4 Shell: 5.8.1 - /bin/zsh Binaries: Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm npmPackages: @tarojs/cli: 3.4.12 => 3.4.12 @tarojs/components: 3.4.12 => 3.4.12 @tarojs/mini-runner: 3.4.12 => 3.4.12 @tarojs/react: 3.4.12 => 3.4.12 @tarojs/rn-runner: 3.4.12 => 3.4.12 @tarojs/runtime: 3.4.12 => 3.4.12 @tarojs/taro: 3.4.12 => 3.4.12 @tarojs/taro-rn: 3.4.12 => 3.4.12 @tarojs/webpack-runner: 3.4.12 => 3.4.12 babel-preset-taro: 3.4.12 => 3.4.12 eslint-config-taro: 3.4.12 => 3.4.12 react: ^17.0.0 => 17.0.2 react-native: ~0.68.1 => 0.68.2 npmGlobalPackages: typescript: 4.5.5

好的 我确认当时配置是开启的，我待会再试试
