### ISSUE TITLE
boolean类型组件属性，只写属性名在微信小程序不会编译为true，但在h5会编译为true

### ISSUE THREAD

**Issue by daofeng-coder** [NervJS/taro#11914]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/daofeng_wx/taro-benxi-dealer/tree/test/](https://gitee.com/daofeng_wx/taro-benxi-dealer/tree/test/)
**小程序基础库: 2.24.3**
**使用框架: Vue 3**

### 复现步骤
进入pages/work/main/index这个页面查看两个swiper，boolean类型的属性
源码开源有问题，导致无法访问，我口述一下，boolean属性一定要写成`:propertyName="true"`的方式才能在小程序编译为true；

### 期望结果
boolean类型的属性直接写上属性名可以在微信小程序编译为true

### 实际结果
boolean类型的属性直接写上属性名在微信小程序未编译为true，但在h5编译为了true

### 环境信息
```
👽 Taro v3.4.11


  Taro CLI 3.4.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\Daofeng\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - D:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
这里只测试了swiper，可能是编译特性，直接写属性名在微信小程序不会编译为true

**Comment by Chen-jj** [comment]
和 Vue 对布尔值的处理有关，在小程序的确需要这样写，Taro 文档也有注明：https://docs.taro.zone/docs/vue-overall#taro-%E8%A7%84%E8%8C%83

后面加一层 Vue3 renderer 手动控制对接的 DOM 方法应该才可以解决
