### ISSUE TITLE
3.4.11 Swiper 组件随着 tab 页面切换，总是跳到最后一个元素开始轮播

### ISSUE THREAD

**Issue by shushu2013** [NervJS/taro#11920]
### 相关平台
H5

### 复现仓库
[https://github.com/shushu2013/taro-bugs](https://github.com/shushu2013/taro-bugs)
**浏览器版本: Chrome 版本 102.0.5005.61（正式版本） (arm64)**
**使用框架: React**

### 复现步骤
```
$ git clone https://github.com/shushu2013/taro-bugs.git

$ cd taro-bugs

$ yarn

$ yarn dev:h5
```
首次切换，Swiper 组件是从第一个元素开始展示，后续切换都会直接跳到最后一个元素

![Jun-10-2022 18-24-13](https://user-images.githubusercontent.com/6076072/173046862-852d2f6f-2515-4bc2-85f2-5dc5a0a3a52a.gif)

### 期望结果
Swiper 表现正常

### 实际结果
Swiper 表现异常

### 环境信息
```
👽 Taro v3.4.11


  Taro CLI 3.4.11 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.3.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    npmPackages:
      @tarojs/components: 3.4.11 => 3.4.11 
      @tarojs/mini-runner: 3.4.11 => 3.4.11 
      @tarojs/plugin-framework-react: 3.4.11 => 3.4.11 
      @tarojs/react: 3.4.11 => 3.4.11 
      @tarojs/runtime: 3.4.11 => 3.4.11 
      @tarojs/taro: 3.4.11 => 3.4.11 
      @tarojs/webpack-runner: 3.4.11 => 3.4.11 
      babel-preset-taro: 3.4.11 => 3.4.11 
      eslint-config-taro: 3.4.11 => 3.4.11 
      react: ^17.0.0 => 17.0.2 

```

**Comment by moyafaxi** [comment]
https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/swiper/swiper.tsx#L298
1. 这里 that.current 测试下来一直是默认值 0,没有更新，直接使用 realIndex 是不是更好
2. slideTo 在 loop 模式下有点问题，在 loop 模式下，应该使用 slideToLoop。

https://github.com/NervJS/taro/pull/11927
@Chen-jj
