### ISSUE TITLE
工程编译时,会将regeneratorRuntime编译到具体页面中去,导致编译后的每个页面文件都会有这段代码,导致整体主包超2M

### ISSUE THREAD

**Issue by jytx** [NervJS/taro#11929]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/jytx/testproj.git](https://github.com/jytx/testproj.git)
**小程序基础库: 2.23.4**
**使用框架: Vue 2**

### 复现步骤
1.执行npm install 进行安装依赖
2.执行npm run build:weapp
3.查看dist/pages/index/index.js 文件

### 期望结果
dist/pages/index/index.js文件内不包括regeneratorRuntime相关代码，regeneratorRuntime代码应该编译在dist/taro.js文件

### 实际结果
regeneratorRuntime相关代码被编译到了dist/pages/index/index.js中,dist/taro.js中没有相关代码

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.0/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.21 => 3.0.21
      @tarojs/mini-runner: 3.0.21 => 3.0.21
      @tarojs/runtime: 3.0.21 => 3.0.21
      @tarojs/taro: 3.0.21 => 3.0.21
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
```

---
### 补充信息
原项目中存在package-lock.json的工程,可以正常安装,并且regeneratorRuntime的代码会被编译到dist/taro.js中,但是没有package-lock.json的同事在编译后会发现regeneratorRuntime的代码被编译到了实际页面中

**Comment by zicong-zhang** [comment]
+1我的是 react16.8 + taro

**Comment by Chen-jj** [comment]
@jytx 提供的 Demo 只有一个页面，所以没有命中 splitchunk 的规则打到 vendor.js 里，当有两个或以上页面使用了 async await，`regeneratorRuntime` 就会被打到 vendor.js 里了。

Demo 还没有证明每个页面都会存在 `regeneratorRuntime` 依赖。
