### ISSUE TITLE
配置项设置collapseWhitespace:true后，使用input标签报错

### ISSUE THREAD

**Issue by bujidao** [NervJS/taro#11928]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/bujidao/taro-vue3_bugs-report_config-collapseWhitespace-input.git](https://github.com/bujidao/taro-vue3_bugs-report_config-collapseWhitespace-input.git)
**小程序基础库: 2.24.5**
**使用框架: Vue 3**

### 复现步骤
1. 更改`config/index.js`配置项，`config>mini>minifyXML>collapseWhitespace`：`true`
2. `src/pages/index/idnex.vue`, 新增一个input标签
3. 重新运行项目，并返回微信开发工具
4. 具体描述，见重现连接的readme.md

### 期望结果
添加input标签以后，正常运行

### 实际结果
input标签不正常运行

### 环境信息
```
 Taro CLI 3.4.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.10 - C:\Program Files\nodejs\v12.22.10\node.EXE
      Yarn: 1.22.10 - C:\Users\Tom\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\v12.22.10\npm.CMD
```

**Comment by moyafaxi** [comment]
html-minifier 库的问题，可以参考这个通过 patch-package 修复 https://github.com/kangax/html-minifier/issues/1065

@bujidao

**Comment by TomatoesMan** [comment]
没有明白该如何 patch，是将 input 从 var selfClosingInlineTags = createMapFromString('comment,img,input,wbr'); 和 var empty = makeMap('area,base,basefont,br,col,embed,frame,hr,img,input,isindex,keygen,link,meta,param,source,track,wbr');  中删除吗？

**Comment by moyafaxi** [comment]
> 没有明白该如何 patch，是将 input 从 var selfClosingInlineTags = createMapFromString('comment,img,input,wbr'); 和 var empty = makeMap('area,base,basefont,br,col,embed,frame,hr,img,input,isindex,keygen,link,meta,param,source,track,wbr'); 中删除吗？

是的

**Comment by lupingW** [comment]
怎么解决的 没他看懂
