### ISSUE TITLE
Taro.login调用后，未等到点选接受或拒绝，success参数方法就被执行了，返回的res.code也都存在。

### ISSUE THREAD

**Issue by lucasphbs** [NervJS/taro#1193]
Taro.login调用后，未等到点选接受或拒绝，success参数方法就被执行了，返回的res.code也都存在。

版本:微信小程序 1.1.4

**Comment by lucasphbs** [comment]
补充截图
<img width="983" alt="image" src="https://user-images.githubusercontent.com/19701561/48813064-26ed3500-ed70-11e8-800e-94a35a6d4e44.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/19701561/48813071-366c7e00-ed70-11e8-8861-7d00ac9f4484.png">

**Comment by Inori-Lover** [comment]
这个弹窗跟login没关系吧

**Comment by Chen-jj** [comment]
微信小程序中调用 Taro.login 相当于调用 wx.login。你可以换成 wx.login 看看行为是不是一样
