### ISSUE TITLE
引用app.config.ts 中的数据 ，报错 defineAppConfig is not defined

### ISSUE THREAD

**Issue by cyzeng-Luca** [NervJS/taro#11949]
### 相关平台
微信小程序

**小程序基础库: 2.24.6**
**使用框架: React**

### 复现步骤
import AppConfig from '@src/app.config';

 ReferenceError: defineAppConfig is not defined

### 期望结果
期望能够正常引用app.config'中的数据

### 实际结果
 ReferenceError: defineAppConfig is not defined

### 环境信息
```
Taro v3.4.10


  Taro CLI 3.4.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.4.10 => 3.4.10 
      @tarojs/mini-runner: 3.4.10 => 3.4.10 
      @tarojs/plugin-framework-react: 3.4.10 => 3.4.10 
      @tarojs/runtime: 3.4.10 => 3.4.10 
      @tarojs/taro: 3.4.10 => 3.4.10 
      @tarojs/webpack-runner: 3.4.10 => 3.4.10 
      babel-preset-taro: 3.4.10 => 3.4.10 
      eslint-config-taro: 3.4.10 => 3.4.10 
```

**Comment by moyafaxi** [comment]
提供下能复现问题的最小 demo

**Comment by AdvancedCat** [comment]
defineAppConfig & definePageConfig 是宏函数，它主要用于「类型提示」和「自动补全」。

**Comment by cyzeng-Luca** [comment]
> defineAppConfig & definePageConfig 是宏函数，它主要用于「类型提示」和「自动补全」。 在编译时会提取config部分生成单独的 配置 文件，它并不是运行时可用的函数。 https://docs.taro.zone/docs/app-config#defineappconfig-%E5%AE%8F%E5%87%BD%E6%95%B0

我有办法在其他JS文件中，export 其中的数据吗？我想导出其中tabBar字段的数据

**Comment by sikaco** [comment]
我遇到了，解决方法是：
保证 defineAppConfig 的 pages 选项中，链接末尾是有 index 的

```
export default defineAppConfig({
  pages: ['components/views/init-page'], // 报错
})
```

```
export default defineAppConfig({
  pages: ['components/views/init-page/index'], // 不报错
})
```

**Comment by cyzeng-Luca** [comment]
app.config文件
export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/me/index',
  ],
  tabBar: {
    color: '#999999',
    selectedColor: '#4FA7FF',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: './assets/images/icon_sy@2x.png',
        selectedIconPath: './assets/images/icon_sy_xz@2x.png',
      },
      {
        pagePath: 'pages/me/index',
        text: '我的',
        iconPath: './assets/images/icon_wd@2x.png',
        selectedIconPath: './assets/images/icon_wd_xz@2x.png',
      },
    ],
  },
});

index.js
import xx from './app.config';

依然报错  ReferenceError: defineAppConfig is not defined
@sikaco

**Comment by xyt0110** [comment]
刚遇到了此问题，搜了下竟然没有解决方案！！！
根据文档描述`defineAppConfig`的作用是为了类型推断，如果仅仅是这个作用的话，拿掉`defineAppConfig`应该是没有影响的
app.config.ts
```ts
import Taro from '@tarojs/taro';

export class AppRoutes {
  static home = '/pages/index/index';
  static about = '/pages/about/about';
}

const pages = [
  AppRoutes.home,
  AppRoutes.about,
];

export default {
  pages: pages.map((row) => row.slice(1)),
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
} as Taro.Config;
```
试了下，其他文件能正常`import { AppRoutes } from 'app.config'`了。如果项目是js写的，为了能使用类型推断，可以改成这样：
```js
export class AppRoutes {
  static home = '/pages/index/index';
  static about = '/pages/about/about';
}

const pages = [
  AppRoutes.home,
  AppRoutes.about,
];

//@ts-check
/** @typedef {import('@tarojs/taro').Config} TaroConfig **/

/** @type TaroConfig */
export default {
  pages: pages.map((row) => row.slice(1)),
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
};
```
比较遗憾的是`app.config.ts`还是不能import其他文件

**Comment by Chen-jj** [comment]
@cyzeng-Luca @xyt0110 可以通过 `window.__taroAppConfig` 获取 app.json 里的配置，不需要额外 import。

另外 `app.config.ts` 是支持 `import` 其他文件的。

**Comment by shengzhou1216** [comment]
same issue.

**Comment by tourze** [comment]
如果目标是读取配置中的一些参数如tabbar配置，可以考虑使用 `Taro.getApp().config.tabBar`来读取。

**Comment by hiitiger** [comment]
same issue
```ts
export default defineAppConfig({
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
})
```

**Comment by hiitiger** [comment]
So，这个问题这么多人在问，也没有真正解决就关闭了？

**Comment by Hisioni** [comment]
脚手架生成的项目，就有这问题呀

**Comment by berial** [comment]
cli直接创建的模板：
? 请输入项目介绍
? 请选择框架 Vue3
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Gitee（最快）
✔ 拉取远程模板仓库成功！
? 请选择模板 vue3-NutUI4（使用 NutUI4.0 的模板）

```
export default defineAppConfig({
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
})

```

```
Compiled with problems:X

ERROR in ./src/app.config.ts

defineAppConfig is not defined


ERROR in ./src/app.config.ts

Cannot read properties of undefined (reading 'length')
```
