### ISSUE TITLE
H5 picker mode = date不能设置日期格式的 end / start

### ISSUE THREAD

**Issue by wenxiuYang** [NervJS/taro#11943]
## 相关平台
H5

###  复现仓库
[picker-demo](https://github.com/wenxiuYang/taro-demo/tree/picker-demo)

### 环境
```
Taro CLI 3.4.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - 
      Yarn: 1.22.18 - 
      npm: 6.14.14 - 
```

### 这个特性解决了什么问题？
H5 端： mode=date的picker 的end/start 属性的取值应为 ‘YYYY-MM-DD’， 而不应该是‘hh:mm’，
end / start 属性的功能为设置 picker mode=date 的取值范围，其取值类型应为 date: 'YYYY-MM-DD', 

现在 h5 中 picker mode=date 的end/start 属性只接受 ‘hh:mm’的值，导致不能为组件设置取值范围

### 这个 API 长什么样？
H5 端：
end / start 的取值类型为‘YYYY-MM-DD'

**Comment by konka-king** [comment]
![image](https://user-images.githubusercontent.com/22173084/173970215-defba92a-69cd-4e17-a340-9b46df6b078b.png)
这个 微信小程序本人亲测是可以的

**Comment by wenxiuYang** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/173970215-defba92a-69cd-4e17-a340-9b46df6b078b.png) 这个 微信小程序本人亲测是可以的

谢谢， 小程序是可以的，但是 H5 不可以

**Comment by moyafaxi** [comment]
升级到最新版本试试， 3.4.12 没有复现你这个问题

**Comment by wenxiuYang** [comment]
> 升级到最新版本试试， 3.4.12 没有复现你这个问题

@moyafaxi  我的issue 有说明是在H5 哦， 你是在 H5端测试的吗，
升级到 3.4.12 仍然不能设置 日期格式的end/start
![image](https://user-images.githubusercontent.com/74034388/174213624-7f4439ff-06ad-42a3-8180-51ff529a4405.png)

**Comment by moyafaxi** [comment]
> > 升级到最新版本试试， 3.4.12 没有复现你这个问题
> 
> @moyafaxi 我的issue 有说明是在H5 哦， 你是在 H5端测试的吗， 升级到 3.4.12 仍然不能设置 日期格式的end/start ![image](https://user-images.githubusercontent.com/74034388/174213624-7f4439ff-06ad-42a3-8180-51ff529a4405.png)

麻烦提供下复现问题的 demo 和你本地环境信息

**Comment by wenxiuYang** [comment]
> > > 升级到最新版本试试， 3.4.12 没有复现你这个问题
> > 
> > 
> > @moyafaxi 我的issue 有说明是在H5 哦， 你是在 H5端测试的吗， 升级到 3.4.12 仍然不能设置 日期格式的end/start ![image](https://user-images.githubusercontent.com/74034388/174213624-7f4439ff-06ad-42a3-8180-51ff529a4405.png)
> 
> 麻烦提供下复现问题的 demo

@moyafaxi
仓库：
[picker-demo](https://github.com/wenxiuYang/taro-demo/tree/picker-demo)

环境
```
Taro CLI 3.4.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - 
      Yarn: 1.22.18 - 
      npm: 6.14.14 - 
```

**Comment by moyafaxi** [comment]
> > > > 升级到最新版本试试， 3.4.12 没有复现你这个问题
> > > 
> > > 
> > > @moyafaxi 我的issue 有说明是在H5 哦， 你是在 H5端测试的吗， 升级到 3.4.12 仍然不能设置 日期格式的end/start ![image](https://user-images.githubusercontent.com/74034388/174213624-7f4439ff-06ad-42a3-8180-51ff529a4405.png)
> > 
> > 
> > 麻烦提供下复现问题的 demo
> 
> @moyafaxi 仓库： [picker-demo](https://github.com/wenxiuYang/taro-demo/tree/picker-demo)
> 
> 环境
> 
> ```
> Taro CLI 3.4.12 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Node: 14.17.4 - 
>       Yarn: 1.22.18 - 
>       npm: 6.14.14 - 
> ```

你的 value 当前时间设置的不合法所以报错了，要设置为 start 和 end 之间的日期

@wenxiuYang

**Comment by wenxiuYang** [comment]
> 

@moyafaxi  好嘞，谢谢，

**Comment by wenxiuYang** [comment]
> > > > > 升级到最新版本试试， 3.4.12 没有复现你这个问题
> > > > 
> > > > 
> > > > @moyafaxi 我的issue 有说明是在H5 哦， 你是在 H5端测试的吗， 升级到 3.4.12 仍然不能设置 日期格式的end/start ![image](https://user-images.githubusercontent.com/74034388/174213624-7f4439ff-06ad-42a3-8180-51ff529a4405.png)
> > > 
> > > 
> > > 麻烦提供下复现问题的 demo
> > 
> > 
> > @moyafaxi 仓库： [picker-demo](https://github.com/wenxiuYang/taro-demo/tree/picker-demo)
> > 环境
> > ```
> > Taro CLI 3.4.12 environment info:
> >     System:
> >       OS: Windows 10
> >     Binaries:
> >       Node: 14.17.4 - 
> >       Yarn: 1.22.18 - 
> >       npm: 6.14.14 - 
> > ```
> 
> 你的 value 设置的不合法所以报错了，要设置为 start 和 end 之间的日期
> 
> @wenxiuYang

@moyafaxi  好嘞，谢谢
