### ISSUE TITLE
switchTab切换到tabbar 页面时无限创建DOM节点,而不是display切换

### ISSUE THREAD

**Issue by wenxiuYang** [NervJS/taro#11942]
### 相关平台
H5

### 复现仓库
[switchTab-demo](https://github.com/wenxiuYang/taro-demo/tree/switchTab-demo)
**浏览器版本: Chrome 版本 102.0.5005.115（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
当 Tabbar page  dom节点已创建，在二级页面 使用switchTab 跳转至Tabbar page ，Tabbar page 的dom 节点被重复创建

### 期望结果
当Tabbar page dom节点已创建， 使用switchTab跳转至该tabbar page 时，dom 节点 应 display 切换

### 实际结果
Tabbar page dom节点被重复创建

### 环境信息
```
 Taro CLI 3.4.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - 
      Yarn: 1.22.18 - 
      npm: 6.14.14 - 
```

**Comment by ZakaryCode** [comment]
该 dom 中并不包含 tabbar，这样的用法在后续中会被禁用

**Comment by ZakaryCode** [comment]
跳转非 tabbar 页面会自动创建新的页面节点，符合正常状态
