### ISSUE TITLE
Error: Exception in HostObject::get(propName:NativeUnimoduleProxy):No static method withInitial

### ISSUE THREAD

**Issue by Felix8029** [NervJS/taro#11950]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
按照分离模式的的接入方式接入，在Android 8.0 以下设备上无法正常运行页面。

### 期望结果
正常加载Taro页面

### 实际结果
打开页面红屏报错

### 环境信息
```
Taro CLI 3.4.10 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/components: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/mini-runner: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/plugin-framework-react: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/react: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/rn-runner: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/runtime: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/taro: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/taro-rn: 3.5.0-beta.0 => 3.5.0-beta.0 
      @tarojs/webpack-runner: 3.5.0-beta.0 => 3.5.0-beta.0 
      babel-preset-taro: 3.5.0-beta.0 => 3.5.0-beta.0 
      eslint-config-taro: 3.5.0-beta.0 => 3.5.0-beta.0 
      expo: ~45.0.2 => 45.0.5 
      react: ^17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 

```

---
### 补充信息
Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.NoSuchMethodError: No static method withInitial(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in class Ljava/lang/ThreadLocal; or its super classes (declaration of 'java.lang.ThreadLocal' appears in /system/framework/core-oj.jar)

仅在Android 8.0 以下设备上复现；对应的问题API 在Android官方要求是API 26：链接：https://developer.android.com/reference/java/lang/ThreadLocal#withInitial(java.util.function.Supplier%3C?%20extends%20S%3E)

本地使用的JDK 为11，且项目内均配置使用java11

compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.majorVersion
    }

AGP 版本 7.1.3, Gradle版本：7.3.3

**Comment by zhiqingchen** [comment]
https://github.com/javalin/javalin/issues/185

**Comment by zhiqingchen** [comment]
是否改过 minSdkVersion

```
minSdkVersion 26
```

**Comment by Felix8029** [comment]
> 

没有，这边配置的是minSdkVersion 21

**Comment by Felix8029** [comment]
Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.NoClassDefFoundError: org.apache.commons.io.IOUtils

并非所有页面都加载不出来，只有部分。一开始页面记载错误，莫名其妙就好了。但打开其他页面就不行了，同时还会出现以上错误信息。应该都是NativeUnimoduleProxy的问题吧
@zhiqingchen

**Comment by Felix8029** [comment]
最终问题定位：
Taro接入原生已有项目中，逐个排查依赖库，发现 commons-io:commons-io:2.9.0 引起上述问题，升级2.11.0也不行，最后修改为expo项目内的2.6版本，即恢复正常。不太清楚内部是做了些什么，暂时没有时间去深究，你们内部可看看，否则后续升级就会成为问题
@zhiqingchen

**Comment by zhiqingchen** [comment]
> 最终问题定位： Taro接入原生已有项目中，逐个排查依赖库，发现 commons-io:commons-io:2.9.0 引起上述问题，升级2.11.0也不行，最后修改为expo项目内的2.6版本，即恢复正常。不太清楚内部是做了些什么，暂时没有时间去深究，你们内部可看看，否则后续升级就会成为问题 @zhiqingchen

感谢反馈。

自行集成方式较为复杂，且不可控。建议依赖版本以 https://github.com/wuba/taro-playground 为准。

**Comment by Felix8029** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Felix8029** [comment]
> 

这个倒也不是未按照playground中依赖版本进行操作，主要是对接入已有原生项目的场景，外在因素太多，且出现问题较难定位。并且上述问题很容易出现的，原生项目随便接入其他第三方库只要使用的common-io就会出问题，且不是那种编译报错，而是运行时系统版本兼容，很难发现。

**Comment by zhiqingchen** [comment]
> > 
> 
> 
> 
> 这个倒也不是未按照playground中依赖版本进行操作，主要是对接入已有原生项目的场景，外在因素太多，且出现问题较难定位。并且上述问题很容易出现的，原生项目随便接入其他第三方库只要使用的common-io就会出问题，且不是那种编译报错，而是运行时系统版本兼容，很难发现。

是的，确实难以发现。
