### ISSUE TITLE
Taro-RN 3.5.0-beta.2 集成模式 调试闪退

### ISSUE THREAD

**Issue by ZhuQinPeng** [NervJS/taro#11953]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
就正常的编译，手机app（Taro glayground app）扫码，闪退

### 期望结果
正常运行

### 实际结果
Taro-RN 3.5.0-beta.2 集成模式调试 闪退

### 环境信息
```
👽 Taro v3.5.0-beta.2


  Taro CLI 3.5.0-beta.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
新版本 Taro glayground app 还未发布，可在自身工程中打包。

或使用 beta 版本

https://github.com/wuba/taro-playground/releases/tag/v1.6.0-beta.8

**Comment by zhiqingchen** [comment]
另外控制台看看有没有报错

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-test/tree/tests/3.5.0-beat.2

**Comment by zhiqingchen** [comment]
看看这个行不行

**Comment by ZhuQinPeng** [comment]
> 看看这个行不行

你好，我刚尝试过了，使用Taro playground App正常，但是使用安卓模拟器还是报上面那个classpath的问题，是什么原因呢，谢谢

**Comment by ZhuQinPeng** [comment]
> 看看这个行不行

我尝试过几次，把android studio相关的一切都卸载删除了重装，但还是没解决，希望大神能给解惑，谢谢

**Comment by zhiqingchen** [comment]
1. 是否按照文档操作 `yarn` `yarn upgradePeerdeps` `yarn start` `yarn android`
2. 检查是否安装 react-native-gradle-plugin `yarn why react-native-gradle-plugin`
3. 使用 A S 进行编译试试

**Comment by ZhuQinPeng** [comment]
> 1. 是否按照文档操作 `yarn` `yarn upgradePeerdeps` `yarn start` `yarn android`
> 
>     2. 检查是否安装 react-native-gradle-plugin `yarn why react-native-gradle-plugin`
> 
>     3. 使用 A S 进行编译试试

你好，我确定我是按照文档操作的，但是为了以防万一，我刚又按你说的操作了一遍，Taro Playgound App正常，AS报错，截图如下：
![图片](https://user-images.githubusercontent.com/18671583/175753846-97224ce4-83d7-4d6d-bd5f-de68627b2c6b.png)

执行`yarn why react-native-gradle-plugin`的结果如下：
![图片](https://user-images.githubusercontent.com/18671583/175753895-4c8379eb-dffd-45fd-8578-9b95b88ee6ea.png)

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-test

**Comment by ZhuQinPeng** [comment]
> 用我init的试试 https://github.com/zhiqingchen/taro-test
> 
> 3.5分支

这是我刚刚试的
![图片](https://user-images.githubusercontent.com/18671583/175754468-ab134e93-d033-41d8-8085-5e698d74253f.png)

报错是一样的
![图片](https://user-images.githubusercontent.com/18671583/175754483-2f20b12e-1597-4116-93d1-add6375eedbf.png)

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-test/actions/runs/2559311232

https://github.com/zhiqingchen/taro-test/actions/runs/2559311231

**Comment by zhiqingchen** [comment]
> https://github.com/zhiqingchen/taro-test/actions/runs/2559311232
> 
> https://github.com/zhiqingchen/taro-test/actions/runs/2559311231

正常编译，建议本地环境搞不定，可以用远程的

**Comment by ZhuQinPeng** [comment]
> > https://github.com/zhiqingchen/taro-test/actions/runs/2559311232
> > https://github.com/zhiqingchen/taro-test/actions/runs/2559311231
> 
> 正常编译，建议本地环境搞不定，可以用远程的

？？？远程的？有文档或使用方法吗？

**Comment by zhiqingchen** [comment]
https://docs.taro.zone/docs/react-native#打包发布安卓包

**Comment by zhiqingchen** [comment]
init 后根目录下的.github有相关github action打包脚本

**Comment by ZhuQinPeng** [comment]
> init 后根目录下的.github有相关github action打包脚本

好的，谢谢
