### ISSUE TITLE
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.

### ISSUE THREAD

**Issue by juhntao** [NervJS/taro#11956]
### 相关平台
H5

### 复现仓库
[https://github.com](https://github.com)
**浏览器版本: Chrome Version 102.0.5005.115 (Official Build) (64-bit)**
**使用框架: React**

### 复现步骤
C:\Users\tao\Desktop\reactTest>npx @tarojs/cli init myTestApp

👽 Taro v3.4.12

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！ TestApp
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板源 Gitee（最快）
√ 拉取远程模板仓库成功！
? 请选择模板 默认模板

C:\Users\tao\Desktop\reactTest>cd myTestApp

C:\Users\tao\Desktop\reactTest\myTestApp>yarn dev:h5
yarn run v1.22.18
warning ..\..\..\package.json: No license field
$ npm run build:h5 -- --watch

> myTestApp@1.0.0 build:h5
> taro build --type h5 "--watch"

👽 Taro v3.3.16

- Compiling...i ｢wds｣: Project is running at http://192.168.0.101:10088/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\tao\Desktop\reactTest\myTestApp\dist
i ｢wds｣: 404s will fallback to /index.html
http://192.168.0.101:10088/

ℹ️  Listening at http://0.0.0.0:10088/

监听文件修改中...

🙅   Failed to compile.

./src/app.config.ts
Module build failed (from @tarojs/taro-loader/lib/h5):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.

### 期望结果
正常运行

### 实际结果
报错， 无法运行

### 环境信息
```
$ taro info
👽 Taro v3.3.16

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - C:\Users\tao\AppData\Local\Temp\yarn--1655728666048-0.14837700908455242\node.CMD
      Yarn: 1.22.18 - C:\Users\tao\AppData\Local\Temp\yarn--1655728666048-0.14837700908455242\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD

Done in 3.67s.
```

**Comment by moyafaxi** [comment]
taro 版本升到最新的试试，v3.4.12 未复现问题

**Comment by juhntao** [comment]
taro 升级到 v3.4.12 可以正常运行了

**Comment by llgoer** [comment]
升级最新还是有错误啊

./src/app.config.ts
Module build failed (from @tarojs/taro-loader/lib/h5):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.

**Comment by aYangLi** [comment]
将 @tarojs/cli 升级到最新版本即可，刚解决完这个问题；
yarn global add @tarojs/cli

**Comment by EzioAuditoly** [comment]
同样的问题，将 @tarojs/cli 升级后没有解决

**Comment by niyingg** [comment]
同样的问题，
<img width="461" alt="image" src="https://github.com/NervJS/taro/assets/13973458/bd9aedd7-298e-47fa-805f-12c1349f6fbc">
装好后 直接运行
<img width="606" alt="image" src="https://github.com/NervJS/taro/assets/13973458/2699ceb1-166b-47dd-a45c-2b76ef68794f">

**Comment by niyingg** [comment]
yarn global add @tarojs/cli 升级可以解决

**Comment by qgq99** [comment]
> 同样的问题，将 @tarojs/cli 升级后没有解决

后来解决了吗佬
