### ISSUE TITLE
tabbar多次切换会出现白屏

### ISSUE THREAD

**Issue by jianghaolun** [NervJS/taro#11969]
### 相关平台
H5

### 复现仓库
[https://gitlab.eazytec-cloud.com/digital-building/app/ibms_h5](https://gitlab.eazytec-cloud.com/digital-building/app/ibms_h5)
**浏览器版本: Chrome**
**使用框架: React**

### 复现步骤
tabbar多次点击

### 期望结果
tabbar多次点击不会白屏

### 实际结果
tabbar多次点击会白屏,4个dom都是display：none

### 环境信息
```
 Taro CLI 3.3.19 environment info:
    System:
      OS: macOS 12.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 8.1.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.19 => 3.3.19 
      @tarojs/mini-runner: 3.3.19 => 3.3.19 
      @tarojs/react: 3.3.19 => 3.3.19 
      @tarojs/runtime: 3.3.19 => 3.3.19 
      @tarojs/taro: 3.3.19 => 3.3.19 
      @tarojs/webpack-runner: 3.3.19 => 3.3.19 
      babel-preset-taro: 3.3.19 => 3.3.19 
      eslint-config-taro: 3.3.19 => 3.3.19 
      react: ^16.10.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by ZakaryCode** [comment]
升级版本修复该问题

**Comment by jianghaolun** [comment]
升级到3.5.0，Taro 配置有误,请检查 [✗] plugins 应该为[数组]怎么解决呢？

**Comment by ZakaryCode** [comment]
> 升级到3.5.0，Taro 配置有误,请检查 [✗] plugins 应该为[数组]怎么解决呢？

升级参考[文档](https://nervjs.github.io/taro-docs/blog/2022/05/19/Taro-3.5-beta#%E5%85%AD%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97)
