### ISSUE TITLE
expo预览跟打包evaluating '_reactNative.View.proptypes.style'错误

### ISSUE THREAD

**Issue by 824759494** [NervJS/taro#1197]
**系统信息**
expo v2.4.0
node v10.2.0
yarn v1.12.1
taro 1.1.5 - 1.1.8

**问题描述**
修改.rn_temp下的app.json配置信息报underfined is not an object(evaluating 'View.propTypes.style') 

**复现步骤**
npm run build:rn之后
修改.rn_temp下的app.json配置信息
expo r --no-dev --no-minify 命令下报underfined is not an object(evaluating 'View.propTypes.style') 
```json
{
  "expo": {
    "name": "Yome",
    "icon": "./assets/img/home.png",
    "version": "1.0.0",
    "sdkVersion": "27.0.0",
    "splash": {
      "image": "./assets/img/home.png"
    },
    "ios": {
      "bundleIdentifier": "taro.expo"
    },
    "android": {
      "package": "taro.expo"
    },
    "assetBundlePatterns": [
      "assets/**"
    ]
  }
}
```

**补充信息**
```
更改taro-rn里面的View.propTypes.style => PropTypes.style
```

**期望行为**
修改app.json后不再需要修改taro-rn里面的内容就可以跑下面的两个命令
```
expo r --no-dev --no-minify
expo start
```

**报错信息**

**Comment by Pines-Cheng** [comment]
e0116102

**Comment by 824759494** [comment]
？？？，什么鬼？
此问题并未解决，直接使用模板源码

**Comment by Pines-Cheng** [comment]
@824759494 最新的版本未解决？注意更新依赖哦。

**Comment by 824759494** [comment]
> @ 824759494最新的版本未解决？注意更新依赖哦。

使用的是v1.2.0-beta.3版本 直接taro init的新建模板
在这个基础上查看的，不是在原有项目上查看的
