### ISSUE TITLE
使用encodeURIComponent后的路由params参数，在新页面打开表现异常。（3.4.12）

### ISSUE THREAD

**Issue by linshimao** [NervJS/taro#11974]
### 相关平台
H5

### 复现仓库
[https://github.com/linshimao/bug/blob/main/b.vue](https://github.com/linshimao/bug/blob/main/b.vue)
**浏览器版本: chrome 103.0.5060.53**
**使用框架: Vue 3**

### 复现步骤
  const e = encodeURIComponent(`lessonId=${123}`)
  // const e = `lessonId=${123}`
  Taro.navigateTo({
    url: `/pages/record-detail/record-detail?${e}`
  })
  新页面打印
  const { router } = getCurrentInstance()
  console.log(router)

### 期望结果
正确输出params参数

### 实际结果
params直接把参数的键值合并了，然后实际的值变成null了

### 环境信息
```
  Taro CLI 3.4.11 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v10.15.2/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.12 => 3.4.12 
      @tarojs/components: 3.4.12 => 3.4.12 
      @tarojs/mini-runner: 3.4.12 => 3.4.12 
      @tarojs/plugin-html: 3.4.12 => 3.4.12 
      @tarojs/runtime: 3.4.12 => 3.4.12 
      @tarojs/taro: 3.4.12 => 3.4.12 
      @tarojs/webpack-runner: 3.4.12 => 3.4.12 
      babel-preset-taro: 3.4.12 => 3.4.12 
      eslint-config-taro: 3.4.12 => 3.4.12 
```

**Comment by Barrierml** [comment]
在get请求当中一般是不会去转译 `=` 符号的，除非你的`query` 参数中带有`=`符号，不单单是 `taro` 的前端路由，其他前端路由，包括后端请求都会把转译后的参数视为一个key，而不是 `k=v` 的形式，如果要转译某个值的话推荐这样写
```js
const value = "你好，我是一个要被转移的参数";
const e = `lessonId=${encodeURIComponent(value)}`;
Taro.navigateTo({
  url: "/pages/record-detail/record-detail?${e}",
});
```
