### ISSUE TITLE
在rush pnpm的monorepo项目中，taro 使用 build:h5失败

### ISSUE THREAD

**Issue by zhanght9527** [NervJS/taro#11971]
### 相关平台
H5

### 复现仓库
[https://github.com/zhanght9527/rush_taro_demo](https://github.com/zhanght9527/rush_taro_demo)
**浏览器版本: 无**
**使用框架: React**

### 复现步骤
在 rush   pnpm 管理的monorepo项目中，使用rush update安装依赖，进入小程序目录，执行rushx build:h5，报错如下：

🙅   Failed to compile.

./src/app.config.ts
Module not found: Can't resolve '@tarojs/taro' in '/Users/zhanght/Desktop/rush_taro_demo/taro_demo/src'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

而在 lerna   workspack 管理的 monorepo 项目中是ok的

### 期望结果
build:h5 编译成功

### 实际结果
编译失败

### 环境信息
```
Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.6.3
```

**Comment by Chen-jj** [comment]
@zhanght9527 和 `rush` 没有关系，是 pnpm 的问题。

`@taorjs/taro` 在 H5 是 alias 为 `@tarojs/taro-h5` 的，然而 3.4 的 package.json 没有写出要依赖它，是靠“幽灵依赖”来引用的。这幽灵依赖在 pnpm 里就被解决了，所以报找不到模块。

https://github.com/NervJS/taro/blob/1a3d5c887ae8997b632878b225b670cdc4cb42f8/packages/taro-webpack-runner/src/config/base.conf.ts#L11

所以开发者在 package.json 补个 `@tarojs/taro-h5` 的依赖就 ok 了。

ps.Taro v3.5 已经支持了 pnpm，主要是把幽灵依赖都提到用户根目录要用户自己装。至于 3.4 版本要使用 pnpm 的话还要补哪些依赖，可以看这两个 commit ：

[packages/taro-cli/templates/default/package.json.tmpl](https://github.com/NervJS/taro/commit/bdf0560ac9a44b1cac9d576980711f8830a2c96d#diff-6eeac9f03bb102ede2f62be2e05878675d7b1491a3a288b33cf67a1622731ee3)

[packages/taro-cli/templates/default/package.json.tmpl](https://github.com/NervJS/taro/commit/db866eb142f632710724828fdf2f64b57ea2a4bf#diff-6eeac9f03bb102ede2f62be2e05878675d7b1491a3a288b33cf67a1622731ee3)
