### ISSUE TITLE
如何加载三维模型

### ISSUE THREAD

**Issue by shuaigeek** [NervJS/taro#11970]
### 这个特性解决了什么问题？
开发小程序，加载三维模型，实现ar功能

### 这个 API 长什么样？
希望可以兼容threejs

**Comment by MiniOcean404** [comment]
使用 webview 吧

**Comment by githubCK** [comment]
kivicube制作的ar插件，直接引入使用就好了；自己单独开发成本太高

**Comment by ZakaryCode** [comment]
参考 https://github.com/wuba/taro-visualization/tree/main/packages/taro-3d
