### ISSUE TITLE
支持eval 和 Function 吗

### ISSUE THREAD

**Issue by wuweikd** [NervJS/taro#11976]
### 这个特性解决了什么问题？
小程序 不支持 ，在考虑从框架角度解决，主要是因为第三方库protobufjs 使用了Function  函数

https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/js-support.html

### 这个 API 长什么样？
打包的时候可以兼容吗

**Comment by moyafaxi** [comment]
这得实现一个 JS 解释器，那么理论上前端代码我可以从远端加载然后执行，小程序厂商代码审核机制就无效了。所以就算支持了，大概率也会被小程序厂商禁止

**Comment by Chen-jj** [comment]
Taro 官方没有实现的计划，可以参考业界的方案：https://github.com/bplok20010/eval5

**Comment by spiritree** [comment]
https://developers.weixin.qq.com/community/minihome/doc/0000ae500e4fd0541f2ea33755b801
