### ISSUE TITLE
taro 全局 渲染 组件 到 小程序 DOM中

### ISSUE THREAD

**Issue by MiniOcean404** [NervJS/taro#11985]
### 这个特性解决了什么问题？
小程序业务需要自定义 toast ，但是现在所有的 toast 都在 代码的 render 函数中一个个手动添加，使用 @taro/react 及 react-dom 中的render 都不能渲染 会直接报错

### 这个 API 长什么样？
小程序业务需要自定义 toast ，但是现在所有的 toast 都在 代码的 render 函数中一个个手动添加，使用 @taro/react 及 react-dom 中的render 都不能渲染 会直接报错

**Comment by Barrierml** [comment]
## 说明
hello呀，因为小程序本身多页面的设计，每一个`Page`都被封装成了一个单独DOM树，页面与页面的DOM完全相互隔离，假设我在A页面渲染了一个toast，切换到B页面就看不到它了。。这个限制不是`taro`可以突破的，而且即使有了全局渲染api，我们应该渲染到哪个页面呢？所以，不是`taro`不想给，是`taro`给不了呀😭

至于为什么`react-dom`无法在小程序内使用，因为`react-dom`是专门提供给浏览器的DOM使用的，`taro`内部自己实现的有一套`“mini-react-dom”`。

## 代替解决方案
虽然全局渲染组件的API无法实现，但是我们完全可以利用HOC自己实现一个在当前页面渲染组件的API
[关于HOC的官方介绍](https://zh-hans.reactjs.org/docs/higher-order-components.html)

> 例子使用React实现，Vue也是类似的方法

我实现了一个简单的`demo`

### 具体HOC写法在这里
[点我查看](https://github.com/Barrierml/taro-renderOnCurrentPage-demo/blob/master/src/utils/customRender.tsx)

### 使用实例在这里
[点我查看](https://github.com/Barrierml/taro-renderOnCurrentPage-demo/blob/62c30341b4c6ad942a47768acaaa686ed7fa6ca4/src/pages/index/index.tsx#L19)

## 随笔
这样的写法其实很简陋，因为每次渲染都会重新diff整个页面的DOM，如果打算生产使用建议针对每个`page`组件实现一个`shouldComponentUpdate `

还有或许可以做一个专门的taro-react-hoc的库？

**Comment by MiniOcean404** [comment]
辛苦了，辛苦了，周六还在加班回复，谢谢，我懂了，你们继续加油
