### ISSUE TITLE
开发微信小程序插件，插件内有页面和组件，当组件嵌入到宿主小程序，此时从组件跳到插件某个页面（navigateTo）再跳回（navigateBack），重启小程序，会报错。

### ISSUE THREAD

**Issue by ivanxinye** [NervJS/taro#11991]
### 相关平台
微信小程序

**小程序基础库: 2.23.4**
**使用框架: React**

### 复现步骤
开发微信小程序插件，插件内有页面和组件，当组件嵌入到宿主小程序，此时从组件跳到插件某个页面（navigateTo）再跳回（navigateBack），重启小程序，会报错。
报错位置 createNativeComponentConfig 中的attach调用setCurrent时，显示var route = currentPage.route || currentPage.__route__;的cannot read route of null。

function createNativeComponentConfig(Component, react, reactdom, componentConfig) {
  var _a, _b;

  R = react;
  h = react.createElement;
  ReactDOM = reactdom;
  setReconciler(ReactDOM);
  var componentObj = {
    options: componentConfig,
    properties: {
      props: {
        type: null,
        value: null,
        observer: function observer(_newVal, oldVal) {
          oldVal && this.component.forceUpdate();
        }
      }
    },
    created: function created() {
      if (!_tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["Current"].app) {
        initNativeComponentEntry(R, ReactDOM);
      }
    },
    attached: function attached() {
      var _this6 = this;

      setCurrent();
      this.compId = getNativeCompId();
      this.config = componentConfig;
      _tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["Current"].app.mount(Component, this.compId, function () {
        return _this6;
      });
    },
    ready: function ready() {
      Object(_tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["safeExecute"])(this.compId, 'onReady');
    },
    detached: function detached() {
      _tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["Current"].app.unmount(this.compId);
    },
    pageLifetimes: {
      show: function show(options) {
        Object(_tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["safeExecute"])(this.compId, 'onShow', options);
      },
      hide: function hide() {
        Object(_tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["safeExecute"])(this.compId, 'onHide');
      }
    },
    methods: {
      eh: _tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["eventHandler"]
    }
  };

  function setCurrent() {
    var pages = getCurrentPages();
    var currentPage = pages[pages.length - 1];
    if (_tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["Current"].page === currentPage) return;
    _tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["Current"].page = currentPage;
    var route = currentPage.route || currentPage.__route__;
    var router = {
      params: currentPage.options || {},
      path: Object(_tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["addLeadingSlash"])(route),
      onReady: '',
      onHide: '',
      onShow: ''
    };
    _tarojs_runtime__WEBPACK_IMPORTED_MODULE_7__["Current"].router = router;

    if (!currentPage.options) {
      // 例如在微信小程序中，页面 options 的设置时机比组件 attached 慢
      Object.defineProperty(currentPage, 'options', {
        enumerable: true,
        configurable: true,
        get: function get() {
          return this._optionsValue;
        },
        set: function set(value) {
          router.params = value;
          this._optionsValue = value;
        }
      });
    }
  } // onShareAppMessage 和 onShareTimeline 一样，会影响小程序右上方按钮的选项，因此不能默认注册。

### 期望结果
插件正常显示

### 实际结果
当插件内有自己的路由页时，跳至路由页再跳回，重启小程序，显示描述中报错导致插件无法被正常加载。

### 环境信息
```
�👽 Taro v3.4.3


  Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\Program Files\node.EXE 
      npm: 8.5.5 - D:\Program Files\npm.CMD  
```

**Comment by dazjean** [comment]
+1   当页面使用了插件中的组件，并且页面有链接跳转到插件页面时。存在如下问题：
1、进入A宿主页面，页面加载渲染了插件组件，在此页面跳转到插件页面，然后返回到页面A。
2、再次返回到宿主A页面的上一级，再次进入A页面。
必现：
```
WAServiceMainContext.js?t=wechat&s=1672369875918&v=2.25.0:1 TypeError: Cannot read property 'route' of null
    at c (VM732 appservice.js:formatted:9864)
    at Uo.attached (VM732 appservice.js:formatted:9834)
    at i.safeCallback (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at i.call (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at t (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at t (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at t (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at t (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at f (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)
    at d.insertChildToElement (WASubContext.js?t=wechat&s=1672369875918&v=2.25.0:1)(env: macOS,mp,1.06.2210310; lib: 2.25.0)
```

相关代码：

```
  function c(e) {
                        var t = getCurrentPages()
                          , n = t[t.length - 1];
                        if (s["Current"].page !== n) {
                            s["Current"].page = n;
                            var r = n.route || n.__route__
                              , i = {
                                params: n.options || {},
                                path: Object(s["addLeadingSlash"])(r),
                                $taroPath: e,
                                onReady: "",
                                onHide: "",
                                onShow: ""
                            };
                            s["Current"].router = i,
                            n.options || Object.defineProperty(n, "options", {
                                enumerable: !0,
                                configurable: !0,
                                get: function() {
                                    return this._optionsValue
                                },
                                set: function(e) {
                                    i.params = e,
                                    this._optionsValue = e
                                }
                            })
                        }
                    }
                    return (e.onShareAppMessage || (null === (i = e.prototype) || void 0 === i ? void 0 : i.onShareAppMessage) || e.enableShareAppMessage) && (o.methods.onShareAppMessage = function(e) {
                        var t = null === e || void 0 === e ? void 0 : e.target;
                        if (t) {
                            var n = t.id
                              , r = s["document"].getElementById(n);
                            r && (t.dataset = r.dataset)
                        }
                        return Object(s["safeExecute"])(this.compId, "onShareAppMessage", e)
                    }
```
