### ISSUE TITLE
Taro.authorize()不支持支付宝小程序吗？

### ISSUE THREAD

**Issue by geminiyu233** [NervJS/taro#1199]
1、做测试时调用授权API Taro.authorize(OBJECT)，提示支付宝小程序暂不支持 authorize，代码如下：
`handleClick(){
    Taro.authorize().then(res=>{
      console.log(res)
    })
  }`
是不是因为我使用的姿势不对？
2、API 文档可否更新一下对支付宝小程序和百度小程序API支持度？

**Comment by Chen-jj** [comment]
支付宝授权可以试试直接使用它的 API： [my.getAuthCode](https://docs.alipay.com/mini/api/openapi-authorize)。
API 文档支持度更新工作量颇大，所以短期内可能未必能够跟得上，欢迎 PR~

**Comment by geminiyu233** [comment]
目前有个项目想写一套代码分别编译微信和支付宝小程序，如果Taro不支持的支付宝或微信API，我就单拎出来写原生的，分别编译。
最后感谢！

**Comment by Surile** [comment]
同上，想用一套代码编译成微信，支付宝，头条。若是Taro支持各个小程序api的话，希望能在文档中更新。

**Comment by luckyadam** [comment]
API 和对应文档，我们会尽快同步的

**Comment by qiliangya** [comment]
请问现在taro 用来开发支付宝小程序可行吗。 是否还有大量适配问题, 有点不敢尝试~

**Comment by Eamonnzhang** [comment]
> 请问现在taro 用来开发支付宝小程序可行吗。 是否还有大量适配问题, 有点不敢尝试~ @luckyadam

+1 @luckyadam

**Comment by guxingke201** [comment]
@luckyadam [文档没有明确API 支持度是遗漏还是默认全部都支持?](https://nervjs.github.io/taro/docs/native-api.html#%E4%BA%A4%E4%BA%92%E5%8F%8D%E9%A6%88)

**Comment by Chen-jj** [comment]
@guxingke201 默认支持，如果使用有问题可以另外提 issue
