### ISSUE TITLE
Taro H5 如何配置路由拦截器

### ISSUE THREAD

**Issue by hqwlkj** [NervJS/taro#11994]
### 这个特性解决了什么问题？
需求：1、在进入首页之前需要判断用户是否登录，如果没有登录则跳转到登录页；2、如果用户访问的页面不存在则可以跳转到指定的404页面或者其它页面。

### 这个 API 长什么样？
类似于 react-router 的功能

**Comment by Chen-jj** [comment]
https://docs.taro.zone/docs/h5#%E8%B7%AF%E7%94%B1%E5%AE%88%E5%8D%AB

**Comment by youngpj** [comment]
解决了没，我也想知道。。
