### ISSUE TITLE
如何在首次进入页面时，在生命周期中将参数清空，保证下一次返回或者刷新页面时参数不存在

### ISSUE THREAD

**Issue by daisybaicai** [NervJS/taro#11998]
### 这个特性解决了什么问题？
可能从第三方页面跳转来时是xxxx/#/page/home/index?timestamp=12343&from=qq
将from和timestamp这种参数都清空，但不刷新页面，保证下次返回或者刷新页面时，是xxxx/#/page/home/index

### 这个 API 长什么样？
同上

**Comment by konka-king** [comment]
根据老夫多年的经验，可能没有这种api，这种需求具体是用在什么样的场景呢？

**Comment by AdvancedCat** [comment]
这个属于特殊业务场景的定制逻辑，需要业务自身去解决，而不能依赖框架本身去hack。

下次返回：onShow / onHide
刷新页面：持久性缓存页面状态，onMount时判断
