### ISSUE TITLE
jsx语法支持问题

### ISSUE THREAD

**Issue by JJJJYYYY** [NervJS/taro#12]
刚刚尝试了下demo
下面这种写法会编译错误。
```javascript
 <View className='index'>
   { [0, 1, 2, 3].map(i => <Text key={i}>{ i }</Text>) }
 </View>
```
编辑结果：
```
<block>
    <view class="index">{{[0, 1, 2, 3].map(i =>
        <Text wx:key={i}>{i}</Text>)}}</view>
</block>
```
写明`return`的写法可以
```
<View className='index'>
  {
    [0, 1, 2, 3].map(i => {
      return <Text key={i}>{ i }</Text>
    })
  }
</View>
```

因为`eslint`没有报错，所以怀疑是BUG。

**Comment by yuche** [comment]
是 bug，晚些时间发个新版本 fix 一下。

**Comment by yuche** [comment]
现在已经可以了，装一下最新版本的 `@tarojs/cli` 试一下。

**Comment by JJJJYYYY** [comment]
@yuche ,貌似还是不行
@tarojs/*: `version`: 0.0.40

又发现了新问题：
在`h5`模式下:
```
<View className='index'>
  {
    [1, 2, 3, 4, 0, 5].map(i => <Text key={i}>{ i }</Text>)
  }
</View>
```
渲染出来是`12345`,看了`Elements`元素`0`有元素，但内容为空

**Comment by yuche** [comment]
这个问题只出现在 h5 吗，还是小程序？

**Comment by JJJJYYYY** [comment]
@yuche ，是的

**Comment by yuche** [comment]
我们还是没办法复现这个 bug，能不能提供一下你的 `tarojs/components` 和 `nervjs` 的版本号？

**Comment by JJJJYYYY** [comment]
更新`nervjs`就没问题了，有问题的版本是`1.2.18`，不知道怎么回事，我创建项目的时候会有问题（创建了好几次，有时候没问题），更新`nervjs`到最新就好了，然后手动回退到`1.2.18`就有问题了，更新就可以了。   
还有更新到`0.0.41`后，小程序貌似还是不支持没有`return`的写法

**Comment by yuche** [comment]
但原来 0.0.40 的版本是小程序可以 `return` 但 H5 可能会有问题？更新 41 之后就反过来？

**Comment by JJJJYYYY** [comment]
没有`return`，我好像尝试的一直都不可以:smile:

**Comment by JJJJYYYY** [comment]
@yuche   
我`debug`了下，应该是`nerv-to-mp`那里的`render.js`有问题
164行 `t.isReturnStatement(parentNode)`  
  
这种情况下`parentNode`是`isArrowFunctionExpression`(不知道有没有其他情况)

还有一个问题，我为什么找不到`nerv-to-mp`的项目地址:joy:

**Comment by yuche** [comment]
nerv-to-mp 的版本号是多少，按理来说新版本如果 parentNode 是isArrowFunctionExpression 会先给他加上一个 return 然后走 return 的分子。

**Comment by yuche** [comment]
nerv-to-mp 就是 `@tarojs/transformer-wx`

**Comment by JJJJYYYY** [comment]
`package.json`上是`latest`
`node_modules`里面是`0.1.30`
一安装下来就是这个版本

**Comment by yuche** [comment]
https://www.npmjs.com/package/nerv-to-mp

最新的版本是 0.2.1

**Comment by JJJJYYYY** [comment]
确定没问题就行，关了
