### ISSUE TITLE
failed to resolve component：PageContainer

### ISSUE THREAD

**Issue by yeahjsen** [NervJS/taro#12004]
### 相关平台
微信小程序

**小程序基础库: 2.24.5**
**使用框架: Vue 3**

### 复现步骤
页面直接使用<PageContainer></PageContainer>，微信开发者工具
vendors.js:3342 [Vue warn]: Failed to resolve component: PageContainer
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <UserTrial tid="pages/userTrial/userTrial?$taroTimestamp=1656400680821" > 
  at <App>

### 期望结果
实现微信pageContainer效果

### 实际结果
微信开发者工具 failed to resolve

### 环境信息
```
👽 Taro v3.3.8

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD  
```

**Comment by yeahjsen** [comment]
warning里报PageContainer没有解析出来，这用不了了吧，我的环境下，直接<PageContainer :show="true"></PageContainer>,没有效果

**Comment by Chen-jj** [comment]
@yeahjsen Taro v3.4.12 没有复现

```html
<template>
  <view>
    <page-container :show="isShow" @clickoverlay="hc">
      <view style='height: 200px'>
        page-container
      </view>
    </page-container>
    <button @tap="hc">toggle</button>
  </view>
</template>

<script>
import Taro from '@tarojs/taro'

export default {
  name: 'ws-carema',
  data: () => {
    return {
      isShow: false
    }
  },
  methods: {
    hc () {
      this.isShow = !this.isShow
    },
  },
}
</script>
```

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/11807297/176395609-a9845072-661a-4261-9efe-4f00c42440cd.png">

另外 warn 的内容也不是说不能用，仔细看

**Comment by yeahjsen** [comment]
taro版本是3.3.8，这些都是issuse提交时的必填信息，都不是基于提交信息去看问题的吗？


------------------

59DC91D16676
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Wednesday, Jun 29, 2022 4:55 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [NervJS/taro] failed to resolve component：PageContainer (Issue #12004)





 
@yeahjsen Taro v3.4.12 没有复现
 <template&gt;   <view&gt;     <page-container :show="isShow" @clickoverlay="hc"&gt;       <view style='height: 200px'&gt;         page-container       </view&gt;     </page-container&gt;     <button @tap="hc"&gt;toggle</button&gt;   </view&gt; </template&gt; <script&gt; import Taro from ***@***.***/taro' export default {   name: 'ws-carema',   data: () =&gt; {     return {       isShow: false     }   },   methods: {     hc () {       this.isShow = !this.isShow     },   }, } </script&gt;
 

 
另外 warn 的内容也不是说不能用，仔细看

**Comment by yeahjsen** [comment]
升级下taro版本

**Comment by yeahjsen** [comment]
![lQLPJxZy48G3lyfNAofNBniwnyfhRSSwbHkCvU0yhcAGAA_1656_647](https://user-images.githubusercontent.com/16367513/176428515-507d10ee-2da5-47d2-9d02-deb9ebed3bc7.png)
![lQLPJxZy48G3lxvNA1PNAu-wYzsTrIFUXjwCvU0yh0CHAA_751_851](https://user-images.githubusercontent.com/16367513/176428639-286b2e88-e2ee-4199-ab8e-e3e60d0a4104.png)
只能说是版本问题，提交的issue里taro版本是3.3.8
