### ISSUE TITLE
写了一个组件，只能在一个页面引用，两个页面如果都用了就失效了～～～

### ISSUE THREAD

**Issue by jianjian-commits** [NervJS/taro#12002]
### 这个特性解决了什么问题？
无法复用

### 这个 API 长什么样？
正常来说哪个页面要用直接import导入就好了

**Comment by konka-king** [comment]
描述内容太少了，有没有 repo

**Comment by Chen-jj** [comment]
> 不会吧？ 描述内容太少了，有没有 repo

+1

@jianjian-commits 麻烦按 bug report 的 issue 模板重新提一个吧，最好附上 demo
