### ISSUE TITLE
百度小程序问题汇总

### ISSUE THREAD

**Issue by SzHeJason** [NervJS/taro#1200]
**问题描述**
当跨组件传递事件的时候 将会导致数据丢失问题 无法获取 bind 函数传递的参数
 
**复现步骤**
```jsx
// parent.js
import Taro, { Component } from "@tarojs/taro"
import { View } from "@tarojs/components"

import DemoComponent from "../demo/index"

export default class Parent extends Component {
  handleClick = (...arg) => {
    console.log(arg) // 获取不到 1
  }

  render() {
    return (
      <View on className='container'>
        <DemoComponent data-title='????' onClick={this.handleClick.bind(this,1)} />
      </View>
    )
  }
}

```

```jsx
// demo.js
import Taro, { Component } from "@tarojs/taro"
import { View } from "@tarojs/components"

export default class Demo extends Component {
  render() {
    return (
      <View on className='container' onClick={this.props.onClick}>
        测试
      </View>
    )
  }
}

```

**期望行为**
希望能在 handleClick 函数里面获取到 bind 传递的参数 与 小程序的行为一致

**系统信息**

 - 操作系统: MacOS
 - Taro 版本 1.1.9
 - Node.js 版本 10.0.0
 - 报错平台 swan

**Comment by jimczj** [comment]
事件类型错误，变成 boolean 值了
![image](https://user-images.githubusercontent.com/13499146/48833009-743fc580-edb5-11e8-96b1-58da3aa614c4.png)

**Comment by luckyadam** [comment]
百度小程序的问题，自定义组件上，data-* 绑定的东西无法通过 dataset 拿到，正在联系解决

**Comment by SzHeJason** [comment]
![image](https://user-images.githubusercontent.com/20609396/49424206-dbf20980-f7d4-11e8-83f3-9ab6785ec335.png)
最新版依然存在问题

**Comment by frojan** [comment]
1. require不支持循环引用，自行避免。
2. 图片链接不能省略协议头，否则不显示（https://xxx/img.jpg， 不能用//xxx/img.jpg）。
