### ISSUE TITLE
yarn dev:weapp 报 Cannot convert undefined or null to object；yarn build:weapp 报 (0 , n.AW) is not a function

### ISSUE THREAD

**Issue by ZhuQinPeng** [NervJS/taro#12006]
### 相关平台
微信小程序

**小程序基础库: 2.24.6**
**使用框架: React**

### 复现步骤
项目升级到3.5.0-beta.2，运行yarn dev:weapp yarn buld:weapp
（yarn dev:weapp报的错已经找到解决办法）

### 期望结果
打包后能正常运行

### 实际结果
报错

### 环境信息
```
👽 Taro v3.5.0-beta.2


  Taro CLI 3.5.0-beta.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
tarojs 版本 3.5.0-beta.2 webpack@5.69.0

**Comment by ZhuQinPeng** [comment]
报错信息如下：
![微信图片_20220629092719](https://user-images.githubusercontent.com/18671583/176331890-9e0ba94e-3534-4f2d-b663-48f867806277.png)

**Comment by Chen-jj** [comment]
@ZhuQinPeng 麻烦提供一下可复现的 Demo

**Comment by ZhuQinPeng** [comment]
> @ZhuQinPeng 麻烦提供一下可复现的 Demo

没有专门弄个demo，就项目从3.4.11升级到3.5.0-beta.2之后，使用webpack5打包，运行yarn build:weapp 就报这个

**Comment by ZhuQinPeng** [comment]
仅记录一下，便于以后查找：小程序使用require拼接图片地址引起的问题
