### ISSUE TITLE
分包中公用的scss文件，打包优化

### ISSUE THREAD

**Issue by heymie** [NervJS/taro#12013]
### 这个特性解决了什么问题？
在开启最小化主包的功能下，当前分包中公用scss全部拷贝至需要使用的页面，导致拷贝多份，是否可以保持原有结构不变，节省分包size。

### 这个 API 长什么样？
能够优化scss的打包逻辑，示例demo:https://github.com/heymie/test_sub_common_scss

**Comment by Chen-jj** [comment]
与分包无关，Sass 的行为就是会把 `@import` merge 到同一个输出的样式文件中。

建议 Sass 变量、函数使用 Sass `@import`，公共样式使用 JS import。这样公共样式才能被 Webpack Splitchunk 正确抽取到公共模块。
