### ISSUE TITLE
render里 {JSON.stringify(this.state.sumPrice)} 正确的值，{this.state.sumPrice}就是错误的值

### ISSUE THREAD

**Issue by jiaowokeye** [NervJS/taro#1201]
**问题描述**
   页面显示一个state.sumPrice   typeof(sumPrice) = "number";
   在render函数里
```
    {JSON.stringify(this.state.sumPrice)} 是正确的状态值
       
    {this.state.sumPrice}//错误的值
```

**复现步骤**
```js
  //计算总价
  evalSumPrice = (dataP) => {
      let sum = 0;
      let data = dataP;
      let selectData = [];
      for (let i = 0; i < data.length; i++) {
          if (data[i].checked && data[i].c_count !== "") {
              selectData.push(data[i]);
              let price = 0;
              let commodityPrices = data[i].commodity.commodityPrices ? data[i].commodity.commodityPrices : []
              if (commodityPrices !== null && commodityPrices.length > 0) {
                  price = commodityPrices[0].c_price;
              }
              sum += price * data[i].c_count;
          }
      }
      this.setState({
          "sumPrice": sum.toFixed(2),
          "selectData": selectData,
          "checkall":true
      })
  }

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.7]
 - Node.js 版本 [e.g. v10.13.0]
 - 报错平台 [weapp]

**补充信息**
   {JSON.stringify(this.state.sumPrice)} 是正确的状态值
       
    {this.state.sumPrice}//错误的值

**Comment by Chen-jj** [comment]
提供一下完整代码

**Comment by jiaowokeye** [comment]
就是类似于这种，我写个简短的代码

`
class Index extends Component {

  config = {
    navigationBarTitleText: '购物车'
  }
  state = {
     sumprice:0
 }
 changeSumprice(){
    this.setState({
      sumprice:12
    })
 }
render(){
   ////下面例子在changeSumprice 执行前后
   ////这里输出  执行前后一直是0
   return <View>
       {
             this.state.sumprice     
       }
  </View>

   ////第二种情况
   ////第一次是0  第二次是12   结果正确
     return <View>
       {
            JSON.stringify( this.state.sumprice)   
       }
  </View>
  
  ////第三种情况
   ////第一次是0  第二次是12   结果正确
  const { sumprice } = this.state;
     return <View>
       {
            sumprice
       }
  </View>


}


`

**Comment by jiaowokeye** [comment]
第一种应该是我写代码不规范的原因，因为这个所以取不到最新的state，在微信小程序开发工具的 appdata里  sumprice 也变不过来

**Comment by Chen-jj** [comment]
老哥你不给一份完整可执行的代码是无法定位问题的。
