### ISSUE TITLE
编译支付宝小程序产物中页面应该是 import  base.axml 文件，而不是每个文件复制一份 base.axml

### ISSUE THREAD

**Issue by moyafaxi** [NervJS/taro#12019]
### 这个特性解决了什么问题？
size 问题

### 这个 API 长什么样？
支付宝小程序产物中页面应该是 import  base.axml 文件，现在打包后每个页面都是复制了一份 base.axml，导致 size 很大

看了一下代码，https://github.com/NervJS/taro/blob/next/packages/taro-alipay/src/index.ts#L26 在这里特地做了这个处理，这个处理的场景是什么。

我在自己的项目中试着把 modifyPageTemplate 方法调用注释了，项目运行也是正常的

**Comment by moyafaxi** [comment]
@Chen-jj  老哥 麻烦看下这段逻辑现在还需要么 https://github.com/NervJS/taro/blob/next/packages/taro-alipay/src/index.ts#L26

**Comment by Chen-jj** [comment]
需要的

**Comment by moyafaxi** [comment]
> 需要的

支付宝文档中找到了，现在编译完每个页面都会默认引用 custom-wrapper，所以会走进这段逻辑。

<img width="796" alt="image" src="https://user-images.githubusercontent.com/22743801/176849360-2f18f408-79f8-4963-99a4-e6a14ae47274.png">

**Comment by Chen-jj** [comment]
受支付宝小程序 template 限制，仍然没有很好的办法处理此问题。目前能想到的办法只有当用户没有使用到 CustomWrapper 的时候，页面不引用 custom-wrapper。但如果用户在项目中使用了 CustomWrapper，仍会为所有页面复制一份 base.wxml 模板。
