### ISSUE TITLE
[feature request] Navigator在h5中的支持

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#1202]
小程序现在支持程度很高了，但是h5的不少特性还没同步更上来，例如Navigator这个组件。
虽然换用View onClick然后手动调也行，但还是希望官方能支持这个组件。

**Comment by jinjinjin0731** [comment]
ok

**Comment by tourze** [comment]
这个issue提到的问题，是已经解决了吗？

**Comment by jinjinjin0731** [comment]
忘了关，已经解决的
