### ISSUE TITLE
支持npm自定义入口吗？

### ISSUE THREAD

**Issue by liangxingchen** [NervJS/taro#1203]
我有一个跨平台的npm包，在不同平台打包时使用不同的入口，package.json 是这样设置的：
```json
{
  "main": "lib/node.js",
  "browser": "lib/client.js",
  "miniprogram": "lib",
}
```
小程序官方原生使用的入口是miniprogram，请问taro有专用入口吗？

**Comment by yuche** [comment]
现在还不支持，但着是一个很好的想法

**Comment by liangxingchen** [comment]
我希望 package.json 支持如下入口：
```js
{
  "taro":"taro 默认入口",
  "taro:h5": "taro-h5.js",
  "taro:rn": "taro-rn.js",
  "taro:weapp": "taro-weapp.js",
  // ...
}
```
 或者支持打包时依据平台不同可以设置npm映射，在config中：
```js
{
  weapp:{
     npm: {
         akita: "akita/lib/taro"
     }
  }
}
```

**Comment by luckyadam** [comment]
暂不支持，后续可以搞一下

**Comment by leeyeh** [comment]
browser 字段是有个社区的 spec 的： https://github.com/defunctzombie/package-browser-field-spec

webpack 设计了一个更通用的 https://webpack.js.org/configuration/resolve/#resolve-aliasfields 的机制，可以指定 resolve 的时候将 package.json 中的哪些字段作为 alias 的配置来使用。如果 taro 用的是 webpack 打包的话可以直接使用这个功能实现这个需求。

这里有个例子： https://github.com/mpvue/mpvue-quickstart/pull/31

**Comment by luckyadam** [comment]
> browser 字段是有个社区的 spec 的： https://github.com/defunctzombie/package-browser-field-spec
> 
> webpack 设计了一个更通用的 https://webpack.js.org/configuration/resolve/#resolve-aliasfields 的机制，可以指定 resolve 的时候将 package.json 中的哪些字段作为 alias 的配置来使用。如果 taro 用的是 webpack 打包的话可以直接使用这个功能实现这个需求。
> 
> 这里有个例子： [mpvue/mpvue-quickstart#31](https://github.com/mpvue/mpvue-quickstart/pull/31)

收到~ 感谢李工~ 我研究下~

**Comment by WingGao** [comment]
目前有进展吗？

**Comment by zhyjor** [comment]
目前进展如何了

**Comment by Chen-jj** [comment]
Taro 2、3 使用 webpack 构建，可以直接配置 aliasfields 了
