### ISSUE TITLE
@tarojs/cli为什么要把@tarojs/plugin-platform-react放在dependencies中？

### ISSUE THREAD

**Issue by czheji** [NervJS/taro#12035]
### 相关平台
微信小程序

**小程序基础库: 与此无关**
**使用框架: React**

### 复现步骤
使用tarojs/cli命令行创建一个项目
taro init hello
选择rect和默认模板，查看pacakge.json，发现dependencies中存在"@tarojs/plugin-framework-react"
```


### 期望结果
@tarojs/plugin-framework-react在devDependencies中

### 实际结果
@tarojs/plugin-framework-react在dependencies中

### 环境信息
```
  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD

```


---
### 补充信息
@tarojs/plugin-framework-react的说明是：“Taro 插件。用于支持编译 React/PReact/Nerv”，按我理解这个不是给webpack用来编译的吗，为什么会出现在dependencies，难道发布/运行时也需要使用？

<!-- generated by taro-issues. 请勿修改或删除此行注释 --><!--labels=T-weapp,V-3,F-react-->

**Comment by Chen-jj** [comment]
@czheji 在 3.5 中已经从 taro cli 里去掉了此依赖
