### ISSUE TITLE
taro3 vue3中列表分页加载渲染慢，导致无法滚动屏幕

### ISSUE THREAD

**Issue by git-guining** [NervJS/taro#12044]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/gitee-guining/taro3-vue3](https://gitee.com/gitee-guining/taro3-vue3)
**小程序基础库: 2.25.0**
**使用框架: Vue 3**

### 复现步骤
git clone
npm install
npm run dev:weapp
手机预览，向下滑动，页面渲染慢，渲染期间无法滚动页面
taro版本为👽 Taro v3.4.13

### 期望结果
加速渲染，每页20条数据，loading结束，可以滚动，demo中去掉了请求，用数据模拟的请求

或者有没有可以监听到渲染结束的方法，hideLoading在渲染结束后调用

### 实际结果
数据加载完毕后，需要等待1-2s才可以滚动，低端机更明显

### 环境信息
```
👽 Taro v3.4.13

3.4.13
PS D:\workspace\myApp> taro info
👽 Taro v3.4.13


  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by git-guining** [comment]
由于gitee这是public需要审核，复现仓库改为https://github.com/git-guining/taro3-vue3

**Comment by Chen-jj** [comment]
@git-guining  

1. pre_list 外层加一下 `<custom-wrapper>`

```html
<custom-wrapper>
  <view class="pre_list">...</view>
</custom-wrapper>
```

2. 问题主要在于 setData 的数据量较大，因为 Taro3 是运行时方案，setData 时会把一些节点信息也一并设置，从而导致数据量增大（设置 `Taro.options.debug = true` 可以看到 setData 的数据）。看看我们能做些什么：

- Taro v3.5 对 setData 的节点信息做了精简，数据量有一定的下降，可以尝试一下升级。
- 尽量减少每条 item 内的节点数。
- 尽量缩短 `className`。原因同上，className 是节点信息，因此同样会被 setData。（目测影响不会太大，可以最后再试试）
- 针对安卓平台减少分页渲染的数据量。

3. `Taro.nextTick` 相当于是 setData 的回调：

> 或者有没有可以监听到渲染结束的方法，hideLoading在渲染结束后调用

可以这样写：

```js
Taro.nextTick(() => {
  Taro.hideLoading()
})
```

4. 如果还有问题，建议尝试封装虚拟列表，只渲染一定数量的节点（目前 Taro 只封装了 React 版本的，后续会提供 Vue3 版本）。

**Comment by git-guining** [comment]
const getPresList = async () => {
      Taro.showLoading({ title: '加载中...'})
      console.log(new Date().getTime(), 'start')
      presList.value.push(...mydata)
      Taro.nextTick(() => {
          Taro.hideLoading()
           console.log(new Date().getTime(), 'end')
      })
}


log:
1657592152095 "start"
1657592152157 "end"
custom wrapper setData:  {i.cn.[0].cn: Array(242)}
小程序 setData 时长： 681ms



Taro.nextTick不是setData的回调

**Comment by git-guining** [comment]
以上方案除虚拟列表都已试过，效果不大

**Comment by Chen-jj** [comment]
具体机型是？

**Comment by git-guining** [comment]
> 具体机型是？

机型是小米6，安卓9

**Comment by Chen-jj** [comment]
身边没有小米 6，拿了太同是 2017 年的小米 Mix2 来测试，前 5 页加载感觉在 500 ms 内都能响应，没有感觉到需要 1-2s，后续因为节点增多是会逐步变慢

**Comment by git-guining** [comment]
> 身边没有小米 6，拿了太同是 2017 年的小米 Mix2 来测试，前 5 页加载感觉在 500 ms 内都能响应，没有感觉到需要 1-2s，后续因为节点增多是会逐步变慢

我刚刚试了下，第一次setData耗时1007ms，第五次1500+ms，当前的demo只有一个简单的列表，有试用过官方文档提供的案例（九机商城，框架: vue3，Taro：3.3.14），在我的手机上，列表加载loading结束后就可以滚动，不知道是怎么实现的，请问是否有优化的思路

**Comment by Chen-jj** [comment]
外部案例的具体实现我们也不清楚的。升级 3.5 了吗？安卓减少分页数量呢？

**Comment by git-guining** [comment]
> 外部案例的具体实现我们也不清楚的。升级 3.5 了吗？安卓减少分页数量呢？

有升级3.5，在米6上效果不大，目前分页是20条数据

Taro.nextTick好像不是在setData结束后才回调，昨天在米6和开发者工具上调试，Taro.nextTick回调执行比setData结束后要早，log如下：
1657592152095 "start" // 这里是push前的log
1657592152157 "end" // 这里是Taro.nextTick回调的log
custom wrapper setData: {i.cn.[0].cn: Array(242)}
小程序 setData 时长： 681ms

**Comment by git-guining** [comment]
刚刚用uni-app跑了同一个demo，加载很快，没有卡顿，orz

**Comment by git-guining** [comment]
刚刚用uni-app跑了同一个demo，加载很快，没有卡顿，orz

**Comment by fangxiaoxingit** [comment]
确实，高端旗舰机这个问题不明显，但是性能稍微不行的，就明显了

**Comment by Chen-jj** [comment]
> Taro.nextTick好像不是在setData结束后才回调，昨天在米6和开发者工具上调试，Taro.nextTick回调执行比setData结束后要早

的确，Vue state 变化到真正 `flushJobs` 还有一个 `Promise.then` 的延时，所以要放在 Vue 的 nextTick 里执行才可以：

```js
vue.nextTick(() => Taro.nextTick(() => Taro.hideLoading()))
```

**Comment by Chen-jj** [comment]
再次测试了一下，这种场景下 Taro 性能主要受制于**节点数量**，而 `setData` 的数据量影响不大。

目前只能建议降低每次渲染的条目数来解决，后续我们再看看有什么优化的办法。

**Comment by git-guining** [comment]
> > Taro.nextTick好像不是在setData结束后才回调，昨天在米6和开发者工具上调试，Taro.nextTick回调执行比setData结束后要早
> 
> 的确，Vue state 变化到真正 `flushJobs` 还有一个 `Promise.then` 的延时，所以要放在 Vue 的 nextTick 里执行才可以：
> 
> ```js
> vue.nextTick(() => Taro.nextTick(() => Taro.hideLoading()))
> ```

多谢，这样确实可以解决目前列表加载的问题
