### ISSUE TITLE
taro@3.4.12版本使用Vant Weapp中的van-uploader组件不进入回调函数onBeforeRead

### ISSUE THREAD

**Issue by hhhzzy** [NervJS/taro#12042]
### 相关平台
微信小程序

**小程序基础库: 2.25.0**
**使用框架: React**

### 复现步骤
1.绑定onBeforeRead事件
<van-uploader fileList={this.state.imgUrl} onBeforeRead={this.onBeforeRead} />
2.获取返回值
    onBeforeRead = (file) => {
        console.log(file);
        return false;
    };

### 期望结果
在onBeforeRead函数中获取返回值或者中断上传流程

### 实际结果
不进入回调函数

### 环境信息
```
👽 Taro v3.4.12


  Taro CLI 3.4.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - D:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - D:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
这种 `onXXX` 形式的函数 props 传递和 JSX 的事件绑定语法是有冲突的，暂时没有很好的兼容办法
