### ISSUE TITLE
taro3.5  apple  m1芯片初始项目后启动报错

### ISSUE THREAD

**Issue by hrhrhr2** [NervJS/taro#12049]
### 相关平台
H5

**浏览器版本: Chrome**
**使用框架: Vue 3**

### 复现步骤
m1芯片电脑使用taro3.5初始项目后无法启动，提示   

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '@swc/core-darwin-arm64'
Require stack:
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@swc/core/binding.js
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@swc/core/index.js
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-prebundle/dist/prebundle/bundle.js
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-prebundle/dist/prebundle/index.js
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-prebundle/dist/index.js
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-runner/dist/index.mini.js
- /Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-runner/index.js
- /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/helper/dist/npm.js
- /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/helper/dist/index.js
- /usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/helper/index.js
- /usr/local/lib/node_modules/@tarojs/cli/dist/util/index.js
- /usr/local/lib/node_modules/@tarojs/cli/bin/taro
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@swc/core/binding.js:129:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/usr/local/lib/node_modules/@tarojs/cli/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@swc/core/binding.js',
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@swc/core/index.js',
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-prebundle/dist/prebundle/bundle.js',
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-prebundle/dist/prebundle/index.js',
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-prebundle/dist/index.js',
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-runner/dist/index.mini.js',
    '/Users/hr/Documents/workspace/app/roface-h5-vue/node_modules/@tarojs/webpack5-runner/index.js',
    '/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/helper/dist/npm.js',
    '/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/helper/dist/index.js',
    '/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/helper/index.js',
    '/usr/local/lib/node_modules/@tarojs/cli/dist/util/index.js',
    '/usr/local/lib/node_modules/@tarojs/cli/bin/taro'
  ]
}

### 期望结果
正常启动

### 实际结果
无法启动

### 环境信息
```
👽 Taro v3.5.0-beta.4


  Taro CLI 3.5.0-beta.4 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/helper: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/plugin-platform-alipay: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/plugin-platform-jd: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/plugin-platform-qq: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/plugin-platform-swan: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/plugin-platform-tt: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/plugin-platform-weapp: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/router: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/runtime: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/shared: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/taro: 3.5.0-beta.4 => 3.5.0-beta.4 
      @tarojs/taro-h5: 3.5.0-beta.4 => 3.5.0-beta.4 
      babel-preset-taro: 3.5.0-beta.4 => 3.5.0-beta.4 
      eslint-config-taro: 3.5.0-beta.4 => 3.5.0-beta.4 

```

---
### 补充信息
tarojs/cli 3.4版本无异常

**Comment by ZakaryCode** [comment]
这看似是包管理器安装依赖策略导致的，问下你具体使用那个包管理器安装依赖

- npm 会根据环境安装 `optionalDependencies` 依赖，可能由于未适配 m1 芯片导致依赖缺失，可以尝试升级 npm 修复该问题；
- yarn 会安装所有 `optionalDependencies` 依赖，理论上不会有这个问题；
- 同样你也可以在项目内安装缺失依赖修复该问题。

**Comment by hrhrhr2** [comment]
使用的是npm 版本是8.1.0,已发现问题产生的条件，使用vscode 中的template初始化项目不会出现此情况，当使用mac中自带的template终端则会出现该情况

**Comment by githubCK** [comment]
init之后使用yarn upgradePeerdeps 出现pod install安装错误；mac m1芯片
有这类问题么

**Comment by wuang1992** [comment]
> init之后使用yarn upgradePeerdeps 出现pod install安装错误；mac m1芯片 有这类问题么

+1

**Comment by Xhyen** [comment]
遇到同样的问题了 有解决方案吗

**Comment by zy0228** [comment]
执行 npx @tarojs/cli init myApp 直接报错
`node:internal/modules/cjs/loader:1028
  const err = new Error(message);
              ^  
Error: Cannot find module '@tarojs/binding-darwin-arm64`
