### ISSUE TITLE
h5的swiper组件随onchange事件设置current的话,swiperItem错位

### ISSUE THREAD

**Issue by li405744717** [NervJS/taro#1204]
`<Swiper className='swiper_container' onChange={this.onChange.bind(this)}
                    current={this.state.swiperCurrent}>`
`//滚动监听事件
  onChange(e) {
    let current = e.detail.current;
    this.setState({
      swiperCurrent:current
    })
  ...
}`

**Comment by jinjinjin0731** [comment]
ok

**Comment by jinjinjin0731** [comment]
已修复
