### ISSUE TITLE
项目启动报错：ReferenceError: defineAppConfig is not defined

### ISSUE THREAD

**Issue by xhan4** [NervJS/taro#12050]
### 相关平台
H5

**浏览器版本:  Chrome 103.0.5060.114**
**使用框架: Vue 3**

### 复现步骤
@tarojs/cli  3.5.0-beta.4 
vue3
webpack5
非ts
默认模板

### 期望结果
初始化项目正常

### 实际结果
初始化启动后报错：ReferenceError: defineAppConfig is not defined

### 环境信息
```
� Taro v3.5.0-beta.4


  Taro CLI 3.5.0-beta.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - E:\nodejs\node.EXE
      Yarn: 1.22.17 - E:\nodejs\node_global\yarn.CMD
      npm: 8.1.1 - E:\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
未通过描述找到该问题，请检查本地项目依赖版本，或者提供可复现的测试项目。
