### ISSUE TITLE
H5 input组件  重新进入页面后  foucs 属性失效

### ISSUE THREAD

**Issue by gowago** [NervJS/taro#12054]
### 相关平台
H5

**浏览器版本: 103.0.5060.114（正式版本） （64 位）**
**使用框架: Vue 3**

### 复现步骤
B页面内 foucs组件属性失效
A 页面 导航到B 页面   foucs属性生效
back回退 后  再进入B页面 属性就不生效了

### 期望结果
聚焦

### 实际结果
不聚焦

### 环境信息
```
  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.5 - D:\Program Files\nodejs\npm.CMD
```

**Comment by ilovelll** [comment]
我在 React 版本下也不生效， Taro 3.4.9

**Comment by ZakaryCode** [comment]
> B页面内 foucs组件属性失效

未能理解这一出所指问题，也无法复现


> A 页面 导航到B 页面 foucs属性生效
> back回退 后 再进入B页面 属性就不生效了

这应该是指已存在的页面在 onShow 时，并没有重新调用 foces 事件，当前可以自行调用，后续版本中优化该问题。

**Comment by ilovelll** [comment]
> 

已经在 `useDidShow` 中调用了，还是不能focus

**Comment by ZakaryCode** [comment]
> 已经在 `useDidShow` 中调用了，还是不能focus

给个 demo 看看你咋写的

**Comment by gowago** [comment]
解决了 要先赋值 false  然后 nextick回调里面赋值 true 才行
