### ISSUE TITLE
运行时 Page 类型的 route 字段未定义

### ISSUE THREAD

**Issue by harry-xm** [NervJS/taro#12065]
### 这个特性解决了什么问题？
Debug 指南中有提到

> 更普适的方法则是通过 `getCurrentPages` 函数访问到当前页面的示例，然后访问实例的 `route` 或 `__route__` 访问到当前页面路由的路径。

但 packages/taro/types/api/framework/index.d.ts 中 Page 类型的定义只有 `route` 一个字段，只通过该字段获取路由可能返回 undefined。

### 这个 API 长什么样？
期望 Taro 能封装一层，统一在 `route` 上获取页面路径。如果封装无法实现的话，建议将 `__route__` 也暴露到类型定义里。

**Comment by ZakaryCode** [comment]
此处会优化类型，由于不同小程序实现问题，推荐以下写法获取：

```ts
Taro.getCurrentInstance().router?.path
```
