### ISSUE TITLE
Taro v3.4.13开发模式运行在微信小程序打开预览提示message：Error: dist/pages/index/index.json: ["usingComponents"]["custom-wrapper"]: "../../custom-wrapper" 未找到

### ISSUE THREAD

**Issue by luo199393** [NervJS/taro#12067]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/luo199393/test.git](https://github.com/luo199393/test.git)
**小程序基础库: 2.17.0**
**使用框架: Vue 3**

### 复现步骤
1、taro init myApp
2、选择vue3
3、选择js
4、选择模板为 vue3-nutui3.0模板
5、最后 npm run dev:weapp - -watch
6、小程序打开进入myapp项目，使用预览模式

### 期望结果
默认创建模板项目可以在微信小程序预览成功

### 实际结果
message：Error: dist/pages/index/index.json: ["usingComponents"]["custom-wrapper"]: "../../custom-wrapper" 未找到
appid: 
openid: 
ideVersion: 1.06.2206090
osType: win32-x64
time: 2022-07-16 21:11:04

### 环境信息
```
👽 Taro v3.4.13


  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - C:\data\date\node\nodejs\node.EXE
      Yarn: 1.22.10 - C:\data\date\node\node_global\yarn.CMD
      npm: 6.14.8 - C:\data\date\node\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@luo199393 写错了，Vue 是 `<custom-wrapper>`，并且不需要引入。

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/11807297/179763057-cdd3308c-503f-4145-9566-af102423559b.png">
