### ISSUE TITLE
Property 'onUnload' does not exist on type 'TaroStatic'. 

### ISSUE THREAD

**Issue by wuweikd** [NervJS/taro#12074]
### 相关平台
微信小程序

**小程序基础库: 无关**
**使用框架: React**

#### 代码
```
import Taro from "@tarojs/taro";

....

Taro.onUnload()


```
#### 错误提示

TS2339: Property 'onUnload' does not exist on type 'TaroStatic'.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/34428646/179525128-4fbbf2cd-e0fa-4907-8bfd-a705ea6506d3.png">

onUnload 是再哪个方法调用

### 期望结果
正常调用onload 和 onunload 

### 实际结果
方法不存在

### 环境信息
```


👽 Taro v3.4.13


  Taro CLI 3.4.13 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.13 => 3.4.13 
      @tarojs/components: 3.4.13 => 3.4.13 
      @tarojs/mini-runner: 3.4.13 => 3.4.13 
      @tarojs/plugin-framework-react: 3.4.13 => 3.4.13 
      @tarojs/plugin-html: 3.4.13 => 3.4.13 
      @tarojs/react: 3.4.13 => 3.4.13 
      @tarojs/runtime: 3.4.13 => 3.4.13 
      @tarojs/taro: 3.4.13 => 3.4.13 
      @tarojs/webpack-runner: 3.4.13 => 3.4.13 
      babel-preset-taro: 3.4.13 => 3.4.13 
      eslint-config-taro: 3.4.2 => 3.4.2 
      react: ^17.0.0 => 17.0.2 
```

**Comment by airqj** [comment]
3.5才支持

**Comment by wuweikd** [comment]
> 
![image](https://user-images.githubusercontent.com/34428646/179707820-5122de56-00ef-4380-a5df-c48154e2714a.png)
?

**Comment by Chen-jj** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/34428646/179707820-5122de56-00ef-4380-a5df-c48154e2714a.png) ?

看成 useUnload 了，我们检查一下的

**Comment by ZakaryCode** [comment]
> TS2339: Property 'onUnload' does not exist on type 'TaroStatic'.

这个是页面的生命周期，并非挂载在 Taro 上的钩子，参考文档写法如下：

```tsx
class Test extends React.Component {
  onUnload () {
    // ...
  }

  render () {
    return (
      <>...</>
    )
  }
}
```

**Comment by wuweikd** [comment]
> > TS2339: Property 'onUnload' does not exist on type 'TaroStatic'.
> 
> 这个是页面的生命周期，并非挂载在 Taro 上的钩子，参考文档写法如下：
> 
> ```tsx
> class Test extends React.Component {
>   onUnload () {
>     // ...
>   }
> 
>   render () {
>     return (
>       <>...</>
>     )
>   }
> }
> ```

hook 写法怎么支持呢

**Comment by lilingling3** [comment]
taro 3.5.12 组件执行顺序发现变化了，onUnload 不执行，  componentDidShow 先执行在执行关闭页面的componentWillUnmount
