### ISSUE TITLE
怎么样在taro中import代码会比taro.js更优先执行？

### ISSUE THREAD

**Issue by cjinhuo** [NervJS/taro#12076]
### 这个特性解决了什么问题？
如果我想在支付宝平台下监听request，也就是监听my.request，但是taro在代码中提前将my.request保存起来，导致监听无效？

taro代码：const nativeRequest = my.canIUse('request') ? my.request : my.httpRequest

当然可以直接监听Taro.request，但是想着更接近平台一点

### 这个 API 长什么样？
~

**Comment by AdvancedCat** [comment]
怎么个监听法？

**Comment by cjinhuo** [comment]
> 怎么个监听法？

const originRequest = my.request
my.request = function(options){
   // use options
  return originRequest(options)
}

类似这种方式

**Comment by AdvancedCat** [comment]
> > 怎么个监听法？
> 
> const originRequest = my.request my.request = function(options){ // use options return originRequest(options) }
> 
> 类似这种方式

如果你仅仅为了 `use options`，那监听 `Taro.request` 也是一样的。Taro拦截 request 是为了 promise 化，options会透传的
