### ISSUE TITLE
taro无 jd.navigateToNative 小程序跳转到宿主页面

### ISSUE THREAD

**Issue by LinShuling16** [NervJS/taro#12070]
### 这个特性解决了什么问题？
jd.navigateToNative 小程序跳转到宿主页面 

### 这个 API 长什么样？
实现jd.navigateToNative 小程序跳转到宿主页面

**Comment by Chen-jj** [comment]
@LinShuling16 是没有 `Taro. navigateToNative` 还是没有 `jd.navigateToNative`
