### ISSUE TITLE
支付宝小程序 Taro.removeStorageSync() 接口无效

### ISSUE THREAD

**Issue by yanghcc** [NervJS/taro#1207]
**问题描述**
[问题描述：支付宝小程序 Taro.removeStorageSync() 接口无效，无法正常删除缓存在本地的数据]

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [ v.1.1.3]
 - Node.js 版本 [v8.12.0]
 - 报错平台 [支付宝小程序开发者工具，支付宝app]

**Comment by luckyadam** [comment]
升级到 1.1.9 试试
