### ISSUE TITLE
Taro nutui H5要如何实现路由和路由嵌套 如何实现局部更新组件？

### ISSUE THREAD

**Issue by binghc** [NervJS/taro#12071]
### 这个特性解决了什么问题？
Taro不支持vue router，那要如何实现路由和路由嵌套，直接用Taro的路由api 都是跳到一个全新页面，
那H5有很多公用的组件如何解决？难道在每个页面重新写一遍组件？

比如用Tarao nutui 开发一个商城项目，底部有一个tabbar，难道每个页面都要写一遍tabbar？
如何解决路由，实现局部更新问题？

### 这个 API 长什么样？
支持路由 支持局部刷新

**Comment by ZakaryCode** [comment]
参考文档添加[路由守卫](https://nervjs.github.io/taro-docs/docs/h5/#%E8%B7%AF%E7%94%B1%E5%AE%88%E5%8D%AB)

路由嵌套并实现局部刷新，可以参考对应社区路由实现。

**Comment by Chen-jj** [comment]
另外 Taro 下一个主要版本讲支持 React/Vue Router
