### ISSUE TITLE
尺寸转换错误

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#12089]
### 相关平台
H5

**浏览器版本: zuixin**
**使用框架: React**

### 复现步骤
designWidth设置的是750，当我在css指定宽度为750px的时候经过转换变成了18.75rem，正常应该是16rem

### 期望结果
正常

### 实际结果
异常

### 环境信息
```
Taro v3.5.0-beta.7


  Taro CLI 3.5.0-beta.7 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1658392968771-0.7904370535767824/node
      Yarn: 1.22.18 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1658392968771-0.7904370535767824/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/components: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/mini-runner: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/plugin-framework-react: ^3.5.0-beta.7 => 3.5.0-theta.1 
      @tarojs/react: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/rn-runner: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/runtime: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/taro: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/taro-rn: 3.5.0-beta.7 => 3.5.0-beta.7 
      @tarojs/webpack-runner: 3.5.0-beta.7 => 3.5.0-beta.7 
      babel-preset-taro: 3.5.0-beta.7 => 3.5.0-beta.7 
      eslint-config-taro: 3.5.0-beta.7 => 3.5.0-beta.7 
      expo: ~45.0.6 => 45.0.6 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.68.2 => 0.68.2 
```

**Comment by ZakaryCode** [comment]
3.5 中不再以 640 为基准计算尺寸，而是会使用用户配置的 deviceRatio 计算

> 这是一个 breaking，但是可以通过配置 h5 默认的 designWidth: 640 和旧版本计算值对齐，另外需要更新 index.html 模板文件，可以参考初始项目

**Comment by ShaoGongBra** [comment]
有没有相关的文档介绍怎么用的，现在我的配置是这样的
```javascript
// 设计稿尺寸
  designWidth: 750,
  // 设计稿尺寸换算规则
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2
  },
```

**Comment by makeng** [comment]
> > 有没有相关的文档介绍怎么用的，现在我的配置是这样的
> > ```js
> > // 设计稿尺寸
> >   designWidth: 750,
> >   // 设计稿尺寸换算规则
> >   deviceRatio: {
> >     640: 2.34 / 2,
> >     750: 1,
> >     828: 1.81 / 2
> >   },
> > ```
> 
> 旧版本的不会接受传入的 designWidth，默认是 640，所以这样写就会和以前一样。
> 
> ```js
> // 设计稿尺寸
>   designWidth: process.env.TARO_ENV === 'h5' ? 640 : 750,
>   // 设计稿尺寸换算规则
>   deviceRatio: {
>     640: 2.34 / 2,
>     750: 1,
>     828: 1.81 / 2
>   },
> ```

这些都不改。index.html 分辨率计算替换成：<script><%= htmlWebpackPlugin.options.script %></script>。
/config/index.js 的分辨率部分不改
