### ISSUE TITLE
Template `tmpl_0_View` not found.

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro#12090]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/ccqgithub/taro-bug-repo.git](https://github.com/ccqgithub/taro-bug-repo.git)
**小程序基础库: 2.12.3**
**使用框架: Vue 3**

### 复现步骤
使用vue3 setup导入组件
```vue
<script setup lang="ts">
import { View } from '@tarojs/components'
import './index.scss'
import Counter from '../../components/Counter.vue'
</script>

<template>
  <View class="index">
    <Counter />
  </View>
</template>
```

报错：
```
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_View` not found.
  83 | 
  84 | <template name="tmpl_0_container">
> 85 |   <template is="{{xs.a(0, i.nn, l)}}" data="{{i:i,cid:0,l:xs.f(l,i.nn)}}" />
     |                ^
  86 | </template>
  87 | 
  88 | <template name="tmpl_1_catch-view">
```

## 如果直接使用模版，element类型不正确，view被当成svg元素了

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1654761/180177991-f423f38d-2ed4-4b97-958b-52bdeed1a9de.png">

### 期望结果
1. setup模式，import的组件能在template中使用
2. 非setup模式，view元素类型提示正确

### 实际结果
报错

### 环境信息
```
Taro CLI 3.4.13 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.13 => 3.4.13 
      @tarojs/mini-runner: 3.4.13 => 3.4.13 
      @tarojs/runtime: 3.4.13 => 3.4.13 
      @tarojs/taro: 3.4.13 => 3.4.13 
      @tarojs/webpack-runner: 3.4.13 => 3.4.13 
      babel-preset-taro: 3.4.13 => 3.4.13 
      eslint-config-taro: 3.4.13 => 3.4.13 
```

**Comment by ccqgithub** [comment]
> @ccqgithub Vue 中 Taro 内置组件需要小写：`<view>`，Demo 对 `<View>` 的使用里是 Taro React 的用法，是不对的。

vue3 setup 是可以用`<View>`的，最后能支持这种写法哦：https://vuejs.org/api/sfc-script-setup.html#using-components

> 另外类型提示是怎么出现的？

直接用小写`<view>`就有这个类型提示，应`view`再vue本身的定义里是svg的子元素。

**Comment by qsjc** [comment]
未使用ts的demo没发现这个问题

**Comment by Chen-jj** [comment]
> vue3 setup 是可以用<View>的，以后基本上都是用这种写法，最好能支持这种写法哦：https://vuejs.org/api/sfc-script-setup.html#using-components

Vue 组件才可以大写，`<view>` 相当于 H5 的 `<div>`，属于原生标签是不可以的。

> 直接用小写<view>就有这个类型提示，因为view在vue本身的定义里是svg的子元素。除了<view>之外，小写的标签很多类型提示都不正确，比如<scroll-view>

感觉是不是装了什么 VSCode 插件后提供的类型提示，你可以点进去类型跟踪是哪个文件导出的类型。目测是一个全局类型，那么你可以通过 TS 的模块补全去修改这个全局类型来解决。

**Comment by ccqgithub** [comment]
> @ccqgithub
> 
> > vue3 setup 是可以用的，以后基本上都是用这种写法，最好能支持这种写法哦：https://vuejs.org/api/sfc-script-setup.html#using-components
> 
> Vue 组件才可以大写，`<view>` 相当于 H5 的 `<div>`，属于原生标签是不可以的。
> 
> > 直接用小写就有这个类型提示，因为view在vue本身的定义里是svg的子元素。除了之外，小写的标签很多类型提示都不正确，比如
> 
> 感觉是不是装了什么 VSCode 插件后提供的类型提示，你可以点进去类型跟踪是哪个文件导出的类型。目测是一个全局类型，那么你可以通过 TS 的模块补全去修改这个全局类型来解决。

这是vue 的类型提示，原因是vue是针对web标准开发的，所以它内置的类型都是正当html标签的。当小程序的标签跟html的标签重叠但是功能不一样时，就会有问题。

**Comment by Richard-Choooou** [comment]
遇到一样的问题，很糟心

**Comment by yijinc** [comment]
遇到类似错误，我是

```vue
<template>
  <Navbar hideBack />
  <view :class="styles.container">
    <text>{{ greeting }}</text>
    <Button type="primary" >nutui</Button>
  </view>
</template>

<script lang="ts" setup>
import Navbar from '@/components/navbar';
import { Button } from "@nutui/nutui-taro";
import styles from './styles.scss';

const greeting = 'Hello world';

</script>


```

button 渲染不出来 

```
[WXML Runtime warning] ./base.wxml
Template `tmpl_0_Button` not found.
<template name="tmpl_1_container">

```

**Comment by Chen-jj** [comment]
在开启了 Volar 等开发者工具插件后，Vue SFC template 能够得到类型提示。原问题修改全局的 `IntrinsicElements` 可以解决， @ZakaryCode 有空可以看看

```ts
import {
  ViewProps
} from '@tarojs/components'

declare global {
  namespace JSX {
    interface IntrinsicElements {
      // allow arbitrary elements
      // @ts-ignore suppress ts:2374 = Duplicate string index signature.
      view: ViewProps
    }
  }
}
```

**Comment by loonyzhang** [comment]
@ZakaryCode 解决了？ 我这边 windows 3.5.4版本还是有这个问题

**Comment by ZakaryCode** [comment]
> @ZakaryCode 解决了？ 我这边 windows 3.5.4版本还是有这个问题

PR 还没有合入，等下一个版本咯

**Comment by lihuangshuaige** [comment]
看了半天 没看懂咋解决啊
