### ISSUE TITLE
@tarojs/mini-runner 没有更新到3.4.14

### ISSUE THREAD

**Issue by konka-king** [NervJS/taro#12097]
### 相关平台
微信小程序

**小程序基础库: 2.24.5**
**使用框架: React**

### 复现步骤
https://www.npmjs.com/package/@tarojs/mini-runner

npm 上最新版本还是3.4.13

### 期望结果
@tarojs/mini-runner 更新到3.4.14

### 实际结果
@tarojs/mini-runner 没有更新到3.4.14

### 环境信息
```
  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - D:\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\08143\AppData\Roaming\npm\yarn.CMD
      npm: 8.9.0 - D:\nodejs\npm.CMD
```

**Comment by konka-king** [comment]
### 相关平台
微信小程序


**小程序基础库: 2.24.5**
**使用框架: React**

### 复现步骤
https://www.npmjs.com/package/@tarojs/mini-runner

npm 上最新版本还是3.4.13

### 期望结果
@tarojs/mini-runner 更新到3.4.14

### 实际结果
@tarojs/mini-runner 没有更新到3.4.14

### 环境信息
```
  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - D:\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\08143\AppData\Roaming\npm\yarn.CMD
      npm: 8.9.0 - D:\nodejs\npm.CMD
```

**Comment by fantasyado** [comment]
facing same issue.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tarojs/mini-runner@3.4.14.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'bg-mp'
npm ERR! notarget

**Comment by Chen-jj** [comment]
感谢反馈~已补发
