### ISSUE TITLE
'react-dom' does not contain an export named 'hydrate'

### ISSUE THREAD

**Issue by wakeupSu** [NervJS/taro#12095]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/wakeupSu/taro-mp/tree/master](https://github.com/wakeupSu/taro-mp/tree/master)
**小程序基础库: 2.25.0**
**使用框架: React**

### 复现步骤
```
npm  i
npm run dev:weapp
```

### 期望结果
正常显示react-native-web的组件

### 实际结果
无法显示react-native-web的组件

### 环境信息
```
👽 Taro v3.4.13


  Taro CLI 3.4.13 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/components: 3.4.13 => 3.4.13 
      @tarojs/mini-runner: 3.4.13 => 3.4.13 
      @tarojs/plugin-framework-react: 3.4.13 => 3.4.13 
      @tarojs/react: 3.4.13 => 3.4.13 
      @tarojs/runtime: 3.4.13 => 3.4.13 
      @tarojs/taro: 3.4.13 => 3.4.13 
      @tarojs/webpack-runner: 3.4.13 => 3.4.13 
      babel-preset-taro: 3.4.13 => 3.4.13 
      eslint-config-taro: 3.4.13 => 3.4.13 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.67.4 => 0.67.4 
```

---
### 补充信息
想基于原先的rn项目和组件库多端开发，所以在taro引入了react-native-web。配置完成后，如果编译的是h5，可以正常运行，rnweb的组件也正常使用，但是编译成微信小程序时，会报下面这错误，但是可以编译成功，小程序也可以正常运行，但是引入的rnweb组件不显示。微信开发者工具的调试器里看了下，是生成的class无效
⚠️  编译警告. 2022/7/22 下午2:59:38

./node_modules/react-native-web/dist/exports/render/index.js 10:0-19
" 'react-dom' does not contain an export named 'hydrate'.

**Comment by zhiqingchen** [comment]
用taro的webview组件

**Comment by wakeupSu** [comment]
> 用taro的webview组件

感谢回复。之前是希望可以直接兼容，小程序页面也可以用原先的样式，也可以少写个webview的通信，看来没办法了。
