### ISSUE TITLE
input支持禁止历史记录 autocomplete="off"

### ISSUE THREAD

**Issue by XuLessReigns** [NervJS/taro#12092]
### 这个特性解决了什么问题？
验证码比较慎重，留存在历史记录中有账户风险，建议隐藏或者可控制开关

### 这个 API 长什么样？
支持禁止或者开启历史记录autocomplete="off"、autocomplete="on"

**Comment by Chen-jj** [comment]
@XuLessReigns 哪个小程序呢？有兴趣也可以帮忙提一下 PR 的
