### ISSUE TITLE
引入Image或者其他组件的时候报错

### ISSUE THREAD

**Issue by yangfan0611** [NervJS/taro#12094]
### 相关平台
微信小程序

**小程序基础库: 2.25.1**
**使用框架: React**

### 复现步骤
根据官网搭建的开发环境，然后开发微信小程序，引入组件报错，重启后自动解决，修改了样式页面没有反应，需要在微信开发者工具重新进入才会显示

### 期望结果
能尽快有解决方案

### 实际结果
暂无

### 环境信息
```
Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@yangfan0611 关闭微信开发者工具的热更新选项

<img width="386" alt="image" src="https://user-images.githubusercontent.com/11807297/180391971-52510213-ff1b-491f-ae1b-96567844314e.png">
