### ISSUE TITLE
不支持手动引入国际化 vue-i18n?

### ISSUE THREAD

**Issue by 893949088** [NervJS/taro#12102]
### 这个特性解决了什么问题？
国际化

### 这个 API 长什么样？
无

**Comment by 893949088** [comment]
环境：
Taro 3.4.16
Vue3
UI   NutUI
Vue-i18n 9.1.10

在template中使用$t('')报错：
![image](https://user-images.githubusercontent.com/4034377/180676119-12b89e88-834c-4189-83c9-64c7d7fa20f4.png)

**Comment by Chen-jj** [comment]
@893949088 麻烦按问题反馈的 issue 模板新建一个 issue，并附上可复现代码的。

**Comment by fusiyanggg** [comment]
同样的问题。编译成h5没问题。编译成小程序端不行

**Comment by 893949088** [comment]
@Chen-jj @fusiyanggg 是的h5正常，微信小程序不行，可有解决办法？

**Comment by Chen-jj** [comment]
duplicate #12166
