### ISSUE TITLE
willMount 中用 Taro.navigateTo 了，后面的数据 还是加载了

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#1210]
**问题描述**
小程序要登录后才能使用，否则跳转到登录页面，api服务器那边也是，会验证用户是否登录，没登录会返回401，现在问题是在willMount中判断没登录，然后跳转了，不过，发现后面的请求还是发起了， 是因为Taro先render的问题么？现在有什么办法能像react router一样先拦截？

[或者可以直接贴源代码，能贴文字就不要截图]

```js
  componentWillMount() {
    if (this.state.logined) {
       Taro.navigateTo({ url: '/pages/login/index' })
   }
  }
```

**期望行为**
没登录下直接跳转，后面的api不请求

**报错信息**

**系统信息**

 - 操作系统: osx 10.14
 - Taro 版本 1.1.8
 - Node.js 版本 v10.13.0
 - 报错平台 weapp

**补充信息**
<img width="639" alt="wx20181122-155604 2x" src="https://user-images.githubusercontent.com/299532/48889018-749c9700-ee6f-11e8-8492-24d2a0a372b3.png">

**Comment by luckyadam** [comment]
用 `redirectTo` 吧

**Comment by dpyzo0o** [comment]
在 componentWillMount 里执行 redirectTo之后，componentDidMount 和 componentDidShow 还是会执行
