### ISSUE TITLE
this.selectComponent / Taro.getCurrentInstance().page.selectComponent无法获取到对象

### ISSUE THREAD

**Issue by 1814356580** [NervJS/taro#12106]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/1814356580/TaroToast](https://github.com/1814356580/TaroToast)
**小程序基础库: 2.25.1**
**使用框架: React**

### 复现步骤
从微信小程序转换为Taro项目，通过 npm run dev:h5/weapp ，再转换为H5或微信小程序时，微信小程序使用了自定义组件，再通过this.selectComponent('#id') 或 Taro.getCurrentInstance().page.selectComponent('#id') 获取此自定义组件时都无法获取到对象

### 期望结果
获取到对象

### 实际结果
this.selectComponent('#id')报警告（selectComponent 方法产生不到目标效果，请使用 React 的 ref 进行重构。）且返回null

Taro.getCurrentInstance().page.selectComponent('#id')报错（Object(...)(...).page.selectComponent is not a function）

### 环境信息
```
  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - E:\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - E:\nodejs\npm.CMD
```

**Comment by mac-boss** [comment]
怎么解决的？
