### ISSUE TITLE
taro脚手架模板没有@tarojs/cli依赖

### ISSUE THREAD

**Issue by Jcanno** [NervJS/taro#12100]
### 这个特性解决了什么问题？
目前的脚手架模板没有@tarojs/cli依赖，如果使用npx安装的脚手架项目，项目和全局环境缺少@tarojs/cli不能运行

### 这个 API 长什么样？
期望脚手架中加入@tarojs/cli作为项目依赖

**Comment by AdvancedCat** [comment]
听起来很有道理，开发者都默认安装全局taro，没考虑到”试用“的场景。

**Comment by Chen-jj** [comment]
Taro CLI 最好是项目本地装的，这样好管理些。可以给模板的 devDependencies 都补一下

**Comment by AdvancedCat** [comment]
> Taro CLI 最好是项目本地装的，这样好管理些。可以给模板的 devDependencies 都补一下

正有此意
