### ISSUE TITLE
开启optimizeMainPackage.enable打包后，上传时提示存在es6 代码，需要转es5，开启后导致主包变大超限

### ISSUE THREAD

**Issue by CristalFJJ** [NervJS/taro#12109]
### 相关平台
微信小程序

**小程序基础库: 2.25.1**
**使用框架: React**

### 复现步骤
1. 未开启时：本地主包1955K，上传预览主包2075K，超限，所以开启优化。
未开启体积图片：https://ibb.co/NxTh5Q1
2. 开启后：本地主包1678K，上传预览时却出现提示，存在es6 特性，需要开启转es5，开启上传主包大小，2420K。
开启后体积图片：https://ibb.co/ZLQJkd7
提示图片：https://ibb.co/mqrshBg
3. 仅开启后会出现提示，开启前后其余代码没有变更，仅添加打包配置optimizeMainPackage.enable

### 期望结果
optimizeMainPackage.enable开启后，上传时无需再转es5

### 实际结果
optimizeMainPackage.enable开启后，上传时提示存在es6 的特性，需要将代码编译成Es5，因此本地设置勾选了将JS编译成es5，结果体积超限了。

### 环境信息
```
Taro CLI 3.4.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - D:\npm_global\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
是哪个模块存在 es6 语法？

按道理 `optimizeMainPackage.enable` 只是修改 splitchunk 的配置，不影响 babel-loader 的转换

**Comment by CristalFJJ** [comment]
> 是哪个模块存在 es6 语法？
> 
> 按道理 `optimizeMainPackage.enable` 只是修改 splitchunk 的配置，不影响 babel-loader 的转换

嗯，是splitchunk提取后的问题，我这边手动提取公共的模块，也出现了一样的问题，代码如下：
`addChunkPages(pages,` pagesNames) {
      pagesNames.forEach(pagename => {
        if (/pkg1\//.test(pagename)) {
          pages.set(pagename, ['pkg1/pkg1Common']);
        }

        // if (/pkg2\//.test(pagename)) {
        //   pages.set(pagename, ['pkg2/pkg2Common']);
        // }
      });
    },`
    `cacheGroups: {
              pkg1Common: {
                name: 'pkg1/pkg1Common',
                minChunks: 2,
                test: (module, chunks) => {
                  const isNoOnlyRequired = chunks.find(chunk => !/\bpkg1\b/.test(chunk.name));
                  return !isNoOnlyRequired;
                },
                priority: 200,
              },
              // pkg2Common: {
              //   name: 'pkg2/pkg2Common',
              //   minChunks: 2,
              //   test: (module, chunks) => {
              //     const isNoOnlyRequired = chunks.find(chunk => {
              //       return !/\bpkg2\b/.test(chunk.name);
              //     });
              //     return !isNoOnlyRequired;
              //   },
              //   priority: 200,
              // },
            }`
          
          发现问题：当注释提取pkg2公共模块时，打包上传不会出现转es5提示。但当pkg2也提取公共模块时，就会出现，但是查看pkg2提取的pkg2Common.js，发现也是babel处理过的es5代码，没有es6语法。就有点奇怪。

**Comment by CristalFJJ** [comment]
> > 是哪个模块存在 es6 语法？
> > 按道理 `optimizeMainPackage.enable` 只是修改 splitchunk 的配置，不影响 babel-loader 的转换
> 
> 嗯，是splitchunk提取后的问题，我这边手动提取公共的模块，也出现了一样的问题，代码如下：
> 
> ```
> addChunkPages(pages, pagesNames) {
>   pagesNames.forEach(pagename => {
>     if (/pkg1\//.test(pagename)) {
>       pages.set(pagename, ['pkg1/pkg1Common']);
>     }
> 
>     // if (/pkg2\//.test(pagename)) {
>     //   pages.set(pagename, ['pkg2/pkg2Common']);
>     // }
>   });
> },
> cacheGroups: {
>   pkg1Common: {
>     name: 'pkg1/pkg1Common',
>     minChunks: 2,
>     test: (module, chunks) => {
>       const isNoOnlyRequired = chunks.find(chunk => !/\bpkg1\b/.test(chunk.name));
>       return !isNoOnlyRequired;
>     },
>     priority: 200,
>   },
>   // pkg2Common: {
>   //   name: 'pkg2/pkg2Common',
>   //   minChunks: 2,
>   //   test: (module, chunks) => {
>   //     const isNoOnlyRequired = chunks.find(chunk => {
>   //       return !/\bpkg2\b/.test(chunk.name);
>   //     });
>   //     return !isNoOnlyRequired;
>   //   },
>   //   priority: 200,
>   // }
> }
> ```
> 
> 发现问题：当注释提取pkg2公共模块时，打包上传不会出现转es5提示。但当pkg2也提取公共模块时，就会出现，但是查看pkg2提取的pkg2Common.js，发现也是babel处理过的es5代码，没有es6语法。就有点奇怪。

奇怪点是：为啥提取pkg2才有问题，不提取又没事，是不是提取后出现一些了一些当前没有编译到的新特性语法，需要polyfill？
因此修改了babel配置，添加useBuiltIns，如下：
```
presets: [
    ['taro', {
      framework: 'react',
      ts: true,
      useBuiltIns: 'usage', // 添加
    }],
  ]
```
添加后，上传时不会出现转es5提示，但运行出错了，会提示：
```
app.js错误:
 TypeError: Can't call method on undefined
```

**Comment by CristalFJJ** [comment]
奇怪点是：为啥提取pkg2才有问题，不提取又没事，是不是提取后出现一些了一些当前没有编译到的新特性语法，需要polyfill？
因此修改了babel配置，添加useBuiltIns，如下：

presets: [
    ['taro', {
      framework: 'react',
      ts: true,
      useBuiltIns: 'usage', // 添加
    }],
  ]
添加后，上传时不会出现转es5提示，但运行出错了，会提示：

app.js错误:
 TypeError: Can't call method on undefined
