### ISSUE TITLE
能不能提供 react 18 版本的模板库（demo）？

### ISSUE THREAD

**Issue by yirenkeji555** [NervJS/taro#12101]
### 这个特性解决了什么问题？
根据 https://github.com/NervJS/taro/discussions/11610 这个discussions 步骤发现有报错。
最好能提供 node版本号

### 这个 API 长什么样？
希望能提供demo

**Comment by Chen-jj** [comment]
正式版发布前会把 3.5 CLI 创建的 react 模板都改为 18 的

**Comment by yirenkeji555** [comment]
你好，这个3.5 正式发布时间节点大概是在什么时候？

**Comment by Chen-jj** [comment]
@yirenkeji555 我看现在 3.5 beta CLI 创建的项目，模板源选择 Github，就是 React18 的了。

**Comment by ZakaryCode** [comment]
3.5.0 published 🎉
