### ISSUE TITLE
如何优化生成的匿名变量长度

### ISSUE THREAD

**Issue by notbucai** [NervJS/taro#12105]
### 这个特性解决了什么问题？
目前主包体积过大，能优化的地方基本都优化了，在过程中发现生成的匿名变量过长，一定程度下会影响体积。
生成的变量：anonymousState__temp[0-9] 
需求：能否自定义生成 or 变短一点

### 这个 API 长什么样？
可以编译过程中配置？

**Comment by Chen-jj** [comment]
Taro 1,2?

**Comment by notbucai** [comment]
> Taro 1,2?

2.2.13

**Comment by Chen-jj** [comment]
Taro 1，2 基本不维护了，可以找到对应位置进行修改，然后 PR 的
