### ISSUE TITLE
Taro 3.5.0 编译 HTML 5 报错

### ISSUE THREAD

**Issue by TechQuery** [NervJS/taro#12138]
## 相关平台

H5

## 复现仓库

idea2app/Taro-Vant-MobX-ts#3

- **浏览器版本: Chrome 103**
- **使用框架: React**

## 复现步骤

先执行命令：

```shell
pnpx @tarojs/cli init taro-test
```

再在菜单中选择：
1. PReact
2. TypeScript
3. LESS
4. PNPM
5. webpack 5
6. GitHub
7. MobX

最后执行命令：

```shell
pnpm dev:h5
```

## 期望结果

HTML 5 构建、运行成功

## 实际结果

> X [ERROR] [plugin scanImports] Can't resolve '\Desktop\taro-test\src\app' in '.'
>
>    node_modules/.pnpm/enhanced-resolve@5.10.0/node_modules/enhanced-resolve/lib/Resolver.js:309:17:
>      309 │       const error = new Error("Can't "   message);
>
> This error came from the "onResolve" callback registered here:
> 
> node_modules/.pnpm/esbuild@0.14.50/node_modules/esbuild/lib/main.js:846:22:
>      846 │         let promise = setup({
>
> <e> [webpack-dev-middleware] Error: No dependency factory available for this dependency type: EntryDependency

## 环境信息

```text
Taro CLI 3.5.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
```

---

## 补充信息

Taro 3.5 正式上线后第一时间升级脚手架，但 HTML 5 端构建出错、微信小程序正常。于是从 CLI 创建全新项目，但错误依旧，遂排除项目依赖问题。

还有两个调试问题：
1. https://issue.taro.zone/ 目前无法选择 Taro 3.4+
2. `taro info` 命令没显示 PNPM 信息

**Comment by yirenkeji555** [comment]
同样的问题。
<img width="958" alt="image" src="https://user-images.githubusercontent.com/48214423/181410776-84ce8f93-9c4c-459c-a888-ce7103f36492.png">

**Comment by yirenkeji555** [comment]
npm run dev:weapp 是ok的，但是npm run dev:h5 不行

**Comment by kala888** [comment]
同样问题

**Comment by pfsj-xk** [comment]
蹬一个解决方案

**Comment by yirenkeji555** [comment]
然后解决了吗？

**Comment by ZakaryCode** [comment]
1. preact 仅支持 `"@prefresh/webpack": "~3.2.3"`；
2. 特性 prebundle 在 h5 中暂不支持 `"publicPath": "."`，可以改为 "/" 或关闭该特性。

**Comment by ZakaryCode** [comment]
需要支持高版本 `@prefresh/webpack` @ZakaryCode

**Comment by TechQuery** [comment]
> 1. preact 仅支持 `"@prefresh/webpack": "~3.2.3"`；
> 2. 特性 prebundle 在 h5 中暂不支持 `"publicPath": "."`，可以改为 "/" 或关闭该特性。

@ZakaryCode 按楼主帖中所述选项重新创建新项目，在 3.5.1 下好了，但老脚手架升级后且遵照上述两点操作，又出现新错误：

```text
ERROR in app
Module not found: Error: Can't resolve 'D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��' in 'D:\Work\idea2app\Taro-Vant-MobX
-ts'
resolve 'D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��' in 'D:\Work\idea2app\Taro-Vant-MobX-ts'
  using description file: D:\Work\idea2app\Taro-Vant-MobX-ts\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: D:\Work\idea2app\Taro-Vant-MobX-ts\package.json (relative path: ./src/appЋ��)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ�� doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.tsx doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.mjs doesn't exist
      .vue
        Field 'browser' doesn't contain a valid alias configuration
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.vue doesn't exist
      as directory
        D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ�� doesn't exist
```

**Comment by ZakaryCode** [comment]
> > 1. preact 仅支持 `"@prefresh/webpack": "~3.2.3"`；
> > 2. 特性 prebundle 在 h5 中暂不支持 `"publicPath": "."`，可以改为 "/" 或关闭该特性。
> 
> @ZakaryCode 按楼主帖中所述选项重新创建新项目，在 3.5.1 下好了，但[老脚手架升级后](https://github.com/idea2app/Taro-Vant-MobX-ts/pull/3/commits/b27222eb14f27acf86ca5bf3209272d14ba19173)且遵照上述两点操作，又出现新错误：
> 
> ```
> ERROR in app
> Module not found: Error: Can't resolve 'D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��' in 'D:\Work\idea2app\Taro-Vant-MobX
> -ts'
> resolve 'D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��' in 'D:\Work\idea2app\Taro-Vant-MobX-ts'
>   using description file: D:\Work\idea2app\Taro-Vant-MobX-ts\package.json (relative path: .)
>     Field 'browser' doesn't contain a valid alias configuration
>     using description file: D:\Work\idea2app\Taro-Vant-MobX-ts\package.json (relative path: ./src/appЋ��)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ�� doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.js doesn't exist
>       .jsx
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.jsx doesn't exist
>       .ts
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.ts doesn't exist
>       .tsx
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.tsx doesn't exist
>       .mjs
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.mjs doesn't exist
>       .vue
>         Field 'browser' doesn't contain a valid alias configuration
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ��.vue doesn't exist
>       as directory
>         D:\Work\idea2app\Taro-Vant-MobX-ts\src\appЋ�� doesn't exist
> ```

依赖源问题，可删除依赖、lock 文件后换源重试

**Comment by TechQuery** [comment]
@ZakaryCode 删干净了再装，webpack 倒是显示成功了，但浏览器运行时挂了，全白屏：

```text
Uncaught SyntaxError: Unexpected token '<' (at runtime.js:1:1)
Uncaught SyntaxError: Unexpected token '<' (at taro.js:1:1)
Uncaught SyntaxError: Unexpected token '<' (at app.js:1:1)
```

**Comment by ZakaryCode** [comment]
> @ZakaryCode 删干净了再装，webpack 倒是显示成功了，但浏览器运行时挂了，全白屏：
> 
> ```
> Uncaught SyntaxError: Unexpected token '<' (at runtime.js:1:1)
> Uncaught SyntaxError: Unexpected token '<' (at taro.js:1:1)
> Uncaught SyntaxError: Unexpected token '<' (at app.js:1:1)
> ```
> 
> [idea2app/Taro-Vant-MobX-ts@3b7e382](https://github.com/idea2app/Taro-Vant-MobX-ts/commit/3b7e382818ffbbb23be131d13c5662a8521dabec)

未能复现，看起来是代理问题，可以检查一下 cli 版本是否一致

**Comment by TechQuery** [comment]
@ZakaryCode CLI 是装在项目本地的，电脑全局现在已经没有了。你把这个 PR 最新代码拉下来试试呢，我是 Windows 10。

**Comment by ZakaryCode** [comment]
> @ZakaryCode CLI 是装在项目本地的，版本也是一致的，电脑全局现在已经没有了。
> 
> 你把这个 PR 最新代码拉下来试试呢，我是 Windows 10。

还是依赖版本的问题，确定下你的依赖源

**Comment by TechQuery** [comment]
> > @ZakaryCode CLI 是装在项目本地的，版本也是一致的，电脑全局现在已经没有了。
> > 你把这个 PR 最新代码拉下来试试呢，我是 Windows 10。
> 
> 还是依赖版本的问题，确定下你的依赖源

完全是 NPM 官方源，没用任何第三方镜像，你确认一下我的 lock 文件有没有 checksum 错误：
https://github.com/idea2app/Taro-Vant-MobX-ts/blob/3b7e382818ffbbb23be131d13c5662a8521dabec/pnpm-lock.yaml

**Comment by TechQuery** [comment]
@ZakaryCode 升级到 3.5.2 后，`publicPath: '.'` 依然白屏，是因为开发服务器无法找到 JS 文件而默认输出 `index.html` 的内容引起语法错误：

![image](https://user-images.githubusercontent.com/19969570/183102814-a9f2f944-d0c4-4ae5-9046-18eb195d0f6d.png)

若该 bug 无法解决，所有依赖 GitHub pages 这样大多有二级目录的静态网站服务会挂掉……

**Comment by TechQuery** [comment]
@ZakaryCode [升级到 `3.5.4`](https://github.com/idea2app/Taro-Vant-MobX-ts/pull/4) 后上述 HTML 5 相对路径问题依旧……

**Comment by TechQuery** [comment]
@NervJS/taro [升级到 `3.5.5`](https://github.com/idea2app/Taro-Vant-MobX-ts/pull/4) 后，HTML 5 用相对路径 `.` 构建**生产环境**修复正常了，**开发环境**又挂了……

![image](https://user-images.githubusercontent.com/19969570/188888219-2ae9de02-cd30-4c07-b6ee-d8157b476299.png)

**Comment by Howie126313** [comment]
大佬们~这个问题。。。最后有解决方案么

**Comment by TechQuery** [comment]
> @NervJS/taro [升级到 `3.5.5`](https://github.com/idea2app/Taro-Vant-MobX-ts/pull/4) 后，HTML 5 用相对路径 `.` 构建**生产环境**修复正常了，**开发环境**用默认的 `/` 竟然挂了……
> 
> ![image](https://user-images.githubusercontent.com/19969570/188888219-2ae9de02-cd30-4c07-b6ee-d8157b476299.png)

升级到最新 `3.5.10`，并不要在开发环境启用 `publicPath: '.'`，上述问题即可解决：https://github.com/idea2app/Taro-Vant-MobX-ts/pull/4/commits/4243f38143097debe79de4b6c262bc7dde170811
