### ISSUE TITLE
导入echarts包后提示[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB" #

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro#1213]
**问题描述**
导入echarts包后提示[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB" 

![image](https://user-images.githubusercontent.com/15973148/48893994-9c462c00-ee7c-11e8-9e5f-deba1b516b7c.png)
![image](https://user-images.githubusercontent.com/15973148/48894001-9fd9b300-ee7c-11e8-8dc8-5d395058049f.png)

**期望行为**
编译成功
**系统信息**

 - 操作系统: [MacOs]
 - Taro 版本 [1.19]
 - Node.js 版本 [v8.0.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#weappcompileexclude

**Comment by darkfiredarkhalo** [comment]
如果参与编译的包是node_modules目录下的怎么忽略,我们使用了ethers.js,也出现了这个问题
