### ISSUE TITLE
创建的React+TS+Sass+Webpack5+Mobx模板项目无法运行

### ISSUE THREAD

**Issue by NICEXAI** [NervJS/taro#12137]
### 相关平台
H5

**浏览器版本: chrome 103.0.5060.134**
**使用框架: React**

### 复现步骤
1、执行taro init demo命令初始化项目
2、选择 React 框架
3、选择使用 TypeScript
4、选择使用Sass预处理器
5、选择Webpack5
6、选择包管理工具yarn
7、选择模板源Github
8、选择模板mobx
9、等待依赖安装完毕后执行 npm run dev:h5运行初始项目

### 期望结果
正常运行

### 实际结果
✖ Errors:

resolve 'D:\WorkCode\other\online-question-bank\src\appЃļ?' in 'D:\WorkCode\other\online-question-bank'
  using description file: D:\WorkCode\other\online-question-bank\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    No description file found in D:\WorkCode\other or above
    no extension
      Field 'browser' doesn't contain a valid alias configuration

### 环境信息
```
  Taro CLI 3.5.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\15005\AppData\Roaming\npm\yarn.CMD
      npm: 8.4.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by SeeSaySee** [comment]
Same to default template.

**Comment by ZakaryCode** [comment]
并为在指定步骤中复现相关问题（包括 mobx、默认模板），看问题信息猜测是在 window10 上部分字符导致的问题，晚点找台验证下。

**Comment by ZakaryCode** [comment]
未能在 window10 复现，在其他类似 issue 中通过 demo 的 lock 文件复现该问题，应该是安装源导致的该错误，可以尝试删掉 node_modules 和 lock 文件并换源重装后试试，是否能避开错误。

**Comment by NICEXAI** [comment]
> 未能在 window10 复现，在其他类似 issue 中通过 demo 的 lock 文件复现该问题，应该是安装源导致的该错误，可以尝试删掉 node_modules 和 lock 文件并换源重装后试试，是否能避开错误。

好的，我尝试一下，非常感谢
