### ISSUE TITLE
3.5.0nutui-taro 无法导入icon

### ISSUE THREAD

**Issue by shijunti19** [NervJS/taro#12148]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: Vue 3**

### 复现步骤
import { createApp } from "vue";
import { Button, Toast, Icon } from "@nutui/nutui-taro";

import "./app.scss";
console.log(process.env.TARO_ENV);
const App = createApp({
  onShow(options) {},
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
});
App.use(Button).use(Toast).use(Icon);

export default App;

### 期望结果
正常编译

### 实际结果
ERROR in ./node_modules/.pnpm/@nutui nutui-taro@3.1.22_vue@3.2.37/node_modules/@nutui/nutui-taro/dist/packages/icon/index.scss (
./node_modules/.pnpm/css-loader@6.5.1_webpack@5.69.0/node_modules/css-loader/dist/cjs.js??clonedRuleSet-4.use[0]!./node_modules/
.pnpm/postcss-loader@6.2.1_postcss@8.3.5 webpack@5.69.0/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-5.use[0]!./node_m
odules/.pnpm/resolve-url-loader@4.0.0/node_modules/resolve-url-loader/index.js!./node_modules/.pnpm/sass-loader@12.4.0_sass@1.50
.0 webpack@5.69.0/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-7.use[1]!./node_modules/.pnpm/@nutui nutui-taro@3.1.22_vue
@3.2.37/node_modules/@nutui/nutui-taro/dist/packages/icon/index.scss) 6:36-93
Module not found: Error: Can't resolve 'iconfont.woff?t=1654497552263' in 'F:\web\xiaolu\nutui\a031\node_modules\.pnpm\@nutui nu
tui-taro@3.1.22_vue@3.2.37\node_modules\@nutui\nutui-taro\dist\packages\icon'
 @ ./node_modules/.pnpm/@nutui nutui-taro@3.1.22_vue@3.2.37/node_modules/@nutui/nutui-taro/dist/packages/icon/index.scss 2:26-51
4 53:4-74:5 56:18-506
 @ ./src/app.ts 5:0-57
 @ ./src/app.boot.js 3:0-30 50:19-28 51:25-34
 @ ./src/app.config.ts 1:0-20

### 环境信息
```
👽 Taro v3.5.0


  Taro CLI 3.5.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - E:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - E:\Program Files\nodejs\yarn.CMD
      npm: 8.15.0 - E:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
icon组件无法导入，会提示iconfont.ttf引用不正确

**Comment by ZakaryCode** [comment]
下一个版本默认支持，当前可以通过配置 `h5.postcss.url.enable: true` 跳过该问题

**Comment by chengzichen** [comment]
使用了taro3.5.1问题还是没有解决

**Comment by Drjingfubo** [comment]
升级到taro3.5.4即可

**Comment by richard1015** [comment]
通过配置 h5.postcss.url.enable: true 跳过该问题
```  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    esnextModules: ['nutui-taro'],
    postcss: {
      url:{
        enable:true
      },
```
