### ISSUE TITLE
Taro3.5.0向导创建的react redux webpack5无法正常编译

### ISSUE THREAD

**Issue by chenxinbin** [NervJS/taro#12143]
### 相关平台
支付宝小程序

### 复现仓库
[https://gitee.com/o2team/taro-project-templates.git#v3.5](https://gitee.com/o2team/taro-project-templates.git#v3.5)
**小程序基础库: 0.0.0**
**使用框架: React**

### 复现步骤
👽 Taro v3.5.0

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 dev
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Gitee（最快）
✔ 拉取远程模板仓库成功！
? 请选择模板 redux

✔ 创建项目: devtest

.......

npx @tarojs/cli build --type alipay --watch
👽 Taro v3.5.0

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ NODE_ENV=production taro build --type alipay --watch
2. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。

Prebundle dependencies: 
     @tarojs/plugin-framework-react/dist/runtime
     @tarojs/runtime
     @tarojs/shared
     @tarojs/taro
     react
     react-dom
     react-redux
     react/jsx-runtime
     redux
     redux-logger
     redux-thunk

[1]    28332 segmentation fault  npx @tarojs/cli build --type alipay --watch

### 期望结果
正常编译

### 实际结果
编译失败

### 环境信息
```
npx @tarojs/cli info
👽 Taro v3.5.0


  Taro CLI 3.5.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.0 => 3.5.0 
      @tarojs/components: 3.5.0 => 3.5.0 
      @tarojs/helper: 3.5.0 => 3.5.0 
      @tarojs/plugin-framework-react: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-alipay: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-jd: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-qq: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-swan: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-tt: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-weapp: 3.5.0 => 3.5.0 
      @tarojs/react: 3.5.0 => 3.5.0 
      @tarojs/router: 3.5.0 => 3.5.0 
      @tarojs/runtime: 3.5.0 => 3.5.0 
      @tarojs/shared: 3.5.0 => 3.5.0 
      @tarojs/taro: 3.5.0 => 3.5.0 
      @tarojs/taro-h5: 3.5.0 => 3.5.0 
      babel-preset-taro: 3.5.0 => 3.5.0 
      eslint-config-taro: 3.5.0 => 3.5.0 
      react: ^18.0.0 => 18.2.0 

```

**Comment by chenxinbin** [comment]
微信小程序正常编译，支付宝不行

**Comment by Chen-jj** [comment]
@chenxinbin 没有复现，请使用 **Github 模板源** 再试试。由于账户问题，Gitee 的模板还没更新，可能有关。

![image](https://user-images.githubusercontent.com/11807297/181443878-aac7d56e-995e-46dc-bf7b-73c7434d4821.png)

![image](https://user-images.githubusercontent.com/11807297/181443930-db8d5f81-c12b-4f2c-b7d4-6f01a63eda90.png)

**Comment by chenxinbin** [comment]
更改github源后，没有出现编译错误。
