### ISSUE TITLE
VirtualList 长列表引入项目报130错误

### ISSUE THREAD

**Issue by chenshuaifeng110** [NervJS/taro#12146]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/](https://github.com/)
**小程序基础库: 2.24.2**
**使用框架: React**

### 复现步骤
import React, { Component } from 'react'
import { View, Image, Text, Swiper, SwiperItem } from '@tarojs/components'
import VirtualList from '@tarojs/components/virtual-list'
function buildData (offset = 0) {
  return Array(100).fill(0).map((_, i) => i   offset);
}

const Row = React.memo(({ id, index, style, data }) => {
  return (
    <View id={id} className={index % 2 ? 'ListItemOdd' : 'ListItemEven'} style={style}>
      Row {index} : {data[index]}
    </View>
  );
})

class Index extends Component {
  state = {
    data: buildData(0),
  }

  render() {
    const { data } = this.state
    const dataLen = data.length
    return (
      <VirtualList
        height={500} /* 列表的高度 */
        width='100%' /* 列表的宽度 */
        itemData={data} /* 渲染列表的数据 */
        itemCount={dataLen} /*  渲染列表的长度 */
        itemSize={100} /* 列表单项的高度  */
      >
        {Row} /* 列表单项组件，这里只能传入一个组件 */
      </VirtualList>
    );
  }
}

export default  Index

### 期望结果
正常

### 实际结果
.._src_components.ts:467 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### 环境信息
```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\chenshuaifeng\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@chenshuaifeng110 配置 [debugReact](https://docs.taro.zone/docs/config-detail#minidebugreact) 看看具体报错内容然后定位一下，如果还有问题请提供完整可复现的 demo

**Comment by jackple** [comment]
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/6183232/189029859-b1148d12-37d0-4255-8916-c196caf995e5.png">
@Chen-jj
