### ISSUE TITLE
Taro3.5.0支付宝小程序模拟器正常，但真机预览，上传后体验版本均白屏

### ISSUE THREAD

**Issue by chenxinbin** [NervJS/taro#12156]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/chenxinbin/taro-project-templates.git](https://github.com/chenxinbin/taro-project-templates.git)
**小程序基础库: 0**
**使用框架: React**

### 复现步骤
使用taro自带向导初始化项目 
>taro init devtest
👽 Taro v3.5.0

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 devtest
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 redux

✔ 创建项目: devtest

npm run build:alipay        

> devtest@1.0.0 build:alipay
> taro build --type alipay

👽 Taro v3.5.0

Tips:
1. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。

✔ Webpack
  Compiled successfully in 2.28s

编译成功后，使用开发者工具真机调试，或者上传版本后扫码体验，都白屏。终端报错：
framework startup perf worker: framework bundle start: 1659077383099
framework startup perf worker: framework bundle start: 1659077383124
framework startup perf worker: biz bundle start: undefined
framework startup perf worker: biz bundle end: undefined
framework startup perf worker: first page start: 1659077384006
framework: App onLaunch
framework: page onLoad pages/index/index
Uncaught TypeError: Cannot read property 'mount' of undefined
    at mount (index.worker.js:121)
    at index.worker.js:121
    at index.worker.js:121
TypeError: Cannot read property 'mount' of undefined
    at mount (index.worker.js:121)
    at index.worker.js:121
    at index.worker.js:121
framework: page onShow pages/index/index
framework startup perf worker: first page end: 1659077384018
framework: getTrackerConfig {}
framework:pages/index/index: transfer costs 10ms, render costs 5ms.
framework: page onReady pages/index/index
framework: App onHide
framework: page onHide pages/index/index

### 期望结果
正常运行

### 实际结果
模拟器正常，只要上真机就白屏

### 环境信息
```
👽 Taro v3.5.0


  Taro CLI 3.5.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.0 => 3.5.0 
      @tarojs/components: 3.5.0 => 3.5.0 
      @tarojs/helper: 3.5.0 => 3.5.0 
      @tarojs/plugin-framework-react: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-alipay: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-jd: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-qq: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-swan: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-tt: 3.5.0 => 3.5.0 
      @tarojs/plugin-platform-weapp: 3.5.0 => 3.5.0 
      @tarojs/react: 3.5.0 => 3.5.0 
      @tarojs/router: 3.5.0 => 3.5.0 
      @tarojs/runtime: 3.5.0 => 3.5.0 
      @tarojs/shared: 3.5.0 => 3.5.0 
      @tarojs/taro: 3.5.0 => 3.5.0 
      @tarojs/taro-h5: 3.5.0 => 3.5.0 
      babel-preset-taro: 3.5.0 => 3.5.0 
      eslint-config-taro: 3.5.0 => 3.5.0 
      react: ^18.0.0 => 18.2.0 

```

**Comment by Chen-jj** [comment]
应该在这个 PR 里修复了，可以先使用 React17 绕过

**Comment by chenxinbin** [comment]
> 应该在这个 PR #12145 里修复了，可以先使用 React17 绕过

使用React17后，确实显示了，不过Image标签不能正常显示，使用开发工具的调试工具Elements查看，Image标签变成View了。
目前已经撤回3.4.14，一切正常。等过段时间再试试

**Comment by chenxinbin** [comment]
新版本3.5.1经核实，确认正常
