### ISSUE TITLE
独立分包后，跳转子包报错Component is not found in path "子包名xx/custom-wrapper"，(较少偶现)

### ISSUE THREAD

**Issue by follow-zy** [NervJS/taro#12159]
### 相关平台
微信小程序

**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
小程序进入子包页面，很少偶现以下报错信息，小程序页面代码并未使用custom-wrapper组件

### 期望结果
正常运行

### 实际结果
页面未使用custom-wrapper，控制台报以下错，**（非必现，在未知原因下较少次数偶现）**
1：Component is not found in path "子包名xx/custom-wrapper"
2：Component is not found in path "子包名xx/comp"
![87ea5709558ff60df70618facc58f2e](https://user-images.githubusercontent.com/39199805/181732456-685c5f36-20e2-434e-87c7-03e188f13678.png)

### 环境信息
```
 Taro CLI 3.4.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0
      Yarn: 1.22.18
      npm: 6.14.11
    npmPackages:
      "@tarojs/components": "3.3.19",
      "@tarojs/react": "3.3.19",
      "@tarojs/runtime": "3.3.19",
      "@tarojs/taro": "3.3.19",
      "react": "^17.0.0",
      "taro-ui": "^3.1.0-beta.0"
```

**Comment by nuintun** [comment]
同样问题

**Comment by Virgil-N** [comment]
一样问题，采用hook开发

**Comment by Chen-jj** [comment]
#12239
