### ISSUE TITLE
taro 3.5 使用 weui 问题

### ISSUE THREAD

**Issue by LiHaoGit** [NervJS/taro#12162]
### 这个特性解决了什么问题？
taro 3.5 
使用 React TypeScript 开发，如何使用 weui 组件。搜了好久都没找到使用方式
```
//app.config.ts
  useExtendedLib:{
    "weui": true
  }
```
```
//src\pages\index\index.config.ts
  "usingComponents": {
    "mp-icon": "weui-miniprogram/icon/icon"
  }
```

```
//src\pages\index\index.tsx
<mp-icon icon="add" color="black" size="{{25}}"></mp-icon>
```

如果尝试使用上述配置 首先  src\pages\index\index.tsx 会报类型错误`类型“JSX.IntrinsicElements”上不存在属性“mp-icon”`
然后执行`yarn run dev:weapp`的时候会报 `Component is not found in path "miniprogram_npm/weui-miniprogram/icon/icon" (using by "pages/index/index")`

### 这个 API 长什么样？
一个可以使用weui的实例

**Comment by smoothdvd** [comment]
```
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'mp-icon': {
        ...
      }
    }
  }
}
```
