### ISSUE TITLE
prebundle  模块开发模式（development）支持开启压缩

### ISSUE THREAD

**Issue by harwinvoid** [NervJS/taro#12160]
### 这个特性解决了什么问题？
prebundle 开发模式下体积比较大，导致体积过大，不能预览

### 这个 API 长什么样？
开放 prebundle  webpack 配置

**Comment by Chen-jj** [comment]
🤔关于这个问题是暴露预编译的 Webpack 比较好；还是跟随以往惯例，使用 `production` 环境变量时自动压缩比较好

**Comment by ZakaryCode** [comment]
> 🤔关于这个问题是暴露预编译的 Webpack 比较好；还是跟随以往惯例，使用 `production` 环境变量时自动压缩比较好

可以继承部分公共 webpack 配置，并根据环境变量自动启动压缩
