### ISSUE TITLE
tarojs cssModule 样式丢失

### ISSUE THREAD

**Issue by phillip111** [NervJS/taro#12167]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/phillipsky/err-demo.git](https://gitee.com/phillipsky/err-demo.git)
**小程序基础库: 2.23.0**
**使用框架: React**

### 复现步骤
1.参考demo中，index 与demo 页面文件与引用

### 期望结果
编译后，dist中pages/demo、pages/index 都有wxss文件

### 实际结果
pages/demo中无法正常生成wxss

### 环境信息
```
Taro CLI 3.2.0-canary.6 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.0.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 7.10.0 - /usr/local/bin/npm

```

**Comment by Chen-jj** [comment]
升级到最新版本再试试

**Comment by phillip111** [comment]
> 升级到最新版本再试试

当前demo 升级3.5.1，发现有其他报错，demo无法正常运行

**Comment by phillip111** [comment]
经过测试，忘记开启cssModule 配置了，demo中可以达到效果，css 会被收集到common.css 里
在主包内无法复现问题，问题会出现在分包里
已经完善更新了demo，麻烦重新查看拉取新代码

**Comment by Chen-jj** [comment]
@phillip111 分包里的也正常喔，公共组件的样式会被抽取到 sub-vendors.wxss，然后两个分包页面也有正确引用它：

![image](https://user-images.githubusercontent.com/11807297/183658632-aadd9caf-b272-4ae3-be11-458d1f07e000.png)

**Comment by phillip111** [comment]
> @phillip111 Taro 3.5.2 分包里的也正常喔，公共组件的样式会被抽取到 sub-vendors.wxss，然后两个分包页面也有正确引用它：
> 
> ![image](https://user-images.githubusercontent.com/11807297/183658632-aadd9caf-b272-4ae3-be11-458d1f07e000.png)

收到，我把 tarojs 版本升级到3.5.2 可以达到你截图的效果，谢谢。3.5.1 版本还是不行
