### ISSUE TITLE
npm run dev:h5 报错

### ISSUE THREAD

**Issue by wuse** [NervJS/taro#1216]
taro init myApp 的新项目 
npm run dev:h5 报以下错误
不过 npm run build:h5  可以打包成功
![mswm arztrvz mpv61u x](https://user-images.githubusercontent.com/13679397/48903167-b9d3bf80-ee95-11e8-9b3b-17313e2c9f6b.png)

**Comment by Littly** [comment]
不是taro的问题 https://github.com/angular/protractor/issues/2978
添加C:\Windows\System32\ 到环境变量PATH，重启电脑再试

**Comment by wuse** [comment]
thank you 
把 C:\Windows\System32 添加到系统环境变量后，重启电脑就好了
