### ISSUE TITLE
升级3.5.1 小程序编译报错

### ISSUE THREAD

**Issue by konka-king** [NervJS/taro#12171]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/konka-king/alipay-pickerview](https://github.com/konka-king/alipay-pickerview)
**小程序基础库: 2.24.5**
**使用框架: React**

### 复现步骤
升级3.5.1 ，运行 pnpm dev:weapp

### 期望结果
正常编译

### 实际结果
编译报错

### 环境信息
```
 Taro CLI 3.5.1 environment info:
   taro info 命令同样报错
```

**Comment by konka-king** [comment]
![image](https://user-images.githubusercontent.com/22173084/182087423-112fb462-23be-4e4f-8d80-812c60db08ca.png)
报错如图

**Comment by konka-king** [comment]
降级了一下taro版本 运行的taro info
```
  System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    npmPackages:
      @tarojs/components: 3.5.1 => 3.5.1 
      @tarojs/helper: ^3.5.1 => 3.5.1 
      @tarojs/plugin-framework-react: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-alipay: ^3.5.1 => 3.5.1 
      @tarojs/plugin-platform-jd: ^3.5.1 => 3.5.1 
      @tarojs/plugin-platform-qq: ^3.5.1 => 3.5.1 
      @tarojs/plugin-platform-swan: ^3.5.1 => 3.5.1 
      @tarojs/plugin-platform-tt: ^3.5.1 => 3.5.1 
      @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1 
      @tarojs/react: 3.5.1 => 3.5.1 
      @tarojs/router: ^3.5.1 => 3.5.1 
      @tarojs/runtime: 3.5.1 => 3.5.1 
      @tarojs/shared: ^3.5.1 => 3.5.1 
      @tarojs/taro: 3.5.1 => 3.5.1 
      @tarojs/taro-h5: ^3.5.1 => 3.5.1 
      babel-preset-taro: 3.5.1 => 3.5.1 
      eslint-config-taro: 3.5.1 => 3.5.1 
      react: ^18.2.0 => 18.2.0 
```

**Comment by lf7817** [comment]
同

**Comment by lf7817** [comment]
之前写的一个taro插件3.5.0之前都是正常的，升级后直接跳过了，也没报错，其他插件正常

**Comment by Chen-jj** [comment]
> 降级了一下taro版本 运行的taro info
> 
> ```
> Taro CLI 3.4.14 environment info:
>   System:
>       OS: macOS 12.5
>       Shell: 5.8.1 - /bin/zsh
>     Binaries:
>       Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
>       Yarn: 1.22.17 - ~/.yarn/bin/yarn
>       npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
>     npmPackages:
>       @tarojs/components: 3.5.1 => 3.5.1 
>       @tarojs/helper: ^3.5.1 => 3.5.1 
>       @tarojs/plugin-framework-react: 3.5.1 => 3.5.1 
>       @tarojs/plugin-platform-alipay: ^3.5.1 => 3.5.1 
>       @tarojs/plugin-platform-jd: ^3.5.1 => 3.5.1 
>       @tarojs/plugin-platform-qq: ^3.5.1 => 3.5.1 
>       @tarojs/plugin-platform-swan: ^3.5.1 => 3.5.1 
>       @tarojs/plugin-platform-tt: ^3.5.1 => 3.5.1 
>       @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1 
>       @tarojs/react: 3.5.1 => 3.5.1 
>       @tarojs/router: ^3.5.1 => 3.5.1 
>       @tarojs/runtime: 3.5.1 => 3.5.1 
>       @tarojs/shared: ^3.5.1 => 3.5.1 
>       @tarojs/taro: 3.5.1 => 3.5.1 
>       @tarojs/taro-h5: ^3.5.1 => 3.5.1 
>       babel-preset-taro: 3.5.1 => 3.5.1 
>       eslint-config-taro: 3.5.1 => 3.5.1 
>       react: ^18.2.0 => 18.2.0 
> ```

编译正常，没有复现，使用 nodejs 16 试试

![image](https://user-images.githubusercontent.com/11807297/182276693-01c20082-1aff-4187-8160-7de8053ade73.png)

<img width="415" alt="image" src="https://user-images.githubusercontent.com/11807297/182275990-53fc84bd-51ee-4550-a0f4-140a4a93b681.png">

**Comment by Chen-jj** [comment]
Taro 会使用 `@swc/register` 去加载 `@tarojs/cli/dist/presets/index.js`

![image](https://user-images.githubusercontent.com/11807297/182280095-fd0668a3-7916-4b07-b377-418bbfb8baeb.png)

![image](https://user-images.githubusercontent.com/11807297/182280201-025b9378-a85b-4bb0-96b2-e91c91ae5d8d.png)

报错出自 swc，也可以自行新建一个相同的 js 使用 @swc/register 加载看看有没问题

**Comment by konka-king** [comment]
> > 降级了一下taro版本 运行的taro info
> > ```
> > Taro CLI 3.4.14 environment info:
> >   System:
> >       OS: macOS 12.5
> >       Shell: 5.8.1 - /bin/zsh
> >     Binaries:
> >       Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
> >       Yarn: 1.22.17 - ~/.yarn/bin/yarn
> >       npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
> >     npmPackages:
> >       @tarojs/components: 3.5.1 => 3.5.1 
> >       @tarojs/helper: ^3.5.1 => 3.5.1 
> >       @tarojs/plugin-framework-react: 3.5.1 => 3.5.1 
> >       @tarojs/plugin-platform-alipay: ^3.5.1 => 3.5.1 
> >       @tarojs/plugin-platform-jd: ^3.5.1 => 3.5.1 
> >       @tarojs/plugin-platform-qq: ^3.5.1 => 3.5.1 
> >       @tarojs/plugin-platform-swan: ^3.5.1 => 3.5.1 
> >       @tarojs/plugin-platform-tt: ^3.5.1 => 3.5.1 
> >       @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1 
> >       @tarojs/react: 3.5.1 => 3.5.1 
> >       @tarojs/router: ^3.5.1 => 3.5.1 
> >       @tarojs/runtime: 3.5.1 => 3.5.1 
> >       @tarojs/shared: ^3.5.1 => 3.5.1 
> >       @tarojs/taro: 3.5.1 => 3.5.1 
> >       @tarojs/taro-h5: ^3.5.1 => 3.5.1 
> >       babel-preset-taro: 3.5.1 => 3.5.1 
> >       eslint-config-taro: 3.5.1 => 3.5.1 
> >       react: ^18.2.0 => 18.2.0 
> > ```
> 
> 编译正常，没有复现，使用 nodejs 16 试试
> 
> ![image](https://user-images.githubusercontent.com/11807297/182276693-01c20082-1aff-4187-8160-7de8053ade73.png)
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/11807297/182275990-53fc84bd-51ee-4550-a0f4-140a4a93b681.png">

感谢，我换到 node 18 可以编译了
