### ISSUE TITLE
taro-alipay 真机调试，带onClick回调的Text变成了image，Image标签变成了view标签

### ISSUE THREAD

**Issue by ZhuQinPeng** [NervJS/taro#12176]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/ZhuQinPeng/learn_taro_alipay.git](https://github.com/ZhuQinPeng/learn_taro_alipay.git)
**小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
无

### 期望结果
正常显示

### 实际结果
带onClick回调的Text变成了image标签导致文本不显示；Image标签变成了view标签导致图片不显示

### 环境信息
```
  Taro CLI 3.5.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
taro-3.5.0
手机系统 鸿蒙2.0.0

**Comment by Chen-jj** [comment]
@ZhuQinPeng Taro `3.5.2` 在模拟器和真机都没有复现喔，升级下试试

![image](https://user-images.githubusercontent.com/11807297/183553620-8bc794bf-d8cb-4669-a8ba-89d4013ddafe.png)

**Comment by liuliuna** [comment]
> @ZhuQinPeng Taro `3.5.2` 在模拟器和真机都没有复现喔，升级下试试
> 
> ![image](https://user-images.githubusercontent.com/11807297/183553620-8bc794bf-d8cb-4669-a8ba-89d4013ddafe.png)
【安卓】
![image](https://user-images.githubusercontent.com/110441812/185400435-b8ecf221-c820-4351-8bc1-89cabee89b8c.png)
【ios】
![image](https://user-images.githubusercontent.com/110441812/185400617-49e11ef2-1265-413c-9f91-ec4ae39aa062.png)
最新版我还是有这个问题 在真机调试时 安卓和ios对图片转换不一致
