### ISSUE TITLE
taro3.5.1 ts sass webpack5 RN初始化项目yarn run dev:rn扫码报错

### ISSUE THREAD

**Issue by Aliom252181** [NervJS/taro#12185]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
yarn
yarn run dev:rn

### 期望结果
可以正常展示

### 实际结果
could not get BatchedBridge,make sure your bundle is packaged correctly

### 环境信息
```
 Taro CLI 3.5.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.7.0 - D:\NODE\node.EXE
      Yarn: 1.22.19 - C:\Users\liuyusen\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.1 - D:\NODE\npm.CMD
```

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/issues/12174

重复
