### ISSUE TITLE
H5打包发布后报错 lib_library is not defined

### ISSUE THREAD

**Issue by CozySnail** [NervJS/taro#1218]
**问题描述**
H5打包发布后报错 lib_library is not defined, 项目无法运行, 所有静态资源network中显示正常

**复现步骤**
[复现问题的步骤]
1. npm run build:h5
2. 将dist完整目录上传至服务器
3. 打开项目地址(url)

**期望行为**
H5项目可以正常打包发布

**报错信息**

    Uncaught ReferenceError: lib_library is not defined

    (说明: 所有静态资源文件加载正常)

![image](https://user-images.githubusercontent.com/18653890/48907203-ba725300-eea1-11e8-9471-2f5aaba96890.png)

**系统信息**

 - 操作系统: [MacOS 10.14]
 - Taro 版本 [e.g. v.1.1.9]
 - Node.js 版本 [e.g. v10.10.0]
 - 报错平台 [h5]

**补充信息**
通过官方群众开发的同学帮助解决问题, 导致此问题的原因可能是由于框架的问题导致的,
最后开发的同学给出了一个临时的解决方案, 方案如下:
```
h5: {
        publicPath: '/front/',
        staticDirectory: 'static',
        **_enableDll: false,   // 临时解决H5打包发布报错 lib_library is not defined 错误_**
        module: {
            postcss: {
                autoprefixer: {
                    enable: true
                }
            }
        }
    }

```

**Comment by CozySnail** [comment]
不知道这个问题是否已经解决了

**Comment by Littly** [comment]
更新到最新版试试看
