### ISSUE TITLE
Could not get BatchedBridge, make sure you bundle is packaged correctly

### ISSUE THREAD

**Issue by luchanan** [NervJS/taro#12181]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
按流程选择模板，没有加任何东西
1. taro init 后 选择 react-native
2.  yarn upgradePeerdeps
3.  yarn start

### 期望结果
可以正确运行

### 实际结果
Could not get BatchedBridge, make sure you bundle is packaged correctly

![微信图片_20220802101332](https://user-images.githubusercontent.com/10396123/182282824-53403c90-2182-4757-89a2-2092ff4f2b35.jpg)

### 环境信息
```
👽 Taro v3.5.1


  Taro CLI 3.5.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD


taro-playground   app-debug.apk  1.61
```

---
### 补充信息
搭建了一两天，还是没有解决，请求帮助

我尝试用了yarn build:rn --platform android 再运行 yarn start还是不行

**Comment by luchanan** [comment]
使用的是集成模式

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/issues/12174

重复
