### ISSUE TITLE
兼容 webpack 5.69.0 以上版本

### ISSUE THREAD

**Issue by nuintun** [NervJS/taro#12195]
### 这个特性解决了什么问题？

兼容 webpack 5.69.0 以上版本

### 这个 API 长什么样？

无

![image](https://user-images.githubusercontent.com/1730277/182538790-1a566949-3657-41c1-8021-5487a2f0642d.png)

关联 https://github.com/NervJS/taro/pull/12194

**Comment by ZakaryCode** [comment]
可以自行升级版本

**Comment by nuintun** [comment]
@ZakaryCode 试了，报错

**Comment by Chen-jj** [comment]
> @ZakaryCode 试了，报错

https://github.com/NervJS/taro/pull/12194/files

prebundle 魔改的 WebpackModuleFederation 插件可能在后续 webpack 版本中有改动，需要兼容一下的样子。然后 peer 也应该用 `^`

**Comment by ZakaryCode** [comment]
> @ZakaryCode 试了，报错

目前未能复现该问题，可以提交相关 demo 用于测试

> @ZakaryCode prebundle 魔改的 WebpackModuleFederation 插件可能在后续 webpack 版本中有改动，需要兼容一下的样子。然后 peer 也应该用 `^`

相关的 pr 已经调整该内容，另外 prebundle 魔改的方案中暂无可复现的版本兼容问题
