### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by helloint** [NervJS/taro#12196]
### 相关平台
H5

**浏览器版本: Chrome 103**
**使用框架: React**

### 复现步骤
用Taro CLI创建一个新项目
taro init
React
Sass
TypeScript
default template

然后执行 dev:h5, 或 dev:weapp

### 期望结果
正常启动

### 实际结果
报错了
(node:6380) UnhandledPromiseRejectionWarning: /Users/111/workspace/tarot1/node_modules/postcss-pxtransform/index.js:44
  const baseFontSize = options.baseFontSize ?? options.minRootSize >= 1 ? options.minRootSize : 20
                                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/Users/111/workspace/tarot1/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getDefaultPostcssConfig (/Users/111/workspace/tarot1/node_modules/@tarojs/webpack5-runner/src/postcss/postcss.h5.ts:72:48)
    at H5WebpackModule.getPostCSSRule (/Users/111/workspace/tarot1/node_modules/@tarojs/webpack5-runner/src/webpack/H5WebpackModule.ts:227:51)
(node:6380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
👽 Taro v3.5.1


  Taro CLI 3.5.1 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.1 => 3.5.1 
      @tarojs/components: 3.5.1 => 3.5.1 
      @tarojs/helper: 3.5.1 => 3.5.1 
      @tarojs/plugin-framework-react: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-alipay: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-jd: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-qq: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-swan: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-tt: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1 
      @tarojs/react: 3.5.1 => 3.5.1 
      @tarojs/router: 3.5.1 => 3.5.1 
      @tarojs/runtime: 3.5.1 => 3.5.1 
      @tarojs/shared: 3.5.1 => 3.5.1 
      @tarojs/taro: 3.5.1 => 3.5.1 
      @tarojs/taro-h5: 3.5.1 => 3.5.1 
      babel-preset-taro: 3.5.1 => 3.5.1 
      eslint-config-taro: 3.5.1 => 3.5.1 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
看了这个代码是在这里被修改的
https://github.com/NervJS/taro/commit/344c6e6d6c9a7a2c135923f5f0784a76b4f4fd2d

**Comment by helloint** [comment]
看来是这里多写了个问号：
https://github.com/NervJS/taro/commit/04d0fc2093fe21c5b6e8a6675d3c458a6c30a37e#diff-c38d2b5421feda6cf30edd421812f28078179d1c07d250afc9ae1afca19cb86eR44

**Comment by ZakaryCode** [comment]
空值合并运算符是标准的 js 语法，在 [ES2020](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) 支持，考虑到部分开发者 Babel 配置差异，可以考虑使用适用性更广的语法。

**Comment by helloint** [comment]
嗯，和我Node版本有关系。Node14以上就支持了。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
谢谢

**Comment by message163** [comment]
node 14 还是有几率 报错
