### ISSUE TITLE
升级弃用的依赖到最新维护版

### ISSUE THREAD

**Issue by nuintun** [NervJS/taro#12193]
### 这个特性解决了什么问题？

提升性能，废弃弃用的依赖版本，防范安全漏洞！

特别是 `@tarojs/components` 等发送到客户端库！

### 这个 API 长什么样？

无

![image](https://user-images.githubusercontent.com/1730277/182506706-5f1f9f12-d812-4b1e-bef4-52675b2644b5.png)

**Comment by ZakaryCode** [comment]
duplicate #11262
