### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by mark-wk** [NervJS/taro#122]
init项目时候安装依赖报错
pm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://r.cnpmjs.org/@tarojs%2ftaro-weapp failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by luckyadam** [comment]
清一下 `npm` 缓存，然后再安装试试

**Comment by mark-wk** [comment]
@luckyadam 清除后还是不行。。

**Comment by yuche** [comment]
你能访问到这个地址吗？

https://r.cnpmjs.org/@tarojs%2ftaro-weapp 

看一下贵司防火墙是否屏蔽了这个地址？

**Comment by mark-wk** [comment]
@yuche  可能得fq

**Comment by Zkim** [comment]
我遇到同样的问题了，不翻墙的确无法访问那个地址，翻墙了虽然能访问了但是也没解决问题，求助！

**Comment by luckyadam** [comment]
访问淘宝源也要翻墙啊。。换成 `yarn` 试试呢

**Comment by mark-wk** [comment]
@luckyadam @Zkim  yarn可以完美安装

**Comment by luckyadam** [comment]
非常棒

**Comment by Zkim** [comment]
我的问题yarn也没有解决，我今天折腾了几个小时终于搞定了，是由于npm config的问题，不知道是哪里设置可能有冲突，一直有问题，我后来全干掉重新绑定淘宝镜像就解决了。

**Comment by mark-wk** [comment]
@Zkim  用yarn要把以前init的删掉，重新init
