### ISSUE TITLE
taro app 真实手机扫码调试，进入页面就 TypeError: undefined is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames.includes')

### ISSUE THREAD

**Issue by Duanruilong** [NervJS/taro#12201]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
初始化完成，yarn dbuild:rn --platform android 进入扫码调试，Android 9 真机taro扫码，进入首页就报错。

![Uploading Snipaste_2022-08-03_11-44-48.png…]()

### 期望结果
可以正常进入调试

### 实际结果
无法进入调试

### 环境信息
```
Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.12.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Duanruilong** [comment]
ERROR  TypeError: undefined is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames.includes')
 LOG  Running "taroDemo" with {"rootTag":291} ERROR  Invariant Violation: "taroDemo" has not been registered. This can happen if:* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by zhiqingchen** [comment]
此问题需要提供demo地址

**Comment by Duanruilong** [comment]
老版taro app扫码没问题，应该是最新版得taro app 不支持，使用老版本扫码没有问题了。

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-playground#supported-versions
