### ISSUE TITLE
npm i @tarojs/webpack-runner  失败

### ISSUE THREAD

**Issue by cross24** [NervJS/taro#1221]
PS C:\Users\dell\Desktop\taro\myApp> npm i @tarojs/webpack-runner

> node-sass@4.10.0 install C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://r.cnpmjs.org/node-sass//v4.10.0/win32-x64-57_binding.node
Cannot download "https://r.cnpmjs.org/node-sass//v4.10.0/win32-x64-57_binding.node":

connect ETIMEDOUT 161.117.70.42:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.10.0 postinstall C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\dell\Desktop\taro\myApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://r.cnpmjs.org/node
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\dell\Desktop\taro\myApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\dell\Desktop\taro\myApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\dell\Desktop\taro\myApp\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\dell\Desktop\taro\myApp\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\dell\Desktop\taro\myApp\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.4
gyp verb command install [ '8.11.4' ]
gyp verb download using dist-url https://r.cnpmjs.org/node
gyp verb install input version string "8.11.4"
gyp verb install installing version: 8.11.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.4
gyp verb build dir attempting to create "build" dir: C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\dell\\.node-gyp\\8.11.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\dell\\.node-gyp\\8.11.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\dell\\.node-gyp\\8.11.4\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb download using dist-url https://r.cnpmjs.org/node
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\dell\.node-gyp\8.11.4
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2018/11/23 11:08:17。
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。

生成失败。

  MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。

    0 个警告
    1 个错误

已用时间 00:00:00.22
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dell\Desktop\taro\myApp\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\Desktop\\taro\\myApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\dell\Desktop\taro\myApp\node_modules\node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN @tarojs/router@1.2.0-beta.1 requires a peer of @tarojs/taro-h5@1.1.0-beta.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2018-11-23T03_08_19_356Z-debug.log

**Comment by luckyadam** [comment]
可以挂个代理，或者用 [cnpm](https://npm.taobao.org) 来安装

**Comment by xPixv** [comment]
node-sass 的 dist 源的问题，即使你把 registry 源和 dist 源修改成淘宝的，国内网络环境也不太容易下载成功

个人解决方法：
新建一个 `.npmrc` 文件在要执行 `npm` 或 `yarn` 命令的目录下，内容如下
``` text
registry=https://registry.npm.taobao.org
sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
```
![文件结构](https://user-images.githubusercontent.com/9652227/51624598-2478a880-1f76-11e9-8244-c6d13338e7a5.png)
然后再执行 yarn(npm) install / yarn(npm) install [package]

（这玩意儿弄了我一个小时，sigh!
