### ISSUE TITLE
Taor v3.5.0 react-redux connect添加forwardRef后导致生命周期不执行

### ISSUE THREAD

**Issue by Tinyyyyyyy** [NervJS/taro#12216]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Tinyyyyyyy/taro-ref.git](https://github.com/Tinyyyyyyy/taro-ref.git)
**小程序基础库: 2.25.2**
**使用框架: React**

### 复现步骤
代码在src/page/index/index.tsx

### 期望结果
正常执行生命周期

### 实际结果
没有执行生命周期

### 环境信息
```
� Taro v3.5.0


  Taro CLI 3.5.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.1 - C:\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\xxx\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.16 - C:\nodejs\npm.CMD

```

---
### 补充信息
删除forwardRef后是正常的。
v3.3.7是没问题，最近在升级v3.5.0测试出的问题。

**Comment by Tinyyyyyyy** [comment]
react-redux的connect执行到React.forwardRef()返回的ref为空导致injectPageInstance没有执行
![1659680202411](https://user-images.githubusercontent.com/42465774/183013597-69401cc4-ff5a-4ed1-8008-4d13de78cddb.png)

**Comment by Chen-jj** [comment]
@Tinyyyyyyy 当页面被 react-redux connect 后，Taro 实际上会传递 `reactReduxForwardedRef` 给 Connect 组件（而不是传递 ref）。和配置 `forwardRef` 的作用是一样的，因此你不需要自己配置此属性。

https://github.com/NervJS/taro/blob/ace861d711e06bfb23833c8ca21c32aca6e4dc7f/packages/taro-plugin-react/src/runtime/connect.ts#L62-L66

**Comment by Tinyyyyyyy** [comment]
@Chen-jj 所以升级3.5需要把connect去掉forwardRef，对吗

**Comment by Chen-jj** [comment]
这个改动很久前作出的，与 3.5 无关
