### ISSUE TITLE
github redux模版启动报错

### ISSUE THREAD

**Issue by Aliom252181** [NervJS/taro#12225]
### 相关平台
H5

**浏览器版本: Chrome104.0.5112.79**
**使用框架: React**

### 复现步骤
使用 react ts webpack5 sass yarn redux的github模版
yarn
yarn run dev:h5

### 期望结果
正常

### 实际结果
ERROR in ./src/app.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Volumes/T5/Code/gc-nativeapp-cli/taro-rn-h5-mini-ts/src/app.ts: Unexpected token, expected "," (22:16)

  20 |   render() {
  21 |     return (
> 22 |       <Provider store={store} >
     |                 ^
  23 |         {this.props.children }
  24 |       < /Provider>
  25 |     )

### 环境信息
```
👽 Taro v3.5.1


  Taro CLI 3.5.1 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.6.0/bin/yarn
      npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.1 => 3.5.1 
      @tarojs/components: 3.5.1 => 3.5.1 
      @tarojs/helper: 3.5.1 => 3.5.1 
      @tarojs/plugin-framework-react: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-alipay: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-jd: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-qq: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-swan: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-tt: 3.5.1 => 3.5.1 
      @tarojs/plugin-platform-weapp: 3.5.1 => 3.5.1 
      @tarojs/react: 3.5.1 => 3.5.1 
      @tarojs/rn-runner: 3.5.1 => 3.5.1 
      @tarojs/router: 3.5.1 => 3.5.1 
      @tarojs/runtime: 3.5.1 => 3.5.1 
      @tarojs/shared: 3.5.1 => 3.5.1 
      @tarojs/taro: 3.5.1 => 3.5.1 
      @tarojs/taro-h5: 3.5.1 => 3.5.1 
      @tarojs/taro-rn: 3.5.1 => 3.5.1 
      babel-preset-taro: 3.5.1 => 3.5.1 
      eslint-config-taro: 3.5.1 => 3.5.1 
      expo: ~45.0.2 => 45.0.8 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.68.2 => 0.68.2 
```

**Comment by Aliom252181** [comment]
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/49222345/183025917-db991604-b7eb-4002-82f2-543e391fd053.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/49222345/183025983-6b0024e5-5c66-414a-b4b8-f06de04bb43d.png">

**Comment by crazylxr** [comment]
怎么解决的呀？
