### ISSUE TITLE
为什么快手小程序安装了@tarojs/plugin-platform-kwai 插件，打包出来的dist里面project.config.json文件，导致导入不了快手开发工具进行预览

### ISSUE THREAD

**Issue by bandiandou** [NervJS/taro#12229]
### 相关平台
快手小程序

**使用框架: React**

### 复现步骤
按照官方文档创建快手小程序，build后，在快手开发工具导入dist包提示没有project.config.json文件，是还需要配置什么文件吗，急急急

### 期望结果
应该包含project.config.json文件

### 实际结果
没有project.config.json文件

### 环境信息
```
� Taro v3.5.1


  Taro CLI 3.5.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\mi\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

```

**Comment by bandiandou** [comment]
![image](https://user-images.githubusercontent.com/86463809/183037144-0dac0194-1f03-47d2-9fb0-edabb498b96e.png)

**Comment by bandiandou** [comment]
![image](https://user-images.githubusercontent.com/86463809/183037237-3faeeb5e-52af-498b-aaef-0af377c5eddc.png)

**Comment by bandiandou** [comment]
![image](https://user-images.githubusercontent.com/86463809/183037833-6c7c09f8-d997-4b44-9ebb-279cb2ae971e.png)

**Comment by bandiandou** [comment]
需要配置什么文件吗

**Comment by qsjc** [comment]
官方文档好像没看到说支持快手小程序啊

**Comment by bandiandou** [comment]
> 官方文档好像没看到说支持快手小程序啊
![image](https://user-images.githubusercontent.com/86463809/183327380-de74be50-6fe5-455f-9013-438f3963a1dd.png)
zhi支持了的吧，官方文档都有写

**Comment by peterczg** [comment]
先自己新建一个config文件看能不能正常跑起来

**Comment by Chen-jj** [comment]
@bandiandou src 目录下新建 `project.ks.json`，编译后就是 `project.config.json` 了

**Comment by bandiandou** [comment]
> @bandiandou src 目录下新建 `project.ks.json`，编译后就是 `project.config.json` 了

建议在官方文档上有补充，官方文档没写
