### ISSUE TITLE
Taro RN 支持 css module 多 className 写法

### ISSUE THREAD

**Issue by biorz** [NervJS/taro#12226]
### 这个特性解决了什么问题？
开启 cssModule 时，不支持多 className 写法。

### 这个 API 长什么样？
希望支持以下写法

```typescript
import styles from './styles.module.scss'

export default function () {
  return <View className={`${styles.a} ${styles.b}`}></View>
}

```

**Comment by y213140** [comment]
这样解析出来也不是cssModule格式

**Comment by biorz** [comment]
> y213140
RN 的方案是天然的 css Module 不需要像 h5 一样生成 hash。主要是为了其他端开启 cssModule 时，在 RN 端可以正确识别语法。

**Comment by biorz** [comment]
fix [12365](https://github.com/NervJS/taro/pull/12365)
