### ISSUE TITLE
百度小程序，嵌套map，第二层s-for绑定有误

### ISSUE THREAD

**Issue by HenryLulu** [NervJS/taro#1223]
![image](https://user-images.githubusercontent.com/14797054/48930958-af193900-ef2e-11e8-9c22-872bea49d6f1.png)
编译成swan后，第二层s-for="$anonymousCallee__15"
![image](https://user-images.githubusercontent.com/14797054/48931100-847bb000-ef2f-11e8-9dc7-c677c2f7d904.png)
但state中，$anonymousCallee__15是在第一层下的。
![image](https://user-images.githubusercontent.com/14797054/48931081-7168e000-ef2f-11e8-8012-962deea08ca5.png)
所以s-for的正确引用应该是s-for="key.$anonymousCallee__15"

**Comment by yuche** [comment]
你这个在微信小程序能跑吗，顺便 JSX 源码贴一份字符，不要截图，整个 render 函数一起贴出来

**Comment by HenryLulu** [comment]
感谢回复～

微信小程序也跑不起来
taro版本：1.1.9
render函数如下：

     render() {
        const ListCards = Object.keys(this.props.lesson).map(key => {
            const curKey = this.props.lesson[key];
            const ListItems = Object.keys(curKey.sub).map(subkey => {
                return (<Text className="listitem">{subkey}</Text>)
                // return subkey
            });
            return (
                <View className="listcard">
                    <Text className="listtitle">{curKey.name}</Text>
                    <View className="sublist">
                        {ListItems}
                    </View>
                </View>
            );
        });

        return (
            <View className="lesson">
                <View className="sidebar">
                    {Object.keys(this.props.lesson).map(key => (
                        <Text className={`sideitem ${this.state.currentUnit === key ? 'current' : ''}`}
                            key={key}>{this.props.lesson[key].unit}</Text>
                    ))}
                </View>
                <ScrollView className="list" scrollY={true}>
                    {ListCards}
                </ScrollView>
            </View>
         );
      }

this.props.lesson 数据格式如下：

    {
      "u0": {
        "unit": "第一章",
        "name": "第一章　集合与函数概念",
        "sub": {
          "l0": "集合",
          "l1": "函数及其表示",
          "l2": "函数的基本性质"
        }
      },
      "u1": {
        "unit": "第二章",
        "name": "第二章　基本初等函数(I)",
        "sub": {
          "l0": "指数函数",
          "l1": "对数函数",
          "l2": "幂函数"
        }
      },
      "u2": {
        "unit": "第三章",
        "name": "第三章　函数的应用",
        "sub": {
          "l0": "函数与方程",
          "l1": "函数模型及其应用"
        }
      }
    }

**Comment by yuche** [comment]
下个版本会修复，临时的解决方案是把循环内的 JSX 定义挪一下：

```jsx
const ListCards = Object.keys(this.props.lesson).map(key => {
    const curKey = this.props.lesson[key];
    return (
        <View className="listcard">
            <Text className="listtitle">{curKey.name}</Text>
            <View className="sublist">
                {Object.keys(curKey.sub).map(subkey => {
                    return (<Text className="listitem">{subkey}</Text>)
                    // return subkey
                });}
            </View>
        </View>
    );
});
```

**Comment by yuche** [comment]
那你现在就这样：

```jsx
const ListCards = Object.keys(this.props.lesson).map(key => {
    const curKey = this.props.lesson[key];
    const subs = Object.keys(curKey.sub);
    return (
        <View className="listcard">
            <Text className="listtitle">{curKey.name}</Text>
            <View className="sublist">
                {subs.map(subkey => {
                    return (<Text className="listitem">{subkey}</Text>)
                    // return subkey
                });}
            </View>
        </View>
    );
});
```
