### ISSUE TITLE
国际化组件（vue-i18n）引入使用报错

### ISSUE THREAD

**Issue by 893949088** [NervJS/taro#12230]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/893949088/taro_test.git](https://github.com/893949088/taro_test.git)
**小程序基础库: 2.55.1**
**使用框架: React**

### 复现步骤
环境：
Taro 3.4.16
Vue3
UI NutUI
Vue-i18n 9.1.10

在template中使用$t('')报错：

![image](https://user-images.githubusercontent.com/4034377/180676119-12b89e88-834c-4189-83c9-64c7d7fa20f4.png)

### 期望结果
正常显示国际化

### 实际结果
template使用$t('')报错

### 环境信息
```

Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - E:\User\NPM\node_global\yarn.CMD
      npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
duplicate #12230
