### ISSUE TITLE
【3.5.2】 <image>标签被编译成<text>标签，导致图片无法展示

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#12237]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/fanlvwen/demo/blob/main/image](https://github.com/fanlvwen/demo/blob/main/image)
**小程序基础库: 2.0**
**使用框架: Vue 2**

### 复现步骤
提交issue的时候，无法选择3.5.2版本
直接运行demo，发现<image>标签被编译成<text>标签，导致图片无法展示

### 期望结果
正确展示图片

### 实际结果
<image>标签被编译成<text>标签，导致图片无法展示

### 环境信息
```
Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.23.3 - D:\nodejs\node.EXE
      npm: 6.14.11 - D:\nodejs\npm.CMD
```

---
### 补充信息
直接用3.5.2的taro init，勾选的taro ui 模板

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/183329529-7943915d-401e-49ee-a673-9ae66080cf0b.png)

**Comment by Chen-jj** [comment]
@fanlvwen 没有复现 image 错误编译成 text 的情况，麻烦提供一下完整 demo

**Comment by Chen-jj** [comment]
和 #12176 有点相似，但都没能复现，最好提供一下完整 demo

**Comment by fanlvwen** [comment]
[demo.zip](https://github.com/NervJS/taro/files/9286510/demo.zip)
@Chen-jj 辛苦看下。是win10环境

**Comment by Chen-jj** [comment]
@fanlvwen 与 windows 应该无关，我试了标签渲染是正常的 `image`

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/11807297/183612355-b04a5072-06b5-4103-b1a5-ab764587b420.png">

图片不显示只是因为你设置了白色 background，去掉就可以了：

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/11807297/183612606-d9a7a23d-2ca3-4c32-b2e8-355cef134dd6.png">

**Comment by fanlvwen** [comment]
> ![image](https://user-images.githubusercontent.com/36951996/183329529-7943915d-401e-49ee-a673-9ae66080cf0b.png)

@Chen-jj 你看我这个截图，编译出来的确实就是<text>

**Comment by fanlvwen** [comment]
很神奇，同样的代码，两边编译出来的代码却不一样，可能是系统配置不一样导致？

**Comment by Chen-jj** [comment]
@fanlvwen 我的截图是用你的 demo 跑的，的确没能复现。。

**Comment by Chen-jj** [comment]
> 很神奇，同样的代码，两边编译出来的代码却不一样，可能是系统配置不一样导致？

重装依赖试试？

**Comment by fanlvwen** [comment]
> @fanlvwen 我的截图是用你的 demo 跑的，的确没能复现。。

我的截图也是demo的代码，我试过两个项目，一个是我们之前2.x的项目，升级了taro和依赖，图片不展示，我以为是依赖问题，然后我用taro init重新建了这个demo项目，依然是不展示图片，编译成了<text>

**Comment by Chen-jj** [comment]
编译后的代码发一下，dev 模式

**Comment by fanlvwen** [comment]
[dist.zip](https://github.com/NervJS/taro/files/9289181/dist.zip)
@Chen-jj

**Comment by Chen-jj** [comment]
@fanlvwen 首先确认一下 CLI 的版本是否和项目的 taro 依赖版本保持一致。

看了你的 dist，发现是我们生成的模板不一样，我的 3 号模板是 `image`，而你的 3 号模板是 `text`。

![image](https://user-images.githubusercontent.com/11807297/183644685-19e97855-4227-4866-9af3-f28d01846892.png)

模板名称与模板号码的对应是在这里处理的：

![image](https://user-images.githubusercontent.com/11807297/183645277-3c1ee486-ce5c-46de-a0a1-6c4d20e62b44.png)

上图红框位置加一行 log，之后编译时在命令行、运行时在开发者工具里都会有输出。对比看看编译时的 origin、mapping 和运行时的 origin、mapping 有没不一样。

当一切正常时，`static-image` 对应的模板号码，也就是 `_num` 属性，应该是 3

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/183854903-170fb24d-aced-4149-87c9-51503f365f5d.png)
系统环境下也是3.5.2；

**Comment by fanlvwen** [comment]
你是用demo直接install后run dev：alipay的吗，我这边应该是vue2的

**Comment by EwanBerg** [comment]
@Chen-jj 3.5.1 IDE预览展示，但是真机未展示

**Comment by chenxinbin** [comment]
我在3.5.0的时候支付宝小程序也出现image渲染出view的情况，但是更新至3.5.2后，恢复正常了

**Comment by chenxinbin** [comment]
> 我在3.5.0的时候支付宝小程序也出现image渲染出view的情况，但是更新至3.5.2后，恢复正常了

我今天确认了下，确实仍存在问题. 3.5.2. 2.5.3 仍存在此问题。无图模式裸奔了好几天

**Comment by EwanBerg** [comment]
> 
昨天我已经把项目转到remax了，一切正常。无奈remax文档挂了，怕同事不方便维护。试了试taro 3.5之前的版本3.4.14 是可以的。3.4.13应该也可以，我们组之前是那个版本写mpass小程序没听他们说图片不正常。

**Comment by EwanBerg** [comment]
> > 我在3.5.0的时候支付宝小程序也出现image渲染出view的情况，但是更新至3.5.2后，恢复正常了
> 
> 我今天确认了下，确实仍存在问题. 3.5.2. 2.5.3 仍存在此问题。无图模式裸奔了好几天

昨天我已经把项目转到remax了，一切正常。无奈remax文档挂了，怕同事不方便维护。试了试taro 3.5之前的版本3.4.14 是可以的。3.4.13应该也可以，我们组之前是那个版本写mpass小程序没听他们说图片不正常。

**Comment by sqs8866** [comment]
我也遇到了这种情况。view给编译成了image；image给编译成了text

**Comment by sqs8866** [comment]
> 我也遇到了这种情况。view给编译成了image；image给编译成了text

vue2是好的，react也是好的，就是vue3有问题

**Comment by Chen-jj** [comment]
#12351 将修复 #12320 ，应该也能修复本问题，各位可以在 3.5.4 再试试的

**Comment by chenxinbin** [comment]
> #12351 将修复 #12320 ，应该也能修复本问题，各位可以在 3.5.4 再试试的

V3.5.4, React 支付宝小程序真机环境下图片显示正常了。
