### ISSUE TITLE
rn apk打包修改包名为中文后App名字变成乱码

### ISSUE THREAD

**Issue by shaoming1101** [NervJS/taro#12245]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
修改app_name = 中文,打包成功以后包名为乱码

### 期望结果
解决乱码

### 实际结果
还未解决

### 环境信息
```
 Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\66411\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by shaoming1101** [comment]
![4ef5793060effde576eb8b53b0163a4](https://user-images.githubusercontent.com/86390105/183357944-f7ee73e4-85e6-41e3-a6db-53f878835d8d.jpg)
![e85de2007df5b2b0418db288f1d0e34](https://user-images.githubusercontent.com/86390105/183357972-a91225d5-8bf1-4a0a-ae44-489f685b1b22.jpg)

**Comment by zhiqingchen** [comment]
使用 Unicode

**Comment by zhiqingchen** [comment]
app_name=\u6d4b\u8bd5\u9879\u76ee
