### ISSUE TITLE
rn打包,修改包名为中文时乱码

### ISSUE THREAD

**Issue by shaoming1101** [NervJS/taro#12243]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
app_name=中文名字,打包以后下载安装包,安装包名是乱码

### 期望结果
能创建中文名

### 实际结果
还没

### 环境信息
```
 Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\66411\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by shaoming1101** [comment]
![4ef5793060effde576eb8b53b0163a4](https://user-images.githubusercontent.com/86390105/183356744-c82de6cf-d57b-4437-b729-53ed836d8d53.jpg)
![e85de2007df5b2b0418db288f1d0e34](https://user-images.githubusercontent.com/86390105/183356765-6da1b52c-17d3-471f-a0fc-84ce629f11f0.jpg)

**Comment by zhiqingchen** [comment]
重复
https://github.com/NervJS/taro/issues/12245
