### ISSUE TITLE
taro3.5.2 H5， 编译出现错误和卡顿状态，编译完后出现错误。

### ISSUE THREAD

**Issue by zhouzyc** [NervJS/taro#12244]
### 相关平台
H5

### 复现仓库
[https://gitee.com/JS-VeryHappy/vh-mobile-demo.git](https://gitee.com/JS-VeryHappy/vh-mobile-demo.git)
**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
taro3.5.1 => 3.5.2；
yarn dev:h5;
1.出现错误：Error: Cannot find module 'webpack'
Require stack:
- /Applications/MAMP/htdocs/myframework/vh-mobile-demo/config/webpack/miniChain.js
- /Applications/MAMP/htdocs/myframework/vh-mobile-demo/config/index.js
（安装"webpack":"^5.0.0" 依赖后可编译）
2.编译后出现很长时间的进度条卡顿。
<img width="1251" alt="WX20220808-133323@2x" src="https://user-images.githubusercontent.com/18420689/183347172-68ce8112-2348-4086-9d01-452e78fdeb17.png">

3.编译完成后出现错误：
<img width="1344" alt="WX20220808-134024@2x" src="https://user-images.githubusercontent.com/18420689/183347197-60d8d1fc-1612-4e8a-8094-1f8febafcda0.png">

### 期望结果
正常运行

### 实际结果
出现错误

### 环境信息
```
Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 
      Yarn: 1.22.19 
      npm: 8.3.1

```

**Comment by zhouzyc** [comment]
再请问下出现错误的时候，全局错误拦截显示页面可以关闭吗，我不需要页面出现错误的UI提示
![WX20220808-134434](https://user-images.githubusercontent.com/18420689/183347535-eb233f85-cdc4-48bd-865f-4d4d3480ad47.png)

**Comment by ZakaryCode** [comment]
- webpack 属于幽灵依赖，需要在根目录安装，相关问题可以看 3.5 版本文章
- prebundle 特性依赖于 import 加载依赖，详情可以参考 [prebundle 文档](https://nervjs.github.io/taro-docs/docs/prebundle)
- 关闭编译器全屏错误提示，参考 [webpack 文档](https://webpack.js.org/configuration/dev-server/#overlay)

**Comment by ZakaryCode** [comment]
卡顿和依赖加载错误复现，将在下一版本修复，该问题和 #12240 重复将关闭
