### ISSUE TITLE
安卓端打包失败

### ISSUE THREAD

**Issue by wandiao** [NervJS/taro#1225]
**问题描述**
打包的app应用报错

**复现步骤**
执行taro init myApp生成项目
cd myApp
npm run dev:rn 启动成功，模拟器正常访问
cd .rn_temp
修改app.json
```js
{
  "expo": {
    "name": "myApp",
    "description": "A very interesting project.",
    "slug": "myApp",
    "privacy": "public",
    "sdkVersion": "27.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.jkal.myApp"
    },
    "android": {
      "package": "com.jkal.myApp"
    }
  }
}
```
执行exp build:android成功打包
下载apk安装
打开 报错
![screenshot_2018-11-23-15-43-31-340_com jkal www](https://user-images.githubusercontent.com/23516461/48932390-a0368480-ef36-11e8-99ed-9b13cc4bb95d.png)

**系统信息**

 - 操作系统: mac10.14
 - Taro 版本 1.1.8
 - Node.js 版本 v11.1.0
 - 报错平台 [rn]

**Comment by Pines-Cheng** [comment]
已重现，正在排查。

**Comment by Manjiz** [comment]
已锁定问题，正在处理

**Comment by wandiao** [comment]
@Manjiz @Pines-Cheng 可以了，nice啊！！
