### ISSUE TITLE
Taro作为完整分包打包，超了2M该怎么办，万分火急求救！

### ISSUE THREAD

**Issue by bluescurry** [NervJS/taro#12259]
### 这个特性解决了什么问题？
项目现状是主包用原生小程序做的，用Taro开发了几个完整分包，现在的问题是Taro分包体积超过2M无法上传体验版，不知道该咋搞了，明天项目上线，求大佬指点迷津，万分感谢！！！

### 这个 API 长什么样？
想尝试使用微信小程序分包异步化来做，能抽出一个子包单独放 node_modules 打包出来的 vendors.js，其他子包不包含它，可以直接使用这个分包的代码。但是不知道咋怎么搞。。。

**Comment by airqj** [comment]
想办法先把静态资源放到服务器上去吧

**Comment by bluescurry** [comment]
> 想办法先把静态资源放到服务器上去吧

一点静态资源没有。。。纯代码，光 vendors.js 和 common.js 加起来就 1.2M

**Comment by moyafaxi** [comment]
主包还有空间吗，可以考虑 vendors.js 、common.js 放主包？

**Comment by bluescurry** [comment]
发现打包文件中含有很多不应该打包的第三方库，修改后减少了400+kb的代码。详细参考：https://github.com/NervJS/taro/issues/8169
