### ISSUE TITLE
feat(plugin-mini-ci) 应该暴露支付宝 minidev 支持的参数 project

### ISSUE THREAD

**Issue by dave-qiao** [NervJS/taro#12256]
## 现状
目前插件中支付宝小程序 miniedev 的字段 project 使用的 outputPath, 
无法在 pluginOpts 中设置来自定义 project
```js
const { outputPath: projectPath } = this.ctx.paths;
....
this.minidev.startIde(Object.assign({
            project: projectPath,
            projectType: 'alipay-mini'
        }
```

## 场景
单独使用 Taro 开发的大多数不存在 outputPath 跟项目要上传的目录不一致的问题，当使用原生跟 Taro 混合开发的方式，并且在工程上做两者的 workSpace 隔离时，会存在自定义打开及上传目录的需求。

## CIPluginOpt 配置信息
```js
module.exports = {
  alipay: {
    appId: '',
    toolId: '',
    privateKeyPath: '',
    project: '' // 暴露此字段
  },
  version: '',
  desc: ''
};
```

**Comment by bigmeow** [comment]
@dave-qiao 升级时注意， 3.6.0 版本这个选项名称变了
https://github.com/NervJS/taro/pull/12437
