### ISSUE TITLE
Taro 3.5.1在搭配recoil使用时，f5刷新页面多次，会出现报错。

### ISSUE THREAD

**Issue by jianhao2010303** [NervJS/taro#12250]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**浏览器版本: chrome 103**
**使用框架: React**

### 复现步骤
1.app 使用 
 <RecoilRoot>
      <Suspense fallback={<Loading />}>{props.children}</Suspense>
    </RecoilRoot>
包裹。
2. 使用recoil初始化内容

export const userInfoStore = atom<IUserInfo | undefined>({
  key: 'userInfoStore',
  default: (async () => {
    if (!cacheGetSync('accessToken')) {
      return undefined
    }
    try {
      return await baseUserInfo()
    } catch (err) {
      console.log(err)
      return undefined
    }
  })()
})
3. f5多刷新几次页面，报错。

### 期望结果
页面不报错。

### 实际结果
ErrorEvent {isTrusted: true, message: 'Uncaught Error: 没有找到页面实例。\n如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues', filename: 'webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js', lineno: 22834, colno: 7, …}
isTrusted: true
bubbles: false
cancelBubble: false
cancelable: true
colno: 7
composed: false
currentTarget: Window {0: Window, window: Window, self: Window, document: document, name: '', location: Location, …}
defaultPrevented: false
error: Error: 没有找到页面实例。 如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues at ensure (webpack-internal:///./node_modules/@tarojs/shared/dist/shared.esm.js:897:13) at AppWrapper.eval (webpack-internal:///./node_modules/@tarojs/runtime/dist/runtime.esm.js:3955:64) at callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13923:12) at commitUpdateQueue (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13944:9) at commitLayoutEffectOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23359:13) at commitLayoutMountEffects_complete (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24683:9) at commitLayoutEffects_begin (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24669:7) at commitLayoutEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24607:3) at commitRootImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26818:5) at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26677:5)
eventPhase: 0
filename: "webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js"
lineno: 22834
message: "Uncaught Error: 没有找到页面实例。\n如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues"
path: [Window]
returnValue: true
srcElement: Window {0: Window, window: Window, self: Window, document: document, name: '', location: Location, …}
target: Window {0: Window, window: Window, self: Window, document: document, name: '', location: Location, …}
timeStamp: 870.3000000119209
type: "error"
[[Prototype]]: ErrorEvent

### 环境信息
```
Taro CLI 3.5.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 
      Yarn: 1.22.19 
      npm: 8.11.0
```

**Comment by jianhao2010303** [comment]
为什么刷新没有Suspense 得loading效果了？

**Comment by ZakaryCode** [comment]
请提交完整示例项目便于测试

- 找不到实例优化于 #12190 可以更新尝试
- Suspense 方案在此处不适用

**Comment by jianhao2010303** [comment]
https://github.com/jianhao2010303/taro-h3.5.2-error.git 

1.clone后 执行yarn install
2. 在首页f5多次刷新页面，就报错异常。

**Comment by ZakaryCode** [comment]
1. 仓库内部分页面存在依赖错误，需要额外修复
2. 如上文所回复，此处报错 “没有找到页面实例” 是由于 Suspense 方案在此处不适用，props.children 并不是一个懒加载组件，可以参考 [react 官方文档](https://reactjs.org/docs/react-api.html#reactsuspense)
3. 多次刷新异常问题在 3.5.2 中不可见

**Comment by jianhao2010303** [comment]
把</Suspense>从app中删除， 下沉到了根组件上，不报错了。
