### ISSUE TITLE
微信或者支付宝扫码拉起小程序后的参数如何获取

### ISSUE THREAD

**Issue by xiao0502** [NervJS/taro#1226]
**问题描述**
微信或者支付宝扫普通链接二维码打开小程序的参数如何获取？ 在mpvue或者小程序中，是通过onLoad生命周期获取，taro的componentWillMount 类似于onLoad，但是无法获取，即为undefined

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```
onLoad(options) {
            // 普通二维码扫码进入流程
            if(options.q) {
                // ....
            }
        },
```

**期望行为**
```
componentWillMount(options) {
            // 普通二维码扫码进入流程
            if(options.q) {
                // ....
            }
        },
```

**报错信息**

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.1]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
`this.$router.params`

**Comment by xiao0502** [comment]
> `this.$router.params`

这个获取不了，支付宝小程序官方文档是这样的。

```
onlaunch(options){
    my.alert({
      title: 'app onLaunch',
      content:  JSON.stringify(options),
      success: (res) => {
          //成功处理代码段
      },
    });
  
  //获取关联普通二维码的码值，放到全局变量qrCode中
  if (options.query && options.query.qrCode) {
      this.qrCode = options.query.qrCode;
    }  
}
```

taro的`componentWillMount`生命周期是不是相当于支付宝小程序的onlaunch，但是按照支付宝小程序的文档上面也无法获取

**Comment by xiao0502** [comment]
@luckyadam

**Comment by jimmy2012** [comment]
@xiao0502 问题解决了吗？我也遇到同样的问题 @luckyadam this.$router.params这个好像无效

**Comment by Chen-jj** [comment]
#3313

**Comment by ZhaoTim** [comment]
this.$router.params对象上有一个q属性吗？还是说this.$router上有一个q属性啊？
@Chen-jj
