### ISSUE TITLE
Taro v3.4.3  yarn upgradePeerdeps 报错

### ISSUE THREAD

**Issue by Resulte** [NervJS/taro#12266]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
1. 执行`taro init` 初始化项目，选择react native模版；
2. 执行`yarn upgradePeerdeps`，报错

### 期望结果
依赖初始化成功

### 实际结果
[!] CocoaPods could not find compatible versions for pod "EXConstants":
  In Podfile:
    EXConstants (from `../node_modules/@tarojs/components-rn/node_modules/expo-constants/ios`)

Specs satisfying the `EXConstants (from `../node_modules/@tarojs/components-rn/node_modules/expo-constants/ios`)` dependency were found, but they required a higher minimum deployment target.

### 环境信息
```
  Taro CLI 3.4.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.3 => 3.4.3
      @tarojs/components: 3.4.3 => 3.4.3
      @tarojs/mini-runner: 3.4.3 => 3.4.3
      @tarojs/react: 3.4.3 => 3.4.3
      @tarojs/runtime: 3.4.3 => 3.4.3
      @tarojs/taro: 3.4.3 => 3.4.3
      @tarojs/webpack-runner: 3.4.3 => 3.4.3
      babel-preset-taro: 3.4.3 => 3.4.3
      eslint-config-taro: 3.4.3 => 3.4.3
      react: ^17.0.2 => 17.0.2
      react-native: ^0.67.3 => 0.67.4
```

**Comment by zhiqingchen** [comment]
使用最新版试试，或提供下初始化后的项目
