### ISSUE TITLE
Taro 3.5.2  因 swc 调用执行文件失败导致 TARO CLI 命令失效

### ISSUE THREAD

**Issue by b2nil** [NervJS/taro#12263]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/swc-project/swc/issues/1351](https://github.com/swc-project/swc/issues/1351)
**小程序基础库: 0.0.0**
**使用框架: React**

### 复现步骤
- 使用 `taro init` 命令新建项目
- 或使用 `taro help init` 等其他命令

### 期望结果
顺利使用 Taro CLI 的命令

### 实际结果
因 swc 无法调用绑定的执行文件，导致 Taro CLI 的 `taro init` 和 `taro help init` 等命令失效

### 环境信息
```
                       
👽 Taro v3.5.2

  Taro CLI 3.5.2 environment info:
    System:
      OS: windows 10
    Binaries:
      Yarn:  1.22.15
      Node: 16..15.1
    npmPackages:
```

---
### 补充信息
虽然是 swc 的问题， 但是 `taro help init` 这样的命令，如果没用使用到 swc 的功能，不应该失效才对

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/issues/12171

**Comment by b2nil** [comment]
先关了。
同样是 node v16.15, 一台电脑没问题，另一台电脑报错。

**Comment by b2nil** [comment]
PS: 
再报错的电脑上安装了 python 后，再运行 taro 命令，报错消失。
