### ISSUE TITLE
h5下,mobx会报错。

### ISSUE THREAD

**Issue by amusiq** [NervJS/taro#1227]
**问题描述**
h5下运行clone下来官方的taro-mobx-sample代码，会报错

**复现步骤**
[复现问题的步骤]
1. clone下来官方的taro-mobx-sample代码
2. yarn dev:h5运行项目

**期望行为**
能够支持h5
**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/28551646/48933661-1b4e6980-ef3c-11e8-834c-685449d818ee.png)
Uncaught Error: MobX injector: Store 'counterStore' is not available! Make sure it is provided by some Provider

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.2.0-beta.1]
 - Node.js 版本 [e.g. v10.9.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by nanjingboy** [comment]
@amusiq 无法复现呢，请确定一下几件事：

1. `@tarojs/cli`为最新版本
2. 如果`@tarojs/cli`为最新版本，把demo中的`node_modules`删掉再试试
3. 如果还不行的话，希望提供一些详细信息

**Comment by amusiq** [comment]
好的，按照你的方法解决了问题，谢谢

**Comment by amusiq** [comment]
> @amusiq 无法复现呢，请确定一下几件事：
> 
> 1. `@tarojs/cli`为最新版本
> 2. 如果`@tarojs/cli`为最新版本，把demo中的`node_modules`删掉再重新`install`试试
> 3. 如果还不行的话，希望提供一些详细信息

好的，按照你的方法解决了问题，谢谢
