### ISSUE TITLE
taro3.5.3， build:h5 编译后运行出现错误

### ISSUE THREAD

**Issue by zhouzyc** [NervJS/taro#12279]
### 相关平台
H5

### 复现仓库
[https://gitee.com/JS-VeryHappy/vh-mobile-demo.git](https://gitee.com/JS-VeryHappy/vh-mobile-demo.git)
**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
taro3.5.1 => 3.5.3；
yarn build:h5 && yarn serve;

1.出现错误：Uncaught (in promise) ScriptExternalLoadError: Loading script failed.
(missing: http://192.168.11.34:8061/remoteEntry.js)
while loading "./@tarojs/taro" from 8120
while loading "./react/jsx-runtime" from 8120
while loading "./@tarojs/runtime" from 8120
while loading "./@tarojs/plugin-framework-react/dist/runtime" from 8120
while loading "./@tarojs/router" from 8120
while loading "./@tarojs/components" from 8120
while loading "./ahooks" from 8120
while loading "./dingtalk-jsapi" from 8120
while loading "./recoil" from 8120
while loading "./react-dom" from 8120
while loading "./react" from 8120
    at 8120 (app.js:1:78)
    at __webpack_require__ (app.js:1:639)
    at handleFunction (app.js:1:4493)
    at app.js:1:4775
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.remotes (app.js:1:4142)
    at app.js:1:1770
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (app.js:1:1717)
    at app.js:1:8245
<img width="959" alt="WX20220811-143302@2x" src="https://user-images.githubusercontent.com/18420689/184077275-de2b4d6e-0fd7-4fed-a413-b793507ea907.png">

### 期望结果
正常运行

### 实际结果
出现错误

### 环境信息
```
Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 
      Yarn: 1.22.19 
      npm: 8.3.1

```

**Comment by ZakaryCode** [comment]
确实存在一些问题，下一个版本修复，也可以手动更新 chunkId 修复错误。

```js
    webpackChain (chain) {
      chain.optimization.set('chunkIds', 'deterministic') // 可以删除参数，也可以赋值为 `deterministic | named`
    }
```

**Comment by zhouzyc** [comment]
> 确实存在一些问题，下一个版本修复，也可以手动更新 chunkId 修复错误。
> 
> ```js
>     webpackChain (chain) {
>       chain.optimization.set('chunkIds', 'deterministic') // 可以删除参数，也可以赋值为 `deterministic | named`
>     }
> ```
这个复现demo 开发模式 编译小程序也会出错
