### ISSUE TITLE
v3.5.3 taro-hooks模板直接运行 dev:weapp 微信开发工具报错 __webpack_modules__[moduleId] is not a function

### ISSUE THREAD

**Issue by 23233** [NervJS/taro#12281]
### 相关平台
微信小程序

**小程序基础库: 2.25.2**
**使用框架: React**

### 复现步骤
taro init taro352
选择 typescript pnpm taro-hooks
直接运行dev:weapp 再微信开发工具中报错
```
页面【comp]错误:
 TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (webpack_bootstrap:19)
    at __webpack_exec__ (comp.js?t=wechat&s=1660205867618&v=f2db1139910e11f1b943ffca14253835:4)
    at comp.js?t=wechat&s=1660205867618&v=f2db1139910e11f1b943ffca14253835:5
    at Function.__webpack_require__.O (webpack_runtime_chunk loaded:25)
    at comp.js?t=wechat&s=1660205867618&v=f2db1139910e11f1b943ffca14253835:6
    at webpackJsonpCallback (webpack_runtime_jsonp chunk loading:74)
    at comp.js?t=wechat&s=1660205867618&v=f2db1139910e11f1b943ffca14253835:2
    at T (WASubContext.js?t=wechat&s=1660205867618&v=2.25.2:1)
    at <anonymous>:6734:7
    at doWhenAllScriptLoaded (<anonymous>:6797:21)(env: Windows,mp,1.06.2208010; lib: 2.25.2)
```

![image](https://user-images.githubusercontent.com/12870070/184094438-a980430b-41b4-4d56-abb6-e2ceeaad5a7a.png)

### 期望结果
无异常

### 实际结果
有异常无法打开

### 环境信息
```
 Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - C:\Users\111\AppData\Local\pnpm\node.EXE
      Yarn: 1.22.18 - C:\Users\111\AppData\Local\pnpm\yarn.CMD
      npm: 8.11.0 - C:\Users\111\AppData\Local\pnpm\npm.CMD

```

**Comment by 23233** [comment]
选择列表如下 node版本 `v16.15.1`
![image](https://user-images.githubusercontent.com/12870070/184094716-3f84ce77-95a5-41a5-aac2-002851a7d089.png)

**Comment by cherrol** [comment]
vue 编译到 weapp 也是一样的错误。

**Comment by xuhongbo** [comment]
> vue 编译到 weapp 也是一样的错误。

俺也一样

**Comment by suemor233** [comment]
我也是，降到 v3.5.2 就没问题

**Comment by xuhongbo** [comment]
> 我也是，降到 v3.5.2 就没问题

你可真是人才，解决了我的问题

**Comment by yedongze** [comment]
> > vue 编译到 weapp 也是一样的错误。
> 
> 俺也一样

试试关闭 prebundle
```
// config/index.js

compiler: {
  type: "webpack5",
  prebundle: {
    enable: false 
  }
}
```

**Comment by yanbowe** [comment]
same here

**Comment by cherrol** [comment]
> > > vue 编译到 weapp 也是一样的错误。
> > 
> > 
> > 俺也一样
> 
> 试试关闭 prebundle
> 
> ```
> // config/index.js
> 
> compiler: {
>   type: "webpack5",
>   prebundle: {
>     enable: false 
>   }
> }
> ```

太棒了，看起来这样是可以的。

**Comment by yuconora** [comment]
3.5.3 微信小程序目前只能关闭 prebundle 或者使用 webpack4 编译, 大佬有时间看下 @Chen-jj

**Comment by zgnation** [comment]
3.5.3我也遇到，麻烦尽快解决

**Comment by zgnation** [comment]
> > > > vue 编译到 weapp 也是一样的错误。
> > > 
> > > 
> > > 俺也一样
> > 
> > 
> > 试试关闭 prebundle
> > ```
> > // config/index.js
> > 
> > compiler: {
> >   type: "webpack5",
> >   prebundle: {
> >     enable: false 
> >   }
> > }
> > ```
> 
> 太棒了，看起来这样是可以的。
我加了，还是不行

**Comment by 23233** [comment]
暂时回退到3.5.2 可暂时解决问题 
测试关闭 `prebundle ` 无效
测试使用`webpack4`  如果使用pnpm需要同步变更依赖 并且重新安装`runner`  这要是修复了 又改回来太麻瓜
所以保命大法 回退到 `3.5.2`

**Comment by Virgil-N** [comment]
我使用的pnpm，然后也报错

**Comment by peakchen90** [comment]
开发模式有问题，压缩构建模式没问题

**Comment by aehyok** [comment]
留个角角  看什么时候更新

**Comment by msir5418** [comment]
降到3.5.2已解决
