### ISSUE TITLE
移除 @tarojs/cli  中残留的 @tarojs/transformer-wx

### ISSUE THREAD

**Issue by arniu** [NervJS/taro#12286]
### 这个特性解决了什么问题？
@tarojs/transformer-wx 似乎没用到，留着何为？

### 这个 API 长什么样？
移除残留的 @tarojs/transformer-wx

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/194981058-25ef6555-62cd-4ee5-a36d-bdcf9cd4645b.png)
![image](https://user-images.githubusercontent.com/22173084/194981078-cc6c8181-d9c3-4a56-9ee1-5f450ca2f49f.png)

搜了下有用到

**Comment by ZEJIA-LIU** [comment]
3.6.3版本已经不在引入该包
