### ISSUE TITLE
taro3.5.2 windows build RN报错

### ISSUE THREAD

**Issue by Aliom252181** [NervJS/taro#12289]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
yarn run taro build --type rn

出现错误
D:\work\gc-nativeapp-system\taro-rn-h5-mini-ts\node_modules\metro-hermes-compiler\src\emhermesc.js:77
          throw ex;
          ^

RuntimeError: abort(SyntaxError: src\app.scss: Call retries were exceeded). Build with -s ASSERTIONS=1 for more info.
    at process.abort (D:\work\gc-nativeapp-system\taro-rn-h5-mini-ts\node_modules\metro-hermes-compiler\src\emhermesc.js:402:15)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.7.0
error Command failed with exit code 7.

### 期望结果
正常build

### 实际结果
D:\work\gc-nativeapp-system\taro-rn-h5-mini-ts\node_modules\metro-hermes-compiler\src\emhermesc.js:77
          throw ex;
          ^

RuntimeError: abort(SyntaxError: src\app.scss: Call retries were exceeded). Build with -s ASSERTIONS=1 for more info.
    at process.abort (D:\work\gc-nativeapp-system\taro-rn-h5-mini-ts\node_modules\metro-hermes-compiler\src\emhermesc.js:402:15)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.7.0
error Command failed with exit code 7.

### 环境信息
```
👽 Taro v3.5.2


  Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.7.0 - D:\NODE\node.EXE
      Yarn: 1.22.19 - C:\Users\liuyusen\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.1 - D:\NODE\npm.CMD
```

**Comment by Aliom252181** [comment]
mac无此问题

**Comment by zhiqingchen** [comment]
![image](https://user-images.githubusercontent.com/1876158/184528699-17a2424e-48d9-451e-a897-d91766a06071.png)
是不是这个错误

**Comment by Aliom252181** [comment]
> ![image](https://user-images.githubusercontent.com/1876158/184528699-17a2424e-48d9-451e-a897-d91766a06071.png) 是不是这个错误

是

**Comment by zhiqingchen** [comment]
可能跟此pr相关。
https://github.com/NervJS/taro/pull/12150

@shinken008

**Comment by zhiqingchen** [comment]
> > ![image](https://user-images.githubusercontent.com/1876158/184528699-17a2424e-48d9-451e-a897-d91766a06071.png) 是不是这个错误
> 
> 是，我翻到之前出现过这个问题，我照着那个问题锁了下sass的版本，就不报错了。

锁到了哪个版本

**Comment by Aliom252181** [comment]
> > > ![image](https://user-images.githubusercontent.com/1876158/184528699-17a2424e-48d9-451e-a897-d91766a06071.png) 是不是这个错误
> > 
> > 
> > 是，我翻到之前出现过这个问题，我照着那个问题锁了下sass的版本，就不报错了。
> 
> 锁到了哪个版本

1.38.0

**Comment by shinken008** [comment]
1.37.5 有问题？已知的在 m1 1.38.0+ 会造成另外的问题

**Comment by tielan** [comment]
![image](https://user-images.githubusercontent.com/5001253/187723437-b824ef22-be97-4803-8611-9e561778a4ea.png)
1.38.0 也报错 taro 3.4.13

**Comment by SidneyLann** [comment]
Same issue in win11, node18.14.0 and taro3.6.1

**Comment by SidneyLann** [comment]
原来是项目里有两个sass版本导致的，加了下面就好了：
"resolutions": {
"sass": "1.50.0"

**Comment by zhiqingchen** [comment]
可以通过 yarn why sass 查看是否存在多个版本
