### ISSUE TITLE
componentDidUpdate中的prevProps值不对

### ISSUE THREAD

**Issue by lupingW** [NervJS/taro#12301]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/wangluping/component-update-prev-props-error.git](https://gitee.com/wangluping/component-update-prev-props-error.git)
**小程序基础库: 2.25.3**
**使用框架: React**

### 复现步骤
运行项目, 看打印台. 上一次props值和当前值一样

### 期望结果
上一次的props值和当前值不一样

### 实际结果
上一次props值和当前值一样

### 环境信息
```
👽 Taro v3.5.3


  Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\node\node.EXE
      npm: 6.14.14 - D:\node\npm.CMD
```

---
### 补充信息
componentWillReciveProps好像直接不执行

**Comment by Chen-jj** [comment]
https://stackoverflow.com/questions/54570157/this-props-and-prevprops-are-equal

**Comment by lupingW** [comment]
![f17917be92f26bb6d5e3ade40607cf4](https://user-images.githubusercontent.com/50098740/186063143-85fc49d0-1ec8-4379-b8ff-96a163ff0fea.jpg)
是不是mobx在感知数据变化时, 使用了forceupdate刷新页面导致的
