### ISSUE TITLE
taro 3.5.3 版本微信小程序转 taro 报 compiler is not defined 错误

### ISSUE THREAD

**Issue by gzwgq222** [NervJS/taro#12309]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/gzwgq222/weapp-convert-taro](https://github.com/gzwgq222/weapp-convert-taro)

**小程序基础库: 3.25.2**
**使用框架: React**

### 复现步骤
进入微信小程序项目根目录执行 taro convert

### 期望结果
正常 convert

### 实际结果
报 compiler is not defined 错误
![企业微信截图_16606414368466](https://user-images.githubusercontent.com/24493132/184856498-64de0ee3-9438-4556-8e1c-435baa042542.png)

### taro/cli
![企业微信截图_16606414313885](https://user-images.githubusercontent.com/24493132/184856398-93d2b07f-c461-42ee-a01e-781aa6dbe440.png)

```

**Comment by gzwgq222** [comment]
@Chen-jj

**Comment by gzwgq222** [comment]
降低到 3.4.7 版本就好的

![企业微信截图_1660652271222](https://user-images.githubusercontent.com/24493132/184880081-469efbfd-cd94-4448-8fd6-f27313c3e715.png)

**Comment by wjljack** [comment]
修改全局node_modules下面的`@tarojs/cli/dist/convertor/index.js`

```javascript
        creator.template(templateName, 'package.json.tmpl', pkgPath, {
            description,
            projectName,
            compiler: 'webpack5',  // 增加
            version,
            css: 'sass',
            typescript: false,
            template: templateName,
            framework: this.framework
        });
        creator.template(templateName, path.join('config', 'index.js'), path.join(configDir, 'index.js'), {
            date,
            compiler: 'webpack5', // 增加
            projectName,
            framework: this.framework
        });

...

        creator.template(templateName, path.join('src', 'index.html'), path.join(this.convertDir, 'index.html'), {
            projectName  // 增加
        });


```
