### ISSUE TITLE
是否能支持ant-design-mobile  v5 版本？

### ISSUE THREAD

**Issue by huanlirui** [NervJS/taro#12316]
### 这个特性解决了什么问题？
ant design系 是国内管理后台用的最多的吧？移动端缺少统一性。

### 这个 API 长什么样？
taro能够兼容ant-design-mobile  v5 版本

**Comment by huanlirui** [comment]
taro ui 缺少很多组件。而且太久没更新了吧。

taro 之前应该是首先支持react 的吧，但是国内vue系列比较多，导致现在react端能用的ui框架都没几个。甚至很多组件，这个框架有，那个框架又没有。如何取舍？

**Comment by mayacger** [comment]
我测试 ant-design-mobile v5 可以用，但是有些问题。
配置 html 插件 https://taro-docs.jd.com/taro/docs/use-h5
我发现是antd-m 的css变量没有生效，把global.css 中的变量拷贝出来，放在在app.scss中即可，同时还可以改theme
目前demo能跑起来，
Swiper 不能滑动不知道为什么。其他的还未测到。

**Comment by Chen-jj** [comment]
Taro 官方不会启动适配工作，如果社区有意愿进行适配，Taro 会积极配合。

Antd 是面向 Web 端的 UI 框架，[Web 和小程序环境仍有一些差异 Taro 是无法抹平的]( https://taro-docs.jd.com/taro/docs/use-h5)，所以会有部分 Antd 的组件可能会跑不起来，需要开发者进行调整。

**Comment by konka-king** [comment]
> 

大佬 taro-ui 我试了 好像不支持 taro 3.5 ，编译后🈶️很多问题，比如 AtButton  编译成 了view ,我想问下 taro-ui 以后会支持吗 taro3.5吗，如果支持 大约需要多久

**Comment by Chen-jj** [comment]
> @Chen-jj
> 
> 大佬小程序 taro-ui 我试了 好像不支持 taro 3.5 ，编译后🈶️很多问题，比如 AtButton 编译成 了view ,我想问下 taro-ui 目前有计划支持 taro3.5吗，如果支持 大约需要多久

@konka-king 另外提一下 issue 咯

**Comment by huanlirui** [comment]
> Taro 官方不会启动适配工作，如果社区有意愿进行适配，Taro 会积极配合。
> 
> Antd 是面向 Web 端的 UI 框架，[Web 和小程序环境仍有一些差异 Taro 是无法抹平的](https://taro-docs.jd.com/taro/docs/use-h5)，所以会有部分 Antd 的组件可能会跑不起来，需要开发者进行调整。

大佬，我说的是antd mobile啊，怎么会是面向web的。
