### ISSUE TITLE
3.5.3 TS errors

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro#12321]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: Vue 3**

### 复现步骤
升级到3.5.3之后出现ts编译错误（3.5.2没问题）：

```
✘ [ERROR] The character ">" is not valid inside a JSX element

    src/utils/util.ts:19:53:
      19 │ export const delayResolve = <T>(v: T, delay = 1000) => {
         ╵                                                      ^

  TypeScript's TSX syntax interprets arrow functions with a single generic type parameter as an
  opening JSX element. If you want it to be interpreted as an arrow function instead, you need to
  add a trailing comma after the type parameter to disambiguate:

    src/utils/util.ts:19:28:
      19 │ export const delayResolve = <T>(v: T, delay = 1000) => {
         │                             ~~~
         ╵                             <T,>

```

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
```
 Taro CLI 3.5.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.3 => 3.5.3 
      @tarojs/components: 3.5.3 => 3.5.3 
      @tarojs/plugin-framework-vue3: 3.5.3 => 3.5.3 
      @tarojs/runtime: 3.5.3 => 3.5.3 
      @tarojs/taro: 3.5.3 => 3.5.3 
      @tarojs/webpack5-runner: 3.5.3 => 3.5.3 
      babel-preset-taro: 3.5.3 => 3.5.3 
      eslint-config-taro: 3.5.3 => 3.5.3 
```
```

**Comment by ZakaryCode** [comment]
https://github.com/NervJS/taro/issues/12275#issuecomment-1211577324
