### ISSUE TITLE
套壳APP路由跳转延迟

### ISSUE THREAD

**Issue by ghost** [NervJS/taro#1232]
**问题描述**
通过 Taro 生成的 H5 代码放到 APP 中，路由跳转的时候会有一秒左右的延迟（点击按钮之后，一秒左右页面才会跳转）。

**期望行为**
和在网页中访问 H5 一样，点击按钮的时候页面立即跳转

**补充信息**
经过查询相关信息，一些答案是说移动端 click 时，屏幕会产生 200-300ms 的延时响应，可以使用 fastclick 之后，也没有解决这个问题。

**Comment by luckyadam** [comment]
这个感觉是 app 的问题吧

**Comment by negivup** [comment]
Native人员没有排查出问题，所以到这问一下有没有解决方案的。
最近这几天我再看看能不能通过其他方式解决这个问题吧
