### ISSUE TITLE
Taro v3.5.3 monorepo下小程序打包图片路径问题

### ISSUE THREAD

**Issue by hellowalker** [NervJS/taro#12322]
### 相关平台
微信小程序

**小程序基础库: 2.24.5**
**使用框架: React**

### monorepo目录结构

```
packages
├──pkg2
│   └── src
│      └── comp1
│           └── imgs
│
└── pkg1
    └── src
          └── page1
```

### 问题描述

- monorepo结构下，pkg1引用pkg2下组件comp1，comp1有图片资源；
- 3.4.12版本下小程序打包pkg1，相关图片会打到dist/weapp/_ /_ /pkg2/src/comp1/imgs/，
- 升级3.5.3版本，相关图片会打到dist/pkg2/src/comp1/imgs/，导致小程序找不到图片资源。

### 期望结果
正确解析路径

### 实际结果
[渲染层网络层错误] Failed to load local image resource......

### 环境信息
```
👽 Taro v3.5.3


  Taro CLI 3.5.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.3 => 3.5.3 
      @tarojs/components: 3.5.3 => 3.5.3 
      @tarojs/plugin-framework-react: 3.5.3 => 3.5.3 
      @tarojs/plugin-html: 3.5.3 => 3.5.3 
      @tarojs/react: 3.5.3 => 3.5.3 
      @tarojs/runtime: 3.5.3 => 3.5.3 
      @tarojs/taro: 3.5.3 => 3.5.3 
      @tarojs/webpack5-runner: 3.5.3 => 3.5.3 
      babel-preset-taro: 3.5.3 => 3.5.3 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 4.7.4

```

**Comment by Chen-jj** [comment]
@hellowalker 麻烦提供一下 demo

**Comment by hellowalker** [comment]
已解决：
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/25142334/190614730-c735714b-7627-4072-a71f-913c1cadf1f3.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/25142334/190614818-844f5c35-4b61-46a9-b4c2-0d6a800560aa.png">

wp5 assets图片路径处理和wp4的url-loader不一样了 可以通过assets的generator配置修复
