### ISSUE TITLE
Vue3 h5编译报错Module not found: Error: Can't resolve 'style-loader' 

### ISSUE THREAD

**Issue by yanbowe** [NervJS/taro#12325]
### 相关平台
H5

### 复现仓库
[https://github.com/yanbowe/taro-vue3-pinia](https://github.com/yanbowe/taro-vue3-pinia)
**浏览器版本: chrome 版本 103.0.5060.114（正式版本）**
**使用框架: Vue 3**

### 复现步骤
pnpm install 
pnpm dev:h5

### 期望结果
正常运行

### 实际结果
报错Module not found: Error: Can't resolve 'style-loader' 
![image](https://user-images.githubusercontent.com/43030980/185316761-9da3016d-7663-4129-9a3a-4b18167a5db7.png)

### 环境信息
```
👽 Taro v3.5.2


  Taro CLI 3.5.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.17.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.2 => 3.5.2 
      @tarojs/components: 3.5.2 => 3.5.2 
      @tarojs/helper: 3.5.2 => 3.5.2 
      @tarojs/plugin-html: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-alipay: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-jd: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-qq: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-swan: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-tt: 3.5.2 => 3.5.2 
      @tarojs/plugin-platform-weapp: 3.5.2 => 3.5.2 
      @tarojs/router: 3.5.2 => 3.5.2 
      @tarojs/runtime: 3.5.2 => 3.5.2 
      @tarojs/shared: 3.5.2 => 3.5.2 
      @tarojs/taro: 3.5.2 => 3.5.2 
      @tarojs/taro-h5: 3.5.2 => 3.5.2 
      babel-preset-taro: 3.5.2 => 3.5.2 
```

**Comment by ZakaryCode** [comment]
版本升级请参考相关[文档](https://nervjs.github.io/taro-docs/blog/2022/07/26/Taro-3.5#%E4%BA%94%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97)和 3.5 标准模板

**Comment by yanbowe** [comment]
> 版本升级请参考相关[文档](https://nervjs.github.io/taro-docs/blog/2022/07/26/Taro-3.5#%E4%BA%94%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97)和 3.5 标准模板

hi，我重新安装node_modules，并且对比升级所需要的依赖，还是会报错。

**Comment by yanbowe** [comment]
我只有h5运行不起来，微信小程序以及其他平台是可以正常运行的

**Comment by kevily** [comment]
安装下style-loader就好了
