### ISSUE TITLE
defineCustomElements 似乎有问题

### ISSUE THREAD

**Issue by notbucai** [NervJS/taro#12330]
### 相关平台
H5

**浏览器版本: Chrome 104.0.5112.79**
**使用框架: React**

### 复现步骤
<img width="613" alt="image" src="https://user-images.githubusercontent.com/32786133/185562962-a12980a3-4135-46ae-9878-ef11bcc03c34.png">

@tarojs/components/loader 

dist/esm/loader.js 文件中

```
// win 参数似乎没有使用
const defineCustomElements = (win,  options) => {
  if (typeof window === 'undefined') return Promise.resolve();
  return patchEsm().then(() => {
    return bootstrapLazy([...], options);
 }
}
```
<img width="692" alt="image" src="https://user-images.githubusercontent.com/32786133/185562780-fb26f2e2-5a42-446e-9674-6a9dfd2cd2d6.png">

### 期望结果
在 react-frame-component 中正确根据window进行处理

### 实际结果
没有效果

### 环境信息
```
Taro CLI 3.4.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.19.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.13 => 3.4.13 
      @tarojs/mini-runner: 3.4.13 => 3.4.13 
   

环境说明请忽略。

```

---
### 补充信息

我在个人项目中的 react-frame-component 中使用 @tarojs/componets 组件，但似乎defineCustomElements() 无法正确进行组件处理，查看dist代码好像参数重win没有进行向下传递。

**Comment by notbucai** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/32786133/185563999-58377bb8-13c7-4eb9-9925-751d7097bd46.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/32786133/185564052-83c2f1f4-9125-4c28-9ef9-11d12ea31f57.png">

**Comment by notbucai** [comment]
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/32786133/185563999-58377bb8-13c7-4eb9-9925-751d7097bd46.png">
> 
> <img alt="image" width="1089" src="https://user-images.githubusercontent.com/32786133/185564052-83c2f1f4-9125-4c28-9ef9-11d12ea31f57.png">

图一是在frame中调用，图二是在项目中使用

**Comment by ZakaryCode** [comment]
```js
const defineCustomElements = (win,  options) => {
  if (typeof window === 'undefined') return Promise.resolve();
  return patchEsm().then(() => {
    return bootstrapLazy([...], options);
 }
}
```

此处是 stencil 代码，看起来无甚问题

另外外部使用 `@tarojs/components` 参考此处文档 https://nervjs.github.io/taro-docs/docs/external-libraries

**Comment by notbucai** [comment]
> ```js
> const defineCustomElements = (win,  options) => {
>   if (typeof window === 'undefined') return Promise.resolve();
>   return patchEsm().then(() => {
>     return bootstrapLazy([...], options);
>  }
> }
> ```
> 
> 此处是 stencil 代码，看起来无甚问题
> 
> 另外外部使用 `@tarojs/components` 参考此处文档 https://nervjs.github.io/taro-docs/docs/external-libraries
<img width="614" alt="image" src="https://user-images.githubusercontent.com/32786133/187624250-84f1c2f1-ee20-4b76-adbf-9b3084645c41.png">

@ZakaryCode  我还是补充一下吧，虽然是stencil的代码。很明显参数中的`win`是没有被使用到的，所以实际上官方的外部使用的例子也是存在误导的。如果是我的理解有问题，请直接指正感激不尽。
<img width="845" alt="image" src="https://user-images.githubusercontent.com/32786133/187623985-aec19927-34b2-4d5f-b1ee-163bb54f6f03.png">
