### ISSUE TITLE
引入微信原生插件，无法捕获到triggerEvent 回调

### ISSUE THREAD

**Issue by huanlirui** [NervJS/taro#12338]
### 相关平台
微信小程序

**小程序基础库: 2.53.3**
**使用框架: React**

### 复现步骤
微信原生插件：https://github.com/Kujiale-Mobile/Painter  

//在taro 中引入使用原生插件

```
 const onImgOK = e => {
    console.log("e", e);
  };
  <painter palette={data} imgOK={onImgOK} />

```
原生插件中的方法：
```
 that.triggerEvent('imgOK', {
              path: filePath,
            });
```
永远都无法触发imgOK中的 console.log

### 期望结果
能够正常拿到 triggerEvent  回调

### 实际结果
无法触发 triggerEvent  回调

### 环境信息
```
👽 Taro v3.4.9


  Taro CLI 3.4.9 environment info:
    System:
      OS: macOS 11.6.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /var/folders/nk/qrzc3m19563_kzdntt60l1z40000gn/T/yarn--1661076172481-0.4262492190286773/node
      Yarn: 1.22.17 - /var/folders/nk/qrzc3m19563_kzdntt60l1z40000gn/T/yarn--1661076172481-0.4262492190286773/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.9 => 3.4.9 
      @tarojs/components: 3.4.9 => 3.4.9 
      @tarojs/mini-runner: 3.4.9 => 3.4.9 
      @tarojs/plugin-framework-react: 3.4.9 => 3.4.9 
      @tarojs/react: 3.4.9 => 3.4.9 
      @tarojs/runtime: 3.4.9 => 3.4.9 
      @tarojs/taro: 3.4.9 => 3.4.9 
      @tarojs/webpack-runner: 3.4.9 => 3.4.9 
      babel-preset-taro: 3.4.9 => 3.4.9 
      eslint-config-taro: 3.4.9 => 3.4.9 
      react: ^17.0.0 => 17.0.2 

✨  Done in 2.29s.
```

---
### 补充信息
微信原生插件：https://github.com/Kujiale-Mobile/Painter

**Comment by huanlirui** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/40491203/185786006-6a5354c9-3105-4939-b0a2-dd24a8b875d6.png">
在调试模式下，能够确定，原生插件中的方法正确执行了。可是并没有触发taro项目中绑定的imgOK方法

**Comment by Chen-jj** [comment]
@huanlirui 

小程序 **triggerEvent** 的事件名五花八门，例如：

`imgOK` `imgOk` `img-OK` 等，它们对应的小程序事件绑定语法分别是 `bindimgOK` `bindimgOk` `bindimg-OK`

而 JSX 的事件绑定语法只有 **onCamelCase** 一种，Taro 并不能知道开发者想要哪种小程序事件绑定语法。

所以先这样 hack 一下绕过吧：`<title onImgOK={this.onImgOk} bindimgOK></title>`

**Comment by FE-Sheldon** [comment]
我和楼主遇到了同样的问题，不过我使用的框架是Vue3，那么Vue3遇到这个问题应该如何hack？ @Chen-jj @huanlirui

**Comment by Howie126313** [comment]
> @huanlirui
> 
> 小程序 **triggerEvent** 的事件名五花八门，例如：
> 
> `imgOK` `imgOk` `img-OK` 等，它们对应的小程序事件绑定语法分别是 `bindimgOK` `bindimgOk` `bindimg-OK`
> 
> 而 JSX 的事件绑定语法只有 **onCamelCase** 一种，Taro 并不能知道开发者想要哪种小程序事件绑定语法。
> 
> 所以先这样 hack 一下绕过吧：`<title onImgOK={this.onImgOk} bindimgOK></title>`

这样写也不生效哇。。。。。

```
// page
<native-input onNativeinputfocus={() => {console.info('onNativeinputfocus');}} bindnativeinputfocus></native-input>

// 事件触发
<view>
    <input 
        placeholder='lalalalalalalalalall'
        selection-start="3" 
        selection-end="7" 
        adjust-position="{{false}}"
        confirm-hold="false" 
        confirm-type="send"
        bindfocus="handleFocus"/>
</view>

Component({
    properties: { },
    methods: {
        handleFocus(e) {
            console.info('handleFocus ------', e);
            this.triggerEvent('nativeinputfocus', e, { bubbles: true, capturePhase: true });
        }
    }
});

```
