### ISSUE TITLE
mobx  页面index.jsx  @inject('store')   X [ERROR] Unexpected "@"

### ISSUE THREAD

**Issue by lceihen** [NervJS/taro#12336]
### 相关平台
微信小程序

**小程序基础库: vscode build报错**
**使用框架: React**

### 复现步骤
直接安装 taro 3.5

### 期望结果
无报错

### 实际结果
报错

### 环境信息
```
👽 Taro v3.5.0


  Taro CLI 3.5.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - D:\lceihen\install\node\node\node.EXE
      Yarn: 1.22.10 - D:\lceihen\install\node\node\node_global\yarn.CMD
      npm: 8.1.4 - D:\lceihen\install\node\node\npm.CMD
```

**Comment by Chen-jj** [comment]
@lceihen 没有复现，请升级到最新版再试试，或提供完整可复现 demo

**Comment by ywanhzy** [comment]
我这边也是一样的错误   
```js
@inject("store")
@observer
```

[ERROR] Unexpected "@"

    src/components/banner/index_home.js:15:0:
      15 │ @inject("store")

✘ [ERROR] Expected identifier but found "@"

    src/store/enter-option.js:10:2:
      10 │   @observable

**Comment by QingyunYang** [comment]
装饰器报错，哪位有解决方案了吗？

**Comment by lisonge** [comment]
把 jsx 改成 tsx ，或者 把装饰器改成原始函数调用 ，这对我有效

**Comment by charsea** [comment]
同问，有 jsx 解决方案了吗

**Comment by lceihen** [comment]
看起来此issue大概率不会被修复,因为不影响到主流程的,我是这样解决的:在选择模板时不使用自带的mobx,选择cli安装完成后手动引入mobx6,目前没发现由于引入导致的bug

**Comment by yoyo837** [comment]
别急啊,才一天的issue, 挂几个月的issue老多了;

只要是问题, 应该支持的都可以尽量支持,member有时间会处理的, 也欢迎有意愿参与共建的提交PR;

**Comment by ChiJohn** [comment]
同问，有解决方案了吗？

**Comment by yoyo837** [comment]
Duplicate of https://github.com/NervJS/taro/issues/13007
