### ISSUE TITLE
ios百度APP内，使用 navigateTo 进行页面跳转，第一次可以正常跳转，之后没有正确跳转页面，停留在当前页

### ISSUE THREAD

**Issue by susuten** [NervJS/taro#12349]
### 相关平台
H5

### 复现仓库
[https://github.com/susuten/taro-demo](https://github.com/susuten/taro-demo)
**浏览器版本: 百度APP13.16.0.10**
**使用框架: React**

### 复现步骤
1. 在index页面点击“跳转User页面”，能正常跳转到user页面
2. 在user 页面再点击“跳转Index页面” 时，无法跳回 index页面

### 期望结果
能正常跳转页面

### 实际结果
第一次可以正常跳转，后面无法跳转，停留在第一次跳转之后的页面

### 环境信息
```
$ taro info
👽 Taro v3.3.3


  Taro CLI 3.3.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.7.5 - C:\Program Files\nodejs\npm.CMD

```

**Comment by ZakaryCode** [comment]
可升级版本修复该问题

**Comment by susuten** [comment]
> 可升级版本修复该问题

不考虑升级最新版本的话，可以升级哪个稳定版本呢？

**Comment by susuten** [comment]
> 可升级版本修复该问题

升级到了3.5.4，仍有这个问题，没有修复

**Comment by ZakaryCode** [comment]
> 升级到了3.5.4，仍有这个问题，没有修复

未能复现该问题，请考虑是否是依赖未更新对齐等问题。

如依旧可现，请提交详细 demo 或更多信息（比如对应浏览器环境、录制视频等）
