### ISSUE TITLE
taro 从3.1.0升到3.2.0报错 Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):

### ISSUE THREAD

**Issue by LLLLLLLX** [NervJS/taro#12348]
### 相关平台
微信小程序

**小程序基础库: 2.25.2**
**使用框架: React**

### 复现步骤
正常运行项目

### 期望结果
启动不报错

### 实际结果
不报错

### 环境信息
```
👽 Taro v3.4.11

publicPath:  undefined
PUBLIC_PATH:  "//test-hwc-gy1-bu-dx-bucket-deepexi.obs.cn-southwest-2.myhuaweicloud.com/dr-uat/mobile/code"

  Taro CLI 3.4.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\12726\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
🙅   编译失败. 2022/8/22 下午1:47:51

./node_modules/taro-cropper/dist/weapp/components/taro-cropper/index.tsx
Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: E:\project\deepexi-dm-mobile1\node_modules\taro-cropper\dist\weapp\components\taro-cropper\index.tsx: Unexpected reserved word 'interface'. (10:0)

   8 |
   9 |
> 10 | interface TaroCropperComponentProps {
     | ^
  11 |   cropperCanvasId: string,          // 画布id
  12 |   cropperCutCanvasId: string,       // 用于裁剪的canvas id
  13 |   width: number,                    // 组件宽度

监听文件修改中...
   9 |
> 10 | interface TaroCropperComponentProps {
     | ^
  11 |   cropperCanvasId: string,          // 画布id  12 |   cropperCutCanvasId: string,       // 用于裁剪的canvas id
  13 |   width: number,                    // 组件宽度

(node:27628) UnhandledPromiseRejectionWarning: [object Array]
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:27628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Chen-jj** [comment]
@LLLLLLLX 3.2 相比 3.1 只是增加了 RN 的适配，小程序没有改动。可以检查一下依赖安装是否正确，如果还有问题，请提供完整 demo
