### ISSUE TITLE
页面配置pages下backgroundColor不生效

### ISSUE THREAD

**Issue by gayshub** [NervJS/taro#12345]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/无，可以自己创建](https://github.com/无，可以自己创建)
**小程序基础库: 2.25.2**
**使用框架: React**

### 复现步骤
创建个页面，在index.config.ts里设置backgroundColor: '#3333'，不生效

### 期望结果
页面下的背景颜色改变

### 实际结果
未改变

### 环境信息
```
λ taro info
👽 Taro v3.5.2


  Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
```

**Comment by gayshub** [comment]
export default {
  navigationBarTitleText: '我的资料',
  backgroundColor: '#3333'
}

**Comment by Chen-jj** [comment]
@gayshub 这个是页面容器的背景色，不是页面的背景色。你真机往下拖动一下页面就明白了。Taro 正常地把配置编译到页面的 json 文件中，与 Taro 无关。

**Comment by JxJPu9bD** [comment]
> @gayshub 这个是页面容器的背景色，不是页面的背景色。你真机往下拖动一下页面就明白了。Taro 正常地把配置编译到页面的 json 文件中，与 Taro 无关。

那请问我应该如何设置页面的背景色呢?
尝试了设置window.backgroundColor也无效
