### ISSUE TITLE
自定义组件中redux连接编译错误

### ISSUE THREAD

**Issue by junhwong** [NervJS/taro#1234]
**问题描述**
小程序端：

```
错误  组件编译  组件src/components/layout.js编译失败！
{ SyntaxError: unknown: Unexpected token, expected { (6:7)
  4 | import { login } from "../actions/index.js";
  5 |
> 6 | export @connect(({ user }) => ({
    |        ^
  7 |   user
  8 | }), (dispatch, x) => ({
```

**复现步骤**
在自定义组件中连接（非页面），想要做一个通用的登录检查，诸如此类。

**系统信息**
 - Taro 版本 [1.1.8]，虽然不是最新但看了下github 没发现有此类问题的提交。

**Comment by 1021683053** [comment]
你这用法本身就是错的吧
![image](https://user-images.githubusercontent.com/7711802/48958954-32717380-ef9d-11e8-9fbd-1b94ed624396.png)

**Comment by junhwong** [comment]
我本身用法没有问题， 我说的是非page 组件

**Comment by junhwong** [comment]
当然这不符合react的标准，但并不妨碍它是个问题。

**Comment by junhwong** [comment]
另外，再支付宝小程序编译后，新加的包内容里的`@`并没有被替换。如dva。
我大致看了下源码，只找到两个地方。。。。 难以下手改和提PR了。
最后搞了个hack来解决：
```js
const { readFileSync, readdirSync, statSync, writeFileSync } = require('fs')

function resolveDir(path) {
    let files = readdirSync(path)
    files.forEach(it => {
        let file = path + '/' + it
        let state = statSync(file)
        if (state.isFile()) {
            replaceFile(file)
        }
        else if (state.isDirectory()) {
            resolveDir(file)
        }
    })
}
const reg = /\.\.\/\@babel/g
function replaceFile(file) {
    let content = readFileSync(file, { encoding: 'utf8' })
    if (reg.test(content) < 1) return
    console.log('准备替换文件:', file)
    content = content.replace(reg, '../_babel')
    writeFileSync(file, content, { encoding: 'utf8' })
}

resolveDir('./dist/npm')


```

**Comment by junhwong** [comment]
额，忘记说了，是最新版本 beta.2

**Comment by luckyadam** [comment]
最新版本编译支付宝小程序时，已经将路径中的 `@` 替换成了 `_`
另外 @1021683053 说的对，你的 `export` 写法是错的

**Comment by junhwong** [comment]
@luckyadam  路径那个问题我用的就是最新版本 v1.2.0-beta.2

另外，那个我的写法没问题，上面我贴的是taro编译报错的信息
我的写法是：
```js
@connect(...)
export class UILayout extends Component {
...
```

**Comment by junhwong** [comment]
我发现个有趣的问题（支付宝端里边，微信端还没调试），当然这个跟taro本身没关系，但可以给后来者减少入坑的机会。

直接这样写Layout 支付宝出问题，UILayout 这样就ok...
还有 props 里边传递函数 必须加前缀 onXX 这样的才可以。

**Comment by luckyadam** [comment]
> 我发现个有趣的问题（支付宝端里边，微信端还没调试），当然这个跟taro本身没关系，但可以给后来者减少入坑的机会。
> 
> 直接这样写Layout 支付宝出问题，UILayout 这样就ok...
> 还有 props 里边传递函数 必须加前缀 onXX 这样的才可以。

Layout 估计是命中了支付宝的关键字
props 传递函数文档中有注明  https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E4%BC%A0%E9%80%92%E5%87%BD%E6%95%B0%E5%B1%9E%E6%80%A7%E5%90%8D%E4%BB%A5-on-%E5%BC%80%E5%A4%B4

**Comment by luckyadam** [comment]
> @luckyadam 路径那个问题我用的就是最新版本 v1.2.0-beta.2

是加了哪个包路径没有替换？

**Comment by junhwong** [comment]
@luckyadam
😅 确实没看到那个 onXX的文档。

添加的包就是 davjs , 我现在把那个包删除了，不知道最新版还有问题没。

**Comment by luckyadam** [comment]
支付宝的问题，这个 commit 修复了
