### ISSUE TITLE
Error: resolve-url-loader: webpack misconfiguration, webpack or the upstream loader did not supply a source-map

### ISSUE THREAD

**Issue by yanbowe** [NervJS/taro#12364]
### 相关平台
H5

### 复现仓库
[https://github.com/yanbowe/nutui-report](https://github.com/yanbowe/nutui-report)
**浏览器版本: 版本 104.0.5112.101（正式版本） (x86_64)**
**使用框架: Vue 3**

### 复现步骤
pnpm install
pnpm  dev:h5
运行报错

### 期望结果
正常运行

### 实际结果
Error: resolve-url-loader: webpack misconfiguration
  webpack or the upstream loader did not supply a source-map
![image](https://user-images.githubusercontent.com/43030980/186143395-6eb27c7d-2307-4e88-9802-7568c405b478.png)

✖ Errors: 

ModuleBuildError: Module build failed (from ./node_modules/.pnpm/resolve-url-loader@4.0.0/node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  a valid source-map is not present (ensure preceding loaders output a source-map)

### 环境信息
```
👽 Taro v3.5.4


  Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.17.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.5.4 => 3.5.4 
      @tarojs/components: ^3.5.4 => 3.5.4 
      @tarojs/helper: ^3.5.4 => 3.5.4 
      @tarojs/plugin-framework-vue3: ^3.5.4 => 3.5.4 
      @tarojs/plugin-html: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-alipay: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-jd: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-qq: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-swan: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-tt: ^3.5.4 => 3.5.4 
      @tarojs/plugin-platform-weapp: ^3.5.4 => 3.5.4 
      @tarojs/plugin-vue-devtools: ^3.5.4 => 3.5.4 
      @tarojs/router: ^3.5.4 => 3.5.4 
      @tarojs/runtime: ^3.5.4 => 3.5.4 
      @tarojs/shared: ^3.5.4 => 3.5.4 
      @tarojs/taro: ^3.5.4 => 3.5.4 
      @tarojs/taro-h5: ^3.5.4 => 3.5.4 
      @tarojs/webpack5-runner: ^3.5.4 => 3.5.4 
      babel-preset-taro: ^3.5.4 => 3.5.4 
```

**Comment by yanbowe** [comment]
nutui组件库的问题

**Comment by wxxyanmei** [comment]
兄弟，你是怎么解决的？

**Comment by yanbowe** [comment]
> 兄弟，你是怎么解决的？

https://github.com/jdf2e/nutui/issues/1588
