### ISSUE TITLE
mobx 只支持5.x版本？不支持4.x?

### ISSUE THREAD

**Issue by LengYXin** [NervJS/taro#1237]
问题描述 低版本的ios手机系统不支持proxy 降低了版本到4.x发现状态更改后组件不会重新渲染

复现步骤 打包预览小程序

期望行为 是否支持4.x版本mobx?毕竟大多人手机系统。。。。

报错信息

![image](https://user-images.githubusercontent.com/19631404/48966606-b106f900-f00f-11e8-821b-43598a8c5293.png)

[这里请贴上你的完整报错截图或文字]

系统信息

操作系统: 
Taro 版本 
    "@tarojs/mobx": "^1.2.0-beta.2",
    "@tarojs/router": "^1.1.4",
    "@tarojs/taro": "^1.1.4",
    "@tarojs/taro-alipay": "^1.1.4",
    "@tarojs/taro-h5": "^1.1.4",
    "@tarojs/taro-swan": "^1.1.4",
    "@tarojs/taro-weapp": "^1.1.4",
    "mobx": "5.6.0",>降低版本后>4.6.0
Node.js 版本 [e.g. v9.0.0]
报错平台 [weapp ios系统9.3.2]
补充信息 计划支持4.x版本mobx?

**Comment by luckyadam** [comment]
收到~ 我们看一下
