### ISSUE TITLE
RN打包直接报错

### ISSUE THREAD

**Issue by poorel** [NervJS/taro#1238]
**问题描述**
打包运行报错（500 - "{\"originModulePath...），具体请看图片，求指导

**复现步骤**
![image](https://user-images.githubusercontent.com/28730190/48968175-41503880-f026-11e8-8d48-01f29541d142.png)
![image](https://user-images.githubusercontent.com/28730190/48968183-6644ab80-f026-11e8-8e83-e3438845e16d.png)

**期望行为**
期望能正常运行

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.9]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [RN]

**Comment by Pines-Cheng** [comment]
@poorel 就一个 500 错误吗？还有没有其他的报错信息？
