### ISSUE TITLE
MediaRecorder api错误

### ISSUE THREAD

**Issue by bwmgd** [NervJS/taro#12389]
### 相关平台
微信小程序

**小程序基础库: 2.22.0**
**使用框架: Vue 3**

### 复现步骤
微信官方文档参考:https://developers.weixin.qq.com/miniprogram/dev/api/media/media-recorder/wx.createMediaRecorder.html
该方法为双参
而Taro.createMediaRecorder()提供的是无参方法

### 期望结果
Taro提供的api文档应于微信官方一致

### 实际结果
Taro与微信官方api不一致

### 环境信息
```
👽 Taro v3.5.4


  Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
```

**Comment by Chen-jj** [comment]
@bwmgd 是 Taro 的类型提示出错，还是 API 调用失败呢？

**Comment by bwmgd** [comment]
> @bwmgd 是 Taro 的类型提示出错，还是 API 调用失败呢？

 是 Taro 的类型提示出错,使用微信官方api的双参即可正常使用
