### ISSUE TITLE
taro物料市场 不在维护了吗

### ISSUE THREAD

**Issue by dingshaohua-cn** [NervJS/taro#12384]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/dingshaohua-cn/taro-swiper-week](https://github.com/dingshaohua-cn/taro-swiper-week)
**小程序基础库: 3.5.3**
**使用框架: React**

### 复现步骤
我发版上去的 只有自己能看到 别人打开链接是404

### 期望结果
正常

### 实际结果
异常

### 环境信息
```
👽 Taro v3.5.3
```

**Comment by honlyHuang** [comment]
已经出来啦，物流市场需要简单的审核才放出来的咯

**Comment by dingshaohua-cn** [comment]
多谢
