### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by sufangyu** [NervJS/taro#12392]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/fangyu/taro-start](https://gitee.com/fangyu/taro-start)
**小程序基础库: 2.8.2**
**使用框架: React**

### 复现步骤
npm run dev:wapp

### 期望结果
process 有值

### 实际结果
ReferenceError: process is not defined

### 环境信息
```
Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.5.4 => 3.5.4 
      @tarojs/components: 3.5.4 => 3.5.4 
      @tarojs/mini-runner: 3.5.4 => 3.5.4 
      @tarojs/plugin-framework-react: ^3.5.4 => 3.5.4 
      @tarojs/react: 3.5.4 => 3.5.4 
      @tarojs/runtime: 3.5.4 => 3.5.4 
      @tarojs/taro: 3.5.4 => 3.5.4 
      @tarojs/webpack5-runner: ^3.5.4 => 3.5.4 
      babel-preset-taro: 3.5.4 => 3.5.4 
      eslint-config-taro: 3.5.4 => 3.5.4 
      react: ^18.2.0 => 18.2.0 
```

---
### 补充信息
compiler: {
    type: 'webpack5',
  },

webpack5 就会报错，webpack4 是可以正常的

**Comment by githubCK** [comment]
process.env.TARO_ENV、process.env. NODE_ENV是可以的，其他信息在前端环境下没有用了吧？process不知道为什么不给直接使用了，可能是考虑解构造成的问题https://taro-docs.jd.com/taro/docs/envs#processenvtaro_env

**Comment by sufangyu** [comment]
您的邮件已经收到，谢谢！

**Comment by ruoruochen** [comment]
遇到同样的问题，页面【pages/xx]错误: ReferenceError: process is not defined。目前无解

**Comment by githubCK** [comment]
@ruoruochen process.env.TARO_ENV、process.env. NODE_ENV是可以的，其他信息在前端环境下没有用了吧？process不知道为什么不给直接使用了，可能是考虑解构造成的问题https://taro-docs.jd.com/taro/docs/envs#processenvtaro_env

**Comment by songwenhui** [comment]
同样的问题，编译小程序没问题，编译H5报该错误，有解决办法吗？

**Comment by ruoruochen** [comment]
> 同样的问题，编译小程序没问题，编译H5报该错误，有解决办法吗？

可以试一下我上面的方案

**Comment by ruoruochen** [comment]
> 【🌟已解决】遇到同样的问题，页面【pages/xx]错误: ReferenceError: process is not defined。

已找到解决方案 ，在confIg/index.js中增加env: {
        BUILD_TYPE: JSON.stringify(process.env.BUILD_TYPE || ''),
    }, 重新npm run build:weapp既可使用process.env.BUILD_TYPE

**Comment by songwenhui** [comment]
> 

小程序打包本身是没问题的，H5改成你说的配置依然不行

**Comment by songwenhui** [comment]
> > 【🌟已解决】遇到同样的问题，页面【pages/xx]错误: ReferenceError: process is not defined。
> 
> 已找到解决方案 ，在config/index.js config对象中增加env: { BUILD_TYPE: JSON.stringify(process.env.BUILD_TYPE || ''), }, 重新npm run build:weapp既可使用process.env.BUILD_TYPE

小程序打包本身是没问题的，H5改成你说的配置依然不行

**Comment by sufangyu** [comment]
您的邮件已经收到，谢谢！
