### ISSUE TITLE
Taro 项目 jsx 无法格式化为双引号问题

### ISSUE THREAD

**Issue by liamwang** [NervJS/taro#1239]
**问题描述**
常规的 jsx 的元素属性用的是双引号，但使用 Taro CLI 创建的项目（我用的是 TypeScript 模板），在 VS Code IDE 中，jsx 的元素属性都会自动格式化为单引号。刚开始以为是我的 Prettier 插件设置的问题，其实不是，我的 React 项目单引号是会自动格式化为双引号的。

请问在哪里有 jsx 单/双引号的设置？ 各配置文件中好像并没找到此项设置，是我漏了什么吗？还是 Taro 脚手架内部封闭了此项设置？

**复现步骤**
在 tsx 文件中的如下代码：

```html
<View className="index">
    ...
</View>
```

格式化后，双引号变成了单引号：

```html
<View className='index'>
    ...
</View>
```
这和我的 React 项目的代码风格不一致。

我做了以下尝试都不能解决问题：

1. 尝试了在 `tsconfig.json` 文件增加如下配置：

```text
"quotemark": [true, "single", "jsx-double"]
```

2. 尝试了在 User Settings 中增加如下配置：

```text
"prettier.jsxSingleQuote": false
```

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 1.2.0-beta.1
 - Node.js 版本 v10.3.0
 - 报错平台 [h5, weapp]

**Comment by luckyadam** [comment]
在 Taro 中建议 JSX 中使用单引号

**Comment by mytharcher** [comment]
That's a really bad practice to use single quote in JSX properties. I vote down this.

**Comment by georgezouq** [comment]
Any idea how to fix this? @luckyadam @liamwang
