### ISSUE TITLE
style内嵌对象解析

### ISSUE THREAD

**Issue by lambdaxs** [NervJS/taro#124]
![image](https://user-images.githubusercontent.com/12015791/41453426-515c30c4-70a8-11e8-9a36-614311eada6f.png)

![image](https://user-images.githubusercontent.com/12015791/41453433-57a92504-70a8-11e8-94c7-d9429b24ed5f.png)

style样式以object变量的形式传入的时候，解析为[Object object]，必须写成字符串才生效。。。。
这不是我认识的react 🤦‍♀️

**Comment by luckyadam** [comment]
小程序不支持支持 style 传对象

**Comment by lambdaxs** [comment]
1

**Comment by yuche** [comment]
0.0.69 开始已经支持

**Comment by Leadrive** [comment]
@yuche 请问支持对象，是支持到什么程度呢？
这种写法呢？
<View style={{display: flex, flex-direction: row, margin-left: 2px}} />
由于flex-direction中间有-，会报错。
另外：
<View style={{display: flex, flex-direction: row, height: (items.length / count)*lineHeight}} />
这种表达式的方式呢？

**Comment by luckyadam** [comment]
```
 'flex-direction': row
```
