### ISSUE TITLE
npm run build:lark 报错:  Maximum call stack size exceeded RangeError: Maximum call stack size exceeded     at RegExp.test (<anonymous>)

### ISSUE THREAD

**Issue by zhangshichuan** [NervJS/taro#12400]
### 相关平台
飞书小程序

### 复现仓库
[https://github.com/zhangshichuan/taro-lark-error](https://github.com/zhangshichuan/taro-lark-error)

**使用框架: React**

### 复现步骤
npm run build:lark

### 期望结果
 正常编译通过

### 实际结果
Maximum call stack size exceeded RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)

### 环境信息
```
👽 Taro v3.4.12


  Taro CLI 3.4.12 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.6.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.21.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.13 => 3.4.13 
      @tarojs/mini-runner: 3.4.13 => 3.4.13 
      @tarojs/plugin-framework-react: 3.4.13 => 3.4.13 
      @tarojs/react: 3.4.13 => 3.4.13 
      @tarojs/runtime: 3.4.13 => 3.4.13 
      @tarojs/taro: 3.4.13 => 3.4.13 
      @tarojs/webpack-runner: 3.4.13 => 3.4.13 
      babel-preset-taro: 3.4.13 => 3.4.13 
      eslint-config-taro: 3.4.13 => 3.4.13 
      react: ^17.0.0 => 17.0.2 
      taro-ui: 3.1.0-beta.2 => 3.1.0-beta.2 

```

---
### 补充信息
npm run dev:lark 没有任何问题,  热更新也没问题. 需要上线的时候执行 npm run build:lark 就报错了

**Comment by Chen-jj** [comment]
@zhangshichuan 意思是只有真机运行报错吗？

**Comment by zhangshichuan** [comment]
> @zhangshichuan 意思是只有真机运行报错吗？

不是, 是 npm run build:lark 这个运行报错, build 不起

**Comment by zhangshichuan** [comment]
无法正常编译

**Comment by zhangshichuan** [comment]
问题解决了, 因为 css 里面设置背景图用 background: url('')直接引入的 assets 里面的大图片, 导致 CssoWebpackPlugin 在处理图片的时候栈溢出,  把 url 的本地图片地址更换为 cdn 图片链接后就能 build 成功了
