### ISSUE TITLE
Taro 利用配置项引入第三方原生组件的问题

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#1241]
一开始的目的是想引入 [wemark](https://github.com/TooBug/wemark) 这个库。

但是发现如果有一个单独的 wxss 文件，即使在另一个 wxss 里 import 了，也无法编译到位。所以只能用 copy 的配置办法来引入组件，看起来也是比较稳定的。[相关 issue](https://github.com/TooBug/wemark/issues/36#issuecomment-427369261)。

但是最近（我现在用的是 1.2.0-beta.2）发现，好像 Taro 即使在 copy 有配置目录时，也会再 copy 之后重新编译一遍相关文件？导致一些很难预测的错误发生。最终解决方法是再加上 compile 的 exclude 项。 [相关 issue](https://github.com/TooBug/wemark/issues/36#issuecomment-441408441)

不知道这个问题方不方便解决。

听说以后会有组件 taro 化，期待一下～

**Comment by Songkeys** [comment]
最新问题总结：https://github.com/TooBug/wemark/issues/36#issuecomment-462662306

**Comment by shenghanqin** [comment]
可以尝试最新的Taro版本，看是否还有这个问题。
