### ISSUE TITLE
偶现页面（子组件） useReady 不触发

### ISSUE THREAD

**Issue by TheKonka** [NervJS/taro#12424]
### 相关平台
微信小程序

**小程序基础库: 2.24.5**
**使用框架: React**

### 复现步骤
在tabbar页面自定义tabbar组件，页面和组件内部的 ```useReady```  hook 偶现不触发

### 期望结果
useReady 正常触发

### 实际结果
useReady 偶现不触发

### 环境信息
```

  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
    npmPackages:
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^18.2.0 => 18.2.0 
```

**Comment by konka-king** [comment]
![image](https://user-images.githubusercontent.com/22173084/188072418-7cb04e16-3919-49e7-8fcd-d070e38def94.png)
![image](https://user-images.githubusercontent.com/22173084/188072458-c9843c39-c179-4cd3-83cc-1db2632e065c.png)
![image](https://user-images.githubusercontent.com/22173084/188072473-7cdc5960-22e9-4866-b039-5bc5a184a676.png)

**Comment by konka-king** [comment]
应该跟组件没有关系，是整个页面的```useReady``` hook 都没触发

**Comment by xin2014** [comment]
useReady 没触发
useLoad 触发了吗
你为什么确定是 bug

**Comment by konka-king** [comment]
> useReady 没触发 useLoad 触发了吗 你为什么确定是 bug

useLoad 触发了。
为什么确定是bug ?  页面的 useReady 不触发 ，这还不叫 bug ?

**Comment by Chen-jj** [comment]
麻烦提供一下 demo

**Comment by huiergo** [comment]
这个问题解决了吗

**Comment by huiergo** [comment]
这个在v3.4.x的时候还是好使的， 然后到v3.5.7就不好使了

**Comment by huiergo** [comment]
> 

OnReady在ios真机上不调用， 而在微信开发工具 上是调用的 ，代码很简单 
class First extends Component {
onReady() {
    console.log('【onReady】')
  }
}

**Comment by sorryljt** [comment]
> 这个在v3.4.x的时候还是好使的， 然后到v3.5.7就不好使了

我也遇到这个问题了，好无语，在开发工具上好使，到了真机就不触发了

**Comment by lanxuexing** [comment]
目前我们也遇到了，在抖音小程序里边，使用iPhone手机真机，出现的频率很高，比较难受，希望是能尽快修复（PS：补充一下，升级到3.5.11依然存在，可以尝试在入口文件里调用这个useReady复现这个问题）

**Comment by Chen-jj** [comment]
@TheKonka @lanxuexing @huiergo @sorryljt 感谢反馈！调查后发现是 React18 会导致的问题，将在 Taro v3.5.12 修复。

**Comment by vivialex** [comment]
目前看 3.6.28还是会出现这个问题

**Comment by vivialex** [comment]
3.6.28还是会出现这个问题 @Chen-jj

**Comment by liu-zhi-fei** [comment]
3.6.30还是会出现这个问题 @Chen-jj
