### ISSUE TITLE
包管理工具支持pnpm

### ISSUE THREAD

**Issue by tzwhyqq** [NervJS/taro#12426]
### 这个特性解决了什么问题？
现在包管理工具用的是npm跟 yarn ，现在已经慢慢都切换到 pnpm。 后续会支持吗。

### 这个 API 长什么样？
支持 pnpm 管理

**Comment by sushi-su** [comment]
[3.5 之后已经支持](https://github.com/NervJS/taro/releases/tag/v3.5.0)
