### ISSUE TITLE
Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by Honye** [NervJS/taro#12420]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: Vue 3**

### 复现步骤
使用 Taro 3.5.5 创建 TS Vue3 新项目，无需修改任何程序直接构建支付宝小程序，使用小程序开发者工具打开代码即可看到错误

```
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at (index):6:994
    at Array.forEach (<anonymous>)
    at g ((index):6:185)
    at m ((index):6:973)
    at M.init ((index):6:9020)
    at M.x ((index):6:2019)
    at new M ((index):6:4623)
    at y ((index):6:2076)
    at new ia ((index):6:7528)
    at new ha ((index):6:7309)
```

### 期望结果
支付宝小程序正常构建并可上传访问

### 实际结果
构建后不可预览、不可上传

### 环境信息
```
👽 Taro v3.5.5


  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-vue3: 3.5.5 => 3.5.5 
      @tarojs/plugin-html: ^3.5.5 => 3.5.5 
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/service: ^3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/taro-h5: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
```

**Comment by Chen-jj** [comment]
@Honye 没有复现。创建项目的选项都列一下，最好提供一下 demo

**Comment by Honye** [comment]
**复现步骤：**

```bash
# 不要修改项目名
pnpm --package=@tarojs/cli dlx taro init miniapp-mth-alipay
```

```bash
cd miniapp-mth-alipay
pnpm build:alipay
```

使用支付宝小程序开发者工具打开项目 dist 目录

<img width="776" alt="错误截图" src="https://user-images.githubusercontent.com/19296374/188355292-9cf07e8e-4271-496e-b457-6d2d3bafded9.png">

**临时解决方案：**

修改项目文件夹名后可正常构建

将项目文件夹 `miniapp-mth-alipay` 改为 `miniapp-taro-alipay` 后再构建可正常使用

**Comment by shenstar** [comment]
最新版本3.6.1还是有这个问题，项目名称要带有taro才能编译成功

**Comment by MortyZhoubo** [comment]
![1](https://user-images.githubusercontent.com/80514041/220503907-6b7726f9-663a-447c-8f4e-e04036cc73fc.png)
![image](https://user-images.githubusercontent.com/80514041/220504003-da680410-9383-4806-9cb3-43ec2b481bf6.png)
目前碰到相同问题，修改报名带有taro依然不成功
![image](https://user-images.githubusercontent.com/80514041/220504092-17f11228-b135-4038-875e-7b87c96ba7ca.png)

**Comment by lindingfeng** [comment]
@Chen-jj 大半年了，这个问题还是没有修复？？只要项目名不带taro的编译到支付宝小程序都报错Cannot read properties of null (reading 'addEventListener')
![BB8A0F90-ADB7-46e9-A6B1-798524E57C8B](https://user-images.githubusercontent.com/26541555/230291099-bd70d6a1-ed4c-40b7-beda-b2757948d243.png)

**Comment by xuanzebin** [comment]
> @Chen-jj
> 
> **复现步骤：**
> 
> ```shell
> # 不要修改项目名
> pnpm --package=@tarojs/cli dlx taro init miniapp-mth-alipay
> ```
> 
> ```shell
> cd miniapp-mth-alipay
> pnpm build:alipay
> ```
> 
> 使用支付宝小程序开发者工具打开项目 dist 目录
> 
> <img alt="错误截图" width="776" src="https://user-images.githubusercontent.com/19296374/188355292-9cf07e8e-4271-496e-b457-6d2d3bafded9.png">
> 
> **临时解决方案：**
> 
> 修改项目文件夹名后可正常构建
> 
> 将项目文件夹 `miniapp-mth-alipay` 改为 `miniapp-taro-alipay` 后再构建可正常使用

按照这个步骤没有复现出来，如果还有问题的话，能否提供一个 demo，以便我们排查问题，感谢反馈~

**Comment by lindingfeng** [comment]
> > @Chen-jj
> > **复现步骤：**
> > ```shell
> > # 不要修改项目名
> > pnpm --package=@tarojs/cli dlx taro init miniapp-mth-alipay
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > cd miniapp-mth-alipay
> > pnpm build:alipay
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用支付宝小程序开发者工具打开项目 dist 目录
> > <img alt="错误截图" width="776" src="https://user-images.githubusercontent.com/19296374/188355292-9cf07e8e-4271-496e-b457-6d2d3bafded9.png">
> > **临时解决方案：**
> > 修改项目文件夹名后可正常构建
> > 将项目文件夹 `miniapp-mth-alipay` 改为 `miniapp-taro-alipay` 后再构建可正常使用
> 
> 按照这个步骤没有复现出来，如果还有问题的话，能否提供一个 demo，以便我们排查问题，感谢反馈~

@xuanzebin 
跑下这个Demo看行不行，我这边编译后支付宝还是报错
https://github.com/lindingfeng/test-project
node -> v16.14.2
pnpm -> 7.27.0
taro -> 3.6.4

**Comment by Honye** [comment]
> > @Chen-jj
> > **复现步骤：**
> > ```shell
> > # 不要修改项目名
> > pnpm --package=@tarojs/cli dlx taro init miniapp-mth-alipay
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > cd miniapp-mth-alipay
> > pnpm build:alipay
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用支付宝小程序开发者工具打开项目 dist 目录
> > <img alt="错误截图" width="776" src="https://user-images.githubusercontent.com/19296374/188355292-9cf07e8e-4271-496e-b457-6d2d3bafded9.png">
> > **临时解决方案：**
> > 修改项目文件夹名后可正常构建
> > 将项目文件夹 `miniapp-mth-alipay` 改为 `miniapp-taro-alipay` 后再构建可正常使用
> 
> 按照这个步骤没有复现出来，如果还有问题的话，能否提供一个 demo，以便我们排查问题，感谢反馈~

刚刚又试了下，按照这个步骤是可以复现的

| 应用 | 版本 |
| ----- | ---- |
| Taro | v3.6.4 |
| NodeJS | v18.14.2 |
| pnpm | v18.4.2 |
| OS | Windows 10 22H2 |
| 小程序开发者工具 | v3.1.3 |

**Comment by eiinu** [comment]
遇到了相同的报错信息，尝试修改文件夹名后依然没有成功🤷🏻‍♀️
Taro 3.6.2
Node 16.16.0
pnpm 8.1.0

**Comment by xuanzebin** [comment]
> > > @Chen-jj
> > > **复现步骤：**
> > > ```shell
> > > # 不要修改项目名
> > > pnpm --package=@tarojs/cli dlx taro init miniapp-mth-alipay
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > cd miniapp-mth-alipay
> > > pnpm build:alipay
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 使用支付宝小程序开发者工具打开项目 dist 目录
> > > <img alt="错误截图" width="776" src="https://user-images.githubusercontent.com/19296374/188355292-9cf07e8e-4271-496e-b457-6d2d3bafded9.png">
> > > **临时解决方案：**
> > > 修改项目文件夹名后可正常构建
> > > 将项目文件夹 `miniapp-mth-alipay` 改为 `miniapp-taro-alipay` 后再构建可正常使用
> > 
> > 
> > 按照这个步骤没有复现出来，如果还有问题的话，能否提供一个 demo，以便我们排查问题，感谢反馈~
> 
> @xuanzebin 跑下这个Demo看行不行，我这边编译后支付宝还是报错 https://github.com/lindingfeng/test-project node -> v16.14.2 pnpm -> 7.27.0 taro -> 3.6.4

依然没有复现，但找到了相关的问题，麻烦尝试一下或许可以解决问题~ #11133 

<img width="867" alt="image" src="https://user-images.githubusercontent.com/38971117/230811546-4667b48f-41a5-4e2d-8b5c-4c77094b4a5f.png">
