### ISSUE TITLE
postcss.pxtransform.config.baseFontSize 参数无效

### ISSUE THREAD

**Issue by linhaobin** [NervJS/taro#12449]
### 相关平台
微信小程序

### 复现仓库
[https://gith](https://gith)
**小程序基础库: **
**使用框架: React**

### 复现步骤
```js
cosnt config = {
  h5: {
    alias,
    postcss: {
      pxtransform: {
        enable: true,
        config: {
          baseFontSize: 16,
        },
      },
}
```

### 期望结果
baseFontSize=16

### 实际结果
baseFontSize=undefined

### 环境信息
```
👽 Taro v3.5.0

```

### 可能影响的代码

- 看起来这里有问题
https://github.com/NervJS/taro/blob/48d979c4b9836292aa557ba0bb364ae9f60c9595/packages/postcss-pxtransform/index.js#L44

- 少了括号？
```js
const baseFontSize = options.baseFontSize || (options.minRootSize >= 1 ? options.minRootSize : 20)
```

**Comment by FE92star** [comment]
看起来是这里取值的问题，可以提一个pr
