### ISSUE TITLE
app.tsx里面的tabBar是否支持动态写入

### ISSUE THREAD

**Issue by anshixiaobai** [NervJS/taro#1244]
app.tsx文件里面  
config: Config = { 
     tabBar：{
         text:  (function(){ return 'abc' })()
    } 
}

或者说 text 是否支持动态写入

**Comment by anshixiaobai** [comment]
tabBar: {
      color: '#999',
      selectedColor: '#CF9C20',
      backgroundColor: '#fff',
      list: [
        {
          iconPath: 'assets/image/tabbar/icon-home.png',
          pagePath: 'pages/index/index',
          selectedIconPath: 'assets/image/tabbar/icon-home-shi.png',
          text: (function () { return '123123' })()
        },
        {
          iconPath: 'assets/image/tabbar/icon-my.png',
          pagePath: 'pages/my/index',
          selectedIconPath: 'assets/image/tabbar/icon-my-shi.png',
          text: '我的'
        }
      ]
    }

 这样写入无效, 但是如果实在一个简单的对象里面  text方法是闭包得的话  他会立即执行

**Comment by luckyadam** [comment]
不支持，只能写静态的
