### ISSUE TITLE
百度小程序中调用 getLaunchOptionsSync 这个api ，内部报错 导致程序异常

### ISSUE THREAD

**Issue by zht0102** [NervJS/taro#12446]
### 相关平台
百度小程序

**小程序基础库: 3.540.7**
**使用框架: React**

### 复现步骤
const appLaunchParams = getLaunchOptionsSync()
报错信息如下：
common.js:1061 Uncaught (in promise) TypeError: Object(...) is not a function
    at _callee$ (common.js:1061)
    at tryCatch (vendors.js:1746)
    at Generator._invoke (vendors.js:1726)
    at Generator.next (vendors.js:1777)
    at asyncGeneratorStep (vendors.js:1187)
    at _next (vendors.js:1209)
    at vendors.js:1216
    at new Promise (<anonymous>)
    at vendors.js:1205
    at commonRequest (common.js:1137)

### 期望结果
程序运行正常

### 实际结果
编译报错

### 环境信息
```
👽 Taro v3.5.0


  Taro CLI 3.5.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.12 => 3.4.12 
      @tarojs/components: 3.4.12 => 3.4.12 
      @tarojs/mini-runner: 3.4.12 => 3.4.12 
      @tarojs/plugin-framework-react: 3.4.12 => 3.4.12 
      @tarojs/react: 3.4.12 => 3.4.12 
      @tarojs/runtime: 3.4.12 => 3.4.12 
      @tarojs/taro: 3.4.12 => 3.4.12 
      @tarojs/webpack-runner: 3.4.12 => 3.4.12 
      babel-preset-taro: 3.4.12 => 3.4.12 
      eslint-config-taro: 3.4.12 => 3.4.12 
      react: ^17.0.2 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.7.4

```

**Comment by yoyo837** [comment]
ref: https://github.com/NervJS/taro/issues/12387

**Comment by ZakaryCode** [comment]
> ref: #12387

这里无关联

**Comment by Chen-jj** [comment]
@zht0102 使用 `onLauch` 生命周期函数的参数代替吧，百度小程序没有提供这个 API。
