### ISSUE TITLE
taro3.5.5 taro-ui 3.1.0-beta.3 版本下 rem转换过大    并且组件样式丢失或错误  

### ISSUE THREAD

**Issue by liuhui1999** [NervJS/taro#12440]
### 相关平台
H5

### 复现仓库
[https://gitee.com/Allight/taro-problem-recurrence.git](https://gitee.com/Allight/taro-problem-recurrence.git)
**浏览器版本: Chrome 104.0.5112.102**
**使用框架: React**

### 复现步骤
yarn install    -> yarn dev:h5

### 期望结果
702px应该无法占满全屏

### 实际结果
占满全屏

### 环境信息
```
 Taro CLI 3.5.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\10037\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by juzijun2020** [comment]
我的环境是taro 3.5.5 + nutui-taro 3.2.1，也是rem转换变大了(12px 在 taro 3.4 下是0.512rem，在taro3.5下是0.6rem)，导致整个页面布局都变大了，望尽快修复，谢谢

**Comment by CaiDingxian** [comment]
可以尝试将HTML模板index.html中的rem脚本替换为<script><%= htmlWebpackPlugin.options.script %></script>（官方文档中未说明，这段代码Copy自taro-cli模板中，更新版本时，需要手动更新此index.html）

**Comment by ZakaryCode** [comment]
> 我的环境是taro 3.5.5 + nutui-taro 3.2.1，也是rem转换变大了(12px 在 taro 3.4 下是0.512rem，在taro3.5下是0.6rem)，导致整个页面布局都变大了，望尽快修复，谢谢

rem 转换变大，但是实际上值是依托于 designWidth，如果该参数值为 640，虽然 rem 值变大，但是由于根节点上设置的 font-size 不同，实际大小是一致的。
