### ISSUE TITLE
使用vue-devtools 闪退且报错

### ISSUE THREAD

**Issue by JuYiYang** [NervJS/taro#12452]
### 相关平台
微信小程序

**小程序基础库: 2.25.4**
**使用框架: Vue 3**

### 复现步骤
npm i @tarojs/plugin-vue-devtools
 config/index.js   plugins: ['@tarojs/plugin-vue-devtools'],
 

### 期望结果
正常且稳定的打开

### 实际结果
打开不到一秒 就退出了devtools 且控制台报错
 throw new _ValidationError.default(errors, schema, configuration);
          ^

ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'provide'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
   -> Options object as provided by the user.
   For typos: please correct them.

### 环境信息
```
Taro v3.5.4


提示  正在启动 vue-devtools...


  Taro CLI 3.5.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - D:\npm.CMD

```

---
### 补充信息
我需要看到页面的数据源

**Comment by Chen-jj** [comment]
@JuYiYang 感谢反馈，vue devtools 的 taro 插件需要兼容 Webpack5
