### ISSUE TITLE
h5 从非tabbar页面回跳到tabbar页面，点击浏览器返回按钮页面白屏

### ISSUE THREAD

**Issue by bluescurry** [NervJS/taro#12455]
### 相关平台
H5

### 复现仓库
[https://github.com/bluescurry/taro-debug](https://github.com/bluescurry/taro-debug)
**浏览器版本: Chrome 104.0.5112.101**
**使用框架: React**

### 复现步骤
1. 从首页点击“跳转到商品页”进入商品页
2. 在商品页点击“点击返回首页”返回首页
3. 在点击浏览器返回

### 期望结果
直接从商品页返回首页

### 实际结果
又打开了一个首页地址，点浏览器返回就返回到了上一个首页，并且白屏了

### 环境信息
```
👽 Taro v3.4.8

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.4.8 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.8 => 3.4.8
      @tarojs/components: 3.4.8 => 3.4.8
      @tarojs/mini-runner: 3.4.8 => 3.4.8
      @tarojs/plugin-framework-react: 3.4.8 => 3.4.8
      @tarojs/react: 3.4.8 => 3.4.8
      @tarojs/runtime: 3.4.8 => 3.4.8
      @tarojs/taro: 3.4.8 => 3.4.8
      @tarojs/webpack-runner: 3.4.8 => 3.4.8
      babel-preset-taro: 3.4.8 => 3.4.8
      eslint-config-taro: 3.4.8 => 3.4.8
      react: ^17.0.0 => 17.0.2
```

---
### 补充信息
从商品页返回首页是通过 switchTab 跳转的，就会有问题，通过 navigateBack 回跳是可以的，但是这种做法在小程序是不行的，会报错，tabbar 页面只能通过 switchTab 跳转。
这里有录屏：
![录屏](https://user-images.githubusercontent.com/19237129/188923509-5d040f31-76b7-4225-92fb-8bcbc1d8acf6.gif)

**Comment by Lycyc** [comment]
我也是  用tabBar白屏  是因为外层的.taro-page 的display:none 没有删除  不知道怎么解决

**Comment by ZakaryCode** [comment]
可尝试升级版本修复该问题

**Comment by bluescurry** [comment]
> 可尝试升级版本修复该问题

请问要升级到什么版本？

**Comment by liuliuna** [comment]
这个问题目前修复了吗 我看还是open状态

**Comment by liuliuna** [comment]
> > 可尝试升级版本修复该问题
> 
> 要升级到什么版本？

老哥解决了吗这个

**Comment by bluescurry** [comment]
> > > 可尝试升级版本修复该问题
> > 
> > 
> > 要升级到什么版本？
> 
> 老哥解决了吗这个

没解决，我升级到了3.4.x的最新版本还是不行，没试升到3.5行不行，因为升3.5改动会比较大

**Comment by Lycyc** [comment]
抱歉&nbsp; 工作没用这个邮箱才看到&nbsp; ***@***.***/router":"2.2.14",希望对你有帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro] h5 从非tabbar页面回跳到tabbar页面，点击浏览器返回按钮页面白屏 (Issue #12455)





   
可尝试升级版本修复该问题
  
要升级到什么版本？
  
老哥解决了吗这个
