### ISSUE TITLE
designWidth 设置 function，校验配置的协议报错

### ISSUE THREAD

**Issue by yzw7489757** [NervJS/taro#12463]
### 相关平台
H5

**浏览器版本: 未至运行**
**使用框架: React**

### 复现步骤
设置config/index.js
``` js
config = {
   designWidth(input) {
    if (input.file.replace(/\\ /g, '/').indexOf('@xy/xxx') > -1) {
      return 375
    }
    return 750
  },
}
```

``` bash
yarn dev:h5
```

### 期望结果
@xy/xxx 设计单位变更为 375

### 实际结果
Taro 配置有误，请检查！ (/Users/xxx/config/index.js)
  [✗] designWidth 应该为一个数字

### 环境信息
```
👽 Taro v3.5.3


  Taro CLI 3.5.3 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.2/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.7 => 3.4.7 
      @tarojs/components: 3.4.7 => 3.4.7 
      @tarojs/mini-runner: 3.4.7 => 3.4.7 
      @tarojs/react: 3.4.7 => 3.4.7 
      @tarojs/rn-runner: 3.4.7 => 3.4.7 
      @tarojs/router: 3.4.7 => 3.4.7 
      @tarojs/runtime: 3.4.7 => 3.4.7 
      @tarojs/taro: 3.4.7 => 3.4.7 
      @tarojs/taro-rn: 3.4.7 => 3.4.7 
      @tarojs/webpack-runner: 3.4.7 => 3.4.7 
      babel-preset-taro: 3.4.7 => 3.4.7 
      eslint-config-taro: 3.4.7 => 3.4.7 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.66.4 => 0.66.4 
```
![image](https://user-images.githubusercontent.com/28922129/189142715-cf27a7dc-79df-4f2a-b0d4-27137ce00b31.png)

**Comment by yzw7489757** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/28922129/189142947-eca57d1e-93dd-4227-abd6-6e292d2531b8.png">

**Comment by konka-king** [comment]
https://github.com/NervJS/taro/commit/7cb197a9623e2cafa91cb3861087dd1a9ff812eb

#11952

升级到3.4.13看看

**Comment by ZakaryCode** [comment]
文档错误，已经更新

> 请保持 cli 和项目内版本依赖一致

**Comment by TheKonka** [comment]
> 文档错误，已经更新
> 
> > 请保持 cli 和项目内版本依赖一致

文档咋打不开了，哥
![image](https://user-images.githubusercontent.com/22173084/190036206-f3366384-9258-440c-8623-a99a5c4130ee.png)

**Comment by ZakaryCode** [comment]
> > 文档错误，已经更新
> > > 请保持 cli 和项目内版本依赖一致
> 
> 文档咋打不开了，哥 ![image](https://user-images.githubusercontent.com/22173084/190036206-f3366384-9258-440c-8623-a99a5c4130ee.png)

多了 README ，删了就行
