### ISSUE TITLE
scss中 引用 iconfont.css报错

### ISSUE THREAD

**Issue by quarkcms** [NervJS/taro#12474]
### 相关平台
H5

### 复现仓库
[https://github.com/jdf2e/nutui-demo/tree/master/taro3](https://github.com/jdf2e/nutui-demo/tree/master/taro3)
**浏览器版本:  Chrome 62**
**使用框架: React**

### 复现步骤
https://github.com/NervJS/taro/issues/9863

猜测是 taro-webpack5-runner/package.json配置文件，把resolve-url-loader升级到4.0.0导致的

### 期望结果
正常运行

### 实际结果
报错

### 环境信息
```
 Taro v3.5.3


  Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by quarkcms** [comment]
刚才测试了一下，使用webpack4无此问题

**Comment by ZakaryCode** [comment]
> ### 复现仓库
> https://github.com/jdf2e/nutui-demo/tree/master/taro3

所提供的 demo 无法正常启动

> 刚才测试了一下，使用webpack4无此问题

修改 demo 运行后有同样问题（demo 中是 webpack4 版本

FYI：resolve-url-loader 是用来解决 scss 引入引入 scss 文件内的资产路径问题，而并非 css 文件，这样的写法并不符合预期 🤔
