### ISSUE TITLE
View' cannot be used as a JSX component.   Its element type 'ReactElement<any, any> | Component<ViewProps, any, any> | null' is not a valid JSX element.

### ISSUE THREAD

**Issue by SevenOfPaul** [NervJS/taro#12486]
### 相关平台
微信小程序

**小程序基础库: 2.24.7**
**使用框架: React**

### 复现步骤
ts react taro会报View' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<ViewProps, any, any> | null' is not a valid JSX element.
'Text' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<TextProps, any, any> | null' is not a valid JSX element.
编译运行结果都正常
但是一致标红

### 期望结果
结束标红

### 实际结果
一直飘红

### 环境信息
```
Taro CLI 3.4.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\Paul\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by SevenOfPaul** [comment]
![微信图片_20220914204816](https://user-images.githubusercontent.com/83870824/190159860-b0b219b1-bed2-4a6d-983a-226d17ecee6d.jpg)

**Comment by yuconora** [comment]
tsconfig.json  把 jsx 改成 react-jsx 试试
```json
{
  "compilerOptions": {
    ...
     "jsx": "react-jsx",
  }
}
```

**Comment by SevenOfPaul** [comment]
感谢您的回应，但是我现在就是react-jsx的状态，您方便让我把项目打包发过去吗？ 我这里不是很方便把项目上传到github。




------------------&nbsp;Original message&nbsp;------------------
From: "yuconora"; 
Sendtime: Thursday, Sep 15, 2022 1:42 PM
To: "NervJS/taro"; 
Cc: "Chris ***@***.***>; "Author"; 
Subject: Re: [NervJS/taro] View&#39; cannot be used as a JSX component.   Its element type &#39;ReactElement<any, any&gt; | Component<ViewProps, any, any&gt; | null&#39; is not a valid JSX element. (Issue #12486)





 
tsconfig.json  把 jsx 改成 react-jsx 试试
 {   "compilerOptions": {     ...      "jsx": "react-jsx",   } }

**Comment by SevenOfPaul** [comment]
[applet.zip](https://github.com/NervJS/taro/files/9572192/applet.zip)

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/190338857-70e10063-8a43-4194-bb28-43b037a70b07.png)
我试了下没有报错，我看```package.json```里面 taro版本是3.5.5，要不先把cli 和项目内版本统一下

**Comment by SevenOfPaul** [comment]
好滴好滴，麻烦大佬了。
我最开始使用的是3.4.11的cli和库，之后一个兄弟告诉我3.5.5不会报我就把cli和库升级到了3.5.5。但是依然飘红。是的，taroui不太好用。我在选ui库的时候烦躁了好久。

**Comment by fan-shi-jun** [comment]
我也遇到了相同的问题，而且这边是组件库需要打包，ts校验过不去没法打包，我裂开

**Comment by fan-shi-jun** [comment]
想问下大佬咋解决的

**Comment by SevenOfPaul** [comment]
咱俩问题应该不是一个，我类型能过，只是单纯飘红。而且最后我也没解决，个人demo,顶着飘红硬写的。
