### ISSUE TITLE
Picker组件无法实现文本国际化处理

### ISSUE THREAD

**Issue by ittat** [NervJS/taro#12489]
### 这个特性解决了什么问题？
picker组件的“确定”，“取消”按钮文本是hardcode。无法进行自定义
https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/picker/picker.tsx#L499-L505

### 这个 API 长什么样？
希望可以像Taro.showModal那样提供confirmText和cancelText自定义属性

**Comment by ZakaryCode** [comment]
小程序组件不需要额外的国际化实现，不过 h5 和 rn 可以考虑增加该特性
