### ISSUE TITLE
Taro3.5.5版本，编译百度小程序提示Page未找到页面

### ISSUE THREAD

**Issue by zzq1101921989** [NervJS/taro#12480]
### 相关平台
百度小程序

**小程序基础库: 3.540.7**
**使用框架: React**

### 复现步骤
通过Taro3.5.5，框架选择React，百度小程序的工具调试基础库选择3.540.7

### 期望结果
能够正常的渲染出index首页的内容

### 实际结果
实际上直接抛出错误
![image](https://user-images.githubusercontent.com/48540122/190042790-06846fec-a33b-4fa4-9068-35f8e1338f60.png)

### 环境信息
```
  Taro CLI 3.5.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - D:\nodejs\yarn.CMD
      npm: 6.14.15 - D:\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
参考配置如下:

```js
    // ...
    prebundle: {
      swc: {
        jsc: {
          target: 'es5'
        }
      },
    },
    // ...
```

// 已经在 PR #12491 中修复，将在下一个版本释出

**Comment by wwyx778** [comment]
taro 3.3.9也有这个问题。有低版本的解决方案吗？
