### ISSUE TITLE
showToast并不能不显示图标，icon为none 还是会显示图标

### ISSUE THREAD

**Issue by zoeblow** [NervJS/taro#125]
Taro.showToast({
      title: '请填写',
      icon: 'none',
      duration: 2000
})
![image](https://user-images.githubusercontent.com/5022080/41454602-989d0e14-70ac-11e8-8b7f-22abfa6daf1c.png)

**Comment by colmugx** [comment]
我帮你测了一下，没有问题，你查一下是不是其他代码干扰了
```
Taro.showToast({
      title: '成功',
      icon: 'none',
      duration: 3000
    })
```
![image](https://user-images.githubusercontent.com/21327913/41455039-3a62ce04-70ae-11e8-99fc-83eea78ab2f6.png)

**Comment by colmugx** [comment]
@zoeblow 
你要不连同 cli 也更新一下，我只是刚好读代码路过看到这个 issue

**Comment by zoeblow** [comment]
见了鬼了，依然不行，cli更新到最新的0.0.51 依然不行 在新的电脑上 安装也是不行 @yuche 大佬

**Comment by luckyadam** [comment]
H5 的这个 api 有问题~ 我们尽快修复

**Comment by Chen-jj** [comment]
h5 端已修复 showToast icon 设置为 'none' 还是显示了 icon 的问题已修复~
