### ISSUE TITLE
最新3.5.5版本 加了set NODE_ENV=production 后启动失败

### ISSUE THREAD

**Issue by hlbj105** [NervJS/taro#12509]
### 相关平台
微信小程序

**小程序基础库: 2.26.0**
**使用框架: React**

### 复现步骤
使用taro init myApp初始化，选择React，sass，ts，默认模板，GitHub源模板，
在package.json中添加一行：
`"dev:weapp:build": "set NODE_ENV=production && taro build --type weapp --watch",`

### 期望结果
期望能正常启动

### 实际结果
` ELIFECYCLE  Command failed with exit code 1.`
![image](https://user-images.githubusercontent.com/16408650/190897334-9a8fc348-b140-4f23-8747-e9d2cb05ef9b.png)

### 环境信息
```
 Taro CLI 3.5.5 environment info:
    System:
      OS: Windows 11
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by wjljack** [comment]
修改全局node_modules下面的`@tarojs/cli/dist/convertor/index.js`

```javascript
        creator.template(templateName, 'package.json.tmpl', pkgPath, {
            description,
            projectName,
            compiler: 'webpack5',  // 增加
            version,
            css: 'sass',
            typescript: false,
            template: templateName,
            framework: this.framework
        });
        creator.template(templateName, path.join('config', 'index.js'), path.join(configDir, 'index.js'), {
            date,
            compiler: 'webpack5', // 增加
            projectName,
            framework: this.framework
        });

...

        creator.template(templateName, path.join('src', 'index.html'), path.join(this.convertDir, 'index.html'), {
            projectName  // 增加
        });


```

**Comment by Chen-jj** [comment]
@hlbj105 有试过 3.5.4 可以么？

**Comment by hlbj105** [comment]
> @hlbj105 有试过 3.5.4 可以么？

刚才试了下，还是这样

**Comment by hlbj105** [comment]
> 我这边 Mac 试了没问题，或者你可以提供一下完整 demo

Demo [https://github.com/hlbj105/taro-error-demo](https://github.com/hlbj105/taro-error-demo)
我觉得可能是win下才有的问题

**Comment by hlbj105** [comment]
> 我这边 Mac 试了没问题，或者你可以提供一下完整 demo

还真是windows的问题，刚才在wsl里试了下，能正常跑，Linux下是没问题的（Linux下使用的环境变量设置是：`NODE_ENV=production taro build --type weapp --watch`）

**Comment by TheKonka** [comment]
taro build --type weapp --watch --env production
这样可以吗

**Comment by hlbj105** [comment]
> 

这样可以，谢谢 @TheKonka
