### ISSUE TITLE
实现小程序 cropImage 接口

### ISSUE THREAD

**Issue by nuintun** [NervJS/taro#12524]
### 这个特性解决了什么问题？
小程序支持了 cropImage 接口

https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.cropImage.html

### 这个 API 长什么样？
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.cropImage.html

**Comment by Chen-jj** [comment]
可以直接使用 Taro.cropImage，而此 API promise 化和类型提示需要修改 Taro 代码来支持，欢迎 PR~

**Comment by nuintun** [comment]
@Chen-jj 👌，下个版本支持下 ts 定义吧！

**Comment by nuintun** [comment]
@Chen-jj https://github.com/NervJS/taro/pull/12529

和上面那位老兄重复了，看你合并哪个吧~
