### ISSUE TITLE
scss 中的 input 属性选择器被转换成了taro-input-core

### ISSUE THREAD

**Issue by gyf30827** [NervJS/taro#12534]
### 相关平台
H5

**浏览器版本: chrome**
**使用框架: React**

### 复现步骤
项目升级到 3.5.5后样式出现问题

### 期望结果
保持3.3.3 的默认行为

### 实际结果
input 标签选择器被转换

### 环境信息
```
> taro info

👽 Taro v3.5.5


  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/mini-runner: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/webpack-runner: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: ^3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
scss  中的 input 标签 被转换为 taro-input-core
![image](https://user-images.githubusercontent.com/22958382/191242529-36e3fc33-3cc4-488a-a26e-ed8dddc57980.png)
<img width="920" alt="image" src="https://user-images.githubusercontent.com/22958382/191242543-94181227-2876-44b6-bd92-d53c3ad4fa12.png">

**Comment by ZakaryCode** [comment]
taro 中的 input 组件就对应 taro-input-core 标签，这是一个特性而非错误。

可以通过配置 [htmltransform](https://nervjs.github.io/taro-docs/docs/config-detail#h5postcsshtmltransform) 来禁用该行为。

**Comment by gyf30827** [comment]
配置了，发现可以，感谢
