### ISSUE TITLE
请问如何获取公众号模板消息中链接上的参数,Taro 与 小程序原生的区别

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1253]
请问如何获取公众号模板消息中链接上的参数,看了文档，小程序 说是原生的 获取方法是
在 onLoad(options){}的 options 中，那么 Taro 该怎么获取呢？

**系统信息**

 - 操作系统: [e.g.mac pro
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v11]
 - 报错平台 [ weapp]

**Comment by Chen-jj** [comment]
#1226
