### ISSUE TITLE
小程序中int64 类型的数字怎么处理

### ISSUE THREAD

**Issue by ming0101** [NervJS/taro#1254]
网上的解决方案适用于小程序吗？

**Comment by ming0101** [comment]
Taro 有官方的处理方案么

**Comment by yuche** [comment]
我个人推荐将会进入 ES2019 的 Big Int：
https://github.com/GoogleChromeLabs/jsbi
你也可以选择社区里存在很久的 BigInteger：
https://www.npmjs.com/package/big-integer

出于礼貌我这次回答你的问题，以后关于如何选择哪个库、如何编程、如何实现某个功能的问题会直接关闭。
