### ISSUE TITLE
希望可以给Ad广告组件增加QQ小程序对应的类型

### ISSUE THREAD

**Issue by yaun369** [NervJS/taro#12548]
### 这个特性解决了什么问题？
目前广告组件不支持设置QQ小程序以及快手小程序广告的类型。希望可以增加 type 字段。

QQ小程序广告类型：https://q.qq.com/wiki/develop/miniprogram/component/open-ability/ad.html
快手小程序广告类型：https://mp.kuaishou.com/docs/develop/components/open/ad.html

### 这个 API 长什么样？
目前广告组件不支持设置QQ小程序以及快手小程序广告的类型。希望可以增加 type 字段。

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/194465295-89b0fc46-dd18-4883-b452-5b17b9ed448f.png)

https://github.com/NervJS/taro/commit/a26b92630eb7ae03538e4b58078c4020e9395a70#diff-42bfebede1c3e372887ab13e7e762d1992949429d91183927abcf82b85312f14R53

看了下已经支持了，可升级到 3.5.6 及以上版本

**Comment by ZakaryCode** [comment]
fix in #12441
