### ISSUE TITLE
本地plugin优化支持typescript

### ISSUE THREAD

**Issue by zsytssk** [NervJS/taro#12557]
### 这个特性解决了什么问题？
可以更舒服的写本地插件

### 这个 API 长什么样？
现在我使用本地插件，插件源文件是支持typescript的, 但是源文件引入的其他文件就不支持，只要使用ts语法就会报错。

eg. 
- 插件本地源文件 xxx/localPlugin.ts, 在config/index.js中使用绝对路径引用，localPlugin.ts支持所有的ts语法
- localPlugin.ts中import引入localOther.ts，localOther无法使用任何的ts语法，`export, type...`

**Comment by ZakaryCode** [comment]
插件还是使用编译后的比较好一些，更通用且使用效率会更高，在加载插件时还需要编译插件会降低开发效率，优化意义不足。

插件编译可以参考项目内 rollup 配置。
