### ISSUE TITLE
新版 View 属性 style 丢失对象形式定义

### ISSUE THREAD

**Issue by nuintun** [NervJS/taro#12551]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/nuintun/taro-bugs](https://github.com/nuintun/taro-bugs)
**小程序基础库: 2.26.0**
**使用框架: React**

### 复现步骤
https://github.com/NervJS/taro/blob/3c01fa96db886ca4c76ca5d8e6109737c281976e/packages/taro-components/types/View.d.ts#L56-L59

### 期望结果
ts 正确定义

### 实际结果
ts 定义报错

### 环境信息
```
👽 Taro v3.5.6

  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 11
    Binaries:
      Node: 18.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\nuintun\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
```

![image](https://user-images.githubusercontent.com/1730277/191652158-4556da76-78d6-4f02-9394-6c3bf44573fe.png)

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/191673038-417f7b3d-c570-4cec-8c8a-f21f6b7a75ae.png)
![image](https://user-images.githubusercontent.com/22173084/191673155-5d3c1ebd-9560-4fac-8cba-d7da1f8b87d3.png)

**Comment by 1zilc** [comment]
![image](https://user-images.githubusercontent.com/44715458/191876062-f635e4b6-49e5-4a35-b867-1868600edd67.png)
![image](https://user-images.githubusercontent.com/44715458/191876075-397afd08-1cf6-4966-b7fc-071efbb31329.png)
key和class也一样

**Comment by zxc0woool** [comment]
新版 3.5.6 View 属性 catchMove 也丢失了
