### ISSUE TITLE
字节小程序交易组件pay-button，相关交易插件如何配置在taro中？

### ISSUE THREAD

**Issue by tinatianzhu** [NervJS/taro#12561]
### 相关平台
字节跳动小程序

**小程序基础库: 2.68.0.3**
**使用框架: React**

### 复现步骤
package.json中配置microapp-trade-plugin，页面报错microapp-trade-plugin没有定义

### 期望结果
Taro中配置字节跳动交易插件生效

### 实际结果
不生效

### 环境信息
```
 Taro v3.3.9
Taro CLI 3.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.0 - C:\app\nodejs\node.EXE
      npm: 6.13.4 - C:\app\nodejs\npm.CMD

```

**Comment by tinatianzhu** [comment]
![image](https://user-images.githubusercontent.com/37437496/191903829-37863c52-6c92-4874-a1d9-271f0988e0a8.png)
配置这个出问题的

**Comment by OneKissAndOneShot** [comment]
用原生接入吧，用taro你会遇到很多问题。

**Comment by Chen-jj** [comment]
duplicate #12650
