### ISSUE TITLE
navigateTo:fail:not supported

### ISSUE THREAD

**Issue by ZhuQinPeng** [NervJS/taro#12560]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/zhuqinpeng/my-app.git](https://gitee.com/zhuqinpeng/my-app.git)
**小程序基础库: 2.26.0**
**使用框架: React**

### 复现步骤
运行小程序；
小程序真机调试，重复点击重新进入小程序；

### 期望结果
不报错，正常进入页面

### 实际结果
报错，不会跳转页面

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
Unhandled promise rejection {errMsg: "navigateTo:fail:not supported"}

**Comment by TheKonka** [comment]
试了下，没有复现

**Comment by ZhuQinPeng** [comment]
谢谢，上午的时候是可以复现的，现在我自己试不知为啥也不复现，就是点重新进入小程序会一直卡在home页，不会路由到index页，您看能再试一下吗

**Comment by ZhuQinPeng** [comment]
![image](https://user-images.githubusercontent.com/18671583/191904372-e43d7ea8-5d87-46dc-8618-8cd145d6124e.png)
刚提交了，再试试

**Comment by TheKonka** [comment]
> ![image](https://user-images.githubusercontent.com/18671583/191904372-e43d7ea8-5d87-46dc-8618-8cd145d6124e.png) 刚提交了，再试试

![image](https://user-images.githubusercontent.com/22173084/191909357-c16e6326-b375-48bd-a845-6f307489245f.png)
这个报错是正常的，因为你执行```Taro.hideTabBar()``` 是在```onReady``` 里面，```onReady```执行时机在```componentDidShow```之后，所以执行```Taro.hideTabBar()``` 的时候，页面已经导航到 ```pages/index/index```， ```pages/home/index```这个tab页面已经被隐藏了,就报图里面那个错误了，知道问题原因了解决方案也很简单，就是把```Taro.hideTabBar()```放在```componentDidShow```里面

**Comment by ZhuQinPeng** [comment]
谢谢解答。
我又遇到一个新问题，就是我使用了redux-persist做持久化缓存，在App.tsx中使用
<Provider store={store}>
  <PersistGate loading={null} persistor={persistor}>
    {this.props.children}
  </PersistGate>
</Provider>，
真机调试会报找不到页面实例，如下：
![image](https://user-images.githubusercontent.com/18671583/192077777-fa9ff095-c454-4ea3-b034-28904d0b46e7.png)
然后我找到了原因，是因为PersistGate组件引起的，不移动这个组件的话，这个问题怎么解决，谢谢

**Comment by TheKonka** [comment]
> 谢谢解答。 我又遇到一个新问题，就是我使用了redux-persist做持久化缓存，在App.tsx中使用如下 ![image](https://user-images.githubusercontent.com/18671583/192078035-f116e814-83d6-4f83-af61-f562fd0434de.png) 真机调试会报找不到页面实例，如下： ![image](https://user-images.githubusercontent.com/18671583/192077995-a6f8b1d5-19b0-4cd0-aa3f-41e944f17be0.png) 然后我找到了原因，是因为PersistGate组件引起的，不移动这个组件的话，这个问题怎么解决，谢谢

这个我不清楚，我只能猜测原因是 ```PersistGate```里面会条件渲染```props.children```，导致小程序报错
https://github.com/NervJS/taro/issues/12432#issuecomment-1247967857

**Comment by ZhuQinPeng** [comment]
好的，谢谢

**Comment by geekact** [comment]
> 谢谢解答。 我又遇到一个新问题，就是我使用了redux-persist做持久化缓存，在App.tsx中使用如下 ![image](https://user-images.githubusercontent.com/18671583/192078035-f116e814-83d6-4f83-af61-f562fd0434de.png) 真机调试会报找不到页面实例，如下： ![image](https://user-images.githubusercontent.com/18671583/192077995-a6f8b1d5-19b0-4cd0-aa3f-41e944f17be0.png) 然后我找到了原因，是因为PersistGate组件引起的，不移动这个组件的话，这个问题怎么解决，谢谢

去探索taro源码后发现，在taro不想修改的情况下，需要hack才能彻底解决persist顺序问题，参考：https://github.com/NervJS/taro/issues/6548#issuecomment-1126661204
