### ISSUE TITLE
Taro.reLaunch偶尔出现提示回调成功，页面没有跳转

### ISSUE THREAD

**Issue by meiqinLiu** [NervJS/taro#12575]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
正式小程序和真机预览的小程序，安卓手机上会偶尔出现  Taro.reLaunch 回调 success 成功，但是页面没有跳转
登录逻辑：小程序进来默认去index页面，然后跳转到login页面，登录成功再到index页面

### 期望结果
 Taro.reLaunch 能够正常跳转

### 实际结果
 Taro.reLaunch 回调 success 成功，但是页面没有跳转
支付宝控制台打印错误信息 ： 当前同时存在多个导航调用  基础库不能保证调用先后顺序，请在前者调用完成后再调用
![8d8d1fe1fcd69e62bbc78fa12361893](https://user-images.githubusercontent.com/38028974/192196152-14bb9a85-664e-465f-a0e9-ad84a2c04e71.jpg)

### 环境信息
```

  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.10 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
```

**Comment by meiqinLiu** [comment]
补充说明：改用redirectTo还是会有这个问题？ success 回调打印是成功的，但是页面并没有发生跳转

**Comment by Chen-jj** [comment]
@meiqinLiu `Taro.reLaunch` 只是负责调用了 `my.reLaunch`，似乎和 Taro 没有关系，可以到支付宝小程序社区咨询一下。
