### ISSUE TITLE
3.5.6  RN 引入 expo-camera ，dev:h5 报错

### ISSUE THREAD

**Issue by StarHosea** [NervJS/taro#12579]
### 相关平台
React Native

### 复现仓库
[https://github.com/StarHosea/taro-exam-rn.git](https://github.com/StarHosea/taro-exam-rn.git)

**使用框架: React**

### 复现步骤
- taro init 选择 gitee react-native 模板，
- 修改 pages/index/index.ts 引入 expo-camera ，h5 报错
Module parse failed: Unexpected token (12:12)
node_modules/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| import EventEmitter from '../vendor/emitter/EventEmitter';
> import type {IEventEmitter} from '../vendor/emitter/EventEmitter';
| 
| // FIXME: use typed events

- 重启 dev:h5 ，控制台一直报错

Module parse failed: Unexpected token (12:12)
node_modules/react-native/Libraries/EventEmitter/RCTDeviceEventEmitter.js
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| import EventEmitter from '../vendor/emitter/EventEmitter';
> import type {IEventEmitter} from '../vendor/emitter/EventEmitter';
| 
| // FIXME: use typed events

### 期望结果
expo-camera 支持 web， 期望dev:h5 可以正常运行

### 实际结果
dev:h5 报错

### 环境信息
```

  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - C:\Program Files\Volta\node.EXE
      Yarn: 1.22.19 - C:\Program Files\Volta\yarn.EXE
      npm: 8.1.2 - C:\Program Files\Volta\npm.EXE
```

**Comment by zhiqingchen** [comment]
用webpack配一下
react-native-web 的 alias

**Comment by zhiqingchen** [comment]
https://necolas.github.io/react-native-web/docs/setup/#package-aliasing

**Comment by tourze** [comment]
感觉这个可以写到Taro-RN文档

**Comment by zhiqingchen** [comment]
好建议，如果项目仅需要支持 rn 与 h5 的话，引入 react-native-web，倒是不错的选择。
