### ISSUE TITLE
当前同时存在多个导航调用  基础库不能保证调用先后顺序，请在前者调用完成后再调用

### ISSUE THREAD

**Issue by meiqinLiu** [NervJS/taro#12578]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
小程序进来默认去index页面，然后跳转到login页面，登录成功再到index页面。安卓手机偶尔出现跳转首页失败的情况

### 期望结果
希望登录后跳转index能够成功

### 实际结果
登录后跳转首页失败，错误信息：当前同时存在多个导航调用  基础库不能保证调用先后顺序，请在前者调用完成后再调用
![8d8d1fe1fcd69e62bbc78fa12361893](https://user-images.githubusercontent.com/38028974/192201317-04b2cbdf-1a8b-4755-a1aa-f8f7849296a5.jpg)

### 环境信息
```
 Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.10 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
duplicate #12575
