### ISSUE TITLE
Taro 3.5.6版本， npm run build:weapp打包,canvas报错

### ISSUE THREAD

**Issue by lingdulib** [NervJS/taro#12573]
### 相关平台
微信小程序

**小程序基础库: 2.26.0**
**使用框架: Vue 3**

### 复现步骤
新建项目,然后运行npm run build:alipay

### 期望结果
正常显示小程序内容

### 实际结果
WAServiceMainContext.js?t=wechat&s=1664158778749&v=2.26.1:1 TypeError: Cannot read property 'node' of null
    at Object.<anonymous> (memberCode.js:1)
    at Function.<anonymous> (WAServiceMainContext.js?t=wechat&s=1664158778749&v=2.26.1:1)
    at :64609/appservice/<SelectorQuery callback function>
    at WAServiceMainContext.js?t=wechat&s=1664158778749&v=2.26.1:1
    at WAServiceMainContext.js?t=wechat&s=1664158778749&v=2.26.1:1
    at Array.forEach (<anonymous>)
    at WAServiceMainContext.js?t=wechat&s=1664158778749&v=2.26.1:1
    at WAServiceMainContext.js?t=wechat&s=1664158778749&v=2.26.1:1
    at WASubContext.js?t=wechat&s=1664158778749&v=2.26.1:1
    at ae (WASubContext.js?t=wechat&s=1664158778749&v=2.26.1:1)(env: Windows,mp,1.06.2209070; lib: 2.26.1)

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
运行npm run dev:weapp ,canvs 绘制正常，但是一旦build:weapp,首次渲染正常，再次进入界面，就提示canvas node 节点为空，dev环境下，无任何问题，赋代码片段:
useReady(()=>{
             const query = Taro.createSelectorQuery()
            query.select("#qrCodeBox")
                .fields({ node: true, size: true })
                .exec((canvansRes) => {
                    const canvas = canvansRes[0].node
                    obtainQrCodeForImageForCanvas(canvas, cardNo)
                })
        })

**Comment by TheKonka** [comment]
是不是再次进入界面，页面变化（跳转），```#qrCodeBox``` 获取不到了？

**Comment by lingdulib** [comment]
应该是没有，因为npm run dev:weapp的时候，来回切换界面，都不会报错，只有build:weapp时才会出现这种情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro] Taro 3.5.6版本， npm run build:weapp打包,canvas报错 (Issue #12573)





 
是不是再次进入界面，页面变化（跳转），#qrCodeBox 获取不到了？

**Comment by lingdulib** [comment]
select选择器换成类选择器，可解决多次进入界面，node节点为空情况
