### ISSUE TITLE
Video组件设置了controls为false时并不会隐藏视频原生控件

### ISSUE THREAD

**Issue by xu-supper-heavyweight** [NervJS/taro#12584]
### 相关平台
字节跳动小程序

**小程序基础库: 2.71.0**
**使用框架: React**

### 复现步骤
给video组件设置controls={false}无效，可以直接复现

### 期望结果
设置controls={false}可以直接完美隐藏原生控件

### 实际结果
设置controls={false}不会隐藏视频原生控件

### 环境信息
```
 Taro v3.5.5


  Taro CLI 3.5.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
源代码如下：
<Video
        ref={videoRef}
        id="video"
        src={src}
        poster={poster}
        className={className}
        autoplay={iAutoplay}
        objectFit="contain"
        loop
        controls={false}
        showFullscreenBtn={isShowFull}
        style={{ ...style }}
        x5-video-player-type="h5-page"
        webkit-playsinline="true"
        x5-playsinline="true"
        x5-video-orientation="portraint"
        onTimeUpdate={onProgress}
      ></Video>

**Comment by TheKonka** [comment]
![Uploading image.png…]()
没有复现

**Comment by xu-supper-heavyweight** [comment]
应该是使用preact会导致此问题。在这个issues有体现https://github.com/NervJS/taro/issues/12589

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/pull/12608
