### ISSUE TITLE
h5设置多页面模式 router: {   mode: 'multi'     },打包文件中 没有生成css文件

### ISSUE THREAD

**Issue by GetWhy** [NervJS/taro#12582]
### 相关平台
H5

### 复现仓库
[https://github.com/GetWhy/-bug-.git](https://github.com/GetWhy/-bug-.git)
**浏览器版本: Google Chrome 99.0.4844.84（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
下载依赖后启动项目 打包h5

### 期望结果
打包文件中有css文件，页面正常显示

### 实际结果
本地模式页面无法正常显示 ；build:h5  打包后没有css文件 

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - D:\code\tools\nvm\programs\nvm\nodejs\node.EXE
      Yarn: 1.22.10 - D:\newFiles\code\software\soft\nodeJs\node_global\yarn.CMD
      npm: 8.7.0 - D:\newFiles\code\software\soft\nodeJs\node_global\npm.CMD

```

**Comment by GetWhy** [comment]
dev:h5启动后显示如图
![1664268566992](https://user-images.githubusercontent.com/49557657/192479790-a8fe610e-be8e-4056-be10-0cff705e9fd6.jpg)

**Comment by GetWhy** [comment]
build:h5打包后文件目录如图 
![image](https://user-images.githubusercontent.com/49557657/192480417-90fc1bb3-6668-4da2-9d5f-908c26589008.png)

**Comment by biorz** [comment]
实际上样式是生效的， 只是访问路由不对，可以访问 /pages/index/index.html(即 ${path}.html) 试试.

考虑启动开发服务器后默认跳转的页面设为 app.config 中的第一个页面. 🤔
