### ISSUE TITLE
当taro-react项目中存在vue依赖时，ts编译报错。View' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by fan-shi-jun** [NervJS/taro#12586]
### 相关平台
H5

**浏览器版本: chrome 62**
**使用框架: React**

### 复现步骤
项目需要进行monorepo 管理，所以要与别的项目进行vue整合。在使用taro cli（react语法，ts语言，其余默认）一个新项目后，在新项目packages.json中加入依赖：    "vue": "^2.6.11",后。在开发过程中，一旦有import Taro from '@tarojs/taro'后，就会ts报错，如标题所示。运行项目不受影响。但是ts编译出错

### 期望结果
ts编译正常

### 实际结果
ts报错：View' cannot be used as a JSX component. Its element type 'ReactElement<any, any> | Component<ViewProps, any, any> | null' is not a valid JSX element.

### 环境信息
```
PS D:\motest\jsxtest> taro info
👽 Taro v3.3.11


  Taro CLI 3.3.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
考虑是不是taro支持两种语法导致vue与react冲突

**Comment by fan-shi-jun** [comment]
示例代码：
import { Component } from 'react'
import { View, Text } from '@tarojs/components'
import Taro from '@tarojs/taro'
import './index.less'

export default class Index extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
      </View>
    )
  }
}

**Comment by fan-shi-jun** [comment]
package.json：
{
  "name": "jsxtest",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "templateInfo": {
    "name": "default",
    "typescript": true,
    "css": "less"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.3.11",
    "@tarojs/runtime": "3.3.11",
    "@tarojs/taro": "3.3.11",
    "@tarojs/react": "3.3.11",
    "react-dom": "^17.0.0",
    "react": "^17.0.0"
  },
  "devDependencies": {
    "vue": "^2.6.11",
    "@types/webpack-env": "^1.13.6",
    "@types/react": "^17.0.2",
    "@tarojs/mini-runner": "3.3.11",
    "@babel/core": "^7.8.0",
    "@tarojs/webpack-runner": "3.3.11",
    "babel-preset-taro": "3.3.11",
    "eslint-config-taro": "3.3.11",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0",
    "@typescript-eslint/parser": "^4.15.1",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "typescript": "^4.1.0"
  }
}

**Comment by fan-shi-jun** [comment]
![jsx1](https://user-images.githubusercontent.com/78457189/192921492-e919e2f2-d6bd-4d33-ba11-59166086d6b6.PNG)
![jsx2](https://user-images.githubusercontent.com/78457189/192921502-078f14cb-236d-4a29-88c6-9176f33fcf26.PNG)

**Comment by fan-shi-jun** [comment]
能否在项目里对vue的jsx定义进行屏蔽呢，typesroot试过了也不行。

**Comment by Chen-jj** [comment]
升级下再试试，现在安装 React 不会带 Vue 相关依赖了

**Comment by fan-shi-jun** [comment]
谢谢大佬，但是项目需要进行pnpm+workspace+monorepo 管理，所以要与别的项目进行整合。。。。。。想看看有没有什么解决方案。

**Comment by ZakaryCode** [comment]
> 谢谢大佬，但是项目需要进行pnpm+workspace+monorepo 管理，所以要与别的项目进行整合。。。。。。想看看有没有什么解决方案。

可以通过 TS 配置[typeRoots](https://www.typescriptlang.org/tsconfig#typeRoots)或[types](https://www.typescriptlang.org/tsconfig#types)引入指定类型来排除 vue 依赖

**Comment by fan-shi-jun** [comment]
> 

在项目中选择指定类型后，vscode编译器还是提示了jsx冲突，目前看来vue是将jsx通过某种方式注册到全局了

**Comment by ZakaryCode** [comment]
> 在项目中选择指定类型后，vscode编译器还是提示了jsx冲突，目前看来vue是将jsx通过某种方式注册到全局了

应该是 taro 类型有那个地方引用了 vue 所以无法屏蔽 🤔

可以考虑在全局覆盖以下类型，因为 vue 覆盖了这些类型导致 react 的类型配置错误

```ts
declare namespace JSX {
  type Element = any
  type ElementClass = any
}
```

**Comment by Binbiubiubiu** [comment]
.npmrc 
``` 
hoist-pattern[]=!vue
```
