### ISSUE TITLE
Taro 3.5.6 版本 css 编译警告

### ISSUE THREAD

**Issue by lingdulib** [NervJS/taro#12585]
### 相关平台
微信小程序

**小程序基础库: 2.26.1**
**使用框架: Vue 3**

### 复现步骤
.Site-content {
    margin-bottom: calc(51.2px   env(safe-area-inset-bottom));
}

### 期望结果
正常编译

### 实际结果
Warning: pages/~/pages/~/~.acss from Css Minimizer plugin
postcss-calc: D:\~\~\pages\~\pages\~\~.acss:519:3: Parse error on line 1:
102.4rpx   en...
---^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "UNKNOWN_DIMENSION"

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
好像是因为使用了calc和env

**Comment by TheKonka** [comment]
是不是少了加号
```css
margin-bottom: calc(51.2px + env(safe-area-inset-bottom))
```

**Comment by lingdulib** [comment]
> `calc` 和 `env` 肯定是可以用的，是不是少了加号
> 
> ```css
> margin-bottom: calc(51.2px + env(safe-area-inset-bottom))
> ```

经过测试发现类似51.2px，必须是整数形式才不会出现这个警告，是小数形式，就会提示这个警告，这个警告是在build模式下触发的，dev模式无此警告

**Comment by lingdulib** [comment]
换了下位置，还是不行，是写法问题吗？margin-bottom: calc(env(safe-area-inset-bottom) + 51.2px);，Taro 3.4.14 版本编译没有这个提示
Warning: pages/`/pages/`/`.wxss from Css Minimizer plugin
postcss-calc: D:\wx_workspace\`\pages\`\pages\`\`.wxss:519:3: Parse error on line 1:
env(safe-area-inset-bottom) + 102.4rpx






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro] Taro 3.5.6 版本 css 编译警告 (Issue #12585)





 
是不是少了加号
 margin-bottom: calc(51.2px + env(safe-area-inset-bottom))

**Comment by Chen-jj** [comment]
@lingdulib 这是 csso 压缩工具的问题，可能没有兼容这种带小数点的写法，可以到 csso 项目下提 issue。

Taro 3.5 的 webpack5 使用了 [css-minimizer-webpack-plugin](https://docs.taro.zone/docs/config-detail#cssminimizer) 插件进行压缩，它支持使用 csso、esbuild、parcelCSS 压缩样式，默认是 csso。你也可以尝试使用 parcelCSS 进行压缩，使用 esbuild 也是会报其它错误。
