### ISSUE TITLE
官方1.2.0-beta.3 （sass  redux）实例，直接运行yarn dev:rn报错:Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by dxhuii** [NervJS/taro#1259]
**问题描述**
官方1.2.0-beta.3 redux实例，直接运行yarn dev:rn报错：Uncaught TypeError: Super expression must either be null or a function, not undefined

**复现步骤**
[复现问题的步骤]
官方包（sass redux）
yarn dev:rn

[或者可以直接贴源代码，能贴文字就不要截图]

官方（sass redux），运行yarn dev:rn

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

![](https://ws1.sinaimg.cn/large/006bnWk0gy1fxmg9ejah1j30u01o0wh7.jpg)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Mac os 10.13.6]
 - Taro 版本 [e.g. 1.2.0-beta.3]
 - Node.js 版本 [e.g. v8.10.0]
 - 报错平台 [rn]
- 手机：小米MIX2S

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by chuanzhang2018** [comment]
同样复现了

**Comment by dxhuii** [comment]
> 同样复现了，在ios下复现 RN跑不起来 其他都可以

我用老项目升级上来，也是一样的报错。等官方修复吧。

**Comment by chuanzhang2018** [comment]
> > 同样复现了，在ios下复现 RN跑不起来 其他都可以
> 
> 我用老项目升级上来，也是一样的报错。等官方修复吧。

我发现这个版本 跑H5也是  不会自动打开页面了。。。。

**Comment by Pines-Cheng** [comment]
问题已复现，正在排查。

**Comment by Pines-Cheng** [comment]
111ab7d913 close

**Comment by Pines-Cheng** [comment]
https://github.com/facebook/react-native/issues/4784?1543369126088

**Comment by dxhuii** [comment]
> [facebook/react-native#4784](https://github.com/facebook/react-native/issues/4784)

嗯，这个修复的版本，什么时候发布

**Comment by Pines-Cheng** [comment]
今天或明天会发一版。@dxhuii

**Comment by Pines-Cheng** [comment]
@dxhuii 已发布

**Comment by dxhuii** [comment]
@Pines-Cheng 谢谢提醒。

**Comment by chuanzhang2018** [comment]
![image](https://user-images.githubusercontent.com/35988956/49195350-b07cb280-f3c1-11e8-81f4-75f214754a42.png)
![image](https://user-images.githubusercontent.com/35988956/49195355-b8d4ed80-f3c1-11e8-899b-43268dea5d6a.png)

**Comment by chuanzhang2018** [comment]
> @chuanzhang2018 我还没有测试，一会试试。

请问怎么降级或者init 指定版本啊  明天我就要出demo给领导看了。。。看他们应该是不行的了

**Comment by dxhuii** [comment]
@chuanzhang2018 重新安装 tarojs/cli 指定版本，然后重新建一个项目，把代码移植过来，试试。

**Comment by dxhuii** [comment]
```
 "dependencies": {
    "@tarojs/async-await": "^1.2.0-beta.4",
    "@tarojs/components": "^1.2.0-beta.4",
    "@tarojs/components-rn": "^1.2.0-beta.4",
    "@tarojs/redux": "^1.2.0-beta.4",
    "@tarojs/redux-h5": "^1.2.0-beta.4",
    "@tarojs/rn-runner": "^1.2.0-beta.4",
    "@tarojs/router": "^1.2.0-beta.4",
    "@tarojs/taro": "^1.2.0-beta.4",
    "@tarojs/taro-h5": "^1.2.0-beta.4",
    "@tarojs/taro-rn": "^1.2.0-beta.4",
    "@tarojs/taro-router-rn": "^1.2.0-beta.4",
    "@tarojs/taro-weapp": "^1.2.0-beta.4",
    "babel-plugin-transform-jsx-to-stylesheet": "^1.2.0-beta.4",
    "nervjs": "^1.3.9",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "taro-ui": "^1.5.0"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "^1.2.0-beta.4",
    "@tarojs/plugin-csso": "^1.2.0-beta.4",
    "@tarojs/plugin-sass": "^1.2.0-beta.4",
    "@tarojs/plugin-uglifyjs": "^1.2.0-beta.4",
    "@tarojs/webpack-runner": "^1.2.0-beta.4",
    "@types/react": "^16.7.8",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^10.0.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "eslint": "^5.9.0",
    "eslint-config-taro": "^1.2.0-beta.4",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-taro": "^1.2.0-beta.4"
  }
```
确实没有修复。还是报一样的错 @chuanzhang2018  @Pines-Cheng

**Comment by dxhuii** [comment]
> > @chuanzhang2018 我还没有测试，一会试试。
> 
> 请问怎么降级或者init 指定版本啊 明天我就要出demo给领导看了。。。看他们应该是不行的了

@chuanzhang2018 好像好了，我现在报其他的错，应该是我自己程序的问题

你这样试一下

删除 node_modules 重新安装一下依赖。再跑一下遍。

**Comment by dxhuii** [comment]
@chuanzhang2018 按我说的，重新弄，应该解决了这个BUG。你试试吧。

**Comment by chuanzhang2018** [comment]
> @chuanzhang2018 按我说的，重新弄，应该解决了这个BUG。你试试吧。

谢谢啦
