### ISSUE TITLE
taro版本从3.3.2升级到3.3.5报initNativeApi' of undefined

### ISSUE THREAD

**Issue by xumaoling0213** [NervJS/taro#12598]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/xumaoling0213/taroUpdateError](https://github.com/xumaoling0213/taroUpdateError)
**小程序基础库: 2.19.2**
**使用框架: Vue 3**

### 复现步骤
打开项目即可看到initNativeApi' of undefined报错

### 期望结果
能正常运行

### 实际结果
报错

### 环境信息
```
 Taro CLI 3.3.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
为了解决https://github.com/NervJS/taro/issues/10098这个问题，将本地taro升级到3.3.5

**Comment by xumaoling0213** [comment]
![0b89e69d13a0d8605e113fd975535fa](https://user-images.githubusercontent.com/27544158/192973883-998f943b-7587-4207-8978-a8d7a5c1d4e9.jpg)

**Comment by xumaoling0213** [comment]
https://github.com/NervJS/taro/issues/9808有点类似这个问题

**Comment by guoenyue** [comment]
+1 同样问题 
编译后的模块中似乎不存在defaultReconciler，不知道是什么情况，taro相关版本均已安装到3.5.6版本
![image](https://user-images.githubusercontent.com/22184722/193215230-8d717d46-b9b2-499e-8125-2f0d3ad4fe10.png)

**Comment by guoenyue** [comment]
> +1 同样问题 编译后的模块中似乎不存在defaultReconciler，不知道是什么情况，taro相关版本均已安装到3.5.6版本 ![image](https://user-images.githubusercontent.com/22184722/193215230-8d717d46-b9b2-499e-8125-2f0d3ad4fe10.png)

找到问题了，是因为项目依赖了一个低版本的taro/plugin-inject插件，即0.0.2版本的插件在3.2版本中正常，而这个插件似乎不在taro-cli的自动升级适应3.5.x版本范围之内，手动升级taro/plugin-inject到1.0.2后，问题得到解决

**Comment by Chen-jj** [comment]
@xumaoling0213 3.3.5 没有复现，应该还是依赖没装好的问题。

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/11807297/194765159-34a2ad09-b811-42cc-b3c6-b13eabd4b233.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/11807297/194765175-faced02c-d145-44b0-bfcc-109dd9c10b56.png">
