### ISSUE TITLE
列表渲染 无法使用key属性

### ISSUE THREAD

**Issue by SaiyanGuo** [NervJS/taro#126]
根据文档中列表渲染的表述写了如下代码：
```javascript
render() {
	return (
		<View className='container'>
			{data.map((item) => <Card data={item} key={item} />)}
		</View>
	)
}
```

生成的小程序页面中没有key属性。
导致微信开发工具给出如下提示：
```
 Now you can provide attr "wx:key" for a "wx:for" to improve performance.
  3 |         <view class="title">{{title}}</view>
  4 |         <view class="content">
> 5 |             <view class="item" wx:for="{{list}}" wx:for-item="item">{{item}}</view>
    |              ^
  6 |             <button class="add" bindtap="add">添加</button>
  7 |         </view>
  8 |     </view>
```

**Comment by yuche** [comment]
如果列表渲染的是自定义组件的确有这个问题，

**Comment by ranglang** [comment]
这个解决了吗？是否可以使用key作为prop了？

**Comment by yuche** [comment]
抱歉之前忘记提交了
https://github.com/NervJS/taro/commit/f73626b76c3b8b4ca3320b91fe817674209e23a7
应该修复了这个问题。

**Comment by beehoo** [comment]
问题似乎没有修复，使用vant-weapp自定义组件，列表渲染依旧报这个问题。版本1.1.0-beta.12
`<van-tabbar active={active} onChange={this.handleChange}>
          {
            data.map((item, index) => {
              return (
                <van-tabbar-item
                  icon={item.icon}
                  key={index}>{ item.label }</van-tabbar-item>
              )
            })
          }
        </van-tabbar>`
