### ISSUE TITLE
taro3.5.2升级3.5.3后出现警告

### ISSUE THREAD

**Issue by yangjisen** [NervJS/taro#12606]
### 相关平台
微信小程序

**小程序基础库: 2.25.4**
**使用框架: Vue 3**

### 复现步骤
▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module [this-is-undefined-in-esm]

    src/helper.js:29:4:
      29 │     this[item.callback] &&
         │     ~~~~
         ╵     undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    src/helper.js:87:0:
      87 │ export const getQueryString = (url) => {
         ╵ ~~~~~~

JS代码如下:
```
export const handleCallbackClick = item => {
  if (!item) return;

  /* Todo 此处是否阻塞 */

  // let params = Taro.getCurrentInstance().router.params;

  /* 如果带有回调并且存在则调用回调函数 */
  if (
    item.callback &&
    this[item.callback] &&
    typeof this[item.callback] === "function"
  )
    return this[item.callback](item);

... 后面其他逻辑
}

export const getQueryString = (url) => { /* 业务逻辑 */}
```

### 期望结果
没有警告报错信息

### 实际结果
降级3.5.2没有报错

### 环境信息
```
  Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD


```

**Comment by Chen-jj** [comment]
应该是 esbuild 版本的问题：https://esbuild.github.io/api/#log-override

**Comment by Chen-jj** [comment]
@yangjisen esbuild 的告警是有道理的，esm 模块没有顶层的 this 对象。你可以修改写法，或者配置 Taro 预编译的 exclude 选项，不对这个包进行预编译：https://docs.taro.zone/docs/config-detail#compilerprebundleexclude
