### ISSUE TITLE
UI 组件库打包无法导出函数

### ISSUE THREAD

**Issue by jimczj** [NervJS/taro#1260]
**问题描述**
Taro UI 组件库打包导出组件时，尝试导出函数，如下图
![image](https://user-images.githubusercontent.com/13499146/49056954-aaa79580-f238-11e8-91fd-f7175a647516.png)
入口文件，如下图
![image](https://user-images.githubusercontent.com/13499146/49056967-b5622a80-f238-11e8-9a7d-6d98e7f57dc0.png)

在应用中 npm link 后使用，微信小程序报错，message is not defined

后在 `AtMessage` 绑定 message 静态方法，发现在 weapp 也无法使用，如下图
![image](https://user-images.githubusercontent.com/13499146/49057099-286ba100-f239-11e8-8fec-b72340dec073.png)

**期望行为**
能在 UI 组件库导出函数

**系统信息**

 - 操作系统: [e.g. Mac]
 - Taro 版本 [e.g. v.1.2.0-beta.3]
 - Node.js 版本 [e.g. v10.0.0]
 - 报错平台 [weapp]

**Comment by xioxin** [comment]
开发F2图表库的按需加载时候遇到相同的问题。

改为按需加载，F2需要由用户引入

我提供一个兼容处理的函数，但是现在无法导出


#### 库导出
![image](https://user-images.githubusercontent.com/5716100/51388506-97dc7d80-1b64-11e9-8cef-b552efbc23e0.png)
![image](https://user-images.githubusercontent.com/5716100/51388518-a3c83f80-1b64-11e9-8510-f3f0d7f280d3.png)

#### 引入使用
![image](https://user-images.githubusercontent.com/5716100/51388564-cd816680-1b64-11e9-9d8e-3faf35c0eede.png)

![image](https://user-images.githubusercontent.com/5716100/51388593-e9850800-1b64-11e9-8184-8498039e717b.png)

**Comment by xioxin** [comment]
这个Issues有解决计划吗

**Comment by Miantang** [comment]
这个问题有解决计划吗

**Comment by Miantang** [comment]
这。直接关了么，已经解决了？

**Comment by HuJean** [comment]
有修复计划吗？
