### ISSUE TITLE
taro3.5.6编译到h5，启动报错

### ISSUE THREAD

**Issue by xianguoGou** [NervJS/taro#12616]
### 相关平台
H5

### 复现仓库
[https://github.com/xianguoGou/taro_demo01](https://github.com/xianguoGou/taro_demo01)
**浏览器版本: Google Chrome Version 105.0.5195.125 (Official Build) (x86_64)**
**使用框架: React**

### 复现步骤
yarn install

yarn dev:h5

在默认打开的浏览器就能看到报错信息

### 期望结果
编译通过，能够正常显示hello world 页面

### 实际结果
TypeError
Cannot read properties of undefined (reading 'isProxied')
Call Stack
 eval
  node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:18950
 i
  node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:1896
 Object.eval [as next]
  node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:1187
 l
  node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:713

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.1 => 3.5.6 
      @tarojs/mini-runner: 3.3.1 => 3.5.6 
      @tarojs/react: 3.3.1 => 3.5.6 
      @tarojs/runtime: 3.3.1 => 3.5.6 
      @tarojs/taro: 3.3.1 => 3.5.6 
      @tarojs/webpack-runner: 3.3.1 => 3.5.6 
      babel-preset-taro: 3.3.1 => 3.5.6 
      eslint-config-taro: 3.3.1 => 3.5.6 
      react: ^17.0.0 => 17.0.2 
      taro-ui: 3.0.0-alpha.10 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.6.3
```

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/194687933-f9b08727-d90c-4eb5-915a-7329de65b151.png)
我这边试了正常

**Comment by robinv8** [comment]
试了下，应该是不支持 node 16

**Comment by robinv8** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/194687933-f9b08727-d90c-4eb5-915a-7329de65b151.png) 我这边试了正常，为什么环境信息 跟 `package.json` 里的不一样 修正：原先正常使用的 `pnpm` ，换了`yarn` 也遇到了同样的错误 ，但是刷新一下就好了，可能是热更新相关的问题，使用 `yarn` 多试了几次后发现也不是必现的 ![image](https://user-images.githubusercontent.com/22173084/194688940-6a8daa45-383b-442a-bc10-ec4158ce03e0.png)

是的，很奇怪，多试几次，该问题就复现不了了

**Comment by robinv8** [comment]
貌似跟 [stencil](https://github.com/ionic-team/stencil) 有关，大概位置
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/12277531/194701009-c65ed9f7-ad53-42dd-931d-b80b30e76b8b.png">

**Comment by xianguoGou** [comment]
> ### 相关平台
> H5
> 
> ### 复现仓库
> https://github.com/xianguoGou/taro_demo01 **浏览器版本: Google Chrome Version 105.0.5195.125 (Official Build) (x86_64)** **使用框架: React**
> 
> ### 复现步骤
> yarn install
> 
> yarn dev:h5
> 
> 在默认打开的浏览器就能看到报错信息
> 
> ### 期望结果
> 编译通过，能够正常显示hello world 页面
> 
> ### 实际结果
> TypeError Cannot read properties of undefined (reading 'isProxied') Call Stack  eval   node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:18950  i   node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:1896  Object.eval [as next]   node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:1187  l   node_modules/@tarojs/components/dist/esm-es5/index-8809c729.js:11:713
> 
> ### 环境信息
> ```
> 👽 Taro v3.5.6
> 
> 
>   Taro CLI 3.5.6 environment info:
>     System:
>       OS: macOS 12.2.1
>       Shell: 5.8 - /bin/zsh
>     Binaries:
>       Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
>       Yarn: 1.22.10 - /usr/local/bin/yarn
>       npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
>     npmPackages:
>       @tarojs/components: 3.3.1 => 3.5.6 
>       @tarojs/mini-runner: 3.3.1 => 3.5.6 
>       @tarojs/react: 3.3.1 => 3.5.6 
>       @tarojs/runtime: 3.3.1 => 3.5.6 
>       @tarojs/taro: 3.3.1 => 3.5.6 
>       @tarojs/webpack-runner: 3.3.1 => 3.5.6 
>       babel-preset-taro: 3.3.1 => 3.5.6 
>       eslint-config-taro: 3.3.1 => 3.5.6 
>       react: ^17.0.0 => 17.0.2 
>       taro-ui: 3.0.0-alpha.10 => 3.0.0-alpha.10 
>     npmGlobalPackages:
>       typescript: 4.6.3
> ```

环境信息给错了， 修正一下：
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 4.6.3

**Comment by ZakaryCode** [comment]
这是一个历史版本问题，根据问题描述判断应该是依赖没有统一导致的

**Comment by zhaoyunchong** [comment]
我这边 也复现了，但是把依赖删除之后。在运行几次就没有碰见这种情况了。是我这边做了什么吗，
这个项目是我前几天搭建的，突然今天运行就会报这个问题,然后把依赖删除后，重新pnpm 安装 暂时还没出现那个问题！！

其实 官网关注下这个问题

**Comment by zhaoyunchong** [comment]
偶现 刚评价完 重启又出现这个问题了   尴尬 又来评论了  好像是偶尔会出现这个问题。 随机的  有时候重启个十几次都没有复现。有时候连着复现两次
