### ISSUE TITLE
支持 solidjs 

### ISSUE THREAD

**Issue by Hi-Alan** [NervJS/taro#12611]
### 这个特性解决了什么问题？
开发比 react 更简洁、运行 react 更快速、最终产物比 react 更小

### 这个 API 长什么样？
用函数式组件，生命周期更简单。也可以借助 [solid-lables](https://github.com/LXSMNSYC/solid-labels) 处理器让 signal 以更”普通“ 的方式编程

**Comment by 4440124** [comment]
react 真的是让人又爱又恨 直到遇到solidjs 就是我心目中完美的react 希望taro早日支持solidjs

**Comment by ZakaryCode** [comment]
Duplicate of #12834
