### ISSUE TITLE
error: node_modules/@tarojs/rn-supporter/dist/empty-module.js: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by StarlightUnion** [NervJS/taro#12618]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
* 1 启动`yarn dev:rn --qr`，启动未报错

* 2.使用Taro Playground扫码在手机上运行

* 3.报错：`error: node_modules/@tarojs/rn-supporter/dist/empty-module.js: Cannot use import statement outside a module`

### 期望结果
成功在手机上运行

### 实际结果
报错闪退

### 环境信息
```
👽 Taro v3.5.5


  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.3 => 3.5.3
      @tarojs/components: 3.5.3 => 3.5.3
      @tarojs/helper: 3.5.3 => 3.5.3
      @tarojs/mini-runner: 3.5.3 => 3.5.3
      @tarojs/plugin-framework-react: 3.5.3 => 3.5.3
      @tarojs/plugin-platform-alipay: 3.5.3 => 3.5.3
      @tarojs/plugin-platform-jd: 3.5.3 => 3.5.3
      @tarojs/plugin-platform-qq: 3.5.3 => 3.5.3
      @tarojs/plugin-platform-swan: 3.5.3 => 3.5.3
      @tarojs/plugin-platform-tt: 3.5.3 => 3.5.3
      @tarojs/plugin-platform-weapp: 3.5.3 => 3.5.3
      @tarojs/react: 3.5.3 => 3.5.3
      @tarojs/rn-runner: 3.5.3 => 3.5.3
      @tarojs/router: 3.5.3 => 3.5.3
      @tarojs/runtime: 3.5.3 => 3.5.3
      @tarojs/shared: 3.5.3 => 3.5.3
      @tarojs/taro: 3.5.3 => 3.5.3
      @tarojs/taro-h5: 3.5.3 => 3.5.3
      @tarojs/taro-rn: 3.5.3 => 3.5.3
      @tarojs/webpack-runner: 3.5.3 => 3.5.3
      babel-preset-taro: 3.5.3 => 3.5.3
      eslint-config-taro: 3.5.3 => 3.5.3
      expo: ~45.0.4 => 45.0.8
      react: ^17.0.2 => 17.0.2
      react-native: ^0.68 => 0.68.3
      taro-ui: ^3.0.0-alpha.9 => 3.0.0-alpha.10
```

**Comment by StarlightUnion** [comment]
补充说明`Taro Playground`版本：`IOS 1.17.0`

**Comment by zhiqingchen** [comment]
```
Cannot use import statement outside a module
```
一般为代码写法问题

**Comment by StarlightUnion** [comment]
> ```
> Cannot use import statement outside a module
> ```
> 
> 一般为代码写法问题

是的，
![image](https://user-images.githubusercontent.com/43316114/194695243-f3a7ad05-4c86-426d-a4ce-75dd81619791.png)
是`@tarojs/rn-supporter`这个包里的`empty-module.js`这个文件

**Comment by StarlightUnion** [comment]
经验证，`3.5.6`同样存在这个问题，原因为`@tarojs/rn-supporter/dist/empty-module.js`文件没有声明导出。

**Comment by zhiqingchen** [comment]
可以提供下，可复现demo

**Comment by StarlightUnion** [comment]
> 可以提供下，可复现demo

https://github.com/StarlightUnion/demos/tree/main/taro-error-demo

* 1.`yarn install`
* 2.`yarn dev:rn --qr`
* 3.使用Taro Playground扫码后app闪退，命令行界面出现错误`error: node_modules/@tarojs/rn-supporter/dist/empty-module.js: Cannot use import statement outside a module`

**Comment by zhiqingchen** [comment]
包含私有包，无法安装成功

**Comment by StarlightUnion** [comment]
> 包含私有包，无法安装成功

稍等，我处理一下

**Comment by StarlightUnion** [comment]
> 包含私有包，无法安装成功

OK了，麻烦重新拉一下

**Comment by zhiqingchen** [comment]
存在几个问题
https://github.com/zhiqingchen/taro-test/commit/204a7ba78025febeb46bc589d5e4a41b472bbf5a

1. 想使用 taro Playground 调试，需要设置 appName: 'taroDemo',
2. `config/index.js` 不支持 import 语法
3. taro ui 支持 rn 在 beta 版本 https://github.com/NervJS/taro-ui/issues/1424
4. react 18，在 rn 0.69 及 taro 3.5.6 才被支持。
5. iconfont 没有内置支持。
6. 部分css语法在rn并不是生效。https://docs.taro.zone/docs/react-native-remind

**Comment by StarlightUnion** [comment]
> 存在几个问题
> 
> > 参考修复 [zhiqingchen/taro-test@204a7ba](https://github.com/zhiqingchen/taro-test/commit/204a7ba78025febeb46bc589d5e4a41b472bbf5a)
> > 清除编译缓存重启：yarn dev:rn --qr --reset-cache
> 
> 1. 想使用 taro Playground 调试，需要设置 appName: 'taroDemo',
> 2. `config/index.js` 不支持 import 语法
> 3. taro ui 支持 rn 在 beta 版本 [Taro UI 支持 React native 内测版本 taro-ui#1424](https://github.com/NervJS/taro-ui/issues/1424)
> 4. react 18，在 rn 0.69 及 taro 3.5.6 才被支持。
> 5. iconfont 没有内置支持。
> 6. 部分css语法在rn并不是生效。https://docs.taro.zone/docs/react-native-remind

感谢，这就试试👍👍👍
