### ISSUE TITLE
编译微信小程序包的时候报错，taro build --type weapp

### ISSUE THREAD

**Issue by yiran114** [NervJS/taro#12625]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/pulls/暂无地址](https://github.com/pulls/暂无地址)
**小程序基础库: 8.0.27以上版本**
**使用框架: React**

### 复现步骤
在做taro build --type weapp 这一步的时候

### 期望结果
编译成功

### 实际结果
报错，显示The "path" argument must be of type string. Received null
编译  发现页面  src/pages/home/policeAffairsMap/index.js
⠙ 正在编译...
ESLint(taro/duplicate-name-of-state-and-props) 错误：this.state.isAndroid 与 this.props.isAndroid 重复可能会导致渲染结不如意料之中的结果。
-----
  20 |   }
  21 |   state = {
> 22 |     isAndroid:navigator.userAgent.indexOf('Android') > -1 || navigator.userAgent.indexOf('Linux') > -1 ? true :false
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 |   }
  24 |  
  25 |   render () {

Warning: render 函数定义一个不从 this.state 解构或赋值而来的变量，此变量又与 this.state 下的变量重名可能会导致无法渲染。
-----
  94 |         const { classname, source, searchIcon, searchIconStyle, disable, theme } = this.props
  95 |         let u = navigator.userAgent
> 96 |         let isAndroid = u.indexOf('Android') > -1 || u.indexOf('Linux') > -1; //android终端
     |            ^^^^^^^^^
  97 |         return (
  98 |             <View className={` ${classname} ${theme == '2' ? 'search-component-page-old' : 'search-component-page-currency'} search-component-page`}>
  99 |
🙅   编译失败.

The "path" argument must be of type string. Received null

### 环境信息
```
MacdeMacBook-Pro-2:huzhou_public_security_h5-develop juanery$ taro info
👽 Taro v2.2.6


  Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.2.6 => 2.2.6 
      @tarojs/components: 2.2.6 => 2.2.6 
      @tarojs/components-qa: 2.2.6 => 2.2.6 
      @tarojs/mini-runner: 2.2.6 => 2.2.6 
      @tarojs/redux: 2.2.6 => 2.2.6 
      @tarojs/redux-h5: 2.2.6 => 2.2.6 
      @tarojs/router: 2.2.6 => 2.2.6 
      @tarojs/taro: 2.2.6 => 2.2.6 
      @tarojs/taro-alipay: 2.2.6 => 2.2.6 
      @tarojs/taro-h5: 2.2.6 => 2.2.6 
      @tarojs/taro-qq: 2.2.6 => 2.2.6 
      @tarojs/taro-quickapp: 2.2.6 => 2.2.6 
      @tarojs/taro-swan: 2.2.6 => 2.2.6 
      @tarojs/taro-tt: 2.2.6 => 2.2.6 
      @tarojs/taro-weapp: 2.2.6 => 2.2.6 
      @tarojs/webpack-runner: 2.2.6 => 2.2.6 
      eslint-config-taro: 2.2.6 => 2.2.6 
      eslint-plugin-taro: 2.2.6 => 2.2.6 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      stylelint-config-taro-rn: 2.2.6 => 2.2.6 
      stylelint-taro-rn: 2.2.6 => 2.2.6 
      taro-ui: ^2.3.4 => 2.3.4 
```

---
### 补充信息
环境

**Comment by Chen-jj** [comment]
Taro 2 把 JSX 语法编译为小程序的 xml 语法，因此对 JSX 语法有一定限制，按提示信息对写法修改再试试.

**Comment by yiran114** [comment]
我已收到您的邮件，谢谢！
