### ISSUE TITLE
快速点击跳转重复页面之后，回退白屏

### ISSUE THREAD

**Issue by jianghaolun** [NervJS/taro#12629]
### 相关平台
H5

### 复现仓库
[https://gitlab.eazytec-cloud.com/digital-building/app/future-town-h5](https://gitlab.eazytec-cloud.com/digital-building/app/future-town-h5)
**浏览器版本: Chrome**
**使用框架: React**

### 复现步骤
快速点击跳转重复页面之后，回退白屏

### 期望结果
不跳转重复页面，回退正常

### 实际结果
跳转重复页面之后，回退白屏

### 环境信息
```
 Taro CLI 3.4.12 environment info:
    System:
      OS: macOS 12.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 8.1.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.12 => 3.4.12 
      @tarojs/components: 3.4.12 => 3.4.12 
      @tarojs/mini-runner: 3.4.12 => 3.4.12 
      @tarojs/plugin-framework-react: 3.4.13 => 3.4.13 
      @tarojs/react: 3.4.12 => 3.4.12 
      @tarojs/runtime: 3.4.12 => 3.4.12 
      @tarojs/taro: 3.4.12 => 3.4.12 
      @tarojs/webpack-runner: 3.4.12 => 3.4.12 
      babel-preset-taro: 3.4.12 => 3.4.12 
      eslint-config-taro: 3.4.12 => 3.4.12 
      react: ^16.10.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3
```

**Comment by ZakaryCode** [comment]
非公开仓库，另通过描述暂无复现该问题

如果问题存在可以尝试升级修复，3.5 版本 web 端版本实际差异与 3.4+ 并无很大（可以通过关闭 prebundle 配置，并调整 h5.designWidth: 640 抹平差异问题）

**Comment by frankcou** [comment]
> 非公开仓库，另通过描述暂无复现该问题
> 
> 如果问题存在可以尝试升级修复，3.5 版本 web 端版本实际差异与 3.4+ 并无很大（可以通过关闭 prebundle 配置，并调整 h5.designWidth: 640 抹平差异）

@ZakaryCode Taro v3.6.11问题依然存在。我只需要从A页面跳转到B页面，然后在B还没渲染完成时立即返回上一页（返回A），最后A页面对应的dom的style会变成`display:none`
