### ISSUE TITLE
h5 使用 webpack4 无法启动 

### ISSUE THREAD

**Issue by dingff** [NervJS/taro#12631]
### 相关平台
H5

**浏览器版本: chrome 105.0.5195.125**
**使用框架: React**

### 复现步骤
使用官方demo，compiler 改为 webpack4，yarn dev:h5 即可复现

### 期望结果
正常启动

### 实际结果

ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
    at validate (/Users/dingff/Documents/linkcld/mini-app/新能源/ne-mini-app/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/dingff/Documents/linkcld/mini-app/新能源/ne-mini-app/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/dingff/Documents/linkcld/mini-app/新能源/ne-mini-app/node_modules/webpack/lib/webpack.js:111:24)
    at webpack (/Users/dingff/Documents/linkcld/mini-app/新能源/ne-mini-app/node_modules/webpack/lib/webpack.js:158:32)
    at f (/Users/dingff/Documents/linkcld/mini-app/新能源/ne-mini-app/node_modules/webpack/lib/index.js:63:16)
    at /Users/dingff/Documents/linkcld/mini-app/新能源/ne-mini-app/node_modules/@tarojs/webpack-runner/src/index.ts:195:20
    at Generator.next (<anonymous>)

### 环境信息
```

  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/mini-runner: ^3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack-runner: ^3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0 
```

**Comment by ZakaryCode** [comment]
按照该步骤并不能复现问题，看错误应该是没有切换安装的 webpack 版本

**Comment by dingff** [comment]
https://github.com/dingff/taro3-test

**Comment by dingff** [comment]
模板创建的时候选择webpack5，然后compiler 改为 webpack4

**Comment by dingff** [comment]
手动安装 webpack4 的依赖可以解决，不过是否能实现切换 webpack 版本时自动更新依赖
