### ISSUE TITLE
无法导入第三方模块中的json文件

### ISSUE THREAD

**Issue by zacksleo** [NervJS/taro#1263]
**问题描述**

导入第三方模块中的json文件报错，本地的可以

**复现步骤**
[复现问题的步骤]

`import pcaC from 'china-dist-data';`

或者

`import pcaC from 'china-dist-data/china-dist-data.json';`

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

```
thirdScriptError 
 sdk uncaught third Error 
 module "npm/china-dist-data/china-dist-data.json" is not defined 
 Error: module "npm/china-dist-data/china-dist-data.json" is not defined
```

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. Taro v1.2.0-beta.2]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
应该是没有做识别

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/f549f5331c524a9c8d55aa95365d5607e3667790
