### ISSUE TITLE
taro3.5.6:编辑发布后，访问页面会报错 ScriptExternalLoadError 错误信息

### ISSUE THREAD

**Issue by hqwlkj** [NervJS/taro#12633]
### 相关平台
H5

**浏览器版本: Google Chrome 版本 105.0.5195.125（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
taro build --type h5

### 期望结果
正常编译后能够正常访问

### 实际结果
Uncaught (in promise) ScriptExternalLoadError: Loading script failed.

https://sagittarius-web.parsec.com.cn/ 测试地址

### 环境信息
```
  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 11.6.8
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0 

```

**Comment by Chen-jj** [comment]
@hqwlkj `remoteEntry.js` 的内容是 HTML：

<img width="902" alt="image" src="https://user-images.githubusercontent.com/11807297/194851414-6147ea81-62c3-4cf0-ad9a-c941728843c2.png">

在 dev 环境此文件的内容是？

**Comment by hqwlkj** [comment]
在 dev 环境下可以正常运行。

**Comment by hqwlkj** [comment]
感觉是使用了 [webpack5](https://taro-docs.jd.com/taro/docs/config-detail#compiler) 后，自定义环境变量导致的问题，那么我们 在使用 webpack5 的时候怎么自定义环境呢？

**Comment by ZakaryCode** [comment]
> 感觉是使用了 [webpack5](https://taro-docs.jd.com/taro/docs/config-detail#compiler) 后，自定义环境变量导致的问题，那么我们 在使用 webpack5 的时候怎么自定义环境呢？

并无关联，和 webpack4 是一致的

> 在 dev 环境下可以正常运行。

在 dev 环境下，taro 会帮助开发者配置 remoteEntry 相关文件的代理设置，而在 prod 中则会复制到对应路径，请检查生成文件中是否缺少该类文件，或发布应用时是否遗漏。

**Comment by hqwlkj** [comment]
> 生成

并没遗漏什么，我自己 自定义了一个 `staging` 环境，在这个环境下运行就会出现这个错误。但是我在 `production` 和 `dev`环境下都没有什么问题； `staging`的配置和`production`的配置目前是基本保持一致的；如图：


<div>
<img src='https://user-images.githubusercontent.com/12181423/195029580-ad5f32bf-9caf-4fd4-bd78-0293b2862788.png' width='220'/>

<img src='https://user-images.githubusercontent.com/12181423/195031542-2cf8ccf1-e309-4664-91a8-cc496a0c5dd7.png' width='420'/>
</div>

<div>
<img src='https://user-images.githubusercontent.com/12181423/195031247-a16bca1c-b580-4531-9a79-ae0165479bd6.png' width='360'/>
<img src='https://user-images.githubusercontent.com/12181423/195030590-65fe7f99-3c1a-41a7-9626-8f1613320473.png' width='360'/>
</div>

**Comment by ZakaryCode** [comment]
这确实是个需要优化增强的地方，目前 prebundle 能力不支持 `production ` 和 `development` 以外的 `process.env.NODE_ENV` 环境变量，后续会优化。

当前由于 taro 本身的代理配置问题，对应开发新增的环境可以通过配置 `devServer.devMiddleware.writeToDisk: true` 跳过问题，生产环境可以在编译完成后通过复制 remoteCacheDir(默认值为 `node_modules/.taro/${TARO_ENV}/remote`) 下的文件到 dist 目录规避问题。
