### ISSUE TITLE
原生项目使用 Taro打包出现问题

### ISSUE THREAD

**Issue by AnthonyHao** [NervJS/taro#12644]
### 相关平台
微信小程序

**小程序基础库: 2.27.0**
**使用框架: React**

### 复现步骤
1. 在原生项目和Taro混合开发，按例子理解（https://github.com/NervJS/taro/tree/next/examples/blended-basic
）就是将Taro的dist文件夹导入到原生项目的dist文件夹中。
2.  实际开发中，发现必须先build原生项目生成dist文件夹，在此之前需要原生项目的 app.js 中引用 Taro 入口文件。（如果在build以后在dist中的app.js中修改，无法把代码打包进去。同时打包以后dist文件夹中的代码也无法识别）
3.  在代码中导入Taro入口文件，会导致build报错。`Can't resolve './taro/app.js' in '/*******/src' `

### 期望结果
可以正常在原生项目中运行Taro

### 实际结果
无法打包成功，最好给一个比（https://github.com/NervJS/taro/tree/next/examples/blended-basic
）更加实际的用例

### 环境信息
```
  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6
      @tarojs/components: 3.5.6 => 3.5.6
      @tarojs/helper: 3.5.6 => 3.5.6
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6
      @tarojs/react: 3.5.6 => 3.5.6
      @tarojs/router: 3.5.6 => 3.5.6
      @tarojs/runtime: 3.5.6 => 3.5.6
      @tarojs/shared: 3.5.6 => 3.5.6
      @tarojs/taro: 3.5.6 => 3.5.6
      @tarojs/taro-h5: 3.5.6 => 3.5.6
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6
      babel-preset-taro: 3.5.6 => 3.5.6
      eslint-config-taro: 3.5.6 => 3.5.6
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
最好给一个比（https://github.com/NervJS/taro/tree/next/examples/blended-basic ）
更加实际的用例。原生小程序也需要打包完的项目。或者给更详细的思路。

**Comment by Chen-jj** [comment]
@AnthonyHao 开发时，推荐在 Taro 项目中进行开发调试，在生产环境下再把 dist 产物移动到原生小程序中。

的确原生小程序也可能需要预先编译，然后再集成两者的产物，**但如何集成应该是使用方需要思考和处理的**。

建议调整原生小程序项目的编译逻辑，编译后插入对 taro app.js 的引用；又或者在原生小程序项目编译前插入，并配置 external 等。

**Comment by harry118** [comment]
@Chen-jj 我有一个Taro的小程序（React） 想打包成一个分包在另一个Taro小程序（Vue）中使用 在访问分包时报错
![image](https://user-images.githubusercontent.com/98019105/210946430-49f638a6-c73d-47c3-a05d-3bf1d0cc4eee.png)
![image](https://user-images.githubusercontent.com/98019105/210946535-58f27a18-6910-4aeb-a731-c06dfeccd4c9.png)
