### ISSUE TITLE
Taro 3.5.6: uploadFile 上传文件始终报跨域问题

### ISSUE THREAD

**Issue by hqwlkj** [NervJS/taro#12642]
### 相关平台
H5

**浏览器版本: Google Chrome 版本 105.0.5195.125（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
```tsx
//图片上传
  const handleUploadImage = useCallback(() => {
    chooseImage({
      count,
      sizeType, sourceType,
      success(res) {
        const tempFiles = res.tempFiles;
        const file = tempFiles[0];
        showLoading({ title: '上传中...' });
        uploadFile({
      url: process.env.APP_HOST + "/common/aliyunoss", 
      filePath: filePath,
      name: "file",
      formData: formData,
      fileName: fileName,
      header: {
        Authorization: `Bearer ${getStorageSync(Constants.TOKEN)}`,
      },
      success: async (result) => {
        if (result.statusCode === HTTP_STATUS.FORBIDDEN) {
          await Taro.showToast({
            title: "没有权限访问",
            icon: "none",
          });
          await redirectTo({ url: "/login" });
        }
        const data = JSON.parse(result.data) as T;
        console.log('data', data);
      },
      fail: (error) => {
           console.log('error', error);
      },
    })
      }
    })
  }, [count, onChange, sizeType, sourceType]);
```

注：此代码在 Taro 3.4.x 版本没有问题

### 期望结果
能够正常上传图片

### 实际结果
`Access to XMLHttpRequest at 'https://sagittarius-api.parsec.com.cn/common/aliyunoss' from origin 'http://192.168.65.6:10086' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 11.6.8
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0 

```

**Comment by TheKonka** [comment]
Duplicate of #12520 
下个版本修复

**Comment by hqwlkj** [comment]
> Duplicate of #12520 下个版本修复 #12619 需要手动传入
> 
> ```js
> withCredentials: false
> ```

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/12181423/195058641-9958088c-a6ee-4efc-96b7-6b7628e9b038.png">
加了还是会存在这个问题

**Comment by TheKonka** [comment]
> > Duplicate of #12520 下个版本修复 #12619 需要手动传入
> > ```js
> > withCredentials: false
> > ```
> 
> <img alt="image" width="1277" src="https://user-images.githubusercontent.com/12181423/195058641-9958088c-a6ee-4efc-96b7-6b7628e9b038.png">
> 加了还是会存在这个问题
> 
> ```tsx
> uploadFile({
>       url: process.env.APP_HOST + "/common/aliyunoss", //仅为示例，非真实的接口地址
>       filePath: filePath,
>       name: "file",
>       formData: formData,
>       fileName: fileName,
>       withCredentials: false,
>       header: {
>         Authorization: `Bearer ${getStorageSync(Constants.TOKEN)}`,
>       },
>       success: async (result) => {}
> ...
> ```

还没有发布哦，刚改好，得等下个版本发布

**Comment by hqwlkj** [comment]
那现在有什么代替方案吗？

**Comment by TheKonka** [comment]
> 那现在有什么代替方案吗？

可以手动修改下 `node_modules`里的代码
![image](https://user-images.githubusercontent.com/22173084/195305327-efada291-5dd5-4970-b3c2-69ed37dca4d2.png)

**Comment by hqwlkj** [comment]
按照你上面的 操作我处理了，但是并没有生效😂

![image](https://user-images.githubusercontent.com/12181423/195379441-a050c15a-5bce-4c61-99a9-a0f45ffd0db4.png)
![image](https://user-images.githubusercontent.com/12181423/195380375-406ba1da-36ae-42d5-80d5-3f35dcfe1ee0.png)

**Comment by hqwlkj** [comment]
感谢，还是希望能尽快发布一版 😄

**Comment by hqwlkj** [comment]
@luckyadam  这个功能能不能先修复一下。

**Comment by Chen-jj** [comment]
3.5.7 修复

**Comment by hqwlkj** [comment]
> 3.5.7 修复

今天发版吗？
