### ISSUE TITLE
Taro.createSelectorQuery().select('#canvas')获取不到canvas实例，在h5

### ISSUE THREAD

**Issue by xianguoGou** [NervJS/taro#12649]
### 相关平台
H5

**浏览器版本: Google Chrome 版本 106.0.5249.103（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
```
const Page = () => {
  const save = () => {
    Taro.createSelectorQuery().select('#canvas').fields({ node: true, size: true }).exec(res => {
      console.log('node',res[0].node) // undefined
    })
  }
  return (
    <View >
      <View onClick={save}>保存头像</View>
      <Canvas
        id="canvas"
        type="2d"
      ></Canvas>
  </View>
  )
}

export default Page
```

### 期望结果
能获取到canvas实例节点

### 实际结果
只能拿到width和height，没有node实例

### 环境信息
```
👽 Taro v3.3.1


  Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.1 => 3.3.1 
      @tarojs/mini-runner: 3.3.1 => 3.3.1 
      @tarojs/react: 3.3.1 => 3.3.1 
      @tarojs/runtime: 3.3.1 => 3.3.1 
      @tarojs/taro: 3.3.1 => 3.3.1 
      @tarojs/webpack-runner: 3.3.1 => 3.3.1 
      babel-preset-taro: 3.3.1 => 3.3.1 
      eslint-config-taro: 3.3.1 => 3.3.1 
      react: ^17.0.0 => 17.0.2 
      taro-ui: 3.0.0-alpha.10 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.6.3
```

**Comment by fan-shi-jun** [comment]
可以试一下这种写法：
  <Canvas style={` position: absolute; top: 0; left: 0; z-index: 0;`} className='Fcanvas' canvasId={this.state.CanvasId} />

   this.ctx = Taro.createCanvasContext(this.state.CanvasId)

**Comment by xianguoGou** [comment]
> Taro.createSelectorQuery()

不行，我是要拿到canvas 实例 node， 问题在于Taro.createSelectorQuery()方法里获取不到canvas node
```
 Taro.createSelectorQuery().select('#canvas').fields({ node: true, size: true }).exec(res => {
      console.log('node',res[0].node) // undefined
    })
```

**Comment by TheKonka** [comment]
> > Taro.createSelectorQuery()
> 
> 不行，我是要拿到canvas 实例 node， 问题在于Taro.createSelectorQuery()方法里获取不到canvas node
> 
> ```
>  Taro.createSelectorQuery().select('#canvas').fields({ node: true, size: true }).exec(res => {
>       console.log('node',res[0].node) // undefined
>     })
> ```

看了下`taro`这块应该还没有完善好，不过另一种方法应该可以获取到
```js
Taro.createSelectorQuery().node(console.log).exec()
```

**Comment by xianguoGou** [comment]
> 

Taro3.3.1支持吗？ 我这报错了。`Uncaught TypeError: Object(...)(...).select(...).node is not a function`

```
Taro.createSelectorQuery().select('#canvas').node(res => {
      console.log('res',res)
    }).exec()
....
<Canvas
    id="canvas"
    type="2d"
 ></Canvas>
```

**Comment by TheKonka** [comment]
> > 
> 
> Taro3.3.1支持吗？ 我这报错了。`Uncaught TypeError: Object(...)(...).select(...).node is not a function`
> 
> ```
> Taro.createSelectorQuery().select('#canvas').node(res => {
>       console.log('res',res)
>     }).exec()
> ....
> <Canvas
>     id="canvas"
>     type="2d"
>  ></Canvas>
> ```

https://github.com/NervJS/taro/commit/1c211e56ad72bc9500352d5bb6900f3ec279d7ff
升级到3.3.20看看

**Comment by xianguoGou** [comment]
> 

升级到3.3.20， 还是报相同的错

**Comment by xianguoGou** [comment]
> > > 
> > 
> > 
> > Taro3.3.1支持吗？ 我这报错了。`Uncaught TypeError: Object(...)(...).select(...).node is not a function`
> > ```
> > Taro.createSelectorQuery().select('#canvas').node(res => {
> >       console.log('res',res)
> >     }).exec()
> > ....
> > <Canvas
> >     id="canvas"
> >     type="2d"
> >  ></Canvas>
> > ```
> 
> [1c211e5](https://github.com/NervJS/taro/commit/1c211e56ad72bc9500352d5bb6900f3ec279d7ff) 升级到3.3.20看看

是不支持h5?

**Comment by TheKonka** [comment]
> > > > 
> > > 
> > > 
> > > Taro3.3.1支持吗？ 我这报错了。`Uncaught TypeError: Object(...)(...).select(...).node is not a function`
> > > ```
> > > Taro.createSelectorQuery().select('#canvas').node(res => {
> > >       console.log('res',res)
> > >     }).exec()
> > > ....
> > > <Canvas
> > >     id="canvas"
> > >     type="2d"
> > >  ></Canvas>
> > > ```
> > 
> > 
> > [1c211e5](https://github.com/NervJS/taro/commit/1c211e56ad72bc9500352d5bb6900f3ec279d7ff) 升级到3.3.20看看
> 
> 是不支持h5?

支持的，我自己用`3.3.20`版本试了一下，发现不知道为什么，需要加一下延时才能获取到
```js
setTimeout(() => {
  Taro.createSelectorQuery().select('#canvas').node(console.log).exec()
}, 100);
```
推荐不用 `@tarojs/components` 里引入的 `Canvas` ，使用 原生的`canvas`，这样不需要延时直接能获取到

**Comment by xianguoGou** [comment]
> 

而且 taro3.3.1 升级到taro3.3.20，启动h5还报错了。
<img width="866" alt="image" src="https://user-images.githubusercontent.com/56954233/196101205-87c1b0d1-211d-41b9-9873-3f5007d104cd.png">

**Comment by ZakaryCode** [comment]
> Taro3.3.1支持吗？ 我这报错了。`Uncaught TypeError: Object(...)(...).select(...).node is not a function`

这是 3.3.20+ 支持的特性

> 支持的，我自己用`3.3.20`版本试了一下，发现不知道为什么，如果是初次渲染的话，需要加一下延时才能获取到
> 推荐不用 `@tarojs/components` 里引入的 `Canvas` ，使用 原生的`canvas`，这样不需要延时直接能获取到

可能和获取节点依赖的参数有关系，部分参数赋值时间较晚 🤔 可以在新的 issue 跟进该问题

> 而且 taro3.3.1 升级到taro3.3.20，启动h5还报错了。 <img alt="image" width="866" src="https://user-images.githubusercontent.com/56954233/196101205-87c1b0d1-211d-41b9-9873-3f5007d104cd.png">

看起来是依赖版本未对齐导致的，可以尝试重置依赖后重新运行项目

**Comment by xianguoGou** [comment]
> > Taro3.3.1支持吗？ 我这报错了。`Uncaught TypeError: Object(...)(...).select(...).node is not a function`
> 
> 这是 3.3.20+ 支持的特性
> 
> > 支持的，我自己用`3.3.20`版本试了一下，发现不知道为什么，如果是初次渲染的话，需要加一下延时才能获取到
> > 推荐不用 `@tarojs/components` 里引入的 `Canvas` ，使用 原生的`canvas`，这样不需要延时直接能获取到
> 
> 可能和获取节点依赖的参数有关系，部分参数赋值时间较晚 🤔 可以在新的 issue 跟进该问题
> 
> > 而且 taro3.3.1 升级到taro3.3.20，启动h5还报错了。 <img alt="image" width="866" src="https://user-images.githubusercontent.com/56954233/196101205-87c1b0d1-211d-41b9-9873-3f5007d104cd.png">
> 
> 看起来是依赖版本未对齐导致的，可以尝试重置依赖后重新运行项目

我用taro3.3.20版本重新初始化了一个项目是可以的，但是从3.3.1升级到20就不行（ps：依赖版本全都切换了）

**Comment by xianguoGou** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/56954233/196318581-8943f1f0-c9df-496e-835e-2081112790fa.png">
<img width="433" alt="image" src="https://user-images.githubusercontent.com/56954233/196318621-d19d1adb-ff8b-43a8-9424-4ef560118888.png">

**Comment by ZakaryCode** [comment]
> 我用taro3.3.20版本重新初始化了一个项目是可以的，但是从3.3.1升级到20就不行（ps：依赖版本全都切换了）

这应该只是有遗漏，或者是没有删除 lock 导致的
