### ISSUE TITLE
Taro 3.5.6版本，支付宝小程序创建worker问题

### ISSUE THREAD

**Issue by lingdulib** [NervJS/taro#12640]
### 相关平台
支付宝小程序

**小程序基础库: 2.7.21**
**使用框架: Vue 3**

### 复现步骤
在app.ts中初始化worker： 
const worker= Taro.createWorker('workers/request/index.js') 
console.log("worker:::" worker) 
模拟器输出：worker:::[object Object] 
真机输出:undefined 

### 期望结果
输出worker创建的对象

### 实际结果
真机输出的是undefined 

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@lingdulib 根据支付宝小程序文档，使用 worker 有一系列配置工作：

![image](https://user-images.githubusercontent.com/11807297/196108925-5af0855b-db8f-4490-95bf-37e260f7bf10.png)

可以先确认一下是否都按文档进行配置了。与 Taro 有关的只有你需要使用 [copy](https://docs.taro.zone/docs/config-detail#copy) 把对应的 worker JS 文件拷贝到 dist 产物中。

如果还有问题，可以尝试使用原生写法试试，或到支付宝小程序社区咨询。

**Comment by CrazyOctopusDan** [comment]
请问怎么使用对应小程序的命名空间？
