### ISSUE TITLE
在h5中行内样式与css样式不统一

### ISSUE THREAD

**Issue by fan-shi-jun** [NervJS/taro#12652]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
在页面中写入两个view，设置其宽度与字体大小。期望行内样式与css样式统一，在h5页面，css样式被转化为0.625 rem，而行内样式为0.5334rem

<View style={{fontSize:Taro.pxTransform(25),width:Taro.pxTransform(25),backgroundColor:'blue'}}>
          22222
        </View>
        <View className='testStyle' style={{backgroundColor:'blue'}}>
          222222222
        </View>
.testStyle{
    font-size: 25px;
    width: 25px;
}

### 期望结果
css样式与行内样式统一

### 实际结果
都是25px但是转化后结果不同。

### 环境信息
```
 Taro CLI 3.3.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD  
```

---
### 补充信息

经过排查，taro采用的css转换器（postcss-pxtransform）是基于config中的deviceRatio比例来进行转换的，在deviceRatio为1时，40px=1rem。

而taro提供的行内样式转换器代码如下：
const pxTransform = function (size) {
    // @ts-ignore
    const { designWidth } = taro.config;
    return Math.ceil((((parseInt(size, 10) / 40) * 640) / designWidth) * 10000) / 10000   'rem';
};

不难看出，行内样式是基于designWidth来进行转化的。在designWidth=640时，40px=1rem。所以两个转换方式基于的config参数并不同。我在修改config后样式统一了，但是并不是长久之计。

错误的config（官方自带）：
const config = {
  designWidth: 750,
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
    375: 1 / 2
  },}
修改后正常的config：
const config = {
  designWidth: 640,
  deviceRatio: {
    640: 1
  },

**Comment by ZakaryCode** [comment]
这是一个旧版本问题，在最新的版本中已经修复
