### ISSUE TITLE
WARNING in ./node_modules/@tarojs/plugin-html/dist/runtime.js 351:0-5 "export 'hooks' was not found in '@tarojs/shared'  @ ./src/app.ts

### ISSUE THREAD

**Issue by Locter9001** [NervJS/taro#12658]
### 相关平台
微信小程序

**小程序基础库: 2.17.3**
**使用框架: Vue 3**

### 复现步骤
yarn install 后出现这个问题
WARNING in ./node_modules/@tarojs/plugin-html/dist/runtime.js 351:0-5
"export 'hooks' was not found in '@tarojs/shared'
 @ ./src/app.ts

![image](https://user-images.githubusercontent.com/96331179/195970684-e52cb14e-2ff3-466d-816a-907680de8043.png)

### 期望结果
成功跑起来

### 实际结果
跑不起来

### 环境信息
```
👽 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.0 - F:\SDK_ALL\NodeJs\node.EXE
      Yarn: 1.22.19 - f:\SDK_ALL\Yarn\bin\yarn.CMD
      npm: 8.19.2 - F:\SDK_ALL\NodeJs\npm.CMD
```

**Comment by Chen-jj** [comment]
Taro CLI 和项目内的 Taro 相关依赖的版本要保持一致。
