### ISSUE TITLE
字节小程序pay-button组件引入无法使用

### ISSUE THREAD

**Issue by Tanoshi0625** [NervJS/taro#12654]
### 相关平台
字节跳动小程序

**小程序基础库: 2.70.0.5**
**使用框架: Vue 3**

### 复现步骤
因字节小程序 pay-button组件未支持，所以建议使用原生组件引用方式。
```
export default definePageConfig({
  navigationBarTitleText: "订单确认页",
  usingComponents: {
    "tt-pay-button": "../../components/pay-button/pay-button",
  },
});

但是会提示：[Vue warn]: Failed to resolve component: tt-pay-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
且功能都无法使用，是否vue版本暂时不兼容呢？请麻烦给一个实例。
并且getThemeConfig函数在app.js里如何调用，直接在onShow里调用可以吗？

### 期望结果
正常使用pay-button组件

### 实际结果
正常使用pay-button组件

### 环境信息
```
👽 Taro v3.5.6

  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.11 => 3.4.11 
      @tarojs/components: 3.4.11 => 3.4.11 
      @tarojs/mini-runner: 3.4.11 => 3.4.11 
      @tarojs/plugin-framework-vue3: 3.4.11 => 3.4.11 
      @tarojs/plugin-html: 3.4.11 => 3.4.11 
      @tarojs/plugin-mini-ci: ^3.4.11 => 3.4.11 
      @tarojs/runtime: 3.4.11 => 3.4.11 
      @tarojs/taro: 3.4.11 => 3.4.11 
      @tarojs/webpack-runner: 3.4.11 => 3.4.11 
      babel-preset-taro: 3.4.11 => 3.4.11 
      eslint-config-taro: 3.4.11 => 3.4.11 
```


---
### 补充信息
使用字节官方给出的react-demo并未有问题，但是由于没有vue-demo。也未认证是否有同样的问题。案例也不多，能参考的太少了

<!-- generated by taro-issues. 请勿修改或删除此行注释 --><!--labels=T-tt,V-3,F-vue3-->

**Comment by Tanoshi0625** [comment]
补上demo地址：
[demo](https://github.com/Tanoshi0625/pay-demo)

**Comment by Chen-jj** [comment]
Taro v3.5.7 开始可以支持使用 `pay-button`

duplicate #12650

**Comment by Tanoshi0625** [comment]
@Chen-jj 您好，请问我这个demo中的。使用原生的pay-button 然后引入也不支持吗
