### ISSUE TITLE
navigateTo中用encodeURIComponent，在新页面的$router中被decode了

### ISSUE THREAD

**Issue by hereisfun** [NervJS/taro#1265]
**问题描述**
navigateTo中用encodeURIComponent，在新页面的$router中被decode了

**复现步骤**
```js
// url: /pages/issues?url=id%3D1234
const url = `/pages/issues?url=${encodeURIComponent('id=1234')}`
Taro.navigateTo({ url })

// 在新页面中
componentDidMount () {
    // fullUrl: "/pages/issues/index?url=id=1234"
    console.log('this.$router', this.$router.fullUrl) 
}
```

**期望行为**
在新页面中的$router.fullUrl与navigateTo中传入的url一致

**系统信息**

 - 操作系统: [MacOS Mojave 10.14.1 (18B75)]
 - Taro 版本 [v1.2.0-beta.2]
 - Node.js 版本 [v10.4.0]
 - 报错平台 [h5]

**补充信息**
https://github.com/NervJS/taro/blob/a376b79d844b30d7da0d77a4075ca575363f86b9/packages/taro-router/src/lib/utils.ts#L77

**Comment by Littly** [comment]
更新到最新版试试，应该不存在这个问题了。

**Comment by minetsh** [comment]
这个问题还存在呀，没有被修复呀

**Comment by saralee2012** [comment]
1.3.37版本的taro 这个问题也还存在
