### ISSUE TITLE
h5 点击 Text 让另一个 Textarea 获取焦点

### ISSUE THREAD

**Issue by bluescurry** [NervJS/taro#12668]
### 这个特性解决了什么问题？
现在有一个场景，希望点击一个 View 元素之后，让下面的Textarea 自动获取焦点，请问该如何实现呢

### 这个 API 长什么样？
我尝试了给 Textarea 绑定一个 useRef，但通过 useRef.current.focus() 方法无法使其自动获取焦点

**Comment by ZakaryCode** [comment]
使用 ref 获取到的是外层节点 `taro-textarea-core`，需要获取其子节点如下

```js
useRef.current.children[0]. focus()
```
