### ISSUE TITLE
css modules 处理样式文件规则与 `create-react-app` 保持一致

### ISSUE THREAD

**Issue by lbb00** [NervJS/taro#1266]
> 还是就按照 create-react-app 的规范来更具有一致性，就是以 .module.css 结尾的就按 css modules 处理，其他的都是全局

https://github.com/NervJS/taro/pull/933#issuecomment-435396880

css modules 是一个额外的附加功能，不应该在开启后影响原有的模式。

讨论并追踪一下？

**Comment by tourze** [comment]
合理

**Comment by icodytan** [comment]
@loveonelong @luckyadam 可以考虑像 umi 最近在讨论的 [通用 css modules 方案](https://github.com/umijs/umi/issues/1417)
