### ISSUE TITLE
@tarojs/cli创建和启动项目报错

### ISSUE THREAD

**Issue by WalkerChan2019** [NervJS/taro#12676]
我使用@tarojs/cli创建和启动项目遇到令我十分困惑的问题：
1. v1.3.9时，提示“× 拉取远程模板仓库失败！”
![QQ截图20221018172640](https://user-images.githubusercontent.com/53211980/196393832-12ba3f69-db7e-4246-9d4a-b5a86e1d7366.png)
2. 最新版本v3.5.6时，报：@tarojs\service\dist\utils\index.js:75  throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
![QQ截图20221018172731](https://user-images.githubusercontent.com/53211980/196393851-415ddab8-7eb7-4a76-a3f0-3a0c5b402be3.png)
3. 启动公司项目，报错类似
![QQ截图20221018172953](https://user-images.githubusercontent.com/53211980/196393858-f5d15ca9-1e3c-46e7-83df-2cac0e265853.png)

**Comment by Chen-jj** [comment]
swc 1.3.8 存在问题

**Comment by weaeqqq** [comment]
要怎么解决，最新的taro版本3.5.6遇到 throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`)

**Comment by justwe7** [comment]
我把node升到18可以用3.5.6，或者低版本的用3.4.x也可以 #12171

**Comment by weaeqqq** [comment]
刚nvm试了node升级到v18.9.0还是会出现swc这个报错问题

**Comment by Chen-jj** [comment]
据反馈，应该是安装 `@swc/core@1.3.9` 时没有安装对应系统的可执行文件导致。非必现。

猜测可能与各位的**系统、Node 版本、包管理工具及其版本、registry、网络环境**等相关。

因此需要各位提供以上信息再作分析。

**Comment by weaeqqq** [comment]
node升级后还是出现这个swc问题，将taro指定到3.4.x就没有这个问题了

**Comment by weaeqqq** [comment]
> 据反馈，应该是安装 `@swc/core` 时（与 swc 版本无关）没有安装对应系统的可执行文件导致。非必现。
> 
> 猜测可能与各位的**系统、Node 版本、包管理工具及其版本、registry、网络环境**等相关。
> 
> 因此需要各位提供以上信息再作分析。

这种问题怎么解决好点，看别人出现的也比较多

**Comment by 1oo1** [comment]
我也遇到了类似的问题，供遇到类似问题的朋友参考。

我是小程序旧项目，从 3.4.9 升级到 3.5.6 后编译出错，经排查是语法不被 swc 识别导致。

**排查过程：**

1、排查异常堆栈信息，出错的地方在 swc，再往上看调用栈，有一行` at readConfig (/xxxx/xxx/xxx/node_modules/@tarojs/helper/src/utils.ts:659:37)`；

2、这是 source map 里的代码行数，比较幸运的是在 `@tarojs/helper/dist/utils.js`  里找到了 readConfig 方法，里面有 swcRegister 的调用，在方法第一行打印log：`console.log('================ 可能有问题的文件', configPath);`

3、执行 taro build，找到报错的代码文件，有问题的原代码比较简单，是page的配置文件：

```ts
const config = {
  allowsBounceVertical: 'NO',
  pullRefresh: 'false'
};

export default config;
```

4、随便对比了两个打印的正常编译的其他配置文件后，更改为下面形式后修复了  swc 的编译问题：

```ts
export default {
  allowsBounceVertical: 'NO',
  pullRefresh: 'false'
};

```

**Comment by jyx12138** [comment]
请问，不指到3.4.x情况下怎么解决？

**Comment by jyx12138** [comment]
> 请问，不指到3.4.x情况下怎么解决？

我这里是删除依赖，改用yarn ，重新install之后正常了，仅供参考

**Comment by roftLin** [comment]
Hey buddy, I have encountered the same issue as you and have solved it, I would like to share my experience with you to see if it can help.
Just a few days ago I was able to install Taro-cli without any issues, then after reinstalling the system, my project encountered the same error as yours. I searched for solutions in the Taro repository and the SWC repository, but there was no ready answer. However, they gave some directions to troubleshoot.
So I tried switching the node version, package manager version and source, and Taro/cli version, but all failed. Finally, I debugged the source code with breakpoints, combined with my own experience, and found that the problem was related to the rust runtime environment, which needed to be installed. The specific installation method can be referred to the link below.
https://blog.csdn.net/u011149152/article/details/123518465

**Comment by TheKonka** [comment]
今天把全局 `taro`版本切到`1.3` 又切到 `3.6`时遇到了，最后重新安装 `tarojs/cli` 最新版本解决了

**Comment by sharesTeam** [comment]
安装windows C++环境 [](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by next-autumn** [comment]
执行 taro init myApp 报错

`Error: Bindings not found
    at Compiler.transformSync (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@swc\core\index.js:250:15)
    at Object.transformSync (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@swc\core\index.js:348:21)
    at compile (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@swc\register\lib\node.js:76:22)
    at compileHook (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@swc\register\lib\node.js:91:16)
    at Module._compile (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\pirates\lib\index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader [as .js] (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\utils\index.js:75
                    throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
                          ^

Error: 插件依赖 "C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\presets\index.js" 加载失败，请检查插件配置
    at apply (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\utils\index.js:75:27)
    at Kernel.initPreset (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:94:38)
    at Kernel.resolvePresets (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:79:18)
    at Kernel.initPresetsAndPlugins (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:73:14)
    at Kernel.<anonymous> (C:\Users\m1814\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modul`

**Comment by MagicHacker** [comment]
3.6.2版本遇到相同的问题

**Comment by sparkKenzo** [comment]
> 有效,安装Microsoft Visual C++就可以了

**Comment by D2073620106** [comment]
安装Microsoft Visual C++运行起来了，这个问题真恶心 ，下载地址：https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by CinseYoung** [comment]
> 

可以! 解决问题了

**Comment by rbmonster** [comment]
> Hey buddy, I have encountered the same issue as you and have solved it, I would like to share my experience with you to see if it can help. Just a few days ago I was able to install Taro-cli without any issues, then after reinstalling the system, my project encountered the same error as yours. I searched for solutions in the Taro repository and the SWC repository, but there was no ready answer. However, they gave some directions to troubleshoot. So I tried switching the node version, package manager version and source, and Taro/cli version, but all failed. Finally, I debugged the source code with breakpoints, combined with my own experience, and found that the problem was related to the rust runtime environment, which needed to be installed. The specific installation method can be referred to the link below. https://blog.csdn.net/u011149152/article/details/123518465

Thanks bro. install rust environment solved my problem.
