### ISSUE TITLE
如何定义环境变量在src/*的代码中来区分类似【开发／测试／正式】的多个运行时环境呢?

### ISSUE THREAD

**Issue by yzStrive** [NervJS/taro#1268]
**问题描述**
某些业务场景的有些变量需要在不同的环境下为不同的值，查阅Taro官网文档和搜索相关issue，我没有找到解决方案。

**试过的解决方案**
package.json中对应的scripts前面加上NODE_ENV，在Taro的config/*下面的文件中能获取到对应的值，但是在src/*中获取不到

**期望行为**
能够在src/*的文件中能够获取运行环境

**系统信息**

 - 操作系统: [macOs 10.12.6]
 - Taro 版本 [@tarojs/cli 1.1.4]
 - Node.js 版本 [v8.12.0]
 - 平台 [ weapp]

**Comment by luckyadam** [comment]
升级到最新的版本吧，然后可以通过在 config 中配置 `env`
https://nervjs.github.io/taro/docs/config-detail.html#env
或者通过命令附加环境变量来做
```
NODE_ENV=production taro build --type weapp --watch
```

**Comment by yzStrive** [comment]
thx,搞定了。package.json的scripts里面的NODE_ENV变量被config/dev.js,config/prod.js默认配置中的env覆盖掉了，改掉就好了。
