### ISSUE TITLE
scroll-view / scroll-into-view （vue版本无效）

### ISSUE THREAD

**Issue by jshuhao** [NervJS/taro#12709]
### 相关平台
微信小程序

**小程序基础库: 8.0.28**
**使用框架: Vue 2**

### 复现步骤
 ``` <template>
   <scroll-view scroll-y="true"
                 style="height: 300rpx;"
                 scroll-into-view="demo2">
      <view id="demo1"
            class="scroll-view-item demo-text-1"></view>
      <view id="demo2"
            class="scroll-view-item demo-text-2"></view>
      <view id="demo3"
            class="scroll-view-item demo-text-3"></view>
    </scroll-view>
</template>

<style  lang="scss">
.scroll-view-item{
  height: 300rpx;
}
.demo-text-1{
  position: relative;
  align-items: center;
  justify-content: center;
  background-color: #1AAD19;
  color: #FFFFFF;
  font-size: 36rpx;
}
.demo-text-1:before{
  content: 'A';
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.demo-text-2{
  position: relative;
  align-items: center;
  justify-content: center;
  background-color: #2782D7;
  color: #FFFFFF;
  font-size: 36rpx;
}
.demo-text-2:before{
  content: 'B';
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
.demo-text-3{
  position: relative;
  align-items: center;
  justify-content: center;
  background-color: #F1F1F1;
  color: #353535;
  font-size: 36rpx;
}
.demo-text-3:before{
  content: 'C';
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>
 ``` 

### 期望结果
期望y轴滚动到id为demo2的位置

### 实际结果
没有效果，此代码在原生微信小程序可以滚动至指定位置

### 环境信息
```
  Taro CLI 3.5.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
3.5.5 / 3.5.6 都无法正常使用

**Comment by Chen-jj** [comment]
@jshuhao 麻烦提供一下完整的 demo

**Comment by jshuhao** [comment]
> @jshuhao 麻烦提供一下完整的 demo

https://github.com/jshuhao/taro-demo.git 
此例子采用的是官方demo，预期滚动到demo2的位置，实际没效果

**Comment by Chen-jj** [comment]
@jshuhao 初始化的时候 `scroll-into-view` 是不起作用的，也测试过微信原生语法也是一样，你可以试试：

![image](https://user-images.githubusercontent.com/11807297/200251654-f4e923d5-89fd-4e52-a605-7b066b4008fb.png)

```xml
<view class="container">
  <view class="page-body">
    <view class="page-section">
      <view class="page-section-title">
        <text bindtap="eh">Vertical Scroll - 纵向滚动</text>
      </view>
      <view class="page-section-spacing">
        <scroll-view scroll-y="{{true}}"
                      style="height: 300rpx;"
                      scroll-into-view="{{toView}}"
                      scroll-top="{{scrollTop}}"
                      >
          <view id="demo1"
                class="scroll-view-item demo-text-1">1</view>
          <view id="demo2"
                class="scroll-view-item demo-text-2">2</view>
          <view id="demo3"
                class="scroll-view-item demo-text-3">3</view>
        </scroll-view>
      </view>
    </view>
  </view>
</view>
```

```js
Page({
  data: {
    scrollTop: 0,
    toView: 'demo2'
  }
})
```

**Comment by jshuhao** [comment]
> @jshuhao 初始化的时候 `scroll-into-view` 是不起作用的，也测试过微信原生语法也是一样，你可以试试：
> 
> ![image](https://user-images.githubusercontent.com/11807297/200251654-f4e923d5-89fd-4e52-a605-7b066b4008fb.png)
> 
> ```
> <view class="container">
>   <view class="page-body">
>     <view class="page-section">
>       <view class="page-section-title">
>         <text bindtap="eh">Vertical Scroll - 纵向滚动</text>
>       </view>
>       <view class="page-section-spacing">
>         <scroll-view scroll-y="{{true}}"
>                       style="height: 300rpx;"
>                       scroll-into-view="{{toView}}"
>                       scroll-top="{{scrollTop}}"
>                       >
>           <view id="demo1"
>                 class="scroll-view-item demo-text-1">1</view>
>           <view id="demo2"
>                 class="scroll-view-item demo-text-2">2</view>
>           <view id="demo3"
>                 class="scroll-view-item demo-text-3">3</view>
>         </scroll-view>
>       </view>
>     </view>
>   </view>
> </view>
> ```
> 
> ```js
> Page({
>   data: {
>     scrollTop: 0,
>     toView: 'demo2'
>   }
> })
> ```

应该是我表达的不太清楚，你可以scroll-top这个属性去掉再试一下，微信小程序上面是可以的正常初始化滚动，但是taro去掉这个属性和原生的表现不太一致

**Comment by jshuhao** [comment]
原生
![1667807182544](https://user-images.githubusercontent.com/43402557/200254128-9d899f90-e5d7-4ad6-9fc2-fbefab23ce7d.jpg)
![1667807190827](https://user-images.githubusercontent.com/43402557/200254145-022df90b-5136-4de3-9dd5-cf1f0a7101be.jpg)

taro
![image](https://user-images.githubusercontent.com/43402557/200254284-a7868562-a853-4119-95ba-1b5461826c79.png)
![1667807304871](https://user-images.githubusercontent.com/43402557/200254355-3fcac35b-7643-457c-bc1e-facd94999eae.jpg)
@Chen-jj  你试试看呢

**Comment by jshuhao** [comment]
![image](https://user-images.githubusercontent.com/43402557/200255385-ffaa5627-aa1e-49c2-94f4-688e4dbd372c.png)
![image](https://user-images.githubusercontent.com/43402557/200255384-be9f8228-2571-4070-be9f-464dd2c8517b.png)
我推测是taro内部scroll-top设置了默认值？如何将这个默认值取消呢 @Chen-jj

**Comment by Chen-jj** [comment]
@jshuhao 的确是由 `scroll-top` 属性引起。**微信小程序中，只要 `scroll-view` 组件上声明了 `scroll-top` 属性，初始化渲染时 `scroll-into-view` 就不会生效**。

又因为 Taro3 的实现机制令到 `dist/base.wxml` 中的 `scroll-view` 必须把所有属性都提前声明，包括 `scroll-top` 属性，。以只能在初始渲染后再设置 `scroll-into-view` 来绕过了：

```js
export default {
  name: 'Index',
  data () {
    return {
      toView: undefined
    }
  },
  onReady () {
    this.toView = 'demo2'
  }
}
```

**Comment by jshuhao** [comment]
> scroll-view

好的，感谢你的解惑
