### ISSUE TITLE
在app.js中怎么获取 在 其他 页面 自定义的 getApp().appCallback ？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1271]
在app.js中怎么获取 在 其他 页面 自定义的 getApp().appCallback ？

小程序初始化时触发App里的onLaunch，后面再执行页面Page里的onLoad，但是在onLaunch里请求获取是否有权限，等待返回值的时候Page里的onLoad事件就已经执行了，所以我在  页面Page 里 给 定义一个app方法（回调函数）getApp().appCallback,在 app 的 onLaunch中获取有权限后，执行！
但是在 app.js 中 ，this.appCallback 总是 undefined!
参考：[https://www.jianshu.com/p/aaf65625fc9d]

**系统信息**

 - 操作系统: [e.g.Mac Pro]
 - Taro 版本 [e.g. v.1.0.8]
 - Node.js 版本 [e.g. v11]
 - 报错平台 [weapp]

**Comment by JoMartinezZhu** [comment]
> 没有这样的操作，你可以用 promise

不是很理解！

**Comment by lyboy2012** [comment]
app 上定义的非生命周期方法，通过Taro.getAPP() 获取不到
![image](https://user-images.githubusercontent.com/3926781/59494004-cf0a4d00-8ebe-11e9-8c57-35dabd5f5434.png)
![image](https://user-images.githubusercontent.com/3926781/59494022-d92c4b80-8ebe-11e9-97de-e30f30ea6291.png)

**Comment by tourze** [comment]
> app 上定义的非生命周期方法，通过Taro.getAPP() 获取不到

请问这个问题解决了吗。。
