### ISSUE TITLE
this.$scope.selectComponent无法获取子组件未绑定事件的方法

### ISSUE THREAD

**Issue by dagangwuyanzu** [NervJS/taro#12717]
### 这个特性解决了什么问题？
子组件定义了一个opne方法与add方法，open方法没有在render jsx代码中绑定给事件，add绑定了onClick 事件，在父组件中调用this.$scope.selectComponent获取子组件方法的时候只能获取add无法获取open

### 这个 API 长什么样？
就算没有在jsx中使用，父组件也应该可以正常使用

**Comment by dagangwuyanzu** [comment]
![image](https://user-images.githubusercontent.com/75358396/197988006-74e669aa-73f5-40bb-9520-7e7f444df842.png)

**Comment by Chen-jj** [comment]
@dagangwuyanzu 麻烦按 issue 模板新建 issue，且附上可复现的 demo
