### ISSUE TITLE
Taro3.5.7   发布的H5应用中使用Taro.chooseLocation在当前页面底部叠加显示，且页面样式乱；预览模式正常

### ISSUE THREAD

**Issue by zerolqn** [NervJS/taro#12729]
### 相关平台
H5

### 复现仓库
[https://gitee.com/rainLotus/test-taro-demo.git](https://gitee.com/rainLotus/test-taro-demo.git)
**浏览器版本: Chrome106,firefox106**
**使用框架: React**

### 复现步骤
1、taro init 创建的空白项目中，调用Taro.chooseLocation()
2、打包项目，nginx中部署发布
3、打开发布的H5项目，验证定位选择（定位选择会在当前页面底部显示出来，而非全屏显示）

### 期望结果
可以正常全屏显示。

### 实际结果
在当前页面的底部显示出来，而且样式错乱，点选地址获取不到结果。
点击多次调用chooseLocation()的话，会在页面底部显示多个。

### 环境信息
```
Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.2 - D:\tools\js\node-v14.19.2-win-x64\node.EXE
      Yarn: 1.22.18 - C:\Users\N-385\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.17 - D:\tools\js\node-v14.19.2-win-x64\npm.CMD
```

---
### 补充信息
问题效果同：https://github.com/NervJS/taro/issues/10958 该Issue显示在3.3.19中已经修复。验证了下，3.3.19版本，在发布模式下面，也依然是存在同样的问题。

**Comment by ZakaryCode** [comment]
fix in https://github.com/NervJS/taro/commit/4558347d732c66641aa526ed484a8573078be814

**Comment by zerolqn** [comment]
该问题在最新版V3.6.6中依旧存在，且预览时的样式也不对。3.5.11中显示的是正常的。
