### ISSUE TITLE
Taro  3.5.7 版本，H5环境  Taro.scanCode  无反应

### ISSUE THREAD

**Issue by zhengjieyuan** [NervJS/taro#12735]
### 相关平台
H5

### 复现仓库
[https://github.com/zhengjieyuan/taro-react-h5.git](https://github.com/zhengjieyuan/taro-react-h5.git)
**浏览器版本: Chrome 微信开发工具**
**使用框架: React**

### 复现步骤
安装taro 3.5.7 
工程下运行  cnpm i
npm run build:h5
文件上传到服务器上。

服务器已经获取微信扫一扫接口权限。  已成功配置 业务域名、JS接口安全域名、网页授权域名。
微信公众号通过菜单访问H5、微信开发工具访问H5页面，点击扫码无反应，提示  《《“ h5 端当前仅在微信公众号 JS-SDK 环境下支持此 API”。 》》

### 期望结果
功能正常使用

### 实际结果
点击扫码按钮，调用Taro.scanCode  无反应

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - D:\ProgramFiles\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\zjy\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - D:\ProgramFiles\nodejs\npm.CMD
```

---
### 补充信息
之前一直用taro开发小程序，没有遇到此问题。
1.是否需要在项目中间配置wx.config信息？
2.是否要在项目上安装 wx-sdk-js引用？
3.微信公众号是否还需要其它配置？   
4.微信公众号是否需要启动服务器配置？

**Comment by ZakaryCode** [comment]
可先验证 3.5.6 版本有无此问题 🤔

**Comment by zhengjieyuan** [comment]
> 可先验证 3.5.6 版本有无此问题 🤔
> 
> * 需要引入 wx-sdk-js，需要配置 wx.config
> * 可自行验证当前环境是否支持对应 API
> 
> ```js
> // 方法1
> wx.checkJsApi({
>   jsApiList: ['scanCode'], // 需要检测的 JS 接口列表
>   success: function(res) {
>   // 以键值对的形式返回，可用的 api 值true，不可用为false
>   // 如：{"checkResult":{"scanCode":true},"errMsg":"checkJsApi:ok"}
>   }
> })
> // 方法2
> typeof window?.wx?. scanCode === 'function'
> ```

3.5.6也存在同样问题。我现在按照wx官方文档尝试下。
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html
这种方式是使用微信原生api吧？

**Comment by ZakaryCode** [comment]
> 3.5.6也存在同样问题。我现在按照wx官方文档尝试下。 https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html 这种方式是使用微信原生api吧？

是的，需要在微信 JS-SDK 环境下才能使用

**Comment by zhengjieyuan** [comment]
已解决

**Comment by dawenxi897094320** [comment]
普通浏览器h5 Taro.scanCode 无法使用 ，怎么解决。
