### ISSUE TITLE
3.5.7 在插件页面 scrollView  不渲染

### ISSUE THREAD

**Issue by yanghu1015** [NervJS/taro#12741]
### 相关平台
微信小程序

**小程序基础库: 2.27.0**
**使用框架: React**

### 复现步骤
使用Taro 开发微信小程序插件，  taro版本为3.5.7
插件页面内使用ScrollView组件，编译过后  ide显示./base.wxml:template:169:16: Template `tmpl_0_36` not found.
scrollView 组件无法正常渲染

### 期望结果
插件页面内scrollView 组件可以正常渲染

### 实际结果
插件页面内scrollView 组件无法正常渲染

### 环境信息
```
� Taro v3.5.7


  Taro CLI 3.5.7 environment info:                                    
    System:                                                           
      OS: Windows 10                                                  
    Binaries:                                                         
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE                
      Yarn: 1.22.19 - C:\Users\banma-0523\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD     
```

**Comment by Chen-jj** [comment]
@yanghu1015 麻烦提供一下 demo

**Comment by yanghu1015** [comment]
@Chen-jj https://github.com/yanghu1015/taro3.5.7demo

**Comment by wojiaojiangyou** [comment]
@yanghu1015 这个有结论了吗 我好像也出现这个问题

**Comment by wojiaojiangyou** [comment]
@Chen-jj  大佬这个问题有没有解决方案呀

**Comment by Chen-jj** [comment]
我们尽快看看的

**Comment by Chen-jj** [comment]
3.5.11 已可以正常运行，可以升级下再试试

<img width="1622" alt="image" src="https://user-images.githubusercontent.com/11807297/212801408-7b6b3869-53c7-417a-b584-fe086d40328c.png">
