### ISSUE TITLE
不能将类型“{ key: number; }”分配给类型“TransformReact2VueType<ViewProps>”。

### ISSUE THREAD

**Issue by RiuHDuo** [NervJS/taro#12740]
### 相关平台
微信小程序

**小程序基础库: 8.0.28**
**使用框架: Vue 3**

### 复现步骤
```
  <view v-for="(item, index) in data.menus" v-bind:key="index">
          <view class="column center menu-item">
            <nut-icon :name="item.icon" size="48" />
            <view>{{ item.text }}</view>
          </view>
        </view>
```
![image](https://user-images.githubusercontent.com/830134/198954139-0d193365-a094-4397-870c-aa58a4e3bf65.png)

vscode里v-bind:key会报要给ts2322 
不能将类型“{ key: number; }”分配给类型“TransformReact2VueType<ViewProps>”。

### 期望结果
不报错

### 实际结果
vscode 提示 不能将类型“{ key: number; }”分配给类型“TransformReact2VueType<ViewProps>”。

### 环境信息
```
  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
根据提示信息在项目中无法复现该问题，应当是依赖安装错误导致的，需要详细信息才能进一步定位。

**Comment by chenchenpp** [comment]
> 

遇到相同的问题，tarojs版本3.5.7，tsconfig配置文件compilerOptions.types添加"@tarojs/components/vue3"后，会导致标签添加key报错。
初步查看taro定义，应该是剔除了key属性的缘故，请排查
![image](https://user-images.githubusercontent.com/33083284/202360274-39016d15-1683-4f6d-b8b9-4653dbba88cf.png)

**Comment by ZakaryCode** [comment]
> 遇到相同的问题，tarojs版本3.5.7，tsconfig配置文件compilerOptions.types添加"@tarojs/components/vue3"后，会导致标签添加key报错。 初步查看taro定义，应该是剔除了key属性的缘故，请排查 ![image](https://user-images.githubusercontent.com/33083284/202360274-39016d15-1683-4f6d-b8b9-4653dbba88cf.png)

与之无关，剔除 key 是因为 vue 中定义了与 react 不同的 key 类型

```ts
  key?: string | number | symbol;
```

**Comment by chenchenpp** [comment]
> > 遇到相同的问题，tarojs版本3.5.7，tsconfig配置文件compilerOptions.types添加"@tarojs/components/vue3"后，会导致标签添加key报错。 初步查看taro定义，应该是剔除了key属性的缘故，请排查 ![image](https://user-images.githubusercontent.com/33083284/202360274-39016d15-1683-4f6d-b8b9-4653dbba88cf.png)
> 
> 与之无关，剔除 key 是因为 vue 中定义了与 react 不同的 key 类型
> 
> ```ts
>   key?: string | number | symbol;
> ```

感谢回复。我明白您所说的差异。不过可结合楼主提问者，目前来看添加"@tarojs/components/vue3"后，使用**_小程序原生标签_**遍历，绑定key属性会引起如楼主一样的ts报错。目前解决的方式是使用taro的基础组件(如:View),不会有key报错的问题，查看两者的定义类来看，一个保留了key，一个去除了。
  view: TransformReact2VueType<ViewProps>
 declare const View: VueComponentType<ViewProps>
我的愚见是：是否可以在SlimProps里如重新定义style一般，定义key呢
![image](https://user-images.githubusercontent.com/33083284/202602697-1ba98d2c-f101-415a-baab-b36636c04a8d.png)
词不达意，还请大佬排查。

**Comment by wdssmq** [comment]
遇到同样问题，姑且把 view 改成了 div

**Comment by ZakaryCode** [comment]
> 感谢回复。我明白您所说的差异。不过可结合楼主提问者，目前来看添加"@tarojs/components/vue3"后，使用**_小程序原生标签_**遍历，绑定key属性会引起如楼主一样的ts报错。目前解决的方式是使用taro的基础组件(如:View),不会有key报错的问题，查看两者的定义类来看，一个保留了key，一个去除了。 view: TransformReact2VueType declare const View: VueComponentType 我的愚见是：是否可以在SlimProps里如重新定义style一般，定义key呢 ![image](https://user-images.githubusercontent.com/33083284/202602697-1ba98d2c-f101-415a-baab-b36636c04a8d.png) 词不达意，还请大佬排查。

key 在 Vue 官方提供的 DefineComponent 类型中会提供，不需要额外定义，这也是需要剔除 react 中 key 属性的原因。

目前无法通过提供示例复现该错误，请检查项目内实际的依赖类型，是否由于包管理器错误的安装依赖，导致不应存在的类型依赖被引入覆盖了相关类型。

**Comment by agileago** [comment]
@chenchenpp 模板的类型检查？你用的volar插件么？

**Comment by chenchenpp** [comment]
> @chenchenpp 模板的类型检查？你用的volar插件么？

是的。vue3当然要用volar

**Comment by agileago** [comment]
这里确实有问题

**Comment by chenchenpp** [comment]
> 这里确实有问题

是的，目前看来官方不认为这是个问题。所以只能自己加类型检测了。

**Comment by agileago** [comment]
https://github.com/vuejs/core/blob/f3e4f038bf299794b2ca4750b4678074660113c8/packages/runtime-dom/types/jsx.d.ts#L1311-L1324

关键现在是vue3没有把 `ReservedProps` 导出来，不好做交叉类型， vue3没考虑新增加自定义元素的类型定义

@ZakaryCode

**Comment by agileago** [comment]
貌似只能拷过来了

**Comment by chenchenpp** [comment]
> 貌似只能拷过来了或者给vue提个pr了

如果项目中导入了@tarojs/components/types/index.vue3，我不觉得这是vue的问题，因为view标签约束是用的taro的类型约束。

**Comment by agileago** [comment]
我知道，taro类型那里没有合并 `ReservedProps` 所以导致原始类型报错， 但是 vue 没有导出 `ReservedProps`

**Comment by agileago** [comment]
给 vue 提了个 pr   https://github.com/vuejs/core/pull/7212

**Comment by chenchenpp** [comment]
> 我知道，taro类型那里没有合并 `ReservedProps` 所以导致原始类型报错， 但是 vue 没有导出 `ReservedProps`

vue是没有导出，但是看taro定义的slimProps，既然自定义了class、style等属性，怎么不在里面自定义key属性呢

**Comment by agileago** [comment]
除了key还有ref, ref_for等属性

**Comment by chenchenpp** [comment]
> 除了key还有ref, ref_for等属性

我认为因为h5和小程序的dom结构本身就不一致，所以ref的类型不能共用。至于ref_for和ref_key完全没用过，这应该是内部使用的，可以不用关注。

**Comment by agileago** [comment]
不是的，slim主要是给组件用的，而你是使用的原生标签，原生标签是另外一回事， 你可以看一下 tsx 怎么定义类型的

**Comment by agileago** [comment]
@chenchenpp  https://github.com/NervJS/taro/pull/12876   试试把这个放到你的项目里面看看还报错么

**Comment by chenchenpp** [comment]
> 不是的，slim主要是给组件用的，而你是使用的原生标签，原生标签是另外一回事， 你可以看一下 tsx 怎么定义类型的

我明白你的意思了，类型文件没看仔细。

**Comment by chenchenpp** [comment]
> @chenchenpp #12876 试试把这个放到你的项目里面看看还报错么

这个是可以的，就是把vue的ReservedProps拿过来做了一个交叉处理

**Comment by agileago** [comment]
更新下版本，已经发布了
