### ISSUE TITLE
taro升级到3.5.7后报错

### ISSUE THREAD

**Issue by hrhrhr2** [NervJS/taro#12750]
### 相关平台
H5

**浏览器版本: 106.0.5249.119**
**使用框架: React**

### 复现步骤
taro从3.3.7升级到3.5.7 使用webpack变异后，启动成功，但是页面无法加载

runtime.js:865 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at options.factory (runtime.js:865:31)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:522:21)
    at eval (app.boot.js:3:70)
    at ./src/app.boot.js (app.js:50:1)
    at options.factory (runtime.js:865:31)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:522:21)
    at eval (app.config.js?4023:1:1)

### 期望结果
成功加载

### 实际结果
无法加载

### 环境信息
```
taro info
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/extend: ^3.3.3 => 3.5.7 
      @tarojs/plugin-framework-react: ^3.5.7 => 3.5.7 
      @tarojs/plugin-html: ^3.5.7 => 3.5.7 
      @tarojs/react: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: ^3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
      react: ^18.2.0 => 18.2.0 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
```

**Comment by Chen-jj** [comment]
@hrhrhr2 麻烦提供一下可复现的 demo

**Comment by songwenhui** [comment]
> ### 相关平台
> H5
> 
> **浏览器版本: 106.0.5249.119** **使用框架: React**
> 
> ### 复现步骤
> taro从3.3.7升级到3.5.7 使用webpack变异后，启动成功，但是页面无法加载
> 
> runtime.js:865 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call') at options.factory (runtime.js:865:31) at **webpack_require** (runtime.js:36:33) at fn (runtime.js:522:21) at eval (app.boot.js:3:70) at ./src/app.boot.js (app.js:50:1) at options.factory (runtime.js:865:31) at **webpack_require** (runtime.js:36:33) at fn (runtime.js:522:21) at eval (app.config.js?4023:1:1)
> 
> ### 期望结果
> 成功加载
> 
> ### 实际结果
> 无法加载
> 
> ### 环境信息
> ```
> taro info
> 👽 Taro v3.5.7
> 
> 
>   Taro CLI 3.5.7 environment info:
>     System:
>       OS: macOS 13.0
>       Shell: 5.8.1 - /bin/zsh
>     Binaries:
>       Node: 16.13.0 - /usr/local/bin/node
>       Yarn: 1.22.19 - /usr/local/bin/yarn
>       npm: 8.19.2 - /usr/local/bin/npm
>     npmPackages:
>       @tarojs/components: 3.5.7 => 3.5.7 
>       @tarojs/extend: ^3.3.3 => 3.5.7 
>       @tarojs/plugin-framework-react: ^3.5.7 => 3.5.7 
>       @tarojs/plugin-html: ^3.5.7 => 3.5.7 
>       @tarojs/react: 3.5.7 => 3.5.7 
>       @tarojs/runtime: 3.5.7 => 3.5.7 
>       @tarojs/taro: 3.5.7 => 3.5.7 
>       @tarojs/webpack5-runner: ^3.5.7 => 3.5.7 
>       babel-preset-taro: 3.5.7 => 3.5.7 
>       eslint-config-taro: 3.5.7 => 3.5.7 
>       react: ^18.2.0 => 18.2.0 
>       taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
> ```

请问 这个问题有解决吗？
