### ISSUE TITLE
taro项目用cnpm安装依赖提示taro/shared 3.4.9版本报错

### ISSUE THREAD

**Issue by txl1123** [NervJS/taro#12752]
### 相关平台
微信小程序

**小程序基础库: 2.27.0**
**使用框架: Vue 3**

### 复现步骤
taro安装完脚手架后，cnpm安装，版本都是3.4.9，运行会报错
由于家里网络不好，无法使用npm和yarn，开启vpn也不行，执行cnpm可以下载依赖，但是安装好后执行`npm run dev:weapp`会提示警告，运行后会在小程序报错
<img width="538" alt="image" src="https://user-images.githubusercontent.com/9738404/199233406-d3e2ba1b-3e3a-45d2-959f-5534aedaebe2.png">

最后开了手机热点npm执行成功后，可以运行，应该cnpm的资源有问题，希望能排查一下，在家弄了好久，还以为出啥问题了

### 期望结果
cnpm也能正常安装使用

### 实际结果
cnpm安装依赖taro环境无法运行

### 环境信息
```
Taro CLI 3.4.9 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.9 => 3.4.9 
      @tarojs/mini-runner: 3.4.9 => 3.4.9 
      @tarojs/plugin-html: ^3.4.11 => 3.4.11 
      @tarojs/runtime: 3.4.9 => 3.4.9 
      @tarojs/taro: 3.4.9 => 3.4.9 
      @tarojs/webpack-runner: 3.4.9 => 3.4.9 
      babel-preset-taro: 3.4.9 => 3.4.9 
      eslint-config-taro: 3.4.9 => 3.4.9 
```

**Comment by ZakaryCode** [comment]
该类问题与对应仓库源的同步策略有关系，可以自行通过 sync 指令修复，以 cnpm 为例参考如下。

```sh
cnpm sync @tarojs/shared
```
