### ISSUE TITLE
使用switchTab跳转至tab页回退后再次跳转页面白屏

### ISSUE THREAD

**Issue by liuliuna** [NervJS/taro#12751]
### 相关平台
H5

### 复现仓库
[https://github.com/liuliuna/taro-bug.git](https://github.com/liuliuna/taro-bug.git)
**浏览器版本: 105.0.5195.125（正式版本）**
**使用框架: React**

### 复现步骤
打开两个tab页后跳转非tab页1再跳转非tab页2，使用switchTab跳转tab页，点击浏览器回退按钮回退至非tab页1，再跳转非tab页2白屏

### 期望结果
正常打开页面

### 实际结果
页面白屏被display：hidden

### 环境信息
```
  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
在h5使用switchTab跳转后，对非tab页页面dom的处理是隐藏而不是销毁，理论上使用switchTab应该销毁其他非tab页面

**Comment by liuliuna** [comment]
@ZakaryCode  我看之前也有人提了几次一直没处理呀这个

**Comment by ZakaryCode** [comment]
> @ZakaryCode 我看之前也有人提了几次一直没处理呀这个

相似但并非是同一个问题，之前的 issue 和这里复现逻辑相似，但其实还是有比较大的区别。比如 #12455 实际是希望 switchTab 可以支持类似 history.go 的方法回溯页面路由，遗憾由于浏览器限制并不能实现，至于其中提到的非 tab 页面返回白屏是一个 3.x 早期版本问题，根据提供示例和描述文字并不能复现问题。

> 打开两个tab页后跳转非tab页1再跳转非tab页2，使用switchTab跳转tab页，点击浏览器回退按钮回退至非tab页1，再跳转非tab页2白屏
> ---
> ### 补充信息
> 在h5使用switchTab跳转后，对非tab页页面dom的处理是隐藏而不是销毁，理论上使用switchTab应该销毁其他非tab页面

这里所述的问题实际是在 tab 页面回退时，由于 pop 事件误伤了 tab 页面节点导致路由栈出现问题。

**Comment by liuliuna** [comment]
> 

跳转白屏在示例中是能复现的，不是返回白屏，是返回后再点击跳转至非tab页2出现的。不过导致白屏的原因确实是路由栈出现问题使dom id重复导致的，修复了应该就可以啦☺
