### ISSUE TITLE
taro-router源码里面的spa.ts第61行router.resolve返回的不一定是个数组，后面能否加个判断，传进Promise.all参数

### ISSUE THREAD

**Issue by cuicuiworld** [NervJS/taro#12754]
### 这个特性解决了什么问题？
const result = await router.resolve(handler.router.forcePath || handler.pathname)
/** router.resolve 返回的不一定是个数组，可能是个函数组件，那么能否加个判断，不然会报错 */
;[element, , params] = await Promise.all(result)

### 这个 API 长什么样？
const result = await router.resolve(handler.router.forcePath || handler.pathname)
;[element, , params] = await Promise.all(Array.isArray(result) ? result : [result])

**Comment by ZakaryCode** [comment]
有具体情况下，可以详细讲讲并附个示例

**Comment by cuicuiworld** [comment]
示例不方便展示，内部项目，但的确存在问题。原先3.4.9版本的这一处的代码并没有去用Promise.all，也没有抽离出spa.js。
![image](https://user-images.githubusercontent.com/21233144/200224752-3cefa541-cb15-4161-9e74-739552bd5183.png)

3.4.9并没有出现问题。
3.5.7出现了以下报错，复现步骤是如下：

我在本地项目使用是借用taro3.5.7版本的createReactApp和createRouter构建了一套。

1. 引入@tarojs/router的createRouter
2. 引入@tarojs/plugin-framework-react/dist/runtime的createReactApp
3. 此处我定义的MiniappPage页面是个中间件，可以加载任何页面。<img width="548" alt="image" src="https://user-images.githubusercontent.com/21233144/200235766-db995477-51b7-4bb5-bb8d-9708f35e76f1.png">
4. 然后就报错了。![image](https://user-images.githubusercontent.com/21233144/200236070-7a86d183-aaa7-422f-a6a9-c8a0876c9464.png)
![image](https://user-images.githubusercontent.com/21233144/200235922-d930963c-875a-4e7b-a5e9-b2d682d4bcd9.png)

**Comment by ZakaryCode** [comment]
听上去应该是依赖版本没有对齐导致的 🤔

**Comment by cuicuiworld** [comment]
实际上我的版本号是一致的，全局taro也是一致都为3.5.7。

**Comment by ZakaryCode** [comment]
> 实际上我的版本号是一致的，全局taro也是一致都为3.5.7。

然而并不能在任何示例中复现，可以检查下 lock 相关文件，是否被其它依赖污染了版本依赖
