### ISSUE TITLE
taro创建项目时选择taro-hooks@canary模板，在微信小程序平台报错

### ISSUE THREAD

**Issue by PathfinderH** [NervJS/taro#12760]
### 相关平台
微信小程序

**小程序基础库: 2.27.0**
**使用框架: React**

### 复现步骤
创建项目后选择taro-hooks@canary模板 运行 打开微信小程序开发者工具直接白屏报错

### 期望结果
在小程序端正常运行

### 实际结果
微信小程序开发者工具打开项目直接白屏报错

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD 
```

**Comment by innocces** [comment]
_(:з」∠)_  关闭preload即可

**Comment by innocces** [comment]
这个问题可以在 taro 这边关闭了. 在  [taro-hooks](https://github.com/innocces/taro-hooks/issues/37) 里关注即可. 

需要配合3.5更改一下插件来兼容prebundle. 

就正上面回答的问题:
1. 小程序需打开 prebundle
2. h5需关闭prebundle
