### ISSUE TITLE
Taro 3.5.7 无法获取到process变量

### ISSUE THREAD

**Issue by Xy2002** [NervJS/taro#12764]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Xy2002/taro-webapack5-demo.git](https://github.com/Xy2002/taro-webapack5-demo.git)
**小程序基础库: 2.27.0**
**使用框架: Vue 3**

### 复现步骤
在页面内访问`process`变量就会报错 `ReferenceError: process is not defined`

### 期望结果
正确获取到process变量

### 实际结果
ReferenceError: process is not defined

### 环境信息
```
Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/mini-runner: ^3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
    npmGlobalPackages:
      typescript: 4.5.4
```

**Comment by Xy2002** [comment]
手动导入 `import process from 'process'` 就又可以访问到`process`变量了，但是不知道为什么需要手动导入才行

**Comment by Chen-jj** [comment]
@Xy2002 印象中 webpack5 对 node API 的处理有改动，可以先查一查 webpack 文档

**Comment by yoyo837** [comment]
webpack 5 ,node中有`process`, 前端没有了.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/6134547/199871058-8da6b3be-9ad1-4493-ab12-307d875d80e2.png">

**Comment by marlti7** [comment]
文档里有写

defineConstants
object

Used to configure some global variables for use in the code.

The configuration method can be referred to [Webpack DefinePlugin](https://webpack.js.org/plugins/define-plugin/)，for eaxmple:

/config/index.js
module.exports = {
  // ...
  defineConstants: {
    A: '"a"' // JSON.stringify('a')
  }
}

**Comment by SilentFlute** [comment]
[taro 3.6.11 webpack5 env环境变量设置](https://github.com/NervJS/taro/discussions/14330)

**Comment by SilentFlute** [comment]
#14330

**Comment by forwzb** [comment]
试试设置变量时，把值改为  XXXX:'"xxxxx"',我不晓得哪里出错，反正这样写还行。
