### ISSUE TITLE
小程序端在 page 标签定义的全局样式编译到 H5 丢失

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#1277]
**问题描述**
小程序端在 page 标签定义的全局样式编译到 H5 丢失

1. 原始代码
```
page {
  background: hsl(240, 17%, 98%);
  color: #4a4a4a;
  font-size: 13px;
}
```
2. 小程序端正常

![image](https://user-images.githubusercontent.com/7480381/49134019-13683e00-f31d-11e8-8b1e-d5fa756ff5d9.png)

3. H5 端样式丢失

**期望行为**

将 page 标签的样式编译到 body

**系统信息**

 - 操作系统: [e.g. MacOS 10.13.3]
 - Taro 版本 [v.1.1.8]
 - Node.js 版本 [v8.11.3]
 - 报错平台 [h5]

**Comment by luckyadam** [comment]
H5 没有 page，换别的替代

**Comment by youngluo** [comment]
@luckyadam 我认为在 H5 端可以将 page 编译为 body 标签

**Comment by luckyadam** [comment]
不好直接对应，样式里你写 body 就行了
