### ISSUE TITLE
希望编译时不要删除project.private.config.json文件

### ISSUE THREAD

**Issue by we125182** [NervJS/taro#12788]
### 这个特性解决了什么问题？
在开发微信，支付宝小程序时，总是会自定义一些编译模式（指定页面路径，参数等）, 这些配置被保存再project.private.config.json中（支付宝是.mini-ide）。每次taro编译时，所有文件都会被清空，导致需要重新配置这些编译模式，导致开发体验不好。
源码位置：
https://github.com/NervJS/taro/blob/fdf029379a52fe137d8a03af43b95fe84a4106c6/packages/taro-service/src/platform-plugin-base.ts#L76-L94

### 这个 API 长什么样？
看了源码发现，有个needClearOutput的配置，希望能够通过这个配置来实现忽略清空某些文件或文件夹。例如：
```js
const config = {
  ...
  needClearOutput: {
     excludes: ['project.private.config.json', '.mini-ide']
  }
}
```
将源码进行一些调整就行，如下
```diff
 private setupImpl () { 
   const { needClearOutput } = this.config 
   if (typeof needClearOutput === 'undefined' || !!needClearOutput) { 
-     this.emptyOutputDir()
+     this.emptyOutputDir(needClearOutput)
   } 
   this.printDevelopmentTip(this.platform) 
   if (this.projectConfigJson) { 
     this.generateProjectConfig(this.projectConfigJson) 
   } 
   if (this.ctx.initialConfig.logger?.quiet === false) { 
     const { printLog, processTypeEnum } = this.ctx.helper 
     printLog(processTypeEnum.START, '开发者工具-项目目录', `${this.ctx.paths.outputPath}`) 
   } 
 } 
  
- protected emptyOutputDir () { 
+ protected emptyOutputDir (needClearOutput) { 
   const { outputPath } = this.ctx.paths 
-  this.helper.emptyDirectory(outputPath) 
+  this.helper.emptyDirectory(outputPath, needClearOutput) 
 } 
```

**Comment by yoyo837** [comment]
个人没有遇到你说的问题，你指的是重新编译吗？

**Comment by tourze** [comment]
看着是重新编译的问题。
如果能完善这点，的确能改善开发体验~

**Comment by we125182** [comment]
> 个人没有遇到你说的问题，你指的是重新编译吗？

是说的重新编译。抱歉没说清楚

**Comment by bigmeow** [comment]
@yoyo837 小程序打开项目时 如果打开的是`dist`输出目录， 会有这个问题； 如果打开的是`src` 目录，则可以规避这个问题。
不过我在 `@tarojs/plugin-mini-ci` 插件里， 默认打开的是 `dist` 目录。

**Comment by bigmeow** [comment]
@we125182 建议把配置放 `src` 目录下， 然后写脚本复制到 `dist`目录。
这样有一点不好，就是每次在小程序开发者工具里直接改配置时，实际上改动的是 `dist` 目录下的配置文件

**Comment by we125182** [comment]
> @we125182 建议暂时把配置放 `src` 目录下， 然后写脚本复制到 `dist`目录。 这样有一点不好，就是每次在小程序开发者工具里直接改配置时，实际上改动的是 `dist` 目录下的配置文件

确实，把项目整个导入到开发者工具中，project.private.config.json不会被清空。但是还是习惯把dist导入。目前是通过插件解决了这个问题的。
