### ISSUE TITLE
taro-native-shell构建Android包是报错 Task :@react-native-community_netinfo:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by xiaoguo525** [NervJS/taro#12795]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
用taro-native-shell构建Android包时，报错：@react-native-community_netinfo:compileReleaseJavaWithJavac，没有改过版本，之前可以构建，
![image](https://user-images.githubusercontent.com/39393904/200572572-0d0295bf-9069-47a6-b838-6b3ea19d45e9.png)
![image](https://user-images.githubusercontent.com/39393904/200572609-aa142b45-d5d9-4b2b-b990-6ca2b152e6bc.png)
![image](https://user-images.githubusercontent.com/39393904/200572814-499b7e6d-6f85-43fe-ba60-9d43efba4ee9.png)

### 期望结果
构建成功

### 实际结果
无法启动和构建

### 环境信息
```
 Taro CLI 2.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
https://github.com/facebook/react-native/issues/35210
