### ISSUE TITLE
多环境自动配置支持

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro#1279]
**问题描述**
应用对应的服务端环境有多个，现在需要在代码中切换，希望cli可以设置环境变量就像
process.env.NODE_ENV 一样，这样就可以通过脚本注入环境自动打包

**期望行为**
taro build 命令支持直接设置process.env, 或者提供其它的方式能解决问题

**系统信息**

 - 操作系统: [macOS]
 - Taro 版本 [1.1.8]
 - Node.js 版本 [ v8.11.1]
 - 报错平台 [h5, weapp]

**Comment by luckyadam** [comment]
Duplicate of #1268

**Comment by luckyadam** [comment]
请到 #1268 里看下
