### ISSUE TITLE
希望支持富文本

### ISSUE THREAD

**Issue by cgx9** [NervJS/taro#128]
后台一般都有富文本编辑器。比如我是用slate。
slate他可以选择保存为带他的数据格式的json，然后前台去解析成html，也可以解析好存入db。

所以现在想要，或者是解析slate的格式，可以区分h5和小程序的格式，显示富文本。或者直接解析html标签成富文本。

小程序上有一个库：wxparse，可以解析html标签为小程序显示的格式。

**Comment by zacksleo** [comment]
其中的一个解决方案，小程序支持 rich-text 组件，需要在服务端将html解析成所需要的json

**Comment by cgx9** [comment]
@zacksleo 我看rich-text代码应该直接支持html标签。只是听说有问题。

**Comment by zacksleo** [comment]
看了下文档，好像是支持 html String了，建议还是用这个吧，wxparse 这类解析器貌似性能不好

**Comment by bernkastle** [comment]
@zacksleo 请问支持html string文档的链接是多少，在小程序文档上没有并没有搜索到，谢谢！

**Comment by zacksleo** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/rich-text.html

<img width="845" alt="wx20180617-100644 2x" src="https://user-images.githubusercontent.com/3369169/41504061-58fe6c92-7216-11e8-8534-c16594e30ee8.png">

**Comment by bernkastle** [comment]
@zacksleo 哦哦，刚只注意到array了，谢谢！！

**Comment by luckyadam** [comment]
最新版本的 beta 已经支持使用 wxParse 了，这是个例子
https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js

**Comment by zhou1992zg** [comment]
小程序富文本可用，但是什么时候支持H5富文本啊

**Comment by luckyadam** [comment]
@zhou1992zg 了解，能不能再开个 issue ，[Feature Request] H5 端富文本支持
