### ISSUE TITLE
多个页面引用同一文件数据后白屏

### ISSUE THREAD

**Issue by queee03** [NervJS/taro#12806]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/queee03/issue-taro-import.git](https://github.com/queee03/issue-taro-import.git)
**小程序基础库: 2.27.1**
**使用框架: React**

### 复现步骤
在不同页面下引用同个文件 `configs/constant` 中的数据就会白屏，控制台无报错；只要随便注释其中一个页面的引用就恢复正常。
以下是不同页面文件中的相同代码：

```tsx
import { APP_TITLE } from "@/configs/constant";

const Index = () => {
  return (
    <View>
      <Text>{APP_TITLE}</Text>
    </View>
  );
};

export default Index;
```

### 期望结果
能实现多页面引用同一文件数据

### 实际结果
引用同一文件数据就会白屏

### 环境信息
```
� Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\nvm\nodejs\node.EXE
      Yarn: 3.2.4 - C:\nvm\nodejs\yarn.CMD
      npm: 8.11.0 - C:\nvm\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/201449228-6740b2c0-cae7-4df7-9989-2268f8173d39.png)
不清楚为啥没复现？

**Comment by paytham** [comment]
您好，我也遇到了，请问问题解决了吗？

**Comment by queee03** [comment]
> 您好，我也遇到了，请问问题解决了吗？

我重新安装了依赖，再在控制台手动跑了dev:weapp就正常了，目前基础库是2.27.2，你也可以试试

**Comment by queee03** [comment]
> 

我重新安装了依赖就没出现这个问题了

**Comment by paytham** [comment]
> > 
> 
> 我重新安装了依赖就没出现这个问题了

嗯，我的问题也找到了，不是基础库的问题，是function component 在某种数据状态下render返回了 null，例如： (if falsy) return null; return <jsx>，这种写法好像会导致一些小程序页面发生中断，依赖解析就出现问题了，另外了解到Taro的React语法应该是一种兼容不能完全对等。

**Comment by paytham** [comment]
> > > 
> > 
> > 
> > 我重新安装了依赖就没出现这个问题了
> 
> 嗯，我的问题也找到了，不是基础库的问题，是function component 在某种数据状态下render返回了 null，例如： (if falsy) return null; return ，这种写法好像会导致一些小程序页面发生中断，依赖解析就出现问题了，另外了解到Taro的React语法应该是一种兼容不能完全对等。

我的基础库也是2.27.2

**Comment by paytham** [comment]
> > > > 
> > > 
> > > 
> > > 我重新安装了依赖就没出现这个问题了
> > 
> > 
> > 嗯，我的问题也找到了，不是基础库的问题，是function component 在某种数据状态下render返回了 null，例如： (if falsy) return null; return ，这种写法好像会导致一些小程序页面发生中断，依赖解析就出现问题了，另外了解到Taro的React语法应该是一种兼容不能完全对等。
> 
> 我的基础库也是2.27.2

所以基本结论是公共模块引入是没问题的，需要注意的是Component的写法，尤其是和render有关的边界值（数据状态state）。

**Comment by alswl** [comment]
解决步骤：

- 删除 `node_moduels`
- 重新 `yarn`
- 重新 `yarn dev:weapp`

不再出现，怀疑是某种缓存起作用的。
