### ISSUE TITLE
Taro.request的content-type，微信默认为json，h5默认为text

### ISSUE THREAD

**Issue by wangmingquan** [NervJS/taro#1280]
**问题描述**
Taro.request的content-type，微信默认为application/json，h5默认为text/plain

**复现步骤**
同一个POST请求：
微信的表现：
```
Request Payload 
{
  aa: "xxx"
}
```
H5的表现：
```
Request Payload 
[object Object]
```

**期望行为**

H5和微信默认保持一致

**报错信息**

无

**Comment by zmbeex** [comment]
没有解决方法，只能放弃这个框架了，可惜啊

**Comment by zmbeex** [comment]
跨域问题 mode: "no-cors"会出现这个问题

**Comment by yuanbolin** [comment]
同样遇到，请问解决了吗
