### ISSUE TITLE
支付宝小程序video标签src无法兼容支持优酷视频编码

### ISSUE THREAD

**Issue by zyqlovekl** [NervJS/taro#12805]
### 这个特性解决了什么问题？
src为优酷视频码时候可以正常播放

### 这个 API 长什么样？
支持优酷视频码

**Comment by TheKonka** [comment]
可以升级到最新版本（或 `3.5.7`及以上版本）再试下，应该是之前的版本`video`组件多了 `enableNative` 属性导致

https://github.com/NervJS/taro/blob/5f0de257427b7f6f4d2843abc1a2e35b85f53ab4/packages/taro-alipay/src/components.ts#L89
