### ISSUE TITLE
Taro是否支持微前端

### ISSUE THREAD

**Issue by huangyiman** [NervJS/taro#12810]
### 这个特性解决了什么问题？
是否可以接入MicroApp或者乾坤的模式，打算Taro做基座，可以首页接入其他的不同应用

### 这个 API 长什么样？
是否可以接入MicroApp或者乾坤的模式，打算Taro做基座，可以首页接入其他的不同应用

**Comment by ZakaryCode** [comment]
Duplicate of #11654
