### ISSUE TITLE
升级Taro版本后,本地编译报错Call stack

### ISSUE THREAD

**Issue by Fiestar** [NervJS/taro#12825]
### 相关平台
H5

**浏览器版本: Chrome 107.0.5304.63**
**使用框架: React**

### 复现步骤
从3.0.28版本升级到3.2.6版本后,通过npm run dev:h5编译, 页面上直接报错
Error
[object Object]

Call Stack
 rejectionHandler
  node_modules/@pmmmwh/react-refresh-webpack-plugin/client/utils/errorEventHandlers.js:52:21
但是不会影响功能.
![78f1461122536f9c0d994f7cd736af1](https://user-images.githubusercontent.com/37931780/201601080-360b2e23-c17e-4bc6-b7f9-c2553b4ce23d.png)

### 期望结果
成功编译

### 实际结果
页面报错

### 环境信息
```
👽 Taro v3.2.8


  Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD

```

**Comment by yoyo837** [comment]
上个复现demo吧

**Comment by dawenxi897094320** [comment]
楼主找到解决方案了吗，在线等急急急急

**Comment by yuuk** [comment]
同遇到

**Comment by Fiestar** [comment]
> 同遇到

https://taro-docs.jd.com/docs/preact#fast-refresh   关掉这个;

**Comment by yuuk** [comment]
> > 同遇到
> 
> https://taro-docs.jd.com/docs/preact#fast-refresh 关掉这个;

那不是失去了热更新的能力么？

**Comment by iDestin** [comment]
2025年同样遇到这个问题，可以reopen一下这个issue吗？

**Comment by yoyo837** [comment]
来个复现开个新issue吧
