### ISSUE TITLE
npm run build:h5 无法注入参数

### ISSUE THREAD

**Issue by hrhrhr2** [NervJS/taro#12833]
### 这个特性解决了什么问题？
希望可以在编译时注入参数，如host='' static=''等。然后在项目中可以通过process.argv访问到注入的参数

### 这个 API 长什么样？
npm run build:h5 host='123'
process.argv中可以拿到参数

**Comment by ZakaryCode** [comment]
编译环境内可以直接使用的，运行时需要额外注入，欢迎 PR

**Comment by hrhrhr2** [comment]
> 编译环境内可以直接使用的，运行时需要额外注入，欢迎 PR

啥意思，我没理解

**Comment by ZakaryCode** [comment]
> 啥意思，我没理解

编译环境内，比如 `config/index.js` 中的各项配置或者插件对应的生命周期中都是可以直接使用 `process.argv` 获取参数；但是页面、组件等生产环境不支持，需要自己在配置中透传，用过 [env](https://nervjs.github.io/taro-docs/docs/config-detail#env) 或者 [defineConstants](https://nervjs.github.io/taro-docs/docs/config-detail#defineconstants) 配置都可以使用。
