### ISSUE TITLE
Taro3.5.7 运行H5应用，页面下拉刷新，元素位置错乱(多个版本都有此问题)

### ISSUE THREAD

**Issue by shbin** [NervJS/taro#12838]
### 相关平台
H5

### 复现仓库
[https://gitee.com/bin-gitee/taro-h5-demo.git](https://gitee.com/bin-gitee/taro-h5-demo.git)
**浏览器版本: Chrome106,firefox106**
**使用框架: React**

### 复现步骤
1、taro init 创建的空白项目中，开启enablePullDownRefresh为true
2、运行H5应用，npm run dev:h5
3、下拉刷新，插入数组。列表渲染后，再下拉一次，下面的Button就跑到上面去了。（要下拉两次）
4、只要更新数据都有这个问题。

### 期望结果
元素位置不变

### 实际结果
在当前页面的下面的Button就跑到上面去了

### 环境信息
```
  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.20.0 - C:\Users\Windows 10\AppData\Local\nvs\default\node.EXE
      Yarn: 1.22.19 - C:\Users\Windows 10\AppData\Local\nvs\default\yarn.CMD
      npm: 6.14.17 - C:\Users\Windows 10\AppData\Local\nvs\default\npm.CMD  
```

**Comment by Barrierml** [comment]
查了一下这个这个问题，是因为`stencil`与`React`之间的 `render` 冲突导致的。
`Taro` 的下拉刷新组件为了能兼容各个框架，使用`WebComponent`框架`stencil`为基座封装的，
直接原因是`stencil`的`diff`元素的问题，`stencil` 和 `React` 一样也是利用虚拟dom进行渲染的，但是其虚拟dom并没有保存在JS内存中，而是和真实节点混合保存在一起，而 `React` 是直接修改dom节点。
所以就会出现，`React` 删除了`stencil` 组件内部的某个元素后，`stencil` 组件重新渲染，在进行`diff`时就会造成错误的排列操作。
https://github.com/ionic-team/stencil/blob/13621c258e086dfbc949ccc0d64d3c0fee85144b/src/runtime/vdom/vdom-render.ts#L703

**Comment by shbin** [comment]
@Barrierml 在页面最外层view改成div可以解决。但页面里面使用自定义组件，组件数据是动态的，再下拉也有这个问题，是所有地方(包括组件)都要把首元素由View修改为基本元素div吗？
上面的git仓库，我已经提交了复现代码

**Comment by Barrierml** [comment]
> @Barrierml 在页面最外层view改成div可以解决。但页面里面使用自定义组件，组件数据是动态的，再下拉也有这个问题，是所有地方(包括组件)都要把首元素由View修改为基本元素div吗？ 上面的git仓库，我已经提交了复现代码

很抱歉呀，我之前提供的临时解决方案确实是有问题的，只解决了第一层的重新渲染问题，忽略了基本元素也是会继续向下传播重新渲染的

那就通过mock数据的方式让首元素主动跳出`stencil` 的传播就可以彻底解决问题啦

> PR的解决方式也是一样的，细节方面可以看PR的介绍 https://github.com/NervJS/taro/pull/12854

```jsx
import { useEffect, useRef } from 'react';
import List from './../../components/List';

const Test = () => {

  const divRef = useRef<any>();

  useEffect(() => {
    Object.defineProperty(divRef.current, 'nodeType', {
      value: 0,
    })
  }, []);

  return (
    <div ref={divRef}>
      <List></List>
    </div>
  );
};

export default Test;
```

**Comment by shbin** [comment]
> 

解决了，感谢！！

**Comment by ZakaryCode** [comment]
该问题为 stencil 组件结合导致，在 3.6 版本中修复，并在 3.5 最新版本同步该特性。
