### ISSUE TITLE
怎么在hash前面添加一个?

### ISSUE THREAD

**Issue by toshuqiong** [NervJS/taro#1284]
**问题描述**
Taro-router使用的hash模式
微信支付检测页面路径使用的是最后刷新的URL，
xxx.com/#/index/index作为首页，所以需要将xxx.com/#/index/index添加到微信支付目录，
如果还有一个页面xxx.com/#/order/index，由于可能会在这个页面手动刷新，所以仍然需要将该页面添加到支付目录，如此则可能需要将所有的页面添加到支付目录，这显然是不现实的。
但微信会忽略掉？后面的内容，所以能不能在hash前添加？，此时url变为xxx.com/?#/index/index，那么只需要将支付目录设置为xxx.com即可。

**系统信息**

 - 操作系统: macOS 
 - Taro 版本 👽 Taro v1.1.8
 - Node.js 版本 v11.1.0
 - 报错平台 [h5]

**Comment by Littly** [comment]
这种模式并不标准.. 暂时不考虑
