### ISSUE TITLE
RN模板更新依赖报错

### ISSUE THREAD

**Issue by cc-Listener** [NervJS/taro#12851]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
装完依赖后运行 yarn upgradePeerdeps
出现报错
yarn run v1.22.17
warning ../../../package.json: No license field
$ install-peerdeps @tarojs/taro-rn@3.5.7 -o -Y && install-peerdeps @tarojs/components-rn@3.5.7 -o -Y && install-peerdeps @tarojs/router-rn@3.5.7 -o -Y && pod-install
install-peerdeps v3.0.3
ERR Unexpected token { in JSON at position 95
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 期望结果
能够正常更新依赖

### 实际结果
更新依赖报错

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7
      @tarojs/components: 3.5.7 => 3.5.7
      @tarojs/helper: 3.5.7 => 3.5.7
      @tarojs/plugin-framework-react: 3.5.7 => 3.5.7
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7
      @tarojs/react: 3.5.7 => 3.5.7
      @tarojs/rn-runner: 3.5.7 => 3.5.7
      @tarojs/router: 3.5.7 => 3.5.7
      @tarojs/runtime: 3.5.7 => 3.5.7
      @tarojs/shared: 3.5.7 => 3.5.7
      @tarojs/taro: 3.5.7 => 3.5.7
      @tarojs/taro-h5: 3.5.7 => 3.5.7
      @tarojs/taro-rn: 3.5.7 => 3.5.7
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7
      babel-preset-taro: 3.5.7 => 3.5.7
      eslint-config-taro: 3.5.7 => 3.5.7
      react: ^18.0.0 => 18.2.0
      react-native: ^0.69.3 => 0.69.7
```

**Comment by zhiqingchen** [comment]
看着像网络原因，可直接用我初始化好的

https://github.com/zhiqingchen/taro-test

**Comment by tyvqin** [comment]
> 看着像网络原因，可直接用我初始化好的
> 
> https://github.com/zhiqingchen/taro-test
> 
> https://github.com/zhiqingchen/taro-test/tree/tests/3.5.7

这也不是个很好的解决办法吧，如果我要加一些依赖上去同样也要更新。

**Comment by zhiqingchen** [comment]
另外的办法就是，查看自身网络问题。尝试重新安装。

**Comment by cc-Listener** [comment]
> 另外的办法就是，查看自身网络问题。尝试重新安装。

这2天试了下，网络状态都正常，但是到了这一步都是同样的报错

**Comment by zhiqingchen** [comment]
install-peerdeps @tarojs/taro-rn -o -Y && install-peerdeps @tarojs/components-rn -o -Y && install-peerdeps @tarojs/router-rn -o -Y && pod-install

可以的吗

**Comment by zhiqingchen** [comment]
可以把安装完的仓库，提交到git上看看
