### ISSUE TITLE
taro小程序正常启动，h5报错 Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by zhuxiaoweb** [NervJS/taro#12869]
### 相关平台
H5

**浏览器版本: chrome最新版**
**使用框架: Vue 3**

### 复现步骤
yarn dev:h5

### 期望结果
期望正常运行

### 实际结果
[HMR] Waiting for update signal from WDS...
app.config.ts?cf92:1 Uncaught (in promise) Error: Cannot find module './app.boot'
    at webpackMissingModule (app.config.ts?cf92:1:1)
index.js?e2a7:551 [webpack-dev-server] Hot Module Replacement enabled.
index.js?e2a7:551 [webpack-dev-server] Live Reloading enabled.

### 环境信息
```
Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
```

---
### 补充信息
macos

**Comment by zhuxiaoweb** [comment]
> eslint-
dev使用这些插件，没有用eslint-webpack-plugin：

"@babel/core": "^7.8.0",
    "@types/webpack-env": "^1.13.6",
    "webpack": "5.69.0",
    "@tarojs/webpack5-runner": "3.5.7",
    "@tarojs/cli": "3.5.7",
    "@vue/babel-plugin-jsx": "^1.0.6",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-preset-taro": "3.5.7",
    "babel-plugin-import": "^1.13.3",
    "css-loader": "3.4.2",
    "eslint-plugin-vue": "^8.0.0",
    "eslint-config-taro": "3.5.7",
    "eslint": "^8.12.0",
    "stylelint": "9.3.0",
    "style-loader": "1.3.0",
    "vue-loader": "^17.0.0",
    "@typescript-eslint/parser": "^5.20.0",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "typescript": "^3.7.0"

**Comment by zhuxiaoweb** [comment]
只有h5不行，小程序是可以正常运行的

**Comment by yoyo837** [comment]
是不是`dev:h5`结束后提示这个错误的? 如果是, 你尝试重新触发一次`HMR`看看会不会好? 也就是找个文件直接`Ctrl+S`保存一次.

**Comment by zhuxiaoweb** [comment]
> 是不是`dev:h5`运行起来结束后直接提示这个错误的? 如果是, 你尝试重新触发一次`HMR`看看会不会好? 也就是找个文件直接`Ctrl+S`保存一次.

![image](https://user-images.githubusercontent.com/32625924/203464202-14961a45-cf56-4fdc-b157-4987144efabb.png)

**Comment by yoyo837** [comment]
截图要表达什么意思? 尝试重新触发一次`HMR`试过了吗?

**Comment by zhuxiaoweb** [comment]
我觉得是这个defineAppConfig方法的问题

**Comment by zhuxiaoweb** [comment]
> 截图要表达什么意思? 尝试重新触发一次`HMR`试过了吗?

是的 重新保存触发了一次

**Comment by yoyo837** [comment]
来个demo吧

**Comment by zhuxiaoweb** [comment]
> 来个demo吧

我现在用taro-cli 拉一个模板 vue3 + ts + webpack5 + nutui + scss 的模板，然后yarn install 以后直接yarn dev:h5就报错了，自己没改动代码，但是昨天是可以的，所以我怀疑是不是官方的依赖出问题了

**Comment by zhuxiaoweb** [comment]
貌似不只是我一个发现，github上也有其他用vue3 + ts + webpack5 + nutui + scss 的作者今天发现这个问题了

**Comment by yoyo837** [comment]
用刚拉的项目对比一下旧项目的lock文件看看有什么差异呢?

**Comment by zhuxiaoweb** [comment]
> 用刚拉的项目对比一下旧项目的lock文件看看有什么差异呢?

昨天正常的lock文件删掉了...

**Comment by helloint** [comment]
我也碰到了，正纳闷了，找到组织了

**Comment by helloint** [comment]
[package.txt](https://github.com/NervJS/taro/files/10072810/package.txt)
[今天的有问题的.package-lock.txt](https://github.com/NervJS/taro/files/10072808/package-lock.txt)
[昨天的正常的.package-lock.txt](https://github.com/NervJS/taro/files/10072809/package-lock.txt)

**Comment by zhuxiaoweb** [comment]
> 我也碰到了，正纳闷了，找到组织了

这个不会影响到一些生产环境项目吧...

**Comment by zhuxiaoweb** [comment]
> 昨天还正常的项目，react18+webpack5，今天删掉lock，重新install后，dev:h5可以复现。 [package.txt](https://github.com/NervJS/taro/files/10072810/package.txt) [今天的有问题的.package-lock.txt](https://github.com/NervJS/taro/files/10072808/package-lock.txt) [昨天的正常的.package-lock.txt](https://github.com/NervJS/taro/files/10072809/package-lock.txt)

这两个文件有点大啊，我试试找下

**Comment by zhuxiaoweb** [comment]
> 来个demo吧

demo来了
https://github.com/yanbowe/taro-vue3-pinia

**Comment by yanbowe** [comment]
删除lock文件，重新install就会报错

**Comment by zhuxiaoweb** [comment]
昨天用h5还有一个问题，nutui里的Range组件在点击进度条给滑块定位的时候会报错，小程序是好的

**Comment by yoyo837** [comment]
锁定一下`enhanced-resolve@5.10.0`,先跳过.

**Comment by yoyo837** [comment]
等上游看看先吧. 我提了个issue.

**Comment by zhuxiaoweb** [comment]
> 等上游看看先吧. 我提了个issue.

嗯嗯

**Comment by yoyo837** [comment]
可以`npm i enhanced-resolve@5.10.0 -D`临时解决.

**Comment by zhuxiaoweb** [comment]
> 锁定一下`enhanced-resolve@5.10.0`,先跳过. [webpack/enhanced-resolve#363](https://github.com/webpack/enhanced-resolve/issues/363)

可能Demo项目可以这样临时解决，
但是我用taro-cli 拉的模板 vue3 + ts + webpack5 + nutui + scss 的模板（github）
用这个办法h5还是出现相同的问题.

**Comment by yoyo837** [comment]
一样的处理手法

**Comment by yoyo837** [comment]
新拉=新install会安装到`enhanced-resolve`新的版本, 再锁一下版本就可以了, 等修复了就解除锁定.

**Comment by zhuxiaoweb** [comment]
> 
我这样操作的：
1.  yarn add enhanced-resolve@5.10.0 -D
2. yarn dev:h5
还是报错，是哪里不对吗？
我园项目package.js的devDep里原本没有enhanced-resolve的。

**Comment by yanbowe** [comment]
> 

把node_modules和lock文件删除，再install

**Comment by zhuxiaoweb** [comment]
> 1. enhanced-resolve

我刚才把node_modules和lock文件删除，再install了一次，还是报这个错，
锁版是在package.js里锁吗？
![image](https://user-images.githubusercontent.com/32625924/203482994-0f1f5675-5de0-4d57-85bb-564230674a3e.png)

**Comment by yanbowe** [comment]
> > 1. enhanced-resolve
> 
> 我刚才把node_modules和lock文件删除，再install了一次，还是报这个错， 锁版是在package.js里锁吗？ ![image](https://user-images.githubusercontent.com/32625924/203482994-0f1f5675-5de0-4d57-85bb-564230674a3e.png)

我这边是正常了，你可以试下我的项目

**Comment by helloint** [comment]
嗯，锁版后问题解决
`"enhanced-resolve": "5.10.0"`

**Comment by zhuxiaoweb** [comment]
> https://github.com/yanbowe/taro-vue3-pinia

嗯 我试了你的项目这样做确实解决了，我用taro-cli拉的nutui模板项目却不行 有点难受

**Comment by yoyo837** [comment]
> > https://github.com/yanbowe/taro-vue3-pinia
> 
> 嗯 我试了你的项目这样做确实解决了，我用taro-cli拉的nutui模板项目却不行 有点难受

你的操作可能不对, 没锁成功.

**Comment by hongxuWei** [comment]
https://github.com/webpack/enhanced-resolve/issues/362
新版跟 webpack-virtual-modules 有冲突

**Comment by zhuxiaoweb** [comment]
> > > https://github.com/yanbowe/taro-vue3-pinia
> > 
> > 
> > 嗯 我试了你的项目这样做确实解决了，我用taro-cli拉的nutui模板项目却不行 有点难受
> 
> 你的操作可能不对, 没锁成功.

嗯 我后面再试试看

**Comment by geekact** [comment]
yarn的解决方案 package.json
```json
{
  "resolutions": {
    "webpack/enhanced-resolve": "5.10.0",
    "@tarojs/webpack5-runner/@tarojs/webpack5-prebundle/enhanced-resolve": "5.10.0"
  }
}
```

**Comment by zhuxiaoweb** [comment]
> yarn的解决方案 package.json
> 
> ```json
> {
>   "resolutions": {
>     "webpack/enhanced-resolve": "5.10.0",
>     "@tarojs/webpack5-runner/@tarojs/webpack5-prebundle/enhanced-resolve": "5.10.0"
>   }
> }
> ```

原来yarn有resolutions可以锁版本，学到了，感谢！

**Comment by yoyo837** [comment]
`enhanced-resolve@5.12.0` 已发布.

**Comment by zhuxiaoweb** [comment]
> enhanced-resolve

嗯 我试了下现在不用锁版本也正常了

**Comment by crimson968** [comment]
还是存在相同的问题

> > enhanced-resolve
> 
> 嗯 我试了下现在不用锁版本也正常了

还是存在相同的问题，请问后来是怎么解决的

**Comment by yoyo837** [comment]
删除`node_modules`, 删除lock文件, reinstall.

**Comment by crimson968** [comment]
> 删除`node_modules`, 删除lock文件, reinstall.

还是不行，貌似是项目内使用了pdfh5，打包h5就会
Field 'browser' doesn't contain a valid alias configuration
我试了下去掉pdfh5就没问题
但是我试了试普通react-h5 cli使用pdfh5打包是ok的
是不是打包配置的问题，还需要配其他哪些参数

**Comment by crimson968** [comment]
> 删除`node_modules`, 删除lock文件, reinstall.

OK了，是其他依赖包导致的
