### ISSUE TITLE
babel-plugin-minify-dead-code组件过期，没有开源License。需要替换成babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions

### ISSUE THREAD

**Issue by edwardean** [NervJS/taro#12866]
### 相关平台
字节跳动小程序

**小程序基础库: 2.74.0.8**
**使用框架: React**

### 复现步骤
 babel-plugin-remove-dead-code 的依赖关系：@tarojs/cli -> @tarojs/transformer-wx  ->  babel-plugin-minify-dead-code

➜  MinAssetApp git:(feature/weixin_tong) npm info babel-plugin-remove-dead-code                   

babel-plugin-remove-dead-code@1.3.2 | Proprietary | deps: 1 | versions: 7
This plugin for babel 6 remove dead code
https://github.com/christophehurpeau/babel-plugin-remove-dead-code#readme

DEPRECATED ⚠️  - use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions

keywords: babel-plugin

dist
.tarball: http://bnpm.byted.org/babel-plugin-remove-dead-code/-/babel-plugin-remove-dead-code-1.3.2.tgz
.shasum: e1a2cd9595bb2f767291f35cab4ec9b467ee62c6
.integrity: sha512-cxk2x58gdIN7epRcL5XOGA8n IFpSLtVflCFhPbRNAt9yGTo9HFLGeu5 602UDB71VjiD5FZAtUWcj6RmP 3SA==

dependencies:
babel-core: 6.10.4 

maintainers:
- churpeau <christophe@hurpeau.com>

dist-tags:
latest: 1.3.2  

published over a year ago by churpeau <christophe@hurpeau.com>

### 期望结果
期望结果是不再依赖没有License的开源组件babel-plugin-minify-dead-code

### 实际结果
实际目前@tarojs/cli依赖了babel-plugin-minify-dead-code

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.0-canary.9 => 3.2.0-canary.9 
      @tarojs/components: 3.2.0-canary.9 => 3.2.0-canary.9 
      @tarojs/mini-runner: 3.2.0-canary.9 => 3.2.0-canary.9 
      @tarojs/react: 3.2.0-canary.9 => 3.2.0-canary.9 
      @tarojs/runtime: 3.2.0-canary.9 => 3.2.0-canary.9 
      @tarojs/taro: 3.2.0-canary.9 => 3.2.0-canary.9 
      babel-preset-taro: ^3.5.7 => 3.5.7 
      eslint-config-taro: 3.2.0-canary.9 => 3.2.0-canary.9 
      react: ^17.0.1 => 17.0.2 
      taro-ui: ^2.3.4 => 2.3.4 
```

**Comment by edwardean** [comment]
另外还有两个组件问题跟babel-plugin-minify-dead-code类似，也是组件没有License。分别是：
1、miniprogram-compiler 0.2.1
依赖关系:
@tarojs/mini-runner -> miniprogram-simulate -> miniprogram-compiler

2、miniprogram-exparser 2.15.0
依赖关系:
@tarojs/mini-runner -> miniprogram-simulate -> j-components -> miniprogram-exparser

**Comment by Chen-jj** [comment]
> miniprogram-exparser

这两个包是微信小程序官方包 miniprogram-simulate 的依赖，目前看来他们没有开源的意思，所以没有解决办法的。
