### ISSUE TITLE
catchMove ts 报错

### ISSUE THREAD

**Issue by HeNanBing** [NervJS/taro#12867]
### 相关平台
微信小程序

**小程序基础库: 2.27.1**
**使用框架: React**

### 复现步骤
catchMove ts 报错
<img width="686" alt="Screenshot 2022-11-23 095928" src="https://user-images.githubusercontent.com/13029560/203456129-dbeb3e22-65ca-4b12-996f-88086e2783df.png">

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
 Taro CLI 3.5.7 environment info:      
    System:
      OS: Windows 10
    Binaries:
      Node: 14.20.0 - C:\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\PC\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.17 - C:\nodejs\npm.CMD

```

**Comment by HeNanBing** [comment]
<img width="269" alt="Screenshot 2022-11-23 100155" src="https://user-images.githubusercontent.com/13029560/203456243-ff0451f9-a41d-4bfe-96cf-7a8b4853cc88.png">
package.json

**Comment by ZakaryCode** [comment]
Duplicate of #12686
