### ISSUE TITLE
react hooks 写法，怎么刷新一个页面 ，调用onLoad 会报错卡死

### ISSUE THREAD

**Issue by HeNanBing** [NervJS/taro#12865]
### 相关平台
微信小程序

**小程序基础库: 2.27.1**
**使用框架: React**

### 复现步骤
1. 首页index 跳转 B页面，在B页面停留超时，默认无感知刷新token，刷新token后要刷新页面
2. const pages = Taro.getCurrentPages()
pages[pages.length -1].onLoad({})  调用此方法刷新B页面
3. B页面卡死，开发工具一直报错
<img width="526" alt="1669097755603" src="https://user-images.githubusercontent.com/13029560/203239425-e10a46ab-13d8-480b-9346-2886c3968680.png">

### 期望结果
正确的方法 刷新页面

### 实际结果
报错

### 环境信息
```
 Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.20.0 - C:\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\PC\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.17 - C:\nodejs\npm.CMD

```

**Comment by HeNanBing** [comment]
都是走接口，接口返回状态码表示token过期，就走重新获取token的接口，token存在store里。
意思是把token相关的封一个use，页面用这个use？

**Comment by Przeblysk** [comment]
页面的hook 去依赖 token就好了，这样token更新了不就重新获取页面数据了

**Comment by dingff** [comment]
用redux呗

**Comment by HeNanBing** [comment]
用的是redux，如果作为依赖加入，那就得内个页面都得加，而且依赖放到useEffect中，如果请求放在 的 onReady或者onLoad里面，不会重新走吧

**Comment by TheKonka** [comment]
我试了 `Taro.getCurrentInstance().page.onLoad()` 没有问题，可以调用

**Comment by HeNanBing** [comment]
包装了一层，把token作为依赖，暂时解决了，谢谢大家的建议
