### ISSUE TITLE
创建一个最新版本的3.5.7新项目支付宝小程序启用小程序基础库2.0构建报错

### ISSUE THREAD

**Issue by zyqlovekl** [NervJS/taro#12879]
### 相关平台
支付宝小程序

**小程序基础库: 2.7.21**
**使用框架: React**

### 复现步骤
1、 taro init myApp
2、cd myApp
3、 taro build --type alipay --watch
4、打开支付宝小程序项目详情启用小程序基础库2.0构建
5、开始报错The keyword 'const' is reserved (440:0)

### 期望结果
正常运行

### 实际结果
VM42 index.html:3 d:\test\test2\dist\prebundle\vendors-node_modules_taro_alipay_prebundle_tarojs_taro_js.js: The keyword 'const' is reserved (440:0)
d:\test\test2\dist\prebundle\node_modules_taro_alipay_prebundle_react_js.js: The keyword 'const' is reserved (133:0)
d:\test\test2\dist\prebundle\vendors-node_modules_taro_alipay_prebundle_react_jsx-runtime_js.js: The keyword 'const' is reserved (1031:0)
Please set enableNodeModuleBabelTransform to true or add "d:/test/test2/dist/prebundle/node_modules_taro_alipay_prebundle_react_js.js, d:/test/test2/dist/prebundle/vendors-node_modules_taro_alipay_prebundle_react_jsx-runtime_js.js, d:/test/test2/dist/prebundle/vendors-node_modules_taro_alipay_prebundle_tarojs_taro_js.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform

### 环境信息
```
$ taro info
� Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
VM42 index.html:3 d:\test\test2\dist\prebundle\vendors-node_modules_taro_alipay_prebundle_tarojs_taro_js.js: The keyword 'const' is reserved (440:0)
d:\test\test2\dist\prebundle\node_modules_taro_alipay_prebundle_react_js.js: The keyword 'const' is reserved (133:0)
d:\test\test2\dist\prebundle\vendors-node_modules_taro_alipay_prebundle_react_jsx-runtime_js.js: The keyword 'const' is reserved (1031:0)
Please set enableNodeModuleBabelTransform to true or add "d:/test/test2/dist/prebundle/node_modules_taro_alipay_prebundle_react_js.js, d:/test/test2/dist/prebundle/vendors-node_modules_taro_alipay_prebundle_react_jsx-runtime_js.js, d:/test/test2/dist/prebundle/vendors-node_modules_taro_alipay_prebundle_tarojs_taro_js.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform

**Comment by Chen-jj** [comment]
@zyqlovekl 3.5.8 试试，没有复现

**Comment by sunan112** [comment]
V3.5.10  支付宝启用component2.0运行报错， 微信小程序正常
使用了Graphql apollo client后在全局使用了provider. 
![image](https://user-images.githubusercontent.com/15712613/208016036-7d014d86-a253-40cf-9a0e-79dbfb215dcf.png)

**Comment by Wujerry** [comment]
勾选 `小程序配置` -> `编译 node_modules模块（ES6转ES5)`
可以解决问题
