### ISSUE TITLE
useShareAppMessage在自定义hook无效

### ISSUE THREAD

**Issue by zsytssk** [NervJS/taro#12873]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:zsytssk/taro-bug-useShareAppMessage.git](git@github.com:zsytssk/taro-bug-useShareAppMessage.git)
**小程序基础库: 3.5.3**
**使用框架: React**

### 复现步骤
直接将仓库代码clone到本地，然后打开src/pages/index/index.tsx
默认是可以设置分享信息的，如果把11行下的代码注释掉，同时打开8行的注释，这时就无法设置分享信息了。

### 期望结果
自定义hook中能设置分享信息

### 实际结果
自定义hook中无法设置分享信息

### 环境信息
```
Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /opt/homebrew/Cellar/node@16/16.16.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /opt/homebrew/Cellar/node@16/16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/taro-h5: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^18.0.0 => 18.2.0 
```

**Comment by Chen-jj** [comment]
@zsytssk 对于页面文件里的 `useShareAppMessage` 钩子调用，Taro 是会通过 AST 分析进行嗅探，然后给页面开启分享功能。但**不会分析页面文件的依赖**，所以导致这个问题。你可以通过配置 [enableShareAppMessage](https://docs.taro.zone/docs/hooks#useshareappmessage) 进行解决，意思是手动打开页面的分享功能。

**Comment by hellohejinyu** [comment]
> @zsytssk 对于页面文件里的 `useShareAppMessage` 钩子调用，Taro 是会通过 AST 分析进行嗅探，然后给页面开启分享功能。但**不会分析页面文件的依赖**，所以导致这个问题。你可以通过配置 [enableShareAppMessage](https://docs.taro.zone/docs/hooks#useshareappmessage) 进行解决，意思是手动打开页面的分享功能。

强烈建议把这个加到文档中去，我还纳闷为啥我不配置 `enableShareAppMessage:  true` 也可以用分享功能，文档中明明说需要配置。但是如果我不在页面中使用 `useShareAppMessage `，又不生效了。搜到这个 issue 才解决了我的困惑。
