### ISSUE TITLE
Vue3 作用域插槽提示类型错误: TransformReact2VueType<SlotProps>

### ISSUE THREAD

**Issue by BeanWei** [NervJS/taro#12880]
### 相关平台
微信小程序

**小程序基础库: 2.27.3**
**使用框架: Vue 3**

### 复现步骤
类似的代码在 nutui 中也可以看到，但是不理解，那边没有提示类型错误么。。。     https://github.com/jdf2e/nutui/blob/11f8cf2098f5aeaa7932cc11886028bfcafd52ef/src/packages/__VUE/calendaritem/index.taro.vue#L39
```vue
<view class="calendar-day">
  <slot name="day" :date="day.type == 'curr' ? day : ''">
    {{ day.type == 'curr' ? day.day : '' }}
  </slot>
</view>
```

### 期望结果
类型提示正确

### 实际结果
不能将类型“{ date: string }”分配给类型“TransformReact2VueType<SlotProps>”。对象字面量只能指定已知属性，并且“date”不在类型“TransformReact2VueType<SlotProps>”中。ts(2322)

### 环境信息
```
Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by agileago** [comment]
主要是taro这边注册了原生标签的类型(tsx)，因为slot是小程序的内置组件，不支持传参，，和vue的不太一样

 https://github.com/NervJS/taro/blob/8ed01c305f8c3ab5719d6400fb440deaab650e00/packages/taro-components/types/index.vue3.d.ts#L277-L279

**Comment by BeanWei** [comment]
@agileago  感谢回复，那有什么hack的办法能够规避这个类型提示呢?

**Comment by agileago** [comment]
> @agileago 感谢回复，那有什么hack的办法能够规避这个类型提示呢?

```typescript
namespace JSX {
     interface IntrinsicElements {
       'slot': any
     }
   }
```
覆盖一下

**Comment by ZakaryCode** [comment]
> 主要是taro这边注册了原生标签的类型(tsx)，因为slot是小程序的内置组件，不支持传参，和vue的不太一样
> 
> https://github.com/NervJS/taro/blob/8ed01c305f8c3ab5719d6400fb440deaab650e00/packages/taro-components/types/index.vue3.d.ts#L277-L279

这里或许可以给 vue 额外修复一下

```diff
- 'slot': TransformReact2VueType<SlotProps>
```
