### ISSUE TITLE
小程序持续集成插件相比微信官方插件功能缺失，无法指定ci机器人编号

### ISSUE THREAD

**Issue by velley** [NervJS/taro#12890]
### 这个特性解决了什么问题？
微信官方ci插件，可以支持多个ci机器人进行代码上传，这样能方便将开发版与体验版分开。如：ci机器人1上传设为体验版，ci机器人2上传设为开发版，多个ci机器人利于项目测试与迭代，希望能支持。

### 这个 API 长什么样？

- 以下为微信官方提供的参数，其中robot参数用于指定ci机器人编号

|键|	类型|	必填	|说明|
|----|----|----|----|
|project|	IProject|	是	|项目对象
|version|	string|	是	|自定义版本号|
|desc	|string|	否	|自定义备注
|setting|	object|	否	|编译设置
|onProgressUpdate|	function	|否	|进度更新监听函数
|robot	|number|	否	|指定使用哪一个 ci 机器人，可选值：1 ~ 30

**Comment by bigmeow** [comment]
可先单独引入使用 `@tarojs/plugin-mini-ci` 版本，
文档： https://github.com/NervJS/taro/tree/feat/3.6/packages/taro-plugin-mini-ci

@velley

**Comment by velley** [comment]
> 

好的 感谢
