### ISSUE TITLE
redux中的connect实现有bug

### ISSUE THREAD

**Issue by skyZhuqing** [NervJS/taro#1289]
------------------------

**问题描述**
[问题描述：下面的代码有bug]

![image](https://user-images.githubusercontent.com/45442381/49192891-064c5d00-f3b8-11e8-8e67-4b9c99e606fb.png)

这样会导致多个相同实例在销毁的时候只会取消一个监听.

另外想咨询下，我如何能够挂在自己的'redux' 组件，貌似 挂在代码被框架写死了
![image](https://user-images.githubusercontent.com/45442381/49192966-50cdd980-f3b8-11e8-99fe-8dadf5975035.png)

**Comment by luckyadam** [comment]
为什么。。 每个实例都对应不同的 subscribe，你再理解一下代码吧

**Comment by skyZhuqing** [comment]
@luckyadam  不懂，请指教
unSubscribe 的变量是在Class 外面 每个实例在销毁的时候，会将“unSubscribe” 设置为null  那下一个实例进行销毁的时候 用的是哪一个“unSubscribe”变量？

**Comment by luckyadam** [comment]
每个组件要连接 redux 都会调用 connect 方法

**Comment by skyZhuqing** [comment]
```
let unSubscribe =null
let c1=new Connect();
let c2=new Connect();
let c3=new Connect();
c1.componentWillMount(); //unSubscribe =c1.listener
c2.componentWillMount();//unSubscribe =c2.listener
c3.componentWillMount();//unSubscribe =c3.listener

c1.componentWillUnMount(); //unSubscribe() 运行结果是 c3.listener 被注销,c1没被注销
c2.componentWillUnMount(); //unSubscribe 为 null  c2没被注销
c3.componentWillUnMount(); //unSubscribe 为null
```

**Comment by skyZhuqing** [comment]
算了 ，当我没提
