### ISSUE TITLE
eslint规则 map循环创建给组件key赋值报错

### ISSUE THREAD

**Issue by lambdaxs** [NervJS/taro#129]
![image](https://user-images.githubusercontent.com/12015791/41460468-789168be-70bf-11e8-9966-4fcff2e81c94.png)

**Comment by yuche** [comment]
谢谢提醒。

https://github.com/NervJS/taro/commit/9b660df235bfa09a217c771bd9773f058ce039ee 修复这个 bug并添加了测试用例。
