### ISSUE TITLE
taro 的  request 不支持 abort，打印出来为 undefined

### ISSUE THREAD

**Issue by hepeng10** [NervJS/taro#12905]
### 相关平台
微信小程序

**小程序基础库: 2.27.3**
**使用框架: React**

### 复现步骤
使用 Taro.request 获取到 requestTask 后，打印 abort 为 undefined。taro 的3.3.20和升级到3.5.8都是这样。
但是将 Taro.request 改为 wx.request 后打印 abort 就有值。

### 期望结果
有 abort 方法

### 实际结果
为 undefined

### 环境信息
```
  Taro CLI 3.5.8 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/opt/nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.8 => 3.5.8 
      @tarojs/components: 3.5.8 => 3.5.8 
      @tarojs/mini-runner: 3.5.8 => 3.5.8 
      @tarojs/plugin-framework-react: 3.5.8 => 3.5.8 
      @tarojs/plugin-mini-ci: 3.5.8 => 3.5.8 
      @tarojs/react: 3.5.8 => 3.5.8 
      @tarojs/runtime: 3.5.8 => 3.5.8 
      @tarojs/taro: 3.5.8 => 3.5.8 
      @tarojs/webpack-runner: 3.5.8 => 3.5.8 
      babel-preset-taro: 3.5.8 => 3.5.8 
      eslint-config-taro: 3.5.8 => 3.5.8 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.8.2
```

**Comment by AdvancedCat** [comment]
请提供一下你的复现 DEMO

**Comment by hepeng10** [comment]
> 请提供一下你的复现 DEMO ， 我本地没有复现你的问题


    req = Taro.request<T>({
      url: reqUrl,
      method: method,
      data: requestData,
    });
    console.log(req?.abort); // 输出 undefined


    req = wx.request<T>({
      url: reqUrl,
      method: method,
      data: requestData,
    });
    console.log(1111, req?.abort); // 输出 abort 函数

我测试的时候已经把可能导致干扰的 request 的各种参数删了，甚至 success 回调方法都没写

**Comment by AdvancedCat** [comment]
可以将 node_modules 删除，然后重新安装依赖，最新版本 taro 应该是没有这个问题的

**Comment by yoyo837** [comment]
还有lock文件也删一下

**Comment by hepeng10** [comment]
> 可以将 node_modules 删除，然后重新安装依赖，最新版本 taro 应该是没有这个问题的

还是一样的，lock 文件也删了的。。。

**Comment by hepeng10** [comment]
> 可以将 node_modules 删除，然后重新安装依赖，最新版本 taro 应该是没有这个问题的

我直接打印 req，Taro.request 是 Promise {<pending>}，wx.request 是 a {uniqueId: 16699521536079702}

**Comment by AdvancedCat** [comment]
把你的 DEMO 发给我吧

**Comment by hepeng10** [comment]
> 把你的 DEMO 发给我吧

排查了发现是用的一个埋点库导致的。。。

**Comment by shmily-jianjian** [comment]
加了拦截器abort也会失效

**Comment by zhaopan-pan** [comment]
> 

+1

**Comment by yoyo837** [comment]
> 排查了发现是用的一个埋点库导致的。。。

如果不是这个原因, 建议开个新issue.

**Comment by lcoln** [comment]
> 加了拦截器abort也会失效

+1
