### ISSUE TITLE
 Taro 的 Textarea 组件没有 confirmType 属性，没有完成onConfirm接口!

### ISSUE THREAD

**Issue by ittat** [NervJS/taro#12911]
### 这个特性解决了什么问题？
平台：H5

小程序的 textarea 组件有 confirm-type，而 Taro 的没有 confirmType。

https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html

https://nervjs.github.io/taro/docs/components/forms/textarea

另外Taro没有完成接口onConfirm：
https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/textarea/index.md

**Comment by TheKonka** [comment]
`confirmType` 和 `onConfirm` 都有支持的， 可以实际测试一下，文档有可能更新落后

**Comment by ittat** [comment]
> `confirmType` 和 `onConfirm` 都有支持的， 可以实际测试一下，文档有可能更新落后
请问h5版本也有支持吗，我这边测试没有效果，看到源代码里面没有这部分代码：

**Comment by ZakaryCode** [comment]
H5 confirmType 暂不考虑支持，onConfirm 将在下一个版本合并
