### ISSUE TITLE
字符串属性赋值字符串变量时会误报taro/jsx-handler-names警告

### ISSUE THREAD

**Issue by tiancheng2000** [NervJS/taro#1295]
### 问题描述
JSX中，对属性赋值字符串变量时会误报taro/jsx-handler-names警告

### 复现步骤
1. 在Page中定义成员变量/常量`config`，内含字符串变量`innerNavBarTitle`
2. 在<Text>或<AtNavBar>JSX中赋值给`value`或`leftText`等，就会提示需以`on`命名（taro/jsx-handler-names）
3. 如果先赋值给一个局部变量如innerNavBarTitle后，再用该变量给`title`等赋值，就不会出ESLint警告
4. 实际运行效果并不受影响（h5, weapp）
![image](https://user-images.githubusercontent.com/3139658/49201143-aadf9680-f3da-11e8-985e-ff0dca07ad1e.png)

### 期望行为
不要误报

### 报错信息
taro/jsx-handler-names

### 系统信息
Node 10.9，Taro 1.1.3，h5+weapp

**Comment by luckyadam** [comment]
升级到最新版本试试

**Comment by tiancheng2000** [comment]
好…我们这边代理管得较严（加上npm没问题、但Yarn的设置好像一直有问题），taro update project 要靠手工改package.json来做😂  下次升级时试一试🙏

**Comment by luckyadam** [comment]
好嘞
