### ISSUE TITLE
vue3多端开发的时候，组件目录下的.vue文件是否也可以通过加平台后缀的形式实现加载不同的组件？

### ISSUE THREAD

**Issue by markchenlife** [NervJS/taro#12969]
### 这个特性解决了什么问题？
一个页面里，可能仅仅是一个小地方需要在不同的平台里实现不同。可以单独把这这个功能放到组件中实现。而不应该是仅仅在整个页面中实现通过后缀加入。

### 这个 API 长什么样？
比如一个产品页，仅仅是显示产品详情的区域不同，我只需要把这个区域做成一个组件，针对不同的平台进行开发就可以了，不需要整个页面都重写。因为api都是一样的。

**Comment by ZakaryCode** [comment]
Duplicate of #9083
