### ISSUE TITLE
官方能否新增一个关于H5多页打包的示例？

### ISSUE THREAD

**Issue by gyt95** [NervJS/taro#12968]
### 这个特性解决了什么问题？
为了H5多页打包，从3.x升级到taro3.5，但官方文档对于H5多页打包的说明实在太少。我在全面升级3.5后，配置了router entry output htmlPluginOption 然后打包上线还是发现有些问题。例如提示找不到definePageConfig。

希望官方能新增一个关于多页打包示例demo。

### 这个 API 长什么样？
至少在更多资源提供一个案例吧。https://docs.taro.zone/docs/composition

**Comment by ZakaryCode** [comment]
听起来是部分依赖缺失导致的，mpa 模式的开发模式和生产模式确实存在一定差异，生产模式需要开发者根据生产环境由开发者自行配置，这些在文档中已有标注。

由于除了 mode 差异，mpa 项目实际与普通 taro 项目并无差异，通过案例或示例 demo 很难比较明确的展示区别，并帮助开发者跳过在生产环境中的各项配置工作。

> 如果有遇到打包的各类问题，欢迎在 issue 下方提交，我们会统一回复并在文档中标注为常见问题

**Comment by gyt95** [comment]
> 听起来是部分依赖缺失导致的，mpa 模式的开发模式和生产模式确实存在一定差异，生产模式需要开发者根据生产环境由开发者自行配置，这些在文档中已有标注。
> 
> 由于除了 mode 差异，mpa 项目实际与普通 taro 项目并无差异，通过案例或示例 demo 很难比较明确的展示区别，并帮助开发者跳过在生产环境中的各项配置工作。
> 
> > 如果有遇到打包的各类问题，欢迎在 issue 下方提交，我们会统一回复并在文档中标注为常见问题

好的，感谢回答

**Comment by CH2655** [comment]
> https://docs.taro.zone/docs/composition
请问h5多页打包问题解决了吗
