### ISSUE TITLE
taro v3.5.7 版本打包后包体积过大的问题

### ISSUE THREAD

**Issue by JTangming** [NervJS/taro#12977]
### 这个特性解决了什么问题？

Taro  H5 端都需要引入 @tarojs/components 和 @tarojs/taro-h5 等基础依赖包。
在编译、打包之后，这些依赖包大约会在首屏占用 3-400KB 的空间，这严重限制了 Taro H5 端应用的性能优化空间。

事实上，我们在 H5 端应用中并不会使用到全部的 Taro 组件和 Api。将这些依赖包全部打包进应用是没有必要，也是不合理的。

例如，taro v3.5.7 版本 taro init 后，打包用 analyzer 分析看，包体积过大了，特别是 taro-video-control_3.entry 这个文件

见图片：

![analyzer](https://user-images.githubusercontent.com/11422098/207529003-a394eacb-2ae3-45b9-a416-f18c4acc6b9c.jpg)

就是一个简单demo，代码中引用示例如下：
```js
import { View, Text, Button } from '@tarojs/components';
import { useNavigationBar, useModal, useToast } from 'taro-hooks';
```

### 这个 API 长什么样？

进一步缩减 taro 代码体积、按需引用而不是全部打包，有没有相关更进一步的优化方案？

**Comment by ZakaryCode** [comment]
组件依赖通过懒加载引入，不影响实际包体大小

> 特殊场景可参考[文档](https://nervjs.github.io/taro-docs/blog/2022-01-20-Taro-3.4#3-dynamic-import-node)
