### ISSUE TITLE
3.5.10 版本设置tabBar之后 yarn dev:h5 不显示页面内容

### ISSUE THREAD

**Issue by 3Fu** [NervJS/taro#12982]
### 相关平台
H5

### 复现仓库
[https://gitee.com/liuxfu/tarojs-test.git](https://gitee.com/liuxfu/tarojs-test.git)
**浏览器版本: 无要求**
**使用框架: Vue 2**

### 复现步骤
yarn 
yarn dev:h5

### 期望结果
页面正常显示，不要报错白屏

### 实际结果
除tabBar，其他区域不显示

### 环境信息
```
Taro v3.5.10


  Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\fu970\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by 3Fu** [comment]
持续关注

**Comment by imwangpan** [comment]
我也是同样问题，无语了

**Comment by hisanshao** [comment]
https://github.com/NervJS/taro/pull/12965 合并进去了，还没发布

**Comment by imwangpan** [comment]
> #12965 合并进去了，还没发布

请问一下，这个修改大概什么时候能发布？

**Comment by houhoz** [comment]
什么时候发布新版本呢

**Comment by zybieku** [comment]
+1

**Comment by ziqiudev** [comment]
+1

**Comment by ZakaryCode** [comment]
> 什么时候发布啊，我们开发都是基于h5的，现在卡主了，所有的版本都会提示这个

正在发布 #13055

**Comment by shijunti19** [comment]
@zybieku https://taro-docs.jd.com/docs/envs
  {process.env.TARO_ENV === 'weapp' && <ScrollViewWeapp />}

问下你，这个功能已经作废了吗，我测试了无效啊，直接原字符显示了，有没有办法在编译坏境把不属于当前环境的代码删了
