### ISSUE TITLE
useLoad / useDidShow 回调函数类型缺少 options 参数

### ISSUE THREAD

**Issue by toyobayashi** [NervJS/taro#12983]
### 相关平台
H5

**浏览器版本: Chrome 108**
**使用框架: React**

### 复现步骤
用 typescript 写 `useLoad((options) => {})`，类型报错

### 期望结果
useLoad / useDidShow 传入带 options 参数的回调函数，类型检查不报错

### 实际结果
报错

### 环境信息
```
Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - C:\Users\toyobayashi\app\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Users\toyobayashi\app\nodejs\yarn.CMD
      npm: 8.5.5 - C:\Users\toyobayashi\app\nodejs\npm.CMD
```

**Comment by wangxiao95** [comment]
useDidShow 传入带 options 参数的回调函数，拿到的参数结果永远是空对象，这什么情况，但是在公共入口ts里的onShow钩子可以拿到参数，页面组件怎么获取onShow的参数？

**Comment by Brucia323** [comment]
> useDidShow 传入带 options 参数的回调函数，拿到的参数结果永远是空对象，这什么情况，但是在公共入口ts里的onShow钩子可以拿到参数，页面组件怎么获取onShow的参数？

+1

**Comment by Niubility-SunLight** [comment]
我也遇到了，有什么办法解决
