### ISSUE TITLE
升级3.5.8后执行npm run dev:weapp 对使用了react-redux装饰器@connect的地方报错提示[ERROR] Unexpected "@"

### ISSUE THREAD

**Issue by ChiJohn** [NervJS/taro#12998]
### 相关平台
微信小程序

**小程序基础库: 2.4.0**
**使用框架: React**

### 复现步骤
升级3.5.8后
对使用了react-redux装饰器@connect的地方

执行npm run dev:weapp报错提示[ERROR] Unexpected "@"，

执行 npm run build:weapp  并没有提示

![错误截图](https://files.catbox.moe/zbl3nk.jpg  "图片title")

### 期望结果
不提示 [X ERROR[]ERROR ]Unexpected "@"

### 实际结果
正常，不提示

### 环境信息
```
👽 Taro v3.5.8


  Taro CLI 3.5.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.1 - C:\topscore\software\nodejs\node.EXE
      npm: 8.19.2 - C:\topscore\software\nodejs\npm.CMD
```

**Comment by yoyo837** [comment]
babel 装饰器支持配置检查一下呢?

**Comment by yoyo837** [comment]
> @ChiJohn 麻烦提供一下 demo

和隔壁这个一样 #13007, 这个有 demo

**Comment by yoyo837** [comment]
Duplicate of #13007
