### ISSUE TITLE
一个JSX元素中的不同事件绑定了同一方法时，后者的参数值会覆盖掉前者

### ISSUE THREAD

**Issue by tiancheng2000** [NervJS/taro#1299]
**问题描述**
一个JSX元素中的不同事件绑定了同一方法时，后者的参数值会覆盖掉前者

**复现步骤**
Taro代码，`onTouchStart`与`onTouchEnd` 绑定了同名方法，最后一个参数值不同：
```js
{groupedItems[seqLabelIdx].map( (item, itemIdx) => {
    return <View className='single-item-container' key={item._id_} 
        onTouchStart={this.showTooltip.bind(this, item.id, true)}
        onTouchEnd={this.showTooltip.bind(this, item.id, false)}>
        ......
```
编译得到的weapp代码(WXML)，按目前的编译方法，将只能取到后一次绑定所用的参数值(`false`)
```xml
<view class="single-item-container" wx:key="{{item.$original._id_}}" 
  bindtouchstart="showTooltip" bindtouchend="showTooltip" 
  wx:for="{{seqLabelIdx.$anonymousCallee__0}}" wx:for-item="item" wx:for-index="itemIdx" 
  data-e-showTooltip-so="this" data-e-showTooltip-a-a="{{item.$original.id}}"
  data-e-showTooltip-a-b="{{false}}">
  ......
```

**期望行为**
能正确绑定两个不同的参数值，或许需编译成`data-e-bindtouchstart-a-b`(跟着事件名走)，而非`data-e-showTooltip-a-b`(跟着方法名走)

**报错信息**
无

**系统信息**
Taro 1.1.3, NodeJs 10.9, weapp

**Comment by luckyadam** [comment]
目前是存在这个问题，暂时不太好解决，会在文档中注明一下

**Comment by tiancheng2000** [comment]
恩，可以大致猜测到难处理的原因…
为了方法能找到参数，`data-e-xxx-a-[a..z]` 可以仍旧跟着方法名走，但把第一个参数的位置留给一个“切换器”？后面的参数，可以基于这个切换器前缀来寻找；当然这种Inner规则的改变也可能牵一发而动全身了🙏

**Comment by luckyadam** [comment]
@tiancheng2000 对，后续考虑换一种实现方式

**Comment by Chen-jj** [comment]
[fix(taro-weapp/alipay/swan/tt/): 小程序端支持在组件上绑定 bind 不同参数的同一回调函数](https://github.com/NervJS/taro/commit/38ce066e69e0a5f7ffe2aeae1c4059f1ef575e31)
