### ISSUE TITLE
状态管理只支持redux吗？有没有可能自己选择？

### ISSUE THREAD

**Issue by xdlrt** [NervJS/taro#13]

**Comment by luckyadam** [comment]
目前只提供了 redux的官方支持~其他状态管理库目前需要自己开发相关支持哦，欢迎PR~

**Comment by alihanniba** [comment]
mobx

**Comment by zhangchao828** [comment]
希望能支持mobx，，它相对于用redux更适合小应用，而小程序往往都不会很大

**Comment by luckyadam** [comment]
mobx +1

**Comment by brucecodezone** [comment]
mobx +1

**Comment by luckyadam** [comment]
@dongliang1993 可以有~

**Comment by xingyifei** [comment]
mobx + 1

**Comment by looch** [comment]
mobx + 1

**Comment by Varavarforvar** [comment]
mobx + 1

**Comment by hicoldcat** [comment]
mobx+1

**Comment by luckyadam** [comment]
#140

**Comment by tolerance-go** [comment]
唱个反调，谁说一定要直接用原生的 redux 有 redux-actions dva 等很多改良框架等着你呢

**Comment by T-baby** [comment]
mobx+1

**Comment by zhuanglong** [comment]
dva支持吗

**Comment by ranshaw** [comment]
强烈推荐weappx，原生小程序，wepy和taro都支持的，上手只需要掌握4个api，https://github.com/tolerance-go/weappx，建议官方在文档上推荐下

**Comment by Darcrandex** [comment]
mobx +1

**Comment by terranc** [comment]
mobx+1

**Comment by linzixi31** [comment]
mobx，taro什么时候加入mobx？

**Comment by yuche** [comment]
mobx 已经支持:
https://nervjs.github.io/taro/docs/mobx.html#docsNav

其它的状态管理可以去 [awesome-taro](https://github.com/NervJS/awesome-taro)
或者在 github 搜索 taro + 你需要的状态管理工具
