### ISSUE TITLE
taro convert转换小程序的官方demo后运行dev:weapp报错 Unexpected "@"

### ISSUE THREAD

**Issue by fantasy525** [NervJS/taro#13007]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/fantasy525/taro_convert_weapp.git](https://github.com/fantasy525/taro_convert_weapp.git)
**小程序基础库: 2.28.1**
**使用框架: React**

### 复现步骤
1.克隆代码
2.yarn
3.yarn dev:weapp

### 期望结果
编译成功，打开小程序能看到

### 实际结果
 [ERROR] Unexpected "@"

    src/pages/logs/logs.js:9:0:
      9 │ @withWeapp({
        ╵ ^

✘ [ERROR] Unexpected "@"

    src/app.js:7:0:
      7 │ @withWeapp({
        ╵ ^

✘ [ERROR] Unexpected "@"

    src/pages/index/index.js:10:0:

### 环境信息
```
Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-react: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/react: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      @tarojs/with-weapp: ^3.5.7 => 3.5.10 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
      react: ^18.0.0 => 18.2.0 

```

**Comment by fantasy525** [comment]
补充一个问题，我的电脑是 mac M1 的cpu，安装的node-sass不支持，报错

Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93) For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1

**Comment by yoyo837** [comment]
应该切换到`sass`, Dart Sass

**Comment by fantasy525** [comment]
> 应该切换到`sass`, Dart Sass

是说让taro内部切换吗还是我自己切换？

**Comment by yoyo837** [comment]
内部

**Comment by yoyo837** [comment]
> 补充一个问题，我的电脑是 mac M1 的cpu，安装的node-sass不支持，报错
> 
> Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93) For more information on which environments are supported please see: https://github.com/sass/node-sass/releases/tag/v4.14.1

你仓库没看见这个错误呢

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/208839984-5e6f5bbe-1d38-4ebd-8bba-aa1510260234.png)

**Comment by yoyo837** [comment]
初步看`babel-preset-taro/index.js` 没执行到就已经抛出错误了

**Comment by Chen-jj** [comment]
> 补充一个问题，我的电脑是 mac M1 的cpu，安装的node-sass不支持，报错
> 
> Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93) For more information on which environments are supported please see: https://github.com/sass/node-sass/releases/tag/v4.14.1

`@tarojs/webpack5-runner` 依赖的是 `sass`，安装依赖后观察 lockfile 也没找到 node-sass，不清楚是哪里来的，可以你要自行排查下。

**Comment by Chen-jj** [comment]
@fantasy525 感谢 @yoyo837 的提示，报错出在依赖预编译阶段，还没到 Webpack 打包阶段。依赖预编译时会使用 esbuild 进行 bundle，而 esbuild 只在 tsx loader 中实现了 `decorator`（https://github.com/evanw/esbuild/issues/104#issuecomment-1025061506），因此需要把 `.js` `.jsx` 都配置为使用 esbuild 的 tsx loader。

**Comment by yoyo837** [comment]
> @fantasy525 感谢 @yoyo837 的提示，报错出在依赖预编译阶段，还没到 Webpack 打包阶段。依赖预编译时会使用 esbuild 进行 bundle，而 esbuild 只在 tsx loader 中实现了 `decorator`（[https://github.com/evanw/esbuild/issues/104#issuecomment-1025061506），因此需要把](https://github.com/evanw/esbuild/issues/104#issuecomment-1025061506%EF%BC%89%EF%BC%8C%E5%9B%A0%E6%AD%A4%E9%9C%80%E8%A6%81%E6%8A%8A) `.js` `.jsx` 都配置为使用 esbuild 的 tsx loader。

666

**Comment by fantasy525** [comment]
@Chen-jj 发布新版本后关闭

**Comment by tourze** [comment]
等发布中。。。刚好遇到这个问题

**Comment by fantasy525** [comment]
> ![image](https://user-images.githubusercontent.com/6134547/208839984-5e6f5bbe-1d38-4ebd-8bba-aa1510260234.png)

<img width="623" alt="image" src="https://user-images.githubusercontent.com/22516157/209458956-319e120a-b941-4baa-be74-43d941cbf4a7.png">

**Comment by fantasy525** [comment]
> > 补充一个问题，我的电脑是 mac M1 的cpu，安装的node-sass不支持，报错
> > Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93) For more information on which environments are supported please see: https://github.com/sass/node-sass/releases/tag/v4.14.1
> 
> `@tarojs/webpack5-runner` 依赖的是 `sass`，安装依赖后观察 lockfile 也没找到 node-sass，不清楚是哪里来的，可以你要自行排查下。

嗨，我发现我把taro相关的包升级到最新版本就没node-sass的问题了
@tarojs/mini-runner，@tarojs/webpack-runner，babel-preset-taro
这三个都升级到3.5.10，之前的版本有这个问题
