### ISSUE TITLE
在 typescript 下使用 css module 时需要自动转换类型文件

### ISSUE THREAD

**Issue by DiamondYuan** [NervJS/taro#1300]
我觉得支持 typings-for-css-modules-loader 会很棒。

**Comment by yuche** [comment]
这层我觉得在框架做是不合适的，因为他的主要功能是为了编辑器解析，生成出来的代码没有意义。
随便一搜就有相关的插件：
https://marketplace.visualstudio.com/items?itemName=clinyong.vscode-css-modules
