### ISSUE TITLE
运行H5的时候出现props和setState问题

### ISSUE THREAD

**Issue by NiMingzhen** [NervJS/taro#1301]
**问题描述**

将老的项目迁移到Taro，在跑H5的时候出现props和setState问题，如下

```js

export default class HomeNav extends Component {
  constructor() {
    super(...arguments)
    this.state = {
      imgList: [
        {
          active: 'beio-active-new.png',
          unactive: 'beio-no-active-new.png',
          key: '0',
          activeCls: 'beio-a',
          unActiveCls: 'beio',
        },
        {
          active: 'omei-active-new.png',
          unactive: 'omei-no-active-new.png',
          key: '1',
          cls: 'nav nav-omei',
          activeCls: 'omei-a',
          unActiveCls: 'omei',
        },
        {
          active: 'xian-active-new.png',
          unactive: 'xian-no-active-new.png',
          key: '2',
          activeCls: 'xian-a',
          unActiveCls: 'xian',
        },
        {
          active: 'zhong-active-new.png',
          unactive: 'zhong-no-active-new.png',
          key: '3',
          activeCls: 'zhong-a',
          unActiveCls: 'zhong',
        },
      ],
      activeKey: '0',
      isNeedImgBase: true,
      mode: 'scaleToFill',
    }
  }
  toSearchPage() {
    navigateTo('/pages/search/index')
  }
  selectNav(key) {
    this.setState({
      activeKey: key,
    })
    this.props.onClick(key)
  }
  render() {
    const { imgList, activeKey, isNeedImgBase, mode } = this.state
    const imgElemList = imgList.map((img) => {
      let src = ''
      let cls = 'nav-img'
      if (activeKey === img.key) {
        src = img.active
        cls = `${cls} ${img.activeCls}`
      } else {
        src = img.unactive
        cls = `${cls} ${img.unActiveCls}`
      }
      return <View className='nav' key={img.key} onClick={this.selectNav.bind(this, img.key)}>
        <View className={cls}>
          <ImageFilter src={src} isNeedImgBase={isNeedImgBase} mode={mode}></ImageFilter>
        </View>
      </View>
    })

    return (
      <View className='home-nav-cont'>
        <View className='search' onClick={this.toSearchPage}>
          <View className='icon'></View>
          <View className='split'></View>
        </View>
        <View className='nav-ct'>
          {imgElemList}
        </View>
      </View>
    )
  }
}

```
项目配置
![image](https://user-images.githubusercontent.com/6270101/49208707-72988200-f3f3-11e8-91d6-cccfe6a2f0e0.png)

使用的Taro v1.1.4

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
能够正常运行
**报错信息**
![image](https://user-images.githubusercontent.com/6270101/49208411-b048db00-f3f2-11e8-87db-3ea95cede6ab.png)

![image](https://user-images.githubusercontent.com/6270101/49208549-03229280-f3f3-11e8-9fdc-a5efa7532508.png)、

**系统信息**

 - 操作系统: [e.g. IOS 10.13.6 ]
 - Taro 版本 [e.g. v1.1.4]
 - Node.js 版本 [e.g.v10.3.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
报错的地方点进去看下，然后截个图

**Comment by NiMingzhen** [comment]
![image](https://user-images.githubusercontent.com/6270101/49267507-d83d4a80-f495-11e8-9e9e-464bd2334bfe.png)
![image](https://user-images.githubusercontent.com/6270101/49267522-eb501a80-f495-11e8-9653-4ce9b69168db.png)
![image](https://user-images.githubusercontent.com/6270101/49267537-f86d0980-f495-11e8-8f73-14f258baf267.png)

**Comment by NiMingzhen** [comment]
这个是父组件的代码

`import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

import HomeNav from './components/HomeNav'
import ImgBrief from './components/ImgBrief'
import FashionItem from './components/FashionItem'
import StyleSeriesItem from './components/StyleSeriesItem'
import StandForBrand from '../../components/StandForBrand'
import ImageFilter from '../../components/ImageFilter'
import MenuNav from '../../components/MenuNav'
import AuthLogin from '../../components/AuthLogin'
import { sharePage, navigateTo } from '../../utils/wxTool'
import { checkUserLogin } from '../../utils/tool'
import './index.scss'

const currentPath = '/pages/index/index'
const classicImg = 'home-clssic-style.png'

export default class Index extends Component {
  config = {
  }
  constructor() {
    super(...arguments)
    this.state = {
      currentKey: '0',
      isShow: false,
      currentChannel: {},
      channelsList: [],
    }
  }

  componentWillMount() { }

  componentDidMount() {
    this.loadData()
    this.checkGetPriceLogin()
  }

  componentWillUnmount() { }

  componentDidShow() { }

  componentDidHide() { }

  onShareAppMessage() {
    return sharePage(currentPath, this.$router.params)
  }

  async loadData() {
    const res = await Taro.$http({
      method: 'get',
      url: 'comparison/main-style',
    })

    const results = res.results || {}
    const channelsList = results.channels || []
    this.setState({
      channelsList,
    }, () => {
      this.getTargetData()
    })
  }

  getTargetData() {
    const currentChannel = this.state.channelsList[parseInt(this.state.currentKey, 10)] || {}
    this.setState({
      currentChannel,
    })
  }

  selectNav(key) {
    this.setState({
      currentKey: key,
    }, this.getTargetData)
  }

  toStyleDetail() {
    navigateTo(`/pages/style/index?style_id=${this.state.currentChannel.id}`)
  }

  toSeriesDetail(seriesId) {
    navigateTo(`/pages/series/index?series_id=${seriesId}`)
  }

  toBrandDetail(brandId) {
    navigateTo(`/pages/brand/index?brand_id=${brandId}`)
  }

  checkGetPriceLogin() {
    const clearT = setTimeout(() => {
      const checkData = checkUserLogin()
      if (checkData.isLogin) {
        return
      }

      // this.setState({
      //   isShow: !checkData.isLogin && !Taro.$hasShowAuthLogin,
      // })

      Taro.$hasShowAuthLogin = true
      clearTimeout(clearT)
    }, 1500)
  }

  closeUserLogin() {
    this.setState({
      isShow: false,
    })
  }

  render() {
    const { currentChannel = {}, isShow } = this.state
    const seriesList = (currentChannel.comparison_style_series || []).map((series) => {
      return <View className='style-item-ct' key={series.style_series_id}>
        <StyleSeriesItem
          seriesData={series}
          onClick={this.toSeriesDetail}
        />
      </View>
    })
    return (
      <View className='home-cont'>
        <HomeNav onClick={this.selectNav}></HomeNav>
        {
          currentChannel.url &&
          <View className='img-brief-ct'>
            <ImgBrief
              url={currentChannel.url}
              title={currentChannel.title}
              subtitle={currentChannel.description}
              onClick={this.toStyleDetail}
            />
          </View>
        }
        {
          currentChannel.representative_brand &&
          <View>
            <View className='subtitle'>{currentChannel.representative_brand.title}</View>
            <View className='stand-for-brand-ct'>
              <StandForBrand
                brandList={currentChannel.representative_brand.brands || []}
                onClick={this.toBrandDetail}
              />
            </View>
          </View>
        }
        {
          currentChannel.representative_product &&
          <View>
            <View className='subtitle'>{currentChannel.representative_product.title}</View>
            <View>
              <FashionItem
                fashionsList={currentChannel.representative_product.products || []}
                onClick={this.toStyleDetail}
              />
            </View>
          </View>
        }
        {
          currentChannel.comparison_style_series &&
          <View>
            <View className='classic-style-ct'>
              <View className='img-ct'>
                <ImageFilter src={classicImg} mode='scaleToFill' alt='风格系列' isNeedImgBase />
              </View>
            </View>
            {seriesList}
          </View>
        }
        <View>
          <MenuNav currentPath={currentPath}></MenuNav>
        </View>
        <AuthLogin
          isShow={isShow}
          onCloseUserLogin={this.closeUserLogin}
        ></AuthLogin>
      </View>
    )
  }
}

`

**Comment by Littly** [comment]
有可以复现的demo吗？从你给的源码看不出来什么情况
