### ISSUE TITLE
taro使用uCharts

### ISSUE THREAD

**Issue by lyj6464** [NervJS/taro#13025]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/lyj6464/IssuesPj.git](https://github.com/lyj6464/IssuesPj.git)
**小程序基础库: 2.76.0.4**
**使用框架: React**

### 复现步骤
1.首先打包成抖音小程序 yarn dev:tt;2.console控制台就开始报错

### 期望结果
渲染出现折线图表

### 实际结果
出现一个报错API_ERROR: at createSelectorQuery exec getContext:fail Canvas: current node only supports undefined context

### 环境信息
```
  Taro CLI 3.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.2 - C:\Program Files (x86)\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\admin_lx\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files (x86)\nodejs\npm.CMD
```

**Comment by xuanzebin** [comment]
当前项目中的 taro 版本存在一些问题，将 taro 版本升级到 3.6.5 即可正常显示。
