### ISSUE TITLE
NutUI使用pnpm启动报错，版本3.5.6

### ISSUE THREAD

**Issue by szg2008** [NervJS/taro#13027]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/jdf2e/nutui.git](https://github.com/jdf2e/nutui.git)
**小程序基础库: 2.27.1**
**使用框架: Vue 3**

### 复现步骤
1.在v4分支，使用pnpm安装依赖，完成之后启动 pnpm dev:taro:h5，之后就会看到报错
2、进入sites/mobile-taro/vue目录，同样是使用pnpm安装依赖，然后执行 pnpm build:h5，也会报错

### 期望结果
两个命令可以正常打包和启动

### 实际结果
不能启动，报错

### 环境信息
```
Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.0.0 - ~/.nvm/versions/node/v17.0.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v17.0.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/mini-runner: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-vue3: 3.5.6 => 3.5.6 
      @tarojs/plugin-html: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
```

---
### 补充信息
1、执行 pnpm dev:taro:h5
👽 Taro v3.5.6

/Users/suzigang/Downloads/project/nutui4.0/nutui/src/sites/mobile-taro/vue/node_modules/.pnpm/registry.npmmirror.com enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:309
			const error = new Error("Can't "   message);
			              ^

Error: Can't resolve '@tarojs/taro' in '/Users/suzigang/Downloads/project/nutui4.0/nutui/src/sites/mobile-taro/vue'
    at finishWithoutResolve (/Users/suzigang/Downloads/project/nutui4.0/nutui/src/sites/mobile-taro/vue/node_modules/.pnpm/registry.npmmirror.com enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:309:18)
    
Node.js v17.0.0

2、执行 pnpm build:h5
✖ Webpack
  Compiled with some errors in 1.43m

✖ Errors: 

resolve '@tarojs/taro' in '/Users/suzigang/Downloads/project/nutui4.0/nutui/src/packages/__VUE/picker'
  Parsed request is a module
  using description file: /Users/suzigang/Downloads/project/nutui4.0/nutui/package.json (relative path: ./src/packages/__VUE/picker)
    aliased with mapping '@tarojs/taro': '@tarojs/taro-h5' to '@tarojs/taro-h5'
      Parsed request is a module

3、使用 yarn安装并且启动，一切正常。

**Comment by ZakaryCode** [comment]
使用 pnpm 请根据 [Taro 3.5 升级指南](https://nervjs.github.io/taro-docs/blog/2022/07/26/Taro-3.5#5-%E4%BD%BF%E7%94%A8-pnpm)相关指引或者根据最新的初始项目补充相关依赖，避免依赖缺失导致的错误
