### ISSUE TITLE
taro3.5.10， 服务器contos6+ 编译出现错误

### ISSUE THREAD

**Issue by zhouzyc** [NervJS/taro#13039]
### 相关平台
H5

### 复现仓库
[https://gitee.com/JS-VeryHappy/vh-mobile-demo.git](https://gitee.com/JS-VeryHappy/vh-mobile-demo.git)
**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤

yarn dev:h5;
1.出现错误：
yarn run v1.22.17
$ cross-env BUILD_ENV=dev taro build --type h5
?? Taro v3.5.10

thread '<unnamed>' panicked at 'attempt to divide by zero', library/std/src/sys/unix/thread.rs:552:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 期望结果
正常运行

### 实际结果
出现错误

### 环境信息
```
Taro CLI 3.5.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 
      Yarn: 1.22.19 
      npm: 8.3.1

```

**Comment by Chen-jj** [comment]
不要上传根目录的 .swc 试试，ignore 掉。

**Comment by zhouzyc** [comment]
> 不要上传根目录的 .swc 试试，ignore 掉。

![image](https://user-images.githubusercontent.com/18420689/209647870-5438b3e9-81c0-49d1-a363-4857cb9571b4.png)
git中没有这个文件

**Comment by Chen-jj** [comment]
那感觉是这个问题：https://github.com/NervJS/taro/issues/12674#issuecomment-1302103171

**Comment by zhouzyc** [comment]
锁定版本   "resolutions": { "@swc/core": "1.3.3" } 后正常，1.3.4+ 全部报错
