### ISSUE TITLE
h5跳页面错误

### ISSUE THREAD

**Issue by duanzb0** [NervJS/taro#13046]
### 相关平台
H5

**浏览器版本: 谷歌**
**使用框架: React**

### 复现步骤
跳转页面后 提示error 没有找到已经加载了的页面，请在页面加载完成后时候此 API。

### 期望结果
正常跳转

### 实际结果
跳转失败

### 环境信息
```
 Taro v3.5.6


  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

**Comment by duanzb0** [comment]
![image](https://user-images.githubusercontent.com/40846827/209789084-14ae658c-78fc-4f0a-894a-cb11fa64dba9.png)

**Comment by ZakaryCode** [comment]
看起来 createVideoContext 错误导致的问题，可以通过以下两个方向验证：

- getCurrentPages 是否能在 createVideoContext 调用前获取页面实例
- createVideoContext 是否调用过快，在页面注入前调用导致相关问题（可以延迟调用，比如在 show 生命周期或者通过点击事件触发等
