### ISSUE TITLE
路由跳转成功后获取不到eventChannel对象

### ISSUE THREAD

**Issue by z-tm314** [NervJS/taro#13049]
### 相关平台
H5

**浏览器版本: chrome 108.0.5359.125**
**使用框架: Vue 2**

### 复现步骤
`Taro.navigateTo({
           url:"/pages/wsla/caseLitigant/msysCaseLitigant?index="   that.dsrxh,
           events: {
                    // 为指定事件添加一个监听器，获取被打开页面传送到当前页面的数据
                    acceptDataFromOpenedPage: function(data) {
                        that.dsrxh = that.dsrxh   1;
                        that.dsrList.push(data);
                    }
           },
           success: function (res)  {
                    console.log(res,"res")
                    res.eventChannel.emit('acceptDataFromOpenerPage', { data: 'test'})
            }
})`
跳转成功没有eventChannel对象

### 期望结果
找到eventChannel对象并在B页面获取传递的参数

### 实际结果
没有找到eventChannel对象

### 环境信息
```
 Taro CLI 3.4.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - D:\software install\node\node.EXE
      Yarn: 1.22.10 - C:\Users\Dell\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - D:\software install\node\npm.CMD
```

**Comment by ZakaryCode** [comment]
目前不支持 eventChannel，可以先通过 eventCenter 替代

**Comment by z-tm314** [comment]
> 目前不支持 eventChannel，可以先通过 eventCenter 替代
官方网站里还有这个示例，有点误导了

**Comment by ShengXi2000** [comment]
那要怎么写啊，我在跳转success里触发了全局event，但是跳转的组件里无法监测到。这是我的代码：
跳转组件：
![image](https://user-images.githubusercontent.com/83119504/227766053-5801e127-55b9-4f15-8e45-f76f5f30a1b1.png)
跳转后的组件：
![image](https://user-images.githubusercontent.com/83119504/227766086-375a3547-6e83-4659-92cd-ce61ac4634ee.png)
这是我实现的代码。
期望结果：跳转后组件能够正常监听并触发order事件回调
实际结果：没有触发order事件回调

**Comment by QingyunYang** [comment]
好像没有好办法，期待taro支持

**Comment by ZEJIA-LIU** [comment]
3.6.28已支持
