### ISSUE TITLE
taro 的Button组件 能否 支持小程序原生的 Button组件的 bindlongtap?

### ISSUE THREAD

**Issue by Jesse-Fan** [NervJS/taro#1305]
**问题描述**
 查看taro封装的Button组件，只有单纯的onClick单次点击事件

**复现步骤**
[复现问题的步骤]
无步骤

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
 期望taro 的Button组件可以像小程序的Button组件一样绑定bindlongtap事件

**系统信息**

 - 操作系统: [e.g. MacOS 14]
 - Taro 版本 [e.g. v.@tarojs/taro@1.2.0-beta.1]
 - Node.js 版本 [e.g. v11.2.0]
 - 报错平台 [weapp]

**Comment by nxboo** [comment]
跟本不支持啊
