### ISSUE TITLE
设置自定义tabBar后，微信小程序报错：[渲染层错误] [jsbridge] invoke loadComponents fail: too eayly.

### ISSUE THREAD

**Issue by joket1999** [NervJS/taro#13053]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/joket1999/taro-custom-tabBar-demo.git](https://github.com/joket1999/taro-custom-tabBar-demo.git)
**小程序基础库: 所有版本**
**使用框架: React**

### 复现步骤
设置自定义tabBar，运行npm run dev:weapp 或者 npm run build:weapp.

page标签里空白没内容，page外面只有自定义tabBar

修改代码或者点击编译按钮刷新会正常渲染页面，关闭项目重新选择项目打开，此问题必定出现。

不使用自定义tabBar则不会出现此问题

### 期望结果
正常渲染页面

### 实际结果
报错：[渲染层错误] [jsbridge] invoke loadComponents fail: too eayly.

页面空白

### 环境信息
```
Taro CLI 3.5.10 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.1/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
    npmPackages:
      @tarojs/components: 3.5.10 => 3.5.10
      @tarojs/mini-runner: 3.5.10 => 3.5.10
      @tarojs/plugin-framework-react: ^3.5.10 => 3.5.10
      @tarojs/plugin-mini-ci: ^3.5.10 => 3.5.10
      @tarojs/react: 3.5.10 => 3.5.10
      @tarojs/rn-runner: ^3.5.10 => 3.5.10
      @tarojs/runtime: 3.5.10 => 3.5.10
      @tarojs/taro: 3.5.10 => 3.5.10
      @tarojs/taro-rn: ^3.5.10 => 3.5.10
      @tarojs/webpack-runner: 3.5.10 => 3.5.10
      babel-preset-taro: 3.5.10 => 3.5.10
      eslint-config-taro: 3.5.10 => 3.5.10
      react: ^18.2.0 => 18.2.0
      react-native: ^0.69.5 => 0.69.7
      taro-ui: 3.1.0-beta.3 => 3.1.0-beta.3

```

---
### 补充信息
<img width="547" alt="图片" src="https://user-images.githubusercontent.com/6611880/209972886-3d216a9e-b184-4771-8133-d722cb3044fd.png">
<img width="419" alt="图片" src="https://user-images.githubusercontent.com/6611880/209972988-125efc53-2df3-43f2-8037-12364c34eab9.png">

**Comment by unetcore** [comment]
看看有没有开启lazyCodeLoading: 'requiredComponents'，我关闭这个设置后正常了

**Comment by joket1999** [comment]
> 看看有没有开启lazyCodeLoading: 'requiredComponents'，我关闭这个设置后正常了

是有开启lazyCodeLoading: 'requiredComponents'，关掉确实正常了
