### ISSUE TITLE
Taro 3.5.7 使用默认的sourceMap配置，微信开发者工具里定位不到代码报错位置

### ISSUE THREAD

**Issue by Magicianzzk** [NervJS/taro#13069]
### Discussed in https://github.com/NervJS/taro/discussions/13068

<div type='discussions-op-text'>

<sup>Originally posted by **Magicianzzk** January  3, 2023</sup>
代码里书写例如 Promise.reject('xxxx'), 微信开发者工具里定位不到代码位置
![image](https://user-images.githubusercontent.com/20254317/210321252-34566712-f1e4-4795-b3df-1977a2a7fa4c.png)

但是console.error('xxx')是可以定位到的，说明source Map应该是生成了的</div>

**Comment by gyt95** [comment]
同问
