### ISSUE TITLE
关于传递组件render的问题

### ISSUE THREAD

**Issue by Herryjoeson** [NervJS/taro#1306]
页面代码
![image](https://user-images.githubusercontent.com/19682746/49235636-81078d80-f435-11e8-96f2-05657401fa68.png)
scaffold代码
![image](https://user-images.githubusercontent.com/19682746/49235662-8f55a980-f435-11e8-8041-1bd6ad90e7e8.png)
navbar代码
![image](https://user-images.githubusercontent.com/19682746/49235695-9f6d8900-f435-11e8-9a9b-9ff337e421be.png)
我就想实现在scaffold使用自定义头部，头部中使用的自己封装的navbar，并且去实现navbar自定义的视图.按照图上的写法小程序编译失败了,就是报错要传递navbar的renderCenter不是一个jsx 表达式

**Comment by yuche** [comment]
贴代码不要贴截图

**Comment by Herryjoeson** [comment]
@yuche

**Comment by Herryjoeson** [comment]
是修复了还是说什么问题
