### ISSUE TITLE
componentDidMount周期在路由跳转前就会执行

### ISSUE THREAD

**Issue by L-x-C** [NervJS/taro#13075]
### 相关平台
H5

**浏览器版本: chrome108**
**使用框架: React**

### 复现步骤
从A页面跳转到B页面，B页面的componentDidMount生命周期中打一个alert，会发现跳转前先执行alert，再页面跳转切换。
这会造成一个问题。如果B页面的componentDidMount中，调用接口加载等操作多的话，js线程会先被他们阻塞住，让页面跳转延迟

### 期望结果
先跳转路由，再执行didmount

### 实际结果
先执行了didmount，再跳转路由

### 环境信息
```
  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v11.15.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    npmPackages:
      @tarojs/components: 3.5.11 => 3.5.11
      @tarojs/mini-runner: 3.5.11 => 3.5.11
      @tarojs/react: 3.5.11 => 3.5.11
      @tarojs/runtime: 3.5.11 => 3.5.11
      @tarojs/taro: 3.5.11 => 3.5.11
      @tarojs/webpack-runner: 3.5.11 => 3.5.11
      babel-preset-taro: ~3.5.11 => 3.5.11
      eslint-config-taro: ~3.5.11 => 3.5.11
      react: ^16.10.0 => 16.14.0
      taro-ui: 3.1.0-beta.4 => 3.1.0-beta.4
    npmGlobalPackages:
      typescript: 4.7.4
```

**Comment by ZakaryCode** [comment]
> ### 期望结果
> 先跳转路由，再执行didmount
> 
> ### 实际结果
> 先执行了didmount，再跳转路由

实际并不会在跳转前自行，该状态仅说明页面显示被阻塞了。可以自行在示例项目中测试，当弹窗挑出阻塞进程时路由已经变更，同时页面 render 已经执行（对应节点已经加载）。

> 这会造成一个问题。如果B页面的componentDidMount中，调用接口加载等操作多的话，js线程会先被他们阻塞住，让页面跳转延迟

taro 并不会对 didmount 做额外的操作，但在 react 中如果 componentDidMount 事件未执行完毕渲染进程将会受阻，这并非 bug 而是开发者需要写代码时需要认真考虑的。
