### ISSUE TITLE
轮播图从最后一张无缝衔接滑动到第一张会出现黑图不显示图片

### ISSUE THREAD

**Issue by Lccitem** [NervJS/taro#13072]
### 相关平台
H5

**浏览器版本: Chrome108.0.5359.125**
**使用框架: React**

### 复现步骤
轮播图从最后一张无缝衔接滑动到第一张会出现黑图不显示图片

### 期望结果
轮播图从最后一张无缝衔接滑动到第一张正常显示图片

### 实际结果
轮播图从最后一张无缝衔接滑动到第一张显示不正常

### 环境信息
```
👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.0 - D:\tools\nvm\nodejs\node.EXE
      Yarn: 1.22.19 - D:\tools\nvm\nodejs\node_global\yarn.CMD
      npm: 8.15.0 - D:\tools\nvm\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
未从描述中复现黑图问题，不过 circular 模式下首尾补帧存在重复元素问题，由 stencil 元素的 cloneNode 方法导致，将在下一版本修复

**Comment by Lccitem** [comment]
应该就是这个问题导致，感谢大佬尽快更新！
