### ISSUE TITLE
组件的 componentDidShow 会在 1.2.0 里吗？

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro#1307]
请问组件的 componentDidShow 是在 taro 1.2.0 里才有吗？
我现在在 1.1.9 里写了没有调用到。

那 1.2.0 大概什么时候 release 呢？

**Comment by luckyadam** [comment]
可以先用 beta 版本咯

**Comment by jswxwxf** [comment]
哈，习惯性的不敢在生产环境上用 beta 版。

**Comment by jswxwxf** [comment]
那来得及。

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/4bb99cd7c33373ac3fa162b96c8ec44809ac9d41
