### ISSUE TITLE
Taro v1.2.0-beta.5 下使用第三方包问题

### ISSUE THREAD

**Issue by jiangzhuorong** [NervJS/taro#1308]
问题描述：
     在Taro v1.2.0-beta.5下，使用第三方包dva-core时，编译报错，微信小程序工具出现如下报错：

thirdScriptError 
 sdk uncaught third Error 
 module "npm/_babel/runtime/helpers/interopRequireWildcard.js" is not defined 
 Error: module "npm/_babel/runtime/helpers/interopRequireWildcard.js" is not defined
    at require (http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716408)
    at http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:36817/appservice/npm/dva-core/lib/index.js:3:31
    at require (http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716549)
    at http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:36817/appservice/npm/dva-core/index.js:1:460
    at require (http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716549)
    at http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:36817/appservice/dva.js:7:14
    at require (http://127.0.0.1:36817/appservice/__dev__/WAService.js:1:716549)
console.error @ VM962:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1543548197362:1189
window.onerror @ VM962:1
scriptLoaded @ appservice?t=1543548197362:1255

**Comment by luckyadam** [comment]
升级到 1.2.0-beta.6
