### ISSUE TITLE
可以用taro打成RN-app里面的小程序吗？

### ISSUE THREAD

**Issue by heyden-suimu** [NervJS/taro#13084]
### 这个特性解决了什么问题？
一码多端问题，解决了RN-app里面的小程序开发效率问题

### 这个 API 长什么样？
支持

**Comment by zhiqingchen** [comment]
打包成 RN bundle 加载是是可以的，打包成小程序是不可以的

**Comment by heyden-suimu** [comment]
> 打包成 RN bundle 加载是是可以的，打包成小程序是不可以的

感谢回应，如果已经有RN项目了，要利用taro集成一些业务模块，比如订单模块这种的，用bundle的形式也ok吗？

**Comment by zhiqingchen** [comment]
这个是业务逻辑，自行探索
