### ISSUE TITLE
模块“"vue"”没有导出的成员“reactive”

### ISSUE THREAD

**Issue by Locter9001** [NervJS/taro#13081]
### 相关平台
微信小程序

**小程序基础库: 2.29.1**
**使用框架: Vue 3**

### 复现步骤
taro init myapp

然后选vue3 ts yarn gitee

### 期望结果
使用的vue版本一致

### 实际结果
warning "@nutui/nutui-taro > vue-router@4.1.6" has unmet peer dependency "vue@^3.2.0".
warning " > @tarojs/plugin-framework-vue3@3.5.6" has unmet peer dependency "vue@^3.0.0".

### 环境信息
```
 Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - f:\SDK_ALL\Yarn\bin\yarn.CMD
      npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
没想到居然烂到这种程度了

**Comment by Locter9001** [comment]
![image](https://user-images.githubusercontent.com/96331179/210552007-b61412ce-d769-42d2-ba93-ce740963ee5a.png)

**Comment by maoxiaoquan** [comment]
![image](https://user-images.githubusercontent.com/15361672/210764139-8325845e-aa04-4456-b87c-e72ea185f1a2.png)
同样问题，也是用的gitee的模版

**Comment by TaksonyL** [comment]
> ![image](https://user-images.githubusercontent.com/15361672/210764139-8325845e-aa04-4456-b87c-e72ea185f1a2.png) 同样问题，也是用的gitee的模版

试试删除 
src/types/global.d.ts
的这些代码
![f80e34d70c3e05bfe64d648a22297bb](https://user-images.githubusercontent.com/53998893/210772370-01b8854a-40fb-4c8b-ba37-939c89429a17.png)
