### ISSUE TITLE
page/index/index.config.tsx编译h5失败

### ISSUE THREAD

**Issue by jamestack** [NervJS/taro#13082]
### 相关平台
H5

**使用框架: React**

### 复现步骤
1. "taro init xxxx"选择 react-native项目模板

2. 把page/index/index.config.ts重命名为page/index/index.config.tsx

3. 执行”npm run dev:rn“成功运行，且无报错。

4. 执行“npm run dev:h5”编译失败，浏览器127.0.0.1:10086页面报错如下：
Syntax error: Unexpected token, expected "," (10:34)
src/app.boot.js

5. 执行"npm run build:h5"编译失败，报错如下:
ModuleBuildError: Module build failed (from @tarojs/taro-loader/lib/h5):
SyntaxError: Unexpected token, expected "," (10:34)

### 期望结果
希望jsx后缀的页面配置文件正常编译到h5

### 实际结果
rn一切正常，h5编译失败

### 附加描述
我有个需求是需要改react navigation自定义属性，给rn导航栏加一个收藏按钮，这就涉及到必须使用tsx的页面配置才可行，然后就发现h5下会编译失败，并且index.config.ts与index.config.rn.tsx不能共存，h5也会报错。

### 环境信息
```
  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.3.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.2.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.11 => 3.5.11 
      @tarojs/components: 3.5.11 => 3.5.11 
      @tarojs/helper: 3.5.11 => 3.5.11 
      @tarojs/plugin-framework-react: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-alipay: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-jd: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-qq: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-swan: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-tt: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-weapp: 3.5.11 => 3.5.11 
      @tarojs/react: 3.5.11 => 3.5.11 
      @tarojs/rn-runner: 3.5.11 => 3.5.11 
      @tarojs/router: 3.5.11 => 3.5.11 
      @tarojs/runtime: 3.5.11 => 3.5.11 
      @tarojs/shared: 3.5.11 => 3.5.11 
      @tarojs/taro: 3.5.11 => 3.5.11 
      @tarojs/taro-h5: 3.5.11 => 3.5.11 
      @tarojs/taro-rn: 3.5.11 => 3.5.11 
      @tarojs/webpack5-runner: 3.5.11 => 3.5.11 
      babel-preset-taro: 3.5.11 => 3.5.11 
      eslint-config-taro: 3.5.11 => 3.5.11 
      expo: ~46.0.1 => 46.0.19 
      react: ^18.0.0 => 18.2.0 
      react-native: ^0.69.3 => 0.69.7
```

**Comment by bobsam** [comment]
你文件名改成 index.config.ts 试试？

**Comment by jamestack** [comment]
page/index/index.config.tsx内容为：

import { Button } from "@tarojs/components"

let rn_config = {}

if(process.env.TARO_ENV === 'rn'){
  rn_config = {
    screenOptions: {
      title: "123",
      headerRight: () => (<Button>123</Button>)
    }
  }
}

export default definePageConfig({
  navigationBarTitleText: '首页',
  rn: rn_config
})

**Comment by ZakaryCode** [comment]
未能通过所述步骤复现相关问题，可进一步定位相关问题或提交 demo 辅助验证。（无更改后续将自动关闭该 Issue
