### ISSUE TITLE
如何让组件也能监听到 onReachBottom 事件？

### ISSUE THREAD

**Issue by jswxwxf** [NervJS/taro#1309]
请教个问题，如何让一个页面里的子组件也能接收到 onReachBottom 事件呢？以前在 wepy 的做法是我会在页面上 broadcast 一个事件，子组件处理这个事情，可是似乎在 taro/react 里没有这样的机制呢

**Comment by jswxwxf** [comment]
我现在就是在尝试这个，不过感觉不太好用…… 好吧，我再想想

**Comment by vimcaw** [comment]
也可以试试将滚动区用 `ScrollView` 包起来，然后用  `ScrollView` 的 `onScrollToLower` 事件判断是否滚动到底部，不过也有些弊端，比如必须设置高度，在滚动区不能下拉加载等等。

**Comment by jswxwxf** [comment]
算了，我直接用 refs 调用子组件的函数，就当给他们发了消息吧……
