### ISSUE TITLE
如何引用高德地图

### ISSUE THREAD

**Issue by laosandegudai** [NervJS/taro#13092]
### 这个特性解决了什么问题？
非腾讯地图的使用

### 这个 API 长什么样？
引用其它地图

**Comment by yoyo837** [comment]
微信小程序就不允许使用高德地图，高德地图的小程序里面也套的<map>，这东西在微信就是腾讯地图，高德地图官网有文档

**Comment by laosandegudai** [comment]
> 微信小程序就不允许使用高德地图，高德地图的小程序里面也套的`<map>`，这东西在微信就是腾讯地图，高德地图官网有文档

好像是这样，虽然在官方文档没找到，但是在高德地图里看到了
![image](https://user-images.githubusercontent.com/17979159/210774507-8aeb3c1c-db05-474b-a3fd-d43cb5efdb65.png)
