### ISSUE TITLE
Taro.env.VERSION在微信小程序上是undefined，在抖音小程序上是正常获取

### ISSUE THREAD

**Issue by joket1999** [NervJS/taro#13097]
### 这个特性解决了什么问题？
区分开发环境和生存环境

### 这个 API 长什么样？
Taro.env.VERSION 获取对应的环境，比如development、production等

**Comment by Chen-jj** [comment]
这是微信小程序 wx.env 的文档，Taro.env 只是返回其对应取值：

![image](https://user-images.githubusercontent.com/11807297/212880633-5dd34f1a-b01e-43a4-843d-2b006a73af65.png)

区分开发环境和生存环境请用 `process.env.NODE_ENV`
