### ISSUE TITLE
Taro转支付宝小程序 使用集成插件@tarojs/plugin-mini-ci 打包后自动上传提审预览，报ip不在白名单

### ISSUE THREAD

**Issue by pengyandong** [NervJS/taro#13098]
### 相关平台
支付宝小程序

**小程序基础库: 2.28.0**
**使用框架: React**

### 复现步骤
1：安装工具
npm install alipay-dev -g

2：运行 alipaydev key upload 自动打开浏览器配置页或直接前往 工具密钥设置 页面，配置工具公钥（第一步中生成的 公钥）以及设置 IP 白名单（可选），设置完成后系统会为您分配一个工具 

3：配置config目录下的index.js文件
// config/index.js

const CIPluginOpt = {
  // 支付宝小程序
  alipay: {
    appId: '支付宝小程序appid',
    toolId: '使用工具生成‘’,
    privateKeyPath: '私钥使用工具生成'
  },
  version: 1.1.1,
// ....其他代码
const config = {
  // 其他代码
  plugins:[['@tarojs/plugin-mini-ci', CIPluginOpt]'],
  }
}

4：执行 taro build --type alipay --preview 命令
:结果：报 ip不在白名单

### 期望结果
打包后可以正常预览，自动上传提审

### 实际结果
报ip不在白名单

### 环境信息
```
  Taro CLI 3.4.0 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.2 - /usr/local/bin/npm
    npmPackages:
    "@babel/runtime": "^7.7.7",
    "@reduxjs/toolkit": "^1.6.1",
    "@tarojs/components": "3.4.0",
    "@tarojs/react": "3.4.0",
    "@tarojs/runtime": "3.4.0",
    "@tarojs/taro": "3.4.0",
    "immer": "^9.0.6",
    "lottie-miniprogram": "^1.0.11",
    "mini-html-parser2": "^0.3.0",
    "minidev": "^1.7.0",
    "miniu": "^2.1.0-alpha.0",
    "moment": "^2.29.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-redux": "7.2.0",
    "redux": "4.0.0",
    "redux-logger": "^3.0.6",
    "taro-code": "^3.3.0"
    "@babel/runtime": "^7.7.7",
    "@reduxjs/toolkit": "^1.6.1",
    "@tarojs/components": "3.4.0",
    "@tarojs/react": "3.4.0",
    "@tarojs/runtime": "3.4.0",
    "@tarojs/taro": "3.4.0",
    "@yumc/uf-x23": "^0.1.5",
    "bignumber.js": "^9.0.1",
    "immer": "^9.0.6",
    "lottie-miniprogram": "^1.0.11",
    "mini-html-parser2": "^0.3.0",
    "minidev": "^1.7.0",
    "miniu": "^2.1.0-alpha.0",
    "moment": "^2.29.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-redux": "7.2.0",
    "redux": "4.0.0",
    "redux-logger": "^3.0.6",
    "taro-code": "^3.3.0"

```

**Comment by bigmeow** [comment]
安装  `@tarojs/plugin-mini-ci@3.6.0-beta.1` 这个版本，  文档：https://github.com/NervJS/taro/tree/feat/3.6/packages/taro-plugin-mini-ci

**Comment by pengyandong** [comment]
这个版本 报@tarojs\plugin-mini-ci\index.js获得的参数不符合要求，请检查！需要传的参数都传了@bigmeow

**Comment by bigmeow** [comment]
是的，参数变了 ，仔细一个个对一下我发你的链接的文档

**Comment by bigmeow** [comment]
@pengyandong 问题解决了吗 如果解决了说一下

**Comment by pengyandong** [comment]
参数已经对了，但是还是会报ip不在白名单中@bigmeow

**Comment by bigmeow** [comment]
这看起来是你白名单没设置正确？
你可以去后台先把白名单关了

**Comment by pengyandong** [comment]
白名单关了之后 是可以上传的@bigmeow

**Comment by bigmeow** [comment]
若设置了，得是CI服务对应的外网ip， 本地上传的要把公司的外网ip写上去，但是一般公司的外网ip每隔几天就会变，除非买了固定ip
