### ISSUE TITLE
ESLint: 暂不支持无状态组件（stateless component） (taro/no-stateless-component)

### ISSUE THREAD

**Issue by bernkastle** [NervJS/taro#131]
![image](https://user-images.githubusercontent.com/11273397/41478809-9e9cddcc-70fb-11e8-9f51-37e02faea91d.png)

这个问题好像不影响程序运行，所以影响不大。这个提示后面是否会修复？
谢谢开发组！！

**Comment by yuche** [comment]
感谢提醒，这是一个 bug。

https://github.com/NervJS/taro/commit/6f3c2f186d9d7142faf78c8bcd26592956701964 修复了这个问题并增加了测试用例。
