### ISSUE TITLE
建立一个Taro组件库的最佳实践？

### ISSUE THREAD

**Issue by zzefff** [NervJS/taro#13103]
### 这个特性解决了什么问题？
建立一个基于 Taro 开发组件库，打包产物可用于 Taro 项目和原生微信小程序项目

### 这个 API 长什么样？
1、基于 Taro 现有的全部特性来编写组件源码；
2、能够打包成：
（1）可以被 Taro 项目直接使用的包
（2）可以被原生微信小程序项目引入使用并正确构建到 miniprogram_npm 里的包；
3、能自带 Lerna 最好了;

希望有一个能满足这样需求的 cli 模板，通过 taro init 可以快速新建一个这样的组件库项目

**Comment by AdvancedCat** [comment]
仓库 [taro-project-templates](https://github.com/NervJS/taro-project-templates/tree/v3.5) 是你实现想法的绝佳之地。

可以建个 issue ，自产自销，欢迎PR

**Comment by zuolung** [comment]
试试[vantui](https://github.com/AntmJS/vantui)
