### ISSUE TITLE
【Taro v3.5.8】报错：t is not a function. (In 't(n[r])', 't' is undefined)_._recoverableErrors_._没有对 onRecoverableError 做校验就直接调用

### ISSUE THREAD

**Issue by qiuxiyu** [NervJS/taro#13109]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/qiuxiyu/taro_issue_demo.git](https://github.com/qiuxiyu/没有复现代码.git)
**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
线上运行时报错。

错误线程:
```
MiniProgramError
t is not a function. (In 't(n[r])', 't' is undefined)
TypeError: t is not a function. (In 't(n[r])', 't' is undefined)
……
```

源码解析详细截图：
https://pages.c-ctrip.com/union/issue/taro_issue20230109.png

我们根据错误信息排查下来，发现了报错的原因：
在react-reconciler.js中有一段逻辑，出现recoverableErrors时，直接调用了 onRecoverableError ，但没有对方法做校验。
P.S. 没有设置默认onRecoverableError方法，也没有设置传递该方法的方式。

### 期望结果
修复错误：
1. 设置默认onRecoverableError方法
2. 设置传递该方法的方式
3. 传入onRecoverableError 捕获真实的错误后，再看一下具体为什么会调用这个方法

### 实际结果
线上报错

### 环境信息
```
👽 Taro v3.5.8


  Taro CLI 3.5.8 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
```

**Comment by qiuxiyu** [comment]
@Chen-jj 咱们这边能否开个口子，允许自定义 onRecoverableError 方法？我们这边希望能够捕获到具体的错误信息

**Comment by longge0516** [comment]
@Chen-jj 这个自定义onRecoverableError 在3.5.12中有么？现在还是需要一个钩子来捕获这个具体的错误
