### ISSUE TITLE
有个小程序的项目，如何配置能让微信小程序和企微小程序都支持?

### ISSUE THREAD

**Issue by Lawguancong** [NervJS/taro#13107]
### 这个特性解决了什么问题？
有个支持企微小程序的项目，如何修改配置能让微信小程序和企微小程序都支持，且不影响原来的企微小程序, 不影响Taro.qy.login接口
版本信息：
"@tarojs/components": "3.4.0",
"@tarojs/plugin-framework-react": "^3.4.0",
"@tarojs/plugin-platform-weapp-qy": "0.0.7",
在config配置了 plugins: ['@tarojs/plugin-platform-weapp-qy']（这里需要怎么改配置呢？）

### 这个 API 长什么样？
有个支持企微小程序的，如何修改配置能让微信小程序和企微小程序都支持，且不影响原来的企微小程序

**Comment by bigmeow** [comment]
https://github.com/NervJS/taro/issues/13113
