### ISSUE TITLE
微信小程序页面回退，componentWillUnmount钩子获取页面栈不包含当前页面

### ISSUE THREAD

**Issue by jeffreyzhang23** [NervJS/taro#13101]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/jeffreyzhang23/taro3-componentWillUnmount-issue.git](https://github.com/jeffreyzhang23/taro3-componentWillUnmount-issue.git)
**小程序基础库: 2.19.1**
**使用框架: React**

### 复现步骤
taro3.5.6版本，初始化项目，注册两个页面，A跳转到b，b里面点击左上角进行back，componentWillUnmount钩子里，打印：console.log('Taro.getCurrentPages()', Taro.getCurrentPages())，发现只有前一个页面a了

### 期望结果
期望页面栈应该有a、b两个页面

### 实际结果
页面栈只有前一个页面，a页面

### 环境信息
```
Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/mini-runner: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/webpack-runner: 3.5.6 => 3.5.6 
      @tarojs/with-weapp: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
用withApp，b页面的onUnload会执行两次，第一次是两个页面（正确结果），第二次是一个页面

**Comment by AdvancedCat** [comment]
左上角 Back 按钮 与 `getCurrentPages` 是微信小程序提供的能力，而`componentWillUnmount `是React的生命周期函数。

当你点击 Back 的时候，微信小程序内部已经把 b 页面给干掉了。 `componentWillUnmount` 是 React 的收尾工作，内部再调用 `getCurrentPages` 就拿不到 b 页面的实例了。

**Comment by jeffreyzhang23** [comment]
> 

但是前面版本，如taro3.0.x版本是表现是符合预期的的，我理解willUnmout，不应该把当前页面实例干掉

**Comment by jeffreyzhang23** [comment]
> 

意思是用taro3，有销毁前获取当前页面栈场景时，还得用with-weapp？
啥都没干，但是3.0.x版本为啥表现符合预期的

**Comment by AdvancedCat** [comment]
> > 
> 
> 意思是用taro3，有销毁前获取当前页面栈场景时，还得用with-weapp？ 啥都没干，但是3.0.x版本为啥表现符合预期的

如果有销毁前获取当前页面栈场景时，直接在 onUnload 函数中调用；详见[文档说明](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/route.html)

componentWillUnmount 是在 onUnload 之后调用的，而且是 React 调度的，因此不会保证页面栈的正确性

可以提供一下你基于 3.0 版本可复现的demo

**Comment by jeffreyzhang23** [comment]
> 

还是这个代码库，分支：feature/v3-ok，taro 3.0.29版本，符合预期。

**Comment by AdvancedCat** [comment]
这是因为 `react-reconciler` 在不同版本中使用了不同的调度策略：

react-reconciler@v0.23 (used in Taro@v3.0.x)
![image](https://user-images.githubusercontent.com/7858761/212635350-2af15f17-1358-4e73-8f6c-4c581133e283.png)

react-reconciler@v0.27 (used in Taro@v3.5.x)
![image](https://user-images.githubusercontent.com/7858761/212635471-7f8e0734-8992-40a6-8b71-103d8fa3e1a7.png)

在 v0.27 版本中，componentWillUnmount 是在异步回调中触发，导致此时读取 Taro.getCurrentPages 仅一个页面。

如果仍需要读取正确页面栈，可以使用 onUnload 生命周期，它保证与小程序的onUnload 生命周期是同一时刻触发。

**Comment by jeffreyzhang23** [comment]
> 这是因为 `react-reconciler` 在不同版本中使用了不同的调度策略：
> 
> react-reconciler@v0.23 (used in [Taro@v3.0.x](mailto:Taro@v3.0.x)) ![image](https://user-images.githubusercontent.com/7858761/212635350-2af15f17-1358-4e73-8f6c-4c581133e283.png)
> 
> react-reconciler@v0.27 (used in [Taro@v3.5.x](mailto:Taro@v3.5.x)) ![image](https://user-images.githubusercontent.com/7858761/212635471-7f8e0734-8992-40a6-8b71-103d8fa3e1a7.png)
> 
> 在 v0.27 版本中，componentWillUnmount 是在异步回调中触发，导致此时读取 Taro.getCurrentPages 仅一个页面。
> 
> 如果仍需要读取正确页面栈，可以使用 onUnload 生命周期，它保证与小程序的onUnload 生命周期是同一时刻触发。

了解了，感谢
