### ISSUE TITLE
创建项目失败:  ReferenceError: notToChangeExt is not defined

### ISSUE THREAD

**Issue by winnshier** [NervJS/taro#13102]
### 相关平台
微信小程序

**小程序基础库: 2.29.1**
**使用框架: React**

### 复现步骤
Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Gitee（最快）
✔ 拉取远程模板仓库成功！
创建项目失败:  ReferenceError: notToChangeExt is not defined

### 期望结果
创建项目

### 实际结果
拉取模版成功但是创建项目失败

### 环境信息
```
  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
```

---
### 补充信息
使用的是  Taro CLI 3.5.11 构建项目，运行 taro init myApp, 选择完模版后提示 拉取远程模板仓库成功，后续报错 创建项目失败:  ReferenceError: notToChangeExt is not defined 尝试切换node版本到 v15.14.0 构建项目，还是同样的报错

**Comment by adufeng** [comment]
应该是gitee的模板源出问题了，选择模板的时候换其他的，比如内置的cli模板，就能正常创建了

**Comment by GarlicGo** [comment]
我也遇到了这个问题，gitee和github模板都是这样

**Comment by Skycweb** [comment]
我也遇到到了.版本Taro CLI 3.5.11

**Comment by chengluliu** [comment]
npx 也是出现这个问题

**Comment by XIAIBIANCHENG** [comment]
我也遇到到了.版本Taro CLI 3.5.11，Gitee和github 都显示ReferenceError: notToChangeExt is not defined

**Comment by ghalip603** [comment]
也是遇到了同样的问题， 前两天还好好的， 昨天早上开始 ，一直报错。  怎么创建都一样是ReferenceError: notToChangeExt is not defined

**Comment by ANDYGE** [comment]
看到NUTUI示例中用的是taroj 3.5.4 版本，切换回去，运行仍然报这个错，感觉应该是模板源的问题，应该是github的模板有变动造成的。

**Comment by GarlicGo** [comment]
> 我也在macOS 13上使用Taro CLI 3.5.11遇到了这个问题，gitee和github模板都是这样

我一开始是使用 GitHub 模板出现这个问题，当时 Gitee 模板还正常，但是很快 Gitee 模板也这样了。

**Comment by huoher** [comment]
遇到同样问题

**Comment by happy-func** [comment]
+1

**Comment by AdvancedCat** [comment]
已修复，请选择 github 拉取模板

fixed by https://github.com/NervJS/taro-project-templates/pull/88 感谢 @functionwell
