### ISSUE TITLE
Map组件在飞书小程序，无法显示

### ISSUE THREAD

**Issue by lzy383408003** [NervJS/taro#13104]
### 相关平台
飞书小程序

**使用框架: React**

### 复现步骤
      <Map
        ref={MapRef}
        id='Point'
        latitude={lat}
        longitude={lng}
        markers={markers}
        onMarkerTap={onMarkerTap}
        style={{ width: '100vw', height: '100vh' }}
        className={styles.map}
      />

### 期望结果
正常渲染地图

### 实际结果
地图组件已经渲染，但是样式全部被覆盖 导致无法显示

### 环境信息
```
👽 Taro v3.4.8


  Taro CLI 3.4.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
3.4.8版本

**Comment by Chen-jj** [comment]
@lzy383408003 真机环境可以显示吗，我用原生写法在开发者工具好像也是没显示出来
