### ISSUE TITLE
新增微信小程序预览二维码的配置入口

### ISSUE THREAD

**Issue by lovelyqun** [NervJS/taro#13110]
### 这个特性解决了什么问题？
我们需要将二维码保存下来,并展示到网页中

### 这个 API 长什么样？
按照微信小程序官方的配置信息即可,新增qrcodeFormat,qrcodeOutputDest配置选项
const CIPluginOpt = {
  // 微信小程序
  weapp: {
    appid: appid,
    privateKeyPath: 'key/private.appid.key',
    qrcodeFormat: 'image', //返回二维码文件的格式 "image" 或 "base64"， 默认值 "terminal" 供调试用
    qrcodeOutputDest: '/path/to/qrcode/file/destination.jpg', //二维码文件保存路径
  },
  // 版本号
  version: '1.0.0',
  // 版本发布描述
  desc: '版本描述',
}

**Comment by AdvancedCat** [comment]
@bigmeow 大喵给看看，能够满足咯？

**Comment by bigmeow** [comment]
@lovelyqun  3.6 分支的更改能满足需求了，构建后会返回 二维码 的路径
![image](https://user-images.githubusercontent.com/10484248/211471584-3fc5aad8-ae28-4639-ac2a-0df2348ddcb0.png)

你可以单独安装 `@tarojs/plugin-mini-ci@3.6.0-beta.1`
文档： https://github.com/NervJS/taro/tree/feat/3.6/packages/taro-plugin-mini-ci

**Comment by lovelyqun** [comment]
感谢解答,已升级版本
这个思路确实有点绕,我暂时把源码的配置修改了.
请问这个版本不需要构建,单独上传的指令是什么?

**Comment by lovelyqun** [comment]
已找到指令,可以关闭了
