### ISSUE TITLE
恳请官方回答下。如何将一个Taro小程序能够同时在微信和企业微信上运行上？

### ISSUE THREAD

**Issue by Lawguancong** [NervJS/taro#13113]
### 如何将一个Taro小程序能够同时在微信和企业微信上运行上？
如题
### 遇到的问题
1. 想着能在微信模式下运行，于是改成weapp， cross-env MINI_PROGRAM_ENV=test taro build --type weapp， 结果在企微开发模式下，Taro.qy.login返回为undefiend？期望，能在weapp下能运行企微代码。
2. 目前遇到的问题，在只能配置weapp或者qywx，且只能在一个环境中运行
3. 如何配置，使得项目能同时能在微信和企微中运行小程序呢？
4.

**Comment by bigmeow** [comment]
在文档中全文搜索“企业微信”可看到这个插件： https://docs.taro.zone/docs/GETTING-STARTED#%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F
Taro.qy.login 只有安装这个插件才能用

**Comment by Lawguancong** [comment]
> 在文档中全文搜索“企业微信”可看到这个插件： https://docs.taro.zone/docs/GETTING-STARTED#%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F Taro.qy.login 只有安装这个插件才能用
你好，已经安装了这个插件 @tarojs/plugin-platform-weapp-qy，但是本地开发和打包回出问题。
这2个该怎么配置呢？
build --type weapp，用这个的话，Taro.qy.login返回undefined
build --type qywx，用这个的话，在微信开发工具只能是企微小程序模式，微信小程序模式跑不了

**Comment by bigmeow** [comment]
代码中你要做判断:
```
if (process.env.TARO_ENV === "weapp") {
     Taro.login
} else if (process.env.TARO_ENV === "qywx") {
     Taro.qy.login
}
```

**Comment by Lawguancong** [comment]
> 还是要用两个构建命令分别构建，但是代码中你要做判断:
> 
> ```
> if (process.env.TARO_ENV === "weapp") {
>      Taro.login
> } else if (process.env.TARO_ENV === "qywx") {
>      Taro.qy.login
> }
> ```
好的 感谢大佬。
这样的话，就得弄2个小程序了是吧，一个微信小程序，一个企微小程序（仅在企微运行）。

**Comment by Lawguancong** [comment]
> TARO_ENV

**Comment by Lawguancong** [comment]
> 还是要用两个构建命令分别构建，但是代码中你要做判断:
> 
> ```
> if (process.env.TARO_ENV === "weapp") {
>      Taro.login
> } else if (process.env.TARO_ENV === "qywx") {
>      Taro.qy.login
> }
> ```

一套代码是可以通过不同构建方式进行打包，但不能在同一小程序同时运行微信和企微小程序吧？
![image](https://user-images.githubusercontent.com/22849450/211481882-8cfc1007-45f6-42e6-a528-5c5b3ee9d881.png)

**Comment by bigmeow** [comment]
明白你所处的场景需求了，还是建议用2个小程序，是在一个也不是不行

你打包的时候还是打包企业微信，判断改一下
不用Taro.qy 来判断，还是用 wx.qy来判断
const isQYEX = !! wx.qy； // 把它存全局store里
if (isQYEX {
  // 企业微信
} else {
 // 微信
}

**Comment by Lawguancong** [comment]
> 明白你所处的场景需求了，还是建议用2个小程序，是在一个也不是不行
> 
> 你打包的时候还是打包企业微信，判断改一下 不用Taro.qy 来判断，还是用 wx.qy来判断 const isQYEX = !! wx.qy； // 把它存全局store里 if (isQYEX) { // 企业微信 } else { // 微信 }

感谢建议
