### ISSUE TITLE
支付宝小程序基础库升级到最新版2.8.3之后，代码中的Radio组件的 onChange 或者 onClick 事件点击无效

### ISSUE THREAD

**Issue by zlh562011966** [NervJS/taro#13128]
### 相关平台
支付宝小程序

**小程序基础库: 支付宝小程序基础库2.8.3**
**使用框架: React**

### 复现步骤
import Taro, { Component} from '@tarojs/taro'
import {View, Radio, RadioGroup} from '@tarojs/components'
import './index.less'

export default class Index extends Component {
_handleChangeAgreement（） {
    console.log('点击事件无效');
}

  render () {
    const { agreementChecked } = this.props;

    return (
      <View className='create-agreement'>
            <RadioGroup onClick={this._handleChangeAgreement.bind(this)}>
              <Label className='create-agreement__radio'>
                <Radio color='#EF8200' checked={agreementChecked} />
              </Label>
            </RadioGroup>
            <Text className="create-agreement__agree">我已阅读并同意</Text>
          </View>
    )
  }
}

### 期望结果
Taro框架的Radio 或者 RadioGroup 组件在支付宝小程序最新版基础库2.8.3版本下的点击事件可以使用。

### 实际结果
Taro框架的Radio 或者 RadioGroup 组件在支付宝小程序最新版基础库2.8.3版本下的点击事件无效。
使用支付宝原生组件，在支付宝小程序最新版基础库2.8.3版本下的点击事件正常。
将支付宝的基础库降级至2.0以下，点击事件也正常。

### 环境信息
```
支付宝开发者工具：v3.3稳定版
支付宝基础库：2.8.3
Taro CLI 3.2.9 environment info:
System:
OS: Windows 10
Binaries:
Node: 16.13.1 - D:\Program Files\nodejs\node.EXE
Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.14.11 - D:\Program Files\nodejs\npm.CMD
```

**Comment by AdvancedCat** [comment]
尝试使用 Taro@v3.5.x 版本试试看，如果仍有问题，请回复

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/213363062-7810ba91-3283-432f-a43b-a4b7775e4ef4.png)
是`onChange` 不是 `onClick` 事件吧，原生组件也没有 `onClick` 事件
