### ISSUE TITLE
[weapp] 增加 scroll-view 组件在 Skyline 渲染引擎中的新特性

### ISSUE THREAD

**Issue by AdvancedCat** [NervJS/taro#13136]
### 这个特性解决了什么问题？
`scroll-view` 新增 `type=custom` 自定义模式，带来了若干个新的组件；
同时 `scroll-view` 组件也新增了若干个新属性以适应新特性；

`scroll-view` 组件：https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html
宣传文章：https://mp.weixin.qq.com/s/OJEWZlPQGUOutidC5HVk7g

### 这个 API 长什么样？
Taro 对 `scroll-view` 组件新特性的支持

**Comment by AdvancedCat** [comment]
需要适配的内容较多，可以考虑拆分多个 PR

**Comment by youmengme** [comment]
期待中...

**Comment by xiang12383** [comment]
这个提议好，什么时候能实现？

**Comment by AdvancedCat** [comment]
> 这个提议好，什么时候能实现？

正在做了，工作上的事有些耽搁了
