### ISSUE TITLE
taro3 vue3 引用原生mp-html组件时报错

### ISSUE THREAD

**Issue by HuangYaobin** [NervJS/taro#13146]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/HuangYaobin/taro-mphtml-demo.git](https://github.com/HuangYaobin/taro-mphtml-demo.git)
**小程序基础库: 2.29.1**
**使用框架: Vue 3**

### 复现步骤
启动项目即可

### 期望结果
渲染文本123

### 实际结果
![](https://user-images.githubusercontent.com/51368773/205229071-d03092f1-fdad-45b7-8e71-563ad37883e1.png)

### 环境信息
```
  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1
      Yarn: 1.22.19
      npm: 6.14.16 
```

**Comment by xuanzebin** [comment]
taro 模拟的 dom 元素在 vue3 环境中会实现并占用了 content 属性名，因此属性应该避免使用 content 作为属性名：
```vue
<script lang="ts" setup>
const content = `<div>123</div>`
</script>
<template>
  <view class="index">
    <mp-html :contentValue="content"></mp-html>
  </view>
</template>
```

并且调整 `src/components/mp-html/index.js` 中对应的 content 属性名，即可正常跑通。
