### ISSUE TITLE
onScrollToLower没到底部就开始加载。无限加载

### ISSUE THREAD

**Issue by chuanzhang2018** [NervJS/taro#1314]
**问题描述**
使用ScrollView 加onScrollToLower方法。onScrollToLower方法无限调用，在RN上

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
const { list } = this.props.productsClothingStore
    const productsList = list.map((item,index) => {
      return (
        <View key={index} className={'item'} style={{width:'50%',alignItems:'center'}} >
          <Image
          className={'product-image'}
          src={item.catalogue_photos["0"].medium_url}
          style={{width:120,height:240}}
          />
          <Text>{item.title}</Text>
        </View>
      )
    }) 
    return (
      <View style={{flex:1}} >
        <ScrollView className='index' scrollY  upperThreshold='20'  lowerThreshold='1' onScrollToLower={this._onScrollToLower} onScrollToUpper={this._onScrollToUpper}    style={{flex:1,flexWrap:'wrap',flexDirection:'row'}} >
          {productsList}
        </ScrollView>
      </View>
```
*期望行为**
滑动到底部或者我设置的高度才走onScrollToLower方法

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统:osx 10.14.1 
 - Taro 版本 1.2.0-beta.1
 - Node.js 版本v10.1.0
 - 报错平台 react native

**补充信息**
[可选]
在微信小程序上  还不会加载。上拉加载 下拉刷新都没走

**Comment by chuanzhang2018** [comment]
> 欢迎提交 Issue~
> 
> 如果你提交的是 bug 报告，请务必遵循 [Issue 模板](https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)的规范，尽量用简洁的语言描述你的问题，最好能提供一个稳定简单的复现。🙏🙏🙏
> 
> 如果你的信息提供过于模糊或不足，或者已经其他 issue 已经存在相关内容，你的 issue 有可能会被关闭。
> 
> Good luck and happy coding~

改了

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/49349164-51ca7800-f6e4-11e8-8c88-7ac67a0529ed.png)
这里你没填

**Comment by Manjiz** [comment]
ScrollView 默认有 50 的提前值，距离底部小于 50 就触发事件
