### ISSUE TITLE
文档链接404 bug

### ISSUE THREAD

**Issue by SetoKaiba** [NervJS/taro#13143]
### 相关平台
微信小程序

**小程序基础库: 无**
**使用框架: React**

### 复现步骤
1. 从官网点击文档
2. 点击基础教程——React

### 期望结果
进入正确的文档网址

### 实际结果
进入了错误的文档网址

### 环境信息
```
👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
这个问题不属于任何一个小程序，我用最正常的方式来提交了issue，被自动关闭了，至少弄个其他分类吧？明明不属于任何一个平台。重新提交一次，只能随便选了个微信小程序平台了。我是真的服了，这环境信息不填还不行，其实我就提交个文档bug而已，这其实很影响新手的体验的，点进去一个链接就是404。

![image](https://user-images.githubusercontent.com/159540/212475889-d6a08cb7-b274-4e3e-aa56-133db323001b.png)

从taro官网进去的文档链接是
1) https://taro-docs.jd.com
自动跳转到
2) https://taro-docs.jd.com/docs

手动输入这个链接，也可以跳到文档
3) https://docs.taro.zone
自动跳转到
4) https://docs.taro.zone/docs

此时的1234的基础教程的链接均指向根目录
https://taro-docs.jd.com/react-overall
https://docs.taro.zone/react-overall

手动输入2，基础教程的链接仍然指向根目录
https://taro-docs.jd.com/react-overall

手动输入4，基础教程的链接指向正确的子目录
![image](https://user-images.githubusercontent.com/159540/212475927-6bf3b016-34a3-4dbf-8837-6302c8be5b0f.png)
https://docs.taro.zone/docs/react-overall
但是左键点击的时候，还是跳转到根目录
![image](https://user-images.githubusercontent.com/159540/212475940-1fb6800d-5535-424b-96e6-daf1287999bb.png)
https://docs.taro.zone/react-overall
中键点击，打开新tab的时候，跳转到正确的子目录
https://docs.taro.zone/docs/react-overall

**Comment by ztl8702** [comment]
蹭楼：

- [ ] https://nervjs.github.io/taro-docs/docs/CONTRIBUTING/codebase-overview 这个也404了

**Comment by ztl8702** [comment]
>
> 期望结果
> 进入正确的文档网址
>
> 实际结果
> 进入了错误的文档网址

这个真的笑死😆

**Comment by AdvancedCat** [comment]
可以移步 [taro-docs](https://github.com/NervJS/taro-docs) 提出issue，当然也欢迎提 PR 修复。

**Comment by SetoKaiba** [comment]
https://github.com/NervJS/taro-docs/issues/61

**Comment by Yuiai01** [comment]
https://taro-ext.jd.com/ 这个链接里面，点击上面的社区，你会发现...
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/112228030/212787229-9859403e-b455-4277-baaa-15a1550b0a49.png">

**Comment by AdvancedCat** [comment]
移步至 https://github.com/NervJS/taro-docs/issues/61 讨论
