### ISSUE TITLE
@tarojs/helper 存在幽灵依赖

### ISSUE THREAD

**Issue by ztl8702** [NervJS/taro#13144]
### 相关平台

和平台无关

### 复现步骤
https://github.com/NervJS/taro/blob/60d3f28dcb7e8fd711a6c99f9dda4cf3e190d312/packages/taro-helper/src/utils.ts#L497

而 https://github.com/NervJS/taro/blob/60d3f28dcb7e8fd711a6c99f9dda4cf3e190d312/packages/taro-helper/package.json 没有 `@babel/traverse`

### 期望结果
n/a

### 实际结果
n/a

### 环境信息
```

👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.11 => 3.5.11 
      @tarojs/components: 3.5.11 => 3.5.11 
      @tarojs/helper: 3.5.11 => 3.5.11 
      @tarojs/plugin-framework-react: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-weapp: 3.5.11 => 3.5.11 
      @tarojs/react: 3.5.11 => 3.5.11 
      @tarojs/router: 3.5.11 => 3.5.11 
      @tarojs/runtime: 3.5.11 => 3.5.11 
      @tarojs/shared: 3.5.11 => 3.5.11 
      @tarojs/taro: 3.5.11 => 3.5.11 
      @tarojs/taro-h5: 3.5.11 => 3.5.11 
      @tarojs/taro-loader: ^3.5.11 => 3.5.11 
      @tarojs/webpack5-runner: 3.5.11 => 3.5.11 
      babel-preset-taro: 3.5.11 => 3.5.11 
      eslint-config-taro: 3.5.11 => 3.5.11 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.4 
```

---
### 补充信息
上下文：https://github.com/NervJS/taro-project-templates/issues/92

**Comment by ztl8702** [comment]
此类 Issue 要怎么创建？https://taro-issue-pro.pf.jd.com 似乎不适合用来填。可否增加一个“依赖/代码质量问题”的分类？

**Comment by ztl8702** [comment]
另：不知道taro团队是否有计划**系统性**地清理官方packages里面的幽灵依赖问题？

**Comment by ztl8702** [comment]
This might help: https://github.com/pnpm/node-modules-check

**Comment by ztl8702** [comment]
之前：https://github.com/NervJS/taro/issues/12135

**Comment by AdvancedCat** [comment]
> 另：不知道taro团队是否有计划**系统性**地清理官方packages里面的幽灵依赖问题？

目前看应该所有模板在 `hoist=false` 模式下，都会有编译问题，这也确实暴露了依赖不全面的问题。需要专人专项去梳理跟进。

**Comment by Chen-jj** [comment]
> 另：不知道taro团队是否有计划**系统性**地清理官方packages里面的幽灵依赖问题？

@ztl8702 感谢指出，我们安排一下梳理计划
