### ISSUE TITLE
RN 打开微信客服 Taro.openCustomerServiceChat 后期是否会支持？

### ISSUE THREAD

**Issue by n1wd** [NervJS/taro#13140]
### 这个特性解决了什么问题？
RN端 打开微信客服 Taro.openCustomerServiceChat 后期是否会支持？

### 这个 API 长什么样？
Taro.openCustomerServiceChat({
  extInfo: {url: ''},
  corpId: '',
  success: function (res) { }
})

**Comment by zhiqingchen** [comment]
不会，这类接口平台关联性非常大，目前没有实现法案。

**Comment by n1wd** [comment]
了解，谢谢
