### ISSUE TITLE
webpack.cache.PackFileCacheStrategy

### ISSUE THREAD

**Issue by qklhk** [NervJS/taro#13156]
### 相关平台
微信小程序

**小程序基础库: 2.29.2**
**使用框架: React**

### 复现步骤
命令
"dev:weapp": "npm run build:weapp:dev -- --watch",
"build:weapp:dev": "taro build --type weapp --mode dev",

配置
  cache: {
    name: process.env.TARO_APP_ENV,
    enable: process.env.TARO_APP_ENV === 'development',
    buildDependencies: {
      config: [ __filename ]
    }
  },

### 期望结果
Taro 持久化缓存配置

### 实际结果
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (296kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (296kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (296kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (296kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (296kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (296kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (295kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (295kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (591kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (177kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)

### 环境信息
```
 Taro v3.5.11

启动  taro-plugin-environment：读取env环境变量  undefined
options {}

  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\node\node.EXE
      Yarn: 1.22.19 - D:\nodejs\node_global\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\node\npm.CMD
```

**Comment by we125182** [comment]
@qklhk 请问你是怎么解决的呢？

**Comment by 1250415649** [comment]
你好，请问解决了吗，我也遇到了同样的问题
