### ISSUE TITLE
taro H5 本地运行使用chrome devtools的 coverage功能

### ISSUE THREAD

**Issue by hellozqy** [NervJS/taro#13163]
### 这个特性解决了什么问题？
taro H5 本地运行使用chrome devtools的 coverage功能，当前为编译过后的代码即使有source map也无法正常连接过去，导致需要在数十万行代码中寻找哪些代码没有覆盖，我们希望有什么办法能够勉强解决这个问题，以便排查代码中各部分的执行时间和覆盖情况

### 这个 API 长什么样？
npm run dev:h5 --coverage

**Comment by ZakaryCode** [comment]
特性表述不清晰，可以新增示例辅助说明。

根据现有描述理解，应当是在使用编辑器开发调试工具，且同时使用 chrome 开发者工具 coverage 面板时，预期能够通过面板直接打开编辑器对应文件。该特性应当由 coverage 面板或通过对应调试工具提供，与 taro 无关（以 vscode 调试 chrome 为例，也不能在开发面板中通过映射直接跳转编辑器对应文件）。

在开发模式下，taro 所提供的文件命名也十分好理解，配合 chrome 开发工具现实的源文件和使用情况，手动排查并不会因为理解造成困难。
