### ISSUE TITLE
【Taro 3.5.12】字节小程序pay-button组件GetGoodsInfo、ApplyRefund等需要在函数里返回的数据包的方法报错

### ISSUE THREAD

**Issue by lanxuexing** [NervJS/taro#13166]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/lanxuexing/taro-demo.git](https://github.com/lanxuexing/taro-demo.git)
**小程序基础库: 2.78.0.4**
**使用框架: React**

### 复现步骤
1. 安装依赖：npm i
2. 运行项目：npm run dev:tt
3. 打开字节开发者工具【PS：必须是IDE 4.0.1之后的版本才开始支持IDE调试，最好是最新的4.0.3】，导入工程，查看运行结果和调试，查看控制台报错信息～

#### 一、使用【立即抢购】功能
可以正常唤起字节内置交易系统的提单页面

#### 二、使用【申请退款】功能
可以正常唤起字节内置交易系统的退款页面

#### 三、其他说明
PS：demo工程里，有自定义封装的可用的demo，写有注释，对比着看就行，Taro在Release 3.5.7之后说已经支持pay-button组件，但是实际使用中，无法使用，还请大佬们帮忙看看，谢谢🙏

#### 四、抖音开放平台相关文档
- [pay-button 交易按钮](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/industry/trading-system/pay-button)

#### 一、使用【立即抢购】功能，getGoodsInfo报错
```vim
tma-core.js:2 [TMA] USER_CUSTOM_ERROR: getGoodsInfo should be object, but got undefined
    at http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:413658
    at u (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:274784)
    at Generator._invoke (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:274537)
    at Generator.forEach.e.<computed> [as next] (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:275141)
    at $i (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:44052)
    at i (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:44258)
```

####  二、使用【申请退款】功能，ApplyRefund报错
```vim
tma-core.js:formatted:349 [TMA] USER_CUSTOM_ERROR: The return value of bind:applyrefund should be an object
    at http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:420855
    at u (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:274784)
    at Generator._invoke (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:274537)
    at Generator.forEach.e.<computed> [as next] (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:275141)
    at $i (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:44052)
    at i (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:44258)
```

### 环境信息
```vim
👽 Taro v3.5.12


  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.12 => 3.5.12 
      @tarojs/components: 3.5.12 => 3.5.12 
      @tarojs/helper: 3.5.12 => 3.5.12 
      @tarojs/mini-runner: ^3.5.12 => 3.5.12 
      @tarojs/plugin-framework-react: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-alipay: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-jd: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-qq: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-swan: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-tt: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12 
      @tarojs/react: 3.5.12 => 3.5.12 
      @tarojs/router: 3.5.12 => 3.5.12 
      @tarojs/runtime: 3.5.12 => 3.5.12 
      @tarojs/shared: 3.5.12 => 3.5.12 
      @tarojs/taro: 3.5.12 => 3.5.12 
      @tarojs/taro-h5: 3.5.12 => 3.5.12 
      @tarojs/webpack5-runner: 3.5.12 => 3.5.12 
      babel-preset-taro: 3.5.12 => 3.5.12 
      eslint-config-taro: 3.5.12 => 3.5.12 
      react: ^18.0.0 => 18.2.0 
```

**Comment by Chen-jj** [comment]
这两个事件比较特别，需要返回特定值给小程序进行处理。下个版本支持。

**Comment by pfsj-xk** [comment]
可以使用了？

**Comment by xxouu** [comment]
> ### 相关平台
> 字节跳动小程序
> 
> ### 复现仓库
> https://github.com/lanxuexing/taro-demo.git **小程序基础库: 2.78.0.4** **使用框架: React**
> 
> ### 复现步骤
> 1. 安装依赖：npm i
> 2. 运行项目：npm run dev:tt
> 3. 打开字节开发者工具【PS：必须是IDE 4.0.1之后的版本才开始支持IDE调试，最好是最新的4.0.3】，导入工程，查看运行结果和调试，查看控制台报错信息～
> 
> ### 期望结果
> #### 一、使用【立即抢购】功能
> 可以正常唤起字节内置交易系统的提单页面
> 
> #### 二、使用【申请退款】功能
> 可以正常唤起字节内置交易系统的退款页面
> 
> #### 三、其他说明
> PS：demo工程里，有自定义封装的可用的demo，写有注释，对比着看就行，Taro在Release 3.5.7之后说已经支持pay-button组件，但是实际使用中，无法使用，还请大佬们帮忙看看，谢谢🙏
> 
> #### 四、抖音开放平台相关文档
> * [pay-button 交易按钮](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/industry/trading-system/pay-button)
> 
> ### 实际结果
> #### 一、使用【立即抢购】功能，getGoodsInfo报错
> ```viml
> tma-core.js:2 [TMA] USER_CUSTOM_ERROR: getGoodsInfo should be object, but got undefined
>     at http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:413658
>     at u (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:274784)
>     at Generator._invoke (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:274537)
>     at Generator.forEach.e.<computed> [as next] (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:275141)
>     at $i (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:44052)
>     at i (http://127.0.0.1:7049/core/2.78.0.4/tma-core.js:2:44258)
> ```
> 
> #### 二、使用【申请退款】功能，ApplyRefund报错
> ```viml
> tma-core.js:formatted:349 [TMA] USER_CUSTOM_ERROR: The return value of bind:applyrefund should be an object
>     at http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:420855
>     at u (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:274784)
>     at Generator._invoke (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:274537)
>     at Generator.forEach.e.<computed> [as next] (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:275141)
>     at $i (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:44052)
>     at i (http://127.0.0.1:7046/core/2.78.0.4/tma-core.js:2:44258)
> ```
> 
> ### 环境信息
> ```viml
> 👽 Taro v3.5.12
> 
> 
>   Taro CLI 3.5.12 environment info:
>     System:
>       OS: macOS 12.6
>       Shell: 5.8.1 - /bin/zsh
>     Binaries:
>       Node: 14.18.0 - /usr/local/bin/node
>       Yarn: 1.22.19 - /usr/local/bin/yarn
>       npm: 6.14.15 - /usr/local/bin/npm
>     npmPackages:
>       @tarojs/cli: 3.5.12 => 3.5.12 
>       @tarojs/components: 3.5.12 => 3.5.12 
>       @tarojs/helper: 3.5.12 => 3.5.12 
>       @tarojs/mini-runner: ^3.5.12 => 3.5.12 
>       @tarojs/plugin-framework-react: 3.5.12 => 3.5.12 
>       @tarojs/plugin-platform-alipay: 3.5.12 => 3.5.12 
>       @tarojs/plugin-platform-jd: 3.5.12 => 3.5.12 
>       @tarojs/plugin-platform-qq: 3.5.12 => 3.5.12 
>       @tarojs/plugin-platform-swan: 3.5.12 => 3.5.12 
>       @tarojs/plugin-platform-tt: 3.5.12 => 3.5.12 
>       @tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12 
>       @tarojs/react: 3.5.12 => 3.5.12 
>       @tarojs/router: 3.5.12 => 3.5.12 
>       @tarojs/runtime: 3.5.12 => 3.5.12 
>       @tarojs/shared: 3.5.12 => 3.5.12 
>       @tarojs/taro: 3.5.12 => 3.5.12 
>       @tarojs/taro-h5: 3.5.12 => 3.5.12 
>       @tarojs/webpack5-runner: 3.5.12 => 3.5.12 
>       babel-preset-taro: 3.5.12 => 3.5.12 
>       eslint-config-taro: 3.5.12 => 3.5.12 
>       react: ^18.0.0 => 18.2.0 
> ```
请问你这个问题解决了吗。
我还是会报这个错，taro版本 3.6.2版本，"vue": "^3.2.31",。
TypeError: getGoodsInfo should be object, but got undefined

**Comment by xxouu** [comment]
请问你这个问题解决了吗。
我还是会报这个错，taro版本 3.6.2版本，"vue": "^3.2.31",。
TypeError: getGoodsInfo should be object, but got undefined

**Comment by lbb1811** [comment]
> 这两个事件比较特别，需要返回特定值给小程序进行处理。下个版本支持。

看样子“下个版本支持”，意思是 `3.7` 吧

**Comment by cyyinfo** [comment]
问题解决了吗？
我是 3.6.22 还是有这个问题
