### ISSUE TITLE
微信小程序下引入腾讯视频插件失败

### ISSUE THREAD

**Issue by scau009** [NervJS/taro#1316]
**问题描述**
[问题描述：微信小程序下引入插件失败]

**复现步骤**
[复现问题的步骤]
1. app.js中添加配置
![image](https://user-images.githubusercontent.com/18747266/49280065-194c5380-f4c4-11e8-9200-88837a96d9d7.png)
2. 在组件中添加声明
![image](https://user-images.githubusercontent.com/18747266/49280096-33863180-f4c4-11e8-8978-b5aca71af711.png)

3. 在对应组件中使用
加入组件
`<txv-video></txv-video>` 

4.错误如下
![image](https://user-images.githubusercontent.com/18747266/49280164-6d573800-f4c4-11e8-8805-a8990cf8275f.png)

**期望行为**
[希望组件能正常显示，编译通过]

**报错信息**
![image](https://user-images.githubusercontent.com/18747266/49280164-6d573800-f4c4-11e8-8805-a8990cf8275f.png)
**系统信息**

 - 操作系统: [mac os 10.14]
 - Taro 版本 [v.1.1.9]
 - Node.js 版本 [v10.11.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
VideoPlay 这个组件的文件代码贴出来看下

**Comment by scau009** [comment]
我稍微修改了一下组件的代码，有了别的报错信息如下
`
import Taro, {Component} from '@tarojs/taro'
import {View} from '@tarojs/components'
import './index.scss'

export default class VideoPlay extends Component {

    static defaultProps = {
        diyParams: {},
        diyStyle: {},
        diyData: [],
    };

    config = {
        // 定义需要引入的插件
        usingComponents: {
            'qqVideo': 'plugin://qqVideo/txv-video'
        }
    };

    constructor(props) {
        super(props)
        this.state = {
            sound: true,
            soundpic: false,
            showCover: true,
        }
    }


    render() {
        return (
            <View style={{height: '100%'}}>
                <txv-video
                    vid="e0354z3cqjp"   // 可使用vid="{{vid}}"的方式应用data变量
                    playerid="txv1"
                    autoplay={true} // 是否自动播放
                ></txv-video>
            </View>
        )
    }
}

`

错误信息如下：
![image](https://user-images.githubusercontent.com/18747266/49284072-6f25f900-f4ce-11e8-983c-643132858385.png)

**Comment by luckyadam** [comment]
这个报错说明代码都没问题了，然后是没找到 plugin 中的组件，你确认一下 plugin 的配置，以及组件的写法对不对
