### ISSUE TITLE
taro获取code码无效

### ISSUE THREAD

**Issue by rankaifeng** [NervJS/taro#13172]
### 相关平台
微信小程序

**小程序基础库: 2.30.0**
**使用框架: React**

### 复现步骤
使用taro.login获取到的code码 传给后台 总是提示code无效（但是如果在index.html引入https://res.wx.qq.com/open/js/jweixin-1.3.2.js这个过后，在项目中使用window.wx.login获取到的code就可以 为什么在taro命名空间下的Login不行）

### 期望结果
能正常获取code

### 实际结果
获取到的code无效

### 环境信息
```
�👽 Taro v3.5


  Taro CLI 3.5.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - D:\node.EXE
      Yarn: 1.22.11 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - D:\npm.CMD
```

**Comment by smoothdvd** [comment]
检查一下微信小程序的appid是否一致

**Comment by rankaifeng** [comment]
appid是一致的 奇怪的是 如果我第一次获取到的code就会报code无效 第二次过后就能成功

**Comment by bigmeow** [comment]
不要在 onGetPhoneNumber 授权回调里获取 code

**Comment by bigmeow** [comment]
`https://res.wx.qq.com/open/js/jweixin-1.3.2.js` 这个是开发 h5用的， 和小程序没关系
