### ISSUE TITLE
请问下taro 3.6.0什么时候发布？

### ISSUE THREAD

**Issue by zzq0324** [NervJS/taro#13179]
### 这个特性解决了什么问题？
请问下taro 3.6.0什么时候发布？我们基于taro3   vue3开发，当前急需要VirtualList的组件，但是taro 3中VirtualList不支持vue3版本，导致开发进度受阻。

### 这个 API 长什么样？
希望可以确认下发布日期，有beta版本先试用也ok，感谢。

**Comment by bigmeow** [comment]
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/10484248/215398683-3ff5b261-cbef-4a3f-8354-9789b183e27c.png">
https://www.npmjs.com/package/@tarojs/cli?activeTab=versions
