### ISSUE TITLE
taro-plugin-mini-ci  缺失原微信的ci 的setting 配置

### ISSUE THREAD

**Issue by oydiligent** [NervJS/taro#13174]
### 这个特性解决了什么问题？
打包 项目设置，自动化es6转es5, 插件代码压缩等

### 这个 API 长什么样？
配置项对其微信原 CI 功能

**Comment by bigmeow** [comment]
上传时的 `es6转es5` `代码压缩`功能 是关闭的， 因为构建时 taro 时已经做了这个工作， 代码压缩也是做了，压根不需要
所以你是啥场景需要额外配置

**Comment by oydiligent** [comment]
> 上传时的 `es6转es5` `代码压缩`功能 是关闭的， 因为构建时 taro 时已经做了这个工作， 代码压缩也是做了，压根不需要 所以你是啥场景需要额外配置

![image](https://user-images.githubusercontent.com/19690319/215978457-ddf3931b-fd45-4762-9ccf-f6a32c795bb5.png)
在微信后台有这个报错，这个报错是es6 语法问题

**Comment by bigmeow** [comment]
如果是使用了`...` 对象扩展运算符， `taro` 构建时会将其转换成 `Object.assign` 形式的， 建立你在构建完成的 `dist`目录里搜索下，确认下

**Comment by oydiligent** [comment]
> 形式的， 建立你在构建完成的 `dist`目录里搜索下，确认下

打包的业务组件没有 ... 对象扩展运算符,但是vendors.js 存在许多 解构的写法
![image](https://user-images.githubusercontent.com/19690319/216212214-633f306a-23ad-4abb-ab45-80094e3880bc.png)

**Comment by bigmeow** [comment]
@oydiligent 试一下这个配置
https://docs.taro.zone/docs/next/config-detail#minicompileinclude

**Comment by bigmeow** [comment]
@oydiligent 问题是否有解决

**Comment by oydiligent** [comment]
> @oydiligent 问题是否有解决

没有，我把压缩关了，检查了一下vendors.js，里面还是存在一些解构（...），其中似乎是我引的recoil库，
![image](https://user-images.githubusercontent.com/19690319/217773596-adbf60a5-0c23-4ae9-b13f-e6714a7a1d7e.png)
然后我把这个配置加上你说的配置
![image](https://user-images.githubusercontent.com/19690319/217774082-45901d5b-637c-4016-8571-5eec5e786ca3.png)
没生效，不知道是否是我配置有问题

备注： recoil 版本 0.7.5  "@tarojs/cli": "3.5.7", "@tarojs/taro": "3.5.7",

**Comment by bigmeow** [comment]
把整个 node_modules 算进去就行了
```ts
    compile: {
      include: [
        (modulePath) => {
          return /node_modules/.test(modulePath);
        }
      ]
    }

```

**Comment by oydiligent** [comment]
> 把整个 node_modules 算进去就行了
> 
> ```ts
>     compile: {
>       include: [
>         (modulePath) => {
>           return /node_modules/.test(modulePath);
>         }
>       ]
>     }
> ```

你说的是这样的配置吧
![image](https://user-images.githubusercontent.com/19690319/218033541-add61b2f-be84-4617-8cc9-f43b27928f71.png)

**Comment by bigmeow** [comment]
1. 预编译得关掉
2. 改了配置后,`node_modules/.taro` 缓存删掉
3. 最好是构建生产模式，混淆和压缩都开启了

**Comment by oydiligent** [comment]
> 1. 预编译得关掉
> 2. 改了配置后,`node_modules/.taro` 缓存删掉
> 3. 最好是构建生产模式，混淆和压缩都开启了
>    就我自己的项目来说，之前也查出了和你一样的问题，把 `node_modules` 目录包含进去，现在已经解决掉了。
> 
> ps： 如果你是 `minorepo` 模式的仓库， 除了把 `node_modules` 目录包含编译意外，还需要包含仓库下的其他依赖包

没起作用
1、我应该采用的是默认的编译配置，那应该用的webpack4，这个没看到有配置预编译的配置
2、我没看见node_modules/.taro这个文件，不过把整个node_modules都删除了
3、package.js 有配置NODE_ENV=production，混淆和压缩都一般都是开启的默认配置，最近为了看打包情况把terser.enable设置为false

**Comment by bigmeow** [comment]
预计 `3.6.2`  版本发布
