### ISSUE TITLE
轮播图从最后一张无缝连接滑动到第一张会出现不显示图片（升级最新版本3.5.12，问题依然存在）

### ISSUE THREAD

**Issue by lowprofile-isp** [NervJS/taro#13188]
### 相关平台
H5

**浏览器版本: Chrome108.0.5359.125**
**使用框架: React**

### 复现步骤
轮播图从最后一张无缝连接滑动到第一张会出现不显示图片

### 期望结果
轮播图从最后一张无缝连接滑动到第一张正常显示

### 实际结果
轮播图从最后一张无缝连接滑动到第一张会出现不显示图片

### 环境信息
```
👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.0 - D:\tools\nvm\nodejs\node.EXE
      Yarn: 1.22.19 - D:\tools\nvm\nodejs\node_global\yarn.CMD
      npm: 8.15.0 - D:\tools\nvm\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
看你提交的环境信息是 3.5.11，该问题修复于 #13079，需至少升级到 3.5.12 版本（如果已经更新，请确定加载的 swiper-item 依赖正确）

swiper 组件使用情况复杂，仅凭一句话很难复现并定位相关问题，提交问题时请附加用例或最小可复现仓库便于快速跟进，谢谢～

**Comment by lowprofile-isp** [comment]
是升级到最新的版本3.5.12，问题还是有的，循环模式收尾衔接有问题。目前没有可用用例和仓库地址

**Comment by lowprofile-isp** [comment]
最后一个切换到第一个时不触发onChange事件

**Comment by lowprofile-isp** [comment]
<Swiper
                    autoplay
                    circular
                    indicatorDots
                    indicatorColor='#999'
                    indicatorActiveColor='#333'
                >
                    {
                        ['https://avatars.githubusercontent.com/u/44639576?s=400&u=9228817869693f672f6aa1d75725548855838c6f&v=4', 'https://avatars.githubusercontent.com/u/44639576?s=400&u=9228817869693f672f6aa1d75725548855838c6f&v=4', 'https://avatars.githubusercontent.com/u/44639576?s=400&u=9228817869693f672f6aa1d75725548855838c6f&v=4'].map((item, i) => (
                            <SwiperItem key={i}>
                                <Image src={item}></Image>
                            </SwiperItem>
                        ))
                    }
                </Swiper>

**Comment by lowprofile-isp** [comment]
[swiper-bug.md](https://github.com/NervJS/taro/files/10542543/swiper-bug.md)

**Comment by jianhao2010303** [comment]
最后一个切换到第一个时不触发onChange事件 +1

**Comment by ZakaryCode** [comment]
在 https://github.com/NervJS/taro/commit/da7871c089f30512cb7a10419756e36699b1cd55 优化，可在新版本中尝试
