### ISSUE TITLE
Taro 版本是3.4.12 在Android9 的手机上白屏

### ISSUE THREAD

**Issue by MarkLogin** [NervJS/taro#13183]
> @rabbitao 楼上正解，你的项目依赖还是 3.2.8

我现在使用的Taro 版本是3.4.12 在Android9 的手机上还存在这个白屏问题,build 构建存在该问题，dev打包不存在该问题

这是报错信息
/chromium: [INFO:CONSOLE(2)] "Uncaught SyntaxError: 'super' keyword unexpected here", source: http://172.17.60.117:8080/pretrapp/chunk/0.js (2)
I/chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: ChunkLoadError: Loading chunk 0 failed.
    (missing: http://172.17.60.117:8080/pretrapp/chunk/0.js)", source: http://172.17.60.117:8080/pretrapp/js/app.js (2)

![DPW16AD(}$Q3GWI_{ O%DLF](https://user-images.githubusercontent.com/12522661/215412232-dfebe4db-f19e-41ab-b0c2-b38567b9178c.png)

这是项目中使用的版本

![9EV4B8MM_ YIVOW_$WZ``LG](https://user-images.githubusercontent.com/12522661/215411941-be0500db-ce6c-470b-bcae-521cf538d2c0.png)

    "@tarojs/cli": "3.4.12",
    "@tarojs/components": "3.4.12",
    "@tarojs/plugin-framework-react": "^3.4.12",

taro info

👽 Taro v3.5.3

  Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.10.0 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - D:\nodejs\npm_path\yarn.CMD
      npm: 7.12.0 - D:\nodejs\npm.CMD
![8VGQP{B3W34(OSMKDFM)9C7](https://user-images.githubusercontent.com/12522661/215412062-9727b212-8f41-465e-afc7-9a461dc70a3a.png)

_Originally posted by @MarkLogin in https://github.com/NervJS/taro/issues/8648#issuecomment-1408088719_

**Comment by ZakaryCode** [comment]
请通过模板新建 issue

根据当前已有错误信息，应该是部分不支持的语法未转换，可以通过新的 issue 提交错误详细信息或尝试升级 taro 版本修复该问题。

**Comment by hxlniada** [comment]
+1
