### ISSUE TITLE
mobx6.x 报错 MobX requires global 'Symbol' to be available or polyfilled

### ISSUE THREAD

**Issue by ranransun** [NervJS/taro#13184]
mobx使用6.x版本微信小程序正常，
支付宝小程序报如题错误，排查了一下，getGlobal 这个方法上的window未定义Symbol，如下图
![image](https://user-images.githubusercontent.com/33243820/215445576-10a8fd70-9d74-45f8-b78c-5f2b0c0b3960.png)

**Comment by yoyo837** [comment]
如果taro没有polyfill这个, 可以先自行polyfill一下

**Comment by zengqingzhuang** [comment]
现在是 用了mobx6后，只要调用observer方法就报错
<img width="777" alt="image" src="https://github.com/NervJS/taro/assets/12510482/96b0bc3e-4435-48c0-a4c0-ccdda83fe769">

**Comment by zengqingzhuang** [comment]
<img width="785" alt="image" src="https://github.com/NervJS/taro/assets/12510482/395cd5e9-1495-4c1c-bd99-b65c6ce8a05d">

**Comment by Solyna** [comment]
遇到了同样的问题，还没解决吗？

**Comment by Solyna** [comment]
> 如果taro没有polyfill这个, 可以先自行polyfill一下

怎么加？
