### ISSUE TITLE
WebStorm提示cannot resolve

### ISSUE THREAD

**Issue by ken3613** [NervJS/taro#13197]
### 相关平台
微信小程序

**小程序基础库: 无关**
**使用框架: Vue 3**

### 复现步骤
只能从@tarojs/taro import Taro，其他import均提示cannot resolve，如 import { useRouter } from '@tarojs/taro';
实际上，点command 单击可以跳转到taro.hook.d.ts中

### 期望结果
无这个警告

### 实际结果
Cannot resolve symbol 'useRouter' 

### 环境信息
```
👽 Taro v3.5.12


  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.5.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.4.0 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.12 => 3.5.12
      @tarojs/components: 3.5.12 => 3.5.12
      @tarojs/helper: 3.5.12 => 3.5.12
      @tarojs/plugin-framework-vue3: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-alipay: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-jd: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-qq: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-swan: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-tt: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12
      @tarojs/router: 3.5.12 => 3.5.12
      @tarojs/runtime: 3.5.12 => 3.5.12
      @tarojs/shared: 3.5.12 => 3.5.12
      @tarojs/taro: 3.5.12 => 3.5.12
      @tarojs/taro-h5: 3.5.12 => 3.5.12
      @tarojs/webpack5-runner: 3.5.12 => 3.5.12
      babel-preset-taro: 3.5.12 => 3.5.12
      eslint-config-taro: 3.5.12 => 3.5.12
```

**Comment by ken3613** [comment]
奇怪的是。。我把tsconfig里面的`baseUrl`配置注释了就不会提示这个，但这不是默认值吗

**Comment by ken3613** [comment]
又看了一下，在vscode下没有问题，是否可以归结为webstorm的锅

**Comment by AdvancedCat** [comment]
> 又看了一下，在vscode下没有问题，是否可以归结为webstorm的锅

拥抱 VSCode 吧，免费开源还好用，你值得拥有

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/216041106-10859f59-0901-492d-a983-d90e364821a3.png)
![image](https://user-images.githubusercontent.com/22173084/216041579-f0cc9ce3-f773-4882-9ade-b9c3f5a84ec8.png)

我用`React`， 正常

**Comment by ken3613** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/216041106-10859f59-0901-492d-a983-d90e364821a3.png) ![image](https://user-images.githubusercontent.com/22173084/216041579-f0cc9ce3-f773-4882-9ade-b9c3f5a84ec8.png)
> 
> 我用`React`， 正常

我用react的模板也正常，V3就会有问题，你可以试试V3+Ts的模板

**Comment by TheKonka** [comment]
嗯，试了下vue 的确实会出现这个提示
搜索了一下，不知道是不是 declare module 的原因
https://github.com/FortAwesome/vue-fontawesome/issues/177
https://youtrack.jetbrains.com/issue/WEB-34818
https://github.com/vueuse/vueuse/issues/896

**Comment by ZakaryCode** [comment]
> V3就会有问题，你可以试试V3+Ts的模板

神奇，原来还有这个问题

> 嗯，试了下vue 的确实会出现这个提示
> 搜索了一下，不知道是不是 declare module 的原因

感觉可能会是，这在 vscode 中调试起来也很头疼，Vue 中类型这些操作真的还挺麻烦的，类似 #14036 提到的问题也是

**Comment by agileago** [comment]
用tsx吧，只能说在模板里面用类型太累了  https://github.com/agileago/vue3-taro

**Comment by jc840031139** [comment]
> 用tsx吧，只能说在模板里面用类型太累了 https://github.com/agileago/vue3-taro

我也使用的就是ts+vue3 
webstorm 也会出现这个问题 
vscode 没问题

**Comment by agileago** [comment]
用tsx
