### ISSUE TITLE
如何在微信小程序中实现文件预览功能？

### ISSUE THREAD

**Issue by Yuiai01** [NervJS/taro#13206]
### 这个特性解决了什么问题？
就是类似当前企微小程序 previewFile 的功能，可以预览文件。

### 这个 API 长什么样？
有一个合理的方法能够在 Taro 构建的微信小程序里预览文件，十分感谢。

**Comment by ZakaryCode** [comment]
openDocument?

**Comment by Yuiai01** [comment]
> openDocument?

openDocument 的文件类型并不全面o(╥﹏╥)o，需要如下功能：
![image](https://user-images.githubusercontent.com/112228030/216005656-ad3ddbd3-2a49-4c49-9061-c17c2978075d.png)

**Comment by TheKonka** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewMedia.html
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html
https://developers.weixin.qq.com/miniprogram/dev/api/file/wx.openDocument.html
只能搜索看看小程序有没有开放相关接口吧

**Comment by Yuiai01** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/api/file/wx.openDocument.html

目前只能是根据文件类型，选择不同的 API 进行打开了，感谢大佬们的帮助，那我 close 掉了。
