### ISSUE TITLE
h5模式下框架host强制设置为本地ip导致配置https代理时报错

### ISSUE THREAD

**Issue by hxlniada** [NervJS/taro#13200]
### 相关平台
H5

**浏览器版本: 109.0.5414.87**
**使用框架: Vue 3**

### 复现步骤
启动dev:h5
通过代理配置测试链接
比如将https://test.taro.com转发到http://127.0.0.1:10086

则会报错
The page at '$pageUrl' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://10.112.99.38:10086/ws'. This request has been blocked; this endpoint must be available over WSS

### 期望结果
在https页面内自动使用wss连接

### 实际结果
依然使用ws://   ip 建立连接

### 环境信息
```
Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.11 => 3.5.11 
      @tarojs/components: 3.5.11 => 3.5.11 
      @tarojs/helper: 3.5.11 => 3.5.11 
      @tarojs/plugin-framework-vue3: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-alipay: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-jd: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-qq: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-swan: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-tt: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-weapp: 3.5.11 => 3.5.11 
      @tarojs/router: 3.5.11 => 3.5.11 
      @tarojs/runtime: 3.5.11 => 3.5.11 
      @tarojs/shared: 3.5.11 => 3.5.11 
      @tarojs/taro: 3.5.11 => 3.5.11 
      @tarojs/taro-h5: 3.5.11 => 3.5.11 
      @tarojs/webpack5-runner: 3.5.11 => 3.5.11 
      babel-preset-taro: 3.5.11 => 3.5.11 
      eslint-config-taro: 3.5.11 => 3.5.11
```

![image](https://user-images.githubusercontent.com/3838586/215967675-47c975e9-3067-4f5a-aa95-f58bbace5e14.png)

查看代码发现taro-webpack5-runner/src/index.h5.ts将host强制设置为本地ip了，希望能做成可配置的

![image](https://user-images.githubusercontent.com/3838586/215968192-f176e9c3-75bb-4704-9cb7-1bc16b17619a.png)

**Comment by hxlniada** [comment]
暂时通过配置127.0.0.1避免了这个问题
但是就不能配置为0.0.0.0了

**Comment by PengBoUESTC** [comment]
> 

配置发一下看看 学习一下

**Comment by hxlniada** [comment]
@PengBoUESTC 
![image](https://user-images.githubusercontent.com/3838586/215977115-292e7a37-99bf-4bee-8286-77f9ecd79966.png)

**Comment by PengBoUESTC** [comment]
> 通过代理配置测试链接
> 比如将[https://test.taro.com转发到http://127.0.0.1:10086](https://test.taro.com%E8%BD%AC%E5%8F%91%E5%88%B0http://127.0.0.1:10086)

我是想看下你有问题的配置 

`通过代理配置测试链接
比如将[https://test.taro.com转发到http://127.0.0.1:10086](https://test.taro.xn--comhttp-8t0l64jy70s//127.0.0.1:10086)`

**Comment by hxlniada** [comment]
@PengBoUESTC 
![image](https://user-images.githubusercontent.com/3838586/215991216-f9a9b09d-5f3c-44ec-aba0-34086d17c5d6.png)
代理工具是whistle

**Comment by ZakaryCode** [comment]
Duplicate of #13493
