### ISSUE TITLE
【Taro v3.5.12】编译到快手小程序平台，不管是否使用 CustomWrapper 包裹，Text内的文案都无法显示

### ISSUE THREAD

**Issue by qiuxiyu** [NervJS/taro#13209]
### 相关平台
快手小程序

### 复现仓库
[https://github.com/qiuxiyu/taro_issue_demo.git](https://github.com/qiuxiyu/taro_issue_demo.git)

**使用框架: React**

### 复现步骤
（0）	环境
IDE版本 1.14.1 和 1.22.0 
新老版本IDE都试了，真机（ios）也预览测试了，结果相同
快手IDE下载地址：
https://mp.kuaishou.com/docs/develop/developerTools/downloadPath.html

（1）问题描述 截图
Taro 3.5.12 编译到快手小程序平台，不管是否使用 CustomWrapper 包裹，Text内的文案都【无法显示】
新老版本IDE都试了，真机也预览测试了，结果相同，截图详见 demo 中的文档

Taro 3.4.7编译到快手小程序平台，不管是否使用 CustomWrapper 包裹，Text内的文案都【可以正常显示】

（2）重现步骤
分别使用：
Taro 3.5.12 编译 demo 中的 kwai_3.5.12/ctaro，
Taro 3.4.7 编译 demo 中的 kwai_3.4.7/ctaro，
随后，使用 快手IDE 打开kwai 项目，即可重现。

### 期望结果
编译到快手小程序平台，不管是否使用 CustomWrapper 包裹，Text内的文案都【可以正常显示】

### 实际结果
编译到快手小程序平台，不管是否使用 CustomWrapper 包裹，Text内的文案都【无法显示】

### 环境信息
```
👽 Taro v3.5.12


  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
```

**Comment by Chen-jj** [comment]
感谢反馈~快手插件 v3.0 修复
