### ISSUE TITLE
【Taro v3.5.12】编译到微信小程序平台，使用 CustomWrapper 包裹原生自定义组件，自定义组件的内容无法显示

### ISSUE THREAD

**Issue by qiuxiyu** [NervJS/taro#13212]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/qiuxiyu/taro_issue_demo.git](https://github.com/qiuxiyu/taro_issue_demo.git)
**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
（0）	环境
IDE版本 1.05.2204250
Node 16.14.0
微信IDE设置的最低基础库版本 2.11.2
微信IDE下载地址：
https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html#_1-05-2204250-Windows-64-%E3%80%81-Windows-32

（1）问题描述 截图
Taro 3.5.12 编译到微信小程序平台，使用 CustomWrapper 包裹原生自定义组件，自定义组件的内容【无法显示】
 
真机（ios）预览效果与IDE一致

（2）重现步骤
示例代码在 taro_custom_component_CustomWrapper_demo 文件夹内
使用 Taro 3.5.12 编译 ctaro，使用 微信IDE 打开weapp，即可重现。

### 期望结果
Taro 3.5.12 编译到微信小程序平台，使用 CustomWrapper 包裹原生自定义组件，自定义组件的内容【正常显示】

### 实际结果
Taro 3.5.12 编译到微信小程序平台，使用 CustomWrapper 包裹原生自定义组件，自定义组件的内容【无法显示】

### 环境信息
```
👽 Taro v3.5.12


  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
```

**Comment by Chen-jj** [comment]
原因是自定义组件 CustomWrapper 的 json 配置没有声明 usingComponent，Taro 也没办法在编译时收集 CustomWrapper 引用的自定义组件。因此开发者可以在 app.config.js 全局注册该自定义组件，或利用 `modifyBuildAssets` 钩子修改 CustomWrapper 的 json 结果。
