### ISSUE TITLE
拖动地图不触发视野发生变化事件onRegionChange

### ISSUE THREAD

**Issue by sqs8866** [NervJS/taro#13221]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/sqs8866/taro-map-bug.git](https://github.com/sqs8866/taro-map-bug.git)
**小程序基础库: 2.78.04**
**使用框架: React**

### 复现步骤
用抖音开发工具及抖音app测试，拖动地图，不走onRegionChange事件

### 期望结果
拖动地图，触发视野发生变化事件onRegionChange

### 实际结果
拖动地图，没有触发视野发生变化事件onRegionChange

### 环境信息
```
� Taro v3.5.10


  Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\86182\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/releases/tag/v3.5.12
https://github.com/NervJS/taro/pull/13091
升级到 `3.5.12` 或更新的版本

**Comment by TigerFightTonight** [comment]
Taro v4.0.4 还是一样不走onRegionChange事件
