### ISSUE TITLE
request is undefined in npm package by import Tarojs/Taro

### ISSUE THREAD

**Issue by Edward-Zhou** [NervJS/taro#13231]
### 相关平台
H5

### 复现仓库
[https://github.com/Edward-Zhou/Meekou.TS.git](https://github.com/Edward-Zhou/Meekou.TS.git)
**浏览器版本: Chrome**
**使用框架: React**

### 复现步骤
1. install package
2. npm run dev
3.go to auto opened browser and http://localhost:4201/examples/mango.html
4. check debug console

### 期望结果
It will send request correct.

### 实际结果
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'request')

### 环境信息
```
👽 Taro v3.6.0


  Taro CLI 3.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
https://github.com/NervJS/taro/issues/12679

**Comment by ZakaryCode** [comment]
可以自行通过 [compile](https://nervjs.github.io/taro-docs/docs/next/config-detail/#minicompile) 配置 node_modules 下的编译行为。

> h5 下有同样配置，与补充 issue 无关
