### ISSUE TITLE
【Taro v3.6.0】生成样式报错

### ISSUE THREAD

**Issue by bs32g1038** [NervJS/taro#13236]
### 相关平台
微信小程序

**小程序基础库: 2.30.0**
**使用框架: React**

### 复现步骤
从3.5.10版本升级到3.6.0版本

### 期望结果
页面正常运行

### 实际结果
[ WXSS 文件编译错误] ./common.wxss
 unexpected "\" at pos 21782
  1123 | }
  1124 | 
> 1125 | .index-modules__button___sH6iv.index-modules__cancel___rda\ W {
       |                                                          ^
  1126 |   color: #6b65d8;
  1127 |   background-color: #fff;
  1128 |   border: 1rpx solid #6b65d8;

### 环境信息
```
👽 Taro v3.6.0


  Taro CLI 3.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by bs32g1038** [comment]
使用配置 `compiler: 'webpack5'` 后解决，`@tarojs/mini-runner` css-loader版本导致的异常

**Comment by Niubility-SunLight** [comment]
webpack5 编译失败，运行就报TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined.

**Comment by Yang03** [comment]
同样的错误，build:h5  版本3.6.2

**Comment by NoXCZJ** [comment]
> webpack5 编译失败，运行就报TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined.

检查下 node_modules 下的 webpack 版本是不是 V5 的

**Comment by JinChunCheng123** [comment]
3.6强制要求webpack5？升webpack5问题更多。。。

**Comment by ricksunxxx** [comment]
E:\taro\campus_customer_taro\takeout\node_modules\_@tarojs_webpack5-prebundle@3.6.14@@tarojs\webpack5-prebundle\dist\utils\webpack.js:10
const { ConcatSource } = webpack_1.sources;
        ^

TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined.
    at Object.<anonymous> (E:\taro\campus_customer_taro\takeout\node_modules\_@tarojs_webpack5-prebundle@3.6.14@@tarojs\webpack5-prebundle\src\utils\webpack.ts:7:9)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.newLoader [as .js] (E:\taro\campus_customer_taro\takeout\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (E:\taro\campus_customer_taro\takeout\node_modules\_@tarojs_webpack5-prebundle@3.6.14@@tarojs\webpack5-prebundle\src\utils\index.ts:157:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)

Node.js v20.5.1

**Comment by ricksunxxx** [comment]
const { ConcatSource } = webpack_1.sources;
        ^
TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined.
Node.js v20.5.1

  "_spec": "webpack@4.46.0",

我的配置文件使用的是compiler是webpack5，但是 node_modules 下的 webpack 版本并不是v5，是需要自己手动升级webpack5吗，我看官方有检查webpack5相关的依赖并且安装。
![image](https://github.com/NervJS/taro/assets/9975520/88bdfc5d-3e34-4887-8f4f-2face8020d6c)

**Comment by samkk** [comment]
同样遇到这个问题了，请求在呢么处理的
```javascript
Documents/project/voun/node_modules/@tarojs/webpack5-prebundle/dist/utils/webpack.js:10
const { ConcatSource } = webpack_1.sources;
        ^

TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined.

```

**Comment by ezirmusitua** [comment]
添加 webpack@^5 的依赖

**Comment by ziqisia** [comment]
> 使用配置 `compiler: 'webpack5'` 后解决，`@tarojs/mini-runner` css-loader版本导致的异常

配置了webpack5还是一样报错

**Comment by xhua007** [comment]
> const { ConcatSource } = webpack_1.sources; ^ TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined. Node.js v20.5.1
> 
> "_spec": "webpack@4.46.0",
> 
> 我的配置文件使用的是compiler是webpack5，但是 node_modules 下的 webpack 版本并不是v5，是需要自己手动升级webpack5吗，我看官方有检查webpack5相关的依赖并且安装。 ![image](https://github.com/NervJS/taro/assets/9975520/88bdfc5d-3e34-4887-8f4f-2face8020d6c)

<img width="995" alt="Image" src="https://github.com/user-attachments/assets/dab15b4c-d1f0-4d7c-8e31-eb190a67424b" />

**Comment by xhua007** [comment]
> 同样遇到这个问题了，请问怎么处理的
> 
> Documents/project/voun/node_modules/@tarojs/webpack5-prebundle/dist/utils/webpack.js:10
> const { ConcatSource } = webpack_1.sources;
>         ^
> 
> TypeError: Cannot destructure property 'ConcatSource' of 'webpack_1.sources' as it is undefined.

<img width="995" alt="Image" src="https://github.com/user-attachments/assets/1cccb6d1-d52a-4c93-b7e8-457cda9f2204" />
