### ISSUE TITLE
vue3项目无法打包rn？

### ISSUE THREAD

**Issue by RiuHDuo** [NervJS/taro#13240]
### 相关平台
React Native

**使用框架: Vue 3**

### 复现步骤
npm run build:rn

👽 Taro v3.5.8

Installing React-Native related packages:
react@^18.0.0 react-native@^0.69.3 expo@~46.0.2 @tarojs/taro-rn @tarojs/rn-runner
React-Native related packages have been installed successfully.

ATTEHNTION: Package.json has been modified automatically, please submit it by yourself.

metro.config.js created
index.js created
error Failed to load configuration of your project.
info Run CLI with --verbose flag for more details.

### 期望结果
打包

### 实际结果
报错

### 环境信息
```
👽 Taro v3.5.10


  Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
不支持

**Comment by zhiqingchen** [comment]
https://docs.taro.zone/docs/react-native
