### ISSUE TITLE
在router跳转前改变了state，跳转页面后，回退，页面状态未更新

### ISSUE THREAD

**Issue by dsky1990** [NervJS/taro#1324]
**问题描述**

`在router跳转前改变了state，跳转页面后，回退，页面状态未更新`

`CODE`

```js
this.setState(Object.assign({}, {
          isSend: false,
          sendMsg: '获取验证码',
          mobileMatch: true,
          passwordMatch: true,
          isSbumit: false,
          smscodedMatch: true,
        }), () => {
          console.log('befor nav: ', this.state)
          Taro.navigateTo({
            url: `/pages/login/login`
          })
        })
```
`console result`
![image](https://user-images.githubusercontent.com/1579516/49326864-9266ac00-f593-11e8-930b-02d72b7ec53e.png)

`rotuer 返回的page状态`

![image](https://user-images.githubusercontent.com/1579516/49326887-e40f3680-f593-11e8-9bcf-e355f0800809.png)

**期望行为**
期望行为：路由跳转回退后，页面按照`state`的状态更新

**系统信息**

 - 操作系统: [mac 10.12.6]
 - Taro 版本 [v1.1.9]
 - Node.js 版本 [v8.12.0]
 - 报错平台 [h5, weapp]

**Comment by Littly** [comment]
路由重构之后未重现 可以整体升级到1.2.0-beta.10试试
