### ISSUE TITLE
taro-cli 自定义插件如何扩展？

### ISSUE THREAD

**Issue by huixisheng** [NervJS/taro#1325]
1. 目前没有找到相关的文档说明？
2. 需求实现一些自定义扩展，比如根据图片资源大小，小图引用base64，大图上传云服务器(比如七牛、阿里云等)

**Comment by luckyadam** [comment]
暂时还不支持自定义扩展，后续我们会升级支持


> 2\. 需求实现一些自定义扩展，比如根据图片资源大小，小图引用base64，大图上传云服务器(比如七牛、阿里云等)

图片转 base64 已经支持了，文档配置中有说明，图片上传就得自己单独写脚本了

**Comment by Chen-jj** [comment]
Taro 2、Taro 3 已支持拓展 CLI 插件
