### ISSUE TITLE
请问是否有兼容腾讯出品的第三方微信组件库TDesign的计划？

### ISSUE THREAD

**Issue by imboni** [NervJS/taro#13255]
### 这个特性解决了什么问题？
可以完美使用腾讯不久前出品的第三方微信组件库TDesign，让开发者有更多的ui库选择

### 这个 API 长什么样？
可兼容大部分常见功能

**Comment by scrapstation** [comment]
+1

**Comment by Chen-jj** [comment]
看起来是小程序原生组件的写法，Taro 是支持引用原生组件的，我们应该不会单独抽时间测试对这个库的支持程度，各位可以先试试使用，有问题再反馈。
