### ISSUE TITLE
taro3.6 如何修改 rn版本

### ISSUE THREAD

**Issue by chuanjing** [NervJS/taro#13262]
### 这个特性解决了什么问题？
需求
1. 兼容ios12
2. 如何在taro3.6把rn版本降到0.64，配套是否有问题（react版本）；

### 这个 API 长什么样？
无

**Comment by zhiqingchen** [comment]
RN版本之间有较大差异，不建议这么做

**Comment by zhiqingchen** [comment]
有较多要改动的地方，参考 Taro 3.6 如何使用 RN 0.69

https://github.com/NervJS/taro/discussions/12468#discussioncomment-4259450
