### ISSUE TITLE
打包的H5在app中运行，出现点击和跳转页面延迟触发（1-2秒），并且期间多次点击，会出现B页面的内容显示在A页面

### ISSUE THREAD

**Issue by 5SUPERMAN** [NervJS/taro#13261]
### 相关平台
H5

**浏览器版本: app**
**使用框架: React**

### 复现步骤
1、taro打包出来的H5，在app中预览
2、通过点击事件，从A页面跳转到B页面，当出现点击事件延迟触发，页面跳转延迟触发时，连续点击该事件，会导致B页面的内容在其他A、B、C页面都会加载出来
3、在步骤2期间，因为点击事件延迟触发，无法做到禁止多次点击的操作

### 期望结果
点击事件不出现延迟，页面跳转不出现延迟

### 实际结果
taro打包出来的H5，在app中预览出现点击事件出现延迟，页面跳转出现延迟，导致无法做点击次数限制

### 环境信息
```
👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
```

### 补充信息
项目使用的版本是3.3.16

**Comment by ZakaryCode** [comment]
旧版本问题，请尝试更新版本后重试

**Comment by doudou673** [comment]
2025年 3.6.19 依然有这个问题
