### ISSUE TITLE
引入全局scss文件后，打包后发现head里面加入了多个相同<style></style> 文件，css文件也很多重复的

### ISSUE THREAD

**Issue by okssq** [NervJS/taro#13270]
### 相关平台
支付宝小程序

**小程序基础库: 任意**
**使用框架: Vue 3**

### 复现步骤
使用的是taro 3.5.12，用cli工具创建，选择默认模板，然后再config - index.js中添加sass配置resource数组，引入src下目录style目录下global.scss, 不管dev还是build，微信小程序，支付宝小程序还是h5都出现样式重复，而且重复很多

### 期望结果
编译后代码不会重复

### 实际结果
编译后代码无限重复

### 环境信息
```
👽 Taro v3.5.12


  Taro CLI 3.5.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\ssq\AppData\Roaming\npm\yarn.CMD
      npm: 9.1.3 - C:\Users\ssq\AppData\Roaming\npm\npm.CMD

```

**Comment by Jhaidi** [comment]
config中的sass.resource建议只引入`variables`配置，不要引入global style或者rest style，否则每次使用sass定义的变量或者函数时，都会产生重复css
