### ISSUE TITLE
VirtualList能否支持实现占据剩余空间

### ISSUE THREAD

**Issue by ljianc** [NervJS/taro#13274]
### 这个特性解决了什么问题？
目前只能通过固定的height指定高度，能否支持 通过css样式 flex:1 实现占据flex布局的剩余空间

**Comment by ZakaryCode** [comment]
不可以，虚拟列表需要根据传入高度计算显示区域，实现该特性意义不大，会挤占组件执行效率

> 实现该特性也是通过计算全屏尺寸作为基准值，可以实现并不会根据页面变化改变，可能导致额外问题；且可能有更多使用场景是占用部分页面高度，实现该特性应当同步考虑该场景。
