### ISSUE TITLE
open-type="chooseAvatar" 无法触发回调？

### ISSUE THREAD

**Issue by gumpBOBO** [NervJS/taro#13289]
taro版本："@tarojs/taro": "3.5.7", 用的vue3版本。
微信开发工具库：2.30.0  (最新的)

代码按官网给的写的
<button class="avatar-wrapper" open-type="chooseAvatar" onChooseAvatar={(e) => handleChooseAvatar(e)}>
能弹出选微信头像，但是点击后就是无法触发回调？

**Comment by whevether** [comment]
> taro版本："@tarojs/taro": "3.5.7", 用的vue3版本。 微信开发工具库：2.30.0 (最新的)
> 
> 代码按官网给的写的 <button class="avatar-wrapper" open-type="chooseAvatar" onChooseAvatar={(e) => handleChooseAvatar(e)}> 能弹出选微信头像，但是点击后就是无法触发回调？

由于并没有实现，之前的getUserInfo获取用户信息的能力被微信回收了。 所以现在这个不实现基本就没法获取到微信的头像和昵称。要么就是把那块使用微信原生模块封装城组件
