### ISSUE TITLE
H5 默认构建产物体积过大，可能错误包含了 @tarojs/components 的 source map

### ISSUE THREAD

**Issue by zhu-he** [NervJS/taro#13301]
### 相关平台
H5

**浏览器版本: 与浏览器无关**
**使用框架: React**

### 复现步骤
用 `taro init` 默认模板初始化 Taro React 项目，`npm run build:h5` 构建，产物中有个文件 chunk/4431.js (1.53 MiB) 大小过大，文件内容中包含了 `./node_modules/@tarojs/components/dist/esm-es5/hls-221423a1.js.map` 的内容

### 期望结果
H5 产物本身不应该包含 source map 相关代码

### 实际结果
H5 产物本身包含了 source map 相关代码

### 环境信息
```
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
可能与 https://github.com/NervJS/taro/commit/91302e7eb236ab96b3dfe5a6ca1e8174790c2f3b#diff-21ad80a9b1d7e6d1e876856b37b880215bfde0b54fa139fc56ba6a1e39e4a8bdR33-R36 改动有关，目前可以用以下代码暂时规避问题
```javascript
h5: {
  webpackChain(chain) {
    chain.module
      .rule('map')
      .test(/\.map$/)
      .use('null-loader')
  }
}
```

**Comment by ZakaryCode** [comment]
确实有点问题，可以参考配置 [`alias: false`](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#deprecated-loaders)

下一个版本修复
