### ISSUE TITLE
v1.2.0-beta.6版本使用第三方模块flyio报错

### ISSUE THREAD

**Issue by lizhoukai** [NervJS/taro#1330]
**问题描述**
```js
// 使用模板调用flyio 出错
const Fly = require('flyio/dist/npm/wx') // eslint-disable-line
const http = new Fly()

//error信息
 sdk uncaught third Error 
 Fly is not defined 
 ReferenceError: Fly is not defined
    at new module.exports (http://127.0.0.1:61023/appservice/npm/flyio/dist/npm/wx.js:841:9)
    at 
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [v1.2.0-beta.6]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by guider** [comment]
同样问题   1.2.0-beta7

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/49528178-6e3a0080-f8ee-11e8-8cb7-cad462a26f52.png)
这个包的代码有问题，这个 Fly 未定义
