### ISSUE TITLE
RootPortal组件内部的点击事件不响应

### ISSUE THREAD

**Issue by zhipenglin** [NervJS/taro#13312]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/zhipenglin/taro-root-portal-bug.git](https://github.com/zhipenglin/taro-root-portal-bug.git)
**小程序基础库: 2.30.0**
**使用框架: React**

### 复现步骤
放在RootPortal组件内部的组件，当RootPortal组件外部有onClick事件监听的时候，内部组件的onClick不能正常响应

### 期望结果
RootPortal组件的内部组件的onClick正常响应

### 实际结果
RootPortal组件的内部组件的onClick不能正常响应

### 环境信息
```
 Taro CLI 3.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/root-portal.html
小程序原生也是不响应，除非你直接点击内部组件

**Comment by zhipenglin** [comment]
是这样，如果RootPortal外部有View监听onClick事件，RootPortal内部View监听的事件就不响应，如果把外部的VIew的onClick去掉，内部的View监听就可以生效了，不是说内部View onClick要RootPortal外部的View生效

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/blob/fa5c71cde7d659be9d037ba427eb9821f5327e3e/packages/taro-runtime/src/dom/event.ts#L176
https://github.com/NervJS/taro/blob/fa5c71cde7d659be9d037ba427eb9821f5327e3e/packages/taro-runtime/src/utils/index.ts#L76-L91

因为有祖先元素监听了`onClick`事件， `isParentBinded`为`true`，导致没有回调

**Comment by Fried-dumplings** [comment]
现在还是会有这个问题，我用原生小程序是没有这个问题，求大佬麻烦看一下 @TheKonka
