### ISSUE TITLE
feat: 我希望虚拟滚动组件可以加入动态高度特性

### ISSUE THREAD

**Issue by wegi8** [NervJS/taro#13322]
### 这个特性解决了什么问题？
虚拟滚动组件高度不规则

### 这个 API 长什么样？
dynamicHeight: boolean;
default: false;

**Comment by ZakaryCode** [comment]
指虚拟列表高度，还是渲染的子组件高度？

**Comment by wegi8** [comment]
> 

子组件高度

**Comment by wegi8** [comment]
> 指虚拟列表高度，还是渲染的子组件高度？

子组件高度

业务层面上，我子组件由于登录用户的权限不同，展示的内容也不同，导致子组件高度不同

**Comment by ZakaryCode** [comment]
这是支持的，可以参见虚拟列表的文档，可以动态传入子组件高度，或者解锁实际子组件高度

**Comment by wegi8** [comment]
> 这是支持的，可以参见虚拟列表的文档，可以动态传入子组件高度，或者解锁实际子组件高度

 unlimitedSize
 解锁高度已经使用，但由于子组件高度差异过大，导致太长的子组件渲染不全

动态高度 目前我看只有父组件一个height的itemSize
就是这样
list 
  -> item1 height 200
  -> item2 height 400
  -> item3 height 350

**Comment by ZakaryCode** [comment]
> 但由于子组件高度差异过大，导致太长的子组件渲染不全

确实，子组件如果加载过慢有可能会有此类问题

> 动态高度 目前我看只有父组件一个height的itemSize

是的，可以通过函数动态设置子组件高度
