### ISSUE TITLE
升级 `Taro` 依赖以支持 `Node 18` 

### ISSUE THREAD

**Issue by TheKonka** [NervJS/taro#13328]
### 这个特性解决了什么问题？
`Node 18` 已经是 `LTS` 版本了，希望升级 `Taro` 依赖以支持 `Node 18` 

 `node-sass@8.0.0` =>  `sass-loader@13.2.0` => `webpack@5.0`

### 这个 API 长什么样？
支持 `Node 18`

**Comment by Airkro** [comment]
现在是支持的，默认没有安装 node-sass

**Comment by ZakaryCode** [comment]
4.x 分支已经支持 node18
