### ISSUE TITLE
Taro API 缺少 checkIsAddedToMyMiniProgram

### ISSUE THREAD

**Issue by whinc** [NervJS/taro#13325]
### 这个特性解决了什么问题？
检测小程序是否被添加到了【我的小程序】

### 这个 API 长什么样？
[wx.checkIsAddedToMyMiniProgram(Object object)](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/my-miniprogram/wx.checkIsAddedToMyMiniProgram.html)

**Comment by 1oo1** [comment]
如果使用 typscript 的话，试试在 global.d.ts 里添加这样的声明：

```ts
/** Taro 有不支持的 api 时，可以通过 wx 直接调用 */
interface WechatApi {
  checkIsAddedToMyMiniProgram: (options: any) => void;
}
declare const wx: WechatApi;
```

**Comment by whinc** [comment]
> 如果使用 typscript 的话，试试在 global.d.ts 里添加这样的声明：
> 
> 
> 
> ```ts
> 
> /** Taro 有不支持的 api 时，可以通过 wx 直接调用 */
> 
> interface WechatApi {
> 
>   checkIsAddedToMyMiniProgram: (options: any) => void;
> 
> }
> 
> declare const wx: WechatApi;
> 
> ```

Ok

**Comment by heiazu** [comment]
可使用@tarojs/plugin-inject进行api的补充：[传送门](https://github.com/NervJS/taro/tree/next/packages/taro-plugin-inject#1-syncapis)

**Comment by Hephaest** [comment]
> 可使用@tarojs/plugin-inject进行api的补充：[传送门](https://github.com/NervJS/taro/tree/next/packages/taro-plugin-inject#1-syncapis)

我试了下不太行。我目前的 Taro 版本是 3.6.16。
