### ISSUE TITLE
typescript 语法错误时，未终止 webpack build 过程

### ISSUE THREAD

**Issue by 1oo1** [NervJS/taro#13327]
### 相关平台
支付宝小程序

**小程序基础库: 任意**
**使用框架: React**

### 复现步骤
1、taro init ts-test；
2、请选择框架 React
3、是否需要使用 TypeScript ？ Yes
4、请选择 CSS 预处理器（Sass/Less/Stylus） Less
5、请选择编译工具 Webpack5
6、请选择包管理工具 pnpm
7、请选择模板源 Gitee
8、请选择模版：默认模板 或者 taro-hooks 均能复现

打开 src/app.ts，随便写一行 ts 语法错误的代码，如 `const name: string = 123;`，在 vscode 里会提示语法错误：`Type 'number' is not assignable to type 'string'.ts(2322)`。此时执行编译命令 `pnpm run build:alipay`。

### 期望结果
编译失败，显示错误原因。

### 实际结果
编译成功。

### 环境信息
```
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/react: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
尝试了在配置文件里添加 bail 和 emitOnErrors，依旧未终止编译。

`chain.merge({ bail: true })` 或 `chain.merge({ bail: true, optimization: { emitOnErrors: false } })`

搜索到了这两个历史 issue https://github.com/NervJS/taro/issues/1700 https://github.com/NervJS/taro/issues/9646 ，还是期望能通过配置选择启用或关闭。

如果有配置成功的也请回复下，多谢了。

**Comment by 1oo1** [comment]
确实跟 taro 没有关系。@babel/plugin-transform-typescript 不会做类型检查。查到一种方案，使用 ForkTsCheckerWebpackPlugin 可以解决，但是我没有成功。

**Comment by AnthonyHao** [comment]
> 确实跟 taro 没有关系。@babel/plugin-transform-typescript 不会做类型检查。
> 
> 目前查到两种方案，均能成功，这两种均需要添加 typescript 到 devDependency。
> 
> **方案一：** 使用 [ForkTsCheckerWebpackPlugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) 在编译阶段检查，需要添加 webpack 插件。
> 
> ```ts
> webpackChain(chain) {
>       chain.merge({
>         plugin: {
>           TsCheck: {
>             plugin: ForkTsCheckerWebpackPlugin,
>             args: [
>               {
>                 async: true,
>                 typescript: {
>                   diagnosticOptions: {
>                     semantic: true,
>                     syntactic: true,
>                   },
>                 },
>                 formatter: process.env.NODE_ENV === 'production' ?
>                   ({
>                     code,
>                     severity,
>                     message,
>                     file,
>                     location: { start: { line, column } } = { start: { line: 0, column: 0 } }
>                   }) => {
>                     // console.log('======', arg);
>                     return `${severity} ${code}: ${message} \n  in ${file}:${line}:${column}\n`;
>                   } : 'codeframe'
>               }
>             ]
>           }
>         }
>       });
>     }
> ```
> 
> **方案二：** 利用 lint-stage，在 commit 阶段检查，需要配置 lint-stage：
> 
> ```json
> {
>   "src/**/*.{ts,tsx,js,jsx,json}": [
>     "bash -c 'tsc --noEmit'",
>     "eslint --fix"
>   ]
> }
> ```
> 
> 方案二的缺点是对整个项目做检查，更好的是用 [tsc-files](https://github.com/gustavopch/tsc-files)，但是该项目目前不支持 pnpm，同时不支持 d.ts 的引入。

感谢分享，顺便问一嘴，如果用ForkTsCheckerWebpackPlugin。就是遇到一个错误就会终止编译。怎么可以让他编译完把所有错误一次性爆出来。 我尝试在modifyWebpackChain里面`ts-loader`，但是失败了。
```
  ctx.modifyWebpackChain(args => {
    const chain = args.chain;
    
    chain.merge({
       module: {
         rules: {
           script: {
             test: /\.(ts|tsx)$/,
             exclude: [/node_modules/],
             use: [
               {
                 loader: 'ts-loader',
                 options: {
                   reportFiles: ['src/**/*.{ts,tsx}']
                 }
               }
             ]
           }
         }
       }
     })
  }
```

**Comment by 1oo1** [comment]
我理解的是应该改 ts-loader里的代码。但是如果不立即中止编译过程会有问题的，后续如语法树的构建都不会成功。
