### ISSUE TITLE
eslint对import Taro from `@tarojs/taro`的处理

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#1332]
**问题描述**
vscode下安装了eslint扩展后，会出现红线警示

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { observer, inject } from '@tarojs/mobx'

import './index.scss'

@inject('counterStore')
@observer
class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount() {}

  componentWillReact() {
    console.log('componentWillRect')
  }

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  increment = () => {
    const { counterStore } = this.props
    console.log(counterStore)
    counterStore.increment()
  }

  decrement = () => {
    const { counterStore } = this.props
    counterStore.decrement()
  }

  incrementAsync = () => {
    const { counterStore } = this.props
    counterStore.incrementAsync()
  }

  render() {
    const { counterStore } = this.props
    const result = counterStore.counter
    const all = counterStore.all
    console.log(result, 'result is.', all)
    return (
      <View className='index'>
        <Button onClick={this.increment}>+</Button>
        <Button onClick={this.decrement}>-</Button>
        <Button onClick={this.incrementAsync}>Add Async</Button>
        <Text>{result}</Text>
        <Text>{all}</Text>
      </View>
    )
  }
}

export default Index

```

**期望行为**
去除红线警示

**报错信息**

<img width="471" alt="wx20181203-090356 2x" src="https://user-images.githubusercontent.com/299532/49347564-acf76d00-f6da-11e8-8a42-afa8d0742ae1.png">

如果把`import Taro, { Component } from '@tarojs/taro'`改成`import { Component } from '@tarojs/taro'`
又出现 
<img width="414" alt="wx20181203-090408 2x" src="https://user-images.githubusercontent.com/299532/49347577-c4365a80-f6da-11e8-9fe8-3e8aa0002393.png">

**系统信息**

 - 操作系统: osx 10.14
 - Taro 版本 1.2.0-beta.6
 - Node.js 版本 10.05
 - 报错平台 weapp

**Comment by yuche** [comment]
`'Taro' is declared but its value is never read` 是 typescript 的 提醒，你应该设置一下你的 tsconfig.json

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/49351622-4761ab80-f6ef-11e8-8282-bb85ea023f0b.png)
这里不是 ts 的报错吗

**Comment by nyrf** [comment]
我就只是用taro init 生成的模板，没用typescript, vscode也是什么也没安装，
<img width="500" alt="wx20181203-113800 2x" src="https://user-images.githubusercontent.com/299532/49351764-e71f3980-f6ef-11e8-8038-1f1287e16a04.png">

<img width="500" alt="wx20181203-113941 2x" src="https://user-images.githubusercontent.com/299532/49351820-251c5d80-f6f0-11e8-84e1-1cbf084cedb0.png">

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/49352089-50537c80-f6f1-11e8-9373-2a4c7c93b877.png)
你的编辑器要加这个

**Comment by doabit** [comment]
这个其实在`tsconfig.json`中添加`"allowJs": true,`这一句就可以了。如果init项目时没有选择typescript，要自己在项目目录下新建`tsconfig.json`,可以直接复制https://github.com/NervJS/taro/blob/master/packages/taro-cli/templates/default/tsconfigjson 这里的内容

**Comment by nyrf** [comment]
谢谢，可以了。
