### ISSUE TITLE
Taro 3.2 - RN如何开发时调试

### ISSUE THREAD

**Issue by chuanjing** [NervJS/taro#13337]
### 这个特性解决了什么问题？
npm run dev:rn

没有出链接，没有出二维码

获取到 http://127.0.0.1:8081/index.bundle?platform=ios&dev=true

Taro playgound 和 Expo 访问都不行

Taro 3.2 版本如何调试呢？

### 这个 API 长什么样？
能通过扫码进行开发时调试，看到开发时候的页面与功能

**Comment by zhiqingchen** [comment]
重复问题：https://github.com/wuba/taro-playground/issues/86
