### ISSUE TITLE
3.2.14转H5，createRouter报错

### ISSUE THREAD

**Issue by datura-lj** [NervJS/taro#13331]
### 相关平台
H5

**浏览器版本: Chrome 92**
**使用框架: React**

### 复现步骤
执行 npm run dev:h5

### 期望结果
不报错

### 实际结果
报错

### 环境信息
```
👽 Taro v3.3.10

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
环境: undefined
undefined process.env.SERVER_ENV

  Taro CLI 3.3.10 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.4.14 => 3.4.14 
      @tarojs/components: 3.4.14 => 3.4.14 
      @tarojs/mini-runner: 3.4.14 => 3.4.14 
      @tarojs/react: 3.4.14 => 3.4.14 
      @tarojs/runtime: 3.4.14 => 3.4.14 
      @tarojs/taro: 3.4.14 => 3.4.14 
      @tarojs/webpack-runner: 3.4.14 => 3.4.14 
      babel-preset-taro: 3.4.14 => 3.4.14 
      eslint-config-taro: 3.4.14 => 3.4.14 
      react: ^17.0.2 => 17.0.2
```

**Comment by datura-lj** [comment]
Could not load content for webpack:///../src/router/index.ts?26d8 (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

**Comment by datura-lj** [comment]
import { createRouter, initPxTransform } from '@tarojs/taro'
import component from "./app"
import { window } from '@tarojs/runtime'
import { createReactApp } from '@tarojs/plugin-framework-react/dist/runtime'

import * as React from 'react'
import ReactDOM from 'react-dom'


import { defineCustomElements, applyPolyfills } from '@tarojs/components/loader'
import '@tarojs/components/dist/taro-components/taro-components.css'

applyPolyfills().then(function () {
  defineCustomElements(window)
})

var config = {"router":{"mode":"browser"},"pages":["pages/index/index","pages/detail/index"],"subpackages":[],"window":{"backgroundTextStyle":"light","navigationBarBackgroundColor":"#fff","navigationBarTitleText":"七鲜","navigationBarTextStyle":"black"}}
window.__taroAppConfig = config

if (config.tabBar) {
  var tabbarList = config.tabBar.list
  for (var i = 0; i < tabbarList.length; i++) {
    var t = tabbarList[i]
    if (t.iconPath) {
      t.iconPath = tabbarIconPath[i]
    }
    if (t.selectedIconPath) {
      t.selectedIconPath = tabbarSelectedIconPath[i]
    }
  }
}
config.routes = [
  
  Object.assign({
      path: 'pages/index/index',
      load: function() {
          return import("./pages/index/index")
      }
  }, {}),

  Object.assign({
      path: 'pages/detail/index',
      load: function() {
          return import("./pages/detail/index")
      }
  }, {}),

]


var inst = createReactApp(component, React, ReactDOM, config)
createRouter(inst, config, React) // 报错 如上条
initPxTransform({
  designWidth: function designWidth(input) {
    if (input.file.replace(/\\+/g, '/').indexOf('@nutui/nutui-react-taro') > -1) {
      return 375;
    }

    return 750;
  },
  deviceRatio: {"375":2,"640":1.17,"750":1,"828":0.905}
})

**Comment by ZakaryCode** [comment]
仅依赖这些难以进一步定位问题，可以先尝试升级版本并对齐依赖后重试
