### ISSUE TITLE
Taro v3.6.1使用custom-wrapper控件报错，Template `tmpl_0_custom-wrapper` not found.

### ISSUE THREAD

**Issue by rambuild** [NervJS/taro#13334]
### 相关平台
微信小程序

**小程序基础库: 2.25.1**
**使用框架: React**

### 复现步骤
使用vant-ui的picker组件时，控制台会报这个错误，同时picker组件无法正常显示。

### 期望结果
picker正常显示

### 实际结果
picker无法显示

### 环境信息
```
👽 Taro v3.5.10


  Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\Development\nvm\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Development\nvm\nodejs\yarn.CMD
      npm: 6.14.15 - C:\Development\nvm\nodejs\npm.CMD
```

**Comment by rambuild** [comment]
重新删除node_modules并重新安装后，可以正常显示一段时间，但是在某个时刻突然就又开始报错了。

**Comment by zzq0324** [comment]
+1，同样的报错

**Comment by liuhuapiaoyuan** [comment]
+1  忽然出现的错误

**Comment by xuanzebin** [comment]
怀疑是 prebundle 的问题，麻烦提供一下 demo 示例。

**Comment by yanchengqu** [comment]
3.3.16版本也遇到了类似问题，test环境存在，prod问题打包是好的。配置一样，很奇怪

**Comment by WeiCongcong** [comment]
遇到同样的问题，使用了`OSSA Picker` 无法显示选项，关掉prebundle之后是正常的，后来exclude掉`ossaui`了。
