### ISSUE TITLE
通过 vue render 函数渲染的组件中包含了内置组件 button，内置组件 button 模版不创建，无法正常显示

### ISSUE THREAD

**Issue by beezen** [NervJS/taro#13338]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/beezen/taro-demo-example.git](https://github.com/beezen/taro-demo-example.git)
**小程序基础库: 2.30.0**
**使用框架: Vue 2**

### 复现步骤
下载项目，到该目录下 https://github.com/beezen/taro-demo-example/tree/main/taro-3.6.1-component

1、直接 yarn dev:weapp 运行，并在微信开发者工具中打开。

2、发现组件并不能成功加载。（主要原因为：render 函数中实现的组件，vue 无法编译时解析到对应的 tag 标签名，在 template 创建时，例如 button 模版就被遗漏了）

### 期望结果
通过 render 函数写的组件也能够正常展示

### 实际结果
组件不能够正常展示

### 环境信息
```
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v16.12.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-vue2: 3.6.1 => 3.6.1 
      @tarojs/plugin-html: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
```

---
### 补充信息
在以往 3.3.x 版本中 componentConfig.includes 包含了所有 nodeName；在3.5.x或3.6.x版本中 componentConfig.includes 包含的 nodeName 都是根据模版按需添加的。

自定义组件代码：
```vue
<script>
export default {
  name: "button-comp",
  render: h => {
    return h("button", "自定义按钮");
  }
};
</script>

```

**Comment by xuanzebin** [comment]
button 模版的获取是通过判断用户对于 @tarojs/components 的引用来实现的，因此你只需要将上述自定义组件的代码修改成：
```vue
<script>
import { Button } from '@tarojs/components'

export default {
  name: "button-comp",
  render: h => {
    return h(Button, "自定义按钮");
  }
};
</script>
```

即可正常运行。

**Comment by beezen** [comment]
> button 模版的获取是通过判断用户对于 @tarojs/components 的引用来实现的，因此你只需要将上述自定义组件的代码修改成：
> 
> ```
> <script>
> import { Button } from '@tarojs/components'
> 
> export default {
>   name: "button-comp",
>   render: h => {
>     return h(Button, "自定义按钮");
>   }
> };
> </script>
> ```
> 
> 即可正常运行。

看了下源码，在Webpack Tree Shaking 的钩子地方有专门收集 @tarojs/components 导入的方法。确实能够解决自己写的自定义组件的问题，但对于那些三方 UI 库，如 vant 之类的，可能就不那么通用了（那些库都不会强依赖 taro 模块），感觉后续还是要研究研究的。
