### ISSUE TITLE
taro 3.5.12 ts 文件类型报错

### ISSUE THREAD

**Issue by bluescurry** [NervJS/taro#13353]
### 相关平台
H5

### 复现仓库
[https://gitee.com/bluescurry/taro-demo.git](https://gitee.com/bluescurry/taro-demo.git)
**浏览器版本: Chrome 109**
**使用框架: React**

### 复现步骤
pnpm run dev:h5 启动项目
控制台会报错

### 期望结果
不报错

### 实际结果
✘ [ERROR] The character ">" is not valid inside a JSX element

    src/hooks/useStoreData.ts:28:17:
      28 │   selector: (s) => S,
         ╵                  ^

  TypeScript's TSX syntax interprets arrow functions with a single generic type parameter as an
  opening JSX element. If you want it to be interpreted as an arrow function instead, you need to
  add a trailing comma after the type parameter to disambiguate:

### 备注
taro 的 3.5 和 3.6 版本都会报错。
<img width="859" alt="image" src="https://user-images.githubusercontent.com/19237129/220894864-a352df51-48be-494a-b3e0-e9c60cf96cdc.png">

### 环境信息
```
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1
      @tarojs/components: 3.6.1 => 3.6.1
      @tarojs/helper: 3.6.1 => 3.6.1
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1
      @tarojs/react: 3.6.1 => 3.6.1
      @tarojs/runtime: 3.6.1 => 3.6.1
      @tarojs/shared: 3.6.1 => 3.6.1
      @tarojs/taro: 3.6.1 => 3.6.1
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1
      babel-preset-taro: 3.6.1 => 3.6.1
      eslint-config-taro: 3.6.1 => 3.6.1
      react: ^18.0.0 => 18.2.0
```

**Comment by ZakaryCode** [comment]
这应该不是 ts 报错，可能是 esbuild 预编译时导致的，得空验证一下

**Comment by ZakaryCode** [comment]
可以先关掉 prebundle 试试

**Comment by bluescurry** [comment]
> 可以先关掉 prebundle 试试

关掉不报错了，辛苦有空修一下吧，prebundle 对启动速度影响还是很大的~ 我从3.4升到3.5就是为了这个哈哈

**Comment by ZakaryCode** [comment]
那确实是 esbuild 导致，可以先排除相关代码的预编译

**Comment by bluescurry** [comment]
> 那确实是 esbuild 导致，可以先排除相关代码的预编译，另外 esbuild 不支持 `<T>() => {}` 这样的类型解析，需要主动避免

好吧
