### ISSUE TITLE
支付宝小程序build打包后发送请求时报错TypeError: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by emmmm-maker** [NervJS/taro#13357]
### 相关平台
支付宝小程序

**小程序基础库: 2.8.3**
**使用框架: Vue 3**

### 复现步骤
进入小程序 点击立即开通按钮 发送请求  报错 TypeError: Cannot read properties of undefined (reading 'pathname')

### 期望结果
打包后小程序能正常发送请求正常运行

### 实际结果
build打包后发送请求报错TypeError: Cannot read properties of undefined (reading 'pathname')

### 环境信息
```
Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 9.4.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.12 => 3.5.12 
      @tarojs/components: 3.5.12 => 3.5.12 
      @tarojs/helper: 3.5.12 => 3.5.12 
      @tarojs/plugin-framework-vue3: 3.5.12 => 3.5.12 
      @tarojs/plugin-html: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-alipay: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-jd: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-qq: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-swan: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-tt: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12 
      @tarojs/router: 3.5.12 => 3.5.12 
      @tarojs/runtime: 3.5.12 => 3.5.12 
      @tarojs/shared: 3.5.12 => 3.5.12 
      @tarojs/taro: 3.5.12 => 3.5.12 
      @tarojs/taro-h5: 3.5.12 => 3.5.12 
      @tarojs/webpack5-runner: 3.5.12 => 3.5.12 
      babel-preset-taro: 3.5.12 => 3.5.12 
      eslint-config-taro: 3.5.12 => 3.5.12 
    npmGlobalPackages:
      typescript: 4.8.4
```

**Comment by TheKonka** [comment]
> 进入小程序 点击立即开通按钮

有 demo ?

**Comment by emmmm-maker** [comment]
@TheKonka 整个项目，我试下能不能抽离出来一个demo
<img width="893" alt="image" src="https://user-images.githubusercontent.com/67179703/221126234-2fd30528-374d-44bd-a09a-a519985d1d3c.png">

**Comment by emmmm-maker** [comment]
@TheKonka https://github.com/emmmm-maker/demo  
麻烦看下

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/221132615-03ba094e-326b-434c-a2ed-ed529cf8daf7.png)
![image](https://user-images.githubusercontent.com/22173084/221132780-4d980032-7416-4ab1-ae3f-facd10290a43.png)
没有遇到你那个报错

**Comment by emmmm-maker** [comment]
@TheKonka 请问是build嘛？

**Comment by emmmm-maker** [comment]
@TheKonka 我这边npm run dev:alipay也是没问题的 npm run build:alipay 就有问题了

**Comment by TheKonka** [comment]
> @TheKonka 请问是build嘛？

哦哦，忘记了build,build是有报错

**Comment by emmmm-maker** [comment]
我升级Taro版本后解决了 谢谢

**Comment by TheKonka** [comment]
可以的，记得保持更新`taro`版本 👍

**Comment by jsPeasant** [comment]
我也遇到这问题了，3.6.20的版本，dev  watch就可以， build就报错， dev和build模式 进行了不同处理吗

**Comment by jerryyan1990** [comment]
> 我也遇到这问题了，3.6.20的版本，dev watch就可以， build就报错， dev和build模式 进行了不同处理吗

3.6.22也一样 dev没问题，build就报错。
