### ISSUE TITLE
原生小程序容器SDK是否有计划？

### ISSUE THREAD

**Issue by coolxiaohao** [NervJS/taro#13359]
### 这个特性解决了什么问题？
目前使用Taro开发的小程序只能在各第三方发布，无法集成至自有APP。企业级应用想实现自有小程序方案比较困难。因此想问问官方大大小程序容器SDK是否有计划支持。

### 这个 API 长什么样？
提供原生集成小程序容器SDK

**Comment by bigmeow** [comment]
腾讯自己还在公测阶段，目前来说，还没稳定下来，所以不着急

**Comment by Chen-jj** [comment]
Taro 不会下场做小程序容器的，再说应该也不会有公司允许对这部分进行开源。
