### ISSUE TITLE
编译配置项copy 的 ignore 配置无效

### ISSUE THREAD

**Issue by lovelyqun** [NervJS/taro#13358]
### 相关平台
微信小程序

**小程序基础库: 2.27.3**
**使用框架: Vue 3**

### 复现步骤
按照文档配置

### 期望结果
按照官方的配置
  copy: {
    patterns: [
      {from:'static/',to:'dist/static/', ignore: ['*.js']}
    ],
    options: {
    }
  },
 应该在打包的时候排除static下的js文件

### 实际结果
拷贝的文件及路径都正确
但是里面还是包含.js文件
正确的配置应该是
  copy: {
    patterns: [
      {from:'static/',to:'dist/static/', ignore: ['**/*.js']}
    ],
    options: {
    }
  },

### 环境信息
```
  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
```js
ignore: ['**/*.js']
```
这样配置
