### ISSUE TITLE
子组件渲染children位置不对

### ISSUE THREAD

**Issue by darkmice** [NervJS/taro#1335]
**问题描述**
子组件渲染children位置不对

**复现步骤**
ListItem.js
```js
class ListItem extends Component {
  render() {
    const {title} = this.props
    return (<View className='list-item'>
      {title && <View className='list-itme-title'>{title}</View>}
      <View className='list-time-body'>{this.props.children}</View>
    </View>)
  }
}
 
```
index.js

```js
class ListItem extends Component {

  render() {
     
return <ListItem title='单位名称'>
          <Input name='name'/>
        </ListItem>`

  }
}
```
 
**报错信息**
生成后的代码：
![image](https://user-images.githubusercontent.com/1502088/49351991-c4415500-f6f0-11e8-82db-d53935862627.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.0-beta.7]
 - Node.js 版本 [e.g. v10.0.0]
 - 报错平台 [ weapp]

**Comment by liuhailang** [comment]
我也遇到了这个问题
