### ISSUE TITLE
Taro Vu3 虚拟列表有可以跑的demo吗？跑起来总是有问题

### ISSUE THREAD

**Issue by zzq0324** [NervJS/taro#13355]
### 相关平台
微信小程序

### 复现仓库
无

**小程序基础库: 未知**
**使用框架: Vue 3**

### 复现步骤
复制官方长列表的demo，https://taro-docs.jd.com/docs/virtual-list#vue 

### 期望结果
能够正常使用虚拟列表，希望帮忙提供一个demo参考，谢谢。

### 实际结果
只渲染第一版可视区域的数据，滚动之后都是空白的。另外往上滚动之后再往下就没法看到第一版初始化数据 的完整信息了。

### 环境信息
```
👽 Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /opt/homebrew/bin/node
      npm: 8.5.5 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1
      @tarojs/components: 3.6.1 => 3.6.1
      @tarojs/helper: 3.6.1 => 3.6.1
      @tarojs/plugin-framework-vue3: 3.6.1 => 3.6.1
      @tarojs/plugin-html: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1
      @tarojs/runtime: 3.6.1 => 3.6.1
      @tarojs/shared: 3.6.1 => 3.6.1
      @tarojs/taro: 3.6.1 => 3.6.1
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1
      babel-preset-taro: 3.6.1 => 3.6.1
      eslint-config-taro: 3.6.1 => 3.6.1
```

**Comment by zzq0324** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/24889976/220918204-d50f6f57-d925-402d-a515-28888f321bd0.png">
网上滚动之后，再往下只能看到局部数据了
<img width="417" alt="image" src="https://user-images.githubusercontent.com/24889976/220918296-a0629b37-5b4f-471d-a907-cca2f1beb5de.png">

帮忙看下是不是demo给的有问题？

**Comment by ZakaryCode** [comment]
模板没有问题，可以录制个详细视频看看，或者附上完整的使用 DEMO

**Comment by zzq0324** [comment]
> 模板没有问题，可以录制个详细视频看看，或者附上完整的使用 DEMO

你看下录制的视频，前面那个是demo的，后面那个是在业务中使用的，刚开始第一屏是正常显示的，上滑之后就只剩下一点点了。
https://user-images.githubusercontent.com/24889976/221077069-b40b8304-b1d1-465b-92d6-b38ca6d3ba86.mp4

**Comment by zzq0324** [comment]
补充下，项目中是使用了nutui 4，虚拟列表用的taro（taro支持更多的参数）。

**Comment by ZakaryCode** [comment]
看起来是 item-size、item-count 参数问题导致的，需要进一步验证看看

**Comment by zzq0324** [comment]
> 看起来是 item-size、item-count 参数问题导致的，需要进一步验证看看

@ZakaryCode 这边还需要提供什么信息吗？研究了很久我以为我写错了^_^

**Comment by zzq0324** [comment]
> 试过了，确实有问题，和视频里面的一样，第一版显示没问题，滚动进入第二版的时候只能显示部分，

@xiang12383 嗯，你也是在用虚拟列表吗？

**Comment by xiang12383** [comment]
> > 试过了，确实有问题，和视频里面的一样，第一版显示没问题，滚动进入第二版的时候只能显示部分，
> 
> @xiang12383 嗯，你也是在用虚拟列表吗？

这个虚拟列表试了一下有点问题，和你说一个效果。另外nutui虚拟列表测试了不确定是不是问题，item之间那部分滑动到顶部时候会产生很大抖动。

**Comment by zzq0324** [comment]
> > > 试过了，确实有问题，和视频里面的一样，第一版显示没问题，滚动进入第二版的时候只能显示部分，
> > 
> > 
> > @xiang12383 嗯，你也是在用虚拟列表吗？
> 
> 这个虚拟列表试了一下有点问题，和你说一个效果。另外nutui虚拟列表测试了不确定是不是问题，item之间那部分滑动到顶部时候会产生很大抖动。

嗯，我就是nutui有问题，不顺畅想换taro的。结果也不行

**Comment by wmhh1129** [comment]
复现了如题一模一样的问题 taro版本3.6.2 编译环境是 weapp，所以应该不是qq那边的兼容性问题。

**Comment by W-ambition** [comment]
同样遇到了该问题，请问最后采用了什么方案？ @zzq0324

**Comment by zzq0324** [comment]
> 同样遇到了该问题，请问最后采用了什么方案？ @zzq0324

后面放弃了，改用uniapp了- -

**Comment by MinakoKitani** [comment]
> > 同样遇到了该问题，请问最后采用了什么方案？ [@zzq0324](https://github.com/zzq0324)
> 
> 后面放弃了，改用uniapp了- -

你好，请问uniapp里采用了什么方式处理虚拟列表？
