### ISSUE TITLE
taro是否支持支持”小程序交易保障标展示组件“

### ISSUE THREAD

**Issue by mattjin** [NervJS/taro#13379]
### 这个特性解决了什么问题？
taro项目展示小程序交易保障标展示组件

### 这个 API 长什么样？
`
<guarantee-bar pageType="{{pageType}}" goodsName="{{goodsName}}" goodsImg="{{goodsImg}}" align="{{align}}" spaceSize="{{spaceSize}}" goodsPrice="{{goodsPrice}}" bannerStyle="{{bannerStyle}}"  />
`

**Comment by AdvancedCat** [comment]
哪个小程序端？贴一下文档

**Comment by mattjin** [comment]
微信小程序
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/guarantee/shopping-guarantee.html
已经知道怎么处理了

**Comment by mattjin** [comment]
微信小程序
https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/business-capabilities/guarantee/shopping-guarantee.html
已经知道怎么处理了
