### ISSUE TITLE
H5 如何在手机上查看调试

### ISSUE THREAD

**Issue by QTTQ** [NervJS/taro#1337]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

我把电脑 本地地址加在hosts中 然后电脑上npm run dev:h5  然后在手机中用这个地址 加载   但无法连接

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

127.0.0.1       localhost
192.168.0.11     localhost

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
期望运行项目时 在同网环境中 手机上可以用 192.168.0.11 加项目端口 查看项目 效果
**报错信息**
请求不到 网络
[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#h5devserver
按这个配一下 ip，然后在同一网络下可以访问

**Comment by QTTQ** [comment]
不行啊，我用其他项目起服务同网可以在手机上查看，taro的h5就显示无法访问此网站

**Comment by QTTQ** [comment]
![aaaa](https://user-images.githubusercontent.com/22019544/49359877-6cb3e100-f712-11e8-9ae8-d036e0cbd8a5.png)

**Comment by QTTQ** [comment]
![aaaaab](https://user-images.githubusercontent.com/22019544/49360007-e0ee8480-f712-11e8-95f1-980f31db41cb.png)
