### ISSUE TITLE
如何使用 Taro 的 API 判断当前小程序版本（开发版/体验版/正式版）？

### ISSUE THREAD

**Issue by zzefff** [NervJS/taro#13385]
### 这个特性解决了什么问题？
使用 Taro 的API 判断当前小程序版本（开发版/体验版/正式版）

### 这个 API 长什么样？
Maybe：
`Taro.xxxx_env = 'develop' / 'trial' / 'release'`

没有找到这样的api，目前只能在不同的小程序里用各自的判断方式，例如在微信小程序里使用：
`__wxConfig.envVersion === 'develop' / 'trial' / 'release'`

**Comment by TheKonka** [comment]
小程序有相应的`api`吧 ，调用 `Taro.getAccountInfoSync` 也是调用小程序原生的 `api`
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/account-info/wx.getAccountInfoSync.html
https://opendocs.alipay.com/mini/api/my.getAccountInfoSync

**Comment by zzefff** [comment]
> 小程序有相应的`api`吧 ，调用 `Taro.getAccountInfoSync` 也是调用小程序原生的 `api` https://developers.weixin.qq.com/miniprogram/dev/api/open-api/account-info/wx.getAccountInfoSync.html https://opendocs.alipay.com/mini/api/my.getAccountInfoSync

确实有用，是我疏忽了。close
