### ISSUE TITLE
从接口获取路由配置，运行阶段挂载路由

### ISSUE THREAD

**Issue by Benjaminbai** [NervJS/taro#13394]
### 这个特性解决了什么问题？
h5动态配置路由

### 这个 API 长什么样？
登陆后获取接口返回的路由数据，动态加载H5路由，实现地址栏随意配置，指定页面组件展示
请问如何实现此功能。
我尝试过使用createRouter方法，但是会报错，应该是load的时候找不到，但是项目运行时又取不到loaderContext，请求大佬帮助
<img width="552" alt="image" src="https://user-images.githubusercontent.com/23426556/222373081-37df53e6-7d6f-4579-baa5-2afd8305d4cb.png">
![Uploading image.png…]()

**Comment by yoyo837** [comment]
我是这样干的
```
const router = {
  '/': '/pages/index/index',
  '/webview': '/pages/webview/index',
  '/access/auto': '/pages/access/auto/index',
  '/user/my': '/pages/user/my/index',
  '/user/register': '/pages/user/register/index',
  '/user/login': '/pages/user/login/index',
  '/user/account': '/pages/user/account/index',
  '/user/forgot': '/pages/user/forgot/index',
  '/match': '/pages/match/index/index',
  '/match/judge': '/pages/match/judge/index',
  '/activity': '/pages/activity/index/index',
  '/activity/signup': '/pages/activity/signup/index',
};
```
左边配置给h5自定义路由, 右边是微信和文件实际本来的path

二次包装 `navitatorTo` 和 `redirectTo`, 封装的方法统一接收左边的路径, 根据平台, 转换成实际的, 用 `Taro.navitatorTo` 和`Taro.redirectTo` 做实际跳转

不知道是不是你想要的

**Comment by Benjaminbai** [comment]
@yoyo837 大佬，还是要结合h5的customRoutes，预先定义好是么？这样的话config文件只会在编译阶段执行一次，没法灵活修改

**Comment by yoyo837** [comment]
什么样的业务场景要在运行时修改?

**Comment by Benjaminbai** [comment]
@yoyo837 有个管理页面提供给用户，可以自定义地址，及绑定的页面组件

**Comment by yoyo837** [comment]
那就执行二次编译, 再上传服务器?

**Comment by ZakaryCode** [comment]
不建议这么使用，不过 load 报错应当是 config.routes 配置问题，可以参考 @tarojs/loader/lib/h5 看看。

**Comment by Benjaminbai** [comment]
@ZakaryCode 大佬，这块儿我不太明白，这是编译阶段运行的，那我在页面里怎么获取loaderContext呢
<img width="540" alt="image" src="https://user-images.githubusercontent.com/23426556/222659645-5284808f-2b50-4302-afb1-cfc481ede52d.png">
