### ISSUE TITLE
close

### ISSUE THREAD

**Issue by Lawguancong** [NervJS/taro#13395]
close

**Comment by wangjunjia** [comment]
taro 代码里没有搜到这个提示，建议去 同盾sdk 里提问，或者再排查一下代码，debugger 一下。

**Comment by Lawguancong** [comment]
> taro 代码里没有搜到这个提示，建议去 同盾sdk 里提问，或者再排查一下代码，debugger 一下。
很明显是taro弹窗的。同盾并没有搜到这个文案。当弹出“暂不支持当前功能” 时，立即Taro.showToast()是可以覆盖该文案的，且和弹窗时一模一样的。
或者Taro.hideToast可以关闭该文案（会闪屏幕）。
麻烦排查下你们的taro组件有无该文案

**Comment by Lawguancong** [comment]
> 什么情况下会弹出这个小窗口 “暂不支持当前功能”？ ![image](https://user-images.githubusercontent.com/22849450/222418138-19431234-78a4-4706-b136-74c6824200bb.png)
> 
> ### 相关平台
> 企业微信小程序
> 
> **使用框架: React**
> 
> ### 复现步骤
> 1. 引用同盾sdk import FMAgent from "./fm-1.6.4.1-es.en";
> 2. 实例化 this.fmagent = new FMAgent(params)
> 3. 调用方法 this.fmagent.getInfo(params)
> 4. 在手机-「企微」「触发该函数就会弹出窗口」toast一个窗口“暂不支持当前功能”
> 
> ### 期望结果
> .
> 
> ### 实际结果
> .
> 
> ### 环境信息
> ```
> 👽 Taro v3.4.8
> 
> Browserslist: caniuse-lite is outdated. Please run:
>   npx update-browserslist-db@latest
>   Why you should do it regularly: https://github.com/browserslist/update-db#readme
> 
>   Taro CLI 3.4.8 environment info:
>     System:
>       OS: macOS 12.5
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 12.22.0 - /usr/local/bin/node
>       Yarn: 1.22.19 - /usr/local/bin/yarn
>       npm: 6.14.11 - /usr/local/bin/npm
>     npmPackages:
>       @tarojs/components: 3.4.0 => 3.4.0 
>       @tarojs/mini-runner: 3.4.0 => 3.4.0 
>       @tarojs/plugin-framework-react: ^3.4.0 => 3.4.0 
>       @tarojs/react: 3.4.0 => 3.4.0 
>       @tarojs/runtime: 3.4.0 => 3.4.0 
>       @tarojs/taro: 3.4.0 => 3.4.0 
>       @tarojs/webpack-runner: 3.4.0 => 3.4.0 
>       babel-preset-taro: 3.4.0 => 3.4.0 
>       eslint-config-taro: 3.4.0 => 3.4.0 
>       react: ^17.0.0 => 17.0.2 
> ```
> 
> ### 补充信息
> .
