### ISSUE TITLE
react-native  安卓执行报错 ：Could not find method applyLegacyReactNativeLibsExtractionPlugin() for arguments [] on project ':expo-av' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by ma-x-x** [NervJS/taro#13390]
### 相关平台
React Native

### 复现仓库
[https://github.com/ma-x-x/my-docs-app.git](https://github.com/ma-x-x/my-docs-app.git)

**使用框架: React**

### 复现步骤
step1: yarn install 

step2: yarn upgradePeerdeps

step3: yarn android

### 期望结果
执行正常

### 实际结果
执行报错
* Where:
Build file '/workspace/cross-end/taro/my-docs-app/node_modules/expo-av/android/build.gradle' line: 181

* What went wrong:
A problem occurred evaluating project ':expo-av'.
> Could not find method applyLegacyReactNativeLibsExtractionPlugin() for arguments [] on project ':expo-av' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':expo'.
> compileSdkVersion is not specified. Please add it to build.gradle

### 环境信息
```
  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/react: 3.6.2 => 3.6.2 
      @tarojs/rn-runner: 3.6.2 => 3.6.2 
      @tarojs/rn-supporter: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/runtime-rn: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/taro-rn: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
      expo: ~47.0.3 => 47.0.13 
      react: ^18.1.0 => 18.2.0 
      react-native: ^0.70.1 => 0.70.7 
```

---
### 补充信息

模版生成的依赖包中 expo-av 为^13.0 版本，【yarn iso】可以正常执行，【yarn android】执行时会报错，降级到 12.03 版本后【yarn android】可正常运行，【yarn ios】执行异常。

**Comment by zhiqingchen** [comment]
先将expo-av 版本改为 13.0.2 参考 https://github.com/zhiqingchen/taro-test/commit/3c7d326f6d38883c9178721097d39369efafada0

已验证打包正常：
https://github.com/zhiqingchen/taro-test/actions

**Comment by zhiqingchen** [comment]
也可删除package中的 expo-module-core 包

**Comment by jingliangapp** [comment]
删除后每次执行 yarn upgradePeerDeps自动更新，什么时候可以发布新版本，这个bug直接导致没法打包了。

**Comment by zhiqingchen** [comment]
可以通过resolutions锁定

**Comment by jingliangapp** [comment]
1、已经增加  resolutions，移除yarn.lock和node_modules
"resolutions": {
    "expo-av": "13.0.2",
  }
2、执行yarn安装依赖
3、执行yarn upgradePeerdeps，这个会自动更新package.json的依赖
3、cd android 执行 gradlew.bat assembleRelease一样报错

Build file 'F:\taro-test\node_modules\expo-av\android\build.gradle' line: 181

* What went wrong:
A problem occurred evaluating project ':expo-av'.
> Could not find method applyLegacyReactNativeLibsExtractionPlugin() for arguments [] on project ':expo-av' of type org.gradle.api.Project.

**Comment by BestKai** [comment]
expo-av 版本 13.0.3
