### ISSUE TITLE
Swiper 中map循环后面跟 SwiperItem报错

### ISSUE THREAD

**Issue by js1121302139** [NervJS/taro#1339]
**问题描述**
Swiper 中map循环后面跟 SwiperItem报错

**复现步骤**
[复现问题的步骤]
[或者可以直接贴源代码，能贴文字就不要截图]

 <Swiper
                            indicatorDots={false}
                            circular={false}
                            onChange={this.handleBanner.bind(this)}>
                            {
                                list.map(item => {
                                    return (
                                        <SwiperItem key={item}>
                                            <View>
                                            </View>
                                        </SwiperItem>

                                    )
                                })
                            }
                            <SwiperItem>
                                <View>
                                    
                                </View>
                            </SwiperItem>
                        </Swiper>
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
希望在循环后面出现自定义的swiperItem
**报错信息**
Uncaught TypeError: Cannot read property 'children' of undefined
    at Swiper.eval (index.js?9b74:3222)
    at Array.map (<anonymous>)
    at Swiper.render (index.js?9b74:3219)
    at eval (index.js?1e21:1565)
    at errorCatcher (index.js?1e21:1481)
    at renderComponent (index.js?1e21:1564)
    at mountComponent (index.js?1e21:1534)
    at ComponentWrapper.init (index.js?1e21:1870)
    at createElement (index.js?1e21:1384)
    at mountChild (index.js?1e21:1450)
**系统信息**

 - 操作系统: [macOS 10.14.1 ]
 - Taro 版本 [1.2.0-beta.2]
 - Node.js 版本 [10.9.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
请更新到 1.2.0-beta.5 以上，该问题已解决
