### ISSUE TITLE
无法设置遮罩层将tabBar遮住

### ISSUE THREAD

**Issue by spicylemonhaha** [NervJS/taro#13409]
### 这个特性解决了什么问题？
解决了遮住tabBar的需求

### 这个 API 长什么样？
降低tabBar的层级接口

**Comment by TheKonka** [comment]
先看下是自定义tabbar还是非自定义tabbar，原生小程序能否遮住

**Comment by ZakaryCode** [comment]
改成自定义 tabbar 自行实现咯
