### ISSUE TITLE
【版本3.6.2 】ScrollView嵌套ScrollView，子组件scroll事件失效，只会触发父组件scroll事件

### ISSUE THREAD

**Issue by lhiro** [NervJS/taro#13413]
### 相关平台
H5

**浏览器版本: chrome 110**
**使用框架: Vue 3**

### 复现仓库
https://github.com/lhiro/taro-3.6.2-issue.git

### 期望结果
各个scrollview组件均可触发scroll事件

### 实际结果
只触发父级scroll事件

### 环境信息
```
👽 Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.19.3 - E:\App\Nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
      npm: 6.14.17 - E:\App\Nodejs\npm.CMD
```

**Comment by GitVitality** [comment]
https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/scroll-view/scroll-view.tsx#L96
在捕获阶段执行了e.stopPropagation()，父元素滚动后不会再传递给子元素。

**Comment by lhiro** [comment]
> https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/scroll-view/scroll-view.tsx#L96 在捕获阶段执行了e.stopPropagation()，父元素滚动后不会再传递给子元素。

代码里有@scroll.stop 且 也加了ev.stopPropagation

**Comment by lilugirl** [comment]
这个问题解决了吗？

**Comment by lhiro** [comment]
> 这个问题解决了吗？

并没有哦
