### ISSUE TITLE
头条支付tt.pay 现在支持了吗？

### ISSUE THREAD

**Issue by Createitv** [NervJS/taro#13410]
### 这个特性解决了什么问题？
跨多端支付能力

### 这个 API 长什么样？
Taro.pay({options})

**Comment by lanxuexing** [comment]
这个API在3.4好像就支持了的，我们都用了，不过现在抖音都全面拥抱交易系统支付了，担保支付以后估计渐渐回收了，交易系统支付Taro在3.6版本之后也是支持了的

**Comment by wenfangdu** [comment]
@lanxuexing 「交易系统支付」是啥，有相关文档嘛？

**Comment by xu756** [comment]
> 这个API在3.4好像就支持了的，我们都用了，不过现在抖音都全面拥抱交易系统支付了，担保支付以后估计渐渐回收了，交易系统支付Taro在3.6版本之后也是支持了的

哪里的，怎么没有
