### ISSUE TITLE
编译钉钉小程序页面内无内容

### ISSUE THREAD

**Issue by lupingW** [NervJS/taro#13415]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:lupingW/taro_dd.git](git@github.com:lupingW/taro_dd.git)
**小程序基础库: 1.25.7**
**使用框架: React**

### 复现步骤
运行npm run test 进入支付宝小程序开发者工具, 切换为钉钉第三方企业用户, 发现页面中只有一个page标签

### 期望结果
正确渲染出dom

### 实际结果
未渲染dom

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\node\node.EXE
      npm: 9.6.0 - D:\node\npm.CMD
```

**Comment by AdvancedCat** [comment]
![image](https://user-images.githubusercontent.com/7858761/223311895-004a6989-204a-4554-848a-0a941fb725d7.png)

看着没啥问题呦
看下你本地是否有明确的报错信息，可以提供一下

**Comment by lupingW** [comment]
![Uploading image.png…]()

**Comment by lupingW** [comment]
https://static.didapinche.com/pics/g/nxp65ppoil83.png

https://static.didapinche.com/pics/g/pman5ljlr2a1.png

https://static.didapinche.com/pics/g/smzjb6zfmr2.png

没有报错信息

**Comment by Chen-jj** [comment]
没有复现+1

<img width="1738" alt="image" src="https://user-images.githubusercontent.com/11807297/228429906-b3dd04c3-2504-489f-8d0c-c2a6c6383c9a.png">
