### ISSUE TITLE
page-container回调函数不生效

### ISSUE THREAD

**Issue by JuYiYang** [NervJS/taro#13419]
### 相关平台
微信小程序

**小程序基础库: 2.27.3**
**使用框架: Vue 3**

### 复现步骤
  <page-container
    :show="show"
    :z-index="zIndex"
    custom-style="background: transparent"
    :class="className('__page')"
    :on-after-enter="clickOverlay"
    :on-click-overlay="clickOverlay"
    :on-before-enter="clickOverlay"
  ></page-container>

#ts
// 外面双向绑定modelValue,赋值给show
const show = computed({
  get: () => props.modelValue,
  set: (val) => {
    emits('update:modelValue', val);
    iptValue.value = '';
    imgUrls.value = [];
  },
})

const clickOverlay = () => {
  console.log('clickOverlay');
  // show.value = false;
};

### 期望结果
点击遮罩层/离开后触发回调，然后我在回调里将show改为false

### 实际结果
所有回调的props传入的函数都不生效，导致直接关闭了这个容器，而我的值却没有被改变 

### 环境信息
```
Taro v3.5.8
Taro CLI 3.5.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - D:\npm.CMD
```

**Comment by TheKonka** [comment]
```js
@leave
@beforeleave
```
这样写看看
https://github.com/NervJS/taro/discussions/13290#discussioncomment-4967603

**Comment by JuYiYang** [comment]
> 

@也不生效，而且官方文档是把这几个回调定义为props

**Comment by TheKonka** [comment]
> @也不生效，而且官方文档是把这几个回调定义为props

你怎么写的哦，我试了可以触发回调
![image](https://user-images.githubusercontent.com/22173084/223374117-de31d6a1-7922-4aeb-be14-4f66ce18841b.png)

**Comment by JuYiYang** [comment]
> > @也不生效，而且官方文档是把这几个回调定义为props
> 
> 你怎么写的哦，我试了可以触发回调 ![image](https://user-images.githubusercontent.com/22173084/223374117-de31d6a1-7922-4aeb-be14-4f66ce18841b.png)

解决了，可是官方文档是把这几个回调定性为props，且前面带on前缀
![image](https://user-images.githubusercontent.com/107595466/223384693-87a43433-40e9-49ad-a9f5-ddcea4185ee7.png)

**Comment by JuYiYang** [comment]
感谢回答

**Comment by TheKonka** [comment]
文档里面的是默认`react`的写法

**Comment by JuYiYang** [comment]
> 文档里面的是默认`react`的写法

好的，感谢解答
