### ISSUE TITLE
ios抖音小程序真机调试白屏 

### ISSUE THREAD

**Issue by nosillytrying** [NervJS/taro#13414]
### 相关平台
字节跳动小程序

**小程序基础库: 2.80.0.2**
**使用框架: Vue 3**

### 复现步骤
直接init一个新的项目  taro版本3.5.6 抖音app版本24.3.0，字节小程序开发者工具4.0.4

### 期望结果
可以真机调试

### 实际结果
DevTools failed to load SourceMap: Could not load content for service.js.map: Unknown error 页面白屏

### 环境信息
```
  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/mini-runner: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-vue3: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/webpack-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
```

**Comment by TheKonka** [comment]
> DevTools failed to load SourceMap: Could not load content for service.js.map: Unknown error 

字节小程序官方原生的模版真机调试也有这个报错提示，不影响调试

我本地试了`taro@3.6.2`真机调试正常显示，没有白屏，可以升级版本试试，还是白屏可以给个`demo`
