### ISSUE TITLE
Taro.showModal，可以增加一个关闭前的回调方法，这个方法可以阻止Modal的关闭

### ISSUE THREAD

**Issue by grainXianSen** [NervJS/taro#13422]
### 这个特性解决了什么问题？
用户一进来页面会显示一个modal，如果用户点击了modal的确定按钮，调用某个接口，接口调用失败，这个时候其实不期望modal关闭

### 这个 API 长什么样？
可以新增一个before-close的option选项，在这里可以阻止modal关闭

**Comment by TheKonka** [comment]
`Taro.showModal`就是 `wx.showModal`，如果微信支持，那就可以，微信不支持，那只能自己写个 `modal`实现
