### ISSUE TITLE
希望可以支持直接导入wxss文件而不是打包进去

### ISSUE THREAD

**Issue by cos2004** [NervJS/taro#1342]
**问题描述**
在样式文件里引入了公共样式，如@import '../common.scss'，希望在小程序下编译出来的是@import '../common.wxss'，而不是把样式直接打包进目标文件了。这种打包方式会多占用小程序包大小

**复现步骤**
```css
@import '../common.scss';
```

**期望行为**
```css
@import '../common.wxss';
```

**报错信息**
而不是像以下把样式都打包进去：
```css
.common-color {color: #FFF}
```

**系统信息**

 - 操作系统: [e.g. OSX 10.14.1]
 - Taro 版本 [e.g. v.1.1.9]
 - Node.js 版本 [e.g. v8.9.0]
 - 报错平台 [weapp]

**补充信息**
注：这是一个优化点，并非报错了不能用

**Comment by Phlen** [comment]
+1

**Comment by tourze** [comment]
这个特性我觉得是有必要的。现在我用的2.x还是会合并进去

**Comment by tourze** [comment]
目前使用3.x，依然会合并进去。。。
