### ISSUE TITLE
希望支持运行标准的vite项目

### ISSUE THREAD

**Issue by alamhubb** [NervJS/taro#13433]
### 这个特性解决了什么问题？
希望可以运行标准的vite项目，如果这个项目不需要编译到小程序端，则只需安装taro，配置编译命令即可。

如果需要编译到小程序端，则再自己添加配置即可，这样能做到和普通vite项目的完全一致。

降低开发者学习成本，屏蔽非必要的配置项，做到约定优于配置的理念

### 这个 API 长什么样？
同vite标准项目一致，可以运行vite标准项目

**Comment by Tenodec** [comment]
其实倒不如希望将webpack打包换成 vite或者rollup，webpack慢了

**Comment by aolsx** [comment]
+1

**Comment by asciichn** [comment]
+1

**Comment by social-uni** [comment]
https://github.com/NervJS/taro/issues/10125#issuecomment-1157211380
