### ISSUE TITLE
app.config.ts中目前仅能引入CommonJS导出文件，无法引入ESM导出文件。

### ISSUE THREAD

**Issue by WilsonLau0755** [NervJS/taro#13437]
### 相关平台
微信小程序

**小程序基础库: 2.30.0**
**使用框架: Vue 3**

### 复现步骤
1、app.config.ts中通过CommonJS形式引入外部文件，填写到navigationBarTitle中，实现参数剥离。
core.js：
```
module.export.name = '***'
```
app.config.ts：
```
const core = require('./core.js')
export default {
  window: {
    navigationBarTitleText: core.name
  }
}
```

上述方法仍需要将name放在代码包中，因业务调整，希望将name放置在后端数据库中，通过http及前端缓存的方式设置。

2、app.config.ts中通过EMS形式引入外部文件
core.js：
```
export default class Core {
  public name = Taro.getStorageSync('name')
}
```
app.config.ts：
```
import Core from './core.js'
export default {
  window: {
    navigationBarTitleText: new Core().name
  }
}
```
报错如下：
```
SyntaxError: Cannot use import statement outside a module
```
app.config.ts无法通过引入ESM形式文件，仅支持CommonJS，且追溯所有导入依赖。

### 期望结果
app.config.ts能引入ESM

### 实际结果
仅引入CommonJS

### 环境信息
```
Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.11.1 - C:\nvm\nodejs\node.EXE
      npm: 8.0.0 - C:\nvm\nodejs\npm.CMD
```

---
### 补充信息
针对上述问题，对于想要全局配置的navigationTitle，除了每个页面调用setNavigationBarTitleText还有其他方法吗？

**Comment by AdvancedCat** [comment]
`app.config.ts` 文件的用途是输出文件 `app.json` ，所以`app.config.ts`是编译时文件，不可以使用任何运行时特性，网络请求/读缓存这些运行时逻辑实现不了。

此外，报错`SyntaxError `错误的原因是 `app.config.ts` 跳过了 `node_modules` 内依赖的ESM转译，而编译时是 commonjs 环境。

**Comment by WilsonLau0755** [comment]
> 

嗯嗯，我猜想也是这样。对于我所说的那种应用场景，除了每个页面去set，有其他好的方法吗？

**Comment by AdvancedCat** [comment]
app.json 或 页面.json 都是配置类文件，在编译打包时就需要确定的。所以，如果要动态设置的话，就需要在编译时完成，比如在编译时请求网络请求或读取缓存。一旦打包到dist里后，配置就固定了。

**Comment by AdvancedCat** [comment]
`app.config.ts` 内支持第三方依赖转译，待修复~~~
