### ISSUE TITLE
自定义组件的文档标签渲染

### ISSUE THREAD

**Issue by lunyong** [NervJS/taro#1343]
自定义组件在文档渲染的时候，组件名为什么会被当成一个标签名？感觉好奇怪。。。
我现在定义了一个player组件，如下：
`import Taro, { Component } from '@tarojs/taro'
import { Video } from '@tarojs/components'

class Player extends Component {
  render() {
    return (
      `<Video src={this.props.src}></Video>`
    )
  }
}`
然后在页面引用这个组件，如下：
`import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Player from '../../components/player'

export default class Home extends Component {
  render() {
    return (
      `<View className="long-wrapper">
        <Player src="https://vd3.bdstatic.com/mda-ia8e6q3g23py8qdh/hd/mda-ia8e6q3g23py8qdh.mp4?playlist=%5B%22hd%22%5D&auth_key=1521549485-0-0-d5d042ba3555b2d23909d16a82916ebc&bcevod_channel=searchbox_feed&pd=share"></Player>
      </View>`
    )
  }
}`
最后在开发者工具上的文档中是这样的：
![image](https://user-images.githubusercontent.com/10205336/49358782-f661af80-f70e-11e8-9135-4834c406b815.png)
这个video标签外面为什么会包裹一层player标签？很怪异，不应该video把Player给替换了吗？

**Comment by yuche** [comment]
这是使用 shadow-dom 的小程序框架一定存在的问题，`Player` 作为一个独立的组件应该有自己的节点可以在 devtools 单独查看和编辑。我认为这样做是正确的，反之，如果没有才是问题。
