### ISSUE TITLE
基于Taro的微信小程序的源码移植为H5时出现报错

### ISSUE THREAD

**Issue by peitsan** [NervJS/taro#13435]
### 相关平台
H5

### 复现仓库
[git@github.com:peitsan/taro-loader-pr.git](git@github.com:peitsan/taro-loader-pr.git)
**浏览器版本:  Chrome 61**
**使用框架: React**

### 复现步骤
复现步骤
运行 npm run build:h5时，报错“pages.get is not a function”，构建终止。无法打包。
运行 npm run dev:h5时，报错“pages.get is not a function”，构建暂停。 当在app.config.ts文件中按ctrl-s保存时会继续构建

### 期望结果

期望结果
正确将app.config.ts中配置的路由参数转为Map对象返回给 options

### 实际结果
实际结果
构建时报错“pages.get is not a function”，此时options为空对象，
重新保存app.,config.ts后又继续构建build依赖， 此时options中传入了pages 中的Map对象

### 环境信息
```
 Taro v3.5.7

Taro CLI 3.5.7 environment info:
System:
OS: Windows 11
Binaries:
Node: 16.14.0 -F:\node\node.EXE
npm: 8.5.5 - F:\node\npm.CMD
```

---
### 补充信息
昨日已提出PR，代码中有修改的位置

**Comment by peitsan** [comment]
附上报错终端
![image](https://user-images.githubusercontent.com/85779787/224021635-62efc56f-61e4-4048-9c5f-e8d98986ae86.png)

此外还有报错的代码
![image](https://user-images.githubusercontent.com/85779787/224022100-bfafa46a-c2a9-4ed2-a3ba-411ce62d6ee2.png)

**Comment by AdvancedCat** [comment]
在 `v3.5.12` 或 `v3.6.2` 下运行是否正常？

**Comment by peitsan** [comment]
测试后发现 从头开始搭建项目 的话没有这个问题 emm
感觉是 app.config.ts配置分包之后才出现的



在 2023-03-10 14:45:24，"Flame" ***@***.***> 写道：

在 v3.5.12 或 v3.6.2 下运行是否正常？

**Comment by AdvancedCat** [comment]
使用过你的DEMO复现，没有发现 pages.get 方法报错，但因redux文件夹缺少文件而报错。可以先完善一下DEMO，再看看

**Comment by TNT-Likely** [comment]
3.6.3仍然会报这个错误

**Comment by lxp284224387** [comment]
3.6.3的h5.js也有这个问题 

我自己的修正方案是第16行的代码
 `}, ${JSON.stringify((0, helper_1.readConfig)(pages.get(path)))})`;`
变更为
`}, ${JSON.stringify((0, helper_1.readConfig)(new Map(pages).get(path)))})`;`

**Comment by peitsan** [comment]
感谢讨论



在 2023-04-04 16:24:07，"lxp284224387" ***@***.***> 写道：

3.6.3的h5.js也有这个问题

我自己的修正方案是第16行的代码
}, ${JSON.stringify((0, helper_1.readConfig)(pages.get(path)))});变更为}, ${JSON.stringify((0, helper_1.readConfig)(new Map(pages).get(path)))});
