### ISSUE TITLE
希望完善QQ小程序广告类型

### ISSUE THREAD

**Issue by ggpcn** [NervJS/taro#13445]
### 这个特性解决了什么问题？
目前广告组件不支持设置QQ小程序广告的类型。希望可以增加 type 字段。

QQ小程序广告类型：https://q.qq.com/wiki/develop/miniprogram/component/open-ability/ad.html

之前有其他用户提过issue，但实测并未解决，测试type="card"，依然无效。目前最新的3.6.2版本，type类型依然仅支持banner。

### 这个 API 长什么样？
希望能够完善针对QQ小程序广告类型的type字段，目前官方支持的type字段有4个，分别是banner、card、feeds、block。

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/blob/next/packages/taro-qq/src/components.ts

在这个文件里面加下就行，欢迎 PR

**Comment by ggpcn** [comment]
> https://github.com/NervJS/taro/blob/next/packages/taro-qq/src/components.ts
> 
> 在这个文件里面加下就行，欢迎 PR

辛苦大佬抽空帮忙加一下吧。我不是懒，是操作不熟练，担心增加不必要的麻烦。感谢🥰

**Comment by zspggp** [comment]
@ZakaryCode 您好

![1](https://user-images.githubusercontent.com/128504353/229051316-b30ef755-5b64-4eeb-b8b6-254c21fb4030.png)
![2](https://user-images.githubusercontent.com/128504353/229051400-e86ab66d-4733-4334-aa0d-b07807ed55fc.png)
![3](https://user-images.githubusercontent.com/128504353/229051533-a479ea49-e32b-4d2d-ad43-6008ef8ae32d.png)

使用今天刚发布的Taro 3.6.2-canary.2，测试依然不可以，可以帮忙再看一下吗？
