### ISSUE TITLE
内置插件 @tarojs/plugin-platform-qq 无法下载

### ISSUE THREAD

**Issue by weitongpan** [NervJS/taro#13448]
### 相关平台
微信小程序

**小程序基础库: 2.3.73**
**使用框架: React**

### 复现步骤
1、npm install -g @tarojs/cli（全局安装taro脚手架）
2、taro init myApp（初始化脚手架会提示下载依赖错误）
3、cd myApp
4、npm install 或者 yarn

### 期望结果
期待能正常下载依赖

### 实际结果
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for @tarojs/plugin-platform-qq

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - D:\ProgramFiles\nodejs\node.EXE
      Yarn: 1.22.19 - D:\ProgramFiles\nodejs\yarn.CMD
      npm: 6.14.13 - D:\ProgramFiles\nodejs\npm.CMD
```

---
### 补充信息
从公司的git仓库中clone下来项目代码，执行npm install 或者 yarn 报错 找不到@tarojs/plugin-platform-qq插件版本，然后尝试初始化一个全新项目，就根据taro官网快速开始教程，初始化了一个项目，但是下载依赖时同样报错 找不到@tarojs/plugin-platform-qq插件版本

**Comment by Shawn-Cui** [comment]
刚提了个，结果发现已经有了

**Comment by AdvancedCat** [comment]
按以下步骤自查：

1. `npm config list` 查看本地设置的 registry 是啥；
2. 然后提取 registry 运行 `npm info @tarojs/plugin-platform-qq --registry=xxx`
3. 如果超时或异常，则多半跟 registry 有关系了，可以换一个 registry 试试

`npm info @tarojs/plugin-platform-qq --registry=https://registry.npmjs.org/` 是正常的
