### ISSUE TITLE
No valid versions found for "@tarojs/plugin-platform-qq"

### ISSUE THREAD

**Issue by Shawn-Cui** [NervJS/taro#13449]
### 相关平台
微信小程序

**小程序基础库: 2.29.1**
**使用框架: React**

### 复现步骤
taro v3.6.2
taro init myApp

### 期望结果
正确安装依赖

### 实际结果
Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 myApp
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 yarn
? 请选择模板源 Gitee（最快）
✔ 拉取远程模板仓库成功！
? 请选择模板 mobx

✔ 创建项目: koya
✔ 创建文件: /Users/xxx/Develop/weapp/y/.editorconfig
✔ 创建文件: /Users/xxx/Develop/weapp/y/.eslintrc.js

⚠ error No valid versions found for "@tarojs/plugin-platform-qq". The package may be unpublished.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
✖ 安装项目依赖失败，请自行重新安装！
Error: Command failed: yarn install
error No valid versions found for "@tarojs/plugin-platform-qq". The package may be unpublished.

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
```

**Comment by yoyo837** [comment]
Duplicate of #13448
