### ISSUE TITLE
同样用一套样式都是rem写法，小程序和H5不一样，H5被放大了

### ISSUE THREAD

**Issue by q8938036** [NervJS/taro#1344]
**问题描述**
同样用一套样式都是rem写法，小程序和H5不一样，H5被放大了

**复现步骤**
eg:
.user-mobile .text {
    color: #333;
    font-size: 0.8rem;
    line-height: 2.77rem;
    font-weight: bold;
}

**期望行为**
不清楚是什么原因造成了rem差异

**报错信息**
PC浏览器和开发工具中：
![image](https://user-images.githubusercontent.com/22056400/49359440-43df1c00-f711-11e8-8801-cdcad8368bb9.png)
真机微信和H5：
![image](https://user-images.githubusercontent.com/22056400/49359602-a46e5900-f711-11e8-94d9-c810b4c1f7f1.png)

**系统信息**

 - 操作系统: macOs
 - Taro 版本 [ v.0.0.64]
 - Node.js 版本 [v8.11.4]
 - 报错平台 [h5, weapp]

**补充信息**

**Comment by luckyadam** [comment]
没有放大，只是平台不同而已

**Comment by q8938036** [comment]
换成px，利用taro自身的转换机制确实没问题，但是没想到平台差异会导致rem不同。。

**Comment by liling0726** [comment]
> 换成px，利用taro自身的转换机制确实没问题，但是没想到平台差异会导致rem不同。。

我也遇到这个问题，是用的px，但是使用taro编译后，样式变大了，有什么解决方案吗，因为是h5 react想一直成Taro
