### ISSUE TITLE
在构建后可以复制 project.private.config.json 文件到 dist 文件中

### ISSUE THREAD

**Issue by RunningCoderLee** [NervJS/taro#13458]
### 这个特性解决了什么问题？
微信小程序会通过  project.private.config.json 和  project.config.json 这2个文件对项目进行配置，其中 project.private.config.json 的优先级更高，有些个人对项目的配置并不希望放在公共的配置文件  project.config.json 中（比如新增了编译模式等），如果 taro 编译的时候可以把 project.private.config.json 文件也复制到 dist 目录下则可以解决每次编译后，之前配置的项目配置内容就不会丢失

### 这个 API 长什么样？
taro 在构建后可以将项目根目录中的 project.private.config.json 文件内容复制到 dist 目录中，效果同 project.config.json 文件

**Comment by RunningCoderLee** [comment]
是的

**Comment by TheKonka** [comment]
> 是的

个人不推荐这样，您可以直接小程序打开项目根目录，这样`project.private.config.json`文件可以正常识别

**Comment by RunningCoderLee** [comment]
ok，这种方式确实可以解决问题，多谢
