### ISSUE TITLE
win系统为啥我只要一跑 dev:weapp 就会被修改700多个文件？

### ISSUE THREAD

**Issue by zpcgx** [NervJS/taro#13455]
### 相关平台
微信小程序

**小程序基础库: 2.24.6**
**使用框架: Vue 3**

### 复现步骤
为啥我只要一跑 dev:weapp 就会被修改700多个文件？ 并且在git忽略文件中添加了忽略dist文件，变更的文件都是开发目录下面的src/xxx

### 期望结果
不出现这么多文件的变动

### 实际结果
通常git文件变更项700多个 这样开发完自己模块根本没法提交代码

### 环境信息
```
 Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - D:\Nvm\nodejs\node.EXE
      npm: 6.14.7 - D:\Nvm\nodejs\npm.CMD

```

---
### 补充信息
taro info 不生效 复制的别人的

**Comment by zpcgx** [comment]
![c4bf54ee0fbaee60b2fd43ac3511aea](https://user-images.githubusercontent.com/60655571/225507885-f6b79af6-2c7e-4b16-8edf-b8bd911f1fc0.png)

**Comment by zpcgx** [comment]
![ea0202c926d560804fec04c9cd3816a](https://user-images.githubusercontent.com/60655571/225507925-5e5eb410-4966-4430-9864-f39d7f8eda3c.png)

**Comment by zpcgx** [comment]
正确的 taro info

**Comment by yoyo837** [comment]
你看看修改的内容是啥?

**Comment by zpcgx** [comment]
Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\l\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
正确的 taro info

**Comment by zpcgx** [comment]
> 

点开看了  啥修改也没有

**Comment by zpcgx** [comment]
> 你看看修改的内容是啥?

点开看了 一般是啥修改也没有

**Comment by yoyo837** [comment]
检查一下是不是有工具修改`lf`、`crlf`

**Comment by zpcgx** [comment]
> 检查一下是不是有工具修改`lf`、`crlf`

我也在查这个问题 但是没有发现有工具修改了换行符

**Comment by yoyo837** [comment]
搞个demo看看? 我个人这边没遇到

**Comment by zpcgx** [comment]
> 搞个demo看看? 我个人这边没遇到

咱俩可以加个v 然后你远程看看

**Comment by zpcgx** [comment]
> 搞个demo看看? 我个人这边没遇到

BluerBlueBlue

**Comment by yoyo837** [comment]
> > 搞个demo看看? 我个人这边没遇到
> 
> 咱俩可以加个v 然后你远程看看

不太方便

**Comment by yoyo837** [comment]
你放demo, 方便其他人自己找时间看, 远程就捆绑了时间, 大家都挺忙的.

**Comment by zpcgx** [comment]
> 你放demo, 方便其他人自己找时间看, 远程就捆绑了时间, 大家都挺忙的.

公司的项目 我没法往上放 要不然就直接放了

**Comment by yoyo837** [comment]
不是让你复制项目, 你创建一个能复现问题的最小项目即可

**Comment by yoyo837** [comment]
维护开源项目是一项非常辛苦的工作，还请多多包涵。
[了解为什么这么严格？](https://nervjs.github.io/taro-issue-helper/#why-strict)

**Comment by zpcgx** [comment]
> 维护开源项目是一项非常辛苦的工作，还请多多包涵。 [了解为什么这么严格？](https://nervjs.github.io/taro-issue-helper/#why-strict)

是不是taro在win系统下 一跑 dev:weapp就会根据系统改变文件的换行符？ 如果是这样的话能不能关闭

**Comment by yoyo837** [comment]
猜能解决问题就不用挂着900个 issue了

**Comment by zpcgx** [comment]
> 猜能解决问题就不用挂着900个 issue了

已经解决了 git输入三个命令
git config --global core.autocrlf false
git config --global core.filemode false
git config --global core.safecrlf true
然后把项目删了重新仓库拉取就好了 还是win系统换行符导致的

**Comment by yoyo837** [comment]
git scm 新安装时勾选这个, 不行的话, 上面的命令应该也OK.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/6134547/225532946-c7f521f0-19ad-4360-ad4c-8cfce50b91e5.png">
