### ISSUE TITLE
通过url传非字符串参数, 结果获取时参数类型变成字符串

### ISSUE THREAD

**Issue by chenlimao** [NervJS/taro#13454]
### 相关平台
微信小程序

**小程序基础库: 2.30.2**
**使用框架: Vue 3**

###  跳转页面
```
Taro.navigateTo({
        url: `/pages/my-income/index?invitePermission=${this.invitePermission}`
})
```

### 获取参数
getCurrentInstance().router.params

### 期望结果
{invitePermission:  true, $taroTimestamp: 1678876635581}

### 实际结果
{invitePermission:  “true”, $taroTimestamp: 1678876635581}

### 环境信息
```
 Taro CLI 3.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - D:\Nvm\nodejs\node.EXE
      npm: 6.14.7 - D:\Nvm\nodejs\npm.CMD

```

**Comment by TheKonka** [comment]
url 传参都是字符串格式，你用原生微信小程序也是一样的效果
