### ISSUE TITLE
h5端使用lodash-es报错TypeError: __webpack_require__.hmd is not a

### ISSUE THREAD

**Issue by jiayafei** [NervJS/taro#13450]
### 相关平台
H5

**浏览器版本: Microsoft Edge版本 110.0.1587.69**
**使用框架: React**

### 复现步骤
正常下载taro 使用react版本引入taro-ui
然后引入import { last, replace, split, startsWith } from 'lodash-es';方法，
console.log("test",split("1,2,3",','))
yarn dev:h5 后浏览器报错

### 期望结果
正常运行

### 实际结果
无非运行

### 环境信息
```
👽 Taro v3.5.4


  Taro CLI 3.5.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\happy.jia\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    "lodash-es": "^4.17.21",
```

**Comment by catnuko** [comment]
我在代码里用taro.request就会报错` __webpack_require__.hmd is not a function`

**Comment by ZakaryCode** [comment]
无意中复现了该问题，与 prebundle 能力相关，应当是 remote app 打包时缺少对应函数导致

> 可以先屏蔽对应依赖加入预编译
