### ISSUE TITLE
编译成钉钉小程序后，除了View和Text，其他组件均不显示

### ISSUE THREAD

**Issue by adufeng** [NervJS/taro#13478]
### 相关平台
钉钉小程序

### 复现仓库
[https://gitee.com/duuuui/taro-test.git](https://gitee.com/duuuui/taro-test.git)

**使用框架: React**

### 复现步骤
1.初始化Taro项目
2.安装@tarojs/plugin-platform-alipay-dd插件
3.打包生成钉钉小程序，在开发工具中不展示Button按钮

### 期望结果
正常渲染Button

### 实际结果
未正常渲染

### 环境信息
```
  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1
      @tarojs/components: 3.6.1 => 3.6.1
      @tarojs/helper: 3.6.1 => 3.6.1
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1
      @tarojs/react: 3.6.1 => 3.6.1
      @tarojs/runtime: 3.6.1 => 3.6.1
      @tarojs/shared: 3.6.1 => 3.6.1
      @tarojs/taro: 3.6.1 => 3.6.1
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1
      babel-preset-taro: 3.6.1 => 3.6.1
      eslint-config-taro: 3.6.1 => 3.6.1
      react: ^18.0.0 => 18.2.0
```

**Comment by adufeng** [comment]
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/52154350/226500187-3c99f710-b10d-4f99-b014-8f87c5bea9ad.png">
经测试，除了view和text，其他组件全部都编译不出来

**Comment by adufeng** [comment]
发现是编译的问题，使用webpack5不能正常编译，webpack4就可以正常编译

**Comment by Chen-jj** [comment]
> 发现是编译的问题，使用webpack5不能正常编译，webpack4就可以正常编译

@adufeng 感谢反馈~发现是 Webpack5 对 `export * from` 语法的处理改变了，导致内部的 AST 分析出错

例如：

```js
// index.js
import { View } from 'B'

// module B
export * from 'A'
```

Webpack5 编译后：

```js
// index.js
var module_A = require('A') // 被 Webpack 处理为直接从 A 取
var View = module_A['View']
```

Webpack4 编译后：

```js
// index.js
var module_B = webpack_require('B') // 仍然保留从 B 模块中取值
var View = module_B['View']

// module B
var module_A = webpack_require('A')
webpack_export(module_A['View])
```

**Comment by xiayifeng** [comment]
插件预计什么时候修复啊？

**Comment by Chen-jj** [comment]
> 插件预计什么时候修复啊？

刚发了 v0.2.0，应该待会就生效了

**Comment by adufeng** [comment]
> > 插件预计什么时候修复啊？
> 
> 刚发了 v0.2.0，应该待会就生效了

大佬，npm已经更新上了，能否更新下yarn的 ( Ĭ ^ Ĭ )

**Comment by yoyo837** [comment]
那是yarn自行同步的吧?

**Comment by adufeng** [comment]
> 那是yarn自行同步的吧?

大佬，一般多同步一次啊，这都两天了😭

**Comment by Chen-jj** [comment]
> Taro 钉钉插件编译不渲染部分组件 NervJS/taro-plugin-platform-alipay-dd#20

为了不影响 treeshaking，再调整了一下，不关闭 `optimization.providedExports` 选项。改为调整钉钉插件的 rollup 配置。插件已发布 v0.3.0 版本.

**Comment by bigmeow** [comment]
> > Taro 钉钉插件编译不渲染部分组件 [NervJS/taro-plugin-platform-alipay-dd#20](https://github.com/NervJS/taro-plugin-platform-alipay-dd/issues/20)
> 
> 为了不影响 treeshaking，再调整了一下，不关闭 `optimization.providedExports` 选项。改为调整钉钉插件的 rollup 配置。插件已发布 v0.3.0 版本.

这同时还解决了这个问题: https://github.com/NervJS/taro-plugin-platform-alipay-dd/issues/23

真是及时雨

**Comment by pakjeon** [comment]
太好啦，查了一个多小时才想起来这里翻翻，果然找到答案 ~ 钉钉小程序相关的开发者可真少
