### ISSUE TITLE
useDidShow渲染销毁问题

### ISSUE THREAD

**Issue by Jairwin-L** [NervJS/taro#13473]
### 相关平台
微信小程序

**小程序基础库: 2.30.2**
**使用框架: React**

### 复现步骤
需要真机预览：
1、2个tabbar切换：从【测试tab】切回【首页tab】，【首页tab】的页面会先展示正常的页面（像是闪一下的感觉），然后再是loading，最后才是请求完接口页面展示
2、【首页tab】进入非tab页面，这里非tab页面指【其他页面】：从【首页tab】按钮进入【其他页面】，然后再点击左上角返回按钮，页面渲染情况也是按照【1】所述那样发生
这个怎么上传视频？

复现repo：git@github.com:Jairwin-L/taro-debug.git

### 期望结果
无论是进入tabbar页面还是非tabbar页面，期望先loading，接口正常则展示正常页面，异常则显示异常页面

### 实际结果
会先展示正常的页面，然后再是loading，最后才是请求完接口页面展示

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 
      @tarojs/plugin-html: ^3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/react: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
目前认为是useDidShow有点问题

**Comment by TheKonka** [comment]
是你的写法问题，`tabbar`页面不会因为页面切换而销毁，虽然你打开了别的页面，但是首页代码还在运行， `loading` 变成了`false` ,所以你返回到首页，就会看到正常的页面，然后你`useModel`里面又把`loading`改成`true`了，这样在恰当的情况下就会出现闪一下的效果

**Comment by Jairwin-L** [comment]
有什么解法或者思路可以参考的嘛？看了下文档：https://docs.taro.zone/docs/react-page#componentdidhide-
这个对应的是类组件写法，函数式是否可以参考改造？

**Comment by TheKonka** [comment]
> 有什么解法或者思路可以参考的嘛？看了下文档：https://docs.taro.zone/docs/react-page#componentdidhide- 这个对应的是类组件写法，函数式是否可以参考改造？



函数组件对应的是 [useDidHide](https://docs.taro.zone/docs/hooks#usedidhide)

**Comment by Jairwin-L** [comment]
> > 有什么解法或者思路可以参考的嘛？看了下文档：https://docs.taro.zone/docs/react-page#componentdidhide- 这个对应的是类组件写法，函数式是否可以参考改造？
> 
> 函数组件对应的是 [useDidHide](https://docs.taro.zone/docs/hooks#usedidhide)

尝试了下，好像没看到效果？https://github.com/Jairwin-L/taro-debug/commit/6f90946539143f9a0112380ed8df98cc8242f054
<img width="2137" alt="image" src="https://user-images.githubusercontent.com/32570960/226292886-cbb9f902-c5ab-4cbd-9087-67c2993567ef.png">
麻烦再帮忙瞧瞧🙏

**Comment by TheKonka** [comment]
```ts
export default function useModel() {
	const [loading, setLoading] = useState<boolean>(true);
	const [resp, setResp] = useState<any>();
	const [isShow, setIsShow] = useState<boolean>(false);

	useEffect(() => {
		let didCancel = false;
		async function fetchData() {
			setLoading(true);
			const response = await testAjax();
			if (isShow && !didCancel) {
				setLoading(false);
				setResp(response);
			}
		}
		if (isShow) {
			fetchData();
		}

		return () => {
			didCancel = true;
		};
	}, [isShow]);

	useDidShow(() => {
		setIsShow(true);
	});
	useDidHide(() => {
		setLoading(true);
		setIsShow(false);
	});
	return {
		...resp,
		loading,
	};
}
```
