### ISSUE TITLE
Taro3 中使用vue css v-bind 获取对象类型数据错误

### ISSUE THREAD

**Issue by songxianling** [NervJS/taro#13497]
### 相关平台
微信小程序

**小程序基础库: 2.30.2**
**使用框架: Vue 3**

### 复现步骤
使用最简单的写法
````
<template>
  <view class="coupon-page-wrap">
    index
    <view class="inner-box">inner-box</view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const menuBtnInfo = ref<any>({
  width: '20px'
})

/** 设置页面属性 */
definePageConfig({
  navigationBarTitleText: 'index',
  navigationBarBackgroundColor: '#FEAA00'
})
</script>

<style lang="scss">
.coupon-page-wrap {
  .inner-box {
    background: yellow;
    padding: 10px;
    width: v-bind('menuBtnInfo.width');
  }
}
</style>


````
### 期望结果
能编辑出 20px 的效果

### 实际结果
得不到

### 环境信息
```
Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5
      @tarojs/components: 3.5.5 => 3.5.5
      @tarojs/helper: 3.5.5 => 3.5.5
      @tarojs/mini-runner: 3.5.5 => 3.5.5
      @tarojs/plugin-framework-vue3: 3.5.5 => 3.5.5
      @tarojs/plugin-html: 3.5.5 => 3.5.5
      @tarojs/plugin-mini-ci: ^3.5.5 => 3.5.5
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5
      @tarojs/plugin-vue-devtools: ^3.5.6 => 3.6.0
      @tarojs/router: 3.5.5 => 3.5.5
      @tarojs/runtime: 3.5.5 => 3.5.5
      @tarojs/shared: 3.5.5 => 3.5.5
      @tarojs/taro: 3.5.5 => 3.6.0
      @tarojs/taro-h5: 3.5.5 => 3.5.5
      @tarojs/webpack-runner: 3.5.5 => 3.5.5
      babel-preset-taro: 3.5.5 => 3.5.5
      eslint-config-taro: 3.5.5 => 3.5.5
    npmGlobalPackages:
      typescript: 4.8.3
```

**Comment by yoyo837** [comment]
提供repo.

**Comment by songxianling** [comment]
最小复现仓库 https://github.com/songxianling/taro-vbind-repoo

**Comment by yoyo837** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/6134547/227094094-969c0e4f-cf6d-4f2e-bc54-4fce205fa0e1.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/6134547/227094188-0b289c14-6c1c-4d7f-8a2f-35ac160490d5.png">

**Comment by yoyo837** [comment]
在小程序中不允许`--46605aa0-menuBtnInfo\.width` 这种 `\.`的名字, 应该是编译名称不兼容.

**Comment by songxianling** [comment]
> 提供最小可复现repo.

**Comment by songxianling** [comment]
> 在小程序中不允许`--46605aa0-menuBtnInfo\.width` 这种 `\.`的名字, 应该是编译名称不兼容.

正常是不会编辑出来 . 或者 \ 这样的内容的；所以还是哪里编译问题！
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/16551088/227124038-1afd2588-f7ff-4bb8-bd3f-e375663a8000.png">
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/16551088/227124072-5eb656c4-661b-4da8-beb6-7e7d7ea518a6.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/16551088/227124201-4d5d1a88-287b-4da6-a267-66b7be9bbec5.png">
应该是类似这样的编辑结果才对！

**Comment by xuanzebin** [comment]
看了一下 vue 的源码，在使用 v-bind 的时候，会判断当前的环境是 prod 还是 dev，然后采取不同的 css var 变量名生成逻辑：
```js
function genVarName(id: string, raw: string, isProd: boolean): string {
  if (isProd) {
    return hash(id + raw)
  } else {
    return `${id}-${raw.replace(/([^\w-])/g, '_')}`
  }
}
```

然后 dev 环境下生成的变量名由于 vue 这边没有考虑到小程序的存在，所以不太兼容小程序环境，因此你可以通过将 NODE_ENV 设置成 production，将该方法切换至 hash 模式解决样式不生效的问题：
`NODE_ENV=production taro build --type weapp --watch`
