### ISSUE TITLE
微信小程序端 config 中的配置使用变量，编译报错

### ISSUE THREAD

**Issue by kycool** [NervJS/taro#1350]
因为有些路由我需要写到常量中去，这样在其他业务中直接使用常量即可，但是在 config 直接使用变量，编译报错

版本：taro 最新的 beta 版本

```js
const pagesOut = [
  'pages/Home/index',
  'pages/user/index',
  'pages/order/index',
  'pages/order/detail',
]

class App extends Component {

  config = {
    pages: pagesOut,
```

报错情况
```js
app.json 中定义的 pages : []
```

是有限制还是我的写法不对，还是？？？？

**Comment by luckyadam** [comment]
config 只支持静态书写，不支持抽成变量

**Comment by yf287** [comment]
> config 只支持静态书写，不支持抽成变量

原谅我挖坟，50+页面的项目，不抽出来的话，启动文件中会光是页面配置就要占很多行，不便于维护呀

**Comment by raykle** [comment]
> > config 只支持静态书写，不支持抽成变量
> 
> 原谅我挖坟，50+页面的项目，不抽出来的话，启动文件中会光是页面配置就要占很多行，不便于维护呀

最新版的好像还是不支持？
