### ISSUE TITLE
使用redux设置类型为对象的数据有问题

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#1351]
**问题描述**
升级到比1.0.7高的版本后（如1.1.9），redux设置对象数据时，componentWillReceiveProps里返回的nextProps与实际设置的状态不一致。

**复现步骤**

```js
// 原始的state
const initialState = {
  userInfo: null,
  showAuthModal: false,
};

// 进行操作设置userInfo，userInfo是object类型的
this.props.dispatch(setUserInfo(data.data));

// 在componentWillReceiveProps中打印nextProps
componentWillReceiveProps(nextProps) {
    console.log('componentWillReceiveProps data', nextProps);
  }

```
如下图，能看到redux log出来的数据 跟componentWillReceiveProps中返回的数据是不一样的
![image](https://user-images.githubusercontent.com/22128204/49368839-cf18db80-f72a-11e8-8c46-ac6cde5e3354.png)

**系统信息**
 - Taro 版本 [1.1.9] （1.0.7版本无此问题，大于1.0.7的都有）

**Comment by xingBri** [comment]
这个问题影响会比较大，可能造成的问题会比较多

**Comment by luckyadam** [comment]
请提供一个比较完整的可测试项目吧

**Comment by xingBri** [comment]
> 请提供一个比较完整的可测试项目吧

好的 我今天找个时间开个项目给你们

**Comment by luckyadam** [comment]
> > 请提供一个比较完整的可测试项目吧
> 
> 好的 我今天找个时间开个项目给你们

好嘞，多谢

**Comment by xingBri** [comment]
hello，前几天比较忙，今天终于可以把测试项目给出来了
这是我从原项目抽离出来的，只保留了能复现我说的bug的功能
希望能帮助你们找到问题
项目地址：https://github.com/xingBri/testTaro

> > > 请提供一个比较完整的可测试项目吧
> > 
> > 
> > 好的 我今天找个时间开个项目给你们
> 
> 好嘞，多谢

hello，前几天比较忙，今天终于可以把测试项目给出来了
这是我从原项目抽离出来的，只保留了能复现我说的bug的功能
希望能帮助你们找到问题
项目地址：https://github.com/xingBri/testTaro

**Comment by xingBri** [comment]
> > > 请提供一个比较完整的可测试项目吧
> > 
> > 
> > 好的 我今天找个时间开个项目给你们
> 
> 好嘞，多谢

hello，前几天比较忙，今天终于可以把测试项目给出来了
这是我从原项目抽离出来的，只保留了能复现我说的bug的功能
希望能帮助你们找到问题
项目地址：https://github.com/xingBri/testTaro

**Comment by xingBri** [comment]
> > > 请提供一个比较完整的可测试项目吧
> > 
> > 
> > 好的 我今天找个时间开个项目给你们
> 
> 好嘞，多谢

hello 请问这个问题现在有什么跟进进展吗

**Comment by shenghanqin** [comment]
@xingBri 可以试试最新版的1.3.22还有这个问题吗？
