### ISSUE TITLE
Text组件嵌套太多层后在百度小程序无法显示

### ISSUE THREAD

**Issue by Bruce-Ming** [NervJS/taro#13511]
### 相关平台
百度小程序

### 复现仓库
[https://github.com/Bruce-Ming/taro-baidu-text.git](https://github.com/Bruce-Ming/taro-baidu-text.git)
**小程序基础库: 百度小程序3.660.2**
**使用框架: React**

### 复现步骤
嵌套层次太多的Text标签就无法显示出来，具体看git地址

### 期望结果
嵌套的Text能正常带样式显示出来

### 实际结果
嵌套的标签无法显示

### 环境信息
```

  Taro CLI 3.6.0 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.4.1 - ~/.nvm/versions/node/v16.4.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.4.1/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.4.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.0 => 3.6.0 
      @tarojs/components: 3.6.0 => 3.6.0 
      @tarojs/helper: 3.6.0 => 3.6.0 
      @tarojs/plugin-framework-react: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-alipay: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-h5: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-jd: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-qq: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-swan: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-tt: 3.6.0 => 3.6.0 
      @tarojs/plugin-platform-weapp: 3.6.0 => 3.6.0 
      @tarojs/react: 3.6.0 => 3.6.0 
      @tarojs/runtime: 3.6.0 => 3.6.0 
      @tarojs/shared: 3.6.0 => 3.6.0 
      @tarojs/taro: 3.6.0 => 3.6.0 
      @tarojs/webpack5-runner: 3.6.0 => 3.6.0 
      babel-preset-taro: 3.6.0 => 3.6.0 
      eslint-config-taro: 3.6.0 => 3.6.0 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.4 => 3.1.0-beta.4 
    npmGlobalPackages:
      typescript: 5.0.2

```

**Comment by Bruce-Ming** [comment]
另外发现Text嵌套以后，第三层以后的点击事件都没有正确绑定，点击事件无法触发
![image](https://user-images.githubusercontent.com/37186519/227480106-46356cd7-cdee-4297-b16a-b2c33d3b339d.png)

**Comment by yuconora** [comment]
[百度小程序Text组件的bug](https://smartprogram.baidu.com/docs/develop/component/base_text/#bug-tip)
![image](https://user-images.githubusercontent.com/14029094/227840277-8e778752-17e8-4d15-8eaa-6ab116339fbf.png)
如果没有文本格式解析的需求 尽量使用 view组件做嵌套

**Comment by Bruce-Ming** [comment]
另外发现问题Taro.createSelectorQuery().in(this) 方法在组件中失效,并且没有提供函数组件的使用方法
![image](https://user-images.githubusercontent.com/37186519/228198209-893082c0-b87b-4f0f-bcf3-ec1a42dc6e89.png)
具体可查看上面的github代码库

**Comment by Chen-jj** [comment]
@Bruce-Ming Taro v3.6.3 开始可以设置百度小程序 Text 组件的循环层数，默认为 3 层，可以根据项目情况来改变。

例子：

```js
const config = {
  // other Taro configs
  plugins: [
    ['@tarojs/plugin-platform-swan', {
      flattenTextLevel: 5
    }]
  ]
}
```

**Comment by Chen-jj** [comment]
> 另外发现Text嵌套以后，第三层以后的点击事件都没有正确绑定，点击事件无法触发，此问题在微信小程序上复现。 ![image](https://user-images.githubusercontent.com/37186519/227480106-46356cd7-cdee-4297-b16a-b2c33d3b339d.png)

这个应该是小程序本身的限制，你可以用原生 demo 测试下

```js
Page({
  a () {
    console.log('第一层点击');
  },
  b () {
    console.log('第2层点击');
  },
  c () {
    console.log('第3层点击');
  },
  d () {
    console.log('第4层点击');
  },
  e () {
    console.log('第5层点击');
  }
})
```

```xml
<view class='index'>
  <view>以下嵌套文本百度无法显示</view>
  <text bindtap="a">
    第一层
    <text style='background:blue' bindtap="b">
      第二层
      <text style='background:red' bindtap="c">
        第三层
        <text bindtap="d">
          第四层
          <text bindtap="e">第五层</text>
        </text>
      </text>
    </text>
  </text>
</view>
```

**Comment by Chen-jj** [comment]
> 另外发现问题Taro.createSelectorQuery().in(this) 方法在组件中失效,并且没有提供函数组件的使用方法 ![image](https://user-images.githubusercontent.com/37186519/228198209-893082c0-b87b-4f0f-bcf3-ec1a42dc6e89.png) 具体可查看上面的github代码库

这里的组件是 React 组件，不是小程序自定义组件，因此不需要加 `.in(this)`

**Comment by Bruce-Ming** [comment]
> 

那请问如何做到在react 组件内只测量自身元素的长宽高，不测量相同的其他组件的呢？有很多相同的子组件。

**Comment by Chen-jj** [comment]
你给DOM节点不同的 id 就可以了吧

**Comment by Bruce-Ming** [comment]
新的问题，使用dangerouslySetInnerHTML方法中的富文本的层级太多还是会丢失部分文本https://github.com/Bruce-Ming/taro-baidu-text/blob/main/screenshot-20230613-143955.png
具体请看https://github.com/Bruce-Ming/taro-baidu-text.git库

**Comment by lupingW** [comment]
> 

微信和支付宝怎么办, Text三层后也没办法点击
