### ISSUE TITLE
onClick点击事件中，event.target === event.currentTarget 永远为false

### ISSUE THREAD

**Issue by SupermanChao** [NervJS/taro#13520]
### 这个特性解决了什么问题？
可以在onClick时间中判断是点击的自己，还是子元素冒泡上来的

### 这个 API 长什么样？
点击自己的时候，event.target === event.currentTarget 为true，点击子元素的时候，event.target === event.currentTarget 为false

**Comment by ZakaryCode** [comment]
问题说明缺少关键信息描述，具体编译平台以及当前实际情况等。
