### ISSUE TITLE
taro 后续是否考虑兼容微信官方跨端 Donut

### ISSUE THREAD

**Issue by ChelesteWang** [NervJS/taro#13534]
### 这个特性解决了什么问题？
taro 后续是否考虑兼容微信官方跨端 Donut https://dev.weixin.qq.com/docs/framework/dev/framework/operation/project-intro.html

### 这个 API 长什么样？
taro 后续是否考虑兼容微信官方跨端 Donut https://dev.weixin.qq.com/docs/framework/dev/framework/operation/project-intro.html

**Comment by Chen-jj** [comment]
将保持关注，可目前还没有兼容的想法。
