### ISSUE TITLE
multiPlatformPlugin多端文件场景，在taro依赖的依赖场景下并没有引用成功

### ISSUE THREAD

**Issue by liuguangyong93** [NervJS/taro#13530]
### 相关平台
微信小程序

**小程序基础库: 微信小程序2.52.2**
**使用框架: React**

### 复现步骤
通过monorepo管理业务taro跨端外部包并发至公司内部npm服务器上，比如taro-core-location（location.js,location.weapp.js）、taro-core-request（request.js,request.weapp.js）。其中，taor-core-location/location.weapp.js中需要引入taro-core-reuqest/request.weapp.js，但是taro项目中进行编译时，对于外部依赖包的依赖包并没有分端编译

### 期望结果
taor-core-location/location.weapp.js中引入taro-core-reuqest/request.weapp.js

### 实际结果
taor-core-location/location.weapp.js中需要引入taro-core-reuqest/request.js

![image](https://user-images.githubusercontent.com/15274523/228178227-14227cd6-f99e-4a15-9b64-88f0ece223d3.png)

### 环境信息
```
Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.3 => 3.3.3 
      @tarojs/components: 3.3.3 => 3.3.3 
      @tarojs/mini-runner: 3.3.3 => 3.3.3 
      @tarojs/react: 3.3.3 => 3.3.3 
      @tarojs/runtime: 3.3.3 => 3.3.3 
      @tarojs/taro: 3.3.3 => 3.3.3 
      @tarojs/webpack-runner: 3.3.3 => 3.3.3 
      babel-preset-taro: 3.3.3 => 3.3.3 
      eslint-config-taro: 3.3.3 => 3.3.3 
      react: 17.0.2 => 17.0.2 
      taro-ui: ^2.3.4 => 2.3.4 
    npmGlobalPackages:
      typescript: 4.5.4
```

**Comment by liuguangyong93** [comment]
@Chen-jj 大佬，帮我看一下这个multiPlatform问题

**Comment by Chen-jj** [comment]
@liuguangyong93 可以参考文档配置一下：https://docs.taro.zone/docs/envs#%E8%A7%A3%E6%9E%90-node_modules-%E5%86%85%E7%9A%84%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6

**Comment by liuguangyong93** [comment]
> @liuguangyong93 可以参考文档配置一下：https://docs.taro.zone/docs/envs#%E8%A7%A3%E6%9E%90-node_modules-%E5%86%85%E7%9A%84%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6

单纯的子包node_modules是没问题的，现在是依赖的依赖没有引用指定平台文件

**Comment by liuguangyong93** [comment]
![image](https://user-images.githubusercontent.com/15274523/228232633-c227b3b8-6d34-4d87-996e-611e2c2a52d0.png)
![image](https://user-images.githubusercontent.com/15274523/228232693-ca733066-71ec-455c-9341-6eb1719dd04b.png)

@Chen-jj

**Comment by liuguangyong93** [comment]
项目中引用语法import { a } from 'somePackage'只会在helper中resolveMainFilePath方法中，触达".../node_modules/somePackage"路径，其实是需要".../node_modules/somePackage/dist/"路径下才可以拼接成功。如图三
![taro源码](https://m.hellobike.com/resource/helloyun/17201/zWmDW_helper-utils.png?x-oss-process=image/quality,q_80)

![dont work](https://m.hellobike.com/resource/helloyun/17201/yZ1g6_monorepo_dont-work.png?x-oss-process=image/quality,q_80)

![work](https://m.hellobike.com/resource/helloyun/17201/S7vcP_mono_work.png?x-oss-process=image/quality,q_80)

**Comment by liuguangyong93** [comment]
> 项目中引用语法import { a } from 'somePackage'只会在helper中resolveMainFilePath方法中，触达".../node_modules/somePackage"路径，其实是需要".../node_modules/somePackage/dist/"路径下才可以拼接成功。如图三 ![taro源码](https://camo.githubusercontent.com/0da8eaffa717ef0f676f80e6921acf00d433af423822b1757fd26890da48ac60/68747470733a2f2f6d2e68656c6c6f62696b652e636f6d2f7265736f757263652f68656c6c6f79756e2f31373230312f7a576d44575f68656c7065722d7574696c732e706e673f782d6f73732d70726f636573733d696d6167652f7175616c6974792c715f3830)
> 
> ![dont work](https://camo.githubusercontent.com/a50da523a7022c67d48ad2a53dfce29d43226aadcf576da52022bc1789f54b4a/68747470733a2f2f6d2e68656c6c6f62696b652e636f6d2f7265736f757263652f68656c6c6f79756e2f31373230312f795a3167365f6d6f6e6f7265706f5f646f6e742d776f726b2e706e673f782d6f73732d70726f636573733d696d6167652f7175616c6974792c715f3830)
> 
> ![work](https://camo.githubusercontent.com/a6d1662501d305275030ad5ce934cce4944f56d72679172c9c1a1dffe9c3b198/68747470733a2f2f6d2e68656c6c6f62696b652e636f6d2f7265736f757263652f68656c6c6f79756e2f31373230312f53377663505f6d6f6e6f5f776f726b2e706e673f782d6f73732d70726f636573733d696d6167652f7175616c6974792c715f3830)

调试下来是这样的 @Chen-jj

**Comment by jiangmengjie957** [comment]
> @liuguangyong93 可以参考文档配置一下：https://docs.taro.zone/docs/envs#%E8%A7%A3%E6%9E%90-node_modules-%E5%86%85%E7%9A%84%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6

@Chen-jj 你好我想请问一下，我按照文档配置了模块，在模拟器上能够成功跑通，但在真机调试时仍旧未解析weapp.tsx的文件是什么原因
