### ISSUE TITLE
Taro 3.6.2 使用webpack5，H5端报错 "Cannot read properties of undefined (reading 'isProxied')"

### ISSUE THREAD

**Issue by binz-i** [NervJS/taro#13533]
### 相关平台
H5

### 复现仓库
[https://gitee.com/bin-gitee/taro-h5.git](https://gitee.com/bin-gitee/taro-h5.git)
**使用框架: React**

### 复现步骤
运行yarn dev:h5，第一次可能不复现，没报错的话多运行几次，会报“Cannot read properties of undefined (reading 'isProxied')"错误

### 期望结果
H5端不报错

### 实际结果
报“Cannot read properties of undefined (reading 'isProxied')"错误

### 环境信息
```
  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.20.0 - C:\Users\Windows 10\AppData\Local\nvs\default\node.EXE
      Yarn: 1.22.19 - C:\Users\Windows 10\AppData\Local\nvs\default\yarn.CMD
      npm: 6.14.17 - C:\Users\Windows 10\AppData\Local\nvs\default\npm.CMD
```

**Comment by TheKonka** [comment]
没有复现
相关 https://github.com/ionic-team/stencil/issues?q=isProxied

**Comment by binz-i** [comment]
> 

第一次不会出现这个错误，这个错误是偶发性的，多跑几次就有

**Comment by binz-i** [comment]
> 没有复现 相关 https://github.com/ionic-team/stencil/issues?q=isProxied

第一次不会出现这个错误，这个错误是偶发性的，多跑几次就有

**Comment by endif2016** [comment]
遇到了 
复现路径 taro init myapp, 选react, github, pnpm, sass, 模板选择 taro-hooks
config里的index.js文件中  cache.enable 设为true。运行 pnpm dev:h5

**Comment by ZakaryCode** [comment]
> 遇到了
> 复现路径 taro init myapp, 选react, github, pnpm, sass, 模板选择 taro-hooks
> config里的index.js文件中 cache.enable 设为true。运行 pnpm dev:h5

说下版本并提供下完整 demo ，仅靠该表述无法复现

**Comment by eat-happy** [comment]
![image](https://user-images.githubusercontent.com/34129948/236973924-e2d603a8-0d16-447c-975b-e78c48919ca4.png)
错误频率很高

**Comment by eat-happy** [comment]
taro 版本3.4.12
react

**Comment by eat-happy** [comment]
![image](https://user-images.githubusercontent.com/34129948/236978936-d17efff7-7a56-42a8-8be6-0f263fc03184.png)
定位到是这个位置

**Comment by wenlittleoil** [comment]
生产环境也会出现```TypeError Cannot read properties of undefined (reading 'isProxied')```
