### ISSUE TITLE
混合开发 从Taro项目外引入组件，作为完整子包打入原生项目。taro页面报错TypeError

### ISSUE THREAD

**Issue by AnthonyHao** [NervJS/taro#13537]
### 相关平台
微信小程序

**小程序基础库: 2.20.2**
**使用框架: React**

### 复现步骤
1. https://github.com/AnthonyHao/taro-snippets/tree/next/examples/blended-basic
2. 在taro文件夹外面有一个用taro写的组件Tile（处于原生项目中，原生项目也安装了taro, react）。
3. config/index.js的alias中配置了组件路径
4. 在taro项目的页面 demo 中引用组件Tile
5. 跑命令 "taro build --type weapp --blended" 把taro项目作为完整子包打入项目
6. 在原生项目中查看demo页面

### 期望结果
demo页面可以打开，正常展示内容。

### 实际结果
demo 页面报错 ‘Cannot read property 'useState' of null’。
在组件Tile文件中，将"useState, useEffect"引用都注释掉，可以正常打开。
如果将taro写的组件Tile，复制到taro文件夹内再跑"taro build --type weapp --blended" ，则可以正常打开页面。（如果用ln -s的软链接，再跑命令，同样会报错）

### 环境信息
```
  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.11 => 3.5.11
      @tarojs/components: 3.5.11 => 3.5.11
      @tarojs/helper: 3.5.11 => 3.5.11
      @tarojs/plugin-framework-react: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-alipay: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-jd: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-qq: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-swan: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-tt: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-weapp: 3.5.11 => 3.5.11
      @tarojs/react: 3.5.11 => 3.5.11
      @tarojs/router: 3.5.11 => 3.5.11
      @tarojs/runtime: 3.5.11 => 3.5.11
      @tarojs/shared: 3.5.11 => 3.5.11
      @tarojs/taro: 3.5.11 => 3.5.11
      @tarojs/taro-h5: 3.5.11 => 3.5.11
      @tarojs/webpack5-runner: 3.5.11 => 3.5.11
      babel-preset-taro: 3.5.11 => 3.5.11
      eslint-config-taro: 3.5.11 => 3.5.11
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
在组件Tile文件中，将"useState, useEffect"引用都注释掉，可以正常打开。
如果将taro写的组件Tile，复制到taro文件夹内再跑"taro build --type weapp --blended" ，则可以正常打开页面。（如果用ln -s的软链接，再跑命令，同样会报错）

**Comment by xuanzebin** [comment]
这边没能复现问题，能正常打开 demo 页，且控制台没有发现报错，麻烦升级到最新版本的 Taro 试一下，如果还有问题再进一步反馈~

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/38971117/230839687-6fc0f585-209b-4b47-b1e7-e5333cba3f0b.png">

**Comment by enjkvbej** [comment]
我也遇到相同问题，请问解决了吗

**Comment by duyanren** [comment]
+1
