### ISSUE TITLE
taro 升级最新版本后编译时报错

### ISSUE THREAD

**Issue by jackajin** [NervJS/taro#13532]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
TypeScript's TSX syntax interprets arrow functions with a single generic type parameter as an opening JSX element. If you want it to be interpreted as an arrow function instead, you need to add a trailing comma after the type parameter to disambiguate:

    src/utils/helper/common.ts:115:39:
      115 │ ... const addOrRemoveItemFromList = <T>(arr: T[], item: T): T[] => {
          │                                     ~~~
          ╵                                     <T,>

[ERROR] Unexpected "const"

    src/utils/helper/common.ts:116:2:
      116 │   const newArr = [...arr]
          ╵   ~~~~~

✘ [ERROR] The character ">" is not valid inside a JSX element

    src/utils/helper/common.ts:115:68:
      115 │ ... const addOrRemoveItemFromList = <T>(arr: T[], item: T): T[] => {
          ╵

### 期望结果
控制台无其他报错信息

### 实际结果
控制台在编译的时候报错

### 环境信息
```
Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2
      @tarojs/components: 3.6.2 => 3.6.2
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2
      @tarojs/plugin-mini-ci: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2
      @tarojs/react: 3.6.2 => 3.6.2
      @tarojs/runtime: 3.6.2 => 3.6.2
      @tarojs/taro: 3.6.2 => 3.6.2
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2
      babel-preset-taro: 3.6.2 => 3.6.2
      eslint-config-taro: 3.6.2 => 3.6.2
      react: 18.2.0 => 18.2.0
```

**Comment by yoyo837** [comment]
看看你的配置, 源码是ts, babel是否配置了ts?

**Comment by jackajin** [comment]
module.exports = { presets: [['taro', { framework: 'react', ts: true }]] }

**Comment by jackajin** [comment]
> 看看你的配置, 源码是ts, babel是否配置了ts?

babel 的配置.---  module.exports = { presets: [['taro', { framework: 'react', ts: true }]] }

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/12275#issuecomment-1211577324
