### ISSUE TITLE
Taro 3.6.2 初始化项目后跑不起来

### ISSUE THREAD

**Issue by NaturalGao** [NervJS/taro#13544]
### 相关平台
微信小程序

**小程序基础库: 2.30.2**
**使用框架: React**

### 复现步骤
初始化项目-》React->Sass->Webpack5->npm->Github-》默认模板

### 期望结果
项目跑起来

### 实际结果
项目跑不起来

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.14.0 - E:\NodeJs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.2 - E:\NodeJs\npm.CMD
```

**Comment by NaturalGao** [comment]
![image](https://user-images.githubusercontent.com/43291304/228905237-bf5dd491-00e7-4e12-9834-035ecc2470ed.png)
![image](https://user-images.githubusercontent.com/43291304/228905305-043e2fce-b72b-4bd8-92ec-c9e679c7443e.png)
这是报错信息

**Comment by bnhjk76123** [comment]
同问
![Xnip2023-03-31_02-26-09](https://user-images.githubusercontent.com/128875388/228930436-f7e776d2-30c8-44ec-b06f-438dadd90f08.jpg)

**Comment by TheKonka** [comment]
@NaturalGao 删除 .swc 再试下看看

**Comment by NaturalGao** [comment]
@TheKonka 试过了，我前几天初始化的项目都能正常跑，就昨天初始化的项目跑不起来

**Comment by molysama** [comment]
![QQ截图20230331100348](https://user-images.githubusercontent.com/6489372/229004400-5dee5e84-f67a-4b2b-968d-dd38c786d105.png)

同跑不起来，没有任何报错，dist目录里只有一个json文件

**Comment by zhaotianlong** [comment]
感觉是依赖版本问题,我3.29下午3.初始化的项目跑起来还没啥问题,下午5.再次初始化项目就不行了,期间报一个swc的版本丢失问题.刚才拉了下 #13533 这里一位仁兄的gitee能正常跑😭,官方赶紧修复下吧

**Comment by LeoFeng23** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/65535014/229012769-fe5e57b7-6a19-4d8b-a6c6-847b7ae5a8b0.png">
现有项目重装依赖之后都跑不起来了
新初始化的项目也跑不起来，模版vue3-nut4，taro版本3.6.2

**Comment by xuanzebin** [comment]
排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
1. 删除项目根目录下的 .swc 文件。
2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
```json
  "resolutions": {
    "@swc/core": "1.3.42"
  }
```
3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
4. 重新执行 yarn dev:weapp

即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~

**Comment by sc32024826** [comment]
从入门到放弃, 今天一连测试了好几个模板  都跑不起来  而且每个都报莫名其妙的错误  比如什么没有发现 app.config 啊啥的,
还切了好几个node版本  都无效  恶心坏了

**Comment by AdvancedCat** [comment]
> 从入门到放弃, 今天一连测试了好几个模板 都跑不起来 而且每个都报莫名其妙的错误 比如什么没有发现 app.config 啊啥的, 还切了好几个node版本 都无效 恶心坏了

很抱歉给你造成不好的开发体验， [swc](https://github.com/swc-project/swc/releases/tag/v1.3.44) 在十几个小时前刚刚发布了新版本，`@swc/register` 恰好向上升级到了这个版本，所以新装依赖就会受到影响。具体原因应该是swc插件不兼容导致的，[戳这里](https://github.com/NervJS/taro/issues/13538)

**Comment by yoyo837** [comment]
要不都改成`~`依赖到 minor版本?

**Comment by JX-Zhuang** [comment]
> 排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
> 
> 1. 删除项目根目录下的 .swc 文件。
> 2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
> 
> ```json
>   "resolutions": {
>     "@swc/core": "1.3.42"
>   }
> ```
> 
> 3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
> 4. 重新执行 yarn dev:weapp
> 
> 即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~

不行，还是会报错

**Comment by JX-Zhuang** [comment]
> 排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
> 
> 1. 删除项目根目录下的 .swc 文件。
> 2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
> 
> ```json
>   "resolutions": {
>     "@swc/core": "1.3.42"
>   }
> ```
> 
> 3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
> 4. 重新执行 yarn dev:weapp
> 
> 即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~

![image](https://user-images.githubusercontent.com/8744030/229026346-bc246484-6c1a-41c2-a6d8-8a83e0476550.png)

**Comment by naico-wang** [comment]
> > 排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
> > 
> > 1. 删除项目根目录下的 .swc 文件。
> > 2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
> > 
> > ```json
> >   "resolutions": {
> >     "@swc/core": "1.3.42"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
> > 4. 重新执行 yarn dev:weapp
> > 
> > 即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~
> 
> ![image](https://user-images.githubusercontent.com/8744030/229026346-bc246484-6c1a-41c2-a6d8-8a83e0476550.png)

如果使用npm安装是会报错，你用yarn试试，或者说在dependencies里面指定swc/core的版本为1.3.42是可以解决的

**Comment by xuanzebin** [comment]
> > 排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
> > 
> > 1. 删除项目根目录下的 .swc 文件。
> > 2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
> > 
> > ```json
> >   "resolutions": {
> >     "@swc/core": "1.3.42"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
> > 4. 重新执行 yarn dev:weapp
> > 
> > 即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~
> 
> 不行，还是会报错

请使用 yarn 或者 pnpm 进行依赖的安装

**Comment by Chen-jj** [comment]
> 要不都改成`~`依赖到 minor版本?

是的，swc 的插件系统仍在快速迭代中，并不稳定，我们之后会锁定其版本

**Comment by HHZWill** [comment]
> > > 排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
> > > 
> > > 1. 删除项目根目录下的 .swc 文件。
> > > 2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
> > > 
> > > ```json
> > >   "resolutions": {
> > >     "@swc/core": "1.3.42"
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
> > > 4. 重新执行 yarn dev:weapp
> > > 
> > > 即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~
> > 
> > 
> > 不行，还是会报错
> 
> 请使用 yarn 或者 pnpm 进行依赖的安装

亲测有效

**Comment by AutumnFrosti** [comment]
还好我看你提的Issues,不然我就准备去写uniapp

**Comment by mamba-1024** [comment]
前天可以初始化，今天突然不行了，差点怀疑人生...

**Comment by minghua233** [comment]
刚刚使用，开局劝退

**Comment by lostexin** [comment]
> `yarn`:
> 
> ```json
>   "resolutions": {
>     "@swc/core": "1.3.42"
>   }
> ```
> 
> `npm`:
> 
> ```json
>   "overrides": {
>     "@swc/core": "1.3.42"
>   }
> ```

安装依赖前别忘了把 package-lock.json 也给删了🤣

---
泰罗给我整迷茫了，第一次 cli 报错劝退，第二次项目运行不起来劝退，第三次我已经想好了，直接变成怪兽胖揍奥特曼

**Comment by yoyo837** [comment]
<img width="115" alt="image" src="https://user-images.githubusercontent.com/6134547/229085243-4bb41dc3-3499-4ee0-acbf-1de5a4258b21.png">

**Comment by NaturalGao** [comment]
我用的 npm ，在 dependencies 下面加上  "@swc/core": "1.3.42"  有效

**Comment by xianjianlf2** [comment]
> > > 排查了，发现是 Taro 使用的 @swc/core 升级到 1.3.44 后导致的问题，可以先暂时通过以下的方式解决：
> > > 
> > > 1. 删除项目根目录下的 .swc 文件。
> > > 2. 在项目根目录下的 package.json 文件下，与 devDependencies 同级属性下添加 resolutions 配置，锁定 @swc/core 使用的版本：
> > > 
> > > ```json
> > >   "resolutions": {
> > >     "@swc/core": "1.3.42"
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 3. 删除 node_modules，使用 yarn 或 pnpm 重新安装依赖。
> > > 4. 重新执行 yarn dev:weapp
> > > 
> > > 即可暂时解决问题，下个版本我们将火速修复该 issue，感谢提供信息~
> > 
> > 
> > 不行，还是会报错
> 
> 请使用 yarn 或者 pnpm 进行依赖的安装

可以使用了

**Comment by AlexBei** [comment]
![image](https://user-images.githubusercontent.com/83709912/229256333-ed4b5b42-b517-4da2-b36d-e22077bf1dfc.png)

新建项目直接删除node_modules，然后添加上面的配置，实测可以跑起来。

**Comment by Hanchengluo** [comment]
error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lemondreamtobe** [comment]
> ```json
> "resolutions": {
>     "@swc/core": "1.3.42"
>   }
> ```

感谢，这个问题已经困扰了半天了，终于解决了

**Comment by uliian** [comment]
> error Command failed with exit code 3221225477. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

这个问题如果在WSL（ubuntu20.04）下跑也一样报错，报的是：
`Segmentation fault (core dumped)
error Command failed with exit code 139.`

win下和Linux下报的都是系统内存错误。
2023年4月1日创建的项目（用gitee的模板），都报的这个错

**Comment by TheKonka** [comment]
@Hanchengluo  @uliian  可以试下 npm cache clean --force

**Comment by lemondreamtobe** [comment]
升级到3.6.2 postcss-px-scale 这个插件直接失效了

**Comment by uliian** [comment]
> @Hanchengluo @uliian 可以试下 npm cache clean --force

运行了npm cache clean --force；也运行了yarn cache clean --force；也把node_modules删除重新执行yarn了，依旧无法正常编译
```
yarn run dev:weapp
error Command failed with exit code 3221225477.
```

**Comment by TheKonka** [comment]
> > @Hanchengluo @uliian 可以试下 npm cache clean --force
> 
> 运行了npm cache clean --force；也运行了yarn cache clean --force；也把node_modules删除重新执行yarn了，依旧无法正常编译
> 
> ```
> yarn run dev:weapp
> error Command failed with exit code 3221225477.
> ```

我也遇到这个问题了，我是 添加 resolutions :{  "@swc/core": "1.3.42" } 后 把 node_modules 和 .swc 删除 ，重新安装就好了

**Comment by enjoyaday** [comment]
![image](https://user-images.githubusercontent.com/7448046/229325079-ed575006-a85b-4756-8e1c-a46bdecf13e0.png)
还是不行，这又是什么问题

**Comment by chenshuanj** [comment]
Error: 缺少 app 全局配置文件，请检查！

初始化项目，按步骤走的：
"templateInfo": {
    "name": "default",
    "typescript": false,
    "css": "none"
  }

有些劝退...

**Comment by bo-tea** [comment]
终于找到组织了  uniapp那边感觉不太适合我  转来taro  新手刚想尝试就差点被劝退  。。

**Comment by HyperClockUp** [comment]
我说跑了一个月的项目更新一下依赖怎么就跑不起来了，感谢这个issue

**Comment by xiashulin** [comment]
搞了整整2个下午，我真是服了

**Comment by yyh1413** [comment]
真服了这个老6

**Comment by yyh1413** [comment]
是启动起来了 微信小程序上报错了
app.js错误:
 ReferenceError: process is not defined

**Comment by yoyo837** [comment]
是不是哪里的依赖 使用了 process , webpack 5没有这个了

**Comment by yyh1413** [comment]
> 是不是哪里的依赖 使用了 process , webpack 5没有这个了

https://github.com/NervJS/taro/issues/13544#issuecomment-1512513635

**Comment by yyh1413** [comment]
> 是不是哪里的依赖 使用了 process , webpack 5没有这个了

![image](https://user-images.githubusercontent.com/85469054/232691012-ee6d2cfc-a7fb-48f6-bbc1-0aef3fe92fd4.png)

**Comment by yyh1413** [comment]
没有地方引用

**Comment by yoyo837** [comment]
报错信息的 process 是 taro 的代码吗?

**Comment by wenlittleoil** [comment]
没见过这么猥琐的玩意，建议放弃

**Comment by wenlittleoil** [comment]
使用taro init选择wxPlugin模版创建项目后，也是报该错误，使用"resolutions": {"@swc/core": "1.3.42"}解决后，运行起来后又报“在该目录下未找到 app.json”的错误，真没见过这么猥琐的玩意

**Comment by TheKonka** [comment]
@wenlittleoil 

>在该目录下未找到 app.json

这个报错很明显，应该是你选择的项目目录不对，或者项目目录配置错误

**Comment by e8tg001** [comment]
被这个“全局配置缺少 pages 字段 ”折腾的没脾气了，都要准备放弃新工程了，总算找到解决方案了
"resolutions": {
    "@swc/core": "1.3.42"
  }
锁定版本，可行

**Comment by wuye1200** [comment]
有没有稳定版本啊  我原来的项目好好的突然就报这个错  版本就是@swc/core": "1.3.42 也不行
