### ISSUE TITLE
taro 运行 H5 端接口请求跨域，应该如何配置 index.js 中的 proxy

### ISSUE THREAD

**Issue by calabash519** [NervJS/taro#1355]
**问题描述**
taro 运行 H5 端接口请求跨域，想通过配置 index.js 中的 proxy，但是发现没有效果

**复现步骤**
```js
// config/index.js 
h5: {
    publicPath: '/',
    devServer: {
      host: 'localhost',
      port: 10086,
      proxy: [
        {
          context: "['/activity','api-biz','api-user']",
          target: "http://192.168.100.183:8091",
          changeOrigin: true,
          secure: false
        }
      ]
    },
   ····
```

**期望行为**
在上述代码中配置代理，期望接口能够如期请求成功，但是未能成功

**报错信息**

```
// 接口请求路径如下
http://localhost:10086/activity/newsflash/category/query_enabled_category.htm?
```

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v.1.1.9
 - Node.js 版本 v8.12.0
 - 报错平台 h5

**Comment by XiaogeTek** [comment]
@calabash519 请问问题是如何解决的？我这边遇到同样问题

**Comment by longmimi** [comment]
你好  请问下index.js中配置生效了吗  我也是不生效，最后改的默认的

**Comment by js-newbee** [comment]
配置 devServer 的 proxy 是可行的，可参考：https://github.com/js-newbee/taro-best-practices/tree/master/multi-platform#%E8%B7%A8%E5%9F%9F

**Comment by huangyanxiong01** [comment]
@js-newbee 刚才我试了一下也是没有效果

**Comment by cnscorpions** [comment]
服务端开CORS算了

**Comment by MarkLogin** [comment]
为什么我配置完代理后还是不行
//请求参数
const option = {
      url: `/api${url}`,
      data: data,
      method: method,
      header: {
        'content-type': contentType,
        'mode': 'no-cors'
      }
//h5 配置
    devServer:{
      proxy: {
        '/api/': {
          target: 'http://192.168.248.123:8080',
          pathRewrite: {'^/api/': '/'},
          changeOrigin:true
        }
      }
    },

**Comment by remember-5** [comment]
@MarkLogin 请问这个问题解决了吗？

**Comment by ofavor** [comment]
> 为什么我配置完代理后还是不行 //请求参数 const option = { url: `/api${url}`, data: data, method: method, header: { 'content-type': contentType, 'mode': 'no-cors' } //h5 配置 devServer:{ proxy: { '/api/': { target: 'http://192.168.248.123:8080', pathRewrite: {'^/api/': '/'}, changeOrigin:true } } },

target: JSON.parse('"xxxx"');
