### ISSUE TITLE
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by qqwwaaa** [NervJS/taro#13558]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
taro build --type h5报错，而且我并没有配置什么.map$

### 期望结果
成功编译

### 实际结果
编译失败

### 环境信息
```
Taro CLI 3.6.2 environment info:
    System:

      OS: Windows 10
    Binaries:
      Node: 16.20.0 - D:\node.EXE
      Yarn: 1.22.19 - C:\Users\25916\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.4 - D:\npm.CMD
```

---
### 补充信息
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.resolve.alias['.map$'] should be a string.
   -> New request
    at webpack (D:\前端学习资料\taroify-demo\node_modules\webpack\lib\webpack.js:31:9)
    at D:\前端学习资料\taroify-demo\node_modules\@tarojs\webpack-runner\src\index.ts:36:20
    at Generator.next (<anonymous>)
    at fulfilled (D:\前端学习资料\taroify-demo\node_modules\@tarojs\webpack-runner\dist\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ZakaryCode** [comment]
旧版本问题，可以自行升级
