### ISSUE TITLE
npm run build:weapp -- --watch 运行报错

### ISSUE THREAD

**Issue by yswtrue** [NervJS/taro#13555]
### 相关平台
微信小程序

**小程序基础库: 2.30.4**
**使用框架: Vue 3**

### 复现步骤
用 vue3, typescript,NutUI4,npm模板新建项目
然后执行`npm run build:weapp -- --watch`

### 期望结果
可以正常运行

### 实际结果
> shiwen-app@1.0.0 build:weapp
> taro build --type weapp --watch

👽 Taro v3.6.2

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。Example:
$ NODE_ENV=production taro build --type weapp --watch
2. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError: The argument 'id' must be a non-empty string. Received ''
    at new NodeError (node:internal/errors:399:5)
    at Module.require (node:internal/modules/cjs/loader:1136:11)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/yswtrue/Code/shiwen-app/shiwen-app/src/app.config.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._compile (/home/yswtrue/Code/shiwen-app/shiwen-app/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.newLoader [as .ts] (/home/yswtrue/Code/shiwen-app/shiwen-app/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_INVALID_ARG_VALUE'
}

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Linux 6.2 NixOS 23.05 (Stoat) 23.05 (Stoat)
      Shell: 3.6.1 - /run/current-system/sw/bin/fish
    Binaries:
      Node: 18.15.0 - /nix/store/barhvvj5m6dz29439w37x42b3g2mialf-nodejs-18.15.0/bin/node
      Yarn: 1.22.19 - /nix/store/r1w9lmzixbwq777xddhx4jn4frahm740-yarn-1.22.19/bin/yarn
      npm: 9.5.0 - /nix/store/barhvvj5m6dz29439w37x42b3g2mialf-nodejs-18.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2 
      @tarojs/plugin-html: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
```

---
### 补充信息
再次运行返回这个错误

```
> shiwen-app@1.0.0 build:weapp
> taro build --type weapp --watch

👽 Taro v3.6.2

Tips:
1. 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。Example:
$ NODE_ENV=production taro build --type weapp --watch
2. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。

fish: Job 1, 'npm run build:weapp -- --watch' terminated by signal SIGSEGV (Address boundary error)

```

**Comment by Mo-Y** [comment]
3.6.2 同样遇到SIGSEGV问题

**Comment by xuanzebin** [comment]
Duplicate of #13544
