### ISSUE TITLE
3.6.3 开发模式热重载失效

### ISSUE THREAD

**Issue by sushi-su** [NervJS/taro#13569]
### 相关平台
微信小程序

**小程序基础库: 2.30.4**
**使用框架: React**

### 复现步骤
<img width="522" alt="image" src="https://user-images.githubusercontent.com/50985188/229666177-ba0b0f64-8f91-4ef9-b804-b40ff4b06e0c.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/50985188/229666326-da4b6edf-a15e-40e0-8687-f7117f84b8d3.png">

### 期望结果
修改代码自动重新编译

### 实际结果
修改代码未重新编译

### 环境信息
```
  Taro CLI 3.6.3 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.6.3 - ~/.nvm/versions/node/v18.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.3 => 3.6.3 
      @tarojs/components: 3.6.3 => 3.6.3 
      @tarojs/helper: 3.6.3 => 3.6.3 
      @tarojs/plugin-framework-react: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-alipay: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-h5: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-jd: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-qq: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-swan: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-tt: 3.6.3 => 3.6.3 
      @tarojs/plugin-platform-weapp: 3.6.3 => 3.6.3 
      @tarojs/react: 3.6.3 => 3.6.3 
      @tarojs/runtime: 3.6.3 => 3.6.3 
      @tarojs/shared: 3.6.3 => 3.6.3 
      @tarojs/taro: 3.6.3 => 3.6.3 
      @tarojs/webpack5-runner: 3.6.3 => 3.6.3 
      babel-preset-taro: 3.6.3 => 3.6.3 
      eslint-config-taro: 3.6.3 => 3.6.3 
      react: ^18.0.0 => 18.0.0 
    npmGlobalPackages:
      typescript: 5.0.3
```

**Comment by sushi-su** [comment]
经定位发现问题出在 @tarojs/webpack5-runner 的上游依赖 ，默认模版安装 postcss-loader 当前最新的 7.2.3 版本导致无法热重载，需要暂时锁定为 7.1.0

**Comment by Chen-jj** [comment]
小程序 + Webpack5 的 JS 热更新是一直还没支持的，意思是 CSS 的热更新也受 postcss-loader 版本影响了吗

**Comment by sushi-su** [comment]
> 小程序 + Webpack5 的 JS 热更新是一直还没支持的，意思是 CSS 的热更新也受 postcss-loader 版本影响了吗

可能我想表达的跟你理解的不一样，终端运行 pnpm dev:weapp，修改 tsx 文件，预期 webpack 能监听到文件修改进行热更新，并在微信开发者工具看到修改后的效果，实际表现为 webpack 没有监听到文件修改，需要手动重新执行 pnpm dev:weapp 才能在微信开发中工具看到修改后的效果

**Comment by sushi-su** [comment]
补充环境信息：MacBook Pro M1, Node 18
手头只有这台电脑，不确定其他配置的电脑会不会有同样的问题

**Comment by TNT-Likely** [comment]
3.6.4还是存在该问题

**Comment by yswtrue** [comment]
一样

**Comment by yswtrue** [comment]
我最开始用nodejs18和yarn,npm都不能热重载.
然后换成nodejs16+pnpm就可以热重载了

**Comment by Jazee6** [comment]
+1, 3.6.4, pnpm

**Comment by yufoo1** [comment]
> 我最开始用nodejs18和yarn,npm都不能热重载. 然后换成nodejs16+pnpm就可以热重载了

您好，我使用 node v16.20.0 + pnpm v8.1.1 好像还是不可以热重载，运行命令是 pnpm run dev:weapp。

**Comment by smithyj** [comment]
看着有点像是 @pmmmwh/react-refresh-webpack-plugin 的问题

**Comment by yswtrue** [comment]
> > 我最开始用nodejs18和yarn,npm都不能热重载. 然后换成nodejs16+pnpm就可以热重载了
> 
> 您好，我使用 node v16.20.0 + pnpm v8.1.1 + taro v3.6.4 好像还是不可以热重载，运行命令是 pnpm run dev:weapp。

我是用vue和关了微信开发者的热重载，看起来是可以的

**Comment by smithyj** [comment]
@yswtrue @TNT-Likely @Chen-jj @xuanzebin 看下我的这个仓库

https://github.com/smithyj/zgy-wxapp

**Comment by GoogooFly** [comment]
> postcss-loade

咋操作的能 说一下嘛

**Comment by darkxinyu** [comment]
> > postcss-loade
> 
> 咋操作的能 说一下嘛

编辑 package.json 
```json
{
  // 原有内容。。。

  // 增加下面的配置
  "resolutions": {
      "postcss-loader": "7.1.0"
  }
}
```

删除 node_modules 和 lock 文件，重新安装依赖

**Comment by xfFelix** [comment]
的确，锁定postcss-loader为7.1.0是正常的

**Comment by DJDIDI** [comment]
> 的确，锁定postcss-loader为7.1.0是正常的

是有效的🙏

**Comment by alswl** [comment]
更换 "postcss-loader": "7.1.0" 只能重新加载一次，并不能一直有效。

**Comment by BennyChan007** [comment]
3.6.13  我关了微信开发工具的热重载就可以了

**Comment by SxmAyuyu** [comment]
增加"postcss-loader": "7.1.0"确实能解决热重载问题，但不知道会不会影响其他东西，我这边慢慢测试完告诉大家

**Comment by SxmAyuyu** [comment]
> 增加“postcss-loader”： “7.1.0”确实能解决热重载问题，但不知道会不会影响其他东西，我这边慢慢测试完告诉大家

好像还是有问题，时灵时不灵

**Comment by DevinXian** [comment]
我这手头 mbp 热更新时灵时不灵，就不敢相信了； 同事 windows 电脑倒是OK

**Comment by 501956430** [comment]
@darkxinyu  刚刚使用了下 头条小程序 无效，是否还有什么解决方案
