### ISSUE TITLE
使用pnpm运行报错

### ISSUE THREAD

**Issue by PL-FE** [NervJS/taro#13568]
### 相关平台
H5

### 复现仓库
[https://github.com/PL-FE/taro-h5.git](https://github.com/PL-FE/taro-h5.git)
**浏览器版本:  Chrome111.0.5563.147**
**使用框架: React**

### 复现步骤
1、pnpm install
2 、pnpm run dev:h5

### 期望结果
使用pnpm install 后，可以顺利运行

### 实际结果
使用yarn install 后，运行不报错
使用pnpm install后，运行报错
   Failed to compile.

./src/app.config.js
Module not found: Can't resolve '@tarojs/taro' in 'D:\csdn\taro-h5\src'

### 环境信息
```
 Taro CLI 3.4.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\pengl\AppData\Local\pnpm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by smoothdvd** [comment]
@PL-FE 我的报错是:
```
ModuleBuildError: Module build failed (from ../../node_modules/.pnpm/@tarojs+taro-loader@3.6.3_@types+react@18.0.28/node_modules/@tarojs/taro-loader/lib/h5.js):
TypeError: pages.get is not a function
    at Array.map (<anonymous>)

/Users/alexgao/Dev/chuan-app/packages/frontend:
```

项目用 pnpm i --shamefully-hoist 安装

**Comment by YujiaCheng1996** [comment]
taro3.6.3 vue3 也是报 TypeError: pages.get is not a function

**Comment by zhouzyc** [comment]
> taro3.6.3 vue3 也是报 TypeError: pages.get is not a function

一样，最新taro几个版本，最近就没一个能跑起来的，不是这个问题就是那个问题，哎

**Comment by TheKonka** [comment]
> taro3.6.3 vue3 也是报 TypeError: pages.get is not a function

react 也是这个报错

**Comment by hcw2175** [comment]
> > taro3.6.3 vue3 也是报 TypeError: pages.get is not a function
> 
> react 也是这个报错 谁感兴趣可以试下 `3.6.2-canary.2` 这个版本 看看正常不 [#13316 (comment)](https://github.com/NervJS/taro/issues/13316#issuecomment-1493277293)

+1

**Comment by TNT-Likely** [comment]
taro3.6.3 react 同报 pages.get is not a function

**Comment by wxs77577** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/1990059/229681373-415f72d0-1804-48a2-991a-075eea634343.png">

手动改下node_modules里面的h5.js能跑起来(`pnpm dev:h5`)，应该是某次更新把`pages`从`Arrray`变成了`Map`

不过`pnpm dev:weapp` 的watch确实没有生效，改了文件都没反应。

**Comment by xuanzebin** [comment]
感谢反馈，taro-loader 在更新后，对 pages 变量的处理存在问题。

正在修复中，给各位带来不便深感抱歉~

**Comment by hxlniada** [comment]
我了个大槽，稳定点啊，最近正打算在公司推呢 @xuanzebin

**Comment by xuanzebin** [comment]
> 我了个大槽，稳定点啊，最近正打算在公司推呢 @xuanzebin

好的老哥，十分抱歉

**Comment by icksky** [comment]
@xuanzebin 你好 最新版 `pnpm dev:weapp` 还是 `Cannot find name 'defineAppConfig'.`

**Comment by TheKonka** [comment]
> @xuanzebin 你好 最新版 `pnpm dev:weapp` 还是 `Cannot find name 'defineAppConfig'.`

 是 typescrpit 项目吗？ app.config.ts 里面报错的吗？

**Comment by xuanzebin** [comment]
> @xuanzebin 你好 最新版 `pnpm dev:weapp` 还是 `Cannot find name 'defineAppConfig'.`

我这边没能在最新版复现你说的问题，有具体的环境信息吗？最好能提供一个复现问题的 demo

**Comment by icksky** [comment]
> 是 typescrpit 项目吗？ app.config.ts 里面报错的吗？

@TheKonka 是的  taro vue3 ts 项目

**Comment by LeoFeng23** [comment]
> 

+1，vue3, taro 3.6.2 重装了依赖之后就起不起来了，升级3.6.4也还是会这样

**Comment by YujiaCheng1996** [comment]
> > 
> 
> +1，vue3, taro 3.6.2 重装了依赖之后就起不起来了，升级3.6.4也还是会这样

我是降级3.6.2后使用declare var defineAppConfig: any;临时解决的

**Comment by TheKonka** [comment]
我也没复现，参照 @xuanzebin 所说，最好能提供一个复现问题的 demo

**Comment by icksky** [comment]
@xuanzebin @TheKonka Hello, 终于复现了。 [复现 repo](https://github.com/icksky/taro-vue3-issue)。通过 cli 初始化， vue3 / ts / pnpm 项目，然后添加 `src/components/hello/index.vue`，重点在于 `components` 文件夹（但是为空没问题）。

**Comment by swbcnegc** [comment]
> @xuanzebin @TheKonka Hello, 终于复现了。 [复现 repo](https://github.com/icksky/taro-vue3-issue)。通过 cli 初始化， vue3 / ts / pnpm 项目，然后添加 `src/components/hello/index.vue`，重点在于 `components` 文件夹（但是为空没问题）。

+1 
unplugin-vue-components 配置了 dirs 在weapp会报这个错，h5端正常。他这个demo应该报错原因也是一样的，没配置dirs，默认是src/components目录 @xuanzebin

**Comment by swbcnegc** [comment]
> 

666，加了这个 不会提示 Cannot find name 'defineAppConfig' ，小程序的热更新也可以了，原先用3.6.4cli创建nutui的demo无法在weapp热更新。

这是为啥，全栈开发第一次写小程序快崩溃了

**Comment by swbcnegc** [comment]
> > > 
> > 
> > 
> > +1，vue3, taro 3.6.2 重装了依赖之后就起不起来了，升级3.6.4也还是会这样
> 
> 我是降级3.6.2后使用declare var defineAppConfig: any;临时解决的

666，加了这个 不会提示 Cannot find name 'defineAppConfig' ，小程序的热更新也可以了，原先用3.6.4cli创建nutui的demo无法在weapp热更新。

这是为啥，全栈开发第一次写小程序快崩溃了

**Comment by LeoFeng23** [comment]
defineAppConfig 这个问题用yarn安装依赖是没有问题的，可以正常启动，但是使用pnpm就会报错

**Comment by xuanzebin** [comment]
> > @xuanzebin @TheKonka Hello, 终于复现了。 [复现 repo](https://github.com/icksky/taro-vue3-issue)。通过 cli 初始化， vue3 / ts / pnpm 项目，然后添加 `src/components/hello/index.vue`，重点在于 `components` 文件夹（但是为空没问题）。
> 
> +1 unplugin-vue-components 配置了 dirs 在weapp会报这个错，h5端正常。他这个demo应该报错原因也是一样的，没配置dirs，默认是src/components目录 @xuanzebin

目前发现 swc 在 pnpm 和 npm 下会存在问题，麻烦都先用 yarn 来进行依赖的安装吧，等下个版本修复了该问题之后再重新使用 pnpm 和 npm 吧。

**Comment by xuanzebin** [comment]
> @xuanzebin @TheKonka Hello, 终于复现了。 [复现 repo](https://github.com/icksky/taro-vue3-issue)。通过 cli 初始化， vue3 / ts / pnpm 项目，然后添加 `src/components/hello/index.vue`，重点在于 `components` 文件夹（但是为空没问题）。

这个复现的 demo，里面有部分依赖比较旧了，更新一下应该就能正常跑起来了：
```
"webpack": "5.78.0",
"typescript": "^4.1.0",
"postcss": "^8.4.18",
"@swc/core": "1.3.42",
"postcss-loader": "7.0.2",
```

typescript 和 postcss 应该是项目依赖没有更新至最新模版版本。
@swc/core 和 postcss-loader 应该是项目中部分依赖锁死导致版本过高报错，webpack 版本是造成 3.6.3 之后的 taro 项目只能使用 yarn，而 npm 和 pnpm 会报错的根本原因，下个版本会修复。

暂时先通过手改 package.json 里的 devDependencies 中的版本来让项目正常跑起来吧。
