### ISSUE TITLE
npm run build:h5 -- --watch报错，小程序编译正常

### ISSUE THREAD

**Issue by Twining** [NervJS/taro#1356]
**问题描述**
执行npm run build:h5 -- --watch报错

**复现步骤**
[复现问题的步骤]
app.js加上
`if (process.env.TARO_ENV === 'weapp') {
  require('taro-ui/dist/weapp/css/index.css')
} else if (process.env.TARO_ENV === 'h5') {
  require('taro-ui/dist/h5/css/index.css')
}`
出现编译失败，报错
`Module not found: Can't resolve 'taro-ui/dist/h5/css/index.css' in 'e:\xxx\xxx\.temp'`
然后删除这段再编译
`Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">`

**期望行为**
H5编译正常

**报错信息**
`Module not found: Can't resolve 'taro-ui/dist/h5/css/index.css' in 'e:\xxx\xxx\.temp'`
`Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">`

**系统信息**

 - 操作系统: windows10
 - Taro 版本 v1.1.9
 - Node.js 版本v10.13.0
 - 报错平台 h5

**Comment by dragon1061** [comment]
我也是一样编译成H5报错，小程序正常，不知道是什么原因

**Comment by fonture** [comment]
> 检查一下taro-ui是不是v1.5.1？ 如果是的话，降级到taro-ui@1.5.0
> taro-ui@1.5.1打包方式发生了变化，后续会有文档说明

我的是1.4.0的，h5打包也会出这个问题
