### ISSUE TITLE
针对 skyline 渲染器的部分调整

### ISSUE THREAD

**Issue by yfme01** [NervJS/taro#13587]
### 这个特性解决了什么问题？
- 编译后的 app.wxss 中引用 common.wxss 在内容之后，skyline 只允许引用在文件最前面，但阅读过之前的文档，为了避免样式覆盖，只能将 common.wxss 放在后面

- 还需要一个可以判断渲染器是 skyline 还是 webview 的 hook

### 这个 API 长什么样？
- 可选的将 common.wxss 放在 app.wxss 前面，或可以在在引用 common.wxss 后方定义样式
- `useRenderer` 返回 页面节点的 `this.renderer`

**Comment by Chen-jj** [comment]
1 是老问题了，应该把 app 样式也抽取到独立的文件中进行引用，就能解决 app.css 的引用顺序问题：

```css
@import './app-core.css';
@import './common.css';
```

2. @AdvancedCat 鑫哥考虑看看是提供 Taro API 还是 hooks 的方式，如果是 hooks 可能也得考虑 Vue3.

**Comment by AdvancedCat** [comment]
简单看了一下，在 weapp 插件中新增一个 Taro API ：
- Taro hooks 目前主要是副作用 hook 为主（`useRouter` 是例外），而应用参数一般是通过平台提供 api 来获得，不太适合；
- 在插件`@tarojs/plugin-platform-weapp` 中新增一个 `Taro.getRenderer()`，获得当前页面的渲染器类型，这样不用区分技术栈；

根据 [微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/migration/#%E5%A6%82%E4%BD%95%E8%AF%86%E5%88%AB%E5%BD%93%E5%89%8D%E9%A1%B5%E9%9D%A2%E6%98%AF%E5%90%A6%E4%BD%BF%E7%94%A8-Skyline) 描述，可通过 `this.renderer` 获取到渲染器类型，目前可以使用如下方法来获得：

```js
import { getCurrentInstance } from '@tarojs/runtime'

// 获得 this.renderer
getCurrentInstance().page.renderer
```

React & Vue 均可用。
