### ISSUE TITLE
[bug] getStorageSync is not a function in TypeScript 5, PNPM 8 & webpack 5.77

### ISSUE THREAD

**Issue by TechQuery** [NervJS/taro#13586]
## 相关平台

H5

## 复现仓库

https://github.com/idea2app/Taro-Vant-MobX-ts/pull/6

- **浏览器版本: Chrome 111.0.5563.147**
- **使用框架: React**

## 复现步骤

用 `pnpm dev h5` 启动后，点 [demo 主导航栏最后一个图标](https://taro-vant-mobx-aaa0u0vpj-techquery.vercel.app/#/pages/interface)，代码会执行

```ts
import { getStorageSync } from '@tarojs/taro';

getStorageSync('token');
```

## 期望结果

没有报错，让接口逻辑可以正常执行。

## 实际结果

```text
Uncaught (in promise) TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_7___default(...).getStorageSync is not a function
```

## 环境信息

```text
👽 Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4
      @tarojs/components: 3.6.4 => 3.6.4
      @tarojs/helper: 3.6.4 => 3.6.4
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4
      @tarojs/plugin-html: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-h5: ^3.6.4 => 3.6.4
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4
      @tarojs/runtime: 3.6.4 => 3.6.4
      @tarojs/shared: 3.6.4 => 3.6.4
      @tarojs/taro: 3.6.4 => 3.6.4
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4
      babel-preset-taro: 3.6.4 => 3.6.4
      eslint-config-taro: 3.6.4 => 3.6.4
```

---

## 补充信息

运行时 `import` 的对象与此相同：https://github.com/NervJS/taro/issues/12943#issuecomment-1340677480

**Comment by YujiaCheng1996** [comment]
vue3版本有同样的问题，Taro.request、Taro.getSystemInfo啥的也是提示这个未找到。同时vue-router也不能用了，打开路径变为/#/pages/index/index，3.6.2版本没有这个尾巴。

**Comment by ZakaryCode** [comment]
> VirtualList内部报错应该也是这个原因，我用的是小程序

这个问题是 web 端的，和小程序无关哈，有需要可以提个新的 issue

**Comment by naico-wang** [comment]
> > VirtualList内部报错应该也是这个原因，我用的是小程序
> 
> 这个问题是 web 端的，和小程序无关哈，有需要可以提个新的 issue

已经提了issue了：https://github.com/NervJS/taro/issues/13572

**Comment by axetroy** [comment]
3.6.9-aplha.6 依旧存在这个问题

楼上的方法不管用，因为

// https://unpkg.com/browse/@tarojs/plugin-platform-h5@3.6.2/dist/taroApis.js

这个文件从 3.6.8 开始就消失了，不见了，搜索整个 node_modules/@tarojs 目录都找不到

**Comment by ShaoXuChenTTT** [comment]
3.6.11发现同样的问题

**Comment by ShaoXuChenTTT** [comment]
同楼上，目前其他npm包引用的内容有比较好的转化方法吗，
(https://github.com/NervJS/taro/blob/next/packages/babel-plugin-transform-taroapi/src/index.ts#L47) apis入参已经没办法获取了

**Comment by wikiwikiki** [comment]
![image](https://github.com/NervJS/taro/assets/45203334/89653743-5c45-420b-855b-13dfff4393fb)
直接引用getStorageSync方法 是可以的，Taro.getStorageSync 是undefined

**Comment by QuincyX** [comment]
4.0.4 依然有这个问题

**Comment by yx-design** [comment]
import {getStorageSync} from "@tarojs/taro";

const getCookie = (k: string): string => {
  return getStorageSync("")
};

4.0.4版本，Cannot resolve symbol 'getStorageSync' ?
