### ISSUE TITLE
3.6.4 监听不到文件改动

### ISSUE THREAD

**Issue by TNT-Likely** [NervJS/taro#13584]
### 相关平台
微信小程序

**小程序基础库: 2.34.0**
**使用框架: React**

### 复现步骤
npm run dev:weapp

### 期望结果
文件改动，重新编译

### 实际结果
文件改动，无法编译

### 环境信息
```

  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      react: ^18.0.0 => 18.2.0 
```

**Comment by TheKonka** [comment]
没有复现，你是不是打开小程序开发者工具自带的热重载了？

**Comment by yyh1413** [comment]
> ### 相关平台
> 微信小程序
> 
> **小程序基础库: 2.34.0** **使用框架: React**
> 
> ### 复现步骤
> npm run dev:weapp
> 
> ### 期望结果
> 文件改动，重新编译
> 
> ### 实际结果
> 文件改动，无法编译
> 
> ### 环境信息
> ```
> 
>   Taro CLI 3.6.4 environment info:
>     System:
>       OS: macOS 13.2.1
>       Shell: 5.8.1 - /bin/zsh
>     Binaries:
>       Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
>       Yarn: 1.22.19 - /usr/local/bin/yarn
>       npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
>     npmPackages:
>       @tarojs/cli: 3.6.4 => 3.6.4 
>       @tarojs/components: 3.6.4 => 3.6.4 
>       @tarojs/helper: 3.6.4 => 3.6.4 
>       @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
>       @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
>       @tarojs/react: 3.6.4 => 3.6.4 
>       @tarojs/runtime: 3.6.4 => 3.6.4 
>       @tarojs/shared: 3.6.4 => 3.6.4 
>       @tarojs/taro: 3.6.4 => 3.6.4 
>       @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
>       babel-preset-taro: 3.6.4 => 3.6.4 
>       eslint-config-taro: 3.6.4 => 3.6.4 
>       react: ^18.0.0 => 18.2.0 
> ```

请问解决了  我也出现这个问题

**Comment by yyh1413** [comment]
我用taro是3.6.2   也监听不到文件修改

**Comment by yyh1413** [comment]
我是将所有依赖更新为最新，在重新打包好用了
要将项目中所有依赖更新为最新版本，可以使用以下步骤：

全局安装 npm-check-updates：可以使用以下命令在全局安装 npm-check-updates：

npm install -g npm-check-updates
```

定位到项目根目录：在命令行中定位到包含 package.json 文件的项目根目录。

运行 npm-check-updates：运行以下命令，使用 npm-check-updates 检查并更新依赖版本：

ncu -u
该命令将检查 package.json 文件中的所有依赖，并将它们的版本更新为最新版本。 -u 选项表示更新依赖版本。

安装更新后的依赖：运行以下命令安装更新后的依赖：

npm install
这将安装所有 package.json 中的更新后的依赖版本。

**Comment by hkai1221** [comment]
> 我是将所有依赖更新为最新，在重新打包好用了 要将项目中所有依赖更新为最新版本，可以使用以下步骤：
> 
> 全局安装 npm-check-updates：可以使用以下命令在全局安装 npm-check-updates：
> 
> npm install -g npm-check-updates
> 
> ```
> 
> 定位到项目根目录：在命令行中定位到包含 package.json 文件的项目根目录。
> 
> 运行 npm-check-updates：运行以下命令，使用 npm-check-updates 检查并更新依赖版本：
> 
> ncu -u
> 该命令将检查 package.json 文件中的所有依赖，并将它们的版本更新为最新版本。 -u 选项表示更新依赖版本。
> 
> 安装更新后的依赖：运行以下命令安装更新后的依赖：
> 
> npm install
> 这将安装所有 package.json 中的更新后的依赖版本。
> ```

有帮助，问题已解决，模拟器可以正常更新了👍
