### ISSUE TITLE
[bug]编译成HTML端代码后，input标签(type='file')不触发change事件

### ISSUE THREAD

**Issue by maple5233** [NervJS/taro#1359]
**问题描述**
编译成HTML5端代码后，input标签(type='file')无法在**移动端浏览器**（本次开发用的微信浏览器）触发change事件

**复现步骤**
##### dom部分
```jsx
<Input type="file" multiple id="image" name="image" accept="image/*" onChange={this.onChangeFile} />
```
##### 事件绑定函数
```js
onChangeFile = (e) => {
    console.log(e)
}
```

**期望行为**
打印出e

**报错信息**

无，并未进入onChangeFile函数

**系统信息**

 - 操作系统: WIN10
 - Taro 版本
```json
    "@tarojs/components": "^1.1.8",
    "@tarojs/taro": "^1.1.8",
    "@tarojs/taro-h5": "^1.1.8",
```
 - Node.js 版本 10.13.0
 - 报错平台: h5

**补充信息**
手动监听事件：
```js
const inputDom = document.querySelector('#image')
inputDom.onchange = (e) => {
  this.onChangeFile(e)
}
```
这么做之后就正常了
大概是忘了emit了....

**Comment by maple5233** [comment]
@jimczj

**Comment by jinjinjin0731** [comment]
抱歉，按你所提供的代码片段并没有复现你这个情况，可以提供可复现的 demo 吗。
![1543909903400](https://user-images.githubusercontent.com/17409735/49426827-ac46ff80-f7dc-11e8-8570-1cd6e7e79025.jpg)

**Comment by maple5233** [comment]
@jinjinjin0731 不好意思 忘了写清楚了 PC端无此问题 问题在于移动端

**Comment by jinjinjin0731** [comment]
已复现，正在解决

**Comment by jinjinjin0731** [comment]
已修复

**Comment by rainyf** [comment]
@jinjinjin0731 请问修复到哪里了。我用的1.2.0-beta.7 还是有这个问题。

**Comment by jinjinjin0731** [comment]
等8发布

**Comment by maple5233** [comment]
@rainyf

可以暂时先用原生的fix一下
把这段代码 加到input的onclick里

```js
const inputDom = document.querySelector('#image')
inputDom.onchange = (e) => {
  this.onChangeFile(e)
}
```
