### ISSUE TITLE
插件依赖 "@tarojs/plugin-platform-h5" 加载失败

### ISSUE THREAD

**Issue by codinglilong** [NervJS/taro#13591]
### 相关平台
H5

**浏览器版本: 版本 111.0.5563.146（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
根据官网运行
npm install -g @tarojs/cli

taro init myApp

npm install

npm rum dev:h5

出现报错

### 期望结果
正常运行

### 实际结果
npm run dev:h5

> myApp001@1.0.0 dev:h5
> npm run build:h5 -- --watch

> myApp001@1.0.0 build:h5
> taro build --type h5 "--watch"

👽 Taro v3.6.4

Error: Cannot find module 'node:path'
Require stack:
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/plugin-platform-h5/dist/index.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/plugin-platform-h5/index.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/utils/index.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/Kernel.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/index.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/index.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/cli/dist/cli.js
- /Users/apple/Learn/taro/myApp001/node_modules/@tarojs/cli/bin/taro
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/plugin-platform-h5/dist/index.js:6:12)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Object.newLoader [as .js] (/Users/apple/Learn/taro/myApp001/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/plugin-platform-h5/dist/index.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/plugin-platform-h5/index.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/utils/index.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/Kernel.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/index.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/index.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/cli/dist/cli.js',
    '/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/cli/bin/taro'
  ]
}
/Users/apple/Learn/taro/myApp001/node_modules/@tarojs/service/dist/utils/index.js:75
                    throw new Error(`插件依赖 "${item}" 加载失败，请检查插件配置`);
                          ^

Error: 插件依赖 "@tarojs/plugin-platform-h5" 加载失败，请检查插件配置

### 环境信息
```
taro info                                        
👽 Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 15.0.0 - ~/.nvm/versions/node/v15.0.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v15.0.0/bin/yarn
      npm: 7.0.2 - ~/.nvm/versions/node/v15.0.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.2
```

**Comment by yoyo837** [comment]
node版本多少, 好像有点低

**Comment by yoyo837** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/6134547/230282966-a95581d1-bbaf-432d-b5ca-0e40a07d2c45.png">

**Comment by yoyo837** [comment]
node 15 是不支持的

**Comment by codinglilong** [comment]
node 15 是不支持的

**Comment by freespy** [comment]
遇到同样的问题，然后手动修改@tarojs\plugin-html\dist\index.js文件，将var path = require('node:path');改为var path = require('path');就可以了。

**Comment by yoyo837** [comment]
> 遇到同样的问题，然后手动修改@tarojs\plugin-html\dist\index.js文件，将var path = require('node:path');改为var path = require('path');就可以了。

改dist源码天大的bug都能解决.  
<img width="116" alt="image" src="https://user-images.githubusercontent.com/6134547/230529845-f83bf6eb-e0fd-4961-80b2-c3f462468583.png">

**Comment by hanwenbo** [comment]
@codinglilong 打开吧 和 node15没关系，node 18也不行

**Comment by liangcheng133** [comment]
> @codinglilong 打开吧 和 node15没关系，node 18也不行

我刚也在做测试的时候也出现了文章的报错，使用node14.0.0运行的，然后我用nvm切成16.0.0就可以正常运行了

**Comment by ChenPt** [comment]
node v14.17.3 => node v16.0.0
前者报错，后者正常运行
nvm 切了个新的node版本就可以了

**Comment by litimi** [comment]
同样遇到了这个问题，node切换到18.15.0正常

**Comment by zhangxing186176** [comment]
[在Node版本15的时候，确实会出现此类错误，建议Node版本16.xxx以上。
![微信截图_20230821141721](https://github.com/NervJS/taro/assets/130450333/c0ae7d42-6909-4434-89f4-e5aaf3d5e976)

**Comment by shellus** [comment]
```
$ node -v
v18.16.1

$ npm run dev:h5

> myApp@1.0.0 dev:h5
> npm run build:h5 -- --watch


> myApp@1.0.0 build:h5
> taro build --type h5 --watch

👽 Taro v3.6.22

找不到插件依赖 "@tarojs/plugin-platform-h5"，请先在项目中安装，项目路径：...\taro-mall

$

```

node18同样有问题
