### ISSUE TITLE
开发微信群满了，新群发下啊

### ISSUE THREAD

**Issue by smithyj** [NervJS/taro#13609]
### 这个特性解决了什么问题？
开发微信群满了，新群发下啊

### 这个 API 长什么样？
开发微信群满了，新群发下啊

**Comment by smithyj** [comment]
@smoothdvd @guotie @Psli @Leechael

**Comment by nevernet** [comment]
其实开发群也不活跃

**Comment by ZakaryCode** [comment]
fixed
