### ISSUE TITLE
已经修复的 h5 端 ”tabbar 生命周期错误“什么时候发包？

### ISSUE THREAD

**Issue by spadeACE7** [NervJS/taro#13602]
### 相关平台
H5

**浏览器版本: Chrome**
**使用框架: React**

### 复现步骤
Uncaught TypeError: Cannot read properties of undefined (reading 'list')
什么时候发包

### 期望结果
3.6.4版本能正常使用

### 实际结果
修复了bug但还没发

### 环境信息
```
Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/rn-runner: 3.6.4 => 3.6.4 
      @tarojs/rn-supporter: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/runtime-rn: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/taro-rn: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      react: ^18.1.0 => 18.2.0 
      react-native: ^0.70.1 => 0.70.8 
```

**Comment by naico-wang** [comment]
3.6.5版本，估计快了。

**Comment by spadeACE7** [comment]
> 



> 3.6.5版本，估计快了。
能不能先发个补充版的；公司着急用

**Comment by TheKonka** [comment]
`3.6.5-alpha` 已经发布，可以升级看看，我试了是正常没有报错了的

**Comment by SidneyLann** [comment]
每次发版都是0测试吗？

**Comment by SidneyLann** [comment]
TypeError
Cannot set property value of [object HTMLElement] which has only a getter
Call Stack
 eval
  node_modules/@tarojs/components/lib/react/react-component-lib/utils/attachProps.js:84:28
 attachProps
  node_modules/@tarojs/components/lib/react/react-component-lib/utils/attachProps.js:68:31
 ReactComponent.componentDidUpdate
  node_modules/@tarojs/components/lib/react/react-component-lib/createComponent.js:34:79
 commitLayoutEffectOnFiber
  node_modules/react-dom/cjs/react-dom.development.js:19241:34
 commitLayoutMountEffects_complete
  node_modules/react-dom/cjs/react-dom.development.js:20352:13
 commitLayoutEffects_begin
  node_modules/react-dom/cjs/react-dom.development.js:20341:11
 commitLayoutEffects
  node_modules/react-dom/cjs/react-dom.development.js:20289:7
 commitRootImpl
  node_modules/react-dom/cjs/react-dom.development.js:22096:9
 commitRoot
  node_modules/react-dom/cjs/react-dom.development.js:21987:9

**Comment by spadeACE7** [comment]
> `3.6.5-alpha` 已经发布，可以升级看看，我试了是正常没有报错了的

好嘞，我去升级试试 🙏
