### ISSUE TITLE
能否加入redux + immutable项目模板

### ISSUE THREAD

**Issue by farzer** [NervJS/taro#1360]

**Comment by yuche** [comment]
有两个问题：

1. 现在宥于微信的限制还不能做到 props 是 immutable 对象，所有 props 都会被微信序列化，最终变成一个 plain object。
2. 我们后来可能会实现自己的 props 通信机制，但也不会加，这属于 redux 模板的一种，在 redux 之上使用什么中间件是用户自己的选择。万一我们加了你这个，又要加 redux-saga 模板，又要加 redux-promise 模板，又要加 redux-observable 模板，然后再排列组合一下岂不是要增加几百种模板？
