### ISSUE TITLE
支付宝小程序能否支持自定义tabbar

### ISSUE THREAD

**Issue by gmy-us** [NervJS/taro#13610]
### 这个特性解决了什么问题？
支付宝小程序能否支持自定义tabbar

### 这个 API 长什么样？
支付宝小程序能否支持自定义tabbar

**Comment by puhahalx** [comment]
在百度小程序可以考虑把custom-tab-bar 编译之后 文件名转成customize-tab-bar,这样可以适用于多平台打包

**Comment by FLDCF** [comment]
我的版本是3.6.17，如何不升级版本能解决呢？现在配置custom和customize-tab-bar，UI没问题，但是点击多次才跳转生效，函数组件
