### ISSUE TITLE
scss文件中的px不会转化为rem

### ISSUE THREAD

**Issue by LEtertops** [NervJS/taro#13615]
### 相关平台
H5

### 复现仓库
[git@github.com:LittleBoBo-beep/taro-bug.git](git@github.com:LittleBoBo-beep/taro-bug.git)
**浏览器版本: Chrome 112**
**使用框架: React**

### 复现步骤
上面仓库是随便找的别人的，这么明显的问题，自己拉一个，
直接安装taro/cli 并初始化一个项目
在pages/index.scss中给样式怎么一个字体或者宽度，尺寸单位为px
然后npm run dev:h5就能复现

### 期望结果
npm run dev:h5启动后，样式文件中的px能转换为rem

### 实际结果
样式文件的中px没有转换，一直是在浏览器中也是px

### 环境信息
```

Taro v3.6.4
  Taro CLI 3.6.4 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.20.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
      npm: 6.14.17 - D:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4
      @tarojs/components: 3.6.4 => 3.6.4
      @tarojs/helper: 3.6.4 => 3.6.4
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4
      @tarojs/react: 3.6.4 => 3.6.4
      @tarojs/runtime: 3.6.4 => 3.6.4
      @tarojs/shared: 3.6.4 => 3.6.4
      @tarojs/taro: 3.6.4 => 3.6.4
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4
      babel-preset-taro: 3.6.4 => 3.6.4
      eslint-config-taro: 3.6.4 => 3.6.4
      react: ^18.0.0 => 18.2.0
```

---

**Comment by yoyo837** [comment]
虽然可能是个很简单的问题, 但大部分情况下, 随意几个文字描述的问题, 在没有复现链接的情况下,让开发人员自行看自己理解的去尝试复现会耗尽开发人员时间, 必然没有问题人本身根据自己的情况直接提供复现解决起来更高效.

**Comment by ZakaryCode** [comment]
> 直接安装taro/cli 并初始化一个项目
> 在pages/index.scss中给样式怎么一个字体或者宽度，尺寸单位为px
> 然后npm run dev:h5就能复现

这个步骤并不能复现问题

**Comment by LEtertops** [comment]
我补一个出来，

> 虽然可能是个很简单的问题, 但大部分情况下, 随意几个文字描述的问题, 在没有复现链接的情况下,让开发人员自行看自己理解的去尝试复现会耗尽开发人员时间, 必然没有问题人本身根据自己的情况直接提供复现解决起来更高效.

不好意思，其实发出来后就后悔了，感觉自己格局小了，情绪也有问题。在这里道歉！对不起！

**Comment by LEtertops** [comment]
> > 直接安装taro/cli 并初始化一个项目
> > 在pages/index.scss中给样式怎么一个字体或者宽度，尺寸单位为px
> > 然后npm run dev:h5就能复现
> 
> 这个步骤并不能复现问题

不好意思，其实发出来后就后悔了，感觉自己格局小了，情绪也有问题。在这里道歉！对不起！

补一个复现仓库
https://github.com/LEtertops/taro-components

**Comment by ZakaryCode** [comment]
虽然 issue 被关闭了，还是补充一下问题的结论，Taro 中使用的 loader 会自动跳过自有模块的转义（以 @tarojs/components 为例，如果不禁用它的 loader 会导致库内 css 与 cssinjs 中的差异导致一些隐患，参考 #12372）所示示例项目名为 taro-components，会被项目判断为 taro 自有模块，所以相关 loader 会被禁用。
