### ISSUE TITLE
3.6.2升级3.6.4公共api丢失(Taro.request is not a function  )

### ISSUE THREAD

**Issue by keepmood** [NervJS/taro#13618]
### 相关平台
H5

### 复现仓库
[https://github.com/keepmood/taro-issue-repro-230410.git](https://github.com/keepmood/taro-issue-repro-230410.git)
**浏览器版本: Chrome  112.0.5615.50（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
clone项目安装依赖后执行yarn dev:h5即可复现
```
    Taro.request({ url: "www.baidu.com" }).then((res) => console.log(res));
```

### 期望结果
Taro.request正常执行

### 实际结果
Taro.request无法执行

### 环境信息
```
  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - C:\program files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\program files\nodejs\yarn.CMD
      npm: 8.1.2 - C:\program files\nodejs\npm.CMD
```

---
### 补充信息
项目是通过cli选择taro-ui模板直接创建的
创建后package.json添加了
```
"resolutions": {
    "@swc/core": "1.3.42"
  }
```
同时将taro相关依赖从3.6.2全选替换为3.6.4后重装依赖即可复现问题。

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/13586#issuecomment-1498731321
应该是一样的问题，可以尝试此方法或者升级到 `3.6.5-alpha`临时修复

**Comment by misty-rain-xy** [comment]
我也遇到同样问题了，打印Taro实例发现里面少了很多方法

**Comment by xuanzebin** [comment]
可以升级到 3.6.5-alpha，这个版本已修复此问题，后续很快会发布正式的 3.6.5 版本 

Duplicate of #13586
