### ISSUE TITLE
[taro-runtime] URL  对象的实例通过 .searchParams.append('c', 3) 方法修改后，在调用 URL 的 toString() 方法后返回的数据异常

### ISSUE THREAD

**Issue by RunningCoderLee** [NervJS/taro#13616]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/RunningCoderLee/taro-demo.git](https://github.com/RunningCoderLee/taro-demo.git)
**小程序基础库: 2.30.2**
**使用框架: React**

### 复现步骤
在项目代码里执行如下代码（已添加在项目里，直接启动即可）

const url = new URL('https://www.baidu.com/index?a=1')
url.searchParams.append('b', '2')
const newUrl = url.toString()
console.log(newUrl)

### 期望结果
https://www.baidu.com/index?a=1&b=2

### 实际结果
https://www.baidu.com/index?a=1

### 环境信息
```
  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      npm: 8.10.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-mini-ci: ^3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
看了下源码，https://github.com/NervJS/taro/blob/e9c821824d/packages/taro-runtime/src/bom/URL.ts#L33

这里只是把 search 的字符串值赋值给了 this.search ，当使用 url.searchParams.append('b', '2') 时，其实是在一个新的 URLSearchParams 的实例上进行修改

https://github.com/NervJS/taro/blob/e9c821824d/packages/taro-runtime/src/bom/URL.ts#L146

修改后的值并不会保存到 this.search 上，所以在最终调用  toString 方法的时候返回的 url 中并没有新增的 b=2。

想确认下，这个是为了兼容有意而为之还是一个 bug？

**Comment by yoyo837** [comment]
@AdvancedCat 巨佬来帮忙确认一下.

**Comment by AdvancedCat** [comment]
这是一个遗留的 bug，Taro 主要是为了填补 URL 的运行时，确保前端路由逻辑可以在小程序中运行，因此没有完全实现 URL 的Web规范。

欢迎 PR 修复。
