### ISSUE TITLE
鸿蒙插件 taro build --type harmony 编译 API 9 FA 模型 JS 代码报错

### ISSUE THREAD

**Issue by bigggge** [NervJS/taro#13639]
### 相关平台
鸿蒙

**使用框架: React**

### 复现步骤

按文档 https://nervjs.github.io/taro-docs/docs/harmony/ 操作

"@tarojs/plugin-platform-harmony": "^3.6.0"

taro build --type harmony

鸿蒙使用 API 9 FA 模型 JS 代码

DevEco Studio 3.1 Beta1
Build Version: 3.1.0.200, built on February 13, 2023
Runtime version: 11.0.13 7-b1751.21 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1536M
Cores: 8
Registry: external.system.auto.import.disabled=true

### 期望结果
编译成功

### 实际结果
```
ModuleParseError: Module parse failed: Duplicate export 'default' (9:7)
File was processed with these loaders:
 * @tarojs/taro-loader/lib/page
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| 
> export default component
|
```

### 环境信息
```
👽 Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      react: ^18.2.0 => 18.2.0 
      taro-ui: 3.1.0-beta.2 => 3.1.0-beta.2 

```

**Comment by jianwei** [comment]
这个问题好了吗 ？ 我也遇到了同样的问题，最新的版本：
`Taro v3.8.0-canary.0


  Taro CLI 3.8.0-canary.0 environment info:
    System:
      OS: macOS 11.7.9
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/components: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/helper: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-framework-react: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-alipay: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-h5: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-jd: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-qq: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-swan: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-tt: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/plugin-platform-weapp: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/react: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/runtime: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/shared: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/taro: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/taro-loader: 3.8.0-canary.0 => 3.8.0-canary.0 
      @tarojs/webpack5-runner: 3.8.0-canary.0 => 3.8.0-canary.0 
      babel-preset-taro: 3.8.0-canary.0 => 3.8.0-canary.0 
      eslint-config-taro: 3.8.0-canary.0 => 3.8.0-canary.0 
      react: ^18.0.0 => 18.2.0 
`

**Comment by xuanzebin** [comment]
目前 FA 模型鸿蒙侧已经不再维护，taro 侧也不再适配，请使用最新的 stage 模型进行开发，详情参考文档：https://docs.taro.zone/docs/next/harmony
