### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by dingminghui** [NervJS/taro#13647]
### 相关平台
H5

**浏览器版本: Chrome **
**使用框架: React**

### 复现步骤
Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 npm
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 默认模板

直接使用最新版  Taro v3.6.4 生成项目，npm run dev:h5 就会出错

### 期望结果
正常启动

### 实际结果
/Users/.../myApp/node_modules/webpack/lib/util/hash/wasm-hash.js:108
		const length = data.length;
                      ^
TypeError: Cannot read properties of undefined (reading 'length')

### 环境信息
```
👽 Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.2
```

**Comment by yoyo837** [comment]
ref #13600 #13568

**Comment by ZakaryCode** [comment]
> 新错误
> 
> ```
> _tarojs_taro__WEBPACK_IMPORTED_MODULE_9___default().setNavigationBarTitle is not a function. (In '_tarojs_taro__WEBPACK_IMPORTED_MODULE_9___default().setNavigationBarTitle({
> title: title || ""
> })', '_tarojs_taro__WEBPACK_IMPORTED_MODULE_9___default().setNavigationBarTitle' is undefined)```
> ```

ref #13618 #13586
