### ISSUE TITLE
view标签不支持hidden？

### ISSUE THREAD

**Issue by laoriy** [NervJS/taro#13644]
### 这个特性解决了什么问题？
在小程序里面使用了canvas，如果使用v-show切换的话，会导致图表显示空白，v-if 会丢失图表交互状态

### 这个 API 长什么样？
view标签加hidden编译为小程序原生的hidden属性

**Comment by heiazu** [comment]
暂时可以通过引入插件`@tarojs/plugin-inject`，动态补充`view`的`hidden`属性，写法如下：

文档：[@tarojs/plugin-inject](https://github.com/NervJS/taro/tree/next/packages/taro-plugin-inject)

```
const config = {
  plugins: [
    ['@tarojs/plugin-inject', {
      components: {
        // 为 view 组件新增了 'hidden' 属性和默认值
        View: {
          'hidden': "false"
        }
      }
    }]
  ]
}

```
