### ISSUE TITLE
能否提供其他API的Interceptor功能

### ISSUE THREAD

**Issue by leietal** [NervJS/taro#13651]
### 这个特性解决了什么问题？
在导航前后需要做一些类似登录判断、权限判断等处理。在发起网络请求的时候需要做一些统一的处理，例如设置token等（现在只有request能用，upload和download不能用）。返回Promise的API都可能有类似的处理的需求。

### 这个 API 长什么样？
Taro.addInterceptor('upload',  logInterceptor);
Taro.addInterceptor('navigateTo',  authInterceptor);

**Comment by ZakaryCode** [comment]
fix in #13676
