### ISSUE TITLE
h5在组件继承时，父组件如果使用了connect，父组件的constructor将不会执行

### ISSUE THREAD

**Issue by hereisfun** [NervJS/taro#1365]
**问题描述**
在h5中，组件如果继承自一个使用了connect的父组件，父组件的constructor将不会执行（小程序则没问题）

**复现步骤**
taro init 一个项目，使用redux模板

```js
// pages/index/index.js
import Taro, { Component } from '@tarojs/taro'
import WrapButton from '../../component/wrapButton'

export default class Index extends Component {
  render () {
    return (
        <WrapButton />
    )
  }
}

// component/Btn.js  父类
import Taro, { Component } from '@tarojs/taro'
import { connect } from '@tarojs/redux'

const mapStateToProps = ({counter}) => {
  return { count: counter.num }
}


@connect(mapStateToProps, null)
export default class Btn extends Component {
  constructor(props) {
    super(props)
    console.log('Btn')     // 不会打印Btn
  }
}

// component/wrapButton.js 子类
import Taro from 'taro'
import { Button } from '@tarojs/components'
import Btn from './Btn'


export default class WrapButton extends Btn {
  // 此处如果注释了，父类constructor中的console将不会执行
  // 如果不注释，则报错: Uncaught TypeError: Cannot read property 'store' of undefined （redux里的context为空）
  // constructor(props) {
  //   super(props)
  // }
  render() {
    console.log('wrapButton props', this.props)
    const { count } = this.props
    return <Button>{count}</Button>
  }
}

```

**期望行为**
期望在h5中子类能正常访问父类的props

**报错信息**
![image](https://user-images.githubusercontent.com/20593467/49425543-deeef900-f7d8-11e8-91fc-d4e3b16abd3f.png)

**系统信息**

 - 操作系统: [Mac 10.13.4]
 - Taro 版本 [Taro v1.2.0-beta.6]
 - Node.js 版本 [v10.4.0]
 - 报错平台 [h5]

**补充信息**
与 #1104 #1198 可能有关，疑似redux的context出现问题。
不使用装饰器，直接调用`connect(mapStateToProps)(wrapButton)`同样有问题

**Comment by Littly** [comment]
组件继承的话 需要使用下面的写法
```javascript
constructor(...args) {
    super(...args)
}
```

组件的构造函数签名是`constructor (props, context) {}`
`super(props)`的话，相当于给`context`传了`undefined`。而在react-redux里面有这么一行，就报错了
https://github.com/NervJS/taro/blob/cc0db54030a7f0c0f3757aa08dd12b298176f441/packages/taro-redux-h5/react-redux/components/connectAdvanced.js#L133

另外，继承connect组件不调用constructor是正常现象。你所继承的connect组件，源码在这里
https://github.com/NervJS/taro/blob/cc0db54030a7f0c0f3757aa08dd12b298176f441/packages/taro-redux-h5/react-redux/components/connectAdvanced.js#L127

子组件所调用的`super(props)`构造函数，仅仅是进行了组件环境的初始化，事件订阅等等，WrappedComponent在connect组件render的时候才会登场。

**Comment by hereisfun** [comment]
@Littly 感谢大佬的详细解答
使用(...args)的方式传参后，报错信息没有了，但在子类里面还是无法访问父类的props

也就是例子里的`console.log('wrapButton props', this.props)`打印出的props里没有父类Btn中的this.props.count

**Comment by imageslr** [comment]
@Littly  大佬，我想请问一下`this._unsafeCallUpdate = true`这一行是做什么用的？

**Comment by shenghanqin** [comment]
可以再试试，最新版1.3.22还有这个问题吗？
