### ISSUE TITLE
react native 导出编译源文件而非bundle文件

### ISSUE THREAD

**Issue by dagouzhi** [NervJS/taro#13661]
### 这个特性解决了什么问题？
类似taro build native-components --type rn  将项目导出一份 编译后的文件，而非直接生成bundle文件，就像typescript ts 转成 js

### 这个 API 长什么样？
taro build --type rn

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/discussions/11860

**Comment by dagouzhi** [comment]
需求是把整个项目把所有源码通过taro编译成标准的react-native 的源码，再通过自己的RN项目集成这套源码，而非直接把源码打包成index.bundle文件

**Comment by zhiqingchen** [comment]
该需求不支持

**Comment by zhiqingchen** [comment]
可以查看rn-transform包源码，输出中间过程代码
