### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'component.render')，RN编译报错

### ISSUE THREAD

**Issue by master429** [NervJS/taro#13669]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
执行yarn run dev:rn 后；
To reload the app press "r"
To open developer menu press "d"

metro-file-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: watchman::QueryParseError: failed to parse query: must use ["anyof", expr...]. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
To print qrcode press "q"
 BUNDLE  ./index 

 LOG  Running "taroDemo" with {"rootTag":11,"initialProps":{}}
 ERROR  TypeError: undefined is not an object (evaluating 'component.render')

### 期望结果
正常编译

### 实际结果
TypeError: undefined is not an object (evaluating 'component.render')

### 环境信息
```
 Taro v3.6.4


  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4 
      @tarojs/components: 3.6.4 => 3.6.4 
      @tarojs/components-rn: ^3.6.4 => 3.6.4 
      @tarojs/helper: 3.6.4 => 3.6.4 
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4 
      @tarojs/plugin-mini-ci: ^3.6.4 => 3.6.4 
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4 
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4 
      @tarojs/react: 3.6.4 => 3.6.4 
      @tarojs/rn-runner: 3.6.4 => 3.6.4 
      @tarojs/rn-supporter: 3.6.4 => 3.6.4 
      @tarojs/runtime: 3.6.4 => 3.6.4 
      @tarojs/runtime-rn: 3.6.4 => 3.6.4 
      @tarojs/shared: 3.6.4 => 3.6.4 
      @tarojs/taro: 3.6.4 => 3.6.4 
      @tarojs/taro-h5: ^3.6.5 => 3.6.5 
      @tarojs/taro-rn: 3.6.4 => 3.6.4 
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4 
      babel-preset-taro: 3.6.4 => 3.6.4 
      eslint-config-taro: 3.6.4 => 3.6.4 
      expo: ~47.0.3 => 47.0.3 
      react: ^18.1.0 => 18.1.0 
      react-native: ^0.70.8 => 0.70.8 
    npmGlobalPackages:
      typescript: 5.0.2
```

---

**Comment by master429** [comment]
直接采用的集中开发模式的react native模板，然后把小程序代码迁移进来，出现报错

**Comment by master429** [comment]
<img width="1287" alt="截屏2023-04-14 下午9 03 51" src="https://user-images.githubusercontent.com/76980858/232054040-0794f945-bfd0-4808-a3bf-d277339c263c.png">

![WechatIMG198](https://user-images.githubusercontent.com/76980858/232054225-c7a2d391-4108-4efb-92bc-256f9e950be0.jpeg)

**Comment by zhiqingchen** [comment]
需要提供 最小可复现demo

**Comment by master429** [comment]
目前问题找到了，RN模板里面的入口文件app.ts中，不能用函数式组件，只能写类组件才不会报错，项目属于迁移以往小程序代码兼容RN实现跨端，其入口文件写了函数式组件，使用taro hooks出现报错；希望后续入口文件能够兼容函数式组件写法

**Comment by master429** [comment]
> 需要提供 最小可复现demo
<img width="998" alt="截屏2023-04-17 上午10 48 55" src="https://user-images.githubusercontent.com/76980858/232366132-ec301d31-586e-48af-835d-99189c43048f.png">

https://github.com/master429/taro2rn/blob/main/src/main.tsx

**Comment by zhiqingchen** [comment]
useLaunch 目前在rn并未支持。入口可以分多个文件，如 rn 的初始化使用 app.rn.tsx ，其他使用 app.tsx

**Comment by master429** [comment]
好的，多谢

**Comment by zhiqingchen** [comment]
更多可参考
https://github.com/wuba/taro-playground

**Comment by master429** [comment]
> 更多可参考 https://github.com/wuba/taro-playground

👌🏻
