### ISSUE TITLE
getCurrentPages

### ISSUE THREAD

**Issue by dockersurface** [NervJS/taro#1367]
`var pages = getCurrentPages();`
`var prevPage = pages[pages.length - 2];  //上一个页面`
`prevPage.setData({defaultAddress: item})`
这个样子修改上一页的defaultAddress，微信开发者工具AppData中数据正常，但是componentDidShow中打印的defaultAddress和AppData中defaultAddress不一致。

**Comment by luckyadam** [comment]
不能这样修改，你只能调用组件的 setState 来修改数据

**Comment by wugy0103** [comment]
但是prevPage.setState()会报错

**Comment by dockersurface** [comment]
> 但是prevPage.setState()会报错

我是这样做的：你要修改的页面的componentDidShow中打印this.$scope.data可以看见你想要的数据，再调用this.setState()。

**Comment by wugy0103** [comment]
> > 但是prevPage.setState()会报错
> 
> 我是这样做的：你要修改的页面的componentDidShow中打印this.$scope.data可以看见你想要的数据，再调用this.setState()。

我也是这样做的，但是这样体验不是很好，prevPage.setState()可以在后台渲染完后在后退

**Comment by banana-pia** [comment]
> 不能这样修改，你只能调用组件的 setState 来修改数据



> 不能这样修改，你只能调用组件的 setState 来修改数据

但是prevPage中获取不到setState方法

**Comment by wugy0103** [comment]
这是来自QQ邮箱的自动回复邮件。
