### ISSUE TITLE
打包H5页面在钉钉H5微应用白屏，使用低版本chrome浏览器（70版本）复现Uncaught SyntaxError: 'super' keyword unexpected here

### ISSUE THREAD

**Issue by LeoFeng23** [NervJS/taro#13674]
### 相关平台
H5

**浏览器版本: chrome 70**
**使用框架: Vue 3**

### 复现步骤
代码打包部署后在钉钉H5微应用注册之后在钉钉中打开，
或低版本chrome中运行（chrome70）

### 期望结果
正常运行

### 实际结果
页面白屏，报错Uncaught SyntaxError: 'super' keyword unexpected here

### 环境信息
```
👽 Taro v3.6.5


  Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.n/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 9.5.0 - ~/.n/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5 
      @tarojs/components: 3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5 => 3.6.5 
      @tarojs/plugin-framework-vue3: 3.6.5 => 3.6.5 
      @tarojs/plugin-html: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5 
      @tarojs/plugin-vue-devtools: ^3.6.5 => 3.6.5 
      @tarojs/router: 3.6.5 => 3.6.5 
      @tarojs/runtime: 3.6.5 => 3.6.5 
      @tarojs/service: 3.6.5 => 3.6.5 
      @tarojs/shared: 3.6.5 => 3.6.5 
      @tarojs/taro: 3.6.5 => 3.6.5 
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5 
      babel-preset-taro: 3.6.5 => 3.6.5 
      eslint-config-taro: 3.6.5 => 3.6.5 
```

---
### 补充信息
钉钉安卓端内置的webview版本为chrome 69，使用taro打包的H5应用在钉钉H5微应用中报错白屏，使用chrome 70版本也可复现

**Comment by LeoFeng23** [comment]
复现链接https://github.com/LeoFeng23/bug-test

**Comment by LeoFeng23** [comment]
报错部分代码为const c = !!l && { passive: !1 },
        u = (0, n.GH)(
          class extends n.mv {
            constructor() {
              super(),
                this.__registerHost(),
                (this.onRefresh = (0, n.yM)(this, "refresh", 7)),
                (this._ScreenY = 0),
                (this._startScreenY = 0),
                (this._lastScreenY = 0),
                (this._isMounted = !1),
                (this.triggerPullDownRefresh = (e) => {
                  !this.dragOnEdge &&
                    this._isMounted &&
                    (e
                      ? ((this._lastScreenY = this.distanceToRefresh + 1),
                        (this.currSt = "release"),
                        this.setContentStyle(this._lastScreenY))
                      : ((this.currSt = "finish"), this.reset()));
                }),

**Comment by LeoFeng23** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/65535014/232225531-5a6bf295-843f-45e9-99f9-587504ea88aa.png">

**Comment by LeoFeng23** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/65535014/232225564-e23e4df4-2caf-477d-b37a-839bdfe42324.png">

**Comment by hxlniada** [comment]
请问这个您是怎么解决的？我也遇到了

**Comment by Miaonster** [comment]
@LeoFeng23 请问是怎么解决的？

**Comment by PL-FE** [comment]
大佬怎么解决的，我也遇到了

**Comment by Miaonster** [comment]
@PL-FE 我加了个 exclude 强制触发了源码里跳过了包含 taro_components 的分支，可以试试

```
  h5: {
    compile: {
      exclude: [(filename: string) => filename.includes('taro_components_include_trick')],
    }
  }
```

**Comment by PL-FE** [comment]
已经收到您的来信，我会尽快回复。

**Comment by PL-FE** [comment]
@Miaonster 还是不行，我是在钉钉69内核的H5。不过还是感谢大佬的帮助

**Comment by PL-FE** [comment]
配置了这个可以
```js
h5:{
    webpackChain(chain, webpack) {
      chain.merge({
        module: {
          rule: {
            myloader: {
              test: /\.js$/,
              use: [
                {
                  loader: 'babel-loader',
                  options: {},
                },
              ],
            },
          },
        },
      });
    },
}
```
