### ISSUE TITLE
3.6.5 版本中app.config.ts 中无法对引用文件进行编译

### ISSUE THREAD

**Issue by kingyang** [NervJS/taro#13686]
### 相关平台
微信小程序

**小程序基础库: 2.26.1**
**使用框架: Vue 3**

### 复现步骤

app.config.ts

import { pagesArray } from './auto/page';

console.log(pagesArray);

export default defineAppConfig({

  pages: ['pages/index/index'],

  pageOrientation: 'portrait',

  tabBar: undefined,

  window: {

    backgroundTextStyle: 'light',

    navigationBarTextStyle: 'white',

    navigationBarBackgroundColor: '#F66442',

  },
  lazyCodeLoading: 'requiredComponents',

  requiredBackgroundModes: ['audio'],

});

./auto/page 

export enum PageAuth {

  Login,

  Vip,
}

type PageInfo = { path: string; auth?: PageAuth };

export type Pages = {

  index: PageInfo;

  login: PageInfo;

};
const pagePath = (name: string, auth?: PageAuth): PageInfo => ({ path: `pages/${name}/index`, auth });

export const pages: Pages = {

  index: pagePath('index'),

  login: pagePath('login'),

};

export const pagesArray: string[] = [];

for (const key in pages) {

  pagesArray.push(pages[key].path);

}

### 期望结果
3.6.2 版本中app.config.ts 是可以正常使用的, 可以对引用ts进行编译

3.6.5 版本报异常信息, 具体是啥原因呢

### 实际结果
export enum PageAuth {
^^^^^^

SyntaxError: Unexpected token 'export'

### 环境信息
```
taro info
👽 Taro v3.6.5


  Taro CLI 3.6.5 environment info:
    System:
      OS: Windows 10 10.0.22624
    Binaries:
      Node: 18.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5
      @tarojs/components: 3.6.5 => 3.6.5
      @tarojs/helper: 3.6.5 => 3.6.5
      @tarojs/plugin-framework-vue3: 3.6.5 => 3.6.5
      @tarojs/plugin-html: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5
      @tarojs/plugin-vue-devtools: 3.6.5 => 3.6.5
      @tarojs/runtime: 3.6.5 => 3.6.5
      @tarojs/shared: 3.6.5 => 3.6.5
      @tarojs/taro: 3.6.5 => 3.6.5
      @tarojs/taro-loader: 3.6.5 => 3.6.5
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5
      babel-preset-taro: 3.6.5 => 3.6.5
      eslint-config-taro: 3.6.5 => 3.6.5
```

**Comment by AdvancedCat** [comment]
严格来说，是暂时不支持引入 ESM 模块文件，若是 CJS 模块，就是 ok 的.

原因是，taro 内部会将 app.config.js 转译为 CJS 模块处理，但忽略了对引用文件进行转译。

@ZakaryCode

**Comment by Chen-jj** [comment]
应该是测试了引用文件，漏了测试引用文件需要编译的情况 @ZakaryCode
