### ISSUE TITLE
npm install 后编译错误

### ISSUE THREAD

**Issue by yifeishu-com** [NervJS/taro#13689]
### 相关平台
H5

**浏览器版本: Edge 112.0.1722.48**
**使用框架: React**

### 复现步骤
使用Taro版本：3.5.11

之前运行是好的，今天npm i @nutui-react-taro之后浏览器运行白屏，报错。降级@nutui-react-taro、删除node_modules重装也还是报错。

错误排查：
加载了一个文件 https://xxx.xxx.xxx.xxx:10086/chunk/node_modules_taro_h5_prebundle_style-0d1ee54c_css-_dc2f0.js ，dev-server返回了 html 文件，然后解析"<"字符报错。

我看node_modules/.taro/h5/remote/chunk 下确实没有这个文件，倒是有一个 node_modules_taro_h5_prebundle_tarojs_router_js-node_modules_taro_h5_prebundle_style-0d1ee54c_css.js 文件。

请问如何修复？

### 期望结果
正常预览

### 实际结果
编译没报错，浏览器预览白屏，报错

### 环境信息
```
👽 Taro v3.5.11

  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.11 => 3.5.11
      @tarojs/components: 3.5.11 => 3.5.11
      @tarojs/helper: 3.5.11 => 3.5.11
      @tarojs/plugin-framework-react: 3.5.11 => 3.5.11
      @tarojs/plugin-html: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-alipay: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-jd: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-qq: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-swan: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-tt: 3.5.11 => 3.5.11
      @tarojs/plugin-platform-weapp: 3.5.11 => 3.5.11
      @tarojs/react: 3.5.11 => 3.5.11
      @tarojs/router: 3.5.11 => 3.5.11
      @tarojs/runtime: 3.5.11 => 3.5.11
      @tarojs/shared: 3.5.11 => 3.5.11
      @tarojs/taro: 3.5.11 => 3.5.11
      @tarojs/taro-h5: 3.5.11 => 3.5.11
      @tarojs/webpack5-runner: 3.5.11 => 3.5.11
      babel-preset-taro: 3.5.11 => 3.5.11
      eslint-config-taro: 3.5.11 => 3.5.11
      react: ^18.0.0 => 18.2.0
    npmGlobalPackages:
      typescript: 4.9.5
```

---
### 补充信息
Uncaught SyntaxError: Unexpected token '<' (at node_modules_taro_h5_prebundle_style-0d1ee54c_css-_dc2f0.js:1:1)
runtime.js:1025  Uncaught (in promise) ChunkLoadError: Loading chunk node_modules_taro_h5_prebundle_style-0d1ee54c_css-_dc2f0 failed.
(missing: https://xxx.xxx.xxx.xxx:10086/chunk/node_modules_taro_h5_prebundle_style-0d1ee54c_css-_dc2f0.js)
while loading "./@tarojs/taro" from webpack/container/reference/taro_app_library
    at __webpack_require__.f.j (runtime.js:1025:29)
    at runtime.js:151:40
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (runtime.js:150:67)
    at fn.e (runtime.js:517:50)
    at ./@tarojs/taro (remoteEntry.js:6234:372)
    at get (remoteEntry.js:6271:23)
    at handleFunction (runtime.js:361:31)
    at onInitialized (runtime.js:373:73)
    at runtime.js:363:65

**Comment by yifeishu-com** [comment]
@ZakaryCode 请帮忙看看~

**Comment by yifeishu-com** [comment]
@ZakaryCode 请帮忙看下，卡住了，还挺急的。。。

**Comment by yifeishu-com** [comment]
我手动把 /node_modules/.taro/h5/remote/remoteEntry.js 里的 node_modules_taro_h5_prebundle_style-0d1ee54c_css-_dc2f0 改成了 node_modules_taro_h5_prebundle_tarojs_router_js-node_modules_taro_h5_prebundle_style-0d1ee54c_css 可以正常运行了，但是没有解决根本问题，请关注一下~

**Comment by ZakaryCode** [comment]
1. 请尝试将 @nutui-react-taro 依赖添加在 prebundle.exclude 配置后重试；
2. 可关注生产环境与开发环境实际编译的区别，或者加入 writeToDisk 配置后观察实际写入缓存的编译文件内容而非 .taro/h5/remote/chunk 下的缓存文件；
3. 可尝试升级到 3.6.5+ 版本验证是否存在同一问题；
4. 如以上方案无法解决，可提交最小可现 DEMO 用于定位问题

**Comment by yifeishu-com** [comment]
升级到3.6.5已解决，多谢

**Comment by HuiWang-World** [comment]
3.6.23 也有这个问题，有人能修复一下吗
