### ISSUE TITLE
支付宝动态加载插架功能不支持

### ISSUE THREAD

**Issue by Tom-About** [NervJS/taro#13687]
### 这个特性解决了什么问题？
https://opendocs.alipay.com/mini/plugin/plugin-usage#%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD

支付宝动态加载插件时，需要使用component组件加载插件，并且必须使用a:if来控制component组件的显示。但是我在taro文档中并没有找到对应的写法，如果直接在项目中使用支付宝的写法的话会报错(报a:if的错误，如下图所示)。问过支付宝小程序的客服，他们说需要在taro下反馈一下。希望做下这块的兼容
![image](https://user-images.githubusercontent.com/54340726/232958967-04a4211b-858c-429d-b58a-21d1f8b1894a.png)
![image](https://user-images.githubusercontent.com/54340726/232959133-9e3ef4f3-82c1-4e20-ad2b-241d2ab16f91.png)

### 这个 API 长什么样？
和上面支付宝文档中的类似，
```js
<component
        is="dynamic-plugin://2021002172680015/get-coupon"
        a:if={pluginIsReady}
        onGetCouponSuccess={onGetCouponSuccess}
        onGetCouponFail={onGetCouponFail}
        onClose={onClosef}
        onUseImmediately={onUseImmediately}
        params={itemList.map((coupon, idx) => ({
          activityId: coupon.activityId,
          customizeSendTime: formatDate(),
          outBizNo: `${new Date().valueOf()}_${coupon.activityId}_${idx}`,
        }))}
        dialogBtnType={1}
        dialogBtnStyle={{
          color: "#fff",
          borderColor: "#EB445B",
          backgroundColor: "#EB445B",
        }}
        boxBounding={{ left: 0, bottom: 0 }}
      >
        领取
      </component>
```

**Comment by Tom-About** [comment]
@ZakaryCode 请问Taro目前确认是没有这个功能吗？如果没有的话预计啥时候可以增加上。我们这边需要定一下是不是要走备用方案（静态加载插件）

**Comment by ZakaryCode** [comment]
> 请问Taro目前确认是没有这个功能吗？

只是根据你的 issue 打了个 tag，对这一块内容不太熟悉

**Comment by Tom-About** [comment]
> > 请问Taro目前确认是没有这个功能吗？
> 
> 只是根据你的 issue 打了个 tag，对这一块内容不太熟悉

那请问啥时候可以给个结论出来，目前卡在这个地方了，大佬帮忙跟下哈

**Comment by ZakaryCode** [comment]
vue3?

**Comment by ZakaryCode** [comment]
看起来只是个 Namespace tags 语法错误，自行调整下 babel 配置试试咯

```js
{
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx", {
        "throwIfNamespace": false
      }
    ]
  ]
}
```

**Comment by Tom-About** [comment]
> ```js
> "plugins": [
>     [
>       "@babel/plugin-transform-react-jsx", {
>         "throwIfNamespace": false
>       }
>     ]
>   ]
> ```

好的，我先试下这种方式

**Comment by Tom-About** [comment]
> 看起来只是个 Namespace tags 语法错误，自行调整下 babel 配置试试咯
> 
> ```js
> {
>   "plugins": [
>     [
>       "@babel/plugin-transform-react-jsx", {
>         "throwIfNamespace": false
>       }
>     ]
>   ]
> }
> ```

试了下，还是跑不通，帮忙看下是不是在这个文件里面配置babel
![image](https://user-images.githubusercontent.com/54340726/233009804-e0b06cc3-2f8f-4d42-b7c7-f887b3ad1da7.png)

**Comment by ZakaryCode** [comment]
看了下，这里由于 preset 并不能从外部覆盖，需要对 babel-preset-taro 进行修改。

```diff
  if (isReact) {
    presets.push([require('@babel/preset-react'), {
      runtime: options.reactJsxRuntime || 'automatic',
+      throwIfNamespace: false
    }])
    if (isWeb && process.env.NODE_ENV !== 'production' && options.hot !== false) {
      if (options.framework === 'react') {
        plugins.push([require('react-refresh/babel'), { skipEnvCheck: true }])
      } else if (options.framework === 'preact') {
        overrides.push({
          include: /\.[jt]sx$/,
          plugins: [require('@prefresh/babel-plugin')]
        })
      }
    }
  }
```

或许为 babel-preset-taro 增加 react 参数，用于外部覆盖 @babel/preset-react 的配置会是个较好的选择

**Comment by Tom-About** [comment]
> 

大佬，这段代码需要我们来添加吗，还是说你们后面会更新一版babel-preset-taro出来

**Comment by Tom-About** [comment]
> fix(babel): 支持修改 react-presets 参数 #13712
好的，了解了，感谢大佬支持

**Comment by Tom-About** [comment]
> 可以先参考这个自行调整下，下一个版本修复

@ZakaryCode 大佬，我们参考这个调整了下，a:if的问题没有了，可以编译。但是直接写支付宝小程序的component标签貌似编译不出来东西，帮忙看下有没有什么办法可以让这个component组件编译出啦
![image](https://user-images.githubusercontent.com/54340726/234204366-0dd2d56b-2a49-4fe5-a89c-728ff9b0c4e9.png)
![image](https://user-images.githubusercontent.com/54340726/234204586-4807ffce-9fd3-48da-899c-7df1e9b81470.png)

**Comment by ZakaryCode** [comment]
> 但是直接写支付宝小程序的component标签貌似编译不出来东西，帮忙看下有没有什么办法可以让这个component组件编译出啦

新增标签需求可以新开一个 enhancement 或者 PR 并附上相关文档，简单使用可以基于 [inject](https://github.com/NervJS/taro-plugin-inject/tree/v1.0.2#3-components) 插件，自行调整

**Comment by Chen-jj** [comment]
@Tom-About 看了一下支付宝动态加载插件的语法，和 Taro 语法差异点挺大的，且不好兼容。可以通过编写一个支付宝原生自定义组件去进行动态加载，即：Taro React -> 原生自定义组件 -> 插件

例如:

原生自定义组件 `<foo>`：

```js
Component({
  data: {
    isReady: false,
  },
  didMount () {
    my.loadPlugin({
      plugin: 'xxx@*', // 指定要加载的插件 ID 和版本号，为 * 时自动选择版本
      success: () => {
        this.setData({ isReady: true }); // 插件已加载，可以渲染插件组件了
      },
    });
  }
});
```

```xml
<!-- 使用 component 组件 渲染插件组件 hello。hello为插件plugin.json中对外暴露的组件 -->
<component is="dynamic-plugin://xxx/captcha4" a:if="{{isReady}}"></component>
```

Taro React:

```jsx
<foo />
```
