### ISSUE TITLE
目前可以使用全局sass么？

### ISSUE THREAD

**Issue by bernkastle** [NervJS/taro#137]
目前有很多可以需要重复使用的固定样式，是否提供全局的支持，或者是否有css-module的方法可以用？

谢谢项目组支持！

**Comment by zacksleo** [comment]
全局样式放到`app.css/app.sass`里面不就可以了

**Comment by bernkastle** [comment]
@zacksleo 放在app.sass里面也不会对其他的component生效，只能在其他sass文件@import进去，这样感觉和单独拆分sass好像没有去呗
