### ISSUE TITLE
Taro.getAccountInfoSync()映射支付宝小程序api的my.getAppIdSync用于获取appid

### ISSUE THREAD

**Issue by JCqiu** [NervJS/taro#13704]
### 这个特性解决了什么问题？
通过Taro.getAccountInfoSync()获取支付宝appid

### 这个 API 长什么样？
Taro.getAccountInfoSync().miniProgram.appId等于my.getAppIdSync().appId

**Comment by TheKonka** [comment]
https://opendocs.alipay.com/mini/api/my.getAccountInfoSync

支付宝也有 `getAccountInfoSync` 吧，可以获取 `appid`
> 推荐使用此 API 替代 [my.getAppIdSync](https://opendocs.alipay.com/mini/api/gazkkm) 来获取小程序 APPID。

**Comment by JCqiu** [comment]
@TheKonka 用了的，只是希望能映射到taro上面来，就不用写两套逻辑了

**Comment by TheKonka** [comment]
> @TheKonka 用了的，只是希望能映射到taro上面来，就不用写两套逻辑了

写两套逻辑是啥意思，直接用 `Taro.getAccountInfoSync().miniProgram.appId`不就行了吗，`my.getAppIdSync()`可以不用。
不过，你直接用 `Taro.getAppIdSync().appId` 也是可以获取到的，`Taro` 会自动把自己替换成 `my`来调用， 报错是类型报错，这个后续可以完善类型

**Comment by JCqiu** [comment]
@TheKonka 我的意思是还得判断环境，能只用一个api就最好了
![image](https://user-images.githubusercontent.com/16211027/233627137-05659897-1227-4930-bd3c-bd3e5c32a8f8.png)

![image](https://user-images.githubusercontent.com/16211027/233626967-dbecf310-de74-49ac-887d-1b3fdc23c0b5.png)

**Comment by AdvancedCat** [comment]
推荐不代表禁止，也就是 Taro.getAccountInfoSync() 在支付宝小程序里仍然是可用的，就没有必要做映射。应该要将 getAppIdSync 视作新的 api 去支持。

**Comment by TheKonka** [comment]
![image](https://user-images.githubusercontent.com/22173084/233642896-43c438c4-516f-4ca1-b0da-64d5a85c5931.png)

肯定是只用一个 `api` 啊，不需要判断环境，支付宝文档里不是写的 `getAccountInfoSync().miniProgram.appId` 吗，为啥你写的是 `getAccountInfoSync().appId`

**Comment by yoyo837** [comment]
他是不是在说同一个Taro API 获取微信和支付的appId?

**Comment by JCqiu** [comment]
@TheKonka 
![image](https://user-images.githubusercontent.com/16211027/233753814-8d43ae82-26b2-4f4e-a13f-50be9c21a950.png)
我看文档上写的是只支持微信

**Comment by TheKonka** [comment]
可能文档更新不及时，以实际测试结果为准👌
