### ISSUE TITLE
v3.7支持使用react-router 替换 taro的路由吗

### ISSUE THREAD

**Issue by gyf30827** [NervJS/taro#13714]
### 相关平台
H5

**浏览器版本: chrome 最新版本**
**使用框架: React**

### 复现步骤
taro 路由频繁出现路由变了页面没有变的bug，说3.5 以上的版本解决，3.7.0-alpha.1  还是频繁出现，有替代方案吗

### 期望结果
是否有demo提供一个 

### 实际结果
是否有demo提供一个 

### 环境信息
```
Taro v3.7.0-alpha.1

publicPath //cdn.iyisong.net/qiwei-order/
buildProdMap undefined

  Taro CLI 3.7.0-alpha.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/components: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/mini-runner: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/plugin-framework-react: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/plugin-html: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/plugin-platform-h5: ^3.6.5 => 3.6.5 
      @tarojs/react: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/runtime: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/taro: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/webpack-runner: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      @tarojs/webpack5-runner: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      babel-plugin-transform-taroapi: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      babel-preset-taro: 3.7.0-alpha.1 => 3.7.0-alpha.1 
      react: 18.1.0 => 18.1.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by ZakaryCode** [comment]
请补充信息便于定位问题，包括但不限于：最小示例项目、可复现路径或视频、出现问题的版本、所使用的路由模式等。同时提交 issue 时请详细或简明扼要的描述问题，避免使用任何模糊表达等不利于定位或解决问题的表述。

**Comment by gyf30827** [comment]
> 另外关于 issue 标题“支持使用react-router 替换 taro的路由”，请参考[文档](https://nervjs.github.io/taro-docs/docs/router-extend)。 希望仅在 Web 端使用也可以通过开启 `multi` 模式，然后基于对应路由库自行改造。

multi 模式 在官方文档里面没有搜到相关说明

**Comment by ZakaryCode** [comment]
> multi 模式 在官方文档里面没有搜到相关说明

https://nervjs.github.io/taro-docs/docs/config-detail#h5routermode

**Comment by gyf30827** [comment]
> > multi 模式 在官方文档里面没有搜到相关说明
> 
> https://nervjs.github.io/taro-docs/docs/config-detail#h5routermode

好的，收到

**Comment by gyf30827** [comment]
> 另外关于 issue 标题“支持使用react-router 替换 taro的路由”，请参考[文档](https://nervjs.github.io/taro-docs/docs/router-extend)。 希望仅在 Web 端使用也可以通过开启 `multi` 模式，然后基于对应路由库自行改造。

 Web 端使用也可以通过开启 `multi` 模式，然后基于对应路由库自行改造。 这个怎么改造有相应的示例吗

**Comment by gyf30827** [comment]
> 另外关于 issue 标题“支持使用react-router 替换 taro的路由”，请参考[文档](https://nervjs.github.io/taro-docs/docs/router-extend)。 希望仅在 Web 端使用也可以通过开启 `multi` 模式，然后基于对应路由库自行改造。

 Web 端使用也可以通过开启 `multi` 模式，然后基于对应路由库自行改造。 这个怎么改造有相应的示例吗

**Comment by ZakaryCode** [comment]
> 这个怎么改造有相应的示例吗或者提供下思路

开启多端路由即可，余下操作与 react-router 常规使用一致，可参考对应工具文档
