### ISSUE TITLE
百度小程序，父组件将异步更新store通过props给子组件，偶现数据更新异常

### ISSUE THREAD

**Issue by HenryLulu** [NervJS/taro#1372]
## 代码
父组件代码：

    @connect(({doc}) => ({doc}))
    export default class extends Component {
        ...
        componentDidMount() {
            dispatch(getDoccontent(docid));
        }
        ...
        render() {
            return (
                <Sub content={this.props.doc.content}></Sub>
            )
        }
    }

子组件代码：

        return (
            <View>
                {this.props.content.map(line => (
                    <Text>{line.text}</Text>
                ))}
            </View>
        )

其中：
getDoccontent是个异步action，获取content数组更新store，content默认值为[]。

## 现象
getDoccontent返回，并正常更新content为有内容的数组后，
百度小程序下，有一定概率，子组件渲染区域会有明显闪烁，并最终为空白。
在子组件render中log出的props也为空数组，和store最后的next state不一致：
![image](https://user-images.githubusercontent.com/14797054/49443625-ec6fa780-f807-11e8-86ed-b5de050d838f.png)

## 其他环境
微信小程序：没问题

## 百度小程序其他写法
在子组件中connect并直接取store数据：有同样问题
将this.props.doc.content先赋值再传给子组件：有同样问题
直接将子组件的render写到父组件中：没问题

**Comment by suyingtao** [comment]
遇到一样的问题了，暂时是这么解决的。
```js
render() {
    return this.props.doc.content.length && (
        <Sub content={this.props.doc.content}></Sub>
    )
}
```

**Comment by pdsuwwz** [comment]
> 
> 结果：
> 
> ![image](https://user-images.githubusercontent.com/11807297/50069933-1ca34700-0207-11e9-9d1b-426d60340a1b.png)

您好，想问下结果里为什么第一次打印出现了 undefined
如下：
```js
this.props.content:  undefined
```
