### ISSUE TITLE
v3.6.5 初始化项目成功后，打包项目报错。

### ISSUE THREAD

**Issue by zhushenhang** [NervJS/taro#13729]
### 相关平台
微信小程序

**小程序基础库: 无上线版本**
**使用框架: React**

### 复现步骤
taro init
选择 react ，ts  no，css sass，webpack5，yarn，模板源 github，使用默认目标。
依赖安装完成后，输入 命令 yarn build:weapp
出现报错信息
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module 'typescript'
Require stack:
- D:\git-project\taro-demo\node_modules\ts-node\dist\util.js
- D:\git-project\taro-demo\node_modules\ts-node\dist\index.js
- D:\git-project\taro-demo\node_modules\postcss-loader\dist\utils.js
- D:\git-project\taro-demo\node_modules\postcss-loader\dist\index.js
- D:\git-project\taro-demo\node_modules\postcss-loader\dist\cjs.js
- D:\git-project\taro-demo\node_modules\webpack\lib\ProgressPlugin.js
- D:\git-project\taro-demo\node_modules\webpack\lib\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\webpack5-prebundle\dist\prebundle\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\webpack5-prebundle\dist\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\webpack5-runner\dist\index.mini.js
- D:\git-project\taro-demo\node_modules\@tarojs\webpack5-runner\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\helper\dist\npm.js
- D:\git-project\taro-demo\node_modules\@tarojs\helper\dist\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\helper\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\cli\dist\util\index.js
- D:\git-project\taro-demo\node_modules\@tarojs\cli\bin\taro

### 期望结果
编译成功，微信开发工具预览出现 hello world 页面

### 实际结果
打包报错

### 环境信息
```
  Taro CLI 3.6.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.13.1 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5
      @tarojs/components: 3.6.5 => 3.6.5
      @tarojs/helper: 3.6.5 => 3.6.5
      @tarojs/plugin-framework-react: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5
      @tarojs/react: 3.6.5 => 3.6.5
      @tarojs/runtime: 3.6.5 => 3.6.5
      @tarojs/shared: 3.6.5 => 3.6.5
      @tarojs/taro: 3.6.5 => 3.6.5
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5
      babel-preset-taro: 3.6.5 => 3.6.5
      eslint-config-taro: 3.6.5 => 3.6.5
      react: ^18.0.0 => 18.2.0
```

**Comment by xuanzebin** [comment]
没有复现你的问题，初步怀疑是 typescript 依赖没有成功安装，可以重新安装依赖试试。

**Comment by zhushenhang** [comment]
删掉重新安装出现警告，看起来确实是ts没有安装成功。
warning "@tarojs/webpack5-runner > postcss-loader > cosmiconfig-typescript-loader@4.3.0" has unmet peer dependency "typescript@>=3".
warning "eslint-config-taro > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".

**Comment by zhushenhang** [comment]
已成功build
我的解决方式是当前项目手动安装ts，全局方式未尝试。
`yarn add --dev typescript`
非常感谢！ @xuanzebin
