### ISSUE TITLE
【Taro 3.5.12】从 3.0.16 版本升级到 3.5.12 造成 app.config.ts 等其他页面配置文件不生效

### ISSUE THREAD

**Issue by TomatoesMan** [NervJS/taro#13731]
### 相关平台
微信小程序

**小程序基础库: 2.12.3**
**使用框架: React**

### 复现步骤
执行 npm run dev:weapp，编译无报错显示

### 期望结果
能够正常显示

### 实际结果
无法显示，nav 为黑色，底部 tabbar 不显示 

### 环境信息
```
👽 Taro v3.6.5


  Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
      npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.12 => 3.5.12 
      @tarojs/components: 3.5.12 => 3.5.12 
      @tarojs/plugin-framework-react: 3.5.12 => 3.5.12 
      @tarojs/react: 3.5.12 => 3.5.12 
      @tarojs/runtime: 3.5.12 => 3.5.12 
      @tarojs/taro: 3.5.12 => 3.5.12 
      @tarojs/webpack5-runner: 3.5.12 => 3.5.12 
      babel-preset-taro: 3.5.12 => 3.5.12 
      eslint-config-taro: 3.5.12 => 3.5.12 
      react: ^16.10.0 => 16.14.0 
```

---
### 补充信息
 进行了 swc 版本控制，但依旧无法正常显示配置信息，"resolutions": {
    "@swc/core": "1.3.6"
  }

**Comment by xuanzebin** [comment]
麻烦提供一下可以复现问题 demo，方便排查

**Comment by TomatoesMan** [comment]
复现步骤
taro init taro-demo
? 请输入项目介绍 none
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Gitee（最快）
√ 拉取远程模板仓库成功！
? 请选择模板 默认模板
npm dev:weapp

会报错 Error: 全局配置缺少 pages 字段，请检查！使用了 yarn 安装依赖并且限制了 @swc/core 版本解决了，请问这个什么时候修复

**Comment by TomatoesMan** [comment]
复现步骤
taro init taro-demo
? 请输入项目介绍 none
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 npm
? 请选择模板源 Gitee（最快）
√ 拉取远程模板仓库成功！
? 请选择模板 默认模板
npm run dev:weapp

会报错 Error: 全局配置缺少 pages 字段，请检查！使用了 yarn 安装依赖并且限制了 @swc/core 版本解决了，请问这个什么时候修复

**Comment by xuanzebin** [comment]
可以升级到 3.6.5 试试，这个问题应该是已经修复了的
