### ISSUE TITLE
组件支持i18n

### ISSUE THREAD

**Issue by suuzee** [NervJS/taro#1373]
**问题描述**

我现在做的小程序需要做国际化的需求，现在默认调用的 `@tarojs/components` 里面的组件，但是一些组件（`picker`的`确定`、`取消` `video`的`暂不支持播放此视频`）的文案默认是中文的，请问有没有对国际化这部分进行支持，比如组件本身支持传`locale`或者这些默认中文的文案可以通过`props`改的计划，或者是否可以通过其他方式来进行修改来满足我们国际化的需求呢？

**复现步骤**

拿组件源码来举例
```jsx
<div className={this.props.className}>
  {children}
  <div style={shouldDivHidden} className={clsMask} onClick={onCancel} />
  <div style={shouldDivHidden} className={clsSlider}>
    <div className='weui-picker__hd'>
      <div className='weui-picker__action' onClick={onCancel}>
        取消
      </div>
      <div className='weui-picker__action' onClick={onChange}>
        确定
      </div>
    </div>
    <div className='weui-picker__bd'>{pickerGroup}</div>
    <input type='hidden' name={name} value={this.state.pickerValue} />
  </div>
</div>
```

**期望行为**
1. 可以支持通过`locale`之类的`props`传入当前语言环境让组件去自动适配语言；或
2. 默认中文的文案可以通过`props`来让用户自行决定输入什么内容；或
3. 可以满足需求的其他方式。

**报错信息**

暂无报错

**系统信息**

 - 操作系统: macOS
 - Taro 版本: v1.2.0-beta7
 - Node.js 版本: v10.13.0
 - 报错平台: weapp

**Comment by yuche** [comment]
Taro 这个框架的 issue 只回答和框架本身有关的内容，上层应用例如有没有这组件那组件你得去 awesome-taro 看，或者去 GitHub 搜索。

**Comment by suuzee** [comment]
@yuche 感谢你的回答，官方不会支持。但是可不可以在`taro`基础组件库里头提供更加定制化的方式呢，现在这些文案是写死的，确实不是很好操作。

**Comment by yuche** [comment]
Taro 在小程序端是没有基础组件库的，全都是小程序的原生组件，这个问题你应该向小程序提才是。

**Comment by suuzee** [comment]
那我有点不太懂，我用的是 `@tarojs/components` 这个包，并且我贴出来的代码是这个包里面的源码，这一部分应该是`Taro`的吧？

**Comment by yuche** [comment]
在小程序 `@tarojs/components` 只有组件的类型文件，它实际上是用来做 IDE 自动补全的

**Comment by suuzee** [comment]
@yuche 感谢回答，我现在搞清楚了，因为在小程序开发工具里面`picker`组件的`样式`变化了，所以误以为这是`@tarojs/components`自己实现的。

**Comment by suuzee** [comment]
我将我的`demo`构建成了`h5`，发现`h5`的`picker`组件是上面这段源码实现的，因为小程序可以说微信官方就是不支持，但是`h5`这部分是可以通过修改`props`实现的吧，这个有考虑过吗？

**Comment by jinjinjin0731** [comment]
上面已经回答很清楚了
i18n 这件事情可以明确地说官方不会做，这事应该留给社区，Taro 本身应该做好框架给社区提供更好的环境。
