### ISSUE TITLE
使用picker组件更新value,报错“Uncaught RangeError: Maximum call stack size exceeded  ”

### ISSUE THREAD

**Issue by zhaotianlong** [NervJS/taro#13753]
### 相关平台
H5

**浏览器版本: chrome112**
**使用框架: React**

### 复现步骤
const AreaPicker = (props: Props) => {
  const { value = ["北京市", "北京市", "东城区"], children, onOk } = props;
  const [selectedLocation, setSelectedLocation] = useState([]);
  const [range, setRange] = useState([]);

  const handleColumnChange = ({ detail }) => {
    const { column, value } = detail;
    setSelectedLocation([1,2,3])
    
  };

  return (
    <Picker
      mode="multiSelector"
      range={[[1],[2,3],[3]]}
      value={selectedLocation}
      onColumnChange={handleColumnChange}
    >
      32334344
    </Picker>
  );
};

export default AreaPicker;

### 期望结果
正常运行

### 实际结果
报错

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.10.0/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v16.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5 
      @tarojs/components: 3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5 => 3.6.5 
      @tarojs/plugin-framework-react: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5 
      @tarojs/react: 3.6.5 => 3.6.5 
      @tarojs/runtime: 3.6.5 => 3.6.5 
      @tarojs/shared: 3.6.5 => 3.6.5 
      @tarojs/taro: 3.6.5 => 3.6.5 
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5 
      babel-preset-taro: 3.6.5 => 3.6.5 
      eslint-config-taro: 3.6.5 => 3.6.5 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.4 => 3.1.0-beta.4 
    npmGlobalPackages:
      typescript: 4.6.4
```

---
### 补充信息
随便写个demo都会报错

**Comment by zhaotianlong** [comment]
`
const AreaPicker = (props: Props) => {
  const { value = ["北京市", "北京市", "东城区"], children, onOk } = props;
  const [selectedLocation, setSelectedLocation] = useState([]);
  const [range, setRange] = useState([]);

  const handleColumnChange = ({ detail }) => {
    const { column, value } = detail;
    setSelectedLocation([1,2,3])
    
  };


  return (
    <Picker
      mode="multiSelector"
      range={[[1],[2,3],[3]]}
      value={selectedLocation}
      onColumnChange={handleColumnChange}
    >
      32334344
    </Picker>
  );
};

export default AreaPicker;
`

**Comment by zhaotianlong** [comment]
`const AreaPicker = (props: Props) => {
  const { value = ["北京市", "北京市", "东城区"], children, onOk } = props;
  const [selectedLocation, setSelectedLocation] = useState([]);
  const [range, setRange] = useState([]);

  const handleColumnChange = ({ detail }) => {
    const { column, value } = detail;
    setSelectedLocation([1,2,3])
    
  };


  return (
    <Picker
      mode="multiSelector"
      range={[[1],[2,3],[3]]}
      value={selectedLocation}
      onColumnChange={handleColumnChange}
    >
      32334344
    </Picker>
  );
};

export default AreaPicker;`

**Comment by zhaotianlong** [comment]
![image](https://user-images.githubusercontent.com/13042136/234792857-2b84c60b-b7e5-4957-afa8-eae74f618d3c.png)
![image](https://user-images.githubusercontent.com/13042136/234793043-03cacfbc-9093-44b2-9259-6fe88427ac3e.png)

**Comment by ZakaryCode** [comment]
循环错误会在下一个版本修复
在 #13735 中有提到 H5 端不支持 region 模式
