### ISSUE TITLE
build:alipay后，由于app.acss 内容里最后 import xxxx; 没有换行导致支付宝开发工具无法识别， 而无法编译预览。

### ISSUE THREAD

**Issue by owmjess** [NervJS/taro#13764]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: Vue 3**

### 复现步骤
1、yarn build:alipay；
2、打包文件app.acss 内容里最后 @import "./common.acss";没有换行导致支付宝开发工具无法识别， 而无法编译预览。
3、输出如下错误信息：
Module build failed (from /snapshot/cube/node_modules/@ali/antcube-thread-loader/lib/cjs.js):
Thread Loader (Worker 0)
@import pre compile failed: 
  => actual: 
 => expect: ./common.acss

### 期望结果
文件app.acss 内容里最后 @import "./common.acss";这句能独立一行，支付宝开发工具才能识别。

### 实际结果
现在结果是所有css内容压缩成一行；导致支付宝开发工具无法识别最后的@import "./common.acss";

### 环境信息
```
👽 Taro v3.6.5


  Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 17.9.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5 
      @tarojs/components: 3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5 => 3.6.5 
      @tarojs/plugin-framework-vue3: 3.6.5 => 3.6.5 
      @tarojs/plugin-html: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5 
      @tarojs/runtime: 3.6.5 => 3.6.5 
      @tarojs/shared: 3.6.5 => 3.6.5 
      @tarojs/taro: 3.6.5 => 3.6.5 
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5 
      babel-preset-taro: 3.6.5 => 3.6.5 
      eslint-config-taro: 3.6.5 => 3.6.5 
    npmGlobalPackages:
      typescript: 4.7.4
```

**Comment by AdvancedCat** [comment]
可以提供一下可复现的 DEMO 看看

**Comment by owmjess** [comment]
> 可以提供一下可复现的 DEMO 看看

taro3.5.6+vue3+typescript+webpack5+sass，这环境主贴上有复现步骤。

**Comment by AdvancedCat** [comment]
> > 可以提供一下可复现的 DEMO 看看
> 
> taro3.5.6+vue3+typescript+webpack5+sass，这环境主贴上有复现步骤。

`pnpm dlx @tarojs/cli@3.5.6 init demo-issue-13764` 按照你的步骤生成的demo并未出现类似问题。
