### ISSUE TITLE
npm run dev:h5 编译H5错误，微信小程序没有问题

### ISSUE THREAD

**Issue by dragon1061** [NervJS/taro#1377]
**问题描述**

[或者可以直接贴源代码，能贴文字就不要截图]
这是项目有做小部分开发报的错

👽 Taro v1.2.0-beta.6

开始编译项目 taroApp
创建  发现文件  src/.DS_Store
创建  发现文件  src/app.scss
创建  发现文件  src/app.tsx
创建  发现文件  src/index.html
创建  发现文件  src/components/tabbar/TabBar.tsx
创建  发现文件  src/pages/index/index.scss
创建  发现文件  src/pages/index/index.tsx

🙅   Failed to compile.

./node_modules/.1.5.1@taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
| 
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">

这是一个新项目报的错

👽 Taro v1.2.0-beta.6

开始编译项目 taroApp11
创建  发现文件  src/app.scss
创建  发现文件  src/app.tsx
创建  发现文件  src/index.html
创建  发现文件  src/pages/index/index.scss
创建  发现文件  src/pages/index/index.tsx

🙅   Failed to compile.

./.temp/app.js
Module not found: Can't resolve 'nervjs' in '/Users/oulongbo/Desktop/test/web/taroApp11/.temp'

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

**系统信息**

 - 操作系统: [e.g. mac os]
 - Taro 版本 [e.g. v.1.2.0 beta.6]
 - Node.js 版本 [e.g. v11.3.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
安装下项目依赖

**Comment by Littly** [comment]
taro-ui的问题
先降级到 taro-ui@1.5.0  后续taro-ui会有文档跟进

**Comment by cooliean** [comment]
我也遇到了  ：）
