### ISSUE TITLE
Page中设置navigationStyle:'custom'无效

### ISSUE THREAD

**Issue by XiaogeTek** [NervJS/taro#1378]
**问题描述**
1、在Page中设置navigationStyle:'custom'，nav bar并没有隐藏
2、在App中全局设置config.window.navigationStyle为custom，nav bar成功隐藏

```js

export default class Home extends Component {

  config = {
    navigationBarTitleText: '首页',
    navigationStyle:'custom',
  };
}

```

**期望行为**
Page中设置navigationStyle:'custom'能够隐藏当前Page的nav bar

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v1.2.0-beta.5]
 - Node.js 版本  [v10.14.1]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
你试试原生小程序行不行
