### ISSUE TITLE
希望能支持生成的页面路径直接自动添加到页面路径配置中，这样不用每次新建完之后手动去配置页面路径

### ISSUE THREAD

**Issue by wangyuan0108** [NervJS/taro#13785]
### 这个特性解决了什么问题？
taro create生成的页面需要手动添加页面路径，在生成页面之后自动加入到页面路径配置中

### 这个 API 长什么样？
taro create

[taro craete功能需求](https://github.com/NervJS/taro/issues/13428)

**Comment by AdvancedCat** [comment]
On my way ...

**Comment by TheKonka** [comment]
Duplicate of #13198
