### ISSUE TITLE
物料市场无法发布，保存发布报错，官方论坛也挂了

### ISSUE THREAD

**Issue by sonofmagic** [NervJS/taro#13795]
### 相关平台
微信小程序

**小程序基础库: 2.0.0**
**使用框架: React**

### 复现步骤
创建一个新物料，发布，报错
点击官方论坛link，报错

### 期望结果
可以发布新物料
可以上官方论坛

### 实际结果
不行

### 环境信息
```
  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.1 - ~\AppData\Local\pnpm\node.EXE
      Yarn: 1.22.18 - ~\AppData\Local\Yarn\bin\yarn.CMD
      npm: 8.19.3 - ~\AppData\Local\pnpm\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/react: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6
      react: ^18.0.0 => 18.2.0
```

**Comment by honlyHuang** [comment]
论坛目前使用： https://github.com/NervJS/taro/discussions 
物料市场目前可以的，报的错可以贴一下吗？

**Comment by sonofmagic** [comment]
![微信截图_20230509174109](https://user-images.githubusercontent.com/15621541/237058484-447a1726-6af3-449b-92ad-cffbbf89f066.png)
![微信截图_20230509174123](https://user-images.githubusercontent.com/15621541/237058487-59d2b1a4-55d4-4067-b44b-a3ffdaf65b30.png)


graphql request payload:
[{"operationName":null,"variables":{"plugin":{"desc":"taro-react-tailwind-vscode-template","tags":["tailwindcss"],"cover":"jfs/t1/172357/13/35828/18736/645a1517Fe4c3347c/bbcf6126ea694c48.jpg","category":2,"version":"1.0.0","filePath":"//storage.jd.com/taro-ext/83387080-ee4d-11ed-9d04-adafc1f48a91_taro-react-tailwind-vscode-template.zip","displayName":"taro-react-tailwind-vscode-template","contentPath":"/tmp/tmp-17691Pr22vjCkT9ME/README.md","platform":[1,2,3,4,5,6,7,8,9]}},"query":"mutation ($plugin: PluginCreateInput!) {\n  plugin: createPlugin(plugin: $plugin) {\n    _id\n    __typename\n  }\n}\n"}]

response

[{"errors":[{"message":"BAD_PARAMS","locations":[{"line":2,"column":3}],"path":["plugin"],"extensions":{"code":"{\"ctx\":{\"user\":\"6455c44d446c4e9e060a2ff9\"},\"error\":{\"isJoi\":true,\"name\":\"ValidationError\",\"details\":[{\"message\":\"\\\"&#21517;&#31216;\\\" length must be less than or equal to 20 characters long\",\"path\":[\"displayName\"],\"type\":\"string.max\",\"context\":{\"limit\":20,\"value\":\"taro-react-tailwind-vscode-template\",\"key\":\"displayName\",\"label\":\"名称\"}}],\"_object\":{\"desc\":\"taro-react-tailwind-vscode-template\",\"tags\":[\"tailwindcss\"],\"cover\":\"jfs/t1/172357/13/35828/18736/645a1517Fe4c3347c/bbcf6126ea694c48.jpg\",\"author\":\"6455c44d446c4e9e060a2ff9\",\"version\":\"1.0.0\",\"category\":2,\"filePath\":\"//storage.jd.com/taro-ext/83387080-ee4d-11ed-9d04-adafc1f48a91_taro-react-tailwind-vscode-template.zip\",\"contentPath\":\"/tmp/tmp-17691Pr22vjCkT9ME/README.md\",\"platform\":[1,2,3,4,5,6,7,8,9],\"displayName\":\"taro-react-tailwind-vscode-template\"}}}"}}],"data":null}]

**Comment by sonofmagic** [comment]
我所有的必填项都写了:
![微信截图_20230509174506](https://user-images.githubusercontent.com/15621541/237059187-d21538d9-7d5f-480a-8c49-47b2c890751d.png)
![微信截图_20230509174517](https://user-images.githubusercontent.com/15621541/237059198-b5bceff1-bf90-4c55-abf2-f90bb263e83f.png)

**Comment by sonofmagic** [comment]
经过测试，是发布插件的名称字符串，有20个的长度限制，目前前端控件没有做限制，后端`graphql server` 那里做了限制。

然后后端抛出错误之后，前端也没处理，就直接显示了一个未知错误 undefined，搞得我这样的用户摸不着头脑。

建议修复一下。
