### ISSUE TITLE
Input 组件在微信Skyline 模式下控制台报错

### ISSUE THREAD

**Issue by ljianc** [NervJS/taro#13792]
Input 组件在Skyline 模式下， [官方](https://developers.weixin.qq.com/miniprogram/dev/component/input.html)要求 `placeholder-style` 参数传对象，不传还报错(`<Input value="测试测试" />`):
![1683449664805](https://user-images.githubusercontent.com/10055508/236667841-dd07cd0b-68ce-4f50-bdc3-a5681f2b9faf.png)

目前定义的ts类型是字符串类型，暂时可以通过 `as any` 来解决`<Input value="测试测试" placeholderStyle={{} as any} />`

微信原生我试了，不传这个参数也可以，不报错。

希望改一下ts类型以支持传对象，并且处理一下不传参的情况

**Comment by TheKonka** [comment]
1、报错是小程序基础库问题，最新版本已无报错
2、placeholder-style 传的就是string，类型无需修改
