### ISSUE TITLE
微信小程序中 一监听innerAudioContext.onTimeUpdate，音频就paused不了，而且innerAudioContext.paused状态返回不对

### ISSUE THREAD

**Issue by yangyan123** [NervJS/taro#13793]
### 相关平台
微信小程序

**小程序基础库: 2.31.0**
**使用框架: React**

### 复现步骤
const MyA = ({ src }) => {
  const [duration, setDuration] = useState<number>(0);
  const [currentTime, setCurrentTime] = useState<number>(0);
  const [paused, setPaused] = useState<number>(true);
  const innerAudioContext = Taro.createInnerAudioContext();
  // innerAudioContext.autoplay = true;
  innerAudioContext.src =
    src || "https://storage.360buyimg.com/jdrd-blog/27.mp3";
  const listener = () => {
    setDuration(innerAudioContext.duration);
    setCurrentTime(innerAudioContext.currentTime);
  };
  // innerAudioContext.onTimeUpdate(listener);
  innerAudioContext.onPlay(() => {
    console.log("开始播放");
    innerAudioContext.onTimeUpdate(listener);
  });
  innerAudioContext.onPause(() => {
    console.log("开始播放11");
    innerAudioContext.offTimeUpdate(listener);
  });
  innerAudioContext.onError((res) => {
    console.log(111,res.errMsg);
    console.log(res.errCode);
  });
  // useEffect(() => {
  //   return () => innerAudioContext.offTimeUpdate(listener);
  // }, []);
  return (
    <View className="box audio">
      <Image
        className="left"
        onClick={() => {
          console.log(innerAudioContext)
          if (innerAudioContext.paused) {
            innerAudioContext.play(); // 播放
          } else {
            innerAudioContext.pause(); // 暂停
          }
        }}
        src={playBtn}
      />
      <View>
        <View
          className="name"
          onClick={() => {
            innerAudioContext.pause(); // 暂停
          }}
        >
          {getPathName(src)}
        </View>
        <View className="seek">
          <View> {Format("mm:ss", currentTime * 1000)}</View>
          <Slider
            step={1}
            value={currentTime}
            backgroundColor="#F2F0F0"
            activeColor="#EC1E38"
            blockSize={12}
            min={0}
            onChange={(e) => {
              innerAudioContext.seek(e.detail.value);
            }}
            // max={200}
          />
          <View> {Format("mm:ss", duration * 1000)}</View>
        </View>
      </View>
    </View>
  );
};

### 期望结果
可正常监听音频状态，正常切换播放状态，播放进度及音频长度

### 实际结果
一监听就卡顿

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.npm-global/bin/yarn
      npm: 9.2.0 - ~/.npm-global/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/react: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
      react: ^18.0.0 => 18.2.0 
```

**Comment by yangyan123** [comment]
哪个好心人看见，帮忙解决一下子

**Comment by Chen-jj** [comment]
@yangyan123 麻烦提供完整可复现的 demo，并注明详细的复现步骤

**Comment by yangyan123** [comment]
https://github.com/yangyan123/jwy-dealer.git
点击播放按钮，不断的重复播放,停止不了

**Comment by xuanzebin** [comment]
出现问题的原因是 innerAudioContext 被频繁初始化了，你需要将初始化的代码挪到 react 组件的外层来进行：

```ts
const innerAudioContext = Taro.createInnerAudioContext();
innerAudioContext.src = "https://storage.360buyimg.com/jdrd-blog/27.mp3";

const MyA = ({ src }) => {
   // ...
})

// ...
```

**Comment by yangyan123** [comment]
> ```ts
> const innerAudioContext = Taro.createInnerAudioContext();
> ```

那如果我多个音频，他不就联动了

**Comment by yangyan123** [comment]
> 出现问题的原因是 innerAudioContext 被频繁初始化了，你需要将初始化的代码挪到 react 组件的外层来进行：
> 
> ```ts
> const innerAudioContext = Taro.createInnerAudioContext();
> innerAudioContext.src = "https://storage.360buyimg.com/jdrd-blog/27.mp3";
> 
> const MyA = ({ src }) => {
>    // ...
> })
> 
> // ...
> ```

我又提交了一版，帮忙看一下，可以播放跟暂停了，但是onTimeUpdate拿不到数据
