### ISSUE TITLE
生成支付宝小程序时，提示页面不存在

### ISSUE THREAD

**Issue by asd39715** [NervJS/taro#13794]
### 相关平台
支付宝小程序

### 复现仓库
[https://gitee.com/koenger/taro_app.git](https://gitee.com/koenger/taro_app.git)
**小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
NODE_ENV=production taro build --type alipay --watch

用支付宝开发工具打开时，报错，提示页面不存在（页面路径是对的），微信小程序，QQ小程序，H5则正常

### 期望结果
生成支付宝小程序能正常打开

### 实际结果
生成支付宝小程序不能正常打开，提示页面不存在

### 环境信息
```
validFiles []

  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^3.6.0 => 3.6.0 
      @tarojs/mini-runner: 3.3.18 => 3.3.18 
      @tarojs/plugin-framework-react: ^3.6.0 => 3.6.0 
      @tarojs/plugin-mini-ci: ^3.4.4 => 3.4.4 
      @tarojs/react: ^3.3.18 => 3.3.18 
      @tarojs/runtime: 3.3.18 => 3.3.18 
      @tarojs/taro: ^3.3.18 => 3.3.18 
      @tarojs/webpack-runner: 3.3.18 => 3.3.18 
      babel-plugin-transform-taroapi: ^3.3.18 => 3.6.0 
      babel-preset-taro: 3.3.18 => 3.3.18 
      eslint-config-taro: 3.3.18 => 3.3.18 
      react: ^17.0.2 => 17.0.2 
```

---
### 补充信息
当前访问的页面不存在
可以尝试更新 XXX 或者看看其他服务
回到首页    更新小程序

这是页面上显示的信息

**Comment by xuanzebin** [comment]
没能复现你的情况，我这边拉代码下来之后运行 `NODE_ENV=production taro build --type alipay --watch` 是可以正常看到页面的
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/38971117/236977605-27d4c3b1-43b5-43ab-8404-09c6a580a2e1.png">

另外，你这个项目中 taro 相关的依赖存在版本没有对齐的情况，容易出现一些预期外的错误：
```
    npmPackages:
      @tarojs/components: ^3.6.0 => 3.6.0 
      @tarojs/mini-runner: 3.3.18 => 3.3.18 
      @tarojs/plugin-framework-react: ^3.6.0 => 3.6.0 
      @tarojs/plugin-mini-ci: ^3.4.4 => 3.4.4 
      @tarojs/react: ^3.3.18 => 3.3.18 
      @tarojs/runtime: 3.3.18 => 3.3.18 
      @tarojs/taro: ^3.3.18 => 3.3.18 
      @tarojs/webpack-runner: 3.3.18 => 3.3.18 
      babel-plugin-transform-taroapi: ^3.3.18 => 3.6.0 
      babel-preset-taro: 3.3.18 => 3.3.18 
      eslint-config-taro: 3.3.18 => 3.3.18 
      react: ^17.0.2 => 17.0.2 
```

建议统一升级到 3.6.6

**Comment by asd39715** [comment]
以上问题，安装 source-map 解决，但是支付宝小程序，还是加载不了，升级到3.6.6时，显示页面遇到了一点小问题，

提示

58a33d71-2be2-40d8-9479-17016a44a2b4:1 TypeError: Function(...) is not a function
    at Object.oyTv (vendors.js:2:1)
    at l (runtime.js:1:1)
    at Object._ (common.js:1:1)
    at l (runtime.js:1:1)
    at Object._ (app.js:1:1)
    at l (runtime.js:1:1)
    at Object.<anonymous> (app.js:1:1)
    at Object._ (app.js:1:1)
    at l (runtime.js:1:1)
    at Module._ (app.js:1:1)

**Comment by xuanzebin** [comment]
麻烦将升级 taro 版本后的 demo 再提交一版，我们再排查一下具体的问题
