### ISSUE TITLE
IOS环境下，input组件设置初始值时，第一次点击输入框聚焦，指针出现在初始内容最前面

### ISSUE THREAD

**Issue by sjhleo** [NervJS/taro#13809]
### 相关平台
微信小程序
IOS真机

**小程序基础库: 2.30.2**
**使用框架: React**

### 复现步骤
复现代码
```
import React from 'react';
import Taro from '@tarojs/taro';
import { View, Input, Text } from '@tarojs/components';


export default class InputPage extends React.Component {

  public constructor(props) {
    super(props);
  }

  public render(): JSX.Element {
    return (
      <View className='page'>
        <Input type='text' placeholder='test' value='12345678'/>
      </View>
    );
  }
}
```

### 期望结果
点击输入框聚焦，光标出现在内容的后面

### 实际结果
第一次点击聚焦光标永远在最前面，后面失焦后再点击光标才出现在初始内容的后面。设置其他类型比如number、digit也存在该问题

### 环境信息
```
👽 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      react: ^18.0.0 => 18.2.0
```

**Comment by xuanzebin** [comment]
经排查，是由于 wxml 模版的 cursor 初始值设置异常导致的，暂时没有很好的办法临时解决这个问题，会跟着下个 taro 版本一起修复上线。

**Comment by LYM0121** [comment]
经尝试，可采用，先设置focus+重新set初始值解决此问题
`      setTimeout(() => {
        setInputFocus(true);
        setKeyword(keyword);
      }, 400);`

**Comment by dawenxi897094320** [comment]
taro3.6.2还是有这个bug 怎么还没解决啊，求解决方案啊。

**Comment by Tom9402** [comment]
你们解决了吗？我通过在AtInput上面直接添加 cursor={-1}解决了
https://developers.weixin.qq.com/community/develop/doc/000aee5b0e4b5817e412e207f61c00
