### ISSUE TITLE
config/index.js 下配置安卓输出目录，可以自定义吗

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#13801]
### 这个特性解决了什么问题？
默认设置是
`rn: {
       appName: 'taroDemo',
        output: {
            ios: './ios/main.jsbundle',
            iosAssetsDest: './ios',
            android: './android/app/src/main/assets/index.android.bundle',
            androidAssetsDest: './android/app/src/main/res',
            // iosSourceMapUrl: '',
            iosSourcemapOutput: './ios/main.map',
            // iosSourcemapSourcesRoot: '',
            // androidSourceMapUrl: '',
            androidSourcemapOutput: './android/app/src/main/assets/index.android.map',
            // androidSourcemapSourcesRoot: '',
        }
}`
安卓是默认打包到assets目录下

### 这个 API 长什么样？
想要实现APP中自定义读取jsbundle路径，比如我想实现热更新功能，从服务端下载jsbundle，存储到SD卡中，app中去读取SD卡中的这个js；
现在放在assets目录下，无法动态写入

**Comment by zhiqingchen** [comment]
这个是默认的位置，可以搜索rn热更新的方案。通过原生先加载下载的jsbundle。
