### ISSUE TITLE
Taro3.X如何自定义入口，render时机和render指定节点

### ISSUE THREAD

**Issue by crimson968** [NervJS/taro#13826]
### 这个特性解决了什么问题？
希望能将taro的h5模块以微应用的形式接入以qiankun为基座的主应用

### 这个 API 长什么样？
暴露render方便自定义

**Comment by ZakaryCode** [comment]
指定应用节点可以使用过 [appId](https://nervjs.github.io/taro-docs/docs/app-config#appid)，其他需求请详细说明

**Comment by crimson968** [comment]
> 指定应用节点可以使用过 [appId](https://nervjs.github.io/taro-docs/docs/app-config#appid)，其他需求请详细说明

现在需要以微应用接入到qiankun主应用，目前找到不入口

**Comment by crimson968** [comment]
> 指定应用节点可以使用过 [appId](https://nervjs.github.io/taro-docs/docs/app-config#appid)，其他需求请详细说明

从app.ts中导出的生命周期主应用获取不到

**Comment by ZakaryCode** [comment]
> 从app.ts中导出的生命周期主应用获取不到

具体需求是？app 的生命周期与所使用的框架相关联，这些不会开放给外部应用获取

**Comment by crimson968** [comment]
> > 从app.ts中导出的生命周期主应用获取不到
> 
> 具体需求是？app 的生命周期与所使用的框架相关联，这些不会开放给外部应用获取

这个应用需要以子应用的形式公用

**Comment by ZakaryCode** [comment]
> 这个应用需要以子应用的形式公用

那可以自定义入口即可，也不需要冗余的操作

> 需要作为微应用 有相关接微应用的方案吗

这个可自行配置，与普通应用改造方案并无差异

**Comment by crimson968** [comment]
> > 这个应用需要以子应用的形式公用
> 
> 那可以自定义入口即可，也不需要冗余的操作
> 
> > 需要作为微应用 有相关接微应用的方案吗
> 
> 这个可自行配置，与普通应用改造方案并无差异
自定义入口是指自定义app.ts吗

**Comment by crimson968** [comment]
> > 这个应用需要以子应用的形式公用
> 
> 那可以自定义入口即可，也不需要冗余的操作
> 
> > 需要作为微应用 有相关接微应用的方案吗
> 
> 这个可自行配置，与普通应用改造方案并无差异

我试了下替换entry为自定义的入口，在taro里貌似不可行

**Comment by ZakaryCode** [comment]
> 我试了下替换entry为自定义的入口，在taro里貌似不可行

指定 [appId](https://nervjs.github.io/taro-docs/docs/app-config#appid) 加载应用即可

**Comment by crimson968** [comment]
> > 这个应用需要以子应用的形式公用
> 
> 那可以自定义入口即可，也不需要冗余的操作
> 
> > 需要作为微应用 有相关接微应用的方案吗
> 
> 这个可自行配置，与普通应用改造方案并无差异



> > 我试了下替换entry为自定义的入口，在taro里貌似不可行
> 
> 指定 [appId](https://nervjs.github.io/taro-docs/docs/app-config#appid) 加载应用即可

这个appid只是设置渲染的容器id吧，和自定义入口有关联么

**Comment by crimson968** [comment]
可能没描述清楚，指定appId我已经指定了，但是taro和普通应用接入qiankun感觉还是有差异的
因为没有办法在定义render的入口暴露qiankun生命周期，app.ts并不是定义render的入口

**Comment by ZakaryCode** [comment]
> 因为没有办法在定义render的入口暴露qiankun生命周期，app.ts并不是定义render的入口

打包应用不支持 mount / unmount 操作，如需要可以控制 appId 对应节点的隐藏；如果需要通过类似 ReactDOM.render / ReactDOM.unmountComponentAtNode 方法控制，可以通过 native-components 模式（注意，该模式不包括应用生命周期等相关内容）

**Comment by crimson968** [comment]
> > 因为没有办法在定义render的入口暴露qiankun生命周期，app.ts并不是定义render的入口
> 
> 打包应用不支持 mount / unmount 操作，如需要可以控制 appId 对应节点的隐藏；如果需要通过类似 ReactDOM.render / ReactDOM.unmountComponentAtNode 方法控制，可以通过 native-components 模式（注意，该模式不包括应用生命周期等相关内容）

好的，那我理解taro是不支持以子应用的方式接入qiankun的

**Comment by ZakaryCode** [comment]
> 好的，那我理解taro是不支持以子应用的方式接入qiankun的

也不能这样说，虽然缺少 mount / unmount 的官方支持，但是能按需注入实际上就已经是qiankun的子应用了。

另外组件模式接入虽然会缺少应用级的事件和方法，但是其他组件和 API 也能够满足绝大多数需求；如果一定需要对应用进一步控制，也可以通过注入 extraImportForWeb / execBeforeCreateWebApp 方法调整注入方案，或者基于 webpackChain 覆盖 `@tarojs/taro-loader/lib/h5` 来调整入口。

**Comment by crimson968** [comment]
> > 好的，那我理解taro是不支持以子应用的方式接入qiankun的
> 
> 也不能这样说，虽然缺少 mount / unmount 的官方支持，但是能按需注入实际上就已经是qiankun的子应用了。
> 
> 另外组件模式接入虽然会缺少应用级的事件和方法，但是其他组件和 API 也能够满足绝大多数需求；如果一定需要对应用进一步控制，也可以通过注入 extraImportForWeb / execBeforeCreateWebApp 方法调整注入方案，或者基于 webpackChain 覆盖 `@tarojs/taro-loader/lib/h5` 来调整入口。

谢谢大佬提供思路，我再尝试尝试

**Comment by crimson968** [comment]
> 另外组件模式接入虽然会缺少应用级的事件和方法，但是其他组件和 API 也能够满足绝大多数需求；如果一定需要对应用进一步控制，也可以通过注入 extraImportForWeb / execBeforeCreateWebApp 方法调整注入方案，或者基于 webpackChain 覆盖 `@tarojs/taro-loader/lib/h5` 来调整入口。

试了一下extraImportForWeb / execBeforeCreateWebApp和@tarojs/taro-loader/lib/h5的方式在本地运行时是可以增强app.boot.js的逻辑，但本地运行时qiankun访问的taro入口实际上是app.js，在app.js中获取不到qiankun的周期函数，好像还是不可行

**Comment by lbf911531** [comment]
> > 另外组件模式接入虽然会缺少应用级的事件和方法，但是其他组件和 API 也能够满足绝大多数需求；如果一定需要对应用进一步控制，也可以通过注入 extraImportForWeb / execBeforeCreateWebApp 方法调整注入方案，或者基于 webpackChain 覆盖 `@tarojs/taro-loader/lib/h5` 来调整入口。
> 
> 试了一下extraImportForWeb / execBeforeCreateWebApp和@tarojs/taro-loader/lib/h5的方式在本地运行时是可以增强app.boot.js的逻辑，但本地运行时qiankun访问的taro入口实际上是app.js，在app.js中获取不到qiankun的周期函数，好像还是不可行

打扰了，请问您现在实现了将taro改造为qiankun子应用吗
