### ISSUE TITLE
swiper 循环轮播不生效

### ISSUE THREAD

**Issue by jiangjingmin** [NervJS/taro#1382]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
hello 请补充一下
 - Taro 版本 [e.g. v.0.0.64]
 - 报错平台 [h5, weapp]
 - 可复现代码
这三条信息

**Comment by jiangjingmin** [comment]
问题描述
[问题描述：swiper在设置了circular循环轮播后，不生效，且自动轮播到最后一个后停止轮播]

复现步骤
[复现问题的步骤]

Go to '...'
Click on '....'
Scroll down to '....'
See error
[或者可以直接贴源代码，能贴文字就不要截图]
index.js
 <Swiper
            className='banner-swiper'
            current='0'
            indicatorColor='#fff'
            indicatorActiveColor='#f86c2e'
            indicatorDots='true'
            circular='true'
            autoplay='true' 
            interval='5000' 
            duration='500'
          >
            { this.state.bannerList.map((item, index) => {
              return (<SwiperItem key={index} onClick={this.toBannerLind(item.bannerLink)}>
                <Image style='width: 100%;height: 100%;background: #fff;' src={item.bannerUrl}></Image>
              </SwiperItem>)
            })}
          </Swiper>

期望行为
[这里请用简洁清晰的语言描述你期望的行为]
正常自动循环轮播
报错信息
无报错信息
[这里请贴上你的完整报错截图或文字]

系统信息

操作系统: [ Windows 10]
Taro 版本 [1.2.0-beta.7]

Node.js 版本 [v10.8.0]
报错平台 [h5,]
补充信息
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
circular属性未生效，因为html里没有循环复制的dom

**Comment by jinjinjin0731** [comment]
好，晚点看一下

**Comment by jinjinjin0731** [comment]
更新到最近版本即可
