### ISSUE TITLE
H5触发了下拉刷新后页面无法向上滚动

### ISSUE THREAD

**Issue by Youngwellcool** [NervJS/taro#13846]
### 相关平台
H5

### 复现仓库
[https://github.com/Youngwellcool/taroTest.git](https://github.com/Youngwellcool/taroTest.git)
**浏览器版本: 企业微信或iPhone的safari浏览器**
**使用框架: Vue 3**

### 复现步骤
1、页面内容的高度没有超过手机屏幕高度
2、触发下拉刷新后，然后滚动页面，页面顶部的内容被遮挡了，滑动不了了

大概分析了下原因是因为：
.taro_router与.rmc-pull-to-refresh-content-wrapper设置了min-height=100vh，在某些浏览器的可用高度不等于100vh的情况，比如企业微信和safari浏览器，设置100vh，分别为724px，716px，但是他们的真实可用高度分别为690px，635px，于是，页面就会出现滚动条，下拉后，页面会就无法向上滚动了
然后我在每个页面中使用js强制将.taro_router与.rmc-pull-to-refresh-content-wrapper的min-height设置为Taro.getSystemInfoSync().windowHeight，发现问题解决了

### 期望结果
H5触发了下拉刷新后在企业微信或iPhone的safari浏览器中，页面可以向上滚动

### 实际结果
H5触发了下拉刷新后在企业微信或iPhone的safari浏览器中，页面无法向上滚动

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
```

**Comment by MRS-WU** [comment]
查询不到.rmc-pull-to-refresh-content-wrapper，怎么用js修改它的css样式

**Comment by Youngwellcool** [comment]
您好，你的邮件我已经收到了。谢谢！

**Comment by Youngwellcool** [comment]
> 查询不到.rmc-pull-to-refresh-content-wrapper，怎么用js修改它的css样式

要开启下拉刷新才有

**Comment by ZakaryCode** [comment]
> 然后我在每个页面中使用js强制将.taro_router与.rmc-pull-to-refresh-content-wrapper的min-height设置为Taro.getSystemInfoSync().windowHeight，发现问题解决了

min-height 样式已被移除

**Comment by Youngwellcool** [comment]
您好，你的邮件我已经收到了。谢谢！
