### ISSUE TITLE
官方文档-事件处理一章

### ISSUE THREAD

**Issue by zzlit** [NervJS/taro#1384]
**问题描述**
官方文档中事件处理一章开始的[例子](https://nervjs.github.io/taro/docs/event.html)出现了`React.Component`，另外例子跑不通。

**复现步骤**
将代码复制运行即可。

```
class Toggle extends React.Component {
  constructor (props) {
    super(props)
    this.state = {isToggleOn: true}
  }

  onClick = (e) => {
    e.stopPropagation()
    this.setState(prevState => ({
      isToggleOn: !prevState.isToggleOn
    }))
  }

  render () {
    return (
      <button onClick={this.onClick}>
        {this.state.isToggleOn ? 'ON' : 'OFF'}
      </button>
    )
  }
}
```

**期望行为**
能运行。

**报错信息**
无报错信息但onClick事件没有触发。

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.0]
 - Node.js 版本 [e.g. v8.11.3]
 - 报错平台 [weapp]

**补充信息**
```
    import { View, Text, Button } from '@tarojs/components'
    
    <Button onClick={this.onClick}>
      {this.state.isToggleOn ? 'ON' : 'OFF'}
    </Button>
```

**Comment by luckyadam** [comment]
文档有误，你应该直接生成一个示例项目来看看里面的代码
```js
import Taro from '@tarojs/taro'
class Toggle extends Taro.Component {
```

**Comment by zzlit** [comment]
> 文档有误，你应该直接生成一个示例项目来看看里面的代码
> 
> ```js
> import Taro from '@tarojs/taro'
> class Toggle extends Taro.Component {
> ```

是的，但按照文档前后的例子来看都是引入的组件，像这里引入Button可以解决，我只是感觉文档写的不明确。
