### ISSUE TITLE
this.state 的变量名不能与 render 的变量名重名

### ISSUE THREAD

**Issue by grubxy** [NervJS/taro#1385]
**问题描述**
className使用变量渲染后样式变成“true”。

**复现步骤**
`	render() {
		const nameClass = 'panel__info';
		return (
			<View className='page'>
				<View className='panel__title'>作者</View>
				<View className='panel__content'>
					<View className='at-row at-row__align--center'>
						<View className='at-col at-col-2'>
							<AtAvatar circle size='small' image={this.props.avatarUrl}/>
						</View>
						<View className='at-col at-col'>
							<Text className={nameClass} onClick={this.handleLogin.bind(this)}>
								{this.formateNickName(this.props.nickName)}
							</Text>
						</View>
					</View>
				</View>
			</View>
		)
	}`

**报错信息**

![image](https://user-images.githubusercontent.com/1298241/49504100-ffd84c80-f8b3-11e8-8d34-4c9d7c337357.png)

**系统信息**

 - 操作系统: [ Windows 7]
 - Taro 版本 [v1.1.8]
 - Node.js 版本 [e.g. v8.11.2]
 - 报错平台 [weapp]

**Comment by grubxy** [comment]
> ![image](https://user-images.githubusercontent.com/7202516/49507395-52693700-f8bb-11e8-9fef-c91164798592.png)
> 没能复现，升级一下到最新的 beta 版本

taro版本已升级，我这边复现了下，在components下会出现，在page下正常。

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/49556720-0ad8be80-f940-11e8-98b1-80478027ec5c.png)


在类中也没法复现
