### ISSUE TITLE
出现Template `tmpl_0_20` not found.这怎错误，找不到什么原因

### ISSUE THREAD

**Issue by XAllure** [NervJS/taro#13855]
### 相关平台
微信小程序

**小程序基础库: 2.32.0**
**使用框架: Vue 3**

### 复现步骤
<view class="login">
		<nut-form @submit="submit" :model-value="userInfo" ref="formRef" class="login-box">
			<nut-form-item>
				<button
					class="avatar-wrapper"
					open-type="chooseAvatar"
					@chooseavatar="chooseAvatar"
				>
					<image class="avatar" :src="userInfo.headimgurl || ''"></image>
				</button>
			</nut-form-item>
			<nut-form-item prop="nickname" required>
				
				<nut-input
					v-model="userInfo.nickname"
					type="nickname"
					placeholder="请输入昵称"
					name="nickname"
					:border="false"
				>
					<template #left> <my2 /> </template>
				</nut-input>
			</nut-form-item>
			<nut-form-item prop="phone" required>
				
				<nut-input
					v-model="userInfo.phone"
					type="digit"
					placeholder="请输入手机号"
					name="phone"
					:border="false"
				>
					<template #left> <people /> </template>
				</nut-input>
			</nut-form-item>
			<nut-button form-type="submit" size="large" type="primary" class="login-bind">
				绑定账号
			</nut-button>
		</nut-form>
	</view>

### 期望结果
没有错误

### 实际结果
Template `tmpl_0_13` not found.
<template name="tmpl_2_container">
<template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}" />
 </template>
<template name="tmpl_3_0">

### 环境信息
```
Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.15.0 - D:\software\nodejs\node.EXE
      npm: 9.5.0 - D:\software\nodejs\npm.CMD
```

**Comment by XAllure** [comment]
![image](https://github.com/NervJS/taro/assets/66450680/37c1bc23-33db-4222-bf02-232009eb11f2)
不知道怎么解决

**Comment by Chen-jj** [comment]
麻烦提供一下 demo 与详细复现说明

**Comment by TheKonka** [comment]
可以尝试把 taro 版本全部升级到最新版本
