### ISSUE TITLE
如何设置Input组件的value值的字体样式，我通过font-family试了下没生效

### ISSUE THREAD

**Issue by YesanQin** [NervJS/taro#13862]
### 这个特性解决了什么问题？
value值要求是宋体，但是设置不了

### 这个 API 长什么样？
透露value的样式设置api，如同placeholder透露出了响应的属性来设置一样

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/15731e65-54bd-4825-a87f-b3d318338762)

这个好像改不了吧？
