### ISSUE TITLE
更新到最新版的trao出现微信小程序转换需要错误

### ISSUE THREAD

**Issue by mienv567** [NervJS/taro#1386]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

[astro【小程序代码+转换错误taro代码】.zip](https://github.com/NervJS/taro/files/2648750/astro.%2B.taro.zip)
**复现步骤**
[复现问题的步骤]
```
安装
nodejs
taro-cli 更新到最新
转义命令 taro convert

![p5qq w hz _qz 68naksb5](https://user-images.githubusercontent.com/7724835/49512942-6cf6dc80-f8ca-11e8-9753-719bfe7c644e.png)
错误  页面转换  pages/detail/index.js
TypeError: Cannot read property 'attributes' of undefined
    at NodePath._getKey (/usr/lib/node_modules/@tarojs/cli/node_modules/babel-traverse/lib/path/family.js:148:23)
转换  页面样式  pages/diceInstructions/index.wxss
错误  页面转换  pages/diceInstructions/index.js
TypeError: Duplicate declaration "windowWidth" (This is an error on an internal node. Probably an internal error)

```
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

希望能转义成功再次开发，并且能运行出页面

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: linux
 - Taro 版本 Taro v1.2.0-beta.7
 - Node.js 版本 v11.3.0
 - 报错平台 小程序转trao

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by mienv567** [comment]
@yuche 帮看看

**Comment by luckyadam** [comment]
升级到 1.2.0-beta.9 试试

**Comment by mienv567** [comment]
@luckyadam 12点后我试试. beta.5正常

**Comment by luckyadam** [comment]
用 1.2.0-beta.9

**Comment by yuche** [comment]
@mienv567 转换没报错修改就是你自己的事了，你自己更熟悉你自己的代码，我们不能帮你写代码也不能帮你 debug，更何况你的代码都压缩了。例如用 0 来循环这种事情小程序可以，react 不行，你得自己去找问题了。

**Comment by hu-qi** [comment]
和楼主一样的问题
![image](https://user-images.githubusercontent.com/17986122/50197783-a37d2e80-0383-11e9-8e11-82e1c91cc99b.png)

升级到最新版本就行了
`
taro update self
`
已完美解决
![image](https://user-images.githubusercontent.com/17986122/50197833-dd4e3500-0383-11e9-9f6d-0d5ae5ad1731.png)

**Comment by mienv567** [comment]
嗯，早就解决这个问题了
