### ISSUE TITLE
无法打包成H5

### ISSUE THREAD

**Issue by nayuta19** [NervJS/taro#13865]
### 相关平台
H5

**浏览器版本: Chrome **
**使用框架: React**

### 复现步骤
 taro update project 后npm run dev:h5

### 期望结果
能出现H5页面

### 实际结果
(node:19620) UnhandledPromiseRejectionWarning: Error: 插件依赖 "@tarojs/plugin-platform-h5" 加载失败，请检查插件配置

### 环境信息
```
 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/react: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
可以打包成微信小程序，但H5不行

**Comment by nayuta19** [comment]
> 手动安装依赖 @tarojs/plugin-platform-h5 试过了，还是报这个错

**Comment by hellowalker** [comment]
<img width="580" alt="image" src="https://github.com/NervJS/taro/assets/25142334/1359fdac-9528-4f72-8726-5aa56e061b4a">

安装后启动 @tarojs/plugin-inject代码报错

**Comment by ZakaryCode** [comment]
低版本升级上来可以手动安装缺失依赖，如依旧存在问题可以提交新的 issue 并附上完整可现 demo

> <img alt="image" width="580" src="https://user-images.githubusercontent.com/25142334/240509442-1359fdac-9528-4f72-8726-5aa56e061b4a.png">
> 安装后启动 @tarojs/plugin-inject代码报错

依赖未对齐，请检查相关依赖版本
