### ISSUE TITLE
Taro 3.6.6 分包 sub-common 下未产出 sourcemap

### ISSUE THREAD

**Issue by alexlees** [NervJS/taro#13873]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/alexlees/sub_sourcemap_demo.git](https://github.com/alexlees/sub_sourcemap_demo.git)
**小程序基础库: 无关小程序基础版本**
**使用框架: React**

### 复现步骤
1. 新建项目
2. 配置产出sourcemap
3. 新建两个 分包
4. 两个分包中引入同一JS代码

具体可参考：https://github.com/alexlees/sub_sourcemap_demo/commit/e952869b6b3a3e461351f0fe0f8b1901eee2198b

### 期望结果
按照配置产出 sourcemap 以便定位问题

### 实际结果
无 sourcemap 产出

### 环境信息
```
👽 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.9 - /home/linuxbrew/.linuxbrew/bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6 
      @tarojs/react: 3.6.6 => 3.6.6 
      @tarojs/runtime: 3.6.6 => 3.6.6 
      @tarojs/shared: 3.6.6 => 3.6.6 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6 
      babel-preset-taro: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
按文档以及日志猜想应该是忘记 copy sourcemap 文件

![36a358d4-e731-48b1-8e61-92519ff53764](https://github.com/alexlees/sub_sourcemap_demo/assets/38124537/1a42cb28-b41b-44cf-ad00-ce083ccb15b3)

![503c5b53-61b1-405b-9917-4080fab6d8d2](https://github.com/alexlees/sub_sourcemap_demo/assets/38124537/97f98a46-f9b3-45e4-9683-dcbb1cbd052e)

![image](https://github.com/alexlees/sub_sourcemap_demo/assets/38124537/fa010f11-3654-4be3-b74a-291d06894f1b)

**Comment by xiaochong2021** [comment]
为什么我vue3， taro3.6.23版本还有这个问题

**Comment by zzy348429898** [comment]
3.6.23,也还有这个问题

**Comment by cma290** [comment]
为啥我没分包 但是产物也没有任何sourcemap 呢 3.6.35 了都

**Comment by zzy348429898** [comment]
邮件已经收到，我会尽快查收。
