### ISSUE TITLE
trao H5 配置devService还是不能跨域请求

### ISSUE THREAD

**Issue by gonganruyi** [NervJS/taro#13878]
### 相关平台
H5

**浏览器版本: chrome 62**
**使用框架: React**

### 复现步骤
devServer: {
      port: 33322,
      proxy: {
        '/api': {
            target: 'xxxxxxx',  // 服务端地址
            changeOrigin: false
        }
      }
    },

### 期望结果
可以跨域

### 实际结果
不能跨域

### 环境信息
```
Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /var/folders/hj/7t2x9vy904lg54h551w1jjpm0000gn/T/yarn--1684559888260-0.9846808361101889/node
      Yarn: 1.17.3 - /var/folders/hj/7t2x9vy904lg54h551w1jjpm0000gn/T/yarn--1684559888260-0.9846808361101889/yarn
      npm: 9.6.6 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.4.4
```

**Comment by gonganruyi** [comment]
已经解决

**Comment by LionLion001** [comment]
> 解决

请问是如何解决的

**Comment by CMrookie** [comment]
在proxy里面加上secure: false试试

**Comment by WildernessZyr** [comment]
> > 解决
> 
> 请问是如何解决的

我是这样配置解决的，这个框架用起来真的是，心累
h5: {
    webpackChain(chain){
      chain.devServer
      .proxy({
          '/api': {
              target: '’, // 目标 API 地址
              changeOrigin: true, // 是否跨域
              pathRewrite: { '^/api': '' }, // 重写路径
          },
      });
    },
},
