### ISSUE TITLE
字节小程序 编译 data-* 自定义属性丢失

### ISSUE THREAD

**Issue by SentoIsuzu** [NervJS/taro#13872]
### 相关平台
字节跳动小程序

**小程序基础库: 2.81.1.81**
**使用框架: Vue 3**

### 复现步骤
 

``` <view data-id="id"> <button open-type="share"  data-channel="video"><button></view>```` 

 添加data-* 自定义属性后，编译出来的结果会丢失  

### 期望结果
编译后保留 data-id = "id" data-channel="video" 等自定义属性

### 实际结果
编译为 
 
``` <view><button open-type="share"  data-channel="undefined"></button></view>``` 

自定义属性丢失

### 环境信息
```
Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5 
      @tarojs/components: 3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5 => 3.6.5 
      @tarojs/plugin-framework-vue3: 3.6.5 => 3.6.5 
      @tarojs/plugin-html: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5 
      @tarojs/runtime: 3.6.5 => 3.6.5 
      @tarojs/shared: 3.6.5 => 3.6.5 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5 
      babel-preset-taro: 3.6.5 => 3.6.5 
      eslint-config-taro: 3.6.5 => 3.6.5 
```

**Comment by SentoIsuzu** [comment]
<view data-id="id"><button open-type="share"  data-channel="video"></button></view>

**Comment by SentoIsuzu** [comment]
原始结构 ` <view data-id="id"><button open-type="share"  data-channel="video"></button></view>`

**Comment by AdvancedCat** [comment]
可以使用 [@tarojs/plugin-inject](https://www.npmjs.com/package/@tarojs/plugin-inject) 插件，向组件注入自定义属性。不在注册范围内的属性都会被过滤，这是出于精简模板考虑。

**Comment by SentoIsuzu** [comment]
> 可以使用 [@tarojs/plugin-inject](https://www.npmjs.com/package/@tarojs/plugin-inject) 插件，向组件注入自定义属性。不在注册范围内的属性都会被过滤，这是出于精简模板考虑。
谢谢老哥

**Comment by AdvancedCat** [comment]
麻烦新开一个 issue 进行讨论吧，应该可以修复的

**Comment by SentoIsuzu** [comment]
> 麻烦新开一个 issue 进行讨论吧，应该可以修复的

已经解决了，通过驼峰的方式是可行的，谢谢

**Comment by zmm2tysu** [comment]
> > 麻烦新开一个 issue 进行讨论吧，应该可以修复的
> 
> 已经解决了，通过驼峰的方式是可行的，谢谢

@SentoIsuzu 请问咋解决的啊？我这样用驼峰法，编译出来的是data-imtype， data-imid，data-imopenid
```
Button: {
  'data-im-open-id': "",
  'data-im-type': "",
  'data-im-id': "",
}

<Button dataImId='1' dataImOpenId='2' dataImType='3' openType='im'>
</Button>

```

**Comment by zmm2tysu** [comment]
> 可以使用 [@tarojs/plugin-inject](https://www.npmjs.com/package/@tarojs/plugin-inject) 插件，向组件注入自定义属性。不在注册范围内的属性都会被过滤，这是出于精简模板考虑。

@AdvancedCat 另外请教下，像这种注入的属性，怎么添加typescript呢？不然在使用的时候会报错找不到该属性

**Comment by AdvancedCat** [comment]
> @tarojs/plugin-inject

README 文档最下方有说明

**Comment by yuerdev** [comment]
> > 麻烦新开一个 issue 进行讨论吧，应该可以修复的
> 
> 已经解决了，通过驼峰的方式是可行的，谢谢

大佬，你是怎么解决的，我也遇到这个问题了

**Comment by surplusChi** [comment]
> > 麻烦新开一个 issue 进行讨论吧，应该可以修复的
> 
> 已经解决了，通过驼峰的方式是可行的，谢谢

你好，我遇到了相同的问题，请问你是如何解决的？能否把代码贴出来

**Comment by uu109** [comment]
> 可以使用 [@tarojs/plugin-inject](https://www.npmjs.com/package/@tarojs/plugin-inject) 插件，向组件注入自定义属性。不在注册范围内的属性都会被过滤，这是出于精简模板考虑。

@tarojs/plugin-inject 只能一个组件一个组件地加自定义属性吗，有没有什么方法可以允许一个自定义属性不被过滤掉，所有标签都能加上
