### ISSUE TITLE
[FR] 热重载 Hot Reload

### ISSUE THREAD

**Issue by wenfangdu** [NervJS/taro#13876]
### 这个特性解决了什么问题？
目前的实现每次修改代码，不管是在哪个页面，整个 app 都会重启回到首页，开发体验不佳。

### 这个 API 长什么样？
支持热加载，当前页面的代码修改后，路由保持不变，只更新当前页面修改的部分。

**Comment by jackple** [comment]
刷新了, 是不回到首页了, 但是我改了字后界面没变化啊!!!

**Comment by gggyuanlin** [comment]
你好，这个修改代码热重载后app重启回到首页的问题，这边你解决了吗， 是怎么解决的呢， 我在taro@3.6.20版本依然有这个问题

**Comment by Puggo1145** [comment]
同，3.6.29 依然有这个问题，对页面做任何更改都会刷新回主页面
