### ISSUE TITLE
Button的开发能力uploadDouyinVideo和onUploadDouyinVideo 钩子是在taro没开放吗

### ISSUE THREAD

**Issue by lyj6464** [NervJS/taro#13882]
### 这个特性解决了什么问题？
解决抖音小程序点击按钮进行拍摄发日常

### 这个 API 长什么样？
跟抖音小程序的文档一样  https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/open-interface/video-capacity/upload-douyin-video/#_uploadparams-%E8%AF%B4%E6%98%8E

**Comment by AdvancedCat** [comment]
基本思路：
1. 在 `@tarojs/runtime` 包（或 TT 端平台插件）的 `createPageConfig()` 中添加 `onUploadDouyinVideo` 监听；
2. 在 `@tarojs/taro` 提供 `useUploadDouyinVideo` 的 hook，供开发者注册回调；

**Comment by lyj6464** [comment]
我找到一个方法
onReady(){
    console.log('onReadyonReadyonReady: ',this.$instance)
    this.$instance.page.onUploadDouyinVideo = function(uploadOptions) {  
        console.log('onUploadDouyinVideoOptions: ', uploadOptions)  
    }  
 }

**Comment by AdvancedCat** [comment]
this.$instance 从何而来的？

**Comment by SentoIsuzu** [comment]
> 我找到一个方法 onReady(){ console.log('onReadyonReadyonReady: ',this.$instance) this.$instance.page.onUploadDouyinVideo = function(uploadOptions) { console.log('onUploadDouyinVideoOptions: ', uploadOptions) } }

老哥，我也遇到了这个问题，细说一下，this.$instance 这个从哪里获取啊

**Comment by lyj6464** [comment]
> this.$instance 从何而来的？

getCurrentInstance()，获取当前页面实例

**Comment by lyj6464** [comment]
`
import Taro, {  getCurrentInstance } from '@tarojs/taro';
$instance = getCurrentInstance()
`

**Comment by AdvancedCat** [comment]
> `import Taro, { getCurrentInstance } from '@tarojs/taro'; $instance = getCurrentInstance()`

没毛病
