### ISSUE TITLE
taro版本3.5.5，打包后低版本微信浏览器白屏，node_modules未编辑成es5

### ISSUE THREAD

**Issue by aiqingsheng** [NervJS/taro#13895]
### 相关平台
H5

**浏览器版本: 2.6.8微信浏览器**
**使用框架: React**

### 复现步骤
1、执行npm run build:h5之后，将dist打包内容上传到服务器
2、2.6.8版本的微信浏览器无法打开界面，会出现白屏问题
3、需升级微信版本使其支持es6语法才可正常当问

### 期望结果
通过修改配置文件，可以将第三方包es6语法进行babel编译

### 实际结果
2.6.8版本微信浏览器白屏

### 环境信息
```
Taro v3.5.8


  Taro CLI 3.5.8 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.8 => 3.6.6
      @tarojs/components: 3.5.5 => 3.6.6
      @tarojs/components-react: 3.5.5 => 3.6.6
      @tarojs/mini-runner: 3.5.5 => 3.6.6
      @tarojs/plugin-framework-react: 3.5.5 => 3.6.6
      @tarojs/react: 3.5.5 => 3.6.6
      @tarojs/runtime: 3.5.5 => 3.6.6
      @tarojs/taro: 3.5.5 => 3.6.6
      @tarojs/webpack-runner: 3.5.5 => 3.6.6
      babel-preset-taro: 3.5.5 => 3.6.6
      eslint-config-taro: 3.5.5 => 3.6.6
      react: ^17.0.0 => 17.0.2
      taro-ui: 3.1.0-beta.2 => 3.1.0-beta.2
    npmGlobalPackages:
      typescript: 4.9.5
```

**Comment by aiqingsheng** [comment]
prod.js中增加配置不生效：
` chain.merge({
        module: {
          rules: [
            {
              test: /\.(js|jsx|ts\tsx)$/,
              include: /(node_modules|bower_components)/,
              use: {
                loader: "babel-loader",
                options: {
                  presets: ["@babel/preset-env"],
                },
              },
            },
          ],
        },
      });`

**Comment by aiqingsheng** [comment]
app.tsx中增加不生效：
`const reduce = Function.bind.call(Function.call, Array.prototype.reduce);
const isEnumerable = Function.bind.call(
  Function.call,
  Object.prototype.propertyIsEnumerable
);
const concat = Function.bind.call(Function.call, Array.prototype.concat);
const keys = Reflect.ownKeys;
if (!Object.entries) {
  Object.entries = function entries(O) {
    return reduce(
      keys(O),
      (e, k) =>
        concat(
          e,
          typeof k === "string" && isEnumerable(O, k) ? [[k, O[k]]] : []
        ),
      []
    );
  };
}`

**Comment by a992681784** [comment]
@aiqingsheng 请问下 后面解决了吗？遇到同样的问题了

**Comment by Yevunye** [comment]
@a992681784 请问你解决了么
我也遇到同样问题了
