### ISSUE TITLE
map中怎样渲染多个类型的子组件

### ISSUE THREAD

**Issue by tudousi991112** [NervJS/taro#1389]
**问题描述**
[问题描述：map中，有多个组件根据不同分类，渲染不同的组件，但是map中不支持 if else 判断语句，该如何更好的将组件分别进行渲染？]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

list:[
        {
          type:"1",
          title:"卡片1"
        },
        {
          type:"2",
          title:"卡片2"
        },
        {
          type:"3",
          title:"卡片3"
        },
        {
          type:"4",
          title:"卡片4"
        },
        {
          type:"5",
          title:"卡片5"
        }
      ]

render () {
    const {list} = this.state;
    return(   
      list.map((item,key) => {
        if(item.type == '1'){
          return <Card1 key={key}/>
        }else if(item.type == '2'){
          return <Card2 key={key}/>
        }else if(item.type == '3'){
          return <Card3 key={key}/>
        }else if(item.type == '4'){
          return <Card4 key={key}/>
        }
      })
      
    )
  }
**期望行为**
[目前Taro规范中介绍到不能在包含 JSX 元素的 map 循环中使用 if 表达式，提倡尽量在 map 循环中使用条件表达式或逻辑表达式，那这种组件类型很多的情况下怎么渲染？]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. macOs 10.12.6]
 - Taro 版本 [e.g. v.1.1.9]
 - Node.js 版本 [e.g. v11.2.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[目前，将4个子组件包在了一层大组件中，map渲染大组件，再去大组件中判断分类，渲染不同子组件也能够实现，想请教有没有更优的方式。]

**Comment by luckyadam** [comment]
有多种做法
1、用逻辑运算符，&& 等等
2、把 map 里的内容抽成一个组件，在组件里去用 if 判断

**Comment by tudousi991112** [comment]
已经解决，感谢
