### ISSUE TITLE
在入口文件app.tsx内的constructor调用Taro.Current.app为null

### ISSUE THREAD

**Issue by hcxmj** [NervJS/taro#13903]
### 相关平台
支付宝小程序

**小程序基础库: 2.8.9**
**使用框架: React**

### 复现步骤
在constructor内执行下列代码发现无法进入执行        
     if(Current.app) {
            Current.app[key] = conf[key];
          }
打印Current.app结果是{app: null, router: null, page: null}

### 期望结果
constructor获取到的Current.app不为null

### 实际结果
Current.app结果是{app: null, router: null, page: null}，初始化完成后有值包含一些生命周期

### 环境信息
```
👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/mini-runner: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/react: 3.6.2 => 3.6.2 
      @tarojs/router: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/taro-h5: 3.6.2 => 3.6.2 
      @tarojs/webpack-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.4 
```

**Comment by TheKonka** [comment]
最新版本没有复现

![image](https://github.com/NervJS/taro/assets/22173084/b54bfa68-e74e-41c3-a786-36cc11e7bb52)
![image](https://github.com/NervJS/taro/assets/22173084/99f060ec-29c1-4d74-b566-b20abe70ca44)

**Comment by hcxmj** [comment]
> 
这个最新版是哪个版本呢，可以贴一下版本信息吗，或者如果回退到我使用的版本能够复现吗

**Comment by hcxmj** [comment]
> 最新版本没有复现
> 
> ![image](https://user-images.githubusercontent.com/22173084/241105396-b54bfa68-e74e-41c3-a786-36cc11e7bb52.png) ![image](https://user-images.githubusercontent.com/22173084/241105489-99f060ec-29c1-4d74-b566-b20abe70ca44.png)
这是我的执行结果
<img width="695" alt="image" src="https://github.com/NervJS/taro/assets/58494807/38989085-e2aa-4b96-b5ae-4e9592f7f457">
<img width="741" alt="image" src="https://github.com/NervJS/taro/assets/58494807/f224805b-eb3e-4025-bca8-0c9bac7fe6f5">

**Comment by AdvancedCat** [comment]
你用的哪个 React 版本？

**Comment by hcxmj** [comment]
> 你用的哪个 React 版本？
17.0.2
<img width="760" alt="image" src="https://github.com/NervJS/taro/assets/58494807/43f985ac-87bb-4f9c-bf40-327864635735">

**Comment by TheKonka** [comment]
```
👽 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/helper: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/plugin-framework-react: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/plugin-platform-alipay: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/plugin-platform-weapp: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/react: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/router: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/runtime: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/taro: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      @tarojs/webpack5-runner: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      babel-preset-taro: 3.6.6-alpha.3 => 3.6.6-alpha.3 
      react: ^18.2.0 => 18.2.0 
```

**Comment by hcxmj** [comment]
> ```
> 👽 Taro v3.6.6
> 
> 
>   Taro CLI 3.6.6 environment info:
>     System:
>       OS: macOS 13.3.1
>       Shell: 5.9 - /bin/zsh
>     Binaries:
>       Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
>       Yarn: 1.22.17 - ~/.yarn/bin/yarn
>       npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
>     npmPackages:
>       @tarojs/components: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/helper: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/plugin-framework-react: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/plugin-platform-alipay: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/plugin-platform-weapp: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/react: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/router: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/runtime: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/taro: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       @tarojs/webpack5-runner: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       babel-preset-taro: 3.6.6-alpha.3 => 3.6.6-alpha.3 
>       react: ^18.2.0 => 18.2.0 
> ```

好的，我尝试一下

**Comment by AdvancedCat** [comment]
> > 你用的哪个 React 版本？
> > 17.0.2
> 
> <img alt="image" width="760" src="https://user-images.githubusercontent.com/58494807/241120410-43f985ac-87bb-4f9c-bf40-327864635735.png">

React 18 使用了新的 Concurrent Root，挂载组件时是异步的，因此 App 类也是在异步中进行的实例化，所以在 constructor 可以读取到 Taro.Current 参数；

React 17 仍使用的 LegacyRoot，组件挂载过程是同步的，而 Taro.Current.app 暂未赋值

**Comment by AdvancedCat** [comment]
![image](https://github.com/NervJS/taro/assets/7858761/eb76d4d4-a75f-4cdd-a6d9-fb2b92186121)

React 18 下的流程：
1. createReactApp 函数中会对 Taro.Current 赋值；
2. React 组件在异步中挂载；
3. App 类实例化；

**Comment by hcxmj** [comment]
> > > 你用的哪个 React 版本？
> > > 17.0.2
> > 
> > 
> > <img alt="image" width="760" src="https://user-images.githubusercontent.com/58494807/241120410-43f985ac-87bb-4f9c-bf40-327864635735.png">
> 
> React 18 使用了新的 Concurrent Root，挂载组件时是异步的，因此 App 类也是在异步中进行的实例化，所以在 constructor 可以读取到 Taro.Current 参数；
> 
> React 17 仍使用的 LegacyRoot，组件挂载过程是同步的，而 Taro.Current.app 暂未赋值

我刚升级完taro版本到3.6.6版本发现打印的还是空，我试着升级下react版本试试看

**Comment by hcxmj** [comment]
<img width="1113" alt="image" src="https://github.com/NervJS/taro/assets/58494807/e00b5004-8b58-489a-832e-406d3b29cc75">
升级完react版本再次运行后报错信息比较奇怪，项目无法正常运行了
<img width="311" alt="image" src="https://github.com/NervJS/taro/assets/58494807/0100074d-610d-4ae5-b583-d9d8a88d02c4">

**Comment by TheKonka** [comment]
用的 webpack 4？

**Comment by hcxmj** [comment]
> 用的 webpack 4？

<img width="900" alt="image" src="https://github.com/NervJS/taro/assets/58494807/f7725ea4-9981-4b8e-b1cc-dc12ecb011a2">
@tarojs/webpack-runner这个吗，没有像普通react项目一样专门使用webpack进行打包

**Comment by TheKonka** [comment]
```
// config/index.js

compiler: {
  type: 'webpack5',
  prebundle: {
	enable: false
  }
},
```
安装 `@tarojs/webpack5-runner`

**Comment by hcxmj** [comment]
> ```
> // config/index.js
> 
> compiler: {
>   type: 'webpack5',
>   prebundle: {
> 	enable: false
>   }
> },
> ```
> 
> 安装 `@tarojs/webpack5-runner`

好的，我试试，谢谢

**Comment by hcxmj** [comment]
> @tarojs/webpack5-runner

安装使用了这个插件配套react18使用，还是报错同样的问题，请问还有其他的思路帮忙看看吗，报错信息是一样的

**Comment by hcxmj** [comment]
> ```
> // config/index.js
> 
> compiler: {
>   type: 'webpack5',
>   prebundle: {
> 	enable: false
>   }
> },
> ```
> 
> 安装 `@tarojs/webpack5-runner`

<img width="982" alt="image" src="https://github.com/NervJS/taro/assets/58494807/ecfddf85-59bf-44d3-89d2-00b2c3546426">
配置添加好后的报错比较奇怪

**Comment by hcxmj** [comment]
> ```
> // config/index.js
> 
> compiler: {
>   type: 'webpack5',
>   prebundle: {
> 	enable: false
>   }
> },
> ```
> 
> 安装 `@tarojs/webpack5-runner`

看了下应该是升级webpack5没有成功，最终在node包里看webpack的版本还是4.x
<img width="435" alt="image" src="https://github.com/NervJS/taro/assets/58494807/73d8326f-0519-402a-9ec7-d53c1ded2487">

**Comment by hcxmj** [comment]
> arojs/webpack5-runner

好的，我尝试下主动升级，另外在webpack4版本下，把complier改一下type发现也可以正常运行

**Comment by hcxmj** [comment]
> 这个我忘了讲了，webpack包 也需要手动升级到 5

主动升级也是OK的，感谢大家！ @AdvancedCat @TheKonka

**Comment by djllhs** [comment]
我用的webpack5，tarojs 3.6.15,依旧出现Taro.Current.app 为空的情况。页面白屏，没有任何报错
![image](https://github.com/NervJS/taro/assets/17997964/5915b861-fa5d-4cec-95f0-fb08832625e8)
@TheKonka

**Comment by TheKonka** [comment]
@djllhs   白屏可能是其他原因，可以单独提个 issue 并提供demo

**Comment by junbinxu** [comment]
> > > 你用的哪个 React 版本？
> > > 17.0.2
> > 
> > 
> > <img alt="image" width="760" src="https://user-images.githubusercontent.com/58494807/241120410-43f985ac-87bb-4f9c-bf40-327864635735.png">
> 
> React 18 使用了新的 Concurrent Root，挂载组件时是异步的，因此 App 类也是在异步中进行的实例化，所以在 constructor 可以读取到 Taro.Current 参数；
> 
> React 17 仍使用的 LegacyRoot，组件挂载过程是同步的，而 Taro.Current.app 暂未赋值



> ![image](https://private-user-images.githubusercontent.com/7858761/241132552-eb76d4d4-a75f-4cdd-a6d9-fb2b92186121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTU0MzQsIm5iZiI6MTcwMTMxNTEzNCwicGF0aCI6Ii83ODU4NzYxLzI0MTEzMjU1Mi1lYjc2ZDRkNC1hNzVmLTRjZGQtYTZkOS1mYjJiOTIxODYxMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDMzMjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNlODU4NzBiZGRiOWVkNzVmNWJmODNhMzlmNjI4OTZhZmI1NGE3NGIyM2UzNmYxYjUwNDdiYmVjOGFmNzZiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Az-I86YHQNBtkrtJDO_NFaekOYGeAPCt9ad526uQWOA)
> 
> React 18 下的流程：
> 
> 1. createReactApp 函数中会对 Taro.Current 赋值；
> 2. React 组件在异步中挂载；
> 3. App 类实例化；

@AdvancedCat 哈喽，如果是react17的话，只能通过升级react来解决这个  Taro.Current  问题吗
