### ISSUE TITLE
「疑问」请问 Taro 的 Storage 在小程序间共享嘛

### ISSUE THREAD

**Issue by wenfangdu** [NervJS/taro#13922]
比如我在 A 小程序设置了：

```js
Taro.setStorage({
  key: 'foo',
  data: 'bar',
})
```

B 小程序通过以下代码可以拿到 `foo` 的值嘛？

```js
Taro.getStorage({
  key: 'foo',
  success(res) {
    console.log(res.data)
  },
})
```

**Comment by TheKonka** [comment]
这个跟 taro 没关系， taro 只是帮你调用微信的api ， 这就涉及到微信小程序自己的机制问题了。
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/storage.html
![image](https://github.com/NervJS/taro/assets/22173084/0be97187-c90a-46ac-9484-bb21b6419f40)
根据微信小程序官方文档，可以得出结论是不共享的
