### ISSUE TITLE
Taro动态添加dom

### ISSUE THREAD

**Issue by fangbicheng** [NervJS/taro#13932]
### 这个特性解决了什么问题？
Taro怎么在page标签下动态添加元素，类似document.appendChild。

### 这个 API 长什么样？
主要是想要实现一个弹窗，可以挂载在page下。

**Comment by AdvancedCat** [comment]
参考案例：
taro3 react：https://github.com/AdvancedCat/taro-react-portal
taro3 vue：https://github.com/AdvancedCat/taro-vue-teleport
