### ISSUE TITLE
taro-plugin-http 包处理 httpOnly Cookie 错误

### ISSUE THREAD

**Issue by kong-dev** [NervJS/taro#13941]
### 相关平台
微信小程序

**小程序基础库: any**
**使用框架: React**

### 复现步骤
- 服务端的 Set-Cookie 响应头中包含 httpOnly 属性；
- 下次发送 HTTPS 协议的请求时不会携带包含 httpOnly 属性的 Cookie；

### 错误原因

> You can ensure that cookies are sent securely and aren't accessed by unintended parties or scripts in one of two ways: with the Secure attribute and the HttpOnly attribute.
>
> A cookie with the Secure attribute is only sent to the server with an encrypted request over the HTTPS protocol. It's never sent with unsecured HTTP (except on localhost), which means [man-in-the-middle](https://developer.mozilla.org/en-US/docs/Glossary/MitM) attackers can't access it easily. Insecure sites (with http: in the URL) can't set cookies with the Secure attribute. However, don't assume that Secure prevents all access to sensitive information in cookies. For example, someone with access to the client's hard disk (or JavaScript if the HttpOnly attribute isn't set) can read and modify the information.
>
> A cookie with the HttpOnly attribute is inaccessible to the JavaScript [Document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) API; it's only sent to the server. For example, cookies that persist in server-side sessions don't need to be available to JavaScript and should have the HttpOnly attribute. This precaution helps mitigate cross-site scripting ([XSS](https://developer.mozilla.org/en-US/docs/Web/Security/Types_of_attacks#cross-site_scripting_(xss))) attacks.
>
> Here's an example:
>
> ```
> Set-Cookie: id=a3fWa; Expires=Thu, 21 Oct 2021 07:28:00 GMT; Secure; HttpOnly
> ```
>
来源： [MDN 文档](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies)

根据上述文档：httpOnly 属性的作用是仅限服务端读写，JS 不可访问。但下列代码中的处理逻辑却是仅限 http 协议请求才携带 httpOnly 属性的 Cookie。

https://github.com/NervJS/taro/blob/34554fb03fd3f9498307b2f9a0e4b60b41f94829/packages/taro-plugin-http/src/runtime/Cookie.ts#LL219C14-L219C14

### 环境信息
```
👽 Taro v3.6.7


  Taro CLI 3.6.7 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.2.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.6.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/react: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/service: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
      react: ^18.2.0 => 18.2.0 


```

**Comment by bigmeow** [comment]
1. includeHttpOnly  是个选项，目前默认值是false， 所以 document.cookie 是获取不到带了httponly属性的cookie的；
2. https://github.com/NervJS/taro/blob/34554fb03fd3f9498307b2f9a0e4b60b41f94829/packages/taro-plugin-http/src/runtime/XMLHttpRequest.ts#LL225C39-L225C39 这个位置的代码需要能获取到带了httpOnly的cookie,可能需要改一下
3. 小程序只支持https协议
4.  我在考虑是否把 includeHttpOnly 的选项直接改为true ,还是修复2的问题，因为小程序环境不用考虑第三方脚本获取cookie的问题

**Comment by bigmeow** [comment]
你现在遇到的问题是 ：服务端设置了 httpOnly 的cookie， 在下次请求时， cookie没有携带到新的请求头上，是吧？

**Comment by wlsu** [comment]
> ```
>     "@tarojs/components": "3.6.35",
>     "@tarojs/components-advanced": "^4.0.6",
>     "@tarojs/helper": "3.6.35",
>     "@tarojs/plugin-framework-react": "3.6.35",
>     "@tarojs/plugin-http": "^4.0.6",
> ```
> 
> `[ '@tarojs/plugin-http', { enableCookie: true, disabledFormData: true, disabledBlob: true, }, ],`
> 
hi, 发现 
* 		set-cookie: JSESSIONID=0743D2E6B565A8A0D68C56129A7C5E45; Path=/webservices; Secure; HttpOnly
* 		set-cookie: TS01406fb8=2425bfd6063b70cc0b0425588b755e77e; Path=/; Secure; HttpOnly; SameSite=Strict;
JSESSIONID失敗；TS01406fb8 成功；看分別是一個path=/ 一個 Path=/webservices; 請問path導致失敗嗎？可以讓Path也成功帶過去嗎？謝謝

**Comment by wlsu-shoalter** [comment]
找到原因了，plugin会把 request 都变成 https://taro.com/pages/cart/index?%24taroTimestamp=1729695570814； urlPath=/pages/cart ； cookiePath=/webservices(真实api path)，导致对比path时失败；这个应该是bug; @bigmeow 请问是否会再修复？ 谢谢

**Comment by wlsu** [comment]
找到原因了，plugin会把 request 都变成 [https://taro.com/pages/cart/index?%24taroTimestamp=1729695570814；](https://taro.com/pages/cart/index?%24taroTimestamp=1729695570814%EF%BC%9B) urlPath=/pages/cart ； cookiePath=/webservices(真实api path)，导致对比path时失败；这个应该是bug; @bigmeow 请问是否会再修复？ 谢谢
