### ISSUE TITLE
[FR] `Taro.relaunch(option)`

### ISSUE THREAD

**Issue by wenfangdu** [NervJS/taro#13940]
### 这个特性解决了什么问题？
Relaunch 是一个单词，Re Launch 看起来很蛋疼……（微信小程序带的好头

### 这个 API 长什么样？
`Taro.relaunch(option)` 作为 `Taro.reLaunch(option)` 的 alias 也能使用。

**Comment by bigmeow** [comment]
还是保持一致吧，除非微信后续自己的sdk 也出来个 alias
