### ISSUE TITLE
打包后报错，无法访问页面

### ISSUE THREAD

**Issue by parabolazz** [NervJS/taro#13951]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/parabolazz/face-to-guy.git](https://github.com/parabolazz/face-to-guy.git)
**小程序基础库: 2.32.0**
**使用框架: Vue 3**

### 复现步骤
1. 安装依赖
2. npm run dev:weapp  页面可访问
3. npm run build:weapp 微信开发者工具页面报错

### 期望结果
打包后页面依然可访问

### 实际结果
页面报错，无法访问
![image](https://github.com/NervJS/taro/assets/17560446/1f7a5c2c-1abc-4d5a-b5c2-42817c7a73a6)

### 环境信息
```
👽 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6 
      @tarojs/plugin-html: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6 
      @tarojs/plugin-vue-devtools: 3.6.6 => 3.6.6 
      @tarojs/runtime: 3.6.6 => 3.6.6 
      @tarojs/shared: 3.6.6 => 3.6.6 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6 
      babel-preset-taro: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 
```

---
### 补充信息
我没有改过taro的打包配置

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/6c77b8f5-d45b-4e8b-87b0-bb758dfd9296)
虽然，但是，我运行起来了

**Comment by parabolazz** [comment]
请问是跑的npm run build:weapp 命令吗？您的node版本是多少？

**Comment by parabolazz** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/243231242-6c77b8f5-d45b-4e8b-87b0-bb758dfd9296.png)
> 虽然，但是，我运行起来了
> 补充：@tarojs/components-advanced 没有在package.json里面，我手动安装了

请问是跑的npm run build:weapp 命令吗？您的node版本是多少？

**Comment by TheKonka** [comment]
node 18 + pnpm 8

**Comment by parabolazz** [comment]
> node 18 + pnpm 8

你好，我换了另外一台电脑，使用了和你相同的版本，重新进行 build，结果还是不行：
<img width="261" alt="image" src="https://github.com/NervJS/taro/assets/17560446/ac77e9fd-174d-4661-8b88-e82f921c5798">
<img width="802" alt="image" src="https://github.com/NervJS/taro/assets/17560446/660bcfcb-c0e6-41ce-97c9-72bf95d336c3">
<img width="1152" alt="image" src="https://github.com/NervJS/taro/assets/17560446/9e33230c-ab37-475c-8b82-d55420afe08d">
想知道可能是什么原因呢

**Comment by parabolazz** [comment]
> > node 18 + pnpm 8
> 
> 你好，我换了另外一台电脑，使用了和你相同的版本，重新进行 build，结果还是不行： <img alt="image" width="261" src="https://user-images.githubusercontent.com/17560446/243242139-ac77e9fd-174d-4661-8b88-e82f921c5798.png"> <img alt="image" width="802" src="https://user-images.githubusercontent.com/17560446/243242115-660bcfcb-c0e6-41ce-97c9-72bf95d336c3.png"> <img alt="image" width="1152" src="https://user-images.githubusercontent.com/17560446/243242076-9e33230c-ab37-475c-8b82-d55420afe08d.png"> 想知道可能是什么原因呢

删除了node_modules后重新安装，似乎可以了，我再观察一下，非常感谢！
