### ISSUE TITLE
[Bug] `Taro.getAccountInfoSync()` 不支持字节小程序

### ISSUE THREAD

**Issue by wenfangdu** [NervJS/taro#13957]
### 相关平台
字节跳动小程序

### 复现仓库
https://github.com/wenfangdu/taro-nutui/tree/getEnvInfoSync
**小程序基础库: 2.68.1.4**
**使用框架: Vue 3**

### 复现步骤
1. `pnpm run dev:tt`
2. 点击按钮

对应的字节小程序 API：https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync

### 期望结果
无报错

### 实际结果
<img width="1229" alt="image" src="https://github.com/NervJS/taro/assets/28700378/5e89bb02-7f26-4636-b81d-4e3126b13c06">

### 环境信息
```
Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.2.15 - /opt/homebrew/bin/bash
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 9.6.7 - ~/Library/pnpm/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-vue3: 3.6.7 => 3.6.7 
      @tarojs/plugin-html: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
```

**Comment by TheKonka** [comment]
不是一个东西吧，首先，Taro.getAccountInfoSync() 在字节小程序里面对于的就是 tt.getAccountInfoSync() 而不是  tt.getEnvInfoSync(), 再者，你这个链接是小游戏的文档，不是小程序的文档

**Comment by wenfangdu** [comment]
@TheKonka 抱歉，链接放错了，https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync，Taro 有类似 `tt.getEnvInfoSync()` 的方法嘛？

**Comment by wenfangdu** [comment]
https://developer.open-douyin.com/forum/question/post/624d41af35567d58e53b64f0

没有 `tt.getAccountInfoSync()` 这个方法呢

**Comment by wenfangdu** [comment]
@TheKonka `tt.getEnvInfoSync()` 是可以的，`Taro.getEnvInfoSync()` 返回的是一个一直 pending 的 Promise，明显是不对的，想尽可能用 Taro 的方法，少调平台的方法

**Comment by TheKonka** [comment]
这是因为 taro 把这个api Promise化了
https://github.com/NervJS/taro/blob/52c0d36e12afce719c42b5855e53b341d98453d2/packages/taro-tt/src/apis-list.ts#L11
把这一行删掉就行了

**Comment by wenfangdu** [comment]
@TheKonka 对应的类型是在哪添加的呢，我也来加下

**Comment by wenfangdu** [comment]
@TheKonka 对应的类型是在哪添加的呢，我也来加下

**Comment by wenfangdu** [comment]
@TheKonka 对应的类型是在哪添加的呢，我也来加下

**Comment by TheKonka** [comment]
> getAccountInfoSync

packages/taro/types/api
