### ISSUE TITLE
SwiperItem上绑定onClick事件不执行

### ISSUE THREAD

**Issue by hcxmj** [NervJS/taro#13967]
### 相关平台
支付宝小程序

**小程序基础库: 2.8.9**
**使用框架: React**

### 复现步骤
添加一个轮播图demo，转支付宝平台，在轮播图上绑定点击事件，点击时无任何事件响应

### 期望结果
点击事件正常执行

### 实际结果
点击事件无法执行

### 环境信息
```
👽 Taro v3.5.11


  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: ^3.6.7 => 3.6.7 
      @tarojs/components: ^3.6.7 => 3.6.7 
      @tarojs/helper: ^3.6.7 => 3.6.7 
      @tarojs/mini-runner: ^3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: ^3.6.7 => 3.6.7 
      @tarojs/react: ^3.6.7 => 3.6.7 
      @tarojs/router: ^3.6.7 => 3.6.7 
      @tarojs/runtime: ^3.6.7 => 3.6.7 
      @tarojs/shared: ^3.6.7 => 3.6.7 
      @tarojs/taro: ^3.6.7 => 3.6.7 
      @tarojs/taro-h5: ^3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: ^3.6.7 => 3.6.7 
      babel-preset-taro: ^3.6.7 => 3.6.7 
      eslint-config-taro: ^3.6.7 => 3.6.7 
      react: ^18.2.0 => 18.2.0 
      taro-ui: ^2.3.4 => 2.3.4 
```
`import { Swiper, SwiperItem, Image } from "@tarojs/components";

export default function TestBanner() {

  const banners = [
    {
      url: 'http://pic3.iqiyipic.com/lequ/common/lego/20230603/fe3a0fd5cb1741f9af155ff5600ad354.jpg?caplist=jpg',
    },
    {
      url: 'http://pic3.iqiyipic.com/lequ/common/lego/20230603/fe3a0fd5cb1741f9af155ff5600ad354.jpg?caplist=jpg',
    },
    {
      url: 'http://pic3.iqiyipic.com/lequ/common/lego/20230603/fe3a0fd5cb1741f9af155ff5600ad354.jpg?caplist=jpg',
    },
  ]

  const clickBaner = (index: number) => {
    console.log('index', index);
  }

  return (
    <Swiper autoplay>
      {
        banners.map((item, index) => {
          return (
            <SwiperItem key={index} onClick={() => clickBaner(index)}>
              <Image src={item.url}></Image>
            </SwiperItem>
          )
        })
      }
    </Swiper>
  )
}`

**Comment by TheKonka** [comment]
这种问题可以看下小程序原生写法是否支持，我试了支付宝小程序原生写法好像也是点击无反应的

**Comment by hcxmj** [comment]
> 这种问题可以看下小程序原生写法是否支持，我试了支付宝小程序原生写法好像也是点击无反应的

好的，谢谢
