### ISSUE TITLE
cell组件支持desc的slot

### ISSUE THREAD

**Issue by lanrenbulan** [NervJS/taro#13989]
### 这个特性解决了什么问题？
可以自定义desc

### 这个 API 长什么样？
desc支持slot

**Comment by TheKonka** [comment]
哪个 ui 库的组件？ 是不是发错地方了？

**Comment by lanrenbulan** [comment]
不好意思，是发错位置了。nutui

**Comment by lanrenbulan** [comment]
> 哪个 ui 库的组件？ 是不是发错地方了？

不好意思，是发错位置了。nutui

**Comment by Chen-jj** [comment]
先关闭咯~
