### ISSUE TITLE
跳转props undefined的问题 

### ISSUE THREAD

**Issue by WihteCrow** [NervJS/taro#1398]
**问题描述**
页面初始化时候，可以拿到props数据
但是页面跳转的时候，拿到的是undefined

**复现步骤**
[复现问题的步骤]
1. app 页面
![image](https://user-images.githubusercontent.com/3975498/49568446-fad6d400-f96b-11e8-97a2-103eba3d00a2.png)
2. Positioning 页面
![image](https://user-images.githubusercontent.com/3975498/49568467-075b2c80-f96c-11e8-8312-c3202c578ddf.png)

3. 通过Taro.navigateTo 跳转结果
![image](https://user-images.githubusercontent.com/3975498/49568503-235ece00-f96c-11e8-8245-c0a88d562441.png)

4. 初始化的时候，是有数据的
![image](https://user-images.githubusercontent.com/3975498/49568529-340f4400-f96c-11e8-8273-977ca0c16e06.png)

**期望行为**
是我使用方式不对吗？希望可以解决

**系统信息**

 - 操作系统: Mac OS X 10.14.1
 - Taro 版本 1.2.0-beta.9
 - Node.js 版本 v10.4.1
 - 报错平台 weapp/alipay

**Comment by WihteCrow** [comment]
没问题，大佬帮我瞅瞅

**Comment by neoscript99** [comment]
Taro 版本 1.2.0-beta.9　，初始化无登录信息，跳转登录界面时，有相同问题

**Comment by luckyadam** [comment]
Taro.navigateTo 和页面主动刷新，获取数据的方式不一样，不建议把对 props 的操作放到 constructor
你可以在 `componentWillMount` 里通过调用 `this.setState` 做 state 的初始化操作

**Comment by neoscript99** [comment]
@luckyadam 
- 我是在首页的componentDidShow中检查是否有登录信息，如果没有跳转登录页面，并没有在constructor处理props。
![image](https://user-images.githubusercontent.com/11485735/49621564-eb559a80-fa00-11e8-8ae9-27ab18cc11a4.png)
- 登录页面代码
```
import Taro, {Component} from '@tarojs/taro'
import {View} from '@tarojs/components'
import {observer, inject} from '@tarojs/mobx'
import {AtInput, AtButton} from 'taro-ui'

import {onChange} from '../../utils/eventUtil'
import config from '../../utils/config'
import Toast from '../../component/Toast';

@inject('manager')
@observer
class Login extends Component {

  state = {name: config.devUserName, workNo: config.devUserWorkNo};

  componentWillReact() {
    super.componentWillReact();
    if (this.props.manager.currentItem.id)
      Taro.navigateBack({delta: 1});
  }

  onLogin() {
    this.props.manager.managerLogin(this.state)
  }

  handleInput(key, v) {
    onChange(this, key, v)
  }

  render() {
    return (
      <View className='flex-col page-card' style='height: 400rpx;justify-content: space-around;'>
        <AtInput title='姓名' type='text' placeholder='您的姓名' value={this.state.name}
                 onChange={this.handleInput.bind(this, 'name')} />
        <AtInput title='工号' type='number' placeholder='您的工号(数字)' value={this.state.workNo}
                 onChange={this.handleInput.bind(this, 'workNo')} />
        <AtButton type='primary' onClick={this.onLogin} disabled={!this.state.name || !this.state.workNo}>登录</AtButton>
        <Toast />
      </View>
    );
  }
}

export default Login;

```

**Comment by WihteCrow** [comment]
@luckyadam 不建议是指什么，有点不明白。是本身不支持在constructor中初始化 state，还是我使用的方式不对。

**Comment by neoscript99** [comment]
> @luckyadam 不建议是指什么，有点不明白。是本身不支持在constructor中初始化 state，还是我使用的方式不对。

应该是某些场景的constructor中，props还没准备好，建议你在componentWillMount中初始化state。
