### ISSUE TITLE
Cannot use import statement outside a module in

### ISSUE THREAD

**Issue by FuncWei** [NervJS/taro#13984]
### 相关平台
H5

**浏览器版本: Chrome最新**
**使用框架: React**

### 复现步骤
根据官网安装配置linaria，build:weapp没问题，build:h5时报错：
EvalError: Cannot use import statement outside a module in
| /node_modules/@stencil/core/internal/client/index.js
| /node_modules/@tarojs/components/dist/components/taro-view-core.js
| /node_modules/@tarojs/components/dist/components/index.js
| /node_modules/@tarojs/components/lib/react/components.js
|/taroai/node_modules/@tarojs/components/lib/react/index.js
| /src/pages/linariaDemo/index.jsx
    at runMicrotasks (<anonymous>)
    at runMicrotasks (<anonymous>)

### 期望结果
无

### 实际结果
无

### 环境信息
```
"@linaria/core": "4.2.10",
"@linaria/react": "4.3.8",
"@linaria/babel-preset": "^4.4.5",
"@linaria/webpack-loader": "^4.1.17",

  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/react: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.5 
```

---
### 补充信息
linaria.config.js rules在官网的基础上加：
{
      test: (filename, code) => {
        if (!/[\\/]node_modules[\\/]/.test(filename)) {
          return false;
        }

        return /\b(?:export|import)\b/.test(code);
      },
      action: require.resolve('@linaria/shaker'),
    },

报错信息有变化：
EvalError: Unexpected token 'export' in
| /node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js
| /node_modules/@stencil/core/internal/client/index.js
| /node_modules/@tarojs/components/dist/components/taro-view-core.js
| /node_modules/@tarojs/components/dist/components/index.js
| /node_modules/@tarojs/components/lib/react/components.js
| /node_modules/@tarojs/components/lib/react/index.js
| /src/pages/linariaDemo/index.jsx
    at runMicrotasks (<anonymous>)
    at runMicrotasks (<anonymous>)

**Comment by ZakaryCode** [comment]
请检查项目依赖是否完整，同时该问题需提交完整可现 demo 用于定位问题。
