### ISSUE TITLE
能否增加打印setData日志的开关

### ISSUE THREAD

**Issue by ljianc** [NervJS/taro#13994]
### 这个特性解决了什么问题？
每次想看setData的内容，都需要手动在dist/Taro.js增加两行日志打印，
重新生成又被覆盖回去了，很麻烦，在配置文件中能否增加打印setData日志的开关
![1686301431265](https://github.com/NervJS/taro/assets/10055508/d1efa10b-2d73-4f86-a785-80204012f268)

### 这个 API 长什么样？
希望增加个是否打印setData的开关

**Comment by Chen-jj** [comment]
有的，dev 模式下添加 `Taro.options.debug = true`，也就是上述截图中 `if (false) {}` 的两句（在 production 模式被 webpack 裁剪了）

**Comment by ljianc** [comment]
> 有的，dev 模式下添加 `Taro.options.debug = true`，也就是上述截图中 `if (false) {}` 的两句（在 production 模式被 webpack 裁剪了）

`Taro.options.debug = true` 是添加在哪里？

**Comment by ljianc** [comment]
还有个问题，示例代码：
```
function Details() {

  const [state, setState] = useState("loading");

  useEffect(() => {
    setState("complete");
  }, []);

  return state;
}
```

通过 `console.log("执行setData了", normalUpdate);`  直接打印，两次都打印的是`complete`：
![image](https://github.com/NervJS/taro/assets/10055508/6345c370-ab5b-4b28-81b2-6b1750736827)

而克隆后再打印`console.log("执行setData了",JSON.parse(JSON.stringify(normalUpdate)));` ，结果是正确的：
![1686486181508](https://github.com/NervJS/taro/assets/10055508/7d700133-e5cc-409b-b75e-aa599e0afbcc)

**Comment by Chen-jj** [comment]
> > 有的，dev 模式下添加 `Taro.options.debug = true`，也就是上述截图中 `if (false) {}` 的两句（在 production 模式被 webpack 裁剪了）
> 
> `Taro.options.debug = true` 是添加在哪里？

随便找个地方写就行。

**Comment by Chen-jj** [comment]
> 通过 `console.log("执行setData了", normalUpdate);` 直接打印，两次都打印的是`complete`： ![image](https://user-images.githubusercontent.com/10055508/244935334-6345c370-ab5b-4b28-81b2-6b1750736827.png)
> 
> 而克隆后再打印`console.log("执行setData了",JSON.parse(JSON.stringify(normalUpdate)));` ，结果是正确的： ![1686486181508](https://user-images.githubusercontent.com/10055508/244935998-7d700133-e5cc-409b-b75e-aa599e0afbcc.png)

`console.log` 在控制台展示的对象是同一个引用，所以你最后再观察肯定是最终态。你可以加入断点来观察，或者 console.log 对象 JSON.stringify 之后的值。
