### ISSUE TITLE
`taro build --type h5 --watch`报错

### ISSUE THREAD

**Issue by JJJJYYYY** [NervJS/taro#14]
```
(node:660) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'postcss-plugin-constparse'
(node:660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
`yarn add postcss-plugin-constparse --save-dev` 报`Not Found`

还有个建议：
建议在`cli`的选项中增加对`less`的支持

谢谢

**Comment by luckyadam** [comment]
收到~我们看看~

**Comment by xiaopxu** [comment]
我也是一样的错误 linux环境
yarn add --dev postcss-plugin-constparse
yarn add v1.7.0
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "@tarojs/plugin-uglifyjs@^0.0.39". Ignoring it.
Couldn't find any versions for "@tarojs/plugin-uglifyjs" that matches "^0.0.39"
? Please choose a version of "@tarojs/plugin-uglifyjs" from this list: 0.0.37
error An unexpected error occurred: "https://registry.npm.taobao.org/postcss-plugin-constparse: Not found".

**Comment by xiaopxu** [comment]
我也是一样的错误 linux环境
```
yarn add --dev postcss-plugin-constparse
yarn add v1.7.0
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "@^0.0.39". Ignoring it.
Couldn't find any versions for "" that matches "^0.0.39"
? Please choose a version of "" from this list: 0.0.37
error An unexpected error occurred: "https://registry.npm.taobao.org/postcss-plugin-constparse: Not found".
```

**Comment by luckyadam** [comment]
更新 `@tarojs/webpack-runner` 到 `0.0.40` 就可以哈

**Comment by xiaopxu** [comment]
可以了，谢谢哈

**Comment by luckyadam** [comment]
@xiaopxu 客气客气👌
