### ISSUE TITLE
3.5.10  React框架 小程序希望支持MutationObserver使用，方便全局监听组件挂载

### ISSUE THREAD

**Issue by 7gongzi** [NervJS/taro#14000]
### 这个特性解决了什么问题？
做业务日志全局曝光使用，方便监听组建是否挂在   减少业务打点代码侵入式

### 这个 API 长什么样？
React框架 小程序希望支持MutationObserver使用，只支持到childlist 属性

**Comment by Chen-jj** [comment]
@7gongzi 参考这里修改项目的 webpack 配置即可：https://github.com/NervJS/taro/blob/99aab0a41432732265c345c42544199df99cb9a4/packages/taro-plugin-vue3/src/webpack.mini.ts#L122
