### ISSUE TITLE
Toast API 能否支持配置以下参数：maskClassName（Toast 遮罩类名）, maskStyle(Toast 遮罩样式	)

### ISSUE THREAD

**Issue by haiting** [NervJS/taro#14029]
### 这个特性解决了什么问题？
自定义Toast的样式

### 这个 API 长什么样？
Toast API 支持配置以下参数：maskClassName（Toast 遮罩类名）, maskStyle(Toast 遮罩样式	)
Taro.showToast({
  title: '成功',
  icon: 'success',
  duration: 2000，
maskClassName: 'my-project-toast',
maskStyle: {height: '200px'}
})

**Comment by bigmeow** [comment]
微信的 showToast 也不支持这个吧，Taro 小程序端就是调用微信的showToast
