### ISSUE TITLE
Toast支持手动关闭

### ISSUE THREAD

**Issue by haiting** [NervJS/taro#14024]
### 这个特性解决了什么问题？
Toast可以 一直显示，通过手动关闭，比如 duration=0的时候，toast一直显示，知道手动调用toast.clear()

### 这个 API 长什么样？
支持配置Toast 一直显示，通过手动关闭，比如 duration=0的时候，toast一直显示，知道手动调用toast.clear()

**Comment by TheKonka** [comment]
你说的 Toast 是某个 ui 库引入的？

**Comment by haiting** [comment]
> 你说的 Toast 是某个 ui 库引入的？

不好意思，没描述清楚，是指 `Taro.showToast(option)` 这个API
https://taro-docs.jd.com/docs/apis/ui/interaction/showToast

**Comment by haiting** [comment]
> 你说的 Toast 是某个 ui 库引入的？

**Comment by haiting** [comment]
比如 duration为0时，默认不启动定时器触发自动关闭
Taro.showToast({
title: '成功',
icon: 'success',
duration: 0
})

`源码这里，duration解构的时候，不设置默认值，默认值使用另外一个参数定义`
<img width="949" alt="image" src="https://github.com/NervJS/taro/assets/20320396/33626bc9-b1ab-4e53-8233-646f6fb02ad8">

**Comment by TheKonka** [comment]
Taro.showToast 在小程序环境都是调用 小程序自己的 showToast，除非小程序原生支持，否则 taro 也没法支持，只能你自己写个 toast 实现

**Comment by haiting** [comment]
> 
那能否提供另一个参数来控制呢？

**Comment by ZakaryCode** [comment]
> 那能否提供另一个参数来控制呢？

请使用 showToast、hideToast 匹配使用达成该操作
