### ISSUE TITLE
如何获取组件的高度

### ISSUE THREAD

**Issue by jethroHuang** [NervJS/taro#1403]
我想获取组件的宽高,我尝试通过 ref 引用得到组件的对象，可是我却没找到相关的文档说如何获取组件的宽高，我打印了组件对象，也没看到高度相关的变量。

----
我的代码
```
  constructor(p){
    super(p);
    this.saveRef = ref => {this.refDom = ref};
  }

  componentDidMount() {
    console.log(this.refDom);
  }
  

  render() {
    return <View ref={this.saveRef}  />
  }
```
补充：
我试过react的clientHeight也就是`this.refDom.clientHeight`结果打印undefined，打印`this.refDom.height`也是undefined

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/native-api.html#wxml-%E8%8A%82%E7%82%B9%E4%BF%A1%E6%81%AF

**Comment by kmvan** [comment]
地址404了

**Comment by chenxk-j** [comment]
@kmvan https://nervjs.github.io/taro/docs/apis/interface/wxml/nodesRef_fields.html#docsNav

**Comment by JX-Zhuang** [comment]
地址404了
