### ISSUE TITLE
Webpack5编译后global/window异常

### ISSUE THREAD

**Issue by JayceZhang9602** [NervJS/taro#14033]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/JayceZhang9602/Taro-webpack5-mobx.git](https://github.com/JayceZhang9602/Taro-webpack5-mobx.git)
**小程序基础库: 2.87.0.9**
**使用框架: React**

### 复现步骤
npm install && npm run build:tt

### 期望结果
小程序正常运行，无异常

### 实际结果
JS报错：
{
    "message": "[MobX] MobX requires global 'Symbol' to be available or polyfilled",
    "name": "Error",
    "stack": "at a(vendors.js:3:11290)\nat ?(vendors.js:3:62983)\nat Array.forEach(<anonymous>)\nat Object.3675(vendors.js:3:62925)\nat r(runtime.js:2:131)\nat Object.9415(vendors.js:3:192)\nat r(runtime.js:2:131)\nat Object.1414(app.js:2:254)\nat r(runtime.js:2:131)\nat e(app.js:2:2139)\n"
}

### 环境信息
```
Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 3.3.1 - /opt/homebrew/bin/fish
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v14.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5 
      @tarojs/components: 3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5 => 3.6.5 
      @tarojs/plugin-framework-react: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5 
      @tarojs/react: 3.6.5 => 3.6.5 
      @tarojs/runtime: 3.6.5 => 3.6.5 
      @tarojs/shared: 3.6.5 => 3.6.5 
      @tarojs/taro: 3.6.5 => 3.6.5 
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5 
      babel-preset-taro: 3.6.5 => 3.6.5 
      eslint-config-taro: 3.6.5 => 3.6.5 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
Taro V3.6.5，编译为微信小程序无异常。
降级至Webpack4编译也无异常。

**Comment by JayceZhang9602** [comment]
lodash使用也有类似的报错。

**Comment by JayceZhang9602** [comment]
貌似是编译为字节小程序时，globalThis注入时机比较晚，mobX初始化取不到globalThis、用了window
mobX内初始化逻辑：
<img width="466" alt="截屏2023-06-20 11 53 08" src="https://github.com/NervJS/taro/assets/20334140/80b3937d-02e4-4304-bbaa-9973177585c6">

微信小程序表现：
<img width="365" alt="截屏2023-06-20 11 49 48" src="https://github.com/NervJS/taro/assets/20334140/9792f671-65a1-40aa-a255-2b7f2d9f0a77">

字节小程序表现：
<img width="643" alt="截屏2023-06-20 11 53 16" src="https://github.com/NervJS/taro/assets/20334140/0e00dbb6-1324-49c1-8f97-8e632ad7b31a">

**Comment by JayceZhang9602** [comment]
定位到到原因：
Webpack5 处理node.global的实现：
`/* webpack/runtime/global */
!function() {
  __webpack_require__.g = (function() {
    if (typeof globalThis === 'object') return globalThis;
    try {
      return this || new Function('return this')();
    } catch (e) {
      if (typeof window === 'object') return window;
    }
  })();
}();`
由于字节小程序环境没有globalThis，且在严格模式下此处this是undefined，所以webpack global模块会返回
`new Function('return this')();`
这种构造函数写法，预期是返回小程序的“全局对象”，但字节小程序环境实际会返回空Object（微信小程序也是）。

**Comment by JayceZhang9602** [comment]
解决方案：

- Webpack5 配置关闭默认的global实现，`node.global = false`
<img width="313" alt="截屏2023-06-26 18 08 01" src="https://github.com/NervJS/taro/assets/20334140/0ba92f1f-92c3-4678-bb2d-ce25f5ee5315">

- 使用ProvidePlugin注入自定义global兼容实现，参考webpack4内的实现即可：
<img width="625" alt="截屏2023-06-26 18 08 43" src="https://github.com/NervJS/taro/assets/20334140/627990f7-517b-4025-b5d9-9cf11b8657d4">

```javascript
// webpack4GlobalRuntime.js
// 来源是webpack@4/buildin/global.js
var g;

// This works in non-strict mode
g = (function() {
	return this;
})();

try {
	// This works if eval is allowed (see CSP)
	g = g || new Function("return this")();
} catch (e) {
	// This works if the window reference is available
	if (typeof window === "object") g = window;
}

// g can still be undefined, but nothing to do about it...
// We return undefined, instead of nothing here, so it's
// easier to handle this case. if(!global) { ...}

module.exports = g;
```

根本原因有3个：
1. 字节小程序环境不支持globalThis；
2. Webpack 5的webpack/runtime/global实现，相对于Webpack4的webpack/buildin/global，变成了严格模式；
3. 小程序的JS环境，new Function('return this')，这种构造函数写法，return的this是空对象（在浏览器引擎或者正常Node环境，都正常return全局对象）；微信小程序、字节小程序表现都是如此。

**Comment by Solyna** [comment]
> 

加完以后lodash又不能用了
![image](https://github.com/NervJS/taro/assets/40814530/c11edb00-3e4d-4364-ba38-19e0a7130d39)

**Comment by Bruce-Ming** [comment]
百度小程序也有此问题。

**Comment by Chen-jj** [comment]
duplicate #12979
