### ISSUE TITLE
Picker 日历，当 value 超出 start 和 end 范围时报错

### ISSUE THREAD

**Issue by robinv8** [NervJS/taro#14042]
### 相关平台
H5

**浏览器版本: Chromium Engine Version 114.0.5735.133**
**使用框架: React**

### 复现步骤
```
 <Picker value='2023/06/23' mode='date' start="2018/01/01" end="2019/12/31"/>
```

![image](https://github.com/NervJS/taro/assets/12277531/0879ee95-9fa2-46ea-8135-5345b17cc975)

源码：https://github.com/NervJS/taro/blob/ad37c4ea919309b6c2788b842efb3345da3abe5c/packages/taro-components/src/components/picker/picker.tsx#L135

### 期望结果
控制台不报错

### 实际结果
有报错

### 环境信息
```
  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvs/default/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.15.0 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/mini-runner: 3.6.6 => 3.6.6 
      @tarojs/webpack-runner: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 
      taro-ui: file:../taro-ui => 3.1.0-beta.5 

```

**Comment by CoalYa** [comment]
这个是不是可以这样处理，超出边界，默认值就等于边界值
