### ISSUE TITLE
component taro convert错误

### ISSUE THREAD

**Issue by gclsoft** [NervJS/taro#1404]
![image](https://user-images.githubusercontent.com/1269898/49623858-52c41800-fa0a-11e8-8580-127ca403554b.png)

![image](https://user-images.githubusercontent.com/1269898/49623820-31fbc280-fa0a-11e8-8fa0-2199453e8f16.png)
![image](https://user-images.githubusercontent.com/1269898/49623830-37f1a380-fa0a-11e8-8497-9ee5bcbc727f.png)
我是这个路径，为什么它显示错了

**Comment by luckyadam** [comment]
看一下 `<ad-swiper />` 和 `<img-loader />` 这两个组件的文件结构和代码吧

**Comment by gclsoft** [comment]
···
// component/ml-swiper/index.js
const app = getApp();
Component({
  /**
   * 组件的属性列表
   */
  properties: {
    imgUrls: { // 属性名
      type: null, // 类型（必填），目前接受的类型包括：String, Number, Boolean, Object, Array, null（表示任意类型）
      value: [] // 属性初始值（可选），如果未指定则会根据类型选择一个
    }
  },

  /**
   * 组件的初始数据
   */
  data: {
    swiperWidth:0,
    swiperHeight:0
  },

  /**
   * 组件的方法列表
   */
  methods: {
    //对swiper的图片进行自适应处理
    swiperLoad:function (e) {
      var self = this;
      //获取图片真实宽度
      var imgwidth = e.detail.width;
      var imgheight = e.detail.height;
      //宽高比
      var ratio = imgwidth / imgheight;
      //计算的高度值
      wx.getSystemInfo({
        success: function (res) {
          //获取屏幕的宽度并保存
          var swiperWidth = res.windowWidth;
          var viewHeight = parseInt(swiperWidth) / ratio;
          self.setData({
            swiperHeight: viewHeight
          });
        }
      });
    }
  }
})
···
<ad-swiper />
![image](https://user-images.githubusercontent.com/1269898/49625122-31195f80-fa0f-11e8-8ef0-bf21168e384f.png)

**Comment by gclsoft** [comment]
```
// component/img-loader/index.js
var isLoad = false;
Component({
  /**
   * 组件的属性列表
   */
  externalClasses: ['my-class'],
  properties: {
    src: {
      type: null,
      value: ''
    },
    mode: {
      type: null,
      value: 'widthFix'
    },
    styleImg: {
      type: null,
      value: ''
    },
    styleView: {
      type: null,
      value: 'margin:36px auto;'
    }
  },

  /**
   * 组件的初始数据
   */
  data: {
    isShow: false,
    noData: false,
  },
  ready: function () {
    var self = this;
    setTimeout(function () {
      self.setData({
        isShow: true
      })
    },5000)
  },
  /**
   * 组件的方法列表
   */
  methods: {
    loadedImage: function () {
      isLoad = true;
      this.setData({
        isShow: true
      })
    }
  }
})
```
<img-loader />

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/49625186-7047b080-fa0f-11e8-84be-90129f2eac86.png)
这几个组件引用的位置是不是写了绝对路径

**Comment by gclsoft** [comment]
没有，
![image](https://user-images.githubusercontent.com/1269898/49625204-88b7cb00-fa0f-11e8-8d1f-30b8fdd70367.png) 都 是这样写的

**Comment by mienv567** [comment]
我的utils文件夹文件没有转换成taro 还是wx.request

**Comment by luckyadam** [comment]
@mienv567 3c3d57f9c39602777af6f213731a717bf5d5b834  你的问题已修复

**Comment by luckyadam** [comment]
> ![image](https://user-images.githubusercontent.com/1269898/49639176-52953e00-fa45-11e8-858d-9a7651463618.png)
> @luckyadam beta1.2@10 我试了还是有错误啊

还没发布呢

**Comment by mienv567** [comment]
@gxlsoft 自己git clone master
编译cli 然后转换

**Comment by luckyadam** [comment]
已经发布了 1.2.0-beta.11

**Comment by gclsoft** [comment]
```
VM3883:1 thirdScriptError 
 sdk uncaught third Error 
 Maximum call stack size exceeded 
 RangeError: Maximum call stack size exceeded
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:660802)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:660990)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:660990)
    at e (http://127.0.0.1:58388/appservice/__dev__/WAService.js:1:661058)
console.error @ VM3883:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1544410684151:4795
window.onerror @ VM3883:1
scriptLoaded @ appservice?t=1544410684151:5678
WAService.js:1 Mon Dec 10 2018 10:58:11 GMT+0800 (中国标准时间) Page route 错误
VM3883:1 Page[pages/home/index/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.
console.warn @ VM3883:1
P @ WAService.js:1
Et @ WAService.js:1
Pt @ WAService.js:1
At @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
ht.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1544410684151:4795
n.registerCallback.t @ appservice?t=1544410684151:4795
l.forEach.t @ appservice?t=1544410684151:4795
(anonymous) @ appservice?t=1544410684151:4795
s.onmessage @ appservice?t=1544410684151:4795
WAService.js:1 Mon Dec 10 2018 10:58:11 GMT+0800 (中国标准时间) Page route 错误
VM3883:1 Page is not constructed because it is not found.
```
编译都没问题，但是在小程序开发者工具里一打开就报错，要怎么解决呢？

**Comment by theprimone** [comment]
@gclsoft 你有解决吗？我现在也有这个问题
