### ISSUE TITLE
使用 3.6.9-alpha.5 后，运行 `dev:weapp` 后，小程序依然无法启动

### ISSUE THREAD

**Issue by zhouLion** [NervJS/taro#14055]
> > #13456 我使用了这次的更新，目前我本地预编译，静态文件的引用路径不会有问题了。 @yoyo837 这个好像还没有上线 npm 吧
> 
> 但是单单修复这个还不够，看这里的 dev:weapp 模式打包的 dist/app.js 文件
> 
> <img alt="image" width="928" src="https://user-images.githubusercontent.com/19882767/247448980-546888f1-e402-4b8f-b640-cc556070807b.png">
> 会有 .wsxx 文件被 require 引入，查询了微信小程序文档，其不支持直接 `require` 一个 `.wxss` 文件,需要采取其他方法来导入和使用 `wxss` 样式，微信小程序有两种方式来导入 wxss 样式：
> 
> * 1. 在 wxml 文件中使用  标签导入
>      在需要使用的 wxml 文件中,添加:
> 
> ```
> <import src="file_path.wxss"/>
> ```
> 
> * 2. 在 page 的 json 文件中指定 style 引用
>      在 page 的 json 文件中,添加:
> 
> ```json
> "style": "path/to/file.wxss"
> ```
> 
> 可能引入此问题的文件：https://github.com/NervJS/taro/blob/next/packages/taro-webpack5-prebundle/src/utils/webpack.ts#L14-L16

- - -

使用 3.6.9-alpha.5 后，运行 `dev:weapp` 后，小程序依然无法启动
 
``` sh
$ % taro info  
👽 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/components: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/helper: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-framework-vue3: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-html: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-alipay: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-h5: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-jd: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-qq: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-swan: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-tt: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/plugin-platform-weapp: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/runtime: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/shared: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/taro: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      @tarojs/webpack5-runner: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      babel-preset-taro: 3.6.9-alpha.5 => 3.6.9-alpha.5 
      eslint-config-taro: 3.6.9-alpha.5 => 3.6.9-alpha.5 
```

<img width="779" alt="image" src="https://github.com/NervJS/taro/assets/19882767/a8f4030e-07e2-4d2f-99d4-4b789ce44f12">

_Originally posted by @zhouLion in https://github.com/NervJS/taro/issues/13918#issuecomment-1600269950_

**Comment by yoyo837** [comment]
https://github.com/NervJS/taro/pull/13918#issuecomment-1600283993
