### ISSUE TITLE
h5端 Input 组件onInput事件的event 和小程序端不一致

### ISSUE THREAD

**Issue by yysanf** [NervJS/taro#1405]
**问题描述**
h5端 Input 组件onInput事件的event 和小程序端不一致

**复现步骤**
[复现问题的步骤]
输入123 onInput事件的event如下:
![tim 20181207105547](https://user-images.githubusercontent.com/21411793/49625015-c700ba80-fa0e-11e8-98d5-e7255f442d83.png)

**期望行为**
event.detail = {value: 123}

**报错信息**

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v.1.2.0-beta.10
 - Node.js 版本v10.13.0
 - 报错平台 h5

**Comment by jinjinjin0731** [comment]
先回退到 beta.7 之前吧。这个新版有点问题。今晚或周末发新版修复

**Comment by luckyadam** [comment]
回退 `@tarojs/components` 这个包就好~

**Comment by jinjinjin0731** [comment]
已修复
