### ISSUE TITLE
ShareElement demo 编译后的小程序和微信小程序原生效果不一致

### ISSUE THREAD

**Issue by smile-alive** [NervJS/taro#14053]
### 相关平台
微信小程序

**小程序基础库: 2.30.3**
**使用框架: React**

### 复现步骤
https://docs.taro.zone/docs/components/viewContainer/share-element
copy 代码，本地运行

### 期望结果
动画效果和小程序原生demo效果一致

### 实际结果
类似于`translateY`的动画效果丢失，只有`PageContainer`的显隐动画

### 环境信息
```
  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/mini-runner: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6 
      @tarojs/react: 3.6.6 => 3.6.6 
      @tarojs/router: 3.6.6 => 3.6.6 
      @tarojs/runtime: 3.6.6 => 3.6.6 
      @tarojs/shared: 3.6.6 => 3.6.6 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/webpack-runner: 3.6.6 => 3.6.6 
      babel-preset-taro: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 4.9.3
```

**Comment by TheKonka** [comment]
ShareElement  的 key 换成 mapkey

**Comment by smile-alive** [comment]
> ShareElement 的 key 转换成mapkey
效果是实现了，ts的报错怎么处理呀
`类型“IntrinsicAttributes & ShareElementProps”上不存在属性“mapkey”`

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/commit/10ff4a6f3471bcc94a21206636f58c7860108604#diff-6353c066b2ca7de7d2e5c6581dbc226f1060330a73322416c6b3784c909d9d64

类型我之前有加过，被机器人🤖️删了

**Comment by smile-alive** [comment]
> [10ff4a6#diff-6353c066b2ca7de7d2e5c6581dbc226f1060330a73322416c6b3784c909d9d64](https://github.com/NervJS/taro/commit/10ff4a6f3471bcc94a21206636f58c7860108604#diff-6353c066b2ca7de7d2e5c6581dbc226f1060330a73322416c6b3784c909d9d64)
> 
> 类型我之前有加过，被机器人🤖️删了

```typescript
/// <reference types="@tarojs/taro" />
import '@tarojs/components';

declare namespace NodeJS {
	interface ProcessEnv {
		TARO_ENV: 'weapp' | 'swan' | 'alipay' | 'h5' | 'rn' | 'tt' | 'quickapp' | 'qq' | 'jd';
	}
}

declare module '@tarojs/components' {
	interface ShareElementProps {
		/** 映射标记
		 * @supported weapp
		 */
		mapkey?: string;
	}
}

```
目前先跑的本地，但是必须在`global.d.ts`文件手动引入`import '@tarojs/components'`,否则`@tarojs/components`的类型被覆盖
