### ISSUE TITLE
npm run dev:weapp编译问题

### ISSUE THREAD

**Issue by genghaode** [NervJS/taro#1406]
**问题描述**

vs code编辑器
taro版本  v1.2.0-beta.9，v1.2.0-beta.10
在app.js内引入./test.js文件
ctrl+s 保存src/test.js，触发修改dist/test.js内的文件
dist/test.js文件会被修改成空文件的可能

正常的情况
![image](https://user-images.githubusercontent.com/9880797/49625900-578cca00-fa12-11e8-8ac6-526aa7ba0302.png)

dist/test.js为空的情况
![image](https://user-images.githubusercontent.com/9880797/49625928-725f3e80-fa12-11e8-83a1-d09f4fe9fd28.png)

不复现时，连续保存文件，一般10次内就会有这种现象

**Comment by luckyadam** [comment]
我们看看
