### ISSUE TITLE
【Taro 3.5.12】Taro页面使用小程序原生组件，页面第一次展示时，组件监听不到页面的onShow生命周期触发，即 pageLifetimes.show 未被触发

### ISSUE THREAD

**Issue by qiuxiyu** [NervJS/taro#14074]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/qiuxiyu/taro_issue_demo.git](https://github.com/qiuxiyu/taro_issue_demo.git)
**小程序基础库: 2.32.2**
**使用框架: React**

### 复现步骤
使用微信 IDE 打开 demo 中的 pages/taroDemo/index 页面，查看 Console 看板中是否有红色字体的 log “pageLifetimes page show”

pages/taroDemo/index 页面引用了 /components/float 组件，组件内通过 pageLifetimes.show 监听页面的 onShow 生命周期，然而：
1. Taro 页面首次 onShow 时，组件内的 pageLifetimes.show 未被触发
2. 奇怪的是，点击“跳转至下一个页面”，会触发 pageLifetimes.hide；返回时，会触发 组件内的 pageLifetimes.show 

**注：IDE 和 真机表现一致**

### 期望结果
Taro 页面首次 onShow 时，组件内的 pageLifetimes.show 可以被触发

### 实际结果
Taro 页面首次 onShow 时，组件内的 pageLifetimes.show 未被触发

### 环境信息
```
👽 Taro v3.5.12

ctxOptions---- { type: undefined }

  Taro CLI 3.5.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
      npm: 8.3.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by xuanzebin** [comment]
经测试，是原生小程序本身在某些情况下不会触发自定义组件的生命周期，已反馈到官方平台：https://developers.weixin.qq.com/community/develop/doc/00060c41640728b19effd842152000?fromCreate=0，持续跟踪一下

**Comment by Chen-jj** [comment]
Taro 页面的执行顺序：

1. 小程序页面 onLoad
  1.1 触发 React render（异步）
2. 小程序页面 onShow
3. React render 完成
4. 调用 setData 传递 DOM 数据
5. 渲染用户界面（页面引用的原生组件在这一步才开始挂载）

可见原生组件挂载的时候，页面 onShow 早已经触发过了，可以理解为组件是异步挂载的。

因此只能建议使用组件 attached 代替组件的初次 onShow。
