### ISSUE TITLE
h5 Taro.redirectTo会出错

### ISSUE THREAD

**Issue by Young1993** [NervJS/taro#1407]
很奇怪，同样的代码

app.js 配置
pages: [
      'pages/snatch/index', // 限时抢购
      'pages/snatch/coupon', // 我的券包
      'pages/snatch/snatchDetail', // 秒杀详情页
      'pages/snatch/goodsDetail', // 商品详情页
  ]

snatchDetail 页面
Taro.redirectTo({url: '/pages/snatch/coupon'}) 可以跳转
 Taro.navigateTo({url: '/pages/snatch/coupon'}) 不可以，还是在当前页面

goodsDetail页面
Taro.redirectTo({url: '/pages/snatch/coupon'})可以跳转

taro版本1.1.9

**Comment by Littly** [comment]
1.2.0-beta.10 在h5下加个配置试试：
```javascript
h5: {
  router: {
    mode: 'hash'
  }
}
```
@SmallRuralDog

**Comment by SmallRuralDog** [comment]
加了配置 路由模式变成hash的了，但是`Taro.redirectTo`依然没见变化，url地址已经变了，页面没见变

**Comment by Littly** [comment]
好的 我们定位一下

**Comment by Young1993** [comment]
> 好的 我们定位一下

我试试 hash值模式

**Comment by Young1993** [comment]
我这边试了 hash值模式还是不行，需要官方再调试一下

**Comment by Littly** [comment]
升级到1.2.0-beta.11试试~

**Comment by jiangyh123** [comment]
Taro.redirectTo确实在H5报错了，是因为浏览器访问吗？

![微信图片_20190320113050](https://user-images.githubusercontent.com/33273887/54657246-ac58da00-4b03-11e9-819d-a54f30d1298f.png)

**Comment by zhangcscc** [comment]
使用 Taro.redirectTo 第一天跳转可以，再次跳转会报这个异常，请问下是什么原因？
![image](https://user-images.githubusercontent.com/41695608/148007514-7770697c-80ae-42e4-a703-4387f0a7e14b.png)
