### ISSUE TITLE
3.4.12 -> 3.6.9 像素尺寸转换有破坏性

### ISSUE THREAD

**Issue by axetroy** [NervJS/taro#14085]
### 相关平台
H5

**浏览器版本: Chrome 104**
**使用框架: React**

### 复现步骤
1. 设置像素

```css
.login-page {
  padding-left: 56px;
  padding-right: 56px;
}
```

2. 设计尺寸的配置

```js
  designWidth: 750,
  deviceRatio: {
    640: 2.34 / 2,
    750: 1,
    828: 1.81 / 2,
    375: 2 / 1,
  },
```

### 期望结果
根据设计稿尺寸 750，如果用 375 尺寸打开页面，那么 56px 就是 28px，换算成为 rem 为 1.19467rem

root: 23.4375px
计算如下：1.19467 * 23.4375 = 28px

### 实际结果
实际得出转换后的 rpm 为 1.4rem

实际像素为：1.4 * 23.4375 = 32.8125

### 环境信息
```
👽 Taro v3.6.9-alpha.7


  Taro CLI 3.6.9-alpha.7 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/components: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/plugin-framework-react: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/plugin-platform-h5: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/react: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/runtime: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/taro: 3.6.9-alpha.7 => 3.6.9-alpha.7
      @tarojs/webpack5-runner: 3.6.9-alpha.7 => 3.6.9-alpha.7
      babel-preset-taro: 3.6.9-alpha.7 => 3.6.9-alpha.7
      eslint-config-taro: 3.6.9-alpha.7 => 3.6.9-alpha.7
      react: ^18.2.0 => 18.2.0
      taro-ui: 3.1.0-beta.2 => 3.1.0-beta.2
```

---
### 补充信息
我是从旧版升级上来的，3.4.12 -> 3.6.9

我翻遍了更新日志，没有找到相关的变更日志。

看起来像是使用了 640 的设计尺寸，没有按照 750 的设计尺寸

**Comment by axetroy** [comment]
而且 css 的设置也有破坏性，例如 Form 组件里面的 <form> 元素，之前的版本是能给给他设置 CSS 的


Before:

```css
.login-form form {
  padding: 20px; // 这条 CSS 在输出的包里面
}
```

After:
更新后这样的 CSS 规则就不起作用了

**Comment by ZakaryCode** [comment]
之前版本计算规则是写死的，无法配置，支持后确实存在不一致，可以配置 designWidth: 640 与旧版本对其

> 跨越这么多版本，还是先多看下发版日志咯

---

> 而且 css 的设置也有破坏性

此处描述并非同一个问题，在此处所指代的新版本中，会自动转换 Taro 支持的组件标签，以 Form 组件为例，form 会被转换为 taro-form-core 便于与小程序一致的样式设置，如果需要设置原生标签样式，可以自行参考文档关闭该特性或者在指定行跳过转换。

**Comment by liuguangyong93** [comment]
<script>
      !(function(n) {
        console.info('width from html===', n.document.documentElement.getBoundingClientRect().width);
        function f() {
          var e = n.document.documentElement,
          w = e.getBoundingClientRect().width,
          x = (40 * w) / 780
          e.style.fontSize = x + 'px'
        }
        n.addEventListener('resize', function() {
          f()
        }),
        f()
      })(window)
    </script>

其中780是公司的设计稿。该方案仅限于编译h5端
