### ISSUE TITLE
pnpm workspace下webpack5打包alias目录图片路径异常

### ISSUE THREAD

**Issue by lindingfeng** [NervJS/taro#14088]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/lindingfeng/taro-test-global-image.git](https://github.com/lindingfeng/taro-test-global-image.git)
**小程序基础库: 2.32.3**
**使用框架: Vue 3**

### 复现步骤
拉取重现链接代码构建运行

### 期望结果
正常打包图片资源

### 实际结果
图片资源打包异常（资源路径异常、未打包图片进dist）

### 环境信息
```
Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 16.20.0 - D:\nodejs\node.EXE
      Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.4 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-vue3: 3.6.8 => 3.6.8
      @tarojs/plugin-html: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
```

---
### 补充信息
webpack4可正常打包图片资源。
![微信截图_20230629135906](https://github.com/NervJS/taro/assets/26541555/b2a0c2ea-fbde-4b6c-a74c-61c7e74a80aa)
![image](https://github.com/NervJS/taro/assets/26541555/3afc6c96-dd4f-45de-8787-ad81547b91d3)

**Comment by Chen-jj** [comment]
@lindingfeng webpack 的路径解析没有问题的，只是解析完后这个路径已经超出了小程序包之外，这是小程序不允许的。你把这些图片转 base64 就好，我猜 webpack4 可能也是把图片转了 base64.

**Comment by yuuk** [comment]
它不能把图片通过类似 file-loader 打到项目中么？

**Comment by yuuk** [comment]
webpack4 能把图标导到dist中

![image](https://github.com/user-attachments/assets/09f8d633-5953-47b9-a2b9-64f35ea65f3b)
