### ISSUE TITLE
小程序运行报错：globalThis is not defined, 和cannot read properties of undefined (reading 'connect')

### ISSUE THREAD

**Issue by chenzhengWin** [NervJS/taro#14082]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
删除node_moudles包和package-lock文件，重新安装依赖后运行，出现问题。报错信息请见补充说明。

### 期望结果
程序正常运行，无报错

### 实际结果
小程序开发工具显示“当前访问的页面不存在”
终端报错：export 'OpenData' (imported as 'OpenData') was not found in '@tarojs/components' ，也是3.6.6版本；
小程序开发工具报错：globalThis is not defined
    at ./node_modules/react-redux/es/components/Context.js

Cannot read properties of undefined (reading 'connect')
    at Object.connect (useStore.js:38:1)
    at ./node_modules/babel-loader/lib/index.js??ruleSet[1].rules[5].use[0]!./src/pages/webView/index.tsx (index.tsx:141:1)

### 环境信息
```
👽 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6 
      @tarojs/react: 3.6.6 => 3.6.6 
      @tarojs/runtime: 3.6.6 => 3.6.6 
      @tarojs/shared: 3.6.6 => 3.6.6 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6 
      babel-preset-taro: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 
      react: ^18.0.0 => 18.2.0 
      taro-ui: 3.1.0-beta.4 => 3.1.0-beta.4 

```

---
### 补充信息
是mpass小程序。近期需求迭代，删除node_moudles包和package-lock文件，重新安装依赖后运行，出现问题。然后重新拉master代码重新运行还是有问题（线上以前发布的没问题）：
终端报错：export 'OpenData' (imported as 'OpenData') was not found in '@tarojs/components' ，也是3.6.6版本；
小程序开发工具报错：globalThis is not defined
    at ./node_modules/react-redux/es/components/Context.js

Cannot read properties of undefined (reading 'connect')
    at Object.connect (useStore.js:38:1)
    at ./node_modules/babel-loader/lib/index.js??ruleSet[1].rules[5].use[0]!./src/pages/webView/index.tsx (index.tsx:141:1)

**Comment by iowxy** [comment]
可以关闭了，解决方案在这里：https://github.com/foca-js/foca/issues/40
