### ISSUE TITLE
taro 3.6.4版本编译rn是否支持了Hermes引擎

### ISSUE THREAD

**Issue by yclnycl** [NervJS/taro#14084]
### 这个特性解决了什么问题？
启用Hermes 

### 这个 API 长什么样？
目前按照文档上编译启用Hermes 编译release 会找不到对应的hcb文件导致编译失败

**Comment by yclnycl** [comment]
@zhiqingchen

**Comment by zhiqingchen** [comment]
3.6.4 版本，RN如何启用则Taro RN如何启用

**Comment by zhiqingchen** [comment]
3.6以上已经完全使用 react-native 进行打包编译了

**Comment by yclnycl** [comment]
> 3.6以上已经完全使用 react-native 进行打包编译了

但是我现在按照文档编译会提示找不到hcb文件,手动在gradle配置里关掉Hermes引擎的开关才可以build release包

**Comment by zhiqingchen** [comment]
debug 为何不会编译 hcb 文件

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-playground/blob/main/android/app/build.gradle#L85

这个地方是否被注释，以及是否正常运行
