### ISSUE TITLE
useError增加区分渲染错误和JS执行错误

### ISSUE THREAD

**Issue by ifushion** [NervJS/taro#14087]
### 这个特性解决了什么问题？
区分后可以统一捕获&上报，渲染错误通常会引起白屏（影响较大），量级也会比JS执行异常小。如果不区分会导致渲染异常被淹没无法重点观测

### 这个 API 长什么样？
useError 回调的异常增加相关来源参数，标明是渲染/JS执行异常

**Comment by Chen-jj** [comment]
`useError` 是小程序 App 的 `onError` 生命周期，这里没有办法区分是框架渲染还是普通的 JS 报错。如果你使用的是 React，渲染错误可以通过 React 的错误边界进行上报：https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary
