### ISSUE TITLE
内部滚动会触发scroll-view下拉刷新

### ISSUE THREAD

**Issue by lovelyqun** [NervJS/taro#14089]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/lovelyqun/taro-nut-tsx.git](https://github.com/lovelyqun/taro-nut-tsx.git)
**小程序基础库: 2.30.0**
**使用框架: Vue 3**

### 复现步骤
      <ScrollView
        scroll-y={true}
        refresherTriggered={state.refresherTriggered}
        refresherEnabled={state.refresherEnabled}
        onRefresherrefresh={onPullDownRefresh}
      >
        <div style="height:80vh">
          <div style="height:200px;overflow:auto">
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
            <div style='height:50px'>dddd</div>
          </div>
        </div>
      </ScrollView >
运行代码
内部向下滚动
再向上滚动就会触发下拉刷新

### 期望结果
内部滚动不允许触发scroll-view下拉刷新

### 实际结果
内部滚动触发scroll-view下拉刷新,导致无法滚动到顶部

### 环境信息
```
  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD   
```

**Comment by Chen-jj** [comment]
测试了一下，原生写法在真机也有同样问题：

```html
<scroll-view
    scroll-y="{{true}}"
    refresherEnabled="{{true}}"
>
    <view style="height:80vh">
        <view style="height:200px;overflow:auto">
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        <view style='height:50px'>dddd</view>
        </view>
    </view>
</scroll-view >
```

**Comment by Chen-jj** [comment]
@lovelyqun 问题出在这个容器的 `overflow:auto` 样式上 `<view style="height:200px;overflow:auto">`，是写法的问题，与 Taro 框架无关，建议参考一下小程序官方文档的用法。

**Comment by lovelyqun** [comment]
确实是微信小程序的问题,感谢
