### ISSUE TITLE
taro+mobx 编译为微信小程序跳转报错

### ISSUE THREAD

**Issue by jiangbingkui** [NervJS/taro#1409]
**问题描述**
vs code编辑器
taro版本 v1.2.0-beta.9，v1.2.0-beta.10

**复现步骤**
[复现问题的步骤]
1.系统为window
2.init后使用sass+mobx;
3.创建相同的页面后在app.js添加后点击过去报错

```js
// 这里可以贴代码


```

**期望行为**
可以正常跑过去

**报错信息**

这是跳转的方法
![image](https://user-images.githubusercontent.com/22762830/49632051-5322da00-fa2f-11e8-983c-b049a49169b4.png)
这是app.js
![image](https://user-images.githubusercontent.com/22762830/49632155-b0b72680-fa2f-11e8-966b-084a3f9e3502.png)
这是报错信息
![image](https://user-images.githubusercontent.com/22762830/49632218-e2c88880-fa2f-11e8-8b9c-95ee79564cd0.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.2.0-beta.7]
 - Node.js 版本 [e.g. v10.8.0]
 - 报错平台 [微信小程序,h5没事，]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
cli 和项目依赖都升级到 1.2.0-beta.10

**Comment by jiangbingkui** [comment]
> cli 和项目依赖都升级到 1.2.0-beta.10
解决了，是不是使用mobx 使用的测试小版本必须beta.10以后？

**Comment by nanjingboy** [comment]
@jiangbingkui 做过一次优化引起的问题，最好还是保持最新版本

**Comment by nanjingboy** [comment]
@luckyadam https://github.com/NervJS/taro/issues/1313 跟这个重复了

**Comment by luckyadam** [comment]
@nanjingboy 666
