### ISSUE TITLE
mobx6.x 支付宝小程序编译报错 MobX requires global 'Symbol' to be available or polyfilled 

### ISSUE THREAD

**Issue by Solyna** [NervJS/taro#14090]
### 相关平台
支付宝小程序

**小程序基础库: 2.32.3**
**使用框架: React**

### 复现步骤
运行后就报错
{
    "mobx": "^6.9.0",
    "mobx-react": "^7.6.0",
}

### 期望结果
正常运行

### 实际结果
支付宝小程序开发这工具打开运行就报错 Error: [MobX] MobX requires global 'Symbol' to be available or polyfilled

### 环境信息
```
 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/helper: 3.6.8 => 3.6.8 
      @tarojs/mini-runner: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8 
      @tarojs/react: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/shared: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.6 => 3.1.0-beta.6 


```

**Comment by miaomiaoG** [comment]
遇到同样问题，通过在app.js中添加
window.Symbol = Symbol
window.Map = Map
window.Set = Set
可以解决部分问题，但前提是不使用Provier，一旦使用Provier就还是会报错
不使用Provier就不会报错，且mobx使用正常
<img width="1821" alt="image" src="https://github.com/NervJS/taro/assets/29765893/4ec777e7-7e1f-48f5-89aa-f87c95594590">

使用Provier报错，
<img width="1663" alt="image" src="https://github.com/NervJS/taro/assets/29765893/2671d5fd-797d-48b7-b200-b9eceed6d244">

**Comment by Solyna** [comment]
> 
我这边验证下来，在页面上用mobx相关，不报错；
在app.ts里虽然加了window.Symbol = Symbol，但是只要在app.ts里使用任何mobx相关的方法，就会报错。
头好大，查了好久，无解。。。

**Comment by Solyna** [comment]
> 遇到同样问题，通过在app.js中添加 window.Symbol = Symbol window.Map = Map window.Set = Set 可以解决部分问题，但前提是不使用Provier，一旦使用Provier就还是会报错 不使用Provier就不会报错，且mobx使用正常 <img alt="image" width="1821" src="https://user-images.githubusercontent.com/29765893/250039912-4ec777e7-7e1f-48f5-89aa-f87c95594590.png">
> 
> 使用Provier报错， <img alt="image" width="1663" src="https://user-images.githubusercontent.com/29765893/250039492-2671d5fd-797d-48b7-b200-b9eceed6d244.png">

https://opendocs.alipay.com/mini/framework/implementation-detail
![image](https://github.com/NervJS/taro/assets/40814530/b7339eac-b29a-42f0-a98a-f318ccdd0b76)

**Comment by Chen-jj** [comment]
duplicate #12979

**Comment by 37972547** [comment]
https://opendocs.alipay.com/mini/03dbc3#globalObjectMode

<img width="1648" height="1394" alt="Image" src="https://github.com/user-attachments/assets/e3721ca1-446b-4c51-aee2-d4c2fe013d31" />
