### ISSUE TITLE
DeprecationWarning: Compilation.assets will be frozen in future

### ISSUE THREAD

**Issue by tutuxxx** [NervJS/taro#14119]
### 相关平台
H5

**浏览器版本: chrome 100**
**使用框架: React**

### 复现步骤
使用以下插件：
export default (ctx, pluginOpts) => {
  ctx.modifyBuildAssets(({ assets }) => {
    // 重置assets
    assets['html/index.html'] = assets['index.html']
  });
}

### 期望结果
无告警

### 实际结果
出现以下告警：
(node:90867) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)

### 环境信息
```
Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.17 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.6.7 => 3.6.7 
      @tarojs/components: ^3.6.7 => 3.6.7 
      @tarojs/helper: ^3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: ^3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: ^3.6.7 => 3.6.7 
      @tarojs/react: ^3.6.7 => 3.6.7 
      @tarojs/router: ^3.6.7 => 3.6.7 
      @tarojs/runtime: ^3.6.7 => 3.6.7 
      @tarojs/shared: ^3.6.7 => 3.6.7 
      @tarojs/taro: ^3.6.7 => 3.6.7 
      @tarojs/taro-h5: ^3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: ^3.6.7 => 3.6.7 
      babel-preset-taro: ^3.6.7 => 3.6.7 
      eslint-config-taro: ^3.6.7 => 3.6.7 
      react: ^18.2.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.2
```

**Comment by ZakaryCode** [comment]
该提示由 webpack 抛出，与 taro 无关

**Comment by tutuxxx** [comment]
> 该提示由 webpack 抛出，与 taro 无关

Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

看着可以通过修改ctx.modifyBuildAssets的调用时机解决？ @ZakaryCode

**Comment by Chen-jj** [comment]
> processAssets

目前是在 processAssets 钩子中出发的 modifyBuildAssets 吧？
