### ISSUE TITLE
[官方急救] 在taro里使用mobx 6版本，在支付宝小程序开发者工具中打开就会报错，window对象的数据各种缺失，使用useBuiltIns: 'entry'添加polyfill还是报错

### ISSUE THREAD

**Issue by Solyna** [NervJS/taro#14110]
### 相关平台
支付宝小程序

**小程序基础库: 1.25.9**
**使用框架: React**

### 复现步骤
随便新起一个Taro3.6版本的内置模版项目，
安装mobx6版本，在app.ts中引入observer包裹，或者任意地方使用mobx，启动项目，用支付宝开发者工具打开，就会报错。
Error: [MobX] MobX requires global 'Symbol' to be available or polyfilled
![image](https://github.com/NervJS/taro/assets/40814530/8734e6d3-de98-446a-a7f1-47081097528b)

使用useBuiltIns: 'entry' 添加polyfill后，还会报：TypeError:Can't call method on undefined
![image](https://github.com/NervJS/taro/assets/40814530/d2d27649-59f1-4cb4-b995-15cfb4069ed7)

尝试过将mobx退回5版本不会报错。
![image](https://github.com/NervJS/taro/assets/40814530/26dec30f-4096-4a30-b019-db1f632125f4)
![image](https://github.com/NervJS/taro/assets/40814530/58f25584-a988-4acb-bb90-a10cc5750f89)
![image](https://github.com/NervJS/taro/assets/40814530/f86b80c8-335e-4fdf-9343-d64a5988b3d7)

### 期望结果
希望官方按步骤操作并定位下问题，在支付宝上能够获取到全部的window对象，并且不会报错

### 实际结果
在支付宝上运行会报错

### 环境信息
```
 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/helper: 3.6.8 => 3.6.8 
      @tarojs/mini-runner: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8 
      @tarojs/react: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/shared: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.6 => 3.1.0-beta.6 
```

**Comment by Chen-jj** [comment]
duplicate #12979

**Comment by ChenRiliang** [comment]
字节小程序也会出现，有解决方案吗？

**Comment by tfusksxl31** [comment]
字节小程序也会出现这个问题，有解决方案了吗？
`Taro CLI 3.6.23 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.23 => 3.6.23 
      @tarojs/components: 3.6.23 => 3.6.23 
      @tarojs/helper: 3.6.23 => 3.6.23 
      @tarojs/plugin-framework-react: 3.6.23 => 3.6.23 
      @tarojs/plugin-html: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-alipay: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-h5: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-jd: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-qq: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-swan: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-tt: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-weapp: 3.6.23 => 3.6.23 
      @tarojs/react: 3.6.23 => 3.6.23 
      @tarojs/router: 3.6.23 => 3.6.23 
      @tarojs/runtime: 3.6.23 => 3.6.23 
      @tarojs/shared: 3.6.23 => 3.6.23 
      @tarojs/taro: 3.6.23 => 3.6.23 
      @tarojs/taro-loader: 3.6.23 => 3.6.23 
      @tarojs/webpack5-runner: 3.6.23 => 3.6.23 
      babel-preset-taro: 3.6.23 => 3.6.23 
      eslint-config-taro: 3.6.23 => 3.6.23 
      react: ^18.0.0 => 18.2.0 `

`├── mobx-react@9.1.0
├── mobx@6.12.0
`
