### ISSUE TITLE
执行gradlew assembleRelease/npm run  android报错‘autolinking.gradle' as it does not exis

### ISSUE THREAD

**Issue by enjoylee-lionjoy** [NervJS/taro#14121]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
使用最新版Taro CLI 选择 webpack5 react react-native的模板，项目名称 bjr。在不做任何代码改动的情况下，运行npm run build:rn /yarn build:rn --platform android 运行正常，接着运行gradlew assembleRelease 出现错误提示

### 期望结果
运行成功

### 实际结果
nfo Starting JS server...
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Settings file 'E:\baJoinApp\bjr\android\settings.gradle' line: 13

* What went wrong:
A problem occurred evaluating settings 'bjr'.
> Could not read script 'E:\baJoinApp\bjr\scripts\autolinking.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Settings file 'E:\baJoinApp\bjr\android\settings.gradle' line: 13

* What went wrong:
A problem occurred evaluating settings 'bjr'.
> Could not read script 'E:\baJoinApp\bjr\scripts\autolinking.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (E:\baJoinApp\bjr\node_modules\execa\index.js:174:9)
    at E:\baJoinApp\bjr\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (E:\baJoinApp\bjr\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (E:\baJoinApp\bjr\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bjr@1.0.0 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bjr@1.0.0 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

### 环境信息
```
  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/react: 3.6.8 => 3.6.8
      @tarojs/rn-runner: 3.6.8 => 3.6.8
      @tarojs/rn-supporter: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/runtime-rn: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/taro-rn: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
      react: ^18.1.0 => 18.2.0
      react-native: ^0.70.1 => 0.70.12
```

**Comment by zhiqingchen** [comment]
https://docs.taro.zone/docs/react-native#%E9%9B%86%E6%88%90%E6%A8%A1%E5%BC%8F

**Comment by yangcodry** [comment]
我也是同样的问题，这个autolinking.gradle文件没有啊
![9ff91a465db9aadbc5153bbaf2b3063e](https://github.com/NervJS/taro/assets/74765069/383710d7-cafe-46a0-873a-2762e748cdcd)

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-test

用这里对应分支，初始化好的编译试试

**Comment by yangcodry** [comment]
> https://github.com/zhiqingchen/taro-test
> 
> 用这里对应分支，初始化好的编译试试
感谢大哥，终于可以了，昨天用taro init里面的react-native模板，在使用yarn upgradePeerdeps时总是失败，尝试单独install-peerdeps也有失败的，导致一个核心的包expo没有下下来，所以在编译的时候找不到settings.gradle里的"../scripts/autolinking.gradle"，也就有了和楼主一样的问题。一开始我以为这个autolinking.gradle文件是相对于项目根目录下的，一直以为是哪一步下载出错了，导致没有在项目根目录下生成这个文件，结果这哥们原来是在expo这个依赖包里，相对路径是相对于expo目录的
