### ISSUE TITLE
ScrollView的下拉刷新如何支持H5

### ISSUE THREAD

**Issue by puchenhui** [NervJS/taro#14139]
### 这个特性解决了什么问题？
根据api了解到，只支持小程序，无法支持h5，解决后可支持多端下拉刷新

### 这个 API 长什么样？
期望下拉刷新相关属性支持h5

**Comment by puchenhui** [comment]
在了解 enablePullDownRefresh 属性后，发现与我的需求不相符，我希望在某个页面进行下拉刷新，但enablePullDownRefresh是全局的。我在此页面用了ScrollView进行上拉加载，看到api可以支持下拉刷新，但仅支持小程序，我希望在小程序端和h5端可以做到下拉刷新，用什么方法比较合适呢？

**Comment by ZakaryCode** [comment]
> 在了解 enablePullDownRefresh 属性后，发现与我的需求不相符，我希望在某个页面进行下拉刷新，但enablePullDownRefresh是全局的。

可以按页面配置，请仔细阅读相关文档

> 根据api了解到，只支持小程序，无法支持h5

与小程序一致

**Comment by puchenhui** [comment]
> > 在了解enablePullDownRefresh属性后，发现与我的需求不符，我希望在某个页面进行下拉刷新，但enablePullDownRefresh是全局的。
> 
> 可以按页面配置，请仔细阅读相关文档
> 
> > 根据api明确，只支持小程序，无法支持h5
> 
> 与小程序一致

但我发现因为列表内容使用的是ScrollView，当页面滑到下面之后，往上滑动的时候，其实我想滑动的是ScrollView里面的内容，但会触发刷新，并且在出触发刷新后页面无法滑动
