### ISSUE TITLE
node_modules 中的模块是 symlink 时无法编译成功

### ISSUE THREAD

**Issue by cheese-git** [NervJS/taro#1413]
**问题描述**

node_modules 中的模块是 symlink 时无法编译成功

**复现步骤**

目录结构：

![image](https://user-images.githubusercontent.com/11363971/49635466-d1d14480-fa3a-11e8-9371-256aa8cee939.png)

`taro-project/package.json`:

![image](https://user-images.githubusercontent.com/11363971/49635556-207ede80-fa3b-11e8-8c55-c5dcb6917881.png)

然后：

```bash
> lerna bootstrap

lerna notice cli v3.5.1
lerna info Bootstrapping 3 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 3 packages
```

```ts
// taro-project/src/pages/index/index.tsx
import { hello } from "my-package-abcd"

console.log(hello)
```

```bash
> cd packages/taro-project-1
> yarn dev:weapp

缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
缺少npm包my-package，开始安装...
```

**系统信息**

 - 操作系统: win10
 - Taro 1.2.0 beta8
 - Node.js 版本 10.13.0

**补充信息**

发现这是 webpack 的问题：https://webpack.js.org/configuration/resolve/#resolve-symlinks

但是在 taro 项目的 config 中设置 symlinks:true 无效，希望可以提供对 webpack 的这项配置

另外，建议不要自动安装…… 
ts 自动导入的时候路径不一致也会自动安装……
如果包名字拼错了也会自动安装……
自动安装失败了最好也不要一直重复尝试……

**Comment by cheese-git** [comment]
**编译失败的原因不是 symlink**, 而是我自己的项目和包没有编译成兼容的 js，且 Taro 并不会编译 node_modules 中的内容。

我可能和 #871 有一样的需求

**Comment by holin** [comment]
我也碰到有symlinks的目录编译失败的问题。
我尝试着把 klaw 升级到 3.0.0 就能正常遍历 symlink 的目录。
这个文件：
https://github.com/NervJS/taro/blob/master/packages/taro-cli/package.json
`"klaw": "^2.1.1",`  改成 `"klaw": "^3.0.0",`

不知道是否能升级。
