### ISSUE TITLE
h5 navigateTo跳转页面后，页面默认停留位置不正确

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#1415]
**问题描述**
h5 navigateTo跳转页面后，页面默认停留位置不正确

**复现步骤**
[复现问题的步骤]
1. 打开A页面
2. 滚动A页面到页面中间
3. 从A页面 navigateTo B页面
4. 此时会发现进入的B页面，页面位置其实是A页面已滚动到的位置

**系统信息**

 - Taro 版本 [1.2.0-beta.7]
 - 报错平台 [h5]

**Comment by Littly** [comment]
更新到最新版试试，已经支持。
https://github.com/NervJS/taro/commit/e939a65198399860ab95ef593f701c2493015757
