### ISSUE TITLE
showCenterPlayBtn设置为false后不生效

### ISSUE THREAD

**Issue by luckyGTL** [NervJS/taro#14161]
### 这个特性解决了什么问题？
播放器中不展示中间的播放按钮，目前showCenterPlayBtn属性不生效

### 这个 API 长什么样？
设置了showCenterPlayBtn设置为false后生效，video播放的时候不展示中间播放按钮

**Comment by ZakaryCode** [comment]
请不要通过 enhancement 提交问题，请补充包括编译平台、示例等相关信息，或者该问题将被关闭
