### ISSUE TITLE
在表单中使用什么input来承载非字符串类型的value？

### ISSUE THREAD

**Issue by zzefff** [NervJS/taro#14164]
### 这个特性解决了什么问题？
自定义的表单控件，用户操作后生成一个对象类型的值，该放在什么类型的input来放置这个值的key value，才能在Form的submit的e.detail中获得该值？
尝试用type=text，不出意外地该值变成[object,object]

### 这个 API 长什么样？
自定义的表单控件，用户操作后生成一个对象类型的值，该放在什么类型的input来放置这个值的key value，才能在Form的submit的e.detail中获得该值

**Comment by Chen-jj** [comment]
问题太抽象，可以在 Discussions 中详细描述相关细节，此 issue 先关闭了
