### ISSUE TITLE
希望适配 微信Skyline渲染模式glass-easel组件框架

### ISSUE THREAD

**Issue by ljianc** [NervJS/taro#14165]
### 这个特性解决了什么问题？
Skyline渲染模式，自组件库2.33.0起强制要求适配这东西了

### 这个 API 长什么样？
这是官方介绍 https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html

**Comment by iugo** [comment]
目前配置的类型上支持 glass-easel
https://github.com/NervJS/taro/blob/792d71e8361ee6aaa622c46f14e3461f0b4cbe28/packages/taro/types/taro.config.d.ts#L218-L223

能说一下如果应用 glass-easel 实际遇到了什么问题吗?

**Comment by ljianc** [comment]
目前发现的有：
1 控制台有警告
![1697781899197](https://github.com/NervJS/taro/assets/10055508/97bd9924-b3ce-4dd4-9122-dbd2dab31ace)
2  scroll-view、swiper的worklet相关事件

最好还是对照一下微信官方的checklist，都过一下吧

**Comment by wzhqwq** [comment]
感觉距离能平稳迁移到Skyline还比较远，我的项目在Skyline下只要有ScrollView就会崩溃

**Comment by TheKonka** [comment]
> 感觉距离能平稳迁移到Skyline还比较远，我的项目在Skyline下只要有ScrollView就会崩溃

不至于奔溃吧，我用了可以用，
可能有样式问题，得手动调整下，ScrollView要加上 type ，css里面 flex 要显式设置 flex-direction

**Comment by tutuxxx** [comment]
https://docs.taro.zone/docs/skyline
