### ISSUE TITLE
2个页面无法使用同一个组件

### ISSUE THREAD

**Issue by Typeve** [NervJS/taro#14177]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Typeve/taro-demo.git](https://github.com/Typeve/taro-demo.git)
**小程序基础库: 2.32.3**
**使用框架: React**

### 复现步骤
在src下创建一个公共组件，无法在2个页面中使用，会导致小程序白屏，Wxml结构中只显示一个page标签，控制台没有报错

### 期望结果
正常显示组件

### 实际结果
白屏

### 环境信息
```
👽 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - ~\AppData\Local\pnpm\node.EXE
      npm: 9.5.1 - ~\AppData\Local\pnpm\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/react: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
      react: ^18.0.0 => 18.0.0
```

---
### 补充信息
使用pnpm@8.6.0进行的创建
 请输入项目名称！ taro-demo
? 请输入项目介绍
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Github（最新）
√ 拉取远程模板仓库成功！
? 请选择模板 默认模板

**Comment by xuanzebin** [comment]
试了 demo 没有出现你说的问题，想问一下在编译打包时，终端是否有出现报错？

**Comment by Typeve** [comment]
> 试了 demo 没有出现你说的问题，想问一下在编译打包时，终端是否有出现报错？

我用另一台电脑使用npm lts跑了一下也是正常的，我升级了一下pnpm@8.6.0=>pnpm@8.6.7,重新pnpm i。
现在正常了。
之前终端没有报错

**Comment by xuanzebin** [comment]
> > 试了 demo 没有出现你说的问题，想问一下在编译打包时，终端是否有出现报错？
> 
> 我用另一台电脑使用npm lts跑了一下也是正常的，我升级了一下pnpm@8.6.0=>pnpm@8.6.7,重新pnpm i。 现在正常了。 之前终端没有报错

okok，初步怀疑是 3.6.8 的 taro-doctor 与 pnpm 的某些版本有所冲突，这个已经解决了，下个版本发布之后应该就没有问题了。
