### ISSUE TITLE
1.2.0-beta.10版本 npm  run dev:h5     dist文件夹闪一下就没了

### ISSUE THREAD

**Issue by Dave-miao** [NervJS/taro#1417]
**问题描述**
1.2.0-beta.10版本 npm  run dev:h5     dist文件夹闪一下就没了

**复现步骤**
[复现问题的步骤]
1.npm  run dev:h5

**Comment by luckyadam** [comment]
闪一下就没了是指？

dev 模式下 dist 目录是没有内容的

**Comment by Dave-miao** [comment]
就是dist整个文件夹都没了

**Comment by Littly** [comment]
1.2.0-beta.10 之后，在编译任务开始前进行了清理工作 把.temp和dist都清除掉了

https://github.com/NervJS/taro/blob/a392ad9bda252d5e5427204e3cf4487cf8378168/packages/taro-cli/src/h5.js#L829-L838

是对调试造成影响了吗？
