### ISSUE TITLE
Taro 编译用 vite 打包的组件库到 h5 端时，不会正确解析小程序标签为 h5 标签

### ISSUE THREAD

**Issue by front-refined** [NervJS/taro#14176]
### 相关平台
H5

**浏览器版本: 版本 114.0.5735.198（正式版本） (arm64)**
**使用框架: Vue 3**

### 复现步骤
https://github.com/front-refined/nutui-taro-compile-h5-issue

拉取 git 仓库

yarn run dev:h5

h5 端，首页 tabs 过长时，点击 item 不会自动滚动定位到指定位置，在小程序环境可以

### 期望结果
Taro 编译用 vite 打包的组件库到 h5 端时，正确解析小程序标签为 h5 标签

### 实际结果
Taro 编译用 vite 打包的组件库到 h5 端时，不会正确解析小程序标签为 h5 标签

### 环境信息
```
  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/helper: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-vue3: 3.6.8 => 3.6.8 
      @tarojs/plugin-html: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/shared: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/taro-loader: 3.6.8 => 3.6.8 
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 
```

---
### 补充信息
这个演示仓库使用的就是 nutui-taro 组件库，它是用 vite 打包的，但是Taro 编译成 h5 端时，没有正确解析小程序标签为 h5 标签，如 <view /> 为 <taro-view-core>，会导致一定的问题，更多详细我在这个演示仓库有 README.md 描述

**Comment by front-refined** [comment]
如 <view /> 应该会被编译成 <taro-view-core />，但是仍然显示 <view />，这个 <nut-tabs /> 的问题也是因为 <scroll-view /> 不会被正常编译成 h5 版的 <taro-scroll-view-core /> 导致的。

**Comment by eiinu** [comment]
或者，是否允许直接 import `@tarojs/components` 组件库 中的 vue 版本组件自行注册使用呢？就像 Taro React 使用组件的那种方式。
这样的话，组件库就可以在构建时保留这部分代码，开发者去使用组件库时也就不会丢失这些组件了。

**Comment by ZakaryCode** [comment]
> 或者，是否允许直接 import `@tarojs/components` 组件库 中的 vue 版本组件自行注册使用呢？就像 Taro React 使用组件的那种方式。
> 这样的话，组件库就可以在构建时保留这部分代码，开发者去使用组件库时也就不会丢失这些组件了。

和组件注册没啥关系，这里是使用的组件实际没有转换成功

另外自行注册 vue 组件是可行的，参考[这里](https://github.com/NervJS/taro/blob/6a7779d98102c9b7b0082ababbac342cbff2d213/packages/taro-platform-h5/src/program.ts#L118)

**Comment by ZakaryCode** [comment]
> 如 `<view />` 应该会被编译成 `<taro-view-core />`，但是仍然显示 `<view />`，这个 `<nut-tabs />` 的问题也是因为 `<scroll-view />` 不会被正常编译成 h5 版的 `<taro-scroll-view-core />` 导致的。

这应该是 vue-loader 的 nodeTransforms 方法没有执行，对应 taro-vue3 插件中的[这里](https://github.com/NervJS/taro/blob/6a7779d98102c9b7b0082ababbac342cbff2d213/packages/taro-plugin-vue3/src/webpack.h5.ts#L73C8-L73C8)
