### ISSUE TITLE
taro-hooks 3.5.8 模板,编译weapp失败

### ISSUE THREAD

**Issue by brady2037** [NervJS/taro#14181]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/gmail2037/taro_3.6.8_hooks.git](https://github.com/gmail2037/taro_3.6.8_hooks.git)
**小程序基础库: 2.30.2**
**使用框架: React**

### 复现步骤
命令行:
taro init taro_hooks

? 请输入项目介绍 taro
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择编译工具 Webpack5
? 请选择包管理工具 npm
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 taro-hooks（使用 taro-hooks 的模板）

命令行运行:
npm install
npm run build:weapp
报错提示:
✖ Errors: 

resolve '@taro-hooks/core' in 'C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\taro-hooks\lib\createUseInfoHook'
  Parsed request is a module
  using description file: C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\taro-hooks\package.json (relative path: ./lib/createUseInfoHook) 
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\taro-hooks\lib\createUseInfoHook\node_modules doesn't exist or is not a directory    
      C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\taro-hooks\lib\node_modules doesn't exist or is not a directory
      C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\taro-hooks\node_modules doesn't exist or is not a directory
      C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules
              Field 'browser' doesn't contain a valid alias configuration
              C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\@taro-hooks\core.mjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\@taro-hooks\core.vue doesn't exist
        C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\@taro-hooks\core doesn't exist
              Field 'browser' doesn't contain a valid alias configuration
              C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\@taro-hooks\core.mjs doesn't exist
            .vue
              Field 'browser' doesn't contain a valid alias configuration
              C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\@taro-hooks\core.vue doesn't exist
        C:\Lance\TaroProjects\taro_3.6.8_hooks\node_modules\@taro-hooks\core doesn't exist
      C:\Lance\TaroProjects\node_modules doesn't exist or is not a directory
      C:\Lance\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory

### 期望结果
编译打包正常

### 实际结果
打包失败

### 环境信息
```
Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.20.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/react: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
      react: ^18.0.0 => 18.2.0
```

---
### 补充信息
npm版本:9.8.0
node版本: 16.21.0
系统:Windows11

**Comment by TheKonka** [comment]
https://github.com/innocces/taro-hooks  可以先到这里问看看

**Comment by Chen-jj** [comment]
https://github.com/innocces/taro-hooks/issues/48

**Comment by innocces** [comment]
如果使用2x 请优先安装对应框架的插件  https://next-version-taro-hooks.vercel.app/site/docs/quick/react-useage

若1x 的话请手动 安装 npm i taro-hooks@1

此外官方仓库中的1x模版和2x不通用. 若使用2x请使用 taro-hooks cannary 的模版初始化

**Comment by Chen-jj** [comment]
最新版 taro-hooks 模板已修复~
