### ISSUE TITLE
编译h5网页显示404

### ISSUE THREAD

**Issue by wlancer1** [NervJS/taro#1418]
编译小程序正常显示，编译h5的时候显示404不显示内容

**Comment by kucy** [comment]
我升级到最新版本就正常了。

**Comment by Littly** [comment]
404是h5路由中对于未注册页面的提示，beta.10版本中有误判。整体升级到1.2.0-beta.11试试

**Comment by wlancer1** [comment]
升级后，在componentWillReceiveProps函数里进行路由跳转的时候跳转不了，无限跳自己

**Comment by lvbaiying** [comment]
1.2.0-beta.3中编译h5模式是可以的 升级到 1.2.0-beta.11 的时候 显示404了

**Comment by lvbaiying** [comment]
> 升级后，在componentWillReceiveProps函数里进行路由跳转的时候跳转不了，无限跳自己

**Comment by lvbaiying** [comment]
> 404是h5路由中对于未注册页面的提示，beta.10版本中有误判。整体升级到1.2.0-beta.11试试

1.2.0-beta.3中编译h5模式是可以的 升级到 1.2.0-beta.11 的时候 显示404了

**Comment by luckyadam** [comment]
@lvbaiying 项目依赖升级了么

**Comment by lvbaiying** [comment]
@luckyadam 项目的所有依赖是 rm -rf 后 重新拉的

**Comment by Littly** [comment]
检查下@tarojs/cli版本是否为最新？
