### ISSUE TITLE
H5 环境中 InnerAudioContext 的 buffered 数值错误

### ISSUE THREAD

**Issue by tangbzai** [NervJS/taro#14185]
### 相关平台
H5

**浏览器版本: edge 114.0.1823.79 (正式版本) (64 位)**
**使用框架: React**

### 复现步骤
调用`Taro.createInnerAudioContext()`后设置个视频地址，获取`buffered`属性

### 期望结果
获取到真实的`buffered`属性

### 实际结果
会显示成`TimeRanges`对象的长度

### 环境信息
```
👽 Taro v3.4.12

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

  Taro CLI 3.4.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

---
### 代码位置：
[InnerAudioContext.ts#L30](https://github.com/NervJS/taro/blob/11d68b4371795eb97d5fb52abad50935ef5429c4/packages/taro-h5/src/api/media/audio/InnerAudioContext.ts#L30C65-L30C65)

### 描述
现在取的是 `buffered.length` 而根据 [HTMLMediaElement - MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement) 中写的 `buffered` 是 [TimeRanges](https://developer.mozilla.org/zh-CN/docs/Web/API/TimeRanges) 类型的
> TimeRanges 接口用来表示一组时间范围，主要目的是跟踪供[<audio>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/audio) 和[<video>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video) 元素加载使用的媒体哪些部分已经被缓冲。
> 一个 TimeRanges 对象包括一个或多个时间范围，其中每个都由一个开始偏移量和结束偏移量指定。
> 你可以将你想要检索的时间范围的索引值传递给 `start()` 和 `end()` 方法来引用每个时间范围。

而文档中的 `buffered` 是个时间点，应该需要查找当前所属的时间范围再返回 `end` 时间

### 疑问点
如果这样实现后，那需要获取所有组的时间范围有什么方式能获取到呢？是否应该有类似 `nativeProps` 的方式透传属性呢？

**Comment by ZakaryCode** [comment]
fixed in #14522
