### ISSUE TITLE
微信小程序不需要加浏览器前缀

### ISSUE THREAD

**Issue by lovelyqun** [NervJS/taro#14193]
### 这个特性解决了什么问题？
优化代码包大小

### 这个 API 长什么样？
在执行微信小程序打包时,不需要对样式加浏览器内核前缀

**Comment by lovelyqun** [comment]
通过配置实现了      autoprefixer: {
        enable: false,
        config: {
          // autoprefixer 配置项
        },
      },
      微信小程序是不是设置默认不开启比较好

**Comment by bigmeow** [comment]
配置下 `package.json` 的 `browserslist`,可以把它支持的浏览器改得更新一些
```
{
  "browserslist": [
    "Android >= 4.1",
    "ios >= 10"
  ],
}
```

**Comment by lovelyqun** [comment]
已解决,关闭
