### ISSUE TITLE
Module not found: Can't resolve './TaroParseabTmpl'

### ISSUE THREAD

**Issue by umeitime** [NervJS/taro#1419]
./.temp/imports/TaroParseaaTmpl.js
Module not found: Can't resolve './TaroParseabTmpl' in '/Users/hujunwei/Desktop/lite_app/taroConvert/.temp/imports'

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/taroize.html#%E8%BD%AC%E6%8D%A2-wxparse-%E6%8A%A5%E9%94%99%E4%B8%8D%E5%AD%98%E5%9C%A8%E6%96%87%E4%BB%B6
看下这个文档

**Comment by yilikunNEO** [comment]
> 把 <template name="wxParse1"> 的模板内所有 <template is="wxParse2" data="{{item}}" /> 修改为 <template is="wxParse0" data="{{item}}" /> 再运行 taro convert 即可。这样修改之后还会取消原来 wxParse 只能处理 11 级 HTML 嵌套的问题，理论上内存不爆栈可以处理无限级 HTML 嵌套。

按照这个建议修改后,再执行`taro convert`,仍然报错:
`Module not found: Can't resolve './TaroParseTmpl' in 'taroConvert/.temp/imports'`
希望得到解答,谢谢
