### ISSUE TITLE
无法获取url中的parameter

### ISSUE THREAD

**Issue by ranglang** [NervJS/taro#142]
```
  Taro.navigateTo({
      url: '/containers/bookDetail/index?id=1',
    });
```

#### /containers/bookDetail/index
```
  componentDidMount(data) {
    console.log('d', data);
  }

  componentWillMount(data) {
    console.log('show', data);
  }
```

## result
![default](https://user-images.githubusercontent.com/12862508/41518699-7344c9bc-72f6-11e8-9fd6-19459a796966.PNG)

**Comment by luckyadam** [comment]
url 参数通过 `this.$router.params` 获取，我加入到文档里哈

**Comment by ranglang** [comment]
this.$router.params works. close it
