### ISSUE TITLE
h5 swiper绑定onChange事件后，每次轮播都会触发多次onChange事件

### ISSUE THREAD

**Issue by bailicangdu** [NervJS/taro#1420]
**问题描述**
swiper绑定onChange事件后，在onChange函数中调用this.setState, 每次轮播都会触发多次onChange事件，并且导致手动滑动后自动轮播失效。

**报错信息**
无报错

**系统信息**

 - 操作系统: [macos]
 - Taro 版本 [1.2.0-beta.11]
 - Node.js 版本 [v10.0.0]
 - 报错平台 [h5]

**Comment by jinjinjin0731** [comment]
this.setState 里面做了些啥操作

**Comment by jinjinjin0731** [comment]
已修复
