### ISSUE TITLE
taro 是否已经支持了 unplugin-auto-import/webpack，plugins要怎么配置啊？

### ISSUE THREAD

**Issue by J1angyue** [NervJS/taro#14214]
### 这个特性解决了什么问题？
unplugin-auto-import/webpack 是否能自动导入？
plugins要怎么配置啊？
不写重复的 taro api 导入代码，提升开发体验

### 这个 API 长什么样？
不写重复的 taro api 导入代码，提升开发体验

**Comment by TheKonka** [comment]
https://blog.csdn.net/weixin_39786582/article/details/131154321
百度出来的结果，试试可以不？

**Comment by J1angyue** [comment]
> https://blog.csdn.net/weixin_39786582/article/details/131154321 百度出来的结果，试试可以不？

谢谢同志，链接里仅仅是 vue和nutui的api自动引入，没有taro的

**Comment by eiinu** [comment]
给 `unplugin-auto-import` 提供一套类似于 [uni-app](https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/uni-app.ts) 这种接口列表，应该就可以实现

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/11899
https://github.com/antfu/unplugin-auto-import/pull/201
相关，我觉得 taro 不会去专门为 [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import) 维护一个 json

**Comment by ZakaryCode** [comment]
> 相关，我觉得 taro 不会去专门为 [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import) 维护一个 json

web 端提供给 babel 的 [json](https://unpkg.com/browse/@tarojs/plugin-platform-h5@3.6.13/dist/definition.json) 应该可用？
