### ISSUE TITLE
是否支持属性精简功能？

### ISSUE THREAD

**Issue by TheKonka** [NervJS/taro#14233]
### 这个特性解决了什么问题？
https://docs.taro.zone/docs/platform-plugin/#%E5%B1%9E%E6%80%A7%E7%B2%BE%E7%AE%80

### 这个 API 长什么样？
可自定义需要打包的属性，或者需要删除的属性

**Comment by Chen-jj** [comment]
使用 CompileMode 可以带到类似效果
