### ISSUE TITLE
微信小程序转taro h5 无法运行

### ISSUE THREAD

**Issue by mienv567** [NervJS/taro#1424]
小程序正常截图
![qq 20181209182608](https://user-images.githubusercontent.com/7724835/49696127-2104aa00-fbe0-11e8-86b9-31686e57cd18.png)

h5截图
![taro-h5](https://user-images.githubusercontent.com/7724835/49696021-8ce61300-fbde-11e8-82f0-722242b848a2.png)

`index.js?e6ae:50 Uncaught (in promise) TypeError: Super expression must either be null or a function
    at _inherits (index.js?e6ae:50)
    at eval (index.js?e6ae:833)
    at createWrappedComponent (index.js?e6ae:974)
    at eval (index.js?e6ae:1030)
index.js?5063:7 Uncaught (in promise) TypeError: _taroH2.default.getApp is not a function
    at eval (index.js?5063:7)
    at Object../.temp/pages/myQuestion/index.js (myQuestion_index.js:11)
    at __webpack_require__ (app.js:768)
    at fn (app.js:131)
    at fn.t (app.js:175)`
微信原生小程序转taro后，taro转小程序可以运行，h5不行。

**Comment by luckyadam** [comment]
把报错贴出来

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/49697096-1c46f280-fbee-11e8-9402-d82b979b4a9a.png)
点进去看下呢

**Comment by mienv567** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/49697096-1c46f280-fbee-11e8-9402-d82b979b4a9a.png)
> 点进去看下呢
function _inherits(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
  第五十行：  throw new TypeError("Super expression must either be null or a function");
  }

**Comment by mienv567** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/49697096-1c46f280-fbee-11e8-9402-d82b979b4a9a.png)
> 点进去看下呢

function _inherits(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    第50行： `throw new TypeError("Super expression must either be null or a function");`
  }

**Comment by mienv567** [comment]
继续测试转换平台
[1.微信转换成功运行](https://github.com/NervJS/taro/issues/1424#issue-389002250)
2.百度转换成功运行，转换过程中以下错误但不影响使用
`错误  压缩错误  文件F:\Git\astro\wenda\taroConvert\node_modules\@tarojs\with-wea
pp\dist\index.js
{ SyntaxError: Unexpected token: punc ())
    at JS_Parse_Error.get (eval at <anonymous> (F:\Git\astro\wenda\taroConvert\n
ode_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
    at formatError (internal/util/inspect.js:775:16)
    at formatRaw (internal/util/inspect.js:573:14)
    at formatValue (internal/util/inspect.js:471:10)
    at inspect (internal/util/inspect.js:193:10)
    at Object.formatWithOptions (util.js:85:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at recursiveRequire (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\@tarojs\cli\src\util\resolve_npm_files.js:214:19)
    at CallExpression (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@
tarojs\cli\src\util\resolve_npm_files.js:143:21)
  message: 'Unexpected token: punc ())',
  filename: '0',
  line: 3045,
  col: 10,
  pos: 82300 }
`
![qq 20181209233414](https://user-images.githubusercontent.com/7724835/49699347-fe3bbb00-fc0a-11e8-90e2-cf2ed5348648.png)
3. 转换react-native 6个页面不成功样式不支持。

4.我感觉转换成小程序都能运行两款已经成功，是不是 es5 es6 语法问题。

**Comment by luckyadam** [comment]
你用的哪个版本转的

**Comment by mienv567** [comment]
> 你用的哪个版本转的

taro 1.2 beta 11，我昨天以为linux下有问题，我就在自己win电脑下安装了最新版.，和linux下一样，会出现以上错误
TypeError: _taroH2.default.getApp
写法：var e = Taro.getApp()
还有这个错误其它就没有啦
TypeError: Super expression must either be null or a

**Comment by luckyadam** [comment]
@mienv567 Taro.getApp() 在 H5 里还没有实现，你可以换种写法，另外那个报错，你得自己定位下问题

**Comment by mienv567** [comment]
> @mienv567 Taro.getApp() 在 H5 里还没有实现，你可以换种写法，另外那个报错，你得自己定位下问题

我不用h5可以，我想用react-native，目前有没有完美的处理pages下的转换方法除css外，我一会儿贴出react转换个别页面转换中出错的地方.

**Comment by mienv567** [comment]
> @mienv567 Taro.getApp() 在 H5 里还没有实现，你可以换种写法，另外那个报错，你得自己定位下问题

嗯，react-native 我也发现是wxml代码的问题，标签括号花括号排序问题，这是经过convert转换后的代码。可能自己在写wxml排列的问题吧
![xo1ds h 0877k y q bnn o](https://user-images.githubusercontent.com/7724835/49734842-8af48080-fcc0-11e8-896a-4aa0ef66a486.png)
