### ISSUE TITLE
vant-weapp van-button dataset 属性设置无效

### ISSUE THREAD

**Issue by HyperLife1119** [NervJS/taro#14256]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:HyperLife1119/taro-issue.git](git@github.com:HyperLife1119/taro-issue.git)
**小程序基础库: 2.33.0**
**使用框架: Vue 3**

### 复现步骤
打开小程序，点击页面上的分享按钮，观察日志中的 dataset 是否有值。

dataset 被编译成了 dataSet，导致无法正确设置 dataset 属性。

### 期望结果
dataset=999

### 实际结果
dataset=null

### 环境信息
```
👽 Taro v3.6.11


  Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11 
      @tarojs/components: 3.6.11 => 3.6.11 
      @tarojs/helper: 3.6.11 => 3.6.11 
      @tarojs/plugin-framework-vue3: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11 
      @tarojs/runtime: 3.6.11 => 3.6.11 
      @tarojs/shared: 3.6.11 => 3.6.11 
      @tarojs/taro: 3.6.11 => 3.6.11 
      @tarojs/taro-loader: 3.6.11 => 3.6.11 
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11 
      babel-preset-taro: 3.6.11 => 3.6.11 
      eslint-config-taro: 3.6.11 => 3.6.11 
```

### 相关链接

van-button 文档：https://vant-contrib.gitee.io/vant-weapp/#/button

**Comment by TheKonka** [comment]
看了下，原因应该是 dataset 是 TaroElement的公有属性，vue runtime 会检测 props 是不是 element 的 属性，如果是，就直接使用 set 修改属性，不使用 setAttribute 方法，导致 taro 没有接收到 props

https://github.com/vuejs/core/blob/3be4e3cbe34b394096210897c1be8deeb6d748d8/packages/runtime-dom/src/patchProp.ts#L113

https://github.com/vuejs/core/blob/3be4e3cbe34b394096210897c1be8deeb6d748d8/packages/runtime-dom/src/modules/props.ts#L95
