### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by J1angyue** [NervJS/taro#14252]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/J1angyue/taro-process-undefined.git](https://github.com/J1angyue/taro-process-undefined.git)
**小程序基础库: 2.33.0**
**使用框架: Vue 3**

### 复现步骤
git clone https://github.com/J1angyue/taro-process-undefined.git

cd taro-process-undefined

pnpm i

pnpm d:we

打开微信小程序开发工具，导入 dist
小程序开发工具控制台会打印错误：
页面【pages/login/index]错误:
 ReferenceError: process is not defined
    at Object../src/utils/request.js (._src_utils_request.js:3)
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../src/api/user.js (._node_modules_.pnpm_@nutui nutui-taro@4.1.2_unplugin-vue-components@0.25.1_node_modules_@nutui_nutui-taro_dist_packages_input_index.scss:1)
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../src/stores/user.js (._src_api_user.js:3)
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../node_modules/.pnpm/unplugin@1.4.0/node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-auto-import!./node_modules/.pnpm/unplugin@1.4.0/node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components!./node_modules/.pnpm/babel-loader@8.2.1_@babel core@7.8.0_webpack@5.78.0/node_modules/babel-loader/lib/index.js??clonedRuleSet-11.use[0]!./node_modules/.pnpm/vue-loader@17.0.0_webpack@5.78.0/node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/login/index.vue?vue&type=script&setup=true&lang=js (index.vue?1fc4:23)
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../src/pages/login/index.vue?vue&type=script&setup=true&lang=js (index.vue?b800:9)
    at __webpack_require__ (webpack_bootstrap:19)(env: Windows,mp,1.06.2303220; lib: 2.33.0)

### 期望结果
不报错，页面正常运行，请求地址和.env.**文件相同

### 实际结果
 ReferenceError: process is not defined

### 环境信息
```
👽 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.16.0 - D:\Softs\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.1 - D:\Softs\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-vue3: 3.6.8 => 3.6.8
      @tarojs/plugin-html: ^3.6.10 => 3.6.10
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/taro-loader: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8
```

---
### 补充信息
是突然间报错process is not defined的，有一段时间是能访问到环境变量的

**Comment by xuanzebin** [comment]
参考：https://docs.taro.zone/docs/config-detail#env

**Comment by xuanzebin** [comment]
需要自己在 config 配置 env

**Comment by J1angyue** [comment]
@xuanzebin 我是按照这份文档实现的，taro的版本是3.6.8，为什么不行呢？https://docs.taro.zone/docs/env-mode-config

**Comment by J1angyue** [comment]
@xuanzebin 不是访问不到环境变量，而是访问 process 都报错。

是 **process is not defined** 而不是 **process.env.XXXXXXX is not defined**

**Comment by xuanzebin** [comment]
功能没有问题，但是你的环境变量文件里缺少对 TARO_APP_API_BASE_URL 的配置，但是你却在 `src/utils/request.js` 中使用了它：
```js
const API_BASE_URL = process.env.TARO_APP_BASE_URL + process.env.TARO_APP_API_BASE_URL
```

**Comment by Lawrence51** [comment]
![Uploading image.png…]()
单纯打印一下process就会报错

**Comment by Lawrence51** [comment]
> 功能没有问题，但是你的环境变量文件里缺少对 TARO_APP_API_BASE_URL 的配置，但是你却在 `src/utils/request.js` 中使用了它：
> 
> ```js
> const API_BASE_URL = process.env.TARO_APP_BASE_URL + process.env.TARO_APP_API_BASE_URL
> ```

现在直接访问process，直接就会报错，只是单纯打印 process

**Comment by bigmeow** [comment]
process 不是对象，没有这个全局变量，自然无法访问。process.env.xxxx 能有值是因为是代码编译时的全局替换，它并非运行时代码

**Comment by Lawrence51** [comment]
> 

编译的时候没有做替换吗

**Comment by Lawrence51** [comment]
> process 不是对象，没有这个全局变量，自然无法访问。process.env.xxxx 能有值是因为是代码编译时的全局替换，它并非运行时代码

编译的时候没有做替换吗？那 .env 文件没法用了吧

**Comment by bigmeow** [comment]
有用的。替换是 完全匹配替换。

**Comment by Lawrence51** [comment]
> 有用的。替换是 完全匹配替换。
试了下，不太行呢，需要额外的配置吗？或者有示例吗

**Comment by Lawrence51** [comment]
> 有用的。替换是 完全匹配替换。

那 .env 文件的书写格式是这样吗?

`
process.env.TARO_APP_API='"https://taro.com"'
`
然后访问的话直接就： console.log（process.env.TARO_APP_API）


我看文档应该是 
`
TARO_APP_API='"https://taro.com"'
`
但是好像没什么用

**Comment by bigmeow** [comment]
https://github.com/J1angyue/taro-process-undefined/blob/8778f56187d98c9305e17b3a496bb5adecd53131/src/utils/request.js#L3C66-L3C87

`.env` 文件中没有定义 `TARO_APP_API_BASE_URL`

**Comment by hzeeli** [comment]
@Lawrence51 hi，找到问题以及解决方法了吗？我也遇到了

**Comment by wmpeng** [comment]
+1

**Comment by wmpeng** [comment]
**我发现了一个解决方法，但我的问题和题主的问题不一定一样**

## 问题描述
### 环境
taro版本 3.6.13
### 操作
按照这个方法配置环境变量 `https://docs.taro.zone/docs/env-mode-config`
我当时的操作是：在.env.dev文件夹加上了一行

```
TARO_APP_BASE_URL = "http://127.0.0.1:5000"
```

然后再执行时`yarn dev:h5 --port 8080`就出现了 `process is not defined`的错误

## 解决方法
1. 将`package.json`中的`"dev:h5": "npm run build:h5 -- --watch"`改成`"dev:h5": "npm run build:h5 -- --watch --mode dev"`
其他的依次类推
2. 或者新建.env文件并在其中添加对应的变量

## 分析
默认的`npm run build:h5 -- --watch`并不会去读.env.dev文件而是.env文件，但是我本身不存在.env文件，所以报错。
而process.xxxx并不是在浏览器运行时获取的，而是编译时做的替换，所以正常情况下，编译结果中并不会包括process.xxx。如果找不到特定的process.xxx就会报错

**Comment by Davied-H** [comment]
> **我发现了一个解决方法，但我的问题和题主的问题不一定一样**
> 
> ## 问题描述
> ### 环境
> taro版本 3.6.13
> 
> ### 操作
> 按照这个方法配置环境变量 `https://docs.taro.zone/docs/env-mode-config` 我当时的操作是：在.env.dev文件夹加上了一行
> 
> ```
> TARO_APP_BASE_URL = "http://127.0.0.1:5000"
> ```
> 
> 然后再执行时`yarn dev:h5 --port 8080`就出现了 `process is not defined`的错误
> 
> ## 解决方法
> 1. 将`package.json`中的`"dev:h5": "npm run build:h5 -- --watch"`改成`"dev:h5": "npm run build:h5 -- --watch --mode dev"`
>    其他的依次类推
> 2. 或者新建.env文件并在其中添加对应的变量
> 
> ## 分析
> 默认的`npm run build:h5 -- --watch`并不会去读.env.dev文件而是.env文件，但是我本身不存在.env文件，所以报错。 而process.xxxx并不是在浏览器运行时获取的，而是编译时做的替换，所以正常情况下，编译结果中并不会包括process.xxx。如果找不到特定的process.xxx就会报错

这种方式run build可以，但是我build的时候还是会报：process is not defined

**Comment by J1angyue** [comment]
@Davied-H @wmpeng @hzeeli @bigmeow @xuanzebin @Lawrence51 是这样的：vite 本来自己除了会读当前mode的env文件，还会继承 .env 文件，但是 taro 不知道为什么不会继承 .env，只会傻傻的只读取当前 mode 的。

**Comment by bigmeow** [comment]
我没遇到你说的问题，我这里会继承

**Comment by dongpobaicai** [comment]
> @xuanzebin 我是按照这份文档实现的，taro的版本是3.6.8，为什么不行呢？https://docs.taro.zone/docs/env-mode-config

config/index.js  env配置环境变量确实可以在业务代码中使用。.env.development只能够在node环境中，至于官方文档中 “**被载入的环境变量我们可以在所有 taro 插件、 config/index.ts配置文件 以及 src 目录下面的项目文件中使用**” 这个在src下就是提示  process这个对象不存在。我推测是，打包编译时候是 webpack => node环境，可以识别这个process。一旦到了运行时，就是前端浏览器环境，就无法访问到 process

**Comment by bigmeow** [comment]
无论node还是运行时，都不是把 `process` 当对象使用的，而是“静态的全局字符串替换”，`process.env.xxx` 这是一个静态的常量，编译时当静态字符串替换的，你要是把它当对象的属性去“点”出来，那就完全理解错误了

**Comment by 490626721** [comment]
> 无论node还是客户端运行时，都不要把 `process` 当对象使用（虽然node有process对象，但是2个环境里都适用的话，就不能把它当对象来用），而是“静态的全局字符串替换”，`process.env.xxx` 这是一个静态的常量，编译时当静态字符串替换的，你要是把它当对象的属性去“点”出来，那就完全理解错误了。 客户端环境本来就没 process 这个对象，只有 node 里有。

https://taro-docs.jd.com/docs/best-practice#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-processenv-%E7%9A%84%E4%BD%BF%E7%94%A8你在打官方脸？

**Comment by night-mao** [comment]
> **我发现了一个解决方法，但我的问题和题主的问题不一定一样**
> 
> ## 问题描述
> ### 环境
> taro版本 3.6.13
> 
> ### 操作
> 按照这个方法配置环境变量 `https://docs.taro.zone/docs/env-mode-config` 我当时的操作是：在.env.dev文件夹加上了一行
> 
> ```
> TARO_APP_BASE_URL = "http://127.0.0.1:5000"
> ```
> 
> 然后再执行时`yarn dev:h5 --port 8080`就出现了 `process is not defined`的错误
> 
> ## 解决方法
> 1. 将`package.json`中的`"dev:h5": "npm run build:h5 -- --watch"`改成`"dev:h5": "npm run build:h5 -- --watch --mode dev"`
>    其他的依次类推
> 2. 或者新建.env文件并在其中添加对应的变量
> 
> ## 分析
> 默认的`npm run build:h5 -- --watch`并不会去读.env.dev文件而是.env文件，但是我本身不存在.env文件，所以报错。 而process.xxxx并不是在浏览器运行时获取的，而是编译时做的替换，所以正常情况下，编译结果中并不会包括process.xxx。如果找不到特定的process.xxx就会报错

我也遇到问题了，只是我的`package.json`中的`"build:weapp"里加了--mode dev, 然后‘npm run build:weapp -- --watch --mode dev’ 里又有mode dev,就导致报错`process is not defined`, 把dev里的mode参数删掉就好了

**Comment by wmpeng** [comment]
> > 无论node还是客户端运行时，都不要把 `process` 当对象使用（虽然node有process对象，但是2个环境里都适用的话，就不能把它当对象来用），而是“静态的全局字符串替换”，`process.env.xxx` 这是一个静态的常量，编译时当静态字符串替换的，你要是把它当对象的属性去“点”出来，那就完全理解错误了。 客户端环境本来就没 process 这个对象，只有 node 里有。
> 
> [https://taro-docs.jd.com/docs/best-practice#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-processenv-%E7%9A%84%E4%BD%BF%E7%94%A8你在打官方脸？](https://taro-docs.jd.com/docs/best-practice#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-processenv-%E7%9A%84%E4%BD%BF%E7%94%A8%E4%BD%A0%E5%9C%A8%E6%89%93%E5%AE%98%E6%96%B9%E8%84%B8%EF%BC%9F)

怎么看着你饮用的话 和 你贴的连接，是一个意思呢？process.env.NODE_ENV就是做静态替换的，并不是一个object

**Comment by HappyDingning** [comment]
报错的那个页面的代码文件里面，随便注释掉一个函数，编译一下，然后取消注释，重新编译，就好了。

反正我这样就好了，大家可以试试
