### ISSUE TITLE
3.6.11 h5无法运行

### ISSUE THREAD

**Issue by agileago** [NervJS/taro#14257]
### 相关平台
H5

### 复现仓库

https://github.com/agileago/vue3-taro

[git@github.com:agileago/vue3-taro.git](git@github.com:agileago/vue3-taro.git)

**浏览器版本: chrome100****小程序基础库: 3.0**
**使用框架: Vue 3**

### 复现步骤
> taro build --type h5 "--watch"

👽 Taro v3.6.11

启动  读取env环境变量  development
启动  读取env环境变量  development
Tips:
1. 建议开启持久化缓存功能，能有效提升二次编译速度，详情请参考: https://docs.taro.zone/docs/config-detail#cache。

● Webpack █████████████████████████ setup (3%)  
 watch run

⠋ 即将开始启动编译，请稍等~<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:10086/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.2:10086/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:10086/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/jianhua/work/vue3-taro/dist' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
/Users/jianhua/work/vue3-taro/node_modules/.pnpm/webpack-virtual-modules@0.5.0/node_modules/webpack-virtual-modules/lib/index.js:132
        finalInputFileSystem._writeVirtualFile(modulePath, stats, contents);
                             ^

TypeError: finalInputFileSystem._writeVirtualFile is not a function
    at VirtualModulesPlugin.writeModule (/Users/jianhua/work/vue3-taro/node_modules/.pnpm/webpack-virtual-modules@0.5.0/node_modules/webpack-virtual-modules/src/index.ts:155:26)
    at /Users/jianhua/work/vue3-taro/node_modules/.pnpm/@tarojs webpack5-prebundle@3.6.11_postcss@8.4.27_vue@3.3.4_webpack@5.88.2/node_modules/@tarojs/webpack5-prebundle/src/index.ts:129:23
    at Array.forEach (<anonymous>)
    at TaroPrebundle.<anonymous> (/Users/jianhua/work/vue3-taro/node_modules/.pnpm/@tarojs webpack5-prebundle@3.6.11_postcss@8.4.27_vue@3.3.4_webpack@5.88.2/node_modules/@tarojs/webpack5-prebundle/src/index.ts:115:33)
    at Generator.next (<anonymous>)
    at /Users/jianhua/work/vue3-taro/node_modules/.pnpm/@tarojs webpack5-prebundle@3.6.11_postcss@8.4.27_vue@3.3.4_webpack@5.88.2/node_modules/@tarojs/webpack5-prebundle/dist/index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jianhua/work/vue3-taro/node_modules/.pnpm/@tarojs webpack5-prebundle@3.6.11_postcss@8.4.27_vue@3.3.4_webpack@5.88.2/node_modules/@tarojs/webpack5-prebundle/dist/index.js:30:12)
    at TaroPrebundle.postCompilerStart (/Users/jianhua/work/vue3-taro/node_modules/.pnpm/@tarojs webpack5-prebundle@3.6.11_postcss@8.4.27_vue@3.3.4_webpack@5.88.2/node_modules/@tarojs/webpack5-prebundle/dist/index.js:102:16)
    at /Users/jianhua/work/vue3-taro/node_modules/.pnpm/@tarojs webpack5-runner@3.6.11_@babel core@7.22.9_@swc core@1.3.23_@vue compiler-sfc@3.3.4_po_cahfkwcvan24dyagss3m4kuahe/node_modules/@tarojs/webpack5-runner/src/index.h5.ts:98:18

Node.js v20.3.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

进程已结束，退出代码为 1

### 期望结果
能跑

### 实际结果
不能跑

### 环境信息
```

启动  读取env环境变量  undefined
启动  读取env环境变量  undefined

  Taro CLI 3.6.10 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.3.0 - ~/Library/pnpm/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 9.6.7 - ~/Library/pnpm/npm
    npmPackages:
      @tarojs/cli: ^3.6.11 => 3.6.11 
      @tarojs/components: 3.6.11 => 3.6.11 
      @tarojs/helper: 3.6.11 => 3.6.11 
      @tarojs/plugin-framework-vue3: 3.6.11 => 3.6.11 
      @tarojs/plugin-html: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-h5: ^3.6.11 => 3.6.11 
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11 
      @tarojs/runtime: 3.6.11 => 3.6.11 
      @tarojs/shared: 3.6.11 => 3.6.11 
      @tarojs/taro: 3.6.11 => 3.6.11 
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11 
      babel-preset-taro: 3.6.11 => 3.6.11 
      eslint-config-taro: 3.6.11 => 3.6.11 
```

---

**Comment by Ttou** [comment]
是有这个问题，回退到 3.6.10 正常

**Comment by ZakaryCode** [comment]
该问题与 PreBundle 被禁用相关联，可以启用跳过该问题，将在下一个版本中修复

**Comment by csyaonie** [comment]
我真的服了3.6.10  h5启动有问题，3.6.11 又出现这个编译问题，两个版本我都不能用，12什么时候上

**Comment by TechQuery** [comment]
Windows 10 上正常，Vercel 这样的线上 Linux 环境有楼主同样的错误：idea2app/Taro-Vant-MobX-ts#10
