### ISSUE TITLE
3.5.4 版本 编译成h5后在支付宝小程序webview中安卓真机访问白屏

### ISSUE THREAD

**Issue by Yevunye** [NervJS/taro#14263]
### 相关平台
支付宝小程序

**小程序基础库: 2.0**
**使用框架: Vue 3**

### 复现步骤
https://testlawsonh5.yorentown.com/common_mini_program/index.html?timestamp=1690642299020&envType=alipayMiniProgram&token=26777274_9407B206075A4FBE86A3F0388F67FD9F&regionBlockCode=sh-lawson&uuid=6296fd9d004c7aa721492fb03b888f86#/pages/help-center/index/index?webview=new

### 期望结果
支付宝小程序webview 安卓真机正常显示

### 实际结果
支付宝小程序webview 安卓真机打开 白屏
支付宝小程序webview IOS真机打开 正常显示
微信小程序webview 安卓真机打开 正常显示
微信小程序webview IOS真机打开 正常显示

### 环境信息
```
启动  读取env环境变量  undefined
启动  读取env环境变量  undefined

  Taro CLI 3.5.4 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.3 - ~/Library/pnpm/node
      npm: 6.14.18- ~/Library/pnpm/npm
    npmPackages:
      @tarojs/cli: ^3.5.4 => 3.5.4
      @tarojs/components: 3.5.4 => 3.5.4
      @tarojs/helper: 3.5.4 => 3.5.4
      @tarojs/plugin-framework-vue3: 3.5.4 =>3.5.4
      @tarojs/plugin-html: 3.5.4 => 3.5.4
      @tarojs/plugin-platform-h5: ^3.5.4=> 3.5.4
      @tarojs/plugin-platform-weapp:3.5.4 => 3.5.4
      @tarojs/runtime: 3.5.4 => 3.5.4
      @tarojs/shared: 3.5.4 => 3.5.4
      @tarojs/taro: 3.5.4=> 3.5.4 
      @tarojs/webpack5-runner: 3.5.4=> 3.5.4
      babel-preset-taro: 3.5.4 => 3.5.4
      eslint-config-taro: 3.5.4 => 3.5.4 
```

**Comment by TheKonka** [comment]
白屏一般都是报错了，搞个 vconsole之类的看下控制台。。
比如你是不是用了  Object.fromEntries
![image](https://github.com/NervJS/taro/assets/22173084/f3b17cc8-4bc6-4e5c-a53f-ced75074c433)

**Comment by ZakaryCode** [comment]
或许是使用了不支持的语法，可以找到对应报错的代码，确定是否通过 babel-loader 转换，如果没有可以通过 [compiler.include](https://nervjs.github.io/taro-docs/docs/next/config-detail#h5compileinclude) 添加
