### ISSUE TITLE
Error: true is not a PostCSS plugin

### ISSUE THREAD

**Issue by hooliy** [NervJS/taro#14264]
### 相关平台
微信小程序
![image](https://github.com/NervJS/taro/assets/3368691/f9a0d3dc-6a8e-4b52-ab7d-77e9db0c051b)

**小程序基础库: 3.0**
**使用框架: React**

### 复现步骤
编译报错

### 期望结果
正确

### 实际结果
错误

### 环境信息
```
Taro v3.3.12


  Taro CLI 3.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\hooliy\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@hooliy 建议参考 #12274 和 #12290 看看，或者升级 Taro 的版本再试试。如还有问题，请提供完整可复现的 Demo.
