### ISSUE TITLE
我们这边要参加支付宝小程序开发者大会技术选型上需要分享taro的优势，希望大佬能给予一些数据支持

### ISSUE THREAD

**Issue by ThomasXing** [NervJS/taro#14271]
### 这个特性解决了什么问题？
https://open.alipay.com/portal/forum/post/131801016

### 这个 API 长什么样？
佛祖保佑 永无bug

**Comment by TheKonka** [comment]
可以参考taro官网的博客

**Comment by ThomasXing** [comment]
需要做跟uniapp等有个实际的比较
| |
邢海青
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月07日 16:36 |
| 收件人 | NervJS/taro ***@***.***> |
| 抄送人 | ThomasXing ***@***.***>,
State ***@***.***> |
| 主题 | Re: [NervJS/taro] 渣渣辉与古天乐 (Issue #14271) |

可以参考taro官网的博客
