### ISSUE TITLE
页面之间如何通信

### ISSUE THREAD

**Issue by huixisheng** [NervJS/taro#1427]
`PageA->PageB` 在`PageB`操作需要有新数据产生需要传给`PageA`

目前想到方法
1. `localStorage` `PageB`写入`PageA`读取
2. ` App()` 添加`global`对象

想请问在`taro`有没有其他实现方式？

**Comment by jiangbingkui** [comment]
路由传参就好了

**Comment by Pines-Cheng** [comment]
事件

**Comment by yuche** [comment]
楼上的说的都对，你还可以用 Taro 内置的 event center:
https://nervjs.github.io/taro/docs/events.html#docsNav
或者 redux:
https://nervjs.github.io/taro/docs/redux.html#docsNav
或者 mobx:
https://nervjs.github.io/taro/docs/mobx.html#docsNav
