### ISSUE TITLE
Swiper 图片重复问题

### ISSUE THREAD

**Issue by js1121302139** [NervJS/taro#1429]
重现步骤
index.js
componentWillMount() { let { b } = this.$router.params; pictureUrlList = b?['https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250','https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250','https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250','https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250']:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsQXoVnHYbnWjpZPMpqVaMjM-XknhatY2ICLQ1kMzLB-QgimMLQ','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsQXoVnHYbnWjpZPMpqVaMjM-XknhatY2ICLQ1kMzLB-QgimMLQ','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsQXoVnHYbnWjpZPMpqVaMjM-XknhatY2ICLQ1kMzLB-QgimMLQ'] } /* pictureUrlList 这个需要自定义两个不重复的图片数组才能看得见问题 */ {pictureUrlList ? <Swiper className="Banner" circular indicatorDots autoplay > { pictureUrlList && pictureUrlList.map(item => { return ( <SwiperItem> <Image className='imgItem' src={item} /> </SwiperItem> ) }) } </Swiper> : null}
a.js
onTapGoPage(b) { Taro.navigateTo({ url:/pages/detail/index?b=${b}}) } <View className="Item" onClick={this.onTapGoPage.bind(this,true)}> true </View> <View className="Item" onClick={this.onTapGoPage.bind(this,false)}> false </View>

依赖的版本号
{
"name": "yichangqiusaiMiniApp",
"version": "1.0.0",
"private": true,
"description": "",
"scripts": {
"build:weapp": "taro build --type weapp",
"build:swan": "taro build --type swan",
"build:alipay": "taro build --type alipay",
"build:h5": "taro build --type h5",
"build:rn": "taro build --type rn",
"dev:weapp": "npm run build:weapp -- --watch",
"dev:swan": "npm run build:swan -- --watch",
"dev:alipay": "npm run build:alipay -- --watch",
"dev:h5": "npm run build:h5 -- --watch",
"dev:rn": "npm run build:rn -- --watch"
},
"author": "",
"license": "MIT",
"dependencies": {
"@tarojs/async-await": "1.2.0-beta.9",
"@tarojs/components": "1.2.0-beta.9",
"@tarojs/redux": "1.2.0-beta.9",
"@tarojs/redux-h5": "1.2.0-beta.9",
"@tarojs/router": "1.2.0-beta.9",
"@tarojs/taro": "1.2.0-beta.9",
"@tarojs/taro-alipay": "1.2.0-beta.9",
"@tarojs/taro-h5": "1.2.0-beta.9",
"@tarojs/taro-swan": "1.2.0-beta.9",
"@tarojs/taro-weapp": "1.2.0-beta.9",
"nerv-devtools": "^1.3.9",
"nervjs": "^1.3.9",
"redux": "^4.0.0",
"redux-logger": "^3.0.6",
"redux-thunk": "^2.3.0",
"taro-ui": "1.5.0"
},
"devDependencies": {
"@tarojs/plugin-babel": "1.2.0-beta.9",
"@tarojs/plugin-csso": "1.2.0-beta.9",
"@tarojs/plugin-less": "1.2.0-beta.9",
"@tarojs/plugin-sass": "^1.2.0-beta.10",
"@tarojs/plugin-uglifyjs": "1.2.0-beta.9",
"@tarojs/webpack-runner": "1.2.0-beta.9",
"@types/react": "^16.4.8",
"@types/webpack-env": "^1.13.6",
"babel-eslint": "^8.2.3",
"babel-plugin-transform-class-properties": "^6.24.1",
"babel-plugin-transform-decorators-legacy": "^1.3.4",
"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
"babel-plugin-transform-object-rest-spread": "^6.26.0",
"babel-preset-env": "^1.6.1",
"eslint": "^4.19.1",
"eslint-config-taro": "1.2.0-beta.9",
"eslint-plugin-import": "^2.12.0",
"eslint-plugin-react": "^7.8.2",
"eslint-plugin-taro": "1.2.0-beta.9"
}
}

预期结果
图片不会重复

实际结果
图片会跟之前上一次点击的页面重复

相关链接

**Comment by js1121302139** [comment]
H5版本

**Comment by jinjinjin0731** [comment]
能用代码块整理一下文字吗。。 有点没看懂你的逻辑

**Comment by js1121302139** [comment]
稍等 这个刚刚从另一个地方复制的

**Comment by js1121302139** [comment]
`
这里是swiper
componentWillMount() { let { b } = this.$router.params; pictureUrlList = b?['https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250','https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250','https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250','https://sophosnews.files.wordpress.com/2013/05/bug_thumb.jpg?w=250']:['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsQXoVnHYbnWjpZPMpqVaMjM-XknhatY2ICLQ1kMzLB-QgimMLQ','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsQXoVnHYbnWjpZPMpqVaMjM-XknhatY2ICLQ1kMzLB-QgimMLQ','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGsQXoVnHYbnWjpZPMpqVaMjM-XknhatY2ICLQ1kMzLB-QgimMLQ'] } /* pictureUrlList 这个需要自定义两个不重复的图片数组才能看得见问题 */ {pictureUrlList ? <Swiper className="Banner" circular indicatorDots autoplay > { pictureUrlList && pictureUrlList.map(item => { return ( <SwiperItem> <Image className='imgItem' src={item} /> </SwiperItem> ) }) } </Swiper> : null}
`
`
a.js
onTapGoPage(b) { Taro.navigateTo({ url:/pages/detail/index?b=${b}}) } <View className="Item" onClick={this.onTapGoPage.bind(this,true)}> true </View> <View className="Item" onClick={this.onTapGoPage.bind(this,false)}> false </View>

`

**Comment by js1121302139** [comment]
https://github.com/NervJS/taro-ui/issues/233

**Comment by jinjinjin0731** [comment]
我这里没法复现你的问题，我重新整理了一下代码，你的 let { b } = this.$router.params;  这行， b 取出来不一定是布尔值，而你下面 pictureUrlList 走的是三目运算，你的 b 是字符串的情况下，按你现有逻辑，三目走的永远都是 true 逻辑，你检查一下 b 的值是什么

**Comment by js1121302139** [comment]
b不一定需要布尔值只是希望在每次点击进去的时候展示不一样的图片列表而已，你可以将图片列表作为参数传到跳转的那个页面

**Comment by jinjinjin0731** [comment]
但是你贴出来的代码逻辑 pictureUrlList = b ？xxx: xxx  你这里的 b 永远是 true 啊。所以你图片数组是一直没有变化的。

**Comment by jinjinjin0731** [comment]
我通过你贴出来的代码，是没有复现重复问题的
