### ISSUE TITLE
@tarojs/plugin-http 小程序下 axios 全局拦截器无效

### ISSUE THREAD

**Issue by tianxing0923** [NervJS/taro#14305]
### 相关平台
微信小程序

**小程序基础库: 3.0.0**
**使用框架: React**

### 复现步骤
```
import axios from axios

// 添加请求拦截器
axios.interceptors.request.use(
  (config) => {
    // 在发送请求之前做些什么
    return config
  },
  (error) => {
    // 对请求错误做些什么
    return Promise.reject(error)
  }
)

// 添加响应拦截器
axios.interceptors.response.use(
  (response) => {
    // 对响应数据做点什么
    return response
  },
  (error) => {
    // 对响应错误做点什么
    return Promise.reject(error)
  }
)
```

### 期望结果
全局添加拦截器可用

### 实际结果
全局添加无效，只有实例级才有效
```
const instance = axios.create();
instance.interceptors.request.use(function () {/*...*/});
```

### 环境信息
```
👽 Taro v3.6.11


  Taro CLI 3.6.11 environment info:
```

---
### 补充信息
taro info  报错：

taro info

👽 Taro v3.6.11

/Users/tianxing/.nvm/versions/node/v16.20.1/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js:50
                sourcePath: path.join(this.appPath, this.initialConfig.sourceRoot),
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'sourceRoot')
    at Kernel.initPaths (/Users/tianxing/.nvm/versions/node/v16.20.1/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/src/Kernel.ts:90:64)
    at new Kernel (/Users/tianxing/.nvm/versions/node/v16.20.1/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/src/Kernel.ts:73:10)
    at CLI.<anonymous> (/Users/tianxing/.nvm/versions/node/v16.20.1/lib/node_modules/@tarojs/cli/src/cli.ts:76:22)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tianxing/.nvm/versions/node/v16.20.1/lib/node_modules/@tarojs/cli/dist/cli.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by bigmeow** [comment]
这是 `axios` 自身的行为，和插件无关，插件只是实现了XHRHttpRequest 对象而已。

你的拦截器添在 `axios.interceptors` 身上，那么你发起请求也需要用 `axios.request()` 方法才能触发，不确定这是 `axios` 的特性还是 `bug`, 可自行向 `axios` 那边反馈

**Comment by bigmeow** [comment]
我翻了下 `axios` 的 源码：
https://github.com/axios/axios/blob/3f53eb6960f05a1f88409c4b731a40de595cb825/lib/axios.js#L46
```typescript
const axios = createInstance(defaults);
// 省略中间代码
axios.default = axios;

// 默认导出的就是一个 axios 实例
export default axios

```
所以你下面的代码导入的其实就是一个axios 创建的实例：
```typescript
import axios from axios

// 添加请求拦截器
axios.interceptors.request.use(
  (config) => {
    // 在发送请求之前做些什么
    return config
  },
  (error) => {
    // 对请求错误做些什么
    return Promise.reject(error)
  }
)
```

那么压根就没有全局拦截器这个说法， 只有实例的拦截器，你用哪个实例进行请求的，那么挂在哪个实例对象下的拦截器才会生效。这和我上面说的表现是相符合的。

**Comment by ShadowSpeedy** [comment]
@tianxing0923  老哥最后解决问题了吗

**Comment by tianxing0923** [comment]
> @tianxing0923 老哥最后解决问题了吗

上面老哥已经回复了啊，没有全局拦截器，如果想多个实例都拦截，就封装一下：

```
function createAxios(baseURL: string) {
  const instance = axios.create({ baseURL })
  // 添加请求拦截器
  axios.interceptors.request.use(
    (config) => {
      // 在发送请求之前做些什么
      return config
    },
    (error) => {
      // 对请求错误做些什么
      return Promise.reject(error)
    }
  )

  // 添加响应拦截器
  axios.interceptors.response.use(
    (response) => {
      // 对响应数据做点什么
      return response
    },
    (error) => {
      // 对响应错误做点什么
      return Promise.reject(error)
    }
  )
  return instance
}

export const xApi = createAxios(config.api.x)
export const yApi = createAxios(config.api.y)

```
