### ISSUE TITLE
Taro.createIntersectionObserver(component, options) 能不能走点心

### ISSUE THREAD

**Issue by aamina8866** [NervJS/taro#14302]
### 相关平台
微信小程序

**小程序基础库: 3.0.0**
**使用框架: Vue 3**

### 复现步骤
Taro.createIntersectionObserver(component, options) 参数observeAll: true 只能监听第一个元素

### 期望结果
完善了。

### 实际结果
只能监听第一个元素

### 环境信息
```
Taro CLI 3.6.10 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.0 - /usr/local/bin/node
      Yarn: 4.0.0-rc.48.git.20230727.hash-88cf2c2 - /usr/local/bin/yarn
      npm: 9.8.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11 
      @tarojs/components: 3.6.11 => 3.6.11 
      @tarojs/helper: 3.6.11 => 3.6.11 
      @tarojs/plugin-framework-vue3: 3.6.11 => 3.6.11 
      @tarojs/plugin-html: ^3.6.11 => 3.6.11 
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11 
      @tarojs/runtime: 3.6.11 => 3.6.11 
      @tarojs/shared: 3.6.11 => 3.6.11 
      @tarojs/taro: 3.6.11 => 3.6.11 
      @tarojs/taro-loader: 3.6.11 => 3.6.11 
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11 
      babel-preset-taro: 3.6.11 => 3.6.11 
      eslint-config-taro: 3.6.11 => 3.6.11 

```

---
### 补充信息
Taro.getCurrentInstance().page.createIntersectionObserver({
        thresholds: [0],
        observeAll: true
      })
这个就可以，但是 这个接口会显示0个参数 。这个不重要重要的是能用。
看了很多Issue ，搜了很多资料，弄了将近4个小时 ，真是服了 老六

**Comment by johnsoncheg** [comment]
+1，还好看到你这个issue了

**Comment by ZakaryCode** [comment]
> Taro.getCurrentInstance().page.createIntersectionObserver({
> thresholds: [0],
> observeAll: true
> })
> 这个就可以，但是 这个接口会显示0个参数 。这个不重要重要的是能用。

这个问题应该反馈给小程序方，另外按照[微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/api/wxml/wx.createIntersectionObserver.html)，`thresholds: [0]` 应当是默认值

**Comment by KanLai** [comment]
> > Taro.getCurrentInstance().page.createIntersectionObserver({
> > thresholds: [0],
> > observeAll: true
> > })
> > 这个就可以，但是 这个接口会显示0个参数 。这个不重要重要的是能用。
> 
> 这个问题应该反馈给小程序方，另外按照[微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/api/wxml/wx.createIntersectionObserver.html)，`thresholds: [0]` 应当是默认值

我没懂你什么意思，这个本来就是一个bug啊 ，我的意思是  
Taro.createIntersectionObserver(component, options) 这个只能监听到第一个元素，
Taro.getCurrentInstance().page.createIntersectionObserver()这个在声明的时候是无参数，

**Comment by ZakaryCode** [comment]
> 我没懂你什么意思，这个本来就是一个bug啊 ，我的意思是

看起来是换了个 GitHub 账号回复？

> Taro.createIntersectionObserver(component, options) 这个只能监听到第一个元素，

该方法传入 `observeAll: true` 没有监听全部应当向微信方反馈，taro 在这里只做透传（当然也不排除使用时 component 传入错误导致出现该情况，由于缺少示例项目无法进一步判断 issue 所述实际情况

> Taro.getCurrentInstance().page.createIntersectionObserver()这个在声明的时候是无参数，

此处声明参考[微信小程序文档](https://developers.weixin.qq.com/miniprogram/dev/reference/api/Component.html#%E5%8F%82%E6%95%B0)，该参数实际可用将在后续补充相关类型。

**Comment by JunVincetHuo** [comment]
是否这个问题，直接调用微信的createIntersectionObserver是没有问题的，应该是没有把observeAll透传过去，目前taro的表现只能监听第一个元素
