### ISSUE TITLE
允许入口组件返回 null

### ISSUE THREAD

**Issue by s97712** [NervJS/taro#14314]
### 这个特性解决了什么问题？
我需要先远程加载数据再展现页面
我尝试让入口组件返回null，直到所有数据准备完毕再返回children
但taro好像不支持这种用法，入口组件返回null会报错 `Uncaught Error: 没有找到页面实例。`

可以考虑支持这种用法吗，现在我只能在所有页面引入加载数据的代码，用起来特别麻烦的。

### 这个 API 长什么样？
```ts
function App({ children }: PropsWithChildren<any>) {

  useLaunch(() => {
    console.log('App launched.')
  })

  // client.config.appInfo({ params: { appid: appInfo.appId } })
  // children 是将要会渲染的页面
  const [ready, setReady] = useState(false)
  useEffect(() => {
    Taro.showLoading({ title: '加载中...' })
    setTimeout(() => {
      Taro.hideLoading()
      setReady(true)
    }, 1000)
  }, [])
  return ready ? children: null;
}
```

**Comment by peterczg** [comment]
@s97712 具体是哪个端？

**Comment by tourze** [comment]
兼容的做法，可以先返回一个 <View />

**Comment by s97712** [comment]
> @s97712 具体是哪个端？
抖音端，微信去年尝试过，也是报错。

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/11396#issuecomment-1142007215
可以试下 display:none ?

**Comment by s97712** [comment]
> [#11396 (comment)](https://github.com/NervJS/taro/issues/11396#issuecomment-1142007215) 可以试下 display:none ?

不是显示的问题，而是数据的加载问题

**Comment by s97712** [comment]
> > [#11396 (comment)](https://github.com/NervJS/taro/issues/11396#issuecomment-1142007215) 可以试下 display:none ?
> 
> 不是显示的问题，而是数据的加载问题

这个问题跟display是没有关系的，display仅改变了DOM的样式，我的问题在于页面渲染和数据初始化的顺序。


我需要在数据加载初始化之后，再去render页面。
而不是先render页面，然后每个页面还要单独去初始化数据，这样你每个页面都得来一遍，特别麻烦。

**Comment by ZakaryCode** [comment]
> 这个问题跟display是没有关系的，display仅改变了DOM的样式，我的问题在于页面渲染和数据初始化的顺序。
> 
> 我需要在数据加载初始化之后，再去render页面。 而不是先render页面，然后每个页面还要单独去初始化数据，这样你每个页面都得来一遍，特别麻烦。

写个 context 到页面内去判断 ready 呗，或者封装个高阶组件或者钩子来处理

**Comment by daizeming** [comment]
> > 这个问题跟display是没有关系的，display只是改变了DOM的样式，我的问题是提供页面渲染和数据初始化的顺序。
> > 我需要在数据加载初始化之后，再去渲染页面。而不是先渲染页面，然后每个页面还要另外去初始化数据，这样你每个页面都得来一遍，特别麻烦。
> 
> 写个上下文到页面内去判断准备好了呗，或者封装个高阶组件或者钩子来处理

使用hoc处理异步加载页面，会有个问题，页面的useLoad,useDidshow会无法触发。因为在异步请求数据时，hoc渲染了loading，这时候useLoad,useDidshow执行时机已经触发了。在到页面组件时，这几个钩子就不会在执行。请问这种有没有什么好的解决方案呢？
```typescript
const withPageReady = (PageComponent: React.ComponentType) => {

  return function PageReady(props) {
    const [isMTJsReady, setIsMTJsReady] = useState(false);

    useEffect(() => {
      // 等待请求数据后，再渲染页面
      setTimeout(() => {
        setIsMTJsReady(true);
      }, 2000);
    })

    if (!isMTJsReady) {
      console.time('isReady');
      return (
        <Loading className="page-ready-loading" type='circular' />
      );
    } else {
      console.timeEnd('isReady');
    }

    return <PageComponent {...props} />;
  };
};
```
