### ISSUE TITLE
小程序getCurrentPages之后怎么执行某个page的方法呢？

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#1431]
打印出来这个数组里面找不到

**Comment by yuche** [comment]
`const pages = Taro.getCurrentPages().map(c => c.$component)`
Taro 的实例在小程序实例的 $component 上

**Comment by ShaoGongBra** [comment]
@yuche 把这个打印出来也没有看见我写的方法在什么地方呀？
c.$component

**Comment by yuche** [comment]
找到数组里的那个实例直接调用就好了

**Comment by ShaoGongBra** [comment]
@yuche 真的可以直接调用呀，我说我怎么打印出来怎么都找不到

**Comment by yuche** [comment]
因为他在原型上
