### ISSUE TITLE
同一个设备上在微信小程序上的字体比h5上的字体大

### ISSUE THREAD

**Issue by xujiujiu** [NervJS/taro#14336]
### 相关平台
微信小程序

**小程序基础库: 3.0.0**
**使用框架: Vue 2**

### 复现步骤
taro版本 ： 3.5.7

```
// index.vue 
 <view class="index">
    <text>你好你好你好你好你好你好 12312312'Hello world!'</text>
  </view>

// index.less
.index{
  font-size: 80px;
}
```

### 期望结果
微信小程序字体与h5上的字体一致

### 实际结果
微信小程序字体比h5上的字体大

### 环境信息
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - D:\node program\nodejs\node.EXE     
      Yarn: 1.22.19 - D:\node program\node_global\yarn.CMD
      npm: 7.7.6 - D:\node program\nodejs\npm.CMD
```

![image](https://github.com/NervJS/taro/assets/25719101/bcb2e9b8-c872-4c2c-b431-acabefba997d)

**Comment by ZakaryCode** [comment]
受 web 端根节点字号配置影响，两端实际显示字号确实会有差异，可以通过以下方式跳过 web 端针对于 PC 场景的此项配置：

1. 将[根节点字号最大最小值](https://nervjs.github.io/taro-docs/docs/size#maxrootsize-number-h5-only-default-40)限制取消，配置为 0 和 Infinity
2. 或者升级到最新版本，并将[目标转换单位](https://nervjs.github.io/taro-docs/docs/size#targetunit-string)设置为 vw
