### ISSUE TITLE
3.6.12 h5无法构建 weapp下启动报错

### ISSUE THREAD

**Issue by DuduStyle** [NervJS/taro#14354]
### 相关平台
H5 WEAPP

### 复现仓库
[git@github.com:DuduStyle/nuti-taro-ui.git](git@github.com:DuduStyle/nuti-taro-ui.git)
https://github.com/DuduStyle/nuti-taro-ui
**浏览器版本: 无需**
**使用框架: React**

#### 问题1复现步骤：
yarn build:h5

#### 问题2
yarn dev:weapp
页面中配置文件
```ts
// src\pages\index\index.config.ts
  usingComponents: {
		cell: 'plugin://contactPlugin/cell',
	},
```

### 期望结果
正常构建正常启动

#### 问题1（H5构建）：
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Invalid URL: //mallstatic-s-cdn2.xxx.cn/mall/h5/static/images/assets/images/cart.png
-- inner error --
TypeError [ERR_INVALID_URL]: Invalid URL: //mallstatic-s-cdn2.xxx.cn/mall/h5/static/images/assets/images/cart.png
Generated code for E:\stu\nuti-taro-ui\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[2].oneOf[0].use[0]!E:\stu\nuti-taro-ui\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[3].use[0]!E:\stu\nuti-taro-ui\node_modules\resolve-url-loader\index.js!E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[5].use[1]!E:\stu\nuti-taro-ui\src\pages\index\index.scss

#### 问题2（小程序启动）：
● Webpack █████████████████████████ setup (3%)  
 watch run

(node:24188) UnhandledPromiseRejectionWarning: Error: Cannot find module 'plugin://contactPlugin/cell'
Require stack:
- E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\dist\plugins\BuildNativePlugin.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\dist\webpack\MiniWebpackPlugin.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\dist\webpack\MiniCombination.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\dist\index.mini.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\index.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\helper\dist\npm.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\helper\dist\index.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\helper\index.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\cli\dist\util\index.js
- E:\stu\nuti-taro-ui\node_modules\@tarojs\cli\bin\taro
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at TaroMiniPlugin.compileFile (E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:792:30)
    at E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:667:12 
    at Set.forEach (<anonymous>)
    at TaroMiniPlugin.getPagesConfig (E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:663:16)
    at TaroMiniPlugin.run (E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:454:12)
    at TaroMiniPlugin.<anonymous> (E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:199:20)
    at Generator.next (<anonymous>)
    at E:\stu\nuti-taro-ui\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:8:71  
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 31.35s.

### 环境信息
```
👽 Taro v3.6.11


  Taro CLI 3.6.11 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.6.4 - ~\AppData\Roaming\npm\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.12 => 3.6.12 
      @tarojs/components: 3.6.12 => 3.6.12 
      @tarojs/helper: 3.6.12 => 3.6.12 
      @tarojs/plugin-framework-react: 3.6.12 => 3.6.12 
      @tarojs/plugin-html: 3.6.12 => 3.6.12 
      @tarojs/plugin-platform-alipay: 3.6.12 => 3.6.12 
      @tarojs/plugin-platform-h5: 3.6.12 => 3.6.12 
      @tarojs/plugin-platform-jd: 3.6.12 => 3.6.12 
      @tarojs/plugin-platform-qq: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-swan: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-tt: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-weapp: 3.6.12 => 3.6.12
      @tarojs/react: 3.6.12 => 3.6.12
      @tarojs/runtime: 3.6.12 => 3.6.12
      @tarojs/shared: 3.6.12 => 3.6.12
      @tarojs/taro: 3.6.12 => 3.6.12
      @tarojs/taro-loader: 3.6.12 => 3.6.12
      @tarojs/webpack5-runner: 3.6.12 => 3.6.12
      babel-preset-taro: 3.6.12 => 3.6.12
      eslint-config-taro: 3.6.12 => 3.6.12
      react: ^18.0.0 => 18.2.0
```

**Comment by ZakaryCode** [comment]
所以到底是哪个端？h5 还是微信？

h5 不支持 usingComponents 参数，如果使用需要通过[多端脚本](https://nervjs.github.io/taro-docs/docs/envs#%E5%A4%9A%E7%AB%AF%E8%84%9A%E6%9C%AC%E9%80%BB%E8%BE%91)排除相关逻辑

**Comment by DuduStyle** [comment]
> 所以到底是哪个端？h5 还是微信？
> 
> h5 不支持 usingComponents 参数，如果使用需要通过[多端脚本](https://nervjs.github.io/taro-docs/docs/envs#%E5%A4%9A%E7%AB%AF%E8%84%9A%E6%9C%AC%E9%80%BB%E8%BE%91)排除相关逻辑
> 
> 另外所述 demo 中无法复现该问题，相关资源无法获取为错误地址（或 CDN 映射地址未在公网提供）导致，与框架侧并无关联

两个问题，两个端都有。第一个问题，是H5的打包问题，打包会解析URL的真实公网地址？第二个问题为小程序下使用usingComponents 的问题

**Comment by DuduStyle** [comment]
为了验证非taro/cli的版本问题，版本已升级为v3.6.12,h5下构建依旧报错。
经过验证，3.6.12 下H5下新版本`output.publicPath`不支持function   @ZakaryCode 
```cmd
PS E:\stu\nuti-taro-ui> taro info        
👽 Taro v3.6.12


  Taro CLI 3.6.12 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.6.4 - ~\AppData\Roaming\npm\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.12 => 3.6.12
      @tarojs/components: 3.6.12 => 3.6.12
      @tarojs/helper: 3.6.12 => 3.6.12
      @tarojs/plugin-framework-react: 3.6.12 => 3.6.12
      @tarojs/plugin-html: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-alipay: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-h5: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-jd: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-qq: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-swan: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-tt: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-weapp: 3.6.12 => 3.6.12
      @tarojs/react: 3.6.12 => 3.6.12
      @tarojs/runtime: 3.6.12 => 3.6.12
      @tarojs/shared: 3.6.12 => 3.6.12
      @tarojs/taro: 3.6.12 => 3.6.12
      @tarojs/taro-loader: 3.6.12 => 3.6.12
      @tarojs/webpack5-runner: 3.6.12 => 3.6.12
      babel-preset-taro: 3.6.12 => 3.6.12
      eslint-config-taro: 3.6.12 => 3.6.12
      react: ^18.0.0 => 18.2.0

```

**Comment by xuanzebin** [comment]
第二个问题已修复，可以升级到 3.6.13 进行验证

**Comment by DuduStyle** [comment]
> 第二个问题已修复，可以升级到 3.6.13 进行验证

thanks

**Comment by DuduStyle** [comment]
> 

@ZakaryCode @xuanzebin 第一个问题有打算支持么？如果只能支持string，bug我就关闭了。

**Comment by xuanzebin** [comment]
> > 
> 
> @ZakaryCode @xuanzebin 第一个问题有打算支持么？如果只能支持string，bug我就关闭了。

目前只支持 string
