### ISSUE TITLE
1.2.0-beta.12版本h5编译成功，但是界面报错

### ISSUE THREAD

**Issue by AloneWeb** [NervJS/taro#1437]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
1.2.0-beta.12版本h5编译成功，但是界面js报错，在1.1.9里没有问题，其他版本没有试过
**复现步骤**
[复现问题的步骤]
1. npm run dev:h5

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
不报错
**报错信息**
![image](https://user-images.githubusercontent.com/22211269/49719984-b0ba5f00-fc99-11e8-8e3b-b7432bdfd5e0.png)

![image](https://user-images.githubusercontent.com/22211269/49719934-8e284600-fc99-11e8-9dbc-c82aff69c137.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.0-beta.12]
 - Node.js 版本 [e.g. v10.5.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
你的页面覆盖了 constructor 但是没有传传 context，你直接写 super(...arguments) 吧

**Comment by AloneWeb** [comment]
是不是不能这样写了
constructor(props) {
}

**Comment by luckyadam** [comment]
> 是不是不能这样写了
> constructor(props) {
> super(props)
> }
> @luckyadam

是啊 ，按我说的那样写吧
