### ISSUE TITLE
小程序隐私协议更新导致的部分api无法使用

### ISSUE THREAD

**Issue by aaa123123999** [NervJS/taro#14376]
### 这个特性解决了什么问题？
什么时候会支持这部分的功能，现在一些手机号和复制功能将要失效

**Comment by Zeppo241** [comment]
在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined
