### ISSUE TITLE
小程序隐私协议更新导致的部分api无法使用

### ISSUE THREAD

**Issue by aaa123123999** [NervJS/taro#14377]
### 这个特性解决了什么问题？
什么时候会支持这部分的功能，9月15日后将无法使用这部分api比如现在的粘贴功能就无法使用

### 这个 API 长什么样？
什么时候会支持这部分的功能

**Comment by zedwang** [comment]
Same question.

**Comment by jz-9527** [comment]
微信需要把Button的openType设置为"agreePrivacyAuthorization"，同时bindagreeprivacyauthorization 监听用户同意隐私协议事件，目前taro的Button组件是没有支持的，这个怎么解决？微信目前已经更新了文档了https://developers.weixin.qq.com/miniprogram/dev/component/button.html

**Comment by xuanzebin** [comment]
> 微信需要把Button的openType设置为"agreePrivacyAuthorization"，同时bindagreeprivacyauthorization 监听用户同意隐私协议事件，目前taro的Button组件是没有支持的，这个怎么解决？微信目前已经更新了文档了https://developers.weixin.qq.com/miniprogram/dev/component/button.html

通过 taro-inject 插件可以自定义添加 taro 组件属性和事件的绑定：https://github.com/NervJS/taro-plugin-inject

**Comment by TheKonka** [comment]
> 

单就你说的Button组件的修改，taro 是已经支持了的

**Comment by TheKonka** [comment]
> 微信需要把Button的openType设置为"agreePrivacyAuthorization"，同时bindagreeprivacyauthorization 监听用户同意隐私协议事件，目前taro的Button组件是没有支持的，这个怎么解决？微信目前已经更新了文档了https://developers.weixin.qq.com/miniprogram/dev/component/button.html

**Comment by cuiliming666** [comment]
请问下现在有taro适配小程序9月15号调整隐私政策的方案了吗？

**Comment by jz-9527** [comment]
> @jz-9527
> 
> 单就你说的Button组件的修改，taro 是已经支持了的 #14183

这个我看了下，是针对微信手机号授权收费问题的更新，并不是这次隐私协议的更新改动，如果大佬们更新上去了，还请留一下稳定可用的版本号，感激不尽

**Comment by bigmeow** [comment]
1. 升级最新版本
2. 老版本支持指南：
```bash
# 注意版本号和自己的 taro 主版本号保持一致
npm i @tarojs/plugin-inject -D
```

`config/index.js` 中增加 `plugins` 配置:
```tsx
{
  ... 其他配置
   plugins:[
      [
        "@tarojs/plugin-inject",
        {
          components: {
            Button: {
              bindagreeprivacyauthorization: ""
            }
          }
        }
      ]
    ]
}

```

类型定义直接忽略：
```tsx
<Button
  // @ts-ignore
  openType="agreePrivacyAuthorization"
  // @ts-ignore
  onAgreePrivacyAuthorization={handleOnAgreePrivacyAuthorization}
  
>我同意</Button>


```

**Comment by cuiliming666** [comment]
大佬们现在项目是taro 2.0.1（不支持plugins）且不好升级，是不是没法子搞了

**Comment by bs32g1038** [comment]
不升级taro版本，要怎么兼容处理，头大

**Comment by cuiliming666** [comment]
有没有啥好的方案呀，求救，一堆依赖短时间升不上去

**Comment by TheKonka** [comment]
```
wx.requirePrivacyAuthorize(Object object)

wx.openPrivacyContract(Object object)

wx.onNeedPrivacyAuthorization(function listener)

wx.getPrivacySetting(Object object)
```

这些 `wx.` api 都可以在代码里面直接调用

**Comment by cuiliming666** [comment]
使用‘agreePrivacyAuthorization’类型的button，不想升级可以使用混合写法，用小程序的写法或页面来实现（taro 2.0.1实验成功）

**Comment by cuiliming666** [comment]
想使用‘agreePrivacyAuthorization’类型的button，不想升级可以使用混合写法，用小程序的写法写组件或页面来实现（taro 2.0.1实验成功）

**Comment by lupingW** [comment]
> 请问下现在有taro适配小程序9月15号调整隐私政策的方案了吗？

https://juejin.cn/post/7272749016755765300

**Comment by Zeppo241** [comment]
在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined

**Comment by szqingt** [comment]
> 在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined

基础库是用的最新的吗？

**Comment by Zeppo241** [comment]
> 



> 

是的，3.0.1

**Comment by Zeppo241** [comment]
> > 在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined
> 
> 基础库是用的最新的吗？

是的，3.0.1

**Comment by hongzhiyuan-man** [comment]
> 想使用‘agreePrivacyAuthorization’类型的button，不想升级可以使用混合写法，用小程序的写法写组件或页面来实现（taro 2.0.1实验成功）

大佬，这样要怎么做啊

**Comment by Xhyen** [comment]
> 在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined

我这里可以，但是出现了告警
`无效的 app.json ["__usePrivacyCheck__"]`

然后导致wx.getPrivacySetting这个方法无法执行，没有回调参数

**Comment by sjy9280** [comment]
taro 2.x版本的怎么搞

**Comment by cuiliming666** [comment]
目前采用混写的方式，判断是否需要授权及‘agreePrivacyAuthorization’同意按钮，使用的是原生来写的弹窗组件，再引入到需要使用的页面，2.0.1及3.x用这个方案都改造完成了

**Comment by deliveph** [comment]
onAgreePrivacyAuthorization  这个触发无效 有什么解决方案吗

**Comment by TheKonka** [comment]
> onAgreePrivacyAuthorization 这个触发无效 有什么解决方案吗

你是不是写错了，是 onNeedPrivacyAuthorization ，你 调用 wx.requirePrivacyAuthorize 就会触发

**Comment by deliveph** [comment]
<Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization={}></Button>    需要这样不是才能同意嘛

**Comment by deliveph** [comment]
Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization=  这样才能同意啊

**Comment by TheKonka** [comment]
> Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊

这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization

**Comment by deliveph** [comment]
> > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> 
> 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization

我是搞了个按纽给让用户点击的  但不触发onAgreePrivacyAuthorization  很奇怪

**Comment by TheKonka** [comment]
> > > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> > 
> > 
> > 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization
> 
> 我是搞了个按纽给让用户点击的 但不触发onAgreePrivacyAuthorization 很奇怪

用户点击 Button openType='agreePrivacyAuthorization' 是**同意**协议了，不会触发**需要同意**onNeedPrivacyAuthorization的。。你还是仔细看下文档先

**Comment by Capchen** [comment]
> > > > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> > > 
> > > 
> > > 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization
> > 
> > 
> > 我是搞了个按纽给让用户点击的 但不触发onAgreePrivacyAuthorization 很奇怪
> 
> 用户点击 Button openType='agreePrivacyAuthorization' 是**同意**协议了，不会触发**需要同意**onNeedPrivacyAuthorization的。。你还是仔细看下文档先

他的意思，我理解应该是使用的官方「2. 主动查询隐私授权同步状态以及展示隐私协议」这个方案，发现button的@agreeprivacyauthorization="handleAgreePrivacyAuthorization"不生效， 你说的应该是「3. 被动监听隐私接口需要用户授权事件」这个方案。

**Comment by deliveph** [comment]
> > > > > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> > > > 
> > > > 
> > > > 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization
> > > 
> > > 
> > > 我是搞了个按纽给让用户点击的 但不触发onAgreePrivacyAuthorization 很奇怪
> > 
> > 
> > 用户点击 Button openType='agreePrivacyAuthorization' 是**同意**协议了，不会触发**需要同意**onNeedPrivacyAuthorization的。。你还是仔细看下文档先
> 
> 他的意思，我理解应该是使用的官方「2. 主动查询隐私授权同步状态以及展示隐私协议」这个方案，发现button的@agreeprivacyauthorization="handleAgreePrivacyAuthorization"不生效， 你说的应该是「3. 被动监听隐私接口需要用户授权事件」这个方案。

是的 ，onAgreeprivacyauthorization="handleAgreePrivacyAuthorization" 不生效，我把版本也更新到了3.6以上了，也无效

**Comment by Capchen** [comment]
> > > > > > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> > > > > 
> > > > > 
> > > > > 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization
> > > > 
> > > > 
> > > > 我是搞了个按纽给让用户点击的 但不触发onAgreePrivacyAuthorization 很奇怪
> > > 
> > > 
> > > 用户点击 Button openType='agreePrivacyAuthorization' 是**同意**协议了，不会触发**需要同意**onNeedPrivacyAuthorization的。。你还是仔细看下文档先
> > 
> > 
> > 他的意思，我理解应该是使用的官方「2. 主动查询隐私授权同步状态以及展示隐私协议」这个方案，发现button的@agreeprivacyauthorization="handleAgreePrivacyAuthorization"不生效， 你说的应该是「3. 被动监听隐私接口需要用户授权事件」这个方案。
> 
> 是的 ，onAgreeprivacyauthorization="handleAgreePrivacyAuthorization" 不生效，我把版本也更新到了3.6以上了，也无效

我这边更新到最新的3.6.15版本，vue3写法
```
<button open-type="agreePrivacyAuthorization" @agreeprivacyauthorization="handleAgreePrivacyAuthorization">
同意
</button>
```
是能触发`handleAgreePrivacyAuthorization`的

**Comment by deliveph** [comment]
> > > > > > > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> > > > > > 
> > > > > > 
> > > > > > 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization
> > > > > 
> > > > > 
> > > > > 我是搞了个按纽给让用户点击的 但不触发onAgreePrivacyAuthorization 很奇怪
> > > > 
> > > > 
> > > > 用户点击 Button openType='agreePrivacyAuthorization' 是**同意**协议了，不会触发**需要同意**onNeedPrivacyAuthorization的。。你还是仔细看下文档先
> > > 
> > > 
> > > 他的意思，我理解应该是使用的官方「2. 主动查询隐私授权同步状态以及展示隐私协议」这个方案，发现button的@agreeprivacyauthorization="handleAgreePrivacyAuthorization"不生效， 你说的应该是「3. 被动监听隐私接口需要用户授权事件」这个方案。
> > 
> > 
> > 是的 ，onAgreeprivacyauthorization="handleAgreePrivacyAuthorization" 不生效，我把版本也更新到了3.6以上了，也无效
> 
> 我这边更新到最新的3.6.15版本，vue3写法
> 
> ```
> <button open-type="agreePrivacyAuthorization" @agreeprivacyauthorization="handleAgreePrivacyAuthorization">
> 同意
> </button>
> ```
> 
> 是能触发`handleAgreePrivacyAuthorization`的

我用是react  不行

**Comment by TheKonka** [comment]
@deliveph  是我理解错了，你说按钮点击 不触发 onAgreePrivacyAuthorization  ，这个我用 react 试了也是可以正常触发的，把 taro 相关依赖都更新到最新版试试

**Comment by yurnery** [comment]
我也是用的 React, onAgreePrivacyAuthorization 这个回调不会触发!
```
<Button
        openType='agreePrivacyAuthorization'
        onAgreePrivacyAuthorization={() => {
          console.log("click');
        }}
        className='privacy_modal_button'
      >
        同意
      </Button>
```

**Comment by TheKonka** [comment]
> 我也是用的 React, onAgreePrivacyAuthorization 这个回调不会触发!
> 
> ```
> <Button
>         openType='agreePrivacyAuthorization'
>         onAgreePrivacyAuthorization={() => {
>           console.log("click');
>         }}
>         className='privacy_modal_button'
>       >
>         同意
>       </Button>
> ```

确认 taro 相关依赖和 微信基础库都是最新的

**Comment by yurnery** [comment]
> > 我也是用的 React, onAgreePrivacyAuthorization 这个回调不会触发!
> > ```
> > <Button
> >         openType='agreePrivacyAuthorization'
> >         onAgreePrivacyAuthorization={() => {
> >           console.log("click');
> >         }}
> >         className='privacy_modal_button'
> >       >
> >         同意
> >       </Button>
> > ```
> 
> 确认 taro 相关依赖和 微信基础库都是最新的

Taro相关的都是最新的了

**Comment by gyt95** [comment]
vue3版本可行方案，亲测可以：

已知：Taro3.5
后台：需要授权手机号就在小程序后台添加对应隐私协议指引https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/
安装：yarn add @tarojs/plugin-inject -D  https://github.com/NervJS/taro-plugin-inject
配置：config/index.js
```js
const config = {
  // ...
  plugins: [
    // '@tarojs/plugin-html', 'taro-plugin-pinia', // 其它插件
    [
      "@tarojs/plugin-inject",
      {
        
        components: {
          Button: {
            bindagreeprivacyauthorization: ""
          }
        }
      }
    ]
  ],
}
```
微信开发者工具配置基础库：3.0.0
app.config.ts 添加属性
```js
export default defineAppConfig({
  pages: [...],
  __usePrivacyCheck__: true, // 添加这个
})
```
 
xxx.vue
```vue
<template>
  <nut-button
       open-type="getPhoneNumber"
       type="primary"
       @getphonenumber="(e) => getPhoneNumber(e, item)"
  >授权手机号</nut-button>
  </nut-button>
  <view v-if="showPrivacy">
    <view>隐私弹窗内容....</view>
    <button open-type="agreePrivacyAuthorization" @agreeprivacyauthorization="handleAgreePrivacyAuthorization">
    同意
    </button>
  </view>
</template>
<script lang="ts" setup>
const showPrivacy = ref(false)
const handleAgreePrivacyAuthorization = () =>{
  console.log(666)
}
const togglePrivacy = () => {
  console.log(showPrivacy.value)
  showPrivacy.value = true
}
useLoad((options) => {
  console.log('useLoad', options);
  wx.getPrivacySetting({
      success: res => {
        console.log(res) // 返回结果为: res = { needAuthorization: true/false, privacyContractName: '《xxx隐私保护指引》' }
        // if (res.needAuthorization) {
        //   // 需要弹出隐私协议
        //   this.setData({
        //     showPrivacy: true
        //   })
        // } else {
        //   // 用户已经同意过隐私协议，所以不需要再弹出隐私协议，也能调用隐私接口
        // }
      },
      fail: () => {},
    })
})
</script>
```
清空全部缓存，重新进入时会看到触发wx.getPrivacySetting，返回的是`needAuthorization: true, privacyContractName: "《xxx小程序隐私保护指引》", errMsg: "getPrivacySetting:ok"`

点击同意按钮后，下次就会返回`needAuthorization: false`。

我这里是点击触发，真正应该是页面一进入就直接弹窗。

yarn dev:wepp 和 yarn build:app 均正常。

**Comment by yurnery** [comment]
react 版本有人成功回调的, 麻烦@一下我,  Taro.getPrivacySetting 这个方法是能返回`needAuthorization: true, privacyContractName: "《xxx小程序隐私保护指引》", errMsg: "getPrivacySetting:ok" ` 这些数据, 只是点击了同意之后, `onAgreePrivacyAuthorization`这个不执行, 下次进来还是继续需要授权

**Comment by m-initiator** [comment]
> react 版本有人成功回调的, 麻烦@一下我, Taro.getPrivacySetting 这个方法是能返回`needAuthorization: true, privacyContractName: "《xxx小程序隐私保护指引》", errMsg: "getPrivacySetting:ok" ` 这些数据, 只是点击了同意之后, `onAgreePrivacyAuthorization`这个不执行, 下次进来还是继续需要授权

3.6.6版本的成功了，用的@tarojs/plugin-inject(3.6.6)这种方法。本来想尝试最新版本的，但是报其它错误，只能回滚到3.6.6.

**Comment by yurnery** [comment]
> react 版本有人成功回调的, 麻烦@一下我, Taro.getPrivacySetting 这个方法是能返回`needAuthorization: true, privacyContractName: "《xxx小程序隐私保护指引》", errMsg: "getPrivacySetting:ok" ` 这些数据, 只是点击了同意之后, `onAgreePrivacyAuthorization`这个不执行, 下次进来还是继续需要授权

成功了,  是我们之前把这个按钮放在 `@antmjs/vantui` 的Dialog 里, 这个Dialog 里的点击都没响应! 我自己 render 就好了

**Comment by yaodongyi** [comment]
> 

<img width="664" alt="image" src="https://github.com/NervJS/taro/assets/31060569/889dd625-cfb9-448d-acd3-0a12b6f2b7e8">

**Comment by TheKonka** [comment]
@yaodongyi  用最新的3.6.15，onAgreePrivacyAuthorization 可以正常监听到，我试了没问题

**Comment by yaodongyi** [comment]
3.6.15，指的是taro框架升级到3.6.15？

**Comment by yaodongyi** [comment]
@TheKonka 3.6.15，指的是taro框架升级到3.6.15？

**Comment by TheKonka** [comment]
> @TheKonka 3.6.15，指的是taro框架升级到3.6.15？

最好taro 相关的都升级到 3.6.15 ，如果不都升级到话， @tarojs/plugin-platform-weapp 这个包必须升级到最新版

**Comment by yaodongyi** [comment]
@TheKonka 那看起来没办法，不管是`@tarojs/plugin-platform-weapp`升级，还是框架升级，都会报错。
1. `taro`框架整体升级：babel等各种依赖报错，项目崩溃。
2. `@tarojs/plugin-platform-weapp`升级，应该是涉及写法/属性报错，项目崩溃。

**Comment by yaodongyi** [comment]
老框架无法回调`onAgreePrivacyAuthorization`，解决方式：暂用`onClick`代替

**Comment by lupingW** [comment]
> 老框架无法回调`onAgreePrivacyAuthorization`，解决方式：暂用`onClick`代替

@tarojs/plugin-inject 往上翻 用这个插件就行

**Comment by yaodongyi** [comment]
@lupingW 已经装了，这里发不了视频，我视频发社区微信群了，这个～怎么说呢，想要回调应该是无解，只能重构或者官方调整一下插件支持回调。
`@tarojs/plugin-inject`第一时间安装了，能够使用open-type，就是无法触发`onAgreePrivacyAuthorization`回调。

**Comment by abramyangfab** [comment]
`Taro.<wxapi>`都触发不了`onAgreePrivacyAuthorization`，升级到了3.6.15了。
例如 `Taro.saveImageToPhotosAlbum`不能触发，但是 `wx.saveImageToPhotosAlbum`能够触发

**Comment by lovepotato** [comment]
有大佬告知一下Taro2.x怎么适配吗?

**Comment by moseszhou** [comment]
> 有大佬告知一下Taro2.x怎么适配吗?

Taro2应该没有这个问题

**Comment by Zavierrr** [comment]
> 目前采用混写的方式，判断是否需要授权及‘agreePrivacyAuthorization’同意按钮，使用的是原生来写的弹窗组件，再引入到需要使用的页面，2.0.1及3.x用这个方案都改造完成了

但是回调怎么办呢，像这样：
![image](https://github.com/NervJS/taro/assets/48075834/ef7a4bde-3468-4372-a672-d898f5617063)
报错：不存在属性“bindgetphonenumber”

**Comment by catmiao8** [comment]
> 1. 升级最新版本
> 2. 老版本支持指南：
> 
> ```shell
> # 注意版本号和自己的 taro 主版本号保持一致
> npm i @tarojs/plugin-inject -D
> ```
> 
> `config/index.js` 中增加 `plugins` 配置:
> 
> ```tsx
> {
>   ... 其他配置
>    plugins:[
>       [
>         "@tarojs/plugin-inject",
>         {
>           
>           components: {
>             Button: {
>               bindagreeprivacyauthorization: ""
>             }
>           }
>         }
>       ]
>     ]
> }
> ```
> 
> 类型定义直接忽略（类似定义这里我自己写的openType怎么也覆盖不了，所以暂时先忽略用着）：
> 
> ```tsx
> <Button
>   // @ts-ignore
>   openType="agreePrivacyAuthorization"
>   // @ts-ignore
>   onAgreePrivacyAuthorization={handleOnAgreePrivacyAuthorization}
>   
> >我同意</Button>
> ```
> 
> `types/global.d.ts`:
> 
> ```ts
> declare module "@tarojs/taro" {
>   namespace getPrivacySetting {
>     interface Option {
>       /** 接口调用结束的回调函数（调用成功、失败都会执行） */
>       complete?: (res: TaroGeneral.CallbackResult) => void;
>       /** 接口调用失败的回调函数 */
>       fail?: (res: TaroGeneral.CallbackResult) => void;
>       /** 接口调用成功的回调函数 */
>       success?: (result: SuccessCallbackResult) => void;
>     }
>     interface SuccessCallbackResult extends TaroGeneral.CallbackResult {
>       /** 是否需要用户授权隐私协议（如果开发者没有在[mp后台-设置-服务内容声明-用户隐私保护指引]中声明隐私收集类型则会返回false；如果开发者声明了隐私收集，且用户之前同意过隐私协议则会返回false；如果开发者声明了隐私收集，且用户还没同意过则返回true；如果用户之前同意过、但后来小程序又新增了隐私收集类型也会返回true） */
>       needAuthorization: boolean;
>       /** 隐私授权协议的名称 */
>       privacyContractName: string;
>     }
>   }
>   interface TaroStatic {
>     getPrivacySetting: (option?: getPrivacySetting.Option) => void;
>   }
> }
> ```
> 
> 注意不要用 promise 的写法



> 微信需要把Button的openType设置为“agreePrivacyAuthorization”，同时绑定dagreeprivacyauthorization监听用户同意隐私协议事件，目前taro的Button组件是不支持的，这个怎么解决？微信目前已经更新了文档了https://developers.weixin [. qq.com/miniprogram/dev/component/button.html](https://developers.weixin.qq.com/miniprogram/dev/component/button.html)



> 1. 升级最新版本
> 2. 老版本支持指南：
> 
> ```shell
> # 注意版本号和自己的 taro 主版本号保持一致
> npm i @tarojs/plugin-inject -D
> ```
> 
> `config/index.js` 中增加 `plugins` 配置:
> 
> ```tsx
> {
>   ... 其他配置
>    plugins:[
>       [
>         "@tarojs/plugin-inject",
>         {
>           
>           components: {
>             Button: {
>               bindagreeprivacyauthorization: ""
>             }
>           }
>         }
>       ]
>     ]
> }
> ```
> 
> 类型定义直接忽略（类似定义这里我自己写的openType怎么也覆盖不了，所以暂时先忽略用着）：
> 
> ```tsx
> <Button
>   // @ts-ignore
>   openType="agreePrivacyAuthorization"
>   // @ts-ignore
>   onAgreePrivacyAuthorization={handleOnAgreePrivacyAuthorization}
>   
> >我同意</Button>
> ```
> 
> `types/global.d.ts`:
> 
> ```ts
> declare module "@tarojs/taro" {
>   namespace getPrivacySetting {
>     interface Option {
>       /** 接口调用结束的回调函数（调用成功、失败都会执行） */
>       complete?: (res: TaroGeneral.CallbackResult) => void;
>       /** 接口调用失败的回调函数 */
>       fail?: (res: TaroGeneral.CallbackResult) => void;
>       /** 接口调用成功的回调函数 */
>       success?: (result: SuccessCallbackResult) => void;
>     }
>     interface SuccessCallbackResult extends TaroGeneral.CallbackResult {
>       /** 是否需要用户授权隐私协议（如果开发者没有在[mp后台-设置-服务内容声明-用户隐私保护指引]中声明隐私收集类型则会返回false；如果开发者声明了隐私收集，且用户之前同意过隐私协议则会返回false；如果开发者声明了隐私收集，且用户还没同意过则返回true；如果用户之前同意过、但后来小程序又新增了隐私收集类型也会返回true） */
>       needAuthorization: boolean;
>       /** 隐私授权协议的名称 */
>       privacyContractName: string;
>     }
>   }
>   interface TaroStatic {
>     getPrivacySetting: (option?: getPrivacySetting.Option) => void;
>   }
> }
> ```
> 
> 注意不要用 promise 的写法

使用插件了，但是没法调用onAgreePrivacyAuthorization呢

**Comment by catmiao8** [comment]
> @lupingW 已经装了，这里发不了视频，我视频发社区微信群了，这个～怎么说呢，想要回调应该是无解，只能重构或者官方调整一下插件支持回调。 `@tarojs/plugin-inject`第一时间安装了，能够使用open-type，就是无法触发`onAgreePrivacyAuthorization`回调。
我也装插件了，但是无法触发onAgreePrivacyAuthorization回调 ，请问是taro的问题吗，大佬有啥好的解决方还是嘛

**Comment by catmiao8** [comment]
> > > > > > Button openType='agreePrivacyAuthorization' onAgreePrivacyAuthorization= 这样才能同意啊
> > > > > 
> > > > > 
> > > > > 这个是需要自己搞个按钮让用户点击的，用户如果没有点击过，你调用 涉及隐私的api 或者 调用 wx.requirePrivacyAuthorize 就会触发onNeedPrivacyAuthorization
> > > > 
> > > > 
> > > > 我是搞了个按纽给让用户点击的 但不触发onAgreePrivacyAuthorization 很奇怪
> > > 
> > > 
> > > 用户点击 Button openType='agreePrivacyAuthorization' 是**同意**协议了，不会触发**需要同意**onNeedPrivacyAuthorization的。。你还是仔细看下文档先
> > 
> > 
> > 他的意思，我理解应该是使用的官方「2. 主动查询隐私授权同步状态以及展示隐私协议」这个方案，发现button的@agreeprivacyauthorization="handleAgreePrivacyAuthorization"不生效， 你说的应该是「3. 被动监听隐私接口需要用户授权事件」这个方案。
> 
> 是的 ，onAgreeprivacyauthorization="handleAgreePrivacyAuthorization" 不生效，我把版本也更新到了3.6以上了，也无效

请问你找到解决方案了嘛  我使用@tarojs/plugin-inject插件也不行  可以加个联系方式讨论下嘛 wx：miaofangdongdemao

**Comment by catmiao8** [comment]
> > > 我也是用的 React, onAgreePrivacyAuthorization 这个回调不会触发!
> > > ```
> > > <Button
> > >         openType='agreePrivacyAuthorization'
> > >         onAgreePrivacyAuthorization={() => {
> > >           console.log("click');
> > >         }}
> > >         className='privacy_modal_button'
> > >       >
> > >         同意
> > >       </Button>
> > > ```
> > 
> > 
> > 确认 taro 相关依赖和 微信基础库都是最新的
> 
> Taro相关的都是最新的了

请问你找到解决方案了吗

**Comment by catmiao8** [comment]
> > react 版本有人成功回调的, 麻烦@一下我, Taro.getPrivacySetting 这个方法是能返回`needAuthorization: true, privacyContractName: "《xxx小程序隐私保护指引》", errMsg: "getPrivacySetting:ok" ` 这些数据, 只是点击了同意之后, `onAgreePrivacyAuthorization`这个不执行, 下次进来还是继续需要授权
> 
> 3.6.6版本的成功了，用的@tarojs/plugin-inject(3.6.6)这种方法。本来想尝试最新版本的，但是报其它错误，只能回滚到3.6.6.

可以加wx讨论下吗  wx:miaofangdongdemao   我得还是不执行onAgreePrivacyAuthorization

**Comment by catmiao8** [comment]
> 

请问你用的taro相关的依赖是多少呢

**Comment by catmiao8** [comment]
> @TheKonka 那看起来没办法，不管是`@tarojs/plugin-platform-weapp`升级，还是框架升级，都会报错。
> 
> 1. `taro`框架整体升级：`babel`等各种依赖报错，项目崩溃。
> 2. `@tarojs/plugin-platform-weapp`升级，应该是涉及写法/属性报错，项目崩溃。

我得也是使用了这个插件   open-type可以正常使用  但是onAgreePrivacyAuthorization回到不触发  请问你有啥好方法吗

**Comment by lupingW** [comment]
Taro3 react版本实现 公司已经用上了
https://juejin.cn/post/7272749016755765300

**Comment by Chen-jj** [comment]
Taro v3.6.16 修复

**Comment by lilugirl** [comment]
> onAgreePrivacyAuthorization 这个回调，不生效，3.6.6，3.6.15都无效 react版本。无法手动触发resolvePrivacyAuthorization： <img alt="image" width="864" src="https://user-images.githubusercontent.com/31060569/265462329-ba9dfa36-6f87-4af3-83d4-70aa93c3a51e.png">
> 
> 同个版本库下，wx demo 是有效的： <img alt="image" width="750" src="https://user-images.githubusercontent.com/31060569/265462634-00778ba8-49dd-4ee2-8e63-333dd50217a9.png">

就想问Taro React下 怎么实现这个 this.resolvePrivacyAuthorization  ,该咋写

**Comment by TheKonka** [comment]
@lilugirl 就是个变量，可以用 useRef 保存

**Comment by yaodongyi** [comment]
> > > > 我也是用的 React, onAgreePrivacyAuthorization 这个回调不会触发!
> > > > ```
> > > > <Button
> > > >         openType='agreePrivacyAuthorization'
> > > >         onAgreePrivacyAuthorization={() => {
> > > >           console.log("click');
> > > >         }}
> > > >         className='privacy_modal_button'
> > > >       >
> > > >         同意
> > > >       </Button>
> > > > ```
> > > 
> > > 
> > > 确认 taro 相关依赖和 微信基础库都是最新的
> > 
> > 
> > Taro相关的都是最新的了
> 
> 请问你找到解决方案了吗

无解，老版本直接用click替代吧，目前升级新版本，和重构项目没区别了，反正我升不动😭

**Comment by lovepotato** [comment]
> > > > > 我也是用的 React, onAgreePrivacyAuthorization 这个回调不会触发!
> > > > > ```
> > > > > <Button
> > > > >         openType='agreePrivacyAuthorization'
> > > > >         onAgreePrivacyAuthorization={() => {
> > > > >           console.log("click');
> > > > >         }}
> > > > >         className='privacy_modal_button'
> > > > >       >
> > > > >         同意
> > > > >       </Button>
> > > > > ```
> > > > 
> > > > 
> > > > 确认 taro 相关依赖和 微信基础库都是最新的
> > > 
> > > 
> > > Taro相关的都是最新的了
> > 
> > 
> > 请问你找到解决方案了吗
> 
> 无解，老版本直接用click替代吧，目前升级新版本，和重构项目没区别了，反正我升不动😭

@yaodongyi @catmiao8  
`<Button
        className={classNameString}
        onClick={this.handleClick.bind(this)}
        style={style}
        open-type={openType}
        id="agree-btn"
        // @ts-ignore
        onAgreeprivacyauthorization={handleAgreePrivacyAuthorization}
      >
        {this.props.children}
      </Button>`
props属性传'onAgreeprivacyauthorization'，亲测有效

**Comment by predaking** [comment]
> 微信管理台更新协议就好了，和taro没关系 https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/

不懂别乱说

**Comment by diamont1001** [comment]
最近公告，不用开发者改了，微信官方自己弹窗

**Comment by biorz** [comment]
> 最近公告，不用开发者改了，微信官方自己弹窗

有链接吗

**Comment by diamont1001** [comment]
> > 最近公告，不用开发者改了，微信官方自己弹窗
> 
> 有链接吗

https://mp.weixin.qq.com/s/5Ud3AE2tXBDhOaWiQRfK_Q
https://developers.weixin.qq.com/community/develop/doc/00060ce195c480815550613ef66000
