### ISSUE TITLE
taro3 react可以支持下mdx吗

### ISSUE THREAD

**Issue by cavey1230** [NervJS/taro#14379]
### 这个特性解决了什么问题？
我们有一个markdown jsx的内容解决方案 可以让用户写出很棒的文章 但是taro3使用mdx会报错

### 这个 API 长什么样？
能够正常编译mdx

**Comment by cavey1230** [comment]
![image](https://github.com/NervJS/taro/assets/56331024/38ab7971-043b-4604-9701-53d6ebdf8464)

**Comment by Chen-jj** [comment]
社区是否有对应的 webpack-loader 进行处理？

**Comment by cavey1230** [comment]
done ，mdx使用new Function 进行转化处理 小程序禁止了eval 之类的动态进行js代码的方式 以切换其他方式

**Comment by jiuhengma** [comment]
@cavey1230 老哥 最后你们怎么解决了，我现在想在小程序里渲染md内容，想请教一下
