### ISSUE TITLE
【重要】v3.6.13 Vue2 执行生产模式构建 H5 端，部分 webComponent 组件没有被初始化。

### ISSUE THREAD

**Issue by beezen** [NervJS/taro#14382]
### 相关平台
H5

### 复现仓库
[https://github.com/beezen/taro-demo-example/tree/main/taro-3.6.13-vue2](https://github.com/beezen/taro-demo-example/tree/main/taro-3.6.13-vue2)
**浏览器版本: chrome 114.0.5735.133**
**使用框架: Vue2**

### 复现步骤
1、初始化项目 vue2，添加节点如下：
```html
<view>==button==</view>
<button>按钮</button>
<view>==text==</view>
<text>文本</text>
```

（也可以直接运行demo项目：https://github.com/beezen/taro-demo-example/tree/main/taro-3.6.13-vue2）

2、运行 npm run build:h5 指令（生产模式 mode=production）。
不显示 taro-button-core 节点，但显示了 taro-text-core 和 taro-view-core 节点。
![image](https://github.com/NervJS/taro/assets/13111739/cae29e7c-0d19-4ab2-8432-818ac00579bd)
（能显示的组件，备注中有截图说明）

猜测可能是 production 模式下，prebundle 构建模块中配置问题。
【备注】：
1、运行 npm run dev:h5 指令一切正常。
 
<img width="558" alt="image" src="https://github.com/NervJS/taro/assets/13111739/5afe6e7b-7ea3-420f-aa9e-13faea646099">

2、运行 npm run build:h5 时，初始化的 webComponent 组件列表只有 8 个。
<img width="828" alt="image" src="https://github.com/NervJS/taro/assets/13111739/9048d279-8622-4b15-98d5-cbd00713f438">

### 期望结果
Vue2 转 H5 端页面上的组件节点都能够生效。

### 实际结果
Vue2 转 H5 端页面上的组件节点只有部分生效。

### 环境信息
```
👽 Taro v3.6.13


  Taro CLI 3.6.13 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    npmPackages:
      @tarojs/cli: workspace:* => 3.6.13 
      @tarojs/components: workspace:* => 3.6.13 
      @tarojs/helper: workspace:* => 3.6.13 
      @tarojs/plugin-framework-vue2: workspace:* => 3.6.13 
      @tarojs/plugin-platform-alipay: workspace:* => 3.6.13 
      @tarojs/plugin-platform-h5: workspace:* => 3.6.13 
      @tarojs/plugin-platform-jd: workspace:* => 3.6.13 
      @tarojs/plugin-platform-qq: workspace:* => 3.6.13 
      @tarojs/plugin-platform-swan: workspace:* => 3.6.13 
      @tarojs/plugin-platform-tt: workspace:* => 3.6.13 
      @tarojs/plugin-platform-weapp: workspace:* => 3.6.13 
      @tarojs/runtime: workspace:* => 3.6.13 
      @tarojs/shared: workspace:* => 3.6.13 
      @tarojs/taro: workspace:* => 3.6.13 
      @tarojs/taro-loader: workspace:* => 3.6.13 
      @tarojs/webpack5-runner: workspace:* => 3.6.13 
      babel-preset-taro: workspace:* => 3.6.13 
      eslint-config-taro: workspace:* => 3.6.13 
```

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/pull/14368 貌似修复了

**Comment by beezen** [comment]
> #14368 貌似修复了

开发模式修复了，生产模式没有修复，上面提到的那个就是我提交的。。

后来，我在生产模式运行了一下，发现还有其他方面的问题，生产模式下的逻辑我没怎么读明白。我也用 Vue3 生产模式运行了一下，也有类似的错误。（下面是报错的截图，看看大佬们能不能看出点什么）
<img width="967" alt="image" src="https://github.com/NervJS/taro/assets/13111739/09dbf7df-37ef-431b-aed2-89063b771acd">
<img width="830" alt="image" src="https://github.com/NervJS/taro/assets/13111739/18263cc6-fb8c-45d1-a37c-3c8104e5bf25">
<img width="952" alt="image" src="https://github.com/NervJS/taro/assets/13111739/04a2ae72-b9db-4d0f-8e80-5ff71a917ae0">

**Comment by ZakaryCode** [comment]
生产环境会抖动掉未使用的组件，可能是未识别到 button 组件，可以配置 componentConfig 跳过该问题

```js
modifyWebpackChain (chain, webpack, data) {
  const config = data.componentConfig
  // 将 button 加入默认配置
  config.includes.add('button')
  // 或者设置默认加载所有组件
  config.includeAll = true
}
```

**Comment by zhouzyc** [comment]
请问修复了吗 我在项目文档中无法找到 modifyWebpackChain 的配置

**Comment by ZakaryCode** [comment]
> 请问修复了吗 我在项目文档中无法找到 modifyWebpackChain 的配置说明

这是插件提供的方法，另外仅在 webpack5 中可用，参考[文档](https://nervjs.github.io/taro-docs/docs/plugin-custom#%E7%BC%96%E8%AF%91%E8%BF%87%E7%A8%8B%E6%89%A9%E5%B1%95)

**Comment by zhouzyc** [comment]
> > 请问修复了吗 我在项目文档中无法找到 modifyWebpackChain 的配置说明
> 
> 这是插件提供的方法，另外仅在 webpack5 中可用，参考[文档](https://nervjs.github.io/taro-docs/docs/plugin-custom#%E7%BC%96%E8%AF%91%E8%BF%87%E7%A8%8B%E6%89%A9%E5%B1%95)
我在生产环境好像也遇到这个问题，https://github.com/NervJS/taro/issues/14381 请问我该如何处理

**Comment by Ttou** [comment]
之前也碰到了 h5 下组件没编译的情况，我是直接把组件全注册了一遍

> fixH5.ts

```ts
import * as components from '@tarojs/components'
import { kebabCase } from 'case-anything'
import Vue from 'vue'

Object.keys(components).forEach(key => {
  const componentName = 'taro-' + kebabCase(key)
  Vue.component(componentName, components[key])
})
```

> app.ts

```ts
import Vue from 'vue'

Vue.config.productionTip = false

if (process.env.TARO_ENV === 'h5') {
  require('./fixH5')
}

const App = {
  onShow(options) {
    console.log('app show', options)
  },
  render(h) {
    // this.$slots.default 是将要会渲染的页面
    return h('block', this.$slots.default)
  }
}

export default App
```

**Comment by zhouzyc** [comment]
> > 我在生产环境好像也遇到这个问题，#14381 请问我该如何处理
> 
> 写个插件调用这个方法呀，参考我上面写的
> 
> > 之前也碰到了 h5 下组件没编译的情况，我是直接把组件全注册了一遍
> 
> 不是同一个问题，这里其实是把 `@tarojs/components` 中未使用的组件抖动掉了

已经本地引入了一个插件安装你上面写的：
![image](https://github.com/NervJS/taro/assets/18420689/0746f419-c697-4f4f-a9a6-5f0f1b831cb8)

但是并没有生效
![image](https://github.com/NervJS/taro/assets/18420689/c6c01e74-d6ef-4d48-9f0d-6677f6e5eea7)

**Comment by ZakaryCode** [comment]
> config.includeAll = true; 如果成功应该会应该是加载全部组件

这个参数在该场景下并为支持，可以先使用 includes.add 替代

**Comment by zhouzyc** [comment]
> > config.includeAll = true; 如果成功应该会应该是加载全部组件
> 
> 重新看了下代码，这个参数在该场景下并为支持，可以先使用 includes.add 替代

includes.add   也是使用了的   config.includes.add('picker');
感觉是在修改后，没有生效，或者是需要重新return出去？
![image](https://github.com/NervJS/taro/assets/18420689/36084b17-43e7-4c3d-ac80-0e43a11473ed)
picker 没有出现
![image](https://github.com/NervJS/taro/assets/18420689/775193fa-6183-4c4b-a995-fa7095a4d516)

**Comment by ZakaryCode** [comment]
> 请问下我这样使用对吗

验证了下你的项目，确实会存在一些问题，下一个版本修复

**Comment by zhouzyc** [comment]
> > 请问下我这样使用对吗
> 
> 验证了下你的项目，确实会存在一些问题，下一个版本修复

感谢大佬，顺便在看下微信小程序，还是这个demo
项目demo地址
https://gitee.com/JS-VeryHappy/vh-mobile-demo.git

小程序在 prebundle.enable=false pnpm dev:weapp 后也是无法正常使用
出现错误：
InternalStateModule.getterFor is not a function
![image](https://github.com/NervJS/taro/assets/18420689/300e9ffb-0960-4a10-83a4-e23741d21724)

**Comment by ZakaryCode** [comment]
> 感谢大佬，顺便在看下微信小程序，还是这个demo 项目demo地址 https://gitee.com/JS-VeryHappy/vh-mobile-demo.git
> 
> 小程序在 prebundle.enable=false pnpm build:weapp 后也是无法正常使用

不同问题分开提 issue 哈，都堆在一个 issue 不好跟进，后续别人看也容易错乱

**Comment by zhouzyc** [comment]
> > 感谢大佬，顺便在看下微信小程序，还是这个demo 项目demo地址 https://gitee.com/JS-VeryHappy/vh-mobile-demo.git
> > 小程序在 prebundle.enable=false pnpm build:weapp 后也是无法正常使用
> 
> 不同问题分开提 issue 哈，都堆在一个 issue 不好跟进，后续别人看也容易错乱，你这个评论我就先折叠了

好的麻烦了 已经建好 https://github.com/NervJS/taro/issues/14381
