### ISSUE TITLE
mobx 数据发生变化但是不渲染bug

### ISSUE THREAD

**Issue by langlangbody** [NervJS/taro#1438]
[问题描述：]
当我使用Picker  mode='multiSelector' 将所有静态资源以及逻辑放在mobx 处理后render中可以获取到store值 但是在 页面中 变化的store 不会显示

 - 操作系统: [mac]
 - Taro 版本 [1.2.0-beta.11]
 - Node.js 版本 10+]
 - 报错平台 [weapp]

**Comment by neoscript99** [comment]
![image](https://user-images.githubusercontent.com/11485735/49776085-a352b280-fd35-11e8-9a97-352ac02e450d.png)
- 在render中，把store中属性先保存到本地变量:` const {meetingStore: {list}} = this.props;`
- 不要直接用props：`this.props.meetingStore.list`

**Comment by yuche** [comment]
@neoscript99 
由于 `meetingStore ` 是一个 mobX store 的实例，他的值实际上是通过 class get properties 来实现的，而这个类传入到小程序实际上会被小程序序列化掉，因此从 meetingStore 取值是无效的。

我们正在探索自己实现一套 props 通信机制，完成的时候能这样写。

**Comment by huangciyin** [comment]
@yuche 微信小程序对于 data 中的数据是需要序列化,导致丢失 class get properties. 但是对于 props 传过来的数据, 不转入 data 的情况下是没有这个问题的.  而 taro 从 props 传也会被序列化, 貌似是打入了 data?  

所以这应该是个 bug. 

期望:
跟原生小程序一样, 从 props 传数据保持原样.

主要应用场景:
例如将 mobx 的 store 通过 props 传给 子组件.

**Comment by langlangbody** [comment]
@huangciyin 我也同意你说的  期望: taro检测机制 能更加的强大

**Comment by yuche** [comment]
@huangciyin 你这个我在 https://github.com/NervJS/taro/issues/1381 回复了

**Comment by yuche** [comment]
1.3 的 props 系统已不存在这个限制
