### ISSUE TITLE
taro3.6.13 微信小程序，在prebundle.enable=false 情况下生产环境无法正常运行

### ISSUE THREAD

**Issue by zhouzyc** [NervJS/taro#14381]
### 相关平台
weapp
### 复现仓库
[https://gitee.com/JS-VeryHappy/vh-mobile-demo.git](https://gitee.com/JS-VeryHappy/vh-mobile-demo.git)
**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
taro3.6.13；
pnpm build:weapp;
小程序在 prebundle.enable=false pnpm dev:weapp 后也是无法正常使用
InternalStateModule.getterFor is not a function
![image](https://github.com/NervJS/taro/assets/18420689/300e9ffb-0960-4a10-83a4-e23741d21724)

### 期望结果
正常运行

### 实际结果
出现错误

### 环境信息
```
Taro CLI 3.6.13 environment info:
    System:
      OS: Windows 11
    Binaries:
      Node: 18.0.0 
      pnpm: 8.6.0
      npm: 8.3.1

```

**Comment by Chen-jj** [comment]
duplicate #13773
