### ISSUE TITLE
H5的Textarea，onInput的e.detail.value 获取不到值

### ISSUE THREAD

**Issue by jadebook** [NervJS/taro#1439]
**问题描述**
H5的Textarea，onInput的e.detail.value 获取不到值

**复现步骤**

**期望行为**
H5的Textarea，onInput的e.detail.value 能获取到值

**Comment by jinjinjin0731** [comment]
已修复

**Comment by jinjinjin0731** [comment]
@Herryjoeson   更新到 1.2.2。 如还有问题，请提个 issue 并贴个复现代码哈
