### ISSUE TITLE
构建h5部署到服务器后，在https域名下 不会尺寸转换 （响应式）

### ISSUE THREAD

**Issue by Noah-Neverland** [NervJS/taro#14397]
### 相关平台
H5

**浏览器版本: Chrome115**
**使用框架: React**

### 复现步骤
构建h5项目部署到https域名访问的服务器

### 期望结果
根据设备尺寸自动更换字体大小

### 实际结果
无自动更新

### 环境信息
```
👽 Taro v3.6.11


  Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.1/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11
      @tarojs/components: 3.6.11 => 3.6.11
      @tarojs/components-react: ^3.6.11 => 3.6.11
      @tarojs/helper: 3.6.11 => 3.6.11
      @tarojs/mini-runner: 3.6.11 => 3.6.11
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11
      @tarojs/plugin-html: ^3.6.11 => 3.6.11
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11
      @tarojs/react: 3.6.11 => 3.6.11
      @tarojs/router: ^3.6.11 => 3.6.11
      @tarojs/runtime: 3.6.11 => 3.6.11
      @tarojs/shared: 3.6.11 => 3.6.11
      @tarojs/taro: 3.6.11 => 3.6.11
      @tarojs/webpack-runner: 3.6.11 => 3.6.11
      babel-preset-taro: 3.6.11 => 3.6.11
      eslint-config-taro: 3.6.11 => 3.6.11
      react: ^18.2.0 => 18.2.0
```

---
### 补充信息
提示的是浏览器CSP限制策略，不可把js代码写在内联里

**Comment by lonelyWalkor** [comment]
这个是 可以通过 设置响应头 解决吧

**Comment by ZakaryCode** [comment]
> 提示的是浏览器CSP限制策略，不可把js代码写在内联里

可以自行[配置](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)

**Comment by hss-zq** [comment]
> 这个是 可以通过 设置响应头 解决吧



> > 提示的是浏览器CSP限制策略，不可把js代码写在内联里
> 
> 可以自行添加[CSP 配置](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)，或者[将目标转换单位改为 vw](https://docs.taro.zone/docs/next/size/#targetunit-string)

配置了，没啥用

**Comment by ZakaryCode** [comment]
> > 可以自行添加[CSP 配置](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)，或者[将目标转换单位改为 vw](https://docs.taro.zone/docs/next/size/#targetunit-string)
> 
> 配置了，没啥用

这里包括了两个不同配置，回复 issue 时请完整说明问题。

另外配置 1 与 taro 无关需要根据项目自行处理；配置 2 情况下若依旧存在该问题，也不会是 taro 相关的操作，顾该 issue 将被关闭。
