### ISSUE TITLE
ReactDOMServer.renderToString error

### ISSUE THREAD

**Issue by didmehh** [NervJS/taro#14401]
### 相关平台
微信小程序

**小程序基础库: 2.31.0**
**使用框架: React**

### 复现步骤
1. 新建一个小程序
2. 创建如下代码：
```js
import ReactDOMServer from 'react-dom/server';
const Custom = () => {
  const htmlString = ReactDOMServer.renderToString(<View>测试</View>);
  console.log({htmlString})
  return null
}
export default Custom
```
3. 引入上方的Custom

### 期望结果
yarn dev:weapp 可以正常无报错

### 实际结果
1. dev:weapp报错，Cannot read property 'getCurrentStack' of undefined
2. build:weapp 正常展示

#### 其他
1. 3.4.1版本报错，3.6.2版本报错，3.5.7版本正常

### 环境信息
```
Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.0/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 5.0.2
```

**Comment by didmehh** [comment]
https://github.com/facebook/react/issues/13276#issuecomment-408232369

看起来是环境问题

`config/index.js`
打印`chain.resolve.alias.store`的映射看是：
`react-dom$ => @tarojs/react`

和这个有关吗

**Comment by didmehh** [comment]
> <img alt="image" width="1036" src="https://user-images.githubusercontent.com/20672900/262211578-d4ebd5b7-0779-4ee8-b80f-a23d4b3120ea.png">
> [facebook/react#13276 (comment)](https://github.com/facebook/react/issues/13276#issuecomment-408232369)
> 
> 看起来是环境问题
> 
> 1. production环境可以，build的时候走的config/prod.js，NODE_ENV: '"production"'
> 2. development不可以，dev:weapp走的是 config/dev.js, NODE_ENV: '"development"'
> 
> 所以是不是 NODE_ENV: '"development"' 环境的时候用到的包有 production的版本的？
> 
> 然后打印看起来似乎有问题的..
> 
> ```js
> webpackChain: (chain, webpack) => {
>       console.log('webpackj is', chain.resolve.alias.store)
> },
> 
> // 运行 yarn dev:weapp
> Map(9) {
>   // ...
>   'react-dom$' => '@tarojs/react',
>   'react-reconciler$' => 'react-reconciler/cjs/react-reconciler.production.min.js',
>   'react$' => 'react/cjs/react.production.min.js',
>   'scheduler$' => 'scheduler/cjs/scheduler.production.min.js',
>   'react/jsx-runtime$' => 'react/cjs/react-jsx-runtime.production.min.js'
> }
> ```
> 
> dev用的包都是prod的看起来。

注意：此处的alias.store是基于taro@3.4.1

所以dev.js的node env改成production也可以，但是应该不是推荐的吧，dev为啥不用dev相关的包，

另外附上3.5.7的版本的alias：

```js
{
  'regenerator-runtime' => 'project/node_modules/regenerator-runtime/runtime-module.js',
  '@tarojs/runtime' => 'project/node_modules/@tarojs/runtime/dist/runtime.esm.js',
  '@tarojs/shared' => 'project/node_modules/@tarojs/shared/dist/shared.esm.js',
  '@' => 'project/src',
  '@tarojs/components$' => '@tarojs/plugin-platform-weapp/dist/components-react',
  'react-dom$' => '@tarojs/react'
}
```

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/commit/d25bb4aee3975c79c8daff065ca61d55ae29215c#diff-2800d1832c927f6936aaaa200cf174ffbb80b5fca46f1ac37ca5a3d05d93bece
3.5.7 版本正常是因为这里`config.isWatch == undefined` ,导致实际没有 setAlias
https://github.com/NervJS/taro/commit/6a98fcf5b0e6079e55fba6266d792fe0ddad781c#diff-62bcad4386ac26a8ca3f1061da8e483199ba4115b1865622dddcb5f66e097604R46
随后就修复了

**Comment by didmehh** [comment]
> [d25bb4a#diff-2800d1832c927f6936aaaa200cf174ffbb80b5fca46f1ac37ca5a3d05d93beceR20](https://github.com/NervJS/taro/commit/d25bb4aee3975c79c8daff065ca61d55ae29215c#diff-2800d1832c927f6936aaaa200cf174ffbb80b5fca46f1ac37ca5a3d05d93beceR20) 3.5.7 版本正常是因为这里`config.isWatch == undefined` ,导致实际没有 setAlias [6a98fcf#diff-2800d1832c927f6936aaaa200cf174ffbb80b5fca46f1ac37ca5a3d05d93beceL20-R21](https://github.com/NervJS/taro/commit/6a98fcf5b0e6079e55fba6266d792fe0ddad781c#diff-2800d1832c927f6936aaaa200cf174ffbb80b5fca46f1ac37ca5a3d05d93beceL20-R21) 随后就修复了
> 
> 至于为什么用 prod 的包，源码注释里有写：
> 
> https://github.com/NervJS/taro/blob/5fedb2060c6628ef7544a8c99e4e1074b1e1a7c3/packages/taro-plugin-react/src/webpack.mini.ts#L21-L22

不管哪个版本 都不支持 renderToString.

```ReactDOMServer.renderToString(<View>测试</View>);```

这个代码加上了之后，prod环境会报错。

**Comment by TheKonka** [comment]
手机上面报错是因为小程序不支持 TextEncoder

https://stackoverflow.com/questions/55868484/referenceerror-cant-find-variable-textencoder
https://github.com/hapijs/joi/issues/2141
可以考虑使用 polyfill 库解决
