### ISSUE TITLE
Taro是否能集成amis，并完成跨端部署

### ISSUE THREAD

**Issue by fengyungithub** [NervJS/taro#14405]
### 这个特性解决了什么问题？
https://github.com/baidu/amis
Taro集成amis，并完成跨端部署

### 这个 API 长什么样？
期望了解从原理上是否可行， amis生成的react组件是否能兼容Taro，是否能被编译成跨端的应用

**Comment by bigmeow** [comment]
太小众了。。。恐怕只有你自己去尝试弄了。
运行时少什么运行时环境再补什么
