### ISSUE TITLE
h5页面在小程序里没法复制页面上的元素内容？

### ISSUE THREAD

**Issue by Young1993** [NervJS/taro#1440]
同样的项目，vue打包生成的h5在小程序里面可以选择页面内标签元素的内容，但是taro打包的就没法选中页面的元素内容。特别是文章内容
如果想复制的话只能通过小程序剪贴板功能？

**Comment by jinjinjin0731** [comment]
没有明白你的意思， 小程序中只有针对 Text 标签内的文字或者通过 API ，才可以做复制选中操作，

**Comment by Young1993** [comment]
我用的就是issue，但是我的vue项目页面可以复制

**Comment by Young1993** [comment]
我现在改成了h5向小程序postmessage消息，然后调用小程序的剪贴板功能
