### ISSUE TITLE
父组件向子组件中传入函数，子组件调用this.props.xx，但父组件中的函数不执行

### ISSUE THREAD

**Issue by lansepan** [NervJS/taro#1441]
问题描述
往子组件传参，类型为函数，子组件调用 this.props.onXXX 无效。
复现步骤
[复现问题的步骤]
父组件：
` handleAreaClick = () => {
    console.log('22222222222')
  }
  render() {
    return (
      <View className='page page-index'>
        <Dropdown title={this.getAreaName()} onClick={this.handleAreaClick} />
      </View>
    )
  }`

子组件：
`  handleClick = () => {
    const { onClick } = this.props
    if (onClick) {
      console.log('111')
      onClick()
    }
  }

  render() {
    const { customStyle, className, title, open } = this.props

    return (
      <View
        className={classNames('yt-dropdown', className)}
        style={customStyle}
        onClick={this.handleClick.bind(this)}
      >
      </View>
    )
  }`

子组件调用 this.props.onClick(),无效

期望行为

子组件能成功触发父组件传参进来的函数

报错信息

无

系统信息

操作系统: macOS High Sierra
Taro 版本 1.2.0-beta.11
Node.js 版本 8.11.2
报错平台 weapp
补充信息

**Comment by luckyadam** [comment]
麻烦两个组件的文件代码贴全一点

**Comment by luckly-boy** [comment]
@lansepan 如何解决呢？我发现taro似乎不支持子组件通过props调用父组件内的setState方法来更新？

**Comment by wohaiwo** [comment]
![image](https://user-images.githubusercontent.com/7277608/57173049-b3da0580-6e5b-11e9-9593-b2e4ab887f55.png)
需要安装文档走
