### ISSUE TITLE
隐私信息授权 

### ISSUE THREAD

**Issue by Tom-Jack-Huang** [NervJS/taro#14419]
### 这个特性解决了什么问题？
微信小程序   隐私信息授权  相关 api 调用

### 这个 API 长什么样？
wx.requirePrivacyAuthorize(Object object)

wx.openPrivacyContract(Object object)

wx.onNeedPrivacyAuthorization(function listener)

wx.getPrivacySetting(Object object)

**Comment by ZakaryCode** [comment]
Duplicate of #14377

**Comment by TheKonka** [comment]
这些 api 都可以 直接 通过 `wx.` 调用，后续 taro 会完善支持 `Taro.` 调用

**Comment by Zeppo241** [comment]
> 这些 api 都可以 直接 通过 `wx.` 调用，后续 taro 会完善支持 `Taro.` 调用

在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined

**Comment by TheKonka** [comment]
> > 这些 api 都可以 直接 通过 `wx.` 调用，后续 taro 会完善支持 `Taro.` 调用
> 
> 在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined

__usePrivacyCheck__报错应该是 ts 报错，不影响运行

调用api 不需要看返回值吧，把 回调函数传进去就行

```ts
if (wx.onNeedPrivacyAuthorization && wx.requirePrivacyAuthorize && wx.getPrivacySetting) {
	wx.getPrivacySetting({
		success: (res: any) => {
			console.log(res);
			if (res.needAuthorization) {
				setPrivacyName(res.privacyContractName);
				setShowAgree.setTrue();
			} else {
				onAgree?.();
			}
		}
	});
	wx.onNeedPrivacyAuthorization((resolve: any) => {
		console.log('onNeedPrivacyAuthorization', resolve);
		setShowAgree.setTrue();
		resolveFn.current = resolve;
	});
	wx.requirePrivacyAuthorize({
		success: (res: any) => {
			console.log('requirePrivacyAuthorizesuccess', res);
			setShowAgree.setFalse();
		},
		fail: (res: any) => {
			console.log('requirePrivacyAuthorizefail', res);
		}
	});
}
```

**Comment by Zeppo241** [comment]
> > > 这些 api 都可以 直接 通过 `wx.` 调用，后续 taro 会完善支持 `Taro.` 调用
> > 
> > 
> > 在app.config.ts里配置__usePrivacyCheck__: true会报错，调用requirePrivacyAuthorize，getPrivacySetting，openPrivacyContract，onNeedPrivacyAuthorization这几个api返回也是undefined
> 
> __usePrivacyCheck__报错应该是 ts 报错，不影响运行
> 
> 调用api 不需要看返回值吧，把 回调函数传进去就行
> 
> ```ts
> if (wx.onNeedPrivacyAuthorization && wx.requirePrivacyAuthorize && wx.getPrivacySetting) {
> 	wx.getPrivacySetting({
> 		success: (res: any) => {
> 			console.log(res);
> 			if (res.needAuthorization) {
> 				setPrivacyName(res.privacyContractName);
> 				setShowAgree.setTrue();
> 			} else {
> 				onAgree?.();
> 			}
> 		}
> 	});
> 	wx.onNeedPrivacyAuthorization((resolve: any) => {
> 		console.log('onNeedPrivacyAuthorization', resolve);
> 		setShowAgree.setTrue();
> 		resolveFn.current = resolve;
> 	});
> 	wx.requirePrivacyAuthorize({
> 		success: (res: any) => {
> 			console.log('requirePrivacyAuthorizesuccess', res);
> 			setShowAgree.setFalse();
> 		},
> 		fail: (res: any) => {
> 			console.log('requirePrivacyAuthorizefail', res);
> 		}
> 	});
> }
> ```

是的，这样有用，感谢

**Comment by gyt95** [comment]
真机这几个API是undefined，什么原因？直接控制台打印wx.getPrivacySetting都是undefined。开发者工具上就没问题。

**Comment by TheKonka** [comment]
> 真机这几个API是undefined，什么原因？直接控制台打印wx.getPrivacySetting都是undefined。开发者工具上就没问题。代码里其实也报红线：找不到名称“wx”。

是不是手机上的微信版本比较低？ 基础库还没更新，可以用 if(wx.getPrivacySetting) 跳过不支持的。
找不到名称“wx”是 ts 报错，不影响运行，也可以 在 global.d.ts里面加上 declare const wx: any;  这样就不报错了

**Comment by gyt95** [comment]
> > 真机这几个API是undefined，什么原因？直接控制台打印wx.getPrivacySetting都是undefined。开发者工具上就没问题。代码里其实也报红线：找不到名称“wx”。
> 
> 是不是手机上的微信版本比较低？ 基础库还没更新，可以用 if(wx.getPrivacySetting) 跳过不支持的。 找不到名称“wx”是 ts 报错，不影响运行，也可以 在 global.d.ts里面加上 declare const wx: any; 这样就不报错了

ts报错的解决了。但是undefined的问题确实不行。然后我试了下https://github.com/hsuna/taro-privacy-popup这个项目，真机模式下也是不行。API 为 undefined 。如果你们不是 undefined 那就真的是微信版本问题了。我手机微信版本 8.0.32 也不算太低吧，而且就算我版本更新上去，那有的用户版本不够会如何？不就无法获取信息？

**Comment by TheKonka** [comment]
你用真机调试的？真机调试效果跟实际会不一样，你用预览看看

**Comment by TheKonka** [comment]
> > 你用真机调试的？真机调试效果跟实际会不一样，你用预览看看
> 
> 也一样，undefined。晚点补图

不应该啊，app.config 里面加上 __usePrivacyCheck__ 了吗？

**Comment by gyt95** [comment]
> > > 你用真机调试的？真机调试效果跟实际会不一样，你用预览看看
> > 
> > 
> > 也一样，undefined。晚点补图
> 
> 不应该啊，app.config 里面加上 `__usePrivacyCheck__ `了吗？

![1693811592636](https://github.com/NervJS/taro/assets/23090676/d11e5049-ff95-4455-b195-970b214c4dc3)

有的。不然的话，开发者工具里面是无效的。现在是开发者工具里有效，但预览和真机都undefined。

![1693811644281](https://github.com/NervJS/taro/assets/23090676/ee28c3f1-029d-4255-8720-296f79e7abe8)

![1693811656670](https://github.com/NervJS/taro/assets/23090676/8985510f-6200-4ad9-9c55-989d0b989401)

**Comment by gyt95** [comment]
> > > 你用真机调试的？真机调试效果跟实际会不一样，你用预览看看
> > 
> > 
> > 也一样，undefined。晚点补图
> 
> 不应该啊，app.config 里面加上 `__usePrivacyCheck__ `了吗？

破案了。还真是微信版本问题，必须8.0.40才能用上基础库3.0.0
https://developers.weixin.qq.com/miniprogram/dev/framework/client-lib/version.html

那这样低版本用户不就用不了小程序。。

**Comment by TheKonka** [comment]
@gyt95  应该不至于用不了，如果没有那些新的api，那么对 隐私接口的调用也不需要用户同意，还是跟以前一样

**Comment by gyt95** [comment]
幸好！我刚试了，只要外层加个判断，wx.canIUse('onNeedPrivacyAuthorization')是true就显示隐私协议组件，false就照以前那样，一样可以授权手机号的。

**Comment by gyt95** [comment]
> @gyt95 应该不至于用不了，如果基础库里面没有那些新的api，那么对 隐私接口的调用也不需要用户同意，还是跟以前一样

嗯嗯对的。
