### ISSUE TITLE
原生组件都不能引用了，报路径错误

### ISSUE THREAD

**Issue by jonahfang** [NervJS/taro#14420]
### 相关平台
微信小程序

**小程序基础库: 2.30.3**
**使用框架: React**

### 复现步骤
package.json中的tarojs版本改为3.6.12, 编译整个项目后，用微信开发者工具调试，报告原生组件路径无法找到。用3.6.11版本都是好的。

### 期望结果
原生组件能找到并编译.

### 实际结果
原生组件未找到。

### 环境信息
```
👽 Taro v3.6.14


  Taro CLI 3.6.14 environment info:
    System:
      OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.12 => 3.6.12
      @tarojs/components: 3.6.12 => 3.6.12
      @tarojs/helper: 3.6.12 => 3.6.12
      @tarojs/mini-runner: 3.6.12 => 3.6.12
      @tarojs/plugin-framework-react: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-alipay: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-h5: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-jd: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-qq: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-swan: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-tt: 3.6.12 => 3.6.12
      @tarojs/plugin-platform-weapp: 3.6.12 => 3.6.12
      @tarojs/react: 3.6.12 => 3.6.12
      @tarojs/runtime: 3.6.12 => 3.6.12
      @tarojs/shared: 3.6.12 => 3.6.12
      @tarojs/taro: 3.6.12 => 3.6.12
      @tarojs/webpack-runner: 3.6.12 => 3.6.12
      babel-preset-taro: 3.6.12 => 3.6.12
      eslint-config-taro: 3.6.12 => 3.6.12
      react: ^18.0.0 => 18.2.0
```

**Comment by jonahfang** [comment]
3.6.13, 3.6.14 两个版本也 测试了，都有这个问题。

**Comment by TheKonka** [comment]
关闭开发者工具重新打开看看？

**Comment by jonahfang** [comment]
试过，没用的

**Comment by xuanzebin** [comment]
麻烦提供一个复现问题的 demo，方便排查一下

**Comment by jonahfang** [comment]
demo如下:

**Comment by jonahfang** [comment]
上述demo项目编译后, 打开开发者工具看到:
![error](https://github.com/NervJS/taro/assets/16301509/bda0a635-8e61-40eb-88df-5c16f5b84add)
如果改为3.6.11, 编译后，看到是这样:
![ok](https://github.com/NervJS/taro/assets/16301509/7c027a3e-1984-48c9-af22-506a862ed89e)

**Comment by Tom-Jack-Huang** [comment]
同样遇到了 

Component is not found in path "subPackageLife/components/mp-html/index" (using by "subPackageLife/pages/messageFlowWorksDetail/index")

3.6.11 是好的

**Comment by xuanzebin** [comment]
> demo如下: wget http://121.42.187.196:8000/mywxappnew-demo.gz (此链接已失效) 操作步骤: 1.解压。 2.根文件夹运行 dkrun 3.docker内, cd /app 4.执行 sh w 编译。 5.在开发者工具中打开项目。
> 
> @xuanzebin

没能打开你的链接，能否将 demo 上传到 github 仓库

**Comment by jonahfang** [comment]
@xuanzebin 链接已恢复！

**Comment by xuanzebin** [comment]
已定位到问题，目前该问题存在于 webpack4 中，可以升级到 webpack5 使用，或者下周发版修复 @jonahfang @Tom-Jack-Huang

**Comment by cat-kun** [comment]
> 已定位到问题，目前该问题存在于 webpack4 中，可以升级到 webpack5 使用，或者下周发版修复 @jonahfang @Tom-Jack-Huang

"webpack": "^5.73.0" 问题依旧

**Comment by peggyannie** [comment]
环境：taro3.6.15、小程序基础库3.0.1
问题：原生页面wxml编译后，内容全没了

demo:

index.wxml文件内容：
```
<view style="text-align: center;">页面Test</view>
```

编译后在dist看到的index.wxml文件内容：
```
<!--wxmlTest/index.wxml-->
<text>wxmlTest/index.wxml</text>
```
