### ISSUE TITLE
H5的Swiper ， 当同一页面使用2个Swiper的时候，会出现问题

### ISSUE THREAD

**Issue by jadebook** [NervJS/taro#1442]
**问题描述**
H5的Swiper ， 当同一页面使用2个Swiper的时候，会出现问题
1.第一个Swiper显示指示点，第二个Swiper不显示指示点，然后结果是第一个Swiper显示的是二个Swiper的指示点。
2. IOS下面第一个Swiper不自动轮播了，而且图片未铺满

**复现步骤**

**期望行为**
一个页面用2个Swiper的时候，指示点正常显示，2个都会各自的自动轮播，而且IOS环境的Swiper里面的图片会铺满

**Comment by Leechael** [comment]
说一下用的 Taro 版本，理论上这个 PR#1283 已经修复这个问题的了，起码我这边是没有这个问题的……

**Comment by jinjinjin0731** [comment]
贴一下版本，我这边也是没有复现你说的情况
