### ISSUE TITLE
使用js如何能将jsx组件挂载到虚拟dom上

### ISSUE THREAD

**Issue by lupingW** [NervJS/taro#14439]
### 相关平台
微信小程序

### 复现仓库
[git@gitee.com:wangluping/react-app.git](git@gitee.com:wangluping/react-app.git)
**小程序基础库: 3.0.0**
**使用框架: React**

### 复现步骤
1. taro小程序在onReady中使用document.getElementById(router.$taroPath)获取到了页面根节点的虚拟dom
2. 有一个jsx组件
需求:
想把这个jsx组件渲染到页面根节点的虚拟dom下, 应该如何操作

### 期望结果
想把这个jsx组件渲染到页面根节点的虚拟dom下, 应该如何操作

### 实际结果
不知道怎么挂载

### 环境信息
```
👽 Taro v3.4.6


  Taro CLI 3.4.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.5 - D:\node\node.EXE
      npm: 9.7.1 - D:\node\npm.CMD
```

**Comment by xuanzebin** [comment]
可以参考使用[React Portals](https://react.dev/reference/react-dom/createPortal)

**Comment by lupingW** [comment]
> 可以参考使用[React Portals](https://react.dev/reference/react-dom/createPortal)

他这个要把createPortals放在父组件的jsx中才可以
