### ISSUE TITLE
taro react typescript默认模版微信开发者工具热更新无法工作

### ISSUE THREAD

**Issue by tokisakiyuu** [NervJS/taro#14454]
### 相关平台
微信小程序

**小程序基础库: 3.0.1**
**使用框架: React**

## 创建项目

```
taro init e-commerce-miniapp
```

创建参数如下

```
Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 多平台电商小程序
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 pnpm
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 默认模板
```

## 首次构建

```
pnpm run build:weapp
```

习惯性的验证构建过程不会出错

## 开发构建

```
pnpm run dev:weapp
```

webpack看起来一切正常，正在监听文件变动

## 修改组件

`src/page/index/index.tsx`

```
  ...
  return (
    <View className='index'>
      <Text>Hello world! 123</Text>
    </View>
  ...
```

### 期望结果
在tsx文件中修改保存组件的文本节点后，webpack开始增量编译，写入磁盘，微信开发者工具监听到文件变化，执行热更新。

### 实际结果
在tsx文件中修改保存组件的文本节点后，webpack开始增量编译了，但是可能没有写入磁盘？所以微信开发者工具没有任何动作。

### 环境信息
```
👽 Taro v3.6.15


  Taro CLI 3.6.15 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.15 => 3.6.15
      @tarojs/components: 3.6.15 => 3.6.15
      @tarojs/helper: 3.6.15 => 3.6.15
      @tarojs/plugin-framework-react: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-alipay: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-h5: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-jd: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-qq: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-swan: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-tt: 3.6.15 => 3.6.15
      @tarojs/plugin-platform-weapp: 3.6.15 => 3.6.15
      @tarojs/react: 3.6.15 => 3.6.15
      @tarojs/runtime: 3.6.15 => 3.6.15
      @tarojs/shared: 3.6.15 => 3.6.15
      @tarojs/taro: 3.6.15 => 3.6.15
      @tarojs/taro-loader: 3.6.15 => 3.6.15
      @tarojs/webpack5-runner: 3.6.15 => 3.6.15
      babel-preset-taro: 3.6.15 => 3.6.15
      eslint-config-taro: 3.6.15 => 3.6.15
      react: ^18.0.0 => 18.0.0
```

---
### 补充信息
观望 taro 项目几年了，没想到都2023年了，你默认模版热更新还是残的。（创建默认模版下来直接 `pnpm run dev:weapp` ，没有任何多余的操作...）

**Comment by Innei** [comment]
我也遇到这个问题。

纠正一下，有一点描述的不对。

webpack 写入磁盘了，微信 devtool 也监听到了同时也 complie 了，但是微信编译的产物没生效
![CleanShot 2023-10-09 at 7  59 10@2x](https://github.com/NervJS/taro/assets/41265413/5267b75d-bf0d-462e-8ddf-16813f4fa77a)

**Comment by Innei** [comment]
需要手动点一下微信开发工具的 Complie 
![CleanShot 2023-10-09 at 7  59 42@2x](https://github.com/NervJS/taro/assets/41265413/5285cf99-43f9-4fb5-8288-54449092e61e)

很有可能是 微信开发工具的 bug

**Comment by tokisakiyuu** [comment]
> 需要手动点一下微信开发工具的 Complie ![CleanShot 2023-10-09 at 7  59 42@2x](https://user-images.githubusercontent.com/41265413/273577937-5285cf99-43f9-4fb5-8288-54449092e61e.png)
> 
> 很有可能是 微信开发工具的 bug

是不是微信开发者工具的bug我还是持怀疑的，因为发这个issue的一年前，一次技术调研的时候也是一模一样的问题，所以那时就没选taro，隔壁某框架这方面体验还不错，所以我觉得这个问题可能是有解的，只是taro这么久以来没有安排上

**Comment by risu-p** [comment]
2023年11月了，有解吗？大家都不需要热更新的？

**Comment by raver** [comment]
遇到同样的问题，同困惑。

**Comment by boiboif** [comment]
wepack5热更新一直没解决，wepack4就没问题

**Comment by Chen-jj** [comment]
duplicate #13876

**Comment by MonshinYu** [comment]
同问

**Comment by Linxiaoxxx** [comment]
目前用的是 Taro 3.6.25+ React 18 + Typescript，关闭微信小程序的热重载就是有用的
![image](https://github.com/NervJS/taro/assets/28133060/22bb5422-9f48-40c1-8e97-fb80b7475e96)

**Comment by djx0716** [comment]
> 目前用的是 Taro 3.6.25+ React 18 + Typescript，关闭微信小程序的热重载就是有用的 ![image](https://private-user-images.githubusercontent.com/28133060/321503087-22bb5422-9f48-40c1-8e97-fb80b7475e96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzA1NjMsIm5iZiI6MTcxODI3MDI2MywicGF0aCI6Ii8yODEzMzA2MC8zMjE1MDMwODctMjJiYjU0MjItOWY0OC00MGMxLThlOTctZmI4MGI3NDc1ZTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA5MTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNmQ3OWE1NTQ2YzcwYzk2OGM4NGExNDM2NTk2NDJlMjFiZDZjMmY4OTJmN2Q5ZjMxNDUyMjk2Yjc2YjFiN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OqY9BbwVhxL660JMI4fcesBwo1KYE4N1XWj-UW9z-6s)

昨天拉的taro ui模板，确实关掉微信开发者工具热更新就可以了。
![image](https://github.com/NervJS/taro/assets/49354879/70fd2203-92ae-43a1-9ab2-e0732ac7ab02)
