### ISSUE TITLE
VirtualList在子项高度不固定时的使用问题，unlimitedSize不生效

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#14461]
### 相关平台
支付宝小程序

**小程序基础库: 1**
**使用框架: React**

### 复现步骤
```
// @ts-ignore
import {Button, Input, ScrollView, Text, View} from "@tarojs/components";
import React, {memo, useCallback, useEffect, useRef, useState} from "react";
import Taro, {Current, useDidShow, usePullDownRefresh, useReachBottom, useReady, usePageScroll, useUnload} from "@tarojs/taro";
import {Component} from "react";
import VirtualList from '@tarojs/components/virtual-list'

const Row = React.memo(({id, index, data}) => {
    return (
        <View id={id}
              style={{
                  display: "flex", flexDirection: "row",
                  height: index % 2 == 0 ? 200 : 20,
                  marginTop: 40,
                  backgroundColor: index % 2 == 0 ? 'yellow' : 'green'
              }}>
            {/*<View className=''></View>*/}
            Row {index} : {data[index]}
        </View>
    )
})

function buildData(offset = 0) {
    return Array(15)
        .fill(0)
        .map((_, i) => i   offset)
}

export default class Index extends Component {
    state = {
        data: buildData(0),
    }

    render() {
        const {data} = this.state
        const dataLen = data.length
        const itemSize = 100
        // @ts-ignore
        return (
            <VirtualList
                className="List"
                height={500}
                item={Row}
                itemData={data}
                itemCount={dataLen}
                itemSize={itemSize}
                unlimitedSize
                // itemSize={(index,item)=>{
                //     console.log('index:',index,'  item:',item)
                //     return 100
                // }}

                overscanCount={3}
                width="100%"

            />
        )
    }
}
```

### 期望结果
设置unlimitedSize之后，黄色高度200，绿色高度20

### 实际结果
黄绿色高度与期望结果不符，且开启unlimitedSize后，itemSize传入函数，不执行打印

![image](https://github.com/NervJS/taro/assets/36951996/19063c21-f68b-447d-88f2-50077b64a5ad)

### 环境信息
```
Taro CLI 3.6.11 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 16.9.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - D:\nodejs\yarn.CMD
      npm: 7.21.1 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11
      @tarojs/components: 3.6.11 => 3.6.11
      @tarojs/helper: 3.6.11 => 3.6.11
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11
      @tarojs/plugin-html: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11
      @tarojs/plugin-react-devtools: 3.6.11 => 3.6.11
      @tarojs/react: 3.6.11 => 3.6.11
      @tarojs/rn-runner: 3.6.11 => 3.6.11
      @tarojs/rn-supporter: 3.6.11 => 3.6.11
      @tarojs/runtime: 3.6.11 => 3.6.11
      @tarojs/runtime-rn: 3.6.11 => 3.6.11
      @tarojs/shared: 3.6.11 => 3.6.11
      @tarojs/taro: 3.6.11 => 3.6.11
      @tarojs/taro-rn: 3.6.11 => 3.6.11
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11
      babel-preset-taro: 3.6.11 => 3.6.11
      expo: ~47.0.3 => 47.0.14
      react: ^18.1.0 => 18.2.0
      react-native: 0.70.7 => 0.70.7

```

**Comment by ZakaryCode** [comment]
![image](https://github.com/NervJS/taro/assets/24262362/8c6d179f-8a6f-4763-a59a-a18ad4d2698e)

**Comment by fanlvwen** [comment]
demo中想要实现黄色200，绿色20，应该怎么写呢？下面这个代码也实现不了。
再请教一个问题，itemSize传入函数，return的高度，转成小程序之后，单位是px，我把黄色和绿色的高度改成用css写：`height:200px`，这样最终会转化为rem，这中间就会产生偏差，导致虚拟列表实际计算出来的高度（px）并不等于我想要实现的（rem），这种怎么处理呢？

` <VirtualList
                className="List"
                height={500}
                item={Row}
                itemData={data}
                itemCount={dataLen}
               // itemSize={itemSize}
                //unlimitedSize
                 itemSize={(index,item)=>{
                    return  index % 2 == 0 ? 200 : 20
                 }}

                overscanCount={3}
                width="100%"

            />`

**Comment by ZakaryCode** [comment]
> demo中想要实现黄色200，绿色20，应该怎么写呢？下面这个代码也实现不了。
> 
> 再请教一个问题，itemSize传入函数，return的高度，转成小程序之后，单位是px，我把黄色和绿色的高度改成用css写：`height:200px`，这样最终会转化为rem，这中间就会产生偏差，导致虚拟列表实际计算出来的高度（px）并不等于我想要实现的（rem），这种怎么处理呢？

描述有点混乱，大致应该两个问题，一则实现按照预设自定义高度展示节点；二是希望实现多端统一子节点实际高度？

第一个问题，按照所述代码是没有问题的，但是子节点代码并未提供，猜测最后与预期有所差异应当是提供的子节点组件实际并未填满子节点，可自行检查相关代码；

第二个问题，希望锁死高度为 200px 也有多个实现方案，一则可以在 JSX 组件中声明，二来在 CSS 中也可以写作 `200PX` 避免 postcss 插件转换尺寸

**Comment by fanlvwen** [comment]
> > demo中想要实现黄色200，绿色20，应该怎么写呢？下面这个代码也实现不了。
> > 再请教一个问题，itemSize传入函数，return的高度，转成小程序之后，单位是px，我把黄色和绿色的高度改成用css写：`height:200px`，这样最终会转化为rem，这中间就会产生偏差，导致虚拟列表实际计算出来的高度（px）并不等于我想要实现的（rem），这种怎么处理呢？
> 
> 描述有点混乱，大致应该两个问题，一则实现按照预设自定义高度展示节点；二是希望实现多端统一子节点实际高度？
> 
> 第一个问题，按照所述代码是没有问题的，但是子节点代码并未提供，猜测最后与预期有所差异应当是提供的子节点组件实际并未填满子节点，可自行检查相关代码；
> 
> 第二个问题，希望锁死高度为 200px 也有多个实现方案，一则可以在 JSX 组件中声明，二来在 CSS 中也可以写作 `200PX` 避免 postcss 插件转换尺寸

暂时就看第一个问题哈，代码就是同一份，看issue中有子节点的代码；代码的内容就是itemSize传入函数（偶数节点高度设为200，奇数高度20），子节点也是相应动态设置了黄色偶节点200，绿色奇数节点20，结果如上面的截图所示，黄色高度不准确

**Comment by fanlvwen** [comment]
排查发现应该是子节点marginTop的原因，去掉之后表现正常。

**Comment by fanlvwen** [comment]
然后还是这份代码，高度都是在jsx中定义的，编译之后单位是px，
![image](https://github.com/NervJS/taro/assets/36951996/980b87b1-fa0e-45b8-a8ee-124d301b9829)

实际场景中由于子节点内容比较复杂，所以样式都是定义在css中，如果要保持子节点在jsx中定义的高度（itemSize={200}），就只能把css中单位改为`PX`对吗？

有什么方法能让itemSize这个值转成`rem`呢？@ZakaryCode

**Comment by fanlvwen** [comment]
因为用PX的话，转换之后，安卓app和支付宝小程序样式差异不大，ios上支付宝小程序有很大差异，跟ios的系统版本有关联，所以用PX比较麻烦，如果itemSize能转成rem，就没这种问题了

**Comment by ZakaryCode** [comment]
> 实际场景中由于子节点内容比较复杂，所以样式都是定义在css中，如果要保持子节点在jsx中定义的高度（itemSize={200}），就只能把css中单位改为`PX`对吗？

如果通过 itemSize 设置高度，实际不需要 CSS 中额外再配置高度

> 有什么方法能让itemSize这个值转成`rem`呢？

没有，这会导致计算错误

**Comment by yangyuedev** [comment]
为什么 itemSize 不使用（或者说没转换成） rpx？
