### ISSUE TITLE
有计划更新RN 0.71后的版本么,什么时候可以推出稳定版?

### ISSUE THREAD

**Issue by OrrinHatch** [NervJS/taro#14464]
### 这个特性解决了什么问题？
想使用RN 0.71后的特性

### 这个 API 长什么样？
有升级rn的教程

**Comment by yhostc** [comment]
同样期待升级到v0.72.4稳定版，或者升级教程？

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/discussions/14128

**Comment by zhiqingchen** [comment]
每个rn版本的升级，会有对应discuss

**Comment by zhiqingchen** [comment]
4.x 会提供 0.73 版本的 rn
