### ISSUE TITLE
切换 tabBar 的情况下 h5端 componentDidMount 重复执行此生命周期

### ISSUE THREAD

**Issue by lvbaiying** [NervJS/taro#1446]
------------------------

**问题描述**
切换 tabBar 的情况下 h5端 componentDidMount 重复执行此生命周期
h5侧下 componentDidShow 与 componentDidHide 内的生命周期 在所有的 tabBar 页都会触发

**复现步骤**
[复现问题的步骤]
1. 创建两个tabBar 页
2. 其中一个页内 componentDidMount 内可以console打印
3. 反复切换两个 tabBar 页
4. 发现 console 存在的那个 tabBar 的componentDidMount 执行次数为 点击tabBar页次数+1次

**期望行为**
与原本的 componentDidMount 一致

**补充信息**
感觉好像类似于是重复创建了 componentDidMount 但是没有在 切换走tabBar的时候卸载掉的感觉

版本 v1.2.0-beta.11

**Comment by Qiu800820** [comment]
@lvbaiying  你可以先看看这个issues #1124
