### ISSUE TITLE
 Error: Fatal: unexpected loadSdkSubPackage case

### ISSUE THREAD

**Issue by yaodongyi** [NervJS/taro#14475]
### 相关平台
微信小程序

**小程序基础库: 3.0.0**
**使用框架: React**

### 复现步骤
新版本库报错，我看到之前的issues是还原到旧的版本库，确实可以，但是新的小程序功能只在新的版本库生效，而且agreePrivacyAuthorization问题只能使用新的版本库，这不是直接陷入恶性新循环了吗，无法解决吗这个问题？

如果无法解决，那么多老用户如何自处😭

### 期望结果
能够正常实现

### 实际结果
 Error: Fatal: unexpected loadSdkSubPackage case
window属性报错

### 环境信息
```
👽 Taro v3.4.1

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.3 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - /opt/homebrew/opt/node@14/bin/npm
    npmPackages:
      @tarojs/components: 3.2.1 => 3.2.1 
      @tarojs/mini-runner: 3.2.1 => 3.2.1 
      @tarojs/react: 3.2.1 => 3.2.1 
      @tarojs/runtime: 3.2.1 => 3.2.1 
      @tarojs/taro: 3.2.1 => 3.2.1 
      @tarojs/webpack-runner: 3.2.1 => 3.2.1 
      babel-preset-taro: 3.2.1 => 3.2.1 
      eslint-config-taro: 3.2.1 => 3.2.1 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 4.9.5
```

**Comment by yaodongyi** [comment]
很紧急哈，不然估计超级大量使用taro的老用户，10号之后全军覆没

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/14377#issuecomment-1695377442
如果因为各种原因不升级到最新版本可以试下这个

**Comment by yaodongyi** [comment]
这个，应该是两个问题。建议你们看看这个：https://github.com/NervJS/taro/issues/13652
1. Error: Fatal: unexpected loadSdkSubPackage case，这个报错是框架问题。
2. 恰好碰上小程序政策，必须升级版本库

**Comment by yaodongyi** [comment]
必须升级微信版本库，导致一升级，框架自身问题出现。
<img width="908" alt="image" src="https://github.com/NervJS/taro/assets/31060569/e42e0756-2331-4d7f-82df-eacbb81eff76">
<img width="633" alt="image" src="https://github.com/NervJS/taro/assets/31060569/08ba2c8f-d59d-463d-a11a-c7fc7c763996">

**Comment by yaodongyi** [comment]
安装完 @tarojs/plugin-inject，就更有意思了
<img width="815" alt="image" src="https://github.com/NervJS/taro/assets/31060569/519f8c51-97d5-4fbf-98a0-0ab8b8c727a0">

**Comment by yaodongyi** [comment]
解决方案：升级开发者工具

**Comment by yaodongyi** [comment]
使用 `@tarojs/plugin-inject`出现新问题：
 
<img width="715" alt="image" src="https://github.com/NervJS/taro/assets/31060569/4b736484-0b27-4671-9a46-32711cb3812b">

**Comment by xuanzebin** [comment]
> 这个，应该是两个问题。建议你们看看这个：#13652
> 
> 1. Error: Fatal: unexpected loadSdkSubPackage case，这个报错是框架问题。
> 2. 恰好碰上小程序政策，必须升级版本库

- `Error: Fatal: unexpected loadSdkSubPackage case` 这个报错已在五个月前的版本进行了容错兜底，升级到最新版本的 Taro 后将不会出现这个问题
- 小程序隐私政策的问题可以参考这位老哥的做法 https://github.com/NervJS/taro/issues/14377#issuecomment-1695377442 下一个版本会将相关的 api 类型补充上去，后续直接使用即可
- tarojs/plugin-inject 报错的问题，提供的信息不够，最好附上一个 demo 链接，方便排查具体是什么原因

**Comment by Chen-jj** [comment]
Taro v3.6.16 修复
