### ISSUE TITLE
IOS下有概率变成两列页面同时存在

### ISSUE THREAD

**Issue by PL-FE** [NervJS/taro#14478]
### 相关平台
H5

**浏览器版本: 钉钉H5微应用：chrome100**
**使用框架: React**

### 复现步骤
概率出现，多发生与路由变化
Taro.navigateTo

### 期望结果
每次只显示一个页面

### 实际结果
同时存在2个页面，并且是两列。页面2主页，页面1是子页
以下是示意图，脱敏
![image](https://github.com/NervJS/taro/assets/41770773/2835c582-ea01-4c49-92e9-d8bbcc11753a)
实际的dom节点
![lQDPJxfRGcCHgmzNBQDNA2CwkKC_0yYBOVUE6YQcSAAyAA_864_1280](https://github.com/NervJS/taro/assets/41770773/4095f731-e7b5-4645-ae38-c964fc3b52c7)

### 环境信息
```
 Taro CLI 3.6.13 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.13 => 3.6.13 
      @tarojs/components: 3.6.13 => 3.6.13 
      @tarojs/helper: 3.6.13 => 3.6.13
      @tarojs/plugin-framework-react: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-h5: ^3.6.13 => 3.6.13
      @tarojs/react: 3.6.13 => 3.6.13
      @tarojs/runtime: 3.6.13 => 3.6.13
      @tarojs/shared: 3.6.13 => 3.6.13
      @tarojs/taro: 3.6.13 => 3.6.13
      @tarojs/webpack5-runner: 3.6.13 => 3.6.13
      babel-preset-taro: 3.6.13 => 3.6.13
      eslint-config-taro: 3.6.13 => 3.6.13
      react: ^17.0.0 => 17.0.2
      react-native: 0.65.0 => 0.65.0
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.7
```

**Comment by ZakaryCode** [comment]
> 概率出现，多发生与路由变化
> Taro.navigateTo

详细是在什么操作情况下，比如用户使用某一类操作或浏览器触发xxx事件时（希望可以附上错误复现的视频与 DEMO

**Comment by PL-FE** [comment]
感谢回复。由于是偶现，当前已知是ios14.2，钉钉H5微应用中的iframe。测试操作了路由跳转。Taro.navigateTo。现在正在努力寻找规律。
