### ISSUE TITLE
taro v3.6.8依旧不能正常使用PageMeta组建

### ISSUE THREAD

**Issue by maomeiqi** [NervJS/taro#14471]
### 相关平台
微信小程序

**小程序基础库: 3.0.0**
**使用框架: React**

### 复现步骤
如下使用，PageMeta无效

import {  PageMeta } from "@tarojs/components";
return (
    <PageMeta
      pageStyle="overflow: hidden;"
      backgroundColor="#f00000"
      backgroundColorTop="#f00000"
      backgroundTextStyle="dark"
    >
       <View>
          .....
      </View>
    </PageMeta>
)

### 期望结果
使用@tarojs/components引用PageMeta能正常使用

### 实际结果
提示错误：
[渲染层错误] [Component] <page-meta>: 只能是页面内的第一个节点，且不能被 wx:if 或 wx:for 动态变更

并且设置相关属性无效
pageStyle={"overflow: hidden;"}
backgroundColor="#f00000"
backgroundColorTop="#f00000"
backgroundTextStyle="dark"

### 环境信息
```
 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/mini-runner: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8 
      @tarojs/react: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 
      react: ^17.0.0 => 17.0.2 
```

**Comment by GetWebHB** [comment]
+1

**Comment by Chen-jj** [comment]
#6092
