### ISSUE TITLE
微信小程序onClick事件参数的prototype失效

### ISSUE THREAD

**Issue by wqj97** [NervJS/taro#1448]
**问题描述**
onClick事件中的参数原型失效, 没有传递下去
我看到源码中有一个processEvent, 会从dataset中取出事件的参数
可是有的时候一些参数可能是一个类. 这一块请问有没有解决方案
**复现步骤**
1. render中的onClick绑定一个事件参数
2. 在小程序开发工具中触发该事件
3. 绑定的事件参数只保留了Property, Prototype丢失
```js
// item是一个类, 类下除了一些property之外还有一些方法
// jsx
<AtIcon onClick={this.handleIncrease.bind(this, item)} />
// js
private handleIncrease (item: ItemData) {
 item.increase(1);
}
```

**期望行为**
给出一个保留prototype的解决方案或在代码层修改
**报错信息**
thirdScriptError
item.increase is not a function; [Component] Event Listener Error @ npm/taro-ui/dist/weapp/components/icon/index#(anonymous)
TypeError: item.increase is not a function

**系统信息**

 - 操作系统: [MacOs]
 - Taro 版本 [1.2.0]
 - Node.js 版本 [v8.12.0]
 - 报错平台 [weapp]

**补充信息**
事件参数从dataset中获取, 使得prototype丢失
![image](https://user-images.githubusercontent.com/18662395/49745496-0adb1480-fcda-11e8-918d-20f2385b2fe4.png)

**Comment by yuche** [comment]
由于 itemData 是一个 class 的实例或者一个包含有函数的对象，而这个类（对象）传入到小程序实际上会被小程序序列化掉，变成一个普通的 JavaScript 对象（或者说 JSON），因此他的原型就没有了。

我们正在探索自己实现一套 props 通信机制，完成的时候能这样写。

**Comment by Chen-jj** [comment]
@wqj97 v1.3.0-beta.0 已重构了 props 系统，传给**自定义子组件**（如 Issue 中的 \<AtIcon \/\>）的函数其绑定的参数不会被序列化。

但传给**内置组件**（如 \<View \/\>）的函数所绑定的参数还是会被底层的小程序框架所序列化。
