### ISSUE TITLE
小程序隐私保护指引设置

### ISSUE THREAD

**Issue by yuanchen1** [NervJS/taro#14484]
### 这个特性解决了什么问题？
为规范开发者的用户个人信息处理行为，保障用户的合法权益，自2023年9月15日起，对于涉及处理用户个人信息的小程序开发者，微信要求，仅当开发者主动向平台同步用户已阅读并同意了小程序的隐私保护指引等信息处理规则后，方可调用微信提供的隐私接口。

### 这个 API 长什么样？
微信提供了wx.onNeedPrivacyAuthorization(function callback) 接口，意为用户触发了一个微信侧未记录过同意的隐私接口调用，开发者可通过响应该事件选择提示用户的时机。此外，微信还提供了 wx.requirePrivacyAuthorize(Object object) 接口，可用于模拟触发 onNeedPrivacyAuthorization 事件。

**Comment by lilugirl** [comment]
`<Button
        id='agree-btn'
        open-type='agreePrivacyAuthorization'
        onAgreePrivacyAuthorization={handleAgreePrivacyAuthorization}
      >
        同意隐私协议
      </Button>`   onAgreePrivacyAuthorization 方法貌似不执行 有人知道为啥吗

**Comment by ZakaryCode** [comment]
Duplicate of #14377
