### ISSUE TITLE
【微信小程序 & H5】字体库引用无效

### ISSUE THREAD

**Issue by hc-advokate** [NervJS/taro#14495]
### 相关平台
微信小程序

**小程序基础库: 1.06.2307260**
**使用框架: Vue 3**

### 复现步骤
你们提交的issue有问题，填写GitHub说无效：https://github.com/hc-advokate/taro

用以下方法引用字体库，然后在程序中使用，字体无效：

Taro.loadFontFace({
	family: "SF-Pro-Rounded-Bold",
	source: 'url("https://github.com/chao921125/taro/raw/main/src/assets/fonts/SF-Pro-Rounded-Bold.ttf")',
	success: console.log,
});

### 期望结果
在微信小程序和H5中正确生效

### 实际结果
无效

### 环境信息
```

Taro CLI 3.6.15 environment info:
System:
OS: macOS 13.5.1
Shell: 5.3 - /bin/zsh
Binaries:
Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
npmPackages:
@tarojs/components: 3.6.15 => 3.6.15
@tarojs/router: 3.6.15 => 3.6.15
@tarojs/taro: 3.6.15 => 3.6.15
@tarojs/taro-h5: 3.6.15 => 3.6.15
@tarojs/webpack-runner: 3.6.15 => 3.6.15

```

**Comment by ZakaryCode** [comment]
> 你们提交的issue有问题，填写GitHub说无效：https://github.com/hc-advokate/taro

需要填写的是 git 链接

> 用以下方法引用字体库，然后在程序中使用，字体无效：
> 
> Taro.loadFontFace({ family: "SF-Pro-Rounded-Bold", source: 'url("https://github.com/chao921125/taro/raw/main/src/assets/fonts/SF-Pro-Rounded-Bold.ttf")', success: console.log, });

地址问题，需要配置 Access-Control-Allow-Origin

**Comment by hc-advokate** [comment]
谢谢

**Comment by dawenxi897094320** [comment]
怎么配置Access-Control-Allow-Origin 啊，求帮助
