### ISSUE TITLE
在基于taro-ui-sample开发第三发组件库时,其他项目引用后H5可以正常运行, weapp报错

### ISSUE THREAD

**Issue by CozySnail** [NervJS/taro#1450]
**问题描述**
在基于taro-ui-sample开发第三发组件库时,其他项目引用后H5可以正常运行, weapp报错

**复现步骤**
[复现问题的步骤]
1. 添加项目依赖 "sn-taro-ui": "^1.0.9-beta.27"
2. 修改配置文件增加配置 esnextModules: ['sn-taro-ui'],
3. npm run dev:weapp
4. 报错
     thirdScriptError 
     sdk uncaught third Error 
     module "npm/sn-taro-ui/dist/weapp/index.js" is not defined 
![image](https://user-images.githubusercontent.com/18653890/49773044-6f25c480-fd2a-11e8-81c5-f0df32fe320d.png)

**期望行为**
基于taro-ui-sample开发第三发组件库,可在h5和weapp端正常呈现

**报错信息**
![image](https://user-images.githubusercontent.com/18653890/49773075-911f4700-fd2a-11e8-95a7-d7da7e4ea972.png)

**系统信息**

 - 操作系统: [Mac OS 10.14.1 (18B75)]
 - Taro 版本 [e.g. v.1.2.0-beta.11]
 - Node.js 版本 [e.g. v10]
 - 报错平台 [h5, weapp]

**Comment by fukai007** [comment]
我这也报这个错

**Comment by licaoming** [comment]
重新编译并没有效果,我的是在更新微信客户端后出现的这个问题<WAService.js:1 Uncaught Error: module "npm/@tarojs/taro-weapp/index.js" is not defined>

**Comment by puppy1205** [comment]
为啥我表单用小程序运行就会报错  然后在h5端就好好的啊

**Comment by puppy1205** [comment]
![image](https://user-images.githubusercontent.com/74134728/128676231-76bc9533-7885-4523-b594-720980bc017a.png)

**Comment by puppy1205** [comment]
报错如上
