### ISSUE TITLE
taro小版本升级时有没有什么官方的最佳实践

### ISSUE THREAD

**Issue by shaobeichen** [NervJS/taro#14525]
### 这个特性解决了什么问题？
现在随着微信小程序的各种改进，导致有时候需要同步最新版本才能使用最新的api，也有其他方案，但总不如taro官方版本升级来的好维护，但是目前小版本升级会出现很多问题，有可能要依赖一起升，升完又可能有一些问题，所以这个需求又不能完美的得到处理

### 这个 API 长什么样？
taro小版本升级时官方的最佳实践

**Comment by bigmeow** [comment]
说下我的：
- 新拉一个项目，和老项目对比，package.json中的依赖哪些增加哪些减少了， 要同步；
- `config/index.ts` 是否增加了或者修改了什么配置(一定要把配置中的缓存关掉)
- 翻发布记录，了解变更（尤其大版本升级的`break`修改）
- 最后就是实际看报错了,具体问题具体修复
- taro 版本升级放到一个开发时间比较长的需求里去（一般2周），这样出了什么兼容问题在开发阶段你能发现
- 如果只是`api` taro 没有同步的，比如最近的隐私政策，可以先用 `@tarojs/plugin-inject` 插件自己去注入配置，无需立马升级。
