### ISSUE TITLE
taro引入微信学生身份验证的插件，升级v3.6.x后，报错找不到模板，WXMLRT_$gwx:./base.wxml:template:161:16: Template `tmpl_0_studentverify` not found.

### ISSUE THREAD

**Issue by dedcx** [NervJS/taro#14521]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/dedcx/taro-bug-repo.git](https://github.com/dedcx/taro-bug-repo.git)
**小程序基础库: 3.0.2**
**使用框架: React**

### 复现步骤
运行 dev:weapp
页面中引入studentVerify插件
  <studentVerify
        onAuth={onStudentVerifyAuth}
        onReject={onStudentVerifyReject}
        onClose={onStudentVerifyClose}
        show
      ></studentVerify>
报错：
`[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_studentverify` not found.
  159 |   
  160 | <template name="tmpl_1_container">
      |   <template is="{{xs.a(1, i.nn, l)}}" data="{{i:i,cid:1,l:xs.f(l,i.nn)}}" />
  162 | </template>
  163 | 
  164 | <template name="tmpl_2_0">`

### 期望结果
运行 dev:weapp 命令时，不会出现报错，且组件正常使用。

### 实际结果
运行 dev:weapp 命令时，出现报错，且组件无法正常使用

### 环境信息
```

  Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5
      @tarojs/components: 3.6.5 => 3.6.5
      @tarojs/helper: 3.6.5 => 3.6.5
      @tarojs/mini-runner: 3.6.5 => 3.6.5
      @tarojs/plugin-framework-react: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5
      @tarojs/react: 3.6.5 => 3.6.5
      @tarojs/runtime: 3.6.5 => 3.6.5
      @tarojs/shared: 3.6.5 => 3.6.5
      @tarojs/taro: 3.6.5 => 3.6.5
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5
      babel-preset-taro: 3.6.5 => 3.6.5
      eslint-config-taro: 3.6.5 => 3.6.5
      react: ^18.0.0 => 18.2.0
    npmGlobalPackages:
      typescript: 5.0.2
```

---
### 补充信息
taro版本升级发现的问题，taro原版本v3.3.19，升级到v3.6.5。
后经本地测试，发现3.6.x之前的版本都没问题，升级v3.6.0后报错。
https://github.com/NervJS/taro/issues/12553  提到的解决方案不适用

**Comment by dedcx** [comment]
1. v3.6.x后会对插件命名做校验，此前插件为驼峰命名，根据报错修改。

**Comment by wq1308786830** [comment]
请问这个问题最后怎么解决的啊

**Comment by agicheng** [comment]
> 请问这个问题最后怎么解决的啊

把 compiler 的prebundle 关掉试试

**Comment by tonyxiaomao** [comment]
> > 请问这个问题最后怎么解决的啊
> 
> 把 compiler 的prebundle 关掉试试

 compiler: {
      type: 'webpack5',
      prebundle: {
        enable: false,
        force: true,
      },
    },
默认是关掉的，还是会出现。有解决了吗？
