### ISSUE TITLE
taro-init(1) does not exist, try --help

### ISSUE THREAD

**Issue by hainuo** [NervJS/taro#1452]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
使用 yarn 安装了 taro 后无法执行命令

**报错信息**

$ taro init myApp                                          12/11/18 - 11:16 上午
👽 Taro v1.2.0-beta.13

error: taro-init(1) does not exist, try --help

**系统信息**

 - 操作系统: [e.g. Windows 10]
Macos10.14.2 Beta (18C52a)
 - Taro 版本 [e.g. v.0.0.64]
Taro v1.2.0-beta.13
 - Node.js 版本 [e.g. v9.0.0]
$ node --version                                      1 :( 12/11/18 - 11:19 上午
v11.3.0

应该是某些系统原因导致的，但是我不太明白该怎么去搜索关键词，还请给予指导。

**Comment by hainuo** [comment]
我的解决办法   删除 yarn 删除 nodejs 然后重新使用 brew install 安装最新版本nodejs 然后使用 npm 安装 yarn 之后一切正常 ，  感觉是因为 nodejs 升级和 yarn 升级不一致 导致 npm 版本不一致 导致安装后 符号链接指向的 node_modules 目录有问题

**Comment by RainyNight9** [comment]
你这么操作，对电脑上其他项目有影响吗？其他项目会依赖这个node 和 yarn 啊
