### ISSUE TITLE
输入框非末尾位置插入文本，光标跳到末尾的问题

### ISSUE THREAD

**Issue by fonture** [NervJS/taro#1454]
**问题描述**
输入框中输入一些文本，将光标移到除了末尾的其他位置，插入文本，每次键入都会使光标又跳回文本末尾

**复现步骤**
[复现问题的步骤]
1. 输入文本“ssss”
2. 将光标移到第二个s后面
3. 键盘输入“3”
4. 键入成功，但光标跳到文本末尾

**期望行为**
光标应该位于新键入内容的后面，而不是整个文本内容的末尾

**系统信息**

 - 操作系统: [ MAC 10.13.4 ]
 - Taro 版本 [ v1.1.4 ]
 - Node.js 版本 [v11.2.0]
 - 报错平台 [h5--QQ浏览器]

**Comment by jinjinjin0731** [comment]
taro 版本为 1.1.4 更新到最新的 1.2.0 即可

**Comment by jinjinjin0731** [comment]
路由出啥错？ 提一个路由相关的 issue？
