### ISSUE TITLE
this.setState is not a function

### ISSUE THREAD

**Issue by hainuo** [NervJS/taro#1458]
**问题描述**
无法设置 state

**复现步骤**
 taro init myApp 
 yarn run dev:rn  
编译完成后输入 i 打开 ios 模拟器
在输入框中输入内容，这个时候 就会触发 onInput 事件 然后就会报错
** js 源码  **
```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text,Input } from '@tarojs/components'
import './index.css'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '登录'
  }
  constructor (props) {
    super(props);
    this.state = { value: '33333' }
  }
  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }
  onInput(e){
    Taro.showToast({
      title:JSON.stringify(e)
    })
    this.setState({value:e.detail.value})
  }
  render () {
    return (
      <View className='index'>
        <Text className='taro-text'>
          登录
        </Text>
        <Input type='text' className='inputStyle' placeholder='输入同步到 view 中' value={this.state.value} onInput={this.onInput} />
        <Text>{this.state.value}</Text>
      </View>
    )
  }
}
```

**期望行为**
可以正常使用 this.setState 设置状态变量

**报错信息**
this.setState is not a function. (In 'this.setState({
          value: e.detail.value
        })', 'this.setState' is undefined)

onInput
    index.js:28:18
onChangeText
    index.js:1:2437
_onChange
    TextInput.js:937:55
invokeGuardedCallback
    ReactNativeRenderer-dev.js:39:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:221:34
invokeGuardedCallbackAndCatchFirstError
    ReactNativeRenderer-dev.js:245:48
executeDispatch
    ReactNativeRenderer-dev.js:572:4
executeDispatchesInOrder
    ReactNativeRenderer-dev.js:603:20
executeDispatchesAndRelease
    ReactNativeRenderer-dev.js:761:29
forEachAccumulated
    ReactNativeRenderer-dev.js:742:12
runEventsInBatch
    ReactNativeRenderer-dev.js:927:6
runExtractedEventsInBatch
    ReactNativeRenderer-dev.js:952:19
<unknown>
    ReactNativeRenderer-dev.js:2703:6
batchedUpdates
    ReactNativeRenderer-dev.js:13724:16
batchedUpdates
    ReactNativeRenderer-dev.js:2565:27
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2701:17
receiveEvent
    ReactNativeRenderer-dev.js:2721:26
__callFunction
    MessageQueue.js:351:47
<unknown>
    MessageQueue.js:116:26
__guardSafe
    MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    MessageQueue.js:115:17

**系统信息**

 - 操作系统: MacOs 10.14.2 Beta (18C52a)
 - Taro 版本 
👽 Taro v1.2.0-beta.13
 - Node.js 版本 [e.g. v9.0.0]
v11.3.0
 - 报错平台 [h5, weapp]
rn 基于 expo 运行
**补充信息**

**Comment by luckyadam** [comment]
`this.onInput.bind(this)`

或者
```js
onInput = (e) => {
    Taro.showToast({
      title:JSON.stringify(e)
    })
    this.setState({value:e.detail.value})
}
```

**Comment by hainuo** [comment]
@luckyadam   明白了   onInput 绑定的对象是 输入框本身而不是 index
