### ISSUE TITLE
slot内的方法调用编译问题

### ISSUE THREAD

**Issue by frojan** [NervJS/taro#1459]
![image](https://user-images.githubusercontent.com/6687233/49785823-b9279e00-fd5c-11e8-87ac-77b413c7861b.png)

如图

**Comment by yuche** [comment]
1. 你要有源码才能知道为啥
2. 你要带上你的版本

**Comment by frojan** [comment]
版本1.1.9 完整源码不方便提供，部分源码截图如下：
![image](https://user-images.githubusercontent.com/6687233/49788280-ea579c80-fd63-11e8-9bff-7873d371ada0.png)
如果需要的话，晚点可以弄个简易版本复现

**Comment by yuche** [comment]
1. 更新一下到最新的 beta 版本
2. 如果还有问题就给一个简易复现，但是不要贴截图

**Comment by frojan** [comment]
简易复现 v1.2.0-beta.14
`import { ComponentClass } from 'react'
import Taro, { Component, Config } from '@tarojs/taro'
import { View } from '@tarojs/components'
import SlotTest from '../../components/SlotTest';
import './index.scss';

type PageStateProps = {}
type PageDispatchProps = {}
type PageOwnProps = {}
type PageState = {
  list: (number | string)[];
}

type IProps = PageStateProps & PageDispatchProps & PageOwnProps

interface Index {
  state: PageState;
  props: IProps;
}
class Index extends Component {
  constructor(props){
    super(props)
    this.state={
      list: [
        '123',
        123,
        '123',
        123
      ]
    }
  }
  config: Config = {
    navigationBarTitleText: '测试页面'
  }
  componentDidMount() {
  }

  private isString(item: any){
    return typeof item === 'string'
  }

  render () {
    const { list } = this.state;
    return (
      <View>
        {
          list.map((item, index) => (
            <SlotTest>
              {
                this.isString(item) ? 
                <View>i am string</View> :
                <View>i am number</View>
              }
            </SlotTest>
          ))
        }
      </View>
    )
  }
}

export default Index as ComponentClass<PageOwnProps, PageState>
  `
子组件：
`import { ComponentClass } from 'react'
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

type PageStateProps = {}
type PageDispatchProps = {}
type PageOwnProps = {
  children?: any;
}
type PageState = {}

type IProps = PageStateProps & PageDispatchProps & PageOwnProps

interface Index {
  props: IProps;
}
class Index extends Component {
  constructor(props){
    super(props)
    this.state={}
  }
  componentDidMount() {
  }


  render () {
    return (
      <View>{this.props.children}</View>
    )
  }
}

export default Index as ComponentClass<PageOwnProps, PageState>
  `
期望显示：
i am string
i am number
i am string
i am number
实际显示：
i am number
i am number
i am number
i am number

更新后报的错跟之前不一样了好像

**Comment by yuche** [comment]
循环里是不能用 slot 的。
参考：https://nervjs.github.io/taro/docs/children.html

**Comment by frojan** [comment]
这个简易复现就是在支付宝里面跑失败的 :(

**Comment by yuche** [comment]
在你的循环里写一个 return 就好了
