### ISSUE TITLE
部分文档和功能对不上

### ISSUE THREAD

**Issue by lkspc** [NervJS/taro#146]
玩了一下 taro，发现很多文档上有的东西，实际功能没有，也遇到一些坑，请官方人员解答一下。目前测试的是 windows 环境下的 h5。
* 在 config 中注入 env 后，页面中获取的 `process.env` 是个空对象
* webpack 自定义配置很多功能无效
* defineConstants 无效，页面中获取不到
* Taro.request 看了源码是直接用的 fetch，没有 polyfill，编译后手机上跑不了
* 无法使用第三方 react 组件库，因为大部分 react 库依赖于 react-dom
....

**Comment by luckyadam** [comment]
你好~ 
1、`env` 目前只在小程序端生效了，H5 端是遗漏了，我们今天可以同步
2、`webpack` 有哪些自定义配置无效呢
3、这个问题同 1
4、这个确实有问题，polyfill 应该要打包进基础库里，不能让开发者自己去引用
5、在 H5 端可以使用第三方 react 组件库，需要在 webpack 加一个 `alias` 配置
```javascript
// config/index.js

const config = {
  ...
  h5: {
    webpack (defaultConfig, webpack) {
      defaultConfig.resolve. alias = {
        'react': 'nervjs',
        'react-dom': 'nervjs'
      }
    }
  }
}
```

**Comment by lkspc** [comment]
devServer 这个配置无效

**Comment by lkspc** [comment]
其他的还没试过，我其实想说的是 “wepback自定义部分配置无效”

**Comment by luckyadam** [comment]
soga~ `devServer` 的配置还没放出来~  我们正在跟进放出

**Comment by lkspc** [comment]
好的，希望尽快放出。

另外，页面里面的 config.navigationBarTitleText 在 h5 中并没有成功修改到 title

**Comment by luckyadam** [comment]
好嘞~ 正在处理~
这个问题我们看下哈

**Comment by PedroGao** [comment]
我搞了半天的devServer配置一点用都没有，苦死我等啊 :sob:

**Comment by jordzhang** [comment]
0.0.59版本，h5上，process.env在页面上还是空，另外defineConstants在h5上也是不支持的？

**Comment by luckyadam** [comment]
最新的 beta 版本已经都支持了~

**Comment by furfar** [comment]
@luckyadam 
我想使用webpack配置别名，但没有生效，已经提了如下issue，请帮忙处理一下，谢谢

https://github.com/NervJS/taro/issues/82#issuecomment-418634826
