### ISSUE TITLE
Taro v1.2.0-beta.12 编译h5报错，小程序正常

### ISSUE THREAD

**Issue by zzlit** [NervJS/taro#1461]
**问题描述**
编译h5报错，小程序正常

**复现步骤**
npm run dev:h5

版本信息
![image](https://user-images.githubusercontent.com/28583195/49786886-2b4db200-fd60-11e8-8d85-d7c496a9a538.png)

_babylon@6.18.0@babylon/lib/index.js 报错处
```
var pp$5 = Parser.prototype;

// This function is used to raise exceptions on parse errors. It
// takes an offset integer (into the current `input`) to indicate
// the location of the error, attaches the position to the end
// of the error message, and then raises a `SyntaxError` with that
// message.

pp$5.raise = function (pos, message) {
  var loc = getLineInfo(this.input, pos);
  message += " (" + loc.line + ":" + loc.column + ")";
  var err = new SyntaxError(message);
  err.pos = pos;
  err.loc = loc;
  throw err;
};
```

**期望行为**

**报错信息**

![image](https://user-images.githubusercontent.com/28583195/49786962-5c2de700-fd60-11e8-8f86-1940d41ee775.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.2.0-beta.12]
 - Node.js 版本 [e.g. v8.11.3]
 - 报错平台 [h5]

**补充信息**

**Comment by luckyadam** [comment]
报错信息贴完整点，相关代码贴一下看下

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/49788365-1f63ef00-fd64-11e8-87ac-4756a7198eda.png)
应该就是这个文件

**Comment by zzlit** [comment]
@luckyadam 已解决，就是这个文件出错了，感谢！

**Comment by Gxuebin** [comment]
npm run dev:h5 
![image](https://user-images.githubusercontent.com/20697809/50382367-97250880-06d8-11e9-90ab-a87e6b14d001.png)

👽 Taro v1.2.1


  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.0 => 1.2.0
      @tarojs/plugin-babel: 1.2.0 => 1.2.0
      @tarojs/plugin-csso: 1.2.0 => 1.2.0
      @tarojs/plugin-less: 1.2.0 => 1.2.0
      @tarojs/plugin-sass: 1.2.0 => 1.2.0
      @tarojs/plugin-uglifyjs: 1.2.0 => 1.2.0
      @tarojs/router: 1.2.0 => 1.2.0
      @tarojs/taro: 1.2.0 => 1.2.0
      @tarojs/taro-h5: 1.2.0 => 1.2.0
      @tarojs/taro-weapp: 1.2.0 => 1.2.0
      @tarojs/webpack-runner: 1.2.0 => 1.2.0
      eslint-config-taro: 1.2.0 => 1.2.0
      eslint-plugin-taro: 1.2.0 => 1.2.0
