### ISSUE TITLE
Image组件未设置src时，会有黑框；mode=""时，图标按原大小显示

### ISSUE THREAD

**Issue by handsomeliuyang** [NervJS/taro#14615]
### 这个特性解决了什么问题？
Image在H5端显示不正常的问题

### 这个 API 长什么样？
1. Image组件未设置src时，没有黑框；

2. mode=""时，图标按scrollToFill显示

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/df0a012b-153a-47b3-bfd6-30ae14fc3eff)
你说的黑框没有复现，默认就是scaleToFill
