### ISSUE TITLE
有参数可以控制这个tabbar的数量限制吗

### ISSUE THREAD

**Issue by swbcnegc** [NervJS/taro#14627]
### 相关平台
H5

**浏览器版本: Chrome  117.0.5938.132****小程序基础库: 2.33.0**
**使用框架: Vue 3**

### 复现步骤
const customRoutes = ((_b = this.conf) === null || _b === void 0 ? void 0 : _b.customRoutes) || {};
    if (Object.prototype.toString.call(list) !== '[object Array]' ||
      list.length < 2 ||
      list.length > 5) {
      throw new Error('tabBar 配置错误');
    }

h5端 需要动态显示tabbar，总数量超过了5个。在微信小程序是可以正常运行，h5运行报错，上面是taro-tabbar.js中的代码，限制了数量

### 期望结果
不限制tabbar数量

### 实际结果
tabBar 配置错误

### 环境信息
```
👽 Taro v3.6.17


  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 11.7.8
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.16 => 3.6.16 
      @tarojs/components: 3.6.16 => 3.6.16 
      @tarojs/helper: 3.6.16 => 3.6.16 
      @tarojs/plugin-framework-vue3: 3.6.16 => 3.6.16 
      @tarojs/plugin-html: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-alipay: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-h5: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-jd: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-qq: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-swan: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-tt: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-weapp: 3.6.16 => 3.6.16 
      @tarojs/runtime: 3.6.16 => 3.6.16 
      @tarojs/shared: 3.6.16 => 3.6.16 
      @tarojs/taro: 3.6.16 => 3.6.16 
      @tarojs/webpack5-runner: 3.6.16 => 3.6.16 
      babel-preset-taro: 3.6.16 => 3.6.16 
      eslint-config-taro: 3.6.16 => 3.6.16 
    npmGlobalPackages:
      typescript: 5.0.2
```

**Comment by TheKonka** [comment]
动态显示怎么搞的？总数量超过了5个微信小程序也是报错的

**Comment by swbcnegc** [comment]
> 动态显示怎么搞的？总数量超过了5个微信小程序也是报错的

app.config里  tabbar->list 配置超过5个微信不会报错。我是在每个页面都引入自己模拟的tabbar。

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/d5c7182e-1663-43f2-bcc4-946693aef61e)
我配置超过5个报错了

**Comment by swbcnegc** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/276045563-d5c7182e-1663-43f2-bcc4-946693aef61e.png) 我配置超过5个报错了

![Xnip2023-10-18_15-51-10](https://github.com/NervJS/taro/assets/121573344/07f92c2e-0a35-483e-a0b9-7bcc051ba6a2)
"custom":true 开启自定义就没限制数量了

**Comment by TheKonka** [comment]
哦哦

**Comment by xuchen522178898** [comment]
这个问题还没有解决吗？ 或者taro 能否让h5端可以使用自定义tabbar
