### ISSUE TITLE
Taro.setClipboardData设置系统剪贴板的内容，调用成功后，会弹出 toast 提示，toast 提示内容能否定制？

### ISSUE THREAD

**Issue by ColinHwang** [NervJS/taro#14642]
### 这个特性解决了什么问题？
Taro.setClipboardData设置系统剪贴板的内容，调用成功后，会弹出 toast 提示，toast 提示内容目前是固定的"内容已复制"，这部分内容能否提供参数定制？

### 这个 API 长什么样？

successMsg/successToastText

**Comment by TheKonka** [comment]
可以，你在成功的回调里面 hidetoast 然后再自己 showtoast 就行

**Comment by ColinHwang** [comment]
这么绕的吗。。。感谢回复
