### ISSUE TITLE
Taro 3.6.17 snapshot无法正常使用

### ISSUE THREAD

**Issue by hellowalker** [NervJS/taro#14647]
### 相关平台
微信小程序

**小程序基础库: 3.1.2**
**使用框架: React**

### 复现步骤
小程序官方snapshot demo https://developers.weixin.qq.com/s/QKYfEdmo7LLH 
用ios真机跑 功能运行正常
改成taro编写后跑 无论ios 安卓机 控制台均报告警
 

### 期望结果
snapshot能够成功执行

### 实际结果

警告：
检测到 NodesRef。node 不能立即回调，可能由于 scroll-view 的按需加载特性，使得不在屏的节点无法立即取到节点相关信息
![IMG_1134](https://github.com/NervJS/taro/assets/25142334/bd7d06b5-912a-417f-9e65-4ea5ec72ac9a)

### 环境信息
```
👽 Taro v3.6.17


  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.7.4


```

**Comment by TheKonka** [comment]
你这个报错应该跟 snapshot 没关系，我试了 snapshot 可以正常使用的
你把 scrollview 去掉或者 让节点在屏看看

**Comment by hellowalker** [comment]
怪的是我压根没用scrollview 节点在屏内

**Comment by hellowalker** [comment]
> 你这个报错应该跟 snapshot 没关系，我试了 snapshot 可以正常使用的 你把 scrollview 去掉或者 让节点在屏看看

怪的是我压根没用scrollview 节点在屏内

**Comment by TheKonka** [comment]
那你 上传个demo看看

**Comment by hellowalker** [comment]
> 那你 上传个demo看看

https://github.com/hellowalker/taro-snapshot-demo

**Comment by hellowalker** [comment]
> 应该是手机上用的还是webview， 改成 skyline render 就没这个报错啦

感谢🙏
