### ISSUE TITLE
button组件opentype=openAwemeUserProfile无法打开抖音小程序的抖音号页面

### ISSUE THREAD

**Issue by workliu111** [NervJS/taro#14649]
### 相关平台
字节跳动小程序

**小程序基础库: 2.98.0.6**
**使用框架: React**

### 复现步骤
为啥taro的button组件opentype设置成openAwemeUserProfile无法触发么，自定义属性  data-AwemeId={follow_userid}   data-aweme-id={follow_userid}data-AwemeId={follow_userid}都无法触发

### 期望结果
可以进入抖音个人号页面

### 实际结果
没进入

### 环境信息
```
👽 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.10 => 3.5.10 
      @tarojs/components: 3.5.10 => 3.5.10 
      @tarojs/helper: 3.5.10 => 3.5.10 
      @tarojs/plugin-framework-react: ^3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-jd: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-qq: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-swan: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-tt: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-weapp: 3.5.10 => 3.5.10 
      @tarojs/react: 3.5.10 => 3.5.10 
      @tarojs/router: 3.5.10 => 3.5.10 
      @tarojs/runtime: 3.5.10 => 3.5.10 
      @tarojs/shared: 3.5.10 => 3.5.10 
      @tarojs/taro: 3.5.10 => 3.5.10 
      @tarojs/taro-h5: 3.5.10 => 3.5.10 
      @tarojs/webpack5-runner: 3.5.10 => 3.5.10 
      babel-preset-taro: 3.5.10 => 3.5.10 
      eslint-config-taro: 3.5.10 => 3.5.10 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.4 

```

**Comment by TheKonka** [comment]
升级到最新版本再试下

**Comment by workliu111** [comment]
更新了仍然不行
Taro v3.6.17


  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.10 => 3.5.10 
      @tarojs/components: 3.5.10 => 3.5.10 
      @tarojs/helper: 3.5.10 => 3.5.10 
      @tarojs/plugin-framework-react: ^3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-jd: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-qq: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-swan: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-tt: 3.5.10 => 3.5.10 
      @tarojs/plugin-platform-weapp: 3.5.10 => 3.5.10 
      @tarojs/react: 3.5.10 => 3.5.10 
      @tarojs/router: 3.5.10 => 3.5.10 
      @tarojs/runtime: 3.5.10 => 3.5.10 
      @tarojs/shared: 3.5.10 => 3.5.10 
      @tarojs/taro: 3.5.10 => 3.5.10 
      @tarojs/taro-h5: 3.5.10 => 3.5.10 
      @tarojs/webpack5-runner: 3.5.10 => 3.5.10 
      babel-preset-taro: 3.5.10 => 3.5.10 
      eslint-config-taro: 3.5.10 => 3.5.10 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.1 => 3.1.1

**Comment by TheKonka** [comment]
taro 相关依赖要保持一致，都要升级到最新版本，你这还都是 3.5.10

**Comment by workliu111** [comment]
升级到3.6.17可以了，谢谢啦
