### ISSUE TITLE
v3.5.0-canary.0执行taro build --type harmony后报错defineAppConfig is not defined

### ISSUE THREAD

**Issue by helen-johnnny** [NervJS/taro#14654]
### 相关平台
鸿蒙

### 复现仓库
[https://gitee.com/openharmony-sig/taro.git](https://gitee.com/openharmony-sig/taro.git)

**使用框架: React**

### 复现步骤
使用了官方提供的demo（taro-shopping-example），并将taro相关依赖都安装成3.5.0-canary.0，执行taro build --type harmony后报错defineAppConfig is not defined

### 期望结果
编译成功并能将鸿蒙项目成功运行

### 实际结果
编译报错

### 环境信息
```
Taro v3.5.0-canary.0
Taro CLI 3.6.4 environment info:
    Binaries:
      Node: 14.19.3
      npm: 8.19.4

(实际执行taro info也会报错：/XXX/XXX/myHarmonyToraApp2/node_modules/@tarojs/plugin-platform-harmony/dist/index.js:589
        if (opts.platform !== HARMONY)
                 ^

TypeError: Cannot read properties of undefined (reading 'platform'))
```

**Comment by xuanzebin** [comment]
请升级 taro 到 4.0.0-beta.82 版本，并参考文档：https://docs.taro.zone/docs/next/harmony 进行最新的鸿蒙开发
