### ISSUE TITLE
1.2.0.beta-13 编译后 taro-ui报错，.beta-12正常

### ISSUE THREAD

**Issue by agulado** [NervJS/taro#1466]
**问题描述**
小程序端：jsEnginScriptError
Component is not found in path "项目路径/npm/taro-ui/dist/weapp/components/icon/index" (using by "component/float-buttons");onAppRoute
Error: Component is not found in path "项目路径/npm/taro-ui/dist/weapp/components/icon/index" (using by "component/float-buttons")

h5端没测试

taro-ui版本：1.5.1

```javascript
/* float-buttons */
import { AtIcon } from 'taro-ui'

/* 核心代码 */
const Buttons = () => (
            buildButtons().map((button, index) => (
                <View
                    key={index}
                    className='buttonBox'
                    onClick={this.props.onClick.bind(this, button)}
                >
                    <AtIcon
                        prefixClass='fa'
                        value={button}
                        size='18'
                        color='#666'
                    />
                    {button === ICON_NAME.SHARE ? ShareButton : null}
                </View>
            ))
        )

        return (
            <View className='wrapper'>
                {Buttons}
            </View>
        )
```

项目路径/npm/taro-ui/dist/weapp/components/icon/index.js 是存在的。

**Comment by luckyadam** [comment]
1.2.0-beta.14 修复了这个问题~

**Comment by agulado** [comment]
> 1.2.0-beta.14 修复了这个问题~

ok~

**Comment by cooliean** [comment]
为什么我都更新了。


"@tarojs/async-await": "^1.2.0-beta.14",
    "@tarojs/components": "^1.2.0-beta.14",
    "@tarojs/mobx": "^1.2.0-beta.14",
    "@tarojs/mobx-h5": "^1.2.0-beta.14",
    "@tarojs/mobx-rn": "^1.2.0-beta.14",
    "@tarojs/rn-runner": "^1.2.0-beta.14",
    "@tarojs/router": "^1.2.0-beta.14",
    "@tarojs/taro": "^1.2.0-beta.14",
    "@tarojs/taro-alipay": "^1.2.0-beta.14",
    "@tarojs/taro-h5": "^1.2.0-beta.14",
    "@tarojs/taro-swan": "^1.2.0-beta.14",
    "@tarojs/taro-tt": "^1.2.0-beta.14",
    "@tarojs/taro-weapp": "^1.2.0-beta.14",

还是这个错误

**Comment by agulado** [comment]
@cooliean 我刚才更新，已经没问题了。

**Comment by fernandoxu** [comment]
我的beta.15为啥也有这问题。。

**Comment by georgezouq** [comment]
@luckyadam tarojs2.0.0-beta.13 + taro-ui:^2.2.4 也有这个问题
