### ISSUE TITLE
使用版本'1.2.0-beta.13'，npm run dev:h5 可以运行，但界面报错Uncaught Error: Can not find proper registered route for '/'

### ISSUE THREAD

**Issue by BackToHappyBear** [NervJS/taro#1467]
初始化的项目，运行出错 Uncaught Error: Can not find proper registered route for '/'

**Comment by Littly** [comment]
麻烦提供一下.temp/app.js的代码 定位问题用~

**Comment by Littly** [comment]
#1421 #1418

**Comment by BackToHappyBear** [comment]
> 跟#1418 #1421 应该是一样的问题

我使用的是最新的版本1.2.0-beta.13，而且项目用 tarojs/cli 初始化后未做其他改动

**Comment by Littly** [comment]
麻烦提供一下.temp/app.js的代码 定位问题用~

**Comment by gmw-zjw** [comment]
今天遇到同样的问题 taro/cli版本号是v1.2.0 - beta 6， 
./temp/app.js
`import { Component } from "@tarojs/taro-h5";
import Nerv from "nervjs";


import './app.scss';

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

import Taro from '@tarojs/taro-h5';
import { Router } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});
class App extends Component {

  config = {
    pages: ['pages/index/index'],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  };

  componentDidMount() {
    this.componentDidShow();
  }

  componentDidShow() {}

  componentDidHide() {}

  componentDidCatchError() {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Router routes={[['/pages/index/index', require('./pages/index/index').default]]} />;
  }

  componentWillUnmount() {
    this.componentDidHide();
  }

}

Nerv.render(<App />, document.getElementById('app'));`

**Comment by gmw-zjw** [comment]
taro/cli 的版本升级到 v1.2.0 beta-14 问题已解决

**Comment by luckyadam** [comment]
@BackToHappyBear 升级 cli 到最新版本

**Comment by BackToHappyBear** [comment]
> @BackToHappyBear 升级 cli 到最新版本

项目就是最新版的，是 1.2.0-beta.14， 依赖和.temp/app.js 上面已经贴了

**Comment by luckyadam** [comment]
> > @BackToHappyBear 升级 cli 到最新版本
> 
> 项目就是最新版的，是 1.2.0-beta.14， 依赖和.temp/app.js 上面已经贴了

你的 cli 不是最新的，你 taro -V 就知道了

**Comment by BackToHappyBear** [comment]
> > > @BackToHappyBear 升级 cli 到最新版本
> > 
> > 
> > 项目就是最新版的，是 1.2.0-beta.14， 依赖和.temp/app.js 上面已经贴了
> 
> 你的 cli 不是最新的，你 taro -V 就知道了

npm 全局安装最新版本可以正常运行了，之前我是直接使用 npx @tarojs/cli init myApp，但是 taro 的版本是 v1.1.1，不清楚是什么原因

**Comment by giantss** [comment]
我现在也遇到了这个问题。`redirectTo:fail Can not find proper registered route for '/pages/pay/pay'"`

`.temp/app.js`
```
import { Component } from "@tarojs/taro-h5";
import Nerv from "nervjs";


import './app.css';

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

import Taro from '@tarojs/taro-h5';
import { Router, createHistory, mountApis } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});

const _taroHistory = createHistory({
  mode: "hash",
  basename: "/",
  customRoutes: {
    "/pages/index/index": "/index",
    "/pages/pay/pay": "/pay"
  },
  firstPagePath: "/pages/index/index"
});

mountApis(_taroHistory);
class App extends Component {

  config = {
    pages: ["/pages/index/index"],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  };

  componentDidMount() {
    this.componentDidShow();
  }

  componentDidShow() {}

  componentDidHide() {}

  componentDidCatchError() {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Router history={_taroHistory} routes={[{
      path: '/pages/index/index',
      componentLoader: () => import( /* webpackChunkName: "index_index" */'./pages/index/index'),
      isIndex: true
    }]} customRoutes={{
      "/pages/index/index": "/index",
      "/pages/pay/pay": "/pay"
    }} />;
  }

  componentWillUnmount() {
    this.componentDidHide();
  }

  constructor(props, context) {
    super(props, context);
    Taro._$app = this;
  }

}

Nerv.render(<App />, document.getElementById('app'));
```
@luckyadam

**Comment by Littly** [comment]
> 我在H5页面跳转时也遇到了这个问题。
> 
> ```
>  Taro.redirectTo({
>             url: '/pages/pay/pay'
>         })
> ```
> 报错： `redirectTo:fail Can not find proper registered route for '/pages/pay/pay'"`
> 
> Taro `v1.2.21`
> 
> 我配置了路由
> ![image](https://user-images.githubusercontent.com/13778798/54916819-5639cb80-4f35-11e9-970e-f3e54fce23df.png)
> 
> `.temp/app.js`
> 
> ```
> import { Component } from "@tarojs/taro-h5";
> import Nerv from "nervjs";
> 
> 
> import './app.css';
> 
> // 如果需要在 h5 环境中开启 React Devtools
> // 取消以下注释：
> // if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
> //   require('nerv-devtools')
> // }
> 
> import Taro from '@tarojs/taro-h5';
> import { Router, createHistory, mountApis } from '@tarojs/router';
> Taro.initPxTransform({
>   "designWidth": 750,
>   "deviceRatio": {
>     "640": 1.17,
>     "750": 1,
>     "828": 0.905
>   }
> });
> 
> const _taroHistory = createHistory({
>   mode: "hash",
>   basename: "/",
>   customRoutes: {
>     "/pages/index/index": "/index",
>     "/pages/pay/pay": "/pay"
>   },
>   firstPagePath: "/pages/index/index"
> });
> 
> mountApis(_taroHistory);
> class App extends Component {
> 
>   config = {
>     pages: ["/pages/index/index"],
>     window: {
>       backgroundTextStyle: 'light',
>       navigationBarBackgroundColor: '#fff',
>       navigationBarTitleText: 'WeChat',
>       navigationBarTextStyle: 'black'
>     }
>   };
> 
>   componentDidMount() {
>     this.componentDidShow();
>   }
> 
>   componentDidShow() {}
> 
>   componentDidHide() {}
> 
>   componentDidCatchError() {}
> 
>   // 在 App 类中的 render() 函数没有实际作用
>   // 请勿修改此函数
>   render() {
>     return <Router history={_taroHistory} routes={[{
>       path: '/pages/index/index',
>       componentLoader: () => import( /* webpackChunkName: "index_index" */'./pages/index/index'),
>       isIndex: true
>     }]} customRoutes={{
>       "/pages/index/index": "/index",
>       "/pages/pay/pay": "/pay"
>     }} />;
>   }
> 
>   componentWillUnmount() {
>     this.componentDidHide();
>   }
> 
>   constructor(props, context) {
>     super(props, context);
>     Taro._$app = this;
>   }
> 
> }
> 
> Nerv.render(<App />, document.getElementById('app'));
> ```
> @luckyadam @Littly

看样子是你没把`/pages/pay/pay`这个页面配进`app.js`里面
![image](https://user-images.githubusercontent.com/5780093/54917248-58505a00-4f36-11e9-96a1-9f3f23d1c25e.png)

**Comment by xiongmao911** [comment]
H5打包后线上lib.dll.js:1 Uncaught Invariant Violation: Can not find proper registered route for '/static/h5/index.html'

.temp/app.js

import { Component } from "@tarojs/taro-h5";
import Nerv from "nervjs";
import { Provider } from "@tarojs/mobx-h5";
import '@tarojs/async-await';

import counterStore from './store/counter';
// import './custom-theme.scss'
import './app.less';

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

import Taro from '@tarojs/taro-h5';
import { Router } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});
const store = {
  counterStore
};

class App extends Component {

  config = {
    pages: ['pages/packageSpecial/index', 'pages/coupons/index'],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  };

  componentDidMount() {
    this.componentDidShow();
  }

  componentDidShow() {}

  componentDidHide() {}

  componentDidCatchError() {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Provider store={store}>
                <Router mode={"browser"} publicPath={"/."} routes={[{
        path: '/pages/packageSpecial/index',
        componentLoader: () => import( /* webpackChunkName: "packageSpecial_index" */'./pages/packageSpecial/index'),
        isIndex: true
      }, {
        path: '/pages/coupons/index',
        componentLoader: () => import( /* webpackChunkName: "coupons_index" */'./pages/coupons/index'),
        isIndex: false
      }]} customRoutes={{
        "/pages/packageSpecial/index": "/package",
        "/pages/coupons/index": "/coupons"
      }} basename={"/static/h5/index.html"} />
              </Provider>;
  }

  componentWillUnmount() {
    this.componentDidHide();
  }

  constructor(props, context) {
    super(props, context);

    Taro._set$app(this);
  }

}

Nerv.render(<App />, document.getElementById('app'));
