### ISSUE TITLE
使用redux父组件传【修改过属性的对象】到子组件数据更新存在问题（weapp）

### ISSUE THREAD

**Issue by yzStrive** [NervJS/taro#1469]
**问题描述**
小程序开发中，使用dva，父组件传一个【对象】到子组件，父组件内修改对象（**新增属性／删除属性**），然后dispatch数据到store里面，更新数据后，触发父组件render,父组件的props回传的值是正确的，子组件会触发render，但是传下来的对象并没有更新。换成是【数组】传递给子组件，则一切正常。

**复现步骤**
https://github.com/yzStrive/taro-redux-dva-demo
```
git clone
yarn 
yarn dev:weapp
打开小程序开发工具，点击界面上的按钮，即可简单的复现。具体问题，可能还需要查看源码。
```

**期望行为**
能够解决此问题

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [MacOS]
 - Taro 版本 [v1.2.0-beta.13]（之前的开发版本存在的，之前不确定是那边的问题，今天更新taro，使用精简版本来复现此bug的）
 - Node.js 版本 [v8.12.0]
 - 报错平台 [weapp]

**补充信息**

**Comment by luckyadam** [comment]
@yzStrive 
https://github.com/yzStrive/taro-redux-dva-demo/blob/5559416f4d088e63cb1ce1360a707347466bdb27/src/pages/home/index.js#L28-L30

对象的 key 不要带小数点，不然数据 diff 会有问题

**Comment by nyrf** [comment]
https://github.com/NervJS/taro/issues/968 应该和这个一样的情况，key中有小数，因为taro是把对象打散成数组，比如keys['4.7']最后taro会变成_arr1.4.7 这就出问题了，现在只能把这部分写成原生，或者如yuche 所说的，https://github.com/NervJS/taro/issues/968#issuecomment-438520571 那样处理

**Comment by yzStrive** [comment]
@nyrf @luckyadam 确实是对象的key上有小数点的问题，thx。
