### ISSUE TITLE
微信小程序skyline模式下，使用CustomWrapper包裹导致样式丢失

### ISSUE THREAD

**Issue by wyf199605** [NervJS/taro#14699]
### 这个特性解决了什么问题？
微信小程序skyline模式下，通过baseLevel或者CustomWrapper生成新组件，组件的样式隔离导致样式失效。

### 这个 API 长什么样？
微信小程序`glass-easel `适配指引要求addGlobalClass属性在JSON中声明；

微信小程序文档：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html#JSON-%E9%85%8D%E7%BD%AE

### 旧版

component.js

```
Component({
  options: {
    addGlobalClass: true
  }
})
```

### 新版

component.json

```
{
  "component": true,
  "addGlobalClass": true
}
```

**Comment by sunflower8th** [comment]
怎么解决这个问题了

**Comment by koppthe** [comment]
> 怎么解决这个问题了,taro 3.6.24 还有问题

这是两周前修复的版本，跟 v3.6.29 发布的，v3.6.24 是两个月前的版本
