### ISSUE TITLE
Taro.openVideoEditor部分机型会自动保存到系统相册，部分机型不会自动保存到相册

### ISSUE THREAD

**Issue by fortune1992** [NervJS/taro#14706]
### 相关平台
微信小程序

**小程序基础库: 3.1.1**
**使用框架: React**

### 复现步骤
选择视频，打开视频裁剪，裁剪完成后，点击完成，现象如下：
1、很多机型上无论是否授予添加到相册权限，都会将裁剪的视频自动保存到系统相册。
2、部分机型上已授予添加到相册权限，不会自动保存裁剪视频到系统相册。

主要问题是：有的机型会将裁剪的视频自动保存到系统相册，有的机型不会自动保存裁剪视频到系统相册，需要手动导出。

### 期望结果
对齐自动保存裁剪视频到系统相册处理结果。

### 实际结果
有的机型会将裁剪的视频自动保存到系统相册，有的机型不会自动保存裁剪视频到系统相册，需要手动导出。

### 环境信息
```
👽 Taro v3.6.18


  Taro CLI 3.6.18 environment info:
    System:
      OS: macOS 11.7.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.20.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18 
      @tarojs/components: 3.6.18 => 3.6.18 
      @tarojs/helper: 3.6.18 => 3.6.18 
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18 
      @tarojs/plugin-mini-ci: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18 
      @tarojs/react: 3.6.18 => 3.6.18 
      @tarojs/runtime: 3.6.18 => 3.6.18 
      @tarojs/shared: 3.6.18 => 3.6.18 
      @tarojs/taro: 3.6.18 => 3.6.18 
      @tarojs/taro-loader: 3.6.18 => 3.6.18 
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18 
      babel-preset-taro: 3.6.18 => 3.6.18 
      eslint-config-taro: 3.6.18 => 3.6.18 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.1 => 3.1.1
```

---
### 补充信息
示例代码：
 Taro.chooseVideo({
        sourceType: ['album'],
        maxDuration: 60,
        compressed: false,
        camera: 'back',
        success: (res) => {
          Taro.openVideoEditor({
            filePath: res.tempFilePath,
            success: (success) => {
              // that.saveVideo(success.tempFilePath);
              });
            },
          });
        },
      });
    });

**Comment by fortune1992** [comment]
> 可以试下原生小程序效果是否如此

还不会写微信原生小程序，目前只会React语法。。。

**Comment by Chen-jj** [comment]
> > 可以试下原生小程序效果是否如此
> 
> 还不会写微信原生小程序，目前只会React语法。。。

@fortune1992 `Taro.chooseVideo` 在小程序端只是透传调用小程序的 API，并没有做额外的事情（等于直接调用 `wx.chooseVideo`），这个问题应该是小程序自身导致的，可以去微信小程序的官方论坛问问看。
