### ISSUE TITLE
使用第三方iView Weapp UI组件，样式和官方显示不同

### ISSUE THREAD

**Issue by TonyLiuYan** [NervJS/taro#1471]
**问题描述**
由于需求需要，需要在taro框架中引入第三方的UI组件iView Weapp，引入后可以正常使用，但是显示的样式和iView官方的显示不同，个别组件差异很大，请问框架目前是否兼容？

**复现步骤**

1. iView官方快速上手地址：https://weapp.iviewui.com/docs/guide/start
2. 显示差异大的组件请参照：Gird，官方示例地址为：https://github.com/TalkingData/iview-weapp/tree/master/examples/pages/grid

**期望行为**
显示效果与iView官方一致

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/size.html#%E5%BF%BD%E7%95%A5
看下这个文档

**Comment by TonyLiuYan** [comment]
> https://nervjs.github.io/taro/docs/size.html#%E5%BF%BD%E7%95%A5
> 看下这个文档

谢谢回复，已认真研读，但未能找到合理的解决方案

**Comment by TonyLiuYan** [comment]
已找到关闭转换配置
路径：`config/index.js`
`weapp`节点中有个`pxtransform`，将下面的`enable: false`设置成false即可
**新问题**：当使用taro-ui的时候，显示又不正常，因项目需求，使用不同的UI组件实现功能，请问两套UI组件是否可以兼容同时使用？

**Comment by JazzOne** [comment]
> 已找到关闭转换配置
> 路径：`config/index.js`
> `weapp`节点中有个`pxtransform`，将下面的`enable: false`设置成false即可
> **新问题**：当使用taro-ui的时候，显示又不正常，因项目需求，使用不同的UI组件实现功能，请问两套UI组件是否可以兼容同时使用？

我目前的做法：

```js
pxtransform: {
          enable: true,
          config: {
            selectorBlackList: ['van']
          }
        }
```
用的是vant-weapp，所以抓取带有van类名的组件，将其列入px转换黑名单，其他的ui库应该同理，你试试看吧~有更好的方式欢迎交流

**Comment by TonyLiuYan** [comment]
@JazzOne   多谢回复
按照你的思路，我做了如下设置
```
        pxtransform: {
          enable: true,
          config: {
            selectorBlackList: ['i-']
          }
        },
```
基本上是可以用了，没有做全面测试
因为iview的组件基本都是`i-`开头，比如按钮：i-button，输入框：i-input

**Comment by luckyadam** [comment]
@TonyLiuYan 也可以通过在样式文件开头的地方加注释来忽略转换

**Comment by soymikey** [comment]
> **问题描述**
> 由于需求需要，需要在taro框架中引入第三方的UI组件iView Weapp，引入后可以正常使用，但是显示的样式和iView官方的显示不同，个别组件差异很大，请问框架目前是否兼容？
> 
> **复现步骤**
> 
> 1. iView官方快速上手地址：https://weapp.iviewui.com/docs/guide/start
> 2. 显示差异大的组件请参照：Gird，官方示例地址为：https://github.com/TalkingData/iview-weapp/tree/master/examples/pages/grid
> 
> **期望行为**
> 显示效果与iView官方一致

请教一下，button的click事件在taro里面怎么写呢?
