### ISSUE TITLE
使用vant-weapp的commonjs版本wxs依赖文件未拷贝到dist目录

### ISSUE THREAD

**Issue by huixisheng** [NervJS/taro#1472]
**问题描述**
![image](https://user-images.githubusercontent.com/1518967/49845616-5c7ebe80-fe02-11e8-9bb6-0c53d4b1fc73.png)

**复现步骤**
将`vant-weapp`打包成`commonjs`版本，引用`icon`组件

**期望行为**
正常运行

**系统信息**

 - Taro 版本 [1.2.0-beta.14]
 - 报错平台 [weapp]

**补充信息**
watch模式编辑器保存`common/utils.wxs`可以正常运行

**Comment by luckyadam** [comment]
wxs 文件没有处理，通过配置 copy 来解决

**Comment by YpchenLove** [comment]
我也遇到相同的问题，在微信小程序里src下组件里的wxs没有被copy到dist里的组件中~
![image](https://user-images.githubusercontent.com/26370242/53467354-dd0f9b80-3a90-11e9-856e-d10a0eb1fb98.png)
上图是src下的组件源码
下图是build后的组件代码，缺少了wxs部分。
![gfoku2jjto0 x 0 fmt y7](https://user-images.githubusercontent.com/26370242/53467423-27911800-3a91-11e9-884d-5903b7b9d40a.png)
希望taro团队能够支持微信小程序的这一特性~，3q~

**Comment by huixisheng** [comment]
临时解决方案
```
  copy: {
    patterns: [
      {
        from: 'src/libs/vant-weapp/dist/common/utils.wxs',
        to: 'dist/libs/vant-weapp/dist/common/utils.wxs',
      },
    ],
    options: {
    }
  },
```

```
   'pxtransform': {
          enable: true,
          config: {
            designWidth: 750,
            platform: 'weapp',
            selectorBlackList: [/^.van-.*?$/, /^.weui-.*?$/],
          },
        },
```
