### ISSUE TITLE
【postcss-pxtransform】 支持排除特定文件

### ISSUE THREAD

**Issue by sjfkai** [NervJS/taro#14722]
### 这个特性解决了什么问题？
目前仅支持通过修改文件内容（添加注释）的方式排除文件，无法直接排除如 node_modules 等文件。以至于在使用第三方组件库时无法完全排除整个模块。

### 这个 API 长什么样？
类似 [postcss-pxtorem](https://github.com/cuth/postcss-pxtorem)，可增加 exclude  配置，排除特定目录，例如：

```js
exclude: 'exclude',
exclude: /exclude/i,
exclude: (file) => file.indexOf('exclude') !== -1,
```

**Comment by Chen-jj** [comment]
看了一下现在应该是有 exclude 配置的：
![image](https://github.com/NervJS/taro/assets/11807297/4ca57521-eb94-46f3-b3a6-5abcacb108ee)
