### ISSUE TITLE
taro默认模版，编译H5运行后报错：Uncaught TypeError: e.on is not a function

### ISSUE THREAD

**Issue by doudou673** [NervJS/taro#14735]
### 相关平台
H5

**浏览器版本: Chorme 版本 118.0.5993.117（正式版本） (arm64)**
**使用框架: React**

### 复现步骤
taro init选择React，使用TS，Less，Webpack5，npm，Gitee，默认模版。然后在项目中运行npm run dev:h5，浏览器中F12切换h5设备，首次会显示页面，但是刷新一下就会报错，报错内容：

VM20239:10 Uncaught TypeError: e.on is not a function
    at l (<anonymous>:10:3333)
    at a (<anonymous>:10:3542)
    at <anonymous>:10:3914

### 期望结果
浏览器正常运行，刷新后不会报错

### 实际结果
首次会显示页面，但是刷新一下就会报错，报错内容：

VM20239:10 Uncaught TypeError: e.on is not a function
    at l (<anonymous>:10:3333)
    at a (<anonymous>:10:3542)
    at <anonymous>:10:3914

### 环境信息
```
👽 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/helper: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8 
      @tarojs/react: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/shared: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.1 => 3.1.1 
```

---
### 补充信息
node 14

**Comment by doudou673** [comment]
<img width="1301" alt="image" src="https://github.com/NervJS/taro/assets/54931067/08c984e5-9324-41c1-a78f-92c8d4f80ae2">

**Comment by ZakaryCode** [comment]
提供信息无法定位相关问题，可尝试进一步判断报错代码，或者尝试升级修复该问题
