### ISSUE TITLE
h5 navigateTo 跳转页面后，点浏览器返回按钮，然后点击下一页，页面错落

### ISSUE THREAD

**Issue by WFQX** [NervJS/taro#1473]
**问题描述**
h5在苹果手机中，触发浏览器默认返回操作，会出现多个页面重叠出现

**复现步骤**
[复现问题的步骤]
1.  navigateTo 跳转B页面
2. 点浏览器返回上一页 ，回到A页面
3. 点击浏览器下一页，回到B页面
4. navigateTo A页面

**期望行为**
只出现一个

**报错信息**
没有任何错误日志

**系统信息**

 - 操作系统: [iOS 12]
 - Taro 版本  1.1.9
 - Node.js 版本 [v10.11.0]
 - 报错平台 [h5]

**补充信息**
路由调整没有兼容浏览器点击返回下一页的情况

**Comment by luckyadam** [comment]
@WFQX 升级到最新的 beta 版本试试

**Comment by WFQX** [comment]
前几天升级到最新的beta，发现这个问题更加严重，1.1.9的页面设置了最小高度100%后，只要不触发iso的下一页是不会有问题的，但是最新的beta不触发也会出现

**Comment by Littly** [comment]
未复现。确认项目的taro依赖和cli都是最新版吗？
