### ISSUE TITLE
预加载this.$preloadData是undefined

### ISSUE THREAD

**Issue by zh28** [NervJS/taro#1476]
**问题描述**
componentWillMount 中获取不到this.$preloadData
打印出来是undefined

**复现步骤**
[复现问题的步骤]
例如：A页面跳转至B页面
* A页面简单跳转事件
```js
export default class A extends Component {
  config = {
    navigationBarTitleText: '首页'
  }
  click(param) {
    Taro.navigateTo({
      url: '/pages/preload/preload?url=hello'
    })
  }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <View onClick={this.click}>
          <Text>点击跳转</Text>
        </View>
      </View>
    )
  }
}
```

* B页面（就是文档里的例子）
```js
export default class B extends Component {
  constructor() {
    super(...arguments);
  }
  config = {
    navigationBarTitleText: '预加载页面'
  };
  componentWillMount () {
    console.log('isFetching: ', this.isFetching)
    this.$preloadData
      .then(res => {
        console.log('res: ', res)
        this.isFetching = false
      })
  }

  componentWillPreload (params) {
    return this.fetchData(params.url)
  }

  fetchData () {
    this.isFetching = true;
  }
  render() {
    return (
      <View className='container'>
           <Text>B页面</Text>
      </View>
    );
  }
}
```

**期望行为**
正常使用this.$preloadData获取到值

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/31911177/49854311-bdb78980-fe24-11e8-822d-194198616ed7.png)

**系统信息**

 - 操作系统: win10
 - Taro 版本
![image](https://user-images.githubusercontent.com/31911177/49854249-8ba62780-fe24-11e8-835b-3b59a3c2fe91.png)

 - Node.js 版本 
![image](https://user-images.githubusercontent.com/31911177/49854284-a6789c00-fe24-11e8-82d1-4ca7b7cb3da8.png)

 - 报错平台
weapp

**补充信息**

**Comment by luckyadam** [comment]
目测是由于 `fetchData`  没有返回数据，这个例子不是很完整，你可以在 `fetchData` 里返回一个 promise 试试

**Comment by zh28** [comment]
> 目测是由于 `fetchData` 没有返回数据，这个例子不是很完整，你可以在 `fetchData` 里返回一个 promise 试试

那建议可以修改一下文档的例子，我还以为返回的数据是taro自动封装到promise里面的呢
