### ISSUE TITLE
关于 API  chooseImage 与 chooseMedia 使用的疑问？

### ISSUE THREAD

**Issue by robinv8** [NervJS/taro#14772]
### 这个特性解决了什么问题？
由于微信小程序基础库从 2.21.0 版本开始废弃 chooseImage，用 ·chooseMedia 替代，但 chooseMedia 仅支持`微信小程序`、`H5`，`taro-ui` 图片选择器组件使用了 chooseImage，如果使用 chooseMedia，会影响其他小程序，现在如何处理？

### 这个 API 长什么样？
期望 chooseMedia 支持更多端

**Comment by TheKonka** [comment]
chooseImage 只说停止维护，没说不能用吧？我就还用的 chooseImage

**Comment by robinv8** [comment]
刚仔细看了，感谢
