### ISSUE TITLE
组件onShow 事件 在页面返回时未触发

### ISSUE THREAD

**Issue by juliazz** [NervJS/taro#14783]
### 相关平台
微信小程序

**小程序基础库: 2.26.0**
**使用框架: Vue 2**

### 复现步骤
页面调用 navigateBack时，返回页面的组件中的OnShow未触发，

  mounted(options){
    Monitor.hookApp(options)
    eventCenter.once(getCurrentInstance().router.onShow, () => {
      console.log('eventCenter.once  onShow page_view_start')
       this.onPageShow()
    })

  },
  beforeDestroy() {
    eventCenter.off(getCurrentInstance().router.onShow);
  },

### 期望结果
返回上一页时 ，返回后的页面中子组件onShow触发

### 实际结果
返回上一页时 ，返回后的页面中子组件onShow未触发

### 环境信息
```
👽 Taro v3.4.8

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

  Taro CLI 3.4.8 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/mini-runner: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.18 => 3.4.8 
      eslint-config-taro: 3.4.8 => 3.4.8 
```

**Comment by Chen-jj** [comment]
@juliazz 事件监听应该使用 `eventCenter.on` 而不是 `eventCenter.once`，后者只触发一次就会移除监听。感谢反馈，我们改一下文档~
