### ISSUE TITLE
使用taro3.4.14   vue3 编译成支付宝小程序，编译无报错，但在小程序开发者工具中报错

### ISSUE THREAD

**Issue by leung0727** [NervJS/taro#14781]
### 相关平台
支付宝小程序

### 复现仓库
[https://codeup.aliyun.com/6329340f4aae4ea05616f2c3/jinyuan/mall-weapp.git](https://codeup.aliyun.com/6329340f4aae4ea05616f2c3/jinyuan/mall-weapp.git)
**小程序基础库: 2**
**使用框架: Vue 3**

### 复现步骤
1.npm run dev:alipay
2.支付宝小程序开发者工具打开编译后的dist/alipay/ ，程序报错，页面出错

### 期望结果
小程序页面正常运行

### 实际结果
小程序开发者工具调试器中报错，页面不显示，报错如下：
error[Parse]: Unexpected character '`'
   --> vendors.js:83:0
  81 | /*! exports used: BaseTransition, Comment, EffectScope, Fragment, KeepAlive, ReactiveEffect, Static, Suspense, Teleport, Text, callWithAsyncErrorHandling, callWithErrorHandling, camelize, capitalize, cloneVNode, compatUtils, computed, createBlock, createCommentVNode, createElementBlock, createElementVNode, createHydrationRenderer, createPropsRestProxy, createRenderer, createSlots, createStaticVNode, createTextVNode, createVNode, customRef, defineAsyncComponent, defineComponent, defineEmits, defineExpose, defineProps, devtools, effect, effectScope, getCurrentInstance, getCurrentScope, getTransitionRawChildren, guardReactiveProps, h, handleError, initCustomFormatter, inject, isMemoSame, isProxy, isReactive, isReadonly, isRef, isRuntimeOnly, isShallow, isVNode, markRaw, mergeDefaults, mergeProps, nextTick, normalizeClass, normalizeProps, normalizeStyle, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onScopeDispose, onServerPrefetch, onUnmounted, onUpdated, openBlock, popScopeId, provide, proxyRefs, pushScopeId, queuePostFlushCb, reactive, readonly, ref, registerRuntimeCompiler, renderList, renderSlot, resolveComponent, resolveDirective, resolveDynamicComponent, resolveFilter, resolveTransitionHooks, setBlockTracking, setDevtoolsHook, setTransitionHooks, shallowReactive, shallowReadonly, shallowRef, ssrContextKey, ssrUtils, stop, toDisplayString, toHandlerKey, toHandlers, toRaw, toRef, toRefs, transformVNodeArgs, triggerRef, unref, useAttrs, useSSRContext, useSlots, useTransitionState, version, warn, watch, watchEffect, watchPostEffect, watchSyncEffect, withAsyncContext, withCtx, withDefaults, withDirectives, withMemo, withScopeId */function(e,so,ao){"use strict";!function(u,b,t){ao.d(so,"a",function(){return ot}),ao.d(so,"b",function(){return 

### 环境信息
```
👽 Taro v3.4.14

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

  Taro CLI 3.4.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\86131\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
你这个仓库不是公开的

**Comment by leung0727** [comment]
糟了，忘了是公司的仓库，我没权限...

**Comment by leung0727** [comment]
https://gitee.com/leung12/jinyuan.git 换了个仓库，能帮忙看看吗 @TheKonka

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/44921541-da28-4535-868e-e62d48ba3718)
这个删掉就正常了，还有就是 umtrack-wx 在支付宝用不了，也要删掉，还有你的版本都 太老了，建议升级到taro最新版

**Comment by leung0727** [comment]
好呢，我试试太感谢了
