### ISSUE TITLE
Taro.showModal 支付宝小程序中 "取消"按钮显示 undefined

### ISSUE THREAD

**Issue by kkerwin** [NervJS/taro#1479]
**问题描述**
Taro.showModal 支付宝小程序中， "取消"按钮显示 undefined

**复现步骤**
[复现问题的步骤]
支付宝小程序开发者工具中没有问题，但是在真机 ios、Android 上"取消"按钮均显示 undefined

[或者可以直接贴源代码，能贴文字就不要截图]![img_1572](https://user-images.githubusercontent.com/7856025/49858285-7d113d80-fe2f-11e8-8ab2-52ce78f792d0.PNG)

```js
Taro.showModal({title:'Taro.showModal'}

```

**期望行为**
显示“取消”

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [ Windows 10]
 - Taro 版本 [1.2.0-beta.14]
 - Node.js 版本 [8.11.1]
 - 报错平台 [alipay]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
```js
Taro.showModal({
  title:'Taro.showModal',
  cancelText: '取消'
})
```
试试这个

另外截图看下你的 package.json

**Comment by kkerwin** [comment]
加了
```js
cancelText: '取消'
```
就可以了。3Q!
...............................................................................................................................
![tim 20181213094144](https://user-images.githubusercontent.com/7856025/49909899-b42d3080-febb-11e8-8bf0-24ef2df8e3e1.png)

**Comment by kkerwin** [comment]
还有我还发现现在是不支持 ‘...’ 扩展运算符了？
![tim 20181213100402](https://user-images.githubusercontent.com/7856025/49910788-03c12b80-febf-11e8-8a78-3dce834458e4.png)
错误：
![tim 20181213100526](https://user-images.githubusercontent.com/7856025/49910840-2b17f880-febf-11e8-89ab-b0f391b02139.png)
使用
````
Object.assign() 
````
就没有问题，我记得以前是可以的啊...

**Comment by luckyadam** [comment]
我尝试了一下，支持呀
