### ISSUE TITLE
VirtualList 渲染异常（滚动时无法正常渲然）

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#14792]
### 相关平台
H5

### 复现仓库
[https://github.com/vdfor/taro-issue-demo-007.git](https://github.com/vdfor/taro-issue-demo-007.git)
**浏览器版本: Chrome 119**
**使用框架: React**

### 复现步骤
1. Taro脚手架创建项目
2. Taro 官网虚拟化列表基础示例Demo [链接](https://taro-docs.jd.com/docs/virtual-list#%E5%9F%BA%E7%A1%80%E7%A4%BA%E4%BE%8B)
3. 异常一：虚拟列表渲染异常；异常二：控制台警告（vendors-node_modules_taro_h5_prebundle_chunk-UIXIYJH6_js._chunkhash_.js:526  Warning: Each child in a list should have a unique "key" prop.）

### 期望结果
虚拟列表正常渲染

### 实际结果
虚拟列表渲染异常

### 环境信息
```
👽 Taro v3.6.18


  Taro CLI 3.6.18 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18 
      @tarojs/components: 3.6.18 => 3.6.18 
      @tarojs/helper: 3.6.18 => 3.6.18 
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18 
      @tarojs/react: 3.6.18 => 3.6.18 
      @tarojs/runtime: 3.6.18 => 3.6.18 
      @tarojs/shared: 3.6.18 => 3.6.18 
      @tarojs/taro: 3.6.18 => 3.6.18 
      @tarojs/taro-loader: 3.6.18 => 3.6.18 
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18 
      babel-preset-taro: 3.6.18 => 3.6.18 
      eslint-config-taro: 3.6.18 => 3.6.18 
      react: ^18.0.0 => 18.2.0 
```

---
### 补充信息
异常一是3.6.17对scrollView进行了调整导致的（已测试3.6.16没有异常一）

**Comment by ZakaryCode** [comment]
> 3\. 异常一：虚拟列表渲染异常；异常二：控制台警告（vendors-node_modules_taro_h5_prebundle_chunk-UIXIYJH6_js._chunkhash_.js:526  Warning: Each child in a list should have a unique "key" prop.）

异常二可忽略，异常一可以在 onScrollNative 中调用事件 stopImmediatePropagation 方法规避该问题，将在下一个版本中修复
