### ISSUE TITLE
是否可以在一个component里面定义一个函数类型的子component？

### ISSUE THREAD

**Issue by bernkastle** [NervJS/taro#148]
![image](https://user-images.githubusercontent.com/11273397/41592334-d4a60ad8-73ee-11e8-9131-609047acf75f.png)
类似于这样的一个component。
但是编译好像通不过。

**Comment by yuche** [comment]
不行，现在一个文件只能定义一个组件

**Comment by cgx9** [comment]
什么时候可以支持？
现在全新文件的子组件，render里map值给一个变量都不行，写起来有点痛苦。

**Comment by yuche** [comment]
使用 map 可以呀，怎么通不过能贴一下你的代码吗 @cgx9

**Comment by yuche** [comment]
Duplicate of #157
