### ISSUE TITLE
Taro v1.2.0-beta.13 中 npm run dev:weapp 直接报错

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#1480]
1. 将原生小程序编译成 taro，过程中没有出现问题；
2. 然后到 taroConvert 包中执行 `npm run dev:weapp` 直接报错。

报错截图：
![image](https://user-images.githubusercontent.com/25219300/49860956-c49ac800-fe35-11e8-82a5-4bc880f8fe1b.png)

node 版本： 
![image](https://user-images.githubusercontent.com/25219300/49861012-e8f6a480-fe35-11e8-8c49-9735d49ca037.png)

**Comment by patchBig** [comment]
`npm install` 直接报错了
![image](https://user-images.githubusercontent.com/25219300/49861267-71754500-fe36-11e8-96a9-37f2d69e0762.png)

**Comment by patchBig** [comment]
`npm install` 直接报错了

![image](https://user-images.githubusercontent.com/25219300/49861362-a1244d00-fe36-11e8-8b4b-a2da8a5a0a32.png)

**Comment by luckyadam** [comment]
项目依赖没有装好，建议换国内源安装

**Comment by patchBig** [comment]
导致的直接后果就是编译失败

![image](https://user-images.githubusercontent.com/25219300/49868222-b81f6b00-fe47-11e8-99a9-38bd7dd8b5cf.png)

**Comment by yuche** [comment]
@patchBig 
这是由于 wxParse 的源码使用了一个不存在的 template 声明造成的。文档里有解决方案
https://nervjs.github.io/taro/docs/taroize.html#转换-wxparse-报错不存在文件

**Comment by patchBig** [comment]
编译之后在开发工具里面看到：

![image](https://user-images.githubusercontent.com/25219300/49868568-ca4dd900-fe48-11e8-8b0c-89c6fc56de16.png)

在构建后项目目录：
![image](https://user-images.githubusercontent.com/25219300/49868732-47794e00-fe49-11e8-8ac0-b0f2a8fcbe19.png)

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/49868850-932bf780-fe49-11e8-8e65-a779142b1450.png)

**Comment by luckyadam** [comment]
重启下开发者工具试试

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/49872193-4c42ff80-fe53-11e8-91ec-4956cc1dd977.png)

**Comment by patchBig** [comment]
现在又报这个错误了。。。
```
taroConvert$ taro build --type weapp
👽 Taro v1.2.0-beta.14

开始编译项目 taroConvert
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.js
缺少npm包@tarojs/taro-weapp，开始安装...
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
缺少npm包@tarojs/plugin-uglifyjs，开始安装...
```

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/49914911-12630f00-fece-11e8-995d-11cb534d6625.png)
编译的时候发现压缩错误。。。
