### ISSUE TITLE
微信小程序WebView 的onLoad/onMessage 无效

### ISSUE THREAD

**Issue by paulloo** [NervJS/taro#14819]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:paulloo/webviewOnMessageBugShow.git](git@github.com:paulloo/webviewOnMessageBugShow.git)
**小程序基础库: 3.2.0**
**使用框架: React**

### 复现步骤
跳转webview地址后，不监听、
onLoad
onError
onMessage

### 期望结果
能监听到onLoad
onError
onMessage
![image](https://github.com/NervJS/taro/assets/32083925/9d0e68df-d846-4887-99fc-68c76d6b3077)

### 实际结果
监听不到onLoad
onError
onMessage

### 环境信息
```
Taro v3.6.18


  Taro CLI 3.6.18 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - D:\Program Files\nodejs\node.EXE 
      Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD 
      npm: 8.5.5 - D:\Program Files\nodejs\npm.CMD     
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18
      @tarojs/components: 3.6.18 => 3.6.18
react: ^18.0.0 => 18.2.0
```

**Comment by paulloo** [comment]
人为原因，非Taro问题:)

**Comment by Unremittingly** [comment]
兄弟你怎么解决的？我这也不行，我这是一个单独的代码很少的项目3.4版本的可以触发这几个函数，另外一个项目内容很多的3.6版本的没有触发，
