### ISSUE TITLE
VirtualList 对于vue框架不友好，Row组件不能传自定义参数

### ISSUE THREAD

**Issue by atdow** [NervJS/taro#14828]
### 这个特性解决了什么问题？
VirtualList 对于vue框架不友，Row组件不能传自定义参数，如果想要有自定义参数，需要使用jsx语法才能实现，能不能增加对vue template写法的兼容。

### 这个 API 长什么样？
增加对vue template写法的兼容，Row组件替换成slot等方式实现组件自定义参数而不是必须要使用jsx语法编写代码。

**Comment by ZakaryCode** [comment]
请仔细阅读虚拟列表文档 [Vue 示例](https://nervjs.github.io/taro-docs/docs/virtual-list)
