### ISSUE TITLE
警告  JS文件 ，没有被引用到，不会被编译？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1482]
修改 BlueTooth.js 后出现了这样的警告：
警告  JS文件    src/components/BlueTooth/BlueTooth.js 没有被引用到，不会被编译;
每次都要重新 npm run dev:weapp,后 修改的才会生效。
![image](https://user-images.githubusercontent.com/43346131/49862250-bbf7c100-fe38-11e8-97e0-7e5220dc0415.png)
![image](https://user-images.githubusercontent.com/43346131/49862318-e0539d80-fe38-11e8-9ac0-b92113b100a0.png)
 - 操作系统: [e.g.Mac]
 - Taro 版本 [e.g. v1.12
 - Node.js 版本 [e.g. v10.14]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
升级到最新版本试试

**Comment by shenghanqin** [comment]
@JoMartinezZhu 升级到最新版试试看。
