### ISSUE TITLE
分包页面开启skyline渲染，分包页面白屏

### ISSUE THREAD

**Issue by swordsman-coder** [NervJS/taro#14820]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/swordsman-coder/taro-skyline.git](https://github.com/swordsman-coder/taro-skyline.git)
**小程序基础库: 3.1.5**
**使用框架: React**

### 复现步骤
主包页面正常
分包页面不正常，白屏
使用原生小程序的skyline渲染，主包 分包页面都正常展示
原生demo：https://github.com/swordsman-coder/wx-skyline.git

### 期望结果
分包页面开启skyline渲染模式下，分包页面展示正常

### 实际结果
分包页面开启skyline渲染模式下，分包页面白屏

### 环境信息
```
👽 Taro v3.6.19


  Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18
      @tarojs/components: 3.6.18 => 3.6.18
      @tarojs/helper: 3.6.18 => 3.6.18
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18
      @tarojs/react: 3.6.18 => 3.6.18
      @tarojs/runtime: 3.6.18 => 3.6.18
      @tarojs/shared: 3.6.18 => 3.6.18
      @tarojs/taro: 3.6.18 => 3.6.18
      @tarojs/taro-loader: 3.6.18 => 3.6.18
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18
      babel-preset-taro: 3.6.18 => 3.6.18
      eslint-config-taro: 3.6.18 => 3.6.18
      react: ^18.0.0 => 18.2.0
```

**Comment by TheKonka** [comment]
试了一下，原生微信小程序也有同样问题，从基础库 3 开始

**Comment by swordsman-coder** [comment]
> 试了一下，原生微信小程序也有同样问题，从基础库 3 开始

![image](https://github.com/NervJS/taro/assets/16441180/10963a4c-6a2d-4569-9aed-3bbcf8a4bb30)

原生demo：https://github.com/swordsman-coder/wx-skyline.git
你使用下我的仓库，原生小程序是正常的

**Comment by TheKonka** [comment]
我没说清楚，原生小程序要在分包里面使用模版才会复现问题

**Comment by DAYDreamder** [comment]
这分包不支持skyline怎么整。。。
开局即结束

**Comment by swordsman-coder** [comment]
> 我没说清楚，原生小程序要在分包里面使用模版才会复现问题

ok 你说的是对的。 我刚才测试了下 分包下可以展示普通的view等，但是使用模板就不行了 但是taro都是使用的template。game over

**Comment by swordsman-coder** [comment]
> 这分包不支持skyline怎么整。。。 开局即结束

准确的说 是分包不支持template, 但是taro都是采用的template渲染这种模式，所以就g了

**Comment by ppyds** [comment]
开发者工具白屏，预览正常显示
   `text
 "@tarojs/react": "3.6.20",
    "@tarojs/runtime": "3.6.20",
    "@tarojs/shared": "3.6.20",
    "@tarojs/taro": "3.6.20",

`

**Comment by ppyds** [comment]
开发者工具白屏，预览正常显示
``` text
   "@tarojs/react": "3.6.20",
    "@tarojs/runtime": "3.6.20",
    "@tarojs/shared": "3.6.20",
    "@tarojs/taro": "3.6.20",
```

**Comment by jschyz** [comment]
用 Taro 开发， skyline 模式就 over 了- =

**Comment by DAYDreamder** [comment]
预览的确正常，不过每次开发者工具调试要把分包先放到主包里也太难受了

**Comment by swordsman-coder** [comment]
![image](https://github.com/NervJS/taro/assets/16441180/a7c9f7f8-fa21-4aed-8df1-82992f026b7f)
截止当前开发者工具更新后 使用正常
手机预览正常
issue关闭
