### ISSUE TITLE
关于 《组件》 在小程序的实现

### ISSUE THREAD

**Issue by JohnPion-Zhang** [NervJS/taro#1483]
**问题描述**
> 贵方关于小程序的实现，<组件>有其完整的生命周期么？也就是说taro实现的小程序组件，是**template**还是**component**?

**Comment by luckyadam** [comment]
基于原生组件

**Comment by JohnPion-Zhang** [comment]
谢谢解答，跟wepy的水货component不一样, 这样我就放心用了～
