### ISSUE TITLE
微信小程序 监听不到onTimeUpdate 事件

### ISSUE THREAD

**Issue by changyijie** [NervJS/taro#14833]
### 相关平台
微信小程序

**小程序基础库: 3.2.1**
**使用框架: React**

### 复现步骤
video组件绑定 onTimeUpdate事件

### 期望结果
可以检测到onTimeUpdate ,以方便自定义进度条

### 实际结果
监听不到onTimeUpdate 事件

### 环境信息
```
 Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.9.0 - E:\dev_env\nodejs\node.EXE
      Yarn: 1.22.18 - E:\dev_env\npm_global\yarn.CMD
      npm: 9.6.7 - E:\dev_env\nodejs\npm.CMD

```

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/5e265c18-56ad-4f0c-a28f-69b7c2e885b7)
![image](https://github.com/NervJS/taro/assets/22173084/f8d0ddb5-020a-44c6-8689-d339b07100e6)

最新版本实测可以

**Comment by changyijie** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/283046151-5e265c18-56ad-4f0c-a28f-69b7c2e885b7.png) ![image](https://user-images.githubusercontent.com/22173084/283046219-f8d0ddb5-020a-44c6-8689-d339b07100e6.png)
> 
> 最新版本实测可以

开发者工具可以监听到，使用真机调试监听不到。可以试试真机

**Comment by TheKonka** [comment]
![IMG_1225](https://github.com/NervJS/taro/assets/22173084/83167485-e22a-4ee5-8892-0084d3fc8b2a)
![image](https://github.com/NervJS/taro/assets/22173084/99f13db4-9dab-40d3-b1b3-54db07022816)
真机预览/调试 都监听到

**Comment by changyijie** [comment]
> ![IMG_1225](https://user-images.githubusercontent.com/22173084/283055305-83167485-e22a-4ee5-8892-0084d3fc8b2a.PNG) ![image](https://user-images.githubusercontent.com/22173084/283056171-99f13db4-9dab-40d3-b1b3-54db07022816.png) 真机预览/调试 都监听到

taro 什么版本呢，我是用 taro init 默认模板，还是监听不到。方便粘贴下配置不

![image](https://github.com/NervJS/taro/assets/31202798/09726ae0-1443-44be-abb2-12bdaaddcf25)

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/e518ea30-1f80-4772-90b3-b30d90570da2)
跟taro版本应该关系不大，我用的都是最新版

**Comment by changyijie** [comment]
> ![image](https://user-images.githubusercontent.com/22173084/283329942-e518ea30-1f80-4772-90b3-b30d90570da2.png) 跟taro版本应该关系不大，我用的都是最新版

那应该小程序问题了，我去小程序官方看看

**Comment by TheKonka** [comment]
嗯，可以用原生小程序试下
