### ISSUE TITLE
引用微信原生组件<share-element>并不生效，已使用@tarojs/plugin-inject 扩展了原生组件

### ISSUE THREAD

**Issue by fujiazhang** [NervJS/taro#14837]
### 相关平台
微信小程序

**小程序基础库: 3.1.1**
**使用框架: Vue 3**

### 复现步骤
config中 已按文档配置，但是实际编译中看到生效了，但是效果不工作。
期待是一个跨页面的组件飞跃的效果。

### 期望结果
正常使用

### 实际结果
not work

### 环境信息
```
� Taro v3.4.2

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.4.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Users\halo\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

![image](https://github.com/NervJS/taro/assets/11347639/9a126990-b89e-4fb7-9e13-20339405c724)
![image](https://github.com/NervJS/taro/assets/11347639/aba3afa2-f619-4bba-8537-e8a18928197c)
![image](https://github.com/NervJS/taro/assets/11347639/7649db9f-ffe7-4198-a94f-0200e1fe2fd7)

**Comment by TheKonka** [comment]
我的建议是你升级一下，taro 新版已经支持了
> 该组件需与 [page-container](https://developers.weixin.qq.com/miniprogram/dev/component/page-container.html) 组件结合使用

```js
import { PageContainer, ShareElement } from '@tarojs/components';
```

![image](https://github.com/NervJS/taro/assets/22173084/36809bfd-2545-44dc-825e-7ca942889a44)

**Comment by fujiazhang** [comment]
> Taro v3.4.2



> 我的建议是你升级一下，taro 新版已经支持了
> 
> > 该组件需与 [page-container](https://developers.weixin.qq.com/miniprogram/dev/component/page-container.html) 组件结合使用
> 
> ```js
> import { PageContainer, ShareElement } from '@tarojs/components';
> ```
> 
> ![image](https://user-images.githubusercontent.com/22173084/283039861-36809bfd-2545-44dc-825e-7ca942889a44.png)

你看清楚再给我close了啊！ 目前不支持的，你发的这个你是用react的版本的啊，我是用的vue, vue现在明确是不支持啊，我看其他issue是让自己用[@tarojs/plugin-inject 扩展了原生组件。
你看清楚再给我close了啊！

**Comment by fujiazhang** [comment]
@Chen-jj 你看清楚再给我close了啊！都tm没解决问题，你着急关个锤子啊关！

**Comment by Chen-jj** [comment]
> 我是用的vue, vue现在明确是不支持啊

@fujiazhang 是试的 Taro 最新版本么

**Comment by yoyo837** [comment]
issue里提供的信息是  Taro v3.4.2

**Comment by xuanzebin** [comment]
组件支持一般不会区分框架，react 可以使用，vue 同理应该也可以，建议先升级版本尝试，还有问题就麻烦提供最新版本的问题 demo

**Comment by Chen-jj** [comment]
> issue里提供的信息是 Taro v3.4.2

旧版本是没有办法的，inject 也不可以，因为这个组件太特殊，只能是 xml 里第一个节点。

只有最新版的 Taro 对这种特殊情况做了支持。我当时是使用 React 测试的，Vue 还没测过，但我想也是ok的

**Comment by TheKonka** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/share-element.html

没有看到你代码里面用 [page-container](https://developers.weixin.qq.com/miniprogram/dev/component/page-container.html)

**Comment by fujiazhang** [comment]
> > issue里提供的信息是 Taro v3.4.2
> 
> 旧版本是没有办法的，inject 也不可以，因为这个组件太特殊，只能是 xml 里第一个节点。
> 
> 只有最新版的 Taro 对这种特殊情况做了支持。我当时是使用 React 测试的，Vue 还没测过，但我想也是ok的

好的，谢谢您！ 祝你生活愉快

**Comment by parabolazz** [comment]
在 taoro-vue3 下，写的 key 属性会丢失，导致动画不生效

**Comment by TheKonka** [comment]
> 在 taoro-vue3 下，写的 key 属性会丢失，导致动画不生效（我使用的是 3.6.6）

用mapkey ,看我前面发的截图

**Comment by parabolazz** [comment]
> > 在 taoro-vue3 下，写的 key 属性会丢失，导致动画不生效（我使用的是 3.6.6）
> 
> 用mapkey ,看我前面发的截图

改用 mapkey 之后，编译后的结果里有key 了，但是没有触发动画效果，可以看下我的代码：
```

  <div @click="show = true" classz>
    <share-element
      mapkey="invite"
      class="invite"
      :duration="300"
      transform
    >
      <div class="home-invite-btn__title">发起坦白局</div>
    </share-element>
  </div>


    <page-container
      :show="show"
      :overlay="false"
      :duration="300"
      position="center"
    >
      <view class="screen screen2">
        <share-element mapkey="invite" class="invite" :duration="300" transform>
          <div class="home-invite-btn__title" @click="show = false">
            发起坦白局
          </div>
        </share-element>
      </view>
    </page-container>
```
<img width="762" alt="image" src="https://github.com/NervJS/taro/assets/17560446/14b0917e-7cce-41b8-89da-7ef93447ff18">
结果如图：
https://github.com/NervJS/taro/assets/17560446/afac6ca0-ddc0-499f-95d3-e131d0659588
编译后的代码如下：
<img width="324" alt="image" src="https://github.com/NervJS/taro/assets/17560446/07473da3-72ee-43cc-81e3-2131ec793bf5">

<img width="376" alt="image" src="https://github.com/NervJS/taro/assets/17560446/211c15ef-ec6e-4169-936e-7a805c836540">
可以帮忙看一下吗？

**Comment by TheKonka** [comment]
@parabolazz  看起来使用vue会有问题，同样代码我用react是有效果的
