### ISSUE TITLE
postcss-pxtransform希望添加一个exclude配置，来过滤例如node_modules里的所有文件

### ISSUE THREAD

**Issue by epicRipper** [NervJS/taro#14831]
### 这个特性解决了什么问题？
我在项目使用postcss-pxtransform和另一个组件库，组件库提供了一个keyframes动画效果，postcss-pxtransform会把keyframes里的px单位转化为rem，仅靠目前提供的selectorBlackList配置无法满足不转化组件库keyframes的需求

### 这个 API 长什么样？
* 希望添加一个exclude配置，支持传入正则路径，将路劲内的文件都过滤不转化为rem

**Comment by ZakaryCode** [comment]
Duplicate of #14722
