### ISSUE TITLE
支付宝小程序原生组件编译标签错误

### ISSUE THREAD

**Issue by lyboy2012** [NervJS/taro#14843]
### 相关平台
支付宝小程序

**小程序基础库: 2.9.4**
**使用框架: React**

### 复现步骤
支付宝小程序原生组件编译标签错误

### 期望结果
 <ali-slider
                min={0}
                max={8}
                step={1}
                value={voiceValue}
                activeColor="#FFC75DFF"
                backgroundColor="#dfdfdf"
                change={{ fn: changeVoice }}
                trackSize="10"
                handleSize="16"
              />

### 实际结果
 <ali-slidermin={0}
                max={8}
                step={1}
                value={voiceValue}
                activeColor="#FFC75DFF"
                backgroundColor="#dfdfdf"
                change={{ fn: changeVoice }}
                trackSize="10"
                handleSize="16"
              />

### 环境信息
```
Taro v3.6.19


  Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-react: 3.6.19 => 3.6.19 
      @tarojs/plugin-html: ^3.6.19 => 3.6.19 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/react: 3.6.19 => 3.6.19 
      @tarojs/router: 3.6.19 => 3.6.19 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19 
      react: ^18.0.0 => 18.2.0 
      taro-ui: ^3.1.0-beta.3 => 3.1.1 
```

---
### 补充信息
原生组件 <ali-slider min={0} 编译后变成 <ali-slidermin={0}

**Comment by chuandong77** [comment]
https://github.com/NervJS/taro/pull/14818
看样子已经修复了，还没发版
