### ISSUE TITLE
打包构建build:weapp碰到的偶发问题

### ISSUE THREAD

**Issue by huixisheng** [NervJS/taro#1485]
**问题描述**

报错1：
```
Expecting 'STRING','NUMBER','NULL','TRUE','FALSE','{','[', got EOF
  1 |
```
发现`app.js`, `app.json` 为空

报错2:

![image](https://user-images.githubusercontent.com/1518967/49865626-7212d900-fe40-11e8-8f3b-d86986f202fb.png)

报错3:

![image](https://user-images.githubusercontent.com/1518967/49865913-2b71ae80-fe41-11e8-895e-7ba9e9b4be39.png)

**复现步骤**
处于偶发，目前是重新构建2次后报错都会消失

**系统信息**
`1.2.0-beta.14`

**补充信息**

并没有找到必现的场景。但打包过程中出现描述中的问题次数还是比较多。

**Comment by luckyadam** [comment]
微信开发者工具升级到最新版本

**Comment by huixisheng** [comment]
微信开发者工具是最新版本，重启微信开发者工具报错会消失。

**Comment by Chen-jj** [comment]
属于开发者工具的问题，点击重新编译或关闭重开。

**Comment by tss0823** [comment]
升级最新，解决了
