### ISSUE TITLE
picker-view 添加 选中样式无效 

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1486]
pickerView 这个 indicatorStyle属性值 中添加 如下值，却无效。

![image](https://user-images.githubusercontent.com/43346131/49866445-c6b75380-fe42-11e8-9127-408a757f8f28.png)

![image](https://user-images.githubusercontent.com/43346131/49866385-9b346900-fe42-11e8-9709-c538c2ccee49.png)

- 操作系统: [e.g.Mac]
 - Taro 版本 [e.g. v.1.12]
 - Node.js 版本 [e.g. v10.14]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
你试试原生可不可以
