### ISSUE TITLE
taro.js 将组件作为函数参数传递

### ISSUE THREAD

**Issue by xcs-go** [NervJS/taro#1487]
taro.js是不是可以像react一样将组件作为函数参数进行传递呢?

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/children.html#docsNav

**Comment by xcs-go** [comment]
按照这个文档的意思我就是不能将组件作为函数的参数传递了？
例如：import A from 'xcxx';
           fn(<A/>)
这样会报错jsEnginScriptError
Component is not found in path "components...

**Comment by yuche** [comment]
现在还不能

**Comment by xcs-go** [comment]
@yuche 好的。谢谢。期待该功能的实现
