### ISSUE TITLE
Taro react build:h5 页面白屏打不开  Invalid or unexpected token

### ISSUE THREAD

**Issue by JanYork** [NervJS/taro#14876]
### 相关平台
H5

**浏览器版本: 最新版本Chrome 和 Edge**
**使用框架: React**

### 复现步骤
我不知原因无法重现问题，这个问题只在我当前项目出现，存在默认配置：
``` 
compiler: {
    type: 'webpack5',
    prebundle: {
      enable: false
    },
  },
``` 
将其修改为如下配置后，打包页面可见，NutUI的ico丢失样式，变为不可见：
```
prebundle: {
      enable: false
    },
```
此操作能解决页面白屏(报错：Invalid or unexpected token 并且路由url停留在index.html)的问题，但是我不知到为什么需要开启这个才行！此为问题1.

问题2是，修改配置后，页面虽然可以渲染，但是，NutUI的所有ico组件全部不显示了，初步判断是样式丢失。

问题3，当我将如下配置：
```
router: {
      mode: 'hash', // 或者是 'browser'
    },
```
修改为：
```
router: {
      mode: 'browser', 
    },
```
此时build:h5同样白屏打不开，并且路由停留在 index.html.

问题1无法重现的原因是，项目内容过多我无法判断是因为什么导致的，无法去复现。

问题2我已经复现，最新的Taro脚手架构建NutUI模版新项目，只是修改了如下配置：
```
compiler: {
    type: 'webpack5',
    prebundle: {
      enable: true,
    },
  },
```
将enable值改为 true后，NutUI的ico组件全部丢失(不可见)。

问题3只是路由配置，无关紧要，只不过这是个问题我一并反馈。

问题1和2是我目前查阅文档与翻阅taro github 仓库任未解决的，并且问题1和2存在某些关联。

注：这些问题，均只在build后的代码出现，在dev:h5所有均为正常，如果开发环境和build后源码有如此影响的差异，我觉得这让我使用Taro开发是很不放心的，dev正常，编译后出错，这真的很让人崩溃，感觉当时选择使用taro构建项目像是一个错误的决定。

### 期望结果
与dev:h5运行后的情况一样正常。

### 实际结果
第一种情况 build:h5后，页面打不开 / 第二种情况 是ico丢失

### 环境信息
```
👽 Taro v3.6.17


  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
```

---
### 补充信息
项目使用了tailwindcss

**Comment by ZakaryCode** [comment]
仅上述信息无法进一步定位问题，需补充相关示例用于定位

> 另外关于问题2，prebundle 模式下对于字体文件支持还需进一步适配，目前建议 exclude 相关依赖
