### ISSUE TITLE
组件所在文件命名问题，不能使用`xxx.component.tsx`

### ISSUE THREAD

**Issue by lovesora** [NervJS/taro#149]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions

```
OS: darwin x64
Node: v8.11.2
Npm: v5.6.0
Yarn: v1.7.0
Taro: 0.0.40
```

### Repro steps
1. 创建文件`comp.component.tsx`
2. 导入
```tsx
import Comp from 'components/comp.component';
```
3. 使用
```tsx
<Comp/>
```
4. 无渲染结果

### Desired functionality
看dist文件夹里comp的文件名仍然是`comp.component.js`，但是引用的路径名变成了`comp.js`，怀疑是后缀解析的时候有些问题

**Comment by luckyadam** [comment]
收到，确实会有问题， `components/comp.component` 这样写的话，后缀被处理成 `.component` 了~ 我修复下~

**Comment by luckyadam** [comment]
最新的 beta 版本已经解决了这个问题 b68b983e8ed469d2dcc25fdccfd5893c65bcae23
