### ISSUE TITLE
支持小程序的 worklet 类型函数定义

### ISSUE THREAD

**Issue by Char-set** [NervJS/taro#14902]
### 这个特性解决了什么问题？
微信小程序skyline渲染引擎，自定义路由功能需要用到该类型函数

官方定义【自定义路由】：https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/custom-route.html

worklet 类型函数：https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/worklet.html#worklet-%E5%87%BD%E6%95%B0%E5%AE%9A%E4%B9%89

### 这个 API 长什么样？
```js
function helloWorklet() {
    'worklet'; //'worklet'声明该函数为work函数，可以在js线程和UI线程中调用
    console.log('hello worklet');
}

useEffect(() => {
        wx.worklet.runOnUI(helloWorklet)();
}, []);
```

目前会报警告 ：“The parameter to runOnUI should be a worklet function”

同时 helloWorklet 函数 并不是  worklet 类型

**Comment by wangjq4214** [comment]
请问现在支持了吗？

**Comment by codedart2018** [comment]
> ```js
> function helloWorklet() {
>     'worklet'; //'worklet'声明该函数为work函数，可以在js线程和UI线程中调用
>     console.log('hello worklet');
> }
> 
> useEffect(() => {
>         wx.worklet.runOnUI(helloWorklet)();
> }, []);
> ```

我的3.20版本可用，没报错

**Comment by Luobinf** [comment]
> ```js
>  'worklet'
> ```



> > ```js
> > function helloWorklet() {
> >     'worklet'; //'worklet'声明该函数为work函数，可以在js线程和UI线程中调用
> >     console.log('hello worklet');
> > }
> > 
> > useEffect(() => {
> >         wx.worklet.runOnUI(helloWorklet)();
> > }, []);
> > ```
> 
> 我的3.20版本可用，没报错

 'worklet' 字符串在生产环境中打包，会被terser-webpack-plugin插件给干掉，你是如何保留的啊

**Comment by lfxiui** [comment]
> > ```js
> >  'worklet'
> > ```
> 
> > > ```js
> > > function helloWorklet() {
> > >     'worklet'; //'worklet'声明该函数为work函数，可以在js线程和UI线程中调用
> > >     console.log('hello worklet');
> > > }
> > > 
> > > useEffect(() => {
> > >         wx.worklet.runOnUI(helloWorklet)();
> > > }, []);
> > > ```
> > 
> > 
> > 我的3.20版本可用，没报错
> 
> 'worklet' 字符串在生产环境中打包，会被terser-webpack-plugin插件给干掉，你是如何保留的啊

在编译后的代码里手动加😂

**Comment by tutuxxx** [comment]
terser: {
      enable: true,
      config: {
        compress: {
          directives: false,
        }
      },
    },

**Comment by tutuxxx** [comment]
4.0.8起已默认支持
