### ISSUE TITLE
taro组件开发脚手架

### ISSUE THREAD

**Issue by amibug** [NervJS/taro#14905]
### 这个特性解决了什么问题？
请教taro官方是否提供taro UI组件开发脚手架，类似web端dumi包含不限于以下功能
1. 组件demo调试
2. 文档生成功能
3. 必要的lint最佳规范

### 这个 API 长什么样？
类似web端dumi
https://d.umijs.org/guide

**Comment by ZakaryCode** [comment]
Duplicate of #13103

**Comment by amibug** [comment]
找不到官网的带demo调试的组件开发脚手架，先参考 https://github.com/AntmJS/vantui 的项目结构
