### ISSUE TITLE
【混合开发】 Taro 组件编译为原生自定义组件引用失败

### ISSUE THREAD

**Issue by AnthonyHao** [NervJS/taro#14913]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:AnthonyHao/Taro-snippet.git](git@github.com:AnthonyHao/Taro-snippet.git)
**小程序基础库: 2.21.4**
**使用框架: React**

### 复现步骤
1. `cd components`
2. `npm i && npm run build:components`
3. 把miniapp导入到微信开发者工具
4. 在`miniapp/pages/index`文件夹中，把index.json和index.wxml 中的`icon`注释掉，可以正常显示。

### 期望结果
可以显示

### 实际结果
报错。
页面【component/comp］错误：
TypeError: runtime
is not a function
at webpackJsonpCallback (web pack  runtime json chunk loading: 36)

### 环境信息
```
Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      npm: 10.2.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
```

**Comment by AnthonyHao** [comment]
<img width="786" alt="Screenshot 2023-11-30 at 10 02 22" src="https://github.com/NervJS/taro/assets/9319975/370f5c06-10d9-4f7d-bff8-bd227da3da84">
<img width="734" alt="Screenshot 2023-11-30 at 10 03 14" src="https://github.com/NervJS/taro/assets/9319975/cc706d0e-01b7-448e-b3fe-5950202414ef">

**Comment by AnthonyHao** [comment]
把Taro官方提供的`taro-project`跟最新的生成的模版比了一下，发现`taro-project`中使用的的是webpack4的。重新生成了一个`compiler: 'webpack4'`的新项目（test-components）。打包引用在miniapp中，可以在page的结构中看到这个节点，但是`#shadow-root`无法展开。看截图有warn
<img width="784" alt="Screenshot 2023-11-30 at 16 48 54" src="https://github.com/NervJS/taro/assets/9319975/6117b43f-bf60-4750-9295-d220861df195">

<img width="362" alt="Screenshot 2023-11-30 at 16 48 46" src="https://github.com/NervJS/taro/assets/9319975/40ccf830-d87c-4c66-88cc-1c6c3c5c1260">

**Comment by xuanzebin** [comment]
报错的原因是 webpack 的 jsonpid 冲突了，参考：https://docs.taro.zone/docs/taro-in-miniapp#%E6%8A%8A-taro-%E9%A1%B9%E7%9B%AE%E6%8B%86%E5%88%86%E5%88%B0%E5%A4%9A%E4%B8%AA%E5%88%86%E5%8C%85

这里需要注意的是，demo 项目中使用的是 webpack 5，webpack 5 已经将 `output. jsonpFunction` 这个属性改为 `output.chunkLoadingGlobal`，所以如果你的项目是 webpack 4，就按照上述文档对 component 原生自定义组件项目的 jsonpid 进行修改，如果是 webpack 5，则需要另外将文档中的 `jsonpFunction` 属性改为 `chunkLoadingGlobal`。

**Comment by AnthonyHao** [comment]
> 报错的原因是 webpack 的 jsonpid 冲突了，参考：https://docs.taro.zone/docs/taro-in-miniapp#%E6%8A%8A-taro-%E9%A1%B9%E7%9B%AE%E6%8B%86%E5%88%86%E5%88%B0%E5%A4%9A%E4%B8%AA%E5%88%86%E5%8C%85
> 
> 这里需要注意的是，demo 项目中使用的是 webpack 5，webpack 5 已经将 `output. jsonpFunction` 这个属性改为 `output.chunkLoadingGlobal`，所以如果你的项目是 webpack 4，就按照上述文档对 component 原生自定义组件项目的 jsonpid 进行修改，如果是 webpack 5，则需要另外将文档中的 `jsonpFunction` 属性改为 `chunkLoadingGlobal`。

感谢，我又试了一下，然后想问两个问题

1. Taro编写的组件方法，如果想要改变原生小程序页面的`data` 应该怎么写。试了试直接在`props.onMyEvent`中`setData`好像不太行，
```
data: {
    motto: 'Hello World',
    userInfo: {},
    hasUserInfo: false,
    canIUse: wx.canIUse('button.open-type.getUserInfo'),
    pickerProps: {
      title: 'test',
      list: ['A', 'B', 'C'],
      onMyEvent () {
        this.setData({
          motto: 'hello'
        })
      }
    }
  }
```
2.  https://docs.taro.zone/docs/taro-in-miniapp/#%E6%A8%A1%E5%BC%8F%E4%BB%8B%E7%BB%8D 说 **以往使用taro build native-components 命令编译的自定义组件会额外包含一套Taro运行时，而这个特性可以帮助你在编译原生自定义组件的同时与taro页面共享同一套运行时代码，避免了两套运行时导致包体增大的问题。通过这种优化，我们能够更加高效地使用混合模式，并减少包体积的增长。** 这个如何处理？

不过问题一比较要紧，可以解释一下吗？

**Comment by AnthonyHao** [comment]
我试了试在`onLoad`里面加，看着可行。感觉用Taro组件同时给Taro和原生小程序提供，还是有点麻烦。
```
onLoad() {
  this.setDate({
    'pickerProps.onMyEvent': this.handleFunc
  })
},

handleFunc() {
   //todo
}
```
