### ISSUE TITLE
taro H5 构建 js 目录除了 app.js 以外的 xx.js 如何配置不再生产（合并到app.js）里

### ISSUE THREAD

**Issue by lishengzxc** [NervJS/taro#14926]
### Discussed in https://github.com/NervJS/taro/discussions/14924

<div type='discussions-op-text'>

<sup>Originally posted by **lishengzxc** December  4, 2023</sup>
taro H5 构建 js 目录除了 app.js 以外的 xx.js 如何配置不再生产（合并到app.js）里 或者将 xx.js 的构建出的文件名固定？

![image](https://github.com/NervJS/taro/assets/12003270/86ee5060-86ee-4e11-9d82-bcff8b3e2553)
![image](https://github.com/NervJS/taro/assets/12003270/8b99df24-bfaf-4b14-a95b-56a8f12f151e)

看了下 855.js 里的内容 好像是 taro View Button Text... 这些组件的实现？

![image](https://github.com/NervJS/taro/assets/12003270/7f891af3-0d75-49f5-82f4-e20f5efe7c8c)
</div>

**Comment by ZakaryCode** [comment]
这并非一个 issue，将回到 discussions 讨论
