### ISSUE TITLE
如何知道来源页面

### ISSUE THREAD

**Issue by hyacinthus** [NervJS/taro#1494]
如果重复提问了不好意思，github 的 issue 搜中文几乎没法搜，翻了半天没翻到。

我想知道当前页面是从哪个页面点过来的。用来智能的防止超过10层跳转。

在 wepy 里边可以通过默认的 payload data 里的 from 字段得到。

Taro 里有没有办法呢。

**Comment by nyrf** [comment]
使用 Taro.getCurrentPages()

**Comment by hyacinthus** [comment]
@nyrf 谢谢 确实是可以取到的。。
```js
    let pages = Taro.getCurrentPages()
    console.log(pages)
    if (pages.length > 1 && pages[pages.length - 2].route === 'pages/index') {
      console.log('from index,and back.')
      Taro.navigateBack()
      return
    }
```

但是这样也未免太麻烦了……
而且整个页面的数据太多了，我只看到了route，没有找到类的名字之类的更好写的标志。

不知道有没有像 wepy 那样的快捷方式。

**Comment by nyrf** [comment]
这个好像现在没有，你可自己写成一个方法，然后直接在需要的页面调用，也是可以的，wepy只是帮你把这个方法写好了。

**Comment by hyacinthus** [comment]
嗯 我现在是可以用的
如果常用的话可以考虑放 $router 里就相当方便了，比如
```js
if (this.$router.source === 'Index') {...}
```

顺便说下我的使用场景是这样，看看有没有更好的做法：

我的详情页面有可能是扫码，分享点进来的。我在详情页面的最底端会放回到首页的按钮，如果判断是从列表过来的，我就会调用返回，如果判断是从其他地方过来的，我就会调用 navigate ，这样页面不会爆栈。。

**Comment by luckyadam** [comment]
可以改进一下~

**Comment by shenghanqin** [comment]
我还见过把页面监控的方法监控起来，超过10级就用自定义的方式来实现跳转。效果还行。
