### ISSUE TITLE
3.6.8项目初始化项目依赖问题

### ISSUE THREAD

**Issue by BinCaoder** [NervJS/taro#14952]
### 相关平台
微信小程序

**小程序基础库: 3.2.3**
**使用框架: React**

### 复现步骤
? 请输入项目介绍 myapp
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 npm
? 请选择模板源 Gitee（最快）
√ 拉取远程模板仓库成功！
? 请选择模板 taro-ui（使用 taro-ui 的模板）
√ cd myapp, 执行 git init
‼ npm ERR!
‼ code ERESOLVE
‼ npm ERR!
‼  ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myapp@1.0.0
npm ERR! Found: @tarojs/plugin-platform-alipay@3.6.5
npm ERR! node_modules/@tarojs/plugin-platform-alipay
npm ERR!   @tarojs/plugin-platform-alipay@"3.6.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @tarojs/plugin-platform-alipay@"3.6.6" from taro-ui@3.2.0
npm ERR! node_modules/taro-ui
npm ERR!   taro-ui@"^3.1.0-beta.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

× 安装项目依赖失败，请自行重新安装！
Error: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myapp@1.0.0
npm ERR! Found: @tarojs/plugin-platform-alipay@3.6.5
npm ERR! node_modules/@tarojs/plugin-platform-alipay
npm ERR!   @tarojs/plugin-platform-alipay@"3.6.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @tarojs/plugin-platform-alipay@"3.6.6" from taro-ui@3.2.0
npm ERR! node_modules/taro-ui
npm ERR!   taro-ui@"^3.1.0-beta.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

### 期望结果
无报错

### 实际结果
依赖关系有误

### 环境信息
```
 Taro CLI 3.6.20 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by BinCaoder** [comment]
![Snipaste_2023-12-11_14-20-51](https://github.com/NervJS/taro/assets/121651233/b610adbf-b407-4166-ba23-5b4943ce1a5a)

**Comment by TheKonka** [comment]
#14954
