### ISSUE TITLE
tabbar默认不显示了吗？？

### ISSUE THREAD

**Issue by SmallRuralDog** [NervJS/taro#1496]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
你没有设置就不显示

**Comment by SmallRuralDog** [comment]
app.tsx里面设置了，代码里面是隐藏的
![image](https://user-images.githubusercontent.com/5151848/49927973-215fb680-fefa-11e8-83b9-0dd7b951ac81.png)
@yuche

**Comment by SmallRuralDog** [comment]
首页是 /pages/index

**Comment by yuche** [comment]
你这是在 h5 上吗

**Comment by SmallRuralDog** [comment]
首页是/pages/index。单url为/可以正常显示，为/pages/index时 刷新就不显示了。h5的

**Comment by yuche** [comment]
你能不能在一开始发 issue 的时候把模板的东西填上，我问你一句答一句不知道要到什么时候才问到问题的关键
