### ISSUE TITLE
Taro.navigateBack(版本>=3.6.16)在当前页面回退时，无法读取浏览器页面栈返回上一页，而是重复刷新当前页面

### ISSUE THREAD

**Issue by isabelke** [NervJS/taro#14965]
### 这个特性解决了什么问题？
无法回退的问题，复现步骤：从A页面跳转到B页面，在B页面点击按钮执行Taro.navigateBack，发现并未返回A页面，而是在当前页面刷新

### 这个 API 长什么样？
希望能返回上一页，而不是刷新当前页面

**Comment by ZakaryCode** [comment]
请补充问题相关信息，包括使用框架（React、Vue……）、平台（h5、weapp、rn……）、复现用例、错误录屏等

**Comment by Lmm240336783** [comment]
3.6.21 版本复现

**Comment by Lmm240336783** [comment]
有什么解决办法吗？
