### ISSUE TITLE
环境变量TARO_APP_ID无效

### ISSUE THREAD

**Issue by Linxiaoxxx** [NervJS/taro#14979]
### 相关平台
微信小程序

**小程序基础库: 3.1.1**
**使用框架: React**

### 复现步骤

在.env.development 和 .env.production 文件分别配置 TARO_APP_ID="wxc...."
使用npm run build:weapp 无效从开发环境的appid切换为生产环境的

### 期望结果
可以根据环境正常切换

### 实际结果
无法根据环境切换

### 环境信息
```
Taro CLI 3.6.16 environment info:
    System:
      OS: Windows 10 10.0.19045    
    Binaries:
      Node: 18.0.0 - ~\AppData\Local\Temp\yarn--1702441244198-0.6516858049189154\node.CMD
      Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1702441244198-0.6516858049189154\yarn.CMD
      npm: 8.6.0 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.16 => 3.6.16
      @tarojs/components: 3.6.16 => 3.6.16
      @tarojs/helper: 3.6.16 => 3.6.16
      @tarojs/plugin-framework-react: 3.6.16 => 3.6.16
      @tarojs/plugin-html: ^3.6.16 => 3.6.16
      @tarojs/plugin-platform-alipay: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-h5: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-jd: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-qq: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-swan: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-tt: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-weapp: 3.6.16 => 3.6.16
      @tarojs/react: 3.6.16 => 3.6.16
      @tarojs/runtime: 3.6.16 => 3.6.16
      @tarojs/shared: 3.6.16 => 3.6.16
      @tarojs/taro: 3.6.16 => 3.6.16
      @tarojs/taro-loader: 3.6.16 => 3.6.16
      @tarojs/webpack5-runner: 3.6.16 => 3.6.16
      babel-preset-taro: 3.6.16 => 3.6.16
      eslint-config-taro: 3.6.16 => 3.6.16
      react: ^18.0.0 => 18.2.0
```

**Comment by bigmeow** [comment]
详细提供一下 `package.json` 的 `scripts` 看看

**Comment by CanonLs** [comment]
@bigmeow 这是我的配置麻烦帮忙看一下我的
`"scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "taro build --type weapp --watch --env production",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch",
    "test": "jest"
  },`

**Comment by CanonLs** [comment]
@bigmeow 帮忙看一下我的问题，以下是我的配置
"scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "taro build --type weapp --watch --env production",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch",
    "test": "jest"
  },

**Comment by CanonLs** [comment]
@bigmeow 并且还有热重载无效，不能实时更新小程序开发工具控制台输出了Page loaded但是页面内容并没有更新

**Comment by Madou-Shinni** [comment]
> ### 相关平台
> 微信小程序
> 
> **小程序基础库: 3.1.1** **使用框架: React**
> 
> ### 复现步骤
> 在.env.development 和 .env.production 文件分别配置 TARO_APP_ID="wxc...." 使用npm run build:weapp 无效从开发环境的appid切换为生产环境的
> 
> ### 期望结果
> 可以根据环境正常切换
> 
> ### 实际结果
> 无法根据环境切换
> 
> ### 环境信息
> ```
> Taro CLI 3.6.16 environment info:
>     System:
>       OS: Windows 10 10.0.19045    
>     Binaries:
>       Node: 18.0.0 - ~\AppData\Local\Temp\yarn--1702441244198-0.6516858049189154\node.CMD
>       Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1702441244198-0.6516858049189154\yarn.CMD
>       npm: 8.6.0 - D:\nodejs\npm.CMD
>     npmPackages:
>       @tarojs/cli: 3.6.16 => 3.6.16
>       @tarojs/components: 3.6.16 => 3.6.16
>       @tarojs/helper: 3.6.16 => 3.6.16
>       @tarojs/plugin-framework-react: 3.6.16 => 3.6.16
>       @tarojs/plugin-html: ^3.6.16 => 3.6.16
>       @tarojs/plugin-platform-alipay: 3.6.16 => 3.6.16
>       @tarojs/plugin-platform-h5: 3.6.16 => 3.6.16
>       @tarojs/plugin-platform-jd: 3.6.16 => 3.6.16
>       @tarojs/plugin-platform-qq: 3.6.16 => 3.6.16
>       @tarojs/plugin-platform-swan: 3.6.16 => 3.6.16
>       @tarojs/plugin-platform-tt: 3.6.16 => 3.6.16
>       @tarojs/plugin-platform-weapp: 3.6.16 => 3.6.16
>       @tarojs/react: 3.6.16 => 3.6.16
>       @tarojs/runtime: 3.6.16 => 3.6.16
>       @tarojs/shared: 3.6.16 => 3.6.16
>       @tarojs/taro: 3.6.16 => 3.6.16
>       @tarojs/taro-loader: 3.6.16 => 3.6.16
>       @tarojs/webpack5-runner: 3.6.16 => 3.6.16
>       babel-preset-taro: 3.6.16 => 3.6.16
>       eslint-config-taro: 3.6.16 => 3.6.16
>       react: ^18.0.0 => 18.2.0
> ```

我和你遇到了一样的问题，很遗憾taro init xxx 拉取的脚手架之中无法让你在开发环境获取环境变量

这里需要**手动修改**启动命令

> 这是我的目录，你可以看到我的三个env文件

![image](https://github.com/NervJS/taro/assets/91399492/b09521d0-b59f-4eec-9fdc-fb1ad7288059)

> 我在微信小程序开发环境中**手动修改**了启动命令
> 添加了 `--mode dev`

![image](https://github.com/NervJS/taro/assets/91399492/7bdce406-c85e-492f-81b6-45c7bfde1f80)

最后我成功实现了获取

![image](https://github.com/NervJS/taro/assets/91399492/668d7e2a-b6a5-4329-bb2c-a952de8b5b99)

**Comment by videni** [comment]
同样的问题，到底怎么解决的呢？ @Linxiaoxxx  @bigmeow

**Comment by anyesu** [comment]
> 同样的问题，到底怎么解决的呢？ @Linxiaoxxx @bigmeow

环境变量配置文件的文件名按下面这样改：

```
.env.dev -> .env.development
.env.prod -> .env.production
```

命令中 `--mode xxx` 读取的配置文件就是 `.env.xxx` 文件：

- https://github.com/NervJS/taro/blob/ba270098fe8a7ebdfd12d92d5922dbda93f393de/packages/taro-cli/src/presets/commands/build.ts#L112
- https://github.com/NervJS/taro/blob/ba270098fe8a7ebdfd12d92d5922dbda93f393de/packages/taro-helper/src/dotenv.ts#L21-L24
