### ISSUE TITLE
请教下 有没有兼容原生小程序的配置方案？

### ISSUE THREAD

**Issue by SaiyanGuo** [NervJS/taro#150]
之前的业务都是原生小程序写的，现在新需求想用taro开发，新老需求耦合度不高，有没有一些兼容的配置方案呢？

**Comment by isting** [comment]
同样的想法，正在重构

**Comment by Lizhooh** [comment]
很难，可以基本没有，因为 Taro 还要兼容 H5。

**Comment by cangku** [comment]
如果分离一个类似 `mpvue-simple` 的模块出来也是可以和老项目并用的，可以平滑过度到 `taro`。

**Comment by luckyadam** [comment]
最新的 beta 版本已经支持了
https://nervjs.github.io/taro/wx-third-party.html
https://nervjs.github.io/taro/wx-hybrid.html
