### ISSUE TITLE
Taro.setStorageSync(key, data)在IOS17里webview设置缓存无效

### ISSUE THREAD

**Issue by wxy123** [NervJS/taro#15011]
### 相关平台
H5

**浏览器版本: Safari 17****小程序基础库: H5**
**使用框架: React**

### 复现步骤
无

### 期望结果
设置缓存成功

### 实际结果
设置缓存失败

### 环境信息
```
 Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.18.1 - E:\installdSoft\nvm\nodejs\node.EXE
      npm: 8.19.2 - E:\installdSoft\nvm\nodejs\npm.CMD
```

---
### 补充信息
H5应用在使用Taro.setStorageSync(key, data)缓存数据时候，在IOS17中，webview里看不到缓存的数据

**Comment by TheKonka** [comment]
不会吧，Taro.setStorageSync(key, data) 在 h5 也只是调用了localStorage.setItem 方法，我没有  ios 17的设备不好测试，但是我试了 taro最新版本在 ios 15下是正常的， 你确定是 setStorageSync + IOS17 的问题吗？如果真的有问题应该很多人反馈， 我看你  Taro CLI 版本是 3.3.19，太老了，不确定是不是因为taro版本的问题，建议你有空升级一下
