### ISSUE TITLE
[Feature request] Taro component support custom props when rendering h5 doms

### ISSUE THREAD

**Issue by mengxy** [NervJS/taro#1501]
Currently custom props assigned to Taro components are omitted. But we need some dom element support custom props, such as "data-growing-container" for [GrowingIO integration](https://docs.growingio.com/docs/sdk-integration/web-js-sdk/#31container).

```html
<div id="1" data-growing-container>
  <div id="2">
    <h1 id="3">商品名称</h1>
  </div>
  <div id="4">
    <div id="5">商品图片</div>
  </div>
  <div id="6">
    <div id="7">商品描述</div>
  </div>
</div>
```
Please consider this feature, thanks.

**Comment by mengxy** [comment]
Any thoughts on this issue? @jinjinjin0731 @yuche

**Comment by jinjinjin0731** [comment]
正在改造，预计 2 月初完成

**Comment by shaodahong** [comment]
@jinjinjin0731 现在进度完成了么
