### ISSUE TITLE
3.6.15版本能够正常启动，但是项目访问报错

### ISSUE THREAD

**Issue by selectDele** [NervJS/taro#15013]
![1703147194763](https://github.com/NervJS/taro/assets/39356455/34c9bd55-645b-4ee7-8fd0-318355f963cb)
![1703147208902](https://github.com/NervJS/taro/assets/39356455/8477d07c-4390-49e0-a933-80884f4cab6d)

### 相关平台
H5

**浏览器版本: edge**
**使用框架: Vue 3**

### 复现步骤
pnpm run dev:h5
启动项目正常，后续通过网页访问项目出现以下报错

runtime-hooks.ts:140  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at TaroHooks.tap (runtime-hooks.ts:140:1)
    at eval (runtime.ts:169:1)
    at ./node_modules/.pnpm/@tarojs plugin-html@3.6.21_postcss@8.4.24_vue@3.3.4/node_modules/@tarojs/plugin-html/dist/runtime.js (src_app_boot_js.js:1062:1)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:486:21)
    at eval (app.boot.js:3:90)
    at ./src/app.boot.js (src_app_boot_js.js:1097:1)
    at __webpack_require__ (runtime.js:36:33)
    at Function.fn (runtime.js:486:21)

### 期望结果
正常启动项目并运行

### 实际结果
启动项目了，浏览器运行报错

### 环境信息
```
👽 Taro v3.6.15


  Taro CLI 3.6.15 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE 
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD     
    npmPackages:
      @tarojs/cli: 3.6.15 => 3.6.15 
      @tarojs/components: 3.6.15 => 3.6.15 
      @tarojs/helper: 3.6.15 => 3.6.15 
      @tarojs/plugin-framework-vue3: 3.6.15 => 3.6.15  
      @tarojs/plugin-html: ^3.6.15 => 3.6.21 
      @tarojs/plugin-platform-alipay: 3.6.15 => 3.6.15 
      @tarojs/plugin-platform-h5: 3.6.15 => 3.6.15     
      @tarojs/plugin-platform-jd: 3.6.15 => 3.6.15     
      @tarojs/plugin-platform-qq: 3.6.15 => 3.6.15     
      @tarojs/plugin-platform-swan: 3.6.15 => 3.6.15   
      @tarojs/plugin-platform-tt: 3.6.15 => 3.6.15     
      @tarojs/plugin-platform-weapp: 3.6.15 => 3.6.15  
      @tarojs/runtime: 3.6.15 => 3.6.15 
      @tarojs/shared: 3.6.15 => 3.6.15
      @tarojs/taro: 3.6.15 => 3.6.15
      @tarojs/webpack5-runner: 3.6.15 => 3.6.15
      babel-preset-taro: 3.6.15 => 3.6.15
      eslint-config-taro: 3.6.15 => 3.6.15

```

**Comment by ZakaryCode** [comment]
从报错信息来看这是由于依赖未对齐导致的hooks不能正常出发抛出的问题，可以检查下项目依赖树，对齐后并重新安装再尝试
