### ISSUE TITLE
3.9以下版本怎么使用获取实时手机号能力

### ISSUE THREAD

**Issue by luozejian** [NervJS/taro#15017]
### 相关平台
微信小程序

**小程序基础库: 3.25**
**使用框架: React**

### 复现步骤
这两种监听事件方式都没有作用
<button
            id="xx1"
            // @ts-ignore
            open-type="getRealtimePhoneNumber"
            // @ts-ignore
            onGetRealtimePhoneNumber={this.onGetRealTimePhoneNumber}
            bindgetrealtimephonenumber={this.onGetRealTimePhoneNumber}
          >

### 期望结果
可以监听到获取手机号的事件

### 实际结果
监听不到

### 环境信息
```
 Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
你升级到最新版本试试呢

**Comment by lupingW** [comment]
![image](https://github.com/NervJS/taro/assets/50098740/55ac4c40-fe5e-4503-a3e0-376749818ded)
试试这种方法呢

**Comment by TheKonka** [comment]
解决方案参考楼上
