### ISSUE TITLE
rn项目可以执行pushy bundle --platform android 命令

### ISSUE THREAD

**Issue by cc-Listener** [NervJS/taro#15028]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
taro init 选择rn模版

### 期望结果
可以执行pushy bundle --platform android 命令

### 实际结果
index.js入口文件未找到

### 环境信息
```
Taro v3.6.1


  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-react: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/react: 3.5.6 => 3.5.6 
      @tarojs/rn-runner: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/taro-rn: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 
      expo: ~46.0.1 => 46.0.21 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
    npmGlobalPackages:
      typescript: 5.0.4
```

---
### 补充信息
error The resource `/Users/aze/Desktop/output-project/wuqi/wuqi-shopAssistant-app/index.js` was not found.
Error: The resource `/Users/aze/Desktop/output-project/wuqi/wuqi-shopAssistant-app/index.js` was not found.
    at /Users/aze/Desktop/output-project/wuqi/wuqi-shopAssistant-app/node_modules/metro/src/IncrementalBundler.js:297:24
    at gotStat (node:fs:2689:21)
    at FSReqCallback.oncomplete (node:fs:206:21)
info Run CLI with --verbose flag for more details.
Error: "react-native bundle" command exited with code 1.
    at ChildProcess.<anonymous> (/Users/aze/.nvm/versions/node/v16.17.0/lib/node_modules/react-native-update-cli/lib/bundle.js:83:16)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by zhiqingchen** [comment]
新版本已支持

**Comment by cc-Listener** [comment]
@zhiqingchen 有没有文档地址呢

**Comment by zhiqingchen** [comment]
新版本加了index.js了

**Comment by zhiqingchen** [comment]
文档就官网
