### ISSUE TITLE
Input 组件 onConfirm 事件无法清空 value

### ISSUE THREAD

**Issue by bmcciscoding** [NervJS/taro#1502]
**问题描述**
我在使用 Input 组件时，期望在 onConfirm 里清空 text。但是并没有。然后我查阅了相关问题，发现处理了 
onInput 事件之后，就可以清空。然后我查阅文档并没有发现这样的说明。

**复现步骤**
[复现问题的步骤]
1. 点击 Input
2. 输入文字
3. 点击确认
```js
constructor(props) {
    super(props)
    this.state = {
       newTodoTitle: ''
    }
  }

// 这里可以贴代码
changeNewTodoTitle(e) {
    this.setState({
      newTodoTitle: e.target.value
    })
  }

  createTodo(data) {
    console.log('user done', data.target.value)
   this.setState({
      newTodoTitle: ''
    })

const newTodo = <Input 
      placeholder='创建一个新的 todo'
      value={this.state.newTodoTitle}
      onConfirm={this.createTodo.bind(this)}
      // 打开下面的注释 点击确认就会清空
      //onInput={this.changeNewTodoTitle}
      type='text'
      ></Input>
```

**期望行为**
期望不处理 onInput 也可以在 onComfirm 里清空 text

**报错信息**
没打开注释的效果
![image](https://user-images.githubusercontent.com/20121334/49943012-ca6dd780-ff21-11e8-8c77-ac71e307962f.png)

打开了注释的效果
![image](https://user-images.githubusercontent.com/20121334/49943183-34867c80-ff22-11e8-9c11-090ff6746714.png)

打开了注释的效果

**系统信息**

 - 操作系统: [mac Moyave 10.14.1]
 - Taro 版本 [v1.2.0-beta.14]
 - Node.js 版本 [v11.2.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
小程序原生可以不处理 onInput 也可以在 onComfirm 里清空 text 么

**Comment by weimode** [comment]
Input 组件怎么才能触发清空value？

**Comment by cfkxzsat** [comment]
同问orz

**Comment by wintarwuwentao** [comment]
官方好像还没有解决这个问题吧？
