### ISSUE TITLE
希望能完善非微信小程序的编译方案

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1504]
历史原因，适配都是微信小程序优先
Taro版本：1.1.8

#需求1 首先各个平台乃至细分平台请分开目录
腾讯，阿里(支付宝,钉钉,mPaas(蚂蚁金服))，百度打包的时候都会编译到dist目录里:
.weapp_temp
.alipay_temp

#需求2 第一步目录分好后希望可以约定大于配置的思想，dist中需要在模拟器中调试的各个平台差异文件夹部分不变
因为dist出来后肯定需要在各个模拟器里调试增删代码。
如果要手动拷贝出来旧的，新编译的每次都要和老的differ
比如.alipay_temp/alipayApi中在小程序开发工具中改过的代码，
每次build alipay后在.alipay_temp/alipayApi中的代码都不变

#需求3 chrome中调试H5貌似webpack读的是dist里面的js,
webpack:///.temp/utils/request.js?061f 这样的
有没有babel-register实时转码方式能够直接看到src代码

**Comment by yuche** [comment]
在目前的版本三个功能均已实现，详情请翻阅 Taro 文档。

**Comment by hugetiny** [comment]
yeah~
