### ISSUE TITLE
Execution failed for task ':expo-modules-core:prepareBoost'.   Not in GZIP format

### ISSUE THREAD

**Issue by Cantaloupe313** [NervJS/taro#15056]
### 相关平台
android app

### 复现仓库
[https://gitee.com/buera/utapp.git](https://gitee.com/buera/utapp.git)
**小程序基础库: 无**
**使用框架: React**

### 复现步骤
使用android  studio构建然后运行app，报错Execution failed for task ':expo-modules-core:prepareBoost'.

### 期望结果
可以正常运行到模拟器

### 实际结果
构建后运行到app提示Execution failed for task ':expo-modules-core:prepareBoost'.

### 环境信息
```


  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.20.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Felix8029** [comment]
https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz  下载不到了，导致文件是个空的。

**Comment by channelltom** [comment]
Hey there guys,
I'm experiencing the same error when building my android application. Has anyone found a fix so far?

**Comment by Felix8029** [comment]
https://github.com/expo/expo/issues/26184

**Comment by zhiqingchen** [comment]
https://github.com/expo/expo/issues/26184#issuecomment-1873694150

**Comment by kenisad5566** [comment]
[JFrog for boost download now is up, and the issue should be resolved. I've tried to build using EAS and its success](https://github.com/expo/expo/issues/26184)

**Comment by Jean-Bekker** [comment]
Fixed the Issue with Boost Library

Step 1: Update URL in ReactAndroid Build Script

1. Navigate to the file: `/node_modules/react-native/ReactAndroid/build.gradle`

2. Locate the following line:

```
https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
```

3. Replace it with:

```
https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz
```

Step 2: Update URL in Expo Modules Core

1. Go to the file: `/node_modules/expo-modules-core/android/build.gradle.`

2. Search for the same URL as in Step 1.

3. Replace it with the new URL provided in Step 1.

Step 3: Apply the Patches

After making the changes, run the following commands to apply the patches:
```
patch-package react-native
patch-package expo-modules-core
```
