### ISSUE TITLE
rn 分离模式 android/ios模拟器上永远显示欢迎页面

### ISSUE THREAD

**Issue by 86chenjie** [NervJS/taro#15090]
![Simulator Screenshot - iPhone_11_Pro_max_6 5_1242 × 2688 - 2024-01-09 at 23 03 03](https://github.com/NervJS/taro/assets/6668037/6673bd41-ed6c-4676-8711-e53286983aff)

### 相关平台
React Native

**使用框架: React**

### 复现步骤
参照官方文档 https://docs.taro.zone/docs/react-native#%E5%88%86%E7%A6%BB%E6%A8%A1%E5%BC%8F
壳工程使用 taro-native-shell 0.71.0 版本，JS工程用taro init使用默认模板。
android/ios成功编译后，均卡在欢迎页面，似乎JS工程打出来的main.jsbundle完全没有生效。

### 期望结果
能显示正常的页面

### 实际结果
显示rn的欢迎页面

### 环境信息
```
Taro v3.6.22


  Taro CLI 3.6.22 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - ~/Library/pnpm/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.22 => 3.6.22 
      @tarojs/components: 3.6.22 => 3.6.22 
      @tarojs/helper: 3.6.22 => 3.6.22 
      @tarojs/plugin-framework-react: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-alipay: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-h5: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-jd: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-qq: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-swan: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-tt: 3.6.22 => 3.6.22 
      @tarojs/plugin-platform-weapp: 3.6.22 => 3.6.22 
      @tarojs/react: 3.6.22 => 3.6.22 
      @tarojs/rn-runner: 3.6.22 => 3.6.22 
      @tarojs/rn-supporter: 3.6.22 => 3.6.22 
      @tarojs/runtime: 3.6.22 => 3.6.22 
      @tarojs/runtime-rn: 3.6.22 => 3.6.22 
      @tarojs/shared: 3.6.22 => 3.6.22 
      @tarojs/taro: 3.6.22 => 3.6.22 
      @tarojs/taro-loader: 3.6.22 => 3.6.22 
      @tarojs/taro-rn: 3.6.22 => 3.6.22 
      @tarojs/webpack5-runner: 3.6.22 => 3.6.22 
      babel-preset-taro: 3.6.22 => 3.6.22 
      eslint-config-taro: 3.6.22 => 3.6.22 
      react: ^18.1.0 => 18.2.0 
      react-native: ^0.70.1 => 0.70.14 
```

---
### 补充信息
图片请见顶部

**Comment by zhiqingchen** [comment]
确实存在这个问题。编译的时候需要设置 SKIP_BUNDLING=1，0.70 以后的版本未加上

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-native-shell/blob/0.70.0/ios/taroDemo.xcodeproj/project.pbxproj#L305
本地可以先加一下

**Comment by zhiqingchen** [comment]
0.71 及 0.72 均未正式支持，建议使用 0.73
https://github.com/NervJS/taro-native-shell/commit/962d505fb937bc53354397a7c56688189858930b

**Comment by 86chenjie** [comment]
我在 0.73.0 试了，还是一样的 
![Uploading Simulator Screenshot - iPhone 8 - 2024-02-23 at 21.58.32.png…]()

**Comment by hooliy** [comment]
怎么解决？taro-native-shell-0.76.0 下载下来也是这样，https://github.com/NervJS/taro-native-shell/issues/100
