### ISSUE TITLE
h5 页面跳转，等待页面  js 下载到跳转之间，能配置过渡 loading

### ISSUE THREAD

**Issue by shushu2013** [NervJS/taro#15108]
### 相关平台
H5

### 复现步骤
h5 有多个页面，现在默认打包是每个页面一个 js，从页面 A 跳转到页面 B，会去下载页面 B 的 js，其中会有一段等待时间（网络不佳），页面无反应，等页面 B 的 js 下载完了，才会跳转到页面 B，如果期间多次点击跳转页面 B 的按钮，可能会打开多个页面 B。希望从调用跳转方法开始，到等待页面 B  js 下载完开始跳转之间，能配置过渡的 loading

https://github.com/NervJS/taro/assets/6076072/fa449a9b-be35-4ee3-aeb9-17f0a364da19

**Comment by shushu2013** [comment]
[https://wuba.github.io/taro-playground/#/pages/global/index](https://wuba.github.io/taro-playground/#/pages/global/index) 可操作复现，等待页面的 js 下载完了，才会跳转到对应页面

https://github.com/NervJS/taro/assets/6076072/6ca8dac4-9db6-43e2-a3c0-a6762f6611ae

**Comment by ZEJIA-LIU** [comment]
在 H5 端添加了路由跳转之前和跳转之后的 api： beforeRouteChange 和 afterRouteChange，用户可以在项目在根据需求自行调用，设置页面跳转之间的过渡状态，优化用户体验。

**Comment by shushu2013** [comment]
> 可以使用 taro 的 eventcenter, 监听 '__taroRouterChange' 和 '__afterTaroRouterChange'即可

@ZEJIA-LIU  发版了么，Taro 哪个版本可以用了
