### ISSUE TITLE
H5 navigateBack方法，如果没有路由栈时没有返回历史来源页面，例如一个产品跳到另一个产品，结果回不去了

### ISSUE THREAD

**Issue by lhiro** [NervJS/taro#15104]
### 相关平台
H5

### 复现仓库
[https://github.com/jdf2e/nutui/tree/v4/packages/nutui-taro-demo?.git](https://github.com/jdf2e/nutui/tree/v4/packages/nutui-taro-demo?.git)
**浏览器版本:  Chrome/120**
**使用框架: Vue 3**

### 复现步骤
具体可以看看demo地址，跳转过去官网组件预览地址点击页面的返回后回不来了
https://vue-zphnmb.stackblitz.io

### 期望结果
点击页面返回能正常返回

### 实际结果
点击页面返回回不到来源页面

### 环境信息
```
node: v14.19.3
taro info

👽 Taro v3.6.21


  Taro CLI 3.6.21 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 14.19.3 - E:\App\Nodejs\node.EXE
      Yarn: 1.22.19 - E:\App\Nodejs\yarn.CMD
      npm: 6.14.17 - E:\App\Nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.21 => 3.6.21
      @tarojs/components: 3.6.21 => 3.6.21
      @tarojs/helper: 3.6.21 => 3.6.21
      @tarojs/plugin-framework-vue3: 3.6.21 => 3.6.21
      @tarojs/plugin-html: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-alipay: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-h5: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-jd: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-qq: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-swan: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-tt: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-weapp: 3.6.21 => 3.6.21
      @tarojs/runtime: 3.6.21 => 3.6.21
      @tarojs/shared: 3.6.21 => 3.6.21
      @tarojs/taro: 3.6.21 => 3.6.21
      @tarojs/webpack5-runner: 3.6.21 => 3.6.21
      babel-preset-taro: 3.6.21 => 3.6.21
      eslint-config-taro: 3.6.21 => 3.6.21
```

**Comment by ZakaryCode** [comment]
是的，navigateBack 不允许跳出应用，这并不是一个 bug，如果有需求可以自行判断跳转

**Comment by lhiro** [comment]
> 是的，navigateBack 不允许跳出应用，这并不是一个 bug，如果有需求可以自行判断跳转

也就是没向下兼容了这里。。。

**Comment by lhiro** [comment]
> 是不是这类场景需要自己判断，通过 history.go(-delta) 处理
1. 假设有5个taro应用，发现升级后出现返回不了（均全部修改业务代码或降级）
2. 应用中点击例如(官方示例)[https://nutui.jd.com/taro/vue/4x/demo.html#/pages/index/index]，点击随便一个页面，我发现我网络不好，刷新一下，结果想回去也返回不了，这是不是有点影响用户体验额

已上虽说都可以自己写业务代码处理，不过正常情况下你浏览【H5】时，你希望是这样一个用户体验么
@beezen @ZakaryCode

**Comment by ZakaryCode** [comment]
> 也就是没向下兼容了这里。。。

之前可以跳出应用，确切来说是个 bug，关闭应用和应用内路由回退是两个场景，在这里不能退出应用更符合 navigateBack API 的设计意图，并不是应当被向下兼容的特性。

> 已上虽说都可以自己写业务代码处理，不过正常情况下你浏览【H5】时，你希望是这样一个用户体验么

很抱歉对您的实际使用造成了影响，但在这里对于 API 的迭代不会将非标准的使用纳入升级兼容的考量范畴，H5 打包出来实际会是一个完整的应用，此类路由 API 的设计也不会将应用外的情况，以及应用间的 API 一并考量，在 Taro 内应当会在实现 exitMiniProgram 此类 API 时考虑此类情况（H5 端暂不支持）。针对于您具体场景下可能导致的问题，这类业务需求需要在业务代码内自行处理。

**Comment by yuuk** [comment]
进入页面后刷新浏览器同样返回不了，我感觉H5应用刷新页面应该算是很高频的操作吧
