### ISSUE TITLE
类型“TaroStatic”上不存在属性“options”

### ISSUE THREAD

**Issue by lqw1** [NervJS/taro#15102]
### 相关平台
微信小程序

**小程序基础库: 3.3.0**
**使用框架: React**

### 复现步骤
import { View } from '@tarojs/components';
import Taro from '@tarojs/taro';

Taro.options.html.transformElement = (taroElement, el) => {
  if (taroElement.nodeName === 'image') {
    taroElement.setAttribute('class', 'aotu')
  }
  if (el.nodeName === 'table') {
    console.log(taroElement, el, '123')
    taroElement.setAttribute('class', '777')
  }
  return taroElement
}

const RenderHtml = ({ content }) => {

  return (
    <View className='dangerously-set-inner-html'>
      <View dangerouslySetInnerHTML={{ __html: content }}></View>
    </View>
  );
};

export default RenderHtml;

### 期望结果
Taro.options.html.transformElement能被执行

### 实际结果
ts报错类型“TaroStatic”上不存在属性“options”，且不能执行

### 环境信息
```
Taro CLI 3.6.20 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE 
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD   
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD     
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20 
      @tarojs/components: 3.6.20 => 3.6.20 
      @tarojs/helper: 3.6.20 => 3.6.20 
      @tarojs/plugin-framework-react: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20     
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20     
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20     
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20   
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20     
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20  
      @tarojs/react: 3.6.20 => 3.6.20 
      @tarojs/runtime: 3.6.20 => 3.6.20 
      @tarojs/shared: 3.6.20 => 3.6.20 
      @tarojs/taro: 3.6.20 => 3.6.20 
      @tarojs/taro-loader: 3.6.20 => 3.6.20
      @tarojs/webpack5-runner: 3.6.20 => 3.6.20
      babel-preset-taro: 3.6.20 => 3.6.20
      eslint-config-taro: 3.6.20 => 3.6.20
      react: ^18.0.0 => 18.2.0
      taro-ui: ^3.2.0 => 3.2.0
```

**Comment by ZakaryCode** [comment]
参考 #15100 回复
