### ISSUE TITLE
在微信小程序中，调用createInnerAudioContext方法时可以传入useWebAudioImplement参数来优化播放短音频时的性能，为什么taro中的createInnerAudioContext没有该参数

### ISSUE THREAD

**Issue by Mrmeimei** [NervJS/taro#15114]
### 这个特性解决了什么问题？
优化小程序中短音频的播放性能

### 这个 API 长什么样？
createInnerAudioContext可以接受传入useWebAudioImplement参数

**Comment by TheKonka** [comment]
应该是ts类型问题，你正常传入可以生效不

**Comment by Mrmeimei** [comment]
问题是这个参数填入和不填入，控制台打印看不出来区别，所以我也不知道传进去的生效了没有，我之所以想填入这个参数，是因为在频繁切换短音频的时候，音频偶尔播放出来没有声音，不知道是自己的问题还是播放器的问题，然后看到微信的文档上有这个参数可以优化性能。
