### ISSUE TITLE
支持自定义导航吗？我看了github上面这个，但是不知道如何引入nav导航组件 https://github.com/mulook/weapp-navigation-bar

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1512]
支持自定义导航吗？我看了github上面这个，但是不知道如何引入nav导航组件 https://github.com/mulook/weapp-navigation-bar

**Comment by cooliean** [comment]
https://www.jianshu.com/p/9d3318f7f219
这里的第5点，你看看可以不

**Comment by luckyadam** [comment]
可以参照大佬 @cooliean  的尝试下
