### ISSUE TITLE
如何基于 Taro 开发第三方多端 UI 库？

### ISSUE THREAD

**Issue by chaserstrong** [NervJS/taro#15128]
### 这个特性解决了什么问题？
翻阅官方文档，找到这篇文章，说明了如何使用taro开发多端ui库，但是按照文档的引导实操的时候发现不能生效。 执行TARO_BUILD_TYPE=ui taro build --ui报：请传入正确的编译类型！
<img width="757" alt="image" src="https://github.com/NervJS/taro/assets/18061322/ab0a9bac-9512-45a6-a569-cd8bd8a22c23">

深入排查发现文档中给出的实际案例是1.xx版本的taro：https://github.com/NervJS/taro-ui-sample。
请问现在3.xx版本是否有类似的案例或者方法？

### 这个 API 长什么样？
无

**Comment by ZakaryCode** [comment]
Duplicate of #13103
