### ISSUE TITLE
taro 3.5.7 转成 H5 构建产物包含全量 tarojs/components

### ISSUE THREAD

**Issue by JackForNet** [NervJS/taro#15156]
### 这个特性解决了什么问题？
H5构建产物不会对开发者造成困扰，实际页面中没有用到该组件，产物里面依然存在。

### 这个 API 长什么样？
期望构建成 H5 可以按需加载，不打入全量的 esm-es5

![image](https://github.com/NervJS/taro/assets/18653377/49ae9162-c09f-4e51-b69b-33fc16072c6d)

**Comment by ZakaryCode** [comment]
Duplicate of #12829
