### ISSUE TITLE
Package the taro-rn project using Android Studio, but the generated release.apk is React, which is the official demo

### ISSUE THREAD

**Issue by Ccc437647** [NervJS/taro#15173]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
1.在项目工程中  运行yarn:build:rn   生成打包文件'android'
2.将'android' 文件复制, 并且 替换掉 壳文件'taro-native-shell'中的'android'文件
3.壳文件'taro-native-shell' 执行 ./gradlew assembleRelease  进行 release.apk 生成
4.但是生成的release.apk  是react 的 demo文件 (App.js)
    使用yarn:android 生成的 debug.apk文件  则是我的项目工程文件

### 期望结果
期望生成的release.apk是我的项目工程文件

### 实际结果
实际上,生成的release.apk是react 的 demo文件 (App.js)

### 环境信息
```
  Taro CLI 3.6.22 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.22 => 3.6.22
      @tarojs/components: 3.6.22 => 3.6.22
      @tarojs/helper: 3.6.22 => 3.6.22
      @tarojs/plugin-framework-react: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-alipay: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-h5: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-jd: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-qq: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-swan: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-tt: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-weapp: 3.6.22 => 3.6.22
      @tarojs/react: 3.6.22 => 3.6.22
      @tarojs/rn-runner: 3.6.22 => 3.6.22
      @tarojs/rn-supporter: 3.6.22 => 3.6.22
      @tarojs/runtime: 3.6.22 => 3.6.22
      @tarojs/runtime-rn: 3.6.22 => 3.6.22
      @tarojs/shared: 3.6.22 => 3.6.22
      @tarojs/taro: 3.6.22 => 3.6.22
      @tarojs/taro-loader: 3.6.22 => 3.6.22
      @tarojs/taro-rn: 3.6.22 => 3.6.22
      @tarojs/webpack5-runner: 3.6.22 => 3.6.22
      babel-preset-taro: 3.6.22 => 3.6.22
      eslint-config-taro: 3.6.22 => 3.6.22
      expo: ~47.0.3 => 50.0.3
      react: ^18.1.0 => 18.2.0
      react-native: ^0.70.1 => 0.70.15
```

**Comment by zhiqingchen** [comment]
壳工程的版本是？

**Comment by Ccc437647** [comment]
> 壳工程的版本是？
这是那个壳工程 https://github.com/NervJS/taro-native-shell
{
  "name": "tarodemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android --no-packager",
    "ios": "react-native run-ios --no-packager",
    "start": "react-native start",
    "test": "jest",
    "upgradePeerdeps": "install-peerdeps @tarojs/taro-rn@3.5.7-alpha.8 -o -Y && install-peerdeps @tarojs/components-rn@3.5.7-alpha.8 -o -Y && install-peerdeps @tarojs/router-rn@3.5.7-alpha.8 -o -Y && pod-install",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.7",
    "@react-native-camera-roll/camera-roll": "~5.0.4",
    "@react-native-clipboard/clipboard": "~1.11.1",
    "@react-native-community/geolocation": "~3.0.2",
    "@react-native-community/netinfo": "~9.3.0",
    "@react-native-community/slider": "~4.3.2",
    "@react-native-masked-view/masked-view": "~0.2.7",
    "@react-native-picker/picker": "~2.4.2",
    "expo": "~47.0.3",
    "expo-av": "~13.0.0",
    "expo-barcode-scanner": "~12.0.0",
    "expo-brightness": "~11.0.0",
    "expo-camera": "~13.0.0",
    "expo-file-system": "~15.1.1",
    "expo-image-picker": "~14.0.0",
    "expo-keep-awake": "~11.0.1",
    "expo-location": "~15.0.1",
    "expo-modules-core": "~1.0.2",
    "expo-permissions": "~13.2.0",
    "expo-sensors": "~12.0.1",
    "react": "18.1.0",
    "react-native": "^0.70.4",
    "react-native-device-info": "~10.3.0",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-image-resizer": "~1.4.5",
    "react-native-pager-view": "~6.0.1",
    "react-native-safe-area-context": "~4.4.1",
    "react-native-screens": "3.18.2",
    "react-native-svg": "~13.4.0",
    "react-native-syan-image-picker": "0.5.3",
    "react-native-webview": "~11.23.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "install-peerdeps": "^3.0.3",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "pod-install": "^0.1.35",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by zhiqingchen** [comment]
1. 壳工程的代码会跳过 js 的打包的
https://github.com/NervJS/taro-native-shell/blob/0.70.0/android/app/build.gradle#L85

2. 安卓目录是不需要复制的，通过配置 output 直接输出到壳工程项目
https://docs.taro.zone/docs/react-native#%E9%85%8D%E7%BD%AE-output

**Comment by Ccc437647** [comment]
> 1. 壳工程的代码会跳过 js 的打包的
>    https://github.com/NervJS/taro-native-shell/blob/0.70.0/android/app/build.gradle#L85
> 2. 安卓目录是不需要复制的，通过配置 output 直接输出到壳工程项目
>    https://docs.taro.zone/docs/react-native#%E9%85%8D%E7%BD%AE-output


我也尝试通过配置 output 直接输出到壳工程项目. 
并且在taro-native-shell\android 执行./gradlew assembleRelease 命令 成功获得release.apk包
但是打开还是官方的demo( 这次我没有// apply from: "../../node_modules/react-native/react.gradle" )
![12](https://github.com/NervJS/taro/assets/74176833/deb6bf2b-5246-48b2-9bce-20e2328241f3)
![13](https://github.com/NervJS/taro/assets/74176833/68e776c9-d618-4580-911c-26a5a656b1b8)

**Comment by zhiqingchen** [comment]
apply from: "../../node_modules/react-native/react.gradle" 这个被注释掉的话，就不会再打包 bundle 了。
检查下 '../android/app/src/main/assets/index.android.bundle' 这个文件是不是你要的

**Comment by Ccc437647** [comment]
> apply from: "../../node_modules/react-native/react.gradle" 这个被注释掉的话，就不会再打包 bundle 了。 检查下 '../android/app/src/main/assets/index.android.bundle' 这个文件是不是你要的

是我要的文件
项目文件通过配置 output 直接输出到壳工程项目
查看了壳工程项目的android/app/src/main/assets/index.android.bundle   就是项目文件里的内容

**Comment by zhiqingchen** [comment]
那就不清楚了，可以看看编译过程
