### ISSUE TITLE
css中注释import无效

### ISSUE THREAD

**Issue by luo7023539** [NervJS/taro#1517]
**问题描述**
编译Taro为支付宝小程序代码时，注释css中import语句无效，仍然被编译出来
注释具体样式没有该问题

**复现步骤**
以下
```css
/* @import "/components/wxParse/wxParse.acss"; */

```
编译为
```css
@import "/components/wxParse/wxParse.acss";
/*  */

```

**期望行为**
移除该行代码或保持注释

**报错信息**

无报错信息

**系统信息**

 - 操作系统: [MacOs 10.13.6]
 - Taro 版本 [1.2.0-beta]
 - Node.js 版本 [8.12.0]
 - 报错平台 [alipay]

**补充信息**

**Comment by shenghanqin** [comment]
试试最新版1.3.22代码？
