### ISSUE TITLE
H5报错：(0 , _tarojs_router__WEBPACK_IMPORTED_MODULE_3__.createHashHistory) is not a function

### ISSUE THREAD

**Issue by JackYangFM** [NervJS/taro#15190]
### 相关平台
H5

**浏览器版本: Chrome Version 120.0.6099.109 (Official Build) (x86_64)**
**使用框架: React**

### 复现步骤
npm run dev:h5

### 期望结果
正常打开页面

### 实际结果
必现报错

### 环境信息
```
  Taro CLI 3.6.10 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    npmPackages:
      @tarojs/components: 3.6.10 => 3.6.10 
      @tarojs/helper: 3.6.10 => 3.6.10 
      @tarojs/mini-runner: 3.6.10 => 3.6.10 
      @tarojs/plugin-framework-react: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-alipay: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-h5: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-jd: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-qq: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-swan: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-tt: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-weapp: 3.6.10 => 3.6.10 
      @tarojs/react: 3.6.10 => 3.6.10 
      @tarojs/rn-runner: 3.6.10 => 3.6.10 
      @tarojs/runtime: 3.6.10 => 3.6.10 
      @tarojs/taro: 3.6.10 => 3.6.10 
      @tarojs/taro-rn: 3.6.10 => 3.6.10 
      @tarojs/webpack-runner: 3.6.10 => 3.6.10 
      @tarojs/webpack5-runner: ^3.6.22 => 3.6.23 
      babel-preset-taro: 3.6.10 => 3.6.10 
      eslint-config-taro: 3.6.10 => 3.6.10 
      react: ^18.0.0 => 18.2.0 
      react-native: ^0.66.0 => 0.66.5 
```

---
### 补充信息
显示编译成功，但是浏览器打开就是报错。

✅  编译成功 1/30/2024, 5:08:19 PM

assets by status 10.1 MiB [cached] 50 assets
assets by path . 1.26 MiB
  assets by path js/*.js 1.26 MiB
    asset js/app.b517e81f.js 1.02 MiB [emitted] [immutable] (name: app)
    asset js/taro.b517e81f.js 176 KiB [emitted] [immutable] (name: taro) (id hint: taro)
    asset js/runtime.b517e81f.js 68.1 KiB [emitted] [immutable] (name: runtime)
  assets by info 912 bytes [hmr]
    asset runtime.fb20006e5aeab9708370.hot-update.js 881 bytes [emitted] [immutable] [hmr] (name: runtime)
    asset runtime.fb20006e5aeab9708370.hot-update.json 31 bytes [emitted] [immutable] [hmr]
  asset index.html 955 bytes [emitted]
Entrypoint app 1.26 MiB = js/runtime.b517e81f.js 68.1 KiB runtime.fb20006e5aeab9708370.hot-update.js 881 bytes js/taro.b517e81f.js 176 KiB js/app.b517e81f.js 1.02 MiB
cached modules 3.92 MiB (javascript) 90 bytes (remote) 90 bytes (share-init) 84 KiB (asset) [cached] 646 modules
runtime modules 47.3 KiB 20 modules
webpack 5.69.0 compiled successfully in 303 ms

<img width="680" alt="WeChatWorkScreenshot_c7c78b96-69e1-42bd-a56c-d22f545b3815" src="https://github.com/NervJS/taro/assets/21030408/26baedd3-daab-4239-bbc4-42ed6d34d6cc">

部署之后报错：
![image](https://github.com/NervJS/taro/assets/21030408/dae530a0-783d-4c99-bfbe-7aee9607b912)

**Comment by ZakaryCode** [comment]
对齐 taro 依赖版本，不要同时使用 3.6.10 和 3.6.23

**Comment by JackYangFM** [comment]
> 对齐 taro 依赖版本，不要同时使用 3.6.10 和 3.6.23

好的，明天试下

**Comment by JackYangFM** [comment]
> > 对齐 taro 依赖版本，不要同时使用 3.6.10 和 3.6.23
> 
> 好的，明天试下

已解决，写死【@tarojs/webpack5-runner】版本号即可。
![image](https://github.com/NervJS/taro/assets/21030408/00dcbabc-c365-4b4c-87fd-4c293358306b)
