### ISSUE TITLE
请教下，框架更新后，本地框架如何升级，项目依赖包如何更新呢？谢谢

### ISSUE THREAD

**Issue by jzsjiale** [NervJS/taro#152]
大家好，我刚学习这个，请教下，框架更新后，本地框架如何升级，项目依赖包如何更新呢？各使用什么命令呢？谢谢

**Comment by zacksleo** [comment]
你要更新指定的包吗 ？ 用 `npm update` + 包包

**Comment by jzsjiale** [comment]
框架更新后，是直接npm install -g @tarojs/cli用这个命令再安装一下吗，项目里的依赖的包，要想全部看看需不需要更新，都更新怎么操作呢

**Comment by zacksleo** [comment]
更新框架用 `npm install -g @tarojs/cli`, 更新项目中的所有依赖用`npm update`

**Comment by jzsjiale** [comment]
好的，非常感谢

**Comment by zacksleo** [comment]
@jzsjiale  问题可以关闭了
