### ISSUE TITLE
npm 运行的时候报错 node_modules/@swc/core-darwin-arm64/swc.darwin-arm64.node

### ISSUE THREAD

**Issue by Xhyen** [NervJS/taro#15207]
### 相关平台
微信小程序

**小程序基础库: 无**
**使用框架: Vue 3**

### 复现步骤
小程序使用 npm run test:weapp 无法启动 报
No loader is configured for ".node" files: node_modules/@swc/core-darwin-arm64/swc.darwin-arm64.node

### 期望结果
排查一下啥问题

### 实际结果
修复该问题

### 环境信息
```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.4.11 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17
      @tarojs/components: 3.6.17 => 3.6.17
      @tarojs/helper: 3.6.17 => 3.6.17
      @tarojs/mini-runner: 3.6.17 => 3.6.17
      @tarojs/plugin-html: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17
      @tarojs/runtime: 3.6.17 => 3.6.17
      @tarojs/shared: 3.6.17 => 3.6.17
      @tarojs/taro: 3.6.17 => 3.6.17
      @tarojs/webpack-runner: 3.6.17 => 3.6.17
      babel-preset-taro: 3.6.17 => 3.6.17
      eslint-config-taro: 3.6.17 => 3.6.17
```

**Comment by Xhyen** [comment]
用的是yarn安装的依赖 设备是m1芯片的 mbp

**Comment by Xhyen** [comment]
重装了一下系统之后 好了 但是昨天安装了一下mac的更新 又开始报相同的错误

Taro CLI 3.6.23 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17
      @tarojs/components: 3.6.17 => 3.6.17
      @tarojs/helper: 3.6.17 => 3.6.17
      @tarojs/mini-runner: 3.6.17 => 3.6.17
      @tarojs/plugin-framework-vue3: 3.6.17 => 3.6.17
      @tarojs/plugin-html: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17
      @tarojs/runtime: 3.6.17 => 3.6.17
      @tarojs/shared: 3.6.17 => 3.6.17
      @tarojs/taro: 3.6.17 => 3.6.17
      @tarojs/webpack-runner: 3.6.17 => 3.6.17
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17
      babel-preset-taro: 3.6.17 => 3.6.17
      eslint-config-taro: 3.6.17 => 3.6.17

**Comment by eiinu** [comment]
先确保本地全局的 Taro Cli 版本与项目内的 Taro 版本是一致的再试试

**Comment by Xhyen** [comment]
> 先确保本地全局的 Taro Cli 版本与项目内的 Taro 版本是一致的再试试

我现在本地的taro-cli和项目内的taro是一致的

**Comment by Xhyen** [comment]
> 先确保本地全局的 Taro Cli 版本与项目内的 Taro 版本是一致的再试试

Taro CLI 3.6.23 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.23 => 3.6.23
      @tarojs/components: 3.6.23 => 3.6.23
      @tarojs/helper: 3.6.23 => 3.6.23
      @tarojs/mini-runner: 3.6.23 => 3.6.23
      @tarojs/plugin-framework-vue3: 3.6.23 => 3.6.23
      @tarojs/plugin-html: 3.6.23 => 3.6.23
      @tarojs/plugin-platform-h5: 3.6.23 => 3.6.23
      @tarojs/plugin-platform-weapp: 3.6.23 => 3.6.23
      @tarojs/runtime: 3.6.23 => 3.6.23
      @tarojs/shared: 3.6.23 => 3.6.23
      @tarojs/taro: 3.6.23 => 3.6.23
      @tarojs/webpack-runner: 3.6.23 => 3.6.23
      @tarojs/webpack5-runner: 3.6.23 => 3.6.23
      babel-preset-taro: 3.6.23 => 3.6.23
      eslint-config-taro: 3.6.23 => 3.6.23

**Comment by Xhyen** [comment]
@eiinu 请问下这个东西有办法解决吗 我的cli和项目的taro版本都是3.6.24 已经是更新到最新了 node版本也是最新的21.6.2 但是只要运行`cross-env APP_ENV=test npm run build:weapp -- --watch` 就报错。

提示[ERROR] No loader is configured for ".node" files: node_modules/@swc/core/node_modules/@swc/core-darwin-arm64/swc.darwin-arm64.node

    node_modules/@swc/core/binding.js:145:48:
      145 │ ...             nativeBinding = require('@swc/core-darwin-arm64');
          ╵


但是如果改成NODE_ENV=production APP_ENV=dev taro build --type weapp --watch 这样就不会报错了。但是无法debugger代码。。

**Comment by Xhyen** [comment]
解决了 查看git历史版本 感觉是vscode帮我自动注入了`import { sources } from 'webpack'这一行代码

然后导致项目在打包的过程中出现了以上报错
