### ISSUE TITLE
抖音小程序应该如何正确使用事件？

### ISSUE THREAD

**Issue by 501956430** [NervJS/taro#15221]
### 相关平台
字节跳动小程序

**小程序基础库: 3.11.0**
**使用框架: Vue 3**

### 复现步骤
抖音小程序 buttom标签的事件，不知如何使用才能有效，尝试使用过 bindpm 、@tappm、 ondpm 都无效 事件不会触发？ 
我应该如何使用？

[官方文档：](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/open-capacity/button-private-message)
**这是抖音官方的例子：**
```
<button
  open-type="privateMessage"
  data-aweme-id="{{ awemeId }}"
  bindpm="pmCallback"
  binderror="pmError"
>
  跳转私聊页
</button>
```
taro vue3 实际代码：
```
<button
          openTypeKeys="privateMessage"
          open-type="tt"
          data-aweme-id=""
          @onpm="pmCallback"
          @onerror="pmError" style="display: flex;align-items: center;justify-content: space-between"
        ></button>
```

应该如何使用什么样的语法才能触发 **pm 、error** 事件，请帮助我下，感谢🙏

### 期望结果
事件能触发

### 实际结果
事件无法触发

### 环境信息
```
Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 12.7.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-vue3: 3.6.19 => 3.6.19 
      @tarojs/plugin-html: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/plugin-vue-devtools: 3.6.19 => 3.6.19 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19
```

**Comment by TheKonka** [comment]
https://docs.taro.zone/docs/next/vue-overall#taro-%E8%A7%84%E8%8C%83-1

https://github.com/NervJS/taro/blob/main/packages/taro-tt/src/components.ts

需要在这个文件里面手动加下事件绑定 bindpm , 或者你可以用 taro-plugin-inject 本地加下

**Comment by 501956430** [comment]
@TheKonka  
 安装了 taro-plugin-inject插件并配置了 
````
plugins: [
      ['@tarojs/plugin-inject', {
        components: {
          Button: {
            bindError: '',
            bindPM: ''
          }
        }
      }]
    ],


<button
          openTypeKeys="privateMessage"
          open-type="tt"
          bindPM="pm"
          bindError="pmError">主页</button> 
````

实际使用时模拟器和真机事件都不生效，是否还有其他地方需要配置才能有效？

**Comment by 501956430** [comment]
<Button
        openType="tt"
        openTypeKeys="privateMessage"
        >
  </Button>

<Button
        openType="privateMessage"
        openTypeKeys="tt"
        >
  </Button>

<Button
        open-type="privateMessage"
        openTypeKeys="tt"
        >
  </Button>

<Button
        open-Type="privateMessage"
        openTypeKeys="tt"
        >
  </Button>

这组件应该如何使用。事件如何触发。
````
"button-privateMessage: fail platform auth deny"
````

**Comment by 501956430** [comment]
````
<Button openType="privateMessage">客户服务</Button>
<Button openType="privateMessage" openTypeKeys="tt">客户服务</Button>
<Button openType="tt" openTypeKeys="privateMessage">客户服务</Button>
````
这组件应该如何使用。事件如何触发。

````
"button-privateMessage: fail platform auth deny"
````

**Comment by TheKonka** [comment]
配置应该是对的，但是监听的时候不要用 bindPM 了， 用 @pm

**Comment by 501956430** [comment]
@TheKonka  onPm bindPM @Pm都尝试过 事件无效

**Comment by 501956430** [comment]
<img width="594" alt="截屏2024-02-18 13 39 20" src="https://github.com/NervJS/taro/assets/20204491/77bcc7f8-1a30-4abd-8251-d06af861472d">
这是编译后的源码
openType="tt" openTypeKeys="privateMessage"

**Comment by TheKonka** [comment]
不清楚是不是 data-awemeid 错了 ，抖音的文档是 data-aweme-id

**Comment by 501956430** [comment]
<img width="314" alt="截屏2024-02-18 13 51 46" src="https://github.com/NervJS/taro/assets/20204491/fa0996bd-6735-4be8-b2a6-4247d500ea75">
这是components 重点是事件不执行，如不够配置data-aweme-id 事件也是会执行的

**Comment by 501956430** [comment]
@TheKonka 是open-type 的问题。taro open-type='privateMessage' 才是正确，但是设置为privateMessage 会提示错误：button-privateMessage: fail platform auth deny

**Comment by TheKonka** [comment]
> 使用该功能前开发者需要去开发者后台-设置-关联设置-抖音号管理为对应的抖音号申请小程序跳转私信能力。


这个权限申请了吗？

**Comment by 501956430** [comment]
@TheKonka  "data-aweme-id should be string, but got undefined" 
taro把 data-aweme-id 转换为data-awemeid了

**Comment by 501956430** [comment]
['@tarojs/plugin-inject', {
        components: {
          Button: {
            'data-aweme-id':'',
            bindopenawemeuserprofile: ''
          }
        }
      }]
配置新增属性 编译后依然是data-awemeid

**Comment by 501956430** [comment]
@TheKonka @eiinu 请问能帮忙处理这个属性问题吗？ 

plugin-platform-tt：
````
Button: {
    bindGetPhoneNumber: string;
    "data-channel": string;
    "data-aweme-id": string;
    "group-id": string;
    "data-is-half-page": string;
    bindOpenAwemeUserProfile: string;
    bindJoinGroup: string;
    bindpm: string;
    binderror: string;
  };
````

Button标签属性data-aweme-id，会被编译成data-awemeid问题。

**Comment by 501956430** [comment]
@TheKonka 
````
<button open-type="openAwemeUserProfile" data-aweme-id="抖音号">客户服务</button>

````

相同代码，抖音可以正常跳转抖音号主页,taro 无法调整并提示错误：data-aweme-id should be string, but got undefined

**Comment by TheKonka** [comment]
dataAwemeId 需要改成驼峰写法

**Comment by 501956430** [comment]
@TheKonka  试过了，问题解决了。
不过疑问的是 怎么是这种格式？属性格式不跟文档对应嘛？

**Comment by TheKonka** [comment]
虽然抖音文档写的是 data-aweme-id，但是因为是 data-* 开头，在 Taro 里面直接写会被当作 dataset  处理。
Taro 其实内部会把所有文档上的非事件属性都转成驼峰，所以直接写驼峰就可以生效了
