### ISSUE TITLE
swiper无法使用map方法循环

### ISSUE THREAD

**Issue by JokerLoLgrey** [NervJS/taro#1524]
## 已解决，请关闭
**问题描述**
swiper内SwiperItem无法使用map方法循环 ，
渲染数组内部数据

**复现步骤**
[复现问题的步骤]
父组件向子组件传递一个数组，
子组件内部有一个轮播图，
轮播图使用react map方法渲染轮播图内部标签，
轮播图不会渲染，
希望能够更新支持
[或者可以直接贴源代码，能贴文字就不要截图]
![image](https://user-images.githubusercontent.com/33446705/49998462-47a35600-ffcf-11e8-96ba-15e8ac701b1b.png)
![image](https://user-images.githubusercontent.com/33446705/49998557-8a652e00-ffcf-11e8-977a-101118f54889.png)

```js
// 这里可以贴代码
<Swiper
          className='indexSwiper'
          indicatorColor='#999'
          indicatorActiveColor='#333'
          circular
          indicatorDots
          autoplay>
          {
            this.props.imgList.map(
              item => {
                (
                  <SwiperItem}>
                    <Image src={item.imgSrc} />
                  </SwiperItem>
                )
              }
            )
          }
        </Swiper>
```

**期望行为**
能够渲染数组，从后端请求回来图片都是数组形式

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [^1.2.0-beta.10]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
dom树中有渲染是这样的
![image](https://user-images.githubusercontent.com/33446705/49999202-293e5a00-ffd1-11e8-8425-b0df596f52f9.png)

**Comment by JohnPion-Zhang** [comment]
```
this.props.imgList.map(
              item => {
               return (
                  <SwiperItem}>
                    <Image src={item.imgSrc} />
                  </SwiperItem>
                )
              }
            )
```

> return 一下试试，哥们

**Comment by JokerLoLgrey** [comment]
> ```
> this.props.imgList.map(
>               item => {
>                return (
>                   <SwiperItem}>
>                     <Image src={item.imgSrc} />
>                   </SwiperItem>
>                 )
>               }
>             )
> ```
> > return 一下试试，哥们

感谢，确实加了一个return可以了，但是map不是自带return的吗

**Comment by jinjinjin0731** [comment]
建议你可以再去看看箭头函数的语法~~~~~~
