### ISSUE TITLE
H5端 @tarojs/components 包 treeshaking 失效

### ISSUE THREAD

**Issue by daifee** [NervJS/taro#15245]
### 相关平台
H5

### 复现仓库
[https://github.com/daifee/taro-demo.git](https://github.com/daifee/taro-demo.git)
**浏览器版本: 无关**
**使用框架: React**

### 复现步骤
1、初始化新项目
2、修改配置 config/index.ts
```js
// config/index.ts
{
  // ...
  h5: {
    compile: {
        include: [filename => /node_modules/.test(filename)]
      },
  }
  // ...
}
```

3、用`webpack-bundle-analyzer`分析，看到包体积增加了500+KB，swiper等没用的组件也被打进去

**配置前：**
![image](https://github.com/NervJS/taro/assets/5410503/428e2c0e-53e6-4c53-8f8f-0017cd5c61c7)

**配置后：**
![image](https://github.com/NervJS/taro/assets/5410503/03f2b67a-1874-428b-b5ad-ba7d39e84acb)

### 期望结果
可以配置 babel 编译 @tarojs/components 包的代码，而且Tree Shaking 功能不会失效

### 实际结果
配置 babel 编译 @tarojs/components 包的代码，Tree Shaking 功能会失效（其它node_modules包的TreeShaking功能正常）

### 环境信息
```
👽 Taro v3.6.23


  Taro CLI 3.6.23 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.23 => 3.6.23 
      @tarojs/components: 3.6.23 => 3.6.23 
      @tarojs/helper: 3.6.23 => 3.6.23 
      @tarojs/plugin-framework-react: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-alipay: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-h5: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-jd: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-qq: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-swan: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-tt: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-weapp: 3.6.23 => 3.6.23 
      @tarojs/react: 3.6.23 => 3.6.23 
      @tarojs/runtime: 3.6.23 => 3.6.23 
      @tarojs/shared: 3.6.23 => 3.6.23 
      @tarojs/taro: 3.6.23 => 3.6.23 
      @tarojs/taro-loader: 3.6.23 => 3.6.23 
      @tarojs/webpack5-runner: 3.6.23 => 3.6.23 
      babel-preset-taro: 3.6.23 => 3.6.23 
      eslint-config-taro: 3.6.23 => 3.6.23 
      react: ^18.0.0 => 18.2.0 
```

**Comment by ZakaryCode** [comment]
因为这个覆盖率的代码还不支持抖动，可以考虑将 browserslist 提高到如下

```
> 0.5%, last 2 versions, Firefox ESR, not dead
Android >= 50
ios >= 11
```

**Comment by toFrankie** [comment]
为什么每个 chunk 都会重复引入 taro/component 等包？

<img width="1993" alt="image" src="https://github.com/NervJS/taro/assets/26947203/4e3b3d56-eb49-455d-a083-821709ad2c2c">

**Comment by ZakaryCode** [comment]
> 为什么每个 chunk 都会重复引入 taro/component 等包？

不是同一个问题哈，大概会是实际引用了不同路径的组件库或者babel配置过低导致webpack无法识别重复代码，有问题可以提交新的 issue 并附上完整的 demo 用于定位问题
