### ISSUE TITLE
taro 3.6.10 版本 打包H5在 android 9手机报错白屏："Uncaught SyntaxError: 'super' keyword unexpected here", source: https://***/js/9.01ab024a.js (2)

### ISSUE THREAD

**Issue by JackYangFM** [NervJS/taro#15247]
### 相关平台
H5

**浏览器版本: Chrome 68.0.3440.91**
**使用框架: React**

### 复现步骤
npm run build:h5

### 期望结果
期望在android 9系统的手机能正常打开

### 实际结果
android 9系统的手机上白屏并报错："Uncaught SyntaxError: 'super' keyword unexpected here", source: https://***/js/9.01ab024a.js (2)

### 环境信息
```
Taro CLI 3.6.10 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.1/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.6.10 => 3.6.10 
      @tarojs/helper: 3.6.10 => 3.6.10 
      @tarojs/mini-runner: 3.6.10 => 3.6.10 
      @tarojs/plugin-framework-react: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-alipay: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-h5: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-jd: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-qq: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-swan: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-tt: 3.6.10 => 3.6.10 
      @tarojs/plugin-platform-weapp: 3.6.10 => 3.6.10 
      @tarojs/react: 3.6.10 => 3.6.10 
      @tarojs/rn-runner: 3.6.10 => 3.6.10 
      @tarojs/runtime: 3.6.10 => 3.6.10 
      @tarojs/taro: 3.6.10 => 3.6.10 
      @tarojs/taro-rn: 3.6.10 => 3.6.10 
      @tarojs/webpack-runner: 3.6.10 => 3.6.10 
      @tarojs/webpack5-runner: 3.6.22 => 3.6.22 
      babel-preset-taro: 3.6.10 => 3.6.10 
      eslint-config-taro: 3.6.10 => 3.6.10 
      react: ^18.0.0 => 18.2.0 
      react-native: ^0.66.0 => 0.66.5
```

---
### 补充信息
npm run dev:h5，本地服务可以在手机上打开，build完的就报错 白屏。

手机输出信息："GET /favicon.ico" "Mozilla/5.0 (Linux; Android 9; V1816A Build/PKQ1.180819.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36"

报错代码片段：
window.classNames=classNames}()}))},"6585":function(e,t,n){function debounce(e,t=250,n){let r;return function(...o){const a=n||this;clearTimeout(r),r=setTimeout((function(){e.apply(a,o)}),t)}}function isVisible(e){return!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length)}n.d(t,{"d":function(){return debounce},"i":function(){return isVisible}})},"4128":function(e,t,n){n.d(t,{"M":function(){return h}});var r=n(7210),o=n(4536),a=n(7109);function setTransform(e,t){e.transform=t,e.webkitTransform=t,e.MozTransform=t}const s="undefined"!=typeof navigator&&/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/i.test(navigator.userAgent),l={"activate":"release","deactivate":"pull","release":"loading","finish":"finish"};let c=!1;try{const e=Object.defineProperty({},"passive",{"get"(){c=!0}});window.addEventListener("cancel",(()=>({})),e)}catch(e){}const u=!!c&&{"passive":!1},d=(0,r.GH)(class extends r.mv{"constructor"(){super(),this.__registerHost(),this.onRefresh=(0,r.yM)(this,"refresh",7),this._ScreenY=0,this._startScreenY=0,this._lastScreenY=0,this._isMounted=!1,this.triggerPullDownRefresh=e=>{!this.dragOnEdge&&this._isMounted&&(e?(this._lastScreenY=this.distanceToRefresh 1,this.currSt="release",this.setContentStyle(this._lastScreenY)):(this.currSt="finish",this.reset()))},this.init=()=>{const e=this.scrollContainer,t=this.el.querySelector("rmc-pull-to-refresh-content");this.el.appendChild=null==t?void 0:t.appendChild.bind(t),this.el.insertBefore=null==t?void 0:t.insertBefore.bind(t),this.el.replaceChild=null==t?void 0:t.replaceChild.bind(t),this.el.removeChild=null==t?void 0:t.removeChild.bind(t),this._to={"touchstart":this.onTouchStart.bind(this,e),"touchmove":this.onTouchMove.bind(this,e),"touchend":this.onTouchEnd.bind(this,e),"touchcancel":this.onTouchEnd.bind(this,e)},Object.keys(this._to).forEach((t=>{e.addEventListener(t,this._to[t],u)}))},this.destroy=()=>{const e=this.scrollContainer;Object.keys(this._to).forEach((t=>{e.removeEventListener(t,this._to[t])}))},this.onTouchStart=(e,t)=>{this._ScreenY=this._startScreenY=t.touches[0].screenY,this._lastScreenY=this._lastScreenY||0},this.isEdge=e=>{const t=this.scrollContainer;if(t&&t===document.body){return(document.scrollingElement?document.scrollingElement:document.body).scrollTop<=0}return e.scrollTop<=0},this.damp=e=>{if(Math.abs(this._lastScreenY)>this.damping)return 0;return e*=.6*(1-Math.abs(this._ScreenY-this._startScreenY)/window.screen.height)},this.onTouchMove=(e,t)=>{const n=t.touches[0].screenY;if(!(this._startScreenY>n)&&this.isEdge(e)){this.dragOnEdge||(this._ScreenY=this._startScreenY=t.touches[0].screenY,this.dragOnEdge=!0),t.cancelable&&t.preventDefault();

**Comment by ZakaryCode** [comment]
将不支持语法所对应依赖，通过 [h5.compile.include](https://nervjs.github.io/taro-docs/docs/config-detail#h5compileinclude) 加入 babel 作用范围

**Comment by JackYangFM** [comment]
> 将不支持语法所对应依赖，通过 [h5.compile.include](https://nervjs.github.io/taro-docs/docs/config-detail#h5compileinclude) 加入 babel 作用范围

怎么能定位到不支持语法所对应的依赖啊，请教一下

**Comment by JackYangFM** [comment]
> > 将不支持语法所对应依赖，通过 [h5.compile.include](https://nervjs.github.io/taro-docs/docs/config-detail#h5compileinclude) 加入 babel 作用范围
> 
> 我就是用该方法解决这个问题，然后产生另一个问题： @tarojs/components 包的treeshaking失效 #15245

我只配了这个可以了，其他的啥也没改，你可以试试
compile: {
        include: [path.resolve(__dirname, '..', 'node_modules/@tarojs/components')],
      },

**Comment by BEN13459290037** [comment]
如果是依赖包问题，为什么dev可以用，build用不了

**Comment by xujiujiu** [comment]
同样的问题，以上操作解决不了问题，引用的三方库是pdfh5，里面引用的是压缩后的pdf.js，使用了上面的[h5.compile.include](https://nervjs.github.io/taro-docs/docs/config-detail#h5compileinclude)依旧无法解决，还是需要解决下为什么dev可以用，build用不了
