### ISSUE TITLE
【虚拟瀑布流组件】能否添加gap相关字段?

### ISSUE THREAD

**Issue by cnyballk** [NervJS/taro#15253]
### 这个特性解决了什么问题？
想在瀑布流列表的某项想添加左右上下的间距，展示更舒服

### 这个 API 长什么样？
rowGap={10}
columnGap={10}

**Comment by ZakaryCode** [comment]
直接给节点加样式就可以？

**Comment by cnyballk** [comment]
> 直接给节点加样式就可以？

里面是定位的，是要加transform么

**Comment by cnyballk** [comment]
行 可以了
  #virtual-waterfall-0-column-0{
    margin-right:5px;
    > view{
      margin-bottom:5px;
    }
  }
  #virtual-waterfall-0-column-1{
    > view{
      margin-bottom:5px;
    }
  }
