### ISSUE TITLE
Video文档出现两次相同命名为 onFullscreenChange的监听事件，并且支持度不同

### ISSUE THREAD

**Issue by barom** [NervJS/taro#15279]
### 相关平台
微信小程序

**小程序基础库: 2.22.1**
**使用框架: React**

### 复现步骤

官方文档：https://taro-docs.jd.com/docs/components/media/video 搜onFullscreenChange。

### 期望结果
 微信小程序支持

### 实际结果
微信小程序IOS端事件无效

### 环境信息
```
👽 Taro v3.6.20


  Taro CLI 3.6.20 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.21 - ~/gaodun.com/gd-taro-mobile/node_modules/.bin/yarn
      npm: 9.2.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      eslint-config-taro: 3.6.20 => 3.6.20 
      taro-ui: ^3.2.0 => 3.3.0 
```

---
### 补充信息
升级taro版本到3.6.20之前使用的版本是3.2.13 onFullscreenChange 事件在微信小程序是生效的。

**Comment by TheKonka** [comment]
我试了微信小程序IOS端事件正常生效

**Comment by szqingt** [comment]
你注意下`onFullScreenChange`和`onFullscreenChange`中的大小写问题，看看有没有用错！
