### ISSUE TITLE
在app.js里无法用跳转

### ISSUE THREAD

**Issue by yuanjie007** [NervJS/taro#1527]
**问题描述**
在app.js的componentWillReceiveProps里面想要做个鉴权，没有登录就跳转到登录页，但是用了Taro.redirectTo({url: 'pages/login/login'})和navigateTo都跳转不了

**复现步骤**
```js
class App extends Component {
  config = {
    pages: [
      'pages/index/index',
      'pages/login/login'
      
    ]
  }
  componentWillReceiveProps () {
    // 如果检测到没有登录。跳转到登录页
    Taro.redirectTo({url: "pages/login/login"})
  }
}
```

**期望行为**
能在app.js里面跳转链接

**报错信息**
我刚才升级到最新的，发现一运行就报这个错了，不知道是什么原因...
![image](https://user-images.githubusercontent.com/18167335/50037251-54b15b00-004a-11e9-9f45-870afece71fb.png)

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.2.0-beta.15]
 - Node.js 版本 [e.g. v8.9.4]
 - 报错平台 [weapp]

**补充信息**
鉴权还有什么更好的建议吗？

**Comment by luckyadam** [comment]
Duplicate of #1352
