### ISSUE TITLE
初始化项目时选择Stylus，仍会安装node-sass依赖

### ISSUE THREAD

**Issue by weakish** [NervJS/taro#1529]
**问题描述**

初始化项目时CSS预处理器选择Stylus，仍会安装node-sass依赖

**复现步骤**

```
npm install -g @tarojs/cli
taro init TaroExample
```

CSS预处理器选择

```
? 请选择 CSS 预处理器（Sass/Less/Stylus） Stylus
```

**期望行为**

不依赖Sass

**报错信息**

```
Cannot download "https://r.cnpmjs.org/node-sass//v4.11.0/linux-x64-59_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

这个其实是网络错误，但是我疑惑的是为什么预处理器选择了Stylus还是会将Sass作为依赖？

**系统信息**

 - Ubuntu 18.04
 - v1.2.0-beta.16
 - Node.js v9.11.1
 - 平台无关

**补充信息**

发现CSS预处理器选【无】，同样依赖node-sass

**Comment by shynome** [comment]
同样的问题, 有什么好的解决方案吗 @yuche

**Comment by shenghanqin** [comment]
其实我感觉还好，编译小程序代码的时候，这个组件并不会编译到dist目录里面吧？

**Comment by shenghanqin** [comment]
你可以试试初始化最新版的1.3.22，还有这个问题吗？

**Comment by weakish** [comment]
1.3.22 可重现。

不过理论上确实只是 dev 依赖，不会影响生产环境。
