### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by pc1995** [NervJS/taro#153]
创建项目后无法通过npm install或者yarn下载依赖包，一直卡，不知道是不是仓库出现问题？

**Comment by pc1995** [comment]
依赖能下载成功，然后项目能够正常跑起来，但是npm install 或者yarn的时候，还是会报诸多错，不知道是干什么的

**Comment by tongjun741** [comment]
同问
`➜  testWxApp git:(master) ✗ npm install
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/after
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/arraybuffer.slice
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/async-limiter
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/backo2
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/base64-arraybuffer
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/blob
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/callsite
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/better-assert
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/component-bind
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/component-inherit
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/has-binary2
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/engine.io-parser
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/has-cors
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/node-gyp-build
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/object-component
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/parseqs
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/parseuri
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/socket.io-parser
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/to-array
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/ultron
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/ws
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/xmlhttprequest-ssl
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/yeast
npm WARN checkPermissions Missing write access to /Users/tongjun/workspace/testWxApp/node_modules/engine.io-client
npm WARN @tarojs/components@0.0.69 requires a peer of @types/react@^16.4.6 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/tongjun/workspace/testWxApp/node_modules/after
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/tongjun/workspace/testWxApp/node_modules/after'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

**Comment by luckyadam** [comment]
@tongjun741 可以换 cnpm 安装
