### ISSUE TITLE
shadow-root下的组件无法使用全局样式或者本身外联的样式

### ISSUE THREAD

**Issue by liudonghua123** [NervJS/taro#1530]
**问题描述**
我在app.py中import了字体的css，但是在子组件中引用字体的样式就不起作用，但是在最顶层的page组件中是没有问题的，好像是因为自组件是在shadow root下面的，是一个独立的dom，不能继承css，如下图所示，第一个是正常的，第二个是样式没有继承的。

![image](https://user-images.githubusercontent.com/2276718/50044066-57976480-00b9-11e9-9e10-72a8a265a772.png)

![image](https://user-images.githubusercontent.com/2276718/50044059-32a2f180-00b9-11e9-8ca2-3ee86a4a82d9.png)

我也尝试过直接把字体相关的css复制到子组建import的less中，生成的wxss里面也确实有的，但还是不生效。

![image](https://user-images.githubusercontent.com/2276718/50044166-97128080-00ba-11e9-8634-b89ed90752c2.png)

**期望行为**
期望可以通过某种方式实现子组件可以使用自己的css或者集成全局样式

**报错信息**

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.2.0-beta.7
 - Node.js 版本 11.4
 - 报错平台 weapp

**补充信息**

似乎只能把样式转换为shadow root下面的<style>...</style>内联样式才可以生效

附上一些参考链接
https://stackoverflow.com/questions/47625017/override-styles-in-a-shadow-root-element
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM
https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/
https://css-tricks.com/playing-shadow-dom/

**Comment by jinjinjin0731** [comment]
[taro文档](https://nervjs.github.io/taro/docs/component-style.html)
[小程序文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html)
