### ISSUE TITLE
taro升级到beta16后，taro-ui图片上传在iOS未生效

### ISSUE THREAD

**Issue by dsky1990** [NervJS/taro#1532]
**系统信息**

 - 操作系统: [mac]
 - Taro 版本 [v.1.2.0-beta.16]
 - Taroui 版本 [1.5.2]
 - Node.js 版本 [v 8.12.0]
 - 报错平台 [h5]

**Comment by Pines-Cheng** [comment]
你说的 iOS 是小程序还是 H5？

**Comment by jimczj** [comment]
未生效指的是什么，上传功能，还是图片选择功能

**Comment by dsky1990** [comment]
h5，上传功能，事件都未触发

**Comment by jinjinjin0731** [comment]
@jimczj

**Comment by SmallRuralDog** [comment]
安卓也有问题 。拍照能正常触发事件，选择图片就不行。

**Comment by jimczj** [comment]
经测试是基础组件库绑定 onChange 有问题，已联系修复

**Comment by dsky1990** [comment]
升级到正式版也有问题，请问一下，什么时候可以修复完成呢

**Comment by jimczj** [comment]
@dsky1990已经修复，等待 Taro 发个版本

**Comment by dsky1990** [comment]
@jimczj 好的，现在就等这个- -不用新的picker组件有问题，用新的，上传组件有问题，囧，辛苦啦
