### ISSUE TITLE
项目目录名称是否包含taro会影响构建代码，且compile的include和exclude配置优先级会被taro覆盖

### ISSUE THREAD

**Issue by Hmyou** [NervJS/taro#15339]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Hmyou/build-issue-demo.git](https://github.com/Hmyou/build-issue-demo.git)
**小程序基础库: 任意**
**使用框架: Vue 3**

### 复现步骤
node20 pnpm，taro init 初始化两个项目，webpack5-sass-vue3-typescript-nutui，区别只有项目目录名不同，一个name-no-demo（不带taro）一个name-taro-demo（带taro），分别执行构建build:weapp，发现构建产物vendors.js中对vue等第三方依赖处理结果不同

### 期望结果
在项目目录名不包含taro的情况下，可以通过compile配置：配置exclude的情况同时include也能生效去编译第三方依赖；或者可以指定编译全部第三方依赖

### 实际结果
目录名不包含taro时，配置了compile.exclude后想再指定include编译第三方依赖时，会被taro-webpack5-runner里的exclude更高优先级给覆盖。目录名包含taro时可以编译其他第三方依赖。

### 环境信息
```
Taro CLI 3.6.23 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.5.1/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.23 => 3.6.23 
      @tarojs/components: 3.6.23 => 3.6.23 
      @tarojs/helper: 3.6.23 => 3.6.23 
      @tarojs/plugin-framework-vue3: 3.6.23 => 3.6.23 
      @tarojs/plugin-html: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-alipay: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-h5: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-jd: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-qq: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-swan: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-tt: 3.6.23 => 3.6.23 
      @tarojs/plugin-platform-weapp: 3.6.23 => 3.6.23 
      @tarojs/runtime: 3.6.23 => 3.6.23 
      @tarojs/shared: 3.6.23 => 3.6.23 
      @tarojs/taro: 3.6.23 => 3.6.23 
      @tarojs/taro-loader: 3.6.23 => 3.6.23 
      @tarojs/webpack5-runner: 3.6.23 => 3.6.23 
      babel-preset-taro: 3.6.23 => 3.6.23 
      eslint-config-taro: 3.6.23 => 3.6.23 
```

---
### 补充信息
可以查看重现链接github里的项目demo与README，有贴出taro-webpack5-runner中存疑的代码部分。h5与mini同理情况

**Comment by Chen-jj** [comment]
@Hmyou 最新版本里，通过这个 PR 应该已经修复了：https://github.com/NervJS/taro/pull/15120

1. 现在 Babel 只会默认编译 node_modules 文件夹里名字带有 taro 的包和项目源码目录。
2. 可以同时配置 include、exclude。需要注意在同时使用时，Webpack 的行为是先判断 include 的范围，再从中判断 exclude。
