### ISSUE TITLE
unexpected character `{`

### ISSUE THREAD

**Issue by proactivefly** [NervJS/taro#15348]
### 相关平台
微信小程序

**小程序基础库: 3.3.0**
**使用框架: React**

### 复现步骤
pnpm install
npm run dev

### 期望结果
微信开发者工具正常运行

### 实际结果
[ WXML 文件编译错误] ./base.wxml
unexpected character `{`
   7 | 
   8 | <template name="tmpl_0_0">
>  9 |   <view hover-class="{{xs.b(i.p1,'none')}} hover-stop-propagation="{{xs.b(i.p4,!1)}}" hover-start-time="{{xs.b(i.p2,50)}}" hover-stay-time="{{xs.b(i.p3,400)}}" bindtouchstart="eh" bindtouchend="eh" bindtouchcancel="eh" bindlongpress="eh" animation="{{i.p0}}" bindanimationstart="eh" bindanimationiteration="eh" bindanimationend="eh" bindtransitionend="eh" style="{{i.st}}" class="{{i.cl}} bindtap="eh" catchtouchmove="eh"  id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">
     |                                                                   ^
  10 |     <block wx:for="{{i.cn}}" wx:key="sid">
  11 |       <template is="{{xs.a(c, item.nn, l)}}" data="{{i:item,c:c 1,l:xs.f(l,item.nn)}}" />
  12 |     </block>
at files://dist\base.wxml#9(env: Windows,mp,1.06.2401020; lib: 3.3.0)

### 环境信息
```
 Taro CLI 3.6.24 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.24 => 3.6.24
      @tarojs/components: 3.6.24 => 3.6.24
      @tarojs/helper: 3.6.24 => 3.6.24
      @tarojs/plugin-framework-react: 3.6.24 => 3.6.24
      @tarojs/plugin-html: ^3.6.22 => 3.6.22
      @tarojs/plugin-platform-alipay: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-h5: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-jd: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-qq: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-swan: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-tt: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-weapp: 3.6.24 => 3.6.24
      @tarojs/react: 3.6.24 => 3.6.24
      @tarojs/runtime: 3.6.24 => 3.6.24
      @tarojs/shared: 3.6.24 => 3.6.24
      @tarojs/taro: 3.6.24 => 3.6.24
      @tarojs/taro-loader: 3.6.24 => 3.6.24
      @tarojs/webpack5-runner: 3.6.24 => 3.6.24
      babel-preset-taro: 3.6.24 => 3.6.24
      eslint-config-taro: 3.6.24 => 3.6.24
      react: ^18.0.0 => 18.2.0
```

**Comment by TheKonka** [comment]
这个问题如果必现的话给个复现demo，我这里微信开发者工具是正常运行的，而且没有其他人反馈
