### ISSUE TITLE
当tabs， swiper封装成组件时，当tabs切换时，swiper的自动轮播会失效，而tabBar的切换则不会

### ISSUE THREAD

**Issue by JokerLoLgrey** [NervJS/taro#1534]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
当tabBar， tabs， swiper封装成组件时，当tabs切换时，swiper的自动轮播会失效，而tabBar的切换则不会
**复现步骤**
[复现问题的步骤]
当tabBar， tabs， swiper封装成组件时，当tabs切换时，swiper的自动轮播会失效，而tabBar的切换则不会
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
// 这是tabBar的home页面代码

import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Search from '../../components/search/search'
import Tabs from '../../components/tabs/tabs'
import Tab0 from './tabsContent/tabIndex0'
import Tab1 from './tabsContent/tabIndex1'

export default class Index extends Component {
  render () {
    const tabList = [{ title: '推荐',content: <Tab0 /> }, { title: '关注', content: <Tab1 /> }]
    return (
      <View className='home'>
        <Search />
        <Tabs tabList={tabList} />
      </View>
    )
  }
}

// 这是tabs组件代码

import Taro from '@tarojs/taro'
import { AtTabs, AtTabsPane } from 'taro-ui'
import './tabs.scss'

export default class Index extends Taro.Component {
  constructor () {
    super(...arguments)
    this.state = {
      current: 0,
    }
  }
  handleClick (value) {
    this.setState({
      current: value
    })
  }
  render () {
    const tabList = this.props.tabList
    return (
      <AtTabs
        className='my-tabs'
        current={this.state.current}
        tabList={tabList}
        onClick={this.handleClick.bind(this)}
        swipeable
        >
        {
          tabList.map(
            (item, i) => {
              return (
                <AtTabsPane current={this.state.current} index={i} >
                  {item.content}
                </AtTabsPane>
              )
            }
          )
        }
      </AtTabs>
    )
  }
}

//这个是swiper封装的组件

import Taro, { Component } from '@tarojs/taro'
// 引入 Swiper, SwiperItem 组件
import { View, Swiper, SwiperItem } from '@tarojs/components'
export default class Index extends Component {
  render () {
    const swiperData = this.props.swiperData
    const swiperAuto = this.props.swiperAuto
    return (
      <Swiper
        indicatorColor='#999'
        indicatorActiveColor='#333'
        circular
        indicatorDots
        autoplay={swiperAuto}
        >
        {
          swiperData.map(
            item => {
              return (
                <SwiperItem>
                  <View>
                    {item}
                  </View>
                </SwiperItem>
              )
            }
          )
        }
      </Swiper>
    )
  }
}

// 这是封装的tabBar

import Taro from '@tarojs/taro'
import { AtTabBar }  from 'taro-ui'
export default class Index extends Taro.Component {
  constructor () {
    super(...arguments)
    this.state = {
      current: 0
    }
  }
  handleClick (value) {
    this.setState({
      current: value
    })
  }
  render () {
    return (
      <AtTabBar
        selectedColor='#212121'
        color='#BDBDBD'
        fixed={this.props.fixed}
        tabList={this.props.tabList}
        onClick={this.handleClick.bind(this)}
        current={this.state.current}
      />
    )
  }
}
```

**期望行为**
切换tabs，轮播图能够自动轮播

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

这是正常轮播的h5截图
![image](https://user-images.githubusercontent.com/33446705/50051964-308f7000-0157-11e9-85b2-48a174e98e51.png)

这是非正常轮播情况
![image](https://user-images.githubusercontent.com/33446705/50051989-9da30580-0157-11e9-93da-4e299988d84b.png)

ps: 非正常轮播在滑动一下又能够正常轮播了，非正常的时候没有点亮的点也正常点亮了
**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
应该是需要初始化轮播图

**Comment by yuche** [comment]
swiper 封装的组件 `swiperAuto` 写一个 defaultProps 为 true

**Comment by JokerLoLgrey** [comment]
> swiper 封装的组件 `swiperAuto` 写一个 defaultProps 为 true

我之前传了的，不行，我之前是写的是autoplay=true，这个不行，我才改成父组件传值，但是还是不行，这个应该是个bug

**Comment by JokerLoLgrey** [comment]
@luckyadam

**Comment by catXiaoXiao** [comment]
+1,我也出现了这个问题！！！！AtTabs 和Swiper 组件同时存在AtTabs 会影响Swiper 组件！！！求解决办法啊

**Comment by JokerLoLgrey** [comment]
> +1,我也出现了这个问题！！！！AtTabs 和Swiper 组件同时存在AtTabs 会影响Swiper 组件！！！求解决办法啊

升级taro和ui版本

**Comment by catXiaoXiao** [comment]
> > +1,我也出现了这个问题！！！！AtTabs 和Swiper 组件同时存在AtTabs 会影响Swiper 组件！！！求解决办法啊
> 
> 升级taro和ui版本

我看了Swiper源码，发现是Swiper组件的生命周期componentWillReceiveProps里每次都会把index = 0
只能在自己封装的组件shouldComponentUpdate做判断禁止不必要的渲染了，或者记录当前current传给Swiper组件

**Comment by JokerLoLgrey** [comment]
> > > +1,我也出现了这个问题！！！！AtTabs 和Swiper 组件同时存在AtTabs 会影响Swiper 组件！！！求解决办法啊
> > 
> > 
> > 升级taro和ui版本
> 
> 我看了Swiper源码，发现是Swiper组件的生命周期componentWillReceiveProps里每次都会把index = 0
> 只能在自己封装的组件shouldComponentUpdate做判断禁止不必要的渲染了，或者记录当前current传给Swiper组件。源码如下：
> ![image](https://user-images.githubusercontent.com/26037975/52923795-6a9e0d80-3364-11e9-883b-ca74036b928f.png)

升级到最新没有这个问题，但是会有其他bug

**Comment by shenghanqin** [comment]
@JokerLoLgrey 可以试试看最新版1.3.22的是否改了吗？

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/68564793-84502980-048c-11ea-9fac-d367c7548755.png)
这不是 DevServer 断开连接的报错吗...
