### ISSUE TITLE
taro create 创建页面错误

### ISSUE THREAD

**Issue by forestberg** [NervJS/taro#15342]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/vastcom/sq_school_taro.git](https://gitee.com/vastcom/sq_school_taro.git)
**小程序基础库: 3.3.4**
**使用框架: React**

### 复现步骤
sqschool_minip % taro create --name postlist
👽 Taro v3.6.24

/usr/local/lib/node_modules/@tarojs/cli/dist/create/page.js:141
        (0, binding_1.createPage)({
                                 ^

Error: Missing field `framework`
    at Page.write (/usr/local/lib/node_modules/@tarojs/cli/src/create/page.ts:168:22)
    at Page.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/src/create/page.ts:147:10)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@tarojs/cli/dist/create/page.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'InvalidArg'

### 期望结果
创建新的页面

### 实际结果
出现错误信息

### 环境信息
```
👽 Taro v3.6.24


  Taro CLI 3.6.24 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.1.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.24 => 3.6.24 
      @tarojs/components: 3.6.24 => 3.6.24 
      @tarojs/helper: 3.6.24 => 3.6.24 
      @tarojs/plugin-framework-react: 3.6.24 => 3.6.24 
      @tarojs/plugin-html: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-alipay: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-h5: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-jd: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-qq: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-swan: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-tt: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-weapp: 3.6.24 => 3.6.24 
      @tarojs/react: 3.6.24 => 3.6.24 
      @tarojs/runtime: 3.6.24 => 3.6.24 
      @tarojs/shared: 3.6.24 => 3.6.24 
      @tarojs/taro: 3.6.24 => 3.6.24 
      @tarojs/taro-loader: 3.6.24 => 3.6.24 
      @tarojs/webpack5-runner: 3.6.24 => 3.6.24 
      babel-preset-taro: 3.6.24 => 3.6.24 
      eslint-config-taro: 3.6.24 => 3.6.24 
      react: ^18.0.0 => 18.2.0 

```

**Comment by TheKonka** [comment]
![image](https://github.com/NervJS/taro/assets/22173084/47c9cdf5-af4b-44f4-bb11-75f450a6f9a2)

package.json 里面手动加下配置吧
