### ISSUE TITLE
vscode 卡死问题

### ISSUE THREAD

**Issue by nailfar** [NervJS/taro#1535]
**问题描述**
[问题描述：现在遇到一个问题，我用的vscode 开发项目，每隔几分钟编辑器就死机了，我以为是微信开发者工具导致的卡死，后来我关闭了微信开发者工具，但是依然每隔几分钟就卡死，就算我不写代码依然会卡死。关闭 taro的 时时监听后vscode 就不会卡死  ]

**复现步骤**
[复现问题的步骤]
1.npm run dev:weapp
2. 打开vscode 编辑代码 刷新微信开发者工具 查看预览效果  重复几次
3. vscode 卡死 需要强制关闭
 
**期望行为**
期望能在vscode 里正常使用，现在taro 编译几次 编辑器就挂了

**报错信息**

没有任何报错信息

**系统信息**

 - 操作系统: win10 
 - Taro 版本 1.2.0-beta.6
 - Node.js 版本 8.11.1
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
可能是对文件的处理不当，文件锁 ？ 猜测而已

**Comment by yuche** [comment]
没能复现这个问题，你得自己慢慢禁用插件调查原因。

**Comment by saviourdog** [comment]
+1
