### ISSUE TITLE
css Module开启影响全局

### ISSUE THREAD

**Issue by stylehuan** [NervJS/taro#1536]
**问题描述**
开启`css modules` ，影响全局的`className`，具体配置如下：

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js
       cssModules: {
          enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }

```

**期望行为**
能够不影响全局，或者可以区分模块

**报错信息**

无

**系统信息**

 - 操作系统: [e.g. mac os]
 - Taro 版本 [e.g. Taro v1.2.0-beta.15]
 - Node.js 版本 [e.g. v11.3.0]
 - 报错平台 [weapp]

**Comment by StingKo** [comment]
#1456
