### ISSUE TITLE
小红书小程序的taro plugin维护问题

### ISSUE THREAD

**Issue by jzhmcoo1** [NervJS/taro#15377]
### 这个特性解决了什么问题？
1. 小红书小程序的taro plugin，目前在独立的仓库下，想请问下是否能够集成到taro主仓库的monorepo下一起维护？
https://github.com/NervJS/taro-plugin-platform-xhs

2. https://github.com/NervJS/taro-plugin-platform-xhs/pull/19 目前pr没有人帮忙review

### 这个 API 长什么样？
1. 是否可以集成主仓库一起维护？
2. 希望帮忙合并和发版

**Comment by jzhmcoo1** [comment]
有没有官方的同学对接一下？

**Comment by Chen-jj** [comment]
已对接
