### ISSUE TITLE
taro 4.0.0-beta.25 to harmony后在DevEco无法运行

### ISSUE THREAD

**Issue by LesterWeng** [NervJS/taro#15382]
### 相关平台
鸿蒙

### 复现仓库
[https://github.com/LesterWeng/taro-issue-harmony1.git](https://github.com/LesterWeng/taro-issue-harmony1.git)

**使用框架: React**

### 复现步骤
yarn

修改下config/index harmony路径配置

yarn run dev:harmony

在deveco打开模拟器，运行查看，发现应用卡在进入页，打开log发现不停抛出errror

### 期望结果
deveco能正常运行，使用taro开发的鸿蒙页面能正常投入使用

### 实际结果
无法运行

### 环境信息
```
👽 Taro v4.0.0-beta.25


  Taro CLI 4.0.0-beta.25 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v16.20.1/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    npmPackages:
      @tarojs/api: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/cli: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/components: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/mini-runner: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/plugin-framework-react: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/react: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/taro: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/taro-h5: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/webpack-runner: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/webpack5-prebundle: 4.0.0-beta.25 => 4.0.0-beta.25 
      @tarojs/webpack5-runner: 4.0.0-beta.25 => 4.0.0-beta.25 
      babel-preset-taro: 4.0.0-beta.25 => 4.0.0-beta.25 
      eslint-config-taro: 4.0.0-beta.25 => 4.0.0-beta.25 
      react: 17.0.2 => 17.0.2 
```

---
### 补充信息
DevEco Studio NEXT Developer Preview1
Build Version: 4.1.3.500, built on January 20, 2024

相关图片：
![image](https://imagecdn.ymm56.com/ymmfile/static/resource/d3e8cd9c-8fe6-46f5-9acc-6a7295d2a5bb.png)

![image](https://imagecdn.ymm56.com/ymmfile/static/resource/81f1828f-b262-416f-a9aa-4727b3a87772.png)

![image](https://imagecdn.ymm56.com/ymmfile/static/resource/f4ecc460-5f70-4489-81b3-1562a5ad753e.png)

![image](https://imagecdn.ymm56.com/ymmfile/static/resource/63604a10-a6eb-46ec-a184-32ec89c8763e.png)

![image](https://imagecdn.ymm56.com/ymmfile/static/resource/b3806afd-c9e2-4521-8b37-5cd6aad052a3.png)

**Comment by LesterWeng** [comment]
忽略node16信息，安装依赖时是node18
Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node

**Comment by xuanzebin** [comment]
经排查，是 react 版本过低导致的报错，可以将版本调整至 18 再重新编译试试：
```
{
  "dependencies": {
      "react": "18.0.0",
      "react-dom": "18.0.0",
  }
}
```

**Comment by LesterWeng** [comment]
> 经排查，是 react 版本过低导致的报错，可以将版本调整至 18 再重新编译试试：
> 
> ```
> {
>   "dependencies": {
>       "react": "18.0.0",
>       "react-dom": "18.0.0",
>   }
> }
> ```

好的 我试试 taro4应该是要支持react17的吧？

**Comment by xuanzebin** [comment]
应该是会支持的，目前应该是有点小问题，之后得排查一下

**Comment by LesterWeng** [comment]
好的
