### ISSUE TITLE
Picker  mode = multiSelector 上滑时不准确

### ISSUE THREAD

**Issue by Dave-miao** [NervJS/taro#1538]
**问题描述**
Picker  mode = multiSelector
做城市选择器
上滑时省市对应不准确
尤其是上滑到第一个时

**Comment by jinjinjin0731** [comment]
你跟我讲的是在异步情况数据更新问题~~ 这个我看下

**Comment by zhhbinn** [comment]
H5下，滑动到第一个选项时似乎不触发onColumnchange

**Comment by luckyadam** [comment]
@jinjinjin0731

**Comment by jinjinjin0731** [comment]
@zhhbinn  啥版本。是否点击了确定之后再次打开

**Comment by jinjinjin0731** [comment]
@zhhbinn  啥版本。是否点击了确定之后再次打开

**Comment by zhhbinn** [comment]
@jinjinjin0731 更新到最新版本了，没有点击确定后打开。在第一列滑动至其他选项时触发了指定方法，但是划到第一个选项时，无法触发。小程序端没有这个问题。

**Comment by zhhbinn** [comment]
@jinjinjin0731 问题应该是：默认选项改成别的选项后再改回默认选项（没按确定），无法触发onColumnchange

**Comment by jinjinjin0731** [comment]
@zhhbinn  可以给一下可复现代码和使用版本吗。  不然我没法定位~~

**Comment by zhhbinn** [comment]
Taro v1.2.0


  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.0 => 1.2.0
      @tarojs/components: 1.2.0 => 1.2.0
      @tarojs/plugin-babel: 1.2.0 => 1.2.0
      @tarojs/plugin-csso: 1.2.0 => 1.2.0
      @tarojs/plugin-less: 1.2.0 => 1.2.0
      @tarojs/plugin-uglifyjs: 1.2.0 => 1.2.0
      @tarojs/redux: 1.2.0 => 1.2.0
      @tarojs/redux-h5: 1.2.0 => 1.2.0
      @tarojs/router: 1.2.0 => 1.2.0
      @tarojs/taro: 1.2.0 => 1.2.0
      @tarojs/taro-alipay: 1.2.0 => 1.2.0
      @tarojs/taro-h5: 1.2.0 => 1.2.0
      @tarojs/taro-swan: 1.2.0 => 1.2.0
      @tarojs/taro-weapp: 1.2.0 => 1.2.0
      @tarojs/webpack-runner: 1.2.0 => 1.2.0
      eslint-config-taro: 1.2.0 => 1.2.0
      eslint-plugin-taro: 1.2.0 => 1.2.0



以上是版本信息，以下是代码https://github.com/zhhbinn/taro-picker

JinJinJin <notifications@github.com> 于2018年12月18日周二 下午5:03写道：

**Comment by jinjinjin0731** [comment]
ok 我查查原因

**Comment by jinjinjin0731** [comment]
更新到最新版即可解决
