### ISSUE TITLE
生产环境打包，每个页面都会把node modules的包也给打进去

### ISSUE THREAD

**Issue by cavey1230** [NervJS/taro#15399]
### 相关平台
H5

**浏览器版本: 123.0.6312.59 arm64**
**使用框架: React**

### 复现步骤
下面贴图

### 期望结果
node modules 打包到单独的地方

### 实际结果
不是每个页面的主js文件里

### 环境信息
```
 Taro CLI 3.6.24 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.24 => 3.6.24 
      @tarojs/components: 3.6.24 => 3.6.24 
      @tarojs/helper: 3.6.24 => 3.6.24 
      @tarojs/plugin-framework-react: 3.6.24 => 3.6.24 
      @tarojs/plugin-html: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-alipay: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-h5: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-jd: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-qq: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-swan: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-tt: 3.6.24 => 3.6.24 
      @tarojs/plugin-platform-weapp: 3.6.24 => 3.6.24 
      @tarojs/react: 3.6.24 => 3.6.24 
      @tarojs/runtime: 3.6.24 => 3.6.24 
      @tarojs/shared: 3.6.24 => 3.6.24 
      @tarojs/taro: 3.6.24 => 3.6.24 
      @tarojs/taro-loader: 3.6.24 => 3.6.24 
      @tarojs/webpack5-runner: 3.6.24 => 3.6.24 
      babel-preset-taro: 3.6.24 => 3.6.24 

```

![206874417](https://github.com/NervJS/taro/assets/56331024/8ed28b46-ea71-4bb9-8094-74259d793e20)

**Comment by cavey1230** [comment]
问题已解决 我这个是monorepo单仓库的项目 用的 pnpm workspace

taro3 会默认的把引用的单仓库里的其他包需要的第三方包一起打包了

其实按正常逻辑，taro3可以不处理的。

因为发包之前，开发会提前对这些包提前打包的。

**Comment by cavey1230** [comment]
done 没有开按需加载

**Comment by toFrankie** [comment]
我的 Taro 3.6.21 打包成这样，我怀疑是分包引用导致的问题，之前也就 1M 多，不知道什么时候打包后有 30M+。

话说你是怎么处理的？

<img width="1753" alt="image" src="https://github.com/NervJS/taro/assets/26947203/9e93e35a-3030-42b8-804e-fa11147d5614">

**Comment by cavey1230** [comment]
> 我的 Taro 3.6.21 打包成这样，我怀疑是分包引用导致的问题，之前也就 1M 多，不知道什么时候打包后有 30M+。
> 
> 话说你是怎么处理的？
> 
> <img alt="image" width="1753" src="https://private-user-images.githubusercontent.com/26947203/321835616-9e93e35a-3030-42b8-804e-fa11147d5614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTg0MzMsIm5iZiI6MTcxNjYxODEzMywicGF0aCI6Ii8yNjk0NzIwMy8zMjE4MzU2MTYtOWU5M2UzNWEtMzAzMC00MmI4LTgwNGUtZmExMTE0N2Q1NjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA2MjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDE5MjE2YTNhY2ZkNWViMTg3ZjkxODI2MDI3MDMxNGMzZTY3YmQyM2MwYjg2YjAyODgzMjlmZjg3NDQ1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGgYsNRmjqY5pZPukZRKFrWSd9lJRE5lsDYqUFKQTFA">

我重新设置了打包的逻辑，可以看看文档

**Comment by cavey1230** [comment]
@toFrankie  webpackChain(chain) {
        chain.resolve.plugin('tsconfig-paths').use(TsconfigPathsPlugin);
        chain.optimization.splitChunks({
          cacheGroups: {
            // aboutReact: {
            //   test: /[\\/]node_modules[\\/]/,
            //   name: 'aboutReact',
            //   chunks: 'all',
            //   maxSize: 244000,
            // },
            aboutReact: {
              test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
              name: 'aboutReact',
              chunks: 'all',
            },
            aboutCodemirror: {
              test: /[\\/]node_modules[\\/](@codemirror.+)[\\/]/,
              name: 'aboutCodemirror',
              chunks: 'async',
              maxSize: 244000,
            },
          },
        });
      },

**Comment by cavey1230** [comment]
> 我的 Taro 3.6.21 打包成这样，我怀疑是分包引用导致的问题，之前也就 1M 多，不知道什么时候打包后有 30M+。
> 
> 话说你是怎么处理的？
> 
> <img alt="image" width="1753" src="https://private-user-images.githubusercontent.com/26947203/321835616-9e93e35a-3030-42b8-804e-fa11147d5614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTg0MzMsIm5iZiI6MTcxNjYxODEzMywicGF0aCI6Ii8yNjk0NzIwMy8zMjE4MzU2MTYtOWU5M2UzNWEtMzAzMC00MmI4LTgwNGUtZmExMTE0N2Q1NjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA2MjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDE5MjE2YTNhY2ZkNWViMTg3ZjkxODI2MDI3MDMxNGMzZTY3YmQyM2MwYjg2YjAyODgzMjlmZjg3NDQ1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGgYsNRmjqY5pZPukZRKFrWSd9lJRE5lsDYqUFKQTFA">

![image](https://github.com/NervJS/taro/assets/56331024/7405b6c1-979a-495e-a6b3-d631baec38bb)

**Comment by toFrankie** [comment]
嗯，我也是这样解决的。有个 CommonJS 的包被打包到每个 chunk 去了，单独拎出来就可以了。
