### ISSUE TITLE
更新0.54之后，似乎事件传参出现了问题

### ISSUE THREAD

**Issue by bernkastle** [NervJS/taro#154]
![image](https://user-images.githubusercontent.com/11273397/41637178-2354a9e6-7485-11e8-8046-70f8855270ee.png)
会有这样的错误，有事还会直接报error，是新版本的问题么？

**Comment by yuche** [comment]
是有这个问题，54 版本删除了一段对 bind 的处理。
https://github.com/NervJS/taro/commit/b3e28bc41987accda52ceb6d5c18637c761ccf8e
修复了这个问题并加了简单用例，后续再补一些复杂的。
