### ISSUE TITLE
组件名为Col时，Col的插槽将不会显示

### ISSUE THREAD

**Issue by so-diao** [NervJS/taro#1540]
**问题描述**
当自定义组件名为 Col 时，该组件的插槽将无法显示。改个名字例如 Column ，插槽又可以正常显示。
h5未测试，仅测试微信小程序。

**复现步骤**

```js
// Col组件
export default class Col extends Component {
    render() {
        return (
            <View className='Col'>
                Col
                {this.props.children}
            </View>
        )
    }
}
```
```js
export default class Index extends Component {
	render () {
		return (
			<View className='index'>
				<Col>
					插槽
				</Col>
				<Text>Hello world!</Text>
			</View>
		)
	}
}
```

**期望行为**
是因为什么原因呢？
是否还有其他字段？

**报错信息**

无报错

**系统信息**

 - 操作系统: [Windows 7]
 - Taro 版本 [ v1.2.0-beta.16]
 - Node.js 版本 [v10.7.0]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
在 https://github.com/NervJS/taro/commit/cd48f4b88d7fbc460634099275301ad109cf5b26 之后，现在自定义组件 + `img` + `import`(不区分大小写) 不可以作为自定义组件
