### ISSUE TITLE
使用了dva的 effects 后 , 页面报错

### ISSUE THREAD

**Issue by karchinkong** [NervJS/taro#1543]
![image](https://user-images.githubusercontent.com/16110331/50067591-8a964100-01fc-11e9-9d63-2a394e4a851c.png)

具体就是增加了这个effects之后，页面直接抛出错误。

![Uploading image.png…]()

请问这是要加 babel-pollyfill吗？

**Comment by zkqiang** [comment]
@karchinkong 你好，我遇到同样的问题，请问你后来如何解决的？
