### ISSUE TITLE
百度小程序swan模版编译结果错误

### ISSUE THREAD

**Issue by suyingtao** [NervJS/taro#1544]
**问题描述**
自定义组件的render中定义的变量与state中变量重名时，编译后的swan模版将二者视为同一变量。

**复现步骤**
```js
// 自定义组件中的render函数
render() {
    const data = 'xxx';
    return <view>{this.state.data + data}</view>
}

// 编译后swan文件
<block>
    <view privateTriggerObserer="{{ _triggerObserer }}">{{data + data}}</view>
</block>

// html：
<view privateTriggerObserer>xxxxxx</view>
```

**期望行为**
编译后能将二者区分开

**报错信息**
无

**系统信息**

 - 操作系统: mac os
 - Taro 版本: 1.2.0-beta.4
 - Node.js 版本: v8.11.3
 - 报错平台: 百度小程序

**Comment by luckyadam** [comment]
render 中定义的变量暂时不要与 state 中变量重名

**Comment by yuche** [comment]
正常编译器支持估计没那么快，目前打算是用 eslint 来解决。在 https://github.com/NervJS/taro/issues/1385 这里追踪吧。

**Comment by yuche** [comment]
Duplicate of #1385
