### ISSUE TITLE
传 props 会丢失 object 里面的 function 属性

### ISSUE THREAD

**Issue by Jeepeng** [NervJS/taro#1546]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
const obj = { a: 1, b: function() {} };
<MyComponent obj={obj} />
```
在`MyComponent`里获取`obj = { a: 1 };`

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: macOS
 - Taro 版本 v1.2.0-beta.16
 - Node.js 版本 v10.14.1
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
我在 https://github.com/NervJS/taro/issues/1448#issuecomment-446059815 统一回答了这类问题。就在那统一追踪这个特性吧。

**Comment by yuche** [comment]
Duplicate of #1448
