### ISSUE TITLE
使用h5运行时Navigate组件没有渲染

### ISSUE THREAD

**Issue by bingxl** [NervJS/taro#1547]
**问题描述**
在jsx中有<Navigate>内容, 运行后在微信小程序,百度小程序上都没问题, 然后使用h5运行后<navigate>元素里的内容都没有了, 查看网页源码页没有对应的节点

[复现问题的步骤]
render() 里使用<Navigate>, 之后在h5模式下运行

[或者可以直接贴源代码，能贴文字就不要截图]

```jsx
// 这里可以贴代码
<View className='fixed-footer fixed'>
     <View className='goto-active'>
            <GotoActive />
      </View>
      <Navigator url='/pages/addplaza/main' className='add-plaza'>
            <Image src={require('../../images/edit_bg.png')} alt='发布研说' className='add-plaza--image' />
      </Navigator>
</View>

```

**期望行为**
渲染Navigate元素

**报错信息**
无

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本:  v1.2.0-beta.16
 - Node.js 版本 v11.4.0
 - 报错平台 h5

**Comment by luckyadam** [comment]
`Navigator` 组件在 H5 端还没实现，暂时用 Taro 的跳转 API 来做吧
