### ISSUE TITLE
不支持导入第三方npm包

### ISSUE THREAD

**Issue by FaureWu** [NervJS/taro#155]
安装好的第三方包，引入到app.js中，并没有拷贝到dist/npm目录下

**Comment by FaureWu** [comment]
因为第三发包的错误，导致没有导入进来 @zacksleo

**Comment by zacksleo** [comment]
有没有报什么错误呢？ 贴下相关代码看看， 也许是不支持？

**Comment by FaureWu** [comment]
第三方语法错误没有抛出错误，那个第三方个人写的，改正好了就正常导入了，不过这个taro出错太难定位了，基本没给有用信息，都靠猜测，目前还有这个错误不知道怎么回事


生成  依赖文件  dist/models/test.js
{ SyntaxError: Unexpected token name «Object», expected punc «,»
    at JS_Parse_Error.get (eval at <anonymous> (/Volumes/Code/taro-startkit/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:73:23)
    at formatError (util.js:640:16)
    at formatValue (util.js:544:18)
    at inspect (util.js:324:10)
    at format (util.js:191:12)
    at Console.log (console.js:130:21)
    at scriptFiles.forEach (/Volumes/Code/taro-startkit/node_modules/@tarojs/cli/src/weapp.js:915:27)
    at <anonymous>
  message: 'Unexpected token name «Object», expected punc «,»',
  filename: '0',
  line: 22,
  col: 26,
  pos: 966 }

**Comment by FaureWu** [comment]
models/test.js

`import ajax from '../utils/ajax'

const namespace = 'test'

export default {
  namespace,

  state: {},

  effects: {
    async queryTest({ payload }, { put }) {
      const { data } = await ajax.get(API.getTest, payload)
      put({
        type: 'save',
        payload: data,
      })
    },
  },

  reducers: {
    save({ payload }) {
      return payload
    },
  },
}

export { namespace }
`

**Comment by zacksleo** [comment]
还是代码有问题，taro 构建时会进行 eslint 检查，这个 utils 文件 应该是没通过格式检查啊

**Comment by yuche** [comment]
@zacksleo eslint 检查失败不会影响编译。

楼主这个问题可能是 redux-saga 相关的，请查看：https://github.com/NervJS/taro/issues/46

**Comment by FaureWu** [comment]
@zacksleo eslint格式检查是过了的，问题是因为我设置defineConstants给的是对象，没有通过JSON.stringify处理，然后在utils中引用了constants导致报错，但是我觉得taro对于用户的代码语法报错太不友好了，一个问题需要，不断裁剪代码来定位

**Comment by FaureWu** [comment]
@yuche 没有用redux-saga，自己封装了一个类dva-core的redux框架 [zoro](https://github.com/FaureWu/zoro) 基于async/await

**Comment by yuche** [comment]
@FaureWu 晚上我们发一个版本会有 babel 那样的报错。
现在试试在文件头部**首行**：
```
import '@tarojs/async-await';
```

**Comment by FaureWu** [comment]
@yuche 这个加了哈，问题已经找到了的，感谢

**Comment by yuche** [comment]
不谢，原因还是在我们，如果报错能定位代码位置，像你这样有经验的开发者应该能自己解决问题。
