### ISSUE TITLE
在图片的处理上有没有什么好的方案

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#1550]
能否允许在image的src里直接引用相对路径。
在打包时，将image相对路径的图片和css中的图片，单独打包到一个文件夹中。
url替换为带有hash的图片路径。并支持添加cdn前缀。

或者各位在静态图片的处理上有没有什么好的方案，可以供参考一下？

**Comment by loveonelong** [comment]
#998 这个issues提到的思路好像还可以？

**Comment by loveonelong** [comment]
@wujjpp 能分享一下你们的方案么

**Comment by DiamondYuan** [comment]
可以自己写一个 loader

**Comment by wujjpp** [comment]
@loveonelong 我们现在就是自己写了2个loader, 一个用于处理css里面的url, 一个用于处理 js 中import 进来的image

___babel-plugin-transform-image-to-url.js___
```javascript
/**
 * Created by Wu Jian Ping on 2018/11/1.
 */

const pathUtils = require('path') //eslint-disable-line
const utils = require('./utils') //eslint-disable-line

module.exports = function ({types: t}) {
  return {
    visitor: {
      VariableDeclarator(path, state){
        let node = path.node
        if (node && node.init) {
          if (utils.isImage(node.init.value) && !utils.isUrl(node.init.value)) {
            let source = pathUtils.join(utils.getAppPath(), 'src', node.init.value)
            let target = pathUtils.join(utils.getAppPath(), state.opts.staticDirectory, utils.getFileNameWithHash(source))
            utils.createDirIfNotExists(pathUtils.dirname(target))
            utils.copyFile(source, target)
            node.init = t.stringLiteral(state.opts.publicPath + pathUtils.basename(target))
          }
        }
      }
    }
  }
}
```

___postcss-plugin-image-to-url.js___

```javascript
/**
 * Created by Wu Jian Ping on 2018/11/1.
 */

const postcss = require('postcss') //eslint-disable-line
const path = require('path') //eslint-disable-line
const utils = require('./utils') //eslint-disable-line

const URL_PATTERNS = [
  /(url\(\s*['"]?)([^"')]+)(["']?\s*\))/g,
  /(AlphaImageLoader\(\s*src=['"]?)([^"')]+)(["'])/g
]

const getPattern = decl => URL_PATTERNS.find((pattern) => pattern.test(decl.value))

module.exports = postcss.plugin('postcss-transform-url', (options) => {
  options = options || {}

  return function (styles, result) {
    const opts = result.opts
    const from = opts.from ? path.dirname(opts.from) : '.'

    styles.walkDecls(decl => {

      const isNotUrl = !utils.isUrl(decl.value)

      if (isNotUrl) {
        const pattern = getPattern(decl)

        if (!pattern) return

        decl.value = decl.value.replace(pattern, (matched, before, url, after) => {
          let index = url.indexOf('?')
          if (index !== -1) {
            url = url.substr(0, index)
          }
          let source = path.join(from, url)
          if (utils.isFont(url)) {
            let file = utils.getFile(source)
            let encodeStr = utils.encodeFile(file, 'base64', true)
            return `${before}${encodeStr}${after}`
          } else if (utils.isImage(url)) {
            let target = path.join(utils.getAppPath(), options.staticDirectory, utils.getFileNameWithHash(source))
            utils.createDirIfNotExists(path.dirname(target))
            utils.copyFile(source, target)
            return `${before}${options.publicPath}${path.basename(target)}${after}`
          }
        })
      }
    })
  }
})
```

___utils.js___
```javascript
/**
 * Created by Wu Jian Ping on 2018/11/1.
 */

const fs = require('fs') // eslint-disable-line
const mkdirp  = require('mkdirp') // eslint-disable-line
const xxhashjs = require('xxhashjs') // eslint-disable-line
const path = require('path') // eslint-disable-line
const mime = require('mime') // eslint-disable-line

const REG_IMAGE = /\.(png|jpe?g|gif|bpm|svg)(\?.*)?$/
const REG_URL = /((http|ftp|https):\/\/)[\w\-_]+(\.[\w\-_]+)+([\w\-.,@?^=%&amp;:/~+#]*[\w\-@?^=%&amp;/~+#])?/
const REG_MEDIA = /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/
const REG_FONT = /\.(woff2?|eot|ttf|otf|svg)(\?.*)?$/

const copyFile = (source, target) =>  {
    fs.copyFileSync(source, target)
}

const createDirIfNotExists = dir => {
    mkdirp.sync(dir)
}

const getFileNameWithHash = fileName => {
    let buf = fs.readFileSync(fileName)
    let digest = xxhashjs.h32(0).update(buf).digest()
    let extName = path.extname(fileName)
    let fileNameWithoutExt = path.basename(fileName, extName)
    return `${fileNameWithoutExt}_${digest}${extName}`
}

const getAppPath = () => process.cwd()

const isImage = val => REG_IMAGE.test(val)

const isUrl = val => REG_URL.test(val)

const isMedia = val => REG_MEDIA.test(val)

const isFont = val => REG_FONT.test(val)

const getFile = filePath => {
    return {
        path: filePath,
        contents: fs.readFileSync(filePath),
        mimeType: mime.getType(filePath)
    };
}

const optimizedSvgEncode = (svgContent) => {
    const result = encodeURIComponent(svgContent)
        .replace(/%3D/g, '=')
        .replace(/%3A/g, ':')
        .replace(/%2F/g, '/')
        .replace(/%22/g, "'")
        .replace(/%2C/g, ',')
        .replace(/%3B/g, ';')

    // Lowercase the hex-escapes for better gzipping
    return result.replace(/(%[0-9A-Z]{2})/g, (matched, AZ) => {
        return AZ.toLowerCase()
    })
}

const encodeFile = (file, encodeType, shouldOptimizeSvgEncode) => {
    const dataMime = `data:${file.mimeType}`

    if (encodeType === 'base64') {
        return `${dataMime};base64,${file.contents.toString('base64')}`
    }

    const encodeFunc = encodeType === 'encodeURI' ? encodeURI : encodeURIComponent

    const content = file.contents.toString('utf8')
    // removing new lines
        .replace(/\n+/g, '')

    let encodedStr = (shouldOptimizeSvgEncode && encodeType === 'encodeURIComponent')
        ? optimizedSvgEncode(content)
        : encodeFunc(content)

    encodedStr = encodedStr
        .replace(/%20/g, ' ')
        .replace(/#/g, '%23')

    return `${dataMime},${encodedStr}`
};

module.exports = { // eslint-disable-line
    copyFile,
    createDirIfNotExists,
    getFileNameWithHash,
    getAppPath,
    isImage,
    isUrl,
    isMedia,
    isFont,
    getFile,
    encodeFile
}

```

**Comment by loveonelong** [comment]
@wujjpp 谢谢分享

**Comment by LeachZhou** [comment]
@loveonelong 大兄弟，现在由我来把taro项目中的图片版本控制做完整了，你当时咋不做完这个再走呢

**Comment by patchBig** [comment]
> @loveonelong
> 
> 我们现在就是自己写了2个loader: 一个用于处理css里面的url, 一个用于处理 js 中import 进来的image
> 
> config 可以参照 #998
> 
> _**babel-plugin-transform-image-to-url.js**_
> 
> ```js
> /**
>  * Created by Wu Jian Ping on 2018/11/1.
>  */
> 
> const pathUtils = require('path') //eslint-disable-line
> const utils = require('./utils') //eslint-disable-line
> 
> module.exports = function ({types: t}) {
>   return {
>     visitor: {
>       VariableDeclarator(path, state){
>         let node = path.node
>         if (node && node.init) {
>           if (utils.isImage(node.init.value) && !utils.isUrl(node.init.value)) {
>             let source = pathUtils.join(utils.getAppPath(), 'src', node.init.value)
>             let target = pathUtils.join(utils.getAppPath(), state.opts.staticDirectory, utils.getFileNameWithHash(source))
>             utils.createDirIfNotExists(pathUtils.dirname(target))
>             utils.copyFile(source, target)
>             node.init = t.stringLiteral(state.opts.publicPath + pathUtils.basename(target))
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> _**postcss-plugin-image-to-url.js**_
> 
> ```js
> /**
>  * Created by Wu Jian Ping on 2018/11/1.
>  */
> 
> const postcss = require('postcss') //eslint-disable-line
> const path = require('path') //eslint-disable-line
> const utils = require('./utils') //eslint-disable-line
> 
> const URL_PATTERNS = [
>   /(url\(\s*['"]?)([^"')]+)(["']?\s*\))/g,
>   /(AlphaImageLoader\(\s*src=['"]?)([^"')]+)(["'])/g
> ]
> 
> const getPattern = decl => URL_PATTERNS.find((pattern) => pattern.test(decl.value))
> 
> module.exports = postcss.plugin('postcss-transform-url', (options) => {
>   options = options || {}
> 
>   return function (styles, result) {
>     const opts = result.opts
>     const from = opts.from ? path.dirname(opts.from) : '.'
> 
>     styles.walkDecls(decl => {
> 
>       const isNotUrl = !utils.isUrl(decl.value)
> 
>       if (isNotUrl) {
>         const pattern = getPattern(decl)
> 
>         if (!pattern) return
> 
>         decl.value = decl.value.replace(pattern, (matched, before, url, after) => {
>           let index = url.indexOf('?')
>           if (index !== -1) {
>             url = url.substr(0, index)
>           }
>           let source = path.join(from, url)
>           if (utils.isFont(url)) {
>             let file = utils.getFile(source)
>             let encodeStr = utils.encodeFile(file, 'base64', true)
>             return `${before}${encodeStr}${after}`
>           } else if (utils.isImage(url)) {
>             let target = path.join(utils.getAppPath(), options.staticDirectory, utils.getFileNameWithHash(source))
>             utils.createDirIfNotExists(path.dirname(target))
>             utils.copyFile(source, target)
>             return `${before}${options.publicPath}${path.basename(target)}${after}`
>           }
>         })
>       }
>     })
>   }
> })
> ```
> 
> _**utils.js**_
> 
> ```js
> /**
>  * Created by Wu Jian Ping on 2018/11/1.
>  */
> 
> const fs = require('fs') // eslint-disable-line
> const mkdirp  = require('mkdirp') // eslint-disable-line
> const xxhashjs = require('xxhashjs') // eslint-disable-line
> const path = require('path') // eslint-disable-line
> const mime = require('mime') // eslint-disable-line
> 
> const REG_IMAGE = /\.(png|jpe?g|gif|bpm|svg)(\?.*)?$/
> const REG_URL = /((http|ftp|https):\/\/)[\w\-_]+(\.[\w\-_]+)+([\w\-.,@?^=%&amp;:/~+#]*[\w\-@?^=%&amp;/~+#])?/
> const REG_MEDIA = /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/
> const REG_FONT = /\.(woff2?|eot|ttf|otf|svg)(\?.*)?$/
> 
> const copyFile = (source, target) =>  {
>     fs.copyFileSync(source, target)
> }
> 
> const createDirIfNotExists = dir => {
>     mkdirp.sync(dir)
> }
> 
> const getFileNameWithHash = fileName => {
>     let buf = fs.readFileSync(fileName)
>     let digest = xxhashjs.h32(0).update(buf).digest()
>     let extName = path.extname(fileName)
>     let fileNameWithoutExt = path.basename(fileName, extName)
>     return `${fileNameWithoutExt}_${digest}${extName}`
> }
> 
> const getAppPath = () => process.cwd()
> 
> const isImage = val => REG_IMAGE.test(val)
> 
> const isUrl = val => REG_URL.test(val)
> 
> const isMedia = val => REG_MEDIA.test(val)
> 
> const isFont = val => REG_FONT.test(val)
> 
> const getFile = filePath => {
>     return {
>         path: filePath,
>         contents: fs.readFileSync(filePath),
>         mimeType: mime.getType(filePath)
>     };
> }
> 
> const optimizedSvgEncode = (svgContent) => {
>     const result = encodeURIComponent(svgContent)
>         .replace(/%3D/g, '=')
>         .replace(/%3A/g, ':')
>         .replace(/%2F/g, '/')
>         .replace(/%22/g, "'")
>         .replace(/%2C/g, ',')
>         .replace(/%3B/g, ';')
> 
>     // Lowercase the hex-escapes for better gzipping
>     return result.replace(/(%[0-9A-Z]{2})/g, (matched, AZ) => {
>         return AZ.toLowerCase()
>     })
> }
> 
> const encodeFile = (file, encodeType, shouldOptimizeSvgEncode) => {
>     const dataMime = `data:${file.mimeType}`
> 
>     if (encodeType === 'base64') {
>         return `${dataMime};base64,${file.contents.toString('base64')}`
>     }
> 
>     const encodeFunc = encodeType === 'encodeURI' ? encodeURI : encodeURIComponent
> 
>     const content = file.contents.toString('utf8')
>     // removing new lines
>         .replace(/\n+/g, '')
> 
>     let encodedStr = (shouldOptimizeSvgEncode && encodeType === 'encodeURIComponent')
>         ? optimizedSvgEncode(content)
>         : encodeFunc(content)
> 
>     encodedStr = encodedStr
>         .replace(/%20/g, ' ')
>         .replace(/#/g, '%23')
> 
>     return `${dataMime},${encodedStr}`
> };
> 
> module.exports = { // eslint-disable-line
>     copyFile,
>     createDirIfNotExists,
>     getFileNameWithHash,
>     getAppPath,
>     isImage,
>     isUrl,
>     isMedia,
>     isFont,
>     getFile,
>     encodeFile
> }
> ```
![image](https://user-images.githubusercontent.com/25219300/59427430-35cf2e00-8e0d-11e9-833e-bdfa9dd37a0b.png)
Hello 想请教一下，在编译 src/utils/wx_request.js 这个 js 的时候；它是在 /Users/yang/work/code/mds-mina-yun-fed/src/utils 这个目录里面去查找 babel-plugin-transform-image-to-url 这个文件；感觉它不应该是在 src 这个目录里面去查找吗？

**Comment by wujjpp** [comment]
@patchBig trao的代码需要稍微改一下的

**Comment by cjz9032** [comment]
> @patchBig trao的代码需要稍微改一下的

这里为什么还需要改呢 我看你上个PR不是merge了么
