### ISSUE TITLE
[Taro4.0.0-beta.45] - solid响应式失效问题

### ISSUE THREAD

**Issue by phy-lei** [NervJS/taro#15501]
### 相关平台
微信小程序

**重现链接仓库地址**
https://github.com/phy-lei/taro-solid-vite

**taro version**
4.0.0-beta.45

**小程序基础库: 3.4.0**
**使用框架: Solidjs**

![image](https://github.com/NervJS/taro/assets/58167763/6f61b1fe-2f47-4958-b1d6-1083405c0725)

### 复现步骤
拉取仓库，pnpm i，pnpm build:weapp  
- 先点击add
- 在点击set styles

### 期望结果
add数字保持不变，随机数保持不变

### 实际结果
add数字变为0，随机数改变

### 环境信息
```
Taro CLI 4.0.0-beta.45 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    npmPackages:
      @tarojs/cli: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/components: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/helper: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-framework-react: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-alipay: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-h5: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-jd: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-qq: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-swan: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-tt: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/plugin-platform-weapp: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/runtime: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/shared: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/taro: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/taro-loader: 4.0.0-beta.45 => 4.0.0-beta.45 
      @tarojs/webpack5-runner: 4.0.0-beta.45 => 4.0.0-beta.45 
      babel-preset-taro: 4.0.0-beta.45 => 4.0.0-beta.45 

```

### 其他
在准备将自己solid插件适配vite的编译时，我发现taro4.0已经在实现solid的编译了，着实是很高兴，然后看了下里面的代码实现，发现跟当时我实现的思路差不多，都是基于solid-js/universal去实现的，但是对于h函数来说，solid其实是不需要的，这可以在我这篇文章[taro-solid小程序插件版本迭代](https://juejin.cn/post/7342148728135319564)能够说明，如果官方比较对于solid的推送比较积极，我可以全力协助相关solid的迭代，我就不在我的仓库那里继续迭代4.0关于vite的适配了。期待获得大佬们的回复 @ZakaryCode

**Comment by ZakaryCode** [comment]
> 在准备将自己solid插件适配vite的编译时，我发现taro4.0已经在实现solid的编译了，着实是很高兴，然后看了下里面的代码实现，发现跟当时我实现的思路差不多，都是基于solid-js/universal去实现的，但是对于h函数来说，solid其实是不需要的，这可以在我这篇文章[taro-solid小程序插件版本迭代](https://juejin.cn/post/7342148728135319564)能够说明，如果官方比较对于solid的推送比较积极，我可以全力协助相关solid的迭代，我就不在我的仓库那里继续迭代4.0关于vite的适配了。期待获得大佬们的回复 @ZakaryCode

欢迎一起共建，其实因为这个实现在你的 PR 之后，很大程度上有所借鉴，这个在对应 PR 上也有阐述。另外对于 h 函数，一定程度上还是有必要性，在 taro-plugin-solid 中示例更多还是使用 jsx 形式去转换 view 等组件，而非通过 @tarojs/components 去引入，当前在插件中实现 h 函数方法主要也应对于该情况引入的字符串标签对应（当然此处后续可能会有所调整）。

当前 Solid 的适配应该还有挺多待完善的内容，包括 web 端的组件库、适配器等，如果大佬愿意一起参与负责 solid 端的内容就再好不过了

**Comment by ZakaryCode** [comment]
当前 issue 可能短时间内没办法跟进，之后会抽一段时间出来专项解决 solid 相关的 issue 问题，如果 @phy-lei  大佬有时间也可以帮忙提交 PR 修复看看，我们也会抽时间快速跟进下～

**Comment by phy-lei** [comment]
> > 在准备将自己solid插件适配vite的编译时，我发现taro4.0已经在实现solid的编译了，着实是很高兴，然后看了下里面的代码实现，发现跟当时我实现的思路差不多，都是基于solid-js/universal去实现的，但是对于h函数来说，solid其实是不需要的，这可以在我这篇文章[taro-solid小程序插件版本迭代](https://juejin.cn/post/7342148728135319564)能够说明，如果官方比较对于solid的推送比较积极，我可以全力协助相关solid的迭代，我就不在我的仓库那里继续迭代4.0关于vite的适配了。期待获得大佬们的回复 @ZakaryCode
> 
> 欢迎一起共建，其实因为这个实现在 #13607 PR 之后，很大程度上有所借鉴，这个在对应 PR 上也有阐述。另外对于 h 函数，一定程度上还是有必要性，在 taro-plugin-solid 中示例更多还是使用 jsx 形式去转换 view 等组件，而非通过 @tarojs/components 去引入，当前在插件中实现 h 函数方法主要也应对于该情况引入的字符串标签对应（当然此处后续可能会有所调整）。
> 
> 当前 Solid 的适配应该还有挺多待完善的内容，包括 web 端的组件库、适配器等，如果大佬愿意一起参与负责 solid 端的内容就再好不过了

我当时也是看了这个pr参考来做的，在solid中，他使用的babel已经进行了对应的编译，而jsx中使用的taro/component中的标签也是为了能够跨端，我也理解这个需求，但是目前对于这个的编译，solid确实是存在createComponent与createElement的冲突。我后续想想办法看，能否做到继续基于此做到编译正确。

**Comment by ZakaryCode** [comment]
> > > 在准备将自己solid插件适配vite的编译时，我发现taro4.0已经在实现solid的编译了，着实是很高兴，然后看了下里面的代码实现，发现跟当时我实现的思路差不多，都是基于solid-js/universal去实现的，但是对于h函数来说，solid其实是不需要的，这可以在我这篇文章[taro-solid小程序插件版本迭代](https://juejin.cn/post/7342148728135319564)能够说明，如果官方比较对于solid的推送比较积极，我可以全力协助相关solid的迭代，我就不在我的仓库那里继续迭代4.0关于vite的适配了。期待获得大佬们的回复 @ZakaryCode
> > 
> > 
> > 欢迎一起共建，其实因为这个实现在 #13607 PR 之后，很大程度上有所借鉴，这个在对应 PR 上也有阐述。另外对于 h 函数，一定程度上还是有必要性，在 taro-plugin-solid 中示例更多还是使用 jsx 形式去转换 view 等组件，而非通过 @tarojs/components 去引入，当前在插件中实现 h 函数方法主要也应对于该情况引入的字符串标签对应（当然此处后续可能会有所调整）。
> > 当前 Solid 的适配应该还有挺多待完善的内容，包括 web 端的组件库、适配器等，如果大佬愿意一起参与负责 solid 端的内容就再好不过了
> 
> 我当时也是看了这个pr参考来做的，在solid中，他使用的babel已经进行了对应的编译，而jsx中使用的taro/component中的标签也是为了能够跨端，我也理解这个需求，但是目前对于这个的编译，solid确实是存在createComponent与createElement的冲突。我后续想想办法看，能否做到继续基于此做到编译正确。

好嘞，有需要可以找我微信支持，微信号与 GitHub 同名
