### ISSUE TITLE
事件绑定无效带 短横 “-”的事件名

### ISSUE THREAD

**Issue by nailfar** [NervJS/taro#1559]
**问题描述**
使用的 vant ui组件,组件提供的 事件  click-icon
在 taro 中使用  <vant-field   onClick-icon ={ this.clickHandler } /> 
事件被转义为 bindclick-icon  然而并不能触发this.clickHandler , 改为 bind:click-icon 才有效； 或者修改组件源码 去掉短横 ，事件处理的机制不是很完善 有待加强

**复现步骤**
[复现问题的步骤]
见问题描述

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
期望支持 带短横的事件名

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: win10
 - Taro 版本 1.2.0-beta.6
 - Node.js 版本 v8.11.1
 - 报错平台 [ weapp]

**补充信息**

**Comment by yuche** [comment]
这类使用第三方组件的极端情况确实没有考虑到，这个组件库也没有遵循小程序的事件命名规范，导致小程序的社区更割裂了。
