### ISSUE TITLE
使用redux报的错误是什么问题呢

### ISSUE THREAD

**Issue by yinchuanjiang** [NervJS/taro#156]
![image](https://user-images.githubusercontent.com/20211697/41644730-8a5c53a2-74a1-11e8-9936-c23be7f161f4.png)
![image](https://user-images.githubusercontent.com/20211697/41644858-edbb1d98-74a1-11e8-9e89-f9bcb5e736d7.png)

**Comment by zacksleo** [comment]
删除 node_modules 及其缓存文件重新安装下依赖？

**Comment by yinchuanjiang** [comment]
我试试

**Comment by yinchuanjiang** [comment]
可以了十分感谢
