### ISSUE TITLE
默认打开浏览器时，可以优先使用 localhost 而不是一个 IP 地址吗？

### ISSUE THREAD

**Issue by Jeff-Tian** [NervJS/taro#15608]
### 这个特性解决了什么问题？
如果使用 http://localhost:10086 会更好一点，但不知道从哪个版本开始，总是默认使用 http://ip:100i86 了。尝试通过 --host localhost 指定主机名，也不起作用。

### 这个 API 长什么样？
默认打开 http://localhost:10086

**Comment by ZakaryCode** [comment]
自行配制下 [devServer.open](https://nervjs.github.io/taro-docs/docs/config-detail#h5devserver) 即可
