### ISSUE TITLE
componentWillReceiveProps 触发异常

### ISSUE THREAD

**Issue by KevinGong2013** [NervJS/taro#1561]
**问题描述**
如果在componentWillReceiveProps 中 dispatch redux 的action，this.props 和nextProps 的值会异常

**复现步骤**
1. git clone https://github.com/KevinGong2013/redux-will-receive-props-demo
2. npm run dev:weapp
3. 点击 `+`
4. ide 大概会卡死，componentWillReceiveProps 无限调用

**期望行为**
componentWillReceiveProps 调用过一次 this.props 应该更新为 nextProps的值， 然而没有更新

**系统信息**

 - 操作系统: [Mac OS X 10.14.1 (18B75)]
 - Taro 版本 [v.1.2.0]
 - Node.js 版本 [v11.2.0]
 - 报错平台 [alipay, weapp]

**Comment by HuiguangChu** [comment]
IMO, 这个问题应该是跟Taro 没有关系。 componentWillReceiveProps 在react中被调用多次是正常的，是因为你的props 一直在更新，而且你设置的条件一直成立， 所以会dead loop。 Taro 中条件比较，要求非特殊情况下要用 === 而不是== 吧？ 尝试一下，改一下条件 if（nextProps.counter.num ! ==  this.props.counter.num）试试？

**Comment by KevinGong2013** [comment]
这个有没有修复的排期呀， 或者推荐的workaround办法呀～

**Comment by JianwenXu** [comment]
遇到同样的问题，在 componentWillReceiveProps 里 执行 action ，因为状态没有更新执行了几百次

**Comment by luckyadam** [comment]
明天会进行修复

**Comment by KevinGong2013** [comment]
大佬这个问题有计划了不 😢

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/50437179-b368b580-0923-11e9-8b51-dc8e02efa74b.png)
这样写在小程序中肯定会导致不断执行

因为 `this.props.dispatchDoNothing()` 这个 action 什么都不做，但是会触发 `componentWillReceiveProps` ，这个时候 this.props 还没有更新

不建议这么写，你可以再增加其他判断条件

**Comment by KevinGong2013** [comment]
那好吧 这里提供一个workaround方法

<img width="511" alt="screen shot 2018-12-26 at 16 47 32" src="https://user-images.githubusercontent.com/5820203/50439733-0c3d4b80-092e-11e9-8e5c-a8fe4b112fc0.png">

**Comment by Cleam** [comment]
如果考虑只执行一次action的话，也可以这样：
```javascript
  componentWillReceiveProps(nextProps: IProps) {
    console.log(this.props, nextProps)
    if (!this.flag) {
      this.flag = true;
      this.props.dispatchDoNothing()
    }
  }
```
但是请问官方有更好的解决方案吗？为啥`this.props`没更新？
