### ISSUE TITLE
[Feature Request] Functional Components

### ISSUE THREAD

**Issue by luankefei** [NervJS/taro#157]
希望能支持函数组件，提高开发效率和代码的可维护性
![image](https://user-images.githubusercontent.com/7992920/41898531-d7c254ec-795c-11e8-89e4-1aba3975b087.png)

**Comment by zacksleo** [comment]
由于小程序的原因，应该支持不了

https://github.com/NervJS/taro/blob/master/packages/eslint-plugin-taro/docs/no-stateless-function.md

**Comment by luckyadam** [comment]
阔以支持，不过得单文件单函数组件，感觉这样的话也失去了函数式组件的优势

**Comment by yuche** [comment]
你这个图里贴这个是支持的，如果 ESLint 没报错应该就支持。

`renderView` 是一个函数表达式而不是函数声明。

```javascript
<View>
  {renderView} /*  这里应该写引用不是调用 `renderView()` */ 
</View>
```

建议楼主看一下文档和 JSX 写法。

**Comment by luankefei** [comment]
抱歉，刚刚看到，栗子写的有问题。希望能够支持函数组件。

**Comment by yuche** [comment]
close via 4aa409fb1fc5e6197a6f69e7392519716efb9d13
