### ISSUE TITLE
发现 taro h5页面进去新页面 更改了标题  返回后 标题名字没有改变回原来的标题

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1571]
发现 taro h5页面进去新页面 更改了标题  返回后 标题名字没有改变回原来的标题

Taro CLI 1.2.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by Littly** [comment]
更新到1.2.2试试~

**Comment by xingwen93** [comment]
从1.2.1到1.2.2已经正确了
