### ISSUE TITLE
多重循环会出现参数没定义

### ISSUE THREAD

**Issue by daijiaoluoxinghui** [NervJS/taro#1573]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

   自定义了一个数组，map三次以获得最内层的数据，但是map经常会出现，自定义参数不存在
编译完，g这个第三层参数会跑到第二层的前面，这时候g本来就不存在
  var order_view = setdata.map(function (h) {
        h.order_list.map(function (t) {
          var $anonymousCallee__58 = g.t.extend_order_goods.map(function (g) {
            g = {
              $original: (0, _index.internal_get_original)(g)
            };

            console.log(g.$original.goods_num, 'asd');

**复现步骤**
[复现问题的步骤]

npm run dev:weapp
任意一个 component
贴上下面的render和return

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
render(
const setdata = [{
      order_list: [{
        extend_order_goods: [{
          goods_num: 1
          }]
        }],
      order_list: [{
        extend_order_goods: [{
          goods_num: 2
          }]
        }],
      order_list: [{
        extend_order_goods: [{
          goods_num: 3
          }]
        }],
      order_list: [{
        extend_order_goods: [{
          goods_num: 4
          }]
        }],
      order_list: [{
        extend_order_goods: [{
          goods_num: 5
          }]
        }],
      }]
    const order_view = setdata.map(h => {
      h.order_list.map(t => {
        t.extend_order_goods.map(g => {
          console.log(g.goods_num, 'asd')
          return (<View>{g.goods_num}</View>)
        })
      })
    })
)
return(
   <View>{order_view}</View>
)


```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [ Windows 7]
 - Taro 版本 [ v.1.1.9
 - Node.js 版本  [v 10.9.0]
 - 报错平台 [ weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
看了文档和issues，有说版本的，有说map格式的，我有点搞不清楚了。有时候编译还会找不到&original

**Comment by yuche** [comment]
老哥，把代码排版一下。现在完全看不清了。
另外你可以升级到 1.2.0 ，可能你这个问题已经修复了。

**Comment by yuche** [comment]
你的代码前两级循环没有写 return，当你的不想写 return 时，在 ES6 的语法应该使用 `()` 包裹住而不是使用 `{}`。

尝试改成这样应该能跑：
```js
const order_view = setdata.map(h => (
        <Block>
          {
            h.order_list.map(t => (
              <Block>
                {t.extend_order_goods.map(g => {
                return (<View>{g.goods_num}</View>)
              })}
              </Block>
            ))
          }
        </Block>
      ))
```

**Comment by HuiguangChu** [comment]
es5 map 函数需要return，es6 不想写return需要(), for example, const myFunction = () => ({value: 'test'}),

**Comment by daijiaoluoxinghui** [comment]
按你的写法，结果只有5。1,2,3,4没有出现。我在react里是有每个map都return的。在Taro里试了几种写法，然后被各种报错弄得意识模糊了，就是找不到正确的写法。

`   const order_view = setdata.map(h => (
      <View>
        {
          h.order_list.map(t => (
            <View>
              {
                t.extend_order_goods.map(g => {
                  return (<View>{g.goods_num}</View>)
                })
              }
            </View>))
        }
      </View>
    ))`
`
 <View className={"scroll_y"}>
          <View>
            <View>
              <View>5</View>
            </View>
          </View>
        </View>`

**Comment by daijiaoluoxinghui** [comment]
@yuche 按你的写法，得到只有5。1,2,3,4没有出现。我在react里map都有return，但在Taro里，不知道是不是格式要求比较严格，换了几种写法，然后被各种报错弄得意识模糊。找不到正确的写法。
代码和git使用都是生手 praypraypray



 `

 const order_view = setdata.map(h => (


     <View>
        {
          h.order_list.map(t => (
            <View>
              {
                t.extend_order_goods.map(g => {
                  return (<View>{g.goods_num}</View>)
                })
              }
            </View>))
        }
      </View>
    ))`
` 

> 

> 
<View className={"scroll_y"}>

> 

          <View>
            <View>
              <View>5</View>
            </View>
          </View>
        </View>`

**Comment by fjc0k** [comment]
多重嵌套我遇到过，这种写法会报错：`() => (<Text />)`，这种写法正常：`() => { return <Text /> }`，当然这是在 1.1.9 ，1.2.0 尚未测试。

**Comment by daijiaoluoxinghui** [comment]
@fjc0k 我按照你说的每个map都加上了return，但还是只有最后一个数据
 #666 里也是这种情况

**Comment by yuche** [comment]
因为你这个代码正常就是应该只输出一个 `5`，哪怕在真的 React 也是如此：

https://codesandbox.io/s/3l5y0w9jq

**Comment by daijiaoluoxinghui** [comment]
对的，自定义的时候没分好~~~~~

**Comment by daijiaoluoxinghui** [comment]
那我是不是可以关闭这个问题了？

**Comment by yuche** [comment]
嗯，你修改一下你的数据结构应该就没问题了
