### ISSUE TITLE
Taro如何开启微信小程序的skyline，文档没有找到

### ISSUE THREAD

**Issue by chenweijianGZ** [NervJS/taro#15758]
### 这个特性解决了什么问题？
文档缺失，补全后方便所有开发者

### 这个 API 长什么样？
有一个独立的文档位置提供skyline的开启方式文档

**Comment by koppthe** [comment]
按微信小程序的文档配置即可

**Comment by 490626721** [comment]
> 按微信小程序的文档配置即可
 你看看你说的是人话吗？

**Comment by 490626721** [comment]
> 按微信小程序的文档配置即可

你看看你说的是人话吗？

**Comment by tutuxxx** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/migration/
