### ISSUE TITLE
How can I pass custom props

### ISSUE THREAD

**Issue by sehmbimanvir** [NervJS/taro#15798]
### 这个特性解决了什么问题？
We have custom base library for our platform and we can pass type props as <map type="google" /> in map component. How can I pass these custom attributes using tarojs.

After code compilation in base.wxml this code is generating
![image](https://github.com/NervJS/taro/assets/10684810/1051255f-0b2e-4926-820d-30f0ee8846f6)

I want to pass type attribute as mentioned below.

![image](https://github.com/NervJS/taro/assets/10684810/609fb337-0dd8-49fc-9504-931a2bd7da5f)

How can I do this?

### 这个 API 长什么样？
No API

**Comment by sehmbimanvir** [comment]
After code compilation in base.wxml this code is generating
![image](https://github.com/NervJS/taro/assets/10684810/1051255f-0b2e-4926-820d-30f0ee8846f6)

I want to pass type attribute as mentioned below.

![image](https://github.com/NervJS/taro/assets/10684810/609fb337-0dd8-49fc-9504-931a2bd7da5f)

How can I do this?

**Comment by TheKonka** [comment]
taro-plugin-inject

**Comment by sehmbimanvir** [comment]
I added like this in ```config/index.ts``` file. But still it's not working

```javascript
plugins: [
    [
      '@tarojs/plugin-inject',
      {
        components: {
          Map: {
            type: 'google'
          }
        },
      },
    ],
```

**Comment by sehmbimanvir** [comment]
Thank you!, This one is resolved. @tarojs/plugin-inject library is working fine to inject custom attributes to the components.
