### ISSUE TITLE
navigateTo无法跳转

### ISSUE THREAD

**Issue by Varavarforvar** [NervJS/taro#158]
小程序端是正常的
但是在h5的话，url改变，但是页面不会跳转

**Comment by Varavarforvar** [comment]
Uncaught (in promise) TypeError: Cannot read property 'refs' of null

**Comment by cgx9** [comment]
我的问题解决。
一，onClick里不能直接写匿名函数。
2， 跳转路径要最前面要有'/'，比如: '/pages/xxx/xxx'; 不能Taro.navigateTo({url: 'pages/productlist/index'})。

**Comment by Varavarforvar** [comment]
@cgx9 我和你目前的方法一样，但是依然存在问题

**Comment by luckyadam** [comment]
跳转代码能不能贴一下

**Comment by Varavarforvar** [comment]
@luckyadam 
```
testNavigate() {
  Taro.navigateTo({url:'/pages/haha/index'})
}
<Button size='default' onClick={this.testNavigate}>按下去</Button>
```

**Comment by luckyadam** [comment]
H5 端跳转不了应该代码报错了，可以看看报错信息么

**Comment by jun601011814** [comment]
@luckyadam h5使用Taro.navigateTo，promise对象是undefined
`Taro.navigateTo({
      url: '/pages/home/index2/index'
    }).then(() => {
      console.log('taro')
    })`

以下是报错：
![image](https://user-images.githubusercontent.com/11892332/44186268-0a2adb00-a14b-11e8-9166-7bd4f2ccb8d0.png)

**Comment by forconz** [comment]
Taro.navigateTo({url: `/pages/partner/signup`})

我的电脑报这个错误
Uncaught (in promise) {errMsg: "navigateTo:fail history.push is not a function"}

但是程序build以后，发布到服务器，又可以跳转
在我同事电脑上也可以跳转

不知道咋回事

**Comment by fuersite** [comment]
@forconz 什么系统？

**Comment by VannySi** [comment]
我重新安装依赖包之后也报这个错误，之前没有问题，可以直接跳转

Uncaught (in promise) {errMsg: "navigateTo:fail history.push is not a function"}

macOS

程序build以后也有该问题

**Comment by VannySi** [comment]
> 我重新安装依赖包之后也报这个错误，之前没有问题，可以直接跳转
> 
> Uncaught (in promise) {errMsg: "navigateTo:fail history.push is not a function"}
> 
> macOS
> 
> 程序build以后也有该问题

@tarojs/cli 降到 1.3.0就好了(出问题的是1.3.19)

**Comment by fuersite** [comment]
可能是 @taro/cli 跟你项目中 taro 版本不一致导致的

**Comment by shadow-boy** [comment]
> 我的问题解决。
> 一，onClick里不能直接写匿名函数。
> 2， 跳转路径要最前面要有'/'，比如: '/pages/xxx/xxx'; 不能Taro.navigateTo({url: 'pages/productlist/index'})。

2018年的bug到2020年都还在、版本都是到2.2.6了，这种bug也是麻烦
