### ISSUE TITLE
开启compileMode模式, dev命令执行时,出现`buffer`未定义情况

### ISSUE THREAD

**Issue by czfadmin** [NervJS/taro#15841]
### 相关平台
微信小程序

**小程序基础库: 3.4.3**
**使用框架: React**

### 复现步骤
- taro init
- 选择nutui模板
- 按照官方配置
- pnpm run dev:weapp

### 期望结果
可以正常dev编译

### 实际结果
```pwsh
D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack-sources@3.2.3\node_modules\webpack-sources\lib\ConcatSource.js:57     
                        if (typeof child.buffer === "function") {
                                         ^

TypeError: Cannot read properties of undefined (reading 'buffer')
    at ConcatSource.buffer (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack-sources@3.2.3\node_modules\webpack-sources\lib\ConcatSource.js:57:21)
    at getContent (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack@5.78.0_@swc core@1.3.96\node_modules\webpack\lib\Compiler.js:694:23)
    at processMissingFile (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack@5.78.0_@swc core@1.3.96\node_modules\webpack\lib\Compiler.js:812:24)
    at D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack@5.78.0_@swc core@1.3.96\node_modules\webpack\lib\Compiler.js:856:10
    at callback (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\graceful-fs@4.2.11\node_modules\graceful-fs\polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:202:21)
```
### 环境信息
```
 Taro CLI 3.6.31 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.19.0 - ~\AppData\Local\fnm_multishells\22128_1717516637550\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - ~\AppData\Local\fnm_multishells\22128_1717516637550\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.31 => 3.6.31
      @tarojs/components: 3.6.31 => 3.6.31
      @tarojs/helper: 3.6.31 => 3.6.31
      @tarojs/plugin-framework-react: 3.6.31 => 3.6.31
      @tarojs/plugin-html: ^3.6.31 => 3.6.31
      @tarojs/plugin-platform-alipay: 3.6.31 => 3.6.31
      @tarojs/plugin-platform-h5: 3.6.31 => 3.6.31
      @tarojs/plugin-platform-jd: 3.6.31 => 3.6.31
      @tarojs/plugin-platform-qq: 3.6.31 => 3.6.31
      @tarojs/plugin-platform-swan: 3.6.31 => 3.6.31
      @tarojs/plugin-platform-tt: 3.6.31 => 3.6.31
      @tarojs/plugin-platform-weapp: 3.6.31 => 3.6.31
      @tarojs/react: 3.6.31 => 3.6.31
      @tarojs/runtime: 3.6.31 => 3.6.31
      @tarojs/shared: 3.6.31 => 3.6.31
      @tarojs/taro: 3.6.31 => 3.6.31
      @tarojs/taro-loader: 3.6.31 => 3.6.31
      @tarojs/webpack5-runner: 3.6.31 => 3.6.31
      babel-preset-taro: 3.6.31 => 3.6.31
      eslint-config-taro: 3.6.31 => 3.6.31
      react: ^18.3.1 => 18.3.1
```

**Comment by victorWuxz** [comment]
我也遇到了，开启compileMode模式就会遇到

**Comment by czfadmin** [comment]
> 我也遇到了，开启compileMode模式就会遇到
很奇怪, 我的好像没有开启这个配置compileMode, 但是这个突然出现的, 重新下载官方模板后, 将配置复制过去后可以正常运行,同时在改成自己的原先的配置, 这个问题又没了😂

**Comment by czfadmin** [comment]
> 我也遇到了，开启compileMode模式就会遇到

确实开启了compileMode的模式问题就出现了

**Comment by RuanLight** [comment]
同开compileMode遇到

**Comment by wzhqwq** [comment]
有一个临时fix，先在配置里把compileMode注释掉，跑通一次dev，然后再取消注释重新跑dev，就不会有问题了，可能是缺了些文件

**Comment by gMorning-Wp** [comment]
把prebundle 关了就好了。prebundle: {enable: false } 半编译暂时不支持prebundle

**Comment by gMorning-Wp** [comment]
> ### 相关平台
> 微信小程序
> 
> **小程序基础库: 3.4.3** **使用框架: React**
> 
> ### 复现步骤
> * taro init
> * 选择nutui模板
> * 按照官方配置
> * pnpm run dev:weapp
> 
> ### 期望结果
> 可以正常dev编译
> 
> ### 实际结果
> ```powershell
> D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack-sources@3.2.3\node_modules\webpack-sources\lib\ConcatSource.js:57     
>                         if (typeof child.buffer === "function") {
>                                          ^
> 
> TypeError: Cannot read properties of undefined (reading 'buffer')
>     at ConcatSource.buffer (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack-sources@3.2.3\node_modules\webpack-sources\lib\ConcatSource.js:57:21)
>     at getContent (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack@5.78.0_@swc core@1.3.96\node_modules\webpack\lib\Compiler.js:694:23)
>     at processMissingFile (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack@5.78.0_@swc core@1.3.96\node_modules\webpack\lib\Compiler.js:812:24)
>     at D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\webpack@5.78.0_@swc core@1.3.96\node_modules\webpack\lib\Compiler.js:856:10
>     at callback (D:\projects\myworkspace\lite-cv\cv-app\node_modules\.pnpm\graceful-fs@4.2.11\node_modules\graceful-fs\polyfills.js:306:20)
>     at FSReqCallback.oncomplete (node:fs:202:21)
> ```
> 
> ### 环境信息
> ```
>  Taro CLI 3.6.31 environment info:
>     System:
>       OS: Windows 11 10.0.22631
>     Binaries:
>       Node: 18.19.0 - ~\AppData\Local\fnm_multishells\22128_1717516637550\node.EXE
>       Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
>       npm: 10.2.3 - ~\AppData\Local\fnm_multishells\22128_1717516637550\npm.CMD
>     npmPackages:
>       @tarojs/cli: 3.6.31 => 3.6.31
>       @tarojs/components: 3.6.31 => 3.6.31
>       @tarojs/helper: 3.6.31 => 3.6.31
>       @tarojs/plugin-framework-react: 3.6.31 => 3.6.31
>       @tarojs/plugin-html: ^3.6.31 => 3.6.31
>       @tarojs/plugin-platform-alipay: 3.6.31 => 3.6.31
>       @tarojs/plugin-platform-h5: 3.6.31 => 3.6.31
>       @tarojs/plugin-platform-jd: 3.6.31 => 3.6.31
>       @tarojs/plugin-platform-qq: 3.6.31 => 3.6.31
>       @tarojs/plugin-platform-swan: 3.6.31 => 3.6.31
>       @tarojs/plugin-platform-tt: 3.6.31 => 3.6.31
>       @tarojs/plugin-platform-weapp: 3.6.31 => 3.6.31
>       @tarojs/react: 3.6.31 => 3.6.31
>       @tarojs/runtime: 3.6.31 => 3.6.31
>       @tarojs/shared: 3.6.31 => 3.6.31
>       @tarojs/taro: 3.6.31 => 3.6.31
>       @tarojs/taro-loader: 3.6.31 => 3.6.31
>       @tarojs/webpack5-runner: 3.6.31 => 3.6.31
>       babel-preset-taro: 3.6.31 => 3.6.31
>       eslint-config-taro: 3.6.31 => 3.6.31
>       react: ^18.3.1 => 18.3.1
> ```

把prebundle 关了就好了， prebundle: {enable: false }。 prebundler 和 半编译有点冲突

**Comment by gMorning-Wp** [comment]
后续会支持～～

**Comment by huangsheng7271** [comment]
我也遇到这个问题了，好恶心
