### ISSUE TITLE
h5能支持蓝牙吗？

### ISSUE THREAD

**Issue by kekxv** [NervJS/taro#15860]
### 这个特性解决了什么问题？
解决网页使用蓝牙的问题

https://developer.chrome.com/docs/capabilities/bluetooth?hl=zh-cn

### 这个 API 长什么样？
和现有的蓝牙接口兼容

https://developer.chrome.com/docs/capabilities/bluetooth?hl=zh-cn

**Comment by koppthe** [comment]
标准还是草案阶段
https://webbluetoothcg.github.io/web-bluetooth/
