### ISSUE TITLE
Taro.navigateTo()报错

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1586]
用的DVA框架 一个onClick事件触发
      Taro.navigateTo({
        url: 'pages/quitSmoking/start'
      })

```js
Uncaught (in promise) undefined
(anonymous) @ index.js?e6ae:832
Info._this.onSubmit @ info.js?019e:50
onClick @ index.js?c5dd:1
dispatchEvent @ index.js?1e21:510
dispatchEvent @ index.js?1e21:520
eventHandler @ index.js?1e21:548

```

**系统信息**

 - 操作系统: [mac 10.13.6]
 - Taro 版本 [1.2.0]
 - Node.js 版本 [10.13.0]
 - 报错平台 [h5,]

**Comment by hugetiny** [comment]
解决了 貌似在DVA的reducer里面用Taro.navigateTo会有问题

**Comment by yuche** [comment]
ok，那关咯
