### ISSUE TITLE
taro update project 问题

### ISSUE THREAD

**Issue by cooliean** [NervJS/taro#1588]
**问题描述**
在项目中使用命令的时候，mobx相关依赖没有更新
"@tarojs/mobx": "^1.2.0",
"@tarojs/mobx-h5": "^1.2.0",
"@tarojs/mobx-rn": "^1.2.0",

之前其实就遇到过，部分是没有更新的，当时没有在意，以为确实是没有更新相关的没有提，但是今天，我复查了一个npmjs网站，看到是又最新的包的，

今天是从1.2.0-beta16，升级到 1.2.0正式版本出现的问题

上次是beta14到15 有问题，忽略掉了  ：）

**系统信息**
![image](https://user-images.githubusercontent.com/4754617/50199941-91ed5400-038e-11e9-9cc8-645a1b9d6824.png)

希望Taro越做越好 ：）

**Comment by cooliean** [comment]
希望下次有一个命令可以  比如 ： taro issues

能出来这里的系统信息，或者是其他更多信息

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

这样不用每次都去看来看去的，好麻烦哦  ：）

**Comment by yuche** [comment]
`taro info` 就是这个命令，待会我修改一下 issue 模板要求带上 taro info 的内容
