### ISSUE TITLE
请教一个问题  在组件的点击事件中怎么获取到各自的index

### ISSUE THREAD

**Issue by Mikelulu** [NervJS/taro#159]
怎么在点击事件中给state中的current_index赋值 0 或者 1
![image](https://user-images.githubusercontent.com/19161230/41671355-7732fb1c-74e9-11e8-8e6f-d8bc23020596.png)

**Comment by zacksleo** [comment]
`onClick={this.titleOnClick(this,1)}` 这里可以传值啊
