### ISSUE TITLE
编译为百度小程序 点击标签没有 按下去的效果

### ISSUE THREAD

**Issue by host110** [NervJS/taro#1590]
**问题描述**
编译为百度小程序 点击标签没有 按下去的效果

**复现步骤**
在微信小程序  支付宝小程序内都没有问题
就百度小程序点击没有灰色的样式效果

[或者可以直接贴源代码，能贴文字就不要截图]

```js
<View className={this.computedStyle(item)} data-has_stock={item.has_stock} data-id={item.id} data-name={item.name} onClick={this.chooseSize}>
                          { item.name == '均码' ? <View>均码</View>

```
据估计是data-has_stock这个属性百度小程序不能识别
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
![_5y dttent z_70l icn](https://user-images.githubusercontent.com/36479041/50202542-658b0500-0399-11e9-9240-6432ebcbc672.png)

**报错信息**

[

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.2.0]
 - Node.js 版本 [e.g. v10.13.0]
 - 报错平台 [swan]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
这个应该是百度小程序自己的限制~
