### ISSUE TITLE
升级1.2.0正式版后，redux传值在h5上失效，小程序正常

### ISSUE THREAD

**Issue by XiaoSongWolf** [NervJS/taro#1591]
升级1.2.0正式版后，redux传值在h5上失效，小程序正常

**问题描述**
前面使用的是1.2.0-beta5版本是没有问题，升级后出现的问题

**期望行为**
能尽快修复这个问题

**报错信息**
![image](https://user-images.githubusercontent.com/19815977/50203174-953b0c80-039b-11e9-9472-b4ac1a1e2596.png)

**系统信息**
  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.0 => 1.2.0
      @tarojs/plugin-babel: 1.2.0 => 1.2.0
      @tarojs/plugin-csso: 1.2.0 => 1.2.0
      @tarojs/plugin-sass: 1.2.0 => 1.2.0
      @tarojs/plugin-uglifyjs: 1.2.0 => 1.2.0
      @tarojs/redux: 1.2.0 => 1.2.0
      @tarojs/redux-h5: 1.2.0 => 1.2.0
      @tarojs/router: 1.2.0 => 1.2.0
      @tarojs/taro: 1.2.0 => 1.2.0
      @tarojs/taro-h5: 1.2.0 => 1.2.0
      @tarojs/taro-weapp: 1.2.0 => 1.2.0
      @tarojs/webpack-runner: 1.2.0 => 1.2.0

**补充信息**
查看源码，h5版本中redux的store没有被挂载

**Comment by luckyadam** [comment]
能否提供一个可以复现的小 demo，你的这个截图是路由相关的，跟 redux 没啥关系
