### ISSUE TITLE
引入ecahrts，折线图渲染异常

### ISSUE THREAD

**Issue by Jam1zhu** [NervJS/taro#1593]
ec-canvas组件，复制的[taro-sample-weapp](https://github.com/NervJS/taro-sample-weapp)里的组件。
折线图代码复制的[官方demo](http://echarts.baidu.com/examples/editor.html?c=line-stack)
出现了以下问题
![image](https://user-images.githubusercontent.com/21252750/50204642-8b67d800-03a0-11e9-9774-8c7433b721ec.png)

同样的代码，如果把```type:'line'```换成```type:'bar'```，就可以正常渲染
```javascript
series: [
            {
                name: '邮件营销',
                type: 'bar',     //  这里把line换成bar，可以正常渲染
                stack: '总量',
                data: [120, 132, 101, 134, 90, 230, 210]
            },
            {
                name: '联盟广告',
                type: 'bar',
                stack: '总量',
                data: [220, 182, 191, 234, 290, 330, 310]
            },
          // ......
        ]
```
![image](https://user-images.githubusercontent.com/21252750/50204965-91aa8400-03a1-11e9-9af6-09327ab73e6b.png)

用原生小程序，引入了ec-canvas，折线图绘制正常，可以排出ec-canvas的问题

taro版本1.2.0

**Comment by jeffhuang2086** [comment]
这个应该和taro框架没什么关系，具体看下echarts的options

**Comment by Jam1zhu** [comment]
@jeffhuang2086  找到原因了...搞了一下午，心塞
cocofig/index.js 里，weapp需要配置complie
```
weapp: {
    compile: {
      exclude: ['src/components/ec-canvas/echarts.js']
    }
  },
```
