### ISSUE TITLE
在ios上，input组件存在的两个问题

### ISSUE THREAD

**Issue by zhaolei69** [NervJS/taro#1597]
**问题描述**
在ios手机上input出现的两个问题：
1、ios11.2系统上，输入文字时，会把字母先输出（ios12.0没问题）；
2、在ios系统上，输入文字过长时，想要把焦点定位到内容的最前边，文字无法滚动，不能把焦点定位到文字的最前面。

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by soraping** [comment]
这是ios11，12出现的bug，不仅小程序，连h5微信端都是这样的问题，光标错位，我的解决方案是这样的

元素定位不要用
```css
position: fixed;
```
用其他的定位方式
如果是modal的话，modal最下层也不要用fixed，否则光标肯定错位
我在h5端就是把这个改了才修复这个问题的，你可以试下

**Comment by zhaolei69** [comment]
> 这是ios11，12出现的bug，不仅小程序，连h5微信端都是这样的问题，光标错位，我的解决方案是这样的
> 
> 元素定位不要用
> 
> ```css
> position: fixed;
> ```
> 
> 用其他的定位方式
> 如果是modal的话，modal最下层也不要用fixed，否则光标肯定错位
> 我在h5端就是把这个改了才修复这个问题的，你可以试下

谢谢，我这边暂时使用的是多行实现的，你说的方法我会去试下的..
