### ISSUE TITLE
(4.x): Cannot access '_raf' before initialization

### ISSUE THREAD

**Issue by b1ngx** [NervJS/taro#15981]
### 相关平台
微信小程序

**小程序基础库: 2.33**
**使用框架: React**

### 复现步骤
```
compiler: {
  type: 'webpack5',
  prebundle: {
    enable: false,
  },
}
```
或 `npm run build`

![image](https://github.com/NervJS/taro/assets/2504871/27fc4ec7-c61c-4151-9f92-4f7960836dd3)

### 期望结果
不报错

### 实际结果
正确运行

### 环境信息
```
👽 Taro v4.0.0-alpha.26


  Taro CLI 4.0.0-alpha.26 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/components: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/helper: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/plugin-framework-react: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/plugin-platform-weapp: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/react: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/runtime: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/shared: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/taro: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/taro-loader: 4.0.0-alpha.26 => 4.0.0-alpha.26
      @tarojs/webpack5-runner: 4.0.0-alpha.26 => 4.0.0-alpha.26
      babel-preset-taro: 4.0.0-alpha.26 => 4.0.0-alpha.26
      react: ^18.3.1 => 18.3.1
```

**Comment by koppthe** [comment]
启用「将 JS 编译成 ES5」
<img width="400" alt="image" src="https://github.com/NervJS/taro/assets/1240899/66c119b4-db59-4106-b594-7b56630d0445">

**Comment by b1ngx** [comment]
![image](https://github.com/NervJS/taro/assets/2504871/5a892f57-3d98-4e42-9862-c96b293b6b1a)

文档需要设置关闭 ES6 转 ES5 功能，开启可能报错

**Comment by b1ngx** [comment]
Solved in https://github.com/NervJS/taro/commit/f7191669aaa5637464a7ba8d76b5c47e0b031d0c

**Comment by deng565430** [comment]
4.03版本还是如此。
复现：
` compiler: {
      type: "webpack5",
      prebundle: {
        enable: false,
      },
    },`
报错：
<img width="858" alt="image" src="https://github.com/user-attachments/assets/8fd0a6e3-0241-4cff-b8e4-56506b62f6f1">

根据issues提示：
1、启用「将 JS 编译成 ES5」
报错：
<img width="876" alt="image" src="https://github.com/user-attachments/assets/0db50776-f16b-44dc-a793-0c41ef2a05e8">

**Comment by HyperLife1119** [comment]
3.x 也有此问题 :(
