### ISSUE TITLE
 taro 1.2.0 版本 config配置alias路径问题

### ISSUE THREAD

**Issue by soraping** [NervJS/taro#1598]
taro 1.2.0 版本 config中已经配置alias路径

```js
alias: {
    "@utils": path.resolve(__dirname, "..", "src/utils")
}
```

源代码是：

```js
import { add } from "@utils";
```

执行编译时出现异常，提示

```bash
缺少npm包@utils，开始安装...
```

查看编译后的文件，发现路径并没有被转成真实路径 

```js
var _utils = require("@utils");
```

**Comment by nyrf** [comment]
这样写
```
 alias: {
    '@utils': 'src/utils'
  },
```

**Comment by soraping** [comment]
@nyrf ,试过了，还是会报 ```缺少npm包@utils，开始安装...```

**Comment by luckyadam** [comment]
提供一个 taro cli 版本

**Comment by soraping** [comment]
@luckyadam 是 ``` Taro v1.2.0 ```,编译日志就是缺少npm包，一段时间后自动编译成功，打开编译文件发现路径没有被替换

**Comment by nyrf** [comment]
我自己就是这样用的，我cli是1.2.0，项目版本也是1.2.0
<img width="434" alt="wx20181220-153615 2x" src="https://user-images.githubusercontent.com/299532/50270589-03033900-046d-11e9-8845-21ae180b03ac.png">

<img width="372" alt="wx20181220-153249 2x" src="https://user-images.githubusercontent.com/299532/50270440-896b4b00-046c-11e9-9498-278d6b9b98de.png">
<img width="612" alt="wx20181220-153435 2x" src="https://user-images.githubusercontent.com/299532/50270526-c7686f00-046c-11e9-90ee-b81272ee89f2.png">

**Comment by soraping** [comment]
@luckyadam ,我的那个是ts版本，是不是还没有支持ts版本的alias
