### ISSUE TITLE
quick start 小程序报错

### ISSUE THREAD

**Issue by fandebiao12345** [NervJS/taro#16]
module ".\npm\@tarojs\taro-weapp\index.js" is not defined

**Comment by luckyadam** [comment]
请问开发开发工具 `@tarojs/cli` 是哪个版本的

**Comment by fandebiao12345** [comment]
0.0.40  windows

**Comment by wzxm** [comment]
![image](https://user-images.githubusercontent.com/13127730/41137360-5d698470-6b0d-11e8-9bca-f4a201d8dd4a.png)
我也遇到这个问题了，很奇怪。

**Comment by dntzhang** [comment]
+1

**Comment by luckyadam** [comment]
我更新了个版本~升级开发工具 `@tarojs/cli` 到 0.0.41 试试哦~

**Comment by luckyadam** [comment]
请升级 到 0.0.42 试试~
