### ISSUE TITLE
@taro 相关依赖升级到 1.2.0 后，ts 告警

### ISSUE THREAD

**Issue by zoux** [NervJS/taro#1602]
之前一直在 1.1.8 上平稳开发，今天升级到了 1.2.0，但发现更新后的项目中，ts 发生告警。

告警及当前 package.json 如下图所示：

![image](https://user-images.githubusercontent.com/24969960/50218272-4ce51400-03c6-11e9-9d40-928ec11cb8b0.png)

![image](https://user-images.githubusercontent.com/24969960/50218280-53738b80-03c6-11e9-9f13-7b1923c1d46f.png)

**Comment by soraping** [comment]
我也是ts的版本，今天升级了，没有出现这样的告警，可以试下关闭编辑器再打开试下

**Comment by zoux** [comment]
删除了 node_modules 重新安装了一次，已经好了。

原因应该是直接的包加载的是如图所示的 3.1.3 版本的 ts；更新后为 3.2.2 ~
