### ISSUE TITLE
解决问题

### ISSUE THREAD

**Issue by lijiantxsxs** [NervJS/taro#16033]
![d244d01bb54a62a7961ddb2ff254517](https://github.com/NervJS/taro/assets/168519903/df4eeb14-7a5b-4916-9e9b-6e503259a96c)
拉取远程模板仓库失败！ 怎么解决

**Comment by lyxdream** [comment]
taro版本更新一下，v1.3.24版本有点低，然后看看网速是不是不好

**Comment by honlyHuang** [comment]
你新项目，用 Taro 最新版本咯 3.x
