### ISSUE TITLE
MovableView 组件 bindchange方法绑定无效

### ISSUE THREAD

**Issue by a515978292** [NervJS/taro#1604]
--问题描述

***** Taro组件 MovableView    bindchange方法绑定无效

------------------------------------------------------
复现源码

import Taro, { Component } from '@tarojs/taro'
import { View,  MovableArea, MovableView} from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { add } from '../../actions/counter'
import classnames from 'classnames'
import './index.less'

@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add () {
    dispatch(add())
  }
}))

export default class index extends Component {
  config = {
    navigationBarTitleText: 'allUserList',
    enablePullDownRefresh:false
  }
  
  constructor(props){
    super(props);
    this.state = {
      list : [
            {x:0,y:0},
            {x:100,y:0},
            {x:200,y:0},
            {x:300,y:0},
            {x:400,y:200},
            {x:400,y:400},
            {x:200,y:400},
          ]
    }
    this.moveChange = this.moveChange.bind(this);
  }

  //分割线
  moveChange(ele,event){ //滑块滚动触发的事件
    console.log(ele);
  }

  render() {
    console.log(this.moveChange)
    return (
      <View>
          <MovableArea className={'MoveBigBox'}>
              {
                this.state.list.map((ele,index)=>{
                  return <MovableView 
                          className={'moveEachBox'}
                          key={index}
                          x={ele.x}
                          y={ele.y}
                          direction='all'
                          bindchange = {this.moveChange}
                          >
                        </MovableView>
                })
              }
          </MovableArea>
      </View>  
    )
  }
}

--------------控制台错误信息------------------
Component "pages/allUserList/index" does not have a method "moveChange" to handle event "change".

ps:我明明是绑定了moveChange方法的

**Comment by a515978292** [comment]
在线等 ---   有个功能必须得 获取到滑块滑动时候的位置

**Comment by a515978292** [comment]
是我的锅，把bindchange   改写成onChange 就可以了 。   介意你们把文档写清楚，你们说的是和wx API一样的  ， 我是碰运气试出来的

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/event.html#%E4%BB%BB%E4%BD%95%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E9%83%BD%E8%A6%81%E4%BB%A5-on-%E5%BC%80%E5%A4%B4

这里不是写得很清楚必须用 on 开头吗，而且你是从官方库 import 过来是有自动补全的
