### ISSUE TITLE
Mac中运行下载的安装包，编译h5没有错误，但是打开页面空白，报错_taroH2.default._set$app is not a function

### ISSUE THREAD

**Issue by hanshengxia** [NervJS/taro#1608]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - /usr/local/bin/node
      npm: 5.5.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/plugin-babel: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/plugin-csso: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/plugin-sass: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/plugin-uglifyjs: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/router: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/taro: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/taro-h5: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/taro-weapp: 1.0.0-beta.29 => 1.0.0-beta.29 
      @tarojs/webpack-runner: 1.0.0-beta.29 => 1.0.0-beta.29 
      eslint-config-taro: 1.0.0-beta.29 => 1.0.0-beta.29 
      eslint-plugin-taro: 1.0.0-beta.29 => 1.0.0-beta.29 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by mienv567** [comment]
你的依赖库都是旧版本 请使用 taro update project 更新

**Comment by hnsxxscyx** [comment]
此问题复现，同样报错taroH2.default._set$app is not a function，
`o v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
`
已使用taro update project把依赖更新， package.json依赖版本如下：
`"dependencies": {
		"@tarojs/async-await": "1.2.21",
		"@tarojs/components": "1.2.21",
		"@tarojs/mobx": "1.2.21",
		"@tarojs/mobx-h5": "1.2.21",
		"@tarojs/mobx-rn": "1.2.21",
		"@tarojs/rn-runner": "1.2.21",
		"@tarojs/router": "1.2.21",
		"@tarojs/taro": "1.2.21",
		"@tarojs/taro-alipay": "1.2.21",
		"@tarojs/taro-h5": "1.2.21",
		"@tarojs/taro-swan": "1.2.21",
		"@tarojs/taro-tt": "1.2.21",
		"@tarojs/taro-weapp": "1.2.21",
		"@tarojs/webpack-runner": "1.2.21",
		"mobx": "^5.5.2",
		"nerv-devtools": "^1.3.9",
		"nervjs": "^1.3.9",
		"taro-ui": "^1.5.0"
	},
	"devDependencies": {
		"@types/react": "16.3.14",
		"@types/webpack-env": "^1.13.6",
		"@tarojs/plugin-babel": "1.2.21",
		"@tarojs/plugin-csso": "1.2.21",
		"@tarojs/plugin-sass": "1.2.21",
		"@tarojs/plugin-uglifyjs": "1.2.21",
		"@tarojs/webpack-runner": "1.2.21",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"babel-eslint": "^8.2.3",
		"eslint": "^4.19.1",
		"eslint-config-taro": "1.2.21",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-taro": "1.2.21",
		"typescript": "^3.0.1"
	}`

**Comment by zwblue** [comment]
> 此问题复现，同样报错taroH2.default._set$app is not a function，
> `o v1.2.20
> 
> Taro CLI 1.2.20 environment info:
> System:
> OS: Windows 10
> Binaries:
> Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
> npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD`
> 
> 已使用taro update project把依赖更新， package.json依赖版本如下：
> 
> `"dependencies": { "@tarojs/async-await": "1.2.21", "@tarojs/components": "1.2.21", "@tarojs/mobx": "1.2.21", "@tarojs/mobx-h5": "1.2.21", "@tarojs/mobx-rn": "1.2.21", "@tarojs/rn-runner": "1.2.21", "@tarojs/router": "1.2.21", "@tarojs/taro": "1.2.21", "@tarojs/taro-alipay": "1.2.21", "@tarojs/taro-h5": "1.2.21", "@tarojs/taro-swan": "1.2.21", "@tarojs/taro-tt": "1.2.21", "@tarojs/taro-weapp": "1.2.21", "@tarojs/webpack-runner": "1.2.21", "mobx": "^5.5.2", "nerv-devtools": "^1.3.9", "nervjs": "^1.3.9", "taro-ui": "^1.5.0" }, "devDependencies": { "@types/react": "16.3.14", "@types/webpack-env": "^1.13.6", "@tarojs/plugin-babel": "1.2.21", "@tarojs/plugin-csso": "1.2.21", "@tarojs/plugin-sass": "1.2.21", "@tarojs/plugin-uglifyjs": "1.2.21", "@tarojs/webpack-runner": "1.2.21", "babel-plugin-transform-class-properties": "^6.24.1", "babel-plugin-transform-decorators-legacy": "^1.3.4", "babel-plugin-transform-jsx-stylesheet": "^0.6.5", "babel-plugin-transform-object-rest-spread": "^6.26.0", "babel-preset-env": "^1.6.1", "babel-eslint": "^8.2.3", "eslint": "^4.19.1", "eslint-config-taro": "1.2.21", "eslint-plugin-react": "^7.8.2", "eslint-plugin-import": "^2.12.0", "eslint-plugin-taro": "1.2.21", "typescript": "^3.0.1" }`

1、taro update project
2、npm install -g @tarojs/cli
这两步试试

**Comment by joker-li** [comment]
难受  突然也出现这种情况
👽 Taro v1.2.20


  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.24 => 1.2.24 
      @tarojs/components: 1.2.24 => 1.2.24 
      @tarojs/plugin-babel: 1.2.24 => 1.2.24 
      @tarojs/plugin-csso: 1.2.24 => 1.2.24 
      @tarojs/plugin-sass: 1.2.24 => 1.2.24 
      @tarojs/plugin-uglifyjs: 1.2.24 => 1.2.24 
      @tarojs/redux: 1.2.24 => 1.2.24 
      @tarojs/redux-h5: 1.2.24 => 1.2.24 
      @tarojs/rn-runner: 1.2.24 => 1.2.24 
      @tarojs/router: 1.2.24 => 1.2.24 
      @tarojs/taro: 1.2.24 => 1.2.24 
      @tarojs/taro-alipay: 1.2.24 => 1.2.24 
      @tarojs/taro-h5: 1.2.24 => 1.2.24 
      @tarojs/taro-swan: 1.2.24 => 1.2.24 
      @tarojs/taro-tt: 1.2.24 => 1.2.24 
      @tarojs/taro-weapp: 1.2.24 => 1.2.24 
      @tarojs/webpack-runner: 1.2.24 => 1.2.24 
      eslint-config-taro: 1.2.24 => 1.2.24 
      eslint-plugin-taro: 1.2.24 => 1.2.24 
      nervjs: ^1.3.0 => 1.3.12

**Comment by chinawzc** [comment]
你们最后怎么解决的

**Comment by Jayxiang** [comment]
我这边升级后就好了

> 1、taro update project
> 2、npm install -g @tarojs/cli

这样
