### ISSUE TITLE
小程序中Text标签dev和build后表现不一致

### ISSUE THREAD

**Issue by schinvendy** [NervJS/taro#1609]
**问题描述**

小程序中Text标签如果里面的内容有出现换行的话，dev和build的表现会不一致。

**复现步骤**

jsx内容：
![x1mgtt 313 0dm jpi4irh](https://user-images.githubusercontent.com/17189558/50265993-ccbdbd80-045c-11e9-939e-0fb5fa4e804f.png)

dev环境下：
![r7hy l57z0cnz2 9q_i9naq](https://user-images.githubusercontent.com/17189558/50266006-d9421600-045c-11e9-9fdb-f56c8fbdc724.png)

build环境下：
![fb_ 8 ht _h 8z 8 4 1 q](https://user-images.githubusercontent.com/17189558/50266022-e959f580-045c-11e9-8161-30e6def2d8bc.png)

**期望行为**

期望表现一致，避免dev下正常然而到了build后布局混乱

**系统信息**
  Taro CLI 1.2.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

**Comment by yuche** [comment]
你截图的代码文字发一下

**Comment by schinvendy** [comment]
> 你截图的代码文字发一下

 state = {
    testText: 'testText',
    stateText: 'stateText'
  };

render() {
    const { testText, stateText } = this.state;
    return (
      <View className="index">
        <View>测试Text标签</View>
        <View style="margin-top:20px">
          <Text>
            这是一个被换行的Text标签内容
            {testText}
          </Text>
          <Text>这是一个没有换行的Text标签内容{stateText}</Text>
        </View>
        <View style="margin-top:20px">
          <Text>
            这是一个被换行的Text标签内容
            {stateText}
          </Text>
          <Text>这是一个没有换行的Text标签内容{testText}</Text>
        </View>
      </View>
    );
  }

**Comment by yuche** [comment]
带上缩进，否则不知道你到底在哪写了 `\n`

**Comment by luckyadam** [comment]
因为 build 后 wxml 会被压缩，你如果要实现换行还是用 `<View />` 标签来做
