### ISSUE TITLE
taro init failed

### ISSUE THREAD

**Issue by xinconan** [NervJS/taro#161]
使用taro初始化项目报错，如图：
![image](https://user-images.githubusercontent.com/8479810/41694401-bfbedfc4-753c-11e8-9a97-e04c5a649864.png)
**环境：**
Node 8.9.1
win 10
**错误信息：**
(node:472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: d:\Program Files (x86)\Nodist\bin\node_modules\@tarojs\cli\templates\default\pkg
(node:472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zacksleo** [comment]
网络问题吧？

**Comment by xinconan** [comment]
网络正常

**Comment by zacksleo** [comment]
see #153

**Comment by xinconan** [comment]
不是网络问题，用的是淘宝源。
看报错信息：`Trying to copy from a source that does not exist`，其实`node_modules@tarojs\cli\templates\default\pkg`是存在的，难道不支持win？

**Comment by zacksleo** [comment]
删除 node_modules 重新安装  #147 #122

**Comment by xinconan** [comment]
已经确定使用mpvue了，这个先不尝试了

**Comment by Young1993** [comment]
> 已经确定使用mpvue了，这个先不尝试了

哈哈哈 我也遇到这个问题
