### ISSUE TITLE
taro 编译 rn 时分包路径有问题

### ISSUE THREAD

**Issue by zhangjie1314** [NervJS/taro#1610]
**问题描述**
在使用taro 编译成rn项目时 分包的路由无法正常编译

**复现步骤**

```json
//  编译前
subPackages: [
        {
            root: 'packages/index',
            pages: [
                    'index/index',
                    'list/index'
            ]
        },
        {
            root: 'packages/ticket',
            pages: [
                    'index/index',
                    'list/index'
            ]
        }
]
```

```json
//  编译后是这样的
subPackages: [
        {
            root: 'packages/index'
        },
        {
            root: 'packages/ticket'
        }
]
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

     Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.4.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^1.2.0 => 1.2.0 
      @tarojs/plugin-babel: ^1.2.0 => 1.2.0 
      @tarojs/plugin-csso: ^1.2.0 => 1.2.0 
      @tarojs/plugin-sass: ^1.2.0 => 1.2.0 
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.0 
      @tarojs/rn-runner: ^1.2.0 => 1.2.0 
      @tarojs/router: ^1.2.0 => 1.2.0 
      @tarojs/taro: ^1.2.0 => 1.2.0 
      @tarojs/taro-alipay: ^1.2.0 => 1.2.0 
      @tarojs/taro-h5: ^1.2.0 => 1.2.0 
      @tarojs/taro-swan: ^1.2.0 => 1.2.0 
      @tarojs/taro-weapp: ^1.2.0 => 1.2.0 
      @tarojs/webpack-runner: ^1.2.0 => 1.2.0 
      eslint-config-taro: ^1.2.0 => 1.2.0 
      eslint-plugin-taro: ^1.2.0 => 1.2.0

**Comment by zhangjie1314** [comment]
@Pines-Cheng  我在本地尝试修改了 cli 文件需要在 ```transformJS.js``` ```getClassPropertyVisitor``` 函数里边添加一些分包处理

**Comment by zhangjie1314** [comment]
我添加的代码如下：
```javascript
if (key.name === 'pages' && t.isArrayExpression(value)) {
            const subPackageParent = astPath.findParent(isUnderSubPackages)
            let root = ''
            if (subPackageParent) {
              /* 在subPackages属性下，说明是分包页面，需要处理root属性 */
              const rootNode = astPath.parent.properties.find(v => {
                return getObjKey(v.key) === 'root'
              })
              root = rootNode ? rootNode.value.value : ''
            }
            
            value.elements.forEach(v => {
              const pagePath = `${root}/${v.value}`.replace(/\/{2,}/g, '/')
              pages.push(pagePath.replace(/^\//, ''))
            })
            astPath.remove()
          }

```

**Comment by Pines-Cheng** [comment]
666
