### ISSUE TITLE
yarn build:weapp 报错

### ISSUE THREAD

**Issue by xiaosu95** [NervJS/taro#16132]
### 相关平台
微信小程序

**小程序基础库: none**
**使用框架: Vue 3**

### 复现步骤
return appConfig.subPackages || appConfig.subpackages || [];
                         ^

TypeError: Cannot read properties of undefined (reading 'subPackages')

### 期望结果
可以正常 build

### 实际结果
报错

### 环境信息
```
Taro v3.6.2


  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.12.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - D:\Program Files\nodejs\yarn.CMD
      npm: 8.1.0 - D:\Program Files\nodejs\npm.CMD
```

**Comment by TheKonka** [comment]
给个 demo 看下

**Comment by xiaosu95** [comment]
https://github.com/xiaosu95/taro-demo

**Comment by TheKonka** [comment]
https://github.com/NervJS/taro/issues/13544

3.6.2 版本有问题，升级一下就好了
