### ISSUE TITLE
taro如何配置host或者disableHostCheck=true

### ISSUE THREAD

**Issue by huangyanyang** [NervJS/taro#1613]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
当使用内网穿透工具将本地服务映射到外网服务时，由于域名不一样，服务报Invalid Host header的错误

**复现步骤**
[复现问题的步骤]
1. 当使用内网穿透工具将本地服务映射到外网服务时，由于域名不一样，服务报Invalid Host header的错误

![image](https://user-images.githubusercontent.com/19208961/50267762-49ec3100-0463-11e9-865a-65d8c3f2f850.png)
![image](https://user-images.githubusercontent.com/19208961/50267771-4fe21200-0463-11e9-9474-a7c4caaa26b4.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

![image](https://user-images.githubusercontent.com/19208961/50267762-49ec3100-0463-11e9-865a-65d8c3f2f850.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2]
 - Node.js 版本 [e.g. v8.11.3]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#h5devserver
