### ISSUE TITLE
Navigator跳转不会执行componentDidHide

### ISSUE THREAD

**Issue by yuanjie007** [NervJS/taro#1614]
**问题描述**
我有A、B、 C  3个页面，A跳到B跳到C，其中B有个定时器，想要跳转页面时清除掉定时器，现在我发现两个怪异的现象（已在原生小程序测试过）:
1.  B跳到C页面之前会想执行componentDidShow(可以看下面的gif图)
2. B跳到C页面不会执行componentDidHide(看文档对应小程序的onHide)，原生的小程序会执行

**复现步骤**
![treedemo](https://user-images.githubusercontent.com/18167335/50271120-bf113380-046e-11e9-92a4-e796c719a18a.gif)

```js
// B 页面的代码
class B extends Component {
  componentDidShow () {
    console.log('调用componentDidShow')
  }
  componentDidHide () {
    console.log('清除定时器 componentDidHide')
  }
}
```

**期望行为**

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v1.2.0-beta.15]
 - Node.js 版本 [e.g. v8.9.4]
 - 报错平台 [weapp]

**补充信息**

**Comment by yuanjie007** [comment]
只有点击导航栏的返回按钮才会触发componentDidHide

**Comment by yuanjie007** [comment]
@Chen-jj 其他两个都是跳转而已，就B页面有这个逻辑，另外，这个B页面的显示是一个组件来的，不知道和这个有没有关系,
B页面的代码: 
```js
export default class B extends Component {
  render () {
    return (
      <View>
        <Child ref='child' params={this.$router.params} />
      </View>
    )
  }
}
// Child 这组的代码就是上面的代码了:
class Child  extends Component {
  componentDidShow () {
    console.log('调用componentDidShow')
  }
  componentDidHide () {
    console.log('清除定时器 componentDidHide')
  }
}
```
不知道这样子行么？

**Comment by Chen-jj** [comment]
开发者工具调试基础库版本多少？

**Comment by yuanjie007** [comment]
2.4.0

**Comment by Chen-jj** [comment]
Taro cli 和项目依赖都升级到最新再试试

**Comment by yuanjie007** [comment]
升级到最新版就ok了，谢谢
