### ISSUE TITLE
微信小程序 taro/cli4.0.2+vite4.2.0+vue3.x TypeError: Cannot read property 'createTextNode' of null

### ISSUE THREAD

**Issue by Aliujiayu** [NervJS/taro#16141]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Aliujiayu/taro4.git](https://github.com/Aliujiayu/taro4.git)
**Taro版本: 4.0.2**
**小程序基础库: 3.5.0**
**使用框架: Vue 3**

### 复现步骤
taro init xtEvaluation
? 请输入项目介绍 测评
? 请选择框架 Vue3
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） 无
? 请选择包管理工具 pnpm
? 请选择编译工具 Vite
? 请选择模板源 CLI 内置默认模板
直接运行即可

### 期望结果
运行起来

### 实际结果
app.js错误:
 TypeError: app.js错误:
 TypeError: Cannot read property 'createTextNode' of null
    at createText (vendors.js? [sm]:6775)
    at processFragment (vendors.js? [sm]:4067)
    at patch (vendors.js? [sm]:3643)
    at ReactiveEffect.componentUpdateFn [as fn] (vendors.js? [sm]:4285)
    at ReactiveEffect.value (vendors.js? [sm]:354)
    at instance.update (vendors.js? [sm]:4409)
    at setupRenderEffect (vendors.js? [sm]:4419)
    at mountComponent (vendors.js? [sm]:4187)
    at processComponent (vendors.js? [sm]:4141)
    at patch (vendors.js? [sm]:3669)(env: macOS,mp,1.06.2407101; lib: 3.5.0)
    at createText (vendors.js? [sm]:6775)
    at processFragment (vendors.js? [sm]:4067)
    at patch (vendors.js? [sm]:3643)
    at ReactiveEffect.componentUpdateFn [as fn] (vendors.js? [sm]:4285)
    at ReactiveEffect.value (vendors.js? [sm]:354)
    at instance.update (vendors.js? [sm]:4409)
    at setupRenderEffect (vendors.js? [sm]:4419)
    at mountComponent (vendors.js? [sm]:4187)
    at processComponent (vendors.js? [sm]:4141)
    at patch (vendors.js? [sm]:3669)(env: macOS,mp,1.06.2407101; lib: 3.5.0)

### 环境信息
```
 Taro v4.0.2


  Taro CLI 4.0.2 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 4.0.2 => 4.0.2 
      @tarojs/components: 4.0.2 => 4.0.2 
      @tarojs/helper: 4.0.2 => 4.0.2 
      @tarojs/plugin-framework-vue3: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-alipay: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-h5: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-harmony-hybrid: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-jd: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-qq: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-swan: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-tt: 4.0.2 => 4.0.2 
      @tarojs/plugin-platform-weapp: 4.0.2 => 4.0.2 
      @tarojs/runtime: 4.0.2 => 4.0.2 
      @tarojs/shared: 4.0.2 => 4.0.2 
      @tarojs/taro: 4.0.2 => 4.0.2 
      @tarojs/vite-runner: 4.0.2 => 4.0.2 
      babel-preset-taro: 4.0.2 => 4.0.2 
      eslint-config-taro: 4.0.2 => 4.0.2 
```

---
### 补充信息
1，项目版本为：taro4 vite4 vue3
2，babel.config.js中不是已经默认引用了babel-preset-taro吗？怎么这个还能报这个错
Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.eslint
3，什么都没改，直接初始化项目都报错

**Comment by 490626721** [comment]
现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅

**Comment by 490626721** [comment]
> 现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅

![捕获2](https://github.com/user-attachments/assets/81dc49bb-ac92-4198-9909-2dc7a2940a0d)
![捕获](https://github.com/user-attachments/assets/aba04661-a396-4df9-84d2-9eb1d8ec5348)

**Comment by Aliujiayu** [comment]
> > 现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅
> 
> ![捕获2](https://private-user-images.githubusercontent.com/31122122/351590959-81dc49bb-ac92-4198-9909-2dc7a2940a0d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDAwMzksIm5iZiI6MTcyMTg5OTczOSwicGF0aCI6Ii8zMTEyMjEyMi8zNTE1OTA5NTktODFkYzQ5YmItYWM5Mi00MTk4LTk5MDktMmRjN2EyOTQwYTBkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGVlODAyODUwOGUzYjZkZjhiNDc1ZTQ0MTc2NThmOTQwMjI3MDM3YzgwODg5MjI0YTRlNTZmZWFiM2Y2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4sAsgmFb0gGnLFgfRDFSNmF1nuWeXPIQMpD2TiF2G5E) ![捕获](https://private-user-images.githubusercontent.com/31122122/351590994-aba04661-a396-4df9-84d2-9eb1d8ec5348.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDAwMzksIm5iZiI6MTcyMTg5OTczOSwicGF0aCI6Ii8zMTEyMjEyMi8zNTE1OTA5OTQtYWJhMDQ2NjEtYTM5Ni00ZGY5LTg0ZDItOWViMWQ4ZWM1MzQ4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ODYxZjMxN2ViZjZlZDJjMjA5ZDUyMTAyOTMzYTM4MDQyOGVlNjNmNzA2NWM2MGRjOTJmNzI5N2I3YjdkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUrpfshbi5zkh5_5OGS_puFxToYdaA-Psy7bNk9tw1Y)

额这个咱不知道啊。。。。我2天前提的，你提我这他们也看不着吧

**Comment by ZEJIA-LIU** [comment]
4.0.3应该已经修复该问题了

**Comment by ZEJIA-LIU** [comment]
> issues表单内容拼接到



> 现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅

欢迎提交issue，感谢反馈问题，我们会尽快修复

**Comment by Aliujiayu** [comment]
> 4.0.3应该已经修复该问题了

2，babel.config.js中不是已经默认引用了babel-preset-taro吗？怎么这个还能报这个错
Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.eslint
------------------------------------------------------------------------------------------------------------------
我提的这个也修复了吗？.eslint设置为requireConfigFile: false，4.0也有其他报错，不知所云，3.6设置后就无报错了，我目前已经降级到3.6开发了，请问我想恢复到4的话，版本稳定吗？

**Comment by liqinuo** [comment]
> 现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅

可以正常提交的哦，请重新试试呢，同时检查下提交的内容是否符合

**Comment by 490626721** [comment]
> > 现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅
> 
> 可以正常提交的哦，请重新试试呢，同时检查下提交的内容是否符合

我这边不行，提交还是直接把内容拼接到url上，导致提交失败
![1722237121906](https://github.com/user-attachments/assets/c07d10c8-a26e-410a-8a8a-1f6739403af5)
![8b08af7eab8717e6cd3f0ee519896eb](https://github.com/user-attachments/assets/ae32662b-1b72-4187-abff-9d88b3da1e8f)

**Comment by 490626721** [comment]
> > > 现在直接issues都不让提了？新提issues表单内容拼接到url上提交？😅
> > 
> > 
> > ![捕获2](https://private-user-images.githubusercontent.com/31122122/351590959-81dc49bb-ac92-4198-9909-2dc7a2940a0d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDAwMzksIm5iZiI6MTcyMTg5OTczOSwicGF0aCI6Ii8zMTEyMjEyMi8zNTE1OTA5NTktODFkYzQ5YmItYWM5Mi00MTk4LTk5MDktMmRjN2EyOTQwYTBkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNGVlODAyODUwOGUzYjZkZjhiNDc1ZTQ0MTc2NThmOTQwMjI3MDM3YzgwODg5MjI0YTRlNTZmZWFiM2Y2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4sAsgmFb0gGnLFgfRDFSNmF1nuWeXPIQMpD2TiF2G5E) ![捕获](https://private-user-images.githubusercontent.com/31122122/351590994-aba04661-a396-4df9-84d2-9eb1d8ec5348.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDAwMzksIm5iZiI6MTcyMTg5OTczOSwicGF0aCI6Ii8zMTEyMjEyMi8zNTE1OTA5OTQtYWJhMDQ2NjEtYTM5Ni00ZGY5LTg0ZDItOWViMWQ4ZWM1MzQ4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5Mjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ODYxZjMxN2ViZjZlZDJjMjA5ZDUyMTAyOTMzYTM4MDQyOGVlNjNmNzA2NWM2MGRjOTJmNzI5N2I3YjdkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mUrpfshbi5zkh5_5OGS_puFxToYdaA-Psy7bNk9tw1Y)
> 
> 额这个咱不知道啊。。。。我2天前提的，你提我这他们也看不着吧

🥰借用一下楼层，他们能看到，多谢~
