### ISSUE TITLE
使用 android studio 安装项目依赖时报错

### ISSUE THREAD

**Issue by kunkuntang** [NervJS/taro#16154]
### 相关平台
React Native

### 复现仓库
[https://github.com/kunkuntang/test-taro-rn.git](https://github.com/kunkuntang/test-taro-rn.git)

**使用框架: React**

### 复现步骤
正常安装 taro 项目：
helloworld@cubeSugerdeiMac helloworld % taro init helloworld-tiktok-rn
👽 Taro v3.6.17

⚠ 获取 taro 全局配置文件失败，不存在全局配置文件：/Users/helloworld/.taro-global-config/index.json

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍 helloworld-tiktok-rn
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择编译工具 Webpack5
? 请选择包管理工具 yarn
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 react-native

使用 android studio 打开 项目里的  android 目录，让 android studio 安装项目依赖

### 期望结果
能够正常打包一个 安装 apk

### 实际结果
我每次使用 taro 启动 Android 的时候，开发环境是可以跑起来的，无论是 taro playground 还是 使用 yarn dev:android ，但是每次我想用 android studio 打包一个 apk 出来的时候，gradle 在安装依赖时总是会报下面的错误：

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FOLLY_LIB
linked by target "expo-modules-core" in directory /Volumes/GLOWAY_STK512GS3-S7_Media/www/helloworld/helloworld-tiktok-rn/node_modules/expo-modules-core/android/legacy
JSI_LIB
linked by target "expo-modules-core" in directory /Volumes/GLOWAY_STK512GS3-S7_Media/www/helloworld/helloworld-tiktok-rn/node_modules/expo-modules-core/android/legacy
REACT_NATIVE_JNI_LIB
linked by target "expo-modules-core" in directory /Volumes/GLOWAY_STK512GS3-S7_Media/www/helloworld/helloworld-tiktok-rn/node_modules/expo-modules-core/android/legacy
REACT_NATIVE_MODULES_CORE
linked by target "expo-modules-core" in directory /Volumes/GLOWAY_STK512GS3-S7_Media/www/helloworld/helloworld-tiktok-rn/node_modules/expo-modules-core/android/legacy

### 环境信息
```
👽 Taro v3.6.17


  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17 
      @tarojs/components: 3.6.17 => 3.6.17 
      @tarojs/helper: 3.6.17 => 3.6.17 
      @tarojs/plugin-framework-react: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-alipay: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-jd: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-qq: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-swan: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-tt: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17 
      @tarojs/react: 3.6.17 => 3.6.17 
      @tarojs/rn-runner: 3.6.17 => 3.6.17 
      @tarojs/rn-supporter: 3.6.17 => 3.6.17 
      @tarojs/runtime: 3.6.17 => 3.6.17 
      @tarojs/runtime-rn: 3.6.17 => 3.6.17 
      @tarojs/shared: 3.6.17 => 3.6.17 
      @tarojs/taro: 3.6.17 => 3.6.17 
      @tarojs/taro-loader: 3.6.17 => 3.6.17 
      @tarojs/taro-rn: 3.6.17 => 3.6.17 
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17 
      babel-preset-taro: 3.6.17 => 3.6.17 
      eslint-config-taro: 3.6.17 => 3.6.17 
      expo: ~47.0.3 => 47.0.14 
      react: ^18.1.0 => 18.3.1 
      react-native: ^0.70.1 => 0.70.15 
```

**Comment by soyouwantme** [comment]
@kunkuntang 请问问题是怎么解决的
