### ISSUE TITLE
组件 正常引用，就是 报错 ？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1616]
![image](https://user-images.githubusercontent.com/43346131/50274116-59757500-0477-11e9-8cac-641f92d53bf4.png)

组件 正常引用，ctrl 后可以跳到 组件，而且相同的组件在另外的 page 也 用过！

taro： v.1.2.0beta7

**Comment by luckyadam** [comment]
如果编译没有报错，并且编译后的文件都正确，那就重启一下开发者工具尝试下

**Comment by JoMartinezZhu** [comment]
> 如果编译没有报错，并且编译后的文件都正确，那就重启一下开发者工具尝试下

试了没有用，最后 是 把蓝牙模块的应用 （import  ...）上移在 npm 安装的包 之后，能运行了！
