### ISSUE TITLE
convert 相对路径文件无法找到

### ISSUE THREAD

**Issue by ayahua** [NervJS/taro#1619]
问题描述
在页面json的usingComponents中引用其他文件时，如果路径是“../components/xxx”，就会去转换命令运行的根目录下查找，结果就是找不到文件报错。

报错信息
image

image

我的项目文件是在project里面的，components是在项目文件里的，但是看报错信息，是去查找我运行taro convert的目录的相对路径了。

系统信息

Taro v1.2 及以上版本已添加 taro info 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

操作系统:macOS 10.13.6
Taro 版本:1.2.0
Node.js 版本 8.14.1
报错平台 weapp

**Comment by ayahua** [comment]
问题描述
在页面json的usingComponents中引用其他文件时，如果路径是“../components/xxx”，就会去转换命令运行的根目录下查找，结果就是找不到文件报错。

报错信息
![image](https://user-images.githubusercontent.com/36917157/50279041-9f383a80-0483-11e9-820a-b43c0aaed50a.png)

![image](https://user-images.githubusercontent.com/36917157/50279024-90ea1e80-0483-11e9-855c-2e822c796b44.png)

我的项目文件是在project里面的，components是在项目文件里的，但是看报错信息，是去查找我运行taro convert的目录的相对路径了。


系统信息

Taro v1.2 及以上版本已添加 taro info 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

操作系统:macOS 10.13.6
Taro 版本:1.2.0
Node.js 版本 8.14.1
报错平台 weapp

**Comment by luckyadam** [comment]
提供一下你的项目完整结构截图以及这个页面在你项目中所处的位置截图吧

**Comment by ayahua** [comment]
> 提供一下你的项目完整结构截图以及这个页面在你项目中所处的位置截图吧

![image](https://user-images.githubusercontent.com/36917157/50319816-4957a700-0504-11e9-9228-e23511e413ec.png)
![image](https://user-images.githubusercontent.com/36917157/50319827-596f8680-0504-11e9-86ea-d23de85f53a6.png)
![image](https://user-images.githubusercontent.com/36917157/50319862-8754cb00-0504-11e9-941f-47755888ef8a.png)

你好，上面第一张图是我项目的文件目录，第二张图是这个json所在的page的详细目录，我把引用路径改成第三张图这样，就不会报错了。

**Comment by luckyadam** [comment]
> 你好，上面第一张图是我项目的文件目录，第二张图是这个json所在的page的详细目录，我把引用路径改成第三张图这样，就不会报错了。

收到，我看下~

**Comment by stevekeol** [comment]
该issue尚未被解决，就被closed？
