### ISSUE TITLE
style class taro_page 没有设置 height 100%，没法全屏？

### ISSUE THREAD

**Issue by shpeng** [NervJS/taro#162]

**Comment by lkspc** [comment]
是有这个问题，我用的是 height: 100vh

**Comment by Harhao** [comment]
在使用ScrollView必须设置一个固定的高度才能绑定下拉事件生效，设置height为100vh的确是可以生效

**Comment by zhangzhenfei** [comment]
.taro_router {
  height: 100%;
}

.taro_page {
  height: 100%;
  overflow: auto;
}

在全局样式里面覆盖一下就好了，因为父级div没有设置一个有效的height，所以子元素的height:100%和min-height:100%是不会生效的

**Comment by dushaobindoudou** [comment]
每个页面不是有个config，为什么不直接配置一个style 或者 class 进去呢，这样设置就是全局的了，局限性太多了
