### ISSUE TITLE
小程序可以使用axios这个库么？

### ISSUE THREAD

**Issue by wangzhe13555313322** [NervJS/taro#1620]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
不能，用 Taro.request 或 flyio

**Comment by luis-wang** [comment]
> 不能，用 Taro.request 或 flyio

用axios会导致安装的库不匹配，编译失败

**Comment by fjc0k** [comment]
可以试试 [taro-axios](https://github.com/fjc0k/taro-axios)。

去除了 axios 对 nodejs 环境的适配，这也是导致 Taro 中不能使用它的原因。

新增 taro 适配器，在 H5 和 ReactNative 环境下使用其自带的 xhr 适配器，在其他环境下使用 taro 适配器。

**Comment by crimson968** [comment]
@fjc0k 使用taro-axios的时候在微信开发者工具小程序模式下需要设置代理或者修改端口之类的吗，我使用了taro-axios调试H5一切正常，但是小程序一直会catch error

**Comment by fjc0k** [comment]
@crimson968 taro-axios 版本，代码截图，错误截图

**Comment by crimson968** [comment]
@fjc0k 

taro-axios 版本："taro-axios": "^0.6.0"

代码截图：

![image](https://user-images.githubusercontent.com/40922240/70422685-160c8000-1aa7-11ea-967a-b4cc6aef48eb.png)

![image](https://user-images.githubusercontent.com/40922240/70422593-ea899580-1aa6-11ea-957e-7002a6cbb83d.png)

**Comment by fjc0k** [comment]
@crimson968 建议你查看控制台的 network 确认原因。request请求域名之类你也得了解。仍有问题请去 [taro-axios](https://github.com/fjc0k/taro-axios) 仓库提 issue。

**Comment by crimson968** [comment]
@fjc0k 好，谢谢大佬

**Comment by crimson968** [comment]
感觉应该就是他这个不支持了，我用wx.request是没问题的，不校验http
