### ISSUE TITLE
请问大佬Map组件里的bindmarkertap应该怎么使用？

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#1621]
**问题描述**
今天在有使用到Map组件，文档中学的比较简单，自己试着写了一下；
`import {Map, View} from '@tarojs/components';
import Taro from '@tarojs/taro';
import {BaseStorePage} from "../BaseStorePage";
import './storeMapList.scss';
import requetNet from "../../../../common/requestNet";
import integral from "../integral";
import userCommon from "../../../../common/userCommon";

export default class storeMapList extends BaseStorePage {

  constructor() {
    super(...arguments);
    this.state = {
      latitude: 24.47951,
      longitude: 118.08948,
      markers: [
        {
          id: 0,
          latitude: 24.47951,
          longitude: 118.08948,
          callout: {
            content: "厦门思明区政府12000元/㎡",
            padding: 10,
            display: "ALWAYS",
            textAlign: "center"
          }
        },
        {
          id: 1,
          latitude: 24.5131500000,
          longitude: 118.1468600000,
          callout: {
            content: " 厦门湖里区政府70000元/㎡",
            padding: 10,
            display: 'ALWAYS',
            textAlign: 'center'
          }
        },
        {
          id: 2,
          latitude: 24.7235700000,
          longitude: 118.1517300000,
          callout: {
            content: " 厦门市同安区政府100",
            padding: 10,
            display: 'ALWAYS',
            textAlign: 'center'
          }
        },
        {
          id: 3,
          latitude: 24.5759000000,
          longitude: 118.0972700000,
          callout: {
            content: " 厦门市集美区政府100",
            padding: 10,
            display: 'ALWAYS',
            textAlign: 'center'
          }
        },
        {
          id: 4,
          latitude: 24.4846000000,
          longitude: 118.0329300000,
          callout: {
            content: " 厦门市海沧区政府100",
            padding: 10,
            display: 'ALWAYS',
            textAlign: 'center'
          }
        },
        {
          id: 5,
          latitude: 24.6196000000,
          longitude: 118.2478900000,
          callout: {
            content: " 厦门市翔安区政府100",
            padding: 10,
            display: 'ALWAYS',
            textAlign: 'center'
          }
        }
      ],
      mapWidth: "",
      mapHeight: ""
    }
  }

  componentWillMount() {

  }

  onTap(e) {
    console.log(e);
  }

  markertap(e) {
    console.log(e);
  }

  render() {
    const longitude = this.state.longitude;
    const latitude = this.state.latitude;
    const markers = this.state.markers;
    return (
      <View className='company-pages-storeMapList'>
        <Map id='myMap' style='width: 100%; height: 300px;' latitude={latitude}
             longitude={longitude} markers={markers} showLocation bindmarkertap={this.markertap.bind(this)}
             onClick={this.onTap}
             includePoints={markers}/>
      </View>
    )
  }
}
`
bindmarkertap点击相应的marker控制台*警告*
内容如下：
Do not have markertap handler in component: store/pages/storeMapList/storeMapList. Please make sure that markertap handler has been defined in store/pages/storeMapList/storeMapList.
请问在Taro中该怎么用bindmarkertap属性

**期望行为**
bindmarkertap
点击标记点时触发，会返回marker的id

**报错信息**
Do not have markertap handler in component: store/pages/storeMapList/storeMapList. Please make sure that markertap handler has been defined in store/pages/storeMapList/storeMapList.

**系统信息**

 - 操作系统: [Mac OS 10.14.1 (18B75)]
 - Taro 版本 ["@tarojs/components": "1.2.0",]
 - Node.js 版本 [v10.8.0]
 - 报错平台 [weapp]

**Comment by zhou1992zg** [comment]
return中的代码：
`<View className='company-pages-storeMapList'>
        <Map id='myMap' style='width: 100%; height: 300px;' latitude={latitude}
             longitude={longitude} markers={markers} showLocation bindmarkertap={this.markertap.bind(this)}
             onClick={this.onTap}
             includePoints={markers}/>
      </View>`

**Comment by yuche** [comment]
`onMarkerTap`

https://nervjs.github.io/taro/docs/event.html#docsNav

**Comment by jinyindu** [comment]
百度小程序onMarkerTap 在开发者工具是可以的 ，但是真机上点了没效果

**Comment by Linyccc** [comment]
这问题还是没解决吗？真机上用onMarkerTap 安卓机上没效果，IOS的可以。bindmarkerTap也是报一楼的问题，是不是dist编译完出现了问题？
