### ISSUE TITLE
在抖音小程序的 button 组件缺少 bindgetidentityinfo 属性方法

### ISSUE THREAD

**Issue by zen0822** [NervJS/taro#16212]
### 这个特性解决了什么问题？
详情可以参考这个链接：https://developer.open-douyin.com/docs/resource/js-component/apiMeta?apiName=button-getIdentityInfo&nodeId=7389524161669892389&scope=component.buttonGetIdentityInfo

同时满足以下条件：

- 抖音号不是“抖音B号”

- 内部能力申请通过

- 用户的抖音号已完成实名认证

- 满足小程序隐私协议管控要求 ，前置用户已授权小程序隐私协议

步骤：
1. <button
  open-type="getIdentityInfo"
  bindgetidentityinfo="getIdentityInfoHandler"
></button>
2. 点击即可唤起获取身份证信息功能

### 这个 API 长什么样？
<button
  open-type="getIdentityInfo"
  bindgetidentityinfo="getIdentityInfoHandler"
></button>

**Comment by zen0822** [comment]
想问下需要在哪个分支拉代码现在，3.0+ 的可以吗

**Comment by zen0822** [comment]
> 想问下需要在哪个分支拉代码现在，3.0+ 的可以吗

@ZEJIA-LIU

**Comment by TheKonka** [comment]
![image](https://github.com/user-attachments/assets/f5c47a44-df1c-4cd2-9062-a9f77389fb47)


这个链接内容的样式为什么这么奇怪

**Comment by zen0822** [comment]
> ![image](https://private-user-images.githubusercontent.com/22173084/367701098-f5c47a44-df1c-4cd2-9062-a9f77389fb47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDQ3NzIsIm5iZiI6MTcyNzE0NDQ3MiwicGF0aCI6Ii8yMjE3MzA4NC8zNjc3MDEwOTgtZjVjNDdhNDQtZGYxYy00Y2QyLTkwNjItYTlmNzczODlmYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAyMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODJmMDFhNzUzYmY3MTMzNDNkMWVmZWJkZTljNTgzYzMwNzk3Yjg5ZGM4YjI2OTkwOTA3YWMwYTQ2YmQ2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qiELlHC8z97jFONJf38FG4vqZlZFYxOY_LXXpJWp8L4)
> 
> 这个链接内容的样式为什么这么奇怪

因为这个文档还在抖音官方文档审核中，还没正式发布，这边已经在部分商户开放了白名单了，所以恳请组织能支持下这个新属性 :D
