### ISSUE TITLE
Taro 3.6.32版本在开发过程中不支持热更新

### ISSUE THREAD

**Issue by MarkLogin** [NervJS/taro#16210]
### 相关平台
H5

**浏览器版本: 126.0.6478.127: Chrome**
**使用框架: React**

### 复现步骤
正常使用Webpack5运行一个开发程序，代码更新修改保存后，网页没有实时热更新，需要手动刷新，求解决方案；

或者是Taro下如何自定义Webpack配置，网上未找到解决方案；

### 期望结果
Taro3.6.32 使用Webpack5 可以热更新

### 实际结果
[HMR] Checking for updates on the s
log.js:41 Ignored an update to unaccepted module 
log.js:41 [HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR] Nothing hot updated.

### 环境信息
```
  Taro CLI 3.6.31 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.20.2 - C:\Program Files\nodejs\node.EXE 
      Yarn: 1.22.22 - D:\nodejs\npm_path\yarn.CMD      
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      @tarojs/cli: 3.6.32 => 3.6.32 
      @tarojs/components: 3.6.32 => 3.6.32 
      @tarojs/plugin-framework-react: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-h5: ^3.6.32 => 3.6.34    
      @tarojs/react: 3.6.32 => 3.6.32 
      @tarojs/runtime: 3.6.32 => 3.6.32 
      @tarojs/taro: 3.6.32 => 3.6.32 
      @tarojs/webpack5-runner: 3.6.32 => 3.6.32
      babel-preset-taro: 3.6.32 => 3.6.32
      eslint-config-taro: 3.6.32 => 3.6.32
      react: ^17.0.0 => 17.0.2
```

**Comment by Rambos** [comment]
似乎有这个问题，很坑

**Comment by 17** [comment]
#15751 试试这个

**Comment by MarkLogin** [comment]
> #15751 试试这个

我运行的是H5环境，参照微信的这个配置不好使。

**Comment by Yss123Yue** [comment]
微信小程序  试着 把 微信开发工具的热重载关掉   把compileHotReLoad 设置为 true 试着好使
![image](https://github.com/user-attachments/assets/947c7239-0fa0-4137-b122-5fc1a646f5b7)
![image](https://github.com/user-attachments/assets/880e7da8-decf-4bef-9579-2e134177281c)

**Comment by 490626721** [comment]
Trao 4.0.7  vue3  nutui  H5端还是存在此问题，每次运行前可以正常编译1-2次，后面再修改代码后页面还是不更新，
