### ISSUE TITLE
编译成百度小程序，分包无法访问

### ISSUE THREAD

**Issue by JavaNoScript** [NervJS/taro#1623]
跟直接用百度小程序分包生成的文件一样，用百度小程序生成的文件可以访问。taro编译成的百度小程序pages主包可以访问，分包编译的时候都没有编译，访问不了。

**Comment by luckyadam** [comment]
贴一下你的 app.js

**Comment by htf123** [comment]
> 贴一下你的 app.js

import '@tarojs/async-await'
import Taro, { Component } from '@tarojs/taro'
import { Provider } from '@tarojs/redux'

import Index from './pages/index/index'

import configStore from './store'

import './app.scss'

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

const store = configStore()

class App extends Component {

  config = {
    pages: [
      'pages/index/index',
      'pages/other/other'
    ],
    subpackages: [
      {
        root: 'subpackage',
        pages: [
          'demo/demo',
        ]
      }
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  }

  componentDidMount () {}

  componentDidShow () {}

  componentDidHide () {}

  componentCatchError () {}

  componentDidCatchError () {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
}

Taro.render(<App />, document.getElementById('app'))

**Comment by htf123** [comment]
![1545356810 1](https://user-images.githubusercontent.com/29914717/50320017-5c1eab80-0505-11e9-9b6d-62d44d5ab517.jpg)

**Comment by htf123** [comment]
> 字段用 `subPackages` 试试
> 另外，贴一下你的 taro 版本

版本：Taro v1.2.0-beta.16

能编译成百度小程序，但是跳转和编译模式都无法访问分包里的页面。pages主包里面的可以访问

<img width="294" alt="25454cc416dbc3389d178da3b9f0b3d" src="https://user-images.githubusercontent.com/29914717/50391959-f2143980-0784-11e9-8b01-0b267172f319.png">

<img width="332" alt="49eaef9fe41c88ce6e90656017647d2" src="https://user-images.githubusercontent.com/29914717/50391961-f7718400-0784-11e9-8e50-dce08a72d0e7.png">

<img width="423" alt="8f7b56d392b6bc19102d52ba33e86b9" src="https://user-images.githubusercontent.com/29914717/50391962-fc363800-0784-11e9-98e6-57e18e597ed6.png">

跳转报错
<img width="968" alt="3e1132ded4a089b2a47556e4e543203" src="https://user-images.githubusercontent.com/29914717/50391998-4b7c6880-0785-11e9-84ec-23f952be80e0.png">
<img width="479" alt="286bc8c1c0ad9a98669c4fafa72da7d" src="https://user-images.githubusercontent.com/29914717/50392010-618a2900-0785-11e9-8952-fb4e555f0f77.png">

**Comment by luckyadam** [comment]
你的字段换成 `subPackages ` 试一下啊

**Comment by luckyadam** [comment]
@htf123 能否再贴一下你编译生成的 app.json

**Comment by htf123** [comment]
> @htf123 能否再贴一下你编译生成的 app.json

"pages": [
    "pages/index/index",
    "pages/other/other"
  ],
  "subpackages": [
    {
      "root": "subpackage",
      "pages": [
        "demo/demo"
      ]
    }
  ],
  "window": {
    "backgroundTextStyle": "light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "WeChat",
    "navigationBarTextStyle": "black"
  }
}

**Comment by luckyadam** [comment]
@htf123 
![image](https://user-images.githubusercontent.com/1782542/50472230-e6c64580-09f2-11e9-8e39-6e790b24ef26.png)
你这还是 subpackages 啊，写 subPackages

你看百度的报错
![image](https://user-images.githubusercontent.com/1782542/50472256-f6de2500-09f2-11e9-8ba1-40bd1c73aeba.png)

**Comment by htf123** [comment]
> @htf123
> ![image](https://user-images.githubusercontent.com/1782542/50472230-e6c64580-09f2-11e9-8e39-6e790b24ef26.png)
> 你这还是 subpackages 啊，写 subPackages
> 
> 你看百度的报错
> ![image](https://user-images.githubusercontent.com/1782542/50472256-f6de2500-09f2-11e9-8ba1-40bd1c73aeba.png)

可以了大神，蟹蟹。可是为什么微信的文档写的是subpackage，小写的，代码里写大写，编译成大写的也好使。之前跟着微信的来，复制粘贴的。

**Comment by luckyadam** [comment]
@htf123 
微信是大小写都行，但是百度只能大写
