### ISSUE TITLE
现有项目，移植到taro中，scss引入路径报错。

### ISSUE THREAD

**Issue by Yana5417** [NervJS/taro#1625]
**问题描述**
[问题描述：我现在想把现有项目移植到taro中，使用taro的多端代码功能。但是使用taro convert命令之后，发现原来的templates文件夹没有了，assets下面的styles文件夹也没有了，还会报引入components下面的scss路径错误。]

**复现步骤**
[复现问题的步骤]
1. 在当前项目src目录下，taro convert
2.跑 npm run dev:h5命令

**期望行为**
有两个疑问，taro支持现有项目移植吗？taro把小程序项目编译之后，templates这些文件被编译到哪里去了？期望能够帮我解答，谢谢！

**报错信息**
![wechatimg16235](https://user-images.githubusercontent.com/22390410/50321765-5f1d9a00-050d-11e9-9868-0a84a8ade712.jpeg)

**系统信息**

 - 操作系统: [mac OS]
 - Taro 版本 [v.1.2.0]
 - Node.js 版本 [v8.9.4]
 - 报错平台 [h5]

**Comment by luckyadam** [comment]
1、支持转义
2、templates 在 imports 目录下

![image](https://user-images.githubusercontent.com/1782542/50347799-de44b980-0571-11e9-8c92-68b9a4147a5d.png)

看一下 bottom-fixed/index.wxss 的源码
