### ISSUE TITLE
h5 打包好的文件名称如何加入哈希值

### ISSUE THREAD

**Issue by SmallRuralDog** [NervJS/taro#1626]
**问题描述**
现在的版本编译好的文件上传服务器了，如果改了代码重新编译好的文件名称还是一样的，这样就得去刷新cdn的缓存

**期望行为**
希望编译好的文件名称加入哈希值等标识

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.20]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5]

**Comment by Littly** [comment]
暂不支持 后续计划开放配置

**Comment by Littly** [comment]
更新：使用h5.output配置即可

```javascript
    output: {
      filename: 'js/[name].[hash:8].js',
      chunkFilename: 'js/[name].[chunkhash:8].js'
    }
```

**Comment by HuangHongRui** [comment]
:)

**Comment by xingwen93** [comment]
你好，那css 怎么加hash
？

**Comment by xingwen93** [comment]
@HuangHongRui @Littly

**Comment by QTTQ** [comment]
我也想问 css  怎么样能 使每次变成编译名不同

**Comment by js-newbee** [comment]
@QTTQ @xingwen93 css 打包带 hash 可参考：https://github.com/js-newbee/taro-best-practices/tree/master/multi-platform#%E6%89%93%E5%8C%85%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E5%B8%A6-hash-%E5%80%BC
