### ISSUE TITLE
请教为什么项目使用lerna的整包发布模式而不是"version": "independent"

### ISSUE THREAD

**Issue by tolerance-go** [NervJS/taro#163]
如果一个插件的小bug修复完成需要发布，那么导致所有子包的版本号都要迁移吧

**Comment by tolerance-go** [comment]
好像 babel 也是这种发布策略，想知道更多细节考虑~

**Comment by zacksleo** [comment]
放在一起和统一版本号为了方便维护吧，这么多包如果一个一个维护，特别是没这么多人力维护和需要快速迭代的情况下，版本号如果不一致，很容易管理混乱啊

**Comment by tolerance-go** [comment]
关键词快速迭代 3q

**Comment by yuche** [comment]
因为每一个包单独拿出来都没用，必须组合在一起才能有效果。但除了少数包之外，也没什么是必须一定要加上的。所以就做成 babel 一样的插件化统一管理。
