### ISSUE TITLE
解构语法-默认值

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#1630]
![image](https://user-images.githubusercontent.com/25219300/50324347-5b901000-0519-11e9-9b46-6c79a8936d2c.png)

![image](https://user-images.githubusercontent.com/25219300/50324362-74002a80-0519-11e9-8bd7-a6cfb5148966.png)

**Comment by Chen-jj** [comment]
暂时通过使用 defaultProps 解决

**Comment by patchBig** [comment]
现在的 需求是 自己定义了一个组件，能够自定义 title ，组件中已经定义了 defaultProps
![image](https://user-images.githubusercontent.com/25219300/50330436-2940db80-0536-11e9-972d-48798e189357.png)

然后在 页面中，不需要传入  title 字段
![image](https://user-images.githubusercontent.com/25219300/50330488-5ee5c480-0536-11e9-8d6b-75c6378dc177.png)

这样的话就会导致这个问题

**Comment by patchBig** [comment]
### 还有一个问题：在自定义组件中，回调传入组件的 自定义事件不成功
```js
Taro.request({
        url: `${context.serverDomain}/api/user/login-by-wechat-phone`,
        data: that.data.registerData,
        method: 'POST',
        dataType: 'json',
        header: {
          Authorization: 'Bearer ' + result.token,
        },
        success(res) {
          let data = res.data
          if (data.success) {
            if (data.data.registered) {
              that.setState({
                show: false
              })
              let user_id = app.parseSubject(data.data.accessToken).userId
              RT.register({
                user_id
              })
              app.updateLgToken(
                {
                  accessToken: data.data.accessToken,
                  expiresIn: data.data.expiresIn,
                  refreshToken: data.data.refreshToken,
                  tokenType: data.data.tokenType
                },
                () => {
                  Taro.showToast({
                    title: '登录成功',
                    icon: 'success',
                    duration: 300
                  })
                  console.log(that)
                  // that.props.onEvent('onLoginSuccess')
                  // that.$scope.triggerEvent('onLoginSuccess')
                  that.props.onLoginSuccess()
                }
              )
          } else {
            app.showToast(`${data.msg} :-)`)
          }
        }
      })
```

### 组件中的 console
![image](https://user-images.githubusercontent.com/25219300/50330823-a02aa400-0537-11e9-9f1f-7c92769c0bbe.png)


### page 中

```
<RegisterModal 
    onLoginSuccess={this.loginSuccess.bind(this)}
    show={showLoginWays}
/>
```

![image](https://user-images.githubusercontent.com/25219300/50330866-c18b9000-0537-11e9-8e3a-ea244ace8f39.png)

![image](https://user-images.githubusercontent.com/25219300/50330958-0a434900-0538-11e9-9f95-739535aae81e.png)

**Comment by yuche** [comment]
@patchBig 
```jsx
// 原来
success(res) {
...
}
// 写成这样：
success: (res) => {
..
}
// 或者在一开始的时候
const { onLoginSuccess } = this.props
onLoginSuccess()
```
这样你就不用写 that 了，当你写 `that.props.onLoginSuccess()` 的时候编译器检测不到你这个函数是从哪来的。

**Comment by Chen-jj** [comment]
@patchBig 你子组件定义了 defaultProps，父组件不传 title，不就使用了 defaultProps 中定义的 title 值了么。

**Comment by zhouweiming** [comment]
结构语法里面，为null的值不会使用默认值，undefined才会使用默认值，这是正常的吧

**Comment by patchBig** [comment]
> @patchBig 你子组件定义了 defaultProps，父组件不传 title，不就使用了 defaultProps 中定义的 title 值了么。

并没有。。。直接就是 null

**Comment by Chen-jj** [comment]
@zhouweiming 父组件不传的话，在 react 中是 undefined，他这样写应该正常取到默认值。

但小程序中，props 通过小程序组件化的 properties 实现，父组件不传时参数默认值为 null，所以他这种解构写法取不到默认值。

暂时推荐使用 defaultProps 解决。

**Comment by Chen-jj** [comment]
@patchBig 贴一下父子组件可复现代码。

感觉你是写了 defaultProps 的同时，又使用了解构赋予默认值的写法。

**Comment by patchBig** [comment]
### 子组件
```
import { Block, View, Form, Button, Image, Text } from '@tarojs/components'
import Taro from '@tarojs/taro'
import withWeapp from '@tarojs/with-weapp'
import Toast from '../toast/index'
import Classnames from 'classnames'
import './index.scss'
// 用户注册模态框
let app = Taro.getApp()

@withWeapp('Component')
class _C extends Taro.Component {
  constructor(props) {
    super(props);
  }
  defaultProps = {
    show: false,
    title: '登录或注册'
  }

 render() {
    let {
      showModal: showModal,
      showPhoneRegisterModal: showPhoneRegisterModal,
      phoneNumber: phoneNumber
    } = this.state;

    let { show, title } = this.props;
    console.log(this.props)
 }
}
```

**Comment by patchBig** [comment]
### 父组件
```
<RegisterModal 
          onLoginSuccess={this.loginSuccess.bind(this)}
          show={showLoginWays}
        />
```

**Comment by patchBig** [comment]
> 那你就只能这样了：
> 
> ```
> success: (res) => {
> ..
> }
> ```
> 或者你写 async/await，不用回调式的 API。

这样可以 👍

不过为啥用 that 不好使呢？之前的 that 和 this 不是一个东西吗？🐶

**Comment by patchBig** [comment]
> 那你就只能这样了：
> 
> ```
> success: (res) => {
> ..
> }
> ```
> 或者你写 async/await，不用回调式的 API。

因为数据绑定的延时性？上面的 console 应该就说明这个问题了，对吗

**Comment by patchBig** [comment]
> @patchBig 贴一下父子组件可复现代码。
> 
> 感觉你是写了 defaultProps 的同时，又使用了解构赋予默认值的写法。

defaultProps 只能酱写？就没问题。。。
```
static defaultProps = {
    show: false,
    title: '登录或注册'
  }
```

**Comment by Chen-jj** [comment]
@patchBig 额，是的，建议先看看 ES6 class  中 static 属性的文档

**Comment by yuche** [comment]
@patchBig 因为编译器要求你一定要写 this.props.onXX 或者从 this.props 结构出来的函数才能正确编译。
如果你写箭头函数或者写 async/await 都可以避免这个问题。

**Comment by patchBig** [comment]
好的 非常感谢

> @patchBig 额，是的，建议先看看 ES6 class 中 static 属性的文档

非常感谢。。。

**Comment by patchBig** [comment]
> @patchBig 因为编译器要求你一定要写 this.props.onXX 或者从 this.props 结构出来的函数才能正确编译。
> 如果你写箭头函数或者写 async/await 都可以避免这个问题。

关于这点的话，文档中貌似没注意到有这一条。。。（不过以后注意吧）
