### ISSUE TITLE
h5执行打包操作报错

### ISSUE THREAD

**Issue by yamlling** [NervJS/taro#16314]
### 相关平台
H5

### 复现仓库
[https://gitee.com/yamlling_admin/taro-react-taroui.git](https://gitee.com/yamlling_admin/taro-react-taroui.git)
**浏览器版本: edge127.0.2651.98**
**使用框架: React**

### 复现步骤
npm run  build:h5

### 期望结果
打包成功

### 实际结果
vite v4.5.3 building for production...
✓ 3 modules transformed.
✓ built in 72ms
[vite]: Rollup failed to resolve import "\app.config.ts" from "C:/Users/Notx200/Desktop/react-app/src/index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
file:///C:/Users/Notx200/Desktop/react-app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:48216
                    throw new Error(`[vite]: Rollup failed to resolve import "${exporter}" from "${id}".\n`  
                          ^

Error: [vite]: Rollup failed to resolve import "\app.config.ts" from "C:/Users/Notx200/Desktop/react-app/src/index.html".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/Notx200/Desktop/react-app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:48216:27)
    at onwarn (C:\Users\Notx200\Desktop\react-app\node_modules\@vitejs\plugin-react\dist\index.cjs:274:9)
    at onRollupWarning (file:///C:/Users/Notx200/Desktop/react-app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:48245:9)
    at onwarn (file:///C:/Users/Notx200/Desktop/react-app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:47976:13)
    at file:///C:/Users/Notx200/Desktop/react-app/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///C:/Users/Notx200/Desktop/react-app/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/Notx200/Desktop/react-app/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///C:/Users/Notx200/Desktop/react-app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26 {
  watchFiles: [
    'taro:compiler',
    'C:\\Users\\Notx200\\Desktop\\react-app\\src\\pages\\index\\index.config.ts',
    'C:\\Users\\Notx200\\Desktop\\react-app\\src\\pages\\car\\index.config.ts',
    'C:/Users/Notx200/Desktop/react-app/src/index.html',
    '\x00vite/modulepreload-polyfill'
  ]
}

Node.js v18.20.4

### 环境信息
```
Taro v4.0.4


  Taro CLI 4.0.4 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 18.20.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 4.0.4 => 4.0.4
      @tarojs/components: 4.0.4 => 4.0.4
      @tarojs/helper: 4.0.4 => 4.0.4
      @tarojs/plugin-framework-react: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-alipay: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-h5: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-harmony-hybrid: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-jd: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-qq: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-swan: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-tt: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-weapp: 4.0.4 => 4.0.4
      @tarojs/react: 4.0.4 => 4.0.4
      @tarojs/runtime: 4.0.4 => 4.0.4
      @tarojs/shared: 4.0.4 => 4.0.4
      @tarojs/taro: 4.0.4 => 4.0.4
      @tarojs/vite-runner: 4.0.4 => 4.0.4
      babel-preset-taro: 4.0.4 => 4.0.4
      eslint-config-taro: 4.0.4 => 4.0.4
      react: ^18.0.0 => 18.3.1
      taro-ui: ^3.3.0 => 3.3.0
```

**Comment by legcc** [comment]
同样的问题

**Comment by yamlling** [comment]
在linux下试了下 可以成功打包， 初步判断应该是windows路径的问题

**Comment by legcc** [comment]
迁移到webpack正常，vite不行

**Comment by yamlling** [comment]
> 迁移到webpack正常，vite不行

目前只能使用linux打包

**Comment by WildernessZyr** [comment]
> 迁移到webpack正常，vite不行

请问如何迁移到webpack

**Comment by Echo-pain-killer** [comment]
我也遇到这个问题，官方能不能快点解决一下啊

**Comment by Hanson8684** [comment]
坑好多，各种各样的问题

**Comment by Lier1210** [comment]
我试了，提示一样的报错信息，windows电脑，我重新 Taro init 一个是webpack的项目，h5打包没问题了

**Comment by IsFaser** [comment]
**临时解决方案:**
```
<script><%= htmlWebpackPlugin.options.script %></script>
```
换成
```
  <script>!function(n){function f(){var e=n.document.documentElement,r=e.getBoundingClientRect(),width=r.width,height=r.height,arr=[width,height].filter(function(value){return Boolean(value)}),w=Math.min.apply(Math,arr),x=40*w/750;e.style.fontSize=x>=40?"40px":x<=20?"20px":x+"px"}; n.addEventListener("resize",(function(){f()})),f()}(window);</script>
  <script type="module" src="/app.config.js"></script>
```

**问题**
修复原理在
![image](https://github.com/user-attachments/assets/c1d4bd29-eb9e-49e2-9949-9aa8395f8ce7)
```
193 | ...
194 | return html.replace(/<script><%= htmlWebpackPlugin.options.script %><\/script>/, htmlScript);
195 | ...
```
万恶根源是
![image](https://github.com/user-attachments/assets/74d243a4-335b-4893-9955-4cdfa2772cb2)
的第35行

**Comment by Ada-siqiliu** [comment]
> **临时解决方案:**
> 
> ```
> <script><%= htmlWebpackPlugin.options.script %></script>
> ```
> 
> 换成
> 
> ```
>   <script>!function(n){function f(){var e=n.document.documentElement,r=e.getBoundingClientRect(),width=r.width,height=r.height,arr=[width,height].filter(function(value){return Boolean(value)}),w=Math.min.apply(Math,arr),x=40*w/750;e.style.fontSize=x>=40?"40px":x<=20?"20px":x+"px"}; n.addEventListener("resize",(function(){f()})),f()}(window);</script>
>   <script type="module" src="/app.config.js"></script>
> ```
> 
> **问题** 修复原理在 ![image](https://private-user-images.githubusercontent.com/46740335/391361114-c1d4bd29-eb9e-49e2-9949-9aa8395f8ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDk5ODAsIm5iZiI6MTczMzEwOTY4MCwicGF0aCI6Ii80Njc0MDMzNS8zOTEzNjExMTQtYzFkNGJkMjktZWI5ZS00OWUyLTk5NDktOWFhODM5NWY4Y2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNWM0MTUwYjY2NDAyMjVjOWY3ODczZGRmZTY4MWM3OWZkY2RmMzU2OWE0NmFlOTFjMjZkODRhN2Y4M2Q3ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Wk89bY5mkrhaD4vHNgi71HImAlbVs83TyCPFwYyO5U)
> 
> ```
> 193 | ...
> 194 | return html.replace(/<script><%= htmlWebpackPlugin.options.script %><\/script>/, htmlScript);
> 195 | ...
> ```
> 
> 万恶根源(L35) ![image](https://private-user-images.githubusercontent.com/46740335/391361159-74d243a4-335b-4893-9955-4cdfa2772cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDk5ODAsIm5iZiI6MTczMzEwOTY4MCwicGF0aCI6Ii80Njc0MDMzNS8zOTEzNjExNTktNzRkMjQzYTQtMzM1Yi00ODkzLTk5NTUtNGNkZmEyNzcyY2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAzMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNWQ2MTE3ZDk1MTc1MmQ5NjUzNzNlNTAzYzg1MzAzODI2MTk2MTkxY2Q4NmMyZDE0NDdlMTdlNjJiOTM2YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IPfhX9_uHkiogFNzp3pI_h0XxGChR9AfmClMqXCwR_0)

这个方法不行呢，我试了还是报同样的错误

**Comment by Ada-siqiliu** [comment]
上边的临时解决方案不行呢，还是同样的错误
