### ISSUE TITLE
@tarojs/webpack-runner 在本机无法安装，代理已挂、非网络原因

### ISSUE THREAD

**Issue by joker-li** [NervJS/taro#1631]
**问题描述**
环境:mac 10.14.2  @tarojs/webpack-runner 无法成功安装 

**复现步骤**
1. 按照网站教程命令行初始化一个taro app
2. npm run dev:h5
3. 出现 @tarojs/webpack-runner 无法安装情况

****终端报错信息***
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/apple./Documents/private/myApp/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/apple./Documents/private/myApp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/apple./Documents/private/myApp/node_modules/node-sass
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**期望行为**
希望能 为我解惑

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
👽 Taro v1.2.0

  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^1.2.0 => 1.2.0
      @tarojs/plugin-babel: ^1.2.0 => 1.2.0
      @tarojs/plugin-csso: ^1.2.0 => 1.2.0
      @tarojs/plugin-less: ^1.2.0 => 1.2.0
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.0
      @tarojs/rn-runner: ^1.2.0 => 1.2.0
      @tarojs/router: ^1.2.0 => 1.2.0
      @tarojs/taro: ^1.2.0 => 1.2.0
      @tarojs/taro-alipay: ^1.2.0 => 1.2.0
      @tarojs/taro-h5: ^1.2.0 => 1.2.0
      @tarojs/taro-swan: ^1.2.0 => 1.2.0
      @tarojs/taro-weapp: ^1.2.0 => 1.2.0
      eslint-config-taro: ^1.2.0 => 1.2.0
      eslint-plugin-taro: ^1.2.0 => 1.2.0

**Comment by joker-li** [comment]
已找到解决办法 sudo xcode-select --install 即可

**Comment by iWinston** [comment]
![image](https://user-images.githubusercontent.com/23229557/76377939-1eff3d00-6387-11ea-9e36-1f0d785297c3.png)
已经安装 xcode-select 依旧报错

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/76382331-4e1bab80-6393-11ea-9a46-a99b790a2a45.png)

**Comment by liuzhenji** [comment]
2.0升级体验真差，费老功夫了。升个级还要我像研究系统一样去解决问题。。。

`xcode-select --install`不行的，跑下面的，先删了再装
```

sudo rm -rf $(xcode-select -print-path)
xcode-select --install
```

**Comment by shenghanqin** [comment]
@liuzhenji 要淡定。我从去年6月开始折腾Taro 1.3.0-beta版，到现在的跟进2.0、3.0版本，里面也踩过特别多的坑。
2.0.0大版本升级，必定会有坑，那就得踩一踩。比如我就在2.0升级中配错了一个配置，导致小程序发布后css样式合并有问题。嘻嘻
