### ISSUE TITLE
defaultProps的数据在第二次render后变成undefined

### ISSUE THREAD

**Issue by XiaogeTek** [NervJS/taro#1633]
**问题描述**
如题

**复现步骤**
1. 见下面所附代码，调试时断点打在const { compTypes } = this.props后
2. 重新编译run起来首次断点断下，compTypes正常
3. 下一次断点断下时，compTypes变成undefined

```js
import Taro from '@tarojs/taro'
import {View, Swiper, SwiperItem, Image, } from '@tarojs/components'

import './index.scss'

export default class Index extends Taro.Component {

  static defaultProps = {
    compTypes : {
      A: 0,
      B: 1,
      C: 2,
      D: 3,
      E: 4,
      F: 5,
      G: 6
    }
  }

  render() {

    const { compTypes } = this.props
    const comp = {type:0, title: 'a'}
    
    return (
      <View className='page'>
        {
          comp.type===compTypes.A&&<View>{comp.title}</View>
        }
      </View>
    )
  }
}


```

**期望行为**
defaultProps中的值不丢失

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.2.0]
 - Node.js 版本 [v10.14.1]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
看一下你的项目依赖版本

**Comment by XiaogeTek** [comment]
> 看一下你的项目依赖版本

1.2.0

**Comment by Chen-jj** [comment]
@XiaogeTek Index 是页面还是组件

**Comment by XiaogeTek** [comment]
@Chen-jj 页面

**Comment by Chen-jj** [comment]
@XiaogeTek 

1.如果页面不会接受 props，这里改用 state。

2.如果页面会接受 Redux 传入的 props，给 store 默认值。

总之页面不需要用到 defaultProps。

**Comment by XiaogeTek** [comment]
@Chen-jj 明白，感谢

**Comment by Ariskywi** [comment]
遇到了同样的问题。
@Chen-jj 觉得还是需要defaultProps的
对于没有使用Redux的应用,组件的prop不一定每次都设置,defaultProps很好的解决了这个问题。

还希望能解决bug

**Comment by Chen-jj** [comment]
@Ariskywi 请认真看我的回答，这个 issue 说的是“**页面**”
