### ISSUE TITLE
小程序scss编译后某些组件或页面样式丢失

### ISSUE THREAD

**Issue by xionghao1991** [NervJS/taro#1635]
**问题描述**
重新编译后有些样式不会被编译。重新进入文件修改后保存，可以正常编译出样式。

**复现步骤**
[复现问题的步骤]
1. 重新npm run dev:weapp
2. 查看文件某些样式出现问题
3. 重新修改文件保存可重新编译出样式

**期望行为**

**所有样式可以正常编译**

![tim 20181221181551](https://user-images.githubusercontent.com/12246987/50337581-8b0c4000-054c-11e9-8108-b3bfef310316.png)

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.0]
 - Node.js 版本 [e.g. v10.10.0]
 - 报错平台 [weapp]

**Comment by xionghao1991** [comment]
> 样式你 import 了么

import了。这个是组件内的。肯定有import。

**Comment by nailfar** [comment]
导入第三方库也是 经常丢失文件 ，多编译几次就好了，这也太为难开发了。每天起来就是赌博,运气好编译就过了。 @LuckyJoker

**Comment by luckyadam** [comment]
@xionghao1991 贴一下相关代码

**Comment by luckyadam** [comment]
@nailfar 不是 taro 的文件，只要正确引用 taro 不会丢文件，你编译完进入 dist 目录查看就知道，是开发者工具没有识别到文件变更，你可以重启开发者工具试试

**Comment by jinjinwa** [comment]
编译N次也还是样式丢失

**Comment by xfcdxg** [comment]
> 编译N次也还是样式丢失
耐心点，实在不行试试重启一下机器...

**Comment by xfcdxg** [comment]
@jinjinjin0731 耐心一点~要不试试重启下机器？
