### ISSUE TITLE
更新1.2.1 之后bind不能给方法传值了

### ISSUE THREAD

**Issue by numcome** [NervJS/taro#1638]
更新1.2.1 之后bind不能给方法传值了
![image](https://user-images.githubusercontent.com/31194716/50369595-2ea03380-05d3-11e9-8b3a-b4b7cd1759d3.png)
![image](https://user-images.githubusercontent.com/31194716/50369599-3f50a980-05d3-11e9-9c91-6d234b165f28.png)

**Comment by luckyadam** [comment]
cli 和项目依赖都要升级到 1.2.1

**Comment by huangyunlong** [comment]
我也遇到这种情况了，taro update project之后通过yarn 重装包还是出现这个问题，请问啥情况

**Comment by luckyadam** [comment]
@huangyunlong 估计是没升级成功

**Comment by huangyunlong** [comment]
我升级到1.22，taro-ui又不能用了，taro-ui用的是1.5
