### ISSUE TITLE
生成ts项目后，怎么调试ts代码呢？

### ISSUE THREAD

**Issue by fantasticsoul** [NervJS/taro#164]
看了官网文档，有个debug指南，但是点击不开，看起来还没有准备好debug相关的指导吗，还是说现阶段暂时不支持调试

**Comment by fantasticsoul** [comment]
好吧，我尝试着弄ts-loader来调试，折腾了一下，算了，回到浏览器的sources tab里找到相应的js文件，直接打断点调试，目前觉得还是能够接受的，之前写react也是一直调试babel编译后的代码，现在只能继续这样了，这个问题暂时关闭吧

**Comment by zacksleo** [comment]
小程序调试好像没啥好办法吧，console 打印？

**Comment by fantasticsoul** [comment]
编译后的js代码可以打断点的

**Comment by luckyadam** [comment]
恩~ 后面可以加入 source map，目前 source map还有点问题，还没放出

**Comment by ronffy** [comment]
source map 还没好吗，开发小程序，没有 source map ，太苦逼了 😂

**Comment by shenghanqin** [comment]
@fantasticsoul 请留心2.0.0beta的source map功能。如果没啥疑问，我选择的是answered啦
