### ISSUE TITLE
更新1.2.1不断报错

### ISSUE THREAD

**Issue by dsky1990** [NervJS/taro#1642]
![image](https://user-images.githubusercontent.com/1579516/50370846-16d3aa00-05e9-11e9-8af5-264c3c25b6d0.png)

- h5

```
👽 Taro v1.2.1


  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.1 => 1.2.1 
      @tarojs/components: ^1.2.1 => 1.2.1 
      @tarojs/plugin-babel: ^1.2.1 => 1.2.1 
      @tarojs/plugin-csso: ^1.2.1 => 1.2.1 
      @tarojs/plugin-sass: ^1.2.1 => 1.2.1 
      @tarojs/plugin-uglifyjs: ^1.2.1 => 1.2.1 
      @tarojs/redux: ^1.2.1 => 1.2.1 
      @tarojs/redux-h5: ^1.2.1 => 1.2.1 
      @tarojs/router: ^1.2.1 => 1.2.1 
      @tarojs/taro: ^1.2.1 => 1.2.1 
      @tarojs/taro-alipay: ^1.2.1 => 1.2.1 
      @tarojs/taro-h5: ^1.2.1 => 1.2.1 
      @tarojs/taro-swan: ^1.2.1 => 1.2.1 
      @tarojs/taro-weapp: ^1.2.1 => 1.2.1 
      @tarojs/webpack-runner: ^1.2.1 => 1.2.1 
      eslint-config-taro: ^1.2.1 => 1.2.1 
      eslint-plugin-taro: ^1.2.1 => 1.2.1 
    npmGlobalPackages:
      typescript: 3.1.6
```

**Comment by luckyadam** [comment]
https://tonghuashuo.github.io/blog/webpack-dev-server-invalid-host-header.html
你看看是不是这个原因

**Comment by dsky1990** [comment]
@luckyadam 好的，感谢🙏

**Comment by dsky1990** [comment]
@luckyadam 额，taro好像没有暴露webpack配置的地方，还有就是我host是默认的`127.0.0.1:10086`，按照文章上的，不会出现这个问题啊
> 例外
当然，或许你并没有遇到这样的问题（等等，如果你没遇到这个问题，你又是出于什么原因把这篇文章看到了这里？），因为官方贴心的设置了一些例外场景，这些场景下不受该补丁的影响：
> - host 为 localhost 或 127.0.0.1 时不会受阻。
> - 只有使用 webpack-dev-server 或 webpack-dev-middleware 时会进行该项检测，webpack 和 打包后的代码不受此影响。

**Comment by ly326269899** [comment]
我刚创建初始工程也一直报错..　强迫症不能忍
查阅了一下是因为　webpack 一直在对host进行安全检查 
解决方法是在工程的config目录下 增加这一段代码
![image](https://user-images.githubusercontent.com/19767452/50371455-14c41800-05f6-11e9-8cb1-05df70c54a6a.png)

**Comment by dsky1990** [comment]
感谢 @ly326269899
