### ISSUE TITLE
希望推进taro4.x适配tailwindcss

### ISSUE THREAD

**Issue by Ka0fKa** [NervJS/taro#16458]
### 这个特性解决了什么问题？
taro4.x适配tailwindcss，在taro流畅的使用tailwindcss。

### 这个 API 长什么样？
希望官方出一个适配，第三方插件很多都不更新了https://github.com/pcdotfan/taro-plugin-tailwind

**Comment by Ryan-CW-Code** [comment]
https://taro-docs.jd.com/docs/tailwindcss
weapp-tailwindcss已经很好的支持了

**Comment by viweei** [comment]
使用 vite 打包的并并没有适配

**Comment by linfanxxxx** [comment]
> 使用 vite 打包的并并没有适配

https://weapp-tw.icebreaker.top/docs/quick-start/frameworks/taro#%E4%BD%BF%E7%94%A8-vite-%E4%BD%9C%E4%B8%BA%E6%89%93%E5%8C%85%E5%B7%A5%E5%85%B7

taro4.x 使用vite构建的方式，参考这个文档成功了
