### ISSUE TITLE
生成的base.wxml文件，在开启skyline的情况下报错

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#16462]
### 相关平台
微信小程序

**小程序基础库: 3.5.6**
**使用框架: React**

### 复现步骤
开启skyline，之后主要的问题有三个
1 block不支持id data-sid属性，需要删除
2 audio模板存在重复 id 属性
3 slot模板在seykline下的报错是 Error: child nodes are not allowed for this element

### 期望结果
正常编译

### 实际结果
报错

### 环境信息
```
Taro CLI 3.6.35 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - /var/folders/rf/gd60z12164z72bny7z_0d4f80000gn/T/yarn--1725449725979-0.31281094491222805/node
      Yarn: 1.22.22 - /var/folders/rf/gd60z12164z72bny7z_0d4f80000gn/T/yarn--1725449725979-0.31281094491222805/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.35 => 3.6.35 
      @tarojs/components: 3.6.35 => 3.6.35 
      @tarojs/helper: 3.6.35 => 3.6.35 
      @tarojs/plugin-framework-react: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-alipay: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-h5: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-jd: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-qq: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-swan: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-tt: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-weapp: 3.6.35 => 3.6.35 
      @tarojs/rn-runner: 3.6.35 => 3.6.35 
      @tarojs/runtime: 3.6.35 => 3.6.35 
      @tarojs/shared: 3.6.35 => 3.6.35 
      @tarojs/taro: 3.6.35 => 3.6.35 
      @tarojs/taro-rn: 3.6.35 => 3.6.35 
      @tarojs/webpack5-runner: 3.6.35 => 3.6.35 
      babel-preset-taro: 3.6.35 => 3.6.35 
      eslint-config-taro: 3.6.35 => 3.6.35 
      expo: ~48.0.19 => 48.0.21 
      react: ^18.2.0 => 18.3.1 
      react-native: ~0.71.11 => 0.71.19
```

**Comment by ShaoGongBra** [comment]
这是patch，可以参考下，不过我把NativeSlot注释掉会引起其他的问题，也没有去研究这里
```patch
diff --git a/node_modules/@tarojs/shared/dist/template.js b/node_modules/@tarojs/shared/dist/template.js
index d1eafbe..0a6fa28 100644
--- a/node_modules/@tarojs/shared/dist/template.js
+++ b/node_modules/@tarojs/shared/dist/template.js
@@ -194,7 +194,7 @@ const Navigator = {
     bindComplete: NO_DEFAULT_VALUE
 };
 const Audio = {
-    id: NO_DEFAULT_VALUE,
+    // id: NO_DEFAULT_VALUE,
     src: NO_DEFAULT_VALUE,
     loop: DEFAULT_FALSE,
     controls: DEFAULT_FALSE,
@@ -286,7 +286,7 @@ const internalComponents = {
     Map: MapComp,
     Slot,
     SlotView,
-    NativeSlot,
+    // NativeSlot,
     Script,
 };
 new Set([
@@ -1061,11 +1061,11 @@ ${this.buildXsTemplate()}
 </template>

 <template name="tmpl_${level}_${nodeAlias}_focus">
-  <${nodeName} ${this.buildAttribute(comp.attributes, nodeName)} id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">${children}</${nodeName}>
+  <${nodeName} ${this.buildAttribute(comp.attributes, nodeName)}${nodeName === "block" ? "" : ' id="{{i.uid||i.sid}}" data-sid=" {{i.sid}}"'}>${children}</${nodeName}>
 </template>

 <template name="tmpl_${level}_${nodeAlias}_blur">
-  <${nodeName} ${this.buildAttribute(attrs, nodeName)} id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">${children}</${nodeName}>
+  <${nodeName} ${this.buildAttribute(attrs, nodeName)}${nodeName === "block" ? "" : ' id="{{i.uid||i.sid}}" data-sid="{{i.sid}}"'}>${children}</${nodeName}>
 </template>
 `;
         if (isFunction(this.modifyTemplateResult)) {
@@ -1100,7 +1100,7 @@ ${this.buildXsTemplate()}
         }
         let res = `
 <template name="tmpl_${level}_${nodeAlias}">
-  <${nodeName} ${this.buildAttribute(comp.attributes, comp.nodeName)} id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">${children}</${nodeName}>
+  <${nodeName} ${this.buildAttribute(comp.attributes, comp.nodeName)}${nodeName === "block" ? "" : ' id="{{i.uid||i.sid}}" data-sid="{{i.sid}}"'}>${children}</${nodeName}>
 </template>
 `;
         if (isFunction(this.modifyTemplateResult)) {
@@ -1123,7 +1123,7 @@ ${this.buildXsTemplate()}
             if (compName === 'custom-wrapper') {
                 template += `
 <template name="tmpl_${level}_${compName}">
-  <${compName} i="{{i}}" l="{{l}}" id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">
+  <${compName} i="{{i}}" l="{{l}}"${compName === "block" ? "" : ' id="{{i.uid||i.sid}}" data-sid="{{i.sid}}"'}>
   </${compName}>
 </template>
   `;
@@ -1144,7 +1144,7 @@ ${this.buildXsTemplate()}
   `;
                 template += `
 <template name="tmpl_${level}_${compName}">
-  <${compName} ${this.buildThirdPartyAttr(attrs, this.thirdPartyPatcher[compName] || {})} id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">${children}</${compName}>
+  <${compName} ${this.buildThirdPartyAttr(attrs, this.thirdPartyPatcher[compName] || {})}${compName === "block" ? "" : ' id="{{i.uid||i.sid}}" data-sid="{{i.sid}}"'}>${children}</${compName}>
 </template>
   `;
             }

```

**Comment by ShaoGongBra** [comment]
slot 节点的子节点是无效的，没有含义。skyline 使用的 glass-easel 编译器会直接视为编译错误

这是官方回复

**Comment by TheKonka** [comment]
这 3个组件你是都用到了吗？ 如果没用到应该不会报错吧？

**Comment by ShaoGongBra** [comment]
> 这 3个组件你是都用到了吗？ 如果没用到应该不会报错吧？

audio这个我肯定没有用到呀

**Comment by TheKonka** [comment]
我也用了 skyline，3个组件都没有用到，base.wxml 里面只有模板自带的 block 组件，并且都没看到你说的那3个问题

**Comment by ShaoGongBra** [comment]
> 我也用了 skyline，3个组件都没有用到，base.wxml 里面只有模板自带的 block 组件，并且都没看到你说的那3个问题

看看是不是没有开启 glass-easel，我是开了这个

这是官方的回复
https://developers.weixin.qq.com/community/develop/doc/0008a8e4d78898624212ffe0561000

**Comment by TheKonka** [comment]
![image](https://github.com/user-attachments/assets/f533100c-0ca3-4904-a6be-7427c7a9e1fa)

你能给个复现这些问题的demo吗，我试了 audio 组件，模板确实id 重复了，但是这个组件已经弃用了，正常来说不用的话就没有影响。


block不支持id data-sid属性我这边没看到报错。

slot 正常也不会有，我知道的就是混合开发中 原生传子元素到 Taro 组件中可以会用到，https://docs.taro.zone/docs/taro-in-miniapp#%E4%BD%BF%E7%94%A8-slot

![image](https://github.com/user-attachments/assets/062c2783-b73b-4299-9764-192a72e799d4)
但是我直接用 NativeSlot 报错跟你的也不一样，不过删掉 slot 的 children 内容确实就不报错了

**Comment by ShaoGongBra** [comment]
> ![image](https://private-user-images.githubusercontent.com/22173084/367523980-f533100c-0ca3-4904-a6be-7427c7a9e1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjgyOTcsIm5iZiI6MTcyNjMyNzk5NywicGF0aCI6Ii8yMjE3MzA4NC8zNjc1MjM5ODAtZjUzMzEwMGMtMGNhMy00OTA0LWE2YmUtNzQyN2M3YTllMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTY2ZjI3ZGMyYjU0YThkNmRkOTY5NDMzNDkwYTZlNDUyYjIxZDVhOTNhYzQ2OTJhMzAzNWEzZDlkZjYyMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5hwGalWS9l96DoBLlUZMW6w18B3wpnDOf_KnA7vwzIw)
> 
> 你能给个复现这些问题的demo吗，我试了 audio 组件，模板确实id 重复了，但是这个组件已经弃用了，正常来说不用的话就没有影响。
> 
> block不支持id data-sid属性我这边没看到报错。
> 
> slot 正常也不会有，我知道的就是混合开发中 原生传子元素到 Taro 组件中可以会用到，https://docs.taro.zone/docs/taro-in-miniapp#%E4%BD%BF%E7%94%A8-slot
> 
> ![image](https://private-user-images.githubusercontent.com/22173084/367525289-062c2783-b73b-4299-9764-192a72e799d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjgyOTcsIm5iZiI6MTcyNjMyNzk5NywicGF0aCI6Ii8yMjE3MzA4NC8zNjc1MjUyODktMDYyYzI3ODMtYjczYi00Mjk5LTk3NjQtMTkyYTcyZTc5OWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1MzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1Zjg3ZjZkMDJlOTYxYTQyYjNmMDQ2NmU5ZWVhNTlhMTRkYWZmYjYyYWZiNzUyZjA3ZDZmN2QxZjZhYWRiOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHVz4y8QcANCvi2zipyQrr1IgLfIETrmJjIyftqhZMc) ~但是我直接用 NativeSlot 报错跟你的也不一样~，不过删掉 slot 的 children 内容确实就不报错了

使用这个命令创建一个项目  `npx duxapp-cli create testDuxui`

1 选择duxui模板
2导航到 `configs/duxuiExample/index.js` 取消下面这段代码的注释
```js
renderer: 'skyline',
    lazyCodeLoading: 'requiredComponents',
    componentFramework: 'glass-easel',
    rendererOptions: {
      skyline: {
        defaultDisplayBlock: false
      }
    },
```
3 使用命令 `yarn dev:weapp --app=duxuiExample` 启动编译，编译后打开就会看到了

这是我最近更新到Taro4的，也是同样的问题

**Comment by ShaoGongBra** [comment]
block不支持id data-sid属性我这边没看到报错。

这个就是大一堆 invalid attribute 报错，我删掉blick的这两个属性他就好了

**Comment by TheKonka** [comment]
![image](https://github.com/user-attachments/assets/35a45ef2-02e5-450e-98fb-166bcebcd112)

我启动后webview报这个错误，把 base.wxml 中的  slot 注释掉才正常渲染

![image](https://github.com/user-attachments/assets/201ba147-decf-4a8c-94f9-65a04db6ec30)

这是打开 skyline 的效果

![image](https://github.com/user-attachments/assets/a60df289-407e-4459-af41-4bca6c6d5b33)

目前看主要问题就是 slot 组件里面带了children 导致报错，你用了 taro-charts 这个库，这个库会把 taro-components 中所有组件都引入，也就包含了 audio 和 slot
