### ISSUE TITLE
升级Taro 1.2.1后AtInput失效

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1647]
升级Taro 1.2.1后AtInput失效
系统：Mac 10.13.6
node:10.13.0
Taro:1.2.1

**Comment by hugetiny** [comment]
onChange/onInput事件捕获不到

**Comment by luckyadam** [comment]
项目依赖也请同步升级

**Comment by hugetiny** [comment]
@luckyadam 已经taro update project了

**Comment by hugetiny** [comment]
这个不会是taro ui的兼容性问题吧

**Comment by yuche** [comment]
package.json 看一下是不是有漏网之鱼没升级

**Comment by hugetiny** [comment]
@luckyadam @yuche 

taro info
👽 Taro v1.2.1


  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.1 => 1.2.1 
      @tarojs/cli: 1.2.1 => 1.2.1 
      @tarojs/components: 1.2.1 => 1.2.1 
      @tarojs/plugin-babel: 1.2.1 => 1.2.1 
      @tarojs/plugin-csso: 1.2.1 => 1.2.1 
      @tarojs/plugin-sass: 1.2.1 => 1.2.1 
      @tarojs/plugin-uglifyjs: 1.2.1 => 1.2.1 
      @tarojs/redux: 1.2.1 => 1.2.1 
      @tarojs/redux-h5: 1.2.1 => 1.2.1 
      @tarojs/rn-runner: 1.2.1 => 1.2.1 
      @tarojs/router: 1.2.1 => 1.2.1 
      @tarojs/taro: 1.2.1 => 1.2.1 
      @tarojs/taro-alipay: 1.2.1 => 1.2.1 
      @tarojs/taro-h5: 1.2.1 => 1.2.1 
      @tarojs/taro-swan: 1.2.1 => 1.2.1 
      @tarojs/taro-weapp: 1.2.1 => 1.2.1 
      @tarojs/webpack-runner: 1.2.1 => 1.2.1 
      eslint-config-taro: 1.2.1 => 1.2.1 
      eslint-plugin-taro: 1.2.1 => 1.2.1

**Comment by hugetiny** [comment]
问题发生在h5上 小程序正常

**Comment by crper** [comment]
同样,发生了此问题,将会1.2.0正常..1.2.1结合taro ui , 控件的值拿到的是一个对象集合..而非直接的value..

用的也是非箭头函数 ,`this.xxx.bind(this)`

**Comment by hugetiny** [comment]
@luckyadam @yuche Taro UI 更新1.5.3后依然有这个问题

**Comment by luckyadam** [comment]
@jimczj 阿集帮忙看看~

**Comment by jimczj** [comment]
确实有问题，需要 input 基础组件修复一下问题

**Comment by jinjinjin0731** [comment]
基础库已经修复。待 TaroUI 发个新版本
