### ISSUE TITLE
mobx模板打包的apk文件，安装后运行报错，redux模板可以成功运行

### ISSUE THREAD

**Issue by bobchow** [NervJS/taro#1648]
**问题描述**
mobx模板打包的apk文件，安装后运行报错，redux模板可以成功运行

**复现步骤**
[复现问题的步骤]
1. taro init myApp，初始化一个新的项目
2. 在模板选择时，选择mobx模板
3. 然后npm run dev:rn，一切正常
4. 然后根据官方开发RN的文档，安装expo cli，然后expo build:android，一切正常打包
5. 将成功打包的apk文件安装到手机上，报错，报错如下：

**期望行为**
希望mobx编译打包的apk文件，安装后，可以正常运行

**报错信息**

![image](https://user-images.githubusercontent.com/2377207/50381272-d6922b80-06bd-11e9-8136-641c7356fc75.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 Taro v1.2.1
 - Node.js 版本 Node: 10.14.0 npm: 6.4.1
 - 报错平台 RN

**补充信息**
暂无

**Comment by nanjingboy** [comment]
@bobchow 看样子是因为 mobx 版本过高导致的，把 mobx 的依赖改为 4.8.0，然后再试试呢。

**Comment by bobchow** [comment]
> @bobchow 看样子是因为 mobx 版本过高导致的，把 mobx 的依赖改为 4.8.0，然后再试试呢。

试了下，mobx改到了4.8.0，还是一样的报错
