### ISSUE TITLE
为 app.css 的引入增加 hash

### ISSUE THREAD

**Issue by Jeff-Tian** [NervJS/taro#16498]
### 这个特性解决了什么问题？
![48d493d3205ee159a3d8eb92a661666](https://github.com/user-attachments/assets/62f6fa99-3aae-4989-ad4e-3b2252503f8b)

请问 taro build:h5 之后的 html 页面，引用 app.css 时，有办法设置一个 hash 吗？原因是改了 app.css 之后，浏览器缓存导致不能及时生效。

代码里是通过 import 引入的：

![5a23588c408a3e56b4080243afc2e58](https://github.com/user-attachments/assets/f39b8bb3-9e8c-4abf-9ff3-badf784c57b5)

### 这个 API 长什么样？
默认开启 hash

即可以是这样的引入：

```html
<link href="/css/app.a0123bcde.css" />
```

**Comment by x011223** [comment]
// config/index.js
```
  h5: {
    // ....
    miniCssExtractPluginOption: {
      filename: 'css/[name].[hash].css',
      chunkFilename: 'css/[name].[chunkhash].css',
    },
  },
```
