### ISSUE TITLE
建议：Taro有没有state自动存到storage或者通过dva自动把redux存到各个平台本地存储的功能

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1655]
Taro有没有state自动存到storage或者通过dva自动把redux存到各个平台本地存储的功能

现在一个个Taro.setStorage,Taro.getStorage太麻烦

**Comment by luckyadam** [comment]
这种功能需要你自己来实现，因为并不是通用功能，你可以自己封装一下相关 action

**Comment by hugetiny** [comment]
@luckyadam 对
