### ISSUE TITLE
Taro官网挂掉了，求解决

### ISSUE THREAD

**Issue by catchpeak** [NervJS/taro#16554]
### 这个特性解决了什么问题？
https://docs.taro.zone/ 官网文档挂掉了

### 这个 API 长什么样？
希望官网恢复访问

**Comment by catchpeak** [comment]
2024-09-19

**Comment by ainightf** [comment]
昨天到现在了还没好，太离谱了

**Comment by ainightf** [comment]
https://taro-docs.jd.com/docs/
是这个新地址
