### ISSUE TITLE
SystemError (webviewScriptError)，地图无法响应onRegionChange事件

### ISSUE THREAD

**Issue by wanghui9309** [NervJS/taro#16595]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Lliuxs/taro-app.git](https://github.com/Lliuxs/taro-app.git)
**小程序基础库: 3.4.10及以上版本**
**使用框架: React**

### 复现步骤
直接模版项目运行，整机调试打开调试工具，看到对应的报错且地图无回调事件
粘贴下列代码
```
export default function Index() {

  function onRegionChange(e) {
    console.log('********** regionchange ***********', e);
  }

  return (
    <View className='index'>
      <Map
        latitude={23.099994}
        longitude={113.32452}
        showLocation
        style={{ width: '100%', height: '100%' }}
        onRegionChange={(e) => onRegionChange(e)}
      ></Map>
    </View>
  );
}
```

### 期望结果
onRegionChange 事件有回调响应
无 SystemError (webviewScriptError) 报错

### 实际结果
onRegionChange 事件无回调响应
有 SystemError (webviewScriptError) 报错

### 环境信息
```
Taro v3.6.25


  Taro CLI 3.6.25 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
      npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.35 => 3.6.25 
      @tarojs/components: 3.6.35 => 3.6.25 
      @tarojs/helper: 3.6.35 => 3.6.25 
      @tarojs/plugin-framework-react: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-alipay: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-h5: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-jd: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-qq: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-swan: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-tt: 3.6.35 => 3.6.25 
      @tarojs/plugin-platform-weapp: 3.6.35 => 3.6.25 
      @tarojs/react: 3.6.35 => 3.6.25 
      @tarojs/runtime: 3.6.35 => 3.6.25 
      @tarojs/shared: 3.6.35 => 3.6.25 
      @tarojs/taro: 3.6.35 => 3.6.25 
      @tarojs/taro-loader: 3.6.35 => 3.6.25 
      @tarojs/webpack5-runner: 3.6.35 => 3.6.25 
      babel-preset-taro: 3.6.35 => 3.6.25 
      eslint-config-taro: 3.6.35 => 3.6.25 
      react: ^18.0.0 => 18.3.1 
```

---
### 补充信息
图片：https://developers.weixin.qq.com/community/develop/doc/00064ac1850758d4c122e95c561000?fromCreate=0

**Comment by wanghui9309** [comment]
部分安卓机型出现打开地图页报错，地图组件 onRegionChange 方法无响应回调
已知设备类型：iQOO Neo6 SE、小米10s、华为P40

**Comment by bfrontend** [comment]
只调用Map这个组件也有这个报错

**Comment by wanghui9309** [comment]
测试数据：
微信小程序基础库：3.5.8（3.4.10及以上）；3.4.0基础库无该问题
Taro：3.6.7、3.6.16、3.6.24、3.6.35 全部有微信地图事件回调无响应问题

**Comment by wanghui9309** [comment]
> > 部分安卓机型出现打开地图页报错，地图组件 onRegionChange 方法无响应回调 已知设备类型：iQOO Neo6 SE、小米10s、华为P40
> 
> 目前有解决方案吗

没找到解决方案，目前微信那边也提了问题反馈，估计是微信更新了什么导致这个问题

**Comment by wanghui9309** [comment]
> 只调用Map这个组件也有这个报错

我使用demo尝试了好几个Taro版本，这个问题还是存在

**Comment by Luxianshen** [comment]
我还以为是微信的bug 结果看起来是 taro的 我的版本3.6.17-35 都不行

**Comment by Luxianshen** [comment]
> webviewScriptError

和机型无关系 安卓微信版本为8.0.51 就不行

**Comment by wanghui9309** [comment]
> > webviewScriptError
> 
> 和机型无关系 安卓微信版本为8.0.51 就不行

现在问题关键不是这个报错，是导致编译后微信小程序map地图事件无回调才是关键

**Comment by Luxianshen** [comment]
> > > webviewScriptError
> > 
> > 
> > 和机型无关系 安卓微信版本为8.0.51 就不行
> 
> 现在问题关键不是这个报错，是导致编译后微信小程序map地图事件无回调才是关键

我也测出来是onRegionChange没有触发 但是我也发现了 安卓微信版本8.0.50 是可以的 iOS则不受影响

**Comment by luckyadam** [comment]
用微信原生试一试呢

**Comment by wanghui9309** [comment]
> > > > webviewScriptError
> > > 
> > > 
> > > 和机型无关系 安卓微信版本为8.0.51 就不行
> > 
> > 
> > 现在问题关键不是这个报错，是导致编译后微信小程序map地图事件无回调才是关键
> 
> 我也测出来是onRegionChange没有触发 但是我也发现了 安卓微信版本8.0.50 是可以的 iOS则不受影响

微信官方现在答复是原生测没问题，让Taro这边修改

**Comment by wanghui9309** [comment]
> 用微信原生试一试呢

我这边测了，用原生没有复现这问题

**Comment by wanghui9309** [comment]
> 用微信原生试一试呢

但是有个疑惑，原生测试没问题，按理来说使用Taro历史版本进行测试也不应该出现问题才对；当然测试微信版本都是 8.0.51 微信小程序基础库版本 3.5.8

**Comment by Luxianshen** [comment]
> > > > > webviewScriptError
> > > > 
> > > > 
> > > > 和机型无关系 安卓微信版本为8.0.51 就不行
> > > 
> > > 
> > > 现在问题关键不是这个报错，是导致编译后微信小程序map地图事件无回调才是关键
> > 
> > 
> > 我也测出来是onRegionChange没有触发 但是我也发现了 安卓微信版本8.0.50 是可以的 iOS则不受影响
> 
> 微信官方现在答复是原生测没问题，让Taro这边修改

我试了花小猪 我就觉得是Taro的问题了

**Comment by Luxianshen** [comment]
> > 用微信原生试一试呢
> 
> 但是有个疑惑，原生测试没问题，按理来说使用Taro历史版本进行测试也不应该出现问题才对；当然测试微信版本都是 8.0.51 微信小程序基础库版本 3.5.8

微信地图最近搞了大改动 昨天给我发邮件了

**Comment by wanghui9309** [comment]
> > > 用微信原生试一试呢
> > 
> > 
> > 但是有个疑惑，原生测试没问题，按理来说使用Taro历史版本进行测试也不应该出现问题才对；当然测试微信版本都是 8.0.51 微信小程序基础库版本 3.5.8
> 
> 微信地图最近搞了大改动 昨天给我发邮件了

现在只能期望Taro这边的问题定位了，目前微信官方应该不会做修复；毕竟原生代码运行确实没有报错，且map事件回调正常😄

**Comment by Luxianshen** [comment]
> 用微信原生试一试呢

大佬 我的小程序 也想上墙

**Comment by Luxianshen** [comment]
> 用微信原生试一试呢

微信开发工具是没有问题的 要用安卓真机 微信版本8.0.51

**Comment by wanghui9309** [comment]
> > 用微信原生试一试呢
> 
> 微信开发工具是没有问题的 要用安卓真机 微信版本8.0.51

就是用的已知有问题的安卓设备，用源码片段预览，该问题未出现；片段已经贴在上面了

**Comment by wanghui9309** [comment]
> > webviewScriptError
> 
> 和机型无关系 安卓微信版本为8.0.51 就不行

我们使用华为P30，微信版本8.0.51 该问题就未出现

**Comment by Luxianshen** [comment]
> > > webviewScriptError
> > 
> > 
> > 和机型无关系 安卓微信版本为8.0.51 就不行
> 
> 我们使用华为P30，微信版本8.0.51 该问题就未出现

我是 荣耀50pro 和 1加11 微信版本8.0.50 正常 微信版本8.0.51 出现问题

**Comment by HelloAndyZhang** [comment]
在map 组件上加个setting属性试试

**Comment by Luxianshen** [comment]
> setting

可以的   <Map setting={[]} >.....</Map>

**Comment by Luxianshen** [comment]
可以解决 3.6.35  `<Map setting={[]}>  </Map>`

**Comment by bfrontend** [comment]
> 在map 组件上加个setting属性试试

setting中添加什么进行测试呢 还是都加上

**Comment by Luxianshen** [comment]
> 在map 组件上加个setting属性试试

可以 ` <Map setting={
              {skew: 0,
              rotate: 0,
              showLocation: false,
              showScale: false,
              subKey: '',
              layerStyle: 1,
              enableZoom: true,
              enableScroll: true,
              enableRotate: false,
              showCompass: false,
              enable3D: false,
              enableOverlooking: false,
              enableSatellite: false,
              enableTraffic: false}}>`

**Comment by HelloAndyZhang** [comment]
> > 在map 组件上加个setting属性试试
> 
> setting中添加什么进行测试呢 还是都加上

 setting={{}}  空标签都可以

**Comment by wanghui9309** [comment]
> > > 在map 组件上加个setting属性试试
> > 
> > 
> > setting中添加什么进行测试呢 还是都加上
> 
> setting={{}} 空标签都可以

有试过，地图事件正常返回嘛？

**Comment by HelloAndyZhang** [comment]
> > > > 在map 组件上加个setting属性试试
> > > 
> > > 
> > > setting中添加什么进行测试呢 还是都加上
> > 
> > 
> > setting={{}} 空标签都可以
> 
> 有试过，地图事件正常返回嘛？

可以的。报错导致的回调不执行

**Comment by bfrontend** [comment]
> > > 在map 组件上加个setting属性试试
> > 
> > setting中添加什么进行测试呢 还是都加上
> 
>  setting={{}}  空标签都可以

嗯 可以 确实不报script error了

**Comment by chobitsX** [comment]
> 这是四年前为了兼容 map 组件的 `setting` 不能为空对象而引入的 `workaround code`
> 
> [7d3399b#diff-0360dccea713da1e521f7021b7b0957e36708a492597c651c3e67af74fc116fc](https://github.com/NervJS/taro/commit/7d3399b7e8bb2ce98012fd2c059696fb24a3a87a#diff-0360dccea713da1e521f7021b7b0957e36708a492597c651c3e67af74fc116fc)
> 
> https://github.com/NervJS/taro/blob/7d3399b7e8bb2ce98012fd2c059696fb24a3a87a/packages/taro-weapp/src/components.ts#L31
> 
> 估计是最近微信小程序基础库 v3.5.8 把相关容错逻辑删除了，临时解决办法如下：
> 
> * 添加 `setting` 属性并设置为 `{}`；
> 
> taro 会在下个版本修复此问题~

增加setting={{}}，就可以正常使用了，临时这么修改不会有啥负面影响吧

**Comment by wanghui9309** [comment]
> > > 这是四年前为了兼容 map 组件的 `setting` 不能为空对象而引入的 `workaround code`
> > > [7d3399b#diff-0360dccea713da1e521f7021b7b0957e36708a492597c651c3e67af74fc116fc](https://github.com/NervJS/taro/commit/7d3399b7e8bb2ce98012fd2c059696fb24a3a87a#diff-0360dccea713da1e521f7021b7b0957e36708a492597c651c3e67af74fc116fc)
> > > https://github.com/NervJS/taro/blob/7d3399b7e8bb2ce98012fd2c059696fb24a3a87a/packages/taro-weapp/src/components.ts#L31
> > > 
> > > 估计是最近微信小程序基础库 v3.5.8 把相关容错逻辑删除了，临时解决办法如下：
> > > 
> > > * 添加 `setting` 属性并设置为 `{}`；
> > > 
> > > taro 会在下个版本修复此问题~
> > 
> > 
> > 增加setting={{}}，就可以正常使用了，看Taro记录是四年前从`{}`换成了`[]`，当时也是为了解决微信报错，现在又从`[]`换成`{}`么，哈哈，就怕明天微信一升级会不会{}又不行了，Taro看能从根本上去兼容下不😋
> 
> 我们会验证完存量的基础库版本再发布，不用担心

我这边测试基础库到3.4.6版本都是正常，之后的版本异常

**Comment by koppthe** [comment]
@wanghui9309  用添加 setting 属性的临时解决方法，把基础库 2.x 版本都测了一遍，没发现异常。
你说的「基础库到3.4.6版本都是正常，之后的版本异常」，可以具体一点是哪个版本添加了 setting 属性之后依旧报错吗？

**Comment by wanghui9309** [comment]
> @wanghui9309 用添加 setting 属性的临时解决方法，把基础库 2.x 版本都测了一遍，没发现异常。
> 你说的「基础库到3.4.6版本都是正常，之后的版本异常」，可以具体一点是哪个版本添加了 setting 属性之后依旧报错吗？

添加 setting 后都没有报错；
在不添加setting的情况下，我这边想表达的是出现问题的基础库版本大概范围

**Comment by koppthe** [comment]
#16603
