### ISSUE TITLE
React Native 的最佳实践是什么?

### ISSUE THREAD

**Issue by vlike** [NervJS/taro#1659]
如果app需要输出手机端应用,
所以兼容React Native也是目标之一,
请问一下有什么UI库当前可以使用的?
(就目前我知道的来说,似乎连官方的UI库还都不支持React Native)

**Comment by Pines-Cheng** [comment]
taro-ui 确实还不支持 RN 端。

**Comment by Pines-Cheng** [comment]
有热心群众总结了一篇，还在持续更新中：[使用 Taro 编译小程序 + H5 + React Native 的最佳实践](https://github.com/js-newbee/taro-best-practices/tree/master/multi-platform)

**Comment by Pines-Cheng** [comment]
[Taro 多端开发的正确姿势：打造三端统一的网易严选（小程序、H5、React Native）](https://juejin.im/post/5c6a151f518825625e4ac830)
