### ISSUE TITLE
canvasToTempFilePath is not a function

### ISSUE THREAD

**Issue by lijinke666** [NervJS/taro#166]
你好遇到了一个问题 有点奇怪 是我的操作有问题吗?

![image](https://user-images.githubusercontent.com/21015895/41720128-a775edba-7594-11e8-9572-3ce67944705c.png)

控制台报错
![image](https://user-images.githubusercontent.com/21015895/41720141-b193cede-7594-11e8-8216-f6c5c7f217d9.png)

其他接口都没毛病 我看源码里头 有的嘛 : ) 

还请有空解答下

**Comment by zacksleo** [comment]
看了下代码，有(TS)定义，但还没有实现  😄

**Comment by lijinke666** [comment]
哇！头皮发麻
那能提供 `wx` 原生的句柄吗？
或者大概啥时候 实现呢 ？ 项目需要用到这个接口 : )

**Comment by zacksleo** [comment]
@luckyadam

**Comment by luckyadam** [comment]
下个版本提供，可以暂时用 `wx. canvasToTempFilePath`

**Comment by lijinke666** [comment]
好的，感谢 
暂时用 `wx.xxxxx()` 代替了
