### ISSUE TITLE
Taro.request 在web下设置header对象中'content-type': 'application/json'无效

### ISSUE THREAD

**Issue by hnsxxscyx** [NervJS/taro#1661]
如题目描述，仅‘application/json’无效，不知道什么原因
‘application/json’示例：
![tim 20181224165746](https://user-images.githubusercontent.com/13851292/50395275-d79a8a00-079d-11e9-92f5-a09677381a5e.png)
![tim 20181224165755](https://user-images.githubusercontent.com/13851292/50395276-d79a8a00-079d-11e9-9457-c86ea069ae3c.png)
form-data:
![tim 20181224165923](https://user-images.githubusercontent.com/13851292/50395277-d79a8a00-079d-11e9-9885-7eab558b6baf.png)
![tim 20181224165930](https://user-images.githubusercontent.com/13851292/50395278-d8332080-079d-11e9-89c6-ba4d164beef0.png)
x-www-form-urlencoded：
![tim 20181224170013](https://user-images.githubusercontent.com/13851292/50395279-d8332080-079d-11e9-824e-f7d031c985fa.png)
![tim 20181224170019](https://user-images.githubusercontent.com/13851292/50395280-d8332080-079d-11e9-9aab-e16e043c115f.png)

附上环境：
顺便taro info并不会给出当前项目依赖，不知道是不是我部分依赖未更新的缘故？
![image](https://user-images.githubusercontent.com/13851292/50395434-e9c8f800-079e-11e9-8795-a59d132ede99.png)
![image](https://user-images.githubusercontent.com/13851292/50395458-0d8c3e00-079f-11e9-8683-17980425dbea.png)
![image](https://user-images.githubusercontent.com/13851292/50395462-12e98880-079f-11e9-9489-0b62e2e360d5.png)

感觉各位大大开源的框架，辛苦了

**Comment by Chen-jj** [comment]
@hnsxxscyx 复现不了，先升级你的依赖到 1.2.1 再试试，如果还有问题，贴一下你的 `Taro.request` 代码。

```js
componentDidMount () {
  Taro.request({
    url: 'login/index',
    method: 'POST',
    data: {
      x: 1,
      y: 2
    },
    header: {
      'content-type': 'application/json'
    },
  })
    .catch(err => console.log(err))
}
```

![image](https://user-images.githubusercontent.com/11807297/50419847-fff1b980-086d-11e9-8c10-7276d937920c.png)

**Comment by zmbeex** [comment]
我也出现了，但是没有解决方案

**Comment by jufang** [comment]
去掉mode: 'no-cors' ,
`const res = await Taro.request({
      url: options.url,
      data: options.data,
      header: {
        ...options?.header,
      },
      method: options.method,
    });`
    
    在dev.js 设置代理地址，实现跨域
    `module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  mini: {hot: true},
  h5: {
    esnextModules: ['taro-ui'],
    devServer: {
      host: 'localhost',
      port: 10086,
      proxy: {
        '/api': {
            target: backend,  // 服务端地址
            changeOrigin: true,
            //  secure:false,
        }
      }
    },
  }
}
`
