### ISSUE TITLE
子组件 props 和 state 名称相同，componentWillReceiveProps 传值异常

### ISSUE THREAD

**Issue by youzipi** [NervJS/taro#1662]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

父组件 `state.isOpened` 的 bool 字段 控制子组件是否显示。
初始值 为 false，点击父组件上按钮后，通过 setState 修改为 true。
第一次 正常修改了，后面的每次操作，父组件的 isOpend 更新为 true 后，传到子组件 `componentWillReceiveProps` 的 参数里的 isOpened 都是 false。

将 props 修改为 isShow 后，可正常执行。
```
// 这种情况可以正常传值。
parent.state: isOpend,
child.props: isShow, 
child.state: isOpend
```
TODO
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: MacOS 10.13.6
 - Taro 版本：1.2.0-beta.13 
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 weapp

**补充信息**
看了源码，
https://github.com/NervJS/taro/blob/0383991ac1/packages/taro-weapp/src/lifecycle.js#L22
这里的表现 和 子组件接收到的 props 一致。

可能是这里的问题：
https://github.com/NervJS/taro/blob/0383991ac1/packages/taro-weapp/src/lifecycle.js#L93

**Comment by yuche** [comment]
他还不能和 render 和变量重名，也不能和 this 下的变量重名。这个问题解决起来没那么简单。应该是用 eslint 限制。

**Comment by yuche** [comment]
Duplicate of #1385
