### ISSUE TITLE
taro4最高支持哪个RN版本？

### ISSUE THREAD

**Issue by SidneyLann** [NervJS/taro#16668]
### 这个特性解决了什么问题？
taro最高支持哪个RN版本？

### 这个 API 长什么样？
taro最高支持哪个RN版本？

**Comment by StillAlexLiu** [comment]
这个版本很多问题，taro、expo、react-native等版本匹配，还有各种配置都有问题，弄了好多天都没弄正常运行

**Comment by ShaoGongBra** [comment]
我已经更新到0.75.4了,可以看看我这个框架是怎么处理的 duxapp.cn

**Comment by VeiZhang** [comment]
@ShaoGongBra 大神，请问更新到0.75.4，一直卡在初始化编译Evaluating settings，有什么解决办法吗

**Comment by SidneyLann** [comment]
> @ShaoGongBra 大神，请问更新到0.75.4，一直卡在初始化编译Evaluating settings，有什么解决办法吗

你的文件不是最新的，比如metro.config.js要这样（你最好init个新工程再对比下配置文件）：
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config')
const { getMetroConfig } = require('@tarojs/rn-supporter')

const config = {}

module.exports = (async function (){
  return mergeConfig(getDefaultConfig(__dirname), await getMetroConfig(), config)
})()

**Comment by VeiZhang** [comment]
@SidneyLann 好的，我看看

**Comment by SidneyLann** [comment]
taro支持rn0.75.4+bridgeles+linaria6.x
