### ISSUE TITLE
如何自定义公共 组件路由

### ISSUE THREAD

**Issue by vivilauge** [NervJS/taro#1667]
例： 一个公共的header， 需要在每个页面都引入

如何能让这个公共的header只渲染一次， 所有页面调用，
而不是每个页面都引入一次，重复渲染一次，
路由是如何配置的呢？

**Comment by yuche** [comment]
在小程序中 Taro 用的是内置的路由，按我的理解，以目前这个小程序路由的 API 要做到自定义局部刷新还能应用路由信息，是没有可能性的。
