### ISSUE TITLE
Taro.navigateBack,返回页面，全局dispatch修改redux变量，componentWillReceiveProps方法不执行，导致我没有办重新重载页面数据

### ISSUE THREAD

**Issue by likeDoMine** [NervJS/taro#1671]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
问题发生的原因: 项目中有三个页面会使用同一个变量，在任何一个页面修改，希望其他两个页面的数据被同步， 并且可以重新刷新页面的查询数据，此时，我采用的方式是用dva去dispatch处理数据，本想通过Taro.navigateBack返回数据，发现页面任何一个钩子函数都不会执行，包括render也不会重新刷新（按理说props已经改变，需要重新render），导致页面完全不会重新设置数据，目前yuche给出的解决方案：采用getCurrentPages的方式，但在h5中存在页面可刷新，倒是页面栈数据丢失。
**复现步骤**
[复现问题的步骤]
1. 多页面采用全局redux，state数据
2. 采用dva，触发dispatcher的方式修改state
3. 全局state注入到每个页面中，props改变，我希望在componentWillReceiveProps得到改变值，重新请求数据列表，props改变，希望可以render重新拉取数据
4.  每个页面的返回采用Taro.navigateBack的返回方式

[或者可以直接贴源代码，能贴文字就不要截图]

`
   Taro.navigateBack();
//全局数据对象
       this.props.dispatch({
                "type":'hotellist/setHotelKeyword',
                'payload':{hotelKeyword:''}
            });

//主页面判断不同查询数据列表
  componentWillReceiveProps(nextProps){
       if(nextProps.hotellist.pageNum === 1&&this.state.scrollTop){
           this.setState({
               'scrollTop': 0
           })
       }
     //根据props的值改变，做判断
        if(nextProps.hotellist.hotelKeyword !== this.props.hotellist.hotelKeyword){
            this.getHotelList(1);
        }
    }
render(){
   //需要渲染
   let {hotelKeyword } =  this.props.hotellist
}
`
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
全局state注入到每个页面中，props改变，我希望在componentWillReceiveProps得到改变值，重新请求数据列表，props改变，希望可以render重新拉取数据


**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。



 - 操作系统: [e.g. Windows 10]： window 7
 - Taro 版本 [e.g. v.0.0.64]：  Taro v1.2.0-beta.15
 - Node.js 版本 [e.g. v9.0.0]  v8.11.4
 - 报错平台 [h5, weapp] h5期望

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by hugetiny** [comment]
同样遇到这个问题

**Comment by tourze** [comment]
1.2.4中依然存在这个问题

**Comment by hugetiny** [comment]
是啊



发自我的小米手机
在 tourze <notifications@github.com>，2019年1月8日 下午11:18写道：

1.2.4中依然存在这个问题

**Comment by treesea2014** [comment]
我也有类似的问题   目前先在 需要的页面里   let {xxx}=this.context.store.getState()

**Comment by Littly** [comment]
之前版本`redirectTo` api 确实会导致这个问题，已经修复。最新版应该没有这个问题了，更新一下看看。

**Comment by shengbowen** [comment]
这个问题依然存在啊，redux数据更新，当前页面更新了，但是页面返回到上一个页面后，上一个页面没有更新

**Comment by rockliuxn** [comment]
这个问题我在taro 3.2.10 也遇到了， 当前页面更新了 redux 的state，Taro.navigateBack 返回到上一页后，页面数据并没有更新，render 方法没有执行，难道只能在 componentDidShow 里面重新刷新数据吗？
