### ISSUE TITLE
安卓系统makePhoneCall没有确认电话号码弹窗

### ISSUE THREAD

**Issue by hzXia** [NervJS/taro#16724]
### 相关平台
微信小程序

**小程序基础库: ≥2.33.0**
**使用框架: React**

### 复现步骤
<Text
                                onClick={() => {
                                    Taro.makePhoneCall({
                                        phoneNumber: phone
                                    });
                                }}
                            >
                                {phone}
                            </Text>

### 期望结果
安卓和ios都有确认电话号码弹窗

### 实际结果
安卓没有弹窗，ios有

### 环境信息
```
👽 Taro v3.6.10 
Taro CLI v3.6.10 environment info:
```

**Comment by TheKonka** [comment]
这个原生小程序应该也是同样的效果，是安卓和ios系统的区别
