### ISSUE TITLE
Taro sass样式变量不能时时更新

### ISSUE THREAD

**Issue by FaureWu** [NervJS/taro#1673]
**问题描述**
提取sass共用变量到一个独立的文件中，然后在组件样式文件中引入变量使用，当仅修改sass变量时不会重新编译关联的组件，无法时时更新

**复现步骤**
1. git clone https://github.com/FaureWu/taro-scss-variable-issue
2. yarn && yarn dev:weapp运行代码，预览效果，此时为黄色背景
3. 修改src/variable.scss变量$background-color: red;保存，界面自动刷新，依旧为黄色背景
4. 需修改对应组件js或者scss样式，才能生效

**期望行为**
修改样式外部文件样式变量，相关联的组件时时更新

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Mac]
 - Taro 版本 [1.2.1]
 - Node.js 版本 [v8.11.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
明白，现在是对 sass 中 import 的样式文件没有监听改动
