### ISSUE TITLE
新版本 H5下的下面导航栏是不是不会变色的？

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1674]
新版本 H5下的下面导航栏是不是不会变色的？

**Comment by xingwen93** [comment]
Taro v1.2.1


  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by luckyadam** [comment]
#1664

**Comment by luckyadam** [comment]
已修复
