### ISSUE TITLE
swiper circular

### ISSUE THREAD

**Issue by LZY86** [NervJS/taro#1675]
**问题描述**
swiper无法实现无限轮播，轮播到最后一个item就停止了

**复现步骤**
[复现问题的步骤]
1. 挂载之后，轮播到最后一个swiperItem之后，就终止了，onChange事件也不再触发了。
2.有时候，自动轮播会失效，但是刷新之后就可以了。
3.swiper组件(SwiperItem、Swiper、以及里面的Image)里面onClick，绑定不成功。

[或者可以直接贴源代码，能贴文字就不要截图]

import { Component } from '@tarojs/taro'
import { Swiper, SwiperItem, Image, View } from '@tarojs/components'
import './UDSwiper.scss'
import { getGlobalData, setGlobalData } from "../../utils/global_data";
import { postIndexPageByBanner } from "../../utils/request";

export default class UDSwiper extends Component {

    state = {
        list: []
    };

    componentWillMount() {
        let udSwiperList = getGlobalData('udSwiperList');
        if (udSwiperList instanceof Array && udSwiperList.length > 0) {
            this.start(udSwiperList)
        } else {
            postIndexPageByBanner({ sourceBanner: 'ST' }, resolve => {
                if (!resolve.data instanceof Array) return
                this.start(resolve.data);
            });
        }
    }

    componentDidMount() {

    }

    start(udSwiperList) {
        setGlobalData('udSwiperList', udSwiperList);
        this.setState({
            list: udSwiperList
        });
    }

    onClick = (e) => {
        let href = e.target.parentNode.dataset.href;
        if (href) {
            window.location.href = href
        }
    };

    render() {
        let list = this.state.list.map(item => {
            return (
                <SwiperItem>
                    <Image
                        className='swiper__image'
                        src={item.img}
                        data-href={item.url}
                    />
                </SwiperItem>
            )
        });

        return (
            <View className='UDSwiper' onClick={this.onClick}>
                <Swiper
                    className={this.props.claz}
                    indicatorColor='rgba(255, 255, 255, .5)'
                    indicatorActiveColor='#fff'
                    interval={1000}
                    autoplay
                    circular
                    indicatorDots
                >
                    {list}
                </Swiper>
            </View>
        )
    }
}

**期望行为**

1、实现循坏轮播
2、swiper 的 onClick事件

**报错信息**

没有报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
我尝试复现一下

**Comment by maskwang** [comment]
Mark  我这面也遇到同样的困扰好久了。
期待尽快解决~~~~~~~~~~~

**Comment by maskwang** [comment]
最新版的h5， 还是有这个问题

**Comment by jinjinjin0731** [comment]
@LZY86  @AloneWeb  @maskwang  抱歉，才回复。此问题已经修复。你们可以再次尝试一下

**Comment by smileying** [comment]
这个问题对版本有要求吗？1.2.4版本也遇到了这个问题，H5页面停在最后一个不能无限轮播

**Comment by jinjinjin0731** [comment]
@smileying  需要更新到最新版本，如果有新还有问题，请新开 issue ，勿在旧的当中回复
