### ISSUE TITLE
小程序转taro的过程中的一些问题描述

### ISSUE THREAD

**Issue by aeron11** [NervJS/taro#1676]
**小程序转taro的过程中的一些问题汇总如下：**

1、有的base64的图片转换是会把原有串转错成另一个，导致不能访问；
2、转换后的点击路由出错：http://127.0.0.1:10086/#/pages/index/pages/path/yourpage，正确的地址应该是：http://127.0.0.1:10086/#/pages/path/yourpage
3、样式会混乱，估计是多页面样式重名所致
4、原生的一些方法不支持
5、在创建节点时报错，需要修改如下文件的一行代码加个boolean型判断：nervjs/dist/index.js ，932行：if (nextVnode && nextVnode !== null)，否则对false的变量再附加属性而报错。
6、对于小程序中的自定义组件，使用triggerEvent时，转换成taro后找不到该方法；

希望能给予相关支持，谢谢

**Comment by yuche** [comment]
第五种情况你能做一个具体的复现代码吗

**Comment by yuche** [comment]
升级 nervjs 可以解决
