### ISSUE TITLE
Input标签在h5版本中iOS和安卓上面显示不一样

### ISSUE THREAD

**Issue by XiaoSongWolf** [NervJS/taro#1678]
Input标签的disabled属性设置为true的情况下，小程序上面不管安卓还是iOS字体颜色都可以设置，
在h5版本中，安卓上面可以设置字体颜色；iOS上面字体直接被置灰，设置字体颜色无效果。

期望：
 iOS上面可以像安卓一样可以设置字体颜色

代码：
<Input className='party-formMsg'  disabled={true} />

开发环境：
Taro v1.2.0-beta.7

**Comment by XiaoSongWolf** [comment]
<Input className='party-formMsg' disabled={true} />
很简单的用法，h5版本在iOS上面一直是置灰状态

![image](https://user-images.githubusercontent.com/19815977/50415350-7c2bd300-0855-11e9-9685-ab1d787577c4.png)

**Comment by XiaoSongWolf** [comment]
<Input className='party-formMsg' disabled={true} />

**Comment by XiaoSongWolf** [comment]
为什么代码不显示呢？

**Comment by XiaoSongWolf** [comment]
![image](https://user-images.githubusercontent.com/19815977/50415477-1ee45180-0856-11e9-8dcd-a0dae13886bd.png)
用图片展示代码吧

**Comment by jinjinjin0731** [comment]
你这个属于 ios 上的样式兼容问题。，具体你谷歌或者度娘搜一下:  ios input disabled 文字颜色，会有很多答案
