### ISSUE TITLE
官方taro-redux-sample，编译成小程序在微信开发者工具打开报错。

### ISSUE THREAD

**Issue by xukg** [NervJS/taro#168]
官方taro-redux-sample，编译成小程序在微信开发者工具打开报错。
![wx20180622-110132](https://user-images.githubusercontent.com/1118374/41755813-ca42bd92-760b-11e8-8b46-b774a64131e0.png)

**Comment by fantasticsoul** [comment]
同样的问题，一模一样的问题，哎，伤心中

**Comment by xukg** [comment]
已经解决，需要把下面三项关闭！
![wx20180622-154450](https://user-images.githubusercontent.com/1118374/41764310-4b6bf894-7633-11e8-9046-0516b26e28b4.png)
