### ISSUE TITLE
h5中安卓  加载首页过程中 一开始未渲染好样式后就显示出来，然后才渲染好了样式排好版。导致一开始排版是乱的

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1680]
h5中安卓  加载首页过程中 一开始未渲染好样式后就显示出来，然后才渲染好了样式排好版。导致一开始排版是乱的 

Taro v1.2.1

  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by Littly** [comment]
试下配置 h5.enableExtract = false

**Comment by xingwen93** [comment]
![image](https://user-images.githubusercontent.com/16276222/50435279-83b5af80-091b-11e9-9a75-dcafa72a86ce.png)

**Comment by xingwen93** [comment]
enableExtract 加了后好像没有作用

**Comment by xingwen93** [comment]
加了后 dev:h5 依旧会 一开始未渲染好样式后就显示出来，然后才渲染好了样式排好版。导致一开始排版是乱的

**Comment by Littly** [comment]
build模式下是不会有这个问题的 dev下忽略即可

如果dev下依然不想见到这个问题，把enableExtract和enableSourceMap都设置为false就好
https://github.com/webpack-contrib/style-loader/issues/107#issuecomment-347043971
