### ISSUE TITLE
区分平台下 require() 引入文件 被执行到

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1681]
const WxParse = (Taro.getEnv() === Taro.ENV_TYPE.WEAPP) ?require('../../components/wxParse/wxParse') : {};  

但是在H5下， require() 被执行，导致 H5下无法解析：
Module not found: Can't resolve 'html2json' in '/Users/lanhui_mac/SouYunTool_local/.temp/components/wxParse'

Taro v1.2.1

  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by yuche** [comment]
用 process.env:
https://nervjs.github.io/taro/docs/envs.html#processenvtaro-env
