### ISSUE TITLE
折叠面板 展开收起动画性能问题什么时候改改？

### ISSUE THREAD

**Issue by scl930227** [NervJS/taro#16822]
### 这个特性解决了什么问题？
实际小程序使用时展开卡顿，多个折叠面板上下排列时更加明显

### 这个 API 长什么样？
优化卡顿问题！ 动画效果使用的是height变更，直接操作 height 属性来实现折叠面板的展开和收起动画，由于高度频繁变化，可能会引起重绘和重排，影响性能；
实在改不了或者觉得设计的很好,不能使用transform: scaleY();transform-origin: top这类方式实现的话！
能不能加个属性开关允许用户自行选择是否开启？

**Comment by TheKonka** [comment]
发错地方了吧，你这个应该去找具体的 ui 库

**Comment by scl930227** [comment]
贴错地方了
