### ISSUE TITLE
如何配置vite的插件

### ISSUE THREAD

**Issue by liuseen-l** [NervJS/taro#16821]
### 这个特性解决了什么问题？
配置vite插件

### 这个 API 长什么样？
可以配置vite的插件

**Comment by jia-wink** [comment]
多看看文档，有写的：
https://docs.taro.zone/docs/next/config-detail#compilerviteplugins

**Comment by liuseen-l** [comment]
> 多看看文档，有写的： https://docs.taro.zone/docs/next/config-detail#compilerviteplugins
没看见我关闭issue了吗

**Comment by jia-wink** [comment]
> > 多看看文档，有写的： https://docs.taro.zone/docs/next/config-detail#compilerviteplugins
> 
> 没看见我关闭issue了吗

你真是搞笑，你看看我回复的时间和你关闭的时间呢？
咋的给你解答了还要嘴硬一下是吧
