### ISSUE TITLE
eslint 问题

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#1685]
![image](https://user-images.githubusercontent.com/25219300/50421977-1b65c000-0880-11e9-9af7-0d2b48717dca.png)
![image](https://user-images.githubusercontent.com/25219300/50421979-291b4580-0880-11e9-8880-8fb3d0548445.png)

代码中这样子不算应用 qrCodeInfo 吗？

**Comment by yuche** [comment]
这样是检测不到的，这条 eslint 插件也不归我们管，你觉得不对可以选择关掉，或者你可以向 https://github.com/yannickcr/eslint-plugin-react/ 提。
