### ISSUE TITLE
DraggableSheet 组件缺少  worklet:onsizeupdate 方法

### ISSUE THREAD

**Issue by songwenhui** [NervJS/taro#16861]
### 这个特性解决了什么问题？
DraggableSheet 组件滚动回调，可以联动其他组件实现一些逻辑或动画

### 这个 API 长什么样？
新增属性  onsizeupdate ，回调返回 pixels、size，API 向微信小程序靠拢

**Comment by songwenhui** [comment]
涉及到 worklet: 的事件都不支持绑定

通过 @tarojs/plugin-inject 插件添加了配置，编译后的 Dom 已经有了该属性，但是回调依然不执行
`DraggableSheet: {
       'worklet:onsizeupdate': '',
},`

**Comment by tutuxxx** [comment]
4.0.8起支持，https://docs.taro.zone/docs/skyline

**Comment by songwenhui** [comment]
4.0.8 版本加上 compileMode 属性，skyline 页面打包后是白页，没有任何节点，干掉 compileMode 页面展示正常
<View compileMode>
      <>
        <Map
          className="bg"
          latitude={23.099994}
          longitude={113.32452}
          onError={() => {}}
        />

        <DraggableSheet
          className="sheet"
          style={{ height: `${sheetHeight}px` }}
          initialChildSize={0.6}
          minChildSize={0.2}
          maxChildSize={1}
          snap
          snapSizes={[0.6]}
          onSizeUpdateWorklet="onSizeUpdate"
        >
          <ScrollView
            type="custom"
            associative-container="draggable-sheet"
            bounces
            className="scrollable"
            scrollY
            showScrollbar={false}
          >
          </ScrollView>
        </DraggableSheet>
      </>
    </View>

**Comment by songwenhui** [comment]
> 4.0.8起支持，https://docs.taro.zone/docs/skyline

麻烦看一下

**Comment by UzumakiHan** [comment]
一样的问题。。。。。
