### ISSUE TITLE
支付宝小程序问题汇总

### ISSUE THREAD

**Issue by SzHeJason** [NervJS/taro#1686]
**问题描述**
这并不是 Taro 的问题，而是支付宝没提供这种功能，限定某个组件查询节点 类似于 微信小程序的 in 语法 或者说是 react 的 this.ref 的方式，这对于组件化是一个很重要的功能，缺少这个功能将导致 组件中使用节点查询的结果 永远都是第一个组件的值

**重现步骤**
```js
// page
export default class pageDemo extends Taro.Component {
  componentDidMount () {
    Taro.createSelectorQuery()
      .selectAll('.child')
      .boundingClientRect()
      .exec(res => {
        console.log(res)
      })
  }
  render () {
    return (
      <View>
        <Child />
        <Child />
      </View>
    )
  }
}


```
```js
// child
export default class pageDemo extends Taro.Component {
  componentDidMount () {
    Taro.createSelectorQuery()
      .in(this.$scope)
      .select('.child')
      .boundingClientRect()
      .exec(res => {
        console.log(res)
      })
  }
  render () {
    return <View className='child'>1111</View>
  }
}

```

**期望行为**
希望能提供类似的方法 和 临时解决方案

**系统信息**
![image](https://user-images.githubusercontent.com/20609396/50423138-5a017780-088c-11e9-8123-d75d06b7aaca.png)

**Comment by SzHeJason** [comment]
还有一个问题 Picker 组件传入样式 没有效果
```
<picker style="margin-left:20px"></picker>
```
同理 传入class 也没有效果

**Comment by jimczj** [comment]
支付宝 input 组件的 bindinput 事件 无法 return 字符串更改内容
![image](https://user-images.githubusercontent.com/13499146/50510928-83a5e300-0ac6-11e9-9549-97bfd852874e.png)

**Comment by koppthe** [comment]
组件：**Picker**
问题：支付宝的 Picker 组件内嵌自定义组件之后，Picker 无法触发，例如：
```html
<picker range="{{selector}}" value="{{selectorValue}}" onChange="handleChange">
  <at-button>点击</at-button>
</picker>
```

**Comment by koppthe** [comment]
组件：**Swiper**
问题：SwiperItem 里面的图片，如果设置了 mode='widthFix'，会导致 Swiper 在初次渲染时获取不到高度而不显示，但如果 Swiper 的属性有变更，会重新渲染成功。

```html
<swiper>
  <swiper-item>
    <image mode="widthFix" src="...."/>
  </swiper-item>
</swiper>
```

**Comment by Chen-jj** [comment]
@jimczj 
![image](https://user-images.githubusercontent.com/11807297/50814722-938ab600-1355-11e9-9a55-bc2372202119.png)

**Comment by SzHeJason** [comment]
Swipe 可否提供 onAnimationFinish 生命周期？

**Comment by Chen-jj** [comment]
@SzHeJason 支付宝最新尝鲜版本已经实现了 query.in()

![image](https://user-images.githubusercontent.com/11807297/55456688-4f3c4880-561a-11e9-860a-541e74a281e3.png)

**Comment by chaojiangcn** [comment]
问题：有些页面提示系统错误，请稍后重试
描述：少数页面进入会出现这样的情况，控制台也不报错
![image](https://user-images.githubusercontent.com/29300205/60696987-9d632f80-9f1a-11e9-815c-f60128cfb6c8.png)

**Comment by Chen-jj** [comment]
@chaojiangcn 自行删减代码先大概定位，这样提问没有意义。

**Comment by chaojiangcn** [comment]
> @chaojiangcn 自行删减代码先大概定位，这样提问没有意义。

行，谢谢
