### ISSUE TITLE
如何打包不同不同的小程序到不同的文件夹？

### ISSUE THREAD

**Issue by Tmac-1** [NervJS/taro#1690]
现在打包微信小程序是进入dist目录。再打包百度小程序也会进入dist目录，就会覆盖之前的微信小程序。怎么才能打包进入不同的目录。

**Comment by yinlsea** [comment]
我这么干
![image](https://user-images.githubusercontent.com/21033870/50906517-3f202d00-1460-11e9-82d9-4543b402d645.png)

**Comment by hejinguo** [comment]
@yinlsea  请问你这里的TARO_BUILD_TYPE是自定义的吗？在哪定义呢？

**Comment by Garfield550** [comment]
Supported since 1.3.0-beta-5, Dup #1066
