### ISSUE TITLE
Taro H5 （chooseMedia、chooseVideo）在iOS没有上传成功/失败的回调！！！

### ISSUE THREAD

**Issue by Winner-Wei** [NervJS/taro#16929]
### 相关平台
H5

**浏览器版本: Chrome 已是最新版本 版本 131.0.6778.86（正式版本） (x86_64)**
**使用框架: Vue 3**

### 复现步骤
Taro.chooseMedia({
    count: multiple.value ? maximum.value - fileListData.value.length : 1,
    mediaType: ['image','video'],
    sourceType: ['album', 'camera'],
    camera: 'back',
    success: (res) => {
     console.log(res)
    }
    fail: () => {},
  })
就这个代码，在ios不行，安卓可以

### 期望结果
taro H5 在ios上能够和安卓保持一致，能够上传视频！！！

### 实际结果
ios在上传视频时没有成功和失败的回调，什么信息都没有返回，浏览器可以，安卓也可以！！！

### 环境信息
```
 Taro v3.6.35


  Taro CLI 3.6.35 environment info:
    System:
      OS: macOS 15.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 18.17.0 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.35 => 3.6.35 
      @tarojs/components: 3.6.35 => 3.6.35 
      @tarojs/helper: 3.6.35 => 3.6.35 
      @tarojs/plugin-framework-vue3: 3.6.35 => 3.6.35 
      @tarojs/plugin-html: 3.6.35 => 3.6.35 
      @tarojs/plugin-platform-h5: 3.6.35 => 3.6.35 
      @tarojs/runtime: 3.6.35 => 3.6.35 
      @tarojs/shared: 3.6.35 => 3.6.35 
      @tarojs/taro: 3.6.35 => 3.6.35 
      @tarojs/taro-loader: 3.6.35 => 3.6.35 
      @tarojs/webpack5-runner: 3.6.35 => 3.6.35 
      babel-preset-taro: 3.6.35 => 3.6.35 
      eslint-config-taro: 3.6.35 => 3.6.35 
    npmGlobalPackages:
      typescript: 4.4.3
```

---
### 补充信息
希望看到尽快联系我，升级taro这是第三次了， 还是没成功，加急！！！

**Comment by yifengyoujian** [comment]
IOS公众号没有提供这个接口, 可以用input原生方法实现

**Comment by wangyuan0108** [comment]
这个api在h5的情况下是有兼容问题，ios可以，安卓调不起系统相册

**Comment by wangyuan0108** [comment]
但是taro文档上说的这个api支持h5，但是貌似确实有兼容问题，希望能统一能调起系统相册，我是ios能调起相册，而安卓系统不行

**Comment by CnPeng** [comment]
麻烦问下解决了没有？我也碰到这个问题了。
