### ISSUE TITLE
Picker组件mode="multiSelector" 在支付宝小程序中不显示

### ISSUE THREAD

**Issue by kkerwin** [NervJS/taro#1692]
**问题描述**
Picker组件mode="multiSelector" 在支付宝小程序中不显示，支付宝开发工具中是空的，手机上是选择时间

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Picker } from '@tarojs/components'
import './index.less'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  state = {
    diqu:[
      [{label:"北京",value:"1"},{label:"天津",value:"2"},],
      [{label:"北京市",value:"1-1"},],
      [{label:"东城区",value:"1-1-1"},{label:"西城区",value:"1-1-2"},],
    ],
  }

  render () {
    return (
      <View>
        <Picker range={this.state.diqu} mode="multiSelector" rangeKey='label'>
          <View>
            选择地区
          </View>
        </Picker>
      </View>
    )
  }
}



```

**期望行为**
和微信小程序中的一样

**报错信息**
微信中：
![tim 20181226111524](https://user-images.githubusercontent.com/7856025/50430658-295b2580-0900-11e9-8428-353a631e626d.png)
支付宝开发工具：
![tim 20181226111551](https://user-images.githubusercontent.com/7856025/50430666-32e48d80-0900-11e9-8f5f-64028d0881c5.png)
手机（支付宝中）：
![img_1593](https://user-images.githubusercontent.com/7856025/50430677-42fc6d00-0900-11e9-9d9c-edb92af0a001.PNG)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [ Windows 7]
 - Taro 版本 [1.2.0]
 - Node.js 版本 [v10.14.2]
 - 报错平台 [alipay]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
支付宝小程序的文档中貌似没有配置 picker 为多列的选项

**Comment by joker-li** [comment]
请问下 楼主后来怎么解决掉啊！

**Comment by chaojiangcn** [comment]
谁用解决办法没

**Comment by DuanShuaiShuai** [comment]
主要是样式为啥没有生效
