### ISSUE TITLE
template无法被解析

### ISSUE THREAD

**Issue by enjoy-myLife** [NervJS/taro#16935]
### 相关平台
飞书小程序

### 复现仓库
[git@github.com:enjoy-myLife/taro-feishu-demo.git](git@github.com:enjoy-myLife/taro-feishu-demo.git)

**使用框架: Vue 3**

### 复现步骤
1.  yarn global add @tarojs/cli
2.  taro init myApp
3.  yarn add @tarojs/plugin-platform-lark
4.   配置插件, plugins: [
    '@tarojs/plugin-platform-lark'
  ]
5. 新增project.lark.json，内容如下：
{
  "miniprogramRoot": "./",
  "projectname": "taro-lark",
  "description": "taro-lark",
  "appid": "touristappid",
  "setting": {
    "urlCheck": true,
    "es6": true,
    "postcss": false,
    "minified": false
  },
  "compileType": "miniprogram"
}
6. package.json 中添加打包命令：
    "scripts": {
    "build:lark": "taro build --type lark",
    "dev:lark": "npm run build:lark -- --watch"
  }
7.yarn dev:lark

### 期望结果
能够回显template下的文本

### 实际结果
在page的index.vue中，template下无论写什么都不被渲染，调试器里看到最终生成的只有<page id="app"></page>,但是setup下的console.log又能够正常打印

### 环境信息
```
Taro v4.0.7


  Taro CLI 4.0.7 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.16.0 - E:\tools\nodejs\node.EXE
      Yarn: 1.22.22 - E:\tools\nodejs\node_global\yarn.CMD   
      npm: 10.8.1 - E:\tools\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 4.0.7 => 4.0.7 
      @tarojs/components: 4.0.7 => 4.0.7 
      @tarojs/helper: 4.0.7 => 4.0.7 
      @tarojs/plugin-framework-vue3: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-alipay: 4.0.7 => 4.0.7         
      @tarojs/plugin-platform-h5: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-harmony-hybrid: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-jd: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-qq: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-swan: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-tt: 4.0.7 => 4.0.7 
      @tarojs/plugin-platform-weapp: 4.0.7 => 4.0.7 
      @tarojs/runtime: 4.0.7 => 4.0.7 
      @tarojs/shared: 4.0.7 => 4.0.7 
      @tarojs/taro: 4.0.7 => 4.0.7 
      @tarojs/vite-runner: 4.0.7 => 4.0.7 
      babel-preset-taro: 4.0.7 => 4.0.7
      eslint-config-taro: 4.0.7 => 4.0.7

```

**Comment by enjoy-myLife** [comment]
调试器里看到的只有id为app的page标签

**Comment by enjoy-myLife** [comment]
我找到原因了，是因为taro build --type lark

**Comment by chieway** [comment]
> 我找到原因了，是因为taro build --type lark

我现在也遇到这个问题，请问是怎么解决的啊
