### ISSUE TITLE
微信小程序：使用小程序回退键后 如果input的value内有值，会和placeholder的文字重叠

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1694]
Taro CLI 1.2.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.1 => 1.2.1 
      @tarojs/cli: 1.2.1 => 1.2.1 
      @tarojs/components: 1.2.1 => 1.2.1 
      @tarojs/plugin-babel: 1.2.1 => 1.2.1 
      @tarojs/plugin-csso: 1.2.1 => 1.2.1 
      @tarojs/plugin-sass: 1.2.1 => 1.2.1 
      @tarojs/plugin-uglifyjs: 1.2.1 => 1.2.1 
      @tarojs/redux: 1.2.1 => 1.2.1 
      @tarojs/redux-h5: 1.2.1 => 1.2.1 
      @tarojs/rn-runner: 1.2.1 => 1.2.1 
      @tarojs/router: 1.2.1 => 1.2.1 
      @tarojs/taro: 1.2.1 => 1.2.1 
      @tarojs/taro-alipay: 1.2.1 => 1.2.1 
      @tarojs/taro-h5: 1.2.1 => 1.2.1 
      @tarojs/taro-swan: 1.2.1 => 1.2.1 
      @tarojs/taro-weapp: 1.2.1 => 1.2.1 
      @tarojs/webpack-runner: 1.2.1 => 1.2.1 
      eslint-config-taro: 1.2.1 => 1.2.1 
      eslint-plugin-taro: 1.2.1 => 1.2.1 
补充：taro-ui:1.5.3
建议吧taro-ui也放在info里

**Comment by luckyadam** [comment]
这个应该是微信小程序的问题，你试试原生会不会有问题

**Comment by hugetiny** [comment]
H5 没有的

**Comment by luckyadam** [comment]
小程序和 H5 不一样，你要试一下原生小程序
