### ISSUE TITLE
鸿蒙系统微信小程序中input组件快速输入时闪烁

### ISSUE THREAD

**Issue by hzXia** [NervJS/taro#16978]
### 相关平台
微信小程序

**小程序基础库: 2.33.0以上**
**使用框架: React**

### 复现步骤
鸿蒙系统，微信小程序，Input输入框快速输入（如121212一直点），输入内容会闪烁

### 期望结果
正常输入

### 实际结果
输入内容一直闪烁

### 环境信息
```
👽 Taro v3.6.10

Taro CLI 3.6.10 environment info:
    System:
      OS: macOS 13.5
```

**Comment by shinken008** [comment]
这个bug应该提给微信

**Comment by hzXia** [comment]
目前看起来微信已修复
