### ISSUE TITLE
Input 设置了 cursor 属性，但是无效，在 v3.6.34 中

### ISSUE THREAD

**Issue by weiqinke** [NervJS/taro#16980]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/weiqinke/taro-input-cursor.git](https://github.com/weiqinke/taro-input-cursor.git)
**小程序基础库: 2.27.3**
**使用框架: React**

### 复现步骤
随便输入 12345， 数据会被格式化为 1-2-3-4-5。光标移动到 2 后，按下删除键，理想状态光标应该在 3 前面，但是实际光标会移动到 5 后面。

### 期望结果
1-2-3-4-5  光标移动到 2 后面，按下删除键，光标应该在3前面

### 实际结果
实际无论在哪里按下删除键，光标都会移动到最后一位后面，指定了 cursor ，但是无效。

### 环境信息
```
 Taro v3.6.34


  Taro CLI 3.6.34 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - /usr/local/bin/node
      Yarn: 1.22.22 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.34 => 3.6.34
      @tarojs/components: 3.6.34 => 3.6.34
      @tarojs/helper: 3.6.34 => 3.6.34
      @tarojs/plugin-framework-react: 3.6.34 => 3.6.34
      @tarojs/plugin-html: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-alipay: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-h5: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-jd: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-qq: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-swan: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-tt: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-weapp: 3.6.34 => 3.6.34
      @tarojs/react: 3.6.34 => 3.6.34
      @tarojs/runtime: 3.6.34 => 3.6.34
      @tarojs/shared: 3.6.34 => 3.6.34
      @tarojs/taro: 3.6.34 => 3.6.34
      @tarojs/taro-loader: 3.6.34 => 3.6.34
      @tarojs/webpack5-runner: 3.6.34 => 3.6.34
      babel-preset-taro: 3.6.34 => 3.6.34
      eslint-config-taro: 3.6.34 => 3.6.34
      react: ^18.0.0 => 18.3.1
```

---
### 补充信息
想要实现 类似 激活码功能，用 - 分割，但是每次删除中间的一个字符，光标就会错位。指定了 cursor 为 3 ，但是光标还是会移动到最后一位后面。

**Comment by weiqinke** [comment]
此处是精简代码
function Index() {
  const [data, setData] = useState({
    cursor: -1,
    value: "",
  });

  const onInput = (event) => {
    const detail = event.detail;
    const prueValue = detail.value.split("-").join("");
    const value = prueValue.split("").join("-");
    setData({
      value,
      cursor: detail.cursor,
    });
    return value;
  };
  return (
    <View style={{ border: "1px solid #000" }}>
      <Input
        type="text"
        value={data.value}
        cursor={data.cursor}
        onInput={onInput}
      />
    </View>
  );
}

**Comment by weiqinke** [comment]
此处是精简代码
function Index() {
    const [data, setData] = useState({
        cursor: -1,
        value: "",
    });

    const onInput = (event) => {
        const detail = event.detail;
        const prueValue = detail.value.split("-").join("");
        const value = prueValue.split("").join("-");
        setData({
          value,
          cursor: detail.cursor,
        });
        return value;
    };
    return (
      <View style={{ border: "1px solid #000" }}>
        <Input
          type="text"
          value={data.value}
          cursor={data.cursor}
          onInput={onInput}
        />
      </View>
    );
}

**Comment by weiqinke** [comment]
精简代码
function Index() {
    const [data, setData] = useState({
      cursor: -1,
      value: "",
    });
    const onInput = (event) => {
        const detail = event.detail;
        const prueValue = detail.value.split("-").join("");
        const value = prueValue.split("").join("-");
        setData({
          value,
          cursor: detail.cursor,
        });
        return value;
    };
    return (
      <View style={{ border: "1px solid #000" }}>
        <Input
          type="text"
          value={data.value}
          cursor={data.cursor}
          onInput={onInput}
        />
      </View>
    );
}

**Comment by weiqinke** [comment]
const onInput = (event) => {
    const detail = event.detail;
    const prueValue = detail.value.split("-").join("");
    const value = prueValue.split("").join("-");
    setData({
      value,
      cursor: detail.cursor,
    });
    return value;
};
return (
  <View style={{ border: "1px solid #000" }}>
    <Input
      type="text"
      value={data.value}
      cursor={data.cursor}
      onInput={onInput}
    />
  </View>
);

**Comment by weiqinke** [comment]
function Index() {
  const [data, setData] = useState({
    cursor: -1,
    value: "",
  });

  const onInput = (event) => {
    const detail = event.detail;
    const prueValue = detail.value.split("-").join("");
    const value = prueValue.split("").join("-");
    setData({
      value,
      cursor: detail.cursor,
    });
    return value;
  };
  return (
    <View style={{ border: "1px solid #000" }}>
      <Input
        type="text"
        value={data.value}
        cursor={data.cursor}
        onInput={onInput}
      />
    </View>
  );
}

**Comment by weiqinke** [comment]
function Index() {
    const [data, setData] = useState({
        cursor: -1,
        value: "",
    });

    const onInput = (event) => {
        const detail = event.detail;
        const prueValue = detail.value.split("-").join("");
        const value = prueValue.split("").join("-");
        setData({
            value,
            cursor: detail.cursor,
        });
        return value;
    };
    return (
        <View style={{ border: "1px solid #000" }}>
            <Input
                type="text"
                value={data.value}
                cursor={data.cursor}
                onInput={onInput}
            />
        </View>
    );
}

**Comment by hanjin001** [comment]
这个估计是微信小程序本身的坑。可以在微信交流社区搜索看看。

**Comment by weiqinke** [comment]
> 估计是微信小程序本身的坑。可以在微信交流社区搜索看看。

用 微信小程序原生代码 写了同样了的逻辑，cursor就没问题。看起来就是 Taro 把 cursor 属性丢弃了

**Comment by hanjin001** [comment]
那可以使用 nativeProps 透传 cursor 试试。

```tsx
<Input 
  nativeProps={{
   cursor: 10,
  }} />
```
Input 组件
[Input](https://github.com/NervJS/taro/tree/main/packages/taro-components/src/components/input)
源码 nativeProps 位置
[nativeProps](https://github.com/NervJS/taro/blob/main/packages/taro-components/src/components/input/input.tsx#L276)


或者直接在模板里使用微信小程序原生的 input 组件，不使用 `@tarojs/components` 的 `Input` 组件试试。

**Comment by hanjin001** [comment]
后续已经解决了，看你关闭了issue？用的原生Input吗，还是 nativeProps 呢。

**Comment by shengyangchao** [comment]
> 那可以使用 nativeProps 透传 cursor 试试。
> 
> <Input 
>   nativeProps={{
>    cursor: 10,
>   }} />
> Input 组件 [Input](https://github.com/NervJS/taro/tree/main/packages/taro-components/src/components/input) 源码 nativeProps 位置 [nativeProps](https://github.com/NervJS/taro/blob/main/packages/taro-components/src/components/input/input.tsx#L276)
> 
> 或者直接在模板里使用微信小程序原生的 input 组件，不使用 `@tarojs/components` 的 `Input` 组件试试。

你好使用了nativeProps不能解决这个问题，使用微信小程序原生的 input 组件的话，我看文档项目再具备多端转换的能力， taro版本4.0.9。请问这个怎么解决呢
`import { View } from '@tarojs/components'
import { Input } from '@tarojs/components'
import { useState, useRef } from 'react'
import './index.scss'

function Index() {
    const [inputValue, setInputValue] = useState('')
    const ref = useRef(null)
    const handleInput = (e) => {
        setInputValue(e.detail.value)
        ref.current = e.detail.cursor
    }
    console.log(ref.current)

    return (
        <View className="container">
            <View className="input-group">
                <Input
                    className="input"
                    type="text"
                    placeholder="请输入内容"
                    onInput={handleInput}
                    value={inputValue}
                    nativeProps={{
                        cursor: ref.current,
                    }}
                />
            </View>
            {inputValue && <View className="result">您输入的内容是：{inputValue}</View>}
        </View>
    )
}

export default Index
`

**Comment by aomnisz** [comment]
> 那可以使用 nativeProps 透传 cursor 试试。
> 
> <Input 
>   nativeProps={{
>    cursor: 10,
>   }} />
> Input 组件 [Input](https://github.com/NervJS/taro/tree/main/packages/taro-components/src/components/input) 源码 nativeProps 位置 [nativeProps](https://github.com/NervJS/taro/blob/main/packages/taro-components/src/components/input/input.tsx#L276)
> 
> 或者直接在模板里使用微信小程序原生的 input 组件，不使用 `@tarojs/components` 的 `Input` 组件试试。

您好，请问原生input组件要怎么调用？nativeProps 我试了似乎没什么作用
