### ISSUE TITLE
 功能怎么扩展

### ISSUE THREAD

**Issue by zhoujianlin8** [NervJS/taro#170]
如何支持支付宝小程序平台 （可以根据weapp修改内置 也可开放配置）
如何支持自定义模板 （模板内容可以在远程）
alias 功能有支持不
taro-cli 可以拆分出taro-croe

**Comment by luckyadam** [comment]
1、支持支付宝小程序还是需要独立开发，需要开发 JSX 转支付宝小程序模板，对应的组件库以及端能力封装，只靠修改配置还是不足以支持的
2、目前还没有自定义模板的功能，如果你有比较通用的模板可以通过提 PR 来进行加入
3、alias 功能还不支持，不过我觉得写完整路径也不是坏事，这样在 VS Code 中可以很快地定位到文件
4、taro-core 可以考虑拆分哦~ 这样也挺便于扩展的

**Comment by singone** [comment]
建议拆分taro-core， 方便扩展
