### ISSUE TITLE
Typescript语法错误并不会导致编译失败，这个是正常的么？

### ISSUE THREAD

**Issue by xiaodid** [NervJS/taro#1700]
**问题描述**
在ts或tsx文件中的语法错误，并不会导致```npm run build:weapp```或者```npm run dev:weapp```编译失败。

**复现步骤**
[复现问题的步骤]
1. ```taro init myProject```
2. 选择typescript
3. 选择Less
4. 选择默认模版
5. 等待项目依赖安装完
6. 进入项目，修改app.tsx, 如：
``` ts
  componentDidMount () {
    ddddd
  }
```
7. run ```npm run build:weapp``` or ```npm run build:h5```

**期望行为**
```npm run dev:weapp```应该指出相应错误，代码会被编译成
``` js
_createClass(t,[{key:"componentDidMount",value:function(){ddddd}}
```
我感觉是taro就这么设计的。

如果这个是正确行为，希望加入语法检查。

**报错信息**

**系统信息**
Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^1.2.0 => 1.2.1
      @tarojs/plugin-babel: ^1.2.0 => 1.2.1
      @tarojs/plugin-csso: ^1.2.0 => 1.2.1
      @tarojs/plugin-less: ^1.2.0 => 1.2.1
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.1
      @tarojs/router: ^1.2.0 => 1.2.1
      @tarojs/taro: ^1.2.0 => 1.2.1
      @tarojs/taro-alipay: ^1.2.0 => 1.2.1
      @tarojs/taro-h5: ^1.2.0 => 1.2.1
      @tarojs/taro-swan: ^1.2.0 => 1.2.1
      @tarojs/taro-weapp: ^1.2.0 => 1.2.1
      @tarojs/webpack-runner: ^1.2.0 => 1.2.1
      eslint-config-taro: ^1.2.0 => 1.2.1
      eslint-plugin-taro: ^1.2.0 => 1.2.1

**补充信息**
无

**Comment by yuche** [comment]
是正常的。

而且
```
  componentDidMount () {
    ddddd
  }
```
不是语法错误，因为不执行代码就不知道 ddddd 是不是没有定义。

**Comment by xiaodid** [comment]
是不是我要看到这种错误，只能手动运行tsc才行了？一边开一个```npm run dev:weapp```，再开一个```tsc --watch```？
希望后续能在build过程中把类型检查和sourcemap也加上，这样就完美了。
感谢。

**Comment by yuche** [comment]
你编辑器的时候也会报错，我认为只有在 precommit 的检查就行了。build 的过程不会加上类型检查，加了又会有人让我取消掉，这事得用户自己决定。
