### ISSUE TITLE
请问谁知道saveFile保存的文件去哪里了??

### ISSUE THREAD

**Issue by pollux2015** [NervJS/taro#1701]
请问谁知道saveFile保存的文件去哪里了??
需求是我要下载一个pdf文件到手机里面, 
提示我保存成功但是,就是在手机里面找不到文件. 
第一次做小程序, 哪位大神能给我解答下吗?

![image](https://user-images.githubusercontent.com/11935278/50440875-1150c980-0933-11e9-9f86-46ada734e03c.png)

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/50443812-ec168800-093f-11e9-9ca4-47cb0dab96c4.png)
https://developers.weixin.qq.com/miniprogram/dev/api/wx.saveFile.html

看个文档有那么难吗

**Comment by id-fq** [comment]
示例代码
```typescript
 const downloadTask = Taro.downloadFile({
     url: 'http://example.com/audio/123', //仅为示例，并非真实的资源
     success: function(res) {
         Taro.playVoice({
             filePath: res.tempFilePath
         })
     }
 })
 downloadTask.onProgressUpdate((res) => {
     console.log('下载进度', res.progress)
     console.log('已经下载的数据长度', res.totalBytesWritten)
     console.log('预期需要下载的数据总长度', res.totalBytesExpectedToWrite)
 })
```
