### ISSUE TITLE
1.2.0-beta.15，this.xxxFn.bind(this,"xxx") 绑定到组件的props上失效

### ISSUE THREAD

**Issue by fengwuxp** [NervJS/taro#1705]
**问题描述**
       在任意的组件中传入onClick的处理，例如this.xxxFn.bind(this,"xxx") ，期望xxxFn中能接收到 传入参数，这问题会导致自定义组件，以及taro-ui的组件使用失效或报错，原因是对应的处理方法没有接收到期望得到的参数。

**复现步骤**
  
 

```js
// 这里可以贴代码
   goToVisit(e) {
        console.log("e", e);
        // Taro.navigateTo({url: "../tabs/index"});
    }
     <View   className='demo-text-1'
                   onClick={this.goToVisit.bind(this, 123)}>
                       <Image className='swiper-item' src={item.img} />
      </View>
```

**期望行为**
期望console.log打印输出123

**报错信息**
结果是打印输出的是点击事件对象event

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [1.2.0-beta.15]
 - Node.js 版本 [ v10.14.2、v11.40]
 - 报错平台 [weapp]

**补充信息**
  项目使用了typescript
   我有单独测试过，如果按照如下代码：
```  
   setTimeout(()=>{
            this.goToVisit.bind(this,1234)
        },1000);
   
```
的写法，goToVisit方法中能得到正确的参数

将版本切换到1.2.0-beta.2可以得到正确的结果

**Comment by GooeyNyan** [comment]
表示同样遇到了这个问题，希望能尽快解决，谢谢🙏！

**Comment by yuche** [comment]
那你就升级你的版本啊，即便这个问题存在我们修复了，也不能覆盖1.2.0-beta.15，你只能装新版本

**Comment by fengwuxp** [comment]
目前只有一个beta.16，没用

**Comment by yuche** [comment]
原来 1.2.0/1.2.1/1.2.2 都不算版本，他们是私生的吗

**Comment by luckyadam** [comment]
cli 和依赖都升级到最新版本吧

**Comment by wangruiStart** [comment]
同样的问题，依赖升级到最新1.2.2。问题依然没有修复

**Comment by geminiyu233** [comment]
这个问题确实是版本的原因，目前最新版本这个问题是存在的，需要切换一下版本。
