### ISSUE TITLE
taro convert 转换 内容丢失

### ISSUE THREAD

**Issue by mindfocus** [NervJS/taro#1706]
**问题描述**
taro convert 转换一个原声小程序时，部分组件属性转换有问题，
比如： onSubmit 会转换成onUbmit
onGetPhoneNumber 会转换成 onEtPhoneNumber

**复现步骤**
[复现问题的步骤]
1. clone repo [wechat-app-mall](https://github.com/EastWorld/wechat-app-mall)
2. taro convert repo
3. 全局搜索 onUbmit

**期望行为**
正确转换

**报错信息**

无报错信息

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.1 => 1.2.1
      @tarojs/components: 1.2.1 => 1.2.1
      @tarojs/plugin-babel: 1.2.1 => 1.2.1
      @tarojs/plugin-csso: 1.2.1 => 1.2.1
      @tarojs/plugin-sass: 1.2.1 => 1.2.1
      @tarojs/plugin-uglifyjs: 1.2.1 => 1.2.1
      @tarojs/redux: 1.2.1 => 1.2.1
      @tarojs/redux-h5: 1.2.1 => 1.2.1
      @tarojs/router: 1.2.1 => 1.2.1
      @tarojs/taro: 1.2.1 => 1.2.1
      @tarojs/taro-alipay: 1.2.1 => 1.2.1
      @tarojs/taro-h5: 1.2.1 => 1.2.1
      @tarojs/taro-swan: 1.2.1 => 1.2.1
      @tarojs/taro-weapp: 1.2.1 => 1.2.1
      @tarojs/webpack-runner: 1.2.1 => 1.2.1
      eslint-config-taro: 1.2.1 => 1.2.1
      eslint-plugin-taro: 1.2.1 => 1.2.1

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
被👽吃掉了？

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/4b248d1b77e5093bea1dc8b41e91d6fa3c8e7267
