### ISSUE TITLE
ScrollView 组件 H5 和小程序的行为不太一致

### ISSUE THREAD

**Issue by fjc0k** [NervJS/taro#1707]
**问题描述**

代码：

这是个 tabs 组件，点击 item 时改变 scrollLeft，达到横向滚动效果。

![image](https://user-images.githubusercontent.com/13151189/50449566-28a7ab00-0963-11e9-8654-a69e6ea3ca61.png)

小程序效果：

![gif](https://user-images.githubusercontent.com/13151189/50449721-03676c80-0964-11e9-9c58-72dc08b689d1.gif)

H5 效果：

![gif2](https://user-images.githubusercontent.com/13151189/50449734-0febc500-0964-11e9-8609-e7e6fe7f9944.gif)

显而易见，在点击末尾的 “选课秘籍” tab时，H5 相对于 小程序有明显的跳动感，在点击“吐槽”时也有种跳动感，不过在 gif 不易看出。

**复现步骤**
如上。

**期望行为**
小程序与H5表现一致。

**报错信息**

无。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

```bash
  Taro CLI 1.2.1 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      Node: 10.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - ~\AppData\Local\Yarn\bin\npm.CMD
```

**Comment by jinjinjin0731** [comment]
H5 的动画效果会从 0 到目标位置。  这个体验可以优化一下

**Comment by fjc0k** [comment]
@jinjinjin0731 我看了源码发现 onScroll 时没把滑动过程中最新的 scrollLeft 记住，仍用 props 传下的 scrollLeft 作为动画的起点，所以出现了这个问题。这个，你们可以忙其他的，我可以提个 pr。🤓

**Comment by jinjinjin0731** [comment]
@fjc0k  好的~~~非常棒

**Comment by fjc0k** [comment]
@jinjinjin0731 老哥，还是你来吧，玩不转玩不转，taro-components build 、test 都报错，这是我的工作，rebase 之前 build 测试过的：

https://github.com/fjc0k/taro/commits/dev-fix-h5-ScrollView

![image](https://user-images.githubusercontent.com/13151189/50466190-018ac100-09d7-11e9-89fc-6ef2d7ed0221.png)

**Comment by jinjinjin0731** [comment]
好 非常感谢 ~ 晚点我看下
