### ISSUE TITLE
设置了其它输出目录在编译时仍然清除 dist 目录

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#1709]
**问题描述**
设置了其它输出目录在编译时仍然清除 dist 目录

**复现步骤**
1. 在 `config/prod.js` 下设置 `outputRoot` 为其它目录
2. 运行 `build:weapp` 或 `build:h5`

**期望行为**
仅清空设置的 `outputRoot` 目录

**报错信息**
无报错，但还是把 `dist` 文件夹清除了

**系统信息**
� Taro v1.2.1

  Taro CLI 1.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/ddfb51ca6aa6ea568a60f26d5c369b7b934334c2
