### ISSUE TITLE
Picker 组件不能传入 dataset 参数

### ISSUE THREAD

**Issue by wind13** [NervJS/taro#1714]
在使用 Picker 组件 `mode=time` 时，尝试添加 `className` 是可以的，但想加入一些 `data-aaa` 之类的属性就不行了，最后出来的 Dom 中是没有的，会有这样的需求，除了取得选择的 value 外，希望再带一些 dataset 的参数，如某行某列的某个 Time Picker 组件，希望知道是哪一行哪一列的等。

**Comment by luckyadam** [comment]
这种情况可以，可以用事件 + bind 来进行传参

**Comment by wind13** [comment]
问题是在微信小程序那边可以正常使用，我是从微信小程序转换过来的，因为这个问题，转过来的小程序不能正常工作，查了半天，发现是因为小程序里设置的 "data-xxx" 并没有传入到 Picker 组件中，同时逻辑上也说不通，"className" 这个属性都是可以的，为什么 "data-xxx" 却不行呢？

**Comment by luckyadam** [comment]
@wind13 能不能贴一个你的示例代码，我们看下

**Comment by wind13** [comment]
A picker in wxml file of WeChat.
```html
            <picker mode="time" value="{{item.time}}" start="18:30" end="20:59"
              bindchange="changeTime" data-year="{{m.y}}" data-day="{{item.day}}" data-month="{{m.m}}" data-ap="pm">
              <view class="picker">
                {{item.time}}
              </view>
            </picker>
```

**Comment by luckyadam** [comment]
In Taro
```jsx
<Picker mode="time" value={item.time}" start="18:30" end="20:59"
  data-year={m.y} data-day={item.day} data-month={m.m}
  onChange={this.changeTime.bind(this))}>
  <view className="picker">
    {{item.time}}
  </view>
</Picker>
```
event handler like this

```js
changeTime: function (e) {
  const ds = e.target.dataset;
  const v = e.detail.value;
  console.log(ds.year);
  console.log(ds.month);
  console.log(ds.day);
  console.log(v);
}
```

it works well

**Comment by wind13** [comment]
No, it doesn't work with me. I am testing under: `npm run dev:h5`.

**Comment by jinmincr** [comment]
radio组件也有同样的问题data-id 没有传入，e.target.dataset获取不到

**Comment by zacksleo** [comment]
这个问题啥时候能解决啊

**Comment by classLfz** [comment]
好像是在 map 里边进行列表渲染的时候，进行 dataset 跟事件绑定会拿不到  `event.target.dataset` (里边是空的)？
