### ISSUE TITLE
H5触发dispatch后返回上一页，this.props.XXXX的数据没有重新渲染。

### ISSUE THREAD

**Issue by achefinil** [NervJS/taro#1716]
**问题描述**
触发dispatch后action成功值也修改了
当前页面展示没问题
但是返回上一页调用的this.props.XXXX的数据没有重新渲染

**复现步骤**

1. A页面为主页面，进入B页面
2. 选择一个日期触发dispatch，redux-logger打印日志，值成功修改。B页面的值也成功渲染。
3. 返回A页面，调用的this.props.XXXX的日期竟然没有变化（没有触发渲染）

**期望行为**
原来是正常的。

**报错信息**
无报错信息。

**系统信息**
👽 Taro v1.2.2

  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.2.0 - ~/.nvm/versions/node/v9.2.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v9.2.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.2 => 1.2.2
      @tarojs/components: ^1.2.2 => 1.2.2
      @tarojs/plugin-babel: ^1.2.2 => 1.2.2
      @tarojs/plugin-csso: ^1.2.2 => 1.2.2
      @tarojs/plugin-less: ^1.2.2 => 1.2.2
      @tarojs/plugin-sass: ^1.2.2 => 1.2.2
      @tarojs/plugin-uglifyjs: ^1.2.2 => 1.2.2
      @tarojs/redux: ^1.2.2 => 1.2.2
      @tarojs/redux-h5: ^1.2.2 => 1.2.2
      @tarojs/router: ^1.2.2 => 1.2.2
      @tarojs/taro: ^1.2.2 => 1.2.2
      @tarojs/taro-h5: ^1.2.2 => 1.2.2
      @tarojs/taro-weapp: ^1.2.2 => 1.2.2
      @tarojs/webpack-runner: ^1.2.2 => 1.2.2
      eslint-config-taro: ^1.2.2 => 1.2.2
      eslint-plugin-taro: ^1.2.2 => 1.2.2

**补充信息**
返回采用Taro.navigateBack的返回方式

**Comment by achefinil** [comment]
补充： 1.2.0-beta.7版本是好的。
1.2.0 1.2.2个别页面就这样 componentWillReceiveProps componentDidShow 都不执行。很奇怪。

**Comment by Littly** [comment]
最新的版本还存在这个问题吗？
