### ISSUE TITLE
Toast在自动关闭后,修改state中的值时会再次弹出

### ISSUE THREAD

**Issue by jyjey** [NervJS/taro#1717]
**问题描述**
Toast在自动关闭后,修改state中的值时会再次弹出

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
Toast能正常关闭,且不会因为修改state中其他值而再次弹出

**报错信息**

**系统信息**
Taro CLI 1.2.1 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.14.2 - D:\node\node.EXE
      Yarn: 1.9.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - D:\node\npm.CMD
**补充信息**

**Comment by Chen-jj** [comment]
@jyjey 什么平台发现的问题？另外提供一下可复现代码
