### ISSUE TITLE
import 进来的包 没有过babel吗?

### ISSUE THREAD

**Issue by nakating** [NervJS/taro#1719]
**问题描述**
构建H5，引入了一个包， 他里面有 `=>` 箭头方法。 构建出来的H5中直接引进来了。 导致在某些环境下无法运行。

```js
//app.tsx
import * as test from "testpackage";

//testpackage
module.exports = {
  arrow: () => 20,
  assign: function(a, b) {
    return Object.assign(a, b);
  }
};


// dist/js/app.js 中的相关代码
  function(e, t, n) {
    "use strict";
    e.exports = {
      arrow: () => 20,
      assign: function(e, t) {
        return Object.assign(e, t);
      }
    };
  }
```

**期望行为**
引入的包也es5ify

**Comment by luckyadam** [comment]
在 `config/index.js` 的 `weapp.compile` 配置里加上 `include` 这个配置，里面写你的 npm 包

```js
weapp: {
  compile: {
    include: []
  }
}
```

**Comment by nakating** [comment]
> 在 `config/index.js` 的 `weapp.compile` 配置里加上 `include` 这个配置，里面写你的 npm 包
> 
> ```js
> weapp: {
>   compile: {
>     include: []
>   }
> }
> ```

我加在 h5里了，但是并没有什么效果。 这个是需求taro某个版本号的配置项吗?

**Comment by luckyadam** [comment]
> 我加在 h5里了，但是并没有什么效果。 这个是需求taro某个版本号的配置项吗?

H5 的话是这个配置

https://nervjs.github.io/taro/docs/config-detail.html#h5esnextmodules

**Comment by nakating** [comment]
resolve
