### ISSUE TITLE
Taro.request success回调无效 微信小程序

### ISSUE THREAD

**Issue by btstack** [NervJS/taro#172]
Taro.request({
      url: 'https://...',
      success: function(res){
        console.log(res)
      },
      fail: function(res){
        console.log(res)
      },
    })

**Comment by isting** [comment]
Taro.request({
  url: 'http://localhost:8080/test',
  data: {
      foo: 'foo',
      bar: 10
  },
  header: {
    'content-type': 'application/json'
  }
})
  .then(res => console.log(res.data))

**Comment by btstack** [comment]
文档里面写可以用success和fail的啊

**Comment by luckyadam** [comment]
@btstack 已经修复啦，下个版本支持

**Comment by btstack** [comment]
感谢！
