### ISSUE TITLE
Slider 组件在 H5 下跟小程序表现不一致

### ISSUE THREAD

**Issue by koppthe** [NervJS/taro#1720]
**问题描述**
当 Slider 组件设置了 min 属性之后，H5 的表现会有误，Slider 无法滑动到最左侧，而且当滑动到最后测时，会突然跳到 max 的值。

例如以下 DEMO：
```js
<Slider step='1' value='100' showValue min='50' max='200'/>
```

H5 下表现的行为：Slider 没法滑动到最左侧，以及 Slider 滑动到最右侧是，value 会从 149 突然跳到 200

**复现步骤**
使用 taro components 的 Slider 基础组件，设置 min 和 max 的值，然后在 H5 下即可重现

**期望行为**
变现跟微信小程序保持一致

**报错信息**
可体验 taro-ui 的 Slider Demo 页：https://taro-ui.aotu.io/h5/#/pages/form/slider/index

**系统信息**
 - 操作系统: mac v10.14.1
 - Taro 版本: v1.2.2
 - Node.js 版本: v8.9.1
 - 报错平台: H5

**Comment by iyoucheng** [comment]
@koppthe 你解决这个问题了吗？

**Comment by iyoucheng** [comment]
@jinjinjin0731 slider 组件在 h5 上有 bug，比如有时候拖动的时候数组会超过设置的最大值，还有比如最大值是 1500，然后拖动到最右边会从200突然变成1500

**Comment by jinjinjin0731** [comment]
@iyoucheng  最近在修。预计 8月初 fix

**Comment by iyoucheng** [comment]
> @iyoucheng 最近在修。预计 8月初 fix

ok，辛苦老哥了

**Comment by ZakaryCode** [comment]
fixed in #a4d2af14d08921bf7afc3f40dde285c945020956
