### ISSUE TITLE
h5中textarea中onInput和onChange返回值只有一个字母

### ISSUE THREAD

**Issue by MisranDia** [NervJS/taro#1724]
**问题描述**
在h5中使用textarea， 使用键盘输入后只能返回单个字母

**复现步骤**
             <Textarea
                value={this.state.value}
                onChange={this.handleChange.bind(this)}
                maxlength={400}
              />

  handleChange (e) {
    console.log(e)
    this.setState({
      value:e.data
    })
  }

使用输入法输入测试后：
![image](https://user-images.githubusercontent.com/37993210/50471999-f729f080-09f1-11e9-8555-d8bd48c5747f.png)
![image](https://user-images.githubusercontent.com/37993210/50472229-e5951880-09f2-11e9-8925-6267cad03aa0.png)

再输入结束
![image](https://user-images.githubusercontent.com/37993210/50472026-145ebf00-09f2-11e9-91cb-84ca72dc4791.png)
![image](https://user-images.githubusercontent.com/37993210/50472250-f34a9e00-09f2-11e9-9057-d7b385bd3073.png)

之前输入的‘测试’被清空了 只留下了’结束（jieshu）’的最后一个字母 

在微信小程序中返回则正常
![image](https://user-images.githubusercontent.com/37993210/50472102-5e47a500-09f2-11e9-9da1-96083bb43807.png)
![image](https://user-images.githubusercontent.com/37993210/50472124-6f90b180-09f2-11e9-8e92-5300ab2e663e.png)

**期望行为**
和小程序返回的内容一致

**报错信息**

无报错 只是返回信息不一致 而且无法解决

**系统信息**

 - 操作系统: [e.g.  Windows 7]
 - Taro 版本 [e.g. v1.2.2]
 - Node.js 版本 [e.g. 8.9.3]
 - 报错平台 [h5]

**补充信息**
这里返回给我的是按键的内容 并不是textarea内已经输入的内容

**Comment by tourze** [comment]
好像这个问题之前也报告过了

**Comment by jinjinjin0731** [comment]
首先你的  Textarea value 绑定了 state ，在每次输入的时候会 setState ，变成了一个受控组件。 根据你的截图来看，你输入框中的内容和打印出来的内容是一致的。 在小程序为什么可以，你看下文档就知道了。 

**tip: 不建议在多行文本上对用户的输入进行修改，所以 textarea 的 bindinput 处理函数并不会将返回值反映到 textarea 上。**

[textarea](https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html)
