### ISSUE TITLE
开发RN端时引入taro-ui，编译时报错，暂时不兼容的情况下也应该保证引入不报错

### ISSUE THREAD

**Issue by devilruiniu** [NervJS/taro#1727]
**问题描述**
在同时开发H5,Weapp,RN时，虽然taro-ui不支持RN端，但是需要在h5,weapp端时引入并使用taro-ui，页面代码中如果使用了taro-ui，运行命令npm run dev:rn时就会报错：
Unable to resolve ./components/calendar" from "./D:\\work_area\\klife_v2.0.1\\klife_h5_mobild_v3\\.rn_temp\\node_modules\\taro-ui\\dist\\weapp\\index.js`: The module `./components/calendar` could not be found"

**复现步骤**
[复现问题的步骤]
1. taro init <peojectName>
2. npm install taro-ui
3. npm run dev:rn
4. 报错

**期望行为**
虽然taro-ui暂时不支持rn，但是最起码引入应该不报错

**报错信息**

Unable to resolve ./components/calendar" from "./D:\\work_area\\klife_v2.0.1\\klife_h5_mobild_v3\\.rn_temp\\node_modules\\taro-ui\\dist\\weapp\\index.js`: The module `./components/calendar` could not be found"

**系统信息**
 - 操作系统: Windows 10
- Taro UI 版本 v1.5.3
 - Taro 版本 v1.2.1
 - Node.js 版本 v8.11.2
 - 报错平台 rn

**补充信息**
[可选]
解决方法：注释node_modules\taro-ui\dist\weapp\index.js文件中
// export { default as AtCalendar } from './components/calendar'的代码
问题原因：components/calendar文件夹中缺少index.js文件

**Comment by Pines-Cheng** [comment]
这个需要自己使用环境变量区分或者写一些跨端代码哦。
