### ISSUE TITLE
Button 组件获取手机号回调事件无效

### ISSUE THREAD

**Issue by thomasyxy** [NervJS/taro#173]
在小程序开发中使用Button获取用户手机号无法触发 `bindgetphonenumber`
代码如下：

``` javascript
<Button className='btn-max-w' plain type='primary' openType='getPhoneNumber' bindgetphonenumber={this.getPhoneNumber}>按钮</Button>
```
得到下面的警告，且getPhoneNumber没有执行

`Do not have getPhoneNumber handler in current page: pages/component/pages/button/button. Please make sure that getPhoneNumber handler has been defined in pages/component/pages/button/button, or pages/component/pages/button/button has been added into app.json`

使用 `onBindgetphonenumber` 没有执行也没有警告

**Comment by 1Crazy** [comment]
哇，踩了个坑。。。。还好找到答案了~~

**Comment by 1Crazy** [comment]
感谢
