### ISSUE TITLE
<Input   focus="true" />focus属性在h5 有bug

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1732]
<Input   focus="true" />focus属性在h5 有bug 

在安卓和苹果 页面中存在Input 和 其他按钮组件

表现：1 苹果设备h5中第一次进入页面时候，不自动弹起键盘，即focus没有自动
           2 苹果和安卓设备 在进入页面后，触发了自动弹起键盘，然后点击屏幕页面其他空白区域，此时失去焦点，接着点击其他按钮组件，按钮控制页面的布局变化，此时又再一次自动弹起键盘，获得了焦点？原理上不应该再一次自动弹起焦点的，触发点击了Input输入框才弹起来

👽 Taro v1.2.2

1.2.2
xingwenmadeMac-mini:~ lanhui_mac$ taro  info
👽 Taro v1.2.2

  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by xingwen93** [comment]
<Input
		               focus="true"
		              type='text'
		              value={data}
		              onFocus={this.vv}
			     onInput={this.vvvv}
		              onBlur={this.vvv}
		            />

**Comment by xingwen93** [comment]
![image](https://user-images.githubusercontent.com/16276222/50500437-415fb000-0a8c-11e9-8945-3f9729255482.png)

**Comment by jinjinjin0731** [comment]
你的 package.json 里面的内容可以贴一下吗~

**Comment by xingwen93** [comment]
![image](https://user-images.githubusercontent.com/16276222/50501168-217ebb00-0a91-11e9-894e-a23e81abc57e.png)

**Comment by xingwen93** [comment]
![image](https://user-images.githubusercontent.com/16276222/50501176-34918b00-0a91-11e9-9243-83adaa3f0399.png)

**Comment by xingwen93** [comment]
苹果的h5第一次加载不自动弹，后面点击个按钮也自动弹了

**Comment by jinjinjin0731** [comment]
最新版本可以解决么。

**Comment by red2333** [comment]
在h5页面下，fouce属性能让input获取到焦点，但不能唤起键盘
