### ISSUE TITLE
Taro.navigateTo 返回问题

### ISSUE THREAD

**Issue by CozySnail** [NervJS/taro#1735]
**问题描述**
Taro.navigateTo遇到一个问题
A ==> Taro.navigateTo B , B ==> Taro.navigateTo C  后
C ==> Taro.navigateBack({delta: 1}) 可以到 B,
C ==> Taro.navigateBack({delta: 2}) 可以到 A,

但是
C ==> Taro.navigateBack({delta: 1}) 可以到 B,
此时在 B 页面就无法使用 Taro.navigateBack({delta: 1}) 到 A 了

**复现步骤**
[复现问题的步骤]
见问题描述

**期望行为**
可以正常多层单次返回

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. MacOS]
 - Taro 版本 [e.g. v.1.2.0-beta.11]
 - Node.js 版本 [e.g. v10]
 - 报错平台 [RN]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
3d06b4b4
