### ISSUE TITLE
1.2.2 map下的模板字符串出现问题

### ISSUE THREAD

**Issue by tyaqing** [NervJS/taro#1738]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**

![wechatimg24057](https://user-images.githubusercontent.com/11229306/50504824-3700de80-0aab-11e9-89fa-9fe271c56a32.jpeg)

今天升级到1.2.2 后之前列表的模板字符串貌似报错,注释掉之后就可以运行.

**期望行为**
resolve

**报错信息**

![2018-12-28 12 05 06](https://user-images.githubusercontent.com/11229306/50504791-015bf580-0aab-11e9-9adc-ff548c3ad983.png)

**系统信息**
Taro v1.2.2

  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/50537061-35f8ab80-0b96-11e9-9bcd-b9d58a2c1e14.png)
写成箭头函数
