### ISSUE TITLE
安装完 @tarojs/cli 之后发现 nrm 切换不了镜像

### ISSUE THREAD

**Issue by AZmake** [NervJS/taro#1741]
OS: Mac

不知道是不是 @tarojs/cli 里面是否安装了yarn, 然后 yarn 锁定了npm镜像地址

**Comment by luckyadam** [comment]
项目目录下有个 npmrc 文件，你看看是不是这个原因

**Comment by AZmake** [comment]
谢谢了，就是这个文件的问题。
顺便问一下，为什么需要指定sass和fsevents的仓库地址？
npmrc这个文件有必要放到template项目里面？
