### ISSUE TITLE
taro1.2.2  父子组件通讯（triggerEvent），组件引用（ref）的问题

### ISSUE THREAD

**Issue by zhouweiming** [NervJS/taro#1742]
问题：
1. echarts组件可以通过triggerEvent('init')来加载，但是我在ec-canvas上添加了`bindinit={this.initChart}`，提示在当前页面找不到`initChart`这个method

2. 获取组件引用，小程序有`this.selectComponent`，我也看了很多issues，提到新版本可以用`ref`来处理，但是我用的1.2.2版本提示`this.refs 是undefined`，用`this.$scope.selectComponent`解决了

```
  state = {
    ec: {
      lazyLoad: true
    }
  }
  componentWillMount () {
    console.info(this.refs); // undefined
    this.$scope.selectComponent('#mychart-dom-area').init((...args) => {
      console.info(args);
    })
  }

  render () {
    return (
      <View className="container">
        <View className="echart-wrapper" ref="ccc">
          <ec-canvas id='mychart-dom-area' ref="aaa" bindinit={this.initChart} canvas-id='mychart-area' ec={this.state.ec}>
          </ec-canvas>
        </View>
      </View>
    )
  }
  
  initChart (...args) { console.info(args); }
```

taro info

➜  we-app-taro git:(master) ✗ taro info
👽 Taro v1.2.2

  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.2 => 1.2.2 
      @tarojs/components: 1.2.2 => 1.2.2 
      @tarojs/plugin-babel: 1.2.2 => 1.2.2 
      @tarojs/plugin-csso: 1.2.2 => 1.2.2 
      @tarojs/plugin-sass: 1.2.2 => 1.2.2 
      @tarojs/plugin-uglifyjs: 1.2.2 => 1.2.2 
      @tarojs/redux: 1.2.2 => 1.2.2 
      @tarojs/redux-h5: 1.2.2 => 1.2.2 
      @tarojs/router: 1.2.2 => 1.2.2 
      @tarojs/taro: 1.2.2 => 1.2.2 
      @tarojs/taro-alipay: 1.2.2 => 1.2.2 
      @tarojs/taro-h5: 1.2.2 => 1.2.2 
      @tarojs/taro-swan: 1.2.2 => 1.2.2 
      @tarojs/taro-weapp: 1.2.2 => 1.2.2 
      @tarojs/webpack-runner: 1.2.2 => 1.2.2 
      eslint-config-taro: 1.2.2 => 1.2.2 
      eslint-plugin-taro: 1.2.2 => 1.2.2

**Comment by Chen-jj** [comment]
在 componentDidMount 中获取 ref

**Comment by Chen-jj** [comment]
bindinit 改成 onInit 试试

**Comment by zhouweiming** [comment]
ok   解决了，谢谢   @Chen-jj
