### ISSUE TITLE
windows 下加入原生小程序页面，编译异常

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#1744]
**问题描述**
windows系统 下加入原生小程序页面，编译异常

**复现步骤**
voice.wxml 位于项目根目录/src/pages/voice/ 文件夹里
![image](https://user-images.githubusercontent.com/23295172/50512035-f31dd180-0aca-11e9-839b-79719998af17.png)

**报错信息**
![image](https://user-images.githubusercontent.com/23295172/50512002-ce295e80-0aca-11e9-8ee8-8077f0f0585a.png)

上图中，蓝色选中的代码是我加入的调试代码，
·fs.existsSync(pageWXMLPath)· 用于检查该文件是否存在，没有正常工作,
所调试代码位于 `@tarojs/cli/src/weapp.js` 内

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v10.0.6]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
是首次编译，还是 watch 时候新增或者修改页面时报的错

**Comment by Dithub2016** [comment]
首次 watch 时，其它还没尝试

**Comment by luckyadam** [comment]
@Dithub2016 收到，我来看下~

**Comment by Dithub2016** [comment]
犯糊涂了，的确没文件存在，目前版本在 1.2.4 正常编译
