### ISSUE TITLE
h5 getSystemInfoSync 无法区分手机型号

### ISSUE THREAD

**Issue by yujiaming890321** [NervJS/taro#1745]
**问题描述**
![b5740bde-d8ad-4012-a2ef-f83a35e5e5f1](https://user-images.githubusercontent.com/13047250/50513766-b1922400-0ad4-11e9-98fa-7eff75bfe979.png)

**系统信息**
 - Taro 1.2.2
 - 报错平台 h5

**Comment by Chen-jj** [comment]
暂时根据 process.env.TARO_ENV 环境变量判断 h5 环境时自己写个方法分析下吧

**Comment by luckyadam** [comment]
H5 暂时自己通过 userAgent 来分析手机型号吧

**Comment by Littly** [comment]
h5下暂时没有什么好办法来区分手机型号。
如果有好的想法，欢迎交流。
