### ISSUE TITLE
无法在 mapStateToProps 获取到 ownProps

### ISSUE THREAD

**Issue by bmcciscoding** [NervJS/taro#1746]
**问题描述**

我创建了一个组件A， 我想通过  <A p1='test' /> 方式传递属性，但是我同时也使用 redux 的 connect 来创建组件，现在我无法再 mapStateToProps 的第二个参数 ownProps 拿到 p1

**复现步骤**

传递属性 p1
```js
render () {
    return (
      <Provider store={store}>
        <Index p1='test' />
      </Provider>
    )
  }
```

期望在通过 ownProps.p1 拿到传递过来的值
```js
// todolist.js
const mapStateToProsp = (state, ownProps) => {
  return {
    ...state.todoListReducer,
    p1: ownProps.p1
  }
}
```

导出
```js
// totodlist.js
export default connect(mapStateToProsp, mapDispatchToProps)(Index)
```

**期望行为**

在 mapStateToProps 中第二个参数 ownProps 拿到传递过来的属性，
或者我该如何写才能拿到呢？

**报错信息**

p1: undefined

**系统信息**

 - 报错平台：weapp

**补充信息**

和 Redux 的文档不一致，在 Taro-Redux 中也没有找到相关的说明

**Comment by luckyadam** [comment]
在群里的回复，以及文档，还有生成的模板代码注释中，都有提及，app 的 render 函数是个语法糖，不会起任何作用，我不明白你为什么还要在 app 的 render 里给页面传 props

![image](https://user-images.githubusercontent.com/1782542/50517001-f88a1480-0ae8-11e9-8bfe-7ec6b7b2c341.png)

**Comment by bmcciscoding** [comment]
感谢你的回复，通过你的截图，我找到了个相关的文档，之前都在查看 使用redux 这个章节，所以没有看到。这里说的入口文件，是启动的第一个页面才会 render 里不起任何作用吗？

因为我的需求其实是想给子组件传递属性，例如这里的 Todo 是我自定义的一个组件
```js
const todolist = this.state.todolist.map((data, index) => {<Todo key={index} todo={data}></Todo>})
```
然后我想在 Todo.js 拿到这个 todo
```js
const mapStateToProsp = (state, ownProps) => {
  return {
    p1: ownProps.todo
  }
}
```
但是这样我依然无法拿到 todo。所以我才会在 App 入口中测试一个最小的例子。
所以我想弄明白是不是通过 connect 的组件都无法通过 ownProps 拿到传递的值？

**Comment by bmcciscoding** [comment]
- Taro v1.2.0-beta.14
- node v11.2.0
- macOS Mojave 10.14.1
- 微信开发工具 v1.02.1812180

**Comment by bmcciscoding** [comment]
编译成 h5 是没问题的，但是小程序会出现这样的情况

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/c3dc5d1c8fbfce0508f4d0219498937d26712e7f
