### ISSUE TITLE
page 级别的 DidHide 后 不调用 子组件的DidHide？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1748]
page 级别的父组件  DidHide 后 不调用 子组件的DidHide，而是调用 子组件的DidShow,当 父组件 DidShow 后 有再次调用 子组件的DidShow ，很不理解，为什么 出现这样的 生命周期 触发事件？

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Mac]
 - Taro 版本 [Taro v1.2.0-beta.7]
 - Node.js 版本 [v10.14.1]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@JoMartinezZhu 升级到1.2.2再试试

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/4bb99cd7c33373ac3fa162b96c8ec44809ac9d41
