### ISSUE TITLE
文档中的链接404

### ISSUE THREAD

**Issue by huixisheng** [NervJS/taro#1750]
**问题描述**
![image](https://user-images.githubusercontent.com/1518967/50532115-9284a800-0b4f-11e9-9e95-d71506a2c38c.png)
红色划线链接404

**Comment by huixisheng** [comment]
- https://nervjs.github.io/taro/docs/state.html 
- https://nervjs.github.io/taro/docs/props.html
正确链接

**Comment by Pines-Cheng** [comment]
多谢提醒～
