### ISSUE TITLE
页面出现 多个  仪表图，初次渲染页面出现 错乱，但是 swichTab 切换后 就回复正常了？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#1752]
### 简单描述问题：
页面出现 多个  仪表图，初次渲染页面出现 错乱，但是 swichTab 切换后 就回复正常了？

### 预期效果：
![image](https://user-images.githubusercontent.com/43346131/50532414-f7da9800-0b53-11e9-8e35-f3f9e0cf6e52.png)

### 实际效果：
？？？
（如有需要请提供截图）
![image](https://user-images.githubusercontent.com/43346131/50532420-06c14a80-0b54-11e9-8132-8a1ea032dd16.png)

**系统信息**

 - 操作系统: [e.g. Mac]
 - Taro 版本 [e.g. v1.2.0-beta.7]
 - Node.js 版本 [e.g. v10.14]
 - 报错平台 [ weapp]

**Comment by Pines-Cheng** [comment]
哪个端？

**Comment by JoMartinezZhu** [comment]
> 哪个端？

weapp(小程序)

**Comment by luckyadam** [comment]
检查一下自身写法，或者调试一下吧

**Comment by JoMartinezZhu** [comment]
> 检查一下自身写法，或者调试一下吧

有什么思路提供一下嘛？现在不知道去哪里找问题！

**Comment by luckyadam** [comment]
出现错位的时候看下 dom 以及样式咯

**Comment by JoMartinezZhu** [comment]
> 出现错位的时候看下 dom 以及样式咯

ios 就显示正常的！说明样式没有用问题吧！

**Comment by zhouweiming** [comment]
canvas会有这个问题，我们之前发现这个问题，是因为canvas一旦初始化后，最好canvas之上的所有元素就不能再有高度变化了，否则就会错位

**Comment by luckyadam** [comment]
可以按楼上大佬说的调整下
