### ISSUE TITLE
为什么使用webstorm打开taro初始化的typescript项目时eslint报语法错误

### ISSUE THREAD

**Issue by mostearly** [NervJS/taro#1755]
文件地址：src/pages/index/index.tsx
编辑器：WebStorm 2018.3
错误代码：
```typescript
type PageDispatchProps = {
  add: () => void
  dec: () => void
  asyncAdd: () => any
}
```
错误提示：
`ESLint: Parsing error: Unexpected token 26 | type PageDispatchProps = { 27 | add: () => void > 28 | dec: () => void | ^ 29 | asyncAdd: () => any 30 | } 31 |`
在补充分号后错误消失，然后下面的导出语句报错
错误代码：
```typescript
export default Index as ComponentClass<PageOwnProps, PageState>
```
错误提示：
`ESLint: Parsing error: Unexpected token, expected ";" 96 | // #endregion 97 | > 98 | export default Index as ComponentClass<PageOwnProps, PageState> | ^ 99 |`

能正常编译，但是ESlint报错

请问这该如何解决？

**Comment by luckyadam** [comment]
升级到最新的版本创建试试
