### ISSUE TITLE
npm run dev: 中 <Text> <br></Text> 可以换行，为何 npm run build: <Text><br></Text>不能换行？

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1759]
npm run dev: 中 <Text> <br></Text> 可以换行，为何 npm run build: <Text><br></Text>不能换行？

taro👽 Taro v1.2.2

  Taro CLI 1.2.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by yuche** [comment]
小程序没有 br 这个组件，你应该用 '\n' 来换行
