### ISSUE TITLE
onClick 传参报错

### ISSUE THREAD

**Issue by karchinkong** [NervJS/taro#1763]
![image](https://user-images.githubusercontent.com/16110331/50536387-cc28d380-0b8e-11e9-9a3e-dd65ff7a3e12.png)
![Uploading image.png…]()
点击执行onClick事件 原本传一个url参数 但现在在函数内获取不到url的值
Taro 当前版本为 1.2.2

**Comment by luckyadam** [comment]
麻烦再贴一下你的事件绑定代码

**Comment by jnpd** [comment]
请问你的问题解决了吗  1.2.8
