### ISSUE TITLE
switchTab 不能实现 onLoad

### ISSUE THREAD

**Issue by yhc-yhc** [NervJS/taro#1768]
wx.switchTab({ 
  url: '../index/index', 
  success: function (e) { 
    var page = getCurrentPages().pop(); 
    if (page == undefined || page == null) return; 
      page.onLoad(); 
    } 
}) 

Taro 里面 调用不 到  page.onLoad()

**Comment by luckyadam** [comment]
就是，原生你也调不到

**Comment by yaoyonstudio** [comment]
![2](https://user-images.githubusercontent.com/13121726/51971065-4a8cd400-24b3-11e9-9e2b-c5e6ffa6acfb.png)

![1](https://user-images.githubusercontent.com/13121726/51971008-2d580580-24b3-11e9-8ea0-789ba4512bbb.png)

switchTab不能执行onLoad，使用getCurrentPages打印出来的page对象没有嵌套的$scope，已有onLoad方法。但是执行不了onLoad方法。
