### ISSUE TITLE
不支持bindgetuserinfo和bindgetphonenumber，无法用来开发产品

### ISSUE THREAD

**Issue by ngwing** [NervJS/taro#177]
无法触发获取用户信息的弹窗，旧的api已经不起作用了。
开发版和体验版触发用户授权的弹窗只能用Button+bindgetuserinfo，但Taro目前不支持。
`          <Button open-type="getUserInfo" bindgetuserinfo={this.bindGetUserInfo} >
            获取授权
          </Button>`

**Comment by ngwing** [comment]
无法触发获取用户信息的弹窗，旧的api已经不起作用了

**Comment by bushuai** [comment]
Change ***bindgetuserinfo*** to ***onGetUserInfo***  #173

**Comment by ngwing** [comment]
Thanks. @bushuai

**Comment by HuangHongRui** [comment]
Thanks!~~~
