### ISSUE TITLE
设置 defineConstants 后，build:h5 报错：Unexpected token num «0.4», expected punc «,»

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#1774]
**问题描述**
更新到 1.2.3 后，build:h5 只生成 lib 文件夹，没有其它内容，印象中好像 1.2.2 也会，其它版本没试过

**复现步骤**
1. 在 `config/index.js` 中配置：
```js
defineConstants: {
  'version': process.env.npm_package_version
}
```
2. 在任意地方的 JSX 中引用 version
3. 运行 `npm run build:h5`

**期望行为**
编译不报错

**报错信息**
命令行报错：
```bash
chunk/about_about.js from UglifyJs
Unexpected token num «0.4», expected punc «,» [chunk/about_about.js:184,15]
```

**系统信息**
👽 Taro v1.2.3

  Taro CLI 1.2.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
经测试，在注释掉 `defineConstants` 中的内容，或者注释掉 `version` 中的引用时编译成功，且编译成小程序正常无报错，只在 ` h5` 下有问题。

**Comment by vimcaw** [comment]
`@tarojs/webpack-runner`已经是 1.2.3 了，控制台的输出已经在上面贴出，报错的只有：
```bash
chunk/about_about.js from UglifyJs
Unexpected token num «0.4», expected punc «,» [chunk/about_about.js:184,15]
```
但是我 about.js 里面并没有 0.4 的字样。

最终显示：
```bash
Done in 14.88s.

Process finished with exit code 0
```

**Comment by vimcaw** [comment]
经测试，不是版本的问题，是设置了 `defineConstants`，然后项目中的 JSX 引用了该值导致的报错，但是我 `package.json` 的版本号是 `1.2.4`；

**新的复现步骤**
1. 在 config/index.js 中配置：
```js
defineConstants: {
  'version': process.env.npm_package_version
}
```
2. 在任意地方的 `JSX` 中引用 `version`
3. 运行 `npm run build:h5`

**补充信息**
经测试，在注释掉 `defineConstants` 中的内容，或者注释掉 `version` 中的引用时编译成功，且编译成小程序正常无报错，`dev:h5`也没报错，只在`build:h5`有问题。

**Comment by luckyadam** [comment]
```js
defineConstants: {
  'version': JSON.stringify(process.env.npm_package_version)
}
```

这样试试

**Comment by vimcaw** [comment]
可以了，非常感谢，原来是我自己疏忽了。
