### ISSUE TITLE
h5 获取页面querystring 失败

### ISSUE THREAD

**Issue by Young1993** [NervJS/taro#1778]
http://127.0.0.1:10086/?userId=1

location.href 可以获取到值

但是
this.$router 是空的
hash: ""
params:
__proto__: Object
path: "/pages/snatch/index"
search: ""
state: {key: "0"}

啥时候支持在url后面添加参数this.$router里面就会有了
taro版本
"@tarojs/async-await": "1.2.2"

**Comment by luckyadam** [comment]
`this.$router` 只能获取 taro 规则的 url 参数，你正常跳转一下 url 就知道

**Comment by Young1993** [comment]
> `this.$router` 只能获取 taro 规则的 url 参数，你正常跳转一下 url 就知道

是的，但是vue的话是可以的，我意思是你们可以做下兼容

**Comment by GthanosAI** [comment]
可以在App.js 里面获取this.vnode.dom.baseURI 能够获取到
