### ISSUE TITLE
render 方法支持语法 不全

### ISSUE THREAD

**Issue by zhoujianlin8** [NervJS/taro#178]
![image](https://user-images.githubusercontent.com/2378370/41805294-b5e91804-76d9-11e8-853b-d2e00820961b.png)

1.前面有if的支持可以在生成的模板中加个判断
2.包含方法的支持可以生成template引用 名称为方法名 数据在_createData 中加命名空间

**Comment by yuche** [comment]
Template 引用的参数不能传函数，你提到的内容eslint插件文档有提到，建议去看看。

**Comment by zhoujianlin8** [comment]
如果不能使用Template 就直接输出内容  变量加命名空间

**Comment by yuche** [comment]
如果 props 传了函数而内容是函数决定那就不行，我认为以template目前提供的能力并不能实现类函数式组件。

一开始我们在Render函数里的JSX引用也是template，但是后来觉得template data必须在page data多保持一份引用有损于性能，后来改为了直接替换。

如果你觉得 template 可以不妨提一个PR.。
