### ISSUE TITLE
taro build ui, 生成的weapp组件不能自动替换alias

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#1781]
使用taro build ui，在使用alias的情况下，ts编写的组件所生成的weapp版本，没有自动替换@components。（js编写的组件情况未知）

生成后仍然为：
```javscript
import XcArrow from '@components/Arrow'
```

生成h5版本解析正常。

**Comment by shenghanqin** [comment]
试一试最新版1.3.22效果如何？
