### ISSUE TITLE
why ?  my argument ?

### ISSUE THREAD

**Issue by pssgo** [NervJS/taro#1783]
```js
// 这里可以贴代码
type Props = {

}

type State = {

}

export default class Index extends Component<Props,State> {
  constructor () {
    super(...arguments)
    this.state = { name:'Hello world!' }
  }

  // 你可以通过 bind 传入多个参数
  preventPop (name, test, e) {    //事件对象 e 要放在最后
    e.preventDefault()
  }

  render () {
    return <Button onClick={this.preventPop.bind(this, this.state.name, 'test')}>123</Button>
  }
}

```

**期望行为**
可以正常的拿到事件函数的参数

**报错信息**
![image](https://user-images.githubusercontent.com/16378134/50588444-05c64b00-0ebd-11e9-8b31-0f8551df8dd6.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
 Taro v1.2.3

  Taro CLI 1.2.3 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v10.8.0/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
    npmPackages:
      @tarojs/components: ^1.1.9 => 1.2.3
      @tarojs/mobx: ^1.2.3 => 1.2.3
      @tarojs/plugin-babel: ^1.1.9 => 1.2.3
      @tarojs/plugin-csso: ^1.1.9 => 1.2.3
      @tarojs/plugin-less: ^1.1.9 => 1.2.3
      @tarojs/plugin-uglifyjs: ^1.1.9 => 1.2.3
      @tarojs/router: ^1.1.9 => 1.2.3
      @tarojs/taro: ^1.1.9 => 1.2.3
      @tarojs/taro-alipay: ^1.1.9 => 1.2.3
      @tarojs/taro-h5: ^1.1.9 => 1.2.3
      @tarojs/taro-swan: ^1.1.9 => 1.2.3
      @tarojs/taro-weapp: ^1.1.9 => 1.2.3
      @tarojs/webpack-runner: ^1.1.9 => 1.2.3
      eslint-config-taro: ^1.1.9 => 1.2.3
      eslint-plugin-taro: ^1.1.9 => 1.2.3
 - 报错平台 : weapp

**Comment by luckyadam** [comment]
cli 和依赖都升级到最新版本

**Comment by pssgo** [comment]
#fix
