### ISSUE TITLE
setState 之后立马引用 state 会是上一次 state 的结果

### ISSUE THREAD

**Issue by jo32** [NervJS/taro#1784]
**问题描述**
setState 之后立马引用 state 会是上一次 state 的结果

**复现步骤**
[复现问题的步骤]
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class TestComp extends Component {

    constructor() {
        this.state = {
            hello: undefined
        }
    }

    componentDidMount() {
        this.setState({
            hello: 'world!'
        });
        console.log(this.state.hello);
    }

    render() {
        return <View></View>
    }
}
```

**期望行为**
console.log 的结果为 "world!"，但是结果为 undefined。

**系统信息**

  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.2.0 - ~/.nvm/versions/node/v9.2.0/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v9.2.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.0 => 1.2.0
      @tarojs/components: ^1.2.0 => 1.2.0
      @tarojs/plugin-babel: ^1.2.0 => 1.2.0
      @tarojs/plugin-csso: ^1.2.0 => 1.2.0
      @tarojs/plugin-less: ^1.2.0 => 1.2.0
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.0
      @tarojs/redux: ^1.2.0 => 1.2.0
      @tarojs/redux-h5: ^1.2.0 => 1.2.0
      @tarojs/router: ^1.2.0 => 1.2.0
      @tarojs/taro: ^1.2.0 => 1.2.0
      @tarojs/taro-alipay: ^1.2.0 => 1.2.0
      @tarojs/taro-h5: ^1.2.0 => 1.2.0
      @tarojs/taro-swan: ^1.2.0 => 1.2.0
      @tarojs/taro-weapp: ^1.2.0 => 1.2.0
      @tarojs/webpack-runner: ^1.2.0 => 1.2.0
      eslint-config-taro: ^1.2.0 => 1.2.0
      eslint-plugin-taro: ^1.2.0 => 1.2.0

**Comment by joyjoy993** [comment]
```
this.setState({
    hello: 'world!'
}, () => {
    console.log(this.state.hello);
});
```

**Comment by O3Q** [comment]
[状态更新一定是异步的](https://nervjs.github.io/taro/docs/state.html#%E7%8A%B6%E6%80%81%E6%9B%B4%E6%96%B0%E4%B8%80%E5%AE%9A%E6%98%AF%E5%BC%82%E6%AD%A5%E7%9A%84)

建议多看两眼文档，爱你哟。
