### ISSUE TITLE
dist中资源目录结构

### ISSUE THREAD

**Issue by monyee** [NervJS/taro#1787]
现在默认build后目录结构是：
![image](https://user-images.githubusercontent.com/8890905/50620119-aefe5700-0f38-11e9-909d-e104a0cc2e1b.png)

该怎么配置将js/css/lib等子目录放到一个目录下， eg:  dist下 index.html,  static目录

**Comment by luckyadam** [comment]
配置一下 webpack，请看下 taro 的编译配置文档

**Comment by monyee** [comment]
> 配置一下 webpack，请看下 taro 的编译配置文档

是否有使用其他插件的事例，比如h5中使用HtmlWebpackPlugin

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#h5webpackchain
