### ISSUE TITLE
能不能搞个wepy转taro的工具，很多老代码用wepy写的

### ISSUE THREAD

**Issue by tinybright** [NervJS/taro#1788]

**Comment by luckyadam** [comment]
这个暂时没有考虑咯，得看看需求

**Comment by yuche** [comment]
编译不仅是把 DSL A 编译成 DSL B，还得模仿特定 DSL 的一些行为，例如原生微信小程序的一些抽象度高的概念，例如 relations 和 behavior 现在也没有实现编译，wepy 这些抽象的概念更多。

就用户的数量而言，wepy 在 npm + cnpm 的下载量也不高，其实比起 taro/mpvue 都几乎没有优势，现在相对数量多也是由于存在的时间长，但从绝对数量的角度来看，他比起原生小程序还是非常小的量。

所以我认为做这个事投入是远远大于收益的，不会去做。

**Comment by mienv567** [comment]
不是因为你个需求就可以决定的。

**Comment by tinybright** [comment]
确实没啥产出，谁项目不急可以研究下，就可以引导一部分用户过来
