### ISSUE TITLE
checkbox不论是否注册onClick，仍然可以选中取消

### ISSUE THREAD

**Issue by heytheww** [NervJS/taro#1789]
**问题描述**
checkbox不论是否注册onClick，仍然可以选中取消。初次渲染，checked与数据保持统一，改变checked时，显示绿色小勾与checked对应的数据(true,false)不统一

**复现步骤**

```js
<View >
        <Checkbox  checked={false}>选中</Checkbox>
        <Checkbox style='margin-left: 20rpx' value='未选中'>未选中</Checkbox>
</View >

```

**期望行为**
使用监听方法改变checked，从而驱动checked改变视图，而不是直接操作视图

**报错信息**
🈚️
![Uploading image.png…]()

**系统信息**

Taro CLI 1.2.2 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.14.0 - /usr/local/opt/node@8/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.2 => 1.2.2
      @tarojs/components: 1.2.2 => 1.2.2
      @tarojs/mobx: 1.2.2 => 1.2.2
      @tarojs/mobx-h5: 1.2.2 => 1.2.2
      @tarojs/mobx-rn: 1.2.2 => 1.2.2
      @tarojs/plugin-babel: 1.2.2 => 1.2.2
      @tarojs/plugin-csso: 1.2.2 => 1.2.2
      @tarojs/plugin-sass: 1.2.2 => 1.2.2
      @tarojs/plugin-uglifyjs: 1.2.2 => 1.2.2
      @tarojs/rn-runner: 1.2.2 => 1.2.2
      @tarojs/router: 1.2.2 => 1.2.2
      @tarojs/taro: 1.2.2 => 1.2.2
      @tarojs/taro-alipay: 1.2.2 => 1.2.2
      @tarojs/taro-h5: 1.2.2 => 1.2.2
      @tarojs/taro-swan: 1.2.2 => 1.2.2
      @tarojs/taro-weapp: 1.2.2 => 1.2.2
      @tarojs/webpack-runner: 1.2.2 => 1.2.2
      eslint-config-taro: 1.2.2 => 1.2.2
      eslint-plugin-taro: 1.2.2 => 1.2.2
报错平台：H5

**补充信息**
🈚️

**Comment by yuche** [comment]
你需要用 `CheckboxGroup` 包住 `Checkbox`，并给 `CheckboxGroup`  绑定 `onChange` 函数

**Comment by heytheww** [comment]
其实我的原意是，Checkbox放在这里，如果我没给他绑定事件的函数，那么它的表现应该是和disabled差不多，我点了有反应，但是不会被选上
