### ISSUE TITLE
在stylus下使用css Modules报错！

### ISSUE THREAD

**Issue by panfire** [NervJS/taro#1791]
在stylus下使用css Modules
编写下图所示的css格式编译报错
![image](https://user-images.githubusercontent.com/17959015/50627353-0ff45200-0f6e-11e9-8390-616af5cc11a5.png)
![image](https://user-images.githubusercontent.com/17959015/50627381-24d0e580-0f6e-11e9-8244-d47ab25136a2.png)

**Comment by luckyadam** [comment]
background-color #ccc
