### ISSUE TITLE
taro-ui 1.5.4 版本报错

### ISSUE THREAD

**Issue by Young1993** [NervJS/taro#1797]
编译出错
🙅   Failed to compile.

./node_modules/taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
|
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">

taro 1.2.2
taro-ui 1.5.4
node v11.6.0

**Comment by loveonelong** [comment]
看这里 #1776

**Comment by loveonelong** [comment]
你要增加这个配置
https://nervjs.github.io/taro/docs/config-detail.html#h5esnextmodules
