### ISSUE TITLE
English info?

### ISSUE THREAD

**Issue by dzek69** [NervJS/taro#18]
This repo is in trending now. I liked NervJS, which is partially translated to English.

What this project is? How this differs from NervJS? Can we expect more English info in the future?

**Comment by xuan45** [comment]
Nervjs is like react and it support for ie8，but taro use jsx and it can transform to h5，APP，and WeChat mini-program，what's more，taro has the same api with react(like componentDidmount etc.)
if you are familiar with react，you can easily get it

**Comment by yuche** [comment]
Many companies in China have their own version of mini programs(a bit like Progressive web app), and Taro is a tool for unifying the development of different mini programs with API and syntax of React. 

Therefore, this is to settle a problem with Chinese characteristics, we have not plan to translate it into English.

**Comment by dzek69** [comment]
Thank you for the explaination. I heard about WeChat, I haven't heard about h5 and APP.

I think you can leave a very short explaination in README in English, so non-Chinese people looking on trending repos and other repos of `NervJS` will know what it is and that they probably don't need it if they can't understand Chinese :)

**Comment by xuan45** [comment]
h5 means html5(web app) and APP means hybird APP(like react-native) and tero will support for react-native by the end of this month，maybe a few weeks later this repo will add en-README(nervjs doesn't plan to add en-README，so it depends on other people，if i have spare time，i will create a pr for it)

**Comment by dzek69** [comment]
Just single paragraph with 2-3 sentences would be enough I think
