### ISSUE TITLE
buildDll 会导致css打包不正确

### ISSUE THREAD

**Issue by GyueGuo** [NervJS/taro#1800]
postcss-pxtransform中h5的单位和ratio被我写死为px和2，然后运行build:h5 和 dev:h5。结果，前者打包出来的css数值是后者的1/2。
经过定位，发现是@tarojs/webpack-runner/dist/index.js中的buildDll和buildProd方法会分别调用一次util/chain.js中的getModule方法，执行两次getPostcssLoader方法，导致postcssLoader.plugins中出现重复plugin。

复现方法：
1、将node_modules中的postcss-pxtransform中h5的rootValue改为2、targetUnit改为px。
2、app.less中添加page {font-size: 40px};
3、分别执行一次 npm run dev:h5  和 npm run build:h5;
4、打包出来的app.css的font-size 分别为 20px  和 10px

**Comment by Littly** [comment]
H5端后面会直接引用内置模块的源码，所以不再需要`buildDll`流程了，这个问题到时候就不会存在了。
