### ISSUE TITLE
H5端报错Failed to execute 'replaceChild' on 'Node'

### ISSUE THREAD

**Issue by schinvendy** [NervJS/taro#1804]
**问题描述**
在测试H5端代码的时候，有好几处都会报错：
```
DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
```

排查了好久，发现一种情况：

在有异步赋值的时候，对该值的判断中存在Block组件时，就会出现报错。

找出原因后就弄了一个可以复现的demo了。

**复现步骤**
```js
import Taro, { Component } from '@tarojs/taro';
import { View, Block } from '@tarojs/components';
import './index.scss';

export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  };

  state = {
    num: 1
  };

  componentDidMount() {
    console.log('did');
    setTimeout(() => {
      this.setState({
        num: 0
      });
    }, 2000);
  }

  render() {
    const { num } = this.state;
    return (
      <View className="index">
        {num === 0 && <View>已卖完</View>}
        {num > 0 && (
          <Block>
            <View>正在销售</View>
            <View>立即购买</View>
          </Block>
        )}
        {/* {num > 0 && <View>正在销售</View>} */}
      </View>
    );
  }
}
```

**报错信息**

这是一个正常运行时的截图：
![correct](https://user-images.githubusercontent.com/17189558/50673176-5356cb00-1017-11e9-9e26-95f361e3c34a.png)
![correct](https://user-images.githubusercontent.com/17189558/50673179-53ef6180-1017-11e9-931d-6fdfa5090d42.gif)

这是一个报错的截图：
![error](https://user-images.githubusercontent.com/17189558/50673183-581b7f00-1017-11e9-8985-c5d0c08e0498.png)
![error](https://user-images.githubusercontent.com/17189558/50673184-594cac00-1017-11e9-929e-d9b378585b37.gif)

**系统信息**
Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

**Comment by xoptimal** [comment]
就算没有嵌套 Block 循环加载有数据, 再次切换数据源, 返回一个空数据, 就会报这个错误~

请问你解决了吗 @schinvendy   @yuche  大胡子, 帮忙看看

**Comment by zsirfs** [comment]
fuck.一个人回复都没有了。坑

**Comment by Leridy** [comment]
fuck.已经被这玩意坑了三次了

**Comment by WhiteYasha** [comment]
fuck.遇到同样的问题，请问是怎么解决的

**Comment by Letyou** [comment]
前来考古，还是没解决。

**Comment by melunar** [comment]
解决了吗 已经closed？

**Comment by Leridy** [comment]
> 解决了吗 已经closed？

没有解决。。。我好像换了一种实现方式。。。已经忘掉怎么处理了

**Comment by melunar** [comment]
也是遇到了这个问题  代码一点点重写排查总算解决了 
系Block兼容问题，替换掉Block，用View代替 或者用View包裹Block即可
官方的解释在这里：https://taro-docs.jd.com/taro/docs/next/debug/#h5
