### ISSUE TITLE
微信小程序转taro再转百度小程序报错

### ISSUE THREAD

**Issue by scd03132506** [NervJS/taro#1807]
新建一个测试微信小程序进入目录，执行taro convert，进入taroConvert目录，执行taro build --type swan，报出如下错误。
![image](https://user-images.githubusercontent.com/17263292/50676993-557a5300-1032-11e9-8176-81f712b99e34.png)

**Comment by Pines-Cheng** [comment]
所以是：微信小程序转taro 成功了，但是 taro 转百度小程序报错？

**Comment by scd03132506** [comment]
是的

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by scd03132506** [comment]
1.2.4

**Comment by scd03132506** [comment]
已找到问题
少了一步taro update project
