### ISSUE TITLE
开发小程序插件时没有编译plugin目录

### ISSUE THREAD

**Issue by joyran** [NervJS/taro#1808]
**问题描述**
开发小程序插件时没有编译plugin目录

**复现步骤**
1. 在src目录下新增 plugin 文件夹，plugin文件夹下新增components文件夹，新增两个文件index.js和index.less,

index.js
```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'

import './index.less'

class Index extends Component {
  config = {
    navigationBarTitleText: 'Plugin'
  }

  render () {
    return (
      <View className='index'>
        <Button className='add_btn'>+</Button>
        <Button className='dec_btn'>-</Button>
        <Button className='dec_btn'>async</Button>
        <View><Text>Hello, World</Text></View>
      </View>
    )
  }
}

export default connect(state => state)(Index)
```

2. plugin文件夹下新增plugin.json文件，内容如下
```json
{
  "publicComponents": {
    "yibot": "components/index"
  }
}
```

3. 修改project.config.json文件
```json
"compileType": "plugin",
"pluginRoot": "plugin/",
```

4. 在 pages/index/index.js中引用插件
5. 运行 npm run dev:weapp，编译后的dist中没有plugin文件夹

**期望行为**
能正常开发小程序插件

Taro CLI 1.2.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.12.0 - C:\Program Files (x86)\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files (x86)\npm.CMD

**Comment by luckyadam** [comment]
我整理一下开发插件的规范吧

**Comment by joyran** [comment]
@luckyadam 非常感谢

**Comment by CrazyOctopusDan** [comment]
> @luckyadam 非常感谢

请问现在是否有规范了，我现在开发小程序插件也是十分需要这个🙏

**Comment by joyran** [comment]
@CrazyOctopusDan 官方好像还没有整理。@luckyadam

**Comment by CrazyOctopusDan** [comment]
> @CrazyOctopusDan 官方好像还没有整理。@luckyadam

那您问题是否已经解决了呢？可否告知🙏🙏🙏

**Comment by joyran** [comment]
没有呢

**Comment by CrazyOctopusDan** [comment]
> 没有呢

那也谢谢啦！

**Comment by tourze** [comment]
= = 求更新进度。。

**Comment by tourze** [comment]
求更新进度

**Comment by cuixi** [comment]
刚试了下不能编译plugin，还是不能开发小程序插件吗

**Comment by cuixi** [comment]
> **问题描述**
> 开发小程序插件时没有编译plugin目录
> 
> **复现步骤**
> 
> 1. 在src目录下新增 plugin 文件夹，plugin文件夹下新增components文件夹，新增两个文件index.js和index.less,
> 
> index.js
> 
> ```js
> import Taro, { Component } from '@tarojs/taro'
> import { View, Button, Text } from '@tarojs/components'
> import { connect } from '@tarojs/redux'
> 
> import './index.less'
> 
> class Index extends Component {
>   config = {
>     navigationBarTitleText: 'Plugin'
>   }
> 
>   render () {
>     return (
>       <View className='index'>
>         <Button className='add_btn'>+</Button>
>         <Button className='dec_btn'>-</Button>
>         <Button className='dec_btn'>async</Button>
>         <View><Text>Hello, World</Text></View>
>       </View>
>     )
>   }
> }
> 
> export default connect(state => state)(Index)
> ```
> 
> 1. plugin文件夹下新增plugin.json文件，内容如下
> 
> ```json
> {
>   "publicComponents": {
>     "yibot": "components/index"
>   }
> }
> ```
> 
> 1. 修改project.config.json文件
> 
> ```json
> "compileType": "plugin",
> "pluginRoot": "plugin/",
> ```
> 
> 1. 在 pages/index/index.js中引用插件
> 2. 运行 npm run dev:weapp，编译后的dist中没有plugin文件夹
> 
> **期望行为**
> 能正常开发小程序插件
> 
> Taro CLI 1.2.3 environment info:
> System:
> OS: Windows 10
> Binaries:
> Node: 8.12.0 - C:\Program Files (x86)\node.EXE
> Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
> npm: 6.4.1 - C:\Program Files (x86)\npm.CMD

小程序插件编译是运行以下命令：
taro build --plugin weapp
taro build --plugin weapp --watch
