### ISSUE TITLE
版本问题  Taro CLI 与本地安装的小程序框架 @tarojs/taro-weapp 版本不一致，请确保一致 Taro CLI: 1.2.3 @tarojs/taro-weapp: 1.2.1

### ISSUE THREAD

**Issue by MoonSeeing** [NervJS/taro#1810]
网上下的一个项目 版本用的是 1.2.1 和我本地装的cli版本不一致为啥会报错  不是应该向下兼容吗 ？

版本问题  Taro CLI 与本地安装的小程序框架 @tarojs/taro-weapp 版本不一致，请确保一致
Taro CLI: 1.2.3
@tarojs/taro-weapp: 1.2.1

**Comment by MoonSeeing** [comment]
总不能为了运行一个项目将cli 重装吧

**Comment by jianguo1202** [comment]
看官方文档，直接升级即可。

**Comment by luckyadam** [comment]
这个不叫不向下兼容，最好请保持版本一致

**Comment by LuckyJoker** [comment]
> 
> 
> 这个不叫不向下兼容，最好请保持版本一致

但是还是希望可以像Angular的CLI一样，项目cli版本低于全局版本时，使用项目的cli。
另外还有一个很严重的问题，使用taro update project命令更新依赖时，安装的依赖是最新的并非与cli版本保持一致，而依赖版本与cli版本不一致会造成bug。我认为CLI应该能对依赖进行控制。

**Comment by SetsunaMango** [comment]
> 网上下的一个项目版本用的是1.2.1和我本地装的cli版本不一致为啥会报错不是应该向下兼容吗？
> 
> 版本问题Taro CLI与本地安装的小程序框架@ tarojs / taro-weapp版本不一致，请确保一致
> Taro CLI：1.2.3 
> @ tarojs / taro-weapp：1.2.1
请问咋解决的 难道真的要重装吗

**Comment by luckyadam** [comment]
@LuckyJoker Angular 与 Taro 情况不同，taro 的执行依靠编译和运行时，运行时的特性依赖编译，编译出来的东西也需要运行时支持，如果你不保证编译器和运行时框架版本一致，很有可能会出问题，这种情况不叫不向下兼容，如果你觉得全部更新会出问题，可以只手工更新部分包

**Comment by LuckyJoker** [comment]
@luckyadam 我想我可能没有表达清楚我的意思。因为我看这个issue的问题和我遇到的是类似的，所以没有单开issue。我没有讨论是不是向下兼容。我的想表达的主要有两点：
1.我知道要`保证编译器和运行时框架版本一致的`，但是Angular的实现是这样的。 AngularCLI在新建项目时会在项目依赖中也安装一个当前版本的AngularCLI。这样的话，当我全局安装的CLI已经更新到新的版本时，使用ng命令，此时不会运行全局的CLI而是运行项目中的版本较旧的CLI。
2. 目前Taro的CLI会破坏`保证编译器和运行时框架版本一致`这一原则，即我使用CLI@1.2.1，如果当前Taro最新的依赖为@1.2.4，那么我运行taro update project，期望的是安装与CLI版本一致的依赖@1.2.1，而taro目前会安装@1.2.4的依赖，这样会带来不必要的耦合。

**Comment by MoonSeeing** [comment]
> > 网上下的一个项目版本用的是1.2.1和我本地装的cli版本不一致为啥会报错不是应该向下兼容吗？
> > 版本问题Taro CLI与本地安装的小程序框架@ tarojs / taro-weapp版本不一致，请确保一致
> > Taro CLI：1.2.3
> > @ tarojs / taro-weapp：1.2.1
> > 请问咋解决的 难道真的要重装吗

是滴 保持版本一致 手动将包改成与cli一致的版本，然后重装

**Comment by mengyang1229** [comment]
taro update project

**Comment by may4** [comment]
> @LuckyJoker @may4 好的，我们再认真思考一下这一块的逻辑设计~ 感谢建议~

感谢。thx

**Comment by zwblue** [comment]
> 说了半天 到底怎么解决 烦死了
试试这两步
1、taro update project
2、npm install -g @tarojs/cli

**Comment by zhang14725804** [comment]
taro update project 如何回退
