### ISSUE TITLE
看了半天也不知道该用哪个IDE开发

### ISSUE THREAD

**Issue by playscforever** [NervJS/taro#1811]
自己选吗？ sublime？ 没有最佳实践？

**Comment by Pines-Cheng** [comment]
大部分童鞋使用的是 vs code ，我更偏爱 webstorm。

**Comment by yuche** [comment]
这类问题还可以延伸更多：

* 要吃什么早餐
* 要用什么显卡
* 要找什么样的女朋友
* 去哪里开房

每个人的喜好和开发模式各不相同，他们选择的原因也各不相同。我觉得最好的选择是，你想怎么样就怎么样。

**Comment by playscforever** [comment]
@yuche 我也是醉了，对于没接触过的来说，选错ide开发会浪费多少时间你知道吗

**Comment by yuche** [comment]
开了这个 issue，楼下各种回复都可以想到：

1楼: vscode + 1
2楼: webstorm + 1
3楼: vscode + 2
4楼: vscode + 3
5楼: vscode + 4
6楼: vscode + 10086
...
101楼 webstorm + 2
102楼 webstorm + 3
103楼 webstorm + 4
104楼 webstorm + 10087
...
201楼 sublime + 2
202楼 sublime + 3
203楼 sublime + 4
204楼 sublime + 5
...
250楼: 楼上 too young 啊，vim 才是神器，谁用谁知道
251楼：vim 傻逼吧，你懂不懂有一种信念叫 emacs
252楼：楼上都在装逼，Visual Stuido 宇宙第一 IDE 才是真正名不虚传，真正的物超所值的效率工具

你随便去个程序员论坛找一下就好了，这种帖子太多了。

**Comment by playscforever** [comment]
但事实是什么呢，对于Taro来说，就是应该用vscode，现实也是大多数都是用的vscode，如果官方能在显眼的地方推荐一下，真的可以避免很多新人走很多弯路啊。

抱歉不应该抬杠。。。

**Comment by yuche** [comment]
其实 webstorm 也很适合开发 Taro，不过我自己也是用 vscode。
对于 JavaScript 开发大部分编辑器其实充分配置之后开发体验都会差得太远，只是哪个细节更好或者生态更丰富而已。

我们可能会考虑加上主流编辑器的配置指南。

**Comment by Lionad-Morotar** [comment]
vscode 配合自定义 snippets 业务肝起来不要太快 hhh

**Comment by zaaack** [comment]
强烈建议 vsc 作为 taro 的官方推荐（逃

**Comment by howewang** [comment]
官方还是应该推荐一个IDE的，不然很多人安装完cli生成一个项目之后就会开始蒙圈，我用什么写代码。。。。那么多IDE谁知道它到底支持哪个。。。。
