### ISSUE TITLE
Taro1.2.4版H5端Input组件问题

### ISSUE THREAD

**Issue by schinvendy** [NervJS/taro#1819]
**问题描述**
在Taro 1.2.3版本下没有出现，升级1.2.4后，Input组件类型为number或者digit时输入就会出现报错。

> Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

**复现步骤**

测试Demo

```js
import Taro, { Component } from '@tarojs/taro';
import { View, Input, Text } from '@tarojs/components';
import './index.scss';

export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  };

  state = {
    text: 'text',
    number: 1,
    digit: 2.2
  };

  componentDidMount() {}

  onInput(type, e) {
    console.log('[type]', type, ', [e detail value]', e.detail.value);
    this.setState({
      [type]: e.detail.value
    });
  }

  render() {
    return (
      <View className="index">
        <Text>获取输入值:{this.state.text}</Text>
        <Input type="text" placeholder="输入同步到 view 中" onInput={this.onInput.bind(this, 'text')} />
        <Text>数字输入的 input:{this.state.number}</Text>
        <Input type="number" placeholder="这是一个数字输入框" onInput={this.onInput.bind(this, 'number')} />
        <Text>带小数点的 input:{this.state.digit}</Text>
        <Input type="digit" placeholder="带小数点的数字键盘" onInput={this.onInput.bind(this, 'digit')} />
      </View>
    );
  }
}
```

**报错信息**

Taro v1.2.3 版本下:
![1 2 3ver](https://user-images.githubusercontent.com/17189558/50720022-4520b180-10e0-11e9-9982-183d97649b30.gif)

Taro v1.2.4 版本下:
![1 2 4ver](https://user-images.githubusercontent.com/17189558/50720025-4baf2900-10e0-11e9-9da7-8e965d91d67d.gif)

**系统信息**
出现报错的环境：
> 👽 Taro v1.2.4
  Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

**Comment by jinjinjin0731** [comment]
已修复
