### ISSUE TITLE
函数传参无法取到

### ISSUE THREAD

**Issue by hyyqcweb** [NervJS/taro#1820]
**问题描述**
事件绑定传参, 取不到参数, 取到的是 arguments对象

**复现步骤**
```js
handleClick = (item) => {
    console.log(item);
  };

render() {
    return (
      <View>
        {[1,2].map((t, r) => (
          <Button key={r} onClick={this.handleClick.bind(this, t)}>
            {t}
          </Button>
        ))}
      </View>
    )
  }
```

**期望行为**
可以正常的拿到事件函数的参数

**报错信息**
![image](https://user-images.githubusercontent.com/17583072/50721055-866e8c80-10f3-11e9-99ca-9965527660cc.png)

**系统信息**
![image](https://user-images.githubusercontent.com/17583072/50721065-a9993c00-10f3-11e9-8ed6-67a563ddd936.png)

 - 报错平台: **weapp**

**补充信息**
最新依赖: 
![image](https://user-images.githubusercontent.com/17583072/50721075-cfbedc00-10f3-11e9-8179-c8f3fb55f407.png)

**Comment by ZhiGang-Fang** [comment]
我更新完，也需要上面的问题，

```
onClick={this.handleClick.bind(this, 1)} 

handleClick = (type) => {console.log(type)}
```
<img width="739" alt="wx20190105-165811 2x" src="https://user-images.githubusercontent.com/24228407/50722572-16b8cb80-110c-11e9-8404-563aebd2b85c.png">

**Comment by hyyqcweb** [comment]
是的, 我什么方法都试了, 比如删除 node_modules , npm update, 还是取不到正常的值

**Comment by Chen-jj** [comment]
@hyyqcweb @ZhiGang-Fang Taro 1.2.4 版本上尝试，没有问题，能正确取值。

你们的问题肯定是 CLI 和依赖版本不一致导致的，可以删掉 node_modules 后手动 npm install 试试。

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class PageView extends Component {
  handleClick = (item) => {
    console.log(item)
  }

  render() {
    return (
      <View>
        {[1,2].map((t, r) => (
          <View key={r} onClick={this.handleClick.bind(this, t)}>
            {t}
          </View>
        ))}
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/50822520-e1f77f00-136c-11e9-93ed-84bd1c97ebd4.png)

**Comment by wswax** [comment]
这个问题怎么解决的呢？我用的taro版本是1.2.12

**Comment by hyyqcweb** [comment]
@wswax  要么升级taro版本依赖(必须统一), 要么降级taro版本(我是降级处理了)

**Comment by wswax** [comment]
@hyyqcweb 嗯我刚刚升级了。
目前是这样子，可以了。



Taro v1.2.13


  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.0 => 1.2.12
      @tarojs/components: ^1.2.0 => 1.2.12
      @tarojs/plugin-babel: ^1.2.0 => 1.2.12
      @tarojs/plugin-csso: ^1.2.0 => 1.2.12
      @tarojs/plugin-sass: ^1.2.0 => 1.2.12
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.12
      @tarojs/redux: ^1.2.0 => 1.2.12
      @tarojs/redux-h5: ^1.2.0 => 1.2.12
      @tarojs/router: ^1.2.0 => 1.2.12
      @tarojs/taro: ^1.2.0 => 1.2.12
      @tarojs/taro-alipay: ^1.2.0 => 1.2.12
      @tarojs/taro-h5: ^1.2.0 => 1.2.12
      @tarojs/taro-swan: ^1.2.0 => 1.2.12
      @tarojs/taro-tt: ^1.2.0 => 1.2.12
      @tarojs/taro-weapp: ^1.2.0 => 1.2.12
      @tarojs/webpack-runner: ^1.2.0 => 1.2.12
      eslint-config-taro: ^1.2.0 => 1.2.12
      eslint-plugin-taro: ^1.2.0 => 1.2.12
      nervjs: ^1.3.9 => 1.3.12

**Comment by Chen-jj** [comment]
@wswax CLI 和依赖要保持一致，不然又可能出现其它问题。你现在分别是 1.2.13 和 1.2.12

**Comment by wswax** [comment]
@Chen-jj 嗯，多谢提醒。
刚重新安装了一下。
Taro v1.2.13


  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.0 => 1.2.13
      @tarojs/components: ^1.2.0 => 1.2.13
      @tarojs/plugin-babel: ^1.2.0 => 1.2.13
      @tarojs/plugin-csso: ^1.2.0 => 1.2.13
      @tarojs/plugin-sass: ^1.2.0 => 1.2.13
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.13
      @tarojs/redux: ^1.2.0 => 1.2.13
      @tarojs/redux-h5: ^1.2.0 => 1.2.13
      @tarojs/router: ^1.2.0 => 1.2.13
      @tarojs/taro: ^1.2.0 => 1.2.13
      @tarojs/taro-alipay: ^1.2.0 => 1.2.13
      @tarojs/taro-h5: ^1.2.0 => 1.2.13
      @tarojs/taro-swan: ^1.2.0 => 1.2.13
      @tarojs/taro-tt: ^1.2.0 => 1.2.13
      @tarojs/taro-weapp: ^1.2.0 => 1.2.13
      @tarojs/webpack-runner: ^1.2.0 => 1.2.13
      eslint-config-taro: ^1.2.0 => 1.2.13
      eslint-plugin-taro: ^1.2.0 => 1.2.13
      nervjs: ^1.3.9 => 1.3.12
