### ISSUE TITLE
Taro对象在mobx方法中调用，发生异常

### ISSUE THREAD

**Issue by shuiruohanyu** [NervJS/taro#1826]
定义一个工具类 在组件中引用此组件，工具类中使用了Taro的API ，

```javascript
import  Taro from '@tarojs/taro';

  //获取所有的菜品数量 及价格 
export  function  getAllFoodInfo(){
	let  allPrice=0;//总价格
	let allNum=0;
	let store= Taro.getStorageSync(foodKey);//取菜品信息
	if(store){
		//对store进行遍历
		Object.keys(store).map((key)=>{
			if(store[key]){
			   allPrice+=store[key].price*store[key].Num;
			   allNum+=store[key].Num;
			}
		})
	}
	return {allPrice,allNum}
}
```

在组件中调用该方法 ok，

接入mobx，在组件中调用  this.props.对象.方法   该方法中 调用了 工具类的方法  

如   

```javascript
import  {observable} from  'mobx';
import  {getAllFoodInfo} from  './common';
export default  observable({
    allObj:{},
    update(){
        this.allObj=getAllFoodInfo();
    }
})

```
 
但是调用时 出现异常 提示 taro不存在 getStorageSync方法  通过监视发现  同一个方法 组件中调用和mobx调用时  Taro的对象不同，此问题 不知道是何种原因所致

**Comment by shuiruohanyu** [comment]
代码中是个示例页面，进行依赖安装之后 ，启动，点击左侧的分类，右侧的分类数据会发生变化，此时进行了mobx中对象方法调用，会报出一个错误，提示taro无对应方法 ，


shuiruohanyu@foxmail.com
 
发件人： Li,Weitao
发送时间： 2019-01-13 23:26
收件人： NervJS/taro
抄送： shuiruohanyu; Author
主题： Re: [NervJS/taro] Taro对象在mobx方法中调用，发生异常 (#1826)
根据你提供的代码片段未能复现问题，能否提供一个可以复现的小 demo

**Comment by nanjingboy** [comment]
@shuiruohanyu 不好意思，能否给一个具体的 demo 呢？无法复现呢

**Comment by shuiruohanyu** [comment]
代码中是个示例页面，进行依赖安装之后 ，启动，点击左侧的分类，右侧的分类数据会发生变化，此时进行了mobx中对象方法调用，会报出一个错误，提示taro无对应方法 ，




shuiruohanyu@foxmail.com
 
发件人： taro-bot[bot]
发送时间： 2019-01-06 11:41
收件人： NervJS/taro
抄送： shuiruohanyu; Author
主题： Re: [NervJS/taro] Taro对象在mobx方法中调用，发生异常 (#1826)
欢迎提交 Issue~
如果你提交的是 bug 报告，请务必遵循 Issue 模板的规范，尽量用简洁的语言描述你的问题，最好能提供一个稳定简单的复现。????????????
如果你的信息提供过于模糊或不足，或者已经其他 issue 已经存在相关内容，你的 issue 有可能会被关闭。
Good luck and happy coding~

**Comment by nanjingboy** [comment]
@shuiruohanyu 你的页面逻辑是什么样子呢？

**Comment by nanjingboy** [comment]
@shuiruohanyu 根据你目前提供的信息并不能重现你所描述的问题，为了节约大家的时间，请提供完整可复现的 demo 出来。 谢谢 🙏

@luckyadam

**Comment by shuiruohanyu** [comment]
由于发的代码版本过早  更新到最新版本 发现问题已经解决  可以将此问题关闭了 谢谢 



shuiruohanyu@foxmail.com
 
发件人： Tom Huang
发送时间： 2019-03-26 13:09
收件人： NervJS/taro
抄送： shuiruohanyu; Mention
主题： Re: [NervJS/taro] Taro对象在mobx方法中调用，发生异常 (#1826)
@shuiruohanyu 根据你目前提供的信息并不能重现你所描述的问题，为了节约大家的时间，请提供完整可复现的 demo 出来。 谢谢 ????
@luckyadam
