### ISSUE TITLE
h5环境下 storage封装问题。

### ISSUE THREAD

**Issue by treesea2014** [NervJS/taro#1827]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里是你们h5 setStorageSync 的实现，
function setStorageSync (key, data = '') {
  if (typeof key !== 'string') {
    console.error(getParameterError({
      name: 'setStorage',
      correct: 'String',
      wrong: key
    }))
    return
  }

  const type = typeof data
  let obj = {}

  if (type === 'symbol') {
    obj = { data: '' }
  } else {
    obj = { data }
  }
  localStorage.setItem(key, JSON.stringify(obj))
}

function getStorageSync (key) {
  if (typeof key !== 'string') {
    console.error(getParameterError({
      name: 'getStorage',
      correct: 'String',
      wrong: key
    }))
    return
  }

  let res = getItem(key)
  if (res.result) return res.data

  return ''
}

function getItem (key) {
  let item
  try {
    item = JSON.parse(localStorage.getItem(key))
  } catch (e) {}

  // 只返回使用 Taro.setStorage API 存储的数据
  if (item && typeof item === 'object' && item.hasOwnProperty('data')) {
    return { result: true, data: item.data }
  } else {
    return { result: false }
  }
}

```

**期望行为**
h5环境，访问同域名下的缓存，别人localstorage.setItem("key","1")

我使用 Taro.getStorageSync("key") 拿不到值1，

如果是 localstorage.setItem("key",{data:"1"})才可以，因为你们value的结构是{data:value}

为什么要多一层data？

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by loveonelong** [comment]
> Taro 的 API 包括 Taro 内置提供的 API 以及对小程序的端能力 API 的封装。
>其中对小程序的端能力 API 的封装，主要会基于微信小程序的 API 规范，对于其他小程序类似的 API，会在 Taro 中适配为小程序 API 的规范格式，并且都挂载在 Taro 命名空间下。

请参考Taro Api说明[https://nervjs.github.io/taro/docs/api-desc.html](https://nervjs.github.io/taro/docs/api-desc.html)
Taro storage Api [https://nervjs.github.io/taro/docs/native-api.html#tarosetstorageobject](https://nervjs.github.io/taro/docs/native-api.html#tarosetstorageobject)

微信小程序storage文档 [https://developers.weixin.qq.com/miniprogram/dev/api/wx.setStorage.html](https://developers.weixin.qq.com/miniprogram/dev/api/wx.setStorage.html)
