### ISSUE TITLE
taro的使用程序员们有没有兴趣创业

### ISSUE THREAD

**Issue by mienv567** [NervJS/taro#1829]
有没有愿意利用taro开发前端的朋友们，后端已写好。我缺前端，有兴趣的联系

**Comment by westeast** [comment]
> 有没有愿意利用taro开发前端的朋友们，后端已写好。我缺前端，有兴趣的联系

创业哪有这么简单，你搞后端再来个前段就可以创业了，哈~

**Comment by angerpeanut** [comment]
加v聊聊：2290791526，备注github
