### ISSUE TITLE
build 后 wxml 内容压缩处理不了换行

### ISSUE THREAD

**Issue by NewsNIng** [NervJS/taro#1831]
**问题描述**
npm run build:weapp
wxml 内容压缩后 没处理换行
**复现步骤**
[复现问题的步骤]
```html
<Text>
    Taro
<Text>
```
以上JSX代码在npm run dev:weapp 时
wxml会处理为
```html
<text>Taro<text>
```
然后执行 npm run build:weapp
反而wxml压缩后没处理换行，即
```html
<text>
    Taro
<text>
```
导致文字下坠，样式错落。

**期望行为**
build 后可以正确处理 换行

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.2.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/components: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/plugin-babel: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/plugin-csso: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/plugin-sass: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/plugin-uglifyjs: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/redux: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/router: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/taro: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/taro-alipay: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/taro-h5: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/taro-weapp: 1.2.0-beta.10 => 1.2.0-beta.10
      @tarojs/webpack-runner: 1.2.0-beta.10 => 1.2.0-beta.10
      eslint-config-taro: 1.2.0-beta.10 => 1.2.0-beta.10
      eslint-plugin-taro: 1.2.0-beta.10 => 1.2.0-beta.10
    npmGlobalPackages:
      typescript: 3.0.3

 - 操作系统: [e.g. Mac]
 - Node.js 版本 [e.g. v10.0.6]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
在 JSX 中 children 内的换行都是没有意义的：

https://stackblitz.com/edit/react-8ympdt?file=index.js
https://github.com/jsx/JSX
http://www.ecma-international.org/publications/files/ECMA-ST-WITHDRAWN/Ecma-357.pdf

如果你需要换行应该手动加 '\n'

**Comment by schinvendy** [comment]
这个问题 #1609 有提到，他们在1.2.1版本解决了

**Comment by yuche** [comment]
> @yuche JSX 不敏感，但小程序内对换行是敏感的，所以两者行为的不一致导致了一些麻烦
> 
> ```
> <text>1
> 2</text>
> ```
> 
> 这样的代码会换行显示
> 
> ```
> 1
> 2
> ```
> 而现在 Taro 的编译产物中会自动给 wxml 中较长的代码进行折行，所以如果我编写
> 
> ```
> <Text>这里有一段很长很长很长的文字<Text className="bold">加粗</Text>aaaaaaa</Text>
> ```
> 
> 会被转译为
> 
> ```
> <text>这里有一段很长很长很长的文字
>   <text class="bold">加粗</text>aaaaaaa</text>
> ```
> 
> 预期显示不换行，实际显示了两行内容。

如果对小程序单独处理拿其它端单独出来又不在 Taro，跨端就无从谈起了，既然使用了 JSX 就得遵守 JSX 的语法规范。在react 和 web 端 应该如何表现，那小程序也应该如此。

从下个版本开始 Text 组件内内容都会编译为一行，表现为何 build 模式出来的代码一致。
