### ISSUE TITLE
css module新增样式类无法时时更新问题

### ISSUE THREAD

**Issue by FaureWu** [NervJS/taro#1833]
**问题描述**
css module新增样式类无法时时更新问题

**复现步骤**
1. clone https://github.com/FaureWu/taro-scss-variable-issue
2. yarn && yarn dev:weapp运行项目
3. 打开文件src/pages/index.js，新增styles.text样式类:
```js
<View className={styles.index}>
  <Text className={styles.text}>Hello world!</Text>
  <Demo data={this.state.data} />
</View>
```
4. 打开文件src/pages/index.scss，新增.text
```css
.index {
  .text {
     color: red;
  }
}
```
5.预览项目，Hello world!未呈现红色，需再次编辑index.js文件可生效

**期望行为**
新增的样式，在样式表中新增时，时时更新，无需重新编辑组件

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Mac]
 - Taro 版本 [1.2.1]
 - Node.js 版本 [v8.11.3]
 - 报错平台 [weapp, h5未测试]

**补充信息**
无

**Comment by luckyadam** [comment]
Duplicate of #1388

**Comment by luckyadam** [comment]
和 #1388 重复了，正在处理，先把这个关了
