### ISSUE TITLE
小程序Input组件清除不了内容

### ISSUE THREAD

**Issue by sage-z** [NervJS/taro#1837]
1. onInput 事件中返回覆盖不了input控件里的值
2. onInput 事件中没有confirm类型，用来判断输入完成后清空文字

```js

import {  View,  Input } from "@tarojs/components";

  onConfirm = data => {
    // const { value } = data.detail
    console.log(data)
    return ""
    // this.props.dispatch({type:'dot/add', payload: value})

  }

  onInput (e) {
    console.log(e)
    return ""
  }

  render() {
    return (
<Input 
       confirmHold 
       onInput={this.onInput.bind(this)} 
       focus={this.state.focus} 
       onFocus={this.onFocus.bind(this)} 
       onConfirm={this.onConfirm.bind(this)} 
      /> )}
```

👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.4 => 1.2.4
      @tarojs/cli: 1.2.4 => 1.2.4
      @tarojs/components: 1.2.4 => 1.2.4
      @tarojs/plugin-babel: 1.2.4 => 1.2.4
      @tarojs/plugin-csso: 1.2.4 => 1.2.4
      @tarojs/plugin-sass: 1.2.4 => 1.2.4
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4
      @tarojs/redux: 1.2.4 => 1.2.4
      @tarojs/router: 1.2.4 => 1.2.4
      @tarojs/taro: 1.2.4 => 1.2.4
      @tarojs/taro-h5: 1.2.4 => 1.2.4
      @tarojs/taro-weapp: 1.2.4 => 1.2.4
      @tarojs/webpack-runner: 1.2.4 => 1.2.4
      eslint-config-taro: 1.2.4 => 1.2.4
      eslint-plugin-taro: 1.2.4 => 1.2.4
    npmGlobalPackages:
      typescript: 3.1.3

**Comment by Zegapaiz** [comment]
需要什么补充信息吗

**Comment by Chen-jj** [comment]
@sage-z 

1. CLI 和依赖都升级到最新版再试试，最新版本上可以成功清除。

2. 没看懂什么是 “onInput 事件中没有confirm类型”
