### ISSUE TITLE
taro转微信小程序，Audio组件安卓机使用正常，苹果机没法使用，api也不正常，微信原生都是正常啊

### ISSUE THREAD

**Issue by wnuoer** [NervJS/taro#1838]
**问题描述**
[问题描述：taro转微信小程序，Audio组件安卓机使用正常，苹果机没法使用，api也不正常，微信原生都是正常啊]

**复现步骤**
[复现问题的步骤]
1. taro转微信小程序，Audio组件安卓机使用正常，苹果机没法使用，api也不正常，微信原生都是正常啊

[或者可以直接贴源代码，能贴文字就不要截图]

```js
<Audio
  src='http://www.ytmp3.cn/down/56520.mp3'
  controls
  autoplay={false}
/>

或者
const audioCtx = Taro.createInnerAudioContext()
    audioCtx.src = 'https://audio.xmcdn.com/group54/M05/F5/F9/wKgLfVwsr6STz8WrABhoG4yY-AE258.m4a'
    audioCtx.autoplay = true
    audioCtx.onPlay(()=>{
      console.log('开始播放')
    })

```

**期望行为**
[苹果机能正常使用这个组件]

**报错信息**

[没有报错，苹果机点击没反应]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - Taro 版本 [e.g. v1.2.4]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
请阅读一下
https://segmentfault.com/a/1190000015584831

**Comment by wnuoer** [comment]
`    const audioCtx = Taro.createInnerAudioContext()
    audioCtx.src = 'https://audio.xmcdn.com/group54/M05/F5/F9/wKgLfVwsr6STz8WrABhoG4yY-AE258.m4a'
    audioCtx.autoplay = true
    audioCtx.obeyMuteSwitch = false
    audioCtx.onPlay(()=>{
      console.log('开始播放')
    })`
这个不行呢

**Comment by wnuoer** [comment]
> 请阅读一下
> https://segmentfault.com/a/1190000015584831

这个还是不行啊

**Comment by hufans** [comment]
> > 请阅读一下
> > https://segmentfault.com/a/1190000015584831
> 
> 这个还是不行啊

我试过了不行
