### ISSUE TITLE
Taroui自定义主题版本测试Button在H5平台报错

### ISSUE THREAD

**Issue by qiuhd2015** [NervJS/taro#1839]
**问题描述**
Taroui自定义主题版本测试Button在H5平台报错，在微信开发者工具中显示正常

**复现步骤**
[复现问题的步骤]
1.taro inint myapp
2.npm install taro-ui@next
3.在项目config增加以下配置
  h5: {
   esnextModules: ['taro-ui']
  }
4.在index.js 文件 增肌Button 相关代码
  import { AtButton } from 'taro-ui'
  <AtButton type='primary'>按钮文案</AtButton>

5.在index.scss 文件导入 @import "~taro-ui/dist/style/index.scss";

**期望行为**
正常显示button

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

开始编译项目 taro-qnetc
创建  发现文件  src\app.js
创建  发现文件  src\app.scss
创建  发现文件  src\index.html
创建  发现文件  src\pages\index\index.js
创建  发现文件  src\pages\index\index.scss

�   Failed to compile.

./node_modules/_taro-ui@2.0.0-beta.1@taro-ui/dist/h5/components/button/index.js
109:18
Module parse failed: Unexpected token (109:18)
You may need an appropriate loader to handle this file type.
|     let component;
|     if (loading) {
>       component = <View className="at-button__icon"><AtLoading color={loadingC
olor} size={loadingSize} /></View>;
|       rootClassName.push('at-button--icon');
|     }

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
  Taro v1.2.3
  Taro CLI 1.2.3 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
 - Taro 版本 [1.2.3]
 - Taro UI 版本 [2.0.0-beta.1]
 - 报错平台 [h5]

**Comment by qiuhd2015** [comment]
> 能否提供一个测试项目我们看看
安装taro-ui 快速上手文档一步一步创建的,

**Comment by luckyadam** [comment]
@tarojs/webpack-runner 版本多少
