### ISSUE TITLE
请问有没有兼容小程序跟h5的下拉刷新和上拉加载

### ISSUE THREAD

**Issue by isTeemo** [NervJS/taro#1841]
请问有没有兼容小程序跟h5的下拉刷新和上拉加载，用滚动监听做的体验实在是不好

**Comment by jinjinjin0731** [comment]
h5 的scrollVIew 打算做成 iScroll 那种形式了，到时候可以暴露相关的 api 在 h5 端做一下兼容。预计 2 月底

**Comment by isTeemo** [comment]
好吧   能快点吗   项目急上线    不行就得换框架了

**Comment by jinjinjin0731** [comment]
h5 目前需要你自己做滚动监听的兼容。小程序直接有。 使用 scrollView 组件的话 ，目前已经有 onScrollToUpper 和 onScrollToLower 事件。 这两个是小程序和 h5 都有，如果这都不满足你需要的条件，那么要么你自己写做兼容 要么你自己换一个框架吧

**Comment by jyjey** [comment]
> h5 的scrollVIew 打算做成 iScroll 那种形式了，到时候可以暴露相关的 api 在 h5 端做一下兼容。预计 2 月底。 小程序目前可以正常使用

请问这个兼容到H5了吗

**Comment by jyjey** [comment]
@jinjinjin0731

**Comment by jinjinjin0731** [comment]
@jyjey 正在搞。 你可以暂时使用 scrollVIew 的 onScrollToUpper 和 onScrollToLower 事件

**Comment by jyjey** [comment]
好的

**Comment by xoptimal** [comment]
都7月份了~  搞好了吗 @jinjinjin0731

**Comment by BinZhiZhu** [comment]
@jinjinjin0731  希望提供个scrollVIew实现h5下拉刷新、加载的demo

**Comment by cnscorpions** [comment]
+ 1

**Comment by chunmu** [comment]
有大大搞好了吗  想用
