### ISSUE TITLE
setState数据无更新无法重新渲染吗？

### ISSUE THREAD

**Issue by xuxiaoxiao312** [NervJS/taro#1843]
**问题描述**
在用小程序movable-area 完成一个拖拽排序的组件，希望movable-view在拖拽结束后回到设置的位置，但如果结束坐标与之前的坐标一致，setState后页面不会更新

```
this.state={
imageList:['test1','test2']
}
componentDidMount(){
    this.calcImage()
}
calcImage(){
     let images = Array.from(this.state.imageList,((el,index)=>{
           return {
                 top:index * 70,
                left:0
           }
}))
}
<MovableArea>
	{imageList.map((el, i) => {
	      return (
			<MovableView key={i}
					direction='all'
					x={el.left}
					y={el.top}>
                                          <VIew onTouchEnd={this.calcImage.bind(this, i)}>{el.src}</VIew>
			</MovableView>
</MovableArea>

```

**期望行为**
有什么办法可以强制重新渲染页面吗？原生小程序是只要setData就会触发更新，Taro似乎做了判断

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.2.0

  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by yuche** [comment]
`this.forceUpdate()`

**Comment by javahuang** [comment]
@xuxiaoxiao312 你好，你的这个问题解决了吗？我也遇到了，通过 setState 设置 MovableView 的 x,y 不渲染

**Comment by xuxiaoxiao312** [comment]
> @xuxiaoxiao312 你好，你的这个问题解决了吗？我也遇到了，通过 setState 设置 MovableView 的 x,y 不渲染

没有，一直没给回复

**Comment by xuxiaoxiao312** [comment]
> @xuxiaoxiao312 你好，你的这个问题解决了吗？我也遇到了，通过 setState 设置 MovableView 的 x,y 不渲染

我自定义了一个moveTimes的变量，每次moveEnd的时候加一，记录移动的次数，在计算x,y的时候加上 moveTimes%2，强行让x,y每次都不一样就可以重新渲染了，权宜之计。。。

**Comment by danieltao1993** [comment]
我也遇到了，setState不执行，回调也没有

**Comment by rwson** [comment]
我也是，setState更新

**Comment by seekcx** [comment]
+1 也是这个问题，scrollIntoView 如果值和上次一样就不跳转了，用户有可能拖动到了别的位置，因此即便 scrollIntoView 没改变，也应该执行跳转，目测有点优化过度了，是否可以通过更新其它无关属性来触发更新？

**Comment by seekcx** [comment]
@yuche `forceUpdate` 看介绍应该是放在组件中，组件代码是封装好的，怎么调用呢？

**Comment by hangbale** [comment]
fdsfsd
