### ISSUE TITLE
taro依赖node-sass

### ISSUE THREAD

**Issue by harrydengchao** [NervJS/taro#1845]
**问题描述**
taro init 初始化时，选择`Less`，安装包里面依然依赖了 `node-sass`

**复现步骤**
1. taro init myapp
2. 选择 Less

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
选择使用 `Less`后，安装包不再依赖 `node-sass`

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v1.2.4]
 - Node.js 版本 [e.g. v8.12.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
本人的开发局限在内网环境，无法安装`node-sass`的依赖项

**Comment by yuche** [comment]
Duplicate of #1529
