### ISSUE TITLE
mobx-state-tree的flow使用问题

### ISSUE THREAD

**Issue by blooddrunk** [NervJS/taro#1847]
使用[mobx-state-tree](https://github.com/mobxjs/mobx-state-tree)进行[异步](https://github.com/mobxjs/mobx-state-tree/blob/master/docs/async-actions.md#asynchronous-actions-and-middleware)操作时(小程序端)有如下错误：

```
mobx-state-tree.js:2910 Uncaught (in promise) ReferenceError: setImmediate is not defined
    at next (mobx-state-tree.js:2910)
    at onFulfilled (mobx-state-tree.js:2886)
    at <anonymous>
```

https://github.com/mobxjs/mobx-state-tree/blob/02ded32c8bfa70e13091ed3967466c6a0d6493ee/packages/mobx-state-tree/src/core/flow.ts#L138

请问如何为`setImmediate`添加polyfill，直接在入口文件中import似乎无效。

**Comment by luckyadam** [comment]
你是怎么加 polyfill 的

**Comment by blooddrunk** [comment]
类似[@tarojs/async-wait](https://github.com/NervJS/taro/blob/master/packages/taro-async-await/index.js) 加个`setImmediate` 方法, 在入口文件引入。 另外试了下配置文件babel `plugins`添加 `babel-plugin-transform-runtime` 也不行
