### ISSUE TITLE
scss中:export后，RN端运行出错

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#1848]
为了方便在scss和js中共享变量，我在scss中使用:export来导出一些变量给JS使用。

然后在RN端运行遇到一些问题，一进入模拟器就会报错：

![image](https://user-images.githubusercontent.com/13899502/50786448-92726e00-12ee-11e9-8414-968dc6cb7dea.png)

![image](https://user-images.githubusercontent.com/13899502/50786463-9b633f80-12ee-11e9-9c75-3b240ddcb27e.png)

![image](https://user-images.githubusercontent.com/13899502/50786492-a9b15b80-12ee-11e9-8ec8-ddd84575c1ce.png)

**系统信息**

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
**补充信息**

看页面提示，是因为StyleSheet中创建的样式，不是对象格式

**Comment by Pines-Cheng** [comment]
sass 有 :export  用法吗？我在官方文档里面没有找到啊。

**Comment by tourze** [comment]
> export

参考 https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript
其实我也没看过文档。。。是在一些开源项目中看到有类似用法

**Comment by Pines-Cheng** [comment]
这种实现是借助了 Webpack 和 CSS modules 的能力。

**Comment by tourze** [comment]
> 这种实现是借助了 Webpack 和 CSS modules 的能力。

是的。。。现在怎么解决这个呢？

**Comment by tourze** [comment]
在实际进行RN开发中，scss变量作为theme参数，在js中共享这种场景很难避免啊。。。能否修复下这个问题？ https://til.hashrocket.com/posts/sxbrscjuqu-share-scss-variables-with-javascript

**Comment by tourze** [comment]
现在官方已经fork了css-react-native，应该是能解决这种问题了？
