### ISSUE TITLE
borderTopStyle/borderRightStyle/borderBottomStyle/borderLeftStyle在RN中的支持

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#1849]
**问题描述**
在RN中使用 border-bottom: 1px solid #fff; 会报错，因为RN的StyleSheet不支持这种写法。
另外阅读文档，发现RN的border只支持borderStyle，不支持具体方向分别设置。
在看taro-ui源码时得知scss是可以使用 `@if` 这种表达式的。所以是否能在scss中注入类似 process.env.TARO_ENV 的变量？这样就可以让开发者在scss中做简单的控制。

**系统信息**
  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by Pines-Cheng** [comment]
设置具体方向的border，可以这样写：

```css
  border-width: 0 0 2px 0;
  border-bottom-color: #dddddd;
  border-style: solid;
```

**Comment by tourze** [comment]
> 设置具体方向的border，可以这样写：
> 
> ```css
>   border-width: 0 0 2px 0;
>   border-bottom-color: #dddddd;
>   border-style: solid;
> ```

有办法在scss中判断当前环境的吗？例如同一个选择器，在RN中我用 border-style: solid; 在其他环境用 border-right-style: solid;

**Comment by Pines-Cheng** [comment]
这个能满足你需求吗：

`/*postcss-pxtransform rn eject enable*/ `与` /*postcss-pxtransform rn eject disable*/` 中间的代码， 在编译成 RN 端的样式的时候，会被删除。建议将 RN 不支持的但 H5 端又必不可少的样式放到这里面。如：样式重制相关的代码。

```css
/*postcss-pxtransform rn eject enable*/

.test {
  color: black;
}

/*postcss-pxtransform rn eject disable*/
```

**Comment by tourze** [comment]
> 这个能满足你需求吗：
> 
> `/*postcss-pxtransform rn eject enable*/ `与` /*postcss-pxtransform rn eject disable*/` 中间的代码， 在编译成 RN 端的样式的时候，会被删除。建议将 RN 不支持的但 H5 端又必不可少的样式放到这里面。如：样式重制相关的代码。
> 
> ```css
> /*postcss-pxtransform rn eject enable*/
> 
> .test {
>   color: black;
> }
> 
> /*postcss-pxtransform rn eject disable*/
> ```

我觉得可行。如果方便的话，其他端最好也有这种注释，如支付宝和头条
