### ISSUE TITLE
请求接口的方法能出一个官方的么

### ISSUE THREAD

**Issue by nm-1216** [NervJS/taro#185]
![image](https://user-images.githubusercontent.com/16759471/41811302-6f29ea36-773f-11e8-81ea-4a45eecc6323.png)

**Comment by nm-1216** [comment]
我封得不好，可我要用啊，每个请求独立写 token 太麻烦了

**Comment by nm-1216** [comment]
![image](https://user-images.githubusercontent.com/16759471/41811313-edd01266-773f-11e8-9186-f8500fff98a6.png)
献丑了！

**Comment by luckyadam** [comment]
这个可以在自己业务里做封装~
