### ISSUE TITLE
用typescript后，特定写法，在文件末尾会出现不明字符</>，报语法错误

### ISSUE THREAD

**Issue by lizongze** [NervJS/taro#1851]
```js
const instance: IFly = new (<any>Fly)();
```
上面的代码编译后，在文件末尾会有</>残留，导致报错

  42 |
  43 | export default instance;
> 44 | </>);
     |   ^
  45 |

**Comment by yuche** [comment]
```typescript
const instance: IFly = new Fly<any>();
```
你想表达的应该是这个意思？

**Comment by lizongze** [comment]
> ```ts
> const instance: IFly = new Fly<any>();
> ```
> 
> 你想表达的应该是这个意思？

不是，就是如下：
```
const instance: IFly = new (<any>Fly)();
```
应该是表示给Fly传递一个any类型的参数

**Comment by yuche** [comment]
https://runkit.com/yuche/5c3339f07f9c020012d3e134
在 JSX 模式，原生的 TypeScript 编译器就无法正确编译你的这个写法。我猜有两个可能：

1. 你这个写法是不合法的写法；
2. TypeScript 编译器有问题

**Comment by fjc0k** [comment]
```ts
const instance: IFly = new (Fly as any)();
```

**Comment by lizongze** [comment]
[typescript文档--高级类型](https://www.css88.com/doc/typescript/doc/handbook/Advanced%20Types.html)
上面的链接里面也有很多这样的写法。。总有绕不开的。
我觉得应该是ts编译器的原因，jsx preserve 选项相关的处理有问题。
你们用的是ts原生的编译器么？
建议迁到babel（没测试过能正确编译不，你要不试试？），如babel-plugin-typescript ，但是需要babel@^7.0.0
所以会有从babel 6.x迁到babel7.x的计划么？

**Comment by lizongze** [comment]
type Role = 'HD' | 'BR' | 'CM' | 'AM' | 'M';
我看了下，之前这么用的enum。没有直接声明enum变量。都是给常规变量辅以类型推断的。
对于用了enum特性的来说，是个问题。。

**Comment by yuche** [comment]
babel 支持的肯定是不如 ts 那么多，他的原理其实就是拿到 ast 把所有类型都去掉。
一开始的时候我们我们也是用 babel 来处理 ts，后来才换到原生 ts 编译器的。

确定了问题这个 issue 可以关闭了，如果你强烈需求这个语法可以像 ts repo 提 issue。

**Comment by lizongze** [comment]
提了issue后被告知真的是写法错误。。
文档说明: https://www.tslang.cn/docs/release-notes/typescript-1.6.html
新的 .tsx 文件扩展名和 as 运算符
TypeScript 1.6 引入了新的 .tsx 文件扩展名. 这一扩展名一方面允许 TypeScript 文件中的 JSX 语法, 一方面将 as 运算符作为默认的类型转换方式 (避免 JSX 表达式和 TypeScript 前置类型转换运算符之间的歧义). 比如:
```js
var x = <any> foo;
// 与如下等价:
var x = foo as any;
```
所以在开启jsx preserve的模式下，所有的前置类型声明都应该用as运算符的方式 即 @fjc0k 那样的写法。

之前我的理解也不对
<any>Fly 就是一个前置的类型声明，不是传入的参数之类的。。

![image](https://user-images.githubusercontent.com/12557918/50818361-b6bb6280-1361-11e9-8260-279c28585628.png)
