### ISSUE TITLE
使用 npx @tarojs/cli init myApp 创建项目，通过 npx taro build --type weapp --watch 命令执行出现找不到命令：taro

### ISSUE THREAD

**Issue by nicedudu** [NervJS/taro#1854]
**问题描述**
使用 npx @tarojs/cli init myApp 创建项目，通过 npx taro build --type weapp --watch 命令执行出现找不到命令：taro

**复现步骤**
[复现问题的步骤]
1. npx @tarojs/cli init myApp 
2. npx taro build --type weapp --watch

**报错信息**

```bash
npx taro build --type weapp --watch

npx: 301 安装成功，用时 9.222 秒
找不到命令：taro
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my_app@1.0.0 npx:weapp: `npx taro build --type weapp --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my_app@1.0.0 npx:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
**系统信息**

 - 操作系统: [e.g. macOS]
 - Taro 版本 [e.g. v.1.2.4]
 - Node.js 版本 [e.g. v10.14.2]
 - 报错平台 [weapp]

**补充信息**
1. 采用Typescript + Mobx 方式
2. 之前采用 taro 版本为 1.1.4 时可以采用 npx 方式执行。

**Comment by tinn2015** [comment]
hi, 这问题解决了吗？求解！

**Comment by yeeing** [comment]
请使用npx @tarojs/cli build --type weapp --watch

**Comment by Garfield550** [comment]
如楼上所说。

**Comment by Garfield550** [comment]
`npx taro` 装的是这个包 https://www.npmjs.com/package/taro
