### ISSUE TITLE
ios8上H5框架加载不起来。TypeError: undefined is not a function (evaluating 'Object.assign({}, onAndSyncApis, noPromiseApis, otherApis)')

### ISSUE THREAD

**Issue by rainyf** [NervJS/taro#1855]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
框架加载不起来。测试时候，safira插线真机调试。
提示错误
<img width="686" alt="wx20190108-160201 2x" src="https://user-images.githubusercontent.com/44222099/50817578-3bf14800-135f-11e9-9bfa-58bb40d4df17.png">

<img width="686" alt="wx20190108-160201 2x" src="https://user-images.githubusercontent.com/44222099/50817636-6c38e680-135f-11e9-8252-151f38fca453.png">

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
ios8可以跑起来
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro v1.2.3

  Taro CLI 1.2.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.3 => 1.2.3 
      @tarojs/components: 1.2.3 => 1.2.3 
      @tarojs/plugin-babel: 1.2.3 => 1.2.3 
      @tarojs/plugin-csso: 1.2.3 => 1.2.3 
      @tarojs/plugin-less: 1.2.3 => 1.2.3 
      @tarojs/plugin-uglifyjs: 1.2.3 => 1.2.3 
      @tarojs/redux: 1.2.3 => 1.2.3 
      @tarojs/redux-h5: 1.2.3 => 1.2.3 
      @tarojs/router: 1.2.3 => 1.2.3 
      @tarojs/taro: 1.2.3 => 1.2.3 
      @tarojs/taro-alipay: 1.2.3 => 1.2.3 
      @tarojs/taro-h5: 1.2.3 => 1.2.3 
      @tarojs/taro-swan: 1.2.3 => 1.2.3 
      @tarojs/taro-weapp: 1.2.3 => 1.2.3 
      @tarojs/webpack-runner: 1.2.3 => 1.2.3 
      eslint-config-taro: 1.2.3 => 1.2.3 
      eslint-plugin-taro: 1.2.3 => 1.2.3 

ledeMacBook:RenMinWenLvTaro guanliyuan$ 

 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
我全文没有Object.assign方法了
http://ask.dcloud.net.cn/question/52039

**Comment by Pines-Cheng** [comment]
贴的图片是不是有点问题？

**Comment by rainyf** [comment]
![Uploading WX20190108-160201@2x.png…]()

**Comment by rainyf** [comment]
> 贴的图片是不是有点问题？

图片已上传

**Comment by luckyadam** [comment]
暂时你这边给全局加个 Object.assign 的 polyfill 吧，我们后续会在框架层面加上

**Comment by Littly** [comment]
已提交https://github.com/NervJS/taro/commit/bd53b6f343ad868f81c233f060830e439537fddf 下个版本修复
