### ISSUE TITLE
添加esnextModules后仍然报Module parse failed: Unexpected token (101:11)的问题

### ISSUE THREAD

**Issue by zuojx1013** [NervJS/taro#1858]
报错：./node_modules/taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.

**复现步骤**
初始化项目就会出现这个问题
1. taro init test
2. npm install taro-ui
3. config/index.js 添加  esnextModules: ['taro-ui'],
4. 使用taro-ui 的任意控件如AtButton
5. H5开发模式编译，报错。

**报错信息**
🙅   Compile failed!

./node_modules/taro-ui/dist/h5/components/pagination/index.js 101:11
Module parse failed: Unexpected token (101:11)
You may need an appropriate loader to handle this file type.
|     };
| 
>     return <View className={classNames(rootClassName, classObject, this.props.className)} style={customStyle}>
|         <View className="at-pagination__operate">
|           <View className="at-pagination__btns">

**系统信息**
taro info
👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      npm: 6.2.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: 1.2.4 => 1.2.4 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.4 => 1.2.4 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-swan: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4 

 - Taro 版本 [v.1.2.4]
 - Taro UI 版本 [ v.1.5.4]
 - 报错平台 [h5] 

**补充信息**
这里我把项目文件传到另一部电脑，执行npm install可以正常编译并打开；
本机在taro-ui 1.5.3版本中，可以正常使用;
是我电脑环境缺少什么配置文件导致的吗？
感谢！🙏

**Comment by luckyadam** [comment]
提供一下你项目存放的路径吧，直接在项目目录下执行 `pwd`
顺便再提供一下你的测试项目

**Comment by zuojx1013** [comment]
路径：/Users/zuojunxin 1/Desktop/wx_CSchool/myTest
测试项目：https://github.com/zuojx1013/Taro-myTest

**Comment by zuojx1013** [comment]
> 提供一下你项目存放的路径吧，直接在项目目录下执行 `pwd`
> 顺便再提供一下你的测试项目

路径：/Users/zuojunxin 1/Desktop/wx_CSchool/myTest
测试项目：https://github.com/zuojx1013/Taro-myTest

**Comment by loveonelong** [comment]
@zuojx1013 你在安装的时候是否使用了cnpm的命令？`cnpm install`。
cnpm安装的node_modules会带一个下划线`_modouleName`，虽然我也没搞明白为什么会这样，并且在打包的时候，引用也会成这个带下划线的module。
所以你的`taro-ui`实际引用为`_taro-ui`，有两种解决方案。
1、将esnextModules: ['taro-ui']，设置为esnextModules: ['taro-ui','_taro-ui']
2、不要使用cnpm命令，仅将npm的registry设置为cnpm的源，并使用npm命令

看一下是否和这种情况一样 #1796

**Comment by zuojx1013** [comment]
> @zuojx1013 你在安装的时候是否使用了cnpm的命令？`cnpm install`。
> cnpm安装的node_modules会带一个下划线`_modouleName`，虽然我也没搞明白为什么会这样，并且在打包的时候，引用也会成这个带下划线的module。
> 所以你的`taro-ui`实际引用为`_taro-ui`，有三种解决方案。
> 
> 1. 升级你的taro版本`taro update self` && `taro update project`
> 2. 将esnextModules: ['taro-ui']，设置为esnextModules: ['taro-ui','_taro-ui']
> 
> > 关于esnextModules https://nervjs.github.io/taro/docs/config-detail.html#h5esnextmodules
> 
> 1. 不要使用cnpm命令，仅将npm的registry设置为cnpm的源，并使用npm命令
> 
> 看一下是否和这种情况一样 #1796

确实可以了，感谢🙏🙏🙏
