### ISSUE TITLE
在手机IOS safari上，page的componentWillUnmount，componentDidHide只走一次，同一个page不管push或者pop多少次，componentDidMount只走一次

### ISSUE THREAD

**Issue by Lxg1582** [NervJS/taro#1860]
**问题描述**
在手机IOS safari上，page的componentWillUnmount，componentDidHide只走一次，同一个page不管push或者pop多少次，componentDidMount只走一次

**复现步骤**
生命周期函数不走，很郁闷

```js


```

**期望行为**

**报错信息**

**系统信息**
Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: 1.2.4 => 1.2.4 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-sass: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.4 => 1.2.4 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-swan: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.4 => 1.2.4 
      @tarojs/webpack-runner: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4 

**补充信息**

**Comment by Littly** [comment]
更新到最新版本看看，应该没有这个问题。如果问题依然存在，需要提供可以复现的仓库地址。
