### ISSUE TITLE
scrollView的onScroll方法参数有误

### ISSUE THREAD

**Issue by figo-fe** [NervJS/taro#1866]
**问题描述**
RT

**复现步骤**

```jsx
<ScrollView onScroll={this.onScroll.bind(this)}>
xxx
</ScrollView>

```

```js
onScroll(evt, event){
    console.log(evt) // 打印出来是 "this" 字符串
    console.log(event) // 打印出来是滚动事件
}

```

**其他尝试**
1. 将方法名改为 onListScroll等都会复现
2. 但将方法名改为 onPageScroll，可正常执行，但onPageScroll是小程序滚动页面的事件
3. 如果在bind后面增加参数，如`this.onScroll.bind(this, 'xxx')`。打印：第一个参数是"xxx"，第二个参数是 "this"，第三个参数是 event

**期望行为**
evt即为滚动事件，而非第二个参数

**系统信息**
Taro CLI 1.2.3 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      npm: 4.6.1 - /usr/local/bin/npm

**Comment by Pines-Cheng** [comment]
哪个端？

**Comment by Chen-jj** [comment]
@figo-fe 事件对象排在所有参数最后是正常现象。

**Comment by crper** [comment]
@Chen-jj  我也遇到了... 

![44001547173697_ pic](https://user-images.githubusercontent.com/8272877/51009864-cc60a000-158c-11e9-84ff-27e43703bf0a.jpg)
![44041547173736_ pic_hd](https://user-images.githubusercontent.com/8272877/51009868-cf5b9080-158c-11e9-8b05-e046524b9ad5.jpg)
![44031547173720_ pic](https://user-images.githubusercontent.com/8272877/51009869-d1255400-158c-11e9-9d10-21dc1e492741.jpg)

绑不绑定`this` , 输出都是第一个为字符串的`this`,第二个才是`event details`

不合理...不用`...`来聚合`args`的话,拿到的是`this`字符串

**Comment by Chen-jj** [comment]
@crper 这是因为cli和依赖包版本不一致导致，开发前必须确保他们版本一致
