### ISSUE TITLE
app.json 申明plugins的使用方式没有兼容

### ISSUE THREAD

**Issue by xiaoreign** [NervJS/taro#1868]
**问题描述**
![image](https://user-images.githubusercontent.com/20812513/50884953-5131a980-1427-11e9-9c75-992bee5755a4.png)
在app.json 申明plugins的使用方式,在原生小程序转换成taro的时候报错

**复现步骤**
taro convert的时候报错

**系统信息**
 - 操作系统: [macOs : 10.14.2]
 - Taro 版本 [ v1.2.4]
 - Node.js 版本 [v8.11.4]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
已修复
