### ISSUE TITLE
不支持render内写方法，传参数？

### ISSUE THREAD

**Issue by xiaofengz** [NervJS/taro#1869]
```
render() {
        const renderContent = () => {
            return (
                <View>1</View>
            )
        }
        return (
            <View className='index'>
                    <View className='filter-content'>
                        {renderContent()}
                    </View>
            </View>
        )
    }
```

报错了
![image](https://user-images.githubusercontent.com/25739935/50885953-19783100-142a-11e9-8e84-bde7ab85083b.png)

如果不支持此写法，那什么写法是支持的呢？
谢谢～

**Comment by yuche** [comment]
你就正常写，不支持会报错具体的地点。
或者可以看文档最佳实践：
https://nervjs.github.io/taro/docs/best-practice.html#docsNav

你这个特性规划在 v1.3，现在那个分支已经实现了，不过发布到 npm 还需要更多调试。

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/157
