### ISSUE TITLE
调用微信所有接口均报错

### ISSUE THREAD

**Issue by LYfirstday** [NervJS/taro#1870]
**问题描述**
调用微信接口报错，不影响使用

**复现步骤**
调用微信随便一个接口，比如上传图片，打电话等

```js
chosePic = () => {
    Taro.chooseImage({count: 2}).then(res => {
      let pics = res.tempFiles;
      if (pics) {
        this.setState({pics: pics});
      }
    });
  }
```

**期望行为**
打开相机拍摄或相册选择图片

**报错信息**
![image](https://user-images.githubusercontent.com/25970534/50890141-95777680-1434-11e9-9631-e2880a55c617.png)

**系统信息**
![image](https://user-images.githubusercontent.com/25970534/50890189-af18be00-1434-11e9-98d2-03cda81d6da8.png)

 - 操作系统: [ Windows 10]
 - Taro 版本 [1.0.0-beta.26]
 - Node.js 版本 [v11.4.0]
 - 报错平台 [ weapp]

**Comment by luckyadam** [comment]
升级到最新版本吧

**Comment by LYfirstday** [comment]
您好！
      首先感谢回复，我是在框架1.0.0就开始用的，已经开发了一个线上产品，目前需要新增功能，发现调用所有wx接口都会报错’mode’undefined，目前不影响使用，但还是担心后续会影响线上产品；附件用taro最新脚手架搭建的一个demo，在我电脑上还是会报错， 我系统是win10.

[cid:image003.png@01D4A8CD.E52ED240]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Li,Weitao <notifications@github.com>
发送时间: Wednesday, January 9, 2019 9:06:56 PM
收件人: NervJS/taro
抄送: LYi; Author
主题: Re: [NervJS/taro] 调用微信所有接口均报错 (#1870)


升级到最新版本吧

―

**Comment by LYfirstday** [comment]
这个问题解决了   上面截图微信开发工具的版本号是 v1.02.1812180   下载最新的微信开发工具就不会再报错了

**Comment by melyao** [comment]
我的开发工具检测已经是最新的了 可是还是会有这个错误

**Comment by luckyadam** [comment]
https://developers.weixin.qq.com/community/develop/doc/00006e5a9c0b086ffee7c25f256800
@melyao
