### ISSUE TITLE
编译为支付宝小程序后， global 全局对象找不到

### ISSUE THREAD

**Issue by zw130633** [NervJS/taro#1872]
**问题描述**
转支付宝小程序后， global 全局对象找不到

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
import {create} from 'dva-core';
import {createLogger} from 'redux-logger';
import createLoading from 'dva-loading';
let app;
let store;
let dispatch;

function createApp(opt) {
    opt.onAction = [createLogger()];
    app = create(opt);
    app.use(createLoading({}));

    if (!global.registered) opt.models.forEach(model => app.model(model));
    global.registered = true;
    app.start();

    store = app._store;
    app.getStore = () => store;

    dispatch = store.dispatch;

    app.dispatch = dispatch;
    return app;
}

export default {
    createApp,
    getDispatch() {
        return app.dispatch;
    }
}
```

**期望行为**
正常运行不报错

**报错信息**
![image](https://user-images.githubusercontent.com/12950369/50891678-c5744900-1437-11e9-84b4-e66289d82ec0.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.2.4]
 - Node.js 版本 [e.g. v8.9.0]
 - 报错平台 [alipay]

**Comment by tomgao365** [comment]
@zw130633 试试 [hugetiny/quit-smoking](https://github.com/hugetiny/quit-smoking/blob/master/src/utils/dva.js#L16)

**Comment by zw130633** [comment]
> @zw130633 试试 [hugetiny/quit-smoking](https://github.com/hugetiny/quit-smoking/blob/master/src/utils/dva.js#L16)

这样是把 global 变为普通的局部变量了，还是不能作为整个项目的全局变量

**Comment by luckyadam** [comment]
因为支付宝没有暴露全局对象
