### ISSUE TITLE
请问，h5的服务器端渲染如何实现

### ISSUE THREAD

**Issue by zhengzhuang96** [NervJS/taro#1875]
**问题描述**
h5需要服务器端渲染什么时候可以出现

**期望行为**
希望h5可以出现服务器端渲染

**Comment by zhengzhuang95** [comment]
好的，非常期待整理出的解决方案，等待中。。。

**Comment by wenisy** [comment]
> 我们将整理一下 Taro 进行服务端渲染的文档

@luckyadam 您好，请问有整理文档的计划了吗？

**Comment by xian107** [comment]
@luckyadam 请问文档整理好了吗

**Comment by godfox2012** [comment]
@luckyadam 同问文档整理好了吗？希望有个基于taro的ssr demo

**Comment by shenggen1987** [comment]
能出来个文档吗，ssr服务怎么启动？

**Comment by Phlen** [comment]
Mark....

**Comment by xinzsky** [comment]
react ssr有next.js  vue ssr有 nuxt.js 。希望taro h5端也出来ssr方案

**Comment by zsirfs** [comment]
还在整理计划嘛？

**Comment by Chen-jj** [comment]
有在计划中，但优先级不高

**Comment by SyMind** [comment]
目前我正在做这方面的尝试，一个 Taro 插件，将 Next.js 作为 Taro 的一个目标 platform，以支持 SSR。

项目在这里：https://github.com/SyMind/tarojs-plugin-platform-nextjs
