### ISSUE TITLE
小程序源码转taro时，wx:if不正确？taro再编译成微信小程序时，wx:if丢了

### ISSUE THREAD

**Issue by xrr0520** [NervJS/taro#1880]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
小程序源码转taro时，wx:if还是正确的，taro再编译成微信小程序时，wx:if丢了

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```微信小程序转taro js
// 这里可以贴代码
{/*  物品  */}
          <View className="card" onClick={this.handleShowSelectCargo}>
            <Cell
              hasArrow
              hasBorder={false}
              expansion
              size="lg"
              renderHeader={<View className="text-muted">物品</View>}
              renderBody={
                <View className="text-right text-lg">
                  <View
                    className="text-muted-light"
                    wx:if={
                      !orderBillInfo.selectedCargo ||
                      !orderBillInfo.selectedCargo.selectedTypeName
                    }
                  >
                    请选择物品信息
                  </View>
                  <View wx:else>
                    {orderBillInfo.selectedCargo.selectedTypeName +
                      '/' +
                      orderBillInfo.selectedCargo.selectedPriceName +
                      '/' +
                      orderBillInfo.selectedCargo.cargoWeigh +
                      '公斤'}
                  </View>
                </View>
              }
            />
          </View>


...taro编译成小程序 wxml

<cell hasArrow="{{true}}" __triggerObserer="{{ _triggerObserer }}" hasBorder="{{false}}" expansion="{{true}}" size="lg">
                    <view class="text-muted" slot="header">物品</view>
                    <view class="text-right text-lg" slot="body">
                        <view class="text-muted-light">请选择物品信息</view>
                        <view>{{anonymousState__temp}}</view>
                    </view>
                </cell>
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
问题出在你的原生小程序源码转 taro 上，你应该带上你的原生小程序源码

**Comment by xrr0520** [comment]
bug原因：slot里面的wx:if等 不能正确转译。

`
<view style='color:red;'>
  <component-tag-name>
    
    <view slot="test">这里是插入到组件slot name="test"中的内容
    <text wx:if="{{text==='aa'}}">{{true}}</text>
    <text wx:elif="{{text==='aa'}}">{{true}}</text>
    <text wx:else>{{false}}</text>
    </view>
    
    <view slot="after">这里是插入到组件slot name="after"中的内容
    <text wx:if="{{text==='aa'}}">{{true}}</text>
    <text wx:elif="{{text==='aa'}}">{{true}}</text>
    <text wx:else>{{false}}</text></view>
  </component-tag-name>
</view>`


`
<view class="wrapper">
  <slot name="test"></slot>
  <view>这里是组件的内部细节</view>
  <slot name="after"></slot>
</view>`

taro转译代码
`render() {
    const { text: text } = this.state
    return (
      <Block>
        {/*  引用组件的页面模版  */}
        <View style="color:red;">
          <ComponentTagName
            renderTest={
              <View>
                这里是插入到组件slot name="test"中的内容
                <Text wx:if={text === 'aa'}>{true}</Text>
                <Text wx:elif={text === 'aa'}>{true}</Text>
                <Text wx:else>{false}</Text>
              </View>
            }
            renderAfter={
              <View>
                这里是插入到组件slot name="after"中的内容
                <Text wx:if={text === 'aa'}>{true}</Text>
                <Text wx:elif={text === 'aa'}>{true}</Text>
                <Text wx:else>{false}</Text>
              </View>
            }
          >
            {/*  这部分内容将被放置在组件 <slot name="before"> 的位置上  */}
            {/*  这部分内容将被放置在组件 <slot name="after"> 的位置上  */}
          </ComponentTagName>
        </View>
      </Block>
    )
  }`
