### ISSUE TITLE
gyp ERR! stack Error: 404 response downloading https://r.cnpmjs.org/node/v8.12.0/node-v8.12.0-headers.tar.gz

### ISSUE THREAD

**Issue by xiaodel** [NervJS/taro#1882]
gyp verb remove removing development files for version: 8.12.0
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://r.cnpmjs.org/node/v8.12.0/node-v8.12.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (D:\code\vue\taroTest\node_modules\node-gyp\lib\install.js:214:14)
gyp ERR! stack     at emitOne (events.js:121:20)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestResponse (D:\code\vue\taroTest\node_modules\request\request.js:1066:10)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)

**Comment by yuche** [comment]
换 npm 或 yarn 或者删除 .npmrc 再安装都可以

**Comment by suzp1984** [comment]
Solution: [https://github.com/nodejs/node-gyp/issues/1230](https://github.com/nodejs/node-gyp/issues/1230)

add 


> NPM_CONFIG_DISTURL=https://nodejs.org/download/release/


to your env.
