### ISSUE TITLE
使用switchTab不能跳转到声明tabBar的首页

### ISSUE THREAD

**Issue by Mliushuai** [NervJS/taro#1887]
使用switchTab不能跳转到声明tabBar的首页
 Taro.switchTab({
      url: '/pages/index/index',
    })

  config = {
   config = {
    pages: [
      'pages/index/index',
      'pages/layout/about/about'
    ],
tabBar: {
      list: [{
        pagePath:'pages/index/index',
        text: "首页",
        iconPath: "./images/tab/home.png",
        selectedIconPath: "./images/tab/home-active.png"
      }
    ]}

**Comment by loveonelong** [comment]
是小程序还是h5?有报错么？Taro版本号是多少？
还有你config好像多写了一层哦。
