### ISSUE TITLE
 编译小程序,经常出现wxss文件为空

### ISSUE THREAD

**Issue by 467057463** [NervJS/taro#1888]
**问题描述**
dev环境下,编译小程序时,wxss文件里没有内容(此问题不是每次都会重现,但出现机率很高)
刚起项目可能没有问题,在scss文件连续保存(按ctrl+s)7+次左右,就出现了这个问题

**复现步骤**
1. yarn dev:weapp 
2. 修改scr/pages/index/index.scss 并保存(ctrl+s),重复此动作(本机7次左右)
3. 编译后的 dist/pages/index/index.wxss 内容为空

**编译信息**
修改  样式文件  src/pages/index/index.wxss
生成  样式文件  dist/pages/index/index.wxss
(PS:本地目录 src/pages/index/index.scss 但编译信息里是 src/pages/index/index.wxss )

**wxss文件**
https://user-images.githubusercontent.com/9367442/51016349-050f7200-15ab-11e9-9dc8-a5e270074a07.jpg

**期望行为**
编译wxss文件能符合预期

**系统信息**

 - 操作系统: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - Taro 版本: v1.2.4
 - Node.js 版本: 10.10.0 

**补充信息**
刚起项目可能没有问题,在scss文件连续保存(按ctrl+s)7+次左右,就出现了这个问题

**Comment by nevernet** [comment]
我也有类似问题， 是一个组件
生成的js, json, wxml, wxss 全部是空白的

系统信息

* 操作系统: macOS Mojave 10.14.2
* Taro 版本: v1.2.7
* Node.js 版本: 10.15.0

**Comment by luckyadam** [comment]
@nevernet 组件能否发我一下

**Comment by jianguo1202** [comment]
请问这个问题 解决了吗

**Comment by lhd951220** [comment]
我也是有这个问题，请问这个问题怎么解决？

**Comment by 467057463** [comment]
@lhd951220 @jianguo1202  没有解决,准备暂时放弃,等大版本更新再试试

**Comment by Alansherlock** [comment]
me too

**Comment by imageslr** [comment]
@luckyadam  我也有这个问题，但是在组件的`index.js`中手动`import 'index.scss'`后就不会出现了这个问题了。

之前都不会手动引入，因为我看到[官方文档](https://nervjs.github.io/taro/docs/tutorial.html#%E7%BB%84%E4%BB%B6%E8%AF%B4%E6%98%8E)写的是“可以需要”，没懂到底需不需要）。
