### ISSUE TITLE
taro radio单选在h5中的第二个页面不能点击，第一个页面就能点击？

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1892]
<RadioGroup>
			          		<Text className='yellowText'>范围</Text>
				              <Label  for='1' key='1'>
				                <Radio value='学习'  >学习</Radio>
				              </Label>
				              <Label  for='2' key='2'>
				                <Radio value='生活' checked>
				                生活
				                </Radio>
				              </Label>
			            </RadioGroup>

该代码 放在第一个页面 h5中，页面进来后，可以点击
放在第二个页面h5中，进来页面后，不可以点击 

Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by jinjinjin0731** [comment]
hello 可以提供更加详细的例子吗。 我创建了两个页面，例子里面用的你提供的代码片段，没有复现你说的情况
