### ISSUE TITLE
使用 taro 编译出来的RN代码如何在 react-native init xxx 命令生成的项目中使用

### ISSUE THREAD

**Issue by jnotnull** [NervJS/taro#1893]
taro 用的是 create-react-native-app xx 生成 RN 代码，使用 expo 来作为开发工具。我怎么能在 react-native init xxx 命令生成的项目中复用这部分 RN 代码？

当前的场景是：有一部分原生的逻辑需要使用原生 Java 来做，而另一部分则交给 RN 来做，它们共用一个 APP。

**Comment by Pines-Cheng** [comment]
如果有好的想法，可以沟通一下。@jnotnull

**Comment by Pines-Cheng** [comment]
其实照你这么做的话，expo 反而是累赘了。

**Comment by jnotnull** [comment]
是啊，所以不想用 expo 相关的东东，希望能直接生成纯 RN 的安卓代码

**Comment by Pines-Cheng** [comment]
expo 依赖已移除，集成方式同 React Native : [集成到现有原生应用](https://reactnative.cn/docs/0.55/integration-with-existing-apps/)
