### ISSUE TITLE
分别打包微信小程序、支付宝小程序ext.json不一样的问题

### ISSUE THREAD

**Issue by wnuoer** [NervJS/taro#1898]
**问题描述**
[问题描述：不同平台ext.json不一样]

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shenghanqin** [comment]
请补充更完整的示例、截图
