### ISSUE TITLE
&nbsp; 不能用？

### ISSUE THREAD

**Issue by yuanjie007** [NervJS/taro#1899]
**问题描述**
更新到最新版本，\&nbsp; (空格)不起作用了

**复现步骤**
[复现问题的步骤]

```js
// 这里可以贴代码

```

**期望行为**
**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
 - 操作系统: [Windows 7]
 - Taro 版本 [v1.2.4]
 - Node.js 版本 [v8.9.4]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Autliety** [comment]
same issue reported

**Comment by luckyadam** [comment]
直接用空格试试

**Comment by Autliety** [comment]
> 直接用空格试试

`<Text>Hello,  {this.state.name}</Text>`
and 
`<Text>Hello,&nbsp;{this.state.name}</Text>`
both lead to:
Hello,Guest 
(with no space)

**Comment by luckyadam** [comment]
What command do you use? @Autliety

**Comment by Autliety** [comment]
> What command do you use? @Autliety

`npm run dev:weapp`

**Comment by yuanjie007** [comment]
> oth lead to:
> Hello,Guest

都试过了，没有效果

**Comment by luckyadam** [comment]
OK, let us see see

**Comment by zw130633** [comment]
在 1.2.4 版本中是 ok 了，但是在 1.2.5、1.2.8、1.2.12 版本中还是存在此问题，&nbsp; 还是无效。其它 1.2.4 以上的版本没做测试，我猜应该也是有问题的
