### ISSUE TITLE
代码中多处 callback/Promise 的疑问

### ISSUE THREAD

**Issue by xqin** [NervJS/taro#19]
代码中多处`API`都存在如下这样的样板式的代码.

```
    success && success(res)
    complete && complete(res)

    return Promise.resolve(res)
```

```
      fail && fail(res)
      complete && complete(res)

      return Promise.reject(err)
```

https://github.com/NervJS/taro/search?utf8=%E2%9C%93&q=Promise.resolve%28res%29&type=

即提供 `callback` 形式的回调逻辑,也有返回 `Promise`.

是整个框架就是这么设计的? 还是没考虑好?

现在还在判断有没有 `success/fail/complete` 然后分别执行不同的函数. 而且各个地方, 对 它们的判断也不一样, 有的地方有判断是不是`function`, 有的地方, 则只判断是不是真值, 而没有明确必须要是一个函数..

改成统一约定成返回 `Promise`, 后续调用方是想用 `success` 或者 `fail` 或者 `complete`, 由调用方 自己掌握 不更好吗?

**Comment by luckyadam** [comment]
是最初设计考虑存在问题，因为最开始设计这些api的时候是采用和微信小程序 API 一致的标准，想能够既兼容微信 API ，同时又增加支持 `Promise` 化，所以可能会导致困惑。
后续会改成统一约定成返回 `Promise`，这样确实会更好些~
