### ISSUE TITLE
JSX编译到小程序不支持枚举条件渲染

### ISSUE THREAD

**Issue by Quilljou** [NervJS/taro#1901]
**问题描述**
使用枚举去做条件渲染，编译到小程序报错了

**复现步骤**
```js
        <View className='loading-status'>
          {
            {
              [LOADING_STATUS.LOADING]: loadingText,
              [LOADING_STATUS.FAILED]: <View onClick={onRetry}> 加载失败, 点击重试 </View>,
              [LOADING_STATUS.NOMORE]: '没有更多了'
            }[loadingStatus]
          }
        </View>
```
编译出来
```xml
<view class="loading-status">
{{{ 
[LOADING_STATUS.LOADING]: loadingText, 
[LOADING_STATUS.FAILED]:<View bindtap="funPrivatehWPei">加载失败, 点击重试</View>, 
[LOADING_STATUS.NOMORE]: '没有更多了' }
[loadingStatus]}}
</view>
```
**期望行为**
期望可以正常渲染

**报错信息**
![image](https://user-images.githubusercontent.com/18414813/51085578-9121c500-1776-11e9-8c25-33c998ad9e7e.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by luckyadam** [comment]
这个写法目前支持不了，请用逻辑运算符 `&&`、`||` 或者 `switch-case` 来代替

**Comment by yuche** [comment]
第一次见这个写法，非常有想象力。

即将进行支持并在文档中推广使用该写法。

**Comment by huruji** [comment]
写法很6

**Comment by nyrf** [comment]
不得不佩服，真的6

**Comment by Quilljou** [comment]
感人的深圳速度

**Comment by kennylbj** [comment]
这个写法好6，峰哥峰哥你学到了吗

**Comment by PWDream** [comment]
现在支持枚举条件渲染了吗？@yuche

**Comment by hangaoke1** [comment]
这个写法是否还能在优化一下，比如匹配不到对应组件时，可以设置默认的组件
