### ISSUE TITLE
Multiple components within single .jsx file won't work

### ISSUE THREAD

**Issue by Autliety** [NervJS/taro#1902]
**问题描述**
Declare an external component with single file won't work.

**复现步骤**
```
class ComponentA extends Taro.Component {
  render() {
    return <Text>External</Text>
  }
}

export default class ComponentB extends Taro.Component {
 render() {
   return (
      <View>
         <Text>Origin</Text>
         <ComponentA/>
         <Text>Text</Text>
     </View>
   )
 }
}
```

**期望行为**
Taro output:
`OriginText`
but original React do:
`OriginExternalText`

**报错信息**

no any error or log in console.

**系统信息**

 - 操作系统: macOS 10.14.2
 - Taro 版本 1.2.4
 - Node.js 版本 11.6.0
 - 报错平台 weapp

**Comment by yuche** [comment]
There is a ESLint rule to forbid developer doing this: 
https://github.com/NervJS/taro/blob/master/packages/eslint-config-taro/rules/jsx.js#L37
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md

Make sure all your code go through the [eslint-config-taro](https://github.com/NervJS/taro/blob/master/packages/eslint-config-taro) check.

**Comment by Autliety** [comment]
Sure, thanks. I got it.
