### ISSUE TITLE
预览图片时控制台报错 Cannot read property 'mode' of undefined

### ISSUE THREAD

**Issue by melyao** [NervJS/taro#1903]
**问题描述**

预览图片时可以正常放大图片预览，可是控制台会报错：
Cannot read property 'mode' of undefined;at api onAppEnterBackground callback function
TypeError: Cannot read property 'mode' of undefined
**复现步骤**

this.state = {
      datalist: ['http://172.16.2.130:7001/public/img/pic1.png', 
      'http://172.16.2.130:7001/public/img/pic2.png']
}

//<Image
//          src={this.state.datalist[1]}
//          onClick={this.preview}
//         data-src={this.state.datalist[1]}
//  />

//js代码
preview (e) {
    var current = e.target.dataset.src;
    Taro.previewImage({
      current: current, // 当前显示图片的http链接
      urls: this.state.datalist //需要预览的图片http链接列表
    })
  }

**期望行为**
希望不要报错

**报错信息**
Cannot read property 'mode' of undefined;at api onAppEnterBackground callback function
TypeError: Cannot read property 'mode' of undefined
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
System:
OS: Windows 7
Binaries:
Node: 10.14.1 
npm: 6.4.1 
Taro：v1.2.4

**补充信息**

**Comment by schinvendy** [comment]
这是微信开发工具上的报错。
等待官方人员下个版本的修复

**Comment by melyao** [comment]
@schinvendy  知道了 谢谢

**Comment by Lionad-Morotar** [comment]
![image](https://user-images.githubusercontent.com/26913795/51098435-4e5afe00-1805-11e9-937d-407fad6758fc.png)

同碰到了这种问题, 如果是微信的问题就只能再等等了

**Comment by yanlee26** [comment]
微信的问题。。。
