### ISSUE TITLE
自定义环境变量 打包报错

### ISSUE THREAD

**Issue by yvan0423** [NervJS/taro#1905]
问题描述

自定义环境变量trial，打包时mobx库报错
如果使用 `NODE_ENV=trial taro build --type weapp --watch` 命令运行，则编译正常

复现步骤

package.json
`"trial:weapp": "NODE_ENV=trial taro build --type weapp",`

config/index.js
```
module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  if (process.env.NODE_ENV === 'trial') {
    return merge({}, config, require('./trial'))
  }
  return merge({}, config, require('./prod'))
}
```

config/trial.js
```
module.exports = {
  env: {
    NODE_ENV: '"trial"'
  },
  defineConstants: {
    domain: '"****"',
  },
  weapp: {},
  h5: {}
}
```

期望行为 [这里请用简洁清晰的语言描述你期望的行为]

报错信息
![image](https://user-images.githubusercontent.com/17000326/51098590-5b2c2180-1806-11e9-947a-13ee40522fbb.png)

系统信息

👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.4 => 1.2.4 
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/mobx: 1.2.4 => 1.2.4 
      @tarojs/mobx-h5: 1.2.4 => 1.2.4 
      @tarojs/mobx-rn: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: 1.2.4 => 1.2.4 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-less: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4 
      @tarojs/rn-runner: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.4 => 1.2.4 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-swan: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.4 => 1.2.4 
      @tarojs/webpack-runner: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4 
    npmGlobalPackages:
      typescript: 2.9.1

**Comment by luckyadam** [comment]
使用什么命令编译报错

**Comment by yvan0423** [comment]
> 使用什么命令编译报错

yarn trial:weapp

**Comment by luckyadam** [comment]
没有复现啊
![image](https://user-images.githubusercontent.com/1782542/51612997-8bd62e80-1f5d-11e9-9098-ff6644be2214.png)
![image](https://user-images.githubusercontent.com/1782542/51613006-91cc0f80-1f5d-11e9-8bd5-e02f8cff6a50.png)
![image](https://user-images.githubusercontent.com/1782542/51613020-9abce100-1f5d-11e9-8c19-ce3ff9c97db2.png)
![image](https://user-images.githubusercontent.com/1782542/51613038-a1e3ef00-1f5d-11e9-86a2-3bc48fb95102.png)
![image](https://user-images.githubusercontent.com/1782542/51613054-aa3c2a00-1f5d-11e9-9af7-cc181386118a.png)

**Comment by yvan0423** [comment]
我查看了mobx打包后的代码，发现是因为process变量没有被编译导致报错
![image](https://user-images.githubusercontent.com/17000326/51653565-f5425580-1fce-11e9-8924-edd076b37b25.png)

本地新建了一个mobx模版的项目运行`yarn trial:weapp`命令，运行正常没有报错
