### ISSUE TITLE
 View 组件 添加 微信小程序的 catchtouchmove ， TS 警告提示

### ISSUE THREAD

**Issue by zanjs** [NervJS/taro#1908]
```ts
类型“IntrinsicAttributes & ViewProps & { children?: ReactNode; }”上不存在属性“catchtouchmove”。
```

**Comment by yuche** [comment]
写 onTouchMove：
https://nervjs.github.io/taro/docs/event.html#docsNav

**Comment by li2215890610** [comment]
你好  我也碰到了同样的问题，我已经换成onTouchMove了，但是还是没有达到下面这个博客的效果

https://blog.csdn.net/weixin_39015132/article/details/82284757

**Comment by Zhou-Bill** [comment]
> 你好 我也碰到了同样的问题，我已经换成onTouchMove了，但是还是没有达到下面这个博客的效果
> 
> https://blog.csdn.net/weixin_39015132/article/details/82284757
> 
> 先谢谢楼主，能看分享一下你怎么解决的吗？

![image](https://user-images.githubusercontent.com/13554001/54741745-5450cf00-4bfa-11e9-97ed-7e930dfa897f.png)
