### ISSUE TITLE
picker编译h5时，mode为date时，设置start字段问题

### ISSUE THREAD

**Issue by kou-tian** [NervJS/taro#1911]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
picker组件设置mode为date类型时，设置start字段，时间选择依然可以选择start设置字段以前时间，并且程序报错
**复现步骤**
[复现问题的步骤]
1. 设置start为当前时间
2. 选择以后时间不报错，选择以前时间报错

[或者可以直接贴源代码，能贴文字就不要截图]
![image](https://user-images.githubusercontent.com/20620462/51101417-85d1a680-1815-11e9-9011-d0f56c0d9ed7.png)
```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
![image](https://user-images.githubusercontent.com/20620462/51101436-997d0d00-1815-11e9-924f-29519a5a3860.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 7
 - Taro 版本 [v1.2.4]
 - Node.js 版本  8.11.3
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
ok 晚点看下

**Comment by kou-tian** [comment]
有看什么情况吗？

**Comment by kou-tian** [comment]
@jinjinjin0731 关闭了是修复了吗？
