### ISSUE TITLE
h5中input组件 设置type='number' onInput报错

### ISSUE THREAD

**Issue by pollux2015** [NervJS/taro#1912]
**问题描述**
H5: Input 组件 设置type='number' 报如下错误在Android浏览器里面
![image](https://user-images.githubusercontent.com/11935278/51104027-d5b56b00-181f-11e9-9562-741e9e4724f2.png)

**复现步骤**
<Input
              className='form-input'
              type='number'
              placeholder='请输入手机号'
              value={formAccount}
              onInput={this.onInputAccount.bind(this)}
            />

**系统信息**

 - 操作系统: [Android]
 - Taro 版本 [1.2.4]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5]

**Comment by jinjinjin0731** [comment]
问题已经修复~  今天应该会发个版本 到时候更新即可
