### ISSUE TITLE
swiper 打开页面swiper-item没有宽度100% ，setState设置current不能切换

### ISSUE THREAD

**Issue by Lorrainelyp** [NervJS/taro#1914]
问题描述：h5打开页面sweiper-item宽度没有100%；不能点击切换，尝试切换时弹回来，然后该swiper-item宽度变为100%；
taro 版本1.2.3

代码：
`            <Swiper
              className='swiper-container'
              circular
              autoplay
              style={`height:${Taro.pxTransform(600)}`}
              onChange={this.onSwiperChange}
            >
              {
                good.pic.map((item, index) =>
                  <SwiperItem key={index}>
                    <View className='swiper-container__item'>
                      <Image
                        mode='widthFix'
                        className='swiper-img'
                        src={item.img}
                      />
                    </View>
                  </SwiperItem>
                )
              }
            </Swiper>`

`  onSwiperChange = (e) => {
    this.setState({
      swiperCurrentInditor: e.detail.current + 1
    })
  }`

**Comment by Lorrainelyp** [comment]
刚进入页面swiper-item宽度没有100%，1-2秒后自动变成100%，或者尝试切换swiper（弹回来，没切成功）时能变成100%；
![image](https://user-images.githubusercontent.com/32082292/51106346-73139d80-1826-11e9-9acf-ee1f68c414e6.png)
setState current是为了显示分页，，因为样式特别所以只能自己获取current显示

**Comment by jinjinjin0731** [comment]
异步数据是吧，我测下

**Comment by ybingyu** [comment]
同异步数据，同问题，关注。

**Comment by jinjinjin0731** [comment]
@Lorrainelyp  试下更新到最新版本
