### ISSUE TITLE
Taro cli 无法正确返回Error Code

### ISSUE THREAD

**Issue by lcw0622** [NervJS/taro#1916]
编译失败时依然返回ErrorCode为0，导致使用一些命令行工具时无法判断编译结果
例子：
```bash
bash$ taro build --type h5
/** some log **/
🙅   Failed to compile.
/** error details **/
bash$ echo $?
0
```

**Comment by loveonelong** [comment]
@luckyadam 他的意思可能是在编译打包出现问题的时候，没有抛出异常码，导致travis等一些工具认为编译过程是没有问题的。我也遇到了类似的需求。比如在build时，如果编译有问题，就抛出异常停止编译。
