### ISSUE TITLE
taro convert github 项目 wechat-app-mall，npm run build:weapp 报错 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by BackToHappyBear** [NervJS/taro#1928]
taro 版本  1.2.5
将 wechat-app-mall 项目 wxParse 按照官网提示把 `<template is="wxParse1" data="{{item}}" />` 修改为 `<template is="wxParse0" data="{{item}}" />`

运行 `taro convert` 后，依次执行 `cd taroConvert`，` npm i` ，`npm run dev:weapp` 报错如下
`Cannot read property 'length' of undefined`

我看凹凸实验室里说转换之后都表现良好，目前转化小程序报错，转化 h5可以运行

**Comment by Autliety** [comment]
Same issue reported after update to v1.2.5.
Confirmed causing by updating.
Using a Promise of callback method could alway trigger this.
```
TypeError: Cannot read property 'length' of undefined
(node:19162) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
(node:19162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```
btw: is there any way to row back the taro's version? I'm trucked here and can not make testing LOL

**Comment by yuche** [comment]
1.2.5 cli 有问题，https://github.com/NervJS/taro/issues/1932
先回到 1.2.4 把

**Comment by luckyadam** [comment]
修复了，可以升级到 1.2.6
