### ISSUE TITLE
动态image如何生成

### ISSUE THREAD

**Issue by ldwonday** [NervJS/taro#193]
```js
export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  }

  state = {
    list: [0, 1, 2, 3]
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        {
          this.state.list.map(item => {
            return <Image key={String(item)} src="/static/images/{{item}}.png" />
          })
        }
      </View>
    )
  }
}

```

图片出不来，static没有copy到dist里面

**Comment by snokier** [comment]
试下 `<Image key={String(item)} src={`/static/images/${item}.png`} />`

**Comment by ldwonday** [comment]
@snokier 编译都不通过
```
 <Image key={String(item)} src={`/static/images/{{item}}.png`} />
```
也不行

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/41820491-45a83214-7805-11e8-8f5b-1a111aa31692.png)

**Comment by bushuai** [comment]
@ldwonday 

try
```
import ImageName from 'path/to/image'
```
then

```
<Image src={ImageName} />
```

**Comment by ldwonday** [comment]
@bushuai 我知道你这样子是没问题的，你没看清我的问题吗？我其实要的动态加载的。

**Comment by HiMrHu** [comment]
@ldwonday <Image key={String(item)} src=require("/static/images/{{item}}.png")/>

**Comment by ldwonday** [comment]
@HiMrHu 试过了，不行的！

**Comment by HiMrHu** [comment]
@ldwonday  你试一下，<Image key={String(item)} src=require("写死路径")/>
看看能不能渲染出来，来排除一下路径错误问题，我觉得require应该没什么问题的

**Comment by ldwonday** [comment]
@HiMrHu

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/41830807-c11e2ad2-7875-11e8-9b92-0c1d45355134.png)
不行的，那个item写成'../../assets/images/0.png'就没问题

**Comment by ldwonday** [comment]
@luckyadam 你好，这种方案是可以的，目前config里面没有暴露相应的参数。我觉得最好有一个static目录cli自动回copy，比如：vue-cli。

**Comment by luckyadam** [comment]
@ldwonday OK，下个版本加一下

**Comment by snokier** [comment]
@luckyadam 请问有发布时间吗？

**Comment by luckyadam** [comment]
@snokier copy 功能已经有了

**Comment by forconz** [comment]
@luckyadam https://nervjs.github.io/taro/config-detail.html#copy 这个网址404了

**Comment by Garfield550** [comment]
> @luckyadam https://nervjs.github.io/taro/config-detail.html#copy 这个网址404了

https://taro-docs.jd.com/taro/docs/config-detail.html#copy
