### ISSUE TITLE
路由传参(JSON格式) 【解析数据后，页面第一次渲染出现错误】

### ISSUE THREAD

**Issue by k-water** [NervJS/taro#1933]
**问题描述**
在父页面的路由上带上JSON格式的数据，在进入路由页去解析后，页面第一次`render`会报错。

**复现步骤**

1. 路由传参

```js
const  dataTag = [{a: 1}, {a: 2}]
Taro.navigateTo({
   url: `/subpages/showAll/featuredList/index?dataTag=${dataTag}`
});
```

2. 页面解析

第一种写法
```js
render() {
  const { dataTag } = this.$router.params
  return (
    <View className='featured-tarbar'>
       {JSON.parse(dataTag).map((item, index) => (
        ))}
     </View>
  )
}
```

第二种写法
```js
render() {
  const { dataTag } = this.$router.params
  return (
    <View className='featured-tarbar'>
       {dataTag && JSON.parse(dataTag).map((item, index) => (
        ))}
     </View>
  )
}
```

第三种写法

``` js
render() {
  const { dataTag } = this.$router.params
  if (dataTag) {
    return (
      <View className='featured-tarbar'>
        {dataTag && JSON.parse(dataTag).map((item, index) => (
        ))}
      </View>
    )
  }
}
```

**期望行为**

**报错信息**

第一第二种写法报错信息如下：

![image](https://user-images.githubusercontent.com/17759275/51153831-9719c200-18ac-11e9-8640-9300b2f1a0f2.png)

第三种写法报错信息如下：

![image](https://user-images.githubusercontent.com/17759275/51153984-3939aa00-18ad-11e9-8200-980b888961e7.png)

**系统信息**

![image](https://user-images.githubusercontent.com/17759275/51154049-7b62eb80-18ad-11e9-8a9d-0624c12602a7.png)

**补充信息**
以上描述的第二种写法在编译后，源码并没有把判断条件编译出来。

**Comment by yuche** [comment]
第一种写法：
dataTag 没有值就会报错，当你的组件加载时 taro 就会跑一次你的 render，这时你的路由是没有值的。
第二种写法：
你没有返回 JSX 但是又放在 JSX children 里，如果你返回了就会带上判断。如果你返回的普通数据应该放在变量里，这里编译不会做处理。
第三种写法：
你编译出来的结果不对，我猜你应该用的是 npm run weapp:dev 编译的，或者你的 cli 没装好。正确装好的编译结果给你参考一下：
```js
  _createData() {
    this.__state = arguments[0] || this.state || {};
    this.__props = arguments[1] || this.props || {};
    ;

    var _$$anonymousCallee__;

    const { dataTag } = this.$router.params;
    if (dataTag) {
      _$$anonymousCallee__ = dataTag ? JSON.parse(dataTag) : [];
    }
    Object.assign(this.__state, {
      dataTag: dataTag,
      $anonymousCallee__0: $anonymousCallee__0
    });
    return this.__state;
  }
```

**Comment by k-water** [comment]
get!
