### ISSUE TITLE
conect方法mapStateToProps返回空对象时，mapDispatchToProps在微信小程序不能生效

### ISSUE THREAD

**Issue by sangruo** [NervJS/taro#1934]
**问题描述**
conect方法mapStateToProps返回空对象时，mapDispatchToProps在微信小程序不能生效

**复现步骤**
[复现问题的步骤]

```js
@connect(
  () => {},
  dispatch => {
    return {
      fnActionQuery() {
        dispatch(fnQuery());
      },
    };
  }
)
```
这种写法在微信小程序中`this.props`为`{}`
```js
@connect(
  ({ user }) => ({
   name: user.name,
  }),
  dispatch => {
    return {
      fnActionQuery() {
        dispatch(fnQuery());
      },
    };
  }
)

```
这种写法可以正常运作，`this.props` 为 `{ name:'xxxx' , fnActionQuery : fn }`

**期望行为**
connect 的任意参数可为空对象或 null 

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.2 ]
 - Taro 版本 [v1.2.4]
 - Node.js 版本 [v9.10.0]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
```js
@connect(
  () => ({}),
  dispatch => {
    return {
      fnActionQuery() {
        dispatch(fnQuery());
      },
    };
  }
)
```
