### ISSUE TITLE
升级1.2.6后Component内函数捕捉event失败

### ISSUE THREAD

**Issue by senseluo** [NervJS/taro#1936]
**问题描述**
升级1.2.6后出现事件绑定捕捉失败的错误，似乎是component内的函数没有捕捉到event，

例如以下代码，之前版本运行都没问题：
```js
import React, { Component } from 'react';

class MyComponent extends Component {
  handleCancelClick = (orderID, e) => {
    e.stopPropagation();
    console.log('handleClick', orderID, e)
  };

  render() {
    return (
      <Button onClick={this.handleCancelClick.bind(this, orderID)}>取消</Button>
    );
  }
}


export default MyComponent;
```

**报错信息**

<img width="778" alt="screen shot 2019-01-15 at 1 19 55 pm" src="https://user-images.githubusercontent.com/128367/51160372-a27ae680-18c8-11e9-8dcc-cb53fbd8a803.png">

**系统信息**
  Taro CLI 1.2.6 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm

**Comment by z0y1** [comment]
现在是第一个参数是event，其他参数都丢了，巨大的bug。。
