### ISSUE TITLE
h5 swiper-item宽度异常，有AtFloatLayout时点击弹出swiper自动轮播被取消

### ISSUE THREAD

**Issue by Lorrainelyp** [NervJS/taro#1937]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
- 刚进入页面swiper-item宽度为100%(iphone6  375px)，正常，刷新页面后小了一截(iphon6 359px)；
- 页面还有引用taro-ui的AtFloatLayout弹窗组件时，点击弹窗swiper自动轮播被取消，自动调回第一张，且swiper-item宽度变为100%

**复现步骤**
[复现问题的步骤]
见问题描述

[或者可以直接贴源代码，能贴文字就不要截图]

```js

  onSkuPopClose() {
    this.setState({
      skuPopIsOpened: false
    })
  }
  onSkuPopClick() {
    this.setState({
      skuPopIsOpened: true
    })
  }

// 点击触发弹窗打开
            <View className='good-operate__item' onClick={this.onSkuPopClick.bind(this)}>
              <View className='operate__label'>选择</View>
            </View>

//swiper
            <Swiper
              className='swiper-container'
              circular
              autoplay
              style={`height:${Taro.pxTransform(600)}`}
            >
              {
                good.pic.map((item, index) =>
                  <SwiperItem key={index}>
                    <View className='swiper-container__item'>
                      <Image
                        mode='widthFix'
                        className='swiper-img'
                        src={item.img}
                      />
                    </View>
                  </SwiperItem>
                )
              }
            </Swiper>

// AtFloatLayout
        <AtFloatLayout
          isOpened={this.state.skuPopIsOpened}
          title='选择'
          onClose={this.onSkuPopClose.bind(this)}
          className='sku-pop custom-style'
        >
          <View className='sku-pop__content'>

          </View>
        </AtFloatLayout>


```

**期望行为**
swiper-item宽度正常；点击其他组件不影响swiper组件

**报错信息**
无

![gif](https://user-images.githubusercontent.com/32082292/51161246-a4df3f80-18cc-11e9-90af-6e92a209a868.gif)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  Windows 10
 - Taro 版本:  v1.2.3
 - Node.js 版本 v10.14.2
 - 报错平台 [h5]

**补充信息**
无

**Comment by jinjinjin0731** [comment]
刷新问题是热更新引起的。 这个在开发体验上尽量优化一下 。第二个问题我尝试复现一下

**Comment by 349989153** [comment]
issue +1

**Comment by jinjinjin0731** [comment]
麻烦更新到最新版本

**Comment by Cicada7year** [comment]
@我的问题与之类似，H5上面swiper计算宽度错误，少了16px，滑动也是相应的少了16px。所以会造成右侧央样式错乱，找了很久不知在哪解决？屏幕宽度为375px但是swiper渲染好后为359px。class='swiper-slide swiper-slide-next' @jinjinjin0731

**Comment by Limuyang1013** [comment]
> @我的问题与之类似，H5上面swiper计算宽度错误，少了16px，滑动也是相应的少了16px。所以会造成右侧央样式错乱，找了很久不知在哪解决？屏幕宽度为375px但是swiper渲染好后为359px。class='swiper-slide swiper-slide-next' @jinjinjin0731

同上，我的也是宽度少了16px，完全不知道哪里出了问题

**Comment by Sandra310** [comment]
在h5打包的模板html中head头加个样式`body{margin:0;}`
