### ISSUE TITLE
运行 npm run dev:h5 报文件乱码错误

### ISSUE THREAD

**Issue by zztiswb116** [NervJS/taro#1938]
**问题描述**
项目中引入了融云的小程序库 RongIMLib.xiaochengxu-1.0.0.js 每次运行就会报错

经过排查发现源码被转成乱码 以下是源代码图片
![image](https://user-images.githubusercontent.com/2384360/51166415-563aa100-18de-11e9-82b4-78651618e611.png)

被转化图片：
![image](https://user-images.githubusercontent.com/2384360/51166432-65b9ea00-18de-11e9-90f0-eff0011ed703.png)

报错信息：
![image](https://user-images.githubusercontent.com/2384360/51166442-71a5ac00-18de-11e9-9243-0c1f3c1de4fb.png)

``` 代码如下：
JSON.rx_escapable = new RegExp('[\\\"\\\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]', "g");
          JSON.meta = {
            "\b": "\\b",
            "   ": "\\t",
            "\n": "\\n",
            "\f": "\\f",
            "\r": "\\r",
            '"': '\\"',
            "''": "\\''",
            "\\": "\\\\"
          };

```
定位问题是由于UglifyJS 引发 在添加了配置项以后依然无效
![image](https://user-images.githubusercontent.com/2384360/51166525-cc3f0800-18de-11e9-9090-82fe2738461f.png)

参考issue：https://github.com/mishoo/UglifyJS2/issues/54

**期望行为**
升级配置，解决错误

**系统信息**
👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.4 => 1.2.4
      @tarojs/components: 1.2.4 => 1.2.4
      @tarojs/mobx: 1.2.4 => 1.2.4
      @tarojs/mobx-h5: 1.2.4 => 1.2.4
      @tarojs/mobx-rn: 1.2.4 => 1.2.4
      @tarojs/plugin-babel: 1.2.4 => 1.2.4
      @tarojs/plugin-csso: 1.2.4 => 1.2.4
      @tarojs/plugin-sass: 1.2.4 => 1.2.4
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4
      @tarojs/rn-runner: 1.2.4 => 1.2.4
      @tarojs/router: 1.2.4 => 1.2.4
      @tarojs/taro: 1.2.4 => 1.2.4
      @tarojs/taro-alipay: 1.2.4 => 1.2.4
      @tarojs/taro-h5: 1.2.4 => 1.2.4
      @tarojs/taro-swan: 1.2.4 => 1.2.4
      @tarojs/taro-weapp: 1.2.4 => 1.2.4
      @tarojs/webpack-runner: ^1.2.4 => 1.2.4
      eslint-config-taro: 1.2.4 => 1.2.4
      eslint-plugin-taro: 1.2.4 => 1.2.4
**补充信息**
[可选]
问题应该出在 UglifyJS

**Comment by zztiswb116** [comment]
> 修改配置之后依然乱码
> ![image](https://user-images.githubusercontent.com/2384360/51177901-edfab800-18fb-11e9-98b2-97dc2f78f9c8.png)

在output选项添加了`beautify: false`还是不行

**Comment by luckyadam** [comment]
`npm run dev:h5` 不会跑压缩，不是 uglify 的问题

**Comment by zztiswb116** [comment]
> `npm run dev:h5` 不会跑压缩，不是 uglify 的问题

运行小程序编译也会表现乱码

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/e718d5e1810dd5fb23e31398c9ec67cf21afb2c3
