### ISSUE TITLE
Taro用于开发npm包，经过babel编译为es5之后报错

### ISSUE THREAD

**Issue by TaroXin** [NervJS/taro#1951]
**问题描述**
使用 `Taro` 开发npm包，es6代码经过babel编译为es5之后，Taro小程序项目引入npm包执行报错

**复现步骤**
[复现问题的步骤]
1. 新建 npm 包
2. 引入Taro并执行Taro的一些方法
3. babel编译并发布

```js
import Taro from '@tarojs/taro'

export default {
  save (key, data) {
    Taro.setStorageSync(key, data)
  },

  get (key) {
    return Taro.getStorageSync(key)
  },
}
```

**期望行为**
babel编译后的es5代码可以正常运行，或者提供一下基本的npm包开发不会引起此错误的方式

**报错信息**

这是经过babel编译后的代码
![image](https://user-images.githubusercontent.com/19855713/51225350-d299a800-190f-11e9-901d-111ace829ac9.png)

这是报错信息
![image](https://user-images.githubusercontent.com/19855713/51225248-4be4cb00-190f-11e9-9502-b22755e97ad5.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.2.7 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/mobx: ^1.2.4 => 1.2.4
      @tarojs/taro: ^1.2.4 => 1.2.4
      eslint-config-taro: ^1.2.7 => 1.2.7
      eslint-plugin-taro: ^1.2.7 => 1.2.7

**Comment by Benjaminbai** [comment]
请问如何解决的？

**Comment by Benjaminbai** [comment]
> **问题描述** 使用 `Taro` 开发npm包，es6代码经过babel编译为es5之后，Taro小程序项目引入npm包执行报错
> 
> **复现步骤** [复现问题的步骤]
> 
> 1. 新建 npm 包
> 2. 引入Taro并执行Taro的一些方法
> 3. babel编译并发布
> 
> ```js
> import Taro from '@tarojs/taro'
> 
> export default {
>   save (key, data) {
>     Taro.setStorageSync(key, data)
>   },
> 
>   get (key) {
>     return Taro.getStorageSync(key)
>   },
> }
> ```
> 
> **期望行为** babel编译后的es5代码可以正常运行，或者提供一下基本的npm包开发不会引起此错误的方式
> 
> **报错信息**
> 
> 这是经过babel编译后的代码 ![image](https://user-images.githubusercontent.com/19855713/51225350-d299a800-190f-11e9-901d-111ace829ac9.png)
> 
> 这是报错信息 ![image](https://user-images.githubusercontent.com/19855713/51225248-4be4cb00-190f-11e9-9502-b22755e97ad5.png)
> 
> **系统信息**
> 
> > Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
> 
> Taro CLI 1.2.7 environment info: System: OS: macOS 10.14.1 Shell: 5.3 - /bin/zsh Binaries: Node: 8.11.1 - /usr/local/bin/node Yarn: 1.6.0 - /usr/local/bin/yarn npm: 6.4.0 - /usr/local/bin/npm npmPackages: @tarojs/mobx: ^1.2.4 => 1.2.4 @tarojs/taro: ^1.2.4 => 1.2.4 eslint-config-taro: ^1.2.7 => 1.2.7 eslint-plugin-taro: ^1.2.7 => 1.2.7

大佬怎么解决的？

**Comment by TaroXin** [comment]
@Benjaminbai 当时并没有解决，之后这个方案被放弃了

**Comment by Benjaminbai** [comment]
@TaroXin 那大佬你用了什么方案啊

**Comment by TaroXin** [comment]
@Benjaminbai 不要编译到cjs就可以了，ES6之上的编译结果并不影响程序调用和运行，我记得当时Taro的源码是没有兼容cjs的，所以报错default找不到

**Comment by Benjaminbai** [comment]
@TaroXin 我编译的是es，还是会报，taro.removeStorageSync is not a function, 而且我的taro版本是3.2.8的
