### ISSUE TITLE
H5picker组件[v1.2.7]:  滑动到每一列第一项无法触发onColumnchange

### ISSUE THREAD

**Issue by pollux2015** [NervJS/taro#1955]
**问题描述**
H5: picker组件mode = 'multiSelector'  每一列滚动到第一项时, 未触发 onColumnChange

**复现步骤**

```js
<Picker
        value={selected}
        onChange={this.onChange.bind(this)}
        onColumnChange={this.onColumnChange.bind(this)}
        range={currentRange}
        mode='multiSelector'
      />

```

**报错信息**

例: 滚动到1k, 2k, 3k 均会触发onColumnChange 
![1](https://user-images.githubusercontent.com/11935278/51235282-1214d280-19aa-11e9-868d-902653260030.png)

滚动到**每一列第一项** (例如: 面议)则不会触发onColumnChange
![2](https://user-images.githubusercontent.com/11935278/51235293-18a34a00-19aa-11e9-9c9e-3bd12dc1d2ff.png)

**系统信息**
 - 操作系统: [ MacOs  Mojava]
 - Taro 版本 [ v1.2.7]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5]

**Comment by jinjinjin0731** [comment]
不会触发吗 我试一下

**Comment by pollux2015** [comment]
请问是否已经解决啊

**Comment by jinjinjin0731** [comment]
@pollux2015  已修复 等待发版
