### ISSUE TITLE
H5 tabBar手动刷新后消失

### ISSUE THREAD

**Issue by wb9436** [NervJS/taro#1956]
**问题描述**
H5版本的tabBar在手动刷新后消失, ```http://127.0.0.1:10086``` 这种形式链接刷新当前页面得tabBar正常, 同一页面 ```http://127.0.0.1:10086/#/pages/index/index ```  这种形式链接刷新页面tabBar会消失, 但是在跳转其他页面回退后, tabBar正常显示

**复现步骤**
使用模板初始简单项目, 创建两个tabBar页面, app.js 中配置tabBar  然后进行如上操作即可实现

**期望行为**
回归正常

**报错信息**
正常情况
![image](https://user-images.githubusercontent.com/39255168/51236766-f0b5e580-19ad-11e9-95d1-de67bd0b1613.png)
刷新后
![image](https://user-images.githubusercontent.com/39255168/51236840-2064ed80-19ae-11e9-94a1-0c0819ac86a0.png)

**系统信息**
![image](https://user-images.githubusercontent.com/39255168/51236699-c95f1880-19ad-11e9-86e3-b6710d1453af.png)

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/14a559435dd11cd6bddf627bc49a88ac41fc44b4 已提交 下个版本修复~

**Comment by maskwang** [comment]
期待下个版本发布
