### ISSUE TITLE
微信小程序中componentWillMount 中 this.props 的内容获取不到最新的

### ISSUE THREAD

**Issue by fshare** [NervJS/taro#1957]
**问题描述**
[问题描述：微信小程序中componentWillMount 中 this.props 的内容获取不到最新的]
componentWillMount () {
    console.log('componentWillMount', this.props, this.props.latest, this.props.detail, this.props.siteinfo)
}
**打印结果**
componentWillMount {detail: {254: {…}, 255: {…}, 256: {…}, 257: {…}, 258: {…}, 259: {…}, 260: {…}, 261: {…}, 262: {…}, 263: {…}, 264: {…}, 265: {…}, 266: {…}, 267: {…}, 268: {…}, 269: {…}, 270: {…}, 271: {…}, 272: {…}, 273: {…}, 274: {…}, 275: {…}, 276: {…}, 277: {…}, 278: {…}, 279: {…}, 280: {…}, 281: {…}, 282: {…}, 283: {…}, 284: {…}, 285: {…}, 286: {…}, 287: {…}, 288: {…}, 289: {…}, 290: {…}, 291: {…}, 292: {…}, 293: {…}, 294: {…}, 295: {…}, 296: {…}, 297: {…}, 298: {…}, 299: {…}, 300: {…}, 301: {…}, 302: {…}, 303: {…}, 304: {…}, 305: {…}, 306: {…}, 307: {…}, 308: {…}, 309: {…}, 310: {…}, 311: {…}, 312: {…}, 313: {…}, 314: {…}, 315: {…}, 316: {…}, 317: {…}, 318: {…}, 319: {…}, 320: {…}, 321: {…}, 322: {…}, 323: {…}, 324: {…}, 325: {…}, 326: {…}, 327: {…}, 328: {…}, 329: {…}, 330: {…}, 331: {…}, 332: {…}, 333: {…}, 334: {…}, 335: {…}, 336: {…}, 337: {…}, 338: {…}, 339: {…}, 340: {…}, 341: {…}, 342: {…}, 343: {…}, 344: {…}, 345: {…}, 346: {…}, 347: {…}, 348: {…}, 349: {…}, 350: {…}, 351: {…}, 352: {…}, 353: {…}, …}dispatch: ƒ (t)latest: (200) [442, 441, 440, 439, 438, 437, 436, 435, 434, 433, 432, 431, 430, 429, 428, 427, 426, 425, 424, 423, 422, 421, 452, 420, 419, 418, 417, 416, 415, 414, 413, 412, 411, 410, 409, 408, 407, 406, 405, 404, 403, 402, 401, 400, 399, 398, 397, 396, 395, 394, 393, 392, 391, 390, 389, 388, 387, 453, 386, 385, 384, 383, 382, 381, 380, 379, 378, 377, 376, 375, 374, 373, 372, 371, 370, 369, 368, 367, 366, 365, 364, 363, 362, 361, 360, 359, 358, 357, 356, 355, 354, 353, 352, 351, 350, 349, 348, 347, 346, 345, …]loading: {global: false, models: {…}, effects: {…}}scroll: (6) [{…}, {…}, {…}, {…}, {…}, {…}]siteinfo: {start: "2010", name: "阿斯顿发生", name_idea: "", logo: "", favicon: ""}__proto__: Object []length: 0nv_length: (...)__proto__: Array(0) {}__proto__: Object {}

 this.props 是有最新的内容，但是this.props.detail, this.props.siteinfo都为空
**系统信息**
Taro v1.2.7
  Taro CLI 1.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.9.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD

**Comment by fshare** [comment]
使用@connect绑定的数据

**Comment by Chen-jj** [comment]
@fshare 提供一下可以复现的代码

**Comment by wuweijian1997** [comment]
` 
componentWillReceiveProps(nextProps) {
  //把props里的list放到state里面
    this.setState({list: nextProps.list});
  }
`
props这么写，然后从state里那数据。不然有时props的数据不会更新，

**Comment by fshare** [comment]
我加了一个判断，再render 中微信小程序为空是重新获取第一页，更多的获取没有问题
我用的是 dva.js，现在暂时能用，@wuweijian1997的方法明天试试
`import Taro, { Component } from '@tarojs/taro'
import { Swiper, SwiperItem, View, Text, Image } from '@tarojs/components'
import { connect } from '@tarojs/redux';
import { AtIcon, AtLoadMore } from 'taro-ui'
import Utils from 'lodash'
import Header from '../../components/Header'
import ArticleList from '../../components/ArticleList'
import './index.css'

@connect(({ article, common, loading }) => ({
  platform: common.system.platform,
  detail: article.detail,
  latest: article.latest.all,
  siteinfo: common.site.info,
  scroll: common.site.scroll,
  loading
}))
class Index extends Component {
  constructor (props) {
    super(props)
    this.state = {
      loadingStatus: 'noMore',
      current: 1,
      duration: 500,
      interval: 5000,
      isCircular: true,
      isAutoplay: true,
      hasIndicatorDots: true,
      list: {
        limit: 6,
        size: 6,
        total: -1,
        data: []
      }
    }
  }

  config = {
    navigationBarTitleText: '站点首页'
  }


  componentWillMount () {
    const { platform, latest, detail, siteinfo } = this.props
    if (platform === 'web'){
      let title = '测试网站'
      if (Utils.has(siteinfo, 'name')){
        title = siteinfo.name
      }
      this.props.dispatch({
        type: 'common/changeTitle',
        payload: title
      })
      Taro.setNavigationBarTitle({
        title
      })
      
      const list = this.state.list
      let limit = list.limit
      let total = latest.length
      let data = []
      if (total === 0){
        total = -1
      }
      let loadingStatus = 'noMore'
      loadingStatus = 'more'
      if (total > 0){
        if (total > limit){
          loadingStatus = 'more'
        } else {
          limit = total
        }
        for (let i = 0; i < limit; i++){
          data.push(detail[latest[i]])
        }
      }
      this.setState({
        loadingStatus,
        list:{
          ...list,
          total,
          data
        }
      })
    }
  }

  loadingMoreClick () {
    this.setState({
      loadingStatus: 'loading'
    })
    const latest = this.props.latest
    const detail = this.props.detail
    const list = this.state.list
    let total = list.total
    if (total === -1){
      total = latest.length
    }
    let start = list.limit
    let end = start + list.size
    let loadingStatus = 'more'
    if (end > total){
      end = total
      loadingStatus = 'noMore'
    }
    let data = list.data
    for (; start < end; start++){
      data.push(detail[latest[start]])
    }

    this.setState({
      loadingStatus,
      list:{
        ...list,
        total,
        limit: end,
        data
      }
    })
  }

  render () {
    const { platform, latest, detail, siteinfo, scroll } = this.props
    const { loadingStatus, current, isAutoplay, duration, isCircular, interval, hasIndicatorDots, list } = this.state
    let loadingMoreStatus = loadingStatus
    let loadingMoreShow = loadingStatus === 'more'
    if (!loadingMoreShow && list.total > 0){
      loadingMoreShow = true
    }
    let scrollShow = scroll.length > 0

    let data = list.data

    if (platform === 'weapp' && list.total === -1){
      let title = '测试网站'
      if (Utils.has(siteinfo, 'name')){
        title = siteinfo.name
      }
      Taro.setNavigationBarTitle({
        title
      })

      const limit = list.limit
      let total = latest.length
      if (total === 0){
        total = -1
      }
      if (total > 0){
        if (total > limit){
          loadingMoreShow = true
          loadingMoreStatus = 'more'
        }
        for (let i = 0; i < limit; i++){
          data.push(detail[latest[i]])
        }
      }
    }
    return (
      <View className='xl-index page'>
        <Header />
        {scrollShow && <View className='page__title'><AtIcon className='fa-fw' prefixClass='fa' value='thumbs-up' size='20' color='#09bb07'></AtIcon><Text>站点推荐</Text></View>}
        {scrollShow && <Swiper
          indicatorColor='#999'
          indicatorActiveColor='#333'
          current={current}
          duration={duration}
          interval={interval}
          circular={isCircular}
          autoplay={isAutoplay}
          indicatorDots={hasIndicatorDots}
          preMargin='20'
        >
          {
            scroll.map((item, idx) => (
              <SwiperItem key={idx}>
                <Image mode='aspectFit' src={item.pic} className='slide-image' />
              </SwiperItem>
            ))
          }
        </Swiper>}
        <View className='page__title'><AtIcon className='fa-fw' prefixClass='fa' value='clock-o' size='20' color='#09bb07'></AtIcon><Text>最新更新</Text></View>
        <ArticleList list={data} />
        {loadingMoreShow && <AtLoadMore
          onClick={this.loadingMoreClick.bind(this)}
          status={loadingMoreStatus}
        />}
      </View>
    )
  }
}

export default Index
`

**Comment by CareyToboo** [comment]
遇到一样的问题。但是放到componentDidMount 一切正常。但是这样页面会闪动一下。
