### ISSUE TITLE
<Text>我是\n换行符 </Text> 在微信小程序和H5表现不一致

### ISSUE THREAD

**Issue by xingwen93** [NervJS/taro#1959]
<Text>我是\n换行符 </Text> 在微信小程序和H5表现不一致

微信小程序\n可以换行
但是h5显示 为 \n字符串，并没有换行

dev模式下 
taro版本
 Taro v1.2.7

  Taro CLI 1.2.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.1.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.7 => 1.2.7 
      @tarojs/cli: 1.2.7 => 1.2.7 
      @tarojs/components: 1.2.7 => 1.2.7 
      @tarojs/plugin-babel: 1.2.7 => 1.2.7 
      @tarojs/plugin-csso: 1.2.7 => 1.2.7 
      @tarojs/plugin-less: 1.2.7 => 1.2.7 
      @tarojs/plugin-sass: 1.2.7 => 1.2.7 
      @tarojs/plugin-uglifyjs: 1.2.7 => 1.2.7 
      @tarojs/redux: 1.2.7 => 1.2.7 
      @tarojs/redux-h5: 1.2.7 => 1.2.7 
      @tarojs/router: 1.2.7 => 1.2.7 
      @tarojs/taro: 1.2.7 => 1.2.7 
      @tarojs/taro-h5: 1.2.7 => 1.2.7 
      @tarojs/taro-weapp: 1.2.7 => 1.2.7 
      @tarojs/webpack-runner: 1.2.7 => 1.2.7 
      eslint-config-taro: 1.2.7 => 1.2.7 
      eslint-plugin-taro: 1.2.7 => 1.2.7

**Comment by xingwen93** [comment]
build和dev 模式下  微信小程序 <Text>我是\n换行符 </Text> 可以换行
build和dev 模式下  h5 <Text>我是\n换行符 </Text> 没有换行 显示为\n

**Comment by yuche** [comment]
h5 是否换行是由 css 控制的，textarea 可以用 \n 换行，`Text` 的实现是 `span` 是无法做到换行的。

你可以这样:

```js

<Text>我是 { process.env.TARO_ENV === 'h5' ? <br /> : '\n' }换行符 </Text>
```
