### ISSUE TITLE
【百度小程序】百度小程序API增加seo相关

### ISSUE THREAD

**Issue by sisufo** [NervJS/taro#1962]
**问题描述**

因为需要百度小程序需要接入百度自然流量，需要设置页面的seo信息，详见 https://smartprogram.baidu.com/docs/introduction/rank/

![image](https://user-images.githubusercontent.com/1243767/51256971-99316d00-19e1-11e9-840e-5b8829c700c4.png)

**期望行为**

需要支持如下三个API:
setMetaDescription
setMetaKeywords
setDocumentTitle

具体说明见，http://smartprogram.baidu.com/docs/develop/api/seo/

**Comment by yuche** [comment]
你可以使用 `process.env` 对 h5 进行特别操作：

```js
if (process.env.TARO_ENV === 'swan') {
  swan.setDocumentTitle(...)
}
```

**Comment by sisufo** [comment]
> 你可以使用 `process.env` 对 h5 进行特别操作：
> 
> ```js
> if (process.env.TARO_ENV === 'swan') {
>   swan.setDocumentTitle(...)
> }
> ```

多谢
