### ISSUE TITLE
页面中为什么使用redux后，调用接口后不能.then

### ISSUE THREAD

**Issue by jinyindu** [NervJS/taro#1963]
this.props.onGetList({}).then((value) => {})  使用了redux后为什么方法是promise但是进入页面后就变成非promise了 没有.then

**Comment by Chen-jj** [comment]
提供一下详细代码

**Comment by jinyindu** [comment]
actions.js 
`let requestGetmyTicketList = (params) => {
  return {
    [CALL_API]: {
      endpoint: 'xxx',
      method: 'GET',
      types:ticketTypes,
      params
    }
  }
}
/** 建议方法以on开头 */
export const onGetTicketList = (params) => (dispatch) => {
 //console.log(dispatch(requestGetmyTicketList(params))) 返回一个promise
  return dispatch(requestGetmyTicketList(params))
}
`
reducer.js
const INITIAL_STATE = {}

export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case ticketTypes[SUCCESS]:
      return {
        ...state,
        ticketData: action.response.data
      }
     case ticketTypes[FAILURE]:
       return {
         ...state,
         ticketData: null
       }
     default:
       return state
  }
}

page页面
@connect(
  state => state.ticket,{
    onGetTicketList
  }
)
this.props.onGetTicketList().then((value) => {}) 此处报错 提示.then 不存在 
console.log(this.props.onGetTicketList()) 打印的时候是underfind
