### ISSUE TITLE
PWA考虑一下

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#1964]
PWA考虑一下,让Taro立足世界吧

**Comment by hugetiny** [comment]
我记得Taro有计划准备i18n吧？没有pwa i18n就失去意义了

**Comment by Pines-Cheng** [comment]
Feature Request 可以提在这里哦：https://feathub.com/NervJS/taro

**Comment by TechQuery** [comment]
Duplicated with https://github.com/NervJS/taro/issues/135#issuecomment-2748703345
