### ISSUE TITLE
config 中的 designWidth 不为 750 时尺寸与预期不符

### ISSUE THREAD

**Issue by Means88** [NervJS/taro#1968]
**问题描述**
生成的 `config/index.js` 中有
```js
designWidth: 750,
deviceRatio: {
  '640': 2.34 / 2,
  '750': 1,
  '828': 1.81 / 2
}
```

**复现步骤**
因为我们的设计稿是 375px，因此修改 config 为
```js
designWidth: 375,
deviceRatio: {
  '375': 2,
  '640': 2.34 / 2,
  '750': 1,
  '828': 1.81 / 2
}
```
发现实际显示的尺寸为原来的 1/4。将 `deviceRatio` 改为 `'375': 1 / 2` 以后尺寸与预期相符。猜测可能是配置的数值有误。

 - 操作系统: macOS
 - Taro 版本: v1.2.4
 - Node.js 版本: v10.6.0
 - 报错平台: weapp

**Comment by luckyadam** [comment]
`'375': 1 / 2` 这个配置才是对的

**Comment by 704826318** [comment]
* Taro 版本: v1.2.13还是有这个问题

**Comment by biaomingzhong** [comment]
同样遇到这个问题，跟样例代码一样的写法是不行的

按照 `'375': 1 / 2 ` 写法是行的

应该修改一下文档和 cli 里面的 template，不要让人误解了

**Comment by crabkiller** [comment]
![image](https://user-images.githubusercontent.com/4629430/68824222-0e88cf80-06d1-11ea-94fc-14de6b89c816.png)
麻烦文档改一下

**Comment by dmwin72015** [comment]
> ![image](https://user-images.githubusercontent.com/4629430/68824222-0e88cf80-06d1-11ea-94fc-14de6b89c816.png)
> 麻烦文档改一下

375 = 1 /2 才是对的吧，

**Comment by crabkiller** [comment]
> > ![image](https://user-images.githubusercontent.com/4629430/68824222-0e88cf80-06d1-11ea-94fc-14de6b89c816.png)
> > 麻烦文档改一下
> 
> 375 = 1 /2 才是对的吧，

实测是的

**Comment by sweetyangtian** [comment]
都在说文档有误，不是'375': 2 / 1， 而是'375': 1 / 2 ，但是，我按照文档写'375': 2 / 1反而是对的
