### ISSUE TITLE
初始化时、安装项目依赖失败，请自行重新安装！

### ISSUE THREAD

**Issue by 17dian** [NervJS/taro#1969]
问题描述
创建项目时，安装项目依赖失败

复现步骤
[复现问题的步骤]

$ taro init myapp
👽👽 Taro v1.2.7

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

? 请输入项目介绍！ aaaa
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板
期望行为
如何处理

报错信息
✔ Initialized empty Git repository in /Users/lidongyang/Desktop/biye/lunwen/.git/

✖ 安装项目依赖失败，请自行重新安装！
✖ Install fail! Error: EEXIST: file already exists, symlink '../../../.1.3.9@nervjs' -> '/Users/lidongyang/Desktop/biye/lunwen/node_modules/.1.2.7@@tarojs/components/node_modules/nervjs'
Error: EEXIST: file already exists, symlink '../../../.1.3.9@nervjs' -> '/Users/lidongyang/Desktop/biye/lunwen/node_modules/.1.2.7@@tarojs/components/node_modules/nervjs'
npminstall version: 2.26.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/lidongyang/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

创建项目 myapp 成功！
请进入项目目录 myapp 开始工作吧！😝

系统信息

操作系统: [e.g. mac 10.13.5]
Taro 版本 [e.g. v1.2.7]
Node.js 版本 [e.g. v10.15.0]

**Comment by yuche** [comment]
你的标题不是带了解决方案吗，删除了再重新安装

**Comment by 17dian** [comment]
npm install 能跑起来，我先关了。

**Comment by unmec** [comment]
```
rm myapp/.npmrc
cd myapp && npm install
```

**Comment by lianxueting** [comment]
× cd app1, 执行 git init
× 安装项目依赖失败，请自行重新安装！

**Comment by eugle** [comment]
现在也有这个问题

**Comment by dododcdc** [comment]
我也遇到了，真坑，目前正在手动npm install
