### ISSUE TITLE
组件config内静态资源引入失败

### ISSUE THREAD

**Issue by wangzhipeng404** [NervJS/taro#197]
无法设置小程序tabBar的iconPath

**Comment by luckyadam** [comment]
小程序 tabBar 的 iconPath 应该在入口文件 app.js 里指定呀

**Comment by wangzhipeng404** [comment]
是在app.js的config里面指定的啊，编译的时候应该把config里面的静态资源copy到小程序目录

Li,Weitao <notifications@github.com>于2018年6月25日 周一17:34写道：

**Comment by luckyadam** [comment]
把你配置，还有静态资源位置贴出来看下吧~
