### ISSUE TITLE
升级到1.2.5后运行npm run dev:weapp报错了

### ISSUE THREAD

**Issue by onsenOnly** [NervJS/taro#1970]
![image](https://user-images.githubusercontent.com/26090883/51311476-f978eb00-1a83-11e9-9210-f9fcdf24a7c9.png)
一直好好的。h5版使用redux的时候，遇到了没有render的问题，升级了cli到1.2.5.今天跑了一下项目的weapp版本。居然编译不过了。？？？？这个是什么回事呢？

后面再新建了一个项目，也是编译不过了？？？？

**Comment by yuche** [comment]
1.2.5 和 1.2.6 都是已经被 deprecated 的版本，麻烦安装的时候注意一下说明。
