### ISSUE TITLE
1.2.7 使用lodash的debounce方法出现问题

### ISSUE THREAD

**Issue by gogoJava** [NervJS/taro#1971]
taro升级到1.2.7版本后使用lodash的debounce方法出现TypeError: Cannot read property 'now' of undefined

**Comment by gogoJava** [comment]
![image](https://user-images.githubusercontent.com/11497535/51315014-2df0a500-1a8c-11e9-93ca-59e253b21da7.png)

**Comment by yuche** [comment]
你之前的版本没问题吗，之前那个版本是什么版本

**Comment by wuguojun1006** [comment]
现在有解决吗？我也遇到这个问题

**Comment by gogoJava** [comment]
1.2.0.bate版本没有问题，升级到1.2.4之后开始出现问题，其他版本就没时候试过，lodash的版本是没有变的，暂时换了个库处理就没问题

**Comment by luckyadam** [comment]
提供一下写法

**Comment by Retroxs** [comment]
具体怎么解决的呢

**Comment by zhgqthomas** [comment]
我是使用 throttle 方法时候报了这个问题，请问有没有解决办法啊

**Comment by zhgqthomas** [comment]
我找到问题了是因为我引用的 lodash.throttle 库的源码中 
var now = function() {
  return root.Date.now();
};

这段代码报错，将这段代码改为 
var now = function() {
  return Date.now();
};

就可以正常使用了，估计 debounce 方法也是如此

**Comment by avalanceonerd** [comment]
用lodash导出的 不要用lodash.debounce即可

**Comment by cyh-93** [comment]
#### 同样的问题，代码如下：
```javascript
import Debounce from 'lodash/debounce'

Debounce(() => {}, 300)
```

#### 环境：
  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.19 => 1.3.19
      @tarojs/components: 1.3.19 => 1.3.19
      @tarojs/plugin-babel: 1.3.19 => 1.3.19
      @tarojs/plugin-csso: 1.3.19 => 1.3.19
      @tarojs/plugin-sass: 1.3.19 => 1.3.19
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19
      @tarojs/redux: 1.3.19 => 1.3.19
      @tarojs/redux-h5: 1.3.19 => 1.3.19
      @tarojs/router: 1.3.19 => 1.3.19
      @tarojs/taro: 1.3.19 => 1.3.19
      @tarojs/taro-alipay: 1.3.19 => 1.3.19
      @tarojs/taro-h5: 1.3.19 => 1.3.19
      @tarojs/taro-swan: 1.3.19 => 1.3.19
      @tarojs/taro-tt: 1.3.19 => 1.3.19
      @tarojs/taro-weapp: 1.3.19 => 1.3.19
      @tarojs/webpack-runner: 1.3.19 => 1.3.19
      eslint-config-taro: 1.3.19 => 1.3.19
      eslint-plugin-taro: 1.3.19 => 1.3.19
      nerv-devtools: ^1.4.4 => 1.4.4
      nervjs: ^1.4.4 => 1.4.4
    npmGlobalPackages:
      typescript: 3.5.3

**Comment by shenghanqin** [comment]
试试看最新版如何？

**Comment by ywanhzy** [comment]
我是在微信小程序里没有问题   支付宝小程序里报这个错

**Comment by Chen-jj** [comment]
升级到 1.x 最新版或 Taro2、Taro3 再试试吧，应该没有问题了。

**Comment by suneai** [comment]
3也报错啊

**Comment by JackClown** [comment]
3也报错

**Comment by beysong** [comment]
+1
