### ISSUE TITLE
启动h5的时候报错

### ISSUE THREAD

**Issue by yiwenzhe8877** [NervJS/taro#1972]
**问题描述**

npm run dev:h5的时候报错，错误内容

UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of typ e string. Received type undefined                                                                                     at Module.require (internal/modules/cjs/loader.js:631:11)                                                         at require (internal/modules/cjs/helpers.js:22:18)                                                                at Object.getNpmPkg (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\util\npm.js:151: 17)                                                                                                                   at buildDist (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\h5.js:894:42)               at Object.build (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\src\h5.js:958:9)             at process._tickCallback (internal/process/next_tick.js:68:7)                                                 (node:14964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throw ing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catc h(). (rejection id: 2)                                                                                            (node:14964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise re jections that are not handled will terminate the Node.js process with a non-zero exit code.

**复现步骤**
[复现问题的步骤]
npm run dev:h5

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
![image](https://user-images.githubusercontent.com/44805121/51319738-d278e400-1a98-11e9-99ca-fec510256ec6.png)


**系统信息**
> 

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.7]
 - Node.js 版本 [e.g. v10.15.0]
 - 报错平台 [h5]

**Comment by Littly** [comment]
有没有可以复现的代码？
