### ISSUE TITLE
Image组件onLoad无法正确触发

### ISSUE THREAD

**Issue by TaroXin** [NervJS/taro#1973]
**问题描述**
`Image`组件`onLoad`与`onError`事件无效，无法触发，必须写成小写才可以触发，如`onload`

**复现步骤**
```html
<Image src='http://xxx' onLoad={this.onImageLoad.bind(this)}/>
```

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
驼峰式的事件命名可以正确触发

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.7 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.7 => 1.2.7
      @tarojs/mobx: 1.2.7 => 1.2.7
      @tarojs/mobx-h5: 1.2.7 => 1.2.7
      @tarojs/mobx-rn: 1.2.7 => 1.2.7
      @tarojs/plugin-babel: 1.2.7 => 1.2.7
      @tarojs/plugin-csso: 1.2.7 => 1.2.7
      @tarojs/plugin-sass: 1.2.7 => 1.2.7
      @tarojs/plugin-uglifyjs: 1.2.7 => 1.2.7
      @tarojs/rn-runner: 1.2.7 => 1.2.7
      @tarojs/router: 1.2.7 => 1.2.7
      @tarojs/taro: 1.2.7 => 1.2.7
      @tarojs/taro-alipay: 1.2.7 => 1.2.7
      @tarojs/taro-h5: 1.2.7 => 1.2.7
      @tarojs/taro-swan: 1.2.7 => 1.2.7
      @tarojs/taro-tt: 1.2.7 => 1.2.7
      @tarojs/taro-weapp: 1.2.7 => 1.2.7
      @tarojs/webpack-runner: 1.2.7 => 1.2.7
      eslint-config-taro: 1.2.7 => 1.2.7
      eslint-plugin-taro: 1.2.7 => 1.2.7

**Comment by jinjinjin0731** [comment]
小程序还是 h5

**Comment by TaroXin** [comment]
小程序的

**Comment by Chen-jj** [comment]
@TaroXin 复现不了，提供一下可复现代码。

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Image } from '@tarojs/components'

export default class PageView extends Component {
  onImageLoad (...args) {
    console.log('onLoad: ', args)
  }

  render() {
    return (
      <View>
      <Image src='https://img13.360buyimg.com/img/jfs/t1/19085/37/4620/46003/5c32fe47Ee72a0d3f/15e1247fc66e5c08.png' onLoad={this.onImageLoad.bind(this)} />
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/51379847-5c818500-1b4b-11e9-817a-2c9ea77184ae.png)

**Comment by TaroXin** [comment]
好像问题突然就没有了。。我什么都没做
