### ISSUE TITLE
h5端页面返回无法触发页面重新渲染，导致使用redux的子组件无法更新

### ISSUE THREAD

**Issue by huangyanyang** [NervJS/taro#1974]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
h5端页面返回无法触发页面重新渲染，导致使用redux的子组件无法更新
**复现步骤**
[复现问题的步骤]
1.
![image](https://user-images.githubusercontent.com/19208961/51360874-68982300-1b08-11e9-88bc-a49351a067f3.png)
在这个页面添加添加到购物车是可以的
2.点击商品进入到详情页
![image](https://user-images.githubusercontent.com/19208961/51360895-78b00280-1b08-11e9-83b0-723be0046ebe.png)
点击添加到购物车也可以
3.点击返回到首页
![image](https://user-images.githubusercontent.com/19208961/51360908-86658800-1b08-11e9-8109-0dcb4f74bdc2.png)
4.购物车没有更新！
5.首页和详情页都是使用同一个购物车组件：
![image](https://user-images.githubusercontent.com/19208961/51360930-a5fcb080-1b08-11e9-95e3-b50bfa1b4687.png)
![image](https://user-images.githubusercontent.com/19208961/51360934-a8f7a100-1b08-11e9-9c1c-beaf26074fe6.png)
6.这是购物车组件使用dedux的代码：
![image](https://user-images.githubusercontent.com/19208961/51360949-b4e36300-1b08-11e9-8925-b793f4c0fd26.png)

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
点击返回购物车组件可以跟redux的保持一致

**报错信息**

无报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 1.2.0
 - Node.js 版本 8.11.3
 - 报错平台 h5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
能否在这做一个简单的复现？
https://codesandbox.io/s/m569y854wy

**Comment by shengbowen** [comment]
同出现了额
