### ISSUE TITLE
使用mobx模板新创建项目启动报错

### ISSUE THREAD

**Issue by wb9436** [NervJS/taro#1979]
**问题描述**
最新版本1.2.7, 使用mobx模板创建项目运行H5版本时出错, 使用官方模板项目 taro-mobx-sample 也出现同样问题

![image](https://user-images.githubusercontent.com/39255168/51367797-2e8a4980-1b27-11e9-9fcd-0dd359a008c8.png)

**复现步骤**
新创建项目安装依赖运行即出现同样问题

**期望行为**
想知道原因及如何修正

**报错信息**

![image](https://user-images.githubusercontent.com/39255168/51367842-6a251380-1b27-11e9-94ec-71be64bdc44b.png)

**系统信息**

![image](https://user-images.githubusercontent.com/39255168/51367848-78732f80-1b27-11e9-9fb9-f6496a516965.png)

![image](https://user-images.githubusercontent.com/39255168/51367884-9476d100-1b27-11e9-98a3-fc23ac3b4523.png)

**Comment by nanjingboy** [comment]
https://github.com/NervJS/taro/issues/1943 已修复，等待发版本 @wb9436

**Comment by yuche** [comment]
close via #1943

**Comment by wb9436** [comment]
> #1943 已修复，等待发版本 @wb9436

@nanjingboy 哦哦  好的  麻烦了
