### ISSUE TITLE
小程序 MovableView 设置坐标后无法重新渲染

### ISSUE THREAD

**Issue by xuxiaoxiao312** [NervJS/taro#1981]
**问题描述**
小程序中使用MovableView，移动后设置与之前相同的x,y坐标值无法重新渲染，this.setState和this.forceUpdate都无法重新，如果x,y值与之前不同就可以重新渲染
**复现步骤**
```js

```
	constructor(props) {
		super(...props);
		this.state = {
			test: [
				{
					top: 0,
					left: 0,
					contnet: '内容1'
				},
				{
					top: 100,
					left: 0,
					contnet: '内容222'
				}
			]
		};
	}
	changePosition() {
		this.forceUpdate();
	}
	render() {
		let { test } = this.state;
		return (
			<MovableArea style='height:200px;width:100%'>
				{test.map((el, i) => {
					return (
						<MovableView
							style='width:100px;height:50px'
							key={i}
							direction='all'
							x={el.left}
							y={el.top}
							onTouchEnd={this.changePosition}
						>
							<View> {el.contnet}</View>
						</MovableView>
					);
				})}
			</MovableArea>
		);
	}
```
完整测试代码

```

**系统信息**
👽 Taro v1.2.0

  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by xuxiaoxiao312** [comment]
@luckyadam 请问这个问题大概什么时候可以解决？

**Comment by xuxiaoxiao312** [comment]
> 我这两天看下~

请问这个问题有什么临时解决方案吗？

**Comment by javahuang** [comment]
@luckyadam 同样遇到这个问题，请问有什么解决方案吗？

**Comment by xuxiaoxiao312** [comment]
@luckyadam @yuche 这个问题要怎么解决呢，项目要上线了，就这里卡住了，页面比较复杂，小程序混写也不能只引用单个组件，请问能给个确切回复吗？

**Comment by luckyadam** [comment]
@xuxiaoxiao312 抱歉，我们这两天看下，最近确实很忙

**Comment by Chen-jj** [comment]
@xuxiaoxiao312 原因有二：

一、小程序的 MovableView 是非可控组件，组件位置变更时 data 的 x 和 y 并不会跟随变化，还是初始值。

二、Taro 更新时会将新的数据和页面 data 作一次 diff，diff 出最小更新。onTouchEnd 时如果 setState 相同的坐标，diff 时发现和 data 中的坐标一样，就会跳过这次更新，所以就会出现你提出的 bug。

因此正确做法是在 onChange 的时候保证 state、data 中坐标值与当前 MovableView 的坐标值一致。

具体代码：

```js
import Taro, { Component } from '@tarojs/taro'
import { View, MovableArea, MovableView } from '@tarojs/components'

export default class Detail extends Component {
  constructor(props) {
    super(...props);
    this.state = {
      test: [
        {
          top: 0,
          left: 0,
          content: '内容1'
        },
        {
          top: 100,
          left: 0,
          content: '内容222'
        }
      ]
    };
  }
  changePosition() {
    this.setState({
      test: [
        {
          top: 0,
          left: 0,
          content: '内容1'
        },
        {
          top: 100,
          left: 0,
          content: '内容222'
        }
      ]
    })
  }

  handleChange (i, e) {
    this.setState(prev => {
      const test = prev.test.slice()
      test[i] = {
        top: e.detail.y,
        left: e.detail.x,
        content: test[i].content
      }
      return { test }
    })
  }

  render() {
    let { test } = this.state;
    return (
      <MovableArea style='height:200px;width:100%'>
        {test.map((el, i) => {
          return (
            <MovableView
              style='width:100px;height:50px'
              key={i}
              direction='all'
              x={el.left}
              y={el.top}
              onTouchEnd={this.changePosition}
              onChange={this.handleChange.bind(this, i)}
            >
              <View> {el.content}</View>
            </MovableView>
          );
        })}
      </MovableArea>
    );
  }
}
```

**Comment by esdotzed** [comment]
@Chen-jj 你答案中的 onChange 应该改成 onTouchMove，否则的话 onChange 事件里面包含 onTouchEnd 这个事件。所以会产生race condition，在手指离开的时候，同时触发 onChange 和 onTouchEnd 导致失效。
