### ISSUE TITLE
使用ref在真机调试有问题

### ISSUE THREAD

**Issue by zongshixuebuhui** [NervJS/taro#1986]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------
https://guides.github.com/features/mastering-markdown/

**问题描述**
[在组件Swiper中使用ref会报错，]
<Swiper className='lunbo' indicatorActiveColor='#333' circular indicatorDots autoplay ref='swiper'>
          {this.state.bannerlist.map((img,index)=>(<SwiperItem key={index} ><Image src={img.src} onClick={this.swiperTo.bind(this,img.url)}/></SwiperItem>))}
        </Swiper>
**复现步骤**
[复现问题的步骤]
1. 在Swiper中加上ref='swiper'就会报错，删除之后就不报错了，而且只有手机上报错

**报错信息**
![0816102a1b725301c8cbff79e92124c](https://user-images.githubusercontent.com/44051077/51381096-2eea0b00-1b4e-11e9-9cbb-5950b927f8c9.jpg)

// 这里可以贴代码

[这里请用简洁清晰的语言描述你期望的行为]

可以解决此bug

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [e.g. v.1.2.1]
 - Node.js 版本 [e.g.8.12.0]
 - 报错平台 [weapp]

**补充信息**
![a40e6c0e6fea1534a65ad33ac5c5dc8](https://user-images.githubusercontent.com/44051077/51381201-6fe21f80-1b4e-11e9-946f-5dfe99ad02b9.png)

[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
可能是taro编译的问题，我们发布了测试版本就没有错误，开发版本遇到这个问题

**Comment by Chen-jj** [comment]
@zongshixuebuhui 升级到最新版再试试
