### ISSUE TITLE
npm run dev:h5 failed to compile

### ISSUE THREAD

**Issue by fenglui** [NervJS/taro#1990]
新建ts mobx模板 npm run dev:h5报错
./node_modules/_@tarojs_mobx-h5@1.2.7@@tarojs/mobx-h5/index.js
Module not found: Can't resolve './Provider' in '...\node_modules\_@tarojs_mobx-h5@1.2.7@@tarojs\mobx-h5'

**Comment by giscafer** [comment]
`1.2.7`版本同样出现H5构建时 `Can't resolve './Provider'`错误。小程序是分包模式

**Comment by yuche** [comment]
Duplicate of #1979
