### ISSUE TITLE
cli v1.2.7 初始化项目存疑

### ISSUE THREAD

**Issue by yuminjustin** [NervJS/taro#1994]
**问题描述**
安装好taro的cli脚手架，初始化一个新项目，一直失败。
cli 全局安装 ，yarn  淘宝镜像，node v10
手动安装之后 ，运行（npm run dev:weapp）又不断地输出缺少@tarojs/taro-weapp

**复现问题的步骤**
按照官方文档操作

**期望行为**
刚开始接触taro，也没搜索到类似的issue，希望得到解答。

**报错信息**

![image](https://user-images.githubusercontent.com/8414340/51449803-b0b58080-1d68-11e9-9298-b4dee3af961d.png)

![image](https://user-images.githubusercontent.com/8414340/51449983-bfe8fe00-1d69-11e9-9e5f-5d48df259537.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.2.7]
 - Node.js 版本 [v10]
 - 报错平台 [h5, weapp]

**Comment by luckyadam** [comment]
可能依赖没有装好，你重新安装下依赖试试

**Comment by yuminjustin** [comment]
> 可能依赖没有装好，你重新安装下依赖试试

恩恩，yarn安装的显示有依赖未安装，然后用npm整个安装了一下，可以运行了
