### ISSUE TITLE
使用expo测试官方代码，video组件在Rn平台运行报错

### ISSUE THREAD

**Issue by zenskcode** [NervJS/taro#1997]
**问题描述**
官方文档代码，video组件在Rn平台运行报错。
代码如下：
![image](https://user-images.githubusercontent.com/46669456/51453230-275a7a00-1d79-11e9-89ee-f9f23ecab92d.png)
报错信息：
![image](https://user-images.githubusercontent.com/46669456/51453279-6b4d7f00-1d79-11e9-848b-a3d40f4f2d78.png)
12:23:16: componentDidShow1222
12:23:18: Warning: Failed prop type: Invalid prop `positionMillis` of type `string` supplied to `Video`, expected `number`.
- node_modules\react-native\Libraries\ReactNative\YellowBox.js:69:16 in error
- node_modules\prop-types\checkPropTypes.js:19:20 in printWarning
- ... 22 more stack frames from framework internals
12:23:18: Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
- node_modules\react-native\Libraries\ReactNative\YellowBox.js:80:15 in warn
- node_modules\react\cjs\react.development.js:92:19 in printWarning
- ... 8 more stack frames from framework internals
 将其中的initIalTime改为{0}，一样的报错

**复现步骤**
按官方video组件文档代码运行RN端，使用expo测试

**期望行为**
检查video组件相关处理，定位问题，是否为组件内部问题，或是组件使用方法错误

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:win10
 - Taro 版本 1.2.7
 - Node.js 版本； 10.14.1
 - 报错平台：RN

**补充信息**
[可选]
video组件内部在处理相关参数的时候，RN平台需要转换为number类型结果没有处理

**Comment by zenskcode** [comment]
将其中的initIalTime改为{0}，一样的报错，可以运行，官方代码有误。但是同样的资源rn端奇慢，h5很快

**Comment by Manjiz** [comment]
是的，如果真要传个字符串的话，那我这边支持一下吧

**Comment by CoderDayson** [comment]
> @zenskcode initIalTime -> initialTime

这个为描述错误，实际代码没错，抱歉
