### ISSUE TITLE
有微信或者qq的社区答疑吗？

### ISSUE THREAD

**Issue by wmbox001** [NervJS/taro#20]
如题。希望能得到反馈

**Comment by yuche** [comment]
![image](https://user-images.githubusercontent.com/7202516/41135320-9abb1f5a-6b03-11e8-9bc3-719bbe5df525.png)

**Comment by zacksleo** [comment]
群满了，进不去啊

**Comment by Howell5** [comment]
群满 +1

**Comment by chenhongen** [comment]
chenhongen-weixin，求拉

**Comment by YutHelloWorld** [comment]
phandom_t 求拉

**Comment by yuche** [comment]
Duplicate of #111
