### ISSUE TITLE
[Feature Request] Taro cli 解决NPM包功能增强

### ISSUE THREAD

**Issue by mindfocus** [NervJS/taro#2000]
缘由：
Taro cli能自动下载缺少的npm包，但是对于file:// 类的包没有办法检测到，同时安装也是失败的

使用到的场景：
1、开发私有包
2、taro-ui和taro/components同时开发（由于发版间隔...比如在taro/components包中更新一些功能后，要对taro-ui也进行同步更新，目前的情况是只能更taro/components发版，影响PR效率)
希望：
1、增强自动下载缺少的npm安装包功能或废除(安心做一个taro,而不去做一个npm)

**Comment by Pines-Cheng** [comment]
@mindfocus  你好，Feature Request 麻烦提到这里 https://feathub.com/NervJS/taro 哦，方便跟踪和统计。
