### ISSUE TITLE
微信小程序使用环境变量报错(process.env)

### ISSUE THREAD

**Issue by sherryxiao1988** [NervJS/taro#2001]
**问题描述**
process.env似乎不能使用，微信开发者工具报错说找不到`process`这个变量

**复现步骤**
在config里面这样使用process.env

```js
const prodConfig = {
  SERVER_URL: process.env.SERVER_URL,
}
```

**报错信息**
taro编译没有问题，可是微信开发者工具报错：
![image](https://user-images.githubusercontent.com/1202426/51460304-02c0cb00-1d96-11e9-9f08-c6f4c0257dcd.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac os high sierra version 10.13.6
 - Taro 版本 1.2.4
 - Node.js 版本 11.6.0
 - 报错平台  weapp

**Comment by luckyadam** [comment]
贴一下 configs.js 的源码

**Comment by sherryxiao1988** [comment]
> 贴一下 configs.js 的源码

```
const devConfig = {}
const prodConfig = {
  SERVER_URL: process.env.SERVER_URL,
}
const defaultConfig = {
  SERVER_URL: 'http://localhost:3000/v1',
}

function envConfig(env) {
  switch(env) {
    case 'development':
      return devConfig
    case 'production':
      return prodConfig
    default:
      return defaultConfig
  }
}

export default {
  ...defaultConfig,
  ...envConfig(process.env.NODE_ENV)
}
```

**Comment by sherryxiao1988** [comment]
@luckyadam 可以麻烦看一下嘛lol 谢谢啦

**Comment by luckyadam** [comment]
你有设置 `process.env.SERVER_URL` 么

**Comment by luckyadam** [comment]
@sherryxiao1988 看下你怎么设置的

**Comment by sherryxiao1988** [comment]
@luckyadam 啊我没设置，不过只要process.env能取到，不应该会报错。它直接说process找不到的。。。

**Comment by proactivefly** [comment]
这个问题也没解决就关了？

**Comment by yunhouhuang** [comment]
问题没解决就关掉了？
