### ISSUE TITLE
微信小程序使用css modules编译时报错

### ISSUE THREAD

**Issue by krysiyi** [NervJS/taro#2002]
**问题描述**
css modules使用之后编译错误

**复现步骤**
[复现问题的步骤]
使用css modules，已在config中配置namingPattern: 'module'
引入页面import styles from './index.module,scss
使用命令  npm run dev:weapp  编译页面时提示无法找到文件

**期望行为**
正确编译  当前路径下寻找index.module.scss而不是index.scss
  
**报错信息**
页面编译  页面D:\pro\scenic\src\pages\index\index编译失败！
{ Error: ENOENT: no such file or directory, open 'D:\pro\scenic\src\pages\index\index.scss'
  ......省略
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\pro\\scenic\\src\\pages\\index\\index.scss' }

**系统信息**
👽 Taro v1.2.7
  Taro CLI 1.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 
      npm: 6.4.1 
 - 报错平台 [h5, weapp]

**补充信息**
在编译时 import styles from "./index.module.scss"
应该去找inde.module.scss文件   但是编译报错说找不到index.scss

**Comment by luckyadam** [comment]
看这个报错，应该是你的代码里写了引用 `index.scss`
