### ISSUE TITLE
video组件h5端自动播放无效

### ISSUE THREAD

**Issue by CoderDayson** [NervJS/taro#2004]
**问题描述**
video组件h5端自动播放无效

[或者可以直接贴源代码，能贴文字就不要截图]
 <Video
          src='http://221.228.226.23/11/t/j/v/b/tjvbwspwhqdmgouolposcsfafpedmb/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4'
          controls={false}
          autoplay={true}
          //poster='http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg'
          initialTime={0}
          id='video'
          loop={false}
          muted={false}
        />

**期望行为**
确认为组件问题后尽快修复，项目受到影响
**报错信息**

[这里请贴上你的**完整**报错截图或文字]
报错信息，控制台日志如下
![image](https://user-images.githubusercontent.com/27328981/51474594-cd7aa400-1dba-11e9-8ae9-dc85dd45acfb.png)

**系统信息**
h5平台，
taro：1.2.8
node: 6.4.1 另一平台10.x版本问题依旧

**Comment by jinjinjin0731** [comment]
![image](https://user-images.githubusercontent.com/17409735/51524068-248a8280-1e68-11e9-811c-f6f7f265cbae.png)
![image](https://user-images.githubusercontent.com/17409735/51524096-34a26200-1e68-11e9-9bfa-6abfe632f9fb.png)
如图所示，应该是视频还处于正在请求中，没法开始自动播放

**Comment by CoderDayson** [comment]
> ![image](https://user-images.githubusercontent.com/17409735/51524068-248a8280-1e68-11e9-811c-f6f7f265cbae.png)
> ![image](https://user-images.githubusercontent.com/17409735/51524096-34a26200-1e68-11e9-9bfa-6abfe632f9fb.png)
> 如图所示，应该是视频还处于正在请求中，没法开始自动播放

偶尔可以，那如何确保自动播放呢，能否做到视频请求到达后自动播放呢，尝试几十上百次可能才有一次自动播放

**Comment by jinjinjin0731** [comment]
autoplay 这个参数就是在资源达到可以播放的时候，开始播放。 加载速度和很多因素有关。 你可以看下这篇文章
[https://zhaoda.net/2014/10/30/html5-video-optimization/](https://zhaoda.net/2014/10/30/html5-video-optimization/)
[https://zhuanlan.zhihu.com/p/42045362](https://zhuanlan.zhihu.com/p/42045362)

**Comment by jinjinjin0731** [comment]
根据你的视频链接我找到了原网址，你看下原网址的加载速度，和上面的图坐下对比，40s 才加载完 5.6 MB，原网址的加载速度，是非常快的
![image](https://user-images.githubusercontent.com/17409735/51527456-75ea4000-1e6f-11e9-9fca-84697a91661e.png)

**Comment by CoderDayson** [comment]
![image](https://user-images.githubusercontent.com/27328981/51544546-2ae62200-1e9b-11e9-84b4-9f6aab19a491.png)
使用您提供的原生地址，发现会response data fail，使用地址在chorme浏览器中直接访问可以瞬间访问
npm 6.6.0
node 11.7.0
taro 1.2.8

**Comment by CoderDayson** [comment]
> 根据你的视频链接我找到了原网址，你看下原网址的加载速度，和上面的图坐下对比，40s 才加载完 5.6 MB，原网址的加载速度，是非常快的
> ![image](https://user-images.githubusercontent.com/17409735/51527456-75ea4000-1e6f-11e9-9fca-84697a91661e.png)
发现将muted设置为true，则每次都可以自动播放成功

**Comment by jinjinjin0731** [comment]
`      <View>
        <Video
          src='https://vd.yinyuetai.com/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4'
          controls={false}
          autoplay
          // poster='http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg'
          initialTime={0}
          id='video'
          loop={false}
          muted={false}
        />
      </View>`
1，首先用这个可以立马加载出来
2，muted 是静音属性
3，你可以分别在 chrome 直接加载`https://vd.yinyuetai.com/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4`
与您提供的链接
`http://221.228.226.23/11/t/j/v/b/tjvbwspwhqdmgouolposcsfafpedmb/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4`
 这是您那边的优化问题，和 Taro video 组件没有关系。 你可以试试直接用 H5 原生页面去试试，不用 Taro 标签，我相信也是一样的结果

**Comment by CoderDayson** [comment]
> ` <View> <Video src='https://vd.yinyuetai.com/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4' controls={false} autoplay // poster='http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg' initialTime={0} id='video' loop={false} muted={false} /> </View>`
> 1，首先用这个可以立马加载出来
> 2，muted 是静音属性
> 3，你可以分别在 chrome 直接加载`https://vd.yinyuetai.com/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4`
> 与您提供的链接
> `http://221.228.226.23/11/t/j/v/b/tjvbwspwhqdmgouolposcsfafpedmb/sh.yinyuetai.com/691201536EE4912BF7E4F1E2C67B8119.mp4`
> chrome 会自动播放视频的，你可以体验一下直接打开链接，他的播放速度。
> 这是您那边的优化问题，和 Taro video 组件没有关系。 你可以试试直接用 H5 原生页面去试试，不用 Taro 组件，我相信也是一样的结果
您好，经过踩坑，发现这是浏览器导致的自动播放限制，详情请google 自动播放策略，
https://github.com/gnipbao/iblog/issues/25
https://gitee.com/hjm100/codes/xo5y21h7ipcsvdj0femr845

**Comment by jinjinjin0731** [comment]
解决就好

**Comment by zlh** [comment]
3.6.5版本微信里头无法自动播放
