### ISSUE TITLE
taro1.2.8 组件文件改动后，h5没有热更新

### ISSUE THREAD

**Issue by phlill** [NervJS/taro#2005]
**问题描述**

taro1.2.8版本，在改动组件的tsx或scss文件后，只监听到文件改动，但没有实现热更新
**复现步骤**
[复现问题的步骤]
1. npm run dev:h5
2. 改动组件的tsx或scss，保存
3. 观察到引用改组件的h5页面没有热更新

**期望行为**
改动组件文件后，引用的页面会热更新

**系统信息**

Taro CLI 1.2.8 environment info:
    System:
      OS: macOS High Sierra 10.13.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.8 => 1.2.8
      @tarojs/plugin-babel: 1.2.8 => 1.2.8
      @tarojs/plugin-csso: 1.2.8 => 1.2.8
      @tarojs/plugin-sass: 1.2.8 => 1.2.8
      @tarojs/plugin-uglifyjs: 1.2.8 => 1.2.8
      @tarojs/router: 1.2.8 => 1.2.8
      @tarojs/taro: 1.2.8 => 1.2.8
      @tarojs/taro-alipay: 1.2.8 => 1.2.8
      @tarojs/taro-h5: 1.2.8 => 1.2.8
      @tarojs/taro-swan: 1.2.8 => 1.2.8
      @tarojs/taro-weapp: 1.2.8 => 1.2.8
      @tarojs/webpack-runner: 1.2.8 => 1.2.8
      eslint-config-taro: 1.2.8 => 1.2.8
      eslint-plugin-taro: 1.2.8 => 1.2.8
 - 报错平台 [h5]

**补充信息**
1.新版本的问题？之前老版本正常
2.组件引用方式：import { IconBlock, MInput } from '../../components';是否是没有显式引用的关系

**Comment by Littly** [comment]
更新到最新版还存在这个问题吗？如果存在，需要一个可以复现这个情况的仓库

**Comment by Mohaiyo** [comment]
同样遇到这个问题，在h5开发环境下面。改变组件内的样式或者脚本都不会热更新，只能检测到文件改动，但是没有重新编译。只有直接在页面上更改才会触发重新编译。详细信息可见下图
![3f9a04e2-cea2-42bc-8cf7-03b89e8d124f](https://user-images.githubusercontent.com/22421509/54103642-24d6e100-4408-11e9-94c5-5e4c3ba6a3ae.png)

**Comment by giantss** [comment]
同上
