### ISSUE TITLE
android 真机调试 Taro.request 直接faile

### ISSUE THREAD

**Issue by LailaiMaster** [NervJS/taro#2007]
**问题描述**
百度小程序 真机调试 android taro.request 返回fail 201 illegal request 什么问题啊，iOS没有问题
百度小程序 android不支持8080端口吗

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
 Taro CLI 1.2.8 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.8 => 1.2.8 
      @tarojs/components: 1.2.8 => 1.2.8 
      @tarojs/plugin-babel: 1.2.8 => 1.2.8 
      @tarojs/plugin-csso: 1.2.8 => 1.2.8 
      @tarojs/plugin-sass: 1.2.8 => 1.2.8 
      @tarojs/plugin-uglifyjs: 1.2.8 => 1.2.8 
      @tarojs/redux: 1.2.8 => 1.2.8 
      @tarojs/redux-h5: 1.2.8 => 1.2.8 
      @tarojs/router: 1.2.8 => 1.2.8 
      @tarojs/taro: 1.2.8 => 1.2.8 
      @tarojs/taro-alipay: 1.2.8 => 1.2.8 
      @tarojs/taro-h5: 1.2.8 => 1.2.8 
      @tarojs/taro-swan: 1.2.8 => 1.2.8 
      @tarojs/taro-tt: 1.2.8 => 1.2.8 
      @tarojs/taro-weapp: 1.2.8 => 1.2.8 
      @tarojs/webpack-runner: 1.2.8 => 1.2.8 
      eslint-config-taro: 1.2.8 => 1.2.8 
      eslint-plugin-taro: 1.2.8 => 1.2.8

**Comment by Chen-jj** [comment]
@LailaiMaster 你可以直接使用 [swan.request](https://smartprogram.baidu.com/docs/develop/api/net_request/#request/) 再试试，定位一下是百度小程序的问题还是 Taro 的问题。
