### ISSUE TITLE
iphone 5s H5页面不显示

### ISSUE THREAD

**Issue by VonJie** [NervJS/taro#2009]
**问题描述**
[iphone 5s 浏览 H5 页面白屏，加入polyfill后，部分页面组件无法正常显示]

iphone 5s
![image](https://user-images.githubusercontent.com/13558164/51517803-f781a400-1e56-11e9-83c1-55611fdfedde.png)

iphone 7 正常
![image](https://user-images.githubusercontent.com/13558164/51517918-4fb8a600-1e57-11e9-84e6-57b2ac0893d9.png)

**系统信息**
 - 操作系统: [macOS 10.14]
 - Taro 版本 [v1.2.7]
 - Node.js 版本 [v8.11.3]
 - 报错平台 [h5]

**Comment by luckyadam** [comment]
能否调试一下样式看看为什么图标没有出来

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/bd53b6f343ad868f81c233f060830e439537fddf
1.2.8版本将router中的es6+的函数调用去掉了 可以去掉polyfill试一下

**Comment by VonJie** [comment]
@luckyadam 浏览器和iphone7手机显示都正常，iphone 5s图标不显示

**Comment by VonJie** [comment]
> [bd53b6f](https://github.com/NervJS/taro/commit/bd53b6f343ad868f81c233f060830e439537fddf)
> 1.2.8版本将路由器中的es6 +的函数调用去掉了可以去掉polyfill试一下

去掉polyfill，iphone 5s就白屏

**Comment by VonJie** [comment]
> 能否调试一下样式看看为什么图标没有出来

调整了下样式，图标出来了。
Swiper组件无法自动轮播，也无法左右切换

**Comment by jinjinjin0731** [comment]
h5 Swiper组件无法自动轮播正在找真机测试。

**Comment by Littly** [comment]
问题已不存在~
