### ISSUE TITLE
微信小程序支持自定义 tabbar 了，Taro是否也要支持下？

### ISSUE THREAD

**Issue by joyran** [NervJS/taro#2011]
微信小程序目前已经支持自定义 tabbar 组件了，但是需要在根目录下添加下面四个文件

custom-tab-bar/index.js
custom-tab-bar/index.json
custom-tab-bar/index.wxml
custom-tab-bar/index.wxss

我在src根目录新建 custom-tab-bar 文件夹，并新增index.js和index.less文件，但是并没有编译，这个需要怎么处理？

https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html

**Comment by luckyadam** [comment]
近期会支持到

**Comment by wugy0103** [comment]
同求

**Comment by javahuang** [comment]
@joyran @wugy0103 https://github.com/NervJS/taro/issues/2240#issuecomment-466261654

**Comment by gclsoft** [comment]
这个要如何使用, 有没例子? 我只设置了custome:true编译会报错:
```
编译  组件文件  src/custom-tab-bar
(node:367032) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pages' of undefined
    at buildPages (C:\Users\gz000069\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1190:27)
    at Object.build (C:\Users\gz000069\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:2217:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:367032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:367032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: ENOENT: no such file or directory, open 'C:\Users\Documents\WeChat Files\fhjjvfdff\Files\taroConverte\src\custom-tab-bar'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at buildSingleComponent (C:\Users\gz000069\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1737:31)
    at buildCustomTabbar (C:\Users\gz000069\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1090:9)
    at buildEntry (C:\Users\gz000069\AppData\Roaming\npm\node_modules\@tarojs\cli\src\weapp.js:1137:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Documents\\WeChat Files\\fhjjvfdff\\Files\\taroConverte\\src\\custom-tab-bar' }
编译  所有页面  
```

**Comment by Chen-jj** [comment]
@gclsoft 在 src 目录下新建 custom-tab-bar 目录存放组件即可，app.json 的配置参考微信小程序文档。

![image](https://user-images.githubusercontent.com/11807297/59179297-2beec600-8b94-11e9-9642-a43136da820a.png)

**Comment by zsirfs** [comment]
> @gclsoft 在 src 目录下新建 custom-tab-bar 目录存放组件即可，app.json 的配置参考微信小程序文档。
> 
> ![image](https://user-images.githubusercontent.com/11807297/59179297-2beec600-8b94-11e9-9642-a43136da820a.png)

小哥。你这个方式我试了一下。Taro 报警告了⚠️。

![image](https://user-images.githubusercontent.com/22249411/59244862-cd375400-8c48-11e9-9800-88117396000e.png)

**Comment by zsirfs** [comment]
![image](https://user-images.githubusercontent.com/22249411/59245077-b9402200-8c49-11e9-8acd-7cf2d26d9224.png)
这是报错

![image](https://user-images.githubusercontent.com/22249411/59245098-c8bf6b00-8c49-11e9-8ec3-6d434cea42ab.png)
编译的目录

**Comment by shenpvip** [comment]
请问hooks写法，在组件里如何拿到自定义tabbar的组件实例呢，如何获取getTabBar

**Comment by eattopking** [comment]
请问hooks写法，在组件里如何拿到自定义tabbar的组件实例呢，如何获取getTabBar

**Comment by wellssu0** [comment]
> 请问hooks写法，在组件里如何拿到自定义tabbar的组件实例呢，如何获取getTabBar

同问

**Comment by wugy0103** [comment]
这是来自QQ邮箱的自动回复邮件。
