### ISSUE TITLE
RichText className属性编译成h5不生效

### ISSUE THREAD

**Issue by liminshen** [NervJS/taro#2013]
**问题描述**
RichText className属性编译成h5不生效

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/14226199/51527480-839fc580-1e6f-11e9-8ce6-adf1d0fddc0a.png)
![image](https://user-images.githubusercontent.com/14226199/51527493-8995a680-1e6f-11e9-8f1b-f1ed66b1a589.png)

**期望行为**
className能编译成class

**系统信息**

Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by jinjinjin0731** [comment]
是个问题 今天修复
