### ISSUE TITLE
使用嵌套组件踩到的坑

### ISSUE THREAD

**Issue by w22296437978** [NervJS/taro#2019]
- css文件中使用@import, h5会报错
- 设置默认props，支付宝小程序在某些情况下会使用默认值，不适用传入的值
- 引入字体在index.html中通过link引入一次，否者h5图标不显示(百度小程序图标不显示原因未知)
- 在icon上绑定事件，支付宝小程序不支持
- 直接在模板内通过this.xx使用state.xx上面的变量，h5不支持
- 直接使用构造函数的props是无效的,要调用this.props
- 组件参数不要直接传递this.state,组件内部拿不到
- 在render中声明的变量会在打印this.state的时候绑定在this.state上面

**Comment by luckyadam** [comment]
每一条可以给一下示例代码

**Comment by w22296437978** [comment]
![image](https://user-images.githubusercontent.com/39508539/51578888-1127f780-1efa-11e9-9c07-d5c3694fd52a.png)

**Comment by w22296437978** [comment]
第二个复现不了了，没有做详细的记录，刚发现了一个问题是子组件的点击事件无法触发父组件的点击事件

**Comment by w22296437978** [comment]
微信，支付宝，tt小程序可以显示正常，h5必须在index link一下，百度小程序怎么整也不显示
![image](https://user-images.githubusercontent.com/39508539/51579707-f5722080-1efc-11e9-883d-7bb7399529a5.png)
![image](https://user-images.githubusercontent.com/39508539/51579736-03c03c80-1efd-11e9-9689-aad527458ea0.png)

**Comment by w22296437978** [comment]
小程序图标点击事件无效
![image](https://user-images.githubusercontent.com/39508539/51579955-cd36f180-1efd-11e9-83a7-8a64f6be44a4.png)

**Comment by w22296437978** [comment]
sorry '直接在模板内通过this.xx使用state.xx上面的变量，h5不支持' 这一个记错了，应该是直接使用state上的变量不可以，使用this.state.xx可以
![image](https://user-images.githubusercontent.com/39508539/51580308-0328a580-1eff-11e9-868a-02c4c1c1755d.png)
![image](https://user-images.githubusercontent.com/39508539/51580355-1e93b080-1eff-11e9-8048-7ddd19e2977c.png)

**Comment by w22296437978** [comment]
微信小程序可以跳转，支付宝不可以跳转，并且刚开始的时候还不能触发父级组件的点击事件（现在可以了emmmm），现在是拿不到参数
![image](https://user-images.githubusercontent.com/39508539/51581477-2e14f880-1f03-11e9-8790-6785e99d5e29.png)
![image](https://user-images.githubusercontent.com/39508539/51581526-64eb0e80-1f03-11e9-84c3-04a44861a23d.png)

**Comment by w22296437978** [comment]
当我将this.props.props 转换为props.props的时候，微信也不能跳转了
![image](https://user-images.githubusercontent.com/39508539/51581732-40dbfd00-1f04-11e9-816e-80dd9331e88e.png)

**Comment by w22296437978** [comment]
我将传递给父组件的参数换成this.state，父级组件的参数直接为null
![image](https://user-images.githubusercontent.com/39508539/51581846-c95a9d80-1f04-11e9-9b13-8c57ccc2ec5f.png)

**Comment by w22296437978** [comment]
循环内使用父组件+子组件的方法，第一个向父组件传递的参数会出现问题（支付宝小程序）
![image](https://user-images.githubusercontent.com/39508539/51586260-73dbbc00-1f17-11e9-9709-0a6a002cd090.png)

**Comment by w22296437978** [comment]
上一个问题已解决，在构造函数当中设置了一次this.stata.imgs[0]=.... 总感觉框架可能处理的有问题
![image](https://user-images.githubusercontent.com/39508539/51586979-362c6280-1f1a-11e9-8189-14b0329a2f8b.png)

**Comment by w22296437978** [comment]
好吧 我错了，构造函数里只能设置默认值，不能对数据进行处理，应当在声明周期函数里进行处理，否则各种坑

**Comment by w22296437978** [comment]
tt小程序里即使我在声明周期函数里面进行处理也会出现使用默认值的问题
![image](https://user-images.githubusercontent.com/39508539/51589027-b05fe580-1f20-11e9-856b-15cf0b7f10a5.png)

**Comment by shenghanqin** [comment]
可以试试看最新版本？
其实我是感觉微信>qq>支付宝>字节跳动小程序，就是小程序本身的完善程度。
