### ISSUE TITLE
自定义组件的根节点不能通过className添加css class, 也不能通过onClick绑定事件

### ISSUE THREAD

**Issue by uxwine** [NervJS/taro#2021]
**问题描述**
自定义组件的根节点不能通过className添加css class, 也不能通过onClick绑定事件

**复现步骤**
1. 自定义组件Container
2. 在Page的render里面使用Container，并在该页面的less中添加abc样式，添加onTest方法
3. 添加className="abc",添加onClick={this.onTest}
4. Container的样式没有变化，点击也没有效果。
5. 如果将onClick改成bindtap，点击时间成功发出，但是会提示错误。

/components/Container/index.tsx

```js
...
render(){
  return (
    <Block>{this.props.children}</Block>
 )
}
...
```

/pages/Home/index.less
```css
.abc {
 background:red;
}
```

/pages/Home/index.tsx
```js
...
render(){
 return (<Container onClick={this.onTest} className="abc" bindtap={this.onTest}/>)
}
...
```

**期望行为**
编译器补充自定义组件对原生props的支持，比如自定义组件的props继承自基础的Props(style, className, onClick)，编译的时候可以正常的将className翻译成class, onClick翻译成bindtap之类。

**报错信息**

VM1298:1 Component "pages/Home/index" does not have a method "onTest" to handle event "tap".
console.warn @ VM1298:1
(anonymous) @ WAService.js:1
f @ WAService.js:1
(anonymous) @ WAService.js:1
n @ WAService.js:1
e @ appservice?t=1548216504359:2420
r.registerCallback.t @ appservice?t=1548216504359:2420
l.forEach.t @ appservice?t=1548216504359:2420
(anonymous) @ appservice?t=1548216504359:2420
s.onmessage @ appservice?t=1548216504359:2420

**系统信息**
 - 操作系统: [macOS High Sierra 10.13.6]
 - Taro 版本 [v1.2.4]
 - Node.js 版本 [10.9.0]
 - 报错平台 [weapp]

**补充信息**
1. 如果将className改成class，编译之后，wxml中显示会保持class这个属性，然后就abc就可以成功修改container的样式。
2. 如果将onClick改成bindtap，点击后会提示没有onTest方法，但是应该是激发了点击事件。

**Comment by sage-z** [comment]
> 为了和 `react` 的规范保持一致，自定义组件不能直接通过 `className` 来设置 `class`，你可以直接写 `class` 代替，或者组件内部用 `this.props.className` 来获取
> 同样也是规范所至，组件的不能直接绑定 `onClick`，你需要在组件内部调用 `this.props.onClick` 来触发

Taro 1.0.7 版本是可以的，是新加的规范吗

**Comment by luckyadam** [comment]
@sage-z 按照 react 规范来吧
