### ISSUE TITLE
支付宝 组件方法报错 component.$scope.selectComponent is not a function

### ISSUE THREAD

**Issue by Iceo4** [NervJS/taro#2026]
最新版本看到修复支付宝ref，但这个问题还是存在用component.$scope.selectComponent is not a function

**Comment by Iceo4** [comment]
> 最新版本看到修复支付宝ref，但这个问题还是存在用component.$scope.selectComponent is not a function

**Comment by harrydengchao** [comment]
同样存在这个问题
