### ISSUE TITLE
编译控制台打印路径错误

### ISSUE THREAD

**Issue by wq1308786830** [NervJS/taro#2027]
编译控制台打印路径错误，打印如下
`修改  组件文件  src/pages/common/order/ListComponent.js
编译  组件文件  src/pages/common/order/ListComponent.js
生成  组件配置  dist/dist/pages/common/order/ListComponent.json
生成  组件逻辑  dist/dist/pages/common/order/ListComponent.js
生成  组件模板  dist/dist/pages/common/order/ListComponent.wxml
生成  组件样式  dist/dist/pages/common/order/ListComponent.wxss`

**Comment by shenghanqin** [comment]
1.3.22及之前的版本也有这个问题，不过不影响使用。
