### ISSUE TITLE
支付宝组件ref报错 component.$scope.selectComponent is not a function

### ISSUE THREAD

**Issue by Iceo4** [NervJS/taro#2028]
**问题描述**
页面引用组件 给组件使用ref 。微信编译不报错，支付宝报错

**复现步骤**
[复现问题的步骤]
注册页面：
import Com from './com.js'
.......
render () {
   
    return (
      <View>
        <Com ref='test'>
        </Com>
      </View>
      
    )
  }
组件：
render () {
   
    return (
      <View>
        12444
      </View>
    )
  }
编译报错：
**报错信息**
TypeError: component.$scope.selectComponent is not a function
    at index.js:2378
    at Array.forEach (<anonymous>)
    at componentTrigger (index.js:2374)
    at index.js:3494
    at af-appx.worker.ide.min.js:7
    at Array.forEach (<anonymous>)
    at af-appx.worker.ide.min.js:7
    at ut.batchedUpdates (af-appx.worker.ide.min.js:7)
    at ut.ready (af-appx.worker.ide.min.js:7)
    at r (af-appx.worker.ide.min.js:7)
定位报错代码：
if (ref.type === 'component') {
        target = component.$scope.selectComponent("#".concat(ref.id)); //（报错）**
          target = target ? target.$component || target : null;
        } else {
          var query = my.createSelectorQuery().in(component.$scope);
          target = query.select("#".concat(ref.id));
        }

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.2.8 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.8 => 1.2.8 
      @tarojs/mobx: 1.2.8 => 1.2.8 
      @tarojs/mobx-h5: 1.2.8 => 1.2.8 
      @tarojs/mobx-rn: 1.2.8 => 1.2.8 
      @tarojs/plugin-babel: 1.2.8 => 1.2.8 
      @tarojs/plugin-csso: 1.2.8 => 1.2.8 
      @tarojs/plugin-less: 1.2.8 => 1.2.8 
      @tarojs/plugin-uglifyjs: 1.2.8 => 1.2.8 
      @tarojs/router: 1.2.8 => 1.2.8 
      @tarojs/taro: 1.2.8 => 1.2.8 
      @tarojs/taro-alipay: 1.2.8 => 1.2.8 
      @tarojs/taro-h5: 1.2.8 => 1.2.8 
      @tarojs/taro-swan: 1.2.8 => 1.2.8 
      @tarojs/taro-weapp: 1.2.8 => 1.2.8 
      @tarojs/webpack-runner: 1.2.8 => 1.2.8 
      eslint-config-taro: 1.2.8 => 1.2.8 
      eslint-plugin-taro: 1.2.8 => 1.2.8

**Comment by Iceo4** [comment]
额 好吧

**Comment by Iceo4** [comment]
> 额 好吧



> 嗯支付宝的同学说不考虑提供此 selectComponent API，所以父组件获取子组件需要另寻他法，尽快解决

额 好吧

**Comment by Lionad-Morotar** [comment]
围观

**Comment by Chen-jj** [comment]
已修复，支付宝开发者工具版本必须高于或等于 v0.29.0-beta.9（尝鲜版）即可正常使用 ref 。

![image](https://user-images.githubusercontent.com/11807297/55704759-90b06780-5a0f-11e9-9142-a1c25dac249e.png)

**Comment by GYDSB** [comment]
已经升级到0.29.1-beta.12 仍然出现TypeError: component.$scope.selectComponent is not a function报错

**Comment by Chen-jj** [comment]
@GYDSB Taro 也要升级
