### ISSUE TITLE
有完整的支持 jsx 语法的列表吗？

### ISSUE THREAD

**Issue by xialvjun** [NervJS/taro#203]
看了你们的文章 https://zhuanlan.zhihu.com/p/38498030 里面有这么一句：

> 以上仅仅是我们转换规则的冰山一角， JSX 的写法极其灵活多变，我们只能通过穷举的方式，将常用的、React 官方推荐的写法作为转换规则加以支持，而一些比较生僻的，或者是不那么推荐的写的写法则不做支持，转而以 eslint 插件的方式，提示用户进行修改。目前我们支持的 JSX转换规则，大致能覆盖到 JSX 80% 的写法操作。

所以，如题，有完整的支持 jsx 语法的列表吗？

**Comment by yuche** [comment]
理论上来说 [ESLint插件](https://github.com/NervJS/taro/tree/master/packages/eslint-plugin-taro) 没提到的都可以支持，但在真实应用场景肯定有许多 cover 不到的地方。

如果你遇到了不支持的语法可以提 issue，有办法做支持我们就做支持，不能做我们就做 ESLint 插件。
