### ISSUE TITLE
微信小程序自定义组件无法热更新

### ISSUE THREAD

**Issue by UZIhuhuhu** [NervJS/taro#2032]
**问题描述**
修改自定义组件的代码时候，无法热更新
显示 `警告  JS文件    xxx.js 没有被引用到，不会被编译`
如果修改自定义组件里的代码，我每次都需要重新编译

**复现步骤**

- 代码里用到的自定义组件

```js
  config = {
    usingComponents: {
      'canvas-drag': '../../utils/canvas-drag/index'
    }
  };
```

- 编译情况
<img width="1055" alt="qq20190124-164746 2x" src="https://user-images.githubusercontent.com/31771183/51666419-bcb77180-1ff8-11e9-8a10-9d6337d4cea2.png">

**期望行为**
自定义组件的修改也能热更新

**报错信息**
警告  JS文件    xxx.js 没有被引用到，不会被编译

**系统信息**

 - 操作系统： macOS 10.14
 - Taro 版本：Taro v1.2.0-beta.6
 - 报错平台： 微信小程序

**Comment by nxboo** [comment]
问题解决了吗？

**Comment by shenghanqin** [comment]
再试试最新版本？
