### ISSUE TITLE
微信小程序父组件向子组件传函数，子组件不识别，全部为null

### ISSUE THREAD

**Issue by LYfirstday** [NervJS/taro#2035]
**问题描述**
父组件向子组件传递带参数的函数类型props，子组件全部显示为null

**复现步骤**
父组件:
export default class Register extends Component {
  constructor (props) {
    super(props);
    this.state = {
      companyId: '',
      referrerId: '',
      jingLuoId: ''
    }
  }

  doChoseCompany = (comId) => {
    this.setState({companyId: comId});
  }

  doChoseReferrer = (userId) => {
    this.setState({referrerId: userId});
  }

  getComId = (comId) => {
    this.setState({ jingLuoId: comId });
  }

  render() {
    return (
         <MemberView
            getComId={this.getComId}
            doChoseReferrer={this.doChoseReferrer}
            doChoseCompany={this.doChoseCompany}
          />
    )
  }
}
![image](https://user-images.githubusercontent.com/25970534/51668791-eaeb8000-1ffd-11e9-9ee2-62498974a71c.png)

子组件(主要回调父组件函数传递数据，下面函数的参数是子组件获取的，回调父组件函数)：
export default class MemberView extends Component {
  constructor(props) {
    super(props);
  }

  doChoseReferrer = (userId) => {
    this.props.doChoseReferrer(userId);
  }

  doChoseCompany = (comId) => {
    this.props.doChoseCompany(comId);
  }

  getComId = (comId) => {
    console.log(this.props)
    this.props.getComId(comId);
  }
}
![image](https://user-images.githubusercontent.com/25970534/51668835-06ef2180-1ffe-11e9-8cf9-94dd6e05ff82.png)

**期望行为**
子组件正确回调父组件传递的函数并传递数据

**报错信息**
![image](https://user-images.githubusercontent.com/25970534/51668647-a6f87b00-1ffd-11e9-9b21-4eeadacf67d6.png)

**系统信息**
Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.4.0 - E:\nodeJs\node.EXE
      Yarn: 1.12.3 - E:\Yarn\bin\yarn.CMD
      npm: 6.5.0 - E:\nodeJs\npm.CMD
**补充信息**
[可选]

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/event.html#%E4%BB%BB%E4%BD%95%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E9%83%BD%E8%A6%81%E4%BB%A5-on-%E5%BC%80%E5%A4%B4

**Comment by LYfirstday** [comment]
失误失误~~没仔细看文档
