### ISSUE TITLE
所有page的constructor都会预先执行一次吗？

### ISSUE THREAD

**Issue by xiaofengz** [NervJS/taro#2038]
发现进到任何一个page的时候，所有其他page的constructor都会被执行？

**Comment by yuche** [comment]
是的，详情可以看文档：

https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
