### ISSUE TITLE
为什么Taro.showModal没有关闭modal的方法

### ISSUE THREAD

**Issue by IFmiss** [NervJS/taro#2039]
**问题描述**
Taro.showModal 在h5 的弹窗中，如果在弹窗的状态下，点击返回，页面的弹窗并没有被关闭，而是一直显示在屏幕上
本来想着在 componentWillUnmount 执行关闭弹窗的方法，发现并没有关闭弹窗的功能

然后我这样执行的
App.js中注册Taro.hideModal方法
```js
Taro.hideModal = function () {
            document.getElementsByClassName('taro__modal')[0].style.cssText = `
            opacity: 0; transition: opacity 0.2s linear; display: none;`
        }
```
然后在其他需要弹窗的页面
```js
componentWillUnmount () {
        Taro.hideModal()
    }
```

**期望行为**
这只是h5我自己弄得临时解决方式，我在官网上没有找到关闭的方法，如果以后需要兼容各个端肯定是不行的，还希望有其他解决方法

**报错信息**

**系统信息**
ios 11   新版微信客户端  有底部白色菜单的那种

 - 操作系统: [e.g. ios 11]
 - Taro 版本 [e.g. 1.2.4]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by IFmiss** [comment]
Taro.hideModal = function () {
            if (!document.getElementsByClassName('taro__modal').length) return
            document.getElementsByClassName('taro__modal')[0].style.cssText = `
            opacity: 0; transition: opacity 0.2s linear; display: none;`
        };
添加一个元素长度判断

**Comment by luckyadam** [comment]
是 `showModal` API 的问题，不用增加一个 `hideModal` 的 api

**Comment by Littly** [comment]
3b51504e3d835a9d076e134bae2dfa8bc24b5480 现在跳转的时候会把modal隐藏掉了
