### ISSUE TITLE
h5 input file文件选择会报错 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#2043]
Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at Input.componentDidMount (lib.dll.js:1)
    at lib.dll.js:1
    at errorCatcher (lib.dll.js:1)
    at lib.dll.js:1
    at Array.forEach (<anonymous>)
    at flushMount (lib.dll.js:1)
    at updateComponent (lib.dll.js:1)
    at Route.forceUpdate (lib.dll.js:1)
    at lib.dll.js:1
    at <anonymous>

**Comment by jinjinjin0731** [comment]
真机 or 浏览器？  taro 版本， 麻烦提供一下

**Comment by ShaoGongBra** [comment]
@jinjinjin0731 我的所有环境似乎都会有，chrome，安卓微信、苹果默认浏览器
<Input ref='h5file' type='file' style={{display:'none'}} onChange={this.h5Upload.bind(this)} />
我是这样写的，然后手动触发了click不知道是不是这个引起的
this.refs.h5file.inputRef.click()

**Comment by ShaoGongBra** [comment]
@jinjinjin0731 虽然他会报错，但是这个也能正常使用，但是似乎还有另外一个问题，onchange似乎会触发两次

**Comment by jinjinjin0731** [comment]
taro info 一下 我需要你的版本号相关信息

**Comment by ShaoGongBra** [comment]
@jinjinjin0731 之前是1.2.7，今天刚升级到1.2.8还没测试

**Comment by ShaoGongBra** [comment]
@jinjinjin0731 
taro info
� Taro v1.2.8


  Taro CLI 1.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Users\admin\AppData\Roaming\

**Comment by ShaoGongBra** [comment]
@jinjinjin0731 你可以远程看我的报错吗，他是一进去页面就会报错，不是后面点击的时候报错的

**Comment by ShaoGongBra** [comment]
@jinjinjin0731 还有我这个input是放在子组建里面的

**Comment by jinjinjin0731** [comment]
提供一下你的复现代码。不然我不好定位问题啊。
