### ISSUE TITLE
通过bind绑定的参数如果为undefined,那么事件中的这一个参数将会被移除，后面的参数位置-1

### ISSUE THREAD

**Issue by w22296437978** [NervJS/taro#2044]

**Comment by w22296437978** [comment]
![image](https://user-images.githubusercontent.com/39508539/51720054-f46cfa80-2086-11e9-9dd8-adaf922bd9c4.png)

**Comment by Chen-jj** [comment]
@w22296437978 小程序事件传 undefined 值的参数会被过滤掉，可以传 null 代替。
