### ISSUE TITLE
支付宝class 编译 逗号

### ISSUE THREAD

**Issue by Iceo4** [NervJS/taro#2045]
**问题描述**
支付宝 className 用数组方式  编译后有逗号，微信没有

**复现步骤**
 源码 ：<View className={['a','b']}>ddd</View>
支付宝 编译后：
<View class='a,b'>
 </View>
微信编译
<View class='a b'>
 </View>

**期望行为**
希望改进  这样支付宝也可以用数组方式写class

**Comment by yuche** [comment]
有没有复现

**Comment by Iceo4** [comment]
> 有没有复现
更新了问题

**Comment by yuche** [comment]
taro/react 是不支持直接传入数组的，这个你得自己引入一个叫 classNames 的库。
