### ISSUE TITLE
组件参数传递

### ISSUE THREAD

**Issue by w22296437978** [NervJS/taro#2046]
这个sub接受的是长度为7的数组，我没有办法在组件内拿到他，但是当我在打印了一次log之后，就可以拿到了
![image](https://user-images.githubusercontent.com/39508539/51723502-51bb7880-2094-11e9-8850-d748c3bfaf16.png)
![image](https://user-images.githubusercontent.com/39508539/51723526-6e57b080-2094-11e9-9dc7-b0f0d8813f2e.png)

**Comment by yuche** [comment]
写一个 defaultProps

https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%99%E7%BB%84%E4%BB%B6%E8%AE%BE%E7%BD%AE-defaultprops
