### ISSUE TITLE
tabbar在h5下不显示

### ISSUE THREAD

**Issue by geminiyu233** [NervJS/taro#2047]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
tabbar在h5下不显示（抱歉翻了相关issue没有发现有用的解决方案，只好又新开一个）
**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js
config = {
    pages: [
      'pages/index/index',
      'pages/findCar/index',
      'pages/findGoods/index',
      'pages/aboutUs/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#409EFF',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'white',
      enablePullDownRefresh: true
    },
    tabBar: {
      color: '#333',
      selectedColor: '#409EFF',
      backgroundColor: '#fff',
      borderStyle: '#ccc',
      list: [{
        pagePath: "pages/home/index",
        text: "首页",
        iconPath: "./images/tab/home.png",
        selectedIconPath: "./images/tab/home-active.png"
      }, {
        pagePath: "pages/findCar/index",
        text: "找车",
        iconPath: "./images/tab/cart.png",
        selectedIconPath: "./images/tab/cart-active.png"
      },{
        pagePath: "pages/findGoods/index",
        text: "找货",
        iconPath: "./images/tab/goods.png",
        selectedIconPath: "./images/tab/goods-active.png"
      },{
        pagePath: "pages/aboutUs/index",
        text: "关于我们",
        iconPath: "./images/tab/aboutUs.png",
        selectedIconPath: "./images/tab/aboutUs-active.png"
      }]
    }
  }

```

**期望行为**
h5下正常显示tabbar

![image](https://user-images.githubusercontent.com/26594368/51728384-0e203900-20ab-11e9-8a39-8be1c0ec7e92.png)

**报错信息**

![image](https://user-images.githubusercontent.com/26594368/51728303-c00b3580-20aa-11e9-9757-85930e05bcd7.png)

**系统信息**

Taro v1.2.8

  Taro CLI 1.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - E:\node\node.EXE
      Yarn: 1.13.0 - E:\node\node_global\yarn.CMD
      npm: 6.5.0 - E:\node\npm.CMD

**补充信息**

默认会带上这个display: none，去掉就好使了

**Comment by peng8934763** [comment]
在 H5 模式下，tabBar 可能会挡住页面 fixed 元素问题：这是因为与小程序的 tabBar 不同，在 H5 下 tabBar 是一个普通的组件，当页面中存在fixed(bottom)定位的元素时，其表现会与小程序中不一致。Taro 提供了一个适配的方法：

.fixed {
  bottom: 0;
  /* 在 H5 模式下将会编译成 margin-bottom: 50px，在小程序模式下则会忽略*/
  margin-bottom: taro-tabbar-height;
}

**Comment by Littly** [comment]
看你这个代码没什么问题 复现问题需要什么操作吗？

**Comment by zwblue** [comment]
默认在h5打包下是隐藏的

**Comment by zwblue** [comment]
在小程序中先运行有没有报错，报错了改下，再重新run dev:h5试试

**Comment by CheerySlowbro** [comment]
小程序下

```scss
.fixed {
    // sass-lint:disable no-duplicate-properties
    bottom: calc(taro-tabbar-height + constant(safe-area-inset-bottom));
    bottom: calc(taro-tabbar-height + env(safe-area-inset-bottom));
}
```

这种写法，编译的时候taro-tabbar-height没有编译成 0px @Littly

**Comment by wenxiayili** [comment]
> Hello~
> 
> 您的问题所提供的信息不足，我们无法定位到具体的问题。如果有空的话还请拔冗提供更具体的信息，否则这个 issue 将在 15 天后被自动关闭。
> 
> 如果您在这 15 天中更新更多信息自动关闭的流程会自动取消，如有其他问题也可以发起新的 Issue。
> 
> Good luck and happy coding~

> 看你这个代码没什么问题 复现问题需要什么操作吗？

我看这么多issues,你发的最多的就是信息不足？

**Comment by wenxiayili** [comment]
> 在 H5 模式下，tabBar 可能会挡住页面 fixed 元素问题：这是因为与小程序的 tabBar 不同，在 H5 下 tabBar 是一个普通的组件，当页面中存在fixed(bottom)定位的元素时，其表现会与小程序中不一致。Taro 提供了一个适配的方法：
> 
> .fixed {
> bottom: 0;
> /* 在 H5 模式下将会编译成 margin-bottom: 50px，在小程序模式下则会忽略*/
> margin-bottom: taro-tabbar-height;
> }

我页面没没有fixed定位 就一个轮播 也是这个bug
