### ISSUE TITLE
vant-weapp area组件内容不显示。

### ISSUE THREAD

**Issue by zhangzhengyou** [NervJS/taro#2049]
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import provinceList from "../../utils/province";
import './index.scss'

class Index extends Component {

    config = {
    navigationBarTitleText: '首页',
    usingComponents: {
      "van-area": "../../components/vant/area/index"
    }
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <van-area
          value="110101"
          columns-num={3}
          area-list={provinceList}
        />
      </View>
    )
  }
}

export default Index;

**Comment by yuche** [comment]
你 render 的代码没写

**Comment by luckyadam** [comment]
代码再贴全一点吧

**Comment by zhangzhengyou** [comment]
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import provinceList from "../../utils/province";
import './index.scss'

class Index extends Component {

    config = {
    navigationBarTitleText: '首页',
    usingComponents: {
      "van-area": "../../components/vant/area/index"
    }
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <van-area
          value="110101"
          columns-num={3}
          area-list={provinceList}
        />
      </View>
    )
  }
}

export default Index;

**Comment by zhangzhengyou** [comment]
render () {
    return (
      <View className='index'>
        <van-area
          value="110101"
          columns-num={3}
          area-list={provinceList}
        />
      </View>
    )
  }

**Comment by zhangzhengyou** [comment]
import Taro, { Component } from '@tarojs/taro'import { View, Button, Text } from '@tarojs/components'import provinceList from "../../utils/province";import './index.scss'class Index extends Component {config = {navigationBarTitleText: '首页',usingComponents: {"van-area": "../../components/vant/area/index"}}componentWillReceiveProps (nextProps) {console.log(this.props, nextProps)}componentWillUnmount () { }componentDidShow () { }componentDidHide () { }render () {return (<View className='index'><van-areavalue="110101"columns-num={3}area-list={provinceList}/></View>)}}export default Index;

**Comment by luckyadam** [comment]
```jsx
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import provinceList from '../../utils/province'

class Index extends Component {
  config = {
    navigationBarTitleText: '首页',
    usingComponents: {
      'van-area': '../../components/vant/area/index'
    }
  }
  state = {
    areaList: {}
  }
  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }
  componentDidMount () {
    this.setState({
      areaList: provinceList
    })
  }
  componentDidShow () { }
  componentDidHide () { }
  render () {
    return (
      <van-area value='110101' columns-num={3} area-list={areaList} />
    )
  }
}
export default Index
```
改成动态设置吧，看了下 vant 的代码，直接设置不能生效，而且为了减少小程序大小，最好像 vant 的 demo 那样，把数据文件做成动态加载
