### ISSUE TITLE
是否支持完全使用 typescript 进行开发。

### ISSUE THREAD

**Issue by Reamd7** [NervJS/taro#205]
使用官方 cli 生成typescript 项目之后，（未进行任何进一步的配置），编译并不成功

**Comment by zacksleo** [comment]
完全支持呀。 你报的啥错误？具体复现的流程是什么

**Comment by Dithub2016** [comment]
$ npm install -g @tarojs/cli

**Comment by Dithub2016** [comment]
![image](https://user-images.githubusercontent.com/23295172/41906081-7f5b5a8e-796f-11e8-90da-8a6e8f80ea81.png)

在 h5 的 dev 命令下，
修改 /src/app.tsx 文件，然后命令行就死在这里了

**Comment by Dithub2016** [comment]
忘了一点，
初始化项目后，
npm install
运行 h5 build 是不通过的 , 
![image](https://user-images.githubusercontent.com/23295172/41906751-487f0a86-7971-11e8-8e40-6065c7212cbc.png)
可以看到 明明选择的是 使用 typescript ，
但是 package.json 文件根本没有 @tarojs/plugin-typescript 这一项，
直到运行了 weapp 的相关命令后，才自动安装了上面那一个，
编译才会不报错

**Comment by luckyadam** [comment]
@Dithub2016 H5 端使用 TS 还有些问题，预计明天可以修复，小程序端是可以使用的

**Comment by Dithub2016** [comment]
![image](https://user-images.githubusercontent.com/23295172/41909609-0b3982a6-797a-11e8-844c-b5aaa9323fde.png)
![image](https://user-images.githubusercontent.com/23295172/41909624-1856e8e8-797a-11e8-847f-acb3e5ba7a99.png)
在选择不用 typescript 生成的项目的情况下
修改了 babel 的设置，h5 的编译通过了。。。。
![image](https://user-images.githubusercontent.com/23295172/41909716-542faa1c-797a-11e8-8819-8d5de4ad765c.png)
小程序的是通不过的，
我根本就没用 npm install 这个 stage-2 的 preset 啊，所以应该都不通过才对，
然后 /config/index.js 里面修改的 babel 配置没有反应，
我是直接改了 node_modules/@tarojs/cli/src/config/babel.js 里的babel 配置，加了 stage-2 才导致的这个问题，原由是 h5 的 babel 编译出来的结果的，运行时的报了一些 Object.assign, 和 Map 之类的 es6 错误

**Comment by Reamd7** [comment]
有一个妥协的解决办法：
1、根据react-scripts-ts-antd（可能react-script-ts也可以，未测试）作为基础模板新建项目，
2、安装   "@tarojs/components": "0.0.59","@tarojs/taro": "0.0.59", "nervjs": "^1.3.0",到项目中，
3、禁用tslint（因为@tarojs/components的d.ts有一丢丢问题，加上免得排那么多错）
4、根据Nerv官网的教程修改react-script的默认配置（https://nervjs.github.io/docs/guides/switching-to-nerv.html），当然你也可以使用内置的react-app-rewired修改配置。
5、修改一些类型错误。。（内置d.ts的bug）
6、Taro.render 改成 Nerv.render（我也不知道为啥）
7、每个tsx都要引入import Nerv from "nervjs"，以保证识别（我没尝试其他办法）
============================================
若在taro的基础上搞是不能简单把Nerv引入的。（尝试过一下，失败了）

**Comment by fangkyi03** [comment]
没有tslint来约束

**Comment by Reamd7** [comment]
更新完之后依旧不行，建议将小程序的打包和H5模式打包区分开来。更新之后产生显示缺乏typescript依赖，之后又显示webpack版本过低。npm i -d webpack 还产生错误。

**Comment by luckyadam** [comment]
@Reamd7 H5 的 TS 支持正在加紧开发中

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/490e7cb36ca9b3ad9f80c4475d6c023e87b6561a

装最新的版本 0.0.68 应该就能解决了

**Comment by CHENFANGC** [comment]
![image](https://user-images.githubusercontent.com/29766018/185558288-205c1d87-689d-40f8-8105-12c870cfde90.png)
