### ISSUE TITLE
ios 兼容性问题【紧急】

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#2052]
**问题描述**

IOS 10.3 版本以下报错

**期望行为**
正常

**报错信息**

![c60f34f8-4051-4dd0-ad17-bde1a3d88441](https://user-images.githubusercontent.com/7480381/51732935-cf927a80-20ba-11e9-9323-b9ff4eb345f7.jpg)

**系统信息**

 Taro CLI 1.2.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.8 => 1.2.8
      @tarojs/components: 1.2.8 => 1.2.8
      @tarojs/plugin-babel: 1.2.8 => 1.2.8
      @tarojs/plugin-csso: 1.2.8 => 1.2.8
      @tarojs/plugin-sass: 1.2.8 => 1.2.8
      @tarojs/plugin-uglifyjs: 1.2.8 => 1.2.8
      @tarojs/redux: 1.2.8 => 1.2.8
      @tarojs/redux-h5: 1.2.8 => 1.2.8
      @tarojs/router: 1.2.8 => 1.2.8
      @tarojs/taro: 1.2.8 => 1.2.8
      @tarojs/taro-h5: 1.2.8 => 1.2.8
      @tarojs/taro-weapp: 1.2.8 => 1.2.8
      @tarojs/webpack-runner: 1.2.8 => 1.2.8
      eslint-config-taro: 1.2.8 => 1.2.8
      eslint-plugin-taro: 1.2.8 => 1.2.8

 - 操作系统: [e.g. IOS 10.1.1]
 - Taro 版本 [e.g. v.1.2.8]
 - Node.js 版本 [e.g. v10.15.0]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
你可以手动引入 Object.values 的 polyfill，或者使用 lodash 等替代解决这个问题

**Comment by youngluo** [comment]
@yuche 能否通过 Taro 配置来解决？这样不能确定是否还有其他的 api 不兼容

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#pluginsbabel

你可以通过 babel-plugin-env 来配置你需要兼容到的系统。

**Comment by youngluo** [comment]
@yuche 建议将这些兼容性内置，IOS 10.3 下都无法正常运行（这个坑埋的太深了😂，直接影响线上项目运行）

**Comment by nyrf** [comment]
@youngluo 我也有这种情况，请问你最后引入了哪个

**Comment by luckyadam** [comment]
@youngluo  `Object.values` 是 es6 的语法，只能自行通过加 polyfill 或者使用 `babel-plugin-transform-runtime` 插件来解决，Taro 只能提供给你引入这些东西能力，具体问题还是要自己来解决

**Comment by youngluo** [comment]
@nyrf 直接加了一个 polyfill

`Object.values = Object.values || _.values`

**Comment by youngluo** [comment]
> @youngluo `Object.values` 是 es6 的语法，只能自行通过加 polyfill 或者使用 `babel-plugin-transform-runtime` 插件来解决，Taro 只能提供给你引入这些东西能力，具体问题还是要自己来解决

Taro 本来就会做语法的转译工作，为什么不做彻底呢？这样埋坑太深了😂。而且 Object.values 是 Taro UI 的 calendar 组件使用的

**Comment by luckyadam** [comment]
@youngluo 这样子，那 Taro UI 得调整下，我们会尽量避免使用 es6 的方法，如果用了也会加 polyfill 的，但如果用户自己用了就只能通过我说的两个方式解决了

**Comment by nyrf** [comment]
> @nyrf 直接加了一个 polyfill
> 
> `Object.values = Object.values || _.values`

哦，你直接用了lodash，我没用lodash, 直接用了下面方法，https://stackoverflow.com/questions/35090153/babel-support-for-object-entries

```
Object.values = Object.values || (x => Object.keys(x).map(k => x[k]));
Object.entries = Object.entries || (x => Object.keys(x).map(k => [k, x[k]]));
```

**Comment by youngluo** [comment]
@luckyadam 多谢

**Comment by js-newbee** [comment]
@youngluo 这个其实是小程序的坑，还是要多多看文档哈，官方文档说得很清楚了
https://developers.weixin.qq.com/miniprogram/dev/framework/details.html#%E5%AE%A2%E6%88%B7%E7%AB%AF-es6-api-%E6%94%AF%E6%8C%81%E6%83%85%E5%86%B5

**Comment by youngluo** [comment]
> > @youngluo `Object.values` 是 es6 的语法，只能自行通过加 polyfill 或者使用 `babel-plugin-transform-runtime` 插件来解决，Taro 只能提供给你引入这些东西能力，具体问题还是要自己来解决
> 
> Taro 本来就会做语法的转译工作，为什么不做彻底呢？这样埋坑太深了😂。而且 Object.values 是 Taro UI 的 calendar 组件使用的

@js-newbee

**Comment by wweggplant** [comment]
楼主解决了么 我也遇到了

**Comment by anyexinglu** [comment]
> @youngluo `Object.values` 是 es6 的语法，只能自行通过加 polyfill 或者使用 `babel-plugin-transform-runtime` 插件来解决，Taro 只能提供给你引入这些东西能力，具体问题还是要自己来解决

@luckyadam 

事实上，我们早就用 babel-preset-taro（v3.0.23），且这个包已经内置了 @babel/plugin-transform-runtime（v7.1.0），附[Taro 相关说法](https://taro-docs.jd.com/taro/blog/2020-09-01-taro-versions/#%E5%85%B3%E4%BA%8E-async-functions-%E7%9A%84%E4%BD%BF%E7%94%A8)：

![image](https://user-images.githubusercontent.com/8243326/115656238-741dc880-a367-11eb-9e95-d07397827a0f.png)

但 Object.values 是 es7 提案引入的， [Object.values](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/values)
![image](https://user-images.githubusercontent.com/8243326/115656109-2d2fd300-a367-11eb-9ab7-f1f723421c2f.png)

目前的 babel-preset-taro 没有编译，所以还是会有问题。
