### ISSUE TITLE
麻烦看下报错

### ISSUE THREAD

**Issue by 419280377** [NervJS/taro#2053]
一、报错信息
![image](https://user-images.githubusercontent.com/20454290/51735491-880fec80-20c2-11e9-8469-f8bfacf538b8.png)

二、render()
![image](https://user-images.githubusercontent.com/20454290/51735526-9c53e980-20c2-11e9-8637-8a9bbd5c7bb7.png)

三、JSX
![image](https://user-images.githubusercontent.com/20454290/51735578-bd1c3f00-20c2-11e9-8907-ec6bac18f3f9.png)

四、错误代码追踪
![image](https://user-images.githubusercontent.com/20454290/51735615-d58c5980-20c2-11e9-9128-3e81511492f5.png)

![image](https://user-images.githubusercontent.com/20454290/51735691-0b314280-20c3-11e9-8a19-5badd6446ad8.png)

**Comment by yuche** [comment]
你现在版本多少

**Comment by 419280377** [comment]
"@tarojs/taro": "^1.2.0-beta.6","@tarojs/taro-weapp": "^1.2.0-beta.6",

> 你现在版本多少

"@tarojs/taro": "^1.2.0-beta.6","@tarojs/taro-weapp": "^1.2.0-beta.6",

**Comment by 419280377** [comment]
> 你现在版本多少

版本太低造成的？

**Comment by 419280377** [comment]
> 你现在版本多少，确定了版本是新的之后，然后贴你 render 函数文字版本

好的

**Comment by yuche** [comment]
升级一下你的 taro，包括cli 和项目依赖，如果还有问题就贴的文字代码

**Comment by luckyadam** [comment]
保持 cli 和项目依赖版本一致
