### ISSUE TITLE
是否支持we-cropper使用和小程序混写的方式引用

### ISSUE THREAD

**Issue by sherryxiao1988** [NervJS/taro#2059]
您好，
我需要实现图片的裁剪功能，找到了这个开源工具：
https://github.com/we-plugin/we-cropper

不知道在文档里面提到的对和小程序混写的支持是否也支持下载we-cropper到src后再混写？
这里是他们的文档：
https://we-plugin.github.io/we-cropper/#/?id=%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

谢谢

**Comment by nyrf** [comment]
可以混写，我用过

**Comment by sherryxiao1988** [comment]
> 可以混写，我用过

@nyrf 是直接把github repo下载到src下面然后混写吗？
谢谢啦！

**Comment by nyrf** [comment]
我最后没用这个，太卡，我后来用的https://github.com/IFmiss/wx-cropper，直接把wx-cropper的src下的代码放在`components/wx-cropper`目录下，然后使用

```
  config = {
    usingComponents: {
      wxcropper: '../../components/wx-cropper/wx-cropper'
    }
  }
```
，注意canvas 中的`this`指向就好

**Comment by sherryxiao1988** [comment]
@nyrf 太感谢了！我去试试

**Comment by wuweijian1997** [comment]
您好，请问你这个问题解决了吗？能发我个demo参考一下吗？自己搞了好久还是Not Found Component

**Comment by luckyadam** [comment]
> 您好，请问你这个问题解决了吗？能发我个demo参考一下吗？自己搞了好久还是Not Found Component

![image](https://user-images.githubusercontent.com/1782542/60072342-bf58f700-974f-11e9-9174-cd453a73d17d.png)

**Comment by febobo** [comment]
> > 您好，请问你这个问题解决了吗？能发我个demo参考一下吗？自己搞了好久还是Not Found Component
> 
> ![image](https://user-images.githubusercontent.com/1782542/60072342-bf58f700-974f-11e9-9174-cd453a73d17d.png)

一样的， V1.2.26

**Comment by shenghanqin** [comment]
请按照要求再提供一下细致的Demo？
