### ISSUE TITLE
能否支持一下mobx ？不要只支持redux

### ISSUE THREAD

**Issue by qinyang1980** [NervJS/taro#206]
很感谢你们设计和开发出了Taro框架。非常6。

提个小问题：状态管理能否支持一下mobx ？

不要只是支持redux，毕竟在社区，这两个都比较火。

多谢 ：）

**Comment by zacksleo** [comment]
see https://github.com/NervJS/taro/pull/140

**Comment by qinyang1980** [comment]
thanks.

**Comment by yuche** [comment]
Duplicate of #13
