### ISSUE TITLE
Mobx的另一种写法observable对象无法自动刷新

### ISSUE THREAD

**Issue by giscafer** [NervJS/taro#2061]
**问题描述**
Mobx的另一种写法observable对象无法自动刷新

**复现步骤**

写了个demo: https://github.com/giscafer/taro-mobx-forceupdate-demo

页面组件里边这样引入store，运行源码见上边demo链接。

```js
import { Text, View } from '@tarojs/components';
import { inject, observer } from '@tarojs/mobx';
import Taro, { Component } from '@tarojs/taro';
import { toJS } from 'mobx';
import './index.scss';


@inject(stores => ({
  data: stores.productStore.data,
  loadData: stores.productStore.loadData,
}))
@observer
class Index extends Component {

  config = {
    navigationBarTitleText: 'mobx issue reproduce',
  }

  constructor(props) {
    super(props);
    this.state = {
    }
  }

  componentWillMount() {
  }


  componentDidMount() {
    this.query();

  }

  componentWillUnmount() { }

  componentDidShow() { }

  query() {
    const { loadData } = this.props;
    loadData().then((res) => {
      if (res) {
        console.log('这里如果不强制刷新一下this.forceUpdate()，mobx观察的对象data不会自动刷新');
        // this.forceUpdate();
        return;
      }
    });
  }

  render() {
    const { data } = this.props;
    const productList = toJS(data) || [];
    return (
      <View className='index'>
        <Text>共{productList.length}条记录</Text>
        {
          productList.length && productList.map((pd, index) => {
            return <View key={pd._id} className='list'>
              <Text>{pd.title}</Text>
            </View>
          })
        }

      </View>
    )
  }

}

export default Index

```

**期望行为**
无需forceUpdate，自动刷新绑定值。期望Taro + Mobx支持这样的写法，React + Mobx开发就支持这种写法。[nanjingboy/taro-mobx-sample](https://github.com/nanjingboy/taro-mobx-sample) 给出的demo相比上边的写法有些繁琐。

**报错信息**
![tim 20190128141403](https://user-images.githubusercontent.com/8676711/51817972-0c9f7c80-2308-11e9-890a-2a54ed185b71.png)
![tim 20190128141426](https://user-images.githubusercontent.com/8676711/51817973-0c9f7c80-2308-11e9-9e83-8853465e0359.png)

**系统信息**
从1.0到目前最新版本一直存在的问题。

**Comment by giscafer** [comment]
有计划排查和修复该问题吗？

**Comment by nanjingboy** [comment]
@giscafer 将 `src/store/project.js` 中 `loadData` 中更改 `data` 值的语句从：

```js
this.data = result.data;
```

修改为：

```js
this.data.replace(result.data);
```

具体原因参见：https://stackoverflow.com/questions/44986339/mobx-observable-array-not-updated

**Comment by giscafer** [comment]
@nanjingboy 真的可以，因为之前开发RN用Mobx也是这么写，没有遇到这个问题。所以没怀疑到这里，感谢。

**Comment by weixiaoyi** [comment]
mobx数组不更新的问题，最好的解决方法是升级到5以上，taro自带的mobx版本太低，太坑

**Comment by nanjingboy** [comment]
@weixiaoyi 如果你不需要适配低端机，你完全可以根据你的需求使用最新的 mobx，这里只是给你提供一个默认的选项。

**Comment by hnsylitao** [comment]
``` js
@inject(stores => ({
  data: stores.productStore.data,
  loadData: stores.productStore.loadData,
}))
```
请问你这里 data 值能够被 observable 观察到改变么，按照taro mobx 注意项提到是观察不到的
https://github.com/NervJS/taro/issues/2446
https://github.com/NervJS/taro/blob/master/docs/mobx.md

**Comment by nanjingboy** [comment]
@hnsylitao 看一下你是不是也犯了这样的错误：https://github.com/NervJS/taro/issues/3443

**Comment by hnsylitao** [comment]
@nanjingboy 感谢回复，我的确碰到了这个问题，但是我在这个issues 里面奇怪的是为什么array 只要用replace 就可以被观察到update
