### ISSUE TITLE
taro 1.2.10

### ISSUE THREAD

**Issue by Pecking** [NervJS/taro#2069]
麻烦告知一下版本1.2.10对应得node 版本告知一下?升级之后启动h5程序会失败

**Comment by luckyadam** [comment]
windows 的话 在 `h5.esnextModules` 配置里加上一个 `@tarojs_components`
windows 上包安装后 / 被换成了 _
下个版本可以不用加 a4eff93

**Comment by luckyadam** [comment]
可以升级到 1.2.11 了

**Comment by Pecking** [comment]
@luckyadam 当我升级之后,执行H5得时候会安装@tarojs/webpack-runner,但是这个包是永远都安装不上得 ,只有用脚手架1.2.4 初始化得项目才可以正常安装和启动
