### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime 

### ISSUE THREAD

**Issue by xian107** [NervJS/taro#2070]
npm run dev:h5会报以下错误，
`./.temp/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit w
ith Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3`
![image](https://user-images.githubusercontent.com/13252682/51896360-3da2ae80-23e7-11e9-9c73-46add0b0d0fa.png)
然后页面显示
![image](https://user-images.githubusercontent.com/13252682/51896483-89555800-23e7-11e9-81cb-43b7b856d85d.png)

**taro info :**
` Taro v1.2.10

 Taro CLI 1.2.10 environment info:
   System:
     OS: Windows 7
   Binaries:
     Node: 10.14.1 - C:\dev\nodejs\node.EXE
     Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
     npm: 6.4.1 - C:\dev\nodejs\npm.CMD`

**Comment by Git-leaner** [comment]
我的这个问题cnpm install node-sass可以解决

**Comment by luckyadam** [comment]
node-sass 没有装好，建议用国内源安装

**Comment by xian107** [comment]
@luckyadam @Git-leaner 关键是我重装了node-sass之后，会报另一个错
![image](https://user-images.githubusercontent.com/13252682/51951337-3626e800-246f-11e9-91dd-556c36284465.png)

**Comment by luckyadam** [comment]
升级到最新版本~

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/0a2f8d830f25357f4ebcda0ec001192dbb8a9a4d

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/0a2f8d830f25357f4ebcda0ec001192dbb8a9a4d
