### ISSUE TITLE
Taro1.2.10编译小程序报错

### ISSUE THREAD

**Issue by zzlit** [NervJS/taro#2072]
**问题描述**
更新1.2.10后编译小程序报错

**报错信息**

![image](https://user-images.githubusercontent.com/28583195/51898117-2c5ba100-23eb-11e9-97a5-def3338cc6a3.png)

**系统信息**
![image](https://user-images.githubusercontent.com/28583195/51898168-501ee700-23eb-11e9-9932-4bcd2cd85983.png)

**Comment by luckyadam** [comment]
node-sass 没有装好，建议用国内源，然后 1.2.10 编译 H5 存在一些问题，用 1.2.11 试试
