### ISSUE TITLE
小于号显示问题

### ISSUE THREAD

**Issue by xuxiaoxiao312** [NervJS/taro#2073]
**问题描述**
无法显示小于号
**复现步骤**
尝试了多种方式都不可以

```js
<Text>{'<'}</Text>
<Text>{'&lt;'}</Text>
<Text>&lt;</Text>
```

**期望行为**
如何正确输出小于号？
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
👽 Taro v1.2.10

  Taro CLI 1.2.10 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/cdf3cbdeee418b1afbd9421c40a482e8ba854d66

**Comment by zlh** [comment]
在最新的版本@1.2.22中，还是出现该问题，无法直接插入符号，需要用变量定义后引入

**Comment by yuche** [comment]
> 在最新的版本@1.2.22中，还是出现该问题，无法直接插入符号，需要用变量定义后引入

贴一个复现的代码
