### ISSUE TITLE
更新1.2.10版本后使用Swiper组件报错TypeError: Swipers is not a constructor

### ISSUE THREAD

**Issue by Git-leaner** [NervJS/taro#2075]
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
JSX中使用使用swiper组件报错
`Uncaught (in promise) TypeError: Swipers is not a constructor
    at Swiper.componentDidMount (index.js?a9b7:87)
    at eval (index.js?1e21:1584)
    at errorCatcher (index.js?1e21:1482)
    at eval (index.js?1e21:1583)
    at Array.forEach (<anonymous>)
    at flushMount (index.js?1e21:1579)
    at updateComponent (index.js?1e21:1666)
    at Route.forceUpdate (index.js?1e21:1762)
    at eval (index.js?e6ae:2515)`
**复现步骤**
 this.mySwiper = new Swipers(this.$el, opt)

[或者可以直接贴源代码，能贴文字就不要截图]

``<Swiper
          className='swplist'
          indicatorActiveColor='#333'
          vertical={false}
          circular={false}
          onChange={this['swiptype']}
          current={mediasel}
          indicatorDots={false}
          autoplay={false}>
           {
             mediatps.map((tp,idx)=>{
              return (<SwiperItem className={'swipitem'}>
              <View className={'booklist'}>
                {list(idx)}
              </View>
                {pagectrl(idx)}
            </SwiperItem>)
            })}
           }
        </Swiper>`js
// 这里可以贴代码

```

**期望行为**
怎么解决？好几个页面都有用到swiper

**报错信息**



**系统信息**
$ taro info
👽 Taro v1.2.10

  Taro CLI 1.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.5.0 - D:\nodejs\node.EXE
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - D:\nodejs\npm.CMD

**补充信息**

**Comment by tourze** [comment]
坐等官方发新版本修复这个问题

**Comment by luckyadam** [comment]
升级到 1.2.11 试试

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/eeae33f
