### ISSUE TITLE
H5端首次加载没问题，点击进入详情页，底部不会隐藏

### ISSUE THREAD

**Issue by liuyingmei123** [NervJS/taro#2079]
**问题描述**
H5端首次加载没问题，点击进入详情页，底部不会隐藏

**复现步骤**
启动项目，在有底部的页面跳转到没有底部的页面，底部依然存在

**期望行为**
正常隐藏底部

**报错信息**
没有

**系统信息**
👽 Taro v1.2.11

  Taro CLI 1.2.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.3 - E:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - E:\Program Files\nodejs\npm.CMD

**Comment by Littly** [comment]
本地没有看到问题 有没有可以复现问题的代码仓库？
