### ISSUE TITLE
如何在现有安卓，ios项目使用taro

### ISSUE THREAD

**Issue by jp1017** [NervJS/taro#2080]
请问，如何操作

**Comment by luckyadam** [comment]
请具体描述一下你的需求

**Comment by jp1017** [comment]
> 请具体描述一下你的需求

我们现在有个APP，包含安卓，IOS端， 后续开发想使用 `taro`，请问该如何集成 @luckyadam

**Comment by Pines-Cheng** [comment]
预计本周合并 京东 jdreact 分支到 master，这样就可以按照原生 React Native 的方式集成了。
