### ISSUE TITLE
taro开发vscode插件

### ISSUE THREAD

**Issue by lvxiaoweiCHN** [NervJS/taro#2081]
taro开发有没有vscode插件？

**Comment by luckyadam** [comment]
要什么插件

**Comment by coppyC** [comment]
不用什么插件，taro的 types 文件很全，提示很好，vscode 自带jsx 提示，不知道你缺少什么功能

**Comment by cardsix** [comment]
比如输入标签时自动补全？每次都按<好麻烦

**Comment by yuche** [comment]
vscode 默认对 JSX 已经内置了自动补全等功能，如果你没有开启可以参考：
https://code.visualstudio.com/docs/nodejs/reactjs-tutorial
设置一下。

**Comment by davidlin88** [comment]
建了个ts模板的taro项目，类似`*.wxapp.tsx`的文件vscode会报找不到模块，应该是无法自动识别`.wxapp`吧，不知各位有没有解决方法

**Comment by coppyC** [comment]
@davidlin88 是import 时候报错的吗？有截图么，我也是用 ts，并不会

**Comment by davidlin88** [comment]
> @davidlin88 是import 时候报错的吗？有截图么，我也是用 ts，并不会

![image](https://user-images.githubusercontent.com/30857148/57578093-ae626800-74b8-11e9-8873-3c16d575184c.png)
就是这样，跟ts没关系，是taro云开发模板的命名和引入方式，vscode的lint工具检查不兼容吧，不知道怎么配置，但把组件名由`index.wxapp.tsx`改为`index.tsx`就可以了

**Comment by coppyC** [comment]
是这样的，你要import index.wxapp
这样写
.wxapp.tsx的后缀是tsx，省略后缀只能省略tsx
不是taro的问题，ts，js都是这样

**Comment by davidlin88** [comment]
> @davidlin88
> 是这样的，你要import index.wxapp 这样写
> .wxapp.tsx的后缀是tsx，省略后缀只能省略tsx
> 不是taro的问题，ts，js都是这样

嗯嗯 感觉还是把名字改成index.tsx方便些，不知道`*.wxapp.tsx`这样的命名风格是对多端有不同代码吗还是怎样，如果没有的话不知道还有何含义

**Comment by Chen-jj** [comment]
已有 vscode 插件：taro-helper

**Comment by lakeoves** [comment]
fbdffbdbfd
