### ISSUE TITLE
require本地代码和包代码表现不一致

### ISSUE THREAD

**Issue by monyee** [NervJS/taro#2084]
**问题描述**
页面引用了本地的lib目录下的passport.js（里面有await promise相关的应用）
后来我把passport单独发布了npm(经过了babel转es5)两份代码一致

![image](https://user-images.githubusercontent.com/8890905/51955328-7772c400-247e-11e9-9a16-5725de4e5a84.png)

通过npm引入的promise方法一直不返回，本地lib/passport可以
就算把dist下lib/passport 直接复制到npm/xx/passport里也不行

**期望行为**
本地代码和通过npm包引入的行为一致

**系统信息**
> Taro v1.2 8

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v1.2 8]
 - Node.js 版本 [e.g. v10.15.0]
 - 报错平台 [ weapp]

**Comment by luckyadam** [comment]
有什么报错

**Comment by monyee** [comment]
没有报错 只是await的方法不返回了 卡住

**Comment by luckyadam** [comment]
能否给一个可以复现的 demo，以排查问题

**Comment by monyee** [comment]
已发现是自己这边问题，感谢@luckyadam 请删了此issue
