### ISSUE TITLE
npm run dev:weapp后微信小程序中的静态资源图片出现404

### ISSUE THREAD

**Issue by hengxuZ** [NervJS/taro#2086]
![image](https://user-images.githubusercontent.com/32482154/51960589-9a0fd780-2494-11e9-8bf3-ee683823caf4.png)

小程序开发工具打开后 当前的页面中的图片都出现了404错误

**Comment by hengxuZ** [comment]
@luckyadam ,大哥你好
      taro直接不识别我的images文件夹所以导致的 图片找不到

通过修改图片的分辨率,能够实现图片请求的到

但是关闭了微信小程序开发工具,重新打开后,再一次不能识别图片文件

谢谢你的帮助十分感激！
不知道到底是我个人原因所致还是？

我想请问 关于分辨率低于64 本地的图片
应该如何引用才能够确保不出现 请求不到的问题

**Comment by luckyadam** [comment]
请看一下我发的文档

**Comment by hengxuZ** [comment]
@luckyadam 已经解决我的问题。
没有仔细翻阅文档,导致的错误
十分感谢你的帮助,提前预祝您新年快乐
也祝愿taro越来越强大👍
