### ISSUE TITLE
服务器运行报错

### ISSUE THREAD

**Issue by z704600202qj** [NervJS/taro#2091]
![image](https://user-images.githubusercontent.com/23369361/51975637-b70cd080-24bd-11e9-844d-cdacac459802.png)

**Comment by luckyadam** [comment]
用 npm 或者 cnpm 重新安装下依赖吧

**Comment by z704600202qj** [comment]
> 用 npm 或者 cnpm 重新安装下依赖吧

重新装过好多次，都是这个问题
