### ISSUE TITLE
支付宝小程序引入dva后上传遇到问题

### ISSUE THREAD

**Issue by linrf** [NervJS/taro#2092]
**问题描述**
在项目中引入dva，正常开发没有问题，编译到支付宝小程序后，有一个这样的文件，npm/dva-core/npm/_babel/runtime/npm/core-js/library/modules/es6.object.get-own-property-descriptor.js，
支付宝小程序ide报路径名称太长
如图
![image](https://user-images.githubusercontent.com/8201516/51983932-fabf0480-24d4-11e9-9a7e-6bb76582ec9b.png)

**复现步骤**

**期望行为**
有没有办法缩短生成出来的目录路径？

**报错信息**

![image](https://user-images.githubusercontent.com/8201516/51983932-fabf0480-24d4-11e9-9a7e-6bb76582ec9b.png)

**系统信息**

 - 操作系统: [Mac]
 - Taro 版本 [👽 Taro v1.2.0-beta.11]
 - Node.js 版本 [v10.10.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
我看看开发工具能不能调整一下，暂时只能靠手动修改文件名咯

**Comment by shufangjian** [comment]
除了手工改，有无其他方法 @luckyadam
