### ISSUE TITLE
[Feature request]能否简单支持一下 在js 里面写css

### ISSUE THREAD

**Issue by coppyC** [NervJS/taro#2094]
首先要感谢Taro 团队，用过其它小程序框架，这几天用了Taro，对比下，真心觉得Taro对小程序支持很友好 ，维护也很积极，而且还提供解决方案。不知道这个框架是什么时候开源的，好像也不是很久，star就已经这么多了，如果不是国内使用react的人少，可能会更多star。
好，开始切入正题
#118 已经存在很久了，官方说有计划支持，也不知道什么时候能支持
现在有个需要，不需要styled-component这样强大的功能，只需要把css的样式文件搬到js写
因为很多组件其实只是需要几行css样式而已，但却不得不再开一个文件写css，这样会让目录变得臃肿，代码难以维护。
希望实现后代码写法类似如下

![image](https://user-images.githubusercontent.com/25004510/52026511-1234d680-2543-11e9-85ca-68a4041cd87c.png)

至于高亮与css的提示，在vscode下可以用vscode-styled-components
目前在不支持这种写法的情况下，我可以把css写在style 中，但是有个问题，在style中的代码不会经过处理，像px的转换，-webkit-前缀的补充都不会得到支持，还有就是小程序中style对象需要解析，性能没有css文件的好。
希望官方能给一个解决方案，一个组件一个文件，在组件迁移的时候也会很舒服。

**Comment by athrunsun** [comment]
强烈支持！css-in-js可以非常方便地实现动态style，希望能在不久的将来得到支持。

BTW, 国内使用react的人肯定不少。vue很火，但是从taro, mpvue这些project的star数可以一定程度反映出react的使用者跟vue不相上下。

**Comment by Lionad-Morotar** [comment]
这应该只能算作功能分支吧, 按普通方式写CSS并没有觉得遇到了什么瓶颈, 毕竟编译为小程序后, CSS文件终究还是存在的

**Comment by tourze** [comment]
关注这个feature

**Comment by eugle** [comment]
+1

**Comment by DonaldDai** [comment]
css-in-js 可以方便开发人员批量生成有规律的css
