### ISSUE TITLE
微信小程序父组件向子组件传递函数，执行了但是还是报错（h5可以运行）

### ISSUE THREAD

**Issue by JokerLoLgrey** [NervJS/taro#2096]
**问题描述**
微信小程序父组件向子组件传递函数，执行了但是还是报错

**复现步骤**
1.首先我先封装了一些tabBar组件，代码如下
```js
import Taro from '@tarojs/taro-h5';
import { AtTabBar } from 'taro-ui';
export default class Index extends Taro.Component {
  constructor() {
    super(...arguments);
    this.state = {
      current: 0
    };
  }
  handleClick(value) {
    this.setState({
      current: value
    });
    console.log(this.props);
    this.props.onCurrentPage(value);
  }
  render() {
    return <AtTabBar
      selectedColor="#212121"
      color="#BDBDBD"
      fixed={this.props.fixed}
      tabList={this.props.tabList}
      onClick={this.handleClick.bind(this)}
      current={this.state.current} />;
  }
}
```

2.然后我在某个页面使用了这个组件

```js
// 这是父组件的函数
currentPage(value) {
    this.setState({
      currentPageShow: value
    });
  }
// 这个是调用这个组件
<TabBar tabList={tabList} fixed={fixed} onCurrentPage={this.currentPage.bind(this)} />
```

**期望行为**
微信小程序和h5一样能够完美运行

**报错信息**
这是报错信息
![image](https://user-images.githubusercontent.com/33446705/52031558-14edf680-2558-11e9-8179-8c18d75abb42.png)
只执行了部分代码（页面没有切换）
![image](https://user-images.githubusercontent.com/33446705/52031579-2e8f3e00-2558-11e9-9106-684ea59a31e2.png)
![image](https://user-images.githubusercontent.com/33446705/52031585-36e77900-2558-11e9-91cf-945596fce0ed.png)
![image](https://user-images.githubusercontent.com/33446705/52031589-3d75f080-2558-11e9-80e4-2229423a700e.png)

**系统信息**
![image](https://user-images.githubusercontent.com/33446705/52031356-04894c00-2557-11e9-9097-0ed14ea4a558.png)

 - 报错平台 [weapp]

**补充信息**

**Comment by JokerLoLgrey** [comment]
已解决，但是出现新的问题
```
export default class Index extends Component {
  render () {
    const tabData = [{ title: '推荐',content: <TabA /> }, { title: '关注', content: <TabB /> }]
    return (
      <View className='home'>
        <Search />
        <Tabs tabList={tabData} />
      </View>
    )
  }
}

```
上面这段代码微信小程序报如下错误
![image](https://user-images.githubusercontent.com/33446705/52032566-71ebab80-255c-11e9-92cc-ce4f7c453137.png)

**Comment by JokerLoLgrey** [comment]
> 已解决，但是出现新的问题
> 
> ```
> export default class Index extends Component {
>   render () {
>     const tabData = [{ title: '推荐',content: <TabA /> }, { title: '关注', content: <TabB /> }]
>     return (
>       <View className='home'>
>         <Search />
>         <Tabs tabList={tabData} />
>       </View>
>     )
>   }
> }
> ```
> 上面这段代码微信小程序报如下错误
> ![image](https://user-images.githubusercontent.com/33446705/52032566-71ebab80-255c-11e9-92cc-ce4f7c453137.png)

这个问题绕了一下解决了,用了如下方法
```
const tabList = [
      {
        title: '推荐'
      },
      {
        title: '关注'
      }
    ]
    return (
      <View className='home'>
        <Search />
        <Tabs tabList={tabList}>
          <AtTabsPane current={0}>
            <TabA />
          </AtTabsPane>
          <AtTabsPane current={1}>
            <TabB />
          </AtTabsPane>
        </Tabs>
      </View>
    )
```

**Comment by Chen-jj** [comment]
@JokerLoLgrey props 传 JSX 要遵循以下写法 https://nervjs.github.io/taro/docs/children.html#%E7%BB%84%E5%90%88

**Comment by JokerLoLgrey** [comment]
> @JokerLoLgrey props 传 JSX 要遵循以下写法 https://nervjs.github.io/taro/docs/children.html#%E7%BB%84%E5%90%88

已经解决了，就是感觉不能封装在内部不是很完美

**Comment by TiamoJrZhang** [comment]
@JokerLoLgrey hello，请问一下你一开始的传递函数报错是咋解决的
