### ISSUE TITLE
引入taro-ui出错

### ISSUE THREAD

**Issue by penxu** [NervJS/taro#2100]
**问题描述**
按照taro-UI步骤引入报以下错：
" '@tarojs/components' does not contain an export named 'OpenData'.

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtNoticebar } from 'taro-ui'
import './index.scss'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <AtNoticebar>Hello world!</AtNoticebar>
      </View>
    )
  }
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by JokerLoLgrey** [comment]
> ontain an export named 'OpenData'.

这种你最好贴一下你的package.json

**Comment by ljmkimqx** [comment]
+1

**Comment by ljmkimqx** [comment]
我也是同样的问题, 编译的是h5
taro 1.2.12 、npm 5.6.0 、node 9.10.0、taro-ui 2.0.0
我的package.json文件如下
`
{
  "name": "H5Develop",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "1.2.12",
    "@tarojs/router": "1.2.12",
    "@tarojs/taro": "1.2.12",
    "@tarojs/taro-alipay": "1.2.12",
    "@tarojs/taro-h5": "1.2.12",
    "@tarojs/taro-swan": "1.2.12",
    "@tarojs/taro-tt": "1.2.12",
    "@tarojs/taro-weapp": "1.2.12",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.0.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/plugin-babel": "1.2.12",
    "@tarojs/plugin-csso": "1.2.12",
    "@tarojs/plugin-sass": "1.2.12",
    "@tarojs/plugin-uglifyjs": "1.2.12",
    "@tarojs/webpack-runner": "1.2.12",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "1.2.12",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "1.2.12"
  }
}
`

**Comment by ljmkimqx** [comment]
我也是同样的问题, 编译的是h5
taro 1.2.12 、npm 5.6.0 、node 9.10.0、taro-ui 2.0.0
我的package.json文件如下
`{
  "name": "H5Develop",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "1.2.12",
    "@tarojs/router": "1.2.12",
    "@tarojs/taro": "1.2.12",
    "@tarojs/taro-alipay": "1.2.12",
    "@tarojs/taro-h5": "1.2.12",
    "@tarojs/taro-swan": "1.2.12",
    "@tarojs/taro-tt": "1.2.12",
    "@tarojs/taro-weapp": "1.2.12",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.0.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/plugin-babel": "1.2.12",
    "@tarojs/plugin-csso": "1.2.12",
    "@tarojs/plugin-sass": "1.2.12",
    "@tarojs/plugin-uglifyjs": "1.2.12",
    "@tarojs/webpack-runner": "1.2.12",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "1.2.12",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "1.2.12"
  }
}`

**Comment by ljmkimqx** [comment]
我也是同样的问题, 编译的是h5
taro 1.2.12 、npm 5.6.0 、node 9.10.0、taro-ui 2.0.0
我的package.json文件如下
<img width="656" alt="2019-02-04 7 47 04" src="https://user-images.githubusercontent.com/30502832/52206605-b0170100-28b5-11e9-9741-c748b87d232f.png">

**Comment by 18978909244** [comment]
同样

**Comment by SlideToUnlock** [comment]
怎么解决的？我也遇到了

**Comment by luckyadam** [comment]
暂时加了一个 OpenData 的空组件  6e6cd8f58aa6d16bb2f31e109e90e1626f8e7fe1

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/6e6cd8f58aa6d16bb2f31e109e90e1626f8e7fe1
