### ISSUE TITLE
升级到v1.2.12后编译的微信小程序无法使用

### ISSUE THREAD

**Issue by 499070844** [NervJS/taro#2104]
**问题描述**
  从1.2.7升级到v1.2.12后编译的小程序无法使用.
  编译时没有报错,但是编译后的小程序无法正常运行.
  旧页面(1.2.7时编译过的页面)无法正常运行.
  新创建的页面编译完后是空白.
**复现步骤**
  从1.2.7升级到1.2.12

**期望行为**
 成功编译
**报错信息**
 微信小程序给出的报错信息为
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'defaultProps' of null 
 TypeError: Cannot read property 'defaultProps' of null
    at Object.createComponent (http://127.0.0.1:53285/appservice/npm/@tarojs/taro-weapp/dist/index.js:3457:54)
    at http://127.0.0.1:53285/appservice/pages/checkout/checkout.js:85:68
    at require (http://127.0.0.1:53285/appservice/__dev__/WAService.js:23:15279)
    at <anonymous>:38:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:53285/appservice/appservice?t=1549005094755:1512:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:53285/appservice/appservice?t=1549005094755:1524:20)
console.error @ VM400:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1549005094755:1399
window.onerror @ VM400:1
scriptLoaded @ appservice?t=1549005094755:1512
script.onload @ appservice?t=1549005094755:1524
WAService.js:19 Fri Feb 01 2019 15:11:37 GMT+0800 (中国标准时间) Page route 错误
VM400:1 Page[pages/index/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.
console.warn @ VM400:1
A @ WAService.js:19
Xt @ WAService.js:20
sn @ WAService.js:20
un @ WAService.js:20
(anonymous) @ WAService.js:20
(anonymous) @ WAService.js:19
L.emit @ WAService.js:8
emit @ WAService.js:6
(anonymous) @ WAService.js:9
(anonymous) @ WAService.js:6
e @ appservice?t=1549005094755:1399
n.registerCallback.t @ appservice?t=1549005094755:1399
l.forEach.t @ appservice?t=1549005094755:1399
(anonymous) @ appservice?t=1549005094755:1399
s.onmessage @ appservice?t=1549005094755:1399
WAService.js:19 Fri Feb 01 2019 15:11:37 GMT+0800 (中国标准时间) Page route 错误
VM400:1 Page is not constructed because it is not found.

------

taro编译时无报错, tsx没有报语法错误

**系统信息**
Taro CLI 1.2.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.5.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

**Comment by Lionad-Morotar** [comment]
问一下 楼主是降级解决么?

**Comment by Lionad-Morotar** [comment]
> 问一下 楼主是降级解决么?

当时升级到v1.2.13解决的
