### ISSUE TITLE
自定义Tabbar通过props传参，真机调试触发两次render()，最后渲染结果为props=null的渲染结果

### ISSUE THREAD

**Issue by wugy0103** [NervJS/taro#2108]
**问题描述**
自定义Tabbar通过props传参来获取那个item为当前选中项，从而设置active样式，开发者工具调试没有问题，使用真机调试会触发两次render()，第一次props的值为null,第二次为正确的值，最后渲染结果为props=null的渲染结果

**复现步骤**
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// app.js配置
tabBar: {
      custom: true,
      color: "#2B349A",
      selectedColor: "#2B349A",
      backgroundColor: "#fff",
      list: [
        {
          pagePath: 'pages/index/index',
          text: '首页',
        },
        {
          pagePath: 'pages/user/index',
          text: '我的',
        }
      ]
    },

// index页引用
<CustomTabBar active="index" />

// user页引用
<CustomTabBar active="user" />

// 自定义Tabbar custom-tab-bar 源码
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './index.scss'
const app = Taro.getApp();
export default class CustomTabBar extends Component {
  render() {
    let {
      active
    } = this.props;
    debugger;
    return <View className={app.globalData.isIPX ? 'custom-tab-bar ipx' : 'custom-tab-bar'}>
          <View className={active !== 'user' ? 'tab-bar-btn active' : 'tab-bar-btn'} onClick={this.switchTab.bind(this, 'index')}>首页</View>
          <View className={active === 'user' ? 'tab-bar-btn user-btn active' : 'tab-bar-btn user-btn'} onClick={this.switchTab.bind(this, 'user')}>我的</View>
        </View>
  }

  /**
   * 切换路由
   */
  switchTab(flag) {
    Taro.switchTab({
      url: `/pages/${flag}/index`
    })
  }

}


```

**期望行为**
期望能正确渲染出我想要的样式，比如上述代码的，在user页中，active样式应该渲染在[我的tab],现在依然渲染的【首页tab】

**报错信息**

![image](https://user-images.githubusercontent.com/20140264/52161579-13603200-2702-11e9-999d-d0c424e6fbdd.png)

**系统信息**
👽 Taro v1.2.12

  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    npmPackages:
      @tarojs/components: 1.2.12 => 1.2.12
      @tarojs/plugin-babel: 1.2.12 => 1.2.12
      @tarojs/plugin-csso: 1.2.12 => 1.2.12
      @tarojs/plugin-sass: 1.2.12 => 1.2.12
      @tarojs/plugin-uglifyjs: 1.2.12 => 1.2.12
      @tarojs/router: 1.2.12 => 1.2.12
      @tarojs/taro: 1.2.12 => 1.2.12
      @tarojs/taro-alipay: 1.2.12 => 1.2.12
      @tarojs/taro-h5: 1.2.12 => 1.2.12
      @tarojs/taro-swan: 1.2.12 => 1.2.12
      @tarojs/taro-tt: 1.2.12 => 1.2.12
      @tarojs/taro-weapp: 1.2.12 => 1.2.12
      @tarojs/webpack-runner: 1.2.12 => 1.2.12
      eslint-config-taro: 1.2.12 => 1.2.12
      eslint-plugin-taro: 1.2.12 => 1.2.12
      nervjs: ^1.3.9 => 1.3.12

 - 报错平台 [weapp]

**补充信息**
[可选]
是我试过先把props赋值给state，然后再用state绑定渲染，依然没用

**Comment by wugy0103** [comment]
刚刚对active做非空判断可以解决问题了，但是这也是一个不好的体验，建议优化

**Comment by Chen-jj** [comment]
@wugy0103 方便提供下一个可复现 demo ？简单尝试了下自定义 tabbar 组件，不同于被页面引用，其 props 会一直为 null。

**Comment by HuangHongRui** [comment]
我也遇到这个 问题了。。。。。Fuck...
