### ISSUE TITLE
是否支持单页面配置navigationStyle （单页面自定义导航栏）

### ISSUE THREAD

**Issue by sherryxiao1988** [NervJS/taro#2109]
官方貌似已经支持了：
https://developers.weixin.qq.com/community/develop/doc/000408d3d34178b682d7bdee259401

而我在config里面进行配置没有效果：
![image](https://user-images.githubusercontent.com/1202426/52164425-2982e800-272c-11e9-8545-7f6e6eb14fc4.png)

请问taro现在支持吗？

**Comment by JokerLoLgrey** [comment]
老哥，官方支持，这个就支持啊，你只需要配置json就行了啊

**Comment by sherryxiao1988** [comment]
@JokerLoLgrey 啊。。官方的json，不就是对应这个的config吗？

**Comment by luckyadam** [comment]
是小程序还是 H5 ？如果小程序的话，官方支持，Taro 就可以

**Comment by sherryxiao1988** [comment]
> 是小程序还是 H5 ？如果小程序的话，官方支持，Taro 就可以

@luckyadam 是小程序，我试过在config里面改，如上图，但是没有效果

**Comment by JokerLoLgrey** [comment]
> > 是小程序还是 H5 ？如果小程序的话，官方支持，Taro 就可以
> 
> @luckyadam 是小程序，我试过在config里面改，如上图，但是没有效果

那是因为官方要年后才支持啊，工具都没有升级😂😂😂

**Comment by sherryxiao1988** [comment]
测试了，模拟器上不行，但是真机上是可以的
