### ISSUE TITLE
事件绑定问题

### ISSUE THREAD

**Issue by zacksleo** [NervJS/taro#211]
在构造函数中，无法使用bind方法
```
  constructor(props) {
    super(props);
    this.onClick = this.onClick.bind(this);
  }
```
如上，使用这种绑定形式报错

**Comment by zh28** [comment]
![image](https://user-images.githubusercontent.com/31911177/41958628-34483d56-7a1d-11e8-9190-ce0d70037043.png)
在标签里用bind也会报错，编译无法通过
![image](https://user-images.githubusercontent.com/31911177/41958679-5d08c63e-7a1d-11e8-82b6-379e413aa4a6.png)

然后我改成了使用 `data-param=""` 可以了，不知道咋回事
![image](https://user-images.githubusercontent.com/31911177/41959284-16d515b2-7a1f-11e8-9fbf-ed9f9ff14408.png)

**Comment by yuche** [comment]
现在没有办法在构造器里 bind 事件。按文档里说，要么在 JSX 里使用 bind，要么使用 class property + arrow function。

@zh28 bind 传递字面量 number 类型在 https://github.com/NervJS/taro/commit/3b6a7991d51afa243255feab54719b668614477b 支持了，但是还没有发新版本。

你现在可以先把数字设置为一个变量，然后再传递进去。

**Comment by zh28** [comment]
@yuche OK，3Q
