### ISSUE TITLE
npm install -g @tarojs/cli安装taro后使用taro命令报错taro: command not found

### ISSUE THREAD

**Issue by ljmkimqx** [NervJS/taro#2110]
**问题描述**
问题过程：之前装过taro, 版本是1.1.0，然后有新版1.2.12，就用npm install -g @tarojs/cli升级, 发现升级完毕后taro版本仍然是1.1.0(taro update self一样没有效果)。然后用yarn进行升级，yarn global add @tarojs/cli。然后升级成功了，1.2.12。然后用taro init创建项目发现不能创建项目，报下面的错
<img width="498" alt="2019-02-03 5 37 52" src="https://user-images.githubusercontent.com/30502832/52175543-6c9e9300-27e0-11e9-9bfe-fc798d43463d.png">
然后我发现有人也有这样的错，他们给出的建议是用npm重装一次taro,然后我用npm install -g @tarojs/cli重装完毕后发现taro命令不能使用。如图
<img width="569" alt="2019-02-03 6 06 58" src="https://user-images.githubusercontent.com/30502832/52175563-9d7ec800-27e0-11e9-843e-61f9642a1281.png">
很奇怪，不知道为什么。而且装完taro后我也能npm uninstall -g @tarojs/cli。

补充：npm install -g @tarojs/cli安装taro后，使用taro命令是提示no found, 但在node相关目录下却有taro的存在
<img width="1138" alt="2019-02-03 8 18 12" src="https://user-images.githubusercontent.com/30502832/52176690-200f8380-27f1-11e9-8c5f-9bdc8531df61.png">

**复现步骤**
如上所述

**期望行为**
能升级taro到1.2.12，并且能taro init正常创建项目

**系统信息**
mac os系统 10.14、npm环境5.6.0、node环境9.10.0(切换到11.3.0问题依然存在)、

**Comment by ljmkimqx** [comment]
已经解决，重装node和npm就好了
(mac: brew uninstall node, 然后到https://nodejs.org/en/官网下载下来安装，然后重新安装taro。注意不要用brew install node，安装完后会找不到npm的，折腾了一晚上)

**Comment by Garfield550** [comment]
对我来说不论是 brew 还是 scoop 这种包管理软件是刚需，不太会改从其他地方管理 node.js 的更新，所以我的方式是先使用 npx 新建项目，然后进入项目目录执行 `yarn add @tarojs/cli` 曲线解决问题。

**Comment by byk04712** [comment]
刚准备玩玩taro，不管是
`$ npm install -g @tarojs/cli`
还是
`$ yarn global add @tarojs/cli`

运行 `taro` 之后还是 command not found。
才刚开始就这么悲催的么

**Comment by XiYeLv** [comment]
嗯，其实配置一下taro环境就好了。编辑mac的bashfile文件，添加taro的路径进去就好了。就像配置mysql等的环境路径一样

**Comment by konghuawei** [comment]
1. 在终端执行 which taro，找到taro安装位置，如：/Users/abc/.nvm/versions/node/v12.16.3/bin/taro；
2. 编辑.bash_profile文件，加入 export PATH="$PATH:/Users/abc/.nvm/versions/node/v12.16.3/bin/taro"，然后保存文件；
3. 在终端执行 source ~/.bash_profile；
4. ok，问题解决
