### ISSUE TITLE
RN 下 navigationBarTextStyle 无效

### ISSUE THREAD

**Issue by Binaryify** [NervJS/taro#2119]
**问题描述**
app.js 下设置 config

```js
window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: "#d33d38",
      navigationBarTitleText: "首页",
      navigationBarTextStyle:"white"
  },

```

**期望行为**
期望字体颜色为白色

**报错信息**

实际表现仍然为黑色，设置 rgb 或者十六进制颜色仍然不变

**系统信息**

Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.2.2
**补充信息**
RN 下会出现

**Comment by Pines-Cheng** [comment]
无法重现哦，你初始化项目使用的是哪个模版？

**Comment by Binaryify** [comment]
默认模版
![image](https://user-images.githubusercontent.com/12221718/54518913-51f33880-49a0-11e9-81e1-db223c1f3490.png)
![image](https://user-images.githubusercontent.com/12221718/54518918-57508300-49a0-11e9-8cff-25de45374a05.png)
