### ISSUE TITLE
引用自定义组件时，路径错误

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#212]
![image](https://user-images.githubusercontent.com/23295172/41956845-a07c4c20-7a17-11e8-9644-fd66ae2916a2.png)
引用路径应为 ../../../components/ProductBanner/index.wxml
项目为 taro init 生成的 typescript；

弃疗

**Comment by yuche** [comment]
看字体你应该是 windows，taro 用的是 node 的 path 模块来处理路径，所以到对应 windows 平台会编译成反斜杠，这应该没啥问题。

不过坑爹之处在于小程序在 windows 也是 unix 规范，这个我们下个版本改吧。
