### ISSUE TITLE
taro-cli templates代码应该抽象化 而不应该每个创建的模板都拷贝一次 减少模板创建的工作量

### ISSUE THREAD

**Issue by fangkyi03** [NervJS/taro#2120]
taro-cli templates代码应该抽象化 而不应该每个创建的模板都拷贝一次 减少模板创建的工作量
![image](https://user-images.githubusercontent.com/30390014/52524444-016d2900-2cd8-11e9-9ab7-ab6baeb7e7e4.png)
应该将这一部分都抽象一下 而不是每次模板化都需要写一次逻辑规则 这样效率太低

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/ac347f7d27d2f1bc1f18388774dc4614ec8ec924 之后模板是从远程拿取了
