### ISSUE TITLE
getCurrentPages 方法在taro的componentWillMount生命周期中调用，获取到的页面对象中没有options这个属性

### ISSUE THREAD

**Issue by pamler** [NervJS/taro#2122]
**问题描述**
getCurrentPages 方法在taro的componentWillMount生命周期中调用，获取到的页面对象中没有options这个属性（e.g. 存放了上一个页面带过来的参数等），而在taro的componentDidMount中可以拿的到。但是原生的微信小程序里onLoad中调用该方法的确是可以获取到的，理论上taro的componentWillMount等价于微信小程序的onLoad，所以API的返回结果建议尽量保持一致。

**复现步骤**
可以拿官方的taro-redux-demo举例，代码如下：
pages/index/index.js中
```js
  goto = () => {
    Taro.navigateTo({
      url: '/pages/index2/index?sd=1'
    })
  }

```

pages/index2/index.js中

```js
  componentWillMount () {
    console.log("page2 will mount: ")
    console.log(getCurrentPages().pop().options)
  }

  componentDidMount () {
    console.log("page2 did mount: ")
    console.log(getCurrentPages().pop().options)
  }

```

**实际结果**

![image](https://user-images.githubusercontent.com/3872791/52543656-3cf61900-2de6-11e9-97ac-8eae1c3e594e.png)

**系统信息**
Taro v1.2.12

**Comment by Chen-jj** [comment]
@pamler 首先要清楚 Taro 中微信小程序的页面或组件都是由 Component 构造成的。

微信小程序启动的第一个页面，componentWillMount 对应 onLoad 没错。

但之后跳转的页面，componentWillMount 对应 attached。原因是 onLoad 触发时机在最后，不利于初始化页面。而页面的 attached 是最早触发的。

目测 attached 中拿不到页面对象的 options。但其实获取参数有很多方式，这时直接拿 this.$router.params 或者用预加载等方法都是可以拿到跳转参数的。没有必要舍近求远。
