### ISSUE TITLE
taro编译到微信小程序，props属性名称过长报错

### ISSUE THREAD

**Issue by pamler** [NervJS/taro#2124]
**问题描述**
taro编译到微信小程序，props名不能过长，这个应该是微信小程序的限制，简单的测试了一下，限制应该是要小于32个字符。所以在taro中，如果props传值，名称长度<=31；如果props传function，名称长度<=26个字符，因为taro会在前面加上前缀 `__fn_`。建议把这个属性名过长的限制加到文档中的taro规范或者注意事项里，或者eslint里增加警告，提醒大家注意下。

**复现步骤**
以官方的todoMVC的demo举例，在pages/index/index.js中

```js

class Index extends Component {
  config = {
    navigationBarTitleText: 'TODO List'
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  onPrintLog() {
    console.log('test')
  }

  render () {
    return (
      <View className='todaoapp'>
        <Header 
          onTestALongLongLongLongFunctionName={this.onPrintLog} 
          testALongLongLongLongVariableName={1}
        />
        <MainSection />
      </View>
    )
  }
}


```

**报错信息**
![image](https://user-images.githubusercontent.com/3872791/52544300-ef2fdf80-2dea-11e9-9a0c-898331fa062f.png)

**Comment by yuche** [comment]
新的 props 系统已经没有这个限制
