### ISSUE TITLE
Picker, Image等组件的dataset在H5下某些情况下无法取到

### ISSUE THREAD

**Issue by pamler** [NervJS/taro#2128]
**问题描述**
Picker，Image等组件，如果给它们添加属性data-xxx="test"，编译到H5后，onClick等事件函数通过e.target.dataset等方式无法获取该属性值，但微信小程序中是可以的。原因是Picker，Image等组件转为H5时，taro对这些组件进行了一些封装，例如Image，转化后变为
`<div class="taro-img" data-xxx="test"><img /></div>`，data-xxx属性被放到了外层div元素中，如果事件函数的触发是通过delegate等方式（见下面的例子），那么不管是e.target还是e.currentTarget都无法取到dataset。

**复现步骤**
[codesandbox](https://codesandbox.io/s/ov68kj4nq)

**系统信息**
    "@tarojs/components": "1.2.8",
    "@tarojs/taro-h5": "1.2.8",
    "nervjs": "1.3.12"

**Comment by shenghanqin** [comment]
试试看最新版本？
