### ISSUE TITLE
CoverView/CoverImage等微信小程序特有组件，H5中能否支持降级

### ISSUE THREAD

**Issue by pamler** [NervJS/taro#2129]
**问题描述**
CoverView, CoverImage等微信小程序特有组件，编译到H5后，H5中貌似是不提供这两种组件的，能否提供降级，降级到普通的div，或者 img等。否则，在开发的时候，还要专门进行判断，如果是微信小程序用CoverView，H5中用View

**Comment by JaxXu** [comment]
刚遇到这个问题想来问问就查到这来了

**Comment by JaxXu** [comment]
@luckyadam 不知道是否有这方面的计划支持降级显示

**Comment by jinjinjin0731** [comment]
已经加上降级处理
