### ISSUE TITLE
创建模板项目报错

### ISSUE THREAD

**Issue by yachao** [NervJS/taro#213]
![2018-06-27_145235](https://user-images.githubusercontent.com/650608/41957504-c0e09ef6-7a19-11e8-85bc-2cb9845ab8fb.png)
windows10下创建模板时报图上的错误

**Comment by luckyadam** [comment]
你看下这个文件存在么
![image](https://user-images.githubusercontent.com/1782542/41961333-c5c5c30a-7a24-11e8-9936-31c355dec1a1.png)

**Comment by yachao** [comment]
@luckyadam 存在的

**Comment by yachao** [comment]
@luckyadam 我把nodist卸了重新装了node，就好了
