### ISSUE TITLE
编译后出现文字下坠

### ISSUE THREAD

**Issue by dabennn** [NervJS/taro#2133]
**问题描述**

嵌套的Text组件中的文字在编译后出现了不该出现的换行，导致文字下坠。

**复现步骤**

```js
<View>
  {
    !isSuccess
      ? <Text className="desc">还差<Text className="orange">{detail.assistTotalCount - detail.assistCount}</Text>次助力即可砍价成功</Text>
      : <Text className="desc">砍价成功</Text>
  }
</View>

```
上述代码在编译后出现换行

![](https://i.loli.net/2019/02/11/5c6144eadec88.png)

**期望行为**

文字不换行，如下方式正常显示
![](https://i.loli.net/2019/02/11/5c6144eadec18.png)

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.2.4
 - Node.js 版本 v8.12.0
 - 报错平台 weapp

**补充信息**

查看编译后的wxml模板文件，发现编译生成了如下代码
```xml
<block>
    <block wx:if="{{!isSuccess}}">
        <text class="desc">还差
            <text class="orange">{{detail.assistTotalCount - detail.assistCount}}</text>次助力即可砍价成功</text>
    </block>
    <block wx:else>
        <text class="desc">砍价成功</text>
    </block>
</block>
```
在还差二字后产生了一个不必要的换行，所以导致了文字的下坠。

**Comment by luckyadam** [comment]
升级到最新版本可以解决

**Comment by dabennn** [comment]
已解决 多谢
