### ISSUE TITLE
小程序转taro 出现 app.json 读取失败，请检查   taro v1.2.12

### ISSUE THREAD

**Issue by zhangfan6644777** [NervJS/taro#2134]
小程序转taro 出现 app.json 读取失败，请检查   taro v1.2.12

**Comment by luckyadam** [comment]
能否提供一个可以复现的 demo

**Comment by zhangfan6644777** [comment]
> 能否提供一个可以复现的 demo



> 能否提供一个可以复现的 demo

问题解决了  我重新npm run dev:weapp 就好了
