### ISSUE TITLE
npm run dev:alipay 控制台报错

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#2137]
**问题描述**
如题：npm run dev:alipay 控制台报错

**报错信息**

npm ERR! missing script: dev:alipay
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     dev:weapp

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhouxun/.npm/_logs/2019-02-12T01_08_36_999Z-debug.log

**系统信息**
Taro CLI 1.2.3 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      npm: 6.4.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.4 => 1.2.3 
      @tarojs/plugin-babel: 1.2.4 => 1.2.3 
      @tarojs/plugin-csso: 1.2.4 => 1.2.3 
      @tarojs/plugin-sass: 1.2.4 => 1.2.3 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.3 
      @tarojs/router: 1.2.4 => 1.2.3 
      @tarojs/taro: 1.2.4 => 1.2.3 
      @tarojs/taro-h5: 1.2.4 => 1.2.3 
      @tarojs/taro-weapp: 1.2.4 => 1.2.3 
      @tarojs/webpack-runner: 1.2.4 => 1.2.3 
      eslint-config-taro: 1.2.4 => 1.2.3 
      eslint-plugin-taro: 1.2.4 => 1.2.3 

**补充信息**

**Comment by luckyadam** [comment]
自行补充一下 `dev:alipay` 这个指令

"dev:alipay": "taro build --type alipay --watch"
