### ISSUE TITLE
端API的能力，从媒体开始，就只支持微信小程序吗？

### ISSUE THREAD

**Issue by xiaohuoni** [NervJS/taro#2138]
**问题描述**
https://nervjs.github.io/taro/docs/native-api.html
查看文档，端能力api，从媒体开始之后的，就只有微信小程序、H5、RN三个对比项，最新的版本应该支持到了字节跳动小程序，但是文档中，对这个端能力并没有体现。
**复现步骤**
1。查看官网文档https://nervjs.github.io/taro/docs/native-api.html
**期望行为**
不支持的请在文档中标注出来，感谢

**Comment by luckyadam** [comment]
我们近期会更新下文档~

**Comment by xiaohuoni** [comment]
感谢@luckyadam

**Comment by Chen-jj** [comment]
#1199
