### ISSUE TITLE
不支持ES6 import default 的路径规则？

### ISSUE THREAD

**Issue by NoahSun** [NervJS/taro#214]
添加了目录 components
![image](https://user-images.githubusercontent.com/12728157/41958237-065c20c0-7a1c-11e8-8a94-6f20a630994b.png)

当写为 `import FontIcon from '../../components/FontIcon` 时编译会有问题：

![image](https://user-images.githubusercontent.com/12728157/41958404-84b5318c-7a1c-11e8-82f6-816029c5b929.png)
![image](https://user-images.githubusercontent.com/12728157/41958475-bd01c55a-7a1c-11e8-9055-c89b0948cc87.png)

写为 `import FontIcon from '../../components/FontIcon/index`  才会引用正确

**Comment by luckyadam** [comment]
嗯嗯，已知 bug ，下个版本修复

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/f8e43d95f605b800101d98fe6a593ea84c06bc64
