### ISSUE TITLE
RN支持？

### ISSUE THREAD

**Issue by soqt** [NervJS/taro#2140]
有没有计划短期内支持RN？

**Comment by js-newbee** [comment]
RN 是有支持的，`npm run dev:rn` 即可，也可以看下这个官方的 demo
[https://github.com/NervJS/TodoMVC](https://github.com/NervJS/TodoMVC)
基本的功能是没啥问题的，不过目前相对而言还不是很完善

**Comment by boot-vue** [comment]
app端很鸡肋   支付还得通过调起浏览器H5支付, 不知道何年能直接调起支付

**Comment by soqt** [comment]
我发现我留言留错地方了 想留在Taro-UI那边，关Issue了
