### ISSUE TITLE
taro 编译h5  Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by KingYYH** [NervJS/taro#2142]
index.js?ef09:574 Uncaught TypeError: Cannot read property 'dispatch' of undefined
    at Connect.initSelector (index.js?ef09:574)
    at new Connect (index.js?ef09:502)
    at mountComponent (index.js?36eb:1521)
    at ComponentWrapper.init (index.js?36eb:1871)
    at createElement (index.js?36eb:1385)
    at mountVNode (index.js?36eb:1517)
    at Object.render (index.js?36eb:1797)
    at eval (app.js?d0a8:404)
    at Object../.temp/app.js (app.js:950)
    at __webpack_require__ (app.js:765)

**Comment by KingYYH** [comment]
编译小程序是正常的，版本依赖都是最新  node 8.11.4

**Comment by luckyadam** [comment]
不要对 App 使用 redux 连接

**Comment by EvanMaFYH** [comment]
> 不要对 App 使用 redux 连接

在微信小程序下对App使用redux没有报错，应该没啥问题吧如果我只需要编译小程序的话，因为我需要在小程序启动的时候将storage中的内容存到state里

**Comment by summer-yyyn** [comment]
遇到同样的问题，请问有解决办法么？

**Comment by HUYIJUNCODING** [comment]
* 我这里也遇到同样问题,可是并没有使用connet进行redux连接,关于store的关联写法如下,应该没有问题吧


```js
import {Provider} from '@tarojs/redux'
import StoreUtil from "./store/stateStore";

const store = StoreUtil.getStore();
...

  render() {
        return (
            <Provider store={store}>
            </Provider>
        )
    }

**Comment by shengbowen** [comment]
有什么解决方法吗，难道各位都没有redux持久化的需求吗

**Comment by 54853315** [comment]
> * 我这里也遇到同样问题,可是并没有使用connet进行redux连接,关于store的关联写法如下,应该没有问题吧
> 
> ```js
> import {Provider} from '@tarojs/redux'
> import StoreUtil from "./store/stateStore";
> 
> const store = StoreUtil.getStore();
> ...
> 
>   render() {
>         return (
>             <Provider store={store}>
>             </Provider>
>         )
>     }
> ```

我在taro2.2.6（目前v2系最高版本）中，可以正常打印出`console.log(store)`。

同时请注意这里提到的细节：https://taro-docs.jd.com/taro/docs/redux/#hooks 这里说到所需的依赖，如果你是用正常的方式安装taro2.2.6，则不用再刻意去安装依赖。

taro官方的redux example：https://github.com/NervJS/taro-redux-sample
