### ISSUE TITLE
componentWillUnmount 比 componentDidMount 先执行的问题

### ISSUE THREAD

**Issue by xn330125** [NervJS/taro#2143]
**问题描述**
微信小程序中，componentWillUnmount执行时，componentDidMount还未执行，导致在didmount中初始化的变量无法引用

```js
componentDidMount() {
        this.disposor = reaction(() => globalStore.data, () => {
            this.reset();
        });
 }
componentWillUnmount() {
        // 这里有可能会报错，this.disposor is not a funtion
        this.disposor();
}
```

**系统信息**

 - Taro 版本：1.2.2
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@xn330125 `componentDidMount` 对应小程序组件的 `ready` 和小程序页面的 `onReady`，componentWillUnmount 则对应 `detached`。
可以提供一份可稳定复现的代码我们测试一下。

**Comment by xn330125** [comment]
因为这个报错是前端错误监控上报的，我本地也复现不了，所以才想来请教一下是否碰到过类似的问题。目前的解决方法就是先判断有没有这个函数，再执行。
```
this.disposor && this.disposor();
```

**Comment by Chen-jj** [comment]
@xn330125 看看有没有其它地方影响了吧，小程序都还没 ready 和 onReady 时你缺销毁了页面或组件（例如用户打开页面后快速返回），你的处理是正确的，或者把方法定义放 `componentWillMount` 中。
