### ISSUE TITLE
Taro.navigateBack 之后怎么重载数据？

### ISSUE THREAD

**Issue by soymikey** [NervJS/taro#2144]
页面在componentWillMount的时候 转跳到登入页面，登入成功后Taro.navigateBack 后怎么重载数据？ 谢谢大家~~ 新年快乐 Happy New Year Everyone~~

**Comment by zongshixuebuhui** [comment]
在前一个页面用didshow生命周期

**Comment by luckyadam** [comment]
componentDidShow
