### ISSUE TITLE
地图图标的点击事件bindmarkertap没有效果

### ISSUE THREAD

**Issue by XanderXueMingJi** [NervJS/taro#2147]
问题描述 [地图图标的点击事件bindmarkertap没有效果]

复现步骤

1. 使用@tarojs/components提供的Map标签显示地图与标点(成功)
2. 给地图上的标点添加点击事件(失败, 控制台提示: VM14603:1 Do not have onMarkertap handler in component: pages/map/index. Please make sure that onMarkertap handler has been defined in pages/map/index.)
3. 发现问题, 是在微信开发者工具的编译器里, index.js的_class2.$$events没有添加onMarkertap才导致控制台没找到对应的方法, 目前每次编译后都要手动输入:
_class2.$$events = ["onMarkertap"]

期望行为 [这里请用简洁清晰的语言描述你期望的行为]
代码编译时希望_class2.$$events能自动添加bindmarkertap对应的点击事件

报错信息
Do not have onMarkertap handler in component: pages/map/index.

系统信息
操作系统: Windows 10
Taro 版本 v1.2.12
Node.js 版本 8.11.3
报错平台 6.5.0

**Comment by luckyadam** [comment]
麻烦贴一下代码

**Comment by ghyzx** [comment]
我也遇到了这个问题，我来贴一下吧
<img width="1444" alt="map" src="https://user-images.githubusercontent.com/5229158/52844948-cee08780-3140-11e9-9782-d82d1eb71d6c.png">
地图能正常显示出来，只是无法响应点击事件；

网上有提到pages注册顺序可能有影响，但我这个是新工程，一共只有2个page，交换顺序后没变化；
<img width="249" alt="pages" src="https://user-images.githubusercontent.com/5229158/52845138-4b736600-3141-11e9-9e4f-9e0674b4054b.png">

附：
taro info 信息如下
👽 Taro v1.2.12
  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm

package.json 信息如下
"dependencies": {
    "@tarojs/components": "1.2.12",
    "@tarojs/router": "1.2.12",
    "@tarojs/taro": "1.2.12",
    "@tarojs/taro-alipay": "1.2.12",
    "@tarojs/taro-h5": "1.2.12",
    "@tarojs/taro-swan": "1.2.12",
    "@tarojs/taro-tt": "1.2.12",
    "@tarojs/taro-weapp": "1.2.12",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.0.0"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "1.2.12",
    "@tarojs/plugin-csso": "1.2.12",
    "@tarojs/plugin-sass": "^1.2.12",
    "@tarojs/plugin-uglifyjs": "1.2.12",
    "@tarojs/webpack-runner": "1.2.12",
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-taro": "1.2.12",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-taro": "1.2.12"
  }


微信调试基础库：v2.6.0

@luckyadam  麻烦帮忙看一下，谢谢。

**Comment by TiamoJrZhang** [comment]
遇到同上相同的问题，麻烦@luckyadam大佬看一下

**Comment by ghyzx** [comment]
一直没更新，有解决方案吗？

**Comment by jinjinjin0731** [comment]
@ghyzx  你可以问题 ，或许看这个可以解决[https://nervjs.github.io/taro/docs/event.html](https://nervjs.github.io/taro/docs/event.html)

**Comment by ghyzx** [comment]
@jinjinjin0731  试了还是没效果

**Comment by ghyzx** [comment]
我发现问题所在了， npm run dev:weapp 生成dist文件时， 没有把 bind开头的方法注册到对应的方法列表里， _class.$$events = ["subNum", "addNum"], _temp2);  ，当我手动添加后就OK了，不知道这是不是一个隐藏的bug。
