### ISSUE TITLE
h5 下switchTab 不支持？目前有没有替代方案？

### ISSUE THREAD

**Issue by mysky621** [NervJS/taro#2151]
从应用内部页面，直接使用Taro.redirectTo({url: 'test?id=1' }），跳转到tabbar得页面，手机返回键，返回直接逐级返回，没有销毁堆栈。
1.有没有销毁堆栈得函数？
2.taro 高版本是否已经 支持switchTab ？
3.tarojs/taro-h5 和 tarojs/taro 中都有类似 TaroH5.switchTab() 和Taro.switchTab() ，使用TaroH5.switchTab()依然提示不支持，不知道这俩包有啥区别？

**Comment by Littly** [comment]
1. 销毁堆栈功能暂未实现..
2. tabbar功能正在重构中 顺利的话可以把switchTab功能也完成
3. @tarojs/taro是api的列表，@tarojs/taro-{h5|weapp|...}才是对应终端的具体api实现

**Comment by ShaoGongBra** [comment]
自己写一个tabbar

**Comment by Littly** [comment]
目前h5端已加入switchTab api，至少调用是ok的，但历史栈没有办法销毁。
