### ISSUE TITLE
Textarea在开启小键盘的时候，setState会执行不成功

### ISSUE THREAD

**Issue by wuyulong1990** [NervJS/taro#2152]
```js
JS：
onInput = e => {
    this.setState({ value: e.target.value });
};

send = () => {
    const { value } = this.state;

    // 这个setState会执行不成功
    this.setState({ value: '' });

    /** 这里是我的解决方法，需要延时100毫秒等待小键盘消失后再执行setState
    setTimeout(() => {
      this.setState({ value: '' });
    }, 100);
    */
};

HTML：
<Textarea
   maxlength={-1}
   showConfirmBar={false}
   cursorSpacing={10}
   value={this.state.value}
   onInput={this.onInput}
   className="input"
/>
<Button type="primary" className="send-btn" onClick={this.send}>
   <View>发送</View>
</Button>
```
我的版本：
    "@tarojs/async-await": "^1.0.7",
    "@tarojs/components": "^1.0.7",
    "@tarojs/redux": "^1.0.7",
    "@tarojs/redux-h5": "^1.0.7",
    "@tarojs/router": "^1.0.7",
    "@tarojs/taro": "^1.0.7",
    "@tarojs/taro-h5": "^1.0.7",
    "@tarojs/taro-weapp": "^1.0.7",
    "@tarojs/cli": "^1.0.7",
    "@tarojs/plugin-babel": "^1.0.7",
    "@tarojs/plugin-csso": "^1.0.7",
    "@tarojs/plugin-sass": "^1.0.7",
    "@tarojs/plugin-uglifyjs": "^1.0.7",
    "@tarojs/webpack-runner": "^1.0.7"

平台：微信小程序
taro版本：Taro v1.0.0-beta.14

发现的结论：
在有小键盘的时候this.setState({ value: '' });会执行不成功。

**Comment by Chen-jj** [comment]
@wuyulong1990 在安卓和 iOS 上都测试过，不能复现。
可以把 CLI 和依赖都升级到 1.2.12 后再试试。
另外你的依赖和 CLI 非相同版本，这样很容易有问题的，务必保持两者版本一致。
