### ISSUE TITLE
官网文档规范文字错误

### ISSUE THREAD

**Issue by biubiubiuG** [NervJS/taro#2153]
在教程->Taro规范 里标签一栏应该是 '始终使用自闭合标签' 吧? 是不是写错了,'始终时候自闭合标签' 这句话不通顺的
![image](https://user-images.githubusercontent.com/30515805/52694960-4332f380-2fa6-11e9-8359-630fefc6abf2.png)

**Comment by luckyadam** [comment]
可以提个 PR 修改一下咯

**Comment by Garfield550** [comment]
@luckyadam 已经提出了 PR，麻烦跟进一下，请 review
