### ISSUE TITLE
组件样式影响外部样式

### ISSUE THREAD

**Issue by rotate720deg** [NervJS/taro#2156]
![image](https://user-images.githubusercontent.com/16872226/52697671-e129bc80-2fac-11e9-91a3-b0fee25c3671.png)
h5编译：组件样式设置`.title`后，会影响到任意页面的样式和组件样式
![image](https://user-images.githubusercontent.com/16872226/52697770-2221d100-2fad-11e9-957b-8b87588deb31.png)
![image](https://user-images.githubusercontent.com/16872226/52697800-306fed00-2fad-11e9-985a-6c82d5df13ed.png)
经过测试，组件的样式貌似不仅仅适用组件，而是全局的？

**Comment by luckyadam** [comment]
暂时可以通过设置相对独立样式类名，或者开启 CSS Modules 来避免冲突
https://nervjs.github.io/taro/docs/css-modules.html

**Comment by rotate720deg** [comment]
> 暂时可以通过设置相对独立样式类名，或者开启 CSS Modules 来避免冲突
> https://nervjs.github.io/taro/docs/css-modules.html

多谢
