### ISSUE TITLE
px compiled into NaNrpx in sass, yarn dev:weapp

### ISSUE THREAD

**Issue by LoveLeeYangYang** [NervJS/taro#2157]
**问题描述**
微信小程序，.scss 的样式文件中，带 px 单位的值被编译为 NaNrpx，样式失效

**复现步骤**
1. width: 80px;
2. yarn dev:weapp
3. See error

[或者可以直接贴源代码，能贴文字就不要截图]

```scss
.some_class {
  width: 80px;
}
```

**期望行为**
希望 px 可以被正确地编译

**报错信息**

width:NaNrpx;

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.1.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
你是否修改了配置里的 designWidth

**Comment by greatwhole** [comment]
> 你是否修改了配置里的 designWidth

你好，我出了一样的错，自查了下是改了配置 designWidth 。请问现在改这个参数有什么需要注意的地方吗？

**Comment by LoveLeeYangYang** [comment]
> 你是否修改了配置里的 designWidth

对的，已经改回来了

**Comment by LoveLeeYangYang** [comment]
> > 你是否修改了配置里的 designWidth
> 
> 你好，我出了一样的错，自查了下是改了配置 designWidth 。请问现在改这个参数有什么需要注意的地方吗？

只有3个合法值吧，其它要自己换算

**Comment by FrankFan** [comment]
> 只有3个合法值吧，其它要自己换算

请问具体怎么换算呢？
