### ISSUE TITLE
H5 Picker组件[v1.2.12]：multiSelector模式不触发onColumnchange

### ISSUE THREAD

**Issue by jeezliu** [NervJS/taro#2158]
**问题描述**
H5 Picker组件[v1.2.12]：multiSelector模式不触发onColumnchange

**复现步骤**
使用 npx @tarojs/cli init myApp 初始化的工程，以下测试代码不触发
```js
  onColumnchange = e => {
    console.log('eee', e);
  }
  onChange = e => {
    console.log('ccc', e);
  }

  render () {
    const r1 = [{name: 'aaa', key: 10}, {name: 'aaa2', key: 11}, {name: 'aaa3', key: 12}];
    const r2 = [{name: 'ddd', key: 20}, {name: 'ddd2', key: 21}, {name: 'ddd3', key: 22}];
    const r3 = [{name: 'bbb', key: 30}, {name: 'bbb2', key: 31}, {name: 'bbb', key: 32}];

    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <Picker mode='multiSelector' rangeKey='name' range={[r1, r2, r3]}
          onColumnchange={this.onColumnchange}
          onChange={this.onChange}
        >
         <View>Picker按钮</View>
        </Picker>
      </View>
    )
  }

```

**期望行为**
选中每一列触发onColumnchange事件

**系统信息**
System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.12 => 1.2.12
      @tarojs/plugin-babel: 1.2.12 => 1.2.12
      @tarojs/plugin-csso: 1.2.12 => 1.2.12
      @tarojs/plugin-sass: 1.2.12 => 1.2.12
      @tarojs/plugin-uglifyjs: 1.2.12 => 1.2.12
      @tarojs/router: 1.2.12 => 1.2.12
      @tarojs/taro: 1.2.12 => 1.2.12
      @tarojs/taro-alipay: 1.2.12 => 1.2.12
      @tarojs/taro-h5: 1.2.12 => 1.2.12
      @tarojs/taro-swan: 1.2.12 => 1.2.12
      @tarojs/taro-tt: 1.2.12 => 1.2.12
      @tarojs/taro-weapp: 1.2.12 => 1.2.12
      @tarojs/webpack-runner: 1.2.12 => 1.2.12
      eslint-config-taro: 1.2.12 => 1.2.12
      eslint-plugin-taro: 1.2.12 => 1.2.12
    npmGlobalPackages:
      typescript: 3.1.5

**Comment by jinjinjin0731** [comment]
onColumnChange。 文档没有更新过来，你可以提个 Pr

**Comment by jeezliu** [comment]
> onColumnChange。 文档没有更新过来，你可以提个 Pr

可以了 属性名改成了onColumnChange

> onColumnChange。 文档没有更新过来，你可以提个 Pr

好的，属性名变成了驼峰 onColumnChange
