### ISSUE TITLE
taro-cli 初始化 plugins 配置时操作了原对象并未能正确去重

### ISSUE THREAD

**Issue by xiaoyuze88** [NervJS/taro#2160]
**问题描述**
当 `plugins.babel.plugins` 中含有非字符串的 babel 插件配置时，该插件将会执行两次。

原因：
taro-cli 中， src/weapp.js 及 src/util/resolve_npm_files.js 两个文件中都操作了 `defaultBabelConfig` 的原对象，且 `pluginsConfig` 变量是 merge 出来的新对象，导致 Array.from(new Set) 未能正确去重。

**复现步骤**
1. 
`plugins.babel.plugins`中加入如下插件配置
```
['add-header-comment', {
    header: ['This string will be inserted in a comment header'],
}]
```
2. 编译
3. 看到结果，最终每个文件都打印了两行 comment

**期望行为**
插件不要重复执行

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
? Taro v1.2.12

  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS High Sierra 10.13.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      babel-plugin-transform-jsx-to-stylesheet: 1.2.12 => 1.2.12 
      postcss-pxtransform: 1.2.12 => 1.2.12 
      react-native: ^0.55.4 => 0.55.4 
    npmGlobalPackages:
      typescript: 1.8.10

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
可以把你的修改提交一个 PR 过来~

**Comment by xiaoyuze88** [comment]
@luckyadam https://github.com/NervJS/taro/pull/2161

**Comment by luckyadam** [comment]
OJBK
