### ISSUE TITLE
Taro微信小程序的分包代码在编译支付宝小程序后提示找不到该该页面

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#2162]
**问题描述**
     最近又一个需求，就是Taro代码同时支持编译微信和支付宝小程序，因为之前先做微信小程序，并且又做分包处理。在编译支付宝小程序后，分包后的页面在被跳转时会提示找不到该页面。
     在看了支付宝小程序论坛后，支付宝小程序不支持分包。
     现在的问题就是，怎么一套Taro代码，对微信的分包和支付宝做兼容处理。

```js
app.js

`  config = {
    pages: [
      'pages/index/index',
      // 到期
      'pages/overTime/overTime',
      // 授权
      'pages/authorize/userAuthorize',
      'pages/authorize/noLocation'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: '小程序平台',
      navigationBarTextStyle: 'black'
    },
    subPackages: [
      {// 门店
        root: "store/",
        pages: [
          'pages/shopIndex/shopIndex',
          'pages/address/address',
          'pages/mCreateOrder/mCreateOrder',
          'pages/mCoupon/mCoupon',
          'pages/orderList/orderList',
          'pages/orderDetail/orderDetail',
          'pages/mShopDetail/mShopDetail',
          'pages/myInfo/myInfo',
          'pages/moreStores/moreStores',
          'pages/storeMapList/storeMapList',
          'pages/integral/integralStore/integralStore',
          'pages/integral/integralDetail/integralDetail',
          'pages/integral/record/record',
          'pages/integral/integralIndex/integralIndex'
        ]
      },
      { // 电商
        root: "e-commerce/",
        pages: [
          'pages/searchGoods/searchGoods',
          // 'pages/goodsDetails/goodsDetails',
          'pages/userCenter/userCenter',
          'pages/addressEdit/addressEdit',
          // 'pages/cartList/cartList',
          'pages/payOrder/payOrder',
          'pages/orderList/orderList',
          'pages/orderDetail/orderDetail',
          'pages/viewOrder/viewOrder',
          'pages/goodsList/goodsList',
          'pages/coupon/couponList/couponList',
          'pages/coupon/myCouponList/myCouponList',
          'pages/coupon/couponDetail/couponDetail',
          'pages/integral/integralStore/integralStore',
          'pages/integral/integralDetail/integralDetail',
          'pages/integral/record/record',

        ]
      }
    ]
  };`

```

**期望行为**
在app.js中做分包兼容

**系统信息**
Taro CLI 1.2.3 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      npm: 6.4.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: 1.2.4 => 1.2.4 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-sass: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.3 => 1.2.3 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.3 => 1.2.3 
      @tarojs/webpack-runner: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4 

 - 操作系统: [OS 1.14.1]
 - Node.js 版本 [v10.8.0]

**Comment by zhou1992zg** [comment]
支付宝开发者工具的错误提示：
`模拟器启动错误
找不到启动页面：找不到页面：store/pages/shopIndex/shopIndex
请检查编译模式设置是否正确`

**Comment by zhou1992zg** [comment]
有什么好的做兼容的建议，请大佬指点指点

**Comment by luckyadam** [comment]
我在 CLI 这边做下处理吧

**Comment by zhou1992zg** [comment]
大佬 多久能做出来？

**Comment by zhou1992zg** [comment]
@luckyadam 大佬 什么时候处理好？急

**Comment by luckyadam** [comment]
@zhou1992zg 今天处理一下

**Comment by zhou1992zg** [comment]
@luckyadam 大佬，这个问题处理的怎么样了？

**Comment by chaojiangcn** [comment]
![image](https://user-images.githubusercontent.com/29300205/60079805-41055080-9761-11e9-80c6-3ac765895287.png)
没有分包不知道这个原因是为什么
