### ISSUE TITLE
&nbsp; 空格在 taro 1.2.4 以上的版本中无效

### ISSUE THREAD

**Issue by zw130633** [NervJS/taro#2163]
**问题描述**
&nbsp; 空格在 taro 1.2.5、1.2.8、1.2.12 版本中无效，其它 1.2.4 以上的版本没做测试，不知道是不是也问题

**复现步骤**

**期望行为**

**报错信息**

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [1.2.12]
 - Node.js 版本 [8.9.0]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
你需要设置 text 组件的 decode 为 true 才能使用 &nbsp;
参考：
https://developers.weixin.qq.com/miniprogram/dev/component/text.html
