### ISSUE TITLE
引入mobx的页面, 设置标题navigationBarTitleText失效

### ISSUE THREAD

**Issue by magicbing** [NervJS/taro#2164]
**问题描述**
引入mobx的页面, 设置标题navigationBarTitleText失效

**复现步骤**
引入mobx并使用后
import { observer, inject } from '@tarojs/mobx'
@inject('xxx')
@observer
设置title失效
  config = {
    navigationBarTitleText: 'xxx',
  }

未引入mobx前正常

**系统信息**
👽 Taro v1.2.11

  Taro CLI 1.2.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\app\nodejs10\node.EXE
      Yarn: 1.13.0 - D:\app\yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\app\nodejs10\npm.CMD

**Comment by yuche** [comment]
config 是不能动态调整的

**Comment by magicbing** [comment]
> config 是不能动态调整的

没有动态设置config的title, 写死一个字符串也是失效的, 在h5里
怀疑是@Inject的问题

等下我升级版本试一下又有没有效果

**Comment by wangcongyi** [comment]
@yuche  如果小程序自身限制，为什么H5也不行？
