### ISSUE TITLE
条件判断在小程序中的问题

### ISSUE THREAD

**Issue by zhangfan6644777** [NervJS/taro#2165]
{process.env.TARO_ENV === 'h5' &&
            <View className="buttonH5">手机号一键登录</View>
          }  这个代码运行在小程序为啥 要显示一个false   怎么弄掉
![image](https://user-images.githubusercontent.com/22075172/52761392-336eea00-304e-11e9-9063-68fae2a34ce9.png)

**Comment by zhangfan6644777** [comment]
我想知道 文档上写的是    如果是 false，Taro 会忽略并跳过它。   为什么我这个是false  但是taro没有忽略

**Comment by yuche** [comment]
当你有 process.env 判断时先这样写吧：

```jsx
{process.env.TARO_ENV === 'h5'
 ? <View className="buttonH5">手机号一键登录</View>
 : ''
      }
```

这个是一个 babel 插件的 bug。

**Comment by zhangfan6644777** [comment]
> 当你有 process.env 判断时先这样写吧：
> 
> ```js-jsx
> {
>   process.env.TARO_ENV === 'h5'
>      ? <View className="buttonH5">手机号一键登录</View>
>      : ''
> }
> ```
> 
> 这个是一个 babel 插件的 bug。

好的 解决了 谢谢  空串是可以的 如果我写null 的话 会多出来一个空view标签
