### ISSUE TITLE
babel插件中无法正确获取文件路径 filename

### ISSUE THREAD

**Issue by xiaoyuze88** [NervJS/taro#2168]
**问题描述**
正常 babel 插件中应可以通过 state.file.opts.filename 访问到当前编译文件的绝对路径，但是 taro 中调用的 babel 插件中获取的 filename 始终是 `unknown`。如：

```
exports.default = () => ({
    visitor: {
      Program(path, state) {
           state.file.opts.filename // 正常应该为当前编译文件的路径，但是 taro 中始终为 'unknown'
      },
})
```

原因是应该是 taro-plugin-babel 中未正确传入 opts.filename，导致插件中始终无法获取正确的文件路径。同时现在 taro-cli 中的 `compileScriptFile` 方法调用 `callPlugin('babel')` 时传入的文件路径为 `entryFilePath`，我的理解应该传入 `sourceFilePath`。

**Comment by xiaoyuze88** [comment]
https://github.com/NervJS/taro/pull/2172

这里不太确定 taro-plugin-babel 中的入参 file 最初的作用是什么，因为原函数中并未使用该入参，但是根据调用方式来推测应该是当前编译文件路径，如果是这样的话那 taro-cli 中的用法就有问题了，应该传入 
 sourceFilePath 而不是始终传入 entryFilePath。

**Comment by luckyadam** [comment]
已经合入啦

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/14b5b7158fc17f80f514030d341cc6c2df6b19e1
