### ISSUE TITLE
swiper组件中的cicular衔接滑动编译成小程序没问题，但是编译成H5就没效果了

### ISSUE THREAD

**Issue by junxinhuang21** [NervJS/taro#2173]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
提供一下复现代码，以及你的 taro 版本

**Comment by junxinhuang21** [comment]
版本是1.2.4，问题主要是请求过来的数据就不能衔接滑动，如果放静态的四张图片就可以，估计是你们封装swiper组件时，获取数据后没有更新swiper节点

<Swiper
className='activity'
indicatorActiveColor='#fff' 
indicatorColor='#d2d2d2'
circular
indicatorDots
autoplay>
{this.state.imgUrls.map((item, index) => {
return (<SwiperItem key={index} >
<Image src={item.img_url} className='slide-image' />
</SwiperItem>)
})}
</Swiper>
 
componentDidMount() {
login().then((res) => {
if (res.code == 200) {
this.setState({
imgUrls: res.data
})
}
})


huang173348950@163.com
 
发件人： JinJinJin
发送时间： 2019-02-14 15:55
收件人： NervJS/taro
抄送： junxinhuang21; Author
主题： Re: [NervJS/taro] swiper组件中的cicular衔接滑动编译成小程序没问题，但是编译成H5就没效果了 (#2173)
提供一下复现代码，以及你的 taro 版本
―

**Comment by junxinhuang21** [comment]
编译成小程序时是没问题的，只有在编译成H5时circular是无效的，图片不能循环轮播

**Comment by jinjinjin0731** [comment]
有更新节点的操作的。 我根据你的代码复现一下吧

**Comment by jinjinjin0731** [comment]
更新到最新版本即可
