### ISSUE TITLE
Radio组件 编译成支付宝小程序后 选项文字描述消失了 微信小程序正常显示（未用TaroUI的AtRadio）

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#2174]
**问题描述**
如题

```js
`<View className='radio-list'>
          <RadioGroup name={nameKey}>
                  {item.items.map((items, i) => {
                         return (<Label className='radio-list__label' for={i} key={i}>
                            <Radio className='radio-list__radio' color='#6190e8'
                                checked={items.checked === 1}
                                value={items.name}>{items.name}</Radio>
                         </Label>)
                     })}
         </RadioGroup>
 </View>`

```
{items.name}在编译成支付宝小程序消失了，只显示了单选按钮

**系统信息**

Taro CLI 1.2.3 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      npm: 6.4.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: 1.2.4 => 1.2.4 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-sass: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.3 => 1.2.3 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.3 => 1.2.3 
      @tarojs/webpack-runner: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4 

 - 操作系统: [e.g. OS 10.14.1]
 - Node.js 版本 [e.g. v10.8.0]
 - 报错平台 [alipay]

**Comment by zhou1992zg** [comment]
`<radioclass="radio-list__radio"color="#6190e8"value="女士"></radio>`
编译成支付宝小程序成这样

微信小程序是这样
`<radioclass="radio-list__radio"color="#6190e8"value="女士">女士</radio>`

**Comment by zhou1992zg** [comment]
不知道怎么回事？请大佬看看

**Comment by jinjinjin0731** [comment]
@zhou1992zg  经测试，这属于支付宝小程序不支持该写法问题。 不支持在 Radio 标签内部写文字，你可以用支付宝原生代码测试一下。  你需要改一下写法
`
<Label className='radio-list__label' for={i} key={i}>
       <Radio className='radio-list__radio' color='#6190e8'
           checked={items.checked === 1} value={items.name}/> {items.name}
</Label>
`

**Comment by zhou1992zg** [comment]
这种写法支持微信小程序吗？

**Comment by jinjinjin0731** [comment]
支持。 但是微信小程序官网的写法也是 `<Radio value={items.name}/> {items.name}  `，但是支持嵌套。这两个你可以用原生的写法去尝试一下。 这种原生就不支持的做法，那么只能在写法上来避免了

**Comment by zhou1992zg** [comment]
ok!测试了支持微信小程序，谢谢！
