### ISSUE TITLE
Taro编译的RN能否实现操作文件增删改和node.js中child-process的功能

### ISSUE THREAD

**Issue by hugetiny** [NervJS/taro#2177]
Taro编译的RN能否实现操作文件增删改和node.js中child-process的功能，据我所知，EXPO是不支持node.js层面的功能的

**Comment by hugetiny** [comment]
比如RN能实现的fs部分功能：https://github.com/itinance/react-native-fs

**Comment by Pines-Cheng** [comment]
文件相关的操作需要依赖原生代码，去掉 expo 依赖之后就可以做了。

**Comment by hugetiny** [comment]
Taro依赖于Expo，在导出的Expo上可以去掉Expo？

**Comment by Pines-Cheng** [comment]
1.2.21 版本已经去掉了 Expo 依赖。

**Comment by hugetiny** [comment]
@Pines-Cheng 好的谢谢。1.2.21去掉了 Expo 依赖 是否意味着编译出来的RN版本能够用现有的所有RN库？

**Comment by Pines-Cheng** [comment]
是的，按照文档 [跨平台开发](https://nervjs.github.io/taro/docs/envs.html) 来就行。
