### ISSUE TITLE
怎么解析HTML和markdown等文本格式，小程序是有wxParse可以用，但是Taro不晓得怎么用

### ISSUE THREAD

**Issue by aushion** [NervJS/taro#218]
解析HTML和markdown

**Comment by zacksleo** [comment]
如果是HTML，可以直接使用<RichText nodes={this.state.nodes}> , this.state.nodes 可以是字符串，也可以是 Array,  [参考代码](https://github.com/NervJS/taro/blob/master/packages/taro-components/src/components/rich-text/__test__/index.test.js)

#128

**Comment by aushion** [comment]
@zacksleo 可以的，我试了的确可行，RichText可以

**Comment by luckyadam** [comment]
最新版本的 beta 已经支持使用 `wxParse` 了，这是个例子
https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js

**Comment by caoleiqing** [comment]
> 最新版本的 beta 已经支持使用 `wxParse` 了，这是个例子
> https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js

为什么我用了以后解析不了link标签呢？

**Comment by junxinhuang21** [comment]
> @zacksleo 可以的，我试了的确可行，RichText可以
但是RichText并不想wxparse那样图片自适应

**Comment by jinyindu** [comment]
@luckyadam 这个百度 和支付宝小程序支持吗

**Comment by z-Listening** [comment]
> 最新版本的 beta 已经支持使用 `wxParse` 了，这是个例子
> https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js

copy代码回来，为什么加载不出来啊？
![image](https://user-images.githubusercontent.com/18062954/59262996-ddfcbf80-8c72-11e9-95a3-5d2e047b0b5b.png)
![image](https://user-images.githubusercontent.com/18062954/59263011-e3f2a080-8c72-11e9-9709-555281730be2.png)

template这里还有报错
![image](https://user-images.githubusercontent.com/18062954/59263047-f076f900-8c72-11e9-89be-a3b99adf42b2.png)

componentDidMount里可以正确拿到WxParse，求解！！控制台没有报错。
![image](https://user-images.githubusercontent.com/18062954/59263112-07b5e680-8c73-11e9-8be3-23f46cba008a.png)

**Comment by z-Listening** [comment]
> > 最新版本的 beta 已经支持使用 `wxParse` 了，这是个例子
> > https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js
> 
> copy代码回来，为什么加载不出来啊？
> ![image](https://user-images.githubusercontent.com/18062954/59262996-ddfcbf80-8c72-11e9-95a3-5d2e047b0b5b.png)
> ![image](https://user-images.githubusercontent.com/18062954/59263011-e3f2a080-8c72-11e9-9709-555281730be2.png)
> 
> template这里还有报错
> ![image](https://user-images.githubusercontent.com/18062954/59263047-f076f900-8c72-11e9-89be-a3b99adf42b2.png)
> 
> componentDidMount里可以正确拿到WxParse，求解！！控制台没有报错。
> ![image](https://user-images.githubusercontent.com/18062954/59263112-07b5e680-8c73-11e9-8be3-23f46cba008a.png)

原因找到了：
![image](https://user-images.githubusercontent.com/18062954/59265028-13a3a780-8c77-11e9-90b7-318c6725feb5.png)

在componentDidMount里同时setState，wxParse就无法渲染出内容

**Comment by z-Listening** [comment]
> 最新版本的 beta 已经支持使用 `wxParse` 了，这是个例子
> https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js

请问template forbidden怎么办！！提交代码加了pre-commit的eslint检查，这个template forbidden，commit过不了。。😭

**Comment by Imagine-Tom** [comment]
> > 最新版本的 beta 已经支持使用 `wxParse` 了，这是个例子
> > https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js
> 
> 请问template forbidden怎么办！！提交代码加了pre-commit的eslint检查，这个template forbidden，commit过不了。。😭

问下我也使用了你同样的组件
但是我在H5的时候会报错。说找不到wx 你那边会报错吗？

**Comment by EdisonVan** [comment]
<template> is forbidden, 在 Taro 中无法使用 HTML 标签。请问这个大家是怎么解决的？

**Comment by Genense** [comment]
taro怎么解析markdown

**Comment by xu756** [comment]
> taro怎么解析markdown

有解决办法没
