### ISSUE TITLE
H5 路由切换

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#2180]
h5版本中。路由跳转后，上个页面的html标签还在，这个不太友好。比如滚动到底部加载更多。写了一个通用组件。页面跳转之后，上个页面的监听还在，还得手动解绑。。。

**Comment by Littly** [comment]
需要想办法解决。
目前碰到的问题是，taro里 componentWillUnmount 对应小程序的 unload/detach 生命周期，如果在路由跳转之后销毁html标签，会导致跳转前页面的 componentWillUnmount 生命周期被调用，跟小程序的表现不一致，所以目前采用的是保留标签这一折中的方式。
