### ISSUE TITLE
Babel插件需Babel 7.x支持

### ISSUE THREAD

**Issue by dachaiyuan** [NervJS/taro#2181]
**问题描述**
我想使用babel的一个插件     @babel/plugin-proposal-optional-chaining
但是这个插件提示需要 babel-core  7.0.0 版本才能使用
我查看依赖关系，是webpack-runner 锁了babel-core

我应该怎么升级比较合理，不影响项目？

**期望行为**
如果无法升级，
希望什么时候能够支持babel7.x  ？

**Comment by yuche** [comment]
如果你的 target 是小程序的话，我想了一下的确是没有什么很好的办法接入 babel 7。

@babel/plugin-proposal-optional-chaining 这个插件在 babel 7 之后才有的功能，没有 babel 6 版本。而如果单单加一层 babel 7 转换也不行，因为有些 babel 插件一定会把 babel 代码转换掉，而不是像 babylon(@babel/parser) 那样可以把 AST 抽出来。

因此这个功能只能等待官方升级了。

**Comment by caigehui** [comment]
极度需要可选链的plugin，这对代码质量的提升不是一点半点

**Comment by redblue9771** [comment]
感觉在用假的TS，可选乱链总是自己补全，一保存，Taro却编译不过-。-

**Comment by shenghanqin** [comment]
3.0版本，这个问题解决了吗？ @yuche

**Comment by yuche** [comment]
> 3.0版本，这个问题解决了吗？ @yuche

当然

**Comment by shenghanqin** [comment]
@redblue9771 默默期待3.0吧，惊喜很多滴。哈哈

**Comment by redblue9771** [comment]
> @redblue9771 默默期待3.0吧，惊喜很多滴。哈哈

我选择原生

**Comment by CarolineQWE** [comment]
如果转换目标是h5呢，有没有希望兼容babel7

**Comment by d393911462** [comment]
3.0 有没有升级转换工具 ？

**Comment by Chen-jj** [comment]
@d393911462 升级工具还没完成，可以看文档手动升级

**Comment by Chen-jj** [comment]
Taro 3 已使用 babel7
