### ISSUE TITLE
小程序生命周期的方法onLoad，onShow等在其他方法内调用时没有转义成taro框架的对应的生命周期方法名

### ISSUE THREAD

**Issue by luodanyalian** [NervJS/taro#2183]
小程序生命周期的方法onLoad，onShow等在其他方法内调用时没有转义成componentWillMount这种的名字，比如下拉刷新的时候我就会调用这种方法

![image](https://user-images.githubusercontent.com/22935907/52848070-d015b280-3148-11e9-9b38-8c929a13ced2.png)

 System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm

 - 报错平台 [ weapp]

**Comment by yuche** [comment]
你是自己写的 onLoad 方法还是使用 taro convert 转换的？

**Comment by luodanyalian** [comment]
taro convert转换的

**Comment by luodanyalian** [comment]
> 你是自己写的 onLoad 方法还是使用 taro convert 转换的？

> taro convert转换的

**Comment by yuche** [comment]
那你要带上源码或者复现和你 taro 的版本

**Comment by luodanyalian** [comment]
源码：
```
/**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {
    // console.log(111);
    wx.showNavigationBarLoading();
    this.onLoad();
    this.onShow();
    wx.stopPullDownRefresh();
    wx.hideNavigationBarLoading();
  }
```
Taro v1.2.12
