### ISSUE TITLE
LoadComponent导致奔溃

### ISSUE THREAD

**Issue by fangkyi03** [NervJS/taro#2184]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
![image](https://user-images.githubusercontent.com/30390014/52862344-0a467a80-3170-11e9-971a-3a6f9eedfd33.png)
这个写法导致taro崩溃
**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]
[LoadingComponent.zip](https://github.com/NervJS/taro/files/2869568/LoadingComponent.zip)

```js
/* eslint-disable taro/no-jsx-in-class-method */
/* eslint-disable taro/render-props */
/* eslint-disable react/react-in-jsx-scope */
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Image } from '@tarojs/components'
import './index.scss'
import api from '../../command/api';
import { connect } from '@tarojs/redux';
import { AtButton, AtIcon } from 'taro-ui'
import LoadingComponent from '../../components/LoadingComponent';



@connect(({Index})=>({...Index}))
class Index extends Component {

  config = {
    navigationBarTitleText: '富川有机种植脐橙'
  }

  renderNormal = () =>{
    return (
      <View>

      </View>
    )
  }

  render () {
    debugger
    const {isShow} = this.props
    return (
      <LoadingComponent
        isShow={isShow}
        showView={this.renderNormal}
      />
    )
  }
}

export default Index

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
不报错 并且可以在页面isShow改变的时候才刷新showView
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]
👽 Taro v1.2.12

  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.0.3

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@fangkyi03 属性传递 JSX 的用法详见 [组合](https://nervjs.github.io/taro/docs/children.html#%E7%BB%84%E5%90%88)

**Comment by luckyadam** [comment]
@fangkyi03 同时当前版本还不支持在 render 方法之外定义 JSX
