### ISSUE TITLE
如果不用JSX,用什么

### ISSUE THREAD

**Issue by zaoqi-unsafe** [NervJS/taro#2187]
未找到相关文档。
eval好像不能直接支持JSX。
我在实现一个编程语言的javascript解释器，欲用这个库实现GUI

**Comment by yuche** [comment]
如果不用 JSX 就没有办法在各小程序端使用 taro，在小程序端使用 taro 意味着你必须使用 taro cli 工具配合 taro 运行时库一起才能运行。

**Comment by zaoqi-unsafe** [comment]
不用JSX不意味着不使用 taro cli 工具配合 taro 运行时库。

是JSX不是taro的语法糖，不像React*一样能用某些函数代替吗？

**Comment by zaoqi-unsafe** [comment]
@yuche 
taro的JSX不是语法糖吗？

**Comment by yuche** [comment]
JSX 在 Taro 中是用来转换为 wxml 的标识符，不像 React 是 createElement 的语法糖。
