### ISSUE TITLE
Taro中调用微信小程序原生API，vscode找不到变量的问题。

### ISSUE THREAD

**Issue by YanceyOfficial** [NervJS/taro#2190]
Taro尚未实现微信小程序云开发的接口，也就是 `Taro.cloud.callFunction({ ... })` ，现在只能通过`wx.cloud.callFunction({ ... })`，怎样解决vscode报 **Cannot find name 'wx'.** 的问题？（虽然现在不影响程序的正常使用）

**Comment by yuche** [comment]
在 global.d.ts:
declare var wx: any;

**Comment by YanceyOfficial** [comment]
已解决，感谢。
