### ISSUE TITLE
cli从V1.2.1升级v1.2.13报错

### ISSUE THREAD

**Issue by DuanShuaiShuai** [NervJS/taro#2192]
**问题描述**
cli从V1.2.1升级v1.2.13报错

**复现步骤**
[复现问题的步骤]
1. taro update self  升级cli
2. taro update project 升级相关依赖
3. npm  run dev:swan
```js
λ npm run dev:swan

> m-web-taro@1.0.0 dev:swan D:\project\m-web-taro
> npm run build:swan  -- --watch


> m-web-taro@1.0.0 build:swan D:\project\m-web-taro
> taro build --type swan "--watch"

👽 Taro v1.2.13

开始编译项目 taro-app
输入类型错误，目前只支持 weapp/h5/rn/swan/alipay/tt 六端类型
```

**期望行为**
编译正常

**报错信息**

目前只支持 weapp/h5/rn/swan/alipay/tt 六端类型

**系统信息**
👽 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by DuanShuaiShuai** [comment]
我在cli build.js,打印了两行console.log
`function build(args, buildConfig) {
  console.log(buildConfig, '++++++++++++++++')
  const { type, watch } = buildConfig
  const outputPath = path.join(appPath, configDir.outputRoot || CONFIG.OUTPUT_DIR)
  if (!fs.existsSync(outputPath)) {
    fs.mkdirSync(outputPath)
  } else {
    if (type !== Util.BUILD_TYPES.H5) {
      Util.emptyDirectory(outputPath)
    }
  }
  console.log(type, '++++++++++++++++')
  switch (type) {
    case Util.BUILD_TYPES.H5:
      buildForH5({ watch })
      break
    case Util.BUILD_TYPES.WEAPP:
      buildForWeapp({ watch })
      break
    case Util.BUILD_TYPES.SWAN:
      buildForSwan({ watch })
      break
    case Util.BUILD_TYPES.ALIPAY:
      buildForAlipay({ watch })
      break
    case Util.BUILD_TYPES.TT:
      buildForTt({ watch })
      break
    case Util.BUILD_TYPES.RN:
      buildForRN({ watch })
      break
    case Util.BUILD_TYPES.UI:
      buildForUILibrary({ watch })
      break
    default:
      console.log(chalk.red('输入类型错误，目前只支持 weapp/h5/rn/swan/alipay/tt 六端类型'))
  }
}`

结果`
λ npm run dev:swan

> m-web-taro@1.0.0 dev:swan D:\project\m-web-taro
> npm run build:swan  -- --watch


> m-web-taro@1.0.0 build:swan D:\project\m-web-taro
> taro build --type swan "--watch"

👽 Taro v1.2.13

开始编译项目 taro-app
{ type: undefined, watch: undefined } '++++++++++++++++'
undefined '++++++++++++++++'
输入类型错误，目前只支持 weapp/h5/rn/swan/alipay/tt 六端类型`

**Comment by guozimo** [comment]
DuanShuaiShuai    企信宝开发者 请加我微信 谢谢 微信号：gwd1991
