### ISSUE TITLE
从小程序编译到h5 ,`onTap`不支持？

### ISSUE THREAD

**Issue by ChandlerVer5** [NervJS/taro#2198]
**问题描述**
编译为h5时，`onTap={this.handleItemTap}`无法响应。

**复现步骤**
就是简单的事件绑定：`onTap={this.handleItemTap}`
```js
onTap={this.handleItemTap}
```

**期望行为**
在编译为h5时，可以转换为click

**报错信息**

点击没有任何消息

**系统信息**
λ taro info
� Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.0 - D:\Applications\Scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 1.13.0 - D:\Applications\Scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\Applications\Scoop\apps\nvm\current\nodejs\nodejs\npm.CMD

**补充信息**
`onTap={this.handleItemTap}`,换成 `onClick`就行了
编译到h5时，没有考虑到`onTap`?

**Comment by yuche** [comment]
用 `onClick`

**Comment by ChandlerVer5** [comment]
好快啊，哈哈哈哈吗，但是我每个都需要改，在cli端不能方便实现吗？

**Comment by yuche** [comment]
不能，这个我们在文档就有说明 tap 就是 click，你可以自己写一个简单的正则批量替换
