### ISSUE TITLE
请问iPhone x 怎么适配呢

### ISSUE THREAD

**Issue by z704600202qj** [NervJS/taro#2200]
请问iPhone x 怎么适配呢
特别是底部按钮部分，
![image](https://user-images.githubusercontent.com/23369361/52935587-c2546d00-3394-11e9-91ca-9fd84470893e.png)
希望是
![image](https://user-images.githubusercontent.com/23369361/52935605-d0a28900-3394-11e9-8331-2df34f05717a.png)

**Comment by yuche** [comment]
在 Taro 中做这样的样式适配和在对应容器中适配没有任何分别，你可以通过在搜索引擎输入并回车「如何适配 iPhone x」找到答案。
