### ISSUE TITLE
先写Image标签，再写一个View标签，两个元素之间产生了10px左右的间隔

### ISSUE THREAD

**Issue by JohnsenZhou** [NervJS/taro#2201]
**问题描述**
先写一个Image标签，随后写一个View标签，这两个标签之间正常情况下不应该存在间隔，但是程序跑起来后能看到大约10px的间隔，在代码中找不出可疑的点

**复现步骤**
如下代码

```js
<View className='card'>
      <Image className='banner'></Image>
      <View className='card-title'>Test</View>
</View>
```

**期望行为**
Image标签和View标签之间没有间隔

**报错信息**
Image标签和View标签之间存在间隔，如下图：
![](https://qnm.hunliji.com/o_1d3vqq3qv1cag8ai1luhcm81c2jb.png)
![](https://qnm.hunliji.com/o_1d3vqq3qv192bptgpek1ct8ncvc.png)
![](https://qnm.hunliji.com/o_1d3vqq3qv2tg14ob1f83re2aphd.png)

**系统信息**
 - 操作系统: [macOS Sierra 10.12.6]
 - Taro 版本 [1.2.12]
 - Node.js 版本 [10.14.2]
 - 报错平台 [weapp]

**Comment by magicbing** [comment]
Image 加一个 display: block;
