### ISSUE TITLE
支付宝小程序中多个服务并发调用时 Taro.hideLoading()无效

### ISSUE THREAD

**Issue by dsitn201703** [NervJS/taro#2202]
**问题描述：**
使用Taro.showLoading({title:'加载中',mask:true}); 和 Taro.hideLoading(); 配合dva-loading
处理页面加载显示loading的问题。但是当多个调用服务并发时，发现支付宝中的loading一直显示，实际上服务数据已经加载完成。在H5和微信小程序中是正常的，支付宝中有问题。
**期望行为：**
当服务数据加载完成时loading可以自行关闭。
**系统信息：**
* 操作系统: [Windows 10]
* Taro 版本 [ v.1.2.4]
* Node.js 版本 [v8.12.0]
* 报错平台 [alipay]

**Comment by Chen-jj** [comment]
@dsitn201703 可以使用支付宝原生 API `my.showLoading` 与 `my.hideLoading` 调试一下，判断是 Taro 还是支付宝的问题。
