### ISSUE TITLE
RN 端的 Taro.pxTransform 需要在任何地方都可使用，以便实现响应式设计

### ISSUE THREAD

**Issue by js-newbee** [NervJS/taro#2204]
**问题描述**

RN 端的 Taro.pxTransform 不支持在 class 之外使用

**复现步骤**
```js
const WRAP = {
  height: Taro.pxTransform(10)
}

export default class extends Component {
  render() {
    return <View style={WRAP}>
  }
}
```

**期望行为**
包含 Taro.pxTransform 的样式可写在 class 外

**报错信息**

undefined is not an object (evaluating '_config.designWidth')

**系统信息**
Taro v1.2.13

**补充信息**
这个是由于 Taro.initPxTransform() 晚于变量初始化，导致报错。
虽然说把样式挪到 class 内就正常了，但这个行为也导致了 RN 上不能很方便的实现响应式设计。

目前样式文件会被编译到单独的 js 文件中，
``` js
StyleSheet.create({
  "wrap": {
    "height": 100
  }
})
```

样式单位转成数字的话就没法适配屏幕了，如果要实现 RN 响应式设计，其实只要编译时输出 "height": Taro.initPxTransform(100) 就完事了
但由于 Taro.initPxTransform() 也晚于 StyleSheet.create()，所以这个方案就不可行了

而目前用 Taro 开发 RN 也没看到其他合适的响应式方案？只能靠声明 style 属性在运行时去处理就太麻烦了

因此，需要把 Taro.initPxTransform() 提前，在任何地方都可用，或是有其他响应式设计思路？

**Comment by Pines-Cheng** [comment]
有点难搞，正在搞。

**Comment by Pines-Cheng** [comment]
8ffbc3161a0affef66538cd65be2807d640e206d

**Comment by Pines-Cheng** [comment]
响应式设计已独立支持，单位在编译后会被 scalePx2dp 函数包裹起来，根据设备尺寸计算。
