### ISSUE TITLE
build完H5后在部分手机上面报call方法undefined,  是有什么包没引入?? 请求帮助

### ISSUE THREAD

**Issue by pollux2015** [NervJS/taro#2206]
**问题描述**
build完H5后在手机上面报call方法undefined, 是缺少什么包?  请求大佬帮助
  e[n].call(r.exports, r, r.exports, __webpack_require__) 

![image](https://user-images.githubusercontent.com/11935278/52949560-97c7db80-33b7-11e9-900e-127fc14ba966.png)

**系统信息**
 - 操作系统: [Android]
 - Taro 版本 [1.2.84]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5]

**Comment by Littly** [comment]
有复现代码吗？

**Comment by pollux2015** [comment]
在webview里面调试也不是很方便,  也许就是这个问题.  #1855
![image](https://user-images.githubusercontent.com/11935278/52991554-1ff5c180-3448-11e9-954d-692388a069f2.png)

**Comment by Littly** [comment]
> 在webview里面调试也不是很方便, 也许就是这个问题. #1855
> ![image](https://user-images.githubusercontent.com/11935278/52991554-1ff5c180-3448-11e9-954d-692388a069f2.png)

加入这个babel插件就ok了吗？

**Comment by pollux2015** [comment]
> > 在webview里面调试也不是很方便, 也许就是这个问题. #1855
> > ![image](https://user-images.githubusercontent.com/11935278/52991554-1ff5c180-3448-11e9-954d-692388a069f2.png)
> 
> 加入这个babel插件就ok了吗？
只要加入这个就OK了

**Comment by Littly** [comment]
那应该就是代码里面用到object.assign了
