### ISSUE TITLE
自定义taro组件的静态图片资源小程序编译后图片引用地址缺少/npm，H5编译没有问题

### ISSUE THREAD

**Issue by guozefei** [NervJS/taro#2208]
**问题描述**
自定义taro组件的静态图片资源小程序编译后图片引用地址缺少/npm，H5编译没有问题

**复现步骤**
写了一个自定义taro组件，里面有用到三张静态图片，在本地调试引用正常，node_modules里也引用正常，但是npm run dev:weapp 后 dist中 npm里的静态图片的引用地址缺少顶层/npm目录，导致图片资源无法找到

![default](https://user-images.githubusercontent.com/6120426/52985363-7eae4180-342e-11e9-9776-2d56c1460d51.PNG)

```js
// 这里可以贴代码
import PlayIcon from '../../images/audio_play.svg'
import PauseIcon from '../../images/audio_pause.svg'
import ExpandIcon from '../../images/expand.svg'
```

**期望行为**
小程序编译后可以正常使用npm包的静态图片资源

**报错信息**

![default](https://user-images.githubusercontent.com/6120426/52985455-dea4e800-342e-11e9-9075-70831ef8206d.PNG)
把dist中的图片链接前面加上 /npm 小程序就可以找到对应图片

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 7
 - Taro 版本 1.2.8
 - Node.js 版本 8.11.2
 - 报错平台 weapp

**Comment by luckyadam** [comment]
静态资源在 npm 包里对吧

**Comment by guozefei** [comment]
是的 node_modules和dist/npm里都有对应的图片
![default](https://user-images.githubusercontent.com/6120426/52985994-36445300-3431-11e9-87cf-50342c24cbf1.PNG)
![default](https://user-images.githubusercontent.com/6120426/52986018-45c39c00-3431-11e9-9ba8-33cf589ff1e7.PNG)

**Comment by guozefei** [comment]
![default](https://user-images.githubusercontent.com/6120426/52986217-f893fa00-3431-11e9-8ba1-21a3beb63bd1.PNG)
这是npm/ynp-taro-audio-player/dist/weapp/components/audioPlyaer/audioPlayer.js里的图片引用 前面加上/npm就没有问题
