### ISSUE TITLE
能否实现组件与组件的映射功能

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#2212]
**问题描述**
希望有能力在代码里面实现 “源组件” 和 “目标组件” 的映射。

**期望行为**
举个例子。好比我们在app开发中会用到WebView组件。小程序、RN都有对应的组件去做渲染，但是H5没有这种能力的，所以我们希望在打开H5中使用WebView组件，实则渲染的是一个WebRedirect组件，用于提示用户“即将跳转到 http://xxxxx”。

在app.js中可以使用类似这样的实现：

```
import Taro from '@tarojs/taro'
import { WebView } from '@tarojs/components'
import WebRedirect from './components/WebRedirect'

if (process.env.TARO_ENV === 'h5') {
    Taro.componentMapping = {
        WebView: WebRedirect
    };
}

...
```

然后在具体组件中使用 `import { WebView } from '@tarojs/components'`，就自动换成WebRedirect组件

**系统信息**
👽 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by luckyadam** [comment]
其实可以转换一下思路
你可以创建一个 MyWebView 组件，如下

```js
import Taro, { Component } from '@tarojs/taro'
import { WebView } from '@tarojs/components'
import WebRedirect from './components/WebRedirect'

export default class MyWebView extends Component {
  render () {
    return (
      process.env.TARO_ENV === 'h5' ? <WebRedirect /> : <WebView />
    )
  }
}
```

然后对外统一使用 MyWebView 组件就行
