### ISSUE TITLE
Taro使用CSSModule，vscode报Cannot find module '...'，但能正常调用。

### ISSUE THREAD

**Issue by YanceyOfficial** [NervJS/taro#2213]
虽然 vscode 报错，但下面 `className={styles.xxx}` 是可以正常使用的，就是看着有点儿不爽。

![error](https://yancey-assets.oss-cn-beijing.aliyuncs.com/Jietu20190219-142504@2x.jpg)

**Comment by luckyadam** [comment]
你需要把 scss 文件生命成一个模块

```
declare module "*.scss";
```

**Comment by YanceyOfficial** [comment]
我在在根目录下的 global.d.ts 文件下已经声明了如下代码，也重启了vscode，但还是不行，我认为是webpack配的问题。

```
declare module "*.scss";

declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.module.scss' {
  const cla```
sses: { [key: string]: string };
  export default classes;
}

declare module '*.module.sass' {
  const classes: { [key: string]: string };
  export default classes;
}
```

**Comment by YanceyOfficial** [comment]
https://stackoverflow.com/questions/50879080/css-scss-code-module-not-found-in-vscode-using-relative-path

可以参照一下

**Comment by hamal-ho** [comment]
在global.d.ts删除
`import React from 'react';`
`declare global {
  namespace JSX {
      interface IntrinsicElements {
          'import': React.DetailedHTMLProps<React.EmbedHTMLAttributes<HTMLEmbedElement>, HTMLEmbedElement>
      }
  }
}`

**Comment by YanceyOfficial** [comment]
> 在global.d.ts删除
> `import React from 'react';`
> `declare global { namespace JSX { interface IntrinsicElements { 'import': React.DetailedHTMLProps<React.EmbedHTMLAttributes<HTMLEmbedElement>, HTMLEmbedElement> } } }`

我声明文件没这句啊。

**Comment by liyongning** [comment]
问题没有解决为什么就关闭了？
