### ISSUE TITLE
npm run build:alipay打包错误

### ISSUE THREAD

**Issue by xiao0502** [NervJS/taro#2214]
**问题描述**
taro开发支付宝小程序，UI框架路径为`src/components/mini-antui`。在开发环境下面，`npm run dev:alipay`能正常运行项目且不报错，用`npm run build:alipay`进行项目打包的时候，控制台提示警告，项目能跑起来，但是UI框架的弹窗组件样式被漏掉。

而且看到打包后的dist目录下面，UI框架`mini-antui`的弹窗组件的css样式文件，即`index.acss`没有拷贝过来。

[或者可以直接贴源代码，能贴文字就不要截图]

**期望行为**
手动把弹窗组件`modal`里面的`index.acss`样式拷贝到dist对应目录下面运行就好了，很奇怪。

**报错信息**

```js
(node:53486) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
(node:53486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. v.1.2.4]
 - Node.js 版本 [e.g. v8.9.4]
 - 报错平台 [支付宝小程序]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
是编译时没有处理到支付宝小程序组件依赖的东西
