### ISSUE TITLE
在使用decorator时报错 

### ISSUE THREAD

**Issue by TiamoJrZhang** [NervJS/taro#2216]
![image](https://user-images.githubusercontent.com/28380327/53002799-8985c800-3468-11e9-9790-1de8bb6464b6.png)
具体试验代码如下：
![qq 20190219170041](https://user-images.githubusercontent.com/28380327/53002568-e92fa380-3467-11e9-8705-e6ddc7791418.png)
![qq 20190219170139](https://user-images.githubusercontent.com/28380327/53002624-0a908f80-3468-11e9-88b3-0411a0a0b649.png)
代码放到react环境下正常运行，这是什么原因，麻烦大佬看下@luckyadam

**Comment by FEVZIAKSOY2018** [comment]
19 Şub 2019 Sal 12:06 tarihinde taro-bot[bot] <notifications@github.com>
şunu yazdı:

**Comment by yuche** [comment]
taro 目前还不支持劫持 render 函数的装饰器，你可以在 https://github.com/NervJS/taro/issues/1155 追踪这个特性的进展。

**Comment by yuche** [comment]
Duplicate of #1155

**Comment by TiamoJrZhang** [comment]
好的感谢

**Comment by TiamoJrZhang** [comment]
> Duplicate of #1155

好的感谢
