### ISSUE TITLE
编译配置的全局copy ignore未生效

### ISSUE THREAD

**Issue by nascentui** [NervJS/taro#2217]
**问题描述**
编译配置的全局copy ignore未生效

**复现步骤**
config 下index.js 
```js
  copy: {
    patterns: [
    ],
    options: {
      ignore: ['*.png', '*.jpg'] // 全局的 ignore
    }
  },

```

**期望行为**
配置生效

**报错信息**
![image](https://user-images.githubusercontent.com/40256175/53002893-bafe9380-3468-11e9-91a7-b4a4c048bb8b.png)

**系统信息**
👽 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
升级到 Taro2、3 应该 ok 了
