### ISSUE TITLE
渲染时===null  条件判断&多个return  问题

### ISSUE THREAD

**Issue by Sdoy** [NervJS/taro#222]
```
render() {
    const {tasks}=this.state;
    if(tasks===null){
      return <View className='page-body' />
    }

    return (
      <View className='page-body'>
        <Text>Hello world!</Text>
      </View>
    )
  }
```
![image](https://user-images.githubusercontent.com/10302939/42027101-7b027390-7afb-11e8-8314-0480b0e43aeb.png)

![v 0 m cd h ox om1lx d4](https://user-images.githubusercontent.com/10302939/42027147-97c7fc8e-7afb-11e8-92f4-c63998bd8797.jpg)

然后把===null跳转转化成!task
发现多个if语句会有问题

```
render() {
    const {tasks} = this.state;
    if (!tasks) {
      return <View className='page-body' >
      </View>
    }

    if (tasks.length === 0) {
      return <View className='page-body'>
        <Text>{tasks.length}</Text>
      </View>
    }


    return (
      <View className='page-body'>
        <Text>Hello world!</Text>
      </View>
    )
  }
```
会转化成
![image](https://user-images.githubusercontent.com/10302939/42028236-4bd25312-7afe-11e8-9ef4-4cb3ea3732e7.png)
很明显,当task为null时,
tasks.length === 0就报错了

workaround: 第二个if判断改为else if
```
else if (tasks.length === 0) {
```
转化正确
![image](https://user-images.githubusercontent.com/10302939/42028334-93737f84-7afe-11e8-888d-284a6e7ff9a0.png)

**Comment by zacksleo** [comment]
这个目前可以这样写

```javascript
render() {
    const {tasks} = this.state;
    return tasks === null ? (
         <View className='page-body' />
    ) : (
        <View className='page-body'>
            <Text>Hello world!</Text>
       </View>
    );
  }
```

三目运算符是没有问题的

**Comment by Sdoy** [comment]
@zacksleo 

![image](https://user-images.githubusercontent.com/10302939/42028685-8be68030-7aff-11e8-8d46-84f390183de2.png)

**Comment by yuche** [comment]
`null` 的问题是为了处理有时候直接 `return null` 的情况，直接给他替换了一个 `<View />`。现在的处理太糙了点。

多个 return 的确是有问题，我想想怎么做才能符合语义。
