### ISSUE TITLE
一加3自带浏览器打开生成h5页面为空白页

### ISSUE THREAD

**Issue by tibic** [NervJS/taro#2220]
**问题描述**
网易严选的taro项目，在一加3自带浏览器打不开。

**复现步骤**

https://github.com/js-newbee/taro-yanxuan/issues/1

**期望行为**
浏览器正常显示

**报错信息**
window.onerror抓不到错误
componentWillMount里面打alert也进不来

**系统信息**
一加3内置浏览器

**补充信息**
初步怀疑taro框架问题，吃掉了报错信息。老铁抓紧找机器排查下吧

**Comment by Littly** [comment]
目前手头没有等于4... 可以给页面加个vconsole之类的调试下

**Comment by js-newbee** [comment]
@Littly 我有用了个云真机平台测了下一加3，在 <head> 中加了 vConsole、 eruda，没有任何提示，有点迷...

**Comment by Littly** [comment]
更新下，看看还存不存在这个问题？
