### ISSUE TITLE
taro开发微信小程序如何定义全局方法

### ISSUE THREAD

**Issue by StephenOo** [NervJS/taro#2223]
**问题描述**
taro在开发微信小程序的时候，如何定义全局的方法
**复现步骤**
[复现问题的步骤]
1. 在入口文件app.tsx定义方法，期望能够全局使用
2. 失败了

**期望行为**
如何在taro中定义全局方法

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [ v.1.2.13]
 - Node.js 版本 [e.g. v10.8.0]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@StephenOo 可以把方法挂在 Taro 对象上。

例如：

```js
// app.js
class App extends Component {
  componentWillMount () {
    Taro.hello = () => {
      console.log('hello')
    }
  }
}
```

```js
// index.js
export default class Index extends Component {
  componentDidMount () {
    Taro.hello()
  }
}
```

**Comment by Hideer** [comment]
@Chen-jj 你好挂载到tora 确实可以但是使用ts的话，ts的警告有解决方案么
