### ISSUE TITLE
npm run dev:h5 编译失败 You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by ctcx** [NervJS/taro#2224]
**问题描述**
第一次使用taro 和 taro-ui，打算开发微信小程序；有react 和 微信小程序原生开发经验；按照taro， taro-ui 官方教程使用，遇到问题后查阅了历史issues 并按照解决办法尝试，问题依旧。

**复现步骤**
```
1. cnpm install -g @tarojs/cli
2. taro init myApp
3. cd myApp
4. cnpm install taro-ui --save
5. npm run dev:h5
```

**config/index.js 已加入配置**
```js
h5: {
    publicPath: '/',
    staticDirectory: 'static',
    esnextModules: ['taro-ui'],
```
**app.scss 加入样式**
```
@import "~taro-ui/dist/style/index.scss";
```
**pages/index.js 加入代码**
```
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import { AtButton } from 'taro-ui'
import './index.scss'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <AtButton type='primary'>按钮文案</AtButton>
      </View>
    )
  }
}

```

**期望行为**
打开页面显示 按钮

**报错信息**
```创建  发现文件  src/app.js
创建  发现文件  src/app.scss
创建  发现文件  src/index.html
创建  发现文件  src/pages/index/index.js
创建  发现文件  src/pages/index/index.scss


ℹ️  Listening at http://127.0.0.1:10086/

监听文件修改中...

🙅   Failed to compile.

./node_modules/.2.0.0@taro-ui/dist/h5/components/countdown/index.js 105:11
Module parse failed: Unexpected token (105:11)
You may need an appropriate loader to handle this file type.
|     } = this.state;
| 
>     return <View className={classNames({
|       'at-countdown': true,
|       'at-countdown--card': isCard
```

**系统信息**
```taro info
👽 Taro v1.2.13
  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.13 => 1.2.13 
      @tarojs/plugin-babel: 1.2.13 => 1.2.13 
      @tarojs/plugin-csso: 1.2.13 => 1.2.13 
      @tarojs/plugin-sass: 1.2.13 => 1.2.13 
      @tarojs/plugin-uglifyjs: 1.2.13 => 1.2.13 
      @tarojs/router: 1.2.13 => 1.2.13 
      @tarojs/taro: 1.2.13 => 1.2.13 
      @tarojs/taro-alipay: 1.2.13 => 1.2.13 
      @tarojs/taro-h5: 1.2.13 => 1.2.13 
      @tarojs/taro-swan: 1.2.13 => 1.2.13 
      @tarojs/taro-tt: 1.2.13 => 1.2.13 
      @tarojs/taro-weapp: 1.2.13 => 1.2.13 
      @tarojs/webpack-runner: 1.2.13 => 1.2.13 
      eslint-config-taro: 1.2.13 => 1.2.13 
      eslint-plugin-taro: 1.2.13 => 1.2.13 
      nervjs: ^1.3.9 => 1.3.12 
    npmGlobalPackages:
      typescript: 3.1.5
```
 - Taro 版本 [v1.2.13]
 - Taro UI 版本 [v2.0.0]
 - 报错平台 [h5, weapp 无效果]

**Comment by Littly** [comment]
按照操作，没有复现你的问题喔

**Comment by Andyliwr** [comment]
遇到了相同的问题
![image](https://user-images.githubusercontent.com/12456160/53091746-bb248f00-354d-11e9-9942-4a80b3d1e76e.png)

**Comment by zhang14725804** [comment]
![_20190220212852](https://user-images.githubusercontent.com/15354910/53094905-5c174800-3556-11e9-9b85-3d4c4786456a.png)

**Comment by holin** [comment]
我也出现这个问题，找了两天了，最后发现是我系统里有一个 `~/.babelrc` 文件导致的，干掉这个文件，就能正常编译了。

**Comment by Littly** [comment]
> 我也出现这个问题，找了两天了，最后发现是我系统里有一个 `~/.babelrc` 文件导致的，干掉这个文件，就能正常编译了。

是否都是类似于这位老哥的情况？不是的话，需要提供一个能复现的仓库 不然完全没法debug

**Comment by wcmboy** [comment]
同样的问题

**Comment by zhang14725804** [comment]
1、首先检查config/index.js 是否已加入配置 esnextModules: ['taro-ui']
2、删掉.temp文件夹重新npm run dev
3、删除node_modules文件夹重新安装依赖

亲测有效

**Comment by wcmboy** [comment]
> 1、首先检查config/index.js 是否已加入配置 esnextModules: ['taro-ui']
> 2、删掉.temp文件夹重新npm run dev
> 3、删除node_modules文件夹重新安装依赖
> 
> 亲测有效

 esnextModules: ['taro-ui']  这个是加到config/index.js哪个位置？

**Comment by ctcx** [comment]
> > 1、首先检查config/index.js 是否已加入配置 esnextModules: ['taro-ui']
> > 2、删掉.temp文件夹重新npm run dev
> > 3、删除node_modules文件夹重新安装依赖
> > 亲测有效
> 
> esnextModules: ['taro-ui'] 这个是加到config/index.js哪个位置？

**config/index.js 已加入配置**

```js
h5: {
    publicPath: '/',
    staticDirectory: 'static',
    esnextModules: ['taro-ui'],
```

**Comment by Littly** [comment]
如果依然出现这种情况 那需要一个可以重现这种情况的仓库地址

**Comment by sananiki** [comment]
我测试了几台机器，两台出现这个情况，只有一台是好的

**Comment by sananiki** [comment]
> 如果依然出现这种情况 那需要一个可以重现这种情况的仓库地址

我用的taro-ui的官方仓库进行的测试，有两台机器win7,win server2008可以正常运行，还有一台win7,mac跑不起来，就报这个./node_modules/.2.0.0@taro-ui/dist/h5/components/countdown/index.js 105:11 错误

**Comment by ASeR1-ATG** [comment]
wat do u mean?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ASeR1-ATG** [comment]
so the mingw??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Littly** [comment]
> > 如果依然出现这种情况 那需要一个可以重现这种情况的仓库地址
> 
> 我用的taro-ui的官方仓库进行的测试，有两台机器win7,win server2008可以正常运行，还有一台win7,mac跑不起来，就报这个./node_modules/.2.0.0@taro-ui/dist/h5/components/countdown/index.js 105:11 错误

神奇了。你是用什么包管理器安装的？看你的报错日志，taro-ui的最终安装目录是`node_modules/.2.0.0@taro-ui`，`esnextModules`里面配`taro-ui`无法匹配到他。

**Comment by Littly** [comment]
> 遇到了相同的问题
> ![image](https://user-images.githubusercontent.com/12456160/53091746-bb248f00-354d-11e9-9942-4a80b3d1e76e.png)

应该是node模块的安装路径导致的。你用的是什么系统和包管理器？

**Comment by asreday** [comment]
改了上面的都还是上面的那个问题，无法编译打包H5

**Comment by asreday** [comment]
> > 遇到了相同的问题
> > ![image](https://user-images.githubusercontent.com/12456160/53091746-bb248f00-354d-11e9-9942-4a80b3d1e76e.png)
> 
> 应该是node模块的安装路径导致的。你用的是什么系统和包管理器？

我是用cnpm i -D taro-ui
版本2.0.2。

**Comment by asreday** [comment]
后面把taro回退到1.2.17后新建一个项目，把package.json复制过去，然后下taro-ui后就好，个人觉得的应该是@tarojs依赖包中的问题，先用1.2.17好了

**Comment by Littly** [comment]
翻了一下上面的评论，这个情况跟具体平台上npm依赖的安装位置有关。

受不同的包管理器影响，taro-ui会被安装在不同的目录下，有最普通的`taro-ui`，有`.2.0.0@taro-ui`，还有`_taro-ui@2.0.0@taro-ui`，这些不同的路径影响了`esnextModules`的匹配。

taro@1.2.20版本之后对匹配逻辑进行了修改，除了字符串匹配，也增加了正则表达式的匹配功能。如果发现配置了`esnextModules`后仍然出现`need an appropriate loader to handle....`的错误，不妨对照本地的安装路径，修改下配置再看看。
