### ISSUE TITLE
在h5中，浏览器控制台会报错Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by xinconan** [NervJS/taro#2225]
**问题描述**
在h5中，点击页面任何位置，浏览器控制台报错：
Unchecked runtime.lastError: The message port closed before a response was received.

**复现步骤**
```js
handleChange (target, e) {
    this.setState({
      [target]: e.target.value
    })
  }
...
// render
<View className='at-row at-row__align--center'>
          <View className='label'>输入</View>
          <View className='at-col'>
            <Input type='number' value={free} onChange={this.handleChange.bind(this, 'free')}></Input>
          </View>
        </View>

```

**期望行为**
没有报错

**报错信息**
Unchecked runtime.lastError: The message port closed before a response was received.

![image](https://user-images.githubusercontent.com/8479810/53076975-f31ada80-352b-11e9-93cc-506bfb77e77e.png)

虽然不影响页面，但看着还是挺难受的

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.2.13]
 - Node.js 版本 [v8.9.4]
 - 报错平台 [h5]

**Comment by Littly** [comment]
控制台报错信息往右边截多一点，看看报错的是哪个文件？

**Comment by xinconan** [comment]
@Littly 没有具体报错的文件
![image](https://user-images.githubusercontent.com/8479810/53221507-a4dd1700-36a4-11e9-914d-2c92c12efcb6.png)

**Comment by xinconan** [comment]
应该不是Taro的问题

**Comment by chaixuhong** [comment]
浏览器有道翻译插件的问题，将浏览器扩展程序关掉。
