### ISSUE TITLE
使用redux时，state中数据更新组件不会触发componentreceiveprops，组件不重新渲染

### ISSUE THREAD

**Issue by TiamoJrZhang** [NervJS/taro#2237]
使用redux时，state中数据更新组件不会触发componentreceiveprops，组件不重新渲染，具体情境下：
1.在使用官网redux demo时没有问题，但是此时redux state中的数据比较简单，为Int值，
2.在redux state中赋值复杂数据结构时，第一次state更新没有问题，第二次组件不会触发componentreceiveprops()，render函数不执行

具体代码如下：
![z_cfc qd5 4 6e7eo4 5k](https://user-images.githubusercontent.com/28380327/53165216-19647700-360d-11e9-8e8e-6c53305e763f.png)
![zo1 p36 x6b irclntx2ug](https://user-images.githubusercontent.com/28380327/53165217-19fd0d80-360d-11e9-80db-11bfbce7ce0e.png)
![85eo4flc2p2 5 o69 ak ms](https://user-images.githubusercontent.com/28380327/53165218-19fd0d80-360d-11e9-880e-f57aba28b3cf.png)

麻烦大佬看一下

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.13]
 - Node.js 版本 [e.g. v8.10.0]
 - 报错平台 [支付宝小程序，weapp]

**Comment by luckyadam** [comment]
对于复杂数据，比如数组，你应该先把数组浅拷贝一下，再发布出去，不要直接修改原数组

**Comment by TiamoJrZhang** [comment]
浅拷贝之后确实可以，能否请教一下大佬为何要做这一步操作，源数据是不可变数据吗

**Comment by luckyadam** [comment]
@TiamoJrZhang 是的，最好不要改变源数据

**Comment by TiamoJrZhang** [comment]
好的感谢
