### ISSUE TITLE
taro 已知bug总结

### ISSUE THREAD

**Issue by fangkyi03** [NervJS/taro#2238]
1.this.props中如果属性是new Set的通过redux刷新model的方式不能替换更新
2.render里面不能写return jsx
3.render中map 嵌套map 需要先声明变量
4.render中map不能写if语句
5.render中map不能写switch
6.element不支持...arg写法
7.不支持Component写法
8.image style属性不起作用

**Comment by yuche** [comment]
1. 这个需要我们重构 props 机制，因为微信会序列化所有 data，所以所有模板用到的数据都是 JSON
2. 你得附上代码
3. 你得附上代码
4. 在写测试用例，下个 patch 版本会有完整的支持
5. 同上
6. 和 1 一样，props 机制完成之后可以。但内置组件这个功能仍然不行，自定义组件可以实现。同样是微信的机制导致的，必须制定地传递每一个参数
7. 你得附上代码，我甚至不懂这句话是什么意思

**Comment by luckyadam** [comment]
请针对每一条问题附上相关代码，不然没人知道这个 issue 在讨论什么

**Comment by fangkyi03** [comment]
1.this.props中如果属性是new Set的通过redux刷新model的方式不能替换更新
2.render里面不能写return jsx
```js
renderTest() {
return (
    <View>
        sasa
    </View>
)
}
render(){
return this.renderTest()
}
```
3.render中map 嵌套map 需要先声明变量
```
    render(){
        return data.map((e)=>{
            return e.data.map((e)=>{
                return (
                    <View></View>
                )
            })
        })
    }
```
4.render中map不能写if语句
```js
render() {
    return data.map((e)=>{
        if (e.type == 0) {
            return <A/>
        }else {
            return <B/>
        }
    })
}
```
6.element不支持...arg写法
``` js
render(){
    return (
        <A {...arg}/>
    )
}
```
7.不支持Component写法
```
render(){
    const {Component} = this.props
    return (
        <Component/>
    )
}
```
8.image style属性不起作用 样式不生效
```js
render(){
    return (
        <Image style={{width:100,height:100}}/>
    )
}
```

**Comment by yuche** [comment]
4 你需要单独开 issue 做一个复现
7 这个写法你应该可以看文档 children 和组合
8 是因为你没有写单位

一般 github 的逻辑是这样的：你发现问题，这个问题在之前的 issue 没有存在过，然后你提出可以复现的代码，最后我们找时间修复这个问题通过 commit 关掉他。

你的所有问题应该都被回复了，如果没什么问题我就关了这个 issue。如果你觉得不满意的就单独的问题开 issue 做复现，确认存在问题就排期修复。
