### ISSUE TITLE
[H5端] 清除Cookie

### ISSUE THREAD

**Issue by mifanj** [NervJS/taro#2239]
期望增加H5端清除Cookie的功能

**Comment by luckyadam** [comment]
请具体描述下需求

**Comment by mifanj** [comment]
> 请具体描述下需求

项目中登录是依赖cookie的，注销就需要清空cookie，小程序端因为是自己存储的cookie所以能实现这个需求，但是h5端完全是依赖接口响应头中的setCookie，不清楚怎么自行清除cookie

**Comment by luckyadam** [comment]
H5 端清除 cookie 自己封装一个方法就可以了

**Comment by Littly** [comment]
封装下 在h5端直接让cookie过期就好了
