### ISSUE TITLE
Taro.request H5 端附加参数 cache 的二义性

### ISSUE THREAD

**Issue by finian** [NervJS/taro#224]
在 `jsonp` 模式下，取值类型为 `Boolean`，在非 `jsonp` 模式下，取值类型为 `String`。两种情况下，`cache` 参数代表的意义不一样，建议在 `jsonp` 模式下的 `cache` 使用 `jsonpCache` 代替，语义更明确

**Comment by luckyadam** [comment]
好建议~ 下个版本加上
