### ISSUE TITLE
大神，微信小程序支持自定义 tabbar 了，Taro支持吗现在

### ISSUE THREAD

**Issue by htf123** [NervJS/taro#2240]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by javahuang** [comment]
同求 @yuche @luckyadam 您好，请问有支持计划吗？

**Comment by htf123** [comment]
> @htf123 上午我开始也以为需要 taro 的额外支持来着，刚才看了下文档，很好集成。
> 
> * 首先参考官方示例，可以直接将 `custom-tab-bar` 目录拷贝到你项目的 src 下面，对应修改 `app.js` 的 tarBar 配置
> * taro 的 `config/index.js` 配置
> 
> ```
>  copy: {
>     patterns: [
>       { from: "src/custom-tab-bar/", to: "dist/custom-tab-bar/" }
>     ],
>     options: {}
>   }
> ```
> * 在对应的 pages 页面设置一下当前激活的 tarBar
> 
> ```js
> componentDidShow() {
>       this.$scope.getTabBar().setData({
>         selected: 1 // 当前页面对应的 index
>       })
>   }
> ```

**Comment by xzedx** [comment]
setData以后tabbar状态不生效

**Comment by zysndy** [comment]
可以试试这么写
```jsx
componentDidShow() {
    if (typeof this.$scope.getTabBar === 'function' &&
      this.$scope.getTabBar()) {
      this.$scope.getTabBar().$component.setState({
        selected: 1,
      })
    }
  }
```

**Comment by ouyangshan09** [comment]
@javahuang 以下代码并不会生效
```
componentDidShow() {
      this.$scope.getTabBar().setData({
        selected: 1 // 当前页面对应的 index
      })
  }
```

**Comment by ouyangshan09** [comment]
@zysndy 感谢，这个方法可以
```
componentDidShow() {
    if (typeof this.$scope.getTabBar === 'function' &&
      this.$scope.getTabBar()) {
      this.$scope.getTabBar().$component.setState({
        selected: 1,
      })
    }
  }
```

**Comment by RosApr** [comment]
@ouyangshan09 我用这个还是不行
```js 
if (
            typeof this.$scope.getTabBar === 'function'
            &&
            this.$scope.getTabBar()
        ) {
            this.$scope.getTabBar().setData({
                selected: 4,
            })
        }
```
这个可以

**Comment by shineSnow** [comment]
taro 3.x 版本 已经不支持 scope了，这个怎么搞？

**Comment by qiyulaoshi** [comment]
> taro 3.x 版本 已经不支持 scope了，这个怎么搞？

我也是这样，你得问题怎么解决的啊

**Comment by congyaqwq** [comment]
https://github.com/NervJS/taro/issues/7980#issuecomment-882021675
引用这位的，可以实现，vue版本在onShow事件中处理～

**Comment by dolphin0618** [comment]
> @htf123 上午我开始也以为需要 taro 的额外支持来着，刚才看了下文档，很好集成。
> 
> * 首先参考官方示例，可以直接将 `custom-tab-bar` 目录拷贝到你项目的 src 下面，对应修改 `app.js` 的 tarBar 配置
> * taro 的 `config/index.js` 配置
> 
> ```
>  copy: {
>     patterns: [
>       { from: "src/custom-tab-bar/", to: "dist/custom-tab-bar/" }
>     ],
>     options: {}
>   }
> ```
> 
> * 在对应的 pages 页面设置一下当前激活的 tarBar
> 
> ```js
> componentDidShow() {
>       this.$scope.getTabBar().setData({
>         selected: 1 // 当前页面对应的 index
>       })
>   }
> ```

文档在哪看的，找了半天taro的文档没看到自定义tabbar
