### ISSUE TITLE
原生小程序引用方式为绝对路径时，WX小程序转taro 报错

### ISSUE THREAD

**Issue by 8pig** [NervJS/taro#2242]
**问题描述**
微信小程序引用为绝对路径  转换成taro  安装依赖并运行 taro build --type weapp
一直提示   `缺少npm 包 util.js 开始安装`

**系统信息**

  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
 - 报错平台 wx

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
应该是不支持绝对路径引用

**Comment by shenghanqin** [comment]
需要更多源代码效果？
