### ISSUE TITLE
使用webpack require.context 报错

### ISSUE THREAD

**Issue by MorisHarA** [NervJS/taro#2243]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
使用webpack require.context 报错

[或者可以直接贴源代码，能贴文字就不要截图]

```js
import { combineReducers } from 'redux'

const context = require.context('./', false, /\.js$/);
const keys = context.keys().filter(item => item !== './index.js');
const reducers = keys.reduce((memo, key) => ({ ...memo, [key.match(/([^/]+)\.js$/)[1]]: context(key).default }), {});

export default combineReducers(reducers);

```

**期望行为**
希望可以通过这种方式统一引入reducer

**报错信息**
require.context is not a function

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS High Sierra 10.13.6]
 - Taro 版本 [v1.2.13]
 - Node.js 版本 [v10.8.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
小程序端编译没有使用 webpack，所以不支持 require.context
