### ISSUE TITLE
css/sass module 自动更新问题

### ISSUE THREAD

**Issue by YanceyOfficial** [NervJS/taro#2244]
当使用样式模块化，改动css或scss的代码时，只会生成新的 ***.wxss，而相应的 ***.wxml并不更新，因此样式修改无法实时反馈，现在只能被动刷一下相应的 ***.jsx 或 ***.tsx

**Comment by YanceyOfficial** [comment]
有时候也没问题，不过大部分情况无法实时反馈。

**Comment by luckyadam** [comment]
确实存在问题，在 #1388 跟踪解决进度吧

**Comment by YanceyOfficial** [comment]
好的，辛苦。

**Comment by wsyxl365** [comment]
暂时的做法你可以修改对应jsx文件中的文字 保存重新编译下 这样你新增加的css module的类名可能就出来了
