### ISSUE TITLE
taro.request 在百度小程序调用时，入参处理结果与微信小程序，h5不一致

### ISSUE THREAD

**Issue by liveKang** [NervJS/taro#2246]
**问题描述**

taro.request 在百度小程序调用时，入参处理结果与微信小程序，h5不一致。

**复现步骤**

微信小程序入参：
```
jsonData:{"data":{"name":"abc","no":"123"}}
```

h5模式入参：
```js
jsonData={"data":{"name":"abc","no":"123"}}
```

百度小程序入参：
```js
"jsonData:{\"data\":{\"name\":\"abc\",\"no\":\"123\"}}"
```

请求函数如下：
```js
export function post(url, data, success, fail) {
	const options = {
		method: 'post',
		headers: {
			'content-type': 'application/x-www-form-urlencoded;charset=utf-8'
		},
		body: `jsonData=${JSON.stringify({ data: data })}`
	}
	return request(url, options, success, fail)
}

function request(url, options, success = () => {}, fail = () => {}) {
	const { method, headers, body } = options
	const params = {
		url: url,
		data: body,
		method: method,
		header: headers,
		success: success,
		fail: fail
	}
	return Taro.request(params)
		.then(response => {
			if (response.statusCode === 200) {
				if (response.data && response.data.code === '200') {
					success(response.data.data)
				} else {
					// 对业务错误码进行处理
				}
				return response.data.data
			} else {
				// 对 http 错误码进行处理
			}
		})
		.catch(err => {
			if (err) {
				fail()
			}
		})
}
```

**期望行为**

期望处理结果与微信小程序，h5保持一致

**报错信息**

微信小程序截图：
![image](https://user-images.githubusercontent.com/15951791/53226223-64d26000-36b5-11e9-8792-a731d17a7f29.png)

百度小程序截图：
![image](https://user-images.githubusercontent.com/15951791/53227098-2c805100-36b8-11e9-8136-71a9c70e3c83.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS High Sierra 10.13.6
 - Taro 版本 v1.2.4
 - Node.js 版本 10.15.0
 - 报错平台 百度小程序

**补充信息**
[可选]

可能的原因：百度小程序 `swan.request` 中 data 字段对 string 类型进行了重复的 `JSON.stringify()`操作。

**Comment by jinjinjin0731** [comment]
百度小程序中，调用是原生方法，即  swan.request  。按百度文档所述
`
data 数据说明：

最终发送给服务器的数据都是 String 类型，如果传入的 data 不是 String 类型，会被转换成 String 。转换规则如下：
1、对于 GET 方法的数据，会将数据转换成 query string（encodeURIComponent(k)=encodeURIComponent(v)&encodeURIComponent(k)=encodeURIComponent(v)…）；
2、对于 POST 方法且 header[‘content-type’] 为 application/json 的数据，会对数据进行 JSON 序列化；
3、对于 POST 方法且 header[‘content-type’] 为 application/x-www-form-urlencoded 的数据，会将数据转换成 query string （encodeURIComponent(k)=encodeURIComponent(v)&encodeURIComponent(k)=encodeURIComponent(v)…）。
`
 这里需要后台去处理了。
[百度小程序文档](https://smartprogram.baidu.com/docs/develop/api/net_request/#request/)

**Comment by liveKang** [comment]
多端统一的话，通过后台来抹平差异不太合理。我去验证下是否是`swan.request`的问题。

**Comment by jinjinjin0731** [comment]
@liveKang  这个百度官方是这样的，我们这也没办法。 你可以看我上面回复的文档地址，官方文档已经写明是这样的。除非官方改，不然也没有别的办法
