### ISSUE TITLE
h5开发模式下，config/index.js  的publicPath不能设置为'./'，会导致app.js 返回index.html内容

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#2249]
![bug](https://user-images.githubusercontent.com/13210798/53288192-badffa00-37c0-11e9-871b-2425be1b7eb5.png)

**Comment by kucy** [comment]
![bug2](https://user-images.githubusercontent.com/13210798/53288260-507b8980-37c1-11e9-837f-dea9f17b467f.png)

**Comment by Littly** [comment]
dev 模式下不应该使用相对路径作为 publicPath
devServer 的 publicPath 应该以“/”开头并且以“/”结尾
https://webpack.js.org/configuration/dev-server/#devserverpublicpath-

**Comment by iamwjj** [comment]
> dev 模式下不应该使用相对路径作为 publicPath
> devServer 的 publicPath 应该以“/”开头并且以“/”结尾
> https://webpack.js.org/configuration/dev-server/#devserverpublicpath-

不支持相对路径，那本地想通过nginx配置在其他域名下面来开发就不行了。。
