### ISSUE TITLE
computeMatch customRoutes find error

### ISSUE THREAD

**Issue by AMDvsTMD** [NervJS/taro#2250]
**问题描述**
[问题描述：computeMatch 不正确导致找不到路由信息]

**复现步骤**

```js
// 这里可以贴代码
  computeMatch (location: Types.Location): Types.RouteObj {
    // 找出匹配的路由组件
    const originalPathname = location.path;
    let pathname = originalPathname
    const foundRoute = this.customRoutes.find(([originalRoute, mappedRoute]) => {
      return originalPathname === mappedRoute
    })
    if (foundRoute) {
      pathname = foundRoute[0]
    }
    const matchedRoute = this.props.routes.find(({path, isIndex}) => {
      if (isIndex && pathname === '/') return true;
      return pathname === path;
    })

    invariant(matchedRoute, `Can not find proper registered route for '${pathname}'`)

    return matchedRoute!
  }
```
**期望行为**
should be return originalPathname === originalRoute
and 
    if (foundRoute) {
      pathname = foundRoute[1]
    }

**报错信息**
![image](https://user-images.githubusercontent.com/9191690/53296968-0a6e0680-3851-11e9-8d04-5a9ed697f7e3.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro v1.2.0-beta.14

 - 操作系统: [ Windows 10]
 - Taro 版本 [v1.2.0-beta.14]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Littly** [comment]
先把taro相关的依赖包都更新到最新再试试看
