### ISSUE TITLE
Picker组件在H5中选中值状态没有与小程序保持一致

### ISSUE THREAD

**Issue by WQone** [NervJS/taro#2253]
**问题描述**
Picker组件在H5中选中值状态没有与小程序保持一致

**复现步骤**
使用的代码为官网示例

```js
state = {
    selector: ['美国', '中国', '巴西', '日本'],
    selectorChecked: '美国',
  };

  onChange = (e) => {
    this.setState({
      selectorChecked: this.state.selector[e.detail.value],
    });
  };

  render() {
    return (
      <View className="container">
        <View className="page-body">
          <View className="page-section">
            <Text>地区选择器</Text>
            <View>
              <Picker mode="selector" range={this.state.selector} onChange={this.onChange}>
                <View className="picker">当前选择：{this.state.selectorChecked}</View>
              </Picker>
            </View>
          </View>
        </View>
      </View>
    );
  }

```

**期望行为**
Picker组件在H5中对于选中的当前状态可以与小程序端表现一致

**报错信息**
H5端：选中后再展开选中值依然保持在0的位置
![dfcdsf2](https://user-images.githubusercontent.com/25738656/53313060-8cfad280-38f2-11e9-9496-8db585c83fae.gif)

小程序端：正常
![dfcdsf1](https://user-images.githubusercontent.com/25738656/53312949-2f668600-38f2-11e9-8079-aa2ffc3522ec.gif)

**系统信息**
 Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by jinjinjin0731** [comment]
请问你的 taro 是什么版本？ 这个问题已经在之前已经修复过了

**Comment by WQone** [comment]
@jinjinjin0731 v1.2.13
