### ISSUE TITLE
app.js 里面的tabBar对象的list 可以动态传入吗？

### ISSUE THREAD

**Issue by soymikey** [NervJS/taro#2254]
我试过把list的数组赋值给customList然后动态传入，但是console里面报错。  

customList=[{
        pagePath: "pages/home/home",
        text: "首页",
        iconPath: "./icons/home.png",
        selectedIconPath: "./icons/home-actived.png"
      }, {
        pagePath: "pages/goodsPublish/goodsPublish",
        text: "商品发布",
        iconPath: "./icons/box.png",
        selectedIconPath: "./icons/box-actived.png"
      }, {
        pagePath: "pages/supplyDemandPublish/supplyDemandPublish",
        text: "供求发布",
        iconPath: "./icons/publish.png",
        selectedIconPath: "./icons/publish-actived.png"
      }
        , {
        pagePath: "pages/mySupplyDemand/mySupplyDemand",
        text: "我的供求",
        iconPath: "./icons/menu.png",
        selectedIconPath: "./icons/menu-actived.png"
      }
        , {
        pagePath: "pages/myNeeds/myNeeds",
        text: "我的需求",
        iconPath: "./icons/needs.png",
        selectedIconPath: "./icons/needs-actived.png"
      }
      ]  

//-----------------------------
tabBar: {
      list:,this.customList, // 这里出错
      color: '#333',
      selectedColor: '#FF7142',
      backgroundColor: '#fff',
      borderStyle: 'black'
    }

**Comment by luckyadam** [comment]
不可以哦，这个要在编译时处理，写死吧
