### ISSUE TITLE
ScrollView中onScrollToLower上的参数跟onScroll公用吗

### ISSUE THREAD

**Issue by Yeyc** [NervJS/taro#2263]
**问题描述**
ScrollView中onScrollToLower上的参数跟onScroll公用吗

**复现步骤**
[复现问题的步骤]
1. <ScrollView scrollTop={ScrollViewTop} onScroll={this.onScroll} onScrollToLower={this.ScrollToLower.bind(this,'start0On','start0',0,'tabList0')} style={dargStyle} scrollWithAnimation>
2. onScroll(e) {
 console.log(e)   // 输出start0On
}

[或者可以直接贴源代码，能贴文字就不要截图]

```js
<ScrollView scrollTop={ScrollViewTop} onScroll={this.onScroll} onScrollToLower={this.ScrollToLower.bind(this,'start0On','start0',0,'tabList0')} style={dargStyle} scrollWithAnimation>
onScroll(e) {
 console.log(e)   // 输出start0On
}

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [微信小程序]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
内置组件的函数和对应容器的函数是完全一样的，你可以看微信的文档找到答案:
https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html
