### ISSUE TITLE
转为微信小程序自定义组件children插入两次

### ISSUE THREAD

**Issue by krysiyi** [NervJS/taro#2265]
**问题描述**
自定义组件使用children，插入了两次

**复现步骤**
自定义组件内容：
`<View className={styles.modal} onClick={this.handleChange} data-flag='mh'>
 <View className={styles.box}> 
 {this.props.children} 
</View>
</View>`

**期望行为**
只在this.props.children位置插入一次

**报错信息**
![2hgu650a0il 2h pd9d 2g](https://user-images.githubusercontent.com/42768069/53390416-0b787280-39ce-11e9-81e1-5565d994d346.png)
正确位置插入了一次
但在组件内部又插入了一次
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2
      npm: 6.4.1 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
看一下你编译出来的 wxml 对不对，如果对的话就是小程序容器的问题了

**Comment by krysiyi** [comment]
> 看一下你编译出来的wxml对不对，如果对的话就是小程序容器的问题了

是对的，两部分一样，现在就是下面多插入的部分盖在上面了，导致我事件判断出错

**Comment by yuche** [comment]
如果编译出来的 wxml 是符合你的预期，那你应该把这个 bug 向小程序容器厂商报告，你遇到问题的应该是微信？
