### ISSUE TITLE
mobx array change not running component render.

### ISSUE THREAD

**Issue by gray-wen** [NervJS/taro#2266]
`class CounterStore {`
  `@observable counter = 0;`
  `@observable testArray = [{ a: 1 }, { a: 2 }];`
  `@observable testArray2 = [{ a: 1 }, { a: 2 }];`
  `counterStore() {`
    `this.counter++`
  `}`
  `increment() {`
   ` this.counter++;`
    `this.testArray.map(x => { x.a++; return x; });`
   ` this.testArray2.map(x => { x.a++; return x; });`
    `console.log(this.testArray, this.testArray2);`
 ` }`
`}`

`render() {`
    `const { counterStore: { counter, testArray, testArray2 } } = this.props;`
`<View className="index-page">`
        `<View>传给了子组件</View>`
       ` {`
        `  testArray.map((x, index) => {`
          `  return <TestChild key={index} test={x}></TestChild>`
         ` })`
      `  }`
        `<Button className="btn-bubble" onClick={this.increment}>+</Button>`
      `  <Button onClick={this.decrement}>-</Button>`
       ` <Button onClick={this.incrementAsync}>Add Async</Button>`
        `<Text>{counter}</Text>`
        `<View>在当前组件</View>`
       ` {`
        `  testArray2.map((x, index) => {`
          `  return <View key={index}>{x.a}</View>`
       `   })`
       ` }`
      `</View>`
`}`

Question:
ObservableArray value changed . page value not change and component not re-run render function

 Taro CLI 1.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

Code:
[taro-dome.zip](https://github.com/NervJS/taro/files/2908343/taro-dome.zip)

**Comment by nanjingboy** [comment]
@gray-wen mobx 是 4.x 吗？如果是 4.x 的话，数组 map 的时候要先 slice 下，具体原因参见 https://mobx.js.org/ 

<img width="812" alt="2019-02-27 10 57 43" src="https://user-images.githubusercontent.com/1390888/53462324-67023900-3a7e-11e9-8592-0e6172861a13.png">

**Comment by gray-wen** [comment]
> @gray-wen mobx 是 4.x 吗？如果是 4.x 的话，数组 map 的时候要先 slice 下，具体原因参见 https://mobx.js.org/
> 
> <img alt="2019-02-27 10 57 43" width="812" src="https://user-images.githubusercontent.com/1390888/53462324-67023900-3a7e-11e9-8592-0e6172861a13.png">

**Comment by gray-wen** [comment]
确实是这个问题 感谢。

**Comment by chankamlam** [comment]
[看这里](https://github.com/NervJS/taro/issues/2358#issuecomment-483685837)
