### ISSUE TITLE
不能找到定义的事件？

### ISSUE THREAD

**Issue by wzxm** [NervJS/taro#227]
![image](https://user-images.githubusercontent.com/13127730/42038942-c52f9948-7b1e-11e8-9e18-8b827ee5b06a.png)
![image](https://user-images.githubusercontent.com/13127730/42038960-d0790f00-7b1e-11e8-8d5c-075cdbb21e9d.png)

在组件中定义了一个方法，可是绑定onClick事件的时候，找不到这个方法？

**Comment by luckyadam** [comment]
你好，你的 taro 版本是多少呢
这个组件是怎么被引用的呢

**Comment by wzxm** [comment]
![image](https://user-images.githubusercontent.com/13127730/42070292-43749dee-7b88-11e8-8843-2c1fd5f218ce.png)
![image](https://user-images.githubusercontent.com/13127730/42070302-4cddee94-7b88-11e8-91fd-e9cea73cda83.png)

这是Taro版本和调用方法。

**Comment by yuche** [comment]
close via v.0.0.60
