### ISSUE TITLE
Page需要一个componentWillHide方法

### ISSUE THREAD

**Issue by 349989153** [NervJS/taro#2273]
**这不是一个bug，更像是建议或请求帮助**

Page能不能有一个componentWillHide方法，当该Page display:none的时候触发。

现在在h5下，从Page A导航到Page B的时候，Page A的componentWillUnmount是不会触发的，因为Page A并没有销毁，只是display:none。

请问如何处理这种情况?

**Comment by 349989153** [comment]
在Taro.Component上发现了componentDidHide生命周期，但尝试调了似乎没起作用。

**Comment by luckyadam** [comment]
componentDidHide 不会触发么

**Comment by 349989153** [comment]
sorry回复迟了，**h5下不会触发, 小程序端没试**。taro版本1.2.13。

复现过程：制造一个页面跳转流程：page A => page B => page C
并且在page B 中写：
```
componentWillUnmount() {
    alert('Unmount')
 }

  componentDidHide() {
    alert('hide')
  }
```
当page B跳到（navigateTo）page C时，都不显示。

当page B跳回（navigateBack）page A时，只显示"Unmount"。

**结论：componentDidHide在h5上无效。**

**Comment by luckyadam** [comment]
当 C 跳回到 B 时，才会触发 B 的 componentDidHide

**Comment by 349989153** [comment]
@luckyadam 请看我上面的描述，h5上componentDidHide都不触发。

**Comment by Littly** [comment]
> sorry回复迟了，**h5下不会触发, 小程序端没试**。taro版本1.2.13。
> 
> 复现过程：制造一个页面跳转流程：page A => page B => page C
> 并且在page B 中写：
> 
> ```
> componentWillUnmount() {
>     alert('Unmount')
>  }
> 
>   componentDidHide() {
>     alert('hide')
>   }
> ```
> 当page B跳到（navigateTo）page C时，都不显示。
> 
> 当page B跳回（navigateBack）page A时，只显示"Unmount"。
> 
> **结论：componentDidHide在h5上无效。**

你的页面B是不是高阶组件？

**Comment by 349989153** [comment]
@Littly 最多用@inject和@observer修饰了
