### ISSUE TITLE
taro-ui在企业微信小程序中，样式全部不起作用了？

### ISSUE THREAD

**Issue by wangxv** [NervJS/taro#2276]
**问题描述**
taro+taro-ui写的微信小程序，在微信上是好的，但是在企业微信上没有样式（taro的组件是好的，taro-ui的组件没有样式）（安卓手机出错，ios正常）

企业微信
![image](https://user-images.githubusercontent.com/30195186/53464656-fa8b3800-3a85-11e9-8efe-8d285714fad6.png)

微信

![image](https://user-images.githubusercontent.com/30195186/53464657-fb23ce80-3a85-11e9-92de-757b3101af68.png)

在组件上用函数式定义ref
微信小程序中得到
![image](https://user-images.githubusercontent.com/30195186/53464755-7a190700-3a86-11e9-96b1-3192fa2bcf8e.png)
企业微信中没有得到

**复现步骤**
1.在企业微信上打开小程序（安卓手机）

**期望行为**
 在企业微信中样式可以正常

**报错信息**
无报错

**系统信息**
 - Taro 版本 [e.g. v1.2.7]
 - Taro UI 版本 [e.g. v.2.0.0]
 - 报错平台 [weapp]

**Comment by arronlovepudding** [comment]
ios是正常的，安卓不行

**Comment by Chen-jj** [comment]
@wangxv 推测是企业微信在部分安卓手机上 [addGlobalClass](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html) 不生效导致。

可以试试 Taro UI 2.0.0 以前的版本。

**Comment by wangxv** [comment]
好的
