### ISSUE TITLE
小程序setState改变数组中的某一项或者某一属性没有生效

### ISSUE THREAD

**Issue by jyjey** [NervJS/taro#2278]
**问题描述**
由于微信小程序的限制一次setState不能超过1024kb，按微信官方文档逐个set数组中的元素，无效。
原生微信小程序代码可以实现。

[或者可以直接贴源代码，能贴文字就不要截图]

```js

setOrderData = (orderData, index) => {
    if(orderData.length > index){
      let key = "orderData["+index+"]";
      this.setState({
        [key]: orderData[index]
      }, () => {
        this.setOrderData(orderData, index + 1)
      })
    }
  };

```

**期望行为**
能正常改变数组中的某一项或者某一属性

**报错信息**

无报错信息，state中没有数据变化

**系统信息**

  Taro CLI 1.2.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - D:\workTool\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\ACE\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - D:\workTool\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@jyjey 提供一下可复现代码

**Comment by jyjey** [comment]
`
import Taro, { Component, Config } from '@tarojs/taro'
import {View, Text, Image} from '@tarojs/components'
import {AtNavBar, AtTabs, AtTabsPane, AtList, AtListItem, AtButton, AtIcon} from 'taro-ui'

export default class Order extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '订单'
  };
  openid = '';
  constructor () {
    super(...arguments)
  }


  state = {
    orderData:[]
  };



  setOrderData = (orderData, index) => {
    if(orderData.length > index){
      let key = "orderData["+index+"]";
      this.setState({
        [key]: orderData[index]
      }, () => {
        this.setOrderData(orderData, index + 1)
      })
    }
  };


  

  componentWillMount ()
  {
    let orderData = ["Strawberry", "Banana", "Mango"];
	this.setOrderData(orderData, 0);
  }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }



  render () {
    const {orderData} = this.state;
	console.log(orderData);
    return (
      <View>

      </View>
    )
  }
}

`

**Comment by jyjey** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@jyjey Taro 在小程序 setData 前，会做一次 [diff](https://nervjs.github.io/taro/docs/best-practice.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%95%B0%E6%8D%AE-diff) ，你正常 setState 即可

**Comment by Chen-jj** [comment]
#882

**Comment by jyjey** [comment]
> @jyjey Taro 在小程序 setData 前，会做一次 [diff](https://nervjs.github.io/taro/docs/best-practice.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%95%B0%E6%8D%AE-diff) ，你正常 setState 即可

感谢
