### ISSUE TITLE
taro怎么渲染一个html字符串，类似react的dangerouslysetinnerhtml

### ISSUE THREAD

**Issue by zhangfan6644777** [NervJS/taro#2279]
taro怎么渲染一个html字符串，类似react的dangerouslysetinnerhtml

**Comment by yuche** [comment]
你可以考虑使用 wxparse。
在 taro 中使用 wxparse 有两个方法：
1. 按照 [使用微信小程序第三方组件和插件](https://nervjs.github.io/taro/docs/wx-third-party.html#docsNav) 使用
2. [把 wxparse 转换为 taro 模块](https://nervjs.github.io/taro/docs/taroize.html)使用

**Comment by zhangfan6644777** [comment]
> 你可以考虑使用 wxparse。
> 在 taro 中使用 wxparse 有两个方法：
> 
> 1. 按照 [使用微信小程序第三方组件和插件](https://nervjs.github.io/taro/docs/wx-third-party.html#docsNav) 使用
> 2. [把 wxparse 转换为 taro 模块](https://nervjs.github.io/taro/docs/taroize.html)使用

我去尝试一下  非常感谢

**Comment by zhangfan6644777** [comment]
> 你可以考虑使用 wxparse。
> 在 taro 中使用 wxparse 有两个方法：
> 
> 1. 按照 [使用微信小程序第三方组件和插件](https://nervjs.github.io/taro/docs/wx-third-party.html#docsNav) 使用
> 2. [把 wxparse 转换为 taro 模块](https://nervjs.github.io/taro/docs/taroize.html)使用

有没有例子 给提供一下呢

**Comment by yuche** [comment]
github 搜索 `taro wxparse` 就有两个例子：
https://github.com/search?q=taro-wxparse&ref=opensearch

**Comment by zhangfan6644777** [comment]
> github 搜索 `taro wxparse` 就有两个例子：
> https://github.com/search?q=taro-wxparse&ref=opensearch

解决了 谢谢

**Comment by jinyindu** [comment]
这个支持百度，字节跳动，和支付宝小程序吗

**Comment by yuche** [comment]
@jiangzeyin 转换到 taro 模块就支持。

**Comment by jiangzeyin** [comment]
> @jiangzeyin 转换到 taro 模块就支持。

@ 错人了吧

**Comment by yuche** [comment]
@jiangzeyin sorry...你们 ji 字辈的兄弟太多了。。

@jinyindu 看楼上

**Comment by jinyindu** [comment]
出现这个错误 转换到taro 后

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53483721-12ca7980-3abd-11e9-823f-829a9b773aea.png)
![image](https://user-images.githubusercontent.com/18224886/53483728-178f2d80-3abd-11e9-9ecf-d0e63125722f.png)

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53485172-7e621600-3ac0-11e9-882a-ec223efd605e.png)
生成的这样文件必须要放在目录下吗

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53493875-65b12a80-3ad7-11e9-8fbf-0381f69d194e.png)
![image](https://user-images.githubusercontent.com/18224886/53493886-69dd4800-3ad7-11e9-95e7-306f774a99dd.png)
官方有wxparse 转taro 后使用的案例吗  我这样一直报错

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53536327-ef491280-3b40-11e9-80e4-a1f9415b25a0.png)

**Comment by yuche** [comment]
@jinyindu 看文档先修改 wxparse 再改

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53537958-c592ea00-3b46-11e9-8fa7-51271f94ee0e.png)
这种写法有问题吗

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53538797-18ba6c00-3b4a-11e9-8570-0ff5e79b9a93.png)
这种写法有问题吗 按钮文档修改后从微信小程序生成taro 模块，加入taro代码中 富文本还是不出来

**Comment by jinyindu** [comment]
页面渲染不出来

**Comment by sgidlhy** [comment]
> ![image](https://user-images.githubusercontent.com/18224886/53493875-65b12a80-3ad7-11e9-8fbf-0381f69d194e.png)
> ![image](https://user-images.githubusercontent.com/18224886/53493886-69dd4800-3ad7-11e9-95e7-306f774a99dd.png)
> 官方有wxparse 转taro 后使用的案例吗 我这样一直报错

我这也一直这样报错，请问你是怎么解决的

**Comment by sgidlhy** [comment]
![image](https://user-images.githubusercontent.com/17716350/58946645-f2dfdb80-87b8-11e9-9ebf-4d748ee6c223.png)
编译h5的时候报这个错，这个应该要怎么解决

**Comment by lemondreamtobe** [comment]
有更好的方法吗 https://github.com/search?q=taro-wxparse&ref=opensearch
这两个没法用
