### ISSUE TITLE
请问能给一个如何绘制曲线图表的demo吗？

### ISSUE THREAD

**Issue by 8gua-men** [NervJS/taro#228]
我写网页一般会用 https://www.highcharts.com/ 绘制图表。
请问能给一个如何绘制曲线图表的demo吗？
另外有演示组件的demo吗？

**Comment by innocces** [comment]
如果是网页理论可以直接使用react的图表库的

**Comment by luckyadam** [comment]
我们正在考虑如何接入第三方 UI 库，小程序有自己第三方绘图库，我们接入后会发通知的哈
