### ISSUE TITLE
荣耀7x 荣耀8 picker 不触发回调事件

### ISSUE THREAD

**Issue by wx56398676** [NervJS/taro#2282]
Taro v1.2.13
H5版本在荣耀7x 荣耀8  系统浏览器内出现
![image](https://user-images.githubusercontent.com/46560578/53534973-eace2b00-3b3b-11e9-9c3c-2e3d9b9ea044.png)
当出现系统自带导航条时 picker不触发回调，相关测试链接及视频已发送群管理员

**Comment by gyf19** [comment]
+1  我们也遇到这个问题， 请问什么时候可以解决呀

**Comment by shenghanqin** [comment]
荣耀7x 荣耀8 的系统信息？浏览器的userAgent？
