### ISSUE TITLE
IOS9.1操作系统setstate 不触发rander( ) 渲染UI

### ISSUE THREAD

**Issue by wx56398676** [NervJS/taro#2283]
IOS9.1操作系统
H5版本 Taro v1.2.13
setstate 不触发rander( ) 渲染UI
相关测试链接及视频已发送群管理员

**Comment by gyf19** [comment]
+1  我们也遇到这个问题， 请问什么时候可以解决呀

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/81cc6365c71588aaab5a2e7c9441d6c8f85128bd 可以尝试下新版本 已经修复了~
