### ISSUE TITLE
微信小程序独立分包不可用

### ISSUE THREAD

**Issue by darkfiredarkhalo** [NervJS/taro#2284]
**问题描述**
微信小程序独立分包(及不依赖于主包加载的分包),会报错,信息如下:
 module "npm/@tarojs/taro-weapp/index.js" is not defined 

**复现步骤**
1,src/目录下新建subpackages/目录,新建页面
2,app.js中声明分包为独立分包(independent:true)
3,config/index.js配置目录copy
4,微信开发者工具中新建编译模式,直接指向独立分包

**期望行为**
可以正常使用独立分包

**报错信息**
![2019-02-28 09 38 51](https://user-images.githubusercontent.com/13959162/53535151-b27b1c80-3b3c-11e9-8a7f-3c991d65ebfb.png)

**系统信息**
 - 操作系统: mac os 10.14.2
 - Taro 版本:  1.2.8
 - Node.js 版本 : 11.1.0
 - 报错平台: weapp

**补充信息**
独立分包的导航栏已加载,但是页面无法呈现

**Comment by luckyadam** [comment]
请提供一个复现的 demo 吧

**Comment by darkfiredarkhalo** [comment]
[subpackageDemo.zip](https://github.com/NervJS/taro/files/2913078/subpackageDemo.zip)
1,解压进入目录,npm install,
2,npm run dev:weapp
3,打开微信开发者工具,选择dist/目录打开
4,编译模式---新建---页面选中subpages/help/index

**Comment by darkfiredarkhalo** [comment]
经测试,普通分包没影响,就是独立分包不行

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/54419341-2410b880-4742-11e9-9c46-fc98f7d70154.png)
由于独立分包的时候，子包无法访问主包内容，所以在独立分包的时候需要把 npm 的依赖同时打包到子包里，Taro 后续会跟进调整，目前你可以依靠手动 copy 的形式来解决~

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/54419341-2410b880-4742-11e9-9c46-fc98f7d70154.png)
由于独立分包的时候，子包无法访问主包内容，所以在独立分包的时候需要把 npm 的依赖同时打包到子包里，Taro 后续会跟进调整，目前你可以依靠手动 copy 的形式来解决~

**Comment by shenghanqin** [comment]
@luodanyalian Taro开发是有诸多小限制的，你得尝试在限制下解决问题先。
这个分包的，可以看看最新版本里面有木有还是？

**Comment by 17** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/54419341-2410b880-4742-11e9-9c46-fc98f7d70154.png)
> 由于独立分包的时候，子包无法访问主包内容，所以在独立分包的时候需要把 npm 的依赖同时打包到子包里，Taro 后续会跟进调整，目前你可以依靠手动 copy 的形式来解决~

@luckyadam 使用独立分包时，npm 依赖应该复制到哪里？
我尝试复制 npm 依赖到分包的 root 路径，尝试过 npm/@taro 或者 @taro 均不能成功加载。
需要手动引入？

**Comment by CPPAlien** [comment]
目前这一块有进展吗？

**Comment by Chen-jj** [comment]
@CPPAlien Taro v3.2.12+ 开始支持

**Comment by nosillytrying** [comment]
现在版本是v3.4.3 还是不支持独立分包

**Comment by wuxuejie** [comment]
独立分包什么时候支持呢，官网示例都运行不起来？
<img width="760" alt="image" src="https://github.com/NervJS/taro/assets/31883495/957b68de-f3c6-4805-a678-62b19da95cf2">
