### ISSUE TITLE
导入多张本地静态图片怎么写简单

### ISSUE THREAD

**Issue by dengxue0** [NervJS/taro#2287]
**问题描述**
导入本地静态图片可以使用 import namedPng from '../../images/path/named.png'引入，
那导入多张本地静态图片，要写多行import吗，有没有其他简写的方式

**复现步骤**

**期望行为**
如果导入10张图片可以不import 10行代码

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 1.2.13
 - Node.js v8.11.1
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Garfield550** [comment]
看这里，也许会有些帮助
https://stackoverflow.com/questions/47614274/use-index-js-to-import-multiple-image-assets-in-react?rq=1
https://stackoverflow.com/questions/44607396/importing-multiple-files-in-react
https://github.com/gatsbyjs/gatsby/issues/3663

**Comment by yuche** [comment]
@Garfield550  提供的第一个链接的方法可行，第二种目前在 Taro 还行不通

**Comment by darkfiredarkhalo** [comment]
直接指定图片src不行吗,非得import

**Comment by yuche** [comment]
不行
