### ISSUE TITLE
在微信开发者工具中不支持打开less文件

### ISSUE THREAD

**Issue by fikyair** [NervJS/taro#2289]

**Comment by fikyair** [comment]
请问有什么优雅的方式么

**Comment by Garfield550** [comment]
使用 VSCode https://code.visualstudio.com/

**Comment by yuche** [comment]
你可以使用其它编辑器或者向微信官方提出需求

**Comment by fikyair** [comment]
> 你可以使用其它编辑器或者向微信官方提出需求
好，谢谢🤡

**Comment by fikyair** [comment]
> 使用 VSCode https://code.visualstudio.com/
好的，谢谢🤔
