### ISSUE TITLE
ESLint 错误报错：JSX 事件名需以 `on` 命名 (taro/jsx-handler-names)

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#229]
想给 Button 重新包装的场景下：

![](https://ws3.sinaimg.cn/large/006tKfTcgy1fsrm6hyf2ej311m0pyqao.jpg)

同样：#145 最后「错误的事件名判断」未解决

**Comment by zacksleo** [comment]
taro 更新到最新版 应该解决了 https://github.com/NervJS/taro/pull/216

**Comment by Songkeys** [comment]
升级到了 0.62。好像仍未解决。在旧项目里用了 `taro upgrade project` 之后，针对 eslint 还需要做什么配置吗？

**Comment by yuche** [comment]
不需要，去看看 `node_modules` 里 `eslint-plugin-taro` 安装的是什么版本。
#216 应该修复你这个问题。

**Comment by Songkeys** [comment]
非常感谢。刚才重启了一下 IDE，解决了……应该是缓存的问题。可以关闭啦。谢谢🙏
