### ISSUE TITLE
taro convert 出现的error: slot 的值必须是一个字符串

### ISSUE THREAD

**Issue by 7zf001** [NervJS/taro#2291]
**问题描述**
我需要for循环来在组件中的slot添加内容。

**复现步骤**
1. 创建组件
```
//  /components/tabs/index.js
Component({
  options: {
    multipleSlots: true
  }
})
```

```
//  /components/tabs/index.wxml
<view>
组件：
start:
<view
  wx:for="{{ 5 }}" 
  wx:key="*this"
>
  <slot name="{{ ‘’ + index }}"></slot>
</view>
end:
</view>
```
2. 创建page
```
// index.wxml
<view>
  page页面:
  <tabs>
     <view 
      wx:for="{{ 5 }}" 
      wx:key="*this" 
      slot="{{ ‘’ + index }}"
    >
      {{ index }}
    </view>
  </tabs>
</view>
```
```
// index.json
{
  "usingComponents": {
    "tabs": "/Components/tabs/index"
  }
}
```
3. taro convert时： 
错误  页面转换  pages/index/index.js
Error: slot 的值必须是一个字符串

**期望行为**
不报错

**报错信息**
tanzhifengdeMacBook-Pro:test tanzhifeng$ taro convert
👽 Taro v1.2.15

开始代码转换...
转换  入口文件  app.js
转换  入口配置  app.json
转换  入口样式  app.wxss
生成  入口文件  taroConvert/src/app.js
转换  页面文件  pages/index/index.js
转换  页面配置  pages/index/index.json
转换  页面模板  pages/index/index.wxml
转换  页面样式  pages/index/index.wxss
错误  页面转换  pages/index/index.js
Error: slot 的值必须是一个字符串

**Comment by yuche** [comment]
如报错所言，Taro 转小程序是没有办法使用动态的 slot 名的，你只能更改你的实现逻辑了

**Comment by 7zf001** [comment]
@yuche 后期版本会支持吗？还是编译上无法实现？

**Comment by yuche** [comment]
编译上无法实现，编译到 jsx 一定要有名字，而且这个名字一定不能是动态生成的。

**Comment by 7zf001** [comment]
@yuche 明白，谢谢啦
