### ISSUE TITLE
微信小程序无法给`自定义组件本身`添加样式类

### ISSUE THREAD

**Issue by ccqgithub** [NervJS/taro#2293]
**问题描述**

比如使用 taro-ui 的自定义组件`<AtButton className="test">`，className会传到自定义组件的根元素(`<at-button><view class="at-button test"></view><at-button>`)，组件本身`at-button`不能添加样式类(`<at-button class="test"><view class="at-button"></view><at-button>`)。

出现这个问题的原因是h5和小程序对于自定义组件的表现不一样，小程序外面会多一层自定义组件标签，比如: `at-button`, 而h5里面是直接渲染根元素！

这与小程序原生不一致，不能实现某些效果。

https://github.com/NervJS/taro-ui/issues/434

**复现步骤**

比如一个View里面放入两个AtButton，在微信小程序里想个给AtButton组件本身加`flex:1`。

模板：
```
<View className="btns">
  <AtButton className="btn">1</AtButton>
  <AtButton className="btn">2</AtButton>
</View>
```

样式
```
.btns { display: flex; }
.btn { flex: 1 };
```

小程序编译出来后是：

```
<view class="btns">
   <at-button> <view class="btn">1</view></at-button>
   <at-button> <view class="btn">2</view></at-button>
</view>
```

由于小程序中`.btn`外面多了一层`at-button`标签，所以并不起作用。

**期望行为**

期望实现这种效果：

```
<view class="btns">
   <at-button class="btn"> <view >1</view></at-button>
   <at-button class="btn"> <view >2</view></at-button>
</view>
```

![image](https://user-images.githubusercontent.com/1654761/53631031-7c2cc280-3c4c-11e9-99b0-5bbc98af1a5a.png)

**报错信息**

**系统信息**

 - 操作系统: macOS High Sierra 10.13.1
 - Taro 版本 v1.2.13
 - Node.js 版本 v10.0.0
 - 报错平台 weapp

**Comment by ccqgithub** [comment]
这种情况，是否可以有一个专门的属性来控制，比如`componentClassName`？

直接用`class`的话编译出来好像是正确的，但是react里不支持`class`保留字，eslint也报错。

**Comment by js-newbee** [comment]
这个是小程序自身的限制，没有太好的办法（不然你设计组件的时候，就要暴露 N 多 xxxClassName 出来才行，你不一定只会对外层样式覆盖的，内层某个元素呢？整个组件的设计就很臃肿了），建议用子代选择器覆盖组件样式 `. btns .at-button` (不一定准确，大概就这个意思)

**Comment by fjc0k** [comment]
在类名这块 Taro 做得还不够完善：

https://github.com/NervJS/taro/issues/2077#issuecomment-458826140

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/443b1dc459ce960f894d96c462742b06080b014a
