### ISSUE TITLE
你好, 创建的taro项目,转化为RN项目(npm run dev:rn), 得到.rn_temp 这个expo项目运行不了

### ISSUE THREAD

**Issue by LGLee** [NervJS/taro#2294]
**问题描述**
你好, 创建的taro项目,转化为RN项目(npm run dev:rn), 得到.rn_temp. 使用taro run dev:rn可以运行,使用expo命令运行不了
**复现步骤**
[复现问题的步骤]
1. npm run dev:rn
2. cd .rn_temp
3. expo start
4. run
**期望行为**
能转化从不依赖expo 最好了.如果暂时是expo  ,希望能 expo detach, 想把剥离出来的rn作为项目的模块集成到原生项目中.

**报错信息**
![image](https://user-images.githubusercontent.com/13104224/53566634-b425fe00-3b97-11e9-885f-8b375d776c44.png)

**系统信息**
> Taro v1.2.12
  Taro CLI 1.2.12 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.12 => 1.2.12
      @tarojs/components-rn: ^1.2.12 => 1.2.14
      @tarojs/router: 1.2.12 => 1.2.12
      @tarojs/taro: 1.2.12 => 1.2.12
      @tarojs/taro-alipay: 1.2.12 => 1.2.12
      @tarojs/taro-h5: 1.2.12 => 1.2.12
      @tarojs/taro-redux-rn: ^1.2.12 => 1.2.14
      @tarojs/taro-rn: ^1.2.12 => 1.2.14
      @tarojs/taro-router-rn: ^1.2.12 => 1.2.14
      @tarojs/taro-swan: 1.2.12 => 1.2.12
      @tarojs/taro-tt: 1.2.12 => 1.2.12
      @tarojs/taro-weapp: 1.2.12 => 1.2.12
      expo: 27.0.1 => 27.0.1
      nervjs: ^1.3.9 => 1.3.12
      react: 16.3.1 => 16.3.1
      react-native: 0.55.2 => 0.55.2

**Comment by LGLee** [comment]
1. npm run dev:rn
2. cd .rn_temp
3. expo start  
4. run
![image](https://user-images.githubusercontent.com/13104224/53566281-b045ac00-3b96-11e9-8640-0d9c29fde98c.png)
请问什么原因?

我想把这个expo  detach , 作为一个模块嵌入原生项目中,是否可行?

**Comment by Pines-Cheng** [comment]
正在去除 expo 依赖。
