### ISSUE TITLE
是否有用cordova把taro生成的H5打包成apk的解决方案

### ISSUE THREAD

**Issue by kanekilua** [NervJS/taro#2296]
**问题描述**
尝试使用cordova打包taro编译生成的h5项目，结果生成的apk在手机上安装后显示白屏。因为公司的cordova技术栈比较成熟，而且想节约学习rn的成本。

**系统信息**
 - 操作系统: Windows 10
 - Taro 版本: 1.2.13
 - Node.js 版本: 8.11.2

**Comment by kanekilua** [comment]
taro init project后，修改
1. h5的publicPath 改为"./"
2. 在app.js中添加deviceready的监听函数后
使用npm run build:h5进行编译，双击编译后的index.html文件在pc端的chrome完全正常。使用cordova将其打包后，手机打开是个空白的页面。使用“chrome://inspect/#devices”调试，报错:
**Uncaught TypeError: this.customRoutes.find is not a function  lib.dll.js 1 **

**Comment by kanekilua** [comment]
taro init project后，修改
1. h5的publicPath 改为"./"
2. 在app.js中添加deviceready的监听函数后
使用npm run build:h5进行编译，双击编译后的index.html文件在pc端的chrome完全正常。使用cordova将其打包后，手机打开是个空白的页面。使用“chrome://inspect/#devices”调试，报错:
**Uncaught TypeError: this.customRoutes.find is not a function  lib.dll.js 1 **

**Comment by kanekilua** [comment]
taro init project后，修改
1 h5的publicPath 改为"./"
2 在app.js中添加deviceready的监听函数后
使用npm run build:h5进行编译，双击编译后的index.html文件在pc端的chrome完全正常。使用cordova将其打包后，手机打开是个空白的页面。使用“chrome://inspect/#devices”调试，报错:
**Uncaught TypeError: this.customRoutes.find is not a function  lib.dll.js 1 **

**Comment by kanekilua** [comment]
已实现/逃

**Comment by my101du** [comment]
@kanekilua  你好，我也想这样实现。先生成 H5 版本的文件，然后用 Cordova 包裹成 app.
请问有没有比较完整的实现步骤？如有的话还请指教。
 Taro 编译出来的 RN 总是出各种问题，屏幕一片血红，报错信息占满整个模拟器（摊手），而且兼顾 RN 后，CSS 等写起来就很不灵活了。

**Comment by cxcxcxcx** [comment]
> taro init project后，修改
> 1 h5的publicPath 改为"./"
试了一下，单这项改动后就可以在 cordova 里用了

**Comment by spearsharp** [comment]
同问
