### ISSUE TITLE
[Feature request]微信小程序的FileSystemManager相关的api支持？

### ISSUE THREAD

**Issue by 1995wyy** [NervJS/taro#2299]
**问题描述**

Taro目前不支持微信小程序的FileSystemManager相关的api, 不知道是否能够提供支持？
[https://developers.weixin.qq.com/miniprogram/dev/api/FileSystemManager.html](url)
希望提供支持，谢谢！！

**Comment by luckyadam** [comment]
支持啊，不过只能在微信小程序用

**Comment by ThatRoy** [comment]
@luckyadam   在 Taro v1.3.11 版本下插件开发，Taro.getFileSystemManager() 获取不到 FileSystemManager 对象

**Comment by 378978764** [comment]
> 支持啊，不过只能在微信小程序用

1.3.19还是不支持，types.d.ts中显示是TODO项
你的回答无意中错误终结了一个issue

**Comment by Garfield550** [comment]
欢迎提一个 PR，目前 Taro 支持以 `const fileManager: any = wx.getFileSystemManager()` 的形式调用 FileSystemManager，只是没有类型检查。
