### ISSUE TITLE
建议支持source标签组件  

### ISSUE THREAD

**Issue by longmimi** [NervJS/taro#2303]
**问题描述**
[问题描述：通过<Audio> 组件播放声音 需要兼容多种格式音频文件，如mp3 ogg等 没有source标签只能写一种]

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
期望支持source 标签 可以加载多个src音频资源

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [mac os 10.14]
 - Taro 版本 [v.1.2.3]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
小程序没有这个标签哦
