### ISSUE TITLE
wx:for-index 微信小程序转taro无法完成转换

### ISSUE THREAD

**Issue by yantingxi** [NervJS/taro#2304]

**Comment by jinjinjin0731** [comment]
附上相关代码 以及 taro 版本

**Comment by yantingxi** [comment]
👽 Taro v1.2.13
  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v11.10.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
![image](https://user-images.githubusercontent.com/30825361/53621868-fa7c6b00-3c32-11e9-8a84-f021df8aa5a2.png)
![image](https://user-images.githubusercontent.com/30825361/53621998-5d6e0200-3c33-11e9-8473-1f7c184b6c3c.png)

**Comment by yuche** [comment]
贴微信小程序的源码，文字，不要截图

**Comment by yantingxi** [comment]
<view class="tab" wx:for-index="idx">
  <view class="{{index ===  Inx? 'select' : 'selectnot'}}" wx:for="{{tab}}" data-index="{{index}}" bindtap="changeTab">{{item}}</view>
</view>

**Comment by yuche** [comment]
你的代码写得有问题吧，wx:for-index="idx" 应该和 wx:for 放在一块
