### ISSUE TITLE
一个程序多项目对app.js中config设置

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#2305]
**问题描述**
现在一个程序是给几个客户用，只是名称有区别，现在只能打包完，再改名称，或者改代码再改名称，比如

```js
    window: {
      backgroundTextStyle: 'light',
      navigationBarTitleText: 'title', //这里只需要动态设置title
      navigationBarTextStyle: 'white',
      navigationBarBackgroundColor: '#f37b1d'
    }
```

这里试过把 `navigationBarTitleText `后面使用变量，发现没用，

**期望行为**
可以实现一程序多项目配置，看有人做了个 https://github.com/BakerJQ/WeAppBunXin, 是基于taro的，不过`navigationBarTitleText ` 这个还是没有找到办法

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.2
 - Taro 版本 1.2.14
 - Node.js 版本 0.13.0
 - 报错平台  weapp

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/53631412-6f5c9e80-3c4d-11e9-8554-f10f241a2396.png)
https://developers.weixin.qq.com/miniprogram/dev/api/wx.setNavigationBarTitle.html
你试试这个能不能满足你的需求。

**Comment by nyrf** [comment]
@Garfield550  这个不行的，要每个页面都设置，

**Comment by Garfield550** [comment]
也许你可以从 @BakerJQ 的这篇文章中获得一些思路？今天刚看到的，也许对你有用。
https://segmentfault.com/a/1190000018350307

**Comment by BakerJQ** [comment]
可以使用Taro配置里的全局变量（https://nervjs.github.io/taro/docs/config-detail.html#defineconstants）

**Comment by luckyadam** [comment]
@nyrf 试试 @BakerJQ 这位大佬的方案呢~

**Comment by nyrf** [comment]
> navigationBarTitleText

谢谢，用这个是可以， @luckyadam 后面有考虑添加多项目配置么？

**Comment by NicholasNC** [comment]
Taro V2.0.5 对于 BakerJQ 的方法好像不行
