### ISSUE TITLE
可不可以实例一个包括支付宝、微信、头条、RN端的同一个项目？？

### ISSUE THREAD

**Issue by xiaoJinGong** [NervJS/taro#2307]
你们确定这两个支付宝小程序二维码不是一样的？？

![image](https://user-images.githubusercontent.com/20038482/53628276-91522300-3c45-11e9-9405-02b37e1871f6.png)

**Comment by yuche** [comment]
要不你来做一个这样的项目？

**Comment by luckyadam** [comment]
https://github.com/js-newbee/taro-yanxuan

**Comment by xiaoJinGong** [comment]
> 要不你来做一个这样的项目？？

不好意思，我还真在做

**Comment by yuche** [comment]
@xiaoJinGong 期待你做出来的那一天，我们也给你大肆宣传一波~
