### ISSUE TITLE
less 不支持@import?

### ISSUE THREAD

**Issue by Mazhp** [NervJS/taro#231]
我在app.less 中引用其它的less文件，报错，是我的写法有问题，还是不支持呢？如图所示：
![less](https://user-images.githubusercontent.com/12904977/42078965-ecea1bb0-7bb0-11e8-8806-41b9d0d6956c.png)

**Comment by Hello-Tan** [comment]
我也遇到这个问题，感觉taro还不够成熟啊··

**Comment by NoahSun** [comment]
前几天开始试验Taro的时候就发现了，刚说来提一个，发现还是有人用@import的嘛

**Comment by fandebiao12345** [comment]
真的是 我定义的变量没法引用  这taro太不成熟了！  根本没法开发！

**Comment by jaylocke** [comment]
是啊，这个问题影响开发

**Comment by Superman-wc** [comment]
也遇到了同样的问题
