### ISSUE TITLE
关于taro版本控制，两个项目版本不一样，微信打包有一个提示版本问题

### ISSUE THREAD

**Issue by infipink** [NervJS/taro#2311]
如何控制项目的taro版本，版本不统一时，微信打包报“版本问题  Taro CLI 与本地安装的小程序框架 @tarojs/taro-weapp 版本不一致，请确保一致”

**Comment by Garfield550** [comment]
可能是你的 Taro CLI 和你项目里的依赖版本差距太大，尝试更新一下这两者
https://docs.npmjs.com/cli/update.html
https://yarnpkg.com/lang/en/docs/cli/upgrade/
如果不太确定可以先使用 outdated 检查一下

**Comment by js-newbee** [comment]
@infipink 在项目中安装 @tarojs/cli 依赖，运行 npm scripts 时，项目内的依赖优先级高于全局
