### ISSUE TITLE
如何使用redux saga中的takeLatest等方法

### ISSUE THREAD

**Issue by jwhklk** [NervJS/taro#2312]
如何使用redux saga中的takeLatest等方法

**Comment by jwhklk** [comment]
我应该去dvajs这个项目里面去问吧

**Comment by jwhklk** [comment]
['load']:[function*({ payload }, { call, put }){
      console.log(payload);
      const data = yield call(homeApi.testpage, {});
      console.log("data~~~~");
      console.log("data~~~~");
      // console.log(data);
      yield put({
        type: 'pageadd',
        payload: data.status,
      });
    },{type:'takeLatest'}],

**Comment by yuche** [comment]
如果你用的是 redux-saga 就直接用，如果你用的是 dva 就去 dva 那里问
