### ISSUE TITLE
Taro 组件picker

### ISSUE THREAD

**Issue by youyou0101** [NervJS/taro#2313]
picker 选中后，再次点开，picker显示是上次选的值。

**Comment by jinjinjin0731** [comment]
taro 版本？  小程序还是 H5 ，附上一下相关代码？

**Comment by youyou0101** [comment]
{/* 普通选择器 */}
          <View className='panel'>
            <View className='panel__title'>普通选择器</View>
            <View className='panel__content'>
              <View className='example-item'>
                <Picker mode='selector' range={selector} value={selectorValue} onChange={this.handleChange}>
                  <View className='demo-list-item'>
                    <View className='demo-list-item__label'>国家地区</View>
                    <View className='demo-list-item__value'>{selector[selectorValue]}</View>
                  </View>
                </Picker>
              </View>
            </View>
          </View>
在h5中出现，taro版本是v1.2.15。

**Comment by jinjinjin0731** [comment]
既然你设置  value={selectorValue}  ，那么这个控件就是受控的了。  你点击确定后，你的回调有没有更新这个 value 的值呢？

**Comment by youyou0101** [comment]
selectorValue是一个state。
`handleChange = e => {
    this.setState({
      selectorValue: e.detail.value
    })
  }`
小程序端不存在这个问题。

**Comment by zhangpengbin** [comment]
这个问题有解决么？遇到了同样的问题

**Comment by jinjinjin0731** [comment]
@youyou0101 @zhangpengbin  更新到最新版本

**Comment by zhangpengbin** [comment]
> @youyou0101 @zhangpengbin 更新到最新版本

已解决谢谢

**Comment by singagain** [comment]
不更新版本有没有解决方法？
