### ISSUE TITLE
Taro 微信版本有时候不会执行componentWillReceiveProps方法。

### ISSUE THREAD

**Issue by youyou0101** [NervJS/taro#2315]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
Taro 微信版本 指的是微信小程序端吧，麻烦补充一下场景描述和关键代码。

**Comment by youyou0101** [comment]
`import Taro, { Component } from "@tarojs/taro";
import { View, Text, Picker } from "@tarojs/components";
import "./index.scss";
import classnames from "classnames";

interface Props<T> {
  current?: number; //关系对应的range id
  onClick?: () => void;
  onChange?: (value: string | number | Object) => void;
  rangeKey?: keyof T;
}

interface DefaultProps<T> {
  title: string;
  hint: string;
  disabled: boolean;
  required: boolean;
  range: T[];
}

type PropsWithDefault<T> = Props<T> & DefaultProps<T>;

interface State {
  current: number; //表示选择了 range 中的第几个（下标从 0 开始）
}

export default class YXRPicker2<T> extends Component<
  PropsWithDefault<T>,
  State
> {
  static options = { addGlobalClass: true };

  readonly state: Readonly<State> = {
    current: this.props.current || 0
  };

  constructor(props) {
    super(props);
    this.setState({ current: this.props.current || 0 });
  }

  componentWillReceiveProps(nextProps) {
    this.setState({ current: nextProps.current });
  }

  static defaultProps: DefaultProps<any> = {
    title: "标题",
    hint: "",
    disabled: false,
    required: false,
    range: []
  };

  onClick = (e: Event) => {
    e.stopPropagation();
    this.props.onClick && this.props.onClick();
  };

  onPickerChange = (obj: { detail: { value: number } }) => {
    this.props.onChange && this.props.onChange(obj.detail.value);
  };

  render() {
    let showValue;
    if (this.props.range && this.props.range.length > 0) {
      let value = this.props.range[this.state.current];
      if (this.props.rangeKey) {
        showValue = value[this.props.rangeKey];
      }
    }

    return (
      <View className="YXRPicker" onClick={this.onClick.bind(this)}>
        <Picker
          className="picker"
          mode="selector"
          disabled={this.props.disabled}
          range={this.props.range}
          rangeKey={this.props.rangeKey as string}
          onChange={this.onPickerChange.bind(this)}
          value={this.state.current}
        >
          <View className="editContainer">
            <View className="title">
              {this.props.title}
              {this.props.required == true && (
                <Text className="no-required" style={{ color: "#F02D2D" }}>
                  *
                </Text>
              )}
            </View>

            <View
              className="txValue"
              style={{ color: showValue ? "#1E2832" : "#B4BECD" }}
            >
              {showValue || this.props.hint}
            </View>
            <Text
              className={classnames("iconfont", "iconRight", "icon-list-right")}
            />
          </View>
        </Picker>
      </View>
    );
  }
}
`
例如这个组件，在使用这个组件的页面改变current的时候，有时候没有调用componentWillReceiveProps。出现在微信小程序中。

**Comment by lyboy2012** [comment]
用componentDidUpdate(prevprops) 来监听属性变化
