### ISSUE TITLE
关于props.children的一些疑问

### ISSUE THREAD

**Issue by gwsme** [NervJS/taro#2319]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
在子组建内插入其他内容，通过 this.props.children插入到子组建内，但是渲染出来的结构是错误的，this.props.children并没有出现在子组建this.props.children插入的位置，而是在子组建的最外层

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 父组建
render () {
    return (<View>
        <Son>
            <View>这应该在子组建内显示</View>
        </Son>
    </View>)
}

// 子组建
render () {
    return (<View>
        {this.props.children}
    </View>)
}
```

**期望行为**

```
// 子组建渲染结果期望是
<View>
    <View>这应该在子组建内显示</View>
</View>
```

**报错信息**

```
// 子组建渲染结果结果是
<View></View>
<View>这应该在子组建内显示</View>
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macBook, 微信开发者工具]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
你得看编译后的代码，编译后的代码是正确的吗？
如果是，你应该想小程序容器商报告这个问题。

**Comment by luckyadam** [comment]
微信小程序的 web component 就是这样，并不会影响你的页面显示

**Comment by imageslr** [comment]
@yuche @luckyadam 不好意思，我想请问如果我在组件中想多次使用`this.props.children`该如何实现？比如这样

```JSX
<View class='my-sticky'>
        <View>1 {this.props.renderSticky}</View>
        <View>2 {this.props.children}</View>
</View>
```

但是编译出来的源码是这样，两个默认slot，导致只有第二个生效：

```html
<block>
    <view class="my-sticky">
        <view>1
            <slot></slot>
        </view>
        <view>2
            <slot></slot>
        </view>
    </view>
</block>
```

我知道可以通过在父组件中传递renderProps实现，但是这样感觉有点麻烦了。组件内部又无法操作this.props.children。请问有什么办法实现吗？
