### ISSUE TITLE
请教使用中如何避免组件间的样式冲突

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#232]
如题，目前正在使用taro，想请教这个问题

**Comment by riskers** [comment]
@xingBri 这个和 taro 无关，是一个 React 组件样式的问题。

如果你使用的是 less/scss，可以这么搞：

```
// pages/A/style.less
.a {
  // page A css...
}

// pages/B/style.less
.b {
  // page B css...
}
```

当然，如果嫌这样麻烦，就看 taro 官方什么支持 css modules 了。

**Comment by luckyadam** [comment]
后续加入 css Modules 支持，目前还是得依靠人工命名的方式控制
