### ISSUE TITLE
在 render 函数中的 jsx 中，类实例对象的getter 函数不起作用

### ISSUE THREAD

**Issue by topmyself** [NervJS/taro#2321]
**问题描述**
组件状态中包含一个类对象，类对象属性是通过 getter 获取的，在 jsx 中，无法获取到正确的值

**复现步骤**
[复现问题的步骤]
1. 声明类 Test
2. 类 Test 中添加 get 函数'
3. 组件中，创建 Test 类的对象
4. jsx 中，获取该 Test 实例的getter 函数
5. 无法获取到值

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
// testmodel.js
class Test{
  private a: string;
  get last(){
    return 'shibai';
  }
  set last(value){
    this.a = value;
  }
}
export { Test };

// 组件中的构造函数
  constructor(props){
    super(props);
    const test = new Test();
    this.state = { test};
  }

// render 函数中，通过 get 函数获取值, jsx 当中
<View className="profile-item-value">
      {this.state.test.last}
 </View>
```

**期望行为**
期望能够通过 get 函数获取值

**报错信息**
无

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
👽 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.07s. - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.2.2

 - 报错平台 [ weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
只在 render 函数，jsx 中失效，如果在 render 函数中，return 之前取值，则正常。
另外只有类中的 getter 函数是有问题的，如果更换为 Object 对象则正常

**Comment by yuche** [comment]
https://github.com/NervJS/taro/issues/1360#issuecomment-443977229

看回答的第一条，你的 Test 也是一个复杂对象（类）
