### ISSUE TITLE
taro + graphql 解决方案

### ISSUE THREAD

**Issue by YouYII** [NervJS/taro#2322]
目前正在研究taro + graphql 的方案, 倒腾出一个简单的办法, 在 h5 , react native中测试过,这里贴一下,免得后来者又走弯路

    import Taro from '@tarojs/taro'
    import ApolloClient from 'apollo-boost';

    const client = new ApolloClient({
      uri: 'http://192.168.1.100:3000/graphql',
      fetch: (url, options) => {
        return Taro.request({
          url,
          method: options.method,
          data: options.body,
          header: options.headers,
        }).then(({data, statusCode}) => {
          return {
            ok: () => {
              return statusCode >= 200 && statusCode < 300;
            },
            text: () => {
              return Promise.resolve(JSON.stringify(data));
            }
          }
        });
      }
    });
    export default client

使用方法

    client.query({
      query: gql`
          query Login($userInput:UserInput!){
              login(userInput:$userInput){
                  expiresIn
                  accessToken
              }
          }
      `,
      variables: {userInput: {name: this.state.username, password: this.state.password}},
    })
    .then(data => Taro.showToast({
        title: JSON.stringify(data.data.login.accessToken),
        icon: 'success',
        duration: 2000,
      }),
    ).catch(error => {
        console.error(error.graphQLErrors[0].message)
        console.error(error.message)
        console.error(error.networkError)
      },
    );

**Comment by YouYII** [comment]
小程序中也使用过,效果挺好的

**Comment by leoswing** [comment]
> 小程序中也使用过,效果挺好的

这个有使用react-apollo 高阶组件 <Query> 和 <Mutation> 吗

**Comment by YouYII** [comment]
我自己用mobx 的action来维护状态, 感觉也蛮好的 , 高阶组件不自由

**Comment by leoswing** [comment]
> 我自己用mobx 的action来维护状态, 感觉也蛮好的 , 高阶组件不自由

全部打算用apollo 来处理状态，所以能用高阶组件的话，可以节省不少调用api的麻烦；
有使用案例吗？ 目前通过client.query 这种我是解决了

**Comment by YouYII** [comment]
# 封装
    async function asyncCall(callback) {
      await sleep(0.01);
      Taro.showLoading({
        title: '加载中',
      })

      try {
        await callback();
      } catch (e) {
        Taro.showToast({
          title: e.message,
          icon: 'none',
          duration: 5000,
        })
        await callback();
      } finally {
        Taro.hideLoading()
      }
    }

    # 用法
    await asyncCall(async () => {
        await doSomeThings();
    })

这个是我用的简单封装 , 可以看看

**Comment by Janice1114** [comment]
> ```
> # 封装
> async function asyncCall(callback) {
>   await sleep(0.01);
>   Taro.showLoading({
>     title: '加载中',
>   })
> 
>   try {
>     await callback();
>   } catch (e) {
>     Taro.showToast({
>       title: e.message,
>       icon: 'none',
>       duration: 5000,
>     })
>     await callback();
>   } finally {
>     Taro.hideLoading()
>   }
> }
> 
> # 用法
> await asyncCall(async () => {
>     await doSomeThings();
> })
> ```
> 
> 这个是我用的简单封装 , 可以看看

请问下有使用 apollo-link-http 在小程序的demo吗？ 目前使用 这个调用中后台的请求的时候，报错了。在H5 用rest link 或者 apollo-link-http 都没问题。

**Comment by Janice1114** [comment]
> 目前正在研究taro + graphql 的方案, 倒腾出一个简单的办法, 在 h5 , react native中测试过,这里贴一下,免得后来者又走弯路
> 
> ```
> import Taro from '@tarojs/taro'
> import ApolloClient from 'apollo-boost';
> 
> const client = new ApolloClient({
>   uri: 'http://192.168.1.100:3000/graphql',
>   fetch: (url, options) => Taro.request({
>     url,
>     method: options.method,
>     data: options.body,
>     header: options.headers,
>   }).then(({data, statusCode}) => {
>     return {
>       ok: () => {
>         return statusCode >= 200 && statusCode < 300;
>       },
>       text: () => {
>         return Promise.resolve(JSON.stringify(data));
>       }
>     }
>   })
> });
> export default client
> ```
> 
> 使用方法
> 
> ```
> client.query({
>   query: gql`
>       query Login($userInput:UserInput!){
>           login(userInput:$userInput){
>               expiresIn
>               accessToken
>           }
>       }
>   `,
>   variables: {userInput: {name: this.state.username, password: this.state.password}},
> })
> .then(data => Taro.showToast({
>     title: JSON.stringify(data.data.login.accessToken),
>     icon: 'success',
>     duration: 2000,
>   }),
> ).catch(error => {
>     console.error(error.graphQLErrors[0].message)
>     console.error(error.message)
>     console.error(error.networkError)
>   },
> );
> ```

求分享在小程序这边用 apollo-link-http 的相关解决方案

**Comment by Janice1114** [comment]
@YouYII  这能否提供一个基于 apollo-link-http的demo看下？ thanks

**Comment by YouYII** [comment]
没有研究

**Comment by Janice1114** [comment]
> 没有研究

@YouYII  那你是怎么访问中后台数据的啊？ 通过什么方式获取

**Comment by grusirna** [comment]
谢谢，我采用这个方式已经解决了

**Comment by woshiji1987** [comment]
> > 没有研究
> 
> @YouYII 那你是怎么访问中后台数据的啊？ 通过什么方式获取

import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { HttpLink } from "apollo-link-http";
import { onError } from "apollo-link-error";
import { ApolloLink } from "apollo-link";

export const request = async (
  url,
  body,
  { method = "GET", params, header } = {}
) => {
  if (body && params) {
    url = `${url}?${qs.stringify(params)}`;
  }
  return await Taro.request({
    url: `${/^http/.test(url) ? "" : ENDPOINT}${url}`,
    method: method,
    data: body,
    dataType: "json",
    header: header
  });
};

const httpLink = new HttpLink({
  uri: `${config.ENDPOINT}/graphql`,
  fetch: (url, options) => {
    const { method = "POST", herder, body } = options;
    return request(url, body, {
      method,
      herder
    }).then(res => {
      const { data, statusCode } = res;
      res.text = () => Promise.resolve(JSON.stringify(data));
      return res;
    });
  }
});
// 验证权限中间件
const authMiddleware = new ApolloLink((operation, forward) => {
  operation.setContext(async ({ headers = {} }) => {
    const { accessToken: token } = await getItem(keys.auth);
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : null,
        "Content-Type": "application/json; charset=utf8"
      }
    };
  });
  return forward(operation);
});

const link = ApolloLink.from([
  onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      graphQLErrors.map(({ message, locations, path }) =>
        console.log(
          `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
        )
      );
    }
    if (networkError)
      console.error(`[Network error]: ${networkError}`, networkError.stack);
  }),
  authMiddleware,
  httpLink
]);

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: link
});

**Comment by woshiji1987** [comment]
如果有websocket需求  

import { WebSocketLink } from "apollo-link-ws";
import { getMainDefinition } from "apollo-utilities";
const wsLink = new WebSocketLink({
/ uri: `ws://localhost:5000/`,  options: {
     reconnect: false,
      reconnect: true
    connectionParams: async () => {
     const { accessToken: token } = await getItem(keys.auth);
      return { token };
    }
   }
 });

然后在ApolloLink.from中加入  
ApolloLink.split(
      ({ query }) => {
        const { kind, operation } = getMainDefinition(query);
        return kind === "OperationDefinition" && operation === "subscription";
      },
     wsLink,
      httpLink
    )

**Comment by woshiji1987** [comment]
`
import Taro from "@tarojs/taro";
import qs from "querystringify";
import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { HttpLink } from "apollo-link-http";
import { onError } from "apollo-link-error";
import { ApolloLink } from "apollo-link";
import { WebSocketLink } from "apollo-link-ws";
import { getMainDefinition } from "apollo-utilities";

import config from "./config";
import { getItem } from "./storage";
import { keys } from "./constants";
import cors from "./interceptors/cors";
// import authorization from "./interceptors/authorization";
import authentication from "./interceptors/authentication";

Taro.addInterceptor(Taro.interceptors.logInterceptor);
Taro.addInterceptor(cors);
// Taro.addInterceptor(authorization);
Taro.addInterceptor(authentication);

const { ENDPOINT } = config;

//  全局包装 请求loading
export const asyncCall = async callback => {
  // await sleep(0.01);
  Taro.showLoading({
    title: "加载中"
  });

  try {
    await callback();
  } catch (e) {
    Taro.showToast({
      title: e.message,
      icon: "none",
      duration: 5000
    });
    await callback();
  } finally {
    Taro.hideLoading();
  }
};

export const request = async (
  url,
  body,
  { method = "GET", params, header } = {}
) => {
  if (body && params) {
    url = `${url}?${qs.stringify(params)}`;
  }
  return await Taro.request({
    url: `${/^http/.test(url) ? "" : ENDPOINT}${url}`,
    method: method,
    data: body,
    dataType: "json",
    header: header
  });
};

// const wsLink = new WebSocketLink({
//   uri: `ws://localhost:5000/`,
//   options: {
//     reconnect: false,
//     // reconnect: true
//     connectionParams: async () => {
//       const { accessToken: token } = await getItem(keys.auth);
//       return { token };
//     }
//   }
// });

const httpLink = new HttpLink({
  uri: `${config.ENDPOINT}/graphql`,
  fetch: (url, options) => {
    const { method = "POST", herder, body } = options;
    return request(url, body, {
      method,
      herder
    }).then(res => {
      console.log("入口res:", res);
      const { data, statusCode } = res;
      res.text = () => Promise.resolve(JSON.stringify(data));
      return res;
    });
  }
});

const authMiddleware = new ApolloLink((operation, forward) => {
  operation.setContext(async ({ headers = {} }) => {
    const { accessToken: token } = await getItem(keys.auth);
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : null,
        "Content-Type": "application/json; charset=utf8"
      }
    };
  });
  return forward(operation);
});

const link = ApolloLink.from([
  onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      graphQLErrors.map(({ message, locations, path }) =>
        console.log(
          `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
        )
      );
    }
    if (networkError)
      console.error(`[Network error]: ${networkError}`, networkError.stack);
  }),
  authMiddleware,
  httpLink
  //  小程序不支持websocket  需要用Taro.connectSocket
  //   ApolloLink.split(
  //     ({ query }) => {
  //       const { kind, operation } = getMainDefinition(query);
  //       return kind === "OperationDefinition" && operation === "subscription";
  //     },
  //    wsLink,
  //     httpLink
  //   )
]);

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: link
});

client.defaultOptions = {
  watchQuery: {
    fetchPolicy: "cache-and-network",
    errorPolicy: "ignore"
  },
  query: {
    fetchPolicy: "network-only",
    errorPolicy: "all"
  },
  mutate: {
    errorPolicy: "all"
  }
};

export default client;
`

**Comment by privateJiangyaokai** [comment]
https://github.com/functorz-team/wx-apollo-subscription-client

**Comment by gaoyueban** [comment]
坐等大佬：
我在调用上出了一些问题
let sub = client.subscribe({ query: query, variables: variables }).subscribe(
    {
      next (data) {
      },
      error (e) {

      }
    }
  )
![image](https://user-images.githubusercontent.com/49631411/170400381-3da6770b-523d-49c7-8186-d93aafd7bbd7.png)
一直返回 type: "ka"

**Comment by woshiji1987** [comment]
小程序的ws是阉割过的，subcribe的ws需要自己再覆盖下，我回头给你个方案，不过预计要明天，今天有点事



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月26日 10:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NervJS/taro] taro + graphql 解决方案 (#2322) |

坐等大佬：
我在调用上出了一些问题
let sub = client.subscribe({ query: query, variables: variables }).subscribe(
{
next (data) {
},
error (e) {

  }

}



)

一直返回 type: "ka"

**Comment by gaoyueban** [comment]
多谢大佬帮助。
我现在是这样写的，用的是https://github.com/functorz-team/wx-apollo-subscription-client
![image](https://user-images.githubusercontent.com/49631411/170401961-18d0ec86-48f9-491a-ba2c-6b702eb0c70b.png)

**Comment by gaoyueban** [comment]
> 小程序的ws是阉割过的，subcribe的ws需要自己再覆盖下，我回头给你个方案，不过预计要明天，今天有点事
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年05月26日 10:04 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [NervJS/taro] taro + graphql 解决方案 (#2322) | 坐等大佬： 我在调用上出了一些问题 let sub = client.subscribe({ query: query, variables: variables }).subscribe( { next (data) { }, error (e) { } } ) 一直返回 type: "ka" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

大佬在吗？

**Comment by woshiji1987** [comment]
稍等，我整理下，3年前的代码了，思路就是替换ws模块



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月27日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NervJS/taro] taro + graphql 解决方案 (#2322) |

小程序的ws是阉割过的，subcribe的ws需要自己再覆盖下，我回头给你个方案，不过预计要明天，今天有点事
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年05月26日 10:04 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [NervJS/taro] taro + graphql 解决方案 (#2322) | 坐等大佬： 我在调用上出了一些问题 let sub = client.subscribe({ query: query, variables: variables }).subscribe( { next (data) { }, error (e) { } } ) 一直返回 type: "ka" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

大佬在吗？

**Comment by woshiji1987** [comment]
加我微信吧  18258896773



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月27日 09:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [NervJS/taro] taro + graphql 解决方案 (#2322) |

小程序的ws是阉割过的，subcribe的ws需要自己再覆盖下，我回头给你个方案，不过预计要明天，今天有点事
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年05月26日 10:04 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [NervJS/taro] taro + graphql 解决方案 (#2322) | 坐等大佬： 我在调用上出了一些问题 let sub = client.subscribe({ query: query, variables: variables }).subscribe( { next (data) { }, error (e) { } } ) 一直返回 type: "ka" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

大佬在吗？

**Comment by gaoyueban** [comment]
我是れ誮惜颜き，我加您了
