### ISSUE TITLE
请更新 @tarojs/webpack-runner > lodash 

### ISSUE THREAD

**Issue by hye** [NervJS/taro#2326]
**问题描述**
NPM install 完提示found 1 moderate severity vulnerability
**复现步骤**
[复现问题的步骤]

```shell
taro init eg
```

**报错信息**
```shell
found 1 moderate severity vulnerability
npm audit
```
 Moderate        │ Prototype Pollution  
------------ | -------------
 Package          │ lodash  
 Patched in       │ >=4.17.11    
 Dependency of │ @tarojs/webpack-runner [dev]
 Path                │ @tarojs/webpack-runner > lodash  
 More info       │ https://npmjs.com/advisories/782   

**系统信息**

 - 操作系统: windows 10 wsl (Linux 4.4 Ubuntu 16.04.5 LTS)
 - Taro 版本  1.2.15
 - Node.js 版本8.15.0

**Comment by Littly** [comment]
已解决
