### ISSUE TITLE
安装完taro之后，启动失败

### ISSUE THREAD

**Issue by hahazxy199433** [NervJS/taro#2328]
问题描述：安装完成 之后，在h5下运行，npm run dev:h5启动失败，报错。

复现步骤 
1.npm install -g @tarojs/cli

2.taro init myApp
? 请输入项目介绍！ test
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 默认模板

3.cd myApp

4.npm run dev:h5

期望行为 启动服务

报错信息
```sh
👽 Taro v1.2.15

开始编译项目 myApp
创建  发现文件  src\app.js
创建  发现文件  src\app.less
创建  发现文件  src\index.html
创建  发现文件  src\pages\index\index.js
创建  发现文件  src\pages\index\index.less


ℹ️  Listening at http://127.0.0.1:10086/

监听文件修改中...

🙅   Failed to compile.

./.temp/app.js
Module build failed (from ./node_modules/_babel-loader@7.1.4@babel-loader/lib/index.js):
Error: Couldn't find preset "es2015" relative to directory "E:\\program\\test"
    at Array.map (<anonymous>)
```

系统信息

Taro v1.2 及以上版本已添加 taro info 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

操作系统: Windows 10
Taro 版本 5.6.0 - D:\nodejs\npm.CMD
Node.js 版本 8.9.4 - D:\nodejs\node.EXE
报错平台 h5
补充信息 
已经反复重新安装taro, 并反复重新install依赖包，依旧报错。

**Comment by ASeR1-ATG** [comment]
oi the one i tried

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ASeR1-ATG** [comment]
ya but it stop on me idk if it's cus i need to do better on mine side

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by luckyadam** [comment]
把 `E:\program\test` 的 babelrc 文件删掉

**Comment by hahazxy199433** [comment]
> 把 `E:\program\test` 的 babel 配置文件删掉

好了。
谢谢。
