### ISSUE TITLE
组件的解构赋值以后，会被 null 值覆盖

### ISSUE THREAD

**Issue by JohannLai** [NervJS/taro#2331]
**问题描述**
组件的解构赋值以后，会被 null 值覆盖

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
render() {
        const { verify = true } = this.props;
        console.log(verify);
```
输出的是 true ， null ， null  ，后面的值都是null
**期望行为**
输出 true

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  macbook
 - Taro 版本  1.2.15
 - Node.js 版本 [ v8.11.13]
 - 报错平台 [ weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
看起来是这个判断有问题
```js
verify = _props$verify === undefined ? true : _props$verify,
```

**Comment by luckyadam** [comment]
确实存在这个问题，因为 Taro 中传入的 prop 默认值是 null，目前版本需要你换种方式来写初始化值了

不过在后续版本中我们会解决这个问题，支持现在的写法

**Comment by JohannLai** [comment]
感谢 🌹

**Comment by Chen-jj** [comment]
@JohannLai Taro v1.2.27-beta.0 后对 props 系统进行了改造，此版本已修复这个问题。

**Comment by JohannLai** [comment]
感谢 @Chen-jj
