### ISSUE TITLE
componentWillMount里面，获取前面页面传来的$router.params后，setState无效

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#2337]
A.js:
`type='返' 

Taro.navigateTo({
      url: '../city/JpCityPick?chooseType=' + type + '&isGuoji=' + this.state.isGuoji,
    })
`

JpCityPick.js:
` chooseType:'xxxxx'

componentWillMount() {
        console.log('$router.params:',this.$router.params)
        let type = this.$router.params.chooseType
        this.setState({
            chooseType: type
        }, () => {
            console.log('componentWillMount type:',this.state.chooseType)
        })
    }`

========================分割线===========================

 console.log('$router.params:',this.$router.params)此处打印正常
期待现象:回调函数里this.state.chooseType值为'返'
实际现象：值为'xxxxx'，没有set上去

微信没问题，支付宝模拟器没问题，支付宝真机不行，componentDidMount也没问题

**Comment by fanlvwen** [comment]
C:\Users\flw>taro -V
� Taro v1.2.13

**Comment by Chen-jj** [comment]
@fanlvwen 复现不了，升级到最新版本后再试试。

或者根据 [debug 指南](https://nervjs.github.io/taro/docs/debug.html#%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%8A%A5%E9%94%99-%E4%BD%86%E6%98%BE%E7%A4%BA%E7%9A%84%E7%BB%93%E6%9E%9C%E4%B8%8D%E5%A6%82%E9%A2%84%E6%9C%9F)，在调用 `setData` 前打 log，看看 setData 的数据是什么，自己调试一下。

如果还有问题，可以提供完整可复现代码给我们看看。
