### ISSUE TITLE
配置相关的问题

### ISSUE THREAD

**Issue by Rannie** [NervJS/taro#2338]
Build 配置
1> 可不可以针对微信，支付宝等不同的小程序目标设置不同的 outputRoot?
2> 可不可以针对不同平台设置不同的环境变量?

文档看了下貌似没提到，希望开发者能给与解答~

**Comment by yuche** [comment]
1: https://nervjs.github.io/taro/docs/config.html
2: https://nervjs.github.io/taro/docs/config-detail.html
