### ISSUE TITLE
taro-components内的picker组件关于异步设定value问题

### ISSUE THREAD

**Issue by mjt412885604** [NervJS/taro#2343]
**问题描述**
taro/packages/taro-components/src/components/picker/index.js， 110行代码，异步设定picker组件的value值，会导致每次打开都是取的上一次的props.value值

**复现步骤**
[复现问题的步骤]
1. 异步获取value，并设定picker的value值
2. 选择事件，默认选中不是异步获取的value，时间

**解决方案**
```js
componentWillReceiveProps (nextProps, props) {
    // 1. 设定异步value值得时候，如果直接在handlePrpos方法内获取props时，是上一次的props，所以会导致每次选定的value都是上一次的value
    // 2. 应该使用的nextProps，更新后的值
    // 修改方案
    // 1. 可以使用 this.handlePrpos(nextProps) 传参的形式
    // 2. 或者将事件添加到队列里 setTimeout(this.handlePrpos, 0)
    // 3. 或者复制后操作 this.props = nextProps

    this.handlePrpos()
  }
```

**期望行为**
希望你们加强一下组件的代码校验规范，一般设定的eslint会报警，组件内缺少很多key的索引值

**Comment by jinjinjin0731** [comment]
1、 taro-components 有单独的 eslint 代码校验配置，你需要安装依赖，之后你会发现没有 eslint 的报错。
2、确实会有这个问题，之后修复。如果你能直接 PR ，那最好不过 :-D

**Comment by mjt412885604** [comment]
我只是抽离了你们一个picker组件源码，可能是我们项目与你们项目eslint配置不一样，不过picker组件缺少一个级联的功能待开发

**Comment by jinjinjin0731** [comment]
嗯，其实多列选择器其实就是一个级联的功能了。 看你怎么去使用。 如果你说的是城市级联，那在 H5 中还是需要自己用多列去实现，因为地址库的 JSON 数据很大。放在这里不太合适。
