### ISSUE TITLE
在最新版本中Taro组件Picker选中的值渲染的是上一个

### ISSUE THREAD

**Issue by freeler** [NervJS/taro#2348]
**问题描述**
在老版本中picker使用正常，
在最新版本中Taro组件Picker选中的是上一次的值。

测试在自己项目以及Taro-UI demo均发现该问题出现。

截图如下：

![image](https://user-images.githubusercontent.com/17817406/53790789-bf47a800-3f62-11e9-9212-6cf6f5349c0b.png)

**复现步骤**
[复现问题的步骤]
1. 打开picker，默认选中的是第一项中国
2. 选中美国，点击确定
3. 再次触发打开picker，picker内选中的是中国
4. 选中巴西，点击确认
5. 再次触发打开picker，picker内选中的是美国

```js
// 这里可以贴代码
  state = {
    selector: ['中国', '美国', '巴西', '日本'],
    multiSelector: [['饭', '粥', '粉'], ['猪肉', '牛肉']],
    selectorValue: 0,
    mulitSelectorValues: [0, 1],
    timeSel: '06:18',
    dateSel: '2018-06-18'
  }
  
    handleChange = e => {
    this.setState({
      selectorValue: e.detail.value
    })
  }

{/* 普通选择器 */}
<View className='panel'>
<View className='panel__title'>普通选择器</View>
<View className='panel__content'>
  <View className='example-item'>
	<Picker mode='selector' range={selector} value={selectorValue} onChange={this.handleChange}>
	  <View className='demo-list-item'>
		<View className='demo-list-item__label'>国家地区</View>
		<View className='demo-list-item__value'>{selector[selectorValue]}</View>
	  </View>
	</Picker>
  </View>
</View>
</View>
```

**期望行为**
1. 打开picker，默认选中的是第一项中国
2. 选中美国，点击确定
3. 再次触发打开picker，picker内选中的是美国
4. 选中巴西，点击确认
5. 再次触发打开picker，picker内选中的是巴西

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [OS: Windows 10]
 - Taro 版本 [v1.2.15]
 - Node.js 版本 [10.15.1]
 - 报错平台 [h5, weapp]

**补充信息**

下载了Taro-UI 的 demo代码，编译运行发现tarojs版本是1.2.8，使用该版本运行正常。
然而升级版本至1.2.13或1.2.15，均会出现上述错乱bug。

**Comment by jinjinjin0731** [comment]
单列问题修复中，近期发版

**Comment by jinjinjin0731** [comment]
不对，你这个像是值的更新问题。 使用你这个 demo 没有复现到你说的问题。  @freeler

**Comment by freeler** [comment]
@jinjinjin0731 我使用的demo是Taro-UI 的demo，在demo中Tarojs版本为1.2.8时是使用正常。除了升级了Tarojs版本至1.2.15其他均没有改动，升级后再H5中会复现问题，运行的picker地址 https://github.com/NervJS/taro-ui/tree/dev/src/pages/form/picker

**Comment by freeler** [comment]
@jinjinjin0731 我把demo的运行环境升级至了1.2.15做的的对比

**Comment by jinjinjin0731** [comment]
@freeler 使用 Demo 没有复现问题啊。你 taro info 一下，看下你的版本依赖信息？

**Comment by freeler** [comment]
@jinjinjin0731 只有在H5中会出现，在小程序中使用正常
版本info:
  Taro CLI 1.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by freeler** [comment]
@jinjinjin0731 Taro 1.2.16版本该问题已得到解决

**Comment by joker-li** [comment]
1.2.16这个bug已经修复了吗？
