### ISSUE TITLE
编程百度小程序运行报错

### ISSUE THREAD

**Issue by anddo** [NervJS/taro#2350]
**问题描述**
原本是用taro开发的微信小程序，最近尝试转百度小程序。编译过程中没有出现错误，启动后会提示lodash的报错

**复现步骤**
启动后就报错

**期望行为**
正常运行

**报错信息**
![qq 20190305171156](https://user-images.githubusercontent.com/1539586/53793944-e3f34e00-3f69-11e9-9f38-c9dfbd2cbe31.jpg)

**系统信息**

 - 操作系统: [Windows 7]
 - Taro 版本 [v.1.2.15]
 - Node.js 版本 [v10.6.0]
 - 报错平台 [swan]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
没有复现，你看看百度开发者工具是不是最新版本，不是的话就更新下

**Comment by anddo** [comment]
@luckyadam 都更新到最新版了。我新建了一个测试项目，只引入了lodash，依然会报错，错误相同。麻烦看下附件项目。
[sample.zip](https://github.com/NervJS/taro/files/2934629/sample.zip)

**Comment by anddo** [comment]
@luckyadam 问题解决了，是因为编译之后 
```
var root = freeGlobal || freeSelf || Function('return this')();
```
变成了
```
var root = freeGlobal || freeSelf || {};
```
