### ISSUE TITLE
关于Taro Router多路径映射问题

### ISSUE THREAD

**Issue by yesvods** [NervJS/taro#2354]
**问题描述**

`pages`目录下的页面组件，对应多个路径时候，需要配置对应的`customRoutes`，由于目前的配置数据结构问题，导致一个组件只能映射一个路径。比如希望`page/index/inex`，映射至`indexA.html`、`indexB.html`、`indexC.html`，需要这样配置：

```js
customRoutes: {
   '/pages/index/index': '/indexA.html',
   '/pages/index/index': '/indexB.html',
   '/pages/index/index': '/indexC.html',
}
```

由于键值不能重复，事实上，上面的配置只能对应`indexC.html`这个路径，其余路径不可访问。

**复现步骤**

1. 在`config/index.js`配置文件配置

```
{
  h5: {
    router: {
      customRoutes: {
         '/pages/index/index': '/indexA.html',
         '/pages/index/index': '/indexB.html',
         '/pages/index/index': '/indexC.html',
      }
    }
  }
}
```

2. `npm run dev:h5`

3. 访问`http://127.0.0.1/indexA.html`

**期望行为**

访问`http://127.0.0.1/indexA.html`，`http://127.0.0.1/indexB.html`,`http://127.0.0.1/indexC.html`，会跳转到`page/index/index`组件声明的页面。

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Mac 10.14.2
 - Taro 版本 v1.2.15
 - Node.js 版本 v10.14.1
 - 报错平台 h5

**补充信息**

`customRoutes`数据结构或许需要变更一下

**Comment by Littly** [comment]
我觉得这不是很合理。一个小程序页面应该只对应一个html，或者说页面地址。否则，如果我们在代码里面写 `Taro.navigateTo({ url: '/pages/index/index' })`，那么实际上展示在浏览器地址栏的，应该是`indexA.html`，`indexB.html`，还是`indexC.html`呢？

**Comment by yesvods** [comment]
小程序一个页面对应一个路径没有问题，`h5`场景下可能需要对应多个映射 @Littly

**Comment by yesvods** [comment]
我们在`h5`场景下会使用，`customNav.forward('indexA.html')` 或者 `customNav.forward('indexB.html')`。

**Comment by yesvods** [comment]
或者说，H5场景我们会在其他地方有多个入口，对应的是同一个页面组件。

**Comment by js-newbee** [comment]
> 或者说，H5场景我们会在其他地方有多个路径入口，对应的是同一个页面组件。

如果是对应同一个页面组件，那加个 url 参数区分下入口就好了嘛？ 你说的多个映射太麻烦了

**Comment by yesvods** [comment]
> > 或者说，H5场景我们会在其他地方有多个路径入口，对应的是同一个页面组件。
> 
> 如果是对应同一个页面组件，那加个 url 参数区分下入口就好了嘛？ 你说的多个映射太麻烦了

这个是业务需求，从技术角度来说也没问题吧。麻烦指的是？

**Comment by yesvods** [comment]
我们目前只能一直停留在`1.2.2`版本，因为这个版本可以支持多路由映射，后面就发生了`breaking change`了，我理解小版本号不应该出现这种情况。

**Comment by Littly** [comment]
目前我们跳页面用的是`Taro.navigateTo`，如果实现了类似于`customNav.forward('indexA.html')`的Api，其他的终端就不好处理了

**Comment by yesvods** [comment]
我们是否可以先抛开导航的问题。目前的问题是需要从不同路径入口进来需要导航到同一个页面组件。 @Littly

**Comment by yohnz** [comment]
> > 或者说，H5场景我们会在其他地方有多个路径入口，对应的是同一个页面组件。
> 
> 如果是对应同一个页面组件，那加个 url 参数区分下入口就好了嘛？ 你说的多个映射太麻烦了

遇到同样的问题，比如，最常见的情况，我要做一个降级方案，如果a.html因为种种原因被微信屏蔽之类的，我希望可以切到b.html。这种情况下url参数就不好用了，因为通常屏蔽的是path。

**Comment by Hardcore0331** [comment]
> 我觉得这不是很合理。一个小程序页面应该只对应一个html，或者说页面地址。否则，如果我们在代码里面写 `Taro.navigateTo({ url: '/pages/index/index' })`，那么实际上展示在浏览器地址栏的，应该是`indexA.html`，`indexB.html`，还是`indexC.html`呢？
是否可以设置一个默认的，或者对应一个数组，默认取第一个；

**Comment by Littly** [comment]
> > 我觉得这不是很合理。一个小程序页面应该只对应一个html，或者说页面地址。否则，如果我们在代码里面写 `Taro.navigateTo({ url: '/pages/index/index' })`，那么实际上展示在浏览器地址栏的，应该是`indexA.html`，`indexB.html`，还是`indexC.html`呢？
> 
> 是否可以设置一个默认的，或者对应一个数组，默认取第一个；

倒是可以实现 但是使用的时候就需要用env变量判断出h5端，再调用api了喔

**Comment by Hardcore0331** [comment]
> > > 我觉得这不是很合理。一个小程序页面应该只对应一个html，或者说页面地址。否则，如果我们在代码里面写 `Taro.navigateTo({ url: '/pages/index/index' })`，那么实际上展示在浏览器地址栏的，应该是`indexA.html`，`indexB.html`，还是`indexC.html`呢？
> > 
> > 
> > 是否可以设置一个默认的，或者对应一个数组，默认取第一个；
> 
> 倒是可以实现 但是使用的时候就需要用env变量判断出h5端，再调用api了喔

可以呀，迫切想升级taro，求支持~

**Comment by ksbaozi** [comment]
请问这个问题解决了吗？
