### ISSUE TITLE
无法获取document.documentElement.scrollTop || window.pageYOffset || document.body.scrollTop

### ISSUE THREAD

**Issue by vurtnr** [NervJS/taro#2356]
**问题描述**
h5端，需要手动实现tab吸顶效果,代码如下：
![image](https://user-images.githubusercontent.com/8241528/53809484-c76a0c80-3f8f-11e9-9593-304ffc2e2d33.png)
三个值永远是0，然后重新init一个空项目，在未在app.js中配置tabbar的情况下一切正常

**复现步骤**
空项目不配置tabbar情况下获取上述三个值其中之一.
同样的项目，app.js中配置tabbar，返回组件，重新获取三个值全部显示为0

**期望行为**
## 可以取到document.documentElement.scrollTop || window.pageYOffset || document.body.scrollTop 三个值中的一个

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOS 10.14.3]
 - Taro 版本 [e.g. v.1.2.12]
 - Node.js 版本 [e.g. v11.2.0]
 - 报错平台 [h5]
![image](https://user-images.githubusercontent.com/8241528/53809723-43645480-3f90-11e9-9f49-3205e8b989c4.png)

**补充信息**
如果有变通的法子，请指导下如何在框架中使用。

**Comment by Littly** [comment]
感谢反馈，确实有这个情况，带 tabbar 的页面结构与平常的不太一样。比如，页面带tabbar的情况下，滚动容器会变成`.taro-tabbar__panel`了。在 Taro 内部暂时是通过比较原始的办法解决：
https://github.com/NervJS/taro/blob/b200a70b0caeb87e1b07d52329e9e1c4edcf92d5/packages/taro-router/src/router/route.tsx#L14-L32
我们后续想个更加优雅的解决办法，避免开发者需要过多地触及Taro内部的细节。

**Comment by vurtnr** [comment]
@Littly 你好，我现在是需要更新还是如何？
