### ISSUE TITLE
mobx array 传给子组件不更新

### ISSUE THREAD

**Issue by ANDEMEN** [NervJS/taro#2358]
**问题描述**
当父组件的 observable 的 array 传递给子组件时，子组件获取到的值不再是 observable 的，且不会更新。

**复现步骤**
```jsx
@observer
class Parent extends Component {
  @observable
  arr = [1, 2, 3];

  @action
  handleClick = () => {
    this.arr = [3, 2, 1];
  };

  render() {
    return (
      <View>
        {this.arr.join(',')}
        <Child arr={this.arr} />
        <Button onClick={this.handleClick}>按钮</Button>
      </View>);
  }
}

@observer
class Child extends Component {
  render() {
    const { arr } = this.props;

    return <View>{arr.join(',')}</View>;
  }
}

```

**期望行为**
期望两者都输出都改变，但子组件却没有更新。

**Comment by luckyadam** [comment]
Duplicate of #2266

**Comment by chankamlam** [comment]
这个问题没有那么简单不是一个slice()可以解决，因为还可能涉及到多层级对象，比如
`
 obj:{
       arr:[{name:'a'},{name:'b'}]
   }
`
你最好用mobx的toJS解决
<img width="342" alt="屏幕快照 2019-04-16 下午10 22 58" src="https://user-images.githubusercontent.com/9009522/56218161-0dd67f00-6097-11e9-922a-75879b66754d.png">
<img width="363" alt="屏幕快照 2019-04-16 下午10 23 15" src="https://user-images.githubusercontent.com/9009522/56218172-116a0600-6097-11e9-934a-bba193943ae9.png">
<img width="410" alt="屏幕快照 2019-04-16 下午10 23 39" src="https://user-images.githubusercontent.com/9009522/56218181-14fd8d00-6097-11e9-9ea1-a27a8032b3ee.png">
