### ISSUE TITLE
小程序转h5：样式表中image标签未转换

### ISSUE THREAD

**Issue by yantingxi** [NervJS/taro#2360]
*问题描述**
如题

**复现步骤**
[复现问题的步骤]
源码：
![image](https://user-images.githubusercontent.com/30825361/53852257-5dd41780-3ffc-11e9-9647-a1b80d7bae81.png)

![image](https://user-images.githubusercontent.com/30825361/53852271-69274300-3ffc-11e9-8c98-9954fc1cc4c4.png)

转换结果：
![image](https://user-images.githubusercontent.com/30825361/53852291-852ae480-3ffc-11e9-87a1-7cd21dd939e1.png)
![image](https://user-images.githubusercontent.com/30825361/53852300-8fe57980-3ffc-11e9-840a-30484ab524a3.png)
**期望行为**
样式文件中的image小程序标签应修改为Img

**系统信息**
Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v11.10.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm

**补充信息**
标签进行转换后， 样式表没有对应更新

**Comment by luckyadam** [comment]
我们不会处理样式中的元素选择器，样式最好用类名控制
