### ISSUE TITLE
两张图片同名，然后页面引用的相对路径也相同时，打包出来的文件路径会相同，从而导致图片只有一个生效。(h5dev环境)

### ISSUE THREAD

**Issue by imalextu** [NervJS/taro#2362]
**问题描述**
两张图片同名，然后页面也面引用的相对路径也相同时，会导致图片只有一个生效。(h5dev环境)

**复现步骤**
[复现问题的步骤]
1.分别在receive页面以及share页面引入同名的badge.png
![image](https://user-images.githubusercontent.com/45706079/53852663-c53e9700-3ffd-11e9-9c41-435db08ff691.png)
![image](https://user-images.githubusercontent.com/45706079/53852857-64fc2500-3ffe-11e9-9cfd-483587ba30fd.png)

2.图片打包出来后的路径会一样，都是http://127.0.0.1:10086/static/images/badge.png
继而导致两张图片只有一张生效。
3.是否能将图片的打包路径应该加上page的这一层啊，类似http://127.0.0.1:10086/static/receive/images/badge.png和http://127.0.0.1:10086/static/share/images/badge.png。或者加hash啥的。现在我暂时通过文件名加前缀来解决问题。

**Comment by Littly** [comment]
**建议修改图片名称避免重名**。

h5下，打包后不再保留原始的文件路径，会把图片统一放到一个指定的路径，所以如果图片同名，又被塞到同个路径之下，就会出现覆盖的情况。如果对于把图片统一放置到一个路径的行为不满意，也可以参考[文档](https://nervjs.github.io/taro/docs/config-detail.html#h5imageurlloaderoption)进行修改。

**Comment by Littly** [comment]
Duplicate of #1402

**Comment by imalextu** [comment]
知晓，感谢。
