### ISSUE TITLE
style support array

### ISSUE THREAD

**Issue by Timson020** [NervJS/taro#2363]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

**问题描述**
style 不支持数组

**复现步骤**
[复现问题的步骤]
1. see code

```js
// 这里可以贴代码
<View style={[styles.container, styles.otherStyle]}>
<Text>xxxx</Text>
</View>

const styles = {
  container: {
     color: 'red'
  },
 otherStyle: {
    backgroundColor: 'blue'
 }
}
```

**期望行为**
数组合并样式

**报错信息**
不支持 数组

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
React 和 H5 的底层 Nerv 的 style 都是不支持数组的，你可以用 object spread 语法做一样的事情，表现力还更强一些。
https://github.com/facebook/react/issues/2239
