### ISSUE TITLE
Taro  调用Taro.showModal 后， 如何调用方法销毁。

### ISSUE THREAD

**Issue by youyou0101** [NervJS/taro#2364]

**Comment by Garfield550** [comment]
Modal 当然是要用户点击确定或取消之后才能销毁的。
而且小程序官方也没有提供 API 形式的功能
![image](https://user-images.githubusercontent.com/3471836/53864921-b15c5a80-4028-11e9-8e39-f4d81ebf49da.png)

**Comment by youyou0101** [comment]
好的 但看源码是有hide()方法 只是没有放出来（这个是在taro-h5看的）， 会出现一种情况： Modal显示后，点击返回键，modal 一直存在。

**Comment by youyou0101** [comment]
`key: "hide",
    value: function hide() {
      var _this3 = this;

      setTimeout(function () {
        _this3.el.style.opacity = '0';
        setTimeout(function () {
          _this3.el.style.display = 'none';
        }, 200);
      }, 0);
    }`
