### ISSUE TITLE
Mobx的典型用法@computed get在小程序里面表现有问题

### ISSUE THREAD

**Issue by czy0729** [NervJS/taro#2365]
**问题描述**
Mobx的典型用法@computed get在小程序里面表现有问题

```js
// --------A写法--------
// userStore.js
@observable userInfo = {
  access_token: ''
}
@computed get isLogin() {
  return !!this.userInfo.access_token
}

// page.js
if (!this.props.userStore.isLogin) {
  return <Login />
}
return <View>something</View>

// --------B写法--------
// userStore.js
@observable userInfo = {
  access_token: ''
}
isLogin() {
  return !!this.userInfo.access_token
}

// page.js
if (!this.props.userStore.isLogin()) {
  return <Login />
}
return <View>something</View>
```

**期望行为**
通常使用Mobx都是使用A写法, access_token为请求后拿到的数据.
流程是 this.props.userStore.isLogin 先是false 再到 true.
H5端和RN端都是正常情况, 能显示View.
但是在小程序里面, 虽然console.log打印出来的结果符合预期,
但是实际上永远只会显示Login, B写法表现正常, 但是这样的写法Mobx的使用意义大减

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.1]
 - Taro 版本 [1.2.15]
 - Node.js 版本 [11.10.0]
 - 报错平台 [weapp]

**补充信息**
我觉得是静态方法导致他没刷新?

**Comment by nanjingboy** [comment]
@czy0729 请将 page.js 中代码改成以下样子：

```js
const { userStore: { isLogin } } = this.props;
if (!isLogin) {
  return <Login />
}
return <View>something</View>
```

具体原因应该是小程序编译器对对象序列化的问题，另外这些注意事项已经在文档中明确指出了：
https://nervjs.github.io/taro/docs/mobx.html 

<img width="814" alt="2019-03-08 11 47 20" src="https://user-images.githubusercontent.com/1390888/54012821-273ffd80-41b2-11e9-9a19-b400b5b58771.png">

**Comment by yuche** [comment]
在 1.3 或 1.4 版本 （取决于这个功能的稳定性） Taro 自己实现 props 通信系统，到时就不会有这个限制。

**Comment by czy0729** [comment]
@nanjingboy 非常感谢
还想补充一句, 我在React里面写通常不使用inject, 而是直接import store进来直接使用, 这种做法在小程序里面现在是行不通的吧?

**Comment by nanjingboy** [comment]
@czy0729 可以不用 inject 的
