### ISSUE TITLE
请问 taro 支持开发微信小程序插件吗？

### ISSUE THREAD

**Issue by zoux** [NervJS/taro#2366]
目前未找到开发微信小程序插件的官方相关文档和示例~

**Comment by luckyadam** [comment]
这个还在计划支持中

**Comment by tourze** [comment]
关注这个，这个挺有需要的

**Comment by zhangfu-git** [comment]
Taro v1.3.0-beta.3初始化一个插件目录，在微信开发工具打开报`VM94:5 未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。`, 
![image](https://user-images.githubusercontent.com/19772048/58143275-cf774580-7c7c-11e9-9709-0e8cf66fffe9.png)
miniprogram目录的plugin为空？

**Comment by shenghanqin** [comment]
你看看，最新版应该支持了的。
