### ISSUE TITLE
onClick监听函数的传值变了？

### ISSUE THREAD

**Issue by soymikey** [NervJS/taro#2371]
为什么之前的onClick监听函数 可以 这样传值onClick={this.getValue.bind(this,value)} 就可以得到value 的值， 但是现在要在函数里 这样e.currentTarget.dataset.eTapAA 才能得到value的值？

**Comment by Chen-jj** [comment]
CLI 和依赖都升级到最新版后试试

**Comment by AKACC** [comment]
同样遇到这个问题，onClick传参只能拿到一个事件参数，其他都是undefined

**Comment by danieltao1993** [comment]
我也遇到了类似的问题：

1. 打包微信小程序后，使用onConfirm传递给子组件的()=>{}箭头函数子组件无法获得并调用    
2. 打包swan百度小程序后，找不到props传递给子组件confirm事件函数   
![图片](https://user-images.githubusercontent.com/15671438/54179719-98462480-44d4-11e9-9603-b316ff831dbe.png)  

3. 代码地址：    
    https://github.com/BDFE/taro-typescript/blob/master/src/components/wraper/index.tsx

**Comment by AKACC** [comment]
> 我也遇到了类似的问题：
> 
> 1. 打包微信小程序后，使用onConfirm传递给子组件的()=>{}箭头函数子组件无法获得并调用
> 2. 打包swan百度小程序后，找不到props传递给子组件confirm事件函数
>    ![图片](https://user-images.githubusercontent.com/15671438/54179719-98462480-44d4-11e9-9603-b316ff831dbe.png)
> 3. 代码地址：
>    https://github.com/BDFE/taro-typescript/blob/master/src/components/wraper/index.tsx

JSX用箭头函数会有问题，试试直接用onConfirm={this.confirmLoc}来调用看看

**Comment by soymikey** [comment]
我感觉是我更新taro cli 之后出现的问题 现在版本 👽 Taro v1.2.15；

 
![image](https://user-images.githubusercontent.com/37310671/54403047-9f09ad00-4709-11e9-96b0-624653692096.png)

暂时只能这样。
支付宝要去 e.currentTarget.dataset.eOnTapAA 这里面拿值
小程序要去 e.currentTarget.dataset.eTapAA 这里面拿值

**Comment by Chen-jj** [comment]
@soymikey CLI 和依赖版本保持一致。1.2.15 事件是正确的，不存在取不到参数的情况。

**Comment by Chen-jj** [comment]
@danieltao1993 @AKACC 同样地 CLI 和依赖都升级最新版后试试，我在 1.2.17 尝试传箭头函数是正常的。

```js
// 父组件
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Child from '../../components/child/child'

export default class PageView extends Component {

  handleClick () {
    console.log('handleClick args: ', ...arguments)
  }

  render() {
    return (
      <View>
        <Child onClick={(a, b, e) => {
          console.log('in: ', a, b, e)
          this.handleClick(a, b, e)
        }}
        />
      </View>
    )
  }
}
```

```js
// 子组件
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

import './child.scss'

export default class Child extends Component {
  handlerClick () {
    console.log('on fn: ', this.props.onClick)
    console.log(this.props.onClick(...arguments))
  }

  render() {
    return (
      <View>
        <View
          style='border: 1px solid blue;color: blue;'
          onClick={this.handlerClick.bind(this, 1, 2)}
        >
          Button 1
        </View>
      </View>
    )
  }
}
```

**Comment by soymikey** [comment]
更新了cli 和项目依赖 到1.2.17 ， 可以了

**Comment by danieltao1993** [comment]
![图片](https://user-images.githubusercontent.com/15671438/54525709-c71a3a00-49af-11e9-9034-18aaa9860f8a.png)
![图片](https://user-images.githubusercontent.com/15671438/54525774-e9ac5300-49af-11e9-8bef-29e61071bc11.png)

这样在百度小程序里，怎么都拿不到props传入的函数

**Comment by Chen-jj** [comment]
@danieltao1993 不要打印，直接调用即可

**Comment by danieltao1993** [comment]
@Chen-jj 
![图片](https://user-images.githubusercontent.com/15671438/54527841-1b281d00-49b6-11e9-95df-659d8caf8676.png)
父组件传入的showPanel是TRUE，但是当前组件setState之后有时候会变成false,不知道是不是setState有问题
![图片](https://user-images.githubusercontent.com/15671438/54527931-59bdd780-49b6-11e9-9aab-3d6f87e45fb6.png)

**Comment by Chen-jj** [comment]
@danieltao1993 [debug指南](https://nervjs.github.io/taro/docs/debug.html#%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%8A%A5%E9%94%99-%E4%BD%86%E6%98%BE%E7%A4%BA%E7%9A%84%E7%BB%93%E6%9E%9C%E4%B8%8D%E5%A6%82%E9%A2%84%E6%9C%9F)
