### ISSUE TITLE
#Taro 代码与微信小程序代码混写# 怎么向微信小程序的 template组件传入 bindtap 方法呢？

### ISSUE THREAD

**Issue by harrydengchao** [NervJS/taro#2374]
**问题描述**
#Taro 代码与微信小程序代码混写# 怎么向微信小程序的 template组件传入 bindtap 方法呢？
* 在 Taro 中 `<import src="xx/xx/a.wxml">`
* 在 Taro 中 `<template is="a" />`
* a.wxml 中有绑定 tap 事件：bindtap="handleInput"
* 在 Taro 中怎么向 a.wxml 传入 handleInput 方法？

**复现步骤**
```html
<!-- a.wxml -->
<template name="a">
    <button bindtap="handleInput">测试</button>
</template>
```

```jsx
// Taro component
<View>
    <import src="xx/xx/a.wxml" />
    <template is="a" />
</View>
```

**期望行为**
在 Taro 中向 微信小程序 template 传入 handleInput 方法，使得 a.wxml 中的 bindtap 事件可以正确响应

**报错信息**

Component "pages/index/index" does not have a method "handleInput" to handle event "tap".
![image](https://user-images.githubusercontent.com/13941171/53870746-c5f31f80-4035-11e9-8c2a-a5a63f43d8c9.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.15]
 - Node.js 版本 [e.g. v10.13.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by harrydengchao** [comment]
个人感觉，这问题目前无解。因此自己改为了，用到这个场景的页面，用微信小程序写。没有用到这个场景的部分，用 Taro 写。

**Comment by luckyadam** [comment]
目前确实无解

**Comment by harrydengchao** [comment]
感谢您的回复

**Comment by febobo** [comment]
在你的Taro component页面加一个<view style={{display: none}} onClick={你要添加的方法}/> 目的是让你的方法被编绎

**Comment by harrydengchao** [comment]
@febobo  感谢你的回复。  如上你的方案，我理解的是，只能在 Taro component 中编译方法。 无法解决向 Taro component 中引用的 wechat template 传递方法的问题。  不知道我理解的正确否？

**Comment by febobo** [comment]
@harrydengchao 你就当成数据传过去， 参考 wxparse事件处理
