### ISSUE TITLE
h5版本，Taro.request 获取不到 Cookie 值

### ISSUE THREAD

**Issue by youyou0101** [NervJS/taro#2377]
服务器返回的 HTTP Response Header，里有Cookie， response返回的header里面获取不到cookies值。

h5返回的header： {"cache-control":"no-cache","content-type":"application/json;charset=UTF-8","expires":"Thu, 01 Jan 1970 00:00:00 GMT","pragma":"No-cache"}
后台设置的Header:
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://0.0.0.0:10086
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Cookie: JSESSIONID=BCF18C8FB10ABE8D241BC5969A47A88E
Date: Thu, 07 Mar 2019 03:11:55 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: No-cache
Transfer-Encoding: chunked
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers

小程序中能获取。

**Comment by JohannLai** [comment]
![image](https://user-images.githubusercontent.com/10769405/53935799-af56d200-40e2-11e9-861d-bb0e9edb243c.png)
@youyou0101
