### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by MakerGYT** [NervJS/taro#2387]
**问题描述**
[问题描述：编译预览h5时出现错误，但没有影响最终效果]

**复现步骤**
[复现问题的步骤]
1. ``npm run dev:h5``
[或者可以直接贴源代码，能贴文字就不要截图]

**报错信息**
```js
Compiling...(node:3564) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/data/taro/myApp/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
(node:3564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
👽 Taro v1.2.16

  Taro CLI 1.2.16 environment info:
    System:
      OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/lib/nodejs/node-v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.8.0 - /usr/local/lib/nodejs/node-v10.15.0/bin/npm
    npmPackages:
      @tarojs/components: 1.2.16 => 1.2.16 
      @tarojs/plugin-babel: 1.2.16 => 1.2.16 
      @tarojs/plugin-csso: 1.2.16 => 1.2.16 
      @tarojs/plugin-uglifyjs: 1.2.16 => 1.2.16 
      @tarojs/router: 1.2.16 => 1.2.16 
      @tarojs/taro: 1.2.16 => 1.2.16 
      @tarojs/taro-alipay: 1.2.16 => 1.2.16 
      @tarojs/taro-h5: 1.2.16 => 1.2.16 
      @tarojs/taro-swan: 1.2.16 => 1.2.16 
      @tarojs/taro-tt: 1.2.16 => 1.2.16 
      @tarojs/taro-weapp: 1.2.16 => 1.2.16 
      @tarojs/webpack-runner: 1.2.16 => 1.2.16 
      eslint-config-taro: 1.2.16 => 1.2.16 
      eslint-plugin-taro: 1.2.16 => 1.2.16 
      nervjs: ^1.3.9 => 1.3.12

**Comment by Littly** [comment]
在opn包里面报的错，结合你的操作系统来看，应该是打开预览链接时找不到默认浏览器了...
