### ISSUE TITLE
从A页面使用Taro.navigateTo跳转到B页面后, 会执行A和B两个页面的componentDidMount

### ISSUE THREAD

**Issue by magicbing** [NervJS/taro#2388]
**问题描述**
从A页面使用Taro.navigateTo跳转到B页面后, 会执行A和B两个页面的componentDidMount(其他的生命周期也会执行, 只用到了componentDidMount);
redirectTo没有问题, 但是有的页面需要用返回按钮

**复现步骤**
[复现问题的步骤]
1. 在A页面
2. Taro.navigateTo(pages/B/index)
3. 此时会执行A和B页面的所有方法

**系统信息**
👽 Taro v1.2.11

  Taro CLI 1.2.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\app\nodejs10\node.EXE
      Yarn: 1.13.0 - D:\app\yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\app\nodejs10\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
我感觉是A页面没消失, 而且执行了

**Comment by luckyadam** [comment]
请问是 H5 么

**Comment by magicbing** [comment]
> 请问是 H5 么

是H5

**Comment by Littly** [comment]
请先把taro-cli和项目依赖项都升级到最新，再看看有没有复现问题~

**Comment by magicbing** [comment]
> 请先把taro-cli和项目依赖项都升级到最新，再看看有没有复现问题~

升级到了1.2.16
第一次Taro.navigateTo A页跳转到B解决了, 没有在B页执行A页的方法;
但是 从B页面在从tarbar返回A页 -> 再Taro.navigateTo跳转到B页;
这时候还是有多次调用, 重复上个步骤n次就会执行页面所有方法n次

写了个demo https://github.com/magicbing/taro-bug-demo.git

**Comment by Littly** [comment]
找到原因了，路由中对于redirect的页面处理有误，下个版本修复。

**Comment by hblz** [comment]
快点发版啊啊
