### ISSUE TITLE
小程序转taro， taro导入为es6语法，build h5后报错

### ISSUE THREAD

**Issue by yantingxi** [NervJS/taro#2393]
**问题描述**
如题

**复现步骤**
[复现问题的步骤]
编译前
[image](https://user-images.githubusercontent.com/30825361/54016096-d1248780-41bc-11e9-9371-f9457e2526c0.png)

编译后
![image](https://user-images.githubusercontent.com/30825361/54016136-f1544680-41bc-11e9-9250-0f873e7b359d.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

![image](https://user-images.githubusercontent.com/30825361/54016158-ffa26280-41bc-11e9-98d5-1967f0507aa6.png)
**系统信息**
👽 Taro v1.2.13

  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v11.10.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
    npmPackages:
      @tarojs/cli: ^1.2.15 => 1.2.15
**补充信息**
import 与 module.exports 不可共存

**Comment by Littly** [comment]
把module.exports换成es6的namedExports再看看

**Comment by Littly** [comment]
> 把module.exports换成es6的namedExports再看看

taro后续可能有功能会依赖到静态的import/export特性，所以写代码时统一使用es6的import/export语法吧~

**Comment by yantingxi** [comment]
小程序开发不支持es6的模块导出吧？

**Comment by yuche** [comment]
taro 会把你的语法转一遍的

**Comment by yantingxi** [comment]
我截图的编译后结果就是taro的代码

**Comment by yantingxi** [comment]
是我哪里配置不对么

**Comment by Littly** [comment]
你写的时候使用import/export就好了
