### ISSUE TITLE
Taro && dva && typescript , 编译h5失败

### ISSUE THREAD

**Issue by daijiaoluoxinghui** [NervJS/taro#2398]
**问题描述**

   npm run build:weapp 没有问题。
然后 npm run build:h5 会通不过

尝试过
1、首先检查config/index.js 是否已加入配置 esnextModules: ['taro-ui']
2、删掉.temp文件夹重新npm run dev
3、删除node_modules文件夹重新安装依赖

安装的依赖：
	"dependencies": {
		"@shymean/mock-server": "^1.1.1",
		"@tarojs/async-await": "1.2.16",
		"@tarojs/components": "1.2.16",
		"@tarojs/redux": "1.2.16",
		"@tarojs/router": "1.2.16",
		"@tarojs/taro": "1.2.16",
		"@tarojs/taro-alipay": "1.2.16",
		"@tarojs/taro-h5": "1.2.16",
		"@tarojs/taro-swan": "1.2.16",
		"@tarojs/taro-weapp": "1.2.16",
		"dva-core": "^1.4.0",
		"dva-loading": "^2.0.6",
		"nervjs": "^1.3.5",
		"promise-polyfill": "^8.1.0",
		"react": "^16.6.3",
		"redux": "^4.0.0",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0",
		"taro-ui": "^1.5.1",
		"tslint": "^5.11.0",
		"tslint-react": "^3.6.0"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "1.2.16",
		"@tarojs/plugin-csso": "1.2.16",
		"@tarojs/plugin-less": "1.2.16",
		"@tarojs/plugin-sass": "1.2.16",
		"@tarojs/plugin-uglifyjs": "1.2.16",
		"@tarojs/webpack-runner": "1.2.16",
		"@types/react": "^16.4.6",
		"@types/webpack-env": "^1.13.6",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"eslint": "^4.19.1",
		"eslint-config-taro": "1.2.16",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "1.2.16",
		"eslint-plugin-typescript": "^0.12.0",
		"typescript": "^3.0.1"
	}

**期望行为**
h5编译能通过

**报错信息**

创建  发现文件  src\shopping\pages\shopping.less
创建  发现文件  src\shopping\pages\sure_order.tsx
✅  Compiled successfully!

- Compiling...[BABEL] Note: The code generator has deoptimised the styling of "E:/upTaro/.temp/components/ec-canvas/echarts.js" as it exceeds the max of "500KB".
�   Failed to compile.

./.temp/app.js
Module not found: Can't resolve '@tarojs/redux-h5' in 'E:\upTaro\.temp'
**系统信息**

 - 操作系统: Windows 7
 - Taro 版本 [e.g. v.1.2.16
 - Node.js 版本  Node: 8.15.0
 - 报错平台 [h5]

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/54087123-da634f00-438a-11e9-9cf0-37ff1d70d379.png)
安装这个包

**Comment by daijiaoluoxinghui** [comment]
貌似是 cnpm i 和 npm i的问题。之前都是cnpm i 的，装了  "@tarojs/redux-h5"，还是报一堆没装。改用npm i 以后，Compiled with warnings,至少不会编译失败了
