### ISSUE TITLE
如何修改h5 JavaScript与CSS输出路径

### ISSUE THREAD

**Issue by ninetowns** [NervJS/taro#2402]
**问题描述**
目前打包后的路径都是在跟目录下的js和css文件夹，如果改变输出位置，比如生成再pages/js和pages/css下

**期望行为**
可以修改默认输出路径

**系统信息**
操作系统: [Windows 10]
Taro 版本 [v.1.2.7]
Node.js 版本 [v8.9.0]
报错平台 [h5]

**Comment by Littly** [comment]
请注意参考文档，如果下面这些配置项还无法满足你的需求，你还可以用webpackChain配置项

https://nervjs.github.io/taro/docs/config-detail.html#h5output
https://nervjs.github.io/taro/docs/config-detail.html#h5chunkdirectory
https://nervjs.github.io/taro/docs/config-detail.html#h5minicssextractpluginoption

**Comment by tcitds1** [comment]
**之前我也在找这个问题的解决方法，没有现成的例子，后面根据文档配置了可用的指定目录输出js和css文件的方法，希望可以给后面配置文件的同学做些参考，附一下图**
![image](https://user-images.githubusercontent.com/17925368/76594535-6119b180-6534-11ea-8230-d36f002d7c40.png)

**Comment by wangrui97** [comment]
如何配置h5 JavaScript与CSS可通过不同cdn域名下访问？
