### ISSUE TITLE
父级state的改变影响Swiper组件的index切换 

### ISSUE THREAD

**Issue by catXiaoXiao** [NervJS/taro#2404]
**问题描述**

父级state的改变影响其子集Swiper组件的current下标
swiper切换不会影响tabs

**期望行为**

父级组件和Swiper组件互不影响

**系统信息**

Taro 1.2.4
taro-ui 2.0.0

**Comment by SzHeJason** [comment]
这个问题 不属于 Taro-UI 所以我把 issue 转到 Taro 了, @jinjinjin0731

**Comment by jinjinjin0731** [comment]
已经解决了。 忘记关闭，更新到最新版本即可
