### ISSUE TITLE
支付宝小程序 my.createSelectorQuery(...).in is not a function

### ISSUE THREAD

**Issue by soymikey** [NervJS/taro#2406]
// console.log 里面的报错
TypeError: my.createSelectorQuery(...).in is not a function
    at index.js:2297
    at Array.forEach (<anonymous>)
    at componentTrigger (index.js:2295)
    at index.js:3416
    at af-appx.worker.ide.min.js:7
    at Array.forEach (<anonymous>)
    at Object.e (af-appx.worker.ide.min.js:7)
    at ut.invokeCallback (af-appx.worker.ide.min.js:7)
    at r (af-appx.worker.ide.min.js:7)
    at ut.onMessage (af-appx.worker.ide.min.js:7)
=====================================================
编译成支付宝小程序后
  if (key === 'componentDidMount') {
    if (component['$$refs'] && component['$$refs'].length > 0) {
      var _refs = {};
      component['$$refs'].forEach(function (ref) {
        var target;
        var query = my.createSelectorQuery().in(component.$scope); // 这一段代码报错
        if (ref.type === 'dom') {
          target = query.select("#".concat(ref.id));
          if ('refName' in ref && ref['refName']) {
            _refs[ref.refName] = target;
          } else if ('fn' in ref && typeof ref['fn'] === 'function') {
            ref['fn'].call(component, target);
          }
        }
      });
      component.refs = Object.assign({}, component.refs || {}, _refs);
    }
  }

这是什么原因呢？

**Comment by Chen-jj** [comment]
等支付宝方面发版本，他们预计月中支持

**Comment by yuwanlin** [comment]
现在还没有支持吧？小程序开发者工具1.5.2， taro2.0

**Comment by Chen-jj** [comment]
@yuwanlin 支付宝何来 v1.5.2

**Comment by yuwanlin** [comment]
> @yuwanlin 支付宝何来 v1.5.2

不好意思，我的意思的是钉钉小程序现在还不支持ref？钉钉小程序开发者工具1.5.2， taro2.0。没看到相关issue，就在这里问了。看了钉钉小程序的文档，也是没有ref的。

**Comment by Chen-jj** [comment]
@Chen-jj 钉钉没测过，你可以先试试

**Comment by yuwanlin** [comment]
> @Chen-jj 钉钉没测过，你可以先试试

测了不行的，三种方式都不行。

taro没有直接编译到钉钉小程序的npm script，所以只有通过yarn dev:alipay编译成支付宝小程序代码的，ref的代码编译后报错`my.createSelectorQuery(...).in`，和这个issue一样，我打印了`my.createSelectorQuery`是有值的。

支付宝小程序文档搜索ref能搜到，钉钉小程序文档搜索ref搜不到内容。

**Comment by Chen-jj** [comment]
@yuwanlin 试试原生写法，是否有 in 方法。没有就没办法了，估计他们基础库不是一波人做所以没同步。
