### ISSUE TITLE
H5 Swiper组件渲染Swiper-Item宽度异常

### ISSUE THREAD

**Issue by Limuyang1013** [NervJS/taro#2408]
Swiper组件渲染出来的Swiper-Item宽度为359px，导致页面样式无法居中，taro是最新版本

**Comment by zzuu666** [comment]
遇到了同样的问题。
相似问题 #1937 #1914 
请尽快修复 Taro 版本 1.2.17 版本中仍存在此问题。

**Comment by jinjinjin0731** [comment]
这个问题是一个热更新异常问题。 体验问题正在修复。你们可以试一下 Build 之后在真机上查看，是没有问题的。   这个问题也是有点怪异，与第三方的插件有关，正计划近期 fix

**Comment by cddsgtc** [comment]
@jinjinjin0731 这个问题我遇到了，而且在非taro的[swiper4X+](https://www.swiper.com.cn/)中也遇到了。异步不异步不知道，但是确实存在。
目前比较勉强的结局方法是在页面或者组件mounted之后使用settimeout,让该组件在下一轮垂询种展现就正常了。

**Comment by CraKeyBoy** [comment]
目前该问题又复现了。taro 最新版 1.3.12.

**Comment by CherishLyf** [comment]
Taro 1.3.19 宽度计算也有问题，不知道问题在哪

**Comment by ManiuLtd** [comment]
@jinjinjin0731 使用taro1.3.20最新版本swiper的宽度问题依然存在

**Comment by rwgao** [comment]
@jinjinjin0731 使用taro1.3.25 最新版swiper的宽度问题依然存在

**Comment by ManiuLtd** [comment]
现在已经是2.0版本了，这个问题依然存在
