### ISSUE TITLE
1.2.17版本的scroll-view问题

### ISSUE THREAD

**Issue by lmf** [NervJS/taro#2410]
**问题描述**
scroll-view在onScroll事件回调中如果调用setState，则无法滑动

**复现步骤**
[复现问题的步骤]
1. 见问题描述

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.17 => 1.2.17 
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-less: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.9 => 1.3.9 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by lmf** [comment]
看了下scroll-view代码，太搞笑了，不测试的吗，onScroll回调中调用setState会触发scroll-view的update，然后就重新初始化scroll了……

**Comment by jinjinjin0731** [comment]
已回退，有点东西落了。非常抱歉。 暂时 taro-components 库引用 1.2.16 的吧

**Comment by lixsh8** [comment]
@jinjinjin0731 现在h5还不能使用scroll-view吗？那监听window.scroll事件又不执行那不是没法做滚动加载什么的了,代码如下版本v.1.2.13
componentDidMount() {
    // scroll事件不会执行
    window.addEventListener(
      "scroll",
      function() {
        console.log('scroll');
       
      }.bind(this),
      false
    );
 }

**Comment by jinjinjin0731** [comment]
@lixsh8  当然可以用。 1.2.17 的有问题，你的 1.2.13不受影响。 window.scroll 是原生事件，不执行多半你写的有问题

**Comment by lmf** [comment]
> 已回退，有点东西落了。非常抱歉。 暂时 taro-components 库引用 1.2.16 的吧

1.2.16在h5下给scrollTop设置成空字符串的时候（取消给scroll-view手动设置的scrollTop），会自动滚动到顶部，在swan小程序下没有这个问题， @jinjinjin0731 能否帮忙看下原因

**Comment by jinjinjin0731** [comment]
@lmf  h5 上么。晚点看下。

**Comment by jinjinjin0731** [comment]
@lmf  这个问题已提交修复

**Comment by lmf** [comment]
> @lmf 这个问题已提交修复

@jinjinjin0731 就说我改完那个明显的问题没有修复……  辛苦
