### ISSUE TITLE
taro 1.2.17 条件渲染时只能写一个else if

### ISSUE THREAD

**Issue by msj0906** [NervJS/taro#2415]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

**问题描述**
taro 1.2.17 条件渲染时只能写一个else if，多个else if 条件渲染时编译成小程序报错

**复现步骤**
[复现问题的步骤]
render() {
    let {checkId} = this.props
    let poupBox = null
    if (`${checkId}` === '1') {
      poupBox = <View>
                  <View className='btn'>免费注册</View>
                </View>
    } else if (`${checkId}` === '2') {
      poupBox = <View>
              <View className='tips'>此文章仅专业投资者可见</View>    
      </View>
    } else if (`${checkId}` === '3') {
      poupBox = <View>
                  <View className='btn'>登录/注册</View>
                </View>
    }
    return (
      <View>
        {checkId
          && <View className="checkIdPoup">
              {poupBox}
            </View>
        }
      </View>
    )
  }

**报错信息**

<img width="618" alt="WeChatfbddb5dc4725547c988d63bb70db2297" src="https://user-images.githubusercontent.com/48462049/54169639-8487c780-44ae-11e9-8a4b-1751a61dd945.png">

**系统信息**

 - 操作系统: 微信编辑器
 - Taro 版本1.2.17
 - Node.js 版本 v11.2.0
 - 报错平台 weapp

**Comment by yuche** [comment]
麻烦写一下真的代码，并且注意好缩进，内容不完整不如不贴

**Comment by msj0906** [comment]
> 麻烦贴一下真的代码，并且注意好缩进，内容不完整等于没有内容
import Taro, { Component } from '@tarojs/taro'
import {View, Image} from '@tarojs/components'
import './checkIdPoup.scss'
import rightIcon from '../../../assets/img/rightIcon.png'

export default class CheckIdPoup extends Component {
constructor(props) {
super(props)
this.state = {
downloadUrl:false,
}
}

render() {
let {checkId} = this.props
let {downloadUrl} = this.state
let poupBox = null
if (${checkId} === '1') {
poupBox = 
加入会员可浏览文章内容
免费注册

} else if (${checkId} === '2') {
poupBox = 
此文章仅专业投资者可见
{!downloadUrl && 下载App了解更多相关信息}
{downloadUrl
&& 

下载地址已复制
请在手机浏览器中打开并下载

}

} else if (${checkId} === '3') {
poupBox = 
此文章仅专业投资者可见
登录/注册

}
return (

{checkId
&& 
{poupBox}

}

)
}
}
![image](https://user-images.githubusercontent.com/48462049/54171352-ffec7780-44b4-11e9-8e0a-5f0b34ffe50c.png)

**Comment by yuche** [comment]
用三个 "```" 包住前后代码才能有缩进，你现在 JSX 标签还是丢了，如果不行就去：
https://gist.github.com/

**Comment by nevernet** [comment]
不支持在render里面写`if`吧

**Comment by beehoo** [comment]
有同样问题，之前版本是好的，升级1.2.17之后报错了
```
render () {
    let content = null
    const current = this.state.current
    if (current === 0) {
        content = <Home />
    } else if (current === 1) {
        content = <Goods />
    } else if (current === 2) {
        content = <Order />
    } else if (current === 3) {
        content = <Cart />
    }
    ...
}
```

**Comment by zzg19901210** [comment]
![image](https://user-images.githubusercontent.com/8346932/56205571-c17e4580-607c-11e9-9372-88d7a1c8f736.png)
![image](https://user-images.githubusercontent.com/8346932/56205582-cf33cb00-607c-11e9-91cf-cf012fb371b3.png)
