### ISSUE TITLE
微信小程序 子组件使用props函数传值给父组件，父组件的函数没有任何输出

### ISSUE THREAD

**Issue by gaoluona** [NervJS/taro#2417]
微信小程序 子组件使用props函数传值给父组件，父组件的函数没有任何输出，各种方式试完之后，感觉父组件的函数没有被触发，props函数是on开头的函数
![image](https://user-images.githubusercontent.com/38789755/54172307-9ec6a300-44b8-11e9-9368-3523fb7e560b.png)
![image](https://user-images.githubusercontent.com/38789755/54172380-cb7aba80-44b8-11e9-9951-97e99f057b5a.png)

**Comment by danieltao1993** [comment]
同样的问题：

1. 打包微信小程序后，使用onConfirm传递给子组件的()=>{}箭头函数子组件无法获得并调用    
2. 打包swan百度小程序后，找不到props传递给子组件confirm事件函数   
![图片](https://user-images.githubusercontent.com/15671438/54179719-98462480-44d4-11e9-9603-b316ff831dbe.png)  

3. 代码地址：    
    https://github.com/BDFE/taro-typescript/blob/master/src/components/wraper/index.tsx

**Comment by zicla** [comment]
这个问题真的是太坑了。遇到了同样的问题，感觉在打包微信小程序后，子组件没有办法调用到父组件传过来的回调函数。

**Comment by Chen-jj** [comment]
@gaoluona @zicla CLI 和依赖都升级到最新版本后再试试

**Comment by zicla** [comment]
> @gaoluona @zicla CLI 和依赖都升级到最新版本后再试试

已经升级到最新版本 1.2.17 ,但是子组件使用props函数传值给父组件，父组件中设置的函数依然没有调用。 目前我测试的情况是 h5，支付宝小程序正常；微信小程序没反应。 请 @Chen-jj 看一下。

**Comment by Chen-jj** [comment]
@zicla 提供一下可复现代码

**Comment by zicla** [comment]
> @zicla 提供一下可复现代码

我本来是为这个issue准备demo的，结果发现了新问题。


父组件 demo.js
```javascript
import Taro, {Component} from '@tarojs/taro'
import {Image, Button, View} from '@tarojs/components'
import DemoWidget from "./DemoWidget";

class Demo extends Component {


  config = {
    navigationBarTitleText: 'DEMO'
  }

  constructor(args) {
    super(args)

    this.state = {
      phone: ""
    }
  }

  componentWillUnmount() {
  }

  componentDidShow() {
  }

  componentDidHide() {
  }

  onChildClick() {
    console.log("父控件感知到子控件的点击方法了！")
    let statePhone = this.state.phone

    if (statePhone.length > 0) {
      this.setState({phone: statePhone.substring(0, statePhone.length - 1)})
    }

  }

  render() {
    let that = this
    let statePhone = that.state.phone

    console.log("父控件中", statePhone)
    return (
      <View className='page-demo'>
        <Button onClick={() => {
          console.log("点击事件")

          that.setState({phone: statePhone + "1"})

        }}>点击给子控件传值 {statePhone} </Button>

        <DemoWidget phone={statePhone} onSuccess={this.onChildClick.bind(this)}/>
      </View>
    )
  }
}

export default Demo

```

子组件 DemoWidget.js
```javascript
import Taro, {Component} from '@tarojs/taro'
import {View, Button} from '@tarojs/components'
import PropTypes from 'prop-types';

export default class DemoWidget extends Component {


  propTypes = {
    phone: PropTypes.string,
    onSuccess: PropTypes.func,
  }


  defaultProps = {
    phone: "",
    onSuccess: () => {
    }
  }

  constructor(props) {
    super(props);

    console.log("props", props)

    this.state = {}

  }

  componentWillMount() {

  }


  handleClick() {

    let that = this

    console.log("内部点击", this.props.onSuccess)

    if (typeof this.props.onSuccess === "function") {
      console.log("父类有定义onSuccess，直接调用")
      this.props.onSuccess()
    } else {
      console.log("props中没有设置onSuccess方法")
    }
  }

  render() {
    let that = this;
    let statePhone = that.props.phone

    console.log("子控件", statePhone);

    return (
      <Button
        className="widget-captcha-text"
        onClick={this.handleClick.bind(this)}>点击让父控件回调 {statePhone} </Button>
    )
  }
}




```


小程序和h5表现不一致。 h5地址： https://dhc.liyarou.com/h5#/pages/demo/demo

**Comment by zicla** [comment]
上面代码对应的新问题是这个issue  https://github.com/NervJS/taro/issues/2422

**Comment by Chen-jj** [comment]
@zicla 微信小程序正常
![image](https://user-images.githubusercontent.com/11807297/54420525-288aa080-4745-11e9-93e5-acc870fff049.png)

**Comment by Chen-jj** [comment]
@zicla H5 也没有问题
![image](https://user-images.githubusercontent.com/11807297/54421153-c894f980-4746-11e9-9278-609c9dbcd37b.png)

**Comment by zicla** [comment]
@Chen-jj 给的这个demo虽然没有复现函数回调的问题（函数回调的问题的确是有的，但是我现在demo中又正常了，我的开发组件中就不行），但是微信小程序中子控件收不到父控件传递过来的phone。这个问题同样致命啊。

**Comment by Chen-jj** [comment]
@zicla 那是因为你多此一举地把 this 赋值给了 that 导致的而已。

```js
// 这里改成直接使用 this.props.phone
let that = this;
let statePhone = that.props.phone
```

Taro 会识别使用到的 props 才加入到小程序的 data。

**Comment by zicla** [comment]
解决了问题，@Chen-jj 所说，必须直接使用 this.props.phone  函数的调用也类似，要用this.props.xxxFunc才行
个人总结两点吧
 1.子控件中要获取props必须使用 this.props.xxx 不能用中间变量来接收，否则就不能拿到xxx这个值。
 2.子控件要触发回调函数，必须使用 this.props.xxxFunc(arg)

**Comment by Zhou-Bill** [comment]
父组件传方法到子组件，子组件中打印该属性为什么是string, 而不是function？ 事我哪里写错了吗
![image](https://user-images.githubusercontent.com/13554001/54799894-2327db80-4c9a-11e9-974a-b2a63514a6c3.png)
![image](https://user-images.githubusercontent.com/13554001/54799943-65e9b380-4c9a-11e9-8e5b-70d647814f65.png)

**Comment by forMine** [comment]
> 父组件传方法到子组件，子组件中打印该属性为什么是string, 而不是function？ 事我哪里写错了吗
> ![image](https://user-images.githubusercontent.com/13554001/54799894-2327db80-4c9a-11e9-974a-b2a63514a6c3.png)
> ![image](https://user-images.githubusercontent.com/13554001/54799943-65e9b380-4c9a-11e9-8e5b-70d647814f65.png)
> 
> 已解决， 从父组件传函数过去要在属性上加 on

属性加了on获取不到props中的方法为何，为null

**Comment by Zhou-Bill** [comment]
> > 父组件传方法到子组件，子组件中打印该属性为什么是string, 而不是function？ 事我哪里写错了吗
> > ![image](https://user-images.githubusercontent.com/13554001/54799894-2327db80-4c9a-11e9-974a-b2a63514a6c3.png)
> > ![image](https://user-images.githubusercontent.com/13554001/54799943-65e9b380-4c9a-11e9-8e5b-70d647814f65.png)
> > 已解决， 从父组件传函数过去要在属性上加 on
> 
> 属性加了on获取不到props中的方法为何，为null

不会吧，反正只要传的是function的话必须加 on，你可能写错了吧

**Comment by Chen-jj** [comment]
@zicla 回复一下你的两点总结，纠正一些点。

1. props 传递除函数外的值时，是可以用中间变量接收的。你的问题是改变了 this 为 that，原因是编译时只会识别 `this.props.xxx`。

2. props 函数的调用除了直接调用外，还可以结构赋值后调用。

**Comment by Chen-jj** [comment]
@forMine 建议先确保 CLI 和依赖版本保持一致，看看文档和 demo 检查语法是否正确。
