### ISSUE TITLE
将原有项目转字节跳动小程序，运行报错：Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by beehoo** [NervJS/taro#2419]
**问题描述**
我将原有的taro项目转字节跳动小程序，编译后运行报：Uncaught ReferenceError: regeneratorRuntime is not defined

**复现步骤**
编译完成后运行就报错

**期望行为**
正常运行

**报错信息**

Uncaught ReferenceError: regeneratorRuntime is not defined

**系统信息**

 - 操作系统: [macOS 10.14.3]
 - Taro 版本 [v.1.2.17]
 - Node.js 版本 [v10.0.0]
 - 报错平台 [tt]

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/async-await.html#docsNav

**Comment by zhy8023** [comment]
我遇到了同样的问题，请问你们是如何解决的？

**Comment by luckyadam** [comment]
@zhy8023 楼上已经贴了文档

**Comment by daijiaoluoxinghui** [comment]
我遇到的不一样
![image](https://user-images.githubusercontent.com/38421595/54510942-4b59c680-498a-11e9-92dc-5a864e53b88b.png)
已经按照上面的链接
![image](https://user-images.githubusercontent.com/38421595/54511013-80feaf80-498a-11e9-9b14-add12f1ec57d.png)
![image](https://user-images.githubusercontent.com/38421595/54511033-8b20ae00-498a-11e9-8284-b418e7bfb173.png)

**Comment by zhy8023** [comment]
> @zhy8023 楼上已经贴了文档

我解决啦，我的问题运行报错Uncaught ReferenceError: regeneratorRuntime is not defined是因为没有配置project.tt.json导致

**Comment by lixiao258** [comment]
> project.tt.json
如何配置啊
