### ISSUE TITLE
npm run dev:h5, 编译没报异常，但 访问 http://localhost:8080/ 是 Cannot GET /

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#242]
Taro v0.0.63 和 Taro v0.0.60 都有这个问题，
访问 本机 ip 和 127.0.0.1，问题依旧，
没有更改 config/ 里的文件
运行 npm run build:h5 是正常的，
项目为 非 typescript , 系统 win7 64bit
以下为编译信息：
$ npm run build:h5 -- --watch

> js@1.0.0 build:h5 C:\git\weapp
> taro build --type h5 "--watch"

👽 Taro v0.0.63

开始编译项目 js

监听文件修改中...

> Listening at http://192.168.10.244:8080/
> Listening at http://localhost:8080/

以下为 chrome network 里的信息:

Request URL: http://localhost:8080/
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer-when-downgrade

**Comment by mindfocus** [comment]
v0.0.64也发现这个问题

**Comment by luckyadam** [comment]
是 `taro init` 直接创建的 js 项目么

**Comment by Dithub2016** [comment]
是的

**Comment by imWildCat** [comment]
```bash
➜  myApp git:(master) ✗ taro --version
👽 Taro v0.0.70

0.0.70
➜  myApp git:(master) ✗ npm --version
5.6.0
```
同样的问题。

**Comment by tvxqljw** [comment]
今天刚下载taro尝试，先是跑了一次 sudo npm run dev:weapp,然后再sudo npm run dev:h5, 也是这个问题

**Comment by luckyadam** [comment]
@tvxqljw 你下的是啥版本

**Comment by Nexoi** [comment]
同上，
「先是跑了一次 sudo npm run dev:weapp,然后再sudo npm run dev:h5, 也是这个问题」

**Comment by luckyadam** [comment]
@Nexoi 版本多少，其次，为什么要加 `sudo`

**Comment by Nexoi** [comment]
@luckyadam 
没加 sudo，版本是：
npm 6.4.1
taro 1.0.0-beta.23

**Comment by luckyadam** [comment]
@Nexoi 编译过程截个图看看咯~ 其次看看直接用 ip 地址能不能访问，有可能是 hosts 文件的问题

**Comment by Nexoi** [comment]
@luckyadam 
编译结果：

```
> lihezaiwu@1.0.0 dev:h5 /Users/neo/Projects/VSCodeProjects/lihezaiwu
> npm run build:h5 -- --watch


> lihezaiwu@1.0.0 build:h5 /Users/neo/Projects/VSCodeProjects/lihezaiwu
> taro build --type h5 "--watch"

👽 Taro v1.0.0-beta.23

开始编译项目 lihezaiwu
创建  发现文件  src/app.css
创建  发现文件  src/app.js
创建  发现文件  src/index.html
创建  发现文件  src/pages/index/index.css
创建  发现文件  src/pages/index/index.js

🙅   Compile failed!

./.temp/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "es2015" relative to directory "/Users/neo/Projects/VSCodeProjects"
    at Array.map (<anonymous>)


ℹ️  Listening at http://10.21.113.59:8080/
ℹ️  Listening at http://localhost:8080/
```

btw, dist 文件夹是空的。。

**Comment by luckyadam** [comment]
@Nexoi 你有加 `es2015`  这个 preset 么

**Comment by xdsjs** [comment]
曾经遇到过，我是因为开VPN倒是，可以检查下关掉VPN试下

**Comment by yuquanwang** [comment]
我也遇到了，通过yarn add babel-preset-env解决
