### ISSUE TITLE
在页面中设置navigationBarTitleText，rn模式下无效

### ISSUE THREAD

**Issue by lightbluestar** [NervJS/taro#2420]
**问题描述**
在页面中设置navigationBarTitleText，rn模式下无效

**复现步骤**
1. taro创建项目，使用typescript+sass+mobx
2. 在页面config字段中设置navigationBarTitleText
3. 导航标题不显示设置的文字

```js
// app.tsx
  window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
  }
// pages/index/index.tsx
  config: Config = {
    navigationBarTitleText: '首页'
  }
```
![image](https://user-images.githubusercontent.com/17740011/54182903-c2e8ab00-44dd-11e9-8d7a-2ab0dff73571.png)

**期望行为**
导航文字应该显示“首页”

**系统信息**
 - 操作系统: macOS 10.14.3
 - Taro 版本 v1.2.8
 - Node.js 版本 10.15.2
 - 报错平台 react-native

**补充信息**
可能和使用了ts有关

**Comment by js-newbee** [comment]
@lightbluestar 版本有点旧了，现在都 1.2.17 了，建议升级试试？

**Comment by lightbluestar** [comment]
@js-newbee 已经升级到最新版本，还是不行

**Comment by Pines-Cheng** [comment]
mbox 装饰器导致的，正在解决，感谢反馈～

**Comment by lightbluestar** [comment]
@Pines-Cheng 辛苦
