### ISSUE TITLE
微信小程序中这个不是预计的效果，h5中正常的

### ISSUE THREAD

**Issue by zwblue** [NervJS/taro#2421]
<View>
   {process.env.TARO_ENV === 'weapp' && <BaseWxParse html={this.getContent(item)} />}
 </View>

在微信小程序中 这个计算后没有渲染子组件，内容没显示出来

<View>
   {process.env.TARO_ENV === 'weapp' && <BaseWxParse html={this.getContent(item)} />}
  {process.env.TARO_ENV === 'h5' && <View dangerouslySetInnerHTML = {{ __html: 
   this.getContent(item) }}></View>}
 </View>
如果 再加下面的一行，在微信小程序中他直接返回了false，h5中正常显示 
求大神指教，我应该如何各端渲染不同的组件

**Comment by js-newbee** [comment]
请务必遵循 Issue 模板的规范... 你这样提问别人根本帮不上忙...

不过感觉是版本问题，建议升级版本试试

**Comment by zwblue** [comment]
> @zwblue 请务必遵循 Issue 模板的规范... 你这样提问别人根本帮不上忙...
> 
> 不过感觉是版本问题，建议升级版本试试

谢谢，问题已解决： 
1、    我这个版本小程序中  这种写法  {process.env.TARO_ENV === 'weapp' ? (<BaseWxParse html={this.getContent(item)}></BaseWxParse>): null}  其中的**this.getContent(item)** 不处理。只能在提前处理好数据再渲染。

**Comment by zwblue** [comment]
> @zwblue 请务必遵循 Issue 模板的规范... 你这样提问别人根本帮不上忙...
> 
> 不过感觉是版本问题，建议升级版本试试

谢谢，问题通过特殊方法已解决，我代码粘贴上去了，但没有显示全，尴尬
