### ISSUE TITLE
在Android上ScrollView不能上下滑动

### ISSUE THREAD

**Issue by ss520k** [NervJS/taro#2425]
------------------------

**问题描述**
在网易严选的开源项目中首页使用的ScrollView不能上下滑动，此现象出现在android上

**复现步骤**
[复现问题的步骤]
1. 下载网易严选,地址：https://github.com/js-newbee/taro-yanxuan
2. 配置好环境
3. npm run dev:rn
4. 在Android手机上运行网易严选app，
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
可以上下滑动
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\fantasy2018\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by pengxiang-git** [comment]
@Pines-Cheng 这个问题解决了吗，android加上tapbar，scrollview就拖动不了

**Comment by Manjiz** [comment]
@pengxiang-git 详细看了下代码，原因是 `@tarojs/taro-router-rn` 给每个 page 带了 ScrollView，现 home 页裡有个 ScrollView，也就是有两个 ScrollView 嵌套，熟悉 RN 开发的应该了解两个 ScrollView 嵌套有坑，里层的 ScrollView 高度大于外层 ScrollView，实际滚动的是外层 ScrollView，所以你滚不动，你可以尝试如下：

```jsx
style={{ height: getWindowHeight() - 20 }}
```

定一个稍小点的高度，就可以滚动了，也就是安卓下，getWindowHeight 所取的高度不精确。

**Comment by pengxiang-git** [comment]
@Manjiz 好的

**Comment by Pines-Cheng** [comment]
如果页面需要禁止滚动或者自定义滚动，可以在 Page 的 config 里面添加：disableScroll:true，这样就不会默认在页面上套 ScrollView 了。

**Comment by ss520k** [comment]
好的
