### ISSUE TITLE
Taro.addInterceptor 建议文档注明版本号，在1.2.15版本中没有这个方法，升级到1.2.17就没问题了

### ISSUE THREAD

**Issue by liujians** [NervJS/taro#2427]
**问题描述**

Taro.addInterceptor 这个方法在1.2.15中报错，打印Taro对象也没有addInterceptor这个方法
升级到1.2.17就没问题了

**期望行为**

建议在文档中标注不支持的版本号。例如`1.2.17以后才支持`

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**补充信息**

  搞了我很久才发现是版本的问题，心累

**Comment by ASeR1-ATG** [comment]
thank u


________________________________

**Comment by luckyadam** [comment]
OJBK，确实遗漏了

**Comment by stupidWall** [comment]
为什么升级到了1.2.22， Taro.addInterceptor还是报错
