### ISSUE TITLE
多个 if 和 else if 一起使用时编译出现问题

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#2432]
**问题描述**
多个 if 和 else if 一起使用时编译出现问题，第一个 if 和紧接着的那个 else if 编译正常，第三个以后的 else if 和 else 会编译到第一个 if 里面嵌套了。

**复现步骤**

关键部分：
```js
    if (type !== 'text') {
      valueView = <Price price={value} type={type} />
    } else if (isExchange) {
      valueView = <Price price={value} isExchange />
    } else if (isPrice) {
      valueView = <Price price={value} />
    } else {
      valueView = <Text>{value}</Text>
    }
```
编译后：
![image](https://user-images.githubusercontent.com/21964227/54281101-f60d6600-45d3-11e9-90c5-9e900172abcf.png)

完整的 render 函数：
```js
  render() {
    const {title, type, isExchange, isPrice, isLink, icon, disabled, value} = this.props;
    let className = 'cell ' + (disabled ? 'disabled' : (isLink ? 'can-click ' : ''));
    
    let valueView, arrow;
    
    if (type !== 'text') {
      valueView = <Price price={value} type={type} />
    } else if (isExchange) {
      valueView = <Price price={value} isExchange />
    } else if (isPrice) {
      valueView = <Price price={value} />
    } else {
      valueView = <Text>{value}</Text>
    }
    
    if (!disabled && isLink) {
      arrow = <Text className='iconfont icon-right' />
    }
    
    return (
      <View
        className={className}
        onClick={this.onClick}
      >
        <Text className='left'>
          {icon && <Text className={'iconfont icon-' + icon} />}
          <Text className='text'>{title}</Text>
        </Text>
        <View>
          {valueView}
          {this.props.children}
          {arrow}
        </View>
      </View>
    )
  }
```

**期望行为**
编译正确

**报错信息**
wxml 语法错误，wx:elif 必须跟在同一级 wx:if 后面

**系统信息**
👽 Taro v1.2.17

Taro CLI 1.2.17 environment info:
  System:
    OS: macOS 10.14.3
Shell: 5.3 - /bin/zsh
Binaries:
  Node: 10.15.0 - /usr/local/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
npmPackages:
@tarojs/cli: 1.2.17 => 1.2.17
@tarojs/components: 1.2.17 => 1.2.17
@tarojs/plugin-babel: 1.2.17 => 1.2.17
@tarojs/plugin-csso: 1.2.17 => 1.2.17
@tarojs/plugin-sass: 1.2.17 => 1.2.17
@tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17
@tarojs/router: 1.2.17 => 1.2.17
@tarojs/taro: 1.2.17 => 1.2.17
@tarojs/taro-h5: 1.2.17 => 1.2.17
@tarojs/taro-weapp: 1.2.17 => 1.2.17
@tarojs/webpack-runner: 1.2.17 => 1.2.17
eslint-config-taro: 1.2.17 => 1.2.17
eslint-plugin-taro: 1.2.17 => 1.2.17
nervjs: ^1.3.5 => 1.3.5 

**补充信息**

**Comment by Garfield550** [comment]
这是个 Bug，issue #2415 已经提过，在 commit abbfc348 已经被修复

**Comment by vimcaw** [comment]
ok, 感谢你们

**Comment by imageslr** [comment]
你好，我也遇到了这个问题，请问如何解决呢？安装旧版本的taro？@vimcaw @Garfield550

**Comment by vimcaw** [comment]
要么等新版本，要么回退版本，要么修改代码结构来绕过这个问题

Zhu <notifications@github.com> 于2019年3月14日周四 下午3:06写道：

**Comment by imageslr** [comment]
回退版本后解决了，多谢~

**Comment by soymikey** [comment]
switch case 不支持， 要用三元表达式来跳过这个问题
