### ISSUE TITLE
如何让Picker支持鼠标拖动？最好支持滚轮

### ISSUE THREAD

**Issue by qwIvan** [NervJS/taro#2433]
**问题描述**
如何让Picker支持鼠标拖动？现在只对触摸时间有响应

**期望行为**
希望支持鼠标拖动，最好还支持鼠标滚轮滚动

https://taro-ui.aotu.io/h5/index.html#/pages/form/picker/index
这里面的picker并不支持鼠标拖动

**Comment by jinjinjin0731** [comment]
支持鼠标拖动啊

**Comment by qwIvan** [comment]
@jinjinjin0731 h5可以在桌面端运行

**Comment by jinjinjin0731** [comment]
左键点击拖拽。

**Comment by qwIvan** [comment]
@jinjinjin0731 我的chrome并不支持拖拽，除非是在移动模式下，使用触摸事件来拖拽。

**Comment by jinjinjin0731** [comment]
请问下为啥不开移动模式。。。

**Comment by jinjinjin0731** [comment]
源码是 touch 事件来写的，主要作用与移动端场景。  PC 场景不推荐使用

**Comment by qwIvan** [comment]
@jinjinjin0731 但是用户不会开移动模式啊。。。能做的话，为什么不支持PC操作呢。

**Comment by jinjinjin0731** [comment]
第一，组件的使用场景不同，如果在 PC 的场景下，是不是 select 比 Picker 更加的适合？
第二，移动端应用和 PC 应用存在设计差异，建议分开两套代码写。 技术栈可以是 react vue ng。 或者是更加轻量级的 nerv :)

**Comment by qwIvan** [comment]
@jinjinjin0731 用taro还不是因为要输出小程序端，而小程序没有select。输出小程序端用户微信小程序，输出web端用于桌面。不冲突。如果非要用select的话，只能在web端和小程序端分别使用不同的实现。最好能够统一起来。

**Comment by qwIvan** [comment]
现在我就是需要在PC端使用移动端的设计。让移动端组件支持一下鼠标操作有那么难吗。

**Comment by jinjinjin0731** [comment]
@qwIvan 不支持。 和难不难没关系，设计理念的差异。 我上面第二点说了。

**Comment by qwIvan** [comment]
@jinjinjin0731 移动设备也可以鼠标操作。桌面端也可以触摸操作。操作方式和设备是两回事。

**Comment by jinjinjin0731** [comment]
@qwIvan 嗯。。话题就此打住。回到该 issue 的问题回答
1、Picker 组件只支持触摸方式，适应在移动端上。
2、对于你需要的 PC 差异化组件，你可以利用这个特性，去实现平台的差异化[多端组件](https://nervjs.github.io/taro/docs/envs.html#%E5%A4%9A%E7%AB%AF%E7%BB%84%E4%BB%B6)

**Comment by qwIvan** [comment]
@qwIvan 既然如此的话，为什么日历组件又可以用鼠标拖动呢？
