### ISSUE TITLE
建议：typescript环境，报错：找不到模块“*.less”等静态资源

### ISSUE THREAD

**Issue by leidenglai** [NervJS/taro#2437]
**问题描述**
typescript环境，报错：找不到模块“*.less”等静态资源

**复现步骤** 
使用cli直接创建应用 选择typescript
使用cssModules 或者导入静态资源文件

**期望行为**
创建global.d.ts时 不要插入这一句
`import React from 'react';`
这会导致global.d.ts变为普通模块文件，而非全局环境声明

[参考 https://stackoverflow.com/a/51114250/11124226](https://stackoverflow.com/a/51114250/11124226)

**报错信息**
vscode报错 找不到模块“./index.module.less”。

**系统信息**
  Taro CLI 1.2.17 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/mobx: 1.2.17 => 1.2.17 
      @tarojs/mobx-h5: 1.2.17 => 1.2.17 
      @tarojs/mobx-rn: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-less: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/rn-runner: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-tt: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.9 => 1.3.12

**Comment by luckyadam** [comment]
可以提个 pr 上来咯
