### ISSUE TITLE
微信小程序组件css未编译

### ISSUE THREAD

**Issue by AoeSyL** [NervJS/taro#2442]
**问题描述**
子组件引入后 css未被编译

**复现步骤**
层级
-index 
    -hotModel 
        -goodsCard

![image](https://user-images.githubusercontent.com/28856703/54401979-16890d80-4705-11e9-84fe-e425b3371c11.png)
开始编译后查看dist未发现index,hotModel和goodsCard的wxss

**index**
`import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.less'
import { AtCard } from "taro-ui"
import { AtSearchBar } from 'taro-ui'
import { HotModel } from '../../models/hotModels/hotModel'
export default class Index extends Component {
  static options = {
    addGlobalClass: true
  }
  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  constructor () {
    super(...arguments)
    this.state = {
      value: ''
    }
  }
  onChange (value) {
    this.setState({
      value: value
    })
  }
  onActionClick () {
    console.log('开始搜索')
  }

  configdata = {
    banner: [
      {url: 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1552230671622&di=2bdbac6b8b16ff7a124dbfa1309d1d0a&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimage%2Fc0%253Dshijue1%252C0%252C0%252C294%252C40%2Fsign%3D37281b8c8082b90129a0cb701be4c302%2F4b90f603738da977c1c6b680ba51f8198718e3b4.jpg'},
      {url: 'https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3573391510,1607065364&fm=26&gp=0.jpg'}
    ],
    posts: [
      {id: 1, title: 'Hello1 World', content: 'Welcome to learning Taro!'},
      {id: 2, title: 'Installation', content: 'You can install Taro from npm.'}
    ]
  }

  render () {
    const { banner } = this.configdata
    const banners = (
      <Swiper
        className='banner-swiper'
        indicatorColor='#999'
        indicatorActiveColor='#333'
        circular
        indicatorDots
        autoplay>
        {banner.map((val) =>
          <SwiperItem key={val.id}>
            <View className='banner-item'>
              <image class="banner-img" src={val.url}></image>
            </View>
          </SwiperItem>
        )}
      </Swiper>
    )

    return (
      <View className='container'>
        <View className='at-raw at-row--wrap'>
          <View className='at-col at-col-12'>
            <AtSearchBar
                actionName='搜索'
                value={this.configdata.value}
                onChange={this.onChange.bind(this)}
                onActionClick={this.onActionClick.bind(this)}
              />
          </View>
          <View className='at-col at-col-12'>
            {banners}
          </View>

          <View className='at-col-12'>
          </View>
          <HotModel renderBody={
            <View className=''>Welcome!</View>
          }>
          </HotModel>
        </View>
      </View>
    )
  }
}

`

**hotModel**
`import Taro, {Component} from '@tarojs/taro';
import { View, Text } from '@tarojs/components'
import './hotModel.less'
import 'taro-ui/dist/style/index.scss'
import { GoodsCards } from '../../components/card-style/goodsCard'
if (process.env.TARO_ENV === "weapp") {
  require("taro-ui/dist/weapp/css/index.css")
} else if (process.env.TARO_ENV === "h5") {
  require("taro-ui/dist/h5/css/index.css")
}

class HotModel extends Component {
  static options = {
    addGlobalClass: true
  }

  data = {
    hotgoods: [
      {start_time:"2019-09-01 0:0:0",status:1,url: 'https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3573391510,1607065364&fm=26&gp=0.jpg'},
      {start_time:"2019-09-01 0:0:0",status:0,url: 'https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3573391510,1607065364&fm=26&gp=0.jpg'}
    ]
  }

  render () {
    const { hotgoods } = this.data
    const goods = (
      <View className='at-row goods-box'>
        {hotgoods.map((val) =>
          <View className='at-col at-col-4' key={val.id}>
            <GoodsCards data={val}/>
          </View>
        )}
      </View>
    )

    return (
      <View className='hotModel'>
        <View className='at-col-12 title-bar'>
          <View className='at-article__h2 title-left'>
            限时秒杀
          </View>
          <View className='at-article__p title-right'>
            tips:收藏宝贝抢占先机 >
          </View>
        </View>
        {goods}
      </View>
    )
  }
}
`

**GoodsCard**
import Taro, {Component} from '@tarojs/taro';
import { View, Text } from '@tarojs/components'
import './goodCard.less'
if (process.env.TARO_ENV === "weapp") {
  require("taro-ui/dist/weapp/css/index.css")
} else if (process.env.TARO_ENV === "h5") {
  require("taro-ui/dist/h5/css/index.css")
}
class GoodsCard extends Component {
  static options = {
    addGlobalClass: true
  }

  render () {
    // const status = this.props.data.status
    // let time = null
    // if(status == 0){
    //   time = <div>已结束</div>
    // }else{
    //   time = <div>{ this.props.data.start_time }</div>
    // }
    return (
          <View className='goods-item'>
          <div>

            <image class="goods-img" src={this.props.data.url}></image>
          </div>
          </View>
    )
  }
}

**系统信息**
 - 操作系统: [Mac Os]
 - Taro 版本 [Taro v1.2.16]
 - Node.js 版本 [v10.14.2]
 - 报错平台 [ weapp]

**补充信息**
未知

**Comment by AoeSyL** [comment]
**补充**
第一次编译未发现wxss
![image](https://user-images.githubusercontent.com/28856703/54402170-03c30880-4706-11e9-9340-ef19c767d3e5.png)

修改index中的css后触发--watch 
![image](https://user-images.githubusercontent.com/28856703/54402261-543a6600-4706-11e9-8597-b4037f77b97f.png)

**Comment by luckyadam** [comment]
你翻一下前面的编译信息，应该有别的报错

**Comment by AoeSyL** [comment]
@luckyadam 感谢   是子组件中css文件名引入错误

**Comment by luckyadam** [comment]
好的
