### ISSUE TITLE
能否提供代码格式化配置文件.prettierrc？

### ISSUE THREAD

**Issue by guxingke201** [NervJS/taro#2445]
### 这个功能解决了什么问题？

[taro官方文档有最佳实践的代码要求](https://nervjs.github.io/taro/docs/best-practice.html)，提供.prettierrc，方便代码格式化

### 你期望的功能是怎样的？

提供.prettierrc，类似：
````
{
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 100,
  "overrides": [
    {
      "files": ".prettierrc",
      "options": {
        "parser": "json"
      }
    }
  ]
}

````

**Comment by Garfield550** [comment]
prettier 的话，可能不是每个人都在用，而且每个人的配置也不同

**Comment by guxingke201** [comment]
多个人在维护同一个项目，是不是应该统一格式化配置？不然格式化下源码提交上去，出现大量变更，做代码审核的人会很费劲的。

[antd团队最近就把代码格式化的配置提交上去](https://github.com/ant-design/ant-design/blob/master/.prettierrc)

**Comment by yuche** [comment]
prettier 在 Taro 中使用有两个问题：

1. 一般有修复功能的 ESLint 规则会使用，Taro 的绝大部分自定义规则是没办法修复的（例如无法在 JSX 使用 ...spread 语法），这样提供了也意义不大
2. Taro 推荐在 JSX 使用单引号，prettier 在 JSX 是强制双引号

**Comment by Garfield550** [comment]
@yuche Prettier 其实可以强制 JSX 使用单引号，使用 `"jsxSingleQuote": true`

```json
{
    "printWidth": 86,
    "tabWidth": 2,
    "useTabs": false,
    "semi": true,
    "singleQuote": true,
    "jsxSingleQuote": true,
    "trailingComma": "es5",
    "bracketSpacing": true,
    "jsxBracketSameLine": true,
    "arrowParens": "avoid",
    "endOfLine": "crlf"
}
```

**Comment by seekcx** [comment]
> prettier 在 Taro 中使用有两个问题：
> 
> 1. 一般有修复功能的 ESLint 规则会使用，Taro 的绝大部分自定义规则是没办法修复的（例如无法在 JSX 使用 ...spread 语法），这样提供了也意义不大
> 2. Taro 推荐在 JSX 使用单引号，prettier 在 JSX 是强制双引号

其实我一直没明白，为什么 Taro 要在 JSX 中使用单引号。

**Comment by cnscorpions** [comment]
+1
