### ISSUE TITLE
mobx 无法观察对象属性的变化

### ISSUE THREAD

**Issue by coppyC** [NervJS/taro#2446]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
@observer
export default class extends Component {
  @observable
  obj = {
    x:1
  }
  render() {
    return (
      <View>
        {this.obj.x}
      </View>
    )
  }
  componentWillMount(){
    // 这样做，视图层没有更新
    setInterval(()=> this.obj.x ++ , 1000)
  }
}

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
现在是要对obj重新赋值，视图层才能更新，
像这样 
```js
this.obj = {
  x: this.obj.x +1
}
```
但我希望是这样
```js
this.obj.x ++
```

👽 Taro v1.2.9

  Taro CLI 1.2.9 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /var/folders/w6/cdk_c0p54111866kwlprhctr0000gn/T/yarn--1552631474187-0.6151180224026473/node
      Yarn: 1.13.0 - /var/folders/w6/cdk_c0p54111866kwlprhctr0000gn/T/yarn--1552631474187-0.6151180224026473/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.17 => 1.2.17
      @tarojs/cli: ^1.2.9 => 1.2.9
      @tarojs/components: 1.2.9 => 1.2.9
      @tarojs/mobx: 1.2.9 => 1.2.9
      @tarojs/mobx-h5: 1.2.9 => 1.2.9
      @tarojs/mobx-rn: 1.2.9 => 1.2.9
      @tarojs/plugin-babel: 1.2.9 => 1.2.9
      @tarojs/plugin-csso: 1.2.9 => 1.2.9
      @tarojs/plugin-sass: 1.2.9 => 1.2.9
      @tarojs/plugin-uglifyjs: 1.2.9 => 1.2.9
      @tarojs/rn-runner: 1.2.9 => 1.2.9
      @tarojs/router: 1.2.9 => 1.2.9
      @tarojs/taro: 1.2.9 => 1.2.9
      @tarojs/taro-alipay: 1.2.9 => 1.2.9
      @tarojs/taro-h5: 1.2.9 => 1.2.9
      @tarojs/taro-swan: 1.2.9 => 1.2.9
      @tarojs/taro-tt: 1.2.9 => 1.2.9
      @tarojs/taro-weapp: 1.2.9 => 1.2.9
      @tarojs/webpack-runner: 1.2.9 => 1.2.9
      eslint-config-taro: 1.2.9 => 1.2.9
      eslint-plugin-taro: 1.2.9 => 1.2.9
      nervjs: ^1.3.9 => 1.3.11

✨  Done in 0.53s.**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
没有 对 对象的属性进行观察？

**Comment by nanjingboy** [comment]
@coppyC 对于

```js
render() {
  return (
    <View>
      {this.obj.x}
    </View>
  )
}
```

小程序会生成两部分：

```js
 {
    key: "_createData",
    value: function _createData() {
      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __runloopRef = arguments[2];
      var obj = this.obj;

      Object.assign(this.__state, {
        obj: obj
      });
      return this.__state;
    }
 }
```

和 

```html
<block>
    <view>{{obj.x}}</view>
</block>
```

而 mobx 只对第一部分（即 _createData 方法进行监听），又根据 mobx 何时作出响应的标准（[链接](https://cn.mobx.js.org/best/react.html#mobx-%E4%BC%9A%E5%AF%B9%E4%BB%80%E4%B9%88%E4%BD%9C%E5%87%BA%E5%8F%8D%E5%BA%94)），你需要按照以下方式修改 render 方法：

```js
render() {
  const { obj: { x } } = this;
  return (
    <View>
      {x}
    </View>
  )
}
```

BTW：这些注意点其实都在 taro 的官方文档注意事项中说明了

**Comment by coppyC** [comment]
@nanjingboy 
好的，我明白了，
所以 是因为render 以编译成 wxml 后，obj.x 只在wxml中，没有在render 函数中，不会对 obj.x的值进行读取，所以没有响应吗。
这看起来好像是这样的，因为下面的代码可以响应
```ts
@observer
export default class extends Component {
  @observable
  obj = {
    x:1
  }
  render() {
   // --------这个地方不一样---------
   // 读取obj中的x，只进行读操作，让mobx能对obj.x作出响应。
    this.obj.x
    // 或者遍历obj中的值，都可以让mobx做出响应，
    // 但是遍历可能会观察多余属性，而且不能进行深度观察
    // Object.values(this.obj)
    // ---------------------------------
    return (
      <View>
        {this.obj.x}
      </View>
    )
  }
  componentWillMount(){
    setInterval(()=> this.obj.x ++ , 1000)
  }
}
```

现在有个思路，
在编译jsx的时候，把jsx中用到的变量编译到 render 函数中进行读取操作，这样可以让mobx的写法更加自由，和h5保持一致。
不知可不可行。

**Comment by nanjingboy** [comment]
@coppyC 看下编译后的代码，在 return 之前你使用了 this.obj.x，所以 mobx 可以监听到。小程序有自己的特殊性，目前还是按照文档的注意事项来写吧
