### ISSUE TITLE
ScrollView 组件无法触发onScrollToUpper 包括onScrollToLower

### ISSUE THREAD

**Issue by joker-li** [NervJS/taro#2447]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)
**问题描述**
[问题描述：ScrollView 组件无法触发onScrollToUpper 包括onScrollToLower onScroll可以正常触发]

```js
// 这里可以贴代码
<ScrollView 
          scrollWithAnimation
          scrollY
          upperThreshold='100'
          className='orderGoods'
          onScrollToUpper={this.leadermore}
          // onScroll={this.leadermore}
        >
        ...内容区
 </ScrollView>  
```

**期望行为**
希望可以正确触发onScrollToUpper

**系统信息**
Taro CLI 1.2.15 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.17 => 1.2.17 
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-sass: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/redux: 1.2.17 => 1.2.17 
      @tarojs/redux-h5: 1.2.17 => 1.2.17 
      @tarojs/rn-runner: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-tt: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.0 => 1.3.12

**Comment by 1138663994** [comment]
遇到同样的问题。

**Comment by jinjinjin0731** [comment]
@joker-li 你的问题把你的 cli 和项目依赖升级到最新即可解决。  cli 和项目依赖的版本号一定要一致

**Comment by jinjinjin0731** [comment]
@1138663994 你的问题麻烦贴下你的相关版本号，代码等信息?

**Comment by talentedman** [comment]
@jinjinjin0731  
我的cli和项目依赖都是1.2.21 已经是最新了 
但是onScroll和onScrollToLower还是没有触发

我的代码如下
![image](https://user-images.githubusercontent.com/18200527/54910290-ff2cfa00-4f26-11e9-93af-0fa4b762fae5.png)

然后我调试scroll-view的源码  发现里面的事件已经不触发了
![image](https://user-images.githubusercontent.com/18200527/54910373-2be11180-4f27-11e9-8205-9719627d4113.png)

**Comment by fangcaiwen** [comment]
> @joker-li 你的问题把你的 cli 和项目依赖升级到最新即可解决。 cli 和项目依赖的版本号一定要一致

不行

**Comment by jinjinjin0731** [comment]
@fangcaiwen 你说个不行可以解决啥问题？新开个 issue 把你的 demo ，版本号给贴出来啊？

**Comment by kala888** [comment]
同样问题，看你这里没有解决方案
其实是给个高度就行了“使用竖向滚动时，需要给 <scroll-view/> 一个固定高度，通过 WXSS 设置 height。”
