### ISSUE TITLE
支付宝小程序@tarojs/taro-alipay包升级到1.2.17版本，ios真机调试报错

### ISSUE THREAD

**Issue by xaruy** [NervJS/taro#2448]
**问题描述**
@tarojs/taro-alipay 升级到 1.2.17后，在iphone7下支付宝真机调试，所有的服务器接口报错。回退到1.2.16后恢复正常。
框架环境使用Taro + Taro UI + Dva 。

**复现步骤**
1. npm i升级到最新版本。
2. 支付宝小程序进入真机调试模式
3. iphone7下访问远程接口报错，network没有去访问

```js
effects: {
    * getIndexList(_, { call, put }) {
      const res = yield call(homeApi.IndexList, { channel: 1 });
      if (res) {
        yield put({
          type: 'save',
          payload: res.data,
        });
      }
    },
  },


export const IndexList = (data) => {
  return Request({
    url: 'aliPay/index/getIndexActionList',
    method: 'GET',
    data,
  });
};
```

**期望行为**

**报错信息**
```js
redux-saga error: uncaught at _callee3
at _callee3 
 at _callee6 
 at takeEvery(home/getIndexList, _callee) 
 at _callee 
 at _callee 
 Error: [object Object]
    at http://127.0.0.1:60430/index.worker.js:23782:17
    at http://127.0.0.1:60430/index.worker.js:22654:26
    at onError (http://127.0.0.1:60430/index.worker.js:23783:11)
    at sagaWithCatch$ (http://127.0.0.1:60430/index.worker.js:23294:13)
    at tryCatch (http://127.0.0.1:60430/index.worker.js:30206:40)
    at Generator.invoke [as _invoke] (http://127.0.0.1:60430/index.worker.js:30425:22)
    at Generator.prototype.(anonymous function) [as throw] (http://127.0.0.1:60430/index.worker.js:30254:21)
    at next (http://127.0.0.1:60430/index.worker.js:32548:32)
    at Object.currCb [as cont] (http://127.0.0.1:60430/index.worker.js:32647:7)
    at end (http://127.0.0.1:60430/index.worker.js:32615:23)
Uncaught (in promise) {error: 4, errorMessage: "无权调用该接口", preventDefault: ƒ}
newFail @ QHkhuZLfIVkRKCCIGzUy.js:5376
(anonymous) @ QHkhuZLfIVkRKCCIGzUy.js:8758
_invokeJS @ preload.js:401
_handleMessageFromObjC @ preload.js:389
(anonymous) @ VM132:1
electron.ipcRenderer.on @ VM83 web-frame-init.js:36
emit @ VM18 events.js:182
```
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro v1.2.1

  Taro CLI 1.2.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.1 => 1.2.17 
      @tarojs/components: ^1.2.1 => 1.2.17 
      @tarojs/plugin-babel: ^1.2.1 => 1.2.17 
      @tarojs/plugin-csso: ^1.2.1 => 1.2.17 
      @tarojs/plugin-sass: ^1.2.1 => 1.2.17 
      @tarojs/plugin-uglifyjs: ^1.2.1 => 1.2.17 
      @tarojs/redux: ^1.2.1 => 1.2.17 
      @tarojs/redux-h5: ^1.2.1 => 1.2.17 
      @tarojs/router: ^1.2.1 => 1.2.17 
      @tarojs/taro: ^1.2.1 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: ^1.2.1 => 1.2.17 
      @tarojs/taro-swan: ^1.2.1 => 1.2.17 
      @tarojs/taro-weapp: ^1.2.1 => 1.2.17 
      @tarojs/webpack-runner: ^1.2.1 => 1.2.17 
      eslint-config-taro: ^1.2.1 => 1.2.17 
      eslint-plugin-taro: ^1.2.1 => 1.2.17

**Comment by luckyadam** [comment]
close via 8a9348c6bf3ecd7226e2b8d84cc088c1c34bf806
