### ISSUE TITLE
支付宝小程序 Cannot read property 'getAllComponents' of undefined 错误 

### ISSUE THREAD

**Issue by easonchiu** [NervJS/taro#2449]
**问题描述**

代码写着写着就报了`Cannot read property 'getAllComponents' of undefined`错，而且目前没有找到现出该错误的规律。
一旦出现该错误，将出现错误时前后的写的代码恢复也没用。
目前我出现过两次这个错误，第一次解决的方式是部分的删除组件重新打包，但最终是没有做任何修改，只是各种尝试重新打包，然后就正常了...

**报错信息**

```
TypeError: Cannot read property 'getAllComponents' of undefined
    at af-appx.worker.ide.min.js:7
    at Array.forEach (<anonymous>)
    at Function.n.getAllComponents (af-appx.worker.ide.min.js:7)
    at af-appx.worker.ide.min.js:7
    at Array.forEach (<anonymous>)
    at af-appx.worker.ide.min.js:7
    at ut.startRender (af-appx.worker.ide.min.js:7)
    at ut.load (af-appx.worker.ide.min.js:7)
    at af-appx.worker.ide.min.js:7
    at ne (af-appx.worker.ide.min.js:7)
setTimeout (async)		
e.setTimeout	@	af-appx.worker.ide.min.js:7
print.(anonymous function)	@	print.js:18
dispatchEvent	@	worker.js:222
(anonymous)	@	VM706:1
electron.ipcRenderer.on	@	/Applications/小程序开发者…eb-frame-init.js:36
emit	@	events.js:182
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.2.15 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.17 => 1.2.14 
      @tarojs/cli: 1.2.17 => 1.2.14 
      @tarojs/components: 1.2.17 => 1.2.14 
      @tarojs/plugin-babel: 1.2.17 => 1.2.14 
      @tarojs/plugin-csso: 1.2.17 => 1.2.14 
      @tarojs/plugin-sass: 1.2.17 => 1.2.14 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.14 
      @tarojs/redux: 1.2.17 => 1.2.14 
      @tarojs/redux-h5: 1.2.17 => 1.2.14 
      @tarojs/router: 1.2.17 => 1.2.14 
      @tarojs/taro: 1.2.17 => 1.2.14 
      @tarojs/taro-alipay: 1.2.17 => 1.2.14 
      @tarojs/taro-h5: 1.2.17 => 1.2.14 
      @tarojs/taro-swan: 1.2.17 => 1.2.14 
      @tarojs/taro-tt: 1.2.17 => 1.2.14 
      @tarojs/taro-weapp: 1.2.17 => 1.2.14 
      @tarojs/webpack-runner: 1.2.17 => 1.2.14 
      eslint-config-taro: 1.2.17 => 1.2.14 
      eslint-plugin-taro: 1.2.17 => 1.2.14 
      nervjs: ^1.3.9 => 1.3.12 
    npmGlobalPackages:
      typescript: 3.2.2
    报错平台: 支付宝小程序

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
重启下开发者工具看看能否正常，目测应该是开发者工具的问题

**Comment by easonchiu** [comment]
额...尝试如下
1. 关掉支付宝开发者工具，重新打开，问题还在
2. 全部关掉，重启，再打开重新编译build模式，问题还在
3. 编译dev模式，问题还在
4. 打开代码保存了一下，热更新...好了....

**Comment by luckyadam** [comment]
> 额...尝试如下
> 
> 1. 关掉支付宝开发者工具，重新打开，问题还在
> 2. 全部关掉，重启，再打开重新编译build模式，问题还在
> 3. 编译dev模式，问题还在
> 4. 打开代码保存了一下，热更新...好了....

使用的是最新版本的支付宝开发者工具么

**Comment by easonchiu** [comment]
使用的是  0.27.1 版本

**Comment by easonchiu** [comment]
@luckyadam 昨天在排除问题的时候发现，造成该错误的原因是我把自己写的一些组件扔在了src目录下自己建立并命名的目录内，当我把这些组件移至components目录内之后，该错误消失了.....你知道这里有什么讲究吗

**Comment by Chen-jj** [comment]
@easonchiu 应该不影响。如果还有问题，可以新建一个原生支付宝项目对比一下。
