### ISSUE TITLE
app.js 里面的 config = {} 无法支持 String 格式

### ISSUE THREAD

**Issue by wzxm** [NervJS/taro#245]
![image](https://user-images.githubusercontent.com/13127730/42144861-0ae6b812-7df0-11e8-8590-bbb4edf4c91a.png)

目前只能写成 config = {}，是否可以支持 config = ‘{}’ 写法？

**Comment by yuche** [comment]
你说的是
```js
config = {
  'pages': [...]
}
```
这样的写法吧。
如果是这样，那应该和 https://github.com/NervJS/taro/issues/235 一样，下个版本发布就可以了。

如果是用字符串把一个对象包起来
```js
config = `{
  'pages': [...]
}`
```
这样的写法毫无意义啊。

**Comment by wzxm** [comment]
是的，我刚进入误区了。已经找到解决方法。
