### ISSUE TITLE
支持 hooks

### ISSUE THREAD

**Issue by briefguo** [NervJS/taro#2455]
NervJS会考虑支持hooks吗？这样在taro里也可以应用起来。

有看过一些taro的文档，实例化组件必须要是class
> https://nervjs.github.io/taro/docs/component.html
> 这里 Taro 和 React 不一样的地方在于没有暴露出一个 createClass 的方法，你只能用 ES6 的 class 类来创建 Taro 组件。

**Comment by coppyC** [comment]
我觉得很难。现在函数组件都不支持，别说hooks了。

**Comment by yuche** [comment]
已经在做了

**Comment by yuche** [comment]
close via 4aa409fb1fc5e6197a6f69e7392519716efb9d13
