### ISSUE TITLE
三目运算条件下的map循环会报错

### ISSUE THREAD

**Issue by phonet** [NervJS/taro#2457]
**问题描述**
[问题描述：三目运算条件下的map循环会报错

**复现步骤**
[复现问题的步骤]
1.showSelectTimeModal 是一个三目运算的条件
2.满足条件下的代码里面有  takeOutTimes.length > 0 && takeOutTimes.map和   currentTakeDate.times.length > 0 && currentTakeDate.times.map两个map循环
3. 此时第二个map就会报错
![image](https://user-images.githubusercontent.com/3205180/54469880-908ac680-47d9-11e9-8ce2-0d0c4ddff73c.png)

[或者可以直接贴源代码，能贴文字就不要截图]

// 代码如下
{
                    showSelectTimeModal &&
                    <FloatLayout
                        onCloseLayout={() => {
                            this.setState({showSelectTimeModal: false});
                        }}>
                        <View className="flex-col package-wrap">
                            <View className="flex-row flex-ac flex-sb modal-header">
                                <Button className="title-btn cancel hide"
                                        hoverClass="hover"
                                        onClick={this.useRedPackModal.bind(this)}
                                >
                                    取消
                                </Button>
                                <View className="flex1 title">请选择送达时间</View>
                                <Button className={`title-btn confirm`}
                                        hoverClass="hover"
                                        disabled={!currentRedPackage.id}
                                        onClick={this.useRedPackModal.bind(this, true)}
                                >
                                    确定
                                </Button>
                            </View>
                            <View className="flex-row time-wrap">
                                <Block>
                                    <View className="left">
                                        {
                                            takeOutTimes.length > 0 && takeOutTimes.map((o, i) => {
                                                return (
                                                    <View key={i}
                                                          className={`item ${currentTakeDate.date === o.date ? "active" : ""}`}
                                                          onClick={() => {
                                                              this.setState({currentTakeDate: o});
                                                          }}
                                                    >
                                                        {o.date}
                                                    </View>
                                                );
                                            })
                                        }
                                    </View>
                                    <View className="flex1 right">
                                        {
                                            currentTakeDate.times.length > 0 && currentTakeDate.times.map((o, i) => {
                                                return (
                                                    <View key={i}
                                                          className={`item ${currentTakeTime === o ? "active" : ""}`}
                                                          onClick={() => {
                                                              this.setState({currentTakeTime: o});
                                                          }}
                                                    >
                                                        {o}
                                                    </View>
                                                );
                                            })
                                        }
                                    </View>
                                </Block>
                            </View>
                        </View>
                    </FloatLayout>
                }

**期望行为**
能够正确渲染出map循环

**报错信息**

![image](https://user-images.githubusercontent.com/3205180/54469884-ad26fe80-47d9-11e9-8e82-bfecf954397b.png)
![image](https://user-images.githubusercontent.com/3205180/54469888-b9ab5700-47d9-11e9-904c-a7bd4c82039d.png)

**系统信息**

 - 操作系统: Windows 7
 - Taro 版本1.2.17
 - Node.js 版本10.15.0
 - 报错平台  weapp

**补充信息**
[可选]
群里大佬说会出现两次循环渲染,待修复

**Comment by yuche** [comment]
你的代码又缺少内容了，能不能走点心啊
