### ISSUE TITLE
ReferenceError: setStore is not defined

### ISSUE THREAD

**Issue by xiamu14** [NervJS/taro#2458]
**问题描述**
项目里使用了 mobx [[，编译小程序时，微信小程序开发工具会提示如下图所示的这个错误：
![](http://static.ohcat.xyz/ping-mu-kuai-zhao-2019-03-16-xia-wu-2-41-56-png%282019-03-16T14:51:38+08:00%29.png)

**复现步骤**
[复现问题的步骤]
1. 新建项目使用 mobx 或在旧项目中依照官方文档添加 mobx
2. yarn dev:weapp 启动小程序调试
3. 在微信小程序控制台中 "console " 查看，第一个错误就是

[或者可以直接贴源代码，能贴文字就不要截图]

app.js 使用 mobx 的和官方一致，如下：

```js
import Taro, { Component } from '@tarojs/taro'
import { Provider } from '@tarojs/mobx'
import counterStore from './store/counter'
import Index from './pages/index'

import './app.scss'

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

const store = {
  counterStore
}
```

**期望行为**
微信开发工具不再报错
**报错信息**

VM107:1 thirdScriptError 
 sdk uncaught third Error 
 setStore is not defined 
 ReferenceError: setStore is not defined

[这里请贴上你的**完整**报错截图或文字]
![](http://static.ohcat.xyz/ping-mu-kuai-zhao-2019-03-16-xia-wu-2-56-28-png%282019-03-16T14:56:58+08:00%29.png)
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Mac mojave 10.14.3]
 - Taro 版本 [Taro v1.2.19]
 - Node.js 版本 [Node v8.11.1]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
新创建的 mobx 项目会报这个错？

**Comment by xiamu14** [comment]
> 新创建的 mobx 项目会报这个错？

无论是新建 mobx ，还是在旧项目里添加 mobx ,都会报这个错误。

**Comment by luckyadam** [comment]
@xiamu14  没有复现，我新创建了一个项目

**Comment by xiamu14** [comment]
> @xiamu14 没有复现，我新创建了一个项目

我将新建后报错的项目代码上传到这个仓库了： git@github.com:xiamu14/taro_setStore_bug_demo.git
同时录制了新建项目到小程序工具调试报错的整个过程视频，视频地址：http://static.ohcat.xyz/output.mp4

**Comment by yzStrive** [comment]
我新加的dva项目也出现这个bug

**Comment by yzStrive** [comment]
解决了 store和@tarojs/redux的导入顺序问题

**Comment by xiamu14** [comment]
> 解决了 store和@tarojs/redux的导入顺序问题

? 我的项目报错是使用的 @tarojs/mobx ，后来官方关掉了 issue ，我就换 redux 了，redux 倒是没问题。
