### ISSUE TITLE
下拉刷新和下拉加载要怎么写

### ISSUE THREAD

**Issue by dzlishen** [NervJS/taro#2460]
如题。

**Comment by ChandlerVer5** [comment]
1：使用ScrollView 为基础，进行书写；
2：自己通过touch 事件判断。

**Comment by luckyadam** [comment]
小程序本身支持
H5 的话目前得用 ScrollView 自己来做

**Comment by kid1412621** [comment]
@luckyadam 我的列表下方还有 view ,是不是只有用 scrollView 来实现?

**Comment by haohailong1990** [comment]
请问下拉刷新，上拉加载怎么弄呢
