### ISSUE TITLE
lost params in chooseImage types

### ISSUE THREAD

**Issue by zWingz** [NervJS/taro#2461]
**问题描述**

`Taro.chooseImage`中的`types`定义少了`success`和`fail`

[line](https://github.com/NervJS/taro/blob/master/packages/taro/types/index.d.ts#L1410)

**系统信息**

 - Taro 版本 [e.g. v1.2.16]

**Comment by zWingz** [comment]
如果只支持`promise` 不支持`success`回调的话, 那在`jsdoc`里就不要加上`demo`的回调写法

**Comment by luckyadam** [comment]
`success` 回调也支持，不过在 typing 了漏了，可以提个 pr 啊
