### ISSUE TITLE
form的submit handler无法响应

### ISSUE THREAD

**Issue by HSUCHING** [NervJS/taro#2462]
**问题描述**
定义了form与submit, submit handler 根本调用不到

**复现步骤**
直接在微信开发工具中使用

[或者可以直接贴源代码，能贴文字就不要截图]

```js
page/index/index.js中:
  formSubmit = e => {
	  console.log('aaaa')
  }

  render () {
    return (
      <Form onSubmit={this.formSubmit} onReset={this.formReset} >
        <View className='example-body'>
          <Switch name='switch' className='form-switch'></Switch>
          <Button form-type="submit">Submit</Button>
        </View>
      </Form>
    )
  }

```

**期望行为**
正常调用，打印时间响应吧

**报错信息**
formSubmit 没有定义

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [mac]
 - Taro 版本 [最新]
 - Node.js 版本 [v1.2.19]
 - 报错平台 [weapp]

**补充信息**

**Comment by luckyadam** [comment]
没有复现，请提供一个可以复现的 demo
