### ISSUE TITLE
h5环境中picker组件mode='region'，选择器中的省市区部分都是空白

### ISSUE THREAD

**Issue by wswax** [NervJS/taro#2464]
问题描述
在h5环境中使用picker插件，发现以下问题：
设置mode='region'，设置默认值，点击出现的选择其中，三栏均为空白。

复现步骤
[复现问题的步骤]

Go to '...'
Click on '....'
Scroll down to '....'
See error
[或者可以直接贴源代码，能贴文字就不要截图]

// 这里可以贴代码
视图部分：

```
<Picker
              mode='region'
              onChange={this.onRegionChange}>
              <View className='picker'>{this.state.regionSel}
              </View>
            </Picker>
```
js部分：

```
this.state = {
      regionSel: '北京市-北京市-朝阳区',
    }
 onRegionChange (regionSel) {
    this.setState({
      regionSel
    })
  }
```
截图：
好吧，不能贴图~
期望行为
正常选择省市区。

报错信息
无报错信息

系统信息

操作系统: [e.g. mac]
Taro 版本 [e.g. 1.2.16]
Node.js 版本 [e.g. v10.14.2]
报错平台 [chrome浏览器]
补充信息
十分感谢！无补充信息

**Comment by jinjinjin0731** [comment]
h5 中不支持 mode='region'。因为地址 JSON 数据太大。你可以使用多列选择器自行实现

**Comment by wswax** [comment]
> h5 中不支持 mode='region'。因为地址 JSON 数据太大。你可以使用多列选择器自行实现

@jinjinjin0731 嗯，好的，多谢啦！

**Comment by melunar** [comment]
确实不支持 但是taro官方文档还写了支持H5。。。。
