### ISSUE TITLE
SearchBar组件-placeholder真机也出现文字重叠，vx版本7.0.2

### ISSUE THREAD

**Issue by Iovedw** [NervJS/taro#2467]
<AtSearchBar
  actionName='搜一下'
  placeholder='搜索一下'
  value={this.state.searchValue}
  onChange={this.onChange.bind(this)}
  onActionClick={this.onActionClick.bind(this)}
/>

**Comment by luckyadam** [comment]
SearchBar 是什么

**Comment by shaodahong** [comment]
@luckyadam 他说的应该是 taro-ui 的 SearchBar 组件
