### ISSUE TITLE
版本1.2.19引入taro-ui报错

### ISSUE THREAD

**Issue by LittleBitCode** [NervJS/taro#2468]
taro版本1.2.19
taro-ui版本2.0.2
已经在`config/index.js`文件中引入
`h5: {
    esnextModules: ['taro-ui']
}`
运行`yarn run dev:h5`仍然出现一下错误

./node_modules/taro-ui/dist/h5/components/countdown/index.js 105:11
Module parse failed: Unexpected token (105:11)
You may need an appropriate loader to handle this file type.
|     } = this.state;
| 
>     return <View className={classNames({
|       'at-countdown': true,
|       'at-countdown--card': isCard

但是taro版本切换至1.2.15就可以正常运行

**Comment by luckyadam** [comment]
升级到最新版本

**Comment by LittleBitCode** [comment]
谢谢

**Comment by JevonYang** [comment]
我也是一样的问题，报错也是一样的，只要引入taro-ui的组件就会报错。下面是我使用的版本，我运行的是h5
```
    "@tarojs/async-await": "1.2.23",
    "@tarojs/components": "1.2.23",
    "@tarojs/redux": "1.2.23",
    "@tarojs/redux-h5": "1.2.23",
    "@tarojs/router": "1.2.23",
    "@tarojs/taro": "1.2.23",
    "@tarojs/taro-alipay": "1.2.23",
    "@tarojs/taro-h5": "1.2.23",
    "@tarojs/taro-swan": "1.2.23",
    "@tarojs/taro-tt": "1.2.23",
    "@tarojs/taro-weapp": "1.2.23",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "taro-ui": "^2.0.2"
```
