### ISSUE TITLE
事件绑定问题, 自定义组件使用 redux 的 connect 包裹后，this 指向了 Connect 

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#247]
![image](https://user-images.githubusercontent.com/23295172/42154717-0dbc64fa-7e19-11e8-9f15-be0f3df5a9ca.png)
页面与组件的关系

![image](https://user-images.githubusercontent.com/23295172/42154680-fa2626e2-7e18-11e8-9cb6-15d07576ac50.png)
相关代码

版本
👽 Taro v0.0.63

**Comment by Dithub2016** [comment]
![image](https://user-images.githubusercontent.com/23295172/42159923-15854ac6-7e28-11e8-97b2-a1d8b168bccf.png)
如果是这样子写的话，问题依旧
Do not have AddressListItem__log handler in current page: pages/tools/addressList/index. Please make sure that AddressListItem__log handler has been defined in pages/tools/addressList/index, or pages/tools/addressList/index has been added into app.json

**Comment by Dithub2016** [comment]
```javascript
onDeleteAddress = (id) => {
    this.props.asyncDeleteAddress(id);
  }
  onSetDefaultAddress = (id) => {
    this.props.asyncSetDefaultAddress(id);
  }
  render () {
    const {
      name, phone, address, isdefault, id,
    } = this.props;
    const {
      status,
    } = this.state;
    return (
      <View className={'address-item' + ' ' + status}>
        <View className="address-item___edit">
          <View className="set-default" onClick={this.onSetDefaultAddress.bind(this, id)}>设为默认</View>
          <View className="delete" onClick={this.onDeleteAddress.bind(this, id)}>删除</View>
        </View>
      </View>
    )
  }
```
这样写的话会报
![image](https://user-images.githubusercontent.com/23295172/42160146-b6357f4a-7e28-11e8-9585-d353dd4f1c81.png)

**Comment by finian** [comment]
第一个示例代码中，语法有问题吧：

```
onEditStatus = () => {
  this.setState({status: 'edit'...}) // <--
}
```

**Comment by Dithub2016** [comment]
@finian 抱歉，这是 webstorm 的代码折叠而已

**Comment by Dithub2016** [comment]
第一个例子在 0.0.64 版本没有再出现，
第二个例子把箭头函数换回function 写法就好了

**Comment by Dithub2016** [comment]
```javascript
@connect(
  () => ({}),
  dispatch => ({
    asyncDeleteAddress: id => dispatch(asyncDeleteAddress(id)),
    asyncSetDefaultAddress: id => dispatch(asyncSetDefaultAddress(id)),
  })
)
export default class AddressListItem extends Component {
  onDeleteAddress = () => {
      console.log(this)
      this.props.asyncDeleteAddress(this.props.id);
    }
    onSetDefaultAddress = () => {
      console.log(this)
      this.props.asyncSetDefaultAddress(this.props.id);
    }
  render() {
    return (
      <View className="address-item___edit">
        <View className="set-default" onClick={this.onSetDefaultAddress}>设为默认</View>
        <View className="delete" onClick={this.onDeleteAddress}>删除</View>
   </View>
    )
  }
}
```
输出的 `this` 指向了 Connect
这是输出的东西
![image](https://user-images.githubusercontent.com/23295172/42194454-a32a1fc2-7ea6-11e8-9cf0-4ee2a15346d0.png)
