### ISSUE TITLE
在开发时如何配置js文件压缩？

### ISSUE THREAD

**Issue by TonyLiuYan** [NervJS/taro#2470]
在开发时如何配置js文件压缩？

**Comment by luckyadam** [comment]
NODE_ENV=production taro build --type weapp --watch

**Comment by js-newbee** [comment]
> NODE_ENV=production taro build --type weapp --watch

这边还得加一个变量用来区分dev、prod 配置哈
NODE_ENV=production BUILD_ENV=development taro build --type weapp --watch

然后在 ./config/index 中修改
if (process.env.NODE_ENV === 'development' || process.env.BUILD_ENV === 'development') {
  return merge({}, config, require('./dev'))
}

**Comment by luckyadam** [comment]
yeap！

**Comment by TonyLiuYan** [comment]
反馈本地环境实际使用测试结果
环境：
window 10
taro：1.2.13

在package.json文件中,添加一条新的命令 
`NODE_ENV=production taro build --type weapp --watch`
执行后控制台输出
```
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
更改命令为：
`set NODE_ENV=production && taro build --type weapp --watch`
可以正常执行并监听文件，但是文件并没有压缩

继续更改命令为：
`set NODE_ENV=production BUILD_ENV=development && taro build --type weapp --watch`
可以正常执行，执行后的dist文件夹确实比之前小了一些，可以解决目前的问题

---
但是，在dist文件夹中的js文件并没有进行压缩，js文件中还存在大量的换行和空格
尝试修改配置文件添加如下信息，但是未能解决
```
plugins: {
    uglify: {
      enable: true,
      config: {
        // 配置项同 https://github.com/mishoo/UglifyJS2#minify-options
      }
    }
  },
```
请问，如何解决上述问题？谢谢

**Comment by luckyadam** [comment]
`NODE_ENV=production taro build --type weapp --watch` 
执行即可
![image](https://user-images.githubusercontent.com/1782542/54575070-ba3c2b80-4a2d-11e9-9d7d-8adaaf7407e8.png)
![image](https://user-images.githubusercontent.com/1782542/54575080-c0caa300-4a2d-11e9-8bfb-97e586106742.png)

**Comment by js-newbee** [comment]
@TonyLiuYan 用 npx + cross-env 试试
`npx cross-env NODE_ENV=production taro build --type weapp --watch`
