### ISSUE TITLE
Taro.chooseImage报错

### ISSUE THREAD

**Issue by dadongfang** [NervJS/taro#2474]
**问题描述**
使用Taro的选择图片方法，或taro-ui的AtImagePicker组件，均报错，“Uncaught TypeError: _taroH2.default.chooseImage is not a function“

**复现步骤**
import Taro, { Component } from '@tarojs/taro'
Taro.chooseImage()

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
![image](https://user-images.githubusercontent.com/6994971/54520458-b82d8a80-49a3-11e9-9c43-013ffe80e054.png)

**系统信息**
$ taro info
� Taro v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.15.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

 - 报错平台 [h5]

**补充信息**
依赖均更新到最新版本

**Comment by luckyadam** [comment]
Close via e496d2f9b80d996ba38d0f8c201c3bd46ad7072e.

**Comment by zhangpengbin** [comment]
> Close via [e496d2f](https://github.com/NervJS/taro/commit/e496d2f9b80d996ba38d0f8c201c3bd46ad7072e).

这个是怎么解决了呢？
