### ISSUE TITLE
请问一下这个new feature何时会提上日程

### ISSUE THREAD

**Issue by 349989153** [NervJS/taro#2476]
首先理解你们工作都非常忙，taro也帮广大技术人员解决了很大的问题。

然后问下：
https://feathub.com/NervJS/taro/+13
这个feature什么时候会提上日程？

**Comment by vimcaw** [comment]
feathub 里面已经写明不能实现的原因了

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/54575281-73026a80-4a2e-11e9-8b71-5f987fd53a07.png)
可以一试

**Comment by vimcaw** [comment]
@luckyadam 我后面在浏览器 Console 试了下，`loaction.go` 貌似不是同步的，这样连续调用的话，返回层级少的话没问题，但是当返回层级过多时我这里会出现还没返回到那个层级就已经替换了当前页面，可能需要在调用`loaction.go` 之前监听 [popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) 事件，再在事件触发时执行替换。

**Comment by Littly** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/54575281-73026a80-4a2e-11e9-8b71-5f987fd53a07.png)
> 可以一试

已经用这个方式实现了 但是个人觉得比较假
