### ISSUE TITLE
以前搭建的taro1.2.15 如果继承 PureComponent 使用 "@tarojs/cli": "^1.2.20", 版本编译会报错 

### ISSUE THREAD

**Issue by pbbisme** [NervJS/taro#2477]
**问题描述**
使用 "@tarojs/cli": "1.2.15" 初始化的项目如果组件有继承PureComponent 这个类 在使用最新  "@tarojs/cli": "^1.2.20", 运行会报错。

**复现步骤**
[复现问题的步骤]
1. 使用如下版本的taro依赖开发项目
2. 使用最新版本的taro/cli 编译
3. npm run dev:h5
4. Uncaught (in promise) TypeError: Super expression must either be null or a function, not undefined

[或者可以直接贴源代码，能贴文字就不要截图]
tarojs 依赖版本
```js
               "@tarojs/async-await": "1.2.15",
		"@tarojs/components": "1.2.15",
		"@tarojs/redux": "1.2.15",
		"@tarojs/redux-h5": "1.2.15",
		"@tarojs/router": "1.2.15",
		"@tarojs/taro": "1.2.15",
		"@tarojs/taro-alipay": "1.2.15",
		"@tarojs/taro-h5": "1.2.15",
		"@tarojs/taro-swan": "1.2.15",
		"@tarojs/taro-tt": "1.2.15",
		"@tarojs/taro-weapp": "1.2.15",	 
		"@tarojs/plugin-babel": "1.2.15",
		"@tarojs/plugin-csso": "1.2.15",
		"@tarojs/plugin-sass": "1.2.15",
		"@tarojs/plugin-uglifyjs": "1.2.15",
		"@tarojs/webpack-runner": "1.2.15",

```

**期望行为**
编译、运行 正常

**报错信息**
![image](https://user-images.githubusercontent.com/18674723/54531394-22ecbf00-49c0-11e9-84d5-3124e0b0f951.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro v1.2.20
  Taro CLI 1.2.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
不知道是bug 还是不向下兼容，把taro依赖全升级到最新 1.2.20 没问题

**Comment by Littly** [comment]
cli和项目依赖使用相同版本吧~ 否则是有可能出现各种奇怪的问题的

**Comment by pbbisme** [comment]
好的，谢谢
