### ISSUE TITLE
H5版 ScrollView 标签onScrollToLower 事件无法触发

### ISSUE THREAD

**Issue by lchcoming** [NervJS/taro#2479]
**问题描述**
我们想把自己的小程序编译H5版，但是发现H5版环境下，ScrollView标签的onScrollToLowe事件无法触发，导致无法下拉刷新，另外onScroll也无法触发事件。

**复现步骤**
[复现问题的步骤]
1. 启动taro h5编译版本
2. home加载商品
3. 下拉列表到底部无法触发onScrollToLower刷新事件

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
test = () => {
    console.log("111111111111 test");
  }

  render() {
    return (
      <ScrollView
        scrollY
        className='scroll-wrapper'
        onScrollToLower={this.test}
      >
        <View className='home'>
          <View className='main'>
            <View className='split-line'></View>
            <Text className='recommend'>猜你喜欢</Text>
            <GoodsList goodParam={{group_id: LIKES_URL}} />
          </View>
        </View>
      </ScrollView>
    )
  }
```

**期望行为**
ScrollView滑动到容器底部可以触发onScrolltolower事件

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.2.0-beta.16
 - Node.js 版本 8.10.0
 - 报错平台 h5

**补充信息**
[可选]
我把页面其他相关信息都删除了，只保留了列表和onScrolltolower事件，事件依然没有触发，目前我们的小程序是没有问题，所以现在不想升级taro的版本，希望能够在此版本上解决。

**Comment by juxiaowei** [comment]
Taro v1.2.20


  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.20 => 1.2.20
      @tarojs/components: 1.2.20 => 1.2.20
      @tarojs/plugin-babel: 1.2.20 => 1.2.20
      @tarojs/plugin-csso: 1.2.20 => 1.2.20
      @tarojs/plugin-sass: 1.2.20 => 1.2.20
      @tarojs/plugin-uglifyjs: 1.2.20 => 1.2.20
      @tarojs/router: 1.2.20 => 1.2.20
      @tarojs/taro: 1.2.20 => 1.2.20
      @tarojs/taro-alipay: 1.2.20 => 1.2.20
      @tarojs/taro-h5: 1.2.20 => 1.2.20
      @tarojs/taro-swan: 1.2.20 => 1.2.20
      @tarojs/taro-tt: 1.2.20 => 1.2.20
      @tarojs/taro-weapp: 1.2.20 => 1.2.20
      @tarojs/webpack-runner: 1.2.20 => 1.2.20
      eslint-config-taro: 1.2.20 => 1.2.20
      eslint-plugin-taro: 1.2.20 => 1.2.20
      nervjs: ^1.3.9 => 1.3.12
    npmGlobalPackages:
      typescript: 3.2.2



onScroll 可以触发
onScrolltolower onScrolltoupper 不能触发

**Comment by jinjinjin0731** [comment]
@juxiaowei  onScrollToUpper 驼峰写法。  @lchcoming 你的问题升级到最新版本即可解决
