### ISSUE TITLE
H5 端scrollView ui组件 onScrollToLower中改变渲染内容数据，会自动滚到顶部，触发onScroll 和 onScrollToupper，  小程序端没有问题

### ISSUE THREAD

**Issue by zwblue** [NervJS/taro#2481]
![image](https://user-images.githubusercontent.com/33955555/54575012-7a754400-4a2d-11e9-8199-6c5043649876.png)
步骤：
1、我加载更多数据时
2、渲染的内容state数组内容增多
3、在小程序端是不滚动到顶部，不触发onScroll事件与onScrollToUpper事件，直接在当前显示内容的后面追加内容
4、而在h5端中， 内容是追加了，但自动滚动到顶部了，触发了onScroll事件与onScrollToUpper事件
版本号：
 "@tarojs/async-await": "1.2.16",
    "@tarojs/components": "1.2.16",
    "@tarojs/redux": "1.2.16",
    "@tarojs/redux-h5": "1.2.16",
    "@tarojs/router": "1.2.16",
    "@tarojs/taro": "1.2.16",
    "@tarojs/taro-alipay": "1.2.16",
    "@tarojs/taro-h5": "1.2.16",
    "@tarojs/taro-swan": "1.2.16",
    "@tarojs/taro-tt": "1.2.16",
    "@tarojs/taro-weapp": "1.2.16",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "taro": "^0.0.7"

**Comment by jinjinjin0731** [comment]
不要重复开相同的问题，上一条已经回复了，更新到最新版本

**Comment by DuduStyle** [comment]
更新并没有解决问题 @jinjinjin0731

**Comment by lidaining-web** [comment]
更新并没有解决问题啊  我也遇到了
