### ISSUE TITLE
Taro 如何setState对象的属性值

### ISSUE THREAD

**Issue by LeeYoung-s** [NervJS/taro#2482]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by LeeYoung-s** [comment]
this.state = {
      test1: 'test',
      stateTest: {
        test: 'liyang'
      }
}

testSetState() {
    let key = 'stateTest.test'
    let key1 = 'test1'
    console.log('修改前的：' + this.state.stateTest.test)
    console.log('修改前的test1：' + this.state.test1)
    this.setState({
      [key]: 'liyang.eos*100',
      [key1]: 'test1update'
    }, () => {
      console.log('修改后的：' + this.state.stateTest.test)
      console.log('修改后的test1：' + this.state.test1)
    })
  }

 输出：
 修改前的：liyang
 修改前的test1：test
 修改后的：liyang
 修改后的test1：test1update

**Comment by tuoxie15** [comment]
@LeeYoung-s 
```
setupBarConfigure: {
        // 是否显示底部栏
        isSetupBar: false,
        // 是否显示书签
        isCatalog: false,
        // 是否打开设置
        isSetUP: false,
        // 设置字体大小
        fontSize: '36rpx',
        // 设置背景颜色
        backColor: '#F8F8F8',
        // 设置字体颜色
        fontColor: '#333333',
},
this.setState({
        setupBarConfigure: Object.assign({}, setupBarConfigure, { fontSize: 14 })
})
```
问问题先把issues格式调好吧...

**Comment by Chen-jj** [comment]
@LeeYoung-s 请看[文档](https://nervjs.github.io/taro/docs/best-practice.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%95%B0%E6%8D%AE-diff)
