### ISSUE TITLE
如何通过 background-image标签引入一个本地的图片文件？

### ISSUE THREAD

**Issue by david2tdw** [NervJS/taro#2483]
**问题描述**

如何在scss文件中通过 background-image标签引入一个本地的图片文件? 
代码里的???应该怎么写？

thanks

**复现步骤**
[复现问题的步骤]
1. 在src/page/home/img目录下添加一个a.png 的图片
2. 在src/page/home目录下创建一个index.scss的文件
3. 添加SCSS样式
```
.img {
    background-image: url('???/a.png')
}
```
**期望行为**
背景图片可以成功引入进来

**报错信息**

背景图片没有生效

**系统信息**
� Taro v1.2.17

  Taro CLI 1.2.17 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 8.11.2 - C:\Program Files\nodejs\node.EXE
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
**补充信息**
除了把图片放到服务器上 还有什么别的解决办法吗？

**Comment by js-newbee** [comment]
按照相对路径引入，url('./img/a.png')

**Comment by david2tdw** [comment]
@js-newbee 已经可以了, 非常感谢！
