### ISSUE TITLE
props属性检测后被添加到了props

### ISSUE THREAD

**Issue by Ariskywi** [NervJS/taro#2486]
**问题描述**
如果在组件中检测了props的某一个属性是否存在，即使该属性不存在，也会被添加到props

**复现步骤**
1、在组件的任意位置检测不存在的属性名
if(this.props.xxx){}，其中xxx属性并不存在。
或者const { xxx } = this.props
2、在nextProps中则会出现xxx属性名。
Object.keys(nextProps)
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
如果组件的props中不存在xxx属性，则任何周期检测xxx属性都是undefined

**报错信息**

无报错

**系统信息**

 - 操作系统: [macOS 10.14.3]
 - Taro 版本 [v1.2.15]
 - Node.js 版本 [10.15.1]
 - 报错平台 [weapp]

**补充信息**
另外#746号 issue仍然存在，还望支持！ 感谢！

**Comment by Chen-jj** [comment]
@Ariskywi 目前我们编译时会找到所有形如 `this.props.xxx` 的成员表达式，然后给每个 props 生成一个对应的小程序的 properties 定义。因此运行时组件会生成默认值为 null 的属性 xxx。

![image](https://user-images.githubusercontent.com/11807297/54613166-3a49ac00-4a95-11e9-914a-8720da79381e.png)

生成默认值为 null 的 xxx 会对你的业务逻辑有影响吗？这里我们最多只能对 if(this.props.xxx) 这种写法做特殊处理，如果 if 里 对 this.props.xxx 做一些类如 ! 的操作或运算我们也是判断不了的。

**Comment by Ariskywi** [comment]
> @Ariskywi 目前我们编译时会找到所有形如 `this.props.xxx` 的成员表达式，然后给每个 props 生成一个对应的小程序的 properties 定义。因此运行时组件会生成默认值为 null 的属性 xxx。
> 
> ![image](https://user-images.githubusercontent.com/11807297/54613166-3a49ac00-4a95-11e9-914a-8720da79381e.png)
> 
> 生成默认值为 null 的 xxx 会对你的业务逻辑有影响吗？这里我们最多只能对 if(this.props.xxx) 这种写法做特殊处理，如果 if 里 对 this.props.xxx 做一些类如 ! 的操作或运算我们也是判断不了的。

首先感谢回复！
虽然对开发造成了困扰，浪费了些时间，但这也不是什么大事情。不过还是希望能在文档中加以说明，避免他人重复踩坑。
另外我对编译原理不是很熟，不太理解为什么一定要生成值为null的properties。不过认为保持一致性当然是越高越好。希望有可能还是多保持一致性。

**Comment by Chen-jj** [comment]
@Ariskywi 为每个 props 都生成小程序的 properties 是因为 props 的实现是基于小程序的 properties 机制的，必须定义好 properties 才能在小程序中从父组件传参给子组件。

**Comment by yuche** [comment]
close via 4aa409fb1fc5e6197a6f69e7392519716efb9d13
