### ISSUE TITLE
更新了 0.0.64 版本，redux 使用上出了点问题

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#249]
```javascript
@connect(
  () => {},
  dispatch => ({
    asyncDeleteAddress: id => dispatch(asyncDeleteAddress(id)),
    asyncSetDefaultAddress: id => dispatch(asyncSetDefaultAddress(id)),
  })
)
```
mapStateToProps 传了个空函数会报错,
如下：
 TypeError: Cannot convert undefined or null to object
    at n.keys (<anonymous>)
    at Connect.stateListener (index.js:136)
    at dispatch (redux.js:227)
    at redux-logger.js:1
    at index.js:14
    at dispatch (redux.js:569)
    at action.js:54
    at <anonymous>

![image](https://user-images.githubusercontent.com/23295172/42193730-da838818-7ea2-11e8-862c-3d4eceecf991.png)
里面的 newMapState 是 undefined,
但这样写在 0.0.63 版本是好的，
现在把 mapStateToProps 参数改成 () => ({}),就好了。
这算是一个 bug 吗?

**Comment by Dithub2016** [comment]
是啊，taro 的版本一升就改了点细节，然后这个参数不打算支持传 `undefined` 的情况吗

**Comment by yuche** [comment]
请问在你升级 64 之前用的是哪个版本？

**Comment by Dithub2016** [comment]
翻 git 记录，到 63 版本之前是以 () => {}, 留空的，
但刚刚回退到 63，64，即使是 65 版本，这个写法都是可以运行，
 没有复现`TypeError: Cannot convert undefined or null to object`这个问题
