### ISSUE TITLE
请问如何mock数据，有相关约定吗？

### ISSUE THREAD

**Issue by jasonlbw** [NervJS/taro#2490]
请问如何mock数据，有相关约定吗？

**Comment by js-newbee** [comment]
Taro 没有提供 mock 也就没有相关约定，
mock 也就是访问某 url 返回 mock 数据，那最简单的就是用 easy-mock(https://easy-mock.com)，注册个账号，用平台提供的 url 就行了，很傻瓜化了
当然也可以本地自建 mock，github 上有很多

**Comment by js-newbee** [comment]
Taro 没有提供 mock 也就没有相关约定，
mock 也就是访问某 url 返回 mock 数据，那最简单的就是用 easy-mock(https://easy-mock.com)，注册个账号，用平台提供的 url 就行了，很傻瓜化了
当然也可以本地自建 mock，github 上有很多
