### ISSUE TITLE
map 的 index 指向了 value 的属性 index

### ISSUE THREAD

**Issue by xyxc0673** [NervJS/taro#2492]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
我有一个 collectionList，单个 collection 形同 
```js
collection = {
  index: "TP311.56/247",
  location: "理科阅览区",
  state: "2019-05-18",
}
```
然后我在组件里 map 循环渲染
```js
<View className='collection-list__body'>
  {collectionList.map((collection, index) => {
    return (
      <View className='collection-list__item' key={index}>
      </View>
    )
  })}
</View>
```
然后微信开发者工具 warning
`VM1650:5 Do not set same key \"TP311.56/247 \" in wx:key.`

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 v1.2.12
 - Node.js 版本 v10.13.0
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@xyxc0673 微信小程序的 key 只支持使用遍历对象内的属性或遍历对象本身：

![image](https://user-images.githubusercontent.com/11807297/54611046-2d2abe00-4a91-11e9-9788-39d1137c66d4.png)

因此使用数组下标变量做 key 是不支持的。这里虽然会编译成 `wx:key="index"`，但根据上图，微信小程序其实是会取 collection.index 作为 key。而你循环对象的 index 属性值都为 "TP311.56/247"，因此会报 key 值不要设置相同值的 warning：

![image](https://user-images.githubusercontent.com/11807297/54611309-a75b4280-4a91-11e9-8a55-41b7034658ec.png)

解决办法：使用 collection 的某个可作为唯一标示的属性作 key：

```js
<View className='collection-list__body'>
  {collectionList.map((collection, index) => {
    return (
      <View className='collection-list__item' key={collection.id}>
      </View>
    )
  })}
</View>
```

**Comment by Chen-jj** [comment]
@xyxc0673 之后我们会加上一条 lint 规则，只能使用遍历对象的属性作为 key。

另外使用 index 作为 key，在一些数组更改的情况上会比不写 key 更糟糕。

**Comment by xyxc0673** [comment]
@Chen-jj 
谢谢解答，之前一直用错了。
