### ISSUE TITLE
问题：如何定义路由?

### ISSUE THREAD

**Issue by Jeff-Tian** [NervJS/taro#2493]
我的 pages 目录结构如下：
https://github.com/Jeff-Tian/me/tree/master/src/pages

![image](https://user-images.githubusercontent.com/3367820/54604073-dddc9180-4a80-11e9-9034-8fadac24da96.png)

config 如下：

![image](https://user-images.githubusercontent.com/3367820/54604098-ec2aad80-4a80-11e9-8036-70c5463d31c6.png)

但是实际上访问 http://localhost:10086/identified，却仍然是渲染的 index。

请问该怎么修改？

**Comment by js-newbee** [comment]
H5 默认是 hash 路由，应该访问 localhost:10086/#/pages/identified/identified

**Comment by luckyadam** [comment]
同楼上，也可以自定义 https://nervjs.github.io/taro/docs/config-detail.html#h5router

**Comment by Jeff-Tian** [comment]
非常感谢！@js-newbee, @luckyadam
