### ISSUE TITLE
编译成rn之后，navigateBack delta参数无效，reLaunch提示不支持

### ISSUE THREAD

**Issue by szm1002** [NervJS/taro#2494]
**问题描述**
Taro.navigateBack遇到一个问题
A ==> Taro.navigateTo B , B ==> Taro.navigateTo C 后
C ==> Taro.navigateBack({delta: 2}) 回到了B，而不是A
事实上，不管传delta几都只能回到B

而如果用 Taro.reLaunch({url: 'A'})，则命令行提示 reLaunch 暂时不支持，
但我看文档写的是rn支持的

附文档链接： https://nervjs.github.io/taro/docs/native-api.html#%E5%AF%BC%E8%88%AA

![image](https://user-images.githubusercontent.com/10546694/54606124-e1264c00-4a85-11e9-9d4f-1dcdee4049a1.png)

**复现步骤**
[复现问题的步骤]
必现，见以上问题描述

**期望行为**
C通过 delta 参数能正常返回到A，或通过 reLaunch 返回到A

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/10546694/54606263-4bd78780-4a86-11e9-8d0e-947926b55934.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.3
 - Taro 版本: Taro v1.2.20
 - Node.js 版本: 11.10.1
 - 报错平台: react native

**补充信息**
搜过以前的Issue，以前是可以正常跳转的，不知现在为何不行

**Comment by Pines-Cheng** [comment]
RN 的 reLaunch 暂时还不支持，文档已更新。

**Comment by szm1002** [comment]
> RN 的 reLaunch 暂时还不支持，文档已更新。

那求修复 navigateBack 的 bug，这种需求还是挺常见的吧~~
