### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by tanyoumei** [NervJS/taro#250]
![image](https://user-images.githubusercontent.com/11582736/42193844-9c4e4942-7ea3-11e8-9206-c61083f3c908.png)

**Comment by tanyoumei** [comment]
![image](https://user-images.githubusercontent.com/11582736/42193919-f21512f2-7ea3-11e8-997a-723cbf69654f.png)

**Comment by tanyoumei** [comment]
使用yarn安装就没有问题 😢

**Comment by yuche** [comment]
原因在于淘宝源还没有更新，现在好了
