### ISSUE TITLE
h5 this.$componentType undefined

### ISSUE THREAD

**Issue by catXiaoXiao** [NervJS/taro#2501]
**问题描述**
组件render里打印this.$componentType是undefined

**期望行为**
this.$componentType 可能取值分别为 PAGE 和 COMPONENT，开发者可以根据此变量的取值分别采取不同逻辑

**系统信息**
1.2.4

**Comment by Chen-jj** [comment]
哪个平台？

**Comment by catXiaoXiao** [comment]
> 哪个平台？

h5
