### ISSUE TITLE
RN端 设置View宽度为750px，在iphone7 plus模拟器上没有填充满

### ISSUE THREAD

**Issue by pengxiang-git** [NervJS/taro#2504]
问题描述

RN端 设置View宽度为750px，在iphone7 plus模拟器上没有填充满

复现步骤

1. Taro init myapp
2. 在index.js中添加一个View组件
3. index.scss中设置width：750px，background：red
右边留了一块白色

期望行为
View横向填充满

报错信息

系统信息
Taro v1.2.17

**Comment by Garfield550** [comment]
View 横向填充满为什么不设置 `width: 100%` 或者 `width: 100vw` 呢？

**Comment by pengxiang-git** [comment]
@Garfield550 百分比是一个方法。根据Taro的官方文档将designWidth设置成750，在组件中设置750px，就是屏幕的最大宽度。View设置成750px，在h5和小程序中都是填充满的。设置px显然要比百分比直观

**Comment by pengxiang-git** [comment]
@Pines-Cheng 根据设计稿尺寸（750px），在RN端尺寸都不正常

**Comment by Pines-Cheng** [comment]
iPhone 6/7/8 为 375*667 ，iPhone 6/7/8 plus 为 414*736，750px 只是一个最常用的设计稿的基本尺寸，具体移动端布局要适用多种尺寸设备，肯定要采用弹性布局的方案，H5 和小程序你在 7Plus 看也不是填充满的。

**Comment by pengxiang-git** [comment]
http://px-shop.oss-cn-shanghai.aliyuncs.com/common/1553075426660.jpg
http://px-shop.oss-cn-shanghai.aliyuncs.com/common/1553075561091.jpg
这是我运行的效果图，H5中是可以填满的@Pines-Cheng

**Comment by Pines-Cheng** [comment]
同一机型吗？

**Comment by pengxiang-git** [comment]
是的同一机型

**Comment by Pines-Cheng** [comment]
8ffbc3161a0affef66538cd65be2807d640e206d
