### ISSUE TITLE
ScrollView在h5模式下报错

### ISSUE THREAD

**Issue by hlwen** [NervJS/taro#2509]
**问题描述**
[问题描述：ScrollView在h5模式下报错，没有判断就scroll.destroy()

**复现步骤**
[复现问题的步骤]
1. 使用ScrollView初始化时报错
2.问题原因已找到不知道怎么提交修改代码

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
文件位置node_modules/@tarojs/components/src/components/scroll-view/index.js?4aee
 componentDidUpdate () {
    if (!this.refs.wrapperScroll) {
      return
    }
    this._scroll.destroy()
    this.initScroll()
  }

  componentWillUnmount () {
    this._scroll.destroy()
  }

```

**期望行为**
omponentDidUpdate () {
    if (!this.refs.wrapperScroll) {
      return
    }
    this._scroll && this._scroll.destroy()
    this.initScroll()
  }

  componentWillUnmount () {
    this._scroll && this._scroll.destroy()
  }

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/13469676/54673758-e7740100-4b35-11e9-9923-afa953fa2fbd.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

   System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.11.0/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.11.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.17 => 1.2.17 
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-less: ^1.2.20 => 1.2.20 
      @tarojs/plugin-sass: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/redux: 1.2.17 => 1.2.17 
      @tarojs/redux-h5: 1.2.17 => 1.2.17 
      @tarojs/rn-runner: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-tt: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.0 => 1.3.9 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
更新到最新版本

**Comment by hlwen** [comment]
更新解决了
