### ISSUE TITLE
constructor 的参数props不能取值

### ISSUE THREAD

**Issue by Ariskywi** [NervJS/taro#2510]
**问题描述**
constructor函数的参数不能获取传参

**复现步骤**

1、构建一个类
2、调用时传给此类参数
3、在constructor中获取参数

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// component
import Taro, { Component } from '@tarojs/taro'
import PropTypes from 'prop-types'
import { View } from '@tarojs/components'
class TestComponent extends Component {
    constructor(props) {
        super(props)
        const { defaultKeys } = props
        console.log(defaultKeys)
    }
    render() {
        return <View>Test</View>
    }
}
// use
render() {
        return <TestComponent defaultKeys={['1']} />
    }
```

**期望行为**
constructor的参数可以获取传值

**报错信息**

无报错

**系统信息**
Taro v1.2.15
OS: macOS 10.14.3
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.9.0 

**补充信息**

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8

在 componentWillMount 里获取吧

**Comment by Ariskywi** [comment]
> https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
> 
> 在 componentWillMount 里获取吧

感谢提醒！ 发现在constructor中使用this.props可以正常获取。

```js
const { defaultKeys } = this.props
```
如果不被修改的话，希望可以在文档中加一句。
