### ISSUE TITLE
Page继承编译失败

### ISSUE THREAD

**Issue by XiaogeTek** [NervJS/taro#2511]
**问题描述**
定义一个Base页面类作为页面基类，具体页面继承该Base，编译失败

[Page基类]

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
// import './index.scss'

export default class Base extends Component {

  render () {
    return (
      <View className='index'>
        <Text>perfect!!!!!!!!</Text>
      </View>
    )
  }
}
```

[页面Index类]

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'
import Base from "../base"

export default class Index extends Base {

  config = {
    navigationBarTitleText: '首页'
  }

  constructor() {
    super(...arguments)
  }
}
```

**期望行为**
目前Component可以通过继承得到多个子类组件，希望Page也能够支持这种用法，通过继承公共父类Page获得多个子类Page

**报错信息**
![image](https://user-images.githubusercontent.com/14268395/54676702-3ae94d80-4b3c-11e9-989c-d5c0209c921b.png)

**demo工程**
[PageExtend.zip](https://github.com/NervJS/taro/files/2991284/PageExtend.zip)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 v1.2.17
 - Node.js 版本 v10.14.1
 - 报错平台 weapp

**Comment by luckyadam** [comment]
没有复现，页面也是可以继承的，可以的话提供一个 demo

**Comment by XiaogeTek** [comment]
[PageExtend.zip](https://github.com/NervJS/taro/files/2991284/PageExtend.zip)
这个是demo，麻烦了

**Comment by imageslr** [comment]
@XiaogeTek @luckyadam 您好，我也遇到了这个问题，就是简单的继承页面，报错`BasePage is undefined`。请问这个什么情况？

**Comment by imageslr** [comment]
@XiaogeTek 请问你解决了吗

**Comment by luckyadam** [comment]
这个问题看过了，是因为子类没有写 render 方法，所以导致报错，补上 render 方法即可

**Comment by XiaogeTek** [comment]
> 这个问题看过了，是因为子类没有写 render 方法，所以导致报错，补上 render 方法即可

请问一下render是怎么写的，我这边加过，一样报错

**Comment by XiaogeTek** [comment]
@imageslr 还没有~
