### ISSUE TITLE
taro-weapp中getElementById方法中选取id错误

### ISSUE THREAD

**Issue by ShiYuanjun-Tim** [NervJS/taro#2512]
文件[packages/taro-weapp/src/util.js](https://github.com/NervJS/taro/blob/2f39b8cab91c63ee79bd8765522b8c5027041071/packages/taro-weapp/src/util.js#L248)

```
export function getElementById (component, id, type) {
...
res = query.select(id)   // => should be  res = query.select(`#${id}`)
...
}
```

这样会导致 使用该方法获取的NodeRef在使用自己方法时获取不到预期的结果
比如 

```
ref.boundingClientRect(function(res){
这里应该能通过res获取元素定位， 但是实际并不会只会有null
}).exec()
```

**Comment by Chen-jj** [comment]
@ShiYuanjun-Tim 这是给编译时处理循环 ref 时用的，并不是开放给开发者的 API。循环中使用 ref 编译后的代码调用此方法时传入的 ID 会带上 # 号。

**Comment by ShiYuanjun-Tim** [comment]
我发现了是我的分支落后了点， 你在taro-transformer-wx的render.ts中已经修改好了
对比 [改前错误的] 对比 [修改后正确的] 

[改前错误的]:https://github.com/ShiYuanjun-Tim/taro/blob/76e8bb8e537ec752008b7f2a0af73a45cb593cf1/packages/taro-transformer-wx/src/render.ts#L1114
 [修改后正确的]:https://github.com/NervJS/taro/blob/f189960045f1d4086e0e27842605897fe542a759/packages/taro-transformer-wx/src/render.ts#L1357
