### ISSUE TITLE
双重map循环，第一级的index对应不上

### ISSUE THREAD

**Issue by fewiki** [NervJS/taro#2514]
> **问题描述**
> [问题描述：双重map循环，第一级的index有错，对应不上
> 
> **复现步骤**
> 
> ```js
> // taro的 index.tsx
> rooms.map((room, outterIndex) => (
>   <View key={room.id}>
>     <View>房间</View>
>     <View className="men">
>       {room.checkInMen.map(（man, innnerIndex）=> (
>         <View onClick={this.handleRemoveMan.bind(this, outterIndex ,innnerIndex)}>
>           {man.name}
>         </View>
>       ))}
>     </View>
>   </View>
> );
> ```
> 
> ```
> 
> <view wx:for="{{loopArray0}}" wx:for-item="room" wx:for-index="outterIndex">
>   <view>房间</view>
>     <view class="men">
>       <view  data-e-tap-a-b="{{index}}" bindtap="handleRemoveMan" wx:for="{{room.$anonymousCallee__0}}" wx:for-item="man" data-e-tap-so="this" data-e-tap-a-a="{{innnerIndex}}">{{man.$original.name}}
>       </view>
>     </view>
>   </view>
> </view>
> ```
> 
> **期望行为**
> [希望官方可以修复一下这个bug，或者在文档上有所提醒（困扰了一下午）😂]
> 
> **报错信息**
> 
> [点击事件传的第一级index有错，目前发现在规律是，奇数列是对的，偶数列是错的]
> 
> **系统信息**
> 
> > Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
> 
> * 操作系统: [Windows 10]
> * Taro 版本 [v.1.2.16]
> * Node.js 版本 [v.8.12.0]
> * 报错平台 [weapp]
> 
> **补充信息**
> [可选]
> [根据你的调查研究，出现这个问题的原因可能在哪里？]
> 小程序不支持双重index传参？

**Comment by fewiki** [comment]
这样写可以：
![image](https://user-images.githubusercontent.com/13325335/54681878-6c681600-4b48-11e9-86ab-2fa6207fe5eb.png)


这样写传不过去：
![image](https://user-images.githubusercontent.com/13325335/54681886-70943380-4b48-11e9-92d8-22ff0b25f3dc.png)

**Comment by yuche** [comment]
到底怎么样才能复现？
是这样：
```
rooms.map((room, outterIndex) => (
  <View key={room.id}>
    <View>房间</View>
    <View className="men">
      {room.checkInMen.map(（man, innnerIndex）=> (
        <View onClick={this.handleRemoveMan.bind(this, outterIndex ,innnerIndex)}>
          {man.name}
        </View>
      ))}
    </View>
  </View>
);
```

还是这样:
![](https://user-images.githubusercontent.com/13325335/54681886-70943380-4b48-11e9-92d8-22ff0b25f3dc.png)
