### ISSUE TITLE
Taro.getMenuButtonBoundingClientRect()调用失败

### ISSUE THREAD

**Issue by JohnsenZhou** [NervJS/taro#2520]
**问题描述**
`Taro.getMenuButtonBoundingClientRect()`提示此方法不存在

**复现步骤**
`Taro.getMenuButtonBoundingClientRect()`提示此方法不存在，只能通过`wx.getMenuButtonBoundingClientRect()`调用

**期望行为**
`Taro.getMenuButtonBoundingClientRect()`能调用成功

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS Sierra 10.12.6]
 - Taro 版本 [v1.2.12]
 - Node.js 版本 [e.g. v10.14.2]
 - 报错平台 [weapp]

**Comment by XiaogeTek** [comment]
**问题描述**
Taro.getMenuButtonBoundingClientRect()无法取到值

**系统信息**
 - 操作系统: Windows 10
 - Taro 版本 v1.2.21
 - Node.js 版本 v10.14.1
 - 报错平台 weapp
