### ISSUE TITLE
1.2.20升级之后map循环后报错,1.2.13版本正常

### ISSUE THREAD

**Issue by cmideal** [NervJS/taro#2524]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

升级1.2.20版本后,
1、map选择判断if提前，
2、不能设置key前缀

问题截图如下：
![image](https://user-images.githubusercontent.com/4355581/54731973-46845500-4bcc-11e9-98cb-630949aa53d5.png)

![image](https://user-images.githubusercontent.com/4355581/54731979-4c7a3600-4bcc-11e9-8ee4-94d206c9e41c.png)

![image](https://user-images.githubusercontent.com/4355581/54731980-50a65380-4bcc-11e9-940e-cbd7aa98744a.png)

从图中可以看到箭头所指部分应该在map循环里面判断参数，提升到了map之外做判断，因此出错

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.2.20

  Taro CLI 1.2.13 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
发文字

**Comment by cmideal** [comment]
```
 const showtype = this.props.showtype
        const goodcfg = this.props.goodcfg
        const envcls = 'ENV_TYPE' + Taro.getEnv()
        const item = this.props.item
        if (showtype == 1) {
            uiContent = <View className={['goods-container type-1 dir--top', envcls]} >
                {
                    item.map((zkmitem, index) => (
                        <View className='goodslist ' key={index}>
          
                            <View className='info'>
           
                                <View className='price'>
                                    {zkmitem.stores > 0 ? <View className='listbuyNow' reportSubmit='true' onSubmit={this.clickBuy.bind(this, zkmitem.goodsid)}>
                            <Button className='excx-fff clear-btn' form-type='submit' style={goodcfg.activeColor}>
                                立即抢购
                            </Button>
                            </View>
                                    :
                                        <View className={['listbuyNow', 'soldout']} style={goodcfg.disabledColor}>已抢完</View>
                                    }
                                </View >
                            </View >
                        </View >
                    ))
                }
            </View >
        }
```
