### ISSUE TITLE
继承extends后import报错找不到模块

### ISSUE THREAD

**Issue by Ariskywi** [NervJS/taro#2526]
**问题描述**
在B中import 了D，C  extends了 B，并且import了D，在page中import C则报错

**复现步骤**

1. 创建B、C、D模块
2. 在B中import D
3. C继承B模块,并import D
4. 在page中import C模块

```js
// B模块
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import DTest from './DTest'

class BTest extends Component {
    render() {
        return (
            <DTest>
                <View>12121</View>
            </DTest>
        )
    }
}

export default BTest

// C 模块
import Taro, { Component } from '@tarojs/taro'
import BTest from './BTest'
import DTest from './DTest'
import { View } from '@tarojs/components'

class CTest extends BTest {
    render() {
        return (
            <DTest>
                <View>12121</View>
            </DTest>
        )
    }
}

export default CTest

// D模块

import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

class DTest extends Component {
    render() {
        return <View>{this.props.children}</View>
    }
}

export default DTest

// page
import CTest from './CTest'

```

**期望行为**
正常找到该模块

**报错信息**
小程序开发工具报错：
![image](https://user-images.githubusercontent.com/9128673/54735970-d5509c00-4be3-11e9-8574-e454488f6d2c.png)

**系统信息**
Taro CLI 1.2.15 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm

**补充信息**

编译无报错

**Comment by luckyadam** [comment]
这样的引用关系有点复杂
如果 BTest 已经是作为基类了，那么 BTest 最好就不应该有 render 函数，因为目前的机制 render 无法被继承

**Comment by Ariskywi** [comment]
> 这样的引用关系有点复杂
> 如果 BTest 已经是作为基类了，那么 BTest 最好就不应该有 render 函数，因为目前的机制 render 无法被继承

确实，如果在BTest中不引用DTest，则正常编译。但是BTest作为一个组件，提供了默认的使用方式。就实现了render
目的是希望B既可以默认使用,也可以继承使用。
