### ISSUE TITLE
taro-cli 升级到 1.2.21 后编译项目出现乱码

### ISSUE THREAD

**Issue by SunChaoran** [NervJS/taro#2530]
**问题描述**

taro-cli 升级到 1.2.21 后编译项目出现乱码

**复现步骤**

在终端中直接运行以下代码后出现截图中的乱码

```
taro build --type weapp '--watch'
```

**报错信息**
![Screen Shot 2019-03-21 at 16 42 43](https://user-images.githubusercontent.com/6645356/54741122-5f0a6480-4bf8-11e9-9fd3-383bbf016d74.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.2
 - Taro 版本 v1.2.21
 - Node.js 版本 8.11.4

**Comment by SunChaoran** [comment]
补充：

系统语言：英文

WebStorm 的 Terminal 中出现乱码，系统自带 Terminal 并不会出现。

**Comment by yuche** [comment]
那这应该是 WebStrom 的问题。
https://www.google.com/search?q=webstorm+terminal+%E4%B9%B1%E7%A0%81&oq=WebStorm+term&aqs=chrome.5.69i57j0l5.5691j0j7&sourceid=chrome&ie=UTF-8

第一个结果或许能解决：
https://www.jianshu.com/p/41947d5589e0

**Comment by Qingtian239113** [comment]
@yuche 注意看会发现，大部分是路径乱码了，而且我这里还出现了奇怪的情况，一开始并没有乱码，编译到一部分的时候乱码了
![image](https://user-images.githubusercontent.com/9690214/54801093-3342b980-4ca0-11e9-970d-91da81898f2f.png)

**Comment by SunChaoran** [comment]
> @yuche 注意看会发现，大部分是路径乱码了，而且我这里还出现了奇怪的情况，一开始并没有乱码，编译到一部分的时候乱码了
> ![image](https://user-images.githubusercontent.com/9690214/54801093-3342b980-4ca0-11e9-970d-91da81898f2f.png)

是的，我的也是这样。

**Comment by shcping** [comment]
兄弟，解决没有，我也遇到了
