### ISSUE TITLE
1.2.17 版本后的 webpackChain 失效

### ISSUE THREAD

**Issue by zcfan** [NervJS/taro#2534]
**问题描述**
1.2.17 版本后的 webpackChain 失效

**复现步骤**

https://github.com/NervJS/taro/blob/a19d749e68f5be9cf763db4fcbcef342626c0765/packages/taro-webpack-runner/src/index.ts#L29-L51

```js
    customizeChain(webpackChain, config.webpackChain)
```

这一行允许开发者自定义 webpackChain ，但定制后再没有执行过 `toConfig` 因此没有生效。

**期望行为**

webpackChain 定制后应该正常生效

**报错信息**

没有报错，但通过 webpackChain 定制的配置无效

**系统信息**
本 issue 无关系统信息

**补充信息**
调用 `toConfig` 时机挪到 `customizeChain` 下面即可

**Comment by pamler** [comment]
修改的代码虽然已经merge了，但是npm库里1.2.21的版本貌似还是旧的代码

**Comment by Littly** [comment]
更新到版本1.2.22，已修复~

**Comment by zengwmFE** [comment]
@Littly 那是不是1.2.21,webpackChain还是无效得
