### ISSUE TITLE
H5 显示异常，有多余的 0

### ISSUE THREAD

**Issue by zacksleo** [NervJS/taro#2537]
**问题描述**

使用 && 渲染元素时，出现了多余的 0

**复现步骤**

```jsx

{this.state.keywordHistoryShow && <Text>test</Text>}

```

**期望行为**

**报错信息**

 显示出了多余的 0

**系统信息**

👽 Taro v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.20 => 1.2.20 
      @tarojs/cli: 1.2.20 => 1.2.20 
      @tarojs/components: 1.2.20 => 1.2.20 
      @tarojs/plugin-babel: 1.2.20 => 1.2.20 
      @tarojs/plugin-csso: 1.2.20 => 1.2.20 
      @tarojs/plugin-sass: 1.2.20 => 1.2.20 
      @tarojs/plugin-uglifyjs: 1.2.20 => 1.2.20 
      @tarojs/router: 1.2.20 => 1.2.20 
      @tarojs/taro: 1.2.20 => 1.2.20 
      @tarojs/taro-h5: 1.2.20 => 1.2.20 
      @tarojs/taro-weapp: 1.2.20 => 1.2.20 
      @tarojs/webpack-runner: 1.2.20 => 1.2.20 
      eslint-config-taro: 1.2.20 => 1.2.20 
      eslint-plugin-taro: 1.2.20 => 1.2.20 
      nervjs: ^1.3.0 => 1.3.0 
    npmGlobalPackages:
      typescript: 2.7.1

**Comment by SunChaoran** [comment]
v1.2.21 可以复现相同问题

```
{process.env.NODE_ENV === 'development' && (
                    <View className={styles.devTag}>{`dev - ${process.env.VERSION}`}</View>
                )}
```

直接输出了 false 在 UI 上

**Comment by yuche** [comment]
https://codesandbox.io/s/383xzz8vr5
似乎没能复现成功

**Comment by zacksleo** [comment]
@yuche 这个和实际开发环境差别比较大啊，版本和依赖都不一样

**Comment by Littly** [comment]
无法复现这个问题

**Comment by Ding95** [comment]
`
{ !!this.state.keywordHistoryShow && <Text>test</Text> }
`
这样就OK了
