### ISSUE TITLE
子组件的props中的事件没有传值

### ISSUE THREAD

**Issue by Ariskywi** [NervJS/taro#2538]
**问题描述**
组件B继承A
给组件B传递了onChange事件函数
但是在A中调用时发现没有接收到onChange函数，此时this指向B的实例

**复现步骤**
1. 构建父类A，定义事件处理函数onItemChange,并在函数中调用this.props.onChange
2. 构建子类B继承A，视图中可触发this.onItemChange
3. 页面使用组件B，给onChange赋值处理函数

```js
// ATest
import Taro, { Component } from '@tarojs/taro'

class ATest extends Component {
    onItemChange() {
        this.props.onChange()
        console.log(this.constructor)
    }
}

export default ATest

ATest.defaultProps = {
    onChange() {
        console.log(1)
    }
}

// BTest
import { View } from '@tarojs/components'
import ATest from './ATest'

class BTest extends ATest {
    render() {
        return <View onClick={this.onItemChange}>12121</View>
    }
}

export default BTest

//use 

render(){
    return <BTest onChange={() => console.log(2)} />
}

```

输出值为1

**期望行为**
B的实例中,this.props.onChange得到更新，输出值为2

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结Taro CLI 1.2.15 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm

**补充信息**
无

**Comment by wolfjobs** [comment]
same issue

**Comment by yuche** [comment]
close via 4aa409fb1fc5e6197a6f69e7392519716efb9d13
