### ISSUE TITLE
#小程序##eslint#引用小程序原生组件和API的问题

### ISSUE THREAD

**Issue by jylhuhuhu** [NervJS/taro#254]
引用小程序原生组件和api，在编辑器中都会有eslint报错，但是在微信开发者工具中都正常能用，想问一下在生产环境中是否有隐患。eslint经常报错
![66c27449-8354-42e0-ae6e-033ba9fb0803](https://user-images.githubusercontent.com/22792323/42197342-ea0d13e6-7eb4-11e8-8e16-38af0d8a867f.png)
<--------------------- 原生组件 --------------------------->
代码如下：
```
 <View className='test'>
        <movable-area className='mova-area'>
              <movable-view className='movable-view' direction="all">
              </movable-view>
        </movable-area>
      </View>
```
![image](https://user-images.githubusercontent.com/22792323/42199516-7abca3f0-7ec1-11e8-91c9-9663c970c91d.png)

开发者工具中：
![image](https://user-images.githubusercontent.com/22792323/42199449-1dc70db6-7ec1-11e8-8277-68a78b68badf.png)

<--------------------- wx api --------------------------->
`
testbutton() {
    wx.chooseImage({
      
    })
  }
`
![image](https://user-images.githubusercontent.com/22792323/42199650-33a31ab6-7ec2-11e8-9fa7-7e6f8f7ac8e1.png)
在微信开发者工具中能正常调用wx.chooseImage

**Comment by yuche** [comment]
```
 <View className='test'>
        <movable-area className='mova-area'>
              <movable-view className='movable-view' direction="all">
              </movable-view>
        </movable-area>
      </View>
```

你这里写是非法的，要大写。

```
testbutton() {
wx.chooseImage({

})
}

```

这样写也不对，应该是 Taro.chooseImage 开头。
虽然暂时运行起来没问题，但迟早出问题。

建议先看文档：
https://nervjs.github.io/taro/jsx.html
