### ISSUE TITLE
Picker 类型date时候返回的时间格式有问题

### ISSUE THREAD

**Issue by z704600202qj** [NervJS/taro#2541]
Picker 类型date时候返回的时间格式有问题

**Comment by chareice** [comment]
这个问题有进展吗？

**Comment by shenghanqin** [comment]
@chareice @z704600202qj 试试看最新版本吧。我看ChangeLog里面有相应的改动。

**Comment by paulloo** [comment]
我升级到2.0.1版本了，问题依然还在@shenghanqin

**Comment by shenghanqin** [comment]
> 我升级到2.0.1版本了，问题依然还在@shenghanqin

是不是可以借助dayjs来将时间格式再转换一次呢？因为我没怎么用过h5版本。嘻嘻

**Comment by lehug** [comment]
挖坟，这个没有解决吗？ios上面moment('YYYY-M-D')会返回 invalid date
