### ISSUE TITLE
自动打包组件到分包而非全部打包到主包

### ISSUE THREAD

**Issue by excxapp** [NervJS/taro#2542]
### 这个功能解决了什么问题？

全部打包组件到主包造成主包过大

### 你期望的功能是怎样的？

主包用到的组件打包到主包，分包用到到组件打包到分包

### 补充信息

1、主包页面和主包组件用到的组件，打包到主包的npm里面。
2、分包及分包用到的组件打包到分包
3、即使多个分包都用到，但是主包没用到的组件也打包到分包（及时打包到多个分包里面也可以）

**Comment by Chen-jj** [comment]
Taro3 已实现。

**Comment by xiaoyuze88** [comment]
> Taro3 已实现。

@Chen-jj 具体是怎么实现的呢？为啥我这边还是碰到大量分包内组件被打到了主包common.js下。。感觉一个组件被引用超过1次（分包内）都会被打到common？
