### ISSUE TITLE
疑似文档错误

### ISSUE THREAD

**Issue by faremax1992** [NervJS/taro#2543]
https://nervjs.github.io/taro/docs/before-dev-remind.html 文档该页

> 其他注意事项
> 运行时 报缺少包，需要要在 .rn_temp 目录里面安装。
> 文字要包在 Text 组件里面，否则不显示。
> display:fixed React Native 不支持
> Animation 和 transform React Native 动画不支持
> React Native 与 H5/小程序 的 Flex 布局相关属性的默认值有差异

我理解中第三条 display:fixed 应该是 position:fixed 吧？

**Comment by Littly** [comment]
确实如此 欢迎PR..
