### ISSUE TITLE
xcode无法运行taro-native-shell APP壳子

### ISSUE THREAD

**Issue by szm1002** [NervJS/taro#2545]
**问题描述**
按照 react native 端开发流程文档，使用 xcode 打开 taro-native-shell 的 ios 文件夹，build失败，
xcode 提示错误： 'React/RCTBundleURLProvider.h' file not found

![image](https://user-images.githubusercontent.com/10546694/54796679-1dc39480-4c8c-11e9-9212-fac319fb1b6e.png)

**复现步骤**
按照 taro 官方文档操作 https://nervjs.github.io/taro/docs/react-native.html ：

![image](https://user-images.githubusercontent.com/10546694/54796716-49467f00-4c8c-11e9-9acd-f9ceb8314ba3.png)

**期望行为**
使用 xcode 能成功在模拟器上运行项目

**报错信息**
appDelegate.m 文件中报错：  'React/RCTBundleURLProvider.h' file not found

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.3
 - Taro 版本： v1.2.21
 - Node.js 版本： 11.12.0
 - 报错平台： react-native: 0.55.4 => 0.55.4

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
react-native: 0.55.4 => 0.55.4 
RN 依赖换成 0.55.4 还有这个报错吗？

**Comment by szm1002** [comment]
> react-native: 0.55.4 => 0.55.4
> RN 依赖换成 0.55.4 还有这个报错吗？

换成0.55.4还有这个报错。
而且我用xcode直接run react-native cli新建的项目是OK的，说明我电脑上rn环境应该没问题

**Comment by Pines-Cheng** [comment]
这个问题解决了吗？

**Comment by szm1002** [comment]
> 这个问题解决了吗？ @szm1002

没有。。因为项目比较急我已经弃taro转原生rn开发了。。

**Comment by szc807414589** [comment]
我也碰到这个问题了，有解决办法么@Pines-Cheng

**Comment by Pines-Cheng** [comment]
引起这个错误的原因很多，大家看看这个有没有帮助：[“RCTBundleURLProvider.h” file not found - AppDelegate.m](https://stackoverflow.com/questions/40368211/rctbundleurlprovider-h-file-not-found-appdelegate-m)

**Comment by Pines-Cheng** [comment]
参考一下这个：[error: Unable to resolve build file: XCBCore.BuildFile](https://stackoverflow.com/questions/50708012/error-unable-to-resolve-build-file-xcbcore-buildfile)
Xcode 10 特有的问题。

**Comment by glitterlip** [comment]
删除`node_modules` ,`Command + Shift + K`清理 cache 然后重新`npm install`,我用这个可以了

**Comment by Pines-Cheng** [comment]
这个 issue 有用：['config.h' file not found](https://github.com/facebook/react-native/issues/19529)

通过以下几步成功解决：

```
rm -rf node_modules/ && yarn cache clean && yarn install
node_modules/react-native/scripts/ios-install-third-party.sh
cd node_modules/react-native/third-party/glog-0.3.4
./configure
```
https://github.com/facebook/react-native/issues/19529#issuecomment-423898864

**Comment by czy0729** [comment]
这个错误耗了我足足一整天的时间
假如Xcode报错地方在 react-native/Libraries/WebSocket/libfishhook.a  not found的话
试一试这个, https://github.com/facebook/react-native/issues/19569#issuecomment-422691829
