### ISSUE TITLE
H5 如何实现 路由缓存?

### ISSUE THREAD

**Issue by 2788** [NervJS/taro#2546]
从A 进入到B页面,
如何缓存A页面? 这样在返回的时候 停留在上个页面的滚动处, 不至于回到顶部, 也不用重新加载一次数据

**Comment by Littly** [comment]
目前H5端已经有这个功能了 跳转后后退，是可以返回之前页面的滚动位置的

**Comment by caicai199604** [comment]
> 目前H5端已经有这个功能了 跳转后后退，是可以返回之前页面的滚动位置的

小程序端 怎么实现这个页面缓存功能

**Comment by summer-yyyn** [comment]
小程序端 怎么实现这个页面缓存功能

**Comment by caicai199604** [comment]
小程序端 自带页面缓存功能，只要不重新执行方法就会一直保持原有状态




------------------ 原始邮件 ------------------
发件人: "yyyn"<notifications@github.com>; 
发送时间: 2019年8月27日(星期二) 上午10:02
收件人: "NervJS/taro"<taro@noreply.github.com>; 
抄送: "你我真的没什么好说的了"<981900309@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [NervJS/taro] H5 如何实现 路由缓存? (#2546)




小程序端 怎么实现这个页面缓存功能
