### ISSUE TITLE
请问路由传参支持对象吗？

### ISSUE THREAD

**Issue by W-quan** [NervJS/taro#2549]
试了下，新页面不能解析出来传过来的对象

**Comment by 378978764** [comment]
首先通过`JSON.stringify`将参数变成字符串，然后新页面通过`JSON.parse`还原成对象。

**Comment by W-quan** [comment]
@378978764 好像有长度限制

**Comment by 378978764** [comment]
那就跳转前设置storage，跳转之后读取，然后清空

**Comment by W-quan** [comment]
打算用store

**Comment by Retroxs** [comment]
没有长度限制， 只有层级限制

**Comment by yuche** [comment]
参考这个用全局 State，否则要多做一次序列化操作
https://github.com/NervJS/taro-v2ex

**Comment by SupermanChao** [comment]
补充一下：小程序支持45kb左右的参数长度，几乎能满足日常所有的参数传递。
项目中传递对象参数时，使用`JSON.stringify`将对象编程json字符串，自定义key，并将参数追加到`url`后面。
但是这么处理会有些问题，如果该JSON字符串里面存在特殊字符串会导致参数被截断，所以在传入时需要用`encodeURIComponent`编码一下，在取出时用`decodeURIComponent`解码一下。
示例：`url: '、/pages/index/index?obj=encodeURIComponent(obj)'`
