### ISSUE TITLE
$router.preload 的参数不会引起页面变化

### ISSUE THREAD

**Issue by ziermu** [NervJS/taro#2550]
**问题描述**
数据通过$router.preload传递过来，通过if(){}else{}进行判断，在打印数据中if 和else中的值都能打印出来，但是页面不能渲染只能显示同一个。

 render () {
    const {region,toast,tests} = this.state;
    const infosData = this.$router.preload.info;
    const {info} = infosData;
    let persons = info.id ? info.person :this.state.consigneeValue;
    let tel = info.id ? info.tel :this.state.phoneValue;
    let address = info.id ? info.address_two :this.state.detailedValue;

    let current = null;
    if(!info.id){
      console.log('保存11',!info.id)
      current = <View className='saveBtn' onClick={this.saveBtn.bind(this)}>保存1</View>
    }else{
      console.log('保存22',!info.id)
      current = <View className='saveBtn' onClick={this.editorSaveBtn.bind(this)}>保存2</View>
    }
    return (
      <View className='addressInfo'>
       <AtToast isOpened = {toast} text={tests} onClose={this.toastClose.bind(this)}></AtToast>
       <View className='content'>
       <View className='list'>
        <AtInput
            name='persons'
            title='收货人'
            placeholder='收货人'
            type='text'
            value={persons}
            onChange={this.handleChange1.bind(this)}
        />
       </View>
       <View className='list'>
        <AtInput
            name='tel'
            title='联系方式'
            placeholder='联系方式'
            type='phone'  
            value={tel}
            onChange={this.handleChange2.bind(this)}
        />
       </View>
       <View className='areaSelect'> 
        <Picker
            mode='region'
            onChange={this.onChange.bind(this)}
            value={region}
            custom-item="{{customItem}}" 
          >
            <View class="picker">
            地区选择 {region[0]}, {region[1]} ,{region[2]}
            </View>
          </Picker>
       </View>
       <View className='list'>
        <AtInput
            name='value'
            title='详细地址'
            placeholder='详细地址'
            type='text'
            value={address}
            onChange={this.handleChange3.bind(this)}
        />
       </View>
      </View>
      <View className='footer'>
       {current}
      </View>
      </View>
    )

![微信图片_20190322114324](https://user-images.githubusercontent.com/46949224/54804149-78b9b380-4cad-11e9-9b3a-05a112ca6cf8.png)
![微信图片_20190322114254](https://user-images.githubusercontent.com/46949224/54804158-7f482b00-4cad-11e9-91a8-bb970e82dc8c.png)
![微信图片_20190322114310](https://user-images.githubusercontent.com/46949224/54804163-82dbb200-4cad-11e9-86c3-ff3c789dae76.png)
![微信图片_20190322114300](https://user-images.githubusercontent.com/46949224/54804172-853e0c00-4cad-11e9-8d89-a3b5f27b05f9.png)
![微信图片_20190322115026](https://user-images.githubusercontent.com/46949224/54804176-8838fc80-4cad-11e9-9abf-1996e0447010.png)

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.13]
 - Node.js 版本 [e.g. v10.15.0]
 - 报错平台 [ weapp]

**Comment by ziermu** [comment]
补充一下：
 let persons =! info.id ? info.person :this.state.consigneeValue; 这里面的数据是能正常显示的
但是如果改为渲染的
 if(!info.id){
      console.log('保存1',!info.id)
      saveButton = <View className='saveBtn' onClick={this.saveBtn.bind(this)}>保存1</View>
    }else{
      console.log('保存2',!info.id)
      saveButton = <View className='saveBtn' onClick={this.editorSaveBtn.bind(this)}>保存2</View>
    }
这种是一直显示保存1这个按钮，保存2按钮始终不能显示，将他改为三元运算形式，也是这种情况

**Comment by Chen-jj** [comment]
@ziermu 提问请先整理好代码和图片格式

**Comment by ziermu** [comment]
这个问题什么时候解决

**Comment by Chen-jj** [comment]
@ziermu 没懂你的问题，只有此处渲染了一次 current： `<View className='footer'>{current}</View>` ，什么叫 “页面不能渲染只能显示同一个”。

**Comment by Chen-jj** [comment]
@ziermu 测试过没有问题。

页面 A：

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class PageView extends Component {
  state = {
    info: {
      info: {
        id: false
      }
    }
  }
  hc () {
    this.$preload('info', this.state.info)
    Taro.navigateTo({
      url: '/pages/detail/detail'
    })
  }

  ci () {
    this.setState({
      info: {
        info: {
          id: !this.state.info.info.id
        }
      }
    })
  }

  render() {
    return (
      <View>
        <View onClick={this.ci.bind(this)}>ci</View>
        <View>{this.state.info.info.id}</View>
        <View onClick={this.hc.bind(this)}>goto</View>
      </View>
    )
  }
}
```

页面 B：

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Detail extends Component {
  render () {
    const infosData = this.$router.preload.info
    const { info } = infosData

    let current = null
    if(!info.id){
      console.log('保存11',!info.id)
      current = <View className='saveBtn'>保存1</View>
    }else{
      console.log('保存22',!info.id)
      current = <View className='saveBtn'>保存2</View>
    }
    return (
      <View className='addressInfo'>
        <View className='footer'>{current}</View>
      </View>
    )
  }
}
```
