### ISSUE TITLE
百度小程序 事件的监听函数不能命名为getData

### ISSUE THREAD

**Issue by lyevdsky** [NervJS/taro#2555]
**问题描述**
百度小程序 事件的监听函数不能命名为getData

**复现步骤**
```js
getData () {
  }
  render () {
    return (
      <View className='index'>
        <View onClick={this.getData}><Text>Hello, World</Text></View>
      </View>
    )
  }
```
![qwe](https://user-images.githubusercontent.com/12131431/54805823-16fc4800-4cb3-11e9-9b3a-958c8b8d12cd.png)

**期望行为**

**报错信息**

**系统信息**

**Comment by Chen-jj** [comment]
@lyevdsky 原生写法也有问题，属于百度小程序的问题，已反馈给百度
