### ISSUE TITLE
APP分享到小程序端拿不到参数

### ISSUE THREAD

**Issue by azoth1991** [NervJS/taro#2557]
APP分享到小程序，小程序端拿不到带过来的参数

taro版本 1.0.0-beta.9
小程序运行环境 安卓/ios
安卓大部分机型出现，iOS必先

``
componentDidMount() {
  const { shareid = ''} = this.$router.params;
}
``
无法拿到带过来的shareid

**Comment by jinjinjin0731** [comment]
1.0.0-beta.9 太老了。、更新到最新版本试一下
