### ISSUE TITLE
升级到 0.0.64，所有的组件传 props 都失效了。

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#256]
**问题描述**
更新了 0.0.64 后，发现在 weapp 中，所有的组件传 props 都失效了。无论传变量还是常量，子组件的 componentWillReceiveProps 就是不触发。把依赖全部回退到 0.0.63 又可以正常编译了。

**复现步骤**
因为项目已经写了有一阵子了，不大清楚具体是哪里的代码导致了问题。
在原项目里，注释掉其他干扰代码，仅在根组件里尝试传一个 prop 给某个子组件，依旧无效。
暂时没有尝试新建项目复现。

可能是这次更新后的 dynamicComponents 导致的？

**系统信息**
 - 操作系统: Mac OS
 - Taro 版本 0.0.64
 - Node.js 版本 10.5.0

**Comment by zacksleo** [comment]
刚在群里问了：
>嗯嗯，先回退，正在解决

**Comment by Songkeys** [comment]
@zacksleo 
好的！非常感谢。我看没有人提 issue，以为是个例，差点折腾半天。

**Comment by yuche** [comment]
试一下 0.0.65
