### ISSUE TITLE
componentWillMount调用Redux Action，Reducers更新state，componentWillReceiveProps不执行

### ISSUE THREAD

**Issue by oulp** [NervJS/taro#2560]
问题描述
componentWillMount调用Redux Action，Reducers更新state，componentWillReceiveProps不执行，DEBUG跟踪Reducers有执行。
若换成componentDidMount，componentWillReceiveProps执行正常

复现步骤 
1.  page
import { loadProjects } from '../../store/actions/project';
@connect(
  ({ project }) => ({
    ...project
  }),
  dispatch => ({
    loadProjects(page, filter) {
      dispatch(loadProjects(page, filter));
    }
  })
)
export default class Project extends Component {
componentDidMount() {
    const { loadProjects } = this.props;
    loadProjects();
  }
componentWillReceiveProps(nextProps) {
    const { loading } = nextProps;
    console.log(loading)
}
}

2.  Reduces
export default function counter(state = INITIAL_STATE, action) {
  switch (action.type) {
    case LOADING:
      return {
        ...state,
        loading: true
      };
}

期望行为 
componentWillReceiveProps执行

报错信息
componentWillReceiveProps不执行

系统信息
 Taro v1.2.17
 微信小程序

**Comment by Chen-jj** [comment]
@oulp 正常啊，componentWillReceiveProps 初始化阶段并不会执行，componentDidMount 后的更新阶段才执行。你在 componentWillMount dispatch 一个同步 action 肯定不调用 componentWillReceiveProps。

**Comment by oulp** [comment]
> @oulp 正常啊，componentWillReceiveProps 初始化阶段并不会执行，componentDidMount 后的更新阶段才执行。你在 componentWillMount dispatch 一个同步 action 肯定不调用 componentWillReceiveProps。

谢谢你的回复，上面的代码没编辑好，数据是request 异步请求。
Actions:
export const loadData = (page = 1, filter) => {
  return dispatch => {
    const data = { ... }
    dispatch({ type: LOADING });
    request(data).then(res => {
      dispatch({ type: LOAD_DEVICES, payload: { ...res, page } });
    });
  };

Reduces：
export default function counter(state = INITIAL_STATE, action) {
switch (action.type) {
case LOADING:
      return {
        ...state,
        error: null,
        loading: true
      };
case LOAD_DEVICES:
      const {
        errors, data
      } = action.payload;
      return {
        ...state,
        loading: false,
        errors, data
      };
default:
      return state;
  }
}

**Comment by gazxm** [comment]
@oulp  你好，请问一下你后面解决了这个问题，我也碰到了这个问题，不知道怎么解决

**Comment by oulp** [comment]
> @oulp 你好，请问一下你后面解决了这个问题，我也碰到了这个问题，不知道怎么解决

还没回复

**Comment by oulp** [comment]
@Chen-jj 帮忙确认下是不是代码问题，谢谢

**Comment by gazxm** [comment]
@oulp 我是在微信小程序里面碰到的这个问题  h5上倒是好的

**Comment by Chen-jj** [comment]
@oulp 复现不了，CLI 和依赖升级到最新版本后再试试。

page:

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { loadProjects } from '../../actions/index'

@connect(store => ({
  error: store.error,
  loading: store.loading,
  data: store.data
}), dispatch => ({
  loadData() {
    dispatch(loadProjects());
  }
}))
export default class Redux extends Component {
  componentWillMount () {
    this.props.loadData()
  }

  componentWillReceiveProps (nextProps) {
    console.log('componentWillReceiveProps: ', nextProps)
  }

  render () {
    return (
      <View>
        <View>error: {this.props.error}</View>
        <View>loading: {this.props.loading}</View>
        <View>data: {JSON.stringify(this.props.data)}</View>
      </View>
    )
  }
}
```

action:

```js
export const loadProjects = () => {
  return dispatch => {
    dispatch({ type: 'LOADING' })
    setTimeout(() => {
      dispatch({
        type: 'LOAD_PROJECTS',
        payload: {
          data: {
            x: 1,
            y: 2
          }
        }
      })
    }, 2000)
  }
}
```

reducers:

```js
const INIT = {
  error: null,
  loading: false,
  data: {}
}

export default function rootReducer (state = INIT, action) {
  switch (action.type) {
    case 'LOADING':
      return {
        ...state,
        error: null,
        loading: true
      }
    case 'LOAD_PROJECTS':
      const { errors, data } = action.payload
      return {
        ...state,
        loading: false,
        errors,
        data
      }
    default:
      return state
  }
}
```

结果：

![image](https://user-images.githubusercontent.com/11807297/55399086-bacfd880-557c-11e9-98b9-cd92c0db2cc1.png)

**Comment by oulp** [comment]
@Chen-jj action延迟改成100或者50时就会复现。

export const loadProjects = () => {
  return dispatch => {
    dispatch({ type: 'LOADING' })
    setTimeout(() => {
      dispatch({
        type: 'LOAD_PROJECTS',
        payload: {
          data: {
            x: 1,
            y: 2
          }
        }
      })
    },100)
  }
}

**Comment by Chen-jj** [comment]
@oulp 

你在 page 加上：

```js
componentDidMount () {
  console.log('mounted')
}
```

看看是先 mounted 还是先触发异步回调 dispatch LOAD_PROJECTS。

如果异步回调先触发，这时还没 mounted，这样不触发 componentWillReceiveProps 是正确的。

还是那句话：**componentWillReceiveProps 初始化阶段并不会执行，componentDidMount 后的更新阶段才执行**。触发 componentDidMount 的时机是小程序页面的 onReady 生命周期。
