### ISSUE TITLE
用了mobx后, componentDidShow()生命周期 不会执行

### ISSUE THREAD

**Issue by magicbing** [NervJS/taro#2561]
**问题描述**

H5页面中 用了mobx后, componentDidShow()生命周期 不会执行
没有使用mobx的页面, 是正常的

**期望行为**
有没有可以替代componentDidShow的方法可以用

**系统信息**
👽 Taro v1.2.17

  Taro CLI 1.2.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\app\nodejs10\node.EXE
      Yarn: 1.13.0 - D:\app\yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\app\nodejs10\npm.CMD

**Comment by nanjingboy** [comment]
https://github.com/NervJS/taro/pull/2583

**Comment by magicbing** [comment]
更新到1.2.22, 项目不能启动了

node控制台报warning:
`./node_modules/@tarojs/mobx-h5/dist/index.esm.js 405:2-11
" '@tarojs/taro-h5' does not contain an export named 'Component'.`

浏览器console报错:
`Uncaught ReferenceError: exports is not defined`

`Object.defineProperty(exports, "__esModule", {
  value: true
});`

**Comment by magicbing** [comment]
把 'transform-runtime', 从config里删掉就可以了,
但是项目里有用到async await

这个有方法解决吗
@nanjingboy

**Comment by Littly** [comment]
已提交修复~ 下个版本解决

**Comment by magicbing** [comment]
> Warning的问题已提交修复~ 下个版本解决

升级了1.2.23 h5还是报错

plugins: [
        'transform-runtime',
      ],
应该还是这边的问题, 注释transform-runtime就好了


node终端报:
⚠️  Compiled with warnings.

./node_modules/@tarojs/mobx-h5/dist/index.esm.js 405:2-6
"export 'default' (imported as 'Taro') was not found in '@tarojs/taro-h5'

浏览器报:
index.js:10 Uncaught ReferenceError: exports is not defined
    at eval (index.js:10)
    at Module../node_modules/@tarojs/taro-h5/src/index.js (app.js:2307)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (app.js?d0a8:1)
    at Object../.temp/app.js (app.js:939)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.0 (app.js:5066)
    at __webpack_require__ (app.js:767)

**Comment by magicbing** [comment]
['transform-runtime',
          {
            'polyfill': false,
          }
        ]

查了一些资料, 加了polyfill参数好了.
