### ISSUE TITLE
Taro-cli 1.2.21 执行yarn dev:rn 报Could not find "stylelint-config-taro-rn".

### ISSUE THREAD

**Issue by TZ-TimZhang** [NervJS/taro#2562]
**问题描述**
Taro-cli 1.2.21 执行yarn dev:rn 报Could not find "stylelint-config-taro-rn".
全新init的项目 没有改过任何代码

**复现步骤**
[复现问题的步骤]
1. yarn dev:rn

**期望行为**
tarn rn编译不报错

**报错信息**
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but stylelint uses 7.0.14. Perhaps this is the source of the error below.
{ Error: Could not find "stylelint-config-taro-rn". Do you need a `configBasedir`?
    at module.exports (/Users/timzhang/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at getModulePath (/Users/timzhang/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/node_modules/stylelint/lib/utils/getModulePath.js:26:11)
    at loadExtendedConfig (/Users/timzhang/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/node_modules/stylelint/lib/augmentConfig.js:194:22)
    at resultPromise.then.resultConfig (/Users/timzhang/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/node_modules/stylelint/lib/augmentConfig.js:168:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 78 }
(node:63281) UnhandledPromiseRejectionWarning: Error: Error: Could not find "stylelint-config-taro-rn". Do you need a `configBasedir`?
    at Promise.all.then.then.then.catch (/Users/timzhang/.nvm/versions/node/v8.11.3/lib/node_modules/@tarojs/cli/src/rn.js:79:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:63281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**系统信息**

  Taro CLI 1.2.21 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    npmPackages:
      @tarojs/components: 1.2.21 => 1.2.21
      @tarojs/plugin-babel: 1.2.21 => 1.2.21
      @tarojs/plugin-csso: 1.2.21 => 1.2.21
      @tarojs/plugin-less: 1.2.21 => 1.2.21
      @tarojs/plugin-uglifyjs: 1.2.21 => 1.2.21
      @tarojs/router: 1.2.21 => 1.2.21
      @tarojs/taro: 1.2.21 => 1.2.21
      @tarojs/taro-alipay: 1.2.21 => 1.2.21
      @tarojs/taro-h5: 1.2.21 => 1.2.21
      @tarojs/taro-swan: 1.2.21 => 1.2.21
      @tarojs/taro-tt: 1.2.21 => 1.2.21
      @tarojs/taro-weapp: 1.2.21 => 1.2.21
      @tarojs/webpack-runner: 1.2.21 => 1.2.21
      eslint-config-taro: 1.2.21 => 1.2.21
      eslint-plugin-taro: 1.2.21 => 1.2.21
      nervjs: ^1.3.9 => 1.3.13
    npmGlobalPackages:
      typescript: 3.2.2

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by TZ-TimZhang** [comment]
Anybody here？

**Comment by Pines-Cheng** [comment]
自己手动装一下  stylelint-config-taro-rn 这个包。

**Comment by TZ-TimZhang** [comment]
@Pines-Cheng 谢谢支持 最终安装了3个库 stylelint, stylelint-config-taro-rn, stylelint-taro-rn 才顺利运行起来

**Comment by zWingz** [comment]
手动安装时可以解决
官方不打算解决该bug吗

**Comment by WingGao** [comment]
+1

**Comment by Pines-Cheng** [comment]
新版已 fix。

**Comment by plc6555493** [comment]
+1

**Comment by lyxia** [comment]
+1
