### ISSUE TITLE
mobx store 中的数据值为数组时，使用 push() 方法改变数组的值不会使得视图更新

### ISSUE THREAD

**Issue by cheese-git** [NervJS/taro#2563]
**问题描述**
mobx store 中的数据值为数组时，使用 push() 方法改变数组的值不会使得视图更新

**复现步骤**

1. 定义 store

`cart.store.ts`:
```ts
import { observable, action } from "mobx"

class CartStore {
  @observable dishes: any[] = []
  @action.bound addDish(dish) {
    // 关键代码
    this.dishes.push(dish)
  }
}

const cartStore = new CartStore()

export default cartStore
```
2. 绑定 store

`App.tsx`:

```tsx
import cartStore from "./cart/cart.store"

const store = {
  cartStore
}

/// ...

render() {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
```

`Cart.tsx`:

```tsx
// ...

@inject("cartStore")
@observer
export default class Cart extends Component {
  render() {
    const {
      cartStore: { dishes }
    } = this.props

    console.log(dishes)
    return (
      <View>
        <CartIcon />
        <Text>购物车是空的</Text>
      </View>
    )
  }
}
```
3. 修改 store 的值

`DishItem.tsx`:

```tsx
// ...

  handleChange() {
    const {
      cartStore: { addDish },
      dish
    } = this.props

    addDish(dish)
  }

//...
```
4. 在视图中点击按钮，触发 handleChange()，没有打印新值

5. 将 push() 方法改为直接赋值新数组，重新触发 handleChange()，成功打印新值

`cart.store.ts`:

```ts
import { observable, action } from "mobx"

class CartStore {
  @observable dishes: any[] = []
  @action.bound addDish(dish) {
    // 关键代码
    // this.dishes.push(dish)
    this.dishes = [...this.dishes, dish]
  }
}

const cartStore = new CartStore()

export default cartStore

```

**期望行为**

能够使用数组的 push() 方法操作 store 的数据。

**系统信息**

 System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.21 => 1.2.21 
      @tarojs/mobx: ^1.2.21 => 1.2.21 
      @tarojs/plugin-babel: 1.2.21 => 1.2.21 
      @tarojs/plugin-csso: 1.2.21 => 1.2.21 
      @tarojs/plugin-sass: ^1.2.21 => 1.2.21 
      @tarojs/plugin-uglifyjs: 1.2.21 => 1.2.21 
      @tarojs/router: 1.2.21 => 1.2.21 
      @tarojs/taro: 1.2.21 => 1.2.21 
      @tarojs/taro-alipay: 1.2.21 => 1.2.21 
      @tarojs/taro-h5: 1.2.21 => 1.2.21 
      @tarojs/taro-swan: 1.2.21 => 1.2.21 
      @tarojs/taro-tt: 1.2.21 => 1.2.21 
      @tarojs/taro-weapp: 1.2.21 => 1.2.21 
      @tarojs/webpack-runner: 1.2.21 => 1.2.21 
      eslint-config-taro: 1.2.21 => 1.2.21 
      eslint-plugin-taro: 1.2.21 => 1.2.21 
      nervjs: ^1.3.9 => 1.3.13 

问题平台：微信小程序

**Comment by Garfield550** [comment]
https://stackoverflow.com/questions/45840393/mobx-not-updating-react-view-when-pushing-to-an-array

https://github.com/mobxjs/mobx-react/issues/444

**Comment by nanjingboy** [comment]
@cheese-git taro 默认的 mobx 版本是 4.8 (为了兼容低端机型)，关于数组的问题在 mobx 文档中已经说的很清楚了，建议认真阅读下。当然，如果你不需要兼容低端机型，完全可以使用最新的 mobx 版本

**Comment by cheese-git** [comment]
谢谢🙏
