### ISSUE TITLE
小程序报错：VM3143:5 Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by hrh94** [NervJS/taro#2567]
Problem in the development of small programs, I found on the Internet may be loops have problems, but now I have commented out all the loops, and there is only one page left, but still reported the error.

**Comment by awangsw** [comment]
估计是小程序调用库的问题
![image](https://user-images.githubusercontent.com/22760725/54970349-c0e21a00-4fbc-11e9-8686-c1270e7e8402.png)

**Comment by Chen-jj** [comment]
@hrh94 提供一下可复现的代码。
