### ISSUE TITLE
通过alias配置指向npm包时，@符号未变成下划线

### ISSUE THREAD

**Issue by Mr-DarrenLee** [NervJS/taro#2577]
**问题描述**
alias配置的指向npm文件，不会处理成非@文件名（兼容支付宝）

**复现步骤**
在config.js配置alias如下：
```js
alias: {
    "sdk": resolve(`node_modules/@my/sdk/${type}`),
}
```
编译后会导致dist/npm目录中的产生一个@my文件夹，在支付宝中就不能提交了（支付宝小程序不支持文件夹名带 @ ）

**期望行为**
@my文件夹名称变更成 “_my”

**报错信息**
无

**系统信息**
👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.0.0 - ~/.nvm/versions/node/v8.0.0/bin/node
      Yarn: 1.12.1 - ~/.nvm/versions/node/v8.0.0/bin/yarn
      npm: 5.0.0 - ~/.nvm/versions/node/v8.0.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.0-beta.12 => 1.2.4
      @tarojs/components: ^1.2.0-beta.12 => 1.2.4
      @tarojs/plugin-babel: ^1.2.0-beta.12 => 1.2.4
      @tarojs/plugin-csso: ^1.2.0-beta.12 => 1.2.4
      @tarojs/plugin-less: ^1.2.0-beta.12 => 1.2.4
      @tarojs/plugin-uglifyjs: ^1.2.0-beta.12 => 1.2.4
      @tarojs/redux: ^1.2.0-beta.12 => 1.2.4
      @tarojs/redux-h5: ^1.2.0-beta.12 => 1.2.4
      @tarojs/router: ^1.2.0-beta.12 => 1.2.4
      @tarojs/taro: ^1.2.0-beta.12 => 1.2.4
      @tarojs/taro-alipay: ^1.2.0-beta.12 => 1.2.4
      @tarojs/taro-h5: ^1.2.0-beta.12 => 1.2.4
      @tarojs/taro-swan: ^1.2.0-beta.12 => 1.2.4
      @tarojs/taro-weapp: ^1.2.0-beta.12 => 1.2.4
      @tarojs/webpack-runner: ^1.2.0-beta.12 => 1.2.4
      eslint-config-taro: ^1.2.0-beta.12 => 1.2.4
      eslint-plugin-taro: ^1.2.0-beta.12 => 1.2.4

**补充信息**
无

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/d09cc2d563846bf5d8039b74ce88694e0ec7cec5
