### ISSUE TITLE
H5 chooseImage的sourceType配置单个选项 不起作用

### ISSUE THREAD

**Issue by hblz** [NervJS/taro#2578]
**问题描述**
H5 下chooseImage的sourceType配置单个选项 不起作用，不管怎么配置，都是显示album和camera
**复现步骤**
[复现问题的步骤]
```js
Taro.chooseImage({
      count: 1,
      sizeType: ['compressed'],
      sourceType: ['album'],
      success: () => {

      }
    })

```

**期望行为**
可以根据sourceType配置 显示相应的功能，如果是配置单个，就直接吊起单个的功能

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.2.21 environment info:
    System:
      OS: macOS High Sierra 10.13.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.21 => 1.2.21 
      @tarojs/components: ^1.2.21 => 1.2.21 
      @tarojs/plugin-babel: ^1.2.21 => 1.2.21 
      @tarojs/plugin-csso: ^1.2.21 => 1.2.21 
      @tarojs/plugin-sass: ^1.2.21 => 1.2.21 
      @tarojs/plugin-uglifyjs: ^1.2.21 => 1.2.21 
      @tarojs/redux: ^1.2.21 => 1.2.21 
      @tarojs/redux-h5: ^1.2.21 => 1.2.21 
      @tarojs/router: ^1.2.21 => 1.2.21 
      @tarojs/taro: ^1.2.21 => 1.2.21 
      @tarojs/taro-alipay: ^1.2.21 => 1.2.21 
      @tarojs/taro-h5: ^1.2.21 => 1.2.21 
      @tarojs/taro-swan: ^1.2.21 => 1.2.21 
      @tarojs/taro-tt: ^1.2.21 => 1.2.21 
      @tarojs/taro-weapp: ^1.2.21 => 1.2.21 
      @tarojs/webpack-runner: ^1.2.21 => 1.2.21 
      eslint-config-taro: ^1.2.21 => 1.2.21 
      eslint-plugin-taro: ^1.2.21 => 1.2.21 
      nervjs: ^1.3.13 => 1.3.13

**Comment by hblz** [comment]
这个 啥时候修复啊

**Comment by hblz** [comment]
急需要

**Comment by hblz** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊 没人回复吗 搞死了

**Comment by hblz** [comment]
@jinjinjin0731

**Comment by jinjinjin0731** [comment]
下周发版。近两天修复

**Comment by xoptimal** [comment]
@jinjinjin0731   v1.3.4 H5端设置 sourceType 仍然无效 ~
```
chooseImage({sourceType: ['camera'] ...)
```

**Comment by xoptimal** [comment]
更新版本后 仍然无效 @Garfield550

**Comment by shenghanqin** [comment]
@hblz 试试看最新版本
