### ISSUE TITLE
[优化] _createClass、_get、_inherits 等工具函数通过 require 引入

### ISSUE THREAD

**Issue by js-newbee** [NervJS/taro#2580]
**问题描述**
编译后的 js 文件中基本都会包含 _createClass、_get、_interopRequireDefault、_classCallCheck、_possibleConstructorReturn、_inherits 等工具函数，为何不将这些函数放在同一个 util.js 中，然后通过 require 引入呢？

毕竟对于有多个页面、多个组件的项目来说，去掉这些重复代码能显著减少打包体积（有看过几次吐槽，说 Taro 编译后动不动就 2M 以上了，确实这点开发过程中还是比较麻烦的，虽然开发时也可以开启压缩，但就不好 debug 了）

**复现步骤**
无

**期望行为**
减少打包体积

**报错信息**
无

**补充信息**
暂未

**Comment by luckyadam** [comment]
这个可以通过配置 `babel-plugin-transform-runtime` 来优化 babel 编译生成的工具函数

**Comment by shengbowen** [comment]
貌似没有用啊

**Comment by shengbowen** [comment]
实测，插件要做下配置，helper必须为true，否则helper函数提取不成功。  useBuiltIns 设为true，否则会引入很过core-js中的pollyfill，导致体积更大。

同时 版本也有要求：
 "babel-plugin-transform-runtime": "7.0.0-beta.0",
"babel-runtime": "7.0.0-beta.0",

```js
'transform-decorators-legacy',
  'transform-class-properties',
  'transform-object-rest-spread',
  [
    'transform-runtime',
    {
      helpers: true,
      polyfill: false,
      regenerator: true,
      useBuiltIns: true,
      moduleName: 'babel-runtime',
    },
  ],


 compile: {
      exclude: [/core-js/, /babel-runtime/],   // 防止node_modules中core-js、babel-runtime被plugin处理，导致报错
    },

```
