### ISSUE TITLE
taro-cli 全局安装,换个电脑就不能用了

### ISSUE THREAD

**Issue by boogoogle** [NervJS/taro#2581]
**问题描述**
1. taro cli 没有安装到本地的node_module/bin目录下,
2. 在npm scripts里面使用的taro是全局安装的taro;
4. taro1.2.13cli创建的项目, 如果另一个同学电脑上安装的taro1.2.27版本, 编译时报错

**复现步骤**
[复现问题的步骤]
1. cd node_modules/.bin,
2. 没有看到taro的命令行工具

**期望行为**
把命令行工具放到node_modules/.bin下

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.13 & v1.2.27]
 - 报错平台 [h5]

**补充信息**
是否可以吧命令行工具放到node_modules/.bin下?

**Comment by js-newbee** [comment]
@boogoogle @tarojs/cli 版本最好跟项目中的 @taro/* 版本保持一致，否则不能保证编译正常的
你把 @tarojs/cli 放到项目中的 package.json 里就好了，这样执行 taro 的时候会调用项目内的版本

`npm i @tarojs/cli@1.2.13` or `yarn add @tarojs/cli@1.2.13`

**Comment by shaodahong** [comment]
#2226 建议这种处理
