### ISSUE TITLE
新创建的项目一直报错误，Unsupported VNode

### ISSUE THREAD

**Issue by lzmhlzsd** [NervJS/taro#2582]
![image](https://user-images.githubusercontent.com/7322084/54967056-3b0ca180-4fb1-11e9-8357-214e432561e6.png)
![image](https://user-images.githubusercontent.com/7322084/54967082-4fe93500-4fb1-11e9-8e3b-6bd30a5c8144.png)

**Comment by lzmhlzsd** [comment]
在其他电脑上能正常运行，发现有个js/app.js文件的打包不一样

能正常运行的
![image](https://user-images.githubusercontent.com/7322084/55048481-4b8d4c80-5083-11e9-9a10-71e9f1cd477d.png)

报错的
![image](https://user-images.githubusercontent.com/7322084/55048513-68298480-5083-11e9-9fea-87ce92edbbc4.png)

**Comment by Littly** [comment]
项目是全新创建的？

**Comment by lzmhlzsd** [comment]
是全新创建的，打包h5就出这个问题。用了2台电脑，一台正常，一台运行报错。发现2个项目打包出来的app.js 不一样

**Comment by leidenglai** [comment]
同样的问题，但我的是只在h5中报错
原因是在 使用高阶函数反向继承时 render中返回的
![image](https://user-images.githubusercontent.com/11383747/56075174-c202ac00-5df0-11e9-9f1f-2ab0ead9fb0c.png)

改成如下就好了：
![image](https://user-images.githubusercontent.com/11383747/56075183-f2e2e100-5df0-11e9-8b89-1ef8a91a435b.png)

看看能不能对bug定位有帮助

**Comment by Littly** [comment]
> 同样的问题，但我的是只在h5中报错
> 原因是在 使用高阶函数反向继承时 render中返回的
> ![image](https://user-images.githubusercontent.com/11383747/56075174-c202ac00-5df0-11e9-9f1f-2ab0ead9fb0c.png)
> 
> 改成如下就好了：
> ![image](https://user-images.githubusercontent.com/11383747/56075183-f2e2e100-5df0-11e9-8b89-1ef8a91a435b.png)
> 
> 看看能不能对bug定位有帮助

你截图的这个单纯就是代码问题了 render里面return的东西不对

**Comment by Littly** [comment]
> 是全新创建的，打包h5就出这个问题。用了2台电脑，一台正常，一台运行报错。发现2个项目打包出来的app.js 不一样

复现不了 需要可以稳定复现的代码跑跑看 这样看不出是什么问题
