### ISSUE TITLE
h5 build后页面不能正常访问(mode:browser)

### ISSUE THREAD

**Issue by Rain20188** [NervJS/taro#2587]
问题描述
h5模式下router的mode设置为browser,编译后的文件运行访问提示路由地址不正确

复现步骤
[复现问题的步骤]
npm run build:h5
然后通过liveserver访问dist下的index.html文件 

期望行为
hash与browser两者行为能一致

报错信息
Can not find proper registered route for '/dist/index.html'
[这里请贴上你的完整报错截图或文字]

系统信息
操作系统: mac os10.14.3
Taro 版本 [1.2.21]
Node.js 版本 [v11.12.0]
报错平台 [h5]

**Comment by Littly** [comment]
看下你的 `h5.router`和`publicPath`？

**Comment by Rain20188** [comment]
> 看下你的 `h5.router`和`h5.publicPath`？

 h5: {
    publicPath: './',
    output: {
      filename: 'static/js/[name].[hash:8].js',
      chunkFilename: 'static/js/[name].[chunkhash:8].js'
    },
    miniCssExtractPluginOption: {
      filename: 'static/css/[name]/[hash].css',
      chunkFilename: 'static/css/[name]/[hash].css'
    },
    router: {
      mode:'browser',
      customRoutes: {
        '/pages/index/index': '/index',
        '/pages/scan/index': '/scan',
        '/pages/home/index': '/home',
        '/pages/mine/index': '/mine',
      }
    },
    enableDll: true,
  }

**Comment by Littly** [comment]
看着没啥问题 需要一个可以复现的demo

**Comment by xiongmao911** [comment]
h5 build后页面不能正常访问报错Uncaught Invariant Violation: Can not find proper registered route for '/static/h5/index.html'  lib.dll.js:1 
也是访问index.html文件，dev没任何问题，但放到线上就不能访问了
![1560496630670](https://user-images.githubusercontent.com/32010968/59490592-adf22e00-8eb7-11e9-858a-b894c24e96eb.jpg)
代码如下
config/index.js
const isH5 = process.env.TARO_ENV === 'h5'
const HOST = '"https://union.007vin.com/"'
const config = {
  projectName: 'cloud-h5-007',
  date: '2019-6-5',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'dist',
  plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread'
      ]
    }
  },
  defineConstants: {
    HOST: isH5 ? '"/api"' : HOST
  },
  copy: {
    patterns: [
    ],
    options: {
    }
  },
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: [
              'last 3 versions',
              'Android >= 4.1',
              'ios >= 8'
            ]
          }
        },
        pxtransform: {
          enable: true,
          config: {

          }
        },
        url: {
          enable: true,
          config: {
            limit: 10240 // 设定转换尺寸上限
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  },
  h5: {
    // publicPath: './',
    staticDirectory: 'static',
    router: {
      mode: 'browser', // 或者是 'browser'
      basename: 'static/h5/index.html',
      customRoutes: {
        '/pages/packageSpecial/index': '/package',
        '/pages/coupons/index': '/coupons'
      }
    },
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: [
              'last 3 versions',
              'Android >= 4.1',
              'ios >= 8'
            ]
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      } 
    },
    esnextModules: ['taro-ui'],
    devServer: {
      allowedHosts: ['union.007vin.com'],
      proxy: {
        '/api': {
          target: JSON.parse(HOST),
          pathRewrite: {
            '^/api': '/'
          },
          changeOrigin: true
        }
      }
    }
  }
}

module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}

config/prod.js
module.exports = {
  env: {
    NODE_ENV: '"production"'
  },
  defineConstants: {
  },
  weapp: {},
  h5: {
    esnextModules: ['taro-ui'],
    publicPath: './',
    router: {
      mode: 'browser', // 或者是 'browser'
      basename: 'static/h5/index.html',
      customRoutes: {
        '/pages/packageSpecial/index': '/package',
        '/pages/coupons/index': '/coupons'
      }
    }
  }
}

**Comment by giantss** [comment]
#4171 我也遇到这样的问题

**Comment by lijia321** [comment]
楼主解决了吗
