### ISSUE TITLE
Taro打包成H5后在5s手机上打开空白

### ISSUE THREAD

**Issue by iOS-XuQiang** [NervJS/taro#259]
Taro项目打包成H5后在5s手机上打开是空白界面，是有什么5s不支持吗？

**Comment by iOS-XuQiang** [comment]
Taro项目打包成H5后在5s手机上打开是空白界面，是有什么5s不支持吗？

**Comment by yuche** [comment]
https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by yuche** [comment]
按照模板提 issue，你不贴代码，不贴报错，没有复现步骤，那就没有办法给你 debug。

**Comment by jordzhang** [comment]
iphone和pc微信确实是空白页，android是可以的
