### ISSUE TITLE
swan.setPageInfo未定义

### ISSUE THREAD

**Issue by holobo** [NervJS/taro#2591]
**问题描述**
按百度要求，百度小程序开启web化后需要调用swan.setPageInfo接口设置页面信息，该接口在百度开发工具中有定义，但是在真机中未定义

**复现步骤**
1. 百度小程序在项目信息中点击接入百度搜索
2. 在代码中调用swan.setPageInfo接口设置页面信息
3. 在百度小程序开发工具中一切正常，在真机中提示swan.setPageInfo未定义
4. 将小程序提交到百度审核时会因未设置页面信息而被拒绝(因为swan.setPageInfo未调用成功)
代码如下：
```js
const pageInfo = data.page_info
      if(TARO_ENV == ENV_TYPE.SWAN && typeof swan != "undefined") {
        swan.setPageInfo && swan.setPageInfo({
          title: pageInfo.title,
          keywords: pageInfo.keywords,
          description: pageInfo.description,
          releaseDate: pageInfo.releaseDate,
          // 单张图时值可以是字符串
          image: pageInfo.image,
          success: function () {
            console.log('页面基础信息设置完成');
          },
          fail: function () {
            console.log('页面基础信息设置失败');
          }
        })
      }
```

**期望行为**
请确认该问题是Taro框架导致的还是百度小程序本身原因导致的

**报错信息**

**系统信息**
Taro v1.2.20
  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.20 => 1.2.20 
      @tarojs/plugin-babel: 1.2.20 => 1.2.20 
      @tarojs/plugin-csso: 1.2.20 => 1.2.20 
      @tarojs/plugin-sass: ^1.2.20 => 1.2.20 
      @tarojs/plugin-uglifyjs: 1.2.20 => 1.2.20 
      @tarojs/router: 1.2.20 => 1.2.20 
      @tarojs/taro: 1.2.20 => 1.2.20 
      @tarojs/taro-alipay: 1.2.20 => 1.2.20 
      @tarojs/taro-h5: 1.2.20 => 1.2.20 
      @tarojs/taro-swan: 1.2.20 => 1.2.20 
      @tarojs/taro-tt: 1.2.20 => 1.2.20 
      @tarojs/taro-weapp: 1.2.20 => 1.2.20 
      @tarojs/webpack-runner: 1.2.20 => 1.2.20 
      eslint-config-taro: 1.2.20 => 1.2.20 
      eslint-plugin-taro: 1.2.20 => 1.2.20 
      nervjs: ^1.3.9 => 1.3.12

**补充信息**

**Comment by jinjinjin0731** [comment]
[页面基础信息设置无效，阻塞上线](https://smartprogram.baidu.com/forum/topic/show/66358)

这个应该是百度小程序的问题，这个问题应该和你的问题类似。你可以去官方社区提个问题，然后等待回复解决办法
