### ISSUE TITLE
小程序的官方组件live-room-play, 事件无法绑定

### ISSUE THREAD

**Issue by fannairu** [NervJS/taro#2593]
需要监听 live-room-play 组件的bindPlayEvent， 
<live-room-play liveAppID={LIVE_APP_ID}
                                playUrl={convertHLSToFLV(url)}
                                orientation={livePlayerIsFullScreen ? 'horizontal' : 'vertical'}
                                objectFit='contain'
                                mode='live' 
                                onPlayEvent={this.onPlayEvent}
                                debug={false}>

死活触发不了
官方插件名叫 “腾讯云直播助手”
taro 版本 1.2.21

**Comment by luckyadam** [comment]
贴一下引用这个插件的页面或者组件的完整代码
