### ISSUE TITLE
动态注入Reducer，出现Cyclic dedependency

### ISSUE THREAD

**Issue by kelvinleungv** [NervJS/taro#2594]
**问题描述**
通过Taro init 新建一个配合Redux构建的项目，
目的是通过修改store配置，使得每个容器组件能够动态注入Reducer。
通过配置injectReducer，进行配置，在各自两个不同的容器组件分别注入对应的Reducer，此时只对其中一个容器组件注入Reducer时，代码能正常运行，当用相同的方式注入另外一个容器组件时，命令行报错（Cyclic dedependency），此前并没有引入任何其他依赖。

**复现步骤**
```js
store 

import { createStore, applyMiddleware, compose } from 'redux'
import thunkMiddleware from 'redux-thunk'
import rootReducer from '../reducers'

const composeEnhancers =
  typeof window === 'object' &&
  window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?   
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
      // Specify extension’s options like name, actionsBlacklist, actionsCreators, serialize...
    }) : compose

const middlewares = [
  thunkMiddleware
]

if (process.env.NODE_ENV === 'development') {
  middlewares.push(require('redux-logger').createLogger())
}

const enhancer = composeEnhancers(
  applyMiddleware(...middlewares),
  // other store enhancers if any
)

export default function configStore () {
  const store = createStore(rootReducer(), enhancer)
  
  store.asyncReducers = {
    ...rootReducer()
  }
  return store
}

```
```js
rootReducer

import { combineReducers } from 'redux'
import counter from './counter'

export default function createReducer(injectedReducers) {
  return combineReducers({
    global: counter,
    ...injectedReducers
  });
}
```

```js
injectReeducerFactory

import { combineReducers } from 'redux'
import createReducer from '../reducers';


export const injectReducerFactory = (store, key, reducer) => {
    if (Object.hasOwnProperty.call(store.asyncReducers, key)) return;
    store.asyncReducers[key] = reducer;
    store.replaceReducer(createReducer(store.asyncReducers));
}
```
```js
testB

import * as Utils from '../../utils/injectReducer';
import { store } from '../../app.js';
import reducer from '../../reducers/testB';
Utils.injectReducerFactory(store, 'testB', reducer);

```
```js
testA

import * as Utils from '../../utils/injectReducer';
import * as Api from '../../common/ajax.js';
import { store } from '../../app.js';
import reducer from '../../reducers/testA';

Utils.injectReducerFactory(store, 'testA', reducer); // 同时使用报错
```

**期望行为**
每个容器组件能够动态注入 reducer

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/21992834/54992168-a0848080-4ff9-11e9-807f-53e8b5deb1e7.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.17]
 - Node.js 版本 [e.g. v10.14.1]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by kelvinleungv** [comment]
通过上述方法动态注入reducer，只动态注入一个容器组件的reducer，在H5端正常运行，但是会导致微信小程序端运行报错
![image](https://user-images.githubusercontent.com/21992834/55203650-20cc0100-5207-11e9-9285-db987900be6d.png)
----
![image](https://user-images.githubusercontent.com/21992834/55203724-62f54280-5207-11e9-9b72-c5cb1b4d5e58.png)

**Comment by Littly** [comment]
cyclic dependency跟reducer没有关系，是指你的代码出现循环依赖了。可以检查下模块的拆分是否合理。

**Comment by Littly** [comment]
> ## 通过上述方法动态注入reducer，只动态注入一个容器组件的reducer，在H5端正常运行，但是会导致微信小程序端运行报错
> ![image](https://user-images.githubusercontent.com/21992834/55203650-20cc0100-5207-11e9-9285-db987900be6d.png)
> ![image](https://user-images.githubusercontent.com/21992834/55203724-62f54280-5207-11e9-9b72-c5cb1b4d5e58.png)

@luckyadam

**Comment by shenghanqin** [comment]
最近还有这个问题吗？ @kelvinleungv

**Comment by tourze** [comment]
taro 3.0.15 测试还是不行
