### ISSUE TITLE
taro convert被抽出来的组件总是报defaultProps undefined警告，手动加上了defaultProps还是会报 

### ISSUE THREAD

**Issue by luodanyalian** [NervJS/taro#2597]
**问题描述**
taro convert被抽出来的组件总是报defaultProps undefined警告，手动加上了defaultProps还是会报 

源码请见https://github.com/NervJS/taro/issues/2527

**期望行为**
希望编译之后自动生成defaultProps没有这个defaultProps undefined警告

**报错信息**

![image](https://user-images.githubusercontent.com/22935907/55046893-f00c9000-507d-11e9-9c7f-8d313a650127.png)

**系统信息**
Taro CLI 1.2.20 environment info:
System:
OS: macOS 10.14
Shell: 5.3 - /bin/zsh
Binaries:
Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
Yarn: 1.9.4 - ~/.nvm/versions/node/v8.11.3/bin/yarn
npm: 6.8.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
npmGlobalPackages:
typescript: 3.3.3

**Comment by yuche** [comment]
你的 `modalStatus` 是在 props.data 下的，不是在 props 下
