### ISSUE TITLE
触发action时，数据被替换成了event对象

### ISSUE THREAD

**Issue by ZhiguangXiong** [NervJS/taro#2598]
**问题描述**

**触发 redux action时，传入的data被替换为了event对象**

**复现步骤**
![企业微信截图_1058b7f2-76ab-4a12-8cc3-712489eae87c](https://user-images.githubusercontent.com/25341976/55048913-e5a1c480-5084-11e9-8449-cd1273dca96e.png)
![企业微信截图_117d9f52-b955-4ace-90d9-878015ce4ad9](https://user-images.githubusercontent.com/25341976/55048912-e5a1c480-5084-11e9-8aad-863eba05c244.png)
![企业微信截图_98bd93a7-c3c1-4c3e-a495-a77dc8833e53](https://user-images.githubusercontent.com/25341976/55048911-e5092e00-5084-11e9-9e5f-a6b7aba126ad.png)
![企业微信截图_8619913a-60af-4546-bec2-2b591bbb3004](https://user-images.githubusercontent.com/25341976/55049023-6e206500-5085-11e9-8638-2c8707a286f0.png)

**报错信息**
![企业微信截图_3fc09d56-40db-4ae2-8544-de5c49ac982e](https://user-images.githubusercontent.com/25341976/55048996-46310180-5085-11e9-8547-408e691e1604.png)

**系统信息**

Taro CLI 1.2.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.6.0 - /usr/local/bin/node
      npm: 5.3.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/components: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/plugin-babel: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/plugin-csso: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/plugin-sass: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/plugin-uglifyjs: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/redux: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/redux-h5: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/router: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/taro: ^1.0.3 => 1.0.3 
      @tarojs/taro-h5: ^1.0.0-beta.24 => 1.0.0-beta.26 
      @tarojs/taro-weapp: ^1.0.3 => 1.0.3 
      @tarojs/webpack-runner: ^1.0.0-beta.24 => 1.0.0-beta.26 
      eslint-config-taro: ^1.0.0-beta.24 => 1.0.0-beta.26 
      eslint-plugin-taro: ^1.0.0-beta.24 => 1.0.0-beta.26

**Comment by Garfield550** [comment]
由于你的 Taro 版本大多都是 `1.0.0-beta.26`，我建议你先运行一下 `taro update self` 和 `taro update project` 更新一下 Taro 版本。

**Comment by ZhiguangXiong** [comment]
> 由于你的 Taro 版本大多都是 `1.0.0-beta.26`，我建议你先运行一下 `taro update self` 和 `taro update project` 更新一下 Taro 版本。

`taro update project`更新版本后，不再报错，多谢
