### ISSUE TITLE
关于页面state缓存问题

### ISSUE THREAD

**Issue by Hello-Tan** [NervJS/taro#260]
发现Taro会自动把页面的state缓存（列表页进详情页，回退后再进入详情页时，state的值还是上次的）。  

**代码如下所示。感觉这个设计弄成可配置化的更好一些，因为实际项目中很多时候是不希望有缓存的。**
  

![1d629dbb99887142e7c633c96ac66fd](https://user-images.githubusercontent.com/23740685/42253658-43038b90-7f75-11e8-9b04-89c57b4ba659.png)
![813b093cfdcc6b92e2dbaa9f7083f25](https://user-images.githubusercontent.com/23740685/42253659-44c1ecba-7f75-11e8-876b-58253cded0bc.png)

**Comment by BODhaha** [comment]
同问

**Comment by zacksleo** [comment]
目前确实有这个问题，我的解决方法是在 componentDidShow 里面重新设置一下 state

**Comment by Songkeys** [comment]
这个好像是原生就有的问题。都是在 unload 里重新设置 data 解决的。

**Comment by zacksleo** [comment]
https://github.com/NervJS/taro/commit/c420b21b91c1243afe9d4de8dbcb5c68149fa263  这个提交好像修复了该问题

**Comment by aushion** [comment]
componentWillUnmount () {
    this.setState({
      data: null,
      loading: true,
      content: null,
      replies: []
    })
   }

**Comment by luckyadam** [comment]
+1 c420b21 修复了这个问题

**Comment by yuche** [comment]
0.0.68 应该能解决，或者你可以尝试 beta 版本。
