### ISSUE TITLE
Taro.showToast和Taro.showLoading混用会导致死循环

### ISSUE THREAD

**Issue by damon-yang** [NervJS/taro#2603]
参考代码
```
A页面：
Taro.showToast({
    title:'登陆成功',
    icon:"success",
    mask:true,
    duration:500,
    complete(){
    Taro.navigateTo({
        url:B页面
    })
    }
})

B页面：
Taro.showLoading({
    title:"加载中",
    mask:true
});
```
如果在B页面删除Taro.showLoading就没有问题。会一直执行showToast的complete函数
`
Taro.navigateTo({
        url:B页面
    })
`
如果是我用法的问题，请提示谢谢！

**Comment by Garfield550** [comment]
<img width="418" alt="Screen Shot 2019-03-28 at 10 14 23" src="https://user-images.githubusercontent.com/3471836/55124762-59ee6d80-5142-11e9-9189-a920440c28a0.png">

**Comment by luckyadam** [comment]
楼上已经答复了
