### ISSUE TITLE
百度小程序componentDidShow componentDidHide没触发

### ISSUE THREAD

**Issue by lyevdsky** [NervJS/taro#2605]
**问题描述**
百度小程序componentDidShow componentDidHide没触发

**系统信息**

 - Taro 版本 1.2.16

**Comment by luckyadam** [comment]
在页面中使用

**Comment by lyevdsky** [comment]
![TIM截图20190328150114](https://user-images.githubusercontent.com/12131431/55136830-65ee2580-516a-11e9-823a-740f5914b901.png)
原生小程序，这个方法在自定义组件里也会触发的

> 在页面中使用

**Comment by charmtiger** [comment]
这个只在页面组件中使用，你可以使用 ref 来调用子组件方法

**Comment by lyevdsky** [comment]
现在是微信可以触发，百度的不可以。每个页面都引入的组件，还要每个页面都使用ref来调用。@charmtiger @luckyadam

**Comment by Chen-jj** [comment]
@lyevdsky 下一版本可用
