### ISSUE TITLE
小程序打开H5页面，onClic事件被点击出现Uncaught (in promise)

### ISSUE THREAD

**Issue by Teitei90** [NervJS/taro#2608]
使用Taro写了一套小程序与H5共用的代码
1.点击小程序中的某个路由跳到H5页面中,pages/webview/index；
2.再点击H5页面的onClick事件,在小程序的调试页面中出现Uncaught (in promise)
   然而再小程序中使用Taro.nagvigateTo~~跳转到小程序中的页面，onClick事件可以生效

![image](https://user-images.githubusercontent.com/49016694/55135858-c891f200-5167-11e9-99d3-7fcc4242f568.png)

**Comment by vimcaw** [comment]
请补充详细、完整的报错信息

**Comment by Littly** [comment]
goToDetail函数内部报错了 检查下实现吧
