### ISSUE TITLE
Taro编译成h5,如何实现图片上传功能？

### ISSUE THREAD

**Issue by bingo618** [NervJS/taro#2609]
**期望行为**
实现图片上传

**报错信息**
![TIM截图20190328144407](https://user-images.githubusercontent.com/20422686/55135955-055de900-5168-11e9-8f91-f414c8037646.png)
![image](https://user-images.githubusercontent.com/20422686/55136075-5ff74500-5168-11e9-94b3-c97ef3e82331.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.2.21]
 - Node.js 版本 [e.g. 10.14.0 ]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
你这个问题和 Taro 无关。 你看你的 request headers 已经有黄色的警告标示。你去搜一下这个就能解决

**Comment by bingo618** [comment]
请问选择图片后，返回的是blobURL,使用 new FormData()，模拟表单提交，直接append("file", file)这个blobURL,上传后图片无法显示？
