### ISSUE TITLE
windows环境下微信开发工具启动不成功

### ISSUE THREAD

**Issue by lynshir** [NervJS/taro#2617]
**问题描述**
今天回家后在家里的windows电脑启动程序，微信开发工具控制台报错 `VM5158:5 Cannot read property 'Symbol(Symbol.iterator)' of undefined`,页面显示不出来，但是真机调试和预览都可以正常进行

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

```
  Taro CLI 1.2.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
```

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
升级到最新版本的微信开发者工具
