### ISSUE TITLE
taro H5下，路由跳转时，怎么传递state数据

### ISSUE THREAD

**Issue by DuduStyle** [NervJS/taro#2623]
**问题描述**
路由跳转非query参数，怎么传递；
在小程序中提供了`this.$preload`,h5中怎么设置

[或者可以直接贴源代码，能贴文字就不要截图]

```js
Taro.navigateTo({ url: `/pages/buy/createOrder`});
// 除了query参数，其他参数怎么设置，

```
![image](https://user-images.githubusercontent.com/31200868/55208800-8bd30300-521a-11e9-86a1-000395ff7726.png)

**Comment by luckyadam** [comment]
hello~ 
目前可以用 redux 或者下面方式处理
https://nervjs.github.io/taro/docs/best-practice.html#%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F

H5 中可以考虑加入 $preload

**Comment by DuduStyle** [comment]
现在是采用了redux，你提到的H5中考虑使用$preload，这个我当时按照文档试了下，好像是不行；就没继续采用了 @luckyadam
