### ISSUE TITLE
支付宝编译报错，微信小程序就没有问题

### ISSUE THREAD

**Issue by numcome** [NervJS/taro#2630]
模拟器显示：
![image](https://user-images.githubusercontent.com/31194716/55221456-7bd01900-5244-11e9-9fbb-09bb28e4014c.png)

编译日志显示：
![image](https://user-images.githubusercontent.com/31194716/55221546-aa4df400-5244-11e9-997d-95d2fca6bdbf.png)
编译后代码：
![image](https://user-images.githubusercontent.com/31194716/55221591-c487d200-5244-11e9-9238-9b001a7be1e9.png)
![image](https://user-images.githubusercontent.com/31194716/55221602-cd78a380-5244-11e9-9d7e-e6227eb0d172.png)
编译前代码：
![image](https://user-images.githubusercontent.com/31194716/55221633-dff2dd00-5244-11e9-88e4-88588b6c3338.png)

**问题描述**
该问题只在支付宝小程序中出现

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

import Taro, { Component } from '@tarojs/taro'
import { View, Image, Text } from '@tarojs/components'

import './index.scss'
import '../../assets/css/iconfont/iconfont.css'

import { get as getGlobalData } from '../../static/js/global_data'
import base from '../../static/js/base'
import common from '../../service/common'

import NumInput from '../numInput'

class Index extends Component {
	static defaultProps = {
		goodsInfo: null,
		onGetScope() { },//获取该组件ref，便于父组件调用内部方法
		onGetGoodsDatilsGG() { },//从商品规格更新商品详情数据
	}
	constructor() {
		super(...arguments)
	}
	state = {
		isShow: false,
		canSubmit: true,//是否可以提交数据创建订单的开关
		goodsType: 0,//订单创建方式---0是加入购物车--1是立即购买--2是拼团活动中的单独购买不用优惠---3是拼团
		N_NUM: 1,
		imgUrl: getGlobalData('domainImg'),//图片前缀
		fPrice: 0,//优惠金额
		integral: 0,//积分
		salemodel: null,//当前活动
		sType: null,//优惠方式--0--无优惠，2--秒杀，3--满减，5--积分，12--打折，pinTuan--拼团（当拼团时，优惠金额又为0的时候则代表订单创建方式为2）
		newLvgg: null,//商品规格
		joinData: null,//当前拼团数据
		N_SPV_ID_Arr: {//当前选择的规格，该数据最多三种规格，无选择时传0   用于传入701b接口的数据
			Spv1: 0,
			Spv2: 0,
			Spv3: 0,
		},
	}
	componentWillMount() { }

	componentDidMount() {
		this.props.onGetScope(this)
	}

	componentWillUnmount() { }

	componentDidShow() { }

	componentDidHide() { }
	boxClick(e) {
		//为盒子添加一个点击事件 阻止事件冒泡
		e.stopPropagation()
	}
	isJsonStr(str) {
		/* 判断是否未JSON字符串 */
		try {
			if (typeof JSON.parse(str) == "object") {
				return true;
			}
		} catch (e) { }
		return false;
	}
	showCut(d) {
		//此处做一个深拷贝，以免更改到父组件的数据
		let sData = {
			isShow: !this.state.isShow,
		}
		if (d != 0 && d) {
			console.log(d, 'JSON.parse(JSON.stringify(d))')
			let data = JSON.parse(JSON.stringify(d))
			sData['goodsType'] = data.type;
			sData['fPrice'] = data.fPrice;
			sData['integral'] = data.integral;
			sData['sType'] = data.sType;
			sData['newLvgg'] = data.lvgg;
			sData['salemodel'] = data.salemodel;
			sData['joinData'] = data.joinData;
			/* if (data.lvgg && data.lvgg.length > 0) {
				sData['canSubmit'] = false;
			} */
		} else {
			sData['N_SPV_ID_Arr'] = { Spv1: 0, Spv2: 0, Spv3: 0, }
			sData['newLvgg'] = null;
			sData['sType'] = null;
		}
		this.setState(sData)
	}

	//没做的-----------------------------------------
	onAddShopNum(bNo, types) {
		//获取创建订单的数量
		// this.setState({
		// 	N_NUM: 1
		// })
		const { goodsInfo } = this.props;
		let { N_NUM } = this.state;
		if (types == 'add') {  // +
			if (this.state.N_NUM >= goodsInfo.STOCK) {
				base.showToast('商品库存不足了！', 'none')
				return
			}
			N_NUM++
		}
		if (types == 'minus') { // -
			if (this.state.N_NUM == 1) {
				base.showToast('不能再减了！', 'none')
				return
			}
			N_NUM--
		}
		this.setState({ N_NUM })
	}
	onAddGoods() {
		/* 数据都准备好了 */
		const { goodsType, N_NUM, canSubmit, salemodel, sType, N_SPV_ID_Arr, joinData } = this.state;
		const { goodsInfo } = this.props;
		// sType: null,//优惠方式--0--无优惠，2--秒杀，3--满减，5--积分，12--打折，pinTuan--拼团（当拼团时，优惠金额又为0的时候则代表订单创建方式为2）
		//salemodel优惠数据--salemodel.SaleId优惠活动id
		// goodsType: 0,//订单创建方式---0是加入购物车--1是立即购买--2是拼团活动中的单独购买不用优惠---3是拼团----4是参加拼团
		// canSubmit: true,//是否可以提交数据创建订单的开关---暂时未使用
		// N_SPV_ID_Arr--当前选择的规格ID数据
		// joinData参加拼团的数据----数据接口说明
		if (!canSubmit) {
			return false;
		}
		if (salemodel) {
			/* 普通优惠 --传入优惠id*/
			console.log(salemodel, sType, N_SPV_ID_Arr, '优惠')
		} else {
			if (sType == 'pinTuan') {
				/* 拼团 */
				if (goodsType == 2) {
					/* 拼团--单独购买 */
					console.log('拼团--单独购买')
				} else if (goodsType == 3) {
					/* 拼团购买 */
					console.log('拼团购买')
				} else if (goodsType == 4) {
					/* 拼团购买--此处可能要传入参与拼团的拼团号-数据再joinData中 */
					console.log(joinData, '参加拼团')
				}
			} else {
				/* 普通购买--无优惠 */
				common.changeCar(this, '800', goodsInfo, N_NUM, goodsType, (res) => {
					this.showCut()
					if (goodsType == 0) {
						base.showToast('加入购物车' + res.msg)
					} else {
						Taro.navigateTo({
							url: `/pages/orderSubmit/orderSubmit?totalNum=${res.cartnum}&&cids=${res.cartid}`
						})
					}
				})
			}
		}

	}
	setGg(index, id) {
		//设置当前选择的规格
		const { N_SPV_ID_Arr, newLvgg } = this.state;
		newLvgg.map((val, inum) => {
			if (index == inum) {
				val.SpvList.map((v) => {
					if (v.isChoose) {
						v.isChoose = false
					}
				})
				val.SpvList.map((value, inNum) => {
					if (value.N_SPV_ID == id) {
						newLvgg[inum].SpvList[inNum].isChoose = true;
						N_SPV_ID_Arr['Spv' + (index + 1)] = id;
					}
				})
			}
		})
		this.setState({ N_SPV_ID_Arr, newLvgg }, () => {
			let chooseLength = 0;
			this.state.newLvgg.map((val) => {
				val.SpvList.map((v) => {
					if (v.isChoose) {
						chooseLength++
					}
				})
			})
			//选择的规格与获取到的规格数量相同时则请求数据
			if (chooseLength >= newLvgg.length) {
				/* this.setState({
					canSubmit: true
				}) */
				this.props.onGetGoodsDatilsGG(N_SPV_ID_Arr);
			}
		})
	}
	render() {
		const { isShow, imgUrl, fPrice, integral, newLvgg, canSubmit } = this.state;
		const { goodsInfo } = this.props;
		return (
			<View>
				{
					isShow ? (
						<View className='shopCloseModal' onClick={this.showCut.bind(this, 0)}>
							{
								goodsInfo ? (
									<View className='box' onClick={this.boxClick.bind(this)}>
										<View className='head'>
											<View className='shopImg'>
												<Image className='headImg' src={imgUrl + goodsInfo.C_MAINPICTURE}></Image>
											</View>
											<View className='center'>
												<View className='center1'>{goodsInfo.GOODS_NAME}</View>
												<View className='center2'>{goodsInfo ? (goodsInfo.STOCK > 15) ? '库存充足' : (goodsInfo.STOCK <= 0) ? '库存不足' : '库存紧张' : ''}</View>
												{
													fPrice != 0 && fPrice ? (
														<View className='center3'>
															<View className='cen1'>￥{fPrice}</View>
															{integral != 0 && integral ? <View className='cen3'>+{integral}积分</View> : ''}
															<View className='cen2'>原价:￥{goodsInfo.salearea ? goodsInfo.salearea : goodsInfo.YSale_Price}</View>
														</View>
													) : (
															<View className='center3'>
																<View className='cen1'>￥{goodsInfo.salearea ? goodsInfo.salearea : goodsInfo.YSale_Price}</View>
															</View>
														)
												}
											</View>
											<View className='shopRight'>
												<View className='close'>
													<Text className='iconfont icon-close' onClick={this.showCut.bind(this, 0)}></Text>
												</View>
												<View className='numAdd'>
													<NumInput type='square' nums={this.state.N_NUM} onChangeCartNum={this.onAddShopNum.bind(this)}></NumInput>
												</View>
											</View>
										</View>
										{
											newLvgg && newLvgg.length > 0 ? (
												<View className='closeBody'>
													{
														newLvgg.map((val, i) => (
															<View className='bodyItem' key={'itBox' + i}>
																<View className='bodyHead'>{val.C_SPE_NAME}</View>
																<View className='bodyBody'>
																	{
																		val.SpvList.map((value, index) => (
																			<View onClick={this.setGg.bind(this, i, value.N_SPV_ID)} className={`spvList ${value.isChoose ? 'isChoose' : 'onChoose'}`} key={'item' + index}>
																				{value.C_SPE_VALUE}
																			</View>
																		))
																	}
																</View>
															</View>
														))
													}
												</View>
											) : ''
										}
										<View className={`food ${canSubmit ? 'can' : 'foodNoSub'}`} onClick={this.onAddGoods.bind(this)}>确定</View>
									</View>
								) : ''
							}
						</View >
					) : ''
				}
			</View>

		)
	}
}
export default Index;

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by numcome** [comment]
![image](https://user-images.githubusercontent.com/31194716/55221789-4c6ddc00-5245-11e9-9bef-ebdf7682e418.png)
重新再编译一次又出现这种情况

**Comment by Chen-jj** [comment]
@numcome 应该是支付宝小程序模板中用到 <= 会报错，我们以反馈给支付宝侧

![image](https://user-images.githubusercontent.com/11807297/55402008-eeaefc00-5584-11e9-94d2-bea0a8d0baf3.png)

你可以把那句判断先在 render 函数里赋值给一个变量，然后渲染此变量。

**Comment by Chen-jj** [comment]
@numcome 支付宝方面回复

![image](https://user-images.githubusercontent.com/11807297/55404434-76e3d000-558a-11e9-9a43-546a0670f05b.png)
