### ISSUE TITLE
ref百度小程序不能用啊，调用不了子组件方法

### ISSUE THREAD

**Issue by yikalosi** [NervJS/taro#2631]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
没有复现的代码就相当于没说

**Comment by Chen-jj** [comment]
@yikalosi 目前百度生命周期的触发顺序和微信非常不同，父组件 ready 了子组件还没有 created，这样是无法实现 ref 的。我们正在和百度沟通解决中。

**Comment by zpzxgcr** [comment]
> @yikalosi 目前百度生命周期的触发顺序和微信非常不同，父组件 ready 了子组件还没有 created，这样是无法实现 ref 的。我们正在和百度沟通解决中。

请问最新进展如何

**Comment by Chen-jj** [comment]
@zpzxgcr 百度那边 9.9 会上线新的生命周期触发时机，近期我们这边会调试适配一下。https://smartprogram.baidu.com/forum/topic/show/70128

**Comment by zpzxgcr** [comment]
> @zpzxgcr 百度那边 9.9 会上线新的生命周期触发时机，近期我们这边会调试适配一下。https://smartprogram.baidu.com/forum/topic/show/70128

辛苦了

**Comment by dpwgit** [comment]
> @zpzxgcr 百度那边 9.9 会上线新的生命周期触发时机，近期我们这边会调试适配一下。https://smartprogram.baidu.com/forum/topic/show/70128

请问Taro近期有对这边做适配的计划嘛？1.3.22版本Taro编译成百度小程序还是会出现自定义组件在componentDidMount钩子中无法拿到节点信息的情况。
![image](https://user-images.githubusercontent.com/39178009/67998798-ac71a880-fc94-11e9-863c-7633d3cbbc49.png)
![image](https://user-images.githubusercontent.com/39178009/67998824-c6ab8680-fc94-11e9-85b3-d08515779420.png)

**Comment by Chen-jj** [comment]
@dpwgit 适配以做，但还不能上。因为百度那边基础库升级率只有90%，估计还有比较长的一段时间。先手动 querySelector 或 selectComponent 吧。

**Comment by Daisy1213** [comment]
> @dpwgit 适配已做，但还不能上。因为百度那边基础库升级率只有90%，估计还有比较长的一段时间。先手动 querySelector 或 selectComponent 吧。

selectComponent现在也不能正常使用啊，我想直接调用子组件的方法，但是发现百度和微信该组件方法所在的对象层级都不一样，很难兼容

**Comment by Chen-jj** [comment]
@Daisy1213 怎么说，两者都是使用各自底层提供的 selectComponent 方法，获取自定义组件实例。

https://github.com/NervJS/taro/blob/400a6d90de5ddf3a60762bad25fdc91027fe8aac/packages/taro-weapp/src/create-component.js#L236

https://github.com/NervJS/taro/blob/400a6d90de5ddf3a60762bad25fdc91027fe8aac/packages/taro-swan/src/create-component.js#L260

对象层级的问题 Taro 解决不了，可以各自写兼容代码。

**Comment by Daisy1213** [comment]
> @Daisy1213 怎么说，两者都是使用各自底层提供的 selectComponent 方法，获取自定义组件实例。
> 
> https://github.com/NervJS/taro/blob/400a6d90de5ddf3a60762bad25fdc91027fe8aac/packages/taro-weapp/src/create-component.js#L236
> 
> https://github.com/NervJS/taro/blob/400a6d90de5ddf3a60762bad25fdc91027fe8aac/packages/taro-swan/src/create-component.js#L260
> 
> 对象层级的问题 Taro 解决不了，可以各自写兼容代码。

经过尝试，使用
```
this.$scope.selectComponent('#id').$component 可以获取到组件实例，进而调用其方法
```
百度、微信、qq都可以正常调用，希望可以帮助到需要的小伙伴，但是还是希望taro尽快把ref这种形式调用的上线，方便开发者使用

**Comment by shenghanqin** [comment]
试试看最新版本吧？

**Comment by zhiqingchen** [comment]
1.3.29
2.0.0-beat.9
百度小程序ref都是undefined
