### ISSUE TITLE
RN项目在android真机上Hot Reloading无效

### ISSUE THREAD

**Issue by wenji-my** [NervJS/taro#2637]
我在真机上已经开启Hot Reloading，修改代码后有Hot Reloading提示，但是界面并没有更新，这是什么问题呢？
**系统信息**

 - 操作系统: [e.g. Mac OS 10.13.6]
 - Taro 版本 [e.g. v1.2.20]
 - Node.js 版本 [e.g. v8.9.0]
 - 报错平台 [RN]

**Comment by Pines-Cheng** [comment]
Remote JS Debugging 是正常的吧？ @wenji-my

**Comment by wenji-my** [comment]
@Pines-Cheng Remote JS Debugging是正常的

**Comment by shenghanqin** [comment]
@wenji-my 试试看最新版本效果吧?
