### ISSUE TITLE
npm run dev:rn 失败，真机红屏

### ISSUE THREAD

**Issue by chzhewl** [NervJS/taro#2638]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)
**问题描述**
1. taro init myApp 初始化项目
2. taro-native-shell android Studio 真机安装成功。
3. npm run dev:rn 出现如下错误：
   (node:19264) UnhandledPromiseRejectionWarning: Error: Error: Could not find "sty
lelint-taro-rn". Do you need a `configBasedir`?
    at Promise.all.then.then.then.catch (C:\Users\Administrator\AppData\Roaming\
npm\node_modules\@tarojs\cli\src\rn.js:79:11)
4. 安卓真机上红屏，出现如下错误：
   error calling AppRegistery.runApplication
Could not get BatchedBridge, make sure your bundle is packaged correctly

补充：
参考issue #2562 的方法，也未能解决 以上 3 出现的问题。

**系统信息**
Taro v1.2.22
Taro CLI 1.2.22 environment info:
  System:
    OS: Windows 7
  Binaries:
    Node: 8.12.0 - E:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - E:\Program Files\nodejs\npm.CMD

**Comment by Pines-Cheng** [comment]
stylelint 相关的的包装上时候，还是有第三个报错？ @chzhewl

**Comment by soymikey** [comment]
![image](https://user-images.githubusercontent.com/37310671/55307274-a4952000-5489-11e9-8aa8-cb5499858180.png)
 在启动模拟器后 就发生错误了， error calling AppRegistry,runApplication

**Comment by leopard7777777** [comment]
+1

.rn_temp目录下的tmp目录没有生成

**Comment by Pines-Cheng** [comment]
@leopard7777777 开发模式不会生成 tmp 目录啊。

**Comment by leopard7777777** [comment]
同样的问题
error calling AppRegistery.runApplication
Could not get BatchedBridge, make sure your bundle is packaged correctly

taro build --type rn

也不生成tmp

**Comment by leopard7777777** [comment]
应该是目录的问题，默认sourceRoot要是src

**Comment by Pines-Cheng** [comment]
@leopard7777777 👍
