### ISSUE TITLE
编译成微信小程序，父组件给子组件传递函数(非匿名函数，以on开头，直接使用this.props.xxxFun调用)，父组件中的函数没有被调用

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#2639]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by SunnyQjm** [comment]
编译成h5正常，微信小程序不正常。查看编译生成的dist文件，发现子组件中发出的信号带on前缀，而父组件中生成的bind函数后面没有on前缀。改dist中的代码，给父组件中的bind函数添加on前缀，仍然无效，子组件并没有发出该信号。直接在子组件的函数调用位置使用this.$scope.triggerEvent发送对应信号，父组件中的事件处理函数才执行

**Comment by SunnyQjm** [comment]
https://github.com/SunnyQjm/TaroBugReportDemo
这是复现Demo代码

**Comment by Chen-jj** [comment]
@SunnyQjm CLI 和依赖版本保持一致

**Comment by SunnyQjm** [comment]
直接用的v1.2.22 的CLI工具初始化的项目，依赖版本也会不一致嘛？

**Comment by SunnyQjm** [comment]
检查了一下依赖版本和CLI版本都是1.2.22

**Comment by SunnyQjm** [comment]
@Chen-jj

**Comment by SunnyQjm** [comment]
玄学，现在Demo又好用了

**Comment by SunnyQjm** [comment]
@

**Comment by SunnyQjm** [comment]
@Chen-jj 我发现在一个页面中引入一个组件，如果在Page页的配置中编写usingComponents，如下：
```JavsScript
config: Config = {
    usingComponents: {
      XbBar: 'components/xb-bar/index'
    }
  };
```
如果在页面的配置中配置类usingComponents，则传递给子组件的函数将不会被正常执行。如果usingComponents不配置，Taro仍然能正常编译，且传递给子组件的函数能正常执行。那usingComponents还有没有必要配置呢，还是这只是Taro的一个Bug？

**Comment by Chen-jj** [comment]
@SunnyQjm 引用原生组件才需要配置 usingComponents。[文档](https://nervjs.github.io/taro/docs/mini-third-party.html#%E5%BC%95%E5%85%A5%E7%AC%AC%E4%B8%89%E6%96%B9%E7%BB%84%E4%BB%B6)
