### ISSUE TITLE
微信小程序编译成taro再编译成微信小程序，文件丢失

### ISSUE THREAD

**Issue by json11** [NervJS/taro#2641]
**问题描述**
【由于之前用的微信小程序封装了很多公司组件，所以要将微信小程序编译成taro，但是很多文件丢失】

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.22]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**Comment by yuche** [comment]
描述结果是没用的，得描述过程
