### ISSUE TITLE
scss中支持defineConstants

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#2644]
**问题描述**
希望将一些样式相关的参数设置成常量，然后在样式中读取

**系统信息**
👽 Taro v1.2.22

  Taro CLI 1.2.22 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by tourze** [comment]
这个需求跟 https://github.com/NervJS/taro/issues/425 中提及的很类似。希望官方能够支持下哈

**Comment by luckyadam** [comment]
好嘞，我们看下

**Comment by luckyadam** [comment]
Duplicate of #2644
