### ISSUE TITLE
h5 部署服务器显示css和js路径错误，本地打开静态网页没问题！

### ISSUE THREAD

**Issue by 516821202** [NervJS/taro#2650]
h5 打包后本地可打开静态网页，但部署到配置了nginx的服务器上后，显示css和js路径错误！！
![image](https://user-images.githubusercontent.com/31182186/55305040-1a48be00-5481-11e9-9dc7-25af42a75e23.png)

**Comment by nevernet** [comment]
看看目录存在吗？

**Comment by Littly** [comment]
检查下你的publicPath，是不是用了相对路径
