### ISSUE TITLE
关于在小程序在iphone xs max 系统12.2，Input 组件无法被遮罩层覆盖

### ISSUE THREAD

**Issue by Zhou-Bill** [NervJS/taro#2653]
**问题描述**
关于在小程序在iphone xs max 系统12.2，Input 组件无法被遮罩层覆盖

**复现步骤**
1. 遮罩层无法遮挡 input 组件， input 框貌似在遮罩层上方，**已使用过z-index属性**
2. 出现的情况只存在于 iphone xs max 系统是12.2版本的机子上

![image](https://user-images.githubusercontent.com/13554001/55308249-b4623380-548c-11e9-969d-f0863e25a7a6.png)

* 其中test 为遮罩层
* `<BannerSearch />` 只是一个简单的input 组件
```js
BannerSearch.js
<View className={styles.container}>
    <Input placeholder={"input"} className={styles.input} placeholderStyle='color:#b2b2b2' onInput={this.handleChange}/>
     <Button className={styles.searchBtn} hoverClass={"none"} type={"primary"} onClick={this.goTo} >搜索</Button>
</View>
```

```
.test.module.less

.test {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: #000;
      z-index: 99;
}
```

> 结果

微信小程序的结果
![image](https://user-images.githubusercontent.com/13554001/55308501-88937d80-548d-11e9-80bd-342010e983a4.png)

iphone xs max 的结果
![image](https://user-images.githubusercontent.com/13554001/55308663-f9d33080-548d-11e9-8776-f0cb210bd547.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.2.17

  Taro CLI 1.2.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by js-newbee** [comment]
@Zhou-Bill input 组件是原生组件，层级无法被覆盖的
https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html

**Comment by Zhou-Bill** [comment]
> @Zhou-Bill input 组件是原生组件，层级无法被覆盖的
> https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html

但是遮罩层的布局是`position:fixed`的话无法遮盖？
另外就是 再其他手机不会出现这个问题，其他手机只的是iphone6s, iphone7 ,iphonex ,和安卓手机，都没出现这个问题。。。

**Comment by js-newbee** [comment]
> > @Zhou-Bill input 组件是原生组件，层级无法被覆盖的
> > https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html
> 
> 但是遮罩层的布局是`position:fixed`的话无法遮盖？
> 另外就是 再其他手机不会出现这个问题，其他手机只的是iphone6s, iphone7 ,iphonex ,和安卓手机，都没出现这个问题。。。

`position: fixed` 也不是万能的，比如不能覆盖 tabBar，只是想说这种情况多半是小程序自身的限制...

**Comment by Zhou-Bill** [comment]
> > > @Zhou-Bill input 组件是原生组件，层级无法被覆盖的
> > > https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html
> > 
> > 
> > 但是遮罩层的布局是`position:fixed`的话无法遮盖？
> > 另外就是 再其他手机不会出现这个问题，其他手机只的是iphone6s, iphone7 ,iphonex ,和安卓手机，都没出现这个问题。。。
> 
> `position: fixed` 也不是万能的，比如不能覆盖 tabBar，只是想说这种情况多半是小程序自身的限制...

好吧

**Comment by js-newbee** [comment]
@Zhou-Bill 建议用原生的写个小 demo 验证一下吧，以免真的是 Taro 的问题 😂
