### ISSUE TITLE
npm run dev:rn 后 报错 没有app_styles文件

### ISSUE THREAD

**Issue by soymikey** [NervJS/taro#2654]
![image](https://user-images.githubusercontent.com/37310671/55309438-5e8f8a80-5490-11e9-8f96-7b2b6e296dc3.png)

编译成react native， android 虚拟机打开报错，以为没有app_styles文件

**Comment by Pines-Cheng** [comment]
编译的时候命令行是否有报错？如果有报错，可能会影响文件生成。

**Comment by soymikey** [comment]
> 编译的时候命令行是否有报错？如果有报错，可能会影响文件生成。

 Pines-Cheng,  谢谢支持 最终安装了3个库 stylelint, stylelint-config-taro-rn, stylelint-taro-rn 才顺利运行起来

**Comment by soymikey** [comment]
> 编译的时候命令行是否有报错？如果有报错，可能会影响文件生成。

 谢谢支持 最终安装了3个库 stylelint, stylelint-config-taro-rn, stylelint-taro-rn 才顺利运行起来
