### ISSUE TITLE
请问 AtRadio 中的option的desc如何换行呢？

### ISSUE THREAD

**Issue by MikyChow** [NervJS/taro#2655]
**问题描述**
[问题描述：请问 AtRadio 中的option的desc如何换行呢？

**复现步骤**
// 这里可以贴代码
`<AtRadio
              options={[
                { label: '官方配送', value: TransportMode.OfficialShipping, desc: '订单满' + config.freeShippingAmount + '即可选择官方配送(免费)' },
                { label: '客户自提', value: TransportMode.SelfHanding, desc: 'AAAAA <br /> BBBBB' },
              ]}
              value={this.state.transportMode}
              onClick={(tranportMode) => this.handerChangeTranportMode(tranportMode)}
            />`
**期望行为**
br 能换行
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
desc必须是纯字符

**Comment by Garfield550** [comment]
AtRadio 的 desc 使用的是 View 组件，desc 样式指定宽度为 AtRadio 的 86%，如果想换行可以试着调整 desc 的宽度，比如
![image](https://user-images.githubusercontent.com/3471836/55387867-ce6f4500-5564-11e9-9ae9-a3a68e5e74a1.png)
![image](https://user-images.githubusercontent.com/3471836/55387997-0c6c6900-5565-11e9-8c43-2566274f9698.png)

https://github.com/NervJS/taro-ui/blob/902c951ad40f9bfd29ede6cd0e68adc843258135/src/style/components/radio.scss#L43-L51

https://github.com/NervJS/taro-ui/blob/6c53d976d099e80d202fef1565492dc86a05d7b9/src/components/radio/index.js#L56

**Comment by MikyChow** [comment]
好的、十分感谢 @Garfield550 
但是还是希望能在后期能自定义标签。
