### ISSUE TITLE
iconfont转h5后不显示

### ISSUE THREAD

**Issue by wnuoer** [NervJS/taro#2656]
**问题描述**
[问题描述：iconfont转h5后不显示]

**复现步骤**

```js
<View className='iconfont icon-Eye article_text' />

@font-face {
  font-family: 'iconfont'; /* project id 704506 */
  src: url('//at.alicdn.com/t/font_704506_1gug7yhfqul.eot');
  src: url('//at.alicdn.com/t/font_704506_1gug7yhfqul.eot?#iefix')
      format('embedded-opentype'),
    url('//at.alicdn.com/t/font_704506_1gug7yhfqul.woff2') format('woff2'),
    url('//at.alicdn.com/t/font_704506_1gug7yhfqul.woff') format('woff'),
    url('//at.alicdn.com/t/font_704506_1gug7yhfqul.ttf') format('truetype'),
    url('//at.alicdn.com/t/font_704506_1gug7yhfqul.svg#iconfont') format('svg');
}
.iconfont {
  font-family: "iconfont" !important;
  font-size: 32px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.icon-Eye:before {
  content: "\e70c";
}
```

**期望行为**
[转换出来的h5图标能出来]

**报错信息**

![image](https://user-images.githubusercontent.com/15000470/55312802-ebd6dd00-5498-11e9-87a0-7f301ee5b893.png)
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.2.22 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by nevernet** [comment]
查查h5下面字体文件确认引入了吗？

**Comment by LeeYoung-s** [comment]
遇到了相同的问题如何解决的 @wnuoer

**Comment by LeeYoung-s** [comment]
May I ask how this problem is finally solved?

**Comment by Littly** [comment]
需要复现的代码 目前看不出什么问题
