### ISSUE TITLE
创建完一个新项目后 npm install 报错

### ISSUE THREAD

**Issue by streamBamboo** [NervJS/taro#2660]
1.2.7 (node_modules\_chokidar@2.1.5@chokidar\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\epiboly\copyMedical\node_modules\.staging\fsevents-28762e6f\node_modules\ansi-regex' -> 'E:\epib
oly\copyMedical\node_modules\.staging\ansi-regex-6d762bf5'

npm ERR! path E:\epiboly\copyMedical\node_modules\_dom7@2.1.3@dom7\node_modules\ssr-window
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'E:\epiboly\copyMedical\node_modules\_dom7@2.1.3@dom7\node_modules\ssr-window' -> 'E:\epiboly\copyMedical\node_modules\_dom7@2.1.3
@dom7\node_modules\ssr-window'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2019-04-01T15_25_15_041Z-debug.log

E:\epiboly\copyMedical>
![image](https://user-images.githubusercontent.com/29224540/55339936-3b87c980-54d6-11e9-82eb-e7775bbcf702.png)

win10系统；
taro版本：1.2.13

**Comment by nevernet** [comment]
npm安装问题吧，跟taro无关的。

**Comment by streamBamboo** [comment]
> npm安装问题吧，跟taro无关的。

之前一直用着都没问题的，就是这次建一个新项目出现这个问题

**Comment by streamBamboo** [comment]
![image](https://user-images.githubusercontent.com/29224540/55371568-3e63d800-5531-11e9-8af5-0c9dfac72cfe.png)
![image](https://user-images.githubusercontent.com/29224540/55371615-63584b00-5531-11e9-8032-68d3709d2c69.png)

这是另外一台电脑也是这个问题  刚创建一个taro项目，难道是因为没有用TypeScript的问题吗？这两个项目都选择了TypeScript为no

**Comment by streamBamboo** [comment]
这个问题我觉得不是npm安装的问题，后续我重新装了好几次node，结果还是一样，问题出现在npm安装taro的时候出现warn， 然后taro init项目之后再npm install就出现问题了，后面我用cnpm重新装了一遍tarojs\cli再cnpm install才能让项目跑起来，这是我在公司的电脑的操作，自己的电脑还要回去测试一波才知道有没有问题

**Comment by nevernet** [comment]
可以确定是跟Taro无关的，根据错误提示仔细查一下. 如果你用cnpm可以，那很可能就是**的问题
