### ISSUE TITLE
使用1.2.22版本h5-router运行报错

### ISSUE THREAD

**Issue by qiangck** [NervJS/taro#2665]
**问题描述**
[问题描述：Uncaught TypeError: (0 , _router.createHistory) is not a function]

**复现步骤**
[复现问题的步骤]
1. 项目taro版本为1.2.4，本地taro版本为1.2.22
2. 重新删除node_modules和package-lock.json并npm i重新安装，使用的是taobao源
3. 项目依赖安装完成后npm run dev:h5启动项目后提示错误
4. Uncaught TypeError: (0 , _router.createHistory) is not a function

[或者可以直接贴源代码，能贴文字就不要截图]

```js
//报错地方为.temp/app.js文件第19行

const _taroHistory = createHistory({
  mode: "hash",
  basename: "/",
  customRoutes: {},
  firstPagePath: "/pages/home/index"
});

```

**期望行为**
之前可以正常运行，只是更换了环境

**报错信息**
app.js?d0a8:19 Uncaught TypeError: (0 , _router.createHistory) is not a function
    at eval (app.js?d0a8:19)
    at Object../.temp/app.js (app.js:915)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.0 (app.js:1604)
    at __webpack_require__ (app.js:767)
    at app.js:902
    at app.js:905

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Mac 10.14.4]
 - Taro 版本 [e.g. v.1.2.22]
 - Node.js 版本 [e.g. v10.15.3]
 - 报错平台 [h5]

**Comment by kennir** [comment]
我在 1.2.23 上也碰到这个问题了，只是做了一个 taro update project

**Comment by leidenglai** [comment]
我也遇到这个问题了。在1.2.17升级1.2.23，结果样式错乱，还原回1.2.17后报这个错，后来将@tarojs/cli 这个包也还原回去才好。`yarn global add @tarojs/cli@1.2.17`
话说为什么小版本升级会导致不兼容？？

**Comment by xsq007** [comment]
我用taro 1.2.22也遇到了这个问题，解决办法是在项目里运行 taro update project 更新当前项目的taro依赖。

**Comment by MikyChow** [comment]
更新后，同样遇到了这个问题
