### ISSUE TITLE
关闭页面蒙层， onClick 不生效

### ISSUE THREAD

**Issue by huangfuchangyu** [NervJS/taro#2667]
**问题描述**

在页面A上点击 按钮 显示 一个蒙层B ，然后，关闭蒙层B， 在A页面上的 onClick 事件第一次点击失效（除非点击A页面上任意位置，onclick事件会恢复响应） 
（蒙层是一个positioin：fixed 的半透明div）
真机调试 微信小程序（ios 和 android）机器都会出现此问题

**复现步骤**
[复现问题的步骤]
1. 点击页面A上的红框框显示蒙层 
<img width="314" alt="111" src="https://user-images.githubusercontent.com/28288892/55392326-a6381400-556d-11e9-8b23-2cdd4195dfe5.png">

2. 显示蒙层
<img width="321" alt="2222" src="https://user-images.githubusercontent.com/28288892/55392261-856fbe80-556d-11e9-980d-a369cecdc404.png">

3. 点击蒙层确认按钮 关闭蒙层  

这时 发现 页面A  onClick事件 第一次点击不响应， 当点击A页面 任意位置之后A页面的 onClick 事件才响应

**期望行为**
关闭蒙层之后 onClick事件第一次点击也会响应

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:   ios ， android 真机调试
 - Taro 版本：1.2.16
 - Node.js 版本 : 10.13.0
 - 报错平台： weapp 

**补充信息**
无

**Comment by Chen-jj** [comment]
@huangfuchangyu 真机控制台有没有报错？微信小程序开发者工具能不能复现？升级 CLI 和依赖到最新版本，提供可复现代码。
