### ISSUE TITLE
Taro.request在字节跳动下，请求数据不成功

### ISSUE THREAD

**Issue by kinger906** [NervJS/taro#2670]
Taro.request({
    url: baseUrl + options.url,
    data: {
      ...request_data,
      ...options.data,
    },
    header: {
      'Content-Type': 'application/json',
    },
    method: options.method.toUpperCase(),
  }).then(res => {
    const { statusCode, data } = res;
    if (statusCode >= 200 && statusCode < 300) {
      if (!noConsole) {
        console.log(
          `${new Date().toLocaleString()}【 M=${options.url} 】【接口响应：】`,
          res.data
        );
      }
      if (data.code != 200) {
        Taro.showToast({
          title: `${res.data.error.message}~` || res.data.error.code,
          icon: 'none',
          mask: true,
        });
      }
      return data;
    } else {
      throw new Error(`网络请求错误，状态码${statusCode}`);
    }
  }).catch(err=>{
    console.log('err',err)
  });
请求失败，提示：errMsg: "request:fail"，在H5、微信、支付宝下可以请求数据，望帮忙看看

**Comment by Chen-jj** [comment]
@kinger906 打断点跟踪一下，实际也是调用字节跳动的 [tt.request](https://developer.toutiao.com/docs/api/request.html) 而已。

或者你可以直接使用 `tt.request` 观察是否能请求成功，区分是 Taro 还是小程序的问题。

**Comment by kinger906** [comment]
Taro.request({
    url: xUrl,
    data: xData,
    header: {
      ...xHeaders,
      'Content-Type': 'application/json',
      ...options.headers
    },
    method: options.method.toUpperCase(),
  }).then(res => {
    const { statusCode, data } = res;
    if (statusCode >= 200 && statusCode < 300) {
      if (!noConsole) {
        console.log(
          `${new Date().toLocaleString()}【 M=${options.url} 】【接口响应：】`,
          res.data
        );
      }
      return data;
    } else {
      throw new Error(`网络请求错误，状态码${statusCode}`);
    }
  })

**Comment by Chen-jj** [comment]
> @kinger906 打断点跟踪一下，实际也是调用字节跳动的 [tt.request](https://developer.toutiao.com/docs/api/request.html) 而已。
> 
> 或者你可以直接使用 `tt.request` 观察是否能请求成功，区分是 Taro 还是小程序的问题。

@kinger906 先自行 debug 一下吧，扔一段请求代码意义不大，还是要你自己在该环境下调试才清晰。

**Comment by webCoderJ** [comment]
确实有这个问题，请问解决了吗

**Comment by shenghanqin** [comment]
我写了好几个月的微信和抖音小程序，这个请求的问题没有出现过。你再多打打断点试试看。

**Comment by webCoderJ** [comment]
> 我写了好几个月的微信和抖音小程序，这个请求的问题没有出现过。你再多打打断点试试看。

这个错误是因为没有将请求域名加白名单，或者在开发工具设置忽略（针对头条小程序）
