### ISSUE TITLE
在百度小程序下，给SwiperItem中给子组件传递list数据被转换为object

### ISSUE THREAD

**Issue by kinger906** [NervJS/taro#2671]
<View className='swiper-wrap'>
          <Swiper current={selectIndex} style={{ height }} onChange={this.handleClick.bind(this)}>
            {tabList.map((tab, tabIndex) => {
              return (
                <SwiperItem key={tabIndex}>
                  <ScrollView scrollY onScroll={this.onScroll.bind(this)}>
                    <ItemList list={articles[tabIndex]} height={height} />
                  </ScrollView>
                </SwiperItem>
              )
            })}
          </Swiper>
        </View>

在子组件ItemList中，传递的list是数组，但是子组件内部获取list时，数据却被转换为Object了，请大牛帮忙看看，注意：仅在百度小程序下有此问题，H5、微信、支付宝正常

**Comment by Chen-jj** [comment]
@kinger906 提供页面、组件的完整可复现代码。

**Comment by kinger906** [comment]
getNewList({
      channel_id: value,
      sub_channel_id: -1,
      pageNo: 1,
      pageSize: 20,
      token: '$2a$10$nxmWkR9.ap8aifsTqPq3IOBXslAIFSp',
      userId: '2038e05b-d179-4a98-85cd-80c79a9383c3',
      user_id: '2038e05b-d179-4a98-85cd-80c79a9383c3'
    }).then((res) => {
      let newArticle = new Object();
      newArticle[value] = res.data ? res.data.article_list : []
      this.setState({
        articles: { ...this.state.articles, ...newArticle }
      })
    })
    this.setState({
      selectIndex: value
    })

ItemList.js组件内容：
render() {
        const { list, height, placeholderList } = this.props;
        if (list.length == 0) {
            return (
                <ScrollView scrollY style={{ height }} className='cate-sub-list'>
                    <View>
                        {placeholderList.map((item) => (
                            <View className='cate-sub-list-item' key={item.article_id} data-id={item.article_id} onClick={this.handleClick.bind(this, item)}>
                                <View className='fl'>
                                    <View className='holder-txt'>
                                        <BlockHolder />
                                        <BlockHolder />
                                        <BlockHolder width='50%' />
                                    </View>
                                    <View>
                                        <BlockHolder width='25%' />
                                    </View>
                                </View>
                                <View className='fr holder-img'>
                                    <Image src={defaultImg}></Image>
                                </View>
                            </View>
                        ))}
                    </View>
                </ScrollView>
            )
        }
        return (
            <View style={{ height }} className='cate-sub-list'>
                {list.map((item) => (
                    <View className='cate-sub-list-item' key={item.article_id} data-id={item.article_id} onClick={this.handleClick.bind(this, item)}>
                        <View className='fl'>
                            <Text className='title'>{item.title}</Text>
                            <View>
                                <Text className='origin'>
                                    <Text>{item.source}</Text>
                                    <Text className='segment'>|</Text>
                                    <Text>{parseBeforeTime(item.timebefore)}</Text>
                                </Text>
                            </View>
                        </View>
                        <View className='fr'>
                            <View className='img' style={{ backgroundImage: `url(${item.small_img_url[0] || defaultImg})` }}></View>
                        </View>
                    </View>
                ))}
            </View>
        )

**Comment by Chen-jj** [comment]
@kinger906 提问请编辑好**代码格式**。
