### ISSUE TITLE
usingComponents属性对应值使用alias没有被解析

### ISSUE THREAD

**Issue by xuanmiao-zero** [NervJS/taro#2672]
**问题描述**
[page页下的config中的usingComponents属性对应值无法使用alias]

**复现步骤**
[复现问题的步骤]
文件 config/index.js:

const config = {
     alias: {
       '@/pages': 'src/pages'
     },
}

文件src/pages/taro/index.js:

export default class Index extends Component {
  config = {
    usingComponents: {
      test: '@/pages/taro/test/test'
    }
  }

  render() {
     return (<View> ... </View> )
  }
}

报错：
 Error: ENOENT: no such file or directory, lstat 'src/pages/taro/index.json'
index.json中usingComponents路径没有解析
期望index.json中usingComponents路径被解析为绝对路径，

**Comment by jonahfang** [comment]
这个问题为何关闭呢？是已经解决还是没有解决？

**Comment by jonahfang** [comment]
@xiaomingplus 我也遇到这个问题。

**Comment by jonahfang** [comment]
@xuanmiaoshuo 我也遇到这个问题。
