### ISSUE TITLE
npm run build:weapp 编译问题

### ISSUE THREAD

**Issue by wang89jun** [NervJS/taro#2673]
**问题描述**
[问题描述：npm run build编译时也未报错，编译成功后上传小程序的时候，有时候会出现某个.wxss没有，再次编译上传有可能又是少了另一个，有时候又都是好的, taro build --type weapp --watch编译基本没问题的 ]

**复现步骤**
[复现问题的步骤]
随机的没办法复现

**Comment by luckyadam** [comment]
@wang89jun 样式文件要在 js 里引用

**Comment by wang89jun** [comment]
都是引用在各自对应的js里，不然样式都不会显示的
