### ISSUE TITLE
与原生代码混合使用时，没有 copy 引用的图片到 dist 目录

### ISSUE THREAD

**Issue by jo32** [NervJS/taro#2674]
**问题描述**

像如下引用图片时，没有自动 copy 图片到 dist 目录：

```
<view class='nonet'>
    <image class='nonet__logo' mode='scaleToFill' src="../../images/nonetwork.png" />
    <view class='nonet__title'>网络异常</view>
    <view class='nonet__btn'>重新加载</view>
</view>
```

**复现步骤**
1. 见描述

**期望行为**
copy 到 dist 目录

**环境**
 - 操作系统: Mac OS
 - Taro 版本: 0.2.17

**Comment by luckyadam** [comment]
暂时是没有解析 wxml 里的图片引用，可以通过配置 [copy](https://nervjs.github.io/taro/docs/config-detail.html#copy)，copy 到 dist
