### ISSUE TITLE
按照多端组件命名规则创建xxx.js和xxx.rn.js，微信小程序中编译生成的是xxx.rn.js而不是xxx.js；rn编译生成xxx.rn.js和xxx.js

### ISSUE THREAD

**Issue by gzqreder** [NervJS/taro#2680]
**问题描述**
根据官方文档跨平台开发部分：https://nervjs.github.io/taro/docs/envs.html
按照多端组件命名规则创建xxx.js和xxx.rn.js。
微信小程序中编译生成的是xxx.rn.js而不是xxx.js，xxx.rn.js中如果引入rn特有的模块会报错
rn编译生成xxx.rn.js和xxx.js，使用能够正确引用xxx.rn.js

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
能够正确引用期望的文件，小程序引用xxx.js，rn引用xxx.rn.js

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [mac]
 - Taro 版本 [1.2.22]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [rn, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
没有复现啊，可以提供一个 demo 么

**Comment by gzqreder** [comment]
taro cli是1.2.22，项目是1.2.21
Taro CLI 1.2.22 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.7.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.21 => 1.2.21 
      @tarojs/mobx: 1.2.21 => 1.2.21 
      @tarojs/mobx-h5: 1.2.21 => 1.2.21 
      @tarojs/mobx-rn: 1.2.21 => 1.2.21 
      @tarojs/plugin-babel: 1.2.21 => 1.2.21 
      @tarojs/plugin-csso: 1.2.21 => 1.2.21 
      @tarojs/plugin-sass: ^1.2.22 => 1.2.22 
      @tarojs/plugin-uglifyjs: 1.2.21 => 1.2.21 
      @tarojs/rn-runner: 1.2.21 => 1.2.21 
      @tarojs/router: 1.2.21 => 1.2.21 
      @tarojs/taro: 1.2.21 => 1.2.21 
      @tarojs/taro-alipay: 1.2.21 => 1.2.21 
      @tarojs/taro-h5: 1.2.21 => 1.2.21 
      @tarojs/taro-swan: 1.2.21 => 1.2.21 
      @tarojs/taro-tt: 1.2.21 => 1.2.21 
      @tarojs/taro-weapp: 1.2.21 => 1.2.21 
      @tarojs/webpack-runner: 1.2.21 => 1.2.21 
      eslint-config-taro: 1.2.21 => 1.2.21 
      eslint-plugin-taro: 1.2.21 => 1.2.21 
      nervjs: ^1.3.9 => 1.3.13 
      stylelint-taro-rn: ^1.2.21 => 1.2.21 
    npmGlobalPackages:
      typescript: 3.4.1
由于1.2.22上rn有另外一个问题  https://github.com/NervJS/taro/issues/2626
项目没有升级
我创建一个全新的1.2.22的项目，小程序部分是能正确生成的

**Comment by luckyadam** [comment]
@gzqreder 那是 RN 端存在问题？

**Comment by Pines-Cheng** [comment]
贴一下代码和文件结构？

**Comment by gzqreder** [comment]
先关闭吧，cli升级到1.2.23后，rn和小程序都能正常生成了。如果再发现，我再提issue
