### ISSUE TITLE
styl 编译失败但退出码不为 1 , 导致后续的程序继续执行, 应该停在编译失败的命令上

### ISSUE THREAD

**Issue by shynome** [NervJS/taro#2682]
**问题描述**
styl  编译失败但退出码不为 1 , 导致后续的程序继续执行, 应该停在编译失败的命令上

**复现步骤**
[复现问题的步骤]
1. 新建 x.styl
2. 输入:
```styl
.xxxx
color: red;
```
3. 执行 npm run build:h5 && echo 'it not stop'

[或者可以直接贴源代码，能贴文字就不要截图]

```styl
.title
font-size: 28px;
```

**期望行为**
停在 styl 报错命令, 不继续执行下一条命令

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
```log
ParseError: index.styl:4:21
   3|     .title
   4|     font-size: 28px;
--------------------------^
   5|     .order_goods_item
   6|         width: 100%;
   7|         display: flex;

expected "indent", got ";"

it not stop
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10 和 linux 
 - Taro 版本 1.2.13
 - Node.js 版本 10.13.0
 - 报错平台 h5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

不报错的话, dist 文件夹下会有下列文件:
```
./
./lib/
./lib/lib.dll.js
./lib/lib-manifest.json
```
然后 CI/CD 直接把这些文件发布到了服务器上, 导致了 h5 页面报错

**Comment by shynome** [comment]
这个 bug 在修了吗

**Comment by Littly** [comment]
> 这个 bug 有人在修了吗

有

**Comment by shynome** [comment]
话说修好了吗 ? 没修好的话我想修
