### ISSUE TITLE
微信小程序编译成taro，微信小程序组件被忽略

### ISSUE THREAD

**Issue by gu-xiaohui** [NervJS/taro#2685]
使用taro convert反编译微信小程序组件，微信小程序组件被忽略
taro版本 1.2.20

**Comment by gu-xiaohui** [comment]
更正一下，是在app.json全局引用的组件不被编译，局部页面引用的能被编译

**Comment by luckyadam** [comment]
原来如此，我们优化一下，可以够提供一个范例

**Comment by shenghanqin** [comment]
优化好了吗？ @luckyadam

**Comment by Chen-jj** [comment]
Duplicate of #4604
