### ISSUE TITLE
正常流程安装报错，安装内容包括：ts，redux模板。。。

### ISSUE THREAD

**Issue by fxqifuzhanglei** [NervJS/taro#269]
TS18002: The 'files' list in config file 'tsconfig.json' is empty.

**Comment by yuche** [comment]
Duplicate of #233

**Comment by yuche** [comment]
ts 现在的支持有问题，你去 #233 关注进展吧

**Comment by fxqifuzhanglei** [comment]
谢谢，后面看到了


------------------------------------------------------------------
发件人：Yu Che <notifications@github.com>
发送时间：2018年7月5日(星期四) 10:42
收件人：NervJS/taro <taro@noreply.github.com>
抄　送：张磊 <zhangl@fxqifu.com>; Author <author@noreply.github.com>
主　题：Re: [NervJS/taro] 正常流程安装报错，安装内容包括：ts，redux模板。。。 (#269)

Closed #269.
