### ISSUE TITLE
传函数给子组件不用on开头就无法使用？

### ISSUE THREAD

**Issue by Rychou** [NervJS/taro#2694]
这种情况终端没有任何警告或者错误提示，找了一晚上原因，居然是因为这个。

希望改善的地方是：
1. 在终端输出提示
2. 传递函数不要强制用`on`, 只是提示用法的规范。

如果是父组件传给子组件的函数是用于修改父组件的`state`, 我可以命名为`updateSomeState`,使用时直接`this.props.updateSomeState()`就可以了。

如果按照`Taro`的规范，用`on`开头，函数名类似这样，`onSomeStateUpdate`，使用时就是`this.props.onSomeStateUpdate`，看着怪别扭的。

**Comment by yuche** [comment]
如果你装好了 eslint 是会有提示的
