### ISSUE TITLE
微信和支付宝event handler 传递参数不一致

### ISSUE THREAD

**Issue by cgxqd123** [NervJS/taro#2696]
**微信和支付宝event handler 传递参数不一致**
**支付宝**
![image](https://user-images.githubusercontent.com/36787884/55704433-a40f0300-5a0e-11e9-806b-1bbb73a6c63d.png)
**微信**
![image](https://user-images.githubusercontent.com/36787884/55704470-b9842d00-5a0e-11e9-891c-0f820cdfab15.png)

```js
onTabBarClick(e,current){
        /*目前条件判断解决*/
        if(process.env.TARO_ENV === 'weapp')
            this.setState({current})
        else if(process.env.TARO_ENV === 'alipay')
            this.setState({current:e})
        console.log(e,current)
    }
    render() {
        let { current,tabBar } = this.state;
        return (
            <View>
                <CTabBar current={current}
                         tabBar={tabBar}
                         onClick={this.onTabBarClick.bind(this)}
                ></CTabBar>
            </View>
        )
    }

```

**期望行为**
```js
// 你可以通过 bind 传入多个参数
  preventPop (name, test, e) {    //事件对象 e 要放在最后

  }

  render () {
    return <Button onClick={this.preventPop.bind(this, this.state.name, 'test')}></Button>
  }
```
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将
![image](https://user-images.githubusercontent.com/36787884/55704495-d02a8400-5a0e-11e9-83db-c8bbae84a45c.png)

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@cgxqd123 子组件调用传入函数的代码也提供一下
