### ISSUE TITLE
字节跳动 组件的state改变后 props会变成初始值 

### ISSUE THREAD

**Issue by qq287757491** [NervJS/taro#2697]
**问题描述**

编译成字节跳动小程序后  组件的state改变后 props会变成初始值   
同时 props 改变时 componentWillReceiveProps 等生命周期不执行  

**复现步骤**    

![c8e70368436086ab08d5449a974ddbe5](https://user-images.githubusercontent.com/13093439/55707006-24386700-5a15-11e9-8cf7-e64c2758332d.GIF)  

page

```
import Taro, {Component} from '@tarojs/taro'
import {View, Button} from '@tarojs/components'
import './index.less'
import InputCom from '../../components/input'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  constructor(props) {
    super(props)
    this.state = {
      cityName: '杭州市'
    }
  }

  componentWillMount() {

    // let iva = setInterval(() => {
    //   console.log('page state====>>>>>>')
    //   console.log(this.state)
    // }, 1000)

  }

  changeCityName() {
    this.setState({
      cityName: '北京市'
    }, () => {
      console.log('page state====>>>>>>')
      console.log(this.state)
    })
  }

  render() {

    const {cityName} = this.state;


    return (
      <View className='index'>
        <InputCom cityName={cityName} onChangeCityName={this.changeCityName}/>
      </View>
    )
  }
}


```
components
```
import Taro, {Component} from '@tarojs/taro'
import {View, Text, Input, Button} from '@tarojs/components'
import './index.less'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  constructor(props) {
    super(props)
    this.state = {
      value: ''
    }
  }

  changeParams(e) {
    this.setState({
      value: e.detail.value
    }, () => {
      // console.log(this.state)
    })
  }

  render() {

    const {value} = this.state

    const {onChangeCityName, cityName} = this.props;

    console.log('com props===>>>')

    console.log(this.props)

    return (
      <View className='index'>
        <Text>{cityName}</Text>
        <Input placeholder='placeholder' value={value} onInput={this.changeParams}/>
        <Button onClick={onChangeCityName}>点这改变父组件state</Button>
      </View>
    )
  }
}


```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [tt]

👽 Taro v1.2.23  
  Taro CLI 1.2.23 environment info:  
    System:  
      OS: macOS 10.14  
      Shell: 3.2.57 - /bin/bash  
    Binaries:  
      Node: 11.12.0 - /usr/local/bin/node  
      Yarn: 1.13.0 - /usr/local/bin/yarn  
      npm: 6.9.0 - /usr/local/bin/npm  
    npmPackages:  
      @tarojs/components: 1.2.23 => 1.2.23   
      @tarojs/plugin-babel: 1.2.23 => 1.2.23   
      @tarojs/plugin-csso: 1.2.23 => 1.2.23   
      @tarojs/plugin-less: 1.2.23 => 1.2.23   
      @tarojs/plugin-uglifyjs: 1.2.23 => 1.2.23   
      @tarojs/router: 1.2.23 => 1.2.23   
      @tarojs/taro: 1.2.23 => 1.2.23   
      @tarojs/taro-alipay: 1.2.23 => 1.2.23   
      @tarojs/taro-h5: 1.2.23 => 1.2.23   
      @tarojs/taro-swan: 1.2.23 => 1.2.23   
      @tarojs/taro-tt: 1.2.23 => 1.2.23   
      @tarojs/taro-weapp: 1.2.23 => 1.2.23   
      @tarojs/webpack-runner: 1.2.23 => 1.2.23   
      eslint-config-taro: 1.2.23 => 1.2.23   
      eslint-plugin-taro: 1.2.23 => 1.2.23   
      nervjs: ^1.3.9 => 1.3.13   

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@qq287757491 复现不了，更新到 Taro v1.2.27-beta.0 后再试试
