### ISSUE TITLE
页面编译后实时更新出现TypeError: Super expression must either be null or a function，注明第一次的时候是正常的，重新编译后也是正常的就是刷新就出现问题了

### ISSUE THREAD

**Issue by curryhh** [NervJS/taro#2704]
报错信息
![20190408225233](https://user-images.githubusercontent.com/22719549/55734288-dc840080-5a51-11e9-8b46-b67f0340e3a3.png)
![20190408225240](https://user-images.githubusercontent.com/22719549/55734307-e6a5ff00-5a51-11e9-8cdf-03a47cb1bf4f.png)

**Comment by curryhh** [comment]
报错信息
![20190408225233](https://user-images.githubusercontent.com/22719549/55734165-a6df1780-5a51-11e9-89f2-808303e2dcdf.png)
![20190408225240](https://user-images.githubusercontent.com/22719549/55734196-b78f8d80-5a51-11e9-8542-eaed2c1e1462.png)

**Comment by beimuaihui** [comment]
我的h5页面修改后也经常出现这个问题

**Comment by curryhh** [comment]
> 我的h5页面修改后也经常出现这个问题

对对对  我都是实时编译h5的时候发现的，你有没有什么解决的方式？

**Comment by curryhh** [comment]
@beimuaihui 对对  我也是h5的时候发现的，你有没有解决方式

**Comment by SpinachMiss** [comment]
H5 很严格，你没有 export default

**Comment by curryhh** [comment]
@SpinachMiss 
应该不是的  1.生成没问题的，刷新之后才会有问题2.我有注意export default 跟import，如果我没这个的话taro生成的时候是有问题的直接报错在控制台的

**Comment by Littly** [comment]
看这个报错日志，应该是页面文件缺少default导出导致的

**Comment by SpinachMiss** [comment]
@curryhh  https://stackoverflow.com/questions/35777991/typeerror-super-expression-must-be-null-or-a-function-not-undefined-with-babel/35778089

**Comment by SeptemberMaples** [comment]
我刚刚更新taro也出现同样错误。  发现是taro-ui没有更新，更新到最新版，并根据文档引入.scss文件。解决了

**Comment by curryhh** [comment]
> 我刚刚更新taro也出现同样错误。 发现是taro-ui没有更新，更新到最新版，并根据文档引入.scss文件。解决了

谢谢了   我有时候出现那个问题而已，项目已经结束了

**Comment by kenphil** [comment]
> 看这个报错日志，应该是页面文件缺少default导出导致的。在taro的路由处理中，default导出是必需品
> 
> https://github.com/NervJS/taro/blob/d4e3ef54289620f281615256a6f3e7dc0b8f5a24/packages/taro-router/src/router/route.tsx#L67-L74

我也出现了这个问题，但是组件导出都有default，除了一些utils

**Comment by useryechen** [comment]
请问楼主这个问题是怎么解决的，我也是出现这个问题了，而且我确定代码没有问题
![image](https://user-images.githubusercontent.com/16095736/61436020-753ced00-a96c-11e9-8a82-4ff5ec2bf1e4.png)

**Comment by LeleCao** [comment]
我也出现这个问题了,h5页面，有人知道怎么解决吗，taro兼容性也太弱了，开源了让我们做小白鼠吗

**Comment by Littly** [comment]
没有复现，麻烦提供可以稳定复现的仓库吧。

**Comment by curryhh** [comment]
> 没有复现，麻烦提供可以稳定复现的仓库吧。

你好，https://github.com/curryhh/taro-douban这个项目就是，编译h5后是正常的，但是一改动之后就出问题了

**Comment by useryechen** [comment]
是经常会出现这个问题，但是我重新ctrl+s保存下   浏览器自动刷新一下  又自己好了

**Comment by Littly** [comment]
> > 没有复现，麻烦提供可以稳定复现的仓库吧。
> 
> 你好，[curryhh/taro-douban](https://github.com/curryhh/taro-douban) 这个项目就是，编译h5后是正常的，但是一改动之后就出问题了

ok 我试下

**Comment by beimuaihui** [comment]
ubuntu + taro1.3.25 + redux ;
我的估计是编译后显示编译成功，但在temp目录下面编译后的文件内容为空，我现在是每次都要多点几次保存，才能确保存编译生成文件有内容

**Comment by lukeymyuan** [comment]
我也有这个问题， h5 有人有解答吗

**Comment by lzd358194530** [comment]
今天刚创建的项目 发现这个问题 哪里有解决了

**Comment by younthu** [comment]
我也遇到过这种问题。2.2.11升级到3.0.

我把`import {Component} from @taro/components` 改成 `import {Component} from react`, 这个问题就消失了。
