### ISSUE TITLE
typescript: Taro.request的返回类型与interceptor冲突

### ISSUE THREAD

**Issue by yuquanwang** [NervJS/taro#2707]
**问题描述**
Taro.request返回类型的结构固定为{ data, statusCode, header }，使用interceptor进行response解析，将使得返回类型不可用，应该如何在这种情况下正确使用？

**复现步骤**

```js
// utils/interceptors.ts
import { Chain } from "@tarojs/taro";

export function parseInterceptor(chain: Chain) {
  const requestParams = chain.requestParams
  return chain.proceed(requestParams)
    .then(res => {
      return res.data
    })
}
```

```js
// app.tsx
import {parseInterceptor } from './utils/interceptors'

...

Taro.addInterceptor(Taro.interceptors.logInterceptor)
Taro.addInterceptor(parseInterceptor)
Taro.addInterceptor(Taro.interceptors.timeoutInterceptor)

...

```

```js
// problem.js
import Taro from '@tarojs/taro'

...

async function getHistoricOrders(){
    // 这里报错
    const { orders } = await Taro.request<ResDTO<UserOrder[]>, any>({
      url: 'http://www.urlpath.com/api/user/orders',
      method: 'GET',
    })
    return orders
}

class UserOrder {
  drug: UserDrug
}

interface ResDTO<T> {
  orders: T
}


...

```

**期望行为**
使用interceptor对response解析后可以直接获取解析后的数据

**报错信息**

![image](https://user-images.githubusercontent.com/16618169/55772905-e85adb80-5ac0-11e9-859f-5d7c224e682d.png)

**系统信息**
  Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
    npmPackages:
      @tarojs/async-await: 1.2.17 => 1.2.17 
      @tarojs/components: 1.2.17 => 1.2.17 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-sass: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/redux: 1.2.17 => 1.2.17 
      @tarojs/redux-h5: 1.2.17 => 1.2.17 
      @tarojs/router: 1.2.17 => 1.2.17 
      @tarojs/taro: 1.2.17 => 1.2.17 
      @tarojs/taro-alipay: 1.2.17 => 1.2.17 
      @tarojs/taro-h5: 1.2.17 => 1.2.17 
      @tarojs/taro-swan: 1.2.17 => 1.2.17 
      @tarojs/taro-tt: 1.2.17 => 1.2.17 
      @tarojs/taro-weapp: 1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.9 => 1.3.12

**Comment by yuche** [comment]
你可以重新写一个函数返回 Taro.request，但是这个函数的类型和签名是你通过 Interceptor 返回的。

**Comment by yuquanwang** [comment]
not a perfect solution

**Comment by wangchun0020** [comment]
![image](https://user-images.githubusercontent.com/8032943/108581269-96946500-7369-11eb-8131-a9c834c74eb5.png)
这么写是否合适？

**Comment by vv13** [comment]
对数据的转换的操作可以不放在interceptor里进行，借由一个转换函数：
```
 function requestHelper <T = any, U = any>(option: request.Option<U>) {
  return request<T, U>(option).then((res) => res.data);
}

const { token } = requestHelper<{token: string}>(config);
```

这样在使用 TypeScript 的时候，就不会有类型错误了。

**Comment by imnot2** [comment]
有最佳实践么？

**Comment by imnot2** [comment]
有最佳实践吗？
