### ISSUE TITLE
H5模式下页面跳转与回退后页面出现重叠

### ISSUE THREAD

**Issue by szhangbiao** [NervJS/taro#2710]
**问题描述**
[问题描述：H5模式下页面跳转与回退后页面出现重叠]

**复现步骤**
[复现问题的步骤]
1. 从A页面跳转到B页面
2. 从B页面跳转到C页面
3.在C页面调用Taro.navigateBack并发出一个全局事件
4.B页面收到全局事件调用Taro.navigateBack回到A页面
5.这时无论是打开其他页面（不包含B）还是切换tab，都出现页面异常
6.如果是正常的使用浏览器的回退则不会出现这种情况

[源代码]
[YunCai-WxPublic.zip](https://github.com/NervJS/taro/files/3058049/YunCai-WxPublic.zip)
重现步骤-选择省份
![WX20190409-170925](https://user-images.githubusercontent.com/10734139/55788643-456b8700-5aeb-11e9-85af-6d03c416313f.png)

**期望行为**
期望页面不要错乱

**报错信息**

没有报错

**系统信息**
> Taro v1.2.23 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
<img width="535" alt="WX20190409-170538@2x" src="https://user-images.githubusercontent.com/10734139/55787849-c9247400-5ae9-11e9-9ab2-7b14959bac78.png">

 - 操作系统: [e.g. mac 10.14.4]
 - Taro 版本 [e.g. v.1.2.23]
 - Node.js 版本 [e.g. v11.5.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[我猜测组件应该是重建了，但是跟老的组件同时存在A页面了？]

**Comment by szhangbiao** [comment]
目前我在C页面调用Taro.navigateBack({ delta: 2})，移除B页面Taro.navigateBack的逻辑，然后就正常了。可以在与我使用Taro.navigateBack的方式不正确造成的

**Comment by szhangbiao** [comment]
H5模式 在build后(Android手机)页面顺序A ->B -> C,按返回键返回到A页面，C页面在A页面的下面，页面发生重叠，iOS没发现这个问题

**Comment by Littly** [comment]
加个vconsole之类的看看控制台输出 这种应该是有脚本报错了

**Comment by szhangbiao** [comment]
现在去验证下又好了，下次再出现的时候我注意下控制台的输出

**Comment by Littly** [comment]
ok 那先关闭了，碰到再reopen
