### ISSUE TITLE
weapp端的refs的问题

### ISSUE THREAD

**Issue by Rychou** [NervJS/taro#2711]
**问题描述**
在微信小程序端，对通过`ref`获取到的原生组件实例，调用`boundingClientRect`方法，在其回调函数中存在重复调用的问题。

**复现步骤**

![](https://ws3.sinaimg.cn/large/005BYqpgly1g1wljuyyw6g30l60d3wh7.jpg)

```js
class Test extends Component {
  handleClick() {
    this.refs.test
      .boundingClientRect(res => {
        console.log('test1'); // 第n次点击Button，该回调就会在第n次点击时执行n次。
      })
      .exec(res => {
        console.log('test2');
      });
  }
  render() {
    return (
      <View id='test' ref='test'>
        <Button onClick={this.handleClick}>Click Here</Button>
      </View>
    );
  }
}
```

不管是字符串`refs`还是函数`refs`都存在此问题。

不过通过`Taro.createSelectorQuery()`获取的原生实例就不存在重复调用的情况

**系统信息**

Taro CLI 1.2.23 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@Rychou 这种情况用 `Taro.createSelectorQuery()`

ref 对应同一个 query 对象，而你每次调用 `Taro.createSelectorQuery()` 都返回一个新的 query。微信小程序的机制，同一个 query 对象的查询方法调用是会叠加的。

这里使用 ref 相当于：

```js
const test = wx.createSelectorQuery().in(this.$scope).select('#test')
test.boundingClientRect(res => console.log('res: ', res))
  .exec(resList => console.log('exec: ', resList))
test.boundingClientRect(res => console.log('res: ', res))
  .exec(resList => console.log('exec: ', resList))
```

![image](https://user-images.githubusercontent.com/11807297/55846086-04b94f80-5b77-11e9-9c37-77d7bf0374d4.png)

**Comment by Rychou** [comment]
> @Rychou 这种情况用 `Taro.createSelectorQuery()`
> 
> ref 对应同一个 query 对象，而你每次调用 `Taro.createSelectorQuery()` 都返回一个新的 query。微信小程序的机制，同一个 query 对象的查询方法调用是会叠加的。
> 
> 这里使用 ref 相当于：
> 
> ```js
> const test = wx.createSelectorQuery().in(this.$scope).select('#test')
> test.boundingClientRect(res => console.log('res: ', res))
>   .exec(resList => console.log('exec: ', resList))
> test.boundingClientRect(res => console.log('res: ', res))
>   .exec(resList => console.log('exec: ', resList))
> ```
> 
> ![image](https://user-images.githubusercontent.com/11807297/55846086-04b94f80-5b77-11e9-9c37-77d7bf0374d4.png)

没看懂，是每次通过`refs`调用`boundingClientRect`会通过`Taro.createSelectorQuery()`创建一个新的query对象吗？

**Comment by Chen-jj** [comment]
@Rychou 文字和例子说得很清晰了，再斟酌一下吧。
