### ISSUE TITLE
rn下不支持showLoading

### ISSUE THREAD

**Issue by leopard7777777** [NervJS/taro#2715]
**问题描述**
rn下不支持showLoading

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/11750796/55820277-4e7d4800-5b2d-11e9-87fe-81f383dc0ca9.png)

[或者可以直接贴源代码，能贴文字就不要截图]

```js
const get = (url, data, header = {}) => {
  return Taro.showLoading({
    title: '加载中...'
  }).then(() => {
    return Taro.request({url, data, header, method: 'GET'}).then(res => {
      if (res.statusCode != 200) {
        return Promise.reject(_.get(res, 'data', {}));
      } else {
        return _.get(res, 'data', {});
      }
    });
  }).then(res => {
    Taro.hideLoading();
    return res;
  });
};


```

**期望行为**

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
👽 Taro v1.2.23

  Taro CLI 1.2.23 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\Admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
Taro.showLoading 又不是 Promise 。。。
