### ISSUE TITLE
Taro.request promise调用在catch中无法获取http状态码

### ISSUE THREAD

**Issue by MikyChow** [NervJS/taro#2717]
**问题描述**
使用taro.request当服务器返回http401时，catch中的err为SyntaxError: Unexpected end of JSON input
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
http请求失败时将http的错误吃掉了、依然去json反序列化http 401 导致错误

**Comment by luckyadam** [comment]
一般判断错误信息即可吧，你的代码里需要用到这样的错误状态码么

**Comment by MikyChow** [comment]
额，获取http状态码应该是一个比较正常的功能吧。很多api都是遵循http的状态码来判定状态的。比如未授权就是401，但是http的body中没有内容。

**Comment by luckyadam** [comment]
我们看下
