### ISSUE TITLE
a error problem

### ISSUE THREAD

**Issue by wkh2** [NervJS/taro#272]
你好。我执行npm run dev:h5的时候报错了，如下的错误
 ERROR
      TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["__tests__","node_modules","dist","tests","jest","lib","**/*.test.ts","**/*.spec.ts"]'.

**Comment by luckyadam** [comment]
你好，目前 H5 端对 TS 的支持有点问题，如果你不用 TS 开发的话，创建项目时询问是否使用 TypeScript 选择 false 吧

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/490e7cb36ca9b3ad9f80c4475d6c023e87b6561a

装最新的版本 0.0.69 应该就能解决了
