### ISSUE TITLE
微信内小图片没有转base64码

### ISSUE THREAD

**Issue by suptwo** [NervJS/taro#2722]
**问题描述**
按照官网示例 
(https://nervjs.github.io/taro/docs/static-reference.html#%E5%BC%95%E7%94%A8%E5%9B%BE%E7%89%87-%E9%9F%B3%E9%A2%91-%E5%AD%97%E4%BD%93%E7%AD%89%E6%96%87%E4%BB%B6)[https://nervjs.github.io/taro/docs/static-reference.html#%E5%BC%95%E7%94%A8%E5%9B%BE%E7%89%87-%E9%9F%B3%E9%A2%91-%E5%AD%97%E4%BD%93%E7%AD%89%E6%96%87%E4%BB%B6]

2-3K的小图片并未转为base64码

**复现步骤**
[复现问题的步骤]

```js
import czy from './assets/czy.png';
```
```
<Image src={czy} />
```
![image](https://user-images.githubusercontent.com/12033906/55865868-cb520580-5bb1-11e9-9e30-2cbbc24f9cf3.png)
![image](https://user-images.githubusercontent.com/12033906/55865944-efade200-5bb1-11e9-8e42-450a8a77d26f.png)

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/55867411-01dd4f80-5bb5-11e9-897d-e37d7a0da602.png)

**Comment by suptwo** [comment]
@luckyadam  你贴的图对我的问题没有帮助， 文档我看过并且贴出来了。 但也谢谢的帮助
![image](https://user-images.githubusercontent.com/12033906/55926008-32b79600-5c42-11e9-906b-78cd9bea9e36.png)

**Comment by luckyadam** [comment]
@suptwo 你还是没看清楚我的图么，文档里的写的是样式才会转 base64 ，你在模板里面引用，为什么还需要转 base64 ？除了增大代码体积，没有任何价值

**Comment by suptwo** [comment]
@luckyadam 明白你文档截图的意思 但是官网文档 是这样写的 意义何在呢。 
我这个icon是循环出来的，想直接用不然需要写很多class实现
![image](https://user-images.githubusercontent.com/12033906/55926419-ce95d180-5c43-11e9-87e1-820bd2cf539b.png)

**Comment by luckyadam** [comment]
@suptwo 因为需要识别到图片资源的引用
