### ISSUE TITLE
app支持动态配置tabBar

### ISSUE THREAD

**Issue by juanjiejie** [NervJS/taro#2723]
我们是第三方小程序，不同店铺的话tabbar显示的不一样，小程序用ext解决了此问题，但是h5不支持，能不能tabbar 配置以后h5不显示，只有微信小程序显示；
可以用自定义tabbar去解决此问题，但是小程序会把所有tabbar组件编译到一个文件里面，这样小程序会比较卡。
所以希望某些平台可以设置不显示默认的tabbar，去自定义

**Comment by luckyadam** [comment]
我们研究下

**Comment by wang777777** [comment]
ext 是啥，在小程序里能具体说说怎么解决的不

**Comment by juanjiejie** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/ext.html?search-key=ext.json
这个文档里有说第三方平台时ext.json文件；我们现在解决办法是服务器发版时附带的json信息

**Comment by BinZhiZhu** [comment]
Taro.setTabBarItem 现在在h5 会 报错 setTabBarItem:fail tabbar item not found ，请问下是啥问题，小程序可以自定义成功

**Comment by xiaozhouwu** [comment]
h5的setTabBarItem有问题🤨

**Comment by shenghanqin** [comment]
可以看一下 #2872 的答复

**Comment by Chen-jj** [comment]
Taro 3 支持配置文件写逻辑了：

const obj = {
  pages: [
    'pages/index/index',
    'pages/my/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}

if (process.env.TARO_ENV === 'weapp') {
  obj['tabBar'] = {
    list: [
      {
        pagePath: "pages/index/index",
        text: "首页"
      },
      {
        pagePath: "pages/my/index",
        text: "日志"
      }
    ]
  }
}


export default obj

**Comment by singagain** [comment]
> Taro.setTabBarItem 现在在h5 会 报错 setTabBarItem:fail tabbar item not found ，请问下是啥问题，小程序可以自定义成功

你解决了吗？我也遇到这个问题

**Comment by daiyuanhao** [comment]
> > Taro.setTabBarItem 现在在h5 会 报错 setTabBarItem:fail tabbar item not found ，请问下是啥问题，小程序可以自定义成功
> 
> 你解决了吗？我也遇到这个问题

你解决了吗
