### ISSUE TITLE
rn下不支持swiper

### ISSUE THREAD

**Issue by leopard7777777** [NervJS/taro#2724]
**问题描述**
rn下不支持swiper，h5下正常

**复现步骤**
![image](https://user-images.githubusercontent.com/11750796/55879802-07955e00-5bd2-11e9-8149-2caae79391a8.png)

![image](https://user-images.githubusercontent.com/11750796/55879739-e6347200-5bd1-11e9-8312-ff59b7dca3ad.png)

[或者可以直接贴源代码，能贴文字就不要截图]

```js
<View className='index__swiper-box'>
          <Swiper autoplay interval={2000} circular>
            <SwiperItem>
              <Image src='http://img.3dmgame.com/uploads/images/news/20181124/1543042277_150670.jpg'></Image>
            </SwiperItem>
            <SwiperItem>
              <Image src='http://b.zol-img.com.cn/soft/5/847/ce8wO9xMfFGr2.jpg'></Image>
            </SwiperItem>
            <SwiperItem>
              <Image src='http://img8.zol.com.cn/bbs/upload/13484/13483443.jpg'></Image>
            </SwiperItem>
          </Swiper>
        </View>

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
👽 Taro v1.2.23

  Taro CLI 1.2.23 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\Admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Manjiz** [comment]
![Untitled](https://user-images.githubusercontent.com/13447336/56009779-9d84d200-5d13-11e9-820d-5f726c1b3b93.gif)
copy了你的代码，运行没问题，你再瞅瞅？
