### ISSUE TITLE
是不是现在taro不支持wx.chooseMessageFile

### ISSUE THREAD

**Issue by leecircle** [NervJS/taro#2726]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
Taro是不是没有支持这个接口wx.chooseMessageFile

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
支持wx.chooseMessageFile可以上传聊天记录中附件

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac 10.4.2
 - Taro 版本 1.2.8
 - Node.js 版本 9.10.0
 - 报错平台 [weapp]

**补充信息**
[可选]
没有支持wx.chooseMessageFile

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/55924637-27ae3700-5c3d-11e9-9526-4b6480a6e7f3.png)
