### ISSUE TITLE
父子组件传值，对象健名断裂问题

### ISSUE THREAD

**Issue by carlsiry** [NervJS/taro#2727]
**问题描述**
父组件向子组件传递一个对象，对象的值是每次从redux 中获取的新对象，在父组件中与redux中的状态值一致，**但是到了子组件中对象健名被分割断裂成下陷成嵌套健值**。

并且奇怪的是，**奇数次值断裂下陷，偶数次复合无损**！所以视图层奇数次序时视图不符合预期，偶次序时视图符合预期。

**复现步骤**

```js
// redux 中定义的状态选择
export const getPicksByProduct = state => {
  const { picks } = state.entities;
  const { picksByProduct } = state.order;
  return Object.keys(picksByProduct).reduce(
    (r, k) => ({ ...r, [k]: picksByProduct[k].map(id => picks[id]) }),
    {}
  );
};

// 父组件从 redux 连接中获取值
const mapStateToProps = state => ({
  channelID: getChannelID(state),
  tableNum: getTableNum(state),
  dinnerID: getDinnerID(state),
  userID: getUserID(state),
  tableMsgID: getTableMsgID(state),
  categories: getCategories(state),
  selectedCategory: getSelectedCategory(state),
  currentNavIndex: getCurrentNavIndex(state),
  error: getError(state),
  selectedProduct: getSelectedProduct(state),
  selectedAttrs: getSelectedAttrs(state),
  products: getProductsByCategory(state),
  picks: getPicksByProduct(state)
});

@connect(
  mapStateToProps,
  dispatch => ({
    appActions: bindActionCreators(appActions, dispatch),
    orderActions: bindActionCreators(orderActions, dispatch)
  })
)
class Menu extends Component 

 // 父组件中往子组件中传递
  render() {
    const { picks /* ...*/ } = this.props;
    if (error) {
      Taro.showToast({ title: error });
      this.timeout = setTimeout(appActions.clearError, 2000);
    }
    console.log("father picks: ", picks);
    return (
       <ProductList picks={picks} /*...*/  />
     )
}

// 子组件中获取父组件的值
class ProductList extends Taro.Component {
  render() {
    const { products, picks, cateID } = this.props;
    const listProduct = products[cateID] || {};
    console.log("第 " + this.props.index + " 类商品列表更新！");
    console.log(picks);
    return ( <ScrollView scrollY>  ）
```

**期望行为**
父组件通讯能传递一致的值，以达到视图符合预期的呈现！

**报错信息**
<img width="750" alt="屏幕快照 2019-04-11 上午10 59 31" src="https://user-images.githubusercontent.com/21176698/55927932-73ff7400-5c49-11e9-8444-4a66e3f6889c.png">

**系统信息**
>
👽 Taro v1.2.24

  Taro CLI 1.2.24 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.24 => 1.2.24
      @tarojs/components: 1.2.24 => 1.2.24
      @tarojs/plugin-babel: 1.2.24 => 1.2.24
      @tarojs/plugin-csso: 1.2.24 => 1.2.24
      @tarojs/plugin-sass: 1.2.24 => 1.2.24
      @tarojs/plugin-uglifyjs: 1.2.24 => 1.2.24
      @tarojs/redux: 1.2.24 => 1.2.24
      @tarojs/redux-h5: 1.2.24 => 1.2.24
      @tarojs/router: 1.2.24 => 1.2.24
      @tarojs/taro: 1.2.24 => 1.2.24
      @tarojs/taro-alipay: 1.2.24 => 1.2.24
      @tarojs/taro-h5: 1.2.24 => 1.2.24
      @tarojs/taro-swan: 1.2.24 => 1.2.24
      @tarojs/taro-tt: 1.2.24 => 1.2.24
      @tarojs/taro-weapp: 1.2.24 => 1.2.24
      @tarojs/webpack-runner: 1.2.24 => 1.2.24
      eslint-config-taro: 1.2.24 => 1.2.24
      eslint-plugin-taro: 1.2.24 => 1.2.24
      nervjs: ^1.3.9 => 1.3.13
      react: ^16.8.5 => 16.8.5
    npmGlobalPackages:
      typescript: 2.8.1
 - 报错平台 weapp

**Comment by carlsiry** [comment]
已经确定是编译器的问题，当把健名中的**点号**改成**双冒号**时便能正常传递到子组件中，希望官方能改进此处！

**Comment by Chen-jj** [comment]
@carlsiry 复现不了，你可以先查一下真正 setData 的值附上来：[debug 指南](https://nervjs.github.io/taro/docs/debug.html#%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%8A%A5%E9%94%99-%E4%BD%86%E6%98%BE%E7%A4%BA%E7%9A%84%E7%BB%93%E6%9E%9C%E4%B8%8D%E5%A6%82%E9%A2%84%E6%9C%9F)
