### ISSUE TITLE
component.$scope undefined

### ISSUE THREAD

**Issue by mqliutie** [NervJS/taro#2728]
**问题描述**

`dispatch`一个`action`的时候,`reducer`返回新值时报错

Cannot read property 'data' of undefined
    at doUpdate (http://127.0.0.1:25553/appservice/npm/@tarojs/taro-weapp/dist/index.js:3772:43)
    at updateComponent (

断点发现这句出错:

`component.$scope.data[privatePropKeyName]`

component.$scope  `undefined`

**复现步骤**

```js
import {GET_USER_INFO} from '../constants'

const initState = {
};

export default function userInfo (state = initState, action) {
    switch (action.type) {

    case GET_USER_INFO: {

       // 这样会报错,  如果直接返回state不会出错
        return {
            ...state, ...action.data
        }
    }

    default:
        return state
    }
}

```

**期望行为**
更新store, 视图更新

**报错信息**

![image](https://user-images.githubusercontent.com/11795518/55930055-289d9380-5c52-11e9-81ad-4b0c3dd7a5a7.png)

从控制台可以看到 `nextState` 值已经更改了, 不知道为什么component的$scope会是undefined

**系统信息**

 - 操作系统: [e.g. macos]
 - Taro 版本 [e.g. v1.7.0]
 - Node.js 版本 [e.g. v11.4.0]
 - 报错平台 [weapp]

**Comment by mqliutie** [comment]
问题原因 : 对App组件进行了 connect 操作,导致了这个问题

**Comment by pawoma** [comment]
我也出现了这个问题， App组件不可以connect ，你的应用场景是什么呢 ？

**Comment by mqliutie** [comment]
@pawoma 应该是判断用户是否登录了吧, 现在`app`的`didmount`里做, 然后想把数据放到`store`中

这样就需要`connect App`, 但是不允许`connect app`的, 所以我把数据存在`storage`中了
