### ISSUE TITLE
带tabBar页面跳转到非tabBar页面使用Taro.navigateBack()返回底部tab消失

### ISSUE THREAD

**Issue by claudlu** [NervJS/taro#273]
**问题描述**
带tabBar页面跳转到非tabBar页面使用Taro.navigateBack()返回时，地址栏地址没有返回，但是页面已经切回上一页，并且底部tabBar按钮消失，小程序正常，h5出现该问题

**复现步骤**
[复现问题的步骤]
群里提过问，官方说修复了，只是还没提交，提个issue收提示~~

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
使用navigateBack能正常返回并出现tabBar底部
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. v.0.0.67]
 - Node.js 版本 [e.g. v8.4.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
官方已回复，tabbar没显示的原因就是地址栏没有push state

**Comment by vimcaw** [comment]
Taro h5 也可以设置 Tabbar 吗？之前一直都是每个页面带个底栏，体验很不好。
