### ISSUE TITLE
Error calling AppRegistry.runApplication.Could not get BatchedBridge,make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by 1995hjh** [NervJS/taro#2730]
taro init 新初始化一个项目Demo，未做任何改动，taro-native-shell拉取之后进入根目录npm install之后，按照官网说明的运行方法，通过npm run dev:rn成功开启项目，在使用android studio打开taro-native-shell项目下的android目录，编译之后运行在真实的安卓手机上，出现如下红屏错误：

```
Error calling AppRegistry.runApplication.Could not get BatchedBridge,make sure your bundle is packaged correctly
```

**复现步骤**
1. taro init Demo
2. 从git上拉取项目taro-native-shell之后，进入项目npm install
3. 进入Demo项目，npm run dev:rn, 项目启动成功
4. 打开android-studio工具，打开taro-native-shell项目下的android文件夹，连接手机，编译运行在真实的安卓手机上，出现上述问题。

**期望行为**
安装成功之后正常运行在安卓手机上

**报错信息**

![image](https://user-images.githubusercontent.com/12559428/55926855-89729f00-5c45-11e9-8888-3e02e2583351.png)

**系统信息**
![image](https://user-images.githubusercontent.com/12559428/55926927-cb034a00-5c45-11e9-9394-71cb89404a9e.png)

**手机信息**

型号：MIX2
Android版本： 8.0.0

**排查过的问题**
1、watchman watch-del-all，清除过缓存，没有解决；
2、 taro-native-shell\android\app\src\main\java\com\tarodemo\MainApplication.java下面的代码未做改动，如下：

```java
         @Override
         protected String getJSMainModuleName() {
               return "index";
         }
```

taro-native-shell\ios\taroDemo\AppDelegate.m下面的代码未做改动，如下：

```object-c
       - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
        NSURL *jsCodeLocation;
        jsCodeLocation = [[RCTBundleURLProvider sharedSettings] 
        jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
       ......
}
```

3、浏览器访问[http://127.0.0.1:8081/index.bundle?platform=android&dev=true]结果如下：

![image](https://user-images.githubusercontent.com/12559428/55927315-326dc980-5c47-11e9-955e-3bac50083008.png)

4、Metro Bundler 启动成功，如下图：

![image](https://user-images.githubusercontent.com/12559428/55927769-d6a44000-5c48-11e9-9e68-e5f1c0ec1c44.png)

5、taro-native-shell中rn的版本依赖：

 "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4"
  }

6、进入Demo项目，删掉node_modules包，重新 npm install，没有解决。

**Comment by Pines-Cheng** [comment]
不错，很详细的 issue ，有尝试过 iOS 端吗？

**Comment by 1995hjh** [comment]
不好意思，没有设备，没搞过

**Comment by Pines-Cheng** [comment]
https://github.com/facebook/react-native/issues/19019

**Comment by Pines-Cheng** [comment]
https://github.com/facebook/react-native/issues/12754

**Comment by luchanan** [comment]
所以集成环境，是怎么解决呢?
