### ISSUE TITLE
多重条件判断编译错误

### ISSUE THREAD

**Issue by 499070844** [NervJS/taro#2732]
**问题描述**
map中条件判断的编译错误

**复现步骤**

在map中出现if else

```jsx
render() {
    let showAddress: JSX.Element[] | JSX.Element;
    const { userAddress } = this.props;
    console.log(userAddress);
    if (userAddress.length !== 0) {
      showAddress = userAddress.map(v => {
        if (v.isDefault) {
          return <View>testtest</View>;
        } else return <View>nonono</View>;
      });
    } else {
      showAddress = <View>您暂未添加地址,请先点击新增地址</View>;
    }
    return (
      <View className="page">
        <View className="bigContainer">
          {showAddress}
          <Fab />
        </View>
      </View>
    );
  }

```

**报错信息**
![微信截图_20190411172244](https://user-images.githubusercontent.com/32221890/55945989-6e705100-5c7e-11e9-99ab-76e3ca169b9c.png)

**系统信息**
> Taro v1.2.24 

 Windows 10]

 - Node.js 版本 [e.g. v11.5.0]
 - 报错平台 [weapp]

###

**Comment by yuche** [comment]
先这样写吧：

```jsx
  render () {
    let showAddress: JSX.Element[] | JSX.Element;
    const { userAddress } = this.props;
    console.log(userAddress);
    if (userAddress.length !== 0) {
      showAddress = userAddress.map(v => {
        let el
        if (v.isDefault) {
          el = <View>testtest</View>;
        } else {
          el = <View>nonono</View>;
        }
        return <Block>{el}</Block>
      });
    } else {
      showAddress = <View>您暂未添加地址,请先点击新增地址</View>;
    }
    return (
      <View className="page">
        <View className="bigContainer">
          {showAddress}
          <Fab />
        </View>
      </View>
    );
  }
```

**Comment by 499070844** [comment]
> 先这样写吧：
> 
> ```js-jsx
>   render () {
>     let showAddress: JSX.Element[] | JSX.Element;
>     const { userAddress } = this.props;
>     console.log(userAddress);
>     if (userAddress.length !== 0) {
>       showAddress = userAddress.map(v => {
>         let el
>         if (v.isDefault) {
>           el = <View>testtest</View>;
>         } else {
>           el = <View>nonono</View>;
>         }
>         return <Block>{el}</Block>
>       });
>     } else {
>       showAddress = <View>您暂未添加地址,请先点击新增地址</View>;
>     }
>     return (
>       <View className="page">
>         <View className="bigContainer">
>           {showAddress}
>           <Fab />
>         </View>
>       </View>
>     );
>   }
> ```

![微信截图_20190411175151](https://user-images.githubusercontent.com/32221890/55948140-7b8f3f00-5c82-11e9-9c71-481718c221d1.png)
出现了新的错误

**Comment by yuche** [comment]
那你就先写三元表达式把，最上层的 if 和循环内的 if 有一个是三元表达式应该就可以

**Comment by zzg19901210** [comment]
const hotNews = this.state.data.hotNewsList.map((news) => {
      if (news.type == "2") {   /*资讯类型为文章*/
        if (news.styleType === "3") {   /* 展示类型为左字右图 */
          return (
            <View className='zxlist'>
              <View className='at-row' onClick={this.gotoInfoDetail}>
                <View className='at-col at-col-7 at-col--wrap'>
                  <View className='at-article__h3 title' style='margin:0;'>{news.title}</View>
                  <View className='at-article__info' style='margin:0;'>{news.writer} {news.pushTime} {news.likeNums}阅读</View>
                </View>
                <View className='at-col at-col-5'>
                  <Image style='height:90px;width:100%;' src={news.coverImgUrl}/>
                </View>
              </View>
            </View>
          )
        }else if (news.styleType === "2") {   /* 展示类型为上图下字 */
          return (
            <View className='zxlist' onClick={this.gotoInfoDetail}>
              <View className='at-article__h3 title' style='margin:0;'>{news.title}</View>
              <View className='at-row at-row__justify--between'>
                <View className='zx-img'>
                  <Image style='height:100px;width:100%;' src={banner}/>
                </View>
                <View className='zx-img'>
                  <Image style='height:100px;width:100%;' src={banner}/>
                </View>
                <View className='zx-img'>
                  <Image style='height:100px;width:100%;' src={banner}/>
                </View>
              </View>
              <View className='at-article__info' style='margin:0;'>体彩网 2019-08-09 30 阅读</View>
            </View>
          )
        }
      }
    }
