### ISSUE TITLE
继承Page报错：xxx is undefined

### ISSUE THREAD

**Issue by imageslr** [NervJS/taro#2733]
**问题描述**
希望创建两个一模一样的页面，因此使用其中一个页面继承另一个页面，但是编译后小程序内报错。报错信息是：BasePage is undefined.

**复现步骤**

```js
// index.jsx 这个页面是基类
import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";

export default class Cart extends Component {
  config = {
    navigationBarTitleText: "购物车"
  };

  state = {};

  componentWillMount() {}

  render() {
    return <View />;
  }
}
```

```js
// _index.jsx
import Taro, { Component } from "@tarojs/taro";
import Cart from "./index";

export default class Index extends Cart {}
```

**期望行为**
`/pages/_index.jsx`页面展示“购物车”页面内容

**报错信息**
thirdScriptError 
 sdk uncaught third Error 
 Cart is not defined 
 ReferenceError: Cart is not defined
    at http://127.0.0.1:23087/appservice/pages/cart/_index.js:49:3
    at require (http://127.0.0.1:23087/appservice/__dev__/WAService.js:1:1001939)
    at <anonymous>:293:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:23087/appservice/appservice?t=1554983910085:3055:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:23087/appservice/appservice?t=1554983910085:3067:20)

**系统信息**
👽 Taro v1.2.20

  Taro CLI 1.2.20 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/opt/node@8/bin/node
      Yarn: yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.18s. - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
    npmGlobalPackages:
      typescript: 3.3.3333

**附加信息**
也遇到过和#2511 一模一样的问题，同样不知道如何解决

#2511 中，开发者说可以继承Page，但是#2526 中说，render函数目前无法继承。请问哪个正确呢？

补充一下，我的需求是想做一个购物车页面，这个是个tabbar页面，在非tabbar页面中跳转过去的话页面栈就清空了。我希望像京东小程序那样，购物车可以是tabbar页面，也可以作为一个单独的页面。因此就想继承Page。不过现在遇到了这个问题。谢谢您解答。

**Comment by luckyadam** [comment]
这个问题看过了，是因为子类没有写 render 方法，所以导致报错，补上 render 方法即可

**Comment by luckyadam** [comment]
子类不要为空，至少有个 render 方法

**Comment by imageslr** [comment]
@luckyadam 子类补了render方法后确实可以通过运行了。但是我希望子类与父类有相同的页面结构，而调用`super.render()`就无法编译了。请问这个有什么解决方案吗？除了复制父类的render方法内容。

**Comment by imageslr** [comment]
@luckyadam  子类有render()方法后又无法通过了，还是报同样的`undefined`错误：

```js
// 基类
import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";

export default class Cart extends Component {
  config = {
    navigationBarTitleText: ""
  };

  state = {};

  componentWillMount() {}

  componentDidMount() {}

  render() {
    return <View>123</View>;
  }
}




// 子类
import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";
import Cart from "./index";

export default class CartPage extends Cart {
  componentWillMount() {}

  componentDidMount() {}

  render() {
    return <View>123</View>;
  }
}
```

**Comment by imageslr** [comment]
![image](https://user-images.githubusercontent.com/17822028/56010487-5815d400-5d16-11e9-884c-d8927c05be08.png)

**Comment by imageslr** [comment]
调试了一下发现，如果两个页面同时在`/app.js`的`pages`数组中时，就会报上图的错误：
![image](https://user-images.githubusercontent.com/17822028/56010588-ce1a3b00-5d16-11e9-9555-6b64a1e517f3.png)


如果将`pages/cart/index`注释掉，就不会报错`undefined`了。注释掉以后，我是否相当于继承了一个组件？意思是组件可以被页面继承，而页面就不行？

**Comment by imageslr** [comment]
目前实现两个一模一样的页面的解决办法是：新建一个基类`base.js`，把它当成组件用，两个页面的render方法都是`return <Base />`。这样重复写的代码最少。

也可以不用新建基类，直接将两个页面的其中之一作为组件，在render方法中返回。这样也能编译通过，只是报错`错误  组件引用  文件./index-page已经在 app.js 中被指定为页面，不能再作为组件来引用！`。

如果是用继承两个页面的其中之一的话，就会报错了。
