### ISSUE TITLE
如何在Taro自定义组件中调用原生微信小程序组件

### ISSUE THREAD

**Issue by Rychou** [NervJS/taro#2734]
调用原生微信小程序组件只需要配置`useComponent`，这就可以在页面中使用原生组件。

但是是否可以在自定义的`taro`组件中调用原生小程序组件呢？ 如果可以，如何实现？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/mini-third-party.html

**Comment by Rychou** [comment]
> https://nervjs.github.io/taro/docs/mini-third-party.html

文档示例是在页面中使用，如果我想在Taro自定义组件中使用原生组件呢，不是在页面js文件中使用

**Comment by kennylbj** [comment]
+1

**Comment by liuguanlin** [comment]
+1

**Comment by Chen-jj** [comment]
@Rychou 用法一样吧，自行试试咯
