### ISSUE TITLE
onClick方法被频繁调用，不停给服务器发请求

### ISSUE THREAD

**Issue by JackonLiu** [NervJS/taro#2738]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
按钮点击事件在view渲染时onClick方法被频繁调用，不停给服务器发请求，停止运行在浏览器还是不停发送请求

**复现步骤**
[复现问题的步骤]
1. Go to  开门列表
2. 还没有点击 开门按钮
3. See error

import Taro, {Component} from '@tarojs/taro'
import {View} from '@tarojs/components'
import isEmpty from 'lodash/isEmpty'
import './index.scss'
import {AtButton, AtIcon, AtList} from "taro-ui";
import {connect} from "@tarojs/redux";
@connect(({door, loading}) => ({
  ...door,
  openDoor: loading.effects["door/openDoor"],
}))
export default class Door extends Component {
  constructor (props) {
    super(props)
    console.log(props)
  }
![image](https://user-images.githubusercontent.com/27143111/56008837-26017380-5d10-11e9-956b-ae7439e53f97.png)

```js
    * openDoor ({payload}, { call, put }) {
      console.log(payload);
      let token = Taro.getStorageSync('auth');
      let { code, page} = yield call(request, {
        url: config.host.api + '/sys/facilityManage/openDoor',
        method: 'post',
        header: {
          Authorization: `Bearer ${token}`,
          "content-type": "application/json",
          "cache-control": "no-cache",
        },
      });
      if (code === 0) {
        yield put({
          type: 'list',
          payload: page
        })
      }
    },
```
``
**期望行为**
期望点击按钮再触发点击事件，而不是打开页面直接触发
**报错信息**
![image](https://user-images.githubusercontent.com/27143111/56008460-f00fbf80-5d0e-11e9-9027-3247260b1963.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [ Windows 7]
� Taro v1.2.22

  Taro CLI 1.2.22 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
npm run dev:h5
**补充信息**
出现这个问题的原因可能在点击事件这里，但是无论我在哪里调用这个方法都会出现频繁请求
我把调用的方法放在onPullDownRefresh也会频繁请求
已经排除了js和路由的问题，也不是后端的问题

**Comment by huiyuye** [comment]
是你调用的方式错了，onClick={ this.onPoor() }, 这样是不管点击不点击，onPoor都是会被调用的，因为你加了（），所以在渲染的时候，就会执行

**Comment by zhixiaoqiang** [comment]
react文档也建议好好看下， 不要在触发事件上写可直接执行的方法 
onClick={() => this.onPoor() }
onClick={this.onPoor}
onClick={this.onPoor.bind(this)}

**Comment by JackonLiu** [comment]
> 是你调用的方式错了，onClick = {this.onPoor（）}，这样是不管点击不点击，onPoor都是会被调用的，因为你加了（），所以在渲染的时候，就会执行。 onClick = {（）=> this.onPoor（）}，这样试试吧
我这样写成功解决问题  onClick={()=> this.onPoor(this.openDoor(item))}
但是又有一个新问题
Uncaught TypeError: _this2.onPoor is not a function

**Comment by zhixiaoqiang** [comment]
> > 是你调用的方式错了，onClick = {this.onPoor（）}，这样是不管点击不点击，onPoor都是会被调用的，因为你加了（），所以在渲染的时候，就会执行。 onClick = {（）=> this.onPoor（）}，这样试试吧
> > 我这样写成功解决问题  onClick={()=> this.onPoor(this.openDoor(item))}
> > 但是又有一个新问题
> > Uncaught TypeError: _this2.onPoor is not a function

这样写
onClick={() => this.onPoor(item) }
onClick={this.onPoor.bind(this, item)}

**Comment by JackonLiu** [comment]
> > > 是你调用的方式错了，onClick = {this.onPoor（）}，这样是不管点击不点击，onPoor都是会被调用的，因为你加了（），所以在渲染的时候，就会执行。 onClick = {（）=> this.onPoor（）}，这样试试吧
> > > 我这样写成功解决问题onClick = {（）=> this.onPoor（this.openDoor（item））} 
> > > 但是又有一个新问题
> > > Uncaught TypeError：_this2.onPoor不是函数
> 
> 这样写
> onClick = {（）=> this.onpenDoor（item）} 
> onClick = {this.onpenDoor.bind（this，item）}
可以了，感谢您的回复
