### ISSUE TITLE
你好，请问 taro 在 rn 环境可以关闭顶部导航栏吗？ 

### ISSUE THREAD

**Issue by Next0186** [NervJS/taro#2741]
**问题描述**
rn 和 H5 环境 不能取消 header
![image](https://user-images.githubusercontent.com/44919719/56016027-98348100-5d2d-11e9-8427-52e1fb575538.png)

**期望行为**
添加 rn 和 H5的 关闭 header 配置

**Comment by Pines-Cheng** [comment]
可以，和微信小程序配置一样，配置 navigationStyle:custom 就行。

**Comment by ID071108** [comment]
你好，在app.config.js的window对象里面设置navigationStyle:custom不能取消顶部导航栏， 请问应该在哪里设置呢
