### ISSUE TITLE
小程序端WebView onMessage 无法收到H5页面消息

### ISSUE THREAD

**Issue by gesineng** [NervJS/taro#2743]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
小程序端WebView onMessage 收不到H5页面发送回来的消息 H5页面postMessage之前触发了页面回退
**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
render() {
		return (
			<WebView
				src={this.state.url}
				onMessage={this.saveUserInfo.bind(this)}
				onError={this.webViewError.bind(this)}
				onLoad={this.webViewOnload.bind(this)}
			/>
		);
	}
/**
	 * saveUserInfo
	 */
saveUserInfo(e) {
		console.log('saveUserInfo --- saveUserInfo --- saveUserInfo', e);
	}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
收到消息
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]
Taro CLI 1.2.20 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 8.12.0 - F:\Node\node.EXE
      Yarn: 1.13.0 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - F:\Node\npm.CMD
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@gesineng 可以先自行写原生小程序代码测试一下，区分是 Taro 还是微信小程序的问题。

**Comment by bobsam** [comment]
@gesineng 这个你目前已经OK了吗？

**Comment by gesineng** [comment]
Ok了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bobsam <notifications@github.com&gt;
发送时间: 2019年12月4日 10:36
收件人: NervJS/taro <taro@noreply.github.com&gt;
抄送: gesineng <522956219@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[NervJS/taro] 小程序端WebView onMessage 无法收到H5页面消息 (#2743)




@gesineng 这个你目前已经OK了吗？

**Comment by bobsam** [comment]
那你还是用Taro实现的吗？
目前我用Taro实现，webview 返回时也是无法接收到消息。
请问是什么原因导致的吗？版本是 Taro v1.3.25 ~ v1.3.26
------
> Ok了。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: bobsam <notifications@github.com&gt; 发送时间: 2019年12月4日 10:36 收件人: NervJS/taro <taro@noreply.github.com&gt; 抄送: gesineng <522956219@qq.com&gt;, Mention <mention@noreply.github.com&gt; 主题: 回复：[NervJS/taro] 小程序端WebView onMessage 无法收到H5页面消息 (#2743) @gesineng 这个你目前已经OK了吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhouyingkai1** [comment]
有解决的吗，能说下怎么解决的吗 @bobsam  @gesineng

**Comment by Grrrr-sc** [comment]
有解决吗

**Comment by dexbol** [comment]
> 小程序端WebView onMessage 收不到H5页面发送回来的消息 H5页面postMessage之前触发了页面回退

需要 postMessage 之后触发页面回退。文档里有写触发时机：


>网页向小程序 postMessage 时，会在特定时机（小程序后退、组件销毁、分享）触发并收到消息。e.detail = { data }
