### ISSUE TITLE
创建mobx模板失败报错

### ISSUE THREAD

**Issue by hranharry** [NervJS/taro#2745]
v1.2.24
不使用typescript
使用sass
使用mobx模板

(node:87480) UnhandledPromiseRejectionWarning: ReferenceError: /Users/harry/.nvm/versions/node/v8.15.1/lib/node_modules/@tarojs/cli/templates/mobx/eslintrc:7
    5|     "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", ".tsx"] }]
    6|   },
 >> 7|   <%if (!typescript) {-%>
    8|   "parser": "babel-eslint"
    9|   <%} else { -%>
    10|   "parser": "@typescript-eslint/parser",

typescript is not defined
    at eval (eval at compile (/Users/harry/.nvm/versions/node/v8.15.1/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:11:7)
    at returnedFn (/Users/harry/.nvm/versions/node/v8.15.1/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/Users/harry/.nvm/versions/node/v8.15.1/lib/node_modules/@tarojs/cli/node_modules/ejs/lib/ejs.js:416:37)
    at render (/Users/harry/.nvm/versions/node/v8.15.1/lib/node_modules/@tarojs/cli/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)

**Comment by luckyadam** [comment]
下个版本会修复，你可以先创建 js 的模板

**Comment by CalmHarbin** [comment]
我创建新项目也失败了
Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

? 请输入项目介绍！
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 Redux 模板

✔ 创建项目: myApp
✔ 创建配置目录: myApp/config
✔ 创建源码目录: myApp/src
✔ 创建页面目录: myApp/src/pages
✔ 创建 actions 目录: myApp/src/actions
✔ 创建 constants 目录: myApp/src/constants
✔ 创建 reducers 目录: myApp/src/reducers
✔ 创建 store 目录: myApp/src/store
✔ 创建页面 TS 文件: myApp/src/pages/index/index.tsx
✔ 创建 action counter TS 文件: myApp/src/actions/counter.ts
✔ 创建 constant counter TS 文件: myApp/src/constants/counter.ts
✔ 创建 reducer counter TS 文件: myApp/src/reducers/counter.ts
✔ 创建 reducer 入口 TS 文件: myApp/src/reducers/index.ts
✔ 创建 store TS 文件: myApp/src/store/index.ts
✔ 创建页面 SCSS 文件: myApp/src/pages/index/index.scss
✔ 创建文件: myApp/src/app.tsx
✔ 创建文件: myApp/src/app.scss
✔ 创建文件: myApp/src/index.html
✔ 创建文件: myApp/config/index.js
✔ 创建文件: myApp/config/dev.js
✔ 创建文件: myApp/config/prod.js
✔ 创建文件: myApp/.editorconfig
✔ 创建文件: myApp/.gitignore
✔ 创建文件: myApp/package.json
✔ 创建文件: myApp/.eslintrc
✔ 创建文件: myApp/project.config.json
✔ 创建文件: myApp/.npmrc

√ Initialized empty Git repository in C:/Users/yuan/Desktop/Taro/myApp/.git/

× 安装项目依赖失败，请自行重新安装！
× Install fail! Error: [@typescript-eslint/parser@^0.12.0] Can't find package @typescript-eslint/parser@^0.12.0
Error: [@typescript-eslint/parser@^0.12.0] Can't find package @typescript-eslint/parser@^0.12.0
    at resolve (C:\Users\yuan\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:78:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Users\yuan\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 3.20.2
npminstall args: D:\Win10\node\node.exe C:\Users\yuan\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\yuan\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org




@typescript-eslint/parser@^0.12.0装这个依赖报错

手动 cnpm install也是报错

Install fail! Error: [@typescript-eslint/parser@^0.12.0] Can't find package @typescript-eslint/parser@^0.12.0

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/09cdab1677ef3c9170171575b5a829a461f5cab8
