### ISSUE TITLE
Uncaught TypeError: (0 , _router.createHistory) is not a function

### ISSUE THREAD

**Issue by JackonLiu** [NervJS/taro#2746]
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
Uncaught TypeError: (0 , _router.createHistory) is not a function
**复现步骤**
[复现问题的步骤]
1. npm run dev:h5

[或者可以直接贴源代码，能贴文字就不要截图]

```js
const _taroHistory = createHistory({
  mode: "hash",
  basename: "/",
  customRoutes: {},
  firstPagePath: "/pages/index/index"
});

mountApis(_taroHistory);
{
  require('taro-ui/dist/h5/css/index.css');
}

 <Router history={_taroHistory} routes={[{
            path: '/pages/index/index',
            componentLoader: () => import(
            /* webpackChunkName: "index_index" */'./pages/index/index'),
            isIndex: true
          }
```

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/27143111/56024526-c53f5e80-5d42-11e9-8240-ddf98a88cf3c.png)

- 操作系统: [ Windows 7]
  Taro v1.2.22

  Taro CLI 1.2.22 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
npm run dev:h5

**补充信息**
通过点击文件，在webstrom中搜索到该文件app.js

删除掉保存的方法和调用的view就可以，但是每回运行一次就会产生这个方法和bug

**Comment by luckyadam** [comment]
项目依赖与 cli 版本保持一致

**Comment by JackonLiu** [comment]
> 项目依赖与cli版本保持一致
我刚才更新了项目依赖还是没有用啊

**Comment by Zhou-Bill** [comment]
遇到类似的，具体怎么操作，没看懂
