### ISSUE TITLE
如何按需引入自定义组件减小打包体积？

### ISSUE THREAD

**Issue by catXiaoXiao** [NervJS/taro#2747]
**问题描述**
自己写的组件，如何在页面组件中按需引入组件，减小打包体积？

```js
// 这里可以贴代码


```
组件index如图
![image](https://user-images.githubusercontent.com/26037975/56028147-1868df80-5d4a-11e9-89a3-5cb5ca42cc89.png)

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by catXiaoXiao** [comment]
我在config.js里配置编译报错
![image](https://user-images.githubusercontent.com/26037975/56029921-2587cd80-5d4e-11e9-9855-44f3e12e33f7.png)

**Comment by luckyadam** [comment]
按这个文档来组织你的组件库吧
https://nervjs.github.io/taro/docs/ui-lib.html

**Comment by catXiaoXiao** [comment]
> 按这个文档来组织你的组件库吧
> https://nervjs.github.io/taro/docs/ui-lib.html
报错，还是找不到
![image](https://user-images.githubusercontent.com/26037975/56104613-0ca83380-5f6b-11e9-8a55-340cbd7447e2.png)
![image](https://user-images.githubusercontent.com/26037975/56104640-277aa800-5f6b-11e9-8a3c-bb43a889fbc2.png)

**Comment by catXiaoXiao** [comment]
只是想按需加载自己写的公共组件而已babel-plugins-import@luckyadam

**Comment by Littly** [comment]
不需要使用import插件。保证你的组件是es模块规范，并且在使用这个插件的时候使用namedImport的形式即可。

**Comment by catXiaoXiao** [comment]
> 不需要使用import插件。保证你的组件是es模块规范，并且在使用这个插件的时候使用namedImport的形式即可。
> 
> 另外，presets中的env，需要加上配置`{ modules: false }`

非常感谢(｡◕◡◕｡)ﾉ

**Comment by catXiaoXiao** [comment]
> 不需要使用import插件。保证你的组件是es模块规范，并且在使用这个插件的时候使用namedImport的形式即可。
> 
> 另外，presets中的env，需要加上配置`{ modules: false }`

昨天了解了一下webpack4的tree-shaking就解惑了(*^▽^*)

**Comment by catXiaoXiao** [comment]
> presets中的env，需要加上配置`{ modules: false }`

不过presets中的env，需要加上配置{ modules: false }是为了什么？？

**Comment by catXiaoXiao** [comment]
> 不需要使用import插件。保证你的组件是es模块规范，并且在使用这个插件的时候使用namedImport的形式即可。
> 
> 另外，presets中的env，需要加上配置`{ modules: false }`

为什么要关闭es6模块转换？

**Comment by catXiaoXiao** [comment]
> 不需要使用import插件。保证你的组件是es模块规范，并且在使用这个插件的时候使用namedImport的形式即可。
> 
> 另外，presets中的env，需要加上配置`{ modules: false }`

大神，我突然这个报错
![image](https://user-images.githubusercontent.com/26037975/56254737-87508a80-60f4-11e9-8c12-5ef2260a5881.png)
