### ISSUE TITLE
请问如何实现路由监控或者自定义路由中间件？

### ISSUE THREAD

**Issue by MikyChow** [NervJS/taro#2756]
希望能有一个路由中间件的功能、这样就能集中管理授权页面。目前在tab中如果某个页面时需要授权的这时候好像没有办法实现切换tab之后跳转。
`            Taro.redirectTo({
              url: '/pages/user/login/login'
            })`
如果在render中直接这样写在小程序中还在显示其他的tab就跳转了

或者能提供某个功能可以watch 路由变化

**Comment by luckyadam** [comment]
你可以加一个空白页面作为整个程序的首页，在里面判断是否登录，再进行相应跳转

**Comment by MikyChow** [comment]
但是这样在switchtab的时候始终都不会render，比如我用户状态为未登录、如果当前访问需要授权的页面才会跳转到登录页面，但是我switchtab的时候并没有任何的事件来确定tab已经跳转了。

**Comment by MikyChow** [comment]
我找到一个案例：https://juejin.im/post/5a30fc466fb9a0450809a773
请问是否是这个意思？

**Comment by luckyadam** [comment]
如果是某个 tab 需要授权，那你在 tab 切换过去之后提示授权就行了，使用 `componentDidShow`，文档里也有写到

**Comment by QuietWind** [comment]
@luckyadam  你说的添加空白页不能解决这个问题

1. 不是所有页面都是在launch的时候去控制 ”登录“ 权限
2. 会有场景是某些个别页面需要特殊权限，这个如何处理

能考虑一下楼主说的，路由加个中间层的hooks来控制，每个页面运行之前校验一下特殊权限，不然自己写的话就会去每个页面加一段代码，是不是可以考虑编译过程就帮忙处理了。

**Comment by atzcl** [comment]
可以自己封装一个路由类来处理

**Comment by WingGao** [comment]
这个感觉非常有必要做，如果是h5，普通刷新就一直停在那也，不能触发
