### ISSUE TITLE
支付宝request API 兼容问题

### ISSUE THREAD

**Issue by junhwong** [NervJS/taro#2757]
我看到 #2355 已经合并，并且只是简单的替换，但是 https://docs.alipay.com/mini/api/network 写的支付宝 基础库 1.11.0 以上才支持, 可以使用 my.canIUse('request') 做兼容性处理。

所以建议做一下兼容处理。

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/blob/master/packages/taro-alipay/src/native-api.js#L162
已经补了判断

**Comment by junhwong** [comment]
不好意思。我直接搜索的issue，没看到这个判断。
