### ISSUE TITLE
h5调试chooseImage模拟报错

### ISSUE THREAD

**Issue by linrf** [NervJS/taro#2758]
**问题描述**
chooseImage模拟报错

**复现步骤**
启动h5调试就报错了

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
![image](https://user-images.githubusercontent.com/8201516/56077444-ebcacb80-5e0e-11e9-9a29-28a9e4fc32fd.png)

图片好像报错了。
Uncaught TypeError: Cannot redefine property: chooseImage

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Mac
 - Taro 版本 👽 Taro v1.2.0-beta.11
 - Node.js 版本 10.10.0
 - 报错平台 h5

**补充信息**

**Comment by freeler** [comment]
同样的错误，泪奔中~

**Comment by luckyadam** [comment]
贴一下使用代码

**Comment by linrf** [comment]
> 贴一下使用代码

代码里并没有使用chooseImage这个方法。看了下应该是挂载在Taro对象上的。引入方式很常规
```
import Taro, { Component } from '@tarojs/taro'

```

这是我的项目依赖，看下是不是和这个有关？
```
	"dependencies": {
		"@tarojs/async-await": "1.2.3",
		"@tarojs/components": "1.2.3",
		"@tarojs/redux": "1.2.3",
		"@tarojs/redux-h5": "1.2.3",
		"@tarojs/router": "1.2.3",
		"@tarojs/taro": "1.2.3",
		"@tarojs/taro-alipay": "1.2.3",
		"@tarojs/taro-h5": "1.2.3",
		"@tarojs/taro-swan": "1.2.3",
		"@tarojs/taro-weapp": "1.2.3",
		"dva-core": "^1.4.0",
		"dva-loading": "^2.0.6",
		"html2json": "^1.0.2",
		"mocker-api": "^1.6.6",
		"nerv-devtools": "^1.3.9",
		"nervjs": "^1.3.9",
		"redux": "^4.0.0",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0",
		"showdown": "^1.9.0"
	},
```

目前我先降级回1.2.3了，因为正在联调。。

**Comment by luckyadam** [comment]
升级的话 cli 和项目依赖要保持一致

**Comment by linrf** [comment]
> 升级的话 cli 和项目依赖要保持一致

我是在项目里执行的npm update，是指需要单独升级cli的版本么？

**Comment by luckyadam** [comment]
你在项目里执行 npm update 只会升级本地项目依赖，安装的 taro cli 也要升级啊

**Comment by linrf** [comment]
> 你在项目里执行 npm update 只会升级本地项目依赖，安装的 taro cli 也要升级啊

这有点反逻辑啊。。并不是大版本的升级，居然强关联么。。

**Comment by luckyadam** [comment]
那你可以把 cli 安装到本地啊，哪里反逻辑？

**Comment by linrf** [comment]
> 那你可以把 cli 安装到本地啊，哪里反逻辑？

我是安装到本地的。。

**Comment by luckyadam** [comment]
那你检查一下版本有没有对上

**Comment by linrf** [comment]
👽 Taro v1.2.24


  Taro CLI 1.2.24 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.10.1 - ~/.npm-global/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.25 => 1.2.25 
      @tarojs/components: 1.2.25 => 1.2.25 
      @tarojs/plugin-babel: 1.2.25 => 1.2.25 
      @tarojs/plugin-csso: 1.2.25 => 1.2.25 
      @tarojs/plugin-less: 1.2.25 => 1.2.25 
      @tarojs/plugin-uglifyjs: 1.2.25 => 1.2.25 
      @tarojs/redux: 1.2.25 => 1.2.25 
      @tarojs/redux-h5: 1.2.25 => 1.2.25 
      @tarojs/router: 1.2.25 => 1.2.25 
      @tarojs/taro: 1.2.25 => 1.2.25 
      @tarojs/taro-alipay: 1.2.25 => 1.2.25 
      @tarojs/taro-h5: 1.2.25 => 1.2.25 
      @tarojs/taro-swan: 1.2.25 => 1.2.25 
      @tarojs/taro-weapp: 1.2.25 => 1.2.25 
      @tarojs/webpack-runner: 1.2.25 => 1.2.25 
      eslint-config-taro: 1.2.25 => 1.2.25 
      eslint-plugin-taro: 1.2.25 => 1.2.25 
      nervjs: ^1.3.9 => 1.3.13 

似乎cli最新版本就是1.2.24？
这是我npm i -g @tarojs/cli@latest  => taro update project => taro info拿到的信息。
重装依赖后，依然报错

**Comment by wycfcqt** [comment]
项目依赖和全局cli版本保持一致了，仍然会报这个错，今天刚升级了1.2.25才出现这个问题的

**Comment by xiaoyueyue165** [comment]
- 版本信息均已升级到 **1.2.25**
````bash
👽 Taro v1.2.25


  Taro CLI 1.2.25 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - D:\Alike\yarn\bin\yarn.CMD
      npm: 6.9.0 - ~\AppData\Roaming\npm\npm.CMD
````
- h5 编译报错 
````js
/* 未支持的api */
export * from './unsupportedApi'

/* 已实现api */
export * from './canvas'
export * from './createAnimation'
export * from './createSelectorQuery'
export * from './imageUtils'
export * from './interactive'
export * from './navigationBar'
export * from './others'
export * from './pullDownRefresh'
export * from './request'
export * from './storage'
export * from './system'
export * from './tabBar'
export * from './videoUtils' // Error:  Uncaught TypeError: Cannot redefine property: chooseImage
export * from './webSocket'

export * from './privateApis'

````

**Comment by Littly** [comment]
是个bug 1.2.26已修复~
