### ISSUE TITLE
import 新建的文件夹里面的js文件，但没有打包进build文件夹，导致报错

### ISSUE THREAD

**Issue by a709691139** [NervJS/taro#276]
在src目录下新建了个utils文件夹，里面有util.js文件，但引用报错。

![image](https://user-images.githubusercontent.com/21304258/42326242-2babaa1e-809b-11e8-9c25-332829c1516d.png)

**Comment by wushuxuan** [comment]
同问

**Comment by luckyadam** [comment]
0.0.68 已经修复了这个问题
