### ISSUE TITLE
feathub里第一个feature "react hook"的评论中出现了xss注入

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#2760]
feat地址： https://feathub.com/NervJS/taro/+14

页面被跳转到了https://blogs.kainy.cn/?from=feathubXSS&location.href=https%3A%2F%2Ffeathub.com%2FNervJS%2Ftaro%2F%2B14

经检查第三条评论中有xss注入

**Comment by Pines-Cheng** [comment]
确实是，感谢～

**Comment by yuche** [comment]
这个是 feathub 的问题，他们应该不维护了，996.icu 也列表也存在这个问题
