### ISSUE TITLE
关于 h5 的 onReachBottom 和 pullDownRefresh

### ISSUE THREAD

**Issue by hyacinthus** [NervJS/taro#2761]
我看更新说明中数次提到了 h5 的这两个东西，文档应该还没更新，我摸索着用，貌似没有效果。

首先 onReachBottom 貌似除了声明一下想不出什么别的使用方法。

PullDownRefresh 我是在代码中放了这个组件，也并没有用。

用成功的人能否指点一下呢？

**Comment by Littly** [comment]
目前的实现还有点问题 稳定之后会在文档中体现~

**Comment by hyacinthus** [comment]
好的知道了，谢谢。
