### ISSUE TITLE
taro怎么做UI测试？jest测试报着问题是什么概念？

### ISSUE THREAD

**Issue by chankamlam** [NervJS/taro#2763]
**问题描述**
【1】我用jest测试组件，组件代码如图
<img width="540" alt="屏幕快照 2019-04-14 下午6 09 32" src="https://user-images.githubusercontent.com/9009522/56091380-cc9c6e80-5ee0-11e9-9802-67d03bc57008.png">
【2】babel.config.js（能配我都配了，我尽力了）
<img width="718" alt="屏幕快照 2019-04-14 下午6 09 06" src="https://user-images.githubusercontent.com/9009522/56091394-f3f33b80-5ee0-11e9-8167-511620bfda77.png">

【3】测试代码如图
<img width="1029" alt="屏幕快照 2019-04-14 下午6 08 53" src="https://user-images.githubusercontent.com/9009522/56091387-e3db5c00-5ee0-11e9-99e3-b5891d4e8ef1.png">

为何报css出错？还有官网能不能多点jest或者mocha“组件测试”和“单元测试”文档，太一笔带过了，而且github源码也没什么测试用例

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-ui-sample
参考一下这个项目写测试
