### ISSUE TITLE
Swpier在h5模式下报错，componentWillUnmount没有判断mySwiper就this.mySwiper.destroy()

### ISSUE THREAD

**Issue by yinlsea** [NervJS/taro#2769]
**问题描述**
@tarojs\components\src\components\scroll-view\index.js
Swpier在h5模式下报错，componentWillUnmount没有判断my iSwiper就this.mySwiper.destroy()

**报错信息**
![image](https://user-images.githubusercontent.com/21033870/56112961-13e13880-5f8f-11e9-9601-4628a93923bf.png)

**系统信息**
taro 1.2.24

**Comment by yanghui1965** [comment]
taro  1.2.26 也存在这问题

**Comment by luckyadam** [comment]
#2790
