### ISSUE TITLE
给子组件传值，没办法获取到

### ISSUE THREAD

**Issue by jxl893251217** [NervJS/taro#277]
给组件传值时，  <Goods
                                stock={row.stock || 0}
                                masterImg={row.product && row.product.masterImg}
                  />
在Goods组件里stock能获取到值，但masterImg值为undefined。但实际上masterImg是确定有值的

**Comment by zacksleo** [comment]
是在组件中使用子组件吗？

**Comment by luckyadam** [comment]
可以给个示例么

**Comment by jxl893251217** [comment]
并不是组件里套组件。数据结构是这样的 var data={ stock:1,imgs:{ masterImg:'xxxxx'}}。stock就能获取到值，masterImg就不可以

**Comment by luckyadam** [comment]
新版组件化会修复这个问题~ 这周内可以发布

**Comment by luckyadam** [comment]
最新的 beta 版本已经解决了这个问题~
