### ISSUE TITLE
About touchEvent in ScrollView

### ISSUE THREAD

**Issue by Rahim-Chan** [NervJS/taro#2770]
**问题描述**
【H5模式下】scrollView组件下touch事件只能监听到touchStart、touchEnd。而touchMove且不能监听到。
小程序模式下是正常的~~

**复现步骤**
拉拽dom对呀ui节点，只能触发touchEnd、touchStart

```js
// 这里可以贴代码
`<ScrollView
        className="my-class scrollView"
        scrollY
        scrollWithAnimation
        scrollTop={0}
        onTouchMove={this.touchEvent}
        onTouchEnd={this.touchEvent}
        onTouchStart={this.touchEvent}
        style={style}
        lowerThreshold={30}
        upperThreshold={20}
        onScrollToLower={this.handleScrollToLower}
        // onScroll={this.onScroll}
      >`
```

**期望行为**
```
touchEvent(e) { conosle.log(e.type)}
```
应出现type为‘touchmove’的值
**报错信息**
无报错

**系统信息**
  Taro CLI 1.2.24 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.9.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by SunnyQjm** [comment]
同样的问题，h5端，ScrollView抓不到onTouchMove事件

**Comment by Tzng** [comment]
我也是，第一个功能就是要做下拉刷新上拉加载，然后发现touchMove没效果，，，

**Comment by YuQian2015** [comment]
同样的问题，之前用1.2.21可以，今天使用1.2.26发现不生效了。

**Comment by SunnyQjm** [comment]
这个问题解决了没～，目前1.3-beta2还不行

**Comment by SunnyQjm** [comment]
![image](https://user-images.githubusercontent.com/29176413/58240092-dab19a80-7d7c-11e9-929a-14cab2b7ff2c.png)
![image](https://user-images.githubusercontent.com/29176413/58240099-e1401200-7d7c-11e9-8560-9f75ea533847.png)
Taro components库下的 scroll-view 组件实现的时候直接拦截了onTouchMove事件？这是有意为之（onTouchMove会影响内部的实现嘛）？

**Comment by SunnyQjm** [comment]
修复了，提了pr,望采纳

**Comment by shenghanqin** [comment]
1.3.1 版本修复。
