### ISSUE TITLE
H5 子页面继承父页面，但是子页面未执行父类的componentDidShow和 componentDidHide，componentDidMount

### ISSUE THREAD

**Issue by dsitn201703** [NervJS/taro#2776]
**问题描述**
H5环境下，子页面继承父页面，但是子页面未执行父类的componentDidShow()和 componentDidHide()， componentDidMount()，必须要在子类中显示调用父类的相应方法。小程序正常。

**期望行为**
子类页面中自动执行父类的componentDidShow，componentDidHide，componentDidMount，不需要显示调用父类方法。

**系统信息**
![image](https://user-images.githubusercontent.com/26814281/56122791-ca501800-5fa5-11e9-825e-3f5217c8b339.png)

**补充信息**
问题原因已沟通，如图：
![image](https://user-images.githubusercontent.com/26814281/56122823-db992480-5fa5-11e9-8c64-307902277aaa.png)

**Comment by Littly** [comment]
已处理 https://github.com/NervJS/taro/commit/ba88faa17cd37175633ebb095b7309a6746f92bc 后续版本修复~
