### ISSUE TITLE
无法通过手机微信扫描进行预览，即在手机上进行小程序预览模式

### ISSUE THREAD

**Issue by whowrongswhere** [NervJS/taro#278]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
能不能再详细描述下问题

**Comment by ZXQ-GIGI** [comment]
问题描述
编译成微信小程序后，无法通过二维码扫描在手机上预览
![image](https://user-images.githubusercontent.com/20365416/43704661-f6f7bf7c-9992-11e8-8e90-526191916958.png)

复现步骤
npm run dev:weapp

期望行为
![image](https://user-images.githubusercontent.com/20365416/43704796-5e6a5b6a-9993-11e8-8d3f-28fae92c3c33.png)

系统信息

操作系统: [mac]
Taro 版本 [v0.0.73]
Node.js 版本 [v9.4.0]

**Comment by ZXQ-GIGI** [comment]
解决了，把dist文件夹删掉重新编译一下就好！

**Comment by whowrongswhere** [comment]
@ZXQ-GIGI 试了两次还是不行了

**Comment by ZXQ-GIGI** [comment]
首先填入自己的APPID，然后将dist删掉（包括正在预览的小程序，项目先删掉），然后重新build，重新打开项目

**Comment by whowrongswhere** [comment]
@ZXQ-GIGI 按你的操作可以预览了，多谢大神指导！
