### ISSUE TITLE
createAnimation 在h5动画没效果

### ISSUE THREAD

**Issue by talentedman** [NervJS/taro#2783]
源码如下:
![TIM截图20190416105807](https://user-images.githubusercontent.com/18200527/56179106-27e07500-6037-11e9-8332-bc246a2f5141.png)

Taro版本
![image](https://user-images.githubusercontent.com/18200527/56179135-3f1f6280-6037-11e9-8cd6-49a6516e6ecc.png)

npm包版本
![image](https://user-images.githubusercontent.com/18200527/56179180-5d855e00-6037-11e9-82d9-c60bb6b23e49.png)

这是一个简单的平移动画
在小程序的表现是正常的
但是在h5中 我看到的效果好像就是跳到了最后一帧  然后卡在那
而且动画结束的回调onTransitionEnd也不触发

**Comment by talentedman** [comment]
![image](https://user-images.githubusercontent.com/18200527/56197934-6f352880-606c-11e9-881f-fee6cc1112f1.png)
换成这种写法就可以了   h5要延迟 0.0

**Comment by luckyadam** [comment]
不需要延迟
正确的写法是在 componentDidMount 里调用动画方法，小程序也一样

**Comment by talentedman** [comment]
@luckyadam 

![image](https://user-images.githubusercontent.com/18200527/56256184-262bb580-60fa-11e9-9785-e8089d1606b9.png)

不行的   我试过了
所有我对h5初始化动画对象的时机真的很懵逼

**Comment by xxyGoTop** [comment]
h5的动画不能覆盖默认样式，导致初始化的时候，开始无法应用动画

**Comment by shenghanqin** [comment]
@talentedman 试试看最新版吧？
我看changelog有相应的修复。
