### ISSUE TITLE
npm run dev:h5 编译报错

### ISSUE THREAD

**Issue by seasolzombie** [NervJS/taro#2785]
**问题描述**
npm run dev:h5 编译报错

**复现步骤**
1.npm install -g @tarojs/cli 安装了包
2.运行 npm run dev:h5

**期望行为**
编译并运行成功

**报错信息**

Uncaught TypeError: Cannot read property 'initRouter' of undefined

**系统信息**

 - 操作系统: [mac 10]
 - Taro 版本 [Taro v1.0.1]
 - Node.js 版本 []
 - 报错平台 [h5]

**补充信息**

**Comment by Littly** [comment]
cli和项目依赖保持版本一致
