### ISSUE TITLE
从npm引用updeep包报错

### ISSUE THREAD

**Issue by yukinight** [NervJS/taro#2789]
**问题描述**
从npm导入‘updeep’模块后，用热启动命令npm run build:weapp -- --watch会报错，而直接编译taro build --type weapp不会出错

**复现步骤**
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
import u from 'updeep'
u({sd:23 }, {dd:234})
```

**期望行为**
可以热加载使用updeep

**报错信息**
VM29898:1 thirdScriptError 
 sdk uncaught third Error 
 process is not defined 
 ReferenceError: process is not defined
    at freeze (http://127.0.0.1:50590/appservice/npm/updeep/dist/freeze.js:54:3)
    at constant (http://127.0.0.1:50590/appservice/npm/updeep/dist/constant.js:48:37)
    at http://127.0.0.1:50590/appservice/npm/updeep/dist/update.js:55:56
    at require (http://127.0.0.1:50590/appservice/__dev__/WAService.js:1:1016120)
    at http://127.0.0.1:50590/appservice/__dev__/WAService.js:1:1015729
    at http://127.0.0.1:50590/appservice/npm/updeep/dist/ifElse.js:7:15
    at require (http://127.0.0.1:50590/appservice/__dev__/WAService.js:1:1016120)
    at http://127.0.0.1:50590/appservice/__dev__/WAService.js:1:1015729
    at http://127.0.0.1:50590/appservice/npm/updeep/dist/if.js:7:15
    at require (http://127.0.0.1:50590/appservice/__dev__/WAService.js:1:1016120)

**系统信息**
Taro v1.2.26
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 8.9.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
updeep此处代码报错，process is not defined，无法获取node下的变量
```
function freeze(object) {
  if (process.env.NODE_ENV === 'production') {
    return object;
  }
  if (process.env.UPDEEP_MODE === 'dangerously_never_freeze') {
    return object;
  }
  if (needsFreezing(object)) {
    recur(object);
  }
  return object;
}
```

**Comment by luckyadam** [comment]
在 `env` 配置里补上 UPDEEP_MODE 这个吧
