### ISSUE TITLE
setState时，渲染过慢，被不需要改变的state属性干扰了，由于其他的属性数据太大

### ISSUE THREAD

**Issue by tyouzu1** [NervJS/taro#279]
**问题描述**
使用setState时，更新一个简单属性 如将other改为false，渲染非常慢。
因为state中的其他属性 如list数据过大，将其减小就正常

项目是从支付宝小程序搬过来的，我在想是不是底层处理state的时候不一样，还没没看源码

**复现步骤**
state中的内容纯属举例！！！
当前页面state
```js
this.state={
list :[数据,数据,数据,数据,...],//  list.length = 1350
other:false,
}

```
更新界面实用的touch事件
```js
<View  onTouchStart={this.touchStart.bind(this)} onTouchEnd={this.touchEnd.bind(this)} onTouchMove={this.touchMove.bind(this)}> </View>

```
当我更新other属性时，渲染的非常慢，事件卡半天才能出来。
```js
onTouchStart(){
console.log('onTouchStart')
this.setState({
    other:true,
})
}
touchEnd(){
console.log('onTouchEnd')
this.setState({
    other:false,
})
}
touchMove(){
console.log('onTouchMove')
this.setState({
    other:true,
})
}
```
只有当我把list变小，更改state时候才能正常渲染
```js
this.state={
list :[数据,数据,数据,数据,...].slice(0,100),//  list.length = 100
other:false,
}

```

**期望行为**
能够正常渲染，setState时 更其他无关属性应该互不相干。

**报错信息**

就是 卡  卡  卡 卡 卡 卡 卡 卡 卡 卡

**系统信息**

mac  iphone  微信小程序

**补充信息**
setState的时候，应该只更新需要更新的属性把，是不是连带着其他的属性一起更新了。

**Comment by rojer95** [comment]
会更新 $usedState 下的所有属性

**Comment by yuche** [comment]
@rojer95 
所有 vdom 的实现都会有一个 diff 逻辑，只有老的 attr 和新的 attr 不同才会应用更改，而 diff 两组 vdom 树其实消耗没有想象地大。证明这件事很简单，只要数组循环出来的组件写上唯一稳定可预测的 key 就好了，这样 diff 算法就只需要遍历一次数组，不会对数组产生的组件做任何修改操作。但即便如此，（楼主提的这个情况）仍然会很慢。

对于小程序而言主要的开销我猜是 JS 线程的 data 传入到原生现成中的通信消耗，两个线程之间大概是通过 json-rpc 通信的，实际上用的是一个字符串，这里又还会有一个序列化和反序列化的开销。就楼主这个情况而言，解决的方案应该是减少真正传入小程序 `setData` 的数据量。我们现在已经保存了 prevState 和 newState，可以通过一次浅对比它们的数据找出真正改变的数据，但这样做也可能导致其他情况变得更慢了。我们还需要做更多地调研找到更好的办法。

事情有一个先后顺序，对于 Taro 而言现在的主要目标是 make it work 和 make it right，然后才是 make it fast。

**Comment by tyouzu1** [comment]
谢谢啦  我最开始估计也是底层实现不一样，但是也一直没怎么看微信的说明，因为暂用其他方式解决了。
主要项目从支付宝小程序迁过来的，因为 **_支付宝小程序 上很正常的_** ，所以提了issue
。
既然这样情况，那我就先关掉啦。

**Comment by yuche** [comment]
你应该把他打开比较合适，等我们把更多时间处理性能问题时也会来处理这个问题的。

**Comment by rojer95** [comment]
@yuche 
理解，希望越做越好。

**Comment by Andrewuetyang** [comment]
希望尽快解决，也遇到了同样的问题，感觉很不合理。

**Comment by Thehardtimesofbeans** [comment]
遇到同样问题，希望尽快解决，像日历控件，就特别卡

**Comment by WormGirl** [comment]
我也是  上拉加载更多卡爆了  就是因为setState太慢了，好长时间才有回调

**Comment by Miantang** [comment]
> @rojer95
> 所有 vdom 的实现都会有一个 diff 逻辑，只有老的 attr 和新的 attr 不同才会应用更改，而 diff 两组 vdom 树其实消耗没有想象地大。证明这件事很简单，只要数组循环出来的组件写上唯一稳定可预测的 key 就好了，这样 diff 算法就只需要遍历一次数组，不会对数组产生的组件做任何修改操作。但即便如此，（楼主提的这个情况）仍然会很慢。
> 
> 对于小程序而言主要的开销我猜是 JS 线程的 data 传入到原生线程中的通信消耗，两个线程之间大概是通过 json-rpc 通信的，实际上用的是一个字符串，这里又还会有一个序列化和反序列化的开销。就楼主这个情况而言，解决的方案应该是减少真正传入小程序 `setData` 的数据量。我们现在已经保存了 prevState 和 newState，可以通过一次浅对比它们的数据找出真正改变的数据，但这样做也可能导致其他情况变得更慢了。我们还需要做更多地调研找到更好的办法。
> 
> 事情有一个先后顺序，对于 Taro 而言现在的主要目标是 make it work 和 make it right，然后才是 make it fast。

就楼主这个情况，老的 attr 和新的 attr 浅对比diff之后的结果，理论上应当只有一个other才合理，但实际情况会给setData的数据量却加上了"整个list"，这个解决的方案是需要在diff层面做文章么？
另外想请教一下，目前taro是采用的什么方式，才引起了这个情况呢？

**Comment by zhaiduo** [comment]
刚用taro差不多完成了个项目，不过性能查、页面渲染慢确实是硬伤。

**Comment by xuzpeng** [comment]
我也遇到了，数据不多，渲染也贼慢，咋优化。。反馈太慢了

**Comment by hardmanhong** [comment]
我遇到的情况是，setState一个一维数组，UI上有多选按钮，存在数组中就选中。
但是setState之后基本都是超过300ms响应UI更新，为了拆除其他数组干扰，我还专门新建一个测试页只有那个一维数据测试，依然如此
