### ISSUE TITLE
如何劫持page 的声明周期

### ISSUE THREAD

**Issue by Yang03** [NervJS/taro#2791]
因为希望收集小程序端的数据
我定义了两个方法来劫持小程序的声明周期
```
Page = function(e) {
//doSometing
}
```
```
App = function(e) {
//doSometing
}
```
我可以通过 函数`App`获取到程序的数据，但是`Page`却不会调用

**Comment by AchillesDS** [comment]
可以在页面组件类上使用修饰器，在修饰器里劫持小程序原本的声明周期方法。
[http://es6.ruanyifeng.com/#docs/decorator](url)
