### ISSUE TITLE
false渲染成‘false’

### ISSUE THREAD

**Issue by yuquanwang** [NervJS/taro#2798]
**问题描述**
taro小程序对false、true的渲染与react不一致

**复现步骤**

```js
<View>{false}</View>

```
将渲染成"false"文本
**期望行为**
react 对于null、undefined、true、false都不会渲染。

**系统信息**
Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
    npmPackages:
      @tarojs/async-await: ^1.2.17 => 1.2.24 
      @tarojs/cli: ^1.2.23 => 1.2.24 
      @tarojs/components: ^1.2.17 => 1.2.24 
      @tarojs/plugin-babel: ^1.2.17 => 1.2.24 
      @tarojs/plugin-csso: ^1.2.17 => 1.2.24 
      @tarojs/plugin-sass: ^1.2.17 => 1.2.24 
      @tarojs/plugin-uglifyjs: ^1.2.17 => 1.2.24 
      @tarojs/redux: ^1.2.17 => 1.2.24 
      @tarojs/redux-h5: ^1.2.17 => 1.2.24 
      @tarojs/router: ^1.2.17 => 1.2.24 
      @tarojs/taro: ^1.2.17 => 1.2.24 
      @tarojs/taro-alipay: ^1.2.17 => 1.2.24 
      @tarojs/taro-h5: ^1.2.17 => 1.2.24 
      @tarojs/taro-swan: ^1.2.17 => 1.2.24 
      @tarojs/taro-tt: ^1.2.17 => 1.2.24 
      @tarojs/taro-weapp: ^1.2.17 => 1.2.24 
      @tarojs/webpack-runner: ^1.2.17 => 1.2.24 
      eslint-config-taro: ^1.2.17 => 1.2.24 
      eslint-plugin-taro: ^1.2.17 => 1.2.24 
      nervjs: ^1.3.9 => 1.3.13

**Comment by yuquanwang** [comment]
没人遇到一样的问题吗？

**Comment by ckytx** [comment]
这个问题啥时候解决下啊
