### ISSUE TITLE
Swiper组建在设置为左右滚动的时候，会将swiper-slide宽度自动减掉16px，怎么解决

### ISSUE THREAD

**Issue by jwhklk** [NervJS/taro#2799]
Swiper组建在设置为左右滚动的时候，会将swiper-slide宽度自动减掉16px，怎么解决

**Comment by jinjinjin0731** [comment]
dev 模式下有可能出现这个问题。 热更新导致。  你可以 build 之后，查看样式是否正确

**Comment by ManiuLtd** [comment]
@jinjinjin0731 使用taro1.3.20最新版本swiper的宽度问题依然存在

**Comment by ManiuLtd** [comment]
现在已经是2.0版本了，这个问题依然存在
