### ISSUE TITLE
h5中 toast组件 展示的时候, 会被页面上z-index大于0的元素遮挡, 在transition变换透明度的时候

### ISSUE THREAD

**Issue by magicbing** [NervJS/taro#2800]
**问题描述**
h5中 toast组件 展示的时候, 会被页面上z-index大于0的元素遮挡, 在transition变换透明度的时候

**复现步骤**
[复现问题的步骤]
1. 
Taro.showLoading({ title: '加载中' })
使用这类toast组件时, 会被页面div遮挡

因为.taro__toast的opacity transition时候 有层叠问题

加上全局样式可以解决
.taro__toast{
  position: relative;
  z-index: 5000;
}

希望这个文件修改一下
packages/taro-h5/src/api/interactive/toast.js

**Comment by Littly** [comment]
由用户自己用样式控制吧，taro内做这一步意义不大。taro给设置层级10000，用户写一个层级10001的div照样可以遮挡。
