### ISSUE TITLE
taro、小程序混写，使用include报错：Included `xxx` not found from `xxx`

### ISSUE THREAD

**Issue by BackToHappyBear** [NervJS/taro#2801]
使用官方推荐的案例
文件目录如图
![image](https://user-images.githubusercontent.com/20684300/56280484-e4702e80-613c-11e9-9263-ff648cc5426e.png)

引用如图
![image](https://user-images.githubusercontent.com/20684300/56280566-0cf82880-613d-11e9-9127-300222ecf65f.png)

加了个 template 文件夹
无效果，提示 
./pages/native/native.wxml:include:-1:-1: Included path `../../templates/toast/toast.wxml` not found from `./pages/native/native.wxml`.
(anonymous) @ VM538:5

**Comment by BackToHappyBear** [comment]
@luckyadam 请关注下这个问题

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/56709436-e72ddd80-6753-11e9-9da8-ae847a892f3c.png)

在 Config 里拷贝一下文件试试

**Comment by BackToHappyBear** [comment]
> ![image](https://user-images.githubusercontent.com/3471836/56709436-e72ddd80-6753-11e9-9da8-ae847a892f3c.png)
> 
> 在 Config 里拷贝一下文件试试

谢谢，是可以的，如果支持如下写法会更方便些
```js
copy: {
    patterns: [
       { from: 'src/templates/**/*.wxml', to: 'dist/templates/**/*.wxml'},
       { from: 'src/templates/**/*.js', to: 'dist/templates/**/*.js'}
    ],
    options: {}
  },
```
