### ISSUE TITLE
taro-alipay 1.2.26 版本运行报错

### ISSUE THREAD

**Issue by wnuoer** [NervJS/taro#2802]
**问题描述**
如题，升级到 1.2.26 版本之后。支付宝小程序运行时报错。

搜索关键字：onTaroCollectChilds

**复现步骤**
编译器中打开小程序。直接报错
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

**系统信息**
Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.26 => 1.2.26
      @tarojs/plugin-babel: 1.2.26 => 1.2.26
      @tarojs/plugin-csso: 1.2.26 => 1.2.26
      @tarojs/plugin-sass: 1.2.26 => 1.2.26
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26
      @tarojs/router: 1.2.26 => 1.2.26
      @tarojs/taro: 1.2.26 => 1.2.26
      @tarojs/taro-alipay: 1.2.26 => 1.2.26
      @tarojs/taro-h5: 1.2.26 => 1.2.26
      @tarojs/taro-swan: 1.2.26 => 1.2.26
      @tarojs/taro-tt: 1.2.26 => 1.2.26
      @tarojs/taro-weapp: 1.2.26 => 1.2.26
      @tarojs/webpack-runner: 1.2.26 => 1.2.26
      eslint-config-taro: 1.2.26 => 1.2.26
      eslint-plugin-taro: 1.2.26 => 1.2.26
      nervjs: 1.3.12 => 1.3.12
**补充信息**

**Comment by Chen-jj** [comment]
@wnuoer 贴一下代码，应该修复了

**Comment by leeviok** [comment]
现在我们也遇到了这个问题，1.2.26版本
![微信截图_20190419105927](https://user-images.githubusercontent.com/25154944/56403025-370f2f00-6292-11e9-8d89-5c27e878cf5d.png)
![微信截图_20190419110008](https://user-images.githubusercontent.com/25154944/56403050-4e4e1c80-6292-11e9-89b4-f2f1d1b5f95d.png)

**Comment by Chen-jj** [comment]
@leeviok 支付宝使用 mobx 引起的报错这位老哥已经修了：[556c31f](https://github.com/NervJS/taro/commit/556c31f7c3e953ad269ab7999dd1605c06d444e9)，可以升级到 v1.2.27-beta.0 再试试。

**Comment by Chen-jj** [comment]
@wnuoer 如果是因为你的组件继承了基类后报错，请记得传递参数给 Taro.component。

![image](https://user-images.githubusercontent.com/11807297/56718322-1dc62100-6771-11e9-96fc-0d8f7c315d5e.png)

如果还有问题就提供一下代码吧，我这边复现不了。

**Comment by qiliangya** [comment]
出现了相同的错误, 在支付宝小程序。 版本也是1.2.26, 而且并未使用mobx

**Comment by Chen-jj** [comment]
@qiliangya 继承了基类？列一下代码？

**Comment by qiliangya** [comment]
是按照实践, 写的装饰器。
``` javascript
// descript.js
export const withIndexDescription = mapStateProps => {
  return function indexDescriptionComponent (Component) {
    return class indexDescription extends Component {
      constructor (props) {
        super (props)
        this.__control = {
        
        } 
      }
  ......

// index.js
@withIndexDescription();
class Index extends Component{ ... }
```

把这个代码注释之后就不会那个错误, 在H5端和微信端没有出现问题

**Comment by Chen-jj** [comment]
@qiliangya 上面我已经截图了。。

```js
constructor () {
  super (...arguments)
}
```

**Comment by qiliangya** [comment]
@Chen-jj 抱歉~ 现在好了
