### ISSUE TITLE
style属性在小程序和react-native上编译问题

### ISSUE THREAD

**Issue by zWingz** [NervJS/taro#2803]
#### style 编译到小程序, 不支持object类型
```jsx
<View style={{left: '10px'}}>test</View>
```
转成小程序
```javascript
// ...
var $loopState__temp2 = { left: '10px' };
return {
    $loopState__temp2: $loopState__temp2
 };
```
```html
<view style="{{item.$loopState__temp2}}"></view>
```
小程序最终显示的是
```html
<view style="[object Object]"></view>
```

#### style 编译到react-native, 不支持字符串
```jsx
<View style='left: 10px;'>test</View>
```
会直接报错, [代码](https://github.com/NervJS/taro/blob/master/packages/babel-plugin-transform-jsx-to-stylesheet/src/index.js#L214)
![image](https://user-images.githubusercontent.com/13031838/56286022-3324c500-614b-11e9-97ec-3bc7141ff7c4.png)

#### 环境信息

`@tarojs/taro@1.2.26`

**Comment by js-newbee** [comment]
@zWingz 附上版本信息之类的吧，项目中一直都是这么写的，没有问题

**Comment by zWingz** [comment]
@js-newbee 小程序的`style`不支持引用`object`的吧 ?

**Comment by js-newbee** [comment]
> @js-newbee 小程序的`style`不支持引用`object`的吧 ?

@zWingz 当然是不支持... 我说的是用 Taro 写的，Taro 会处理这个的，所以让你提供版本信息啊，不然怎么排查问题...

**Comment by zWingz** [comment]
@js-newbee 上面已经补了

**Comment by js-newbee** [comment]
@zWingz 我用 taro init 新建了一个 1.2.26 的项目，复现不了，编译后的代码为：
```js
var anonymousState__temp = (0, _index.internal_inline_style)({ left: '10px' });
Object.assign(this.__state, {
  anonymousState__temp: anonymousState__temp
});
```

建议提供下可复现的完整代码

**Comment by zWingz** [comment]
@js-newbee 
![image](https://user-images.githubusercontent.com/13031838/56332841-7a9b6780-61c4-11e9-9cd0-d01afc13ce7c.png)
如果`class`名字为`_C`, 则会有这个问题, 如果是其他名字则不会
通过`taro-covert`将原生小程序转成`taro`, 类名都会改成`_C`, 因此有了这个问题

**Comment by zWingz** [comment]
至于`react-native`的`style`为字符串时, 问题都存在

**Comment by js-newbee** [comment]
> @js-newbee
> ![image](https://user-images.githubusercontent.com/13031838/56332841-7a9b6780-61c4-11e9-9cd0-d01afc13ce7c.png)
> 如果`class`名字为`_C`, 则会有这个问题, 如果是其他名字则不会
> 通过`taro-covert`将原生小程序转成`taro`, 类名都会改成`_C`, 因此有了这个问题

确实是，类名为 _C 时不正常... 
@yuche 大佬给看看吧，taro-transformer-wx/src/index.ts  第 480 行

**Comment by biorz** [comment]
新版本已解决。
