### ISSUE TITLE
云开发  云函数的目录配置问题

### ISSUE THREAD

**Issue by taichenglu** [NervJS/taro#2804]
使用云开发，在 project.config.json 中增加了配置
`"cloudfunctionRoot": "./cloudfn/"`

然后还需要在 config/index.js 增加配置

```
copy: {
  patterns: [
    { from: 'src/cloudfn/', to: 'dist/cloudfn/' }
  ]
}
```

这样虽然可以使用，但是开发工具会提示

> 如果不希望在小程序/小游戏的运行环境中执行该文件，请使用 project.config.json "miniprogramRoot" 组织项目目录结构

并且每次打包提交代码就会提示 cloudfn 未打包。想问一下，有没有办法做到 dist 目录是这样的：

```
dist
  src
  cloudfn
  project.config.json
```
然后把 miniprogramRoot 指向到 dist/src

**Comment by jinjinjin0731** [comment]
你可以将你的项目文件作为你的小程序项目，而不是 dist 文件。那样你就不必使用 copy 去生成到 dist 目录。 你可以参考[云开发模板](https://nervjs.github.io/taro/docs/wxcloud.html)的项目结构来组织你的项目。  
注意:  project.config.json 的文件记得配置好
    `"miniprogramRoot":` "client/dist/",`
  `"cloudfunctionRoot": "cloud/functions/",`

**Comment by taichenglu** [comment]
谢谢 @jinjinjin0731  思路不错，解决问题

**Comment by taichenglu** [comment]
忘记贴一下我的配置了，供其他同学参考

```
{
  "miniprogramRoot": "dist/",
  "cloudfunctionRoot": "cloudfn/",
  ...
}
```

另外发现一个现象，这样配置之后，dist 目录依然会生成一个 project.config.json

```
{
  "miniprogramRoot": "./",
  "cloudfunctionRoot": "cloudfn/",
  ...
}
```

这个文件会不会是多余的？并且这里的 cloudfunctionRoot 路径其实是错误的，它应该是 `../cloudfn/` @jinjinjin0731

**Comment by jinjinjin0731** [comment]
> 另外发现一个现象，这样配置之后，dist 目录依然会生成一个 project.config.json

这里依然会生成，是你没有把  project.config.json 这个文件放到外层的同级目录。  这个文件应该和你的 cloudfn 文件夹同级。 
之前的云模板结构你仔细看了没~~~ 它是在最外层的。放在最外层可解决你的问题

**Comment by taichenglu** [comment]
project.config.json 文件是没有放错的，我重新初始化一个示例项目，问题还是一样 @jinjinjin0731 

![image](https://user-images.githubusercontent.com/3377075/56547984-764ec000-65b1-11e9-8519-16b55de5a42f.png)

**Comment by jinjinjin0731** [comment]
@taichenglu 你重新初始化示例项目，选的是云模板？

**Comment by taichenglu** [comment]
@jinjinjin0731 哦，不是的，我都是用导入项目，我现在试一下看，谢谢

**Comment by taichenglu** [comment]
不过这个问题和模板没有关系，他是一个独立的问题，为什么编译时会在 dist 目录下再生成一个 project.config.json？他是有用的吗？我尝试删除它并没有发生什么问题

**Comment by jinjinjin0731** [comment]
有关系。这是 cli 的处理。

**Comment by taichenglu** [comment]
谢谢 @jinjinjin0731 ，我弄明白了，我少了一级目录，taro 是作为整个 client 目录，我之前是把 cloudfn 放到 taro 这个目录里去了

![image](https://user-images.githubusercontent.com/3377075/56549314-05a9a280-65b5-11e9-9285-9a9c17e03bb7.png)

**Comment by zheNeng** [comment]
如果我的小程序选择ts开发，如果taro 不把webpakc的配置提供出来，需要单独写一个webpack去编译ts文件。
需求：可以开放更多的webpack配置Merge选项么？

**Comment by zheNeng** [comment]
如果我的小程序云函数选择 ts 开发，如果 taro 不把 webpakc 的配置提供出来，需要单独写一个 webpack 
 去编译ts文件。
需求：可以开放更多的webpack配置Merge选项么？(主要是云函数代码的资源路径，被 webpack 处理了)
