### ISSUE TITLE
H5下编译报错：Cannot read property 'logInterceptor' of undefined 

### ISSUE THREAD

**Issue by imageslr** [NervJS/taro#2807]
网络请求中使用了`Taro.interceptors.logInterceptor`，小程序内没有问题，但是h5下编译时报错`TypeError: Cannot read property 'logInterceptor' of undefined `。

[复现demo](https://github.com/imageslr/taro-library)

请问这是什么问题呢？

另外编译到h5以后，navigator组件的className不会编译出来。比如：

```
<Navigator
        className='at-row at-row__align--start my-book-card'
        hoverClass='None'
      >
```

编译出来就成了
```
<div class="None">
```

**Comment by Littly** [comment]
navigate类名问题已处理
https://github.com/NervJS/taro/commit/032eafa7a7f030e6131b01796f5a373a2d547784#diff-177ae8f59eb339f227cb42b05465dad5R107
