### ISSUE TITLE
希望未来能支持scss中使用资源别名引用

### ISSUE THREAD

**Issue by catXiaoXiao** [NervJS/taro#2808]
**问题描述**
目前使用webpack自带的~@image报错

**期望行为**
希望未来支持一下

**系统信息**
Taro^1.2.4

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
Duplicate of #1474

**Comment by waveheart** [comment]
。。。。
找bug了半天。。原来还没支持，还以为是自己写错了。。。好惨。。。

**Comment by Chen-jj** [comment]
可以升级到 Taro 2、3 再试试
