### ISSUE TITLE
WECHAT-APP-MALL 使用 taro convert 文件丢失

### ISSUE THREAD

**Issue by BackToHappyBear** [NervJS/taro#2809]
版本信息
Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
    npmGlobalPackages:
      typescript: 3.1.6

上面是 taroConvert 文件夹下的内容，缺失了 datepicker
![image](https://user-images.githubusercontent.com/20684300/56333681-bb48b000-61c7-11e9-84fe-bd25d86443a4.png)

wechat-app-mall 目前用的是 master 分支最新的，git 信息：d2df38c9

**Comment by yuche** [comment]
https://github.com/EastWorld/wechat-app-mall/search?q=datepicker&unscoped_q=datepicker
这个 template 应该从来没有用到过，所以不会转换

**Comment by BackToHappyBear** [comment]
> https://github.com/EastWorld/wechat-app-mall/search?q=datepicker&unscoped_q=datepicker
> 这个 template 应该从来没有用到过，所以不会转换

好吧，这个我之前没有注意，因为我在官方给出的 taro、原生混合开发案例里，添加了 template，但是却不生效https://github.com/NervJS/taro/issues/2801 ，就直接拉了社区的代码测试了下

**Comment by yuche** [comment]
那个issue就在那里追踪吧
