### ISSUE TITLE
小程序中swiper组件属性设置无效

### ISSUE THREAD

**Issue by Nodewebzsz** [NervJS/taro#281]
`<Swiper className='swiper' 	onChange={this.swiperChange} indicatorDots={true} autoplay={true} interval='3000' duration='200'>`

这个里面indicatorDots不管是设置true还是默认false都出现指示点

**Comment by jinjinjin0731** [comment]
不应该出现这样的问题啊，晚点看一下

**Comment by atzcl** [comment]
没发现这个问题

**Comment by Sayid1** [comment]
只要设置了，不管是什么值都是true，不要指示点可以不设置

**Comment by jinjinjin0731** [comment]
问题还是没有复现， 按照你的写法 设置 indicatorDots={false} 指示点也是消失的，建议更新到最新版本再试一下
