### ISSUE TITLE
React devtools 一直Waiting for roots to load，redux devtools却正常

### ISSUE THREAD

**Issue by joriscai** [NervJS/taro#2810]
**问题描述**
根据官方提供的[文档](https://nervjs.github.io/docs/guides/devtools.html)，引用了nerv-devtools，但是在控制台打开React devtools，发现一直提示如下图。
![image](https://user-images.githubusercontent.com/17852005/56340695-408e8d80-61e5-11e9-94a9-55849cdf961d.png)
图标显示已经是可以使用了，但是却没有显示。

打开控制台，却发现好像是React devtool插件报错了，但redux devtools却能够正常使用哦
![image](https://user-images.githubusercontent.com/17852005/56340769-7df31b00-61e5-11e9-938d-c3ff1b8fe155.png)
Taro是使用了Nerv类React语法的框架，无法确定是否是插件问题，麻烦团队大佬看看这个问题，解决一下。

**复现步骤**
```js
// 这里可以贴代码
if (process.env.NODE_ENV !== 'production')  {
  require('nerv-devtools')
}
// before Nerv.render()
Nerv.render(<App />, document.getElementById('#root'))
```

**期望行为**
能够正常使用React devtools。

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 1.2.22
 - Node.js 版本 10.15.1
 - 报错平台 h5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
把依赖换成 nervjs@beta 就可以了

**Comment by joriscai** [comment]
> 把依赖换成 nervjs@beta 就可以了

nervjs@beta 我这边已经换了，package.json显示是 "nervjs": "^1.4.0-beta.2"，请问是这个版本吗？我这边还是不能使用呢。

**Comment by kid1412621** [comment]
+1

**Comment by yuche** [comment]
nerv-devtools 也要换成 beta 版本

**Comment by kid1412621** [comment]
换了啊

**Comment by yuche** [comment]
那建一个可以复现的仓库把

**Comment by Eric-Guo** [comment]
[换nerv-devtools到beta版本就好了](https://github.com/Eric-Guo/taro-redux-todolist/commit/bfe8d66666e2a0b0051c68adcdc04b7c5e46ff4c)
