### ISSUE TITLE
编译成微信小程序后 `componentWillReceiveProps` 这个生命周期函数的触发有问题

### ISSUE THREAD

**Issue by RunningCoderLee** [NervJS/taro#2818]
## 问题描述
taro 在编译成微信小程序后 `componentWillReceiveProps` 这个生命周期函数的触发有问题

## 复现步骤

1. clone https://github.com/RunningCoderLee/myMiniApp 这个项目到本地后安装依赖并运行
2. 小程序启动后 点击页面上的 `asyncAdd` 按钮，2秒后观察控制台
3. 此时 log 记录了 2次 `componentWillReceiveProps` 的调用，并打印了方法中的 `this.props`，`nextProps` 的值

## 期望行为
正常情况下，第一次 `componentWillReceiveProps` 方法中的 `nextProps` 的值应该等于 第二次 `componentWillReceiveProps` 方法中的 `this.props` 的值，但实际这2个值并不一样

## 报错信息

![image](https://user-images.githubusercontent.com/13218863/56354472-5fe9e280-6206-11e9-925d-678e73cc811a.png)

## 系统信息

```shell
  Taro CLI 1.2.24 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.24 => 1.2.24 
      @tarojs/components: 1.2.24 => 1.2.24 
      @tarojs/plugin-babel: 1.2.24 => 1.2.24 
      @tarojs/plugin-csso: 1.2.24 => 1.2.24 
      @tarojs/plugin-sass: 1.2.24 => 1.2.24 
      @tarojs/plugin-uglifyjs: 1.2.24 => 1.2.24 
      @tarojs/redux: 1.2.24 => 1.2.24 
      @tarojs/redux-h5: 1.2.24 => 1.2.24 
      @tarojs/router: 1.2.24 => 1.2.24 
      @tarojs/taro: 1.2.24 => 1.2.24 
      @tarojs/taro-alipay: 1.2.24 => 1.2.24 
      @tarojs/taro-h5: 1.2.24 => 1.2.24 
      @tarojs/taro-swan: 1.2.24 => 1.2.24 
      @tarojs/taro-tt: 1.2.24 => 1.2.24 
      @tarojs/taro-weapp: 1.2.24 => 1.2.24 
      @tarojs/webpack-runner: 1.2.24 => 1.2.24 
      eslint-config-taro: 1.2.24 => 1.2.24 
      eslint-plugin-taro: 1.2.24 => 1.2.24 
      nervjs: ^1.3.9 => 1.3.13 
```

## 补充信息

在使用 h5 模式下是正常的，在编译成小程序后就不符合正常的生命周期调用了

**Comment by RunningCoderLee** [comment]
请问这个问题有什么进展吗？

**Comment by Chen-jj** [comment]
@RunningCoderLee 考虑中

**Comment by yz1311** [comment]
+1,我还以为我代码有问题，componentWillReceiveProps触发了，this.props===nextProps

**Comment by ItxiaoDz** [comment]
+1，也是小程序中出现。感觉有点现是this.props和nextProps用了同一个对象了

**Comment by JasonYan2015** [comment]
+1 
我这边遇到的问题是，上一周期判断 nextProps.XXX 和 this.props.XXX 新旧值是正常的。
但是到下一次触发新的 componentWillReceiveProps 时，正常情况下这一轮周期的 this.props.XXX 应该等于上一轮周期的 nextProps.XXX 
但实际这一轮周期的 this.props.XXX 还是为空，导致预期的判断逻辑错误了

**Comment by GaoYuJian** [comment]
@ItxiaoDz 
同样的问题1.3.14  this.props === nextProps

**Comment by GaoYuJian** [comment]
@Chen-jj

**Comment by JasonYan2015** [comment]
更新到 v1.3.18 发现问题还是存在

**Comment by shenghanqin** [comment]
@RunningCoderLee 试试看最新版吧？`weapp: 修复微信小程序遗留代码：nextProps 初始化，引起的冲突 (00cf71c)`

**Comment by RunningCoderLee** [comment]
最近没有在用 taro 了，请还在使用的同学帮忙看下吧，如果已解决麻烦告知我一下，我把 issue 关了

@JasonYan2015 @ItxiaoDz @yz1311

**Comment by Chen-jj** [comment]
Taro3  应该没有这个问题了。
