### ISSUE TITLE
v1.2.26版本H5中调用Taro.startPullDownRefresh() 不会触发onPullDownRefresh()

### ISSUE THREAD

**Issue by CDJenson** [NervJS/taro#2822]
**问题描述**
v1.2.26版本H5中调用Taro.startPullDownRefresh() 不会触发onPullDownRefresh()，手动下拉可以触发onPullDownRefresh()

**期望行为**
期望H5中能支持Taro.startPullDownRefresh()触发onPullDownRefresh()

**系统信息**
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.1.0 - C:\DevelopProgramFiles\nodejs\node.EXE
      Yarn: 1.7.0 - C:\Users\xx\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\DevelopProgramFiles\nodejs\npm.CMD

**Comment by blackRe** [comment]
为什么文档中写的startPullDownRefresh支持h5，我用的使用的h5文件却无法低调用，哥，文档用点心，我看的想哭啊，还有个是Taro.pageScrollTo(params).then(...)明明写的支持，为啥h5也不支持啊，我在谷歌浏览器打开的，把链接发在微信上打开了也没有刷新或者定位到我指定的位置

**Comment by shenghanqin** [comment]
@zoujunda 麻烦看一下最新版效果？

**Comment by zoujunda** [comment]
> @zoujunda 麻烦看一下最新版效果？

我现在是1.3.25版本，H5在页面中调用Taro.startPullDownRefresh()可以触发页面onPullDownRefresh()，在组件中则不会。微信在组件中也可以。

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。
