### ISSUE TITLE
Taro 不支持微信小程序第三方开发getExtConfig

### ISSUE THREAD

**Issue by JonesAtom** [NervJS/taro#2823]
Taro 目前不支持微信小程序第三方开发getExtConfig，希望官方有解决方法

**Comment by Chen-jj** [comment]
@JonesAtom 支持。

![image](https://user-images.githubusercontent.com/11807297/56409427-9af22180-62ab-11e9-8ad5-2e4045154bc6.png)

![image](https://user-images.githubusercontent.com/11807297/56409434-9fb6d580-62ab-11e9-9421-88fd67ab62cd.png)
