### ISSUE TITLE
TabBar的list里的图标，希望可以传入组件，这样更灵活一点

### ISSUE THREAD

**Issue by jwhklk** [NervJS/taro#2824]
TabBar的list里的图标，希望可以传入组件，这样更灵活一点

**Comment by jwhklk** [comment]
现在的方式有点太逊了，我多很久没用图片做这样的组件了，全部都用字体库了

**Comment by jinjinjin0731** [comment]
taro-ui 的么？

**Comment by jwhklk** [comment]
不是ui的，就是taro组件里面的



------------------ 原始邮件 ------------------
发件人: "JinJinJin"<notifications@github.com>; 
发送时间: 2019年4月19日(星期五) 下午4:50
收件人: "NervJS/taro"<taro@noreply.github.com>; 
抄送: "klk"<523947655@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NervJS/taro] TabBar的list里的图标，希望可以传入组件，这样更灵活一点 (#2824)




taro-ui 的么？
 
&mdash;

**Comment by jinjinjin0731** [comment]
那你指的应该就是支持 tabBar 的 custom 特性。

**Comment by jwhklk** [comment]
------------------ 原始邮件 ------------------
发件人: "JinJinJin"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 下午4:55
收件人: "NervJS/taro"<taro@noreply.github.com>;
抄送: "klk"<523947655@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NervJS/taro] TabBar的list里的图标，希望可以传入组件，这样更灵活一点 (#2824)




那你指的应该就是支持 tabBar 的 custom 特性。
