### ISSUE TITLE
在pages下面的index文件中引用其它模块导入的文件会引起编译报错

### ISSUE THREAD

**Issue by PWDream** [NervJS/taro#2825]
![image](https://user-images.githubusercontent.com/4903755/56405739-3f6e6680-62a0-11e9-8fe9-d0b52eb19c49.png)
![image](https://user-images.githubusercontent.com/4903755/56405769-56ad5400-62a0-11e9-9ebc-2bd797586494.png)

目前的解决方案是，直接引用在index里面直接引用

**Comment by shenghanqin** [comment]
我最近发现
```
export default {
 a: 1
}

// index.js
import { a } from 'xxx'
```
a可能也找不到。
