### ISSUE TITLE
样式刷新后就改变了

### ISSUE THREAD

**Issue by JackonLiu** [NervJS/taro#2828]
**问题描述**
按钮样式刷新几次就改变了

**复现步骤**
[复现问题的步骤]
1. Go to 开门页面
2.刷新几次
3. See error

[或者可以直接贴源代码，能贴文字就不要截图]

```js
`<View title={item.id} className='item'>
              <View className='door-view' >
                <AtIcon value='iphone-x' size='34' color='#5c89e4' ></AtIcon>
                {item.name}
                <AtButton  className='open-door' type='primary' onClick={this.openDoor.bind(this,item)}>开门</AtButton>
              </View>
            </View>
.open-door{
  font-size: 25px;
  height: 46px;
  line-height: 40px;
  display: inline-block;
  float:right;
  color: white;
  margin-right: 30px;
  background-color: #5c89e4;
}

`

```

**报错信息**
样式改变，按钮似乎不在<view>里面
这是开始的按钮
![按钮样式](https://user-images.githubusercontent.com/27143111/56413234-61281780-62b9-11e9-9ade-49c41aaa5376.png)

![样式改版](https://user-images.githubusercontent.com/27143111/56413236-64230800-62b9-11e9-8d74-0d5d56a08b04.png)
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
� Taro v1.2.22

  Taro CLI 1.2.22 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
问题可能在taro，也可能在Atbutton

**Comment by jinjinjin0731** [comment]
版本？ 平台？  就一个问题可能在 taro。 怎么解决问题？
