### ISSUE TITLE
[微信小程序]安卓机的CoverView组件无法覆盖原生组件Canvas

### ISSUE THREAD

**Issue by Shalhvi** [NervJS/taro#2839]
**问题描述**
[微信小程序]安卓机的CoverView组件无法覆盖原生组件Canvas，苹果表现正常。

**复现步骤**
```js
<CoverView
  className='navigation'
  style={{
    height: `${height}px`,
    lineHeight: `${height}px`,
    paddingTop: `${paddingTop}px`,
    backgroundColor: `${backgroundColor}`,  
  }}
>
  {title}
</CoverView>

/* 样式 */
.navigation {
  position: fixed;
  left: 0;
  top: 0;
  z-index: 9;
}
```

**期望行为**
安卓机的CoverView组件可以覆盖Canvas

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
 Taro v1.2.26
  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm

 - 报错平台 weapp

**Comment by zhenliliu** [comment]
目前的解决方式就是将canvas导出图片来代替

**Comment by Garfield550** [comment]
CoverView 和 Canvas 的层级问题是微信小程序常见问题，你可以去微信小程序开发社区反馈一下。

从代码来看你似乎是用 CoverView 做了个导航条到组件，跟下面微信社区里找到的问题比较类似，
感兴趣可以跟进下
https://developers.weixin.qq.com/community/develop/doc/0000242e53cf0849276806d755bc00?highLine=cover-view%2520canvas

**Comment by Shalhvi** [comment]
> CoverView 和 Canvas 的层级问题是微信小程序常见问题，你可以去微信小程序开发社区反馈一下。
> 
> 从代码来看你似乎是用 CoverView 做了个导航条到组件，跟下面微信社区里找到的问题比较类似，
> 感兴趣可以跟进下
> https://developers.weixin.qq.com/community/develop/doc/0000242e53cf0849276806d755bc00?highLine=cover-view%2520canvas



> CoverView 和 Canvas 的层级问题是微信小程序常见问题，你可以去微信小程序开发社区反馈一下。
> 
> 从代码来看你似乎是用 CoverView 做了个导航条到组件，跟下面微信社区里找到的问题比较类似，
> 感兴趣可以跟进下
> https://developers.weixin.qq.com/community/develop/doc/0000242e53cf0849276806d755bc00?highLine=cover-view%2520canvas

是的，渲染先后顺序问题，因为给canvas加了条件判断，导致后于CoverView渲染><

**Comment by Shalhvi** [comment]
> CoverView 和 Canvas 的层级问题是微信小程序常见问题，你可以去微信小程序开发社区反馈一下。
> 
> 从代码来看你似乎是用 CoverView 做了个导航条到组件，跟下面微信社区里找到的问题比较类似，
> 感兴趣可以跟进下
> https://developers.weixin.qq.com/community/develop/doc/0000242e53cf0849276806d755bc00?highLine=cover-view%2520canvas

是的，渲染先后顺序问题，因为给canvas加了条件判断，导致后于CoverView渲染><

**Comment by BluesVN** [comment]
<img width="470" alt="image" src="https://github.com/NervJS/taro/assets/27759401/59ad5208-b28d-4be3-8a0c-9996b98fd5f6">
