### ISSUE TITLE
Image 图片加载失败时，如何替换为缺省图？

### ISSUE THREAD

**Issue by DuduStyle** [NervJS/taro#2841]
如何使用onError去替换失败的图片，而不频繁操作State

**Comment by shuzhiweb** [comment]
同问。。。怎么解决啊

**Comment by Pines-Cheng** [comment]
这样子可以实现吗？

```jsx
<Image src={record.picture} onError={(e)=>{e.target.onerror = null; e.target.src="image_path_here"}}/>
```

**Comment by shuzhiweb** [comment]
> 这样子可以实现吗？
> 
> ```js-jsx
> <Image src={record.picture} onError={(e)=>{e.target.onerror = null; e.target.src="image_path_here"}}/>
> ```

打印e.target 没有 src 这个属性，尴尬

**Comment by Pines-Cheng** [comment]
哪个平台？

**Comment by shuzhiweb** [comment]
> 哪个端？

小程序端和H5端用e.target.src 方式都不可行

**Comment by yuche** [comment]
尝试下用 e.detail.src

**Comment by shuzhiweb** [comment]
@FrankFan 我暂时的处理时，用定位做的，缺省图定位到网络图片下面。

**Comment by shuzhiweb** [comment]
@FrankFan 我暂时的处理是用定位做的，缺省图定位到网络图片下面。

**Comment by FrankFan** [comment]
@shuzhiweb  没太明白「用定位做的」是什么意思  。

我用的hack方法是 `在 Image 触发 OnError 回调中调用 setState 给图片赋值缺省图片的地址` 。

**Comment by jinjinjin0731** [comment]
基本是用原生小程序去做处理， 最终还是要 this.setData 去改变 src 地址。
