### ISSUE TITLE
react native  .rn.tsx 独立组件样式文件编译引入出错

### ISSUE THREAD

**Issue by ickeep** [NervJS/taro#2846]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
![image](https://user-images.githubusercontent.com/9164133/56479817-ebef5900-64e9-11e9-8065-f5d1a167346b.png)

如上图文件结构，在 product_list.rn.tsx  引入文件
```js
import './product_list.less'
 ```
在 .rn_temp目录下生成的内容

```js
// 编译后的文件带了 .rn 导致出错
import product_list.rnStyleSheet from "./product_list.rn_styles";
var _styleSheet = product_list.rnStyleSheet;
```

**期望行为**
编译正常

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/9164133/56479847-0a555480-64ea-11e9-84cd-2274afec0a43.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.2.27-beta.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      babel-plugin-transform-jsx-to-stylesheet: 1.2.27-beta.0 => 1.2.27-beta.0
      postcss-pxtransform: 1.2.27-beta.0 => 1.2.27-beta.0
      stylelint-taro-rn: 1.2.27-beta.0 => 1.2.27-beta.0

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
babel-plugin-transform-jsx-to-stylesheet
生成styleSheetIdentifierValue  的时候 把 .号过滤

**Comment by Pines-Cheng** [comment]
我来处理一下，感谢提 issue。
