### ISSUE TITLE
组件嵌套问题

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#2850]
```jsx
// A 组件
<View>{this.props.children}</View>

// B 组件
<Text>{this.props.children}</Text>

// 使用
<A>
  111
  <B>222</B>
</A>
```

预期是这样的：
```jsx
<View>
  111
  <Text>222</Text>
</View>
```

实际上渲染出来是这样的
```jsx
<View>111</View>
<Text>222</Text> // B 组件不在 A 组件里，和 A 组件的 View 并列了
```

**Comment by yuche** [comment]
你在小程序开发者工具看着是是这样，但是你仔细看编译后的结果和最终显示都应该是准确的。

这是小程序开发者工具的 bug。

**Comment by yinLiangDream** [comment]
> 你在小程序开发者工具看着是是这样，但是你仔细看编译后的结果和最终显示都应该是准确的。
> 
> 这是小程序开发者工具的 bug。

我用的全局样式，B 组件的样式继承一部分 A 组件的，但是渲染出来，A 组件的样式没有影响到 B 组件

**Comment by yuche** [comment]
小程序的自定义组件的样式就是不能继承的
https://developers.weixin.qq.com/community/develop/doc/21bf63d2e9eafe5088ebbae918c5f4bb

**Comment by yinLiangDream** [comment]
好吧……我要改改思路了，还有 1.3 版本啥时候放出来啊，很想要 class 里面写无状态组件，不然写的太麻烦了orz

**Comment by yuche** [comment]
这周应该会发 beta 版本
