### ISSUE TITLE
微信小程序中父组件的render在子组件render之后触发，并且传值后不触发子组件render

### ISSUE THREAD

**Issue by sanye33** [NervJS/taro#2854]
![image](https://user-images.githubusercontent.com/22977141/56497160-0b5ca500-652f-11e9-8668-78cff012c70f.png)
![image](https://user-images.githubusercontent.com/22977141/56497187-26c7b000-652f-11e9-8ebb-75f9ed931623.png)

我设置了一个延迟的setState，也只触发了父组件的render，子组件没有变化，问题只在微信小程序中出现，支付宝小程序没有问题

**Comment by skilme** [comment]
![image](https://user-images.githubusercontent.com/22977141/56497295-8920b080-652f-11e9-8e6e-04dd081e4e8f.png)

**Comment by skilme** [comment]
经过测试，我回退到之前的版本，这个问题解决了。。。
![image](https://user-images.githubusercontent.com/22977141/56498210-495bc800-6533-11e9-9456-e4c11306f29f.png)

![image](https://user-images.githubusercontent.com/22977141/56498222-54aef380-6533-11e9-831a-f50b5072bf18.png)

**Comment by Chen-jj** [comment]
@skilme 提供一下父子组件的完整可复现代码。

**Comment by skilme** [comment]
子组件：

`import Taro, { Component } from '@tarojs/taro'
import { Map } from '@tarojs/components'

export interface IProps {
  width?: number, // 地图宽度
  height?: number, // 地图高度
  latitude: number,
  longitude: number,
  scale?: number,
  markers?: Array<IMaker>,
  'show-location'?: boolean,
  [x: string]: any
}

interface IState {}

interface IMaker {
  id?: number,
  latitude: number,
  longitude: number,
  iconPath: string,
  title?: string,
  zIndex?: number,
  rotate?: number,
  alpha?: number,
  with?: number,
  height?: number,
  callout?: ICallout,
  label?: any,
  anchor?: any,
  'aria-label'?: string
  [x: string]: any
}

type ICallout = {
  content: string
  color: string,
  fontSize: number,
  borderRadius: number,
  borderWidth: number,
  borderColor: string,
  bgColor: string,
  padding: number,
  display: 'BYCLICK' | 'ALWAYS',
  textAlign:  'left' | 'right' | 'center'
}

class Tmap extends Component<IProps, IState> {
  static defaultProps = {
    width: 750,
    height: 750,
    scale: 15,
    latitude: 22.520015,
    longitude: 113.941815,
    markers: []
  }
  render () {
    const {
      width,
      height,
      scale,
      markers,
      latitude,
      longitude,
      'show-location': showLocation
    } = this.props
    const mapStyle = {
      width: Taro.pxTransform(width as number),
      height: Taro.pxTransform(height as number)
    }
    return (
      <Map
        style={mapStyle}
        scale={scale}
        markers={markers}
        latitude={latitude}
        longitude={longitude}
        show-location={showLocation}
      />
    )
  }
}

export default Tmap
`

父组件：
`import { ComponentType } from 'react'
import Taro, { Component, Config } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Tmap from '../../components/map/map'
// import getLocaltion from '../../adapter/getLocaltion'

interface IState {
  mapWidth: number,
  mapHeight: number,
  latitude: number,
  longitude: number,
  scale?: number,
  markers?: Array<any>,
  [x: string]: any
}

interface IProps {
  user: IUserStore;
}


@inject('user') @observer
class Index extends Component<IProps, IState> {
  static defaultProps = {
    user: store.user
  }
  config: Config = {
    navigationBarTitleText: ''
  }

  constructor (props) {
    super(props)
    this.state = {
      mapWidth: 750,
      mapHeight: 750,
      latitude: 22.520015,
      longitude: 113.941815,
      showLocation: false,
      scale: 15,
      markers: [{
        id: 1,
        width: 30,
        height: 40,
        latitude: 22.520015,
        longitude: 113.941815,
        iconPath: pioMaker,
        callout: {
          content: '我是气泡呀呀',
          color: '#666',
          fontSize: 18,
          padding: 10,
          borderRadius: 10,
          textAlign: 'center'
        }
      }, {
        id: 2,
        width: 30,
        height: 40,
        latitude: 22.522015,
        longitude: 113.941815,
        iconPath: 'https://a.amap.com/jsapi_demos/static/demo-center/icons/poi-marker-default.png',
        callout: {
          content: '我是气泡呀呀',
          color: '#666',
          fontSize: 18,
          padding: 10,
          borderRadius: 10,
          textAlign: 'center'
        }
      }]
    }
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        scale: 10
      })
    }, 3000)
  }

  render() {
    console.log(`-----父组件的render----->`, this.state)
    const {
      latitude,
      longitude,
      scale,
      markers,
      mapWidth,
      mapHeight,
      showLocation
    } = this.state
    return (
      <View className='p-take'>
        <Tmap
          width={mapWidth}
          height={mapHeight}
          latitude={latitude}
          longitude={longitude}
          scale={scale}
          show-location={showLocation}
          markers={markers}
        />
      </View>
    )
  }
}

export default Index as ComponentType
`

**Comment by Chen-jj** [comment]
@sanye33 使用你的代码，结果正常：

![image](https://user-images.githubusercontent.com/11807297/56937648-765e3b00-6b30-11e9-84fc-95d38295989e.png)

建议你在 setTimeout 触发时，进入编译后父组件 render 函数一步步打断点，

代码和我这边 master 最新编译出的有点出入，但大同小异，进入此 `propsManager.set` 调用：

![image](https://user-images.githubusercontent.com/11807297/56937832-5ed38200-6b31-11e9-8ed4-d26402f75df4.png)

然后会赋值，跟着在 setter 里会调用 `updateComponent` 方法：

![image](https://user-images.githubusercontent.com/11807297/56937914-cbe71780-6b31-11e9-8cc3-5a03aba61299.png)

跟踪 updateComponent 到 doUpdate 方法中，看此时给子组件的 [setData](https://nervjs.github.io/taro/docs/debug.html#debug-diff) 数据是否正确。

**Comment by sanye33** [comment]
![image](https://user-images.githubusercontent.com/22977141/56938707-21252800-6b36-11e9-8bf4-3a71e269839a.png)
我的好像没有被编译

**Comment by Chen-jj** [comment]
@sanye33 列代码要列全

**Comment by sanye33** [comment]
![image](https://user-images.githubusercontent.com/22977141/56939116-086a4180-6b39-11e9-872d-0fcb6d65ddbe.png)

**Comment by Chen-jj** [comment]
@sanye33 老哥 createData 不是有吗，你自己都截图出来了。另外能不能把代码截全？？截图截不全就 cope 代码文本啊，信息都提供不全，怎么帮你呢

**Comment by Chen-jj** [comment]
@sanye33 你自己先打断点吧，步骤我已经说得非常详细了。

**Comment by sanye33** [comment]
```javascript
define("pages/my/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,fetch,XMLHttpRequest,WebSocket,webkit,WeixinJSCore,Reporter,print,URL,DOMParser,upload,preview,build,showDecryptedInfo,syncMessage,checkProxy,showSystemInfo,openVendor,openToolsLog,showRequestInfo,help,showDebugInfoTable,closeDebug,showDebugInfo,__global,WeixinJSBridge){ "use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _get = function get(object, property, receiver) { if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { return get(parent, property, receiver); } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } };

var _class, _temp2;

var _index = require("../../npm/@tarojs/taro-weapp/index.js");

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var Index = (_temp2 = _class = function (_BaseComponent) {
  _inherits(Index, _BaseComponent);

  function Index() {
    var _ref;

    var _temp, _this, _ret;

    _classCallCheck(this, Index);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = Index.__proto__ || Object.getPrototypeOf(Index)).call.apply(_ref, [this].concat(args))), _this), _this.$usedState = ["mapWidth", "mapHeight", "latitude", "longitude", "scale", "showLocation", "markers"], _this.config = {
      navigationBarTitleText: ''
    }, _this.$$refs = [], _temp), _possibleConstructorReturn(_this, _ret);
  }

  _createClass(Index, [{
    key: "_constructor",
    value: function _constructor(props) {
      _get(Index.prototype.__proto__ || Object.getPrototypeOf(Index.prototype), "_constructor", this).call(this, props);
      // static defaultProps = {
      //   user: store.user
      // }

      this.state = {
        mapWidth: 750,
        mapHeight: 750,
        latitude: 22.520015,
        longitude: 113.941815,
        showLocation: false,
        scale: 15,
        markers: [{
          id: 1,
          width: 30,
          height: 40,
          latitude: 22.520015,
          longitude: 113.941815,
          iconPath: 'https://a.amap.com/jsapi_demos/static/demo-center/icons/poi-marker-default.png',
          callout: {
            content: '我是气泡呀呀',
            color: '#666',
            fontSize: 18,
            padding: 10,
            borderRadius: 10,
            textAlign: 'center'
          }
        }, {
          id: 2,
          width: 30,
          height: 40,
          latitude: 22.522015,
          longitude: 113.941815,
          iconPath: 'https://a.amap.com/jsapi_demos/static/demo-center/icons/poi-marker-default.png',
          callout: {
            content: '我是气泡呀呀',
            color: '#666',
            fontSize: 18,
            padding: 10,
            borderRadius: 10,
            textAlign: 'center'
          }
        }]
      };
    }
  }, {
    key: "componentDidMount",
    value: function componentDidMount() {
      var _this2 = this;

      setTimeout(function () {
        _this2.setState({
          scale: 10
        });
      }, 3000);
    }
  }, {
    key: "_createData",
    value: function _createData() {
      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __isRunloopRef = arguments[2];
      ;

      console.log("-----\u7236\u7EC4\u4EF6\u7684render----->", this.__state);
      var _state = this.__state,
          latitude = _state.latitude,
          longitude = _state.longitude,
          scale = _state.scale,
          markers = _state.markers,
          mapWidth = _state.mapWidth,
          mapHeight = _state.mapHeight,
          showLocation = _state.showLocation;

      Object.assign(this.__state, {});
      return this.__state;
    }
  }]);

  return Index;
}(_index.Component), _class.properties = {}, _class.$$events = [], _temp2);
exports.default = Index;

Component(require('../../npm/@tarojs/taro-weapp/index.js').default.createComponent(Index, true));
});
```
@Chen-jj 抱歉没有截全代码，这个父组件编译后生成的所有代码，麻烦了

**Comment by Chen-jj** [comment]
@sanye33 v1.2.27-beta.0 对 `createData` 的编译不应该是这个样子，会有 `propsManager.set` 这一串东西，你把 CLI 和依赖包重新安装下再试试。

**Comment by sanye33** [comment]
> @sanye33 v1.2.27-beta.0 对 `createData` 的编译不应该是这个样子，会有 `propsManager.set` 这一串东西，你把 CLI 和依赖包重新安装下再试试。
已经试过多次重新安装`1.2.27-beta.0` 结果都是一样，只有回退版本后，才表现正常

**Comment by Chen-jj** [comment]
@sanye33 CLI 装了吗

**Comment by sanye33** [comment]
@Chen-jj 也更新到了最新版本

**Comment by Chen-jj** [comment]
@sanye33 你到 dist/npm/@tarojs/taro-weapp/dist/index.js 里搜一下有没有 propsManager 的定义并截图

**Comment by sanye33** [comment]
![image](https://user-images.githubusercontent.com/22977141/56940275-dad4c680-6b3f-11e9-9f6b-990b477e8b02.png)

**Comment by sanye33** [comment]
@Chen-jj 已经好了，我将缓存文件  和 node_model全删了   重新yarn   编译后   没问题了

**Comment by Chen-jj** [comment]
@sanye33 用 npm 吧，稳一点
