### ISSUE TITLE
this.setState()函数的回调事件不执行

### ISSUE THREAD

**Issue by hello-lun** [NervJS/taro#2855]
我的某个组件使用Taro.eventBus.trigger(),触发‘updateHomeData’事件，本组件监听这个事件，然后在'updateHomeData'事件里执行this.setState()改变state变量。然后在setState()的回调里调用某个函数。但奇怪的是setState()的回调不执行。
代码如下图：
![image](https://user-images.githubusercontent.com/34638158/56570768-1fb3a700-65ee-11e9-9093-4211f5f95e2c.png)

我想用setTimeout模拟setState的回调函数，居然发现一个更加奇怪的现象。
我在setState后面加上setTimeout定时器后，居然setState的回调就执行了。这到底是什么情况？
代码如下：
![image](https://user-images.githubusercontent.com/34638158/56571422-7a99ce00-65ef-11e9-80e4-6592cff08210.png)

打印的结果如下：
![image](https://user-images.githubusercontent.com/34638158/56572219-3ad3e600-65f1-11e9-8296-4812770983e0.png)

求大佬搭救一下

**Comment by yuche** [comment]
你是在哪个平台出现这个问题

**Comment by hello-lun** [comment]
小程序端出现的问题


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Yu Che <notifications@github.com>
发送时间: 2019年4月22日 19:24
收件人: NervJS/taro <taro@noreply.github.com>
抄送: hello-lun <872570730@qq.com>, Author <author@noreply.github.com>
主题: 回复：[NervJS/taro] this.setState()函数的回调事件不执行 (#2855)




你是在哪个平台出现这个问题

**Comment by Chen-jj** [comment]
@hello-lun 哪个小程序平台？

**Comment by Garfield550** [comment]
参考一下 Taro UI 的写法？

```js
  bindMessageListener () {
    Taro.eventCenter.on('atMessage', (options = {}) => {
      const { message, type, duration } = options
      const newState = {
        _isOpened: true,
        _message: message,
        _type: type,
        _duration: duration || this.state._duration
      }
      this.setState(newState, () => {
        clearTimeout(this._timer)
        this._timer = setTimeout(() => {
          this.setState({
            _isOpened: false
          })
        }, this.state._duration)
      })
    })
    // 绑定函数
    Taro.atMessage = Taro.eventCenter.trigger.bind(Taro.eventCenter, 'atMessage')
  }
```

https://github.com/NervJS/taro-ui/blob/b63eb1aebb366046e3416ab806e76a6f3bddca43/src/components/message/index.js#L19-L39

**Comment by hello-lun** [comment]
> @hello-lun 哪个小程序平台？Taro 版本号多少？

我是在微信小程序遇到的，taro版本号是 v1.2.22

**Comment by Chen-jj** [comment]
@hello-lun 复现不了。可以升级到 1.2.27-beta.0 再试试。

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Detail extends Component {
  state = {
    current: 0
  }
  componentWillMount () {
    Taro.eventCenter.on('fire', () => {
      this.setState({
        current: 1
      }, () => {
        console.log('cb called')
      })
    })
  }

  render() {
    return (
      <View>
        <View>current: {this.state.current}</View>
        <View onClick={() => Taro.eventCenter.trigger('fire')}>fire</View>
      </View>
    )
  }
}
```

**Comment by Garfield550** [comment]
> > @hello-lun 哪个小程序平台？Taro 版本号多少？
> 
> 我是在微信小程序遇到的，taro版本号是 v1.2.22

请至少升级到 1.2.23 以上试一试，taro-ui 的最低版本是 1.2.23

![image](https://user-images.githubusercontent.com/3471836/56942029-b6321c00-6b4a-11e9-88d8-bedc90839929.png)

https://github.com/NervJS/taro-ui/blob/b63eb1aebb366046e3416ab806e76a6f3bddca43/package.json#L84-L96
