### ISSUE TITLE
多端开发遇到的问题

### ISSUE THREAD

**Issue by luweiCN** [NervJS/taro#2856]
------------------------

**问题描述**
页面文件采用`test.h5.js`，`test.weapp.js`无效

**报错信息**
1. pages目录下的page文件，我写了h5和小程序端对应的js
![image](https://user-images.githubusercontent.com/25150291/56497978-5d52fa00-6532-11e9-8fd1-ab2bd763870e.png)
在app.js中做了如下定义
![image](https://user-images.githubusercontent.com/25150291/56498028-968b6a00-6532-11e9-8e21-67b06c4cdec6.png)

2. 但是在小程序中bian编译出来的文件如下图
![image](https://user-images.githubusercontent.com/25150291/56498041-a73be000-6532-11e9-996c-471da46f5f41.png)
app.json中定义如下
![image](https://user-images.githubusercontent.com/25150291/56498056-b4f16580-6532-11e9-9f8f-9bf4b8f24559.png)
所以得到了如下图的错误
![image](https://user-images.githubusercontent.com/25150291/56498072-c33f8180-6532-11e9-8314-e4b3b5e738e8.png)

3. h5中得到如下错误
![image](https://user-images.githubusercontent.com/25150291/56498089-d94d4200-6532-11e9-80b3-4aa7229fb6d0.png)

**期望行为**
期望页面文件也能支持**统一接口的多端文件**的跨端方式，并且，比如在h5中，如果没有定义`test.h5.js`的跨端文件，能够自动引入`test.js`作为默认文件

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-less: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: ^1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 

**补充信息**
组件**统一接口的多端文件**的跨端方式经测试是没问题的，但是页面就不行

**Comment by jinjinjin0731** [comment]
不支持页面

**Comment by luweiCN** [comment]
@jinjinjin0731 为什么不支持呢，有没有支持的计划

**Comment by jinjinjin0731** [comment]
暂时没有支持的计划，你可以去[FeatHub](https://feathub.com/NervJS/taro) 投个票。到时候会评估然后加上特性

**Comment by tourze** [comment]
不看issue不知道还有这个限制。。。
