### ISSUE TITLE
微信小程序正常，h5编译报错

### ISSUE THREAD

**Issue by Painfee** [NervJS/taro#2858]
**问题描述**
    微信小程序正常，h5编译报错
**复现步骤**
报错如下：

![image](https://user-images.githubusercontent.com/38997514/56504769-30134580-654c-11e9-8aa8-06faa3347e03.png)
![image](https://user-images.githubusercontent.com/38997514/56504885-98622700-654c-11e9-9e3c-bf4f83d8b131.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.13.4]
 - Taro 版本 [Taro v1.2.0-beta.7]
 - Node.js 版本 [10.14.1]
 - 报错平台 [h5]

**补充信息**
更新了taro版本或者重新下载node_modules都没用

**Comment by Littly** [comment]
cli和项目依赖版本保持一直即可

**Comment by Painfee** [comment]
感谢，问题已经解决了！但其中有个小小的问题，分享一下吧
就是我用 npm i -g @tarojs/cli@1.2.26，试了好几次都失败了，最后去更新了下node版本再来试试就成功了，命令如下（我也不知道为什么，给后来有类似问题的同学能借鉴借鉴下）
![image](https://user-images.githubusercontent.com/38997514/56633671-acfc0780-6691-11e9-8917-e45e860d17ec.png)
