### ISSUE TITLE
dev:h5编译过程正常，但打开网页报错Unexpected token ,

### ISSUE THREAD

**Issue by hhw28** [NervJS/taro#2866]
------------------------

**问题描述**
1、支付宝、微信小程序编辑运行一切正常
2、编译成h5，编译过程一切成功，无报错
3、但是打开h5网页报错如图

![image](https://user-images.githubusercontent.com/24521571/56551812-f11cd880-65bb-11e9-9b87-87707fbd418d.png)

4、第三个报错信息中代码如下图，是有export的

![image](https://user-images.githubusercontent.com/24521571/56551857-127dc480-65bc-11e9-8aeb-bf690ffbcac8.png)

**期望行为**
1、h5成功编译，并能打开网页正常运行

**代码截图**

1、config/index.js
![image](https://user-images.githubusercontent.com/24521571/56552186-0a725480-65bd-11e9-8d34-86f352624b4a.png)

2、src/app.js
![image](https://user-images.githubusercontent.com/24521571/56552233-3261b800-65bd-11e9-88c0-6f395b9787dd.png)

**系统信息**
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by Littly** [comment]
看起来你配了路径别名？

![image](https://user-images.githubusercontent.com/5780093/56586800-f0fbf780-6612-11e9-9efb-94719991133b.png)

**Comment by hhw28** [comment]
> 看起来你配了路径别名？
> 
> ![image](https://user-images.githubusercontent.com/5780093/56586800-f0fbf780-6612-11e9-9efb-94719991133b.png)

的确配了，但是h5网页中并没有针对这个有报错

**Comment by Littly** [comment]
这个情况有可能是alias导致的，目前h5的alias实现有点问题，正在修复

**Comment by hhw28** [comment]
> 这个情况有可能是alias导致的，目前h5的alias实现有点问题，正在修复

我把alias注释，编译还是正常，打开浏览器查看还是同样的报错

**Comment by Littly** [comment]
![image](https://user-images.githubusercontent.com/5780093/56856979-76780280-6999-11e9-9105-0bbed862f4c6.png)
那你从这个位置点进去截个图，看看具体的情况

**Comment by hhw28** [comment]
> ![image](https://user-images.githubusercontent.com/5780093/56856979-76780280-6999-11e9-9105-0bbed862f4c6.png)
> 那你从这个位置点进去截个图，看看具体的情况

![image](https://user-images.githubusercontent.com/24521571/56873271-c4f1d380-6a63-11e9-91b8-d64e492a7f07.png)

**Comment by Yana5417** [comment]
请问这个问题解决了吗？我这边也是新定义了路径别名，然后报`Uncaught SyntaxError: Unexpected token '<'`
