### ISSUE TITLE
使用crypto.createHash提示Uncaught TypeError: crypto.createHash is not a function

### ISSUE THREAD

**Issue by polofish** [NervJS/taro#2867]
**问题描述**
使用crypto.createHash提示Uncaught TypeError: crypto.createHash is not a function
 

**复现步骤**
在代码中插入如下
const str = 'xxxx'
const crypto = require('crypto')
console.log(crypto)   // 显示众多undefined(比如常用的createHash\createHmac\ 等等)
const sha1sum = crypto.createHash('sha1')
console.log(sha1sum) // 已报错了.... 报错信息如上方问题描述
sha1sum.update(str)
hash = sha1sum.digest('hex')

<img width="264" alt="WechatIMG1564" src="https://user-images.githubusercontent.com/22722049/56553699-dfd6ca80-65c1-11e9-8911-733959755734.png">
<img src="https://user-images.githubusercontent.com/22722049/56553680-d5b4cc00-65c1-11e9-8db7-5d7e763e3a8a.png">

**期望行为**
能够正常使用 createHash\createHmac\randomBytes等

**报错信息**
Uncaught TypeError: crypto.createHash is not a function
    at eval (query.js?69a9:10)
    at Module../.temp/utils/query.js (app.e6e46c68c5f944a3e658.js:1043)
    at __webpack_require__ (app.e6e46c68c5f944a3e658.js:767)
    at fn (app.e6e46c68c5f944a3e658.js:130)
    at eval (model.js:2)
    at Module../.temp/pages/home/model.js (app.e6e46c68c5f944a3e658.js:1007)
    at __webpack_require__ (app.e6e46c68c5f944a3e658.js:767)
    at fn (app.e6e46c68c5f944a3e658.js:130)
    at eval (index.js?58e7:2)
    at Module../.temp/models/index.js (app.e6e46c68c5f944a3e658.js:995)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac 10.14.4
 - Taro 版本 v1.2.26
 - Node.js 版本 v10.14.2
 - 报错平台 h5, weapp

**Comment by jinjinjin0731** [comment]
crypto 是 node 包。无法使用。你要引入对应的 web 版本

**Comment by Garfield550** [comment]
你可以使用 `crypto-js`

比如 MD5

`import MD5 from 'crypto-js/md5';`

![image](https://user-images.githubusercontent.com/3471836/56566835-2e965b80-65e6-11e9-8fc2-9851cddf1533.png)
![image](https://user-images.githubusercontent.com/3471836/56566866-4241c200-65e6-11e9-933b-3a60ba085ff5.png)

**Comment by Creat155** [comment]
![Snipaste_2019-05-10_17-37-44](https://user-images.githubusercontent.com/39396448/57517876-5a397580-734a-11e9-8441-0f8f9991c64f.png)

**Comment by cj506817364** [comment]
具体怎么解决的?我也碰到这个问题了,在控制台可以运行,但是用Pycharm运行就失败

Pycharm运行截图:
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/83981303-2822-4d00-a1ef-1cfdffdfa4f1">

控制台运行截图
<img width="703" alt="image" src="https://github.com/user-attachments/assets/18800f66-37ea-4309-98a1-011a9e713172">

操作系统: mac 14.5
Node.js 版本 v10.24.1
报错平台 pycharm
