### ISSUE TITLE
关于页面渲染奇怪的问题

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#2868]
我使用 requestAnimationFrame 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/24502330/56559344-f5ed8680-65d3-11e9-8eaa-d99258c2faff.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/24502330/56559357-06056600-65d4-11e9-9c26-763a54002f5b.png">

如果我不写 
```jsx
<Text style={{visiable: 'hidden'}}>{this.state.progress}</Text>
```
页面是这样一直卡住，然后突然 100%
![image](https://user-images.githubusercontent.com/24502330/56560121-29311500-65d6-11e9-9d4e-97c2ca65c9c0.png)
![image](https://user-images.githubusercontent.com/24502330/56559976-bd4eac80-65d5-11e9-9a1c-4a6fefd00983.png)

如果我写了就很正常慢慢加载
![image](https://user-images.githubusercontent.com/24502330/56560041-f424c280-65d5-11e9-92f1-b0d89ae98fe9.png)

预期：
希望写不写都一样能加载
另外
```jsx
<Text style={{display: 'none'}}>{this.state.progress}</Text>
```
也是突然加载的，我怀疑是纯样式改变，无法触发 setState

**Comment by Littly** [comment]
什么平台？

**Comment by yinLiangDream** [comment]
微信小程序

**Comment by yinLiangDream** [comment]
> 什么平台？

微信小程序

**Comment by Chen-jj** [comment]
@yinLiangDream 正常啊，你不 setTimeout 肯定是把所有 state 合并起来。setState 并不是同步的

**Comment by yinLiangDream** [comment]
> @yinLiangDream 正常啊，你不 setTimeout 肯定是把所有 state 合并起来。setState 并不是同步的

可是关我写那一行 Text 有什么关联呢？这么说的话我写的字应该是直接 0 跳到 100，但是字是每 0.5 会动一下，还有异步问题，我这样写也不行
```jsx
this.setState(
      {
        loadProgress: this.state.loadProgress + 0.5
      },
      () => {
        if (this.state.loadProgress < 100) {
          timer = requestAnimationFrame(() => {
            this.loadProgress();
          });
        } else {
          this.setState({
            loadProgress: 100
          });
        }
      }
    );
```

**Comment by Chen-jj** [comment]
@yinLiangDream 你可以结合编译后的 js 中的 createData 函数、wxml 中模板变量和 [真正 setData 的值](https://nervjs.github.io/taro/docs/debug.html#%E8%A2%AB-diff-%E9%80%BB%E8%BE%91%E8%BF%87%E6%BB%A4)，先自行定位一下。

**Comment by yinLiangDream** [comment]
@Chen-jj 
<img width="871" alt="image" src="https://user-images.githubusercontent.com/24502330/56647714-7edbef00-66b4-11e9-934f-46486928adb8.png">
这是编译过后的代码，我把这一行注释掉就不能正常渲染了……和编译前情况一模一样
然后我去 diff 了一下，更神奇了，其实 diff 是没问题的，写不写 Text diff 的情况都是一样的
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/24502330/56648918-bc417c00-66b6-11e9-83cc-13b652a15b46.png">
我如果按照断点慢慢调试，看模拟器上是没有问题的，一点一点增长，如果我把断点放开，那么就会出现之前的现象，停住不动，突然 100

**Comment by Chen-jj** [comment]
@yinLiangDream 先升级到最新版本 v1.2.27-beta.0 再试试。

另外 setData 调用的**次数**和每次 setData 的**内容**是否正确？

如果还是不行，可以提供最简洁的可复现的代码我晚点看看。

**Comment by yinLiangDream** [comment]
```jsx
import Taro, { Component } from '@tarojs/taro';

export default class test extends Component {
  state = {
    loadProgress: 0
  };
  loadProgress() {
    this.setState({
      loadProgress: this.state.loadProgress + 0.5
    });
    if (this.state.loadProgress < 100) {
      timer = requestAnimationFrame(() => {
        this.loadProgress();
      });
    } else {
      this.setState({
        loadProgress: 100
      });
    }
  }
  componentDidMount() {
    this.loadProgress();
  }
  render() {
    return (
      <View className={`load-progress show`} style={{ top: '0' }}>
        <View
          className={`load-progress-bar bg-blue`}
          style={{
            transform: `translate3d(-${100 -
              this.state.loadProgress}%, 0px, 0px)`
          }}
        />
      </View>
    );
  }
}
```
```css
.load-progress {
	pointer-events: none;
	top: 0;
	position: fixed;
	width: 100%;
	left: 0;
	z-index: 2000;
}
.load-progress .load-progress-bar {
	position: relative;
	width: 100%;
	height: 4rpx;
	overflow: hidden;
	transition: all 200ms ease 0s;
}
.bg-blue {
        background-color: blue;
}
```

**Comment by archywillhe** [comment]
did you manage to resolve this problem?
