### ISSUE TITLE
页面退出清除缓存后，再次进入未能初始化 state

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#287]
**问题描述**
最近的一个 [commit](https://github.com/NervJS/taro/commit/c420b21b91c1243afe9d4de8dbcb5c68149fa263) 加了一个页面退出时清除缓存的功能。但是发现页面的缓存（state）直接清空后，再次进入这个页面，state 并没有再次初始化。

（也就是说，比如下面的 state 初始化语句并不会在第二次包括之后进入页面时起效。）
```jsx
state = {
  a: 1
}
```

**系统信息**
 - 操作系统: Mac OS
 - Taro 版本 0.0.68
 - Node.js 版本 10.6.0

**Comment by luckyadam** [comment]
确实欠考虑了~ 08f63fd  这个 commit 应该修复了这个问题~
另外 @tarojs/taro-weapp 这个包发了一个 beta 版本 `0.0.69-beta.0` 可以安装试试

**Comment by luckyadam** [comment]
好嘞~ 那我关闭啦
