### ISSUE TITLE
引入 支付宝 mini-antui 组件，组件样式错误

### ISSUE THREAD

**Issue by huangjianke** [NervJS/taro#2870]
**问题描述**
引用 tab 组件，样式错误
![image](https://user-images.githubusercontent.com/8692455/56567410-71a4fe80-65e7-11e9-9dbc-cec5d4dfc62b.png)

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
展示正常样式的组件

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.2]
 - Taro 版本 [1.2.22]
 - Node.js 版本 [10.15.3]
 - 报错平台 [alipay]

**Comment by shenghanqin** [comment]
是差一倍吗？

你的样式是不是按照375来写的，而Taro好像是按照750的。

**Comment by dasoncheng** [comment]
@huangjianke 在taro（typescript）中如何引入`mini-antui `
