### ISSUE TITLE
超级奇怪，为什么this.setState的回调事件不执行？？？

### ISSUE THREAD

**Issue by hello-lun** [NervJS/taro#2871]
我的某个组件使用Taro.eventBus.trigger(),触发‘updateHomeData’事件，本组件监听这个事件，然后在'updateHomeData'事件里执行this.setState()改变state变量。然后在setState()的回调里调用某个函数。但奇怪的是setState()的回调不执行。
代码如下图：
![image](https://user-images.githubusercontent.com/34638158/56570768-1fb3a700-65ee-11e9-9093-4211f5f95e2c.png)

我想用setTimeout模拟setState的回调函数，居然发现一个更加奇怪的现象。
我在setState后面加上setTimeout定时器后，居然setState的回调就执行了。这到底是什么情况？
代码如下：
![image](https://user-images.githubusercontent.com/34638158/56571422-7a99ce00-65ef-11e9-80e4-6592cff08210.png)

打印的结果如下：
![image](https://user-images.githubusercontent.com/34638158/56572219-3ad3e600-65f1-11e9-8296-4812770983e0.png)

求大佬搭救一下

**Comment by yuche** [comment]
Duplicate of #2855

**Comment by yuche** [comment]
请不要发重复的 issue
