### ISSUE TITLE
不同角色不同的tabbar

### ISSUE THREAD

**Issue by wang777777** [NervJS/taro#2872]
用微信小程序custom-tab-bar，不同的页面setData不同的list，数量也不同，这种实现方式当tabbar超过三个，在切换的时候icon会有闪烁，请问Taro官方有没有好的实现方式

**Comment by Chen-jj** [comment]
@wang777777 可以写个原生小程序 demo 测试一下是否也有问题。

**Comment by wang777777** [comment]
@Chen-jj 原生小程序也有这个问题的

**Comment by Chen-jj** [comment]
@wang777777 建议到微信小程序社区寻找一下解决办法

**Comment by wang777777** [comment]
@Chen-jj 根据角色不同，显示不同的导航，Taro 没有解决方案吗? 
https://github.com/NervJS/taro/issues/2723#issuecomment-481932028, 因为我看到这儿是有说在研究

**Comment by Chen-jj** [comment]
@wang777777 不是同一个问题吧，原生也有的问题我们解决不了
