### ISSUE TITLE
关于滚动条的问题

### ISSUE THREAD

**Issue by smallgold** [NervJS/taro#2874]
**问题描述**
关于滚动条的问题，在开发环境下读取不到window的滚动条高度，只能读取某个容器的滚动条，而在正式环境读取的又是window的滚动条，而且之前能够读取滚动条高度的dom没有了。导致函数报错

**复现步骤**
开发环境：
![图片](https://user-images.githubusercontent.com/16591041/56627931-7797ef80-667a-11e9-98a5-04d6efb65cd8.png)

正式环境：
![图片](https://user-images.githubusercontent.com/16591041/56627995-bf1e7b80-667a-11e9-85c3-633f0299855c.png)

```js
document.getElementsByClassName('taro-tabbar__panel')[0].scrollTop
```

**期望行为**
希望打包前和打包后的dom结构，样式尽量保证统一

**系统信息**

> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.22]
 - Node.js 版本 [e.g. v10.14.2]
 - 报错平台 [h5]

**Comment by Chen-jj** [comment]
可以使用 Taro2 或 3 再试试
