### ISSUE TITLE
Prop名为isActive时，值可能会是错的

### ISSUE THREAD

**Issue by nicholasxuu** [NervJS/taro#2876]
**问题描述**
如果一个component的prop名是 `isActive`，这个prop的值可能跟你设定的结果不同。

比如我在一个component的prop里设定了`isActive=true`，在`componentDidMount`的时候，`this.props.isActive`会显示为`false`，跟我设定的不同。

可能因为`isActive`是的reserved prop名，但是文档中没有注明。

**复现步骤**

简化版本：
```js
class A extends Component {
  ...
  render() {
    return <B isActive={true} />
  }
}

class B extends Component {
  componentDidMount() {
    console.log(this.props.isActive); // 有时会是false
  }
}

```

**期望行为**
如果无法避免，文档里注明别用`isActive`作prop。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.15 => 1.2.15
      @tarojs/components: 1.2.15 => 1.2.15
      @tarojs/mobx: 1.2.15 => 1.2.15
      @tarojs/mobx-h5: 1.2.15 => 1.2.15
      @tarojs/mobx-rn: 1.2.15 => 1.2.15
      @tarojs/plugin-babel: 1.2.15 => 1.2.15
      @tarojs/plugin-csso: 1.2.15 => 1.2.15
      @tarojs/plugin-less: 1.2.15 => 1.2.15
      @tarojs/plugin-uglifyjs: 1.2.15 => 1.2.15
      @tarojs/rn-runner: 1.2.15 => 1.2.15
      @tarojs/router: 1.2.15 => 1.2.15
      @tarojs/taro: 1.2.15 => 1.2.15
      @tarojs/taro-alipay: 1.2.15 => 1.2.15
      @tarojs/taro-h5: 1.2.15 => 1.2.15
      @tarojs/taro-swan: 1.2.15 => 1.2.15
      @tarojs/taro-tt: 1.2.15 => 1.2.15
      @tarojs/taro-weapp: 1.2.15 => 1.2.15
      @tarojs/webpack-runner: 1.2.15 => 1.2.15
      eslint-config-taro: 1.2.15 => 1.2.15
      eslint-plugin-taro: 1.2.15 => 1.2.15
      nervjs: ^1.3.9 => 1.3.12
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@nicholasxuu 升级到 v1.2.27-beta.0 再试试
