### ISSUE TITLE
从pages目录import非组件和样式文件，编译时都会被忽略。

### ISSUE THREAD

**Issue by 5468sun** [NervJS/taro#2878]
**问题描述**
native中引入dva。项目有很多 model 文件分布在不同的目录中。这些model文件统一通过一个model.js 文件export出来供dva初始化使用。问题是这个model.js经过编译后，内容不完整。

**复现步骤**
[复现问题的步骤]
1

以下是model.js文件
```js
import appGlobal from './appGlobal';
import ProductModel from '../pages/product/ProductModel';
import ProductIndexModel from '../pages/product/IndexModel';

export default [
  appGlobal,
  ProductModel,
  ProductIndexModel
]

```

编译之后变成了
```js
import appGlobal from './appGlobal';
// 原来引自其他目录的2个model消失了

export default [
  appGlobal,
  ProductModel,
  ProductIndexModel
]

```

**期望行为**
编译后生成的model.js 文件内容完整

**报错信息**
没有报错。

**系统信息**

 Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

**Comment by 5468sun** [comment]
补充说明：
ProductModel和IndexModel在pages目录才会复现这个问题。
此问题跟dva或者model都没有关系，只要尝试从pages目录中import非组件和样式文件，都会被忽略掉。
不知道是bug还是feature.

**Comment by shenghanqin** [comment]
为啥不放在公共组件里面呢？你是在Component里面调用Page的？
