### ISSUE TITLE
h5 canvas style属性失效

### ISSUE THREAD

**Issue by zWingz** [NervJS/taro#2880]
**问题描述**

h5端`canvas`组件style属性失效, 其实除了`class`以及内置事件外, 其他属性都失效
![image](https://user-images.githubusercontent.com/13031838/56657274-34fe0380-66ca-11e9-84d4-4d38d60c9acb.png)

**复现步骤**

```html
<View className='index'>
      <Text>Hello world!</Text>
      <Canvas my-data='fdsaf' canvasId='resultCanvas' style='width: 666px; height: 666px;' fdsaf={123}></Canvas>
</View>
```

**期望行为**
能正确设置`style`

**系统信息**
`tarojs@1.2.26`

**补充信息**
[canvas-file](https://github.com/NervJS/taro/blob/master/packages/taro-components/src/components/canvas/index.js)

目测没有把`props`中其余的属性添加到`wrapProps`下
![image](https://user-images.githubusercontent.com/13031838/56657418-8e663280-66ca-11e9-93fd-6b1cf814d4e4.png)

从代码来看, 是在`didMounted`阶段根据`wrapDom`的宽高来设置`canvas`宽高
这样的话, 修改宽高后无法反应到`canvas`中

**Comment by Littly** [comment]
有道理 目前的canvas组件只参考了小程序的文档来实现，有一些属性遗漏了
