### ISSUE TITLE
使用 addGlobalClass 会导致样式重复渲染

### ISSUE THREAD

**Issue by taichenglu** [NervJS/taro#2882]
正常组件渲染是这样的

![image](https://user-images.githubusercontent.com/3377075/56702855-b9876b00-6738-11e9-8315-844f887913a2.png)

用了 

```
static options = {
  addGlobalClass: true
}
```

发现变成这样了

![image](https://user-images.githubusercontent.com/3377075/56702890-e50a5580-6738-11e9-935f-906f1a4de5d9.png)

这是啥情况？有时还会重复更多。

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro/issues/1230#issuecomment-441446910

这是预期行为哈

**Comment by taichenglu** [comment]
@Garfield550 多谢，了解了，之前没搜到这个 issue :)
