### ISSUE TITLE
build后，自动去除了console.log

### ISSUE THREAD

**Issue by simbawus** [NervJS/taro#2885]
**问题描述**
yarn build:h5后，自动去除了console.log

**期望行为**
可以以某种方式保留console.log，例如：window.console.log，或者加了指定注释的console.log

**系统信息**

Taro CLI 1.2.22 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.22 => 1.2.22 
      @tarojs/components: 1.2.22 => 1.2.22 
      @tarojs/plugin-babel: 1.2.22 => 1.2.22 
      @tarojs/plugin-csso: 1.2.22 => 1.2.22 
      @tarojs/plugin-sass: 1.2.22 => 1.2.22 
      @tarojs/plugin-uglifyjs: 1.2.22 => 1.2.22 
      @tarojs/redux: 1.2.22 => 1.2.22 
      @tarojs/redux-h5: 1.2.22 => 1.2.22 
      @tarojs/router: 1.2.22 => 1.2.22 
      @tarojs/taro: 1.2.22 => 1.2.22 
      @tarojs/taro-alipay: 1.2.22 => 1.2.22 
      @tarojs/taro-h5: 1.2.22 => 1.2.22 
      @tarojs/taro-swan: 1.2.22 => 1.2.22 
      @tarojs/taro-tt: 1.2.22 => 1.2.22 
      @tarojs/taro-weapp: 1.2.22 => 1.2.22 
      @tarojs/webpack-runner: 1.2.22 => 1.2.22 
      eslint-config-taro: 1.2.22 => 1.2.22 
      eslint-plugin-taro: 1.2.22 => 1.2.22 
      nervjs: ^1.3.9 => 1.3.13 
      react: ^16.8.6 => 16.8.6

**补充信息**

由于yarn build:h5 是在production模式下进行的，可能是uglify配置的问题

**Comment by Littly** [comment]
taro默认不会移除console，检查下项目配置~

https://github.com/NervJS/taro/blob/301ee126f168c71396ce04b7cf23220863393b89/packages/taro-webpack-runner/src/util/chain.ts#L16-L25

文档在此 https://nervjs.github.io/taro/docs/config-detail.html#pluginsuglify

**Comment by simbawus** [comment]
我没对Uglify做任何附加配置，都是默认的。

```js
// prod.js
module.exports = {
  env: {
    NODE_ENV: '"production"'
  },
  defineConstants: {
  },
  weapp: {},
  h5: {
    /**
     * 如果h5端编译后体积过大，可以使用webpack-bundle-analyzer插件对打包体积进行分析。
     * 参考代码如下：
     * webpackChain (chain) {
     *   chain.plugin('analyzer')
     *     .use(require('webpack-bundle-analyzer').BundleAnalyzerPlugin, [])
     * }
     */
  }
}

```
