### ISSUE TITLE
h5 canvas.setFontSize失效

### ISSUE THREAD

**Issue by zWingz** [NervJS/taro#2886]
**问题描述**
h5端调用`cvs.setFontSize`失效

**复现步骤**

```js
const cvs = Taro.createCanvasContext('resultCanvas')
 cvs.setFontSize(48) // 失效
cvs.fillText('test', 0, 40)
cvs.font = '48px sans-serif' // 成功
cvs.fillText('testtest', 0, 80)
cvs.draw()
```

![image](https://user-images.githubusercontent.com/13031838/56706810-f0fe1380-6748-11e9-90c9-aca09a3751c7.png)

**系统信息**

`tarojs@1.2.26`

**补充信息**

h5的`canvas`设置字体需要通过
```js
cvs.font = '18px sans-serif`
```
设置, 并且要带上`font-family`

[源码](https://github.com/NervJS/taro/blob/master/packages/taro-h5/src/api/canvas/createCanvasContext.js#L81) 中只设了`font-size`, 没有设置`family`

如果通过`cvs.setFontSize('18px sans-serif')` 是可行, 但能否兼容小程序暂未测试

`ts`类型声明对于`cvs.font`设置为`function`, 但实际上并不是, [源码](https://github.com/NervJS/taro/blob/master/packages/taro/types/index.d.ts#L11384)

**Comment by Littly** [comment]
类型文件的问题... `font`应该是个字符串属性，不应该是`function`。需要设置字体的话，直接用font属性就ok。
`setFontSize`函数理论上是只能传数字的，不过h5端会直接将调用的参数传递给`font`属性，所以顺手设置个font-family也可以，不过如同你所说，小程序就不一定兼容了。

https://github.com/NervJS/taro/blob/301ee126f168c71396ce04b7cf23220863393b89/packages/taro-h5/src/api/canvas/createCanvasContext.js#L81-L83
