### ISSUE TITLE
react-native中使用hideLoading无法关闭loading

### ISSUE THREAD

**Issue by ineo6** [NervJS/taro#2887]
**问题描述**
在RN中使用Taro.hideLoading()无法隐藏加载内容

**复现步骤**
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
  deleteLoading: () => {
    Util.loadingCount--;
    if (Util.loadingCount === 0) {
      Taro.hideLoading();
    }
  },
```

**期望行为**
可以正常销毁loading

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.2
 - Taro 版本 1.2.25
 - Node.js 版本 10.15.3
 - 报错平台 [rn]

**补充信息**
[可选]
`taro/packages/taro-rn/src/api/WxToast/index.js` 文件里修改了`showToast`方法，但是`hideToast`调用未修改，关闭时不存在`global.wxToastRootSiblings`

```js
function hideToast () {
  global.wxToastRootSiblings && Toast.hide(global.wxToastRootSiblings)
  global.wxToastRootSiblings = undefined
}
```

![image](https://user-images.githubusercontent.com/3783838/56709037-bd73b700-6751-11e9-8972-1601beef0d69.png)

**Comment by Pines-Cheng** [comment]
感谢提醒～
