### ISSUE TITLE
public文件夹下的文件 是import或者css引用 才导入的吗？

### ISSUE THREAD

**Issue by pssgo** [NervJS/taro#2888]
**问题描述**

如果通过拼接路径，没有通过 import 或者 css引用图片 那么文件不会被拷贝到dist文件夹下，这个是这样设计的 还是一个bug那？

**复现步骤**
[复现问题的步骤]

```js
import Taro from '@tarojs/taro'
import { View, Image } from '@tarojs/components'

import "../../public/images/t1.jpg" // 如果我注释掉这一句 那么图片就没有被拷贝到dist下

import styles from './index.module.less'

export default class Swipe extends Taro.Component {

  state = {
    list: [
      '../../public/images/t1.jpg',
    ]
  }

  render() {
    return (
      <View>
        <View className={styles.list}>
          {this.state.list.map(item => {
            return <Image key={item} src={item} />
          })}
        </View>
      </View>
    )
  }
}

```
这是注释掉的效果
![image](https://user-images.githubusercontent.com/16378134/56710763-442c9200-675a-11e9-8eb7-c0f4ecdcae53.png)

这是未注释掉的效果
![image](https://user-images.githubusercontent.com/16378134/56710800-6faf7c80-675a-11e9-8714-26ec5d4deeef.png)

**期望行为**
可以正常的加载图片

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
👽 Taro v1.2.17

  Taro CLI 1.2.17 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v10.8.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.26 => 1.2.26
      @tarojs/components: 1.2.17 => 1.2.17
      @tarojs/mobx: 1.2.17 => 1.2.17
      @tarojs/plugin-babel: 1.2.17 => 1.2.17
      @tarojs/plugin-csso: 1.2.17 => 1.2.17
      @tarojs/plugin-less: 1.2.17 => 1.2.17
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17
      @tarojs/router: 1.2.17 => 1.2.17
      @tarojs/taro: 1.2.17 => 1.2.17
      @tarojs/taro-alipay: 1.2.17 => 1.2.17
      @tarojs/taro-h5: 1.2.17 => 1.2.17
      @tarojs/taro-swan: 1.2.17 => 1.2.17
      @tarojs/taro-weapp: 1.2.17 => 1.2.17
      @tarojs/webpack-runner: 1.2.17 => 1.2.17
      eslint-config-taro: 1.2.17 => 1.2.17
      eslint-plugin-taro: 1.2.17 => 1.2.17
      nervjs: ^1.3.5 => 1.3.9

**补充信息**
是否 可以通过 静态分析 url地址  或者 直接把public下的静态资源拷贝过去那？

**Comment by Littly** [comment]
就是这样设计的 如果有额外的需要copy的资源 用`copy`配置

https://nervjs.github.io/taro/docs/config-detail.html#copy
