### ISSUE TITLE
Taro CoverView 在 ios的支付宝小程序里 圆角被背景覆盖，把背0,景设置为rbga,可看到圆角

### ISSUE THREAD

**Issue by sutootototo2002** [NervJS/taro#2891]
**问题描述**

CoverView 在 ios的支付宝小程序里 圆角被背景覆盖，把背景设置为background:rgba(255, 255, 255, 0.01);可看到圆角
**复现步骤**
[复现问题的步骤]
1.  在后面添加
 ```<CoverView className='menus_avator' style=""></CoverView>```
2. .menus_avator{width:100%;height:40px;border-radius:35px;}
3. 用ios 手机 在支付宝小程序中看效果，不加背景会默认为白色，ios下是白色直角，android是透明的圆角
4. 希望赶紧修复这个bug
5.Canvas 层级不能在Map之上

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
<Map className='mb-map' id='mymap' show-location={this.state.showLocation} subkey={this.state.mapKey} latitude={this.state.latitude} longitude={this.state.longitude} scale={this.state.scale} controls={this.state.controls} onControlTap={this.onControlTap}/>
<CoverView className='menus_avator' style=""></CoverView>
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
这是支付宝小程序自身的问题

**Comment by sutootototo2002** [comment]
canvas能不能放在最高层级啊。android 的小程序不行，支付宝可以，哭

**Comment by HelloAndyZhang** [comment]
![image](https://user-images.githubusercontent.com/29533265/56843130-9b07a800-68cf-11e9-9e6a-a5db010d55e5.png)


> canvas能不能放在最高层级啊.android的小程序不行，支付宝可以，哭
