### ISSUE TITLE
H5: getCurrentPages如何获取来源页的完整路径(path + params)

### ISSUE THREAD

**Issue by catXiaoXiao** [NervJS/taro#2899]
**问题描述*
 const pageArr = Taro.getCurrentPages().filter(item => item)
 const prePage = pageArr[pageArr.length - 2]
  if (prePage && prePage['vnode']['_owner']['props']['path'] === preUrl) {
     Taro.navigateBack({ delta: 1 })
  }
发现path不是完整路径，不带params

**期望行为**
希望能获取完整来源路径

**系统信息**
Taro1.2.4

**Comment by catXiaoXiao** [comment]
来个人啊啊啊啊

**Comment by luckyadam** [comment]
这是 H5 么

**Comment by catXiaoXiao** [comment]
> 这是 H5 么

是h5，拿不到完整路径

**Comment by catXiaoXiao** [comment]
找到了！！在prePage['vnode']['_owner']['vnode']['props']['currentLocation']里，好长o(╥﹏╥)o
