### ISSUE TITLE
路由Taro.navigateTo指向不对

### ISSUE THREAD

**Issue by AlicePrincess** [NervJS/taro#29]
![image](https://user-images.githubusercontent.com/18545458/41140840-43a2129a-6b22-11e8-81ce-5dba2f732280.png)
![image](https://user-images.githubusercontent.com/18545458/41140847-4b9e45fe-6b22-11e8-8da9-fefe7540a905.png)
跳转的路由和代码中指定的路由路径不一致，不知道该如何解决

**Comment by missmimia** [comment]
===> url: '/pages/details/details' 
这样试一下，之前在小程序里遇到同样的，加个'/' 给解决了的。

**Comment by missmimia** [comment]
[参考下文档：](https://nervjs.github.io/taro/router.html)
是要加 '/' 的。

// 跳转到目的页面，打开新页面
Taro.navigateTo({
  url: '/pages/page/path/name'
})

// 跳转到目的页面，在当前页面打开
Taro.redirectTo({
  url: '/pages/page/path/name'
})
