### ISSUE TITLE
小程序中使用 redux 的子组件数据更新问题

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#290]
**问题描述**
以下仅为小程序端的问题，h5 未测试。
在 A 页面有子组件 C 使用了 redux，然后跳转到了 B 页面（没有子组件 C），在 B 页面更新了子组件 C 使用到的 store 数据，然后 navigateBack 回到 A 页面，发现 子组件 C 的渲染没有发生变化，然后其它点击交互更新了 A 页面的其它数据（与 redux无关，即 state ) ，即重新执行了 A 页面的 render ，子组件 C 的才执行了 render，数据才发生更改。
注：没有使用过 shouldComponentUpdate 

**复现步骤**
无

**期望行为**
子组件的 render 好像并没有受到 redux 的数据更新影响，只和使用它的页面 的 render 有关，
而在 h5 端，navigateBack 是会重新渲染一遍页面的，所以不会存在这个问题，
感觉小程序的页面栈和 redux 的使用有点问题，但又不能说是 bug , 请问这方面如何避免

**报错信息**
```js\
// 进入页面 A 
// 下面的这个为 子组件 C 的 render 函数写的 console.log(this.props.address)
AddressWithOrder.js:125 {addressList: Array(0), selectedAddressId: null}

// 此处为进入 A 页面后，子组件 C 自行执行 dispatch 更新的两个 action信息
 action SET_ADDRESS_LIST @ 10:25:27.340
redux-logger.js:1  prev state {address: {…}}
redux-logger.js:1  action     {type: "SET_ADDRESS_LIST", addressList: Array(5)}
redux-logger.js:1  next state {address: {…}}

redux-logger.js:1  action SELECT_ADDRESS @ 10:25:27.347
redux-logger.js:1  prev state {address: {…}}
redux-logger.js:1  action     {type: "SELECT_ADDRESS", id: "14"}
redux-logger.js:1  next state {address: {…}}

// 接着， 子组件 C 的 render 执行了
AddressWithOrder.js:125 {addressList: Array(5), selectedAddressId: "14"}

// 跳转到 B 页面后，页面 B 执行的两个 dispatch action
SET_ADDRESS_LIST @ 10:25:31.668
redux-logger.js:1  prev state {address: {…}}
redux-logger.js:1  action     {type: "SET_ADDRESS_LIST", addressList: Array(5)}
redux-logger.js:1  next state {address: {…}}

redux-logger.js:1  action SELECT_ADDRESS @ 10:25:32.832
redux-logger.js:1  prev state {address: {…}}
redux-logger.js:1  action     {type: "SELECT_ADDRESS", id: "35"}
redux-logger.js:1  next state {address: {…}}
// 以下为空，
// 跳转(navigateBack)回 A 页面，控制台也没有任何输出,
// 在 A 页面发生了交互，执行了 setState 后，子组件 C 的 render中的 console 执行了 
AddressWithOrder.js:125 {addressList: Array(5), selectedAddressId: "35"}
```

**系统信息**

 - 操作系统: windows7
 - Taro 版本 v0.0.68
 - Node.js 版本 v8.11.2

**Comment by luckyadam** [comment]
恩，这是之前一个设计上的考虑，当页面是 hide 的时候就不再更新这个页面的数据了，主要是为了一点点性能上的提升~

https://github.com/NervJS/taro/blob/master/packages/taro-redux/src/connect/connect.js#L24

可以讨论一下，看看这样的设计是否合理

**Comment by Dithub2016** [comment]
这就有点尴尬了，自定义组件是没有 `componentDidShow` 的方法的，那么返回到这个页面的时候，要想刷新组件的渲染，就只能把组件重新 `render` 逻辑提升到页面的 DidShow 上了，这样要么就让更多的数据重复渲染(比如 forceUpdate)，要么就耦合组件和页面的逻辑（比如使用 state 控制组件渲染）。
再者，小程序当中 onHide 的执行是得有点频繁的，在调用部分 api 的情况下，会触发页面的 onHide 和 onShow 操作，那么要优化这个性能还得再做更多的判断.
还有就是，需要让页面在返回的时候重新渲染一下，那么小程序是正常了，在 h5 端又会不会引入新的性能损耗呢，感觉这样会进一步扩大 h5 和 小程序的差异呢

**Comment by luckyadam** [comment]
嗯嗯，思考了一下，你说的有道理，我先把这个处理去掉

**Comment by luckyadam** [comment]
bf2fb6a
