### ISSUE TITLE
H5 的 Taro.request 的 GET 请求 querystring 参数的问题

### ISSUE THREAD

**Issue by qianzhaoy** [NervJS/taro#2901]
如果在 H5 里调用 request get请求.  data 如下.
```javascript
{
  data: {
     tags: [1,2,3]
  }
}
```
如果参数是个数组的情况下, 经过 request 方法的 `encodeURIComponent`, 会导致 `[`,`]`丢失. 接口就可能报错.

因为与小程序原生的 request 不一致, 是否是需要 `JSON.stringify`一次再 `encodeURIComponent`呢.

**Comment by luckyadam** [comment]
h5 的 request 里没有做 encodeURIComponent 操作啊

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/56858063-23a54780-69a7-11e9-83bb-647983f5bede.png)
大概是这样吧

**Comment by qianzhaoy** [comment]
是的
