### ISSUE TITLE
原生的小程序可以转换成taro继续维护吗？

### ISSUE THREAD

**Issue by Chad97** [NervJS/taro#2907]
最近接手了一个小程序，觉得写的太丑，原生的小程序可以一键转换成taro 继续维护吗？

**Comment by yuche** [comment]
可以，但是原来的代码就丑，转出来的代码也不会漂亮

**Comment by Chad97** [comment]
> 可以，但是原来的代码就丑，转出来的代码也不会漂亮

求老哥指点~ 刚接触taro，就是想用taro把上个人的 小程序项目维护下去

**Comment by yuche** [comment]
转成 Taro 只是模板变成了 JSX，生命周期换个名字，不会让你的代码一下就更可读了

**Comment by Chad97** [comment]
:smile: 好的我知道了大佬，我是一个喜欢瞎捣鼓的人，我想用taro 把之前的小程序继续写下去 是用 `$ taro convert` 吗？
官方有具体文档吗？

**Comment by yuche** [comment]
对

**Comment by Chad97** [comment]
> 转成 Taro 只是模板变成了 JSX，生命周期换个名字，不会让你的代码一下就更可读了

:smile: :smile: :smile: 好的我知道了大佬，我是一个喜欢瞎捣鼓的人，我想用taro 把之前的小程序继续写下去 是用 $ taro convert 吗？
官方有具体文档吗？  :yum:

**Comment by Chad97** [comment]
> 对

文档中找到了，谢谢大佬，调用taro-ui ，使用路由 Taro.redirectTo 的 AtTabBar 跳转后还是消失了,taro如何实现局部更新呢？

**Comment by yuche** [comment]
taro ui 的问题去 taro ui 提 issue
