### ISSUE TITLE
使用Hooks构建【函数式组件】，编译不通过

### ISSUE THREAD

**Issue by JohnPion-Zhang** [NervJS/taro#2909]
**问题描述**
使用Hooks构建函数式组件，编译不通过

**复现步骤**
[复现问题的步骤]
```js
// 以下是代码，并无其他依赖
import { useState, useEffect } from 'react'
import { View } from '@tarojs/components'
import {
  Dispatch,
  SetStateAction,
  FunctionComponent
} from 'react'

const Example: () => JSX.Element = () => {
  const handleSetCount: (previousCount: number) => number = previousCount  => {
    return previousCount +  1
  }
  const [ count, setCount ]: [ number, Dispatch<SetStateAction<number>> ] = useState(0)
  return <View onClick={() => setCount(handleSetCount) }>{{ count }}</View>
}

export default Example as FunctionComponent<{}>

```

**期望行为**
希望函数式组件能通过编译，能支持Hooks特性更好

**报错信息**

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/25896388/56859587-bd78ee80-69bf-11e9-9dba-b9e1037eb672.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

<img width="445" alt="image" src="https://user-images.githubusercontent.com/25896388/56859598-e00b0780-69bf-11e9-9195-a7eb1f177954.png">

**Comment by yuche** [comment]
1.3 才支持这个特性，你用法也不对

**Comment by JohnPion-Zhang** [comment]
> 1.3 才支持这个特性，你用法也不对

那么去掉hooks不说，**函数组件**在Taro该如何声明(TS)，才能通过编译。大神可否指点一下

**Comment by yuche** [comment]
1.3 才支持函数式组件

**Comment by JohnPion-Zhang** [comment]
Thx
