### ISSUE TITLE
请问H5 ，如何设置document.title，通过navigationBarTitleText好像不行

### ISSUE THREAD

**Issue by aokde** [NervJS/taro#291]
如题：
自己使用了一个变相了方法，在新页面中  
componentDidShow () {
    document.title = this.config.navigationBarTitleText;
   }
但是在回到上一页时，不能显示原来的，
如果框架能自己使用 navigationBarTitleText 就好了，希望官方采纳

**Comment by luckyadam** [comment]
嗯嗯，是想用 `navigationBarTitleText` 来实现替换 `title` ，不过还没来得及实现，后续版本会加入

**Comment by aokde** [comment]
谢谢回复，期待中！
请问有路由监听事件吗？就是路径变化就触发的事件？

**Comment by luckyadam** [comment]
恩，目前
`componentDidShow` 和 `componentDidHide` 主要就是扮演路由变化时的监听的

**Comment by luckyadam** [comment]
@aokde 666 啊，这也可以，不过 `setInterval` 还是会影响性能(꒦_꒦)

**Comment by aokde** [comment]
嘿嘿，我知道的，最开始使用的是原生事件监听，但是会有冲突（数组数据还没有变化就执行了）， 所以先临时使用以下，期待官方加入一个 路由事件，这样我们可以适应更多的场景

**Comment by tourze** [comment]
这个貌似还没有修复，希望能解决哈

**Comment by aokde** [comment]
@tourze 其实没必要处理，在每个页面的componentDidShow ()  中 设置一下 document.title  就可以了，把navigationBarTitleText的值 设置成独立的常量， navigationBarTitleText与 document.title  都等于它

**Comment by tourze** [comment]
我贴下我最终的解决方案吧。新建个 fixH5Title.js，内容是：

`

function fixH5Title() {

  return function (Component) {

    return class WithShare extends Component {

      componentDidShow() {
        if (process.env.TARO_ENV === 'h5') {
          if (this.config && this.config.navigationBarTitleText) {
            // 修复h5不支持title变更的问题
            document.title = this.config.navigationBarTitleText
          }
        }
        if (super.componentWillMount) {
          super.componentWillMount();
        }
      }

      render() {
        return super.render();
      }
    }
  };
}

export default fixH5Title;
`

在修复修复h5标题无效的地方使用：
`
@fixH5Title()
export default class Index extends Component {
  ...
}
`

即可。

感觉这个最好还是官方解决啊。。。这样fix不利于后续维护
