### ISSUE TITLE
父子通信 在父组件数据更新后 子组件时而可以接受到最新变化的值（导致子组件不更新渲染页面） 时而接受不到

### ISSUE THREAD

**Issue by candyZou** [NervJS/taro#2912]
**问题描述**
[问题描述：componentWillReceiveProps 生命周期,在子组件里时而执行，时而不执行。
 父子通信 在父组件数据更新后 子组件时而可以接受到最新变化的值（导致子组件不更新渲染页面） 时而接受不到
]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.23]
 - Node.js 版本 [e.g. v10.15.3]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
带上复现
