### ISSUE TITLE
build h5 安卓手机报错 'super' keyword unexpected here

### ISSUE THREAD

**Issue by 18978909244** [NervJS/taro#2913]
**问题描述**

H5 build出来
https://www.kuashou.com/warn-app/index.html#/pages/detail/index?task_id=16
在ios和电脑浏览器不会报错，
在安卓手机打开会报错

Uncaught SynctaxError:'super' keyword unexpected here

**复现步骤**

1. 安卓手机打开https://www.kuashou.com/warn-app/index.html#/pages/detail/index?task_id=16
2. 页面空白，点console调试
3. 看到报错信息

**期望行为**

正常运行

**报错信息**

'super' keyword unexpected here

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.2.26 environment info:
    System:
      OS: macOS High Sierra 10.13.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26
      @tarojs/components: 1.2.26 => 1.2.26
      @tarojs/plugin-babel: 1.2.26 => 1.2.26
      @tarojs/plugin-csso: 1.2.26 => 1.2.26
      @tarojs/plugin-less: 1.2.26 => 1.2.26
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26
      @tarojs/router: 1.2.26 => 1.2.26
      @tarojs/taro: 1.2.26 => 1.2.26
      @tarojs/taro-alipay: 1.2.26 => 1.2.26
      @tarojs/taro-h5: 1.2.26 => 1.2.26
      @tarojs/taro-swan: 1.2.26 => 1.2.26
      @tarojs/taro-tt: 1.2.26 => 1.2.26
      @tarojs/taro-weapp: 1.2.26 => 1.2.26
      @tarojs/webpack-runner: 1.2.26 => 1.2.26
      eslint-config-taro: 1.2.26 => 1.2.26
      eslint-plugin-taro: 1.2.26 => 1.2.26
      nervjs: ^1.3.9 => 1.3.12
    npmGlobalPackages:
      typescript: 3.1.1

**Comment by Littly** [comment]
这个super应该是来自你项目的其他依赖，检查下看看。目前taro在h5端的babel编译排除了node_modules目录。

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/311ffa53c1ae2b5e5f59020f488cbba37b198809 后续版本中，taro h5端处理不再排除node_modules目录 关键字`super`也将会被编译掉

**Comment by rockliuxn** [comment]
这个问题依然存在，在部分安卓机型上加载的时候，会报同样的错误，页面白屏！
@Littly  
在taro v3.0.26 版本中是否有对这个问题进行兼容处理？

``` bash
Taro CLI 3.0.26 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26
      @tarojs/mini-runner: 3.0.26 => 3.0.26
      @tarojs/react: 3.0.26 => 3.0.26
      @tarojs/router: 3.0.26 => 3.0.26
      @tarojs/runtime: 3.0.26 => 3.0.26
      @tarojs/taro: 3.0.26 => 3.0.26
      @tarojs/taro-h5: 3.0.26 => 3.0.26
      @tarojs/webpack-runner: 3.0.26 => 3.0.26
      babel-preset-taro: 3.0.26 => 3.0.26
      eslint-config-taro: 3.0.26 => 3.0.26
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

**Comment by GZWZC** [comment]
同样遇到这样的问题。

在部分安卓机型上加载的时候，会报同样的错误，页面白屏 @Littly
