### ISSUE TITLE
{process.env.TARO_ENV === 'weapp' && <ScrollViewWeapp />} 编译成微信小程序false未被忽略

### ISSUE THREAD

**Issue by GYDSB** [NervJS/taro#2914]
类似process.env.TARO_ENV环境判断，再支付宝小程序下可见，在微信小程序下期望是被忽略的但是仍显示为false ,

**Comment by Garfield550** [comment]
在 Taro 的 JSX 里写出类似 `{false}` 的语法是会被渲染出来的 #2798

你可以换一下写法

![image](https://user-images.githubusercontent.com/3471836/56863471-2cb70880-69e9-11e9-95c0-0a12ef3fa6ab.png)
![image](https://user-images.githubusercontent.com/3471836/56863474-32145300-69e9-11e9-92e9-2584d9edec6b.png)

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/2798
