### ISSUE TITLE
字节跳动，接收不到componentWillReceiveProps方法，导致子组件不更新

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#2918]
`import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import Son from './son'

import './index.css'

export default class Index extends Component {

  constructor() {
    super(...arguments)
    this.state = {
      name: 'aaaaaaa'
    }
  }
  componentDidShow() { 
    let self = this;
    setTimeout(() => {
      console.log('开始赋值')
      self.setState({
        name: '222222222'
      },()=>{
        console.log('赋值:',self.state.name)
      })
    }, 4000);
  }
  render() {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <View className='c' >
        <Son name={this.state.name}></Son>
        </View>
       
      </View>
    )
  }
  componentDidHide() { }

  
}
`

子组件：
`
import Taro , { Component }from '@tarojs/taro'
import {View, Text } from '@tarojs/components'

export default class Son extends Component {

    constructor(props) {
        super(props)
        console.log("父组件传值parms :", props);
        this.state = {
            name: '0000000'
        }
    }
    componentWillReceiveProps(prop) {
        let test = prop
        console.error('prop:::::', prop)
    }
    componentWillMount() { }

    componentDidShow() { }

    componentDidHide() { }

    componentDidCatchError() { }

    render() {
        return (
            <View className='page-wrap'>
                <Text style='width:200px;height:200px;background-color: #ffaa01;'>{this.state.name}</Text>
            </View>
        )
    }
}
`

现象：`componentWillReceiveProps`方法不执行，导致子组件不刷新

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/56874128-60864280-6a6a-11e9-8187-bae6ed5ed01e.png)

**Comment by fanlvwen** [comment]
同一份代码在微信、支付宝、百度中都能收到componentWillReceiveProps方法
只有头条不行，麻烦检查下编译成头条小程序是否存在问题？

**Comment by Chen-jj** [comment]
@fanlvwen 复现不了，升级到 v1.2.27-beta.0 再试试。

![image](https://user-images.githubusercontent.com/11807297/56940498-69961300-6b41-11e9-8c77-e93cf19a3116.png)

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Detail extends Component {
  constructor() {
    super(...arguments)
    this.state = {
      name: 'aaaaaaa'
    }
  }
  componentDidShow() {
    let self = this;
    setTimeout(() => {
      console.log('开始赋值')
      self.setState({
        name: '222222222'
      },()=>{
        console.log('赋值:',self.state.name)
      })
    }, 2000);
  }
  render() {
    return (
      <View className='index'>
        <View>Hello world!</View>
        <View className='c' >
        <Header name={this.state.name}></Header>
        </View>

      </View>
    )
  }
}
```

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Header extends Component {
  constructor(props) {
    super(props)
    console.log("父组件传值parms :", props);
    this.state = {
        myName: props.name
    }
  }

  componentWillReceiveProps(nextProps) {
      console.error('prop:::::', nextProps)
      this.setState({
        sub_name: nextProps.name
      })
  }

  render() {
    return (
      <View className='page-wrap'>
        <View style='width:200px;height:200px;background-color: #ffaa01;'>
          <View>state.myName: {this.state.sub_name}</View>
          <View>props.name: {this.props.name}</View>
        </View>
      </View>
    )
  }
}
```

**Comment by fanlvwen** [comment]
1.2.26依旧如此，我升级1.2.27试试
![image](https://user-images.githubusercontent.com/36951996/56949688-1da99500-6b66-11e9-97db-442626b5c03a.png)

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/56950776-da045a80-6b68-11e9-8aa8-db330237f04e.png)
@Chen-jj 
代码拷贝你 回复中的代码
taro以及依赖已经升级到最新，还是不行，我这是win7环境，我看你们调试使用mac，看来跟系统还有关系？

**Comment by Chen-jj** [comment]
@fanlvwen 父子组件编译后的 js 代码提供一下，v1.2.27-beat.0

**Comment by fanlvwen** [comment]
@Chen-jj 有点奇怪，之前1.2.26版本建的项目，测试失败，然后升级taro到1.3.0beta，再update project，还是不行（就用的你的代码），今天重新taro init一个项目，运行没问题了
这是我这边的复现步骤。我去对比对比package.json，你们照我的步骤，应该也能复现，因为我看issue里面 头条的子组件不更新不是个例。

**Comment by Chen-jj** [comment]
@fanlvwen node_moudles 删掉重新安装再试试。

**Comment by Chen-jj** [comment]
#2931
