### ISSUE TITLE
showToast 提示问题

### ISSUE THREAD

**Issue by mysky621** [NervJS/taro#2921]
场景：完成操作返回上一级。
旧的实现方式： 
Taro.showToast({title:'操作成功',icon:'none'});
Taro.navigateBack({delta: 1})
显示不提示，直接返回上级。
1.尝试下面方式，showToast 默认延时1500毫秒
  Taro.showToast({title:'操作成功',icon:'none', success: function(){
      Taro.navigateBack({delta: 1})
    }});
依然不提示，直接返回上一级
2.尝试下面方式
 Taro.navigateBack({delta: 1})
setTimeout(() => { Taro.navigateBack({delta: 1}) }, 1500);
效果正常实现。
个人感觉这块实现问题，showToast 默认延时失效了？

**Comment by Chen-jj** [comment]
@mysky621 请按照 issue 模板提供一切必要信息

**Comment by vimcaw** [comment]
这是微信小程序本身的问题，改下顺序，先返回上一页再弹出提示。
