### ISSUE TITLE
Taro.canvasToTempFilePath 百度小程序报错

### ISSUE THREAD

**Issue by Songyan992** [NervJS/taro#2923]
![C7ED7D6E-438D-4A6B-BEEB-8178F7F2A1D7](https://user-images.githubusercontent.com/19424910/56885712-af020400-6a9f-11e9-8f87-25c21faf6e36.png)

版本：Taro v1.2.26
百度小程序开发工具上编译

Taro.canvasToTempFilePath是否未支持百度小程序？

**Comment by Chen-jj** [comment]
@Songyan992 其实 Taro 只是调用了 `swan.canvasToTempFilePath` 而已，你可以直接调用看看报错是否一样，一样的话就看看百度的文档吧。

**Comment by Shalhvi** [comment]
开发工具会报错误202，但真机是调用成功的
