### ISSUE TITLE
Featuring Taro in Docusaurus

### ISSUE THREAD

**Issue by Hongarc** [NervJS/taro#2925]
Hello, we would like to feature your project to the Docusaurus users page.

Are you with me on this?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1080)

[Pull request](https://github.com/facebook/Docusaurus/compare/master...Hongarc:taro?expand=1)

**Comment by yuche** [comment]
It looks good to me. But you should make the pull request by yourself.
