### ISSUE TITLE
在自定义组件中引用 npm 原生第三方组件

### ISSUE THREAD

**Issue by kennylbj** [NervJS/taro#2926]
使用[f2-canvas](https://github.com/antvis/f2-canvas)中遇到了问题。

我自定义了一个``f2Canvas``组件，引用封装了第三方``f2-canvas``，按照文档编写如下：
```js
// components/f2Canvas

// index.js
Component({
  properties: {
    opts: Object,
  },
});

// index.json
{
  "component": true,
  "usingComponents": {
    // 发现此处无法引用第三方f2-canvas
    "ff-canvas": "@antv/f2-canvas"
  }
}

// index.wxml
<ff-canvas id="column-dom" canvas-id="column" opts="{{ opts }}"></ff-canvas>
```

在Page中引用该自定义组件时候，报错：
```js
// pages/result/index.js
class Result extends Component {
  config = {
    usingComponents: {
      'f2-canvas': '../../components/f2Canvas/index',
    },
  }
  render () {
    const opts = {
      onInit: this.initChart,
    };
    return (
      <View className='page'>
        <View className='doc-body bg'>
          <View className='panel'>
            <f2-canvas opts={opts} />
          </View>
        </View>
      </View>
    )
  }
}
```
``
Component is not found in path "components/f2Canvas/@antv/f2-canvas" (using by "components/f2Canvas/index");onAppRoute
Error: Component is not found in path "components/f2Canvas/@antv/f2-canvas" (using by "components/f2Canvas/index")
``

查看了dist/npm，发现没有@antv/f2-canvas目录。

请问如何在自定义组件中引用第三方的原生组件（需要通过npm安装的原生组件）？还是我的用法有问题，谢谢了。

**Comment by Garfield550** [comment]
暂不支持 npm 方式引入原生组件

![image](https://user-images.githubusercontent.com/3471836/56936835-1cf40d00-6b2c-11e9-892d-1832a2b84698.png)

我自己是用 clone 到本地的形式做的

**Comment by kennylbj** [comment]
@Garfield550 很蓝瘦，希望早点支持。😖

**Comment by cloudZQY** [comment]
还是希望能支持直接引用npm第三方原生组件。因为我们团队是从wepy迁移过来的，有些业务类的组件希望能兼容，所以使用原生开发。只能用拷贝的形式的话，会很影响各团队对组件的同步。

**Comment by shenghanqin** [comment]
@kennylbj 试试看最新版？或者看看Changelog？

**Comment by guxinyan** [comment]
这个现在在taro3中支持了吗
