### ISSUE TITLE
sass plguin 注入变量失效

### ISSUE THREAD

**Issue by mgsers** [NervJS/taro#2929]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**

配置文件中，参考dart-sass 文档，配置sass注入env变量失效

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// config.js
plugins: {
    sass: {
      data: "$env: " + process.env.NODE_ENV + ";"
    }
 }
```
```scss
// index.scss
p {
  @if $env == 'development' {
    color: blue;
 } 
}
```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Garfield550** [comment]
@mgsers 你好，在 1.3.21 下测试，sass 变量可以传入

![image](https://user-images.githubusercontent.com/3471836/67472161-46c56100-f683-11e9-8d54-8dd47c04ca1a.png)

编译结果：

```css
.index{content:production}
```
