### ISSUE TITLE
如果实现页面级的onBack事件，好像没有找到对应的api。

### ISSUE THREAD

**Issue by glivia** [NervJS/taro#2933]
我看支付宝小程序是有对应的方法的。

**Comment by Chen-jj** [comment]
@glivia 看了下好像只有支付宝的 Page 构造器有实现此 onBack 事件，其它小程序并没有这个特性。其实页面 onShow 不就可以满足你需求了吗。

**Comment by glivia** [comment]
如果要监听单个页面的onBack事件，然后实现挽留弹窗这样的效果，现在是不是不支持？

**Comment by Chen-jj** [comment]
@glivia onShow、onHide 不就 ok 了吗

**Comment by glivia** [comment]
sorry，没太明白你的意思，如果用onHide，能阻止页面返回？

**Comment by Chen-jj** [comment]
@glivia onBack 又能阻止页面返回？

**Comment by glivia** [comment]
能啊，配合页面的event.preventDefault能阻止页面返回。

**Comment by purocean** [comment]
> 能啊，配合页面的event.preventDefault能阻止页面返回。

现在实测不能阻止返回，只能监听返回事件
