### ISSUE TITLE
VS code 提示找不到模块，但编译使用都正常

### ISSUE THREAD

**Issue by imWayneWY** [NervJS/taro#2937]
微信小程序， TypeScript开发

在Problems Panel中提示：

```Cannot find module '@tarojs/taro'.```

但编译没问题。
很奇怪，同级别其它文件夹不报错，只有新加入的组件中会报错。

例如：
同样的引入： 
```
import Taro , { PureComponent } from '@tarojs/taro‘
```
```
\client\src\components\CategaryList\CategaryList.tsx   //报错（新加入的组件）
\client\src\components\ItemList\ItemList.tsx   //不报错
```
是ESlint的问题吗？

编译可以通过，只是报错一直提示看着闹心

**Comment by yuche** [comment]
如果编译没问题，那就是编辑器的问题，taro 也没有很好办法解决

**Comment by coderafei** [comment]
应该是同时使用npm和yarn造成的，删了node_modules用yarn重新安装一遍就好了
