### ISSUE TITLE
请教一个问题：应该怎么获取 config/下的配置

### ISSUE THREAD

**Issue by cmzz** [NervJS/taro#2938]
需求是这样的：
在本地开发的时候想定一个测试的 api_url

我尝试放到 config/dev.js 下，但是不知道怎么读取出来。 

请大佬指点下

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#defineconstants
设置了之后直接用

**Comment by kokiy** [comment]
![image](https://user-images.githubusercontent.com/15773714/87444667-a573a600-c629-11ea-9bf2-4b654657d287.png)
@cmzz   然后 在项目中直接引用
