### ISSUE TITLE
编译react-lazyload无限循环，导致node栈溢出

### ISSUE THREAD

**Issue by zytjs** [NervJS/taro#2943]
**问题描述**
使用`yarn dev:weapp`时，`react-lazyload`依赖的`index.js`、`decorator.js`文件，无限循环编译，导致node栈溢出。

**复现步骤**
[复现问题的步骤]
1. `yarn add react-lazyload`
2. `import LazyLoad from 'react-lazyload';`
3. 下面是使用方式，不过应该用不到，运行`yarn dev:weapp`时就会无限循环，直到node栈溢出。
```jsx
<LazyLoad>
  <img src="图片链接" />
</LazyLoad>
```

**期望行为**
正常编译

**报错信息**

...
编译  组件文件  node_modules/react-lazyload/lib/decorator.js
编译  组件文件  node_modules/react-lazyload/lib/index.js

<--- Last few GCs --->

[30832:0x103800000]    58496 ms: Scavenge 1382.2 (1426.6) -> 1375.7 (1429.1) MB, 7.3 / 0.0 ms  (average mu = 0.113, current mu = 0.057) allocation failure
[30832:0x103800000]    58551 ms: Scavenge 1383.4 (1429.1) -> 1375.9 (1431.1) MB, 5.4 / 0.0 ms  (average mu = 0.113, current mu = 0.057) allocation failure
[30832:0x103800000]    58607 ms: Scavenge 1383.5 (1431.1) -> 1376.6 (1433.6) MB, 7.9 / 0.0 ms  (average mu = 0.113, current mu = 0.057) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3a29a33dbe3d]
    1: StubFrame [pc: 0x3a29a33934b0]
Security context: 0x16fad1b1e6e1 <JSObject>
    2: walker [0x16fa3ccddfe1] [/usr/local/lib/node_modules/@tarojs/cli/node_modules/traverse/index.js:~116] [pc=0x3a29a3a35cd4](this=0x16fab521ad11 <JSGlobal Object>,node_=0x16fa3cceb1f9 <Object map = 0x16fad805d959>)
    3: walk [0x16fadd4f3bc9] [/usr/local/lib/node_modules/@tarojs/cli/node_modules/traverse/index.js:22...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003b125 node::Abort() [/usr/local/bin/node]
 2: 0x10003b32f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001a89a5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100573dc2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100576895 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x10057273f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x100570914 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10057d1ac v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10057d22f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10054cb74 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: 0x1007d4a44 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x3a29a33dbe3d
/var/folders/f_/ghrchd6s26d_k3brkjrdwd3m0000gn/T/yarn--1556961329203-0.7454922291905037/node: line 3: 30832 Abort trap: 6           "/usr/local/bin/node" "$@"
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! taro@1.0.0 build:weapp: `taro build --type weapp "--watch"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the taro@1.0.0 build:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aibota/.npm/_logs/2019-05-04T09_16_30_755Z-debug.log
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation abo

**系统信息**

System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.20 => 1.2.20
      @tarojs/components: 1.2.15 => 1.2.15
      @tarojs/plugin-babel: 1.2.15 => 1.2.15
      @tarojs/plugin-csso: 1.2.15 => 1.2.15
      @tarojs/plugin-less: 1.2.15 => 1.2.15
      @tarojs/plugin-uglifyjs: 1.2.15 => 1.2.15
      @tarojs/router: 1.2.15 => 1.2.15
      @tarojs/taro: 1.2.15 => 1.2.15
      @tarojs/taro-alipay: 1.2.15 => 1.2.15
      @tarojs/taro-h5: 1.2.15 => 1.2.15
      @tarojs/taro-swan: 1.2.15 => 1.2.15
      @tarojs/taro-tt: 1.2.15 => 1.2.15
      @tarojs/taro-weapp: 1.2.15 => 1.2.15
      @tarojs/webpack-runner: 1.2.15 => 1.2.15
      eslint-config-taro: 1.2.15 => 1.2.15
      eslint-plugin-taro: 1.2.15 => 1.2.15
      nervjs: ^1.3.9 => 1.3.12
    npmGlobalPackages:
      typescript: 3.2.4

**补充信息**

**Comment by Garfield550** [comment]
Taro 不支持使用原生 React 组件，也不支持 `<div></div>` 这些原生 HTML 元素，如果必须使用 react-lazyload 的话可以尝试使用 Nerv 封装一下，可以参照 Taro Components 的源代码 https://github.com/NervJS/taro/blob/master/packages/taro-components/src/components/image/index.js

https://github.com/twobin/react-lazyload/blob/f9ec624a46559b359983f489febfb06807707bc2/src/index.jsx#L271-L278

**Comment by bwor** [comment]
How to solve this problem
