### ISSUE TITLE
使用mobx报错 Please pass a valid component to 'observer' 

### ISSUE THREAD

**Issue by mushan0x0** [NervJS/taro#2949]
**问题描述**

用了mbox报错`Please pass a valid component to 'observer' `，点击报错的组件随便改一下又可以跑成功了

**复现步骤**

对比了两次编译结果的不同地方，右边是正常能运行的
![image](https://user-images.githubusercontent.com/29084441/57190175-40fb8800-6f4a-11e9-9c1c-36b5eefd0517.png)

**期望行为**

正常编译

**报错信息**

![image](https://user-images.githubusercontent.com/29084441/57190200-69838200-6f4a-11e9-97d0-d1fe32bf7e20.png)

**系统信息**

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.6.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/mobx: 1.2.26 => 1.2.26 
      @tarojs/mobx-h5: 1.2.26 => 1.2.26 
      @tarojs/mobx-rn: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-less: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/rn-runner: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
    npmGlobalPackages:
      typescript: 2.8.1

**Comment by Garfield550** [comment]
你给官方上一下复现代码呀
