### ISSUE TITLE
Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by fandebiao12345** [NervJS/taro#295]
这啥玩意  出现好几次 都不知道哪错了

**Comment by yuche** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mistycarlyle31** [comment]
Misty n aj
