### ISSUE TITLE
Taro cli 编译问题

### ISSUE THREAD

**Issue by CPPAlien** [NervJS/taro#2952]
**问题描述**
通过 Taro 编译，`nsPrefix = qName === 'xmlns' && ''` 会被翻译成 `nsPrefix = undefined;`

**期望行为**
应该翻译成： `nsPrefix = ''`;

**报错信息**
![image](https://user-images.githubusercontent.com/4279515/57194004-f858c480-6f73-11e9-84d3-f25e5f0bfb97.png)

**系统信息**
 Taro v1.2.26
  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v9.8.0/bin/node
      Yarn: 1.6.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v9.8.0/bin/npm
    npmPackages:
      @tarojs/components: 1.2.26 => 1.2.26
      @tarojs/plugin-babel: 1.2.26 => 1.2.24
      @tarojs/plugin-csso: 1.2.26 => 1.2.24
      @tarojs/plugin-sass: 1.2.26 => 1.2.26
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.24
      @tarojs/router: 1.2.26 => 1.2.24
      @tarojs/taro: 1.2.26 => 1.2.24
      @tarojs/taro-alipay: 1.2.26 => 1.2.24
      @tarojs/taro-h5: 1.2.26 => 1.2.24
      @tarojs/taro-swan: 1.2.26 => 1.2.24
      @tarojs/taro-tt: 1.2.24 => 1.2.24
      @tarojs/taro-weapp: 1.2.26 => 1.2.24
      @tarojs/webpack-runner: 1.2.26 => 1.2.24
      eslint-config-taro: 1.2.26 => 1.2.24
      eslint-plugin-taro: 1.2.26 => 1.2.24
      nervjs: ^1.3.9 => 1.3.13

**Comment by yuche** [comment]
没能复现，把你这个函数一起贴出来把

**Comment by CPPAlien** [comment]
内容是环信 sdk，https://github.com/easemob/webim-weixin-xcx，放在 taro 中后，会出错
