### ISSUE TITLE
1.3.0-beta.0 转换微信小程序为支付宝小程序，报错：TypeError: Cannot read property 'onTaroCollectChilds' of undefined

### ISSUE THREAD

**Issue by snimstice** [NervJS/taro#2954]
**问题描述**
1.3.0-beta.0将微信小程序转换为支付宝小程序，所有taro依赖版本号也为1.3.0-beta,0，在支付宝小程序开发者工具中无法打开项目，报错：TypeError: Cannot read property 'onTaroCollectChilds' of undefined

**复现步骤**
1. 更新taro至1.3.0-bata.0
2. 进入微信小程序根目录运行 taro convert 
3. 进入编译好的文件中 npm install 
4. 依赖项安装好以后 npm run build:alipay
5. 使用支付宝小程序开发者工具打开dist/alipay报错

打包后的代码：https://github.com/snimstice/alipay-dist
**期望行为**
可以正常打开

**报错信息**

![image](https://user-images.githubusercontent.com/23273812/57204356-dc900580-6fe9-11e9-9e04-e855db89b449.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0-beta.0]
 - Node.js 版本 [e.g. v10.15.3]
 - 报错平台 [支付宝小程序]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@snimstice 参考一下这个issue #2802 ，如果继承了基类，constructor 中 super 的参数要注意。
