### ISSUE TITLE
networkTimeout 配置支持支付宝

### ISSUE THREAD

**Issue by shaodahong** [NervJS/taro#2956]
`networkTimeout` 目前只支持微信小程序，`request` 方法也没看到支持 `timeout` 配置，支付宝的 `request` 是支持 `timeout` 的，这块能不能做个兼容

**Comment by Chen-jj** [comment]
@shaodahong 试试使用内置拦截器 [Taro.interceptors.timeoutInterceptor](https://nervjs.github.io/taro/docs/native-api.html#%E6%8B%A6%E6%88%AA%E5%99%A8)

**Comment by shaodahong** [comment]
好的
