### ISSUE TITLE
引入本地data.json报错

### ISSUE THREAD

**Issue by jiangyh123** [NervJS/taro#2961]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：我升级成1.3.0的时候，我在本地放了一个正确的json，在项目页面中引入时，显示错误，json是正确的json,在没有升级之前，我这段代码是好的，数据也展示出来了，没有报错]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js


![image](https://user-images.githubusercontent.com/33273887/57209622-b3806c80-700b-11e9-861f-e5fb3d9b887b.png)


**期望行为**
就是将json数据展示出来

**报错信息**

![image](https://user-images.githubusercontent.com/33273887/57209641-cb57f080-700b-11e9-9df0-0546221cfa11.png)


**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [ Taro v1.3.0-beta.0]
 - Node.js 版本 [ v10.15.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Garfield550** [comment]
**期望行为**
就是将json数据展示出来

**报错信息**

![image](https://user-images.githubusercontent.com/33273887/57209641-cb57f080-700b-11e9-9df0-0546221cfa11.png)

**Comment by 378978764** [comment]
有可能是因为更新之后，小程序的根目录变成了`dist/weapp`，修改一下试试？
