### ISSUE TITLE
Picker 在RN的运行环境下无法正常使用

### ISSUE THREAD

**Issue by yazakid** [NervJS/taro#2962]
Picker 在h5的情况下可以正常使用，转成RN就无法正常使用
只能这样处理一下在IOS上使用，and上依然无解。。。
`import { Picker as RNPicker, DatePickerIOS } from 'react-native';`

**Comment by Pines-Cheng** [comment]
无法正常使用指的是什么，有报错？ @yazakid

**Comment by yazakid** [comment]
点击无反应，在h5上正常




| |
yazaky
邮箱：15012992791@163.com
|

Signature is customized by Netease Mail Master

在2019年05月06日 20:11，Pines 写道：

无法正常使用指的是什么，有报错？ @yazakid

**Comment by Pines-Cheng** [comment]
贴一下 RN 的代码？

**Comment by yazakid** [comment]
``import Taro, { Component } from '@tarojs/taro'
import { View, Text, Picker } from '@tarojs/components'

export default class PagePicker extends Component {
  state = {
    selector: ['美国', '中国', '巴西', '日本'],
    selectorChecked: '美国',
    timeSel: '12:01',
    dateSel: '2018-04-22'
  }

  onChange = e => {
    this.setState({
      selectorChecked: this.state.selector[e.detail.value]
    })
  }

  onTimeChange = e => {
    this.setState({
      timeSel: e.detail.value
    })
  }
  onDateChange = e => {
    this.setState({
      dateSel: e.detail.value
    })
  }

  render () {
    return (
      <View className='container'>
        <View className='page-body'>
          <View className='page-section'>
            <Text>地区选择器</Text>
            <View>
              <Picker mode='selector' range={this.state.selector} onChange={this.onChange}>
                <View className='picker'>
                  当前选择：{this.state.selectorChecked}
                </View>
              </Picker>
            </View>
          </View>
          <View className='page-section'>
            <Text>时间选择器</Text>
            <View>
              <Picker mode='time' onChange={this.onTimeChange}>
                <View className='picker'>
                  当前选择：{this.state.timeSel}
                </View>
              </Picker>
            </View>
          </View>
          <View className='page-section'>
            <Text>日期选择器</Text>
            <View>
              <Picker mode='date' onChange={this.onDateChange}>
                <View className='picker'>
                  当前选择：{this.state.dateSel}
                </View>
              </Picker>
            </View>
          </View>
        </View>
      </View>
    )
  }
}

就是官方的示例，用run dev:rn 跑出来在手机上无法点击

**Comment by Manjiz** [comment]
给文字套 `<Text />`

**Comment by Dssssds** [comment]
@Manjiz  嵌套了Text ，还是不行呀。RN上一点作用没有。
