### ISSUE TITLE
h5打包成APP在低版本Android下显示空白

### ISSUE THREAD

**Issue by beehoo** [NervJS/taro#2963]
**问题描述**
将Taro创建的项目打包成h5，再用hbuilder打包成app，在低版本安卓机（测试机Android 5.0）下打开空白，错误信息：this.customRoutes.find is not a function

**复现步骤**
1. 创建Taro项目并打包成H5
2. 用HBuilder打包成APP
3. 打开显示空白，查看错误日志显示：this.customRoutes.find is not a function

**期望行为**
低版本Android下能正常运行

**报错信息**
this.customRoutes.find is not a function

**系统信息**
 - 操作系统: [Android 5.1.1]
 - Taro 版本 [e.g. v.1.2.26]
 - Node.js 版本 [e.g. v10.0.0]
 - 报错平台 [h5]

**补充信息**
浏览器版本：chrome   43.0.2357.121
低版本安卓机自带浏览器打开好像也有问题，显示空白

**Comment by luckyadam** [comment]
可以试一下 1.3.0 的 beta 版本，解决了这个问题

**Comment by beehoo** [comment]
> 可以试一下 1.3.0 的 beta 版本，解决了这个问题

试了还是存在这个问题

**Comment by liminshen** [comment]
Array.prototype.find = Array.prototype.find || function(fn){
    fn&&fn(this[this.findIndex()] || -1)
}

**Comment by hutaoer** [comment]
现在使用的Taro 2.2.6 版本，在 安卓 5.1.1 版本上，也是展示空白。这个bug，官方后面会修复吗？
