### ISSUE TITLE
Taro1.3由于重构props，导致props传递的函数中获取的this实例，由父组件变成了props。

### ISSUE THREAD

**Issue by 378978764** [NervJS/taro#2965]
## 问题描述：
比方说有一个组件A，里面放了组件B，绑定了`onSuccess`这个函数，写法如下：
```
// 组件A
onSuccess (this) {
console.log(this)
}
// render
<B onSuccess={this.onSuccess}/>


// 组件B
<View onClick={this.props.onSuccess}></View>
```
那么点击B的时候，在A中打印的却是传递的props，并非组件了。

## 提出问题
1、重构之后如何获得父组件实例
2、如果项目中大量使用了先前的方法访问父组件的this, 岂不是需要全部重构？

**Comment by 378978764** [comment]
最新进展：发现升级`1.3.0`之后，所有都必须要显式地绑定当前页面的`this`了。
之前的版本给组价绑定一个事件，可以简写为：
```js
<Child onSuccess={this.onSuccess}/>
```
需要绑定参数的时候，才需要`bind`：
<Child onSuccess={this.onSuccess.bind(this, 'hello')} />
更新到`1.3.0`之后，所有的都需要绑定，不管函数是否需要传递参数：
<Child onSuccess={this.onSuccess.bind(this)} />

**Comment by luckyadam** [comment]
需要绑定才是正确的，和 react 保持一致的
