### ISSUE TITLE
[1.3.0] taro-cli的postcss跟stylelint版本冲突问题

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#2968]
**问题描述**

@tarojs/cli依赖了：

```
    "postcss": "^6.0.22",
    "stylelint": "^9.10.1",
```

这里的 stylelint 依赖了 postcss v7

在执行npm run dev:rn时，如果样式不标准，会报错：

![image](https://user-images.githubusercontent.com/13899502/57230121-358f8600-704a-11e9-80fc-96e9317f03b5.png)

**复现步骤**
升级到taro v1.3.0-beta

**期望行为**
显示具体的stylelint检测结果

**报错信息**
![image](https://user-images.githubusercontent.com/13899502/57230121-358f8600-704a-11e9-80fc-96e9317f03b5.png)

**Comment by Pines-Cheng** [comment]
Duplicate of #2934
