### ISSUE TITLE
video组件在安卓手机上有问题

### ISSUE THREAD

**Issue by yarayao** [NervJS/taro#2971]
**问题描述**
 video组件在安卓手机上层级太高，无法遮挡；全屏播放时会自动从头开始；视频比较窄时进度条显示有问题

**复现步骤**
[复现问题的步骤]

```js


// 这里可以贴代码

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
有什么解决方法？

**报错信息**
以下是遮挡和进度条问题截图
![2b8861dfca02e8b63c3573ad8198f23](https://user-images.githubusercontent.com/19224441/57266894-9fdb1180-70b0-11e9-831b-dafb4828fe76.jpg)
![343a95662870bf151327277e3998667](https://user-images.githubusercontent.com/19224441/57266898-a2d60200-70b0-11e9-9d6b-5cbf82084e84.jpg)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 v.1.2.26
 - Node.js 版本 v8.9.0
 - 报错平台 h5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
只有 H5 是这样么

**Comment by yarayao** [comment]
> 只有 H5 是这样么

目前只是编译了H5，其他端没有注意
