### ISSUE TITLE
Taro.pxTransform H5端不加单位自动添加rem

### ISSUE THREAD

**Issue by innocces** [NervJS/taro#2972]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**使用Taro.pxTransform(), 转化数字类的，在小程序端解析为不加参数的，在H5端会自动加上rem**

**复现步骤**
[复现问题的步骤]
```js
<ScrollView
          className='home__game'
          scrollX
          scrollWithAnimation
          scrollLeft={ Taro.pxTransform(630) }
        >
   <View></View>
</ScrollView>
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
在小程序端scrollLeft属性正确解析为315（Number）
![image](https://user-images.githubusercontent.com/38065966/57268020-cbf89180-70b4-11e9-9e34-c790fcc13a40.png)
在H5端由于解析自带了rem，所以scrollLeft属性不生效(暂时直接写了数字代替了)
![image](https://user-images.githubusercontent.com/38065966/57268025-d2870900-70b4-11e9-9f14-2d09d20279cf.png)
**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/38065966/57268059-f34f5e80-70b4-11e9-93da-2a5877804bdc.png)
![image](https://user-images.githubusercontent.com/38065966/57268090-0d893c80-70b5-11e9-9ba4-b6cd2d7f3cbd.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本  v.1.2.26
 - Node.js 版本  v10.15.1
 - 报错平台 H5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
这个应该是 H5 ScrollView 组件 scrollLeft 参数的问题

**Comment by jinjinjin0731** [comment]
@innocces  其实 Taro.pxTransform 这个方法，解析出来的都会是带单位的。 scrollLeft 在小程序中可以用带单位的字符串，实际上是在小程序基础库 2.4.0 以上支持了传入字符串。  所以这里的传参还是尽量使用数字吧，带单位的写法后续兼容一下。   你也可以来个 PR :)

**Comment by Garfield550** [comment]
小程序带单位字符串的... 我反倒比较好奇为什么你小程序里的 `scrollLeft` 是纯数字

![image](https://user-images.githubusercontent.com/3471836/57282536-d8461400-70df-11e9-8137-d2ba42a4622a.png)

```tsx
const progressBarStyle = {
  height: strokeWidth && Taro.pxTransform(+strokeWidth),
};

<View style={progressBarStyle}></View>
```
