### ISSUE TITLE
h5 路由bug

### ISSUE THREAD

**Issue by catXiaoXiao** [NervJS/taro#2976]
**问题描述**
redirectTo打开的page用Taro.getCurrentPages()获取不到！！！

**复现步骤**
页面跳转：A <=> B
B当前页F5刷新，用Taro.redirectTo（A），A再用navigateTo（B）后B再次返回A时：
const pageArr = **Taro.getCurrentPages()**.filter(item => item)
const prePage = pageArr[pageArr.length - 2]
prePage['vnode']['_owner']['vnode']['props']['currentLocation']['path'] + prePage['vnode']['_owner']['vnode']['props']['currentLocation']['search'] 不等于上一页A路由！！！

**期望行为**
请尽快修复bug谢谢

**系统信息**
Taro1.2.4

**Comment by luckyadam** [comment]
你先升级到最新的正式版本，或者最新的 beta 版本试试吧
