### ISSUE TITLE
reLaunch后state变了，但是到界面没更新

### ISSUE THREAD

**Issue by spirke** [NervJS/taro#2977]
Taro.reLaunch({
      url: '/pages/Scan/index',
      success:()=>{
        this.setState({
          test:true,
        })
        setTimeout(()=>{
          console.log(this.state.test)
        },1)
      }
    })  
界面代码：<View>{test}</View>，但是界面显示一直为：false

**Comment by vimcaw** [comment]
请补充平台、Taro版本等重要信息

**Comment by spirke** [comment]
微信小程序，taro版本1.2.12

**Comment by Garfield550** [comment]
先更新到 1.2.26 试试看？

**Comment by spirke** [comment]
更新到最新版本无效

**Comment by Chen-jj** [comment]
@spirke 正常现象。你在页面的生命周期打些 log 就清楚了，reLaunch 会卸载当前页面，重新加载新页面。意即会经历当前页面 detached(componentWillUnmount)，新页面 onLoad(componentWIllMount)。

你在 `Taro.reLaunch` 的 success 回调调用绑定了旧页面对象的 setState，肯定不会反映到新页面的视图上。

事实上 success 回调不应该再调用 setState，因为页面马上就要 unmount。

**Comment by spirke** [comment]
原本的问题是：在relaunch后sock接受到数据，然后根据数据去修改state，界面不更新；
请教下怎么在relaunch后更新界面
