### ISSUE TITLE
构建 h5 时会删除  dist 目录

### ISSUE THREAD

**Issue by yesmeck** [NervJS/taro#2978]
**问题描述**

`taro build --type h5 --watch` 会删除 dist 目录。

**复现步骤**

1. 运行 `npm run dev:alipay`
2. 运行 `npm run dev:h5`

h5 的构建会导致 dist 被删除，小程序无法启动。

**期望行为**

不删除 dist

**报错信息**

无
**系统信息**

```javascript
Taro v1.3.0-beta.0
```

**Comment by yesmeck** [comment]
https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/h5/index.ts#L119

在这被删

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/85cc143cd4fe0defb0d809695728737e68230c18 可以试试 beta.1版本 已经不存在这个问题
