### ISSUE TITLE
react-redux connect 第二个参数使用对象时，在微信小程序无效

### ISSUE THREAD

**Issue by buf1024** [NervJS/taro#298]
**问题描述**
react-redux `connect` 第二个参数使用对象时，在微信小程序无效。
react-redux `connect` 的原型为：  
```js
connect([mapStateToProps], [mapDispatchToProps], [mergeProps], [options])
```
其中第二个参数可接受对象或函数，当接受对象是，对象元素为action creator的函数。
传参为对象时，在**微信小程序**是无效的，在**h5**中中没有问题

**复现步骤**

参考代码(在**微信小程序**是无效的，在**h5**中中没有问题):
```js
const mapStateToProps = (state) => {
  return {
    counter: state.user
  }
}

export default connect(mapStateToProps, {
  add: usrAct.userAdd,
  dec: usrAct.userMinus,
  asyncAdd: usrAct.userAsyncAdd.request
})(Index)

```

**期望行为**
无论在任何一端，行为应表现和`react-redux connect`函数一致

**报错信息**
组件的`this.props`里面没注入`add，dec`等函数信息

**系统信息**

 - 操作系统: [macos 10.12.6]
 - Taro 版本 [v.0.0.68]
 - Node.js 版本 [v9.10.1]

**Comment by luckyadam** [comment]
小程序端的 redux 连接使用的是 `@tarojs/redux` ，它的 `connect` 方法没有支持这种用法，后续可以加入支持~ 或者能不能提个 PR 呢

**Comment by luckyadam** [comment]
@lkspc 正在处理嘞
