### ISSUE TITLE
taro1.3.0-beta.0转为h5时报错 useEffect不是个函数

### ISSUE THREAD

**Issue by sprout-echo** [NervJS/taro#2982]
**问题描述**
[问题描述：taro1.3.0-beta.0转为h5时报错 useEffect不是个函数]

**复现步骤**
[复现问题的步骤]
`useEffect(() => {
    Taro.setNavigationBarTitle({
      title: '测评结果',
    });
  }, []);`

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
![image](https://user-images.githubusercontent.com/17763943/57292126-9e7f0880-70f3-11e9-85f2-5299ddc14065.png)

**系统信息**
 - 操作系统: [ Windows 10]
 - Taro 版本 [ v.1.3.0-beta.0]
 - Node.js 版本 [ v10.0.0]
 - 报错平台 [h5]

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/88eeaa26c5d37239af16202e0dca483d9dbdffef
