### ISSUE TITLE
[1.3.0.beta1] RN编译时报错 invariant_1.default is not a function

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#2984]
**问题描述**
![image](https://user-images.githubusercontent.com/13899502/57321658-66e48080-7134-11e9-89c4-6a430d948b82.png)

另外，
```
1:1     ⚠  @-rule 会被 React Native 忽略 [stylelint]
```
这个在群里提过，是说因为@import的问题？如果是有报错的话，应该有个更具体的错误信息吧。

**期望行为**
如果是有样式警告，应该提示

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
感谢反馈。
我在样式文件添加：`@import "../about/index";` ，没有复现 `'@-rule 会被 React Native 忽略'`的报错。

```
invariant_1.default is not a function
```
是样式校验的报错，确实有问题，正在 fix。
