### ISSUE TITLE
tsx 报错

### ISSUE THREAD

**Issue by misszoessmile** [NervJS/taro#2989]
**问题描述**
根据taro官方文档搭建myApp项目，进行开发的时候遇到父组件给子组件传值时编辑器飘红报错，但是传值可以成功，报错信息见下面截图。

**复现步骤**
[复现问题的步骤]
1. 新建test.tsx文件
2. 新建line.tsx组件，并在test.tsx组件引用

父组件代码：
```js
import Taro, { Component } from '@tarojs/taro';
import { View, Text, Button } from '@tarojs/components';
import Line from '../line/line'
class Demo extends Component {
    componentWillMount() { }
    componentDidMount() { }
    componentWillReceiveProps(nextProps, nextContext) { }
    componentWillUnmount() { }
    componentDidShow() { }
    componentDidHide() { }
    componentDidCatchError() { }
    componentDidNotFound() { }
    render() {
        return (
            <View>
                <Line name="12" />
            </View>
        );
    }
}
export default Demo;
```
子组件代码：
 ```js

import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtListItem } from 'taro-ui'
import './line.scss'

class Line extends Component {
    componentWillMount() { }
    componentDidMount() { }
    componentWillUnmount() { }
    componentDidShow() { }
    componentDidHide() { }

    render() {
        return (
            <View className='wrap-line'>
                <AtListItem title={this.props.name} extraText='详细信息' />
            </View>
        )
    }
}
export default Line
```

**期望行为**
编辑器提示错误，不影响功能实现，影响开发体验，期望帮忙解决，谢谢！

**报错信息**
当给子组件传参时父组件在vscode中提示错误：
Type '{ name: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Line> & Readonly<{}> & Readonly<{ children?: any; }>'.
  Property 'name' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Line> & Readonly<{}> & Readonly<{ children?: any; }>'.ts(2322)
错误如图：
![image](https://user-images.githubusercontent.com/35720631/57359000-325edc00-71a9-11e9-9145-b9ccdf43e800.png)

子组件能获取到值，但同样提示错误：
Property 'name' does not exist on type 'Readonly<{}> & Readonly<{ children?: any; }>'.
错误如图：
![image](https://user-images.githubusercontent.com/35720631/57359118-718d2d00-71a9-11e9-93af-c3d78e052593.png)

**系统信息**

👽 Taro v1.2.26
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

**Comment by yuche** [comment]
你没写泛型，读一下 TypeScript 文档，或者搜关键词 TypeScript react

**Comment by MRCXX** [comment]
![image](https://user-images.githubusercontent.com/55433454/74135078-9fb30800-4c26-11ea-99b9-c6a4f6dfe654.png)

```
class Line extends Component <{name: string}, {}> {
```
