### ISSUE TITLE
Taro.cloud.callFunction()  提示没有then

### ISSUE THREAD

**Issue by momokara** [NervJS/taro#2993]
------------------------

**问题描述**
taro-cli 生成的云函数模板 调用 
  Taro.cloud
      .callFunction()
 tslint 检测会 提示没有then

![image](https://user-images.githubusercontent.com/25426376/57393267-5516e200-71f5-11e9-8bf5-3955a2748f38.png)

**期望行为**
Taro.cloud
      .callFunction() 下应该包含then属性

**报错信息**
类型“void | Promise<CallFunctionResult>”上不存在属性“then”。
  类型“void”上不存在属性“then”。ts(2339)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
@tarojs\taro\types\index.d.ts
line 11964 
  function callFunction(param: ICloud.CallFunctionParam): Promise<ICloud.CallFunctionResult> | void
函数 返回 的是 联合类型 void 中没有then属性
尝试返回 交叉类型~

**Comment by momokara** [comment]
强迫症 <(－︿－)>~

**Comment by yuche** [comment]
老哥你可以提 PR

**Comment by davidlin88** [comment]
同难受23333 ts还不熟 希望有解决方法

**Comment by ZakaryCode** [comment]
按照当前 typing 中所描述的，callFunction 参数中包含 `'complete' | 'success' | 'fail'` 索引的 `function`，会返回 `void` 类型，不包含则为 `promise` 类型。
