### ISSUE TITLE
[1.3.0-beta.1] taro 的 hooks 表现跟原生 react 不一致

### ISSUE THREAD

**Issue by atzcl** [NervJS/taro#2995]
**问题描述**
 taro 的 hooks 表现跟原生 react 不一致

**复现步骤**
1. 创建一个 page、一个函数组件
2. 在函数组件使用 useEffect
3. 在函数组件触发事件，使传入的 props 数据发生变动
4. 结果会发现整个函数组件都会被重置、渲染

**taro**
>组件，非 page
![image](https://user-images.githubusercontent.com/28823188/57422594-54a53800-7243-11e9-9f3e-bed51d017411.png)

>props 数据每变动一次，都会将整个组件重置、渲染，具体看 console 的变动
![image](https://user-images.githubusercontent.com/28823188/57422611-6555ae00-7243-11e9-93fb-56efd2025237.png)

**原生**
![image](https://user-images.githubusercontent.com/28823188/57422676-97ffa680-7243-11e9-9023-d4a0b2985cb3.png)
![image](https://user-images.githubusercontent.com/28823188/57422682-9cc45a80-7243-11e9-91d9-1c7c5a9e03e7.png)

**期望行为**
跟原生保持一致

**系统信息**
```bash
👽 Taro v1.3.0-beta.1


  Taro CLI 1.3.0-beta.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
```

**Comment by yuche** [comment]
可以把你的复现做成一个仓库吗

**Comment by Chen-jj** [comment]
@atzcl 不是不渲染，而是第二个参数传了空数组后不多次跑 useEffect，不渲染的话第四张图就不会显示 19 了。

![image](https://user-images.githubusercontent.com/11807297/57423597-3e997680-7247-11e9-9333-d3dce4e9067a.png)

**Comment by atzcl** [comment]
@Chen-jj 😂我不是说不渲染，而是 taro 是把整个组件重新调用、重置渲染了，不会保存 useEffect 的状态，useEffect 的第二个参数传空数组的效果等同于 componentDidMount，在原生 react 里面， props 的变动不会导致 useEffect 的重置，而 taro 的则会，我建一个最小化仓库复现下哈~

**Comment by atzcl** [comment]
@yuche @Chen-jj 大佬们，仓库在这里：[https://github.com/atzcl/yx](https://github.com/atzcl/yx)

**Comment by atzcl** [comment]
表现：
![image](https://user-images.githubusercontent.com/28823188/57426629-8d004280-7252-11e9-858b-901cb2f3cb80.png)

**Comment by atzcl** [comment]
另外还有一个编译的问题，可以看这里的注释：[https://github.com/atzcl/yx/blob/0b48458fd8af9a706ecfc457953ef0091c856eb5/src/pages/index/components/Timer.tsx#L1-L12](https://github.com/atzcl/yx/blob/0b48458fd8af9a706ecfc457953ef0091c856eb5/src/pages/index/components/Timer.tsx#L1-L12)

**Comment by JasonJie** [comment]
![image](https://user-images.githubusercontent.com/15973148/57434095-b928bd00-726c-11e9-9a7c-db53133d4734.png)
我也出现了相同的问题。
在使用setMoveTop时，不会触发这个函数。在这个方法中使用setMoveEndPonint，会一直触发这个函数。

**Comment by yuche** [comment]
@tarojs/taro-weapp 替换到 beta0 是否还会出现这个问题

**Comment by atzcl** [comment]
@yuche 大佬，beta0  下的 hooks 是正常的~ 另外编译异常的问题还是存在，，，

**Comment by JasonJie** [comment]
@yuche 我的这个问题会修复吗？数组中传入了state，但是使用setXXXX的时候，这个useEffect没有触发的问题。

**Comment by yuche** [comment]
> @yuche 我的这个问题会修复吗？数组中传入了state，但是使用setXXXX的时候，这个useEffect没有触发的问题。

你可以根据 https://github.com/NervJS/taro/commit/866aca19fc15ba7505fcf7c044b51bcd55e379ca 改 打包后 dist/npm/@tarojs/taro-weapp 的源码，如果没用再提新的 issue。
