### ISSUE TITLE
支持SSR吗

### ISSUE THREAD

**Issue by EmmenCao** [NervJS/taro#30]
我记得看文档Nerv 是支持SSR的，请问Taro支持SSR吗？
后期是否有下拉刷新和自动加载组件？

**Comment by luckyadam** [comment]
SSR支持的~
可以有，组件会不断完善

**Comment by EmmenCao** [comment]
谢谢，大佬们无私奉献的大无畏精神。

**Comment by Landvetter** [comment]
请问怎么使用呢，在文档中没看到跟ssr相关的部分
