### ISSUE TITLE
@taro/taro-weapp 报错

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#300]
**问题描述**
位于 node_modules/@tarojs/taro-weapp/dist/taro-weapp.js 文件的
1262 行代码，对一个 Object 执行了 map 方法，导致报错.

**复现步骤**
不太清楚，代码大概长这样，
删掉 {res.map.... 代码块就好了，
```js
render() {
  const {allList = [], onlineList = [], offineList = []} = this.state;
  const scrolls = [allList, onlineList, offlineList];
  return (
    <View>
      {scrolls.map((res, resIndex) => {
          return (
            <ScrollView
              scrollY
              onScrolltolower={this.onGetMore.bind(this)}
            >
              {res.map(item => {
                return (
                  <View className="order-list-item___wrap" key={item.id}>
                    <OrderListItem />
                  </View>
                );
              })}
            </ScrollView>
          );
        })}
    </View>
  )
}
```

**期望行为**
bug fixed

**报错信息**
以下为报错信息
```js
VM9396:1 thirdScriptError
inData.map is not a function;at pages/store/orderList/index page lifeCycleMethod onLoad function
TypeError: inData.map is not a function
    at http://127.0.0.1:29645/appservice/npm/@tarojs/taro-weapp/dist/index.js:1260:31
    at Array.map (<anonymous>)
    at dynamicRecursive (http://127.0.0.1:29645/appservice/npm/@tarojs/taro-weapp/dist/index.js:1250:16)
    at http://127.0.0.1:29645/appservice/npm/@tarojs/taro-weapp/dist/index.js:1278:16
    at Array.map (<anonymous>)
    at http://127.0.0.1:29645/appservice/npm/@tarojs/taro-weapp/dist/index.js:1277:29
    at Array.map (<anonymous>)
    at dynamicRecursive (http://127.0.0.1:29645/appservice/npm/@tarojs/taro-weapp/dist/index.js:1250:16)
    at $45b1b249 (http://127.0.0.1:29645/appservice/pages/store/orderList/index.js:73:65)
    at http://127.0.0.1:29645/appservice/npm/@tarojs/taro-weapp/dist/index.js:2726:23
```
具体情况
![image](https://user-images.githubusercontent.com/23295172/42502476-becb99be-8468-11e8-9e51-231bd16400c8.png)

**系统信息**

 - 操作系统: windows 7
 - Taro 版本 v0.0.68
 - Node.js 版本 v8.11.2

**补充信息**
我怎么记得，之前是没问题的，可能是记错了

**Comment by Dithub2016** [comment]
补充一下，删除 OrderListItem 自定义组件的使用就好了，

**Comment by Dithub2016** [comment]
再补充一下，回退到 taro v0.0.67 没有问题

**Comment by zacksleo** [comment]
constructor里面给个初始值

**Comment by Dithub2016** [comment]
在 `contructor`  里是存在 state 的初始值的,
allList, onlineList, offlineList 皆为 `[]`

**Comment by yuche** [comment]
麻烦把报错代码和复现代码对应起来，你报错和代码不是一回事怎么查啊

**Comment by Dithub2016** [comment]
不是一回事？
第一层 map scrolls 数据，
![image](https://user-images.githubusercontent.com/23295172/42752119-874cb8cc-891f-11e8-815a-611eca4de595.png)
indata 为 数组，没异常，
嵌套的第二层 map ，indata 是一个 Object ，导致报错的发生
![image](https://user-images.githubusercontent.com/23295172/42752216-c7ca30aa-891f-11e8-87fe-ffccdc62012b.png)

**Comment by clarktang** [comment]
我也出现了一样的问题。
![1531735042748](https://user-images.githubusercontent.com/37982974/42752996-23445c38-8922-11e8-9abb-ace11a741e9b.jpg)
上面的代码只要把map中的`<View>`换成一个普通的`<View>Hello world</View>`就没问题，报的错误也是inData.map is not a function

**Comment by yuche** [comment]
请问到 0.0.69 有问题吗？

**Comment by clarktang** [comment]
![123](https://user-images.githubusercontent.com/37982974/42753262-ea316d36-8922-11e8-8e0c-b58eab2cfa77.png)
版本号：0.0.69
macos

**Comment by clarktang** [comment]
补充一下：在node:8.8.0和node:10.6.0，都测试过，报一样的错误。

**Comment by clarktang** [comment]
已解决，升级到0.0.70,node 版本10.6.0

**Comment by Dithub2016** [comment]
node v8.11.2 以及 v8.11.3 还有 v10.6.0 , 在 taro v0.0.70 版本该问题继续存在
