### ISSUE TITLE
1.3.0 beta.1 使用 hooks 构建微信小程序报错

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#3000]
```jsx
import Taro , { useState } from '@tarojs/taro';
function Example {
  const [selected, setSelected] = useState('');
  return <View>{selected}</View>
}
```
编译不错，但是小程序报错
报错如下
![image](https://user-images.githubusercontent.com/24502330/57445548-2f391e00-7285-11e9-8c16-34b33210f6fa.png)

查看代码是这个未定义
![image](https://user-images.githubusercontent.com/24502330/57445656-690a2480-7285-11e9-9bd5-c21c86eee481.png)

正常编译下是这个
![image](https://user-images.githubusercontent.com/24502330/57445716-8b9c3d80-7285-11e9-977a-ceb082a5a767.png)

**Comment by yinLiangDream** [comment]
我研究了下，是编译的问题，如果这个编译成
```jsx
// (Taro.Component) 改成
(_index.default.Component)
```
就没有问题了，hooks 也是生效的，希望改一下orz

**Comment by MarvinShawn** [comment]
> 我研究了下，是编译的问题，如果这个编译成
> 
> ```js-jsx
> // (Taro.Component) 改成
> (_index.default.Component)
> ```
> 
> 就没有问题了，hooks 也是生效的，希望改一下orz

俺也一样

**Comment by yuche** [comment]
typescript 默认会把 没有用到的 import 移除，Taro 被移除掉了所以没能编译出来。

你可以在文件里写个 console.log(Taro) 或者使用 js。

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/866aca19fc15ba7505fcf7c044b51bcd55e379ca
