### ISSUE TITLE
修改state赋值的变量却改变state原始值

### ISSUE THREAD

**Issue by Cupidor** [NervJS/taro#3004]
**问题描述**
从state取出的数组，赋值给另一个变量后，对变量数组push，this.state里的原数组竟然发生改变

**复现步骤**
// 添加备用手机号
  onAddTelephone() {
    const { value } = this.state
    let tele = this.state.telephones
    console.log(this.state.telephones)
    if (value === '') {
      Taro.atMessage({
        message: '手机号码不可以为空',
        type: 'warning'
      })
    } else if (getLength(value) < 11) {
      Taro.atMessage({
        message: '手机号码必须为11位',
        type: 'warning'
      })
    } else {
      if (tele.length >= 5) {
        Taro.atMessage({
          message: '最多添加5个备用手机',
          type: 'warning'
        })
      } else {
        let isexist = false
        for (let item of tele) {
          if (item === value) {
            isexist = true
            Taro.atMessage({
              message: '该手机号码已存在',
              type: 'warning'
            })
            break
          }
        }
        if (isexist === false) {
          tele.push(value)
          console.log(this.state.telephones)
          this.onUpdate(tele)
        }
      }
    }
  }

**期望行为**
不改变原始this.state.telephones数组，只改变tele数组

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/30062524/57500484-2b091100-7316-11e9-8965-2474e6c2c620.png)

前2次的打印信息为我上述代码的console.logtaro

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.2.23]
 - Node.js 版本 [e.g. 11.13.0]
 - 报错平台 [weapp]

**补充信息**

**Comment by yuche** [comment]
因为 JavaScript 的数组引用类型，所以是一定会改的。

如果你不想改的话可以赋值的时候复制一份：
```
let tele = this.state.telephones.slice()
```
