### ISSUE TITLE
1.2.26 ScrollView onScroll 事件不触发

### ISSUE THREAD

**Issue by wei090603** [NervJS/taro#3005]
![image](https://user-images.githubusercontent.com/25702339/57500884-d8305900-7317-11e9-9eaf-19cbb987a7aa.png)
H5中绑定的事件都没有触发，希望不是我写的有问题！

**Comment by jinjinjin0731** [comment]
@wei090603 
1.  你这个写法很明显错了。你虽然设置了 ScrollView 的高度。但是你的子元素是否有撑开了，可以使 ScrollView 滑动？  
2. 你所看到的滑动，是因为你的 ScrollView 高度大于你的窗口高度，从而导致的 View 滚动
3. 你可以这样修改
![image](https://user-images.githubusercontent.com/17409735/57592703-afec6880-756a-11e9-9558-65d84fccd7fd.png)

**Comment by wei090603** [comment]
![image](https://user-images.githubusercontent.com/25702339/57593269-43269d80-756d-11e9-8506-211452d25622.png)
![image](https://user-images.githubusercontent.com/25702339/57593281-4cb00580-756d-11e9-8312-8463e2021bf4.png)
请问有什么办法可以获取到scrollTop吗？一直为0 没解决！
