### ISSUE TITLE
使用taro初始化一个项目，执行yarn build:weapp后，使用微信小程序打开预览，报编译错误：

### ISSUE THREAD

**Issue by oyhanyu** [NervJS/taro#3006]
------------------------

**问题描述**
[问题描述： 编译后微信开发者工具预览，报编译错误]

**复现步骤**
[复现问题的步骤]
1.  taro init app
2. yarn build:weapp
3. 在微信开发工具中预览

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [mac]
 - Taro 版本 [最新版]
 - Node.js 版本 [v8.10]
 - 报错平台 [weapp]

**错误信息**
WAService.js:11 Uncaught ReferenceError: requirePlugin is not defined
    at initNativeApi (index.js:1)
    at index.js:1
    at require (WAService.js:11)
    at WAService.js:11
    at index.js:1
    at require (WAService.js:11)
    at WAService.js:11
    at app.js:1
    at require (WAService.js:11)
    at appservice:21

Fri May 10 2019 11:46:18 GMT+0800 (CST) page 编译错误
appservice:28 pages/index/index.js 出现脚本错误或者未正确调用 Page()
(anonymous) @ appservice:28
WAService.js:10 Fri May 10 2019 11:49:55 GMT+0800 (CST) Page route 错误
WAService.js:10 Page[pages/index/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.

**补充信息**
支付宝小程序可以正常访问，微信不可以

**Comment by luckyadam** [comment]
你选择的开发者工具基础库版本太低了

**Comment by oyhanyu** [comment]
@luckyadam 非常感谢
