### ISSUE TITLE
crypto-js

### ISSUE THREAD

**Issue by Creat155** [NervJS/taro#3008]
![image](https://user-images.githubusercontent.com/39396448/57518735-48f16880-734c-11e9-9319-777f5186c069.png)
crypto-js怎么获取的到sign呢？ @jinjinjin0731

**Comment by Garfield550** [comment]
### The Hashing Output

The hash you get back isn't a string yet. It's a WordArray object. When you use a WordArray object in a string context, it's automatically converted to a hex string.

```JS
var hash = CryptoJS.SHA256("Message");
​
typeof hash
> "object";
​
hash
> "2f77668a9dfbf8d5848b9eeb4a7145ca94c6ed9236e4a773f6dcafa5132b2f91";
```

You can convert a WordArray object to other formats by explicitly calling the toString method and passing an encoder.


```js
var hash = CryptoJS.SHA256("Message");
​
hash.toString(CryptoJS.enc.Base64)
> "L3dmip37+NWEi57rSnFFypTG7ZI25Kdz9tyvpRMrL5E=";
​
hash.toString(CryptoJS.enc.Hex)
> "2f77668a9dfbf8d5848b9eeb4a7145ca94c6ed9236e4a773f6dcafa5132b2f91";
```

Ref: https://cryptojs.gitbook.io/docs/#the-hashing-output
