### ISSUE TITLE
RN样式转换时，建议已知的不兼容样式除了警告外，最好在RN端先注释了

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3011]
**问题描述**

我们使用taro开发，习惯是先开发H5/小程序，再到RN。因为RN跟常规的web开发，样式支持程度差异较大，需要对样式进行大量兼容的改造，所有在转换taro h5 => RN的时候很痛苦，改了一天样式，模拟器还是红红一片。

所以建议对于不兼容的样式，RN端能不能在报错的同时，也先注释了这些有问题的样式。开发只要让应用跑起来，有H5、小程序对照的话，样式调整可以快很多。而不是一开始就花费大量精力去调整样式。

**系统信息**
```
👽 Taro v1.2.26


  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

```

**Comment by Pines-Cheng** [comment]
建议一开始就 H5、RN 同步开发，先开发好 小程序 或 H5 ，再适配 RN 的话，后期调样式会很痛苦的。
