### ISSUE TITLE
如何获取url 中的query String

### ISSUE THREAD

**Issue by JackonLiu** [NervJS/taro#3012]
**问题描述**
taro如何获取url 中的query String

**复现步骤**
[复现问题的步骤]
1. 传入url
http://58.61.150.66:10086/?auth=NkIxNEEyNjM0NjY4N0I3N

如何获取auth

**期望行为**
获取auth

**系统信息**
操作系统: [ Windows 7]
� Taro v1.2.22
Taro CLI 1.2.22 environment info:
System:
OS: Windows 7
Binaries:
Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
Yarn: 1.15.2 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
npm run dev:h5

**补充信息**
      let authObject = yield Taro.getStorage({key: 'auth'});
      let auth = authObject.data;
使用了这种方法，但是拿的并不是URL中的auth
使用了this.props.$router.params也是没有用的
因为这个url是从APP中传过来的，并不是taro内部路由跳转

**Comment by luckyadam** [comment]
自己解析

**Comment by pkaq** [comment]
> 自己解析

怎么个自己解析法???????

**Comment by shenghanqin** [comment]
1. 写一个getQueryString的方法
2. 使用 new URL自动获取，但可能需要引入polyfill
