### ISSUE TITLE
如何在taro中使用cax渲染 SVG

### ISSUE THREAD

**Issue by 23233** [NervJS/taro#3013]
## 如题所说
我想使用cax 渲染一个svg 但是不知道如何使用 使用 usingComponents 一直是报错 path错误 请教一下如何顺利进行？

**Comment by luckyadam** [comment]
cax 是什么，贴一下代码

**Comment by Garfield550** [comment]
@luckyadam 腾讯 Omi 框架的 SVG 渲染引擎 Cax，基于小程序 Canvas。
https://github.com/Tencent/omi/tree/master/packages/cax

**Comment by boyongjiong** [comment]
你好，你这个问题有解决吗 @23233 @Garfield550 @luckyadam  或者说有没有别的解决方案，现在想 taro 中使用 svg 做一个下图所示交互效果，感觉 svg 是最好的解决方案

![image](https://user-images.githubusercontent.com/8553969/59398450-dd733e80-8dc2-11e9-91cb-5aa751c25cfe.png)

或者有没有人有更好的解决思路，能不能分享一下

**Comment by brookyu** [comment]
请问这个问题解决了吗？现在有个taro3-svg库，可惜taro的vue3 项目引用失败
WARNING in ./src/pages/RichPlayer/index.vue?vue&type=script&setup=true&lang=js 1:0-262
"export 'default' was not found in '-!../../../node_modules/babel-loader/lib/index.js!../../../node_modules/vue-loader/dist/index.js??ref--10-0!../../../node_modules/windicss-webpack-plugin/dist/loaders/windicss-template.cjs!./index.vue?vue&type=script&setup=true&lang=js'
 @ ./src/pages/RichPlayer/index.vue (./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/RichPlayer/index.vue)
 @ ./src/pages/RichPlayer/index.vue
