### ISSUE TITLE
Taro.request在SWAN环境下，获得的单值JSON数组会变成数值

### ISSUE THREAD

**Issue by willxucn** [NervJS/taro#3015]
**问题描述**
Taro.request在SWAN环境下，获得的单值JSON数组会变成数值

**复现步骤**
```js
    Taro.request({
      method: 'POST',
      url: app.globalData.webAddr + '/service.svc/listget',
      data: {
        cred: that.cred,
      },
      dataType: 'json',
      success: function (res) {
         console.log(res)
      },
      fail: () => {
        console.log('get fail')
      }
    })
```

调试时跟踪了网络传输的数据：
第一次：服务器返回多个值的数组：
HTTP Response记录数据如下：
`[1694,1690,1686]`
`0: 1694`
`1: 1690`
`2: 1686`
console.log(res)日志：
`{statusCode: 200, header: {...}, data: Array(3)}`

第二次：服务器返回一个数值的数组：
HTTP Response记录数据如下：
`[1570]`
`0: 1570`

console.log(res)日志：
`{statusCode: 200, header: {...}, data: 1570}`

服务器采用WCF框架，返回时自动对Array进行序列化，每次访问，无论数组内有多少数值，在百度小程序调试工具的Network-Response以及Preview中监测到的均为数组形式，说明服务器返回应没有问题；
另外，调试时，尝试去掉`dataType:'json'`问题依旧存在。
以上问题，相同代码在微信环境中执行正常。

**期望行为**
服务器返回JSON格式的数组，无论一个或多个，success的res均应该为数组

**报错信息**
无报错，但数值不符合期望

**系统信息**
 - Taro CLI 1.2.26 environment info:
 - OS: Windows 10
 - Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
 - 报错平台 [swan]

**补充信息**

**Comment by luckyadam** [comment]
你试试原生的 swan.request 行不行

**Comment by shenghanqin** [comment]
@willxucn 请再尝试一下？
