### ISSUE TITLE
h5: Input 组件中文状态下输入异常

### ISSUE THREAD

**Issue by shpeng** [NervJS/taro#302]
@taro-component 0.0.54
h5, ios上， input 中文输入，异常。 输入"jkl", 没有 composition 的状态， 得到了如下图。

![wechatimg134](https://user-images.githubusercontent.com/11827343/42559427-a57d25ea-8526-11e8-95e3-848f9f7c163e.jpeg)

**Comment by jinjinjin0731** [comment]
更新到 最新的版本试一下
