### ISSUE TITLE
ts模式，components 模块下 event 描述没有被 export 出来

### ISSUE THREAD

**Issue by gu-xionghong** [NervJS/taro#3020]
**问题描述**
在 ts 模式下，使用 `onClick` 等事件，对应的 `event` 参数描述文件没有被 `export` 出来，引用的话，需要直接去到 `@tarojs/components/types/common` 下获取

**复现步骤**
直接创建 ts 模板

```js
import { ITouchEvent } from '@tarojs/components/types/common'

// ...
class Template extends Component<IProps, IState> {
  // 此处希望能直接从  @tarojs/components 中引出
  handleClick(e: ITouchEvent) {}

  render() {
    return (
      <View className="template" onClick={this.handleClick}></View>
    )
  }
}
```

**期望行为**
直接从 `@tarojs/components` 中引出对应的 `event` 描述
```js
import { ITouchEvent } from '@tarojs/components'
```

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac 10.14.2
 - Taro 版本 v1.2.26
 - Node.js 版本 v10.14.2
 - 报错平台 *

**补充信息**
无

**Comment by Garfield550** [comment]
正常用啊，有什么问题吗？tsc 不关心这个的吧。

```ts
import { CommonEvent } from '@tarojs/components/types/common';
```

```ts
 private handleConfirm(e: CommonEvent): void {
   this.props.onConfirm(...arguments);
   this.handleClose(e);
 }
```
