### ISSUE TITLE
scss文件修改监听有顺序问题，后修改的会被编译到文件头部，导致样式被覆盖

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#3021]
![WechatIMG1178](https://user-images.githubusercontent.com/31879769/57593472-1de65f00-756e-11e9-8a03-cbb31e778e1d.png)
这个scss监听文件修改的时候有个问题，就是后修改的文件会被加在文件的顶部，这样就会导致后面修改这个文件的样式会被覆盖掉
比如说我修改index.scss保存之后就会，这个里面的代码就会跑到文件顶部，部分样式就会被icon.scss覆盖掉

**Comment by shenghanqin** [comment]
@ShaoGongBra 试试最新版本还有这个问题吗？
