### ISSUE TITLE
componentDidMount在h5端 为什么每次进去都会执行  不是说对应着小程序的onLaunch么   两端表现不一致

### ISSUE THREAD

**Issue by lzt9977** [NervJS/taro#3023]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js


// 这里可以贴代码

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by lzt9977** [comment]
版本   "@tarojs/taro": "1.2.26"

![image](https://user-images.githubusercontent.com/23352892/57597759-3b71f380-7583-11e9-8b59-4aafd657289b.png)

点击下面的tabbar的时候 两端表现

h5

![image](https://user-images.githubusercontent.com/23352892/57597785-547aa480-7583-11e9-9a94-97040a563f49.png)

weapp

![image](https://user-images.githubusercontent.com/23352892/57597819-7c6a0800-7583-11e9-8c38-b8b76fbf1c10.png)

**Comment by lzt9977** [comment]
componentDidMount 跟 componentDidShow 一样的表现了

**Comment by lzt9977** [comment]
求救啊 有没有人

**Comment by luckyadam** [comment]
哪里的 componentDidMount

**Comment by lzt9977** [comment]
主页的

**Comment by lzt9977** [comment]
> 哪里的 componentDidMount

主页的  代码很简单 刚开始写就发现这个问题了 我已经把逻辑什么都删了

现在就写了2个console  

![image](https://user-images.githubusercontent.com/23352892/57598277-2e560400-7585-11e9-94bf-c579c3da4126.png)

首页和统计切换几次 h5端表现如下

![image](https://user-images.githubusercontent.com/23352892/57598283-34e47b80-7585-11e9-8775-10930cfe0717.png)

**Comment by lzt9977** [comment]
![image](https://user-images.githubusercontent.com/23352892/57598401-aa504c00-7585-11e9-970e-13ecacc3998a.png)

qq群有人说是正常的 h5就是这个表现  但是官网没说明啊  生命周期两端都不同步吗

issue里面的微信群 加好友也进不去 这个问题毫无头绪  打包法也没用了。打包完还是有这个问题

**Comment by luckyadam** [comment]
没有明白你的问题，页面的 componentDidMount 和 onLaunch 有什么关系？H5 的 tabbar 页面的 componentDidMount 在 tabbar 切换的时候就会执行，这个也不影响你的使用啊

**Comment by lzt9977** [comment]
> 没有明白你的问题，页面的 componentDidMount 和 onLaunch 有什么关系？H5 的 tabbar 页面的 componentDidMount 在 tabbar 切换的时候就会执行，和小程序没有一致，但这个也不影响你的使用啊

ok 我就想知道两端是不是一致
