### ISSUE TITLE
H5 picker end属性设置后 选择其他年份的时间日期点击确定后，再打开就又可选了end设置过的日期了

### ISSUE THREAD

**Issue by lvzhimingjobs** [NervJS/taro#3024]

**Comment by jinjinjin0731** [comment]
提供一下代码片段以及你的版本号？无法排查问题

**Comment by lvzhimingjobs** [comment]
![image](https://user-images.githubusercontent.com/37326179/57599986-09648f80-758b-11e9-8782-8a774fa05ecf.png)
![image](https://user-images.githubusercontent.com/37326179/57600003-141f2480-758b-11e9-8bd7-4c5c1df306af.png)
![image](https://user-images.githubusercontent.com/37326179/57600032-2a2ce500-758b-11e9-8720-9650df61e815.png)

**Comment by lvzhimingjobs** [comment]
![image](https://user-images.githubusercontent.com/37326179/57600096-652f1880-758b-11e9-9531-79867309d2c9.png)

**Comment by lvzhimingjobs** [comment]
版本号：V1.2.26

**Comment by jinjinjin0731** [comment]
你的 Picker 是封装的一个自定义组件吗？ 更新触发 componentWillReceiveProps ？
可以给一个小 demo 方便复现么？

**Comment by lvzhimingjobs** [comment]
嗯 是的  封装的组件 在更新的时候触发componentWillReceiveProps，获取当前的时间，处理后给 end使用

**Comment by lvzhimingjobs** [comment]
import { Component } from '@tarojs/taro';
import Taro, { Picker, View } from '@tarojs/components';

class DatePicker extends Component {
  state = {
    errorDate: undefined,
  };
  componentWillReceiveProps = () => {
    const endDate = new Date();
    const Y = endDate.getFullYear() + '-';
    const M =
      (endDate.getMonth() + 1 < 10 ? '0' + (endDate.getMonth() + 1) : endDate.getMonth() + 1) + '-';
    const D = endDate.getDate() + ' ';
    const erroEnDate = Y + M + D;
    this.setState({
      errorDate: erroEnDate,
    });
  };
  render() {
    const { dateSel, onChange } = this.props;
    return (
      <Picker mode='date' end={this.state.errorDate} onChange={e => onChange(e)}>
        <View className='picker styleSelect'>{dateSel}</View>
      </Picker>
    );
  }
}

export default DatePicker;

**Comment by lvzhimingjobs** [comment]
使用的页面：
<View className='phone-wrap input-box'>
            <DatePicker
              onChange={e => this.setState({ birthday: e.detail.value })}
              dateSel={this.state.birthday}
            />
</View>

**Comment by lvzhimingjobs** [comment]
就算是end写死一个时间也会出现这个问题，end='2019-05-13' 也一样

**Comment by lvzhimingjobs** [comment]
<Picker mode='date' end='2019-05-13' onChange={e => onChange(e)}>

**Comment by lvzhimingjobs** [comment]
@jinjinjin0731 老哥 怎么样了？有救吗？

**Comment by jinjinjin0731** [comment]
@lvzhimingjobs  晚点我复现一下

**Comment by lvzhimingjobs** [comment]
好的 现在在测试阶段，希望您那边尽快回复一下，我也答复测试那边，谢谢您辛苦了。

**Comment by lvzhimingjobs** [comment]
可以了吗？ @jinjinjin0731

**Comment by jinjinjin0731** [comment]
@lvzhimingjobs  没有复现。 一下我根据你的代码片段写的 demo 
![image](https://user-images.githubusercontent.com/17409735/57617896-793b4000-75b4-11e9-9cd1-86d6e6c8886c.png)

![image](https://user-images.githubusercontent.com/17409735/57617821-498c3800-75b4-11e9-90b0-277cde5dd0e5.png)

![image](https://user-images.githubusercontent.com/17409735/57617930-8f490080-75b4-11e9-9f18-b04479596c15.png)

> 选择之后再次打开
![image](https://user-images.githubusercontent.com/17409735/57617972-b0115600-75b4-11e9-834f-b706114788f6.png)

**Comment by lvzhimingjobs** [comment]
![image](https://user-images.githubusercontent.com/37326179/57665453-8432b680-762e-11e9-8b48-37c060417964.png)
你的demo第一步 5月13以后就可以选择，就有问题了

**Comment by lvzhimingjobs** [comment]
@jinjinjin0731 你的第一步就已经错误 可以选择了

**Comment by lvzhimingjobs** [comment]
@jinjinjin0731 还有你选择一个其他年份月份的

**Comment by lvzhimingjobs** [comment]
@jinjinjin0731 你还能收到我的消息吗？

**Comment by jinjinjin0731** [comment]
@lvzhimingjobs  第一步为什么有问题， 你默认给的值是 undefined 是个无效值。 这步又不会触发 componentWillReceiveProps 。为什么会是错的？  我选择其他年月份点击确定之后可以是正常的

**Comment by jinjinjin0731** [comment]
你仔细看我的截图。 我还打印了  `console.log(this.state.errorDate)`   两次的值在截图里面都有体现。 流程没有发现什么问题

**Comment by lvzhimingjobs** [comment]
我现不在这里进行操作，erroDate从父级传过来，
class DatePicker extends Component {
  render() {
    const { dateSel, onChange, erroDate } = this.props;
    return (
      <Picker mode='date' onChange={e => onChange(e)} end={erroDate}>
        <View className='picker styleSelect'>{dateSel}</View>
      </Picker>
    );
  }
}

**Comment by lvzhimingjobs** [comment]
父级：
componentWillReceiveProps = nextProps => {
     const { resumeData: { data },  } = nextProps;
      const endDate = new Date();
      const Y = endDate.getFullYear() + '-';
      const M =
        (endDate.getMonth() + 1 < 10 ? '0' + (endDate.getMonth() + 1) : endDate.getMonth() + 1) +
        '-';
      const D = endDate.getDate() + ' ';
      const erroEnDate = Y + M + D;
      this.setState({erroDate: erroEnDate,})
};
 {/*---------------生日-----------------begin*/}
          <View className='phone-wrap input-box'>
            <Text className='formLable'>
              <Text className='haveTo'>*</Text>生日
            </Text>
            <DatePicker
              onChange={e => {
                this.setState({ birthday: e.detail.value });
                trk.onEvent('cvbirth', { birth: e.detail.value });
              }}
              dateSel={this.state.birthday}
              erroDate={this.state.erroDate}
            />
            {this.state.birthday ? (
              <Text className='carryOut'>完成</Text>
            ) : (
              <Text className='erro'>请选择</Text>
            )}
 </View>

**Comment by lvzhimingjobs** [comment]
我这边确实存在问题，即使把end的时间写死一个'2019-05-14'也不行

**Comment by lvzhimingjobs** [comment]
@jinjinjin0731 我这边确实存在问题，即使把end的时间写死一个'2019-05-14'也不行

**Comment by lvzhimingjobs** [comment]
> @lvzhimingjobs 第一步为什么有问题，你默认给的值是undefined是个无效值。这步又不会触发componentWillReceiveProps。为什么会是错的？我选择其他年月份点击确定之后是正常的

我刚开始不放在componentWillReceiveProps这里面，放在render里也有问题的

**Comment by jinjinjin0731** [comment]
那你能写一个抽出一个最简单可复现的 demo 贴一下？  父组件文件的所有代码，以及子组件的代码。 我依靠这两个文件去复现。

**Comment by lvzhimingjobs** [comment]
方便加个微信吗  我录个屏给你看看 @jinjinjin0731 ，方便的话留一下微信号好吗？

**Comment by lvzhimingjobs** [comment]
稍等 那我抽一下demo

**Comment by lvzhimingjobs** [comment]
父级：
// eslint-disable-next-line no-unused-vars
import _ from 'lodash';
import Taro, { Component } from '@tarojs/taro';
import '@tarojs/async-await';
import { Button, Label, Radio, RadioGroup, Text, View, Input, Textarea } from '@tarojs/components';
import './index.less';
import DatePicker from '../components/datePicker';

@PageDecorator.thisIsEditPage({
  title: '我的微简历',
  model: ResumeModel,
  loadActions: [ResumeActions.getDictionary, ResumeActions.getResume],
  pickStates: ['dictionaryData', 'resumeData'],
})
export default class Create extends Component {
  state = {
  	birthday:'2018-09-09'
    erroDate: undefined, // 不可选日期
  };

  componentWillReceiveProps = nextProps => {
    const {
      resumeData: { data },
    } = nextProps;
      const endDate = new Date();
      const Y = endDate.getFullYear() + '-';
      const M =
        (endDate.getMonth() + 1 < 10 ? '0' + (endDate.getMonth() + 1) : endDate.getMonth() + 1) +
        '-';
      const D = endDate.getDate() + ' ';
      const erroEnDate = Y + M + D;
      this.setState( { erroDate: erroEnDate },
      );
    }
  };

  

  render() {
    return (
      <View className='index'>
        <View className='infoTitle'>基本信息</View>
        <View className='basicInfor'>
         
          {/*---------------生日-----------------begin*/}
          <View className='phone-wrap input-box'>
            <Text className='formLable'>
              <Text className='haveTo'>*</Text>生日
            </Text>
            <DatePicker
              onChange={e => {
                this.setState({ birthday: e.detail.value });
                trk.onEvent('cvbirth', { birth: e.detail.value });
              }}
              dateSel={this.state.birthday}
              erroDate={this.state.erroDate}
            />
            {this.state.birthday ? (
              <Text className='carryOut'>完成</Text>
            ) : (
              <Text className='erro'>请选择</Text>
            )}
          </View>
      </View>
    );
  }
}

**Comment by lvzhimingjobs** [comment]
子级：
import { Component } from '@tarojs/taro';
import Taro, { Picker, View } from '@tarojs/components';

class DatePicker extends Component {
  render() {
    const { dateSel, onChange, erroDate } = this.props;
    return (
      <Picker mode='date' onChange={e => onChange(e)} end={erroDate}>
        <View className='picker styleSelect'>{dateSel}</View>
      </Picker>
    );
  }
}

export default DatePicker;

**Comment by lvzhimingjobs** [comment]
@ @jinjinjin0731  拆了一下 你试试可用吗 在我这拆太庞大了

**Comment by jinjinjin0731** [comment]
@lvzhimingjobs  晚点复现一下

**Comment by lvzhimingjobs** [comment]
我怀疑触发了其他年月日的onchange后end失效了@jinjinjin0731

**Comment by lvzhimingjobs** [comment]
不用组建使用官方提供的文档里，问题同在
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Picker } from '@tarojs/components'

export default class PagePicker extends Component {
  state = {
    dateSel: '2018-04-22'
  }

  onDateChange = e => {
    this.setState({
      dateSel: e.detail.value
    })
  }

  render () {
    return (
      <View className='container'>
        <View className='page-body'>
          <View className='page-section'>
            <Text>日期选择器</Text>
            <View>
            <Picker mode='date' onChange={this.onDateChange} end='2019-05-14'>
              <View className='picker'>
                当前选择：{this.state.dateSel}
              </View>
            </Picker>
            </View>
          </View>
        </View>
      </View>
    )
  }
}

**Comment by jinjinjin0731** [comment]
taro info 一下你的版本信息，截图发我一下。   邮件发我一下你的微信号吧，我加你

**Comment by lvzhimingjobs** [comment]
taro版本
![image](https://user-images.githubusercontent.com/37326179/57680224-b577aa80-765f-11e9-8c38-0c2605226a31.png)

**Comment by lvzhimingjobs** [comment]
wx：17611248918

**Comment by jinjinjin0731** [comment]
版本和依赖保持一致
我看你截图第一个 router 是 1.2.21。   所有 tarojs 的包版本。 需要保持一致。  你升级一下吧

**Comment by lvzhimingjobs** [comment]
已解决，服务棒棒哒
