### ISSUE TITLE
H5 的 onPullDownRefresh 和 onReachBottom 的问题

### ISSUE THREAD

**Issue by qianzhaoy** [NervJS/taro#3026]
如果我在 page 页没有使用 `'@tarojs/taro'` 或者 '@tarojs/components' 模块的任何方法或者组件.

转换成H5后, 不会自动引入
> import { PullDwonRefresh } from '@tarojs/components'
> import { Taro } from '@tarojs/taro'

从而导致报错.

**Comment by Littly** [comment]
确实是个问题 下个版本修复下

**Comment by Littly** [comment]
5b18d63091aaa33412b4d9cee17ba50929f2dfab 已提交修复
