### ISSUE TITLE
windowHeight在RN下与预期不符

### ISSUE THREAD

**Issue by canvasT** [NervJS/taro#3030]
# 问题描述
通过测试发现，getSystemInfo接口获取的windowHeight与screenHeight一样

# 预期
按照官方文档，windowHeight表示“可使用窗口高度”，应该不包括导航栏、状态栏以及底部tab bar的高度

# 环境
Taro 1.2.26
ReactNative 0.55
系统 iPhone8 模拟器, iOS 12.0

**Comment by Pines-Cheng** [comment]
微信小程序下确实为 可使用窗口高度，即：不包括导航栏、状态栏以及底部tabbar的高度。

RN 这边暂时比较难实现。
