### ISSUE TITLE
taro Swiper组件在h5页面滑不动,开发者工具和手机上都不能滑动

### ISSUE THREAD

**Issue by wangjingwj** [NervJS/taro#3035]
**问题描述**
taro Swiper组件在h5页面滑不动,开发者工具和手机上都不能滑动

**复现步骤**
js

<Swiper
        className={styles.swiper}
        indicatorColor='#e0e0e0'
        indicatorActiveColor='#666666'
        circular
        indicatorDots
        previous-margin='30px'
        next-margin='30px'
        onChange={this.changeHandle.bind(this)}
      >
        <SwiperItem
          className={styles.swiperitems}
        >
          <Image
            src='https://gd4.alicdn.com/imgextra/i1/2694617348/TB2.omLq8USMeJjy1zkXXaWmpXa_!!2694617348.jpg_400x400.jpg'
          />
        </SwiperItem>
        <SwiperItem
          className={styles.swiperitems}
        >
          <Image
            src='https://gd1.alicdn.com/imgextra/i3/551021376/TB2iZBKd1uSBuNjSsplXXbe8pXa_!!551021376.jpg_400x400.jpg'
          />
        </SwiperItem>
      </Swiper>

css 

.swiper {
  width:100%;
  height:400px;
}

.wrap-image {
  width:100%;
  height:400px;
}

.swiperitems {
  width:100%;
  height:400px;
}

**期望行为**
期望能够滑动

**报错信息**

无

**系统信息**
taro 1.2.26

开发者工具稳定版

安卓手机

**补充信息**
只要打开过h5调试器，都滑不动

**Comment by jinjinjin0731** [comment]
这个问题关了。 你的是在 webview 上 h5 不可滑动。 正常的 h5 页面是ok 的。这个要看下微信社区
