### ISSUE TITLE
如何正确集成lodash？

### ISSUE THREAD

**Issue by kala888** [NervJS/taro#3037]
如何正确集成lodash？
我看taro里面有很多组件都引用了lodash
在项目中直接使用 lodash（并没有在package.json中显示的引入dependencies）
```
import _ from 'lodash'
...
_.filter(....)
```
执行build
```
yarn build:weapp
```
小程序由原来的191KB增长为261KB，是否可以通过
 babel-plugin-lodash 和 lodash-webpack-plugin
 来给小程序瘦身？

**Comment by luckyadam** [comment]
import filter from 'lodash/filter'

**Comment by kala888** [comment]
好吧
