### ISSUE TITLE
微信小程序和 taro 代码并存

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#3039]
![image](https://user-images.githubusercontent.com/25219300/57688730-caa90500-7670-11e9-83df-caa81cedeb5f.png)

如果是在原生小程序写法中以这种方式书写，在 dist 文件夹里面没有对应的文件。

原文件目录结构：

![image](https://user-images.githubusercontent.com/25219300/57688921-25426100-7671-11e9-97cd-f1a7a3cdcc53.png)

编译之后的：

![image](https://user-images.githubusercontent.com/25219300/57688969-355a4080-7671-11e9-9151-6499778d5dfe.png)

**Comment by Garfield550** [comment]
参考：
```tsx
// Component.tsx

export default class HtmlParser extends Component<Props, {}> {
  public render(): JSX.Element {
    const rootClass = classNames(this.props.className);

    return (
      <View className={rootClass}>
        <import src='./wxParser/index.wxml' />
        <template is='wxParser' data='{{wxParserData:richText.nodes}}' />
      </View>
    );
  }
}

```

```js
// config.js

const config = {
  copy: {
    patterns: [
      {
        // 拷贝 wxParser 的样式表
        from: 'src/Components/WxParser/wxParser/index.wxss',
        to: 'dist/Components/WxParser/wxParser/index.wxss',
      },
      {
        // 拷贝 wxParser 的小程序原生页面
        from: 'src/Components/WxParser/wxParser/index.wxml',
        to: 'dist/Components/WxParser/wxParser/index.wxml',
      },
    ],
  },
```

**Comment by patchBig** [comment]
> 参考：
> 
> ```ts
> // Component.tsx
> 
> export default class HtmlParser extends Component<Props, {}> {
>   public render(): JSX.Element {
>     const rootClass = classNames(this.props.className);
> 
>     return (
>       <View className={rootClass}>
>         <import src='./wxParser/index.wxml' />
>         <template is='wxParser' data='{{wxParserData:richText.nodes}}' />
>       </View>
>     );
>   }
> }
> ```
> 
> ```js
> // config.js
> 
> const config = {
>   copy: {
>     patterns: [
>       {
>         // 拷贝 wxParser 的样式表
>         from: 'src/Components/WxParser/wxParser/index.wxss',
>         to: 'dist/Components/WxParser/wxParser/index.wxss',
>       },
>       {
>         // 拷贝 wxParser 的小程序原生页面
>         from: 'src/Components/WxParser/wxParser/index.wxml',
>         to: 'dist/Components/WxParser/wxParser/index.wxml',
>       },
>     ],
>   },
> }
> ```

帮了大忙了 感谢👍
