### ISSUE TITLE
支付宝小程序分包找不到页面

### ISSUE THREAD

**Issue by ooxx87** [NervJS/taro#3040]
支付宝小程序分包找不到页面，但是转成微信可以
`
		pages: [
			'pages/news/home/index',
            'pages/eco/home/index',
			'pages/news/newsDetail/index',
			'pages/user/home/index',
			//'pages/demo/demo',
			'pages/common/userSinglePopView/userSinglePopView',
			'pages/common/orgSinglePopView/orgSinglePopView',
			'pages/common/orgPopView/orgPopView',
			'pages/common/userPopView/userPopView',
			'pages/index/index'
		],
		window: {
			backgroundTextStyle: 'light',
			navigationBarBackgroundColor: '#fff',
			navigationBarTitleText: 'WeChat',
			navigationBarTextStyle: 'black'
		},
		tabBar: {
			"color": "#666666",
			"selectedColor": "#e68478",
			"backgroundColor": "#ffffff",
			"position": "bottom",
			"list": [
				{
					"pagePath": "pages/news/home/index",
					"text": "头条",
					"iconPath": "./images/foot_a.png",
					"selectedIconPath": "./images/foot_a_active.png"
				},
				{
					"pagePath": "pages/index/index",
					"text": "党务",
					"iconPath": "./images/foot_b.png",
					"selectedIconPath": "./images/foot_b_active.png"
				},
				{
					"pagePath": "pages/index/index",
					"text": "AI助理",
					"iconPath": "./images/foot_c.png",
					"selectedIconPath": "./images/foot_c_active.png"
				},
				{
					"pagePath": "pages/eco/home/index",
					"text": "生态",
					"iconPath": "./images/foot_d.png",
					"selectedIconPath": "./images/foot_d_active.png"
				},
				{
					"pagePath": "pages/user/home/index",
					"text": "我的",
					"iconPath": "./images/foot_e.png",
					"selectedIconPath": "./images/foot_e_active.png"
				}
				
			]
		},
		subPackages: [
			{
				"root": "subPackageWork",
				"pages": [
					"pages/meeting/demo/index",
				]
			},
			{
				"root": "subPackageEco",
				"pages": [
                    'pages/detail/index',
                    'pages/personal/index',
					'pages/public/index',
					'pages/answer/release/index',
					'pages/activity/create/index',
					'pages/activity/addActForm/index',
					'pages/activity/addActTypesForm/index',
					
					'pages/activity/edit/index',
					'pages/activity/detail/index',
					'pages/activity/signUp/index',
					'pages/activity/signUpUser/index',
					'pages/activity/staffList/index',
					'pages/vote/addVoteForm/index',
					'pages/vote/voteDetail/index',
					'pages/vote/addTypesForm/index',
					'pages/survey/detail/index',
				]
			}
		],`

**Comment by Chen-jj** [comment]
@ooxx87 提供一下 Taro 版本信息。

**Comment by ooxx87** [comment]
> @ooxx87 提供一下 Taro 版本信息。

taro 1.2.26

**Comment by Chen-jj** [comment]
@ooxx87 CLI 和依赖都升级到 v1.3.0-beta.2 后再试试。

**Comment by ooxx87** [comment]
> @ooxx87 CLI 和依赖都升级到 v1.3.0-beta.2 后再试试。

好的，我先试下，谢谢

**Comment by ooxx87** [comment]
> @ooxx87 CLI 和依赖都升级到 v1.3.0-beta.2 后再试试。

升级到1.3.0-beta.2后依然无法在支付宝小程序里跳转到分包页面

**Comment by ooxx87** [comment]
> @ooxx87 CLI 和依赖都升级到 v1.3.0-beta.2 后再试试。

而且，我发现

> @ooxx87 提供一下 Taro 版本信息。

你好，我试了下在编译完以后的小程序js里改为my.navigateTo 也是无法跳转到分包的。同样的分包配置在原生支付宝小程序中可以

**Comment by ooxx87** [comment]
> @ooxx87 提供一下 Taro 版本信息。

@Chen-jj 你好我试过1.2.6和1.3 beta2了都不行，请问有别的解决方案来让支付宝小程序中的主包跳转到分包吗？

**Comment by Chen-jj** [comment]
@ooxx87 提供一个完整 demo 测试一下？

**Comment by ooxx87** [comment]
> @ooxx87 提供一个完整 demo 测试一下？

今天排查了下，是因为在一个页面用了loadsh的去重，然后这个去重函数在支付宝小程序那边因为版本问题炸了。微信可以跳转分包，支付宝那边就死活不行。重新更新了loadsh包后解决了。

**Comment by ywanhzy** [comment]
@ooxx87   我也使用了import fp from 'lodash/fp' 报错的       现在解决了
