### ISSUE TITLE
taro转字节小程序 px转换显示有问题

### ISSUE THREAD

**Issue by Chen-mbs** [NervJS/taro#3041]
**问题描述**
taro转字节小程序  text 标签的长沙市样式的px数值编译成rpx  但是字节小程序的开发工具是用px显示 导致text的 文字大小总体缩小 

**复现步骤**
[复现问题的步骤]
css样式

.sub-txt-title{
  height: 36px;line-height: 36px;
    font-size: 30px;
    color: black;
}

**期望行为**
解决字节小程序文字缩小的问题

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

1.3版本 taro info  报错

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [Taro v1.3.0-beta.0]
 - Node.js 版本 [10.15.3]
 - 报错平台 [tt]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@Chen-mbs 成功编译到 .ttxs 是 rpx 单位的话，是字节跳动小程序的问题吧

**Comment by shenghanqin** [comment]
@Chen-mbs 是不是designWidth按照375来思考的？
