### ISSUE TITLE
ios端canvas无法接收onLongPress事件

### ISSUE THREAD

**Issue by wangruiStart** [NervJS/taro#3043]
**问题描述**
IOS真机 taro canvas组件只能接收到touchStart, touchMove和touchEnd事件。其他的如onLongPress无法响应。
微信开发者工具可以正常响应，android正常响应。

此外，微信开发者工具组获取到longPress的event对象是普通touch对象，而不是CanvasTouch对象

**复现步骤**
[复现问题的步骤]

```js


press(e){
    console.log('触发了press2');
    if (this.canvas) {
      const touches = [...e.touches];
      if(touches[0]){
        touches[0].x = this.x;
        touches[0].y = this.y;
      }
      console.log('触发了press');
      this.canvas.emitEvent('press', [{...e, touches}]);
    }
  }


<Canvas style={'width: '+this.state.width+'; height:'+this.state.height}
        className='canvas' canvasId='f2-canvas'
        id={id}
        onTouchStart={this.touchStart.bind(this)}
        onTouchMove={this.touchMove.bind(this)}
        onTouchEnd={this.touchEnd.bind(this)}
        onLongPress={this.press.bind(this)} onTouchForceChange={this.press.bind(this)}
      />;
```

**系统信息**

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.0 - /usr/local/bin/node
      Yarn: 1.5.1 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-less: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
    npmGlobalPackages:
      typescript: 2.6.1

**Comment by luckyadam** [comment]
哪个端

**Comment by wangruiStart** [comment]
> 哪个端

IOS 微信小程序
