### ISSUE TITLE
android 5.0.1系统自带浏览器和windows版微信无法运行编译后的h5版本

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#3044]
![QQ截图20190515095739](https://user-images.githubusercontent.com/13210798/57743699-b4df2280-76f8-11e9-8004-11b886a0e4a4.png)
![QQ截图20190515095854](https://user-images.githubusercontent.com/13210798/57743701-b577b900-76f8-11e9-9fbf-cd8c67c23699.png)
![QQ截图20190515095922](https://user-images.githubusercontent.com/13210798/57743703-b6104f80-76f8-11e9-8b19-2fb8d6539d93.png)
![QQ截图20190515100012](https://user-images.githubusercontent.com/13210798/57743705-b6a8e600-76f8-11e9-8ce8-401ce43882bd.png)

**Comment by luckyadam** [comment]
可以升级到 1.3.0-beta.2 版本，这个问题已经修复了

**Comment by Littly** [comment]
确实还残留了一个find的调用 下个版本修复~

**Comment by kucy** [comment]
> 可以升级到 1.3.0-beta.2 版本，这个问题已经修复了

我升级了1.3.0-beta.2，发现这两个问题依然还在。

**Comment by pandaXiong01** [comment]
android 5.0 系统自带浏览器1.3.0确实存在这个问题
