### ISSUE TITLE
微信小程序和 taro 混写

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#3045]
发现第一次编辑的时候，页面能够正常打开，但是控制台报了一个错误，并且在 app.js 文件里面并不能正常调用 Taro.getApp

![image](https://user-images.githubusercontent.com/25219300/57745043-2372af00-76fe-11e9-87e9-451a28dc48e5.png)

**Comment by vimcaw** [comment]
信息太少了，请补充源代码，并点击报错右侧的 js 位置提示跳转到对应的文件，补充报错附近的代码。

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/57830177-e08b0700-77e3-11e9-880c-4d416a0bc1f2.png)
![image](https://user-images.githubusercontent.com/25219300/57830189-e97bd880-77e3-11e9-8fb7-2ff1faa6c5da.png)

**Comment by patchBig** [comment]
> 信息太少了，请补充源代码，并点击报错右侧的 js 位置提示跳转到对应的文件，补充报错附近的代码。

这个就是附近的报错，不知道怎么去排查。。。

**Comment by vimcaw** [comment]
方便的话可以附上相关的源代码吗

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/57831200-0665db00-77e7-11e9-8a26-06830c6df799.png)
还有一个问题 就是编码之后发现变成中文了

**Comment by patchBig** [comment]
> 方便的话可以附上相关的源代码吗

打开编译工具的 es6 转 es5 就好了

但是上面那个字体文件变化的问题还是不知道

**Comment by vimcaw** [comment]
在我这里是没问题的，字体文件变化时是开启了 es6 转 es5 吗，或者有没有用其他的处理程序处理过，如果都没有可以在项目下运行`taro info`复制输出的信息粘贴到这里。

**Comment by patchBig** [comment]
> taro info

![image](https://user-images.githubusercontent.com/25219300/57851327-d8968b80-7812-11e9-967f-85f55085b30e.png)

字体文件变化不是开启 es5 导致的，只是编译之后最上面的会多一个 `@charset "UTF-8";`

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/57851532-61adc280-7813-11e9-8206-d8c48249d0f0.png)
