### ISSUE TITLE
项目中nervjs没有更新

### ISSUE THREAD

**Issue by afateg** [NervJS/taro#3046]
**问题描述**
在执行 `taro update self` 和 `taro update project` 之后，项目中的nervjs依然没有更新， `taro info` 中显示 `nervjs: ^1.3.0 => 1.3.13`。

**复现步骤**
1. `taro update self`
2. `taro update project`
3. `taro info`

**期望行为**
为什么nervjs没有更新？如何才能更新？

**报错信息**
无

**系统信息**
$ taro info
👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 1.2.26 => 1.2.26
      @tarojs/components: 1.2.26 => 1.2.26
      @tarojs/plugin-babel: 1.2.26 => 1.2.26
      @tarojs/plugin-csso: 1.2.26 => 1.2.26
      @tarojs/plugin-sass: 1.2.26 => 1.2.26
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26
      @tarojs/router: 1.2.26 => 1.2.26
      @tarojs/taro: 1.2.26 => 1.2.26
      @tarojs/taro-h5: 1.2.26 => 1.2.26
      @tarojs/taro-weapp: 1.2.26 => 1.2.26
      @tarojs/webpack-runner: 1.2.26 => 1.2.26
      eslint-config-taro: 1.2.26 => 1.2.26
      eslint-plugin-taro: 1.2.26 => 1.2.26
      nervjs: ^1.3.0 => 1.3.13

 - 操作系统: macOS 10.14.4
 - Taro 版本 v1.2.26
 - Node.js 版本 v11.10.1
 - 报错平台 

**补充信息**
无

**Comment by yuche** [comment]
npm i nervjs@版本号
