### ISSUE TITLE
1.3.0-beta.2 slot问题

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#3047]
我这里有个A组件
```jsx
function A(props) {
  return (
    <View>
      {props.renderA}
      <View>{props.children}</View>
      {props.renderB}
    </View>

  )
}
```

页面使用A组件
```jsx
function pageA() {
  return (
    <A renderA={<View>666</View>} renderB={<View>777</View>} renderC={<View>888</View>}>
      kkk
    </A>
  )
}
```
结果 renderC 也被渲染出来了，且renderA，renderB也不在对应位置，我如果把props.children注释掉，结果什么都不会渲染。

下面截图是栗子
<img width="373" alt="image" src="https://user-images.githubusercontent.com/24502330/57759657-f4276680-772c-11e9-9720-094c7b80a127.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/24502330/57759618-de19a600-772c-11e9-87f3-533a87b4f9b2.png">

<img width="292" alt="image" src="https://user-images.githubusercontent.com/24502330/57759994-66984680-772d-11e9-8225-7370e259bef2.png">

**Comment by yuche** [comment]
先写 this.props.renderA 吧
