### ISSUE TITLE
（ v0.0.68）莫名报错：module "npm/@tarojs/taro-weapp/index.js" is not defined

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro#305]
重启微信开发者工具后该错误会消失（此时即便是点击重新编译的按钮，页面刷新后也不会再报错），但重启 taro 编译（`Ctrl+C` && `npm run dev:weapp`）后还是会报错

![image](https://user-images.githubusercontent.com/13287948/42564638-e21885aa-8533-11e8-815b-50ec539daaac.png)

**Comment by kenberkeley** [comment]
我都怀疑是不是 taro 的问题。。。

**Comment by a591371947** [comment]
没人处理吗这个问题

**Comment by sumaolin** [comment]
#2233 是正解了，先启动编译，在启动微信开发者工具
