### ISSUE TITLE
H5   IOS 微信浏览器，页面没有正常跳转，会出现重叠

### ISSUE THREAD

**Issue by aushion** [NervJS/taro#3057]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

**问题描述**

IOS 微信浏览器 页面跳转会出现重叠，安卓机没有问题

**复现步骤**

1. 从首页进入A页面
2. A页面点击按钮跳转到B页面
3. 会出现两个A页面，一个B页面从上到下依次排列的情况
4. 以下是A页面的代码

```
export default class Test extends Taro.Component {
  handleClick = () => {
    Taro.navigateTo({
      url: '../result/index?question=test'
    })
  }
  render() {
    return (
      <View >
        <Button onClick={this.handleClick.bind(this)}>点击跳转</Button>
      </View>
    );
  }
}

 ```

**期望行为**
B页面能够完整出现，而不是重叠出现

**报错信息**
这是在A页面点击跳转按钮后的结果
![image](https://user-images.githubusercontent.com/12783375/57822897-17532400-77c8-11e9-814f-f4ab4cc94e88.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.3.0-beta.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
只有IOS会有这个问题，安卓包括桌面端没有这个问题

**Comment by aushion** [comment]
已经解决，是我首页的跳转是写在首页输入框的focus事件里的，首页input的focus难道会和过渡页input的focus造成混淆，发生干扰?不得而知，没有进一步测试。我先关了吧

**Comment by 1361033362** [comment]
我也遇到这种情况 但是是在支付宝小程序的IOS才会出行 但是我就是单纯的跳转
