### ISSUE TITLE
src以外文件夹编译问题

### ISSUE THREAD

**Issue by innocces** [NervJS/taro#306]
**问题描述**
最近在开发一套基于taro的组件库，在src以外建立了component文件夹，但是编译有问题，而且在编译过程中会将我component文件夹的入口文件index.js自动babel掉，这个不知道为什么会有这样的机制。
![tarobug](https://user-images.githubusercontent.com/38065966/42564746-25fdd540-8534-11e8-890f-3c2cb1f5d3ed.png)
这样不知道是和编译机制有关还是如何
**复现步骤**
[复现问题的步骤]
源码如下
```js
import Taro, { Component } from '@tarojs/taro'
import { Button, View } from '@tarojs/components'

import './button.scss'

export default class TaroButton extends Component {
  render () {
    return (
      <View>
        <Button>111</Button>
      </View>
    )
  }
}
```

**报错信息**
![tarobug](https://user-images.githubusercontent.com/38065966/42564746-25fdd540-8534-11e8-890f-3c2cb1f5d3ed.png)

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.0.0.68]
 - Node.js 版本 [e.g. v10.3.0]

**Comment by innocces** [comment]
补充被babel掉的入口文件
![babel](https://user-images.githubusercontent.com/38065966/42564966-bedae550-8534-11e8-98bf-bd7319b16462.png)
![bf](https://user-images.githubusercontent.com/38065966/42564968-bf3794e4-8534-11e8-8f3e-089409fefc91.png)

**Comment by luckyadam** [comment]
嗯嗯，不能在 src 目录外放业务代码

**Comment by innocces** [comment]
那入口文件为什么会被自动babel掉

**Comment by innocces** [comment]
![default](https://user-images.githubusercontent.com/38065966/42608339-db3cf262-85b9-11e8-8ce8-58ed07644e9f.png)
放到src里面y也是报一样的错误

**Comment by luckyadam** [comment]
嗯嗯，目前的机制是引用的文件都会经过 babel 编译~ 这个报错是因为这个组件文件被 import 了但是没有在 jsx 里使用到，升级到最新版本的 Taro 就没有这个问题了
