### ISSUE TITLE
支付宝小程序跳转分包页面会报找不到页面

### ISSUE THREAD

**Issue by ooxx87** [NervJS/taro#3061]
**问题描述**
支付宝小程序跳转分包页面会报找不到页面

**复现步骤**
支付宝小程序跳转分包页面会报找不到页面

**期望行为**
在支付宝能跳转分包页面

**报错信息**
找不到分包页面

**系统信息**
> Taro v1.2.6 以及 1.3 beta2

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [aliapy]

**Comment by shenghanqin** [comment]
@ooxx87 请给出更具体一些的源代码、截图、Demo。
