### ISSUE TITLE
设置 onPullDownRefresh 方法 h5 会触发

### ISSUE THREAD

**Issue by kid1412621** [NervJS/taro#3062]
**问题描述**
页面设置 `onPullDownRefresh` 方法 ,哪怕页面级别设置了 `config = {  enablePullDownRefresh: false }` 也会滚动.
**此外, 但是官方文档明确写的 h5 不支持啊**

**复现步骤**
同上

**期望行为**
h5 不支持就不滚动

**报错信息**

**系统信息**
Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by yuche** [comment]
不支持的意思就是无法用这个参数控制

**Comment by kid1412621** [comment]
@yuche 那不能控制包括非预期行为吗？
