### ISSUE TITLE
RN 0.55.4 上传图片bug 

### ISSUE THREAD

**Issue by ChengGPBU** [NervJS/taro#3063]
**问题描述**
RN端上传图片功能  
![image](https://user-images.githubusercontent.com/24949641/57835563-5c3f8080-77f1-11e9-8971-fc2c07fd7911.png)

**复现步骤**
[复现问题的步骤]
1. Android端选择相册图片上传
// 这里可以贴代码

**期望行为**
RN端正常上传图片

**报错信息**
![image](https://user-images.githubusercontent.com/24949641/57835638-93159680-77f1-11e9-87b3-65ab64a42a35.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [ macOS 10.14.4]
 - Taro 版本 [v1.3.0-beta.2]
 - Node.js 版本 [ 12.1.0 ]
 - 报错平台 [rn]

**补充信息**
RN 0.57.2 已修复 希望taro 同步更新到RN高版本
https://github.com/facebook/react-native/commit/9e377c394779a23af755189737bdca7b89f7412f

**Comment by Pines-Cheng** [comment]
直接贴代码？

**Comment by Pines-Cheng** [comment]
可以参考一下这个：[How to Upload Images in a React Native App(]https://heartbeat.fritz.ai/how-to-upload-images-in-a-react-native-app-4cca03ded855)
