### ISSUE TITLE
Taro 编译成H5 Taro.request对象为空

### ISSUE THREAD

**Issue by Ucself** [NervJS/taro#3066]
**问题描述**
Taro 编译成H5 Taro.request对象为空

**复现步骤**
![image](https://user-images.githubusercontent.com/5546554/57837274-0e2c7c00-77f5-11e9-9ed7-dd754dc4dd64.png)

![image](https://user-images.githubusercontent.com/5546554/57837284-171d4d80-77f5-11e9-848e-a80694b7b2a2.png)

![image](https://user-images.githubusercontent.com/5546554/57837301-1e445b80-77f5-11e9-9d93-bf29d917b64c.png)

**期望行为**
正常调用

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
 - 操作系统: MAC
 - Taro 版本: v1.2.8
 - Node.js 版本: v11.8.0
 - 报错平台: h5

**补充信息**

**Comment by Littly** [comment]
@tarojs/cli 和 @tarojs/taro-h5 分别是什么版本？
