### ISSUE TITLE
用taro写微信小程序，引入redux-form报错

### ISSUE THREAD

**Issue by zilan830** [NervJS/taro#3067]
**问题描述**
用taro的redux模板写微信小程序，引入redux-form报错
![image](https://user-images.githubusercontent.com/13581409/57833344-6743e200-77ec-11e9-8864-6bf045d293f7.png)
![image](https://user-images.githubusercontent.com/13581409/57833567-d9b4c200-77ec-11e9-9a71-58bb5434d004.png)

**代码**
因为是用的 taro redux 模板，没有变得地方就不贴了，就把有改动的地方贴出来。

reducer.js
```js
import { combineReducers } from 'redux'
import { reducer as formReducer } from 'redux-form'
export default combineReducers({
  form:formReducer
})
```

index.js
```js
import Taro, { Component } from "@tarojs/taro"
import { View } from "@tarojs/components"
import { connect } from "@tarojs/redux"
import { Field, reduxForm } from "redux-form"

import TextInput from "./textInput"

import "./index.less"

const mapStateToProp = (state,props) => {
  console.log("state",state,"props",props)
  return{
    ...state
  }
}

@connect(mapStateToProp)
@reduxForm({
  form: "testForm"
})
class Index extends Component {
  config = {
    navigationBarTitleText: "首页"
  }

  constructor(props){
    super(props)
  }

  render() {
    return (
      <View className='index'>
          <Field name='inputField' component={TextInput} placeholder='请填写' />
      </View>
    )
  }
}

export default Index
```

textInput.js
```js
import Taro, { Component } from "@tarojs/taro"
import { Input } from "@tarojs/components"

export default class InputField extends Component {
  render() {
    const { input, placeholder } = this.props
    return <Input placeholder={placeholder} value={input.value} />
  }
}
```

**期望行为**
在用taro写微信小程序时，可以使用redux-form。

**报错信息**
![image](https://user-images.githubusercontent.com/13581409/57833344-6743e200-77ec-11e9-8864-6bf045d293f7.png)
![image](https://user-images.githubusercontent.com/13581409/57833567-d9b4c200-77ec-11e9-9a71-58bb5434d004.png)

**系统信息**
 - 操作系统: [macOS 10.14.4]
 - Taro 版本 [v1.2.26]
 - Node.js 版本 [v11.9.0]
 - 报错平台 [weapp]

**Comment by BennyEu** [comment]
现在能用了吗？

**Comment by shenghanqin** [comment]
@zilan830 你好，方便用最新版本再测试一下吗？你的图片已经无法查看了，方便的话可以重新提供一下截图。
