### ISSUE TITLE
在部分x5内核的浏览器上会报Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by hahaiamzd** [NervJS/taro#3069]
问题描述
在华为旧机型自带的浏览器和在qq浏览器app下，浏览的页面是空白页，通过spy-debugger得到错误:Uncaught TypeError: undefined is not a function.

附：手机浏览器UA信息
 Mozilla/5.0(Linux;Android 5.1;zh-cn;
 HUAWEI CUN-TL00 Build/CUN-TL00)
 AppleWebKit/537.36(KHTML,like Geoko)
Version/4.0 Mobile Safari/537.36

复现步骤
①用Android模拟器上安装qq浏览器HD版本
②访问http://h5.test.hengqihj.com

如需要查看报错信息，则安装spy-debugger，根据教程操作即可查看到报错信息。

期望行为
希望能正常访问。

报错信息

Uncaught TypeError: undefined is not a function.

系统信息
  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: ^1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
补充信息

无

**Comment by Littly** [comment]
与 #3044 #2963 是同个问题 升级到1.3.0-beta.3试试

**Comment by hahaiamzd** [comment]
> 与 #3044 #2963 是同个问题 升级到1.3.0-beta.3试试

升级版本后重新打包还是会报同样的错误。

**Comment by Littly** [comment]
可以继续升级试试。有部分代码调用了findIndex，已经去掉。

**Comment by toFrankie** [comment]
2022 年了，华为 P10 Plus 打开页面也会空白页（QQ浏览器、X5 内核、EMUI 8.0.0、Android 8.0.0）
