### ISSUE TITLE
使用案例 中的很多案例已经打不开了或者打开登录不了了，或者搜都搜不到了。请问这跟他们使用了taro方案有关吗？

### ISSUE THREAD

**Issue by yfhk** [NervJS/taro#3072]
使用案例 中的很多案例已经打不开了或者打开登录不了了，或者搜都搜不到了。请问这跟他们使用了taro方案有关吗

**Comment by yuche** [comment]
业务能不能继续开展，开展得顺不顺利是一个业务问题，不是一个技术问题。
这个问题你可以问他们的老板，产品经理，运营，Taro 能决定的只有开发者的开发体验和开发效率。
