### ISSUE TITLE
1.3.0@beta2  出现 Cannot read property 'designWidth' of undefined 的问题

### ISSUE THREAD

**Issue by lentoo** [NervJS/taro#3073]
**问题描述**
在 1.2.26版本是正常的，然后升级到 1.3.0@beta2 
出现 Cannot read property 'designWidth' of undefined 的问题

**复现步骤**

在 1.2.26版本是正常的，然后升级到 1.3.0@beta2 

**期望行为**

正常使用

**报错信息**

![image](https://user-images.githubusercontent.com/24666230/57899745-c22f1500-7890-11e9-9ba7-6275717b1a53.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0@beta2]
 - Node.js 版本 [e.g. v8.11.4]
 - 报错平台 [weapp]

**Comment by Pines-Cheng** [comment]
哪个平台？

**Comment by lentoo** [comment]
weapp

**Comment by zhangfu-git** [comment]
开发插件遇到相同的问题

**Comment by yuche** [comment]
这类问题都是项目依赖和 CLI 版本不一致导致的
