### ISSUE TITLE
H5 Input 组件在iOS8系统下存在Bug

### ISSUE THREAD

**Issue by Sdoy** [NervJS/taro#3079]
**问题描述**

Input组件在iOS8的Safari H5下无法正常工作,没有回调onInput或者onChange

**报错信息**

![image](https://user-images.githubusercontent.com/10302939/57916031-a180b280-78c4-11e9-89d6-5fb8128f4892.png)

**系统信息**
👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/opt/node@8/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.12

**Comment by githubmann** [comment]
ios8 不支持 includes 方法
