### ISSUE TITLE
beta版本一直无法为组件定义外部样式

### ISSUE THREAD

**Issue by ChandlerVer5** [NervJS/taro#3080]
** 问题描述 **
#### 目前有两个问题：
1.  无法为组件定义外部样式
  ```
  static externalClasses = ['custom-class']; //组件接受的外部样式类
  ```
  生成为以下代码：

  ```
  <t-button compid="{{$compid__289}}" />
  ```

  手动修改编译后文件，如下，才能在百度和微信小程序中生效：

  ```
  <t-button custom-class="status" compid="{{$compid__289}}" />
  ```
  另外：
  ~~`taro doctor` 检测`jsxAttributeNameReplace、alias`不被支持？ 这里提了: https://github.com/NervJS/taro/issues/2947#issuecomment-493373462~~

2. 组件传递事件，有情况会无法访问`this`。
  示例：
  组件中：
  ```js
    fun1(e){
        this.props.onShowXxx(e);
    }
  ```
  组件外，`onShowXxx`：
  ```js
  onShowXxx(params){
    // 此处无法访问 this
    this.setState({
      xxx:params,
    })
  } 
  // 修改为
  onShowXxx = (params) =>{
    // 此处可以访问 当前this
    this.setState({
      xxx:params,
    })
  } 
  ```

** 系统信息 **
� Taro v1.3.0 - beta.3

Taro CLI 1.3.0 - beta.3 environment info:
System:
OS: Windows 10
Binaries:
Node: 11.2.0 - D: \Applications\Scoop\apps\nvm\current\nodejs\nodejs\node.EXE
Yarn: 1.16.0 - D: \ScoopApp\apps\yarn\current\Yarn\bin\yarn.CMD
npm: 6.4.1 - D: \Applications\Scoop\apps\nvm\current\nodejs\nodejs\npm.CMD

** 补充信息 **
  [可选]

生成为以下代码：

```
 <t-button compid="{{$compid__289}}" />
```

手动修改编译后文件，如下，才能在百度和微信小程序中生效：

```
 <t-button custom-class="status" compid="{{$compid__289}}" />
```

** 问题描述 **
  1.3.0 - beta.2无法为组件定义外部样式
  ```
  static externalClasses = ['custom-class']; //组件接受的外部样式类
  ```

** 系统信息 **
� Taro v1.3.0 - beta.3

Taro CLI 1.3.0 - beta.3 environment info:
System:
OS: Windows 10
Binaries:
Node: 11.2.0 - D: \Applications\Scoop\apps\nvm\current\nodejs\nodejs\node.EXE
Yarn: 1.16.0 - D: \ScoopApp\apps\yarn\current\Yarn\bin\yarn.CMD
npm: 6.4.1 - D: \Applications\Scoop\apps\nvm\current\nodejs\nodejs\npm.CMD

**Comment by yuche** [comment]
1. https://github.com/NervJS/taro/issues/2077
2. 你更改后的写法是对的，正常的 React 也需要 bind this 或者使用箭头函数

**Comment by ChandlerVer5** [comment]
> 1. #2077
> 2. 你更改后的写法是对的，正常的 React 也需要 bind this 或者使用箭头函数

1. 我试过，不行啊
2. 🆗

**Comment by kukelove** [comment]
1. 没有用啊，我晕

**Comment by kukelove** [comment]
> > 1. #2077
> > 2. 你更改后的写法是对的，正常的 React 也需要 bind this 或者使用箭头函数
> 
> 1. 我试过，微信百度不行啊，另外支付宝和头条不支持吧。
> 2. 🆗

楼主解决了，说下吧，无解啊

**Comment by ChandlerVer5** [comment]
> > > 1. #2077
> > > 2. 你更改后的写法是对的，正常的 React 也需要 bind this 或者使用箭头函数
> > 
> > 
> > 
> > 1. 我试过，微信百度不行啊，另外支付宝和头条不支持吧。
> > 2. 🆗
> 
> 楼主解决了，说下吧，无解啊

？第一个没解决，第二个我用箭头

**Comment by Garfield550** [comment]
```js
const that = this;
onShowXxx(params) {
  that.setState({
    xxx:params,
  })
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_separate_this

**Comment by skymoonya** [comment]
第一个问题我也遇到了，这么久了，官方有修复计划么 @yuche

**Comment by ChandlerVer5** [comment]
beta版本一直无法为组件定义外部样式，推荐 `customStyle` 属性传入，可以多端兼容。

**Comment by skymoonya** [comment]
@ChandlerVer5 刚刚开始写小程序，因为之前用的react，所以选择了taro，没找到`customStyle `的相关文档和用法，方便给个链接么

**Comment by ChandlerVer5** [comment]
> @ChandlerVer5 刚刚开始写小程序，因为之前用的react，所以选择了taro，没找到 customStyle  的相关文档和用法，方便给个链接么

在组件中自定义 `customStyle` 传入啊，我是这个意思.

**Comment by skymoonya** [comment]
> > @ChandlerVer5 刚刚开始写小程序，因为之前用的react，所以选择了taro，没找到 customStyle  的相关文档和用法，方便给个链接么
> 
> 在组件中自定义 `customStyle` 传入啊，我是这个意思.

那样式不是得用全局的

**Comment by ChandlerVer5** [comment]
> > > @ChandlerVer5 刚刚开始写小程序，因为之前用的react，所以选择了taro，没找到 customStyle  的相关文档和用法，方便给个链接么
> > 
> > 
> > 在组件中自定义 `customStyle` 传入啊，我是这个意思.
> 
> 那样式不是得用全局的

你写在代码里传入啊

**Comment by skymoonya** [comment]
> > > > @ChandlerVer5 刚刚开始写小程序，因为之前用的react，所以选择了taro，没找到 customStyle  的相关文档和用法，方便给个链接么
> > > 
> > > 
> > > 在组件中自定义 `customStyle` 传入啊，我是这个意思.
> > 
> > 
> > 那样式不是得用全局的
> 
> 你写在代码里传入啊

懂了，行内样式传入

**Comment by youngluo** [comment]
![image](https://user-images.githubusercontent.com/7480381/59263614-fb7e5900-8c73-11e9-9747-804368df68f7.png)
v1.3.0 同样存在这个问题，升级后对当前项目影响较大，不知有解决方案吗？ 
@luckyadam @yuche

**Comment by wkl007** [comment]
升级后同样有这个问题，望解决

**Comment by liu-dongyu** [comment]
v1.3.2，函数式的写法好像也不行，望解决
```JavaScript
function Com() {
  return <View className="my-class">demo</View>
}

Com.externalClasses = ['my-class']

export default Com
```

**Comment by wkl007** [comment]
```
<UIcon
 icon='icon-fanhuizhuye'
 color='#373737'
 size={48}
 customStyle={{
  display: `inline-block`,
  marginTop: `-3rpx`
  }}
/>
```
我现在都是给组件传customStyle了
