### ISSUE TITLE
Taro h5端 Slider 只支持拖拽，不支持点击

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#3086]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
H5端的Slider使用的时候可以通过拖拽改变数值，但是不能通过点击某个位置跳转到具体的值，想实现如下效果：
![image](https://user-images.githubusercontent.com/29176413/57964163-160a2e80-7963-11e9-919c-6d9757338f76.png)
点击红圈位置，跳转到下面的效果：
![image](https://user-images.githubusercontent.com/29176413/57964165-26220e00-7963-11e9-871e-89628c3e2396.png)

**Comment by shenghanqin** [comment]
@SunnyQjm 微信官方的Swiper组件和Slider组件，都不支持点击跳转。

https://developers.weixin.qq.com/miniprogram/dev/component/slider.html

**Comment by forgotwho** [comment]
微信官方的 Slider组件，现在是支持点击跳转的。只支持拖拽，不支持点击，体验很不好，能否解决一下
，
