### ISSUE TITLE
Taro.getImageInfo API 在 web( h5 ) 不能使用, 与文档不符

### ISSUE THREAD

**Issue by kid1412621** [NervJS/taro#3087]
**问题描述**
Taro.getImageInfo API 在 web( h5 ) 不能使用, 与 [文档](https://nervjs.github.io/taro/docs/apis/multimedia/images/getImageInfo.html) 不符。类似情况还有，请更新下文档，这样很浪费开发者时间啊。

**复现步骤**
web 环境调用 API

**期望行为**
文档和实际行为一致
![image](https://user-images.githubusercontent.com/26278054/57964539-4d7bd980-7969-11e9-81b3-62789d60c89b.png)

**报错信息**
![image](https://user-images.githubusercontent.com/26278054/57964525-3b01a000-7969-11e9-9b3d-f76b037386b1.png)

**系统信息**
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
无

**Comment by Littly** [comment]
升级到1.3.0-beta.2

**Comment by kid1412621** [comment]
> 1.3.0-beta.2

nb 了, h5 报错:
```
Uncaught TypeError: Cannot read property 'isRoute' of undefined
    at findRef (index.js?56fb:212)
    at createCanvasContext (createCanvasContext.js?3cd4:10)
    at WrappedComponent.onGenPost (index.js?7a4d:86)
    at CourseItem.toGenPost (index.js?5998:30)
    at dispatchEvent (index.esm.js?eb37:508)
    at dispatchEvent (index.esm.js?eb37:518)
    at HTMLDocument.eventHandler (index.esm.js?eb37:546)
```
还有,请问下getImageInfo 在小程序端要获取本地图片应该怎么写呢? 我图片在 `/asset/image/` 下, 但是微信那边报错, 路径前面加了 `/pages/` 怎么破啊?

**Comment by Littly** [comment]
> > 1.3.0-beta.2
> 
> nb 了,版本未发, 文档先行 , h5 报错:
> 
> ```
> Uncaught TypeError: Cannot read property 'isRoute' of undefined
>     at findRef (index.js?56fb:212)
>     at createCanvasContext (createCanvasContext.js?3cd4:10)
>     at WrappedComponent.onGenPost (index.js?7a4d:86)
>     at CourseItem.toGenPost (index.js?5998:30)
>     at dispatchEvent (index.esm.js?eb37:508)
>     at dispatchEvent (index.esm.js?eb37:518)
>     at HTMLDocument.eventHandler (index.esm.js?eb37:546)
> ```
> 
> 还有,请问下getImageInfo 在小程序端要获取本地图片应该怎么写呢? 我图片在 `/asset/image/` 下, 但是微信那边报错, 路径前面加了 `/pages/` 怎么破啊?

你的`getImageInfo`是怎么调用的？

**Comment by kid1412621** [comment]
> > > 1.3.0-beta.2
> > 
> > 
> > nb 了，版本未发，文档先行，h5 报错:
> > ```
> > Uncaught TypeError: Cannot read property 'isRoute' of undefined
> >     at findRef (index.js?56fb:212)
> >     at createCanvasContext (createCanvasContext.js?3cd4:10)
> >     at WrappedComponent.onGenPost (index.js?7a4d:86)
> >     at CourseItem.toGenPost (index.js?5998:30)
> >     at dispatchEvent (index.esm.js?eb37:508)
> >     at dispatchEvent (index.esm.js?eb37:518)
> >     at HTMLDocument.eventHandler (index.esm.js?eb37:546)
> > ```
> > 
> > 
> > 还有，请问下 getImageInfo 在小程序端要获取本地图片应该怎么写呢？我图片在 `/asset/image/` 下，但是微信那边报错，路径前面加了 `/pages/` 怎么破啊？
> 
> 这个错貌似是因为你的 cli 没有一起升级导致的
> 
> 你的 `getImageInfo` 是怎么调用的？

也升级了哈, Taro v1.3.0-beta.3

```
  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```
调用:
```javascript
 const ctx = Taro.createCanvasContext('post-canvas', this.$scope)
    Taro.getImageInfo({
      src: img.src,
    }).then(res => {
      ctx.drawImage(res.path, 0, 0, 750, 400, 750, 400)
      ctx.draw();
    })
```

还有, 想问下要调用本地图片应该怎调用?

**Comment by Garfield550** [comment]
开发之前参考[小程序文档](https://developers.weixin.qq.com/miniprogram/dev/api/wx.getImageInfo.html)先

然后我这边只有小程序的代码，你可以参考下
```ts
  const imageInfo = await Taro.getImageInfo({
    src: this.CheckInPosterImageUrl,
  });

  if (imageInfo.path) {
    try {
      const status = await Taro.saveImageToPhotosAlbum({
        filePath: imageInfo.path,
      });
      if (status.errMsg.includes('ok')) {
        Taro.hideLoading();
        Toast.Success('保存成功');
      }
    } catch (error) {
      Toast.Message('保存失败，请重试');
    }
  }
```

**Comment by kid1412621** [comment]
> ```ts
> Taro.getImageInfo
> ```

嗯, 本地图片不用 `Taro.getImageInfo` 了吧? 我发现 `drawImage`  本地图片直接写相对路径又可以了, 神奇了
