### ISSUE TITLE
1.3.0 页面如何同时支持 hooks 和 config (及页面特有生命周期事件)?

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#3088]
使用 hooks 的前提是组件必须为 FunctionComponent.

[NervJS/taro-v2ex-hooks](https://github.com/NervJS/taro-v2ex-hooks/blob/master/src/pages/hot/hot.tsx) 例子中展示了页面也可以是 function.
在这种情况下, 页面配置 (navigationBarTitleText 等) 和页面事件 (componentDidShow onShareAppMessage 等) 该如何设置?

```ts
function IndexPage() {
    this.config = {
        navigationBarTitleText: '首页',
    }

    return (
		<h1>首页</h1>
	)
}

IndexPage.prototype.config = {
    navigationBarTitleText: '首页',
}

IndexPage.config = {
    navigationBarTitleText: '首页',
}

export default IndexPage
```

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/3054
