### ISSUE TITLE
taro 1.3beta2 小程序跳转分包navigationBarTitleText失效，会用默认的标题替换页面中的配置

### ISSUE THREAD

**Issue by ooxx87** [NervJS/taro#3089]
**问题描述**
taro 1.3beta2 小程序跳转分包navigationBarTitleText失效，会用默认的标题替换页面中的配置

**期望行为**
跳转分包页面后，能显示分包页面中通过config配置的标题

**Comment by shenghanqin** [comment]
`Taro info`给出小程序更完整的信息，另外，请使用最新版尝试一下？
