### ISSUE TITLE
v1.3.0-beta.2 百度小程序自定义组件 iconfont 不显示

### ISSUE THREAD

**Issue by Shalhvi** [NervJS/taro#3090]
**问题描述**
v1.3.0-beta.2 百度小程序自定义组件 iconfont不显示，微信小程序显示正常

**复现步骤**
```jsx
// app.ts
import './font/iconfont.scss'
```

```jsx
// 父组件
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { IProps, IState } from './type'
import './style.scss'

import { ComponentClass } from 'react'

import FloatingBtn from '../../components/FloatingBtn'

class Test extends Component<IProps, IState> {
  constructor(props: IProps) {
    super(props)
  }

  static options = {
    addGlobalClass: true
  }

  render() {
    return (
      <View className='test'>
        <FloatingBtn  />
      </View>
    )
  }
}

export default Test as ComponentClass<IProps, IState>
```

```jsx
// 子组件
import { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { IProps, IState } from './type'
import './style.scss'

export default class extends Component<IProps, IState> {
  constructor(props: IProps) {
    super(props)
  }

  static options = {
    addGlobalClass: true
  }

  render() {
    return (
      <View className='iconfont icon-btn_hyh'>
    )
  }
}
```

**期望行为**
百度小程序自定义组件显示iconfont

**报错信息**
无

**系统信息**
👽 Taro v1.3.0-beta.2
  Taro CLI 1.3.0-beta.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm

 - 报错平台 [swan]

**Comment by Chen-jj** [comment]
@Shalhvi v1.3.0-beta5 测试正常，升级后再试试吧。

App.js

```js
import './font/iconfont.css'
```

页面：

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import A from '../../components/a/a'

export default class Detail extends Component {
  render () {
    return (
      <View className='index'>
        <A />
      </View>
    )
  }
}
```

组件：

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class A extends Component {
  static options = {
    addGlobalClass: true
  }
  render() {
    return <View className='iconfont iconfont-left-circle' style='font-size: 24px;' />
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/58393664-2eb8c980-8072-11e9-8f9c-1a06a730d6c3.png)

**Comment by ckytx** [comment]
我也遇到这个问题
👽 Taro v1.3.0-beta.5
  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3
      Yarn: 1.16.0
      npm: 6.9.0

![批注 2019-05-27 150948](https://user-images.githubusercontent.com/5945838/58402134-31c3b200-8092-11e9-8fbe-3c037629c161.jpg)
![批注 2019-05-27 151132](https://user-images.githubusercontent.com/5945838/58402161-3e480a80-8092-11e9-97fd-bffaa45b79bc.jpg)

**Comment by skymoonya** [comment]
![image](https://user-images.githubusercontent.com/13905873/58466420-3a88b680-816c-11e9-9167-e335c82c7b24.png)
![image](https://user-images.githubusercontent.com/13905873/58466583-83d90600-816c-11e9-9938-274946a579b4.png)
一样的问题，但是在微信开发者工具中是ok的

**Comment by Chen-jj** [comment]
@ckytx @skymoonya 提供一个完整可复现的项目 demo 我测试下吧。

**Comment by ckytx** [comment]
@Chen-jj 
[test.zip](https://github.com/NervJS/taro/files/3226717/test.zip)
工具上无法显示，但是手机端预览正常，dist没删除是我本地编译好的
可以看我之前截图，组件里的class没有全局的class名

**Comment by skymoonya** [comment]
[c-mini-program.tar.gz](https://github.com/NervJS/taro/files/3227134/c-mini-program.tar.gz)
@Chen-jj 和 @ckytx 不同的是我在手机端预览也有问题

**Comment by Chen-jj** [comment]
#3239

**Comment by Chen-jj** [comment]
@ckytx @skymoonya 等百度开发者工具下一个版本再试试。

**Comment by skymoonya** [comment]
> @ckytx @skymoonya 等百度开发者工具下一个版本再试试。

了解

**Comment by ckytx** [comment]
> @ckytx @skymoonya 等百度开发者工具下一个版本再试试。
百度更新了开发工具2.2.7，可以显示了，谢谢了

**Comment by Chen-jj** [comment]
@Shalhvi @skymoonya @ckytx 百度开发者工具，基础库改为 3.60.16 即可。
