### ISSUE TITLE
H5 Image 组件 onLoad 回调触发，但是参数不对

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#3091]
**问题描述**
H5端在使用Image组件的onLoad回调获取图片加载完成后的宽高，期望得到下面文档中叙述的效果
![image](https://user-images.githubusercontent.com/29176413/57966457-b91f7000-7984-11e9-95d1-e1936c102255.png)
但是实际上返回的事件并没有detail属性
![image](https://user-images.githubusercontent.com/29176413/57966468-d5bba800-7984-11e9-89ac-f0e5359ee2d6.png)

**Comment by ZakaryCode** [comment]
fix in 40c47a0db2bb7f953a3880c54c40f6ce8ae5b3c5
