### ISSUE TITLE
[Feature Request]RN环境下的storage同步存取

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3094]
**问题描述**
有点尴尬，我们有个项目基本都是直接同步到storage的。。迁移到RN很麻烦

![image](https://user-images.githubusercontent.com/13899502/57978510-b171d100-7a41-11e9-8854-5bc984d59f2b.png)

**期望行为**
跟小程序提供一样的API

**系统信息**
👽 Taro v1.3.0-beta.3

  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by YuanQuan** [comment]
我也是 希望可以尽快支持

**Comment by Pines-Cheng** [comment]
这个 RN 平台支持不了哦，建议使用 await/async 。
