### ISSUE TITLE
在Ubuntu上，Taro.request()请求json数据发送后，没有执行success()回调。

### ISSUE THREAD

**Issue by numeny** [NervJS/taro#3095]
**问题描述**
在Ubuntu上，Taro.request()请求json数据发送后，没有执行success()回调。

**复现步骤**
1. 用taro init myApp新建一个项目。
2. 建立一个Button，并且关联click_button
3. 在click_button函数里，调用Toast.request()
4. 点击Button，弹出Toast，显示fail.
5. 用浏览器访问http://localhost/t.json, 显示
{ name: "a", OK : "true" }
```js
// ```js
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  click_button (e) {
    Taro.request({
      url: 'http://localhost/t.json',
      dataType: 'json',
      success: (res) => {
        Taro.showToast({title: 'success'})
      },
      fail: (error) => {
        Taro.showToast({title: 'fail'})
      },
      complete: () => {
        // Taro.showToast({title: "complete"})
      },
    })
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <Button size='mini' type='warn' onClick={this.click_button.bind(this)}>按钮</Button>
      </View>
    )
  }
}
// ```

```
**期望行为**
期望能够Toast.request()能够成功，回调success() 函数，并且获得数据，弹出Toast，显示"success"

**报错信息**
1. 第一种场景(即复现步骤里描述场景和代码)：这种场景下有chrome的network调试窗口上有json数据返回
Failed to load http://localhost/t.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:10086' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):1
Uncaught (in promise) TypeError: Failed to fetch
![case1_1](https://user-images.githubusercontent.com/4244064/57982617-3f69ae00-7a7a-11e9-8736-d3c1cc125650.JPG)
![case1_2](https://user-images.githubusercontent.com/4244064/57982618-409adb00-7a7a-11e9-81eb-45d9764c0c5a.JPG)

2. 根据上一种场景错误提示，当增加Taro.request()参数mode: 'no-cors'，时报错如下：
index.js?3a5f:83 Uncaught (in promise) SyntaxError: Unexpected end of input
    at eval (index.js?3a5f:83)
并且，依然弹出错误Toast。这种场景下有chrome的network调试窗口上有json数据返回
![case2_1](https://user-images.githubusercontent.com/4244064/57982619-42649e80-7a7a-11e9-9a32-810b87472332.JPG)
![case2_2](https://user-images.githubusercontent.com/4244064/57982620-442e6200-7a7a-11e9-815a-c5c9e8250f8b.JPG)
![case2_3](https://user-images.githubusercontent.com/4244064/57982621-44c6f880-7a7a-11e9-8977-fdf7927c8e32.JPG)
![case2_4](https://user-images.githubusercontent.com/4244064/57982622-45f82580-7a7a-11e9-97ff-de6d94418ab7.JPG)

3. 后来我又在场景二基础上，修改dataType: 'html'，这次弹出Toast,显示success（回调了success()函数，但是返回的data却是NULL。console上没有任何错误信息提示。
![case3_1](https://user-images.githubusercontent.com/4244064/57982624-498bac80-7a7a-11e9-81c6-8c803a459783.JPG)

**系统信息**
Taro v1.3.0-beta.3

  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
报错平台：h5

**补充信息**
场景二应该是OK的场景，但是不知道为什么显示SyntaxError

**Comment by ZakaryCode** [comment]
这只是个跨域问题，和 Taro 无关，可以参考 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS) 的相关文档
