### ISSUE TITLE
setState设置二维数组与原微信小程序内设置结果不一致

### ISSUE THREAD

**Issue by GYDSB** [NervJS/taro#3098]
let pages =[]
let value = ['inner']
预期设置后 pages[['inner']]
实际在setState后变为pages[0]:[`inner`]
而在原生微信小程序下setData 是与预期一致 的，设置方法如下
setData({
[`pages[0]`]:value
})

**Comment by Chen-jj** [comment]
@GYDSB 提供一下完整可复现代码

**Comment by GYDSB** [comment]
this.setData({
[pages[0]]:value
})
在原生小程序下结果为pages:[[value]]
this.setState({
  [pages[0]]:value
})
设置后在调试器显示为pages[0]:value,pages:[]而非pages:[[value]]

**Comment by GYDSB** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@GYDSB 你这样写，setState 表现正常吧，再者原生小程序你确定是 pages:[[value]] ？？

**Comment by GYDSB** [comment]
taro上按上方式控制台输出
pages: []
pages[0]: ["test"]且调试器AppData显示pages:[]   
原生setData 输出
pages: [["test"]]且调试器AppData显示pages:[["test"]] @Chen-jj

**Comment by GYDSB** [comment]
-。-应该是直接吧pages[0]当成key了，导致表现有点不一致

**Comment by Chen-jj** [comment]
@GYDSB 当成 key ，是正确的。

**Comment by GYDSB** [comment]
@Chen-jj -。-所以不一致了～

**Comment by Chen-jj** [comment]
@GYDSB JS 里面这样写不正确吗？

**Comment by GYDSB** [comment]
正确，但是跟期望的表现不一致 @Chen-jj 期望的是更新pages某项值，不是新增一个’pages[0]‘属性的值

**Comment by Chen-jj** [comment]
@GYDSB 我的意思是你写法有误。

**Comment by GYDSB** [comment]
this.setState({
[`pages[0]`]:value
})这样没问题吧 @Chen-jj

**Comment by Chen-jj** [comment]
@GYDSB 你这种写法，是指用 pages[0] 作为 key，而不是修改 pages 的第一项。。。。你先去 react playground 了解一下 ES6 的属性名表达式和 setState 用法吧。
