### ISSUE TITLE
[RN]css中的flex如果传值三个，会报错

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3100]
**问题描述**
![image](https://user-images.githubusercontent.com/13899502/57999355-a84b3780-7b07-11e9-9f7b-466e81fb4e78.png)

截图这里转译成：

```
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: 100%;
```

就可以了应该

**期望行为**
参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex 拆分成N项

**系统信息**
```
👽 Taro v1.3.0-beta.3


  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by shenghanqin** [comment]
请根据Taro的[各端开发说明](http://taro-docs.jd.com/taro/docs/before-dev-remind.html#flexbox-%E5%BC%B9%E6%80%A7%E7%9B%92-9)来跟一下问题。
我是感觉是需要分开写的。

**Comment by tourze** [comment]
> 请根据Taro的[各端开发说明](http://taro-docs.jd.com/taro/docs/before-dev-remind.html#flexbox-%E5%BC%B9%E6%80%A7%E7%9B%92-9)来跟一下问题。
> 我是感觉是需要分开写的。

有些代码是从h5其他地方迁移过来的。用的css不一定符合RN要求。如果taro能在转译时做下判断，那么开发者可以更加自然。

**Comment by Garfield550** [comment]
这样编译器会变得更复杂了
