### ISSUE TITLE
1.3.0-beta.3 weapp 端无法传递 props

### ISSUE THREAD

**Issue by kid1412621** [NervJS/taro#3103]
**问题描述**
微信小程序子组件接收不到 props (defaultProps 已设置，老版本不设置也没事), h5 没问题
我回退回去就又好了, 所以确定写的没问题

**复现步骤**
[复现问题的步骤]
1. 安装 taro 1.3.0-beta.3 全家桶;
2. 创建父, 子组件, 父组件传值给子组件, 子组件通过 props 调用.

**期望行为**
父组件能通过 props 传值给子组件

**报错信息**
无报错信息

**系统信息**
 Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by yuche** [comment]
带上复现

**Comment by chenjing1552** [comment]
同样遇到这个问题

**Comment by kid1412621** [comment]
> 带上复现

稍等, 我先回滚回了 1.2 版本, 先把活干完, 伤不起 beta 花了我一天时间了

**Comment by luckyadam** [comment]
cli 和项目依赖有没有一起升级到 beta

**Comment by kid1412621** [comment]
> cli 和项目依赖有没有一起升级到 beta

一起升了的, `taro info` 显示 taro cli 的版本是 beta, `package-lock.json` 显示的也是 beta

**Comment by luckyadam** [comment]
最好能给个例子

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/15b33d1d0e9dece52edd61854689c9aee5b5d485

**Comment by lingxiao-Zhu** [comment]
多久发布这个修复 @yuche
