### ISSUE TITLE
Taro.startPullDownRefresh(params).then(...)h5下mac无法调用下拉刷新

### ISSUE THREAD

**Issue by blackRe** [NervJS/taro#3105]
Taro.startPullDownRefresh(params).then(...)在h5中无法执行，在小程序中调用是正常的，同事还有一个问题是Taro.pageScrollTo(params).then(...)居然也不支持h5所以导致就算使用scrollView来处理也无法实现下拉加载，希望修复这两个问题

**Comment by Littly** [comment]
taro版本多少？

**Comment by xoptimal** [comment]
H5的下拉实现, 能够有一个示例吗 ~

**Comment by BinZhiZhu** [comment]
同问 希望h5下拉刷新 有个简单的demo

**Comment by andyhuai** [comment]
H5的下拉刷新没有demo?提供的API都没有效果
