### ISSUE TITLE
多个页面同时存在Taro.chooseImage选择重复的图片没有回调。

### ISSUE THREAD

**Issue by yanguoyu** [NervJS/taro#3108]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
在h5中两个不同的页面都调用Taro.chooseImage，如果第二个页面选择相同的图片不会回调。
**复现步骤**
[复现问题的步骤]
1. page1调用Taro.chooseImage选择一张图片
2. page2调用Taro.chooseImage选择page1相同的图片
3. 没有回调

[或者可以直接贴源代码，能贴文字就不要截图]

```js


// 这里可以贴代码

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
两个不同的页面之间应该互相不影响。

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
![image](https://user-images.githubusercontent.com/12881040/58059593-3e32a100-7ba0-11e9-9693-c9c5f190d4a4.png)

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
我认为原因是在多个页面中packages/taro-h5/src/api/image/chooseImage.js这个文件里面的taroChooseImageId这个元素是同一个，导致切换页面选择了同一张图片不会触发https://github.com/NervJS/taro/blob/32e6f96be2957f0c6300dc7e2044d31c080e795b/packages/taro-h5/src/api/image/chooseImage.js#L50这个onChange

**Comment by yanguoyu** [comment]
不同页面应该使用不同的元素来避免这个问题吗？还是我要全局存储下这个文件？

**Comment by yanguoyu** [comment]
是不是可以在chooseImage中增加一个id参数？

**Comment by guxingke201** [comment]
解决了么？发现类似问题，同一个文件无法上传两次

**Comment by yanguoyu** [comment]
自己传元素的id进去应该可以，但是之前的元素不会被销毁。
