### ISSUE TITLE
页面初始化先执行render函数后执行componentWillMount函数

### ISSUE THREAD

**Issue by 1035901787** [NervJS/taro#311]
**问题描述**
页面初始化先执行render函数后执行componentWillMount函数

**复现步骤**

**期望行为**

**报错信息**

**系统信息**

 - 操作系统: [mac]
 - Taro 版本 [e.g. v.0.0.68]
 - Node.js 版本 [e.g. v9.4.0]

**补充信息**

**Comment by solenchey** [comment]
Readme-edits

**Comment by luckyadam** [comment]
恩，这是组件化导致的，当属正常，因为需要先搜集一次 render 里定义的变量，放到 state 里去，所以需要先执行一次 render 方法
