### ISSUE TITLE
Checkbox 在h5下报运行异常

### ISSUE THREAD

**Issue by guxingke201** [NervJS/taro#3112]
**问题描述**
任意页面引入如下代码，h5下报js异常

**复现步骤**

1. 任意页面引入如下代码
1. npm run dev:h5
1. 访问引入此代码的页面
1. 报异常，和https://github.com/NervJS/taro/issues/738 类似

```js
import Taro from '@tarojs/taro'
import { View, Checkbox, Text, CheckboxGroup, Label } from '@tarojs/components'

export default class Index extends Taro.Component {
  constructor () {
    super(...arguments)
    this.state = {
      isAgree: true
    }
  }

  handleChangeFour (value) {
    console.log('handleChangeFour:', value)
    this.setState({
      isAgree: !this.state.isAgree
    })
  }

  render () {
    return (
      <View className='login-agree-box'>
        <CheckboxGroup onChange={this.handleChangeFour.bind(this)}>
          <Label>
            <Checkbox checked={this.state.isAgree} color='#ff2852' value='1'>
              <Text className='link-line'>
                我同意《软件产品代理合作协议》
              </Text>
            </Checkbox>
          </Label>
        </CheckboxGroup>
      </View>
    )
  }
}

```

**期望行为**

正常运行，不报异常。

微信小程序也可以正常显示并交互

taro-ui出一个类似Checkbox.AgreeItem的组件(https://mobile.ant.design/components/checkbox-cn/#Checkbox.AgreeItem)最好了

**报错信息**

![image](https://user-images.githubusercontent.com/8326941/58065020-da67a280-7bb6-11e9-8f38-f1c09569f903.png)

**系统信息**

- 操作系统: Windows 10
- Taro 版本 v1.2.26
- Node.js 版本 v9.8.0
- nervjs 版本 v1.3.13
- 报错平台 h5

**补充信息**
如果改成下面的写法，h5不报异常，微信小程序却看不到文字了
```jsx
<Text className='link-line'><span>我同意《软件产品代理合作协议》</span></Text>
```
代码示例写法参考了https://github.com/NervJS/taro/issues/1715

**Comment by jinjinjin0731** [comment]
nervjs 的版本 换成 1.4.0-beta.5 以上，hooks 有问题

**Comment by guxingke201** [comment]
升级后运行`npm run build:h5`用到微信小程序的包`transformer-wx`？1.2.x不会出现这种情况
![image](https://user-images.githubusercontent.com/8326941/58410026-e74b3100-80a3-11e9-9386-8f9bab5ea343.png)
