### ISSUE TITLE
通过props渲染时，没有渲染相应的值

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro#3117]
![image](https://user-images.githubusercontent.com/15973148/58079386-76a79e80-7be3-11e9-9c70-64c65bed4b70.png)
![image](https://user-images.githubusercontent.com/15973148/58079390-79a28f00-7be3-11e9-8d12-21dd344749f3.png)
编译后的文件不对。
版本:
Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-less: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-sass: ^1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-weapp: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      nervjs: ^1.3.9 => 1.3.13 
    npmGlobalPackages:
      typescript: 1.8.10

**Comment by luckyadam** [comment]
提供下源码文字版本

**Comment by JasonJie** [comment]
@luckyadam 
`"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _get = function get(object, property, receiver) { if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { return get(parent, property, receiver); } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } };

var _class, _temp2;

var _index = require("../../npm/@tarojs/taro-weapp/index.js");

var _index2 = _interopRequireDefault(_index);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var nextIcon = "/img/icon/next.png";

var MItem = (_temp2 = _class = function (_Taro$Component) {
  _inherits(MItem, _Taro$Component);

  function MItem() {
    var _ref;

    var _temp, _this, _ret;

    _classCallCheck(this, MItem);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = MItem.__proto__ || Object.getPrototypeOf(MItem)).call.apply(_ref, [this].concat(args))), _this), _this.$usedState = ["$compid__15", "props", "nextIcon", "event", "__fn_onInput"], _this.customComponents = ["AtSwitch"], _temp), _possibleConstructorReturn(_this, _ret);
  }

  _createClass(MItem, [{
    key: "_constructor",
    value: function _constructor(props) {
      _get(MItem.prototype.__proto__ || Object.getPrototypeOf(MItem.prototype), "_constructor", this).call(this, props);

      this.$$refs = [];
    }
  }, {
    key: "_createData",
    value: function _createData() {
      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __isRunloopRef = arguments[2];
      var __prefix = this.$prefix;
      ;
      var props = this.__props;

      var _renderType = void 0;
      if (props.type == "input") {}
      if (props.type == "arrow") {}
      if (props.type == "switch") {}
      if (props.type == "checkbox") {}
      var $compid__15 = (0, _index.genCompid)(__prefix + "$compid__15");
      _index.propsManager.set({
        "onChange": this.__props.event
      }, $compid__15);
      Object.assign(this.__state, {
        $compid__15: $compid__15,
        props: props,
        nextIcon: nextIcon
      });
      return this.__state;
    }
  }, {
    key: "funPrivateODqQC",
    value: function funPrivateODqQC() {
      return this.props.event.apply(undefined, Array.prototype.slice.call(arguments, 1));
    }
  }]);

  return MItem;
}(_index2.default.Component), _class.$$events = ["funPrivateODqQC"], _class.$$componentPath = "component/MItem/index", _temp2);
exports.default = MItem;

Component(require('../../npm/@tarojs/taro-weapp/index.js').default.createComponent(MItem));`
