### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'isProduction' of undefined

### ISSUE THREAD

**Issue by zhangfu-git** [NervJS/taro#3118]
**问题描述**
用taro初始化一个插件目录，运行taro build --plugin weapp --watch，报如下错误
![image](https://user-images.githubusercontent.com/19772048/58082958-9bebdb00-7bea-11e9-8c8a-82bde2745df7.png)

**系统信息**
👽 Taro v1.3.0-beta.3

  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-less: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-weapp: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      nervjs: ^1.3.9 => 1.3.13 
    npmGlobalPackages:
      typescript: 3.4.5

**补充信息**
taro升级为最新版本 v1.3.0-beta.3

**Comment by ruansongsong** [comment]
我也遇到了这个问题，请问解决了吗
