### ISSUE TITLE
0.68-0.69 onClick无法传递参数

### ISSUE THREAD

**Issue by Sdoy** [NervJS/taro#312]
**问题描述**
onClick没法传递参数

**复现步骤**

```
<View style='width:100%;height:20px' onClick={this._dealRecommendClick.bind(this,'test')} />
```
```
_dealRecommendClick=(recommend,e)=>{
    console.log(recommend,e)
  };
```

**期望行为**
输出 test和 event对象

**报错信息**

![image](https://user-images.githubusercontent.com/10302939/42671612-683f5644-8693-11e8-8ffb-b0c2e429af38.png)

**系统信息**

 - 操作系统: Mac 10.13.6 (17G65)
 - Taro 版本 0.68和0.69
 - Node.js 版本 v8.4.0

**Comment by Sdoy** [comment]
emmm,方法名不用 _开头,就正常了

**Comment by solenchey** [comment]
Readme-edits

**Comment by ogundiperukayah** [comment]
Good

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/63cb96a1ed5282a3fcc2b474e02e51ba03422c0a
提交了一个新的 ESLint 规则：函数命名规范(`taro/function-naming`)，宥于 wxml 的限制，函数名现在有三项限制：
* 方法名不能含有数字
* 方法名不能以下划线开头或结尾
* 方法名的长度不能大于20
