### ISSUE TITLE
taroize wxml include 代码丢失

### ISSUE THREAD

**Issue by icai** [NervJS/taro#3120]
**问题描述**
taroize  wxml include 代码丢失

**复现步骤**
[复现问题的步骤]

项目代码：

https://github.com/icai/EWEIWX

**期望行为**

include 代码引入

**报错信息**

![image](https://user-images.githubusercontent.com/1061012/58087467-2e907800-7bf3-11e9-8d12-c57873309a27.png)
![image](https://user-images.githubusercontent.com/1061012/58087476-33edc280-7bf3-11e9-99ca-81dfcf3bdab5.png)

**系统信息**
  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.1.6

 - 操作系统: OSX
 - Taro 版本  Taro v1.3.0-beta.3
 - Node.js 版本 v11.10.0

**Comment by yuche** [comment]
写相对路径应该可以
