### ISSUE TITLE
关于更新项目中 Taro 相关的依赖

### ISSUE THREAD

**Issue by hejinguo** [NervJS/taro#3121]
执行 `taro update project` 后，
发现只更新了 `package.json`   并没有更新 `package-lock.json`

**Comment by Garfield550** [comment]
`package-lock.json` 是 npm 自己管理的并且会自动更新，如果没有，手动运行一次 `npm install`

> Using a locked package is no different than using any package without a package lock: any commands that update node_modules and/or package.json’s dependencies will **automatically** sync the existing lockfile. This includes npm install, npm rm, npm update, etc. To prevent this update from happening, you can use the --no-save option to prevent saving altogether, or --no-shrinkwrap to allow package.json to be updated while leaving package-lock.json or npm-shrinkwrap.json intact.

Ref: https://docs.npmjs.com/files/package-locks#using-locked-packages
