### ISSUE TITLE
1.3版本上用tsx建立的函数组件无法被识别，报错Taro is not defined

### ISSUE THREAD

**Issue by coolguy001tv** [NervJS/taro#3122]
**问题描述**
使用TS建立函数组件（后缀名为tsx）时，在1.3 beta1 beta3 (beta2版本未尝试)上均无法正常工作，报Taro is not defined。 但是如果将该函数组件后缀名改为JS则工作正常。

**复现步骤**
[复现问题的步骤]
有代码
```js
import Taro from '@tarojs/taro'
import { View, Text } from '@tarojs/components'

function Header(){
  return (
    <View>
      <Text>Header</Text>
    </View>
  )
}
export default Header
```
1. 命名为X.tsx，在任意正常页面引入（我测试的环境下是/pages/index/index.tsx）
2. 执行`yarn dev:h5`
3. 开发工具报错，报错信息见后文
4. 将第一步的命名改为X.js，执行第1-2步，正常

**期望行为**
支持ts

**报错信息**

```
ReferenceError: Taro is not defined
    at eval (Header.js?b828:4)
    at Module../.temp/components/demo/Header.js (index_index.js:11)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (index.js:10)
    at Module../.temp/pages/index/index.js (index_index.js:47)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
```

**系统信息**
  Taro CLI 1.3.0-beta.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\CoolGuy\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[根据你的调查研究，出现这个问题的原因可能在哪里？]
从编译后的文件来看，两者的主要差别在于ts下编译的结果少了一行taro/h5的引用，以下是编译后的文件：
```js
import Nerv from "nervjs";
import { View, Text } from '@tarojs/components';

class Header extends Taro.Component {
  render() {
    return <View>
      <Text>Header</Text>
    </View>;
  }

}

export default Header;
```
能够看到的确Taro是没有定义的；
而JS后缀的名字，最终编译后的结果是:
```js
import Nerv from "nervjs";
import Taro from "@tarojs/taro-h5";
import { View, Text } from '@tarojs/components';

class Header extends Taro.Component {
  render() {
    return <View>
      <Text>Header</Text>
    </View>;
  }

}

export default Header;
```
这样就不会出错了

**Comment by grepug** [comment]
你在函数式组件中任意调一个hook就可以了。他们说下个版本修复。

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/769bb080450b6e7873673b31acc09ab9bbb9dca6
1.3.0-beta.6版本已修复这个问题
