### ISSUE TITLE
[RN]Input组件没有透传参数到RN的TextInput

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3125]
**问题描述**
看 `node_modules/@tarojs/components-rn/dist/components/Input/index.js`，传递给TextInput的参数是有挑选的，我们直接传入一些参数，如 `placeholderTextColor` 最终会无效的。。。希望能将文档提及的参数 https://facebook.github.io/react-native/docs/textinput.html 透传给最终组件。或者官方自己封装一下也行。。。

![image](https://user-images.githubusercontent.com/13899502/58138439-b5336c80-7c68-11e9-874e-19fed02e616a.png)

![image](https://user-images.githubusercontent.com/13899502/58138450-c0869800-7c68-11e9-9be9-cc4e80f8df10.png)

**期望行为**
参数能透传给平台最终负责渲染的组件

**系统信息**
```
👽 Taro v1.3.0-beta.3


  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by Manjiz** [comment]
TextInput 的参数你都可以传了
