### ISSUE TITLE
Taro在componentDidCatchError 监听不到错误

### ISSUE THREAD

**Issue by leoswing** [NervJS/taro#3126]
**问题描述**
在Taro创建的project里面，通过在 componentDidCatchError 钩子，监听组件错误。尝试在 componentWillMount 里面写一些 引用异常类似的错误， 但是在 componentDidCatchError 钩子里面没有打印出异常信息。

**复现步骤**
[复现问题的步骤]
1. 在钩子 componentWillMount 引用不存在的变量，产生引用异常。
2. 在钩子 componentDidCatchError ，监听异常，并且进行console log
3. 异常产生了，控制台有报错，但是 componentDidCatchError 钩子并没有打印出相关console log
4. 最终表明 componentDidCatchError 没有监听到组件的异常

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// ```js
class LogException extends Component {
      ....
      componentWillMount () {
          console.log(this.ref.undefined);
      }
    componentDidCatchError (err) {
        console.log(`error occur: ${err}`);
    }
}
// ```

```

**期望行为**
期望在 componentDidCatchError 钩子里面捕获到组件异常

**报错信息**

只有引用异常的报错，在钩子 componentDidCatchError 里面没有捕获到异常。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [1.2.26]
 - Node.js 版本 [10.15.3]
 - 报错平台 [h5]

**Comment by Chen-jj** [comment]
@leoswing componentDidCatchError 等于小程序的 onError 生命周期，是**入口文件 APP** 的生命周期方法，不是组件或页面自身的生命周期方法。

![image](https://user-images.githubusercontent.com/11807297/58392885-ad136c80-806e-11e9-88dc-6eda662b3162.png)

![image](https://user-images.githubusercontent.com/11807297/58392888-b1d82080-806e-11e9-902b-116000963bdf.png)

![image](https://user-images.githubusercontent.com/11807297/58392898-b8ff2e80-806e-11e9-89cc-5e37926ce093.png)
