### ISSUE TITLE
自己发了一个npm包，安装成功且引用后，并没有拷贝到dist/npm中，一直提示找不到

### ISSUE THREAD

**Issue by MuJinYan** [NervJS/taro#3127]
问题描述  自己使用原生小程序方法封装了一个npm包，安装成功后，在app.js也进行了引用，但并未自动拷贝到dist/npm中，编译时一直提示找不到npm包

复现步骤 
在node_modules中已看到成功安装，且将此npm包直接在原生微信小程序可成功引用
但在app.js中进行引用
import { Location } from 'fantuan-platform-miniprogram'
编译时并未自动放入dist/npm包，造成一直提示缺少npm包

报错信息
缺少npm包fantuan-platform-miniprogram，开始安装...
warning " > @tarojs/components@1.2.4" has unmet peer dependency "classnames@^2.2.5".                                                                                                    
warning " > @tarojs/components@1.2.4" has unmet peer dependency "omit.js@^1.0.0".                                                                                                       
warning " > @tarojs/components@1.2.4" has unmet peer dependency "weui@^1.1.2".                                                                                                          
warning " > dva-core@1.4.0" has incorrect peer dependency "redux@3.x".                                                                                                                  
warning " > dva-loading@2.0.6" has unmet peer dependency "dva@^2.0.4".                                                                                                                  
缺少npm包fantuan-platform-miniprogram，开始安装...

系统信息
➜  myApp git:(master) ✗ taro info
👽 Taro v1.2.4

  Taro CLI 1.2.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.4 => 1.2.4 
      @tarojs/components: 1.2.4 => 1.2.4 
      @tarojs/plugin-babel: ^1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-csso: 1.2.4 => 1.2.4 
      @tarojs/plugin-sass: 1.2.4 => 1.2.4 
      @tarojs/plugin-uglifyjs: ^1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/redux: 1.2.4 => 1.2.4 
      @tarojs/redux-h5: 1.2.4 => 1.2.4 
      @tarojs/router: 1.2.4 => 1.2.4 
      @tarojs/taro: 1.2.4 => 1.2.4 
      @tarojs/taro-alipay: 1.2.4 => 1.2.4 
      @tarojs/taro-h5: 1.2.4 => 1.2.4 
      @tarojs/taro-swan: 1.2.4 => 1.2.4 
      @tarojs/taro-weapp: 1.2.4 => 1.2.4 
      @tarojs/webpack-runner: 1.2.4 => 1.2.4 
      eslint-config-taro: 1.2.4 => 1.2.4 
      eslint-plugin-taro: 1.2.4 => 1.2.4 
    npmGlobalPackages:
      typescript: 3.4.3

操作系统: mac os 10.14.5
Taro 版本 1.2.4
Node.js 版本 8.12.0
报错平台 weapp

**Comment by Garfield550** [comment]
你好，1.2.4 是很老的版本了，建议先更新一下 Taro 到 1.2.26，敢于尝试的话可以试试 1.3.0-beta.3

如果你是想在 usingComponents 里使用来自 npm 的原生组件的话，Taro 暂时还不支持，可以选择下载到本地目录使用相对路径的方式

```ts
import { Location } from 'fantuan-platform-miniprogram';

class Index extends Taro.Component {
  public config: Taro.Config {
	usingComponents: {
	  // 'Location': 'fantuan-platform-miniprogram' // 暂不支持 npm 方式
	  'Location': 'path/to/the/custom/component',
	}
  }
}

export default Index as ComponentType;
```

如果是其他方式建议表达清楚一些，然后等待官方解答吧。

**Comment by shenghanqin** [comment]
@MuJinYan 可以尝试最新版本。
