### ISSUE TITLE
小程序打包不会压缩

### ISSUE THREAD

**Issue by LeeeoZhang** [NervJS/taro#3131]
**问题描述**
小程序build不会压缩

**复现步骤**

```js
config/index.js

plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread'
      ]
    },
    uglify: {
      enable: true,
    },
    csso: {
      enable: true,
    },
  },

```

**期望行为**
build会对js和css代码进行压缩

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.4.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-sass: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-weapp: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      nervjs: ^1.3.9 => 1.3.9

**Comment by LeeeoZhang** [comment]
#2947

**Comment by Garfield550** [comment]
刚想提个 issue 来着

**Comment by luckyadam** [comment]
已经修复了，可以升级到 1.3.0-beta.4 尝试~

**Comment by LeeeoZhang** [comment]
> 已经修复了，可以升级到 1.3.0-beta.4 尝试~

更新cli到1.3.0-beta.4可以解决，thx
