### ISSUE TITLE
如何添加 reflect-metadata 支持？

### ISSUE THREAD

**Issue by hannq** [NervJS/taro#3132]
观察发现编译 `*.ts` 并没有采用 typescript 自带的 tsc 编译，似乎是使用的 babel 编译的
babel 要实现 `reflect-matadata` 需要使用 `babel-plugin-transform-typescript-metadata` 这个插件，
这个插件是基于 `@babel/core: ^7`，但是现在 taro 是使用的 `babel-core: 6.26.3`， 完全没法用 

现在发现 taro 本身也有通过typescript编译的： plugin-typescript，
不知道在哪里配置

想知道可以通过什么方式实现

**Comment by Garfield550** [comment]
这部分我个人觉得暂时是没有办法配置的，编译工作大部分都是由 Taro CLI 自己管理的，暂不开放给开发者配置。仔细读文档也会发现只有 H5 会允许自定义部分 Webpack 配置，而小程序则几乎没有。

Babel 6 的问题需要等官方更新。

**Comment by dyk98** [comment]
同问，想使用装饰器但是引入reflect-metadata无效，还是会Reflect.hasOwnMetadata不存在

**Comment by s97712** [comment]
加了 
```
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
```
`Reflect.getMetadata("design:type", cls);` 还是不起作用
