### ISSUE TITLE
taro版本：1.3.0-beta.3，组件内使用mobx报错~

### ISSUE THREAD

**Issue by uloveits** [NervJS/taro#3143]
**问题描述**
[问题描述：升级1.3.0-beat.3之后，使用mobx报以下错误]
![微信图片_20190523095936](https://user-images.githubusercontent.com/26559166/58220454-863cf980-7d41-11e9-95ed-40e4b9ceb69e.png)

**复现步骤**
[复现问题的步骤]
1.父页面引用组件。
2.组件里使用mobx。
`import { inject, observer } from "@tarojs/mobx"
import './index.scss';

@inject('auth')
@observer
class KtUserCard extends Taro.Component {}`

期望行为：组件也可以使用mobx。

**Comment by langlangbody** [comment]
版本回退到1.3.0-beta.0 mobx 就好了  我也是 升级到1.3.0-beta.3 报很多错

**Comment by luckyadam** [comment]
升级到 1.3.0-beta.4 试试呢

**Comment by nanjingboy** [comment]
@uloveits 升级到 1.3.0-beta.5 试试呢？[taro-mobx-sample](https://github.com/nanjingboy/taro-mobx-sample) 中无法复现呢
