### ISSUE TITLE
h5端 input输入框 number类型先输入数字然后输入非数字字符input框会被清空

### ISSUE THREAD

**Issue by lvzhimingjobs** [NervJS/taro#3144]

**Comment by lvzhimingjobs** [comment]
![image](https://user-images.githubusercontent.com/37326179/58221905-d074a980-7d46-11e9-9b5a-45a0fb6d8f82.png)

**Comment by jinjinjin0731** [comment]
已经在微信中回复了~ 你这个问题属于写法问题。关闭了
