### ISSUE TITLE
希望样式文件在编译时如果有报错, 不会直接退出编译

### ISSUE THREAD

**Issue by Lionad-Morotar** [NervJS/taro#3148]
**问题描述**

如果less文件有语法错误:
![image](https://user-images.githubusercontent.com/26913795/58224206-601e5600-7d4f-11e9-9621-3697934548fa.png)

一旦`ctrl+s`保存文件, 命令行会直接报错退出停止编译:
![image](https://user-images.githubusercontent.com/26913795/58224190-45e47800-7d4f-11e9-84dd-38575ec2289e.png)

**taro info**

```
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Users\18062\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
可以升级到 1.3.0-beta.4 尝试

**Comment by Lionad-Morotar** [comment]
> 可以升级到 1.3.0-beta.4 尝试

Thank'U 明天我试一试~
