### ISSUE TITLE
用typescript 编译后的文件代码中，引用的还是x.ts，导致找不到模块

### ISSUE THREAD

**Issue by xshua06** [NervJS/taro#3149]
**问题描述**
用typescript 编译后的文件代码中，引用的还是x.ts，导致找不到模块

**复现步骤**
1.两个ts文件同一个目录
a.ts 
b.ts
```js
const a = require('./b');
```
2. yarn dev:weapp编译
```js
var a = require('./b.ts')
```
导致编译后的dist/weapp/中没有ts文件，找不到模块

**期望行为**
修复他

**报错信息**
编译问题，导致找不到模块

**系统信息**
Taro v1.3.0-beta.3
  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm

**Comment by Garfield550** [comment]
`import a from './b'` 这种写法呢

**Comment by luckyadam** [comment]
已经修复，可以升级到 1.3.0-beta.4 尝试
