### ISSUE TITLE
Please use English

### ISSUE THREAD

**Issue by dandv** [NervJS/taro#315]
https://blog.codinghorror.com/the-ugly-american-programmer/

**Comment by isting** [comment]
laowai ye xie wechat mini apps?

**Comment by zacksleo** [comment]
The project is a framework for building Wechat mini program which is mainly for the Chinese region.   There are no foreign developers as far as I know.

**Comment by ogundiperukayah** [comment]
Very good

**Comment by ianva** [comment]
I think he just want to make the github rank clear, but the project only serve to Chinese region. 
The framework is so popular that always front of the rank recently, but the foreigner don't know what is it. if description of project has a english version, it will be much better.

**Comment by zacksleo** [comment]
Well, we can have a short introduction in English.

**Comment by dandv** [comment]
> There are no foreign developers as far as I know.

If everything stays Chinese, there won't be any new foreign developers, guaranteed.

**Comment by zacksleo** [comment]
@dandv You're right. Unfortunately the project is base on Wechat mini program which has no document in English. It's very hard for people who want to develop a Wechat mini program in English. All depends on WeChat. Frustrated.

**Comment by zacksleo** [comment]
> Awesome React-like framework supporting JSX that can compile your code into Wechat Mini Program, Html5 and React Native etc.

@luckyadam  What about this introduction ?

**Comment by kenberkeley** [comment]
@dandv Wechat Mini Program is a nightmare and I sincerely hope that it will never spread abroad

**Comment by AdvancedCat** [comment]
Maybe you want to know "What is Wechat mini program?".
Wechat mini program is a tiny AppleStore which embed in Wechat. Perhaps you could call it "WechatStore".Haha!
But Wechat mini program has own grammar.  So the purpose of Taro is using React grammar to generate a wechat mini program. @dandv

**Comment by mokennnnn** [comment]
so cool.May be It's time to learn chinese

**Comment by kenberkeley** [comment]
@mokennnnn learning Chinese is great, but learning Wechat mini program sucks

**Comment by harryfei** [comment]
Programming with Chinese characteristics.
