### ISSUE TITLE
ts模式下，currentTarget.dataset 不存在属性 xxx

### ISSUE THREAD

**Issue by gu-xionghong** [NervJS/taro#3151]
**问题描述**
在 ts 模式下，使用 onClick 等事件，设置接收的 event 类型后，取值`event.currentTarget.dataset.xx` 时提示 *类型“{}”上不存在属性“xx”。*

**复现步骤**
直接创建 ts 模板

```js
import { ITouchEvent } from '@tarojs/components/types/common'

// ...
class Template extends Component<IProps, IState> {
  handleClick(e: ITouchEvent) {
  // 此处报错：类型“{}”上不存在属性“id”。
    const { id } = e.currentTarget.dataset
  }

  render() {
    return (
      <View className="template" data-id="1" onClick={this.handleClick}></View>
    )
  }
}
```

**期望行为**
顺利取出 `id` 值，不报错

**报错信息**
*类型“{}”上不存在属性“xx”。*
![报错信息](https://user-images.githubusercontent.com/12096816/58231590-f95a6600-7d69-11e9-8840-b55dc76309bc.png)
![Target 声明代码 ](https://user-images.githubusercontent.com/12096816/58231615-037c6480-7d6a-11e9-9d6a-5c02580415ff.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac 10.14.2
 - Taro 版本 v1.2.26
 - Node.js 版本 v10.14.2
 - 报错平台 *

**补充信息**
无

**Comment by Garfield550** [comment]
TS 类型错误的话，你可以自己修一下，提 Pull Request

**Comment by Garfield550** [comment]
或者如果你能保证它运行时不出问题的话，你可以这样写
```ts
const e: object = {};
// @ts-ignore
const { id } = e.currentTarget.dataset
```

![image](https://user-images.githubusercontent.com/3471836/58236678-f9f8f980-7d75-11e9-840c-147389e09de9.png)
