### ISSUE TITLE
1.3.0-beta.3版本，编译后dist目录下缺少了部分page

### ISSUE THREAD

**Issue by hahaiamzd** [NervJS/taro#3154]
**问题描述**
在1.3.0-beta.3版本下运行 npm run dev:weapp
编译完后在dist目录下发现部分page没有编译进来
降回1.2.26版本后运行同样的命令，编译成功并且dist下的page没有丢失。

**Comment by luckyadam** [comment]
给一个 demo 吧

**Comment by zhangfu-git** [comment]
遇到相同的问题，现在build后在dist下生成了一个weapp文件夹,  我是把project.config.json里的`"miniprogramRoot"`修改为`"./dist/weapp"`解决
