### ISSUE TITLE
CSS filter滤镜与预期不符

### ISSUE THREAD

**Issue by ppxb** [NervJS/taro#3155]
**问题描述**
在使用CSS的filter:drop-shadow()时，开发者工具预览正常，真机预览出现花屏、样式丢失、渲染不全等现象。

**复现步骤**
```js

// ./component/taskcard/index.js

render() {
    const { taskInfo } = this.state
    return (
      <View className="task--card">
        <View className="top">
          <Image src={this.checkStatus(taskInfo.status)} className='status' />
          <View className="title">{taskInfo.statusText}</View>
          <Text className='time'>{taskInfo.time}</Text>
        </View>
        <View className="middle">
          <Text className='type'>{taskInfo.type}</Text>
          <Text className='desc'>备注：</Text>
          <Text className='desc--text'>{taskInfo.desc}</Text>
          <View className='bottom'>
            {
              taskInfo.sendTime ?
                <View className='send'>
                  <Text className='title'>预计送达</Text>
                  <View className='time-wrapper'>
                    <Text className='time'>{taskInfo.sendTime}</Text>
                    <Text className='ago'>分钟后</Text>
                  </View>
                </View> :
                (
                  taskInfo.showAppraise ? <View className='appraise'>评价</View>
                    : <View className='total'>总计</View>
                )
            }
            <View className='right'>
              <Text className='sigal'>¥</Text>
              <Text className='price'>{taskInfo.price}</Text>
            </View>
          </View>
        </View>
        <View className="divider--bottom"></View>
      </View>
    )
  }

```css

//  ./component/taskcard/index.scss

.rank--card {
  display: flex;
  justify-content: space-between;
  align-items: center;
  box-sizing: border-box;
  margin-top: 32px;
  padding: 28px 20px;
  border-radius: 8px;
  background: #fff;
  // box-shadow: 0px 0 40px rgba(0, 0, 0, 0.1);
  filter: drop-shadow(0px 0 12px rgba(0, 0, 0, 0.1));
}

```

**期望行为**
![TIM截图20190523163811](https://user-images.githubusercontent.com/17081240/58238793-7d1c4e80-7d7a-11e9-944f-e73d05813e87.jpg)

**报错信息**
![IMG_0828](https://user-images.githubusercontent.com/17081240/58239150-22cfbd80-7d7b-11e9-836a-a22e23cf41f4.PNG)
![IMG_0830](https://user-images.githubusercontent.com/17081240/58239153-23685400-7d7b-11e9-906d-51b24f8d2f0e.PNG)
![IMG_0829](https://user-images.githubusercontent.com/17081240/58239155-24998100-7d7b-11e9-94d6-c7ab873704ad.PNG)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  Windows 10
 - Taro 版本 1.3.0-beta.3
 - Node.js 版本 11.13.0
 - 报错平台 weapp

**Comment by Garfield550** [comment]
CSS 的问题你可以先检查一下对应的 wxss 文件。

排查方向：
Taro 编译样式表默认会经过一次 autoprefixer 处理，所以可以先排查编译后的文件是否被 autoprefixer 处理错了。

样式问题也有可能涉及到手机设备本身，参考微信文档的[实现差异](https://developers.weixin.qq.com/miniprogram/dev/devtools/details.html)一节，微信小程序在 iOS 上是 JavaScript Core 执行，WKWebView 渲染的，Android 是由腾讯自研 X5 JSCore 执行，Chrome 内核渲染的，开发者工具则是由 nwjs 的 Chrome Webview 渲染的，三者本身差异较多，再由于手机系统版本不同（iOS 10 与 iOS 12 / Android 7 与 Android 9）之类的差异，附带的渲染引擎可能有所不同，有可能会导致渲染问题。如果发现是这类问题，建议到微信开发者官方论坛，向官方反馈问题。

**Comment by Garfield550** [comment]
你好，我在微信官方社区找到了相关问题，其中有一个帖子已经被官方确认为 Bug，正在解决。

https://developers.weixin.qq.com/community/develop/doc/000ee60c53c9804bba78c7e7856800?highLine=CSS%2520Filter

https://developers.weixin.qq.com/community/develop/doc/0006aeddbe0fb0540548ce32656400?highLine=CSS%2520Filter

**Comment by ppxb** [comment]
感谢，制作这种带投影的异性容器在小程序中属实不易。再次感谢。

**Comment by ppxb** [comment]
这个Issue官方那边给回复了。
[地址](https://developers.weixin.qq.com/community/develop/doc/0006e28d720af8eb83983d65056400?jumpto=comment&commentid=0004aae9060e403b8898b18f6520)
用原生小程序代码写没有问题，是否是TARO的问题呢？

**Comment by Garfield550** [comment]
> 这个Issue官方那边给回复了。
> [地址](https://developers.weixin.qq.com/community/develop/doc/0006e28d720af8eb83983d65056400?jumpto=comment&commentid=0004aae9060e403b8898b18f6520)
> 用原生小程序代码写没有问题，是否是TARO的问题呢？

贴一下编译后的 wxss 咯
