### ISSUE TITLE
小程序转换H5，运行命令 npm run dev:h5的时候出错

### ISSUE THREAD

**Issue by xiaoboJoin** [NervJS/taro#3156]
Hi，我通过社区，把– EastWorld/wechat-app-mall ★5000+ – 微信小程序商城，小程序转换成H5，根据步骤：
1，taro convert
2，npm run dev:h5
最后提示：

ℹ️  Listening at http://127.0.0.1:10086/

监听文件修改中...

🙅   Failed to compile.

./.temp/imports/TaroParseaaTmpl.js
Module not found: Can't resolve './TaroParseabTmpl' in '/Users/bob/Documents/github/wechat-app-mall/taroConvert/.temp/imports'

请问，怎么解决？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/taroize.html

**Comment by ifkhkh** [comment]
文件存在却提示 
Module not found: Can't resolve 'utils/util.js' in 'C:\Users\HighSun\Documents\GitHub\testTaro\hs-mini-eshop\taroConvert\.temp'
不知道如何解决了
