### ISSUE TITLE
小程序转H5，浏览器提示找不到Nerv对象

### ISSUE THREAD

**Issue by xiaoboJoin** [NervJS/taro#3158]
小程序转H5，浏览器提示找不到Nerv对象，转换成功了，
Compiled successfully!

但是H5打开的时候报错
![1558605631600](https://user-images.githubusercontent.com/6210610/58244293-e6a15a80-7d84-11e9-9b8d-103cc13f0484.jpg)

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by ybingyu** [comment]
同样的问题。taro 版本 1.3.0-beta.5
![image](https://user-images.githubusercontent.com/10411477/58778384-f03c8500-8604-11e9-9fc3-064f4faa90cd.png)

**Comment by Garfield550** [comment]
升级一下 v1.3.0-beta.6 然后把 `package.json` 的 Nerv 和 Nerv-DevTools 版本改成 `^1.4.0-beta.5` 试试。（只是建议

**Comment by ybingyu** [comment]
似乎不行。
![image](https://user-images.githubusercontent.com/10411477/58792032-f727bf80-8625-11e9-99d9-21fd9082d587.png)
![image](https://user-images.githubusercontent.com/10411477/58792081-0dce1680-8626-11e9-98fb-65e8d3a892c1.png)

**Comment by loosenRogers** [comment]
你好 你这个问题解决了么
你的流程是微信小程序 ->  taro  ->  h5吧
这个流程的流程的话  我也遇到同样的问题[issue#3398](https://github.com/NervJS/taro/issues/3398)
看你这个提的还的还蛮早的，官方一直没解决啊

**Comment by Littly** [comment]
贴一下转换后的 app.js 代码看看?

**Comment by loosenRogers** [comment]
> 贴一下转换后的 app.js 代码看看?

以下是微信小程序官方组件demo pcker的转换成h5的app.js文件内容
头部引入Taro，但是在其中用的Nerv.render()方法，所以报错

```
import Taro from "@tarojs/taro-h5";

import './app.scss';

import { Router, createHistory, mountApis } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});

const _taroHistory = createHistory({
  mode: "hash",
  basename: "/",
  customRoutes: {},
  firstPagePath: "/index/index"
});

mountApis(_taroHistory);
class App extends Taro.Component {
  componentWillMount = () => {};
  config = {
    pages: ["/index/index"],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    },
    sitemapLocation: 'sitemap.json'
  };

  componentWillMount() {
    this.$app.globalData = this.globalData;
  }

  render() {
    return <Router history={_taroHistory} routes={[{
      path: '/index/index',
      componentLoader: () => import( /* webpackChunkName: "index_index" */'./index/index'),
      isIndex: true
    }]} customRoutes={{}} />;
  }

  constructor(props, context) {
    super(props, context);
    Taro._$app = this;
  }

}

export default App;
Nerv.render(<App />, document.getElementById('app'));

```

**Comment by loosenRogers** [comment]
之前1.3.2版本还是有的；发布新版本后，这个问题好像已经没有再复现了
