### ISSUE TITLE
1.3.0-beta.3版本，AtModal组件引入报错

### ISSUE THREAD

**Issue by SeptemberMaples** [NervJS/taro#3159]
**问题描述**
[问题描述：更新到1.3.0-beta.3版本后，AtModal组件引入报错]

**复现步骤**

```js
   VM7377:1 ReferenceError: isRenderAction is not defined
    at AtModal._createData (index.js:134)
    at Object.createComponent (index.js:3027)
    at index.js:174
    at require (WAService.js:1)
    at <anonymous>:221:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1558606639570:2747)
    at HTMLScriptElement.script.onload (appservice?t=1558606639570:2759)
```

**系统信息**

Taro v1.3.0-beta.3
  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-sass: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/redux: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/redux-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/taro-weapp: 1.3.0-beta.3 => 1.3.0-beta.3 
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3 
      nervjs: ^1.3.9 => 1.3.13 
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
已解决，可以升级到 1.3.0-beta.4 尝试

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/1caf4056df0f9c4d5cb8a548c906ef2e20c07c19
