### ISSUE TITLE
自定义icon H5可以正常显示 微信小程序不显示

### ISSUE THREAD

**Issue by 531431988** [NervJS/taro#3161]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
H5版 图标正常显示

![image](https://user-images.githubusercontent.com/8703951/58296477-68859800-7e06-11e9-92bd-4c8891f8d1e5.png)

微信小程序版 图标无法显示
![image](https://user-images.githubusercontent.com/8703951/58296643-14c77e80-7e07-11e9-8f3c-541941104b2c.png)

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
import Taro, { Component } from '@tarojs/taro';
import PropTypes from 'prop-types';
import { View } from '@tarojs/components';

class AIcon extends Component {
  static defaultProps = {
    type: '',
    color: ''
  };
  static propTypes = {
    type: PropTypes.string.isRequired
  };
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {
    const { type, color } = this.props;
    return <View className={`a-icon icon-${type}`} style={{ color }} />;
  }
}
export default AIcon;

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@531431988 微信小程序组件的样式需要配置才受全局影响：[文档](https://nervjs.github.io/taro/docs/component-style.html)

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/58299101-8eb03580-7e10-11e9-8f8b-89ccc6f85043.png)
效果已经有了，但是class为何重复
![image](https://user-images.githubusercontent.com/8703951/58299092-86f09100-7e10-11e9-869e-d989df6903d1.png)

**Comment by tourze** [comment]
class名重复，我以前在1.2.x开发时遇过，可以尝试下升级版本

**Comment by Chen-jj** [comment]
@531431988 编译后的 wxss 是否正确，正确的话就是微信的处理。
