### ISSUE TITLE
yarn 和 cnpm 都无法安装beta4版本，已开启翻墙代理。

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#3162]
![bug](https://user-images.githubusercontent.com/13210798/58296735-7c7dc980-7e07-11e9-8595-479a35c7d1bf.png)

**Comment by Garfield550** [comment]
electron-to-chromium 安装失败了，换回官方源而不是淘宝源试一下？

https://www.npmjs.com/package/electron-to-chromium

![image](https://user-images.githubusercontent.com/3471836/58296824-f9a93e80-7e07-11e9-87aa-4e8cd809950e.png)

**Comment by LeeeoZhang** [comment]
切换到npm源可以正常更新

**Comment by yuche** [comment]
terminal 或 cmd 的代理需要单独设置，具体你可以上网找。
安装类问题应该由开发者自行解决。
