### ISSUE TITLE
在小程序中配合 dva 使用时，reducers 中更改解构得到的数组内容，总会修改源数组

### ISSUE THREAD

**Issue by chantzekin** [NervJS/taro#3165]
**问题描述**

根据「优秀案例和第三方库征集」中推荐方案加入 dva 相关配置后，普通使用 store 没问题，但当在 reducers 的方法中使用诸如

```js
EDIT (state) {
   const list = [...state.list] // 也尝试过 state.list.concat() 和 .slice()
   list[0].name = 'change'
   return { ...state, list }
}
```

均会出现修改 `list[0].name` 时 state.list 也会作出更改，导致在 return 之前 state 已经变更，视图不会触发更新

而且从 redux-logger 中可以看到 pre state 也跟随更改

尝试 taro cli 的 redux 默认模版和 dva cli web 端均没发现该问题（难道是 dva-core 配置方式不对？😂）

另外使用 JSON.parse(JSON.stringify(state.list)) 这种方式没有问题

**复现步骤**

[demo.zip](https://github.com/NervJS/taro/files/3214882/demo.zip)

下载 demo，安装依赖后小程序中运行

点击界面 edit 按钮

**期望行为**

解构数组得到的新数组，更改其对象项属性，不会影响 state 中源数组

**报错信息**

无

**系统信息**

```bash
  Taro CLI 1.3.0-beta.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.9.2
```

 - 操作系统: macOS 10.14.5
 - Taro 版本 1.3.0-beta.4
 - Node.js 版本 v11.10.0
 - 报错平台 weapp

**补充信息**

无

**Comment by chantzekin** [comment]
另外 `const list = state.list.map(i => i)` 也是不可以的 但是 `const list = state.list.map(i => ({ ...i }))` 可以

**Comment by becarchal** [comment]
要在nest store数据里做对象属性修改，不宜做浅拷贝。推荐用优秀的工具库lodash做深拷贝；
`import cloneDeep from 'lodash/cloneDeep'`
` const list = [...state.list]` 改为 `const list = cloneDeep(state.list)`
即可解决你的问题；
修复前：
![image](https://user-images.githubusercontent.com/20692744/58392307-f0b8a700-806b-11e9-956b-473c77e1eeb9.png)
修复后：
![image](https://user-images.githubusercontent.com/20692744/58392354-29f11700-806c-11e9-9899-606c011485d4.png)

希望能帮助到你@chantzekin
