### ISSUE TITLE
1.3.0-beta.4 Cannot read property 'compid' of undefined

### ISSUE THREAD

**Issue by hao-li** [NervJS/taro#3167]
**问题描述**
支付宝小程序 Cannot read property 'compid' of undefined

**复现步骤**
1. git clone git@github.com:hao-li/taro-problem-sample.git
2. yarn
3. yarn build:alipay
4. 使用 Mini Program Studio（支付宝开发者工具）打开 dist/alipay 目录
5. 使用 Mini Program Studio 模拟器查看小程序
6. 点击『点击进入支付宝小程序问题页』按钮
7. 点击页面右上角返回按钮
> 需要先解决前置的 #3135 
> 如果尚未解决，则在项目根目录下执行下面命令以回避 #3135 的问题
> ```
> cp node_modules/entities/maps/* dist/alipay/npm/entities/maps
> ```

**期望行为**
一切正常

**报错信息**
![49081558668176_ pic_hd](https://user-images.githubusercontent.com/11334645/58305853-18b9c780-7e2c-11e9-861b-cdb5325f2909.jpg)
![49091558668193_ pic](https://user-images.githubusercontent.com/11334645/58305863-20796c00-7e2c-11e9-8d0a-9d8624259edf.jpg)

**系统信息**
```
👽 Taro v1.3.0-beta.4


  Taro CLI 1.3.0-beta.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/plugin-babel: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/plugin-csso: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/plugin-sass: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/plugin-uglifyjs: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/router: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/taro: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/taro-alipay: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/taro-h5: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/taro-swan: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/taro-weapp: 1.3.0-beta.4 => 1.3.0-beta.4
      @tarojs/webpack-runner: 1.3.0-beta.4 => 1.3.0-beta.4
      eslint-config-taro: 1.3.0-beta.4 => 1.3.0-beta.4
      eslint-plugin-taro: 1.3.0-beta.4 => 1.3.0-beta.4
      nervjs: ^1.4.0-beta.4 => 1.4.0-beta.4
```

**补充信息**
1.3.0-beta.3 无此现象
微信小程序正常

**Comment by dogrod** [comment]
1.3.0-beta5 出现相同问题，希望尽快解决
