### ISSUE TITLE
图片的处理的问题——求指教

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#3173]
想求教一下，例如把图片都放在一个 images 的一个文件夹下面，然后其他 css 或者 scss 里面引用的时候；
本地开发的时候，直接引用的是本地起的服务器上面的图片；
要 build 的时候，能够把图片上传到服务器上，然后在 css 里面引用的是 服务器上的文件路径。
求指点

**Comment by ZakaryCode** [comment]
加个钩子传图，路径替换请参考 webpack 配置
