### ISSUE TITLE
Taro v1.3.0-beta.5 微信小程序模板传递props为空

### ISSUE THREAD

**Issue by yucccc** [NervJS/taro#3176]
**问题描述**
使用 ``taro init`` 选择微信小程序模板初始化项目 
在初始化项目 ``src/pages/index/index``文件中给Avatar组件随便传递一个参数 组件内接收为空

**如下**
```js
export default class Index extends Component {
 // some code
  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
       {/* 传递参数 Avatar接收为空 */}
        <Avatar name={1} />
        <Navigator url='plugin://myPlugin/list'>
          Go to pages/list!
        </Navigator>
      </View>
    )
  }
}
```

**系统信息**
 Taro v1.3.0-beta.5
  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-less: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      nervjs: ^1.3.9 => 1.3.13

**Comment by Chen-jj** [comment]
@yucccc 微信小程序插件开发，使用插件的页面或组件传参给插件组件还有问题，需要再想想怎么解决。

**Comment by yucccc** [comment]
🤦‍♀️

**Comment by yucccc** [comment]
@Chen-jj 那影响开发者使用吗 建议开发者应用在生产环境吗

**Comment by Chen-jj** [comment]
@yucccc 微信小程序插件开发先用回 v1.2.6

**Comment by Chen-jj** [comment]
@yucccc 已修复，参考[文档](https://nervjs.github.io/taro/docs/miniprogram-plugin.html#taro-v13-%E7%BB%84%E4%BB%B6%E6%8F%92%E4%BB%B6%E6%8E%A5%E5%8F%97%E5%A4%96%E9%83%A8-props-%E7%9A%84%E9%97%AE%E9%A2%98)，应该 1.3.3 上线。
