### ISSUE TITLE
使用微信自定义 tab bar 报错

### ISSUE THREAD

**Issue by biliGates** [NervJS/taro#3179]
**问题描述**
在 项目`src`文件夹下添加了自定义的`custom-tab-bar.js`文件，在编译完成之后，在项目`dist`文件夹下生成了 `custom-tab-bar.js`、`custom-tab-bar.wxss`、`custom-tab-bar.json`、`custom-tab-bar.wxml`文件，但是开发者工具中出现报错，并且自定义tab bar 无法展示。

**报错信息**
```js
Error: Component is not found in path "custom-tab-bar/index"
    at m (WAService.js:1)
    at WAService.js:1
    at se (WAService.js:1)
    at WAService.js:1
    at Object.t [as onReady] (WAService.js:1)
    at WAService.js:1
    at f (WAService.js:1)
    at WAService.js:1
    at WAService.js:1
    at e (appservice?t=1558772993325:1261)
```

**系统信息**
```bash
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.11.0 - E:\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Users\37826\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - E:\nodejs\npm.CMD
```

**补充信息**
经测试，把dist目录下以上四个文件移动到如下位置，即可正常运行。
```bash
dist/
  custom-tab-bar/
    index.js
    index.json
    index.wxml
    index.wxss
```

**Comment by Chen-jj** [comment]
@biliGates 看看你的目录结构，正确做法是在 src 目录下添加 custom-tab-bar 文件夹存放组件。

![image](https://user-images.githubusercontent.com/11807297/59179222-f4801980-8b93-11e9-9760-2edb1d708e69.png)

**Comment by Cjhome** [comment]
![image](https://user-images.githubusercontent.com/19768869/66733945-d86aec80-ee93-11e9-86e2-b8d13c8a72f0.png)
还是会报
![image](https://user-images.githubusercontent.com/19768869/66733964-ee78ad00-ee93-11e9-8ac6-9c745dea5dcb.png)

**Comment by Chen-jj** [comment]
@Cjhome index.vue 是什么操作
