### ISSUE TITLE
input 组件多次点击会失效

### ISSUE THREAD

**Issue by williamnie** [NervJS/taro#3181]
如果在两个输入框之间来回切换，多切几次，输入框就会坏掉，无法输入了，明显特征就是placeholder显示了
taro 试了很多个版本都有这个问题，目前是最新的1.13-beta5版本，
node版本10.9
复现视频 地址   链接: https://pan.baidu.com/s/1EYpZPM2GGzXv2rUxEqf2Lg 提取码: 4759 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by williamnie** [comment]
貌似是微信的bug，今天看到微信小程序社区里面也有问的，应该不是taro的问题

**Comment by yuche** [comment]
复现代码更关键

**Comment by williamnie** [comment]
已经确定是微信的bug了，原生小程序代码也会有问题，官方已经修复了
https://developers.weixin.qq.com/community/develop/doc/00068c12078570d9c89821c2b51c00?jumpto=comment&commentid=00026a5d7d0910e5d098ca6fb564
