### ISSUE TITLE
[RN]Label组件无法自定义样式

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3183]
**问题描述**
看了下 `node_modules/@tarojs/components-rn/dist/components/Label/index.js`的实现，这个组件是使用View来模拟的。在RN中View是没有color、fontSize之类的样式的。我建议这里改用Text来包裹。

**期望行为**
Label能像其他平台一样自定义样式

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
👽 Taro v1.3.0-beta.3

  Taro CLI 1.3.0-beta.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2

**Comment by Manjiz** [comment]
`<Label />` 是可以包裹其它内容的，不单是文本，所以，你可以在 `<Label />` 下面加 `<Text />` 来控制文本的样式
