### ISSUE TITLE
是否一种一致的解决方案让markdown在各端都可以正常展示？

### ISSUE THREAD

**Issue by linxiaowu66** [NervJS/taro#3184]
目前markdown虽然可以转为html用RichText去展示，可是RichText在小程序端展示的效果可以以一塌糊涂来表示，有的人可能说可以使用wxParse，但是RN端呢？有没有出个一致性方案，解决这些所有的问题，就不需要我们一个终端用一种，这样也符合该框架提出的目标，不是吗？

**Comment by yuche** [comment]
这个情况用环境变量更好一些
https://nervjs.github.io/taro/docs/envs.html#

多端开发不是所有端所有代码都一样，是有差异时能给你提供方案。

**Comment by SunnyQjm** [comment]
@linxiaowu66 
https://github.com/SunnyQjm/taro_rich_text
自己撸的Taro框架下的Markdown解析，目前测试支持微信小程序端和H5端（其他端没有测试）
