### ISSUE TITLE
beta.5 设置input的type为number时？，输入过程中，控制台报错

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#3185]
![QQ截图20190527093657](https://user-images.githubusercontent.com/13210798/58390297-1beac880-8063-11e9-8555-241cb9f76282.png)
![QQ截图20190527093710](https://user-images.githubusercontent.com/13210798/58390298-1beac880-8063-11e9-92e6-a0f05cf7e68b.png)

**Comment by jinjinjin0731** [comment]
贴一下你完整的写法

**Comment by kucy** [comment]
> 贴一下你完整的写法

<Input className='input name' placeholder='请输入用户名/手机号' maxLength='11' onFocus={this.onNameFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} type='number' value={name} onConfirm={this.confirm.bind(this)} onInput={this.inputName.bind(this)}  />

**Comment by kucy** [comment]
<Input className='input name' placeholder='请输入用户名/手机号' maxLength='11' onFocus={this.onNameFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} type='number' value={name} onConfirm={this.confirm.bind(this)} onInput={this.inputName.bind(this)}  />
          @jinjinjin0731

**Comment by kucy** [comment]
![number_bug](https://user-images.githubusercontent.com/13210798/58391039-9e28bc00-8066-11e9-98f4-7c586f513c2b.png)
@jinjinjin0731

**Comment by kucy** [comment]
`<Input className='input name' placeholder='请输入用户名/手机号' maxLength='11' onFocus={this.onNameFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} type='number' value={name} onConfirm={this.confirm.bind(this)} onInput={this.inputName.bind(this)}  />`

**Comment by jinjinjin0731** [comment]
没有能够复现这个问题。 可以提供下可以复现的demo 吗？ 把可以复现的 组件 or 页面文件的 代码贴一下。 @kucy

**Comment by kucy** [comment]
`import Taro, { Component } from '@tarojs/taro'
import { View, Image, Text, Input, Button } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import md5 from 'md5-node'
import { post, get } from '../../util/js/request'
import { changeUser } from '../../actions/user'
import '../../util/css/login_vendor.scss'
import './login.scss'
import { isWeiXin } from '../../util/js/tool'
import SwitchPc from '../../components/switch_pc/switch_pc'
import { IS_FIRST_LOGIN, PROMOTER, PLATFORM, USER_NAME, USER_PASS } from '../../constants/storage_keys'
import logoImg from '../../assets/images/logo@3x.png'

@connect(({ user }) => ({
  user
}), (dispatch) => ({
  dispatchUser (data) {
    dispatch(changeUser(data))
  }
}))
class Login extends Component {
  config = {
    navigationBarTitleText: '登录'
  }

  constructor (props) {
    super(props)
    this.state = {
      name: '',
      password: '',
      showPass: false,
      isShowNameError: false,
      isShowPasswordErrorIcon: false,
      isShowPasswordErrorText: false,
      redirectPage: '',
      isCheckedPassword: true
    }
  }

  async componentDidMount () {
    if (typeof this.$router.params.redirectPage !== 'undefined') {
      this.setState({
        redirectPage: decodeURIComponent(this.$router.params.redirectPage)
      })
    }
    if (process.env.TARO_ENV === 'h5' && isWeiXin() && process.env.NODE_ENV === 'production') { // 
      let href = window.location.href
      let code = this.$router.params.code || ''
      // http://rc2.yunzhiqu.com/h5/index.html?code=061wo6A31NqMcR1tSdB31TzWz31wo6AP&state=STATE#/pages/login/login
      if (!code && href.indexOf('code=') !== -1) {
        code = href.substring(href.indexOf('code=') + 5, href.indexOf('&state='))
      }
      if (!code) {
        if (href.indexOf('yunzhiqu.com') !== -1 && href.indexOf('code=') === -1) {
          window.location.href = `https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2402a285f9fe3ca3&redirect_uri=${encodeURIComponent(href)}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirec`;
        }
      } else {
        try {
          Taro.showLoading({
            mask: true,
            title: '登陆中'
          })
          let res = await get('weChat/getWeChatUserInfo?code=' + code)
          Taro.hideLoading()
          if (res.success === 'true') {
            if (res.info.mobile) {
              this.props.dispatchUser(res.info)
              // Taro.navigateTo({
              //   'url': '/pages/index/index'
              // })
              window.location.href = href.substring(0, href.indexOf('index.html') + 10) + '#/pages/index/index'
            } else {
              try {
                let promoterRes = await post('/weChat/getEventKey', {openid: res.info.openid})
                // console.log('promoterRes: ', promoterRes)
                // alert(JSON.stringify(promoterRes))
                if (promoterRes.info.promoter && promoterRes.info.promoter !== '') {
                  global.cookie.set(PROMOTER, promoterRes.info.promoter)
                }
                if (promoterRes.info.platform && promoterRes.info.platform !== '') {
                  global.cookie.set(PLATFORM, promoterRes.info.platform)
                }
              } catch (e) {
                console.log(e)
              }
              
              Taro.navigateTo({
                url: '/pages/register/register?openid=' + res.info.openid + '&type=3'
              })
            }
          } else {
            Taro.showToast({
              icon: 'none',
              title: res.msg
            })
          }
        } catch (e) {
          Taro.hideLoading()
          console.log(e)
        }
      }
    } else {
      if (global.cookie.get(USER_NAME) && global.cookie.get(USER_PASS)) {
        this.setState({
          name: global.cookie.get(USER_NAME),
          password: global.cookie.get(USER_PASS) 
        })
      }
    }
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  switchShowPass () {
    this.setState({
      showPass: !this.state.showPass
    })
  }

  keyBoradBlur () {
    if (process.env.TARO_ENV === 'h5') {
      window.scrollTo(0, 1)
    }
  }

  async confirm () {
    let name = this.state.name
    let password = this.state.password
    if (process.env.TARO_ENV === 'h5') {
      let loginList = document.getElementsByClassName('login-index')
      name = document.getElementsByClassName('login-index')[loginList.length - 1].getElementsByClassName('name')[0].value
      password = document.getElementsByClassName('login-index')[loginList.length - 1].getElementsByClassName('password')[0].value
    }
    if (name.trim() === '') {
      Taro.showToast({
        'icon': 'none',
        'title': '请输入用户名'
      })
      return
    }
    if (password.trim() === '') {
      Taro.showToast({
        'icon': 'none',
        'title': '请输入密码'
      })
      return
    }
    if (!RegExp('^1[0-9]{10}$').test(name)) {
      Taro.showToast({
        'icon': 'none',
        'title': '手机号格式有误'
      })
      return
    }
    try {
      Taro.showLoading({
        'title': '提交中',
        mask: true
      })
      let res = await post('user/session/get', {
        'mobile': name,
        'passwd': md5(password)
      })
      if (!res) {
        Taro.hideLoading()
        return
      }
      if (res.success !== 'true') {
        Taro.hideLoading()
        if (res.code * 1 === 4004) {
          this.setState({
            isShowNameError: true
          })
          return
        }
        // if (res.code * 1 === 4008) {
        //   this.setState({
        //     isShowPasswordErrorIcon: true,
        //     isShowPasswordErrorText: true
        //   })
        //   setTimeout(() => {
        //     this.setState({
        //       isShowPasswordErrorText: false
        //     })
        //   }, 1500)
        //   return
        // }
        Taro.showToast({
          'icon': 'none',
          'title': res.msg
        })
        return
      }
      let userInfo = await post('user/userInfo/get', {
        'session_mid': res.info.session_mid,
        'session_mtoken': res.info.session_mtoken
      })
      if (userInfo.success !== 'true') {
        Taro.hideLoading()
        Taro.showToast({
          'icon': 'none',
          'title': userInfo.msg
        })
        return
      }
      if (this.state.isCheckedPassword) {
        global.cookie.set(USER_NAME, this.state.name)
        global.cookie.set(USER_PASS, this.state.password)
      }
      let user = {}
      Object.assign(user, res.info)
      Object.assign(user, userInfo.info)
      this.props.dispatchUser(user)
      this.keyBoradBlur()
      let nextUrl = ''
      if (!!Taro.getStorageSync(IS_FIRST_LOGIN)) {
        nextUrl = '/pages/mall/mall'
      } else {
        nextUrl = !!this.state.redirectPage ? this.state.redirectPage : '/pages/index/index'
      }
      Taro.removeStorageSync(IS_FIRST_LOGIN)
      if (process.env.NODE_ENV !== 'production') {
        if (process.env.TARO_ENV !== 'h5') {
          Taro.switchTab({
            'url': nextUrl
          })
        } else {
          Taro.navigateTo({
            'url': nextUrl
          })
        }
        
      } else {
        if (process.env.TARO_ENV !== 'h5') {
          Taro.switchTab({
            'url': nextUrl
          })
        } else {
          let href = window.location.href
          window.location.href = href.substring(0, href.indexOf('index.html') + 10) + '#' + nextUrl
        }
      }
      
    } catch (e) {
      Taro.hideLoading()
      Taro.showToast({
        'icon': 'none',
        'title': '登录失败'
      })
      console.log('err: ', e)
    }
  }

  inputName (event) {
    this.setState({
      'name': event.detail.value
    })
  }

  inputPassword (event) {
    this.setState({
      'password': event.detail.value
    })
  }

  forget () {
    Taro.navigateTo({
      'url': '/pages/register/register?type=2'
    })
  }

  toRegister () {
    Taro.navigateTo({
      url: '/pages/register/register?type=1'
    })
  }

  onNameFocus () {
    if (this.state.isShowNameError) {
      this.setState({
        isShowNameError: false
      })
    }
  }

  onPasswordFocus () {
    if (this.state.isShowPasswordErrorIcon) {
      this.setState({
        isShowPasswordErrorIcon: false
      })
    }
  }

  switchChecked () {
    this.setState({
      isCheckedPassword: !this.state.isCheckedPassword
    })
  }

  render () {
    let { name, password, showPass, isCheckedPassword } = this.state
    return (
      <View className='login-index login-common'>
        <Text className='register' onClick={this.toRegister.bind(this)}>注册</Text>
        <Image src={logoImg} className='logo'></Image>
        <View className='form'>
          <View className='input-item'>
            <Image className='left-icon icon-user' src={require('../../assets/images/icon_login_user@3x.png')}></Image>
            <Input className='input name' placeholder='请输入用户名/手机号' maxLength='11' onFocus={this.onNameFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} type='number' value={name} onConfirm={this.confirm.bind(this)} onInput={this.inputName.bind(this)}  />
          </View>
          <View className='input-item'>
            <Image className='left-icon icon-password' src={require('../../assets/images/icon_password@3x.png')}></Image>
            <Input className='input password' placeholder='请输入密码' onFocus={this.onPasswordFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} confirmType='提交' value={password} type='text' password={!showPass} onConfirm={this.confirm.bind(this)} onInput={this.inputPassword.bind(this)} />
            <Image className='right-icon' src={showPass ? require('../../assets/images/zhengyan-2@3x.png') : require('../../assets/images/biyan@3x.png')} onClick={this.switchShowPass.bind(this)} ></Image>
          </View>
        </View>
        <Button className='submit' onClick={this.confirm.bind(this)}>登录</Button>
        <View className='forget-checked'>
          <Text className='forget' onClick={this.forget.bind(this)}>忘记密码?</Text>
          <View className='checked' onClick={this.switchChecked.bind(this)}>
            <Image className='ck-icon'  src={isCheckedPassword ? require('../../assets/images/icon_checked_select@3x.png') : require('../../assets/images/icon_checked_normal@3x.png')} />
            <Text>记住密码</Text>
          </View>
        </View>
        <SwitchPc />
      </View>
    )
  }
}

export default Login
`

`{
	"name": "hhh",
	"version": "1.0.0",
	"private": true,
	"description": "",
	"scripts": {
		"build:weapp": "taro build --type weapp",
		"build:swan": "taro build --type swan",
		"build:alipay": "taro build --type alipay",
		"build:tt": "taro build --type tt",
		"build:h5": "taro build --type h5",
		"build:rn": "taro build --type rn",
		"dev:weapp": "npm run build:weapp -- --watch",
		"dev:swan": "npm run build:swan -- --watch",
		"dev:alipay": "npm run build:alipay -- --watch",
		"dev:tt": "npm run build:tt -- --watch",
		"dev:h5": "npm run build:h5 -- --watch",
		"dev:rn": "npm run build:rn -- --watch"
	},
	"author": "",
	"license": "MIT",
	"dependencies": {
		"@tarojs/async-await": "1.3.0-beta.5",
		"@tarojs/components": "1.3.0-beta.5",
		"@tarojs/redux": "1.3.0-beta.5",
		"@tarojs/redux-h5": "1.3.0-beta.5",
		"@tarojs/router": "1.3.0-beta.5",
		"@tarojs/taro": "1.3.0-beta.5",
		"@tarojs/taro-alipay": "1.3.0-beta.5",
		"@tarojs/taro-h5": "1.3.0-beta.5",
		"@tarojs/taro-swan": "1.3.0-beta.5",
		"@tarojs/taro-tt": "1.3.0-beta.5",
		"@tarojs/taro-weapp": "1.3.0-beta.5",
		"md5-node": "^1.0.1",
		"nerv-devtools": "^1.3.9",
		"nervjs": "^1.3.9",
		"redux": "^4.0.0",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0"
	},
	"devDependencies": {
		"@types/react": "^16.4.8",
		"@types/webpack-env": "^1.13.6",
		"@tarojs/plugin-babel": "1.3.0-beta.5",
		"@tarojs/plugin-csso": "1.3.0-beta.5",
		"@tarojs/plugin-sass": "1.3.0-beta.5",
		"@tarojs/plugin-uglifyjs": "1.3.0-beta.5",
		"@tarojs/webpack-runner": "1.3.0-beta.5",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"babel-eslint": "^8.2.3",
		"eslint": "^4.19.1",
		"eslint-config-taro": "1.3.0-beta.5",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-taro": "1.3.0-beta.5"
	}`

**Comment by kucy** [comment]
`import Taro, { Component } from '@tarojs/taro'
import { View, Image, Text, Input, Button } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import md5 from 'md5-node'
import { post, get } from '../../util/js/request'
import { changeUser } from '../../actions/user'
import '../../util/css/login_vendor.scss'
import './login.scss'
import { isWeiXin } from '../../util/js/tool'
import SwitchPc from '../../components/switch_pc/switch_pc'
import { IS_FIRST_LOGIN, PROMOTER, PLATFORM, USER_NAME, USER_PASS } from '../../constants/storage_keys'
import logoImg from '../../assets/images/logo@3x.png'

@connect(({ user }) => ({
  user
}), (dispatch) => ({
  dispatchUser (data) {
    dispatch(changeUser(data))
  }
}))
class Login extends Component {
  config = {
    navigationBarTitleText: '登录'
  }

  constructor (props) {
    super(props)
    this.state = {
      name: '',
      password: '',
      showPass: false,
      isShowNameError: false,
      isShowPasswordErrorIcon: false,
      isShowPasswordErrorText: false,
      redirectPage: '',
      isCheckedPassword: true
    }
  }

  async componentDidMount () {
    if (typeof this.$router.params.redirectPage !== 'undefined') {
      this.setState({
        redirectPage: decodeURIComponent(this.$router.params.redirectPage)
      })
    }
    if (process.env.TARO_ENV === 'h5' && isWeiXin() && process.env.NODE_ENV === 'production') { // 
      let href = window.location.href
      let code = this.$router.params.code || ''
      // http://rc2.yunzhiqu.com/h5/index.html?code=061wo6A31NqMcR1tSdB31TzWz31wo6AP&state=STATE#/pages/login/login
      if (!code && href.indexOf('code=') !== -1) {
        code = href.substring(href.indexOf('code=') + 5, href.indexOf('&state='))
      }
      if (!code) {
        if (href.indexOf('yunzhiqu.com') !== -1 && href.indexOf('code=') === -1) {
          window.location.href = `https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2402a285f9fe3ca3&redirect_uri=${encodeURIComponent(href)}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirec`;
        }
      } else {
        try {
          Taro.showLoading({
            mask: true,
            title: '登陆中'
          })
          let res = await get('weChat/getWeChatUserInfo?code=' + code)
          Taro.hideLoading()
          if (res.success === 'true') {
            if (res.info.mobile) {
              this.props.dispatchUser(res.info)
              // Taro.navigateTo({
              //   'url': '/pages/index/index'
              // })
              window.location.href = href.substring(0, href.indexOf('index.html') + 10) + '#/pages/index/index'
            } else {
              try {
                let promoterRes = await post('/weChat/getEventKey', {openid: res.info.openid})
                // console.log('promoterRes: ', promoterRes)
                // alert(JSON.stringify(promoterRes))
                if (promoterRes.info.promoter && promoterRes.info.promoter !== '') {
                  global.cookie.set(PROMOTER, promoterRes.info.promoter)
                }
                if (promoterRes.info.platform && promoterRes.info.platform !== '') {
                  global.cookie.set(PLATFORM, promoterRes.info.platform)
                }
              } catch (e) {
                console.log(e)
              }
              
              Taro.navigateTo({
                url: '/pages/register/register?openid=' + res.info.openid + '&type=3'
              })
            }
          } else {
            Taro.showToast({
              icon: 'none',
              title: res.msg
            })
          }
        } catch (e) {
          Taro.hideLoading()
          console.log(e)
        }
      }
    } else {
      if (global.cookie.get(USER_NAME) && global.cookie.get(USER_PASS)) {
        this.setState({
          name: global.cookie.get(USER_NAME),
          password: global.cookie.get(USER_PASS) 
        })
      }
    }
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  switchShowPass () {
    this.setState({
      showPass: !this.state.showPass
    })
  }

  keyBoradBlur () {
    if (process.env.TARO_ENV === 'h5') {
      window.scrollTo(0, 1)
    }
  }

  async confirm () {
    let name = this.state.name
    let password = this.state.password
    if (process.env.TARO_ENV === 'h5') {
      let loginList = document.getElementsByClassName('login-index')
      name = document.getElementsByClassName('login-index')[loginList.length - 1].getElementsByClassName('name')[0].value
      password = document.getElementsByClassName('login-index')[loginList.length - 1].getElementsByClassName('password')[0].value
    }
    if (name.trim() === '') {
      Taro.showToast({
        'icon': 'none',
        'title': '请输入用户名'
      })
      return
    }
    if (password.trim() === '') {
      Taro.showToast({
        'icon': 'none',
        'title': '请输入密码'
      })
      return
    }
    if (!RegExp('^1[0-9]{10}$').test(name)) {
      Taro.showToast({
        'icon': 'none',
        'title': '手机号格式有误'
      })
      return
    }
    try {
      Taro.showLoading({
        'title': '提交中',
        mask: true
      })
      let res = await post('user/session/get', {
        'mobile': name,
        'passwd': md5(password)
      })
      if (!res) {
        Taro.hideLoading()
        return
      }
      if (res.success !== 'true') {
        Taro.hideLoading()
        if (res.code * 1 === 4004) {
          this.setState({
            isShowNameError: true
          })
          return
        }
        // if (res.code * 1 === 4008) {
        //   this.setState({
        //     isShowPasswordErrorIcon: true,
        //     isShowPasswordErrorText: true
        //   })
        //   setTimeout(() => {
        //     this.setState({
        //       isShowPasswordErrorText: false
        //     })
        //   }, 1500)
        //   return
        // }
        Taro.showToast({
          'icon': 'none',
          'title': res.msg
        })
        return
      }
      let userInfo = await post('user/userInfo/get', {
        'session_mid': res.info.session_mid,
        'session_mtoken': res.info.session_mtoken
      })
      if (userInfo.success !== 'true') {
        Taro.hideLoading()
        Taro.showToast({
          'icon': 'none',
          'title': userInfo.msg
        })
        return
      }
      if (this.state.isCheckedPassword) {
        global.cookie.set(USER_NAME, this.state.name)
        global.cookie.set(USER_PASS, this.state.password)
      }
      let user = {}
      Object.assign(user, res.info)
      Object.assign(user, userInfo.info)
      this.props.dispatchUser(user)
      this.keyBoradBlur()
      let nextUrl = ''
      if (!!Taro.getStorageSync(IS_FIRST_LOGIN)) {
        nextUrl = '/pages/mall/mall'
      } else {
        nextUrl = !!this.state.redirectPage ? this.state.redirectPage : '/pages/index/index'
      }
      Taro.removeStorageSync(IS_FIRST_LOGIN)
      if (process.env.NODE_ENV !== 'production') {
        if (process.env.TARO_ENV !== 'h5') {
          Taro.switchTab({
            'url': nextUrl
          })
        } else {
          Taro.navigateTo({
            'url': nextUrl
          })
        }
        
      } else {
        if (process.env.TARO_ENV !== 'h5') {
          Taro.switchTab({
            'url': nextUrl
          })
        } else {
          let href = window.location.href
          window.location.href = href.substring(0, href.indexOf('index.html') + 10) + '#' + nextUrl
        }
      }
      
    } catch (e) {
      Taro.hideLoading()
      Taro.showToast({
        'icon': 'none',
        'title': '登录失败'
      })
      console.log('err: ', e)
    }
  }

  inputName (event) {
    this.setState({
      'name': event.detail.value
    })
  }

  inputPassword (event) {
    this.setState({
      'password': event.detail.value
    })
  }

  forget () {
    Taro.navigateTo({
      'url': '/pages/register/register?type=2'
    })
  }

  toRegister () {
    Taro.navigateTo({
      url: '/pages/register/register?type=1'
    })
  }

  onNameFocus () {
    if (this.state.isShowNameError) {
      this.setState({
        isShowNameError: false
      })
    }
  }

  onPasswordFocus () {
    if (this.state.isShowPasswordErrorIcon) {
      this.setState({
        isShowPasswordErrorIcon: false
      })
    }
  }

  switchChecked () {
    this.setState({
      isCheckedPassword: !this.state.isCheckedPassword
    })
  }

  render () {
    let { name, password, showPass, isCheckedPassword } = this.state
    return (
      <View className='login-index login-common'>
        <Text className='register' onClick={this.toRegister.bind(this)}>注册</Text>
        <Image src={logoImg} className='logo'></Image>
        <View className='form'>
          <View className='input-item'>
            <Image className='left-icon icon-user' src={require('../../assets/images/icon_login_user@3x.png')}></Image>
            <Input className='input name' placeholder='请输入用户名/手机号' maxLength='11' onFocus={this.onNameFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} type='number' value={name} onConfirm={this.confirm.bind(this)} onInput={this.inputName.bind(this)}  />
          </View>
          <View className='input-item'>
            <Image className='left-icon icon-password' src={require('../../assets/images/icon_password@3x.png')}></Image>
            <Input className='input password' placeholder='请输入密码' onFocus={this.onPasswordFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} confirmType='提交' value={password} type='text' password={!showPass} onConfirm={this.confirm.bind(this)} onInput={this.inputPassword.bind(this)} />
            <Image className='right-icon' src={showPass ? require('../../assets/images/zhengyan-2@3x.png') : require('../../assets/images/biyan@3x.png')} onClick={this.switchShowPass.bind(this)} ></Image>
          </View>
        </View>
        <Button className='submit' onClick={this.confirm.bind(this)}>登录</Button>
        <View className='forget-checked'>
          <Text className='forget' onClick={this.forget.bind(this)}>忘记密码?</Text>
          <View className='checked' onClick={this.switchChecked.bind(this)}>
            <Image className='ck-icon'  src={isCheckedPassword ? require('../../assets/images/icon_checked_select@3x.png') : require('../../assets/images/icon_checked_normal@3x.png')} />
            <Text>记住密码</Text>
          </View>
        </View>
        <SwitchPc />
      </View>
    )
  }
}

export default Login
`
`{
	"name": "hhh",
	"version": "1.0.0",
	"private": true,
	"description": "",
	"scripts": {
		"build:weapp": "taro build --type weapp",
		"build:swan": "taro build --type swan",
		"build:alipay": "taro build --type alipay",
		"build:tt": "taro build --type tt",
		"build:h5": "taro build --type h5",
		"build:rn": "taro build --type rn",
		"dev:weapp": "npm run build:weapp -- --watch",
		"dev:swan": "npm run build:swan -- --watch",
		"dev:alipay": "npm run build:alipay -- --watch",
		"dev:tt": "npm run build:tt -- --watch",
		"dev:h5": "npm run build:h5 -- --watch",
		"dev:rn": "npm run build:rn -- --watch"
	},
	"author": "",
	"license": "MIT",
	"dependencies": {
		"@tarojs/async-await": "1.3.0-beta.5",
		"@tarojs/components": "1.3.0-beta.5",
		"@tarojs/redux": "1.3.0-beta.5",
		"@tarojs/redux-h5": "1.3.0-beta.5",
		"@tarojs/router": "1.3.0-beta.5",
		"@tarojs/taro": "1.3.0-beta.5",
		"@tarojs/taro-alipay": "1.3.0-beta.5",
		"@tarojs/taro-h5": "1.3.0-beta.5",
		"@tarojs/taro-swan": "1.3.0-beta.5",
		"@tarojs/taro-tt": "1.3.0-beta.5",
		"@tarojs/taro-weapp": "1.3.0-beta.5",
		"md5-node": "^1.0.1",
		"nerv-devtools": "^1.3.9",
		"nervjs": "^1.3.9",
		"redux": "^4.0.0",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0"
	},
	"devDependencies": {
		"@types/react": "^16.4.8",
		"@types/webpack-env": "^1.13.6",
		"@tarojs/plugin-babel": "1.3.0-beta.5",
		"@tarojs/plugin-csso": "1.3.0-beta.5",
		"@tarojs/plugin-sass": "1.3.0-beta.5",
		"@tarojs/plugin-uglifyjs": "1.3.0-beta.5",
		"@tarojs/webpack-runner": "1.3.0-beta.5",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"babel-eslint": "^8.2.3",
		"eslint": "^4.19.1",
		"eslint-config-taro": "1.3.0-beta.5",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-taro": "1.3.0-beta.5"
	}`

@jinjinjin0731

**Comment by jinjinjin0731** [comment]
@kucy   根据你的代码片段来看。可能是这里出的问题。
```jsx
<Input className='input password' placeholder='请输入密码' onFocus={this.onPasswordFocus.bind(this)} onBlur={this.keyBoradBlur.bind(this)} confirmType='提交' value={password} type='text' password={!showPass} onConfirm={this.confirm.bind(this)} onInput={this.inputPassword.bind(this)} />
```
你试一下吧 type = 'text' 删掉试一下

**Comment by kucy** [comment]
是输入手机号的过程中控制台一直打印错误。和密码框没影响吧。type='text'也删过。还是不行。
[bug.zip](https://github.com/NervJS/taro/files/3221637/bug.zip)

**Comment by kucy** [comment]
是输入手机号的过程中控制台一直打印错误。和密码框没影响吧。type='text'也删过。还是不行。
[bug.zip](https://github.com/NervJS/taro/files/3221640/bug.zip)  @jinjinjin0731

**Comment by jinjinjin0731** [comment]
你定位下这里的  input 的 type 是什么属性。 number 的话不应该会报这个错。。。我本地没有复现这个问题。 你可以抽一个 简易版的 demo 发一下吗？

**Comment by kucy** [comment]
[textnumber.zip](https://github.com/NervJS/taro/files/3221705/textnumber.zip)
重现demo。 @jinjinjin0731

**Comment by slmev** [comment]
number类型就是不支持

**Comment by kucy** [comment]
@jinjinjin0731 请看楼上回答

**Comment by jinjinjin0731** [comment]
@kucy  晚点看下

@slmev  源码做了处理。  number 和 file 类型都不会做 selection 处理

**Comment by slmev** [comment]
@jinjinjin0731
```
!['number', 'file'].indexOf('number') >= 0
``` 
改成
```
!(['number', 'file'].indexOf('number') >= 0)
```

**Comment by jinjinjin0731** [comment]
@slmev  @kucy   看到了。一个 PR 引起的问题，写的有问题。
 刚才我本地没有重新 install 所以没有复现。
@kucy  可以暂时进 node_modules 里面找到 ` @taro/js -> componenst -> src -> componenst -> input ` 改一下这里的源码。  后续这里我修复下
