### ISSUE TITLE
百度小程序父组件props传值子组件时而成功时而失败

### ISSUE THREAD

**Issue by vincentxiu** [NervJS/taro#3188]
编译成百度小程序时，父组件请求接口后拿到的值传递给子组件时，有时会出现子组件接收失败的情况，有时可以接收到，接口的数据每一次都是正常拿到的。

**Comment by ckytx** [comment]
升级到1.2.27-beta0或者最新的1.3.0-beta版

**Comment by Chen-jj** [comment]
#2245
