### ISSUE TITLE
1.2.26 如何配置qq轻应用project.config.json

### ISSUE THREAD

**Issue by NauxChen** [NervJS/taro#3189]
**问题描述**
如题

**补充信息**
因为微信小程序和QQ小程序差不多，目前做了用dev:weapp+环境变量的方式进行打包，现在卡在project.config.json怎么根据环境变量设置qq小程序appid。
看了cli的代码好像是直接用的readJSONSync。
目前有办法根据环境变量设置project.config.json吗

**Comment by foreverpw** [comment]
@NauxChen  请问如何解决的
