### ISSUE TITLE
Taro Page 中调用this.$preloadData，提示不存在

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#3192]
**问题描述**
Taro: v1.3.0-beta.5
页面中使用预加载机智，调用this.$preloadData提示不存在，实际上使用是没问题的，应该是Component中少了$preloadData的声明吧
![image](https://user-images.githubusercontent.com/29176413/58399312-5b78db00-808a-11e9-840b-5b536e2a3510.png)

**Comment by Garfield550** [comment]
`index.d.ts` 好像是没有，你可以提一个 PR。

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/3227
