### ISSUE TITLE
父容器为flex:1,子元素的高度设置为100% 会失效。

### ISSUE THREAD

**Issue by kucy** [NervJS/taro#3193]
![image](https://user-images.githubusercontent.com/13210798/58400447-97fa0600-808d-11e9-9ca9-f0cf141f4a2d.png)

**Comment by luckyadam** [comment]
建议了解一下 flex 布局

**Comment by kucy** [comment]
tabbar 用了flex布局。不会导致页面的高度设置为100%失效吗？如果空页面使用absolute定位撑满，又会导致在ios上滑动体验不好 @luckyadam
