### ISSUE TITLE
innerAudioContext.pause() 不生效

### ISSUE THREAD

**Issue by lhy58** [NervJS/taro#3194]
![1558940230(1)](https://user-images.githubusercontent.com/24452719/58401245-dee8fb00-808f-11e9-84b0-0a655decd011.png)

**Comment by luckyadam** [comment]
ios 还是 android 上不生效？

**Comment by lhy58** [comment]
ios,发现这个方法根本就不执行

**Comment by lhy58** [comment]
找到问题了
应该是吧这段代码放在最前面
const innerAudioContext = Taro.createInnerAudioContext(this)
不能放在函数里面
不然每次点击都会create一个新的,是暂停不了的
