### ISSUE TITLE
使用iconfont时如何做体积优化

### ISSUE THREAD

**Issue by vand7813** [NervJS/taro#3196]
目前项目中使用iconfont的方法是创建iconfont.css文件，app.js中引用。
但是在自定义组件不能用全局样式，需要单独引入iconfont.css文件，造成每个组件都会复制一份，空间有些浪费。

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/component-style.html#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%E7%B1%BB

**Comment by vand7813** [comment]
多谢🙏
