### ISSUE TITLE
react hooks 定义的state 不能在小程序的template里面使用

### ISSUE THREAD

**Issue by JasLin** [NervJS/taro#3198]
**问题描述**

小程序的template使用的是Component里面定义的Data的数据，react hooks 定义的state生成的数据并没有设置到组件的state里面去。

**复现步骤**

A.js
```jsx
function A () {
  const [content, setContent] = useState({
      text: 'this is a template'
  })
  return (
    <View>
      <import src='./tmp.wxml' />
      <template is='item' data='{{...content}}' />
    </View>
  )

export default A
```

tmp.wxml
```html
<template name="item">
  <view>
    <text>a {{text}} b</text>
  </view>
</template>
```

**期望行为**

template能够渲染出来 ```a this is a template b```

**报错信息**

错误的渲染的结果：  ```a b```

**系统信息**

  Taro CLI 1.3.0-beta.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-sass: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4
      react: ^16.8.6 => 16.8.6
    npmGlobalPackages:
      typescript: 2.9.1

**补充信息**

```js
    key: "_createData",
    value: function _createData() {
      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __isRunloopRef = arguments[2];
      ;

      var _useState = (0, _index.useState)({
        text: 'this is a template'
      }),
          _useState2 = _slicedToArray(_useState, 2),
          content = _useState2[0],
          setContent = _useState2[1];

      Object.assign(this.__state, {}); // FIXME: 这里如果把hooks的状态assign给组件的_state，就可以了， ```Object.assign(this.__state, { content});```
      return this.__state;
    }
  }]);
```

生成的小程序的代码，createData没有吧state设置给_state,所以template使用不了

Object.assign(this.__state, {});

这里如果把hooks的状态assign给组件的_state，就可以了， ```Object.assign(this.__state, { content});```

**Comment by JasLin** [comment]
ps: 用React.Component 定义state，则可以正常的渲染，因为this.__state里面能找到对应的变量。 不知function component 有什么办法可以绕过去？

**Comment by yuche** [comment]
不推荐这样混写，变量只有在 jsx 中用到才会加入到最后 assign 的 state 里。
如果有强烈这样的需求可以在随便一个地方用一次：

```
function A () {
  const [content, setContent] = useState({
      text: 'this is a template'
  })
  return (
    <Block t={content}>
      <import src='./tmp.wxml' />
      <template is='item' data='{{...content}}' />
    </Block>
  )

```

**Comment by JasLin** [comment]
正常不会使用template，是因为用了第三方组件towxml所致。
不过。hooks定义的state本身就是组件的状态，应该被是被组件全局使用的吧？

**Comment by yuche** [comment]
不会，你没用到就不会使用
