### ISSUE TITLE
微信小程序websocket请求问题

### ISSUE THREAD

**Issue by easonzhuyi** [NervJS/taro#3199]
**问题描述**
微信小程序中开发者工具预览正常，真机模式下 查看调试工具面板 network中websocket的请求会转到xhr下，wss服务没有配置问题（其他原生写的微信小程序在用）

**复现步骤**
[复现问题的步骤]
Taro.getSystemInfo({
        success: info => {
          console.log(info.model, info.system)
          // if (!(info.model.indexOf("iPhone") > -1 || info.system.indexOf("iOS") > -1))
          // return

          Taro.connectSocket({
            url: xxx,
            success: function () {
              console.log('connect success')
            }
          }).then(task => {
            task
              .onError(function () {
                console.log('onError')
               
              })
            task.onMessage(function (msg) {
              console.log('onMessage: ', msg)
              // task.close()
            })
           ...

        }
      })

**期望行为**
在network中查看到ws中的链接

**报错信息**

无报错

**系统信息**
Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0
      Yarn: 1.10.0 
      npm: 6.4.1 

**补充信息**
直接在打包后的文件中写原生小程序wx.connectSocket也是同样的状况

**Comment by Chen-jj** [comment]
@easonzhuyi Taro API 只是调用了 wx 的 API 而已，并没有做什么额外处理，建议到微信小程序社区找找解决办法

**Comment by easonzhuyi** [comment]
我用原生写的也一样，可能是真机调试的功能

> @easonzhuyi Taro API 只是调用了 wx 的 API 而已，并没有做什么额外处理，建议到微信小程序社区找找解决办法

的确，我用原生写的也一样，可能是开发者工具真机调试功能的问题，关闭这个issue吧

**Comment by ThoughtZer** [comment]
@easonzhuyi 不知是否有解决办法，这样的话，就没办法调试了。因为 我们的需求中有录音，录音的`onFrameRecorded` 方法在开发工具里面不触发，只有真机触发，然而真机又不能发起ws请求

**Comment by shenghanqin** [comment]
> @easonzhuyi 不知是否有解决办法，这样的话，就没办法调试了。因为 我们的需求中有录音，录音的`onFrameRecorded` 方法在开发工具里面不触发，只有真机触发，然而真机又不能发起ws请求

按说真机有vConsole调试，看到效果就行。另外，比如音频播放这种，开发者工具里面跟真机就差异特别多，还是以真机为准！

**Comment by ThoughtZer** [comment]
@shenghanqin 好吧 你是对的  已经发现了  只是看着不一样，但是实际是对的，，，
