### ISSUE TITLE
weapp,使用navigateTo和左上角的返回，会报错。

### ISSUE THREAD

**Issue by wbget** [NervJS/taro#320]
**问题描述**
https://github.com/wbget/taro-test

**复现步骤**
[复现问题的步骤]
来回跳转，9次必现。

```js
(node) warning: possible EventEmitter memory leak detected. 16 listeners added. Use emitter.setMaxListeners() to increase limit.

```

**系统信息**

 - 操作系统: macOS 10.13.2
 - Taro 版本 [e.g. v.0.0.68]
 - Node.js 版本 [e.g. v8.9.4]

**Comment by yuche** [comment]
这大概是因为小程序只能有 10层 。
![image](https://user-images.githubusercontent.com/7202516/42991420-064ef368-8c38-11e8-8dba-c971e60e092a.png)
https://developers.weixin.qq.com/miniprogram/dev/api/ui-navigate.html

**Comment by wbget** [comment]
左上角应该是出栈，应该一直在1和0之间。

**Comment by luckyadam** [comment]
安装到最新版本试试呢

**Comment by wbget** [comment]
[微信的问题](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=0004cefe50c628782d17c4ebc51c00&commentid=00042e60a0c8100a21177158e5ec&parent_commentid=000e66e1444e38a92e17528ea518&commentid=0004ce65ec0588c92f178685f5b8&parent_commentid=000e66e1444e38a92e17528ea518&token=666404097&devtools=1)
