### ISSUE TITLE
使用taro ui定制化，打包成小程序出现组件路径错误

### ISSUE THREAD

**Issue by Janice1114** [NervJS/taro#3205]
**问题描述**
基于taro-ui 定制自己样式的多端UI组件库， 打包成小程序报错，提示组件路径不正确。

**复现步骤**
[复现问题的步骤]
1. 引入taro-ui 作为package.json 的依赖， "taro-ui": "^2.1.0"; 用的taro 的相关依赖版本为 1.2.26
2. 基于taro-ui 的component js， 创建自己的定制化component 的 js文件
```js
import Taro from '@tarojs/taro'
import { AtRadio as MuRadio } from 'taro-ui'
import '../../style/components/radio.scss'

export default MuRadio

```
3. 文件打包入口 `ui.js` 添加相关component 作为导出
```js
export { default as MuRadio } from './components/radio'
```
4.  运行命令 `npm run build:weapp` 打包成小程序，发现报错：  组件错误  组件MuRadio路径错误，请检查！（可能原因是导出的组件名不正确）
工程的相关config 如下： 

```js
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true
        },
        url: {
          enable: true,
          limit: 10240
        }
      }
    },
    resolve: {
      // alias: {
      //   'taro-ui': 'ui/taro-ui'
      // }
    }
  },
  h5: {
    publicPath: '/',
    esnextModules: ['taro-ui'],
    staticDirectory: 'static',
    module: {
      postcss: {
        autoprefixer: {
          enable: true
        }
      }
    }
  },
```

**期望行为**
打包成小程序不会出错，这个路径是真实存在的， 打包成H5没问题。

**报错信息**
组件错误  组件MuRadio路径错误，请检查！（可能原因是导出的组件名不正确）
![error](https://user-images.githubusercontent.com/22658512/58446901-1958a380-8135-11e9-81db-7029fe9c11a7.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.2.26]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
taro-cli 打包成小程序的时候，解析文件路径有问题

**Comment by Janice1114** [comment]
@luckyadam  请问下这个发现是什么问题吗？ 麻烦帮解决下

**Comment by Janice1114** [comment]
请问有后续跟进吗？谢谢 @luckyadam

**Comment by foreverpw** [comment]
+1

**Comment by Fantasy9527** [comment]
楼主问题解决了么
