### ISSUE TITLE
Taro.setNavigationBarColor 在百度小程序里面设置不生效

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#3206]
```
Taro.setNavigationBarColor({
      backgroundColor: '#2CC998',
      frontColor: '#ffffff'
    }).then(res => {
      console.log("setNavigationBarColor");
      console.log(res);
    })
```
没效果

**Comment by danieltao1993** [comment]
Taro中找不到Taro.setPageInfo方法，Taro已经更新到最新版本，其他依赖也全部更新
  componentDidShow() {
    console.log('setPageInfo', this.$scope);
    debugger;
    let setPageInfo = Taro.setPageInfo || this.$scope.setPageInfo;
    setPageInfo && setPageInfo({
      title: '湖北交警96110',
      keywords: '湖北交警,湖北交警96110,湖北高速交警,湖北事故报警,湖北高速事故,湖北高速事故报警',
      description: '以高速桩号和位置码形式表示交通事故发生位置，解决在高速路上事故当事人无法准确说明自己位置的问题，便于交警、事故当事人及时准确获取事故发生位置。',
      success: function () {
        console.log('setPageInfo success');
      },
      fail: function (err) {
        console.log('setPageInfo fail', err);
      }
    })
  }

**Comment by danieltao1993** [comment]
需要调用的是百度小程序的api：swan.setPageInfo；但是Taro中无法获取到，不知道怎么才能访问，是Taro没有更新swan的底层依赖吗？

**Comment by Chen-jj** [comment]
@patchBig @danieltao1993 欢迎 PR：https://github.com/NervJS/taro/blob/master/packages/taro/src/native-apis.js

**Comment by Chen-jj** [comment]
@patchBig 复现不了

```js
export default class Detail extends Component {
  componentDidMount () {
    Taro.setNavigationBarColor({
      backgroundColor: '#2CC998',
      frontColor: '#ffffff'
    })
      .then(res => {
        console.log("setNavigationBarColor");
        console.log(res);
      })
  }
  render () {
    return (
      <View>
        <A />
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/59168651-39db2180-8b69-11e9-8355-2c1c3ad24d24.png)
