### ISSUE TITLE
H5端在安卓手机内某些APP内打开，Taro.navigateTo失效

### ISSUE THREAD

**Issue by zacharyzc** [NervJS/taro#3207]
**问题描述**
在安卓手机（如华为，小米）“建设银行”App内，通过扫一扫功能打开taro项目编写的h5页面，第一次在页面A点击按钮跳转页面B后，在页面B点返回按钮回到页面A，再次点击按钮却无法跳转至页面B

**复现步骤**
1. 安卓手机下载建行手机客户端
2. 通过扫一扫打开网页（网页需为https）
3. 页面A点击跳转按钮至页面B
4. 页面B点返回至页面A
5.页面A再次点击按钮，无法跳转至页面B

```

// 页面A
Taro.navigateTo({
    url: xxx
})

// 页面B
Taro.navigateBack({
   delta:1
})

 ```

**期望行为**
本人猜测该问题的原因可能是因为taro项目对某个浏览器版本存在兼容问题，希望得到解决。若是本人代码问题希望能给予提示

**报错信息**

点返回报错如下

_**Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "text/html;charset=utf-8;base64," to begin with "".**_

第二次点击报错如下
**_Failed to excute 'pushState' on 'History', A history state object with URL '' cannot be created in a document with origin 'xxx' and URL 'data:text/html;charset=utf-8;base64;'_**

**系统信息**

Taro CLI 1.3.0-beta.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/components: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/plugin-babel: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/plugin-csso: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/plugin-sass: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/redux: 1.2.27-beta.0 => 1.2.27-beta.0 
      @tarojs/redux-h5: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/router: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/taro: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/taro-alipay: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/taro-h5: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/taro-swan: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/taro-weapp: 1.3.0-beta.2 => 1.3.0-beta.2 
      @tarojs/webpack-runner: 1.3.0-beta.2 => 1.3.0-beta.2 
      eslint-config-taro: 1.3.0-beta.2 => 1.3.0-beta.2 
      eslint-plugin-taro: 1.3.0-beta.2 => 1.3.0-beta.2 
      nervjs: ^1.3.9 => 1.3.13 

**补充信息**

是不是对某些浏览器版本存在不兼容，还望解决～模糊之处可联系本人微信zhangc0605

**Comment by Littly** [comment]
弄了个页面尝试调试，但建行app扫码出来页面直接白屏无法调试。有什么操作需要特别注意的吗？

**Comment by carltian** [comment]
same issue
