### ISSUE TITLE
没有新的 createContext API

### ISSUE THREAD

**Issue by Shawmon** [NervJS/taro#3208]
**问题描述**
访问不到新的 createContext API
**复现步骤**
yarn dev:alipay

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Image } from '@tarojs/components'
import styles from './index.css'
Taro.createContext({})
// ...
```
**期望行为**
能够访问到 Taro.createContext API

**报错信息**
![image](https://user-images.githubusercontent.com/21117408/58449210-21b4dc80-813d-11e9-96b5-39f6667e6098.png)
![image](https://user-images.githubusercontent.com/21117408/58449220-2ed1cb80-813d-11e9-8f9c-6c7c8318b232.png)
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro v1.3.0-beta.5

  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-sass: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/redux: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/redux-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      nervjs: ^1.3.9 => 1.3.13 
    npmGlobalPackages:
      typescript: 3.0.3

**Comment by yuche** [comment]
你这是哪个平台
