### ISSUE TITLE
bind 方法会把 immutable 对象转换成普通对象

### ISSUE THREAD

**Issue by ypli0629** [NervJS/taro#321]
```
onClick={this.convert.bind(this,immutableObj)}
```
方法接收到的是普通对象

**Comment by Simbachen** [comment]
bind的参数这里会通过小程序的data来传递，这里建议通过其他的方式来传递immutableObj。例如：提供一个对象的map，
data = [immutableObj]
onClick={this.convert.bind(this,index)}

**Comment by yuche** [comment]
1.3 之后已经没有这个限制
