### ISSUE TITLE
小程序端npm run dev:weapp运行，出现_index.genCompid is no a function的错误

### ISSUE THREAD

**Issue by Creat155** [NervJS/taro#3210]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

![image](https://user-images.githubusercontent.com/39396448/58458386-ab73a280-815b-11e9-9cb8-466ed2cf1a8c.png)

微信开发者工具版本号是1.02
Taro版本是1.26

**Comment by Chen-jj** [comment]
@Creat155 CLI 版本和依赖版本保持一致。

**Comment by Creat155** [comment]
> @Creat155 CLI 版本和依赖版本保持一致。

请问一下怎么降级CLI的版本号，麻烦了？

**Comment by Chen-jj** [comment]
@Creat155 直接 npm install -g @tarojs/cli@[指定版本] 即可

**Comment by Creat155** [comment]
thanks @Chen-jj
