### ISSUE TITLE
createCanvasContext在H5环境下的问题

### ISSUE THREAD

**Issue by liucien** [NervJS/taro#3211]
**问题描述**
createCanvasContext 在H5环境下vnode一直无法被函数内获取到，微信小程序可以正常工作

**复现步骤**
组件内使用就行

代码片段
![image](https://user-images.githubusercontent.com/32785166/58459970-34d8a400-815f-11e9-8bea-a27d78ad9320.png)

直接报错，打断点进去vnode是有这个值的
![image](https://user-images.githubusercontent.com/32785166/58460049-5cc80780-815f-11e9-9086-08ebe87386e2.png)

**期望行为**
应该入文档表述的一致
![image](https://user-images.githubusercontent.com/32785166/58459786-c8f63b80-815e-11e9-979a-6683469fdb2c.png)

**报错信息**
![image](https://user-images.githubusercontent.com/32785166/58459684-8e8c9e80-815e-11e9-93ec-ddbfdcae7925.png)

**系统信息**
![image](https://user-images.githubusercontent.com/32785166/58460218-c21bf880-815f-11e9-9d75-20d662009aea.png)

**Comment by RedLlips** [comment]
我h5报的是：
index.esm.js?eb04:2469 TypeError: Cannot read property 'getContext' of null
    at createCanvasContext (createCanvasContext.js?3cd4:15)
    at WrappedComponent.componentWillMount (notfound.js?9be0:24)
    at eval (index.js?1e21:1528)
    at errorCatcher (index.js?1e21:1481)
    at mountComponent (index.js?1e21:1527)
    at ComponentWrapper.init (index.js?1e21:1869)
    at createElement (index.js?1e21:1384)
    at mountChild (index.js?1e21:1450)
    at mountVNode$1 (index.js?1e21:1440)
    at createElement (index.js?1e21:1390)

我的版本是 1.2.26

**Comment by MrGetlman** [comment]
我是在H5上面没有任何效果。

`componentDidMount() {
		const ctx = Taro.createCanvasContext('canvas', this.$scope);
		console.log(ctx,"ctx")
		ctx.rect(0, 0, 150, 75);
		ctx.setFillStyle('red');
		ctx.fill();
		ctx.draw();
	}`

**Comment by RedLlips** [comment]
h5好像不支持taro提供的Canvas，你可以用原生的。然后通过环境判断。

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/58786422-1c163580-861a-11e9-891a-e822935af7a6.png)
这里是 `canvasId` 吧
