### ISSUE TITLE
添加Taro.cloud.CloudID字段

### ISSUE THREAD

**Issue by 1995wyy** [NervJS/taro#3212]
**问题描述**
微信小程序 Taro.cloud中缺少CloudID字段。

```js
console.log(wx.cloud);
console.log(Taro.cloud);
```

![image](https://user-images.githubusercontent.com/37872336/58461480-61da8600-8162-11e9-9318-6896ce9c9878.png)

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.3-bata5]
 - Node.js 版本 [e.g. v10]
 - 报错平台 [weapp]

**Comment by jinjinjin0731** [comment]
2.7.0 版本出的新 api 。可以暂时直接 wx.cloud 调用。
