### ISSUE TITLE
1.3.0-beta.5 H5暂时不支持 API createContext

### ISSUE THREAD

**Issue by BensonEu** [NervJS/taro#3215]
**问题描述**
H5调用 createContext 报错

**复现步骤**
// ```js
import Taro, { createContext } from '@tarojs/taro';

const context = createContext('test');
// ```
**期望行为**
正常使用createContext

**报错信息**
![1559032759528](https://user-images.githubusercontent.com/27949351/58464295-04e1ce80-8168-11e9-9f61-bf98a4d7b72d.jpg)

**系统信息**
Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.config/yarn/global/node_modules/.bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/cli: ^1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-sass: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/rn-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro: ^1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4

**Comment by yuche** [comment]
升级一下 nervjs 的依赖

**Comment by BensonEu** [comment]
升级 nervjs 到 1.4.0-beta.5 , 问题依然存在
