### ISSUE TITLE
H5下编译报错：Cannot read property 'logInterceptor' of undefined

### ISSUE THREAD

**Issue by beilo** [NervJS/taro#3216]
**问题描述**
H5下编译报错：Cannot read property 'logInterceptor' of undefined，
Cannot read property 'timeoutInterceptor' of undefined

```js
const request = <T>(
  url: string,
  method: HttpMethod,
  parms?: {
    data?: object | string | arrayBuffer;
    header?: any;
  }
) => {
  Taro.addInterceptor(Taro.interceptors.logInterceptor);  // 报错代码
  Taro.addInterceptor(Taro.interceptors.timeoutInterceptor);
  return new Promise<T>((resolve, reject) => {
    Taro.request({
      url: baseUrl + url,
      method: method,
      data: parms!.data,
      header: parms!.header || headers(),
      success: res => {
        const { statusCode = '', header = {}, data = {} } = res || {};
        if (statusCode >= 200 && statusCode <= 300) {
          Taro.setStorage({
            key: 'response_time',
            data: new Date(header!.date)!.getTime() || 0
          });
          resolve(data!.data as T);
        } else if (statusCode == 401) {
          // 跳转登录
          Taro.navigateTo({
            url: '/pages/user/login/index?goback=1'
          });
          reject(new Error('登录失效,请重新登录'));
        } else if (statusCode == 500) {
          const msg = data!.msg;
          reject(new Error(msg));
        }
        reject(new Error('服务器正在维护中...'));
      },
      fail: err => {
        reject(err);
      }
    });
  });
};
```

**报错信息**
```
Cannot read property 'logInterceptor' of undefined，
Cannot read property 'timeoutInterceptor' of undefined
```

**系统信息**
Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/mobx: 1.2.26 => 1.2.26 
      @tarojs/mobx-h5: 1.2.26 => 1.2.26 
      @tarojs/mobx-rn: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/rn-runner: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13

**Comment by luckyadam** [comment]
可以升级到最新版本试一下

**Comment by beilo** [comment]
1.3.0 5beta版本没问题
