### ISSUE TITLE
微信小程序 云函数 开发的 ts 编译问题

### ISSUE THREAD

**Issue by zheNeng** [NervJS/taro#3219]
**问题描述**
云函数的 ts 编译,云函数内的node_module资源引用路径错误。

**复现步骤**
1. 在 src 下，新建 cloudfunction 云函数文件夹
2. 在 src/cloudfunction 新建 add 文件夹（add 云函数）与 index.ts
3. 在 src/cloudfunction/index.ts 中引入 ./add 
4. 在 src/app.tsx 中引入 src/cloudfunction/index
5. 在 src/cloudfunction/add/index.ts 中引入src/cloudfunction/node_modules/wx-server-sdk/index.js
6. 编译项目
**期望行为**
期望编译后的 cloudfunction/add/index 中引入的wx-server-sdk 路径是当前node_modules中的，而不是根 node_modules 下的
![image](https://user-images.githubusercontent.com/28520144/58482334-c14f8a80-8190-11e9-888c-b1c645084401.png)

**系统信息**
👽 Taro v1.3.0-beta.4
  Taro CLI 1.3.0-beta.4 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm**补充信息**

[可选]
1. webpack 可以 增加一个云函数配置。
2. 或者暴露更多的 webpack 配置

**Comment by shenghanqin** [comment]
@zheNeng 期待Taro 2.0版本吧
