### ISSUE TITLE
Context.Provider支持嵌套，请问mobx的Provider什么时候能支持嵌套？

### ISSUE THREAD

**Issue by BrookShuihuaLee** [NervJS/taro#3221]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

原生mobx是支持Provider嵌套的。一开始我在Taro里也这么用了，后来才发现Taro不支持mobx的Provider嵌套。这对mobx来说，像是个bug

**复现步骤**
[复现问题的步骤]
1. 在Taro里嵌套mobx的Provider

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

Taro里的mobx应该尽量跟原生的mobx表现一致

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - Taro 版本 1.3.0-beta.3

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

谢谢各位开发，Taro很棒，希望它变得更棒

**Comment by nanjingboy** [comment]
@BrookShuihuaLee 最近事情有点多，会抽时间跟进 taro 的 Context 的。

**Comment by renjie1996** [comment]
> @BrookShuihuaLee 最近事情有点多，会抽时间跟进 taro 的 Context 的。

能不能提高优先级尽快支持，没有这个功能。实在太难用了

**Comment by cncolder** [comment]
如果 Mobx 能跟进支持 hooks, 或许可以直接使用 Taro.createContext 来创建 Provider

https://feathub.com/NervJS/taro/+67

**Comment by BrookShuihuaLee** [comment]
> 如果 Mobx 能跟进支持 hooks, 或许可以直接使用 Taro.createContext 来创建 Provider
> 
> https://feathub.com/NervJS/taro/+67

目前就可以用context，只是得用contextType获取。
不过我觉得比起mobx-react里的Provider，体验还是差很远。

**Comment by cncolder** [comment]
> 目前就可以用context，只是得用contextType获取。
> 不过我觉得比起mobx-react里的Provider，体验还是差很远。

现在模拟的是 mobx-react@5, mobx 全面拥抱 hooks 以后, API 变化比较大.

**Comment by BrookShuihuaLee** [comment]
> > 目前就可以用context，只是得用contextType获取。
> > 不过我觉得比起mobx-react里的Provider，体验还是差很远。
> 
> 现在模拟的是 mobx-react@5, mobx 全面拥抱 hooks 以后, API 变化比较大.

不清楚mobx-react@6的计划。我认为目前还是应该实现最常用的API。Taro的最大优势就是React，在使用方式上越接近原生React，用户的学习成本就越低，这个优势也就越大。反之亦然

**Comment by nanjingboy** [comment]
@BrookShuihuaLee 由于现在还不支持下面的写法：

```js
import Taro from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'

const Index = () => {
  return doSomething(() => {
    return (
      <View>
        <Text>Hello World</Text>
      </View>
    )
  })
}

function doSomething(fn) {
  return fn();
}

export default Index;
```

也没想到好的方法绕过该限制，所以暂时不知如何实现，使用 useContext 吧，使用方法查看：[示例](https://github.com/nanjingboy/taro-mobx-sample/tree/master/src/pages/useContext)

**Comment by BrookShuihuaLee** [comment]
> @BrookShuihuaLee 由于现在还不支持下面的写法：
> 
> ```js
> import Taro from '@tarojs/taro'
> import { View, Text } from '@tarojs/components'
> import './index.scss'
> 
> const Index = () => {
>   return doSomething(() => {
>     return (
>       <View>
>         <Text>Hello World</Text>
>       </View>
>     )
>   })
> }
> 
> function doSomething(fn) {
>   return fn();
> }
> 
> export default Index;
> ```
> 
> 也没想到好的方法绕过该限制，所以暂时不知如何实现，使用 useContext 吧，使用方法查看：[示例](https://github.com/nanjingboy/taro-mobx-sample/tree/master/src/pages/useContext)

好的
