### ISSUE TITLE
[RN]Taro.getCurrentPages方法不存在

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3224]
**问题描述**
升级到1.3.0.beta5之后，这个方法报错了。在beta3都还存在，只是参数没跟其他端保持一致。。。

**期望行为**
跟其他端的结果保持一致

**报错信息**
```
2019-05-29 03:48:46.158 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
TypeError: _taroRn2.default.getCurrentPages is not a function. (In '_taroRn2.default.getCurrentPages()', '_taroRn2.default.getCurrentPages' is undefined)
```

**系统信息**
```
👽 Taro v1.3.0-beta.5


  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by Pines-Cheng** [comment]
代码方便贴一下吗？

**Comment by Pines-Cheng** [comment]
我这里测试的能获取到啊。

**Comment by yechunxi** [comment]
Taro CLI 1.3.0-beta.3 
System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm

Taro.getCurrentPages() 在componentDidShow 调用，返回正常。
但是在componentDidMount() 中调用，就会报错 _taroRn.default.getCurrentPages is not a function

**Comment by Pines-Cheng** [comment]
@yechunxi 感谢反馈～
