### ISSUE TITLE
[Feature Request]js文件支持条件编译

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3225]
**问题描述**
类似 https://nervjs.github.io/taro/docs/before-dev-remind.html#%E6%A0%B7%E5%BC%8F%E4%BB%A3%E7%A0%81%E7%9A%84%E6%9D%A1%E4%BB%B6%E7%BC%96%E8%AF%91 这样。

现在是可以通过`*.rn.js`来分平台，但是对于一些很少的变化，还是希望在原来的文件中增加判断来做。

如果使用 `if (process.env.TARO_ENV === 'rn')` 来判断并引入第三方类库，在RN下会有一些奇怪问题

**Comment by luckyadam** [comment]
会有啥奇怪的问题
