### ISSUE TITLE
组件无法改名

### ISSUE THREAD

**Issue by BrookShuihuaLee** [NervJS/taro#3226]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

如果有一个组件`ComponentA`。使用`const Component = ComponentA; return <Component />`无法渲染`ComponentA`。这在配置化的时候，问题变得很严重。`const Component = config.Component; return <Component />`永远是无效的。

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js

const Component = ComponentA; return <Component />

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**

变量改名之后组件能正常渲染

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - Taro 版本 1.3.0-beta.3

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

Taro是个好框架

**Comment by yuche** [comment]
这个没有办法做到，JSX 是在编译时把 JSX 编译到 wxml 的。这类在运行时才能确定 JSX 到底是哪个组件的行为是做不到的。

**Comment by BrookShuihuaLee** [comment]
> 这个没有办法做到，JSX 是在编译时把 JSX 编译到 wxml 的。这类在运行时才能确定 JSX 到底是哪个组件的行为是做不到的。

好的，谢谢，目前看来是有难度。希望有一天能有办法支持。。。
