### ISSUE TITLE
ScrollView 组件的 scrollIntoView 属性在 H5 端不生效

### ISSUE THREAD

**Issue by draculapile** [NervJS/taro#3238]
**问题描述**
ScrollView 组件的 scrollIntoView 属性在 H5 端不生效

**复现步骤**
```js
  // ...
  state = {
    scrollInto: 'content-0'
  }
  btnClickOne () {
    this.setState({
      scrollInto: 'content-0'
    })
  }
  btnClickTwo () {
    this.setState({
      scrollInto: 'content-1'
    })
  }
  btnClickThree () {
    this.setState({
      scrollInto: 'content-2'
    })
  }
  render() {
    let { scrollInto } = this.state
    console.log('render', scrollInto)
    return (
      <View className='test-scroll'>
        <Button className='btn' onClick={this.btnClickOne.bind(this)}>1</Button>
        <Button className='btn' onClick={this.btnClickTwo.bind(this)}>2</Button>
        <Button className='btn' onClick={this.btnClickThree.bind(this)}>3</Button>
        <ScrollView scrollY scrollIntoView={scrollInto} style={{height: '300px'}}>
          <View style={{background: 'green', height: '300px'}} className='content' id='content-0'></View>
          <View style={{background: 'yellow', height: '300px'}} className='content' id='content-1'></View>
          <View style={{background: 'red', height: '300px'}} className='content' id='content-2'></View>
        </ScrollView>
      </View>
    )
  }


```

**期望行为**
点击按钮绑定的事件，ScrollView 内容应该能够滚动对应 id 的区域

**报错信息**
无报错，render 函数里 console.log('render', scrollInto) 能打印正确的信息，但是 ScrollView 不滚动

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本: v.1.2.26
 - Node.js 版本: 10.15.3
 - 报错平台: h5

**补充信息**

![{E9A84AA4-876A-424D-9C78-055F50395353}_20190529145551](https://user-images.githubusercontent.com/24435036/58536087-299a7c80-8222-11e9-8887-04d325e8ec01.jpg)

![{9740828A-9C49-48B3-84C1-40F3BCCDB4E9}_20190529145627](https://user-images.githubusercontent.com/24435036/58536102-2d2e0380-8222-11e9-933e-6bb045faca3b.jpg)

**Comment by jinjinjin0731** [comment]
暂不支持。

**Comment by draculapile** [comment]
> 暂不支持。有点问题正在修复

OK了解，期待修复，谢谢

**Comment by IFmiss** [comment]
@jinjinjin0731  请问锚点滚动现在支持了吗

**Comment by ssun125** [comment]
h5貌似还是不行啊

**Comment by giantss** [comment]
在h5上我也试过了不行

**Comment by vibin-lin** [comment]
2020年8月了, 依旧没有修复...

**Comment by ZakaryCode** [comment]
> 2020年8月了, 依旧没有修复...

这是一个已经关闭的 issue，如果有问题可以提交一个新的 issue 描述相关问题。

另外该问题已经在 #690fcc8 修复，如果确实存在问题，应描述`编译平台、版本`等相关信息，并提交事例用于复现问题。
