### ISSUE TITLE
更新到1.3.0-beta.5 组件全局样式出问题了

### ISSUE THREAD

**Issue by dawang90** [NervJS/taro#3239]
**环境描述**
百度小程序

**问题描述**
组件全局样式 addGlobalClass: true
有部分样式名还是加上了组件名前缀
**复现步骤**
[复现问题的步骤]
组件at-modal
`<View onTouchMove={this.handleTouchMove} className='at-modal'>`
        `<View className='at-modal__overlay' onClick={this.handleClickOverlay} />`
        `<View className='at-modal__container'>{this.props.children}</View>`
      `</View>`
实际输出
`<view className='at-modal_at-modal'>`
        `<view className='at-modal__overlay'></view>`
        `<view className='at-modal__container'>{this.props.children}</View>`
      `</view>`
**期望行为**

`<view className='at-modal'>`
       ` <view className='at-modal__overlay'></view>`
        `<view className='at-modal__container'>{this.props.children}</View>`
      `</view>`

**Comment by Chen-jj** [comment]
@dawang90 没懂你描述的问题是什么，完善一下描述，并提供详细可复现的代码吧。

**Comment by Chen-jj** [comment]
@dawang90 等百度下一个版本咯。

![image](https://user-images.githubusercontent.com/11807297/58617339-6df54d80-82f2-11e9-84e1-e39dabdc84f1.png)

**Comment by dawang90** [comment]
> @dawang90 等百度下一个版本咯。
> 
> ![image](https://user-images.githubusercontent.com/11807297/58617339-6df54d80-82f2-11e9-84e1-e39dabdc84f1.png)

期待下个版本的优化，我暂时在组件中引入对应样式来解决目前的问题

**Comment by Chen-jj** [comment]
@dawang90 嗯嗯，到时更新下百度开发者工具再试试吧。

**Comment by Chen-jj** [comment]
百度开发者工具，基础库改为 3.60.16 即可修复。
