### ISSUE TITLE
如何在用 react hooks 写的组件中监听 onPageScroll  事件

### ISSUE THREAD

**Issue by jing2si** [NervJS/taro#3241]
如题。
另外在 React Hooks 中怎样监听像 componentWillMount, componentDidShow 这种生命周期。

**Comment by yuche** [comment]
hooks 只能提供 useEffect 的生命周期。其它生命周期应该用 Class Component

**Comment by jing2si** [comment]
Thx, @yuche 那我只能把 hooks 组件当成 Class 组件的子组件去监听不支持的生命周期了

**Comment by baoxiangyang** [comment]
我也同样遇到了这个问题
