### ISSUE TITLE
H5:swiper的current赋为0，swiperItem视图不会变

### ISSUE THREAD

**Issue by mirokooku** [NervJS/taro#3242]
**问题描述**
1. H5:swiper的current赋为0的时候，swiperItem视图不会切换到第0个，小程序端可以
2.H5:scrollIntoView没有作用，小程序端是可以的

**复现步骤**
//问题1：
//`JSX`:
const tabList = [{ title: '多平台' }, { title: '亚马逊' }, { title: 'eBay' }, { title: '速卖通' }, { title: 'Lazada' }, { title: 'Wish' }]
<Swiper
        className='tabs-body'
        duration={300}
        // circular
        skipHiddenItemLayout
        current={this.state.current}
        onChange={(e) => {this.changeTab(e.detail.current)}}
      >
        {tabList.map((item) => {
          return <SwiperItem className='center'>标签内容--{item.title}</SwiperItem>
 })}

//`JS`:
  changeTab = (e) => {
    if (e !== this.state.current) {
      this.setState({
        current: e
      });
    }
  }

//问题2：
//`JSX`:
const tabList = [{ title: '多平台' }, { title: '亚马逊' }, { title: 'eBay' }, { title: '速卖通' }, { title: 'Lazada' }, { title: 'Wish' }]
<ScrollView className='header-scroll' scrollX scrollWithAnimation scrollIntoView={'header-item' + this.state.current}>
          <View className='header-scroll-inner'>
            {tabList.map(item => {
              const index = counter++;
              const isActiveClass = this.state.current === index ? 'header-item-active' : 'header-item-inactive';

              return (
                <View id={'header-item' + index} className={'header-item ' + isActiveClass} onClick={this.changeTab.bind(this, index)} key={index}>
                  <View className='header-item-inner'>
                    {item.title}
                    <View id={'header-item-underline' + index} className='header-item-underline'/>
                  </View>
                </View>
              )
            })}
          </View>
        </ScrollView>

//`JS`:
无

**期望行为**
1. 希望swiper的current赋值为0的时候，swiperitem切换到对应的第0个
2. 希望scrollIntoView改变时，能够正常起作用

**报错信息**
没有报错

**系统信息**
  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v11.12.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-less: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-sass: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/redux: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/redux-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      nervjs: 1.4.0-beta.4 => 1.4.0-beta.4

**补充信息**
这2个问题，小程序端都是OK的，但是H5端有问题

**Comment by haoxinxin** [comment]
current 值给字符串类型的就好了。

**Comment by jinjinjin0731** [comment]
已修复了。 忘记关闭
