### ISSUE TITLE
怎么构建类似Taro官网？

### ISSUE THREAD

**Issue by hengboy** [NervJS/taro#3245]
不好意思，请问下该怎么构建类似
https://nervjs.github.io/taro/docs/README.html

Taro官网这种的网站？

通过什么方式？

**Comment by Garfield550** [comment]
> 不好意思，请问下该怎么构建类似
> [nervjs.github.io/taro/docs/README.html](https://nervjs.github.io/taro/docs/README.html)
> 
> Taro官网这种的网站？
> 
> 通过什么方式？

Taro 文档用的是 [docusaurus](https://docusaurus.io/)，具体怎么构建文档参考 https://github.com/NervJS/taro/tree/master/docs 目录

**Comment by hengboy** [comment]
谢谢
