### ISSUE TITLE
升级到 1.3.0-beta.5 在H5端 onPullDownRefresh报ref找不到错误

### ISSUE THREAD

**Issue by itstrive** [NervJS/taro#3249]
**问题描述**
开启下拉刷新的时候，之前只有小程序支持，现在H5端升级到新版本后，出现报错
```
Cannot read property 'pullDownRefreshRef' of undefined
```

```
  componentDidShow() {
    this.pullDownRefreshRef && this.pullDownRefreshRef.bindEvent(); //这里找不到
  }

<PullDownRefresh onRefresh={this.onPullDownRefresh && this.onPullDownRefresh.bind(this)} ref={ref => {
      if (ref) this.pullDownRefreshRef = ref; //这里没有挂载上
    }}>{_temp}</PullDownRefresh>
```

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0-beta.5]
 - Node.js 版本 [e.g. v10.14.1]
 - 报错平台 [h5]

**补充信息**
[根据你的调查研究，出现这个问题的原因可能在哪里？]
猜测问题:
```
1. React在 v16.3之后 ref的形式变成了 `React.createRef() `
2. 在组件PullDownRefresh 中，用的还是 this.ref函数的形式
3. 也可能是 componentDidShow生命周期获取不到的原因，也就是在render之前触发了。
```

我现在解决办法是，暂时在H5中去掉了,onPullDownRefresh。

**Comment by Littly** [comment]
首先确保@tarojs/cli、@tarojs/werbpack-runner和@tarojs/taro-h5的版本一致。如果问题依然存在，那可能需要升级下nervjs，升级到1.4.0-beta.5再试。

**Comment by itstrive** [comment]
@Littly 我是直接通过 `yarn global add @tarojs/cli@latest` 升级的，项目中也都 `update`了，所以版本号肯定跟你们官方一致。
按照刚才您的回复，nervjs我也升级到 beta.5了，问题也一样存在的。
![image](https://user-images.githubusercontent.com/2168473/59174884-cd225000-8b85-11e9-8b72-bfd02a92f2f3.png)
