### ISSUE TITLE
ubuntu16.04安装npm安装taro成功，但找不到taro命令

### ISSUE THREAD

**Issue by xslshr** [NervJS/taro#3256]
ubuntu16.04安装npm安装taro成功，但找不到taro命令，npm版本6.9.0

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro/issues/699

参考这边的回复吧。

**Comment by DINGXIO96** [comment]
我这边也出现了相关问题
npm全局安装后还找不到taro命令
