### ISSUE TITLE
H5 端报错 this.refs.子组件.func() is not a function 

### ISSUE THREAD

**Issue by draculapile** [NervJS/taro#3258]
**问题描述**

使用 refs ，父组件直接调用子组件的方法，会报 is not a function

**复现步骤**

这个问题比较奇怪，组件结构如下：
![{3285CC30-FDB3-4F93-A329-161B190FF7CA}_20190530163233](https://user-images.githubusercontent.com/24435036/58619979-94b68280-82f8-11e9-8b17-c3cb4ba24155.jpg)

child three 向 component 传值，component 能拿到 argument，打印 this.refs.childTwo，拿到了组件实例，但是调用 func() 就会报错，在 child two 内部，func 如果绑定一下的话，
```js
  func = (arg) => {
    // handle arg
  }
```
打印 this.refs.childTwo，可以看到 func 出现在 _rendered.component 下面：

![{9C15E28A-81F6-45C2-BBFD-871A841602C9}_20190530163132](https://user-images.githubusercontent.com/24435036/58619902-69cc2e80-82f8-11e9-8908-fdfdcabbd5d9.jpg)

这是业务代码，我自己又写了个 demo 想复现这个 bug，并没有出现，但是，打印组件的信息，func 的位置出现在这里：

![{A0AF695E-17F0-49DF-BACD-030D0C2F0815}_20190530162229](https://user-images.githubusercontent.com/24435036/58620454-b2381c00-82f9-11e9-9e6c-18200e4cb380.jpg)

并不在 _rendered.component 里面，所以我想知道出现这种情况的原因是啥？谢谢！

**期望行为**

能正确调用子组件的方法

**报错信息**

![{BF58EA2D-3DC6-461A-B186-52BA6C366335}_20190530163729](https://user-images.githubusercontent.com/24435036/58620320-608f9180-82f9-11e9-87b0-c87b3c631b31.jpg)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本: v.1.2.26
 - Node.js 版本: v10.15.3
 - 报错平台: h5

**补充信息**

**Comment by yuche** [comment]
你找不到 ref 的情况被 connect 高阶组件包起来了，ref 指向的是 connect 组件

**Comment by draculapile** [comment]
> 你找不到 ref 的情况被 connect 高阶组件包起来了，ref 指向的是 connect 组件

看到了，页面引入了 connect ，那这种情况下，就只能写成 this.refs.组件名._rendered.component.func() 调用了么

**Comment by yuche** [comment]
你还可以使用 fowardRef API，不过只能在 h5 上用

**Comment by draculapile** [comment]
> 你还可以使用 fowardRef API，不过只能在 h5 上用

ok，谢谢！
