### ISSUE TITLE
1.3.0-bate.5 h5 config.navigationBarTitleText 无效

### ISSUE THREAD

**Issue by nxboo** [NervJS/taro#3265]
官方demo可复现  
config: Config = {
    navigationBarTitleText: '首页'
  }

**Comment by luckyadam** [comment]
未能复现

**Comment by xiaozhouwu** [comment]
用了mobx的页面就无效

**Comment by useryechen** [comment]
楼主解决了吗  我也出现这个问题了，需要在tabbar上二次点击title才会改变

**Comment by shenck215** [comment]
@xiaozhouwu 我也遇到了，mobx修饰后，navigationBarTitleText就无效了
