### ISSUE TITLE
this.$router.params中会多出一个与path同名的字段(weapp 1.3.0-beta.5)

### ISSUE THREAD

**Issue by so-diao** [NervJS/taro#3266]
**问题描述**
微信小程序中切换页面的时候，`this.$router.params`中会多出一个与`this.$router.path`同名的字段
如图 `params`应该是空的
![图片](https://user-images.githubusercontent.com/24741025/58680436-4d80ce00-839a-11e9-9879-ed908699bbce.png)

**复现步骤**
复现仓库 => [地址](https://github.com/so-diao/taro-report/tree/router)
```js
// 就这么切换就会出现，navigateTo也会
changePage() {
    Taro.redirectTo({
        url: '/view/posts'
    })
}
```

**系统信息**
 Taro v1.3.0-beta.5
 Taro CLI 1.3.0-beta.5 environment info:
   System:
     OS: Windows 7
   Binaries:
     Node: 10.7.0 - D:\node\node.EXE
     Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
     npm: 6.1.0 - D:\node\npm.CMD
报错平台 [weapp]

**Comment by Garfield550** [comment]
复现了，不过是只有在不给页面传参时发生的现象，如果是给页面传参的话，打印出的内容是正常的传参

```js
changePage() {
    Taro.redirectTo({
        url: '/view/posts?haha=233'
    })
}
```

![image](https://user-images.githubusercontent.com/3471836/58681755-5eccd900-83a0-11e9-8595-3f5f60a51d48.png)

我猜测你需要判断 params 是否是空对象，你可以先使用 `if (this.$router.params.haha)` 来判断传参是否正确，临时解决下

```js
if (this.$router.params.haha) {
    console.log('Haha')
}
```

![image](https://user-images.githubusercontent.com/3471836/58681851-e3b7f280-83a0-11e9-9902-d4ee839ba403.png)

**Comment by so-diao** [comment]
> 我猜测你需要判断 params 是否是空对象，你可以先使用 `if (this.$router.params.haha)` 来判断传参是否正确，临时解决下

我需要根据`params`拼出一个完整的url字符串，只有先手动删除一下了。

**Comment by so-diao** [comment]
https://github.com/NervJS/taro/blob/8f0fdcad5f05b0e21fca4cc049e6a0e04b1e221e/packages/taro-weapp/src/create-component.js#L306

**Comment by Garfield550** [comment]
问题可能出在更早的 cacheDataSet 上，Key 是个时间戳好像，对应的 Value 是一个以路径做名称的函数 'view/index': *ƒ* Index()

**Comment by Garfield550** [comment]
queryToJson 是不是有点问题呢 为什么会返回一个对象 { view/index: '' } 给 _params 呢
![image](https://user-images.githubusercontent.com/3471836/58688635-9abf6880-83b7-11e9-9a02-25a1e6c9a7ed.png)
![image](https://user-images.githubusercontent.com/3471836/58688683-c2aecc00-83b7-11e9-80c0-8161cc985e8b.png)
![image](https://user-images.githubusercontent.com/3471836/58688964-6bf5c200-83b8-11e9-84ba-63a576141f9f.png)
之后 L3869 的 cacheDataSet 就会把 _cacheKey 根 _params ({ view/index: '' }) 设置到一起，最后拿到的 params 就成了 { view/index: '' } 了呀

https://github.com/NervJS/taro/blob/923579b4e4e9660402c969ff88851caeeeb68f86/packages/taro-weapp/src/util.js#L211-L240

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/58689540-df4c0380-83b9-11e9-8491-9387e257c337.png)

**Comment by so-diao** [comment]
![图片](https://user-images.githubusercontent.com/24741025/58689923-f17a7180-83ba-11e9-80a6-ce224cb97545.png)

这段代码，url如果没有`?`就是-1了，后边一个index +1就是0了，把完整的url都传进去了。
`queryToJson`这个函数只能处理`a=1&b=2`这样字符串。

![截图](https://user-images.githubusercontent.com/24741025/58690114-651c7e80-83bb-11e9-972d-0e59ab8ea64e.png)

**Comment by Garfield550** [comment]
> ![图片](https://user-images.githubusercontent.com/24741025/58689923-f17a7180-83ba-11e9-80a6-ce224cb97545.png)
> 
> 这段代码，url如果没有`?`就是-1了，后边一个index +1就是0了，把完整的url都传进去了。
> `queryToJson`这个函数只能处理`a=1&b=2`这样字符串。
> 
> ![截图](https://user-images.githubusercontent.com/24741025/58690114-651c7e80-83bb-11e9-972d-0e59ab8ea64e.png)

是的，是这段
![image](https://user-images.githubusercontent.com/3471836/58690255-af056480-83bb-11e9-8321-14bfbabb7677.png)
![image](https://user-images.githubusercontent.com/3471836/58690260-b4fb4580-83bb-11e9-9624-4ef8b01449df.png)

**Comment by so-diao** [comment]
判断一下`?`就搞定了:thumbsup:

**Comment by Garfield550** [comment]
你去提 PR 吧 👍

**Comment by so-diao** [comment]
仔细看了一下`queryToJson`的逻辑，如果query参数如下，就没办法处理了，而且key是通过判断`=`符号的index，没有处理多级对象的`[]`，导致对象参数的key是这样的`obj[arr][]`
```js
// 不能正确处理obj
obj: {
    arr: [1, 2]
}

// queryStr
// obj[arr][]=1&obj[arr][]=2
// obj%5Barr%5D%5B%5D=1&obj%5Barr%5D%5B%5D=2
```
![图片](https://user-images.githubusercontent.com/24741025/58764442-90f55b00-8599-11e9-9b05-17eb83fc7302.png)

**Comment by Garfield550** [comment]
这个没有处理我觉得可以理解，想做全很麻烦，照顾到各种 Corner Case 是个很漫长的过程。

**Comment by so-diao** [comment]
> 这个没有处理我觉得可以理解，想做全很麻烦，照顾到各种 Corner Case 是个很漫长的过程。

恩，你说的对，刚对比了一下其他的路由库，发现也是没有做处理。
https://github.com/vuejs/vue-router/blob/ea8cb474f869a5a12a095fcb5989c45c68971d14/src/util/query.js
