### ISSUE TITLE
网络请求后redux不传递新的props给组件，需要重新打开页面才能看到上一次的数据

### ISSUE THREAD

**Issue by ShaneLuo97** [NervJS/taro#3268]
**问题描述**
Page组件使用Redux传递props，在componentDidMount生命周期dispatch了一个异步网络请求，并成功获取到数据，也成功更新到了store（console.log打印出来看到的），但是传递过来的props并没有更新，componentWillRecieveProps也不执行，视图不刷新，重复执行网络请求也能成功更新store，也是不刷新。如果重新进入该Page，可以展示上一次的数据。

对象的key并没有小数点，在reducer里面添加了一个时间戳也不行

**复现步骤**
```js
@connect(({ userData }) => ({
  userData
}), (dispatch) => ({
  doGetUserPublish(type, page, pageSize?) {
    dispatch(doGetUserPublish(type, page, pageSize))
  }
}))
class MyAccountPage extends Component<IProps, PageState> {

  constructor(props) {
    super(props)
    this.state = { nowKey: 'all', refresh: true };
    this.handleStar = this.handleStar.bind(this);
  }

  componentDidMount = () => {
    this.handleGetData();
  }

  handleGetData = () => {
    const { refresh, nowKey } = this.state;
    this.props.doGetUserPublish(nowKey, 1);
 }

 render () {
  ...
 }
}
```

**期望行为**
数据能实时更新

**报错信息**
![image](https://user-images.githubusercontent.com/30209869/58684035-54fba380-83a9-11e9-83f9-612165f30a69.png)
redux-devtool 打出来的更新后的store，content里面是要渲染的数据

**系统信息**
Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-less: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/redux: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/redux-h5: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5
      nervjs: ^1.3.9 => 1.3.13
    npmGlobalPackages:
      typescript: 3.4.5

**Comment by Chen-jj** [comment]
@ShaneLuo97 哪个平台？

**Comment by ShaneLuo97** [comment]
@Chen-jj 小程序

**Comment by luckyadam** [comment]
升级到 1.3.0-beta.6 试试

**Comment by Chen-jj** [comment]
@ShaneLuo97 复现不了，建议更新 CLI 和依赖到最新版本再试试，再检查一下业务代码，或者在 dist/npm/@tarojs/redux/dist/index.js 的 listener 里打断点 debug 一下。

**Comment by sillyhong** [comment]
遇到了同样的问题，store状态已经更新，但是组件里面使用this.props.xxx 获取不到数据

**Comment by Chen-jj** [comment]
@sillyhong  Taro 版本多少？

**Comment by sillyhong** [comment]
@Chen-jj  1.3.0

**Comment by Chen-jj** [comment]
@sillyhong 提供下代码吧。

**Comment by sillyhong** [comment]
@Chen-jj 问题解决了，是自己写的业务代码有问题
