### ISSUE TITLE
RN下，store中通过import引入reducer，不会被编译到.rn_temp当中

### ISSUE THREAD

**Issue by lingxiao-Zhu** [NervJS/taro#3270]
**问题描述**
RN下的redux，在store文件中引入reducer，通过import的方式，当编译到.rn_temp文件夹下，会丢失当行代码。

**复现步骤**
```js
import { createStore, applyMiddleware, compose, combineReducers } from "redux";
import orderConfirm from "../pages/orderConfirm/reducer";

const rootReducer = combineReducers({
  orderConfirm
});
```

**期望行为**
正常运行

**报错信息**
orderConfirm is not defined

// 下面这行代码会消失
import orderConfirm from "../pages/orderConfirm/reducer";

**系统信息**
 - 操作系统: [macos 10.13.6]
 - Taro 版本 [1.3.0-beta.5]
 - Node.js 版本 [v9.0.0]
 - 报错平台 [rn]

**补充信息**
目前可以通过require的方式引入，不会报错

 const orderConfirm = require("../pages/orderConfirm/reducer").default;

**Comment by Pines-Cheng** [comment]
https://github.com/NervJS/taro/pull/3147
