### ISSUE TITLE
[RN]app.js中的render方法不支持使用条件判断

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#3274]
**问题描述**
类似 `if (process.env.TARO_ENV === 'rn')` 这样的判断在render中使用是无效的。

![image](https://user-images.githubusercontent.com/13899502/58742841-4b317900-8459-11e9-8c7f-5e58428c5b76.png)

现在我们要接入 https://github.com/ant-design/ant-design-mobile-rn 必须用 Provider 包裹一层。。。

**期望行为**
能自定义

**系统信息**
```
👽 Taro v1.3.0-beta.5


  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by tourze** [comment]
https://rn.mobile.ant.design/index-cn https://github.com/rilyu/teaset 都不行

**Comment by Pines-Cheng** [comment]
无效是什么意思？能贴一下编译后的代码吗？

**Comment by Pines-Cheng** [comment]
我这边测试没问题啊。

**Comment by tourze** [comment]
> 我这边测试没问题啊。
> ![image](https://user-images.githubusercontent.com/9441951/58759184-7f3f9380-8558-11e9-86a0-d4af4b7b5f18.png)

是指app.js这个文件编译后的代码。类似 @ant-design/react-native 这个类库，如果要用modal那些组件，必须在最外层加一个Provider。你可以参考我截图的代码，看看 `.rn_temp/app.js` 这个文件的生成是否符合预期。

**Comment by Pines-Cheng** [comment]
代码编译的时候会对 appjs 进行处理，所以还是不建议在 appjs 中写逻辑。
