### ISSUE TITLE
template 中引用的组件不被编绎，只被当做标签

### ISSUE THREAD

**Issue by febobo** [NervJS/taro#3276]
**问题描述**
template 中引用的组件不被编绎，只被当做普通标签

**复现步骤**
[复现问题的步骤]
```
<template name="WxParse">
  <AComponent /> // 这个组件只被当成标签使用
</template>
```

[或者可以直接贴源代码，能贴文字就不要截图]

```js


// 这里可以贴代码

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
template 中能使用Taro定义的组件

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
什么样的情况你一定要使用 Template

**Comment by febobo** [comment]
@yuche wxparse中引用的内容太多地方需要用到， 所以需要剥离成组件

**Comment by yuche** [comment]
那我建议你通过 taro convert 把 wxparse 转化为 taro 组件再进行使用

**Comment by febobo** [comment]
@yuche 好的， 了解了， 感谢

**Comment by febobo** [comment]
@yuche 有一个疑问，像咱们这种常用的组件为什么不在底层提供多端支持呢
