### ISSUE TITLE
[bug] taro-init(1) does not exist

### ISSUE THREAD

**Issue by liuzhuan** [NervJS/taro#328]
**问题描述**

在 macOS 上使用 yarn 全局安装 taro，运行 `taro init myApp`，报错：

```sh
👽 Taro v0.0.69

  taro-init(1) does not exist, try --help
```

**复现步骤**

1. 全局安装 taro `yarn global add @tarojs/cli`

```sh
yarn global v0.15.1
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed @tarojs/cli@0.0.69 with binaries:
      - taro
✨  Done in 26.50s.
```
2. 创建空白文件夹 `mkdir -p taro-in-action`
3. 进入文件夹 `cd taro-in-action`
4. 创建 taro 工程模板 `taro init myApp`

**期望行为**

正常创建 Taro 项目模板。

**报错信息**

```sh
👽 Taro v0.0.69

  taro-init(1) does not exist, try --help
```

**系统信息**

 - 操作系统: macOS High Sierra 10.13.5
 - Taro 版本: v0.0.69
 - Node.js 版本: v9.3.0

**Comment by Pines-Cheng** [comment]
重新安装一下 `@tarojs/cli` 试试？

**Comment by liuzhuan** [comment]
@Pines-Cheng 

重新安装了 v0.0.70 ，就可以了。

感谢～
