### ISSUE TITLE
请问何时可以支持离屏画布渲染?

### ISSUE THREAD

**Issue by minzojian** [NervJS/taro#3281]
小程序2.7版已经支持通过[wx.createOffscreenCanvas()](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/wx.createOffscreenCanvas.html)创建离屏画布了.
想知道taro什么时候能同步更新这个功能呢?
~~或者在taro还没有开始支持之前,有没有什么办法直接调wx.createOffscreenCanvas.然后再接合现有的context的相关API去使用~~
谢谢

**Comment by Garfield550** [comment]
> 而对于微信小程序中没有，而某些小程序平台特有的 API，可以先尝试用 Taro. + API 名称来进行调用，如果出现未定义，则使用对应小程序平台的命名空间（如 my、swan、tt 等）来进行调用，并反馈给我们。

https://nervjs.github.io/taro/docs/apis/about/desc.html

**Comment by Forrest-joker** [comment]
![image](https://user-images.githubusercontent.com/26075716/118115267-4f26ed80-b41b-11eb-9e1f-4d91b62d9fb7.png)
恶心到吐的文档，既然要做就请做好！！

**Comment by Chen-jj** [comment]
@Forrest-joker 

首先，这是一个**免费的开源项目**，维护人员都有各自的本职工作。

如果觉得哪里做得不好，可以**礼貌地**提出意见，也可以参与共建，文档下方就有编辑按钮。

缺乏**尊重**和**开源精神**的言论，我们不会接纳。
