### ISSUE TITLE
使用hooks开发组件，React.forwardRef暴露子组件失败，父组件无法使用 ref

### ISSUE THREAD

**Issue by YDMua** [NervJS/taro#3283]
**问题描述**
用hooks开发子组件，使用React.forwardRef暴露子组件，但是父组件用ref去引用子组件的会报错，是否是taro未做React.forwardRef的处理；

**复现步骤**
[复现问题的步骤]
1. 开发子组件 Template, 暴露子组件export default React.forwardRef(Template)
2. 子组件有个openDialog方法
3. 父组件引用子组件<Template ref='Template'>
4. 父组件调用子组件的方法：this.refs.Template.openDialog()

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
使用hooks开发组件，父组件能够使用ref直接调用其内部的方法

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
```
thirdScriptError sdk uncaught third Error module "npm/react/cjs/react.development.js" is not defined
Error: module "npm/react/cjs/react.development.js" is not defined
``` 
**系统信息**
> Taro v1.3.0-beta.5

 - 操作系统: [e.g. macOs Mojave 10.14.5]
 - Taro 版本 [e.g. v.1.3.0-beta.5]
 - Node.js 版本 [e.g. v10.13.0]
 - 报错平台 [weapp]

**Comment by yuche** [comment]
目前小程序容器的提供的接口很难访问到 slot 的内容，可能这个特性要列在比较滞后的排期了。

**Comment by MingNeo** [comment]
+ 1，文档上标注下吧。用hooks重构完一个组件发现有这问题。修改起来太麻烦了。

**Comment by forconz** [comment]
React.forwardRef 如何变通实现？

**Comment by forconz** [comment]
```
import Nerv from 'nervjs';
// export const ReactConfetti = React.forwardRef<Ref, Props>((props, ref) => (
export const ReactConfetti = Nerv.forwardRef<Ref, Props>((props, ref) => (
  <ReactConfettiInternal canvasRef={ref} {...props} />
))
```

这个我测试了没问题

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
