### ISSUE TITLE
H5 page 页下拉刷新组件, 导致页面内的 position:fixed 元素失效的问题

### ISSUE THREAD

**Issue by qianzhaoy** [NervJS/taro#3285]
`PullDownRefresh`组件有 `transform` , 在他里面的子组件有 固定定位的元素的话, 会无法基于浏览器视口做定位. 而变成基于 `PullDownRefresh` 组件定位, 导致弹窗定位错误

**Comment by Xyspeaker** [comment]
出现同样问题固定定位position:fixed:会失效，去掉onPullDownRefresh 显示效果正常

**Comment by guxingke201** [comment]
顶一下

**Comment by guxingke201** [comment]
@qianzhaoy @Xyspeaker h5下能看到这个动画吗：
![image](https://user-images.githubusercontent.com/8326941/58938955-970d5680-87a8-11e9-9518-617317d73a1f.png)

**Comment by guxingke201** [comment]
试过createPortal，会有异常

**Comment by qianzhaoy** [comment]
@guxingke201 没有吧

**Comment by guxingke201** [comment]
> @guxingke201 没有吧

h5没有动画，那h5下要自己弄个动画吗？
那应该是bug吧...没空去看源码修改，坐等修复

**Comment by purocean** [comment]
@guxingke201 是报 Nerv 找不到吗？

我把 Nerv 导出给全局就可以了

```js
import Nerv, { createPortal } from 'nervjs'
window['Nerv'] = Nerv
```

**Comment by guxingke201** [comment]
不记得了，[后面提了一个pr](https://github.com/NervJS/taro/pull/3958)，不知道为啥一直没合并

**Comment by ItxiaoDz** [comment]
> `PullDownRefresh`组件有 `transform` , 在他里面的子组件有 固定定位的元素的话, 会无法基于浏览器视口做定位. 而变成基于 `PullDownRefresh` 组件定位, 导致弹窗定位错误

这个问题可以通过覆盖样式解决
.rmc-pull-to-refresh-transition {
  transform: none !important;
}

**Comment by AlertConsole** [comment]
> > `PullDownRefresh`组件有 `transform` , 在他里面的子组件有 固定定位的元素的话, 会无法基于浏览器视口做定位. 而变成基于 `PullDownRefresh` 组件定位, 导致弹窗定位错误
> 
> 这个问题可以通过覆盖样式解决
> .rmc-pull-to-refresh-transition {
> transform: none !important;
> }

完美解决了我目前遇到的问题。改了好多东西没想到最后这么容易解决了。非常感谢

**Comment by MingBuGaiJue** [comment]
taro 3.2无效
