### ISSUE TITLE
转h5，手动添加导航栏，pages/index页面重复显示

### ISSUE THREAD

**Issue by sprout-echo** [NervJS/taro#3286]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
转为h5，将.taro-tabbar__tabbar小程序的页面导航隐藏，手写一个导航栏，点击跳转到其他页面，再点击导航栏的首页 router.push('/index')的时候首页的内容会重复显示，重复上述操作，首页的内容也会相应的重复显示
**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/17763943/58774083-6c799d00-85f2-11e9-8e10-6f74271cf013.png)
如上图：点击测试tab页，再点击首页，发现首页的内容被重复显示了

[或者可以直接贴源代码，能贴文字就不要截图]

```js

onRoute = active => {
    switch (active) {
      case 1:
        router.switchTab('/index');
        break;
      case 2:
        router.push('/evaluation/index');
        break;
      case 3:
        router.push('/professor/index');
        break;
      case 4:
        router.push('/news/index');
        break;
      default:
        break;
    }
  };

// ```js
// 上面是封装header组件里的路由跳转的代码
// ```
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [1.3.0-beta.2]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
升级到最新的 beta 版本试试呢

**Comment by sprout-echo** [comment]
> 升级到最新的 beta 版本试试呢

升级到1.3.0-beta.6之后 还是会有上面的问题，苦恼

**Comment by sprout-echo** [comment]
用router.replace就可以了
