### ISSUE TITLE
h5中swiper组件中使用map函数输出swiperItem时，多个图片挤到一个屏幕内

### ISSUE THREAD

**Issue by NotMeIsMe** [NervJS/taro#3294]
**问题描述**
图片从服务器异步取回后，通过.map()函数，在swiper组件内循环输出返回多个swiperItem组件。但是显示在屏幕中，多个图片挤到了一起。

**复现步骤**
```js
<Swiper className='index_swiper' interval='2000' circular autoplay>
  {
    swiperData.map((item) => {
      return (
        <SwiperItem key={item.id}>
          <View onClick={this.toItemNotice.bind(this, item.file_id)}>
            <Image src={item.image_url} mode='widthFix' className='swiper_image'></Image>
          </View>
        </SwiperItem>
      )
    })
  }
</Swiper>
```

**期望行为**
通过直接写多个swiperItem，固定网址的方式，宽度是没有问题。希望跟这个一样。

**报错信息**
![image](https://user-images.githubusercontent.com/25151331/58784299-a27c4880-8615-11e9-88b8-9a21f07ce2c9.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0]
 - Node.js 版本 [e.g. v8.9.3]
 - 报错平台 [h5]

**补充信息**
[可选]
是否是不支持map函数方式return回来？

**Comment by jinjinjin0731** [comment]
swiperData.length &&  swiperData.map 这样写吧。 加个判断。

**Comment by NotMeIsMe** [comment]
我试过很多方法了，都不行。现在暂时用着写死的方法，手写多个swiperItem，固定图片地址。

**Comment by jinjinjin0731** [comment]
```jsx
swiperData.length && <Swiper className='index_swiper' interval='2000' circular autoplay>
  {
    swiperData.map((item) => {
      return (
        <SwiperItem key={item.id}>
          <View onClick={this.toItemNotice.bind(this, item.file_id)}>
            <Image src={item.image_url} mode='widthFix' className='swiper_image'></Image>
          </View>
        </SwiperItem>
      )
    })
  }
</Swiper>
```    
这样也不行？

**Comment by so-diao** [comment]
可以等数据返回了再渲染`Swiper`
```js
{
    length && <Swiper><Swiper/>
}
```

**Comment by NotMeIsMe** [comment]
我直接声明一个有数据的swiperData的数组，用map的方式输出，也不行。只有写死才可以。。

**Comment by jinjinjin0731** [comment]
不应该啊。 贴一下你的 taro 版本。 1.3 的哪个 beta . 然后贴一下复现的代码片段。 你贴的这个我这里完全 ok

**Comment by NotMeIsMe** [comment]
低版本我是可以的，升级高版本之后才出现这个问题。但是不升级，感觉后面也有一些功能用不了，所以今天想解决一下这个问题。

**Comment by jinjinjin0731** [comment]
贴一下你的  package.json 的相关版本信息。  还有你的 cli 具体的版本信息

**Comment by NotMeIsMe** [comment]
![image](https://user-images.githubusercontent.com/25151331/58791503-e9be0580-8624-11e9-9ba0-95e1fb1b8837.png)

**Comment by NotMeIsMe** [comment]
![image](https://user-images.githubusercontent.com/25151331/58791602-170ab380-8625-11e9-98ae-e57dea67e2fb.png)

**Comment by NotMeIsMe** [comment]
之前用的是1.2.22版本，轮播图是正常的

**Comment by jinjinjin0731** [comment]
nervjs 这个版本升级到 1.4.0-beta.5 试一下

**Comment by NotMeIsMe** [comment]
升级还是不行

**Comment by jinjinjin0731** [comment]
@NotMeIsMe  我这边怎样复现？ 可以提供下你的复现代码吗？ 上面的那个我没有复现。
