### ISSUE TITLE
小程序成功运行，但是到了H5就会报错，class和className的兼容问题、map不支持、Navigator不支持

### ISSUE THREAD

**Issue by AlicePrincess** [NervJS/taro#33]
首先是
![image](https://user-images.githubusercontent.com/18545458/41141607-3868844c-6b25-11e8-8cf9-1eb32ebb3c41.png)
![image](https://user-images.githubusercontent.com/18545458/41141617-40e54e3e-6b25-11e8-81f2-696895da76fa.png)
后来把map删了
![image](https://user-images.githubusercontent.com/18545458/41141637-5e990736-6b25-11e8-828d-8beb582d65ea.png)
![image](https://user-images.githubusercontent.com/18545458/41141641-63266f64-6b25-11e8-9ef4-199995634187.png)
最后把Navigator替换成了View
![image](https://user-images.githubusercontent.com/18545458/41141673-87a46166-6b25-11e8-8873-892c6633bf26.png)
![image](https://user-images.githubusercontent.com/18545458/41141688-90cc45e2-6b25-11e8-855d-770b3e906d07.png)
一路的不顺利，但是小程序中都是好的
不知道是不是代码哪边需要设置兼容性？

**Comment by yuche** [comment]
先引用 `Navigator` 再使用。

另外，你循环的 callee 错了，应该是 `this.state.numbers`，建议先看看文档，也可以参考 demo：
https://github.com/NervJS/taro-todo
