### ISSUE TITLE
这依赖报错什么原因，为什么会在if条件多了in？

### ISSUE THREAD

**Issue by caiyongqiang** [NervJS/taro#3306]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)
![image](https://user-images.githubusercontent.com/31945098/58857245-5691d800-86d7-11e9-8639-e3b722cfb166.png)

![image](https://user-images.githubusercontent.com/31945098/58857326-880aa380-86d7-11e9-8525-b656a132223b.png)

**Comment by luckyadam** [comment]
cli 和项目依赖版本保持一致

**Comment by caiyongqiang** [comment]
是的，谢谢


------------------ 原始邮件 ------------------
发件人: "Li,Weitao"<notifications@github.com>;
发送时间: 2019年6月4日(星期二) 下午5:13
收件人: "NervJS/taro"<taro@noreply.github.com>;
抄送: "蔡永强"<1324019229@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NervJS/taro] 这依赖报错什么原因，为什么会在if条件多了in？ (#3306)




cli 和项目依赖版本保持一致
