### ISSUE TITLE
微信编译的npm文件夹taro-ui中好像缺少文件 

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#3309]
**问题描述**
![image](https://user-images.githubusercontent.com/34000909/58861757-aa092380-86e1-11e9-8071-d9f7c57f5c1e.png)
微信编译的npm文件夹taro-ui中好像缺少文件 导致一下问题
![image](https://user-images.githubusercontent.com/34000909/58861800-c4430180-86e1-11e9-83a4-c221b23ebffc.png)

h5编译没有问题

**系统信息**
 - 操作系统: Windows 10
 - Taro 版本1.3.0-beta.6
 - Node.js 版本 10.14.1
 - 报错平台 weapp

**Comment by guggit** [comment]
![image](https://user-images.githubusercontent.com/34000909/58862663-c4440100-86e3-11e9-9211-052983a5d212.png)
打包出现这个问题

**Comment by guggit** [comment]
@luckyadam

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/58866769-daee5600-86eb-11e9-9887-18c7a093a6fc.png)
这是什么文件？

最好整理一个可以复现问题的 demo 看看

**Comment by guggit** [comment]
@luckyadam  上一个问题是我这边写法有点问题，大佬，微信小程序编译后生成这样的语句对吗？
![image](https://user-images.githubusercontent.com/34000909/58925667-e50b6580-877a-11e9-867b-f72774921c9d.png)

**Comment by guggit** [comment]
小程序运行的时候提示我React undefined

**Comment by luckyadam** [comment]
> @luckyadam 上一个问题是我这边写法有点问题，大佬，微信小程序编译后生成这样的语句对吗？
> ![image](https://user-images.githubusercontent.com/34000909/58925667-e50b6580-877a-11e9-867b-f72774921c9d.png)

不对，贴一下这个文件的代码
