### ISSUE TITLE
支付宝小程序直接进入某个页面，url带有query参数，但是this.$router.params为空对象

### ISSUE THREAD

**Issue by hjc22** [NervJS/taro#3313]
支付宝小程序如果直接进入某个页面（比如通过编译模式进入），url带有query参数，但是页面的this.$router.params为空对象，App的this.$router.params能拿到query，这是支付宝官方本身就存在的问题，直接进入某个页面，onload拿不到options，正常切换页面无此问题，希望taro能解决这个问题，taro可以拿App的query 和页面的query去进行合并，让页面的this.$router.params能正常获取。

**Comment by Chen-jj** [comment]
#2085

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/58936671-ddf84d80-87a2-11e9-987a-0df43efd4ca1.png)
我去提个文档修改

**Comment by Chen-jj** [comment]
@Garfield550 支付宝侧由框架来 merge 到页面的 $router.params 吧，这位老哥说得对，统一用法比较好。

**Comment by Garfield550** [comment]
> @Garfield550 支付宝侧由框架来 merge 到页面的 $router.params 吧，这位老哥说得对，统一用法比较好。

好的 👌
