### ISSUE TITLE
weapp模式 config文件配置plugins的sass部分中的data属性 不生效

### ISSUE THREAD

**Issue by wjeek** [NervJS/taro#3314]
**问题描述**
我在项目中试着去实现scss文件全局变量的自动注入
发现通过修改taro-plugin-sass可以达到这个目的
但是我的变量是通过js模版字符串注入到data上，data会被默认配置覆盖

**复现步骤**
[复现问题的步骤]
```js
const version = 1234
const config = {
 plugins: {
  sass: {
    data: `\$version: ${version};`,
  },
 }
}
```
[这部分源码说明data在config中配置无效](https://github.com/NervJS/taro/blob/e425b57ce5bc2379e3d8a5c3575d7d31b9fb0ef7/packages/taro-plugin-sass/index.js)

**期望行为**
可以通过data的方式设置sass全局变量

**报错信息**
在某个sass文件中会报
Error: Undefined variable: "$version".

**系统信息**

 - 操作系统: [mac]
 - Taro 版本 [v.1.2.23]
 - Node.js 版本 [e.g. v8.12.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
你升级到 1.2.26 或者最新版本试试

**Comment by wjeek** [comment]
> 你升级到 1.2.26 或者最新版本试试

刚才看那段源码好像就是最新版的吧 config里的data会被后边Object.assign覆盖

**Comment by luckyadam** [comment]
4bf27b2c1b5814f22d8fd39a611eb1f940ed7851  已解决
