### ISSUE TITLE
Taro1.3.0 beta.6下，使用useReducer时，value为布尔值时，值失效

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro#3316]
![image](https://user-images.githubusercontent.com/15973148/58925545-8219ce80-877a-11e9-94fa-1c16b59c98cd.png)
![image](https://user-images.githubusercontent.com/15973148/58925548-88a84600-877a-11e9-87a3-8375bcb059a9.png)
初始化fetching为true，但是Button没有设置为disabled的状态

**Comment by yuche** [comment]
你把 state 换个名字试试

**Comment by JasonJie** [comment]
> 你把 state 换个名字试试

state还个值就好了。

**Comment by yuche** [comment]
以后你发 issue，记得按标准发。下次再这样我直接关掉了
