### ISSUE TITLE
微信小程序运行报错，不知道为什么编译器生成的代码有React关键字

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#3319]
**问题描述**
![image](https://user-images.githubusercontent.com/34000909/58927605-d1173200-8781-11e9-84e5-77219e41190b.png)
微信小程序运行报错，不知道为什么编译器生成的代码有React关键字
![image](https://user-images.githubusercontent.com/34000909/58927693-30754200-8782-11e9-90fc-dca11c5970ea.png)

**复现步骤**
无

**系统信息**
 - 操作系统: Windows 10
 - Taro 版本 1.3.0-beta.6
 - Node.js 版本 10.14.1
 - 报错平台 [weapp]

**Comment by yuche** [comment]
看下你源码是怎么写的，是不是写成 div 了

**Comment by guggit** [comment]
> 看下你源码是怎么写的，是不是写成 div 了

是div,除了div的情况还有什么情况会生成React.createElement这种写法？

**Comment by yuche** [comment]
先贴你源码出来

**Comment by guggit** [comment]
> 先贴你源码出来

![image](https://user-images.githubusercontent.com/34000909/58934635-9f13c900-879d-11e9-8864-a8ec442a61cd.png)
![image](https://user-images.githubusercontent.com/34000909/58934646-aa66f480-879d-11e9-944c-4913cd74014b.png)

**Comment by yuche** [comment]
render 方法现在还不能继承
