### ISSUE TITLE
编译成H5出现部分元素被rmc-pull-to-refresh-content-wrapper导致下拉显示不全

### ISSUE THREAD

**Issue by GYDSB** [NervJS/taro#3320]

**Comment by GYDSB** [comment]
Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: 1.3.13 => 1.3.13

**Comment by GYDSB** [comment]
破案-页面书写了onPullDownRefresh导致页面中多个元素出现 被包裹rm-pull-to-refresh 类-。-不过一般来说，页面只会对page包裹么，但是使用后发现不仅是根元素，被map列表渲染对元素也被该类包裹了

**Comment by Littly** [comment]
https://github.com/NervJS/taro/commit/7e48537d3184e4c86e45e7b1670ffabc623e1a37
是有过这个问题.. 更新到1.3.0-beta.8可以修复..
