### ISSUE TITLE
cli生成的项目父组件无法像子组件传值,更换成旧项目的依赖就可以了，具体原因不明.

### ISSUE THREAD

**Issue by adsjkqhaoran** [NervJS/taro#3322]
**问题描述**
cli生成的项目父组件无法像子组件传值,更换成旧项目的依赖就可以了，具体原因不明.

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/8953281/58928542-797ac580-8785-11e9-9b34-f1a51047e30a.png)
![image](https://user-images.githubusercontent.com/8953281/58928560-8697b480-8785-11e9-955a-8c3b778d9bbb.png)
使用cli生成的项目父组件无法向子组件传值
![image](https://user-images.githubusercontent.com/8953281/58928371-d75add80-8784-11e9-9f74-083c712594cb.png)
左边的依赖父组件无法像子组件传值,右边的可以。。。。

```js
// 不能正常使用的那份依赖 
{
  "name": "card",
  "version": "1.0.0",
  "private": true,
  "description": "card",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "^1.2.0",
    "@tarojs/redux": "^1.3.0-beta.6",
    "@tarojs/router": "^1.2.0",
    "@tarojs/taro": "^1.2.0",
    "@tarojs/taro-alipay": "^1.2.0",
    "@tarojs/taro-h5": "^1.2.0",
    "@tarojs/taro-swan": "^1.2.0",
    "@tarojs/taro-tt": "^1.2.0",
    "@tarojs/taro-weapp": "^1.3.0-beta.6",
    "dva-core": "^1.4.0",
    "dva-loading": "^3.0.4",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "redux-logger": "^3.0.6",
    "taro-ui": "^2.1.0"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "^1.2.0",
    "@tarojs/plugin-csso": "^1.2.0",
    "@tarojs/plugin-sass": "^1.2.0",
    "@tarojs/plugin-uglifyjs": "^1.2.0",
    "@tarojs/webpack-runner": "^1.2.0",
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^1.2.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-taro": "^1.2.0"
  }
}
```

**期望行为**
希望知道是哪个包的问题。。不然每次我都用老项目的依赖了。

**报错信息**
毛报错，很坑

**系统信息**
不能传值的信息
  Taro CLI 1.2.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.8.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 5.4.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^1.2.0 => 1.2.26 
      @tarojs/plugin-babel: ^1.2.0 => 1.2.26 
      @tarojs/plugin-csso: ^1.2.0 => 1.2.26 
      @tarojs/plugin-sass: ^1.2.0 => 1.2.26 
      @tarojs/plugin-uglifyjs: ^1.2.0 => 1.2.26 
      @tarojs/redux: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/router: ^1.2.0 => 1.2.26 
      @tarojs/taro: ^1.2.0 => 1.2.26 
      @tarojs/taro-alipay: ^1.2.0 => 1.2.26 
      @tarojs/taro-h5: ^1.2.0 => 1.2.26 
      @tarojs/taro-swan: ^1.2.0 => 1.2.26 
      @tarojs/taro-weapp: ^1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/webpack-runner: ^1.2.0 => 1.2.26 
      eslint-config-taro: ^1.2.0 => 1.2.26 
      eslint-plugin-taro: ^1.2.0 => 1.2.26

**Comment by yuche** [comment]
@tarojs/taro 也要升级

**Comment by adsjkqhaoran** [comment]
> @ tarojs / taro也要升级

是升1.3？

**Comment by Garfield550** [comment]
Taro 的各个包目前需要统一版本，所以如果有个包升级了 1.3 其他所有包也要升级 1.3。

**Comment by adsjkqhaoran** [comment]
> Taro 的各个包目前需要统一版本，所以如果有个包升级了 1.3 其他所有包也要升级 1.3。

谢谢 我旧的确实全用的是1.2 但是他这么什么错都不报一下实在让人蛋疼呀！

**Comment by Garfield550** [comment]
> > Taro 的各个包目前需要统一版本，所以如果有个包升级了 1.3 其他所有包也要升级 1.3。
> 
> 谢谢 我旧的确实全用的是1.2 但是他这么什么错都不报一下实在让人蛋疼呀！

你写的是 ^1.2.0 `^` 这个符号，会匹配 1.2.x 的所有版本，yarn 或者 npm 安装/更新 的时候就自动给你装上了 1.2.26
