### ISSUE TITLE
taro全局安装以后 taro不能识别指令

### ISSUE THREAD

**Issue by wangdan3024** [NervJS/taro#3323]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)
**问题描述**
[问题描述：taro全局安装以后 taro不能识别指令

**复现步骤**
[复现问题的步骤]
1，使用npm 安装taro 安装成功以后使用taro报不是内部或外部指令
2，改用yarn安装出现同样的问题
3，两种方法安装然后taro -V 都是taro不是内部或外部指令
4，使用 npm info taro 可以看到版本信息

[或者可以直接贴源代码，能贴文字就不要截图]

```js


// 这里可以贴代码

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。
```

**期望行为**
希望告诉怎么解决

**报错信息**
taro不是内部或外部命令

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.7]
 - Node.js 版本 [e.g. v10.16.0]
 - 报错平台 [命令行工具]

**补充信息**
[可选]

**Comment by Garfield550** [comment]
Dup #699

**Comment by wangdan3024** [comment]
> Dup #699

最开始我就是用的npm安装的然后安装出现问题以后再用yarn安装的然后出现了同一个问题

**Comment by Garfield550** [comment]
> > Dup #699
> 
> 最开始我就是用的npm安装的然后安装出现问题以后再用yarn安装的然后出现了同一个问题

这可能是 Vendor 级的问题，你再等等吧。先用 `npx @tarojs/cli init` 吧。

**Comment by wangdan3024** [comment]
> > > Dup #699
> > 
> > 
> > 最开始我就是用的npm安装的然后安装出现问题以后再用yarn安装的然后出现了同一个问题
> 
> 这可能是 Vendor 级的问题，你再等等吧。先用 `npx @tarojs/cli init` 吧。

我先试试看行不行 连taro-V都报错简直让人崩溃

**Comment by StephenOo** [comment]
遇到了同样的问题，请问如何解决的

**Comment by wangdan3024** [comment]
其实具体原因也没找出来 只知道是依赖问题，所以从同事那边拷贝了依赖配置文件 然后在安装才解决
