### ISSUE TITLE
原生小程序 编译成 taro 样式问题

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#3324]
![image](https://user-images.githubusercontent.com/25219300/58930945-3d009700-8790-11e9-9c44-cb947a7348be.png)

在 src 文件夹里面写的 是 sass，发现在生成的 dist 目录下面没有样式文件。

![image](https://user-images.githubusercontent.com/25219300/58930991-6de0cc00-8790-11e9-89f5-65c27e386e09.png)

### 想请教一下：如何在 config/index.js 里面配置，让 src 里面所有的 sass 都编译一遍。有案例最好。阿里嘎多

**Comment by patchBig** [comment]
@luckyadam @yuche Hello  这个有什么好的解决办法吗？

**Comment by luckyadam** [comment]
后缀改成 scss 试试

**Comment by patchBig** [comment]
改过了，然后因为里面的样式嵌套写法，导致编译报错了。。。

**Comment by patchBig** [comment]
> 后缀改成 scss 试试

改过了，然后因为里面的样式嵌套写法，导致编译报错了。。。
