### ISSUE TITLE
import 动态引用js文件

### ISSUE THREAD

**Issue by hbxks18** [NervJS/taro#3327]
**问题描述**
使用trao搭建了一套基于mobx的模板，由于每个store文件都需要在app.js里引用，所以想实现动态引用，即事先配置好路由文件，包括store文件的文件所在位置。

方案一：
使用import('../xx.js')来进行加载，并且在plugins里配置'syntax-dynamic-import'。
表现：trao编译通过，但是小程序里报错Unexpected token import。

方案二：
使用require(../xx.js')来进行加载。
表现：当路径是变量，trao报错TypeError: Path must be a string. Received undefined，当路径是字符串时，则编译通过。（ps: 原生小程序里，require支持动态引用）

**复现步骤**
```js
// 方案一代码
const createStores = (router) => {
    router.forEach(({ path, defaultStore = 'store' }) => {
        const _path = '@/pages'+ path +'/' + defaultStore + ''
        import(_path).then(res => {
            console.log(res);
        })
    });
}
// babel配置文件
  plugins: {
    babel: {
      sourceMap: true,
      presets: [
        'env',
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread',
        'syntax-dynamic-import'
      ]
    }
  },

// 方案二
const createStores = (router) => {
    const stores = {};
    router.forEach(({ path, defaultStore = 'store' }) => {
        const _path = '@/pages'+ path +'/' + defaultStore + ''
        const store = require(_path);
        const name = store.default.constructor['__props'];
        stores[name] = store.default;
    });
    return stores;
}
```

**期望行为**
方案一：import应该被编译成相应的require
方案二：require应该跟小程序原生表现一致，支持动态引用

**报错信息**
方案一：
![image](https://user-images.githubusercontent.com/23228604/58937918-58769c80-87a6-11e9-8aa1-d8db44ca52d0.png)
方案二：
![image](https://user-images.githubusercontent.com/23228604/58937981-7e03a600-87a6-11e9-9749-1d7f3375ba0e.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.2.21
  Taro CLI 1.2.21 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/components: ^1.2.2 => 1.2.21
      @tarojs/mobx: ^1.2.2 => 1.2.21
      @tarojs/mobx-h5: ^1.2.2 => 1.2.21
      @tarojs/mobx-rn: ^1.2.2 => 1.2.21
      @tarojs/plugin-babel: ^1.2.2 => 1.2.21
      @tarojs/plugin-csso: ^1.2.2 => 1.2.21
      @tarojs/plugin-sass: ^1.2.2 => 1.2.21
      @tarojs/plugin-uglifyjs: ^1.2.2 => 1.2.21
      @tarojs/rn-runner: ^1.2.2 => 1.2.21
      @tarojs/router: ^1.2.2 => 1.2.21
      @tarojs/taro: ^1.2.2 => 1.2.21
      @tarojs/taro-alipay: ^1.2.2 => 1.2.21
      @tarojs/taro-h5: ^1.2.2 => 1.2.21
      @tarojs/taro-swan: ^1.2.2 => 1.2.21
      @tarojs/taro-tt: ^1.2.2 => 1.2.21
      @tarojs/taro-weapp: ^1.2.2 => 1.2.21
      @tarojs/webpack-runner: ^1.2.2 => 1.2.21
      eslint-config-taro: ^1.2.2 => 1.2.21
      eslint-plugin-taro: ^1.2.2 => 1.2.21
      nervjs: ^1.3.9 => 1.3.13

**Comment by Garfield550** [comment]
目前暂时不支持，等官方后续更新吧。

**Comment by wuchangming** [comment]
@Garfield550 ，动态 import 目前有没支持的计划？

**Comment by wuchangming** [comment]
taro 3.x 现在能自定义配置webpack plugin。可以通过关闭小程序 webpack 的 code-splitting 解决。
参考：https://github.com/webpack/webpack/issues/3637#issuecomment-429501574

配置方式：
```js
const config = {
  ...
 // 小程序配置
  mini: {
       // 添加自定义插件
        webpackChain(chain, webpack) {
            chain.plugin('limitChunkCountPlugin').use(webpack.optimize.LimitChunkCountPlugin, [
                {
                    maxChunks: 1
                }
            ])
        }
  },
  ...      
}
```

@luckyadam 
不过我觉得这种特性最好内置到taro库中, 这样import() 在小程序端也正常运行，同时不影响h5端使用它进行代码分块。

**Comment by wuchangming** [comment]
提了 PR ：https://github.com/NervJS/taro/issues/3327
