### ISSUE TITLE
构建RN，整合到 taro-native-shell 后无法启动

### ISSUE THREAD

**Issue by xiongcheng1107** [NervJS/taro#3329]
**问题描述**
构建RN，整合到 taro-native-shell 后无法启动

**复现步骤**
1. taro-cli版本1.2.26，node版本10.15.3，yarn版本1.16.0
2. 微信构建正常，H5构建正常
3. RN构建8081端口js代码正常呈现
4. 整合到taro原生 React Native 壳子，react-native run-android启动，端口构建失败，安卓模拟器报错code500
5. 此时终端有提示，部分样式可能会被react native忽略，鉴于js bundle正常呈现，所以暂时没管
5. 另外项目中有使用过taro ui

**期望行为**
模拟器正常渲染呈现页面

**报错信息**
终端报错：

```
error: bundling failed: Error: While trying to resolve module weui from file C:\Users\Administrator\Desktop\taro-native-shell-master\node_modules\@tarojs\components\dist\index.js, the package C:\Users\Administrator\Desktop\taro-native-shell-master\node_modules\weui\package.json was successfully found. However, this package itself specifies a main module field that could not be resolved
```

模拟器报错：

```
the development server returned response error code:500
URL: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false
```

**系统信息**
 - 操作系统: [Windows 7]
 - Taro 版本 [1.2.26]
 - Node.js 版本 [10.15.3]
 - 报错平台 [rn]

**补充信息**
经测试，native官方的组件页面，直接命名为app.js，可正常渲染呈现
将官方组件页面，单独放入taro构建出来的app.js路由中，可正常渲染呈现
然而将taro构建的其他页面放入路由，模拟器直接就是红屏code500

再补充一个整合之后的package.json
```
"dependencies": {
    "@tarojs/components-rn": "^1.2.26",
    "@tarojs/taro-rn": "^1.2.26",
    "@tarojs/taro-router-rn": "^1.2.26",
    "@tarojs/taro-redux-rn": "^1.2.26",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "redux": "^4.0.0",
    "tslib": "^1.8.0",
    "@tarojs/components": "1.2.26",
    "@tarojs/router": "1.2.26",
    "@tarojs/taro": "1.2.26",
    "@tarojs/taro-alipay": "1.2.26",
    "@tarojs/taro-h5": "1.2.26",
    "@tarojs/taro-swan": "1.2.26",
    "@tarojs/taro-tt": "1.2.26",
    "@tarojs/taro-weapp": "1.2.26",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "stylelint": "9.0.0",
    "stylelint-config-taro-rn": "1.2.26",
    "stylelint-taro-rn": "1.2.26"
  },
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "@babel/runtime": "^7.3.4",
    "@commitlint/cli": "^7.5.2",
    "@commitlint/config-conventional": "^7.5.0",
    "babel-jest": "^24.5.0",
    "conventional-changelog-cli": "^2.0.12",
    "husky": "^1.3.1",
    "jest": "^24.5.0",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
```

**Comment by Pines-Cheng** [comment]
taro ui 不支持 RN 端哦。

**Comment by xiongcheng1107** [comment]
> taro ui 不支持 RN 端哦。

嗯，所以在这之前我测试过，把整合后的app.js路由里单独放react native官方的hello world页面，结果可以正常在模拟器中渲染出来，于是可以证明nativa渲染只会考虑app.js和指定的页面。
然后我**用taro构建的另一个没有使用taro ui的页面单独放进路由**，其它页面引入全部备注掉，则还是没有办法正常渲染，报错code500，根据这个状态码大概推测是页面中引入的某个包的问题，有可能是@tarojs/components这个包，上面贴了有终端报错信息。不知道我这个思路对不对。。大佬辛苦啦，麻烦看一下

**Comment by Pines-Cheng** [comment]
为什么终端报错的路径里会有 weui ？

**Comment by xiongcheng1107** [comment]
> 为什么终端报错的路径里会有 weui ？

在Metro Bundler里报的这个，懵逼中

**Comment by Pines-Cheng** [comment]
@tarojs\components 有依赖于 weui，但是 RN 编译怎么会有这个呢？

**Comment by xiongcheng1107** [comment]
> @tarojs\components 有依赖于 weui，但是 RN 编译怎么会有这个呢？

不太懂原理，但执行react-native run-android确实是报了这个。

另外刚刚我注意到package文件里面有@tarojs/components和@tarojs/components-rn 这两个包，但打包出来的rn页面全部引用的@tarojs/components，似乎看着后者更像是对的？

上面我又补充了dependencies和devDependencies，除了第一次编译时报错，也是在这里找到其它人的解决方法，手动装了stylelint，stylelint-config-taro-rn， stylelint-taro-rn，其它的都没动过
