### ISSUE TITLE
引用第三方库路径错误

### ISSUE THREAD

**Issue by zhuxianguo** [NervJS/taro#3331]
**问题描述**
引用第三方库，第三方库又依赖其他的库，本来是绝对路径，自动变成相对路径

**复现步骤**
[复现问题的步骤]
![QQ截图20190605163304](https://user-images.githubusercontent.com/9689585/58942534-85c84800-87b0-11e9-889b-af37989f957e.png)

**期望行为**
期望不要自动变更引用路径

**报错信息**
![QQ截图20190605163331](https://user-images.githubusercontent.com/9689585/58942541-88c33880-87b0-11e9-82b1-8a3f0870af2c.png)

**系统信息**
  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - D:\tools\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by luckyadam** [comment]
Taro 里用不了 rc-components

**Comment by liuwuhaoo** [comment]
发现了类似的错误，是 htmlparse2 这个库。
这个库里有一句 `var decode_codepoint_1 = __importDefault(require("entities/lib/decode_codepoint"));`
但是貌似被解析成相对路径了   
![image](https://user-images.githubusercontent.com/19514172/66632973-4f0dad00-ec3c-11e9-8034-9dc8dd0c902c.png)    
@luckyadam

**Comment by luckyadam** [comment]
> 发现了类似的错误，是 htmlparse2 这个库。
> 这个库里有一句 `var decode_codepoint_1 = __importDefault(require("entities/lib/decode_codepoint"));`
> 但是貌似被解析成相对路径了
> ![image](https://user-images.githubusercontent.com/19514172/66632973-4f0dad00-ec3c-11e9-8034-9dc8dd0c902c.png)
> 这个 entities 是另外一个第三方库，是在 node_modules 目录下面的。
> @luckyadam

htmlparse2 这个库在小程序里用不了
