### ISSUE TITLE
react-native run-android 在模拟器上红屏，真机可以

### ISSUE THREAD

**Issue by yikalosi** [NervJS/taro#3332]
Unable to load script from assets index.android.bundlel.

Make sure your bundle is packaged correctly or you're

running a packager server.

jniloadScriptFromAssets

CatalystInstanceImpl.java

loadscriptFromAssets

catalystInstanceImpl.java:216

1oadscript

JSBundleLoader.java:31

runJSBundle

catalystInstanceImpl.java:234

createReactContext

ReactInstancellanager.java:1114

access$900

ReactInstancellanager.java:113

run

ReactIns tancellanager.java:911

run

Thread.java:841

**Comment by dxhuii** [comment]
@yikalosi 这个问题，你怎么解决的
