### ISSUE TITLE
无法使用MovableView

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#334]
**问题描述**
在项目中有一个手势放大的需求，发现微信小程序中有个组件movable-view是可以比较轻松高效地做到的。taro文档中也说了支持movable-view，可是在实际引用就会报错。

```js
// 这里可以贴代码
<MovableArea>
        <MovableView></MovableView>
</MovableArea>
```

**报错信息**
在编辑器中eslint会报：不支持自定义组件嵌套
保存之后会运行失败
![image](https://user-images.githubusercontent.com/22128204/42763011-68238938-8944-11e8-9b35-f4b6da773d21.png)

**Comment by yuche** [comment]
原因在于 `MovableArea` 和 `MovableVIew` 没有加入到自定义组件列表。晚点发个新版本应该就行了。

**Comment by xingBri** [comment]
请问新版本的发布时间大概是在什么时候呢？ 因为现在项目需求比较急  或者可以告知有没有什么自行解决的办法吗

**Comment by yuche** [comment]
已经发了0.0.70

**Comment by chm1n9** [comment]
@taro/cli 是 0.0.7 但是 components 还是0.0.69

**Comment by xingBri** [comment]
请问怎么能比较方便的更新到0.0.70呢？ 目前还没更新过

**Comment by yuche** [comment]
`taro update self` 和 `taro update project`

**Comment by xingBri** [comment]
更新了 谢谢，这更新体验非常好！ 试了一下发现eslint还是报错 但是编译时没发生错误  是eslint没更新规则吗？ 另外，h5上的navigateBack函数炸了，用不了，尝试用history.go(-1)发现不行，层级会叠起来。
