### ISSUE TITLE
小程序Picker组件，编译有问题

### ISSUE THREAD

**Issue by lingxiao-Zhu** [NervJS/taro#3341]
**问题描述**
小程序Picker组件，编译有问题

**复现步骤**
![image](https://user-images.githubusercontent.com/22609330/59002433-fde04d80-8844-11e9-9721-58c778b6a5a3.png)

![image](https://user-images.githubusercontent.com/22609330/59002437-03d62e80-8845-11e9-93ab-8658e52218f3.png)

**期望行为**
正常运行

**报错信息**
如图

**系统信息**
 - 操作系统: [macos]
 - Taro 版本 [1.3.0-beta6]
 - Node.js 版本 [9.0.0]
 - 报错平台 [weapp]

**补充信息**
失败场景是range是props传递的，pickerValue是组件内部state；
如果两者都是本地state或者props的，就没问题。

**Comment by yuche** [comment]
贴完整的代码，贴文字。
