### ISSUE TITLE
简单的写法，编译失败1.3.0

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#3344]
**问题描述**
![image](https://user-images.githubusercontent.com/34000909/59011981-d8653b00-8868-11e9-8eb2-be69bf8ebed5.png)
编译失败
// ```
import { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

interface IconTextComponentProps {
  json: any;
  data: any;
}

export class IconTextComponent extends Component<IconTextComponentProps, any> {

  renderLeft = () => <View></View>

  renderRight = () => <View></View>

  render() {
    const { json } = this.props, icon = json.icon;

    if (!icon) return <View></View>

    if (json.className === 'dataSource-icon-text2')
      return this.renderLeft();

    if (json.className === 'dataSource-icon-text')
      return <View></View>

    return <View></View>
  }
}

```

**期望行为**
编译成功 或告知问题改变其他写法

 - 操作系统: Windows 10
 - Taro 版本 1.3.0-beta.6
 - Node.js 版本 10.14.1
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/59012269-a6080d80-8869-11e9-92ea-fffca3a716df.png)
代码贴完整点

**Comment by guggit** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/59012269-a6080d80-8869-11e9-92ea-fffca3a716df.png)
> 代码贴完整点

import { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

interface IconTextComponentProps {
  json: any;
  data: any;
}

export default class IconTextComponent extends Component<IconTextComponentProps, any> {

  renderLeft = () => <View></View>

  renderRight = () => <View></View>

  render() {
    const { json } = this.props, icon = json.icon;

    if (!icon) return <View></View>

    if (json.className === 'dataSource-icon-text2')
      return this.renderLeft();

    if (json.className === 'dataSource-icon-text')
      return <View></View>

    return <View></View>
  }
}

**Comment by guggit** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/59012269-a6080d80-8869-11e9-92ea-fffca3a716df.png)
> 代码贴完整点

import { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

interface IconTextComponentProps {
  json: any;
  data: any;
}

export default class IconTextComponent extends Component<IconTextComponentProps, any> {

  renderLeft() {
    return <View></View>
  }

  renderRight() {
    return <View></View>
  }

  render() {
    const { json } = this.props, icon = json.icon;

    if (!icon) return <View></View>

    if (json.className === 'dataSource-icon-text2')
      return this.renderLeft();

    if (json.className === 'dataSource-icon-text')
      return <View></View>

    return <View></View>
  }
}
