### ISSUE TITLE
taro-rn没法用mobx

### ISSUE THREAD

**Issue by yikalosi** [NervJS/taro#3348]
1.taro init myapp
2.选择typescript，mobx，sass

问题：Cannot read property 'counter' of undefined

**Comment by Pines-Cheng** [comment]
taro 及其依赖版本？

**Comment by yikalosi** [comment]
taro版本是1.2.26，项目里面没有改过其他的，选择redux可以成功，mobx就不行

**Comment by Pines-Cheng** [comment]
最新的CLI已 fix ，建议升级一下 CLI。

**Comment by yikalosi** [comment]
升级到beta.8版本可以的
