### ISSUE TITLE
小程序swiper-item无法修改transform

### ISSUE THREAD

**Issue by lichking666** [NervJS/taro#3350]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
业务场景：
![image](https://user-images.githubusercontent.com/34772565/59024579-c5f8fa80-8884-11e9-888d-3a6725ec85d2.png)
需要一个滑动的分类展示，每个item字数不一定，但是间隔一定。然后每次编译之后swiper-item的style里的transform是百分比写法，导致字数不一致时item间隔不一致如下：
![image](https://user-images.githubusercontent.com/34772565/59024695-03f61e80-8885-11e9-9a0b-9db4bf0d12e5.png)
在代码中修改transform失败
 style={`transform: translate(${62 * index}rpx, 0px) translateZ(0px) !important`}

**期望行为**
希望可以选择transform里写百分比还在自定偏移量

 - 操作系统: [e.g. mac os]
 - Taro 版本 [e.g. v.1.2.8]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [ weapp]

**补充信息**
taro编译的时候会把自己写的同名style属性覆盖掉

**Comment by wqj97** [comment]
同样遇到了这个问题

**Comment by smizel** [comment]
我也遇到了这个问题

**Comment by Chen-jj** [comment]
@lichking666 升级到 v1.3.0-beta.6 再试试，还有问题则提供一下完整可复现代码。

**Comment by lichking666** [comment]
> @lichking666 升级到 v1.3.0-beta.6 再试试，还有问题则提供一下完整可复现代码。

升级到v1.3.0-beta.6之后dom不显示了，1.2.8
![image](https://user-images.githubusercontent.com/34772565/59141948-59970c00-89e8-11e9-9bb0-eb75be40b45a.png)
1.3.0-beta.6
![image](https://user-images.githubusercontent.com/34772565/59141960-9e22a780-89e8-11e9-8752-afccffd0abd3.png)
代码：index.tsx
`<Swiper
          className='swiper'
          indicatorColor='#999'
          indicatorActiveColor='#333'
          displayMultipleItems={1}
        >
          <SwiperItem className='swiper_list'>
            <View className='swiper_text_at'>全部</View>
          </SwiperItem >
          <SwiperItem className='swiper_list'>
            <View className='swiper_text'>水果</View>
          </SwiperItem >
          <SwiperItem className='swiper_list'>
            <View className='swiper_text'>蔬菜1</View>
          </SwiperItem >
          <SwiperItem className='swiper_list'>
            <View className='swiper_text'>蔬菜22</View>
          </SwiperItem >
        </Swiper>`


index.scss
`.swiper {
    height: 90px !important;
    line-height: 90px;
    background-color: white;
    margin-bottom: 20px;
  padding-left: 42px;

  &_list {
    height: 90px !important;
    width: auto !important;
    display: inline-block !important;
    position: none !important;
  }

  &_text {
    font-size:28px;
    font-family:PingFang SC;
    font-weight:400;
    color:rgba(50,50,50,1);
    line-height:44px;
    margin-right: 62px;
    height:40px;
  }

  &_text_at {
    font-size:32px;
    font-family:PingFang SC;
    font-weight:800;
    color:rgba(0,0,0,1);
    line-height:44px;
    margin-right: 62px;
    padding-bottom: 26px;
    height:44px;
    border-bottom: 9px solid rgba(255,90,0,1);
  }
}
`

**Comment by Chen-jj** [comment]
@lichking666 

1.3.0-beta.8 可以显示，CLI 和依赖版本要保持一致。

![image](https://user-images.githubusercontent.com/11807297/59175748-39528300-8b89-11e9-98be-48c7d39b3c44.png)

并不是 Taro 把 swiper-item 的 style 在编译时处理了，你看编译后的 wxss 就知道了。而是微信小程序不支持给 swiper-item 设置 transform，你可以给编译后的 swiper-item 设置 transform 看看，是不生效的。

而且 Swiper 组件用于轮播，并不是这样用的。你的这种标题栏需求直接 CSS 写就好了。
