### ISSUE TITLE
AtInput输入中文handleChange无法监听，只能监听非中文

### ISSUE THREAD

**Issue by zhangzhiguoGitHub** [NervJS/taro#3351]
Taro v1.3.0-beta.6
最新版依赖
constructor (props) {
    super(props)

    this.state = {
      info: { ...this.props.value },
      areaList: [],
      multiIndex: [],
      listLength: 0
    }
  }
   <AtInput
              title='收件人姓名'
              name='username'
              value={info.username}
              onChange={this.handleChange.bind(this, 'username')}
            />
handleChange = (name, val) => {
    console.log(name,val)
    const { info } = this.state
    info[name] = val
  [}[](url)](url)
![1559837097(1)](https://user-images.githubusercontent.com/24820656/59048197-ec845900-88b7-11e9-9894-fbc1ced869b8.jpg)
![1559837178(1)](https://user-images.githubusercontent.com/24820656/59048302-1dfd2480-88b8-11e9-994a-14d2c7b250d7.jpg)

**Comment by aizigao** [comment]
@luckyadam 我这边有一些比较老的测试机型，现在只在ios8,9 在d163be7 提交后出现了类似
https://github.com/NervJS/taro/pull/3217 的问题，
具体为使用输入时在输入框展示编码型输入法输入中文时内容重复，当前试过了ios8,9,10,13的机器，在8,9下会有问题，我这边临时改了下原型链覆盖了一下，希望官方处理一下
