### ISSUE TITLE
怎么配置微信小程序的sitemap

### ISSUE THREAD

**Issue by woncs** [NervJS/taro#3357]
**问题描述**
微信小程序貌似新来了个sitemap功能，，没在taro文档里找到怎么配置的办法。
微信官方文档： https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/sitemap.html

**复现步骤**
在新版开发者工具中会提示

**期望行为**
taro支持配置

**报错信息**
![wxtool](https://user-images.githubusercontent.com/4041730/59154941-4cddeb00-8ab0-11e9-9801-8a55d67902f1.png)

**Comment by Chen-jj** [comment]
@woncs 写个 sitemap.json，配置 [copy](https://nervjs.github.io/taro/docs/config-detail.html#copy) 就好了。
