### ISSUE TITLE
## mapbox-gl使用问题

### ISSUE THREAD

**Issue by LOUSANPANG** [NervJS/taro#3358]
**问题描述**
1. 引用 `mapbox-gl` 使用时报错信息 `_typeof is not defined` 。
2. 对于 `mapbox-gl` 在 `vue` `react` 甚至是原生里边都没有问题，地图会正常显示。

**复现步骤**
1. 这里展示引入已下载好的 `mapbox-gl-js` 文件，也使用过 `npm` 的`mapbox-gl` 问题一样。 
2. 引入
    ```
        <link rel="stylesheet" href="./map/mapbox-gl.css">
        import Mapboxgl from "../../map/mapbox-gl"
    ```
3. 使用
    ```
      componentDidMount() {
        console.log(Mapboxgl)
        new Mapboxgl.Map({
          container: "map",
          epsg: "EPSG:3857",
          zoom: 3,
          center: [116.39, 39.91],
          hash: true,
          style:
            "http://vtctest.geo-compass.com/api/v1/map/10001000084/publish?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMyIsImlhdCI6MTU1NjE4MjQwNiwiZXhwIjoxNTU2Nzg3MjA2fQ.3haSYFupHKq-6t2X5_GD45SmG7sKW8LTA46Anj1LcEY"
        })
      }
    ```
4. 
    ```
      render() {
          return (
            <View id='map' />
          )
       }
    ```
5. 可以打印出来 `Mapboxgl` ，也渲染成功 `html` ，但是有些有些东西找不到。
![image](https://user-images.githubusercontent.com/36870764/59155215-00e27480-8ab7-11e9-9e7d-7c1cf9a75e1c.png)

![image](https://user-images.githubusercontent.com/36870764/59155228-34bd9a00-8ab7-11e9-9608-56a2f0dbf593.png)

```
  1. 该问题在 https://github.com/mapbox/mapbox-gl-js/issues/3422#event-830865781 中提到过。
  2. 貌似是 babel 编译问题。
```

**期望行为**
[地图成功显示]

**报错信息**
![image](https://user-images.githubusercontent.com/36870764/59155215-00e27480-8ab7-11e9-9e7d-7c1cf9a75e1c.png)

**系统信息**
 - 操作系统: [e.g. macOS 10.14.5]
 - Taro 版本 [e.g. v.1.3.0]
 - Node.js 版本 [e.g. v11.10]
 - 报错平台 [h5]

**补充信息**
1. [相关问题 `_typeof is not defined`]
```
  https://github.com/mapbox/mapbox-gl-js/issues/3422#event-830865781
```
2. 测试过vue、react、原生都没有问题，它们也是同样的代码。

**Comment by Mrxpj** [comment]
> https://github.com/mapbox/mapbox-gl-js/issues/3422#event-830865781

你好，请问你解决了吗，我这里也出现同样的问题
