### ISSUE TITLE
文档的Taro.chooseImage缺少参数的描述

### ISSUE THREAD

**Issue by gdutwyg** [NervJS/taro#3361]
**问题描述**
Taro.chooseImage缺少参数的描述
https://nervjs.github.io/taro/docs/apis/multimedia/images/chooseImage.html

![image](https://user-images.githubusercontent.com/11848087/59170755-aad30700-8b72-11e9-98f1-236357185e47.png)

**期望行为**
增加参数的描述

**Comment by Pines-Cheng** [comment]
参数和微信小程序一致。
