### ISSUE TITLE
滚动加载的列表数据替换性能很差

### ISSUE THREAD

**Issue by joker-ye** [NervJS/taro#3362]
**问题描述**
二级分类下的商品列表，滚动加载，每页10条数据，滚动三页数组arr里有30条数据
切换二级分类，arr替换成新的10条数据，接口数据很快，但是渲染替换的时间很长，用户体验很很差

**Comment by Garfield550** [comment]
请提供复现代码，方便官方确认问题。

**Comment by Chen-jj** [comment]
@joker-ye 哪个端？哪个版本？最好提供一下代码

**Comment by zhongqiang1839** [comment]
> 请提供复现代码，方便官方确认问题。

支付宝小程序确实有这个问题，  环境dva + taro.     简单来说 组件中通过dispatch 调用 state两个数组切换，从100条数据的长列表切换成空数组，就会卡顿好久大约5秒以上。  麻烦能确认下吗

**Comment by zhongqiang1839** [comment]
> @joker-ye 哪个端？哪个版本？最好提供一下代码

支付宝小程序确实有这个问题， 环境dva + taro. 简单来说 组件中通过dispatch 调用 state两个数组切换，从100条数据的长列表切换成空数组，就会卡顿好久大约5秒以上。 麻烦能确认下吗

**Comment by Chen-jj** [comment]
@zhongqiang1839 版本？

**Comment by zhongqiang1839** [comment]
> @zhongqiang1839 版本？

Taro 1.2.26,   dva 1.4.0

**Comment by Chen-jj** [comment]
@zhongqiang1839 升到 beta.8 再试试

**Comment by Chen-jj** [comment]
@zhongqiang1839 小程序性能问题一般在于 setData 次数与每次 setData 大小。参考[这里](https://nervjs.github.io/taro/docs/debug.html#%E8%A2%AB-diff-%E9%80%BB%E8%BE%91%E8%BF%87%E6%BB%A4)找到真正 setData 的地方打 log 再看看问题在哪里。

**Comment by febobo** [comment]
> > @zhongqiang1839 版本？
> 
> Taro 1.2.26, dva 1.4.0

Hi, 问下咱们这个问题解决了吗? 我们也遇到同样的问题

**Comment by Chen-jj** [comment]
@febobo https://nervjs.github.io/taro/docs/debug.html#%E8%A2%AB-diff-%E9%80%BB%E8%BE%91%E8%BF%87%E6%BB%A4
