### ISSUE TITLE
Taro cli能否支持ApolloProvider 实现 apollo client

### ISSUE THREAD

**Issue by Janice1114** [NervJS/taro#3363]
**问题描述**
目前taro cli的源码不支持 apollo client，能否在类似判断 redux的基础上，添加对apolloProvider的标签插入支持。在AST解析的时候当判断到位 apollo provider，类似redux插入 <ApolloProvider>标签

**复现步骤**
[复现问题的步骤]
1. 执行cli命令，` taro init myAPP`
2. 发现无法支持 ApolloProvider 以及相关apollo client <Mutation> <Query>组件
3. app.js 引入 Apollo Client 以及 ApolloProvider；
使用 ApolloProvider 标签 包裹 ；
使用 npm run build:h5 执行构建

```js

import { ApolloClient } from 'apollo-client';
import { ApolloProvider } from 'react-apollo';
...

class App extends Component {
   render () {
      return (
        <ApolloProvider client={client}>
            <App />
       </ApolloProvider>
      )
  }
}

```

**期望行为**
ApolloProvicer 能在打包之后的 app.js 中成功包裹，而不是被移除；如：

```js
<ApolloProvider>
    <index />
</ApolloProvider>
```

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

- 操作系统: [Windows 10]
- Taro 版本 [v1.3.0-beta.8]
- Node.js 版本 [v9.9.0]
- 报错平台 [h5]

**补充信息**
[根据你的调查研究，出现这个问题的原因可能在哪里？]
taro cli 对 ApolloProvider的标签判断未支持，需要判断到相关Apollo Provider。

**Comment by luckyadam** [comment]
#2679

**Comment by luckyadam** [comment]
尽量在 1.3 正式版之后的小版本迭代中支持

**Comment by Janice1114** [comment]
@luckyadam 谢谢，麻烦支持了。 目前尝试了 1.3.0正式版 还是不行的。 <ApolloProvider> 标签注入还是打包异常的

**Comment by nuknal** [comment]
react-apollo 内部使用了context.Consumer ReactNode之类taro未实现的语法，
最新版本已经支持hooks了，我觉得可以修改react-apollo，因为实际上在使用hooks的时候apollo只是从context取了个client。
建议看看react-apollo的源码了解下是否可行
[...来自一个不懂JavaScript的后端]
