### ISSUE TITLE
1.3.x webView 小程序问题

### ISSUE THREAD

**Issue by lei40251** [NervJS/taro#3364]
**问题描述**

用 npm install -g @tarojs/cli 安装的 v1.3.x 最新的beta版本执行 npm run build:weapp 后的版本 WebView 控件打开任何网页都是一片空白；但是同样代码 用 v1.2.26 版本 编译没有问题。

**系统信息**
�👽 Taro v1.2.26
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
以上正常

以下版本有问题
�👽 Taro v1.3.0-beta.8
  Taro CLI 1.3.0-beta.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@lei40251 哪个端

**Comment by lei40251** [comment]
微信小程序 @Chen-jj

**Comment by Chen-jj** [comment]
@lei40251 完整可复现代码也提供一下。

**Comment by lei40251** [comment]
@Chen-jj 
`import Taro, { Component, Config } from '@tarojs/taro'
import { WebView } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
        <WebView src='https://www.baidu.com' />
    )
  }
}
`

直接这样就行

**Comment by lei40251** [comment]
import Taro, { Component, Config } from '@tarojs/taro'
import { WebView } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
        <WebView src='https://www.baidu.com' />
    )
  }
}

**Comment by lei40251** [comment]
`import { WebView } from '@tarojs/components'`
...
`<WebView src='https://www.baidu.com' />`
这样的，刚才代码被处理过了。。。

**Comment by Chen-jj** [comment]
@lei40251 beta.8，复现不了。

```js
import Taro, { Component } from '@tarojs/taro'
import { View, WebView } from '@tarojs/components'

import './detail.scss'

export default class Detail extends Component {
  render () {
    return (
      <View>
        <WebView src='https://www.baidu.com' />
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/59176746-9f8cd500-8b8c-11e9-8e7e-56f66b8674c7.png)

**Comment by lei40251** [comment]
我的是win10 ，会不会和系统有关？

**Comment by lei40251** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@lei40251 看看编译后的 wxml，然后再试试原生的。

**Comment by lei40251** [comment]
@Chen-jj 
wxml 

v1.2 正常
```
<block>
    <web-view src="https://www.baidu.com"></web-view>
</block>
```

v1.3 有问题
```
<block wx:if="{{$taroCompReady}}">
    <web-view src="https://www.baidu.com"></web-view>
</block>
```

**Comment by Chen-jj** [comment]
@lei40251 CLI 和依赖保持版本一致。

**Comment by lei40251** [comment]
好吧，明白了；
不过，我直接按文档快速开始就是这样的。。。

**Comment by Chen-jj** [comment]
@lei40251 不可能，如果你是用 1.3 的 CLI 创建的项目不会这样子。

**Comment by lei40251** [comment]
嗯，前面版本串了，都用1.3正常，谢谢。

**Comment by littleQing** [comment]
确实有这个问题呀，网易严选demo，clone下来，安装完依赖
1. yarn run dev:weapp 预览正常
2. yarn run build:weapp ，预览 webview页面加载的网页就空白了
