### ISSUE TITLE
点击事件获取不到event 

### ISSUE THREAD

**Issue by Murphycx94** [NervJS/taro#3365]
```javascript
onPreview = ({ imgLarge }, e) => {
    console.log(e)  // undefined
    if (this.props.isAd && this.props.onDownload) {
      this.props.onDownload(e)
    } else {
      e.stopPropagation()
      Taro.previewImage({
        current: imgLarge,
        urls: this.props.images.map(el => el.imgLarge)
      })
    }
  }
```
```javascript
<View className="image-item" key={item.imgSmall} onClick={this.onPreview.bind(this, item)}>
</View>
```

把event打印出来是undefined

依赖比较旧了，不支持匿名函数传参
"dependencies": {
    "@tarojs/async-await": "^1.2.0-beta.7",
    "@tarojs/components": "^1.2.0-beta.7",
    "@tarojs/redux": "^1.2.0-beta.7",
    "@tarojs/redux-h5": "^1.2.0-beta.7",
    "@tarojs/router": "^1.2.0-beta.7",
    "@tarojs/taro": "^1.2.0-beta.7",
    "@tarojs/taro-alipay": "^1.2.0-beta.7",
    "@tarojs/taro-h5": "^1.2.0-beta.7",
    "@tarojs/taro-swan": "^1.2.0-beta.7",
    "@tarojs/taro-weapp": "^1.2.0-beta.7",
    "dva-core": "^1.4.0",
    "dva-loading": "^2.0.6",
    "md5": "^2.2.1",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.8",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/plugin-babel": "^1.2.0-beta.7",
    "@tarojs/plugin-csso": "^1.2.0-beta.7",
    "@tarojs/plugin-less": "^1.2.0-beta.7",
    "@tarojs/plugin-uglifyjs": "^1.2.0-beta.7",
    "@tarojs/webpack-runner": "^1.2.0-beta.7",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^1.2.0-beta.7",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "^1.2.0-beta.7",
    "eslint-plugin-typescript": "^0.12.0",
    "typescript": "^3.0.1"
  }

**Comment by Chen-jj** [comment]
@Murphycx94 升级到 v1.3.0-beta.8 后再试试
