### ISSUE TITLE
H5端出现Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by hnsxxscyx** [NervJS/taro#3366]
复现：未知，但可以确定非代码的错，因为只要重开项目然后把src原样复制进去就可以跑，但过一段又会出现此错误，哪怕代码并未更改。
原代码：taro init 的初试index.html模板
环境：
👽 Taro v1.2.26
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
升级到 1.3.0-beta.8 试试

**Comment by Young1993** [comment]
我也是的，版本号 1.2.15

**Comment by hnsxxscyx** [comment]
> 升级到 1.3.0-beta.8 试试

已成功复现，h5的publicPath: './' 就会报这个，改为/正常

**Comment by useryechen** [comment]
你好，我也出现了这个问题。但是我的config中publicPath默认就是/  打包后还是出现这个问题

**Comment by useryechen** [comment]
我用live-server在dist目录下起服务确实存在这个问题，但是用wamp起了个服务然后把打包后的文件放上去访问是没问题的

**Comment by Littly** [comment]
问题就出在publicPath上，检查下配置吧。
https://github.com/NervJS/taro/issues/4163#issuecomment-521085257
https://github.com/NervJS/taro/issues/4163#issuecomment-522831187

**Comment by Yana5417** [comment]
请问这个问题最终是怎样解决的呢？
我在index.js中配置
`publicPath: '/'`
prod.js中配置
`module.exports = {
  env: {
    NODE_ENV: '"production"'
  },
  defineConstants: {
  },
  weapp: {},
  h5: {
    publicPath: './',
  }
}
`
打包之后，线上访问页面依然报`Uncaught SyntaxError: Unexpected token '<'`

**Comment by Yana5417** [comment]
> 升级到 1.3.0-beta.8 试试

我用的1.3.27，也有这个问题

**Comment by cnscorpions** [comment]
同上，配置设置为publicPath: '/'，依然是这个问题

**Comment by cnscorpions** [comment]
`config/prod.js`里publicPath: '/'解决了问题

**Comment by JanYork** [comment]
我config中publicPath默认就是/ ，打包直接Uncaught SyntaxError: Unexpected token。。。。，真的服了taro
