### ISSUE TITLE
1.3.0 beta8  showLoading 显示上一个showToast内容

### ISSUE THREAD

**Issue by ninetowns** [NervJS/taro#3367]
**问题描述**
更新到最新版本（1.3.0 beta8）后，showLoading将显示上一个showToast的内容，无论title为空或者不填都如此

**复现步骤**
```js
    Taro.showToast({
      title:'abc'
    })
    setTimeout(()=>{
      Taro.showLoading();  //显示abc
    },4000)
```

**期望行为**
正常显示loding

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
**系统信息**
 Taro v1.3.0-beta.8
  Taro CLI 1.3.0-beta.8 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.12.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@ninetowns 哪个端

**Comment by ninetowns** [comment]
@Chen-jj h5
