### ISSUE TITLE
`Taro.request`中回调`complete`函数中没有接收到参数

### ISSUE THREAD

**Issue by biliGates** [NervJS/taro#337]
# 问题描述
小程序端`Taro.request`方法中的`complete`回调函数，没有接收到参数。与小程序官方`API`有出入。`complete`如果接收不到参数,那么这个回调的存在就没有什么意义了。希望能于官方`API`功能上保持一致。

**Comment by yuche** [comment]
Duplicate of #330

**Comment by Chen-jj** [comment]
已修复: [d9d36f9](https://github.com/NervJS/taro/commit/d9d36f94a3c2b88a5ce9520b0e380a559e93b769)
