### ISSUE TITLE
微信小程序转taro报错：template is not defined 

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3370]
**问题描述**
[taro convert转换小程序时，报错template is not defined ]

**复现步骤**
[复现问题的步骤]
1. 小程序项目目录下
2. taro convert
3. 报错template is not defined 

**期望行为**
[taro convert小程序项目报错，阻断了转换的过程]

**报错信息**
taro convert小程序项目报错，阻断了转换的过程；
官方文档中也没有样例明确转换成功后，会是什么样子，会有哪些文件；
![image](https://user-images.githubusercontent.com/13342245/59184120-04055f80-8ba0-11e9-8304-00f18ec90743.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
close via d9b3d0c330b5bd47ae96e53b76fe1e23365d2aa0
