### ISSUE TITLE
taro init的时候出现babel相关的报错 

### ISSUE THREAD

**Issue by 34678** [NervJS/taro#3376]
**问题描述**
初始化taro项目后报错
**复现步骤**
[复现问题的步骤]
1安装taro后 taro init
2 因为报错babel版本不兼容 于是我执行
Yarn add babel-loader babel-core@^7.0.0-bridge @babel/core 
3  taro build --type weapp --watch
4 出现了问题描述中的截图

**期望行为**
期望正常运行起来代码

**报错信息**

![image](https://user-images.githubusercontent.com/23259141/59200442-cec23700-8bca-11e9-8450-a6c834fe5907.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.0-beta.5

  Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 0.0.42 => 0.0.42
      @tarojs/components: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-babel: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-csso: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-sass: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/plugin-uglifyjs: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/router: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-alipay: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-h5: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-swan: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-tt: 1.3.0-beta.3 => 1.3.0-beta.3
      @tarojs/taro-weapp: ^1.3.0-beta.5 => 1.3.0-beta.5
      @tarojs/webpack-runner: 1.3.0-beta.3 => 1.3.0-beta.3
      eslint-config-taro: 1.3.0-beta.3 => 1.3.0-beta.3
      eslint-plugin-taro: 1.3.0-beta.3 => 1.3.0-beta.3
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4

**Comment by luckyadam** [comment]
你不用再安装 babel 了，Taro 的模板里已经指定了依赖的 babel 版本，你正常安装就行

**Comment by 34678** [comment]
> 你不用再安装 babel 了，Taro 的模板里已经指定了依赖的 babel 版本，你正常安装就行

未安装的情况下跑起来提示是不兼容的@babel/core哦~我又看到一个类似的issue但是解决不了~

**Comment by 34678** [comment]
> 你不用再安装 babel 了，Taro 的模板里已经指定了依赖的 babel 版本，你正常安装就行

我直接init myapp 然后  taro build --type weapp --watch
效果如图
![image](https://user-images.githubusercontent.com/23259141/59202494-2c588280-8bcf-11e9-80d3-314d68643417.png)
今天突然这样的。
之前运行还很正常

**Comment by 34678** [comment]
然后我去 拉个个taro做的小程序  跑起来也没问题，也就是说我的环境是没问题的。。不知道为什么init之后的不行

**Comment by 34678** [comment]
我把微信小程序taroconvert之后再跑起来还是出现一样的问题~need help~
![image](https://user-images.githubusercontent.com/23259141/59204665-af7bd780-8bd3-11e9-85e5-14efded8902a.png)

**Comment by 34678** [comment]
我把版本回退到1.2.11就可以了。虽然我还是没搞懂什么问题哈哈~

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/59237739-df57c900-8c2d-11e9-8e89-3f8de2d54d79.png)
麻烦把 cli 和其他依赖版本匹配

**Comment by luckyadam** [comment]
> ![image](https://user-images.githubusercontent.com/3471836/59237739-df57c900-8c2d-11e9-8e89-3f8de2d54d79.png)
> 麻烦把 cli 和其他依赖版本匹配

眼力好😂

**Comment by 34678** [comment]
> ![image](https://user-images.githubusercontent.com/3471836/59237739-df57c900-8c2d-11e9-8e89-3f8de2d54d79.png)
> 麻烦把 cli 和其他依赖版本匹配

想请问下taro cli init的项目为什么会出现 自己安装的依赖和本身版本不匹配的情况呢~

**Comment by Garfield550** [comment]
> > ![image](https://user-images.githubusercontent.com/3471836/59237739-df57c900-8c2d-11e9-8e89-3f8de2d54d79.png)
> > 麻烦把 cli 和其他依赖版本匹配
> 
> 想请问下taro cli init的项目为什么会出现 自己安装的依赖和本身版本不匹配的情况呢~

可能是没装好？不过你这个 taro info 的结果很奇怪，Taro CLI 1.3.0-beta.5 environment info 返回的 @tarojs/cli 是0.0.42，然后你的其他依赖版本是 1.3.0-beta.3，让我也摸不着头。

**Comment by Garfield550** [comment]
1.3.0 正式版发布了，我觉得你可以删除所有 @tarojs 相关的包，然后重新安装，init。

**Comment by 34678** [comment]
> 1.3.0 正式版发布了，我觉得你可以删除所有 @tarojs 相关的包，然后重新安装，init。

好滴 问题解决了 十分感谢

**Comment by 34678** [comment]
使用taro update之后装了1.3.0 又出现这个问题了...help
👽 Taro v1.3.0


  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-sass: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0

**Comment by luckyadam** [comment]
你把 node_modules 删了，然后重新安装依赖吧

**Comment by soju-cao** [comment]
遇到同样的问题

> 使用taro update之后装了1.3.0 又出现这个问题了...help
> 👽 Taro v1.3.0
> 
> Taro CLI 1.3.0 environment info:
> System:
> OS: macOS High Sierra 10.13.6
> Shell: 5.3 - /bin/zsh
> Binaries:
> Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
> Yarn: 1.13.0 - /usr/local/bin/yarn
> npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
> npmPackages:
> @tarojs/components: 1.3.0 => 1.3.0
> @tarojs/plugin-babel: 1.3.0 => 1.3.0
> @tarojs/plugin-csso: 1.3.0 => 1.3.0
> @tarojs/plugin-sass: 1.3.0 => 1.3.0
> @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0
> @tarojs/router: 1.3.0 => 1.3.0
> @tarojs/taro: 1.3.0 => 1.3.0
> @tarojs/taro-alipay: 1.3.0 => 1.3.0
> @tarojs/taro-h5: 1.3.0 => 1.3.0
> @tarojs/taro-swan: 1.3.0 => 1.3.0
> @tarojs/taro-tt: 1.3.0 => 1.3.0
> @tarojs/taro-weapp: 1.3.0 => 1.3.0
> @tarojs/webpack-runner: 1.3.0 => 1.3.0
> eslint-config-taro: 1.3.0 => 1.3.0
> eslint-plugin-taro: 1.3.0 => 1.3.0
> nervjs: ^1.4.0 => 1.4.0

遇到同样的问题，删除重新安装依赖，无法解决。
