### ISSUE TITLE
Eslint的问题

### ISSUE THREAD

**Issue by code-coder** [NervJS/taro#338]
taro init项目:
语法：TS
模板：redux

初始化后打开tsx和ts文件都是红的，看着好难受！
希望能优化一下

**Comment by zend** [comment]
config 目录的文件，本身只支持commonjs方式，但eslint一直抱怨要让我改成es6的 export default。

**Comment by luckyadam** [comment]
@code-coder 1.0.0-beta.9 版本解决了这个问题
