### ISSUE TITLE
支付宝小程序上传失败

### ISSUE THREAD

**Issue by zhongqiang1839** [NervJS/taro#3380]
**问题描述**
问题如图，打包完成后上传显示 dva-core 路径过长
![image](https://user-images.githubusercontent.com/17607547/59249783-25c21d80-8c58-11e9-81aa-30355e53a242.png)

**期望行为**
正常上传版本

**报错信息**
![image](https://user-images.githubusercontent.com/17607547/59249783-25c21d80-8c58-11e9-81aa-30355e53a242.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: MAC
 - Taro 版本 1.3.0.beta8
 - Node.js 版本 10.5.0
 - 报错平台 alipay

**Comment by ooxx87** [comment]
先卸载dva-core，然后先安装core-js，再安装dva-core
