### ISSUE TITLE
字节跳动小程序获取手机号报错

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#3382]
**问题描述**
字节跳动小程序调用login方法后获取手机号报错

**复现步骤**
[复现问题的步骤]
1. 调用login方法
2. 点击按钮获取手机号
3. 授权同意
4. 报错
```js
<Button
   className='author-button'
    openType='getPhoneNumber'
    style={this.props.buttonStyle}
     onGetPhoneNumber={this.getPhoneNumber.bind(this)}>
 </Button>

componentWillMount() {
        if (Platform.isTt) {
            this.ttLogin();
        }
    }
 async ttLogin() {
        let token = _.get(this.props, 'userinfo.session.token');
        if (!!token) return;
        let info = await Taro.login();
        console.log(info);
    }
getPhoneNumber(info) {
     console.log(info);
    }
```

**期望行为**
正常获取Api接口数据

**报错信息**
![481560237252_ pic_hd](https://user-images.githubusercontent.com/42051272/59251102-9454aa80-8c5b-11e9-933f-3539c83bf932.jpg)
报错点进去截图（event.type为undefined）
![471560236916_ pic_hd](https://user-images.githubusercontent.com/42051272/59251167-b8b08700-8c5b-11e9-841f-3f222412e37b.jpg)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/components: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-babel: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-csso: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-less: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/redux: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/router: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-alipay: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-h5: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-swan: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-tt: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-weapp: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/webpack-runner: 1.3.0-beta.6 => 1.3.0-beta.6 
      eslint-config-taro: 1.3.0-beta.6 => 1.3.0-beta.6 
      eslint-plugin-taro: 1.3.0-beta.6 => 1.3.0-beta.6 
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4

**Comment by VFiee** [comment]
修改为var eventType = event.type ? event.type.toLocaleLowerCase() : null;
getPhoneNumber可以执行成功，但返回的数据信息中没有获取到对应的数据
![511560329040_ pic_hd](https://user-images.githubusercontent.com/42051272/59336533-532eca00-8d31-11e9-803e-8a2961be6171.jpg)
![521560329085_ pic_hd](https://user-images.githubusercontent.com/42051272/59336570-6346a980-8d31-11e9-9647-4d3412242131.jpg)

**Comment by Chen-jj** [comment]
@VFiee 调试一下：https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F

**Comment by zeegb** [comment]
@VFiee 想问下这个解决了吗？遇到了同样的问题。
