### ISSUE TITLE
编译成百度小程序没有报错，页面不显示内容

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#3383]
**问题描述**
编译成百度小程序，无报错，任何页面显示不出来，只有底部四个TabBar，ajax请求正常，UI无法显示，项目中大量使用类函数组件（https://nervjs.github.io/taro/docs/functional-component.html#%E7%B1%BB%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6）

**复现步骤**
[复现问题的步骤]
1. yarn dev:swan
2. 填写百度小程序appid
3. 打开控制台无报错
4. 只显示四个Tab，页面内容不显示

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```js

index.swan
<template name="renderTopSearch">
    <block>
        <view class="{{'fixed-wrap ' + (fixedColor ? 'fixed-wrap-active' : '')}}">
            <view class="fixed-search">
                <view class="area" bindtap="chooseCity">{{anonymousState__temp}}
                    <image class="area-select" mode="aspectFit" src="{{anonymousState__temp2}}"></image>
                </view>
                <view class="search" bindtap="toSearch">
                    <image class="search-icon" mode="aspectFit" src="{{anonymousState__temp3}}"></image><text class="search-placeholder">请输入小区名称或商圈</text>
                </view>
            </view>
        </view>
    </block>
</template>


<block s-if="{{$taroCompReady}}">
    <view class="wrap">
        <template is="renderTopSearch" data="{{...anonymousState__temp12}}"></template>
    </view>
</block>
```

**期望行为**
正常显示UI

**报错信息**
无报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/components: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-babel: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-csso: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-less: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/redux: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/router: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-alipay: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-h5: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-swan: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-tt: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/taro-weapp: 1.3.0-beta.6 => 1.3.0-beta.6 
      @tarojs/webpack-runner: 1.3.0-beta.6 => 1.3.0-beta.6 
      eslint-config-taro: 1.3.0-beta.6 => 1.3.0-beta.6 
      eslint-plugin-taro: 1.3.0-beta.6 => 1.3.0-beta.6 
      nervjs: ^1.4.0-beta.3 => 1.4.0-beta.4

**Comment by yuche** [comment]
更新到 1.3.0 正式版

**Comment by VFiee** [comment]
升级到1.3.0之后，页面显示正常
