### ISSUE TITLE
微信小程序开发工具中子组件不进入componentDidShow生命周期，真机正常

### ISSUE THREAD

**Issue by sycreece** [NervJS/taro#3386]
**问题描述**

微信小程序开发工具中，在A页面组件中嵌套子组件B，子组件B没有执行componentDidShow生命周期，在taro cli 1.2.x版本中没有这个问题

**复现步骤**

1. 在A页面组件中添加子组件B；
2. 微信小程序开发工具进入A页面，没有执行子组件B的componentDidShow；

```js
//A页面组件
import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";
import { connect } from "@tarojs/redux";

import SwiperGuides from "./components/swiperGuides";

import "./index.scss";

class Index extends Component {
  state = {
    params: null
  };
  config = {
    navigationBarTitleText: "test"
  };

  componentWillMount() {
    this.setState({
      params: this.$router.params
    });
  }

  async onPullDownRefresh() {
    Taro.stopPullDownRefresh();
  }

  render() {
    return (
      <View>
        {this.state.params ? (
          <SwiperGuides />
        ) : null}
      </View>
    );
  }
}

export default Index;


// 子组件B
import Taro, { Component } from "@tarojs/taro";
import { View, Swiper, SwiperItem } from "@tarojs/components";
import { connect } from "@tarojs/redux";

import curl from "@/utils/requestMethod";
import apiConfig from "@/constants/apiConfig";

import GuideCard from "@/components/guideCard";
import MLoading from "@/components/mLoading";

import "./index.scss";

@connect(({ user, globalData }) => {
  const { header } = globalData;
  const { mpUserInfo, hbcUserInfo } = user;
  return {
    header,
    mpUserInfo,
    hbcUserInfo
  };
})
class SwiperGuides extends Component {
  constructor(props) {
    super(props);
    this.state = {
      show: false, // 是否显示列表
      isLoading: true,
      guidesNum: 2.1, // swiper每屏显示的司导个数
      guidesInfo: []
    };
  }

  async getGuideList(callback) {
    this.userId = this.props.hbcUserInfo ? this.props.hbcUserInfo.userId : "";
    try {
      const res = await curl({
        url: apiConfig.guideInfo,
        method: "POST",
        header: Object.assign({}, this.props.header),
        data: {
          userId: this.userId,
          openId: this.props.mpUserInfo.openid,
          offset: "0",
          limit: "16"
        }
      });
      this.setState({
        isLoading: false
      });
      if (res.status === 200 && res.data && res.data.length) {
        this.setState({
          show: true,
          guidesInfo: res.data
        });
        res.data.length <= 2 &&
          this.setState({
            guidesNum: res.data.length
          });
        // console.log(res.data);
      } else {
        this.setState({
          show: false,
          guidesNum: 2.1,
          guidesInfo: []
        });
      }
      callback && callback();
    } catch (e) {
      this.setState({
        isLoading: false
      });
      console.log(e);
    }
  }

  componentDidShow() {
    this.getGuideList();
  }

  async onPullDownRefresh() {
    const callback = () => {
      Taro.stopPullDownRefresh();
    };
    this.getGuideList(callback);
  }

  render() {
    return (
      <View>
        {this.state.show ? (
          <View>
            <View className='guide-title'>为你推荐的司导</View>
            <Swiper
              className='swiper-banner'
              displayMultipleItems={this.state.guidesNum}
            >
              {this.state.guidesInfo.map((guideInfo, index) => {
                return (
                  <SwiperItem
                    className={this.state.guidesNum <= 2 ? "swiperGuides" : ""}
                    key={String(index)}
                  >
                    <GuideCard guideInfo={guideInfo} />
                  </SwiperItem>
                );
              })}
            </Swiper>
          </View>
        ) : null}
        <MLoading loading={this.state.isLoading} />
      </View>
    );
  }
}

export default SwiperGuides;
```

**期望行为**

微信开发工具正常进入子组件B的 componentDidShow 生命周期

**报错信息**

**系统信息**

Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~.tnvm/versions/alinode/v4.7.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~.tnvm/versions/alinode/v4.7.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0 => 1.3.0
      @tarojs/components: 1.3.0 => 1.3.0
      @tarojs/plugin-babel: 1.3.0 => 1.3.0
      @tarojs/plugin-csso: 1.3.0 => 1.3.0
      @tarojs/plugin-sass: 1.3.0 => 1.3.0
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0
      @tarojs/redux: 1.3.0 => 1.3.0
      @tarojs/redux-h5: 1.3.0 => 1.3.0
      @tarojs/router: 1.3.0 => 1.3.0
      @tarojs/taro: 1.3.0 => 1.3.0
      @tarojs/taro-alipay: 1.3.0 => 1.3.0
      @tarojs/taro-h5: 1.3.0 => 1.3.0
      @tarojs/taro-swan: 1.3.0 => 1.3.0
      @tarojs/taro-tt: 1.3.0 => 1.3.0
      @tarojs/taro-weapp: 1.3.0 => 1.3.0
      @tarojs/webpack-runner: 1.3.0 => 1.3.0
      eslint-config-taro: 1.3.0 => 1.3.0
      eslint-plugin-taro: 1.3.0 => 1.3.0
      nervjs: ^1.4.0 => 1.4.0
    npmGlobalPackages:
      typescript: 3.3.4000

**补充信息**
1、可能1.3.0编译的时候对小程序开发工具支持不好；
2、微信小程序开发工具自身有问题；

**Comment by Chen-jj** [comment]
@sycreece 可以触发，排除一下业务代码的问题吧。

```js
// page
export default class Index extends Component {
  state = {
    params: null
  }

  componentWillMount() {
    this.setState({
      params: this.$router.params
    })
  }

  render() {
    return (
      <View>
        {this.state.params ? (
          <A />
        ) : null}
      </View>
    );
  }
}
```

```js
// component
export default class A extends Component {
  constructor(props) {
    super(props);
    this.state = {
      show: false, // 是否显示列表
    };
  }

  componentDidShow() {
    console.log('didshow')
  }

  render() {
    return (
      <View>
        {this.state.show ? (
          <View>
            <View className='guide-title'>为你推荐的司导</View>
          </View>
        ) : null}
      </View>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/59398454-dea46b80-8dc2-11e9-84be-b26621a16d9c.png)

**Comment by sycreece** [comment]
> @sycreece 可以触发，排除一下业务代码的问题吧。
> 
> ```js
> // page
> export default class Index extends Component {
>   state = {
>     params: null
>   }
> 
>   componentWillMount() {
>     this.setState({
>       params: this.$router.params
>     })
>   }
> 
>   render() {
>     return (
>       <View>
>         {this.state.params ? (
>           <A />
>         ) : null}
>       </View>
>     );
>   }
> }
> ```
> 
> ```js
> // component
> export default class A extends Component {
>   constructor(props) {
>     super(props);
>     this.state = {
>       show: false, // 是否显示列表
>     };
>   }
> 
>   componentDidShow() {
>     console.log('didshow')
>   }
> 
>   render() {
>     return (
>       <View>
>         {this.state.show ? (
>           <View>
>             <View className='guide-title'>为你推荐的司导</View>
>           </View>
>         ) : null}
>       </View>
>     );
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/11807297/59398454-dea46b80-8dc2-11e9-84be-b26621a16d9c.png)

请问是用上述环境测试的吗，微信开发工具用的什么版本呢？

**Comment by Chen-jj** [comment]
@sycreece Taro 1.3.0，开发者工具最新版本。CLI 和依赖的版本要保持一致。

**Comment by sycreece** [comment]
> @sycreece Taro 1.3.0，开发者工具最新版本。CLI 和依赖的版本要保持一致。

仔细找了下原因，是微信开发工具基础库版本低，不支持这个声明周期~
