### ISSUE TITLE
自定义组件编译出错一次之后就【没有被引用到，不会被编译】

### ISSUE THREAD

**Issue by BrookShuihuaLee** [NervJS/taro#3387]
**问题描述**

在自定义组件中，只要编译出错一次，之后就会报【没有被引用到，不会被编译】，然后就只能重新全量编译了。

**复现步骤**

1. taro init taro-test
2. 引入一个自定义组件，如下
3. 删除`public a() {`里的`{`，保存编译，编译报错
4. 恢复`{`，报`警告  JS文件    src/pages/dddd/index.tsx 没有被引用到，不会被编译`

```js

import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";

export default class Dddd extends Component {
  public render() {
    return <View>23{this.a()}</View>
  }

  public a() {
    return 'sdf'
  }
}


```

**期望行为**

文件不会因为某次编译出错而脱离引用

**报错信息**

警告  JS文件    src/pages/dddd/index.tsx 没有被引用到，不会被编译

**系统信息**

👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/mobx: 1.3.0 => 1.3.0 
      @tarojs/mobx-h5: 1.3.0 => 1.3.0 
      @tarojs/mobx-rn: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-less: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/rn-runner: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0

**补充信息**

加油

**Comment by jonahfang** [comment]
@BrookShuihuaLee 我是在--watch时遇到这个问题，中止当前正在运行的watch,重新开始就好了。

**Comment by BrookShuihuaLee** [comment]
> @BrookShuihuaLee 我是在--watch时遇到这个问题，中止当前正在运行的watch,重新开始就好了。

这里报的就是热更新的问题。需要重新全量编译，是不符合预期的

**Comment by yaogengzhu** [comment]
这个问题解决了吗？  我也是遇到了怎么处理呢？ @BrookShuihuaLee

**Comment by BrookShuihuaLee** [comment]
> 这个问题解决了吗？ 我也是遇到了怎么处理呢？ @BrookShuihuaLee

不知道，等修复

**Comment by qiruiqq3** [comment]
这个问题，最新版本确实也还存在。重启就好了

**Comment by LeeeMooo** [comment]
这个问题依然存在，每次都要全部重新编译，太影响效率了

**Comment by tanggaoliang** [comment]
错误报的是没有引用,我把这个文件的import语句删除再恢复就正常了,比中止cmd命令,再重新run快一些.期待解决方案.

**Comment by tanggaoliang** [comment]
page下面的index.jsx文件错误以后修正就可以了,不会未引用

**Comment by tanggaoliang** [comment]
我发现h5模式下运行没有问题,先以h5运行吧,界面搭建好了再用微信调整吧
