### ISSUE TITLE
v1.3.0 在目录路径很长的情况下编译失败

### ISSUE THREAD

**Issue by shynome** [NervJS/taro#3389]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 创建一个路径很长的目录 `/drone/src/vvvv.eeee.ccc.com/project/`
2. `cd /drone/src/vvvv.eeee.ccc.com/project/`
2.  执行 `taro init frontend`
3. `cd frontend`
4. `npm run build:h5` 或 `npm run dev:h5` 都会失败

**期望行为**
正常编译

**报错信息**
```log
multi ./.temp/app.js
Module not found: Can't resolve '/drone/src/vvvv.eeee.ccc.com/project/frontend/.temp/app.js' in '/drone/src/vvvv.eeee.ccc.com/project/frontend'
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10 和 linux 均会出现
 - Taro 版本 v1.3.0
 - Node.js 版本 12.2.0
 - h5

**补充信息**

短一点的路径即可生成成功, 路径的特殊符号 `-` 和 `.` 均无影响

**Comment by shynome** [comment]
补充: v1.2 的版本没有这个问题

**Comment by Chen-jj** [comment]
使用 Taro2 或 3 再试试吧。
