### ISSUE TITLE
map内子组件传参问题

### ISSUE THREAD

**Issue by Sdoy** [NervJS/taro#339]
**问题描述**
直接看代码吧

```
{
        products.map((product,index)=>{
          console.log(`isLastItem----`,(index + 1 )=== products.length)
          return <ProductCell product={product} key={index}  islast={(index + 1 )=== products.length} />
        })
      }
```
然后在ProductCell组件内输出this.props;
![image](https://user-images.githubusercontent.com/10302939/42805966-d39b6b72-89df-11e8-8cd5-3f139ad9d503.png)

行吧,换个写法
```
{
        products.map((product,index)=>{
          console.log(`isLastItem----`,(index + 1 )=== products.length)
          const isLast=(index + 1 )=== products.length;
          return isLast?<ProductCell product={product} key={index}  islast />:<ProductCell product={product} key={index}  islast={false} />
        })
      }
```
结果:
![image](https://user-images.githubusercontent.com/10302939/42806231-87b035ca-89e0-11e8-9b2c-6f26d1e52051.png)
这应该是同一个cell先被赋值了true后被赋值了false

**系统信息**

 - 操作系统: mac
 - Taro 版本 0.0.69
 - Node.js 版本 8.5

**Comment by luckyadam** [comment]
最新的 beta 版本已经修复了这个问题
