### ISSUE TITLE
state值由有值变为undefined，不会触发更新渲染

### ISSUE THREAD

**Issue by jinmincr** [NervJS/taro#3391]
**问题描述**
使用根据state计算的值，无法更新className

**复现步骤**
```js

class Record extends Component {
  constructor(props) {
    super(props)
    this.state = {
      cardStatus: {}
    }
  }

  init() {
    let temp = {}
    for (let i = 0; i < 5; i++) {
      temp[i] = {
        recorded: false,
        graded: false,
      }
    }
    this.setState({
      cardStatus: temp
    })
  }

  update(index) {
  let temp = this.state.cardStatus
  temp[index].graded = true
      this.setState({
        cardStatus: temp
      })
  }

  render() {
    const { cardStatus } = this.state

    const temp = _.find(cardStatus, item => {
      return !item.graded
    })

    return (
      <View className='record-page'>
          <View className={`record-share ${!!temp ? 'not-record-all' : ''}`} onClick={this.doShare}>分享我的跟读</View>
      </View>
    )
  }
}

```

**期望行为**
中间会有一些逻辑调用update方法，然后当cardStatus里的每项graded为true时，View里的class也会更新，最终是不带‘not-record-all’的

**系统信息**
>Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
是不是必须直接使用state或者props的值，不然无法更新渲染？

**Comment by Chen-jj** [comment]
@jinmincr 升级到1.3再试试

**Comment by jinmincr** [comment]
> @jinmincr 升级到1.3再试试

并不管用。。。

**Comment by Chen-jj** [comment]
@jinmincr 参考这里先打断点 debug 下吧。https://nervjs.github.io/taro/docs/debug.html#debug-diff

**Comment by jinmincr** [comment]
> @jinmincr 参考这里先打断点 debug 下吧。https://nervjs.github.io/taro/docs/debug.html#debug-diff

我尝试了下，如果temp由undefined变为有值，会触发更新，反之由有值变为undefined，不会触发更新

**Comment by Chen-jj** [comment]
@jinmincr 看看是不是被 diff 过滤了

**Comment by jinmincr** [comment]
> @jinmincr 看看是不是被 diff 过滤了

是的，diff结果里没有看到了

**Comment by Chen-jj** [comment]
@jinmincr 贴一下 diff 对比的两个对象的值，JSON.stringify 后的。

**Comment by jinmincr** [comment]
> @jinmincr 贴一下 diff 对比的两个对象的值，JSON.stringify 后的。

我这儿数据太多了，你可以简单的模拟下，比如初始state
```
this.state = {
  test: '123'
}
```
点击一个按钮，修改state，
```
doShare() {
    this.setState({
      test: undefined
    })
}
```

```
<View className={`${this.state.test  ? 'not-record-all' : ''}`} onClick={this.doShare}>分享</View>
```
不会触发更新

**Comment by luckyadam** [comment]
setState 时给数据设置 undefined 会被过滤，可以设置 null 试试
