### ISSUE TITLE
import进来的JSON文件无法热更新

### ISSUE THREAD

**Issue by BrookShuihuaLee** [NervJS/taro#3392]
**问题描述**

修改已经引用进来的JSON文件，会拷贝但不会更新到代码

**复现步骤**
1. 弄一个组件引入一个JSON文件
2. 更新JSON文件
3. 文件会被拷贝，但是不会更新到代码（第一次taro会把JSON塞入代码里，但是之后不会去更新它）

```js

import Taro, { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";

import A_J from "./a.json";

export default class Dddd extends Component {
  public render() {
    return <View>23{this.a()}</View>
  }

  public a() {
    return 'sdf' + JSON.stringify(A_J)
  }
}

```

**期望行为**

更新被引入的JSON文件应该有效

**报错信息**

修改  文件      src/pages/dddd/a.json
拷贝  文件      dist/pages/dddd/a.json

**系统信息**

👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/mobx: 1.3.0 => 1.3.0 
      @tarojs/mobx-h5: 1.3.0 => 1.3.0 
      @tarojs/mobx-rn: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-less: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/rn-runner: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0

**补充信息**

应该是taro的import json实现机制导致的，import json，会把json直接拷贝到代码里，但是之后json文件更新了，又没有进行替换，只做了json文件拷贝。

加油

**Comment by so-diao** [comment]
所以为什么不写成导出js呢

**Comment by BrookShuihuaLee** [comment]
> 所以你为什么不写成导出js呢

这个json是从其他地方下载的，会跑脚本去更新下载。taro既然已经支持import json文件了，那就尽量支持的好一点吧。

**Comment by so-diao** [comment]
小程序还不支持直接引入json，只能把json写在js里导出
所以只有把下载的json文件处理成js文件，`exports.default=json字符串`

**Comment by BrookShuihuaLee** [comment]
> 小程序还不支持直接引入json，只能把json写在js里导出
> 所以只有把下载的json文件处理成js文件，`exports.default=json字符串`

已经支持，只是不支持热更新。ctrl+c然后重新全量编译就好了

**Comment by so-diao** [comment]
原生小程序不支持，最终也还是要编译为原生的。
所以如果你想要多个地方共用一个json数据，只能是改成js。

**Comment by BrookShuihuaLee** [comment]
> 原生小程序不支持，最终也还是要编译为原生的。
> 所以如果你想要多个地方共用一个json数据，只能是改成js。

理解【多个地方共用一个json数据，只能是改成js。】但是这个bug描述的就是热更新的问题。和这个没有关系

**Comment by so-diao** [comment]
:sweat_smile:
