### ISSUE TITLE
1.3.0版本，Swiper组件中使用类函数组件绘制SwiperItem，在支付宝、百度小程序上表现异常

### ISSUE THREAD

**Issue by wenziguoguo** [NervJS/taro#3394]
**问题描述**
使用swiper组件，默认横向滑动，SwiperItem使用类函数组件
1、在微信上表现正常
2、在支付宝上表现为多个SwiperItem重叠
3、在百度上表现为多个SwiperItem纵向展现

**复现步骤**
测试下面的代码
```js
renderItem = () => {
    return (
      <Block>
        <SwiperItem>
          <View className='demo-text-1'>1</View>
        </SwiperItem>
        <SwiperItem>
          <View className='demo-text-2'>2</View>
        </SwiperItem>
        <SwiperItem>
          <View className='demo-text-3'>3</View>
        </SwiperItem>
      </Block>
    );
  }

  render() {
    return (
      <View className="s4s-page index-page">
        <Swiper
          className='test-h'
          indicatorColor='#999'
          indicatorActiveColor='#333'
          circular
          indicatorDots>
          {this.renderItem()}
        </Swiper>
      </View>
    )
  }
```
微信小程序结果：
![image](https://user-images.githubusercontent.com/47095059/59320422-e7cd0400-8d00-11e9-9500-8f5d55968ed1.png)

支付宝小程序结果：
![image](https://user-images.githubusercontent.com/47095059/59320603-8eb1a000-8d01-11e9-882f-a6531557da9e.png)

百度小程序结果：
![image](https://user-images.githubusercontent.com/47095059/59320716-e3edb180-8d01-11e9-9802-be13970bdca0.png)

**期望行为**
![image](https://user-images.githubusercontent.com/47095059/59320422-e7cd0400-8d00-11e9-9500-8f5d55968ed1.png)

**报错信息**
无

**系统信息**
👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
- 报错平台 [alipay、swan]，其他平台未尝试。

**Comment by luckyadam** [comment]
Swiper 和 SwiperItem 之间应该不能再套其他组件

**Comment by wenziguoguo** [comment]
可是我直接添加同样的Block，包裹几个SwipeItem没有问题啊，我看了下生成的小程序的xml文件是一样的。
```
<Swiper
          className='test-h'
          indicatorColor='#999'
          indicatorActiveColor='#333'
          circular
          indicatorDots>
          <Block>
            <Block>
              <SwiperItem>
                <View className='demo-text-1'>1</View>
              </SwiperItem>
              <SwiperItem>
                <View className='demo-text-2'>2</View>
              </SwiperItem>
              <SwiperItem>
                <View className='demo-text-3'>3</View>
              </SwiperItem>
            </Block>
          </Block>
        </Swiper>
```
