### ISSUE TITLE
taro暂不支持startPullDownRefresh（h5）

### ISSUE THREAD

**Issue by xiafengaha** [NervJS/taro#3397]
taro版本信息
👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.17 => 1.2.17 
      @tarojs/cli: 1.2.17 => 1.2.17 
      @tarojs/components: ^1.2.16 => 1.2.16 
      @tarojs/plugin-babel: 1.2.17 => 1.2.17 
      @tarojs/plugin-csso: 1.2.17 => 1.2.17 
      @tarojs/plugin-sass: 1.2.17 => 1.2.17 
      @tarojs/plugin-uglifyjs: 1.2.17 => 1.2.17 
      @tarojs/redux: ^1.2.17 => 1.2.17 
      @tarojs/redux-h5: ^1.2.17 => 1.2.17 
      @tarojs/rn-runner: ^1.2.17 => 1.2.17 
      @tarojs/router: ^1.2.17 => 1.2.17 
      @tarojs/taro: ^1.2.17 => 1.2.17 
      @tarojs/taro-alipay: ^1.2.17 => 1.2.17 
      @tarojs/taro-h5: ^1.2.17 => 1.2.17 
      @tarojs/taro-swan: ^1.2.17 => 1.2.17 
      @tarojs/taro-tt: ^1.2.17 => 1.2.17 
      @tarojs/taro-weapp: ^1.2.17 => 1.2.17 
      @tarojs/webpack-runner: 1.2.17 => 1.2.17 
      eslint-config-taro: 1.2.17 => 1.2.17 
      eslint-plugin-taro: 1.2.17 => 1.2.17 
      nervjs: ^1.3.9 => 1.3.13 
是因为版本问题还是什么吗？
项目代码：
`<ScrollView
            onScrollToUpper={this.ScrollToUpper}
            onScrollToLower={this.ScrollToLower}
            scrollY={this.state.scrollY}
            scrollWithAnimation
            style={{ height: getWindowHeight() }}
          >`
在ScrollToUpper函数中输出Taro.startPullDownRefresh(),提示暂不支持

**Comment by jinjinjin0731** [comment]
项目的依赖版本没有跟新，你这还是1.2.17。你只跟新了 CLI。  更新下项目的依赖版本即可

**Comment by xiafengaha** [comment]
感谢，我升级项目依赖后确实支持了，但是在相同ScrollToUpper函数中使用Taro.startPullDownRefresh()。没有下拉的效果。这个是为啥呢

**Comment by jinjinjin0731** [comment]
[ scroll-view](https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html)

![image](https://user-images.githubusercontent.com/17409735/59331476-a3ecf580-8d26-11e9-9b82-4710728fd6f1.png)

**Comment by xiafengaha** [comment]
谢谢
