### ISSUE TITLE
微信小程序转taro再转h5后，转后的h5在浏览器中无法正常预览

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3398]
**问题描述**
[问题描述：将现有微信小程序，taro convert转换成taro项目后，再build:h5，最终转成的h5项目在浏览器无法正常浏览]

**复现步骤**
[复现问题的步骤]
1. 试验了两个微官方的组件demo小程序项目，[picker](https://developers.weixin.qq.com/miniprogram/dev/component/picker.html)&[navigator](https://developers.weixin.qq.com/miniprogram/dev/component/navigator.html)
2. 小程序项目中执行taro convert，先将小程序转换成taro项目
3. 进入taroConvert目录，npm i 安装依赖；依赖安装完成后，npm run dev:h5运行h5项目
4. 页面无法正常预览，报错Nerv变量无定义；
![image](https://user-images.githubusercontent.com/13342245/59327357-d7765280-8d1b-11e9-926a-4088f995875c.png)
![image](https://user-images.githubusercontent.com/13342245/59327373-e78e3200-8d1b-11e9-9fad-50e826dad6ca.png)
5、如果是npm run build:h5，h5项目从入口文件index.html打开，index中引用的js和css路径不对，手动修改后，引入资源后，再报错第4步的错
![image](https://user-images.githubusercontent.com/13342245/59327471-39cf5300-8d1c-11e9-9a65-02d1bbda7351.png)
![image](https://user-images.githubusercontent.com/13342245/59327595-8f0b6480-8d1c-11e9-9ee9-8773a6aacdcf.png)

**期望行为**
[微信小程序转后的taro项目，再转换成h5项目，能够在浏览器正常预览]

**报错信息**
[已在复现步骤中贴图]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.0]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by li305263** [comment]
遇到了一样的问题.
System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 
      Yarn: 1.13.0
      npm: 6.4.1

**Comment by loosenRogers** [comment]
找到一个跟我一样的问题，小伙伴20多天前就提了[issue3158]((https://github.com/NervJS/taro/issues/3158))，现在还没解决

**Comment by jianguo1202** [comment]
appjs的Nave改成 Taro，或者在上面加入import Nerv from "nervjs"

**Comment by loosenRogers** [comment]
> appjs的Nave改成 Taro，或者在上面加入import Nerv from "nervjs"

这个手动可以解决问题，但是按理说应该转换过程中进行处理的，所以看issue还是留着

**Comment by loosenRogers** [comment]
1.3.2之后的版本，该问题已经修复了，不存在了
