### ISSUE TITLE
-webkit-box-orient: vertical; 打包后丢失了

### ISSUE THREAD

**Issue by liling0726** [NervJS/taro#3399]
**问题描述**
-webkit-box-orient: vertical; 打包后丢失了

```js

display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
```
打包后：

```js
    display: -webkit-box;
    -webkit-line-clamp: 2;
    overflow: hidden;
    text-overflow: ellipsis;
```
导致多行省略不生效

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro/issues/2947#issuecomment-500340231

**Comment by fenglui** [comment]
解决方案 使用autoprefixer开关
```
/*! autoprefixer: off */
-webkit-box-orient: vertical;
/* autoprefixer: on */
```

**Comment by liling0726** [comment]
> 解决方案 使用autoprefixer开关
> 
> ```
> /*! autoprefixer: off */
> -webkit-box-orient: vertical;
> /* autoprefixer: on */
> ```

目前是使用的这种方法，打包的时候就会报Second Autoprefixer control comment was ignored. Autoprefixer applies control comment to whole block, not to next rule的warningwarning

**Comment by guggit** [comment]
解决了吗，我也遇到同样的问题
