### ISSUE TITLE
H5底部导航已经选中的tab仍然可以点击刷新页面

### ISSUE THREAD

**Issue by dukanghui** [NervJS/taro#3402]
**问题描述**
[问题描述：H5底部导航已经选中的tab仍然可以点击刷新页面]

**复现步骤**
[复现问题的步骤]
1. 例如：当前tab页为 首页，点击首页tab图标，仍然刷新页面

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```

**期望行为**
[期望点击已经选中的tab 不刷新当前页面，或者有配置可选项]
（因为项目中涉及微信公众号分享，刷新页面会有影响）

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 👽 Taro v1.2.26


  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\user\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by wenxiayili** [comment]
> CC @Littly

请问这个问题解决了吗？

**Comment by dukanghui** [comment]
> > CC @Littly
> 
> 请问这个问题解决了吗？

不知道解决没有，用自定义底部导航吧

**Comment by wenxiayili** [comment]
> > > CC @Littly
> > 
> > 
> > 请问这个问题解决了吗？
> 
> 不知道解决没有，用自定义底部导航吧

在我的测试中，手机上是没问题的，模拟器（Chrome）中会有这个问题，您可以在真机上试试

**Comment by ZakaryCode** [comment]
可以升级版本
