### ISSUE TITLE
taro rn 找不到入口文件

### ISSUE THREAD

**Issue by yikalosi** [NervJS/taro#3403]
taro 版本1.3.0
在taro-native-shell react-native run-android 找不到 entry index.js

**Comment by YuanQuan** [comment]
需要修改壳子代码比如IOS的appDelegate.m文件
![image](https://user-images.githubusercontent.com/2345176/59397859-adc33700-8dc0-11e9-9364-d2893b87bedb.png)

**Comment by yikalosi** [comment]
>  需要修改壳子代码比如IOS的appDelegate.m文件
> ![图片](https://user-images.githubusercontent.com/2345176/59397859-adc33700-8dc0-11e9-9364-d2893b87bedb.png)

ios到是@"rn_temp/index",android不知道在哪里改

**Comment by Pines-Cheng** [comment]
我来 fix 一下  taro-native-shell

**Comment by yikalosi** [comment]
> 我来修一下taro-native-shell

大佬，安卓的修改了吗

**Comment by liukaixin01** [comment]
I have the same question

**Comment by liukaixin01** [comment]
@yikalosi https://github.com/NervJS/taro/issues/3546
