### ISSUE TITLE
1.3.0，使用yarn link链接第三方自定义包同步开发时，小程序端编译未将node_modules转换为npm

### ISSUE THREAD

**Issue by kooyooha** [NervJS/taro#3407]
**问题描述**
1.3.0最新版本，使用yarn link链接第三方自定义包同步开发时，小程序端编译未将node_modules转换为npm。小程序包括微信，支付宝及百度。尝试退回1.2.26版本恢复正常。
发现只要第三方包的目录中存在node_modules，同时该第三方包存在引入另一个包就能复现，编译日志未报错。非link通过yarn add的包没有问题。该问题导致无法link第三方包进行同步开发，望尽快解决，谢谢。

**编译后出错代码段（项目编译js）**
var _index4 = require("../npm/【第三方包名】/node_modules/【第三个包引入的另一个包名】/dist/index.js");

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0 => 1.3.0 
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-less: 1.3.0 => 1.3.0 
      @tarojs/plugin-sass: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/redux: 1.3.0 => 1.3.0 
      @tarojs/redux-h5: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0 
      react: ^16.8.6 => 16.8.6 
    npmGlobalPackages:
      typescript: 3.2.2

 - 报错平台  weapp，alipay，swan

**Comment by zzyhdu** [comment]
这个在1.3.9好像已经解决了
