### ISSUE TITLE
微信小程序真机调试报错

### ISSUE THREAD

**Issue by xuxiaoxiao312** [NervJS/taro#3412]
**问题描述**
微信小程序真机调试时每个组件和页面提示TypeError: Super expression must either be null or a function, not undefined

**复现步骤
我的页面源代码基本结构为
```js
import { View, Text } from '@tarojs/components';
import Taro, { Component } from '@tarojs/taro';

export default class inviteRule extends Component {
  constructor(){
    super(...arguments);
		this.state = {
		};
	}
}

```

**报错信息**
真机调试报错信息：
![image](https://user-images.githubusercontent.com/24541297/59401111-401d0800-8dcc-11e9-986f-b8eacd33fa63.png)
![image](https://user-images.githubusercontent.com/24541297/59401133-4f9c5100-8dcc-11e9-98c0-424dcdc12ce0.png)
报错详情：
![image](https://user-images.githubusercontent.com/24541297/59401186-7fe3ef80-8dcc-11e9-8041-de467c4794b7.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
![image](https://user-images.githubusercontent.com/24541297/59401212-8f633880-8dcc-11e9-8a49-51da5f765e22.png)

**Comment by Chen-jj** [comment]
@xuxiaoxiao312 升级到 1.3.0 再试试

**Comment by KinoshitaHanson** [comment]
@Chen-jj 
我是1.3版本，也有这个问题 ，在微信小程序模拟器里可以正常调试、开发， 但是真机调试就会出现如下错误， 真机预览也是。
![image](https://user-images.githubusercontent.com/18358711/59487079-2653f180-8eae-11e9-9df9-8bd2af3db3bd.png)
![image](https://user-images.githubusercontent.com/18358711/59487109-3ec40c00-8eae-11e9-97db-be25ca043a54.png)
![image](https://user-images.githubusercontent.com/18358711/59487193-759a2200-8eae-11e9-93a6-c96750c5dec9.png)

**Comment by Chen-jj** [comment]
@KinoshitaHanson 你的项目真机调试并没有报错，Taro v1.3.2。

![image](https://user-images.githubusercontent.com/11807297/59751090-81248900-92b2-11e9-929f-dff726a6b72c.png)

@xuxiaoxiao312 @KinoshitaHanson 建议检查一下 Taro 版本，还有手机上微信版本需要更新，再或者使用多几台手机再测试一下。

**Comment by xuxiaoxiao312** [comment]
升级到1.3.2后问题解决了
