### ISSUE TITLE
Taro + ts  Taro版本由1.2.26升级至1.3.0后，编译成小程序报错

### ISSUE THREAD

**Issue by misszoessmile** [NervJS/taro#3413]
**问题描述**
将Taro升级至1.3.0后，执行npm run dev:weapp，用微信开发者工具打开dist目录，控制台显示报错，项目直接打不开。

**报错信息**
![image](https://user-images.githubusercontent.com/35720631/59402290-372e3580-8dd0-11e9-8ed3-a1ad8f888361.png)
![image](https://user-images.githubusercontent.com/35720631/59402318-59c04e80-8dd0-11e9-8d3b-33e1fbf7028c.png)
![image](https://user-images.githubusercontent.com/35720631/59402338-7492c300-8dd0-11e9-85f2-767527fcab81.png)

**系统信息**
![image](https://user-images.githubusercontent.com/35720631/59402385-9ee48080-8dd0-11e9-91e6-1d5af3205479.png)

**Comment by yuche** [comment]
你的项目依赖没有升级
