### ISSUE TITLE
taro获取子组件props之后值为空

### ISSUE THREAD

**Issue by 1Crazy** [NervJS/taro#3414]
**问题描述**
taro子组件获取父组件内容值为空
**复现步骤**
[复现问题的步骤]

父组件
```
<publicList 
            list={222}
          />
```

子组件
```
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class publicList extends Component {
  render () {
    let {list} = this.props
    console.log(this,'this')
    console.log(list)
    return (
      <View className='publicList'>
        {list}
      </View>
    )
  }
}
```

**期望行为**
希望子组件有值

**报错信息**

打印结果

![image](https://user-images.githubusercontent.com/24940058/59402888-ea982980-8dd2-11e9-8b05-f03eb672b28f.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10] windows7
 - Taro 版本 [e.g. v.0.0.64]  @tarojs/cli@1.3.0-beta.3
 - Node.js 版本 [e.g. v9.0.0] v10.15.3
 - 报错平台 [h5, weapp] weapp

**Comment by Chen-jj** [comment]
@1Crazy 升级到 1.3.0 再试试。

**Comment by 1Crazy** [comment]
晚上试试，谢了

**Comment by 1Crazy** [comment]
还是不行，是空值，已经升级到1.3.0

**Comment by 1Crazy** [comment]
引入子组件的方式我是：  vscode提示我——已声明“publicList”，但从未读取其值。
```
import publicList from '../../components/publicList'
```

**Comment by Chen-jj** [comment]
@1Crazy 建议 init 个新项目，或者找找 github 上的实际项目看看。这是最基本的功能，也没有其他同学反馈同样情况，应该是没问题的。

**Comment by Chen-jj** [comment]
呃。。自定义组件大写。。。。h5 标签才小写，React 的约定。

**Comment by 1Crazy** [comment]
可以了。。。谢了
