### ISSUE TITLE
打包h5时，webpack.resolve.mainFields的问题

### ISSUE THREAD

**Issue by seaheart** [NervJS/taro#3415]
**问题描述**
webpack brower端默认mainFields是
mainFields: ['browser', 'module', 'main']
 
有些包，比如isomorphic-fetch。brower端的js是在package.json的browser字段

但是taro 1.2.26的生成出来的webpack配置是
 mainFields: [ 'main:h5', 'main', 'module' ]

所以打包h5的时候，是不是要考虑brower字段

**Comment by Littly** [comment]
有道理，可以加上

**Comment by wangking873** [comment]
h5 webpack配置  mainFields: ['browser', 'module', 'main']
小程序webpack配置 mainFields: ['taromini', 'module', 'main']

是否可以这样区分，package.json有taromini导出的库说明支持taro引入

main:h5  太奇怪了

**Comment by wangking873** [comment]
"main": "lib/index.js",  目标环境 node.js
"browser": "es/index.js",  目标环境 浏览器
"taromini": "mini/index.js",  目标环境 taro小程序
