### ISSUE TITLE
在使用组件的情况下，组件内部的 width 使用 100% 计算不正确。

### ISSUE THREAD

**Issue by zhang704** [NervJS/taro#3417]
**问题描述**
在使用组件的情况下，组件内部的 width 使用 100% 计算不正确。

**复现步骤**
[复现问题的步骤]
1. 外部的列表将 style 设为 width: calc(100% - 50px)。
2. 组件内部的width: calc((100% - 20px) / 2)，宽度与外部宽度不符。

**期望行为**
列表中的每个组件宽度正确展示。

**报错信息**
![image](https://user-images.githubusercontent.com/18161513/59412839-ed097c00-8df0-11e9-8d21-40319c09a11c.png)
![image](https://user-images.githubusercontent.com/18161513/59412853-f4c92080-8df0-11e9-9b47-76d910728e4a.png)
![image](https://user-images.githubusercontent.com/18161513/59412865-fa266b00-8df0-11e9-823d-1eb2dd40b48b.png)
![image](https://user-images.githubusercontent.com/18161513/59413018-512c4000-8df1-11e9-937d-5c0878894633.png)
tips: 红框为正确展示范围。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0]
 - Node.js 版本 [e.g. v10.15.2]
 - 报错平台 [weapp]

**Comment by xhwgood** [comment]
大半年的时间过去了，楼主解决了吗？
