### ISSUE TITLE
hooks不支持全局样式

### ISSUE THREAD

**Issue by leeviok** [NervJS/taro#3419]
![微信图片_20190613164113](https://user-images.githubusercontent.com/25154944/59417574-1a0e5c80-8dfa-11e9-81a7-dee1319562ff.png)

版本：1.3.0
函数式组件，想要引入全局样式
这两种设置方式都试过，都不成功

希望官方能够支持此重要功能！

**Comment by luckyadam** [comment]
你写错了，是 `MainClass.options`

**Comment by leeviok** [comment]
> 你写错了，是 `MainClass.options`

是的，现在可以了，谢谢
