### ISSUE TITLE
taro升级1.3.0版本后，编译成小程序，子组件接收样式失效

### ISSUE THREAD

**Issue by misszoessmile** [NervJS/taro#3420]
**问题描述**
taro版本由1.2.26升级至1.3.0，也更新了项目依赖，按照文档使用 externalClasses 定义段定义若干个外部样式类，发现样式不生效。

**复现步骤**
[复现问题的步骤]
1. taro update self
2. taro update project
3. npm run dev:weapp
子组件：
![image](https://user-images.githubusercontent.com/35720631/59418543-c6047780-8dfb-11e9-8bc2-9319d4fb68a5.png)
父组件：
![image](https://user-images.githubusercontent.com/35720631/59418786-390dee00-8dfc-11e9-83f8-525a073bb483.png)
父组件样式表：
![image](https://user-images.githubusercontent.com/35720631/59418905-6d81aa00-8dfc-11e9-8a4b-d41cba658114.png)

**期望行为**
能实现子组件使用父组件的样式

**报错信息**
升级前：
![image](https://user-images.githubusercontent.com/35720631/59418311-660dd100-8dfb-11e9-963a-02a470509063.png)
升级后：
![image](https://user-images.githubusercontent.com/35720631/59418325-6d34df00-8dfb-11e9-87b8-ec706c510fb1.png)

**系统信息**
Taro CLI 1.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.4.0 - C:\Program Files\nodejs\npm.CMD

**Comment by Garfield550** [comment]
Dup #3080

**Comment by Garfield550** [comment]
Dup #3080
