### ISSUE TITLE
插件配置路径问题

### ISSUE THREAD

**Issue by patchBig** [NervJS/taro#3422]
在 config/index.js 配置如下，
```
plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env']
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread',
        ['./tools/babel-plugin-transform-image-to-url', {
            publicPath: 'http://127.0.0.1:9000/',
            staticDirectory: 'dist/static'
          }
        ]
      ]
    }
  },
```

发现在编译 js 的时候，都会去找相对路径 `./tools/babel-plugin-transform-image-to-url`，导致编译报错。

报错信息如下：

![image](https://user-images.githubusercontent.com/25219300/59430322-8dbd6300-8e14-11e9-80f0-1c957d0d6abc.png)

目录结构如下：

![image](https://user-images.githubusercontent.com/25219300/59430381-b180a900-8e14-11e9-86c1-36cf414b08d1.png)

**Comment by luckyadam** [comment]
写成绝对路径试试

**Comment by patchBig** [comment]
> 写成绝对路径试试

嗯嗯 可以的 
thank you
