### ISSUE TITLE
taro+typescript+mobx 初始化项目 taro doctor 后出现  54:22 error Parsing error: Unexpected token, expected ";"

### ISSUE THREAD

**Issue by yikalosi** [NervJS/taro#3425]
版本1.3.0-beta.8
init 一个demo taro+typescript+mobx
问题 taro doctor后出现

  54:22  error  Parsing error: Unexpected token, expected ";"

  52 | }
  53 |
> 54 | export default Index as ComponentType
     |                      ^
  55 |

✖ 1 problem (1 error, 0 warnings)

**Comment by luckyadam** [comment]
贴一下报错页面的完整代码

**Comment by yikalosi** [comment]
import { ComponentType } from 'react'
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { observer, inject } from '@tarojs/mobx'

import './index.scss'

type PageStateProps = {
  counterStore: {
    counter: number,
    increment: Function,
    decrement: Function,
    incrementAsync: Function
  }
}

interface Index {
  props: PageStateProps;
}

@inject('counterStore')
@observer
class Index extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentWillReact () {
    console.log('componentWillReact')
  }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  increment = () => {
    const { counterStore } = this.props
    counterStore.increment()
  }

  decrement = () => {
    const { counterStore } = this.props
    counterStore.decrement()
  }

  incrementAsync = () => {
    const { counterStore } = this.props
    counterStore.incrementAsync()
  }

  render () {
    const { counterStore: { counter } } = this.props
    return (
      <View className='index'>
        <Button onClick={this.increment}>+</Button>
        <Button onClick={this.decrement}>-</Button>
        <Button onClick={this.incrementAsync}>Add Async</Button>
        <Text>{counter}</Text>
      </View>
    )
  }
}

export default Index  as ComponentType

**Comment by liu-dongyu** [comment]
下面两种写法`taro doctor`也是提示`Parsing error: Unexpected token` 
```javascript
interface Itest {
  id: string
  name: string
}
```

```javascript
let someValue: any = 'this is a string'
let strLength: number = (someValue as string).length
```

**Comment by hnsylitao** [comment]
+1 碰到相同的问题，是babel-eslint的问题~

**Comment by BennyEu** [comment]
请问这个问题解决了吗?

**Comment by fishead** [comment]
临时解决方案。

1. 安装开发依赖
```shell
yarn add @typescript-eslint/eslint-plugin --dev
```

2. 编辑 .eslintrc 文件，添加 overrides 项，代码内容来自 https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js#L55

完整的 .eslintrc，rules 可以自行调整
```js
module.exports = {
  extends: ["taro"],
  parser: "babel-eslint",
  rules: {
    "no-unused-vars": ["error", { "varsIgnorePattern": "Taro" }],
    "react/jsx-filename-extension": [
      1,
      { "extensions": [".js", ".jsx", ".tsx"] }
    ]
  },
  overrides: [
    {
      files: ['**/*.ts?(x)'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },

        // typescript-eslint specific options
        warnOnUnsupportedTypeScriptVersion: true,
      },
      plugins: ['@typescript-eslint'],
      // If adding a typescript-eslint version of an existing ESLint rule,
      // make sure to disable the ESLint rule here.
      rules: {
        // TypeScript's `noFallthroughCasesInSwitch` option is more robust (#6906)
        'default-case': 'off',
        // 'tsc' already handles this (https://github.com/typescript-eslint/typescript-eslint/issues/291)
        'no-dupe-class-members': 'off',
        // 'tsc' already handles this (https://github.com/typescript-eslint/typescript-eslint/issues/477)
        'no-undef': 'off',

        // Add TypeScript specific rules (and turn off ESLint equivalents)
        '@typescript-eslint/no-angle-bracket-type-assertion': 'warn',
        'no-array-constructor': 'off',
        '@typescript-eslint/no-array-constructor': 'warn',
        '@typescript-eslint/no-namespace': 'error',
        'no-use-before-define': 'off',
        '@typescript-eslint/no-use-before-define': [
          'warn',
          {
            functions: false,
            classes: false,
            variables: false,
            typedefs: false,
          },
        ],
        'no-unused-vars': 'off',
        '@typescript-eslint/no-unused-vars': [
          'warn',
          {
            args: 'none',
            ignoreRestSiblings: true,
          },
        ],
        'no-useless-constructor': 'off',
        '@typescript-eslint/no-useless-constructor': 'warn',
      },
    },
  ],
};
```
