### ISSUE TITLE
可不可以自定义支付宝小程序的导航条

### ISSUE THREAD

**Issue by fanchaot** [NervJS/taro#3427]
**问题描述**
有没有办法 支付宝小程序 可以像微信小程序 百度小程序一样 设置
 > navigationStyle: 'custom'   来自定义导航条

这是百度小程序
![image](https://user-images.githubusercontent.com/32870484/59486371-ae84c780-8eab-11e9-9914-4414e1faa9ff.png)

这是支付宝小程序
![image](https://user-images.githubusercontent.com/32870484/59486454-e8ee6480-8eab-11e9-9ddc-cdc989d890c4.png)

**Comment by Chen-jj** [comment]
@fanchaot https://docs.alipay.com/mini/api/xwq8e6
