### ISSUE TITLE
h5 下 scrollview 标签 onTouchMove 无效

### ISSUE THREAD

**Issue by Zigei** [NervJS/taro#3428]
**问题描述**
h5 下 scrollview 标签 onTouchMove 无效
```js
<ScrollView style={{height:"200px"}} onTouchMove={(e)=>{console.log(1111)}}>
......
</ScrollView>
```

**期望行为**
允许捕捉到事件  下拉刷新已经失效了

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.0]
 - 报错平台 [h5]

**Comment by jinjinjin0731** [comment]
已修复~
