### ISSUE TITLE
preload太快导致showToast无法显示

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#3429]
![image](https://user-images.githubusercontent.com/3361732/59491649-c4998480-8eb9-11e9-9f8c-67ea8bcd3246.png)

A页面点击跳转到B页面，B页面componentWillPreload加载数据，用户数据异常，需要showToast给用户，并返回A页面
现在A页面点击基本就闪下，还在A页面，showToast提示看不到
视觉上进不去B页面，速度太快了

**Comment by Chen-jj** [comment]
@jpdan 是因为你立即重定向导致。showToast.then => switchTab
