### ISSUE TITLE
npm run dev:h5 报错，原因是项目的父路径中包含 src

### ISSUE THREAD

**Issue by leizongmin** [NervJS/taro#3431]
**问题描述**

如果项目所在的父路径包含 `src`，则构建 h5 时会报错。

**复现步骤**

1. `cd ~/src`
2. `taro init xxx`
3. `cd xxx`
4. `npm run dev:h5`

**期望行为**

输出 `✅  Compiled successfully!`

**报错信息**

```
👽 Taro v1.3.0

开始编译项目 xxx
创建  发现文件  src/app.less
创建  发现文件  src/app.tsx
创建  发现文件  src/index.html
创建  发现文件  src/pages/index/index.less
创建  发现文件  src/pages/index/index.tsx


ℹ️  Listening at http://127.0.0.1:10086/

监听文件修改中...

🙅   Failed to compile.

multi (webpack)-dev-server/client?http://127.0.0.1:10086 (webpack)/hot/dev-server.js ./.temp/app.js
Module not found: Can't resolve '~/src/xxx/.temp/app.js' in '~/src/xxx'
```

**系统信息**

```
👽 Taro v1.3.0


  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0 => 1.3.0
      @tarojs/plugin-babel: 1.3.0 => 1.3.0
      @tarojs/plugin-csso: 1.3.0 => 1.3.0
      @tarojs/plugin-less: 1.3.0 => 1.3.0
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0
      @tarojs/router: 1.3.0 => 1.3.0
      @tarojs/taro: 1.3.0 => 1.3.0
      @tarojs/taro-alipay: 1.3.0 => 1.3.0
      @tarojs/taro-h5: 1.3.0 => 1.3.0
      @tarojs/taro-swan: 1.3.0 => 1.3.0
      @tarojs/taro-tt: 1.3.0 => 1.3.0
      @tarojs/taro-weapp: 1.3.0 => 1.3.0
      @tarojs/webpack-runner: 1.3.0 => 1.3.0
      eslint-config-taro: 1.3.0 => 1.3.0
      eslint-plugin-taro: 1.3.0 => 1.3.0
      nervjs: ^1.4.0 => 1.4.0
```

**补充信息**

在 `taro-cli` 模块的 `src/h5/index.ts` 文件的 `getDist()` 方法内，有这么一行 `const distDirname = dirname.replace(sourceRoot, tempDir)`，其中 `sourceRoot` 的值是 `src`，`tempDir` 的值是 `.temp`，如果 `dirname`（指当前要处理的文件的完整路径，比如 `src/app.js`）的父路径包含了 `src`，比如 `~/src/xxx/src/app.js`，则会导致第一个 `src` 被替换了，生成了一个非预期的路径，最终导致报错 `Module not found: Can't resolve '~/src/xxx/.temp/app.js' in '~/src/xxx'`。

我尝试在项目配置文件 `config/index.js` 中将 `sourceRoot` 和 `outputRoot` 改为绝对路径，又会引发其他的报错，可以判断此两项属性是不能写成绝对路径的。

如果将 `~/src/xxx` 移动到其他目录，比如 `~/hello/xxx`，则再次执行 `npm run dev:h5` 会成功。

源码位置：https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/h5/index.ts#L1187

**Comment by Littly** [comment]
有道理。直接replace有点贪图方便了

**Comment by WangxinsHub** [comment]
希望解决
