### ISSUE TITLE
h5 build后页面不能正常访问报错Uncaught Invariant Violation: Can not find proper registered route for '/static/h5/index.html' lib.dll.js:1

### ISSUE THREAD

**Issue by xiongmao911** [NervJS/taro#3434]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
dev没任何问题，但放到线上访问/static/h5/index.html文件，页面就打不开，报错Uncaught Invariant Violation: Can not find proper registered route for '/static/h5/index.html' 

**复现步骤**
[复现问题的步骤]
1、更改了配置router, basename: '/static/h5/index.html'

![1560501236711](https://user-images.githubusercontent.com/32010968/59495685-6e7d0f00-8ec2-11e9-906c-d3f7080de76f.jpg)

.temp/app.js

import Taro, { Component } from "@tarojs/taro-h5";
import { Provider } from "@tarojs/mobx-h5";
import '@tarojs/async-await';

import counterStore from "./store/counter";
// import './custom-theme.scss'
import './app.less';

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

import Nerv from "nervjs";
import { Router, createHistory, mountApis } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});

const _taroHistory = createHistory({
  mode: "browser",
  basename: "/static/h5/index.html",
  customRoutes: {
    "/pages/packageSpecial/index": "/package",
    "/pages/coupons/index": "/coupons"
  },
  firstPagePath: "/pages/packageSpecial/index"
});

mountApis(_taroHistory);
const store = {
  counterStore
};

class App extends Component {

  config = {
    pages: ["/pages/packageSpecial/index", "/pages/coupons/index"],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  };

  componentDidMount() {
    this.componentDidShow();
  }

  componentDidShow() {}

  componentDidHide() {}

  componentDidCatchError() {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Provider store={store}>
                  
              <Router history={_taroHistory} routes={[{
        path: '/pages/packageSpecial/index',
        componentLoader: () => import( /* webpackChunkName: "packageSpecial_index" */'./pages/packageSpecial/index'),
        isIndex: true
      }, {
        path: '/pages/coupons/index',
        componentLoader: () => import( /* webpackChunkName: "coupons_index" */'./pages/coupons/index'),
        isIndex: false
      }]} customRoutes={{
        "/pages/packageSpecial/index": "/package",
        "/pages/coupons/index": "/coupons"
      }} />
              
                </Provider>;
  }

  componentWillUnmount() {
    this.componentDidHide();
  }

  constructor(props, context) {
    super(props, context);
    Taro._$app = this;
  }

}

Nerv.render(<App />, document.getElementById('app'));
![1560501491268](https://user-images.githubusercontent.com/32010968/59495872-d895b400-8ec2-11e9-93ee-3bde45790d4f.jpg)

![1560501419834](https://user-images.githubusercontent.com/32010968/59495801-adab6000-8ec2-11e9-957a-d29305b86c3a.jpg)

[代码只贴截图，不贴文字会被视为无效issue]

```js

// ```js
config/prod.js

module.exports = {
  env: {
    NODE_ENV: '"production"'
  },
  defineConstants: {
  },
  weapp: {},
  h5: {
    publicPath: './',
    /**
     * 如果h5端编译后体积过大，可以使用webpack-bundle-analyzer插件对打包体积进行分析。
     * 参考代码如下：
     * webpackChain (chain) {
     *   chain.plugin('analyzer')
     *     .use(require('webpack-bundle-analyzer').BundleAnalyzerPlugin, [])
     * }
     */
    esnextModules: ['taro-ui'],
  }
}
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
怎么修改才能正常方位

**报错信息**

![1560496630670](https://user-images.githubusercontent.com/32010968/59496066-3e823b80-8ec3-11e9-85a6-86ecb7e83ac0.jpg)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/mobx: 1.3.0 => 1.3.0 
      @tarojs/mobx-h5: 1.3.0 => 1.3.0 
      @tarojs/mobx-rn: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-less: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/rn-runner: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0 
    npmGlobalPackages:
      typescript: 3.3.3333

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Littly** [comment]
修改下格式吧 这格式没几个人看得懂了
