### ISSUE TITLE
h5上传图片，文件名没有后缀，类型也不对。

### ISSUE THREAD

**Issue by Fntys** [NervJS/taro#3436]
**问题描述**
![image](https://user-images.githubusercontent.com/13896710/59500604-5e6a2d00-8ecc-11e9-830e-d0f567edb036.png)

**复现步骤**
用的Taro UI的ImagePicker组件
![image](https://user-images.githubusercontent.com/13896710/59500694-8b1e4480-8ecc-11e9-8944-8ccd546c6131.png)

**期望行为**
![image](https://user-images.githubusercontent.com/13896710/59500722-9bceba80-8ecc-11e9-8c97-fbc1d7fbb8c7.png)

**系统信息**
  Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - D:\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\nodejs\npm.CMD

**Comment by tourze** [comment]
需要自己根据mime type来生成个随机文件名。。。这个在微信群里有反馈过

**Comment by xiaozhouwu** [comment]
> 需要自己根据mime type来生成个随机文件名。。。这个在微信群里有反馈过

具体要怎么操作？

**Comment by tourze** [comment]
> > 需要自己根据mime type来生成个随机文件名。。。这个在微信群里有反馈过
> 
> 具体要怎么操作？

```
import extName from 'ext-name';

          // TODO 现在 chooseImage 还不能返回完整的文件名，所以只能暂时这样fix

          try {
            const extInfo = extName.mime(tempFile.type);
            fileName = `temp.${extInfo[0].ext}`;
          } catch (e) {
            console.warn('error',e);
          }
```
