### ISSUE TITLE
企业微信的支持？ 

### ISSUE THREAD

**Issue by nevernet** [NervJS/taro#3438]
同 #3171 ， 虽然可以原生使用， 但是有考虑Taro做这部分封装吗？

**Comment by nevernet** [comment]
any news?

**Comment by GarfieldLucy** [comment]
any news？

**Comment by Chen-jj** [comment]
> Stage: Landed at 3.1.0-beta.0
> Taro CLI 插件：[@tarojs/plugin-platform-weapp-qy](https://github.com/NervJS/taro-plugin-platform-weapp-qy)（v3.1+）

**Comment by nevernet** [comment]
是否考虑在1.0里面支持企业微信？
