### ISSUE TITLE
在使用Taro.loadFontFace遇到了报错

### ISSUE THREAD

**Issue by Barretem** [NervJS/taro#344]
**问题描述**
在打印Taro.loadFontFace是能够获取到对应的函数的，当进行传参操作的时候程序出现了报错。

**复现步骤**
[复现问题的步骤]
在index.js中加入的componentWillMount声明周期中加入以下代码：
Taro.loadFontFace({
      family: 'Bitstream Vera Serif Bold',
      source: 'url("https://developer.mozilla.org/@api/deki/files/2934/=VeraSeBd.ttf")',
    });

**期望行为**
方法可以正确调用

**报错信息**
![image](https://user-images.githubusercontent.com/20395024/42856073-16a42b84-8a76-11e8-91b0-d11556f3a28a.png)

**系统信息**
 - 操作系统: [mac10.12.6]
 - Taro 版本 [v.0.0.69]
 - Node.js 版本 [v8.9.1]

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/43082226-1d42ef8a-8ec6-11e8-8086-798e9423a581.png)

**Comment by Barretem** [comment]
已解决，就是基础库版本问题。谢谢Taro团队的回复！

**Comment by zpzxgcr** [comment]
![image](https://user-images.githubusercontent.com/16409424/55242795-ed29bf00-5278-11e9-8d06-0e4aea412e2d.png)
我这里提示没有这个方法 楼主帮我看些 谢了
