### ISSUE TITLE
Taro 从1.3.0-beta5升级到1.3.0正式版，dist目录没有子目录了？

### ISSUE THREAD

**Issue by shenghanqin** [NervJS/taro#3440]
**问题描述**
1.3.0正式版之前的版本存在dist/tt或者dist/weapp，现在只有dist目录了？

**复现步骤**

**期望行为**

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  Mac
 - Taro 版本  1.3.0
 - Node.js 版本 v10.14.1
 - 报错平台 

**补充信息**

**Comment by Littly** [comment]
### 多端同步调试

~~从 1.3 版本开始，项目编译后的结果不再直接放在 `dist` 目录下，而是会在 `dist` 目录下创建一个与编译的目标平台名同名的目录，并将结果放在这个目录下，例如编译到微信小程序，最终结果是在 `dist/weapp` 目录下，这样做的好处是，各个平台使用独立的目录互不影响，从而达到多端同步调试的目的。~~

1.3.5-beta.5 开始恢复之前的编译操作，文件会直接编译到 config 中配置的 `outputRoot` 目录下，如果需要多端同时调试，可以修改配置为

```
outputRoot: `dist/${process.env.TARO_ENV}`
```

https://github.com/NervJS/taro/issues/2947#issue-440404914
