### ISSUE TITLE
Textarea 组件 iOS 真机上 touch 事件不能触发

### ISSUE THREAD

**Issue by ZhouChilly** [NervJS/taro#3441]
**问题描述**
Textarea 组件 iOS 真机上 touch 事件不能触发

**复现步骤**
如题

**期望行为**
Textarea 在 iOS 真机上能像触发 touch 事件

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14]
 - Taro 版本 [1.2.26]
 - Node.js 版本 [10.15]
 - 报错平台 [weapp]

**补充信息**
[小程序开发者平台对应的问题](https://developers.weixin.qq.com/community/develop/doc/000a02c61e84183ca878a939851c00?_at=1558915200022)

**Comment by Pines-Cheng** [comment]
哪个端？

**Comment by ZhouChilly** [comment]
微信小程序，报错平台有写 weapp

**Comment by jinjinjin0731** [comment]
贴一下你的代码？
