### ISSUE TITLE
@tarojs/redux 的 types 文件需要修改

### ISSUE THREAD

**Issue by PoiScript** [NervJS/taro#3442]
**问题描述**

@tarojs/redux 的 types 文件在 connect 函数的[相关定义](https://github.com/NervJS/taro/blob/a9b8fa72bd7d8ec3d923f2c64e126061af5b3331/packages/taro-redux/types/index.d.ts#L21-L29)中有问题：

```typescript
export type InferableComponentEnhancerWithProps<IInjectedProps, INeedsProps> =
    <IComponent extends ComponentClass<IInjectedProps & INeedsProps>>(component: IComponent) => IComponent

export interface IConnect {
  <IStateProps = {}, IDispatchProps = {}, IOwnProps = {}, IStore = any>(
      mapStateToProps?: MapStateToPropsParam<IStateProps, IOwnProps, IStore>,
      mapDispatchToProps?: MapDispatchToPropsParam<IDispatchProps, IOwnProps>,
  ): InferableComponentEnhancerWithProps<IStateProps & IDispatchProps, IOwnProps>
}
```
其中 `InferableComponentEnhancerWithProps` 接受的参数和返回值都是 `IComponent` ，而实际上应该是不同的，因为 `IInjectedProps` 是经过函数之后注入的 props 而 `INeedsProps` 是本来就存在的 props。

应该改成类似以下的定义：

```ts
export type InferableComponentEnhancerWithProps<IInjectedProps, INeedsProps> =
    <IComponent extends ComponentClass<IInjectedProps & INeedsProps>>(component: IComponent)
        => ComponentClass<INeedsProps>
```

可以参考 `@types/react-redux` 的[定义](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0182c2730f9d4adb2e6a1216203864c7501ec916/types/react-redux/v5/index.d.ts#L46-L50)：

```ts
// Injects props and removes them from the prop requirements.
// Will not pass through the injected props if they are passed in during
// render. Also adds new prop requirements from TNeedsProps.
export interface InferableComponentEnhancerWithProps<TInjectedProps, TNeedsProps> {
    <P extends TInjectedProps>(
        component: Component<P>
    ): ComponentClass<Omit<P, keyof TInjectedProps> & TNeedsProps> & {WrappedComponent: Component<P>}
}
```

**Comment by Pines-Cheng** [comment]
欢迎 PR 咯～

**Comment by vonweb** [comment]
返回值应该是`ComponentType`类型的
`type ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>`

**Comment by l1Dan** [comment]
![WechatIMG35](https://user-images.githubusercontent.com/7961100/64558908-9b34ab80-d377-11e9-94b7-5f9844c05cd3.jpeg)
同样有这个需求，希望官方支持下

**Comment by engineerzy** [comment]
从@tarojs/redux引入的connect，在连接函数式组件时，InferableComponentEnhancerWithProps函数返回值应该是ComponentType类型，而不是只有ComponentClass类型，不然会一直提示类型错误

**Comment by Chen-jj** [comment]
Taro 3 可以直接使用 redux，不需要引入 @tarojs/redux 了
