### ISSUE TITLE
Mobx另一种写法不更新

### ISSUE THREAD

**Issue by lyz1991** [NervJS/taro#3443]
<img width="790" alt="WechatIMG33" src="https://user-images.githubusercontent.com/15042461/59562884-04509f80-9065-11e9-8c1f-d10bda59a03a.png">
<img width="315" alt="WechatIMG34" src="https://user-images.githubusercontent.com/15042461/59562885-04e93600-9065-11e9-800b-60dafeea7ff9.png">
点击之后发现，name有输出，但是页面不更新

**Comment by lyz1991** [comment]
我知道了，observer应该放在inject上面，但是Taro官方文档写的？？
<img width="658" alt="WechatIMG35" src="https://user-images.githubusercontent.com/15042461/59562929-e3d51500-9065-11e9-8fdf-ac0d4024cab6.png">

**Comment by lyz1991** [comment]
但是放到上面，mobx报warning

**Comment by lyz1991** [comment]
这个问题怎么说？

**Comment by nanjingboy** [comment]
@lyz1991 因为 observer 监听的是 render（小程序是 _createData） 方法，你在 inject 中对 user 对象进行了引用，按照 inject > observer 的顺序，name 并不是可观察对象，所以不会触发，而 observer > inject 的顺序，这个也只是在小程序中恰好能够正常触发是因为 inject 对 _createData 方法做了修改 props 的操作，而 h5 跟 rn 是不会触发的。

解决方案：在 render 中对可观察对象进行引用。

**Comment by lyz1991** [comment]
> @lyz1991 因为 observer 监听的是 render（小程序是 _createData） 方法，你在 inject 中对 user 对象进行了引用，按照 inject > observer 的顺序，name 并不是可观察对象，所以不会触发，而 observer > inject 的顺序，这个也只是在小程序中恰好能够正常触发是因为 inject 对 _createData 方法做了修改 props 的操作，而 h5 跟 rn 是不会触发的。
> 
> 解决方案：在 render 中对可观察对象进行引用。

我第一种写法，在render里有引用的

**Comment by lyz1991** [comment]
> @lyz1991 因为 observer 监听的是 render（小程序是 _createData） 方法，你在 inject 中对 user 对象进行了引用，按照 inject > observer 的顺序，name 并不是可观察对象，所以不会触发，而 observer > inject 的顺序，这个也只是在小程序中恰好能够正常触发是因为 inject 对 _createData 方法做了修改 props 的操作，而 h5 跟 rn 是不会触发的。
> 
> 解决方案：在 render 中对可观察对象进行引用。

<img width="673" alt="WechatIMG1" src="https://user-images.githubusercontent.com/15042461/60493379-43c2f100-9cdf-11e9-9432-6e2544bca28c.png">
<img width="430" alt="WechatIMG2" src="https://user-images.githubusercontent.com/15042461/60493380-445b8780-9cdf-11e9-8cd6-3532b410edc1.png">
<img width="938" alt="WechatIMG3" src="https://user-images.githubusercontent.com/15042461/60493471-779e1680-9cdf-11e9-9cba-73f296916b0b.png">
但是在非小程序项目里，这样写法是没问题的

**Comment by nanjingboy** [comment]
@lyz1991 这个限制是针对小程序来说的，如果你的应用不需要跑在小程序里可以忽视它，不然的话还是按照规则玩吧
