### ISSUE TITLE
支付宝真机分包 跳转报错 

### ISSUE THREAD

**Issue by shufangjian** [NervJS/taro#3445]
支付宝真机报错，模拟器反而正确

**报错信息**
![image](https://user-images.githubusercontent.com/7800305/59573308-eaef3800-90e4-11e9-8a3c-7f36b11bb213.png)

**系统信息**
 - Taro 版本 [1.3.0-beta.6]
 - 报错平台 [支付宝小程序]

**Comment by ooxx87** [comment]
哎呀我们也发现redux，dva在支付宝真机的这个问题了，求解决

**Comment by luckyadam** [comment]
不分包会报错么

**Comment by shufangjian** [comment]
不分包 没有问题

**Comment by sanye33** [comment]
我们这边是支付宝模拟器正常，真机进入分包页面就报这个错误

**Comment by shufangjian** [comment]
![image](https://user-images.githubusercontent.com/7800305/60073741-d4d02000-9753-11e9-8e9b-ed47053e7a38.png)
有些分包能跳转成功，但是所有onClick事件无法正常响应

**Comment by Chen-jj** [comment]
@shufangjian 提供下可复现代码。

**Comment by shufangjian** [comment]
@Chen-jj https://github.com/shufangjian/saas-taro 复现仓库，主页进去之后，绑定账号15161885512，无需验证码，主页tabbar生态-- 悬浮按钮发布 -- 报名活动

**Comment by Chen-jj** [comment]
@shufangjian 项目跑不起来

![image](https://user-images.githubusercontent.com/11807297/60232296-c8240700-98ce-11e9-8cba-a0ac315c83c4.png)

**Comment by shufangjian** [comment]
@Chen-jj 麻烦把 src/app.tsx文件中pages的配置项 'pages/work/home/index' 路径提取到第一个，直接预览

**Comment by Chen-jj** [comment]
> @Chen-jj https://github.com/shufangjian/saas-taro 复现仓库，主页进去之后，绑定账号15161885512，无需验证码，主页tabbar生态-- 悬浮按钮发布 -- 报名活动

@shufangjian 找不到

**Comment by shufangjian** [comment]
![image](https://user-images.githubusercontent.com/7800305/60320561-b2850f00-99ac-11e9-806f-47aaf565508e.png)

您好，没有这个页面吗

**Comment by Chen-jj** [comment]
@shufangjian 发布可以点呀，iphone

**Comment by shufangjian** [comment]
是可以点，发布-活动报名，里面input事件，button事件均失效了

**Comment by Chen-jj** [comment]
@shufangjian 不是事件失效，我慢慢调试了一晚，发现 picker 里包两个 view 就会报“发生错误，请看控制台”。

```xml
<Picker mode='date'>
  <View>开始时间</View>
  <View>
     请选择
  </View>
</Picker>
```

1. 自己试试是不是一样的问题点，然后写个原生测试。
2. 这种问题自测时就应该通过控制变量法进行定位，并且建议提问题时提交的项目一定要精简，尤其是需要真机调试的问题，没错编译推送浪费大量时间。

**Comment by shufangjian** [comment]
@Chen-jj  首先感谢您的指正
但是我这边调试出来的结果与您的有点不一致，
1.非正常渲染情况下 ，下面截图页面，button 是type='primary' 没有正常渲染，事件也失效了
![image](https://user-images.githubusercontent.com/7800305/60378318-680a9d80-9a53-11e9-9375-9469e2aa4876.png)


2. 在app.tsx里将下面两个页面路径注释掉，渲染与事件就正常了
'pages/aiHelper/home/index',
'pages/bindAccount/index'

**Comment by shufangjian** [comment]
@Chen-jj  首先感谢您的指正
但是我这边调试出来的结果与您的有点不一致，
1.非正常渲染情况下 ，下面截图页面，button 是type='primary' 没有正常渲染，事件也失效了
![image](https://user-images.githubusercontent.com/7800305/60378318-680a9d80-9a53-11e9-9375-9469e2aa4876.png)


2. 在app.tsx里将下面两个页面路径注释掉，渲染与事件就正常了
'pages/aiHelper/home/index',
'pages/bindAccount/index'

**Comment by shufangjian** [comment]
最小还原仓库，https://github.com/shufangjian/demo2

**Comment by Chen-jj** [comment]
@shufangjian Taro-ui 的问题下一个版本 1.3.7 应该就可以了。
