### ISSUE TITLE
componentWillReceiveProps在小程序下不能触发，但h5下可以

### ISSUE THREAD

**Issue by BreathlessWay** [NervJS/taro#3448]
**问题描述**
实际代码在h5中componentWillReceiveProps可以正常触发，但在小程序中不会被触发，实际props也已经更新，在render中可以获得最新的props，但是在小程序中未触发componentWillReceiveProps，复现代码比较长

**Comment by beyondghx** [comment]
我们也遇到类似问题，字节跳动小程序。请问你们解决了吗？如果解决了请告知下解决方案，谢谢
