### ISSUE TITLE
module "npm/@tarojs/taro-weapp/index.js" is not defined 

### ISSUE THREAD

**Issue by nickrogit** [NervJS/taro#345]
按官方步骤初始项目，编译后报以下错误，怎么解决？
VM634:1 thirdScriptError 
 sdk uncaught third Error 
 module "npm/@tarojs/taro-weapp/index.js" is not defined 
 Error: module "npm/@tarojs/taro-weapp/index.js" is not defined
    at require (http://127.0.0.1:59663/appservice/__dev__/WAService.js:22:7213)
    at http://127.0.0.1:59663/appservice/__dev__/WAService.js:22:7068
    at http://127.0.0.1:59663/appservice/app.js:9:14
    at require (http://127.0.0.1:59663/appservice/__dev__/WAService.js:22:7354)
    at http://127.0.0.1:59663/appservice/appservice?t=1531897044619:1031:9

**Comment by yuche** [comment]
安装不完整，cnpm 再装一次试试？

**Comment by nickrogit** [comment]
cnpm install -g @tarojs/cli安装了问题依旧

**Comment by yuche** [comment]
应该是重新安装 `taro init` 那个目录的依赖，这里是本地的依赖没找到

**Comment by Harhao** [comment]
请问这个问题该怎么进行解决？？

**Comment by Harhao** [comment]
已经解决了，需要重新安装依赖。第一init安装依赖的时间比较长

**Comment by Harhao** [comment]
重新安装项目依赖之后，编译源码之后，还是会出现这个错误

**Comment by luckyadam** [comment]
确定项目依赖安装好了么

**Comment by guotie** [comment]
init项目后没有报错，然后增加一个页面后报错，是什么原因

**Comment by luckyadam** [comment]
@guotie 是报啥错嘞

**Comment by guotie** [comment]
在刚才关闭的issue中反馈了，应该是微信开发工具的问题

**Comment by luckyadam** [comment]
OJBK 那先关闭啦~

**Comment by yuhong-l** [comment]
遇到这个问题，无法解决，似乎是node_modules文件夹里面齐全，但是dist文件夹下的生成的npm文件夹总是会少东西。
可以看到编译之后taro文件夹里只有一个index.js，然而里面会引用一个./dist/index.js并不存在。
即使手动从node_modules里复制过来，下次编译还是会重新生成只有index.js一个文件。
![image](https://user-images.githubusercontent.com/37088436/48980329-687c3800-f102-11e8-8266-2a0481d528f1.png)

**Comment by 1ihu** [comment]
解决了么
