### ISSUE TITLE
在小程序内使用useSelector，状态没有改变

### ISSUE THREAD

**Issue by vonweb** [NervJS/taro#3456]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
将自带的模板改成FunctionComponent，使用 `useSelector` `useDispatch` hook， `useDispatch` 可以正常改变store里面值， `useSelector` 返回值没有变化

**复现步骤**
[复现问题的步骤]
1. 点击”+“， ”-“改变了store内的值，但页面上没有变化

![image](https://user-images.githubusercontent.com/5784758/59588036-40ddd300-9119-11e9-9503-76ee56fefdc8.png)

![image](https://user-images.githubusercontent.com/5784758/59587973-1be96000-9119-11e9-9156-cc448e5f571c.png)

```js

import { FunctionComponent } from 'react'
import Taro from '@tarojs/taro'
import { useSelector, useDispatch } from '@tarojs/redux'
import { View, Button, Text } from '@tarojs/components'
import { add, minus } from '../../actions/counter'

const Demo: FunctionComponent = () => {
  const counter = useSelector<RootReducer, number>(state => state.counter.num)
  const dispatch = useDispatch()

  function onAdd() {
    dispatch(add())
  }

  return (
    <View className='index'>
      <Button className='add_btn' onClick={onAdd}>
        +
      </Button>
      <Button className='dec_btn' onClick={() => dispatch(minus())}>
        -
      </Button>
      <View>
        <Text>{counter}</Text>
      </View>
      <View>
        <Text>Hello, World2</Text>
      </View>
    </View>
  )
}

export default Demo

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
状态变化

**报错信息**
无

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 1.3.1
 - Node.js 版本 v10.16.0
 - 报错平台 weapp

**补充信息**
无

**Comment by yuche** [comment]
你能做一个复现的仓库吗

**Comment by vonweb** [comment]
@yuche 在线跑不起来，也遇到[#3447](https://github.com/NervJS/taro/issues/3447)问题， actions跟reducers没动，就是`taro init`生成的
reducer
```js
import { ADD, MINUS, PLUS } from '../constants/counter'

const INITIAL_STATE = {
  num: 0,
}

export default function counter(state = INITIAL_STATE, action) {
  switch (action.type) {
    case ADD:
      return {
        ...state,
        num: state.num + 1,
      }
    case MINUS:
      return {
        ...state,
        num: state.num - 1,
      }
    case PLUS:
      return {
        ...state,
        num: state.num + action.payload,
      }
    default:
      return state
  }
}
```js
actions:
```
import { ADD, MINUS } from '../constants/counter'

export const add = () => {
  return {
    type: ADD,
  }
}
export const minus = () => {
  return {
    type: MINUS,
  }
}

// 异步的action
export function asyncAdd() {
  return dispatch => {
    setTimeout(() => {
      dispatch(add())
    }, 2000)
  }
}
```

**Comment by liu-dongyu** [comment]
同样的问题，`taro init`生成的reducer，改成hook以后，从`useSelector`获取的值没有响应变化

**Comment by crabkiller** [comment]
你好，请问这个问题怎么解决了吗，我看 issue 已经关闭了 @vonweb @yuche
