### ISSUE TITLE
[源代码]taro-cli目录下运行 "npm pack"命令 报错 'JSX' only refers to a type, but is being used as a namespace here

### ISSUE THREAD

**Issue by xsq007** [NervJS/taro#3459]
**问题描述**
下载v1.3.1版本taro源代码到本地，在taro-cli目录下运行"npm pack" 报错

**复现步骤**
1. 下载v1.3.1版本源代码到本地
2. 进入packages/taro-cli目录，运行 npm i 
3. 运行 npm pack，报错 

**期望行为**
 成功运行  npm pack

**报错信息**
![image](https://user-images.githubusercontent.com/10074113/59596987-565bf880-912b-11e9-84ad-ac72a1b90942.png)

**系统信息**
 - 操作系统:  macOS Mojave 10.14.5
 - Taro 版本 v1.3.1
 - Node.js 版本 v8.12.0

**Comment by yuche** [comment]
你需要用 lerna bootstrap 再进行源码的修改
