### ISSUE TITLE
小程序开发引入使用Nerv开发的自定义组件，报错了

### ISSUE THREAD

**Issue by wqzwh** [NervJS/taro#346]
**问题描述**
我在使用taro开发小程序页面的时候，在项目中引入自定义组件（使用Nerv开发的），在小程序调试工具上面显示报错

**复现步骤**

在项目中自定义组件：
![image](https://user-images.githubusercontent.com/16662470/42869709-664ea696-8aa8-11e8-8d35-7e77b6f3913e.png)

然后在page中的index中引入：
![image](https://user-images.githubusercontent.com/16662470/42869743-7fbd6964-8aa8-11e8-850d-6788a3c20924.png)
![image](https://user-images.githubusercontent.com/16662470/42869756-8d007e54-8aa8-11e8-998e-caa592bf2a65.png)

最终在小程序调试工具上显示报错：
![image](https://user-images.githubusercontent.com/16662470/42869793-a6605518-8aa8-11e8-84c7-8ce0428275da.png)

```js
// 自定义组件代码
import Nerv from 'nervjs'

class TButton extends Nerv.Component {

  render () {
    return (
      <button className='t-button-wrap'>
      11111
      </button>
    )
  }
}

export {
  TButton
} 
```

**期望行为**
希望能兼容自定义Nerv开发或者react开发的组件

**报错信息**
已经在问题描述中添加了

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. v.0.0.70]
 - Node.js 版本 [e.g. v8.11.1]

**补充信息**
如果使用Nerv自定义开发组件，发现constructor不存在

**Comment by yuche** [comment]
当你使用 Taro 时，直接从 Taro 引入依赖，不用考虑 Nerv 是啥。
建议先看一下文档再动手：
https://nervjs.github.io/taro/

**Comment by wqzwh** [comment]
@yuche  我是这么考虑的，如果我直接使用Taro依赖的Component去做的话，那么封装的基础ui组件就会依赖taro了，我想使用Nerv或者react写一套ui基础组件，这样的话，ui组件还能在其他地方使用。

**Comment by yuche** [comment]
你从 taro 引入依赖一样可以，在其他的项目设置一下 alias 就行了

**Comment by wqzwh** [comment]
@yuche 如果有些项目不依赖taro这个框架，我在项目里也能使用自己封装的ui组件么，关键在定义组件的时候连constructor都不存在，我不敢保证在其他项目（不依赖taro框架的）中能正常运行。

**Comment by yuche** [comment]
可以，你 alias 之后导入那个的 Component 就是 alias 之后的 Component，你想 react 也可以，nerv 也可以

**Comment by wqzwh** [comment]
@yuche  好的，我先试试

**Comment by wqzwh** [comment]
![image](https://user-images.githubusercontent.com/16662470/43070751-3c12e186-8ea3-11e8-98ef-fd792caef29b.png)
例如这是我自己开发的组件，但是这样引入直接使用就会报如下错误：

![image](https://user-images.githubusercontent.com/16662470/43070800-5a53ade2-8ea3-11e8-8116-ccad3e92a7e4.png)

node命令行报如下错误：

![image](https://user-images.githubusercontent.com/16662470/43070846-7758cdbe-8ea3-11e8-9ecb-5941f6c11435.png)

**Comment by luckyadam** [comment]
你在小程序里是用不了 Nerv 的组件啊，Nerv 使用的是 HTML 的标签，这个在小程序里肯定是运行不了的

**Comment by wqzwh** [comment]
@luckyadam  我重新描述下：这个tui是我自己自定义的ui组件库，使用的是nervjs这个库，然后放在公司内网的git上管理，在taro项目中通过npm下载这个tui来使用。再一个，我看@tarojs/components里面的组件也是用的nervjs，然后直接在taro中引入就不会报错，自己写的引入就会报错，我看了，两者写法差不多，这是什么原因。其实我最终的目的就是想根据自己的业务需求编写一套适合自己的ui组件，方便后期复用。这样的话我该怎么操作，求解。

**Comment by luckyadam** [comment]
@wqzwh 是这样子的 @tarojs/components 是给 h5 用的组件库，所以它是用 `nervjs` 写的，但如果是想要兼容多端，必须得用 Taro 的写法来写组件，用 `nervjs` 是不行的

**Comment by luckyadam** [comment]
@jeasonnow 是的，当然你也可以使用 Taro 语法来自己写一些组件~

**Comment by wqzwh** [comment]
@luckyadam 了解了
