### ISSUE TITLE
全局变量未及时更新，导致设置拦截器错误

### ISSUE THREAD

**Issue by lavi2510** [NervJS/taro#3460]
**问题描述**
小程序扫码后在willMount时获取this.$router.params参数，赋值给一个全局变量并设置拦截器，这时刷新二维码this.$router.params参数变更，全局变量变更，但addInterceptor内获取的全局变量未改变

**复现步骤**
1. 在微信开发平台 扫描小程序体验版二维码打开小程序
2. 在开发平台更改页面路径
3. 重新扫码

```js
//设置全局变量 this.baseURL
constructor (props) {
    super(props);
    this.state = {};
    this.baseURL = "";
  }

//拦截器
envInterceptor = (chain) => {
    const requestParams = chain.requestParams;
    if(requestParams.url.indexOf('http') === -1)
      requestParams.url = `${this.baseURL}${requestParams.url}`;
    return chain.proceed(requestParams).then(res => console.log("envInterceptor", this.baseURL))
  };

//在willMount获取页面参数赋值给全局变量并设置拦截器
componentWillMount() {
    console.log('index willmount');
    const { baseURL, applicationOID } = this.$router.params;
    console.log("index willmount", baseURL);
    this.baseURL = baseURL || Taro.getStorageSync('baseURL');
    baseURL && Taro.setStorageSync('baseURL', baseURL);
    Taro.addInterceptor(this.envInterceptor);
    console.log("SDKVersion", Taro.getSystemInfoSync().SDKVersion);
    console.log(Taro.getSystemInfoSync().brand + "  " + Taro.getSystemInfoSync().model);
  }

```

**期望行为**
更新全局变量时，拦截器内全局变量同时更新

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/13363238/59603065-fcfbc580-913a-11e9-8d8a-a3d6c8fc642e.png)

**系统信息**
 - 操作系统: [ ios 12.3.1]
 - Taro 版本 [v1.2.26]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@lavi2510 老哥你这种情况比较特殊，原因是拦截器的状态由一个全局对象维护，而你第三步重新扫码打开小程序时，小程序只是把页面对象卸载后重新创建，但拦截器的全局对象没有被销毁。意思是拦截器还保留着上一次的状态，也就是第一次 willMount 时 addInterceptors 加入的闭包函数。

这里我给你开了个 API **cleanInterceptors**，可以清除之前添加过的拦截器，在 addInterceptors 前调用即可。

```js
componentWillMount() {
    // ...
    // 加入下面这句
    Taro.cleanInterceptors()
    Taro.addInterceptor(this.envInterceptor, this);
}
```

**Comment by lavi2510** [comment]
你好，更新到1.3.2版本仍然用不了该函数，大概在哪个版本上呢？

**Comment by Chen-jj** [comment]
等等1.3.3

**Comment by lavi2510** [comment]
好的， 谢谢~
