### ISSUE TITLE
请问有没有像vue-router 的history模式的路由模式

### ISSUE THREAD

**Issue by junliepigyao** [NervJS/taro#3465]
**问题描述**
因为这边制作H5需要获取根据微信提供的URL链接来动态获取到code，配置的时候需要根据微信提供的URL获取最后的地址：
https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx49127e1c5ce3532c&redirect_uri={URL}&response_type=code&scope=snsapi_base&state=2#wechat_redirect

上面链接的URL待了#号不能正常使用。

**期望行为**
添加像vue-router 的history模式的路由模式
能灵活使用两种路由地址

**报错信息**

**系统信息**
👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.1 => 1.3.1 
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/mobx: 1.3.0 => 1.3.0 
      @tarojs/mobx-h5: 1.3.0 => 1.3.0 
      @tarojs/mobx-rn: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-sass: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/rn-runner: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.1

**Comment by klgd** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#h5router 文档有说明

**Comment by junliepigyao** [comment]
> https://nervjs.github.io/taro/docs/config-detail.html#h5router 文档有说明

感谢。我一直在路由文档里面找。没看到编译文档去。。。谢谢
