### ISSUE TITLE
微信小程序，webgl canvas支持相关。使用函数方式获取refs，第一次正确获取，推出canvas页面重新进入发现返回的ref类型无法正确获取webgl context

### ISSUE THREAD

**Issue by zzyhdu** [NervJS/taro#3467]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```js

 render() {
    const { unsupported } = this.state;
    if (unsupported) {
      // return this._renderUnsupported();
    }

    return (
      <Canvas
        ref={this._bindCanvasRef}
        canvasId='canvasId'
        // eslint-disable-next-line jsx-quotes
        className="glcanvas"
        type='webgl'
      />
    );
  }

  _bindCanvasRef = (ref: any) => {
    this._gl = null
    if(ref){=
      ref.node().exec((res) => {=
        const node = res[0].node;
        
        if(node && !this._gl){
          this._canvasNode = node;
          this._gl = node.getContext('webgl');=
          this._newGlRenderer(this._gl);
        }
      })
    }else{
      this._canvasNode = null;
      this._gl = null;
    }
  };


// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
每次都可以获取到正确的ref

**报错信息**

在第二次之后报错： getContext is not a function

**系统信息**

- 操作系统: macOS 10.14.1
- Taro 版本: v1.3.1
- Node.js 版本 10.1.0
- 报错平台: weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@zzyhdu 再详细描述一下复现步骤

**Comment by zzyhdu** [comment]
页面a进入页面b，页面b有webgl canvas,第一次进入可以获取到webglRenderingContext，返回页面a，重新进入页面b，无法获取webglRenderingContext，提示：xx.getContext is not function

**Comment by Chen-jj** [comment]
@zzyhdu 真机测过没有问题，ref 获取是正确的，再排查下手机型号、微信版本等其它原因咯。

![RPReplay_Final1561086145 2019-06-21 11_03_34](https://user-images.githubusercontent.com/11807297/59894724-420e4900-9414-11e9-87ee-e8ea903b2e78.gif)

```js
export default class Detail extends Component {
  render() {
    const { unsupported } = this.state;
    if (unsupported) {
      // return this._renderUnsupported();
    }

    return (
      <Canvas
        ref={this._bindCanvasRef}
        canvasId='canvasId'
        // eslint-disable-next-line jsx-quotes
        className="glcanvas"
        type='webgl'
      />
    );
  }

  _bindCanvasRef = (ref) => {
    this._gl = null
    if(ref){
      console.log('ref: ', ref)
      ref.node().exec((res) => {
        const node = res[0].node;
        console.log('node: ', node)

        if(node && !this._gl){
          this._canvasNode = node;
          this._gl = node.getContext('webgl')
          console.log('_gl: ', this._gl)
        }
      })
    }else{
      console.log('ref undefined')
      this._canvasNode = null;
      this._gl = null;
    }
  }
}
```

**Comment by zzyhdu** [comment]
@Chen-jj 能不能把环境发我对比下～感谢🙏

**Comment by zzyhdu** [comment]
@Chen-jj 拿同事的iphone和小米试了，iphone的可以正常获取ref，但是无法作图（这个问题需要再确认），小米8和我的手机（荣耀v20）表现一致，推测android平台存在上诉问题，请确认～

**Comment by Chen-jj** [comment]
@zzyhdu 安卓打印一下 ref 取值是多少？或者直接换用 querySelector api 看看有没有相同问题，排查一下是 Taro 还是小程序的问题。

**Comment by zzyhdu** [comment]
![image](https://user-images.githubusercontent.com/4222224/59998193-69257e80-9691-11e9-8761-91979136ee5f.png)
代码是在自定义控件中的，直接调用可能有问题。。微信的文档好像说是要用this调用，通过taro应该是不行的？图片中第一个是ref，第二个是调用Taro.createSelectorQuery().select('#glcanvasId'))

**Comment by Chen-jj** [comment]
@zzyhdu 没太懂你的意思。

**Comment by zzyhdu** [comment]
@Chen-jj ...你可以直接看log～图片中第一个是通过bindred获取到的ref，第二个是调用Taro.createSelectorQuery().select('#glcanvasId'))获取的对象

**Comment by Chen-jj** [comment]
@zzyhdu 可以进入 /dist/npm/@taojs/taro-weapp/dist/index.js 文件，找到 componentTrigger 函数。然后 debug 一下 `query.select(...)` 里的 id 是否和 wxml 中给 canvas 打上的随机 id 一致、target 得到值是多少。

![{453C1880-327B-2E52-DBAC-4B316DEA3239}](https://user-images.githubusercontent.com/11807297/60084528-4b781800-976a-11e9-9da2-d35eea636adc.jpg)

然后再找到 onReady 这段（等于小程序页面 onReady 生命周期函数），在里面加上小程序原生 querySelector 方法查询 canvas 的随机 id，看是否能查出来。

![{75520F65-BC63-F21B-59CA-48F1B32FAB4A}](https://user-images.githubusercontent.com/11807297/60084823-d0fbc800-976a-11e9-8302-e6a1e4b1d46d.jpg)

**Comment by zzyhdu** [comment]
![WechatIMG45](https://user-images.githubusercontent.com/4222224/60148863-474d0880-9805-11e9-8dd2-689db51f83d2.jpeg)
![WechatIMG44](https://user-images.githubusercontent.com/4222224/60148868-4a47f900-9805-11e9-978a-b464540955df.jpeg)
![WechatIMG43](https://user-images.githubusercontent.com/4222224/60148871-4c11bc80-9805-11e9-91d0-f71f2c9309a2.jpeg)
![Screen Shot 2019-06-26 at 11 25 12 AM](https://user-images.githubusercontent.com/4222224/60148875-4d42e980-9805-11e9-8429-aac8f505f942.png)
![Screen Shot 2019-06-26 at 11 24 52 AM](https://user-images.githubusercontent.com/4222224/60148878-4f0cad00-9805-11e9-98f0-0414df669712.png)


在onReady中怎么获取随机Id我不太懂

**Comment by Chen-jj** [comment]
@zzyhdu 总之 taro 小程序的 ref 就是给组件打 id，然后用 querySelect API 查 dom。自己 debug 下原生能不能获取到打上的随机 id 吧。
