### ISSUE TITLE
h5端判断是否在微信公众号中支持API，该报错信息有误

### ISSUE THREAD

**Issue by maoyifanDev** [NervJS/taro#3470]
**问题描述**
h5端判断是否在微信公众号中支持API，该报错信息有误

**复现步骤**
1. 项目中调用Taro.getLocation
2. 在微信开发者工具（公众号网页调试模式）中打开
3. console中出现错误信息，h5端仅在微信公众号中支持 API getLocation（实际上我就是在微信公众号中调用）

![image](https://user-images.githubusercontent.com/47847170/59679744-3b0fec80-9202-11e9-8b7f-64cfd187ba66.png)

```js

阅读源码觉得出现这错误的逻辑判断有问题

https://github.com/NervJS/taro/blob/400bb7ae9cf67006a44d28b2fb04a3f6ae24e544/packages/taro-h5/src/api/utils/index.js#L190
https://github.com/NervJS/taro/blob/400bb7ae9cf67006a44d28b2fb04a3f6ae24e544/packages/taro-h5/src/api/utils/index.js#L76

此处是根据是否存在window.wx来判断是否在微信公众号中支持该api的，wx不应该是小程序中的全局对象么，怎么也拿来判断h5公众号中是否支持某API

```

**期望行为**

**系统信息**

 - 操作系统: [macOS]
 - Taro 版本 [v.1.3.2]
 - Node.js 版本 [v8.10.0]
 - 报错平台 [h5]

**Comment by HoganGolden** [comment]
请问是怎么解决的
