### ISSUE TITLE
快应用构建报错，文件加载失败

### ISSUE THREAD

**Issue by summeroct2** [NervJS/taro#3473]
**问题描述**

taro初始化的项目，构建快应用，提示文件加载失败，报构建错误。

**复现步骤**
1. taro init my-taro-app
2. taro build --type quickapp --watch 构建失败，提示 `错误  包安装    缺少包 @tarojs/components-qa`
3. npm i -S @tarojs/components-qa 安装失败
4. 手动添加依赖到package.json，删除node_modules，npm i ，重新安装成功
5. 配置 project.quickapp.json，运行`taro build --type quickapp --watch` 提示 `快应用环境准备失败，请重试！`
6. 直接再次运行 `taro build --type quickapp --watch` 提示两条promise报错的提示：
`(node:48560) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module 'adb-commander'`
`(node:48560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
7. 用快应用IDE导入taro构建出的dist目录，编译报错，提示下面报错信息中的错误

**期望行为**

构建正常，正常运行。

**报错信息**

IDE构建报错截图：
![image](https://user-images.githubusercontent.com/28774479/59733511-b4e6bb00-9280-11e9-918d-56349fade8b5.png)

**系统信息**

 - 操作系统 [macOS High Sierra 10.13.6]
 - Taro 版本 [1.3.2]
 - Node.js 版本 [8.9.3]
 - 报错平台 [quickapp]

![image](https://user-images.githubusercontent.com/28774479/59732373-8ff04900-927c-11e9-9ff0-58ecdd374ca4.png)

**补充信息**

直观分析是缺少ux文件加载器，可能是编译工作没完成。

**Comment by chaojiangcn** [comment]
同问编译后的文件只有，app.ux    其他的页面都编译失败 用的taro1.3.2bate

**Comment by luckyadam** [comment]
进入 dist 目录安装一下依赖，然后再运行呢

**Comment by summeroct2** [comment]
> 进入 dist 目录安装一下依赖，然后再运行呢

这样可以，但用IDE打开仍然报构建错误。

**Comment by luckyadam** [comment]
@summeroct2 还是用系统的 terminal 或者 item2 这样的工具来跑吧
