### ISSUE TITLE
编译过程中报：Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

### ISSUE THREAD

**Issue by sycreece** [NervJS/taro#3474]
**问题描述**
如题，编译过程中报：Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

```bash
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.js
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
拷贝  NPM文件   dist/npm/promise-polyfill/lib/index.js
```

**期望行为**
正常编译，没有warning

**报错信息**
![image](https://user-images.githubusercontent.com/16397055/59735754-83beb880-9289-11e9-8ed0-72c549acda42.png)

**系统信息**
Taro CLI 1.3.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~.tnvm/versions/alinode/v4.7.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~.tnvm/versions/alinode/v4.7.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.2 => 1.3.0
      @tarojs/components: 1.3.2 => 1.3.0
      @tarojs/plugin-babel: 1.3.2 => 1.3.0
      @tarojs/plugin-csso: 1.3.2 => 1.3.0
      @tarojs/plugin-sass: 1.3.2 => 1.3.0
      @tarojs/plugin-uglifyjs: 1.3.2 => 1.3.0
      @tarojs/redux: 1.3.2 => 1.3.1
      @tarojs/redux-h5: 1.3.2 => 1.3.0
      @tarojs/router: 1.3.2 => 1.3.0
      @tarojs/taro: 1.3.2 => 1.3.0
      @tarojs/taro-alipay: 1.3.2 => 1.3.0
      @tarojs/taro-h5: 1.3.2 => 1.3.0
      @tarojs/taro-swan: 1.3.2 => 1.3.0
      @tarojs/taro-tt: 1.3.2 => 1.3.0
      @tarojs/taro-weapp: 1.3.2 => 1.3.0
      @tarojs/webpack-runner: 1.3.2 => 1.3.0
      eslint-config-taro: ^1.3.2 => 1.3.0
      eslint-plugin-taro: ^1.3.2 => 1.3.0
      nerv-devtools: ^1.4.1 => 1.4.1
      nervjs: ^1.4.1 => 1.4.1
    npmGlobalPackages:
      typescript: 3.3.4000

**Comment by beibeiaiwuhao** [comment]
同问这个问题，系统信息一致，求解决办法

**Comment by guozilin** [comment]
![image](https://user-images.githubusercontent.com/17874134/59812784-c6dc6280-9341-11e9-99b3-1c96e497c2d6.png)
同样的警告，这个有对应的配置项吗？

**Comment by luckyadam** [comment]
把项目依赖也升级到 1.3.2

**Comment by nicoleffect** [comment]
同问

**Comment by sycreece** [comment]
> 把项目依赖也升级到 1.3.2

已经升级了，但是还是会报~

**Comment by yuche** [comment]
eslint-plugin-react 是不是没升级

**Comment by sycreece** [comment]
> eslint-plugin-react 是不是没升级
升了

```js
"dependencies": {
		"@tarojs/async-await": "1.3.3",
		"@tarojs/components": "1.3.3",
		"@tarojs/redux": "1.3.3",
		"@tarojs/redux-h5": "1.3.3",
		"@tarojs/router": "1.3.3",
		"@tarojs/taro": "1.3.3",
		"@tarojs/taro-alipay": "1.3.3",
		"@tarojs/taro-h5": "1.3.3",
		"@tarojs/taro-swan": "1.3.3",
		"@tarojs/taro-tt": "1.3.3",
		"@tarojs/taro-weapp": "1.3.3",
		"nerv-devtools": "^1.4.1",
		"nervjs": "^1.4.1",
		"redux": "^4.0.1",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0",
		"taro-ui": "^2.2.1"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "1.3.3",
		"@tarojs/plugin-csso": "1.3.3",
		"@tarojs/plugin-sass": "1.3.3",
		"@tarojs/plugin-uglifyjs": "1.3.3",
		"@tarojs/webpack-runner": "1.3.3",
		"@types/react": "^16.8.22",
		"@types/webpack-env": "^1.13.9",
		"argh": "^0.1.4",
		"babel-eslint": "^8.2.6",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.7.0",
		"chalk": "^2.4.2",
		"ejs": "^2.6.2",
		"eslint": "^5.16.0",
		"eslint-config-taro": "1.3.3",
		"eslint-plugin-import": "^2.17.3",
		"eslint-plugin-react": "^7.14.0",
		"eslint-plugin-taro": "1.3.3",
		"qs": "^6.7.0"
	},
```

**Comment by dpyzo0o** [comment]
这个问题解决了吗？ 我也碰到了同样的问题

Taro CLI 1.3.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.13 => 1.3.13 
      @tarojs/components: 1.3.10 => 1.3.10 
      @tarojs/plugin-babel: 1.3.10 => 1.3.10 
      @tarojs/plugin-csso: 1.3.10 => 1.3.10 
      @tarojs/plugin-sass: 1.3.10 => 1.3.10 
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10 
      @tarojs/router: 1.3.10 => 1.3.10 
      @tarojs/taro: 1.3.10 => 1.3.10 
      @tarojs/taro-alipay: 1.3.10 => 1.3.10 
      @tarojs/taro-h5: 1.3.10 => 1.3.10 
      @tarojs/taro-qq: 1.3.10 => 1.3.10 
      @tarojs/taro-quickapp: 1.3.10 => 1.3.10 
      @tarojs/taro-swan: 1.3.10 => 1.3.10 
      @tarojs/taro-tt: 1.3.10 => 1.3.10 
      @tarojs/taro-weapp: 1.3.10 => 1.3.10 
      @tarojs/webpack-runner: 1.3.10 => 1.3.10 
      eslint-config-taro: 1.3.10 => 1.3.10 
      eslint-plugin-taro: 1.3.10 => 1.3.10 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
      stylelint-config-taro-rn: 1.3.10 => 1.3.10 
      stylelint-taro-rn: 1.3.10 => 1.3.10 
    npmGlobalPackages:
      typescript: 3.4.5

**Comment by hqzh** [comment]
> 把项目依赖也升级到 1.3.2

同样无效
