### ISSUE TITLE
webgl canvas开发过程中需要获取图片，查看微信小程序文档，发现Image从2.7.0加入，但是 通过taro编译过后提示： Image is not defined.尝试使用new wx.Image(),提示wx.Image is not a constructor

### ISSUE THREAD

**Issue by zzyhdu** [NervJS/taro#3476]
**问题描述**
webgl canvas开发过程中需要获取图片，查看微信小程序文档，发现Image从2.7.0加入，但是
通过taro编译过后提示： Image is not defined.尝试使用new wx.Image(),提示wx.Image is not a constructor

**复现步骤**

```js

_createImageTexture(src: any): WebGLTexture {
    const { gl } = this._props;

    const texture = gl.createTexture();
    const image = new wx.Image();
    image.onload = () => {
      gl.bindTexture(gl.TEXTURE_2D, texture);
      gl.texImage2D(
        gl.TEXTURE_2D,
        0,
        gl.RGBA,
        gl.RGBA,
        gl.UNSIGNED_BYTE,
        image
      );

      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    };

    image.src = src;

    return texture;
  }

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

```

**期望行为**
可以正确创建Image对象

**报错信息**

 Image is not defined

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [mac]
 - Taro 版本 [1.3.1]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [ weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@zzyhdu 原生小程序能 `new wx.Image()` ？

**Comment by zzyhdu** [comment]
@Chen-jj 这个是我在群里问过老李，他让我这样试的～原来的代码是 new Image().小程序是不是能这样，我也不确定。https://developers.weixin.qq.com/miniprogram/dev/api/canvas/Image.html，这文档太简单了～

**Comment by Chen-jj** [comment]
@zzyhdu API 问题写份原生自己定位下。https://nervjs.github.io/taro/docs/debug.html#api-%E9%97%AE%E9%A2%98

**Comment by zzyhdu** [comment]
@Chen-jj ok,我明天试试，我还不知道怎么写原生的～

**Comment by luckyadam** [comment]
微信小程序文档里也没有找到 Image 对象的用法，你先试试原生里怎么用吧

**Comment by zzyhdu** [comment]
@luckyadam 嗯，文档太简单了，网上也很难找到资料，今天我尝试了在原生new Image(),提示Image is not defined,目前卡在这了～对小程序太不熟悉，太难猜了。

**Comment by zzyhdu** [comment]
@luckyadam 找到了！Image Canvas.createImage()
