### ISSUE TITLE
带有async 和await的微信小程序 执行taro convert失败

### ISSUE THREAD

**Issue by luyuan11233** [NervJS/taro#3477]
在微信小程序上使用
import regeneratorRuntime from '../../libs/runtime' 

Page({
   async onLoad({companyId}) {
        wx.showNavigationBarLoading();
        const res = await getShopInfo(companyId);
        this.setData({
            clerks:res.data.data.clerks || [],
            company:res.data.data.company || ''
        })
        wx.hideNavigationBarLoading()
    },
})

执行上述代码，会转换异常

**Comment by luyuan11233** [comment]
也不知道会不会改，我现在只能一个一个的把我的同步 await请求，一个一个改成 getData().then()了，很痛苦....

**Comment by luyuan11233** [comment]
越改越痛苦..

**Comment by luyuan11233** [comment]
代码从链表式结构 到了循环嵌套结构...从小白能看懂，到我自己也看不懂了

**Comment by luyuan11233** [comment]
改的怀疑人生了....好累

**Comment by luckyadam** [comment]
应该是没有考虑到 async await 的写法，我们看一下

**Comment by luyuan11233** [comment]
@luckyadam 好的，麻烦了哈  最好是改一下，因为用 async await 开发的还是很多的

**Comment by RedLemonPie** [comment]
遇到了相同的问题,
const regeneratorRuntime = require('../../../../utils/plugins/runtime')
使用的这种方式使用async/await,使用场景很多,感觉全改过来有点过于麻烦
