### ISSUE TITLE
app.js中加逻辑判断写多个Taro.render，打包出来只有一个

### ISSUE THREAD

**Issue by maoyifanDev** [NervJS/taro#3479]
**问题描述**
要实现的业务逻辑是，在h5端，需要根据ua判断，展示两种页面，一种正常流程页面，一种不可用页面

**复现步骤**

1. 在app.js中，根据某些条件render不同的页面

![image](https://user-images.githubusercontent.com/47847170/59753235-445a9100-92b6-11e9-885c-3e6c4a611b1d.png)

2. 此处的`ua.page.isAvailable`是true，实际应该打印'aaaa'，走`<div>可用</div>`渲染逻辑

实际上，页面打印确实是'aaaa'，但走的是else里面的`<div>不可用</div>`

![image](https://user-images.githubusercontent.com/47847170/59753169-242ad200-92b6-11e9-8a27-fd13d29cf2f7.png)

**期望行为**
打印出'aaaa', 渲染出`<div>可用</div>`

**报错信息**

查看打出来的源码，发现，上面那段代码，打包出来是这样的

![image](https://user-images.githubusercontent.com/47847170/59753441-b7640780-92b6-11e9-9630-5711401ae27f.png)

可以看出，if, else中render那部分被移除了，将最后一个render提取了出来，与实际逻辑不符

**系统信息**

 - 操作系统: [macOS]
 - Taro 版本 [v1.3.2]
 - Node.js 版本 [v8.10.0]
 - 报错平台 [h5]

**Comment by Garfield550** [comment]
app.js 保持原样，把你的逻辑写在 pages/index.js 可以吗？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/tutorial.html#%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6-render-%E6%96%B9%E6%B3%95%E8%AF%B4%E6%98%8E
