### ISSUE TITLE
【快应用】使用Taro里的Swiper组件编译错误，失败

### ISSUE THREAD

**Issue by KwongyeeChia** [NervJS/taro#3481]
![image](https://user-images.githubusercontent.com/39576364/59754604-feeb9300-92b8-11e9-86a3-c7bfcac25e8b.png)
![image](https://user-images.githubusercontent.com/39576364/59754639-10349f80-92b9-11e9-87ff-7f0bc9a100a2.png)

**Comment by luckyadam** [comment]
贴下使用代码

**Comment by KwongyeeChia** [comment]
![image](https://user-images.githubusercontent.com/39576364/59814650-a6fc6d00-9348-11e9-97aa-a871542957a1.png)
![image](https://user-images.githubusercontent.com/39576364/59814662-af54a800-9348-11e9-8944-282311370688.png)
import { View, Text, Image, Input, Swiper, SwiperItem } from '@tarojs/components'
<Swiper
					className='test-h'
					indicatorColor='#999'
					indicatorActiveColor='#333'
					vertical
					circular
					indicatorDots
					autoplay>
					<SwiperItem>
					<View className='demo-text-1'>1</View>
					</SwiperItem>
					<SwiperItem>
					<View className='demo-text-2'>2</View>
					</SwiperItem>
					<SwiperItem>
					<View className='demo-text-3'>3</View>
					</SwiperItem>
				</Swiper>
就正常的....引入 调用..

**Comment by KwongyeeChia** [comment]
找到问题了...swiper-item这个组件编译不成功 导入就报错了 单独使用swiper组件可行
