### ISSUE TITLE
自定义表单获取不到值

### ISSUE THREAD

**Issue by frontlich** [NervJS/taro#3482]
自定义组件里加了 static behaviors = ['wx://form-field']，

在1.2.23版本能获取到自定义表单项的值，升级到1.3.2之后获取不到自定义表单组件的值了

**Comment by frontlich** [comment]
打包后自定义组件的name丢失了

**Comment by luckyadam** [comment]
> 打包后自定义组件的name丢失了

哪个name

**Comment by zzzzyp** [comment]
> > 打包后自定义组件的name丢失了
> 
> 哪个name
![微信图片_20190809143300.png](https://i.loli.net/2019/08/09/lqLaftHPnzpQIYv.png)
![微信图片_20190809143304.png](https://i.loli.net/2019/08/09/COLbXS8nluPKqT1.png)
编译后自定义组件上的name丢失，Form里拿不到自定义表单控件的值了
