### ISSUE TITLE
函数式组件，如果返回值是通过方法调用返回，即报错

### ISSUE THREAD

**Issue by nanjingboy** [NervJS/taro#3485]
**问题描述**

函数式组件，如果返回值是通过方法调用返回的，即报以下错误：

* h5

<img width="468" alt="屏幕快照 2019-06-19 下午5 36 14" src="https://user-images.githubusercontent.com/1390888/59811815-1de03880-933e-11e9-94cd-9e44edc36fe3.png">

* 微信

<img width="1034" alt="屏幕快照 2019-06-20 上午9 38 49" src="https://user-images.githubusercontent.com/1390888/59812094-53d1ec80-933f-11e9-9a14-a4216f694b5b.png">

**复现步骤**

如下所示，在 Index 中的返回值通过调用 doSomething 返回，即报错。

```js
import Taro from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'

const Index = () => {
  return doSomething(() => {
    return (
      <View>
        <Text>Hello World</Text>
      </View>
    )
  })
}

function doSomething(fn) {
  return fn();
}

export default Index
```

**期望行为**

函数式组件，如果返回值是通过方法调用返回，能够正常运行。

**系统信息**

👽 Taro v1.3.2

  Taro CLI 1.3.2 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.2 => 1.3.2
      @tarojs/plugin-babel: 1.3.2 => 1.3.2
      @tarojs/plugin-csso: 1.3.2 => 1.3.2
      @tarojs/plugin-sass: 1.3.2 => 1.3.2
      @tarojs/plugin-uglifyjs: 1.3.2 => 1.3.2
      @tarojs/router: 1.3.2 => 1.3.2
      @tarojs/taro: 1.3.2 => 1.3.2
      @tarojs/taro-alipay: 1.3.2 => 1.3.2
      @tarojs/taro-h5: 1.3.2 => 1.3.2
      @tarojs/taro-swan: 1.3.2 => 1.3.2
      @tarojs/taro-tt: 1.3.2 => 1.3.2
      @tarojs/taro-weapp: 1.3.2 => 1.3.2
      @tarojs/webpack-runner: 1.3.2 => 1.3.2
      eslint-config-taro: 1.3.2 => 1.3.2
      eslint-plugin-taro: 1.3.2 => 1.3.2
      nerv-devtools: ^1.4.0 => 1.4.1
      nervjs: ^1.4.0 => 1.4.1

**Comment by yuche** [comment]
这样的做法是行不通的。Taro 使用 JSX 最大的限制在于无法动态地生成 JSX。

这个例子相当于 `doSomething()`  在运行时生成了一个 JSX，但编译器是无法知道它生成的是 JSX。

**Comment by nanjingboy** [comment]
@yuche OK，我再想其他方法绕过吧
