### ISSUE TITLE
Taro转TT获取不到通过参数获取不到场景值

### ISSUE THREAD

**Issue by chaojiangcn** [NervJS/taro#3486]
**问题描述**
微信小程序转的Taro，再转的tt，通过参数获取不到场景值,  

**复现步骤**

```
 _this.componentWillMount = function (a) {
      console.log('index->1',a)   // undefined
```

**期望行为**
[有什么解决办法]

**报错信息**

![image](https://user-images.githubusercontent.com/29300205/59812179-9e536900-933f-11e9-8d64-1e5d462ad6d1.png)

**系统信息**

  Taro CLI 1.3.0-beta.5 environment info:
  System:
      OS: Windows 7
  Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
用 this.$router.params，开发前请阅读一遍文档

**Comment by chaojiangcn** [comment]
> 用 this.$router.params，开发前请阅读一遍文档

_谢谢_
