### ISSUE TITLE
app文件中store文件与mobx引入顺序导致的编译问题

### ISSUE THREAD

**Issue by mosqlee** [NervJS/taro#3488]
**问题描述**
app.js中，store文件在mobx之前import，编译的文件中没有引入mobx相关的npm包。

**复现步骤**
[复现问题的步骤]
1. 使用taro mobx模版，typescript
2. 将mobx的store 统一放在一个ts文件中导出
3. 将app.ts中的store文件和mobx的Provider引入顺序改变，store在上，mobx在下
4. yarn dev:weapp
5. See error

app.tsx
```js
import '@tarojs/async-await'
import Taro, { Component, Config } from '@tarojs/taro'
// store 和Provider的引入顺序改变
import {store} from './store/index'
import { Provider } from '@tarojs/mobx'
import Index from './pages/index'


 ```

store/index.ts
```js
import counterStore from "./counter";

export const store = {
  counterStore,
};

```

**期望行为**

不论mobx文件和store的引入顺序，都能正常编译，不报错。

**报错信息**

VM200492:1 thirdScriptError 
 sdk uncaught third Error 
 setStore is not defined 
 ReferenceError: setStore is not defined
    at http://127.0.0.1:57698/appservice/app.js:26:1
    at require (http://127.0.0.1:57698/appservice/__dev__/WAService.js:1:1113027)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:57698/appservice/appservice?t=1560998098947:1118:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:57698/appservice/appservice?t=1560998098947:1130:20)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Hackintosh 10.14.4
 - Taro 版本 1.3.2
 - Node.js 版本 10.15.3
 - 报错平台 weapp

**补充信息**
repo:https://github.com/mosqlee/taro_mobx_bug.git

**Comment by nanjingboy** [comment]
@mosqlee 升级到最新版本后该问题已经不存在了。
