### ISSUE TITLE
app.js里的config能不能做成动态的?

### ISSUE THREAD

**Issue by Cicada7year** [NervJS/taro#3490]
如题，或者可以做成app.h5.js  app.weapp.js这种

**Comment by JokerLoLgrey** [comment]
不能，这个最后会转换成json文件

**Comment by Cicada7year** [comment]
> 不能，这个最后会转换成json文件

有没有什么实现方式  要不然每次编译都得手动处理   有些麻烦

**Comment by yulrosy** [comment]
package.json
"yarn:app:h5": "cp app.h5.js app.js && yarn build:h5"

**Comment by luckyadam** [comment]
正在研究

**Comment by dcalsky** [comment]
My current way is using gulp to generate manually 2 kinds of `app.js` depends on the building environment, though just the config is different.

**Comment by so-diao** [comment]
可以用`process.env`来做变量，不过h5会报错，h5我是用的`app.h5.js`。

**Comment by Chen-jj** [comment]
Taro 3 已可编写动态 config
