### ISSUE TITLE
h5 下 taro-ui的组件样式没有转换成rem

### ISSUE THREAD

**Issue by shock-lee** [NervJS/taro#3492]
**问题描述**
最新的taro，最新的taro-ui，npm run dev:h5，引入taro-ui的组件，taro-ui的组件的样式（px）没有被编译成rem

**复现步骤**
[复现问题的步骤]

![image](https://user-images.githubusercontent.com/17798390/59841386-d03bee00-9386-11e9-8085-e9b98ca87dd9.png)

![image](https://user-images.githubusercontent.com/17798390/59841464-f5c8f780-9386-11e9-9c76-b0cd79d5a2bb.png)

```js

import {AtTag,AtButton} from 'taro-ui';

// app.js
import 'taro-ui/dist/style/index.scss'

```

**期望行为**
样式能够被编译

**报错信息**

无报错

**系统信息**

![image](https://user-images.githubusercontent.com/17798390/59842174-90760600-9388-11e9-8e0b-3034e74237eb.png)

**Comment by Janice1114** [comment]
> **问题描述**
> 最新的taro，最新的taro-ui，npm run dev:h5，引入taro-ui的组件，taro-ui的组件的样式（px）没有被编译成rem
> 
> **复现步骤**
> [复现问题的步骤]
> 
> ![image](https://user-images.githubusercontent.com/17798390/59841386-d03bee00-9386-11e9-8085-e9b98ca87dd9.png)
> 
> ![image](https://user-images.githubusercontent.com/17798390/59841464-f5c8f780-9386-11e9-9c76-b0cd79d5a2bb.png)
> 
> ```js
> import {AtTag,AtButton} from 'taro-ui';
> 
> // app.js
> import 'taro-ui/dist/style/index.scss'
> ```
> 
> **期望行为**
> 样式能够被编译
> 
> **报错信息**
> 
> 无报错
> 
> **系统信息**
> 
> ![image](https://user-images.githubusercontent.com/17798390/59842174-90760600-9388-11e9-8e0b-3034e74237eb.png)

@shock-lee  请问这个解决了吗 怎么处理的

**Comment by shock-lee** [comment]
> > **问题描述**
> > 最新的taro，最新的taro-ui，npm run dev:h5，引入taro-ui的组件，taro-ui的组件的样式（px）没有被编译成rem
> > **复现步骤**
> > [复现问题的步骤]
> > ![image](https://user-images.githubusercontent.com/17798390/59841386-d03bee00-9386-11e9-8085-e9b98ca87dd9.png)
> > ![image](https://user-images.githubusercontent.com/17798390/59841464-f5c8f780-9386-11e9-9c76-b0cd79d5a2bb.png)
> > ```js
> > import {AtTag,AtButton} from 'taro-ui';
> > 
> > // app.js
> > import 'taro-ui/dist/style/index.scss'
> > ```
> > 
> > 
> > **期望行为**
> > 样式能够被编译
> > **报错信息**
> > 无报错
> > **系统信息**
> > ![image](https://user-images.githubusercontent.com/17798390/59842174-90760600-9388-11e9-8e0b-3034e74237eb.png)
> 
> @shock-lee 请问这个解决了吗 怎么处理的

在app.scss中引入taro-ui的样式文件。

**Comment by XuChunxiao** [comment]
或参考官方文档可解决:
配置需要额外编译的源码模块
由于引用 `node_modules` 的模块，默认不会编译，所以需要额外给 H5 配置 `esnextModules`，在 taro 项目的 `config/index.js` 中新增如下配置项：
h5: {
  esnextModules: ['taro-ui']
}
