### ISSUE TITLE
建议：Flutter web 转译 Taro 后开发全平台小程序

### ISSUE THREAD

**Issue by GreatGreatGreg** [NervJS/taro#3493]
flutter的思路来源于react。它通过一次编写支持开发app（安卓、ios）、桌面、web程序。但是它缺乏国内小程序的支持
上个月flutter web发布了，转译为标准的javascript、css、html和canvas成为了现实（dart2js）。这些技术完全可以与taro交融。从技术角度上看flutter转译为taro，进而通过taro支持所有平台是可行的

这将是伟大的创新，全球首创！可以大大减轻程序员的负担，解放程序员，减少996.icu

看好并支持taro团队，加油

**Comment by tourze** [comment]
flutter转taro，又要填一波组件差异了吧。。。而且flutter的开发生态完全不同于其他端，难搞。

**Comment by anthhub** [comment]
不如 taro 转 flutter, flutter 一点也不好写

**Comment by Qiyu8** [comment]
Dart2js是DartVM本身就支持的能力，所以比较好实现，已经有类似的探索https://github.com/areslabs/flutter_mp，而taro转flutter涉及到js2Dart这个反向操作，编译的难度大大增加，从腾讯团队的https://github.com/TGIF-iMatrix/MXFlutter架构图可以看出需要对flutter的底层原理有较深入理解，当然如果支持确实更好

**Comment by greatGregLiu** [comment]
https://github.com/areslabs/flutter_mp/issues/6

从最近看到Taro Next的架构看, Flutter 是可以适配小程序的 , 而且这个工作他们自己不做, 要社区去做, 刚好 areslabs团队 有技术,有经验, 可以去做. 这样子京东就把小程序开发难度大大降低了

支持

**Comment by greatGregLiu** [comment]
qq 团队: https://github.com/TGIF-iMatrix/MXFlutter

**Comment by chenchengyin** [comment]
用Flutter 的WebView加载Taro写出来的H5，在Android上正常运行，在IOS上跑不起来，有人遇到过么

**Comment by chenxyzl** [comment]
> [areslabs/flutter_mp#6](https://github.com/areslabs/flutter_mp/issues/6)
> 
> 从最近看到Taro Next的架构看, Flutter 是可以适配小程序的 , 而且这个工作taro自己不做, 要社区去做, 刚好 areslabs团队 有技术,有经验, 可以去做. 这样子京东就把小程序开发难度大大降低了
> 
> 支持

flutter_map 这个项目看起来暂停了的样子，单从思路来说，相当好，期望能继续下去

**Comment by Morris-Mao** [comment]
看好并支持taro团队，加油
