### ISSUE TITLE
从props中取children属性，导致编译成小程序代码错误

### ISSUE THREAD

**Issue by kala888** [NervJS/taro#3494]
新建一个demo项目，package.json
```
 "@tarojs/components": "1.3.2",
    "@tarojs/router": "1.3.2",
    "@tarojs/taro": "1.3.2",
    "@tarojs/taro-alipay": "1.3.2",
    "@tarojs/taro-h5": "1.3.2",
    "@tarojs/taro-swan": "1.3.2",
    "@tarojs/taro-tt": "1.3.2",
    "@tarojs/taro-weapp": "1.3.2",
    "nervjs": "^1.4.0",
    "nerv-devtools": "^1.4.0"
```
创建一个TextComp(正常运行)
```
export default class TextComp extends Taro.PureComponent {
  static defaultProps = {
    lineOfItems: 3,
    paddingHorizontal: 20,
    children:[]
  }

  render() {
    const {
      lineOfItems,
      paddingHorizontal,
    } = this.props
    return (
      <View >
        {paddingHorizontal/lineOfItems}
      </View>
    )
  }
}
```
编译后的小程序代码（正常）
![image](https://user-images.githubusercontent.com/1215976/59893098-4f283980-940e-11e9-939e-11d1facde8a3.png)

修改render方法，增加一行代码，增加从props中取children

```
  render() {
    const {
      lineOfItems,
      paddingHorizontal,
     children, // 这里会导致编译异常
    } = this.props
    return (
      <View >
        {paddingHorizontal/lineOfItems}
      </View>
    )
  }
```

![image](https://user-images.githubusercontent.com/1215976/59893196-c1991980-940e-11e9-951a-b45063cae693.png)

PS: "1.2.27-beta.0" 可以正常使用children

**Comment by jinjinjin0731** [comment]
![image](https://user-images.githubusercontent.com/17409735/59893575-f8bbfa80-940f-11e9-9671-8051c91047a6.png)

文档明确说明不要操作 children 了，和哪个版本能不能用无关。

**Comment by kala888** [comment]
@jinjinjin0731 看到了，谢谢
https://nervjs.github.io/taro/docs/children.html#children
