### ISSUE TITLE
组件的条件渲染

### ISSUE THREAD

**Issue by clarktang** [NervJS/taro#350]
**问题描述**
<img width="604" alt="12323333" src="https://user-images.githubusercontent.com/37982974/42933699-fc3ce198-8b77-11e8-966a-4aa0e473c5e3.png">

![image](https://user-images.githubusercontent.com/37982974/42933946-9b1141d8-8b78-11e8-9b9a-affeeeb33ee9.png)

图中的render是一个页面组件，render中的其他组件都是自定义组件，并且自定义组件render方法中打印该组件render方法是否执行。

有如下几个问题：
1. `queComponent`的值打印出来永远都是`null`
2. 这里是条件渲染，但是所有的自定义组件的render方法都会执行
3. 无论if条件怎么样，所有的自定义组件的compoenntDidMount在初始化的时候都会执行。

**期望行为**
期望真正的条件渲染，如果自定义组件不被使用，不要调用它的render方法，更不要在初始化的时候调用自定义组件的生命周期方法。

**报错信息**
如图所示：
![image](https://user-images.githubusercontent.com/37982974/42934059-d52ea4c8-8b78-11e8-821d-02c063788793.png)

**系统信息**

 - 操作系统:macos
 - Taro 版本 0.0.70
 - Node.js 版本 10.6.0

**Comment by yuche** [comment]
现在的组件化方案是基于 template 实现的，当你引入组件的时候就会自动加载走完生命周期。
新的组件化方案能解决问题能解决这个问题，今晚或明天会发一个 beta 版本。
到时我会 at 你试用一下。

**Comment by clarktang** [comment]
@yuche 第二个问题中，所有的自定义组件的render都会执行，这个也是同样的原因引起的吗？

**Comment by yuche** [comment]
@clarktang 是的

**Comment by luckyadam** [comment]
最新的 beta 版本已经解决了这个问题~

**Comment by hugeorange** [comment]
在这个版本下 "@tarojs/taro": "1.2.12",  还是会出现这个问题啊
![image](https://user-images.githubusercontent.com/18440746/52252193-03339700-293c-11e9-9122-badc87e1d9c1.png)
![image](https://user-images.githubusercontent.com/18440746/52252197-0890e180-293c-11e9-86f3-90edd5834071.png)
![image](https://user-images.githubusercontent.com/18440746/52252199-0af33b80-293c-11e9-9319-94b525b052df.png)

系统信息：macos
nodejs 9.6.1

**Comment by forsigner** [comment]
这个问题有计划解决？
