### ISSUE TITLE
Taro1.3.2 Nervjs1.4.1 使用hooks的组件Jest快照测试报错

### ISSUE THREAD

**Issue by masteroy** [NervJS/taro#3501]
**问题描述**
之前提过相关的issue: https://github.com/NervJS/taro/issues/3342
但更新到最新的nervjs后依然报错
```
invalid hooks call: hooks can only be called in a stateless component.
```
这是我的依赖版本
```
$ yarn list --pattern "nerv|tarojs"
yarn list v1.6.0
├─ @tarojs/cli@1.3.2
├─ @tarojs/components@1.3.2
├─ @tarojs/plugin-babel@1.3.2
├─ @tarojs/plugin-csso@1.3.2
├─ @tarojs/plugin-sass@1.3.2
├─ @tarojs/plugin-uglifyjs@1.3.2
├─ @tarojs/router@1.3.2
├─ @tarojs/taro-h5@1.3.2
├─ @tarojs/taro-weapp@1.3.2
├─ @tarojs/taro@1.3.2
├─ @tarojs/taroize@1.3.2
├─ @tarojs/transformer-wx@1.3.2
├─ @tarojs/utils@1.3.2
├─ @tarojs/webpack-runner@1.3.2
├─ nerv-is-commonjs@1.4.1
├─ nerv-server@1.4.1
├─ nerv-shared@1.4.0
├─ nerv-test-utils@1.4.1
├─ nerv-utils@1.4.1
└─ nervjs@1.4.1
Done in 1.40s.
```

**Comment by luckyadam** [comment]
提供一个 demo 看看吧

**Comment by masteroy** [comment]
@luckyadam 
这是Repo: [taro-unit-test](https://github.com/masteroy/taro-unit-test/tree/master)

**Comment by yuche** [comment]
有两个方案：
1. 降级 Jest 到 Jest 23
2. 在 jest config 中把 react-is alias 到 nerv-is

**Comment by masteroy** [comment]
@yuche 在我的demo里面已经把react-is alias 到nerv-is-commonjs了https://github.com/masteroy/taro-unit-test/blob/master/jest.config.js#L14

**Comment by yuche** [comment]
更新 nerv-server 到 1.4.3 可行。

**Comment by gxbsst** [comment]
`{
  "name": "name",
  "version": "1.0.0",
  "private": true,
  "description": "description",
  "templateInfo": {
    "name": "redux",
    "typescript": false,
    "css": "less"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "test": "jest"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/async-await": "1.3.22",
    "@tarojs/components": "1.3.22",
    "@tarojs/redux": "1.3.22",
    "@tarojs/redux-h5": "1.3.22",
    "@tarojs/router": "1.3.22",
    "@tarojs/taro": "1.3.22",
    "@tarojs/taro-alipay": "1.3.22",
    "@tarojs/taro-h5": "1.3.22",
    "@tarojs/taro-swan": "1.3.22",
    "@tarojs/taro-tt": "1.3.22",
    "@tarojs/taro-weapp": "1.3.22",
    "nerv-devtools": "^1.5.4",
    "nervjs": "^1.5.4",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.7.0",
    "@babel/plugin-proposal-decorators": "^7.7.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.6.2",
    "@babel/plugin-transform-react-jsx": "^7.7.0",
    "@babel/preset-env": "^7.7.1",
    "@tarojs/plugin-babel": "1.3.20",
    "@tarojs/plugin-csso": "1.3.20",
    "@tarojs/plugin-less": "1.3.20",
    "@tarojs/plugin-uglifyjs": "1.3.20",
    "@tarojs/webpack-runner": "1.3.20",
    "@testing-library/dom": "^6.10.1",
    "@testing-library/jest-dom": "^4.2.3",
    "@types/jest": "^24.0.22",
    "@types/react": "^16.4.8",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^24.9.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-taroapi": "^1.3.22",
    "babel-preset-env": "^1.6.1",
    "eslint": "^5.16.0",
    "eslint-config-taro": "1.3.20",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "eslint-plugin-taro": "^1.3.22",
    "jest": "^24.9.0",
    "jsdom": "^15.2.1",
    "jsdom-global": "^3.0.2",
    "nerv-is": "1.4.3",
    "nerv-is-commonjs": "^1.4.1",
    "nerv-server": "^1.5.4",
    "nerv-test-utils": "^1.5.4",
    "redux-mock-store": "^1.5.3",
    "stylelint": "9.3.0",
    "stylelint-config-taro-rn": "1.3.20",
    "stylelint-taro-rn": "1.3.20"
  }
}
`


## 测试代码
`
import { renderIntoDocument, isElement, findAllInRenderedTree } from 'nerv-test-utils'
import { render } from '@tarojs/taro'
import IndexPage from '../index'

describe('@IndexPage', () => {
  it('should work', () => {
    const r = renderIntoDocument(<IndexPage initialCount={1} />) 
  })
})
`

## 组件代码

`
import { View } from '@tarojs/components'
import { useState } from '@tarojs/taro'
import './index.less'

export default function IndexPage (){
  const [count, setCount] = useState(1)
  return (
    <View>
      Count: {count}
    </View>
  )
}
`
## 错误

`

Error: invalid hooks call: hooks can only be called in a stateless component.

`
