### ISSUE TITLE
H5  swiper 手动设置 current 为 0 无效

### ISSUE THREAD

**Issue by ppbl** [NervJS/taro#3516]
**问题描述**
H5  swiper组件， 手动设置 current 为 0 无效

**复现步骤**

1. 引入 swiper
2. current 属性受控， 改变current, 其他值可以正常滑动， 0 无效

```jsx
const [current, setCurrent] = useState(2);

setCurrent(0);

<Swiper
    onChange={handleChange}
    current={current}
>
 ```

**期望行为**
滑到第一个滑块

**报错信息**
不报错，但是没有反应

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.3]
 - Node.js 版本 [v12.4.0]
 - 报错平台 [h5]

**Comment by singagain** [comment]
你怎么解决的，我也遇到这个问题
