### ISSUE TITLE
打包快应用时，在快应用调试器可以看效果，但在快应用开发工具ide不能预览。

### ISSUE THREAD

**Issue by zw888** [NervJS/taro#3518]
taro build --type quickapp --watch  打包快应用时，手机快应用调试器可以预览效果
但将dist打包后的文件放到快应用开发工具IDE中不能预览。这个是我这边的方法不对么？请大神请教。

预览之前在ide中也试过 npm run server 了，还是不行。

**Comment by zw888** [comment]
![image](https://user-images.githubusercontent.com/33955555/60009039-b9a7d680-96a7-11e9-8915-f9332d021865.png)

**Comment by luckyadam** [comment]
不对吧，调试器代开的应该是 dist 里的编译后代码

**Comment by zw888** [comment]
> 不对吧，调试器代开的应该是 dist 里的编译后代码

大佬，这个问题解决是了，是快应用那边的ide的原因。更新了ide就可以了。但是现在有个问题，快应用的提供的组件无法在taro中使用，我想问问现在taro转化快应用的功能是不是还没有完善
