### ISSUE TITLE
Cannot read property 'extraProps' of undefined;at api nextTick callback function

### ISSUE THREAD

**Issue by broven** [NervJS/taro#3519]
**问题描述**
Cannot read property 'extraProps' of undefined;at api nextTick callback function
源代码: https://github.com/NervJS/taro/blob/506ca025afcdaf301cf1d01820beae831c56f605/packages/taro-weapp/src/propsManager.js#L26
commit:
https://github.com/NervJS/taro/commit/506ca025afcdaf301cf1d01820beae831c56f605
**复现步骤**

```js
看下我给你们的代码链接, class 上哪里有 this.data.extraProps
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
👽 Taro v1.3.3

  Taro CLI 1.3.3 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.3 => 1.3.3
      @tarojs/mobx: 1.3.3 => 1.3.3
      @tarojs/mobx-h5: 1.3.3 => 1.3.3
      @tarojs/mobx-rn: 1.3.3 => 1.3.3
      @tarojs/plugin-babel: 1.3.3 => 1.3.3
      @tarojs/plugin-csso: 1.3.3 => 1.3.3
      @tarojs/plugin-less: 1.3.3 => 1.3.3
      @tarojs/plugin-sass: 1.3.3 => 1.3.3
      @tarojs/plugin-uglifyjs: 1.3.3 => 1.3.3
      @tarojs/rn-runner: 1.3.3 => 1.3.3
      @tarojs/router: 1.3.3 => 1.3.3
      @tarojs/taro: 1.3.3 => 1.3.3
      @tarojs/taro-alipay: 1.3.3 => 1.3.3
      @tarojs/taro-h5: 1.3.3 => 1.3.3
      @tarojs/taro-swan: 1.3.3 => 1.3.3
      @tarojs/taro-tt: 1.3.3 => 1.3.3
      @tarojs/taro-weapp: 1.3.3 => 1.3.3
      @tarojs/webpack-runner: 1.3.3 => 1.3.3
      eslint-config-taro: 1.3.3 => 1.3.3
      eslint-plugin-taro: 1.3.3 => 1.3.3
      nerv-devtools: ^1.4.1 => 1.4.1
      nervjs: ^1.4.1 => 1.4.1

[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by broven** [comment]
![image](https://user-images.githubusercontent.com/12854613/60009993-75b5d100-96a9-11e9-88c7-d3078ad46770.png)

**Comment by luckyadam** [comment]
3deb1a797d3c6039ff6894db8b1589863346f019

**Comment by liu-dongyu** [comment]
更新v1.3.3后遇到同样错误，上方fix似乎没发布，只能回退v1.3.2了..

**Comment by broven** [comment]
嗯，回退后锁版本吧。 他们这块写的有点草率。看后面能不能加些测试覆盖到


On 06/25/2019 09:24, Liu Dongyu wrote:

更新v1.3.3后遇到同样错误，上方fix似乎没发布，只能回退v1.3.2了..

**Comment by jinjinjin0731** [comment]
已经发布了 更新到 1.3.4 吧
