### ISSUE TITLE
render方法中，console出来的值和页面中的值不一致

### ISSUE THREAD

**Issue by maoyifanDev** [NervJS/taro#3520]
**问题描述**
页面render方法中，同一个变量，console.log出来的值和页面中展示的值不一致

**复现步骤**
[复现问题的步骤]
1. 使用mobx
2. 在store中写一个累加器
3. 在累加的过程中修改loading状态

```js
addNum = () => {
    this.props.testStore.addNum()
  }

render () {
    const testStore = this.props.testStore
    const { num, loading } = testStore
    // const adding = loading.addNum
    console.log('loading.addNum', loading.addNum)
    return (
      <View className="index">
        <View onClick={this.addNum}>
          <View>
            {loading.addNum}-{num}
          </View>
        </View>
      </View>
    )
  }
```
```
class TestStore {
  @observable
  num = 1
  @observable
  loading = {
    addNum: 'aaaa',
  }

  @action
  addNum () {
    this.loading.addNum = 'bbbb'
    setTimeout(() => {
      this.loading.addNum = 'cccc'
      this.num++
    }, 1000)
  }
}

export default TestStore
```

**期望行为**
console.log出来的`loading.addNum`应该与页面中显示的一致，然而在点击过程中，并非一致

**更换写法**
如果，将`loading.addNum`用一个变量代替，如上代码，用`adding`来代替，页面中也用`adding`，页面将会正常展示，why？

**其他平台测试信息**
h5中表现正常，打印出来的`loading.addNum`与页面展示的一致

**系统信息**
 - 操作系统: [macOS]
 - Taro 版本 [v.1.3.2]
 - Node.js 版本 [v8.10.0]
 - 报错平台 [alipay]

**Comment by nanjingboy** [comment]
@maoyifanDev 小程序中监听的是 `_createData` 方法，你看编译后的代码，如果使用 `const adding = loading.addNum`，那么这个值就在 `_createData` 方法内，所以值改变的时候能够触发更新，这一点文档中说的很明白了，所以按照 taro 的文档，而不是 mobx-react 的文档。

**Comment by maoyifanDev** [comment]
> @maoyifanDev 小程序中监听的是 `_createData` 方法，你看编译后的代码，如果使用 `const adding = loading.addNum`，那么这个值就在 `_createData` 方法内，所以值改变的时候能够触发更新，这一点文档中说的很明白了，所以按照 taro 的文档，而不是 mobx-react 的文档。

我们站在一个普通使用Taro开发者的角度，我们并不关心值是不是在`_createData `方法内，因为我们不知道编译出来是什么样的。所以站在普通react开发角度，`console.log('loading.addNum', loading.addNum)`出来的值，就应该是和`<View>{loading.addNum}</View>`页面中的值一致的，因为从开发者角度，这就是同一个东西，为啥会不一样，希望得到解决，多谢
