### ISSUE TITLE
-webkit-box-orient: vertical; 打包后丢失了

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#3521]
问题描述
-webkit-box-orient: vertical; 打包后丢失了

display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
打包后：

    display: -webkit-box;
    -webkit-line-clamp: 2;
    overflow: hidden;
    text-overflow: ellipsis;
导致多行省略不生效

 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.0]
 - Node.js 版本 [10.14.1]
 - 报错平台 [h5]

**Comment by Garfield550** [comment]
Dup #3399

**Comment by guggit** [comment]
> Dup #3399
> 
> https://stackoverflow.com/questions/46152850/webkit-box-orient-styling-disappears-from-styling

谢谢。
参考：：
 /* autoprefixer: ignore next */
   -webkit-box-orient: vertical;

**Comment by zhangtong1993** [comment]
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;  使用这种还是不行

**Comment by Garfield550** [comment]
@zhangtong1993 建议新开一个 Issue，详细描述一下你的过程并提供一些复现代码，并且按照要求提供 Taro 和相关依赖的版本。

**Comment by yuuk** [comment]
都没解决就把issue关了。。。？
