### ISSUE TITLE
swiper的滑动有没有uniapp那样的previous-margin和next-margin属性，实现这样的效果

### ISSUE THREAD

**Issue by bb798sky** [NervJS/taro#3525]
swiper的滑动有没有uniapp那样的previous-margin和next-margin属性，实现这样的效果

![image](https://user-images.githubusercontent.com/39869566/59553404-1d0a7800-8fc7-11e9-9a97-421c6ba32308.png)

**Comment by jinjinjin0731** [comment]
参考这篇文章 [利用Taro的Swiper组件实现3D 覆盖流效果](https://taro-club.jd.com/topic/96/%E5%88%A9%E7%94%A8taro%E7%9A%84swiper%E7%BB%84%E4%BB%B6%E5%AE%9E%E7%8E%B03d-%E8%A6%86%E7%9B%96%E6%B5%81%E6%95%88%E6%9E%9C)
