### ISSUE TITLE
video controls属性

### ISSUE THREAD

**Issue by xiafengaha** [NervJS/taro#3526]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[video 标签加入controls属性为true时，在控制台打印出video实例，其他的controls属性为false，也导致了poster属性失效]

**复现步骤**
[复现问题的步骤]

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```js

// 这里可以贴代码

<Video
           src={src}
           controls
           direction
           poster={img}
           preload='true'
         />


// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
[video controls能根据传入的显示]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOs]
 - Taro 版本 [1.3.4]
 - Node.js 版本 [10.15.3]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
[video 标签加入controls属性为true时，在控制台打印出video实例，其他的controls属性为false，也导致了poster属性失效]   这句话是什么意思？  有前后的对比图贴一下么

**Comment by Garfield550** [comment]
可能他想说的是 controls 为 true 时 poster 属性无效吧。不过我没测试过，只是根据他的描述进行猜测。

**Comment by xiafengaha** [comment]
controls的属性为true的时候，我在componentDidMount生命周期里面，document.getElementsByTagName('video')打印出这个video实例，实例里面的controls属性不管我在Video标签传true还是false，显示的永远是false,也就导致了poster属性无效。现在说清楚了吗？

**Comment by xiafengaha** [comment]
> [video 标签加入controls属性为true时，在控制台打印出video实例，其他的controls属性为false，也导致了poster属性失效] 这句话是什么意思？有前后的对比图贴一下么

controls的属性为true的时候，我在componentDidMount生命周期里面，document.getElementsByTagName('video')打印出这个video实例，实例里面的controls属性不管我在Video标签传true还是false，显示的永远是false,也就导致了poster属性无效。现在说清楚了吗？

**Comment by jinjinjin0731** [comment]
不要获取 video 这个标签。 这个标签是个占位。 你看生成出来的 dom 元素就知道了。 其他的样式全是自定义模拟出来的。 controls 与 poster 的控制属性逻辑并不在 video 这个标签上

**Comment by jinjinjin0731** [comment]
如果你设置 controls 了 true , poster 还是失效了。 贴一下你这个页面的完整 jsx 代码，我这边没有复现

**Comment by xiafengaha** [comment]
> 如果你设置 controls 了 true , poster 还是失效了。 贴一下你这个页面的完整 jsx 代码，我这边没有复现

![image](https://user-images.githubusercontent.com/26809910/60146975-2cc36100-97fe-11e9-8b8a-957237fb4688.png)
具体Video的标签代码就是这样

**Comment by xiafengaha** [comment]
> > 如果你设置 controls 了 true , poster 还是失效了。 贴一下你这个页面的完整 jsx 代码，我这边没有复现
> 
> ![image](https://user-images.githubusercontent.com/26809910/60146975-2cc36100-97fe-11e9-8b8a-957237fb4688.png)
> 具体Video的标签代码就是这样

我如果把Video标签替换成h5 的video标签，这样写是会有预览图出现的

**Comment by xiafengaha** [comment]
> > > 如果你设置 controls 了 true , poster 还是失效了。 贴一下你这个页面的完整 jsx 代码，我这边没有复现
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26809910/60146975-2cc36100-97fe-11e9-8b8a-957237fb4688.png)
> > 具体Video的标签代码就是这样
> 
> 我如果把Video标签替换成h5 的video标签，这样写是会有预览图出现的

poster的url错了，你可自行替换成图片url就可以了

**Comment by jinjinjin0731** [comment]
有一个属性影响到， 组件的 onDurationChange 这个属性。  这个等下提交修复。

**Comment by carlSunLiang** [comment]
![image](https://user-images.githubusercontent.com/8129970/62332288-7b48d700-b4f1-11e9-8799-916cbfa60461.png)
![image](https://user-images.githubusercontent.com/8129970/62332302-8a2f8980-b4f1-11e9-8e3d-e10fc34e508e.png)
我设置了 但是海报没有显示，直接就是一闪而过
