### ISSUE TITLE
使用React.lazy预加载组件，import 导入组件会编译失败

### ISSUE THREAD

**Issue by liweiSm** [NervJS/taro#3529]
**问题描述**
   微信小程序需要实现功能组件预加载，所以我用了 React.lazy() 但是打包编译的时候报错导致编译不通过，后来我换了一种方式（react-loadable）进行组件预加载，但是编译还是不通过，报错都是指向import，不知道是不是taro不支持代码中的import

![image](https://user-images.githubusercontent.com/20532827/60069563-e7435d00-9745-11e9-986b-eb20f75958c1.png)

下面是代码：
// ```js
 "React.lazy(() => import('./components/preconditionPage'))"
// ```

```

**期望行为**
希望能告知是什么问题，另外如果是平台的问题能不能有其它好的替代方案实现预加载功能

**系统信息**
 - 操作系统:  Windows 10
 - Taro 版本 1.3.2
 - Node.js 版本 11.13.0
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
1. 不使用支持 React 的方法，你只能从 Taro 对象下面取；
2. 需要遵循 Taro 组件规范的第三方组件才能使用

**Comment by liweiSm** [comment]
> 1. 不使用支持React的方法，你只能从Taro对象下面取;
> 2. 需要遵循Taro组件规范的第三方组件才能使用

我试过用Taro，但是taro没有lazy函数，也没有Suspense，那是不是说明在taro中就无法使用lazy预加载了，会有其它方式吗

**Comment by yuche** [comment]
小程序没有预加载这个概念，所有包都是一次性加载完毕的。类似的东西叫分包。

**Comment by liweiSm** [comment]
> 小程序没有预加载这个概念，所有包都是一次性加载完毕的。类似的东西叫分包。

这样啊，那我换种方式来实现，好的，非常感谢

**Comment by seawind8888** [comment]
@liweiSm 请问你最后的实现方案是怎样的呢，我正好也遇到这样的问题

**Comment by liweiSm** [comment]
> @liweiSm 请问你最后的实现方案是怎样的呢，我正好也遇到这样的问题

小程序不能用预加载，换种方式实现吧，先import 组件进来，根据业务去判断加载

**Comment by Derekgogo** [comment]
> @liweiSm 请问你最后的实现方案是怎样的呢，我正好也遇到这样的问题

https://blog.csdn.net/qq_36977923/article/details/124153107
我是这么做的
