### ISSUE TITLE
Taro中小程序里阻止事件捕获

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#3532]
**问题描述**
有一个组件A，传参数渲染子节点（this.props.children），组件A最外层有一个点击事件，子节点最外层也有一个点击事件，我想在某些情况下点击组件A的时候，不执行this.props.children最外层的点击事件（事件捕获），小程序文档：https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/event.html#%E4%BA%8B%E4%BB%B6%E8%AF%A6%E8%A7%A3，请问小程序怎么编写阻止事件捕获的代码，Taro文档中没有找到。

**系统信息**
Taro CLI 1.3.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.2 => 1.3.2 
      @tarojs/components: 1.3.2 => 1.3.2 
      @tarojs/plugin-babel: 1.3.2 => 1.3.2 
      @tarojs/plugin-csso: 1.3.2 => 1.3.2 
      @tarojs/plugin-less: 1.3.2 => 1.3.2 
      @tarojs/plugin-uglifyjs: 1.3.2 => 1.3.2 
      @tarojs/redux: 1.3.2 => 1.3.2 
      @tarojs/router: 1.3.2 => 1.3.2 
      @tarojs/taro: 1.3.2 => 1.3.2 
      @tarojs/taro-alipay: 1.3.2 => 1.3.2 
      @tarojs/taro-h5: 1.3.2 => 1.3.2 
      @tarojs/taro-swan: 1.3.2 => 1.3.2 
      @tarojs/taro-tt: 1.3.2 => 1.3.2 
      @tarojs/taro-weapp: 1.3.2 => 1.3.2 
      @tarojs/webpack-runner: 1.3.2 => 1.3.2 
      eslint-config-taro: 1.3.2 => 1.3.2 
      eslint-plugin-taro: 1.3.2 => 1.3.2 
      nerv-devtools: ^1.4.1 => 1.4.1 
      nervjs: ^1.4.1 => 1.4.1

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/533
