### ISSUE TITLE
taro模板中，不能直接用快应用原生组件。

### ISSUE THREAD

**Issue by zw888** [NervJS/taro#3533]
![image](https://user-images.githubusercontent.com/33955555/60076875-3d6ecb00-975b-11e9-98c0-23485fcd6295.png)

**Comment by jinjinjin0731** [comment]
编译有报错么？

**Comment by jinjinjin0731** [comment]
引入 Progress ，用 Taro Progress 这个组件有什么问题吗？

**Comment by luckyadam** [comment]
可以用啊
