### ISSUE TITLE
在render组件中，无法在map中绑定事件

### ISSUE THREAD

**Issue by liu-dongyu** [NervJS/taro#3536]
**问题描述**
在render组件中，无法在`map`中绑定`onClick`事件

**复现步骤**
```js
import Taro from '@tarojs/taro'
import { View, Block } from '@tarojs/components'

function Demo () {
  const data = [{ id: 1, val: 'demo' }]
  const onClickDemo = () => {
    console.log(11)
  }
  const renderDemo = () => (
    <Block>
      {data.map(item => (
        // 不使用onClick则正常
        <View key={String(item.id)} onClick={onClickDemo}>
          {item.val}
        </View>
      ))}
    </Block>
  )
  
  return <View>{renderDemo()}</View>
}

export default Demo
```

**期望行为**
能绑定事件

**报错信息**
![WechatIMG381](https://user-images.githubusercontent.com/16187601/60077049-a0f8f880-975b-11e9-91e0-6aeaa915388e.jpeg)

**系统信息**
  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.6.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/cli: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: ^1.3.1 => 1.3.2 
      @tarojs/redux-h5: ^1.3.1 => 1.3.2 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.1 
      nervjs: ^1.4.0 => 1.4.1 
报错平台 weapp

**Comment by yuche** [comment]
1.

```
  const renderDemo = () => (
    <Block>
      {data.map(item => {
        // 不使用onClick则正常
        return <View key={String(item.id)} onClick={onClickDemo}>
          {item.val}
        </View>
      })}
    </Block>
  )
```

2. 

```
  const renderDemo = () => (
    <Block>
      {data.map(item => {
        // 不使用onClick则正常
        return <View key={item.id} onClick={onClickDemo}>
          {item.val}
        </View>
      })}
    </Block>
  )
```
