### ISSUE TITLE
Taro H5打包报错

### ISSUE THREAD

**Issue by Tyf2345** [NervJS/taro#3538]
Taro H5打包报错
./node_modules/taro-ui/dist/h5/components/countdown/index.js 105:11
Module parse failed: Unexpected token (105:11)
You may need an appropriate loader to handle this file type.
|     } = this.state;
|
>     return <View className={classNames({
|       'at-countdown': true,
|       'at-countdown--card': isCard

Done in 26.75s.

版本信息
 "dependencies": {
    "@tarojs/components": "1.2.26",
    "@tarojs/router": "1.2.26",
    "@tarojs/taro": "1.2.26",
    "@tarojs/taro-alipay": "1.2.26",
    "@tarojs/taro-h5": "1.2.26",
    "@tarojs/taro-swan": "1.2.26",
    "@tarojs/taro-tt": "1.2.26",
    "@tarojs/taro-weapp": "1.2.26",
    "axios": "^0.19.0",
    "js-cookie": "^2.2.0",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "taro-ui": "^2.2.1"
  },

**Comment by Littly** [comment]
https://taro-ui.aotu.io/#/docs/questions
