### ISSUE TITLE
根据条件渲染子组件，切换状态的时候 子组件生命周期componentDidShow没执行，息屏再次展示页面子组件的componentDidShow才会执行

### ISSUE THREAD

**Issue by zantop** [NervJS/taro#3540]
根据条件渲染子组件，切换状态的时候 子组件生命周期componentDidShow没执行，息屏再次展示页面子组件的componentDidShow才会执行

父组件
` {currentPage === 'home' ? <Home /> : null}
{currentPage === 'element' ? <Element /> : null}
`

**Comment by Chen-jj** [comment]
@zantop 请提供详细信息。建议写份原生测试对比。

**Comment by luckyadam** [comment]
子组件的 componentDidShow 是跟随页面的 componentDidShow 的，所以组件动态切换是不会触发组件的 componentDidShow，你应该用子组件的 componentWillRecieveProps
