### ISSUE TITLE
【快应用】事件传参数不成功

### ISSUE THREAD

**Issue by KwongyeeChia** [NervJS/taro#3545]
**问题描述**
[问题描述：遍历后的元素事件绑定传递参数异常，无法正常获取参数]

**复现步骤**
[复现问题的步骤]
1.对组件循环过后，对里面的元素添加事件绑定，点击传递参数
```js
handleNavigate(target,id,e) {
  console.log('target',target)
  console.log('id',id)
  console.log('e',e)
  // Taro.navigateTo({
  //   url: 'pages/bookDetail/index?bookId=253'
  // })
}
```
```js
arr.map(i=>{
<View className='novelBookSingle' onClick={this.handleNavigate.bind(this,i.bookId)}></View>
})
```

**期望行为**
获取bind事件传入的参数

**报错信息**

![image](https://user-images.githubusercontent.com/39576364/60146347-d8b77d00-97fb-11e9-921b-01aaa700ff6d.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by KwongyeeChia** [comment]
解决了...麻烦官方给出taro相应得快应用注意事项文档
```js
<View className='novelBookSingle' onClick={this.handleNavigate.bind(this)} bookid={id} cover={cover}>

**Comment by KwongyeeChia** [comment]
```js
<View className='novelBookSingle' onClick={this.handleNavigate.bind(this)} bookid={id} cover={cover}>

**Comment by KwongyeeChia** [comment]
```js
<View className='novelBookSingle' onClick={this.handleNavigate.bind(this)} bookid={id} cover={cover}>
```
```js
handleNavigate(e) {
  console.log('bookid', JSON.stringify(e.target.attr))
  let { bookId } = e.target.attr
  Taro.navigateTo({
    url: 'pages/bookDetail/index?bookId='+bookId
  })
}
```

**Comment by KwongyeeChia** [comment]
以上是传参方法，麻烦taro官方 给出相应 taro写快应用得相应注意事项，更新开发手册

**Comment by luckyadam** [comment]
已经修复了
