### ISSUE TITLE
Taro转百度小程序,setState报错 Invalid Expression in Data set:0

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#3549]
**问题描述**
Taro在百度小程序中执行setState，控制台报错

**复现步骤**
[复现问题的步骤]
1. npm run dev:swan
2. 百度小程序开发工具打开swan，并配置appid
3. 点击按钮执行setState，控制台报错

```js
toggleSearchTypeLayer() {
    let { showLayer = false } = this.state;
    this.setState({
      value: '',
      showLayer: !showLayer,
      isSuggest: false,
      isLoadSuggest: false,
      suggestList: [],
    });
  }
<View
          className='type-select'
          onClick={this.toggleSearchTypeLayer.bind(this)}
        ></View>
```

**期望行为**
执行setState成功并刷新视图

**报错信息**

![image](https://user-images.githubusercontent.com/42051272/60159373-9b67e500-9825-11e9-8dc7-6d87fc12b297.png)

**系统信息**
Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-less: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3

**Comment by Chen-jj** [comment]
@VFiee https://nervjs.github.io/taro/docs/debug.html#debug-diff

**Comment by VFiee** [comment]
> @VFiee https://nervjs.github.io/taro/docs/debug.html#debug-diff
原因：看到控制台报错，UI又没有刷新，所以以为是setState的问题，今天查看按照文档查看setState的diffData发现state是更新成功的，UI也刷新了。但是存在另外一个问题，这是个是我的函数
```js
```

**Comment by Chen-jj** [comment]
@VFiee 老哥你提供一份完整可跑的代码吧，你提供的代码信息缺失这么多，我们很难定位。

**Comment by VFiee** [comment]
> @VFiee 老哥你提供一份完整可跑的代码吧，你提供的代码信息缺失这么多，我们很难定位。
> 
> 刷新的问题按文档打印 setData 的值、结合 xml 模板变量来看吧，看 diff 过滤后的值是否正确，自己检查一下业务逻辑是否正确。

```js
     renderSearchType() {
    let { isSingle = '', type = '', showLayer = false } = this.state;
   //  问题出在这个变量data，如果变量修改为其它变量名就可以了，上面已经说过了，setState没问题，也按照文档排查问题了，diffData也没问题，所以最终的问题就是这个变量名为data，所以渲染数据的时候出不来，我修改为其它变量名就可以了。（需要测试的话随便写个render组件函数即可。）
    const data = isSingle ?
      _.filter(ConfigType, curr => curr.type === type) :
      ConfigType;
    console.log(data);
    return (
      !!showLayer && <View className='type-list'>
        {[1, 2, 3].map((item, index) => <View>{item}</View>)}
        {/* {data.map((item, key) =>
          <View
            key={`type-item-${key}`}
            className={`type-item ${item.type === type ? 'active' : ''}`}
            onClick={this.changeSearchType.bind(this, item.type)}
          >
            {item.title}
          </View>
        )} */}
      </View>
    );
  }
```



问题已自行解决，总结一下
是代码变量设置为data，然后循环的时候没有循环出来，换成其它变量就可以了。
