### ISSUE TITLE
rn 运行不能打开终端的问题

### ISSUE THREAD

**Issue by Mihawk-zhao** [NervJS/taro#3550]
**问题描述**
npm run dev:rn打不开终端，就用yarn dev:rn尝试吧

![image](https://user-images.githubusercontent.com/19793378/60159511-e681f800-9825-11e9-9a18-00d13bda7ad8.png)

**Comment by Pines-Cheng** [comment]
直接运行 taro build --type rn --watch 呢？

**Comment by NotMeIsMe** [comment]
我也是这个问题

**Comment by NotMeIsMe** [comment]
初始化完毕，监听文件修改中...
之后并没有弹出终端。

**Comment by Mihawk-zhao** [comment]
npm run dev:rn            yarn dev:rn             taro build --type rn --watch 都试下，

**Comment by Mihawk-zhao** [comment]
> 初始化完毕，监听文件修改中...
> 之后并没有弹出终端。

npm run dev:rn yarn dev:rn taro build --type rn --watch 都试下，

**Comment by Mihawk-zhao** [comment]
> 初始化完毕，监听文件修改中...
> 之后并没有弹出终端。

npm run dev:rn           yarn dev:rn           taro build --type rn --watch 都试下，

**Comment by Mihawk-zhao** [comment]
> 初始化完毕，监听文件修改中...
> 之后并没有弹出终端。

npm run dev:rn 、、、、yarn dev:rn、、、、 taro build --type rn --watch 都试下，

**Comment by yikalosi** [comment]
在window下没有弹出终端

**Comment by yikalosi** [comment]
@Mihawk-zhao 你taro 版本是什么1.3.4吗

**Comment by Pines-Cheng** [comment]
如果还是无法弹出终端，就在 Taro 工程下手动运行一下：`react-native start` 启动终端。
