### ISSUE TITLE
[快应用] 列表子组件做父组件局部数据刷新不成功

### ISSUE THREAD

**Issue by KwongyeeChia** [NervJS/taro#3551]
**问题描述**
使用子组件触发返回新的数据setState父组件的对应值，数据有变动，dom视图不重绘

**复现步骤**
[复现问题的步骤]
1. 写一个子组件，循环它
2. 子组件绑定事件，回调新的列表数据给父组件
3. 父组件拿到子组件的更新数据，进行局部数据刷新

```js
arr.map(i=>{
<NovelTitle column={i} repeatbookid={novelRepeatBookId} onSunTrigger={this.getSunCall.bind(this)} />
```
 ```js
getSunCall(e,columnid) {
    // console.log('columnid:',columnid)
    let { novelColumn } = this.state
    let shallowCopy = Object.assign({},novelColumn)
    console.log('fresh data:', JSON.stringify(e.books))
    console.log('oldData',JSON.stringify(novelColumn.columns[0]))
    console.log('shallowCopy',JSON.stringify(shallowCopy.columns[0]))
    for (let i in shallowCopy.columns) {
      // 找到对应分栏
      if (shallowCopy.columns[i].id == columnid) {
        shallowCopy.columns[i].books = e.books
        this.setState({
          novelColumn: shallowCopy
        })
      }
    }
  }
```

**期望行为**
dom能根据数据做对应渲染，key有正确的添加唯一id

**系统信息**
Taro CLI 1.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
没能复现这个问题，能否提供一个 demo

**Comment by KwongyeeChia** [comment]
已经解决了 出现的原因是外层循环 里面的组件 里面的组件又套了组件 可能是组件之间耦合太深 导致的


 
---原始邮件---
发件人: "Li,Weitao"<notifications@github.com>
发送时间: 2019年7月2日(星期二) 晚上7:32
收件人: "NervJS/taro"<taro@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"Kwongyee"<871302121@qq.com>;
主题: Re: [NervJS/taro] [快应用] 列表子组件做父组件局部数据刷新不成功 (#3551)



没能复现这个问题，能否提供一个 demo
