### ISSUE TITLE
require nodejs核心模块：引用无法找到

### ISSUE THREAD

**Issue by DarcyXf** [NervJS/taro#3552]
**问题描述**
[迁移一部分功能到Taro中，这部分功能使用到了nodejs的核心模块，如【url, querystring】,此时cli会报引用不存在]

```js
action.js:
const url = require('url')
...
```

**期望行为**
如何解决这种依赖问题呢？

**报错信息**

修改  JS文件    src/store/net/action.js
错误  引用文件  文件 /Users/admin/Documents/ws/miniprogram/src/store/net/action.js 中引用 ../../../../url 不存在！
生成  依赖文件  dist/weapp/store/net/action.js
(node:81393) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'url'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /Users/admin/Documents/ws/miniprogram/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:175:30
...

**系统信息**
  Taro CLI 1.3.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.1 => 1.3.1
      @tarojs/cli: ^1.3.4 => 1.3.4
      @tarojs/components: 1.3.1 => 1.3.1
      @tarojs/plugin-babel: 1.3.1 => 1.3.1
      @tarojs/plugin-csso: 1.3.1 => 1.3.1
      @tarojs/plugin-sass: 1.3.1 => 1.3.1
      @tarojs/plugin-uglifyjs: 1.3.1 => 1.3.1
      @tarojs/redux: 1.3.1 => 1.3.1
      @tarojs/redux-h5: 1.3.1 => 1.3.1
      @tarojs/router: 1.3.1 => 1.3.1
      @tarojs/taro: 1.3.1 => 1.3.1
      @tarojs/taro-alipay: 1.3.1 => 1.3.1
      @tarojs/taro-h5: 1.3.1 => 1.3.1
      @tarojs/taro-swan: 1.3.1 => 1.3.1
      @tarojs/taro-tt: 1.3.1 => 1.3.1
      @tarojs/taro-weapp: 1.3.1 => 1.3.1
      @tarojs/webpack-runner: 1.3.1 => 1.3.1
      eslint-config-taro: 1.3.1 => 1.3.1
      eslint-plugin-taro: 1.3.1 => 1.3.1
      nerv-devtools: ^1.4.0 => 1.4.3
      nervjs: ^1.4.0 => 1.4.3

**Comment by luckyadam** [comment]
使用不了 node 的模块
