### ISSUE TITLE
Taro转百度小程序，组件中使用this.props.children，页面无法显示

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#3553]
**问题描述**
使用Taro文档中Children，无法显示出来https://nervjs.github.io/taro/docs/children.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**复现步骤**
[复现问题的步骤]
1. 编写组件A
2. 页面B引用组件A， <A>
<View>Taro Children</View>
</A>
3. 百度开发工具运行，无法显示

```js
组件A
renderPropsChildren() {
        return <View>
            {this.props.children}
        </View>
    }
render() {
        return <View>
            {this.renderPropsChildren()}
        </View>
    }
页面B
  <Authorize>
            <View>Taro children</View>
  </Authorize>
```

**期望行为**
经过多次尝试，在组件A中如果不使用renderPropsChildren函数渲染，而是直接在render方法中直接return <View>{this.props.children}</View>是可以，但是我需要在renderPropsChildren函数进行逻辑判断渲染。期望在renderPropsChildren中正常渲染(微信小程序没问题)

**报错信息**
无法显示传入的Children

**系统信息**
 Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-less: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3

**Comment by yuche** [comment]
初步怀疑是百度小程序支持在 template 中使用 slot，你可以先把 `renderPropsChildren` 做成一个独立的组件。

**Comment by VFiee** [comment]
> 初步怀疑是百度小程序支持在 template 中使用 slot，你可以先把 `renderPropsChildren` 做成一个独立的组件。

百度小程序支持slot，链接https://smartprogram.baidu.com/docs/develop/framework/custom-component_temp/

**Comment by VFiee** [comment]
请问一下，有计划兼容renderPropsChildren在百度小程序中的问题么？

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。
