### ISSUE TITLE
rn 导航栏底边阴影怎么去掉

### ISSUE THREAD

**Issue by Mihawk-zhao** [NervJS/taro#3557]
**问题描述**
如图，RN端，想把底部阴影去掉，怎么去掉啊
![image](https://user-images.githubusercontent.com/19793378/60165398-cc4e1700-9831-11e9-8a33-d53f42d30232.png)

**复现步骤**
1.初始化项目，RN端，加导航栏的。

**Comment by Pines-Cheng** [comment]
默认导航栏样式，暂时没有提供修改的接口。
