### ISSUE TITLE
【taroize】taroize转换模板参数wx:scope-data失败

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3559]
**问题描述**
[问题描述：taro convert转换微信小程序，转换模板参数：wx:scope-data失败]

**复现步骤**
[复现问题的步骤]
1. 微信小程序下执行taro convert
2. Error: 转换模板参数： `wx:scope-data: {{...scopeData}}` 报错

**期望行为**
[wxml中wx:scope-data可以使用taroize转换成功]

**报错信息**

[Error: 转换模板参数： `wx:scope-data: {{...scopeData}}` 报错]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.2]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
wx:scope-data为微信新属性，可能还没有做转换支持

**Comment by yuche** [comment]
`wx:scope-data` 起一个什么作用，似乎微信小程序文档里没有描述这个的文档。

**Comment by loosenRogers** [comment]
文档中确实还没有详细文档  只在[开发版日志](https://developers.weixin.qq.com/miniprogram/dev/devtools/nightly.html#2019.05.07)提过
先关了吧   等出详细文档吧
