### ISSUE TITLE
taro 编译字节跳动小程序后出现parserScriptError,微信小程序内没有问题

### ISSUE THREAD

**Issue by y449329998** [NervJS/taro#3560]
**问题描述**
在h5和微信小程序工具内编译代码没有问题,在头条小程序中编译会出现问题

VM137:1 [TMA][ERROR][RUNTIME] parserScriptError
undefined
undefined +0ms

**复现步骤**
1.编译完成后,启动头条小程序工具就会出现
2.之前taro1.3.0的时候没有出现,更新taro到1.3.2以后报错
3.taro 退回到1.3.0版本号现在依然报错
4.以为是头条小程序工具问题,这个工具也重装了2遍,还是无效
5.yarn build:tt编译时没有出现错误,只有官方taro-ui分页的语法错误
    ESLint(taro/duplicate-name-of-state-and-props) 错误：this.state.current 与 this.props.current 重复可 
    能会导致渲染结不如意料之中的结果。

package.json中的内容
```js
{
	"name": "bookapp",
	"version": "1.0.0",
	"private": true,
	"description": "bookapp",
	"scripts": {
		"build:weapp": "taro build --type weapp",
		"build:swan": "taro build --type swan",
		"build:alipay": "taro build --type alipay",
		"build:tt": "taro build --type tt",
		"build:h5": "taro build --type h5",
		"build:rn": "taro build --type rn",
		"dev:weapp": "npm run build:weapp -- --watch",
		"dev:swan": "npm run build:swan -- --watch",
		"dev:alipay": "npm run build:alipay -- --watch",
		"dev:tt": "npm run build:tt -- --watch",
		"dev:h5": "npm run build:h5 -- --watch",
		"dev:rn": "npm run build:rn -- --watch"
	},
	"author": "",
	"license": "MIT",
	"dependencies": {
		"@tarojs/components": "1.3.4",
		"@tarojs/router": "1.3.4",
		"@tarojs/taro": "1.3.4",
		"@tarojs/taro-alipay": "1.3.4",
		"@tarojs/taro-h5": "1.3.4",
		"@tarojs/taro-swan": "1.3.4",
		"@tarojs/taro-tt": "1.3.4",
		"@tarojs/taro-weapp": "1.3.4",
		"moment": "^2.24.0",
		"nerv-devtools": "^1.4.3",
		"nervjs": "^1.4.3",
		"taro-ui": "^2.1.0"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "1.3.4",
		"@tarojs/plugin-csso": "1.3.4",
		"@tarojs/plugin-sass": "1.3.4",
		"@tarojs/plugin-uglifyjs": "1.3.4",
		"@tarojs/webpack-runner": "1.3.4",
		"@types/react": "^16.4.6",
		"@types/webpack-env": "^1.13.6",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"eslint": "^5.16.0",
		"eslint-config-taro": "1.3.4",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "1.3.4",
		"stylelint": "9.3.0",
		"stylelint-config-taro-rn": "1.3.0-beta.4",
		"stylelint-taro-rn": "1.3.0-beta.4"
	}
}

```

**期望行为**
不知道是什么原因造成的,希望官方给点建议

**报错信息**
taro doctor  命令检查错误
检查 Taro 配置
  [✗] h5.esnextModules 不合法的字段
说明:此处是按官方全局引入Taro Ui的报错(  esnextModules: ['taro-ui'] )
检查依赖
  [✓] 没有发现问题
检查推荐内容
  [!] 没有检查到常见的测试依赖(jest/mocha/ava/tape/jesmine/karma), 配置测试可以帮助提升项目质量
      
报错全部内容;
![微信截图_20190626174153](https://user-images.githubusercontent.com/20854119/60169699-c65c3400-9839-11e9-818a-c6432b26ca32.png)

**系统信息**

 Taro CLI 1.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

 Taro 版本 [1.3.4]
 Taro UI 版本 [2.1.0]
 报错平台 [tt]

**补充信息**
个人感觉是taro 对字节跳动小程序编译或者编译配置的问题,但是暂时不知道问题在哪里

**Comment by y449329998** [comment]
**最新发现**'
当引入taro-ui组件或者引入自己编写的组件,用taro编译yarn build;tt 就会出现这个问题

**Comment by Chen-jj** [comment]
@y449329998 复现不了，报错也不是 Taro 报的。建议 taro init 一个新项目再看看。

**Comment by y449329998** [comment]
@Chen-jj 
我这边可以提供一个小demo,您可以看一下,只要出现taro-ui的组件或者自己写的组件引入,就会报这种错误
**demo地址**
[https://github.com/y449329998/book](https://github.com/y449329998/book)
**删除taro-ui组件或者自己写的组件,就不会出现报错**
例如demo中的index中的这两个组件删除后就不会报错:
```js
 <AtIcon/>
 <BookGrid/>
```

**Comment by Chen-jj** [comment]
@y449329998 没有报错。。不过我在 mac 下测试的，没有 windows 环境。

报错是出自字节跳动的，我也想不到什么好办法。建议重新 init 个 Taro 项目试试。

![image](https://user-images.githubusercontent.com/11807297/60415308-5967e600-9c0d-11e9-8172-2c17b826beef.png)

**Comment by Chen-jj** [comment]
@y449329998 或者找到这个路径下的开发者工具相关文件删除后再重装下开发者工具

**Comment by Chen-jj** [comment]
@y449329998 头条方面的回答。

![image](https://user-images.githubusercontent.com/11807297/60415735-8ff23080-9c0e-11e9-87e0-bc4a31500305.png)

新建一个项目慢慢加逻辑定位错误吧。

**Comment by y449329998** [comment]
@Chen-jj  在您的建议之前,已经卸载头条开发这工具多次无效,看到您的建议后,我又来了一次彻底的删除头条小程序开发工具,找到

**Comment by y449329998** [comment]
@Chen-jj  在您的建议之前,已经卸载重装头条开发者工具多次无效,看到您的建议后,我又来了一次彻底的删除头条小程序开发工具,找到头条开发工具的临时文本地文件和件以及日志文件之后(这些文件卸载时候是没有被删除掉的),进行了重装,终于正常了,非常感谢
