### ISSUE TITLE
无法在在app.js引入原生组件

### ISSUE THREAD

**Issue by VicenLaw** [NervJS/taro#3561]
**问题描述**
无法在在app.js引入原生组件；组件文件并没有复制到dist，在页面配置usingComponents的时候，则可以。

**复现步骤**

```js

// 在页面配置的，可以生效

// ```js
    usingComponents: {
      "van-button": "../../components/vant/button/index",
      "van-nav-bar": "../../components/vant/nav-bar/index",
      "van-tabbar": "../../components/vant/tabbar/index",
      "van-tabbar-item": "../../components/vant/tabbar-item/index"
    }
// ```

// 在app.js 配置的，组件并没有并复制到dist

    usingComponents: {
      "van-button": "components/vant/button/index",
      "van-nav-bar": "components/vant/nav-bar/index",
      "van-tabbar": "components/vant/tabbar/index",
      "van-tabbar-item": "components/vant/tabbar-item/index"
    }

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

Component is not found in path "components/vant/button/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "components/vant/button/index" (using by "pages/index/index")

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

 - 操作系统: [e.g. Windows 10]
Windows 10
 - Taro 版本 [e.g. v.0.0.64]
1.3.0
 - Node.js 版本 [e.g. v9.0.0]
v10.16
 - 报错平台 [h5, weapp]
weapp

**补充信息**

**Comment by jonahfang** [comment]
为何要在 app.js 引入原生组件呢？

**Comment by mihuartuanr** [comment]
没有解决方案？

**Comment by VicenLaw** [comment]
@mihuartuanr 可以在需要使用的页面引入

**Comment by mihuartuanr** [comment]
@VicenLaw 每个页面都需要呢…有些组件很频繁

**Comment by Chen-jj** [comment]
Taro 3 已支持
