### ISSUE TITLE
v1.3.4 Taro.memo的实现有问题,state改变不触发render

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#3562]
**问题描述**

Taro.memo的实现有问题。如果使用了memo，props没有发生改变，即便state改变也不能触发render。

这貌似和react实现的不一样啊。

这个问题从下午把我坑到凌晨，现在是半夜3点，我写了个自定义hooks，因为组件都用了Taro.memo所以一直都没摸到头绪，一开始还以为是自定义hooks有问题。

哇，难受。

要哭撩。嘤嘤嘤

See：
https://github.com/facebook/react/issues/15661

```js
memo((props)=>{
  const [foo,setFoo] = useState(0)
  useEffect(()=>{
    setTimeout(() => {
      setFoo(1) // 不触发render，被阻止了。
    }, 3000)
   })
})
```

**期望**

Taro.memo不应该拦截组件自身的更新。

**系统信息**
> Taro v1.3.4

**Comment by loveonelong** [comment]
比较暴力的方法就是在memo.js添加对于nextState的判断。

不过这种实现，还是有问题呀。

```js
import { isFunction, objectIs } from './util'

export function memo (component, propsAreEqual) {
  component.prototype.shouldComponentUpdate = function (nextProps, nextState) {
    return (
      (isFunction(propsAreEqual) ? !propsAreEqual(this.props, nextProps) : !objectIs(this.props, nextProps)) &&
      !objectIs(this.state, nextState)
    )
  }

  return component
}

```

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/19eef476e06b42f4aa6617ea64fee95ce70da8fe
