### ISSUE TITLE
return无法跳出函数

### ISSUE THREAD

**Issue by Xuralyon** [NervJS/taro#3566]
> render() {
>     const a = 1
>     if (a === 1) {
>       return \<View>111\</View>
>     }
>     return \<View>222\</View>
>   }

期望输出：

> \<View>111\</View>

实际输出：

> \<View>111\</View>
> \<View>222\</View>

**Comment by yuche** [comment]
Duplicate of #https://github.com/NervJS/taro/issues/2367
