### ISSUE TITLE
小程序和h5能使用同一个canvas?或者为什么小程序canvas转h5会报错？

### ISSUE THREAD

**Issue by caiyongqiang** [NervJS/taro#3567]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
我现在用小程序的canvas写画布生成海报，但是为什么转成h5后视乎不支持绘制图片功能？
报错内容：
"Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'"
其他似乎都能正常，就是这个不行

**复现步骤**
[复现问题的步骤]
"Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'"
![image](https://user-images.githubusercontent.com/31945098/60233697-fa843300-98d3-11e9-8e4a-4e4ae3cf549a.png)

```js

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
希望优秀的你们有没有解决办法，还是变成h5只能使用h5标签的canvas绘制生成海报？请求，谢谢。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro v1.2.26  ===> h5版报错
![image](https://user-images.githubusercontent.com/31945098/60233807-8007e300-98d4-11e9-9703-7b982d52e66e.png)

**补充信息**

**Comment by archerQ** [comment]
请问这个报错是哪里的问题呢，我这边也遇到了

**Comment by darkfiredarkhalo** [comment]
我也遇见了,taro的canvas在小程序中完全不起作用,在h5中drawImage根本不执行,小程序原生没问题

**Comment by archywillhe** [comment]
根本就用了。。。折腾了半天

**Comment by withwz** [comment]
> 根本就用不了。。。折腾了半天。。 有些想放弃用taro了啦。。

我也受不了了，做了些什么东西

**Comment by Link-X** [comment]
同问。没人管么！
