### ISSUE TITLE
Video 配合 Swiper 在IOS端无法正常切换轮播图

### ISSUE THREAD

**Issue by hnliyuan** [NervJS/taro#3568]
**问题描述**
把Video放在SwiperItem里面，在模拟器安卓均正确切换轮播图，
但在IOS端无法正常切换

**期望行为**
IOS端真机如安卓模拟器一样，可以随意滑动切换轮播图

**系统信息**
npmPackages:
      @tarojs/async-await: ^1.3.0 => 1.3.0 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-less: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: ^1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.3.13 
      react: ^16.8.6 => 16.8.6

**Comment by jinjinjin0731** [comment]
小程序？

**Comment by hnliyuan** [comment]
> 小程序？

该问题只在特定IOS端微信版本重现，我升级到最新版本问题迎刃而解
