### ISSUE TITLE
请求增强 H5 侧 Webpack 的可配置性

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro#357]
目前 Webpack 的主要配置都藏在 `node_modules/@tarojs/webpack-runner/dist/` 下的 `config/` 与 `utils/index.js - patchCustomConfig`，可配置度相对较低且较为零散。例如，目前无法给编译出来的 CSS 加哈希，我只能这样子操作：

![image](https://user-images.githubusercontent.com/13287948/42993267-85ce368a-8c3d-11e8-89f9-eb5050b0b592.png)

实在有太多不能配置的项，举个例子：

![image](https://user-images.githubusercontent.com/13287948/42993209-622a817a-8c3d-11e8-8b9d-681fc32795a5.png)

**Comment by Littly** [comment]
感谢反馈~ 确实是考虑到高度自定义的需求才加入了函数式的webpack配置 看来还是有盲区  拿小本本记下了..

**Comment by kenberkeley** [comment]
盲区太多，而且把 Webpack 配置藏起来没有意义，不妨参考 vue-cli 那样可以任由用户配置
