### ISSUE TITLE
window环境中RN编译后run-android报404错误，找不到index.js

### ISSUE THREAD

**Issue by goforor** [NervJS/taro#3570]
![图片](https://user-images.githubusercontent.com/40154651/60241120-20660380-98e5-11e9-8d55-28996a7e5e4c.png)

![图片](https://user-images.githubusercontent.com/40154651/60241137-265be480-98e5-11e9-94d7-e4138441dbd0.png)

**Comment by liukaixin01** [comment]
https://github.com/NervJS/taro/issues/3546
