### ISSUE TITLE
设置外部样式不生效

### ISSUE THREAD

**Issue by lyevdsky** [NervJS/taro#3573]
**问题描述**
之前也有人提过这个问题，但是我升到1.3.4还是没有解决。

**复现步骤**

```js
<Cols myclass="red-text"></Cols>

生成代码：
<cols compid="{{$compid__0}}"></cols>

另如果写成my-class，控制台会输出错误
<Cols my-class="red-text"></Cols>
```

**报错信息**
![image](https://user-images.githubusercontent.com/12131431/60248264-d8e77380-98f4-11e9-8998-0d6145178352.png)

**系统信息**
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.7.0 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@lyevdsky props 没写成驼峰，会导致子组件接收不了这个 props。但不会报错，你截图的报错看路径是 swan 的，重启开发者工具吧。

**Comment by lyevdsky** [comment]
@Chen-jj 写成驼峰才不会报错。但问题还是一样`<cols compid="{{$compid__5}}"></cols>`

**Comment by Chen-jj** [comment]
@lyevdsky 都没有报错

**Comment by Chen-jj** [comment]
#3080

**Comment by Chen-jj** [comment]
@lyevdsky 

page.js:

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import A from '../../components/a/a'

import './detail.scss'

export default class Detail extends Component {
  render() {
    return <View>
      <A  external-class='red-text' />
    </View>
  }
}
```

page.scss: 

```sass
.red-text {
  color: red
}
```

a.js

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class A extends Component {
  static externalClasses = ['external-class']
  render() {
    return (
      <View className='external-class'>
        A
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/60320363-080cec00-99ac-11e9-9edb-aa536ef335ac.png)

**Comment by lyevdsky** [comment]
@Chen-jj 
微信开发者工具：
![image](https://user-images.githubusercontent.com/12131431/60321545-b1a1ac80-99af-11e9-8caa-89178133b0f4.png)
百度的：
![image](https://user-images.githubusercontent.com/12131431/60322367-dc8d0000-99b1-11e9-9111-faf25fd72d1c.png)

**Comment by Chen-jj** [comment]
@lyevdsky 我上面的截图就是百度的。没有报错。

![image](https://user-images.githubusercontent.com/11807297/60328147-41e7ed80-99c0-11e9-9e71-b39da2f7e583.png)

**Comment by lyevdsky** [comment]
@Chen-jj  类名一定要带 -  才有用

**Comment by Garfield550** [comment]
> @Chen-jj 之前应该是因为我taro实际版本没有升级到1.3.4的原因，重新安装下就好了。现在问题是外部类名一定要带 - 才有用

> 注意：externalClasses 需要使用 短横线命名法 (kebab-case)，而不是 React 惯用的 驼峰命名法 (camelCase)。否则无效。

Ref: https://nervjs.github.io/taro/docs/component-style.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB

**Comment by lyevdsky** [comment]
@Garfield550 @Chen-jj 和命名没有关系好吗，我说的是原来外部类命名成externalclass也是有效的，现在外部类必须加上-符号才行。
下图是fix#3080的commit
![image](https://user-images.githubusercontent.com/12131431/60416178-b8c6f580-9c0f-11e9-8dac-ddfaa4f085f5.png)

**Comment by Chen-jj** [comment]
@lyevdsky 加 - 吧，不然编译时区分不了，肯定需要加规则的。
