### ISSUE TITLE
升级taro cli到1.3.4之后出现依赖问题

### ISSUE THREAD

**Issue by zzyhdu** [NervJS/taro#3574]
**问题描述**
升级taro cli到1.3.4之后出现依赖问题，file的形式引用libs，在最后生成的dist文件中找不到evnet.js这个文件

**复现步骤**
通过npm引用公共的libs包，libs包使用了event.js中的EventEmitter

```js
import EventEmitter from 'events';
// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

```

**期望行为**
形成正确的依赖

**报错信息**
![image](https://user-images.githubusercontent.com/4222224/60253923-88c1de80-98ff-11e9-9172-2f0a6fcba0db.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

![image](https://user-images.githubusercontent.com/4222224/60253983-a5f6ad00-98ff-11e9-95c1-881dbd4956cf.png)

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zzyhdu** [comment]
Ps：目录结构
![image](https://user-images.githubusercontent.com/4222224/60254034-be66c780-98ff-11e9-9a12-26ea32a05b04.png)

项目依赖：
![image](https://user-images.githubusercontent.com/4222224/60254101-db9b9600-98ff-11e9-9395-bfe3e5853ae2.png)

libs依赖：
![image](https://user-images.githubusercontent.com/4222224/60254129-ebb37580-98ff-11e9-85fa-5dd9903362e6.png)

编译后代码：
![image](https://user-images.githubusercontent.com/4222224/60254199-0dacf800-9900-11e9-94d5-5f9cc056a69a.png)
报错行：
![image](https://user-images.githubusercontent.com/4222224/60254250-24ebe580-9900-11e9-8509-b76ae74905ba.png)

**Comment by cncolder** [comment]
不清楚具体原因, 但 Taro 自带事件系统, 可以考虑用这个.

https://nervjs.github.io/taro/docs/apis/about/events.html

**Comment by zzyhdu** [comment]
因为这个libs是web和rn一起在用，所以不想把taro的代码侵入进去～有没有好的建议

**Comment by cncolder** [comment]
@zzyhdu 之前 taro 和 lerna 一直有些兼容问题, 不知道现在修复了没有.

可以试试 lerna link https://github.com/lerna/lerna/tree/master/commands/link
把 libs 变成一个真正的本地 npm private module. 在 miniapp 里引用本地版本号.

**Comment by zzyhdu** [comment]
ok，我再去研究研究，比较奇怪的就是，为什么在老版本里面依赖是正常copy的，比如在1.3.1或者1.2.26都是正常的，在1.3.4下却不可以。今天我的同事开始配置环境的时候在1.3.4，1.3.1，1.2.26都有依赖问题，libs下的event.js都没有copy过去。

**Comment by wqj97** [comment]
同样遇到这个问题, 老版本没问题, 新版本有问题

**Comment by wqj97** [comment]
> ok，我再去研究研究，比较奇怪的就是，为什么在老版本里面依赖是正常copy的，比如在1.3.1或者1.2.26都是正常的，在1.3.4下却不可以。今天我的同事开始配置环境的时候在1.3.4，1.3.1，1.2.26都有依赖问题，libs下的event.js都没有copy过去。

同学你解决了没~

**Comment by wqj97** [comment]
@cncolder 抱歉没得到回复~ @你一下~

**Comment by zzyhdu** [comment]
@wqj97 头疼，还是没解决，一直在忙别的事情，我只能停在1.3.1，还只能在我的电脑上行，我回家在1.3.1下也不行，今天晚上找了会，没找到办法。。

**Comment by wqj97** [comment]
@zzyhdu 哎头疼, 也没见着有人解决...

**Comment by wqj97** [comment]
@zzyhdu 
我用他们的eventCenter替换了, 改动不大

**Comment by yuche** [comment]
不要使用 node 内部的库，Taro 不会像 webpack 一样把它们打包进来。

**Comment by zzyhdu** [comment]
最后把event拷出来，改了个名字publish在自己的npm上了，close了
