### ISSUE TITLE
子组件传对象进去，对象中有值为函数，子组件内部无法获取

### ISSUE THREAD

**Issue by ayahua** [NervJS/taro#3576]
**问题描述**
[问题描述：父组件给子组件传对象进去，对象中有值为函数，子组件内部无法获取]

**复现步骤**
想写一个table组件，然后发现
![image](https://user-images.githubusercontent.com/36917157/60256568-61214500-9904-11e9-9824-55c52af266cc.png)
![image](https://user-images.githubusercontent.com/36917157/60256654-8a41d580-9904-11e9-958d-a08060016b2f.png)
代码输出里面，上面是父组件输出的，columns对象里面有onRender方法，下面在子组件里输出的时候就没有了

**期望行为**
父组件传对象给子组件时，内部的函数能获取

**系统信息**

 - 操作系统:mac os 10.14
 - Taro 版本 1.2.17
 - Node.js 版本 8.15.1

**Comment by Chen-jj** [comment]
@ayahua v1.3.0+ 才支持，升级到最新版本吧
