### ISSUE TITLE
defineConstants

### ISSUE THREAD

**Issue by Varavarforvar** [NervJS/taro#358]
defineConstants的变量 要怎么访问到?

**Comment by zacksleo** [comment]
参考文档： https://nervjs.github.io/taro/config-detail.html#defineConstants
例如：
```
  defineConstants: {
    API_GATEWAY:  '"http://localhost/api/v1"'
  },
```

文件中直接使用 `API_GATEWAY`

```
params.url = API_GATEWAY + params.url;
```

**Comment by zacksleo** [comment]
@anshixiaobai 你是用了两层引号包裹么

**Comment by anshixiaobai** [comment]
你好  我在 config/index.js 文件中  在config对象中 添加了  
defineConstants: {
    API_GATEWAY: '"http://localhost/api/v1"'
  },

在app.tsx 中  直接   console.log(API_GATEWAY);     visual studio  直接提示报错，在微信模拟器上面也运行不起来    Taro 版本是最新的

**Comment by zacksleo** [comment]
重新运行npm run  build:weapp 了吗

**Comment by anshixiaobai** [comment]
重启 可以使用了  多谢
