### ISSUE TITLE
h5打包后在真机上运行，Taro.uploadFile这个方法根本不触发

### ISSUE THREAD

**Issue by xiafengaha** [NervJS/taro#3580]
**问题描述**
[问题描述：目前，在chrome内用浏览器调试h5的uploadFile这个方法，上传请求API什么的都OK。然后打包后，在真机上使用上传功能失效]

**复现步骤**
[复现问题的步骤]
1. 先在代码中写入Taro.uploadFile方法
2. 在chrome中调试app上传功能（运行正常）
3. 打包后，用hbuilder在进行真机调试
4. 在真机上进行上传功能测试（机型是：努比亚z17mini,目前只测了这个机型）上传功能失效，本地用了charles进行代理，发现没有请求上传的API。

看下面的截图

**期望行为**
[上传功能在真机上也能运行]

**代码截图**

![image](https://user-images.githubusercontent.com/26809910/60312259-3deea800-998d-11e9-9eae-8860d4e1aee4.png)
![image](https://user-images.githubusercontent.com/26809910/60312291-6a0a2900-998d-11e9-8cdc-3382d4774d1c.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Android]
 - Taro 版本 [1.3.4]
 - Node.js 版本 [10.15.3]
 - 报错平台 [h5]

** taro依赖信息**
 Taro v1.3.4
  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/cli: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: 1.3.4 => 1.3.4 
      @tarojs/redux-h5: 1.3.4 => 1.3.4 
      @tarojs/rn-runner: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by xiafengaha** [comment]
刚确认了一下iphone6s机型，然后代码里面我也确认了，在真机上点击图片上传，选完图片后，直接跳过了Taro.uploadFile()这个方法

**Comment by Slngle** [comment]
你域名有配置么？upload的安全域名

**Comment by xiafengaha** [comment]
> 你域名有配置么？upload的安全域名

能说具体点吗？我h5在chrome调试的域名和打包后的域名都是一样的。如果安全域名这个没配置的话uploadFile这个方法应该在chrome本地调试就会出错，现在的问题是，在本地chrome调试是OK的，相同的域名，在真机上。uploadFile这个方法不执行

**Comment by xiafengaha** [comment]
没有大佬能回答一下吗？

**Comment by xoptimal** [comment]
@Slngle  @Littly   H5 也要配置安全域名的吗 , 怎么配置~

**Comment by xiafengaha** [comment]
我目前用原生的input自己实现了上传功能，毕竟taro有他们的优先级。https://github.com/xiafengaha/vux/tree/master/src/components/upload需要的朋友可以参考一下。方法改成react的就可以了。

**Comment by superfluidLW** [comment]
Taro已经升级到1.3.18版本，遇到同样的问题。在微信小程序“打开调试”可以成功上传选中的图片，“关闭调试”之后再调用uploadfile就不发出请求了。
