### ISSUE TITLE
微信小程序自定义组件通过props.renderComponent传入JSX层级异常问题

### ISSUE THREAD

**Issue by icomicsme** [NervJS/taro#3582]
**问题描述**
开发用于微信小程序的自定义组件A，通过赋值props.renderContent传入JSX作为组件A的子元素，但编译后renderContent的层级关系并非预期，想问下是否有解决方案，感谢。

**复现步骤**
1. 新建组件A
2. 使用组件A，通过JSX赋值props.renderContent
3. 组件A内，renderContent的位置非预期

```js
// 组件A
class List extends Component {
  render() {
    return (
      <View
        className={ `list-container ${ this.props.className || '' }` }
        style={ this.props.style || '' }
      >
        <View
          className={ `list-label ${ this.props.labelClassName || '' }` }
          style={ this.props.labelStyle || '' }
        >
          { this.props.label }
        </View>
        <View
          className={ `list-content ${ this.props.contentClassName || '' }` }
          style={ this.props.contentStyle || '' }
        >
          { this.props.renderContent }
        </View>
      </View>
    )
  } 
}

export default List

// 使用
<List label='手机号' renderContent={ <input /> }  />

```

**期望行为**

期望props.renderContent出现在指定位置

**报错信息**

![image](https://user-images.githubusercontent.com/43262551/60319724-f9253a00-99a9-11e9-85e6-b5ffc331def1.png)

**系统信息**

Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0 => 1.3.0 
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/redux: 1.3.0 => 1.3.0 
      @tarojs/redux-h5: 1.3.0 => 1.3.0 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nervjs: ^1.4.0 => 1.4.0 

**补充信息**
并不是太熟悉机制，暂未找到解决方案。

**Comment by yuche** [comment]
层级不对是微信开发者工具的bug，显示的位置是对的。

**Comment by icomicsme** [comment]
展示也不对诶，的确是跑下来的，同样的结构不用自定义组件就没问题。

**Comment by Chen-jj** [comment]
@icomicsme props 传递 jsx 是通过微信小程序的 [slot](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6wxml%E7%9A%84slot) 实现的。

使用多 slot 后开发者工具上查看结构的确如图所示，在组件 shadow dom 外。写原生小程序也一样的。

我也试了一下，虽然结构显示如此，但写样式应该不影响：

```xml
<block>
    <view>
        <view>{{label}}</view>
        <view style="background: red;height: 100px;">
            <slot name="content"></slot>
        </view>
    </view>
</block>
```

![image](https://user-images.githubusercontent.com/11807297/60795477-54bba880-a19e-11e9-9bab-997160125a0e.png)

如果对你写样式有影响，只能换种写法了。
