### ISSUE TITLE
支付宝小程序错误提示

### ISSUE THREAD

**Issue by 1067011734** [NervJS/taro#3587]
我用taro开发，没有加载过这个js文件，怎么提示了？
![Snip20190628_2](https://user-images.githubusercontent.com/19586117/60328028-ee759f80-99bf-11e9-9018-ed4de72db64b.png)

**Comment by Chen-jj** [comment]
@1067011734 看看是你项目的 js 还是支付宝开发者工具的吧。Taro 没有这样的文件。
