### ISSUE TITLE
1.3.4 mobx处理数组报错

### ISSUE THREAD

**Issue by yuquanwang** [NervJS/taro#3590]
**问题描述**
升级到1.3.4（估计1.3.0以上都有这问题），之前使用mobx写的observe数组的地方均报错，数组更新，但是无法取得数组内的item。报错undefined；

**复现步骤**
[复现问题的步骤]
1. 使用1.2.26版本，集成mobx，采用mobx5.9.4以上，
2. 编写class observable其某个数组的属性
3. 使用该属性的map方法进行页面渲染，并验证使用正常
4. 升级taro所有库的版本到1.3.4
5. 报错

```js

export default class SomeClass {
...
@observable someArr: [] = []
...
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/16618169/60349009-4b3e7d80-99f3-11e9-87bb-4734606011e1.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.2.26 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.2.17 => 1.3.4 
      @tarojs/cli: ^1.2.26 => 1.3.4 
      @tarojs/components: ^1.2.17 => 1.3.4 
      @tarojs/mobx: ^1.2.26 => 1.3.4 
      @tarojs/mobx-h5: ^1.2.26 => 1.3.4 
      @tarojs/mobx-prop-types: ^1.2.26 => 1.2.26 
      @tarojs/mobx-rn: ^1.2.26 => 1.3.4 
      @tarojs/plugin-babel: ^1.2.17 => 1.3.4 
      @tarojs/plugin-csso: ^1.2.17 => 1.3.4 
      @tarojs/plugin-sass: ^1.2.17 => 1.3.4 
      @tarojs/plugin-uglifyjs: ^1.2.17 => 1.3.4 
      @tarojs/router: ^1.2.17 => 1.3.4 
      @tarojs/taro: ^1.2.17 => 1.3.4 
      @tarojs/taro-alipay: ^1.2.17 => 1.3.4 
      @tarojs/taro-h5: ^1.2.17 => 1.3.4 
      @tarojs/taro-swan: ^1.2.17 => 1.3.4 
      @tarojs/taro-tt: ^1.2.17 => 1.3.4 
      @tarojs/taro-weapp: ^1.2.17 => 1.3.4 
      @tarojs/webpack-runner: ^1.2.17 => 1.3.4 
      eslint-config-taro: ^1.2.17 => 1.3.4 
      eslint-plugin-taro: ^1.2.17 => 1.3.4 
      nervjs: ^1.3.9 => 1.4.3

**Comment by nanjingboy** [comment]
@yuquanwang CLI 升级看看呢

**Comment by Garfield550** [comment]
```shell
npmPackages:
@tarojs/async-await: ^1.2.17 => 1.3.4 
@tarojs/cli: ^1.2.26 => 1.3.4 
@tarojs/components: ^1.2.17 => 1.3.4 
@tarojs/mobx: ^1.2.26 => 1.3.4 
@tarojs/mobx-h5: ^1.2.26 => 1.3.4 
@tarojs/mobx-prop-types: ^1.2.26 => 1.2.26 // 你这个是 1.2.26 没有升级 1.3.4
@tarojs/mobx-rn: ^1.2.26 => 1.3.4 
@tarojs/plugin-babel: ^1.2.17 => 1.3.4 
@tarojs/plugin-csso: ^1.2.17 => 1.3.4 
@tarojs/plugin-sass: ^1.2.17 => 1.3.4 
@tarojs/plugin-uglifyjs: ^1.2.17 => 1.3.4 
@tarojs/router: ^1.2.17 => 1.3.4 
@tarojs/taro: ^1.2.17 => 1.3.4 
@tarojs/taro-alipay: ^1.2.17 => 1.3.4 
@tarojs/taro-h5: ^1.2.17 => 1.3.4 
@tarojs/taro-swan: ^1.2.17 => 1.3.4 
@tarojs/taro-tt: ^1.2.17 => 1.3.4 
@tarojs/taro-weapp: ^1.2.17 => 1.3.4 
@tarojs/webpack-runner: ^1.2.17 => 1.3.4 
eslint-config-taro: ^1.2.17 => 1.3.4 
eslint-plugin-taro: ^1.2.17 => 1.3.4 
nervjs: ^1.3.9 => 1.4.3 
```

**Comment by zhangchenna** [comment]
根本不支持 5以上的mobx 只能用4.8

**Comment by nanjingboy** [comment]
@zhangchenna 默认使用 4.8 是因为小程序可能运行在低端的机器上，如果你不需要兼容低端机器的话，可以使用 5+ 啊，没有强制你绑死在 4.8

**Comment by zhangchenna** [comment]
> @zhangchenna 默认使用 4.8 是因为小程序可能运行在低端的机器上，如果你不需要兼容低端机器的话，可以使用 5+ 啊，没有强制你绑死在 4.8

我试了5+ 的类数组类对象 都不能生成正常数组 方法无效  4.8 正常  例如 Array.from()

**Comment by nanjingboy** [comment]
@zhangchenna 如果说 4.8 正常的话，那么 5+ 应该不会有问题，建议再仔细看下 [mobx 文档](https://cn.mobx.js.org/) 或给个完整的 demo 看看。不然无法定位

**Comment by yuquanwang** [comment]
OK，前段时间忙，晚上我看下

Mutrix

**Comment by yuquanwang** [comment]
taro init了一个新项目进行复现，发现是在jsx中传入的mobx数组全部变成了[]。
```javascript
  render() {
    const { usualDrugs } = this.props.user!;
    const drugs = usualDrugs.map((item) => {
      return new Drug({
        genericName: item.genericName,
        brandName: item.brandName,
        factory: item.factory,
        productList: [item]
      })
    })

    console.log('drugs: ', drugs);

    return (
      <View className='index'>
        <Button onClick={this.incrementAsync}>Add Async</Button>
        {drugs.length &&
          <View className='panel'>
            <View className='panel__title'>常用药品</View>
            +  <DrugList list={drugs} />
          </View>}
      </View>
    )
  }
```

**Comment by cloudZQY** [comment]
> taro init了一个新项目进行复现，发现是在jsx中传入的mobx数组全部变成了[]。
> 
> ```js
>   render() {
>     const { usualDrugs } = this.props.user!;
>     + const drugs = usualDrugs.map((item) => {
>     +  return new Drug({
>     +    genericName: item.genericName,
>     +    brandName: item.brandName,
>     +    factory: item.factory,
>     +    productList: [item]
>     +  })
>     +})
> 
>     + console.log('drugs: ', drugs);
> 
>     return (
>       <View className='index'>
>         <Button onClick={this.incrementAsync}>Add Async</Button>
>         + {drugs.length &&
>         +  <View className='panel'>
>         +    <View className='panel__title'>常用药品</View>
>         +     <DrugList list={drugs} />  // 该自定义组件中打印的props.list为[]
>         +  </View>}
>       </View>
>     )
>   }
> ```

通碰到，猜测是taro解析ast时，解析到array.map会进行处理。但是这个usualDrugs是一个ObservableArray，并不是单纯的数组。

**Comment by Garfield550** [comment]
> Due to limitations of native arrays in ES5 observable.array will create a faux-array (array-like object) instead of a real array. In practice, these arrays work just as fine as native arrays and all native methods are supported, including index assignments, up-to and including the length of the array.
> 
> Bear in mind however that Array.isArray(observable([])) will yield false, which some native array manipulation methods require and which some external libraries may also require. E.g. [].concat(observable([])) will not work as expected since the native array concat method expects the test to return true. So whenever you need to pass an observable array to an external library or use the observable array as an argument to native array manipulation methods, you should create a shallow copy by using array.slice(), which will cause Array.isArray(observable([]).slice()) to yield true.

Ref: https://mobx.js.org/refguide/array.html
