### ISSUE TITLE
Taro升级到1.3.2后报错，部分页面报错

### ISSUE THREAD

**Issue by BambooSword** [NervJS/taro#3594]
**问题描述**
Taro升级到1.3.2后报错，部分页面当数据量很大时，用porps传递数据会出现（VM28728:1 vdSyncBatch 数据传输长度为 1481791 已经超过最大长度 1048576）数据长度过大的问题。
如果是setState数据过大我可以自行处理，但是目前这种问题，自己好像不太好解决

**复现步骤**
1.跳转到指定页面，fetch数据
2.使用props传递数据
3. 控制台出现如：VM28728:1 vdSyncBatch 数据传输长度为 1481791 已经超过最大长度 1048576，之类的报错。
4.页面停止渲染

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```js

         {partType === 'tough' && (
            <View className='at-indexes__list-c'>
              <View className='at-indexes__list-title'>
                <View className='at-indexes__list-title-area'>
                  {dataList.spaceName}：
                  {dataList.spaceSize ? `${dataList.spaceSize}㎡/` : ''}
                  {dataList.count}项目
                </View>
                <View>
                  合价：
                  <Text className='at-indexes__list-title-amount'>
                    {dataList.paymentStr}
                  </Text>
                </View>
              </View>
              {dataList.list &&
                dataList.list.map((itemL, ind) => {
                  console.log(itemL, 'this is items')
                  return (
                    <OrderItem
                      index={ind}
                      type='hard'
                      orderItemData={itemL}
                      onCustomClick={this.props.onCustomClick}
                      key={itemL.skuId}
                    />
                  );
                })}
            </View>
          )}

```

**期望行为**
希望能不报错，能正常传输数据
**报错信息**

![image](https://user-images.githubusercontent.com/18547539/60380648-86848f00-9a7b-11e9-8302-b80a3a7fc52a.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [Taro v1.3.4]
 - Node.js 版本 [10.15.3]
 - 报错平台 [weapp]

**Comment by nevernet** [comment]
肯定是某个地方的setState的数据过大， 建议拆分代码，一步一步试试看

**Comment by Garfield550** [comment]
fetch 数据建议一次少一些，或者加入分页功能。

**Comment by Chen-jj** [comment]
@BambooSword 组件每次渲染，props 会被 assign 到将要被 setData 的数据当中。因此 props 大，setData 的数据肯定大了。建议先处理好数据再传给子组件。

https://github.com/NervJS/taro/blob/260360fff9ee5ff03c6eaad6d9daeddc3e21f561/packages/taro-weapp/src/lifecycle.js#L154
