### ISSUE TITLE
h5 下从 Page B 通过 Taro.navigateTo 回到 Page A 出现重叠问题

### ISSUE THREAD

**Issue by Psli** [NervJS/taro#3597]
**问题描述**
h5 下从 Page A 通过 Taro.navigateTo 到 Page B，
再从 Page B 通过 Taro.navigateTo 到 Page A，
Page A 会出现重叠

**复现步骤**

config 配置
```js
h5: {
    router: {
      customRoutes: {
        '/pages/index/index': '/',
        '/pages/index/index2': '/pageb'
      }
    },
```

Page A 代码
```js
  gotoPageB() {
    Taro.navigateTo({ url: '/pages/index/index2' });
  }

  render () {
    return (
      <View className='index'>
        <View><Text>Hello, Page A</Text></View>
        <Button onClick={this.gotoPageB}>Go To Page B</Button>
      </View>
    )
  }
```

Page B 代码
```js
  gotoPageA() {
    Taro.navigateTo({ url: '/pages/index/index' });
  }

  render () {
    return (
      <View className='index'>
        <View><Text>Hello, Page A</Text></View>
        <Button onClick={this.gotoPageA}>Go To Page A</Button>
      </View>
    )
  }
```

**期望行为**
希望能消除重叠

**报错信息**

![屏幕快照-2019-06-30-15.04.38.jpg](https://i.loli.net/2019/06/30/5d1862447aa1380769.jpg)

**系统信息**
 - Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4
      @tarojs/components: 1.3.4 => 1.3.4
      @tarojs/plugin-babel: 1.3.4 => 1.3.4
      @tarojs/plugin-csso: 1.3.4 => 1.3.4
      @tarojs/plugin-sass: 1.3.4 => 1.3.4
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4
      @tarojs/redux: 1.3.4 => 1.3.4
      @tarojs/redux-h5: 1.3.4 => 1.3.4
      @tarojs/router: 1.3.4 => 1.3.4
      @tarojs/taro: 1.3.4 => 1.3.4
      @tarojs/taro-alipay: 1.3.4 => 1.3.4
      @tarojs/taro-h5: 1.3.4 => 1.3.4
      @tarojs/taro-swan: 1.3.4 => 1.3.4
      @tarojs/taro-tt: 1.3.4 => 1.3.4
      @tarojs/taro-weapp: 1.3.4 => 1.3.4
      @tarojs/webpack-runner: ^1.3.4 => 1.3.4
      eslint-config-taro: 1.3.4 => 1.3.4
      eslint-plugin-taro: 1.3.4 => 1.3.4
      nerv-devtools: ^1.4.0 => 1.4.3
      nervjs: ^1.4.0 => 1.4.3

**Comment by Littly** [comment]
感谢反馈

**Comment by targeral** [comment]
请问最后是怎么解决的？
