### ISSUE TITLE
[eslint] 希望添加hooks相关的lint规则

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#3598]
如：
https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks

**Comment by yuche** [comment]
你可以提个 PR 在模板加上

**Comment by loveonelong** [comment]
@yuche 麻烦尽快看一下这个需求？大型项目中如果没有lint，hooks中很容易忽略掉一些deps，从而导致一些问题

**Comment by loveonelong** [comment]
抱歉，好像已经有eslint-plugin-react-hooks了。

**Comment by loveonelong** [comment]
npmPackages:
      @tarojs/async-await: 1.3.10 => 1.3.10 
      @tarojs/components: 1.3.10 => 1.3.10 
      @tarojs/components-qa: 1.3.10 => 1.3.10 
      @tarojs/mobx: 1.3.10 => 1.3.10 
      @tarojs/mobx-h5: 1.3.10 => 1.3.10 
      @tarojs/mobx-rn: 1.3.10 => 1.3.10 
      @tarojs/plugin-babel: 1.3.10 => 1.3.10 
      @tarojs/plugin-csso: 1.3.10 => 1.3.10 
      @tarojs/plugin-less: 1.3.10 => 1.3.10 
      @tarojs/plugin-sass: 1.3.10 => 1.3.10 
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10 
      @tarojs/redux: 1.3.10 => 1.3.10 
      @tarojs/redux-h5: 1.3.10 => 1.3.10 
      @tarojs/rn-runner: 1.3.10 => 1.3.10 
      @tarojs/router: 1.3.10 => 1.3.10 
      @tarojs/taro: 1.3.10 => 1.3.10 
      @tarojs/taro-alipay: 1.3.10 => 1.3.10 
      @tarojs/taro-h5: 1.3.10 => 1.3.10 
      @tarojs/taro-qq: 1.3.10 => 1.3.10 
      @tarojs/taro-quickapp: 1.3.10 => 1.3.10 
      @tarojs/taro-swan: 1.3.10 => 1.3.10 
      @tarojs/taro-tt: 1.3.10 => 1.3.10 
      @tarojs/taro-weapp: 1.3.10 => 1.3.10 
      @tarojs/webpack-runner: 1.3.10 => 1.3.10 
      eslint-config-taro: 1.3.10 => 1.3.10 
      eslint-plugin-taro: 1.3.10 => 1.3.10 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
      stylelint-config-taro-rn: 1.3.10 => 1.3.10 
      stylelint-taro-rn: 1.3.10 => 1.3.10

**Comment by loveonelong** [comment]
eslint-plugin-react-hooks 会提醒需要在本地安装。
```
eslint "src/**/*.{js,jsx,ts,tsx}"


Oops! Something went wrong! :(

ESLint: 5.16.0.
ESLint couldn't find the plugin "eslint-plugin-react-hooks". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-react-hooks is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-react-hooks@latest --save-dev

Path to ESLint package: /Users/onelong/work/ilisten-taro-pack/node_modules/_eslint@5.16.0@eslint

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team
```

**Comment by loveonelong** [comment]
还有一个问题是，按完玩，调用eslint 直接检测是ok的，但vscode中无法显示有问题的地方。

**Comment by yuche** [comment]
> 还有一个问题是，按完玩，调用eslint 直接检测是ok的，但vscode中无法显示有问题的地方。

那就是你的配置问题了

**Comment by xPixv** [comment]
```text
[Info  - 12:25:00 AM] ESLint server stopped.
[Info  - 12:25:01 AM] ESLint server running in node v10.11.0
[Info  - 12:25:01 AM] ESLint server is running.
[Info  - 12:25:04 AM] ESLint library loaded from: c:\Users\Cloud\Desktop\SteamCN-Mini-Program\node_modules\eslint\lib\api.js
[Error - 12:25:06 AM] Failed to load plugin react-hooks: Cannot find module 'eslint-plugin-react-hooks' Referenced from: c:\Users\Cloud\Desktop\SteamCN-Mini-Program\node_modules\eslint-config-taro\index.js Referenced from: C:\Users\Cloud\Desktop\SteamCN-Mini-Program\.eslintrc
```

VSCode 里没法用了，找不到 `react-hooks` 插件。

并且在 node_modules 和 lockfile 里也没找到 `eslint-plugin-react-hooks` 包

只有自己手动安装包之后才能用 _(:з)∠)_

**Comment by nyrf** [comment]
升级最新版本后taro doctor  报错了，自己安装了eslint-plugin-react-hooks也没用
···
⠋ 正在诊断项目...(node:59620) UnhandledPromiseRejectionWarning: Error: Failed to load plugin react-hooks: Cannot find module 'eslint-plugin-react-hooks'
···
