### ISSUE TITLE
【H5】模式下Taro.createCanvasContext(this.canvasId, this) 报错

### ISSUE THREAD

**Issue by Rahim-Chan** [NervJS/taro#3601]
在H5下使用`Taro.createCanvasContext(this.canvasId, this)`时报错了。

Cannot read property 'vnode' of undefined

```js
报错文件地址
webpack:///node_modules/@tarojs/taro-h5/src/api/canvas/createCanvasContext.js


```

**系统信息**
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.9.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
贴一下使用的代码吧

**Comment by Rahim-Chan** [comment]
> 贴一下使用的代码吧
```
import Taro, { Component } from '@tarojs/taro';
import PropTypes from 'prop-types';
import { Canvas } from '@tarojs/components';
import './index.css';
function randomString(length) {
    var str = Math.random().toString(36).substr(2);
    if (str.length >= length) {
      return str.substr(0, length);
    }
    str += randomString(length - str.length);
    return str;
  }
export default class CanvasDrawer extends Component {
  constructor(props) {
    super(props);
    this.canvasId = randomString(10);
    this.ctx = null;
  }


  componentDidMount() {
    this.create();
  }

  create = (config) => {
    this.ctx = Taro.createCanvasContext(this.canvasId, this.$scope);
    const height = getHeight(config);

  }


  render() {
    const { pxWidth, pxHeight, debug } = this.state;
    if (pxWidth && pxHeight) {
      return (
        <Canvas
          canvas-id={this.canvasId}
          style={`width:${pxWidth}px; height:${pxHeight}px;`}
          className={`${debug ? 'debug' : 'pro'} canvas`}
        />
      );
    }
    return null;
  }
}
```

**Comment by Littly** [comment]
```javascript
  create = (config) => {
    this.ctx = Taro.createCanvasContext(this.canvasId, this.$scope);
    const height = getHeight(config);

  }
```
`this.$scope`的意思是让你把组件的scope传进去，也就是说一般放`this`就好了，而不是让你把整个`this.$scope`放进去

**Comment by Rahim-Chan** [comment]
> ```js
>   create = (config) => {
>     this.ctx = Taro.createCanvasContext(this.canvasId, this.$scope);
>     const height = getHeight(config);
> 
>   }
> ```
> 
> `this.$scope`的意思是让你把组件的scope传进去，也就是说一般放`this`就好了，而不是让你把整个`this.$scope`放进去

这个我也放this也放了。
![image](https://user-images.githubusercontent.com/18487314/61107338-44fbd700-a4b2-11e9-9e3c-52718fbe619c.png)

**Comment by archerQ** [comment]
请问下这个有解决吗，用Canvas总是会出现各种各样的问题，刚解决一个又出现跟你一样的问题

**Comment by imnotfancy** [comment]
@Rahim-Chan 您好，请问这个问题解决了吗？

**Comment by buuing** [comment]
@Rahim-Chan 现在是崭新的`2021年2月3号`目前为止依然还在报错, 我弱弱的问一下, 这个问题`taro`还有计划修复吗🤣

**Comment by zqqqqz** [comment]
目前H5调用createCanvasContext方法还是会报错，taro版本3.4.3
