### ISSUE TITLE
怎么设置可以让 taro 转成小程序后的代码是 es6 风格的？

### ISSUE THREAD

**Issue by you1cheng** [NervJS/taro#3602]
现在编译之后的代码是 es5 的，看着难受

**Comment by Garfield550** [comment]
Taro 代码的转译是 Babel 管理的，你可以看下能不能改 Babel 设置。

**Comment by luckyadam** [comment]
额，还有这种需求么，taro 目前没有配置关闭 babel 编译的选项

**Comment by Garfield550** [comment]
> 额，还有这种需求么，taro 目前没有配置关闭 babel 编译的选项

可能他在调试时遇到了些问题，因为缺少 sourceMap ，经常在打断点的时候要面对 Babel 过的 ES5 代码。

**Comment by jokester** [comment]
```js
// node_modules/@tarojs/cli/src/weapp.js
// 我把 defaultBabelConfig 注释掉后自己的babel conf (包括targets等) 才生效

const babelConfig = _.mergeWith({}, defaultBabelConfig, pluginsConfig.babel, (objValue, srcValue) => {
```

----------

另外taro用的uglify也不支持es6, 换掉这个之前可能没法es6 ready

**Comment by ZakaryCode** [comment]
[文档](https://nervjs.github.io/taro-docs/docs/config-detail#minicompileexclude)
