### ISSUE TITLE
开发Taro框架的跨端组件，编译出错

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#3608]
**问题描述**
升级到1.3.4之后根据Taro提供的文档[https://taro-docs.jd.com/taro/docs/ui-lib.html](https://taro-docs.jd.com/taro/docs/ui-lib.html)进行编写，编译报如下错误
![image](https://user-images.githubusercontent.com/29176413/60427115-9d1c1900-9c28-11e9-80b2-571c53333e0b.png)

**期望行为**
期望编译出正常的UI组件库

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Linux 4.15 Deepin 15 15.10.1]
 - Taro 版本 [ v.1.3.4]
 - Node.js 版本 [ v12.3.1]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-ui-sample
参考一下这个项目吧
