### ISSUE TITLE
请求一个思路

### ISSUE THREAD

**Issue by YouMaster930615** [NervJS/taro#3609]
是这样  我有一套使用taro 开发的小程序代码   包括里面有一个微信授权这一类在其他浏览器上点击没有效果的组件，想问一下 如果把我这套代码打包成例如h5 rn 之类的 如何做到让授权这些dom以及js功能消失？ 
不能说 让我转成其他端的时候 注释掉吧？

**Comment by YouMaster930615** [comment]
https://nervjs.github.io/taro/docs/envs.html

**Comment by iburning** [comment]
process.env.TARO_ENV 用这个环境属性来判断吧？
