### ISSUE TITLE
componentDidShow 失效

### ISSUE THREAD

**Issue by thisSillyCow** [NervJS/taro#3610]
**问题描述**

返回到上一层的时候  componentDidShow  方法没有执行

**复现步骤**

点击下一页 然后在返回   componentDidShow  方法没有执行

**期望行为**
解决当前的需求

**报错信息**
暂无
**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.4]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [快应用]

**Comment by thisSillyCow** [comment]
快应用 页面的生命周期： onHide、onBackPress、onMenuPress 这三个api都不能用

**Comment by luckyadam** [comment]
没有复现， componentDidShow 表现正常

**Comment by thisSillyCow** [comment]
好的 谢谢 我这边是组件使用 componentDidShow 不行的  不在组件上是可以的
