### ISSUE TITLE
开发小程序插件时支付功能怎么样调用

### ISSUE THREAD

**Issue by chunyangyang** [NervJS/taro#3616]
**问题描述**
在使用taro开发微信小程序插件的时候要调用支付功能，但是微信需要使用FunctionalPageNavigator，来调起支付，然后在微信的开发文档有需要配置功能页函数
![image](https://user-images.githubusercontent.com/20843521/60476252-7653f600-9cad-11e9-9c83-a9e91eeed6ab.png)

**复现步骤**
![image](https://user-images.githubusercontent.com/20843521/60476285-9b486900-9cad-11e9-91a9-37b0a24a8c7d.png)
可以正常调起支付但是功能函数无法使用

**期望行为**
期望可以正常使用微信的支付功能

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac
 - Taro 版本 1.3.3
 - Node.js 版本 8.9
 - 报错平台 weapp

**Comment by Chen-jj** [comment]
@Huatingzi 再看看小程序文档吧，感觉是你没用对。

**Comment by Huatingzi** [comment]
![image](https://user-images.githubusercontent.com/20843521/60512378-fc505b00-9d06-11e9-85e1-03b5041ebbf1.png)
我主要是不知道这一步在taro要怎么写，因为我在src/plugin下建了目录会说我没引用
![image](https://user-images.githubusercontent.com/20843521/60512526-58b37a80-9d07-11e9-9d5e-d46fcb0f7640.png)
在taro里面没有找到相应的开发指导，项目就差这一个功能了，麻烦大神给指点指点

**Comment by Chen-jj** [comment]
@Huatingzi 这个文件不是写在插件里的，仔细看文档吧。这种文件没被引用不会经过 Taro 编译，你可以配置 copy 配置项直接输出到 dist。
