### ISSUE TITLE
QuickApp 不支持React的ref功能

### ISSUE THREAD

**Issue by kongzhe607** [NervJS/taro#3617]

**Comment by kongzhe607** [comment]
alipay和weapp都支持ref引用，但是同样的代码quickapp环境无法使用，建议同步该功能https://nervjs.github.io/taro/docs/ref.html

**Comment by luckyadam** [comment]
在快应用文档中没有找到获取页面元素和组件的方法，所以暂时无法实现这个特性，需要与快应用的开发人员沟通一下

**Comment by jiongrui** [comment]
@luckyadam  
![image](https://user-images.githubusercontent.com/30332228/75424186-1ff1a100-597b-11ea-88da-36cacf53951f.png)

**Comment by Chen-jj** [comment]
duplicate #4245
