### ISSUE TITLE
使用classnames 内容无法渲染

### ISSUE THREAD

**Issue by super918180** [NervJS/taro#362]
`<View className='category-left'>
          {Object.keys(data).map(v => (
            <View key={v} className={cls('left-item', {['left-item-active']: data[v].select})}>
              {data[v].name}
            </View>
          ))}
        </View>`

改代码中  {data[v].name} 显示空白，把className删除掉就能正常显示

**Comment by luckyadam** [comment]
有报什么错么

**Comment by super918180** [comment]
没有任何报错，从微信开发者工具可以看到，class已经正确显示了，但是下面的内容部分为空

**Comment by luckyadam** [comment]
请问更新到最新的 beta 版本还存在这个问题么~
