### ISSUE TITLE
【微信小程序】scss生成wxss时能否去掉注释

### ISSUE THREAD

**Issue by alvinwsz** [NervJS/taro#3622]
当前版本是1.3.0，使用了taro ui组件库2.2.1
1. app.scss里全局应用了需要的组件style文件，然后生成app.wxss出现了N次相同的注释
2. 为保持风格一致，自定义组件和页面也都使用了taro ui风格，生成的wxss也有同样的注释
主要是注释不小，累积下来导致小程序包过大，没法真机调试。
希望能在生成wxss文件时将这些注释去掉

**Comment by Garfield550** [comment]
你用的是 dev 模式吧，而且以 `/* I'm a comment. */` 形式包裹的注释是不会被过滤掉的，单行注释会被删除 `// I'm a comment.`。
参考: https://stackoverflow.com/questions/16844408/which-output-styles-remove-multiline-line-comments

**Comment by Garfield550** [comment]
试验了一下，好像 Taro 只会在 production 时才会加载 csso 配置，我在我的 prod.js 里把 csso `enable: false` 不会压缩样式文件和去掉注释，dev.js 里 `enable: true` 然后怎么配置都不会压缩样式文件

![image](https://user-images.githubusercontent.com/3471836/60485491-c479f100-9ccf-11e9-836b-c45ce9babd77.png)
![image](https://user-images.githubusercontent.com/3471836/60485582-0c991380-9cd0-11e9-82d2-db551771832d.png)

这两个配置的生成结果是一样的，如下
![image](https://user-images.githubusercontent.com/3471836/60485509-d3f93a00-9ccf-11e9-8fe0-35076f6314a7.png)

**Comment by Garfield550** [comment]
果然只有 Production 时才读配置

https://github.com/NervJS/taro/blob/4699d020217b5c3f26d25576b1ad841d8f04f6ff/packages/taro-cli/src/mini/compileStyle.ts#L259-L266

**Comment by alvinwsz** [comment]
这么效率，点赞，验证ok，谢了
