### ISSUE TITLE
render里面jsx不能整合数据，必须在return外面整合好了才能使用，否则会报Cannot read property 'map' of undefined错

### ISSUE THREAD

**Issue by wangjingwj** [NervJS/taro#363]
**问题描述**

在render里面遍历数组的时候，数组返回的数据需要整合，如果在里面直接整合就会报错，必须在return之前整理好才不会报错

**复现步骤**

//报错的代码，主要是`${host}${item.logo_url}`这个引起的报错
needPayList && needPayList.length && needPayList.map((item,i) => {
                            return (
                                            <Image src={`${host}${item.logo_url}`}   />
                            )
                        })

编译报错的源码截图如下
![image](https://user-images.githubusercontent.com/13778018/43034758-02fba322-8d15-11e8-9c4c-6643a6999763.png)

**期望行为**

上面的item.log_url选要加上域名信息，host是一个全局变量,字符串拼接，希望展示完成的图片链接
**报错信息**
Cannot read property 'map' of undefined;at pages/confirm/index page lifeCycleMethod onLoad function
TypeError: Cannot read property 'map' of undefined
[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/13778018/43034650-f5192362-8d12-11e8-83d0-097bda91e819.png)

**系统信息**

 - 操作系统: ----- Windows 10
 - Taro 版本 ---0.0.71
 - Node.js 版本 ---8.11.3

**补充信息**

如果我在return之前整合好数据就不会报错了，如下图
![image](https://user-images.githubusercontent.com/13778018/43034677-86e57890-8d13-11e8-903a-5ca8fc16afdb.png)
![image](https://user-images.githubusercontent.com/13778018/43034681-b26c7bee-8d13-11e8-84ff-f90423d9a344.png)

needPayList && needPayList.length && needPayList.map((item,i) => {
            item.payStyleImg = `${host}${item.logo_url}`
        });  
主要是在item.payStyleImg走这一步的就没问题了，然后后续的代码里面直接使用展示就可以了，如果实在数据每一项里面直接整合数据，map就会报undefined的错误

**Comment by yuche** [comment]
给 `needPayList `设置一个默认值还会报错吗

**Comment by wangjingwj** [comment]
needPayList有一个值，不是needPayList为空报错，而是在jsx里needPayList && needPayList.length && needPayList.map((item,i) => {
return (
<Image src={`${host}${item.logo_url}`} />
)
})整合数据报错，主要是`${host}${item.logo_url}`这一步引起报错

**Comment by luckyadam** [comment]
收到，是属性中存在表达式导致
