### ISSUE TITLE
小程序页面间生命周期对eventCenter的影响

### ISSUE THREAD

**Issue by symnetry** [NervJS/taro#3631]
**复现步骤**
[复现问题的步骤]
在页面A与页面B中的componentDidShow生命周期中都监听了‘timeout’消息
并且在页面A与页面B中的componentDidHide生命周期中都取消监听了这一消息
现在初次加载，进入页面A 触发timeout,能够收到相应消息
此时跳转(Taro.navigateTo)到页面B，然后再跳转回页面A，再次触发timeout,能够收到来自2个页面的消息

**期望行为**
既然我在B页面取消监听了这一事件，回到A页面的时候应该听不到B页面的消息

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.3.0-beta.6 
System: OS: Windows 10                                                                 
Binaries: Node: 11.9.0

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
Taro 的 eventCenter 在设计之初就是一个 general purpose 的事件机制，不应该和组件的生命周期绑定。

如果你需要绑定组件生命周期或者做更细化的管理可以使用 Hooks 或 Redux。

**Comment by JasonYan2015** [comment]
有点不太明白
eventCenter如果要使用的话，肯定会需要在生命周期里声明on的吧，然后为了消除不同页面on的影响，需要在hide周期里off掉
看起来没毛病呀？
