### ISSUE TITLE
【taroize】微信小程序转换taro过程中，require引用资源，其参数为表达式时，转换失败

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3644]
**问题描述**
[问题描述：微信小程序转换taro过程中，require引用资源，其参数为表达式时，转换失败]

**复现步骤**
[复现问题的步骤]
1. taro convert转换微信小程序项目
2. 出错
这样书写时，报错
```
const root = '../../../../util/';
const location = require(root + 'location.js');
```

**期望行为**
[转换正常，不报错，支持require动态引入]

**报错信息**

![image](https://user-images.githubusercontent.com/13342245/60559094-06617080-9d7e-11e9-8d36-5db101b0f479.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.2]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据错误信息提示，现已定位是对require动态引入语句转换失败]

**Comment by yuche** [comment]
Taro 本身还不支持动态引用，这个特性在可见的未来是不会支持了。
