### ISSUE TITLE
不太相信。

### ISSUE THREAD

**Issue by AibiTi** [NervJS/taro#365]
> Taro 已经投入到了生产环境使用，超过 3 万行代码的 TOPLIFE 小程序已全面上线。

Taro 在初期都表现出很多 BUG，都现在还是有很多 BUG， Taro 已经投入到了生产环境使用，真的不太相信这句话的真实性。更让人怀疑这是一个营销的广告语。

**Comment by chm1n9** [comment]
issues里的bug，大部分都遇到了 -.-， 一般都hack掉了

**Comment by kenberkeley** [comment]
有 bug 其实很正常，但很多非常基础非常低级的 bug 其实就显得 taro 千疮百孔，用起来也没有足够的信心

**Comment by lanshengzhong** [comment]
这么急着用吗？不如先观望观望 。开源不易！

**Comment by lloydzhou** [comment]
反正我用了3天，遇到一个老李说要重构一周的bug后，将项目迁移到了wepy

**Comment by AibiTi** [comment]
**我的意思是：**对于一个有 3 万行代码上线产品的框架应该不会有太多的 **“坑”**。但实际开发与体验中就遇到了非常多的问题。不知道他们是怎么做这个  TOPLIFE  的。

**Comment by luckyadam** [comment]
翻看所有的 issue， Taro 主要的 bug 集中在小程序的组件化，这一部分已经在重构了，并且接近重构完成。
而TOPLIFE 开发的时候对组件使用程度不深，导致很多问题没有发现，同时前一段时间 Taro 也在疯狂迭代增加网友所期望的功能，测试不能及时补上，才导致一些低级问题的出现。
小程序组件化重构完成后，Taro 将趋于稳定，请大家拭目以待。

**Comment by rainbowMorelhahahah** [comment]
小程序 真的bug 超级多。。。。

**Comment by yuzexing** [comment]
最近正在选小程序框架，观望中...

**Comment by YikaJ** [comment]
@luckyadam 确实 BUG 都体现在小程序的自定义组件上面，我认为原因就在于小程序是基于 Web Component / Shadow DOM 去实现的自定义组件，和原本使用 React 有很大的不同，更何况在小程序下 props 传 function 还会被 JSON.stringify 去掉。
我在想是不是小程序自定义组件这一块其实用 template 去实现更加合理呢？用 template 去构建一个组件出来，在全局绑 event / state，用 template data 来传递 props 。这样编译出来的组件应该不会有过多受限于小程序自定义组件的问题，而且会和 React 组件更加相像。

**Comment by luckyadam** [comment]
@YikaJ 
使用 template 来实现组件会带来很多不可控的问题，特别是在循环组件渲染、组件多重嵌套的情况下，要保证组件正确渲染与 `props` 正确传递的难度非常大，实现的成本也非常高，这样就会带来很多问题，而且多数情况下，性能并不好，举个例子

```js
render () {
    return (
        <View>
          {this.list.map(item => {
            return (
              <View>
                <A title='a' prop={item}></A>
                <B title='b' prop={item}></B>
                <C title='c' prop={item}></C>
              </View>
            )
          })}
        </View>
    )
  }
```

要保证上述循环渲染的组件传参，使用 `template` 实现成本就比较高，甚至还要借助 `wxs` 来实现。

而且，使用 `template` 还有一个比较严重的问题就是，**子组件的更新必须依赖页面**，就是在子组件中，执行 `setState` 操作，最终肯定是要调用到页面的 `setState` ，这样就会导致页面中一个很深层次的简单子组件如果调用 `setState` 去更新自己，结果却发现需要调用到页面的 `setState` 方法，从而带动大面积的更新操作，由此带来性能问题。

正所谓，“做的越多，错的越多”。所以基于以上种种原因，我们在 `1.0.0-beta.x` 版本起就开始采用小程序的自定义组件化，我们只需要在小程序组件之上做一层轻量的封装，这样带来的好处就是
- 组件化更加健壮
- 尽可能减少由于框架带来的性能问题
- 依托官方组件化，方便以后解锁更多可能

以上。

**Comment by kenberkeley** [comment]
@luckyadam @yuche 辛苦了~
