### ISSUE TITLE
this.$router 在 @tarojs/taro 下 index.d.ts 里的类型描述与实际内容不一致

### ISSUE THREAD

**Issue by xiamu14** [NervJS/taro#3650]
**问题描述**
在类组件中的 componentDidMount 方法下使用 this.$router 时发现 vscode 根据类型文件提示 this.$router 具有 params 和 preload 两个对象值，但运行时发现 this.$router 具有 params 和 path 两个对象值。"@tarojs/taro": "1.3.2" 的类型描述文件 index.d.ts 关于 $router 的描述不正确。

**复现步骤**
[复现问题的步骤]
1.  在组件 componentDidMount 方法中使用 this.$router ，vscode 会给出如下图提示：
![vscode 提示](http://static.ohcat.xyz/taro_type_error.png)
2. 添加打印 this.$router 的代码，如下：
```js
console.log(this.$router)
```
3. 在微信开发者工具中查看，显示如下打印信息：
![微信开发者工具](http://static.ohcat.xyz/taro_type_error_2.png)

```js
import Taro, { Component, Config } from '@tarojs/taro'
import { View } from '@tarojs/components'
// import { AtButton } from 'taro-ui''
import TabBar from '../../components/TabBar'
import './index.scss'

export default class Index extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () {
    Taro.setNavigationBarColor({
      frontColor: '#ffffff',
      backgroundColor: '#01ABBA',
      animation: {
        duration: 0,
        timingFunc: 'easeIn'
      }
    })
  }

  componentDidMount () {
    console.log(this.$router);
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  chooseAddress() {
    Taro.chooseAddress({
      success: (res) => {
        console.log(res)
      },
      fail: function(err) {
        // chooseAddress:fail auth deny 拒绝授权 主动拒绝后 只有用户清除小程序 才能重新拉起授权
        // chooseAddress:fail cancel 同意授权 但是 取消选择地址
        console.log(err)
      }
    })
  }

  render () {
    return (
      <View className='home_wrap'>
        <View className='home_img'>
          <View className='menu'>
            <View className='edit item'>
              <View className='title'>发物流</View>
              <View className='subtitle'>预约上门取件</View>
            </View>
            <View className='order item'>
              <View className='title'>发物流</View>
              <View className='subtitle'>预约上门取件</View>
            </View>
          </View>
          {/* <AtButton type="primary" onClick={this.chooseAddress}>获取收货地址</AtButton> */}
        </View>
        <TabBar path={this.$router.path}></TabBar>
      </View>
    )
  }
}

```

**期望行为**
@tarojs/taro 的类型描述文件和实际运行时结果一致

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
$ /Users/ben/Documents/w/sideproject/outsouring/deliver_goods/node_modules/.bin/taro info
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /var/folders/cg/psfybknj4tlg8br8c4hf4bs80000gn/T/yarn--1562136357730-0.8261955126947313/node
      Yarn: 1.16.0 - /var/folders/cg/psfybknj4tlg8br8c4hf4bs80000gn/T/yarn--1562136357730-0.8261955126947313/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.4 => 1.3.4
      @tarojs/cli: ^1.3.4 => 1.3.4
      @tarojs/components: 1.3.2 => 1.3.2
      @tarojs/plugin-babel: 1.3.2 => 1.3.2
      @tarojs/plugin-csso: 1.3.2 => 1.3.2
      @tarojs/plugin-sass: 1.3.2 => 1.3.2
      @tarojs/plugin-uglifyjs: 1.3.2 => 1.3.2
      @tarojs/router: 1.3.2 => 1.3.2
      @tarojs/taro: 1.3.2 => 1.3.2
      @tarojs/taro-alipay: 1.3.2 => 1.3.2
      @tarojs/taro-h5: 1.3.2 => 1.3.2
      @tarojs/taro-swan: 1.3.2 => 1.3.2
      @tarojs/taro-tt: 1.3.2 => 1.3.2
      @tarojs/taro-weapp: 1.3.2 => 1.3.2
      @tarojs/webpack-runner: 1.3.2 => 1.3.2
      eslint-config-taro: 1.3.2 => 1.3.2
      eslint-plugin-taro: 1.3.2 => 1.3.2
      nerv-devtools: ^1.4.0 => 1.4.1
      nervjs: ^1.4.0 => 1.4.1

 - 报错平台 [weapp]

**Comment by Garfield550** [comment]
preload 是有的，参考 https://nervjs.github.io/taro/docs/optimized-practice.html#%E5%9C%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%AD-%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8-this-preload-%E5%87%BD%E6%95%B0%E8%BF%9B%E8%A1%8C%E9%A1%B5%E9%9D%A2%E8%B7%B3%E8%BD%AC%E4%BC%A0%E5%8F%82

![image](https://user-images.githubusercontent.com/3471836/60635420-5eaf7580-9e45-11e9-8373-1310b085ccfd.png)

**Comment by Chen-jj** [comment]
@xiamu14 preload 可选，你可以提个 pr 改成可选属性。path 不是供用户用的，没有必要在 types 中声明。

**Comment by Garfield550** [comment]
> @xiamu14 preload 可选，你可以提个 pr 改成可选属性。path 不是供用户用的，没有必要在 types 中声明。

我把 path 加上了，preload 我去改成可选吧。#3653

**Comment by Garfield550** [comment]
> @xiamu14 preload 可选，你可以提个 pr 改成可选属性。path 不是供用户用的，没有必要在 types 中声明。

我突然考虑到一种情况，有的用户可能会用这个 Path 来做打点。

**Comment by Chen-jj** [comment]
@Garfield550 path 不是必有的，我记得是页面跳转有传参时，用于标记取回参数的，不太建议用户使用。

**Comment by Garfield550** [comment]
@Chen-jj 那我删掉好了

**Comment by ppbl** [comment]
@Chen-jj  比如我现在维护的一份代码，path 确实被使用了，不管建议不建议，这个属性暴露出来了不是吗，如果换成 ts 就会报错

**Comment by xiamu14** [comment]
谢谢你们及时的反馈，这个我了解怎么处理了。
