### ISSUE TITLE
设置externalClasses在升级taro版本后不生效

### ISSUE THREAD

**Issue by GYDSB** [NervJS/taro#3651]
? Taro v1.3.3

  Taro CLI 1.3.3 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: 1.3.4 => 1.3.4 
      @tarojs/redux-h5: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 

未升级前1.2.6版本是正常的-

**Comment by Garfield550** [comment]
试试这边的方法 https://github.com/NervJS/taro/issues/3573#issuecomment-507134154

**Comment by Chen-jj** [comment]
@GYDSB 升级到最新版本后再试试。

**Comment by Chen-jj** [comment]
#3573
