### ISSUE TITLE
Taro.request 调用abort方法 报错

### ISSUE THREAD

**Issue by ouyangshan09** [NervJS/taro#3654]
**问题描述**
使用Taro.request() 返回的值，调用abort() 报错

**复现步骤**
[复现问题的步骤]
1. 导入`@tarojs/taro`
2. 执行 `const requstTask = Taro.rqeust(object)`
3. 执行 `requstTask.abort()`
4. 小程序报错，报错如图下所示
![image](https://user-images.githubusercontent.com/3814130/60578184-5c9cd680-9db3-11e9-881d-73d21e783349.png)

```js
const requestTask = Taro.request({
  url: 'https://xxx/api/auth/login',
  data: {
    account: 'admin',
    password: '123456',
  },
  method: 'POST',
  success: (res) => {
    console.log('request login res:', res);
  },
  fail: (error) => {
    console.log('request login error:', error);
  },
  complete: () => {
    console.log('request login complete:');
  }
});
requestTask.abort()
```

**期望行为**
调用abort方法，可以正常取消请求，并且ts不会提示`类型“Promise<Promised<any>>”上不存在属性“abort”`

**报错信息**
![image](https://user-images.githubusercontent.com/3814130/60578184-5c9cd680-9db3-11e9-881d-73d21e783349.png)

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.4]
 - Node.js 版本 [e.g. v8.9.3]
 - 报错平台 [weapp]

**补充信息**
#1178 该问题并没有修复

**Comment by Garfield550** [comment]
@Chen-jj 看代码是把 `abort()` 方法加到 `request` 返回的 `res` 上了对吗？

```js
const response = await Taro.request(...param);
response.abort();
```

**Comment by Chen-jj** [comment]
@Garfield550 不是呃，加到 res 上就没有 abort 的意义了，因为请求已经完成了。

可以像楼主这样用：

```js
const requestTask = Taro.request({
  url: 'https://xxx/api/auth/login',
  data: {
    account: 'admin',
    password: '123456',
  },
  method: 'POST',
  success: (res) => {
    console.log('request login res:', res);
  },
  fail: (error) => {
    console.log('request login error:', error);
  },
  complete: () => {
    console.log('request login complete:');
  }
});
requestTask.abort()
```

也可以：

```js
const requestTask = Taro.request({
  url: 'https://xxx/api/auth/login',
  data: {
    account: 'admin',
    password: '123456',
  },
  method: 'POST'
});
if (reason) requestTask.abort()
requestTask
  .then(res => ...)
```

**Comment by Garfield550** [comment]
@Chen-jj 那么意味着 async/await 方式没有办法用 abort 吗？
另外 taro request 的 typings ，abort 该怎么定义

**Comment by Garfield550** [comment]
```ts
namespace request {
  type Promised<T extends any | string | ArrayBuffer = any> = {
    data: T;
    statusCode: number;
    header: any;
  };
  type Param<P extends any | string | ArrayBuffer = any> = {
    url: string;
    data?: P;
    header?: any;
    method?:
      | 'OPTIONS'
      | 'GET'
      | 'HEAD'
      | 'POST'
      | 'PUT'
      | 'DELETE'
      | 'TRACE'
      | 'CONNECT';
    dataType?: string;
    responseType?: string;
    jsonp?: boolean;
    jsonpCache?: boolean;
    mode?: 'no-cors' | 'cors' | 'same-origin';
    credentials?: 'include' | 'same-origin' | 'omit';
    cache?:
      | 'default'
      | 'no-cache'
      | 'reload'
      | 'force-cache'
      | 'only-if-cached';
    timeout?: number;
    retryTimes?: number;
    backup?: string | string[];
    dataCheck?(): boolean;
    useStore?: boolean;
    storeCheckKey?: string;
    storeSign?: string;
    storeCheck?(): boolean;
    success?: ParamPropSuccess;
    fail?: ParamPropFail;
    complete?: ParamPropComplete;
  };
  type ParamPropSuccess = (res: any) => any;
  type ParamPropFail = (err: any) => any;
  type ParamPropComplete = () => any;
}

function request<T = any, U = any>(
  OBJECT: request.Param<U>
): Promise<request.Promised<T>>;
```

当前 request 的 typings 是这样的，Promise 返回的是 `{ data: T = any, statusCode: number, header: any }`

**Comment by Chen-jj** [comment]
@Garfield550 可以吧。

```js
const response = Taro.request(...param);
const res = await response
response.abort();
```

types 可以这样定义：

![{EB07467C-B62B-2463-F0E6-697DA51A88CA}](https://user-images.githubusercontent.com/11807297/60794125-a7e02c00-a19b-11e9-9af5-e45f8c716b57.jpg)

**Comment by Garfield550** [comment]
@Chen-jj 你看这么定义可以吗？

```ts
namespace request {
  type Promised<T extends any | string | ArrayBuffer = any> = {
    data: T;
    statusCode: number;
    header: any;
  };

  interface requestTask<T> extends Promise<request.Promised<T>> {
    abort(): void;
  }

  type Param<P extends any | string | ArrayBuffer = any> = {
    url: string;
    data?: P;
    header?: any;
    method?:
      | 'OPTIONS'
      | 'GET'
      | 'HEAD'
      | 'POST'
      | 'PUT'
      | 'DELETE'
      | 'TRACE'
      | 'CONNECT';
    dataType?: string;
    responseType?: string;
    jsonp?: boolean;
    jsonpCache?: boolean;
    mode?: 'no-cors' | 'cors' | 'same-origin';
    credentials?: 'include' | 'same-origin' | 'omit';
    cache?:
      | 'default'
      | 'no-cache'
      | 'reload'
      | 'force-cache'
      | 'only-if-cached';
    timeout?: number;
    retryTimes?: number;
    backup?: string | string[];
    dataCheck?(): boolean;
    useStore?: boolean;
    storeCheckKey?: string;
    storeSign?: string;
    storeCheck?(): boolean;
    success?: ParamPropSuccess;
    fail?: ParamPropFail;
    complete?: ParamPropComplete;
  };
  type ParamPropSuccess = (res: any) => any;
  type ParamPropFail = (err: any) => any;
  type ParamPropComplete = () => any;
}

function request<T = any, U = any>(
  OBJECT: request.Param<U>
): request.requestTask<T>;

```

![image](https://user-images.githubusercontent.com/3471836/60794537-90ee0980-a19c-11e9-9728-8e366cd5a39e.png)

**Comment by Chen-jj** [comment]
@Garfield550 可以呀

**Comment by Garfield550** [comment]
@Chen-jj OK 我去提 PR 了

**Comment by Garfield550** [comment]
@Chen-jj 下面两个暂时还不支持对吗

[RequestTask.offHeadersReceived(function callback)](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/RequestTask.offHeadersReceived.html)

[RequestTask.onHeadersReceived(function callback)](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/RequestTask.onHeadersReceived.html)

**Comment by Chen-jj** [comment]
@Garfield550 可以搞，还没空搞，大概是 request params 里有定义这两个函数的话，给加到 requestTask 上。欢迎 PR 哈。

**Comment by Garfield550** [comment]
@Chen-jj 可以 Review 一下，有问题在 PR 上提 Request Change

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/60797716-699a3b00-a1a2-11e9-966d-ccf169217ccd.png)

注释的示例代码为 VSCode 优化了一下

**Comment by TigerHee** [comment]
调用addInterceptor后Taro.request的返回就没有abort方法了

**Comment by FE-wuhao** [comment]
> 调用addInterceptor后Taro.request的返回就没有abort方法了

后来咋解决的啊哥们儿  现在还是这个样子 一旦加了拦截器就没办法阻断请求了

**Comment by languis** [comment]
> > 调用addInterceptor后Taro.request的返回就没有abort方法了
> 
> 后来咋解决的啊哥们儿 现在还是这个样子 一旦加了拦截器就没办法阻断请求了

估计是你是直接then然后返回了..  官方文档忒差了.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/14243687/175802211-8947e6eb-30dc-44a0-afb0-a638d7c1cd06.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/14243687/175802229-6fc12bea-ca1e-4f58-82ff-6954294807b2.png">
