### ISSUE TITLE
微信小程序登录偶尔出现500的情况，code 和 iv 和 encrypted每点一次都获取的新的

### ISSUE THREAD

**Issue by guanyueming** [NervJS/taro#3660]
> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)
![image](https://user-images.githubusercontent.com/37822389/60586360-81e61080-9dc4-11e9-8186-678e793df566.png)

![image](https://user-images.githubusercontent.com/37822389/60586403-95917700-9dc4-11e9-90d1-e995ba229136.png)

🙏🙏🙏

------------------------

**问题描述**

**复现步骤**
[复现问题的步骤]
1. 点击微信登录按钮
2. 每次获取新的code、iv、encrypted
3. 拿到值调后端的接口偶尔出现500的情况
4. 
![image](https://user-images.githubusercontent.com/37822389/60586638-09cc1a80-9dc5-11e9-8f41-1a31737b9a14.png)

**期望行为**
不会出现偶尔500的情况

 - 操作系统: [Windows 10，真机]
 - 报错平台 [weapp]

**Comment by Garfield550** [comment]
HTTP 500 已经告诉你了是 Internal Server Error（内部服务器错误）

> The 500 Internal Server Error is a very general HTTP status code that means something has gone wrong on the website's server, but the server could not be more specific on what the exact problem is.

**Comment by yuche** [comment]
这不是一个 Taro 相关的问题
