### ISSUE TITLE
关于css缓存问题

### ISSUE THREAD

**Issue by gebilaofan** [NervJS/taro#3661]
**h5公众号样式缓存**
h5公众号编译完，丢到服务器运行之后，下次编译修改完，线上运行会出现严重的缓存。之前调试微信公众号分享的时候，被缓存折磨了一个晚上。现在项目每次编译完，在不同的机型上都会出现一个缓存的问题，手机上的样式不一样。每次调试都要清除缓存，或者是重新刷新页面。但我们的客户不知道有缓存要刷新页面。
后来在文档里面找到配置，在config下的index.js加上如下代码：
```
    output: {
      filename: 'js/[name].[hash:8].js',
      chunkFilename: 'js/[name].[chunkhash:8].js',
    },
```
这样可以有效的清除js缓存，可css缓存怎么清除。

我试过吧编译好的css文件名，通过node脚本动态的凭借上时间戳，但这样丢到线上服务器，就开始报错。

![image](https://user-images.githubusercontent.com/46524158/60591327-d4c5c500-9dd0-11e9-989f-040cddf8af4e.png)

我找过原因，css文件是对于你app.js page下的页面，你修改了样式名，js会找不到样式就会报错。
![image](https://user-images.githubusercontent.com/46524158/60591385-f45ced80-9dd0-11e9-9173-8cc4e5365c55.png)

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.3.4]
 - Node.js 版本 [e.g. v10.16.0]
 - 报错平台 [h5,]

**补充信息**
Taro还是根据webpack的打包机制来的，应该是可以在配置里面加输出的样式名 ，每次编译完的样式名都不一样，可以跟output输出时候加上hash防止缓存。

**Comment by luckyadam** [comment]
https://taro-docs.jd.com/taro/docs/config-detail.html#h5minicssextractpluginoption

**Comment by gebilaofan** [comment]
> https://taro-docs.jd.com/taro/docs/config-detail.html#h5minicssextractpluginoption

已解决

**Comment by gebilaofan** [comment]
> https://taro-docs.jd.com/taro/docs/config-detail.html#h5minicssextractpluginoption

> 已解决

**Comment by gebilaofan** [comment]
> https://taro-docs.jd.com/taro/docs/config-detail.html#h5minicssextractpluginoption

  >  

- [ ] 

- [ ] 

- 试试

**Comment by hugh0524** [comment]
https://taro-docs.jd.com/taro/docs/config-detail.html#h5minicssextractpluginoption  加上之后可以对css加hash，但是在app.js中引入的css没有正确修改文件名

**Comment by Already5402** [comment]
https://taro-docs.jd.com/docs/config-detail#miniminicssextractpluginoption
