### ISSUE TITLE
canvas绘制有问题

### ISSUE THREAD

**Issue by alvinwsz** [NervJS/taro#3667]
当前版本1.3.0
原本需要的功能是组件内容导出为图片，但目前做不到，只好使用canvas按组件内容布局绘制图片。但是目前看来效果不好
1. 首先是像素比例问题：setLineWidth(1)画的线远远比组件border(solid 1px)要粗的多，setFontSize(12)也远比style(font-size:12px)大
2. font和line颜色有变且被模糊钝化处理：因为不知道上述比例关系，尝试setLineWidth(0.1)，画的线还是比border(solid 1px)要宽，且被模糊钝化处理，而且黑色线被绘制成灰色，fontsize改小也存在同样问题

对这部分不了解，想请教下
1. canvas和组件所使用像素大小比例关系是怎样的
2. 怎样能绘制出跟组件渲染一样效果的图片
谢谢

**Comment by jinjinjin0731** [comment]
如果是小程序的话。那他默认的值 px 。他不会像 rpx 一样进行相应。 这块可能需要动态计算。 最后显示效果已真机为准吧
