### ISSUE TITLE
不支持传递函数？

### ISSUE THREAD

**Issue by Varavarforvar** [NervJS/taro#367]
rt

**Comment by luckyadam** [comment]
代码贴出来看看哦

**Comment by xiaoyuze88** [comment]
![image](https://user-images.githubusercontent.com/5201649/59489530-04aa3880-8eb5-11e9-89e4-35f4331beb83.png)
![image](https://user-images.githubusercontent.com/5201649/59489551-11c72780-8eb5-11e9-8b52-4603f91920ea.png)
![image](https://user-images.githubusercontent.com/5201649/59489556-155aae80-8eb5-11e9-9974-e45cd2c991ee.png)

不太确定这里面的实现逻辑，如图，按该方式传递函数在原生小程序内是可以传过去的，但是taro中只有 test1 中的形式可以传递过去。其他是被 `shakeFnFromObject` 函数过滤掉了，test1 不知道为啥能够传递。

我们的场景是需要传递 function 类型的 validator 进去 form 组件，不知道能否按照原生小程序支持的特性来实现？
