### ISSUE TITLE
TS中Taro.memo没有导出

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro#3670]
**问题描述**
在Typescript中使用Taro.memo报错

**复现步骤**
```js
Taro.memo(xxxx)
```

**期望行为**
导出Taro.memo

**报错信息**
![image](https://user-images.githubusercontent.com/15973148/60644170-db534b80-9e67-11e9-9a4a-21cf70d271ef.png)

**系统信息**
Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-less: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.1 => 1.4.1 
      nervjs: ^1.4.1 => 1.4.1 
      react: ^16.8.6 => 16.8.6 
    npmGlobalPackages:
      typescript: 1.8.10

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/3517
