### ISSUE TITLE
支付宝小程序, 组件嵌套props不传递

### ISSUE THREAD

**Issue by qiliangya** [NervJS/taro#3671]
**问题描述**
在支付宝小程序中组件嵌套无法传递props

**复现步骤**
1. A页面使用B组件，B组件使用C组件 并传递props给C -> C组件无法接收到props
2. A页面直接使用C组件并传递props -> C组件正常接收

**期望行为**
组件嵌套传递props能正常

**系统信息**

 - Taro 1.3.4
 - Node.js 版本 10.15.3
 - 报错平台 alipay

**补充信息**
一开始我是使用taro-ui,并发现在支付宝小程序上, AtActivityIndicator组件无法设置loading的大小[issues](https://github.com/NervJS/taro-ui/issues/661)也是无法接收到props的问题。 但在微信小程序上没有异常

现在自己封装的组件也会出问题

**Comment by Chen-jj** [comment]
@qiliangya 提供代码吧。

**Comment by qiliangya** [comment]
A页面
``` javascript
<View className="container">
        <Test1 demo="測試1"/>
        <Test2 demo="123"/>
</View>
```

Test1组件
``` javascript
<View>
<View>{this.props.demo}</View>
    <Test2 demo="我是測試2"/>
</View>
```

Test2组件
```javascript
<View>
    <View>test2被引入</View>
    <View>{this.props.demo}</View>
</View>
```

test2并未接收到 来着test1组件的props

--------------------------
问题补充, 我的代码在同事的电脑上 能正常跑。
但在我这不行。 重装了依赖也无效

**Comment by Chen-jj** [comment]
@qiliangya 依赖和 CLI 保持版本一致。

**Comment by qiliangya** [comment]
@Chen-jj  版本均为1.3.4。 刚试了下 因为我在项目启动的时候区分了环境, 重新设置了NODE_ENV的 如果NODE_ENV为test 就会出这个问题, 但如果NODE_ENV是别的值就不会。  这个也能影响? 不能设置为test吗

**Comment by Chen-jj** [comment]
@qiliangya 不会影响

**Comment by qiliangya** [comment]
@Chen-jj  现在就是我运行 test命令 就出现我说的上述问题, 运行dev命令 就不会 一切正常
![image](https://user-images.githubusercontent.com/31298600/60651684-507b4c80-9e79-11e9-8761-ebcdfdd9142d.png)

test命令
![image](https://user-images.githubusercontent.com/31298600/60651733-62f58600-9e79-11e9-87c3-92d194f555ca.png)

dev命令
![image](https://user-images.githubusercontent.com/31298600/60651815-92a48e00-9e79-11e9-8dfe-cd1a514666d1.png)

代码 就是问题开头的那些, 并未做环境区分。。 此外 taro-ui引入组件,只要是有嵌套的组件 在test环境下 也会出现这种问题。 dev环境不会

**Comment by Chen-jj** [comment]
@qiliangya 提供完整的 demo 项目我看看吧

**Comment by qiliangya** [comment]
@Chen-jj  [临时仓库](https://github.com/qiliangya/taro-nodeenv-demo)  麻烦了

**Comment by Chen-jj** [comment]
@qiliangya 的确，NODE_ENV 为 test 时编译时没有给 xml 加上 ` a:if="{{$taroCompReady}}"`，影响到组件生命周期触发顺序，所以 props 传递有问题。你可以换一个环境名称。
