### ISSUE TITLE
升级1.3.5，循环列表点击事件失效

### ISSUE THREAD

**Issue by Kage336** [NervJS/taro#3677]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

升级1.3.5，循环列表点击事件失效，查看编译之后的代码，发现 `data-e-tap-a-a` 字段为 undefined,导致在调用 anonymousFunc0 时，`_$indexKey`为 undefined, 无法调用 `anonymousFunc0Map` 方法

**复现步骤**
[复现问题的步骤]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```tsx


// 这里可以贴代码
// 点击链接查看如何插入代码：

import { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './index.less'

interface IProps {
  /** 当前选中的 tab 下标 */
  current: number;
  onChange(index: number): void;
}
interface IState {
  /** 可选 tab 切 */
  tabList: string[];
}

export default class TabBar extends Component<IProps, IState> {
  static externalClasses = ['cover-class'];
  static defaultProps = {}
  constructor (props) {
    super(props);

    this.state = {
      tabList: ['已支付', '已退货']
    }
  }

  render() {
    return (
      <View className='tabbar-wrapper'>
        {
          this.state.tabList.map((tab, index) => (
            <View
              key={`${tab}-${index}`}
              onClick={() => {
                this.props.current !== index && this.props.onChange && this.props.onChange(index)
              }}
              className={`tab-item ${this.props.current === index ? 'active' : ''}`}
            >{tab}</View>
          ))
        }
      </View>
    )
  }
}

```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
点击页面按钮触发 onChange 事件

**报错信息**
点击无反应，无报错
[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: win10
 - Taro 版本  1.3.5
 - Node.js 版本8.10
 - 报错平台 weapp ( 小程序)

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by lzctbyong** [comment]
是的 ++++++++++++++++1

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/61c54c66fe18cf47e8b0624aff2de7cd5aa3ea4b

**Comment by Tecode** [comment]
@Kage336 
修改
`             
onClick={() => {this.props.current !== index && this.props.onChange && this.props.onChange(index)
}}
`
改为bind方法
`
onClick={this.props.onChange.bind(this,index)}
`
