### ISSUE TITLE
RN: Android 下 Taro.navigateTo 某个页面后，标题没有居中

### ISSUE THREAD

**Issue by goddyZhao** [NervJS/taro#3678]
**问题描述**
两个页面，一个是页面 A、一个页面 B，在A页面中有个按钮，点击后调用：`Taro.navigateTo()`，进入 B 页面，然后发现 B 页面的标题栏的标题没居中（Android 真机下）

**复现步骤**
[复现问题的步骤]
1. 打开 App
2. 点击页面 A 中的按钮，跳转到B
3. 发现B页面标题栏标题没居中

**期望行为**
标题应该居中显示

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![WechatIMG71](https://user-images.githubusercontent.com/164988/60677203-6e65a300-9eb3-11e9-917b-ff966bd3371c.jpeg)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.3.2 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.5 => 1.3.5
      @tarojs/components: 1.3.2 => 1.3.2
      @tarojs/components-rn: ^1.3.2 => 1.3.4
      @tarojs/mobx: 1.3.2 => 1.3.2
      @tarojs/mobx-h5: 1.3.2 => 1.3.2
      @tarojs/mobx-rn: 1.3.2 => 1.3.2
      @tarojs/plugin-babel: 1.3.2 => 1.3.2
      @tarojs/plugin-csso: 1.3.2 => 1.3.2
      @tarojs/plugin-less: 1.3.2 => 1.3.2
      @tarojs/plugin-uglifyjs: 1.3.2 => 1.3.2
      @tarojs/rn-runner: 1.3.2 => 1.3.2
      @tarojs/router: 1.3.2 => 1.3.2
      @tarojs/taro: 1.3.2 => 1.3.2
      @tarojs/taro-alipay: 1.3.2 => 1.3.2
      @tarojs/taro-h5: 1.3.2 => 1.3.2
      @tarojs/taro-redux-rn: ^1.3.2 => 1.3.4
      @tarojs/taro-rn: ^1.3.2 => 1.3.4
      @tarojs/taro-router-rn: ^1.3.2 => 1.3.4
      @tarojs/taro-swan: 1.3.2 => 1.3.2
      @tarojs/taro-tt: 1.3.2 => 1.3.2
      @tarojs/taro-weapp: 1.3.2 => 1.3.2
      @tarojs/webpack-runner: 1.3.2 => 1.3.2
      eslint-config-taro: 1.3.2 => 1.3.2
      eslint-plugin-taro: 1.3.2 => 1.3.2
      nerv-devtools: ^1.4.0 => 1.4.3
      nervjs: ^1.4.0 => 1.4.3
      react: 16.3.1 => 16.3.1
      react-native: 0.55.4 => 0.55.4

**Comment by goddyZhao** [comment]
这个问题应该是很common的问题，请问有相应的回复吗？

**Comment by Pines-Cheng** [comment]
正在排查～

**Comment by goddyZhao** [comment]
@Pines-Cheng ，谢谢，请问有进展吗？

**Comment by Pines-Cheng** [comment]
确实，当存在返回按钮时，会不居中。
