### ISSUE TITLE
PureComponent 的 DidMount 生命周期 setState 回调不执行

### ISSUE THREAD

**Issue by Elliott-Hu** [NervJS/taro#3679]
```js
import Taro, { PureComponent } from "@tarojs/taro"
import { View } from "@tarojs/components";
import PropTypes from "prop-types"

import styles from "./index.module.scss"

// 这边继承的是 PureComponent，如果换成Component 就不会用问题
export default class NavigationBar extends PureComponent {
  static options = {
    addGlobalClass: true
  }

  static propTypes = {
    title: PropTypes.string,
    showHomeIcon: PropTypes.bool,
    dispatchNoticeHeightChange: PropTypes.func
  }
  static defaultProps = {
    showHomeIcon: true,
    title: "AI名片",
    dispatchNoticeHeightChange: (height) => { console.log("navigationBar 高度：", height) }
  }

  state = {
    isFirstPage: true,
    statusBarHeight: 20
  }

  HEIGHT = 44

  componentDidMount() {
    let statusBarHeight = 20
    try {
      statusBarHeight = Taro.getSystemInfoSync().statusBarHeight
    } catch (error) {
      console.log(error)
    }

    // FIXME: 回调不执行
    this.setState({ 
      isFirstPage: Taro.getCurrentPages().length === 1,
      statusBarHeight
    }, () => {
     //  预期应该打印1234，并且dispatchNoticeHeightChange
    //  然而并没有
      console.log(1234)
      this.props.dispatchNoticeHeightChange(this.HEIGHT + statusBarHeight)
   })
    
  }

  handleOnClickBack = () => {
    Taro.navigateBack()
  }
  handleOnClickBackHome = () => {
    Taro.reLaunch({ url: "/page/mainPage/pages/allHouseList/main" })
  }
  renderCapsule = () => {
    const { showHomeIcon } = this.props;
    const { isFirstPage } = this.state;

    if (showHomeIcon) {
      return (
        <View className={`${styles.capsule}${!isFirstPage ? " " + styles.double : ""}`}>
          { !isFirstPage && <View onClick={this.handleOnClickBack} className={styles.btn}><View className={`sprite ${styles["capsule-back"]}`}></View></View> }
          <View onClick={this.handleOnClickBackHome} className={styles.btn}><View className={`sprite ${styles["capsule-home"]}`}></View></View>
        </View>
      )
    }
    if (!isFirstPage) {
      return <View onClick={this.handleOnClickBack} className={`sprite ${styles.back}`}></View>
    }
    return null
  }
  render () {
    const { showHomeIcon, title } = this.props

    console.log("showHomeIcon", showHomeIcon)
    const { statusBarHeight } = this.state
    const style = { "paddingTop": `${statusBarHeight}PX`  }

    return (
      <View className={styles.navigation}>
        <View className={styles.placeholder} style={style}></View>
        <View className={styles.content} style={style}>
          <View className={`${styles["capsule-content"]} ${styles["capsule-left"]}`}>
            { this.renderCapsule() }
          </View>
          <View className={styles.title}>{ title }</View>
          <View className={styles["capsule-content"]}></View>
        </View>
      </View>
    )
  }
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.4 => 1.3.4 
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: 1.3.4 => 1.3.4 
      @tarojs/redux-h5: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
      react: ^16.8.6 => 16.8.6 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@Elliott-Hu 请提供代码。

**Comment by Elliott-Hu** [comment]
`
export default class NavigationBar extends PureComponent {
  static options = {
    addGlobalClass: true
  }

  static propTypes = {
    title: PropTypes.string,
    showHomeIcon: PropTypes.bool,
    dispatchNoticeHeightChange: PropTypes.func
  }
  static defaultProps = {
    showHomeIcon: true,
    title: "AI名片",
    dispatchNoticeHeightChange: (height) => { console.log("navigationBar 高度：", height) }
  }

  state = {
    isFirstPage: true,
    statusBarHeight: 20
  }

  HEIGHT = 44

  componentDidMount() {
    let statusBarHeight = 20
    try {
      statusBarHeight = Taro.getSystemInfoSync().statusBarHeight
    } catch (error) {
      console.log(error)
    }

    // FIXME: 回调不执行
    this.setState({ 
      isFirstPage: Taro.getCurrentPages().length === 1,
      statusBarHeight
    }, () => {
     //  预期应该打印1234，并且dispatchNoticeHeightChange
    //  然而并没有
      console.log(1234)
      this.props.dispatchNoticeHeightChange(this.HEIGHT + statusBarHeight)
   })
    
  }

  handleOnClickBack = () => {
    Taro.navigateBack()
  }
  handleOnClickBackHome = () => {
    Taro.reLaunch({ url: "/page/mainPage/pages/allHouseList/main" })
  }
  renderCapsule = () => {
    const { showHomeIcon } = this.props;
    const { isFirstPage } = this.state;

    if (showHomeIcon) {
      return (
        <View className={`${styles.capsule}${!isFirstPage ? " " + styles.double : ""}`}>
          { !isFirstPage && <View onClick={this.handleOnClickBack} className={styles.btn}><View className={`sprite ${styles["capsule-back"]}`}></View></View> }
          <View onClick={this.handleOnClickBackHome} className={styles.btn}><View className={`sprite ${styles["capsule-home"]}`}></View></View>
        </View>
      )
    }
    if (!isFirstPage) {
      return <View onClick={this.handleOnClickBack} className={`sprite ${styles.back}`}></View>
    }
    return null
  }
  render () {
    const { showHomeIcon, title } = this.props

    console.log("showHomeIcon", showHomeIcon)
    const { statusBarHeight } = this.state
    const style = { "paddingTop": `${statusBarHeight}PX`  }

    return (
      <View className={styles.navigation}>
        <View className={styles.placeholder} style={style}></View>
        <View className={styles.content} style={style}>
          <View className={`${styles["capsule-content"]} ${styles["capsule-left"]}`}>
            { this.renderCapsule() }
          </View>
          <View className={styles.title}>{ title }</View>
          <View className={styles["capsule-content"]}></View>
        </View>
      </View>
    )
  }
}
`

**Comment by Chen-jj** [comment]
@Elliott-Hu 哪个平台

**Comment by Elliott-Hu** [comment]
微信小程序

**Comment by Chen-jj** [comment]
@Elliott-Hu 不是回调不执行，是你的 setState 内容和 data 一样被 diff 过滤，没有执行 setData。自己打打断点就懂了。https://nervjs.github.io/taro/docs/debug.html#debug-diff
