### ISSUE TITLE
【H5 bug】使用navigateBack报错

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#368]
**问题描述**
在项目中，有好几处地方使用了navigateBack方法，本来在0.0.60版本时没有发现问题，之前升级到0.0.70后发现了使用这方法在h5中会报错。

```js
Taro.navigateBack();

```

**报错信息**
![image](https://user-images.githubusercontent.com/22128204/43063512-92a9592c-8e8e-11e8-8b87-2ba2ba590263.png)

**系统信息**

 - Taro 版本 [e.g. v.0.0.70]

**Comment by xingBri** [comment]
使用浏览器的返回，还会出现多个页面样式层叠在一起的bug。

**Comment by Littly** [comment]
fix via 9d8078c
