### ISSUE TITLE
多条件判断小程序编译错误

### ISSUE THREAD

**Issue by niuhuahua** [NervJS/taro#3689]
> **问题描述**
> 组件多条件渲染，通过变量渲染组件。当存在一个变量时，小程序正常，当存在多个变量时，编译失败
> 
> **代码步骤**
> 
> 
> ```js-jsx
> render() {
>     let typeText, btnGroup = null;
>          if( orderItem.status == 3 && (orderItem.payStatus==2 || orderItem.payStatus==3)){
>           typeText = ( <Text className='order-item-title-type'> 分拣中</Text>) 
>           btnGroup = (  <Text className='order-item-title-type'>显示状态按钮 </Text> ) //加上这个变量就注册，注释掉就能成功运行
>         }
>     return (
>       <View className="page">
>         <View className="bigContainer">
>           {typeText }
>          <View>
>         {btnGroup }
>         </View>
>         </View>
>       </View>
>     );
>   }
> ```
>  **代码贴图**
>  [
![微信图片_20190705151936](https://user-images.githubusercontent.com/27671478/60704942-68fe6c00-9f38-11e9-87ee-9ffd967e0533.png)
](url)
>
> **报错信息**
> [
![微信图片_20190705151640](https://user-images.githubusercontent.com/27671478/60704781-fc836d00-9f37-11e9-99d8-5949e59e7bd3.png)
](url)
> [
![微信图片_20190705151648](https://user-images.githubusercontent.com/27671478/60704812-14f38780-9f38-11e9-8db6-b84c36fb4be9.png)
](url)
> **系统信息**
> 
> > Taro v1.2.13
> 
> Windows 10]
> 
> * Node.js 版本 [e.g. v8.9.3]
> * 报错平台 [weapp]

**Comment by yuche** [comment]
升级你的 Taro 就可以解决了
