### ISSUE TITLE
Taro编译小程序没问题，编译h5报错无法正常编译

### ISSUE THREAD

**Issue by vvvvd** [NervJS/taro#3692]
**复现步骤**
一套微信小程序用taro写的代码，正常用yarn dev:weapp进行编译，在微信开发者工具上开发是没有问题的。但是，进行yarn dev:h5进行编译，则会报编译错误。

![image](https://user-images.githubusercontent.com/34501848/60710139-92bd9000-9f44-11e9-93df-296880952c63.png)

代码是一个能在微信小程序开发的一个项目

**期望行为**
期望h5编译成功

**报错信息**
```
🙅   Failed to compile.

./node_modules/taro-ui/dist/h5/components/countdown/index.js 105:11
Module parse failed: Unexpected token (105:11)
You may need an appropriate loader to handle this file type.
|     } = this.state;
| 
>     return <View className={classNames({
|       'at-countdown': true,
|       'at-countdown--card': isCard
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOS]
 - Taro 版本 [e.g. v.1.2.26]
 - Node.js 版本 [e.g. v10.5.0]
 - 报错平台 [h5]

**补充信息**
1、项目中有应用地图amap，但是目前把这个文件以及页面已经删掉重新启动也会有问题。
2、是否在语法上会有不兼容，但是目前报错是node_modules/taro-ui的错误。所以很诡异。

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/60786259-62feca00-a188-11e9-8c4e-5d132c447bfa.png)

**Comment by zlyyyy** [comment]
我这边ts里面报这个错，大佬怎么处理啊 @luckyadam 

```

./src/utils/hooks.ts 18:7
Module parse failed: Unexpected token (18:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
 const { setLoginStatus, systemInfo, autorun, loginout } = userInfoStore
 
> export interface callbackFn {
  (imgs: uploadImgItem[]): void
 }

```
