### ISSUE TITLE
子组件的props不能传递父组件实例

### ISSUE THREAD

**Issue by YuanQuan** [NervJS/taro#3693]
**问题描述** 
子组件的props不能传递父组件实例
**复现步骤** 
 

```
myPage.tsx
...
 return (
            <XPage
                myInstance={this} //这里传递父组件实例
                title="甜甜购"
                isTabBarPage={true}
                className="main"
                scrollTop={scrollTop}
                scrollIntoView={scrollCate}
                onScroll={this.mainOnScroll.bind(this)}
                onScrollToLower={this.getNextData.bind(this)}>
...
```
 子组件XPage.ts
```
interface IProps {
...
    myInstance?:any
...
}

```
**期望行为**
这里编译没有问题，打开页面时候会报错

**报错信息**

![image](https://user-images.githubusercontent.com/2345176/60710591-9f8eb380-9f45-11e9-8b81-fad102765a65.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Mac]
 - Taro 版本 [1.3.2]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
目前字节跳动也同样会报错，大约是Json序列化的错误

**Comment by Chen-jj** [comment]
@YuanQuan props 都会被合并到小程序的 data，组件实例里有循环引用所以小程序序列化对象时会报死循环。因此不能够使用 props 传递组件实例。

绝大部分情况下使用 props 即可，并不需要直接使用父组件对象。如果实在需要，自行使用一个全局文件存吧。
