### ISSUE TITLE
map嵌套后组件响应事件获取数据有误

### ISSUE THREAD

**Issue by derekeeeeely** [NervJS/taro#3695]
**问题描述**
map嵌套后组件响应事件获取数据有误

**复现步骤**
1. 点击4-7 正常打印
2. 点击1-3 打印出[4,5,6,7] 4xxxx
3. event打印出来发现e.target.dataset是一样一样的

```js
        {
          [[1,2,3],[4,5,6,7]].map(item => <View key={item.join(',')}>
            {item.map(_item => (
              <View
                key={_item}
                onClick={() => {console.log(item, _item)}}
              >
                {_item}
              </View>
            ))}
          </View>)
        }
```

**期望行为**
期望嵌套时正确输出

**报错信息**

**系统信息**
  Taro CLI 1.3.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.1/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.15.1/bin/npm

**补充信息**

**Comment by neilwang543** [comment]
遇到一样的问题，希望尽快修复。。

**Comment by Chen-jj** [comment]
#3665

**Comment by Chen-jj** [comment]
先用回 1.3.4

**Comment by robinv8** [comment]
![image](https://user-images.githubusercontent.com/12277531/77719497-5c6af800-7020-11ea-9352-84858e7da599.png)
![image](https://user-images.githubusercontent.com/12277531/77719510-62f96f80-7020-11ea-9cfe-87a0d8e61424.png)

taro 版本 2.0.7
map嵌套，定义事件会报错
