### ISSUE TITLE
eslint/ts 编辑器报错，但是仍能通过编译

### ISSUE THREAD

**Issue by ppbl** [NervJS/taro#3696]
**问题描述**

eslint/ts 编辑器已经报错了，但是仍能通过编译

**复现步骤**

1. 初始化一个项目， 随便改点东西比如把 config: Config 的 : Config 删除了
（修改了一下更直观一点 比如我直接 `ss:string = 1`）

```js
config: number = {
    pages: [
      'pages/index/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  }

  ss: string = 1;
```

**期望行为**

编译不通过

**实际行为**

编译就像往常一样通过了~。。。~(万一哪一天运行时 啪 的报错了，我没脸说我用的 ts 啊)

**系统信息**

>  Taro CLI 1.3.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by Garfield550** [comment]
即使这是 Bug，也不能全依赖工具去纠错啊。

**Comment by yuche** [comment]
出于运行效率和大部分人的需求考虑，编译是不检查类型错误的。如果需要检查可以自行编写 npm scripts 命令。

**Comment by ppbl** [comment]
@yuche
嗯，我明白了就是目前暂时不支持 ts 对吧 
那我要在哪里配置一下呢，能不能大概举个例子，谢谢。 
就比如比如 那种， 稍微具体一点。。。😂

**Comment by ppbl** [comment]
或者官方能不能支持一下 搞个类似于开关的东西， 需要的话可以打开（原谅不是每个人都是大神。）
我觉得按照编译的规则来是错的（ts），还让继续编译, 就好比一个东西明明是犯法的，却让他先干，被不被警察抓到等以后听天由命一样，很奇怪的感觉。。。

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/60716092-1b422d80-9f51-11e9-804b-792a2c39e685.png)

你可以 lint-staged + husky + eslint 来阻止你提交的时候出现这些低级错误。

![image](https://user-images.githubusercontent.com/3471836/60716368-ca7f0480-9f51-11e9-9c04-e6cb5acfccf3.png)

**Comment by ppbl** [comment]
@Garfield550  谢谢你。
