### ISSUE TITLE
h5中使用display控制组件显隐，无法触发componentDidShow周期。

### ISSUE THREAD

**Issue by zheNeng** [NervJS/taro#3699]
**问题描述**

我用display控制显隐，在h5上，子组件捕捉不到componentDidShow这个钩子，
导致，在display切换的时候，不会dispatch mapStateToProps，组件中的props直接少了从redux取的那部分数据

**复现步骤**
[复现问题的步骤]

子组件，接受父组件下传的props，同时也接受从state中connact而来的props。
当父组件通过控制子组件display属性来控制显示隐藏的时候，子组件只能触发componentWillReceiveProps钩子函数.我需要手动触发componentDidShow才能获取来自state的数据。

**期望行为**

dispaly变化的时候，组件能够有反应。

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

componentDidShow 这个钩子的判断条件，不清楚...

**Comment by luckyadam** [comment]
组件的 componentDidShow 是跟随页面的 componentDidShow 而触发的
