### ISSUE TITLE
[H5]`dva-loading`更新无法触发组件的重新渲染

### ISSUE THREAD

**Issue by BennyEu** [NervJS/taro#3704]
**问题描述**
如题

**复现步骤**
[最小复现仓库](https://github.com/BennyEu/taro-dva-loading)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
1.3.5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by 521707** [comment]
我也遇到了同样的问题， 请问解决了吗？
