### ISSUE TITLE
组件带有其他实例属性时，这个属性会重复出现在实例state里面

### ISSUE THREAD

**Issue by kobezhu** [NervJS/taro#3705]
**问题描述**

组件带有其他实例属性（非`state`、`config`等框架指定属性）时，这个属性重复出现在实例`state`里面。

**复现步骤**

有下面组件：
```js
// 组件外面的一个普通变量。
const qux = 5;
class Demo extends Taro.PureComponent {
  state = {
   foo: 1
  }
  render() {
    // 注意这里使用了上面提到的变量`qux`。
    return <View>{ qux }</View>;
  }
  // 实例属性
  bar = 2
  // 取值函数getter
  get baz() {
    return 3;
  }
}
```
上面组件的`state`只有一个属性`foo`，在实例化之后，这里出现异常，普通实例属性`bar`和取值函数`baz`都出现在`this.state`里面，甚至，如果组件里面使用了组件外面的普通变量，也会出现在`this.state`里面：
```js
this.state.bar; // 2
this.state.baz; // 3
this.state.qux; // 5
```
看似问题不大，但是会导致莫名其妙的bug，例如`state`里面出现与`this.bar`同名的属性`this.state.bar`，那么就会被`this.bar`覆盖。

**期望行为**

正常情况下，显而易见：
```js
this.state.bar; // undefined
this.state.baz; // undefined
this.state.qux; // undefined
```

**报错信息**

没有任何报错。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 v1.3.0
 - Node.js 版本 10.16.0
 - 报错平台 [h5, weapp]

**补充信息**

如果是转换机制导致必须这样做，也不应该使用同名属性，而是内部变量名例如`$$bar`等。

**Comment by lhzbxx** [comment]
+1

**Comment by Garfield550** [comment]
> 不要在 state 与 props 上用同名的字段，因为这些被字段在微信小程序中都会挂在 data 上。

Ref: https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6-state-%E4%B8%8E-props-%E9%87%8C%E5%AD%97%E6%AE%B5%E9%87%8D%E5%90%8D%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by kobezhu** [comment]
这哪里是props？是直接在实例上

**Comment by kobezhu** [comment]
> > 不要在 state 与 props 上用同名的字段，因为这些被字段在微信小程序中都会挂在 data 上。
> 
> Ref: https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6-state-%E4%B8%8E-props-%E9%87%8C%E5%AD%97%E6%AE%B5%E9%87%8D%E5%90%8D%E7%9A%84%E9%97%AE%E9%A2%98

这哪里是props啊？这是直接在实例上。

**Comment by luckyadam** [comment]
这些变量如果你在 JSX 里使用的话就会被合入 state，最终放入小程序的 data 里用来做模板渲染，暂时不要和 state 与 props 中变量重名
