### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by wujunze** [NervJS/taro#3708]
你好: 
项目依赖 ``` "react-native-image-zoom-viewer": "^2.2.13",```不存在  npm install 失败

相关 issue 请参考  https://github.com/ascoders/react-native-image-viewer/issues/320

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/60779610-f7a7fe80-a16d-11e9-8876-5b9e669bdb4c.png)

你好，这个版本存在的，而且 npm 在遇到 `^` 开头的版本标记时会自动安装 `2.2.x` 版本的包，这里会安装最新的 `2.2.26` 的。

请删除 `node_modules` 并 `npm cache clean --force` / `yarn cache clean --force` 之后再试一下。

Ref: https://www.npmjs.com/package/react-native-image-zoom-viewer/v/2.2.13

**Comment by wujunze** [comment]
你好:
       我清理的缓存 执行 ``` npm cache clean --force``` 命令  
       执行  ```npm install```  这个包依然找不到   你清理一下缓存  再安装试试  
![image](https://user-images.githubusercontent.com/12997869/60780627-d6491180-a171-11e9-9082-ef68b58f89c8.png)

**Comment by Garfield550** [comment]
https://registry.npmjs.org/react-native-image-zoom-viewer/-/react-native-image-zoom-viewer-2.2.26.tgz

我把你终端里的包地址抄出来了，你点一下看看能不能下载到这个包。

![image](https://user-images.githubusercontent.com/3471836/60780961-0c3ac580-a173-11e9-8954-855479dcb6fc.png)

**Comment by Garfield550** [comment]
你把 `yarn.lock` 或者 `package-lock.json` 文件也删除一下。 我看到你的地址里包名 `v` 是大写的 `react-native-image-zoom-Viewer`，可能你的 lockfile 有问题。

删掉之后再删一次 `node_modules`。

是在不行的话使用 Yarn 吧，它从自己的源下载包，不走 npmjs.org 。

**Comment by wujunze** [comment]
收到 谢谢 @Garfield550   

https://github.com/ascoders/react-native-image-viewer/releases   这个 Git 仓库的 tag 都是空的

**Comment by Garfield550** [comment]
@wujunze npmjs 发包不一定需要 Git Tag 的，而是根据 package.json 的 `"version": "1.0.0"` 来的。

**Comment by wujunze** [comment]
OK Thanks  @Garfield550
