### ISSUE TITLE
【H5 bug】点击浏览器返回，上一个页面没清除（升级至0.0.70才出现）

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#371]
**问题描述**
A、B两个页面，A跳转到B后，点击浏览器返回键，B页面的元素没有清除，出现了两个页面层叠在一起的bug。

**系统信息**

 - Taro 版本 [e.g. v.0.0.70]

**补充信息**
我查看了部署了服务器的0.0.60版本：
发现0.0.60中，页面元素清除得很到位，所以不会出现层叠bug。
而0.0.70中，返回时，页面元素清除估计有问题，没有清除干净。

所以我猜测可以从浏览器后退监听事件部分着手。

**Comment by luckyadam** [comment]
收到~谢谢详细反馈~
