### ISSUE TITLE
taro有这个吗？Taro.env.USER_DATA_PATH，想要把base64转成临时路径再保存到相册

### ISSUE THREAD

**Issue by WuMengYu** [NervJS/taro#3710]

**Comment by Garfield550** [comment]
你指的是 `wx.env.USER_DATA_PATH` 吗？可以先尝试在代码里调用一下，如果出错的话在这边反馈一下。

> 本地用户文件是从 1.7.0 版本开始新增的概念。我们提供了一个用户文件目录给开发者，开发者对这个目录有完全自由的读写权限。通过 wx.env.USER_DATA_PATH 可以获取到这个目录的路径。

Ref: https://developers.weixin.qq.com/minigame/dev/tutorial/ability/file-system.html#%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E6%96%87%E4%BB%B6

**Comment by luckyadam** [comment]
> 你指的是 `wx.env.USER_DATA_PATH` 吗？可以先尝试在代码里调用一下，如果出错的话在这边反馈一下。
> 
> > 本地用户文件是从 1.7.0 版本开始新增的概念。我们提供了一个用户文件目录给开发者，开发者对这个目录有完全自由的读写权限。通过 wx.env.USER_DATA_PATH 可以获取到这个目录的路径。
> 
> Ref: https://developers.weixin.qq.com/minigame/dev/tutorial/ability/file-system.html#%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E6%96%87%E4%BB%B6

学习了

**Comment by WuMengYu** [comment]
在taro项目里不能使用wx.env.USER_DATA_PATH,我试了Taro.env.USER_DATA_PATH也报错，不知道taro能不能获取文件目录

**Comment by WuMengYu** [comment]
> 你指的是 `wx.env.USER_DATA_PATH` 吗？可以先尝试在代码里调用一下，如果出错的话在这边反馈一下。
> 
> > 本地用户文件是从 1.7.0 版本开始新增的概念。我们提供了一个用户文件目录给开发者，开发者对这个目录有完全自由的读写权限。通过 wx.env.USER_DATA_PATH 可以获取到这个目录的路径。
> 
> Ref: https://developers.weixin.qq.com/minigame/dev/tutorial/ability/file-system.html#%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E6%96%87%E4%BB%B6

在taro项目里不能使用wx.env.USER_DATA_PATH,我试了Taro.env.USER_DATA_PATH也报错，不知道taro能不能获取文件目录

**Comment by Garfield550** [comment]
您好，我这边是可以的，Taro 1.3.5

![image](https://user-images.githubusercontent.com/3471836/60853336-32716b80-a22e-11e9-8f90-be563f782ffe.png)
![image](https://user-images.githubusercontent.com/3471836/60853338-39987980-a22e-11e9-8978-237bfc2f3b14.png)

**Comment by dpyzo0o** [comment]
@Garfield550 请问taro里可以加入这个实现吗, 目前还是只能用wx.env.USER_DATA_PATH来获取. `Taro.env` 无法获取到这个变量

**Comment by Garfield550** [comment]
@dpyzo0o 我确认了一下在 typings 里是有的，你可以尝试一下，但是没有搜索到相关的逻辑，可能需要找 @Chen-jj  确认一下。

定义在这里
https://github.com/NervJS/taro/blob/c283fd0af3ea161fb8877689365de17b3a7d4930/packages/taro/types/api/base/env.d.ts#L6-L9

**Comment by dpyzo0o** [comment]
@Garfield550 typings 是有，但是 Taro 下访问不到这个变量 `Taro.env` `Taro.envObj` 都不行
<img width="705" alt="Screen Shot 2020-01-08 at 13 37 20" src="https://user-images.githubusercontent.com/24768249/71953089-099d5380-321c-11ea-88ba-f5a2bfefe201.png">

**Comment by Garfield550** [comment]
了解了，我去问一下。

**Comment by Garfield550** [comment]
应该下个版本就能使用 `Taro.env` 调用了。
![image](https://user-images.githubusercontent.com/3471836/71955869-7ae10480-3224-11ea-843e-bbebaea97aa0.png)
![image](https://user-images.githubusercontent.com/3471836/71955900-8f250180-3224-11ea-83b6-444291bc46bb.png)

**Comment by Darcrandex** [comment]
版本: 3.0.7
框架: react

我在定义文件中找到了
```
declare namespace Taro {
  /**
   * @supported weapp
   * @see https://developers.weixin.qq.com/miniprogram/dev/api/base/env/envObj.html
   */
  abstract class env {
    /** 文件系统中的用户目录路径 (本地路径) */
    static USER_DATA_PATH: string
  }
}
```
但是打印出来的是'Taro.env undefined'

```
componentDidMount() {
    console.log("Taro.env", Taro.env);
  }
```

怎么办???

**Comment by shanlh** [comment]
+1，这个问题好像又复现了

**Comment by ILoveChy** [comment]
+1,正好最近要用

**Comment by Chen-jj** [comment]
@Darcrandex @shanlh @ILoveChy 新开一个 issue 吧
