### ISSUE TITLE
Taro 1.3  已支持QQ小程序了吗，是否对文档更新？

### ISSUE THREAD

**Issue by tianlu1677** [NervJS/taro#3713]
Taro 1.3 已支持QQ小程序了论坛里说已支持，但是文档中还未有相应的描述

**Comment by Chen-jj** [comment]
@tianlu1677 已支持，用法和微信小程序一致。文档还没能有时间同步，欢迎 PR。

**Comment by teddyzhang29** [comment]
使用云开发后 转成非微信小程序(比方说qq小程序), 同样也能使用云开发功能吗?

**Comment by Chen-jj** [comment]
@teddyzhang29 微信和qq应该可以，其他应该不行，可以试试
