### ISSUE TITLE
应该如何学习呢？

### ISSUE THREAD

**Issue by fansangg** [NervJS/taro#3719]
没有前端经验，会一些js，昨天开始看这个框架，《Taro 多端开发实现原理与项目实战》看到redux这一步有一点看不懂了，所以对于我这类人应该怎么开始学习呢？先react，然后再过一遍redux？然后css啥的是不是也得过一遍？

**Comment by Garfield550** [comment]
您好，如果开发微信小程序的话，学习路线建议先了解一下 ES2017（JS），CSS（SASS/LESS），然后阅览一遍微信小程序文档，熟悉一下 API、组件和生命周期，然后再学习 React，建议从 React 16 版本以上的语法开始，熟悉一下生命周期，Redux/Mobx 之类的可以看情况使用，不一定要在每个项目里使用，用 React 的原生 `setState()` 也可以解决大部分问题。

个人见解，不代表官方建议。
