### ISSUE TITLE
组件内部使用createselectorquery一直没找到节点

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#3722]
我在组件内部使用这个 API
```jsx
    let tabHeight = 0;
    const query = Taro.createSelectorQuery().in(this)
    for (let i = 0; i < tabs.length; i++) {
      let view = query.select('#'+ tabs[i].id);
      view.fields({
        size: true
      }, (data: any) => {
        tabs[i].top = tabHeight;
        tabHeight = tabHeight + data.height;
        tabs[i].bottom = tabHeight;
      }).exec();
    }
```

结果一直报错没找到
![image](https://user-images.githubusercontent.com/24502330/60856427-c432a600-a239-11e9-8923-8ebfec940626.png)

组件内是有这个的 id 的
![image](https://user-images.githubusercontent.com/24502330/60856495-f3491780-a239-11e9-98f6-d2290d701116.png)

**Comment by Chen-jj** [comment]
@yinLiangDream https://nervjs.github.io/taro/docs/apis/interface/wxml/selectorQuery_in.html#docsNav
