### ISSUE TITLE
ScrollIntoView 对于 slot 的元素无效

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#3728]
组件内部
```jsx
      <ScrollView scrollY scrollWithAnimation style={{height: pxTransform(props.height)}} scrollIntoView={scrollId} onScroll={onScroll}>
        {this.props.children}
      </ScrollView>
```

外部使用
```jsx
<ClVerticalTab tabs={tabs} height={600}>
          {tabs.map((item) => (
        <View id={item.id} key={item.name}>
          <ClVerticalTabCell name={item.name}>{item.name}</ClVerticalTabCell
        </View>
          ))}
</ClVerticalTab>
```
![image](https://user-images.githubusercontent.com/24502330/60863663-036df080-a254-11e9-9901-cc9a12f3193b.png)
![image](https://user-images.githubusercontent.com/24502330/60863673-0963d180-a254-11e9-9811-ac605e35d488.png)

结果并不跳指定id，如果直接将 children 的内容写在组件内部是好的

**Comment by yuche** [comment]
如果不是 ScrollView 就可以吗

**Comment by yinLiangDream** [comment]
> 如果不是 ScrollView 就可以吗

不是，我的意思是不使用 children，直接将 tabs 内容写在组件内部是能够跳转的，用了 children 渲染出来一模一样，但是不能跳转了
这么写是能够跳转的
![image](https://user-images.githubusercontent.com/24502330/60864421-27323600-a256-11e9-9bed-243c2dad4b9a.png)
![image](https://user-images.githubusercontent.com/24502330/60864467-492bb880-a256-11e9-9f7d-2663c155b529.png)
![image](https://user-images.githubusercontent.com/24502330/60864475-4e890300-a256-11e9-9c9a-349f10cc65e3.png)

**Comment by luckyadam** [comment]
看上去应该是小程序自己问题，你可以用原生写法使用 slot，看看能否跳转定位

**Comment by yinLiangDream** [comment]
@luckyadam 我去官方小程序社区问了，确实是小程序自身的问题，不过这个问题我已经解决了，自己实现了一下跳转的功能

**Comment by Fancy-X** [comment]
> @luckyadam 我去官方小程序社区问了，确实是小程序自身的问题，不过这个问题我已经解决了，自己实现了一下跳转的功能

你好，我也遇到同样的问题，请问你是怎么解决的呢
