### ISSUE TITLE
在render方法中引用组件本身的方法时，编译出来的代码会在方法前面加上render

### ISSUE THREAD

**Issue by moonreplace** [NervJS/taro#3731]
**问题描述**
在H5编译环境中，如果在render方法中引用了类本身的方法，会在编译出来的代码自动加上render前缀，而原来的方法并没有加上render前缀
1.3.2没有问题，在1.3.5和1.3.6中能稳定复现

**复现步骤**
```js

// 这里可以贴代码
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
class Demo extends Component {
    getAppDesc() {
        return (
            <Text>Demo</Text>
        );
    }
    render() {
         const desc = this.getAppDesc()；
         return (
             <View>{desc}</View>
         );
    }
}
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**报错信息**
![屏幕快照 2019-07-09 15 46 48](https://user-images.githubusercontent.com/1296019/60869097-eab80780-a260-11e9-9340-57283facb0b1.png)
![屏幕快照 2019-07-09 15 46 37](https://user-images.githubusercontent.com/1296019/60869199-1935e280-a261-11e9-9da7-284ae9bb69fa.png)
![屏幕快照 2019-07-09 15 50 39](https://user-images.githubusercontent.com/1296019/60869333-5d28e780-a261-11e9-9883-789b1563c875.png)

**系统信息**

 - 操作系统: [e.g. Mac, Linux]
 - Taro 版本 [e.g. v.1.3.5, v1.3.6]
 - Node.js 版本 [e.g. v10.0.0]
 - 报错平台 [h5]

**Comment by Garfield550** [comment]
如果写成 `renderAppDesc()` 呢？

**Comment by moonreplace** [comment]
> 如果写成 `renderAppDesc()` 呢？

这样是可以的

**Comment by Garfield550** [comment]
> > 如果写成 `renderAppDesc()` 呢？
> 
> 这样是可以的

那就临时这样写吧... 2333
可能是被这个逻辑影响了吧。
![image](https://user-images.githubusercontent.com/3471836/60876065-b9920400-a26d-11e9-9e0d-6d88d5673569.png)
