### ISSUE TITLE
componentDidNotFound 没有监听到

### ISSUE THREAD

**Issue by listar** [NervJS/taro#3732]
app.js 写入
`
  componentDidNotFound(res){
    console.log('onPageNotFound', res);
  }`

使用 
`Taro.navigateTo({
      url: “url”
    });`

监听不到

并且这个报错
![image](https://user-images.githubusercontent.com/1744030/60870733-fd800b80-a263-11e9-855f-573a33bd7aac.png)

componentDidCatchError 监听不到

**Comment by Garfield550** [comment]
微信小程序的 App.js 也没有 `onPageNotFound` 生命周期，在 `onError` 周期里也无法捕获 `wx.navigateTo` 的错误。

![image](https://user-images.githubusercontent.com/3471836/60877228-ffe86280-a26f-11e9-93ef-aff4ffeccfd5.png)

Ref: https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/app.html

**Comment by Garfield550** [comment]
刚才的回复有问题，已经删除了。

微信小程序的 App 生命周期有 `onPageNotFound(Object object)`，但是我的测试是 `wx.navigateTo` 到不存在的页面时捕捉不到错误。

![image](https://user-images.githubusercontent.com/3471836/60879099-8eaaae80-a273-11e9-9ccf-0b0a266e7301.png)

**Comment by Garfield550** [comment]
使用自定义编译模式跳转的页面是可以在 App 生命周期里抓到错误的，也许你可以试一下 Taro 是否支持这种方式，`wx.navigateTo` 有 `fail` 回调，建议 navigate 相关的路由逻辑在这里处理。

![image](https://user-images.githubusercontent.com/3471836/60879548-653e5280-a274-11e9-9596-f2cc38534db8.png)

**Comment by listar** [comment]
> 使用自定义编译模式跳转的页面是可以在 App 生命周期里抓到错误的，也许你可以试一下 Taro 是否支持这种方式，`wx.navigateTo` 有 `fail` 回调，建议 navigate 相关的路由逻辑在这里处理。
> 
> ![image](https://user-images.githubusercontent.com/3471836/60879548-653e5280-a274-11e9-9596-f2cc38534db8.png)

谢谢！ 因为老的项目跳转路径，有很多后端返回的路径， 改版里面路径全换了，想一劳永逸！
想一步搞定是我想多了
