### ISSUE TITLE
ES6组件传属性这种写法{...this.props}转小程序报错

### ISSUE THREAD

**Issue by yanchengqu** [NervJS/taro#3734]
![image](https://user-images.githubusercontent.com/7960007/60872063-9879e500-a266-11e9-8d98-793f256bc074.png)

**Comment by yuche** [comment]
报什么错，哪个版本

**Comment by luckyadam** [comment]
提供一下文字的代码示例吧

**Comment by zsirfs** [comment]
@luckyadam 大佬。我记得Taro的规则似乎不支持**扩展运算符**的不定属性吧。现在支持了吗？

**Comment by Chen-jj** [comment]
已支持
