### ISSUE TITLE
编译成H5字体单位没有转换

### ISSUE THREAD

**Issue by Huatingzi** [NervJS/taro#3737]
**问题描述**
转换成小程序没有问题，但是转换成H5字体单位没有转
![image](https://user-images.githubusercontent.com/20843521/60875089-c9104d80-a26b-11e9-983c-3e2eafe79874.png)

**期望行为**
期望单位可以正常转换

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac
 - Taro 版本 1.3.1
 - Node.js 版本 8.9.9
 - 报错平台 h5

**Comment by Garfield550** [comment]
Taro 和依赖先升级到 1.3.6 版本再试一下呢？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/size.html
请阅读一下这个文档
