### ISSUE TITLE
h5的swiper组件绑定current时候，当我点击current为0的按钮时候swiper不切换，其他就可以

### ISSUE THREAD

**Issue by LiJiaPeng001** [NervJS/taro#3739]
如题所示，h5上的swiper组件，想点击按钮切换swiper，绑定了current，但是在点击current为0的按钮时候，页面并无切换效果，但是切换其他下标的时候就会进行切换

**Comment by jinjinjin0731** [comment]
更新到最新版本吧。 问题已经修复

**Comment by ghyzx** [comment]
当前最新的1.3.9 仍然存在这个问题 @jinjinjin0731

**Comment by ghyzx** [comment]
1.3.11 还是有问题

**Comment by ghyzx** [comment]
1.3.11 还是有问题 @jinjinjin0731

**Comment by ghyzx** [comment]
1.3.11下，current到0时，还是有问题  @jinjinjin0731

**Comment by isxiaoxin** [comment]
> 1.3.11下，current到0时，还是有问题 @jinjinjin0731

哈喽，我也遇到了这个问题。你可以试下，把 "0" 改为 "-1" 就可以往前切换了
