### ISSUE TITLE
1.2.15版本taroStyle使用style-loader插入taro的样式首屏问题

### ISSUE THREAD

**Issue by guojun6** [NervJS/taro#3740]
**问题描述**
在tarojs/webpack-runner/dist/util/chain.js>getModule方法里，发现taroStyle用style-loader，customStyle用MiniCssExtractPlugin提取。导致在业务中预加载界面时图片已经加载完成但是taroStyle还未插入，表现现象为图片显示不正常(超大)一瞬间(直到taroStyle插入到文档中)。翻看1.2.8版本，并没有对taroStyle和customStyle做区分，请问做此区分的收益是什么。

**复现步骤**
tarojs/webpack-runner/dist/util/chain.js代码位置
![image](https://user-images.githubusercontent.com/22863128/60886033-822e5200-a283-11e9-9891-8ab18ab9a350.png)

![image](https://user-images.githubusercontent.com/22863128/60885985-675bdd80-a283-11e9-9d95-6ced3958b05e.png)

**期望行为**
taroStyle恢复使用MiniCssExtractPlugin

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: MacOS
 - Taro 版本 [e.g. v1.2.15]
 - Node.js 版本 [v10.13.0]
 - 报错平台 [h5]

**Comment by Chen-jj** [comment]
可以升级到 Taro 2 或 3 再试试
