### ISSUE TITLE
taro版本是1.3.6,在父组件里面通过ref不能调用子组件里面的方法

### ISSUE THREAD

**Issue by wangjingwj** [NervJS/taro#3744]
子组件里面有个pay方法没有暴露出来，页面调用到<PaymentCell
                wechatPayCancelBack={false}
                preDeposit={(this.productType == 'PreDeposit' || confirmOrderObj.ActualPrice > confirmOrderObj.PreDeposit) ? false : true}
                orderNo={dealcode}
                totalPrice={confirmOrderObj.ActualPrice}
                ref={(node) => (this.refCellList = node)}
                onComplete={this.closePay}
                onClose={this.closePay}
                onError={this.closePay}
              />

通过this.refCellList.pay()来调用，页面报错，
![image](https://user-images.githubusercontent.com/13778018/60935577-e6d9c300-a2fc-11e9-8ca7-8b8acd437ae1.png)
这样的写法在1.2.26里面是没有问题的，可以正常使用

**Comment by wangjingwj** [comment]
父组件里面的jsx
<View className={`${styles['confirm-order-area']} ${styles['pay-area']}`}>
              <PaymentCell
                wechatPayCancelBack={false}
                preDeposit={(this.productType == 'PreDeposit' || confirmOrderObj.ActualPrice > confirmOrderObj.PreDeposit) ? false : true}
                orderNo={dealcode}
                totalPrice={confirmOrderObj.ActualPrice}
                ref={(node) => (this.refCellList = node)}
                onComplete={this.closePay}
                onClose={this.closePay}
                onError={this.closePay}
              />
            </View>

父组件调用
confirmOrder = (formData) => {
    console.log(formData);
    const paramObj = {
      Goods:[
        {
          ID:formData.ID,          //商品ID
          Amount:formData.Amount,  //数量
          Price:formData.Price,    //单价
          MarketPrice:formData.MarketPrice,  //市场价
          Name:formData.Name                 //商品名称
        }
      ],
      CouponNumber:formData.CouponNumber,  //优惠券
      TotalMoney:formData.ActualPrice       //支付金额--实付款
    };
    MemberOrder.pay(paramObj).then(data => {
      if(data && data.OrderNo) {
        this.setState({
          dealcode:data.OrderNo,
        },() => {
          console.log('this-this',this,this.refCellList);
          this.refCellList.pay();
        });
      }else{
        this.closePay();
      }
    },() => {
      this.closePay();
    }).catch(() => {
      this.closePay();
    });
  }

**Comment by wangjingwj** [comment]
子组件PaymentCell里面的pay方法
pay(password) {
    const {
      current
    } = this.state;
    if (current === PAYMENT_ENUM.Wechat) {
      this.createPayOrder();
      return;
    }

    if (password) {
      this.confirm(password);
    } else {
      this.setState({
        inputModalOpend: true
      });
    }
  }

**Comment by wangjingwj** [comment]
demo调用的例子

import Taro, { Component } from '@tarojs/taro';

      import { PaymentCell } from '@/components';

      class Demo extends Component {

        refCellList = null;

        state = {
          orderNo: 'abcd',
          totalPrice: 10
        }

        handlePay() {
          this.refCellList.pay();
        }

        render () {
          const {
            orderNo,
            totalPrice
          } = this.state;

          return (
            <CellList
              ref={(node) => (this.refCellList = node)}
              orderNo={orderNo}
              totalPrice={totalPrice}
              onChange={this.handleCheck.bind(this)}
              onComplete={this.handleComplete.bind(this)}
            />
          );
        }
      }

      export default Demo;

**Comment by wangjingwj** [comment]
参数名称|说明|
-------|---|
orderNo | 订单号 |
price | 支付金额 |
payNo | 支付单号 |
payment | 支付方式 |


- ### redirectBtnOpt
属性名称|说明|
-------|---|
btnLabel | 按钮名称 |
btnPath | 按钮跳转路径 |



- ### 事件
名称|说明|
---|---|
onComplete | 支付完成 |
onChange | 支付方式变化 |
onError | 错误 |

- ### 方法
名称|说明|
---|---|
pay | 支付方法 |

**Comment by ZakaryCode** [comment]
fixed
