### ISSUE TITLE
map嵌套循环下Array.isArray编译后对象不存在

### ISSUE THREAD

**Issue by YunGouOS** [NervJS/taro#3745]
**问题描述**
问题描述：数组多层嵌套循环渲染下Array.isArray后 数据遍历的对象提示不存在

**复现步骤**
1、创一个基本的嵌套数组
2、render中使用map循环该数组拿到嵌套的数组
3、嵌套的数组使用Array.isArray 判断下
4.、编译后页面提示不存在

```
const orderList={
	"StoreName": "测试",
	"GoodsList": [{
		"GoodsName": "核销测试",
		"Image": "xxxxxxx",
		"Price": 100.00,
		"Count": 1
	}],
	"Id": "2862",
	"CreateTime": "2019/06/04 18:25:05",
	"StatusText": "状态1"
}
 render() {
        return (
            <View>
                 {Array.isArray(orderList) && orderList.length > 0 ? (
                       orderList.map((item,index) => {
                           return (
                               <View className="store-order-list-content common-margin-top-20">
                                        {Array.isArray(item.GoodsList) && item.GoodsList.length > 0 ? (
                                           
                                        ) : ''}
                              </View>
                          )
                  })
              ) : ''}
         </View>
        )
}

```

**期望行为**
加上Array.isArray判断后item应该是存在的

**报错信息**
ReferenceError: item is not defined

**系统信息**
Taro v1.3.6

  Taro CLI 1.3.6 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      Node: 10.15.3 - D:\nodejs\node.EXE
      npm: 6.4.1 - D:\nodejs\npm.CMD

**补充信息**

[根据你的调查研究，出现这个问题的原因可能在哪里？]

编译后的代码先执行了两次Array.isArray

 var anonymousState__temp5 = Array.isArray(this.__props.orderList) && this.__props.orderList.length > 0;
      var anonymousState__temp6 = Array.isArray(item.$original.GoodsList) && item.$original.GoodsList.length > 0;
      var loopArray20 = Array.isArray(this.__props.orderList) && this.__props.orderList.length > 0 ? this.__props.orderList.map(function (item, index) {
        item = {
          $original: (0, _index.internal_get_original)(item)
        };

**Comment by yuche** [comment]
你的代码崩了

**Comment by YunGouOS** [comment]
> 你的代码崩了

不好意思 修改过了

**Comment by yuche** [comment]
```
      {Array.isArray(item.GoodsList) && item.GoodsList.length > 0 ? (
                                           
                                        ) : ''}
                            </View>
```
这里中间是什么？

目前提供的这个代码没办法复现

**Comment by YunGouOS** [comment]
> ```
>       {Array.isArray(item.GoodsList) && item.GoodsList.length > 0 ? (
>                                            
>                                         ) : ''}
>                             </View>
> ```
> 
> 这里中间是什么？
> 
> 目前提供的这个代码没办法复现

啥也没有 就是渲染  这一句的时候 Array.isArray(item.GoodsList) 就已经出错了， 我目前解决方案是不用Array.isArray() 就可以了

**Comment by yuche** [comment]
还是不能复现，你可以试一下更新到 1.3.7

**Comment by HanleyCN** [comment]
@yuche 这个问题还是存在, 复现代码:
```
const data = [
  {
    id: 1,
    list: [
      {id: 1},
      {id: 2}
    ]
  },
  {
    id: 2,
    list: [
      {id: 3},
      {id: 4}
    ]
  }
]

return (
      <View className='container'>
        {
          Array.isArray(data) && data.map(item => {
              return (
                <View key={item.id}>{
                  Array.isArray(item.list) && item.list.map(son => {
                    return (<View key={son.id}>{son.id}</View>)
                  })
                }</View>
              )
            }
          )
        }
      </View>
    )
```
