### ISSUE TITLE
【H5 bug】componentDidShow钩子无效

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#375]
**问题描述**
在小程序中使用正常，但在h5中发现componentDidShow钩子却没有触发。

[或者可以直接贴源代码，能贴文字就不要截图]

```js
componentDidShow() {
   console.log('in show') //没有输出
}

```

**系统信息**

 - Taro 版本 [e.g. v.0.0.72]

**Comment by luckyadam** [comment]
@Littly 看看哦

**Comment by Littly** [comment]
app.js里面的componentDidShow/componentDidHide被漏掉了 后续版本会补上
另外 h5版本检测不到前台后台的切换状态 所以仅仅是在didMount之后和willUnmount之前触发这两个状态而已喔

**Comment by Littly** [comment]
fix via  e8376cf

**Comment by luckyadam** [comment]
可以升级到 `1.0.0-beta.7` 尝试哦~
#389
