### ISSUE TITLE
QuickApp: 自动生成的manifest.json中文件的filter字段触发平台错误，导致页面跳转失败。

### ISSUE THREAD

**Issue by kongzhe607** [NervJS/taro#3750]
测试环境：1050版本模拟器
测试机型：红米4，OPPO R9S，华为Nova

[haptest2.zip](https://github.com/NervJS/taro/files/3376211/haptest2.zip)

建议删除自动生成代码中的filter配置。

**Comment by kongzhe607** [comment]
"pages": {
      "pages/index": {
        "component": "index",
        "filter": {
          "view": {
            "uri": "https?://.*"
          }
        }
      }
    }

**Comment by luckyadam** [comment]
已经没有自动生成，需要时可以自己配置
