### ISSUE TITLE
Taro v1.3.7 使用了Taro.memo 的hooks组件路径错误

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#3751]
**问题描述**
组件错误  组件HomeBanner路径错误，请检查！（可能原因是导出的组件名不正确）

心塞！！！
**复现步骤**

```js
import Taro from '@tarojs/taro'
import { View, Swiper, SwiperItem, Image } from '@tarojs/components'
import './index.scss'

type Props = {
  bannerList: any[]
}

const HomeBanner = ({ bannerList }: Props) => {
  return (
    <Swiper
      className='home-banner'
      autoplay
      circular
      indicatorDots={bannerList.length > 1 ? true : false}
      indicatorColor='rgba(255,255,255,.64)'
      indicatorActiveColor='#fff'
    >
      {bannerList.map(item => (
        <SwiperItem key={item}>
          <View className='home-banner__item'>
            <Image className='home-banner__item__cover' src='' />
          </View>
        </SwiperItem>
      ))}
    </Swiper>
  )
}

HomeBanner.defaultProps = {
  bannerList: []
}

export default Taro.memo(HomeBanner)


```

**Comment by loveonelong** [comment]
貌似去掉Taro.memo仍然报组件导出路径问题

**Comment by loveonelong** [comment]
我这可怜的项目是上不了线了，嘤嘤嘤

**Comment by yuche** [comment]
之前的版本可以吗

**Comment by loveonelong** [comment]
1.3.5的时候是正常的

**Comment by loveonelong** [comment]
错误  组件错误  组件HomeBanner路径错误，请检查！（可能原因是导出的组件名不正确）
编译  组件文件  src/components/HomeFreeAudioList/index.tsx

**Comment by loveonelong** [comment]
错误  页面编译  页面/Users/onelong/work/ilisten-taro-pack/src/pages/index/index编译失败！
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object
    at validateString (internal/validators.js:107:11)
    at Object.relative (path.js:1052:5)
    at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:179:84
    at Array.forEach (<anonymous>)
    at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:170:47
    at Array.forEach (<anonymous>)
    at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:169:54
    at Array.forEach (<anonymous>)
    at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:166:40
    at Generator.next (<anonymous>)

**Comment by gy18505** [comment]
我也遇到同样的问题！路径和代码都没有问题。

**Comment by gy18505** [comment]
> 错误 页面编译 页面/Users/onelong/work/ilisten-taro-pack/src/pages/index/index编译失败！
> TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object
> at validateString (internal/validators.js:107:11)
> at Object.relative (path.js:1052:5)
> at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:179:84 at Array.forEach () at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:170:47
> at Array.forEach ()
> at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:169:54 at Array.forEach () at /Users/onelong/work/ilisten-taro-pack/node_modules/_@tarojs_cli@1.3.7@@tarojs/cli/dist/mini/page.js:166:40
> at Generator.next ()

这个问题也出现了，请问你的解决了吗？

**Comment by gy18505** [comment]
> 我也遇到同样的问题！路径和代码都没有问题。

OS: MacOS version 10.13.6
taro: 1.3.10
editor: VS Code

**Comment by loveonelong** [comment]
@gy18505 你能大概贴一下导出的代码么，我看看
