### ISSUE TITLE
H5模式下页面后退到当前页面，页面componentDidShow没有触发

### ISSUE THREAD

**Issue by Riskel** [NervJS/taro#3754]
H5模式下页面后退到当前页面，页面componentDidShow没有触发，因为一些状态已经用redux修改了，需要返回的时候触发一下事件重新渲染

**复现步骤**
[复现问题的步骤]
1. 触发页面中路由的跳转navigateTo
2. 浏览器返回
3. componentDidShow ()没有触发

componentDidShow () {
    console.log(22222)
    this.setState()
  }

Taro 版本 [v.1.3.4]

**Comment by Littly** [comment]
这个“当前页面”，是个高阶组件吗？

**Comment by Riskel** [comment]
> 这个“当前页面”，是个高阶组件吗？
我这边好像是被引用的组件，有个父组件

**Comment by Riskel** [comment]
> 这个“当前页面”，是个高阶组件吗？

已经调试完成了，看起来就是因为这个组件是子组件，现在在父组件上用ref向下调用子组件的componentDidShow（）方法就能解决问题了。谢谢大佬
