### ISSUE TITLE
1.3.7 微信小程序报错：Uncaught TypeError: taro.Link is not a constructor

### ISSUE THREAD

**Issue by jisong-zhu** [NervJS/taro#3755]
**问题描述**
升级到taro 1.3.7版本，编译微信小程序版本，在微信开发者工具打开编译后的代码，报错：
WAService.js:1 Uncaught TypeError: taro.Link is not a constructor
  

**复现步骤**
升级到1.3.7，依赖包和tarojs/cli都是1.3.7

**期望行为**
正确运行

**报错信息**
![image](https://user-images.githubusercontent.com/3304349/60957414-2fae6d80-a337-11e9-8a6e-1db70898ad83.png)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v
 - Node.js 版本 8.11.3
 - 报错平台 weapp

**补充信息**
原因排查，在编译后的目录中，npm文件加下，缺少了@tarojs/taro相关文件
![image](https://user-images.githubusercontent.com/3304349/60957606-82882500-a337-11e9-8e4e-77182fe23dc4.png)

**Comment by ZhongMingKun** [comment]
升级cli到1.3.8，再重新装一下依赖试试，我昨天也是升级后没法用了

**Comment by laozijiaojiangnan** [comment]
export {object} 是不是没加这一步导出模型
