### ISSUE TITLE
Taro v1.3.8 hooks组件作为page时，报错：未找到 Taro.Component 的类定义

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#3760]
**报错信息**

```
错误  页面编译  页面/Users/onelong/work/ilisten-taro-pack/src/pages/playing/index编译失败！
Error: 未找到 Taro.Component 的类定义
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/_@tarojs_transformer-wx@1.3.8@@tarojs/transformer-wx/lib/src/index.js:623:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:87:37)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:3:12)
    at Object.buildSinglePage (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:25:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/dist/mini/watch.js:67:34)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/watch.js:7:71
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Mac
 - Taro 版本 v1.3.8
 - Node.js 版本 v12
 - 报错平台 weapp

**Comment by luckyadam** [comment]
确实有问题，暂时不要用函数式组件来写页面吧

**Comment by loveonelong** [comment]
不行哦。因为需要多个context。不用函数式组件做不到鸭





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by loveonelong** [comment]
1.3.5的时候还正常的喔





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by nanjingboy** [comment]
@luckyadam 这个在 <= 1.3.7 之前都是 OK 的

**Comment by wanghui47** [comment]
@luckyadam 您好，看到您说 “确实有问题，暂时不要用函数式组件来写页面吧”； 但是我这个 3767 是全部官方默认的，没有写新的组件，也出现这个问题，是因为官方的 mobx 模板里面有使用函数式组件吗？

**Comment by nanjingboy** [comment]
@wanghui47 这个在  <= 1.3.6 之前是 OK 的，需要 @luckyadam 检查下 1.3.7 改了什么导致这个问题

**Comment by wanghui47** [comment]
@nanjingboy 好的，谢谢您。

**Comment by hqman** [comment]
@yuche  我想用master代码 自己编一个 taro-transformer-wx 替换全局安装taro-cli的代码
但是遇到一个问题？
运行 build (tsc) 出现一大推error,该如何解决？
```
src/functional.ts:27:58 - error TS2345: Argument of type 'babel.types.LVal[]' is not assignable to parameter of type 'import("/Users/xxx/project/plays/taro/
```

**Comment by yuche** [comment]
@hqman 因为你安装依赖没有按 package.json.lock 来装

**Comment by hqman** [comment]
多谢 我再试试

**Comment by czhhgghm** [comment]
好想知道这个问题最后怎么解决呢

**Comment by alenfaker** [comment]
遇到同样的问题，
页面pages中使用函数组件，结合
import { observer, inject } from '@tarojs/mobx'
const Home = inject('categoryStore')(observer((props) => {
  console.log(this)
  useEffect(() => {
    console.log(props)
  }, [props])
  return (
    <View>
      <NavSearchBar />
      <TopBanner />
      <TopNavList />
      <Seckill />
      <FloorGrid />
      <FloorGrid />
      <ScrollNews />
      <RecommendList />
    </View>
  )
}))

Error: 未找到 Taro.Component 的类定义

mobx官方demo：
const colors = observable({
   foreground: '#000',
   background: '#fff'
});

const App = () =>
  <Provider colors={colors}>
     <app stuff... />
  </Provider>;

const Button = inject("colors")(observer(({ colors, label, onClick }) =>
  <button style={{
      color: colors.foreground,
      backgroundColor: colors.background
    }}
    onClick={onClick}
  >{label}</button>
));

// 稍后..
colors.foreground = 'blue';
// 所有button都会更新

**Comment by zicong-zhang** [comment]
我也想知道怎么解决， export default memo(AAA); 这种写法会导致 TS 不会检测自动导入

**Comment by langxiaohui123** [comment]
Error: 未找到 Taro.Component 的类定义
    at transform (/usr/local/lib/node_modules/@tarojs/cli/node_modules/@tarojs/transformer-wx/lib/src/index.js:623:15)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/page.js:87:37
    请问你们怎么解决的？
