### ISSUE TITLE
1.3.7 创建 mobx 模板编译时报错：Error: 未找到 Taro.Component 的类定义

### ISSUE THREAD

**Issue by wanghui47** [NervJS/taro#3767]
**问题描述**
使用 Taro 创建 mobx 模板，创建成功，但是编译时候报错：Error: 未找到 Taro.Component 的类定义

**复现步骤**
1. Go to 'CMD'
2. cd your folder
3. type 'taro init myApp'
4. use the settings:
![image](https://user-images.githubusercontent.com/33652729/61014888-24e9ec00-a3bc-11e9-9091-17143fcb335f.png)

5. cd myApp
6. type 'npm run dev:weapp'
7. you will see the error:
![image](https://user-images.githubusercontent.com/33652729/61014975-7e521b00-a3bc-11e9-9a6b-c213b6125a08.png)

**期望行为**
所有代码均为默认创建，期待正常编译成功。

**报错信息**
Error: 未找到 Taro.Component 的类定义

![image](https://user-images.githubusercontent.com/33652729/61015006-9b86e980-a3bc-11e9-8ce0-bab2f0cdbda5.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.3.7]
 - Node.js 版本 [v10.16.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
Duplicate of #3760
