### ISSUE TITLE
videoContext.play()方法缺少 succes 等回调参数

### ISSUE THREAD

**Issue by gitivon** [NervJS/taro#3770]
**问题描述**
根据微信小程序文档 [https://developers.weixin.qq.com/miniprogram/dev/api/media/live/LivePlayerContext.play.html](https://developers.weixin.qq.com/miniprogram/dev/api/media/live/LivePlayerContext.play.html)

应当支持传入一个object，包括了 success, fail和complete回调

**复现步骤**
api缺失

**期望行为**
支持api

**Comment by Garfield550** [comment]
您好，请问是 TypeScript 提示错误还是 API 运行时不支持传入参数？

有详细的报错信息和复现代码可以提供下吗？

**Comment by gitivon** [comment]
> 您好，请问是 TypeScript 提示错误还是 API 运行时不支持传入参数？
> 
> 有详细的报错信息和复现代码可以提供下吗？

![image](https://user-images.githubusercontent.com/3938359/61027592-267dd900-a3e9-11e9-87f9-543bf9a3dec6.png)

`index.d.ts: 3111`

运行时暂不得知，至少TS目前的类型不对

**Comment by gitivon** [comment]
低级失误，看错 api 了抱歉
