### ISSUE TITLE
RichText组件，渲染富文本的问题

### ISSUE THREAD

**Issue by 1391020381** [NervJS/taro#3771]
1. RichText组件，问题说支持html string。但是使用后发现不能显示内容。
2. 在[希望支持富文本 ](https://github.com/NervJS/taro/issues/128)，看到 支持 wxParse https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js
3. 我的问题是，在支付宝端要展示富文本需要怎么做？ 支付宝文档（https://docs.alipay.com/mini/component/rich-text） 提到的  [mini-html-parser](https://github.com/ant-mini-program/mini-html-parser)  依然编译就报错。

**Comment by 1391020381** [comment]
使用支付宝的  报如下错误 https://github.com/ant-mini-program/mini-html-parser/issues/1

**Comment by liran319** [comment]
我这边也是传入的nodes值为html字符串，但是确实也是没有渲染出来

**Comment by hao-li** [comment]
```
yarn build:alipay
```

```
(node:31409) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'events'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:267:30
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:266:12)
    at resolveNpmFilesPath (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:55:9)
    at analyzeImportUrl (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:87:29)
(node:31409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31409) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
👽 Taro v1.3.15


  Taro CLI 1.3.15 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.15 => 1.3.15
      @tarojs/components-qa: 1.3.15 => 1.3.15
      @tarojs/plugin-babel: 1.3.15 => 1.3.15
      @tarojs/plugin-csso: 1.3.15 => 1.3.15
      @tarojs/plugin-sass: 1.3.15 => 1.3.15
      @tarojs/plugin-uglifyjs: 1.3.15 => 1.3.15
      @tarojs/router: 1.3.15 => 1.3.15
      @tarojs/taro: 1.3.15 => 1.3.15
      @tarojs/taro-alipay: 1.3.15 => 1.3.15
      @tarojs/taro-h5: 1.3.15 => 1.3.15
      @tarojs/taro-qq: 1.3.15 => 1.3.15
      @tarojs/taro-quickapp: 1.3.15 => 1.3.15
      @tarojs/taro-swan: 1.3.15 => 1.3.15
      @tarojs/taro-tt: 1.3.15 => 1.3.15
      @tarojs/taro-weapp: 1.3.15 => 1.3.15
      @tarojs/webpack-runner: 1.3.15 => 1.3.15
      eslint-config-taro: 1.3.15 => 1.3.15
      eslint-plugin-taro: 1.3.15 => 1.3.15
      nerv-devtools: ^1.4.4 => 1.4.4
      nervjs: ^1.4.4 => 1.4.4
      stylelint-config-taro-rn: 1.3.15 => 1.3.15
      stylelint-taro-rn: 1.3.15 => 1.3.15
```

**Comment by cherishing** [comment]
const aa = `管理<font color="red" size="30">会</font>的根本区别是( )`;
<RichText nodes={aa}></RichText>
结果 font color并没有在百度小程序中渲染出来，web中是正常渲染的，这是什么原因呢

**Comment by astudentat** [comment]
19年的问题了，现在还没发在支付宝小程序使用RichText。有没有人关注一下～

**Comment by HeyShinner** [comment]
```js
<RichText
        nodes={
          process.env.TARO_ENV === "alipay"
            ? [
                {
                  name: "div",
                  attrs: {
                    class: "wrapper",
                    style: "color: orange;",
                  },
                  children: [
                    {
                      type: "text",
                      text: "Hello&nbsp;World!",
                    },
                  ],
                },
              ]
            : nodes
        }
      />
```
上述代码我支付宝都编译不过，报错如下：
![image](https://user-images.githubusercontent.com/16172530/170932280-f9153405-dd3d-4f64-97a3-1e2d12ba5256.png)

依赖版本：
"@tarojs/taro": "3.2.8",
"@tarojs/taro-alipay": "2.2.13",

支付宝开发者工具版本：
ap/SDKVersion: 1.25.4

**Comment by HeyShinner** [comment]
> 19年的问题了，现在还没发在支付宝小程序使用RichText。有没有人关注一下～

你是页面报错还是页面空白

**Comment by astudentat** [comment]
> > 19年的问题了，现在还没发在支付宝小程序使用RichText。有没有人关注一下～
> 
> 你是页面报错还是页面空白

空白，空白是没有用mini-html-parser。用了之后就能成功显示了

**Comment by HeyShinner** [comment]
> > > 19年的问题了，现在还没发在支付宝小程序使用RichText。有没有人关注一下～
> > 
> > 
> > 你是页面报错还是页面空白
> 
> 空白，空白是没有用mini-html-parser。用了之后就能成功显示了

方便看一下怎么使用的吗？我看我的写法没问题，已经定位是这个组件的问题了，return null 就不报错

**Comment by astudentat** [comment]
> 
js部分
nodes是 const [nodes,setNodes] = useState([])
<img width="602" alt="image" src="https://user-images.githubusercontent.com/40906200/170936053-58a4c2cc-45e2-466a-a14e-5078b1fb8125.png">
组件部分
<img width="488" alt="image" src="https://user-images.githubusercontent.com/40906200/170936183-69e81fb9-6def-4b28-a8a9-ebaf635104b9.png">

**Comment by astudentat** [comment]
> > > > 19年的问题了，现在还没发在支付宝小程序使用RichText。有没有人关注一下～
> > > 
> > > 
> > > 你是页面报错还是页面空白
> > 
> > 
> > 空白，空白是没有用mini-html-parser。用了之后就能成功显示了
> 
> 方便看一下怎么使用的吗？我看我的写法没问题，已经定位是这个组件的问题了，return null 就不报错

顺便问一下 你有试过dangerouslySetInnerHTML吗

**Comment by HeyShinner** [comment]
> > 
> 
> js部分 nodes是 const [nodes,setNodes] = useState([]) <img alt="image" width="602" src="https://user-images.githubusercontent.com/40906200/170936053-58a4c2cc-45e2-466a-a14e-5078b1fb8125.png"> 组件部分 <img alt="image" width="488" src="https://user-images.githubusercontent.com/40906200/170936183-69e81fb9-6def-4b28-a8a9-ebaf635104b9.png">

多谢，找到原因了，

> > > > > 19年的问题了，现在还没发在支付宝小程序使用RichText。有没有人关注一下～
> > > > 
> > > > 
> > > > 你是页面报错还是页面空白
> > > 
> > > 
> > > 空白，空白是没有用mini-html-parser。用了之后就能成功显示了
> > 
> > 
> > 方便看一下怎么使用的吗？我看我的写法没问题，已经定位是这个组件的问题了，return null 就不报错
> 
> 顺便问一下 你有试过dangerouslySetInnerHTML吗

多谢，找到问题了，是我大意了，小程序里暂时没试过这个 api
