### ISSUE TITLE
taro 1.3.8 子组件每次新增代码就提示 《没有被引用到，不会被编译》

### ISSUE THREAD

**Issue by zhangchenna** [NervJS/taro#3772]
taro 1.3.8 子组件每次新增代码就提示 《没有被引用到，不会被编译》
需要重新全量编译 太痛苦了

 Taro CLI 1.3.8 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.8 => 1.3.8 
      @tarojs/components: 1.3.8 => 1.3.8 
      @tarojs/mobx: 1.3.8 => 1.3.8 
      @tarojs/plugin-babel: 1.3.8 => 1.3.8 
      @tarojs/plugin-csso: 1.3.8 => 1.3.8 
      @tarojs/plugin-sass: 1.3.8 => 1.3.8 
      @tarojs/plugin-uglifyjs: 1.3.8 => 1.3.8 
      @tarojs/router: 1.3.8 => 1.3.8 
      @tarojs/taro: 1.3.8 => 1.3.8 
      @tarojs/taro-weapp: 1.3.8 => 1.3.8 
      @tarojs/webpack-runner: 1.3.8 => 1.3.8 
      eslint-config-taro: 1.3.8 => 1.3.8 
      eslint-plugin-taro: 1.3.8 => 1.3.8 
      nerv-devtools: 1.4.3 => 1.4.3 
      nervjs: 1.4.3 => 1.4.3

**Comment by zhangchenna** [comment]
是因为子组件代码太多？

**Comment by hqman** [comment]
类似问题 每次jsx 写错，都需要重新编译，开发效率严重降低，恳请大佬解决一下？

**Comment by liuhuyu** [comment]
顶啊 严重影响效率。。。

**Comment by guanrongjia** [comment]
顶 严重影响效率。。。

**Comment by sillyhong** [comment]
顶 严重影响效率。。。求修复

**Comment by zpzxgcr** [comment]
顶 严重影响效率。。。

**Comment by sillyhong** [comment]
> 顶 严重影响效率。。。求修复

我的问题找到了，是因为app.js 里面config.pages参数和文件夹大小写不一致。
