### ISSUE TITLE
【快应用】Taro Redux 模板 快应用报错

### ISSUE THREAD

**Issue by YouthBaby** [NervJS/taro#3773]
**问题描述**
使用taro redux模板创建快应用，编译成功，运行报错

**复现步骤**
[复现问题的步骤]
1、使用Taro redux模板创建一个默认demo
2、安装快应用必备依赖（@tarojs/components-qa @tarojs/taro-quickapp）
3、taro build --type quickapp -- --watch (第一次可能会报错，cd dist && npm install)
4、正常情况下会打开快应用，提示【很抱歉，TaroQuickAPP出现错误】

**期望行为**
运行正常（默认模板是正常的）

**报错信息**
![Screenshot_20190711_161816](https://user-images.githubusercontent.com/17606350/61034872-ac555080-a3f8-11e9-8568-02baae188d18.jpg)
![Screenshot_20190711_161818](https://user-images.githubusercontent.com/17606350/61034878-b1b29b00-a3f8-11e9-9d5a-cfdae44d8ecd.jpg)
**系统信息**
Taro CLI 1.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
**补充信息**
[可选]
直接原因可能是@tarojs/taro-quickapp/dist/index.js 中1762行 createContext： true是注释状态。
在dist\build\pages\index\index.js 中会执行 var ReduxContext = Taro__default.createContext(null);
希望可以支持下

**Comment by yuche** [comment]
你的项目依赖版本太低了

**Comment by YouthBaby** [comment]
> 你的项目依赖版本太低了

是用1.3.8创建的demo, 这个还低吗？依赖都是1.3.8

**Comment by YouthBaby** [comment]
> 你的项目依赖版本太低了

@yuche  刚刚升级了cli 到1.3.9, 创建redux模板，编译快应用，依旧报错，报错截图跟issue中一样
Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
![image](https://user-images.githubusercontent.com/17606350/61192749-57ac2100-a6e9-11e9-9aa0-810895603b3f.png)
