### ISSUE TITLE
tarojs/plugin-babel 版本和其他包不一致

### ISSUE THREAD

**Issue by broven** [NervJS/taro#3779]
**问题描述**
tarojs/plugin-babel 没有发布1.3.8版本, taro update project 却将pkg.json 中的tarojs/plugin-babel跟新为1.3.8
**复现步骤**
```
$ taro update self
$ taro update project
```

**期望行为**
我认为不是tarocli的问题， 而是这次发包的问题。
既然是用lerna管理, 并且版本号不是independent, 那么tarojs/plugin-babel应该随着一起发布才对吧。

**补充信息**
建议发布下tarojs/plugin-babel

**Comment by broven** [comment]
or `taro update project` 里面的 tarojs/plugin-babel改下版本?

**Comment by Garfield550** [comment]
这个原因是因为 taro-cli 在更新时会查一下 taro-cli 的版本，如 1.3.8，然后将 package.json 里 Taro 所有的依赖包版本都指定为 1.3.8。

这样做的原因是基于 Lerna 统一管理版本的模式来的。

如果某个包（如这个 @tarojs/plugin-babel）版本不一致，可以手动改为 NPM 上的最新版本，然后重新执行 npm i/yarn 安装一下。
