### ISSUE TITLE
使用typescript引用<App/>报错的问题

### ISSUE THREAD

**Issue by geekeryoung** [NervJS/taro#378]
我创建时开启了typescript，然后生成的app.tsx加载的那里有这么一行代码：
`Taro.render(<App/>, document.getElementById('app'));`
`<App/>`这里一直在报这个错：
`Error:(42, 13) TS2345: Argument of type 'Element' is not assignable to parameter of type 'Component<{}, {}>'.Property 'setState' is missing in type 'Element'.`
虽然可以编译成功，但是总有一条红线看着好难受啊，求解决办法。

**Comment by luckyadam** [comment]
可以试试最新版本~ 0.0.73

**Comment by yuche** [comment]
closing via https://github.com/NervJS/taro/commit/779157fd585ea55c796a6cd24b1187377d6314f7
