### ISSUE TITLE
金立快应用1040版本样式有问题

### ISSUE THREAD

**Issue by thisSillyCow** [NervJS/taro#3780]
**问题描述**
dai'm代码
![OSC@X4 N2N7S3P1NXOVUJU1](https://user-images.githubusercontent.com/30546278/61052287-aa51b880-a41d-11e9-9fa7-de608943d722.png)
显示结果：
![IMG_3637](https://user-images.githubusercontent.com/30546278/61052309-b50c4d80-a41d-11e9-816d-0e669469f74e.JPG)
[novel_hap.zip](https://github.com/NervJS/taro/files/3382063/novel_hap.zip)

**Comment by yuche** [comment]
在你这个情况 Taro 是不会对样式做特殊处理的，很可能就是快应用容器本身有样式处理得 bug
