### ISSUE TITLE
小程序上使用组件和不使用组件相同的样式会有不同的表现

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#3782]
如下图所示的，给scrollview这样的样式更够让他自动高度，并且占据剩余的所有空间，但是把它放在组件里面就不行了！这个不知道是不是小程序的问题还是什么问题？
![微信图片_20190712100249](https://user-images.githubusercontent.com/31879769/61097099-837e9b00-a48c-11e9-9a12-5f1c295230fa.png)
![微信图片_20190712100258](https://user-images.githubusercontent.com/31879769/61097100-84173180-a48c-11e9-8052-5a1318bf401c.png)

**Comment by ShaoGongBra** [comment]
https://developers.weixin.qq.com/s/bUalrUmQ7P9A
这个是小程序示例，是可以用flex让组件自动高度的

**Comment by jinjinjin0731** [comment]
你的小程序示例的自定义组件  safeview 这里 给了 class 啊。 而你上面截图的自定义组件 scroll-view-self 并没有给  class 样式.  你的示例上 safeview 的 class 删掉一样不能撑开高度

**Comment by ShaoGongBra** [comment]
我知道呀，我不知道吗，问题是我用taro，我要怎么给这个加上一个class呢？  @jinjinjin0731
