### ISSUE TITLE
微信开发者工具真机调试报错

### ISSUE THREAD

**Issue by mxh861001** [NervJS/taro#3783]
**问题描述**
刚初始化的新项目，开发者工具真机调试就直接报错了

**复现步骤**
1. taro init **
2. yarn dev:weapp

**报错信息**
![001](https://user-images.githubusercontent.com/9146759/61097539-44514980-a48e-11e9-8587-a6e9f2be755e.jpg)

**系统信息**
<img width="364" alt="002" src="https://user-images.githubusercontent.com/9146759/61097628-95f9d400-a48e-11e9-8903-b94633721b70.png">

**Comment by Garfield550** [comment]
您好，这个是微信小程序开发者工具的问题，官方已经修复，请更新一下微信小程序开发工具到 Nightly 版本

Ref: https://developers.weixin.qq.com/community/develop/doc/0006e0a83c4af0c53fd8d1dde5b000?highLine=define

**Comment by mxh861001** [comment]
@Garfield550  多谢，已经看到了
