### ISSUE TITLE
使用mobx时，componentWillMount写成箭头函数后，observable变量变化页面不会刷新

### ISSUE THREAD

**Issue by z372183629** [NervJS/taro#3792]
**问题描述**
[问题描述：使用mobx的组件，componentWillMount写成箭头函数会出现不刷新的问题]

**复现步骤**
[复现问题的步骤]
1. 写一个全局store，在app.js中通过Provider注入
2. 在页面A中通过inject注入store，显示store的内容，再写个button修改内容
3. 在页面A中声明componentWillMount方法，写成箭头函数形式，```componentWillMount=()=>{}```
4. 运行，点击button修改store的内容，观察页面刷新情况

// 代码放这里
```
https://github.com/z372183629/taro-mobx-demo
```

**期望行为**
如果不可以写成箭头函数，请在文档中注明；或者修复这个bug

**报错信息**
页面不刷新

**系统信息**

 - 操作系统: macos mojave 10.14.5
 - Taro 版本 1.3.6
 - Node.js 版本 10.10.0
 - npm 版本 6.10.0
 - 报错平台 weapp

**Comment by z372183629** [comment]
目前还发现一个问题
使用了mobx包裹的组件，componentWillMount方法写成箭头函数后，在它销毁时，会触发错误
```
Cannot read property 'dispose' of undefined; [Component] Lifetime Method Error @ pages/home/home#detached
```

**Comment by Garfield550** [comment]
您好，原生 React 不建议使用箭头函数定义生命周期方法。

> An important issue when using arrow function properties is that, because they are properties and not methods, they do not exist in the prototype.

> This prevents the browser from reusing the same function when rendering multiple copies of the same element (each copy of the element will be running a different render function, instead of the same function with a different `this` every time), which makes optimization by the javascript engine harder to do, or at the very least delays the point where the engine would want to optimize.

> Even where arrow function properties are supported (TypeScript, babel with class properties plugin), it is recommended to write everything as methods, so they exist in the prototype. If any of your methods needs to be given as an argument or as JSX element's property, the recommendation is to do `this.methodName = this.methodName.bind(this)` in the constructor, creating a local version of the shared prototype method.

Ref: https://github.com/facebook/react/issues/10810

**Comment by z372183629** [comment]
> 您好，原生 React 不建议使用箭头函数定义生命周期方法。
> 
> > An important issue when using arrow function properties is that, because they are properties and not methods, they do not exist in the prototype.
> 
> > This prevents the browser from reusing the same function when rendering multiple copies of the same element (each copy of the element will be running a different render function, instead of the same function with a different `this` every time), which makes optimization by the javascript engine harder to do, or at the very least delays the point where the engine would want to optimize.
> 
> > Even where arrow function properties are supported (TypeScript, babel with class properties plugin), it is recommended to write everything as methods, so they exist in the prototype. If any of your methods needs to be given as an argument or as JSX element's property, the recommendation is to do `this.methodName = this.methodName.bind(this)` in the constructor, creating a local version of the shared prototype method.
> 
> Ref: [facebook/react#10810](https://github.com/facebook/react/issues/10810)

使用```taro convert```命令将小程序转成tarojs项目，输出的结果中，包含大量使用箭头函数表示的生命周期方法。
我就是在convert后的代码中发现的问题。

**Comment by yuche** [comment]
> 您好，原生 React 不建议使用箭头函数定义生命周期方法。
> 
> > An important issue when using arrow function properties is that, because they are properties and not methods, they do not exist in the prototype.
> 
> > This prevents the browser from reusing the same function when rendering multiple copies of the same element (each copy of the element will be running a different render function, instead of the same function with a different `this` every time), which makes optimization by the javascript engine harder to do, or at the very least delays the point where the engine would want to optimize.
> 
> > Even where arrow function properties are supported (TypeScript, babel with class properties plugin), it is recommended to write everything as methods, so they exist in the prototype. If any of your methods needs to be given as an argument or as JSX element's property, the recommendation is to do `this.methodName = this.methodName.bind(this)` in the constructor, creating a local version of the shared prototype method.
> 
> Ref: [facebook/react#10810](https://github.com/facebook/react/issues/10810)
> 
> 这里也有个 StackOverflow 回答告诉你不建议为生命周期方法使用箭头函数写法。
> 
> > Each time your function performs a => operation it has to create a new function object. This prevents the browser from reusing the same function when rendering multiple copies of the same element which makes optimization by the javascript engine harder to do. This would cause performance issues(, but in most programs, it won't be noticeable).
> 
> > It is recommended not to use arrow functions for life-cycle methods in React
> 
> Ref: [stackoverflow.com/questions/48571948/pros-and-cons-of-using-reacts-life-cycle-methods-in-arrow-function-format/48572018](https://stackoverflow.com/questions/48571948/pros-and-cons-of-using-reacts-life-cycle-methods-in-arrow-function-format/48572018)

也没有说不支持，而是技术上可以这么做。

但之前有人回答得对，使用箭头函数的话在原型就找不到。然而许多库是从原型上判断有没有生命周期再执行，因此更好的做法还是用类方法。

**Comment by z372183629** [comment]
@Garfield550 目前疑惑解决了，另外还有个问题，```taro convert```命令还需要优化下，转出来的页面代码中，几乎都是以箭头函数形式定义的生命周期方法，很容易出问题。

**Comment by yuche** [comment]
close via eb7931ccaa0f29aba96c77b46877343f33ae2d68
