### ISSUE TITLE
小程序插件模板使用taro-ui路径错误

### ISSUE THREAD

**Issue by guxingke201** [NervJS/taro#3794]
**问题描述**
小程序插件模板使用taro-ui路径错误
**复现步骤**
[复现问题的步骤]
1. taro init 

![image](https://user-images.githubusercontent.com/8326941/61106302-4c6db100-a4af-11e9-81a1-cd644fb11231.png)

2.  修改`src\plugin\pages\list\list.tsx`，引入taro-ui
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import ListItem from '../../components/listItem/listItem'
import { AtButton } from 'taro-ui'
import './list.scss'

export default class List extends Component {
  state = {
    list: [
      {
        name: 'A',
        value: '1'
      },
      {
        name: 'B',
        value: '2'
      },
      {
        name: 'C',
        value: '3'
      }
    ]
  }

  render() {
    return (
      <View>
        {this.state.list.map(item => {
          return <ListItem name={item.name} value={item.value} key={item.name} />
        })}
        <AtButton type='primary' disabled>
          不可操作
        </AtButton>
      </View>
    )
  }
}

```
list.scss
```css
@import '~taro-ui/dist/style/components/button.scss';
@import '~taro-ui/dist/style/components/loading.scss';
```
3. 运行`npm run dev:weapp`
4. 运行`taro build --plugin weapp --watch`
5. 使用微信开发工具打开根目录，点击`Go to pages/list`

**期望行为**
修改taro plugin 构建，正常解析扩展组件路径，正常浏览插件页面

**报错信息**
![image](https://user-images.githubusercontent.com/8326941/61106589-33193480-a4b0-11e9-85c9-bd4addbf9e22.png)

**系统信息**
 Taro CLI 1.3.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 9.9.0 - H:\node\nodejs\node.EXE
      npm: 5.6.0 - H:\node\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
![image](https://user-images.githubusercontent.com/8326941/61106649-6360d300-a4b0-11e9-8b78-ac8b1ffcb1bc.png)
`../../../npm/taro-ui/`多了一级，改为`../../npm/taro-ui/`就正常了

**Comment by DreamPWJ** [comment]
这个问题非常严重，严重影响开发效率

**Comment by ThatRoy** [comment]
@guxingke201 你好，请问这个问题，现在是只能先手动把打包后文件里的路径改掉吗 ？

**Comment by guxingke201** [comment]
官方没解决，只能手动改了

**Comment by Chen-jj** [comment]
尽快修复
