### ISSUE TITLE
@tarojs/cli 1.3.8版本页面在使用纯函数式组件时会发生TypeError: Cannot call a class as a function错误

### ISSUE THREAD

**Issue by xuedingesmiao** [NervJS/taro#3799]
**问题描述**
@tarojs/cli 1.3.8版本页面在使用纯函数式组件时会发生错误，浏览器控制台报TypeError: Cannot call a class as a function错误，
![image](https://user-images.githubusercontent.com/25097637/61113326-9dd26c00-a4c0-11e9-8494-19d322be9a4e.png)
，但是用class组件包裹函数式组件就不会报错
1.3.6无此问题，这应该是1.3.8的一个bug

**复现步骤**

函数式组件代码如下
```js
import Taro from '@tarojs/taro';
import { View } from '@tarojs/components';

function Index() {
  return <View>this is a function component</View>;
}

export default Index;
```
函数组件单独做页面就会报错，
![image](https://user-images.githubusercontent.com/25097637/61115708-9e213600-a4c5-11e9-9f45-5ddb027c1dbf.png)

用class组件包裹就不会报错
![image](https://user-images.githubusercontent.com/25097637/61115555-4da9d880-a4c5-11e9-82b5-dd78a87766b8.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v1.3.8]
 - Node.js 版本 [v10.16.0 ]
 - 报错平台 [h5]

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/d0bc3bd10a1860b4bc1e6daace7a2a8c4c787b7a should fixed.
