### ISSUE TITLE
map 列表的时候，map函数外部变量无法使用

### ISSUE THREAD

**Issue by jimczj** [NervJS/taro#380]
**问题描述**
在render函数中，map 列表的时候，map函数外部变量无法使用

**复现步骤**

```js
render () {
    const { tabList, scroll } = this.props
    const itemCls = 'at-tabs__item'
    return <View className='at-tabs']>
      <View className='at-tabs__item at-tabs__item--current' onClick={this.handleClick}>标签</View>
      {
        tabList.map(item => <View className={itemCls} key={item.key} onClick={this.handleClick.bind(this)}>
          {item.title}
        </View>)
      }
    </View>
  }

```

**期望行为**
view 有 className

**报错信息**

如下图，className 没办法传入
![image](https://user-images.githubusercontent.com/13499146/43194070-1ae06500-9034-11e8-93dc-528d889a2d1c.png)

**系统信息**

 - 操作系统: [mac 10.13.3]
 - Taro 版本 [v.0.0.70]
 - Node.js 版本 [v10.0.0]

**补充信息**

**Comment by Harhao** [comment]
遇到相类似的需要动态样式的情况，尝试比较多的做法，都会编译出错，期待社区给出好的解决方法
