### ISSUE TITLE
sass全局使用、一直引入不进去、求大声帮忙

### ISSUE THREAD

**Issue by lifudea** [NervJS/taro#3800]
![Uploading 1562926660(1).png…]()
![1562926708(1)](https://user-images.githubusercontent.com/50136663/61121294-78019300-a4d1-11e9-918a-b3d53b229655.png)
![1562926727(1)](https://user-images.githubusercontent.com/50136663/61121313-818afb00-a4d1-11e9-8b6d-978d50debe6b.png)
sass一直引入不进入

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by lifudea** [comment]
taro 1.3.0版本的   谢谢了




------------------ 原始邮件 ------------------
发件人: "Li,Weitao"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 晚上8:54
收件人: "NervJS/taro"<taro@noreply.github.com>; 
抄送: "咿呀咿呀咿"<525537973@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NervJS/taro] sass全局使用、一直引入不进去、求大声帮忙 (#3800)




taro 版本多少

**Comment by luckyadam** [comment]
升级到最新版本再试试

**Comment by lifudea** [comment]
还是不可以、

**Comment by lifudea** [comment]
目前1.3.9版本

**Comment by moonreplace** [comment]
1.3默认用的是dart, 试试这个能行不？
`const sass = require('node-sass');
sassLoaderOption: {
            implementation: sass,
            includePaths: [nodeModulesPath, styleBasePath]
        },
`
@lifudea

**Comment by lifudea** [comment]
我试试了下不可以、不知道是不是我写错了 。是放publish里   plugins:{sassLoaderOption: { implementation: sass, includePaths: ['src/mixin.scss'] }}  么......

**Comment by o-x-o** [comment]
webpack的sass配置都是在 module 里配的。可在taro里却是在plugins里配而且感觉丝毫不起作用。

**Comment by moonreplace** [comment]
> 我试试了下不可以、不知道是不是我写错了 。是放publish里 plugins:{sassLoaderOption: { implementation: sass, includePaths: ['src/mixin.scss'] }} 么......

publicPath: packConfig.nonImagePublicPath,
        staticDirectory: 'static',
        sassLoaderOption: {
            implementation: sass,
            includePaths: [nodeModulesPath, styleBasePath]
        },
直接放在config根目录下

**Comment by moonreplace** [comment]
> webpack的sass配置都是在 module 里配的。可在taro里却是在plugins里配而且感觉丝毫不起作用。

直接放在config根目录下配

**Comment by o-x-o** [comment]
都不行

**Comment by o-x-o** [comment]
> > webpack的sass配置都是在 module 里配的。可在taro里却是在plugins里配而且感觉丝毫不起作用。
> 
> 直接放在config根目录下配

不行

**Comment by Nodewebzsz** [comment]
遇到相同的问题，编译报错，求解

**Comment by Garfield550** [comment]
在 #4443 解决了，等新版本再试一下。
