### ISSUE TITLE
Taro自定义组件的子组件使用微信原生自定义组件，父组件无法监听子组件事件

### ISSUE THREAD

**Issue by seeyoumr** [NervJS/taro#3801]
**问题描述**
 Taro 自定义组件 A，引用 微信小程序原生自定义组件B，组件A无法监听组件B发出的事件。

**复现步骤**
```js
// 组件A
class A extends Component {

	constructor(props) {
		super(props);
	}
	
	myeventListoner = (params: any = null) => {
		console.log('I am clicked, params: ', params);
	}
	
	render() {
		return (
			<View>
			  <custom-editor testName="点我点我点我" bindmyevent={this.myeventListoner}></custom-editor>
			</View>
		);
	}
}

// 组件B
// wxml
<view class="test-box" bindtap="onTap">
  {{testName}}
</view>
// js
Component({
  properties: {
    testName: {
      type: String,
      value: 'testName,haha'
    }
  },
  methods: {
    onTap: function(e) {
      console.log(e)
      console.log('this: ', this);
      this.triggerEvent('myevent', e.detail, {})
    },
  }
})
// 点击“点我点我点我”
```

**期望行为**
点击后可以调到组件A中的myeventListoner方法

**报错信息**
VM10019:1 Component "components/A/index" does not have a method "myeventListoner" to handle event "myevent".

**系统信息**
 - 操作系统: [e.g. Windows 10 ]
 - Taro 版本 [e.g. v.1.2.22]
 - Node.js 版本 [e.g. v10.13.0]
 - 报错平台 [weapp]

**补充信息**
暂无

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/mini-third-party.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by seeyoumr** [comment]
组件A的代码render:
`return (
      <View style={visibleStyle}>
        <AtList>
          <AtListItem title={label} hasBorder={false} />
          <View style={{padding: '0 24rpx 10rpx'}}>
            <View>
              <custom-editor testName='点我点我点我' onBindmyevent={this.myeventListoner}></custom-editor>
            </View>
          </View>
        </AtList>
      </View>
    );`
运行不会报错了，但是并没有执行回调函数 myeventListoner

**Comment by yuche** [comment]
`onMyevent`

**Comment by seeyoumr** [comment]
首先感谢 @yuche ，下面贴出可运行代码：
1：组件A中部分改动代码：`<custom-editor testName="点我点我点我" onMyevent={this.myeventListoner}></custom-editor>`
2：组件B中部分改动代码：`this.triggerEvent('onmyevent', e.detail, {})`;
再次感谢各位对我的帮助！
