### ISSUE TITLE
创建H5应用，如何实现外部链接的跳转？

### ISSUE THREAD

**Issue by TonyLiuYan** [NervJS/taro#3803]
使用taro创建一个H5的应用，想实现点击按钮或着链接跳转到www.baidu.com这样的外部链接地址网站，该如何实现？

**Comment by innocces** [comment]
=。-  window.location.href='http://www.baidu.com'

**Comment by Trouble5** [comment]
跳转之后返回来会显示首页页面，虽然链接还是上一层的

**Comment by jsonliu6** [comment]
这个问题有解决方法吗？
