### ISSUE TITLE
this.props.children插入位置不对

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#3809]
{this.props.children}进来的位置怎么不对了呢？然后就导致ScrolView的scrollIntoView失效了，无法滚动到指定的id
![微信图片_20190713100617](https://user-images.githubusercontent.com/31879769/61165709-69a98a80-a556-11e9-9be2-8736d149ad83.png)

**Comment by ShaoGongBra** [comment]
亲测在小程序上渲染后的效果也是一样的，和在开发者工具上一样

**Comment by ShaoGongBra** [comment]
我看可原生小程序的solt也是这样的问题。。。。。这个难道要原生小程序支持吗？

**Comment by liuhailang** [comment]
我也遇到了this.props.children插入位置不对的问题

**Comment by ShaoGongBra** [comment]
一般情况下就算插入位置不对，样式也是没问题的，但是我这个是插入到ScrollView下面的，这样的话，this.props.children的内容不在ScrollView下，然后ScrollView的scrollIntoView就没办法跳转到相应的位置 @liuhailang

**Comment by ShaoGongBra** [comment]
@yuche 大佬能不能给微信反馈一下，我们这种没什么普通程序员，在微信社区发个帖都没有回复的，官方也不看

**Comment by yuche** [comment]
这个也没啥办法，他们也不怎么鸟我们

**Comment by ShaoGongBra** [comment]
。。。微信这么吊的吗，这个问题我看社区上一年前就有人提过了 @yuche

**Comment by liuhailang** [comment]
我这边位置不对的话是会影响布局的@ShaoGongBra

**Comment by ShaoGongBra** [comment]
额，你是怎么写的，怎么会影响布局呢，我在微信社区发起了一个帖子，可以去顶一下
https://developers.weixin.qq.com/community/develop/doc/000882eae2c1001fa3d8cca4651000
@liuhailang

**Comment by melunar** [comment]
> 一般情况下就算插入位置不对，样式也是没问题的，但是我这个是插入到ScrollView下面的，这样的话，this.props.children的内容不在ScrollView下，然后ScrollView的scrollIntoView就没办法跳转到相应的位置 @liuhailang

我也遇到这个问题 了，做字母索引不能通过外部children的方式传入，怪不得taro-ui的字母索引把内部样式写死了，原来是不能扩展，真是坑
