### ISSUE TITLE
lodash 引入问题

### ISSUE THREAD

**Issue by lionrock** [NervJS/taro#381]
**问题描述**
引入`lodash.get`后报错

**复现步骤**
1. `yarn add lodash.get`
2. 在组件内引入lodash.get `import get from 'lodash.get'` 后使用`get`方法会报错

```js
import get from 'lodash.get';
// 此处省略若干代码
get(object, 'propName', 'defaulValue');
```

**报错信息**
![image](https://user-images.githubusercontent.com/4017964/43206834-2c91238c-9059-11e8-9dd3-1680e0815dd6.png)

**系统信息**

 - 操作系统: MacOS 10.13.6
 - Taro 版本 v0.0.73
 - Node.js 版本 v9.11.1

**补充信息**

`dist/npm/lodash.get/index.js` 的导出方式为 `module.exports = get;`

![image](https://user-images.githubusercontent.com/4017964/43207208-1feaf76a-905a-11e8-8bf5-2c0b2e1c880a.png)

**解决方案**
加上`module.exports.default = get;`

**Comment by lionrock** [comment]
引入 moment 同样有问题
![image](https://user-images.githubusercontent.com/4017964/43210421-a691cad0-9061-11e8-99f9-bfe254a67c8f.png)

**Comment by lionrock** [comment]
不知道能否统一加上`module.exports.default = module.exports`

**Comment by luckyadam** [comment]
可以可以~可以在编译的时候处理~

**Comment by HecateDK** [comment]
这个问题应该解决了吧，我在`1.0.0-beta.8`版本的时候是好的
![image](https://user-images.githubusercontent.com/19571458/44200787-0d898b00-a17a-11e8-83e9-de9b654693d3.png)

**Comment by luckyadam** [comment]
@lionrock 试试最新的 beta 版本呢
