### ISSUE TITLE
Switch Component不应该在组件内部State中修改Checked Property

### ISSUE THREAD

**Issue by dcalsky** [NervJS/taro#3812]
**问题描述**
使用Switch组件的时候，传入一个props: {Checked: boolean}，值为false，点击Switch切换。如果props中的Checked的依然为false（没变），那么Switch也不应该被切换到Checked=true的状态。

也就是说，Switch的Checked状态应该由外部props决定，而不能在内部State中擅自修改。

理论上说，应该去掉这段代码。
https://github.com/NervJS/taro/blob/dc3530297c087f17392df045f586b4a5dea600bb/packages/taro-components/src/components/switch/index.js#L32-L34

**期望行为**
如果不修改props中的checked，那么switch不应该被切换到checked状态。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOS]
 - Taro 版本 [e.g. v.1.3.9]
 - Node.js 版本 [e.g. v12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
https://github.com/NervJS/taro/blob/dc3530297c087f17392df045f586b4a5dea600bb/packages/taro-components/src/components/switch/index.js#L32-L34

**Comment by GYxiaOZ** [comment]
我也觉得，现在的switch并不是受控组件，应该用props传入的checked来确定状态，而不应该用内部的state来确定状态

**Comment by ZakaryCode** [comment]
这一点是和微信小程序端保持一致的。

如果希望通过传入checked控制，依旧可以通过设置checked来控制组件内部的状态，并无影响。
