### ISSUE TITLE
taro 框架集成 极光小程序IMSdk, 无法连接远程的websocket服务

### ISSUE THREAD

**Issue by xiangxiong** [NervJS/taro#3814]
**问题描述**
1、taro 框架集成 极光推送小程序Sdk, 无法连接远程的websocket服务。经过测试，在原生的小程序的app.js 中集成是没有问题的。表明远程socket服务和sdk 多没有问题.

**复现步骤**
[复现问题的步骤]
1. 在极光官网下载小程序的sdk,按照官方提示步骤集成到项目中. 请参考 https://docs.jiguang.cn//jmessage/client/im_sdk_wxapplet/
2. 初始化相关的秘钥参数:
```
   // jmessage-wxapplet-sdk-1.4.0 这个可以去上面提供的官网地址下载. 这段代码放在js 文件最上面。
  var JMessage = require('./utils/jmessage-wxapplet-sdk-1.4.0.min.js'); 

  componentDidMount () {
    this.init();
  }
  
  init(){
    var jim = new JMessage({
      debug : true
    });
    console.log('jim',jim);
  
    jim.init({
      appkey:"bb62a48cc54e300e2e58fa0b",
      random_str:"b37b052d0e9b4aa8a16ebe5446f9fba9",
      signature:"bf184eeb9722a637c313a36e9fea80bf",
      timestamp:"1562947140309"
    }).onSuccess(function(data) {
      console.log('data',data);
      //TODO
    }).onFail(function(data) {
      console.log('data',data);
      //TODO
    });
  }
```

**期望行为**
期望能够得到onSuccess 里面打印的内容    console.log('data',data);。

**报错信息**
这里没有明显异常，只在控制台的network 里面没有看到 ws 里面有连接请求。表明没有连上websocket 服务.

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. OS X El Capitan 10.11.20]
 - Taro 版本 [e.g. Taro v1.2.20]
 - Node.js 版本 [e.g. v10.9.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
有什么报错么

**Comment by xiangxiong** [comment]
没有报错,就是 jim.init 初始化函数 连不上 wss  服务（wss://ws.im.jiguang.cn/socket.io/?EIO=3&transport=websocket），network 里面没有长连接请求,  然后没有执行回调  .onSuccess(function(data) {}).   不知道这种第三方框架集成的问题，连接 wss  这种服务，最好放在哪个入口文件比较合适。或者在哪个阶段运行最合适.

**Comment by luckyadam** [comment]
原生小程序里是如何集成的，看上去这个 sdk 的集成是和框架无关的

**Comment by webzhangxiaoyu** [comment]
> **问题描述**
> 1，taro框架集成了sdk，无法连接远程的websocket服务。经过测试，在原生的小程序的app.js中集成是没有问题的。表明远程socket服务和sdk没有问题。
> 
> **复现步骤**
> [复现问题的步骤]
> 
> 1. 在极光官网下载小程序的sdk，按照官方提示步骤集成到项目中。请参考https://docs.jiguang.cn//jmessage/client/im_sdk_wxapplet/
> 2. 初始化相关的秘钥参数：
> 
> ```
>    // jmessage-wxapplet-sdk-1.4.0 这个可以去上面提供的官网地址下载. 这段代码放在js 文件最上面。
>   var JMessage = require('./utils/jmessage-wxapplet-sdk-1.4.0.min.js'); 
> 
>   componentDidMount () {
>     this.init();
>   }
>   
>   init(){
>     var jim = new JMessage({
>       debug : true
>     });
>     console.log('jim',jim);
>   
>     jim.init({
>       appkey:"bb62a48cc54e300e2e58fa0b",
>       random_str:"b37b052d0e9b4aa8a16ebe5446f9fba9",
>       signature:"bf184eeb9722a637c313a36e9fea80bf",
>       timestamp:"1562947140309"
>     }).onSuccess(function(data) {
>       console.log('data',data);
>       //TODO
>     }).onFail(function(data) {
>       console.log('data',data);
>       //TODO
>     });
>   }
> ```
> 
> **期望行为**
> 期望能够获得onSuccess里面打印的内容console.log（'data'，data）;。
> 
> **报错信息**
> 这里没有明显异常，只在控制台的网络里面没有看到ws里面有连接请求。表明没有连上websocket服务。
> 
> **系统信息**
> 
> > Taro v1.2及更高版本已添加`taro info`命令，方便大家查看系统及依赖信息，运行该命令后将结果粘贴下面即可。
> 
> * 操作系统：[例如OS X El Capitan 10.11.20]
> * Taro版本[例如Taro v1.2.20]
> * Node.js版本[例如v10.9.0]
> * 报错平台[weapp]

你好，我也遇见这个问题了，请问怎么解决。

**Comment by bestK** [comment]
我也是一样的症状

**Comment by fengyua5** [comment]
楼上有解决方案了吗
