### ISSUE TITLE
快应用端JSX不支持...spread表达式

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#3816]
**问题描述**
快应用端JSX不支持...spread表达式

**期望行为**
期望...spread表达式能正常使用

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Linux 4.15 Deepin 15 15.10.2
 - Taro 版本 [1.3.9]
 - Node.js 版本 [12.3.1]
 - 报错平台 [quickapp]

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/4d18e3cc9eecaacc2fefa603e9966888e9cdb53e
