### ISSUE TITLE
map 函数里面，子组件无法正常使用

### ISSUE THREAD

**Issue by jimczj** [NervJS/taro#382]
**问题描述**
render 函数中，使用jsx进行map，组件使用错误

**复现步骤**
[复现问题的步骤]
```js
render () {
    const { tabList, current, color } = this.props
    const style = `color: ${color};border-bottom: 1px solid ${color};`
    return <View className='at-tab-bar'>
      {
        tabList.map((item, i) => <View className='at-tab-bar__item' style={current === i ? style : ''} key={item} onClick={this.handleClick.bind(this, i)}>
          <View className='at-tab-bar__icon' ><AtIcon value='computer' color={color} /></View>
          <View className='at-tab-bar__title'>{item.title}</View>
        </View>)
      }
    </View>
  }

```
AtIcon 是自己定义的一个组件，在map函数外面能正常使用如图1，在map函数里面无法正常调用如图2

***图1：***
![image](https://user-images.githubusercontent.com/13499146/43207626-0c055e42-905b-11e8-9d67-79294663dff1.png)

***图2：***
![image](https://user-images.githubusercontent.com/13499146/43207703-36fd3480-905b-11e8-95ed-b23a45b67805.png)

**期望行为**
在map中能正常使用组件

**报错信息**

![image](https://user-images.githubusercontent.com/13499146/43207825-7db76a1c-905b-11e8-9454-9a4d28f4e246.png)
props 无法传递过去

**系统信息**

 - 操作系统: [mac 10.13.3]
 - Taro 版本 [v.0.0.70]
 - Node.js 版本 [v10.0.0]

**补充信息**
map 时 props 无法传递

**Comment by luckyadam** [comment]
#389
目前提供了新的组件化版本，升级到 1.0.0-beta.1 试试~
