### ISSUE TITLE
TARO_BUILD_TYPE=ui taro build --ui 组件打包的产物只有h5与weapp吗？xxx.swan.js, xxx.alipay.js等各端文件丢失

### ISSUE THREAD

**Issue by tanshenghu** [NervJS/taro#3822]
针对于独立的组件库(组件工程与项目工程是分开的)打包，最终产物只有h5,weapp目录

打包命令用的是官方提供的TARO_BUILD_TYPE=ui taro build --ui

比如test组件目录里面有 test.js, test.h5.js, test.weapp.js, test.swan.js, test.alipay.js文件
而组件打完包后 test.swan.js, test.alipay.js 这两个端的文件没有打过来，而这两个文件可能与微信端又有很大的不同之处，是需要单独处理的

**Comment by luckyadam** [comment]
小程序都是从 weapp 目录下引用文件
