### ISSUE TITLE
Component properties 是否应该 shakeFnFromObject？

### ISSUE THREAD

**Issue by cangku** [NervJS/taro#3823]
**问题描述**
开发某组件的时候，希望传递一个对象至组件内部，对象中的 function 被过滤了。

**复现步骤**
运行[代码片段](https://developers.weixin.qq.com/s/Foj7JSmb7r9s)，然后断点页面内和组件内均可以使用 data 对象中的 function 。Taro 相关[代码位置](https://github.com/NervJS/taro/blob/master/packages/taro-weapp/src/lifecycle.js#L165)

**期望行为**
不过滤 function ？

**报错信息**
无

**系统信息**
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.0 => 1.3.8 
      @tarojs/components: 1.3.0 => 1.3.0 
      @tarojs/plugin-babel: 1.3.0 => 1.3.0 
      @tarojs/plugin-csso: 1.3.0 => 1.3.0 
      @tarojs/plugin-less: ^1.3.3 => 1.3.8 
      @tarojs/plugin-stylus: 1.3.0 => 1.3.0 
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0 
      @tarojs/redux: ^1.3.0 => 1.3.8 
      @tarojs/redux-h5: ^1.3.0 => 1.3.8 
      @tarojs/router: 1.3.0 => 1.3.0 
      @tarojs/taro: 1.3.0 => 1.3.0 
      @tarojs/taro-alipay: 1.3.0 => 1.3.0 
      @tarojs/taro-h5: 1.3.0 => 1.3.0 
      @tarojs/taro-swan: 1.3.0 => 1.3.0 
      @tarojs/taro-tt: 1.3.0 => 1.3.0 
      @tarojs/taro-weapp: 1.3.0 => 1.3.0 
      @tarojs/webpack-runner: 1.3.0 => 1.3.0 
      eslint-config-taro: 1.3.0 => 1.3.0 
      eslint-plugin-taro: 1.3.0 => 1.3.0 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.0.1

**补充信息**
AppData 中没有展示对应属性的 function。这里同步一个微信社区官方咨询[AppData function](https://developers.weixin.qq.com/community/develop/doc/000424bff60a60cfaad86a0375b800?fromCreate=1)

**Comment by Chen-jj** [comment]
@cangku 提供原生的代码片段意思是什么？

**Comment by Chen-jj** [comment]
@cangku CLI 与版本都升级到 1.3.9 再试试。还有问题则提供相关可复现代码。
