### ISSUE TITLE
打包H5，如何修改打包出来的chunk引用路径？

### ISSUE THREAD

**Issue by Fntys** [NervJS/taro#3824]
现在打包出来的app.js里面引入的chunk路径默认为/chunk/index_index,js。
我想修改，请问如何配置？

**Comment by luckyadam** [comment]
https://taro-docs.jd.com/taro/docs/config-detail.html#h5publicpath

**Comment by Fntys** [comment]
已经找到解决方案了，配置这个就可以了:
chunkPublicPath
