### ISSUE TITLE
编译出错 与预期不符合

### ISSUE THREAD

**Issue by Jackliu007888** [NervJS/taro#3825]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 执行编译命令  正常编译
![image](https://user-images.githubusercontent.com/23191517/61197948-02343c00-a70a-11e9-9b89-538bfbac7a2e.png)

```js
render() {
  debugger
  const {
      userStore: {memberInfo}= {},
      shopStore: {
        shopInfo: {
          logo = '',
          merchantName = ''
        }
      } = {},
    } = this.props
  debugger
}
```
编译成
```
var _this5 = this;

      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __isRunloopRef = arguments[2];
      var __prefix = this.$prefix;
      ;
      var $compid__10 = (0, _index.genCompid)(__prefix + "$compid__10");

      debugger;
```

**期望行为**
es6的结构错误  就算用es5写  也会少声明变量的语句 
用的是mobx

**报错信息**

![image](https://user-images.githubusercontent.com/23191517/61197948-02343c00-a70a-11e9-9b89-538bfbac7a2e.png)

**Comment by yuche** [comment]
你需要把 JSX 也贴出来，单单这点内容也无法复现

**Comment by Jackliu007888** [comment]
因为包含一些业务代码  我一会单独建个能稳定复现的项目

**Comment by luckyadam** [comment]
请提供可以复现问题的 demo

**Comment by Jackliu007888** [comment]
@yuche @luckyadam 
https://github.com/Jackliu007888/taro-mobx-demo
