### ISSUE TITLE
findRef is not defined H5

### ISSUE THREAD

**Issue by chuyun** [NervJS/taro#3826]
![image](https://user-images.githubusercontent.com/19328403/61199257-d9af4080-a70f-11e9-878a-dc42c79d578b.png)

**Comment by luckyadam** [comment]
你自己检查一下 findRef 导出了没有，是怎么导出的

**Comment by chuyun** [comment]
> 你自己检查一下 findRef 导出了没有，是怎么导出的

this.$scope 传值的问题，已找到原因，thanks
