### ISSUE TITLE
编译支付宝小程序后，props为undefined

### ISSUE THREAD

**Issue by Yan-Hua** [NervJS/taro#3828]
![image](https://user-images.githubusercontent.com/33085588/61202009-ebe1ac80-a718-11e9-990a-819d21ac701a.png)
![image](https://user-images.githubusercontent.com/33085588/61202027-fd2ab900-a718-11e9-8eb0-15b9765de848.png)
这是编译后的报错和代码，propsManager为undefined，貌似是connect里的props都是undefined

**Comment by sunzitong** [comment]
我也遇到这个问题 请问如何解决的

**Comment by oracle11770** [comment]
我也遇到这个问题 请问如何解决的
