### ISSUE TITLE
事件处理函数命名bug

### ISSUE THREAD

**Issue by iisbigfish** [NervJS/taro#383]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
如果函数名字 /handleClickNavigateTo为这个时，编译报错。改变函数名字报错消失。
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
 // 处理函数
  handleClickNavigateTo (url) {
    console.log(url)
  }
组件里的 render 函数
render () {
<View className='head' onClick={this.handleClickNavigateTo.bind(this, 'item.url')}>test</View>
}

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

界面报错信息：
![image](https://user-images.githubusercontent.com/23730777/43215534-fd59b1a4-906e-11e8-812c-36da43f73d84.png)
控制台报错信息：
![image](https://user-images.githubusercontent.com/23730777/43215571-188766ba-906f-11e8-8d1f-05723d8b7eea.png)
**系统信息**

 - 操作系统: [MacOS]
 - Taro 版本 [v.0.0.72]
 - Node.js 版本 [v8.11.3]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
hello~ `handleClickNavigateTo ` 这个函数名过长了，导致超出了小程序的限制

**Comment by cheese-git** [comment]
同样遇到了类似的问题

希望能有相应的错误提示或写入文档，这种 bug 真的很难发现 😿
