### ISSUE TITLE
运行 `dev:rn` 无法唤起 `Metro Bundler`

### ISSUE THREAD

**Issue by quanzaiyu** [NervJS/taro#3830]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

运行 `yarn dev:rn`，项目成功编译，打包到`rn_temp`目录。但是，无法启动 `Metro Bundler`。

**复现步骤**
[复现问题的步骤]

1. 创建好项目后，运行 `yarn dev:rn`，ok，项目成功编译，打包到`rn_temp`目录。但是，无法启动 `Metro Bundler`。
2. 按照官方文档所述，部分电脑不会自动启动 `Metro Bundler`，于是，在项目根目录下运行 `react-native start`，ok， `Metro Bundler`成功启动了，截图如下：

![QQ截图20190715161025](https://user-images.githubusercontent.com/13745132/61202822-33693800-a71b-11e9-8701-ec612e8cba48.png)

3. 按照官方文档所述，克隆项目 `https://github.com/NervJS/taro-native-shell`，执行 `git clone git@github.com:NervJS/taro-native-shell.git`
4. 进入到 `taro-native-shell` 目录，运行 `react-native run-android`，截图如下：

![QQ截图20190715161227](https://user-images.githubusercontent.com/13745132/61202878-5dbaf580-a71b-11e9-8293-88d062a86f96.png)

5. 看样子已经成功连接到 `Metro Bundler`，模拟器有响应，但是 `Metro Bundler` 报错，如下：

```
error: bundling failed: ambiguous resolution: module `D:\Documents\Test\taroTest\rn_temp\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `D:\Documents\Test\taroTest\node_modules\react-native\package.json`
  * `D:\Documents\Test\taroTest\taro-native-shell\node_modules\react-native\package.json`

 BUNDLE  [android, dev] rn_temp/index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

截图如下：

![QQ截图20190715161312](https://user-images.githubusercontent.com/13745132/61202904-76c3a680-a71b-11e9-9d5d-6ba5fa543d21.png)

![QQ截图20190715161404](https://user-images.githubusercontent.com/13745132/61202961-9bb81980-a71b-11e9-9910-6a3362af965a.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

启动 `react-native run-android` 后，成功运行到模拟器

**报错信息**

```
error: bundling failed: ambiguous resolution: module `D:\Documents\Test\taroTest\rn_temp\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `D:\Documents\Test\taroTest\node_modules\react-native\package.json`
  * `D:\Documents\Test\taroTest\taro-native-shell\node_modules\react-native\package.json`

 BUNDLE  [android, dev] rn_temp/index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

```
$ taro info
👽 Taro v1.3.9


  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
```

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
非常详细的 issue，感谢反馈～

**Comment by Pines-Cheng** [comment]
require `react-native`, but there are several files providing this module.
项目中存在多个 react-native。
PS：不建议把 taro-native-shell  放在 Taro 项目下哦。
