### ISSUE TITLE
支付宝tabbar页内的组件不会执行生命周期

### ISSUE THREAD

**Issue by leeviok** [NervJS/taro#3831]
支付宝端，tabbar页面，在来回切换tab的时候，不会触发页面内组件的生命周期（show和hide事件），只会触发页面自身的生命周期

微信正常，页面和组件的生命周期都可以触发

taro版本：1.3.0

![微信截图_20190715161336](https://user-images.githubusercontent.com/25154944/61203352-b8088600-a71c-11e9-8154-89d1b7d39e8e.png)
![微信截图_20190715161218](https://user-images.githubusercontent.com/25154944/61203357-bb037680-a71c-11e9-99a6-621b0832798a.png)
![微信截图_20190715161844](https://user-images.githubusercontent.com/25154944/61203365-be96fd80-a71c-11e9-915f-1fa9801d483d.png)
![微信截图_20190715162045](https://user-images.githubusercontent.com/25154944/61203370-c22a8480-a71c-11e9-8fcc-4343f2ccb132.png)

**Comment by luckyadam** [comment]
你试试支付宝原生支不支持

**Comment by leeviok** [comment]
测试了一下原生，发现确实不支持。
支付宝原生的组件有着特殊的生命周期（didMount、didUpdate、didUnmount），和页面的生命周期不一样
没办法了，只有改代码了，支付宝小程序做起来太难受了。。
