### ISSUE TITLE
cloud.callFunction 的返回值应该是 any

### ISSUE THREAD

**Issue by crossjs** [NervJS/taro#3839]
cloud.callFunction 的返回值应该是 any，比如云端返回一个数组，那么 result 就是 any[]。

https://github.com/NervJS/taro/blob/master/packages/taro/types/index.d.ts#L11643

**Comment by luckyadam** [comment]
你可以提个 pr 看看

**Comment by jinjinjin0731** [comment]
不对。他不会是一个 any。  你云端返回一个数组。 result 会是一个  AnyObject 类型。 具体定义可以看下代码。

**Comment by crossjs** [comment]
> 不对。他不会是一个 any。 你云端返回一个数组。 result 会是一个 AnyObject 类型。 具体定义可以看下代码。

AnyObject 是 {}，不满足 [] 的情况

**Comment by crossjs** [comment]
> Hello~
> 
> 您的问题楼上已经有了确切的回答，如果没有更多的问题这个 issue 将在 15 天后被自动关闭。
> 
> 如果您在这 15 天中更新更多信息自动关闭的流程会自动取消，如有其他问题也可以发起新的 Issue。
> 
> Good luck and happy coding~

做个补充。

AnyObject 是 {}，不满足 [] 的情况。

比如，我这里返回的数组：
```ts
export const main = async ({ cate = "" }: any, context: any) => {
  const { data } = await db
    .collection("videos")
    .where({
      cate,
    })
    .get();

  // data 是 any[]，直接返回 data，而不是 data 的父对象。
  return data;
};
```

**Comment by jinjinjin0731** [comment]
@crossjs  注意看下文档哦~  [云开发](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-client-api/functions/callFunction.html)

> success返回参数/promise返回结果说明：
>-  errMsg 通用返回结果
>- result 云函数返回的结果
>- requestID 云函数执行 ID，可用于在控制台查找日志

他返回的会是一个对象。 至于你云函数返回的结果，是在这个对象内的 result 中获取

**Comment by crossjs** [comment]
> @crossjs 注意看下文档哦~ [云开发](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-client-api/functions/callFunction.html)
> 
> > success返回参数/promise返回结果说明：
> > 
> > * errMsg 通用返回结果
> > * result 云函数返回的结果
> > * requestID 云函数执行 ID，可用于在控制台查找日志
> 
> 他返回的会是一个对象。 至于你云函数返回的结果，是在这个对象内的 result 中获取

现在需要修改的就是 result 的类型声明，”这个对象内的 result“ 可以是任意值。

现在对应的行是
https://github.com/NervJS/taro/blob/master/packages/taro/types/index.d.ts#L11649

这里应该是 any

**Comment by crossjs** [comment]
再补充一个官方的：

https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-client-api/functions/callFunction.html

```js
success: res => {
    // output: res.result === 3
  },
```

你可以找到上述字符，这里 result 是个 number，所以，现在的实现是不对的。

**Comment by jinjinjin0731** [comment]
没错啊  `res.result` 是你云函数返回的数据。  `res` 返回的数据是  `{errMsg, result, requestID}`。  我定义返回类型 `AnyObject | string | undefined` 有什么问题吗？   AnyObject 的定义是  
```   
type AnyObject = {
      [x: string]: any
    }```

对应的返回值就是 any 。 也就是 `res.result` 或者 res 的其中一个 key 返回是一个  any 。  有什么问题吗？

**Comment by crossjs** [comment]
> 没错啊 `res.result` 是你云函数返回的数据。 `res` 返回的数据是 `{errMsg, result, requestID}`。 我定义返回类型 `AnyObject | string | undefined` 有什么问题吗？ AnyObject 的定义是
> 
> ```
> type AnyObject = {
>       [x: string]: any
>     }```
> 
> 对应的返回值就是 any 。 也就是 `res.result` 或者 res 的其中一个 key 返回是一个  any 。  有什么问题吗？
> ```

你就想如果我返回的 result === 3，现在的类型声明是否符合这个返回值就好了。
如果还认为没有问题，建议写段代码试试吧。

**Comment by Garfield550** [comment]
猜测 Issue 提问者的需求大概是 res.result 是 Number | String | Array | Object | undefined

它可以是
```js
res.result = 3
res.result = "Test message"
res.result = [1, 2, 3]
res.result = {
  data: "Test message",
  other: 3
}
```

**Comment by jinjinjin0731** [comment]
@crossjs @Garfield550   明白意思了。  @crossjs  你 PR 重新开一下 我合一下吧。   这个可以是 any 。 
这一写成 AnyObject ，我认为正常业务应该是一个  Object 。会包含 是否正常调用的状态码，以及返回数据。大概会是一个 ` {code: 200, data:{...}, errMsg} `这一样的返回数据

**Comment by crossjs** [comment]
> @crossjs @Garfield550 明白意思了。 @crossjs 你 PR 重新开一下 我合一下吧。 这个可以是 any 。
> 这一写成 AnyObject ，我认为正常业务应该是一个 Object 。会包含 是否正常调用的状态码，以及返回数据。大概会是一个 `{code: 200, data:{...}, errMsg}`这一样的返回数据

OK.

BTW, 云端返回的数据格式始终是 {code, result, eggMsg}
