### ISSUE TITLE
第三方开发平台配置文件ext.json需要复制到dist目录中

### ISSUE THREAD

**Issue by deepcoldy** [NervJS/taro#384]
**问题描述**
在开发第三方平台小程序时，需要在根目录配置ext.json。
目前只能在dist目录直接创建ext.json才能生效。
但是每次npm run dev都会删除dist目录，所以希望能支持从项目根目录或者src某处同步过去。

[相关腾讯文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/ext.html?t=2018724)

**Comment by luckyadam** [comment]
现在提供了 copy 配置，可以将文件 copy 至 dist 目录
https://nervjs.github.io/taro/config-detail.html#defineConstants

**Comment by jinyindu** [comment]
https://nervjs.github.io/taro/config-detail.html#defineConstants 打开是404

**Comment by foreverpw** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#copy
