### ISSUE TITLE
底层编辑器bug

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [NervJS/taro#3840]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> 
------------------------

**问题描述**
运行npm run build:weapp -- --watch 自动热更新,如果只修改.js文件,会自动编译,编译结束后导致CSS样式表丢失,必须再次保存一下CSS样式文件.

**复现步骤**
[复现问题的步骤]
1.运行 npm run build:weapp -- --watch启动项目
2. 修改项目中任何一个js文件
3.查看dist文件夹下,该组件/页面所对应的wxss文件
4.样式表丢失?

**期望行为**
不管修改js还是CSS样式表,自动编译的时候,修改结果需要同步.

**系统信息**
> 
 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [ 1.3.4 ]
 - Node.js 版本 [10.8.0]
 - 报错平台 [weapp]

**补充信息**

保存.js文件
![image](https://user-images.githubusercontent.com/24189898/61261695-30bb2100-a7b5-11e9-8149-61b8411973b2.png)
保存CSS文件
![image](https://user-images.githubusercontent.com/24189898/61261727-547e6700-a7b5-11e9-8f7f-80ea2913570b.png)

**备注:CSS指的是scss/less**

**Comment by Littly** [comment]
本地没有复现，可以用最新版本试试看。
