### ISSUE TITLE
快速dispatch redux actions情况下无法正确记录prevProps 导致shouldComponentUpdate返回结果不可靠

### ISSUE THREAD

**Issue by tmhenry** [NervJS/taro#3844]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
自己实现了shouldComponentUpdate去控制前端的重复渲染，但发现在快速连续dispatch action的时候shouldComponentUpdate总是返回false。看了taro/redux的代码，我猜想是因为prevProps的记录问题。

连续的dispatch action的时候，react的默认行为是将setState batch起来后统一处理，所以只会有一次重新渲染。但每次state变化的时候，prevProps都会变化，最终prevProps记录的是最后一次action执行之前的值，这样导致shouldComponentUpdate返回仅仅只依赖最后一次action对state的改变。

**复现步骤**
在redux-saga中连续派发action，观察connect到store的Component，shouldComponentUpdate智慧被调一次，同时prevProps记录的是最后一次action之前的值。

**期望行为**
多次连续派发action，只触发一次生命周期，但shouldComponentUpdate中传入的prevProps是所有action执行之前的props，而不是最后一个action之前的props。

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
 Taro CLI 1.3.0 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm

 - redux: ^4.0.0
 - redux-saga: ^1.0.3

**补充信息**
react-redux更新之后也有人在报这个issue，链接如下。react中虽然会batch这些setState，但prevProps传入的是正确的值。如果不手动控制shouldComponentUpdate，而是每一次都选择render的话，不会有这个问题。
https://github.com/reduxjs/react-redux/issues/1105

Taro代码中，我觉得是这一段导致了问题
![image](https://user-images.githubusercontent.com/170525/61264165-26e9eb80-a7be-11e9-928c-1515bfffdfd6.png)

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
