### ISSUE TITLE
this.$router.params在页面切换后未重置

### ISSUE THREAD

**Issue by daledelv** [NervJS/taro#3846]
**问题描述**
this.$router.params在页面切换后未重置

**复现步骤**
1.微信小程序，编译模式设置一个一级页面，带上参数，访问
2.用tabbar切换一级页面
3.切回到步骤一配置的页面时，参数仍存在，猜测因为一级页面再次切换时只触发了didshow

**期望行为**
this.$router.params应该在didshow时根据url重新获取

**报错信息**
如问题描述

**系统信息**
 - 操作系统: macOS 10.14.5
 - Taro 版本 1.3.5
 - Node.js 版本 10.8.0
 - 报错平台 weapp

**补充信息**
猜测因为一级页面再次切换时只触发了didshow

**Comment by Chen-jj** [comment]
@daledelv 不太明白，参数还在不是正确？

**Comment by daledelv** [comment]
@Chen-jj 按照底部栏配置好的固定链接，我swithTab回来的页面应该是不带携带参数，但是却保留了第一次访问这个页面时的参数，期望的行为是每次进入一个页面时，都重新从url上读参数

**Comment by Chen-jj** [comment]
@daledelv onShow 没有接受参数的，做不到帮你清，自己手动清吧。你写原生也一样，在 onLoad 把参数保存起来（taro 做的相当于这一步），tab 切换后回来还是要自己手动清。
