### ISSUE TITLE
小程序build 之后flex 失效

### ISSUE THREAD

**Issue by RainyNight9** [NervJS/taro#3849]
**问题描述**
[问题描述：就是在yarn dev:weapp的时候写的style，flex布局，看效果时正常，但是在yarn build:weapp之后，flex布局的 align-items:center; 失效，就是想知道是真的会有这个问题还是，build造成的？还是？]

**复现步骤**
[复现问题的步骤]
1. flex布局的 align-items:center; 失效
2. View 下边有一个 Image，给 View设置flex布局

```js
//  js代码，
<View className='type-img'>
                      <Image
                          className='t-img'
                          src={item.img}
                      />
                    </View>

css代码

                display:flex;
                justify-content: center;
                align-items:center;

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
[希望知道是什么原因造成的，有什么解决办法吗？还是需要换个方法实现？]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOs 10.13.6 ]
 - Taro 版本 [e.g. v.1.3.0]
 - Node.js 版本 [e.g. v10.15.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@RainyNight9 建议写个原生 demo 试试，Taro 应该不影响样式表现。
