### ISSUE TITLE
未做url decoded处理，导致this.$router.params解析错误

### ISSUE THREAD

**Issue by yushaoqin** [NervJS/taro#3851]
**问题描述**
未先对参数进行 url decode，导致 this.$router.params错误

**复现步骤**
[复现问题的步骤]
1. 编译模式中添加: path: pages/index/index , scene: p1%3D1%v16p2%3Dv2
2.页面中任意生命周期函数打印 this.$router.params

```js
import Taro,{ Component } from '@tarojs/taro';

// pages/index/index.jsx
export default class Index extends Component {
  componentDidMount() {
    // output: {"p1%3D1%v16p2%3Dv2" : ""}
    // expected: {p1 : "v1", p2 : "v2"}
    console.log(this.$router.params); 
  }

  render() {
    return <View />
  }
}
```

**期望行为**
以下方式都可以接受：
1. (best)先进行url decoded再进行参数解析，获取正确的this.$router.params
2. 提供获取weapp原生参数的途径

**报错信息**
无报错

**系统信息**
👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm

 - 操作系统:  mac
 - Taro 版本:  v1.3.0
 - Node.js 版本: v10.15.3
 - 报错平台:  weapp

**补充信息**

**Comment by yushaoqin** [comment]
补充：
仅在通过scene字段传参时出现此问题
（此时原生weapp是在 onLoad(options) 生命周期的 options.scene字段获取到参数 e.g. options.scene='p1%3Dv1%26p2%3Dv2'）
此时应先对该参数进行decode，再进行params的解析。

**Comment by Chen-jj** [comment]
@yushaoqin 场景值怎么设置的，为什么会被 encode

**Comment by hnliyuan** [comment]
> �补充：
> 仅在通过scene字段传参时出现此问题
> （此时原生weapp是在 onLoad(options) 生命周期的 options.scene字段获取到参数 e.g. options.scene='p1%3Dv1%26p2%3Dv2'）
> 此时应先对该参数进行decode，再进行params的解析。
请问一下，开发环境如何模拟该场景？

**Comment by yushaoqin** [comment]
抱歉，经测试发现是使用方式错误。
Taro是将微信小程序原生生命周期函数 onLoad中的参数作为Taro中 this.$router.params透传。(正确行为)

以下两个场景：
a. 通过微信小程序服务端接口： wxacode.get 生成二维码， 页面参数直接作为该接口 path 参数中的query部分传递。 e.g.path =  "pages/index/index?p1=v1"
--- Taro中通过 this.$router.params.p1读取到 "v1"

2.通过微信小程序服务端接口：wxacode.getUnlimited 生成二维码，页面参数作为该接口 scene参数。 
e.g. page = "pages/index/index", scene = "p1=v1"
-- Taro中通过 this.$router.params.scene读取到 "p1%3Dv1" （encode行为是小程序行为）
