### ISSUE TITLE
【taroize】v1.3.9  taro convert转换小程序项目出错

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3852]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 在小程序项目中执行taro convert
2. 报错，转换失败

为了验证是否是自己项目问题，有特意找了之前转换没问题的小程序官方组件[navigator](https://developers.weixin.qq.com/miniprogram/dev/component/navigator.html)
同样是转换出错，同样的报错内容

![image](https://user-images.githubusercontent.com/13342245/61283879-67625d00-a7f0-11e9-9a82-e937097a1594.png)

**期望行为**
[正常转换]

**报错信息**
上图已展示

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.9]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
最新版本已修复
