### ISSUE TITLE
【全链路转换，策略问题】微信小程序->taro->h5 ，运行报错

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3854]
**问题描述**
[问题描述：现在的场景是微信小程序转换为taro，再转换为H5，然后运行报错]

**复现步骤**
[复现问题的步骤]
1. 微信小程序项目中执行taro convert
2. 进入taroConvert目录,安装依赖&修改配置，npm run dev:h5，转换成H5
3. 报错

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.eval (util.js?3bbf:52)
    at eval (util.js:59)
    at Module../.temp/utils/util.js (app.js:1071)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (app.js?d0a8:27)
    at Module../.temp/app.js (app.js:915)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at Object.0 (app.js:3864)
```
![image](https://user-images.githubusercontent.com/13342245/61286411-5cf69200-a7f5-11e9-85ef-e25c2425c7b0.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.9]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
按照报错，查找问题缘由，找到webpack官方已经关闭的一个[issue](https://github.com/webpack/webpack/issues/4039)
意思就是，模块内，import和module.exports混用导致这个错误
然后使用taro转换产生这个问题的原因就是：
taroize转换小程序过程中，都会在模块内通过import引入依赖的，例如
```
import Taro from '@tarojs/taro'
import withWeapp from '@tarojs/with-weapp'
```
而写微信小程序的时候，不少用户还是习惯用微信小程序最先支持的commonjs规范，用require和module.exports；所以在一个模块中就很容易出现；
然后，taroize在转换过程中对这些是不做处理的，在taro再转h5的过程，webpack就报错了
我现在在本地的处理方法是，在taroize之后，做了个中间层，把文件中的require和module.exports都替换成es6的import和export default了，感觉有些硬
希望官方能给出更优雅的解决方案

**Comment by caipenga** [comment]
> **问题描述**
> [问题描述：现在的场景是微信小程序转换为taro，再转换为H5，然后运行报错]
> 
> **复现步骤**
> [复现问题的步骤]
> 
> 1. 微信小程序项目中执行taro转换
> 2. 进入taroConvert目录，安装依赖和修改配置，npm run dev：h5，转换成H5
> 3. 报错
> 
> **期望行为**
> [这里请用简洁清晰的语言描述你期望的行为]
> 
> **报错信息**
> 
> ```
> Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
>     at Module.eval (util.js?3bbf:52)
>     at eval (util.js:59)
>     at Module../.temp/utils/util.js (app.js:1071)
>     at __webpack_require__ (app.js:767)
>     at fn (app.js:130)
>     at eval (app.js?d0a8:27)
>     at Module../.temp/app.js (app.js:915)
>     at __webpack_require__ (app.js:767)
>     at fn (app.js:130)
>     at Object.0 (app.js:3864)
> ```
> 
> ![图片](https://user-images.githubusercontent.com/13342245/61286411-5cf69200-a7f5-11e9-85ef-e25c2425c7b0.png)
> 
> **系统信息**
> 
> > Taro v1.2及更高版本已添加`taro info`命令，方便大家查看系统及依赖信息，运行该命令后将结果粘贴下面即可。
> 
> * 操作系统：[macOS 10.14.5]
> * 芋头版[v1.3.9]
> * Node.js版本[12.4.0]
> * 报错平台[h5，weapp]
> 
> **补充信息**
> [任选]
> 按照报错，发现问题缘由，找到webpack官方已经关闭的一个[问题](https://github.com/webpack/webpack/issues/4039)
> 意思就是，模块内，import和module.exports混用导致这个错误
> 然后使用taro转换产生这个问题的原因就是：
> taroize转换小程序过程中，都会在模块内通过import♡依赖的，例如
> 
> ```
> import Taro from '@tarojs/taro'
> import withWeapp from '@tarojs/with-weapp'
> ```
> 
> 而写微信小程序的时候，大量用户还是习惯用微信小程序最先支持的commonjs规范，用require和module.exports；所以在一个模块中就很容易出现；
> 然后，taroize在转换过程中对这些是不做处理的，在taro再转h5的过程，webpack就报错了
> 我现在在本地的处理方法是，在taroize之后，做成一个中间层，把文件中的要求和module.exports都替换成es6的进口和出口违约了，感觉有些硬
> 希望官方能指出更优雅的解决方案

遇到同样的问题

**Comment by Chen-jj** [comment]
手动修复吧

**Comment by kevinroy-lo** [comment]
@loosenRogers 请问这个问题后来怎么解决了。
