### ISSUE TITLE
navigateTo 被打开页面调用this.getOpenerEventChannel()报错

### ISSUE THREAD

**Issue by zcc19910524** [NervJS/taro#3856]
使用Taro.navigateTo跳转 被打开的界面 this. getOpenerEventChannel is not a function

**Comment by yuche** [comment]
报什么错，怎么复现，你这两行字完全没看懂

**Comment by zcc19910524** [comment]
> 报什么错，怎么复现，你这两行字完全没看懂

被打开的界面 this. getOpenerEventChannel is not a function

**Comment by yuche** [comment]
哪个平台

**Comment by zcc19910524** [comment]
> 哪个平台

微信小程序

**Comment by Chen-jj** [comment]
@zcc19910524 请按 issue 模板提供一切必要信息。

**Comment by zcc19910524** [comment]
> @zcc19910524 请按 issue 模板提供一切必要信息。
问题描述
Taro.navigateTo方法 传入 events参数 在被打开的界面 this对象 没有getOpenerEventChannel方法
可以参考 文档页面 https://nervjs.github.io/taro/docs/apis/interface/navigation/navigateTo.html#docsNav
https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.navigateTo.html

复现步骤
A.jsx: 
`
Taro.navigateTo({
  url: `../B/index?type=${type}`,
     events: {
        acceptDataFromOpenedPage: (data) => {
         console.log(data)
         },
        }
      })
`
B.jsx
`
const eventChannel = this.getOpenerEventChannel()
`
this对象中没有getOpenerEventChannel方法

报错信息
this.getOpenerEventChannel is not a function

系统信息

Taro CLI 1.3.8 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - ~/.nvm/versions/node/v8.9.1/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v8.9.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.8 => 1.3.8
      @tarojs/components: 1.3.8 => 1.3.8
      @tarojs/plugin-babel: 1.3.8 => 1.3.8
      @tarojs/plugin-csso: 1.3.8 => 1.3.8
      @tarojs/plugin-less: 1.3.8 => 1.3.8
      @tarojs/plugin-sass: 1.3.8 => 1.3.8
      @tarojs/plugin-uglifyjs: 1.3.8 => 1.3.8
      @tarojs/redux: 1.3.8 => 1.3.8
      @tarojs/redux-h5: 1.3.8 => 1.3.8
      @tarojs/router: 1.3.8 => 1.3.8
      @tarojs/taro: 1.3.8 => 1.3.8
      @tarojs/taro-alipay: 1.3.8 => 1.3.8
      @tarojs/taro-h5: 1.3.8 => 1.3.8
      @tarojs/taro-swan: 1.3.8 => 1.3.8
      @tarojs/taro-tt: 1.3.8 => 1.3.8
      @tarojs/taro-weapp: 1.3.8 => 1.3.8
      @tarojs/webpack-runner: 1.3.8 => 1.3.8
      eslint-config-taro: 1.3.8 => 1.3.8
      eslint-plugin-taro: 1.3.8 => 1.3.8
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3

**Comment by Chen-jj** [comment]
@zcc19910524 使用 `this.$scope.getOpenerEventChannel`，因为 this.$scope 才是原生小程序的页面或组件实例。

**Comment by Chen-jj** [comment]
@zcc19910524 之后会把 this.$scope 的这些特殊方法挂 this 上。

**Comment by smallwebbird** [comment]
现在在模拟器上用这个方法可以，但是在手机上测试是不好用的，第一在navigateTo的success回调中res根本没有eventChannle字段，在手机上打印的log如下
![image](https://user-images.githubusercontent.com/28871189/69495176-fa2da980-0efe-11ea-8163-df3a4a3e4f93.png)
其二就是在被打开的页面中也没有getOpenerEventChannel方法

**Comment by yhchlixia** [comment]
不知道是不是版本的原因，我用的是2.10.4，然后在this.$mp.page里面找到了getOpenerEventChannel方法，使用this.$mp.page.getOpenerEventChannel()就没问题了（真的是找了很久）

**Comment by WAWZ** [comment]
是的，wepy 同理， this.getOpenerEventChannel 改成 this.$wx.getOpenerEventChannel() 就解决啦

**Comment by Chen-jj** [comment]
Taro3 没有 this.$scope 的概念了。

**Comment by Murphycx94** [comment]
> Taro3 没有 this.$scope 的概念了。

Taro3怎么使用getOpenerEventChannel方法？

**Comment by Chen-jj** [comment]
@Murphycx94 不需要用这个，可以直接用 [Taro Event](https://nervjs.github.io/taro/docs/apis/about/events)

**Comment by huaoguo** [comment]
@Chen-jj https://huaoguo.github.io/taro/2020/11/11/taro3-page-event.html
Taro Event 无法很好的应对这个场景啊

**Comment by huaoguo** [comment]
@Chen-jj 发现 navigateTo 的 success 回调时机在真机和模拟器不同，真机是在 constructor、componentWillMount、componentDidMount 运行完后，success 才执行，模拟器不是。

**Comment by cuiyajie** [comment]
Taro3 删除了获得小程序页面对象的方法之后，感觉好多功能都不能使用了，比如channel的使用。另外Taro3提供的eventCenter在页面挑转成功后触发事件，可能在跳转后的页面还没有注册监听事件。

**Comment by SilentFlute** [comment]
win10
`taro`: `3.2.9`
`react`: `17.0.0`
`微信开发者工具`: `Stable 1.05.2106250`

A页面:

```
const pid = '0118999';

Taro.navigateTo({
  url: `/pages/index/articleInfo?pid=${pid}`,
  success() {
    console.log('success');
    Taro.eventCenter.once(`pageInit:${pid}`, () => {
      Taro.eventCenter.trigger(
        `myEvent:${pid}`,
        {
          title: '这是一个标题',
          content: '这是一段内容这是一段内容这是一段内容'
        }
      )
    });
  }
});
```
B页面:

```
class ArticleInfo extends Component {

  constructor(props) {
    console.log('constructor');
    super(props);
    this.state = {
      loading: true,
      data: {}
    }
    const { pid } = getCurrentInstance().router.params;
    Taro.eventCenter.once(`myEvent:${pid}`, data => {
      console.log(`myEvent:${pid}`);
      this.setState({
        loading: false,
        data
      })
    });
  }

  UNSAFE_componentWillMount() {
    console.log('UNSAFE_componentWillMount');
  }

  componentDidMount() {
    console.log('componentDidMount');
    setTimeout(
      () => {
        const { pid } = getCurrentInstance().router.params;
        Taro.eventCenter.trigger(`pageInit:${pid}`);
      },
      5
    )
  }

  render() {
    console.log('render');
    const { loading, data } = this.state;
    const { title, content } = data;

    if(loading) {
      return (
        <View>loading...</View>
      )
    }

    return (
      <View>
        <View className='title'>
          {title}
        </View>
        <View className='detail'>
          {content}
        </View>
      </View>
    )
  }
}
```
微信开发者工具:

A页面`success`先执行, 然后再进到B页面的各生命周期中:

1. success
2. constructor
3. UNSAFE_componentWillMount
4. render
5. componentDidMount

真机调试:

先执行B页面的各声明周期, 最后才执行A页面的`success`:

1. constructor
2. UNSAFE_componentWillMount
3. render
4. componentDidMount
5. success

以及开发者工具和真机环境最后都会再打印两行: 

`myEvent:0118999`和`render`, 这是因为我们`setState`之后导致页面`re-render`

这里的关键的地方在于: 事件的监听要在触发之前!

真机调试时候`success`最后执行, 而在之前`componentDidMount`中就先触发了事件, 那`success`中监听事件就会监听不到, 因此需要延迟一下

**Comment by SilentFlute** [comment]
当然了, 这个方式其实还是挺繁琐的, 最简便的方式还是使用`查询字符串`的方式传参:

```
const finalItem = JSON.stringify(item);

Taro.navigateTo({
  url: `../articleInfo/index?data=${finalItem}`
})
```
```
const { data } = getCurrentInstance().router.params;
const { title, content } = JSON.parse(data);

return (
  <View>
    <View className='title'>
      {title}
    </View>
    <View className='detail'>
      {content}
    </View>
  </View>
)
```
或者如果项目中使用了`redux` `dva`, 那可以通过`redux` `dva`的形式来传递数据, 从而完成跨页面通信

**Comment by light212** [comment]
Taro.getCurrentInstance().page.getOpenerEventChannel()

**Comment by luabuCN** [comment]
useLoad((option) => {
    console.log(option, '当前参数')

    if (process.env.TARO_ENV === 'weapp') {
      const pages = getCurrentPages()
      const current = pages[pages.length - 1]
      const eventChannel = current.getOpenerEventChannel()
      // 监听acceptDataFromOpenerPage事件，获取上一页面通过eventChannel传送到当前页面的数据
      eventChannel.on('acceptDataFromOpenerPage', function (data: any) {
        console.log(data, '传递过来的数据')
      })
    }
  })
