### ISSUE TITLE
是否支持小程序分包加载

### ISSUE THREAD

**Issue by yuzexing** [NervJS/taro#386]
**问题描述**
小程序端是否支持分包加载功能?

https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages.html?search-key=%E5%88%86%E5%8C%85%E5%8A%A0%E8%BD%BD

**Comment by zhuchuanwu** [comment]
同问，如果不支持，基本就没有考虑的必要了

**Comment by luckyadam** [comment]
现在不支持，后面就不能开发了么。。。

**Comment by yuzexing** [comment]
这回答一点都不官方...

**Comment by luckyadam** [comment]
分包加载已支持，下个版本发布~
9bb3e986708a4e5cb23553be96da1492f2f386e6

**Comment by luckyadam** [comment]
分包支持版本已发布
