### ISSUE TITLE
Taro.request不能直接请求一个string url

### ISSUE THREAD

**Issue by moonreplace** [NervJS/taro#3864]
**问题描述**
Taro.request直接请求一个url地址会报错
Taro.request('http://api'), 报错

**复现步骤**
任意使用Taro.request直接请求一个地址都会报错

```js
Taro.request('http://api')
```

**期望行为**
和1.2保持一致，可以正常请求

**报错信息**

TypeError: Cannot read property 'replace' of undefined
    at generateRequestUrlWithParams (index.js?3a5f:11)
    at _request (index.js?3a5f:52)
    at taroInterceptor (index.js?3a5f:104)
    at Chain.proceed (index.esm.js?5f9d:1587)
    at Link.request (index.esm.js?5f9d:1620)
    at getServerTime (server.js?311f:4)
    at eval (serverTime.js?65e0:11)

**系统信息**

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.10.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.2 => 1.3.2
      @tarojs/cli: ^1.3.2 => 1.3.2
      @tarojs/components: ^1.3.2 => 1.3.2
      @tarojs/mobx: ^1.3.2 => 1.3.2
      @tarojs/mobx-h5: ^1.3.2 => 1.3.2
      @tarojs/plugin-babel: ^1.3.2 => 1.3.2
      @tarojs/plugin-csso: ^1.3.2 => 1.3.2
      @tarojs/plugin-sass: ^1.3.2 => 1.3.2
      @tarojs/plugin-uglifyjs: ^1.3.2 => 1.3.2
      @tarojs/router: ^1.3.2 => 1.3.2
      @tarojs/taro: ^1.3.2 => 1.3.2
      @tarojs/taro-h5: ^1.3.2 => 1.3.2
      @tarojs/taro-weapp: ^1.3.2 => 1.3.2
      @tarojs/webpack-runner: ^1.3.2 => 1.3.2
      eslint-config-taro: ^1.3.2 => 1.3.2
      eslint-plugin-taro: ^1.3.2 => 1.3.2
      nervjs: ^1.4.3 => 1.4.3
      react: ^16.7.0 => 16.7.0
**补充信息**
大体看了一下，应该是url, string被变成了一个字符object

**Comment by Chen-jj** [comment]
@moonreplace 开发前请看[文档](https://nervjs.github.io/taro/docs/apis/network/request/request.html)
