### ISSUE TITLE
1.3.9微信小程序使用useContext报错Store is not defined

### ISSUE THREAD

**Issue by xuedingesmiao** [NervJS/taro#3865]
**问题描述**
1.3.9微信小程序使用useContext报错Store is not defined
![image](https://user-images.githubusercontent.com/25097637/61356645-5d506500-a8a9-11e9-8d5e-512d3e447c8c.png)
![image](https://user-images.githubusercontent.com/25097637/61356673-6b9e8100-a8a9-11e9-9029-ebb9ba19b61a.png)

**复现步骤**
相关代码如下
父组件代码
```js
import Taro, { useReducer } from '@tarojs/taro';
import Count from './Count';
import Step from './Step';

export const Store = Taro.createContext(null);

function reducer(state, action) {
  switch (action) {
    case 'incCount':
      state.count++;
      return state;
    case 'incStep':
      state.step++;
      return state;
    default:
      return state;
  }
}

function Parent() {
  const [state, dispatch] = useReducer(reducer, { count: 0, step: 0 });
  return (
    <Store.Provider value={{ state, dispatch }}>
      <Count />
      <Step />
    </Store.Provider>
  );
}

export default Parent;
```

子组件代码
```js
import Taro, { useReducer, useContext, useMemo } from '@tarojs/taro';
import { Button } from '@tarojs/components';
import { Store } from './index';

function Count() {
  const { state, dispatch } = useContext(Store);
  const CountMemo = useMemo(
    () => (
      <Button onClick={() => dispatch('incCount')}>
        incCount {state.count}
      </Button>
    ),
    [state.count, dispatch]
  );
  return <CountMemo />;
}

export default Count;

```

```js
import Taro, { useReducer, useContext, useMemo } from '@tarojs/taro';
import { Button } from '@tarojs/components';
import { Store } from './index';

function Step() {
  const { state, dispatch } = useContext(Store);
  const StepMemo = useMemo(
    () => (
      <Button onClick={() => dispatch('incStep')}>incStep {state.step}</Button>
    ),
    [state.step, dispatch]
  );
  return <StepMemo />;
}

export default Step;

```
在h5下页面行为是正常的
![image](https://user-images.githubusercontent.com/25097637/61357060-23cc2980-a8aa-11e9-928f-3f8974dcdb6f.png)
微信开发工具中在报错的文件中搜索Store如图
![image](https://user-images.githubusercontent.com/25097637/61357297-8b827480-a8aa-11e9-9739-d3292c5a4dd0.png)

感觉是在编译为小程序的过程中
```js
import { Store } from './index';
```
这句代码被莫名的干掉了

**期望行为**
希望useContext小程序下能够正常使用

 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.9]
 - Node.js 版本 [10.16.0 ]
 - 报错平台 [ weapp]

**Comment by yuche** [comment]
你这个 `Store` 单独放到一个没有 JSX 的文件试试看

**Comment by xuedingesmiao** [comment]
@yuche
Store单独放文件夹问题解决了，但是又碰上新问题了，useMemo小程序下无法正常渲染，页面空白，h5下是正常的
![image](https://user-images.githubusercontent.com/25097637/61425944-32b6e880-a94b-11e9-8442-24fb07a2fd32.png)
![image](https://user-images.githubusercontent.com/25097637/61425977-5712c500-a94b-11e9-81dd-8026065438b1.png)

**Comment by yuche** [comment]
不要说结果，说过程

**Comment by xuedingesmiao** [comment]
过程就是我把store单独放置了，store的问题解决了，子组件中能够获得store的状态，但是子组件中useMemo包裹的button小程序没有加载，相同的代码h5下button是能够显示的，我想是不是taro小程序对useMemo的处理有问题
```js
function Count() {
  const { state, dispatch } = useContext(Store); // Store不再是not defined
  const CountMemo = useMemo(
    () => (
      <Button onClick={() => dispatch('incCount')}> //此button小程序下无法加载
        incCount {state.count}
      </Button>
    ),
    [state.count, dispatch]
  );
  return <CountMemo />;
}

```

**Comment by yuche** [comment]
Taro 的 JSX 是没办法当做一个变量处理的，所以所有 hooks 里都没办法传入和返回 JSX，你这个情况应该考虑使用 `Taro.memo` API。
