### ISSUE TITLE
1.3.9 开启TypeScript后，编译直接报错

### ISSUE THREAD

**Issue by lnstock** [NervJS/taro#3866]
**问题描述**
√ 拉取远程模板仓库成功！
? 请输入项目介绍！
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板

**复现步骤**
npm run build:h5

**报错信息**
找不到项目配置文件config/index.js，请确定当前目录是Taro项目根目录!

我看到项目下config里确实没有 index.js，只有index.ts

**Comment by lichking666** [comment]
遇到了同样的问题

**Comment by jiangchangzzz** [comment]
也碰到这个问题了，修改文件名index.ts为index.js可以解决

**Comment by xlelou** [comment]
遇到同样问题 怎么解决的

**Comment by Garfield550** [comment]
你好，没有复现，尝试重新安装一下 @tarojs/cli？

```shell
~/Projects/Me> /Users/name/Projects/Test/taro/packages/taro-cli/bin/taro init new-project-typescript
👽 Taro v1.3.9

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ new-project-typescript
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板

✔ 创建项目: new-project-typescript
✔ 创建文件: new-project-typescript/global.d.ts
✔ 创建文件: new-project-typescript/package.json
✔ 创建文件: new-project-typescript/project.config.json
✔ 创建文件: new-project-typescript/tsconfig.json
✔ 创建文件: new-project-typescript/config/dev.js
✔ 创建文件: new-project-typescript/config/index.js
✔ 创建文件: new-project-typescript/config/prod.js
✔ 创建文件: new-project-typescript/src/app.scss
✔ 创建文件: new-project-typescript/src/app.tsx
✔ 创建文件: new-project-typescript/src/index.html
✔ 创建文件: new-project-typescript/src/pages/index/index.scss
✔ 创建文件: new-project-typescript/src/pages/index/index.tsx

✔ cd new-project-typescript, 执行 git init
⠴ 执行安装项目依赖 yarn install, 需要一会儿...^C
~/Projects/Me> ls -al ./new-project-typescript/config/
total 24
drwxr-xr-x  5 name  staff   160 Jul 18 13:13 .
drwxr-xr-x  9 name  staff   288 Jul 18 13:13 ..
-rw-r--r--  1 name  staff   113 Jul 18 13:13 dev.js
-rw-r--r--  1 name  staff  2217 Jul 18 13:13 index.js
-rw-r--r--  1 name  staff   424 Jul 18 13:13 prod.js


~/Projects/Me> npx @tarojs/cli@1.3.9 init new-project-typescript-npx
👽 Taro v1.3.9

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ new-project-typescript-npx
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板

✔ 创建项目: new-project-typescript-npx
✔ 创建文件: new-project-typescript-npx/global.d.ts
✔ 创建文件: new-project-typescript-npx/package.json
✔ 创建文件: new-project-typescript-npx/project.config.json
✔ 创建文件: new-project-typescript-npx/tsconfig.json
✔ 创建文件: new-project-typescript-npx/config/dev.js
✔ 创建文件: new-project-typescript-npx/config/index.js
✔ 创建文件: new-project-typescript-npx/config/prod.js
✔ 创建文件: new-project-typescript-npx/src/app.scss
✔ 创建文件: new-project-typescript-npx/src/app.tsx
✔ 创建文件: new-project-typescript-npx/src/index.html
✔ 创建文件: new-project-typescript-npx/src/pages/index/index.scss
✔ 创建文件: new-project-typescript-npx/src/pages/index/index.tsx

✔ cd new-project-typescript-npx, 执行 git init
⠼ 执行安装项目依赖 yarn install, 需要一会儿...^C^C^C
~/Projects/Me> ls -al ./new-project-typescript-npx/config/
total 24
drwxr-xr-x  5 name  staff   160 Jul 18 13:16 .
drwxr-xr-x  9 name  staff   288 Jul 18 13:16 ..
-rw-r--r--  1 name  staff   113 Jul 18 13:16 dev.js
-rw-r--r--  1 name  staff  2221 Jul 18 13:16 index.js
-rw-r--r--  1 name  staff   424 Jul 18 13:16 prod.js
```

**Comment by luckyadam** [comment]
> 你好，没有复现，尝试重新安装一下 @tarojs/cli？
> 
> ```shell
> ~/Projects/Me> /Users/name/Projects/Test/taro/packages/taro-cli/bin/taro init new-project-typescript
> 👽 Taro v1.3.9
> 
> Taro即将创建一个新项目!
> Need help? Go and open issue: https://github.com/NervJS/taro/issues/new
> 
> ✔ 拉取远程模板仓库成功！
> ? 请输入项目介绍！ new-project-typescript
> ? 是否需要使用 TypeScript ？ Yes
> ? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
> ? 请选择模板 默认模板
> 
> ✔ 创建项目: new-project-typescript
> ✔ 创建文件: new-project-typescript/global.d.ts
> ✔ 创建文件: new-project-typescript/package.json
> ✔ 创建文件: new-project-typescript/project.config.json
> ✔ 创建文件: new-project-typescript/tsconfig.json
> ✔ 创建文件: new-project-typescript/config/dev.js
> ✔ 创建文件: new-project-typescript/config/index.js
> ✔ 创建文件: new-project-typescript/config/prod.js
> ✔ 创建文件: new-project-typescript/src/app.scss
> ✔ 创建文件: new-project-typescript/src/app.tsx
> ✔ 创建文件: new-project-typescript/src/index.html
> ✔ 创建文件: new-project-typescript/src/pages/index/index.scss
> ✔ 创建文件: new-project-typescript/src/pages/index/index.tsx
> 
> ✔ cd new-project-typescript, 执行 git init
> ⠴ 执行安装项目依赖 yarn install, 需要一会儿...^C
> ~/Projects/Me> ls -al ./new-project-typescript/config/
> total 24
> drwxr-xr-x  5 name  staff   160 Jul 18 13:13 .
> drwxr-xr-x  9 name  staff   288 Jul 18 13:13 ..
> -rw-r--r--  1 name  staff   113 Jul 18 13:13 dev.js
> -rw-r--r--  1 name  staff  2217 Jul 18 13:13 index.js
> -rw-r--r--  1 name  staff   424 Jul 18 13:13 prod.js
> 
> 
> ~/Projects/Me> npx @tarojs/cli@1.3.9 init new-project-typescript-npx
> 👽 Taro v1.3.9
> 
> Taro即将创建一个新项目!
> Need help? Go and open issue: https://github.com/NervJS/taro/issues/new
> 
> ✔ 拉取远程模板仓库成功！
> ? 请输入项目介绍！ new-project-typescript-npx
> ? 是否需要使用 TypeScript ？ Yes
> ? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
> ? 请选择模板 默认模板
> 
> ✔ 创建项目: new-project-typescript-npx
> ✔ 创建文件: new-project-typescript-npx/global.d.ts
> ✔ 创建文件: new-project-typescript-npx/package.json
> ✔ 创建文件: new-project-typescript-npx/project.config.json
> ✔ 创建文件: new-project-typescript-npx/tsconfig.json
> ✔ 创建文件: new-project-typescript-npx/config/dev.js
> ✔ 创建文件: new-project-typescript-npx/config/index.js
> ✔ 创建文件: new-project-typescript-npx/config/prod.js
> ✔ 创建文件: new-project-typescript-npx/src/app.scss
> ✔ 创建文件: new-project-typescript-npx/src/app.tsx
> ✔ 创建文件: new-project-typescript-npx/src/index.html
> ✔ 创建文件: new-project-typescript-npx/src/pages/index/index.scss
> ✔ 创建文件: new-project-typescript-npx/src/pages/index/index.tsx
> 
> ✔ cd new-project-typescript-npx, 执行 git init
> ⠼ 执行安装项目依赖 yarn install, 需要一会儿...^C^C^C
> ~/Projects/Me> ls -al ./new-project-typescript-npx/config/
> total 24
> drwxr-xr-x  5 name  staff   160 Jul 18 13:16 .
> drwxr-xr-x  9 name  staff   288 Jul 18 13:16 ..
> -rw-r--r--  1 name  staff   113 Jul 18 13:16 dev.js
> -rw-r--r--  1 name  staff  2221 Jul 18 13:16 index.js
> -rw-r--r--  1 name  staff   424 Jul 18 13:16 prod.js
> ```

windows 下有此问题，下个版本修复😂

**Comment by luckyadam** [comment]
Duplicate of #3880

**Comment by Garfield550** [comment]
> windows 下有此问题，下个版本修复😂

Issue 描述没有提到具体运行环境，所以在 macOS 上测的。给大家造成误解真是抱歉。

**Comment by xlelou** [comment]
..我说怎么重装了一边还是不行呢

**Comment by Yongest** [comment]
> Duplicate of #3880

真没想到这么一个低级错误也会犯，发布前都不要测试的吗？还那么多人的一个凹凸实验室，

> Duplicate of #3880
