### ISSUE TITLE
H5中, 注入mobx的组件,this.props.children属性为空数组

### ISSUE THREAD

**Issue by ZenoZhengs** [NervJS/taro#3870]
**问题描述**
Taro项目编译成H5时,注入mobx的组件获取不到children子组件,打印this.props.children=[]

**复现步骤**

Index.tsx
```js
type PageStateProps = {
  counterStore: ICounterStore
}

type PageOwnProps = {

}

@inject(stores => ({
  counterStore: stores.counterStore as ICounterStore,
}))
@observer
class Index extends Component<PageStateProps & PageOwnProps> {

  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillReact () {
    console.log('componentWillReact')
  }

  increment = () => {
    const { counterStore } = this.props
    counterStore.increment()
  }

  decrement = () => {
    const { counterStore } = this.props
    counterStore.decrement()
  }

  incrementAsync = () => {
    const { counterStore } = this.props
    counterStore.incrementAsync()
  }

  render () {
    const { counterStore: { counter } } = this.props
    return (
      <View>
        <Button onClick={this.increment}>+</Button>
        <Button onClick={this.decrement}>-</Button>
        <Button onClick={this.incrementAsync}>Add Async</Button>
        <Text>{counter}</Text>
        <Dialog>
          <View className="dialog-message">
            Thank you for using Taro.
          </View>
        </Dialog>
      </View>
    )
  }
}

export default Index  as ComponentClass<PageOwnProps>

```

Dialog.tsx
```js
import { ComponentClass } from 'react'
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { inject, observer } from '@tarojs/mobx'

import { ICounterStore } from '../../stores/counter'

type PageStateProps = {
  counterStore: ICounterStore
}

@inject(stores => ({
  counterStore: stores.counterStore as ICounterStore
}))
@observer
class Dialog extends Component<PageStateProps> {
  render () {
    const { counterStore: { counter } } = this.props
    console.log(this.props.children)
    return (
      <View className='dialog'>
        <View className='header'>Welcome!</View>
        <View>{`counter in dialog: ${counter}`}</View>
        <View className='body'>
          { this.props.children }
        </View>
        <View className='footer'>-- divider --</View>
      </View>
    )
  }
}

export default Dialog as ComponentClass<{}>
```

**期望行为**
H5能够正常显示

**报错信息**
<img width="866" alt="Screen Shot 2019-07-17 at 23 36 37" src="https://user-images.githubusercontent.com/45112245/61392288-0bcbc880-a8f1-11e9-96e3-2e550ad93563.png">

**系统信息**
  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.9 => 1.3.9 
      @tarojs/mobx: 1.3.9 => 1.3.9 
      @tarojs/mobx-h5: 1.3.9 => 1.3.9 
      @tarojs/mobx-rn: 1.3.9 => 1.3.9 
      @tarojs/plugin-babel: 1.3.9 => 1.3.9 
      @tarojs/plugin-csso: 1.3.9 => 1.3.9 
      @tarojs/plugin-sass: 1.3.9 => 1.3.9 
      @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9 
      @tarojs/rn-runner: 1.3.9 => 1.3.9 
      @tarojs/router: 1.3.9 => 1.3.9 
      @tarojs/taro: 1.3.9 => 1.3.9 
      @tarojs/taro-alipay: 1.3.9 => 1.3.9 
      @tarojs/taro-h5: 1.3.9 => 1.3.9 
      @tarojs/taro-swan: 1.3.9 => 1.3.9 
      @tarojs/taro-tt: 1.3.9 => 1.3.9 
      @tarojs/taro-weapp: 1.3.9 => 1.3.9 
      @tarojs/webpack-runner: 1.3.9 => 1.3.9 
      eslint-config-taro: 1.3.9 => 1.3.9 
      eslint-plugin-taro: 1.3.9 => 1.3.9 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.5.2

**Comment by ZenoZhengs** [comment]
**补充**
H5下,只要组件注入mobx,父组件赋给子组件所有的props属性值都为空

**Comment by nanjingboy** [comment]
@ZenoZhengs https://github.com/NervJS/taro/pull/3877 感谢反馈，已修复。

**Comment by nanjingboy** [comment]
@ZenoZhengs 已发新版本，更新下试试

**Comment by nanjingboy** [comment]
@ZenoZhengs 我已经验证过了，OK 的，你再看看

**Comment by ZenoZhengs** [comment]
问题已经解决,这两天没有上github,所有没有及时收到回复
