### ISSUE TITLE
taro-ui 本地构建, 编译为小程序时报错

### ISSUE THREAD

**Issue by hnliyuan** [NervJS/taro#3872]
**问题描述**
在引入定制的taro-ui项目，将taro-ui在本地构建并作为外部引入时出错
**复现步骤**

1.npm run build:component
2.复制dist到新建的taro项目新建文件目录为  ui/taro-ui/...
3.config/index.js 设置alias 
  alias: {
    'taro-ui': 'ui/taro-ui',
  }
4. npm run dev:weapp

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import { AtCalendar, AtButton } from 'taro-ui'
import './index.less'

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <AtButton>风卷残云</AtButton>
      </View>
    )
  }
}

```

**期望行为**

**报错信息**
开始编译项目 testTaroUi
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   dist/npm/@tarojs/taro-weapp/index.js
生成  入口配置  dist/app.json
生成  入口文件  dist/app.js
生成  入口样式  dist/app.wxss
编译  所有页面  
编译  页面文件  src/pages/index/index
编译  组件文件  ui/taro-ui/index.js
编译  组件文件  ui/taro-ui/weapp/index.js
编译  组件文件  ui/taro-ui/weapp/components/button/index.js
编译  组件文件  dist/npm/@tarojs/taro-weapp/index.js
编译  组件文件  dist/npm/@tarojs/taro-weapp/dist/index.js
错误  组件错误  组件AtButton路径错误，请检查！（可能原因是导出的组件名不正确）
错误  页面编译  页面/Users/lc/WebstormProjects/testTaroUi/src/pages/index/index编译失败！
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1252:5)
    at pageDepComponents.forEach.depComponent (/Users/lc/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:1414:60)
    at Array.forEach (<anonymous>)
    at componentMap.forEach.component (/Users/lc/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:1406:31)
    at Array.forEach (<anonymous>)
    at realComponentsPathList.forEach.component (/Users/lc/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:1405:24)
    at Array.forEach (<anonymous>)
    at buildSinglePage (/Users/lc/.config/yarn/global/node_modules/@tarojs/cli/src/weapp.js:1402:30)
    at <anonymous>

**系统信息**
Taro CLI 1.2.26 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/opt/node@8/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
    npmPackages:
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-less: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: 1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.9 => 1.4.3 

定制的taro-ui版本为2.1.0

**Comment by DreamPWJ** [comment]
极有可能是微信开发者工具的bug
