### ISSUE TITLE
如何能在执行完统一入口后再加载目标页面

### ISSUE THREAD

**Issue by ninetowns** [NervJS/taro#3876]
**问题描述**

现在的需求是在第一次进入网站时先获得一些状态（比如登录信息）之后再初始化实际页面

目前状况是在app.js中无法阻塞实际页面的加载，经观察它们是并行的

**期望行为**
可以有个阻塞统一入口在执行完一些数据初始化后再进入目标页面

**系统信息**
  Taro CLI 1.3.4 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.12.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@ninetowns 你等初始化后再显示页面，或跳转到对应页面不就可以了吗。

**Comment by ninetowns** [comment]
@Chen-jj 感谢回复，但问题是：
1、不可能在每个页面都写这些重复代码，哪怕是封装了公用方法也很不方便
2、我现在的做法就是跳转到一个中间页，由这个页做完数据初始化后再跳转，但这样对于微信认证和统计造成问题

**Comment by xPixv** [comment]
Google 搜索 “骨架屏”

Taro 物料市场里有个实现，可以参考：https://taro-ext.jd.com/plugin/view/5d2749424cc17c655cfda575

**Comment by loveonelong** [comment]
> @Chen-jj 感谢回复，但问题是：
> 1、不可能在每个页面都写这些重复代码，哪怕是封装了公用方法也很不方便
> 2、我现在的做法就是跳转到一个中间页，由这个页做完数据初始化后再跳转，但这样对于微信认证和统计造成问题

使用装饰器复用起来就很方便了
