### ISSUE TITLE
Taro compiler doesn't inline const enum

### ISSUE THREAD

**Issue by ZhangJian-3ti** [NervJS/taro#3879]
**问题描述**
As TypeScript documentation here:
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#94-constant-enum-declarations

`The entire const enum declaration is erased in the emitted JavaScript code`

But still generate code like:
```javascript
var <EnumName>;  
(function (<EnumName>) {  
    <EnumMemberAssignments>  
})(<EnumName>||(<EnumName>={}));
```
which is unexpected.

**复现步骤**
[复现问题的步骤]
```javascript
const enum CommonCmsId {
    month = 1,
    day = 2,
    week = 3,
    monday = 4,
}
const commonCmsIds = {
id: CommonCmsId.month, value: 'Month',
}
```
should generate:
```
**期望行为**
```javascript
const commonCmsIds = {
  id: 1, value: 'Month',
}
```

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
 Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.0.0 -
      Yarn: 1.16.0 -
      npm: 6.9.0 - C:\nodejs\npm.CMD
      TypeScript: 3.5.3
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
no idea yet.

**Comment by yuche** [comment]
现有机制是没办法做到直接把 `const enum` 把编译到值的，因为当前编译器只接受一个文件编译，不会寻找他的依赖关系，也就是说当你 `const enum` export 出去，另一个文件就不会知道它引用的到底是啥。

下个 major 版本会有 webpack 改造，那时应该可以做到，

**Comment by ZhangJian-3ti** [comment]
Looking forward to that.

**Comment by Chen-jj** [comment]
可以升级到 Taro 2、3 再试试

**Comment by xingqiwu55555** [comment]
> 可以升级到 Taro 2、3 再试试

依然有这个问题
