### ISSUE TITLE
taro 1.3.9 在 windows 下创建项目失败的原因分析和解决办法

### ISSUE THREAD

**Issue by muxi2015** [NervJS/taro#3880]
**解决办法**
将 *.config.ts 扩展名改为 .js 即可.

**问题描述**
taro cli 在 windows 下创建项目提示找不到 *.config.js

**复现步骤**
[复现问题的步骤]
1. taro init project-name
2. 选择 Typescript 的支持
3. yarn dev:weapp
4. 提示找不到 *.config.js

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.9]
 - Node.js 版本 [10.16]
 - 报错平台 [weapp]

**补充信息**
简单读了一下源码, 发现创建项目的时候因为选了 TS 的支持, 则进入了下面这个 if 分支
[Imgur](https://imgur.com/miFtNry)
在下面这段代码中
```javascript
!destRePath.startsWith(`/${CONFIG_DIR_NAME}`)
```
windows 下运行 destRePath 为 `\config\dev.js`, 而这里判断的是根据是不是以 `/` 开头, 这时候问题就很明了了, 这也是其他 issue 中有人回复自己运行没问题的原因, 因为那个人是 Mac OS

没有完整读过源代码就不提 pr 了, 希望上面的分析可以给官方一点帮助.

**Comment by Chen-jj** [comment]
@muxi2015 等等下一版本看看有没得到修复。

https://github.com/NervJS/taro/blob/19af493239ebd92c5da521b515af5888558ea657/packages/taro-cli/src/create/init.ts#L58
