### ISSUE TITLE
微信小程序原生第三方组件中的 wxs 文件不会被复制到 dist 中

### ISSUE THREAD

**Issue by umaim** [NervJS/taro#3885]
**问题描述**
微信小程序原生组件中的 [wxs 文件](https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/)不会被复制到 dist 中

**复现步骤**
按照文档中 [引入第三方组件](http://taro-docs.jd.com/taro/docs/mini-third-party.html) 之后，构建微信小程序时会漏掉原生组件 wxs 文件

临时解决方案：不得不在 `config.copy` 下手动写复制才行

**期望行为**
希望在 Taro 构建的时候，将原生组件中的 wxs 文件也复制到目标目录

**QQ小程序的 [qs 文件](https://q.qq.com/wiki/develop/miniprogram/frame/view/view_qs_all.html)应该也同理，希望能一并解决**

**报错信息**
没有

**系统信息**
 - 操作系统:  Windows 10
 - Taro 版本 1.3.9
 - Node.js 版本 12
 - 报错平台 weapp

**Comment by MrLeihe** [comment]
这是个巨坑

**Comment by pitipon** [comment]
me too .. I have this bug

**Comment by mihuartuanr** [comment]
这个更新了么……这个问题应该好严重的呢

**Comment by towry** [comment]
多久了怎么问题还在。。想按照官方教程使用 vant 库，但是 wxs 似乎拷贝不过去。。。
