### ISSUE TITLE
taroUI组件样式出不来是咋回事？

### ISSUE THREAD

**Issue by a591371947** [NervJS/taro#3887]
![image](https://user-images.githubusercontent.com/42060656/61459512-73d8e800-a99f-11e9-8218-9e67c201104e.png)
![image](https://user-images.githubusercontent.com/42060656/61459573-9cf97880-a99f-11e9-93e1-94992b1e6371.png)

什么才有可能影响组件的样式 我改问题的时候 改着改着突然就没样式了 我现在代码版本都回到了改之前的版本 还是没用

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/component-style.html
https://taro-ui.aotu.io/#/docs/questions
