### ISSUE TITLE
taro componentWillUnmount h5 钩子函数不生效

### ISSUE THREAD

**Issue by lang-strive** [NervJS/taro#3888]
taro 版本之前1.22 taro componentWillUnmount h5 钩子函数不生效 升级到1.39版本后还是不生效

**Comment by lang-strive** [comment]
componentWillUnmount()
页面卸载时触发，如 redirectTo 或 navigateBack 到其他页面时

**Comment by yuche** [comment]
你可以用 componentDidHide 来做类似的事情
