### ISSUE TITLE
1.0.0-beta.22 发布

### ISSUE THREAD

**Issue by Simbachen** [NervJS/taro#389]
主要更新有小程序组件化重构，在这一版中，采用小程序原生的自定义组件来实现组件化，相较之前的基于 `template` 的组件化有了非常大的进步。

主要更新功能：

- 自定义组件现在可以传入 `this.props.children`；
- 稳定性有了很大的提高，之前在各种情况下自定义组件传参失败的情况会大幅减少；
- 基于原生组件化功能，我们将逐步取消之前版本的各种限制，包括：
  * 使用第三方组件库，例如 `zan-ui`
  * 传入匿名函数
  * 在 `render` 方法之外使用 JSX 元素

升级需要注意：

- 样式，小程序自定义组件除继承样式外， app.wxss 中的样式、组件所在页面的的样式对自定义组件无效。因此组件样式需写在对应的wxss文件中。通过className传入组件样式。
- props 传函数，在小程序中是通过*组件事件*来实现的，在子组件中调用时无法获取到函数执行的返回值，同时给子组件传递函数时，属性名必须以 `on` 开头
- 受限于小程序组件化，必须要在 properties 里指定具体的 prop 才能传入。因此，如果代码中没有使用到任何 prop，直接在`render`方法里打印`this.props` 将会是一个空对象
- 由于小程序不支持将data中任何一项的value设为 `undefined` ，在setState的时候也请避免这么用。你可以使用`null`来替代
- 不要使用`id`作为prop或state，例如`this.props.id`在小程序中会丢失

如何升级到beta版本：

原有的update命令无法升级到beta版，需要手动升级。
- 升级cli工具到beta版：npm install -g @tarojs/cli@1.0.0-beta.xx
- 到对应的项目目录中手动更新package.json文件，将@tarojs 下相关的依赖包更新到对应的beta版本

试用中遇到问题可以在这里回复~

**Comment by rojer95** [comment]
![image](https://user-images.githubusercontent.com/20662049/43257430-5deaa7c4-9102-11e8-9320-3869912c8621.png)
![image](https://user-images.githubusercontent.com/20662049/43257443-64948cb6-9102-11e8-8381-f96c1bc738c5.png)
体验了一下。
遇到这个问题。

**Comment by Songkeys** [comment]
通过 props map 出来的渲染出错：

```jsx
       <View className='tabs-container'>
        {this.props.tabs.map((t, i) => (
          <View
            className={`tab ${this.state.activeIndex === i ? 'active' : ''}`}
            key={t}
            onClick={this.handleChangeTab.bind(this, i)}
          >
            <Text>{t}</Text>
          </View>
        ))}
      </View>
```

渲染结果：

![image](https://user-images.githubusercontent.com/22665058/43287319-4e3617f0-9157-11e8-97be-21404293047e.png)

```
<block>
    <view class="tabs-container">{{__triggerPropsFn("tabs.map", [
        <View>].concat([(t, i) => { return
            <View className={anonymousState__temp} wx:key={t}
            bindtap="handleChangeTab" data-e-handleChangeTab-so="this" data-e-handleChangeTab-a-a={i}>
                <Text>{t}</Text>
            </View>; }]))}}</view>
</block>
```

**Comment by luckyadam** [comment]
@Songkeys 升级到 `1.0.0-beta.1` 修复了这个问题

**Comment by Songkeys** [comment]
1.0.0-beta.1:
`this.props.children` 在模板中与其他变量混合导致编译出错：
```jsx
<Button>{this.props.text}</Button>    // ok!
<Button>{this.props.children}</Button>    // ok!
<Button>{this.props.text || this.props.children}</Button>    // 出错
```
编译结果：(Bad value with message)
```
<button>{{text || <slot />}}</button>
```

**Comment by Songkeys** [comment]
1.0.0-beta.1:
渲染自定义组件时，使用 `this.props.xxx` 进行判断的条件渲染有问题：
```
static defaultProps = {
  isTrue: true, // or false
}
...
{!this.prop.isTrue && <Btn />}
```

如果直接使用 defaultProps 进行渲染没有问题，但一旦这个 prop 是父组件传下来的，就会出错：
![](https://ws1.sinaimg.cn/large/006tKfTcgy1ftojzbkirij312w09qjw8.jpg)

出错行为还挺奇怪……好像是下面这样，还没仔细研究具体行为：
```
{!this.prop.isTrue && <Btn />} // 会出错
{this.prop.isTrue && <Btn />} // 不会出错
```

同时发现，如果直接把这个字段写在页面上，还是可以显示的：
```
<View>{this.props.isTrue}</View>  // 可以在页面上显示正确的结果
```

**Comment by Songkeys** [comment]
1.0.0-beta.1:
好像 defaultProps 即时设定了，也全部变成 null 了？

**Comment by luckyadam** [comment]
@Songkeys 收到~ 非常感谢反馈~ 我们快速跟进一下~

**Comment by yuche** [comment]
@Songkeys 
https://github.com/NervJS/taro/commit/3202b493c4f162be4c1fde99d5983d2dbd809f18 可以支持到`<Button>{this.props.text || this.props.children}</Button>` 这种写法，原来觉得在 JSX 使用 || 的频率比较低，现在有 children 了其实还是应该支持的。

至于 `{!this.prop.isTrue && <Btn />}` 报错的原因应该是你写成了 `this.prop` 而不是 `this.props`?

你的例子我写成了几个测试用例：https://github.com/NervJS/taro/commit/4b871d8254bd0cb11e4ef4f49c0ee4cc06808080

**Comment by Songkeys** [comment]
@yuche 
不要意思，是我发在这里的 issue 打错了，项目中是写的 `props`。可以看下上面图中的报错，报的确实是 `... 'props' of undefined...`。

看了一下测试用例，都没有问题。我这边编译完的 dist 文件也没有问题。但实际运行时会报错。

下面是我项目编译完的代码：
```
<block wx:if="{{!isLoggedIn}}"> // 报错
    <btn type="primary" __triggerObserer="{{ _triggerObserer }}" text="登录"></btn>
</block>
```

如果我去掉逻辑运算符：
```
<block wx:if="{{isLoggedIn}}"> // 正常运行
    <btn type="primary" __triggerObserer="{{ _triggerObserer }}" text="登录"></btn>
</block>
```

**Comment by yuche** [comment]
@Songkeys 
应该和 https://github.com/NervJS/taro/issues/401 是同一个问题，我们正在看原因

**Comment by luckyadam** [comment]
@Songkeys 可以试试 `1.0.0-beta.2` 哦

**Comment by Songkeys** [comment]
1.0.0-beta.2:
试了一下。
在 JSX 中写 || 已经可以了。

关于 `‘props’ of undefined`：
我新建了一个项目，复现了一下。之前还是说错了……遗漏的触发条件其实是嵌套的条件判断，行为有点奇怪，我都晕了，不知道咋形容了……

关于 defaultProps 都是 null：
情况是，一个 prop 如果在 render 中使用了，它就会变成 null。

两个测试可以看一下这个仓库：
```
git clone https://github.com/Songkeys/taro-demo.git
```

**Comment by Songkeys** [comment]
1.0.0-beta.3:
当 map 渲染含有字符串模板时，提示：
![](https://ws3.sinaimg.cn/large/006tNc79gy1fttm3xct2hj30r40ho0yh.jpg)

https://github.com/Songkeys/taro-demo/blob/ac4557b9ade68597eb79be4237529d14816d1a32/src/pages/comp/comp.js#L9-L18

**Comment by Songkeys** [comment]
1.0.0-beta.4:
值为 `null` 的字段通过 `setState()` 进入 `state` 后，变成空 object：
![](https://ws3.sinaimg.cn/large/0069RVTdgy1ftu8gxwstwj31f61a6gv2.jpg)

**Comment by Simbachen** [comment]
#417

**Comment by Songkeys** [comment]
升级到 beta.9 之后：

父页面：
```jsx
render() {
  const { id } = this.$router.params
  return <Content userId={id} />
}
```

子组件：
```jsx
  static defaultProps = {
    userId: null,
  }

  componentDidMount() {
    console.log(this.props.userId) // null
    setTimeout(() => {
      console.log(this.props.userId) // 正常
    }, 1000)
  }
```

而且这个情况出现在这个页面被推入的场景下，如果用开发者工具的编译模式直接打开这个页面，是不会出现问题的，估计是和 App 的生命周期又有影响了？

---

话说之前提过的直接用 `<Content userId={this.$router.params.id} />` 传递页面参数的问题，也还没有修复。

---

另外不知道可不可以做到在自定义组件中取到父页面实例？之前的做法是 `this.$scope`，但现在 `this.$scope` 变成组件本身后，就没办法取到了。不过感觉这个需求不是很合理？（之前用这种方法直接取页面参数的：`this.$scope.options`，省了传 props 的步骤，会不会不怎么合适……？）

**Comment by luckyadam** [comment]
@Songkeys
建议在父页面中这么传入子组件~

父页面：
```javascript
componentWillMount() {
  const params = this.$router.params
  this.setState({
    id: params.id
  })
}

render () {
  return <Content userId={this.state.id} />
}
```

**Comment by joshua7v** [comment]
升级到`1.0.0-beta.10`
小程序好像依旧不支持`this.props.children`
target h5 没什么问题，小程序获取不到`this.props.children`

**Comment by BryantZhou** [comment]
children使用方式有点问题

无效写法
```js
const {children} = this.props
return <View>{this.props.children}</View>
```
有效写法

```js
return  <View>{this.props.children}</View>
```

**Comment by Songkeys** [comment]
@luckyadam 
已经按你的建议改过了，beta.10 还是有之前提过的 [页面被推入的场景下 state 获取不正常](https://github.com/NervJS/taro/issues/389#issuecomment-411891845) 的问题。

忘了是从哪个版本出现的这个问题了，前面beta几版还都是正常的。
