### ISSUE TITLE
用css无法只显示多行/单行文字的前半部分，而隐藏后半部分。

### ISSUE THREAD

**Issue by numeny** [NervJS/taro#3890]
**用css无法只显示部分文字，而隐藏其他文字。**

**复现步骤**
1. 构建简单的多行文字。
2. 使用下列CSS，无法实现多行文字时，只显示部分文字，而隐藏其他文字。
3. 对于上述css加不加效果一样，无法实现多行文字只显示前几行，而用省略号省略后半部分。

```js
  // 场景一
  // 多行文字省略css
  display: -webkit-box;
  text-overflow:ellipsis;                                                  
  -webkit-line-clamp: 3;
  overflow: hidden;
  width: 100%;                                                             

  // 场景二
  // 单行文字省略后半部分文字css
  width: 100%;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis; 
```

**期望行为**
场景一的CSS：能够使得多行文字只显示前几行，后半部分不显示，用省略号代替。
场景二的CSS：能够使得单行文字只显示半部分，后半部分不显示，用省略号代替。

**报错信息**

**系统信息**
👽 Taro v1.3.9

  Taro CLI 1.3.9 environment info:
    System:
      OS: Linux 4.10 Ubuntu 16.04.3 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
      npm: 5.6.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    npmPackages:
      @tarojs/components: 1.3.9 => 1.3.9 
      @tarojs/plugin-babel: 1.3.9 => 1.3.9 
      @tarojs/plugin-csso: 1.3.9 => 1.3.9 
      @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9 
      @tarojs/router: 1.3.9 => 1.3.9 
      @tarojs/taro: 1.3.9 => 1.3.9 
      @tarojs/taro-alipay: 1.3.9 => 1.3.9 
      @tarojs/taro-h5: 1.3.9 => 1.3.9 
      @tarojs/taro-swan: 1.3.9 => 1.3.9 
      @tarojs/taro-tt: 1.3.9 => 1.3.9 
      @tarojs/taro-weapp: 1.3.9 => 1.3.9 
      @tarojs/webpack-runner: 1.3.9 => 1.3.9 
      eslint-config-taro: 1.3.9 => 1.3.9 
      eslint-plugin-taro: 1.3.9 => 1.3.9 
      nerv-devtools: ^1.4.0-beta.3 => 1.4.3 
      nervjs: ^1.4.0-beta.3 => 1.4.3 

**补充信息**

**Comment by yuche** [comment]
Taro 是除了预处理器/后处理器之外基本不会对 CSS 做处理，你可以试下直接在小程序开发者工具进行调试，如果直接添加没有效果，那应该就是小程序容器有问题。

**Comment by numeny** [comment]
我用的是h5版本，用上述css，在自己编写的html网页里是可以实现预期效果的，但是用Taro编辑的网页里不行。您可以试一下。您可以参照下：http://www.daqianduan.com/6179.html

**Comment by numeny** [comment]
能复现吗？能解决吗？

**Comment by StevenStar** [comment]
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;
