### ISSUE TITLE
百度小程序使用mobx的rootStore用法异常

### ISSUE THREAD

**Issue by wucipo** [NervJS/taro#3891]
**问题描述**
mobx使用store多模块，如user、msg、order，且封装成为rootStore的属性，转换百度小程序无法正常展示，如下提示
【Custom Component Error】can't find components/Userinfo/Userinfo, please check your config:

**复现步骤**
[复现问题的步骤]
1. 创建根store
2. 子store构造函数赋值自身的this.root

```js
import GlobalMD from './global'
import PayMD from './pay'
import CouponMD from './coupon'
import OptionsMD from './options'

class Common {
  constructor() {
    this.GlobalMD = new GlobalMD(this)
    this.PayMD = new PayMD(this)
    this.CouponMD = new CouponMD(this)
    this.OptionsMD = new OptionsMD(this)
  }
}
let CommonMD =  new Common()
const store = {
  GlobalMD: CommonMD.GlobalMD,
  PayMD: CommonMD.PayMD,
  CouponMD: CommonMD.CouponMD,
  OptionsMD: CommonMD.OptionsMD
}
export default store
```

**报错信息**
![image](https://user-images.githubusercontent.com/18008712/61507197-5fd0cd00-aa17-11e9-98e8-bc5587f21312.png)

**系统信息**
 - 操作系统:  Windows 10
 - Taro 版本 v1.3.8
 - Node.js 版本  10.15.0
 - 报错平台 swanapp 百度小程序

**Comment by wucipo** [comment]
此问题很影响多人维护代码分块协同开发

**Comment by Chen-jj** [comment]
@wucipo 能否提供一份完整可复现的项目 demo

**Comment by Chen-jj** [comment]
@wucipo 复现不了，更新到最新版再试试。而且我觉得不是 mobx 的问题，你点进去报错信息再详细定位下吧。

store/counter.js

```js
import { observable, action } from 'mobx'

class CounterStore {
  @observable
  testArry = []

  @action.bound
  add() {
    console.log('this: ', this)
    this.testArry.push("测试")
  }

  @action.bound
  delete() {
    this.testArry.pop()
  }
}

export default CounterStore
```

store/todo.js:

```js
import { observable, action } from 'mobx'

class TodoStore {
  @observable
  todos = []

  @action.bound
  add() {
    this.todos.push("测试")
  }

  @action.bound
  delete() {
    this.todos.pop()
  }
}

export default TodoStore
```
store/index.js

```js
import CounterStore from './counter'
import TodoStore from  './todo'

class Common {
  constructor() {
    this.CounterStore = new CounterStore(this)
    this.TodoStore = new TodoStore(this)
  }
}
let CommonMD =  new Common()

const store = {
  CounterStore: CommonMD.CounterStore,
  TodoStore: CommonMD.TodoStore
}

export default store
```

app.js:

```js
import store from './store'

class App extends Component {
  render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/62437485-fcb09b80-b775-11e9-8968-e86c68337dda.png)

**Comment by wucipo** [comment]
`
/**
 * 子模块CounterStore增加构造函数且赋值到this.root
 */
import { observable, action } from 'mobx'

class CounterStore {
 // 注意这里constructor构造函数
  constructor(root) {
    this.root = root
  }
  @observable
  todos = []

  @action.bound
  add() {
    this.todos.push('测试')
  }

  @action.bound
  delete() {
    this.todos.pop()
  }
}
export default CounterStore
`
**注意：本意是子store模块间能够相互访问通信，是方式不正确？**

**Comment by wucipo** [comment]
> @wucipo 复现不了，更新到最新版再试试。而且我觉得不是 mobx 的问题，你点进去报错信息再详细定位下吧。
> 
> store/counter.js
> 
> ```js
> import { observable, action } from 'mobx'
> 
> class CounterStore {
>   @observable
>   testArry = []
> 
>   @action.bound
>   add() {
>     console.log('this: ', this)
>     this.testArry.push("测试")
>   }
> 
>   @action.bound
>   delete() {
>     this.testArry.pop()
>   }
> }
> 
> export default CounterStore
> ```
> 
> store/todo.js:
> 
> ```js
> import { observable, action } from 'mobx'
> 
> class TodoStore {
>   @observable
>   todos = []
> 
>   @action.bound
>   add() {
>     this.todos.push("测试")
>   }
> 
>   @action.bound
>   delete() {
>     this.todos.pop()
>   }
> }
> 
> export default TodoStore
> ```
> 
> store/index.js
> 
> ```js
> import CounterStore from './counter'
> import TodoStore from  './todo'
> 
> class Common {
>   constructor() {
>     this.CounterStore = new CounterStore(this)
>     this.TodoStore = new TodoStore(this)
>   }
> }
> let CommonMD =  new Common()
> 
> const store = {
>   CounterStore: CommonMD.CounterStore,
>   TodoStore: CommonMD.TodoStore
> }
> 
> export default store
> ```
> 
> app.js:
> 
> ```js
> import store from './store'
> 
> class App extends Component {
>   render () {
>     return (
>       <Provider store={store}>
>         <Index />
>       </Provider>
>     )
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/11807297/62437485-fcb09b80-b775-11e9-8968-e86c68337dda.png)

```javascript
import { observable, action } from 'mobx'

/**
 * 子模块CounterStore增加构造函数且赋值到this.root
 */
class CounterStore {
 // 注意这里constructor构造函数
  constructor(root) {
    this.root = root
  }
  @observable
  todos = []

  @action.bound
  add() {
    this.todos.push('测试')
  }

  @action.bound
  delete() {
    this.todos.pop()
  }
}
export default CounterStore
```
**注意：本意是子store模块间能够相互访问通信，是方式不正确？**

**Comment by Chen-jj** [comment]
@wucipo 试了下的确 store 组合通讯有问题，不仅是百度端。可以加一下 MobX 问题反馈微信群询问一下[作者](https://github.com/nanjingboy/)。

**Comment by wucipo** [comment]
@Chen-jj 麻烦提供下Mobx问题反馈微信群可以吗

**Comment by Chen-jj** [comment]
@wucipo 试试加一下这个[小助手](https://github.com/NervJS/taro/issues/198)，然后让他加一下 MobX 群？

**Comment by wucipo** [comment]
@Chen-jj 一直没拉我入群，已经申请了很多天了

**Comment by Chen-jj** [comment]
@wucipo 现在拉了吗？

**Comment by wucipo** [comment]
> @wucipo 现在拉了吗？

已进入

**Comment by wucipo** [comment]
> @wucipo 现在拉了吗？

已进入

**Comment by wucipo** [comment]
[mobx#3891.zip](https://github.com/NervJS/taro/files/3531286/mobx.3891.zip)
**demo版本已把问题复现，望抽空解决之**

**Comment by nanjingboy** [comment]
@wucipo 根据 demo 应该是循环引用的问题，关于该问题的讨论参见：https://github.com/NervJS/taro/issues/1991

**Comment by Chen-jj** [comment]
#1991

**Comment by nanjingboy** [comment]
问题与 https://github.com/NervJS/taro/issues/1991 重复了
