### ISSUE TITLE
h5下chooseImage可以选择除图片以外的文件

### ISSUE THREAD

**Issue by Cdream-l** [NervJS/taro#3892]
**问题描述**
h5下chooseImage可以选择除图片以外的文件

**期望行为**
只可选择图片媒体文件

**系统信息**
  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Users\zhijia\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
     @tarojs/components: 1.3.9 => 1.3.9
     @tarojs/plugin-babel: 1.3.9 => 1.3.9
     @tarojs/plugin-csso: 1.3.9 => 1.3.9
     @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9
     @tarojs/router: 1.3.9 => 1.3.9
     @tarojs/taro: 1.3.9 => 1.3.9
     @tarojs/taro-alipay: 1.3.9 => 1.3.9
     @tarojs/taro-h5: 1.3.9 => 1.3.9
     @tarojs/taro-swan: 1.3.9 => 1.3.9
     @tarojs/taro-tt: 1.3.9 => 1.3.9
     @tarojs/taro-weapp: 1.3.9 => 1.3.9
     @tarojs/webpack-runner: 1.3.9 => 1.3.9
     eslint-config-taro: 1.3.9 => 1.3.9
      eslint-plugin-taro: 1.3.9 => 1.3.9
      nerv-devtools: ^1.4.0-beta.3 => 1.4.3
      nervjs: ^1.4.0-beta.3 => 1.4.3
**补充信息**
 不确定是否属于bug，依api的名称来说，应该阻止选择媒体类型以外的文件，或提供前置钩子，由开发者自行处理

**Comment by Littly** [comment]
chooseImage使用的input带着`accept="image/*"`属性，不知道你所说的情况是出现在什么平台？

**Comment by azl397985856** [comment]
> chooseImage使用的input带着`accept="image/*"`属性，不知道你所说的情况是出现在什么平台？

请问如何选择除图片之外的文件， 比如pdf，word之类？
