### ISSUE TITLE
Taro如何将测试环境打包成dist

### ISSUE THREAD

**Issue by sansx** [NervJS/taro#3894]
**问题描述**
想要将taro的测试环境打包出来，发现没有途径，可以把dev的配置复制到prod里面，但是这样的话，感觉两个配置文件分开就没什么意义了

**Comment by Garfield550** [comment]
没有理解你的需求，能详细描述下吗？

**Comment by sansx** [comment]
运行build:h5的时候，只能把config/prod.js（正式环境）下的配置打包出来，没有方法使用config/dev.js（测试环境）里面的defineConstants配置打包
react打包可以选择特定的.env文件作为环境变量打包，taro打包出的dist好像只能是prod.js下面设置的defineConstants

**Comment by sansx** [comment]
@Garfield550 你好，还需要我提供什么其他信息吗

**Comment by Garfield550** [comment]
如果你是想要在 taro build 命令指定 config 文件的话那么这是个 enhancement ，暂未实现。

**Comment by luckyadam** [comment]
配置一下 https://nervjs.github.io/taro/docs/config-detail.html#env

**Comment by sansx** [comment]
@luckyadam 感谢回复  
这个配置了，但是`dev.js`下面的配置只在`dev:h5`等`dev:`的指令下面生成的文件生效，而`dev:h5`指令，在开始编译的时候会生成`dist`文件夹，但是马上就被自动删除  
最后只剩下没打包过的`.temp`文件夹，想要获得`dev`的配置打包出的`dist`，看起来应该是还没有实现的功能  
这样我只能把`dev`的配置复制到`prod.js`，然后运行`build:h5`来获取到`dev`配置的`dist`打包文件，影响不是很大，不过不能选择要打包的环境还是稍微有些可惜

**Comment by giantss** [comment]
@sansx 我理解的是这样的 `config` 文件夹下有3个文件 `dev.js`  `index.js`  `prod.js` 默认情况下只配置 `index.js` 里面就好了 如果开发环境下有特殊配置项可以在 `dev.js`下配置，如果打包生产环境的包需要特殊配置可以在 `prod.js` 中配置。 `dev.js`  和 `prod.js` 中的配置项优先级最高，会覆盖index.js中的配置项。我这样理解的对吗？@luckyadam

**Comment by sunyxq** [comment]
@sansx 我的理解是，需求需要打包两种不同运行环境的项目源码包：正式环境(`pro`，线上版本)和测试环境(`tst`，测试版本),而且测试环境和开发环境配置基本一致。
 在升级Taro`1.3.18`版本之前(之前版本为`1.0.x`版本逐渐升级到`1.2.14`)，处理方法是在`config`目录新建一个`test.js`配置文件,把`dev.js`中除开发相关配置(如：`devServer`)之外的都拷贝到`test.js`并修改`test.js`配置文件中`env.NODE_ENV: '"test"'`;
![pic1](http://pxyu8nrr9.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-09-17%20%E4%B8%8B%E5%8D%884.02.20.png)
然后在`package.json`中配置如下`scripts`:
```
  "test:h5": "set NODE_ENV=test && npm run build:h5",
```
在`index.js`最下面方法中添加如下逻辑：
```
 ...
 else if(process.env.NODE_ENV === 'test') {
  merge({}, config, require('./test'))
 }
...
```
最后在终端运行`npm run test:h5`即可打包
然而，昨天升级`1.3.18`版本后，运行`npm run test:h5`也是直接打包线上版本`pro.js`，百思不得其解

**Comment by sansx** [comment]
@giantss @sunyxq 
多谢回复，我回头试一下😄

**Comment by sunyxq** [comment]
@sansx 
不好意思，我今天仔细验证了一下，以前的方法不可行(为什么这么久没人反馈，个中缘由不表)。就不要浪费时间验证了。我也是今天发现以前的根本没用，才来github解决方案，刚好看到楼主的`issue`，回复我已经删除了，免得误人子弟。抱歉！

**Comment by sansx** [comment]
@sunyxq 哈哈，没事，算是帮我排除错误了，如果之后有什么好方法可以再继续讨论
