### ISSUE TITLE
能自定义公用plugin吗？公用还是只支持plugins.babel plugins.uglify plugins.csso plugins.sass？

### ISSUE THREAD

**Issue by jiangwanwei** [NervJS/taro#3895]
**问题描述**
[问题描述：能自定义公用plugin吗？公用还是只支持plugins.babel plugins.uglify plugins.csso plugins.sass 吗 ？]

**Comment by luckyadam** [comment]
暂时只支持这些，不过正在做插件化改造

**Comment by jiangwanwei** [comment]
> 暂时只支持这些，不过正在做插件化改造，即将支持自定义插件

噢  3q
