### ISSUE TITLE
小程序转 taro 再 yarn dev:h5 项目编译不成功

### ISSUE THREAD

**Issue by ifkhkh** [NervJS/taro#3896]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
编译过程中，提示找不到文件
但是 .temp\utils\util.js 这个文件是存在的

**报错信息**
🙅   Failed to compile.

./.temp/app.js
Module not found: Can't resolve 'utils/util.js' in 'C:\Users\HighSun\Documents\GitHub\testTaro\hs-mini-eshop\taroConvert\.temp'

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.8

  Taro CLI 1.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.8]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5]

**Comment by yuche** [comment]
你写相对路径试试

**Comment by ifkhkh** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

写的就是相对路径阿

> 你写相对路径试试

**Comment by ifkhkh** [comment]
![Uploading image.png…]()

![Uploading image.png…]()


写的就是相对路径

**Comment by ifkhkh** [comment]
util/utils 写成 ./util/utils 就不报错了

**Comment by archywillhe** [comment]
:(
