### ISSUE TITLE
字节跳动异步函数报错

### ISSUE THREAD

**Issue by Huatingzi** [NervJS/taro#3898]
**问题描述**
在字节跳动会不支持报错
**复现步骤**
![image](https://user-images.githubusercontent.com/20843521/61533418-700c9a80-aa5f-11e9-9b44-6e8a9def07e2.png)
这种函数不被支持，
在app.js引入了
![image](https://user-images.githubusercontent.com/20843521/61533455-8c103c00-aa5f-11e9-857f-612b6f53cb88.png)
但是还是一样的结果报错

**期望行为**
可以正常使用异步函数
**报错信息**
![image](https://user-images.githubusercontent.com/20843521/61533488-a64a1a00-aa5f-11e9-9e30-033d6b974169.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: mac
 - Taro 版本 1.2.23
 - Node.js 版本 8.9.0
 - 报错平台 字节跳动

**Comment by Chen-jj** [comment]
@Huatingzi 
https://nervjs.github.io/taro/docs/before-dev-remind.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F
