### ISSUE TITLE
Taro 1.3 的scroll组件在chrome浏览器上报Added non-passive event listener to a scroll-blocking 'touchmove' event

### ISSUE THREAD

**Issue by moonreplace** [NervJS/taro#3907]
**问题描述**
Taro 1.3 的scroll组件在devtools里报Added non-passive event listener to a scroll-blocking 'touchmove' event

会造成页面渲染的卡顿

**复现步骤**
任意一个scroll组件都会报这个warning

```js
 <ScrollView
                            scrollX
                            className="container"
                            id="demoContainer"
                            scrollLeft={listScrollLeft}
                            onScroll={this.onScoll}
                            scrollWithAnimation="true"

                        >
                            {listist.map((item, index) => {
                               
                                return (
                                    <View key={index} className="list-item">
                                        <View onClick={this.test.bind(this, item, index)}>
                                            <View className="wrapper">
                                                <Image />
                                            </View>
                                        </View>
                                  </View>
                                 )
                 </ScrollView>

```

**期望行为**
不要有这个warning

**报错信息**
vendor_546a661e77d6b01305d0.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**系统信息**

Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.10.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.2 => 1.3.10
      @tarojs/cli: ^1.3.2 => 1.3.10
      @tarojs/components: ^1.3.2 => 1.3.10
      @tarojs/mobx: ^1.3.2 => 1.3.10
      @tarojs/mobx-h5: ^1.3.2 => 1.3.10
      @tarojs/plugin-babel: ^1.3.2 => 1.3.10
      @tarojs/plugin-csso: ^1.3.2 => 1.3.10
      @tarojs/plugin-sass: ^1.3.2 => 1.3.10
      @tarojs/plugin-uglifyjs: ^1.3.2 => 1.3.10
      @tarojs/router: ^1.3.2 => 1.3.10
      @tarojs/taro: ^1.3.2 => 1.3.10
      @tarojs/taro-h5: ^1.3.2 => 1.3.10
      @tarojs/taro-weapp: ^1.3.2 => 1.3.10
      @tarojs/webpack-runner: ^1.3.2 => 1.3.10
      eslint-config-taro: ^1.3.2 => 1.3.10
      eslint-plugin-taro: ^1.3.2 => 1.3.10
      nervjs: ^1.4.3 => 1.4.3
      react: ^16.7.0 => 16.8.6

**Comment by jinjinjin0731** [comment]
其实你换个非 Chrome 的就不会了。 这块提示是因为  onTouchMove 的绑定写在了 div 上。 出现告警的是推荐使用 addEventListener 的方式去绑定。  后续改下。  这个  应该不会造成渲染卡顿吧。

**Comment by wayung** [comment]
我也出现这个问题，但页面有点卡顿，大概需要等3~5秒，一个视图里加载3000多条记录，这个怎么解决呢？

![c](https://user-images.githubusercontent.com/11419700/62455763-ad845e00-b7a9-11e9-80fa-3446269e4946.gif)

**Comment by magicbing** [comment]
我这也有这个问题, 会卡几秒的样子, 希望能处理一下

**Comment by wayung** [comment]
这个issue都没提供解决方案，怎么close掉了呢？

**Comment by xmsz** [comment]
现在也是还是这样

都快哭了

连调试都用不了了

**Comment by Ashira97** [comment]
@jinjinjin0731 不会造成渲染卡顿 但是会造成chrome控制台无法调试
