### ISSUE TITLE
taro编译h5时createCanvasContext报错

### ISSUE THREAD

**Issue by opacityKing** [NervJS/taro#3909]
![image](https://user-images.githubusercontent.com/26480260/61600674-686a1300-ac64-11e9-92c1-fcff27602bb1.png)

```js

// ```js
const context = Taro.createCanvasContext('canva', this.$scope);
<Canvas style='width: 150px; height: 150px;background:#fff' canvasId='canva' />
// ```

```

Taro CLI 1.3.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.2 - C:\Users\fat\soft\node.EXE
      Yarn: 1.7.0 - C:\Users\fat\AppData\Roaming\npm\yarn.CMD
      npm: 5.4.0 - C:\Users\fat\soft\npm.CMD

**Comment by mohong** [comment]
我也遇到了，发现H5下this.$scope取值取不到，直接用this的话不会报错，但是不知道后面的逻辑对不对。

**Comment by opacityKing** [comment]
直接用this的话vnode就报错了……

**Comment by Littly** [comment]
传this就好

**Comment by ZhongEden** [comment]
> 直接用this的话vnode就报错了……

我也遇到了这个问题
你的解决了吗？

**Comment by opacityKing** [comment]
没解决，，最后直接后端给了我base64

**Comment by yztsp** [comment]
我的也是 ， 直接用this的话vnode就报错了……
