### ISSUE TITLE
小程序转 Taro 后编译 H5 后 @taros/components 报错

### ISSUE THREAD

**Issue by ifkhkh** [NervJS/taro#3911]
**问题描述**
小程序 taro convert 后进入 taroConvert，yarn install 后执行 yarn dev:h5
编译一段时间后报错并且没有编译成功。

**报错信息**

ℹ️  Listening at http://127.0.0.1:10086/

监听文件修改中...

⚠️  Compiled with warnings.

./.temp/pages/index/storeMap/storeMap.js 259:29-32
" '@tarojs/components' does not contain an export named 'Map'.

./.temp/pages/index/store/store.js 280:29-32
" '@tarojs/components' does not contain an export named 'Map'.

./.temp/pages/index/searchStore/searchStore.js 469:78-81
" '@tarojs/components' does not contain an export named 'Map'.

./.temp/pages/index/joinHsprint/joinHsprint.js 443:29-32
" '@tarojs/components' does not contain an export named 'Map'.

**系统信息**
taro info
👽 Taro v1.3.8

  Taro CLI 1.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.1 - C:\Users\HighSun\AppData\Roaming\npm\npm.CMD

**Comment by yuche** [comment]
在 h5 现在还没有 Map 这个组件

**Comment by ifkhkh** [comment]
但是为何首页都显示不出来，首页并没有用到 Map

**Comment by yuche** [comment]
你的首页有 import Map 吗

**Comment by ifkhkh** [comment]
import Nerv from "nervjs";
import { View, Navigator, Image, Text, Swiper, SwiperItem } from '@tarojs/components';
import Taro from "@tarojs/taro-h5";
import withWeapp from '@tarojs/with-weapp';
import './index.scss';
const util = require('../../utils/util.js');
const api = require('../../api/api.js');

const { ImageApi } = require('../../model/image.js');
const { Product } = require('../../model/product.js');

首页只用到了这些

开发者工具 console 报错如下
![image](https://user-images.githubusercontent.com/15436119/61603245-6c4f6280-ac6f-11e9-91e7-ac0d71b5da01.png)

![image](https://user-images.githubusercontent.com/15436119/61603257-7cffd880-ac6f-11e9-879e-4c0443db6404.png)

**Comment by luckyadam** [comment]
H5 暂时没有实现 Map 组件，如果要编译到 H5 就不要直接引入 Map，可以写跨平台代码
https://taro-docs.jd.com/taro/docs/envs.html

**Comment by ifkhkh** [comment]
谢谢回复，但是这里
![image](https://user-images.githubusercontent.com/15436119/61677316-c44e9d80-ad31-11e9-97a1-c2b015e5783e.png)
 这个报错是因为 util，但是 util  里面并没有引入 map，是显示的 util.js 的 module.exports 报错
![image](https://user-images.githubusercontent.com/15436119/61677349-e3e5c600-ad31-11e9-8854-b45d39c91602.png)
