### ISSUE TITLE
Taro怎么配置多个打包环境

### ISSUE THREAD

**Issue by songyizhe** [NervJS/taro#3912]
我想要h5通过打包命令打包成多种环境，比如npm run build:h5 test是打包成测试环境的

**Comment by luckyadam** [comment]
在 config 里增加配置文件，在 index.js 里按需引入

**Comment by songyizhe** [comment]
但是我在package.json里面配置命令无效呀，package.json那里我该如何去写？

**Comment by songyizhe** [comment]
> 在配置增加配置文件，在index.js里按需引入

但是我在的package.json里面配置命令无效呀，的package.json那里我该如何去写？

**Comment by xiankuncheng** [comment]
@songyizhe 可以参考下npm scripts文档，里面解释的很详细。
[npm scripts](https://www.npmjs.cn/cli/run-script/)

**Comment by justLearner** [comment]
npm run build:h5-test 或者 npm run build:h5_test 通过传环境参数区分
