### ISSUE TITLE
自定义Form表单，在微信小程序中无法通过 this.props.children 传入子组件

### ISSUE THREAD

**Issue by K-walker** [NervJS/taro#3918]
**问题描述**

使用taro的Form组件，自定义一个可验证的表单组件，H5中，可以通过Button触发 onSubmit事件，但是在微信小程序中无响应

**复现步骤**

IForm.tsx

```js

import Taro from "@tarojs/taro";
import './index.scss'
import { Form } from '@tarojs/components'
import _isFunction from 'lodash/isFunction';

interface IProps {
	onSubmit?(e:any):void,
}

export default class IForm extends Taro.Component<IProps> {

	static defaultProps = {
		onSubmit:() => {},
	}

	constructor (props) {
		super(props)
	}

	handleSubmit (e) {
		const { onSubmit } = this.props ;
		_isFunction(onSubmit) && onSubmit(e)
	}

	render () {
		return (
			<Form
				onSubmit={this.handleSubmit.bind(this)}
				className={`tui-form`}>
				{this.props.children}
			</Form>
		 )
	}
}


```
使用:
```js
<IForm onSubmit={this.handleSubmit.bind(this)}>
	<Button formType="submit">提交</Button>
</IForm>
```

**期望行为**

点击提交按钮，响应onSubmit事件

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macos 10.14.4]
 - Taro 版本 [v1.3.9]
 - Node.js 版本 [10.15.3]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@K-walker 提供编译后的 wxml

**Comment by K-walker** [comment]
@Chen-jj  
```wxml
<block wx:if="{{$taroCompReady}}">
    <view class="index">
        <i-form compid="{{$compid__46}}">
            <button form-type="submit">提交</button>
        </i-form>
    </view>
</block>
```

**Comment by K-walker** [comment]
@Chen-jj  这是 IForm的wxml
```
<block wx:if="{{$taroCompReady}}">
    <form bindsubmit="handleSubmit" class="tui-form" data-e-submit-so="this">
        <slot></slot>
    </form>
</block>
```

**Comment by K-walker** [comment]
通过验证发现，无法响应form的onSubmit事件，是因为通过 this.props.children 传入的子组件，没有被正确的渲染在  `<form></form>` 标签中，实际渲染如下:
伪代码:
```
<page>
  <form bindsubmit=”handleSubmit“></form>
  <button form-type="submit">提交</button>
</page>
```
button组件被渲染到了外面，因此，点击button，无法响应form的submit事件，这应该是Taro转化成微信的一个BUG吧，还请重视一下，谢谢了
@Chen-jj

**Comment by Chen-jj** [comment]
@K-walker 小程序的 slot 是这样的，你看 wxml 面板 slot 的内容在子组件外面，你可以写个原生 demo 测试下能否响应 onSubmit。

**Comment by K-walker** [comment]
@Chen-jj 我试过了，其实不是无法响应onSubmit的问题，因为这个Button都没有被渲染在form标签中，所以无论怎么点击都不会触发onSubmit事件，还是小程序的这个slot的问题，这就有点难受了，请问一下，如果非要动态给form传子组件的话，有没有其他什么办法

**Comment by Chen-jj** [comment]
@K-walker 嗯的确是小程序 slot 的问题。动态传组件都是通过 slot 实现的，你可以试试父组件传判断变量控制 form 内显示的子组件。

**Comment by Chen-jj** [comment]
@K-walker 不用 Form，传入 View，onClick 的回调提交表单也行。

**Comment by K-walker** [comment]
@Chen-jj 我需要通过原生的submit事件去获取表单里各项的值  e.detail.value ，如果这个表单组件没有被正确的渲染在form标签中，那么提交表单，我也是拿不到这个表单字段的value，所以，最终的问题还是因为，组件没有被渲染进form标签中

**Comment by K-walker** [comment]
@Chen-jj 我要实现的功能是通过响应submit事件之后，去校验表单各项，不过我现在已经通过另一种方式实现我的需求，现在算是解决了！谢了

**Comment by Chen-jj** [comment]
@K-walker 自己维护表单各项 value 不就行了吗。。Form 又不必要。

**Comment by K-walker** [comment]
@Chen-jj 这不是为了省事嘛，哈哈，不过现在也解决了，多谢

**Comment by missmimia** [comment]
> @Chen-jj 这不是为了省事嘛，哈哈，不过现在也解决了，多谢

想知道你是怎么解决的~~~~ 可以说一下吗？蟹蟹

**Comment by K-walker** [comment]
@missmimia 我的解决方案不是很好，你去看 COLOR UI 吧，里面有form表单的验证

**Comment by taichenglu** [comment]
讨厌解决之后不分享方法的楼主，太坏 :)
