### ISSUE TITLE
setClipboardData 功能在 微信h5 界面打开 无法复制

### ISSUE THREAD

**Issue by zhangborui123** [NervJS/taro#3919]
**问题描述**
[问题描述：setClipboardData 功能在 微信h5 界面打开 无法复制]

**复现步骤**
[复现问题的步骤]
1. 在微信打开h5 网页 调用 setClipboardData 方法 没有反应

if(data&&data.orderNo&&data.orderNo.length > 0){
      let status = this.getOrderStateString(orderStatus)
      let formatString = `订单编号：${data.orderNo}\n下单时间：${data.createTime}\n订单状 
       态：${status}`
      Taro.setClipboardData({
        data: formatString
      })
      // 因为在小程序中 复制都是正常的
      // 但是在微信中的h5 界面 Android 可以复制但是没有提示 iOS设置 不可以复制，也没有提示
      if(!isWeapp){
        Taro.showToast({
          title: '内容已复制',
          icon: 'none'
        })
      }
    }

**期望行为**
[希望taro 可以支持更多的复制功能]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
>  taro info 
👽 Taro v1.3.9

  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.9 => 1.3.9 
      @tarojs/cli: 1.3.9 => 1.3.9 
      @tarojs/components: 1.3.9 => 1.3.9 
      @tarojs/mobx: 1.3.9 => 1.3.9 
      @tarojs/mobx-h5: 1.3.9 => 1.3.9 
      @tarojs/plugin-babel: 1.3.9 => 1.3.9 
      @tarojs/plugin-csso: 1.3.9 => 1.3.9 
      @tarojs/plugin-sass: 1.3.9 => 1.3.9 
      @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9 
      @tarojs/router: 1.3.9 => 1.3.9 
      @tarojs/taro: 1.3.9 => 1.3.9 
      @tarojs/taro-h5: 1.3.9 => 1.3.9 
      @tarojs/taro-weapp: 1.3.9 => 1.3.9 
      @tarojs/webpack-runner: 1.3.9 => 1.3.9 
      eslint-config-taro: 1.3.9 => 1.3.9 
      eslint-plugin-taro: 1.3.9 => 1.3.9 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 

 - 操作系统: [e.g. macOS 10.14]
 - Taro 版本 [e.g. v.1.3.9]
 - Node.js 版本 [e.g. v10.15.3]
 - 报错平台 [h5]

**Comment by Garfield550** [comment]
已经修复，下个版本试一下吧。

Ref: #4611
