### ISSUE TITLE
RN 的 helloworld 报错

### ISSUE THREAD

**Issue by nicholasxuu** [NervJS/taro#3921]
**问题描述**
taro新建的最基础的app，rn运行时会报错。

**复现步骤**
1. `taro init taroDemo`
1.5. init的配置：不用ts，无css预处理，默认模板。
2. `npm run build:rn -- --watch`
3. 去taro-native-shell项目，运行`react-native run-ios --simulator="iPhone X"`
4. Invariant violation, element type is invalid

![image](https://user-images.githubusercontent.com/676478/61682172-26fc6500-ad43-11e9-9073-946dc10be607.png)

![image](https://user-images.githubusercontent.com/676478/61686391-17384d00-ad52-11e9-87c0-4baa5e70c1a5.png)

**期望行为**
至少 helloworld 能用

**报错信息**

Invariant violation, element type is invalid

搜了，网上有几乎完全一样的报错信息，但是如果是类似问题，应该是taro打包造成的问题。

https://blog.csdn.net/niuba123456/article/details/82086513

**系统信息**

 - 操作系统: macOS 10.14.5
 - Taro 版本 1.3.10
 - Node.js 版本 8.11.3
 - 报错平台 rn

**Comment by nicholasxuu** [comment]
找到问题了。
1. taro版本1.3.8才行，1.3.9开始都有问题，至少解决这个后也会遇到 `UIManager.getViewManagerConfig is not a function`的问题。（感谢这篇blog：https://juejin.im/post/5d2ec7ed6fb9a07ec56eacac）
2. taro init出来的文件是jsx文件，rn打包后会出现我这个issue里的错误。解决方法就是：
把src里的jsx文件改为js文件就行了。。。

**Comment by Pines-Cheng** [comment]
UIManager.getViewManagerConfig is not a function 是 expo-av 依赖的问题，已经提了 PR ，但是还没正式发版。
https://github.com/expo/expo/issues/4737

**Comment by Pines-Cheng** [comment]
1.3.9 的模板进行了重构，有点问题已经修复了，麻烦等发版本吧。

**Comment by nicholasxuu** [comment]
谢谢，发现用1.3.8有mobx common的bug （新版本里修好了，现在鱼和熊掌不能兼得）

**Comment by wods** [comment]
选择ts可以正常运行

**Comment by viewerw** [comment]
> UIManager.getViewManagerConfig is not a function 是 expo-av 依赖的问题，已经提了 PR ，但是还没正式发版。
> [expo/expo#4737](https://github.com/expo/expo/issues/4737)

@unimodules/react-native-adapter 已经发布3.0.0 了，react-native-unimodules 也发了新版了，taro-rn@1.3.12 里面用的还是~0.4的，需要更新成~0.5

**Comment by viewerw** [comment]
> > UIManager.getViewManagerConfig is not a function 是 expo-av 依赖的问题，已经提了 PR ，但是还没正式发版。
> > [expo/expo#4737](https://github.com/expo/expo/issues/4737)
> 
> @unimodules/react-native-adapter 已经发布3.0.0 了，react-native-unimodules 也发了新版了，taro-rn@1.3.12 里面用的还是~0.4的react-native-unimodules ，需要更新成~0.5 @Pines-Cheng

@Pines-Cheng

**Comment by tourze** [comment]
master已经升级到0.5了，要等下个版本发布。
可以参考我的做法，直接在package.json锁死版本：

```
	"resolutions": {
		"react-native-unimodules": "^0.5.3",
		"expo-av": "^6.0.0",
		"expo-brightness": "^6.0.0",
		"expo-file-system": "^6.0.0",
		"expo-image-picker": "^6.0.0",
		"expo-keep-awake": "^6.0.0",
		"expo-location": "^6.0.0",
		"expo-sensors": "^6.0.0"
	}
```
