### ISSUE TITLE
componentDidCatchError 监听不到函数里面的错误

### ISSUE THREAD

**Issue by sanye33** [NervJS/taro#3922]
**问题描述**
在部分情况下的错误没用触发 componentDidCatchError，无法收集到错误信息
在原生微信小程序中试过，onError 是没有问题，能监听到类似的错误信息

**期望行为**
希望 componentDidCatchError 能监听到合理的报错信息

**复现步骤截图**

- **在 app 里面调用 componentDidCatchError**
![image](https://user-images.githubusercontent.com/22977141/61690078-148e2580-ad5b-11e9-85df-fac413021de9.png)

-  **在页面生命周期钩子抛出错误，监听正常**
![image](https://user-images.githubusercontent.com/22977141/61689110-3090c780-ad59-11e9-8472-4cc633fe73fa.png)
![image](https://user-images.githubusercontent.com/22977141/61689196-4f8f5980-ad59-11e9-8bd4-e4ee363b8b6c.png)

-  **在页面函数中抛出错误，无法触发 componentDidCatchError**
![image](https://user-images.githubusercontent.com/22977141/61689651-2cb17500-ad5a-11e9-82dc-b0b6d8e96c5a.png)
![image](https://user-images.githubusercontent.com/22977141/61689668-34711980-ad5a-11e9-84ee-5c6a2115949b.png)

**系统信息**
👽 Taro v1.3.4

  Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v11.13.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.10 => 1.3.10 
      @tarojs/components: 1.3.10 => 1.3.10 
      @tarojs/components-rn: 1.3.10 => 1.3.10 
      @tarojs/mobx: 1.3.10 => 1.3.10 
      @tarojs/mobx-h5: 1.3.10 => 1.3.10 
      @tarojs/mobx-rn: 1.3.10 => 1.3.10 
      @tarojs/plugin-babel: 1.3.10 => 1.3.10 
      @tarojs/plugin-csso: 1.3.10 => 1.3.10 
      @tarojs/plugin-less: 1.3.10 => 1.3.10 
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10 
      @tarojs/rn-runner: 1.3.10 => 1.3.10 
      @tarojs/router: 1.3.10 => 1.3.10 
      @tarojs/taro: 1.3.10 => 1.3.10 
      @tarojs/taro-alipay: 1.3.10 => 1.3.10 
      @tarojs/taro-h5: 1.3.10 => 1.3.10 
      @tarojs/taro-redux-rn: 1.3.10 => 1.3.10 
      @tarojs/taro-rn: 1.3.10 => 1.3.10 
      @tarojs/taro-router-rn: 1.3.10 => 1.3.10 
      @tarojs/taro-swan: 1.3.10 => 1.3.10 
      @tarojs/taro-tt: 1.3.10 => 1.3.10 
      @tarojs/taro-weapp: 1.3.10 => 1.3.10 
      @tarojs/webpack-runner: 1.3.10 => 1.3.10 
      eslint-config-taro: 1.3.10 => 1.3.10 
      eslint-plugin-taro: 1.3.10 => 1.3.10 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4

**Comment by sanye33** [comment]
这个，有找到问题么？

**Comment by Chen-jj** [comment]
@sanye33 翻翻 async 的原理就明白了。
