### ISSUE TITLE
1.3.10 自定义组件HeaderTitle style无法作用到标签<HeaderTitle style="width=100%;">

### ISSUE THREAD

**Issue by rongxingxingkai** [NervJS/taro#3924]
升级到1.3.10之后，1.2版本是ok的

自定义组件HeaderTitle
&lt;HeaderTitle style="width=100%;"&gt;
微信工具看到标签是这样，没有style，style丢失了
&lt;header-title is="components/HeaderTitle/index"&gt;
#shadow-root

**Comment by yuche** [comment]
自定义组件是组件的抽象，不是一个真正的 DOM 节点，不能应用 style 这类属性。

**Comment by rongxingxingkai** [comment]
> 自定义组件是组件的抽象，不是一个真正的 DOM 节点，不能应用 style 这类属性。

但是在html文档里面确实会有一个<header-title 标签生成，如果不能应用style，那么自定义组件将在外层需要添加view包装，这样层级更多
