### ISSUE TITLE
使用npm link开发和npm不同包版本号包中构建错误

### ISSUE THREAD

**Issue by huey-LS** [NervJS/taro#3928]
**问题描述**
由于npm包的安装策略，当包版本号不一致时可能出现一下情况
![image](https://user-images.githubusercontent.com/5868138/61759199-528e5680-adfa-11e9-8f59-1dd2aa9f1f28.png)
即同时安装了2个`querystringify`

此时执行 `taro build --type weapp`构建微信小程序时会产生问题
![image](https://user-images.githubusercontent.com/5868138/61759301-ab5def00-adfa-11e9-834a-aa65b6f46ed5.png)
如图`querystringify`被复制到`url-parse`下，但是`page/index/index.js`里的加载路径是
![image](https://user-images.githubusercontent.com/5868138/61759426-f7109880-adfa-11e9-8210-a0e487848325.png)
导致无法正确加载

**复现步骤**
[复现问题的步骤]
1. taro init
2. npm i --save-dev url-parse
3. npm i --save-dev querystringify@2.1.0 (为了产生不同版本，故意所为)
4. `pages/index/index.js` 中 使用 `url-parse`和`querystringify`
4. npm run build:weapp
5. 查看 `dist/pages/index/index.js`

**期望行为**
能正确的解析包地址

**系统信息**
  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - ~/.nvm/versions/node/v8.9.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v8.9.3/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v8.9.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.9 => 1.3.9 
      @tarojs/plugin-babel: 1.3.9 => 1.3.9 
      @tarojs/plugin-csso: 1.3.9 => 1.3.9 
      @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9 
      @tarojs/router: 1.3.9 => 1.3.9 
      @tarojs/taro: 1.3.9 => 1.3.9 
      @tarojs/taro-alipay: 1.3.9 => 1.3.9 
      @tarojs/taro-h5: 1.3.9 => 1.3.9 
      @tarojs/taro-swan: 1.3.9 => 1.3.9 
      @tarojs/taro-tt: 1.3.9 => 1.3.9 
      @tarojs/taro-weapp: 1.3.9 => 1.3.9 
      @tarojs/webpack-runner: 1.3.9 => 1.3.9 
      eslint-config-taro: 1.3.9 => 1.3.9 
      eslint-plugin-taro: 1.3.9 => 1.3.9 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 

**补充信息**
复现仓库 [https://github.com/ignous/taro-build-error-with-npm-deep-dependencies](https://github.com/ignous/taro-build-error-with-npm-deep-dependencies)

**Comment by ignous** [comment]
npm link开发也会出现以上情况哈，因为npm link导致必然会同时纯在2次安装的包

**Comment by ignous** [comment]
https://github.com/NervJS/taro/blob/0bc1208d870aed888dbcf229195c34582c8b2bdd/packages/taro-cli/src/util/constants.ts#L91
是否可以添加 `g`  做全局匹配来解决？
