### ISSUE TITLE
Header FromData 设置表单格式无法实现

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [NervJS/taro#393]
![image](https://user-images.githubusercontent.com/11493796/43315752-8f3c4c2a-91c9-11e8-926a-b8d5ce288f43.png)
![image](https://user-images.githubusercontent.com/11493796/43315840-dd84f508-91c9-11e8-8ed0-2b26e81b5091.png)
![image](https://user-images.githubusercontent.com/11493796/43315860-ed2c4aec-91c9-11e8-8384-ab5736afb03e.png)

**Comment by luckyadam** [comment]
好嘞~
