### ISSUE TITLE
H5 页面在支付宝中打开，路由切换后，点击左上角的返回按钮，标题保留了上一个页面的navigationBarTitleText配置。

### ISSUE THREAD

**Issue by sisiea** [NervJS/taro#3931]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
H5 页面在支付宝中打开，路由切换后，点击左上角的返回按钮，标题保留了上一个页面的navigationBarTitleText配置。

H5 页面在支付宝中打开：
有页面A 切换路由 到页面B。
路由切换后，点击左上角的返回按钮，标题保留了上一个页面的navigationBarTitleText配置。

**复现步骤**
[复现问题的步骤]
1. H5 页面在支付宝中打开：网易严选的demo页面首页：
![image](https://user-images.githubusercontent.com/12793405/61763594-78baf300-ae08-11e9-96be-ed06086c68bf.png)

2. 点击为你推荐的商品进入商品详情
3. 点击左上角的【返回】按钮，回到首页，页面的标题还是“商品详情”

**期望行为**
返回到首页后，页面标题应该更新为首页的标题

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.13.4
 - Taro 版本 1.3.2
 - Node.js 版本 10.16.0
 - 报错平台 [h5]

**补充信息**
真实的项目中也遇到了这个问题，上面贴的信息是项目依赖的Taro版本。
不过问题在网易严选demo中也重现了。

[网易严选demo地址](https://github.com/js-newbee/taro-yanxuan)

**Comment by luckyadam** [comment]
Taro 版本有点旧，升级到最新版本吧，已经解决这个问题了
