### ISSUE TITLE
`npm run dev:h5`启动服务以后，修改文件并保存，h5服务会挂掉！

### ISSUE THREAD

**Issue by LoveXiaoLiu** [NervJS/taro#3935]
版本：tarojs/taro（1.3.9）

`npm run dev:h5`启动服务以后，修改文件并保存，h5服务会挂掉，需要重启服务，很麻烦！

报错如下：
![image](https://user-images.githubusercontent.com/16411017/61773227-c181a480-ae26-11e9-87a6-6c4086311545.png)

**Comment by luckyadam** [comment]
关闭代码编辑器的编译相关插件
