### ISSUE TITLE
如何添加回调监听异步请求，使得页面重新载入数据

### ISSUE THREAD

**Issue by 2359634711** [NervJS/taro#3943]
**问题描述**
在入口初有一些配置信息是异步请求获取的，在这期间，可能index等其他页面可能已经加载完毕。这就导致一部分数据加载不进来。在原生小程序中可以对app.js中的异步请求加上回调，使得异步请求结束后可以进行重新加载。

Taro可不可以实现原生小程序在app.js设置回调的代替方式。

[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
1.在app.tsx中进行异步请求，并将请求到的数据保存在storage
1. index页面对storage进行读取
2. 当index.tsx页面加载完毕时，异步请求还没有结束。
3. 导致index.tsx页面数据不完整。

```js
// app.tsx
componentDidMount() {
    // 设置navBottom End
    setTimeout(() => {
      Taro.setStorage({
        key: 'baseConfig',
        data: baseConfig
      })
    }, 5000)
    //设置全局变量至storage缓存 End
}
 ```

```js
// index.tsx
componentDidMount() {
        //从storage中读取配置信息
        Taro.getStorage({
            key: 'baseConfig'
        }).then((res: any) => {
            console.log(res)
            this.setState({
                navBottom: res.data.navBottom
            })
        })
    }
 ```

**期望行为**
期望在异步请求之后可以进行回调等方式通知index页面进行重新加载

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.16.0 - D:\nodejs\node.EXE
      npm: 6.9.0 - D:\nodejs\npm.CMD

 - 平台 [weapp]

**Comment by loveonelong** [comment]
使用redux、mobx等状态管理，或context

**Comment by 2359634711** [comment]
谢谢，那除了redux等状态管理，没有回调的方式了吗，只要能实现在app.tsx页面调用别的页面的函数就行。

**Comment by yuche** [comment]
还可以使用 [eventCenter](https://nervjs.github.io/taro/docs/apis/about/events.html#docsNav)

**Comment by 2359634711** [comment]
万分感谢。使用eventCenter完全可以方便的达到要求，&#129322;
