### ISSUE TITLE
useRef 问题

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#3945]
我按照官网文档使用 ref 但是会报以下错误

<img width="773" alt="image" src="https://user-images.githubusercontent.com/24502330/61842539-2b538a00-aecb-11e9-9940-08b3120e6d5e.png">

**Comment by regrex** [comment]
+1

**Comment by eyelly-wu** [comment]
h5上正常，微信小程序编译报错

**Comment by mercer08** [comment]
+1

**Comment by JamesAgoda** [comment]
+1

**Comment by masteroy** [comment]
+1

**Comment by pureZjr** [comment]
+1

**Comment by BennyEu** [comment]
什么时候能修复？

**Comment by only4ly** [comment]
修复了没....

**Comment by saviourdog** [comment]
这就关了??????

**Comment by Chen-jj** [comment]
#4466 

已修复，下个版本带出。
