### ISSUE TITLE
列表渲染中阻止冒泡事件报错

### ISSUE THREAD

**Issue by lhzbxx** [NervJS/taro#3946]
**问题描述**
在列表渲染的情况下，尝试用 e.stopPropagation() 阻止冒泡，提示 e.stopPropagation is not a function。
尝试用 https://github.com/NervJS/taro/issues/761#issuecomment-472283713 的方法包装一层 View，但是仅在列表中只有一个元素的时候不报错，其他情况下依旧报错。

**复现步骤**
```js

{list.map((i, index) => (
  <View
    className="item"
    key={i.label}
    onClick={() => onClick && onClick(index, false)}
  >
    <Text className="label">{i.label}</Text>
    <View onClick={(e) => e.stopPropagation()}>
      <Image
        className="icon"
        src={closeSVG}
        onClick={(e) =>
          closeable &&
          onClick &&
          onClick(index, true)
          // e.stopPropagation()
        }
      />
    </View>
  </View>
))}
```

**期望行为**

使用 e.stopPropagation() 不报错的情况下阻止冒泡。

**报错信息**

thirdScriptError
e.stopPropagation is not a function; [Component] Event Handler Error @ components/auto-complete/index#(anonymous)
TypeError: e.stopPropagation is not a function

**系统信息**

  Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.10.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.5.3

**Comment by yuche** [comment]
你打印下看 e 是什么

**Comment by lhzbxx** [comment]
> 你打印下看 e 是什么

e 是正常的，包含了 stopPropagation 函数，且 typeof e.stopPropagation === 'function'。

```js
changedTouches: [{…}]
currentTarget: {id: "", offsetLeft: 325, offsetTop: 151, dataset: {…}, x: 352.33984375, …}
detail: {x: 352.33984375, y: 174.95703125}
mark: {}
preventDefault: ƒ ()
stopPropagation: ƒ ()
target: {id: "", offsetLeft: 325, offsetTop: 151, dataset: {…}, x: 352.33984375, …}
timeStamp: 5138
touches: [{…}]
type: "tap"
```

**Comment by yuche** [comment]
你打印的地方同时也是你报错的地方吗

**Comment by lhzbxx** [comment]
> 你打印的地方同时也是你报错的地方吗

当然，是写在一起的，确实很诡异。

**Comment by yycang** [comment]
同样遇到错误

**Comment by Jinxhao18** [comment]
我遇到类似的，打印出来event对象包含detail:{value:1},打印event的key只有一个，e.detail=1，e.detail.value=undefined，数据只能看不能摸

**Comment by Jinxhao18** [comment]
taro 2.6.0    e[0].stopPrapagation()；可以阻止冒泡，event是个数组
