### ISSUE TITLE
支付宝小程序这种写法真机执行很慢 

### ISSUE THREAD

**Issue by lang-strive** [NervJS/taro#3947]
<img width="576" alt="屏幕快照 2019-07-25 上午11 00 01" src="https://user-images.githubusercontent.com/31495553/61848754-c0617d80-aee1-11e9-812a-fe3fb6e4f790.png">
支付宝小程序这种写法真机执行很慢 ，支付宝小程序模拟器，微信小程序和H5都没问题 我的taro版本是 1.3.9

**Comment by lang-strive** [comment]
> CC @ Chen-jj

这个是什么原因造成的求告知

**Comment by Chen-jj** [comment]
http://taro-docs.jd.com/taro/docs/debug.html#没有任何报错-但显示的结果不如预期 看 setdata 次数和数据量

**Comment by lang-strive** [comment]
<img width="874" alt="屏幕快照 2019-07-24 下午10 04 02" src="https://user-images.githubusercontent.com/31495553/61919155-e12fde80-af86-11e9-8029-08d6368bf083.png">
跟这个有关系嘛

**Comment by Chen-jj** [comment]
@lang-strive 不知道你 waring 的原因，还是那句话，看 setData 次数和数据量。
