### ISSUE TITLE
swiper circular true 在h5无法实现真正的衔接滑动

### ISSUE THREAD

**Issue by Anjing1993** [NervJS/taro#3948]
**问题描述**

swiper组件的circular属性设置为true，h5和微信小程序表现不一致
1.例如有5张图，h5里面左滑到最后一张时，继续左滑，出现自动从最后一张右滑回到第一张，没办法进行真正的衔接滑动
2.微信小程序左滑到最后一张时，继续左滑，正常衔接
3.swiper 内部的 间距配置有计划支持吗？类似 微信小程序 swiper的previous-margin/next-margin可以实现如图所示功能的
![image](https://user-images.githubusercontent.com/9416309/61870517-e5211980-af10-11e9-8032-dfee908a6b40.png)

**复现步骤**

swiper组件的circular属性设置为true即可复现
![image](https://user-images.githubusercontent.com/9416309/61856226-50102780-aef4-11e9-8bc5-760ff8c112fc.png)

**期望行为**

期望h5实现真正的衔接滑动和微信小程序保持一致

**报错信息**

无报错

**系统信息**

 Taro CLI 1.3.4 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.4 => 1.3.4 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: 1.3.4 => 1.3.4 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.3.3333

**Comment by jinjinjin0731** [comment]
没有复现。  数据是异步请求的么。  如果是话，在初次渲染的时候做下判断吧 。  swiperData.length>0 && <swiper/> 

微信小程序 swiper的previous-margin/next-margin 这样的后续支持。  如果需要实现，现在在 H5 端可用改写样式实现，具体参考 [利用taro的swiper组件实现3d-覆盖流效果](http://taro-club.jd.com/topic/96/%E5%88%A9%E7%94%A8taro%E7%9A%84swiper%E7%BB%84%E4%BB%B6%E5%AE%9E%E7%8E%B03d-%E8%A6%86%E7%9B%96%E6%B5%81%E6%95%88%E6%9E%9C/2)

**Comment by CrazyKakarotto** [comment]
我也遇到了

**Comment by Anjing1993** [comment]
@jinjinjin0731 
我的锅，因为指示器不可以配置自定义图片，自己自定义了指示器并配合了 onChange去设置高亮出现了上面说的情况...
![image](https://user-images.githubusercontent.com/9416309/62909661-17a39100-bdb0-11e9-8752-5a9019888adf.png)

=====================================================
微信小程序 swiper的previous-margin/next-margin 这样的后续支持。 如果需要实现，现在在 H5 端可用改写样式实现，具体参考 利用taro的swiper组件实现3d-覆盖流效果
===================
这个例子如果设置circular 为true切换一轮后会出现 右边有一张显示不出来的问题
![image](https://user-images.githubusercontent.com/9416309/62909586-be3b6200-bdaf-11e9-9ec3-74172aa5a9eb.png)
