### ISSUE TITLE
小程序 Checkbox 在 Map 使用出现自动执行事件问题

### ISSUE THREAD

**Issue by rexleimo** [NervJS/taro#395]
![image](https://user-images.githubusercontent.com/11493796/43354164-99a2bdd8-9279-11e8-9ef6-af97ca5d8684.png)

![image](https://user-images.githubusercontent.com/11493796/43354165-a33734f0-9279-11e8-9b09-3870d8c89f5e.png)

![image](https://user-images.githubusercontent.com/11493796/43354167-b367c452-9279-11e8-8bdd-7c13daa65e88.png)

无论是 onClick 和 onChange 都出现这个问题，
疑点：
    小程序在网络请求的时候，把对象赋值了，然后进行页面刷新，然后小程序CheckBox 当新对象处理，出现不断执行，在两个网络请求中出现死循环操作
```
   // Taro.request({
        //     url: BaseUrl.appServer() + "checkout/cart/selectone",
        //     header: {
        //         'Fecshop-Uuid': Taro.getStorageSync('fecshop-uuid')
        //     },
        //     data: {
        //         checked: one.active == 1 ? 0 : 1,
        //         item_id: one.item_id
        //     },
        // }).then(result => {

        // })

        // Taro.request({
        //     url: BaseUrl.appServer() + "checkout/cart/index",
        //     header: {
        //         'Fecshop-Uuid': Taro.getStorageSync('fecshop-uuid')
        //     }
        // }).then(result => {
        //     var cart_info = result.data.data.cart_info;
        //     this.setState({
        //         cart_info: cart_info,
        //         list: cart_info.products
        //     })
        // })
```

在web端并没有问题。
老哥！！！！ 你们的测试人员 有没有测过 小程序端的！
在web端 会吧 PX 单位 转为 rem 单位
在小程序端 缺无法进行 导致在小程序 字体特别小 ！！！ 这个问题本来想说的，但是觉得只是做小程序，那就没有反馈。

**Comment by rainbowMorelhahahah** [comment]
![_20180728160655](https://user-images.githubusercontent.com/11493796/43354512-488c3d28-9280-11e8-894e-8388145cf048.png)

**Comment by rainbowMorelhahahah** [comment]
问题出现在这里 并不是赋值 而是在执行！。。

**Comment by rainbowMorelhahahah** [comment]
![image](https://user-images.githubusercontent.com/11493796/43354630-8c069d1c-9282-11e8-84ed-fed910e83cd2.png)
改为
![image](https://user-images.githubusercontent.com/11493796/43354636-9ad18f1e-9282-11e8-8bdb-51612519b342.png)
让this 拥有__event name 方法 然后到 wxml 修改 对应的 for 为 对应的函数名

**Comment by luckyadam** [comment]
可以试试最新的 beta 版本
https://github.com/NervJS/taro/issues/389
