### ISSUE TITLE
建议FunctionComponent的type定义加入config

### ISSUE THREAD

**Issue by vonweb** [NervJS/taro#3950]
**问题描述**
创建FunctionComponent类型的页面，设置页面的config时不方便，希望在官方的FunctionComponent中加入config的类型定义

**复现步骤**

现在通过新建的taroPatch.d.ts实现的
```js
import Taro from '@tarojs/taro'

declare module '@tarojs/taro' {
  interface FunctionComponent {
    config?: Taro.Config
  }
}

```

**期望行为**
直接在`node_modules\@tarojs\taro\types\index.d.ts`中加入config类型定义

**报错信息**

![image](https://user-images.githubusercontent.com/5784758/61859331-82bd1e80-aefa-11e9-93c4-fa8968541494.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.10]
 - Node.js 版本 [10.16.0]
 - 报错平台 [weapp]

**补充信息**

**Comment by yuche** [comment]
你可以修改 taro-cli 的模板：https://github.com/NervJS/taro/blob/master/packages/taro-cli/templates/default/global.d.ts 提交 PR。

**Comment by yybawang** [comment]
可以在 useEffect 中使用 Trao 方法设置

```
useEffect(() => {
    Taro.setNavigationBarTitle({
      title: '登录'
    });
  }, []);
```
