### ISSUE TITLE
【taroize】taroize后，wx变量没有得到全部转换

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3953]
**问题描述**
[问题描述：taroize后，wx变量没有得到全部转换]

**复现步骤**
[复现问题的步骤]
1. 进入小程序项目，执行taro convert
2. 转换后taro仍存在wx字眼

```js
// wx这个变量没有被转换成Taro
// 场景1
const _wx = wx

// 场景2
for(let key in wx){
   ...
}
```

**期望行为**
[转换后代码wx全部正确替换成Taro]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.8]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
在 app.js 直接注入以下代码你是否觉得能满足需求：
```jsx
import Taro from '@tarojs/taro'

if (process.env.TARO_ENV === 'h5') {
	window.wx = Taro
}
```

**Comment by loosenRogers** [comment]
> 在 app.js 直接注入以下代码你是否觉得能满足需求：
> 
> ```js-jsx
> import Taro from '@tarojs/taro'
> 
> if (process.env.TARO_ENV === 'h5') {
> 	window.wx = Taro
> }
> ```

这样可以解决  不用在ast里面进行替换了

但是昨天又发现个问题[#3955](https://github.com/NervJS/taro/issues/3955)
其实是伴随着，很奇怪，转换的时候
```js
const _wx = wx
// 没有转换成功，所以我就手动的改了taroConvert/src目录下的转换代码，改成
const _wx = Taro
// 重新编译后，代码中这样去调用_wx. getNetworkType，报错没有该方法
// 但是如果我直接Taro. getNetworkType就可以执行
```
