### ISSUE TITLE
'@tarojs/redux-h5' does not contain an export named 'useDispatch'

### ISSUE THREAD

**Issue by chenyongduan** [NervJS/taro#3954]
- 操作系统: [Windows 10]
 - Taro 版本 [v1.3.10]
 - Node.js 版本 [v10.15.0]
 - 报错平台 [h5]

![TIM图片20190725174216](https://user-images.githubusercontent.com/7391871/61864240-a6389700-af03-11e9-9d94-fd4366208da7.png)

**Comment by yuche** [comment]
Duplicate of https://github.com/NervJS/taro/issues/3447

**Comment by chenyongduan** [comment]
![image](https://user-images.githubusercontent.com/7391871/61921021-41764e80-af8e-11e9-8384-8fc3d58c08b7.png)
升级了nervjs还是提示找不到useDispatch；

**Comment by yuche** [comment]
仔细看 issue

**Comment by chenyongduan** [comment]
![image](https://user-images.githubusercontent.com/7391871/61921278-3243d080-af8f-11e9-8949-deb1e134e715.png)
是这个吧，但还是不行
还是说H5这个后面才会支持
