### ISSUE TITLE
const taro = Taro；执行taro.getNetworkType({})报错

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3955]
**问题描述**
[问题描述：const taro = Taro；执行taro.getNetworkType({})报错]

**复现步骤**
[复现问题的步骤]
1. 定义个变量const taro = Taro
2. 使用taro调用方法时报错

```js
const taro = Taro;
taro.getNetworkType({
  success: res => {
    // 返回网络类型, 有效值：
    // wifi/2g/3g/4g/unknown(Android下不常见的网络类型)/none(无网络)
    app.globalData.networkType = res.networkType;
  }
});
```
报错信息如下：
TypeError: taro.getNetworkType is not a function

**期望行为**
[taro中方法能够正常调用]

**报错信息**
![image](https://user-images.githubusercontent.com/13342245/61863970-2c081280-af03-11e9-8c7c-21fbc6ffffac.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.8]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
请不要这么干，在编译时会去寻找 Taro.xxx 这的样 API 调用方式
