### ISSUE TITLE
trao 支持犸良.....lottie吗？

### ISSUE THREAD

**Issue by liuyunzyj** [NervJS/taro#3957]

**Comment by liuyunzyj** [comment]
trao 支持犸良.....lottie吗？

**Comment by liuyunzyj** [comment]
trao 如何集成lottie

**Comment by yuche** [comment]
你可以用 https://github.com/landn172/lottie-miniapp 把它当成一个第三方小程序组件，也可以把它写成一个 Taro 组件

**Comment by liuyunzyj** [comment]
好的，我刚刚到这个库中看到了，就是不知道会不会有什么坑

**Comment by liuyunzyj** [comment]
@yuche 这个库应该适配taro支持的各个小程序端吧

**Comment by liuyunzyj** [comment]
@yuche 这个库不支持支付宝小程序，有库支持支付宝小程序的吗？ ![image](https://user-images.githubusercontent.com/40293335/61920572-aa5cc700-af8c-11e9-8920-8b7350dadb24.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/61920945-f52b0e80-af8d-11e9-8297-8b94705c6967.png)

**Comment by lixsh8** [comment]
> @yuche 这个库应该适配taro支持的各个小程序端吧

有人开发成taro组件了吗？

**Comment by niyingg** [comment]
真的不支持，在这里看到答案，如今有支持的吗
