### ISSUE TITLE
RN运行时报错：undefined is not an object ( evalluating '_ExponentDeviceMotion2.default.Gravity')

### ISSUE THREAD

**Issue by lifudea** [NervJS/taro#3959]
![微信图片_20190725200539](https://user-images.githubusercontent.com/50136663/61873169-dbe77b00-af17-11e9-8602-a803a11cd601.jpg)

**Comment by lifudea** [comment]
试了好多次了、都不行

**Comment by Pines-Cheng** [comment]
@lifudea 请按照 issue 补齐环境相关信息（taro info）和 重现步骤，帮助快速定位解决问题。

**Comment by lifudea** [comment]
Taro v1.3.9


  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD

**Comment by lifudea** [comment]
创建一个taro项目后打包成rn，然后拖到react-native项目里、npm install下上包后运行就会报这个错误
react-native版本0.55.4

**Comment by Pines-Cheng** [comment]
拖到react-native项目里？

**Comment by lifudea** [comment]
不是这样的么..........    拖进去然后把pacage.json换下在npm install

**Comment by Pines-Cheng** [comment]
开发 还是 发布？

**Comment by lifudea** [comment]
开发

**Comment by wanglingsong** [comment]
我也遇到同样的错误信息

**Comment by lifudea** [comment]
@wanglingsong 兄弟你解决了没啊

**Comment by wanglingsong** [comment]
> @wanglingsong 兄弟你解决了没啊

应该是需要用那个壳子项目，参考这里：
https://nervjs.github.io/taro/docs/react-native.html#%E5%90%AF%E5%8A%A8%E5%BA%94%E7%94%A8

**Comment by lifudea** [comment]
xie'xi

**Comment by lifudea** [comment]
准备直接用rn写了

**Comment by SummerSMJ** [comment]
我说taro是LJ没人反对吧
