### ISSUE TITLE
webpack-runner 为何要锁定 less 的版本

### ISSUE THREAD

**Issue by LucasIcarus** [NervJS/taro#3960]
**问题描述**
https://github.com/NervJS/taro/blob/fb9c37ada3c9bad0f8f3d3682b20f10308d7624f/packages/taro-webpack-runner/package.json#L51

`@tarojs/webpack-runner` 里锁定了 less 的版本在 3.0.4 是出于什么特殊的考虑么? , `'3.0.4': '2018-05-07T01:53:09.069Z'`  3.0.4 已经是一年前的版本了.

锁定版本后实际 bundle 过程中的 less-loader 寻址会固定指向 less@3.0.4, 无法使用 less 更新的一些 feature.

e.g.
```less
@i: #38f;
@j: rgba(@i, .8);
.k {
  color: @j;
}
```
会抛出一个错误: `color functions take numbers as parameters`.

上述 less 代码在 less@3.9.0 可以被正常处理.

**补充信息**
https://github.com/NervJS/taro/blob/fb9c37ada3c9bad0f8f3d3682b20f10308d7624f/packages/taro-webpack-runner/package.json#L47

有一点附带的疑问.

sass 应该是切换到 dart-sass 去做预处理了?  
sass-plugin 和 less-plugin 是不是已经处于废弃状态?

**Comment by Littly** [comment]
主要是开始写的时候就是这个版本了... 如果需要新的特性可以升级
