### ISSUE TITLE
renderFunction 定义在 render 方法之后，或为匿名函数，会被识别成 renderProps

### ISSUE THREAD

**Issue by Darmody** [NervJS/taro#3966]
**问题描述**
`renderFunction` 如果定义为匿名函数，或者定义在了 render 方法之后，会被识别成 `renderProps`， import 无用的 SuperClass

**复现步骤**
在 render 方法之后定义 `renderFunction`，或者将 render 方法定义为匿名函数

**期望行为**
正确识别 render 函数

**报错信息**
<img width="619" alt="屏幕快照 2019-07-26 10 46 35" src="https://user-images.githubusercontent.com/6788752/61922437-0591b800-af93-11e9-87ec-06b08b97b043.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Mac
 - Taro 版本 1.3.6
 - Node.js 版本 11
 - 报错平台 weapp

**补充信息**
`renderFunction`如果定义为匿名函数，或者定义在了 render 方法之后，`self.methods` 里就不会包含这个 render 函数，因此会被认为是 `renderProps`，从而会把 `SuperClass` import 进来。

**Comment by yuche** [comment]
Duplicate # https://github.com/NervJS/taro/issues/3914

**Comment by yuche** [comment]
下个版本 ESLint 会规范你的组件生命周期顺序

**Comment by Darmody** [comment]
@yuche 这不算是解决方法吧？如果我用 typescript ，更倾向于把方法都定义为私有方法，而且匿名函数也是需要的

**Comment by yuche** [comment]
你私有与否不影响 ESLint 的运行

**Comment by Darmody** [comment]
> 你私有与否不影响 ESLint 的运行

因为 private 方法从风格上来说，应该放在public 方法后面
