### ISSUE TITLE
在页面中(pages/index/index.tsx) 中引入一个组件 (pages/test.tsx)及组件中的变量比如 i 时 ，小程序会报 “component is not found” 错误

### ISSUE THREAD

**Issue by xiamu14** [NervJS/taro#3968]
**问题描述**
在页面中(pages/index/index.tsx) 中引入一个组件 (pages/test.tsx)及组件中的变量 i ，使用语句如下： “export Test, {i} from "./test”，小程序会报如下错误：
VM375:1 jsEnginScriptError
Component is not found in path "pages/index/test" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "pages/index/test" (using by "pages/index/index")
    at K (WAService.js:1:1211869)
    at K (WAService.js:1:1212073)
    at WAService.js:1:1229865
    at Module.Fe (WAService.js:1:1230444)
    at Function.value (WAService.js:1:1258713)
    at Ct (WAService.js:1:1274208)
    at WAService.js:1:1278269
    at At (WAService.js:1:1278762)
    at Function.<anonymous> (WAService.js:1:1282088)
    at i.<anonymous> (WAService.js:1:1251386)

**复现步骤**
[复现问题的步骤]
1. 在组件(pages/index/test.tsx) 中导出组件类和变量 i。
2. 在页面(pages/index/index.tsx) 中引入 组件 Test 和变量 i， 并使用 i ，如：consol.log(i)。
3. 使用小程序调试模型 yarn dev:weapp。
4. 在微信开发工具打开可以看到此错误：
VM375:1 jsEnginScriptError
Component is not found in path "pages/index/test" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "pages/index/test" (using by "pages/index/index")
    at K (WAService.js:1:1211869)
    at K (WAService.js:1:1212073)
    at WAService.js:1:1229865
    at Module.Fe (WAService.js:1:1230444)
    at Function.value (WAService.js:1:1258713)
    at Ct (WAService.js:1:1274208)
    at WAService.js:1:1278269
    at At (WAService.js:1:1278762)
    at Function.<anonymous> (WAService.js:1:1282088)
    at i.<anonymous> (WAService.js:1:1251386)

```jsx
// pages/index/index/tsx
import Taro, { Component, Config } from "@tarojs/taro";
import { View, Text } from "@tarojs/components";
import Test, {i} from "./test";
import "./index.scss";

console.log(i);

export default class Index extends Component {
  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: "首页"
  };

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  render() {
    return (
      <View className="index">
        <Text>Hello world!</Text>
        <Test />
      </View>
    );
  }
}

```

```jsx
// pages/index/test.tsx
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'

export const i = 12;

export default class Test extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Text>这是第一个组件!</Text>
      </View>
    )
  }
}

```

**期望行为**
应该可以正常引入才对，h5 网页就不会有错误。

**报错信息**

<img width="577" alt="屏幕快照 2019-07-26 上午11 37 49" src="https://user-images.githubusercontent.com/10813360/61924720-9c627280-af9b-11e9-94c6-198f8f610eb4.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.10

  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /var/folders/cg/psfybknj4tlg8br8c4hf4bs80000gn/T/yarn--1564112391101-0.7576312418760951/node
      Yarn: 1.17.3 - /var/folders/cg/psfybknj4tlg8br8c4hf4bs80000gn/T/yarn--1564112391101-0.7576312418760951/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/cli: ^1.3.10 => 1.3.10
      @tarojs/components: 1.3.10 => 1.3.10
      @tarojs/plugin-babel: 1.3.10 => 1.3.10
      @tarojs/plugin-csso: 1.3.10 => 1.3.10
      @tarojs/plugin-sass: 1.3.10 => 1.3.10
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10
      @tarojs/router: 1.3.10 => 1.3.10
      @tarojs/taro: 1.3.10 => 1.3.10
      @tarojs/taro-alipay: 1.3.10 => 1.3.10
      @tarojs/taro-h5: 1.3.10 => 1.3.10
      @tarojs/taro-qq: 1.3.10 => 1.3.10
      @tarojs/taro-quickapp: 1.3.10 => 1.3.10
      @tarojs/taro-swan: 1.3.10 => 1.3.10
      @tarojs/taro-tt: 1.3.10 => 1.3.10
      @tarojs/taro-weapp: 1.3.10 => 1.3.10
      @tarojs/webpack-runner: 1.3.10 => 1.3.10
      eslint-config-taro: 1.3.10 => 1.3.10
      eslint-plugin-taro: 1.3.10 => 1.3.10
      nerv-devtools: ^1.4.0 => 1.4.3
      nervjs: ^1.4.0 => 1.4.3
      stylelint-config-taro-rn: 1.3.10 => 1.3.10
      stylelint-taro-rn: 1.3.10 => 1.3.10

 - 操作系统: [e.g. mac os 10.14.6]
 - Taro 版本 [e.g. v.1.3.10]
 - Node.js 版本 [v10.16.0]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
不要在组件里导出变量或函数给其他文件引用，因为最后编译成小程序的时候不能保留组件的 require 代码，小程序会报错，所以 Taro 会在编译时把所有的组件引用都删掉

**Comment by xiamu14** [comment]
恩，我在项目中已经去掉了。但这个描述在 taro 官网文档上我好像没找到，如果是没有的话，可以在官网文档上加一下吗，以免其他开发者也经历这样的过程?

**Comment by luckyadam** [comment]
@xiamu14 确实，文档漏加了，我找个合适的地方加上去

**Comment by xiamu14** [comment]
谢谢！

**Comment by pollux2015** [comment]
我自定的组件 比如 
```
// a.js
class Some extends Component{
}
export default Some
```

```
// b.js
import Some from './a.js'

npm run dev:wepp

在这里 就会报错 component is not found

```
