### ISSUE TITLE
taroize后的，部分场景中生命周期钩子没有转换或者正常转换

### ISSUE THREAD

**Issue by loosenRogers** [NervJS/taro#3969]
**问题描述**
[问题描述：微信小程序经过taroize转换后，小程序生命周期钩子没有转换或者正常转换为Taro对应的钩子]

**复现步骤**
[复现问题的步骤]
1. 微信小程序项目中执行taro convert
2. 部分场景生命周期没有得到转换或者正确的转换

场景1
小程序入口文件app.js
![image](https://user-images.githubusercontent.com/13342245/61924286-b13e0680-af99-11e9-84d0-e696bc51fb4b.png)
```js
// 正常转换
componentWillMount = (options = this.$router.params || {}) => {
    // 会将this.$router.params作为options的默认值
}
```

场景2
Page()传入的为一个变量，这种时候，钩子完全没有转换
```js
var a = {
 onload: function(options){}
}

var b = {
  // some methods
}

var pageObj = merge(b, a)

page(pageObj)
```

**期望行为**
[taroize后，小程序中的钩子能够得到正确的转换，特定钩子的默认参数，也可以带入]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14.5]
 - Taro 版本 [v1.3.8]
 - Node.js 版本 [12.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
看一下你之前提的 issue，回复你的需求

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/d0e0343844a1fe16b6975f53c7de396aeb7036f1
