### ISSUE TITLE
IOS 端 View onClick 事件点击没反应

### ISSUE THREAD

**Issue by zhuliminl** [NervJS/taro#3977]
OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.10 => 1.3.10
      @tarojs/components-rn: ^1.3.10 => 1.3.10
      @tarojs/plugin-babel: 1.3.10 => 1.3.10
      @tarojs/plugin-csso: 1.3.10 => 1.3.10
      @tarojs/plugin-sass: 1.3.10 => 1.3.10
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10
      @tarojs/redux: ^1.3.10 => 1.3.10
      @tarojs/redux-h5: ^1.3.10 => 1.3.10
      @tarojs/router: 1.3.10 => 1.3.10
      @tarojs/taro: 1.3.10 => 1.3.10
      @tarojs/taro-alipay: 1.3.10 => 1.3.10
      @tarojs/taro-h5: 1.3.10 => 1.3.10
      @tarojs/taro-qq: 1.3.10 => 1.3.10
      @tarojs/taro-quickapp: 1.3.10 => 1.3.10
      @tarojs/taro-redux-rn: ^1.3.10 => 1.3.10
      @tarojs/taro-rn: ^1.3.10 => 1.3.10
      @tarojs/taro-router-rn: ^1.3.10 => 1.3.10
      @tarojs/taro-swan: 1.3.10 => 1.3.10
      @tarojs/taro-tt: 1.3.10 => 1.3.10
      @tarojs/taro-weapp: 1.3.10 => 1.3.10
      @tarojs/webpack-runner: ^1.3.10 => 1.3.10
      eslint-config-taro: 1.3.10 => 1.3.10
      eslint-plugin-taro: 1.3.10 => 1.3.10
      nerv-devtools: ^1.4.0 => 1.4.3
      nervjs: ^1.4.0 => 1.4.3
      react: 16.3.1 => 16.3.1
      react-native: 0.55.4 => 0.55.4
      stylelint-config-taro-rn: 1.3.10 => 1.3.10
      stylelint-taro-rn: 1.3.10 => 1.3.10

**Comment by luckyadam** [comment]
请提供相关代码

**Comment by myjacksun** [comment]
同遇到这个问题 ios12.2 大部分onClick事件都无效 ios13没问题

**Comment by zhuliminl** [comment]
很大可能是标签的层级写得不对。我后来解决了
