### ISSUE TITLE
constructor 无法获取 props（0.0.63 与之后的新版本不兼容）

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro#398]
![image](https://user-images.githubusercontent.com/13287948/43366798-d5438708-9375-11e8-8f9d-397886fb4d66.png)

**Comment by kenberkeley** [comment]
亲测 0.0.63 不会报错，之后的版本都报错

![image](https://user-images.githubusercontent.com/13287948/43366922-6e197194-9377-11e8-8196-4076e79efd19.png)

**Comment by kenberkeley** [comment]
https://github.com/NervJS/taro/issues/285#issuecomment-412912285

**Comment by kenberkeley** [comment]
隔壁老李建议使用 defaultProps，且自行在 constructor 中做容错处理

**Comment by luckyadam** [comment]
后续会在文档中注明这一点~
