### ISSUE TITLE
Taro Javascript 可迁移Typescript吗？

### ISSUE THREAD

**Issue by MoonCheung** [NervJS/taro#3981]
我等准备写Taro项目使用Javascript，后期可考虑迁移Typescript，不知是否有出现未知问题多？

**Comment by calimanco** [comment]
有能力建议直接上Typescript，习惯于Javascript的随意，会让你放弃迁移的。
结论：语言看个人能力，跟框架无关。

**Comment by MoonCheung** [comment]
> 有能力建议直接上Typescript，习惯于Javascript的随意，会让你放弃迁移的。
> 结论：语言看个人能力，跟框架无关。

好的，Typescript这个语言我会后期考虑写
