### ISSUE TITLE
快应用端（quickapp）使用taro-ui，编译button组件的时候报错

### ISSUE THREAD

**Issue by SunnyQjm** [NervJS/taro#3984]
**问题描述**
在快应用端使用taro-ui，编译button组件出错（button组件依赖于具体端的组件库里包干form组件，而快应用端组件库没有form组件）
![image](https://user-images.githubusercontent.com/29176413/61989178-07747d80-b05e-11e9-94dd-30bca5970d90.png)

**期望行为**
快应用端使用taro-ui能正常编译使用

**系统信息**

 - 操作系统: [ Linux 4.15 Deepin 15 15.11 ]
 - Taro 版本 [ v.1.3.10]
 - Node.js 版本 [e.g. v12.6.0]
 - 报错平台 [h5]

**Comment by tourze** [comment]
同样遇到这个问题了。
![image](https://user-images.githubusercontent.com/13899502/61994458-00c12700-b0ad-11e9-9bc6-a737cf33016f.png)

**Comment by jinjinjin0731** [comment]
taro-ui 应该还没有适配 快应用端喔。

**Comment by tourze** [comment]
> taro-ui 应该还没有适配 快应用端喔。

我不是taro-ui的，只是目录名叫这个。。。主要问题是button标签没兼容吧

**Comment by tourze** [comment]
这个问题的重点是没兼容button标签吧
