### ISSUE TITLE
Swiper组件外部引用样式时,使用overflow:hidden 在H5中出现空白bug

### ISSUE THREAD

**Issue by PenToseLin** [NervJS/taro#3989]
**问题描述**
Swiper组件外部引用样式时,使用overflow:hidden 在H5中出现空白bug
小程序里面正常使用
h5就不行，主要打算给Swiper添加圆角然后overflow:hidden使SwiperItem可以出现圆角的样子

但是内联样式就没问题

**复现步骤**
[复现问题的步骤]
1.使用Swiper
2.给Swiper组件添加overflow:hidden;样式
3.查看h5

```Typescript

return (
      <View className='banner' style={{padding: '20px 30px'}}>
        {list.length &&
          <View style={style.swiper}>
            <Swiper
              indicatorColor='#999'
              indicatorActiveColor={'#999'}
              circular
              indicatorDots
              autoplay>
              {
                list.map((item, index) => (
                  <SwiperItem key={index}>
                    <Image  style={{width: '100%'}} src={item.img} />
                  </SwiperItem>
                ))
              }
            </Swiper>
          </View>
        }
      </View>
    );
```

```less
.banner {
  padding: 20px 30px;
  .swiper-wrapper{
    border-radius: 20px;
    overflow: hidden;
    .img{
      width: 100%;
    }
  }
}

```

**期望行为**
小程序和h5能够统一

**报错信息**

![1564245493894](https://user-images.githubusercontent.com/19309224/61997187-81454f00-b0d0-11e9-882b-a3c919687b4e.jpg)
![1564245531622](https://user-images.githubusercontent.com/19309224/61997188-83a7a900-b0d0-11e9-8fbc-e41b93da3a34.jpg)

**系统信息**
 Taro v1.3.10

  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v10.11.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
    npmGlobalPackages:
      typescript: 3.5.1
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
内联样式没有问题， 使用 class 类名出现的问题是吗？

**Comment by PenToseLin** [comment]
@jinjinjin0731 是的

**Comment by jinjinjin0731** [comment]
@PenToseLin  试一下 Build 打一个包看看， 这个如果正常的话，那么这个表现有可能是热更新插入样式引起的问题。。。

**Comment by Mao5211** [comment]
为啥我没在这个issue下发过言 你们讨论会自动给我发邮件啊- 。-

**Comment by PenToseLin** [comment]
@jinjinjin0731 打包又出问题
线上出现这个

![11564485214_ pic](https://user-images.githubusercontent.com/19309224/62125936-1d559d00-b301-11e9-9411-a87ae5621d8b.jpg)

本地直接打开出现这个

![1564486574332](https://user-images.githubusercontent.com/19309224/62126010-52fa8600-b301-11e9-9674-4f0f65444b6d.jpg)

这几个文件看了下都存在，
index.html看了下路径是这样的
![51564485339_ pic](https://user-images.githubusercontent.com/19309224/62126059-7b828000-b301-11e9-8043-d7982f40fc45.jpg)

**Comment by CraKeyBoy** [comment]
确实是热更的问题，正常 build 放到 nginx 下运行此问题没有复现。
