### ISSUE TITLE
TypeError: XXX is not a function

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro#399]
![image](https://user-images.githubusercontent.com/13287948/43367643-e366330a-9382-11e8-9bec-7404e5612d63.png)

**Comment by kenberkeley** [comment]
render 中不引用到 handler2 则正常：

![image](https://user-images.githubusercontent.com/13287948/43367647-0e6c8540-9383-11e8-831d-eed047b121fa.png)

**Comment by kenberkeley** [comment]
值得一提的是，一模一样的代码，在页面组件（非子组件）中运行正常：

![image](https://user-images.githubusercontent.com/13287948/43367683-8c3f24be-9383-11e8-9f57-45894452eca3.png)

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/63cb96a1ed5282a3fcc2b474e02e51ba03422c0a
提交了一个新的 ESLint 规则：函数命名规范(`taro/function-naming`)，宥于 wxml 的限制，函数名现在有三项限制：
* 方法名不能含有数字
* 方法名不能以下划线开头或结尾
* 方法名的长度不能大于20

**Comment by kenberkeley** [comment]
你把 handler1 2 换成 a b 一样如此

**Comment by luckyadam** [comment]
没有复现诶~

**Comment by kenberkeley** [comment]
@luckyadam https://github.com/kenberkeley/taro-0.0.73

**Comment by luckyadam** [comment]
@kenberkeley 哦哦，0.0.73 啊，之前版本是有这个问题，只要方法在 JSX 里绑定过，方法名就会被重命名，导致在生命周期里调用就不存在了，beta 版本已经修复了这个问题~

**Comment by kenberkeley** [comment]
呃。。。问题是 beta 版不稳定。。。所以依然还是 0.0.73 跑着

**Comment by luckyadam** [comment]
@kenberkeley 唔~ 那我们在 0.0.xx 版本里修复吧~ 现在 beta 版越来越稳定了哦，可以尝试迁移一下~ 嘿嘿

**Comment by kenberkeley** [comment]
@luckyadam 全局样式问题不解决，还是没办法

**Comment by luckyadam** [comment]
@kenberkeley 这个略麻烦~ 不过我们尽快搞一搞
