### ISSUE TITLE
Taro.pxTransform() 在字节小程序上无法正常工作

### ISSUE THREAD

**Issue by neurotoxinvx** [NervJS/taro#3990]
**问题描述**
Taro.pxTransform() 方法在字节小程序上无法正常工作，无论是 iPhone 还是 Android ，任何不同尺寸的机型下，Taro.pxTransform(100) 返回的结果都是相同的。

**复现步骤**
[复现问题的步骤]
1. 创建一个 Page，在 componentDidMount 中输出 console.log(Taro.pxTransform(100))
2.使用字节小程序开发者工具打开我们经 Taro 编译后的小程序 output 目录
3.切换当前机型为 iPhone 6 ，查看控制台输出为 100rpx
4.切换当前机型为 iPhone 7 Plus，查看控制台输出依然为 100rpx

```js
console.log(Taro.pxTransform(100))
```

**期望行为**
在不同尺寸的机型上，Taro.pxTransform(100)，输出的结果应该是不同的

**报错信息**

![image](https://user-images.githubusercontent.com/8528330/62003796-ec356b00-b14e-11e9-8510-0ee243125782.png)

![image](https://user-images.githubusercontent.com/8528330/62003801-f8b9c380-b14e-11e9-9056-078b1c1d335d.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.9 => 1.3.9
      @tarojs/mobx: 1.3.9 => 1.3.9
      @tarojs/mobx-h5: 1.3.9 => 1.3.9
      @tarojs/mobx-rn: 1.3.9 => 1.3.9
      @tarojs/plugin-babel: 1.3.9 => 1.3.9
      @tarojs/plugin-csso: 1.3.9 => 1.3.9
      @tarojs/plugin-stylus: 1.3.9 => 1.3.9
      @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9
      @tarojs/rn-runner: 1.3.9 => 1.3.9
      @tarojs/router: 1.3.9 => 1.3.9
      @tarojs/taro: 1.3.9 => 1.3.9
      @tarojs/taro-alipay: 1.3.9 => 1.3.9
      @tarojs/taro-h5: 1.3.9 => 1.3.9
      @tarojs/taro-swan: 1.3.9 => 1.3.9
      @tarojs/taro-tt: 1.3.9 => 1.3.9
      @tarojs/taro-weapp: 1.3.9 => 1.3.9
      @tarojs/webpack-runner: 1.3.9 => 1.3.9
      eslint-config-taro: 1.3.9 => 1.3.9
      eslint-plugin-taro: 1.3.9 => 1.3.9
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3
    npmGlobalPackages:
      typescript: 3.4.2

 - 操作系统: [Mac OS 10.14.5]
 - Taro 版本 [1.3.9]
 - Node.js 版本 [v12.4.0]
 - 报错平台 [字节小程序]

**Comment by luckyadam** [comment]
pxTransform 的计算只和 designWidth 和 deviceRatio 两个配置有关，所以不同尺寸输出的值必然也是一致的，具体尺寸适配交由 rpx 单位来做，建议阅读一下 rpx 相关文章以及 Taro 关于尺寸的文档
