### ISSUE TITLE
weapp.compile.exclude是否支持文件类型

### ISSUE THREAD

**Issue by chenjigeng** [NervJS/taro#3991]
weapp.compile.exclude目前好像只能支持传文件数组，能否支持传文件类型？比如我从原生小程序转taro，我不想之前的js文件被编译，只想新增的ts文件被编译。

**Comment by luckyadam** [comment]
暂时还不行，可以完整描述一下你的需求

**Comment by chenjigeng** [comment]
需求是这样的，对于一些需要将原生转为taro框架的业务，由于之前原生的页面有很多，已经上百个了，而且都是js文件。然后我转为taro后，就算没有写taro的页面，编译一次都会将我之前的原生页面都编译，编译一次得几分钟，这我感觉没有必要，而且极大影响开发体验。
所以我想taro业务就用ts来写，以此作区分。就想看下目前支不支持通过配置来避免原生页面或者*.js来免除编译的烦恼。不然项目启动一次太慢了，而且也不合理。

**Comment by Chen-jj** [comment]
Taro 2、3 使用 webpack 编译，exclude 是 babel-loader 的 exclude ，可以通过 webpack-chain 修改配置达到目的了。
