### ISSUE TITLE
H5端 Taro.render()方法无效

### ISSUE THREAD

**Issue by Fntys** [NervJS/taro#3992]
**问题描述**
在H5端使用Taro.render()无效
![image](https://user-images.githubusercontent.com/13896710/62004324-2b1aef00-b156-11e9-9e0a-0874cfce1370.png)
![image](https://user-images.githubusercontent.com/13896710/62004331-39690b00-b156-11e9-8247-057fdd441814.png)

**期望行为**
向body里面插入组件元素

**系统信息**
👽 Taro v1.3.0-beta.6
  Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - D:\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\nodejs\npm.CMD
h5

**Comment by yuche** [comment]
这样复杂的逻辑你需要建一个最小化复现仓库

**Comment by liuchuzhang** [comment]
请问 taro 支持这个写法么
