### ISSUE TITLE
TARO_BUILD_TYPE=ui taro build --ui这个打包ui组件的命令，windows系统上应该不行，mac上是可以的

### ISSUE THREAD

**Issue by tanshenghu** [NervJS/taro#3995]
错误内容如下: 
> TARO_BUILD_TYPE=ui taro build --ui

'TARO_BUILD_TYPE' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @esign/taro-front-end@0.0.9 test: `TARO_BUILD_TYPE=ui taro build --ui`
npm ERR! Exit status 1
npm ERR!

**Comment by luckyadam** [comment]
尝试一下
https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows
