### ISSUE TITLE
更新到1.3.10，以render开头的props 采用一个JSX或者箭头函数都会报错

### ISSUE THREAD

**Issue by MuJinYan** [NervJS/taro#3996]
**问题描述**
我将taro更新到1.3.10，并升级了所有依赖及cli
在自定义组件上采用render开头的props中传入jsx，不管是只有一个<View />还是箭头函数或者是只有一个顶层jsx元素，eslint均会报错

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/16420319/62016828-decbbf80-b1e6-11e9-9bed-fe37de79145d.png)
![image](https://user-images.githubusercontent.com/16420319/62016848-eee39f00-b1e6-11e9-9b1f-d0575c6f0c64.png)
![image](https://user-images.githubusercontent.com/16420319/62016985-8517c500-b1e7-11e9-818f-f0228874a161.png)

```
 <MiniCartFooter transparent={loading} renderLeftContent={() => <View className={styles.content}>
            <View className={styles.info}>实付金额 <Text className={styles.price}>
              {currency(orderOtherInfo.price)}
            </Text></View>
          </View>}
        >
          {loading ? <View className={classNames(styles.content, styles.contentCenter)}>
            <View className={styles.fontColorGray}><Text>生成订单中</Text><View className={styles.dot}>...</View></View>
          </View> : <View className={classNames(styles.content, styles.contentCenter)} onClick={this.createOrder}>
            确认付款
          </View>}
        </MiniCartFooter>
```
```
<Popup
      visible={visible}
      onClose={changePopupStatus}
      title='请选择支付方式'
      renderFooter={<View className={styles.footer}>
          <View className={styles.left}>注意：</View>
          <View className={styles.right}>凡带 VISA/MasterCard 标志的 Debit 卡请选择 VISA/MasterCard 支付方式</View>
        </View>
      }
    >
      {choices.map((payType, index) => {
        return <Block key={`payType-${index.toString()}`}>
          <Row onClick={this.handleChangePayType.bind(this, payType)}>
            <View className={styles.payTypeRow}>
              <View className={styles.icon}>
                <Image src={PayTypeIcons.get(payType)} />
              </View>
              <View className={classNames(styles.type, {
                [styles.active]: R.equals(payType.type, pay_type)
              })}
              >
                <Text>{payType.value}</Text>
              </View>
            </View>
          </Row>
          <SeparatorBar height={1} color='#F4F4F4' />
        </Block>
      })}
    </Popup>
```
```
<MiniCartFooter transparent={loading} renderLeftContent={<View>测试</View>}>
          {loading ? <View className={classNames(styles.content, styles.contentCenter)}>
            <View className={styles.fontColorGray}><Text>生成订单中</Text><View className={styles.dot}>...</View></View>
          </View> : <View className={classNames(styles.content, styles.contentCenter)} onClick={this.createOrder}>
            确认付款
          </View>}
        </MiniCartFooter>
```

**期望行为**
期望eslint不报错

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
 Taro CLI 1.3.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v8.12.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.10 => 1.3.10 
      @tarojs/components: 1.3.10 => 1.3.10 
      @tarojs/plugin-babel: 1.3.10 => 1.3.10 
      @tarojs/plugin-csso: 1.3.10 => 1.3.10 
      @tarojs/plugin-less: 1.3.10 => 1.3.10 
      @tarojs/plugin-sass: 1.3.10 => 1.3.10 
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10 
      @tarojs/redux: 1.3.10 => 1.3.10 
      @tarojs/redux-h5: 1.3.10 => 1.3.10 
      @tarojs/router: 1.3.10 => 1.3.10 
      @tarojs/taro: 1.3.10 => 1.3.10 
      @tarojs/taro-alipay: 1.3.10 => 1.3.10 
      @tarojs/taro-h5: 1.3.10 => 1.3.10 
      @tarojs/taro-swan: 1.3.10 => 1.3.10 
      @tarojs/taro-tt: 1.3.10 => 1.3.10 
      @tarojs/taro-weapp: 1.3.10 => 1.3.10 
      @tarojs/webpack-runner: 1.3.10 => 1.3.10 
      eslint-config-taro: 1.3.10 => 1.3.10 
      eslint-plugin-taro: 1.3.10 => 1.3.10 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.4.3

 - 操作系统: mac os
 - Taro 版本 1.3.10
 - Node.js 版本 8.12.0
 - 报错平台 weapp

**补充信息**

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/2d3bd0562600038393cdc069b7325af2bccac45e

**Comment by MuJinYan** [comment]
我使用yarn 重装了2次，此文件依然是错误的
![image](https://user-images.githubusercontent.com/16420319/62017857-e68d6300-b1ea-11e9-826c-bf5d050a3b19.png)

**Comment by MuJinYan** [comment]
> close via [2d3bd05](https://github.com/NervJS/taro/commit/2d3bd0562600038393cdc069b7325af2bccac45e)

我使用yarn 重装了2次，此文件依然是错误的
![image](https://user-images.githubusercontent.com/16420319/62017988-5ac80680-b1eb-11e9-811d-d551e2ba592d.png)

**Comment by stcer** [comment]
我这里也是一样, 升级到1.3.10,  h5下组件以render开头的属性传入箭头函数或jsx无法正常使用
