### ISSUE TITLE
map 遍历中的 onclick 事件无法调用 event.stopPropagation

### ISSUE THREAD

**Issue by A0150315** [NervJS/taro#3998]
**问题描述**
map 遍历 Text 组件，给Text组件绑定onClick事件，并在事件中调用 
> event.stopPropagation

控制台则提示 
> e.stopPropagation is not a function

**复现步骤**
1. 新建一个数据 
> const tab=['A','B','C']；

2. 通过以下代码遍历渲染；

```js
{
  tab.map(title => (
    <Text
      onClick={event => {
        event.stopPropagation();
      }}
    >
      {title}
    </Text>
  ));
}
```

3. 此时渲染正常；
4. 点击Text组件；
5. 控制台报错：
> e.stopPropagation is not a function

**期望行为**
1. 输出的是 
> event.stopPropagation is not a function
2. 不应该报错，且运行正常

**报错信息**
![image](https://user-images.githubusercontent.com/18693417/62019334-0758b700-b1f1-11e9-8e0f-f37ffabc79e6.png)

**系统信息**
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/5b0252773c4f66f1fca8247d25700caa15c59aad
