### ISSUE TITLE
H5，存在事件 onTouchMove 的 View 包裹 ScrollView，其中的 onTouchMove 无法被触发

### ISSUE THREAD

**Issue by A0150315** [NervJS/taro#4000]
**问题描述**
H5，存在事件 onTouchMove 的 View 包裹 ScrollView，其中的 View 的 onTouchMove 无法被触发。

**复现步骤**
1.  伪代码如下，其中的onTouchMove无法触发
```js
<View
  onTouchMove={
    // not work
    event => console.log(1)
  }
>
  <ScrollView>{/* sth. */}</ScrollView>
</View>
```
2. 但当我在ScrollView中添加onTouchMove事件，问题解决了，代码如下：
```js
<View
  onTouchMove={
    // work
    event => console.log(1)
  }
>
  <ScrollView onTouchMove={() => {}}>{/* sth. */}</ScrollView>
</View>;
```

**期望行为**
外层View的onTouchMove正常触发

**系统信息**
  Taro CLI 1.2.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**类似issue**
#3428 
#2770

**Comment by shenghanqin** [comment]
1.3.1 版本修复。可以升级到最新版
