### ISSUE TITLE
watch 模式下 scss 编译有问题。

### ISSUE THREAD

**Issue by hqman** [NervJS/taro#4004]
## 问题
进入watch 模式，修改scss 文件会单独编译，而不会汇总到 app.wxss。

## app.scss文件如下
```css
// app.scss
@import "variable_overrides";
@import "~taro-ui/dist/style/index.scss";
@import "utilities";
@import "icon";
@import "pages/profile";
```
 ## 终端log

当修改 pages/_profile.scss后，终端显示:
>>监听文件修改中...
>>修改  样式文件  src/assets/styles/pages/_profile.wxss
>>生成  样式文件  dist/assets/styles/pages/_profile.wxss

 - 操作系统: [mac]
 - Taro 版本 [ v.1.3.10]
 - 报错平台 [  weapp]

**Comment by hqman** [comment]
@luckyadam  大佬 我更新到 1.3.14 还是出现这个问题

```
监听文件修改中...

修改  样式文件  src/assets/styles/_variables.wxss
生成  样式文件  dist/assets/styles/_variables.wxss
修改  样式文件  src/assets/styles/_variables.wxss
生成  样式文件  dist/assets/styles/_variables.wxss
```

**Comment by Chen-jj** [comment]
升级到 Taro 2 或 3 应该没问题了。
