### ISSUE TITLE
ts+observer+函数组件 组件props无法正常检查

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro#4008]
**问题描述**

使用 Vscode 编辑器开发，发现使用observer包裹函数组件后，使用组件时，参数类型写错了都没有提示。

尝试修复：
修改 @tarojs/mobx 的types
```
- export function observer(component);
+ export function observer<P extends object>(component: Taro.FunctionComponent<P>): Taro.FunctionComponent<P>;
```
这样修改后，组件的提示正常了，但是 class组件 + @observer 就异常了

**复现步骤**
[复现问题的步骤]

**期望行为**

不知下一步如何写这个类型了，是不是应该像 mobx-react-lite 独立一个 observer 给函数组件使用呢？

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.7.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.10 => 1.3.10 
      @tarojs/components: 1.3.10 => 1.3.10 
      @tarojs/mobx: 1.3.10 => 1.3.10 
      @tarojs/mobx-h5: 1.3.10 => 1.3.10 
      @tarojs/mobx-rn: 1.3.10 => 1.3.10 
      @tarojs/plugin-babel: 1.3.10 => 1.3.10 
      @tarojs/plugin-csso: 1.3.10 => 1.3.10 
      @tarojs/plugin-sass: 1.3.10 => 1.3.10 
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10 
      @tarojs/rn-runner: 1.3.10 => 1.3.10 
      @tarojs/router: 1.3.10 => 1.3.10 
      @tarojs/taro: 1.3.10 => 1.3.10 
      @tarojs/taro-alipay: 1.3.10 => 1.3.10 
      @tarojs/taro-h5: 1.3.10 => 1.3.10 
      @tarojs/taro-swan: 1.3.10 => 1.3.10 
      @tarojs/taro-tt: 1.3.10 => 1.3.10 
      @tarojs/taro-weapp: 1.3.10 => 1.3.10 
      @tarojs/webpack-runner: 1.3.10 => 1.3.10 
      eslint-config-taro: 1.3.10 => 1.3.10 
      eslint-plugin-taro: 1.3.10 => 1.3.10 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by charmtiger** [comment]
第二次仿照 mobx-react的写法尝试了一下，达到了预期效果
```
- export function observer(component);
+
+ export type IReactComponent<P = any> =
+   | React.StatelessComponent<P>
+   | Taro.ComponentClass<P>
+   | React.ClassicComponentClass<P>
+   | Taro.FunctionComponent<P>
+
+ export function observer<P extends IReactComponent>(component: P): P;
```

有点问题就是可以看到 React 相关，但是不写vscode 反而会报错。

**Comment by Chen-jj** [comment]
@charmtiger 这样可以吧？

```ts
export type ITaroComponent<P = any> =
   | Taro.ComponentClass<P>
   | Taro.FunctionComponent<P>

export function observer<P extends ITaroComponent>(component: P): P
```

**Comment by charmtiger** [comment]
@Chen-jj  不行的，组件Prop类型检查不起作用，并且报错，信息如下
![image](https://user-images.githubusercontent.com/8412626/62460742-6a2fec80-b7b5-11e9-8173-0be22b86a614.png)

**Comment by Chen-jj** [comment]
@charmtiger 我这边 ok 喔

函数式组件 Add：

![image](https://user-images.githubusercontent.com/11807297/63208895-d4795300-c10c-11e9-9822-1e7923b4d803.png)

类组件 Card：

![image](https://user-images.githubusercontent.com/11807297/63208904-e955e680-c10c-11e9-87d2-f459d98a14a7.png)

两个组件都能得到类型提示：

![image](https://user-images.githubusercontent.com/11807297/63208912-02f72e00-c10d-11e9-9575-085340ae7ece.png)

![image](https://user-images.githubusercontent.com/11807297/63208919-1609fe00-c10d-11e9-9446-0f5d1427893b.png)

修改后的 d.ts：

![image](https://user-images.githubusercontent.com/11807297/63208932-35089000-c10d-11e9-90ba-396fc510fb0f.png)

**Comment by charmtiger** [comment]
@Chen-jj 好的，我这边试一下，如果再不行的话，我做个demo发给您
