### ISSUE TITLE
Taro v1.3.10 百度小程序如何不使用双向数据绑定

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#4012]
**问题描述**
Taro v1.3.10 百度小程序如何不使用双向数据绑定 

**复现步骤**

```jsx
  return (
    <View className='playing-progress'>
      <Slider
        onChange={changeSeek}
        className='playing-progress__bar'
        min={0}
        max={duration || (list[index] && list[index].totaltime) || null}
        value={currentTime}
        backgroundColor='#f4f4f8'
        blockSize={16}
        blockColor='#fedc42'
        selectedColor='#fedc42'
        activeColor='#fedc42'
      />
      <View className='playing-progress__time'>
        <View className='playing-progress__time__current'>{currentTimeDate}</View>
        <View className='playing-progress__time__total'>{durationDate}</View>
      </View>
    </View>
  )
```

被解析成了，注意`value="{= currentTime =}"`这个属性
```jsx
<block s-if="{{$taroCompReady}}">
    <view class="playing-progress">
        <slider bindchange="anonymousFunc0" class="playing-progress__bar" min="{{0}}" max="{{duration || list[index] && list[index].totaltime || null}}" value="{= currentTime =}" background-color="#f4f4f8" block-size="{{16}}" block-color="#fedc42" selected-color="#fedc42" active-color="#fedc42"></slider>
        <view class="playing-progress__time">
            <view class="playing-progress__time__current">{{currentTimeDate}}</view>
            <view class="playing-progress__time__total">{{durationDate}}</view>
        </view>
    </view>
</block>

```

**系统信息**
Taro CLI 1.3.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.10 => 1.3.10 
      @tarojs/components: 1.3.10 => 1.3.10 
      @tarojs/components-qa: 1.3.10 => 1.3.10 
      @tarojs/mobx: 1.3.10 => 1.3.10 
      @tarojs/mobx-h5: 1.3.10 => 1.3.10 
      @tarojs/mobx-rn: 1.3.10 => 1.3.10 
      @tarojs/plugin-babel: 1.3.10 => 1.3.10 
      @tarojs/plugin-csso: 1.3.10 => 1.3.10 
      @tarojs/plugin-less: 1.3.10 => 1.3.10 
      @tarojs/plugin-sass: 1.3.10 => 1.3.10 
      @tarojs/plugin-uglifyjs: 1.3.10 => 1.3.10 
      @tarojs/redux: 1.3.10 => 1.3.10 
      @tarojs/redux-h5: 1.3.10 => 1.3.10 
      @tarojs/rn-runner: 1.3.10 => 1.3.10 
      @tarojs/router: 1.3.10 => 1.3.10 
      @tarojs/taro: 1.3.10 => 1.3.10 
      @tarojs/taro-alipay: 1.3.10 => 1.3.10 
      @tarojs/taro-h5: 1.3.10 => 1.3.10 
      @tarojs/taro-qq: 1.3.10 => 1.3.10 
      @tarojs/taro-quickapp: 1.3.10 => 1.3.10 
      @tarojs/taro-swan: 1.3.10 => 1.3.10 
      @tarojs/taro-tt: 1.3.10 => 1.3.10 
      @tarojs/taro-weapp: 1.3.10 => 1.3.10 
      @tarojs/webpack-runner: 1.3.10 => 1.3.10 
      eslint-config-taro: 1.3.10 => 1.3.10 
      eslint-plugin-taro: 1.3.10 => 1.3.10 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
      stylelint-config-taro-rn: 1.3.10 => 1.3.10 
      stylelint-taro-rn: 1.3.10 => 1.3.10

**Comment by loveonelong** [comment]
这里不需要双向数据绑定啊

**Comment by yuche** [comment]
有没有百度小程序相关文档

**Comment by loveonelong** [comment]
我是说不希望taro解析为双向数据绑定，会出现一些比较奇怪的问题

**Comment by yuche** [comment]
我是说关于百度小程序关于双向绑定的文档发一下

**Comment by loveonelong** [comment]
https://smartprogram.baidu.com/docs/develop/framework/view_data/

**Comment by Chen-jj** [comment]
@loveonelong 复现不了，提供完整可复现代码。

**Comment by yuche** [comment]
是否使用双向绑定是由这个数据结构控制的：

```jsx
const swanSpecialAttrs = {
  'ScrollView': ['scrollTop', 'scrollLeft', 'scrollIntoView'],
  'Input': ['value'],
  'Textarea': ['value'],
  'MovableView': ['x', 'y'],
  'Slider': ['value']
}
```

它是由百度小程序官方的人建议添加的。
