### ISSUE TITLE
[头条小程序] className传入数组，最终渲染的结果跟其他端不一致

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#4018]
**问题描述**
例如代码：
```
<View
        className={[
          'diy-basic-window',
          `diy-basic-window__${style_id}`,
        ]}
        style={wrapperStyle}
      >
</View>
```

在微信小程序下是正确的：
![image](https://user-images.githubusercontent.com/13899502/62120127-96e68e80-b2f3-11e9-91e0-085f6ce42ee5.png)

在头条小程序下是不正确的：
![image](https://user-images.githubusercontent.com/13899502/62120147-a1088d00-b2f3-11e9-9616-d151014e5582.png)

可以看到，两个className用了逗号做分隔

**期望行为**
跟其他端行为保持一致

**系统信息**
```
👽 Taro v1.3.11


  Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.11 => 1.3.11 
      @tarojs/cli: 1.3.11 => 1.3.11 
      @tarojs/components: 1.3.11 => 1.3.11 
      @tarojs/components-qa: 1.3.11 => 1.3.11 
      @tarojs/components-rn: 1.3.11 => 1.3.11 
      @tarojs/plugin-babel: 1.3.11 => 1.3.11 
      @tarojs/plugin-csso: 1.3.11 => 1.3.11 
      @tarojs/plugin-sass: 1.3.11 => 1.3.11 
      @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11 
      @tarojs/redux: 1.3.11 => 1.3.11 
      @tarojs/redux-h5: 1.3.11 => 1.3.11 
      @tarojs/rn-runner: 1.3.11 => 1.3.11 
      @tarojs/router: 1.3.11 => 1.3.11 
      @tarojs/taro: 1.3.11 => 1.3.11 
      @tarojs/taro-alipay: 1.3.11 => 1.3.11 
      @tarojs/taro-h5: 1.3.11 => 1.3.11 
      @tarojs/taro-qq: 1.3.11 => 1.3.11 
      @tarojs/taro-quickapp: 1.3.11 => 1.3.11 
      @tarojs/taro-redux-rn: 1.3.11 => 1.3.11 
      @tarojs/taro-rn: 1.3.11 => 1.3.11 
      @tarojs/taro-router-rn: 1.3.11 => 1.3.11 
      @tarojs/taro-swan: 1.3.11 => 1.3.11 
      @tarojs/taro-tt: 1.3.11 => 1.3.11 
      @tarojs/taro-weapp: 1.3.11 => 1.3.11 
      @tarojs/webpack-runner: 1.3.11 => 1.3.11 
      eslint-config-taro: 1.3.11 => 1.3.11 
      eslint-plugin-taro: 1.3.11 => 1.3.11 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by shenghanqin** [comment]
> **问题描述**
> 例如代码：
> 
> ```
> <View
>         className={[
>           'diy-basic-window',
>           `diy-basic-window__${style_id}`,
>         ]}
>         style={wrapperStyle}
>       >
> </View>
> ```
> 
> 在微信小程序下是正确的：
> ![image](https://user-images.githubusercontent.com/13899502/62120127-96e68e80-b2f3-11e9-91e0-085f6ce42ee5.png)
> 
> 在头条小程序下是不正确的：
> ![image](https://user-images.githubusercontent.com/13899502/62120147-a1088d00-b2f3-11e9-9616-d151014e5582.png)
> 
> 可以看到，两个className用了逗号做分隔
> 
> **期望行为**
> 跟其他端行为保持一致
> 
> **系统信息**
> 
> ```
> 👽 Taro v1.3.11
> 
> 
>   Taro CLI 1.3.11 environment info:
>     System:
>       OS: macOS 10.14.5
>       Shell: 5.3 - /bin/zsh
>     Binaries:
>       Node: 11.9.0 - /usr/local/bin/node
>       Yarn: 1.13.0 - /usr/local/bin/yarn
>       npm: 6.9.0 - /usr/local/bin/npm
>     npmPackages:
>       @tarojs/async-await: 1.3.11 => 1.3.11 
>       @tarojs/cli: 1.3.11 => 1.3.11 
>       @tarojs/components: 1.3.11 => 1.3.11 
>       @tarojs/components-qa: 1.3.11 => 1.3.11 
>       @tarojs/components-rn: 1.3.11 => 1.3.11 
>       @tarojs/plugin-babel: 1.3.11 => 1.3.11 
>       @tarojs/plugin-csso: 1.3.11 => 1.3.11 
>       @tarojs/plugin-sass: 1.3.11 => 1.3.11 
>       @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11 
>       @tarojs/redux: 1.3.11 => 1.3.11 
>       @tarojs/redux-h5: 1.3.11 => 1.3.11 
>       @tarojs/rn-runner: 1.3.11 => 1.3.11 
>       @tarojs/router: 1.3.11 => 1.3.11 
>       @tarojs/taro: 1.3.11 => 1.3.11 
>       @tarojs/taro-alipay: 1.3.11 => 1.3.11 
>       @tarojs/taro-h5: 1.3.11 => 1.3.11 
>       @tarojs/taro-qq: 1.3.11 => 1.3.11 
>       @tarojs/taro-quickapp: 1.3.11 => 1.3.11 
>       @tarojs/taro-redux-rn: 1.3.11 => 1.3.11 
>       @tarojs/taro-rn: 1.3.11 => 1.3.11 
>       @tarojs/taro-router-rn: 1.3.11 => 1.3.11 
>       @tarojs/taro-swan: 1.3.11 => 1.3.11 
>       @tarojs/taro-tt: 1.3.11 => 1.3.11 
>       @tarojs/taro-weapp: 1.3.11 => 1.3.11 
>       @tarojs/webpack-runner: 1.3.11 => 1.3.11 
>       eslint-config-taro: 1.3.11 => 1.3.11 
>       eslint-plugin-taro: 1.3.11 => 1.3.11 
>       nerv-devtools: ^1.4.3 => 1.4.3 
>       nervjs: ^1.4.3 => 1.4.3 
>       react: 16.3.1 => 16.3.1 
>       react-native: 0.55.4 => 0.55.4 
>     npmGlobalPackages:
>       typescript: 2.4.2
> ```

我们这样用的classNames来完成的，可以参考https://www.npmjs.com/package/classnames

**Comment by yuche** [comment]
楼上说得对，你可以用 classNames。Taro 和 React 一样，不支持 class 原生传入数组。
