### ISSUE TITLE
1.3.11版本微信小程序button组件事件绑定异常

### ISSUE THREAD

**Issue by EickeOe** [NervJS/taro#4022]
**问题描述**
微信小程序，一个页面存在两个按钮，两个按钮的css定位都设置为`position: inherit;`，绑定不同的click事件，则两个按钮click时触发的事件都为最后一个按钮绑定的事件

```js
<View className="first">
          <Button className="text" onClick={() => console.log(1)}>
            1
          </Button>
        </View>
        <View className="last">
          <Button className="text" onClick={() => console.log(2)}>
            2
          </Button>
</View>
```
```css
.text{
  position: inherit;
}
```

**期望行为**
按钮click事件正常调用

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.11]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**Comment by yuche** [comment]
单单这段代码还是没法复现，你可以把整个组件的代码一起贴出来

**Comment by EickeOe** [comment]
@yuche 按钮的样式设置为`position: inherit;`，就出现了问题

**Comment by yuche** [comment]
你有没有其他小程序（例如百度/字节跳动）可以试一下

**Comment by Chen-jj** [comment]
@EickeOe 自己看看 Button 组件的默认样式，就能知道为什么了。

![image](https://user-images.githubusercontent.com/11807297/62191717-a70b7600-b3a6-11e9-9cc9-c80f69836f88.png)

**Comment by Chen-jj** [comment]
答案：Button 的 after 伪类是 position absolute 的，你把 Button 改静态定位了，第二个按钮边框就覆盖整个页面，你按哪里都触发按钮二的 onClick，就这么简单一个样式问题。

**Comment by EickeOe** [comment]
@Chen-jj 解决了，谢谢大佬
