### ISSUE TITLE
H5下编译报错: Cannot read property 'referencePaths' of undefined

### ISSUE THREAD

**Issue by MatthewWu5** [NervJS/taro#4024]
**问题描述**
给Taro页面组件提供自定义基类时(基类继承Taro.component) 编译H5报错

**复现步骤**
代码如下
```js
// page
export class TagSearch extends Connected<Props, State> {
// base class
export class Connected<Props = {}, State = {}> extends TaroComponent<
  Props & Store,
  State
> {
  constructor(props?: any) {
    super(props)
  }
}
```
编译h5报错 但编译weapp时没有问题
Cannot read property 'referencePaths' of undefined
    at Array.forEach (<anonymous>)

重现repo https://github.com/p-lay/play-mp/tree/issue/h5
yarn h5即可重现

**期望行为**
编译通过

**报错信息**
./.temp/util/component.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users//Documents/Code/justPlay/play-mp/.temp/util/component.js: Cannot read property 'referencePaths' of undefined
    at Array.forEach (<anonymous>)

**系统信息**
 - 操作系统: mac
 - Taro 版本 1.3.5
 - CLI 1.3.11
 - Node.js 版本 v10.9.0
 - 报错平台  h5

**补充信息**
当尝试将Connect重命名为Component时 编译变为warning
./.temp/components/tagSearch/index.js 159:2-11
" '../../util/component' does not contain an export named 'Component'.

但打开页面时找不到对应的基类
chrome devtool debug发现superClass为undefined

![image](https://user-images.githubusercontent.com/16813684/62190882-f9e42e00-b3a4-11e9-86f3-c46aef818589.png)

**Comment by Littly** [comment]
确实有点小问题 下个版本修复。暂时而言，可以把`@tarojs/taro-h5`的重命名去掉来规避这个问题。　
![image](https://user-images.githubusercontent.com/5780093/62442962-15c44700-b78c-11e9-999e-a83d0ec70042.png)

**Comment by MatthewWu5** [comment]
多谢多谢~
