### ISSUE TITLE
Taro v1.3.10 hooks中没有用在jsx中的state能否不挂在Page的data上

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#4026]
**问题描述**

RT.

这样对性能好一点吧.

**Comment by yuche** [comment]
你可以做一个没用到又挂上去的复现，原理上来说只有你用在了 JSX 上渲染的数据才会挂上去

**Comment by shenghanqin** [comment]
> 你可以做一个没用到又挂上去的复现，原理上来说只有你用在了 JSX 上渲染的数据才会挂上去

也就是说，与小程序wxml通信的data是会放在initData里面？
