### ISSUE TITLE
能否支持一下Socket.IO

### ISSUE THREAD

**Issue by 502647092** [NervJS/taro#4027]
Source: https://github.com/socketio/socket.io-client
由于之前很多项目都是直接用了Socket.IO处理WebSocket的通信
项目组看下 能不能兼容一下

**Comment by yuche** [comment]
https://github.com/10cella/weapp.socket.io

**Comment by 502647092** [comment]
@yuche 麻烦问下 这个是只能兼容微信还是可以兼容Taro的所有Ws

**Comment by 502647092** [comment]
@yuche 
![image](https://user-images.githubusercontent.com/10203793/62204187-43417700-b3bf-11e9-98ea-3bee43490010.png)
打包的时候遇到这个错误 请问是什么问题
会影响使用嘛

**Comment by 502647092** [comment]
经过测试 可以使用

**Comment by giantss** [comment]
@502647092 请问一下你现在使用的是 socket.io 是哪一个

**Comment by yuebanyin** [comment]
> 经过测试 可以使用

我的taro安装这个包之后小程序编译连不上，您知道是什么原因吗

**Comment by yuebanyin** [comment]
> https://github.com/10cella/weapp.socket.io

您好 我遇到taro用这个包 socket 还是连不上的问题，小程序编译 eio = 4 ，但是客户端eio=3

**Comment by yuebanyin** [comment]
![image](https://github.com/NervJS/taro/assets/65444216/e0b09627-bca4-42e1-881e-a6b807a9f647)
