### ISSUE TITLE
【求助】集成Sentry不能正常工作

### ISSUE THREAD

**Issue by clarktang** [NervJS/taro#403]
**问题描述**
使用Sentry作为程序异常追踪系统，集成raven-js，但是不能上报错误，而react项目能够正常的上报错误。

```js
// app.js
from Raven import 'raven-js'

/* ..................... 省略 ............  */
compoenentDidMount () {
  Raven.config(url).install()
  // 最简单的例子就是
  Raven.captureMessage('broken!')
}

```

create-react-app中在app.js中同样位置，同样代码，得到结果如下：

![1111111111111](https://user-images.githubusercontent.com/37982974/43390468-e168669c-9420-11e8-8be3-7d7aff76eed6.png)

**期望行为**
Sentry服务器应该要收到『borken』语句。

**报错信息**
无，正常编译

**系统信息**

 - 操作系统: macos
 - Taro 版本 0.0.71 & 1.0.0-beta.1
 - Node.js 版本  10.6.0

初步怀疑是微信小程序环境不支持fetch造成的

**Comment by Pines-Cheng** [comment]
![image](https://segmentfault.com/img/bVI7cG?w=536&h=209)

**Comment by luckyadam** [comment]
小程序中应该不能用 fetch api 来发送请求
