### ISSUE TITLE
Taro的`taro/types/index.d.ts`文件实在是太大了，建议优化

### ISSUE THREAD

**Issue by loveonelong** [NervJS/taro#4030]
**问题描述**

`taro/types/index.d.ts`有1.2w行，所有的定义都放在一起杂乱无章。

建议将不同的类型定义拆分到单独的d.ts文件里。

比如Taro组件相关api(ex: Taro.component)和各个平台api(ex: swan.setPageInfo)都单独放到一个文件里，方便维护。

**Comment by luckyadam** [comment]
有道理，需要拆分一下

**Comment by Garfield550** [comment]
优化了，更新到最新版就可以了。
