### ISSUE TITLE
如何手动清空this.$router.param?

### ISSUE THREAD

**Issue by songming43** [NervJS/taro#4032]
**问题描述**
使用`this.$router.params`来获取小程序码中携带的参数，但是发现在'ios设备中', `this.$router.params`中的参数在生命周期中一直存在，页面跳出后，该参数一直存在。安卓设备中没有这个问题, 安卓设备中`this.$router.params`中的参数只在第一次扫小程序码的时候有，页面跳出再次进入后便没有改参数。请问：如何手动清空`this.$router.params`?

**复现步骤**
```js
componentDidMount(){
   var { store_id, q, scene } = this.$router.params;
   if (store_id){
       await Store.setCurrentStore(store_id);
   }  
}
第一次通过扫描小程序码进入该页面后，会从`this.$router.params`中解析出store_id;
但是，在ios设备中，再次进入该页面后，this.$router.params.store_id依然存在，请问如何手动清除this.$router.params.store_id ？我希望再次进入页面(不通过小程序码)后，this.$router.params.store_id不要再存在了
 ```

**期望行为**
我希望再次进入页面(不通过小程序码)后，this.$router.params.store_id不要再存在了

**报错信息**

**系统信息**
 - 操作系统: [e.g. MacOS]
 - Taro 版本 [e.g. v.1.2.21]
 - Node.js 版本 [e.g. v11.4.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@songming43 "页面跳出再次进入后" 是什么意思，页面A跳页面B，页面B点返回还是再打开新页面A。页面是普通页面还是 Tab 页面，都说详细点。

**Comment by songming43** [comment]
> @songming43 "页面跳出再次进入后" 是什么意思，页面A跳页面B，页面B点返回还是再打开新页面A。页面是普通页面还是 Tab 页面，都说详细点。

扫码进入A页面(Tab页面)，然后A页面切换到B页面(Tab页面)，再次从B页面切换到A页面,this.$router.params中的参数依然在

**Comment by Chen-jj** [comment]
@songming43 那肯定啊，B 回 A，A 页面对象都没有销毁，一直存在

**Comment by songming43** [comment]
> @songming43 那肯定啊，B 回 A，A 页面对象都没有销毁，一直存在

@Chen-jj 怎么清空这个this.$router.params呢？我现在希望，仅在扫小程序码进入A页面的时候this.$router.params中的值存在，从A页面切换到B，再从B切换到A的时候this.$router.params被清空

**Comment by Chen-jj** [comment]
@songming43 你 didmount 挂 this 上，之后想怎么做都可以。

**Comment by songming43** [comment]
> @songming43 你 didmount 挂 this 上，之后想怎么做都可以。

@Chen-jj 怎么挂呢？
```
    this.componentDidMount = componentDidMount(){
          this.$router.params = {};
    }
```
这样吗？

**Comment by Chen-jj** [comment]
@songming43 

```js
componentDidMount () {
  this.parmas = this.$router.params
}

componentDidShow () {
  this.params = {}
}
```
