### ISSUE TITLE
taro怎么局部刷新啊，我这两个写法不管用

### ISSUE THREAD

**Issue by WuMengYu** [NervJS/taro#4038]
① this.setState({    [`sku_list[${current_pro_stock}]`]: value   })
var  mText = 'sku_list['+ current_pro_stock +']';
console.log('mText', mText);
② this.setState({
    [mText]: value,
 })

**Comment by WuMengYu** [comment]
111

**Comment by luckyadam** [comment]
Taro 自己已经做了优化了
https://nervjs.github.io/taro/docs/optimized-practice.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%95%B0%E6%8D%AE-diff
