### ISSUE TITLE
如何配置编译出es6，而不是es5

### ISSUE THREAD

**Issue by luckalphie** [NervJS/taro#4041]
因为编译小程序代码，需要调试，es5的代码太难看，而且本身小程序也支持es6

**Comment by luckyadam** [comment]
暂时还支持不了~ 关于调试的话，目前 es5 的代码勉强能看吧 😂

**Comment by luckalphie** [comment]
请问
1、有没有考虑支持？
2、现在不支持的话，能不能给小程序编译输出sourceMap

**Comment by Garfield550** [comment]
我相信以后都会支持的

**Comment by loveonelong** [comment]
+1

**Comment by xPixv** [comment]
ES6 顺便还能让体积更小点儿 233

**Comment by fanyinghao** [comment]
询问下进度

**Comment by Chen-jj** [comment]
Taro3 能支持 source-map，也能自己调整 babel 配置 preset-env 的 target 控制编译产物
