### ISSUE TITLE
[Feature request]按照端不同的设置不同的配置

### ISSUE THREAD

**Issue by broven** [NervJS/taro#4043]
我们利用Taro开发了微信、字节小程序 （未来还有百度快应用），但是针对每个端都有不同的app配置(app -> config), 比如`config.pages` `config.tabBar`等, 不知道这种的需求Taro上的最佳实践是怎么样的。

**Comment by BinZhiZhu** [comment]
可以使用暴力方法 编译的时候异步修改文件

**Comment by broven** [comment]
@BinZhiZhu 是可以, 但是这样每次人工修改感觉成本是在的, 而且容易出错

**Comment by broven** [comment]
如果目前不支持这种能力的话, 我觉得可以扩展下config这里
```
config = {
common: {}
weapp: {}
tt: {}
}
```
类似这样, 最后merge起来的方式

**Comment by BinZhiZhu** [comment]
官方不支持 暂时也只能这么做



------------------ 原始邮件 ------------------
发件人: "metaJS"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午5:26
收件人: "NervJS/taro"<taro@noreply.github.com>; 
抄送: "Nikita"<854767470@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [NervJS/taro] [Feature request]按照端不同的设置不同的配置 (#4043)




@BinZhiZhu 是可以, 但是这样每次人工修改感觉成本是在的, 而且容易出错

**Comment by broven** [comment]
@BinZhiZhu 嗯, 那我想想怎么做合理, 提个PR扩展下吧。

**Comment by luckyadam** [comment]
在最新版本支持这个写法了
https://github.com/NervJS/taro/pull/3867
