### ISSUE TITLE
feathub 域名证书过期了

### ISSUE THREAD

**Issue by binggg** [NervJS/taro#4046]
**问题描述**

**复现步骤**
[复现问题的步骤]
1. Go to 'https://feathub.com/NervJS/taro'

![image](https://user-images.githubusercontent.com/7686861/62305118-e377c880-b4b1-11e9-80d2-12ca7fb76631.png)

```

**期望行为**

证书续期

**报错信息**

**系统信息**

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

证书没有自动续期

**Comment by shenghanqin** [comment]
feathub是第三方的，不是taojs官方运营的。
