### ISSUE TITLE
h5的swiper组件绑定了current，当current为0时swiper不切换，其他值可以正常切换

### ISSUE THREAD

**Issue by ghyzx** [NervJS/taro#4052]
该问题有在其他 issue 讨论到（地址：https://github.com/NervJS/taro/issues/3739 ），
但问题未彻底解决就被关闭了，这里再提一次吧。

------------------------
**问题描述**
h5的swiper组件绑定了current，当current为0时swiper不切换，其他值可以正常切换
1.3.9、1.3.11 等新版本均存在这个问题；
1.2.26 等老一些的版本是正常的；

**期望行为**
新版本 修复current为0时swiper的切换问题。

**系统信息**
Taro v1.3.11

  Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.11 => 1.3.11 
      @tarojs/plugin-babel: 1.3.11 => 1.3.11 
      @tarojs/plugin-csso: 1.3.11 => 1.3.11 
      @tarojs/plugin-sass: 1.3.11 => 1.3.11 
      @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11 
      @tarojs/router: 1.3.11 => 1.3.11 
      @tarojs/taro: 1.3.11 => 1.3.11 
      @tarojs/taro-alipay: 1.3.11 => 1.3.11 
      @tarojs/taro-h5: 1.3.11 => 1.3.11 
      @tarojs/taro-swan: 1.3.11 => 1.3.11 
      @tarojs/taro-tt: 1.3.11 => 1.3.11 
      @tarojs/taro-weapp: 1.3.11 => 1.3.11 
      @tarojs/webpack-runner: 1.3.11 => 1.3.11 
      eslint-config-taro: 1.3.11 => 1.3.11 
      eslint-plugin-taro: 1.3.11 => 1.3.11 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3

**Comment by ghyzx** [comment]
Taro v1.3.12 仍然存在这个问题  @jinjinjin0731 @Pines-Cheng

**Comment by ghyzx** [comment]
请问：有什么新进展吗？或者，有什么计划吗？
一直不敢升级到最新版本（停留在1.2.26）。

**Comment by gdpu-wxq** [comment]
1.3.18了，这个问题还没修复吗

**Comment by udbbbn** [comment]
1.3.37 这个问题还是存在

**Comment by ZakaryCode** [comment]
fixed in #b4bb27cc5fc5bda53a0ba53379e9e6078eef942f
