### ISSUE TITLE
百度、支付宝小程序 有自定义组件的页面抖动明显

### ISSUE THREAD

**Issue by hjc22** [NervJS/taro#4053]
`
<View class='my-page'>
         <cus-component    name={data.data}></cus-component> 
  <View>{data.name}</View>
</View>
`
类型这样的结构下 ，data数据一起过来，` <View>{data.name}</View>`会先渲染出来，`<cus-component    name={data.data}></cus-component>` 会后渲染出来 ，就造成页面很明显的抖动了一下，因为自定义组件从中间冒出来，造成结构抖动，百度、百度web化，支付宝，都有这个问题，微信没有这个问题。原生的百度、支付宝没有这样的问题

**Comment by Chen-jj** [comment]
@hjc22 请按 issue 模板格式修改你的问题。
