### ISSUE TITLE
自定义组件的observer  初始的时候没有调用，微信的observer初始会调用执行一次

### ISSUE THREAD

**Issue by hjc22** [NervJS/taro#4054]
自定义组件的observer  初始的时候没有调用，微信的observer初始会调用执行一次

**Comment by shenghanqin** [comment]
可以看看这个文档。
https://taro-docs.jd.com/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
