### ISSUE TITLE
微信小程序配置alias无效

### ISSUE THREAD

**Issue by guxingke201** [NervJS/taro#4056]
**问题描述**

微信小程序配置alias无效，配置的alias是依赖的依赖，没有直接在src里使用

**复现步骤**
[复现问题的步骤]
1. 配置alias
1. h5下生效了
1. 微信小程序无效

**期望行为**
微信小程序的构建对alias配置效果能够和webpack一样

**报错信息**

替换失败

**系统信息**
```
👽 Taro v1.3.11


  Taro CLI 1.3.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 9.9.0 - H:\node\nodejs\node.EXE
      npm: 5.6.0 - H:\node\nodejs\npm.CMD

```

**补充信息**
查阅源码发现recursiveRequire并没有使用alias来替换

**Comment by BinZhiZhu** [comment]
可以的啊 你最好贴下你的代码~

**Comment by guxingke201** [comment]
`alias: {
    './adapters/http':'axios-miniprogram-adapter'
  },`

**Comment by guxingke201** [comment]
axios依赖里有个‘./adapters/http’会导致构建失败，想通过别名替换解决这个问题

**Comment by guxingke201** [comment]
源码发现recursiveRequire并没有使用alias来替换如何解释？

**Comment by BinZhiZhu** [comment]
你仔细过下alias doc   应该是这样才对  

https://nervjs.github.io/taro/docs/config-detail.html#alias

**Comment by guxingke201** [comment]
请提供一下代码，怎么配置`alias: { './adapters/http':'axios-miniprogram-adapter' },`才有效

**Comment by guxingke201** [comment]
源码发现recursiveRequire并没有使用alias来替换如何解释？请回答一下

**Comment by guxingke201** [comment]
合并pr后，配置
`'./adapters/http': path.resolve(__dirname, '..', 'node_modules/axios-miniprogram-adapter/dist')`

**Comment by Chen-jj** [comment]
Taro2、3 使用 webpack 构建，应该没有问题了
