### ISSUE TITLE
支付宝小程序，Android真机Iconfont 不显示

### ISSUE THREAD

**Issue by tielan** [NervJS/taro#4057]
**问题描述**
在app.scss 中引入 @import "./iconfont"; 
并在 text 中使用 iconfont 微信及支付宝小程序 用模拟器都显示正常，但是使用Android真机 支付宝小程序 无法显示 iconfont ，iOS 真机正常，微信小程序 两端正常

**复现步骤**
[复现问题的步骤]
1. app.scss 中引入 @import "./iconfont"; 
2.  text 中使用 iconfont
3. 构建支付宝小程序使用 Android真机调试

**期望行为**
Android真机 支付宝小程序 正常显示 iconfont 

**系统信息**
👽 Taro v1.3.10
  Taro CLI 1.3.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.1.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.7.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 3.10.10 - D:\Program Files\nodejs\npm.CMD

**Comment by hzcxiha** [comment]
老哥这个问题解决了吗，我也遇到了

**Comment by tielan** [comment]
这个是支付宝小程序的bug 你把所有字体都拷贝进去就可以了
