### ISSUE TITLE
Taro.uploadFile接口封装存在不一致

### ISSUE THREAD

**Issue by clarktang** [NervJS/taro#406]
**问题描述**
正常情况下，前后端采用`application/json`作为content-type，后端返回的也是json, 但是`Taro.uploadFile`会把json对象自动转化为字符串。

<img width="518" alt="wx20180731-183122 2x" src="https://user-images.githubusercontent.com/37982974/43454531-f914257c-94ef-11e8-8eba-d752f0a9e4c7.png">

图中`res`封装了后端换回的json数据，只是把这个数据自动转化成为字符串了。其他的接口Taro.request不存在该问题

**期望行为**
不要自动将后端的json转化为字符串，promise应该和Taro.request保持一致。

**系统信息**

 - 操作系统: macos
 - Taro 版本 1.0.0beta.1
 - Node.js 版本 10.6.0

**Comment by Chen-jj** [comment]
请问是小程序环境还是 h5 环境呢

**Comment by clarktang** [comment]
小程序环境

**Comment by Chen-jj** [comment]
小程序下，API 的 promise 化只是把微信返回的值 resolve 出来而已，不会操作微信 API 的返回值。所以你可以试试把 Taro.uploadFile 改成 wx.uploadFile，在 success 回调中拿到的值应该和调用 Taro.uploadFile 的 then 中接收到的值一致。

**Comment by clarktang** [comment]
确认是wx.uploadFile自身的问题
