### ISSUE TITLE
Hook 怎么接受 navigateTo({url:'/pages/index/index?id=1'})

### ISSUE THREAD

**Issue by eruca** [NervJS/taro#4064]
ClassComponent 可以使用this.$router.param, 可是在FunctionComponent需要怎么做呢？

**Comment by luckyadam** [comment]
在函数式组件中暂时可以用 `this.$router.params` 来解决

**Comment by coolhwm** [comment]
> 在函数式组件中暂时可以用 `this.$router.params` 来解决

貌似不行呀， Cannot read property '$router' of undefined

**Comment by coolhwm** [comment]
哦了，不能用箭头函数定义方法，用function定义就可以了
