### ISSUE TITLE
浏览器执行回退操作后PreviewImage不消失

### ISSUE THREAD

**Issue by dcalsky** [NervJS/taro#4069]
**问题描述**
在H5 platform上，调用Taro.previewImage后，如果执行回退(go back)操作，包含图片的遮罩层依然不会消失，而页面被回退了。正常的来说，执行go back的时候，只是关闭遮罩层而已，页面不会回退。

**复现步骤**
[复现问题的步骤]
1. 使用Taro.previewImage API
2. 点开一张图片
3. 在浏览器中执行回退操作
4. 发现遮罩层不会消失

```
    Taro.previewImage({
      urls: [imageUrl],
      current: imageUrl
    });
```

**期望行为**
包含图片的遮罩层被关闭，而页面不会被回退。

**报错信息**
行为错误，无报错。

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOS]
 - Taro 版本 [e.g. v.1.3.11]
 - Node.js 版本 [e.g. v12.4.0]
 - 报错平台 [h5]

**补充信息**
无

**Comment by shenghanqin** [comment]
感觉是不是在didHide或者willUnmount上增加一个关闭previewImage的方法？

**Comment by dcalsky** [comment]
@yuche 这应该算这一个bug吧

**Comment by Liaozzzzzz** [comment]
和react的Portals一样的吧, 这种只能想办法在监听路由变化的时候关闭, 或者暴露出一个方法来关闭

**Comment by ZakaryCode** [comment]
页面回退关闭遮罩层，已经修复

> 页面回退阻塞的功能不会实现，阻塞回退会导致页面重复渲染，如果需要可以考虑主动监听 popstate 事件
