### ISSUE TITLE
函数式组件在支付宝小程序端所有的函数都会先执行一遍

### ISSUE THREAD

**Issue by hisanshao** [NervJS/taro#4071]
**问题描述**
打开支付宝小程序，所有页面及组件的函数式组件方法都会先执行一遍

**复现步骤**
[复现问题的步骤]
1. 打开支付宝小程序

```js

export default function PageA () {
    console.log('打开支付宝小程序所有组件会先执行一下')
}

export default function ComponentA () {
    console.log('打开支付宝小程序所有组件会先执行一下')
}

export default function PageB () {
    console.log('打开支付宝小程序所有组件会先执行一下')
}

export default function ComponentB () {
    console.log('打开支付宝小程序所有组件会先执行一下')
}

```

**期望行为**
只有打开了A页面才执行PageA的方法

**报错信息**

执行机制有问题

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v8.10.0/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.11 => 1.3.11 
      @tarojs/components: 1.3.11 => 1.3.11 
      @tarojs/plugin-babel: 1.3.11 => 1.3.11 
      @tarojs/plugin-csso: 1.3.11 => 1.3.11 
      @tarojs/plugin-less: 1.3.11 => 1.3.11 
      @tarojs/plugin-uglifyjs: 1.3.11 => 1.3.11 
      @tarojs/redux: 1.3.11 => 1.3.11 
      @tarojs/redux-h5: 1.3.11 => 1.3.11 
      @tarojs/router: 1.3.11 => 1.3.11 
      @tarojs/taro: 1.3.11 => 1.3.11 
      @tarojs/taro-alipay: 1.3.11 => 1.3.11 
      @tarojs/taro-h5: 1.3.11 => 1.3.11 
      @tarojs/taro-swan: 1.3.11 => 1.3.11 
      @tarojs/taro-tt: 1.3.11 => 1.3.11 
      @tarojs/taro-weapp: 1.3.11 => 1.3.11 
      @tarojs/webpack-runner: 1.3.11 => 1.3.11 
      eslint-config-taro: 1.3.11 => 1.3.11 
      eslint-plugin-taro: 1.3.11 => 1.3.11 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
      stylelint-config-taro-rn: 1.3.11 => 1.3.11 
      stylelint-taro-rn: 1.3.11 => 1.3.11 
 - 操作系统: [e.g. macOS 10.14.5]
 - Taro 版本 [e.g. v.1.3.11]
 - Node.js 版本 [e.g. v8.10.0]
 - 报错平台 [alipay]

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
