### ISSUE TITLE
QuickApp：1.3.12，index中开发者设置了copy sign/release后，快应用环境无法准备成功。

### ISSUE THREAD

**Issue by kongzhe607** [NervJS/taro#4079]
![image](https://user-images.githubusercontent.com/5809518/62505858-db60b580-b830-11e9-91c6-b356def62a12.png)

参见图片。：）

**Comment by luckyadam** [comment]
这个就有点蛋疼了😱

**Comment by kongzhe607** [comment]
这个是真是需求呀。

config里面我加了如下的代码，就运行不了了，你觉得呢？

  copy: {
    patterns: [
      {
        from: 'src/asset',
        to: `dist/${process.env.TARO_ENV}/src/asset`,
      },
      {
        from: 'sign/release',
        to: 'dist/quickapp/sign/release',
      },
    ],
    options: {},
  },

**Comment by kongzhe607** [comment]
copy到sign下面，然后hap build && hap release就可以直接出包了。
