### ISSUE TITLE
函数名称内有 "Page" 关键字编译出错

### ISSUE THREAD

**Issue by a709691139** [NervJS/taro#408]
**问题描述**
函数名称内有 "Page"就会编译出错,
onClick={this.toEditAddressPage.bind(this, "test")}  

![image](https://user-images.githubusercontent.com/21304258/43507596-2323ef86-95a0-11e8-943e-fb550e3f19c1.png)

**系统信息**
系统: win10 
Taro: 0.0.67

**Comment by luckyadam** [comment]
你好~ 不是因为 Page 关键字，而是因为 `toEditAddressPage ` 这个函数名比较长，长度为 17 ，如果在 JSX 中函数使用了 `.bind`，那么函数名会被加到元素属性上，小程序的属性名有长度限制，经过测试 `0.0.67` 版本这里函数名最长 15，最新的 beta 版本优化后，长度限制为 20.
