### ISSUE TITLE
开启css module后 绑定类无效

### ISSUE THREAD

**Issue by CalmHarbin** [NervJS/taro#4087]
**问题描述**
[问题描述：开启css module后类绑定应使用class,不能用className

**复现步骤**
[复现问题的步骤]

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'

import styles from './Test.module.scss'

export default class Test extends Component {
  constructor(props) {
    super(props)
    this.state = { }
  }

  render () {
    return (
     {/*这里使用class正常,使用className异常*/}
      <View class={styles.test}>
        <Text class={styles.txt}>Hello world!</Text>
      </View>
    )
  }
}

```

**期望行为**
使用className也能是正确的渲染样式

**报错信息**

无报错信息

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  Windows 10
 - Taro 版本 [e.g. v.1.3.11]
 - Node.js 版本 [e.g. v10.15.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
转换wxml的时候未将className替换为class

**Comment by yuche** [comment]
麻烦做成一个带有 package.json 的仓库，单单这个代码片段无法复现

**Comment by luckyadam** [comment]
确实没有复现，提供一个完整的 demo 吧

**Comment by CalmHarbin** [comment]
> 麻烦做成一个带有 package.json 的仓库，单单这个代码片段无法复现

已经做了一个demo
 [仓库地址](https://github.com/CalmHarbin/Taro-css-module-)

![image](https://user-images.githubusercontent.com/34387163/62925751-9961e180-bde5-11e9-8363-41d04603ae6f.png)
![image](https://user-images.githubusercontent.com/34387163/62925782-a7176700-bde5-11e9-892f-25d8d14ed92b.png)

**Comment by CalmHarbin** [comment]
👽 Taro v1.3.13


  Taro CLI 1.3.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\Win10\node\node.EXE
      npm: 6.4.1 - D:\Win10\node\npm.CMD
