### ISSUE TITLE
taro-cli下面min目录是否有计划根据端进行拆分？

### ISSUE THREAD

**Issue by zhuxianguo** [NervJS/taro#4089]
taro-cli中目前除了RN和H5外的端解析都是放到min下面了，感觉min下面的程序if越来越多了，越来越复杂了，不知道是否有计划把这个目录根据端进行拆分呢？

**Comment by luckyadam** [comment]
没有这个计划，后续的计划是小程序改成用 webpack 编译

**Comment by Garfield550** [comment]
> 没有这个计划，后续的计划是小程序改成用 webpack 编译

各端的库呢？会不会从 Rollup 换成 Webpack。
