### ISSUE TITLE
CanvasContext.drawImage()报错问题

### ISSUE THREAD

**Issue by archerQ** [NervJS/taro#4091]
使用Canvas画图，代码大致如下：
`let ctx = Taro.createCanvasContext('myCanvas', this)
    console.log('===图片信息==',images)
    let front = images.front
    console.log('==底图信息==', front)
    ctx.drawImage(front, 10, 10, 300, 400)
    ctx.draw()`

其中front是下载下来的图片，格式为：
`http://127.0.0.1:9091/f52be074-19d3-4c12-abbb-dc158975544e`

报的错误如下：
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'

有大佬知道是什么原因，怎么处理吗？求解答

**Comment by luckyadam** [comment]
在什么平台下报的错，具体错误截图看下

**Comment by archerQ** [comment]
> 
> 
> 在什么平台下报的错，具体错误截图看下

> 在H5中

> 
![图片](https://user-images.githubusercontent.com/21662463/62589886-437ccd80-b8fd-11e9-8680-f86098528835.png)

**Comment by geekgray** [comment]
楼主问题解决了吗 是怎么回事？

**Comment by meiye1988** [comment]
楼主后面解决了吗 现在我遇到和你一样情况   望楼主指教下谢谢

**Comment by Link-X** [comment]
> 楼主后面解决了吗现在我遇到和你一样情况
用h5原生canvas api。别用小程序的就行。

**Comment by Link-X** [comment]
> > 楼主后面解决了吗现在我遇到和你一样情况
> > 用h5原生canvas api。别用小程序的就行。

后面h5单独写了一套。没用Taro.createCanvasContext()。
