### ISSUE TITLE
RN 运行不起，一直stopped

### ISSUE THREAD

**Issue by Mihawk-zhao** [NervJS/taro#4093]
如下图，yarn dev:rn，都正常，浏览器加载index.js也可以。但在壳子文件夹里，react-native run-android的时候，应用就始终打不开了。
![image](https://user-images.githubusercontent.com/19793378/62588182-6ad09c00-b8f7-11e9-8e7b-2e04164e2fea.png)

**Comment by Pines-Cheng** [comment]
应用闪退，这个原因导致的：https://github.com/NervJS/taro-native-shell/issues/4
