### ISSUE TITLE
taro create component xx 无效？

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#4097]
**问题描述**
使用`taro create page index` 这个命令可以生成页面，使用`taro create component xxx` 这样，没有任何页面生成，也没输出任何错误

```
❯ taro create component wx
👽 Taro v1.3.11

```

**系统信息**
❯ taro info
👽 Taro v1.3.11

  Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.6.0 - ~/.config/nvm/12.6.0/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.config/nvm/12.6.0/bin/npm

**Comment by Chen-jj** [comment]
@nyrf 
![image](https://user-images.githubusercontent.com/11807297/62669197-58229980-b9c1-11e9-8690-157d6b5245db.png)

**Comment by nyrf** [comment]
@Chen-jj 
```
❯ taro --help
👽 Taro v1.3.11

Usage: taro <command> [options]

Options:
  -V, --version       output the version number
  -h, --help          output usage information

Commands:
  init [projectName]  Init a project with default templete
  config <cmd>        Taro config
  create [type]       Create page or component for project
  build               Build a project with options
  update              Update packages of taro
  convert             Convert weapp to taro
  info                Diagnostics Taro env info
  doctor              Diagnose taro project
  help [cmd]          display help for [cmd]
```
意思是现在不能create component? 我前面版本还用过这个命令、

**Comment by Chen-jj** [comment]
@nyrf 不能，还不支持创建组件，创建页面按 `taro create --name=<page_name>` 用。CLI 的用法提示下个版本会改正过来。

**Comment by archywillhe** [comment]
相关自己做个模版加个command是哪篇代码？

**Comment by archywillhe** [comment]
找到了 https://nervjs.github.io/taro/docs/template.html#%E6%A8%A1%E6%9D%BF%E6%BA%90
