### ISSUE TITLE
不能install，安装依赖报错

### ISSUE THREAD

**Issue by suwu150** [NervJS/taro#41]
```
/Users/suwu150/.nvm/versions/node/v8.0.0/bin/node /Users/suwu150/.nvm/versions/node/v8.0.0/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
npm ERR! Unexpected end of input at 1:7572
npm ERR! port","version":"0.4.1","dependencies":{"array.prototype.find":"^1.0.
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suwu150/.npm/_logs/2018-06-08T10_20_57_884Z-debug.log
```

**Comment by luckyadam** [comment]
这个信息有点少~ 要不换国内npm源安装试试？

**Comment by iAimer** [comment]
同不能安装， 版本：0.0.41
<img width="607" alt="qq20180608-210037 2x" src="https://user-images.githubusercontent.com/15074596/41159439-20ae58ba-6b5f-11e8-8e27-1fee875b9757.png">

**Comment by luckyadam** [comment]
@iAimer 是直接创建完项目，然后在项目目录下安装么~可以贴一下 `package.json` 么

**Comment by iAimer** [comment]
{
  "name": "WebIndex",
  "version": "1.0.0",
  "private": true,
  "description": "WindWork",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "^0.0.41",
    "@tarojs/router": "^0.0.41",
    "@tarojs/taro": "^0.0.41",
    "@tarojs/taro-h5": "^0.0.41",
    "@tarojs/taro-weapp": "^0.0.41",
    "nervjs": "^1.2.18"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "^0.0.41",
    "@tarojs/plugin-csso": "^0.0.41",
    "@tarojs/plugin-sass": "^0.0.41",
    "@tarojs/plugin-uglifyjs": "^0.0.41",
    "@tarojs/webpack-runner": "^0.0.41",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^0.1.3",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "^0.1.3"
  }
}


创建项目的时候就失败，然后我再yarn install, npm install, cnpm install 都不行...

**Comment by iAimer** [comment]
<img width="610" alt="1" src="https://user-images.githubusercontent.com/15074596/41171791-5998e922-6b84-11e8-8bdd-e129d34922da.png">

upset...

**Comment by suwu150** [comment]
我换了cnpm的源之后安装成功，在使用npm和taobao的源的时候出错
