### ISSUE TITLE
项目配置中的copy的options.ignore选项并不生效。

### ISSUE THREAD

**Issue by fishen** [NervJS/taro#4100]
**问题描述**
按照文档设置，在watch模式下，copy.options.ignore选项并不生效。

**复现步骤**
[复现问题的步骤]
1. 修改配置
2. npm run dev:weapp
3. 修改忽略的文件并保存
4. 忽略的文件依然被拷贝

```
  copy: {
    patterns: [
      
    ],
    options: {
      ignore: ["src/ext.json"]
    }
  },
```

**期望行为**
设置忽略的文件可以不进行拷贝

**报错信息**
![image](https://user-images.githubusercontent.com/17705466/62609983-4dbabe00-b935-11e9-95f2-d961a616c55c.png)

**系统信息**
Taro CLI 1.3.11 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.0.0 - /usr/bin/node
      npm: 6.10.3 - /usr/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.12 => 1.3.12
      @tarojs/components: 1.3.12 => 1.3.12
      @tarojs/plugin-babel: 1.3.12 => 1.3.12
      @tarojs/plugin-csso: 1.3.12 => 1.3.12
      @tarojs/plugin-sass: 1.3.12 => 1.3.12
      @tarojs/plugin-uglifyjs: 1.3.12 => 1.3.12
      @tarojs/router: 1.3.12 => 1.3.12
      @tarojs/taro: 1.3.12 => 1.3.12
      @tarojs/taro-alipay: 1.3.12 => 1.3.12
      @tarojs/taro-h5: 1.3.12 => 1.3.12
      @tarojs/taro-swan: 1.3.12 => 1.3.12
      @tarojs/taro-tt: 1.3.12 => 1.3.12
      @tarojs/taro-weapp: 1.3.12 => 1.3.12
      @tarojs/webpack-runner: 1.3.12 => 1.3.12
      eslint-config-taro: 1.3.12 => 1.3.12
      eslint-plugin-taro: 1.3.12 => 1.3.12
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3
      stylelint-config-taro-rn: 1.3.12 => 1.3.12
      stylelint-taro-rn: 1.3.12 => 1.3.12
    npmGlobalPackages:
      typescript: 3.4.5

**补充信息**
试过“ext.json”,"/src/ext.json"等设置都不生效。

**Comment by shenghanqin** [comment]
过来跟一个，没准以后用到。

**Comment by Chen-jj** [comment]
Taro3 已解决。
