### ISSUE TITLE
 TypeError: Cannot read property 'uglify' of undefined

### ISSUE THREAD

**Issue by huangyanyang** [NervJS/taro#4103]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
 TypeError: Cannot read property 'uglify' of undefined
**复现步骤**
[复现问题的步骤]
运行直接报错
![image](https://user-images.githubusercontent.com/19208961/62623480-87022680-b953-11e9-9928-69470e00040d.png)

```js

// 这里可以贴代码
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
运行不报错
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

taro info                                                 
 Taro v1.3.12                                             
                                                          
                                                          
Taro CLI 1.3.12 environment info:                         
  System:                                                 
    OS: Windows 10                                        
  Binaries:                                               
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD      
h5报错    
                                                          
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
这个项目是很久之前开发了，中间taro已经升级过几版了，不知道跟版本升级有没有关系

**Comment by Garfield550** [comment]
你的 taro info 为什么没有其他组件的版本信息，正常的应该是这样的

```shell
  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3
    Binaries:
      Node: 12.8.0
      Yarn: 1.17.3
      npm: 6.10.3
    npmPackages:
      @tarojs/async-await: 1.3.12 => 1.3.12 
      @tarojs/cli: 1.3.12 => 1.3.12 
      @tarojs/components: 1.3.12 => 1.3.12 
      @tarojs/mobx: 1.3.12 => 1.3.12 
      @tarojs/plugin-babel: 1.3.12 => 1.3.12 
      @tarojs/plugin-csso: 1.3.12 => 1.3.12 
      @tarojs/plugin-sass: 1.3.12 => 1.3.12 
      @tarojs/plugin-uglifyjs: 1.3.12 => 1.3.12 
      @tarojs/router: 1.3.12 => 1.3.12 
      @tarojs/taro: 1.3.12 => 1.3.12 
      @tarojs/taro-weapp: 1.3.12 => 1.3.12 
      @tarojs/webpack-runner: 1.3.12 => 1.3.12 
      eslint-config-taro: 1.3.12 => 1.3.12 
      eslint-plugin-taro: 1.3.12 => 1.3.12 
      nerv-devtools: ^1.4.3 => 1.4.3 
      nervjs: ^1.4.3 => 1.4.3 
```

**Comment by yuche** [comment]
这种情况一般是你依赖没有安装好的缘故

**Comment by suwu150** [comment]
请问该问题如何解决的
