### ISSUE TITLE
微信小程序转出，编译H5，报TaroParsebcTmpl错误

### ISSUE THREAD

**Issue by acwind** [NervJS/taro#4108]
**问题描述**
[问题描述：将一个微信小程序转成taro成功，但是准备编译成H5的时候出错]

**复现步骤**
命令：taro build --type h5
报错：Module not found: Can't resolve './TaroParsebcTmpl' in '/..path../taroConvert/.temp/imports'

 - 操作系统:Mac OS 10.14
 - Taro 版本 1.3.12
 - Node.js 版本 [10.16.0]
 - 报错平台 [h5]

**Comment by yuche** [comment]
在 h5 端不要使用 wxparse，你可以直接用 `dangerouslySetInnerHTML` API
