### ISSUE TITLE
原生语法页面调用taro语法组件不能触发声明周期

### ISSUE THREAD

**Issue by chenfaxiang** [NervJS/taro#4122]
原生语法页面调用taro语法组件不能触发声明周期，这里有一个 demo ，帮忙看一下
[fe_mp_all.zip](https://github.com/NervJS/taro/files/3484735/fe_mp_all.zip)

**Comment by chenfaxiang** [comment]
@yuche

**Comment by yuche** [comment]
哪个页面，怎么进入

**Comment by chenfaxiang** [comment]
@yuche 我在项目 `taro-sample-weapp` 也做了一个 demo，这个比较清晰，这边提了一个 [pull request](https://github.com/NervJS/taro-sample-weapp/pull/25) ，demo 的入口文件是 `src/pages/native/native.wxml`，调用的对应 `taro` 组件是 `src/components/tabTaro/tabTaro.js`

**Comment by Chen-jj** [comment]
@chenfaxiang tabTaro 组件的生命周期会被触发。

![image](https://user-images.githubusercontent.com/11807297/62923837-3c642c80-bde1-11e9-93a7-d6460f583086.png)

**Comment by chenfaxiang** [comment]
@Chen-jj 老哥，不好意思，这里是之前提的一个，描述有误，在 `taro-sample-weapp` 这个项目的 [pull request](https://github.com/NervJS/taro-sample-weapp/pull/25) 里面的测试我也发现了生命周期可以正常执行；最终的问题是这样，我们在 taro 的原生组件中调用用 taro 语法写的组件时，taro 组件语法写的组件中的传参和事件不会被执行。

**Comment by Chen-jj** [comment]
@chenfaxiang  demo

**Comment by chenfaxiang** [comment]
@Chen-jj demo 就是 `taro-sample-weapp` 项目的这个 [pull request](https://github.com/NervJS/taro-sample-weapp/pull/25)，在文件 `pages/native/native.js` 中定义了一个 `taroHandler` 事件，在 `pages/native/native.wxml` 中的组件 `tabNative` 调用上绑定了属性 `myProperty` 和事件 `tabHandler` ，之后在 taro 语法写的子组件 `tabNative.js`  中属性 `myProperty` 没有接收到，`onClick` 点击事件也不会被触发。

**Comment by Chen-jj** [comment]
@chenfaxiang 原生组件传 props 给 Taro 组件需要通过 [extraProps](https://nervjs.github.io/taro/docs/best-practice.html#%E5%8E%9F%E7%94%9F%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E4%BC%A0%E9%80%92-props-%E7%BB%99-taro-%E7%BB%84%E4%BB%B6)

**Comment by Chen-jj** [comment]
@chenfaxiang 

native.js:

```js
Page({
  onReady() {
    this.setData({
      extraProps: {
        myProperty: '+++++++++++++++++++taro component',
        taroHandler: this.taroHandler
      }
    })
  }
})
```

native.wxml:

```wxml
<tabNative extraProps="{{extraProps}}"></tabNative>
```

tabTaro.js:

```js
Component({
  clickHandler = () => {
    console.log(this.props.myProperty)
    this.props.taroHandler()
  }
})
```
