### ISSUE TITLE
如何使用 taro-echarts的canvasToTempFilePath

### ISSUE THREAD

**Issue by ywlang** [NervJS/taro#4124]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
因为使用的图表在小程序真机上有抖动问题，我打算把图表转化为图片展示
**复现步骤**
[复现问题的步骤]

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
这是插件地址http://npm.taobao.org/package/taro-echarts

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
希望能使用canvasToTempFilePath吧图表转换为图片
**报错信息**
直接使用Taro.canvasToTempFilePath报错，"canvasToTempFilePath: fail canvas is empty"
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.3.2]
 - Node.js 版本 [e.g. v8.9.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
这类第三方类库的问题你应该去相关的库去提 issue
