### ISSUE TITLE
自定义表单控件无效

### ISSUE THREAD

**Issue by zzzzyp** [NervJS/taro#4128]
**问题描述**
自定义的表单控件，加了static behaviors = ['wx://form-field']，在form里获取不到它的值

**复现步骤**
[复现问题的步骤]
1. 创建自定义表单控件
```
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

class InputItem extends Component {

  static behaviors = ['wx://form-field']

  state = {
    value: ''
  }


  render() {
    return (
      <View></View>
    )
  }
}

export default InputItem
```
2. 提交form,并打印
```
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Form } from '@tarojs/components'
import InputItem from '../../components/InputItem'


class Index extends Component {


  onSubmit = (e) => {
    console.log(e.detail.value)
  }

  render () {
    return (
      <View className='index'>
        <Form onSubmit={this.onSubmit}>
          <InputItem name='test'></InputItem>
          <Button formType='submit'>submit</Button>
        </Form>
      </View>
    )
  }
}

export default Index
```

**期望行为**
打印的值应为{ test: "" }

**报错信息**
实际打印值为{}

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.3.12]
 - Node.js 版本 [e.g. v10.13.0]
 - 报错平台 [weapp]

**补充信息**
复现的时候发现只要在自定义的组件中引用一下props.name，就可以拿到值了:(

**Comment by Chen-jj** [comment]
@zzzzyp 的确，没有显式使用到的 state 或 props 不会被加入到小程序的 data 中：

https://github.com/NervJS/taro/blob/b8c29c63bbbf62952f6da01b53bf4df8f57b8cc9/packages/taro-weapp/src/lifecycle.js#L154-L174

这个 behavior 我感觉是给组件定义了 name 和 value 的 properties，但并没有在 Taro 组件里显式声明或使用。因此建议写上 defaultProps 绕过。
