### ISSUE TITLE
快应用WebView加载不出页面

### ISSUE THREAD

**Issue by loveshuffle** [NervJS/taro#4129]
**问题描述**
WebView加载不出url

**复现步骤**
import Taro, { Component } from '@tarojs/taro'
import { View, Text, WebView } from '@tarojs/components'
import './index.scss'

export default class NewsVideo extends Component {

    constructor () {
        super()
        this.state = {
            videoUrl: 'https://huaban.com/'
        }
    }
    componentWillMount () { }

    componentDidMount () {}

    render () {
        const {videoUrl} = this.state;
        return (
            <WebView src={videoUrl} />
        )
    }
}

**期望行为**
能加载出url

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.12]
 - Node.js 版本 [e.g. v10.13.0]

**补充信息**
quickapp.json文件已配置了system.webview，在别的项目可以加载出url

**Comment by jinjinjin0731** [comment]
没有复现，可以正常加载出页面

```jsx
import Taro, { Component } from '@tarojs/taro'
import { WebView  } from '@tarojs/components'

export default class Index extends Component {
  constructor () {
    super()
    this.state = {
        videoUrl: 'https://huaban.com/'
    }
}

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  render () {
    const {  videoUrl  } = this.state;
    return (
        <WebView src={videoUrl} />
    )
  }
}

```

![1091565612579_ pic_hd](https://user-images.githubusercontent.com/17409735/62864721-138b5b00-bd3f-11e9-9286-fe4a9cdf0e09.jpg)
