### ISSUE TITLE
微信小程序，setState update 多个属性，appData没有更新

### ISSUE THREAD

**Issue by yeluolei** [NervJS/taro#4136]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

在函数内setState, 实际state已经生效，但是在appData面版中，只有一个值更新了。
```js
  componentWillMount() {
    let provinceCitiesStore = ProvinceConfig;
    var provincesCitiesInit = [
      provinceCitiesStore.map(x => x.label), 
      provinceCitiesStore[0].children.map(x => x.label)
    ]
    this.setState({
      provinceCitiesStore: provinceCitiesStore,
      provinceCities: provincesCitiesInit
    })
  }
```
在AppData面版中的值:
```
{
  "role": 0,
  "user": null,
  "onLogin": {
    "type": "app_first_launch"
  },
  "provinceCity": [
    2,
    2
  ],
  "sizeList": [
    {
      "value": 1,
      "label": "1-10人"
    },
    {
      "value": 2,
      "label": "10-100人"
    },
    {
      "value": 3,
      "label": "100-500人"
    },
    {
      "value": 4,
      "label": "500人以上"
    }
  ],
  "size": 0,
  "tmpLicenseFile": "",
  "tmpLogoFile": "",
  "province": "广东省",
  "city": "东莞市",
  "anonymousState__temp": "广东省 - 东莞市",
  "anonymousState__temp2": "请选择",
  "__key_": null,
  "__preload_": null,
  "compid": null,
  "__webviewId__": 971,
  "$compid__8910": "0",
  "$compid__8911": "1",
  "$compid__8912": "2",
  "$compid__8913": "3",
  "$compid__8914": "4",
  "$compid__8915": "5",
  "$compid__8916": "6",
  "$compid__8917": "7",
  "$compid__8918": "8",
  "$compid__8919": "9",
  "provinceCities": [
    [
      "北京市",
      "上海市",
      "广东省",
      "浙江省",
      "福建省",
      "甘肃省",
      "安徽省",
      "广西壮族自治区",
      "贵州省",
      "海南省",
      "河北省",
      "河南省",
      "黑龙江省",
      "湖北省",
      "湖南省",
      "吉林省",
      "江苏省",
      "江西省",
      "辽宁省",
      "内蒙古自治区",
      "宁夏回族自治区",
      "青海省",
      "山东省",
      "山西省",
      "陕西省",
      "重庆市",
      "四川省",
      "台湾省",
      "天津市",
      "云南省",
      "西藏自治区",
      "新疆维吾尔自治区",
      "香港特别行政区",
      "澳门特别行政区",
      "海外"
    ],
    [
      "广州市",
      "深圳市",
      "东莞市",
      "佛山市",
      "河源市",
      "惠州市",
      "江门市",
      "揭阳市",
      "茂名市",
      "梅州市",
      "清远市",
      "汕头市",
      "汕尾市",
      "韶关市",
      "潮州市",
      "阳江市",
      "云浮市",
      "湛江市",
      "肇庆市",
      "中山市",
      "珠海市"
    ]
  ],
  "$taroCompReady": true
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
AppData 应该与state同步

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.0

  Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.0 => 1.3.0
      @tarojs/components: 1.3.0 => 1.3.0
      @tarojs/plugin-babel: 1.3.0 => 1.3.0
      @tarojs/plugin-csso: 1.3.0 => 1.3.0
      @tarojs/plugin-sass: 1.3.0 => 1.3.0
      @tarojs/plugin-uglifyjs: 1.3.0 => 1.3.0
      @tarojs/redux: 1.3.0 => 1.3.0
      @tarojs/redux-h5: 1.3.0 => 1.3.0
      @tarojs/router: 1.3.0 => 1.3.0
      @tarojs/taro: 1.3.0 => 1.3.0
      @tarojs/taro-alipay: 1.3.0 => 1.3.0
      @tarojs/taro-h5: 1.3.0 => 1.3.0
      @tarojs/taro-swan: 1.3.0 => 1.3.0
      @tarojs/taro-tt: 1.3.0 => 1.3.0
      @tarojs/taro-weapp: 1.3.0 => 1.3.0
      @tarojs/webpack-runner: 1.3.0 => 1.3.0
      eslint-config-taro: 1.3.0 => 1.3.0
      eslint-plugin-taro: 1.3.0 => 1.3.0
      nervjs: ^1.3.9 => 1.4.0
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@yeluolei https://nervjs.github.io/taro/docs/debug.html#debug-diff 先自行打断点定位下吧。
