### ISSUE TITLE
npm run dev:h5 编译成功，但是页面报错 Cannot read property 'dispatch' of undefined     at Connect.initSelector

### ISSUE THREAD

**Issue by summer-yyyn** [NervJS/taro#4141]
**问题描述**
npm run dev:h5 编译成功，但是页面报错 Cannot read property 'dispatch' of undefined     at Connect.initSelector

**复现步骤**
npm run dev:h5 

但是项目中npm run dev:wepp 编译正常，小程序运行也正常

**期望行为**
期望，方便的花给出解决方案，谢谢

**报错信息**
Uncaught TypeError: Cannot read property 'dispatch' of undefined
    at Connect.initSelector (index.esm.js?9e15:572)
    at new Connect (index.esm.js?9e15:500)
    at mountComponent (index.esm.js?5b59:1708)
    at ComponentWrapper.init (index.esm.js?5b59:2137)
    at createElement (index.esm.js?5b59:1398)
    at mountVNode (index.esm.js?5b59:1699)
    at Object.render (index.esm.js?5b59:2051)
    at eval (app.js?d0a8:347)
    at Module../.temp/app.js (app.7629dc6629fef4869bdf.js:927)
    at __webpack_require__ (app.7629dc6629fef4869bdf.js:767)

**系统信息**
👽 Taro v1.3.12

  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v12.4.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.12 => 1.3.12 
      @tarojs/components: 1.3.12 => 1.3.12 
      @tarojs/plugin-babel: 1.3.12 => 1.3.12 
      @tarojs/plugin-csso: 1.3.12 => 1.3.12 
      @tarojs/plugin-sass: 1.3.12 => 1.3.12 
      @tarojs/plugin-uglifyjs: 1.3.12 => 1.3.12 
      @tarojs/redux: 1.3.12 => 1.3.12 
      @tarojs/redux-h5: 1.3.12 => 1.3.12 
      @tarojs/router: 1.3.12 => 1.3.12 
      @tarojs/taro: 1.3.12 => 1.3.12 
      @tarojs/taro-alipay: 1.3.12 => 1.3.12 
      @tarojs/taro-h5: 1.3.12 => 1.3.12 
      @tarojs/taro-swan: 1.3.12 => 1.3.12 
      @tarojs/taro-tt: 1.3.12 => 1.3.12 
      @tarojs/taro-weapp: 1.3.12 => 1.3.12 
      @tarojs/webpack-runner: 1.3.12 => 1.3.12 
      eslint-config-taro: 1.3.12 => 1.3.12 
      eslint-plugin-taro: 1.3.12 => 1.3.12 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
      stylelint-config-taro-rn: 1.3.12 => 1.3.12 
      stylelint-taro-rn: 1.3.12 => 1.3.12 

 - 报错平台 [h5]

**Comment by Littly** [comment]
没有复现，麻烦提供代码。

**Comment by summer-yyyn** [comment]
哪一块儿的代码？

**Comment by summer-yyyn** [comment]
报错信息点开是这个文件webpack:///node_modules/_@tarojs_redux-h5@1.3.12@@tarojs/redux-h5/dist/index.esm.js?9e15

**Comment by Littly** [comment]
> 哪一块儿的代码？

页面的代码，或者可以复现问题的最小仓库

**Comment by Littly** [comment]
检查下是不是组件的构造函数把context传丢了吧

**Comment by animasling** [comment]
我也遇到这问题了。 1.3.20 伤心

**Comment by waveheart** [comment]
同遇到了这个问题， 我的问题是在 app.js 上面直接使用了@connect(mapState, mapDispatch).
解决方案是不写这两行， 因为app.js 上会注入store 实例。 需要dispatch 或者拿数据的话，直接调用store对应的方法

**Comment by 54853315** [comment]
我说一下我的实现过程，仅针对Taro v2.2.6 


```
//app.jsx 

import { Provider } from '@tarojs/redux'
import configStore from './store'



const store = configStore()


class App extends Component {
//....

render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
}
```

具体的业务pages /home.jsx

```
import Taro, { Component } from "@tarojs/taro";
import * as actions from '@actions/home'
import { connect } from "@tarojs/redux";

class Home extends Component {

}
```

这样我是正常运行的。
@connect(state => state.home, { ...actions })

**Comment by navydong** [comment]
> 检查下是不是组件的构造函数把context传丢了吧

我也遇到了，debugger了下源码，定位到是父组件的context丢失
造成原因：应该是父组件这样写了
```js
constructor(props){ 
    super(props)
}
```
导致只传递的props，context丢失

按下面这样就可以了
```js
constructor(){ 
    super(...arguments) 
}
```
