### ISSUE TITLE
window下通过官方文档步骤新建初始化项目后无法运行！报错找不到index.js！尝试N遍！

### ISSUE THREAD

**Issue by wsmhz** [NervJS/taro#4148]
**问题描述**

通过官方文档步骤新建初始化项目无法运行

**复现步骤**
1.npm install -g @tarojs/cli
2.taro init myApp
3.cd myApp
（选择ts跟js都尝试了，默认模板）
4.npm run dev:weapp
 run时编译报错

**期望行为**

正常运行，让我看见hello world ！好嘛？(#^.^#)

**报错信息**

![image](https://user-images.githubusercontent.com/33542541/62857776-04021700-bd2b-11e9-8ffb-8f243e82e5f7.png)
编译后提示dist文件夹下index目录找不到index.js

**系统信息**
![image](https://user-images.githubusercontent.com/33542541/62857930-78d55100-bd2b-11e9-945a-1bc01981fafe.png)
 - 操作系统:  Windows 7
 - Taro 版本  v1.3.12
 - Node.js 版本 10.5.0
 - 报错平台 weapp

**补充信息**
![image](https://user-images.githubusercontent.com/33542541/62858922-4f69f480-bd2e-11e9-9cbc-0370618454a5.png)

尝试过卸载node.js环境（10x，8x） 卸载全局taro环境，重新安装，npm install
尝试过选择ts，选择js，选择默认模板，redux

**Comment by Pines-Cheng** [comment]
模版问题？

**Comment by Chen-jj** [comment]
@wsmhz taro init 的截图、及 taro init 后的项目代码扔上来一下

**Comment by Chen-jj** [comment]
@wsmhz 把文件夹 node.js 改一下名，不要有 .js，下个版本修复

![image](https://user-images.githubusercontent.com/11807297/62871403-04f87000-bd4e-11e9-9737-174fcbb3dfb9.png)

**Comment by wsmhz** [comment]
@Chen-jj , 已找出问题了，果然修改项目所在文件夹名称为不带.js即可编译，惊了(#^.^#)
