### ISSUE TITLE
最新版的taro 安装tarocli的时候出错 

### ISSUE THREAD

**Issue by franken133** [NervJS/taro#4151]
找不到依赖包postcss-pxtransform1.3.13

**Comment by Eric-Guo** [comment]
Same here, root reason is package [postcss-pxtransform](https://www.npmjs.com/package/postcss-pxtransform) highest version is 1.3.12.

**Comment by nyaapass** [comment]
根据 [npmjs.com](https://www.npmjs.com/package/postcss-pxtransform) 显示, 1.3.13 版的 postcss-pxtransform 还没有发布至 npm 上, 目前上面还停留在 1.3.12 版

**Comment by luckyadam** [comment]
已发布

**Comment by shenghanqin** [comment]
现在才恍惚先前几次升级tarojs时，有一些版本升级还提示组件不存在的原因了，先去在npm上看看新版的子依赖是否发布了。
