### ISSUE TITLE
使用typescript 时，taro doctor对interface属性后无逗号或者分号的提示

### ISSUE THREAD

**Issue by nyrf** [NervJS/taro#4152]
**问题描述**
vscode使用prettier，typescript的interface属性后可以没有分号也没有逗号，但使用taro doctor检测会提示错误,

```js
interface Shop {
  id: number
  name: string
}
```

**报错信息**

```js
  9:3  error  Parsing error: Unexpected token

   7 | interface Shop {
   8 |   id: number
>  9 |   name: string
     |   ^
```
**系统信息**
❯ taro info
👽 Taro v1.3.11

  Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.6.0 - ~/.config/nvm/12.6.0/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.config/nvm/12.6.0/bin/npm

**Comment by yuche** [comment]
close via 093133a213858c66d230f63bb983b90d2cd28baf
