### ISSUE TITLE
函数式组件内定义一个函数，并在函数内返回jsx，编译报错。

### ISSUE THREAD

**Issue by missmimia** [NervJS/taro#4155]
**问题描述**
函数式组件内定义一个函数，并在函数内返回jsx，编译报错。

**复现步骤**

```js

const HomePage: Taro.FunctionComponent = () => {

  const handleUnFixedType = ({ layoutType }) => {
    let content;
    if(layoutType === 11 || layoutType === 12 || layoutType === 13) {
      content = (
        <View className={styles.activityImages}>
          <View>
            这是匹配layoutType 11 的标签
          </View>
        </View>
      );
    } else if (layoutType === 24) {
      content = (
        <View className={styles.activityImages}>
          今天天气真好
        </View>
      );
    } else {
      content = <View />;
    }
    return content;
  };

  return (
    <View>
      {handleUnFixedType(homeDettail)}
    </View>
  )
}

```

**期望行为**
编译通过不报错。

**报错信息**
TypeError: Cannot read property 'path' of undefined
    at RenderParser.handleJSXInIfStatement (F:\umart-mobile\node_modules\@tarojs\transformer-wx\lib\src\render.js:1573:78)
    at JSXElement.handleJSXElement (F:\umart-mobile\node_modules\@tarojs\transformer-wx\lib\src\render.js:392:26)
    at RenderParser.handleJSXElement (F:\umart-mobile\node_modules\@tarojs\transformer-wx\lib\src\render.js:95:17)
    at JSXElement (F:\umart-mobile\node_modules\@tarojs\transformer-wx\lib\src\render.js:390:22)
    at NodePath._call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:192:19)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 1.3.12
 - Node.js 版本 
 - 报错平台 weapp

**Comment by yuche** [comment]
把 handleUnFixedType 改为 render 开头

**Comment by missmimia** [comment]
> 把 handleUnFixedType 改为 render 开头

我这里有两个函数 改成render之后不报上面的错 
报这个：
TypeError: Cannot read property 'insertBefore' of undefined
    at Transformer.buildAnonyMousFunc (F:\umart-mobile\node_modules\@tarojs\transformer-wx\lib\src\class.js:126:43)
    at JSXExpressionContainer (F:\umart-mobile\node_modules\@tarojs\transformer-wx\lib\src\class.js:573:30)
    at NodePath._call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (F:\umart-mobile\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:115:19)

**Comment by yuche** [comment]
> > 把 handleUnFixedType 改为 render 开头
> 
> 我这里有两个函数 改成render之后不报上面的错
> 报这个：
> TypeError: Cannot read property 'insertBefore' of undefined
> at Transformer.buildAnonyMousFunc (F:\umart-mobile\node_modules@tarojs\transformer-wx\lib\src\class.js:126:43)
> at JSXExpressionContainer (F:\umart-mobile\node_modules@tarojs\transformer-wx\lib\src\class.js:573:30)
> at NodePath._call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:76:18)
> at NodePath.call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:48:17)
> at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:105:12)
> at TraversalContext.visitQueue (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:150:16)
> at TraversalContext.visitSingle (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:108:19)
> at TraversalContext.visit (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:192:19)
> at Function.traverse.node (F:\umart-mobile\node_modules\babel-traverse\lib\index.js:114:17)
> at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:115:19)

报这个错的代码贴一下

**Comment by missmimia** [comment]
> > > 把 handleUnFixedType 改为 render 开头
> > 
> > 
> > 我这里有两个函数 改成render之后不报上面的错
> > 报这个：
> > TypeError: Cannot read property 'insertBefore' of undefined
> > at Transformer.buildAnonyMousFunc (F:\umart-mobile\node_modules@tarojs\transformer-wx\lib\src\class.js:126:43)
> > at JSXExpressionContainer (F:\umart-mobile\node_modules@tarojs\transformer-wx\lib\src\class.js:573:30)
> > at NodePath._call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:76:18)
> > at NodePath.call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:48:17)
> > at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:105:12)
> > at TraversalContext.visitQueue (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:150:16)
> > at TraversalContext.visitSingle (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:108:19)
> > at TraversalContext.visit (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:192:19)
> > at Function.traverse.node (F:\umart-mobile\node_modules\babel-traverse\lib\index.js:114:17)
> > at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:115:19)
> 
> 报这个错的代码贴一下


  const renderFixedType = ({ layoutType, detailList = [{showProductUrl: []}] }) => {
    let content;
    if(layoutType === 12 || layoutType === 24) {
      content = (
        <View className={styles.featuredV3}>
          <View className={styles.featuredItem}>
            <View className={styles.featuredItemTitle}>{detailList[0].mainTitle}</View>
            <View className={styles.featuredItemDesc}>{detailList[0].subTitle}</View>
            <View className={styles.featuredBtn}>立即疯抢</View>
            <View className={styles.v3PicWrapper}>
              {
                !!detailList[0].showProductUrl.length && (
                  <Image className={styles.v3Pic} src={detailList[0].showProductUrl[0].imgUrl} />
                )
              }
            </View>
          </View>
          <View className={styles.featuredRightItem}>
            {
              detailList.slice(1, 3).map((item, index) => (
                <View key={item.id} className={styles.item}>
                  <View>
                    <View className={styles.featuredItemTitle}>{item.mainTitle}</View>
                    <View className={styles.featuredItemDesc}>{item.subTitle}</View>
                    <View className={styles.featuredBtn}>立即疯抢</View>
                  </View>
                  <View className={styles.v3RightPic}>
                    {
                      !!item.showProductUrl.length && (
                        <Image src={item.showProductUrl[index].imgUrl} />
                      )
                    }
                  </View>
                </View>
              ))
            }
          </View>
        </View>
      );
    }
    return content;
  };

**Comment by Varavarforvar** [comment]
突然遇到了这个问题，几分钟前还好好的

**Comment by yuche** [comment]
>   const renderFixedType = ({ layoutType, detailList = [{showProductUrl: []}] }) => {
>     let content;
>      if(layoutType === 12 || layoutType === 24) {
>        content = (
>          <View className={styles.featuredV3}>
>            <View className={styles.featuredItem}>
>              <View className={styles.featuredItemTitle}>{detailList[0].mainTitle}</View>
>              <View className={styles.featuredItemDesc}>{detailList[0].subTitle}</View>
>              <View className={styles.featuredBtn}>立即疯抢</View>
>              <View className={styles.v3PicWrapper}>
>                {
>                  !!detailList[0].showProductUrl.length && (
>                    <Image className={styles.v3Pic} src={detailList[0].showProductUrl[0].imgUrl} />
>                  )
>                }
>              </View>
>            </View>
>            <View className={styles.featuredRightItem}>
>              {
>                detailList.slice(1, 3).map((item, index) => (
>                  <View key={item.id} className={styles.item}>
>                    <View>
>                      <View className={styles.featuredItemTitle}>{item.mainTitle}</View>
>                      <View className={styles.featuredItemDesc}>{item.subTitle}</View>
>                      <View className={styles.featuredBtn}>立即疯抢</View>
>                    </View>
>                    <View className={styles.v3RightPic}>
>                      {
>                        !!item.showProductUrl.length && (
>                          <Image src={item.showProductUrl[index].imgUrl} />
>                        )
>                      }
>                    </View>
>                  </View>
>                ))
>              }
>            </View>
>          </View>
>        );
>     }
>     return content;
>   };

贴整个文件，你这个片段也不会报错

**Comment by missmimia** [comment]
> > const renderFixedType = ({ layoutType, detailList = [{showProductUrl: []}] }) => {
> > let content;
> > if(layoutType === 12 || layoutType === 24) {
> > content = (
> > 
> > 
> > {detailList[0].mainTitle}
> > {detailList[0].subTitle}
> > 立即疯抢
> > 
> > {
> > !!detailList[0].showProductUrl.length && (
> > ![]({detailList[0].showProductUrl[0].imgUrl})
> > )
> > }
> > 
> > 
> > 
> > {
> > detailList.slice(1, 3).map((item, index) => (
> > 
> > 
> > {item.mainTitle}
> > {item.subTitle}
> > 立即疯抢
> > 
> > 
> > {
> > !!item.showProductUrl.length && (
> > ![]({item.showProductUrl[index].imgUrl})
> > )
> > }
> > 
> > 
> > ))
> > }
> > 
> > 
> > );
> > }
> > return content;
> > };
> 
> 贴整个文件，你这个片段也不会报错

咦  整个文件如果去掉这个函数编译阶段 就不会报错了。。。。

emmmm 我抽成class组件出来了 现在是可以了。。>.<

**Comment by yuche** [comment]
你不去掉这个函数会报错吗，什么样的情况下会报错

**Comment by missmimia** [comment]
> 你不去掉这个函数会报错吗，什么样的情况下会报错

写法就是正常写一个render开头的函数，里面返回jsx，然后我在页面调用。但编译的时候就报错了。
注释掉这个render开头的函数就可以正常编译，项目也跑的起来。不去掉就是在编译的阶段就报错了。

报下面这个错：
TypeError: Cannot read property 'insertBefore' of undefined
at Transformer.buildAnonyMousFunc (F:\umart-mobile\node_modules@tarojs\transformer-wx\lib\src\class.js:126:43)
at JSXExpressionContainer (F:\umart-mobile\node_modules@tarojs\transformer-wx\lib\src\class.js:573:30)
at NodePath._call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:76:18)
at NodePath.call (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:48:17)
at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:105:12)
at TraversalContext.visitQueue (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:150:16)
at TraversalContext.visitSingle (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:108:19)
at TraversalContext.visit (F:\umart-mobile\node_modules\babel-traverse\lib\context.js:192:19)
at Function.traverse.node (F:\umart-mobile\node_modules\babel-traverse\lib\index.js:114:17)
at NodePath.visit (F:\umart-mobile\node_modules\babel-traverse\lib\path\context.js:115:19)

**Comment by yuche** [comment]
贴整个文件的代码

**Comment by redblue9771** [comment]
闭包函数组件在使用外部Apollo Hooks生成的变量时就也触发这个Err
```
  function Page() {
    const { data: storeList, error: storeListErr, loading } = useStoreListQuery()

    const renderSub = () => {
      return storeList && storeList.map((item) => <View />)
    }

    return <View>{renderSub}</View>
  }

```

> 🙅   编译失败.
> 
> ./src/pages/index/index.tsx
> Module Error (from ./node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js):
> Cannot read property 'insertBefore' of undefined
>

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
