### ISSUE TITLE
以render开头的箭头函数编译报错

### ISSUE THREAD

**Issue by John251314** [NervJS/taro#4159]
**问题描述**
从1.3.4升级到1.3.12，以render开头的箭头函数编译报错；以前不报错，现在报错，改成render开头的方法后，正常编译运行，

>Error: 以 render 开头的类函数必须返回 JSX，否则会导致渲染失败。如果是为了渲染字符串，建议更名。
> 以 VSCode 为例：右键点击选择方法名，点击 rename symbol（重命名符号），输入新方法名。

**复现步骤**
1. 自定义组件，使用render开头的箭头函数渲染子节点
2. 保存编译，报错

```
    renderRow = (promotionList: Promotion[], index: number) => {
        const { onClickItem } = this.props;
        return (
            <View key={index.toString()} className={styles.row}>
                {promotionList.map((promotion, key) => (
                    <View key={key.toString()} className={styles.item}>
                        <PromotionGriditem
                            promotion={promotion}
                            onClick={() => {
                                onClickItem(promotion)
                            }}
                        />
                    </View>
                ))}
            </View>
        );
    }
```

**期望行为**
可通过编译并正常执行

**报错信息**

![image](https://user-images.githubusercontent.com/19367953/62918294-cc01df00-bdd1-11e9-805e-135dabf20910.png)

**系统信息**

 - 操作系统:macOS 10.14.3
 - Taro 版本: 👽 Taro v1.3.12
 - Node.js 版本 :8.12.0 
 - 报错平台: weapp

**Comment by chenjigeng** [comment]
这个啥时候发版？目前依赖这个东西。。

**Comment by snowshoes** [comment]
v.1.3.14 已集成

**Comment by jlala** [comment]
现在问题依旧存在

**Comment by yuche** [comment]
> 现在问题依旧存在

v.1.3.14 还是会报这个错吗

**Comment by jlala** [comment]
> > 现在问题依旧存在
> 
> v.1.3.14 还是会报这个错吗

是的还存在这个编译警告问题
![image](https://user-images.githubusercontent.com/8163601/63669720-581df880-c80d-11e9-9ed7-932de45720fd.png)

**Comment by yuche** [comment]
> > > 现在问题依旧存在
> > 
> > 
> > v.1.3.14 还是会报这个错吗
> 
> 是的还存在这个编译警告问题
> ![image](https://user-images.githubusercontent.com/8163601/63669720-581df880-c80d-11e9-9ed7-932de45720fd.png)

能把你报错的用例用代码字符串贴出来吗

**Comment by xsq007** [comment]
![image](https://user-images.githubusercontent.com/10074113/70518773-e24c5b80-1b75-11ea-94a7-e24aff85c5d1.png)

在v1.3.27 编译遇到上述错误
