### ISSUE TITLE
iconfont未能打包到static文件中,图片资源正常

### ISSUE THREAD

**Issue by cleverTom** [NervJS/taro#4160]
**问题描述**
[问题描述：使用阿里iconfont进行资源打包,iconfont文件未能拷贝到static文件夹中, 但是并未转成base64格式, wxss引用了哈希后的文件]

**复现步骤**
[复现问题的步骤]
1. app.tsx中引入iconfont.scss
2.iconfont中@font-face引入url中本地src/static/font/iconfont.eot文件
3. 执行Taro 打包操作
4. 最外层的static并不包含字体文件,但是编译后的wxss引用了哈希后的文件;

**期望行为**
[期望打包后能够包含字体文件]

**报错信息**
config中url的limit改为false也不生效;
打包后的wxss信息如下:
@font-face {
  font-family: "iconfont";
  src: url("http://localhost:8080/test/d5716c52.eot");
  /* IE9 */
  src: url("http://localhost:8080/test/d5716c52.eot") format("embedded-opentype"), url("http://localhost:8080/test/3b989fe6.woff2") format("woff2"), url("http://localhost:8080/test/695ff911.woff") format("woff"), url("http://localhost:8080/test/dd0a5ecd.ttf") format("truetype"), url("http://localhost:8080/test/29befde8.svg") format("svg");
  /* iOS 4.1- */ }
文件并未拷贝到外层static文件夹中;
[无报错信息, wxss中使用hash的静态文件,但是并未拷贝到static文件夹]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Mac 10.14.6]
 - Taro 版本 [e.g. v1.3.10]
 - Node.js 版本 [e.g. v11.1.0]
 - 报错平台 [weapp]

**Comment by linkMHran** [comment]
微信小程序端, 我开启了静态资源引用后, 连线上的iconfont引用都会被打包成本地, 现在解不了啊

**Comment by linkMHran** [comment]
哦, iconfont.css必须和eot文件在一个目录下,才能拷贝进去

**Comment by linkMHran** [comment]
老铁,升级了一个昨天的小版本,又不行了 啊 这个问题查一下吧
