### ISSUE TITLE
不渲染组件，结果却执行了子组件的生命周期

### ISSUE THREAD

**Issue by hnsylitao** [NervJS/taro#4169]
**问题描述**
不渲染组件，结果却执行了子组件的生命周期

**复现步骤**
[复现问题的步骤]

> index

```js
 render(){
  return <View>
      <Authority renderNoMath={<Text>没有权限?</Text>}>
        <Production>
          <Text>Welcome</Text>
        </Production>
      </Authority>
 <View>
}
```
> Authority 

```js
 render(){
  return <Block>
      {this.state.authority ? this.props.children : this.props.renderNoMath}
 <View>
}
```
> Production

```js
 componentDidMount(){
  console.log('did mount');
 }
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\Application\Development\nodejs\node.EXE
      Yarn: 1.16.0 - D:\Application\Development\npm\yarn.CMD
      npm: 6.4.1 - D:\Application\Development\nodejs\npm.CMD

**Comment by hnsylitao** [comment]
按照我的理解，应该production 不会渲染猜对，结果却是触发了所有的生命周期。。

**Comment by luckyadam** [comment]
微信小程序么

**Comment by hnsylitao** [comment]
@luckyadam 是的

**Comment by Chen-jj** [comment]
@hnsylitao render 传 JSX 在小程序端是通过 **slot** 实现的。

而我测试过原生写法， 假设通过 slot 传自定义组件 <b><b/>，即使子组件不使用此传入的组件 b，b 也会触发其 attached 生命周期。所以你遇到的问题属于小程序自身限制，暂时没有办法解决。

建议把判断放到父组件或使用 renderProps 实现。

**Comment by hnsylitao** [comment]
谢谢了，只能改变写法了。
