### ISSUE TITLE
自定义组件的 behaviors？

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#417]
现在（v1.0.0-beta.5）支持转换成自定义组件之后有一个问题就是，如果我用自定义组件包装了一个 button（`<Button formType="submit">Submit</Button>`），之后想调用的时候裹一个 `<Form>`，`onSubmit` 是取不到结果的。

![](https://ws4.sinaimg.cn/large/0069RVTdgy1ftve212juyj31k20880u7.jpg)

但是微信提供了类似 mixins 的 [behaviors](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/behaviors.html)，尤其是 「*自定义组件可以通过引用内置的 `behavior` 来获得内置组件的一些行为。*」：

> 代码示例：
>
> ```
> Component({
>    behaviors: ['wx://form-field'] 
> })
> ```
> 在上例中， wx://form-field 代表一个内置 behavior ，它使得这个自定义组件有类似于表单控件的行为。
> 内置 behavior 往往会为组件添加一些属性。在没有特殊说明时，组件可以覆盖这些属性来改变它的 type 或添加 observer 。

或许在 Taro 中可以保留组件的 `behavior` 属性关键字，让用户传入数组？

```js
<Btn behaviors={['wx://form-field']} />
```

当想 mixin 其他组件的属性、数据、生命周期函数和方法的时候：

```
import AnotherComp from './AnotherComp'

<Btn behaviors={[AnotherComp]} />
```

或者上面二者统一一下：
```
import { WxFormField } from '@tarojs/behaviors'
import AnotherComp from './AnotherComp'

<Btn behaviors={[WxFormField, AnotherComp]} />
```

（`AnotherComp` 被编译成用 `Behavior()` 构造器定义？）

或者更符合 React 用法的是：

```
import { WxFormField } from '@tarojs/components'
import AnotherComp from './AnotherComp'

class Btn extends WxFormField { ... } // 'wx://form-field'
class Btn extends AnotherComp { ... }
```

（但这样有点不大方便？）

不知道大佬们怎么看？

**Comment by Simbachen** [comment]
1、普通的方法和属性可以通过组件继承而来
2、内置behaviors则需要通过配置的方式了

其中1目前是已经支持的，2考虑在组件里增加一个behavior的配置字段，具体方案我们还得再确定一下，会尽快支持的

**Comment by Simbachen** [comment]
beta.8版本组件已支持behaviors配置：static behaviors = []

**Comment by yanchengqu** [comment]
建议官网提供一个behaviors实例代码。我从原生小程序迁移到taro，还是不起作用。有实例代码对比一下，才能发现是否我姿势不对。
