### ISSUE TITLE
H5 配置了router打包后部署到服务器上无法访问

### ISSUE THREAD

**Issue by giantss** [NervJS/taro#4171]
**问题描述**
H5 打包后部署到服务器上无法访问，在本地可以访问。

**config/index.js**

```
 h5: {
  ...
    router: {
      mode: 'browser',
      basename: '/report',
      customRoutes: {
        '/pages/home/index': '/home',
        '/pages/callback/login/index': '/callback_login',
        '/pages/callback/pay/index': '/callback_pay',
        '/pages/buy/index':'/buy',
      }
    },
...
}
```

以上配置 运行 `yarn dev:h5` 在本地可以通过 `http://127.0.0.1:10086/report/home`访问，但`yarn build:h5` 部署到服务器后，通过 `http://{{domain}}/report/home` 访问报 404 错误，请教问题出在那里。。

**Comment by giantss** [comment]
@Littly 求指点。。

**Comment by jackie-gan** [comment]
个人觉得是，静态服务器没有做对应的配置

**Comment by giantss** [comment]
@jackie-gan  能看下你是服务器是怎么配置的么

**Comment by Littly** [comment]
@jackie-gan 说得对 browser模式需要服务器配置相应的fallback

**Comment by giantss** [comment]
@Littly 能给个例子吗？着急啊

**Comment by yuxino** [comment]
`mode`为`browser`的话在`nginx`加一段配置试试

```
location / {
  try_files $uri $uri/ /index.html;
} 
```

`hash`的话就不需要配置了 但是页面某些地方有用到锚点定位的话 需要注意一下

**Comment by giantss** [comment]
嗯 我最终看了这个  https://segmentfault.com/a/1190000017855419 解决了我的问题，我的一个域名下面部署了多个子目录，所以不能用根目录。
