### ISSUE TITLE
hooks 微信分享

### ISSUE THREAD

**Issue by Mihawk-zhao** [NervJS/taro#4172]
![8de547253f9ef0ffd45214692e12dae](https://user-images.githubusercontent.com/19793378/63068502-ea88e700-bf45-11e9-8a85-3380cd14d046.png)
加了这个函数，还是没有分享出现
![image](https://user-images.githubusercontent.com/19793378/63068511-f4aae580-bf45-11e9-9075-4b483e8a40ba.png)

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/commit/ba91cb97e1737b62824ed4ddda0d2203bfdf5f86
下个版本
