### ISSUE TITLE
微信小程序转Taro后props里没有函数，无法使用triggerEvent

### ISSUE THREAD

**Issue by lvxianlei** [NervJS/taro#4175]
原微信小程序中
![image](https://user-images.githubusercontent.com/22474478/63070565-47889b00-bf4e-11e9-99c6-c7d9c3d3e2d3.png)
![image](https://user-images.githubusercontent.com/22474478/63070577-5707e400-bf4e-11e9-95c9-ef1a4ddaaf65.png)
转换后：
![image](https://user-images.githubusercontent.com/22474478/63070595-65560000-bf4e-11e9-8ea4-ea261fd93987.png)
![image](https://user-images.githubusercontent.com/22474478/63070624-7c94ed80-bf4e-11e9-813c-6423cfe84143.png)
但是这个调用无效，经改动为
![image](https://user-images.githubusercontent.com/22474478/63070637-90d8ea80-bf4e-11e9-81b3-38ee81a49491.png)
后，仍然无效，render（）中打印 this.props
![image](https://user-images.githubusercontent.com/22474478/63070660-af3ee600-bf4e-11e9-893e-43b0e32639ba.png)
![image](https://user-images.githubusercontent.com/22474478/63070671-c1208900-bf4e-11e9-9ce0-3557cf70f4c7.png)
render第二次打印结果为
![image](https://user-images.githubusercontent.com/22474478/63070696-db5a6700-bf4e-11e9-9212-637f93e7000d.png)

**Comment by Chen-jj** [comment]
无法复现
