### ISSUE TITLE
页面引用组件传递props时，组件在render函数上打印props并没有对应值，页面在componentDidMount执行this.setState函数后组件才能获得对应的值

### ISSUE THREAD

**Issue by gaoyuanfell** [NervJS/taro#4178]
**问题描述**
页面引用组件传递props时，组件在render函数上打印props并没有对应值，页面在componentDidMount执行this.setState函数后组件才能获得对应的值

**复现步骤**
[复现问题的步骤]

componentDidMount函数内执行this.setState后，CuCustom组件才能在传入的值
![image](https://user-images.githubusercontent.com/21239565/63075488-80cc0580-bf64-11e9-9fa3-dedc08c2bf04.png)

```js

import { Component } from "@tarojs/taro";
import { View } from "@tarojs/components";
import CuCustom from "../../components/cu-custom/cu-custom";

export default class Demo extends Component{

  constructor(props) {
    super(props)
    this.state = {

    }
  }

  state: any

  componentWillMount() {

  }

  componentDidMount() {
    this.setState({
      a:1
    })
  }

  componentWillUnmount() {

  }

  // 微信/百度/字节跳动/支付宝小程序
  componentDidShow() { }

  // 微信/百度/字节跳动/支付宝小程序
  componentDidHide() { }

  render(){
    return (
      <View className="tab-scroll">
         <CuCustom isCustom={false} isBack={true} backText="关闭" titleText="demo"></CuCustom>
      </View>
    )
  }
}




import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text, Block } from '@tarojs/components';
import './cu-custom.scss';

export default class CuCustom extends Component<any> {
  constructor() {
    super();
    this.state = {
      
    }
  }

  static options = {
    addGlobalClass: true
  }

  config: Config = {}

  state: any

  componentWillMount() {

  }

  componentDidMount() {
    
  }

  componentWillUnmount() { }

  // 微信/百度/字节跳动/支付宝小程序
  componentDidShow() { }

  // 微信/百度/字节跳动/支付宝小程序
  componentDidHide() { }

  render() {
    console.info(this.props)
    return (
      <View></View>
    )
  }
}


```

**期望行为**
组件内能够或去页面传进来的值，不需要在页面内执行this.setState方法

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
真确的结果
![image](https://user-images.githubusercontent.com/21239565/63077003-8546ed00-bf69-11e9-89bf-d55a81e7b061.png)
![image](https://user-images.githubusercontent.com/21239565/63076981-74967700-bf69-11e9-86d2-a786036f0206.png)

错误的结果
![image](https://user-images.githubusercontent.com/21239565/63077021-9132af00-bf69-11e9-8c02-863ead2cb87e.png)
![image](https://user-images.githubusercontent.com/21239565/63077032-9a238080-bf69-11e9-8d30-6eb827c8e2ea.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 v1.3.13
 - Node.js 版本 10.15.3
 - 报错平台 weapp

**补充信息**

**Comment by Chen-jj** [comment]
@gaoyuanfell 

```js
constructor(props) {
  super(props)
}
```

**Comment by gaoyuanfell** [comment]
> @gaoyuanfell
> 
> ```js
> 构造函数（道具）{
>    super（props）
> }
> ```

失误失误，组件忘记加了
