### ISSUE TITLE
在使用到微信小程序插件时，如何再进行这种跨平台开发呢？

### ISSUE THREAD

**Issue by jzsjiale** [NervJS/taro#418]
对于微信小程序这边，有些功能点可以使用到微信小程序插件来实现，那么这种情况下，如何再进行跨平台开发呢？

**Comment by zacksleo** [comment]
直接使用微信原生的插件恐怕不行，或者小程序插件也使用Taro开发？

**Comment by jzsjiale** [comment]
微信小程序插件，不一定是自己开发的，这是个问题，可以考虑下这块，现在微信小程序插件越来越多，很多别人的插件功能都可以直接引入使用，不用重复开发了，这样对跨平台开发来说是个很大的问题。

**Comment by luckyadam** [comment]
@jzsjiale 这种情况很难做到跨平台了，除非那些插件用 Taro 开发~

**Comment by ZhechenLi** [comment]
> 那么Taro现阶段怎么开发小程序插件?

用 @tarojs/redux 的 setStore 代替 app.js 中的 Provider
```js
// path/to/pages/index/index
import {setStore} from '@tarojs/redux';
setStore(store);
```
App.config.pages 不要忘，暂时就发现这些坑
开发插件的时候 app.js 里面的代码都会被忽略

**Comment by luckyadam** [comment]
@ZhechenLi  有 global

**Comment by ZhechenLi** [comment]
> @ZhechenLi 有 global

可是类似 regenerator 这类变量在插件的代码里面是访问不到的，得改成 global.regenerator
```js
// would be wrong
regenerator.wrap(...)

// nice 
global.regenerator.wrap(...)
```

当初是假想如果能接收接入方传来的全局作用域，来实现下面的效果
```js
scope.regenerator = require(...)
// nice
regenerator.wrap(...)
```

当然后来发现还是行不通😂

**Comment by luckyadam** [comment]
嗯嗯，只能通过 global.xx 访问，你可以通过 Taro 的内置环境变量来写不同平台的代码试试

**Comment by CrazyOctopusDan** [comment]
然而我还是不知道怎么让plugin文件通过编译。。。

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/e3ca6ca779aa092f59dd40303647e170ec62ee4a
