### ISSUE TITLE
在taro中引入vant-weapp，vant自带的部分Props，Events无效

### ISSUE THREAD

**Issue by kapbook-caizhehao** [NervJS/taro#4181]
背景：在taro中引入了vant-weapp的popup组件，popup组件中部分props和event无效
代码：
![image](https://user-images.githubusercontent.com/38315632/63089441-71f84980-bf8a-11e9-8ea3-e8fb5065bc54.png)
参考：
![image](https://user-images.githubusercontent.com/38315632/63089460-81779280-bf8a-11e9-8fcc-b6aa24e31af6.png)
![image](https://user-images.githubusercontent.com/38315632/63089472-8ccabe00-bf8a-11e9-93dc-c125a795b8d7.png)

**Comment by luckyadam** [comment]
https://taro-docs.jd.com/taro/docs/miniprogram-plugin.html#taro-v13-%E7%BB%84%E4%BB%B6%E6%8F%92%E4%BB%B6%E6%8E%A5%E5%8F%97%E5%A4%96%E9%83%A8-props-%E7%9A%84%E9%97%AE%E9%A2%98

用 extraProps 传递

**Comment by Chen-jj** [comment]
@kapbook-caizhehao extraProps 是原生组件使用 Taro 组件使用的，这里不适用。

Taro 组件使用原生组件时，事件以 on 开头。你把 `bind:click-overlay={this.clickClose}` 改成 `onclick-overlay={this.clickClose}` 即可

**Comment by shenghanqin** [comment]
> Vant Weapp 是移动端 Vue 组件库 Vant 的小程序版本，两者基于相同的视觉规范，提供一致的 API 接口，助力开发者快速搭建小程序应用。
看官方介绍，这是Vue方式的小程序组件库，原来在tarojs里面也适用？

**Comment by Chen-jj** [comment]
@shenghanqin 他们在小程序端是原生组件

**Comment by zhangchenna** [comment]
onclick-overlay={this.clickClose} 在taro 3.0.17 里并不生效啊

**Comment by ecpanda** [comment]
onclick-overlay={this.clickClose} 在taro 3.0.7 里也并不生效啊

**Comment by Chen-jj** [comment]
@ecpanda 重新开个 issue 吧，这是 Taro 2 的
