### ISSUE TITLE
无法引用在线iconfont

### ISSUE THREAD

**Issue by liuyunzyj** [NervJS/taro#4184]
如何引用在线的

![image](https://user-images.githubusercontent.com/40293335/63144146-22665c00-c024-11e9-89c6-d41626338361.png)

我这边引用加载不到？

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/63144186-4fb30a00-c024-11e9-9637-e819fb052c9d.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/63144267-b506fb00-c024-11e9-86fb-fec85a7c0fa0.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/63144263-b20c0a80-c024-11e9-8da1-59ccd17f2d19.png)

**Comment by Chen-jj** [comment]
@liuyunzyj 请按 issue 模板修改你的问题。

**Comment by liuyunzyj** [comment]
@Chen-jj 你能引入在线的iconfont吗？

**Comment by le0l1** [comment]
https://juejin.im/post/5b32f826e51d4558a934a61e  可以参考这个 引入在线iconfont
