### ISSUE TITLE
【taroize】wx:elif未被括号包裹会抛出异常，未给出正确提示

### ISSUE THREAD

**Issue by Qiyu8** [NervJS/taro#4188]
问题描述
微信小程序wxml写法如下：
```
<view >
    <view wx:if="{{data.test}}"></view>
    <view wx:elif="data.haha"></view>
</view>
```
在taro convert的过程中会报错
TypeError: Property left of LogicalExpression expected node to be of a type ["Expression"] but instead got null

复现步骤
1.在微信小程序根目录执行 taro convert

期望行为
因为wx:if没有被括号包裹会正常提示，因此希望wx:elif也能正常提示如下：
wx:elif 的值需要用双括号 `{{}}` 包裹它的值

报错信息
TypeError: Property left of LogicalExpression expected node to be of a type ["Expression"] but instead got null
      at handleConditions [D:\taro\packages\taroize\lib\src\wxml.js:427:31]

系统信息
操作系统: Windows 10
Taro 版本 v1.3.13
Node.js 版本 v12.7.0
报错平台 weapp
补充信息
优化点：在转换过程中如果能够提示微信小程序中具体某行的错误就很好了，这个问题在超过3000行的wxml文件中定位比较困难

**Comment by yuche** [comment]
复现源码崩了

**Comment by Qiyu8** [comment]
没有标记为code，哈哈
