### ISSUE TITLE
子组件中的列表组件调用父组件通过props传的带参函数，传的参数都是最后一项数据。

### ISSUE THREAD

**Issue by wuwenyuan111** [NervJS/taro#4190]
**问题描述**
父组件通过props传递一个带参函数给子组件，在子组件中的列表组件中每一个item的onClick属性来调用这个函数，并传入参数。最后发现每一个item传入的参数都是最后一个数据的数据项，没有分别赋值。

**复现步骤**
[复现问题的步骤]
1.父组件的函数：
```
onSearch = (searchValue?: string) => {
         const {getUserBaseInfo} = this.props;
         getUserBaseInfo(searchValue)
}
```
2.子组件调用
```
 // 列表数据循环调用此函数生成组件列表
  renderBattlesInfoItem = (info: any, infoType: 'our' | 'opponent') => {
    const {onSearch} = this.props;
    return <View key={info.userNo}>
      {/*用户数据*/}
      <View style={{textAlign: infoType === "opponent" ? 'right' : 'left'}}>
        <View style={{color: infoType === "opponent" ? '#ed3f14' : '#74caff'}}
    // 调用父组件传来的带参函数
      onClick={() => onSearch(info.userNo)}
>
          {info.userName}
        </View>
        <View>{info.clanName || '--'}</View>
      </View>
</View>
```

**期望行为**
列表组件的每一个onClick属性调用的参数是各自的数据，不是最后一项的数据

**系统信息**
 Taro CLI 1.3.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.12 => 1.3.12 
      @tarojs/components: 1.3.12 => 1.3.12 
      @tarojs/plugin-babel: 1.3.12 => 1.3.12 
      @tarojs/plugin-csso: 1.3.12 => 1.3.12 
      @tarojs/plugin-less: 1.3.12 => 1.3.12 
      @tarojs/plugin-sass: 1.3.12 => 1.3.12 
      @tarojs/plugin-stylus: 1.3.12 => 1.3.12 
      @tarojs/plugin-uglifyjs: 1.3.12 => 1.3.12 
      @tarojs/redux: 1.3.12 => 1.3.12 
      @tarojs/router: 1.3.12 => 1.3.12 
      @tarojs/taro: 1.3.12 => 1.3.12 
      @tarojs/taro-alipay: 1.3.12 => 1.3.12 
      @tarojs/taro-h5: 1.3.12 => 1.3.12 
      @tarojs/taro-swan: 1.3.12 => 1.3.12 
      @tarojs/taro-tt: 1.3.12 => 1.3.12 
      @tarojs/taro-weapp: 1.3.12 => 1.3.12 
      @tarojs/webpack-runner: 1.3.12 => 1.3.12 
      eslint-config-taro: 1.3.12 => 1.3.12 
      eslint-plugin-taro: 1.3.12 => 1.3.12 
      nervjs: ^1.4.3 => 1.4.3

**Comment by wuwenyuan111** [comment]
#### 可能是使用了匿名函数导致的问题。
我换成函数绑定this的方式就可以分别赋值了。
子组件：
```
...
 onClickNewUser(userNo){
  this.props.onSearch(userNo)
 }
...

        <View style={{color: infoType === "opponent" ? '#ed3f14' : '#74caff'}} onClick={this.onClickNewUser.bind(this,info.userNo)}>
....
```

**Comment by Chen-jj** [comment]
@wuwenyuan111 先用 bind 吧，这种情况对匿名函数的处理有点问题

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
