### ISSUE TITLE
组件填写 className 后，在小程序代码中看到class 值都有2个，重复！

### ISSUE THREAD

**Issue by kingctan** [NervJS/taro#4191]
组件填写 className 后，在小程序代码中看到class 值都有2个，重复了。

**Comment by Chen-jj** [comment]
@kingctan 请按 issue 模板修改你的问题。

**Comment by Surile** [comment]
@Chen-jj  在转编译的话，class名称会被编译两次、使用审查元素查看的时候会出现两个相同的class。

**Comment by seekcx** [comment]
![image](https://user-images.githubusercontent.com/8244814/63310417-36b09e80-c32d-11e9-8b4e-6c08e8cf04b8.png)

这样，每个 class 名称都有两个，实际上只写了一个

**Comment by jinjinjin0731** [comment]
有没有编译两个，看下编译出来的 dist 目录的小程序代码就知道了。 开发工具显示两个相关的 class ，这是开发工具的 Bug
