### ISSUE TITLE
taro h5 项目跑起来后浏览器报错：backend.js:formatted:6488 Uncaught TypeError: e.getPublicInstance is not a function

### ISSUE THREAD

**Issue by viclee25** [NervJS/taro#4194]
**问题描述**
taro h5 项目跑起来后浏览器报错：
backend.js:formatted:6488 Uncaught TypeError: e.getPublicInstance is not a function

**报错信息**

![image](https://user-images.githubusercontent.com/29431453/63205543-99f5c300-c0d8-11e9-86ee-3134e3e165d4.png)

**系统信息**

![image](https://user-images.githubusercontent.com/29431453/63205567-dde8c800-c0d8-11e9-9b8e-05ad90d7cc65.png)

**Comment by luckyadam** [comment]
看起来是某个浏览器插件报的错

**Comment by new9xgh** [comment]
看看是不是React DevTools这个引起的。
[Latest React DevTools breaking DEV when debugging](https://github.com/thepracticaldev/dev.to/issues/3744)

**Comment by yang657850144** [comment]
应该是 REACT DevTools 引起的。
解决方法: 在 chorme 的扩展程序中，将 React DevTools 禁用或者删除掉。
