### ISSUE TITLE
【taroize】拼接的图片资源在转换过程中出现假性报错

### ISSUE THREAD

**Issue by Qiyu8** [NervJS/taro#4195]
问题描述
微信小程序js写法如下：
`let a = data.cdnUrl + '/static/webapp/images/audio.png'`
或者在wxml中写法如下：
`<image src="{{cdnurl + '/static/a.jpg'}}"></image>`
在taro convert的过程中会报错
错误  图片不存在 /static/webapp/images/audio.png
错误  图片不存在/static/a.jpg

复现步骤
1.在微信小程序根目录执行 taro convert

期望行为
转换不报错

报错信息
错误  图片不存在 /static/webapp/images/audio.png
错误  图片不存在/static/a.jpg

系统信息
操作系统: Windows 10
Taro 版本 v1.3.13
Node.js 版本 v12.7.0
报错平台 weapp
补充信息
优化点：区分拼接的图片和非拼接的图片，只判断非拼接图片且非URL图片的存在性，否则在富图片小程序的转换过程中会出现大量假性报错

**Comment by luckyadam** [comment]
会报错，但是还是能转换成功吧

**Comment by Qiyu8** [comment]
嗯，可以转换成功，作为强迫症晚期的程序猿正在修复这个问题

**Comment by Qiyu8** [comment]
@luckyadam 这个问题已经有实现方案了，我可以提个PR吗？
