### ISSUE TITLE
windows按照文档初始化支持ts的微信云模板项目时，编译失败找不到项目配置文件config/index.js

### ISSUE THREAD

**Issue by wsmhz** [NervJS/taro#4196]
**问题描述**
windows按照文档初始化支持ts的微信云模板项目时，编译失败！找不到项目配置文件config/index.js，请确定当前目录是Taro项目根目录!

**复现步骤**
[复现问题的步骤]
1.npm install -g @tarojs/cli
2.taro init myApp（选择ts跟wxcloud模板）
3.cd myApp/client
4.npm install (！！使用该微信云模板不会在新建初始化时自动安装依赖，需要切换到client目录运行npm install ！！)
4.npm run dev:weapp
run时编译报错
找不到项目配置文件config/index.js，请确定当前目录是Taro项目根目录!

**期望行为**
正常编译运行

**报错信息**
![image](https://user-images.githubusercontent.com/33542541/63205907-1fc83d00-c0de-11e9-9c97-2b11b6800d50.png)
![image](https://user-images.githubusercontent.com/33542541/63205922-5b630700-c0de-11e9-9fde-de0499a4e6dc.png)

！！使用该微信云模板不会在新建初始化时自动安装依赖，需要切换到client目录运行npm install ！！

**系统信息**
![image](https://user-images.githubusercontent.com/33542541/63206044-4edfae00-c0e0-11e9-92ad-42338dab272f.png)

操作系统: Windows 7
Taro 版本 v1.3.12
Node.js 版本 10.5.0
报错平台 weapp

**补充信息**
![image](https://user-images.githubusercontent.com/33542541/63205999-9ca7e680-c0df-11e9-9d13-f79455cc2f21.png)

感觉对于新接触的人不是特别友好，之前我也提过问题，也是初始化的时候存在的问题，总之，希望充分测试吧~~~

**Comment by Chen-jj** [comment]
@wsmhz 试试找到你 CLI 安装位置，然后在 taro-build 文件里的这里打个 log，看看 `projectConfPath` 取值是什么。

![image](https://user-images.githubusercontent.com/11807297/63208209-ddb1f200-c103-11e9-90f5-2cd295e3330a.png)

**Comment by wsmhz** [comment]
![image](https://user-images.githubusercontent.com/33542541/63233241-9b062c00-c261-11e9-8c19-4f6260c9391f.png)
其实这个报错是显而易见的，为何初始化时选择的是typescript，编译寻找的一直是.js类型？

**Comment by Chen-jj** [comment]
@wsmhz 先把 config 下的文件手动改回 .js 吧，应该是 windows 的路径处理有点问题。

**Comment by 121607691** [comment]
同样的问题，其他一致模板使用的vue3+nutui4，包管理用的npm，config目录下直接默认.js当还是提示

![image](https://user-images.githubusercontent.com/22384322/221781696-b1b413be-00ca-447d-bcf1-e4537c5cec22.png)，unplugin-vue-components 已经通过npm i unplugin-vue-components -D 命令安装过了，
![image](https://user-images.githubusercontent.com/22384322/221781956-e859031e-41e6-479b-9434-1744625cd36a.png)
