### ISSUE TITLE
小程序列表页加载会有超过最大长度 1048576

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#4198]
**问题描述**
第一次加载15条数据 然后在一直分页加载到很多条的时候没有问题，但是后退后，再进入该列表页时，还没请求列表数据 就直接出错了，改了很多写法，也没办法解决

**复现步骤**

**期望行为**
无报错

**报错信息**
数据传输长度为 1381850 已经超过最大长度 1048576

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.13]
 - Node.js 版本 [10.14.1]
 - 报错平台 [weapp]

**补充信息**
猜测是第二次进入的时候 带入了第一次请求的很多数据导致的

**Comment by Chen-jj** [comment]
@guggit 看看实际 setData 再作优化吧https://nervjs.github.io/taro/docs/debug.html#debug-diff

**Comment by guggit** [comment]
> @guggit 看看实际 setData 再作优化吧https://nervjs.github.io/taro/docs/debug.html#debug-diff

应该和我写的代码关系不大，不管我怎么优化肯定还有问题，我是正常分页，只要一直刷 数据量肯定会多，然后后退后在进入该页面才出错的

**Comment by Chen-jj** [comment]
Setdata看了吗

**Comment by guggit** [comment]
> Setdata看了吗

嗯 我发帖前就看了，调用次数太多 我也不确定是个setdata出错了

**Comment by guggit** [comment]
有办法确定数据量大小吗

**Comment by Chen-jj** [comment]
@guggit setData 你看不到数据量？

**Comment by ZakaryCode** [comment]
最大长度 1048576 是小程序本身的限制，通常可以从三个层面去解决:
1. 去掉不必要的字段，过滤掉无用参数;
2. 二维数组 参考微信小程序论坛方案 [invokeWebviewMethod 数据传输长度已经超过最大长度如何解决](https://developers.weixin.qq.com/community/develop/doc/000222e78f0d38e3552636d5056804);
3. 删除列表中不显示的数据（eg: 默认加载 10 页，显示第 11 页数据时，删除首页内容……）.
