### ISSUE TITLE
组件生命周期在小程序中是如何实现的

### ISSUE THREAD

**Issue by honchy** [NervJS/taro#42]
小程序的组件没有类似componentDidMount这样的生命周期。

那么，在小程序的场景下，这样的生命周期是什么样的触发逻辑呢？

**Comment by luckyadam** [comment]
我们组件化是自己实现的，没有用小程序组件那一套，所以生命周期都可以自定义咯~
而页面的生命周期有依赖与小程序页面生命周期，`componentDidMount ` 大致等价于小程序的 `onReady` 方法

**Comment by honchy** [comment]
@luckyadam 

不过在小程序里面运行的时候，什么时机触发的componentDidMount呢？因为小程序没有类似的时机可用，怎么知道已经插入到真实的 DOM，或者已经从 DOM 卸载掉呢？

**Comment by luckyadam** [comment]
@honchy  小程序页面有 `onReady` 方法的

**Comment by honchy** [comment]
@luckyadam   具体到组件呢，比如自定义了一个 Button 组件，Button 组件会有这些生命周期方法吗？

**Comment by luckyadam** [comment]
嗯嗯，有的，组件同样有生命周期~ 组件生命周期依赖于页面生命周期来实现~

**Comment by honchy** [comment]
cool

**Comment by farzer** [comment]
有个疑问是为什么把didshow放在didmount前执行？有个场景是当前业务只在挂载完成的时候执行一次，然后每次页面展示的时候执行另外的业务，即是

```js
componentDidMount() {
    // 只在第一次加载的时候执行
    checkLogin()
}
componentDidShow() {
    // 页面加载时候执行
    runDependenceLogin()
}
```
