### ISSUE TITLE
Taro.canvasToTempFilePath 问题

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#420]
v1.0.0-beta.5

```js
        wx.canvasToTempFilePath(
          {
            canvasId: 'canvas',
            success: res => {
              console.log(res)
            },
          },
          this.$scope,
        )

        const res = await Taro.canvasToTempFilePath(
          { canvasId: 'canvas' },
          this.$scope,
        )
```
结果：

![](https://ws3.sinaimg.cn/large/0069RVTdgy1ftvjzberiqj30ws06cgnw.jpg)

报错的是 `Taro.canvasToTempFilePath` 的结果，`wx.canvasToTempFilePath` 成功打印。

是不是第二个参数的问题？

[wx.canvasToTempFilePath(OBJECT, this)](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/temp-file.html)

**Comment by Harhao** [comment]
这个可以参考一下https://nervjs.github.io/taro/wx-relations.html

**Comment by Songkeys** [comment]
@Harhao 
谢谢。我知道这个，所以代码里写的就是 `this.$scope`。取到的都是自定义组件实例。两段代码应该是等价的，

**Comment by ttylikl** [comment]
在该API的文档页面里[](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/temp-file.html)，可以看到如下：

> Bug & Tip
tip: 在 draw 回调里调用该方法才能保证图片导出成功。

**Comment by ttylikl** [comment]
文档地址 https://developers.weixin.qq.com/miniprogram/dev/api/canvas/temp-file.html

**Comment by zcfan** [comment]
@Songkeys 我这没法复现，可以提供一个会出问题的仓库么

**Comment by STLighter** [comment]
@zcfan 这种是当canvas在一个自定义组件的时候会产生的，应该是这里只传了一个参数而没有传递额外的参数
https://github.com/NervJS/taro/blob/master/packages/taro-weapp/src/native-api.js#L69

**Comment by MaRuiL** [comment]
@zcfan 我也遇到了同样的问题，请问一下这个api问题什么时候能解决？@SongKeys 这个问题最终解决了吗？用什么办法解决的可否告诉下。。

**Comment by luckyadam** [comment]
现在最新版本还有这个问题么

**Comment by MaRuiL** [comment]
@luckyadam 请问是我更新的版本有问题吗？已经到最新的1.0.4了，急求解决办法

**Comment by Songkeys** [comment]
@MaRuiL 暂时用wx的方法替代了。

**Comment by shaodushu** [comment]
@luckyadam 请问这个问题解决了嘛，版本自从0.7.0升级到1.0.7，自定义组件使用canvas，在this.ctx.draw的回调使用Taro.canvasToTempFilePath，
![image](https://user-images.githubusercontent.com/26360246/46943554-76ba4b80-d0a2-11e8-9321-149c50577bc7.png)

**Comment by MaRuiL** [comment]
@shaodushu 感觉还没解决，直接调微信api解决

**Comment by shaodushu** [comment]
@MaRuiL 谢谢，我试过了，没出来。你有代码片段嘛？
