### ISSUE TITLE
h5 网页授权，路由守卫 怎么实现，请求一个思路

### ISSUE THREAD

**Issue by chenyinlong** [NervJS/taro#4202]
微信网页的授权及处理 ，需要路由守卫进行处理，请问有什么好的思路来实现嘛？

🙏🙏🙏

**Comment by luckyadam** [comment]
只能通过 componentDidShow 和 componentDidHide 两个生命周期来处理

**Comment by chenyinlong** [comment]
@luckyadam 就是通过类继承，每个页面都进行一次 授权验证，这样的操作吧

**Comment by nyrf** [comment]
我也在找，我发现uni有个https://github.com/SilurianYang/uni-simple-router这个，不过好像思路不适用taro，你看看

**Comment by chenyinlong** [comment]
@nyrf  谢谢，我这就去看看

**Comment by gaoxiaosong** [comment]
@chenyinlong 我正在用React的高阶组件做，然后需要授权的页面导出时套上高阶组件。。

**Comment by BurnhamZhang** [comment]
通过componentDidShow实现路由守卫体验太差了，页面都进去了，再守卫已经没意义了，通过一个代理页面判断好权限后再重定向到目标页面的体验才能好一些

**Comment by xiao252** [comment]
如果没有路由守卫那h5端页面权限那块该怎么处理呢？例如用户手动更改url地址 @BurnhamZhang @luckyadam

**Comment by ZakaryCode** [comment]
duplicate #7470
