### ISSUE TITLE
block标签

### ISSUE THREAD

**Issue by Surile** [NervJS/taro#4205]
微信小程序使用block标签时，会被识别为空，但在转换成H5时，则会被识别成div，如果使用flex布局的话，会影响布局。

**Comment by Surile** [comment]
期望在h5也能识别为空。

**Comment by luckyadam** [comment]
了解，只能尽快支持 React Fragment 了

**Comment by Surile** [comment]
了解。期待。

**Comment by Chen-jj** [comment]
Taro3 已支持 React Fragment
