### ISSUE TITLE
this.$router.params在页面关闭后, 里面的参数依然存在？BUG!!!

### ISSUE THREAD

**Issue by songming43** [NervJS/taro#4206]
**问题描述**
A页面为Tab页面，通过小程序码(携带了一个id参数)进入到A页面后，然后点击按钮通过reLaunch方法关闭所有页面，跳转到B页面(Tab页面)，再由B页面切换tab跳转到A页面，此时会发现this.$router.params中的id参数依然存在，为什么A页面关闭后，this.$router.params依然还在？
**复现步骤**
1. 通过小程序码扫码进入A页面(Tab页面)
    1）在A页面中解析小程序码中的id参数
    2）点击跳转，通过reLaunch跳转到B页面(A页面已关闭)
2. B页面中点击Tab跳转到A页面
    1）发现A页面中this.$router.parmas中的id参数依然存在？
注：仅ios设备中存在这个问题，android中不存在这个问题

**期望行为**
希望在A页面被关闭后，再次进入A页面，params重置

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Mac]
 - Taro 版本 1.2.21
 - Node.js 版本 [v11.4.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
#3846

**Comment by Chen-jj** [comment]
@songming43 估计 A 页面并没有被销毁，你在 componentWillUnmount 打个 log 就清楚了。

**Comment by songming43** [comment]
> @songming43 估计 A 页面并没有被销毁，你在 componentWillUnmount 打个 log 就清楚了。

在A页面的componentWillUnmount中 log，有打印，说明A页面确实是销毁了，但是在ios设备中再次进入A页面，this.$router.params是仍然有值的。这个问题只有在ios设备中有，在安卓设备上却是正常的，安卓设备上A页面销毁后，再次进入A页面，this.$router.params是没值的

**Comment by songming43** [comment]
> > @songming43 估计 A 页面并没有被销毁，你在 componentWillUnmount 打个 log 就清楚了。
> 
> 在A页面的componentWillUnmount中 log，有打印，说明A页面确实是销毁了，但是在ios设备中再次进入A页面，this.$router.params是仍然有值的。这个问题只有在ios设备中有，在安卓设备上却是正常的，安卓设备上A页面销毁后，再次进入A页面，this.$router.params是没值的

**Comment by songming43** [comment]
```
  componentWillMount = () =>{
    this.params = this.$router.params;
    console.log('componentWillMount',this.params);
  }
  componentWillUnmount = () => {
    this.params = {}
    console.log('componentWillUnmount',this.params);
  };
  componentDidMount = async () => {
     console.log('componentDidMount', this.params);
  }
```
这个我在A页面三个生命周期中写的代码，A页面销毁后触发componentWillUnmount清空this.params, 但是由于ios设备中存在问题，再次进入A页面后componentWillMount中this.$router.params依然有值, 就导致A页面中的params参数一直存在，导致业务错误

**Comment by songming43** [comment]
```
  componentWillMount = () =>{
    this.params = this.$router.params;
    console.log('componentWillMount',this.params);
  }
  componentWillUnmount = () => {
    this.params = {}
    console.log('componentWillUnmount',this.params);
  };
  componentDidMount = async () => {
     console.log('componentDidMount', this.params);
  }
```
这个我在A页面三个生命周期中写的代码，A页面销毁后触发componentWillUnmount清空this.params, 但是由于ios设备中存在问题，再次进入A页面后componentWillMount中this.$router.params依然有值, 就导致A页面中的params参数一直存在，导致业务错误

**Comment by songming43** [comment]
@Chen-jj

**Comment by songming43** [comment]
这个问题能帮忙先解决下吗？现在业务用到这块 ios设备中this.$router.params在页面卸载后依然没有清除, android设备上却是正常的 @Chen-jj

**Comment by Chen-jj** [comment]
@songming43 进入 dist/@tarojs/taro-weapp/dist/index.js ，搜索 "onLoad"，找到小程序的 onLoad 生命周期，打印其参数。看看是否销毁后，重新进入页面，页面 onLoad 触发时仍然有参。

**Comment by songming43** [comment]
> @songming43 进入 dist/@tarojs/taro-weapp/dist/index.js ，搜索 "onLoad"，找到小程序的 onLoad 生命周期，打印其参数。看看是否销毁后，重新进入页面，页面 onLoad 触发时仍然有参。

```
 weappComponentConf.methods['onLoad'] = function () {
      var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
      if (this.$component.__isReady) return;
      console.log('options',options)
      Object.assign(this.$component.$router.params, options);
      initComponent.apply(this, [ComponentClass, isPage]);
    };
```
在上述代码中打印options, 然后用ios,安卓两种设备进入小程序，发现页面销毁后，ios依然有参，安卓设备没有。
[
![WechatIMG359](https://user-images.githubusercontent.com/25769573/63420191-c98a2f80-c438-11e9-9e98-0ac3e636ba9d.jpeg)
![WechatIMG26](https://user-images.githubusercontent.com/25769573/63420205-ce4ee380-c438-11e9-8c06-21aad3d17eef.jpeg)

](url)

**Comment by Chen-jj** [comment]
@songming43 那就是小程序的问题咯，taro 只是把 onLoad 拿到的 options 挂在 this.$router 而已，建议自行写判断绕过。

**Comment by songming43** [comment]
> @songming43 那就是小程序的问题咯，taro 只是把 onLoad 拿到的 options 挂在 this.$router 而已，建议自行写判断绕过。

我在原生小程序上写了个demo，页面卸载后再次进入页面options的值不存在，ios和android均正常符合预期，但是在taro上ios是不正确的 @Chen-jj

**Comment by songming43** [comment]
> > @songming43 那就是小程序的问题咯，taro 只是把 onLoad 拿到的 options 挂在 this.$router 而已，建议自行写判断绕过。
> 
> 我在原生小程序上写了个demo，页面卸载后再次进入页面options的值不存在，ios和android均正常符合预期，但是在taro上ios是不正确的，是不是因为taro的componentWillUnmount方法虽然有触发，但实际上页面并未卸载？componentWillUnmount是和原生小程序的onUnload对应吗？

**Comment by Chen-jj** [comment]
@songming43 一样的，代码搜 onUnload 就能看到。原生没复现感觉是模拟的情况不够准确。你也在 onLoad 打过 log 了，的确有 options，onLoad 是小程序触发的，它带参了 Taro 就会赋值给 this.$router

**Comment by songming43** [comment]
> @songming43 一样的，代码搜 onUnload 就能看到。原生没复现感觉是模拟的情况不够准确。你也在 onLoad 打过 log 了，的确有 options，onLoad 是小程序触发的，它带参了 Taro 就会赋值给 this.$router

在dist文件下全局搜索并没有找到onUnload, onUnload是在放在哪里了呢？@Chen-jj
![WX20190823-111014](https://user-images.githubusercontent.com/25769573/63564217-ca38d800-c596-11e9-8441-a266eb2a21fe.png)
![WX20190823-111035](https://user-images.githubusercontent.com/25769573/63564220-cdcc5f00-c596-11e9-9346-4112bcb93cbc.png)

**Comment by Chen-jj** [comment]
@songming43 搜一下 detached，Taro 在微信小程序里页面也是使用 Component 构建的，因此触发的是 Component 的生命周期

**Comment by songming43** [comment]
> @songming43 搜一下 detached，Taro 在微信小程序里页面也是使用 Component 构建的，因此触发的是 Component 的生命周期

我在detached方法中打印this.$component, 说明这个页面已经销毁了吧? this.$router.params在ios设备上却没有销毁，再次进入这个页面后 this.$router.params依然有值。是不是Component构建的页面在detached方法中并没有销毁页面？没有重置options?
![WX20190823-113146](https://user-images.githubusercontent.com/25769573/63565412-6ebd1900-c59b-11e9-983a-f477531ec505.png)
<img width="387" alt="WX20190823-113133@2x" src="https://user-images.githubusercontent.com/25769573/63565416-7381cd00-c59b-11e9-9780-5ff277150687.png">

**Comment by Chen-jj** [comment]
@songming43 销毁是小程序做的，你也看到 onLoad 有 options 了，onLoad 是小程序触发的，不是 Taro 的问题。
