### ISSUE TITLE
我在用taro init项目的时候

### ISSUE THREAD

**Issue by xiaoningzihai** [NervJS/taro#4207]
Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

(node:1100) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@tarojs/cli/templates/taro-temp'
(node:1100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by luckyadam** [comment]
权限问题，你可以用 `sudo taro init` 来解决
不过建议用 `nvm` 等 node 管理工具来管理 node 版本，这样就不会有权限问题

**Comment by xiaoningzihai** [comment]
但是这样的话每次删文件就得通过sudo删除，最后我通过npx解决了，谢谢。我感觉/usr/local/lib/node_modules/@tarojs/cli/templates/taro-temp也就是模版的copy放在全局感觉用起来有点尴尬。

**Comment by luckyadam** [comment]
对，正在考虑换一个地方存放模板

**Comment by xiaoningzihai** [comment]
感谢大佬答复，很喜欢凹凸实验室的东西

**Comment by luckyadam** [comment]
😆

**Comment by rabbit77** [comment]
> 但是这样的话每次删文件就得通过sudo删除，最后我通过npx解决了，谢谢。我感觉/usr/local/lib/node_modules/@tarojs/cli/templates/taro-temp也就是模版的copy放在全局感觉用起来有点尴尬。

麻烦问下是怎么通过npx解决的吗
