### ISSUE TITLE
微信小程序 地图功能 moveToLocation BUG!!

### ISSUE THREAD

**Issue by chm2211912096** [NervJS/taro#4208]
**问题描述**
微信小程序 map组件中执行 mapContext.moveToLocation, 什么回调方法都没有执行

**复现步骤**
[复现问题的步骤]
1. 缩放地图
2. 拖动地图
3. 点击位置按钮回到定位位置
4. moveToLocation执行，但是success, fail, complete回调方法都没有执行

```js
// 获取地图上下文
componentDidMount() {
    this['map'] = Taro.createMapContext('map');
}

// 移动地图
componentDidShow() {
     this.getUserLocation();
}

// 方法    **此时 this['map']已经赋值完成**
getUserLocation() {
    Taro.getLocation({
	type: 'gcj02'
    }).then(({latitude, longitude}) => {
	this['map'].moveToLocation({
    	    success() {
		console.log('success');
	    },
	    fail() {
	         console.log('fail');
	    },
	    complete() {
		console.log('complete');
	    }
	});
    }).catch(() => {
	toast('获取位置失败');
    })
}

```

**期望行为**
要么打印 success, complete
要么打印 fail, complete

**报错信息**
没有报错，地图移动正常

**系统信息**
 - 操作系统: [macOS High Sierra v10.13.6]
 - Taro 版本 [v1.3.2]
 - Node.js 版本 [v12.6.0]
 - Typescript版本 [v3.2.2]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@chm2211912096 https://developers.weixin.qq.com/community/develop/doc/00044e591c8398dce8c8793635b814?highLine=moveToLocation

基础库调到 2.8.0
