### ISSUE TITLE
Taro里加了dva，在三级页面里往redux里更新状态，在回调里跳回二级页面，要几十秒才能响应到值。

### ISSUE THREAD

**Issue by gaoshuzhen** [NervJS/taro#4211]
**系统信息**
 - 手机型号：华为荣耀8
 - 操作系统: [安卓8.0.0]
 - Taro 版本 [Taro v 1.3.13]
 - Node.js 版本 [node -v 10.16.0]
 - 报错平台 [alipay]

**补充信息**
在三级页面往redux里更新状态，在更新成功的回调里跳回二级页面，在二级页面获取刚刚更新的状态值，要几十秒才能拿到。

**Comment by Chen-jj** [comment]
@gaoshuzhen 只有问题没有代码，别人怎么帮你呢
