### ISSUE TITLE
设备方向

### ISSUE THREAD

**Issue by gitdust** [NervJS/taro#4213]
**问题描述**
设备方向的的三个接口没有封装
onDeviceMotionChange、startDeviceMotionListening、stopDeviceMotionListening

**Comment by Pines-Cheng** [comment]
哪个端？

**Comment by gitdust** [comment]
> 哪个端？

微信小程序，在 [index.d.ts](https://github.com/NervJS/taro/blob/master/packages/taro/types/index.d.ts)  中没有声明这三个 API
