### ISSUE TITLE
Swiper组件在H5端无法正常实现循环轮播功能

### ISSUE THREAD

**Issue by dq77** [NervJS/taro#4214]
**问题描述**

swiper组件适配了微信小程序和支付宝小程序，但在H5模式下无法循环轮播（播到最后一张图片以后无法在自动回到第一张继续播）

**复现步骤**

1. 打开官方文档的swiper组件页面（https://taro-ui.jd.com/#/docs/swiper），使用手机自带浏览器扫码（在页面右上角）
2. 打开”自动播放“选项和”循环播放“选项
3. 即可看到轮播图在轮播到最后一张图以后就定住了，无法回到第一张继续轮播（仅H5端能复现，小程序端此组件无BUG）
4. 官方文档的代码已经可以复现BUG，我就不贴代码了。

```js
// 这里可以贴代码
```

**期望行为**

期望H5端能够和小程序端一样，能够实现循环播放轮播

**报错信息**

无报错

**系统信息**

👽 Taro v1.2.26

  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.26 => 1.2.26 
      @tarojs/components: 1.2.26 => 1.2.26 
      @tarojs/plugin-babel: 1.2.26 => 1.2.26 
      @tarojs/plugin-csso: 1.2.26 => 1.2.26 
      @tarojs/plugin-sass: 1.2.26 => 1.2.26 
      @tarojs/plugin-uglifyjs: 1.2.26 => 1.2.26 
      @tarojs/redux: 1.2.26 => 1.2.26 
      @tarojs/redux-h5: 1.2.26 => 1.2.26 
      @tarojs/rn-runner: 1.2.26 => 1.2.26 
      @tarojs/router: 1.2.26 => 1.2.26 
      @tarojs/taro: 1.2.26 => 1.2.26 
      @tarojs/taro-alipay: 1.2.26 => 1.2.26 
      @tarojs/taro-h5: 1.2.26 => 1.2.26 
      @tarojs/taro-swan: 1.2.26 => 1.2.26 
      @tarojs/taro-tt: 1.2.26 => 1.2.26 
      @tarojs/taro-weapp: 1.2.26 => 1.2.26 
      @tarojs/webpack-runner: ^1.2.26 => 1.2.26 
      eslint-config-taro: 1.2.26 => 1.2.26 
      eslint-plugin-taro: 1.2.26 => 1.2.26 
      nervjs: ^1.3.0 => 1.3.13 

**补充信息**

这个我真不知道

**Comment by dq77** [comment]
或者把官方文档的代码放在VScode里 然后 npm run dev:h5 ，也可以在谷歌浏览器复现此BUG。

**Comment by luckyadam** [comment]
升级到最新版本试试

**Comment by jinjinjin0731** [comment]
这个已经修复过了。 升级到最新吧

**Comment by dq77** [comment]
我按照 luckyadam 说的，更新了@tarojs/components 这个包。目前1.3.14版本已经修复了这个BUG，亲测1.3.10还没修复呢，有用1.3.10版本之前的同学更新到1.3.14之后就好了。问题关闭。

**Comment by CherishLyf** [comment]
1.3.19 这个BUG 又存在了..

**Comment by xahy123** [comment]
我这2.2.6都存在了
