### ISSUE TITLE
组件使用render传入整个组件，会多出来一层view，导致flex布局失效

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#4223]
我只整个组件传入的。
![微信图片_20190820151221](https://user-images.githubusercontent.com/31879769/63325550-f5d07e00-c35c-11e9-825f-6a8fc2de266c.png)
![微信图片_20190820151230](https://user-images.githubusercontent.com/31879769/63325551-f6691480-c35c-11e9-87ab-a123be9d3e8f.png)

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
