### ISSUE TITLE
taro支付宝端编译小程序代码头部无法自定义

### ISSUE THREAD

**Issue by JockSisca** [NervJS/taro#4225]
**问题描述**
[问题描述：taro双端编译小程序代码头部无法自定义]

**复现步骤**

taro编译在app.tsx的config使用自定义头部且页面单独的config中也写入自定义头部支付宝端头部依旧存在微信不存在

index.tsx:
```
config: Config = Taro.getEnv() == 'ALIPAY' ? {  

 navigationBarTitleText: '',

 navigationStyle: "custom"

,transparentTitle: 'YES'

 } : {

 navigationBarTitleText: '',

 navigationStyle: "custom",

enablePullDownRefresh: false

  };

```
app.tsx:
```
  config: Config = {

    pages: [

      'pages/index/index'

    ],

    window: {

      navigationStyle: "custom"

    },

  }
```

**期望行为**
1.允许写入单独的JSON配置
2.修复双端不兼容

**报错信息**

[未报错]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.14]
 - Node.js 版本 [e.g. v11.8.0]
 - 报错平台 [alipay]

**补充信息**
暂无

**Comment by luckyadam** [comment]
支付宝小程序不支持 `navigationStyle: "custom"` 这个配置
