### ISSUE TITLE
H5 getCurrentPages返回的page不符合预期

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#4228]
**问题描述**
[问题描述：H5 getCurrentPages返回的page不符合预期]

**复现步骤**
[复现问题的步骤]
1.A页面 navigateTo B页面，在B页面打印，两个page打印出来的path都是B页面

```js
  const pages = Taro.getCurrentPages().filter(page => !!page);
  pages.forEach((page, i) => {
    console.log(i, page.$component.$router);
  });

```

**期望行为**
打印结果对应页面的路径
**报错信息**
![image](https://user-images.githubusercontent.com/5822190/63334682-7c418b80-c36e-11e9-8462-f41ff5a39d27.png)

**系统信息**

 - 操作系统: [macOS 10.14.6]
 - Taro 版本 [1.3.13]
 - Node.js 版本 [10.14.6]
 - 报错平台 [h5]

**Comment by PlutoCA** [comment]
![image](https://user-images.githubusercontent.com/31099607/63634239-35150c80-c686-11e9-95e1-d0221a62af7d.png)
h5 用这个还挺多问题的，有时返回页面 路由栈还会添加null进去
