### ISSUE TITLE
taro组件增加的classname编译后没有生成css

### ISSUE THREAD

**Issue by Mulberry-Leaf** [NervJS/taro#4229]
**问题描述**
taro组件增加的classname编译后没有生成css

**复现步骤**
[复现问题的步骤]
1. 新增一个页面添加，页面内容如searchIndex.js

```
// searchIndex.js
import { ComponentClass } from 'react'
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Input, Button, Icon } from '@tarojs/components'

import './index.less'
// import { connect } from '@tarojs/redux';

type PageOwnProps = {}

type PageState = {}

type IProps = PageOwnProps

interface SearchIndex {
  props: IProps;
}

// @connect()
class SearchIndex extends Component {
  config: Config = {
    navigationBarTitleText: '商品搜索'
  }

	render() {
		return (
			<View className='searchIndex'>
        <div className='ceshi'>测试css</div>
        <View className='searchwarp'>
          <Input className='searchIn' type='text' placeholder='请输入商品信息' />
          <Button className='searchBtn' plain type='primary'>搜索</Button>
          <Icon size='60' type='success' />
        </View>
      </View>
		)
	}
}

export default SearchIndex as ComponentClass<PageOwnProps, PageState>
```

```
// searchIndex.less
.searchIndex {
  flex-direction: column;
  position: relative;
  width: 100%;
  .ceshi {
    background-color: #3385ff;
    color: #fff
  }
  .searchwarp {
    flex-direction: column;
    position: absolute;
    left: 50%;
    top: 50%;
    .searchIn {
      width: 220px;
    }
    .searchBtn {
      width: 70px;
      background-color: #3385ff;
      color: #fff;
    }
  }
}

```

**期望行为**
1、能正常编译出css
2、用dev添加className就能正常生成class并且css有效果，期望taro组件添加className 后也能正常有css效果
3、searchwarp 这个css 的left: 50%, top: 50% ,也均不生效，背景必须写成 background-color 才生效，直接写background 无效，希望有相关的文档说明，提供哪些属性有用

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/38044924/63337182-1b688200-c373-11e9-8900-6513ce292afc.png)

**Comment by jinjinjin0731** [comment]
经过测试， 是由于快应用自定义组件时， 接受的外部样式名需要指定为  class  。新版会修复这个问题

**Comment by Mulberry-Leaf** [comment]
> 经过测试， 是由于快应用自定义组件时， 接受的外部样式名需要指定为 class 。新版会修复这个问题

这么写的话<View class="test">aa</View>会报下面的类型错误提示：

不能将类型“{ children: string; class: string; }”分配给类型“IntrinsicAttributes & ViewProps & { children?: ReactNode; }”。
  类型“IntrinsicAttributes & ViewProps & { children?: ReactNode; }”上不存在属性“class”。ts(2322)

**Comment by Mulberry-Leaf** [comment]
> 经过测试， 是由于快应用自定义组件时， 接受的外部样式名需要指定为 class 。新版会修复这个问题

<Button class='searchBtn'> 不支持

**Comment by Mulberry-Leaf** [comment]
> 经过测试， 是由于快应用自定义组件时， 接受的外部样式名需要指定为 class 。新版会修复这个问题

```
<Button class='searchBtn'></Button>
```
这个组件不支持这种写法
