### ISSUE TITLE
Taro 不能识别 npm 作用域包导致重复安装依赖

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#423]
**问题描述**
Taro 不能识别 npm 作用域包导致重复安装依赖，一直在重复安装，跟死循环一样。

**复现步骤**
1. 安装了一个带有作用域的包（`@scope/example`形式）
2. 在代码中引用这个包（`import example from '@scope/example'`）
3. 运行 `dev:weapp`
4. 终端提示`缺少npm包@scope/example，开始安装...`

**期望行为**
不出现重复安装

**报错信息**

```bash
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
缺少npm包@kc/taro-ajax，开始安装...
...
...
...
```

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v0.0.73
 - Node.js 版本 v8.11.2

**补充信息**
应该是 Taro 没有对这个格式的包做兼容导致的。

**Comment by kid1412621** [comment]
额，9102年了，现在还没解决？taro , npm 均为最新版 ，ubuntu。

**Comment by nevernet** [comment]
还没修复的。。。

**Comment by nevernet** [comment]
临时解决办法，把@scope/exmaple配置到别名里面

**Comment by z-Listening** [comment]
closed了，是已经修复了吗？表示还是遇到了import之后，报缺少包，开始安装......这个现象

**Comment by nevernet** [comment]
@z-Listening 已经修复的。 升级到最新版本
