### ISSUE TITLE
官方文档GETTING-STARTED.md有重复内容！

### ISSUE THREAD

**Issue by EdisonVan** [NervJS/taro#4230]
**问题描述**
[问题描述：官方文档GETTING-STARTED.md有重复内容！]

下面这段注意事项在文档中重复出现了2次！
```
注意事项
值得一提的是，如果安装过程出现sass相关的安装错误，请在安装mirror-config-china后重试。
$ npm install -g mirror-config-china
```

**期望行为**
[删除一段重复内容吧！]

**报错信息**
![image](https://user-images.githubusercontent.com/38999461/63345563-9a66b600-c385-11e9-8805-03560bf4f6fb.png)

**Comment by new9xgh** [comment]
其实是有区别的，一个是【值得一提】另一个是【值得一提再提】。可以理解为，起到再次提醒的作用吧。

第一段：
![image](https://user-images.githubusercontent.com/5210026/63356870-17505a80-c39b-11e9-86d4-a8e3639563ff.png)

第二段：
![image](https://user-images.githubusercontent.com/5210026/63356823-07387b00-c39b-11e9-8c38-97bc1b817b23.png)

**Comment by luckyadam** [comment]
可以提个 pr 来修一下咯

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/63563871-3a465e80-c595-11e9-87f8-74a24d0f96b2.png)
直接修改提交。
