### ISSUE TITLE
微信小程序插件引用图片路径编译报错

### ISSUE THREAD

**Issue by IDrinkMoreWater** [NervJS/taro#4231]
**问题描述**
微信小程序插件引用图片路径编译报错

**复现步骤**
[复现问题的步骤]
1. taro init 初始化微信小程序插件项目
2. 页面插件src/plugin/pages/list目录下新增images文件夹
3. 修改 list路径下list.tsx页面代码，添加引用images下的图片代码，如**navigationIcon ，searchIcon** 
```
import Taro, { Component } from '@tarojs/taro'
import { View, Image } from '@tarojs/components';
import ListItem from '../../components/listItem/listItem'
import './list.less'
import navigationIcon from './images/navigation.png';
import searchIcon from './images/icon_search.png';
export default class Index extends Component {
  state = {
    list: [{
      name: 'A',
      value: '1'
    }, {
      name: 'B',
      value: '2'
    }, {
      name: 'C',
      value: '3'
    }]
  }

  render () {
    return (
      <View>
	    <Image src={navigationIcon}/>
	   <Image src={searchIcon}/>
        {this.state.list.map(item => {
          return <ListItem name={item.name} value={item.value} key={item.name} />
        })}
      </View>
    )
  }
}
```

**期望行为**
页面正常编译正常引用图片

**报错信息**
![image](https://user-images.githubusercontent.com/13063062/63365849-04de1d00-c3ab-11e9-9df7-40e0f6d60136.png)

完整错误信息：
(node:9132) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'D:\Document
s\Desktop\plugin\miniprogram\plugin\pages\list\images'
(node:9132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eit
her by throwing inside of an async function without a catch block, or by rejecting a promise which w
as not handled with .catch(). (rejection id: 1)
(node:9132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future
, promise rejections that are not handled will terminate the Node.js process with a non-zero exit co
de.

**系统信息**
 Taro CLI 1.3.11 environment info:
   System:
     OS: Windows 7
   Binaries:
     Node: 8.11.2 - C:\Program Files (x86)\nodejs\node.EXE
     npm: 5.6.0 - C:\Program Files (x86)\nodejs\npm.CMD
 - 报错平台 [ weapp-plugin]

其他重要补充信息：
**以上示例代码，发现只import引用1张图片时不会报错，2张或2张以上时才会发现报错**

**Comment by IDrinkMoreWater** [comment]
问题没解决，还有其他问题，dev:weapp 编译现在是首次编译不会报错，但是改动文件后自动编译的还会报错
![微信图片_20190829170115](https://user-images.githubusercontent.com/13063062/63926736-eb119980-ca7e-11e9-9cc1-cf914c3e5d78.png)
build:weapp下编译不会报错，运行后会报错
![image](https://user-images.githubusercontent.com/13063062/63927026-7c810b80-ca7f-11e9-84df-23604a583ef3.png)

**Comment by Chen-jj** [comment]
@IDrinkMoreWater 复现不了，修改后并没有报错

![image](https://user-images.githubusercontent.com/11807297/64157497-6604f680-ce69-11e9-8ffc-1665909029c6.png)

![image](https://user-images.githubusercontent.com/11807297/64157675-b4b29080-ce69-11e9-8828-f01c80d1af43.png)

**Comment by IDrinkMoreWater** [comment]
@Chen-jj 你是用jsx编译的所以正常，init项目的时候选择typescript就能重现了，应该是这个原型，我用脚手架从新初始化新的项目是可以重现的

**Comment by Chen-jj** [comment]
@IDrinkMoreWater 是不是用错命令，应该是 `taro build --plugin weapp --watch`

**Comment by IDrinkMoreWater** [comment]
@Chen-jj 嘉健兄能加微信聊么，确实没用错命令啊，我用taro build --plugin weapp --watch不报错， taro build --plugin weapp才报错哦
