### ISSUE TITLE
使用if进行环境变量判断来得到jsx出现问题

### ISSUE THREAD

**Issue by cloudZQY** [NervJS/taro#4233]
**问题描述**
使用if判断环境变量，return到一段jsx，编译出来有问题

**复现步骤**
[复现问题的步骤]
```js
if (process.env.TARO_ENV === 'weapp') {
  return <View>weapp</View>
}
return <View>其他</View>
```
以上代码在其他app中正常，在微信中会编译成
```js
<View>weapp</View>
<View>其他</View>
```

改成如下代码后ok
```js
if (process.env.TARO_ENV === 'weapp') {
  return <View>weapp</View>
} else {
  return <View>其他</View>
}
```

**期望行为**
使用上述写法也能得到预期的编译，或者在文档最佳实践中标明。

**报错信息**

**系统信息**
 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.3.11]
 - Node.js 版本 [e.g. v8.9.4]
 - 报错平台 [weapp]

**补充信息**

**Comment by Chen-jj** [comment]
Taro3 可以支持这种中途 return 的语法了
