### ISSUE TITLE
weapp-升级到Taro1.3后自定义组件设置style样式无效

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro#4234]
**问题描述**
升级到Taro1.3后自定义组件设置`style`样式无效

**复现步骤**
[复现问题的步骤]

```js
              <SearchbarView
                focus={false}
                style='display: flex;flex:1;'
                onSearchClick={this.onSearchClick}
                searchToken={searchToken}
                searchImg={searchImg}
                placeholder='搜索你想要的宝贝吧~'
                backgroundColor='#ffffff'
                textColor='#9B9B9B'
                onFocus={this.onSearchFocus}
                inputDisabled
                onSearchViewClick={this.onSearchFocus}
              />

```
SearchbarView 是自定义组件,`style='display: flex;flex:1;'`设置的样式不生效，1.2.6是好的

**期望行为**
自定义组件style设置的样式生效

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
 - 报错平台 [ weapp]

 Taro CLI 1.3.14 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.14 => 1.3.14 
      @tarojs/cli: 1.3.14 => 1.3.14 
      @tarojs/components: 1.3.14 => 1.3.14 
      @tarojs/plugin-babel: 1.3.14 => 1.3.14 
      @tarojs/plugin-csso: 1.3.14 => 1.3.14 
      @tarojs/plugin-sass: 1.3.14 => 1.3.14 
      @tarojs/plugin-uglifyjs: 1.3.14 => 1.3.14 
      @tarojs/redux: 1.3.14 => 1.3.14 
      @tarojs/redux-h5: 1.3.14 => 1.3.14 
      @tarojs/router: 1.3.14 => 1.3.14 
      @tarojs/taro: 1.3.14 => 1.3.14 
      @tarojs/taro-alipay: 1.3.14 => 1.3.14 
      @tarojs/taro-h5: 1.3.14 => 1.3.14 
      @tarojs/taro-swan: 1.3.14 => 1.3.14 
      @tarojs/taro-weapp: 1.3.14 => 1.3.14 
      @tarojs/webpack-runner: 1.3.14 => 1.3.14 
      eslint-config-taro: 1.3.14 => 1.3.14 
      eslint-plugin-taro: 1.3.14 => 1.3.14 
      nervjs: ^1.4.4 => 1.4.4 
    npmGlobalPackages:
      typescript: 3.5.3

**补充信息**
用微信开发者工具调试，发现element.style没有设置样式

**Comment by Chen-jj** [comment]
@GaoYuJian React 中本不能这样用，taro 1.3 的表现才是正确的。你只是相当于给自定义组件传递 名为 style 的 props 而已。
