### ISSUE TITLE
以 render 开头的 props 只能传入包含一个 JSX 元素的 JSX 表达式。

### ISSUE THREAD

**Issue by gaoshanshanshan** [NervJS/taro#4237]
**问题描述**
以 render 开头的 props 只能传入包含一个 JSX 元素的 JSX 表达式。

**复现步骤**
[复现问题的步骤]
taro升级1.3.14后运行项目

```js

 <CPage
                    api={getMsgList}
                    initGetListDataCallBack={callback => this._callbackGetList = callback}
                    renderPage={data => {
                        return (
                           <View>test renderProps</View>
                        )
                    }}
  />

CPage 的 render 方法

render() {
        const { loadMoreStatus, page, showNoMore } = this.state
        const { renderPage } = this.props
        console.log('renderPage ', this.state)
        return (
            <View className="page-container">
                {
                    renderPage(this.state)
                }
                {
                    showNoMore && page > 1 &&
                    <AtLoadMore
                        status={loadMoreStatus}
                        moreText="下拉加载更多"
                        loadingText="努力加载中"
                        noMoreText="没有更多啦"
                        onClick={this.noneFun}
                    />
                }
            </View>
        )
    }

```

**期望行为**
使用renderProps，不会有如下报错

**报错信息**

![image](https://user-images.githubusercontent.com/30390622/63400376-26202700-c406-11e9-953c-78d27761694e.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro CLI 1.3.14 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      npm: 6.10.1 - ~/.nvm/npm/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.14 => 1.3.14
      @tarojs/components: 1.3.14 => 1.3.14
      @tarojs/mobx: 1.3.14 => 1.3.14
      @tarojs/mobx-h5: 1.3.14 => 1.3.14
      @tarojs/mobx-rn: 1.3.14 => 1.3.14
      @tarojs/plugin-babel: 1.3.14 => 1.3.14
      @tarojs/plugin-csso: 1.3.14 => 1.3.14
      @tarojs/plugin-sass: 1.3.14 => 1.3.14
      @tarojs/plugin-uglifyjs: 1.3.14 => 1.3.14
      @tarojs/rn-runner: 1.3.14 => 1.3.14
      @tarojs/router: 1.3.14 => 1.3.14
      @tarojs/taro: 1.3.14 => 1.3.14
      @tarojs/taro-alipay: 1.3.14 => 1.3.14
      @tarojs/taro-h5: 1.3.14 => 1.3.14
      @tarojs/taro-swan: 1.3.14 => 1.3.14
      @tarojs/taro-tt: 1.3.14 => 1.3.14
      @tarojs/taro-weapp: 1.3.14 => 1.3.14
      @tarojs/webpack-runner: 1.3.14 => 1.3.14
      eslint-config-taro: 1.3.14 => 1.3.14
      eslint-plugin-taro: 1.3.14 => 1.3.14
      nerv-devtools: ^1.4.4 => 1.4.4
      nervjs: ^1.4.4 => 1.4.4
      stylelint-config-taro-rn: 1.3.14 => 1.3.14
      stylelint-taro-rn: 1.3.14 => 1.3.14

**补充信息**

**Comment by gaoshanshanshan** [comment]
将@tarojs/cli降级到v1.3.13 就不会再报错

**Comment by georgezouq** [comment]
新版本里同样的问题 有没有除了降级的解决方案？
