### ISSUE TITLE
微信小程序 获取用户手机号

### ISSUE THREAD

**Issue by Rxiaoyi** [NervJS/taro#4238]
微信小程序 获取用户手机号，第一次总会解密失败，第二次就好了，当我退出，再次登录后，又解密失败，刷新后再次登录又可以登录了，请问这是什么原因呢？
`
//小程序端代码
Taro.login({
            success(res) {
               if (res.code) {
                  //发起网络请求
                  Taro.request({
                     url: '',
                     method: 'GET',
                  }).then(resx => {
                     if (resx) {
                        Taro.request({
                           url: '',
                           data: {
                              encryptedData: encryptedData,
                              iv: iv,
                              sessionKey: resx.data.session_key,
                           },
                           method: 'GET',
                        }).then(res => {
                           console.log(res, '获取用户手机号码');
                        })
                     }
                  })
               }
            }
         });`
`
![CF524C43-ABBB-42D9-8E7E-8DC6C93C59B1](https://user-images.githubusercontent.com/38679132/63401823-528a7200-c40b-11e9-81e0-235417f4be83.png)

//后端代码，这里是调用的微信提供的方法来解密数据
getPhoneNumber : async (req, res) => {
      let appId = '';
      let sessionKey = req.query.sessionKey;
      let encryptedData = req.query.encryptedData;
      let iv = req.query.iv;
      let pc = new WXBizDataCrypt(appId, sessionKey);
      let data = pc.decryptData(encryptedData, iv);
      return await data;
   },

![AF970CCE-9ED8-4D1C-932E-4FC54212458E](https://user-images.githubusercontent.com/38679132/63401847-69c95f80-c40b-11e9-9504-9750e7b5a1fa.png)

这是微信提供的解密方法
![image](https://user-images.githubusercontent.com/38679132/63401720-ead42700-c40a-11e9-85c1-43d4c29e4d80.png)

**Comment by cloudZQY** [comment]
这个跟Taro无关，是微信小程序的问题。
微信的加密数据，是1. 你先登录，微信生成`session_key`给你  2.你调用获取手机号的api，这时候会微信会根据上次登录获得的session_key加密好手机号给你，你再用手上的session_key解密。
上述顺序错了，你手里的session_key和微信加密用的session_key就不是一个，解密会失败。

**Comment by Rxiaoyi** [comment]
> 这个跟太郎无关，是微信小程序的问题。
> 微信的加密数据，是1。你先登录，微信生成`session_key`给你2.你调用获取手机号的api，这时候会微信会根据上次登录获得的session_key加密好手机号给你，你再用手上的session_key解密。
> 上述顺序错了，你手里的session_key可以和微信加密用的session_key可以就不是一个，解密会失败。

我现在就是先登录，然后去获取手机号码，再用登录过后得到的session_key和获取手机号码返回的数据去后台解密的。

**Comment by cloudZQY** [comment]
> 手机

根据你的代码，我没有看到你何时获取的iv和encryptedData，应该是在登录之前就获取了。请问是修过过后再试的吗？

**Comment by Garfield550** [comment]
```tsx
<Button
  type='primary'
  lang='zh_CN'
  openType='getPhoneNumber'
  onGetPhoneNumber={this.onGetPhoneNumber.bind(this)}>
  第二步，授权手机号
</Button>
```

onGetPhoneNumber 事件永远发生在 Taro.login 之前，
尝试在按钮获取加密数据之前调用 Taro.login

**Comment by Rxiaoyi** [comment]
> ```tsx
> < 按钮
>   类型= '初级'
>   郎= ' zh_CN的'
>   的openType = ' getPhoneNumber '
>    onGetPhoneNumber = { 此。onGetPhoneNumber。bind（this）} >
>   第二步，授权手机号
> </ Button >
> ```
> 
> onGetPhoneNumber事件永远发生在Taro.login之前，尝试
> 在按钮获取加密数据之前调用Taro.login

原本我是在每次app.js中用的Taro.login,然后把openid存到了缓存中，在用的时候从缓存中取，请问一下，这种方法可行吗？

**Comment by Rxiaoyi** [comment]
> > 手机
> 
> 根据你的代码，我没有看到你何时获取的静脉和的EncryptedData，应该是在登录之前就获取了。请问是修过过后再试的吗？

![image](https://user-images.githubusercontent.com/38679132/63660183-e1223900-c7e7-11e9-935f-1ce7540fe572.png)
获取那两个参数是我在点击获取用户手机号码去获取到的

**Comment by Garfield550** [comment]
> > ```tsx
> > < 按钮
> >   类型= '初级'
> >   郎= ' zh_CN的'
> >   的openType = ' getPhoneNumber '
> >    onGetPhoneNumber = { 此。onGetPhoneNumber。bind（this）} >
> >   第二步，授权手机号
> > </ Button >
> > ```
> > 
> > 
> > onGetPhoneNumber事件永远发生在Taro.login之前，尝试
> > 在按钮获取加密数据之前调用Taro.login
> 
> 原本我是在每次app.js中用的Taro.login,然后把openid存到了缓存中，在用的时候从缓存中取，请问一下，这种方法可行吗？

Taro.login 获得的是 Code 不是 OpenId。

Code 有五分钟过期时间。

Code 需要给后端解密出 SessionKey。

SessionKey 可以解密 iv 和 encryptedData。

**Comment by Rxiaoyi** [comment]
嗯嗯，我就是想在每次进入小程序的时候就调用Taro.login获取code然后去后端解密openID，然后存在缓存里。在用的时候去缓存中取，大佬，你看我说的这种方式可以用吗？

**Comment by Garfield550** [comment]
App.onLoad(): void => Taro.login(): Code => Taro.request('/backend/login', Code): { Seccess, openId } => ... => Page.Button.onGetPhoneNumber: EncData => Taro.request('/backend/phone', EncData): PhoneNumber => console.log(PhoneNumber): void

**Comment by Rxiaoyi** [comment]
APP.onload是不是相当于Taro中的componentDidShow这一个方法

**Comment by DrakeXiang** [comment]
> ```tsx
> <Button
>   type='primary'
>   lang='zh_CN'
>   openType='getPhoneNumber'
>   onGetPhoneNumber={this.onGetPhoneNumber.bind(this)}>
>   第二步，授权手机号
> </Button>
> ```
> 
> onGetPhoneNumber 事件永远发生在 Taro.login 之前，
> 尝试在按钮获取加密数据之前调用 Taro.login

这应该在文档里面写一下，我在支付宝下直接在回调里面使用`Taro.login`是正常的，在微信下就解密错误
