### ISSUE TITLE
Canvas标签在支付宝小程序中编译问题

### ISSUE THREAD

**Issue by RedLlips** [NervJS/taro#4239]
**问题描述**
Canvas标签在支付宝小程序中编译问题

**复现步骤**
[复现问题的步骤]
![cdde40509161814cb464a566efdc905](https://user-images.githubusercontent.com/45442596/63405167-70aa9f00-c418-11e9-8099-48a6cb941db6.png)

**期望行为**
期望与其他端一致

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  Windows 10
 - Taro 版本  v1.3.12
 - Node.js 版本  8.11.3
 - 报错平台 [alipay]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
可以升级到 Taro3 再试试
