### ISSUE TITLE
自定义事件二次编译问题

### ISSUE THREAD

**Issue by mosquito1803** [NervJS/taro#4240]
**问题描述**
自定义事件在convert后二次编译时被当做属性处理了

**复现步骤**
[复现问题的步骤]

原始内容：

```html
<btn bind:test="handleTest" text="{{text}}"/>
```

convert后：

```html
<Btn onTest={this.handleTest} text={text}></Btn>
```

再次build后

wxml：

```html
<btn compid="{{$compid__0}}"></btn>
```

js部分内容截取：

```javascript
var _state = this.__state,
    imgUrls = _state.imgUrls,
    text = _state.text;

_index.propsManager.set({
  "onTest": this.handleTest,
  "text": text
}, $compid__0);
Object.assign(this.__state, {
  $compid__0: $compid__0
});
```

可以看到，自定义事件被当做普通属性处理了，因此在自定义组件中通过`this.triggerEvent("test")`触发的事件将无法监听到

**期望行为**

自定义事件能正常监听到

**报错信息**

**系统信息**

  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.5.3

**Comment by luckyadam** [comment]
这个是正常的
