### ISSUE TITLE
react native ios端 运行报错 'Native molule cannot be null'

### ISSUE THREAD

**Issue by imlinqin** [NervJS/taro#4249]
**问题描述**
[问题描述：react native ios端 运行报错 'Native molule cannot be null']

**复现步骤**
[复现问题的步骤]
1.  react native 版本为0.55.4 
2.AppDelegate.m 指向‘rn_temp/index’，moduleName:@"myApp" 和 app.json name名字一样
3.运行红屏报错 'Native molule cannot be null'

这是taro typeScript mbox版 初始化版项目 
rn_temp/app.js
```js

var _class, _temp;

import { Provider as TCRNProvider } from '@tarojs/components-rn';
import TaroRouter from '@tarojs/taro-router-rn';
import pagesIndexIndex from './pages/index/index';
import Taro from '@tarojs/taro-rn';
import React from 'react';
import { Component } from "@tarojs/taro-rn";
import { Provider } from "@tarojs/mobx-rn";

import counterStore from "./store/counter";
//import 'taro-ui/dist/style/index.scss' // 全局引入一次即可
import appStyleSheet from "./app_styles";
// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }
var _styleSheet = appStyleSheet;
const store = {
  counterStore
};
let App = (_temp = _class = class App extends Component {
  constructor() {
    super(...arguments);
    /**
     * 指定config的类型声明为: Taro.Config
     *
     * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
     * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
     * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
     */
    Taro._$app = this;
  }
  componentDidMount() {
    this.componentDidShow();
  }
  componentDidShow() {}
  componentDidHide() {}
  componentDidCatchError() {}
  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Provider store={store}>
                  
                <TCRNProvider>
                  <RootStack />
                </TCRNProvider>
                </Provider>;
  }

  componentWillUnmount() {
    this.componentDidHide && this.componentDidHide();
  }

}, _class.config = {
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}, _temp);
const RootStack = TaroRouter.initRouter([['pages/index/index', pagesIndexIndex]], Taro, App.config);
Taro.initNativeApi(Taro);
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});
export default App;




```

**期望行为**
react native ios端 能正常运行 taro rn 初始化项目

**报错信息**

![image](https://user-images.githubusercontent.com/9410678/63422721-7e265000-c43d-11e9-89e9-369e61b96525.png)

**系统信息**

  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.13 => 1.3.13 
      @tarojs/components-rn: ^1.3.13 => 1.3.14 
      @tarojs/mobx: 1.3.13 => 1.3.13 
      @tarojs/mobx-h5: 1.3.13 => 1.3.13 
      @tarojs/mobx-rn: 1.3.13 => 1.3.13 
      @tarojs/plugin-babel: 1.3.13 => 1.3.13 
      @tarojs/plugin-csso: 1.3.13 => 1.3.13 
      @tarojs/plugin-sass: 1.3.13 => 1.3.13 
      @tarojs/plugin-uglifyjs: 1.3.13 => 1.3.13 
      @tarojs/rn-runner: 1.3.13 => 1.3.13 
      @tarojs/router: 1.3.13 => 1.3.13 
      @tarojs/taro: 1.3.13 => 1.3.13 
      @tarojs/taro-alipay: 1.3.13 => 1.3.13 
      @tarojs/taro-h5: 1.3.13 => 1.3.13 
      @tarojs/taro-redux-rn: ^1.3.13 => 1.3.14 
      @tarojs/taro-rn: ^1.3.13 => 1.3.13 
      @tarojs/taro-router-rn: ^1.3.13 => 1.3.14 
      @tarojs/taro-swan: 1.3.13 => 1.3.13 
      @tarojs/taro-tt: 1.3.13 => 1.3.13 
      @tarojs/taro-weapp: 1.3.13 => 1.3.13 
      @tarojs/webpack-runner: 1.3.13 => 1.3.13 
      eslint-config-taro: 1.3.13 => 1.3.13 
      eslint-plugin-taro: 1.3.13 => 1.3.13 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
      stylelint-config-taro-rn: 1.3.13 => 1.3.13 
      stylelint-taro-rn: 1.3.13 => 1.3.13 
 - 报错平台 [rn]

**补充信息**
这是taro typeScript mbox版 初始化版项目 
[可选]
taro rn版 是否要手工添加相关 ios Libraies

**Comment by Pines-Cheng** [comment]
有 pod install 安装依赖吧。

**Comment by Pines-Cheng** [comment]
壳子里原生依赖 `expo-sensors`  没有安装。

**Comment by imlinqin** [comment]
> 有 pod install 安装依赖吧。
引用官方的 taro-native-shell  ，pod install 还是报错 
’Command Ld failed with a nonzero exit code‘


![image](https://user-images.githubusercontent.com/9410678/63564308-3287b980-c597-11e9-8020-e31d3c09394b.png)

**Comment by Pines-Cheng** [comment]
感觉像是  iOS simulator 及依赖安装相关的问题，参考一下这个issue：https://github.com/facebook/react-native/issues/23282
