### ISSUE TITLE
如何自动在每个单独的 SCSS 文件中引入 SCSS 全局变量

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#425]
在一般的项目中我一般都是在`sass-loader`的`data`选项或者`sass-resources-loader`实现所有 scss 文件自动引入全局变量文件。

但是我看到 Taro 文档中貌似只有 h5 支持 webpack 配置，`defineConstants`选项配置的常量在 scss 文件中貌似并不生效，而且不支持编辑器代码补齐。

请问你们是怎么实现全局变量文件自动引入的？

**Comment by luckyadam** [comment]
目前小程序只能手动写了~

**Comment by vimcaw** [comment]
编译成小程序的时候，`scss`文件应该也是要通过`sass-loader`打包吧，那样的话应该可以通过修改 `webpack` 文件实现的，`sass-loader`有个`data`选项，可以在导入`sass`文件时给所有的文件加入一个指定内容，比如`@import "../../var"`。

**Comment by luckyadam** [comment]
@vimcaw 不是用 sass-loader ，是直接用 node-sass 编译的，不过可以研究下下这个如何实现~

**Comment by tourze** [comment]
求实现这个

**Comment by psaren** [comment]
我在项目中试着去实现scss文件全局变量的自动注入
发现通过修改taro-plugin-sass可以达到这个目的
实现了添加两个参数去自动为每个scss文件注入全局变量
config.js
```
plugin: {
  sass: {
       importer: sassImporter,
       resource: 'path/to/variable.scss',
       projectDirectory: 'path/to/project'
   }
}
```
这为我的项目中带来了很多方便。
具体修改可以看下面的PR
#2725
