### ISSUE TITLE
H5版本,魅族16s手机,Taro.request 获取不到cookie

### ISSUE THREAD

**Issue by xiaohailiang** [NervJS/taro#4251]
**问题描述**
Taro编译h5版本, 在魅族16s手机中, 自带浏览器, 微信内置浏览器,企业微信内置浏览器,通过Taro. request向后端发送请求时, 不能携带cookie, 导致登录信息不能被识别.
 请求中已添加了参数credentials: 'include'
钉钉内置浏览器正常.其他的h5页面(非taro写的)是可以正常使用cookie的.

暂时只在魅族16s发现该问题. 同事的一些安卓和IOS测试正常.

**复现步骤**
找个魅族16s手机,随便测试即可,在日志中查看是否携带cookie

 ```js
    Taro.request({
                 url: 'xxx',
		data: data,
		credentials: 'same-origin',
		method: 'GET',
		header:  {
                       'content-type': 'application/json'
                }
    })
 ```

**期望行为**
api文档上所描述的信息, 没有兼容性问题.

**报错信息**

后端返回错误, 因为没有cookie

**系统信息**
👽 Taro v1.3.10

  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.12 => 1.3.10
      @tarojs/components: 1.3.12 => 1.3.10
      @tarojs/plugin-babel: 1.3.12 => 1.3.10
      @tarojs/plugin-csso: 1.3.12 => 1.3.10
      @tarojs/plugin-sass: 1.3.12 => 1.3.10
      @tarojs/plugin-uglifyjs: 1.3.12 => 1.3.10
      @tarojs/redux: 1.3.12 => 1.3.10
      @tarojs/redux-h5: 1.3.12 => 1.3.10
      @tarojs/router: 1.3.12 => 1.3.10
      @tarojs/taro: 1.3.12 => 1.3.10
      @tarojs/taro-alipay: 1.3.12 => 1.3.10
      @tarojs/taro-h5: 1.3.12 => 1.3.10
      @tarojs/taro-swan: 1.3.12 => 1.3.10
      @tarojs/taro-tt: 1.3.12 => 1.3.10
      @tarojs/taro-weapp: 1.3.12 => 1.3.10
      @tarojs/webpack-runner: 1.3.12 => 1.3.10
      eslint-config-taro: 1.3.12 => 1.3.10
      eslint-plugin-taro: 1.3.12 => 1.3.10
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3
      stylelint-config-taro-rn: 1.3.12 => 1.3.10
      stylelint-taro-rn: 1.3.12 => 1.3.10

 - 操作系统: mac 10.14.5 (18F132)
 - Taro 版本 [v1.3.10]
 - Node.js 版本 [v10.15.0]
 - 报错平台 [h5]

**补充信息**
是否存在兼容性问题, 是否和默认浏览器有关, 能否修复?
不然我就不能使用cookie了, 毕竟不能要求客户不能使用魅族手机

**Comment by luckyadam** [comment]
你试试原生的 fetch 行不行

**Comment by xiaohailiang** [comment]
原生的fetch可以. 什么时候能修复一下吗

**Comment by chenxiao01** [comment]
什么时候修？？？16天了没人修吗  单独用fetch taro多端就没啥意义了

**Comment by chenxiao01** [comment]
@luckyadam
