### ISSUE TITLE
【快应用】执行转换操作，提示缺少包@tarojs/components-qa，然后就退出了

### ISSUE THREAD

**Issue by Qiyu8** [NervJS/taro#4252]
问题描述
任意选择一个taro程序，执行taro build --type quickapp会报错:
缺少包@tarojs/components-qa，请安装

复现步骤
1.在taro根目录执行 taro build --type quickapp

期望行为
@tarojs/components-qa是快应用的UI库，一般情况下都是需要安装的，希望可以做到自动安装依赖

报错信息
缺少包@tarojs/components-qa，请安装

系统信息
操作系统: Windows 10
Taro 版本 v1.3.14
Node.js 版本 v12.7.0
报错平台 weapp
补充信息
优化点：自动安装依赖包@tarojs/components-qa，优化转换体验

**Comment by luckyadam** [comment]
手动安装即可

**Comment by Qiyu8** [comment]
涛哥，打算提个自动安装依赖的PR

**Comment by luckyadam** [comment]
可以啊
