### ISSUE TITLE
RichText回车符无效

### ISSUE THREAD

**Issue by gaorubin1990** [NervJS/taro#4258]
**问题描述**
RichText显示富文本信息时，无法将回车符换行显示

**复现步骤**
将带有回车符的富文本html字符串放到RichText组件中

**期望行为**
有回车符的地方可以换行显示

**报错信息**
无换行显示

**系统信息**
"@tarojs/async-await": "1.3.12",
    "@tarojs/components": "1.3.12",
    "@tarojs/redux": "1.3.12",
    "@tarojs/redux-h5": "1.3.12",
    "@tarojs/router": "1.3.12",
    "@tarojs/taro": "1.3.12",
    "@tarojs/taro-alipay": "1.3.12",
    "@tarojs/taro-h5": "1.3.12",
    "@tarojs/taro-swan": "1.3.12",
    "@tarojs/taro-tt": "1.3.12",
    "@tarojs/taro-weapp": "1.3.12",
    "lodash": "^4.17.15",
    "nerv-devtools": "^1.4.0",
    "nervjs": "^1.4.0",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "taro-ui": "^2.2.1"
**补充信息**

**Comment by Chen-jj** [comment]
什么平台

**Comment by gaorubin1990** [comment]
> 什么平台

微信小程序

**Comment by Chen-jj** [comment]
写份原生试试原生 RichText 是否可以吧

**Comment by gaorubin1990** [comment]
> 写份原生试试原生 RichText 是否可以吧

原生richtext是？我现在用的是@tarojs/components中的RichText在微信平台是有问题的。富文本字符串在web端应用渲染是正常显示缩进和回车的

**Comment by Chen-jj** [comment]
原生 richtext 指写份原生的微信小程序测试小程序提供的 RichText 组件。Taro 的 RichText 直接使用的微信的，你需要区分是微信小程序的问题还是 Taro 的问题。
