### ISSUE TITLE
组件属性以render开头命名，传入jsx在小程序不生效。

### ISSUE THREAD

**Issue by missmimia** [NervJS/taro#4259]
**问题描述**
组件属性以render开头命名，传入jsx在小程序不生效。
h5正常编译显示，冇问题。

```js

// 这里可以贴代码
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
父组件引用：
      <Title
        arrow
        bottomBorder
        className={styles.item}
        renderTips={<View>{mobileStatus}</View>}
        onClick={() => onVerifyLink()}
      >
        <View className={styles.itemName}>手机号</View>
      </Title>

子组件代码：

type Props = {
  arrow?: boolean;
  className?: string;
  renderTips?: React.ReactElement;
  onClick?: () => void;
  children: any;
};

const Title: Taro.FC<Props> = props => {
  const {
    arrow = false,
    className,
    renderTips = '',
    onClick = () => {},
  } = props;

  return (
    <View className={`${styles.wrapper} ${className}`} onClick={onClick}>
      <View>
        <View className={styles.title}>{props.children}</View>
        <View className={styles.tips}>
          {renderTips}
          {arrow && <AiIcon type="arrow" size={20} className={styles.arrow} />}
        </View>
      </View>
    </View>
  );
};

// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
急求解决！！！！！！！😭

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

h5:生成后的html结构：
![image](https://user-images.githubusercontent.com/28520397/63495766-13375080-c4f3-11e9-84fe-f299bdd3b7f9.png)

小程序生成后的结构：
![image](https://user-images.githubusercontent.com/28520397/63495806-264a2080-c4f3-11e9-9ad8-a4bddf24b3e4.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本  "@tarojs/taro": "1.3.12"
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@missmimia https://nervjs.github.io/taro/docs/children.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9，直接使用 {this.props.renderTips}，不要先解构
