### ISSUE TITLE
应当支持全局样式

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro#426]
小程序官方文档 https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html 中提到：

> 定义在 app.wxss 中的样式为全局样式，作用于每一个页面。在 page 的 wxss 文件中定义的样式为局部样式，只作用在对应的页面，并会覆盖 app.wxss 中相同的选择器。

而目前（v1.0.0-beta.6）在 `src/app.js` 中引入的全局样式却无法作用于所有页面与组件（至少在开发者工具中是这样子的，因为新的组件化方案基于 Shadow DOM 实现）。该与 v0.0.73 及其之前的版本都不兼容且不合理。

**Comment by kenberkeley** [comment]
https://github.com/NervJS/taro/issues/404

**Comment by kenberkeley** [comment]
相信很多同学都会用 WeUI 这种样式库，一般都是全局引入，而不是每个页面每个组件都引入

**Comment by vimcaw** [comment]
感谢分享，原来是这样，我说怎么一升级 iconfont 全部不显示了，暂时只能在组件的样式文件里一个个引入了。

**Comment by htfcumt2004** [comment]
真需要一个全局的样式引入

**Comment by luckyadam** [comment]
正在支持 ing

**Comment by kenberkeley** [comment]
请问打算 beta 几可以支持呀~

**Comment by luckyadam** [comment]
@kenberkeley beta.14 支持啦

**Comment by kenberkeley** [comment]
棒

**Comment by kenberkeley** [comment]
棒

**Comment by kenberkeley** [comment]
当前（Taro 1 beta 17 + 小程序基础库 2.2.3）通过如下配置实现继承全局样式：

```js
class XXX extends Component {
  static options = {
    addGlobalClass: true
  }
  ...
}
```
