### ISSUE TITLE
在taro中使用hooks 并使用Dva？

### ISSUE THREAD

**Issue by chenyinlong** [NervJS/taro#4260]
H5中构建时报
<img width="420" alt="微信截图_20190822154942" src="https://user-images.githubusercontent.com/16054968/63496458-89888280-c4f4-11e9-886f-a65c971c3782.png">
redux-h5 中并没有实现useStore 等hooks方法嘛？
如果可以的话，我需要怎么做才能使用？

**Comment by luckyadam** [comment]
贴一下相关代码

**Comment by Littly** [comment]
redux-h5的hooks系列api还在开发中。

**Comment by chenyinlong** [comment]
谢谢
