### ISSUE TITLE
Hooks 在支付宝小程序的分包也出现了之前redux在支付宝分包报错的问题都是store丢失

### ISSUE THREAD

**Issue by ooxx87** [NervJS/taro#4261]
Hooks 在支付宝小程序的分包也出现了之前redux在支付宝分包报错的问题都是store丢失
![微信图片_20190822160017](https://user-images.githubusercontent.com/39373576/63497242-f51f1f80-c4f5-11e9-8515-bb6692a79af1.jpg)

请问能修复下吗？正式项目较急

**Comment by Chen-jj** [comment]
应该也是一样问题，分包的全局环境和主包全局环境割裂，全局对象失效。尽快修复

**Comment by ooxx87** [comment]
感谢

**Comment by Chen-jj** [comment]
@ooxx87 提供一下代码

**Comment by Chen-jj** [comment]
@ooxx87 复现不了，提供一个最小可复现 demo 吧
