### ISSUE TITLE
微信小程序json里给类定义组件问题

### ISSUE THREAD

**Issue by dawang90** [NervJS/taro#4262]
------------------------

**问题描述**
微信小程序问题
```js
render() {
   const json = {
   list: [{
    name: <View></View>
   }]
  }
  return (
     <View>
        <List data={json}></List>
     </View>
  )
}
// ```
编译后const json这段代码没了
报 json is not defined
```

**Comment by Chen-jj** [comment]
@dawang90 不支持这样传 JSX，使用 [renderProps](https://nervjs.github.io/taro/docs/render-props.html) 或 [组合](https://nervjs.github.io/taro/docs/children.html#%E7%BB%84%E5%90%88)。
