### ISSUE TITLE
【快应用】SCSS文件转换为CSS文件之后没有格式化

### ISSUE THREAD

**Issue by Qiyu8** [NervJS/taro#4263]
问题描述
Taro的SCSS写法如下：
```
page {
     background-color: red;
     font-size: 24px;
}
```
在taro build --type quickapp之后生成的CSS文件如下所示（全部挤在了一行）：
`page {background-color: red;font-size: 24px;}`

复现步骤
1.在Taro根目录执行taro build --type quickapp

期望行为
生成格式化的CSS文件

报错信息
无

系统信息
操作系统: Windows 10
Taro 版本 v1.3.14
Node.js 版本 v12.7.0
报错平台 weapp
补充信息

**Comment by Qiyu8** [comment]
而且在转换过程中去除了所有空格，导致出现类似 backgroud-color:#fff!important的错误样式，快应用就无法预览了

**Comment by luckyadam** [comment]
直接 build 会压缩，加上 --watch 试试
