### ISSUE TITLE
convert后再执行build无法从app.js中onlaunch获取场景值

### ISSUE THREAD

**Issue by mosquito1803** [NervJS/taro#4264]
**问题描述**
在微信小程序中，页面内可以通过onload获取场景值，app.js中可以通过onlaunch中获取场景值。使用taro执行convert后重新build，在页面内仍然可以正常获取场景值，但app.js中无法正常获取

**复现步骤**

app.js部分代码片段：

```javascript
App({
  onLaunch({ scene }) {
    console.log(scene)
```

在convert后再进行build，会报错`Cannot read property 'scene' of undefined`，推测可能是app.js中对应的生命周期没有对相关参数进行兼容

**期望行为**

与页面中onload的处理类似，希望app.js中onlaunch也能做同样兼容。

**报错信息**

![image](https://user-images.githubusercontent.com/37946436/63504049-45e94500-c503-11e9-8022-1df9e58525ce.png)

**系统信息**
  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.5.3

**补充信息**

目前可以使用this.$router.params替代来获取场景值，但建议能做兼容

**Comment by luckyadam** [comment]
升级到 1.3.14 再 convert 试下呢

**Comment by mosquito1803** [comment]
升级到1.3.15后问题仍然存在

**Comment by luckyadam** [comment]
1.3.18 解决了此问题
