### ISSUE TITLE
能否在编译层面对渲染中用到但未赋初值的数组变量做兼容

### ISSUE THREAD

**Issue by mosquito1803** [NervJS/taro#4266]
如下的代码
```
<view wx:for="{{list}}"></view>
```
执行convert后，得到
```
{list.map((item, index) => {
  return (
    <view></view>
  )
})
}
```

如果list未赋初值，则首次渲染时将报错。

能否在convert时进行优化，编译成为
```
{list && list.map((item, index) => {
  return (
    <view></view>
  )
})
}
```

这样比较符合微信小程序的开发习惯，因微信小程序中不赋初值仅仅只是不进行渲染，而不会抛出错误

环境：

  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.5.3

**Comment by luckyadam** [comment]
在编译时并不知道这个变量有没有被赋值啊

**Comment by mosquito1803** [comment]
是的 所以看下如果能编译成我后面提的list&&list.map这种形式是否好一点 这个其实也并不需要知道变量是否被赋值吧 而且增加了一层容错
