### ISSUE TITLE
支付宝小程序proceed这个方法不执行,微信小程序没有问题

### ISSUE THREAD

**Issue by liuyunzyj** [NervJS/taro#4268]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
使用官方推荐的https://github.com/TigerHee/taro-request
请求一个401的接口
微信小程序走proceed这个方法，支付宝小程序不走这个方法，
接口返回
{data: {…}, headers: {…}, status: 401, error: 19, errorMessage: "http status error"}
**复现步骤**
[复现问题的步骤]
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
希望支付宝小程序走proceed这个方法
**报错信息**

**Comment by Chen-jj** [comment]
@liuyunzyj 先自行打断点定位下吧，或者直接使用 Taro 提供的 interceptor

**Comment by liuyunzyj** [comment]
@Chen-jj 打过了，微信没有问题，支付宝不走

**Comment by Chen-jj** [comment]
@liuyunzyj 打过断点应该能定位到具体问题吧

**Comment by liuyunzyj** [comment]
就是这个问题啊---》微信小程序走proceed这个方法，支付宝小程序不走这个方法，

**Comment by liuyunzyj** [comment]
我用console.log打印的，支付宝小程序在proceed这个方法里就不回打印出东西，而微信小程序可以打印出来

**Comment by Chen-jj** [comment]
@liuyunzyj 额，我的意思是代码方面的问题，通过打断点定位出更具体的问题点

**Comment by Chen-jj** [comment]
@liuyunzyj 不是这样调试的。。你打个 debugger，一句一句代码调吧

**Comment by liuyunzyj** [comment]
这样也试过了，不走proceed这个方法，我截图给你吧

**Comment by Chen-jj** [comment]
@liuyunzyj 你关注点不应只是走不走 proceed，而是为什么不走。建议从 request 返回一直断点下来，肯定能定位到问题。

**Comment by liuyunzyj** [comment]
代码
![image](https://user-images.githubusercontent.com/40293335/63562425-28ae8800-c590-11e9-87c3-7bb011c330a1.png)
微信小程序：进入debugger
![image](https://user-images.githubusercontent.com/40293335/63562453-3cf28500-c590-11e9-87f3-36fd66d04837.png)

支付宝小程序：没有进入debuggger
![image](https://user-images.githubusercontent.com/40293335/63562478-598ebd00-c590-11e9-9956-d29bd11f01dd.png)

**Comment by Chen-jj** [comment]
@liuyunzyj  还是这个回复，你关注点不应只是走不走 proceed，而是为什么不走。建议从 request 返回一直断点下来，肯定能定位到问题。

**Comment by liuyunzyj** [comment]
你可以把官方的demo拿下来后分别在支付宝和微信各端小程序，在我那个位置调试下，他不是这个方法，一个的代码那为什么微信走，支付宝不走

**Comment by Chen-jj** [comment]
@liuyunzyj 你断点关注的地方是不对的，“建议从 request 返回一直断点下来，肯定能定位到问题。”

**Comment by Chen-jj** [comment]
@liuyunzyj customInterceptor，甚至说你使用到的 request 库，你都没有 debugger 进去看，那怎么看出问题呢

**Comment by liuyunzyj** [comment]
我就这么问你吧，一样的请求下来，一样的代码，微信能打到断点，支付宝不行，你可以把官网的demo拿下来试一试，请求一个401的接口

**Comment by Chen-jj** [comment]
@liuyunzyj 我的意思是你可以先自行打断点，定位到具体问题，方法已经详细告诉你了。

**Comment by liuyunzyj** [comment]
我这边已经打过断点了，支付宝打到那个地方后就不会去走这个断点，你自己真的是可以去拿https://github.com/TigerHee/taro-request这个试一试就知道了

**Comment by liuyunzyj** [comment]
你自己不去试就知道说打断点，我也知道一路打断点咯，问题就是打到那个地方，支付宝小程序，就不走那个断点了，你说，你还能怎么打断点

**Comment by Chen-jj** [comment]
@liuyunzyj customInterceptor 你 debugger 进去看了吗？你使用到的 request 库 debugger 进去看了吗？原生的 interceptor 你试过行不行了吗？

**Comment by liuyunzyj** [comment]
兄弟，你去拉下https://github.com/TigerHee/taro-request这个试一试就知道了，按我的来那个地方debugger下就知道了，支付宝是的401请求来的数据，跟微信小程序请求来的的走法不一样

**Comment by Chen-jj** [comment]
@liuyunzyj “customInterceptor 你 debugger 进去看了吗？你使用到的 request 库 debugger 进去看了吗？原生的 interceptor 你试过行不行了吗？”建议这些都做了再提问

**Comment by liuyunzyj** [comment]
建议尝试后在回复
