### ISSUE TITLE
执行eslint检查时，出现报错~

### ISSUE THREAD

**Issue by Surile** [NervJS/taro#4269]
执行以下命令
```javascript
eslint ./src
```
会报以下错误
```javascript
Error: Cannot find module 'eslint-config-taro'
```
**问题来了：**
* 首先我已经在使用`yarn add eslint-config-taro`下载**npm**包了。
* 其次才执行`eslint ./src`

**Comment by ahonn** [comment]
执行 `./node_modules/.bin/eslint ./src`，直接执行 `eslint ./src` 调用全局 node_modules 下的 eslint。
建议你把 `eslint ./src` 加到 package.json 的 script 中，通过 `yarn run lint` 执行。这样会自动将当前目录下的 node_modules/.bin/ 加到 PATH 中再运行对应到命令，就不会有以上到问题了。

**Comment by Surile** [comment]
@ahonn 了解。谢谢

**Comment by uwjiaoxing** [comment]
```bash
cd /usr/local/lib/node_modules/@tarojs/cli && yarn add eslint-config-taro
```
参考  https://github.com/NervJS/taro/issues/2121#issuecomment-462621441
