### ISSUE TITLE
开发计划提议

### ISSUE THREAD

**Issue by liymax** [NervJS/taro#427]
个人觉得即将开始的开发项更加让人期待，特别是 Tree Shaking和Styled Components支持，
如果能早日实现，必将吸引更多开发者的关注

**Comment by vimcaw** [comment]
可以建立一个新功能投票的 Issue 吗？让呼声最高的功能优先开发。

类似 `Snipaste` 的 [Requested features \| 已收集的建议 · Issue \#282 · Snipaste/feedback](https://github.com/Snipaste/feedback/issues/282)

**Comment by luckyadam** [comment]
@vimcaw 可以的~ 这样更能带动社区发展了~ 👍

**Comment by MinJieLiu** [comment]
+1

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/caf47fe1d4ba919957d8c4b9b45bf8a05c005f97
