### ISSUE TITLE
[rn]希望rn可以根据app所定义的页面来编译

### ISSUE THREAD

**Issue by YuanQuan** [NervJS/taro#4276]
**期望行为**
1.希望可以通过配置app中的pages与subPackages来编译页面文件
2.希望可以只编译rn或不带平台标记的命名文件
PS：目前的项目目录都编译
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [rn]

**Comment by YuanQuan** [comment]
@Pines-Cheng

**Comment by Pines-Cheng** [comment]
这个需求貌似可以通过定义跨端文件来解决：

![image](https://user-images.githubusercontent.com/9441951/65407139-24d28780-de14-11e9-8763-8d06632f730b.png)

![image](https://user-images.githubusercontent.com/9441951/65407140-28660e80-de14-11e9-8a02-3d0de0752347.png)

**Comment by Pines-Cheng** [comment]
已实现，将在 2.1 中发布。
