### ISSUE TITLE
H5 多个页面监听滚动事件 取消监听还是会被触发

### ISSUE THREAD

**Issue by PlutoCA** [NervJS/taro#4280]
**问题描述**
H5 多个页面监听滚动事件 已经在 componentWillUnmount 取消监听了，但还是会在其它页面被触发

**复现步骤**
[复现问题的步骤]
进入page1 => 注册滚动事件 => componentWillUnmount 卸载事件
=> 进入page2 => 注册滚动事件 => 滚动 => 触发page1 和 page2 的滚动事件

```js
  // page1
  componentDidMount () { 
    window.addEventListener('scroll',  throttle(this.onScrollPage1, 600, 200))
  }

  onScrollPage1 = () => {
    console.log('我是page1页面的绑定的滚动事件')
  }

  componentWillUnmount = () => {
    console.log('page1页面卸载')
    window.removeEventListener("scroll", this.onScrollPage1);
  }
```

```js
 // page2 页面
  componentDidMount () { 
    window.addEventListener('scroll',  throttle(this.onScrollPage2, 600, 200))
  }

  onScrollPage2 = () => {
    console.log('我是page2页面的绑定的滚动事件')
  }

  componentWillUnmount = () => {
    console.log('page2页面卸载')
    window.removeEventListener("scroll", this.onScrollPage2);
  }
```
会在一个页面触发多个事件
![image](https://user-images.githubusercontent.com/31099607/63635598-cc825b80-c696-11e9-9fc4-4088c770cc23.png)

要是没复现 那就再来一个page😂

**期望行为**
取消监听了就不要再被触发了

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
```
Taro v1.3.14
  Taro CLI 1.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
```
**补充信息**
[可选]
好像Taro.navigateTo 并不会触发 componentWillUnmount

**Comment by Littly** [comment]
navigateTo并不会触发componentWillUnmount。在componentDidHide里处理吧。

**Comment by Littly** [comment]
navigateTo并不会触发componentWillUnmount。在componentDidHide里处理吧。

**Comment by PlutoCA** [comment]
问题是哪怕触发了removeEventListener 事件 可还是会被执行呀
![image](https://user-images.githubusercontent.com/31099607/63647947-f8ffab80-c75a-11e9-9529-13e398bcb2ce.png)

**Comment by PlutoCA** [comment]
@Littly
