### ISSUE TITLE
建议h5端的路由去除pages和index

### ISSUE THREAD

**Issue by AlexStacker** [NervJS/taro#429]
现在h5生成的路由都带有pages和index，比如登录页面`/pages/login/index`，这样在地址栏里看着不友好，假如需要手动输入的话字符又太多，如果直接是`/login`就好很多。

建议生成h5页面的时候把路由里的`pages`和`index`去掉，可以满足大部分的情况。或者在现有基础上多生成一条不含`pages`和`index`的记录，这样对历史项目应该也没有问题了。

**Comment by Littly** [comment]
有道理 我们后面给路由加个alias配置 应该可以满足你的需求
