### ISSUE TITLE
h5 使用named export的方式导出page,会出错

### ISSUE THREAD

**Issue by masteroy** [NervJS/taro#4290]
**问题描述**
默认的page导出方式是这样：
``` javascript
// index.tsx
export default class Index extends Component {
    ....
}
// app.tsx
import Index from './pages/index'
...
```
如果采用named export的方式：
``` javascript
// index.tsx
export class Index extends Component {
    ....
}
// app.tsx
import { Index } from './pages/index'
```

可以编译通过，在weapp下面运行时没问题的，但在h5下会报

``` terminal
Error: Received a falsy component for route "/pages/index/index". Forget to export it?
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 👽 Taro v1.3.14

  Taro CLI 1.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\PROGRA~2\Yarn\bin\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by JamesAgoda** [comment]
@Littly 赞

**Comment by masteroy** [comment]
@Littly 赞
