### ISSUE TITLE
引入第三方vant-weapp报错

### ISSUE THREAD

**Issue by JazzOne** [NervJS/taro#4302]
**问题描述**
引入第三方vant-weapp报错

**复现步骤**
[复现问题的步骤]
1. 下载vant-weapp
2. 拷贝dist文件内容至项目components文件夹
3. 引入组件并使用

![2A242CBF021CC25726F67EF9516B0C70](https://user-images.githubusercontent.com/17613972/63739346-72181380-c8bf-11e9-850b-10b17d2e8b83.jpg)

![46E6605EAAEB4523EDA1ED57DED1EB1C](https://user-images.githubusercontent.com/17613972/63739352-793f2180-c8bf-11e9-9d65-b7958247adcf.jpg)

![image](https://user-images.githubusercontent.com/17613972/63739377-88be6a80-c8bf-11e9-8b56-c3d794f30a5f.png)

**期望行为**
正常引入并使用

**报错信息**

![image](https://user-images.githubusercontent.com/17613972/63739491-eeaaf200-c8bf-11e9-837f-9949380fcb7c.png)

**系统信息** 

 - 操作系统: [macOS 10.14.6]
 - Taro 版本 [v.1.3.14]
 - Node.js 版本 [v12.8.1]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by mihuartuanr** [comment]
**Taro中引入Vant Weapp，不能直接通过第三方`NPM`包的形式直接调用。**

需要进行以下几步：

* 在github上找到[Vant-weapp](https://github.com/youzan/vant-weapp)下载文件包，将对应的`dist`目录复制到项目`/src/components/vant-weapp`目录下。

* 在`Pages`对应文件的`config.usingComponents`中，配置每个页面所需要的组件。(无法在`app.js`中进行所谓的全局注册组件。)

```
  config = {
    navigationBarTitleText: '首页',
    usingComponents: {
      "van-button": "../../components/vant-weapp/button/index",
      "van-popup": "../../components/vant-weapp/popup/index"
    }
  }
```

* 在使用`Vant-weapp`组件后，`taro`构建会**自动**将相应的组件复制一份到`dist/components`下，而`Vant-weapp`的组件还依赖工具库`/src/components/vant-weapp/wxs`，该工具库`taro`**不会自动**复制到`dist`中。所以，我们需要修改`/config/index.js`文件中的`config.copy.patterns`，让其在编译时，自动复制到`dist`对应目录下。

```
  copy: {
    patterns: [
      {
        from: 'src/components/vant-weapp/wxs/',
        to: 'dist/components/vant-weapp/wxs/'
      }
    ],
    options: {
    }
  },
```

* 由于`Vant-weapp`的样式使用的单位是`px`，所以会被`taro`编译成`rpx`，以便对各个设配进行适配。可以通过修改`/config/index.js`文件中的`config.weapp.module.pxtransform.selectorBlackList`不让其单位转换。

```
pxtransform: {
  enable: true,
  config: {

  },
  selectorBlackList: [
    /^.van-.*?$/,  // 这里是vant-weapp中className的匹配模式
  ]
},
```

这是参考别人，自己又整理的，我也是大姑娘上轿。现在可用。

**Comment by JazzOne** [comment]
> **Taro中引入Vant Weapp，不能直接通过第三方`NPM`包的形式直接调用。**
> 
> 需要进行以下几步：
> 
> * 在github上找到[Vant-weapp](https://github.com/youzan/vant-weapp)下载文件包，将对应的`dist`目录复制到项目`/src/components/vant-weapp`目录下。
> * 在`Pages`对应文件的`config.usingComponents`中，配置每个页面所需要的组件。(无法在`app.js`中进行所谓的全局注册组件。)
> 
> ```
>   config = {
>     navigationBarTitleText: '首页',
>     usingComponents: {
>       "van-button": "../../components/vant-weapp/button/index",
>       "van-popup": "../../components/vant-weapp/popup/index"
>     }
>   }
> ```
> 
> * 在使用`Vant-weapp`组件后，`taro`构建会**自动**将相应的组件复制一份到`dist/components`下，而`Vant-weapp`的组件还依赖工具库`/src/components/vant-weapp/wxs`，该工具库`taro`**不会自动**复制到`dist`中。所以，我们需要修改`/config/index.js`文件中的`config.copy.patterns`，让其在编译时，自动复制到`dist`对应目录下。
> 
> ```
>   copy: {
>     patterns: [
>       {
>         from: 'src/components/vant-weapp/wxs/',
>         to: 'dist/components/vant-weapp/wxs/'
>       }
>     ],
>     options: {
>     }
>   },
> ```
> 
> * 由于`Vant-weapp`的样式使用的单位是`px`，所以会被`taro`编译成`rpx`，以便对各个设配进行适配。可以通过修改`/config/index.js`文件中的`config.weapp.module.pxtransform.selectorBlackList`不让其单位转换。
> 
> ```
> pxtransform: {
>   enable: true,
>   config: {
> 
>   },
>   selectorBlackList: [
>     /^.van-.*?$/,  // 这里是vant-weapp中className的匹配模式
>   ]
> },
> ```
> 
> 这是参考别人，自己又整理的，我也是大姑娘上轿。现在可用。

Vant-weapp的组件还依赖工具库/src/components/vant-weapp/wxs，该工具库taro不会自动复制到dist中。

如上所述，就是这个原因导致报错，现已解决

**Comment by liliang-cn** [comment]
![image](https://user-images.githubusercontent.com/20553741/70782611-62ff9780-1dc2-11ea-9d94-d09fbd76a2a2.png)
![image](https://user-images.githubusercontent.com/20553741/70782625-6d219600-1dc2-11ea-8d65-86597f822f71.png)
van-loading 是好使的，van-tabs会报错，可有什么方法？

**Comment by journey-xt** [comment]
补充一下 Vant Weapp@2.0+  wxs 位置在dis目录下 所以配置有所更改
 patterns: [
      {
        from: 'src/components/vant-weapp/dist/wxs/',
        to: 'dist/components/vant-weapp/dist/wxs/',
      },
    ],

**Comment by xiao8Git** [comment]
taro 版本2.1.6里添加了下面配置还是会把px转成rpx，这应该是bug
selectorBlackList: [
    /^.van-.*?$/,  // 这里是vant-weapp中className的匹配模式
  ]

**Comment by erlei22** [comment]
> taro 版本2.1.6里添加了下面配置还是会把px转成rpx，这应该是bug
> selectorBlackList: [
> /^.van-.*?$/, // 这里是vant-weapp中className的匹配模式
> ]

taro 版本2.1.1 也会出现这个问题
