### ISSUE TITLE
[微信小程序]驼峰式命名的事件无法被触发

### ISSUE THREAD

**Issue by mihuartuanr** [NervJS/taro#4306]
开发中引入了`vant-weapp`，对于里面类似`vant-tree-select`组件的`bind: click-nav`，在`Taro`中改写成`onClickNav`，无法被触发。

原谅我没看懂，`Taro`中这个绑定的事件最终编译成了什么...

**Comment by yuche** [comment]
你有在 usingComponents 加入使用的组件吗

**Comment by mihuartuanr** [comment]
引入组件了，不是连字符形式都可以触发，有连字符形式的，改写成驼峰就不行了。

**Comment by luckyadam** [comment]
这种情况得写成 `onClick-nav`，这样才会编译成 `bind:click-nav` 因为 Taro 编译不知道原生小程序里事件名是啥，只能写什么就编译成什么

**Comment by mihuartuanr** [comment]
> 这种情况得写成 `onClick-nav`，这样才会编译成 `bind:click-nav` 因为 Taro 编译不知道原生小程序里事件名是啥，只能写什么就编译成什么

……测试过，不行

**Comment by Chen-jj** [comment]
@mihuartuanr 没有问题，完全可以触发。

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Index extends Component {

  config = {
    usingComponents: {
      'van-tree-select': '../../components/vant-weapp/dist/tree-select/index'
    }
  }

  state = {
    items: [
      {
        // 导航名称
        text: '所有城市',
        // 该导航下所有的可选项
        children: [
          {
            // 名称
            text: '温州',
            // id，作为匹配选中状态的标识
            id: 1
          },
          {
            text: '杭州',
            id: 2
          }
        ]
      }
    ]
  }

  render () {
    return (
      <View>
        <van-tree-select
          items={this.state.items}
          onClick-nav={() => console.log('nav click')}
          onClick-item={e => console.log('item click: ', e.detail.text)}
        />
      </View>
    )
  }
}
```

```xml
<van-tree-select items="{{items}}" bind:click-nav="anonymousFunc0" bind:click-item="anonymousFunc1" __fn_onClick-nav="{{true}}" __fn_onClick-item="{{true}}"></van-tree-select>
```

![image](https://user-images.githubusercontent.com/11807297/63821638-43ae3d00-c980-11e9-8f92-97a67cb4fdf2.png)

**Comment by mihuartuanr** [comment]
> @mihuartuanr 没有问题，完全可以触发。
> 
> ```js
> import Taro, { Component } from '@tarojs/taro'
> import { View } from '@tarojs/components'
> 
> export default class Index extends Component {
> 
>   config = {
>     usingComponents: {
>       'van-tree-select': '../../components/vant-weapp/dist/tree-select/index'
>     }
>   }
> 
>   state = {
>     items: [
>       {
>         // 导航名称
>         text: '所有城市',
>         // 该导航下所有的可选项
>         children: [
>           {
>             // 名称
>             text: '温州',
>             // id，作为匹配选中状态的标识
>             id: 1
>           },
>           {
>             text: '杭州',
>             id: 2
>           }
>         ]
>       }
>     ]
>   }
> 
>   render () {
>     return (
>       <View>
>         <van-tree-select
>           items={this.state.items}
>           onClick-nav={() => console.log('nav click')}
>           onClick-item={e => console.log('item click: ', e.detail.text)}
>         />
>       </View>
>     )
>   }
> }
> ```
> 
> ```
> <van-tree-select items="{{items}}" bind:click-nav="anonymousFunc0" bind:click-item="anonymousFunc1" __fn_onClick-nav="{{true}}" __fn_onClick-item="{{true}}"></van-tree-select>
> ```
> 
> ![image](https://user-images.githubusercontent.com/11807297/63821638-43ae3d00-c980-11e9-8f92-97a67cb4fdf2.png)

还是版本问题，昨天升级了`@tarojs/cli`，重新初始化环境，刚刚试了下，可以了。辛苦

**Comment by nancunpei** [comment]
使用vant-weapp 1.5.2, taro3 似乎不能触发事件
`package.json`
```
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.0.9",
    "@tarojs/react": "3.0.9",
    "@tarojs/runtime": "3.0.9",
    "@tarojs/taro": "3.0.9",
    "leaflet": "^1.7.1",
    "proj4": "^2.6.2",
    "proj4leaflet": "^1.0.2",
    "prop-types": "^15.7.2",
    "react": "^16.10.0",
    "react-dom": "^16.10.0",
    "taro-ui": "3.0.0-alpha.3"
  }
```

`pages/index/index.js`
```
import React, { Component } from 'react'
import Taro from '@tarojs/taro'

export default class Index extends Component {

  // config = {
  //   usingComponents: {
  //     'van-tree-select': '../../components/vant-weapp/dist/tree-select/index'
  //   }
  // }

  render() {
    const state = {
      items: [
        {
          text: '所有城市',
          // 该导航下所有的可选项
          children: [
            {
              // 名称
              text: '温州',
              // id，作为匹配选中状态的标识
              id: 1
            },
            {
              text: '杭州',
              id: 2
            }
          ]
        }
      ]
    }
    return (
      <view>
        <van-tree-select
          items={state.items}
          onClickNav={() => console.log('nav click')}
          onClickItem={e => console.log('item click: ', e.detail.text)}
        />
      </view>
    )
  }
}
```

`pages/index/index.config.js`
```
export default {
  navigationBarTitleText: '关于',
  usingComponents: {
    'van-tree-select': '../../components/vant-weapp/dist/tree-select/index',
  }
}
```

**Comment by zhangchenna** [comment]
3.0.17 不行啊

**Comment by zhangchenna** [comment]
> 3.0.17 触发不了onClick-left这种

只能改源码吗？
