### ISSUE TITLE
通过dev:h5方式本地运行，文件修改后页面有问题

### ISSUE THREAD

**Issue by neoscript99** [NervJS/taro#431]
# **问题描述**
工程自动更新失败

# **复现步骤**
1. 通过yarn dev:h5运行工程
2. 修改单个文件，并保存（.js或.scss文件都一样）
3. taro检查到文件更新，日志中提示编译成功
    ```    
    修改  文件变动  src/pages/shop/shop.scss
    ✅  Compile successfully! 
    ```
1. chrome打开的网页会自动刷新，但页面、样式会出现问题
1. 重启服务后是正常的
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

无

**系统信息**

 - 操作系统: [Deepin GNU/Linux 15.5]
 - Taro 版本 ["@tarojs/taro": "^0.0.73","@tarojs/cli": "^0.0.73"]
 - Node.js 版本 [v9.3.0]
-  yarn版本[1.6.0]

**Comment by neoscript99** [comment]
# 正常页面
![image](https://user-images.githubusercontent.com/11485735/43750280-35576c58-9a2a-11e8-88c8-ab0c4ee96581.png)

# 修改文件重新编译后的错误页面截图（修改内容都是正确的，没有代码问题）
![image](https://user-images.githubusercontent.com/11485735/43750218-e16c5f86-9a29-11e8-8d66-4be3fe73b8ab.png)

# 重启服务后显示又正常

**Comment by Littly** [comment]
可能是不同页面之间样式相互覆盖导致的样式异常 后续会给页面添加选择器解决

**Comment by neoscript99** [comment]
目前有办法规避吗？使用起来太麻烦。

**Comment by luckyadam** [comment]
@neoscript99 主要是不同页面出现了同名样式覆盖的情况导致~ 修改样式名或者通过页面加选择器，然后在页面选择器下写样式可以规避这个问题

**Comment by neoscript99** [comment]
什么是“页面加选择器”，有没有代码可以参考下？
我自己写的scss是没有重名的。

谢谢！

**Comment by luckyadam** [comment]
@neoscript99 选择器，className 之类的没有重名么
