### ISSUE TITLE
taro-native-shell壳子执行run-android报错

### ISSUE THREAD

**Issue by Lynss** [NervJS/taro#4311]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
执行 react-native run-android 遇到报错
![image](https://user-images.githubusercontent.com/21052565/63757969-9f7bb600-c8ed-11e9-93e2-b218e38fddd4.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

![image](https://user-images.githubusercontent.com/21052565/63757969-9f7bb600-c8ed-11e9-93e2-b218e38fddd4.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macos 10.14.6
 - Taro 版本 1.3.14
 - Node.js 版本 10.16.3
 - 报错平台 react-native

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
遇到报错
![image](https://user-images.githubusercontent.com/21052565/63757969-9f7bb600-c8ed-11e9-93e2-b218e38fddd4.png)
，去对应的github仓库找了下发现相关issue ,https://github.com/expo/expo/pull/4585,猜测是模版变化导致，
因此尝试着将taro-native-shel中的依赖的expo-*全部换成最新的6.0.0
![image](https://user-images.githubusercontent.com/21052565/63757981-a4d90080-c8ed-11e9-84a9-aa8b3d742580.png)
，问题解决

**Comment by Lynss** [comment]
顺便想问问，官方能把rn的版本更新下么，感觉0.55的坑有点点多。。。跑ios的时候也是各种问题，而且都是很多人碰到了的。但是用rn-cli建的最新版的demo都没碰到问题。

**Comment by Pines-Cheng** [comment]
> 顺便想问问，官方能把rn的版本更新下么，感觉0.55的坑有点点多。。。跑ios的时候也是各种问题，而且都是很多人碰到了的。但是用rn-cli建的最新版的demo都没碰到问题。

可以自行升级的，直接升级 RN 版本就行。

**Comment by Pines-Cheng** [comment]
taro-native-shell 依赖已更新。
