### ISSUE TITLE
H5下拉刷新没有效果（使用hooks api）

### ISSUE THREAD

**Issue by sussertod891015** [NervJS/taro#4313]
**问题描述**
编译H5，使用Taro.startPullDownRefresh、usePullDownRefresh、useReachBottom没有效果。

**复现步骤**
![image](https://user-images.githubusercontent.com/10465307/63780924-80941880-c91b-11e9-96a7-c0f76cc1c324.png)

```js

useDidShow( () => {
		// dispatch( {
		// 	type: 'product/getProducts',
		// 	payload: {
		// 		current: 1,
		// 	},
		// } );
		Taro.startPullDownRefresh();
	} );
	
	usePullDownRefresh( () => {
		// dispatch( {
		// 	type: 'product/getProducts',
		// 	payload: {
		// 		current: 1,
		// 	},
		// } ).then( () => {
		// 	Taro.stopPullDownRefresh();
		// } );
		console.log(123);
	} );
	
	useReachBottom( () => {
		// if ( props.list.length < props.total ) {
		// 	dispatch( {
		// 		type: 'product/getProducts',
		// 		payload: {
		// 			current: props.current + 1,
		// 		},
		// 	} );
		// }
		console.log(456);
	} );
```

**期望行为**
能够正常使用下拉刷新、上拉加载的功能。

**报错信息**

无报错信息

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.15 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.8.0 - ~/.nvm/versions/node/v11.8.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v11.8.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.8.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.15 => 1.3.15 
      @tarojs/components: 1.3.15 => 1.3.15 
      @tarojs/plugin-babel: 1.3.15 => 1.3.15 
      @tarojs/plugin-csso: 1.3.15 => 1.3.15 
      @tarojs/plugin-sass: 1.3.15 => 1.3.15 
      @tarojs/plugin-uglifyjs: 1.3.15 => 1.3.15 
      @tarojs/redux: 1.3.15 => 1.3.15 
      @tarojs/redux-h5: 1.3.15 => 1.3.15 
      @tarojs/router: 1.3.15 => 1.3.15 
      @tarojs/taro: 1.3.15 => 1.3.15 
      @tarojs/taro-alipay: 1.3.15 => 1.3.15 
      @tarojs/taro-h5: 1.3.15 => 1.3.15 
      @tarojs/taro-swan: 1.3.15 => 1.3.15 
      @tarojs/taro-tt: 1.3.15 => 1.3.15 
      @tarojs/taro-weapp: 1.3.15 => 1.3.15 
      @tarojs/webpack-runner: 1.3.15 => 1.3.15 
      eslint-config-taro: 1.3.15 => 1.3.15 
      eslint-plugin-taro: 1.3.15 => 1.3.15 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      react: ^16.8.6 => 16.8.6 

**补充信息**
无

**Comment by giantss** [comment]
哎 H5是老问题了

**Comment by yulrosy** [comment]
我也遇到了

**Comment by igpfpyu** [comment]
3.0.14版本表示也遇到同样的问题

**Comment by igpfpyu** [comment]
更新的东西能同步到API上吗？

**Comment by Chen-jj** [comment]
@igpfpyu 3.0.15 试试，还不行就新开个 issue 附上demo 咯

**Comment by ouzhou** [comment]
救救h5 
支持一下useReachBottom

**Comment by ZakaryCode** [comment]
> 救救h5 支持一下useReachBottom

3.x 支持
