### ISSUE TITLE
同一个事件处理函数在同一个组件上不能多次bind

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#432]
**问题描述**
同一个事件处理函数在同一个组件上不能多次`bind`，只能生成同一个函数。

**复现步骤**

```js
<ActionBar
  onAddToCart={this.showSku.bind(undefined, 'addToCart')}
  onPurchase={this.showSku.bind(undefined, 'purchase')}
/>
```

**期望行为**
生成两个不同的函数，每个的参数都不同。

**报错信息**
无报错，但是与期望行为不一致，最终只会生成同一个参数一样的函数，后面的`bind`会把前面的覆盖掉， 最终生成的函数为最后一次`bind`的结果。

即对于上述代码：无论触发`onAddToCart`事件还是`onPurchase`事件，`showSku`函数接收到的参数始终是`purchase`。

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.0.beta.7
 - Node.js 版本 v8.11.2

**补充信息**

**Comment by Simbachen** [comment]
当前版本同一个事件处理函数在同一个组件上多次绑定，如果有用到xx.bind(this, args)的方式来传参，则参数会冲突。
建议暂时先通过1、在组件里调用的时候才传参，或2、定义两个方法showSkuA，showSkuB 来规避这个问题

**Comment by Chen-jj** [comment]
[fix(taro-weapp/alipay/swan/tt/): 小程序端支持在组件上绑定 bind 不同参数的同一回调函数](https://github.com/NervJS/taro/commit/38ce066e69e0a5f7ffe2aeae1c4059f1ef575e31)
