### ISSUE TITLE
Error: 以 render 开头的类函数必须返回 JSX，否则会导致渲染失败。如果是为了渲染字符串，建议更名

### ISSUE THREAD

**Issue by tianleiyiji123** [NervJS/taro#4321]
**问题描述**
[问题描述：原生小程序转taro的时候报：Error: 以 render 开头的类函数必须返回 JSX，否则会导致渲染失败。如果是为了渲染字符串，建议更名]

**复现步骤**
[复现问题的步骤]
1. 原生小程序转taro

错误  页面编译  页面G:\kidsStudy\giftcard-mp\taroConvert\src\common\pages\shop-list\index编译失败！
Error: 以 render 开头的类函数必须返回 JSX，否则会导致渲染失败。如果是为了渲染字符串，建议更名。
以 VSCode 为例：右键点击选择方法名，点击 rename symbol（重命名符号），输入新方法名。

**补充信息**
因为方法里面含有render字符串只要把方法名更换就好
比如方法：renderItem换个其他的就好

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/d0e0343844a1fe16b6975f53c7de396aeb7036f1
