### ISSUE TITLE
编译器无法将组件的.wxs文件复制到/dist相应目录下

### ISSUE THREAD

**Issue by mihuartuanr** [NervJS/taro#4325]
当前环境`@tarojs/cli1.3.13`

**问题描述**

编译器无法将组件的`.wxs`文件复制到`/dist`相应目录下，导致`.wxml`加载不到相应的`.wxs`文件。

同[#3885](https://github.com/NervJS/taro/issues/3885)...

**Comment by Chen-jj** [comment]
same issue

**Comment by mihuartuanr** [comment]
@Chen-jj 是同样的问题，可没看到解决方案...

大概还要等多久呢?
