### ISSUE TITLE
componentDidCatchError微信正常  支付宝捕获不到错误

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#4329]
页面主动抛出错误：
>  let n = null
    console.log('n:',n.charAt(5))

app.js中;

> componentDidCatchError(err) {
        console.log('componentDidCatchError:',err)
    }

**问题描述**
以上代码运行会报错，微信能在`componentDidCatchError`中捕获到，支付宝不行
**但是报错的代码 在支付宝原生的onError是能捕获到的**

**期望行为**
支付宝能捕获异常

**报错信息**
![image](https://user-images.githubusercontent.com/36951996/63904642-5427eb80-ca44-11e9-870d-8a3a92a663c2.png)
这是支付宝ide捕获的错误日志

**系统信息**
> 
![image](https://user-images.githubusercontent.com/36951996/63904629-483c2980-ca44-11e9-935f-b4dbeb9e399b.png)

**补充信息**
支付宝没做适配？

**Comment by Chen-jj** [comment]
@fanlvwen 复现不了

![image](https://user-images.githubusercontent.com/11807297/63910128-09b06a00-ca58-11e9-8e6b-f222d29283aa.png)

![image](https://user-images.githubusercontent.com/11807297/63910159-2b115600-ca58-11e9-8bad-b30d595987bf.png)

**Comment by fanlvwen** [comment]
[test.zip](https://github.com/NervJS/taro/files/3554165/test.zip)
@Chen-jj 
这是新建的一个测试项目，run dev:alipay之后是抓取不到的，麻烦帮忙看一下

我发现我的支付宝控制台打印的ap/SDKVersion:是1.3.15   你的是1.18.3，这个是在哪里改的

**Comment by fanlvwen** [comment]
更新到支付宝最新ide  能捕获异常了
