### ISSUE TITLE
h5端 Canvas组件，canvasId设置为动态时，无法编译出对应的ref

### ISSUE THREAD

**Issue by daledelv** [NervJS/taro#4337]
**问题描述**
h5端 Canvas组件，canvasId设置为动态时，无法编译出对应的ref

**复现步骤**
例
```js
{this.state.banners.map((item, index) => (
  <SwiperItem className='SwiperItem' key={item}>
    <Canvas
      canvasId={`share_canvas${index}`}
      className='share_canvas'
    />
  </SwiperItem>
))}
```
.temp内编译出的文件没有ref

**期望行为**
期望支持动态

**系统信息**
Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.13 => 1.3.13
      @tarojs/cli: 1.3.13 => 1.3.13
      @tarojs/components: 1.3.13 => 1.3.13
      @tarojs/plugin-babel: 1.3.13 => 1.3.13
      @tarojs/plugin-csso: 1.3.13 => 1.3.13
      @tarojs/plugin-sass: 1.3.13 => 1.3.13
      @tarojs/plugin-uglifyjs: 1.3.13 => 1.3.13
      @tarojs/rn-runner: 1.3.13 => 1.3.13
      @tarojs/router: 1.3.13 => 1.3.13
      @tarojs/taro: 1.3.13 => 1.3.13
      @tarojs/taro-alipay: 1.3.13 => 1.3.13
      @tarojs/taro-h5: 1.3.13 => 1.3.13
      @tarojs/taro-swan: 1.3.13 => 1.3.13
      @tarojs/taro-tt: 1.3.13 => 1.3.13
      @tarojs/taro-weapp: 1.3.13 => 1.3.13
      @tarojs/webpack-runner: 1.3.13 => 1.3.13
      eslint-config-taro: 1.3.13 => 1.3.13
      eslint-plugin-taro: 1.3.13 => 1.3.13
      nerv-devtools: ^1.4.3 => 1.4.3
      nervjs: ^1.4.3 => 1.4.3
    npmGlobalPackages:
      typescript: 3.2.2

**补充信息**
目前手动添加了ref={ref => (this[`__taroref_share_canvas${index}`] = ref)}以解决问题

**Comment by tourze** [comment]
请问这个问题有进度了吗

**Comment by tourze** [comment]
我贴下我的解决方案，我是在app.js中根据当前环境，覆盖了createCanvasContext。
H5下的canvas context支持程度跟微信小程序不太一致，根据实际报错，自己补充下类似setFillStyle这种兼容函数就好了

```
    // Taro.createCanvasContext 在H5下的兼容
    Taro.__h5__createCanvasContext = Taro.createCanvasContext;
    Taro.createCanvasContext = (canvasId) => {
      // H5环境下，taro原来的根据canvasid获取，方式是有问题的，只能在这里做下兼容，同时这样写就要求canvas那边要加多个id参数
      const ctx = document.getElementById(canvasId).getElementsByTagName('canvas')[0].getContext('2d');
      ctx.setFillStyle = (val) => {
        ctx.fillStyle = val;
      };
      ctx.draw = (reserve, callback) => {
        // reserve 本次绘制是否接着上一次绘制。即 reserve 参数为 false，则在本次调用绘制之前 native 层会先清空画布再继续绘制；若 reserve 参数为 true，则保留当前画布上的内容，本次调用 drawCanvas 绘制的内容覆盖在上面，默认 false。
        callback && setTimeout(callback, 20);
      };
      return ctx;
    };
```

**Comment by Chen-jj** [comment]
可以升级到 Taro 3 再试试
