### ISSUE TITLE
h5 地址栏回退 document.title问题

### ISSUE THREAD

**Issue by manwuyu** [NervJS/taro#4338]
h5端，（微信内部没有问题，其他浏览器都有问题）
A页面的componentDidMount里面修改document.title =A
B页面的 componentDidMount里面修改document.title =B
从A页面进入B页面, document.title修改成功
从B页面（手机回退）返回A页面 document.title未修改，componentDidMount也没有触发，其他的生命周期方法都没有触发

有什么方法可以触发吗

**Comment by luckyadam** [comment]
回退后 A 页面的 `componentDidShow` 没触发么

**Comment by Littly** [comment]
页面后退触发的是`componentDidShow`。
