### ISSUE TITLE
[小程序]:枚举渲染时，组件无法加载

### ISSUE THREAD

**Issue by fyang0728** [NervJS/taro#4343]
**问题描述**
小程序端在使用枚举渲染组件的时候，无法正常的将组件渲染出来。需要把键值换成字符串才能正常渲染。
h5端可以正常渲染

**复现步骤**

```js
// 这种情况下，在小程序中组件是无法渲染的
{
  {
    ComA: <ComA options={options} />,
    ComB: <ComB options={options} />
   }[is]
}

// 这种情况下，在小程序中可以正常渲染
{
  {
    'ComA': <ComA options={options} />,
    'ComB': <ComB options={options} />
   }[is]
}
```

**期望行为**
希望可以不用加单引号，否则格式化代码时会不小心去掉

**系统信息**
Taro CLI 1.3.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

 - 报错平台 [ weapp]

**Comment by yuche** [comment]
应该是键名，我之前也口误了……

**Comment by shichaohui** [comment]
这问题都大半年了，还没解决。

**Comment by shenghanqin** [comment]
@shichaohui 你可以选择在等着taro next 3版本去玩react版本，其实小程序里面限制特别多，干嘛要这么放飞自我呢？嘻嘻

**Comment by shichaohui** [comment]
> @shichaohui 你可以选择在等着taro next 3版本去玩react版本，其实小程序里面限制特别多，干嘛要这么放飞自我呢？嘻嘻

小程序的坑是真的多，这也不行那也不行的。

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
