### ISSUE TITLE
component.$scope.setData( dataDiff, cb)引起的数据异常

### ISSUE THREAD

**Issue by zzyhdu** [NervJS/taro#4344]
**问题描述**
本问题是接https://github.com/NervJS/taro/issues/3927的，通过log发现在component.$scope.setData( dataDiff, cb)运行过后，component的props出现异常。

**复现步骤**

[复现问题的步骤]
数据源来自websocket，收到event之后更新magnet,redux以数组的形式存放magnet
一下提供了去掉setData和未去掉的对比

![image](https://user-images.githubusercontent.com/4222224/63990024-ffa07100-cb14-11e9-8beb-1262c7b65e53.png)
![image](https://user-images.githubusercontent.com/4222224/63990049-19da4f00-cb15-11e9-8d6d-f771eb583323.png)
![image](https://user-images.githubusercontent.com/4222224/63990421-8a35a000-cb16-11e9-95d3-1d516ea6694d.png)
![image](https://user-images.githubusercontent.com/4222224/63990426-8e61bd80-cb16-11e9-9d7c-e66f799be1d1.png)

**期望行为**
数据正确。希望提供解题思路

**系统信息**

![image](https://user-images.githubusercontent.com/4222224/63990569-0af49c00-cb17-11e9-8ea3-b36d9e6d2a48.png)

**补充信息**

**Comment by zzyhdu** [comment]
ps，在去掉setData时候的log
![image](https://user-images.githubusercontent.com/4222224/63990638-573fdc00-cb17-11e9-86d8-c6406d984f09.png)

**Comment by John251314** [comment]
遇到了同样的问题，使用redux管理数据，在更新数据之后，追踪到doUpdate后数据异常，坑死了

**Comment by Chen-jj** [comment]
@zzyhdu 大概猜到问题所在，试试两种方法： `component.$scope.setData(dataDiff, cb)` 这里。

1. dataDiff 改为 data，不用 diff 后的数据。
2. `JSON.parse(JSON.stringify(dataDiff))` 先序列化 setData 的数据。

然后你需要提供完整可复现代码，文本格式。
