### ISSUE TITLE
taro下typescript无法检测错误？

### ISSUE THREAD

**Issue by BUPTlhuanyu** [NervJS/taro#4348]
**问题描述**
基于typescript的taro官方示例中，interface state中与组件中的state的数据不一致，编译也通过了，并且不会进行预编译报错提示。

**复现步骤**
[复现问题的步骤]
1. 在目录下taro init taro-t1创建项目
2. 提示是否需要使用typescript的时候，选择是
3. 来到 taro-t1目录下，修改taro-t1\src\pages\index\index.tsx如下：
```
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'

interface State{
  // list: any[]
}

interface Props{}

export default class Index extends Component<Props, State> {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
  config: Config = {
    navigationBarTitleText: '首页'
  }

  state = {
    list: [
      {selected: true,text: 'one'},
      {selected: true,text: 'two'},
      {selected: true,text: 'three'}
    ]
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    const list = this.state.list
        .filter(l => l.selected)
        .map(l => {
          return <li key={l.text}>{l.text}</li>
        })
    return (
      <View className='index'>
        {list}
        <Text>Hello world!</Text>
      </View>
    )
  }
}

```

4. npm run dev:h5编译通过，貌似这里的typescript是个摆设？

**期望行为**
typescript检查出错，编译不通过

**报错信息**

无，编译成功

**系统信息**
👽 Taro v1.3.15

  Taro CLI 1.3.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
无

**Comment by yuche** [comment]
编译器是不会检查类型错误的，如果你需要检查可以自行加一个 tsc 命令在 `npm run build` 之前。

**Comment by BUPTlhuanyu** [comment]
嗯，taro现在是不能实时的检测ts的类型错误，希望增加功能，像create-react-app一样，增加ts的实时检测功能。最新的create-react-app利用fork-ts-checker-webpack-plugin并增加ts-pnp对文件的resolve做了优化，是否也可以考虑一下这个？

**Comment by BUPTlhuanyu** [comment]
您好，tsc也不管用，在类型有错误的时候，依旧可以编译通过，是否可以效仿create-react-app加上ts-pnp，fork-ts-webpack-plugin在ts类型出错的时候终端项目的编译？
