### ISSUE TITLE
typescript模板eslint不起作用

### ISSUE THREAD

**Issue by sankincn** [NervJS/taro#4349]
**问题描述**
eslint不起作用

**复现步骤**
1. taro init初始化项目，选择typescript模板
2. 运行项目，会检查typescript语法错误，但eslint不起作用，不检查代码风格、代码报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm

 - 操作系统: [e.g. Windows 10]
mac
 - Taro 版本 [e.g. v.0.0.64]
1.3.13
 - Node.js 版本 [e.g. v9.0.0]
10.16.0
 - 报错平台 [h5, weapp]
weapp

**Comment by yuche** [comment]
你用 eslint 命令检查是可以的，编辑器不检查是因为你的插件没有开启检查 tsx 文件。

**Comment by sankincn** [comment]
好的 我以为cli里面会默认开启ts文件的校验，我现在是在命令行自己配置eslint要检查的文件后缀
