### ISSUE TITLE
升级到1.3.16后item is not defined错误

### ISSUE THREAD

**Issue by Jiang-Rain** [NervJS/taro#4359]
**问题描述**
把@tarojs/cli升级到1.3.16后
![image](https://user-images.githubusercontent.com/27628585/64087852-5f935380-cd71-11e9-8b8a-81e6d369b659.png)
![image](https://user-images.githubusercontent.com/27628585/64087879-789c0480-cd71-11e9-9f06-7f98256771be.png)
![image](https://user-images.githubusercontent.com/27628585/64087891-8b163e00-cd71-11e9-999c-151ad8e90965.png)
![image](https://user-images.githubusercontent.com/27628585/64087912-98cbc380-cd71-11e9-94c8-c683942857b4.png)
1.3.15之前都没事，升级后就报item is not defined错误

**系统信息**
Taro CLI 1.3.16 environment info:
System:
OS: macOS 10.14.6
Shell: 5.3 - /bin/zsh
Binaries:
Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
npm: 6.11.2 - ~/.nvm/versions/node/v10.16.2/bin/npm

**Comment by b1ngx** [comment]
升级 1.3.16 后，列表循环都报错了

**Comment by tommytroylin** [comment]
+1

1.3.15 无问题。 1.3.16  jsx 里使用到 map 的地方都报错

**Comment by dreamthen** [comment]
+1
taro-ui的AtTabBar的item部分,还有export default部分也有报错
