### ISSUE TITLE
百度小程序使用map返回组件时出错

### ISSUE THREAD

**Issue by kk412027247** [NervJS/taro#4361]
**问题描述**
百度小程序使用map返回组件时出错

**复现步骤**
数组用map方法，返回组件的时候出错

```js
import Taro, {Component} from '@tarojs/taro'
import {View,} from '@tarojs/components'
import ListItem from './listItem/listItem'

import './index.scss'

const list = [111, 222, 333];


class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  };

  render() {
    return (
      <View className='index'>

        {
          list.map(item => <ListItem item={item} key={item} />)
        }
      </View>
    )
  }
}

export default Index


```

这个项目 https://github.com/kk412027247/swan-app

**期望行为**
希望可以顺利渲染出组件

**报错信息**

![0A3142A7-8F15-4245-A284-24E352CA6467](https://user-images.githubusercontent.com/30715186/64092330-fb7b8a00-cd86-11e9-8bbc-7d1077069254.png)

**系统信息**

 - 操作系统: [ Windows 10]
 - Taro 版本 [1.3.16]
 - Node.js 版本 [10.15.3]
 - 报错平台 [ swan]

**Comment by Chen-jj** [comment]
@kk412027247 CLI 和依赖都升级到 1.3.17 再试试

![image](https://user-images.githubusercontent.com/11807297/64153556-b4ae9280-ce61-11e9-9af2-b71dea2ea42a.png)

**Comment by kk412027247** [comment]
升级到 1.3.17 顺利通过
