### ISSUE TITLE
H5 项目AtInput 类型为text时，系统自带九宫格拼音输入法 光标跳动

### ISSUE THREAD

**Issue by guangzhuo** [NervJS/taro#4364]
问题描述：
H5 页面当input为text类型时，点击弹出系统自带九宫格输入法，选择拼音时，连续多次输入字符时，光标会往前跳，无法定位到最后；

[复现问题的步骤]
1. 点击输入框为text类型的input
2. 切换成系统自带的九宫格
3. 在选择拼音
4. 连续多次点击输入后 光标来回跳动

```
       <AtInput
          name={`codeInput${this.props.key}`}
          title={<Image className='inputImg' src={login04} />}
          type='text'
          placeholder='请输入短信验证码'
          value={this.state.captcha.inputCapCode}
          onChange={(value) => { this.CapCodeChange(value) }}
        >
          <View
            className='code'
            onClick={()=> this.openModel(this.props.phone)}
          >{this.state.captcha.countDown}</View>
        </AtInput>
 ```

**期望行为**
光标不跳动，始终定位在最后方

**报错信息**
![text(1)](https://user-images.githubusercontent.com/24909534/64103982-e2ce9c80-cda5-11e9-9ebe-15de73bd10f6.jpg)

**系统信息**
 Taro v1.3.4
  Taro CLI 1.3.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 -
      Yarn: 1.15.2 
      npm: 6.4.1

**Comment by jinjinjin0731** [comment]
type='codeInput' ?

**Comment by guangzhuo** [comment]
> type ='codeInput'？这是啥类型
这里是我测试随便写的一个字符，现在改成text了， 还是会出现跳动的问题

**Comment by 15700353375** [comment]
遇到同样的问题了，请问解决办法是？

**Comment by crimson968** [comment]
请问这个问题有解决吗，好像是光标跳转BUG导致的

**Comment by guangzhuo** [comment]
> 请问这个问题有解决吗，好像是光标偏移BUG导致的

这个问题，在H5下用原生input没有这个问题，我看过其他H5的页面，没发现这样的问题，taro组件不知道是什么原因会一直跳动

**Comment by crimson968** [comment]
@guangzhuo 原生的没有，因为原生的没有对Ios端的光标跳转做特殊处理，taro input代码里对ios光标处理的代码导致了这个issue所针对的问题·

**Comment by LixingY** [comment]
请问这个问题解决了吗，我也遇到了，taro版本1.3.20 ios 13.3.1 微信版本7.0.11

**Comment by wbbw007** [comment]
我也遇到了相同的问题，是否有提供解决方法

**Comment by broccoli77** [comment]
同问，请问如何解决该问题？
taro版本2.2.6 ios版本12.4.3 微信版本7.0.12

**Comment by guangzhuo** [comment]
1.基于业务封装h5 input组件，避免上述问题（缺点是  改的有点多）；
2.试着安装更高的版本，（但是2.X版本一样有问题）；
3.找产品商量吧，就看你的魅力牛批不牛批了；

**Comment by crimson968** [comment]
我在自定义的onchange事件里处理了光标逻辑，解决了这个问题

**Comment by zhangxiangliang** [comment]
> 我在自定义的onchange事件里处理了光标逻辑，解决了这个问题

小哥哥请问具体如何解决？
