### ISSUE TITLE
微信小程序的scrollView 触发不了下拉刷新

### ISSUE THREAD

**Issue by cdd111** [NervJS/taro#4365]
**问题描述**
[微信小程序的scrollView 触发不了下拉刷新]

**复现步骤**
写一个scrollView组件，下拉刷新
![图片](https://user-images.githubusercontent.com/12994339/64104584-13630600-cda7-11e9-9c7f-7ce164e4d2ef.png)
已经设置好scrollView高度
![图片](https://user-images.githubusercontent.com/12994339/64104288-8f108300-cda6-11e9-81ce-e28598ca1b89.png)

```js

// 这里可以贴代码
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
<ScrollView
          className='scrollview'
          scrollY
          scrollWithAnimation
          scrollTop={Math.random()}
          style={scrollStyle}
          lowerThreshold={Threshold}
          upperThreshold={Threshold}
          onScrollToLower={this.onScrollToLower.bind(this)}
        >
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
能下拉刷新

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 1.3.10
 - Node.js 版本 10.15.3
 - 报错平台weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
你的意思是触发不了 onScrollToLower 么。 给了具体高度吗

**Comment by cdd111** [comment]
> 
> 
> 你的意思是触发不了 onScrollToLower 么。 给了具体高度吗

对，找到原因了，高度没加单位
谢谢回复 我关掉这个issue

**Comment by Chen-jj** [comment]
@cdd111 什么下拉刷新，你是不是 `onScrollToUpper` 写成 `onScrollToLower`
