### ISSUE TITLE
http401错误不进入catch分支

### ISSUE THREAD

**Issue by clarktang** [NervJS/taro#437]
**问题描述**
访问一个接口，接口返回401错误，这时候Taro.request的catch并没有触发，而是进入了正常的then流程。
<img width="442" alt="wx20180808-201819 2x" src="https://user-images.githubusercontent.com/37982974/43836700-c31a83d0-9b48-11e8-9bd7-1aedd5909556.png">
![wx20180808-201855](https://user-images.githubusercontent.com/37982974/43836707-c764fd6c-9b48-11e8-8f98-6ffb23a488dc.png)
![wx20180808-201842](https://user-images.githubusercontent.com/37982974/43836713-cc2bd104-9b48-11e8-8359-f2efd5031eb8.png)

**期望行为**

401错误应该进入catch分支

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统:macos
 - Taro 版本1.0.0beta.2
 - Node.js 版本 10.6.0

**Comment by zacksleo** [comment]
![image](https://user-images.githubusercontent.com/3369169/43838162-267ceba8-9b4d-11e8-880d-34914a3639e9.png)

**Comment by kennylbj** [comment]
404也不进入呀，这样的设计很不合理。

**Comment by zacksleo** [comment]
有啥不合理的，400以上代码是一大类

**Comment by kennylbj** [comment]
自己封装一个request吧，把code不是200多的请求都throw error

**Comment by DrakeXiang** [comment]
@zacksleo 支付宝下401是走的catch，太坑了

**Comment by kennylbj** [comment]
反人类设计
