### ISSUE TITLE
添加pull-up-refresh功能

### ISSUE THREAD

**Issue by neuyu** [NervJS/taro#4370]
**问题描述**
pull-down-refresh改为pull-to-refresh，支持上拉加载。现在的上拉加载，只能通过scrollview，自己根据touch事件来实现吗？

**期望行为**
scrollview提供上拉加载，下拉刷新能力，类如rn的RefreshControl

```
<ScrollView
    refreshControl={
         <RefreshControl
               refreshing={this.state.refreshing}
               onRefresh={this._onRefresh}
         />
    }
       ...
/>
```

**Comment by ZakaryCode** [comment]
可以参考文档 [页面事件处理函数](https://nervjs.github.io/taro/docs/tutorial.html#%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0)

**Comment by neuyu** [comment]
> 可以参考文档 [页面事件处理函数](https://nervjs.github.io/taro/docs/tutorial.html#%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0)

你说的这个是针对小程序的事件回调，但是我们希望支持H5端

**Comment by dedeyi** [comment]
H5端现在的下拉刷新针对的是整个页面，下拉时候通过transform是整个页面下移，会导致页面固定元素比如：导航条、悬浮按钮一起被下拉移动，交互很不友好。
而下拉场景其实很多是针对某个视图内的下拉交互，所以我觉得给 scrollview 提供下拉刷新功能很有必要。
