### ISSUE TITLE
 app.jsx中pages引用一直值会出错

### ISSUE THREAD

**Issue by jinyang1994** [NervJS/taro#4371]
**问题描述**
在`app.jsx`中配置pages时，如果pages中引用标量，会提示`src/undefined`没有找到

**复现步骤**

```js
const HOME_PAGE = 'pages/index/index';
const DETAIL_PAGE = 'pages/detail/index';

class App extends Component {
  config = {
    pages: [
      HOME_PAGE,
      DETAIL_PAGE,
    ],
  }
}
```

**期望行为**
可以正常指向页面

**报错信息**

但是现在提示的都是`src/undefined` 不存在！

**系统信息**

System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.13 => 1.3.13 
      @tarojs/components: 1.3.13 => 1.3.13 
      @tarojs/plugin-babel: 1.3.13 => 1.3.13 
      @tarojs/plugin-csso: 1.3.13 => 1.3.13 
      @tarojs/plugin-less: 1.3.13 => 1.3.13 
      @tarojs/plugin-uglifyjs: 1.3.13 => 1.3.13 
      @tarojs/redux: 1.3.13 => 1.3.13 
      @tarojs/redux-h5: 1.3.13 => 1.3.13 
      @tarojs/router: 1.3.13 => 1.3.13 
      @tarojs/taro: 1.3.13 => 1.3.13 
      @tarojs/taro-alipay: 1.3.13 => 1.3.13 
      @tarojs/taro-h5: 1.3.13 => 1.3.13 
      @tarojs/taro-swan: 1.3.13 => 1.3.13 
      @tarojs/taro-tt: 1.3.13 => 1.3.13 
      @tarojs/taro-weapp: 1.3.13 => 1.3.13 
      @tarojs/webpack-runner: 1.3.13 => 1.3.13 
      eslint-config-taro: 1.3.13 => 1.3.13 
      eslint-plugin-taro: 1.3.13 => 1.3.13 
      nerv-devtools: ^1.4.0 => 1.4.3 
      nervjs: ^1.4.0 => 1.4.3 
      stylelint-config-taro-rn: 1.3.13 => 1.3.13 
      stylelint-taro-rn: 1.3.13 => 1.3.13

**补充信息**

**Comment by luckyadam** [comment]
是的，这个现在支持不了

**Comment by jinyang1994** [comment]
好的，那我先关了
