### ISSUE TITLE
quickstart， npm run build:weapp报错Maximum call stack size exceeded

### ISSUE THREAD

**Issue by waahai** [NervJS/taro#4373]
C:\workspace\myproj4>npm run build:weapp

> myproj4@1.0.0 build:weapp C:\workspace\myproj4
> taro build --type weapp

� Taro v1.3.17

开始编译项目 myproj4
(node:27916) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RangeError: Maximum call stack size exceeded
(node:27916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Chen-jj** [comment]
@waahai 详细描述一下你的操作步骤

**Comment by luckyadam** [comment]
依赖没有安装
