### ISSUE TITLE
HOOK  useRef   current的值拿不到，  

### ISSUE THREAD

**Issue by lfxlove** [NervJS/taro#4374]
`function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    console.log(inputEl.current) // ---> null
    inputEl.current.focus(); // 报错了
  };
  return (
    <View>
      <Input ref={inputEl} type="text" />
      <Button onClick={onButtonClick}>Focus the input</Button>
    </View>
  );
}`

**Comment by Chen-jj** [comment]
@lfxwoaini 请按 issue 模板提供一切必要信息。
