### ISSUE TITLE
【快应用】路由跳转API不支持相对路径，需要绝对化

### ISSUE THREAD

**Issue by Qiyu8** [NervJS/taro#4375]
问题描述
Taro中a.jsx写法如下：
```
bindViewTap = () => {
  Taro.navigateTo({
     url: '../location/location'
  })
}
```

在转为快应用之后，触发bindViewTap之后没有跳转到location页面

复现步骤
1.编写包含相对路径的泰罗程序
2.执行taro build --type quickapp

期望行为
taro运行时会将相对路径转换为绝对路径，因为快应用只支持类似于/pages/location/location的路径

报错信息
无响应

系统信息
操作系统: Windows 10
Taro 版本 v1.3.17
Node.js 版本 v12.7.0
报错平台 weapp
补充信息
经过试验，reLaunch、switchTab和redirectTo也存在这个问题

**Comment by jiongrui** [comment]
这个问题似乎没解决啊，啥时候能解决一下呢？
