### ISSUE TITLE
Audio在h5端onError无法捕获错误,小程序端却可以

### ISSUE THREAD

**Issue by mraiguo** [NervJS/taro#4378]
**问题描述**

Audio在h5端onError无法捕获错误,小程序端却可以

**复现步骤**
[复现问题的步骤]
1. 使用Taro.createInnerAudioContext()创建一个audio实例
2. 填加一个不支持的格式链接
3. 添加错误处理函数
4. 播放音频

```js

    const audioEl = Taro.createInnerAudioContext()
    audioEl.src = 'http://gcdncs.101.com/v0.1/static/fish/media/ring.amr'
    audioEl.onError(function (e) {
      console.log('发生错误:', e)
    })
    audioEl.play()

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
和小程序端一样能够抛出错误信息
![image](https://user-images.githubusercontent.com/22299421/64152804-ee7e9980-ce5f-11e9-91af-21ffaad7f80e.png)
h5端无法捕获异常,只能浏览器抛出错误
![image](https://user-images.githubusercontent.com/22299421/64152908-2f76ae00-ce60-11e9-9af5-e08868a44c41.png)

**系统信息**
 - 操作系统: [e.g. Windows 10]
Windows 10
 - Taro 版本 [e.g. v.0.0.64]
 v1.3.11

 - Node.js 版本 [e.g. v9.0.0]
8.10.0
 - 报错平台 [h5, weapp]
h5

**Comment by targeral** [comment]
这个大概要什么时候解决，也遇到这种问题了。

**Comment by shenghanqin** [comment]
看了源码，按说是有抛错的。

```js
  // 1网络错误, 2解码错误, 3解码错误，4 不合适资源
    this.audio.addEventListener('error', (e) => {
      Object.defineProperty(e, 'detail', {
        enumerable: true,
        value: {errMsg: e.srcElement.error.code}
      })
      this.props.onError && this.props.onError(e)
    })
```
