### ISSUE TITLE
文档搜索框背景色与文字相同

### ISSUE THREAD

**Issue by ASkyBig** [NervJS/taro#4380]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
文档搜索框背景色与文字相同

**复现步骤**
[复现问题的步骤]
1. 浏览器打开链接： https://nervjs.github.io/taro/docs/static-reference.html
2. 点击搜索，输入文字
3. 无法看到文字

**期望行为**

看到文字
**报错信息**

看不到文字
![image](https://user-images.githubusercontent.com/26340566/64157013-749ede00-ce68-11e9-8f5c-b9a752774d39.png)
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS Mojave]
 - 报错平台 [Chrome 浏览器 版本 76.0.3809.132（正式版本） （64 位）]

**补充信息**
应该是文字颜色设置成了白色

**Comment by Pines-Cheng** [comment]
已 fix ，感谢反馈～
