### ISSUE TITLE
头条小程序不支持async/await 语法（真机）

### ISSUE THREAD

**Issue by kk412027247** [NervJS/taro#4382]
**问题描述**
已经引入 **@tarojs/async-await**，版本: `1.3.17`，
但是在真机上，头条小程序不支持 async/await语法；

**复现步骤**

```
export const asyncAdd = () => async (dispatch)=> {
  setTimeout(() => {
    dispatch(add())
  }, 2000)
};

```

在模拟器上运行正常，但是在真机上就报错了，IOS与Android 都报错
项目代码 https://github.com/kk412027247/tt-app

![微信图片_20190903185218](https://user-images.githubusercontent.com/30715186/64167476-fcdaae80-ce7b-11e9-935f-3a35ab93b914.jpg)
![微信图片_20190903185214](https://user-images.githubusercontent.com/30715186/64167477-fd734500-ce7b-11e9-8b45-c3f0418334cd.png)

**期望行为**
在真机上也能运行async/await语法

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [v 1.3.17]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [tt]

**Comment by Chen-jj** [comment]
@kk412027247 头条真机 global 对象内属性不能直接作为全局属性获取，和模拟器表现不符，正在与头条方面协商，暂时不要用 async await 吧。

**Comment by shenghanqin** [comment]
我做抖音小程序中没碰到类似的问题。我是感觉还好，可以给字节跳动提bug。嘻嘻
