### ISSUE TITLE
ScrollView指定onTouchMove后，无法正常滑动

### ISSUE THREAD

**Issue by yerphon** [NervJS/taro#4384]
**问题描述**
为ScrollView指定onTouchMove后，无法正常滑动

**复现步骤**
1. 使用ScrollView的时候属性onTouchMove={this.handleScrollViewMove}

2.  ```handleScrollViewMove = e => {
    console.log('handleScrollViewMove')
    if (this.state.open) { 
      console.log('open'); 
      e.stopPropagation();
    }else{
      console.log('close'); 
    }

3. 此时open数值是false,然而此时无法滑动ScrollView了，按道理是不应该执e.stopPropagation();
![image](https://user-images.githubusercontent.com/7892904/64188379-dda44700-cea4-11e9-9f81-4ac0017ae06a.png)

4.  整体设置 

<ScrollView
     className='scrollview'
     enableBackToTop
     onTouchMove={this.handleScrollViewMove}
            >

**期望行为**
希望可以用open来控制ScrollView可以滑动跟禁止滑动的状态切换

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 V1.3.11
 - Node.js 版本10.16.1
 - 报错平台 Weapp

**Comment by Chen-jj** [comment]
@yerphon 你看看编译后的 wxml，小程序中没有 `e.stopPropagation()`，所以遇到它会把 bindtap 换成 catchtap，因此要看编译后的模板是否正确。

**Comment by yerphon** [comment]
> @yerphon 你看看编译后的 wxml，小程序中没有 `e.stopPropagation()`，所以遇到它会把 bindtap 换成 catchtap，因此要看编译后的模板是否正确。

感谢回复，我看到是有catchtouchmove="handleScrollViewMove"这行的。
已找到解决方法，非BUG。

**Comment by Chen-jj** [comment]
@yerphon 通过控制 scrollY 属性来控制是否可以滚动，不要用 onTouchMove
