### ISSUE TITLE
调用Taro.addInterceptor后再调用的Taro.request返回的requestTask就没有abort()方法了

### ISSUE THREAD

**Issue by TigerHee** [NervJS/taro#4386]
**问题描述**
调用Taro.addInterceptor后再调用的Taro.request返回的requestTask就没有abort()方法了

**复现步骤**
[复现问题的步骤]
1. 在任意组件的componentDidMount周期内调用Taro.request调试

```js
场景1不调用addInterceptor：
componentDidMount() {
    // Taro.addInterceptor(Taro.interceptors.timeoutInterceptor)
    const requestTask = Taro.request({
      url: 'test.php', //仅为示例，并非真实的接口地址
      data: {
        x: '' ,
        y: ''
      },
      header: {
        'content-type': 'application/json'
      },
      success (res) {
        console.log(res.data)
      }
    })
    console.log('requestTask === ', requestTask)
  }
得到结果：
requestTask内有abort方法

场景2先调用addInterceptor：
componentDidMount() {
    Taro.addInterceptor(Taro.interceptors.timeoutInterceptor)
    const requestTask = Taro.request({
      url: 'test.php', //仅为示例，并非真实的接口地址
      data: {
        x: '' ,
        y: ''
      },
      header: {
        'content-type': 'application/json'
      },
      success (res) {
        console.log(res.data)
      }
    })
    console.log('requestTask === ', requestTask)
  }
得到结果：
requestTask没有abort方法


```

**期望行为**
即使调用addInterceptor也能返回abort

**报错信息**
调用addInterceptor：
![微信图片_20190904142027](https://user-images.githubusercontent.com/15956567/64230353-3c0e0b80-cf1f-11e9-8a4c-389b71b02075.png)
不调用addInterceptor：
![微信图片_20190904142041](https://user-images.githubusercontent.com/15956567/64230366-44664680-cf1f-11e9-9ac0-f296e9dba61e.png)

**系统信息**
 Taro CLI 1.3.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.10.0 
      Yarn: 1.12.3
      npm: 5.6.0

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by 1995lk** [comment]
返回的是promise  用.then()
