### ISSUE TITLE
Swiper 我看代码有一个问题。

### ISSUE THREAD

**Issue by zsirfs** [NervJS/taro#4387]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

swiper 更新代码:
https://github.com/NervJS/taro/blob/master/packages/taro-components/src/components/swiper/index.js#L111
![image](https://user-images.githubusercontent.com/22249411/64230769-48469880-cf20-11e9-86bf-9f1c0866376f.png)

更新current，修改swiper代码，问题如果current如果是0，当前会更新为0嘛？我看到this._$current为上一个下标，根本可能为0.所以每次current修改为0 的时候，swiper不会变化。

这个问题我给 @luckyadam 发过邮件咨询，至今没有回应。麻烦请代码review一下。

![image](https://user-images.githubusercontent.com/22249411/64230866-92c81500-cf20-11e9-89b5-532d6e2573fc.png)

每次都需要这样写hack，很丑。

**期望行为**
swiper 的current可以从1 变化到0

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10] macos 10.14
 - Taro 版本 [e.g. v.0.0.64] 1.3.13
 - Node.js 版本 [e.g. v9.0.0] 10.13
 - 报错平台 [h5, weapp] h5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zsirfs** [comment]
这个问题是一个月前就发现了。而且主要维护者发过邮件。没得回应，我看到代码至今没有修改，求回应。

**Comment by zsirfs** [comment]
上面hack，除了使用ref外，要么需要current不为数字0即可

**Comment by Qiyu8** [comment]
这个问题比较明显，可以提个PR了

**Comment by zsirfs** [comment]
额。如果是这样的话
![image](https://user-images.githubusercontent.com/22249411/64252015-6a561000-cf4c-11e9-9548-efbb86e74a69.png)

两个月前。这是主维护者嘛？难道从来不看邮件嘛？很尴尬。一直关注项目发展，发现一直没改。看到这里判断写的很多，要做什么特别的逻辑嘛？可以找对应的维护者沟通一下。我这里不提pr。主要让你们知道一下即可。

**Comment by zsirfs** [comment]
@Qiyu8 感谢回复
