### ISSUE TITLE
输出两遍 props

### ISSUE THREAD

**Issue by wang777777** [NervJS/taro#4396]
**问题描述**
taro 默认 redux 空模板，为什么在 jsx render 中 console props，会输出两遍？

**复现步骤**
[复现问题的步骤]
1. taro 初始化项目 redux
2. page/index/index.jsx 中 render console.log(this.props)
3. 输出两遍 props, 此时 shouldComponentUpdate 未执行

**期望行为**
只输出一遍

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
