### ISSUE TITLE
h5模式下 nerv-devtools 报错

### ISSUE THREAD

**Issue by Elliott-Hu** [NervJS/taro#4399]
![image](https://user-images.githubusercontent.com/16644716/64256758-a68e6e00-cf56-11e9-8369-1699e050d153.png)

![image](https://user-images.githubusercontent.com/16644716/64256725-9c6c6f80-cf56-11e9-9adf-2223deb52c51.png)

**系统信息**
👽 Taro v1.3.12

  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.17 => 1.3.17 
      @tarojs/components: 1.3.17 => 1.3.17 
      @tarojs/plugin-babel: 1.3.17 => 1.3.17 
      @tarojs/plugin-csso: 1.3.17 => 1.3.17 
      @tarojs/plugin-sass: 1.3.17 => 1.3.17 
      @tarojs/plugin-uglifyjs: 1.3.17 => 1.3.17 
      @tarojs/redux: 1.3.17 => 1.3.17 
      @tarojs/redux-h5: 1.3.17 => 1.3.17 
      @tarojs/router: 1.3.17 => 1.3.17 
      @tarojs/taro: 1.3.17 => 1.3.17 
      @tarojs/taro-alipay: 1.3.17 => 1.3.17 
      @tarojs/taro-h5: 1.3.17 => 1.3.17 
      @tarojs/taro-swan: 1.3.17 => 1.3.17 
      @tarojs/taro-tt: 1.3.17 => 1.3.17 
      @tarojs/taro-weapp: 1.3.17 => 1.3.17 
      @tarojs/webpack-runner: 1.3.17 => 1.3.17 
      eslint-config-taro: 1.3.17 => 1.3.17 
      eslint-plugin-taro: 1.3.17 => 1.3.17 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      react: ^16.8.6 => 16.9.0 
      stylelint-config-taro-rn: 1.3.17 => 1.3.17 
      stylelint-taro-rn: 1.3.17 => 1.3.17

**Comment by Elliott-Hu** [comment]
@yuche

**Comment by kinsui** [comment]
> @yuche 麻烦帮忙看一下

你好，请问解决了吗？求助~

**Comment by xueleilei** [comment]
同样遇到这个问题，请问已经修复了吗？  @yuche

**Comment by wsyxl365** [comment]
@yuche 同样遇到这个问题，请问已经解决了吗

**Comment by cnscorpions** [comment]
同问

**Comment by SinguJ** [comment]
同样此问题。
操作系统：`Windows 10 1909 18363.836`
浏览器：`Chrome 81.0.4044.138（正式版本） （64 位）`
NPM依赖：
- @tarojs/components: 2.2.2
- @tarojs/components-qa: 2.2.2
- @tarojs/mobx: 2.2.2
- @tarojs/mobx-h5: 2.2.2
- @tarojs/router: 2.2.2
- @tarojs/taro: 2.2.2
- @tarojs/taro-alipay: 2.2.2
- @tarojs/taro-h5: 2.2.2
- @tarojs/taro-qq: 2.2.2
- @tarojs/taro-quickapp: 2.2.2
- @tarojs/taro-swan: 2.2.2
- @tarojs/taro-tt: 2.2.2
- @tarojs/taro-weapp: 2.2.2
- babel-runtime: ^6.26.0
- mobx: 4.8.0
- nerv-devtools: ^1.5.5
- nervjs: ^1.5.5
- regenerator-runtime: 0.11.1
- taro-ui: ^2.3.4

React Developer Tools版本：`4.6.0 (3/26/2020)`
