### ISSUE TITLE
非全局安装下使用npx创建项目的问题

### ISSUE THREAD

**Issue by wowlusitong** [NervJS/taro#44]
因为不想全局安装，所以使用 `npx @tarojs/cli init myApp` 创建项目。
当 build 的时候就需要 `npx @tarojs/cli build`, build作为一个相对比较频繁使用的命令，每次这么操作比较麻烦（如网络原因）
是否也可以将 `@tarojs/cli` 作为 [template](https://github.com/NervJS/taro/blob/master/packages/taro-cli/templates/default/pkg#L20) 的依赖？这样在项目内就可以 `npx taro build` 或使用 `npm script`了

**Comment by luckyadam** [comment]
可以提个 PR 更新下模板么~

**Comment by yuche** [comment]
如果文档可以同步更新 PR 那就更棒了~
