### ISSUE TITLE
使用第三方组件库echarts-for-weixin的时候报错

### ISSUE THREAD

**Issue by HecateDK** [NervJS/taro#440]
代码和bug如图
![image](https://user-images.githubusercontent.com/19571458/43881270-3d4b36be-9bde-11e8-876d-c53d71d6a1b0.png)

看起来像是没有把ec-canvas编译进dist文件里
执行的命令行是`npm run dev:weapp`

**Comment by HecateDK** [comment]
![image](https://user-images.githubusercontent.com/19571458/43882032-d4e452e2-9be0-11e8-83ab-473192fcf67f.png)

是要具体到`ec-canvas.js`文件吗？
不过还是不行

**Comment by NNorLand** [comment]
@HecateDK 这个问题你解决了吗？我也遇到了。是哪里写错了吗？

**Comment by luckyadam** [comment]
@NNorLand 她的版本不是beta版本

**Comment by NNorLand** [comment]
@luckyadam 谢谢，建议文档里注明版本几开始支持。不然很困惑。

**Comment by YuDaChao** [comment]
@HecateDK 你的问题解决了嘛？我遇到的错误和你的有点不一样
![image](https://user-images.githubusercontent.com/23699765/46021362-1d01d980-c113-11e8-97b3-423996187400.png)
![image](https://user-images.githubusercontent.com/23699765/46021414-386ce480-c113-11e8-9b77-66aac3a6fbe8.png)
版本是： "@tarojs/taro": "^1.0.3",

**Comment by luckyadam** [comment]
@YuDaChao https://github.com/NervJS/taro-sample-weapp 参考一下这个
