### ISSUE TITLE
taro 1.3之后，如果想使用react-native 的expo构建应用该怎么做？

### ISSUE THREAD

**Issue by brucecodezone** [NervJS/taro#4404]
**问题描述**
Taro 1.3 之后移除了对react-native的expo支持，想开发react-native应用需要安装ios android的开发套件，比较麻烦，希望官方可以提供一份文档可以让开发者自行添加expo支持~

**系统信息**
Taro CLI 1.3.17 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm

**Comment by Pines-Cheng** [comment]
taro 1.3之后是基于原生的 RN ，原生的 RN 用不了 expo 的构建。
