### ISSUE TITLE
taro小程序三目运算符编译错误，导致开发者工具报错

### ISSUE THREAD

**Issue by sansx** [NervJS/taro#4406]
**问题描述**
小程序三目运算符编译出错，编译后的文件逻辑与期望的不符合，导致编辑器报错

**复现步骤**
```
{Taro.getStorageSync("token") ? (
          data.getOrders &&
          data.getOrders.list.map(e => (
            <View
              className={classnames(styles.itemBox)}
              onClick={this.toItemInfo.bind(this, e.id)}
              key={e.id}
            >
              <Item data={e} />
            </View>
          ))
        ) : (
          <View>
            <View className={classnames(styles.loginTip)}>
              您还没有登录，请登录后查看订单
            </View>
            <View className={classnames(styles.loginBox)}>
              <LoginBtn title="登录" type="primary"></LoginBtn>
            </View>
          </View>
        )}
```

**期望行为**
编译出符合逻辑的代码

**报错信息**
编译后文件错误部分如下：
var loopArray6 这里无视了三目运算之后的判断逻辑，直接编译成了anonymousState__temp6 ? data.getOrders.list，导致没有获取到data.getOrders.list编辑器直接报错
`Cannot read property 'list' of undefined;`
```
var anonymousState__temp5 = (0, _index5.default)(_orderListModuleScssMap2.default.loginBox);
      var anonymousState__temp6 = _index2.default.getStorageSync("token");
      var loopArray6 = anonymousState__temp6 ? data.getOrders.list.map(function (e, _anonIdx) {
        e = {
          $original: (0, _index.internal_get_original)(e)
        };
        var $loopState__temp2 = data.getOrders ? _index2.default.getStorageSync("token") ? (0, _index5.default)(_orderListModuleScssMap2.default.itemBox) : null : null;
        var $compid__36 = (0, _index.genCompid)(__prefix + "LixnCYQDQy" + _anonIdx);
        anonymousState__temp6 && _index.propsManager.set({
          "data": e.$original
        }, $compid__36);
        return {
          $loopState__temp2: $loopState__temp2,
          $compid__36: $compid__36,
          $original: e.$original
        };
      }) : [];
```

**系统信息**
👽 Taro v1.3.17

  Taro CLI 1.3.17 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.npm-global/lib/node_modules/yarn/bin/yarn
      npm: 6.8.0 - ~/.npm-global/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.17 => 1.3.17 
      @tarojs/cli: 1.3.17 => 1.3.17 
      @tarojs/components: 1.3.17 => 1.3.17 
      @tarojs/plugin-babel: 1.3.17 => 1.3.17 
      @tarojs/plugin-csso: 1.3.17 => 1.3.17 
      @tarojs/plugin-sass: 1.3.17 => 1.3.17 
      @tarojs/plugin-uglifyjs: 1.3.17 => 1.3.17 
      @tarojs/redux: 1.3.17 => 1.3.17 
      @tarojs/redux-h5: 1.3.17 => 1.3.17 
      @tarojs/router: 1.3.17 => 1.3.17 
      @tarojs/taro: 1.3.17 => 1.3.17 
      @tarojs/taro-alipay: 1.3.17 => 1.3.17 
      @tarojs/taro-h5: 1.3.17 => 1.3.17 
      @tarojs/taro-swan: 1.3.17 => 1.3.17 
      @tarojs/taro-tt: 1.3.17 => 1.3.17 
      @tarojs/taro-weapp: 1.3.17 => 1.3.17 
      @tarojs/webpack-runner: 1.3.17 => 1.3.17 
      eslint-config-taro: 1.3.17 => 1.3.17 
      eslint-plugin-taro: 1.3.17 => 1.3.17 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      stylelint-config-taro-rn: 1.3.17 => 1.3.17 
      stylelint-taro-rn: 1.3.17 => 1.3.17

**Comment by shenghanqin** [comment]
建议更好的设置变量，而不是将所有的判断条件和获取参数都放在判断上。
因为Taro的适配层并不是万能的。
