### ISSUE TITLE
H5 router reLaunch 跳转问题

### ISSUE THREAD

**Issue by ghlinjianqiang** [NervJS/taro#4408]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
H5项目中，一级页面点击navigateTo进入==>二级设置页面==>点击退出登录reLaunch到登录页。点击退出登录relaunch会直接跳回一级页面，页面栈length为2，点击历史按钮前进才是目标登录页。

**复现步骤**
[复现问题的步骤]
1. 一级页面
![image](https://user-images.githubusercontent.com/39210772/64322092-75fd1180-cff4-11e9-9541-9ab5bef91104.png)

2. 二级设置页面
![image](https://user-images.githubusercontent.com/39210772/64322172-a2189280-cff4-11e9-9960-6e6f8188b76b.png)

3. 点击退出登录reLaunch到登录页的结果
![image](https://user-images.githubusercontent.com/39210772/64322638-8b267000-cff5-11e9-83c5-83fa8858441a.png)

4. 点击前进才是期望的登录页
![image](https://user-images.githubusercontent.com/39210772/64322669-9f6a6d00-cff5-11e9-8015-56492fc48725.png)

[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]
[代码只贴截图，不贴文字会被视为无效issue]

```js

// 这里可以贴代码
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.3.4]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by guxingke201** [comment]
h5的bug优先级真低，都3个月了

**Comment by Littly** [comment]
已提交 https://github.com/NervJS/taro/commit/484d3b09174b7458e11be2a82ee0a567eec5f89f
