### ISSUE TITLE
通过taro init 创建的文件夹需要root权限，否则不能增、删、改文件

### ISSUE THREAD

**Issue by wongzzh** [NervJS/taro#4409]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. 初始化一个taro项目执行命令：sudo taro init test
2. 是否需要使用 TypeScript ？ No
3. 请选择 CSS 预处理器（Sass/Less/Stylus） Stylus
4. 请选择模板 (Use arrow keys) 选择 redux 
5. 将创建好的test项目添加的vscode编辑器中，尝试删除任何文件、修改任意文件、在任意目录创建文件，都不能成功，提示如下：
Error: EACCES: permission denied, unlink '/Users/mac/Downloads/test/src/pages/index/index.jsx'

无法写入文件 (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/mac/Downloads/test/src/pages/index/abc.css')
如果加上root权限如 sudo mkdir abc 则是正常的
（同样用taro init 命令初始化一个项目，如不选择redux模版，使用默认模版，就不会出现此问题）

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
希望能解决此问题

**系统信息**
System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm

**Comment by luckyadam** [comment]
因为你是用 `sudo` 创建的

**Comment by wongzzh** [comment]
问题解决了，确实是这样，非常感谢。
