### ISSUE TITLE
【with-weapp】setData函数有bug

### ISSUE THREAD

**Issue by canvasT** [NervJS/taro#4415]
**问题描述**
taro-with-weapp package中的setData存在问题，因为setData为同步函数，setState为异步函数，在上一次setState未生效之前 ，后续的setData会造成数据覆盖

**复现步骤**

```js
this.state = {
  a: 0,
  b: 0,
  c: 0
}

setData({
  a: 1
})

setData({
  b: 1
})

setData({
  c: 1
})
```

**期望行为**
```
this.state = {
  a: 1,
  b: 1,
  c: 1
}
```

**报错信息**
最终结果可能是
```
this.state = {
  a: 0,
  b: 0,
  c: 1
}

```

**系统信息**
 Taro v1.3.17

  Taro CLI 1.3.17 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.5.3
**补充信息**
2019.8.28之前的版本还是好的，不知道为什么删了：
![image](https://user-images.githubusercontent.com/1745014/64400336-7eaa2200-d09e-11e9-8393-3a59a04466f8.png)

**Comment by yuche** [comment]
你可以提个 PR 重新加上

**Comment by guxingke201** [comment]
这个bug会导致微信小程序源码写的组件可以正常运行，然后使用taro convert转成taro代码就挂了。

这个[日期时间组件](https://github.com/rover95/wxapp-timePicker)就可以重现这个bug。

taro convert不会只是个玩具吧......
