### ISSUE TITLE
H5环境下react devtools报错

### ISSUE THREAD

**Issue by Java-http** [NervJS/taro#4418]
**问题描述**

H5环境下react devtools报错
![image](https://user-images.githubusercontent.com/17530621/64407151-3139af00-d0b6-11e9-9021-157d336331e2.png)

**复现步骤**

在 `app.jsx` 中取消注释
```
// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
  require('nerv-devtools')
}
```
**期望行为**
正常使用 devtools

**报错信息**

![image](https://user-images.githubusercontent.com/17530621/64407151-3139af00-d0b6-11e9-9021-157d336331e2.png)

**系统信息**
```
  Taro CLI 1.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD

  报错平台 h5
```

**Comment by Pines-Cheng** [comment]
duplicate of https://github.com/NervJS/taro/issues/4399

**Comment by xiaowang1314** [comment]
没解决呀，怎么关闭了
