### ISSUE TITLE
props报错 <BottomFixation content={<View>subcontent</View>} />报错ReferenceError: React is not defined

### ISSUE THREAD

**Issue by czb128abc** [NervJS/taro#4422]
**问题描述**
<BottomFixation content={<View>subcontent</View>} />

![image](https://user-images.githubusercontent.com/339385/64442444-65d35800-d102-11e9-80e1-b12abcddfbbd.png)

```js
// ```js
// ```
<BottomFixation content={<View>subcontent</View>}>
            <AtButton
              type="primary"
              disabled={primaryDisabled}
              onClick={this.handleRegister}
              loading={loading}
            >
              确定提交
            </AtButton>
          </BottomFixation>
```

**报错信息**

![image](https://user-images.githubusercontent.com/339385/64442646-c06cb400-d102-11e9-881f-1c6a726deeef.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro v1.3.17

  Taro CLI 1.3.17 environment info:
    System:
      OS: macOS High Sierra 10.13.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
 - 报错平台 [ weapp]

**Comment by Pines-Cheng** [comment]
哪个端？问题怎样复现？

**Comment by czb128abc** [comment]
BottomFixation 是一个组件, 有个属性 content(PropTypes.node), 当 content 为 <View>subcontent</View> 时,会报 ReferenceError: React is not defined

**Comment by Chen-jj** [comment]
@czb128abc 传 JSX 时属性名以 **render** 开头 https://nervjs.github.io/taro/docs/children.html

**Comment by yellowjian** [comment]
> @czb128abc 传 JSX 时属性名以 **render** 开头 https://nervjs.github.io/taro/docs/children.html

对于function component 而言， 在子元素里面得不到renderHeader 的值
