### ISSUE TITLE
redux connect + weapp + 函数组件： Component is not found in path

### ISSUE THREAD

**Issue by ionush** [NervJS/taro#4424]
**问题描述**
用connect和函数组件作为page遇到这个报错：

微信开发者工具
![image](https://user-images.githubusercontent.com/26359601/64488060-a7384480-d275-11e9-8aa0-6a81c6abd623.png)

terminal
![image](https://user-images.githubusercontent.com/26359601/64488065-b7502400-d275-11e9-8934-8fe34457fb39.png)

h5 没有问题。是不是weapp不支持hooks？

**复现步骤**

```js
const Home = connect(
  ({ homePage, global: { i18n } }) => ({
    homePage,
    i18n,
  }),
  dispatch => ({
    add() {
      dispatch(add())
    },
    dec() {
      dispatch(minus())
    },
    changeLangRequest({ lang }) {
      dispatch(changeLangRequest({ lang }))
    },
  })
)(_Home)

export default Home

const _Home = () => (<View><Text>hello</Text></View>)
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.14 => 1.3.14 
      @tarojs/components: 1.3.14 => 1.3.14 
      @tarojs/plugin-babel: 1.3.14 => 1.3.14 
      @tarojs/plugin-csso: 1.3.14 => 1.3.14 
      @tarojs/plugin-sass: 1.3.14 => 1.3.14 
      @tarojs/plugin-uglifyjs: 1.3.14 => 1.3.14 
      @tarojs/redux: 1.3.14 => 1.3.14 
      @tarojs/redux-h5: 1.3.14 => 1.3.14 
      @tarojs/router: 1.3.14 => 1.3.14 
      @tarojs/taro: 1.3.14 => 1.3.14 
      @tarojs/taro-alipay: 1.3.14 => 1.3.14 
      @tarojs/taro-h5: 1.3.14 => 1.3.14 
      @tarojs/taro-swan: 1.3.14 => 1.3.14 
      @tarojs/taro-tt: 1.3.14 => 1.3.14 
      @tarojs/taro-weapp: 1.3.14 => 1.3.14 
      @tarojs/webpack-runner: 1.3.14 => 1.3.14 
      eslint-config-taro: 1.3.14 => 1.3.14 
      eslint-plugin-taro: 1.3.14 => 1.3.14 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      react: ^16.9.0 => 16.9.0 
      stylelint-config-taro-rn: 1.3.14 => 1.3.14 
      stylelint-taro-rn: 1.3.14 => 1.3.14

**Comment by Chen-jj** [comment]
@ionush 

函数式组件以大写字母开头，编译时才会找出它进行编译，你写了 _Index 所以编译时没有处理，这里我们考虑加些错误提示吧。

```js
const Home = () => (<View><Text>hello</Text></View>)

const _Home = connect(
  ({ homePage, global: { i18n } }) => ({
    homePage,
    i18n,
  }),
  dispatch => ({
    add() {
      dispatch(add())
    },
    dec() {
      dispatch(minus())
    },
    changeLangRequest({ lang }) {
      dispatch(changeLangRequest({ lang }))
    },
  })
)(Home)

export default _Home
```
