### ISSUE TITLE
ui 打包报错，一直重复引用

### ISSUE THREAD

**Issue by Dolov** [NervJS/taro#4427]
**问题描述**
在 UI 库中开发了一个 Tree, 通过 A B 互相引用的方式，yarn dev:weapp 可以正常使用，但是在打包的时候 yarn build 就会一直在重复引用，请问这种情况如果解决

**复现步骤**
[复现问题的步骤]
在 UI 库中开发了一个 Tree, 通过 A B 互相引用的方式，yarn dev:weapp 可以正常使用，但是在打包的时候 yarn build 就会一直在重复引用，请问这种情况如果解决

**期望行为**
希望能够正常打包

**报错信息**

<img width="586" alt="WechatIMG95" src="https://user-images.githubusercontent.com/19704420/64499393-63802200-d2eb-11e9-80ca-016ff2d58e66.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: MAC
 - Taro 版本 1.3.15
 - Node.js 版本 12.1
 - 报错平台  UI 打包

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
提供一个 demo 看看吧

**Comment by Dolov** [comment]
> 提供一个 demo 看看吧

你好，这是 demo 的地址  https://github.com/Dolov/taro-tree
单独打包为 h5 或者 weapp 是没有问题的，但是如果使用 TARO_BUILD_TYPE=ui taro build --ui 打包为多端 UI 库就会出现循环引用。

非常感谢！
