### ISSUE TITLE
微信小程序中，使用高阶函数来写hook,编译wxml时报错

### ISSUE THREAD

**Issue by yesixuan** [NervJS/taro#4430]
这是我的一个自定义hook，他的功能是实现条件渲染
```jsx
export const useConditionRender = (condition, defaultRender: any = null) => (reactDom) => {
  const [ res, setRes ] = useState(null)
  useEffect(() => {
    condition
      ? setRes(reactDom)
      : setRes(defaultRender)
  }, [condition])
  return res
}
```

用法
```jsx
const conditionRender = useConditionRender(showComment, '默认展示...')
{
        conditionRender(<AtTextarea/>)
}
```
![image](https://user-images.githubusercontent.com/22050621/64506639-dfd62d80-d30a-11e9-9204-3c0591bcec77.png)

![image](https://user-images.githubusercontent.com/22050621/64506655-f2e8fd80-d30a-11e9-8f08-1c270faae77b.png)

![image](https://user-images.githubusercontent.com/22050621/64506703-157b1680-d30b-11e9-81e3-a1e0cf31ace2.png)

![image](https://user-images.githubusercontent.com/22050621/64506718-23309c00-d30b-11e9-8c0c-4c261951cfd3.png)

**Comment by yuche** [comment]
Taro 的一大限制就是没有办法把 JSX 作为一个变量传入到函数中，除了文档表明可以用的情况（例如 map 和 render props） 之外，其它情况都是不可行的。
