### ISSUE TITLE
cli 工具对文件夹快捷方式无法扫描，产生报错进而无法编译。

### ISSUE THREAD

**Issue by tangbc** [NervJS/taro#4431]
**问题描述**

在 src 源码目录下存在`快捷方式`的文件夹时，跑 run dev 时会报错。

**复现步骤**

我们的项目采用了 lerna 来管理，而 taro 的源码目录就是一个用 lerna 管理的 package，所以就生成了如下目录：

```bash
├── actions
├── app.less
├── app.tsx
├── index.html
├── node_modules
├───── @utils (这个是 lerna 包的快捷方式，由 lerna 自动生成)
├──────── index.ts
├── package.json
├── pages
├── reducers
└── store
```

显然 ` src/node_modules/@utils` 被当成了一个文件，实际上是文件夹的快捷方式！

**报错信息**

![image](https://user-images.githubusercontent.com/6846113/64515734-bb388080-d31f-11e9-8d15-d6e2fdfb4bf0.png)

问题就出在 `node_modules/@utils` 这个快捷方式的判断上：

```bash
创建  发现文件  src/pages/index/index.less
创建  发现文件  src/pages/index/index.tsx
创建  发现文件  src/node_modules/@utils
```

**系统信息**

 - 操作系统: macOS
 - Taro 版本 1.3.17
 - Node.js 版本 v10.16.0
 - 报错平台 h5 weapp

**补充信息**

初步定位报错点在源码这里：
https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/h5/index.ts#L162

```js
if (!file.stats.isDirectory()) {
  util_1.printLog("create" /* CREATE */, '发现文件', relativePath);
  this.processFiles(file.path);
}
```

显然这里的 if 判断有问题， `node_modules/@utils` 这个是个文件夹的快捷方式，也被判断成了非文件夹，再进行 `fs.readFileSync` 就报错了。

再往前面翻一下逻辑，问题应该就出在 [`klaw(sourcePath)`](https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/h5/index.ts#L159) 这里**缺少对文件夹快捷方式的判断和 walker**，最终放到根目录 `.temp` 文件夹后 `src/node_modules` 就是一个空文件夹。

希望 taro 团队尽快解决一下，谢谢！

**Comment by CntChen** [comment]
解决软链问题外,  用`lerna`可能有另一个问题.
`taro` 的打包是对入口目录进行扫描, 并复制一份到 `.temp` 目录进行构建.
使用 `lerna bootstrap` 后, 会在 `src` 目录下安装 `learn` 的依赖,  `src/node_modules`, 这个文件夹同样会被扫描, 可能导致扫描文件规模很大.
