### ISSUE TITLE
[百度小程序]自定义组件在componentDidMount钩子中无法拿到节点信息

### ISSUE THREAD

**Issue by myl0204** [NervJS/taro#4438]
**问题描述**
在自定义组件的componentDidMount执行selectorQuery.selectAll操作，boundingClientRect中拿到的是空数组。

**复现步骤**
自定义组件中

```js
// 在componentDidMount中执行
const query: SelectorQuery = this.$scope.createSelectorQuery()
query
  .selectAll('.tab_item')
  .boundingClientRect((rects: clientRectElement[]) => {
    console.log(rects) // 空数组 []
    this.setState({ rects })
  })
  .exec()
```

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.17 => 1.3.14 
      @tarojs/cli: 1.3.17 => 1.3.14 
      @tarojs/components: 1.3.17 => 1.3.14 
      @tarojs/plugin-babel: 1.3.17 => 1.3.14 
      @tarojs/plugin-csso: 1.3.17 => 1.3.14 
      @tarojs/plugin-sass: 1.3.17 => 1.3.14 
      @tarojs/plugin-uglifyjs: 1.3.17 => 1.3.14 
      @tarojs/redux: 1.3.17 => 1.3.14 
      @tarojs/redux-h5: 1.3.17 => 1.3.14 
      @tarojs/router: 1.3.17 => 1.3.14 
      @tarojs/taro: 1.3.17 => 1.3.14 
      @tarojs/taro-alipay: 1.3.17 => 1.3.14 
      @tarojs/taro-h5: 1.3.17 => 1.3.14 
      @tarojs/taro-swan: 1.3.17 => 1.3.14 
      @tarojs/taro-weapp: 1.3.17 => 1.3.14 
      @tarojs/webpack-runner: 1.3.17 => 1.3.14 
      eslint-config-taro: 1.3.17 => 1.3.14 
      eslint-plugin-taro: 1.3.17 => 1.3.14 
      nervjs: ^1.4.4 => 1.4.4 

**补充信息**
钩子执行时机可能有问题。加一个延时后可以正常拿到节点信息。

**Comment by Chen-jj** [comment]
same issue #2631
