### ISSUE TITLE
Taro.request每次调用都会push taroInterceptor

### ISSUE THREAD

**Issue by eriklynd** [NervJS/taro#4441]
**问题描述**
Taro.request方法每次调用都会向interceptor chain中push一个taroInterceptor。导致interceptor chain越来越长。

**复现步骤**

1. 多次调用Taro.request方法
2. 断点查看或者打印interceptor chain

https://github.com/NervJS/taro/blob/cdc9f4803b462597cd481827466f86018140606c/packages/taro/src/interceptor/index.js#L10
```js
request (requestParams) {
    this.chain.interceptors.push(this.taroInterceptor) // 这行代码每次调用Taro.request都会被执行
    return this.chain.proceed({ ...requestParams })
  }

```

**期望行为**
taroInterceptor只被push一次

**Comment by Iveon** [comment]
...这个问题还没修复吗？我一个请求第一次请求没问题，每在多一次请求 拦截器就多工作一次....
