### ISSUE TITLE
Taro 组件编译问题

### ISSUE THREAD

**Issue by SzHeJason** [NervJS/taro#4445]
**问题描述**

1. 目前有项目使用了 Taro + lerna 的形式开发多组件方案，但是 Taro 的 UI 打包机制过于约束，无法让每个 package 各自打包组件，希望能支持通过传递参数来让指定文件编译成 Taro 包 , 让打包更加自由，(或则能通过babel、rollup、webpack 插件实现这种功能)

   ![image](https://user-images.githubusercontent.com/20609396/64680831-206fab80-d4b1-11e9-8095-f867fb545ed6.png)

2. 不可通过第三方组件实现继承的效果,但是把第三方组件代码放到当前项目就好了

   ![image2](http://storage.360buyimg.com/mtd/home/xnip2019-09-12_16-35-511568277444289.jpg)

3. 如果在 scss 文件下引用了第三方模块，会导致 UI 组件编译失败 

```scss
@import "~taro-ui/dist/style/index.scss";
// 或者使用 alias 也会导致编译失败
@import "@common/taro-ui/dist/style/index.scss"
```

4. 编译 UI 时，组件在 h5 下会自动添加不必要的代码
![image](https://user-images.githubusercontent.com/20609396/65677550-69645a00-e084-11e9-9144-9e6bfea7c166.png)

5. 编译UI之后, weapp 目录下的 alias 路径没有经过处理 (h5会转变成相对路径处理)，导致项目引用组件时报错
```
// 编译前
import Base from '@common/base'

// 编译后的 weapp 文件下
import Base from '@common/base'

// 编译后的 h5 文件下
import BaseComponent from "../../../../common/base";
```

**期望行为**

1. 编译指定组件为 Taro 组件

   ```shell
    # 编译指定组件为 Taro 组件
    taro build --ui --config ../config/index.js
   ```

2. 可以继承第三方组件

3. 正常编译通过

**系统信息**
![image](https://user-images.githubusercontent.com/20609396/64682964-fb7d3780-d4b4-11e9-89b7-fce4252b19e9.png)

**Comment by SzHeJason** [comment]
https://github.com/SzHeJason/taro-bug-demo 写了一个示例库

**Comment by SzHeJason** [comment]
组件打包不能通过的形式
```
import Taro from '@tarojs/taro'

import component from './components/a-x/ui/component/index'

// 失败
export default component

// 成功
export { default as component }
```

**Comment by SzHeJason** [comment]
css module 无法编译 UI 组件
![image](https://user-images.githubusercontent.com/20609396/68820979-ecd71a80-06c7-11ea-948c-b2b207cfbbf0.png)

**Comment by kyjo2014** [comment]
# 当前行为
缺少对`import { component as xxxx} from 'xxxx' `的支持
当使用 `  export { default as xxxx } from ` 语法导出组件，编译时会报
“路径错误，请检查！（可能原因是导出的组件名不正确”
# 期望行为
正常引入组件

**Comment by luckyadam** [comment]
75f8d11f07067fc4df450fdcb8f17200587bb9bb

**Comment by zhang14725804** [comment]
alias路径别名错误，1.3.5的时候好好的，更新到2.0.0.beta出问题了
![image](https://user-images.githubusercontent.com/15354910/71357280-15540d80-25c0-11ea-98b2-af2baa04acb3.png)

![image](https://user-images.githubusercontent.com/15354910/71357319-45031580-25c0-11ea-88b6-f3a2b4da584f.png)

求解
