### ISSUE TITLE
编译h5， 编译成功了，可是h5 报错

### ISSUE THREAD

**Issue by Zhou-Bill** [NervJS/taro#4447]
taro 版本 1.2.26

![image](https://user-images.githubusercontent.com/13554001/64705701-f1722d80-d4e2-11e9-8135-3c5b56c6fb9b.png)

![image](https://user-images.githubusercontent.com/13554001/64705869-3b5b1380-d4e3-11e9-8af7-2c0e5d0a1137.png)

h5 打开空白，不知道为什么，
小程序可以正常运行

**Comment by ZakaryCode** [comment]
升级试试咯，还有问题可以提供一个可复现的样例
