### ISSUE TITLE
navigateBack返回成功后调用页面栈刷新问题

### ISSUE THREAD

**Issue by potatoes0521** [NervJS/taro#4449]
**问题描述**
微信小程序环境
navigateBack返回成功后调用页面栈方法获取页面栈
然后调用页面栈的onReady方法部分机型  如iphoneX XS  IOS系统 12.4.1  微信版本7.0.3
不会触发页面重载  如 componentDidMount  和  componentWillMount不触发

**复现步骤**
[复现问题的步骤]
1. 进入一个界面  比如发布一条消息  
2. 发布成功后通过navigateBack返回上一页
3. navigateBack的success事件被触发之后获取页面栈并且刷新页面

![image](https://user-images.githubusercontent.com/32003360/64747930-14342e80-d543-11e9-8507-fe87beccb2fc.png)
```js

export const backReload = (sleepTime) => {
  setTimeout(() => {
    Taro.navigateBack({
      success: () => {
        const pageArray = Taro.getCurrentPages()
        pageArray[pageArray.length - 1].onReady()
      }
    })
  }, sleepTime)
}

```

**期望行为**
期望能改动这个  类似于原生小程序在调用页面栈返回的时候  触发这些方法可以直接触发componentWillMount或者componentDidMount方法或者可以兼容直接写微信小程序onLoad之类的方法

**报错信息**

无报错信息  只是不会触发

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:IOS  12.4.1
 - Taro 版本1.3.17
 - Node.js 版本12.10.0
 - 报错平台 ,weapp

**Comment by Chen-jj** [comment]
@potatoes0521 不要私自调用小程序生命周期方法，你的写法是不规范的。

**Comment by dzjwan521** [comment]
解决了吗。我我页不知道怎么返回刷新

**Comment by potatoes0521** [comment]
let pages = Taro.getCurrentPages(); //  获取页面栈
let prevPage = pages[pages.length - 2]; // 上一个页面
prevPage.$component.setState({
    data: data
}, () => {
    Taro.navigateBack()
})


或者是调用方法
| |
刘洋
|
|
liuyang0359@163.com
|
签名由网易邮箱大师定制


在2019年10月23日 17:28，dzj<notifications@github.com> 写道：

解决了吗。我我页不知道怎么返回刷新

**Comment by iSozL** [comment]
navigateBack会触发componentDidShow事件，试着把要执行的函数迁移进去试试，Taro有一个自带的hooks, useDidShow，navigateBack会触发它
