### ISSUE TITLE
微信小程序的开放接口怎么调用

### ISSUE THREAD

**Issue by guotie** [NervJS/taro#445]
例如wx.login, 支付的，授权的，转发的等等

文档里没有提啊

**Comment by zacksleo** [comment]
把wx替换成Taro就可以了，都可以直接使用

**Comment by guotie** [comment]
index.d.ts中定义的Param有问题啊

wx.login的Object有很多，里面就定义了一个scope

**Comment by guotie** [comment]
index.d.ts定义的login参数不全
```
    type Param = {
      /**
       * 需要获取权限的scope，详见 [scope 列表](https://developers.weixin.qq.com/miniprogram/dev/api/authorize-index.html#scope-列表)
       */
      scope: string
    }
```

实际上这个login的参数Object远远不止这么一个scope key

**Comment by guotie** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/api-login.html#wxloginobject

**Comment by zacksleo** [comment]
这个定义不全，但是不影响使用啊， 你看微信的文档写就行了 另外你可以PR

**Comment by Quilljou** [comment]
getFileSystemManager() 这个API支持吗？
