### ISSUE TITLE
map一个函数式视图：丢失key值，onClick事件内传参异常

### ISSUE THREAD

**Issue by sayll** [NervJS/taro#4452]
**问题描述**
map一个函数式视图：丢失key值，onClick事件内传参异常

**复现步骤**
1. 渲染出现 key 赋值失败提示
2. 点击出现，获取入参失败

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'

class MyPage extends Component {
  state = {
    list: [
      { text: 1 },
      { text: 2 },
      { text: 3 },
      { text: 4 },
    ],
  }

  config = {
    navigationBarTextStyle: 'white',
    navigationBarTitleText: 'test',
    navigationBarBackgroundColor: '#31353D',
    enablePullDownRefresh: true,
    onReachBottomDistance: 50,
  }

  render() {
    return (
      <View>
        {this.state.list.map(item => this.renderList(item))}
      </View>
    )
  }
  renderList(item) {
    return <View key={item.text} onClick={() => console.log(item.text)}>
      <Text>{item.text}</Text>
    </View>
  }
}

export default MyPage

```

**期望行为**
点击对应项，打印对应数值。
循环遍历，key值应该有效

**报错信息**
=
![image](https://user-images.githubusercontent.com/18632641/64764253-4316c880-d574-11e9-8a6e-9ef434d22f77.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.5
 - Taro 版本 v1.3.17
 - Node.js 版本  v12.8.0
 - 报错平台 weapp

**补充信息**
该现象仅在 map 函数视图出现

**Comment by iugo** [comment]
@luckyadam 建议将 **返回 JSX 的 map() 参数不要复用** 写入最佳实践文档, 以避免大家遇到类似问题.

**Comment by Chen-jj** [comment]
#4190

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
