### ISSUE TITLE
pxTransform在其它小程序的表现问题

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#4454]
**问题描述**
支付宝小程序中Css样式被转换为rem，Taro.pxTransform转换为rpx，但是转换的rpx生成的样式问题在支付宝中无法达到需要的效果，所以希望开发一个类似于Taro.pxTransform转换为rem的API。。。。。

**复现步骤**
Css生成的样式
![image](https://user-images.githubusercontent.com/42051272/64773700-6a29c600-d585-11e9-892c-1e8144515590.png)

Taro.pxTransform生成的样式【样式无法达到预期】
![image](https://user-images.githubusercontent.com/42051272/64773863-b248e880-d585-11e9-9618-dfe97e870216.png)

**期望行为**
期望开放一个Taro.pxTransRem的API让开发者在不同平台调用不同的API，满足开发需求。

**报错信息**

无报错信息

**系统信息**
Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.8.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.18 => 1.3.18 
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: ^1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-less: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/redux: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18

**Comment by luckyadam** [comment]
在支付宝小程序，Taro 也是转成 rpx，你看到的转成 rem 是支付宝小程序自己的行为

**Comment by VFiee** [comment]
> 在支付宝小程序，Taro 也是转成 rpx，你看到的转成 rem 是支付宝小程序自己的行为

我明白您的意思，我希望开放一个转成rem的API，让开发者来决定在不同平台调用不同的API，以达到预期效果。

**Comment by luckyadam** [comment]
> 我明白您的意思，我希望开放一个转成rem的API，让开发者来决定在不同平台调用不同的API，以达到预期效果。

但目前支付宝小程序似乎没有给出 px 到 rem 的换算规则，这个 API 不好实现

**Comment by VFiee** [comment]
> > 我明白您的意思，我希望开放一个转成rem的API，让开发者来决定在不同平台调用不同的API，以达到预期效果。
> 
> 但目前支付宝小程序似乎没有给出 px 到 rem 的换算规则，这个 API 不好实现

好的，谢谢！
