### ISSUE TITLE
H5端 tabBar切换tab后刷新页面，底部tabbar会消失

### ISSUE THREAD

**Issue by chenruir** [NervJS/taro#4456]
**问题描述**

H5端的tabBar在切换tab后刷新页面底部tabbar会消失, ```http://127.0.0.1:5000/```这种形式链接刷新当前页面的tabBar正常, 同一页面 ```http://127.0.0.1:5000/#/pages/index/index``` 这种形式链接刷新页面tabBar会消失

**复现步骤**
使用模板创建简单项目, 新增两个tabBar页面, app.js 中配置tabBar 然后进行如上操作即可实现

**期望行为**
回归正常

**报错信息**

正常情况
![image](https://user-images.githubusercontent.com/28745838/64774632-220ba300-d587-11e9-9a7f-b00dd704849b.png)
```http://127.0.0.1:5000/```刷新页面tabbar正常显示

切换底部其他tab后，f5刷新页面，底部tabbar消失
![image](https://user-images.githubusercontent.com/28745838/64775112-05bc3600-d588-11e9-9420-2140d1816b7d.png)

![image](https://user-images.githubusercontent.com/28745838/64775029-e6250d80-d587-11e9-93a3-42bff4a511e7.png)

**Comment by Ding95** [comment]
我也发现了这个问题 我看的是 tabbar 加了一个 'taro-tabbar__tabbar-hide' 的class，就是把 tabbar display: none 了。

**Comment by chenruir** [comment]
taro @1.3.18版本会存在该问题。降低版本为1.3.16刷新tabbar页面是正常的

**Comment by tzerocode** [comment]
> taro @1.3.18版本会存在该问题。降低版本为1.3.16刷新tabbar页面是正常的

我试了还是一样。

**Comment by ZakaryCode** [comment]
fixed in commit 61dc79ab7253bd15427bc2fcc32ab9355792d3d7

**Comment by zwc4825** [comment]
hash模式下的bug，换成browser模式
h5: {
    publicPath: '/',
    staticDirectory: 'static',
    esnextModules: ['taro-ui'],
    router:{
      mode: 'browser'
     }，
    .....
  }

**Comment by toFrankie** [comment]
`@3.4.1` 版本 H5 端仍存在此问题，有时刷新页面，tarbar 无端消失，并无主动调用 `hideTarBar()` 或 `showTabBar()`。调试看了，还是添加了 `.taro-tabbar__tabbar-hide` 选择器
