### ISSUE TITLE
weapp ios 真机子组件不调用componentDidMount

### ISSUE THREAD

**Issue by GaoYuJian** [NervJS/taro#4458]
**问题描述**
页面结构如下图所示:
有俩个Tab页首页和店铺，店铺页面的组件在经过下面`复现步骤`的操作会触发bug,子组件componentDidMount不调用 (只有iOS真机会出现，微信小程序基础库版本2.8.2)
<img width="336" alt="屏幕快照 2019-09-12 19 23 39" src="https://user-images.githubusercontent.com/8776592/64780419-e971c680-d592-11e9-9819-713d88aeb135.png">
<img width="335" alt="屏幕快照 2019-09-12 19 23 49" src="https://user-images.githubusercontent.com/8776592/64780435-f1ca0180-d592-11e9-84b3-88a683dffc02.png">

**复现步骤**
1. 进入应用，点击店铺页面
2. 点击清空列表，清空店铺页面子组件
3. 切换到首页，点击`调整二级页面`，设置店铺页面数据重新渲染子组件
4. 店铺页面子组件不触发componentDidMount

[复现demo](https://github.com/GaoYuJian/TaroRenderDemo)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
  Taro CLI 1.3.14 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.14 => 1.3.14 
      @tarojs/components: 1.3.14 => 1.3.14 
      @tarojs/plugin-babel: 1.3.14 => 1.3.14 
      @tarojs/plugin-csso: 1.3.14 => 1.3.14 
      @tarojs/plugin-sass: ^1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.14 => 1.3.14 
      @tarojs/redux: 1.3.14 => 1.3.14 
      @tarojs/redux-h5: 1.3.14 => 1.3.14 
      @tarojs/router: 1.3.14 => 1.3.14 
      @tarojs/taro: 1.3.14 => 1.3.14 
      @tarojs/taro-alipay: 1.3.14 => 1.3.14 
      @tarojs/taro-h5: 1.3.14 => 1.3.14 
      @tarojs/taro-swan: 1.3.14 => 1.3.14 
      @tarojs/taro-tt: 1.3.14 => 1.3.14 
      @tarojs/taro-weapp: 1.3.14 => 1.3.14 
      @tarojs/webpack-runner: 1.3.14 => 1.3.14 
      eslint-config-taro: 1.3.14 => 1.3.14 
      eslint-plugin-taro: 1.3.14 => 1.3.14 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.14 => 1.3.14 
      stylelint-taro-rn: 1.3.14 => 1.3.14 
    npmGlobalPackages:
      typescript: 3.5.3
 - 操作系统: [iOS]
 - 报错平台 [weapp]

**补充信息**
通过调试发现是小程序原生组件的`ready`方法没有调用

**Comment by Chen-jj** [comment]
@GaoYuJian 小程序的问题，这种写法会导致 ready 不触发，建议换种写法。

![image](https://user-images.githubusercontent.com/11807297/64938608-15da5b00-d891-11e9-9f3c-248463c591df.png)

**Comment by GaoYuJian** [comment]
@Chen-jj  你好有什么替代写法吗，我们的实际场景是电商购物车，先清空购物车，再到商品详情添加商品到购物车

**Comment by Chen-jj** [comment]
@GaoYuJian 把逻辑放 componentWillMount

**Comment by GaoYuJian** [comment]
@Chen-jj 
componentDidMount不调用，后续componentWillReceiveProps也不会调用，还有在componentDidMount中需要调用一下dom相关的api, 用componentWillMount不太合适

**Comment by Chen-jj** [comment]
@GaoYuJian 加个变量控制一下展示时机试试

```js
componentDidShow () {
    this.setState({
      show: true
    })
  }

  componentDidHide () {
    this.setState({
      show: false
    })
  }

  render () {
    return (
      <View className='index'>
        {this.state.show &&
          <View>
          {
            this.props.counter.testList.map((v, i) => {
              return <CheckIcon onCheckChange={checked => this.onCheckChange(checked, i)} key={v.key} defaultChecked={v.checked} />
            })
          }
          </View>
        }
      </View>
    )
  }
```
