### ISSUE TITLE
Hooks  组件中使用 Ref ，提示类型错误 

### ISSUE THREAD

**Issue by hqwlkj** [NervJS/taro#4462]
**问题描述**
Hooks  组件中使用 Ref ，提示类型错误 
![image](https://user-images.githubusercontent.com/12181423/64903236-cb69aa80-d6e7-11e9-9b58-2aeb0b614aaf.png)

**复现步骤**

```js
const inputRef = useRef<HTMLInputElement>(null);

<Input
    ref={inputRef}
    type='text' placeholder='请输入标签名称，最多5个字' maxLength={5}
    onBlur={({ detail }) => setDefaultTags([...defaultTags, detail.value])}
 />

```

**期望行为**
与官网文档上是的使用方式一致 
https://nervjs.github.io/taro/docs/hooks.html#useref

**报错信息**

![image](https://user-images.githubusercontent.com/12181423/64903249-e63c1f00-d6e7-11e9-90b5-7845589de429.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. macOS 10.14.6]
 - Taro 版本 [e.g. v1.3.18]
 - Node.js 版本 [e.g. v12.9.1]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
const inputRef = useRef(null)

**Comment by hqwlkj** [comment]
@luckyadam  一样的
![image](https://user-images.githubusercontent.com/12181423/65294687-8a631180-db91-11e9-9ad7-0f2dd1690278.png)

主要是 `ref` 的类型只支持 ` ref?: string | ((node: any) => any)` 类型。所以使用 `hooks` 时，还不支持。
