### ISSUE TITLE
Uncaught TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by forconz** [NervJS/taro#4464]
**问题描述**
使用IntersectionObserver不支持观察View，但是支持div

定义了一个hook组件useOnScreen，用来观察一个元素是否在视窗可见，代码如下：
```
import { useState, useEffect } from '@tarojs/taro'
import { type } from 'os';

function useOnScreen(target, options) {
  // State and setter for storing whether element is visible
  const [isIntersecting, setIntersecting] = useState(false);

  useEffect(() => {
    if (!IntersectionObserver) {
      throw new Error('Current browser does not support IntersectionObserver ')
    }
    const observer = new IntersectionObserver(
      // Update our state when observer callback fires
      entries => setIntersecting(entries && entries.isIntersecting),
      options
    );

    console.log(`typeof target.current=${typeof target.current}`)
    if (target.current && observer)
      observer.observe(target.current);
    
    return () => {
      observer && observer.unobserve(target.current);
    };
  }, []); // Empty array ensures that effect is only run on mount and unmount

  return isIntersecting;
}

export default useOnScreen;
```

**复现步骤**
[复现问题的步骤]
1. 写一个stateless的页面
```
function Feed () {
  // 判断是否到了底部
  const ref = useRef();
  const bottomOnScreen = useOnScreen(ref, {
    root: null,
    rootMargin: '-50px'
  });

 ...

 <View ref={ref}>1234</View>
}
```

如果用 View就抛异常
useOnScreen.js?e383:19 Uncaught TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at Object.eval [as effect] (useOnScreen.js?e383:19)
    at eval (index.esm.js?d052:1546)
    at Array.forEach (<anonymous>)
    at invokeEffects (index.esm.js?d052:1542)
    at eval (index.esm.js?d052:1567)
    at Array.forEach (<anonymous>)
    at eval (index.esm.js?d052:1565)

按F12去watch  target.current，其值如下图：
![QQ截图20190915232420](https://user-images.githubusercontent.com/9990289/64923788-fd762c00-d80f-11e9-94a8-241ba948c270.png)

如果我们把代码View改成div
```
function Feed () {
  // 判断是否到了底部
  const ref = useRef();
  const bottomOnScreen = useOnScreen(ref, {
    root: null,
    rootMargin: '-50px'
  });

 ...

 <div ref={ref}>1234</div>
}
```
这个异常就消失了。

interface IntersectionObserver {
    readonly root: Element | null;
    readonly rootMargin: string;
    readonly thresholds: ReadonlyArray<number>;
    disconnect(): void;
    observe(target: Element): void;
    takeRecords(): IntersectionObserverEntry[];
    unobserve(target: Element): void;
}

observe(target: Element): void;
咱们这个View不是Element，所以抛异常了

我暂时用div凑合用的了，这个问题算不算taro的bug？

btw：我这边开发左侧菜单，在谷歌浏览器下非常适配，但是放真机下，因为微信多了那个头部占据了空间，左侧菜单就溢出了，这个问题一般如何解决？我觉得750的设计尺寸有问题，在谷歌浏览器下开发一点问题都没，各种手机都自适应，但是一放入iphone6真机屏幕里，就会有问题，因为微信提供的可视尺寸并不是设计尺寸，微信头部占据了一部分高度，taro在这块并没有做自适应吧？

**Comment by forconz** [comment]
观察的Element改成 <Text ref={ref}>1234</Text>，一样有问题

![QQ截图20190915233202](https://user-images.githubusercontent.com/9990289/64923887-0b787c80-d811-11e9-8fdf-658e5e401114.png)
异常信息如下图：
![QQ截图20190915233242](https://user-images.githubusercontent.com/9990289/64923893-20eda680-d811-11e9-9479-438a9c7c7230.png)

**Comment by shuxinhuang** [comment]
请问，如何用createIntersectionObserver api （不用hook的方式），用 this.createIntersectionObserver 程序运行报错 this.createIntersectionObserver is not a function;at "pages/index/index" page lifeCycleMethod onReady function
TypeError: this.createIntersectionObserver is not a function 。 用wx.createIntersectionObserver 方式，程序运行不会报错，但是Observer的回调不执行

**Comment by luckyadam** [comment]
改成 

import { useState, useEffect, findDOMNode } from '@tarojs/taro' 

observer.observe(findDOMNode(target.current))

试试

**Comment by forconz** [comment]
@luckyadam 非常感谢，问题解决了

我发现getBoundingClientRect和observe(target: Element): void;都存在类似问题

在js代码中
```
import { findDOMNode } from '@tarojs/taro'

const bottomElementRef = useRef(null);
  const bottomOnScreen = useIntersectionObserver(bottomElementRef?findDOMNode(bottomElementRef.current):null, {
    root: null,
    rootMargin: '-100px'
  });
```

在ts代码中
```
import Nerv from "nervjs";
const rect = Nerv.findDOMNode(node).getBoundingClientRect();
```

ts不支持 
`import { findDOMNode } from '@tarojs/taro'`
