### ISSUE TITLE
HOOK useRef current的值拿不到，无法调用子组件的方法

### ISSUE THREAD

**Issue by Hsyneve** [NervJS/taro#4466]
**问题描述**
按照官方文档使用useRef这个hook创建的节点，，在后面的点击事件中这个节点的current值为null

**复现步骤**
按照官网示例

 ```
import Taro, { useContext, useRef, Component } from "@tarojs/taro";
import { View, Button, Text,Input,Navigator } from "@tarojs/components";
function IndexPage() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` 指向已挂载到 DOM 上的文本输入元素
    console.log(inputEl);
    // inputEl.current.focus();
  };
 
  
  return (
    <View className="index">
      <Input ref={node => (this.inputEl = node)} type="text" />
      <Button onClick={onButtonClick}>Focus the input</Button>
    </View>
  );
}
export default IndexPage

 ```

**期望行为**
与官方文档一样拿到dom节点

**报错信息**

![image](https://user-images.githubusercontent.com/22348060/64939839-db72bd00-d894-11e9-8472-5e37e4df7828.png)

**系统信息**
> 

 - 操作系统: [e.g. Windows 10]
 - Taro 版本: v1.3.18
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
@Hsyneve 用法是 `<Input ref={inputEl} type="text" />`，不过还是会有问题，尽快修复。

**Comment by Hsyneve** [comment]
谢谢大神知晓，我开始是按照<Input ref={inputEl} type="text" />这个写法来的，没有用我才改成了别的方式，报错都是一样

**Comment by githubmann** [comment]
有进展吗 @Chen-jj

**Comment by MingNeo** [comment]
这么基础的功能都出错了…

**Comment by superman0159** [comment]
通过字符串创建的可以用，useRef还是用不了，求解决

**Comment by jiangbo0216** [comment]
Taro CLI 1.3.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 1.19.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
      npm: 6.9.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD

`inputEl.current.focus();` current虽然可以取到值,但是无法调用dom的方法,有没有进展呢

**Comment by githubmann** [comment]
@Chen-jj 大佬，能给个答复吗？

**Comment by CastileMan** [comment]
一个半月了哟。。

**Comment by Chen-jj** [comment]
本周修一下

**Comment by pasBone** [comment]
请问这个问题修复完发布了吗？刚刚更新到"1.3.22"问题依旧哦

**Comment by gaogao2017** [comment]
什么时间修复呀，着急呀,开发的项目都快上线了

**Comment by superman0159** [comment]
> 什么时间修复呀，着急呀,开发的项目都快上线了

老老实实用字符串ref吧orz

**Comment by Chen-jj** [comment]
还没发版，尽快发一个

**Comment by pasBone** [comment]
> > 什么时间修复呀，着急呀,开发的项目都快上线了
> 
> 老老实实用字符串ref吧orz

function component 怎么用字符串？

**Comment by pasBone** [comment]
> 还没发版，尽快发一个

尽快呀老哥，就等你们临门一脚了

**Comment by superman0159** [comment]
> > > 什么时间修复呀，着急呀,开发的项目都快上线了
> > 
> > 
> > 老老实实用字符串ref吧orz
> 
> function component 怎么用字符串？

```
<Component ref="com" />
<script>
console.log(this.$refs.com);
</script>

**Comment by pasBone** [comment]
> > > > 什么时间修复呀，着急呀,开发的项目都快上线了
> > > 
> > > 
> > > 老老实实用字符串ref吧orz
> > 
> > 
> > function component 怎么用字符串？
> 
> ```
> <Component ref="com" />
> <script>
> console.log(this.$refs.com);
> </script>
> ```
function component里面this不是undefined吗？？？难道我任督二脉没打通？

**Comment by superman0159** [comment]
> function component里面this不是undefined吗？？？难道我任督二脉没打通？

没想到吧，还真的可以用，就是有点奇怪

**Comment by Garfield550** [comment]
@superman0159 1.3.23 发了，更新试一下？

**Comment by pasBone** [comment]
> @superman0159 1.3.23 发了，更新试一下？

哇我试试，爱你哟

**Comment by gaogao2017** [comment]
@Chen-jj 
更新1.3.23,安装依赖包报错
![image](https://user-images.githubusercontent.com/26714881/68662596-18e38600-0578-11ea-9f5d-7c714c23b747.png)

**Comment by pasBone** [comment]
> @Chen-jj
> 更新1.3.23,安装依赖包报错
> ![image](https://user-images.githubusercontent.com/26714881/68662596-18e38600-0578-11ea-9f5d-7c714c23b747.png)

同升级失败，折腾死我了

**Comment by Chen-jj** [comment]
@gaogao2017 @pasBone 再试试把

![image](https://user-images.githubusercontent.com/11807297/68727823-73c0c000-0600-11ea-9781-8c2b535d7da4.png)

**Comment by gaogao2017** [comment]
好了
