### ISSUE TITLE
--watch 监听文件修改自动结束

### ISSUE THREAD

**Issue by KaleidoX** [NervJS/taro#4468]
**问题描述**
ubuntu18.04 、16.04环境下  --watch 监听文件修改自动结束, 其他环境运行正常.

**复现步骤**

[复现问题的步骤]
1. taro build --type weapp --watch
2. 文件监听直接退出
3. [开始](https://cdn.caomall.net/15686839871282851841.png)
4. [结束](https://cdn.caomall.net/156868400512364072.png)

**期望行为**
希望在ubuntu 环境中正常实现文件监听

**报错信息**
无报错信息

**系统信息**
```
taro info
👽 Taro v1.3.18


  Taro CLI 1.3.18 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.18 => 1.3.18 
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-sass: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/redux: ^1.3.18 => 1.3.18 
      @tarojs/redux-h5: ^1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-qq: 1.3.18 => 1.3.18 
      @tarojs/taro-quickapp: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18 

```

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
暂时没有 ubuntu 测试环境，能否先帮忙分析下原因

**Comment by KaleidoX** [comment]
> 暂时没有 ubuntu 测试环境，能否先帮忙分析下原因

![image](https://user-images.githubusercontent.com/30251578/65298028-8ab4da00-db9c-11e9-84f0-a6e313eb5e1a.png)

``` javascript
    const watcher = chokidar.watch(watcherPaths, {
       ---  ignored: /(^|[/\\])\../,
        persistent: true,
        ignoreInitial: true,
    });
```
把这个 ignored 去掉就可以在 ubuntu 系统内正常监听文件了

**Comment by KaleidoX** [comment]
> > 暂时没有 ubuntu 测试环境，能否先帮忙分析下原因
> 
> ![image](https://user-images.githubusercontent.com/30251578/65298028-8ab4da00-db9c-11e9-84f0-a6e313eb5e1a.png)
> 
> ```js
>     const watcher = chokidar.watch(watcherPaths, {
>        ---  ignored: /(^|[/\\])\../,
>         persistent: true,
>         ignoreInitial: true,
>     });
> ```
> 
> 把这个 ignored 去掉就可以在 ubuntu 系统内正常监听文件了

因为 我的文件外层路径属于 dotfiles 
> ~/.local/share/code/badger
