### ISSUE TITLE
支付宝小程序this.props.children无法显示

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#4469]
**问题描述**
使用Taro文档中Children，无法显示出来（初步判断和百度小程序类似）

文档地址：https://nervjs.github.io/taro/docs/children.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**复现步骤**
[复现问题的步骤]
1. 编写组件A
2. 页面B引用组件A， <A>
<View>Taro Children</View>
</A>
3. 支付宝开发工具运行，无法显示

```js
组件A
renderPropsChildren() {
        return <View>
            {this.props.children}
        </View>
    }
render() {
        return <View>
            {this.renderPropsChildren()}
        </View>
    }
页面B
  <Authorize>
            <View>Taro children</View>
  </Authorize>
```

**期望行为**
经过多次尝试，在组件A中如果不使用renderPropsChildren函数渲染，而是直接在render方法中直接return <View>{this.props.children}</View>是可以，但是我需要在renderPropsChildren函数进行逻辑判断渲染。期望在renderPropsChildren中正常渲染(微信小程序没问题)

**报错信息**
无法显示传入的Children

**系统信息**
 Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.8.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.18 => 1.3.18 
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: ^1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-less: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/redux: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18

**Comment by Chen-jj** [comment]
@VFiee 直接在 render return 的 JSX 内做逻辑判断吧，支付宝不支持在 template 中使用 slot，所以没有办法。

**Comment by VFiee** [comment]
> @VFiee 直接在 render return 的 JSX 内做逻辑判断吧，支付宝不支持在 template 中使用 slot，所以没有办法。
亲测，可以。谢谢提醒。
by the way：可以在官网类组件函数处标记一下。
