### ISSUE TITLE
taro编译小程序源码报错的问题

### ISSUE THREAD

**Issue by 12522611705** [NervJS/taro#4472]
<view class="container">
    <v-book-list-header title="{{data.name}}" code="{{data.code}}" params="{{data.params}}" />
    <view class="book-list">
        <block wx:for="{{dataList && data.list}}" wx:key="{{index}}">
            <v-book-info bookData="{{item}}" class="book-info">
                <view slot="footer" class="price price-border" wx:if="{{item.chargeTypeName == '分享后领取'}}">{{item.chargeTypeName}}</view>
                 <view slot="footer" class="price" wx:else></view>
            </v-book-info>
        </block>
    </view>
    <v-change-one wx:if="{{data.label != 1}}" type="1" code="{{data.code}}" bindchangeData="changeData"/>
</view>

**Comment by 12522611705** [comment]
后来请教群里大神发现   slot 语法要加一个block才能编译成功  <block slot="footer" ><view class="price" wx:else></view></block>

**Comment by yuche** [comment]
你代码没发出来
