### ISSUE TITLE
Taro 有没有页面跳转的全局事件监听机制？

### ISSUE THREAD

**Issue by glacjay** [NervJS/taro#4473]
比如我可以加个全局的 handler，在里面记录所有的页面跳转事件的日志。

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/tutorial.html#componentdidshow
componentDidShow/componentDidHide

**Comment by shenghanqin** [comment]
我觉得方法有两种
1、小程序侧增加一个被动的全局监听方法
2、在页面跳转时，将页面跳转的情况加入到全局监听里面。

**Comment by glacjay** [comment]
@luckyadam 抱歉我没写清楚，已经修改了标题和描述。

**Comment by glacjay** [comment]
好吧，看来没有，那我自己封装个 navigateTo 接口好了。

其实我是觉得，虽然微信没有，但 taro 应该是可以加个这种机制的吧。
