### ISSUE TITLE
关于支付宝指纹识别

### ISSUE THREAD

**Issue by yutao331763646** [NervJS/taro#4475]
请问支持支付宝指纹识别吗，我看文档只支持微信

**Comment by luckyadam** [comment]
支付宝有的话就支持

**Comment by yutao331763646** [comment]
> 支付宝有的话就支持

支付宝是有支持的，现在taro现有的api能适配到支持支付宝吗

**Comment by broven** [comment]
@yutao331763646 你可以直接调用支付宝的 my. 来用
