### ISSUE TITLE
rn上的Textarea在disableScroll为true时候的问题

### ISSUE THREAD

**Issue by Slngle** [NervJS/taro#4476]
**问题描述**
[问题描述：Textarea在disableScroll设为true的时候，点击其他区域键盘不会收回]

**复现步骤**
[复现问题的步骤]
1. config里面disableScroll设置为true
2. 点击Textarea拉起键盘，再点击其他区域，发现键盘不会收回（onbulr没触发？）

```js

class FeedbackSub extends Component {
  static defaultProps = {}

  state = {
    disabled: true
  }

  config = {
    navigationBarTitleText: '问题反馈',
    navigationStyle: 'custom',
    disableScroll: true
  }

  params = {
    content: ''
  }
  render() {
    return (
      <View className="feed-4036">
      <Textarea
              autoFocus
              className="feed-4036-wrap-textarea"
              placeholder="您的反馈对我们很重要"
              onInput={this.onInput}
            />
      </View>
    )
   }
  }

```

**期望行为**
[ 期望点击其他区域键盘收起 ]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

     Taro CLI 1.3.2 environment info:
        System:
          OS: macOS 10.14.6
          Shell: 5.3 - /bin/zsh
      Binaries:
          Node: 11.14.0 - /usr/local/bin/node
          Yarn: 1.16.0 - /usr/local/bin/yarn
          npm: 6.9.0 - /usr/local/bin/npm

**补充信息**
[ 可能设置disableScroll为true事件没冒泡到触发onBlur的地方？]

**Comment by Pines-Cheng** [comment]
我测试了一下，貌似无论 disableScroll 是否为 true 都不会收起。
