### ISSUE TITLE
微信打开h5 使用 Taro.setNavigationBarTitle 和 Taro.setNavigationBarColor 无效吗？

### ISSUE THREAD

**Issue by giantss** [NervJS/taro#4479]
微信打开h5 使用 Taro.setNavigationBarTitle 和 Taro.setNavigationBarColor 无效吗？

<img width="525" alt="WeChatffc0aaf51f90278fe6fb332c1c4a34d1" src="https://user-images.githubusercontent.com/13778798/65096637-38d34f00-d9f8-11e9-853b-196c63da521e.png">

**Comment by jinjinjin0731** [comment]
无效，微信浏览禁止修改了

**Comment by giantss** [comment]
好的 3q

**Comment by F8-Tortoise** [comment]
楼主用了什么方法解决这个问题呢？目前遇到了这个问题
