### ISSUE TITLE
后续是否会支持小程序分包加载模式

### ISSUE THREAD

**Issue by Mjian-chen** [NervJS/taro#448]
后续是否会支持小程序分包加载模式

**Comment by Mjian-chen** [comment]
后续是否会支持小程序分包加载模式

**Comment by luckyadam** [comment]
会的~ 后续会加入支持

**Comment by qinyang1980** [comment]
顶一个，希望这个能早点做 ：） 正式项目一般都需要的。

**Comment by luckyadam** [comment]
@qinyang1980 OJBK

**Comment by ronffy** [comment]
@luckyadam  关注下，希望这个能尽快支持！
开始重构的时候不知道不能分包，现在重构一半了才发现这个问题，只能先按不分包处理下了

**Comment by luckyadam** [comment]
@ronffy 收到~ 我们尽快支持~

**Comment by ronffy** [comment]
@luckyadam  辛苦辛苦，等如果能腾出时间，尽量贡献一些PR，共同促进 taro 成长！

**Comment by luckyadam** [comment]
@ronffy 这样最棒了~

**Comment by luckyadam** [comment]
分包加载已支持
9bb3e986708a4e5cb23553be96da1492f2f386e6

**Comment by luckyadam** [comment]
分包支持版本已发布
