### ISSUE TITLE
ts文件中使用了类型声明，当该ts文件被别名方式'@/...'导入时，h5编译报错，小程序正常；打包时也无法处理别名'@'

### ISSUE THREAD

**Issue by xujiandream** [NervJS/taro#4480]
**问题描述**
ts文件中的类型声明，当以别名'@'方式导入该ts文件时，h5编译报错，小程序正常；TARO_BUILD_TYPE=ui taro build --ui 方式打包时也无法识别'@'

 ```
// index.ts(主文件以别名开头路径引入socket文件)
export { default as Socket } from '@/socket'
```

 ```
// socket.ts（文件中connect参数url带了类型说明）
import Taro from '@tarojs/taro'
export default class Socket {
  connect (url: string) {
    Taro.connectSocket({
      url
    }).then(socket => {
    })
  }
}
```

**期望行为**
使用别名引入ts文件时能够兼容ts文件中的类型声明

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
<img width="609" alt="WX20190918-104212@2x" src="https://user-images.githubusercontent.com/23227529/65103612-5822aa00-da01-11e9-8c21-4eb54d7f64a6.png">

**系统信息**
Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-sass: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-qq: 1.3.18 => 1.3.18 
      @tarojs/taro-quickapp: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18 

**补充信息**
[可选]
是否taro对别名处理异常

**Comment by ZakaryCode** [comment]
你需要在 config 下添加 alias 配置，否则无法被识别
