### ISSUE TITLE
Taro 无法为自定义组件添加 class 样式类名

### ISSUE THREAD

**Issue by gaoupon** [NervJS/taro#4482]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
目前 Taro 编译微信小程序自定义组件时，由于微信使用 web component 的关系，会产生组件自己的标签。例如： 

```js
const Card: Taro.FC<{}> = () => {
  return <view className="card-item">hello world</view>
}
```

```js
<ScrollView>
  <Card/> //自定义组件
  ......
</ScrollView>
```

会编译成如下结构：

![ScreenClip](https://user-images.githubusercontent.com/8264905/65114176-603a1400-da18-11e9-9b74-cb7985f32304.png)

而真正 react 组件是没有这个 `<card ...>` 标签的, 这会导致如下问题：

当我想要控制每个 card 的 width （例如 100rpx）以及其他 css 属性时（用 externalClasses 也是一样），只能作用到 `view.card-item` 这一层，而没有办法作用在 `<card></card>` 这一层（因为不能设置 card 的 className）,结果 `<card>` 仍然占满一行。

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
提供能力为外层<card>标签添加 class

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结
- 操作系统: [ Windows 10]
 - Taro 版本 [v.1.3]
 - Node.js 版本 [v9.0.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
这个问题我看了其他 issue，有提到相似的问题，然后对应的回复可能都没有理解真实的问题点，到现在也没有真正的解决办法，这其实对组件化设计的影响很大。

**Comment by Chen-jj** [comment]
@gaoupon 什么场景需要样式作用于 card。card 只是一个抽象节点，样式作用组件内根节点，即 card-item 则可。

> 当我想要控制每个 card 的 width （例如 100rpx）以及其他 css 属性时（用 externalClasses 也是一样），只能作用到 view.card-item 这一层，而没有办法作用在 <card></card> 这一层（因为不能设置 card 的 className）,结果 <card> 仍然占满一行。

.card-item 设置 display: inline-block; 、float 或者使用 flex 都可以控制，不设置的话默认 display：block 那布局上看肯定还是占满一行。

**Comment by gaoupon** [comment]
> .card-item 设置 display: inline-block; 、float 或者使用 flex 都可以控制，不设置的话默认 display：block 那布局上看肯定还是占满一行。

@Chen-jj  这的确可以解决一部分问题，但有的时候 css 样式选择器是强依赖于结构的，例如

``` css
  &:not(:last-child) {
    margin-right: 8px;
  }
```

类似这种应该只能作用于 `card` 才能生效。

**Comment by Chen-jj** [comment]
@gaoupon nth-child，last-child 这些选择器肯定不行了，绕一绕用 js 确定类名等，或去微信的开发者社区看看有没有解决办法把。

**Comment by singletonPeople** [comment]
我也是我这样的问题 真的是折磨   
![image](https://user-images.githubusercontent.com/53305259/79087709-c4387700-7d72-11ea-967c-2c2e8653a5b0.png)
class 和 style都不行
