### ISSUE TITLE
函数式组件的函数参数默认值无效

### ISSUE THREAD

**Issue by LeeHarlan** [NervJS/taro#4483]
**问题描述**
函数式组件的函数参数默认值无效

```jsx
import Taro from '@tarojs/taro';
import noop from 'lodash/noop';
import { View } from '@tarojs/components';

function TestComponent({ onClick = noop }) {
  return (
    <View onClick={onClick}>点击一下</View>
  );
}

export default TestComponent;

```

**期望行为**
点击`点击一下`正常运行，不会报错

**报错信息**
![WX20190918-142412](https://user-images.githubusercontent.com/14872348/65120406-2836cf00-da20-11e9-94a2-69ee73a115e5.png)

**Comment by Chen-jj** [comment]
@LeeHarlan 

```js
function A (props) {
  const { onClick = noop } = props
  return (
    <View onClick={onClick}>点击一下</View>
  )
}
```

**Comment by LeeHarlan** [comment]
我习惯这样写，没有效果所以就来问下
```jsx
function A ({ onClick = noop }) { }
```

**Comment by shenghanqin** [comment]
> 我习惯这样写，没有效果所以就来问下
> 
> ```js-jsx
> function A ({ onClick = noop }) { }
> ```

感觉tarojs的写法是有一定限制的，按照官方解答的来即可

**Comment by LeeHarlan** [comment]
是的，先按官方解答的来

看了下编译过后的代码，是有处理，只是用的时候又直接调用了 `this.props.onClick`

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
