### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'util'

### ISSUE THREAD

**Issue by XT-0515** [NervJS/taro#4485]
**问题描述**
taro 编译微信小程序  报错  

**复现步骤**
1. npm run dev:weapp

**期望行为**
可正常编译

**报错信息**
(node:13425) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'util'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:267:30
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:3:12)
    at recursiveRequire (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:266:12)
    at resolveNpmFilesPath (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:55:9)
    at analyzeImportUrl (/usr/local/lib/node_modules/@tarojs/cli/dist/util/resolve_npm_files.js:87:29)
(node:13425) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13425) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**系统信息**
Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.8 => 1.3.18 
      @tarojs/components: ^1.3.8 => 1.3.18 
      @tarojs/components-rn: ^1.3.4 => 1.3.18 
      @tarojs/plugin-babel: 1.3.4 => 1.3.4 
      @tarojs/plugin-csso: 1.3.4 => 1.3.4 
      @tarojs/plugin-sass: ^1.3.4 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.4 => 1.3.4 
      @tarojs/redux: ^1.3.8 => 1.3.18 
      @tarojs/router: 1.3.4 => 1.3.4 
      @tarojs/taro: 1.3.4 => 1.3.4 
      @tarojs/taro-alipay: 1.3.4 => 1.3.4 
      @tarojs/taro-h5: 1.3.4 => 1.3.4 
      @tarojs/taro-redux-rn: ^1.3.4 => 1.3.18 
      @tarojs/taro-rn: ^1.3.4 => 1.3.18 
      @tarojs/taro-router-rn: ^1.3.4 => 1.3.18 
      @tarojs/taro-swan: 1.3.4 => 1.3.4 
      @tarojs/taro-tt: 1.3.4 => 1.3.4 
      @tarojs/taro-weapp: 1.3.4 => 1.3.4 
      @tarojs/webpack-runner: 1.3.4 => 1.3.4 
      eslint-config-taro: 1.3.4 => 1.3.4 
      eslint-plugin-taro: 1.3.4 => 1.3.4 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
      stylelint-config-taro-rn: 1.3.4 => 1.3.4 
      stylelint-taro-rn: 1.3.4 => 1.3.4

**Comment by luckyadam** [comment]
不要使用 node 的包，比如这个 `util`

**Comment by XT-0515** [comment]
> 不要使用 node 的包，比如这个 `util`

项目中没有使用到util这个包，而且在其他mac上编译是没有问题的。

**Comment by XT-0515** [comment]
> 不要使用 node 的包，比如这个 `util`

**Comment by XT-0515** [comment]
把node版本降到8版本，重新安装依赖包，没什么用，后来多执行了几次 npm i   奇迹般的好了，不报错了 emm...
