### ISSUE TITLE
taro init 安装不了

### ISSUE THREAD

**Issue by ISBN9527** [NervJS/taro#4487]
![image](https://user-images.githubusercontent.com/30942709/65210769-d39e5d00-dace-11e9-8cbe-e794fba5e00a.png)

![image](https://user-images.githubusercontent.com/30942709/65210892-6b03b000-dacf-11e9-90a5-c23b9e0dcd30.png)

**Comment by ISBN9527** [comment]
请大佬解答

**Comment by ISBN9527** [comment]
重新安装出现下图错误
![image](https://user-images.githubusercontent.com/30942709/65211217-84592c00-dad0-11e9-89f8-9f323cc7abab.png)

**Comment by ISBN9527** [comment]
上面安装成功是一下操作：sudo npm i -g @tarojs/cli --unsafe-perm=true --allow-root

**Comment by Chen-jj** [comment]
@ISBN9527 用 nvm 安装 nodejs

**Comment by shenghanqin** [comment]
现在如何了呢？

**Comment by Littly** [comment]
重装node吧 node不要用sudo装
