### ISSUE TITLE
this.props.children在小程序中会触发children的生命周期？

### ISSUE THREAD

**Issue by leifeng** [NervJS/taro#4489]
**问题描述**
在h5中this.props.children是正常的，在微信小程序中就算不使用```{this.props.children}```也会触发children的生命周期

**复现步骤**

```js
class Index extends Component {
  render() {
    return (
      <Card>
        <Hello />
      </Card>
    );
  }
}
```
```js
class MyCard extends Component {
  render() {
    return (
      <View>
        Card不使用this.props.children,也会触发children中的render
        {/* <View>{this.props.children}</View> */}
      </View>
    );
  }
}
```
```js
class Hello extends Component {
  render() {
    console.log('hello-render');
    return <View>Hello</View>;
  }
}
```
在h5中不会出现```hello-render```,在小程序中会出现```hello-render```
[在线例子，h5正常，在小程序中有问题](https://codesandbox.io/s/nerv-sandbox-ghte9?fontsize=14)

**期望行为**
期望跟h5效果一样

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@leifeng 建议写份原生小程序测试一下 slot 会否触发组件生命周期

**Comment by leifeng** [comment]
谢谢，原来是小程序的问题
https://developers.weixin.qq.com/community/develop/doc/000284adc5c310175029dee4a51400
