### ISSUE TITLE
taro更新到1.3.18后使用@withWeapp('Component')，生命周期attached不触发

### ISSUE THREAD

**Issue by vecold** [NervJS/taro#4491]
**问题描述**
微信小程序，taro更新到1.3.18后使用@withWeapp('Component')，生命周期attached不触发

**复现步骤**
微信小程序新建一个页面，在页面中放一个组件，组件被渲染时没有走attached生命周期
import withWeapp from '@tarojs/with-weapp'
@withWeapp('Component')
class _C extends Taro.Component {
attached = e => {
}
}

export default _C

**期望行为**
修复或提供解决方案

**报错信息**

**系统信息**
👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
weapp

**补充信息**

**Comment by luckyadam** [comment]
没有复现你的问题
