### ISSUE TITLE
Taro Hooks useEffect 第二个参数设置为`[]`执行一次的语法实际上执行两次

### ISSUE THREAD

**Issue by youtiao66** [NervJS/taro#4493]
**问题描述**
Taro Hooks useEffect 第二个参数设置为`[]`执行一次的语法实际上执行两次

**复现步骤**
1. **目标是使用`mobx`在组件间共享状态，新建`store`全局状态**
2. 希望执行`useEffect`一次，第二个参数设置为`[]`，并在回调中修改`store`状态
3. 结果会造成`useEffect`回调实际执行两次

```js

import Taro, { useEffect } from '@tarojs/taro'
import { observer } from '@tarojs/mobx'
import { View } from '@tarojs/components'
import { observable } from 'mobx'

const store = observable({ count: 0 })

function Test() {
  const { count } = store
  useEffect(
    () => {
      console.log('useEffect')
      store.count = 1
    },
    []
  )
  return (
    <View>{count}</View>
  )
}

export default observer(Test)

```

**期望行为**
执行`useEffect`回调一次
```
  => useEffect
```

**报错信息**
执行`useEffect`回调两次
```
  => useEffect
  => useEffect
```

**系统信息**
```
Taro v1.3.18
weapp
package.json
  "mobx": "4.8.0"
System:
  OS: Windows 10
Binaries:
  Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.15.2 - C:\Users\EDZ\AppData\Roaming\npm\yarn.CMD
  npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**补充信息**
- **实际上我使用`React Hooks` + `mobx-react` + `mobx`不会导致该问题**
- 可能是因为在回调中修改`store`会导致这个错误，不知道是否还有其他方式去修改全局`store`

**Comment by youtiao66** [comment]
**`Taro` + `@tarojs/mobx`依然存在该问题**
```js
import Taro, { useEffect } from '@tarojs/taro'
import { useLocalStore } from '@tarojs/mobx'
import { View } from '@tarojs/components'

function Test() {
  const store = useLocalStore(() => ({
    count: 0
  }))
  useEffect(
    () => {
      console.log('useEffect')
      store.count = 1
    },
    []
  )
  return (
    <View>{store.count}</View>
  )
}

export default Test
```

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8

因为提前执行的原因，会多执行一次，但接下来的运行是正确的，应该不会造成什么影响

**Comment by youtiao66** [comment]
使用类组件可能不会有大的影响。但当我在Hooks中向服务端请求数据的时候，会造成两次请求，这在我们当前实际业务中难以接受。请问你们是如何看待两次向服务端发送请求这一点的？两次请求可能对服务端也有副作用。你们有不有更好的方式去避免Hooks中出现两次数据请求？

**Comment by youtiao66** [comment]
类组件 constructor 与 render 默认多调用一次影响不大，但 Hooks 中已经不适用，副作用较多：
- 向服务端发送数据请求
- 获取当前时间
- 异步回调，错误处理，Alert弹窗

**Comment by fjc0k** [comment]
@luckyadam 在实现 useState 时应该可以获取到这是预执行还是正式执行吧，是预执行则直接跳过

**Comment by deng-yc** [comment]
遇到同样问题, 直接用`useEffect`没有问题, 加上mobx并且改变状态就会执行两次

**Comment by kotoyo1516** [comment]
我useContext + mobx改变状态也会执行两次

**Comment by 23233** [comment]
同样的问题 +1 希望能解决 不然自己hack 太蠢了!

**Comment by sevenvip** [comment]
同样的问题 +1

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。

**Comment by chris-fung** [comment]
Taro3还是有这个问题

**Comment by airqj** [comment]
@Chen-jj 
taro@3.4.2还有这问题 :(

**Comment by yurentle** [comment]
taro@3.6.18还有这个问题，还不解决吗，或者给个解决方式也好 😑

**Comment by wunanbeiya** [comment]
现在还有呢
