### ISSUE TITLE
taro-native-shell Android运行报错

### ISSUE THREAD

**Issue by Dongfengjie** [NervJS/taro#4494]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
react-native run-android后报错
**复现步骤**
[复现问题的步骤]
1. cd taro-native-shell
2. yarn install
3. react-native run-android

**期望行为**
壳子运行成功

**报错信息**

![image](https://user-images.githubusercontent.com/34671012/65296810-4b848a00-db98-11e9-819b-8444cc306d9c.png)

**系统信息**
👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\39487\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**补充信息**
已经把expo依赖更新到6.0，运行后依旧报错

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/65398210-87159300-dde8-11e9-9aee-7c5519d68013.png)
看起来是因为这个依赖安装失败。

**Comment by Dongfengjie** [comment]
> ![image](https://user-images.githubusercontent.com/9441951/65398210-87159300-dde8-11e9-9aee-7c5519d68013.png)
> 看起来是因为这个依赖安装失败。

依赖装了很多遍，翻墙的，不翻墙的，npm、yarn，都试过了，依旧是这个报错

**Comment by Pines-Cheng** [comment]
使用 Android Studio 启动可能看到的报错信息更全一些，还有，关键错误信息麻烦贴一下文字，方便搜索。

**Comment by Dongfengjie** [comment]
> 使用 Android Studio 启动可能看到的报错信息更全一些，还有，关键错误信息麻烦贴一下文字，方便搜索。
cmd报错如下：
* What went wrong:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
> Could not determine artifacts for com.facebook.fresco:fresco:1.3.0
   > Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/fresco/1.3.0/fresco-1.3.0.aar'.
      > Could not HEAD 'https://jcenter.bintray.com/com/facebook/fresco/fresco/1.3.0/fresco-1.3.0.aar'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
43 actionable tasks: 1 executed, 42 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.ht

Android Studio报错如下：
Emulator: Critical: UpdateLayeredWindowIndirect failed for ptDst=(1188, 97), size=(564x21), dirty=(564x21 0, 0) (连到系统上的设备没有发挥作用。) ((null):0, (null))


网上查了很多，貌似是Gradle的问题？我也不确定这个，大佬能帮忙确定下吗？感激不尽

**Comment by Dongfengjie** [comment]
> 使用 Android Studio 启动可能看到的报错信息更全一些，还有，关键错误信息麻烦贴一下文字，方便搜索。

用Android studio启动taro-native-shell下的Android文件，出现报错ERROR: Could not determine artifacts for com.facebook.fresco:fresco:1.3.0: No cached version available for offline mode

![image](https://user-images.githubusercontent.com/34671012/65406140-2189cc80-de11-11e9-943a-3e32aecd55c6.png)
确实是这个依赖没有装上，但我在翻墙的状态下依旧无法成功安装，网上找了很多方法也都没用

**Comment by Pines-Cheng** [comment]
这个有帮助吗：[“No cached version… available for offline mode.”](https://stackoverflow.com/questions/22607661/no-cached-version-available-for-offline-mode)

确认一下 Android Studio 代理是否生效。

如果是 socks5 代理 ，如下这样设置其实并没有什么用：

```
#systemProp.socks.proxyHost=127.0.0.1
#systemProp.socks.proxyPort=7077

#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=7077

#systemProp.https.proxyHost=socks5://127.0.0.1
#systemProp.https.proxyPort=7077
```

正确设置方法应该是这样：
```
org.gradle.jvmargs=-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=7077
```
修改 `$HOME/.gradle/gradle.properties` 文件,加入上面那句，这样就可以全局开启 gradle 代理。
