### ISSUE TITLE
百度小程序constructor无法在第一次获取props

### ISSUE THREAD

**Issue by kk412027247** [NervJS/taro#4496]
**复现步骤**
[复现问题的步骤]
百度小程序constructor无法在第一次获取props
如果在constructor中把props赋值到state，会引起报错

```
class Index extends Component {

  constructor(props) {
    super(props);
    console.log(props.counter.num)
  }

  config = {
    navigationBarTitleText: '首页'
  };

  render() {
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.props.add}>+</Button>
        <Button className='dec_btn' onClick={this.props.minus}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View><Text>{this.props.counter.num}</Text></View>
        <View><Text>Hello, World</Text></View>
      </View>
    )
  }
}

const mapStateToProps = ({counter}) => ({counter});
const mapDispatchToProps = (dispatch) => bindActionCreators({add, minus, asyncAdd}, dispatch);


export default connect(mapStateToProps, mapDispatchToProps)(Index)

```

全部代码
[https://github.com/kk412027247/swan-app](https://github.com/kk412027247/swan-app)

**期望行为**
可以顺利获取到props中的数据

**报错信息**

![百度小程序](https://user-images.githubusercontent.com/30715186/65298236-5261cb80-db9d-11e9-8072-5e87fc8c6025.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.3.17]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [swan]

**补充信息**
1、百度小程序在第二次渲染的时候，可以获取到整个props数据
2、微信小程序 没有这个bug

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
文档里有注明

**Comment by kk412027247** [comment]
原来如此，但是目前发现 头条和微信小程序都没有这个bug，只有百度会出现
