### ISSUE TITLE
【微信小程序】子组件里 map 生成的第2层子组件，在数据更新时无法正确获取props并更新

### ISSUE THREAD

**Issue by ignous** [NervJS/taro#4497]
**问题描述**
子组件里 map 生成的第2层子组件，在数据更新时无法正确获取props并更新

**复现步骤**
[复现问题的步骤]
1. 正常显示  
<img width="408" alt="WX20190920-115829@2x" src="https://user-images.githubusercontent.com/5868138/65298432-154a0900-db9e-11e9-920d-db0c3e5801b0.png">

2. 点击界面上的 refresh 按钮
3. 错误显示
<img width="413" alt="WX20190920-115853@2x" src="https://user-images.githubusercontent.com/5868138/65298445-20049e00-db9e-11e9-9086-0e2403b142fb.png">

pages/index
```js
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'
import './index.css'

import InfoList from '../../components/info-list';

let key = 0;

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页'
  }

  state: {
    items: any[]
  } = {
    items: []
  }

  componentDidMount () {
    this.refresh();
  }

  refresh = () => {
    console.log('refresh');
    let count = 2;
    let newItems: any[] = [];
    for (let i = 0; i < count; i++ ){
      ++key;
      newItems.push({
        key: 'id-' + key,
        text: 'text-' + key
      })
    }
    console.log(newItems)

    this.setState({
      items: newItems
    })
  }

  render () {
    const { items } = this.state;
    console.log(items)

    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <InfoList items={items} />
        <Text>Hello world! AAA</Text>

        <Button onClick={this.refresh}>refresh</Button>
      </View>
    )
  }
}
```

components/info-list
```js
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

import Info from '../info';

export default class InfoList extends Component<any> {
  render () {
    const { items } = this.props;

    console.log('info-list', items);

    return (
      <View>
        <View>Info List</View>
        {
          items.map((item) => {
            const itemKey = item.key;
            const itemText = item.text;
            const itemData = item;

            return (
              <View key={itemKey}>
                <Info
                  key={itemKey}
                  item={itemData}
                  text={itemText}
                  renderMore={(
                    <View>{itemKey}</View>
                  )}
                ><View>children-{itemKey}</View></Info>
              </View>
            )
          })
        }
        <View>Info List End</View>
      </View>
    )
  }
}
```

components/info
```js
import Taro from '@tarojs/taro';
import { View } from '@tarojs/components'

// import Box from '../box';
export default function Info (props) {
  const { item } = props;

  console.log('info item', item);

  const computeValue = item ? 'computeValue' + item.text + item.key : 'no-item'

  return (
    <View>
      <View>{props.renderMore}</View>
      <View>{props.children}</View>
      <View>{computeValue}</View>
    </View>
  )
}
```

**期望行为**
refresh 后也能正确显示

**报错信息**

无

**系统信息**
👽 Taro v1.3.15

  Taro CLI 1.3.15 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - ~/.nvm/versions/node/v8.9.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v8.9.3/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v8.9.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-qq: 1.3.18 => 1.3.18 
      @tarojs/taro-quickapp: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18 

**补充信息**
<img width="381" alt="WX20190920-120115@2x" src="https://user-images.githubusercontent.com/5868138/65298523-678b2a00-db9e-11e9-8193-4700830dd92f.png">
可以看到更新了4次（数组里有2个元素，所以都更新了2次）

2次init， key变化导致了init的发生
<img width="405" alt="WX20190920-120308@2x" src="https://user-images.githubusercontent.com/5868138/65298646-ce104800-db9e-11e9-932c-d41cd799f881.png">
<img width="398" alt="WX20190920-120324@2x" src="https://user-images.githubusercontent.com/5868138/65298647-cea8de80-db9e-11e9-9f2c-f9b8198dbb2d.png">

2次 update
<img width="595" alt="WX20190920-120352@2x" src="https://user-images.githubusercontent.com/5868138/65298648-cea8de80-db9e-11e9-9e4d-568229ccec4b.png">
<img width="607" alt="WX20190920-120413@2x" src="https://user-images.githubusercontent.com/5868138/65298650-cea8de80-db9e-11e9-9a49-487e2df4b288.png">
根据断点猜测 很可能 update和init 操作到都是不同的组件，导致正确都数据没有更新到新挂载到组件上

**Comment by Chen-jj** [comment]
@ignous CLI 和依赖版本保持一致。

**Comment by ignous** [comment]
更新了， 但是问题还是存在
<img width="496" alt="WX20190923-103032@2x" src="https://user-images.githubusercontent.com/5868138/65399127-8b907a80-dded-11e9-8c4f-7bb1c9a515ad.png">

**Comment by Chen-jj** [comment]
@ignous components/info-list 中的 View 组件不要加 key。taro 的 props 系统在这种情况下会和微信的 diff 算法有冲突。

**Comment by ignous** [comment]
![image](https://user-images.githubusercontent.com/5868138/66694473-538ea000-ece6-11e9-9064-621f46565fb2.png)
这里应该是 compid生成规则里没有使用key，单纯的使用index导致的吧，index和key不同步就会有问题吧

**Comment by ignous** [comment]
anonIdx换成 key就正常了， 可能需要转换的时候做更多的判断吧

**Comment by Chen-jj** [comment]
@ignous 这么说吧，这是歪打正着的结果。

#### 初次渲染

genCompid 为自定义组件生成组件 id，假设 1，2。然后把 props 放进 propsManager。

propsManager:

```js
{
  '1': {
    key: 'id-1'
  },
  '2': {
    key: 'id-2'
  }
}
```

#### 点击按钮

点击按钮后会跑父组件的 render 逻辑，重新 genCompid 生成组件 id，还是 1 和 2。然后把 props 放进 propsManager。

propsManager:

```js
{
  '1': {
    key: 'id-3'
  },
  '2': {
    key: 'id-4'
  }
}
```

因为加了 key，会先卸载两个 info 组件，再加入两个。

错误原因：info 组件 unmount 时会把 propsManager 中对应的 props 对象销毁。

propsManager:

```js
{}
```

新创建的两个 info 组件再到 propsManager 中取 props 时，对应的 props 已经被销毁，所以props 为空。

#### 不加 key

不加key，diff 算法不会销毁 info，走组件更新逻辑，因此没有问题。

#### anonIdx 换成 key

在点击按钮时，key 是用户逻辑，会自增，genCompid 会生成 3 和 4。

```js
{
  '1': {
    key: 'id-1'
  },
  '2': {
    key: 'id-2'
  },
  '3': {
    key: 'id-3'
  },
  '4': {
    key: 'id-4'
  }
}
```

然后 propsManager[1]、propsManager[2] 即使被删除，还是不影响获取 props。

但这样会导致内存泄漏。

**Comment by ignous** [comment]
1. 卸载，再重新创建2个新的子组件我觉得是个挺常见的操作，特别是处理子组件没有多的处理props update，那种功能复杂，update里处理不到位的子组件。

2. 内存溢出产生原因不是很明白，compid生成规则从index到key后， key=1,key=2组件unmount的时候为什么无法清理对应propsManager中的数据， 感觉处理应该是类似的？ 这里逻辑我还没看过不是很确定

主要是感觉这个问题，使用map得建议不加key了...  这个感觉和之前用react的用法推荐正好相反呀

**Comment by ignous** [comment]
当然不是我上面说明的那个直接index换key的写法哈。。  只是在想compid 的规则调整下，是不是能解决这个问题，如果能愉快的使用key，代码写起来会更舒服哈

**Comment by ignous** [comment]
> 因为加了 key，会先卸载两个 info 组件，再加入两个。
> 
> 错误原因：info 组件 unmount 时会把 propsManager 中对应的 props 对象销毁。

话说这个原因我很认同，我的初步推测也是卸载然后新增导致的

**但是为啥是建议去掉key呀...**
这个建议不能理解呀，我本来想是不是是能在 **编译时** compid的生成规则就会考虑react key的因素，让propsMange里的数据和实际生成的组件保证一致

** 内存溢出的说法 **
![image](https://user-images.githubusercontent.com/5868138/66703225-e52bfb00-ed42-11e9-9f29-f1a22abfdd8f.png)
我也是实际测试了，如图并不会，unment很好的卸载了数据

当然我改的也比较粗暴，直接把anidx改成了key 

我在想 **是不是有其他原因不能key** 
比如 其他小程序端对 key的处理不一样（其他小程序我不太熟悉，微信小程序是有key的）。希望能被告知
