### ISSUE TITLE
由于依赖的版本升级导致的Error: ENOENT: no such file or directory, open 'util' 

### ISSUE THREAD

**Issue by dujiahui0918** [NervJS/taro#4498]
**问题描述**
npm run dev:weapp的时候报错 Error: ENOENT: no such file or directory, open 'util'

**复现步骤**
[复现问题的步骤]
1. rm -rf node_modules 
2. npm i
3. npm run dev:weapp

**期望行为**
正确运行 不报错

**报错信息**

![image](https://user-images.githubusercontent.com/24837120/65307929-8b109d80-dbbb-11e9-9655-3f27da41818e.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS 10.14]
 - Taro 版本 [Taro v1.3.4]
 - Node.js 版本 [v8.11.1]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by dujiahui0918** [comment]
问题原因：es-abstract 这个包里面引用了object-inspect,object-inspect里面用了node的util。es-abstract  v1.14.0升级新引入了object-inspect,目前看v1.13.0是没有引入这个包的。
 

        
![image](https://user-images.githubusercontent.com/24837120/65308386-8a2c3b80-dbbc-11e9-9807-f15ed78e9987.png)

![image](https://user-images.githubusercontent.com/24837120/65308618-0a52a100-dbbd-11e9-8d79-24abec9067b6.png)

解决方案：
1.在项目package.json手动加入"es-abstract": "1.13.0"
![image](https://user-images.githubusercontent.com/24837120/65308939-aed4e300-dbbd-11e9-8e5a-f497b0ae8da9.png)
2.rm -rf node_modules
3.npm i
4.npm run dev:weapp
5.运行正常结果如图：
![image](https://user-images.githubusercontent.com/24837120/65309208-34f12980-dbbe-11e9-9249-94eca4f69e5d.png)


个人建议：建议taro加强依赖包的版本控制，防止依赖升级的时候无感知出现类似 问题。

**Comment by luckyadam** [comment]
es-abstract 不是 taro 的包，taro 的运行时框架也没有依赖他，应该是你自己直接安装或者某些依赖包引入的，版本应该你自己控制
