### ISSUE TITLE
自定义组件设置行内样式无效

### ISSUE THREAD

**Issue by yjgeek** [NervJS/taro#4501]
**问题描述**
给自定义组件加上行内样式无效，原生的是可以的

**复现步骤**
index.tsx
```js
// Select 我自定义的组件
render(){
    return <Select style="width: 100%" />
}
```
原生的
```html
<!--select 是我自定义的组件-->
<select style="width: 100%" />
```

**期望行为**
自定义组件能保留行内样式

**报错信息**
组件的行内样式原生是可以的。但是在taro就没了，导致我定义的组件不能自适应父元素宽度

原生截的图
![5713BFDC-B169-4727-9E39-0ECEAC0000C1](https://user-images.githubusercontent.com/18167335/65366901-a8497880-dc5c-11e9-99ca-b950adf0e1ec.png)

**系统信息**
 - 操作系统: [Windows 10]
 - Taro 版本 [v1.3.18]
 - Node.js 版本 [v11.12.0]
 - 报错平台 [weapp]

**Comment by ZakaryCode** [comment]
自定义组件传入的参数，应当是你在组件内部去处理的。（如果没有在自定义组件内处理 style，那么编译时也不会处理这个参数
