### ISSUE TITLE
H5 Taro.navigateTo 跳转报错

### ISSUE THREAD

**Issue by fuersite** [NervJS/taro#4504]
H5上 Taro.navigateTo跳转失败
```javascript
Taro.navigateTo({
      url: `/pages/bus/index?merchant_id=${merchant_id}`,
 });
```

Error:
Uncaught (in promise) {errMsg: "navigateTo:fail history.push is not a function"}

<img width="952" alt="WX20190922-071157@2x" src="https://user-images.githubusercontent.com/20378359/65380172-4c3c2e00-dd08-11e9-9761-1547870ba823.png">

**Comment by ZZsimon** [comment]
我也碰到了这个问题，把脚手架和框架升级到最新版本解决了。 @fuersite

**Comment by fuersite** [comment]
@ZZsimon 是的脚手架跟框架版本不一致导致的，我今天同步了版本就好了，谢谢你
