### ISSUE TITLE
在 H5 平台上无法创建 createInnerAudioContext 

### ISSUE THREAD

**Issue by justpsvm** [NervJS/taro#4506]
**问题描述**
在 H5 平台上无法创建 createInnerAudioContext ,微信小程序正常。

**复现步骤**
[复现问题的步骤]
1. 创建一个 createInnerAudioContext 实例 

相关代码:
```js
let audio = Taro.createInnerAudioContext()
```

**期望行为**
正常创建 createInnerAudioContext 实例。

**报错信息**

在 H5 平台报错如下: 
![图片](https://user-images.githubusercontent.com/11767814/65386089-a8836a00-dd69-11e9-987c-8d72f4d4faee.png)

**系统信息**

 - 操作系统: [macOS 10.14.6]
 - Taro 版本 [v1.3.18]
 - Node.js 版本 [12.10.0]
 - 报错平台 [h5]

**Comment by luckyadam** [comment]
H5 上还没支持
