### ISSUE TITLE
mobx inject & observer 的class 类被继承时小程序和H5表现不一致

### ISSUE THREAD

**Issue by codingwesley** [NervJS/taro#4507]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

当一个 inject & observer 的Class类被继承时，执行的逻辑小程序和H5是有差异的的

小程序正确
H5不正确

**复现步骤**

我做了一个demo

https://github.com/codingwesley/taro-demo

[复现问题的步骤]
1. 

运行 `yarn run dev:weapp`

小程序运行的控制台能看到log

```
init parent
index.js:108 test name show === sub child
```

2.

运行 `yarn run dev:weapp`

控制台能看到log
```
undefined "=== sub child"
```
父级类不会有log

父级类
```jsx

import Taro, { Component } from "@tarojs/taro"
import { inject, observer } from "@tarojs/mobx"


@inject("counterStore")
@observer
export class Comp extends Component {
  constructor() {
    super()
    console.log("init parent");
  }

  get name() {
    return "test name show"
  }
}

页面类
```jsx
interface Index {
  props: PageStateProps
}

@inject("counterStore")
@observer
class Index extends Comp {

  render() {
    console.log(this.name, "=== sub child")

    const {
      counterStore: { counter }
    } = this.props
    return (
      <View className="index">
        <Text>{counter}</Text>
      </View>
    )
  }
}

export default Index as ComponentType

```

**期望行为**
和小程序的行为保持一致，都有log

**系统信息**
➜  ~ taro info
👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm

**补充信息**

我测试过是加了mobx的装饰器引起的，希望能解释一下为什么，谢谢！！！

**Comment by nanjingboy** [comment]
@codingwesley 这是因为你的 `Comp` 没有 `render` 方法，另外建议只在需要引用 `observable` 对象时再对组件进行 `inject` 和 `observer`

**Comment by nanjingboy** [comment]
@codingwesley 已修复，等新版本发布可再更新试试。

**Comment by codingwesley** [comment]
> @codingwesley 已修复，等新版本发布可再更新试试。

谢谢，下个发布计划是什么时候？

**Comment by nanjingboy** [comment]
@codingwesley 也就这几天吧
