### ISSUE TITLE
安卓 使用redirectTo跳到下一个页面 并没有销毁当前页面，返回后，componentDidMount会重复累加执行

### ISSUE THREAD

**Issue by xiangjiejie** [NervJS/taro#4508]
> Feature Request 请提到 [FeatHub](https://feathub.com/NervJS/taro)

> Taro 使用上的问题请提到 [Taro 社区——让每一次交流被沉淀](https://taro-club.jd.com/)

如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
安卓 使用redirectTo 结合pushState 跳到下一个页面 并没有销毁当前页面，返回后，componentDidMount会重复累加执行

**复现步骤**
[复现问题的步骤]
1、

使用redirectTo 跳转下一页
// console.log('componentDidMount')
}

2、 返回上一页
componentDidMount 执行了两次

js

```
 componentDidMount () {
    console.log('componentDidMount')
    this.redirectTo()
  }
redirectTo () {
window.history.pushState({}, '', `#a`)
Taro.redirectTo({
      url:'a'
 })

```

**期望行为**
返回回来，componentDidMount 执行一次

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: 安卓
 - Taro 版本 [3.1.15]
 - 报错平台  H5

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
Duplicate of #4509
