### ISSUE TITLE
安卓微信内使用navigatorTo跳转，返回后，componentDidMount 会再次执行

### ISSUE THREAD

**Issue by xiangjiejie** [NervJS/taro#4509]
**问题描述**
安卓微信内使用navigatorTo跳转，返回后，componentDidMount 会再次执行

**复现步骤**
1、安卓手机微信内，使用navigatorTo跳转后返回上一页，上一页的componentDidMount会执行，componentDidHide也会执行
iOS内不会执行

```js

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
返回后 componentDidMount 不再执行

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: 安卓
 - Taro 版本  1.3.15
 - Node.js 版本 
 - 报错平台  H5微信

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by ZakaryCode** [comment]
可以尝试升级下版本
