### ISSUE TITLE
支付宝canvasId异常

### ISSUE THREAD

**Issue by yutao331763646** [NervJS/taro#4511]
`   <Canvas class="canvas"
                        onTouchend={this.onTouchEnd.bind(this)}
                        onTouchStart={this.onTouchStart.bind(this)}
                        onTouchmove={this.onTouchMove.bind(this)}
                        canvas-id="canvas"
                        canvasId='canvas'
                        id="canvas"></Canvas>`

在支付宝编译之后 id为this

`<canvas id="this"></canvas>`

**Comment by Wuwei9536** [comment]
我也遇到同样的问题，canvas编译错误
