### ISSUE TITLE
微信小程序打包时上传图片问题

### ISSUE THREAD

**Issue by litao1993** [NervJS/taro#4513]
**问题描述**
我现在有一个需求：需要在打包时将图片上传到oss，需要使用webpack插件(webpack-aliyun-oss)，但是小程序打包好像不支持webpack插件，我要怎么做

**复现步骤**
无

**Comment by luckyadam** [comment]
暂时还不能直接支持，只能再单独写个脚本来上传

**Comment by litao1993** [comment]
> 暂时还不能直接支持，只能再单独写个脚本来上传

好的
