### ISSUE TITLE
H5安卓微信内，使用Taro.navigatorTo 跳转，然后返回，render会不断叠加

### ISSUE THREAD

**Issue by xiangjiejie** [NervJS/taro#4514]
**问题描述**
H5安卓微信内，使用Taro.navigatorTo 跳转，然后返回，render会不断叠加
导致数据多了就会卡

iOS 表现正常

**复现步骤**
[复现问题的步骤]
1、加载页面，render 打印一次
1、使用Taro.navigateTo 跳转下一个页面
2、返回，render 打印的次数倍增

js
```
Taro.navigateTo({
url:'a'
})

render() {
console.log('render')
return null
}

```

**期望行为**

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  安卓 微信 H5
 - Taro 版本  1.3.19
 - Node.js 版本 
 - 报错平台  H5

**补充信息**
经过测试，返回后，页面重复DOM存在 2个

![image](https://user-images.githubusercontent.com/10069039/65410411-de355b00-de1c-11e9-9a91-a2559add5ba7.png)

**Comment by ZakaryCode** [comment]
可以升级新版本看看能否复现这个问题
