### ISSUE TITLE
taro 转出来的小程序 代码 onTabItemTap 事件失效，使用原生代码可以触发事件

### ISSUE THREAD

**Issue by AsherSun** [NervJS/taro#4517]
**问题描述**
使用taro开发支付宝小程序， onTabItemTap 事件失效。使用支付宝小程序原生代码测试，是可以触发事件的，已亲自测试过。

**复现步骤**
[复现问题的步骤]
1. 在设置为tabBar页面中添加 onTabItemTap 事件函数
2. 点击tabBar item ，在支付宝小程序中并不会触发该事件函数

![image](https://user-images.githubusercontent.com/28916706/65421097-78090200-de35-11e9-9b98-ffb92782d640.png)

**期望行为**
onTabItemTap 事件函数可以触发

**系统信息**
👽 Taro v1.3.13

  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.13 => 1.3.13 
      @tarojs/components: 1.3.13 => 1.3.13 
      @tarojs/plugin-babel: 1.3.13 => 1.3.13 
      @tarojs/plugin-csso: 1.3.13 => 1.3.13 
      @tarojs/plugin-less: ^1.3.13 => 1.3.17 
      @tarojs/plugin-sass: 1.3.13 => 1.3.13 
      @tarojs/plugin-uglifyjs: 1.3.13 => 1.3.13 
      @tarojs/redux: 1.3.13 => 1.3.13 
      @tarojs/redux-h5: 1.3.13 => 1.3.13 
      @tarojs/router: 1.3.13 => 1.3.13 
      @tarojs/taro: 1.3.13 => 1.3.13 
      @tarojs/taro-alipay: 1.3.13 => 1.3.13 
      @tarojs/taro-h5: 1.3.13 => 1.3.13 
      @tarojs/taro-qq: 1.3.13 => 1.3.13 
      @tarojs/taro-swan: 1.3.13 => 1.3.13 
      @tarojs/taro-weapp: 1.3.13 => 1.3.13 
      @tarojs/webpack-runner: 1.3.13 => 1.3.13 
      eslint-config-taro: 1.3.13 => 1.3.13 
      eslint-plugin-taro: 1.3.13 => 1.3.13 
      nervjs: ^1.4.3 => 1.4.3 
    npmGlobalPackages:
      typescript: 3.2.1

 - 操作系统: maOs
 - Taro 版本: 1.3.13
 - Node.js 版本 v10.15.3
 - 报错平台 支付宝小程序

**补充信息**
- 微信小程序使用taro编译出来的代码可以触发事件
- 支付宝小程序使用taro 编译出来的代码不能触发事件
- 支付宝小程序使用原生代码绑定 onTabItemTap 事件可以触发
- 其余小程序没有测试过

**Comment by AsherSun** [comment]
@luckyadam 前辈，为什么要关掉该Issue。是问题不能复现吗？

**Comment by Jetsly** [comment]
> @luckyadam 前辈，为什么要关掉该Issue。是问题不能复现吗？

因为前辈修复了吧
