### ISSUE TITLE
TARO转快应用时，依赖环境安装出现错误

### ISSUE THREAD

**Issue by Issacpeng** [NervJS/taro#4518]
**问题描述**
TARO转快应用时，依赖环境安装出现错误

**复现步骤**
1.正常转换成功后，进入环境依赖安装流程

**期望行为**
依赖安装正常

**报错信息**
`生成  依赖文件  dist/src/utils/util.js
生成  页面样式  dist/src/pages/index/index.css
生成  页面样式  dist/src/pages/index/map.css
生成  页面样式  dist/src/pages/logs/logs.css

监听文件修改中...

✔  快应用容器已经准备好

- 安装快应用依赖环境, 需要一会儿...'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
× 快应用依赖环境安装失败，请进入 dist 重新安装！
Error: Command failed: NODE_ENV=development npm install
'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

快应用环境准备失败，请重试！
Waiting for the debugger to disconnect...`

<img width="428" alt="捕获" src="https://user-images.githubusercontent.com/11417652/65479666-ec3cb780-dec0-11e9-9b93-8429449b2751.PNG">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.3.18]
 - Node.js 版本 [v12.10.0]
 - 报错平台 [quickApp]

**补充信息**
解决思路：
    是由于WINDOW下不支持NODE_ENV设置造成，
1）直接调用npm run install
2)  安装cross_env等库，支持在window种跨平台支持NODE_ENV配置

**Comment by slixina** [comment]
你好，我也遇到了这个问题，请问解决了吗

**Comment by Issacpeng** [comment]
@slixina 已修复，根据环境不同做了区分处理
