### ISSUE TITLE
Taro hook 组件中怎么获取当前组件的实列?

### ISSUE THREAD

**Issue by hqwlkj** [NervJS/taro#4521]
**问题描述**
在使用 `canvas`的 `createCanvasContext` 方法时，需要传入一个当前组件的实列；
使用hook，是获取不到当前组件的`this`，那么我们在使用`createCanvasContext`方法第二个参数传递什么呢？
例： `const context: Taro.CanvasContext = Taro.createCanvasContext('poster-canvas', this);`,
这里传入的`this`是获取不到的。

**复现步骤**

```js
const Poster=()=>{
      useDidShow(() => drawBall());

      const drawBall=()=>{
            console.log('this', this); // => undefined
            const context: Taro.CanvasContext = Taro.createCanvasContext('poster-canvas', this);
      }

     return <View>
         <Canvas className='poster-canvas' canvasId='poster-canvas' />
     </View>
}
export default Poster;

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-less: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/rn-runner: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18 
    npmGlobalPackages:
      typescript: 3.5.1
**补充信息**

[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zzyyzz1992** [comment]
我感觉是不是加上一个hook就可以？
useCanvasContext

**Comment by hqwlkj** [comment]
但是目前没有这个 `useCanvasContext ` hook

**Comment by luckyadam** [comment]
暂时写 this.$scope

**Comment by hqwlkj** [comment]
`this` 都是一个 `undefined` ，怎么可能有 `this.$scope`。
![image](https://user-images.githubusercontent.com/12181423/65489491-d689bb00-dedd-11e9-92e3-5d6614c8788f.png)

**Comment by fjc0k** [comment]
这里有个 Taro 工具库已实现 useScope: https://github.com/fjc0k/vtils/tree/master/packages/taro#usescope
