### ISSUE TITLE
taro小程序：父组件传值子组件，子组件拿到值后更新setState保存，然后父组件传递给子组件的props值就改了！！！

### ISSUE THREAD

**Issue by weiweixuan** [NervJS/taro#4525]
## taro小程序：父组件传值子组件，子组件拿到值后更新setState保存，然后父组件传递给子组件的props值就改了！！！

![image](https://user-images.githubusercontent.com/40062338/65501027-ccbe8280-def2-11e9-8f8d-67952135ba95.png)

![image](https://user-images.githubusercontent.com/40062338/65501200-232bc100-def3-11e9-8414-3dbad2e6f55e.png)

![image](https://user-images.githubusercontent.com/40062338/65501367-769e0f00-def3-11e9-8b38-e5b8606b0c0c.png)

### h5是OK的，应该是小程序内部机制问题，希望官方解决一下，感谢

**Comment by Chen-jj** [comment]
@weiweixuan 请按照 issue 模板提供一切必要信息，最好有个完整可复现 demo。
