### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by DBCdouble** [NervJS/taro#4528]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
定义了一个使用了hook的函数组件，在父class组件中引用编译报错
**复现步骤**
[复现问题的步骤]

[代码只贴截图，不贴文字会被视为无效issue]
![image](https://user-images.githubusercontent.com/22364324/65505259-5f631f80-defb-11e9-98ec-25309a66b197.png)
![image](https://user-images.githubusercontent.com/22364324/65505279-6722c400-defb-11e9-9809-c95b53bc2092.png)
![image](https://user-images.githubusercontent.com/22364324/65505285-6db13b80-defb-11e9-8558-b22374db07ee.png)
![image](https://user-images.githubusercontent.com/22364324/65505294-71dd5900-defb-11e9-8263-a6cde926c9fa.png)

**期望行为**

**报错信息**
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [v1.3.18]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [weapp]

**补充信息**

**Comment by snokier** [comment]
+1

**Comment by luckyadam** [comment]
能否给个可以运行的 demo
