### ISSUE TITLE
taro 路由跳转参数都变成string类型了

### ISSUE THREAD

**Issue by wzhsh90** [NervJS/taro#4531]
本来传递的参数是整型，但在第2个界面，获取的时候this.$router.params打印出来却是string

**Comment by luckyadam** [comment]
小程序还是 H5

**Comment by wzhsh90** [comment]
小程序




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午2:36
收件人: "NervJS/taro"<taro@noreply.github.com>;
抄送: "@"小万"^^$"<624837932@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NervJS/taro] taro 路由跳转参数都变成string类型了 (#4531)




小程序还是 H5

**Comment by luckyadam** [comment]
小程序自己处理的

**Comment by wzhsh90** [comment]
好的，肯定是自己要处理的，只是看官方例子是不一致才反馈的。




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午2:55
收件人: "NervJS/taro"<taro@noreply.github.com>;
抄送: "@"小万"^^$"<624837932@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NervJS/taro] taro 路由跳转参数都变成string类型了 (#4531)




小程序自己处理的

**Comment by luckyadam** [comment]
收到，我们看看
