### ISSUE TITLE
map循环中key使用解构赋值等处理时渲染有问题

### ISSUE THREAD

**Issue by MingNeo** [NervJS/taro#4535]
**问题描述**
使用map循环时给元素加的key属性，如果使用解构赋值/lodash.get等方法取对象中id放到变量里，当列表内容变化时就会显示错乱。使用index反而没有问题。

**复现步骤**

![image](https://user-images.githubusercontent.com/4495272/65586933-9565d980-dfb7-11e9-8c38-2df311d59387.png)
这样会出错，列表中新增一条数据后会显示错乱，新增的item的位置上重复显示之前的项。

这样显示正常
![image](https://user-images.githubusercontent.com/4495272/65587301-394f8500-dfb8-11e9-8a20-478f21156bce.png)

![image](https://user-images.githubusercontent.com/4495272/65587266-2ccb2c80-dfb8-11e9-9c41-80dfcf417d65.png)

**期望行为**
正常处理map循环

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

  Taro CLI 1.3.17 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.17 => 1.3.17 
      @tarojs/components: 1.3.17 => 1.3.17 
      @tarojs/plugin-babel: 1.3.17 => 1.3.17 
      @tarojs/plugin-csso: 1.3.17 => 1.3.17 
      @tarojs/plugin-sass: 1.3.17 => 1.3.17 
      @tarojs/plugin-uglifyjs: 1.3.17 => 1.3.17 
      @tarojs/redux: 1.3.17 => 1.3.17 
      @tarojs/rn-runner: 1.3.17 => 1.3.17 
      @tarojs/router: 1.3.17 => 1.3.17 
      @tarojs/taro: 1.3.17 => 1.3.17 
      @tarojs/taro-h5: 1.3.17 => 1.3.17 
      @tarojs/taro-weapp: 1.3.17 => 1.3.17 
      @tarojs/webpack-runner: 1.3.17 => 1.3.17 
      eslint-config-taro: ^1.3.17 => 1.3.17 
      eslint-plugin-taro: ^1.3.17 => 1.3.17 
      nervjs: ^1.4.3 => 1.4.4 
    npmGlobalPackages:
      typescript: 3.5.1

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
