### ISSUE TITLE
不支持jsotp

### ISSUE THREAD

**Issue by yutao331763646** [NervJS/taro#4537]
不支持jsotp  为什么啊    啊

**Comment by iugo** [comment]
是这个吗? https://www.npmjs.com/package/jsotp

这是后端要做的, 和 Taro 没什么关系呀.

**Comment by yutao331763646** [comment]
> 是这个吗? https://www.npmjs.com/package/jsotp
> 
> 这是后端要做的, 和 Taro 没什么关系呀.

这个是前端的 是我自己把key搞错了

**Comment by yutao331763646** [comment]
不好意思是我自己把otpkey搞错了，关了吧
