### ISSUE TITLE
对于 lerna 产生的快捷方式文件夹扫描任然报错

### ISSUE THREAD

**Issue by tangbc** [NervJS/taro#4538]
### 问题描述
当 taro 和 lerna 结合使用时对于 lerna 产生的快捷方式文件夹扫描任然报错。

之前提了个 issue #4431 ，发现昨天 `1.3.19` 已经更新了，试了下，还是扫描出错，所以上传了个复现 demo

### 复现步骤：

先全局安装 [taro](https://github.com/NervJS/taro) 和 [lerna](https://github.com/lerna/lerna )；

然后：

```bash
git clone https://github.com/tangbc/taro-lerna-demo

cd taro-lerna-demo/

npm install

lerna bootstrap // lerna 包建立连接关系

npm run dev:h5
```

### 报错信息：

```bash
 Taro v1.3.19

开始编译项目 lerna-tets
创建  发现文件  src/.DS_Store
创建  发现文件  src/app.less
创建  发现文件  src/app.tsx
创建  发现文件  src/index.html
创建  发现文件  src/packages/.DS_Store
创建  发现文件  src/pages/package.json
创建  发现文件  src/packages/utils/index.ts
创建  发现文件  src/packages/utils/package.json
创建  发现文件  src/pages/index/index.less
创建  发现文件  src/pages/index/index.tsx
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat '/Users/mymac/github/packages/utils'
Emitted 'error' event at:
    at /usr/local/lib/node_modules/@tarojs/cli/node_modules/klaw/src/index.js:28:26
    at callback (/usr/local/lib/node_modules/@tarojs/cli/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
```

### 原因猜测

因该是扫描文件夹快捷方式时的源路径寻找错误：`lstat '/Users/mymac/github/packages/utils'` 。

**Comment by luckyadam** [comment]
hello~ 抱歉，由于之前很忙，这个问题一直没来得及看，我看了你的仓库，发现是一个 Taro 项目里包含了 lerna 包管理，这种方式目前暂时不支持，目前可以支持在 Taro 项目之外使用 lerna 来管理，结构如下
             
    ├── packages           
    |   ├── taroproj   
    |   └── util          
    └── lerna.json

**Comment by tangbc** [comment]
好的，如果后期这个支持了麻烦在这个 issue 注明下，我们好更新到这种形式。

试了下如果这样组织也是报错的：
```bash
├── packages           
|   ├── taroproj   
|   └── util          
└── lerna.json
```

Taro 编译 src 选择 `taroproj` 目录后，始终无法通过快捷方式引用 `util` 文件夹下的文件。
