### ISSUE TITLE
0.0.73升级到beta.9之后找不到组件的错误

### ISSUE THREAD

**Issue by clarktang** [NervJS/taro#454]
**问题描述**
在0.0.73上面可以正常使用，升级到beta.9之后，很多自定义组件都无找不到。

![image](https://user-images.githubusercontent.com/37982974/44029541-3a89c92c-9f30-11e8-925b-f0d463d03b9f.png)

大量的自定义组件出现上面的错误，到底是什么原因导致的？

**期望行为**
小版本升级不要出现这种运行不起来的问题

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: macos
 - Taro beta.9
 - Node.js: 10.6.0

**Comment by yuche** [comment]
请问你在 beta.8 有遇到相同的问题吗

**Comment by clarktang** [comment]
@yuche , 我之前应该是0.0.73，估计是使用了taro update project之后没有修改parkage.json。我应该当时还处于0.0.73中。升级到1.0之后组件写法上有什么改变吗？为什么大面积的组件无法使用？

**Comment by clarktang** [comment]
@zacksleo , 试了很多种办法都还是一样的各种组件 not defined，尤其是页面组件引用自定义组件，然后自定义组件再引用自定义组件，这种多层次的组件嵌套，基本最后一层的自定义组件都是not defined

**Comment by zacksleo** [comment]
我感觉是在 73 和 beta 的版本切换中发生的这个问题，要不然你彻底清理下，重新安装呢

**Comment by luckyadam** [comment]
编译过程中有没有出现报错

**Comment by clarktang** [comment]
@luckyadam , 编译过程中没有任何报错信息。只是模拟器首页大部分的自定义组件undefined

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/44089982-3b3f23dc-9ffb-11e8-8470-21eb4ce512ae.png)
这里的报错可以看下这两个组件的写法么，同时这两个组件的目录结构

**Comment by clarktang** [comment]
@luckyadam ， 没有做任何更改，升级到beta.10就好了。简直哭笑不得

**Comment by HecateDK** [comment]
beta.8也会出现这个问题，如下图，不知道为什么有时候编译的时候，ec-canvas里面只有wxml文件，但等久一点，或者再编译一两次就好了。

![image](https://user-images.githubusercontent.com/19571458/44191991-3f8df380-a160-11e8-8228-d63993fee9c6.png)

**Comment by luckyadam** [comment]
@HecateDK 有一个文件过大了，而且是不需要经过 taro 编译的，可以通过配置排除~ 我稍后更新下文档

**Comment by HecateDK** [comment]
@luckyadam  soga  好的   
```js
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
```
这个警告信息一直被我忽略了哈哈哈

**Comment by luckyadam** [comment]
@HecateDK 已经加上啦~ https://github.com/NervJS/taro/blob/master/docs/config-detail.md#weappcompile

**Comment by vimcaw** [comment]
经常是重启`dev:weapp`服务时遇到，重启一下`微信开发者工具`就好了。
