### ISSUE TITLE
关于页面title设置的问题

### ISSUE THREAD

**Issue by useryechen** [NervJS/taro#4540]
**问题描述**
通过浏览器后退键返回后，再次进入之前的页面，页面的title未修改

**复现步骤**
[复现问题的步骤]
1. 进入A页面，在didMount中设置document.title = A
2. 进入B页面，在didMount中设置document.title = B
3. 通过浏览器返回键，返回A页面，title改变为A
4. 再次进入B页面，页面title还是A

**期望行为**
通过任何操作进入页面，title正常显示

**系统信息**
� Taro v1.3.14

  Taro CLI 1.3.14 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
 - 报错平台 [h5]

**补充信息**
[可选]
再次进入B页面的时候，没有走didMount事件，像触发了浏览器的前进键一样，虽然可以通过didShow来做,但是感觉这应该不是正确的做法吧

**Comment by Littly** [comment]
A页面是高阶组件吗？

**Comment by useryechen** [comment]
> A页面是高阶组件吗？
> 另外，需要提供能够复现的demo

感谢回复，这个应该是我的问题，我通过document.title设置的会有这种问题，通过config配置上的没问题
