### ISSUE TITLE
taro版本1.3.18，函数式组件不支持es6的解构

### ISSUE THREAD

**Issue by hong418884611** [NervJS/taro#4546]
**问题描述**
![image](https://user-images.githubusercontent.com/25003355/65738195-a297db00-e113-11e9-82b2-14dcae951e73.png)
控制台打印a是有值的，但是检查转译后的小程序代码是没有set进data里面(补充下，是加了if就不支持解构了，不加if是支持解构的)
![image](https://user-images.githubusercontent.com/25003355/65738303-e68ae000-e113-11e9-981b-552dda82583a.png)
**复现步骤**
![image](https://user-images.githubusercontent.com/25003355/65738364-1d60f600-e114-11e9-8f76-91bcf8ed85d6.png)
![image](https://user-images.githubusercontent.com/25003355/65738400-441f2c80-e114-11e9-828e-05e5e5ef0fd9.png)
**期望行为**
函数式组件支持解构
**个人分析**
函数式组件加了if之后不支持解构

**Comment by iugo** [comment]
遇到过类似问题, 暂时的解决办法就是减少涉及 JSX 的代码复用. 因为这会导致编译为 template, 从而造成一些问题.

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
