### ISSUE TITLE
【Feature Request】RN环境下的scanCode支持

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#4550]
**问题描述**
RT

**期望行为**
跟小程序行为保持一致

**系统信息**
```
👽 Taro v1.3.18


  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by Pines-Cheng** [comment]
scanCode 的 API 之前有调研过，无论是 `expo-barcode-scanner` 还是社区提供的包，交互和功能都比较粗糙，要想实现微信小程序那样的交互，还是离不开原生的开发，故搁置了。

**Comment by tourze** [comment]
不一定要一模一样吧，起码有这种扫码的接口能兼容先

**Comment by Pines-Cheng** [comment]
那你可以试一下  [expo-barcode-scanner](https://github.com/expo/expo-barcode-scanner)  ，直接使用可能会更加灵活。

**Comment by Pines-Cheng** [comment]
那你可以试一下  [expo-barcode-scanner](https://github.com/expo/expo-barcode-scanner)  ，直接使用可能会更加灵活。

**Comment by tourze** [comment]
好吧
