### ISSUE TITLE
map循环自定义组件数据错乱

### ISSUE THREAD

**Issue by UchihaObitoZzz** [NervJS/taro#4552]
**问题描述**
Taro-ui Tabs组件里使用自定义组件 map循环套map循环，如果2个map的第2个参数名相同会导致列表数据错乱，用原生组件不会出现此问题

**复现步骤**
map遍历原生组件：
![bug1](https://user-images.githubusercontent.com/22854203/65845863-63b19180-e36e-11e9-908e-7fc45d335fd1.jpg)
![bug2](https://user-images.githubusercontent.com/22854203/65845936-a4a9a600-e36e-11e9-9909-76e37a080e92.jpg)

map遍历自定义组件：
![bug3](https://user-images.githubusercontent.com/22854203/65846004-d6227180-e36e-11e9-855e-0da351f80aad.jpg)
![bug4](https://user-images.githubusercontent.com/22854203/65846009-dae72580-e36e-11e9-975e-76f67dd191ac.jpg)

自定义组件代码：
![bug5](https://user-images.githubusercontent.com/22854203/65846016-e8041480-e36e-11e9-9d37-80c3ee2e5854.jpg)

**期望行为**
自定义组件和原生组件map遍历结果应保持一致

**系统信息**
![bug6](https://user-images.githubusercontent.com/22854203/65846113-52b55000-e36f-11e9-93a0-df524ad4c30c.png)

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
@UchihaObitoZzz 看看编译后的代码，循环时生成的 component id，是根据循环下标来保证其唯一性的，下标变量取名一样时因为作用域问题，生成的 component id 即不唯一，props 传递就会有问题。
所以下标变量取名不要相同。

**Comment by UchihaObitoZzz** [comment]
> @UchihaObitoZzz 看看编译后的代码，循环时生成的 component id，是根据循环下标来保证其唯一性的，下标变量取名一样时因为作用域问题，生成的 component id 即不唯一，props 传递就会有问题。
> 所以下标变量取名不要相同。

👌
