### ISSUE TITLE
QuickApp：1.3.18：return ret || {} 转意成 return  {}；

### ISSUE THREAD

**Issue by kongzhe607** [NervJS/taro#4556]
![image](https://user-images.githubusercontent.com/5809518/65864274-2f58c800-e3a4-11e9-9b74-80deaadfd2de.png)
源码

![image](https://user-images.githubusercontent.com/5809518/65864355-50211d80-e3a4-11e9-9dda-0900d675945a.png)
转意后代码
[life.zip](https://github.com/NervJS/taro/files/3669769/life.zip)

**Comment by kongzhe607** [comment]
https://github.com/NervJS/babel-plugin-remove-dead-code

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/bfaaa091435fb00e8d989819b6bf69604d44c3ed
