### ISSUE TITLE
Taro脚手架创建的项目时redux无法使用store.getState()获取到最新状态

### ISSUE THREAD

**Issue by tovinping** [NervJS/taro#4558]
**问题描述**
[问题描述：Taro脚手架创建项目时选择redux;我在组件外的工具函数中需要使用redux无法获取到最新状态]

**复现步骤**
[复现问题的步骤]
在utils/index.js文件中引入store
1.import storeConfig from '../store'
2. const store = storeConfig().getState()
3. console.log(store) // 这时你会发现store的值是初始状态的

```js
import storeConfig from '../store'
export function getRedux(state) {
  const globalState = storeConfig().getState()
  // 若之前有dispatch过store
 // 你会发现这里获取到的globalState竟然是初始值
  return globalState[state]
}
```

**期望行为**
希望优化脚手架(请看补充信息)

**报错信息**
获取到的state是原始状态

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.3.18]
 - Node.js 版本 [e.g. v10.16.0]
 - 报错平台 [weapp]

**补充信息**
原脚架生成的部分代码store/index.js:
export default function configStore () {
  const store = createStore(rootReducer, enhancer)
  return store
}
脚手架生成store/index.js改成这样就可以了：
const store = createStore(rootReducer, enhancer)
export default store

**Comment by luckyadam** [comment]
你写错了，要获取 store 需要这样写
`import { getStore } from '@tarojs/redux'`

而且不建议自己私自调用 store dispatch 来修改状态
