### ISSUE TITLE
context功能在微信小程序上无法触发更新

### ISSUE THREAD

**Issue by calimanco** [NervJS/taro#4563]
**问题描述**
我为了维护全局统一的定时器，给页面增加了PageContainer的组件，并在其中引入SystemTimeContext，而且周期性更新value。
我在组件内使用useContext的时候，在h5上表现正常，但在微信小程序只在初始化的时候拿到值，后续更新并不会触发。

**复现步骤**
1. 新建一个context/index.ts用来存放context。

```js
export const SystemTimeContext = Taro.createContext(0)
```

2. 新建PageContainer.tsx组件

```js
import { SystemTimeContext } from '@/context/index'
function PageContainer({children}) {
  const [time, setTime] = useState(Math.ceil(new Date().getTime() / 1000))
  useEffect(() => {
    Taro.eventCenter.on('clockRun', aimTime => {
      if (aimTime) {
        setTime(aimTime)
      }
    })

    return () => {
      Taro.eventCenter.off('clockRun')
    }
  }, [])
  return (<SystemTimeContext.Provider value={time}>
          {children}
        </SystemTimeContext.Provider>)
}
```

3. 页面上使用PageContainer包在最外层，页面是class风格的，因为redux相关的hooks在h5上不完善

4. 页面上的组件内使用（hooks风格）

```js
import { SystemTimeContext } from '@/context/index'
const systemTime = useContext(SystemTimeContext)
```

**期望行为**
组件接收到更新

**报错信息**
无，在PageContainer中打印时钟更新是可以看到的

**系统信息**
  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.19 => 1.3.19
      @tarojs/components: 1.3.19 => 1.3.19
      @tarojs/plugin-babel: 1.3.19 => 1.3.19
      @tarojs/plugin-csso: 1.3.19 => 1.3.19
      @tarojs/plugin-sass: 1.3.19 => 1.3.19
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19
      @tarojs/redux: 1.3.19 => 1.3.19
      @tarojs/redux-h5: 1.3.19 => 1.3.19
      @tarojs/router: 1.3.19 => 1.3.19
      @tarojs/taro: 1.3.19 => 1.3.19
      @tarojs/taro-alipay: 1.3.19 => 1.3.19
      @tarojs/taro-h5: 1.3.19 => 1.3.19
      @tarojs/taro-swan: 1.3.19 => 1.3.19
      @tarojs/taro-tt: 1.3.19 => 1.3.19
      @tarojs/taro-weapp: 1.3.19 => 1.3.19
      @tarojs/webpack-runner: 1.3.19 => 1.3.19
      eslint-config-taro: 1.3.19 => 1.3.19
      eslint-plugin-taro: 1.3.19 => 1.3.19
      nerv-devtools: ^1.4.6 => 1.4.6
      nervjs: ^1.4.6 => 1.4.6
      react: ^16.10.2 => 16.10.2
      stylelint-config-taro-rn: 1.3.19 => 1.3.19
      stylelint-taro-rn: 1.3.19 => 1.3.19

**补充信息**
无

**Comment by JRliu** [comment]
遇到同样的问题，部分组件正常，部分不会触发重新渲染。。尝试过class和hook的写法，结果一样，暂时没找到规律

**Comment by aoarashi1988** [comment]
试着在源码里调试了一下，我这里的问题是useContext比Provider先触发
在自己代码里保证Provider传值之前没有调用任何useContext相关组件

**Comment by shean012** [comment]
也遇到了无法重新渲染的问题，通过dispatch更新了state，在控制台显示了更新了，正常会触发rerender，useEffect也没有重新执行。

**Comment by xuya227939** [comment]
我也有相同的问题，代码如下：
```
const ThemeContext = Taro.createContext(0);

class App extends Taro.Component {
    render() {
        return (
            <ThemeContext.Provider value={1}>
                <Toolbar />
            </ThemeContext.Provider>
        );
    }
}
  
function Toolbar() {
    return (
        <div>
            <ThemedButton />
        </div>
    );
}
  
class ThemedButton extends Taro.Component {
    static contextType = ThemeContext;
    render() {
        console.log('context', this.context);
        return (
            <Button theme={this.context}>123</Button>
        );
    }
}

export default App;
```

相关依赖，```package.json```：

```
"dependencies": {
    "@tarojs/components": "2.1.5",
    "@tarojs/router": "2.1.5",
    "@tarojs/taro": "2.1.5",
    "@tarojs/taro-alipay": "2.1.5",
    "@tarojs/taro-h5": "2.1.5",
    "@tarojs/taro-qq": "2.1.5",
    "@tarojs/taro-quickapp": "2.1.5",
    "@tarojs/taro-swan": "2.1.5",
    "@tarojs/taro-tt": "2.1.5",
    "@tarojs/taro-weapp": "2.1.5",
    "babel-runtime": "^6.26.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "less-loader": "^4.0.0",
    "lint-staged": "^10.0.8",
    "nerv-devtools": "^1.5.6",
    "nervjs": "^1.5.6",
    "pre-commit": "^1.2.2",
    "stylelint-config-standard": "^18.3.0",
    "taro-axios": "^1.1.1",
    "taro-ui": "^2.2.1"
  },
  "devDependencies": {
    "@tarojs/cli": "2.1.5",
    "@tarojs/mini-runner": "2.1.5",
    "@tarojs/plugin-babel": "2.1.5",
    "@tarojs/plugin-csso": "2.1.5",
    "@tarojs/plugin-less": "2.1.5",
    "@tarojs/plugin-sass": "2.1.5",
    "@tarojs/plugin-uglifyjs": "2.1.5",
    "@tarojs/webpack-runner": "2.1.5",
    "@types/react": "^16.4.6",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.6",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^5.3.0",
    "eslint-config-taro": "2.1.5",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "eslint-plugin-taro": "2.1.5",
    "stylelint": "^9.3.0",
    "stylelint-config-taro-rn": "2.1.5",
    "stylelint-taro-rn": "2.1.5"
  }
```

输出结果
![image](https://user-images.githubusercontent.com/16217324/82968532-1c17fe00-a000-11ea-863b-369cf292a316.png)

**Comment by Chen-jj** [comment]
升级到 Taro3 再试试

**Comment by cr7cr8** [comment]
you need export ThemeContext

**Comment by cr7cr8** [comment]
you need to place into another file ThemeContext, and import it into app.js
