### ISSUE TITLE
[求助]lerna中子包引用@tarojs/taro带来的问题

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#4564]
**问题描述**

我们现在有三个taro项目，代码重复度比较高，主要重复的都是：
1. util 助手方法
2. ui 组件

现在我们尝试使用lerna来重新组织这三个项目，最终的项目结构是：

![image](https://user-images.githubusercontent.com/13899502/66370256-179bc800-e9d2-11e9-9435-476519b8caa7.png)

其中utils/taro-utils是我们封装出来的助手函数，utils这个包不依赖taro。

diy-app / shop-mobile 是我们以前的项目，我们将引用到助手函数的地方都改用包名来使用，似乎没有问题，但是在 npm run dev:h5 时报错了。

![image](https://user-images.githubusercontent.com/13899502/66370331-621d4480-e9d2-11e9-8b28-9abaff75652d.png)

在diy-app中，我们用了 import { hideLoading } from 'taro-util' 然后报错如上图所示。

hideLoading.js的代码很简单：

```
import Taro from '@tarojs/taro';

/**
 * 关闭loading
 */
const hideLoading = () => {
  // TODO 封一层
  return Taro.hideLoading();
};

export default hideLoading;
```

我们是后端转前端的开发，还不是十分熟悉babel/webpack配置，看了下@tarojs/cli 的实现，找不到头绪。想请教下，这种情形我们应该怎么处理？

现在只是助手函数抽出为单独的包都报错了，估计UI库抽出来还会有更多坑。
因为我们没打算发布到npm，都是本地开发，如果像文档描述那样去按照ui库打包再发布不太现实。。。

**系统信息**
```
👽 Taro v1.3.19


  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by tourze** [comment]
up

**Comment by luckyadam** [comment]
> up

正在研究

**Comment by luckyadam** [comment]
能否给一个简易的示例 demo，我跑一下

**Comment by tourze** [comment]
demo地址： https://github.com/tourze/taro_lerna_demo

```
lerna bootstrap
cd packages/taro-shop
npm run dev:h5
```

![image](https://user-images.githubusercontent.com/13899502/66711092-b734ce00-edb7-11e9-8944-6539f62471d0.png)

**Comment by luckyadam** [comment]
> demo地址： https://github.com/tourze/taro_lerna_demo
> 
> ```
> lerna bootstrap
> cd packages/taro-shop
> npm run dev:h5
> ```
> 
> ![image](https://user-images.githubusercontent.com/13899502/66711092-b734ce00-edb7-11e9-8944-6539f62471d0.png)
收到

**Comment by luckyadam** [comment]
这里有两个问题
1、小程序编译没有支持到 yarn workspaces，通过 f6da12350aa33ffb805f76cb486c65353f03a55f 这个 commit 解决了
2、H5 的报错问题，是因为 Taro 编译没有将 npm 包里的 `@tarojs/taro` 替换成对应平台的运行时包名，例如 H5 要替换成 `@tarojs/taro-h5`
![image](https://user-images.githubusercontent.com/1782542/66739881-4f0fe600-eea4-11e9-8c15-d415a71b259e.png)

这个替换操作暂时有点困难，可以将这里的引用https://github.com/tourze/taro_lerna_demo/blob/master/packages/taro-util/lib/hideLoading.js#L1

改写成

```js
let Taro
if (process.env.TARO_ENV === 'h5') {
  Taro = require('@tarojs/taro-h5')
} else if (process.env.TARO_ENV === 'weapp') {
  Taro = require('@tarojs/taro-weapp')
}
```

**Comment by tourze** [comment]
升级到1.3.20了再测试dev:weapp，报错：

```
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.js
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/taro/dist/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/taro/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/taro-weapp/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/promise-polyfill/lib/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/regenerator-runtime/runtime.js
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/async-await/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/redux/dist/index.js
拷贝  NPM文件   packages/diy-app/dist/npm/@tarojs/redux/index.js
缺少npm包@gzcrm/constants，开始安装...
error An unexpected error occurred: "https://registry.npm.taobao.org/@gzcrm%2fconstants: Not found".                                                                                                                                  
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
缺少npm包@gzcrm/constants，开始安装...
```

无法正常编译

**Comment by luckyadam** [comment]
有没有复现的例子

**Comment by tourze** [comment]
发现新的问题，如果在子包中使用 Taro.eventCenter，会报错提示找不到 Taro.eventCenter
![image](https://user-images.githubusercontent.com/13899502/68086298-531c9b80-fe85-11e9-9954-f439c673870a.png)
![image](https://user-images.githubusercontent.com/13899502/68086304-60398a80-fe85-11e9-8233-24ee0d802570.png)

**Comment by tourze** [comment]
经测试，是因为Taro有一些方法是放到 `@tarojs/taro` 里面的，不是放到每个runtime下。。。所以上面要改写成：

```
let Taro = require('@tarojs/taro');

if (process.env.TARO_ENV === 'h5') {
  Object.assign(Taro, require('@tarojs/taro-h5'));
} else if (process.env.TARO_ENV === 'weapp') {
  Object.assign(Taro, require('@tarojs/taro-weapp'));
}
```
config/index.js中有个参数 `weapp.compile.include`，能不能通过这个来控制呢？

**Comment by tourze** [comment]
用我上个回复的方法，依然不行，因为`packages/taro-router/src/router/router.tsx`在这里时会mount一次路由的API。
