### ISSUE TITLE
Picker组件没有样式

### ISSUE THREAD

**Issue by gaorubin1990** [NervJS/taro#4565]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
Picker组件引入后无样式
![image](https://user-images.githubusercontent.com/49272745/66371956-597b3d00-e9d7-11e9-9272-1db55d5b1337.png)

**Comment by Chen-jj** [comment]
@gaorubin1990 Picker 弹层是小程序 picker 弹层。picker 选择结果的样式开发者需要自己写。
