### ISSUE TITLE
[hooks] context如何全局注入小程序中?

### ISSUE THREAD

**Issue by zerokarafont** [NervJS/taro#4567]
**问题描述**
我有一个context的全局组件<AppProviders></AppProviders>包裹顶层<App />， 发现并没有执行
**复现步骤**
1.创建全局Context
```js
import Taro from '@tarojs/taro'
import { AuthProvider } from '@/context/auth-context'
import { UserProvider } from '@/context/user-context'

function AppProviders({ children }) {
  console.log('AppProviders')
  return (
    <AuthProvider>
      <UserProvider>{children}</UserProvider>
    </AuthProvider>
  )
}

export default AppProviders
```
2.注入到全局App中
```js
class App extends Component {

  config = {
    pages: [
      'pages/index/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  }

  componentDidMount () {}

  componentDidShow () {}

  componentDidHide () {}

  componentDidCatchError () {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render () {
    return (
      <AppProviders><Index /></AppProviders>
    )
  }
}
Taro.render(<App />, document.getElementById('app'))
```
3.或者这样
```js
Taro.render(<AppProviders><App /></AppProviders>, document.getElementById('app'))
```
**期望行为**
初始加载的时候<AppProviders></AppProviders>应该会执行打印
**报错信息**
无
**系统信息**
  Taro CLI 1.3.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
无

**Comment by Chen-jj** [comment]
@zerokarafont 小程序中，App.js 只取生命周期函数和 config 分别生成 app.js 和 app.json 。render 函数并没有作用。

![image](https://user-images.githubusercontent.com/11807297/66634491-c5f87500-ec3f-11e9-9782-38f67b8da4d9.png)

**Comment by zerokarafont** [comment]
@Chen-jj 
```js
  render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
```
我是参照官方文档的mobx注入写的, 目前官方没有提供context的全局注入方式, 应该这么全局注入context呢?

**Comment by luckyadam** [comment]
目前不能全局注入，你只能把一些东西存到全局文件，然后再调用

**Comment by zerokarafont** [comment]
@luckyadam 
多谢 期待早日的支持
