### ISSUE TITLE
H5 配置entry 后，无法使用 customRoutes选项

### ISSUE THREAD

**Issue by icesman** [NervJS/taro#4569]
**问题描述**
1、在 `Taro H5`的配置中配置 `entry`选项，
2、配置后，设置 `router` 选项中的`mode` 为 `multi`，此时无法使用 `customRoutes`，所有 `customRoutes`中的选项会指向 `router`中的 `renamePagename` 里的配置，但是`renamePgaename` 只能返回字符串，导致所有页面都指向了同一个路由。

**复现步骤**
[复现问题的步骤]
1. 在`src` 下新建 `views` 目录
2. 在`view` 下新建一个页面

 ```js
h5: {
    entry: {
      A: ['./src/views/A/app.js']
    },
    publicPath: '/',
    staticDirectory: 'static',
    output: {
      filename: 'js/[name].[hash:8].js',
      chunkFilename: 'js/[name].[chunkhash:8].js'
    },
    router: {
      mode: 'multi',
      renamePagename: () => 'index', 
      customRoutes: {
        '/pages/index/index': '/index',
        '/pages/B/index': '/B/index'
      },
    }
}
```

**期望行为**
在 H5模式下支持多页，跟  `webpack` 配置一致
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [1.3.8]
 - Node.js 版本 [10.15.1]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by icesman** [comment]
@luckyadam @Littly  两位能帮忙看一下吗？感谢

**Comment by Chen-jj** [comment]
暂不支持打包多页应用
