### ISSUE TITLE
H5多页模式下，更改其中一个页的代码，重新编译，会造成所有页哈希名变化，不利于缓存

### ISSUE THREAD

**Issue by chowsource** [NervJS/taro#4570]
**问题描述**
H5多页模式下，更改其中一个页的代码，重新编译，会造成所有页哈希名变化，不利于缓存
**复现步骤**
[复现问题的步骤]
修改其中一个页面 js 代码，重新编译，所有多页的文件哈希都改变了

**期望行为**
在其他页面没有变化的，编译出的 hash 名应该不变，这样有利于缓存，要不然，发布其中一个页面更改，会造成所有页面文件刷新。

**Comment by icesman** [comment]
你好，能咨询一下你多页的配置是怎么配置的吗？我配置了多页之后，customRoutes就会出现问题

**Comment by chowsource** [comment]
我没怎么配置，没你用的多，customRoutes 没有用到。taro 的开发文档不详细，多页都没有写上去。都是看提交才知道支持多页了。但是支持的多页看上去也不太完善。和阿里开源差距有点大。

**Comment by shenghanqin** [comment]
淡定。entry是新颖用法。

**Comment by Chen-jj** [comment]
duplicate of #6956
