### ISSUE TITLE
基于taro开发自己的第三方组件库，引入后编译报压缩错误

### ISSUE THREAD

**Issue by MuJinYan** [NervJS/taro#4572]
**问题描述**
我基于taro开发了一些组件，也可以在组件库中采用```TARO_BUILD_TYPE=ui taro build --ui```正确的导出，但是在项目中引入此组件库时，在编译的过程中报压缩错误

**复现步骤**
组件库的入口文件
![image](https://user-images.githubusercontent.com/16420319/66470558-60c84680-eabc-11e9-8e26-0f64164f7e58.png)

项目中引入报压缩错误
![image](https://user-images.githubusercontent.com/16420319/66470692-adac1d00-eabc-11e9-9456-86d92f610716.png)

**期望行为**
可以正确的引入

**系统信息**
👽 Taro v1.3.19

  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.19 => 1.3.19 
      @tarojs/components: 1.3.19 => 1.3.19 
      @tarojs/plugin-babel: 1.3.19 => 1.3.19 
      @tarojs/plugin-csso: 1.3.19 => 1.3.19 
      @tarojs/plugin-less: 1.3.19 => 1.3.19 
      @tarojs/plugin-sass: 1.3.19 => 1.3.19 
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19 
      @tarojs/redux: 1.3.19 => 1.3.19 
      @tarojs/redux-h5: 1.3.19 => 1.3.19 
      @tarojs/router: 1.3.19 => 1.3.19 
      @tarojs/taro: 1.3.19 => 1.3.19 
      @tarojs/taro-alipay: 1.3.19 => 1.3.19 
      @tarojs/taro-h5: 1.3.19 => 1.3.19 
      @tarojs/taro-swan: 1.3.19 => 1.3.19 
      @tarojs/taro-tt: 1.3.19 => 1.3.19 
      @tarojs/taro-weapp: 1.3.19 => 1.3.19 
      @tarojs/webpack-runner: 1.3.19 => 1.3.19 
      eslint-config-taro: 1.3.19 => 1.3.19 
      eslint-plugin-taro: 1.3.19 => 1.3.19 
      nerv-devtools: ^1.4.6 => 1.4.6 
      nervjs: ^1.4.6 => 1.4.6 
    npmGlobalPackages:
      typescript: 3.4.3

**补充信息**
taro压缩采用的是uglifyjs，uglifyjs本身不支持ES6, 但taro-ui采用的同种方式导出，却可以正确运行

**Comment by Pines-Cheng** [comment]
不压缩是可以正常引入和使用的吧。

**Comment by luckyadam** [comment]
对比一下和 taro-ui 的区别咯

**Comment by MuJinYan** [comment]
@luckyadam 嗯嗯，已经找到原因了
