### ISSUE TITLE
getSystemInfo 支持 safeArea

### ISSUE THREAD

**Issue by seekcx** [NervJS/taro#4573]
从 2.7.0 开始，微信支持了 safeArea，可以更方便的判断安全矩形，建议支持一下。

![image](https://user-images.githubusercontent.com/8244814/66483075-e953e080-ead6-11e9-9a38-8f8507e2c4a1.png)
https://developers.weixin.qq.com/miniprogram/dev/api/base/system/system-info/wx.getSystemInfo.html#%E5%8F%82%E6%95%B0

**Comment by Chen-jj** [comment]
@seekcx [不需要额外兼容](https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F)

![image](https://user-images.githubusercontent.com/11807297/66632878-0e159880-ec3c-11e9-85a7-981bb5e41ef9.png)

**Comment by daidi** [comment]
> @seekcx [不需要额外兼容](https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F)
> 
> ![image](https://user-images.githubusercontent.com/11807297/66632878-0e159880-ec3c-11e9-85a7-981bb5e41ef9.png)

但是H5上面没有兼容，是否可以一并支持这个参数？

**Comment by Chen-jj** [comment]
@daidi H5 应该可以测算到，欢迎 PR 哈

**Comment by BigKongfuPanda** [comment]
> 

H5上面的返回值中没有safeArea吧？

**Comment by loocor** [comment]
> 

H5 里有 SafeArea ，但是在 iPhone XR 下全都为零：
![2941659942487_ pic](https://user-images.githubusercontent.com/25772398/183371761-ebc3145e-ac98-4d0a-99da-9506e02dde3c.jpg)
