### ISSUE TITLE
引入的原生组件库所有组件被打包到dist

### ISSUE THREAD

**Issue by sankincn** [NervJS/taro#4574]
![1570626280440](https://user-images.githubusercontent.com/20496148/66483828-75b2d300-ead8-11e9-853b-27df57e902ed.jpg)

如图，我实际在项目中通过usingComponents只是引入了其中几个组件。有时打包一直这样，有时又一直不会出现这个问题

**Comment by Chen-jj** [comment]
@sankincn 请按 issue 模板提供一切必要信息，不稳定复现的问题最好有 demo。

**Comment by sankincn** [comment]
毫无规律，没法复现，demo也不一定能复现
