### ISSUE TITLE
CheckboxGroup 在H5模式下报错，taro 版本号：v1.3.18

### ISSUE THREAD

**Issue by dingjiangbo** [NervJS/taro#4577]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
CheckboxGroup 在H5模式下报错，TypeError: Cannot read property 'for' of undefined，
组件报错位置
![image](https://user-images.githubusercontent.com/21108398/66554043-cb41bb00-eb7e-11e9-9d32-000c5b1ba8c5.png)

**复现步骤**
[复现问题的步骤]
```
 constructor (props) {
    super(props)
    this.state = {
      .... ,
     agree_rem: false,
    }
}
...
render () {
  let {agree_rem} =  this.state
   return (
         <View>
         ...
        <View className="bot_button_one">
              <CheckboxGroup onChange={this.niming.bind(this)}>
                <Checkbox className="check" name="box_check" checked={agree_rem}> 
               </Checkbox>
                同意并允许系统
              </CheckboxGroup>
            </View>
        </View>
   )
}
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
导致页面显示不出来
![image](https://user-images.githubusercontent.com/21108398/66554436-8cf8cb80-eb7f-11e9-8b5d-e17f3a7dca8d.png)

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
λ taro info
� Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\Program Files (x86)\nodejs\node.EXE
      Yarn: 1.9.4 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - D:\Program Files (x86)\nodejs\node_gobal\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
<Checkbox> 外层需要套一层 label
