### ISSUE TITLE
taro 版本由1.2.13升到1.3.19后todoMVC删除其中一项，销毁的总是最后一项的组件

### ISSUE THREAD

**Issue by liwanying** [NervJS/taro#4578]
**问题描述**
[问题描述：官网todomvc demo taro + redux，将taro版本由1.2.13更新到1.3.19后，删除todo，销毁组件错误，1.2.13表现正常]

**复现步骤**
[复现问题的步骤]

![image](https://user-images.githubusercontent.com/16506381/66572050-deff1880-eba2-11e9-8a1b-0833002e955e.png)

**补充信息**
[可选]
1.3版本修改了组件传递参数，是不是这块导致的

**Comment by Chen-jj** [comment]
@liwanying 首先更新 todoMVC。组件 <TodoItem /> 被涛哥测试快应用时注释了 checkbox ，取消注释后勾选某条 todo，然后点击删除选中按钮，一切正常。

**Comment by liwanying** [comment]
@Chen-jj 您好，目前这个问题和todomvc例子无关，只是拿官网的例子来说明问题，我写的其他demo都有此现象，在map出来的元素中，删除其中一项，销毁的都是最后一个组件，而没有删掉指定的key的组件（Taro1.3+版本出现，1.2的版本表现正常）

**Comment by Chen-jj** [comment]
@liwanying 上 demo

**Comment by liwanying** [comment]
拿todomvc的例子看taro+redux，简化，只测试删除，看销毁元素，
**默认初始化数据手动多加几项**
todoList
`
import Taro, { Component } from '@tarojs/taro'
import { connect } from '@tarojs/redux'
import { View, Text } from '@tarojs/components'
import { bindActionCreators } from 'redux'

import TodoItem from '../../components/TodoItem/TodoItem'

import * as TodoActions from '../../actions'
import { getVisibleTodos } from '../../selectors'

import './TodoList.scss'

const mapStateToProps = state => ({
  filteredTodos: getVisibleTodos(state)
})

const mapDispatchToProps = dispatch => ({
  actions: bindActionCreators(TodoActions, dispatch)
})


@connect(
  mapStateToProps,
  mapDispatchToProps
)
export default class TodoList extends Component {
  render () {
    const { filteredTodos = [], actions } = this.props
    return (
      <View className='todo-list'>
        {filteredTodos.map((todo, index) =>
          <TodoItem
            key={todo.id}
            todo={todo}
            onDeleteTodo={this.props.actions.deleteTodo}
          />
        )}
      </View>
    )
  }
}

`
todoItem
`
import Taro, { Component } from '@tarojs/taro'
// import { View, Checkbox, Label, CheckboxGroup, Text } from '@tarojs/components'
import { View, Text } from '@tarojs/components'

import classnames from 'classnames'

import TodoTextInput from '../TodoTextInput/TodoTextInput'
import './TodoItem.scss'

export default class TodoItem extends Component {
  static defaultProps = {
    todo: {}
  }

  state = {
    animation: null
  }

  componentWillReceiveProps(nextProps) {
    if (this.props.todo.id !== nextProps.todo.id) {
      const animation = Taro.createAnimation({duration:0});
      animation.height('initial').opacity(1).step();
      this.setState({
        animation: animation.export()
      })
    }
  }

  componentWillUnmount() {
    console.log(111, this.props.todo.text)
  }

  handleDelete = (todo) => {
    this.props.onDeleteTodo(todo.id)
  }

  render () {
    const {todo} = this.props

    return (
      <View className={classnames({
        'list-item': true,
        completed: todo.completed,
        editing: this.state.editing
      })}
      animation={this.state.animation}
      >
        <View className='view'>
          <Text style={{color: '#4d4d4d'}}>{todo.text}</Text>
          <Text onClick={this.handleDelete.bind(this, todo)}>delete</Text>
        </View>
      </View>
    )
  }
}

`

**Comment by liwanying** [comment]
请把package里Taro版本升级下由之前的1.2升级到1.3.19
```js
{
	"name": "todo-list",
	"version": "1.0.0",
	"private": true,
	"description": "todo-list",
	"main": "index.js",
	"scripts": {
		"build:rn": "taro build --type rn",
		"build:weapp": "taro build --type weapp",
		"build:h5": "taro build --type h5",
		"dev:rn": "npm run build:rn -- --watch",
		"dev:weapp": "npm run build:weapp -- --watch",
		"dev:h5": "npm run build:h5 -- --watch",
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"author": "",
	"license": "MIT",
	"dependencies": {
		"@tarojs/async-await": "1.3.19",
		"@tarojs/components": "1.3.19",
		"@tarojs/redux": "1.3.19",
		"@tarojs/redux-h5": "1.3.19",
		"@tarojs/rn-runner": "1.3.19",
		"@tarojs/router": "1.3.19",
		"@tarojs/taro": "1.3.19",
		"@tarojs/taro-alipay": "1.3.19",
		"@tarojs/taro-h5": "1.3.19",
		"@tarojs/taro-weapp": "1.3.19",
		"babel-plugin-transform-decorators": "^6.24.1",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-jsx-to-stylesheet": "1.0.5",
		"classnames": "^2.2.6",
		"nervjs": "^1.4.0",
		"redux": "^4.0.1",
		"redux-devtools-extension": "^2.13.5",
		"redux-logger": "^3.0.6",
		"redux-thunk": "^2.3.0",
		"reselect": "^3.0.1"
	},
	"devDependencies": {
		"@tarojs/cli": "1.3.19",
		"@tarojs/plugin-babel": "1.3.19",
		"@tarojs/plugin-csso": "1.3.19",
		"@tarojs/plugin-sass": "1.3.19",
		"@tarojs/plugin-uglifyjs": "1.3.19",
		"@tarojs/webpack-runner": "1.3.19",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"eslint": "^4.19.1",
		"eslint-config-taro": "1.3.19",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "1.3.19",
		"webpack-bundle-analyzer": "^3.0.3"
	}
}

```

**Comment by liwanying** [comment]
@Chen-jj 按照demo是否已经复现？

**Comment by Chen-jj** [comment]
@liwanying 删除没有错，不要在 componentWillUnmount 中打印 this.props

**Comment by liwanying** [comment]
@Chen-jj 删除是没有错，但是销毁的组件不对，都是销毁的最后一个。如果做一些动效，比如当前元素高度变为0后删除，销毁组件不对就会有页面抖动问题，始终销毁最后一个组件，当前组件在点击后高度渐变为0，拿到新的数据高度再变为原始高度，（此时在componentWillReceiveProps里销毁了动画）页面出现了轻微抖动，有种跳数据的感觉
**删除没有按照diff算法，删除相应key的组件**

**Comment by Chen-jj** [comment]
@liwanying diff 由小程序底层控制，没有办法。

**Comment by liwanying** [comment]
@Chen-jj 小程序可以穿入wx:key 当数据改变触发渲染层重新渲染的时候，会校正带有 key 的组件，框架会确保他们被重新排序，而不是重新创建，以确保使组件保持自身的状态，并且提高列表渲染时的效率。(小程序没有问题，也写了demo)
Taro版本在1.2的版本销毁组件可以销毁相应key的组件，1.3版本修改了组件传入参数的方式，是不是这里影响了？

**Comment by Chen-jj** [comment]
@liwanying 应该不影响，貌似是二级属性做 key 时（ `wx:key="$original.id"`），diff 会有问题，你可以写个原生 demo 测试下。

现在的编译：

![image](https://user-images.githubusercontent.com/11807297/66699560-8a7ea900-ed1a-11e9-8913-149212d5a0ac.png)

改成一级属性做 key 就 ok：

![image](https://user-images.githubusercontent.com/11807297/66699542-6753f980-ed1a-11e9-9142-aa3df1f8a1cf.png)

**Comment by liwanying** [comment]
@Chen-jj 不好意思，回复晚了，写了个原生demo，二级属性做 key ，微信的销毁元素有问题，那目前taro怎么写可以打包成一级属性做key？不会要手动改吧😊

**Comment by Chen-jj** [comment]
@liwanying 暂时没有，看看换种实现方式吧。
