### ISSUE TITLE
npm run dev:wepp 就会提示jsEnginScriptError Component is not found in path

### ISSUE THREAD

**Issue by pollux2015** [NervJS/taro#4579]
**问题描述**
npm run dev:wepp 就会提示组件不存在
是这个组件有什么问题 ??? 求大佬帮我看看 有点崩溃-_-

jsEnginScriptError
Component is not found in path "components/q-tag/q-tag" (using by "components/paper/paper-list-item/paper-list-item");onAppRoute
Error: Component is not found in path "components/q-tag/q-tag" (using by "components/paper/paper-list-item/paper-list-item")

**复现步骤**
![image](https://user-images.githubusercontent.com/11935278/66620854-9da75100-ec14-11e9-94ff-6d3acfc5b994.png)

```q-tag.js

import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Skeleton from 'taro-skeleton'
import Qbutton from '../../q-button/q-button'
import Qtag from '../../q-tag/q-tag' // 这个注销掉就可以
import Iconfont from '../../iconfont/iconfont'
import { getPaperStatus, getPaperActionUrl } from '../../../utils/paper'
import './paper-list-item.scss'

export default class PaperItem extends Component {
  static defaultProps = {
    number: 0,
    paper: {},
    skeleton: true,
    isLast: false
  }

  handleItem() {
    const { paper } = this.props
    Taro.navigateTo({
      url: getPaperActionUrl(paper)
    })
  }

  render() {
    const { paper, number, isLast } = this.props
    const isSkeleton = !!paper.skeleton
    const { code, statusName, actionName, color } = getPaperStatus(
      paper.status,
      paper.end_time
    )

    const currentClass = code === 10 ? 'active' : 'default'

    return (
      <View
        className={'paper-item-wrapper ' + currentClass}
        onClick={this.handleItem.bind(this)}
      >
        {isSkeleton && <Skeleton loading title avatar row={1} action />}
        {!isSkeleton && (
          <View
            className={`paper-item paper-item-${number} paper-item-${
              isLast ? 'loast' : 'normal'
            }`}
          >
            <View className='paper-item-content'>
              <View className='paper-item-title'>
                <Qtag my-class='paper-item-dot' color={color} size='small'>
                  {statusName}
                </Qtag>
                {paper.title}
              </View>
              <View className='paper-item-bot'>
                <View className='paper-item-rel'>出题: {paper.author} </View>
                <View className='paper-item-rel'>交卷: {paper.count} </View>
              </View>
            </View>

            {code === 10 && (
              <Qbutton
                my-class='paper-item-action'
                ghost={code !== 10}
                color={code === 10 ? 'primary' : 'black'}
                size='small'
              >
                {actionName}
              </Qbutton>
            )}

            {code !== 10 && <Iconfont my-class='item-angle' />}
          </View>
        )}
      </View>
    )
  }
}


// ```paper-list-item.js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './q-tag.scss'

export default class Tag extends Component {
  static externalClasses = ['my-class']
  static defaultProps = {
    size: 'default',
    color: 'primary',
    ghost: false
  }

  render() {
    const { size, color, ghost } = this.props
    const classStr = [
      'my-class',
      'q-tag',
      `size-${size}`,
      `color-${color}`,
      ghost ? 'ghost' : null
    ]
      .filter(item => item)
      .join(' ')
    return <View className={classStr}>{this.props.children}</View>
  }
}


```

**期望行为**
编译成功

**报错信息**
jsEnginScriptError
Component is not found in path "components/q-tag/q-tag" (using by "components/paper/paper-list-item/paper-list-item");onAppRoute
Error: Component is not found in path "components/q-tag/q-tag" (using by "components/paper/paper-list-item/paper-list-item")
    at V (WAService.js:1:1297138)
    at V (WAService.js:1:1297342)
    at V (WAService.js:1:1297342)
    at V (WAService.js:1:1297342)
    at WAService.js:1:1317308
    at Module.Re (WAService.js:1:1317886)
    at Function.value (WAService.js:1:1400169)
    at kt (WAService.js:1:1415611)
    at WAService.js:1:1419877
    at xt (WAService.js:1:1420370)

**系统信息**
Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.19 => 1.3.18
      @tarojs/components: 1.3.19 => 1.3.18
      @tarojs/plugin-babel: 1.3.19 => 1.3.18
      @tarojs/plugin-csso: 1.3.19 => 1.3.18
      @tarojs/plugin-sass: 1.3.19 => 1.3.18
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.18
      @tarojs/redux: 1.3.19 => 1.3.18
      @tarojs/redux-h5: 1.3.19 => 1.3.18
      @tarojs/router: 1.3.19 => 1.3.18
      @tarojs/taro: 1.3.19 => 1.3.19
      @tarojs/taro-alipay: 1.3.19 => 1.3.18
      @tarojs/taro-h5: 1.3.19 => 1.3.19
      @tarojs/taro-swan: 1.3.19 => 1.3.18
      @tarojs/taro-tt: 1.3.19 => 1.3.18
      @tarojs/taro-weapp: 1.3.19 => 1.3.18
      @tarojs/webpack-runner: 1.3.19 => 1.3.19
      eslint-config-taro: 1.3.19 => 1.3.18
      eslint-plugin-taro: 1.3.19 => 1.3.19
      nerv-devtools: ^1.4.6 => 1.4.6
      nervjs: ^1.4.6 => 1.4.6
      stylelint-config-taro-rn: 1.3.19 => 1.3.18
      stylelint-taro-rn: 1.3.19 => 1.3.18
    npmGlobalPackages:
      typescript: 3.5.2

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by pollux2015** [comment]
频繁的出现这个问题...

**Comment by pollux2015** [comment]
目录张这样
![image](https://user-images.githubusercontent.com/11935278/66621613-6c7c5000-ec17-11e9-9827-af14a5b21b69.png)

**Comment by pollux2015** [comment]
手动把这个paper-list-item下的所有引入的组件手动保存后 就没有报错了
这是怎么回事.....

**Comment by pollux2015** [comment]
其他很多页面 引入了自定义组件 都出现了此问题, 我现在有点崩溃.....

**Comment by pollux2015** [comment]
没法玩耍了

**Comment by luckyadam** [comment]
http://taro-docs.jd.com/taro/docs/debug.html#jsenginscripterror

**Comment by pollux2015** [comment]
@luckyadam 我检查了1.2 步骤都发现没有问题
然后我微信的开发者工具删了 我重新下了一个
依旧有同样的问题
然后我吧那个没有引用到的组件 重新保存一下就可以

这是什么情况

**Comment by pollux2015** [comment]
我都快开发完了  中途有出现类似的情况, 重新启动开发者工具就可以了
但是今天不行 哭鸟

**Comment by pollux2015** [comment]
##以下都是dist目录下的文件

// components目录结构
![image](https://user-images.githubusercontent.com/11935278/66629307-eae6eb00-ec33-11e9-8fc9-6419dba249c3.png)

// page目录结构
![image](https://user-images.githubusercontent.com/11935278/66629355-0f42c780-ec34-11e9-95ac-fc4f86ea552b.png)

**Comment by pollux2015** [comment]
@luckyadam 实在没办法了一会这个组件找不到 过一会儿那个又找不到
有时候手动保存后可以解决某个组件, 过一会儿又出来了

![image](https://user-images.githubusercontent.com/11935278/66629431-503adc00-ec34-11e9-9f75-660e74c845e9.png)

VM734:1 jsEnginScriptError
Component is not found in path "components/question/ques-block/ques-block" (using by "pages/paper-viewer/paper-viewer");onAppRoute
Error: Component is not found in path "components/question/ques-block/ques-block" (using by "pages/paper-viewer/paper-viewer")
    at V (WAService.js:1:1297138)
    at V (WAService.js:1:1297342)
    at WAService.js:1:1317308
    at Module.Re (WAService.js:1:1317886)
    at Function.value (WAService.js:1:1400169)
    at kt (WAService.js:1:1415611)
    at WAService.js:1:1419877
    at xt (WAService.js:1:1420370)
    at Function.<anonymous> (WAService.js:1:1423760)
    at i.<anonymous> (WAService.js:1:1393108)

**Comment by luckyadam** [comment]
提交一个可以复现问题的简单 demo 吧，我看看

**Comment by pollux2015** [comment]
我不玩了,  我用微信的去写了

**Comment by zjxpcyc** [comment]
这个关的也太随意了吧。都没解决这个问题

**Comment by zjxpcyc** [comment]
解决了，楼主应该跟我一样的问题。把  static 的变量或者方法干掉，或者换别的方式实现就可以了

**Comment by jinjinwa** [comment]
怎么解决的

**Comment by stevekeol** [comment]
Taro维护的真的是一言难尽，开发者用心的提了那么详尽的issue，没得到解决，只得到一个最终的回复“哦”，然后就关了该issue。WTF？
