### ISSUE TITLE
字节跳动小程序的全局样式控制组件 真机上无效 开发工具上没问题

### ISSUE THREAD

**Issue by zyy-3927** [NervJS/taro#4580]
**问题描述**
字节跳动小程序的全局样式控制组件 真机上无效 开发工具上没问题

**复现步骤**
[复现问题的步骤]
1. 创建一个taro项目
2.做一个简单的组件如下：
“
// js
class Index extends Component {
static defaultProps = {
    className:'',
    text:''
  };
  static externalClasses = ['my-class']
  static options = {
    addGlobalClass: true
  }

render () {
    const { className,text } = this.props
    return (
      <View className={`btn-index ${className} my-class`}>
        {text}
      </View>
    )
  }
}
export default Index 
//css
.btn-index{
	width:300px;
	height: 80px;
	line-height: 80px;
	border-radius: 40px;
	font-size: 36px;
	text-align: center;
	margin: 50px auto;
	background: #000;
	color: #fff;
}
”
3.在页面内加载这个组件 如下：
"//js
import Btn from '../../component/button'
class Index extends Component {
render () {
    return (
      <View className='index'>
        <Btn  my-class={'my-btn'} text={'外部样式'}/>
        <Btn className="my-btn" text={'全局样式'}/>
      </View>
    )
  }
}
export default Index 
//css
.index{
	.my-btn{
		background: #f00;
	}
}
"

**期望行为**
全局样式组件上有效

**报错信息**

无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [安卓手机]
 - Taro 版本 [v1.3.2]
 - Node.js 版本 [v10.15.3]
 - 报错平台 [tt]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shenghanqin** [comment]
字节跳动小程序相比较微信小程序，很多功能都是不完善的（内测阶段吧）。所以，这个全局覆盖样式在微信小程序可能跑的通，在字节跳动小程序上就得写一个原生小程序试试看。
