### ISSUE TITLE
Taro父子组件传值，编译支付宝小程序，页面不显示，控制台报错，若不传值，显示正常

### ISSUE THREAD

**Issue by oracle11770** [NervJS/taro#4582]
**问题描述**
Taro父子组件传值，编译支付宝小程序，页面无法进行下一步，控制台报错，若不传值，显示正常。

**复现步骤**
1，已设置defaultProps
export default class PopAbout extends Component{
    static defaultProps = {
        isPopOpen: false,
        selectI: 0,
        onChangeSelectIndex: () => {},
        onClosePop: () => {},
    }

**期望行为**
解决代码报错

**报错信息**
![微信图片_20191011172107](https://user-images.githubusercontent.com/35660748/66640419-8a63a800-ec4b-11e9-8ca3-e989c2cdb3dd.png)

![image](https://user-images.githubusercontent.com/35660748/66640491-a9fad080-ec4b-11e9-80e7-94c8c256e1d5.png)

**系统信息**
> Taro v1.3.19 。

 - 操作系统: window7
 - Taro 版本 v1.3.19 
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台  【支付宝】

**Comment by Chen-jj** [comment]
@oracle11770 taro CLI 与依赖版本保持一致。

**Comment by oracle11770** [comment]
> @oracle11770 taro CLI 与依赖版本保持一致。
多谢回复！

**Comment by oracle11770** [comment]
> @oracle11770 taro CLI 与依赖版本保持一致。

多谢回复！

**Comment by oracle11770** [comment]
> @oracle11770 taro CLI 与依赖版本保持一致。

多谢回复！    

我是下载的代码，直接install后就编译了   如何确认taro CLI 与依赖版本保持一致  

还望回复，多谢

**Comment by Chen-jj** [comment]
https://taro-docs.jd.com/taro/docs/GETTING-STARTED.html#%E7%8E%AF%E5%A2%83%E5%8F%8A%E4%BE%9D%E8%B5%96%E6%A3%80%E6%B5%8B

**Comment by oracle11770** [comment]
> https://taro-docs.jd.com/taro/docs/GETTING-STARTED.html#%E7%8E%AF%E5%A2%83%E5%8F%8A%E4%BE%9D%E8%B5%96%E6%A3%80%E6%B5%8B

感谢大神，问题圆满解决了，就是因为taro版本不一致的问题导致的
跪谢！！！
