### ISSUE TITLE
componentDidShow 请求数据，当返回此页面的时候不应该 再次 走 componentDidShow

### ISSUE THREAD

**Issue by wang777777** [NervJS/taro#4583]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  componentDidShow 请求数据，当返回此页面的时候不应该 再次 走 componentDidShow，taro 中没法知道路由的 action, 通常 react 中会判断 action, 请问 taro 中要实现此操作，应该怎么做？谢谢

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
返回不请求 componentDidShow 中的接口
**报错信息**
无
[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
trao 的路由不想react 中的路由，可以判断 action 是不是 pop

**Comment by Pines-Cheng** [comment]
哪个端？

**Comment by Garfield550** [comment]
componentDidShow 对应的是小程序的 onShow 生命周期，根据微信小程序生命周期示意图，从页面 2 返回页面 1 时会再次激活页面 1 的 onShow 生命周期函数。

![image](https://user-images.githubusercontent.com/3471836/66895300-00d62080-f025-11e9-9084-14ecb9f5b43a.png)
