### ISSUE TITLE
taro小程序里 如何在函数式组件获取组件里View基本元素的高度

### ISSUE THREAD

**Issue by xjpbxl123** [NervJS/taro#4585]
**问题描述**
- 因为要做一个高度的动画过度，想要取得元素的高度，但是该元素是属于函数式组件。函数式组件拿不到this实例，打印出来是undefined，无法设置:
``` js
Taro.createSelectorQuery().in(this.$scope)
```

**期望行为**
 能否在函数组件里获取元素的高度

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
根据下面老兄提醒，非箭头函数式的函数组件是能拿到this，但是this.$scope还是无法拿到，
也就是还是无法成功设置:
```js
Taro.createSelectorQuery().in(this.$scope)

```

**Comment by Lynss** [comment]
同样的疑惑，现在很多需要用到this的api如果用函数组件都有点难以找到对应的使用方式，虽然很多官方都提供了对应的hooks，但是还是偶尔有一部分找不到。。。

**Comment by BoringDays** [comment]
组件声明换成一般函数，不用箭头函数即可

**Comment by xjpbxl123** [comment]
> 组件声明换成一般函数，不用箭头函数即可


问题：函数式组件用非箭头函数声明可以拿到this，但是this.$scope打印出来是undefined，无法：
```js
Taro.createSelectorQuery().in(this.$scope)
```

**Comment by fjc0k** [comment]
这里有个 Taro 工具库已实现 useScope: https://github.com/fjc0k/vtils/tree/master/packages/taro#usescope

**Comment by MuYiBo** [comment]
在React的函数组件中，不管是箭头函数还是普通函数，还是都获取不到this。拿不到当前组件实例

**Comment by weiqiyue** [comment]
死穴啊，官方文档写着在自定义组件内使用this.createSelectorQuery()，但是函数式组件哪里有this啊
