### ISSUE TITLE
字节跳动小程序编译后开发工具无法运行

### ISSUE THREAD

**Issue by qwe9527** [NervJS/taro#4591]
**问题描述**

字节跳动小程序编译后开发工具无法运行，报parserScriptError。

- **编译未报错**
- **未开启es6转es5**

**复现步骤**

yarn dev:tt

**期望行为**

正常运行

**报错信息**

![微信截图_20191012222934](https://user-images.githubusercontent.com/23071889/66702973-ff180e80-ed3f-11e9-8b24-58689a06b328.png)

**系统信息**

```
  Taro CLI 1.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\soft\nodejs\node.EXE
      Yarn: 1.17.3 - C:\soft\yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\soft\nodejs\npm.CMD

```

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shenghanqin** [comment]
贴一下相应代码吧。
tarojs的小程序开发，对代码要求还是挺严格的。（当然，更加规范。）

**Comment by luckyadam** [comment]
希望能提交一个可以复现的 demo

**Comment by qwe9527** [comment]
不好意思各位，是我的代码问题，引用了一个微信小程序的插件:joy::joy:
