### ISSUE TITLE
Taro打包快应用，快应用依赖环境安装失败&丢失了页面组件

### ISSUE THREAD

**Issue by slixina** [NervJS/taro#4593]
**问题描述**
[使用Taro跑快应用，出现错误【快应用依赖环境安装失败，请进入 qk 重新安装！】qk是我的打包输出目录。到了qk，发现有了打包文件，使用快应用IDE打开，yarn install之后，执行 npm run watch  提示 UnhandledPromiseRejectionWarning: Error: 编译失败：请确认manifest.json中配置的文件路径存在：pages\videoMiddle\videoMiddle ，于是我回到我的项目目录下面，这个文件是有的，但是在打包出来的qk目录下面没有（打包H5没有问题） ]

**复现步骤**
[复现问题的步骤]
1. 在项目目录下 npm run dev:qk
 出现问题：× 快应用依赖环境安装失败，请进入 qk 重新安装！
2. 到打包输出的目录qk，执行yarn install 初始化  成功
3.执行npm run watch
  报错【UnhandledPromiseRejectionWarning: Error: 编译失败：请确认manifest.json中配置的文件路径存在：pages\videoMiddle\videoMiddle】打出来的包里面没有这个文件，但是项目里有

*package.json中scripts配置
"scripts": {
    "build:h5": "taro build --type h5 ",
    "build:qk": "taro build --type quickapp",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:qk": "npm run build:qk --watch"
  },

*videoMiddle组件代码
import Taro from '@tarojs/taro'
import { View, Image, ScrollView } from '@tarojs/components'
import { useEffect, useLayoutEffect, useReducer, useState, useRef, useCallback, useMemo } from '@tarojs/taro'
import app from '@/utils/appData'

function VideoMiddle () {
    useEffect(() => {
        app.navigateTo({
            url: `/pages/videoDetail/videoDetail?category_id=${this.$router.params.category_id}`
        })
        handleDidShow()
    },[])

    // 视频页点击history的返回的时候回到首页
    const handleDidShow = () => {
        window.onhashchange = (e) => {
            let url = location.hash.split('?')[0]
            if(url === "#/pages/videoMiddle/videoMiddle") {
                if(this.$router.params.category_id) { //用category_id判断页面入口是否为其他入口
                    Taro.navigateBack()
                }else {
                    Taro.switchTab({ //入口为首页
                        url: '/pages/index/index'
                    })
                }
            }
        }
    }

    return (
        <View></View>
    )
}
export default VideoMiddle

**期望行为**
[
1、希望taro build quickapp是 快应用依赖环境安装成功 
2、希望打包出来的项目不会比源项目缺少页面组件
]

[
- 安装快应用依赖环境, 需要一会儿...'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
× 快应用依赖环境安装失败，请进入 qk 重新安装！
Error: Command failed: NODE_ENV=development yarn install
'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

LOG] 当前minPlatformVersion >= 1040，平台采用v8版本为6.5+（对应chrome版本为65版+），工具将不再对V8 6.5版本支持的ES6代码进行转换
(node:5136) UnhandledPromiseRejectionWarning: Error: 编译失败：请确认manifest.json中配置的文件路径存在：pages\videoMiddle\videoMiddle
    at Object.throw (G:\work\qk\node_modules\@hap-toolkit\shared-utils\lib\index.js:1:1876)
    at Object.keys.forEach.routePath (G:\work\qk\node_modules\hap-toolkit\gen-webpack-conf.js:82:27)
    at Array.forEach (<anonymous>)
    at confsList.forEach (G:\work\qk\node_modules\hap-toolkit\gen-webpack-conf.js:76:24)
    at Array.forEach (<anonymous>)
    at resolveEntries (G:\work\qk\node_modules\hap-toolkit\gen-webpack-conf.js:75:13)
    at genWebpackConf (G:\work\qk\node_modules\hap-toolkit\gen-webpack-conf.js:160:19)
    at Promise (G:\work\qk\node_modules\hap-toolkit\lib\commands\compile.js:1:1429)
    at new Promise (<anonymous>)
    at e (G:\work\qk\node_modules\hap-toolkit\lib\commands\compile.js:1:665)
(node:5136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled
with .catch(). (rejection id: 1)
(node:5136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [ v.1.3.4]
 - Node.js 版本 [ v10.16.3]
 - 报错平台 [quickapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by slixina** [comment]
issue补充

****app.js中页面配置

pages: [
            "pages/index/index",
            "pages/mine/mine",
            "pages/videoMiddle/videoMiddle",
            "pages/activity/activity",
            "packageExceptMain/pages/reserverMaster/reserverMaster"
        ],
        subPackages: [
            {
                root: 'packageToolMeasure',
                pages: [
                    "pages/userForm/userForm",
                    "pages/faceAnalytic/faceAnalytic",
                    "pages/nameTest/nameTest",
                    "pages/nameTestResult/nameTestResult",
                    "pages/surnamesList/surnamesList",
                    "pages/nameList/nameList",
                    "pages/duckZhouDream/duckZhouDream",
                    "pages/duckZhouArticle/duckZhouArticle",
                    "pages/baZiPaiPan/baZiPaiPan",
                    "pages/taoHuaBaZi/taoHuaBaZi",
                    "pages/baziBirth/baziBirth",
                    "pages/peachBlossom/peachBlossom",
                    "pages/horoscope/horoscope",
                    "pages/ziwei/ziwei",
                    "pages/qiMenDunJia/qiMenDunJia",
                    "pages/qiMenDunJiaShow/qiMenDunJiaShow",
                    "pages/fengshui/fengshui",
                    "pages/xiangshu/xiangshu",
                    "pages/zodiacPairing/zodiacPairing",
                    "pages/zodiacKnowledgeList/zodiacKnowledgeList",
                    "pages/zodiac/zodiac",
                ]
            },
            {
                root: 'packageExceptMain',
                pages: [
                    "pages/calendarDetail/calendarDetail",
                    "pages/message/message",
                    "pages/agreement/agreement",
                    "pages/forgetPassword/forgetPassword",
                    "pages/login/login",
                    "pages/register/register",
                    "pages/bindPhone/bindPhone",
                    "pages/famousIntroduction/famousIntroduction",
                    "pages/chat/chat",
                    "pages/artical/artical",
                    "pages/order/order",
                    "pages/masterCard/masterCard",
                    "pages/orderConfirm/orderConfirm",
                    "pages/fortune/fortune",
                    "pages/orderDetail/orderDetail",
                    "pages/orderProfile/orderProfile",
                    "pages/consultMaster/consultMaster",
                    "pages/masterIntroduction/masterIntroduction",
                    'pages/reserverMaster/reserverMaster',
                    'pages/masterSchedule/masterSchedule',
                    "pages/setting/setting",
                    "pages/fileSetting/fileSetting",
                    "pages/accountSecurity/accountSecurity",
                    "pages/guide/guide",
                    "pages/paySuccess/paySuccess",
                    "pages/collection/collection",
                    "pages/feedback/feedback",
                    "pages/about/about",
                    "pages/hotpush/hotpush",
                    "pages/videoDetail/videoDetail",
                    "pages/myClassroom/myClassroom",
                    "pages/myQuestion/myQuestion",
                    "pages/orderQuestionMsg/orderQuestionMsg",
                    "pages/messageIndex/messageIndex",
                    "pages/calendar/calendar",
                    "pages/cordovaLogin/cordovaLogin",
                    "pages/cordovaRegister/cordovaRegister",
                    "pages/cordovaBindPhone/cordovaBindPhone"
                ]
            }
        ],  


源项目路径下videoMiddle组件
![image](https://user-images.githubusercontent.com/49421399/66735071-eae72500-ee97-11e9-8cf6-688c4b64cac0.png)

打包出来没有videoMiddle组件
![image](https://user-images.githubusercontent.com/49421399/66735151-271a8580-ee98-11e9-9024-445241613d8e.png)

**Comment by luckyadam** [comment]
1、快应用环境安装失败了~ 可以自己进入到项目的 dist 目录下自行手动安装一下，就是安装 npm 依赖
2、第二个报错应该是这个页面没有编译成功，你可以看下控制台编译时有什么报错
