### ISSUE TITLE
用taro将小程序转成H5,安装完依赖以后,执行yarn dev:h5报错Unknown plugin "transform-decorators-legacy" specified in "base" at 3

### ISSUE THREAD

**Issue by hjx5309** [NervJS/taro#4598]
**问题描述**
用taro将小程序转成H5,安装完依赖以后,执行yarn dev:h5报错
Unknown plugin "transform-decorators-legacy" specified in "base" at 3
![image](https://user-images.githubusercontent.com/23748339/66739597-a95c7700-eea3-11e9-9fdf-f0c5ae4773b1.png)

**复现步骤**
[复现问题的步骤]
1. 安装taro  ---yarn global add @tarojs/cli
2.找到小程序文件夹
3.执行taro convert
4.在taroConver下执行yarn install
5.执行yarn dev:h5

**期望行为**

通过执行yarn dev:h5,可以正常打开网页
**报错信息**
Unknown plugin "transform-decorators-legacy" specified in "base" at 3

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
  Taro CLI 1.3.19 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.16.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 5.3.0 - D:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
项目依赖没装好，重新安装试试

**Comment by hjx5309** [comment]
已经装了一天了，主要都是用yarn装的，现在不知道是哪一个依赖没有装

**Comment by luckyadam** [comment]
删了 node_modules 重新安装，另外检查下
![image](https://user-images.githubusercontent.com/1782542/66755659-09b2df00-eecb-11e9-9479-12b93a59edf8.png)
这个目录及其父级目录有没有 babel 配置文件，有的话删掉

**Comment by hjx5309** [comment]
目前还是不行，但我只把小程序一部分代码放上去，到是运行成功了，只是控制台老是报Cannot assign to read only property 'exports' of object，这个很头疼

**Comment by luckyadam** [comment]
这是你自己代码的问题

**Comment by hjx5309** [comment]
了解，我看了下，是require 和 import 混用

**Comment by hjx5309** [comment]
小程序转了H5以后，编译完的页面都和第一个页面一样?
源文件:
![image](https://user-images.githubusercontent.com/23748339/66796266-bcba2180-ef39-11e9-93d1-58d13eb35752.png)
编译后的文件:(这是第一个文件的dom)
![image](https://user-images.githubusercontent.com/23748339/66796371-04d94400-ef3a-11e9-935f-c299c4196485.png)

**Comment by luckyadam** [comment]
> 小程序转了H5以后，编译完的页面都和第一个页面一样?
> 源文件:
> ![image](https://user-images.githubusercontent.com/23748339/66796266-bcba2180-ef39-11e9-93d1-58d13eb35752.png)
> 编译后的文件:(这是第一个文件的dom)
> ![image](https://user-images.githubusercontent.com/23748339/66796371-04d94400-ef3a-11e9-935f-c299c4196485.png)

没有明白你的意思

**Comment by ChunrunHan** [comment]
请问，解决了吗？

**Comment by ChunrunHan** [comment]
> 了解，我看了下，是require 和 import 混用

混用导致的问题吗？

**Comment by memerylihong** [comment]
我也有同样的问题，如何解决呢？

**Comment by memerylihong** [comment]
> 了解，我看了下，是require 和 import 混用

那最后是怎么解决的呢  朋友
