### ISSUE TITLE
无法使用redux-saga

### ISSUE THREAD

**Issue by yz1311** [NervJS/taro#46]
taro-cli:v0.0.41

redux配置:
`
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk'
import createSagaMiddleware from 'redux-saga'
import rootReducer from '../reducers'
import rootSaga from '../sagas';

const sagaMiddleware = createSagaMiddleware()
let middlewares = [thunk,sagaMiddleware]

export default function configStore () {
  const store = createStore(rootReducer, applyMiddleware(...middlewares));
  // then run the saga
  sagaMiddleware.run(rootSaga);
  return store
}
`

运行报错:
![image](https://user-images.githubusercontent.com/9854019/41186731-166ff132-6bce-11e8-8e19-f85db0babe05.png)

在对应的dist/npm/redux-saga目录下，发现并没有相关的文件
![image](https://user-images.githubusercontent.com/9854019/41186754-84892ac6-6bce-11e8-82c2-cf1b33c6302c.png)

**Comment by luckyadam** [comment]
`0.0.42` 修复了 `redux-saga` 包抽离文件的问题，但是发现运行还是有问题，因为 `redux-saga` 里存在循环依赖，导致小程序解析错误，目前解决方案是把 `redux-saga` 编译好的文件下载到本地进行使用。

**Comment by yz1311** [comment]
app.js
`
import Taro, { Component } from '@tarojs/taro'
//该处的声明必须早于redux配置
import '@tarojs/async-await';
import Index from './pages/index';
import {Provider,connect} from '@tarojs/redux';
import configStore from './store/config-store'

const store = configStore()
....

render () {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
`

**Comment by yz1311** [comment]
集成过程:
###  **1.app.js**
//注意，该库的引用必须早于config-store的引用
`import '@tarojs/async-await'; `
`import {Provider,connect} from '@tarojs/redux';`
`import configStore from './store/config-store';`

### **2./store/config-store.js**
`import { createStore, applyMiddleware } from 'redux';`
`import createSagaMiddleware from 'redux-saga/dist/redux-saga';`
`import rootReducer from '../reducers';`
`import rootSaga from '../sagas';`

`const sagaMiddleware = createSagaMiddleware();`
`let middlewares = [sagaMiddleware];`

`export default function configStore () {`
 ` const store = createStore(rootReducer, applyMiddleware(...middlewares));`
  `// then run the saga`
  `sagaMiddleware.run(rootSaga);`
  `return store`
`}`

### **3.需要引用effects的地方**
`import {effects} from 'redux-saga/dist/redux-saga';`
`const {all,fork} = effects;`

**Comment by wkh2** [comment]
您好 ，我启动服务的时候出现了这个错误，
 ERROR
      TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["__tests__","node_modules","dist","tests","jest","lib","**/*.test.ts","**/*.spec.ts"]'.

**Comment by luckyadam** [comment]
@wkh2 你好，因为 H5 的 TS 支持还没完全好，所以建议先使用 js 来开发

**Comment by Rychou** [comment]
@luckyadam 你好，我在集成`redux-saga`时发现没有这个文件,`redux-saga/dist/redux-saga`.
版本：`redux-saga：^1.0.1`

**Comment by luowenming** [comment]
-webkit-box-orient: vertical;
这个样式编译成h5就没了？微信小程序是可以的。

**Comment by lilywang711** [comment]
> @luckyadam 你好，我在集成`redux-saga`时发现没有这个文件,`redux-saga/dist/redux-saga`.
> 版本：`redux-saga：^1.0.1`

@Rychou 需要降级下 redux-saga 的版本到^0.16.2
