### ISSUE TITLE
Hooks how to use Canvas the ---- this.$scope ?

### ISSUE THREAD

**Issue by supermavericks** [NervJS/taro#4600]
Hooks how to use Canvas the ---- this.$scope ?
Please help。 keyword about this of  Javascript  hard understand

**Comment by luckyadam** [comment]
You can use `useScope` Hooks API
```js
import Taro, { Component, Config, useScope } from '@tarojs/taro'
const scope = useScope()
```

**Comment by supermavericks** [comment]
@luckyadam 谢谢

**Comment by JX-Zhuang** [comment]
@luckyadam 最新版的taro 没有useScope
