### ISSUE TITLE
map循环数组，然后使用name属性 直接编译失败

### ISSUE THREAD

**Issue by YouMaster930615** [NervJS/taro#4601]
**问题描述**
调用接口返回数据  然后再render中对数据进行map循环，打印数据都是正常的

**复现步骤**
[复现问题的步骤]
1. const { cityAry = [] } = this.state
2.判断 cityAry 是否有数据
3.进行map循环

```js

`{
            cityAry.length > 0 ? (
              cityAry.map((item, index) => {
                return (
                  <View key={index} className={selectId === item.id ? 'EachCitySelect' : 'EachCity'} onClick={this.getSecondCity.bind(this, item)}>
                    {item.name}
                  </View>
                );
              })
            ) : ''
}
`

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by YouMaster930615** [comment]
![image](https://user-images.githubusercontent.com/32992897/66750504-3234dc00-eebf-11e9-97a0-f1400e1ea9e7.png)

**Comment by YouMaster930615** [comment]
不知道问题出现在哪里  麻烦大佬帮我看一下

**Comment by yuche** [comment]
单单就你贴的这段代码没办法复现

**Comment by iamfat** [comment]
> **问题描述**
> 调用接口返回数据 然后再render中对数据进行map循环，打印数据都是正常的
> 
> **复现步骤**
> [复现问题的步骤]
> 
> 1. const { cityAry = [] } = this.state
>    2.判断 cityAry 是否有数据
>    3.进行map循环
> 
> ```js
> `{
>             cityAry.length > 0 ? (
>               cityAry.map((item, index) => {
>                 return (
>                   <View key={index} className={selectId === item.id ? 'EachCitySelect' : 'EachCity'} onClick={this.getSecondCity.bind(this, item)}>
>                     {item.name}
>                   </View>
>                 );
>               })
>             ) : ''
> }
> `
> ```
> 
> **期望行为**
> [这里请用简洁清晰的语言描述你期望的行为]
> 
> **报错信息**
> 
> [这里请贴上你的**完整**报错截图或文字]
> 
> **系统信息**
> 
> > Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
> 
> * 操作系统: [e.g. Windows 10]
> * Taro 版本 [e.g. v.0.0.64]
> * Node.js 版本 [e.g. v9.0.0]
> * 报错平台 [h5, weapp]
> 
> **补充信息**
> [可选]
> [根据你的调查研究，出现这个问题的原因可能在哪里？]

我也遇到类似的问题, 直接通过
```javascript
const {id, name} = item
```
然后调用id和name是可以的，直接调用 `item.id`和`item.name`不行, 感觉这个JSX编译坑到死啊

**Comment by yuche** [comment]
> > **问题描述**
> > 调用接口返回数据 然后再render中对数据进行map循环，打印数据都是正常的
> > **复现步骤**
> > [复现问题的步骤]
> > 
> > 1. const { cityAry = [] } = this.state
> >    2.判断 cityAry 是否有数据
> >    3.进行map循环
> > 
> > ```js
> > `{
> >             cityAry.length > 0 ? (
> >               cityAry.map((item, index) => {
> >                 return (
> >                   <View key={index} className={selectId === item.id ? 'EachCitySelect' : 'EachCity'} onClick={this.getSecondCity.bind(this, item)}>
> >                     {item.name}
> >                   </View>
> >                 );
> >               })
> >             ) : ''
> > }
> > `
> > ```
> > 
> > 
> > **期望行为**
> > [这里请用简洁清晰的语言描述你期望的行为]
> > **报错信息**
> > [这里请贴上你的**完整**报错截图或文字]
> > **系统信息**
> > > Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
> > 
> > 
> > 
> > * 操作系统: [e.g. Windows 10]
> > * Taro 版本 [e.g. v.0.0.64]
> > * Node.js 版本 [e.g. v9.0.0]
> > * 报错平台 [h5, weapp]
> > 
> > **补充信息**
> > [可选]
> > [根据你的调查研究，出现这个问题的原因可能在哪里？]
> 
> 我也遇到类似的问题, 直接通过
> 
> ```js
> const {id, name} = item
> ```
> 
> 然后调用id和name是可以的，直接调用 `item.id`和`item.name`不行, 感觉这个JSX编译坑到死啊

你也要把组件代码贴出来，具体是 `item.id`和`item.name` 在哪里调用，单凭一个简短的说明我们也是没法定位问题的。
