### ISSUE TITLE
dva里更新了数据，当数据上有原生js方法的时候不生效

### ISSUE THREAD

**Issue by lxzy-yun** [NervJS/taro#4605]
renderHead=() => {
    const {date} = this.props
    return(
      <View>{date.toLocaleString()}</View>
    )
  }
比如上面这个方式，date是有值的，但是toLocaleString以后就不显示了，只能在外面用一个变量去执行一下才能正常显示

**Comment by luckyadam** [comment]
最好给一下完整的代码看看

**Comment by lxzy-yun** [comment]
> 最好给一下完整的代码看看

```
render () {
    const {name}=this.props
    const aaa=name.toUpperCase()
    return (
      <View className={'index'}>
        <Button onClick={this.go}>跳转</Button>
        <View className='count'>{aaa}</View>
      </View>
    )
  }
```
像这样，只能在外面执行下原生的js方法才能正确显示，不然直接写在里面{name.toUpperCase()}，这样内容就莫名其妙消失了
