### ISSUE TITLE
移动端 H5 下 Taro.setClipboardData 无效

### ISSUE THREAD

**Issue by CheerySlowbro** [NervJS/taro#4611]
**问题描述**
移动端 H5 下 Taro.setClipboardData 无效

**复现步骤**

PC端 Chrome 是可以的，移动端 Safari 不行

```js

Taro.setClipboardData({ data });

```

**期望行为**
移动端 H5 下 Taro.setClipboardData 无效

**报错信息**

**系统信息**
  Taro CLI 1.3.13 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - ~/.nvs/default/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.13 => 1.3.13
      @tarojs/components: 1.3.13 => 1.3.13
      @tarojs/plugin-babel: 1.3.13 => 1.3.13
      @tarojs/plugin-csso: 1.3.13 => 1.3.13
      @tarojs/plugin-sass: 1.3.13 => 1.3.13
      @tarojs/plugin-uglifyjs: 1.3.13 => 1.3.13
      @tarojs/redux: 1.3.13 => 1.3.13
      @tarojs/redux-h5: 1.3.13 => 1.3.13
      @tarojs/router: 1.3.13 => 1.3.13
      @tarojs/taro: 1.3.13 => 1.3.13
      @tarojs/taro-alipay: 1.3.13 => 1.3.13
      @tarojs/taro-h5: 1.3.13 => 1.3.13
      @tarojs/taro-swan: 1.3.13 => 1.3.13
      @tarojs/taro-tt: 1.3.13 => 1.3.13
      @tarojs/taro-weapp: 1.3.13 => 1.3.13
      @tarojs/webpack-runner: 1.3.13 => 1.3.13
      eslint-config-taro: 1.3.13 => 1.3.13
      eslint-plugin-taro: 1.3.13 => 1.3.13
      nerv-devtools: ^1.4.4 => 1.4.4
      nervjs: ^1.4.4 => 1.4.4

**Comment by Garfield550** [comment]
你好，这是一个已知问题，并且有提交尚未合并，请等待后续版本更新。
https://github.com/NervJS/taro/pull/4247

**Comment by luckyadam** [comment]
@Garfield550 可以帮忙看看是否合适哦~ 可以的话就合入吧~

**Comment by Garfield550** [comment]
@luckyadam 这几天有点忙，争取周五晚上看一下。

**Comment by A0150315** [comment]
@Garfield550 @luckyadam 这个PR的代码有问题，iOS会唤起键盘，不用合了😂

**Comment by Garfield550** [comment]
@A0150315 了解

**Comment by AloneWeb** [comment]
@Garfield550 @luckyadam  试了下，这个PR在IOS（ip6sp, v13.1.3）下依旧无法复制

**Comment by AloneWeb** [comment]
无法复制的可以先用下面的代码试下
> const copy = function (message) {
>       var input = document.createElement("input")
>       input.value = message
>       document.body.appendChild(input)
>       input.select()
>       input.setSelectionRange(0, input.value.length), document.execCommand('Copy')
>       document.body.removeChild(input)
>     }

**Comment by Garfield550** [comment]
@AloneWeb 我在 iOS 13.1.3 6sP Safari 测试过可以了，你可以 clone master 分支的代码测试一下你的设备。

**Comment by AloneWeb** [comment]
@Garfield550  我这里6sp, ios 13.1.3试了没有问题

**Comment by Garfield550** [comment]
@AloneWeb 居然是一样的设备，我先 Close 好了，再有问题 reopen 吧。

**Comment by Michaelooo** [comment]
[Document.execCommand 已废弃](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/execCommand)，H5中使用execCommand 这个 API 来设置剪贴板，发现部分浏览器不可用。
* 移动端 chrome-84.0.x 不可用
* 微信-7.0.14 不可用
* 移动端 safari&ios- 14.0 不可用
* ……

不知可有什么解决办法？
