### ISSUE TITLE
当一个元素后面添加一个同级元素（由map动态生成），会报dom of undefined

### ISSUE THREAD

**Issue by leifeng** [NervJS/taro#4612]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
```
      <View>
        <Text>第一</Text>
        {list.map((item, index) => {
          return <View key={index}>{item.title}</View>;
        })}
      </View>
```
这种情况下会报  Cannot read property 'dom' of undefined
**复现步骤**
[在线例子](https://codesandbox.io/s/nerv-sandbox-gt36w?fontsize=14)

**期望行为**
正常显示出map循环出来的元素

**报错信息**

 Uncaught (in promise) TypeError: Cannot read property 'dom' of undefined
    at patchNonKeyedChildren (index.js:1078)
    at patchArrayChildren (index.js:1047)
    at patchChildren (index.js:1059)
    at patch (index.js:986)
    at updateComponent (index.js:1959)
    at reRenderComponent (index.js:1904)
    at ComponentWrapper.update (index.js:2252)
    at patch (index.js:992)
    at updateComponent (index.js:1959)
    at rerender (index.js:2046)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro v1.3.20
  Taro CLI 1.3.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

**补充信息**

**Comment by luckyadam** [comment]
先把 `nervjs` 降级到 `1.4.6`

**Comment by Zhou1eezZZ** [comment]
为什么我不是同级的元素，用map遍历循环页会报同样的错，今天刚从19更新到20版本。

**Comment by AloneWeb** [comment]
![image](https://user-images.githubusercontent.com/22211269/66975724-eefe8700-f0d1-11e9-8445-b9c80ea6e33d.png)
依然报错啊

**Comment by Garfield550** [comment]
`^1.4.6` 的意思是任何与 1.4.6 兼容的版本，它可以是 1.4.7 之类的
`^version “Compatible with version” See semver`

改成 1.4.6 强制该版本号

![image](https://user-images.githubusercontent.com/3471836/66975878-75b36400-f0d2-11e9-8d8a-8e13f2fa0533.png)

**Comment by AloneWeb** [comment]
好 谢谢

**Comment by AloneWeb** [comment]
![image](https://user-images.githubusercontent.com/22211269/66981201-a355d880-f0e5-11e9-8e23-e0c488c1ab53.png)

**Comment by beautycss** [comment]
也碰到这个问题，降到1.4.6是可以了。
那这个问题是打算放在哪个版本里修复呢？

**Comment by Garfield550** [comment]
@beautycss 需要等 Nerv 修复

**Comment by yuche** [comment]
Try nervjs@1.5.1

**Comment by CynthiaNC** [comment]
> 我出现同样的问题，但不是同级的元素，View包裹了map遍历出来的组件们，但View有一个同级的元素，报同样的错。
> 我通过给父元素View添加一个key值来解决了这个问题。

亲测有效，感谢
