### ISSUE TITLE
react native中input实现有问题，

### ISSUE THREAD

**Issue by Lynss** [NervJS/taro#4613]
**问题描述**
在封装Taro的input组件做成一个可以自由加减以及输入的组件时，发现在weapp上ok的封装在rn中出现异常。

**复现步骤**
1. 引入Input组件；
2. 输入值为100；
3. 检验发现100大于10，重新setState为10，打印发现值已经改为10，并传递给Input组件
4. weapp中生效，rn中，值是10，但是显示为100

**期望行为**
希望在外界传递新的值后，Input是完全受控的

**报错信息**
没有报错

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统 macos
 - Taro 版本 1.3.20
 - Node.js 版本 10.16
 - 报错平台 [rn]

**补充信息**
[可选]
看了下React native端Input的源码，发现value设置的事this.state.returnValue,而新传递的props.value会被传递给state的value，猜测，是因此导致值被传递而实际页面展示的值没有变化

**Comment by Pines-Cheng** [comment]
我在本地验证一下。

**Comment by Pines-Cheng** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/input.html

```
value | string |   | 是 | 输入框的初始内容
```
微信小程序那边也不是完全受控的，其他端的交互特性都是以小程序为准的。
