### ISSUE TITLE
写闭包组件时出现报错

### ISSUE THREAD

**Issue by UchihaObitoZzz** [NervJS/taro#4614]
**问题描述**
当一个函数式组件拥有闭包组件时，调用闭包组件会报方法找不到的错

**复现步骤**
```js
public renderList() {
    const renderlistItem = () => {
      return <View className="list-item" style={{ background: "#333" }}></View>;
    };

    return <View className="list">{renderlistItem()}</View>;
  }

  public render() {
    return (
      <View className="test">
        <View>{this.renderList()}</View>
      </View>
    );
  }
```

**期望行为**
支持此功能

**报错信息**

<img width="426" alt="bug" src="https://user-images.githubusercontent.com/22854203/66905811-22d99e00-f039-11e9-8afa-070f4d2b4629.png">

**系统信息**

 - 操作系统: [MacOS]
 - Taro 版本 [v1.3.14]
 - Node.js 版本 [v11.12.0]
 - 报错平台 [weapp]

**Comment by UchihaObitoZzz** [comment]
**补充**

但是业务页面不知道怎么回事这样写就不会报错，但是会出现另一个问题，行内写style不正常显示

**业务代码**

<img width="618" alt="WechatIMG2" src="https://user-images.githubusercontent.com/22854203/66907020-3dad1200-f03b-11e9-929f-66f2f7891f0d.png">

**问题**

<img width="391" alt="WechatIMG3" src="https://user-images.githubusercontent.com/22854203/66907156-76e58200-f03b-11e9-8709-7200230b6aaf.png">

**Comment by Chen-jj** [comment]
@UchihaObitoZzz 不支持这样写，你可以选择把 renderListItem 抽出来放到和 renderList 平级，或把 renderList 抽成一个组件。
