### ISSUE TITLE
editor组件获取不到context

### ISSUE THREAD

**Issue by yonghui66** [NervJS/taro#4616]
**问题描述**
在使用Taro.createSelectorQuery()时，按原生那样去获取context表示获取不到内容，返回null的
例如：Taro.createSelectorQuery().select('.editor').context(function(res) {}).exec()

**复现步骤**

```js

import Taro, { useEffect, Component } from '@tarojs/taro';
import { View, Editor } from '@tarojs/components';
import { AtIcon } from 'taro-ui';

class EditorText extends Component {
  componentDidMount(){
    this.getContext()
  }

  getContext = async () => {
    Taro.createSelectorQuery()
      .select('.editor-container')
      .context(function(res) {
       // 这里的res返回为null！！
        console.log(res);
      })
      .exec();
  };

  render() {
    return (
      <View className="editor">
        <View className="toolbar">
          <AtIcon prefixClass="icon icon-shangjiantou" size="20" color="#000" />
        </View>
        <Editor
          placeholder="输入详情"
          onReady={e => console.log(e)}
          onInput={e => console.log(e)}
          className="editor-container"
        />
      </View>
    );
  }
}

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

👽 Taro v1.3.19

  Taro CLI 1.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zicjin** [comment]
![image](https://user-images.githubusercontent.com/199482/69165745-0693ba00-0b2d-11ea-96e6-9fd16338bf65.png)
实际我得到的是这样的对象，不是EditorContext

**Comment by yonghui66** [comment]
已经知道问题了，当Editor存在于component时会出现如上问题。
需要把Editor放在page页面的js中可以拿到正确的对象
