### ISSUE TITLE
升级taro最新版1.3.20后mobx模板启动rn报错

### ISSUE THREAD

**Issue by Lynss** [NervJS/taro#4617]
**问题描述**
升级最新版后，mobx模板报错

**复现步骤**
1.基于mobx和ts搭建项目
2. 从1.3.19升级到1.3.20，taro update self,taro update project
3. 为页面组件增加inject注解
4.启动，rn环境，进入页面，然后点击返回，报错， xxxx 'dispose' of undefined

**期望行为**
和小程序的mobx一样不会报错

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:macos
 - Taro 版本 1.3.20
 - Node.js 版本 10
 - 报错平台 rn

**补充信息**
weapp上正常

**Comment by Lynss** [comment]
![671571280767_ pic_hd](https://user-images.githubusercontent.com/21052565/66974363-6978d800-f0cd-11e9-9e8b-9c42181f68d1.jpg)

**Comment by Lynss** [comment]
![691571281298_ pic](https://user-images.githubusercontent.com/21052565/66974472-c5436100-f0cd-11e9-816d-2717d2588c78.jpg)
可能是这个改动的问题

**Comment by nanjingboy** [comment]
@Lynss  好的，谢谢反馈

**Comment by nanjingboy** [comment]
@Lynss 大佬，无法复现呢

**Comment by nanjingboy** [comment]
@Lynss 在 dispose 之前对监听器做了判断，可在新版本发布后再试试是否还有问题，如依旧有问题，希望提供下可复现的 demo。

**Comment by Lynss** [comment]
> @Lynss 在 dispose 之前对监听器做了判断，可在新版本发布后再试试是否还有问题，如依旧有问题，希望提供下可复现的 demo。

谢谢回复，最近有点忙，会有时候响应不及时～我会抽时间升级看看的
