### ISSUE TITLE
H5中Image组件的mode='aspectFill'表现不符预期（与小程序表现不一致）

### ISSUE THREAD

**Issue by myl0204** [NervJS/taro#4620]
**问题描述**

1. 当图片宽度大于高度时，显示的是图片左边部分，即被截取的是**右边**部分

2. 当图片高度大于宽度时，显示的是效果与`scaleToFill`相同，即图片被*拉伸*了

**复现步骤**
设置Image组件的宽高相同，设置mode为aspectFill，找几张不同宽高比的图片带入。

**期望行为**
1.当图片宽度大于高度时，显示的是图片**中间**部分，即被截取的是**左右**两边

2.当图片高度大于宽度时，显示的是图片**中间**部分，即被截取的是**上下**两边

**系统信息**
Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.0 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.16 => 1.3.16
      @tarojs/mobx: 1.3.16 => 1.3.16
      @tarojs/mobx-h5: 1.3.16 => 1.3.16
      @tarojs/mobx-rn: 1.3.16 => 1.3.16
      @tarojs/plugin-babel: 1.3.16 => 1.3.16
      @tarojs/plugin-csso: 1.3.16 => 1.3.16
      @tarojs/plugin-sass: 1.3.16 => 1.3.16
      @tarojs/plugin-uglifyjs: 1.3.16 => 1.3.16
      @tarojs/rn-runner: 1.3.16 => 1.3.16
      @tarojs/router: 1.3.16 => 1.3.16
      @tarojs/taro: 1.3.16 => 1.3.16
      @tarojs/taro-alipay: 1.3.16 => 1.3.16
      @tarojs/taro-h5: 1.3.16 => 1.3.16
      @tarojs/taro-swan: 1.3.16 => 1.3.16
      @tarojs/taro-tt: 1.3.16 => 1.3.16
      @tarojs/taro-weapp: 1.3.16 => 1.3.16
      @tarojs/webpack-runner: 1.3.16 => 1.3.16
      eslint-config-taro: 1.3.16 => 1.3.16
      eslint-plugin-taro: 1.3.16 => 1.3.16
      nerv-devtools: ^1.5.1 => 1.5.1
      nervjs: ^1.5.1 => 1.5.1
      stylelint-config-taro-rn: 1.3.16 => 1.3.16
      stylelint-taro-rn: 1.3.16 => 1.3.16
**补充信息**
1. img设置成水平垂直居中 ，可以解决1
2. 在1的基础上，当图片高度大于宽度时，img的样式应为:
```css
.taro-img__mode-aspectfill {
  width: 100%;
  min-height: 100%;
}
```

**Comment by CherishLyf** [comment]
+1

**Comment by shenghanqin** [comment]
目前我看了源代码，目前Image组件是模拟实现的微信小程序的mode，可能比不上`object-fit`效果准确。

**Comment by GuoliangWang** [comment]
> 目前我看了源代码，目前Image组件是模拟实现的微信小程序的mode，可能比不上`object-fit`效果准确。

我也看了下源码。作者是在，图片加载完后，根据图片的宽高设置对应的样式（原始图片宽度比高度大就高度100%，宽度比高度小就宽度100%）。这个算法是错误的，应该根据用户设置的图片宽高比，和图片原始尺寸的宽高比进行对比，用户设置的宽高比小于图片原始尺寸宽高比就宽度100%，反之高度100% 但是很难获取用户设置的样式最终导致图片的尺寸，所以最好用object-fit:cover;模拟。或者background-image模拟。

**Comment by GuoliangWang** [comment]
如果用background-image模拟的话。可以在元素上面覆盖一层opacity为0的图片，模拟图片的一些操作特性。借鉴uiniapp😄

**Comment by shenghanqin** [comment]
其实知道想要的图片比例的话，用`object-fit:cover`可能效果会更好点。当然，图片模式七八种吧，实际得列出各种测试场景的。
