### ISSUE TITLE
Taro Canvas组件转化支付宝小程序时，丢失canvasId、className、style等属性

### ISSUE THREAD

**Issue by quxiaodai** [NervJS/taro#4624]
Taro Canvas组件转化支付宝小程序时，丢失canvasId、className、style等属性

Taro：
 <Canvas style='width: 100%; height: 225px' className='trend-charts' canvasId='lineChartCanvas' id='lineChartCanvas' disableScroll={true} onTouchStart={this.onshowChartValue.bind(this)} ></Canvas>

支付宝：
<canvas id="this"></canvas>

**Comment by Garfield550** [comment]
请提供一下复现代码可以吗？

**Comment by quxiaodai** [comment]
<img width="2104" alt="ali_canvas" src="https://user-images.githubusercontent.com/16485705/67060885-2da74680-f191-11e9-828d-50612ed8fffb.png">
<img width="2650" alt="taro_canvas" src="https://user-images.githubusercontent.com/16485705/67060896-35ff8180-f191-11e9-8cd9-a7b8b52bd0f8.png">

**Comment by Chen-jj** [comment]
#4511
