### ISSUE TITLE
props 不能传递自定义组件吗?

### ISSUE THREAD

**Issue by languis** [NervJS/taro#4627]
**问题描述**
有自定义A，B，C三个组件

A组件组件以参数形式将B传递给C组件.
C组件内调用B组件则无法显示.

![1](https://s2.ax1x.com/2019/10/18/KepFs0.jpg)
![2](https://s2.ax1x.com/2019/10/18/Kep2Wj.jpg)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  mac os 10.15
 - Taro 版本 👽 Taro v1.3.19
 - Node.js 版本 v11.9.0
 - 报错平台  weapp

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/children.html

**Comment by LeiHanChenZhou** [comment]
@luckyadam 你好，我在使用 [ render props ] 时遇到了一些困惑，可以帮我解答一下嘛
 
```js
// 伪代码
// Child.js
const Child = (props) => {
  const data = 'data needs to pass'
  return <View>{ props.renderSomething(data) }</View>
// 下面这一行是可以执行的，但是这样我无法把数据传递进去
// return <View> { props.renderSomething } </View>
}

// Base.js
const Base  = () => {
  return <Child renderSomething={data => <View>{data}</View>} >Base</Child>
}
```
上面的代码貌似无法如期执行，因为以render开头的props可能被编译器认为是占位符

运行时会报类似于下面的错误
![image](https://user-images.githubusercontent.com/19839331/67547798-a4fd4d00-f732-11e9-9827-9b0ea1381af5.png)
其中的 **renderExpandPanel** 等效于上面示例代码的 **renderSomething**

我希望能够在调用**renderSomething**的时候传递一些数据进去，请问我该如何解决这个问题
