### ISSUE TITLE
百度小程序安卓真机首次加载，页面3次以上重复一个组件会导致内容无法正常显示

### ISSUE THREAD

**Issue by fesiong** [NervJS/taro#4628]
**问题描述**
taro开发的百度小程序，一个组件在页面中重复使用3次以上，如果组件的变量是数组或对象，并且这些变量的内部数据有部分相同的情况下，则会从第三次开始组件不能正常显示。
这个bug只在安卓版的百度app中打开百度小程序才出现。
并且实测中，如果在defaultProps中不声明这个变量，则能正常显示。

**复现步骤**
0、创建一个组件，包含数组或对象变量，在首页循环输出这个组件
1、百度小程序
2、安卓手机
3、百度开发者工具选择真机调试，用安卓版百度app扫码

下面是代码
1、首页 pages/index/index.tsx
```tsx
import Taro, { Component, Config } from '@tarojs/taro'
import { View } from '@tarojs/components'
import SeoImage from '../../components/image'

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页'
  }

  state = {
    list: [
      {item_type: 'nav', show_type: '1'},
      {item_type: 'nav', show_type: '2'},
      {item_type: 'nav', show_type: '3'},
      {item_type: 'nav', show_type: '4'},
    ]
  }

  render () {
    const { list } = this.state
    return (
      <View className='index'>
        {list.map((item, index) => {
        return <SeoImage componentIndex={index} componentData={item}></SeoImage>
        })}
      </View>
    )
  }
}

```
2、image组件components/image/index.tsx
```tsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './index.scss'

export default class SeoImage extends Component {
  constructor () {
    super(...arguments)
    this.state = {}
  }

  static defaultProps = {
    componentData: {},
    componentIndex: 0
  }

  static options = {
    addGlobalClass: true,
  }

  render() {
    const { componentData } = this.props
    return <View>
      <View>image - {componentData.item_type} {componentData.show_type}</View>
    </View>
  }
}
```
**期望行为**
期待的显示结果是
![image](https://user-images.githubusercontent.com/9912496/67086869-543aa100-f1d4-11e9-9977-eedde162665f.png)

**报错信息**
但安卓端打开的结果是
![image](https://user-images.githubusercontent.com/9912496/67086956-89df8a00-f1d4-11e9-9aa7-4a9901779133.png)

👽 Taro v1.3.20

  Taro CLI 1.3.20 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.20 => 1.3.20
      @tarojs/plugin-babel: 1.3.20 => 1.3.20
      @tarojs/plugin-csso: 1.3.20 => 1.3.20
      @tarojs/plugin-sass: 1.3.20 => 1.3.20
      @tarojs/plugin-uglifyjs: 1.3.20 => 1.3.20
      @tarojs/router: 1.3.20 => 1.3.20
      @tarojs/taro: 1.3.20 => 1.3.20
      @tarojs/taro-alipay: 1.3.20 => 1.3.20
      @tarojs/taro-h5: 1.3.20 => 1.3.20
      @tarojs/taro-qq: 1.3.20 => 1.3.20
      @tarojs/taro-quickapp: 1.3.20 => 1.3.20
      @tarojs/taro-swan: 1.3.20 => 1.3.20
      @tarojs/taro-tt: 1.3.20 => 1.3.20
      @tarojs/taro-weapp: 1.3.20 => 1.3.20
      @tarojs/webpack-runner: 1.3.20 => 1.3.20
      eslint-config-taro: 1.3.20 => 1.3.20
      eslint-plugin-taro: 1.3.20 => 1.3.20
      nerv-devtools: ^1.5.1 => 1.5.1
      nervjs: ^1.5.1 => 1.5.1
      stylelint-config-taro-rn: 1.3.20 => 1.3.20
      stylelint-taro-rn: 1.3.20 => 1.3.20

 - 操作系统: macOS 10.14.6
 - Taro 版本 v1.3.20
 - Node.js 版本 v12.7.0
 - 报错平台 [swan] 安卓真机

**补充信息**
估计问题出在defaultProps的合并处理处

**Comment by fesiong** [comment]
跟踪发现是dataDiff 的值的问题。每次调用组件，组件的状态component.$scope.data应该是独立的，但这里使用不知道为什么会使用了旧的组件状态。

**Comment by Chen-jj** [comment]
@fesiong diff 前后的对象，和 diff 结果，都截图看看https://nervjs.github.io/taro/docs/debug.html#debug-diff

**Comment by fesiong** [comment]
正常的数据是这样的：
（上传不了截图，这里放文字）
diff前的数据：
{"componentData":{"item_type":"nav","show_type":"1"},"$taroCompReady":true}
diff后的数据：
{"componentData":{},"componentIndex":0,"compid":"0","id":"_11210"}
diff结果：
{"componentData.item_type":"nav","componentData.show_type":"1","$taroCompReady":true}
diff前的数据：
{"componentData":{"item_type":"nav","show_type":"2"},"$taroCompReady":true}
diff后的数据：
{"componentData":{},"componentIndex":0,"compid":"1","id":"_11214"}
diff结果：
{"componentData.item_type":"nav","componentData.show_type":"2","$taroCompReady":true}
diff前的数据：
{"componentData":{"item_type":"nav","show_type":"3"},"$taroCompReady":true}
diff后的数据：
{"componentData":{},"componentIndex":0,"compid":"2","id":"_11218"}
diff结果：
{"componentData.item_type":"nav","componentData.show_type":"3","$taroCompReady":true}
diff前的数据：
{"componentData":{"item_type":"nav","show_type":"4"},"$taroCompReady":true}
diff后的数据：
{"componentData":{},"componentIndex":0,"compid":"3","id":"_11222"}
diff结果：
{"componentData.item_type":"nav","componentData.show_type":"4","$taroCompReady":true}
卓手机打开的结果是这样的：
![image](https://user-images.githubusercontent.com/9912496/68018563-663c3980-fcd4-11e9-9b66-ef4371df1fa1.png)

**Comment by Chen-jj** [comment]
@fesiong 复现了，的确如此。

设置 defaultProps 相当于构造 Component 时设置了 data 属性。

```js
Component({
  data: { "componentData": {} }
})
```

错误在于第三第四项，diff 时读取 this.data，componentData 已经有值，值指向数组前一位的对象。其实应该是构造 component 时 data.componentData 的默认值 {} 才对。

红框应该都为空对象才对：

![image](https://user-images.githubusercontent.com/11807297/68393175-735e9a00-01a6-11ea-8de3-e471ea4d61cf.png)

这是百度在安卓上的一个 bug，我们也无力解决，只能建议不写 defaultProps 了。

**Comment by shenghanqin** [comment]
@fesiong 小程序调试分为taro适配层和原生小程序逻辑层。上述问题其实最后发现是百度小程序的问题，这在我开发抖音小程序也碰到过类似的情况。所以用开源框架，还是得具备更强的调试能力才可以滴。

**Comment by fesiong** [comment]
谢谢解答。
