### ISSUE TITLE
支持一下wx.hideHomeButton

### ISSUE THREAD

**Issue by Herryjoeson** [NervJS/taro#4629]

**Comment by Garfield550** [comment]
已经记录工作项。
https://github.com/NervJS/taro/blob/9882bed0628f3f38d13b307bd94a53d87d4d0101/packages/taro/types/api/ui/ui.navigationBar.d.ts#L108
欢迎提交 Pull Request。

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E6%8A%A5%E9%94%99
