### ISSUE TITLE
mapStateToProps 没有第二个参数

### ISSUE THREAD

**Issue by aloneszjl** [NervJS/taro#463]
**问题描述**
redux connect 函数 第一个参数没有传 mapStateToProps 只接受state一个参数 没有像react-redux那样传入组件的props 

**复现步骤**
```js
@connect((state, props) => {
   console.log(props);
   return state
})

```

**期望行为**
传入组件的props 以便可以获取对应的数据

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/555
