### ISSUE TITLE
uploadFile是否支持h5？同样的代码小程序没事。在h5端调用接口就报错误？

### ISSUE THREAD

**Issue by syyzz3** [NervJS/taro#4634]
![微信图片_20191021141020](https://user-images.githubusercontent.com/11385973/67180572-977f5480-f40c-11e9-9725-2fc31abb91d1.png)
![微信图片_20191021141025](https://user-images.githubusercontent.com/11385973/67180573-977f5480-f40c-11e9-96e0-20c59bce376e.png)
![3119567073-5dad46a49d2d9_articlex](https://user-images.githubusercontent.com/11385973/67180643-c4336c00-f40c-11e9-8153-d4fc3a81f020.png)
一个上传图片的功能，在小程序端和h5端都有，使用一个接口。
调用接口在小程序端没有问题，但在h5上就报错。我看到报错以为是后端的问题，后端说接口在小程序上都没有问题，就就不是接口的问题。
但我看了一下上传的参数也没有问题，不知道是哪的原因?

**Comment by luckyadam** [comment]
https://stackoverflow.com/questions/40561738/php-message-warning-missing-boundary-in-multipart-form-data-post-data-in-unknow

**Comment by syyzz3** [comment]
![微信图片_20191021141020](https://user-images.githubusercontent.com/11385973/67254955-53468f80-f4b2-11e9-814a-723e24ecf9ab.png)
![微信图片_20191021141025](https://user-images.githubusercontent.com/11385973/67254967-60fc1500-f4b2-11e9-92f5-40b619521785.png)
@luckyadam 您好，加了之后虽然不报错了，但是后端还是无法获得图片

**Comment by zongyan86** [comment]
这个bug应该激活啊，一样的问题。无奈。
![image](https://user-images.githubusercontent.com/3397251/67744934-d1c8a180-fa5d-11e9-8a5d-1c8fe1761853.png)

**Comment by zongyan86** [comment]
> Hello~
> 
> 您的问题楼上已经有了确切的回答，如果没有更多的问题这个 issue 将在 15 天后被自动关闭。
> 
> 如果您在这 15 天中更新更多信息自动关闭的流程会自动取消，如有其他问题也可以发起新的 Issue。
> 
> Good luck and happy coding~



> 这个bug应该激活啊，一样的问题。无奈。
> ![image](https://user-images.githubusercontent.com/3397251/67744934-d1c8a180-fa5d-11e9-8a5d-1c8fe1761853.png)

**Comment by Pinchuan** [comment]
3.0版本这个问题又出现了

**Comment by lp13762436965** [comment]
加一  blob 链接 后端直接报跨域
