### ISSUE TITLE
taro h5端默认把png的小图片转成base64了,但是在页面却无法显示？

### ISSUE THREAD

**Issue by syyzz3** [NervJS/taro#4635]
![QQ截图20191021151259](https://user-images.githubusercontent.com/11385973/67184022-5b042680-f415-11e9-842d-5164f5abdc04.png)
单独打开base64可以访问到图片，在页面上却无法显示是什么原因？

base64:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApYAAACQCAYAAACyNCs+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsSAAALEgHS3X78AAANDUlEQVR42u3dW28c52EG4G+PpESdTKuSLYc7jGPZQd0ihVu3KdDWcOGLXrRoigbor8ivyQ/obVu0N01PQBOkRYo0QNKgRYLm4JN2GauWpVBnieSSu70QlxgOZ2d2Vx/JPTwPsPgOMyvPWDcvZue1K2EMq6urlXHOBwBgtm1ubvZHPTc3KBYESMESAGCx5AbLvMB5KChmA+U3v/4XvdO+EwAApsd7X/vranqdDpgHBzKhspI+BgAA+6oh9XAynSHrOSdXUh8AAEhLZ8RDP4dXQziUNNOh0hNLAACyBk8sDx5EDrJkNjymQ6UnlgAAZKWz4qG8WM2cFIInlgAADJcNlZX0gTQ/hQMAUOTIT+HpAwPZUClYAgCQNciJR8LlsPCoFQ4AQJ6hObG+3+LJ/jcsQxAsAQA4Ki8rVlZXV3PfsRyMgiUAAFm5xZ0QhrfCAQCgSGkrPH2igAkAQNbQnKj5DQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQhWAIAEIVgCQBAFIIlAABRCJYAAEQxLFj29z8AAJA2NCdWMyeFIFACAFDuSHasF5zY/8t/+NHrv/H6lddeOL/86sqZxvpys/75Zr2WNOrVpFqt/Mpp3w0AAPH1ev3b3d1ee2d3r721s/vx46fdG3cfbn303z//7INQ8MSyEkIIq6urlfDs6WU1hFBLfRqZdW3/O9Xf+uJLZ995ay1pvXQheeH8cnJ2qb621KwnzUYtqVUrLwfvbwIATKveXq//fzvdvfZOd6/zeKvbuftwq9359EH733+40f7BTz99EkLohWcBci/z6WbWvRBCb3Nzs58XLNPhsp4a08cr+5+QGg/ma1fON/7k919rfeGVS8nqxTOtleVGsrxUTxq1aqteq36uUgmN0/63CQAwz/r90N3r9X6xs9vrbG3vth9vddub9592PvzkXvsb3/mgs/HZw+7g1PTXUmM/7IfG/c9ueBYkB+Ne+ng2WA57ajn45AXLI6FyyN7B/OK5pdpX333j2vW1F1qXL51Jzp9tJs1GrbXcrLfqtWpSqYQzp/0XAQAwC/r98HR3r9fe6e51tnZ2Ow+f7LTv3HvaeX/jbvtvv/2zm/cfbe8NTk1/LWee3csLlns5n8Gxfl6wHBYuq6H8ieWwsWzv0PzP33396peuX0murq4kF84215aX6slSo5bUa9VWtVq5eNp/gQAAJ6nf79/v7vY629299tb2bufBk53Orc3H7f95/7P2333757fSp5bMi/byxmywzIbLg1AZCoJl3s/i6UA5GEMoD5ijhMyRA+h7byeXvvxr19ZffvHc2sXzS8nZpUbSbFRbzXpNmQgAmFn7ZZnOdnev/WS7237waLtz886jzvd+fPPGN7/fvpc6ddLAmN0rC5SDeS8cDpiHfv5OnX8kWIYwPFymA2X2E8LwgDnqU81xnnrmHi8pE70UngVkAIDTkFuW2bj1sPNv/9W5sV+WGSgKhXnHJxnL9rKfbMDsZY6Hg2AZQmG4rBR8QhgvXB5H+CydHyoTXVheWznTXFcmAgBiyinLdDbvP22PWJYZNo8VHscJlem9opB5KFSGkAphmWA5GMd5Ojnq+LxBdJSxbO9grkwEAIwqVZbZ2NrZbUcsy4w7jvv0MdY/p5/3Zx4JliEcCpeDY88T5IYdG+edzHGC5rGUib7yzvUrb71xdf3qCyutCyvNljIRAMy3YWWZH394p/033/rpcZdlRjn2PN8tu55xr/UgVIaQCZYhHAmX2XMmnY8SQCcJkM/z3bLrKdtTJgKAGZVTltm4eedRewrKMnl7k4bRca5/kvmhUBlCTrBMywmZw773PGF03NA5GE/jfc6R7+VL16+cfe/tRJkIAE5Huiyz8Xir256Bsswo3ykax7mX7HyUdQjhaJhMKwyWwxQEzrw/M9YT0Od9nzNvb5rKRK1GrZooEwHAaIrKMv/8nx9tfHzz/s7g1PTXSuanWZYZZ5xkPsr6QFGAHGaiYFkkYuhMr48jdA7GqSsT/dk71699MXlRmQiAhZdblrn/dOP9zt0bc1qWGfdeJlkfmCQ8FokeLIscU+hMzxeyTNRs1FqNWjVRJgJgFvX7/Qfd3V5bWWbo8UnWB2KHxyInGiyLjBk68/aUid5OLv3Om9eSa5fPtZSJAJgmyjKF95ed562H7YUQTjY8FpmaYFmkJHTm3cdplIkG49SXiS6dW26tLNdbS8160qhXk3qtqkwEwPPKLcvcvP2o863vt5Vljs5HWR8yLeGxyEwEyzLKRIVj6VyZCIBR7JdlPtnZ7bWVZaajLDNt5iJYFlEmKr3ucctErWajljwrE1WSSqWiTAQwR5Rl5ud9x9Mw98GyiDLRyNc6dK5MBDB7MmWZjQdPdtq3Nh+3//fjX3b+6l9/8mn61JK5skyOeQ+PRRY6WBZRJiq9nrK9vDJRq9moJspEAMdvvyyzsd3du6EsUzrPWw/bCyEsdngsIlhOYE7KRKMen2QsvZc3X7185o++/Pl1ZSKAiSnLFN9Ldj7K+hDhcXyC5TFQJiocS+epMlFr9cJya+VMc32pUWs1GzVlImCh5JRlNjbvP73x8c37nX/87ocdZZkj81HWBwTH+ATLE6ZMVHrdykTAQtkvy3R2unsdZRnvO846wXKKKBONfK1D56ky0dqFlWayvFRPmvVaq1FXJgJOj7KM8LgoBMsZoUxUej1le8pEwLHKlGU6Dx5td27eedT+wU8+vfEv3/v4XupUZZn89bC9EILwOCsEyzmgTBS9TLS2slxPlImAjEFZprPT3esoy5TOR1kfIjzOPsFyASgTFY6lc2UiWBzKMsoyPB/BcsEpE5Ved2mZ6E//4PrLv7r+YnL50pnk3Jnm2lKztq5MBNMrpyzTuXP/aUdZ5vC/pjHXB4THxSZYMpQy0cjXOnSuTASnI1WW6Wxt73aUZY7sTbI+IDwyjGDJRJSJSq+nbC+893Zy6bffvNZ65fK5ZL9MtNZsVNeViWA0yjKF95ed562H7YUQhEcmI1gSnTLRsZaJWvVa9eWgTMRiOFKWufdwu/PJ7YdtZZnc+SjrQ4RHYhMsOXHKRIVj6XxQJnr1lUtrL15YTpSJmGX9ftjd6/V+sV+W6Tze6naUZQrno6wPCI6cNMGSqTLjZaK8vWkqE7UqlcrZMf46IAplGe87sjgES2aGMtHI1zp0/pV3rl956/WrydXVlZYyETHllWXu3HvS/tGHd467LDMYlWVgCgiWzAVlotLrKdsbWiZq1GtJTZmIEEKv17/T3e119ssyGw8ebbeVZZRlIE2wZO4pE0UtE7UunVtuKRPNLWWZ4nvJzkdZHyI8Mu8ESxaeMlHhWDrPKRMlS41aokw0nYaVZdqfPuh84z8+SJdlQjj58KgsAzNOsIQCc14mKtorGke+l7PLjepX//CNa8pEJ2u/LLOx091rK8t43xFOkmAJE1ImGvlah86zZaKlZj1ZaigTjUJZRniEaSRYwjFQJiq9nrK98O5vti7+7q+/kixymWhYWeaHP7vV/qfvfnQ3daqyTP562F4IQXiE4yBYwglTJjqeMlGzWU+as1cmGpRlNna6e21lmdL5KOtDhEc4WYIlTBllosKxdL525Xzjj3/vtbUvfO5SaxrKRMoyyjKwSARLmCHKRKXXPU6ZqHXuTLO11Kyt77/XOXGZKFuWefS0u3H73pP2+527N/7+Ox/cvH3vibKM8AgLQbCEOaFMNPK1Dp3n/J+JWs1GrdWoVdcrlVDZL8tsbG3vtpVljuxNsj4gPMJ8ECxhASgTlV7PqPMQxvtpV1kmRXiE+SdYwoJTJho5bKbFeu9xFssyw/ZCCMIjLDrBEig0Q2WiwRjzfc68exo3VCrLAAtDsAQmtiBlojyxf7oeZxw2974jcOoES+BYzEmZKO9aJn23UVkGmHuCJXDiprxMNOy7aTGeNnrfEZg7giUwVaawTDSM8AiQIVgCM+WUykRZyjIAOQRLYG4c43udebzvCJAhWAILIcJ7nVl+sgbIECyBhTfCe50jER6BRff/6+vcgbI+LJwAAAAASUVORK5CYII=

**Comment by luckyadam** [comment]
图片有问题吧

**Comment by syyzz3** [comment]
@luckyadam 小程序上没有问题，直接打开base64也没有问题，在网页上就出现了问题，很奇怪就是一张普通的图片

**Comment by linshuizhaoying** [comment]
解决方案是什么 @syyzz3
