### ISSUE TITLE
taro 中如何运用   动态 import（）

### ISSUE THREAD

**Issue by liuyunzyj** [NervJS/taro#4636]
例如：引入富文本组件，但富文本组件并不兼容各个平台，但是又会打包到不相干的平台上去导致小程序包过大

**Comment by luckyadam** [comment]
不支持动态 import

**Comment by liuyunzyj** [comment]
@luckyadam 富文本组件，只适用于微信小程序，使用编译命令打包其他小程序，富文本组件也会打包过去这样导致其他小程序整体包过大的问题，官方有解决的方案嘛？

**Comment by luckyadam** [comment]
> @luckyadam 富文本组件，只适用于微信小程序，使用编译命令打包其他小程序，富文本组件也会打包过去这样导致其他小程序整体包过大的问题，官方有解决的方案嘛？

我觉得你没有仔细看我发的文档
