### ISSUE TITLE
Text的decode无效了

### ISSUE THREAD

**Issue by Qingtian239113** [NervJS/taro#4639]
最新版本1.3.20，weapp

**Comment by Garfield550** [comment]
麻烦请提供一个简单的复现代码

**Comment by Qingtian239113** [comment]
如下，不能换行了，旧版本是可以的
![2681571746037_ pic](https://user-images.githubusercontent.com/9690214/67284154-a434a300-f507-11e9-8024-240a66d3f906.jpg)
