### ISSUE TITLE
函数传递和调用

### ISSUE THREAD

**Issue by ZXQ-GIGI** [NervJS/taro#464]
问题描述
从0.0.73升级到beta9时遇到的函数传递

复现步骤
<img width="584" alt="wechatimg232" src="https://user-images.githubusercontent.com/20365416/44135261-f3f5c5c6-a09a-11e8-8c5b-281c8d71f936.png">

期望行为
函数正常运行

报错信息
无反应

系统信息
操作系统: [mac]
Taro 版本 [v.1.0.0-beta6]
Node.js 版本 [9.4.0]

**Comment by yuche** [comment]
你写成 

```js
Taro.chooseImage({
  ...,
  success: () => {
  this.props.onSendMessage(..)
  }
})
```
应该这样就行了。

推荐使用 promise 版本的 API，配合 async/await 使用非常酸爽。

**Comment by ZXQ-GIGI** [comment]
还是没有任何反应

**Comment by yuche** [comment]
找一下你改了之后编译出来的 js，贴一下你编译出来 chooseImage 的代码

**Comment by ZXQ-GIGI** [comment]
- 源码
<img width="589" alt="wechatimg246" src="https://user-images.githubusercontent.com/20365416/44185883-b4553380-a148-11e8-8f49-89fe1287c2bc.png">

- 编译
<img width="555" alt="wechatimg244" src="https://user-images.githubusercontent.com/20365416/44185833-77893c80-a148-11e8-8bda-cd839eb6f41a.png">

**Comment by yuche** [comment]
**`this.props.onSendMessage`**
this this this, 你写了箭头函数就是不改 this 的引入啊

**Comment by ZXQ-GIGI** [comment]
aha，没注意，非常非常感谢~
