### ISSUE TITLE
在循环中使用 Render Props ，在小程序中会渲染异常

### ISSUE THREAD

**Issue by Dolov** [NervJS/taro#4640]
**问题描述**
将官网中 Render Props 的示例放在循环中使用，在小程序中发现多个 Cat 组件的状态是共享的，这样是不对的

**复现步骤**
[复现问题的步骤]
1. 将官网中 Render Props 的示例放在循环中使用，在小程序中发现多个 Cat 组件的状态是共享的，这样是不对的

```js

const dataSource = [
  {
    name: '京东',
    id: '001',
  },
  {
    name: '淘宝',
    id: '002',
  }
]

render () {
    return (
      <View className='index'>
        {dataSource.map(item => {
          return (
            <MouseTracker 
              key={item.id}
              
            />
          )
        })}
      </View>
    )
  }

```

**错误代码示例**
https://github.com/Dolov/su_bus

[无报错信息]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [MAC]
 - Taro 版本 [1.3.19]
 - Node.js 版本 [12.11.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shenghanqin** [comment]
请给出更加完整的示例，或者给出调用组件的源代码、截图和示例。
目前我还是没get到问题的表现。

**Comment by Dolov** [comment]
> 请给出更加完整的示例，或者给出调用组件的源代码、截图和示例。
> 目前我还是没get到问题的表现。

你好，https://github.com/Dolov/su_bus     
这个仓库中代码就可以复现问题

**Comment by guxingke201** [comment]
Render Props 是不是只支持一个？循环也只会出现第一个
![image](https://user-images.githubusercontent.com/8326941/68836403-3db13800-06f5-11ea-8203-3fc708626afb.png)

![image](https://user-images.githubusercontent.com/8326941/68836476-65a09b80-06f5-11ea-9084-2cec937f7078.png)

**Comment by Dolov** [comment]
可以正常出现，但是状态有问题
