### ISSUE TITLE
微信小程序入口文件改为HOOKS函数式组件导致生成的app.json内容为空对象，无法运行

### ISSUE THREAD

**Issue by xiajun325** [NervJS/taro#4641]
**问题描述**
微信小程序入口app.jsx由类组件形式改为函数式组件
导致生成的app.json内容为空对象

**复现步骤**
1.将app入口改为HOOKS函数式组件
2.声明config改为App.config = { ...} 
3. yarn dev:weapp
4. 编译后生成app.json 为  { }  , 导致无法运行小程序

```js
//app.jsx
export default function App() {
      return (
        <Index />
     )
}

  App.config = {
        pages: [
          'pages/index/index'
        ],
        window: {
          backgroundTextStyle: 'light',
          navigationBarBackgroundColor: '#fff',
          navigationBarTitleText: 'WeChat',
          navigationBarTextStyle: 'black'
        }
      }

```

**期望行为**
可以正常运行

**报错信息**
VM1758:1 appJSON["pages"] 字段需为 array
console.error @ VM1758:1
(anonymous) @ VM1771:2

**系统信息**
👽 Taro v1.3.20
  Taro CLI 1.3.20 environment info:
    System:
      OS: macOS High Sierra 10.13
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm

**补充信息**
问题原因：
在 mini/astProcess.js 中
```js
 else if (node.id.name === 'App') {
                        componentClassName = '_App';  //这里类名改为_App
  
......
 if (left.object.name === componentClassName // 这里比较时用的是 App, 所以不等
                    && t.isIdentifier(left.property)
                    && left.property.name === 'config') {
                    needSetConfigFromHooks = true;
                    configFromHooks = node.right;

```
经验证，将App.config= ...  改为_App.config = ... 就可以了

**Comment by luckyadam** [comment]
app 不能改成 hook

**Comment by luckyadam** [comment]
app 不能改成 hook

**Comment by saviourdog** [comment]
same shit
