### ISSUE TITLE
[RN]"boxSizing" is not a valid style property 

### ISSUE THREAD

**Issue by everfire130** [NervJS/taro#4643]
[复现问题的步骤]
1. 写一个带box-sizing属性的scss及使用到页面上
2. npm run dev:rn
3. 用taro-native-shell打开应用
![4721571711193_ pic_hd](https://user-images.githubusercontent.com/11308837/67255915-2183f780-f4b7-11e9-88f0-cfae355488c6.jpg)

**Comment by Garfield550** [comment]
> flexbox in RN doesn’t have box-sizing property but flex items behave as if they have box-sizing: content-box (not border-box - that is padding and border are not included in component’s width and height).

Ref: http://blog.tap349.com/react-native/flexbox/2017/11/18/react-native-layout/#box-sizing

> React Native styles all views as if box-sizing: border-box is set. See this code: https://github.com/facebook/react-native/blob/5aa1fb3ff326a429e33a443576da866f2a63c20c/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L632

Ref: https://stackoverflow.com/questions/38503451/does-it-exist-an-equivalent-of-box-sizing-border-box-in-flexbox-for-react-nativ

**Comment by everfire130** [comment]
I know.But how to ignore the property in taro. @Garfield550

**Comment by Pines-Cheng** [comment]
[样式代码的条件编译](https://taro-docs.jd.com/taro/docs/before-dev-remind.html#%E6%A0%B7%E5%BC%8F%E7%9A%84%E6%9D%A1%E4%BB%B6%E7%BC%96%E8%AF%91)
