### ISSUE TITLE
[Taro][Mobx][WeChat Mini App]thirdScriptError Cannot read property 'init' of undefined;at "pages/xxx/xxx" page lifeCycleMethod onReady function

### ISSUE THREAD

**Issue by JimmieWong** [NervJS/taro#4644]
👽 Taro v1.3.21

  Taro CLI 1.3.21 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.21 => 1.3.21 
      @tarojs/mobx: 1.3.21 => 1.3.21 
      @tarojs/mobx-h5: 1.3.21 => 1.3.21 
      @tarojs/mobx-rn: 1.3.21 => 1.3.21 
      @tarojs/plugin-babel: 1.3.21 => 1.3.21 
      @tarojs/plugin-csso: 1.3.21 => 1.3.21 
      @tarojs/plugin-sass: 1.3.21 => 1.3.21 
      @tarojs/plugin-uglifyjs: 1.3.21 => 1.3.21 
      @tarojs/rn-runner: 1.3.21 => 1.3.21 
      @tarojs/router: 1.3.21 => 1.3.21 
      @tarojs/taro: 1.3.21 => 1.3.21 
      @tarojs/taro-alipay: 1.3.21 => 1.3.21 
      @tarojs/taro-h5: 1.3.21 => 1.3.21 
      @tarojs/taro-swan: 1.3.21 => 1.3.21 
      @tarojs/taro-tt: 1.3.21 => 1.3.21 
      @tarojs/taro-weapp: 1.3.21 => 1.3.21 
      @tarojs/webpack-runner: 1.3.21 => 1.3.21 
      eslint-config-taro: 1.3.21 => 1.3.21 
      eslint-plugin-taro: 1.3.21 => 1.3.21 
      nerv-devtools: ^1.5.1 => 1.5.1 
      nervjs: ^1.5.1 => 1.5.1 
      stylelint-config-taro-rn: 1.3.21 => 1.3.21 
      stylelint-taro-rn: 1.3.21 => 1.3.21 
    npmGlobalPackages:
      typescript: 3.4.5

Wechat debug base library: 2.9.0
<img width="524" alt="Screen Shot 2019-10-21 at 10 48 49 PM" src="https://user-images.githubusercontent.com/1055066/67256396-5c872a80-f4b9-11e9-9534-081ba26d3586.png">

**Comment by nanjingboy** [comment]
@JimmieWong 大佬还能提供一个可复现的 demo ？

**Comment by JimmieWong** [comment]
> @JimmieWong 大佬还能提供一个可复现的 demo ？

[taro-demo-thirdScriptError.zip](https://github.com/NervJS/taro/files/3753822/taro-demo-thirdScriptError.zip)

**Comment by JimmieWong** [comment]
@nanjingboy 请用demo复现 and FYI.
0. 在mac电脑上
1. 目前本地所有的环境都是最新的, 包括wechat devtools， 如图。
2. taro 1.3.20 也有类似情况。
3. taro 1.3.19 在网络上下载的demo 没有这个问题。
4. 移植到taro 模版创建的mobx工程里出现问题。

<img width="330" alt="Screen Shot 2019-10-22 at 12 26 06 PM" src="https://user-images.githubusercontent.com/1055066/67259197-251f7a80-f4c7-11e9-9e37-060abda355e5.png">

**Comment by nanjingboy** [comment]
@JimmieWong 由于 `Gauge` ref 了 `GaugeChart`，而 `GaugeChart` 又 ref 了 `ec-canvas`，你在  
`Gauge` 的 `componentDidMount` 调用 `GaugeChart` 的 `refresh` 方法，此时 `GaugeChart` 还没有 ready，所以在 `GaugeChart` 的 `refresh` 中 `this.Chart` 为 `undefined`。建议根据小程序的生命周期顺序调整一下写法（目前能保证的是在 componentDidMount 中肯定能拿到 ref），或者这样修改
`refresh` 方法：

```js
refresh(data) {
  if (this.Chart) {
    this.Chart.init(...)
  } else {
    setTimeout(() => {
      this.Chart.init(...)
    }, 0)
  }
}
```

**Comment by JimmieWong** [comment]
Thanks for your support. and your solution works.
