### ISSUE TITLE
Process is not defined

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#4645]
**问题描述**
目的:开发包太大无法预览,想在开发的时候利用taro压缩功能.
已知taro开发时候压缩代码的命令是   NODE_ENV=production taro build --type weapp --watch,为了方便我本地判断process.env.NODE_ENV===production时打包正式服务器版本,否则打包预发布(开发)版本,但是为了压缩代码必须设置NODE_ENV=production,所以我该如何使用taro设置一个环境变量判断当前为开发环境或正式环境.

**复现步骤**
![image](https://user-images.githubusercontent.com/42051272/67257304-eafdab00-f4bd-11e9-8f9e-e81296ed528b.png)

**期望行为**
传递参数获取process

**报错信息**

![image](https://user-images.githubusercontent.com/42051272/67257304-eafdab00-f4bd-11e9-8f9e-e81296ed528b.png)

**系统信息**
Taro CLI 1.3.20 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.20 => 1.3.20 
      @tarojs/cli: 1.3.20 => 1.3.20 
      @tarojs/components: 1.3.20 => 1.3.20 
      @tarojs/plugin-babel: 1.3.20 => 1.3.20 
      @tarojs/plugin-csso: 1.3.20 => 1.3.20 
      @tarojs/plugin-less: 1.3.20 => 1.3.20 
      @tarojs/plugin-uglifyjs: 1.3.20 => 1.3.20 
      @tarojs/redux: 1.3.20 => 1.3.20 
      @tarojs/redux-h5: 1.3.20 => 1.3.20 
      @tarojs/rn-runner: 1.3.20 => 1.3.20 
      @tarojs/router: 1.3.20 => 1.3.20 
      @tarojs/taro: 1.3.20 => 1.3.20 
      @tarojs/taro-h5: 1.3.20 => 1.3.20 
      @tarojs/taro-weapp: 1.3.20 => 1.3.20 
      @tarojs/webpack-runner: 1.3.20 => 1.3.20 
      eslint-config-taro: 1.3.20 => 1.3.20 
      eslint-plugin-taro: 1.3.20 => 1.3.20 
      nervjs: ^1.5.1 => 1.5.1

**Comment by Garfield550** [comment]
试一下 `defineConstants` 可不可以。
https://nervjs.github.io/taro/docs/config-detail.html#defineconstants

**Comment by VFiee** [comment]
> 试一下 `defineConstants` 可不可以。
> https://nervjs.github.io/taro/docs/config-detail.html#defineconstants

谢谢,我设置了env现在可以了 https://nervjs.github.io/taro/docs/config-detail.html#env

**Comment by joweyoung** [comment]
> > 试一下 `defineConstants` 可不可以。
> > https://nervjs.github.io/taro/docs/config-detail.html#defineconstants
> 
> 谢谢,我设置了env现在可以了 https://nervjs.github.io/taro/docs/config-detail.html#env

具体是怎么设置的呢？可以给个代码截图吗

**Comment by Chen-jj** [comment]
> > > 试一下 `defineConstants` 可不可以。
> > > https://nervjs.github.io/taro/docs/config-detail.html#defineconstants
> > 
> > 
> > 谢谢,我设置了env现在可以了 https://nervjs.github.io/taro/docs/config-detail.html#env
> 
> 具体是怎么设置的呢？可以给个代码截图吗

taro build 命令的输出就有具体设置的代码，仔细看看
