### ISSUE TITLE
【优化】编写闭包函数式组件控制台eslint报错

### ISSUE THREAD

**Issue by wuhuanda** [NervJS/taro#4646]
**问题描述**
taro官方文档上的描述：“**闭包函数式组件** 自 v1.3.0-beta.2 起支持”,目前在项目中使用的taro版本号为1.3.20,直接编写闭包函数式组件会报eslint error

**复现步骤**
1. 编写函数式闭包组件
```
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.css'

function Index() {
  const renderTitle = () => {
    return <View><Text>test</Text></View>
  };
  return (
    <View>{renderTitle()}</View>
  );
}

export default Index;
```
2. 控制台 `eslint` 报错

**期望行为**
支持闭包函数式组件在函数式组件编译不是eslint报错而是warning或者支持配置该条eslint。

**报错信息**
![image](https://user-images.githubusercontent.com/32833804/67258117-affd7680-f4c1-11e9-91d4-2067c1d803ef.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: Windows 10
 - Taro 版本 v.1.3.20
 - Node.js 版本 10.16.3
 - 报错平台 weapp

**补充信息**
可能是源码在转换阶段进行了eslint规则的定义。[https://github.com/NervJS/taro/blob/master/packages/taro-transformer-wx/src/eslint.ts](https://github.com/NervJS/taro/blob/master/packages/taro-transformer-wx/src/eslint.ts)
![image](https://user-images.githubusercontent.com/32833804/67258266-4c277d80-f4c2-11e9-8a02-7381857ac8c2.png)

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
