### ISSUE TITLE
h5中的Video组件添加poster后，视频播放进度条失效

### ISSUE THREAD

**Issue by hanyingming** [NervJS/taro#4648]
**问题描述**
taro打包的h5, Video组件中设置poster封面图后，控制器的进度条失效

**复现步骤**
[复现问题的步骤]
1.问题代码：包含poster属性
 <Video
              controls={true}
              src='http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400'
              poster='http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg'
              showFullscreenBtn={false}
              showCenterPlayBtn={process.env.TARO_ENV === 'h5'}
              initialTime='0'
              id='myVideo'
              style={{ width: '100%', height: '100%' }}
              object-fit='contain'
              onPlay={this.handStartPlay}
              onEnded={this.handleVideoEnded}
              onPause={this.handlePause}
              className={styles.videoView}
            >
            </Video>

截图：
![image](https://user-images.githubusercontent.com/24975264/67259364-f81f9780-f4c7-11e9-9d5d-a22fb3ee7411.png)

2. 无问题代码（需要注释poster属性） 
  <Video
              controls={true}
              src='http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400'
              // poster='http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg'
              showFullscreenBtn={false}
              showCenterPlayBtn={process.env.TARO_ENV === 'h5'}
              initialTime='0'
              id='myVideo'
              style={{ width: '100%', height: '100%' }}
              object-fit='contain'
              onPlay={this.handStartPlay}
              onEnded={this.handleVideoEnded}
              onPause={this.handlePause}
              className={styles.videoView}
            >
            </Video>
截图：
![image](https://user-images.githubusercontent.com/24975264/67259268-74fe4180-f4c7-11e9-9d2b-78e525aab60f.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
h5自定义进度条为什么因为设置了poster属性而失效？

**报错信息**
![image](https://user-images.githubusercontent.com/24975264/67259364-f81f9780-f4c7-11e9-9d5d-a22fb3ee7411.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
 - 操作系统: Windows 10
 - Taro 版本 1.3.13 or 1.3.21
 - Node.js 版本 v10.13.0
 - 报错平台 h5

  Taro CLI 1.3.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Users\DELL\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - D:\Program Files\nodejs\npm.CMD

**Comment by shichaohui** [comment]
@Chen-jj 为什么关了，解决方案呢？
