### ISSUE TITLE
taro如何升级react-navigation

### ISSUE THREAD

**Issue by jackgreentemp** [NervJS/taro#4649]
taro进行RN开发时，默认路由导航使用的是react-navigation 2.x，

但是目前react-navigation最新版本已经到4.x。如何升级？

**Comment by Pines-Cheng** [comment]
Taro RN 端的路由及 API 和 微信小程序一致，基于 react-navigation 封装好的，直接调用就可以，有什么场景需要直接使用 react-navigation 吗？

**Comment by jackgreentemp** [comment]
@Pines-Cheng
您好，使用底部tabBar导航，部分tab页面是h5，为了在tab首页对其它tab页进行预加载，需要使用react-navigation高版本的lazy:false属性。

**Comment by Pines-Cheng** [comment]
> createBottomTabNavigator里原来的navigationOptions，要改成defaultNavigationOptions，然后app.js里的RootStack，要用createAppContainer(RootStack)包装一下。

升级 v4 涉及到 Android 和 iOS 端原生的改动：[Getting started](https://reactnavigation.org/docs/zh-Hans/getting-started.html)，而收益又有限，决定暂不升级。
