### ISSUE TITLE
反向继承组件的时候 render()劫持失败

### ISSUE THREAD

**Issue by BryantZhou** [NervJS/taro#465]
**问题描述**
模仿@tarojs/redux里面的connect方法进行反向劫持组件，只能劫持到正常的声明周期，render方法劫持失败

**复现步骤**

decorator.js
```js
function demo() {
  return function demoComponent(Component) {
    class Demo extends Component {
      async componentWillMount() {
        console.log('in will -------------->');
        if (super.componentWillMount) {
          super.componentWillMount();
        }
      }

      render() {
        console.log('in render -------------->');

        return super.render();
      }
    }

    return Demo;
  };
}

export default demo;

```
component

```js
@demo()
class Index extends Component {
  componentWillMount() {
    console.log('Component WillMount');
  }
  render() {
    console.log('Component Render');
    
    return <View />
  }
}
```
控制台输出
![image](https://user-images.githubusercontent.com/12403684/44142336-77d04184-a0b2-11e8-82d7-cfb28605e11b.png)

**期望行为**
能劫持到render

**报错信息**

**系统信息**

 - 操作系统: [e.g. MacOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.0-beta.10]
 - Node.js 版本 [e.g. v8.11.1]

**补充信息**

**Comment by AlexStacker** [comment]
H5版本没有这个问题。

**Comment by BryantZhou** [comment]
所以就是在小程序里面 没办法利用这个方法对与return的数据进行一次劫持修改之类的操作么

**Comment by luckyadam** [comment]
@BryantZhou 劫持数据的话，可以试试能不能用 `_createData()` 方法

**Comment by BryantZhou** [comment]
@luckyadam _createData()是能拿到数据 貌似我表达错了 我是想操控render时候dom的渲染，例如在组件基础上加多一层组件之类的需求，现在我暂时用了redux来解决了这个问题，等你们支持了无状态组件，这个需求应该就很好解决了，thx

**Comment by luckyadam** [comment]
@BryantZhou OJBK

**Comment by adsjkqhaoran** [comment]
我也遇到这个问题 本来打算在组件外层 通过高阶组件的功能 集成验证表单的功能和提示组件 但是发现不能重新render= =

**Comment by bigggge** [comment]
`function demoComponent(Component) {
  class Demo extends Component {
    componentWillMount() {
      console.log('in will -------------->');
      if (super.componentWillMount) {
        super.componentWillMount();
      }
    }

    render() {
      console.log('in render -------------->');

      return super.render();
    }
  }

  return Demo;
}

class Test extends Component {
  componentWillMount() {
    console.log('Component WillMount');
  }

  render() {
    console.log('Component Render');

    return <View />;
  }
}

export default demoComponent(Test);`

为什么上面这段代码 in will --------------> 也打不出来

**Comment by yuche** [comment]
Duplicate of  #1155

**Comment by youngluo** [comment]
> ```
> function demoComponent(Component) {
>   class Demo extends Component {
>     componentWillMount() {
>       console.log('in will -------------->');
>       if (super.componentWillMount) {
>         super.componentWillMount();
>       }
>     }
> 
>     render() {
>       console.log('in render -------------->');
> 
>       return super.render();
>     }
>   }
> 
>   return Demo;
> }
> 
> class Test extends Component {
>   componentWillMount() {
>     console.log('Component WillMount');
>   }
> 
>   render() {
>     console.log('Component Render');
> 
>     return <View />;
>   }
> }
> 
> export default demoComponent(Test);
> ```
> 为什么上面这段代码 in will --------------> 也打不出来

同问？

**Comment by HeyShinner** [comment]
> ```
> function demoComponent(Component) {
>   class Demo extends Component {
>     componentWillMount() {
>       console.log('in will -------------->');
>       if (super.componentWillMount) {
>         super.componentWillMount();
>       }
>     }
> 
>     render() {
>       console.log('in render -------------->');
> 
>       return super.render();
>     }
>   }
> 
>   return Demo;
> }
> 
> class Test extends Component {
>   componentWillMount() {
>     console.log('Component WillMount');
>   }
> 
>   render() {
>     console.log('Component Render');
> 
>     return <View />;
>   }
> }
> 
> export default demoComponent(Test);
> ```
> 
> 为什么上面这段代码 in will --------------> 也打不出来

同问
