### ISSUE TITLE
h5上传图片使用chooseImage返回的blob路径,通过uploadFile方法上传后端无法获取？

### ISSUE THREAD

**Issue by syyzz3** [NervJS/taro#4650]
![QQ截图20191022165038](https://user-images.githubusercontent.com/11385973/67271373-f61bff80-f4ec-11e9-856b-8175741478c7.png)
![QQ截图20191022165421](https://user-images.githubusercontent.com/11385973/67271490-31b6c980-f4ed-11e9-936a-60f21633dd8b.png)

chooseImage方法返回的filePath是这种：blob:http://localhost:33333/d736aff9-884b-409f-9641-905cafd57978
通过uploadFile方法进行上传
![QQ截图20191022165340](https://user-images.githubusercontent.com/11385973/67271471-29f72500-f4ed-11e9-8899-1abc85da2a65.png)
![QQ截图20191022165643](https://user-images.githubusercontent.com/11385973/67271504-38ddd780-f4ed-11e9-92d3-b4023d90b89f.png)
后端无法获取我传的值是什么原因？

**Comment by zongyan86** [comment]
碰到同样的问题啊，兄弟，怎么解决的？

**Comment by syyzz3** [comment]
@zongyan86 判读是否是h5，如果是就用input file的方式提交

**Comment by zongyan86** [comment]
好的，我目前已经通过这种方式实现。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"syyzz3"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午4:46
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"许宗彦"<378588579@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] h5上传图片使用chooseImage返回的blob路径,通过uploadFile方法上传后端无法获取？ (#4650)




@zongyan86 判读是否是h5，如果是就用input file的方式提交
