### ISSUE TITLE
在H5环境中@inject('')它的存在会导致H5标题Title的消失

### ISSUE THREAD

**Issue by msl573885800** [NervJS/taro#4651]
![image](https://user-images.githubusercontent.com/45838485/67273143-76902f80-f4f0-11e9-814a-0cf20b9cb7fd.png)
当上面圈起来的两个同时存在时，打包后标题消失，如果去掉@inject('')，标题就能显示

**Comment by nanjingboy** [comment]
@msl573885800 更新到最新版本 `1.3.21`，最新版本是好的。

<img width="375" alt="屏幕快照 2019-10-22 下午5 43 56" src="https://user-images.githubusercontent.com/1390888/67274683-8bba8d80-f4f3-11e9-90f3-f92431a18030.png">

<img width="253" alt="屏幕快照 2019-10-22 下午5 43 44" src="https://user-images.githubusercontent.com/1390888/67274681-8b21f700-f4f3-11e9-91b2-cf7df17a19e5.png">
