### ISSUE TITLE
outputRoot: `dist/${process.env.TARO_ENV}` 无效

### ISSUE THREAD

**Issue by zoujunda** [NervJS/taro#4653]
**问题描述**
参照文档多端同步调试配置：outputRoot: `dist/${process.env.TARO_ENV}`，编译调试生成的目录为dist/undefined

**复现步骤**
[复现问题的步骤]
1. 在 config/index.js，配置outputRoot: `dist/${process.env.TARO_ENV}`
2. 运行：dev:weapp

**期望行为**
达到文档效果

**报错信息**
![image](https://user-images.githubusercontent.com/22700161/67275633-9bd36c80-f4f5-11e9-9da9-2ace844f1ab4.png)
![image](https://user-images.githubusercontent.com/22700161/67275643-a0982080-f4f5-11e9-8a9e-b26b616ad478.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows 7]
 - Taro 版本 [ v1.3.21]
 - Node.js 版本 [ 10.1.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
应该是config/index.js文件中process.env.TARO_ENV 为undefined导致

**Comment by sankincn** [comment]
构建配置都还没有执行，此时环境变量还未植入node进程，应该是拿不到env的。你可以在index.js底部暴露的方法里获取env，然后把修改outputRoot值。。

**Comment by zoujunda** [comment]
可以直接从构建命令获取环境变量，参照cross-env。



zoujunda@coship.com
 
发件人： Sankin Tan
发送时间： 2019-10-22 20:37
收件人： NervJS/taro
抄送： zoujunda; Author
主题： Re: [NervJS/taro] outputRoot: `dist/${process.env.TARO_ENV}` 无效 (#4653)
构建配置都还没有执行，此时环境变量还未植入node进程，应该是拿不到env的。你可以在index.js底部暴露的方法里获取env，然后把修改outputRoot值。。

**Comment by zoujunda** [comment]
已解决，是自己编译器默认yarn对应的taro cli和npm taro cli版本不一致导致
