### ISSUE TITLE
gitlab ci cd

### ISSUE THREAD

**Issue by ikerlin** [NervJS/taro#4659]
**问题描述**
我们使用gitlab的ci/cd构建项目，但是服务器上没有taro，所以会导致`yarn build:h5`的时候报错。服务器上采用基于nodejs的docker镜像构建，如果镜像把taro-cli打包进去每次更新都要修改镜像，有没有不打包taro-cli到镜像内的更好方案？

**复现步骤**

**期望行为**
正常打包

**报错信息**

```bash
$ taro build --type h5
/bin/sh: 1: taro: not found
error Command failed with exit code 127.
```

**系统信息**

 - 操作系统: linux
 - Taro 版本: v1.3.9
 - Node.js 版本: 8.0
 - 报错平台: h5

**Comment by Garfield550** [comment]
有的，参考 Taro UI 的做法，是把 `@tarojs/cli` 添加到项目的 `package.json` 里。

```json
"devDependencies": {
  "@tarojs/cli": "1.3.15",
}
```

https://github.com/NervJS/taro-ui/blob/dev/package.json

**Comment by cong1223** [comment]
> ```json
> "@tarojs/cli": "1.3.15",
> ```

请问解决了吗

**Comment by cong1223** [comment]
解决了吗
