### ISSUE TITLE
刚创建的项目，怎么这么多的红色警告

### ISSUE THREAD

**Issue by januwA** [NervJS/taro#466]
![image](https://user-images.githubusercontent.com/22570563/44142803-fb355d4c-a0b3-11e8-9610-4b9e684cbb7f.png)

**Comment by AlexStacker** [comment]
请试试用@tarojs/cli 1.0.0-beta.10创建，全局安装这个版本。

**Comment by luckyadam** [comment]
@AlexStacker +1

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/455
