### ISSUE TITLE
index.esm.js?eb37:1884   Uncaught (in promise) TypeError: Cannot read property 'dom' of undefined

### ISSUE THREAD

**Issue by zouhailin** [NervJS/taro#4660]
**问题描述**
    微信原生小程序代码转taro

**复现步骤**
[复现问题的步骤]
    1: 执行 taro convert  无报错
    2: 执行 yarn dev:h5   无报错
    3: 运行 0.0.0.0:10086 报以上错误
    4: 无scss 样式

**Comment by yuche** [comment]
升级 nervjs 依赖到 1.5.1

**Comment by zouhailin** [comment]
> 升级nervjs依赖到1.5.1或降级到1.4.7

已经这么做过， 但是无效
