### ISSUE TITLE
useDidShow取值错误

### ISSUE THREAD

**Issue by wangruiStart** [NervJS/taro#4664]
**问题描述**
A页面useSelector从store中取到的prop 为false，useState的值也是false，A 页面进行操作将prop和state都改为true。路由跳转到B。再从B跳回A后触发A的useDidShow, 这时候回调中的props和state都是
还是false。是初始值

**报错信息**

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [macOS，]
 - Taro 版本 [1.3.14]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Garfield550** [comment]
麻烦请提供一个复现 Demo 可以吗

**Comment by wangruiStart** [comment]
> 麻烦请提供一个复现 Demo 可以吗
感觉demo反而更说不清。

...
import Taro, { useState, useDidShow } from '@tarojs/taro';
import {View, Button} from '@tarojs/components';

export default () => {

  const [number, setState] = useState(0);

  useDidShow( () => {
    console.log(number)
  })

  return (
    <View>
      <Button onClick={() => setState(pre => pre + 1)}>增加</Button>
    </View>
  )
}
...

不知道你能不能看懂。点击一次增加之后，页面跳转出去再跳回来，这时候理想值应该是打印1.实际上打印的还是0

**Comment by xxyGoTop** [comment]
同样得问题，赶紧解决下，紧急

如: 抽离出来一个存取本地storage hooks

```js
const useLocalStorage = <T>(key: string, initialValue?: T, isSerial?: boolean): [T, (value: T) => void] => {
  const [state, setState] = useState<T>(() => {
    try {
      const storageValue = Taro.getStorageSync(key);
      if(typeof storageValue !== 'string') {
        Taro.setStorageSync(key, isSerial ? String(initialValue) : JSON.stringify(initialValue));
        return initialValue;
      } else {
        return isSerial ? storageValue : JSON.parse(storageValue || 'null');
      }
    } catch(e) {
      console.error('init storage value error')
      return initialValue;
    }
  });

  useEffect(() => {
    try {
      Taro.setStorageSync(key, isSerial ? String(state) : JSON.stringify(state));
    } catch(e) {
      console.error('set storage value error')
    }
  }, [state]);

  return [state, setState];
};

export default useLocalStorage;
```

在login page 页设置完token

```js
const [token, setToken] = useLocalStorage<string>('token');
function Index() {
    handleTOken（） {
       setToken('asdasdasdasd') // 此时设置token
       Taro.navigateTo({
         url: "/pages/index/index"
        })
     }
}
```

但是切换到index page页面获取得时候
```js
const [token] = useLocalStorage<string>('token');
function Index() {
    useDidShow（） {
       console.log(token) // 此时打印token依然是null
     }
}

```

**Comment by xxyGoTop** [comment]
@Garfield550

**Comment by luckyadam** [comment]
@wangruiStart 没有复现你所说的问题，麻烦升级到最新版本试试
@xxyGoTop 你的 taro 版本多少

**Comment by xxyGoTop** [comment]
@luckyadam 1.3.19

**Comment by wangruiStart** [comment]
1.3.22正常了@xxyGoTop

**Comment by wangruiStart** [comment]
如果用到f2，不要升级。会报错。采坑了。。。。。@ xxyGoTop

**Comment by xxyGoTop** [comment]
好吧，暂时就不升级了 @wangruiStart
