### ISSUE TITLE
Taro 1.3.21 RN项目启动默认还是expo

### ISSUE THREAD

**Issue by zoujunda** [NervJS/taro#4665]
**问题描述**
Taro 1.3.21 RN项目启动默认还是expo。是按文档操作的，删除node_modules重新install后，还是一样。

**复现步骤**
[复现问题的步骤]
1. 使用taro命令创建项目模板 taro init projec
2. yarn install
3. npm run build:rn -- --watch

**期望行为**
默认使用taro-native-shell壳子

**报错信息**
![image](https://user-images.githubusercontent.com/22700161/67353900-514e0080-f586-11e9-9675-1b96de59acc5.png)
![image](https://user-images.githubusercontent.com/22700161/67353919-590da500-f586-11e9-846b-067f4ce3f12d.png)
![image](https://user-images.githubusercontent.com/22700161/67353929-632fa380-f586-11e9-8c45-3bfe27572a5e.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [Windows7]
 - Taro 版本 [v1.3.21]
 - Node.js 版本 [10.1.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Pines-Cheng** [comment]
没有重现，为什么你初始化的项目依赖同时存在 1.3.21 和 1.2.0 两个版本？

**Comment by zoujunda** [comment]
> 没有重现，为什么你初始化的项目依赖同时存在 1.3.21 和 1.2.0 两个版本？

嗯，我发现这个问题了。我的taro客户端是通过"taro update self"升到1.3.21的,之前是1.2.26版本，可能是升级不完全导致。我现在正在重现安装taro cli，感觉应该可以解决问题，解决好了，再回复。

**Comment by zoujunda** [comment]
> 没有重现，为什么你初始化的项目依赖同时存在 1.3.21 和 1.2.0 两个版本？
重现安装了taro cli还是不行
![image](https://user-images.githubusercontent.com/22700161/67363926-0beafc80-f5a1-11e9-890e-0fab8a336248.png)
![image](https://user-images.githubusercontent.com/22700161/67363970-28873480-f5a1-11e9-9ec1-4950a0e23e56.png)

**Comment by zoujunda** [comment]
解决了。原因是我webstorm默认配置的是yarn命令，yarn安装的taro cli是1.2.0版本，而通过taro update self 升级的是npm 下的taro。删除掉yarn下的taro，webstorm配置改为npm，就可以了
