### ISSUE TITLE
[微信小程序]mobx的computed(getter)属性在条件渲染下无效

### ISSUE THREAD

**Issue by drewxiuxiuxiu** [NervJS/taro#4667]
**问题描述**
```jsx
let local = useLocalStore(() => ({
    get foo() {
       return 'bar'
    }
  }))

return (
    <View>
        { local.foo === 'bar' && <SomeView /> }
    </View>
)
```

在此情况下`SomeView`永远无法渲染. 微信调试工具中可见store中并没有`foo`属性.

H5正常.

**复现步骤**
[复现问题的步骤]
如上

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
与H5相同

**报错信息**

无
**系统信息**

Taro CLI 1.3.21 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v8.15.0/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v8.15.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.19 => 1.3.21 
      @tarojs/components: 1.3.21 => 1.3.21 
      @tarojs/mobx: 1.3.21 => 1.3.21 
      @tarojs/mobx-h5: 1.3.21 => 1.3.21 
      @tarojs/mobx-rn: 1.3.21 => 1.3.21 
      @tarojs/plugin-babel: 1.3.21 => 1.3.21 
      @tarojs/plugin-csso: 1.3.21 => 1.3.21 
      @tarojs/plugin-sass: 1.3.21 => 1.3.21 
      @tarojs/plugin-uglifyjs: 1.3.21 => 1.3.21 
      @tarojs/rn-runner: 1.3.21 => 1.3.21 
      @tarojs/router: 1.3.21 => 1.3.21 
      @tarojs/taro: 1.3.21 => 1.3.21 
      @tarojs/taro-alipay: 1.3.21 => 1.3.21 
      @tarojs/taro-h5: 1.3.21 => 1.3.21 
      @tarojs/taro-swan: 1.3.21 => 1.3.21 
      @tarojs/taro-tt: 1.3.21 => 1.3.21 
      @tarojs/taro-weapp: 1.3.21 => 1.3.21 
      @tarojs/webpack-runner: 1.3.21 => 1.3.21 
      eslint-config-taro: 1.3.21 => 1.3.21 
      eslint-plugin-taro: 1.3.21 => 1.3.21 
      nerv-devtools: ^1.4.0 => 1.5.1 
      nervjs: ^1.4.0 => 1.5.1 
      stylelint-config-taro-rn: 1.3.21 => 1.3.21 
      stylelint-taro-rn: 1.3.21 => 1.3.21 
    npmGlobalPackages:
      typescript: 3.6.2

**补充信息**
[可选]

**Comment by nanjingboy** [comment]
@drewxiuxiuxiu 不要在 `JSX` 中对可观察对象进行引用，这样修改代码：

```js
let local = useLocalStore(() => ({
    get foo() {
       return 'bar'
    }
  }))


const { foo } = local

return (
    <View>
        { foo === 'bar' && <SomeView /> }
    </View>
)
```

具体描述参见：http://taro-docs.jd.com/taro/docs/mobx.html#observer
