### ISSUE TITLE
安卓微信内使用navigatorTo跳转，返回后，componentDidMount 会再次执行

### ISSUE THREAD

**Issue by xiangjiejie** [NervJS/taro#4670]
**问题描述**
安卓微信内，页面A使用navigatorTo跳转页面B，返回后，页面A componentDidMount 会再次执行。
页面A会生成新的实例，存在多个实例，导致页面越来越卡
IOS内，页面A componentDidMount不会再次执行

**复现步骤**
页面A 使用Taro.navigatorTo 跳到页面B，返回页面A

**可复现代码**
pageA
``` pageA
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'

class Index extends Component {
  componentDidMount () {
    console.log('componentDidMount');
  }

  navigator = () => {
    Taro.navigateTo({
      url: '/pages/demo/index'
    })
  }

  render () {
    return (
      <View className='index'>
        <Text onClick={this.navigator}>navigator</Text>
      </View>
    )
  }
}

export default Index 

```
pageB

``` pageB
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

class Demo extends Component {
  render () {
    return (
      <View className='demo'>
        demo
       
      </View>
    )
  }
}

export default Demo 

```

**期望行为**
返回后，页面A不再执行componentDidMount,不应该存在多个相同的实例

**报错信息**
页面A刚加载：一个taro_page
![11](https://user-images.githubusercontent.com/10069039/67390363-1fad5780-f5cf-11e9-9558-0ad470d4ff8d.jpg)
页面A返回后：两个taro_page
![11_2](https://user-images.githubusercontent.com/10069039/67390379-263bcf00-f5cf-11e9-9844-b352935402f9.jpg)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: 安卓 + 微信
 - Taro 版本 1.3.14
 - 报错平台 H5

**Comment by Chen-jj** [comment]
@xiangjiejie 最好能提供一份完整可复现代码

**Comment by xiangjiejie** [comment]
> @xiangjiejie 最好能提供一份完整可复现代码

已贴代码，请查看。可能还是部分安卓微信会出现这种情况

**Comment by shenghanqin** [comment]
您可以尝试一下在ios上是不是也有同样的问题？

因为我还没深入接触到Taro的核心，我说一下我的浅显理解。
小程序分为JS核心层和View视图层，而视图层可能有多个，中间用原生层来通信。也就是说，PageA页面跳到PageB时，PageA页面的视图层还存在着，只是暂时onHide啦。返回时只会触发onShow。

而h5中，其实跟React上差不多，是在一个网页容器中实现的跳转，那么返回PageA页面时，还是会触发ComponentDidMount的。
