### ISSUE TITLE
支付宝小程序中componentDidMount没有在onReady中触发

### ISSUE THREAD

**Issue by frojan** [NervJS/taro#4674]
支付宝小程序中componentDidMount没有在onReady中触发，想在onReady中处理一些逻辑，但没找到对应的生命周期，直接写onReady貌似也不行。

为之奈何？

1024快乐！

**Comment by Chen-jj** [comment]
@frojan 现在页面和组件分别会在 onLoad 和 didMount 生命周期里做一次 setData，在 setData 的 callback 中触发 componentDidMount。对于页面来说应该和 onReady 差不多的时机，对于组件那当然会比 didMount 晚一些。逻辑放 componentDidMount 有什么问题？

**Comment by frojan** [comment]
@Chen-jj  目前倒没啥问题，做些统计，时间可能会有偏差。只是看到和微信小程序的实现不一样，有疑惑所以问一下。
