### ISSUE TITLE
小程序里 mobx inject 不支持 hooks 组件

### ISSUE THREAD

**Issue by ickeep** [NervJS/taro#4676]
**问题描述**
小程序里 mobx inject 不支持 hooks 组件

```js
import Taro from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'
import { inject, observer } from '@tarojs/mobx'
import Store, { User } from '../../store'
import './index.less'

function Index(props: { user: User }) {
  // props 为空对象 inject 后取不到 user 的值
  // const { user: { user, setUser } } = props 报错
  const { user: { user, setUser } = Store.user } = props // 临时解决方案

  return (
    <View className='index'>
      <Text>Hello world!{user.id} 111 {user.name}</Text>
      <Button onClick={() => setUser({ id: 1, name: '1234' })}>setUser</Button>
      <Button onClick={() => setUser({ id: '', name: '' })}>setUser</Button>
    </View>
  )
}

Index.config = {
  navigationBarTitleText: '首页'
}

export default inject('user')(observer(Index))

```

**期望行为**
小程序里 mobx inject 与 h5 一致 支持 hooks 组件

**报错信息**

![image](https://user-images.githubusercontent.com/9164133/67456993-0bb43500-f665-11e9-8863-0884f0374f20.png)

**系统信息**
 Taro CLI 1.3.20 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm

**Comment by nanjingboy** [comment]
@ickeep inject 只在类组件中可用

**Comment by suiyi8760** [comment]
那请问用hooks的话怎么inject呢

**Comment by nanjingboy** [comment]
@suiyi8760  用 hooks 就能获得 store 信息了，要 inject 干吗？看这里的例子：https://github.com/nanjingboy/taro-mobx-sample

**Comment by suiyi8760** [comment]
> @suiyi8760 用 hooks 就能获得 store 信息了，要 inject 干吗？看这里的例子：https://github.com/nanjingboy/taro-mobx-sample

是用createContext？这个api不是只支持微信小程序吗

**Comment by hlsky1988** [comment]
@suiyi8760 请问这个问题你解决了吗？ taro2 函数式组件如何 inject 呢

**Comment by nanjingboy** [comment]
@hlsky1988 inject 不支持函数组件
