### ISSUE TITLE
iphone手机自带输入法输入联想词无法触发input框的onInput/onChange事件

### ISSUE THREAD

**Issue by 2474370906** [NervJS/taro#4677]
**问题描述**
![1571901777(1)](https://user-images.githubusercontent.com/32259472/67462552-61430e80-f672-11e9-9af4-5cbfca76d1ee.jpg)

红色框中的文字被点击后不会触发onInput/onChange事件

**复现步骤**
iphoneX手机
h5端
input中输入任意文字，点击联想出来的词

```js
import Taro, { Component } from '@tarojs/taro'
import {View, Text, Button, Checkbox, Input } from '@tarojs/components'
class FormConfig extends Component {
  constructor(props) {
    super(props);
    this.state = {
      name: ''
    }
  }
  onInput (event) {
    this.setState({
      name: event.detail.value
    })
    console.log(event.detail.value)
    return event.detail.value
  }
  render () {
    const { name } = this.state
    return (<Input type='text' value={name} onInput={this.onInput.bind(this)} placeholder='将会获取焦点' />)
  }
}

```
**期望行为**
iphone手机自带输入法输入联想词onInput/onChange事件

**报错信息**
无

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. iOS 13]
 - Taro 版本 [e.g. v.1.3.18]
 - Node.js 版本 [e.g. v8.9.4]
 - 报错平台 [h5]

**Comment by shenghanqin** [comment]
好像还得说明一下是什么小程序？

**Comment by 2474370906** [comment]
> 好像还得说明一下是什么小程序？

h5端，不是小程序，npm run build:h5

**Comment by AzubuFrost** [comment]
IOS英文键盘的intellisense 联想词输入仍然存在同样的问题
