### ISSUE TITLE
子组件props数据更新在微信小程序中不执行

### ISSUE THREAD

**Issue by chaonsf** [NervJS/taro#4681]
export default class NearByClinic extends Component{
    constructor(props){
        super(props)
        this.state={
            hospital_map:props.hospital_map,
            visible:false,
            HPHP_ID:'',
            pointArr:[],
        }
    }
    componentDidMount(){
        
    }
    map(point){
        let cli=point.split(',');
        this.setState({
             pointArr:cli,
             visible:true
        })
    }
    closeMap(){
        this.setState({
            visible:false
        })
    }
    render(){
        return(
            <View className='at-row'>
                 <View className='at-col at-col-10 at-col__offset-1 at-col--wrap'>
                      <Text>{this.props.Text}</Text>
                      {this.state.hospital_map.map((item,index)=>(
                                            <View className="weui-cell weui-cell_access">
                                                {/* <View className='weui-cell__hd'  onClick={this.selectClinic.bind(this,item.HPHP_ID)}>
                                                      <Checkbox checked={this.state.HPHP_ID==item.HPHP_ID?true:false}></Checkbox>
                                                </View> */}
                                                 <View className="weui-cell__bd" onClick={()=>this.props.selectClinic(item.HPHP_ID)}>
                                                     <View className='HPHP_NAME'>[{item.HPPN_NAME}]{item.HPHP_NAME}</View>
                                                     <View className="HPHP_ADDR">{item.HPHP_ADDR}</View>
                                                 </View>
                                                 <View className="weui-cell__ft" onClick={this.map.bind(this,item.BAIDU_POINT)}>查看地图</View>
                                            </View>
                      ))} 
                 </View>
                 <AtDrawer show={this.state.visible} width='100%'>
                        <Map id='map' longitude={this.state.pointArr[0]} latitude={this.state.pointArr[1]}></Map>
                        <View className='at-row button'>
                            <View className='at-col at-col-10 at-col__offset-1'>
                                  <AtButton onClick={this.closeMap.bind(this)} type='primary'>关闭</AtButton>
                            </View>
                        </View>
                   </AtDrawer>
            </View>
        )
    }
}
NearByClinic.defaultProps={
     hospital_map:[]
}
给子组件一个默认值，然后就不渲染了
父组件调用子组件
 <NearByClinic Text='可使用诊所:' hospital_map={this.state.hospital_map} selectClinic={(id)=>this.selectClinic(id)}></NearByClinic>

**Comment by Chen-jj** [comment]
@chaonsf 请按 issue 模板提供一切必要信息

**Comment by Chen-jj** [comment]
@chaonsf 并且整理好代码格式
