### ISSUE TITLE
taro 使用 自定义组件无法传入函数

### ISSUE THREAD

**Issue by I-find-you11** [NervJS/taro#4682]
const extraProps = {cruiseList, allList, fn:{onConfirm(id){ console.log(id)} } }

    const dataLength = popupData ? popupData.length : 0; 
    const FilterPopupView = dataLength ? (<ElCheckBox
      data={popupData}
      onChange={this.onCheckboxChange}
      activeKey={activeKey}
      onHandleUpdate={onHandleUpdate}
      filterParams={filterParams}
    />) : bgHeight == 286 ? <cruiseList extraProps={extraProps} onConfirm={(id) => { console.log(id)} /> : <sortFilter />

不适用extraProps 也无法 传入 属性。我试过单独拿出来直接渲染也没用。

**Comment by Chen-jj** [comment]
@I-find-you11 不太明白你遇到的问题。

extraProps 用于**原生小程序组件**传递 props 给 **Taro 组件**。

而你的 cruiseList 组件小写字母开头，说明是一个原生小程序组件，就不需要用到 extraProps。

Taro 组件给原生小程序组件传参，调用时直接写在组件上即可。
