### ISSUE TITLE
mobx重复渲染两次页面组件

### ISSUE THREAD

**Issue by Java-http** [NervJS/taro#4683]
**问题描述**
使用mobx后,页面打开会重复渲染两次,我在脚手架提供的mobx模版也试了,同样会出现这个问题

**复现步骤**
![image](https://user-images.githubusercontent.com/17530621/67484371-95322a00-f69a-11e9-99d7-8b4869aac834.png)

地址: `\src\pages\index\index.jsx`
```
  componentDidMount () { 
    console.log("我被渲染了我被渲染了")
  }
```

**系统信息**

👽 Taro v1.3.21

  Taro CLI 1.3.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.14.0 
      Yarn: 1.17.3 
      npm: 6.7.0

**Comment by nanjingboy** [comment]
@Java-http 导致这个问题的原因与 https://github.com/NervJS/taro/issues/4637#issuecomment-545296567 一样，已经修好了，等发布后再更新就可以了。

**Comment by Java-http** [comment]
@nanjingboy 好的,谢谢大佬

**Comment by ben-lau** [comment]
请问下什么时候更新呢  就这个问题卡了几天了

**Comment by ben-lau** [comment]
还有两端的生命周期顺序不一致的问题

**Comment by nanjingboy** [comment]
@ben-lau 发布了
