### ISSUE TITLE
requestSubscribeMessage 只补充了类型定义，并没有添加该方法

### ISSUE THREAD

**Issue by zhaofinger** [NervJS/taro#4686]
**问题描述**
requestSubscribeMessage 只补充了类型定义，Taro并没有添加该方法，直接调用会报错。

**复现步骤**
[复现问题的步骤]
1. 使用`Taro.requestSubscribeMessage`调用报错

```js
Taro.requestSubscribeMessage({
  tmplIds: MESSAGE_IDS,
  success(res) {
    console.log(res);
  },
  fail(err) {
    console.log(err);
  },
});
```

**期望行为**
`Taro`添加`requestSubscribeMessage`方法

**报错信息**
![image](https://user-images.githubusercontent.com/31442077/67550957-5c499200-f73a-11e9-919a-f6ca4d379915.png)

**系统信息**

 - 操作系统: [e.g. macOS 10.15]
 - Taro 版本 [e.g. 1.3.21]
 - Node.js 版本 [e.g. 10.15.0]
 - 报错平台 [weapp]

**Comment by Garfield550** [comment]
参考文档来个 PR 呗

https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E6%8A%A5%E9%94%99

**Comment by zhaofinger** [comment]
> 参考文档来个 PR 呗
> 
> https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E6%8A%A5%E9%94%99

ok，提交了
