### ISSUE TITLE
插件开发：使用 Provider 提示 setStore 方法未定义 

### ISSUE THREAD

**Issue by K-walker** [NervJS/taro#4688]
**问题描述**

在插件页面中使用 Provider 提示 setStore 方法未定义

**复现步骤**

1. 通过taro init创建插件开发模板项目
2. 在插件页面使用 Provider 
3. 执行 taro build --plugin weapp 报错
4. 提示 setStore 未定义

![image](https://user-images.githubusercontent.com/10557092/67554745-8f901f00-f742-11e9-928b-3c11f1181e19.png)

```js

import Tabbar from '@/plugin/components/Tabbar';
import { store } from '@/plugin/store';
import { Navigator, View } from '@tarojs/components';
import { Provider } from '@tarojs/redux';
import Taro from '@tarojs/taro';

import style from './index.module.scss';

const DEFAULT_TABS = [
  {id:1,text:'首页',icon:'iconx5'},
  {id:2,text:'商城',icon:'iconx3'},
  {id:3,text:'我的',icon:'iconx1'},
];
export default function Home () {

  const handleTabItemClick = (index) => {
    console.log(DEFAULT_TABS[index]);
  }
  return (
    <Provider store={store}>
      <View className={style.home}>
        <View className={style.container}>
          <Navigator url="plugin-private://wxb4617adf983d7b05/pages/me/index">个人中心</Navigator>
        </View>
        <Tabbar tabs={DEFAULT_TABS} onClick={handleTabItemClick} />
      </View>
    </Provider>
  )
}
```

**期望行为**

Provider 使用不报错

**报错信息**

![image](https://user-images.githubusercontent.com/10557092/67554698-7a1af500-f742-11e9-9a8f-d8a2f50cea72.png)

**系统信息**

 - 操作系统:：macOS 10.14.4
 - Taro 版本： 1.3.21
 - Node.js 版本：  10.15.3
 - 报错平台： 微信插件

**Comment by Chen-jj** [comment]
@K-walker 复现不了，看看依赖是否装好了吧。

编译后代码：

![image](https://user-images.githubusercontent.com/11807297/68912359-ee214980-0792-11ea-8d9a-51a45be851c3.png)
