### ISSUE TITLE
如何获取ec-canvas dom

### ISSUE THREAD

**Issue by HecateDK** [NervJS/taro#469]
**问题描述**
获取到ec-canvas dom

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/19571458/44186609-f84a3780-a14c-11e8-9294-adc71dff3cc5.png)
 如何获取ec-canvas？

**期望行为**
可以引入`ReactDOM`吗？

**系统信息**

 - 操作系统: mac
 - Taro 版本:  v1.0.0-beta.8
 - Node.js 版本: v8.9.2

**Comment by luckyadam** [comment]
用 `ReactDOM ` 肯定不行咯，小程序里有自己获取 WXML 节点的方法

**Comment by luckyadam** [comment]
@HecateDK this.$scope.selectComponent ，在 Taro 里要这么用

**Comment by HecateDK** [comment]
是的，可以了
![image](https://user-images.githubusercontent.com/19571458/44199101-c6010000-a175-11e8-92dd-a92bfa806f19.png)


谢谢

**Comment by JX-Zhuang** [comment]
taro 3.0.9 函数组件用selectComponent
