### ISSUE TITLE
纯ts编写组件库时似乎不能生成.d.ts描述文件

### ISSUE THREAD

**Issue by zhaofinger** [NervJS/taro#4690]
**问题描述**
使用纯ts编写组件库，在`tsconfig`里指定`declaration`为`true`，不能生成`.d.ts`描述文件。

**复现步骤**
1. tsx编写组件库
2. 在`tsconfig.json`中配置`declaration`为`true`
3. 运行 `yarn build:component`
4. 成功打包但是未生成描述文件

**期望行为**
通过配置项生成描述文件

**报错信息**
无

**系统信息**
 - 操作系统: [e.g. macOS 10.15]
 - Taro 版本 [e.g. v1.3.21]
 - Node.js 版本 [e.g. v10.15.0]
 - 报错平台 [h5, weapp]

**补充信息**
无

**Comment by zhaofinger** [comment]
另外，我自己编写的组件库，如果不打包直接使用的话，在h5模式下回有报错，在配置里面配置了`esnextModules`也是无效的，报错如下：
![image](https://user-images.githubusercontent.com/31442077/67612401-e6decf80-f7d4-11e9-9e66-60c4ec662be1.png)

**Comment by zhaofinger** [comment]
在h5模式下，npm安装的组件库不能是纯ts编写的组件库吗？有什么配置可以开启一下的吗？

**Comment by tourze** [comment]
> 在h5模式下，npm安装的组件库不能是纯ts编写的组件库吗？有什么配置可以开启一下的吗？

同关注这个问题
