### ISSUE TITLE
[RN]建议npm run build:rn -- --watch时忽略cache

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#4695]
**问题描述**
今日为一个rn项目接入taro-router-rn，出现一些很诡异的问题，删了node_modules重装也不行。遇到的问题有：

1. https://github.com/facebook/metro/issues/242
2. https://github.com/facebook/react-native/issues/22675

最后发现应该是rn的cache问题。我们以前习惯是使用`node node_modules/react-native/local-cli/cli.js start --reset-cache`来启动metro的。taro在dev:rn最好补充这个，不在意那么一点启动时间啦。。。好过找问题找个把小时

**系统信息**

```
👽 Taro v1.3.21


  Taro CLI 1.3.21 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by Pines-Cheng** [comment]
RN  的 launchPackager 命令没有暴露出 clear cache 的接口，这一步还是得手动做：
`node ./node_modules/react-native/local-cli/cli.js start --reset-cache`
