### ISSUE TITLE
打包H5到线上显示Error: Loading chunk 6 failed.

### ISSUE THREAD

**Issue by schizobulia** [NervJS/taro#4696]
**问题描述**

本地运行正常,但打包之后显示文件加载错误

**复现步骤**

1. npm run build:h5
2. [仓库地址](https://github.com/508lab/wxprogram/tree/h5)
3. [线上地址](https://www.dongkji.com/h5)

**报错信息**

Error: Loading chunk 6 failed.

**系统信息**

👽 Taro v1.3.21
  Taro CLI 1.3.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by schizobulia** [comment]
#### 线上已恢复正常,但我并不知道是什么原因...
#### 只是过了一晚线上就恢复正常了！(我并未做任何事情)

**Comment by aizigao** [comment]
同样的问题，我的版本号为1.3.17
