### ISSUE TITLE
在 h5 上报 TypeError: _get(...).call is not a function

### ISSUE THREAD

**Issue by seekcx** [NervJS/taro#4698]
**问题描述**

编译之后在 h5 中报 TypeError: _get(...).call is not a function 错误。

**复现步骤**

1. 以 h5 模式运行
2. 打开首页

**期望行为**

正常工作

**报错信息**

```bash
TypeError: _get(...).call is not a function
    at Index.componentDidMount (index.js?7a4d:224)
    at eval (index.esm.js?eb37:1786)
    at errorCatcher (index.esm.js?eb37:1658)
    at eval (index.esm.js?eb37:1785)
    at Array.forEach (<anonymous>)
    at flushMount (index.esm.js?eb37:1781)
    at updateComponent (index.esm.js?eb37:1876)
    at Route.forceUpdate (index.esm.js?eb37:2012)
    at eval (index.esm.js?eb04:2471)
```

**系统信息**

Taro v1.3.9
Taro CLI 1.3.9 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm

**Comment by Littly** [comment]
看看源码？

**Comment by schizobulia** [comment]
1. 执行：taro update self
2. 执行：taro update project
3. 重新运行查看

**Comment by seekcx** [comment]
@Littly 稍等，我看能不能整理一个最小可复现的 demo，因为之前一直是写的小程序，今天刚刚尝试编译 h5，业务代码比较多，我也定位不到问题。

这是浏览器打开的报错图：

![image](https://user-images.githubusercontent.com/8244814/67646036-132a5580-f967-11e9-939f-1dd0d45da33f.png)

@schizobulia 尝试了一下，还是存在那个报错，而且又多了 mobx 的几个错误。

**Comment by seekcx** [comment]
@schizobulia 

```
Taro CLI 1.3.21 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
```

这个版本似乎有个问题，在页面里 `componentWillMount` 中调用 mobx 还是 undefined，会调用两次，第一次是 undefined，第二次正常

**Comment by schizobulia** [comment]
如果依然报：TypeError: _get(...).call is not a function  那直接回退版本吧.
PS：版本并不会影响React生命周期的,问题可能在于你没有一个默认初始化的值.
参考：Index.defaultProps 属性的使用

**Comment by seekcx** [comment]
@schizobulia 我翻了一下 issue，第二个应该是 #4637 一样的问题。

第一个问题还在排查中

**Comment by seekcx** [comment]
![image](https://user-images.githubusercontent.com/8244814/67653141-fdc32480-f982-11e9-9a1f-1a11d5a7bb34.png)

问题貌似出在这一行已经注释的代码上，注释上就没错了。。我想不出为什么会引起这个错误，这个方法现在也只是写在这，根本没有地方去调用，但是很奇怪，只要取消注释就报错了。返回其它值也不会报错，如果实在找不到原因，这个问题可以先关闭，我换一种写法吧。

**Comment by seekcx** [comment]
再补充一下。。貌似是 lodash 的 get 方法问题，是因为 get 方法在编译后会与系统的方法冲突吗？
