### ISSUE TITLE
h5 navigateTo使用问题

### ISSUE THREAD

**Issue by jun601011814** [NervJS/taro#470]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
h5使用Taro.navigateTo，返回的promise对象是undefined

**复现步骤**

```is
Taro.navigateTo({
   url: '/pages/home/index2/index'
 }).then(() => {
   console.log('taro')
 })
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
控制台能打印taro字符串

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/11892332/44186268-0a2adb00-a14b-11e8-9166-7bd4f2ccb8d0.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
navigateTo 不是 `Promise` 的
然后你的的版本有点低啊，可以升级到 `1.0.0-beta.10` ，开发体验更好

**Comment by jun601011814** [comment]
@luckyadam 版本刚刚更新过了,cli在更新。我说看着官网上api写着支持Promise化使用才这么用的，在小程序上我试了是ok的，是只支持小程序吗？

**Comment by luckyadam** [comment]
@jun601011814 只有异步的 api 才会需要 Promise 化

**Comment by jun601011814** [comment]
@luckyadam 明白，我给看漏了，不好意思。感谢回答，很棒。
