### ISSUE TITLE
引用本地libs没有正确copy

### ISSUE THREAD

**Issue by zzyhdu** [NervJS/taro#4701]
**问题描述**
项目中使用了本地的npm包，在项目的node_modules下可以发现完整的libs包目录，yarn run dev：weapp后，在dist下的npm中libs只有一个index.js.

**复现步骤**

在node_modules下
![image](https://user-images.githubusercontent.com/4222224/67646233-f5112500-f967-11e9-8fae-85074bc61185.png)

在npm下

![image](https://user-images.githubusercontent.com/4222224/67646250-0fe39980-f968-11e9-801f-300746bef129.png)

index.js的部分代码

![image](https://user-images.githubusercontent.com/4222224/67646255-2984e100-f968-11e9-8bb6-ba5d49b0d712.png)

项目的dependencies列表

![image](https://user-images.githubusercontent.com/4222224/67646279-4f11ea80-f968-11e9-88b5-8deac0a78528.png)

libs的package.json

```js
{
  "name": "libs",
  "version": "1.0.0",
  "private": true,
  "description": "common libs for native and web app",
  "main": "dist/index.js",
  "scripts": {
    "build": "flow && eslint --fix \"src/**\" \"tests/**\" && babel src -d dist",
    "format": "prettier --trailing-comma es5 --single-quote --write \"src/**/*.js\" \"tests/**/*.js\"",
    "test": "babel-node tests/run.js"
  },
  "author": "Jiulong Wang",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/node": "^7.5.5",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-flow": "^7.0.0",
    "@babel/runtime": "^7.5.5",
    "babel-eslint": "^10.0.2",
    "eslint": "^6.1.0",
    "eslint-plugin-flowtype": "^3.13.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jasmine": "^2.10.1",
    "fetch-mock": "^7.3.9",
    "flow-bin": "0.98.0",
    "jasmine": "^3.4.0",
    "node-fetch": "^2.6.0",
    "prettier": "^1.18.2"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "dropbox": "^4.0.30",
    "proto": "../proto",
    "taro-events": "^2.0.1"
  }
}
```

**期望行为**
copy到npm的应该是一个完整的libs包

**报错信息**

**系统信息**

![image](https://user-images.githubusercontent.com/4222224/67646341-a44dfc00-f968-11e9-8d76-346e94026a98.png)

**补充信息**
在项目下引用了两个本地npm包，一个libs，一个proto，在libs中引用了proto，libs和proto使用了yarn link，目前proto的copy是正常的

**Comment by Garfield550** [comment]
你的 libs 的 package.json 好像没有指定 files 字段，先补充一下这个字段试试？

类似 taro 这样

https://github.com/NervJS/taro/blob/master/packages/taro/package.json#L8-L14

https://docs.npmjs.com/files/package.json#files

**Comment by zzyhdu** [comment]
Omitting the field will make it default to ["*"], which means it will include all files.

不是这个哦，缺省的时候会打包所有的文件。我试了，写进去也是不可以的～

**Comment by zzyhdu** [comment]
taro这部分copy是怎么处理的，我买了过期的小册子，有点受伤

**Comment by luckyadam** [comment]
贴一下 `dist/index.js` 的源码

**Comment by zzyhdu** [comment]
`
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var _exportNames = {
  MagnetInfo: true,
  MagnetStates: true,
  MagnetTypes: true,
  POST_IT_DEFAULT_HEIGHT: true,
  POST_IT_DEFAULT_WIDTH: true,
  EventBus: true,
  Rect: true,
  Point: true,
  Matrix2D: true,
  UndoBuffer: true,
  Queue: true,
  CoordinateSystemHelper: true,
  FollowHelper: true,
  followHelper: true,
  guestManager: true,
  AsyncStates: true,
  CanvasRegion: true,
  DEFAULT_CENTER_X: true,
  DEFAULT_CENTER_Y: true,
  DEFAULT_HEIGHT: true,
  DEFAULT_WIDTH: true,
  MAX_ZOOM: true,
  Transform: true,
  ZoomApi: true,
  Log: true,
  Analytics: true,
  actions: true,
  reducers: true,
  NetDrive: true
};
Object.defineProperty(exports, "MagnetInfo", {
  enumerable: true,
  get: function get() {
    return _MagnetInfo["default"];
  }
});
Object.defineProperty(exports, "MagnetStates", {
  enumerable: true,
  get: function get() {
    return _MagnetInfo.MagnetStates;
  }
});
Object.defineProperty(exports, "MagnetTypes", {
  enumerable: true,
  get: function get() {
    return _MagnetInfo.MagnetTypes;
  }
});
Object.defineProperty(exports, "POST_IT_DEFAULT_HEIGHT", {
  enumerable: true,
  get: function get() {
    return _MagnetInfo.POST_IT_DEFAULT_HEIGHT;
  }
});
Object.defineProperty(exports, "POST_IT_DEFAULT_WIDTH", {
  enumerable: true,
  get: function get() {
    return _MagnetInfo.POST_IT_DEFAULT_WIDTH;
  }
});
Object.defineProperty(exports, "EventBus", {
  enumerable: true,
  get: function get() {
    return _EventBus["default"];
  }
});
Object.defineProperty(exports, "Rect", {
  enumerable: true,
  get: function get() {
    return _Rect["default"];
  }
});
Object.defineProperty(exports, "Point", {
  enumerable: true,
  get: function get() {
    return _Point["default"];
  }
});
Object.defineProperty(exports, "Matrix2D", {
  enumerable: true,
  get: function get() {
    return _Matrix2D["default"];
  }
});
Object.defineProperty(exports, "UndoBuffer", {
  enumerable: true,
  get: function get() {
    return _UndoBuffer["default"];
  }
});
Object.defineProperty(exports, "Queue", {
  enumerable: true,
  get: function get() {
    return _UndoBuffer.Queue;
  }
});
Object.defineProperty(exports, "CoordinateSystemHelper", {
  enumerable: true,
  get: function get() {
    return _CoordinateSystemHelper["default"];
  }
});
Object.defineProperty(exports, "FollowHelper", {
  enumerable: true,
  get: function get() {
    return _FollowHelper["default"];
  }
});
Object.defineProperty(exports, "followHelper", {
  enumerable: true,
  get: function get() {
    return _FollowHelper.followHelper;
  }
});
Object.defineProperty(exports, "guestManager", {
  enumerable: true,
  get: function get() {
    return _GuestManager.guestManager;
  }
});
Object.defineProperty(exports, "AsyncStates", {
  enumerable: true,
  get: function get() {
    return _AsyncStates["default"];
  }
});
Object.defineProperty(exports, "CanvasRegion", {
  enumerable: true,
  get: function get() {
    return _PanZoomHelper["default"];
  }
});
Object.defineProperty(exports, "DEFAULT_CENTER_X", {
  enumerable: true,
  get: function get() {
    return _PanZoomHelper.DEFAULT_CENTER_X;
  }
});
Object.defineProperty(exports, "DEFAULT_CENTER_Y", {
  enumerable: true,
  get: function get() {
    return _PanZoomHelper.DEFAULT_CENTER_Y;
  }
});
Object.defineProperty(exports, "DEFAULT_HEIGHT", {
  enumerable: true,
  get: function get() {
    return _PanZoomHelper.DEFAULT_HEIGHT;
  }
});
Object.defineProperty(exports, "DEFAULT_WIDTH", {
  enumerable: true,
  get: function get() {
    return _PanZoomHelper.DEFAULT_WIDTH;
  }
});
Object.defineProperty(exports, "MAX_ZOOM", {
  enumerable: true,
  get: function get() {
    return _PanZoomHelper.MAX_ZOOM;
  }
});
Object.defineProperty(exports, "Transform", {
  enumerable: true,
  get: function get() {
    return _Transform["default"];
  }
});
Object.defineProperty(exports, "ZoomApi", {
  enumerable: true,
  get: function get() {
    return _ZoomApi["default"];
  }
});
Object.defineProperty(exports, "Log", {
  enumerable: true,
  get: function get() {
    return _Log["default"];
  }
});
Object.defineProperty(exports, "Analytics", {
  enumerable: true,
  get: function get() {
    return _Analytics["default"];
  }
});
exports.NetDrive = exports.reducers = exports.actions = void 0;

var _MagnetInfo = _interopRequireWildcard(require("./MagnetInfo"));

var _EventBus = _interopRequireDefault(require("./EventBus"));

var _Rect = _interopRequireDefault(require("./Rect"));

var _Point = _interopRequireDefault(require("./Point"));

var _Matrix2D = _interopRequireDefault(require("./Matrix2D"));

var _UndoBuffer = _interopRequireWildcard(require("./UndoBuffer"));

var _CoordinateSystemHelper = _interopRequireDefault(require("./CoordinateSystemHelper"));

var _FollowHelper = _interopRequireWildcard(require("./FollowHelper"));

var _GuestManager = require("./GuestManager");

var _AsyncStates = _interopRequireDefault(require("./AsyncStates"));

var _PanZoomHelper = _interopRequireWildcard(require("./PanZoomHelper"));

var _Transform = _interopRequireDefault(require("./Transform"));

var _ZoomApi = _interopRequireDefault(require("./ZoomApi"));

var _Log = _interopRequireDefault(require("./Log"));

var _Analytics = _interopRequireDefault(require("./Analytics"));

var actions = _interopRequireWildcard(require("./actions"));

exports.actions = actions;

var reducers = _interopRequireWildcard(require("./reducers"));

exports.reducers = reducers;

var NetDrive = _interopRequireWildcard(require("./NetDrive"));

exports.NetDrive = NetDrive;

var _apis = require("./apis");

Object.keys(_apis).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _apis[key];
    }
  });
});

var _Avatar = require("./Avatar");

Object.keys(_Avatar).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _Avatar[key];
    }
  });
});

var _ChannelMember = require("./ChannelMember");

Object.keys(_ChannelMember).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _ChannelMember[key];
    }
  });
});

var _GuestUtils = require("./GuestUtils");

Object.keys(_GuestUtils).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _GuestUtils[key];
    }
  });
});

var _ProtoFactory = require("./ProtoFactory");

Object.keys(_ProtoFactory).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _ProtoFactory[key];
    }
  });
});

var _RTCInfo = require("./RTCInfo");

Object.keys(_RTCInfo).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _RTCInfo[key];
    }
  });
});

var _Utils = require("./Utils");

Object.keys(_Utils).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _Utils[key];
    }
  });
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {}; if (desc.get || desc.set) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } } newObj["default"] = obj; return newObj; } }

`

**Comment by zzyhdu** [comment]
![image](https://user-images.githubusercontent.com/4222224/67667410-b8b1e900-f9a8-11e9-99ac-bddf1a0d11e1.png)

**Comment by luckyadam** [comment]
把 libs 下的 .babelrc 删掉

**Comment by zzyhdu** [comment]
有了！。。。
能不能看下下面这个问题。。
![image](https://user-images.githubusercontent.com/4222224/67672842-c325b000-f9b3-11e9-826c-57a9eff4c399.png)

**Comment by zzyhdu** [comment]
proposal-class-properties这个在devDependencies里面有为啥会找不到呢？

**Comment by zzyhdu** [comment]
接上上个
![image](https://user-images.githubusercontent.com/4222224/67673129-51019b00-f9b4-11e9-8fda-d82a06a4f0a3.png)

**Comment by shaodushu** [comment]
@luckyadam  @zzyhdu 请问如何解决的。我现在遇到类似的问题。1.3.22版本dva-model-extend不能拷贝它所需依赖文件
![image](https://user-images.githubusercontent.com/26360246/68568502-b49cc580-0496-11ea-9b32-b929007134a0.png)
