### ISSUE TITLE
[Taro][微信小程序]本地数据库能力支持可行性

### ISSUE THREAD

**Issue by JimmieWong** [NervJS/taro#4702]
**背景**：项目涉及企业数据图表化，即相同的数据，需要用各种维度来展示。
**技术想法**：利用本地数据库虚拟表技术，最大化利用数据库的CRUD能力来规避冗余的代码逻辑来过滤组合数据。
**技术框架**：基于taro开发的微信小程序

我的问题是：单看微信小程序，没有看到有本地数据库相关的能力介绍。taro是否支持本地数据库扩展？技术想法是否可行？引入数据库会不会极大增加包大小，导致上架问题。 谢谢。

**Comment by Lizhooh** [comment]
这问题有点挫，微信不同意，上层框架怎么搞，用 localStorage 模拟一个。

**Comment by Chen-jj** [comment]
小程序没有开放这个功能，taro 本身是做不了的。
