### ISSUE TITLE
缺少npm包 判断的依据是什么?

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#4704]
**问题描述**

在问题列表里搜索"缺少npm包"会出现很多结果.

我觉得 cli 在这方面的设计上有三点问题:

一. 对于"缺少"的判断不够严谨, 我认为最简单的方法应该是 `require.resolve("module name")`, 这里如果返回结果, 就说明一定有这个包, 不管是 link 还是 monorepo. 之后从这个入口文件所在的目录, 向上搜索 `package.json`, 一定能找到npm包的根目录, 否则它也不会出现在 node_modules 目录下.

二. 对于包的输出位置进行严格控制, 不必关心来源地址和相对路径, 不放在 `dist/npm` 下面就一定是 BUG(记得兼容 config.js). 现在有些包会被复制到根目录下面的 `npm` 文件夹里.

三. 缺少的包也不要武断的开始安装, 因为 cli 未必能搞清项目的具体状况, 这里建议在 config 下面加一个选项, 例如 `config.weapp.npm.autoinstall`, 允许用户拒绝自动安装, cli 运行到这里选择警告并退出.

**复现步骤**

```shell
$ taro build --type weapp --watch
👽 Taro v1.3.21

开始编译项目 miniprogram
生成  工具配置  dist/project.config.json
编译  入口文件  src/app.tsx
拷贝  NPM文件   clients/mp/npm/@tarojs/async-await/npm/promise-polyfill/lib/index.js
拷贝  NPM文件   clients/mp/npm/regenerator-runtime/runtime.js
拷贝  NPM文件   clients/mp/npm/@tarojs/async-await/index.js
拷贝  NPM文件   clients/mp/npm/@tarojs/taro/dist/index.js
拷贝  NPM文件   clients/mp/npm/@tarojs/taro/index.js
拷贝  NPM文件   clients/mp/npm/@tarojs/taro-weapp/dist/index.js
拷贝  NPM文件   clients/mp/npm/@tarojs/taro-weapp/index.js
拷贝  NPM文件   clients/mp/dist/npm/yallist/iterator.js
拷贝  NPM文件   clients/mp/dist/npm/yallist/yallist.js
拷贝  NPM文件   clients/mp/npm/lru-cache/index.js
缺少npm包@tarojs/mobx-common，开始安装...
```

我已经安装了 `@tarojs/mobx`, 怎么会缺少 `@tarojs/mobx-common` 呢? 而且就算我安装了也没用.

个别 npm 输出的位置也让人一头雾水

```shell
tree -L 1 -d
.
├── config
├── dist
├── node_modules
├── npm 为什么会出现这个目录
└── src
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
小程序的编译即将改造成 webpack 编译，到时候就没有你说的这几个问题了

**Comment by cncolder** [comment]
那实在是太好了, 编译结果还能有很多优化空间.

上面提到的多出来的 npm 文件夹, 是因为引用了 npm 包下面的子目录导致的.

比如:

`import flowRight from 'lodash/flowRight'`
