### ISSUE TITLE
1.3.21 taro rn 初始化项目,启动开发环境报错 Native module cannot be null

### ISSUE THREAD

**Issue by Fantasy9527** [NervJS/taro#4705]
**问题描述**
[问题描述：taro cli 1.3.21版本初始化的模板代码,启动rn开发环境,报错 Native module cannot be null]

**复现步骤**
[复现问题的步骤]
1. taro init 初始化项目
2. 启动rn 开发环境
3. 报错: Native module cannot be null 或者 module appregistry is not registered callable module

**Comment by Fantasy9527** [comment]
1.3.14 没有该问题

**Comment by Pines-Cheng** [comment]
我看看

**Comment by Fantasy9527** [comment]
> 没能重现，你看看有没有其他的改动，依赖有 Taro 的依赖有没有升级到同样的版本。

taro 依赖没有问题,都是最新版本. 有可能是客户端pod版本的问题.但是我对比了 taro提供的壳子.
pod所有依赖的版本都对上了.但是在我们的app里还是跑不起来.依然报错 ` Native module cannot be null `

还有没有其他思路,定位这种问题?

**Comment by Pines-Cheng** [comment]
会不会是缓存导致的？https://github.com/NervJS/taro/issues/4695

`Native module cannot be null` 下面的报错栈应该可以看到报错的 native 模块，截个全面点的图看看？

**Comment by Fantasy9527** [comment]
问题已解决,1.3.4之后需要强依赖 unimodule
