### ISSUE TITLE
两个相同路径的页面栈，已经hide的页面shouldComponentUpdate返回false已经更新了

### ISSUE THREAD

**Issue by igauch** [NervJS/taro#4710]
**问题描述**
如题

**复现步骤**
[复现问题的步骤]
从页面a到页面b，页面a和b都是同一路径/pages/index，来自同一taro.Component类
采用mobx进行数据管理，到b页面后，数据更新，但不想让页面a刷新，所以使用shouldComponentUpdate进行控制，但已经hide的页面a的shouldComponentUpdate并没有执行

**期望行为**
已经hide的页面a的shouldComponentUpdate正常执行，返回false不再更新视图

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.20 => 1.3.20 
      @tarojs/mobx: 1.3.20 => 1.3.20 
      @tarojs/mobx-h5: 1.3.20 => 1.3.20 
      @tarojs/mobx-rn: 1.3.20 => 1.3.20 
      @tarojs/plugin-babel: 1.3.20 => 1.3.20 
      @tarojs/plugin-csso: 1.3.20 => 1.3.20 
      @tarojs/plugin-sass: 1.3.20 => 1.3.20 
      @tarojs/plugin-uglifyjs: 1.3.20 => 1.3.20 
      @tarojs/rn-runner: 1.3.20 => 1.3.20 
      @tarojs/router: 1.3.20 => 1.3.20 
      @tarojs/taro: 1.3.20 => 1.3.20 
      @tarojs/taro-alipay: 1.3.20 => 1.3.20 
      @tarojs/taro-h5: 1.3.20 => 1.3.20 
      @tarojs/taro-swan: 1.3.20 => 1.3.20 
      @tarojs/taro-tt: 1.3.20 => 1.3.20 
      @tarojs/taro-weapp: 1.3.20 => 1.3.20 
      @tarojs/webpack-runner: 1.3.20 => 1.3.20 
      eslint-config-taro: 1.3.20 => 1.3.20 
      eslint-plugin-taro: 1.3.20 => 1.3.20 
      nerv-devtools: ^1.4.0 => 1.5.1 
      nervjs: ^1.4.0 => 1.5.1 
      stylelint-config-taro-rn: 1.3.20 => 1.3.20 
      stylelint-taro-rn: 1.3.20 => 1.3.20

**Comment by Garfield550** [comment]
哪个平台的问题？
请补充一下复现代码可以吗？

**Comment by igauch** [comment]
代码如下，具体表现可到代码片段中查看https://developers.weixin.qq.com/s/uYJudtmr7Pcn

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { observer, inject } from '@tarojs/mobx'

import './index.scss'


@inject('counterStore')
@observer
class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }
  shouldComponentUpdate() {
    return !this.hasHide
  }

  componentDidShow () {
    this.hasHide = false
  }

  componentDidHide () {
    this.hasHide = true
  }

  increment = () => {
    const { counterStore } = this.props
    counterStore.increment()
  }

  decrement = () => {
    const { counterStore } = this.props
    counterStore.decrement()
  }

  incrementAsync = () => {
    Taro.navigateTo({
      url: '/pages/index/index'
    })
  }

  render () {
    const { counterStore: { counter } } = this.props
    return (
      <View className='index'>
        <Button onClick={this.increment}>+</Button>
        <Button onClick={this.decrement}>-</Button>
        <Button onClick={this.incrementAsync}>跳到新页面</Button>
        <Text>{counter}</Text>
      </View>
    )
  }
}

export default Index
```

**Comment by igauch** [comment]
有解决方案了吗？更新安排上没？产品中影响较大，感谢🙏 @Chen-jj

**Comment by Chen-jj** [comment]
@igauch  shouldComponentUpdate 打断点看看有没有进去

**Comment by igauch** [comment]
没有进去

**Comment by igauch** [comment]
@Chen-jj 没有进去，代码见上，可以看看，谢谢

**Comment by Chen-jj** [comment]
@igauch 我觉得如此表现是对的。你可以找个 mobx 的 React 项目测试一下，mobx 对组件的更新走的 forceUpdate，因此并不会走 shouldComponentUpdate。意思即 shouldComponentUpdate 并不能阻止 mobx 状态变化引起的组件更新。

跟踪 mobx 组件更新时，react-dom 中代码，`workInProgress.updateQueue.hasForceUpdate` 为 true，跳过 shouldComponentUpdate 直接返回。

![image](https://user-images.githubusercontent.com/11807297/68014894-b8c52800-fccb-11e9-8c96-ae8ee63f7c91.png)
