### ISSUE TITLE
插件开发：async-await 和 core-js  使用报错 

### ISSUE THREAD

**Issue by K-walker** [NervJS/taro#4717]
**问题描述**

使用 async-await 和 core-js 编译报错

**复现步骤**

下载 [演示项目](https://github.com/K-walker/corejs-error-demo.git) ，执行:

1. yarn 
2. npm run plugin

**期望行为**

正常编译通过不报错

**报错信息**

![image](https://user-images.githubusercontent.com/10557092/67755240-c2078800-fa72-11e9-9538-3c0b99ba78a2.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: macOS 10.14.4
 - Taro 版本 1.3.19
 - Node.js 版本 10.15.3
 - 报错平台 小程序插件

**Comment by huangnana520** [comment]
关闭增强编译

**Comment by K-walker** [comment]
@huangnana520 这个一直是关闭的，还是报错

**Comment by JasonYan2015** [comment]
#4025

**Comment by vdfor** [comment]
同存在这个问题

**Comment by K-walker** [comment]
> 经尝试，在引入 `import '@tarojs/async-await'` 的地方
> 
> ```js
> const { regeneratorRuntime } = global;
> ```
> 
> 可行

虽然说可以打印，但是控制台还是会报错，并且无法使用 store

**Comment by vdfor** [comment]
> > 经尝试，在引入 `import '@tarojs/async-await'` 的地方
> > ```js
> > const { regeneratorRuntime } = global;
> > ```
> > 
> > 
> > 可行
> 
> 虽然说可以打印，但是控制台还是会报错，并且无法使用 store

![批注 2019-11-12 183058](https://user-images.githubusercontent.com/9846146/68664051-a6c07080-057a-11ea-9009-ee019402af42.png)

我这样用是可以的

**Comment by K-walker** [comment]
> > > 经尝试，在引入 `import '@tarojs/async-await'` 的地方
> > > ```js
> > > const { regeneratorRuntime } = global;
> > > ```
> > > 
> > > 
> > > 可行
> > 
> > 
> > 虽然说可以打印，但是控制台还是会报错，并且无法使用 store
> 
> ![批注 2019-11-12 183058](https://user-images.githubusercontent.com/9846146/68664051-a6c07080-057a-11ea-9009-ee019402af42.png)
> 
> 我这样用是可以的

用是可以用的，就是控制台会报错，你控制台没有报错吗？你可以用我提供的[演示代码](https://github.com/K-walker/corejs-error-demo.git)，运行起来看看

**Comment by vdfor** [comment]
> > > > 经尝试，在引入 `import '@tarojs/async-await'` 的地方
> > > > ```js
> > > > const { regeneratorRuntime } = global;
> > > > ```
> > > > 
> > > > 
> > > > 可行
> > > 
> > > 
> > > 虽然说可以打印，但是控制台还是会报错，并且无法使用 store
> > 
> > 
> > ![批注 2019-11-12 183058](https://user-images.githubusercontent.com/9846146/68664051-a6c07080-057a-11ea-9009-ee019402af42.png)
> > 我这样用是可以的
> 
> 用是可以用的，就是控制台会报错，你控制台没有报错吗？你可以用我提供的[演示代码](https://github.com/K-walker/corejs-error-demo.git)，运行起来看看

我用最新版本的taro(1.3.23)创建了一个demo，修改了list下的一些代码（下图）,控制台未报错，建议你升级taro到最新版本试试
![批注 2019-11-13 003830](https://user-images.githubusercontent.com/9846146/68691109-24ea3a80-05ae-11ea-9b0f-fec3beab57e7.png)

另外，如果你是第一次运行为报错，修改代码后实时编译报错的，这个似乎与async-await无关，参见 #4811

**Comment by shenghanqin** [comment]
@K-walker 再试试看

**Comment by K-walker** [comment]
> @K-walker 再试试看

好的，我用最新版试试下先

**Comment by K-walker** [comment]
> > > > > 经尝试，在引入 `import '@tarojs/async-await'` 的地方
> > > > > ```js
> > > > > const { regeneratorRuntime } = global;
> > > > > ```
> > > > > 
> > > > > 
> > > > > 可行
> > > > 
> > > > 
> > > > 虽然说可以打印，但是控制台还是会报错，并且无法使用 store
> > > 
> > > 
> > > ![批注 2019-11-12 183058](https://user-images.githubusercontent.com/9846146/68664051-a6c07080-057a-11ea-9009-ee019402af42.png)
> > > 我这样用是可以的
> > 
> > 
> > 用是可以用的，就是控制台会报错，你控制台没有报错吗？你可以用我提供的[演示代码](https://github.com/K-walker/corejs-error-demo.git)，运行起来看看
> 
> 我用最新版本的taro(1.3.23)创建了一个demo，修改了list下的一些代码（下图）,控制台未报错，建议你升级taro到最新版本试试
> 
> ![批注 2019-11-13 082638](https://user-images.githubusercontent.com/9846146/68722076-59cab180-05ef-11ea-855b-44d7fef41cc1.png)
> 
> 另外，如果你是第一次运行未报错，修改代码后实时编译报错的，这个似乎与async-await无关，参见 #4811 

我按你的方式，确实 不会再报 generatorRuntime 这个错，但是我还有问题想问问，就是，我在plugin中新建一个 store.ts 文件，然后再 list.tsx 中引入，咋就报错呢，去掉就ok了，感觉很奇怪啊，是不是每新建的文件需要在 index.ts 中导出一下？不知道你有没有遇到过这种问题

**Comment by Chen-jj** [comment]
像我在 #4025 中说的，微信插件中不能直接访问 global 对象中的属性。

看看 @tarojs/async-await 的代码可知，我们把 regeneratorRuntime 的 polyfill 挂在 gobal 上。

babel 编译后，代码中直接访问 regeneratorRuntime，但微信插件中不能这样访问，只能 global.regeneratorRuntime 这样访问。

因此，这位老哥 @vdfor 的 hack 是可行的。因为这句会原封不打地编译出来，从 global 中读取了 regeneratorRuntime。

> 经尝试，在引入 `import '@tarojs/async-await'` 的地方
> 
> ```js
> const { regeneratorRuntime } = global;
> ```
> 
> 可行

至于为什么 @K-walker 说还报错，可以看看编译后的代码，`const { regeneratorRuntime } = global;` 是否在使用之后。

因为 babel 编译会把 function 提前，所以看看编译后的代码就懂了。

这样会有问题：

```
import '@tarojs/async-await'

const { regeneratorRuntime } = global

export async function sayHello () {
  console.log('Hello plugin!')
}

export const answer = 42
```

这样可行：

```js
import '@tarojs/async-await'

const { regeneratorRuntime } = global

export const sayHello = async function () {
  console.log('Hello plugin!')
}

export const answer = 42
```

但 hack 代码不好维护，建议写插件还是不用 async-await，直接用 Promise。

**Comment by K-walker** [comment]
@Chen-jj 多谢，多谢
