### ISSUE TITLE
[一个奇怪的现象] SwiperItem内部list map，<Image />总是多一个，其他的标签正常

### ISSUE THREAD

**Issue by ZXQ-GIGI** [NervJS/taro#472]
问题描述
SwiperItem内部list map，<Image />总是多一个，其他的标签正

复现步骤

- Image

![2471534407444_ pic_hd](https://user-images.githubusercontent.com/20365416/44197273-cba81700-a170-11e8-9105-f4ac3d04586b.jpg)

- 结果
![2481534407471_ pic](https://user-images.githubusercontent.com/20365416/44197329-e7abb880-a170-11e8-8d70-70fa3a061bba.jpg)
![2491534407489_ pic](https://user-images.githubusercontent.com/20365416/44197348-f003f380-a170-11e8-83a5-1117c61b5f25.jpg)

- Text
![2501534407526_ pic_hd](https://user-images.githubusercontent.com/20365416/44197444-2e99ae00-a171-11e8-864e-9e041c0b990b.jpg)

- 结果
![2511534407544_ pic](https://user-images.githubusercontent.com/20365416/44197524-6ef92c00-a171-11e8-8387-9d36f7c150a8.jpg)
![2521534407565_ pic](https://user-images.githubusercontent.com/20365416/44197532-74ef0d00-a171-11e8-9bba-b186e3093e9f.jpg)

期望行为
显示正常的Image个数

系统信息

操作系统: mac
Taro 版本: v1.0.0-beta.9
Node.js 版本: v9.4.0

**Comment by jinjinjin0731** [comment]
转成 H5 端出现的吗

**Comment by jinjinjin0731** [comment]
好的 明白了~

**Comment by zacksleo** [comment]
```
        <Swiper className="swiper" indicatorDots current={0} displayMultipleItems={1}>
          {/*{expressionList}*/}
          {
            [[1, 2, 3], [4, 5], [6, 7], [8, 9, 10]].map((e, index) => {
              return (<SwiperItem key={`item${index}`}>
                {
                  e.map((ee, eIndex) => {
                    return (
                      <Image key={`image'eIndex}`} src="https://im2-test.zhongan.io/image/file/8ba0e3d4-4b00-4809-8146-82d50f6631f6" style="width:40px;height:40px"></Image>
                    )
                  })
                }
              </SwiperItem>
              );
            })
          }
        </Swiper>
```
好像是 key={`image'eIndex}`}  这块出了问题，如果不使用模板字符串的话就正常

**Comment by ZXQ-GIGI** [comment]
- 嗯，确实是key的问题，但是如果是字符串拼接`key={'image'+eIndex}`:

```js
<Swiper className="swiper" indicatorDots current={0} displayMultipleItems={1}>
  {/*{expressionList}*/}
  {
    [[1, 2, 3], [4, 5], [6, 7], [8, 9, 10]].map((e, index) => {
      return (<SwiperItem key={`item${index}`}>
        {
          e.map((ee, eIndex) => {
            return (
              <Image key={'image' + eIndex} src="https://im2-test.zhongan.io/image/file/8ba0e3d4-4b00-4809-8146-82d50f6631f6" style="width:40px;height:40px"></Image>
            )
          })
        }
      </SwiperItem>
      );
    })
  }
</Swiper>
```

会报这个错误：
![2571534476696_ pic_hd](https://user-images.githubusercontent.com/20365416/44246513-2002d380-a211-11e8-930e-e66958ce35f9.jpg)

- 如果将将字符串拼接放在外面，还是会多一个，将模板字符串放在外面，也还是会多一个

```js
<Swiper className="swiper" indicatorDots current={0} displayMultipleItems={1}>
  {/*{expressionList}*/}
  {
    [[1, 2, 3], [4, 5], [6, 7], [8, 9, 10]].map((e, index) => {
      return (<SwiperItem key={`item${index}`}>
        {
          e.map((ee, eIndex) => {
            const key = 'image' + eIndex;
            return (
              <Image key={key} src="https://im2-test.zhongan.io/image/file/8ba0e3d4-4b00-4809-8146-82d50f6631f6" style="width:40px;height:40px"></Image>
            )
          })
        }
      </SwiperItem>
      );
    })
  }
</Swiper>
```

但是好像也不完全是这个原因，如果换成`<Text />`，用的也是模板字符串，就不会有问题
