### ISSUE TITLE
【RN】不支持hook？

### ISSUE THREAD

**Issue by everfire130** [NervJS/taro#4720]
**问题描述**
RN端使用不了hook（useState,useDispatch等）

**复现步骤**
[复现问题的步骤]

1. 使用hook构建组件

2.使用并rn运行

```js

```

**期望行为**
在RN端使用hook

**报错信息**
![image](https://user-images.githubusercontent.com/11308837/67820346-d17ae580-faf3-11e9-95e2-1cd6f1d74709.png)
[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.3.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.22 => 1.3.22
      @tarojs/components: 1.3.22 => 1.3.22
      @tarojs/components-rn: 1.3.22 => 1.3.22
      @tarojs/plugin-babel: 1.3.22 => 1.3.22
      @tarojs/plugin-csso: 1.3.22 => 1.3.22
      @tarojs/plugin-sass: 1.3.22 => 1.3.22
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22
      @tarojs/redux: 1.3.22 => 1.3.22
      @tarojs/redux-h5: 1.3.22 => 1.3.22
      @tarojs/router: 1.3.22 => 1.3.22
      @tarojs/taro: 1.3.22 => 1.3.22
      @tarojs/taro-alipay: 1.3.22 => 1.3.22
      @tarojs/taro-h5: 1.3.22 => 1.3.22
      @tarojs/taro-qq: 1.3.22 => 1.3.22
      @tarojs/taro-quickapp: 1.3.22 => 1.3.22
      @tarojs/taro-redux-rn: 1.3.22 => 1.3.22
      @tarojs/taro-rn: 1.3.22 => 1.3.22
      @tarojs/taro-router-rn: 1.3.22 => 1.3.22
      @tarojs/taro-swan: 1.3.22 => 1.3.22
      @tarojs/taro-tt: 1.3.22 => 1.3.22
      @tarojs/taro-weapp: 1.3.22 => 1.3.22
      @tarojs/webpack-runner: 1.3.22 => 1.3.22
      eslint-config-taro: 1.3.22 => 1.3.22
      eslint-plugin-taro: 1.3.22 => 1.3.22
      nerv-devtools: ^1.5.1 => 1.5.1
      nervjs: ^1.5.1 => 1.5.1
      react: 16.3.1 => 16.3.1
      react-native: 0.55.4 => 0.55.4
      stylelint-config-taro-rn: 1.3.22 => 1.3.22
      stylelint-taro-rn: 1.3.22 => 1.3.22

 - 报错平台 [rn]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zoujunda** [comment]
React Native 0.59.x 以上的版本才支持React Hooks，Taro 默认使用的React Native 0.55.4

**Comment by everfire130** [comment]
@zoujunda 文档没有说明所产生的疑惑。各端没有对齐功能，比较难受

**Comment by zoujunda** [comment]
> @zoujunda 文档没有说明所产生的疑惑。各端没有对齐功能，比较难受

确实，文档基本只针对微信小程序描述全了，除了微信小程序其他端也没啥商业项目，RN甚至demo都没有，试试水先，慢慢填坑吧。
