### ISSUE TITLE
Swiper设置自动切换，重新修改SwiperItem数量，current没有重置，导致新的SwiperItem没有显示

### ISSUE THREAD

**Issue by HuiHenry** [NervJS/taro#4723]
初始化的时候SwiperItem有3个，然后修改SwiperItem数量，修改成1个，current没有重置，修改后的内容没有显示。

**Comment by Garfield550** [comment]
Swiper 组件是 `@tarojs/components` 提供的，已经为你转移到 Taro 来了。

**Comment by luckyadam** [comment]
贴下代码怎么修改的，在微信小程序里，swiper 用的是原生组件

**Comment by BurnhamZhang** [comment]
+1 微信报错说current大于swiperitem的length，只好改成受控组件
