### ISSUE TITLE
新版本手百v11.15.5.10 redux 更新state后，组件第一次会重新渲染，第二次更新不重新渲染

### ISSUE THREAD

**Issue by tangxiaolang101** [NervJS/taro#4725]
重复事件重复state数据更新，第一次组件会重新渲染，第二次以后就不再更新了

**Comment by Pines-Cheng** [comment]
麻烦问题详细一点，说清楚环境和端，最好提供能浮现的代码或 Demo。

**Comment by tangxiaolang101** [comment]
问题信息补充：
1. 使用的taro版本：1.2.13
2. 手百端版本：v11.15.5.10
3. 问题场景：
通过 redux 管理了一个conter的状态，点击按钮，conter 的值由10开始减1，没点击一次，减1一次，减1的动作会通过action同步修改store中的状态，来重新渲染页面（conter在页面上有展示）
4. 现象：
第一次操作，conter在页面上重新渲染了，然后第二次在执行点击操作，就不会触发重新渲染了。

以上是问题详情~~有需要补充的，请回复联系~

**Comment by tangxiaolang101** [comment]
> 麻烦问题详细一点，说清楚环境和端，最好提供能浮现的代码或 Demo。

下方comment已补充

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。
