### ISSUE TITLE
无法打包微信小程序sitemap.json

### ISSUE THREAD

**Issue by GyueGuo** [NervJS/taro#4730]
src文件夹下的sitemap.json并不会被打包到dist文件夹。
这样导致小程序开发工具报错，无法运行。

复现：
src/app.jsx中config字段添加
`
"sitemapLocation": "sitemap.json"
`

src目录下添加sitemap.json文件，内容：
`
{
  "desc": "关于本文件的更多信息，请参考文档 https://developers.weixin.qq.com/miniprogram/dev/framework/sitemap.html",
  "rules": [{
  "action": "allow",
  "page": "*"
  }]
}
`

**Comment by Daisy1213** [comment]
试一下不要再config里加这个字段，反而会被打进dist

**Comment by Daisy1213** [comment]
![image](https://user-images.githubusercontent.com/18098766/67916234-06f50100-fbd0-11e9-8c0f-6f964e0ec5f0.png)

 copy: {
    patterns: [
      {from: 'sitemap.json', to: '/dist/weapp/sitemap.json'}
    ],
    options: {
    }
  },

**Comment by Issacpeng** [comment]
@GyueGuo @Daisy1213  这个问题 我以前提过，官方已修复了：https://github.com/NervJS/taro/issues/4534

**Comment by GyueGuo** [comment]
> #4534

就是你提的这个问题，我之前在issues里没搜到。这个sitemap还需要自行配置？
我目前的版本是v1.3.22，这个版本还是无法自动移动sitemap。

**Comment by Daisy1213** [comment]
@Issacpeng 有修复吗，我用的最新的版本也遇到了同样的问题，https://github.com/NervJS/taro/issues/3357 工作人员有给出解决方案就是用copy呀

**Comment by Daisy1213** [comment]
@Issacpeng 我看跟你这个issue不太一样，@GyueGuo 不是taro打包微信时吗，场景不一样吧

**Comment by GyueGuo** [comment]
> @Issacpeng 我看跟你这个issue不太一样，@GyueGuo 不是taro打包微信时吗，场景不一样吧

嗯是不一样，感觉好像差不多。我是taro编译微信，你是微信转taro。我试过taro convert，但是无奈转换出来代码错误态度，render里的内容都对不上。我现在在尝试重构，进度也十分缓慢。

**Comment by Chen-jj** [comment]
@GyueGuo 

@Daisy1213 说的是正解，配置下 copy 吧。
