### ISSUE TITLE
关于网络请求和长度单位问题

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#4735]
您好，我们尝试将React-Native项目改造成Taro项目
想问下
1.原有的fetch/ajax一定要改成Taro.request吗？
2.长度单位能否使用数字如width: 1; 而不是使用Px单位呢？
3.我们希望转化成本低一些

求助，谢谢

**Comment by Pines-Cheng** [comment]
1. 针对原有的 fetch/ajax 请求，React Native 提供了和 web 标准一致的 Fetch API，小程序没有暴露出 XMLHttpRequest/Fetch 等API。
2. 长度单位 px 在 RN 里面会自动转化为数字

**Comment by penghuwan** [comment]
> 1. 针对原有的 fetch/ajax 请求，React Native 提供了和 web 标准一致的 Fetch API，小程序没有暴露出 XMLHttpRequest/Fetch 等API。
> 2. 长度单位 px 在 RN 里面会自动转化为数字

不好意思，我想您可能误会我的意思了，说直白点我的问题是这样的

1. 在Taro项目中能否不给长度加 px单位？
2. 在Taro项目中能否直接使用fetch API ？而不使用Taro.request
>
求解答

**Comment by Pines-Cheng** [comment]
直接用 fetch API RN 支持，小程序不支持。

不给长度加 px单位无法实现跨端啊，你改造成 Taro 项目却没有跨端需求？

**Comment by penghuwan** [comment]
> 直接用 fetch API RN 支持，小程序不支持。
> 
> 不给长度加 px单位无法实现跨端啊，你改造成 Taro 项目却没有跨端需求？

谢谢您的热忱答复， 请问一下，是否将来会引入**长度单位”默认值“的功能**呢？ 
>
比如就像web开发中那样，如果我不写单位(px)而直接写数字的话，那么单位默认就是px
>
是否将来会引入类似这种默认提供的功能呢？
>
最后感谢您在百忙之中的回复了，谢谢

**Comment by Pines-Cheng** [comment]
这个可以加起来很简单，可以搞。

**Comment by penghuwan** [comment]
谢谢你，我的问题已经得到了解答。
>
请问预计在哪一个版本发布呢？

**Comment by Pines-Cheng** [comment]
> 不写单位(px)而直接写数字的话，那么单位默认就是px
这样子写本身属于不规范的写法，而且 IDE 也会有警告或报错，还是不支持了。
