### ISSUE TITLE
wxplugin框架第三方组件库的样式无效

### ISSUE THREAD

**Issue by guxingke201** [NervJS/taro#4736]
**问题描述**
wxplugin框架第三方组件库的样式无效
**复现步骤**
[复现问题的步骤]
1. taro创建wxplugin脚手架
2. avatar.tsx加入taro-ui组件
3. avatar.scss加入样式
4. 运行taro build --plugin weapp
5. 运行taro build --type weapp
6. 用微信工具打开预览页面发现样式没生效
7.如果把avatar.scss的样式放到app.scss里可以生效

```tsx
import Taro, { Component } from '@tarojs/taro'
import { AtAvatar, AtButton } from 'taro-ui'
import { View } from '@tarojs/components'
import './avatar.scss'

export default class Avatar extends Component {
  render() {
    return (
      <View>
        <View className="testclass">aaa</View>
        <AtAvatar
          circle
          image='http://storage.360buyimg.com/taro-static/static/images/logo.png'></AtAvatar>
        <AtButton type='primary'>primary</AtButton>
        <AtButton type='primary'>primary</AtButton>
        <AtButton type='primary'>primary</AtButton>
      </View>
    )
  }
}

```
```scss
@import '~taro-ui/dist/style/variables/default.scss';
@import '~taro-ui/dist/style/mixins/index.scss';
@import '~taro-ui/dist/style/components/button.scss';
@import '~taro-ui/dist/style/components/avatar.scss';
```
**期望行为**
avatar.scss加入第三方组件样式可以生效，且没有异常信息
**报错信息**
异常信息应该和样式无效无关，但还是希望能处理下
![image](https://user-images.githubusercontent.com/8326941/67918253-808fed80-fbd6-11e9-872e-ee3d0a5b2613.png)

**系统信息**
👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 9.8.0 - H:\node\nodejs\node.EXE
      npm: 5.6.0 - H:\node\nodejs\npm.CMD

**补充信息**
看过编译后的wxss存在样式，但是没生效，有可能是微信插件语法的bug

**Comment by Chen-jj** [comment]
@guxingke201 报错是 appid 没填好，仔细看看插件部分的文档吧。

**Comment by Chen-jj** [comment]
#4117 

> 你写的是“插件页面”，taro-ui 组件都配置了 addGlobalClass，所以 taro-ui 组件的样式可以从页面 wxss 获取。但如果写的是“插件组件”，则会没有样式，正如我一开始向你确定是否有样式。因此如果你需要写“插件组件”，则只能直接拿 taro-ui 组件源码了。

**Comment by guxingke201** [comment]
样式丢了如果是小程序的问题，那还可以选整包引入样式，不至于拿源码了
