### ISSUE TITLE
H5应用卸载后再调render无效

### ISSUE THREAD

**Issue by ishanyang** [NervJS/taro#4737]
**问题描述**
有个微前端需求要多次 mount(Taro.render),unmouted(Taro.unmountComponentAtNode)

**复现步骤**
[例子github代码仓库](https://github.com/ishanyang/taro-exmaple-mount-unmount)

1. npm install
2. npm run dev:h5
3. 调式工具多次调用 unmounted、mount，mount 无效

[src/app.js](https://github.com/ishanyang/taro-exmaple-mount-unmount/blob/master/src/app.jsx)
```js
export const mount = async () => {
  console.log("mount");
  Taro.render(<App />, document.getElementById("app"));
};

export async function unmount() {
  console.log("unmount");
  Taro.unmountComponentAtNode(document.getElementById("app"));
}

window.mount = mount;
window.unmount = unmount;
```
**期望行为**
希望可以多次调用 unmount, mount

**Comment by luckyadam** [comment]
额，不支持这样，换种实现方式吧
