### ISSUE TITLE
封装第三方组件，打包成微信小程序后路径错误

### ISSUE THREAD

**Issue by GyueGuo** [NervJS/taro#4738]
问题描述：
引用封装成npm包的taro组件，再被编译成小程序代码后，json文件中usingComponents字段内的组件路径不正确，但是taro-ui没问题。
复现步骤 [复现问题的步骤]

1、创建一个包native-logindialog-wx：
```javascript
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class NativeLoginDialog extends Taro.Component {
  render() {
    return (
      <View>123321</View>
    )
  }
}
```

页面js中(render代码就不写了)
```javascript
import NativeLoginDialog from 'native-logindialog-wx';
import { AtButton } from 'taro-ui';
```

编译后的json文件
```json
{
  "usingComponents": {
    "at-button": "../../npm/taro-ui/dist/weapp/components/button/index",
    "native-login-dialog": "native-logindialog-wx"
  }
}
```

报错信息:
>Component is not found in path "pages/index/native-logindialog-wx" (using by "pages/index/welcome")
Error: Component is not found in path "pages/index/native-logindialog-wx" (using by "pages/index/welcome")

系统信息

操作系统:  macOS High Sierra 10.13.6
Taro 版本：  v1.3.22
Node.js 版本： 8.15.0
报错平台 ：weapp

**Comment by GyueGuo** [comment]
taro内所有需要封装成包的组件都得经过taro编译
[文档地址](https://nervjs.github.io/taro/docs/ui-lib.html)

**Comment by zpzxgcr** [comment]
楼主最后如何解决的
