### ISSUE TITLE
hook写的页面会在小程序启动时全部执行一遍

### ISSUE THREAD

**Issue by saviourdog** [NervJS/taro#4740]
hook写的页面会在小程序启动时全部执行一遍

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
