### ISSUE TITLE
将Taro ScrollView组件的enableBackToTop属性设为true，在RN端、钉钉小程序都无效

### ISSUE THREAD

**Issue by zyfly** [NervJS/taro#4741]
**问题描述**
将Taro ScrollView组件的enableBackToTop属性设为true，在RN端、钉钉小程序都无效。

```
    <ScrollView
        className='u-news-list'
        enableBackToTop
        scrollY
        onScrollToLower={this.onScrollToLower.bind(this, showDatas)}
    >...</ScrollView>
```

**期望行为**
竖向时，iOS 点击顶部状态栏、安卓双击标题栏时，滚动条返回顶部

**系统信息**
 - 操作系统: [MacOS 10.15]
 - Taro 版本 [v1.3.21]
 - Node.js 版本 [v11.13.0]
 - 报错平台 [钉钉小程序、RN端]

**Comment by Pines-Cheng** [comment]
Swiper 组件没有看到 `enableBackToTop` 这个属性啊。
