### ISSUE TITLE
[Feature Request]多个taro项目共享page代码的想法

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#4742]
**问题描述**
我们现在使用lerna来管理项目代码，其中包含了多个taro项目。

目前助手类的方法，我们独立为独立的package，然后能正常使用和编译了。但是在项目中，我们有不少重复页面（有些定制项目，copy一份然后小修改下就交付的了），如关于我们、登录注册等等。请问这种情形有没有可能将重复页面抽为独立的package来实现共用？

我的想法如下，例如对于小程序里面，我们将重复的页面抽出为独立的package，命名为`@tarojs/user-module`，结构大概如：

```
taro-user/
----index.js
----pages/
--------login/
------------index.js
------------index.scss
--------register/
------------index.js
------------index.scss
--------about-us/
------------index.js
------------index.scss
```

然后在我们的项目的`app.js`的`config.pages` 使用如：

```
  config = {
    pages: [
      'pages/index/index', // 常规的页面引入
      'pages/index/preview',
      'npm://@tarojs/user-module/pages/login/index|pages/login/index',
      'npm://@tarojs/user-module/pages/register/index|pages/login/index',
      'npm://@tarojs/user-module/pages/about-us/index|pages/about-us/index',
    ],
    window: {
      'backgroundTextStyle': 'light',
      'backgroundColor': '#f3f3f3',
      'navigationBarBackgroundColor': '#fff',
      'navigationBarTitleText': '首页',
      'navigationBarTextStyle': 'black',
    },
  };
```

以`npm://包名/路径名|最终page路径`的格式来引入npm包中的页面。

对于这种方式引入的page，可加一些约束，如不能使用相对路径，只能直接引用npm包或使用别名，就能降低编译带来的bug数量。

----

我觉得还有一种可能，就是taro官方完善下taro-cli的插件能力，让应用开发者能在cli的各个声明周期自己做一些编译的工作，也能解决类似我们的这种问题。

https://github.com/NervJS/taro/issues/1325

**系统信息**
```
👽 Taro v1.3.22


  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 2.4.2
```

**Comment by shenghanqin** [comment]
我也觉得这个功能挺重要的，因为假设有一个tarojs老项目，此时要新开发一个新的tarojs项目，但里面的页面功能、登录注册模块其实是一致的，但只是有部分细节不那么完全一致，如何共享这些基础架构和组件，确实挺值得探究的。

以下是我写的tarojs的草稿分析。

* 架构功能
      - [ ] 状态管理-redux 实现，全局状态（登录态、特殊开关等）
      - [ ] 页面状态-加载中、加载失败提示（网络、请求）
      - [ ] 网络状态监听，与接口请求的联动
      - [ ] 登录对接（微信登录等）
  * Components 常用组件
      - [ ] 页面组件 
      - [ ] 页面状态 
    * 弹窗组件
    * 音频组件
    * 视频组件
      * 组件设计
      * 与音频的冲突解决？
    * 富文本组件
      - [ ] FormidBtn组件-微信小程序 
  * Utils 工具类方法
      - [ ] API请求 
        - [ ] mock代理
        - [ ] request与网络状态联动
        - [ ] 通用错误码、以及页面error状态显示
      - [ ] 小程序10页锁 
    * canvas画图
      - [ ] 文件上传 
      * 选择图片
      * 图片上传
      * 文件上传？

**Comment by shenghanqin** [comment]
看到一篇很不错的文章，可以参考。
【第1764期】小程序工程化探索：大规模场景下的问题和解决方案
https://mp.weixin.qq.com/s/O-J2mbxIWKG5dUXP0IBAcw

**Comment by georgezouq** [comment]
同样使用 lerna 遇到这个问题，有计划支持吗？

**Comment by luna-zhao-8** [comment]
[https://github.com/NervJS/taro/issues/6411](url)

**Comment by luna-zhao-8** [comment]
#6411

**Comment by lkangd** [comment]
> 同样使用 lerna 遇到这个问题，有计划支持吗？

你好，请问你是怎么解决这个问题的呢？可以简单地提供一点思路吗？🙏

**Comment by foosaa** [comment]
请问解决了吗

**Comment by tourze** [comment]
> 请问解决了吗

我放弃了这种方案。但是讲道理3.x中，我提到的大部分问题应该都可以支持了。

**Comment by songxiaoliang** [comment]
@tourze 嗨，准备打算使用这种方式去做，3.x的版本已经可以支持了吗

**Comment by songxiaoliang** [comment]
@tourze @foosaa @lkangd 解决了吗各位大佬，怎么做呀
