### ISSUE TITLE
样式文件不会自动生成，例如：需要点开less文件后，才会触发生成

### ISSUE THREAD

**Issue by HecateDK** [NervJS/taro#475]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1. npm run build:weapp
2. index.wxss为空
3. 打开对应的index.less
4. 保存，触发生成样式文件

![image](https://user-images.githubusercontent.com/19571458/44201163-26467080-a17b-11e8-9a10-bc71ac7b9665.png)
![image](https://user-images.githubusercontent.com/19571458/44201204-4aa24d00-a17b-11e8-8395-ad8096594cc7.png)

**期望行为**
自动编译生成对应的wxss文件

**系统信息**

 - 操作系统: masos 
 - Taro 版本: 1.0.0-beta.8
 - Node.js 版本: 8.9.2

**Comment by luckyadam** [comment]
这里有一个 babel 的 warning，可以通过这个 `weapp.compile.exclude` 配置，来排除不需要再编译的文件
https://nervjs.github.io/taro/config-detail.html#weapp

**Comment by HecateDK** [comment]
@luckyadam  谢谢 试了一下 配置后没有这个warning。谢谢

不过这个less没有自动编译的问题是因为什么？

**Comment by BryantZhou** [comment]
@HecateDK 我遇到过同样的问题 最后定位到是js没import这个less文件导致的...

**Comment by HecateDK** [comment]
@BryantZhou  好的 谢谢 确实是这个问题
