### ISSUE TITLE
Radio组件在h5下不能点击选中

### ISSUE THREAD

**Issue by xspacer** [NervJS/taro#4750]
**问题描述**
[问题描述：Radio组件在h5下不能点击选中

**复现步骤**
[复现问题的步骤]
1. npm run dev:h5

```js
import Taro, { Component, Config } from '@tarojs/taro'
import {View, Radio, RadioGroup} from '@tarojs/components'
import './index.scss'

export default class Index extends Component {
  config: Config = {
    navigationBarTitleText: '首页'
  }

  render () {
    return (
      <View className='page'>
        <RadioGroup>
          <Radio value='选中' checked>选中</Radio>
          <Radio value='未选中'>未选中</Radio>
        </RadioGroup>
      </View>
    )
  }
}

```

**期望行为**
Radio组件在h5下可以点击选中

**系统信息**
  Taro CLI 1.3.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

**Comment by Java-http** [comment]
我也遇到了这个问题

**Comment by ZakaryCode** [comment]
> **问题描述**
> [问题描述：Radio组件在h5下不能点击选中
> 
> **复现步骤**
> [复现问题的步骤]
> 
> 1. npm run dev:h5
> 
> ```js
> import Taro, { Component, Config } from '@tarojs/taro'
> import {View, Radio, RadioGroup} from '@tarojs/components'
> import './index.scss'
> 
> export default class Index extends Component {
>   config: Config = {
>     navigationBarTitleText: '首页'
>   }
> 
>   render () {
>     return (
>       <View className='page'>
>         <RadioGroup>
>           <Radio value='选中' checked>选中</Radio>
>           <Radio value='未选中'>未选中</Radio>
>         </RadioGroup>
>       </View>
>     )
>   }
> }
> ```
> 
> **期望行为**
> Radio组件在h5下可以点击选中
> 
> **系统信息**
> Taro CLI 1.3.22 environment info:
> System:
> OS: Windows 10
> Binaries:
> Node: 10.14.1 - D:\Program Files\nodejs\node.EXE
> Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
> npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

该组件在H5上使用，需要传入onChange prop手动控制

**Comment by DULANGHAI** [comment]
这个在2.x哪个版本可以拉到，我看2.1.5上还是没有
@luckyadam
