### ISSUE TITLE
多端组件的方案里，能否提供单独的支付宝小程序和RN的实现方式呢？

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#4751]
我们项目计划从现有的RN项目改造成taro项目，所以我们格外关注原有的RN应用的体验
但问题在于，我阅读文档的时候发现，没有单独的针对支付宝小程序和RN应用的js文件格式。

或者换句话说： 根据taro现有的方式，支付宝小程序的js和我们原本的RN的js格式混合到一起了
<img width="775" alt="89A33CB33AC0054FB8AF2DD3E437568E" src="https://user-images.githubusercontent.com/23090498/68096017-023e8e80-fee9-11e9-98de-de9325c2dd76.png">

这让我们感到有点棘手，请问您能提供建议和帮助吗？

**Comment by Pines-Cheng** [comment]
支付宝小程序 和 RN 端也是支持的，文档没有列出来而已，我完善一下。

**Comment by penghuwan** [comment]
太感谢了！
