### ISSUE TITLE
taro 组件useLayoutEffect 没有执行

### ISSUE THREAD

**Issue by gaogao2017** [NervJS/taro#4754]
**问题描述**
[问题描述：taro 组件useLayoutEffect 没有执行]

**报错信息**

没有任何报错，在微信小程序运行时，没有执行useLayoutEffect 中语句

**系统信息**
![image](https://user-images.githubusercontent.com/26714881/68098818-e099d300-fef9-11e9-93e0-488641d392e5.png)

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
