### ISSUE TITLE
qq开发错误

### ISSUE THREAD

**Issue by 154305** [NervJS/taro#4755]
VM20:206 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property **'__core-js_shared__'** of undefined 
 TypeError: Cannot read property **'__core-js_shared__'** of undefined
    at http://127.0.0.1:62437/appservice/npm/babel-runtime/npm/core-js/library/modules/_shared.js:6:19
    at require (http://127.0.0.1:62437/appservice/__dev__/QLogic.js:1:829451)
    at http://127.0.0.1:62437/appservice/__dev__/QLogic.js:1:829060
    at http://127.0.0.1:62437/appservice/npm/babel-runtime/npm/core-js/library/modules/_shared-key.js:3:14
    at require (http://127.0.0.1:62437/appservice/__dev__/QLogic.js:1:829451)
    at http://127.0.0.1:62437/appservice/__dev__/QLogic.js:1:829060
    at http://127.0.0.1:62437/appservice/npm/babel-runtime/npm/core-js/library/modules/_object-gpo.js:6:16
    at require (http://127.0.0.1:62437/appservice/__dev__/QLogic.js:1:829451)
    at http://127.0.0.1:62437/appservice/__dev__/QLogic.js:1:829060
    at http://127.0.0.1:62437/appservice/npm/babel-runtime/npm/core-js/library/modules/es6.object.get-prototype-of.js:5:23

**Comment by luckyadam** [comment]
能否提供一个可以复现问题的 demo
