### ISSUE TITLE
定义一个自定义render函数方法 return tsx时，函数多次调用时会出现问题

### ISSUE THREAD

**Issue by Gengar-666** [NervJS/taro#4756]
** 复现代码 **
```js

//  定义
public RenderTest(index, text) {
    return <View onClick={() => console.log(index, text)}>{text}</View>;
}

// 使用
render() {
  return (<View>
         {this.RenderTest(1, "111")}

        {this.RenderTest(2, "222")}

        {this.RenderTest(3, "333")}
</View>)
}

```

**期望行为**
每个渲染方法的参数应该互不干扰

**报错信息**

不管点击哪个都会打印最后一次传入的参数， 上述例子会打印 3, "333"
dom 渲染没问题，只是事件受影响

**系统信息**

 - 操作系统: [e.g. MacOS]
 - Taro 版本 [e.g. v1.3.14]
 - Node.js 版本 [e.g. v11.12.0]
 - 报错平台 [weapp]

**补充信息**
感觉闭包可以解决，但是好像不支持

**Comment by 13078417792** [comment]
2020-4-17，也出现了这个问题，请问有解决方案吗
