### ISSUE TITLE
字节跳动真机调试报错：regeneratorRuntime is not defined;

### ISSUE THREAD

**Issue by 1138663994** [NervJS/taro#4758]
**问题描述**
字节跳动真机调试报错：regeneratorRuntime is not defined;

**复现步骤**
[复现问题的步骤]
taro run dev:tt。再真机上调试报错 如下

![image](https://user-images.githubusercontent.com/22468141/68117243-bff06e00-ff37-11e9-8a8d-93e2e6cbe213.png)

app.jsx中也引入了 import '@tarojs/async-await'  代码

尝试再编译后的代码中也是能查看到global中是有regeneratorRuntime属性的（如下图），但是直接打印regeneratorRuntime就报上图错误, 也无法再组件中正常使用regeneratorRuntime。

![image](https://user-images.githubusercontent.com/22468141/68117481-60df2900-ff38-11e9-87f4-ca079906a60f.png)

**期望行为**
能正常再字节跳动小程序上运行

**报错信息**

[TMA][ERROR][RUNTIME] jsEngineScriptError
regeneratorRuntime is not defined;onAppRoute
ReferenceError: regeneratorRuntime is not defined
....

**系统信息**
 Taro CLI 1.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.16.2 - D:\Program Files (x86)\nodejs\node.EXE
      Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - D:\Program Files (x86)\nodejs\npm.CMD。

 - 操作系统: [  Windows 10，华为p10plus]
 - Taro 版本 [ v1.3.19 ]
 - Node.js 版本 [v10+ ]
 - 报错平台 [tt]

**Comment by Chen-jj** [comment]
same issue #4382
