### ISSUE TITLE
不能import第三方库

### ISSUE THREAD

**Issue by mushan0x0** [NervJS/taro#476]
**问题描述**
import第三方库会得到undefined

**复现步骤**
[复现问题的步骤]
1.  安装一个dayjs  
```js
yarn add -s dayjs
```
2. import dayjs
```js
import dayjs from 'dayjs'
```
3. 打印dayjs
```js
console.log(dayjs)
// 控制台输出 undefined
```

**期望行为**
正常使用import

**报错信息**

如果直接使用的话报错：

VM7355:1 thirdScriptError
dayjs_min_js_1.default is not a function;at App lifeCycleMethod onLaunch function
TypeError: dayjs_min_js_1.default is not a function
    at _App.componentDidMount (http://127.0.0.1:53714/appservice/app.js:35:47)
    at t.onLaunch (http://127.0.0.1:53714/appservice/npm/@tarojs/taro-weapp/dist/index.js:2609:13)
    at t (http://127.0.0.1:53714/appservice/__dev__/WAService.js:18:25054)
    at new t (http://127.0.0.1:53714/appservice/__dev__/WAService.js:18:26437)
    at Function.<anonymous> (http://127.0.0.1:53714/appservice/__dev__/WAService.js:18:26622)
    at http://127.0.0.1:53714/appservice/__dev__/WAService.js:18:9835
    at http://127.0.0.1:53714/appservice/app.js:55:1
    at require (http://127.0.0.1:53714/appservice/__dev__/WAService.js:19:20075)
    at http://127.0.0.1:53714/appservice/appservice?t=1534412768581:1027:9

**系统信息**

 - 操作系统: [macOS]
 - Taro 版本 [1.0.0-beta.10 typescript模版]
 - Node.js 版本 [v10.6.0]

**补充信息**

```js
const dayjs = require('dayjs')
```
这样是可以的

**Comment by yuche** [comment]
```
import * as dayjs from 'dayjs'
```

这样可以吗

**Comment by HecateDK** [comment]
我用的moment
```js
import moment from 'moment';
```

这样是可以的
![image](https://user-images.githubusercontent.com/19571458/44201966-395a4000-a17d-11e8-8800-46b305412996.png)

**Comment by yuche** [comment]
`import moment from 'moment';`

在 TypeScript 实际上会被编译成 `const moment = require('moment').default;`，你可以通过调整 `tsconfig` 的 `allowSyntheticDefaultImports ` 来调整默认 import 的值。

ref：
https://github.com/Microsoft/TypeScript/issues/5565

**Comment by kankungyip** [comment]
我发现有些第三方库可以正确import，有些不行。

**Comment by mushan0x0** [comment]
@yuche 改了allowSyntheticDefaultImports不行，import * as 这样可以，就这么用吧

**Comment by zacksleo** [comment]
如果 `import * as moment from 'moment';`不能正常使用，
根据 https://momentjs.com/docs/#/use-it/typescript/， 在 `tsconfig.json` 添加 `"allowSyntheticDefaultImports": true`, 然后使用 `import moment from 'moment';`， 可以正常使用
