### ISSUE TITLE
能否支持小程序对应的方法catchtap捕获事件。

### ISSUE THREAD

**Issue by carlSunLiang** [NervJS/taro#4762]
主要支持的场景是，做小程序自动上报无埋点，捕获事件的时候，onClick 捕获不到，在最外层，onClick对应的是bind + 事件名。 没法捕获冒泡

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/event.html#docsNav

**Comment by monyee** [comment]
人家提问的是捕获 不是冒泡

**Comment by lilingling3** [comment]
请问解决了吗

**Comment by iusn** [comment]
请问 解决了吗？ 怎么实现无埋点统计？
