### ISSUE TITLE
h5 Taro.getApp() return undefined

### ISSUE THREAD

**Issue by Phlen** [NervJS/taro#4763]
**问题描述**
1.3.22版本 H5模式下，在组件render方法或生命周期调用Taro.getApp()返回均为undefined
1.3.12版本正常

小程序未知

**复现步骤**
[复现问题的步骤]
```js
componentDidMount () {
  console.log(Taro.getApp())
}
```

**期望行为**
正常返回App实例

**报错信息**
undefined
**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统:  macOS 10.14.5
 - Taro 版本 1.3.22
 - Node.js 版本10.15
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by ItxiaoDz** [comment]
1.3.29也存在这个问题
