### ISSUE TITLE
taro 1.3.22版本 rn 不支持装饰器,编译出错

### ISSUE THREAD

**Issue by Fantasy9527** [NervJS/taro#4764]
**问题描述**
taro 1.3.22版本 rn 不支持装饰器,编译出错
官方的mobx例子也不能正常编译

**Comment by Pines-Cheng** [comment]
RN 默认的 Babel 配置[metro-react-native-babel-preset](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js)不包含 `@babel/plugin-proposal-decorators`，Taro RN 端暂时不支持自定义 Babel 配置，后续改造之后可以自行添加或修改 Babel 配置了。

**Comment by Fantasy9527** [comment]
@Pines-Cheng  为什么旧版本是支持装饰器的

**Comment by Pines-Cheng** [comment]
这样子吗，我看看。

**Comment by Fantasy9527** [comment]
@Pines-Cheng  
无法重现么?
你用的低版本是多少? 
我用1.3.18编译有装饰器的是没有问题的

**Comment by Pines-Cheng** [comment]
已 fix
