### ISSUE TITLE
[weapp] render props 编译不过

### ISSUE THREAD

**Issue by LeiHanChenZhou** [NervJS/taro#4765]
**问题描述**

按照[官方关于 render props 使用介绍](https://nervjs.github.io/taro/docs/render-props.html)
使用 Render Props 但是会出现编译不过的问题.
报错信息：`Error: 以 render 开头的 props 只能传入包含一个 JSX 元素的 JSX 表达式。`

**复现步骤**
1. 在组件内自定义 `renderTabPanel` 方法
2. 向子组件 `Tabs` 的 `renderPanel` 属性传入
3. 保存，随后编译报错

```js
export default class Base extends Component {
 // ... 省略一些函数

  // 其他 render 函数
  renderTabPanel = data => {
    return <View>{JSON.stringify(data)}</View>
  }

  render(): any {
    const { className, style } = this.props
    const cls = classNames('container', className)
    const { tabsData } = this.state
    return (
      <View className={cls} style={style}>
        <NavBar title="日期设置" />
        <Tabs
          data={tabsData}
          renderPanel={this.renderTabPanel}
        />
      </View>
    )
  }
}
```

**期望行为**
编译通过

**报错信息**
`Error: 以 render 开头的 props 只能传入包含一个 JSX 元素的 JSX 表达式。`
<img width="719" alt="image" src="https://user-images.githubusercontent.com/19839331/68193029-4b780680-ffed-11e9-9b3e-4b293dc250d9.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
👽 Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.22 => 1.3.22 
      @tarojs/components: 1.3.22 => 1.3.22 
      @tarojs/plugin-babel: 1.3.22 => 1.3.22 
      @tarojs/plugin-csso: 1.3.22 => 1.3.22 
      @tarojs/plugin-sass: 1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22 
      @tarojs/router: 1.3.22 => 1.3.22 
      @tarojs/taro: 1.3.22 => 1.3.22 
      @tarojs/taro-alipay: 1.3.22 => 1.3.22 
      @tarojs/taro-h5: 1.3.22 => 1.3.22 
      @tarojs/taro-qq: 1.3.22 => 1.3.22 
      @tarojs/taro-quickapp: 1.3.22 => 1.3.22 
      @tarojs/taro-swan: 1.3.22 => 1.3.22 
      @tarojs/taro-tt: 1.3.22 => 1.3.22 
      @tarojs/taro-weapp: 1.3.22 => 1.3.22 
      @tarojs/webpack-runner: 1.3.22 => 1.3.22 
      eslint-config-taro: 1.3.22 => 1.3.22 
      eslint-plugin-taro: 1.3.22 => 1.3.22 
      nerv-devtools: ^1.5.2 => 1.5.3 
      nervjs: ^1.5.2 => 1.5.2 
      stylelint-config-taro-rn: 1.3.22 => 1.3.22 
      stylelint-taro-rn: 1.3.22 => 1.3.22 

 - 报错平台 [weapp]

**补充信息**
貌似检查 `render` 开头的 `props` 时，只判断了他是不是占位符(类似于: `this.props.renderXXX`).

**Comment by Chen-jj** [comment]
@LeiHanChenZhou ESLint 说得很清楚了，**以 render 开头命名的 props 只能传入单个 JSX 元素或箭头函数**。不支持传变量。
