### ISSUE TITLE
[weapp] 循环使用 Render Props 出现运行时报错

### ISSUE THREAD

**Issue by LeiHanChenZhou** [NervJS/taro#4766]
**问题描述**
在微信小程序中，循环使用 `Render Props`  报错
**复现步骤**
[复现问题的步骤]
1. 在 `Base.tsx` 和 `Tabs.tsx` 中分别编写一下内容后保存
2. 运行时报错 `thirdScriptError`

```js
// Base.tsx
...
render () {
 return (
  <View>
    <Tabs
      data={tabsData}
      renderPanel={data => <View>{JSON.stringify(data)}</View>}
    />
  </View>)
}
...

// Tabs.tsx
 ...
 render(): any {
    const { className, style, data } = this.props
    const cls = classNames('container', className)
    const { current } = this.state
    const titles = _.map(data, ({ title }) => ({ title }))
    return (
      <AtTabs
        tabList={titles}
        current={current}
        onClick={this.handleTabsClick}
        className={cls}
        style={style}
      >
        {/*<AtTabsPane current={current} index={0} key={`tabs_${0}`}>*/}
        {/*  {this.props.renderPanel({xx: 'hahah'})}*/}
        {/*</AtTabsPane>*/}
        {data.map((item, index) => (
          <AtTabsPane current={current} index={index} key={`tabs_${index}`}>
            <View>{this.props.renderPanel(item.panelData)}</View>
          </AtTabsPane>
        ))}
      </AtTabs>
    )
  }

```

**期望行为**
不报错，并且正确渲染多个组件

**报错信息**
![image](https://user-images.githubusercontent.com/19839331/68196481-b3c9e680-fff3-11e9-8274-8c608672df26.png)

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
👽 Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.22 => 1.3.22 
      @tarojs/components: 1.3.22 => 1.3.22 
      @tarojs/plugin-babel: 1.3.22 => 1.3.22 
      @tarojs/plugin-csso: 1.3.22 => 1.3.22 
      @tarojs/plugin-sass: 1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22 
      @tarojs/router: 1.3.22 => 1.3.22 
      @tarojs/taro: 1.3.22 => 1.3.22 
      @tarojs/taro-alipay: 1.3.22 => 1.3.22 
      @tarojs/taro-h5: 1.3.22 => 1.3.22 
      @tarojs/taro-qq: 1.3.22 => 1.3.22 
      @tarojs/taro-quickapp: 1.3.22 => 1.3.22 
      @tarojs/taro-swan: 1.3.22 => 1.3.22 
      @tarojs/taro-tt: 1.3.22 => 1.3.22 
      @tarojs/taro-weapp: 1.3.22 => 1.3.22 
      @tarojs/webpack-runner: 1.3.22 => 1.3.22 
      eslint-config-taro: 1.3.22 => 1.3.22 
      eslint-plugin-taro: 1.3.22 => 1.3.22 
      nerv-devtools: ^1.5.2 => 1.5.3 
      nervjs: ^1.5.2 => 1.5.2 
      stylelint-config-taro-rn: 1.3.22 => 1.3.22 
      stylelint-taro-rn: 1.3.22 => 1.3.22 

 - 报错平台 [weapp]

**补充信息**
[可选]
只渲染一个组件时，render props 可以正确执行，代码如下所示

```typescript
// Tabs.tsx
  render(): any {
    const { className, style, data } = this.props
    const cls = classNames('container', className)
    const { current } = this.state
    const titles = _.map(data, ({ title }) => ({ title }))
    return (
      <AtTabs
        tabList={titles}
        current={current}
        onClick={this.handleTabsClick}
        className={cls}
        style={style}
      >
        <AtTabsPane current={current} index={0} key={`tabs_${0}`}>
          {this.props.renderPanel({xx: 'hahah'})}
        </AtTabsPane>
        {/*{data.map((item, index) => (*/}
        {/*  <AtTabsPane current={current} index={index} key={`tabs_${index}`}>*/}
        {/*    <View>{this.props.renderPanel(item.panelData)}</View>*/}
        {/*  </AtTabsPane>*/}
        {/*))}*/}
      </AtTabs>
    )

```

**Comment by Chen-jj** [comment]
@LeiHanChenZhou 暂不支持，用 HOC 吧
