### ISSUE TITLE
map嵌套循环 第二个map如果加上判断条件然后返回一个jsx 会出现 if条件里面的语句不执行，console.log(mIndex,'2')将不会执行，请帮忙解决

### ISSUE THREAD

**Issue by Brandzhao01** [NervJS/taro#4767]
return floor.list.map((item, index) => {
			return (
				<View>
					<View className='floor_title'>
						<Image className='item_title_img' src={item.head.title_img} />
					</View>
					<View className='floor_img'>
						<Image className='item_title_image' src={item.head.image} />
					</View>
					<View className='floor_item'>
						{ 
							item.mid.map((mItems,mIndex)=>{
								console.log(mItems.title);
								if(mItems.title=='连衣裙'){
									console.log(mIndex,'2');
									return (<View><Text>123</Text></View>)
								}
							})
						} 
					</View>
					<ScrollView scrollX={true}>
						<View className='floor_scroll'>
							{
								item.bottom.map((bItem)=>{
									return(
										<View className='floor_scroll_item'>
											<Image className='floor_scroll_img' src={bItem.image} />>
										</View>
									)
								})
							}
						</View>
					</ScrollView>
				</View>
			)

		});

**Comment by Chen-jj** [comment]
@Brandzhao01 参照 Issue 模版整理好代码格式，提供一切必要信息。

这样的提问让别人如何帮你：
![image](https://user-images.githubusercontent.com/11807297/68273928-b0d9ff00-00a2-11ea-8def-7641a62f14e2.png)
