### ISSUE TITLE
[alipay]组件setState的问题

### ISSUE THREAD

**Issue by Nickhao485** [NervJS/taro#4769]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.声明一个父组件和子组件并传递一个值
2.先setState子组件的值，10ms之后setState父组件的值
3.子组件无法获得父组件传递的值

子组件:
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Test extends Component {
  render() {
    const { detail } = this.props
    return (
      <View className="container">{detail.data}</View>
    )
  }
}
```

父组件：
```js

import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Test from '@/components/TestComp/test'

export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  }

  state = {
    foo: true,
    detail: [],
  }

  componentDidMount() {
    this.setState({
       detail: [{Name: 'test'}]
    })
    setTimeout(() => {
      this.setState({
        foo: false
      })
    }, 1)
  }

  

  render() {
    const { foo, detail } = this.state
    return (
       <View>
         <View>{foo}</View>
         {
           detail.map(arr => (
            <Test detail={arr}></Test>
           ))
         }
       </View>
    )
  }
}
```

**期望行为**
子组件获得detail的值

**报错信息**

无报错

**系统信息**
System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.0.1 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.22 => 1.3.22 
      @tarojs/components: 1.3.22 => 1.3.22 
      @tarojs/plugin-babel: 1.3.22 => 1.3.22 
      @tarojs/plugin-csso: 1.3.22 => 1.3.22 
      @tarojs/plugin-less: 1.3.22 => 1.3.22 
      @tarojs/plugin-sass: 1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22 
      @tarojs/redux: 1.3.22 => 1.3.22 
      @tarojs/redux-h5: 1.3.22 => 1.3.22 
      @tarojs/router: 1.3.22 => 1.3.22 
      @tarojs/taro: 1.3.22 => 1.3.22 
      @tarojs/taro-alipay: 1.3.22 => 1.3.22 
      @tarojs/taro-h5: 1.3.22 => 1.3.22 
      @tarojs/taro-swan: 1.3.22 => 1.3.22 
      @tarojs/taro-tt: 1.3.22 => 1.3.22 
      @tarojs/taro-weapp: 1.3.22 => 1.3.22 
      @tarojs/webpack-runner: 1.3.22 => 1.3.22 
      eslint-config-taro: 1.3.22 => 1.3.22 
      eslint-plugin-taro: 1.3.22 => 1.3.22 
      nerv-devtools: ^1.5.3 => 1.5.3 
      nervjs: ^1.5.3 => 1.5.3 
      react: ^16.8.6 => 16.9.0 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
父组件先setState或者将两个setState合并都不会出现问题
追踪源码的时候发现mountComponent根本没传值，头疼

**Comment by Chen-jj** [comment]
@Nickhao485 复现不了，自组件能正常显示 props.detail.data

![image](https://user-images.githubusercontent.com/11807297/68279873-55fad480-00af-11ea-9f98-b3a7ab4fde16.png)

**Comment by Nickhao485** [comment]
> @Nickhao485 复现不了，自组件能正常显示 props.detail.data
> 
> ![image](https://user-images.githubusercontent.com/11807297/68279873-55fad480-00af-11ea-9f98-b3a7ab4fde16.png)

不好意思，我修改了一下例子，麻烦您再试试

**Comment by Nickhao485** [comment]
@Chen-jj
