### ISSUE TITLE
路由传递数据失败

### ISSUE THREAD

**Issue by yerphon** [NervJS/taro#4771]
**问题描述**
[问题描述：Taro.navigateTo无法在success函数内通过res.eventChannel.emit传送数据到即将打开的页面]

**复现步骤**
[复现问题的步骤]
1. A页面 ：
Taro.navigateTo({
                    url: '/pages/B/B',
                    success: function(res){
                        // 通过eventChannel向被打开页面传送数据
                        res.eventChannel.emit('acceptDataFromOpenerPage', { data: 'test' })
                    }
                })
2. B页面
    componentWillMount() {
        console.log(this.$scope.getOpenerEventChannel()) //此处是undefined
        // })
    }

**期望行为**
[能在B页面收到A页面传送到的数据]

**报错信息**
![image](https://user-images.githubusercontent.com/7892904/68265702-cdb50900-0087-11ea-99cb-e783576db256.png)

![image](https://user-images.githubusercontent.com/7892904/68265474-1c15d800-0087-11ea-8ac5-c760203c5df9.png)

**系统信息**
系统信息
操作系统: Windows 10
Taro 版本 V1.3.11
Node.js 版本10.16.1
报错平台 Weapp

**Comment by Chen-jj** [comment]
@yerphon `componentDidMount` 中再调用，因为 Taro 中小程序页面用的 Component 构造器构造，`componentWillMount` 在 `attached` 生命周期中触发，其实页面还没 `onLoad`，所以没有这个方法。

另外也不建议这样传参，你可以选择正常地 url 传参，也可以使用 Taro 提供的两种预加载手段，会比这样传参更好。
