### ISSUE TITLE
useRef  使用中.current 始终是null

### ISSUE THREAD

**Issue by lfxwoaini** [NervJS/taro#4772]
这个是文档中的示例，代码如下

function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` 指向已挂载到 DOM 上的文本输入元素
    inputEl.current.focus();
  };
  return (
    <View>
      <Input ref={inputEl} type="text" />
      <Button onClick={onButtonClick}>Focus the input</Button>
    </View>
  );
}

报错结果如下
TypeError: Cannot read property 'focus' of null
    at TextInputWithFocusButton.anonymousFunc0

**Comment by Chen-jj** [comment]
same issue #4466
