### ISSUE TITLE
windows下 weapp.compile.exclude 配置排除npm包文件问题

### ISSUE THREAD

**Issue by deng-yc** [NervJS/taro#4775]
**问题描述**

在windows下配置 `weapp.compile.exclude` 忽略npm包中的文件问题

**复现步骤**
[复现问题的步骤]
1. 配置 weapp.compile.exclude  
```js
weapp:{
    compile: {
        exclude: ['node_modules/tim-wx-sdk/tim-wx.js'],
    },
}
```
**期望行为**
期望该文件不被处理直接复制

**系统信息**
 - 操作系统: Windows 10]
 - Taro 版本 1.3.22
 - Node.js 版本 10.
 - 报错平台 [weapp]

**补充信息**
cli中 `resolve_npm_files.js` 
![image](https://user-images.githubusercontent.com/12589538/68271385-44a7cd00-009b-11ea-9c7c-b1ecd8a8b442.png)

这里的`filePath.indexOf(item)`,没有处理windows下分隔符

**Comment by luckyadam** [comment]
tim-wx-sdk
直接配置这个包名吧

**Comment by deng-yc** [comment]
前面有正则表达式筛选了,直接写`tim-wx-sdk`是没有作用的  必须是 `node_module/tim-wx-sdk`
