### ISSUE TITLE
无法与 constate/unstated-next 集成使用

### ISSUE THREAD

**Issue by zicjin** [NervJS/taro#4778]
**问题描述**
无法与 [constate](https://github.com/diegohaz/constate)/[unstated-next](https://github.com/jamiebuilds/unstated-next) 集成使用

**复现步骤**
```js
import Taro, { Component, Config, useState } from '@tarojs/taro'
import { Text, Button } from '@tarojs/components'
import constate from "constate"

function useCounter() {
  const [count, setCount] = useState(0)
  const increment = () => setCount(prevCount => prevCount + 1);
  return { count, increment };
}

const [CounterProvider, useCounterContext] = constate(useCounter);

function IButton() {
  const { increment } = useCounterContext();
  return <Button onClick={increment}>+</Button>;
}

function Count() {
  const { count } = useCounterContext();
  return <Text>{count}</Text>;
}

export default class Product extends Component {
  config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }
  componentDidMount () { }
  componentWillUnmount () { }
  componentDidShow () { }
  componentDidHide () { }

  render () {
    return (
      <CounterProvider>
        <Count />
        <IButton />
      </CounterProvider>
    )
  }
}
```

**期望行为**
以上为constate的Basic example. 无法执行. unstated-next 效果一样.

**报错信息**
![image](https://user-images.githubusercontent.com/199482/68298010-51481780-00d3-11ea-8d81-2b6d6491744d.png)

update:发现编译时报错,src/demo/constate.tsx 是唯一使用了constate的组件.
![image](https://user-images.githubusercontent.com/199482/68526323-8fcd1480-0315-11ea-8852-01ccdedfed32.png)

**系统信息**
 - 操作系统: Windows 10
 - Taro 版本 v1.3.22
 - Node.js 版本 13.0.1
 - 报错平台 [weapp]

**Comment by atzcl** [comment]
使用 taro3 是可以的

**Comment by yuche** [comment]
楼上说得对，unstated 其实是一个高阶组件，Taro 1/2 没有办法支持

**Comment by Chen-jj** [comment]
Taro 3 支持，之后会推出对应的默认模板
