### ISSUE TITLE
render props 传递组件时，组件中调用的函数不执行

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#4781]
**问题描述**

render props 传递组件时，组件中调用的函数不执行

![image](https://user-images.githubusercontent.com/7480381/68365760-80f72e00-016c-11ea-9cfd-6c1678b9d3ce.png)

```js
 <Cell  renderExtra={<Text className={styles['list-amount']}>+{util.price(data.amount)}</Text>} />
```

**期望行为**

正常渲染

**实际效果**

![image](https://user-images.githubusercontent.com/7480381/68366034-3aee9a00-016d-11ea-8df7-0f99665c33c3.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v1.3.22]
 - Node.js 版本 [10.16.0]
 - 报错平台 [weapp]

**Comment by youngluo** [comment]
@luckyadam

**Comment by Chen-jj** [comment]
@youngluo 复现不了，提供一下完整可复现项目
