### ISSUE TITLE
jest执行测试用例报错

### ISSUE THREAD

**Issue by sankincn** [NervJS/taro#4782]
**问题描述**
build成h5组件后，执行jest测试时报错引入的文件无法被jest识别。
```
Jest encountered an unexpected token
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
```

**复现步骤**
build成h5后的代码
```js
import Nerv from "nervjs";
import Taro from "@tarojs/taro-h5";
import { View } from '@tarojs/components';
import './index.less';
class Column extends Taro.Component {
  render() {
    const { title } = this.props;
    return <View className="column">
        <View className="column__title">{title}</View>
        <View className="column__content">
          {this.props.children}
        </View>
      </View>;
  }
}
Column.defaultProps = {
  title: ''
};
export default Column;
```
babel配置和taro-ui保持一致
```js
const apis = require('@tarojs/taro-h5/dist/taroApis');

module.exports = {
  presets: [
    [
      '@babel/env',
      {
        spec: true,
        useBuiltIns: false,
      },
    ],
  ],
  plugins: [
    '@babel/plugin-proposal-class-properties',
    [
      '@babel/plugin-transform-react-jsx',
      {
        pragma: 'Nerv.createElement',
      },
    ],
    ['@babel/plugin-proposal-object-rest-spread'],
    ['babel-plugin-transform-taroapi', {
      apis,
      packageName: '@tarojs/taro-h5',
    }],
  ],
};
```

jest配置和taro-ui保持一致
```js
module.exports = {
  verbose: true,
  moduleFileExtensions: ['js', 'jsx', 'json'],
  rootDir: __dirname,
  testMatch: ['<rootDir>/src/**/*.test.js','<rootDir>/src/**/test.js'],
  transform: {
    '^.+\\.js?$': 'babel-jest',
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
  moduleNameMapper: {
    react: 'nervjs',
    'react-addons-test-utils': 'nerv-test-utils',
    'react-dom': 'nervjs',
    'weui': '<rootDir>/__mock__/style-mock.js',
    '\\.(css|less|sass|scss)$': '<rootDir>/__mock__/style-mock.js',
    '^@\/(.*)$': '<rootDir>/src/$1',
  },
};
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**
<img width="1962" alt="WeChatba81802101d8a6a69b1a6b4f33ff0c2f" src="https://user-images.githubusercontent.com/20496148/68369314-f36c0c00-0174-11ea-8e95-196f1e8dfda0.png">

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。
Taro CLI 1.3.21 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.21 => 1.3.21 
      @tarojs/cli: 1.3.21 => 1.3.21 
      @tarojs/components: 1.3.21 => 1.3.21 
      @tarojs/plugin-babel: 1.3.21 => 1.3.21 
      @tarojs/plugin-csso: 1.3.21 => 1.3.21 
      @tarojs/plugin-less: 1.3.21 => 1.3.21 
      @tarojs/plugin-uglifyjs: 1.3.21 => 1.3.21 
      @tarojs/redux: 1.3.21 => 1.3.21 
      @tarojs/redux-h5: 1.3.21 => 1.3.21 
      @tarojs/router: 1.3.21 => 1.3.21 
      @tarojs/taro: 1.3.21 => 1.3.21 
      @tarojs/taro-h5: 1.3.21 => 1.3.21 
      @tarojs/taro-weapp: 1.3.21 => 1.3.21 
      @tarojs/webpack-runner: 1.3.21 => 1.3.21 
      nervjs: ^1.5.1 => 1.5.3

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-ui-sample
参考一下这个项目的测试写法

**Comment by xuzpeng** [comment]
@sankincn 大佬最终咋解决的？我情况和你一样
