### ISSUE TITLE
Video属性showCenterPlayBtn是否可用

### ISSUE THREAD

**Issue by Daisy1213** [NervJS/taro#4784]
求问video是否显示中间的操作按钮该属性showCenterPlayBtn是否可用，文档上并没有给出详细的描述，希望补充一下

**Comment by shenghanqin** [comment]
建议你给出文档的链接，或者给出示意图。

我这边看了[Taro的Video](http://taro-docs.jd.com/taro/docs/components/media/video.html)里面没有这个属性，在微信小程序文档中看到了"show-center-play-btn"看到了相关属性。
当然，我在Taro的源码中[index.md](https://github.com/NervJS/taro/blob/master/packages/taro-components/src/components/video/index.md)找到了该属性的使用方法，希望能帮到你。

**Comment by shenghanqin** [comment]
文档会慢慢补充的，你可以先看我给的解答。嘻嘻

**Comment by Daisy1213** [comment]
> 文档会慢慢补充的，你可以先看我给的解答。嘻嘻
![image](https://user-images.githubusercontent.com/18098766/68446780-bc4f3680-0218-11ea-82a0-a843d18fb342.png)
![image](https://user-images.githubusercontent.com/18098766/68446791-c07b5400-0218-11ea-95a9-26ebea1c16f8.png)
我使用了上面提到的属性，value为false
图一是ios的百度小程序的表现，视频播放结束完成后还是会显示中间的重播按钮
图二是android的百度小程序，使用showCenterPlayBtn属性，表现正常，
麻烦排查一下该问题，谢谢大佬~

**Comment by Garfield550** [comment]
组件都是编译到端原生组件的，所以 Taro 这边出问题的话大概率 Android 和 iOS 都会有问题，从你的截图反馈来看，大概率是百度智能小程序这边的问题，建议用原生代码写一个百度智能小程序试一下。

另外我也搜到了有人在百度小程序开发者社区里的反馈，平台也是 iOS： https://smartprogram.baidu.com/forum/topic/show/67030

也有人反馈缓冲画面和播放按钮重叠，音量按钮和播放按钮重叠等问题。

建议写一个原生小程序试验一下。

**Comment by Daisy1213** [comment]
> 组件都是编译到端原生组件的，所以 Taro 这边出问题的话大概率 Android 和 iOS 都会有问题，从你的截图反馈来看，大概率是百度智能小程序这边的问题，建议用原生代码写一个百度智能小程序试一下。
> 
> 另外我也搜到了有人在百度小程序开发者社区里的反馈，平台也是 iOS： https://smartprogram.baidu.com/forum/topic/show/67030
> 
> 也有人反馈缓冲画面和播放按钮重叠，音量按钮和播放按钮重叠等问题。
> 
> 建议写一个原生小程序试验一下。

嗯嗯，这个我也有看到，我联系下百度的人反馈一下，谢谢您~
