### ISSUE TITLE
请问Taro支持flow.js吗

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#4785]
您好，我看到Taro已经支持TypeScript了
>
但是我们项目目前用的是flow.js做类型约束
>
所以想问下**Taro支持flow.js吗?**
>
如果暂时不支持的话，会不会引入开发排期呢？

**Comment by canyara** [comment]
现在flow在非react环境几乎无法配置 我也找到非react jsx报错的解决办法

**Comment by canyara** [comment]
[https://github.com/facebook/flow/issues/4657#issuecomment-323602289](url)

找到一个方法解决jsx错误,其他就正常设置就能用了

**Comment by penghuwan** [comment]
如果Taro不能支持flow的话
>
我们就需要每次都通过 flow-remove-types 这个命令行去把原有的flow代码全部转化一遍了
>
当然这样也可以，就是多一些麻烦
>
最后再问下，Taro能够集成对flow代码的处理吗?

**Comment by SweetDonuts** [comment]
同问，习惯 js + flow 开发了

**Comment by Chen-jj** [comment]
暂时没有计划支持，如果有详细实现的思路和想法，欢迎提交 [RFC](https://github.com/NervJS/taro-rfcs)
