### ISSUE TITLE
更新到1.3.22之后，mobx下的props数据结构和以往不一致

### ISSUE THREAD

**Issue by uloveits** [NervJS/taro#4786]
**问题描述**
[问题描述：更新到1.3.22之后，在页面里面的组件也引入mobx的情况下，props的数据包含在数组里面]

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/26559166/68443744-d89aa580-020f-11ea-8070-2be9f40139f0.png)

**期望行为**
[数据不要放在数组里面 和以前保持一致]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

![Uploading image.png…]()

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by uloveits** [comment]
问题的原因 好像不是组件里也用了mobx 具体原因未知

**Comment by nanjingboy** [comment]
@uloveits 构造函数中 `super` 的调用方式改成再看看： `super(...arguments)`

**Comment by shenghanqin** [comment]
TAro的标准写法是这样的，我建议也这么写。

```js
constructor(props) {
    super(props)
    this.state = {}
  }
```

**Comment by uloveits** [comment]
改成super(...arguments)  好了

**Comment by shenghanqin** [comment]
> 改成super(...arguments) 好了

可以尝试我给的写法吗？我想验证一下。

**Comment by shenghanqin** [comment]
> 改成super(...arguments) 好了

可以尝试我给的写法吗？我想验证一下。

**Comment by Garfield550** [comment]
@shenghanqin 这种写法当然可以啊。

```ts
public constructor(props: Props) {
  super(props);
}
```

**Comment by uloveits** [comment]
> @shenghanqin 这种写法当然可以啊。
> 
> ```ts
> public constructor(props: Props) {
>   super(props);
> }
> ```



> > 改成super(...arguments) 好了
> 
> 可以尝试我给的写法吗？我想验证一下。

可以的

**Comment by shenghanqin** [comment]
> @shenghanqin 这种写法当然可以啊。
> 
> ```ts
> public constructor(props: Props) {
>   super(props);
> }
> ```

那是当然，既然React和Taro的标准写法都是如此，那就是很有道理的。你给出的是TypeScript的写法，我这大部分代码是非TS版本的。嘻嘻。
