### ISSUE TITLE
renderProps样式在微信端未正确编译

### ISSUE THREAD

**Issue by guxingke201** [NervJS/taro#4788]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
按照[renderProps官方示例](https://nervjs.github.io/taro/docs/render-props.html#docsNav)使用，样式在微信端未正确编译
**复现步骤**
[复现问题的步骤]
1. taro init 新增一个项目
2. 新增mouse.js
3. 引入mouse，renderCat的传入带样式的ReactNode
4. 使用微信打开，发现样式没生效

![image](https://user-images.githubusercontent.com/8326941/68448071-3f728b80-021d-11ea-9d47-e8b714a81d4e.png)

### mouse.js
```js
class Mouse extends Taro.Component {
  constructor(props) {
    super(props)
    this.handleMouseMove = this.handleClick.bind(this)
    this.state = { x: 0, y: 0 }
  }

  handleClick(event) {
    const { x, y } = event.detail
    this.setState({
      x,
      y
    })
  }

  render() {
    const { renderCat }= this.props
    return (
      <View style={{ height: '100%' }} onClick={this.handleClick}>
        {renderCat(this.state)}
      </View>
    )
  }
}

```
### index.jsx
```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.scss'
import Mouse from './mouse'

export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  render() {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <Mouse renderCat={() => <View style={{ color: 'blue' }}>自定义footer</View>}></Mouse>
      </View>
    )
  }
}

```
**期望行为**
style能正常生效

**报错信息**
无

**系统信息**
👽 Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 9.9.0 - H:\node\nodejs\node.EXE
      npm: 5.6.0 - H:\node\nodejs\npm.CMD

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
