### ISSUE TITLE
想请教一下,初次进入页面时候的app.js; 1.js; 2.js....这些js分别有什么, 为什么要分成1.2.3.js这样

### ISSUE THREAD

**Issue by magicbing** [NervJS/taro#4791]
想请教一下,初次进入页面时候的app.js; 1.js; 2.js....这些js分别有什么, 为什么要分成1.2.3.js这样
有什么关键词告知一下我自己搜搜看, 分包加载; 或者有链接也可以, 最好能讲解下
写了很久业务还不知道代码是什么样, 比较疑惑
补一张图
![1](https://user-images.githubusercontent.com/12853293/68467031-77df8d00-0250-11ea-9ea0-9b6c83c347b2.png)
👽 Taro v1.3.11

  Taro CLI 1.3.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - D:\app\yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by shenghanqin** [comment]
请你按照issue模板来提交问题，里面最好附上源代码、示例、截图，以及你当前的开发环境。

**Comment by luckyadam** [comment]
建议了解一下 webpack 打包机制

**Comment by magicbing** [comment]
> 建议了解一下 webpack 打包机制

查了下资料好像是webpack里的chunk, 目的是把可以比较独立的js包切开, 变成script标签, 让浏览器并发下载, 还可以缓存. 这样提高页面加载速度
