### ISSUE TITLE
更新到1.3.22之后，npm install 失败(gyp: binding.gyp not found - 2.2.1@fsevents)

### ISSUE THREAD

**Issue by jonahfang** [NervJS/taro#4795]
问题描述
[问题描述：更新到1.3.22之后，npm install 失败(gyp: binding.gyp not found - 2.2.1@fsevents)]

复现步骤
[复现问题的步骤] 新建项目 taro init testproject, 然后执行 npm install.

期望行为
[npm 成功]

报错信息
请参见下面的截图:
![image](https://user-images.githubusercontent.com/16301509/68522409-07834b00-02e6-11ea-8a9d-7da7198864e5.png)

系统信息
ProductName: Mac OS X
ProductVersion: 10.15.1
BuildVersion: 19B88
NodeVersion: v12.12.0

**Comment by Garfield550** [comment]
依赖问题，删除 node_modules 并且挂上代理软件，重新执行 yarn install 或 npm install

**Comment by jonahfang** [comment]
试过了，没有用。

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/68523504-3359fd00-02f5-11ea-9535-2ea8de8470fb.png)

**Comment by jonahfang** [comment]
@Garfield550 没看懂，这句话啥意思?

**Comment by shenghanqin** [comment]
尝试删除node_modules文件夹和package-lock.json文件，再执行npm install？

**Comment by jonahfang** [comment]
改用 npm install 此问题消失(用 cnpm v4.6.0 此问题依然存在)!
