### ISSUE TITLE
无法配置"@babel/preset-flow"

### ISSUE THREAD

**Issue by canyara** [NervJS/taro#4796]
taro-cli版本:1.3.22
build:weapp报错
` Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".`

config中的babel配置:
`babel: {
      sourceMap: true,
      presets: [
        [
          "env",
          {
            modules: false
          }
        ],
        "@babel/preset-flow"
      ],
      plugins: [
        "transform-decorators-legacy",
        "transform-class-properties",
        "transform-object-rest-spread"
      ]
    }`

taro-cli的babel版本还是老的，需要升级到7才能用，现在"@babel/preset-flow"无法使用

**Comment by luckyadam** [comment]
目前 Taro 用的 babel 6 ，你要配置 presets 或者 plugin 的话，得用 babel 6 的
