### ISSUE TITLE
如何获取tabbar的高度

### ISSUE THREAD

**Issue by pkaq** [NervJS/taro#4797]
由于需要用到 样式控制 calc(100vh - "tabbar高度") 
那么 如何获取tabbar的高度呢?

**Comment by shenghanqin** [comment]
是什么类型的项目呢？还有示意图呢？

**Comment by pkaq** [comment]
这个跟项目类型以及我的业务场景无关的吧? 问题是文档翻完也没找到

**Comment by vkcyan** [comment]
h5的是50PX,注意用大写,不会被解析成rem
不过calc 这个移动端兼容性不是太好,多测试

**Comment by pkaq** [comment]
ok
