### ISSUE TITLE
touch事件的event对象类型有问题

### ISSUE THREAD

**Issue by zhongzhong0505** [NervJS/taro#4798]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
MovableView的onTouchEnd的回调事件里面，event对象类型有误。

<img width="783" alt="企业微信截图_a91244ca-89f4-4a5a-8fd5-39e98833c5ee" src="https://user-images.githubusercontent.com/15847574/68537813-488e6480-03a5-11ea-9ca9-838511dab8f0.png">
<img width="620" alt="WX20191110-103023@2x" src="https://user-images.githubusercontent.com/15847574/68537814-4c21eb80-03a5-11ea-8da3-4f33b3db9057.png">

**复现步骤**
[复现问题的步骤]

1. 引入taro的MovableView组件
2. 监听onTouchEnd的事件
3. 查看event对象属性
```js

// 这里可以贴代码
// 点击链接查看如何插入代码：
// https://coding.net/help/doc/project/markdown.html#i-5

// ```js
// 代码放这里（前后的 "```" 有助 Mardown 整理代码格式和加入代码高亮）
handlerTouchEnd(e: ITouchEvent) {
    
  }
<View className="movable-item-container">
        <MovableArea className="movable-item-area" style={areaStyle}>
          <MovableView
            className="movable-item-view"
            direction="horizontal"
            damping={100}
            x={x}
            inertia
            outOfBounds
            onChange={this.handlerChange.bind(this)}
            onTouchStart={this.handlerTouchStart.bind(this)}
            onTouchEnd={this.handlerTouchEnd.bind(this)}>
            {this.props.children}
          </MovableView>
        </MovableArea>
        <View className="movable-item-op">{renderOp()}</View>
      </View>
// ```

// 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间。
// 代码提供不全或代码格式混乱的 issues 【有可能被忽略】，烦请各位注意。

```

**期望行为**
跟标准的事件对象属性一致

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shenghanqin** [comment]
是微信小程序还是其他平台？

**Comment by shenghanqin** [comment]
是你提及的[h5、weapp]还是什么平台？

**Comment by zhongzhong0505** [comment]
\

> 是你提及的[h5、weapp]还是什么平台？

weapp,微信模拟器里面

**Comment by shenghanqin** [comment]
那试一试微信小程序的真机的console是不是有问题呢？

比如，我的小伙伴在模拟器上写好了音频播放器，但是在微信小程序上可能还是会碰到很多其他不一样的表现，或者bug。这种触摸事件优先以真机效果为准。

**Comment by zhongzhong0505** [comment]
不用taro提供的类型是没有问题，在真机上，而且taro这个跟标准的touchevent都不一样，微信是用的标准的，这就很让人费解了

**Comment by luckyadam** [comment]
是说 taro 提供的类型和小程序不一致么，如果不一致可以提交 pr 来修改
