### ISSUE TITLE
npmrc还是让用户自己配置比较好吧

### ISSUE THREAD

**Issue by wowlusitong** [NervJS/taro#48]
关于 https://github.com/NervJS/taro/pull/17 。 
我yarn使用淘宝源会导致安装失败，只能先在本地去掉tempalte的npmrc。

以下为测试结果
- npm + 淘宝源 = 成功
- npm + npmjs源 = 成功
- yarn + yarnpkg = 成功
- yarn + 淘宝源 = 失败

----

结论: `npmrc` 这种东西还是让用户自己设置比较好吧？毕竟每个人的网络环境和使用习惯都不同。

**Comment by suwu150** [comment]
https://github.com/NervJS/taro/issues/41

**Comment by yuche** [comment]
现在情况是很多用户并不知道如何配置从不同的源安装，目前看好像从 cnpm 安装成功率最高。

**Comment by wowlusitong** [comment]
@yuche 目前看来只有yarn+淘宝源会安装失败，改为如果是yarn用户就不生成npmrc文件？毕竟大部分安装yarn的开发者都有一定的动手能力.

**Comment by yuche** [comment]
@wowlusitong 我觉得可以
