### ISSUE TITLE
使用 mobx reaction  无法响应 props 里面的数据变更

### ISSUE THREAD

**Issue by Luncher** [NervJS/taro#4800]
**问题描述**

子组件希望响应 props 中的一个 id 属性更新, 从而去获取数据。但是 props 里面的 id 变更的时候， reaction 没有响应。

**复现步骤**

*子组件写法*

```typescript

@observer
export default class AgeList extends Component<IProps> {
  componentDidMount() {
    console.log('componentDidMount')
    this.disposer = reaction(
      () => this.props.shopId,
      shopId => {
        console.log('reaction: ', shopId)
        if (shopId) {
          Taro.showLoading()
          this.getBabyAgeList()
        }
      },
      { fireImmediately: true }
    )
  }
}

```

*父组件写法：*

```typescript

@inject('shopAllStore')
@observer
export default class Age extends Component<IProps> {

  @observable.ref shopId: string = null

  @action.bound
  updateShopId(shopId: string) {
    this.shopId = shopId
  }

  componentDidMount() {
    this.updateShopId(this.$router.params.shopId)
  }

  render() {
    console.log('render age page')
    return (
      <View className="age-wrapper">
        <Text className="page-title">选择宝宝年龄</Text>
        <Text className="page-title-desc">我们将推荐您最适合宝宝的套餐</Text>
        <AgeList shopId={this.shopId} />
      </View>
    )
  }

}

```

**期望行为**

子组件能够响应 props 的变更。

**报错信息**

--

**系统信息**

Taro v1.3.12

  Taro CLI 1.3.12 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.12 => 1.3.12
      @tarojs/mobx: 1.3.12 => 1.3.12
      @tarojs/mobx-h5: 1.3.12 => 1.3.12
      @tarojs/mobx-rn: 1.3.12 => 1.3.12
      @tarojs/plugin-babel: 1.3.12 => 1.3.12
      @tarojs/plugin-csso: 1.3.12 => 1.3.12
      @tarojs/plugin-less: 1.3.12 => 1.3.12
      @tarojs/plugin-sass: ^1.3.12 => 1.3.12
      @tarojs/plugin-uglifyjs: 1.3.12 => 1.3.12
      @tarojs/rn-runner: 1.3.12 => 1.3.12
      @tarojs/router: 1.3.12 => 1.3.12
      @tarojs/taro: 1.3.12 => 1.3.12
      @tarojs/taro-alipay: 1.3.12 => 1.3.12
      @tarojs/taro-h5: 1.3.12 => 1.3.12
      @tarojs/taro-swan: 1.3.12 => 1.3.12
      @tarojs/taro-tt: 1.3.12 => 1.3.12
      @tarojs/taro-weapp: 1.3.12 => 1.3.12
      @tarojs/webpack-runner: 1.3.12 => 1.3.12
      eslint-config-taro: 1.3.12 => 1.3.12
      eslint-plugin-taro: 1.3.12 => 1.3.12
      nerv-devtools: ^1.4.0 => 1.4.3
      nervjs: ^1.4.0 => 1.4.3
      stylelint-config-taro-rn: 1.3.12 => 1.3.12
      stylelint-taro-rn: 1.3.12 => 1.3.12

**Comment by luckyadam** [comment]
升级到最新版本再试试

**Comment by nanjingboy** [comment]
@Luncher 这样改你的 render：

```js
  render() {
   const { shopId } = this;
    return (
      <View className="age-wrapper">
        <AgeList shopId={shopId} />
      </View>
    )
  }
```

原因已经在：[https://taro-docs.jd.com/taro/docs/mobx.html#observer](https://taro-docs.jd.com/taro/docs/mobx.html#observer) 说明了。

**Comment by Luncher** [comment]
> @Luncher 这样改你的 render：
> 
> ```js
>   render() {
>    const { shopId } = this;
>     return (
>       <View className="age-wrapper">
>         <AgeList shopId={shopId} />
>       </View>
>     )
>   }
> ```
> 
> 原因已经在：https://taro-docs.jd.com/taro/docs/mobx.html#observer 说明了。

tarojs 版本跟正常的 `React` + `Mobx` 的使用姿势差太多了，用起来很头疼

**Comment by shenghanqin** [comment]
我用redux来解决全局状态统一，但在单个页面中还是用的state来传递变量。
这个也可以在mobx上，其实用简单的方案可能会更容易一些。

**Comment by nanjingboy** [comment]
@Luncher 我们尽量保持与 React 一致的使用体验，但终归 Taro 不等同于 React，所以在一些地方还是建议按照 Taro 的文档处理。

**Comment by Luncher** [comment]
@nanjingboy 按照你推荐的写法，还是不起作用。子组件的 `reaction` 不会触发

```typescript

  componentDidMount() {
    this.disposer = reaction(
      () => this.props.shopId,
      shopId => {
        console.log('reaction: ', shopId)
        if (shopId) {
          Taro.showLoading()
          this.getBabyAgeList()
        }
      },
      { fireImmediately: true }
    )
  }

```

**Comment by nanjingboy** [comment]
@Luncher 我在最新版 1.3.25 中没有复现，你升级到最新版看看，如果还有问题提供一个可以复现的 demo（可能我漏掉了什么关键的细节）。
