### ISSUE TITLE
使用Redux Persist导致的Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by canyara** [NervJS/taro#4801]
使用taro的storage写的storage
实际微信小程序运行时由于stoarge还没有恢复完成 所有注册的页面（即便没有显示或者导航）都会运行，这时connect注册的store还没有初始化就会导致这个问题

**Comment by shengbowen** [comment]
我也遇到了，貌似taro 的redux  createStore只能同步执行，没办法等到异步加载完本地数据再创建store。

**Comment by shengbowen** [comment]
目前发现是因为taro的store设置是同步的，没办法异步获取数据之后再设置store，目前的解决方案是获取数据之后，dispatch一个init action来初始化整个state。至于reducer怎么更新整个state可以参考https://www.redux.org.cn/docs/recipes/reducers/BeyondCombineReducers.html
