### ISSUE TITLE
构建 ui 库的时候现在默认执行构建 RN 端的了吗？

### ISSUE THREAD

**Issue by yinLiangDream** [NervJS/taro#4803]
1.3.22版本，我发现库里面多了 ui 这个文件夹，其中构建流程为
<img width="651" alt="图片" src="https://user-images.githubusercontent.com/24502330/68575521-33016380-04a7-11ea-8e76-7ebf25373e81.png">
结果就导致了每次都会构建 RN 端的文件，未适配的一些属性会报错，可不可以不构建 RN 端的 UI
<img width="609" alt="图片" src="https://user-images.githubusercontent.com/24502330/68575671-81166700-04a7-11ea-9991-6daf1acbe517.png">

**Comment by Issacpeng** [comment]
我看最新有修改的代码，把这部分做了环境区分，但还没正式发布。

**Comment by Pines-Cheng** [comment]
@Issacpeng  是的，已 fix，还没发布，不会影响 小程序和 H5 的构建，麻烦暂时无视。
