### ISSUE TITLE
函数组件内层map无法获取外层map变量

### ISSUE THREAD

**Issue by qiaoyixuan** [NervJS/taro#4804]
Metric.js

```js
import Taro from '@tarojs/taro'
import { View, Text } from '@tarojs/components'

export default ({ data }) => {
  if (!data) return null
  if (!data.key_list || !data.key_list.length) return '暂无数据'
  const { key_list = [], conf = {} } = data
  return (
    <View>
      {
        key_list.map((key) => {
          const graphData = data[key]
          if (!graphData) return null
          const chartKeys = Object.keys(graphData).filter(k => k.startsWith('metric_group'))
          console.log(graphData)
          return (
            <View key={key}>
              {
                chartKeys.map((k, i) => {
                  const metricGroup = graphData[k]
                  return <View>Summary</View>
                })
              }
            </View>
          )
        })
      }
    </View>
  )
}
```

Index.js
```js
const data = {
  key_list: ['graph0'],
  graph0:  {
    metric_group0: {},
    metric_group1: {},
  }
}
<Metric data={data} />
```

**报错信息**
循环chartKeys时，无法获取metricGroup

![image](https://user-images.githubusercontent.com/13936160/68580811-161e5d80-04b2-11ea-893d-66bf5f7f49ca.png)
taro代码中没有对key中graphData赋值的逻辑

**系统信息**
Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.21 => 1.3.21 
      @tarojs/components: 1.3.21 => 1.3.21 
      @tarojs/plugin-babel: 1.3.21 => 1.3.21 
      @tarojs/plugin-csso: 1.3.21 => 1.3.21 
      @tarojs/plugin-less: 1.3.21 => 1.3.21 
      @tarojs/plugin-sass: ^1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.21 => 1.3.21 
      @tarojs/redux: 1.3.21 => 1.3.21 
      @tarojs/redux-h5: 1.3.21 => 1.3.21 
      @tarojs/router: 1.3.21 => 1.3.21 
      @tarojs/taro: 1.3.21 => 1.3.21 
      @tarojs/taro-alipay: 1.3.21 => 1.3.21 
      @tarojs/taro-h5: 1.3.21 => 1.3.21 
      @tarojs/taro-swan: 1.3.21 => 1.3.21 
      @tarojs/taro-tt: 1.3.21 => 1.3.21 
      @tarojs/taro-weapp: 1.3.21 => 1.3.21 
      eslint-config-taro: 1.3.21 => 1.3.21 
      eslint-plugin-taro: 1.3.21 => 1.3.21 
      nerv-devtools: ^1.4.0 => 1.5.1 
      nervjs: ^1.4.0 => 1.5.1 
      stylelint-config-taro-rn: 1.3.21 => 1.3.21 
      stylelint-taro-rn: 1.3.21 => 1.3.21

**Comment by liuxiaoxiao1** [comment]
遇到了同样的问题，希望能够解决...

**Comment by qiaoyixuan** [comment]
@yuche @shenghanqin

**Comment by qiaoyixuan** [comment]
这个问题从1.x开始，现在都2.x了还没解决。。。。

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
