### ISSUE TITLE
taro怎么配置多个环境

### ISSUE THREAD

**Issue by yufengkz** [NervJS/taro#4807]
**问题描述**
taro怎么配置多个环境？多个环境的不同变量？

**复现步骤**
无

**期望行为**
开发时存在多个环境，包括开发环境、测试环境、准生产环境、生产环境，在taro中如何配置不同的打包命令来区分多个环境？就像vue中的.env.dev .env.test  .env.uat  .env.prod等环境变量

**报错信息**
无

**系统信息**
无

**Comment by shenghanqin** [comment]
我是自己在启动命令里面加了SERVER_ENV等变量

**Comment by Qiyu8** [comment]
taro内部的处理逻辑是：加watch就是测试环境，不加watch就是生产环境

**Comment by luckyadam** [comment]
> taro内部的处理逻辑是：加watch就是测试环境，不加watch就是生产环境

+1

你也可以在 config 里新增配置文件，然后 index.js 里引用它，再配置一下 [env](https://nervjs.github.io/taro/docs/config-detail.html#env) 给它个环境变量

**Comment by yufengkz** [comment]
@luckyadam
是这样的吗？
```
// 新建uat文件
module.exports = {
  env: {
    NODE_ENV: '"uat"'
  },
  ......
}
// index.js
module.exports = function (merge) {
  console.log(process.env.NODE_ENV)
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  if (process.env.NODE_ENV === 'uat') {
    return merge({}, config, require('./uat'))
  }
  return merge({}, config, require('./prod'))
}
```
在package.json怎么配置打包命令？
比如我想添加: "uat:h5": "taro build --type h5 --watch" 这个命令如何配置呢？

**Comment by wenxiayili** [comment]
> CC @luckyadam

官方的issues感觉质量真是不高？？？一个tabbar问题 都没解决？cli环境1.3.25
config/index.js的tabbar如下：
 ` json
     pages: [
    '/pages/index/index',
    '/pages/home/home',
  ],
  tabbar: {
    color: "#626567",
    selectedColor: "#6e9eea",
    backgroundColor: "#FBFBFB",
    borderStyle: "white",
    custom: false,
    list: [{
      pagePath: "/pages/index/index",
      text: "测试",
      iconPath: "",
      selectedIconPath: ""
    },
    {
      pagePath: "/pages/home/home",
      text: "首页",
      iconPath: "",
      selectedIconPath: ""
    }]
`
我这么配置有什么问题吗？

**Comment by morelearn1990** [comment]
> **问题描述**
> taro怎么配置多个环境？多个环境的不同变量？
> 
> **复现步骤**
> 无
> 
> **期望行为**
> 开发时存在多个环境，包括开发环境、测试环境、准生产环境、生产环境，在taro中如何配置不同的打包命令来区分多个环境？就像vue中的.env.dev .env.test .env.uat .env.prod等环境变量
> 
> **报错信息**
> 无
> 
> **系统信息**
> 无

老哥，这个问题解决了么？

**Comment by yufengkz** [comment]
没有解决...

**Comment by rowthan** [comment]
taro的环境变量env是枚举值，只有development和production两种，设置为uat时，打包会报错。只能设置另外的变量值来区分了~

**Comment by sherfruit** [comment]
> 我是自己在启动命令里面加了SERVER_ENV等变量

如何在启动项目的时候添加？

**Comment by ksbaozi** [comment]
> taro的环境变量env是枚举值，只有development和production两种，设置为uat时，打包会报错。只能设置另外的变量值来区分了~

请问如何添加 我自己写了一条命令 
```
"build-test:weapp": "taro build --type weapp --server a",
```
但是在 ```process.env.server``` 中获得的还是 undefined

**Comment by PresByter2015** [comment]
请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。

**Comment by sherfruit** [comment]
> 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。

我用了cross-env 解决了

**Comment by PresByter2015** [comment]
> > 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。
> 
> 我用了cross-env 解决了

大佬是怎么写的呢？
我是这样写的
`"test": "cross-env API_ENV=test npm run build:weapp -- --watch",`
然后打印 `process.env.API_ENV`结果是development

**Comment by sherfruit** [comment]
> > > 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。
> > 
> > 
> > 我用了cross-env 解决了
> 
> 大佬是怎么写的呢？
> 我是这样写的
> `"test": "cross-env API_ENV=test npm run build:weapp -- --watch",`
> 然后打印 `process.env.API_ENV`结果是development

这样试下？
 npm run test
"test": "npm run build:test -- --watch"
"build:test": "cross-env API_ENV=test taro build --type weapp",

**Comment by PresByter2015** [comment]
> > > > 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。
> > > 
> > > 
> > > 我用了cross-env 解决了
> > 
> > 
> > 大佬是怎么写的呢？
> > 我是这样写的
> > `"test": "cross-env API_ENV=test npm run build:weapp -- --watch",`
> > 然后打印 `process.env.API_ENV`结果是development
> 
> 这样试下？
> npm run test
> "test": "npm run build:test -- --watch"
> "build:test": "cross-env API_ENV=test taro build --type weapp",

undefined

**Comment by sherfruit** [comment]
> > > > > 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。
> > > > 
> > > > 
> > > > 我用了cross-env 解决了
> > > 
> > > 
> > > 大佬是怎么写的呢？
> > > 我是这样写的
> > > `"test": "cross-env API_ENV=test npm run build:weapp -- --watch",`
> > > 然后打印 `process.env.API_ENV`结果是development
> > 
> > 
> > 这样试下？
> > npm run test
> > "test": "npm run build:test -- --watch"
> > "build:test": "cross-env API_ENV=test taro build --type weapp",
> 
> undefined

项目文件 config>dev && config>prod

![image](https://user-images.githubusercontent.com/20284294/87417462-ca085780-c602-11ea-9d7e-c789f4604e00.png)

**Comment by PresByter2015** [comment]
> > > > > > 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。
> > > > > 
> > > > > 
> > > > > 我用了cross-env 解决了
> > > > 
> > > > 
> > > > 大佬是怎么写的呢？
> > > > 我是这样写的
> > > > `"test": "cross-env API_ENV=test npm run build:weapp -- --watch",`
> > > > 然后打印 `process.env.API_ENV`结果是development
> > > 
> > > 
> > > 这样试下？
> > > npm run test
> > > "test": "npm run build:test -- --watch"
> > > "build:test": "cross-env API_ENV=test taro build --type weapp",
> > 
> > 
> > undefined
> 
> 项目文件 config>dev && config>prod
> 
> ![image](https://user-images.githubusercontent.com/20284294/87417462-ca085780-c602-11ea-9d7e-c789f4604e00.png)

图裂开了，大佬

**Comment by sherfruit** [comment]
> > > > > > > 请问 这个问题 解决了吗？我在script设置环境变量，打印出来的结果还`NODE_ENV`的结果一样。
> > > > > > 
> > > > > > 
> > > > > > 我用了cross-env 解决了
> > > > > 
> > > > > 
> > > > > 大佬是怎么写的呢？
> > > > > 我是这样写的
> > > > > `"test": "cross-env API_ENV=test npm run build:weapp -- --watch",`
> > > > > 然后打印 `process.env.API_ENV`结果是development
> > > > 
> > > > 
> > > > 这样试下？
> > > > npm run test
> > > > "test": "npm run build:test -- --watch"
> > > > "build:test": "cross-env API_ENV=test taro build --type weapp",
> > > 
> > > 
> > > undefined
> > 
> > 
> > 项目文件 config>dev && config>prod
> > ![image](https://user-images.githubusercontent.com/20284294/87417462-ca085780-c602-11ea-9d7e-c789f4604e00.png)
> 
> 图裂开了，大佬

额 你要在项目配置文件里设置才有值的 就在那两个文件里添加设置 PAGE_ENV: process.env.API_ENV?`"${process.env.API_ENV}"`:'"other"',

**Comment by PresByter2015** [comment]
> process.env.API_ENV?`"${process.env.API_ENV}"`:'"other"',

成功了，谢谢🙏啦！！！

**Comment by xblcx** [comment]
cross-env 直接就可以解决，感谢
