### ISSUE TITLE
使用echarts漏斗图报错thirdScriptError undefined;at SelectorQuery callback function undefined

### ISSUE THREAD

**Issue by goodgoodstudyY** [NervJS/taro#4808]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
在使用漏斗图时，会产生报错，但是把漏斗图改成饼状或折线图就没有问题
**复现步骤**
[复现问题的步骤]
1. 首先下载GitHub 上的 ecomfe/echarts-for-weixin 项目ec-canvas目录
2. 在页面引入目录里的echarts
以下为当前使用漏斗图页面

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

import * as echarts from '../../components/ec-canvas/echarts'

import './index.less'

function initChart(canvas, width, height) {
  const chart = echarts.init(canvas, null, {
    width: width,
    height: height
  });
  canvas.setChart(chart);

  var option = {
    calculable: true,
    series: [
      {
        name: '漏斗图',
        type: 'funnel',
        width: '40%',
        height: '45%',
        left: '5%',
        top: '50%',
        data: [{ value: 100, name: '展现' },
        { value: 80, name: '点击' },
        { value: 60, name: '访问' },
        { value: 30, name: '咨询' },
        { value: 10, name: '订单' },

        ]
      }
    ]
  };
  chart.setOption(option);
  return chart;
}

export default class xPage extends Component {
  config = {
    navigationBarTitleText: '',
    usingComponents: {
      'ec-canvas': '../../components/ec-canvas/ec-canvas'
    }
  }
  state = {
    ec: {
      onInit: initChart
    }
  }

  render () {

    return (
        <View className='container'>
          <ec-canvas canvas-id='mychart-funnel' ec={this.state.ec}></ec-canvas>
        </View>
    )
  }
}


```

**期望行为**
希望漏斗图可以展示出来

**报错信息**

thirdScriptError
undefined;at SelectorQuery callback function
undefined
console.error @ VM3304:1
errorReport @ VM3320 WAService.js:1
thirdErrorReport @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
r @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
(anonymous) @ VM3320 WAService.js:1
n @ VM3318 asdebug.js:1
(anonymous) @ VM3318 asdebug.js:1
(anonymous) @ VM3318 asdebug.js:1
_ws.onmessage @ VM3318 asdebug.js:1

**系统信息**

 - 操作系统:Windows 10
 - Taro 版本 Taro v1.3.21
 - Node.js 版本 v12.13.0
 - 报错平台 weapp

**Comment by yuche** [comment]
你用法不对，可以参考：
http://blog.poetries.top/2019/08/31/taro-echarts/

**Comment by goodgoodstudyY** [comment]
找到问题了 是因为我引入的echarts.js有问题 我在https://www.echartsjs.com/zh/builder.html 重新打包下载并替换掉了原先echarts.js 用同一套代码 漏斗图就出来啦
