### ISSUE TITLE
安装 babel-plugin-preval 后 编译时有报错

### ISSUE THREAD

**Issue by Jackie-Web** [NervJS/taro#4814]
**问题描述**
我在用babel-plugin-preval@1.6.4 这个插件， 在编译的时候会有报错 
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined

**复现步骤**

1. taro init 新的项目
2. 在config/index.js 下 plugins.babel.plugins 下添加 babel-plugin-preval 代码如下 
![image](https://user-images.githubusercontent.com/11611057/68729089-01ea7580-0604-11ea-8a31-65a6b4ce77aa.png)

3. 修改 app.js 文件 如下
![image](https://user-images.githubusercontent.com/11611057/68729144-1e86ad80-0604-11ea-960f-ef19d89f7a3b.png)

4. 编译后 就可以看到报错 

config/index.js文件修改如下 
```
plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread',
        'babel-plugin-preval',
      ]
    }
  },
```

app.js修改如下 
```
import preval from 'babel-plugin-preval/macro';

config: Config = {
    pages: preval`
      module.exports=(function() {
        if (process.env.TARO_ENV === 'weapp') {
          return [
            'pages/index/index'
          ]
        }
      })()
    `,
  }
```

**期望行为**
希望可以修复这个问题，解决多端配置的方案。

**报错信息**

![image](https://user-images.githubusercontent.com/11611057/68728958-a7e9b000-0603-11ea-8121-a148946f9898.png)

编辑结束后 会再次报出几个错误 
![image](https://user-images.githubusercontent.com/11611057/68728994-c18af780-0603-11ea-9592-4bb7ee7e04db.png)

**系统信息**

 - 操作系统: [e.g. mac os]
 - Taro 版本 [e.g. v1.3.15]   [e.g. v1.3.23]
 - Node.js 版本 [e.gv12.2.0]
 - 报错平台 [weapp] 暂时发现这个平台

**补充信息**
在群里问过，说是引用了外部的node包 但是除了 babel-plugin-preval这个包 我这边并没有引用外部的其他包。

**Comment by luckyadam** [comment]
2、不需要在 babel plugins 里面添加插件
3、不需要在 app 里写 `import preval from 'babel-plugin-preval/macro'`

**Comment by Jackie-Web** [comment]
> 2、不需要在 babel plugins 里面添加插件
> 3、不需要在 app 里写 `import preval from 'babel-plugin-preval/macro'`

好的 我试试
