### ISSUE TITLE
beta11 将自定义组件当做npm依赖

### ISSUE THREAD

**Issue by limichange** [NervJS/taro#482]
**问题描述**
从beta10升级到beta11后，运行编译程序提示缺少npm依赖

**复现步骤**
从beta10升级到beta11

**期望行为**
正确识别自定义组件

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/1947344/44242311-867cf700-a1fb-11e8-81cc-5c08c145289c.png)

**系统信息**

 - 操作系统: mac 10.13.6
 - Taro 版本 beta11
 - Node.js 版本 10.4.0

**Comment by zacksleo** [comment]
代码是怎么写的呢

**Comment by limichange** [comment]
@zacksleo 

![image](https://user-images.githubusercontent.com/1947344/44244119-e88e2a00-a204-11e8-9cb3-c10236b3d487.png)


```js
import UserInfo from './UserInfo'
```

**Comment by zacksleo** [comment]
`import UserInfo from './UserInfo/index'`呢

**Comment by limichange** [comment]
这样写能找到

**Comment by zacksleo** [comment]
Duplicate of  #429 #430

**Comment by luckyadam** [comment]
@zacksleo 这个和那两个 issue 还不太一样~ 我看下这种情况

**Comment by AlexStacker** [comment]
确实不一样，这个应该是要求写相对路径，不过要是支持指定文件夹做根目录的方式的话也挺好的，省了好多 ...点点点

**Comment by luckyadam** [comment]
@AlexStacker 是说 alias 咩

**Comment by zacksleo** [comment]
自动安装这个不是很好用啊

**Comment by luckyadam** [comment]
@zacksleo 优化一下~😅

**Comment by limichange** [comment]
不要自动安装吧，看起来是很好的功能但其实很烦人。

**Comment by zacksleo** [comment]
嗯，我觉得也是，实际体验并不好，也没有太大用处，建议最多给个 warning 就够了

**Comment by yuche** [comment]
Duplicate of #498

**Comment by yuche** [comment]
close via 5401154
