### ISSUE TITLE
Taro Input无法获取输入框的值

### ISSUE THREAD

**Issue by 490567134** [NervJS/taro#4821]
Taro Input官方API提供的onInput方法无法获取输入框的值，但是小程序自己的input绑定的bindinput事件没有问题，有哪位大佬遇到过吗？

**Comment by shenghanqin** [comment]
请给出更完整的源代码、demo、对比等。

**Comment by cunkai** [comment]
AtSearchBar 的 onChange 属性在微信开发者工具2.9.3也失效，搜索框输入不会触发onChange，改到开发者工具2.8问题消除。

**Comment by 490567134** [comment]
<Input
                        type='text'
                        placeholder='请填写新昵称'
                        value={value}
                        onInput={this.onChange.bind(this)}
                        placeholderClass={styles.input_holder}
                    />

  onChange = e => {
        console.log(e, '1')
        this.setState({
            value: 222222
        },()=>{
            console.log(this.state.value)
        })
    }
这里是相关代码，onInput开发者工具上不触发，真机上也不触发

**Comment by 490567134** [comment]
<Input
         type='text'
         placeholder='请填写新昵称'
         value={value}
         onInput={this.onChange.bind(this)}
         placeholderClass={styles.input_holder}
  />
onChange = e => {
    console.log(e, '1')
    this.setState({
        value: 222222
    },()=>{
        console.log(this.state.value)
    })
}
这里是相关代码，onInput开发者工具上不触发，真机上也不触发

**Comment by 490567134** [comment]
已解决 谢谢3楼的回答

**Comment by Vitaminaq** [comment]
我也碰倒了，这么坑的吗？还跟版本有关系

**Comment by Garfield550** [comment]
微信开发者工具基础库版本 Bug，其实后退一个小版本就好了。

**Comment by shenghanqin** [comment]
详情=>本地设置=>调试基础库，这里更换基础库版本试试看。

**Comment by 490567134** [comment]
已经通过更改基础库版本解决了，2.9.3版本有问题，使用2.9.2就没问题啦

**Comment by mytharcher** [comment]
升级工具到 `2.9.4` 也 ok 了，只有 `2.9.3` 是有问题的。
