### ISSUE TITLE
useEffect中设置state中的值后，props变成{}，即使设置了defaultProps也没用

### ISSUE THREAD

**Issue by gaogao2017** [NervJS/taro#4823]
**问题描述**
在自定义组件中，useEffect函数中设置state值，执行后props会变成{}

**复现步骤**
代码
![image](https://user-images.githubusercontent.com/26714881/68755812-033b9280-0644-11ea-9bd8-1e1b0d00f830.png)

调试结果
![image](https://user-images.githubusercontent.com/26714881/68755956-4c8be200-0644-11ea-95d4-eb1742af9c52.png)

**期望行为**
useEffect 在监控[] 时异步获取数据，并且不会影响props值

**报错信息**
没有报错

**系统信息**
![image](https://user-images.githubusercontent.com/26714881/68755839-10f11800-0644-11ea-98b0-7caa335f87e3.png)

**补充信息**
useEffect 在监控[] 时会自动执行两次，在其函数体中设置state值时，会出现第二次自执行时props为空

**Comment by Chen-jj** [comment]
@gaogao2017 代码贴文本

**Comment by Chen-jj** [comment]
#4815

**Comment by gaogao2017** [comment]
自定义组件代码
`
import Taro, { useState,useEffect,useCallback } from '@tarojs/taro'
import { View} from '@tarojs/components'
export default function AA(props) {
   const [list,setList]=useState()
  //组件初始化
  useEffect(()=>{
    console.log('执行useEffect[]')
    setList(1111)
  },[])
  useEffect(()=>{
    console.log('porps更新时props值:',props)
  },[props])
  useEffect(()=>{
    console.log('list更新时props值:',props)
  },[list])
  //事件绑定
  const goto=useCallback(()=>{
    props.selectedCB(111)
  })
  return (
   <View onClick={goto}>111</View>
  )
  
}

AA.defaultProps={
  initId:'',
  selectedCB:function(){}
}
AA.options={
  addGlobalClass:true
}
`

**Comment by gaogao2017** [comment]
自定义组件代码：


import Taro, { useState,useEffect,useCallback } from '@tarojs/taro'
import { View} from '@tarojs/components'
export default function AA(props) {
   const [list,setList]=useState()
  //组件初始化
  useEffect(()=>{
    console.log('执行useEffect[]')
    setList(1111)
  },[])
  useEffect(()=>{
    console.log('porps更新时props值:',props)
  },[props])
  useEffect(()=>{
    console.log('list更新时props值:',props)
  },[list])
  //事件绑定
  const goto=useCallback(()=>{
    props.selectedCB(111)
  })
  return (
   <View onClick={goto}>111</View>
  )
  
}

AA.defaultProps={
  initId:'',
  selectedCB:function(){}
}
AA.options={
  addGlobalClass:true
}

**Comment by Chen-jj** [comment]
@gaogao2017 升级到最新版

**Comment by gaogao2017** [comment]
我还发现通过useEffect 监控props
props值会变成{}
及时父组件传了props 或者设置了defalutProps也会变成{}

**Comment by gaogao2017** [comment]
升级到1.3.25 问题都好了
