### ISSUE TITLE
Taro create --name [页面名称] 命令不支持多层目录，不是很方便！

### ISSUE THREAD

**Issue by honlyHuang** [NervJS/taro#4825]
**问题描述**
Taro create --name [页面名称] 命令不支持多层目录

**复现步骤**

1. Taro create --name shop/cart

**期望行为**
![image](https://user-images.githubusercontent.com/3080820/68761184-8235c880-064e-11ea-9f91-6d35d8ddc891.png)

**报错信息**
无，但无法生产对应目录

**系统信息**
暂无

**补充信息**
来源：[论坛-Taro create --name [页面名称] 命令不支持多层目录，不是很方便！](https://taro-club.jd.com/topic/838/taro-create-name-%E9%A1%B5%E9%9D%A2%E5%90%8D%E7%A7%B0-%E5%91%BD%E4%BB%A4%E4%B8%8D%E6%94%AF%E6%8C%81%E5%A4%9A%E5%B1%82%E7%9B%AE%E5%BD%95-%E4%B8%8D%E6%98%AF%E5%BE%88%E6%96%B9%E4%BE%BF)

**Comment by Chen-jj** [comment]
比较冷门，暂不考虑实现
