### ISSUE TITLE
taro useState hook 与原生 react hooks 表现不一致

### ISSUE THREAD

**Issue by dpyzo0o** [NervJS/taro#4830]
### 问题描述

react hooks 中使用 `useState`, 当 `setState` 一个和之前 `state` 一样的值时, react 将不会 rerender. 文档中是这样写的

![Screen Shot 2019-11-14 at 10 31 40](https://user-images.githubusercontent.com/24768249/68821715-ffeaea00-06c9-11ea-8789-73c9c9326577.png)

但是在 taro 中, 只要是调用了 `useState` 返回的 `setState` 函数, 都会触发一次 rerender. 微信小程序与 h5 中都可以复现.

### 复现步骤

下面是一段可复现的代码:

```js
import Taro, { useState } from "@tarojs/taro";
import { View, Text, Button } from "@tarojs/components";
import "./index.css";

export default function Index() {
  const [count, setCount] = useState(0);
  console.log(count)

  const handleClick = () => {
    console.log('clicked')
    setCount(0)
  }

  return (
    <View className='index'>
      <Text>Hello world!</Text>
      <Button onClick={handleClick}>click</Button>
    </View>
  );
}
```

微信小程序中的表现:

<img width="609" alt="Screen Shot 2019-11-14 at 10 37 23" src="https://user-images.githubusercontent.com/24768249/68822179-3412da80-06cb-11ea-876f-ef8e00d8ae82.png">

h5 中的表现:

![1573699225993](https://user-images.githubusercontent.com/24768249/68822200-43922380-06cb-11ea-8e29-cac6653abd02.jpg)

原生 react 中的表现:

![Screen Shot 2019-11-14 at 10 42 20](https://user-images.githubusercontent.com/24768249/68822297-82c07480-06cb-11ea-9b38-ceee85502e45.png)

### 期望行为

与 react hooks 表现一致

### 系统信息

```bash
  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 1.3.22 => 1.3.22 
      @tarojs/plugin-babel: 1.3.22 => 1.3.22 
      @tarojs/plugin-csso: 1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22 
      @tarojs/router: 1.3.22 => 1.3.22 
      @tarojs/taro: 1.3.22 => 1.3.22 
      @tarojs/taro-alipay: 1.3.22 => 1.3.22 
      @tarojs/taro-h5: 1.3.22 => 1.3.22 
      @tarojs/taro-qq: 1.3.22 => 1.3.22 
      @tarojs/taro-quickapp: 1.3.22 => 1.3.22 
      @tarojs/taro-swan: 1.3.22 => 1.3.22 
      @tarojs/taro-tt: 1.3.22 => 1.3.22 
      @tarojs/taro-weapp: 1.3.22 => 1.3.22 
      @tarojs/webpack-runner: 1.3.22 => 1.3.22 
      eslint-config-taro: 1.3.22 => 1.3.22 
      eslint-plugin-taro: 1.3.22 => 1.3.22 
      nerv-devtools: ^1.5.0 => 1.5.5 
      nervjs: ^1.5.0 => 1.5.5 
      stylelint-config-taro-rn: 1.3.22 => 1.3.22 
      stylelint-taro-rn: 1.3.22 => 1.3.22 
    npmGlobalPackages:
      typescript: 3.6.3
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by dpyzo0o** [comment]
@yuche

**Comment by Chen-jj** [comment]
小程序应该好了https://github.com/NervJS/taro/commit/aec705ec653be62eacc96a552cccb49ffe8a9ec1

**Comment by dpyzo0o** [comment]
> 小程序应该好了[aec705e](https://github.com/NervJS/taro/commit/aec705ec653be62eacc96a552cccb49ffe8a9ec1)

等 1.3.26 就行了吗？

**Comment by Chen-jj** [comment]
嗯
