### ISSUE TITLE
子组件props拿不到父组件传递过来的ref

### ISSUE THREAD

**Issue by pasBone** [NervJS/taro#4832]
### 问题描述

目的：父组件想调用子组件方法

尝试方法1：  forwardRef
遇到阻碍： taro没有暴露forwardRef
尝试方法2： ref
遇到阻碍：子组件props拿不到父组件传递过来的ref
### 复现步骤
子组件
```js
// 子组件
export const ChildComponent: FC<IProps> = (props) => {
  console.log(props.ref);  // undefined
  useImperativeHandle(props.ref, () => {
    return {
      childFn: () => {
          // todo
      }
    }
  });
})

// 父组件
// childRef.current  可以拿到实例
<ChildComponent ref={childRef} />
```

### 期望行为
父组件调用子组件方法

### 系统信息

"@tarojs/taro": "1.3.23",
 "nervjs": "^1.5.5",

**Comment by Chen-jj** [comment]
@pasBone 不太清楚你要干嘛，如果是 “父组件想调用子组件方法”，ref 就可以。forwardRef 用于父组件直接获取子组件内部节点。

**Comment by pasBone** [comment]
> @pasBone 不太清楚你要干嘛，如果是 “父组件想调用子组件方法”，ref 就可以。forwardRef 用于父组件直接获取子组件内部节点。

我用的HOOKS，直接ref调用不到子组件的方法。
这是ref.curren打印出来的截图，并没有看到子组件的方法
![image](https://user-images.githubusercontent.com/18027183/68838613-ef526800-06f9-11ea-8dc0-6cf2da2daee6.png)

**Comment by pasBone** [comment]
这是我参照react的方式，才使用的 forwardRef
![image](https://user-images.githubusercontent.com/18027183/68838861-70116400-06fa-11ea-8df3-13f881d480ec.png)

**Comment by Chen-jj** [comment]
@pasBone useImperativeHandle 和 forwardRef 配合用的，小程序还做不到 forwardRef，所以这种需求用 Class Component 吧。

**Comment by pasBone** [comment]
目前子啊taro中，useImperativeHandle 和 forwardRef 配合有时候可以有时候不可以，这种不确定性的原因是什么我也不知道，

**Comment by pasBone** [comment]
在真机上用 useImperativeHandle 和 forwardRef 的方式没问题。开发者工具偶尔可以，原因未知

**Comment by iusn** [comment]
taro 版本 2.0.5
7.0.1版本的微信
发现这个问题
目前我自己定位的问题是
真机 有时候useImperativeHandle不起作用
打开调试模式就可以 可以调用子组件方法
否则报错
VM5324:1 Uncaught (in promise) thirdScriptError
authRef.current.showAction is not a function
TypeError: authRef.current.showAction is not a function
 然后如果在子组件中调用必须执行
useEffect 才能找到子组件中的方法

**Comment by BoringDays** [comment]
> 这是我参照react的方式，才使用的 forwardRef
> ![image](https://user-images.githubusercontent.com/18027183/68838861-70116400-06fa-11ea-8df3-13f881d480ec.png)

方法一在taro可行，目前我自己项目基本就是靠这个吃饭的

**Comment by shenmengnana** [comment]
下面这样写是可以的
```js
const childRef = useRef() 
<ChildComp 
 ref={cmp => {
      cmp && (childRef.current = cmp);
    }}
 />
```
ref={childRef} 这种  childRef会被重置成undefined（原因未知）
