### ISSUE TITLE
h5 设置断点怎么调试？

### ISSUE THREAD

**Issue by dlxqlig** [NervJS/taro#4833]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
希望还是给出一些示例代码来展示你的想法或者问题？

**Comment by dlxqlig** [comment]
运行yarn run dev:h5 代码运行，在chrome浏览器找不到代码来设置断点

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/68828802-e786c980-06e1-11ea-9ea1-739f5e40ce5a.png)

**Comment by dlxqlig** [comment]
找到了，多谢

**Comment by dlxqlig** [comment]
![Snipaste_2019-11-14_13-39-13](https://user-images.githubusercontent.com/6405352/68829747-ac39ca00-06e4-11ea-98b6-fb25285fc63f.jpg)

看了一下，都是经过taro翻译过的代码，能调试翻译之前的吗？
再问一下，能用vscode调试吗？

**Comment by shenghanqin** [comment]
你说的应该是SourceMap类似的功能吧？还请期待Taro后续的更新吧。

**Comment by dlxqlig** [comment]
了解，多谢。
