### ISSUE TITLE
在Taro里 怎么调用 支付宝小程序 的原生API？

### ISSUE THREAD

**Issue by cuixiaoya** [NervJS/taro#4834]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
比如Taro.request，你也可以用wx.request，只需要把wx设置为全局变量（方式eslint过不去）。
其实运行时，小程序本身是认可wx的。

支付宝小程序也类似。
