### ISSUE TITLE
循环中的索引值不能正确渲染到视图

### ISSUE THREAD

**Issue by DarcyXf** [NervJS/taro#4839]
### 复现步骤
1. 编译下方的代码，在微信小程序开发者工具中打开
2. 点击‘delete’删除索引值为2的item
3. 现象：剩余两个item,第二个item的索引值为3，期待为2

index.js
```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

import Item from "./item";

export default class List extends Component {
  constructor(props) {
    super(props);
    this.state = {
      list: [
        {
          id: 1,
          text: "aaa"
        },
        {
          id: 2,
          text: "bbb"
        },
        {
          id: 3,
          text: "ccc"
        }
      ]
    };
  }

  onDelete = id => {
    const newList = this.state.list.filter(i => i.id !== id)
    this.setState({list: newList})
  }

  renderList(list) {
    return list.map((item, index) => (
        <Item
          key={`key-${item.id}`}
          index={index}
          text={item.text}
          mid={item.id}
          onDelete={this.onDelete}
        />
    ));
  }

  render() {
    return (
      <View className='list'>
        {this.renderList(this.state.list)}
      </View>
    );
  }
}

```
item.js
```
import Taro from '@tarojs/taro'
import {View} from '@tarojs/components'

export default function Item(props) {
    const onDelete = () => {
        props.onDelete(props.mid);
    }

    const {index, text} = props;
    return (
        <View style='display: flex; align-item: center; margin: 20px'>
            <View>索引：{index+1}</View>
            <View style='margin: 0 40px;'>{text}</View>
            <View onClick={onDelete}>delete</View>
        </View>
    )
}

Item.defaultProps = {
    index: 0,
    text: '',
}

```

### 期望行为

期待删除第二项以后，剩余的项目中第二项的索引值为2

### 系统信息

Taro v1.3.5

  Taro CLI 1.3.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.5 => 1.3.5
      @tarojs/plugin-babel: 1.3.5 => 1.3.5
      @tarojs/plugin-csso: 1.3.5 => 1.3.5
      @tarojs/plugin-sass: 1.3.5 => 1.3.5
      @tarojs/plugin-uglifyjs: 1.3.5 => 1.3.5
      @tarojs/router: 1.3.5 => 1.3.5
      @tarojs/taro: 1.3.5 => 1.3.5
      @tarojs/taro-alipay: 1.3.5 => 1.3.5
      @tarojs/taro-h5: 1.3.5 => 1.3.5
      @tarojs/taro-swan: 1.3.5 => 1.3.5
      @tarojs/taro-tt: 1.3.5 => 1.3.5
      @tarojs/taro-weapp: 1.3.5 => 1.3.5
      @tarojs/webpack-runner: 1.3.5 => 1.3.5
      eslint-config-taro: 1.3.5 => 1.3.5
      eslint-plugin-taro: 1.3.5 => 1.3.5
      nerv-devtools: ^1.4.0 => 1.5.4
      nervjs: ^1.4.0 => 1.5.4

**Comment by DarcyXf** [comment]
@guotie @smoothdvd

**Comment by DarcyXf** [comment]
@luckyadam @yuche

**Comment by Chen-jj** [comment]
@DarcyXf 先不要加 key
