### ISSUE TITLE
引入rc-form, 不能调用rc-form的方法createForm方法

### ISSUE THREAD

**Issue by ErnestWangZuNian** [NervJS/taro#484]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

------------------------

**问题描述**
引入rc-form, 不能调用rc-form的方法createForm方法

**复现步骤**
[复现问题的步骤]
1. 引入taro官方redux模板
2.cnpm install rc-form
报错  Error: module "pages/index/rc-form.js" is not defined

```js
import { createForm, formShape } from "rc-form";
console.log(createForm, "wwww");

```

**期望行为**
正常引用

**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/11648360/44244602-50de0b00-a207-11e8-8a62-e2a34575b138.png)

**系统信息**

 - 操作系统: [e.g. Windows 7
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]

**Comment by luckyadam** [comment]
`pages/index/rc-form.js` ，在 index 页面中有引用这个文件么

**Comment by ErnestWangZuNian** [comment]
没有 
import { createForm, formShape } from "rc-form";
只在page/index中引入了 rc-form

**Comment by luckyadam** [comment]
rc-form 这是 react 的组件，在 Taro 中不能使用
另外，你的版本有点旧了，升级到 1.0.0-beta.11 吧

**Comment by NoBey** [comment]
@luckyadam  现在rc-form能了吗，有什么好的表单解决方案吗

**Comment by JohannLai** [comment]
同问，有好用的表单解决方案吗？
