### ISSUE TITLE
taro项目本身怎么调试，支持vscode吗，还是直接用打log?

### ISSUE THREAD

**Issue by dlxqlig** [NervJS/taro#4840]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
参考debug指南
https://nervjs.github.io/taro/docs/debug.html
