### ISSUE TITLE
原生微信小程序通过taro convert反编译过来的代码，丢掉了原生代码的逻辑，丢掉了基础规范

### ISSUE THREAD

**Issue by anryzhang** [NervJS/taro#4841]
### 问题描述
1，在原生小程序里写的三目运算符，在convert后，直接丢掉了三目运算，返回的是三目运算的结果。
2， 在原生里的正常语法规范，在convert后， 语法的规范也丢了，如语句后的 ; 被丢了。

**Comment by Garfield550** [comment]
JS 可以省略语句后的分号，如果希望加回来的话，建议自己增加 prettier 插件，把 `semi` 设置成 true，https://prettier.io/docs/en/options.html#semicolons

第一个可能是个问题。

**Comment by yuche** [comment]
第二个按楼上的说，第一个要给复现
