### ISSUE TITLE
使用taro开发第三方UI库组件

### ISSUE THREAD

**Issue by xiaerhuo** [NervJS/taro#4844]
### 问题描述
![1573799109727](https://user-images.githubusercontent.com/24564048/68921488-e9b95880-07b3-11ea-8af2-0d755254bf86.jpg)

使用`taro build --ui`编译出来的组件，是没有被编译过的？

**这样是否意味着taro编译的小程序第三方ui组件仅支持在taro项目中使用？**

**Comment by Garfield550** [comment]
建议到文档页面详细读一下介绍。

Taro 开发到多端 UI 组件当然是只能用在 Taro 上的。

https://taro-docs.jd.com/taro/docs/ui-lib.html

**Comment by ChangerHe** [comment]
后期是否会提供H5端的recompiler包用来支持react base的项目, 而不用强依赖于nervjs(taro)?

**Comment by shenghanqin** [comment]
我也有这个想法。 @luckyadam
