### ISSUE TITLE
微信原生小程序转H5时有些文件没有

### ISSUE THREAD

**Issue by secularworld** [NervJS/taro#4846]
微信原生小程序转H5时有些文件没有了，而且转换是有报错，不知道什么原因

The "path" argument must be of type string. Received type undefined

**Comment by Littly** [comment]
是转换时报的错还是转换完跑h5时报的错？

**Comment by secularworld** [comment]
转换的时候报错，而且转换之后会丢失一些文件

**Comment by secularworld** [comment]
刚刚用taro doctor检测，有提示说没有安装util.js依赖，这个是指我小程序的util.js 还是taro有util.js依赖？

**Comment by shenghanqin** [comment]
请提供源码、示例demo，或者终端截图。
尽量全面一些，好方便排查问题。
