### ISSUE TITLE
在小程序内使用useSelector，状态没有改变

### ISSUE THREAD

**Issue by crabkiller** [NervJS/taro#4848]
### 问题描述

将自带的模板改成FunctionComponent，使用 useSelector useDispatch hook， useDispatch 可以正常改变store里面值， useSelector 返回值没有变化

### 复现步骤

请看 https://github.com/NervJS/taro/issues/3456 这个 issue 已经 closed 了，但是我目前用的 1.3.25 仍然是有问题，请问是解决了吗，我需要怎么操作

### 期望行为

状态变化

**Comment by Chen-jj** [comment]
@crabkiller 提供一下可复现 demo

**Comment by crabkiller** [comment]
我提出的问题就是 https://github.com/NervJS/taro/issues/3456 这个 issue 的问题，请问 https://github.com/NervJS/taro/commit/1ab61236b8349b5c9289bbd6fe854528b96c5cc0 这条 commit 的修复代码能合到 1.3.x 版本上吗 @Chen-jj

**Comment by Chen-jj** [comment]
@crabkiller 试试 2.0.0-beta.2 咯

**Comment by crabkiller** [comment]
你好，我这个是线上正式项目，用 beta 版怕出什么问题不好解决，毕竟还在 beta 阶段，或者2.0.0 正式版大概什么时候发布有计划吗，而且我个人觉得为了这种 bugfix 而升级大版本，这个跨度有点大

**Comment by Chen-jj** [comment]
@crabkiller 看了下 1.3.2 就有了

![image](https://user-images.githubusercontent.com/11807297/69031268-aa3d7700-0a14-11ea-8bb0-c6344ebc4fce.png)

**Comment by crabkiller** [comment]
好吧我的问题，不好意思

**Comment by azumia** [comment]
> 好吧我的问题，不好意思

请问是如何解决的？我也遇到了....

**Comment by azumia** [comment]
@crabkiller 请问是如何解决的？我也遇到了....

**Comment by crabkiller** [comment]
> @crabkiller 请问是如何解决的？我也遇到了....

我的当时是自己使用错误，建议你可以把 `@tarojs/redux` 升级到 `1.3.2` 以上版本试试，如果还有问题检查一下代码是否有问题，或者把你代码贴出来看看。
