### ISSUE TITLE
微信小程序组件每添加一个属性就需要等 taro 发布一次版本才能使用吗？

### ISSUE THREAD

**Issue by bee961122** [NervJS/taro#4852]
### 问题描述

比如scroll-view组件，微信小程序官网最新支持了scroll-anchoring属性，在taro里不能直接用，不生效，最新版本的 taro 也没有及时增加支持。

想问的是：taro 是不是应该出一个通用的方法解决这个问题，不用每次都要等新版本发布才能使用最新的小程序组件属性？

**Comment by Garfield550** [comment]
仅微信小程序的话，先自己改一下 d.ts 文件试一下，另外Taro 的多端组件一定程度上是使用 Nerv 重新做的，如果用到小程序外的地方需要等更新。

**Comment by Chen-jj** [comment]
@bee961122 可以直接写
![image](https://user-images.githubusercontent.com/11807297/69030261-f33ffc00-0a11-11ea-8656-dc7e71a14e66.png)
