### ISSUE TITLE
本地安装的是1.3.22  项目跑的是1.3.14 想降回去报错·

### ISSUE THREAD

**Issue by aaa583834691** [NervJS/taro#4853]
C:\Users\Angsi>npm i -g @tarojs/cli@1.3.14
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated eslint-plugin-typescript@0.12.0: Deprecated: Use @typescript-eslint/eslint-plugin instead
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN eslint-config-taro@1.3.14 requires a peer of eslint@^5.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-taro@1.3.14 requires a peer of eslint@^5.16.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path C:\Users\Angsi\AppData\Roaming\npm\taro.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Users\Angsi\AppData\Roaming\npm\taro.cmd: is outside C:\Users\Angsi\AppData\Roaming\npm\node_modules\@tarojs\cli and not a link
npm ERR! File exists: C:\Users\Angsi\AppData\Roaming\npm\taro.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Angsi\AppData\Roaming\npm-cache\_logs\2019-11-16T03_29_29_969Z-debug.log

**Comment by Littly** [comment]
请依照issue模板参与讨论
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way
