### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by damonare** [NervJS/taro#4858]
### 问题描述
子组件如下：
```js
export default class Avatar extends Component {
  render() {
    return (
      <View>测试</View>
    )
  }
}
```
父组件引用：
```js
import Avatar from '../../components/avatar'
// 如上命名为Avatar再进行引用的话报错 TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object
```

### 复现步骤
子组件：
```js
export default class Avatar extends Component {
  render() {
    return (
      <View>测试</View>
    )
  }
}
```
父组件：
```js
import Avatar from '../../components/avatar'
class  User extends Component {
  render() {
     return (
      <Avatar />
   )
  }
}
```

### 系统信息

👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 2.5.0 - /usr/local/bin/fish
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.18 => 1.3.18 
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-less: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/redux: 1.3.18 => 1.3.18 
      @tarojs/redux-h5: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-alipay: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-swan: 1.3.18 => 1.3.18 
      @tarojs/taro-tt: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nerv-devtools: ^1.4.0 => 1.5.5 
      nervjs: ^1.4.0 => 1.5.5 
      stylelint-config-taro-rn: 1.3.18 => 1.3.18 
      stylelint-taro-rn: 1.3.18 => 1.3.18 
    npmGlobalPackages:
      typescript: 3.3.3333

**Comment by Chen-jj** [comment]
@damonare 复现不了，普通引用一个组件不会错的，自己检查一下代码吧

**Comment by sunflower-tc** [comment]
遇到了同样的问题+1

**Comment by Liberxue** [comment]
```zsh
错误  组件错误  组件GojsDiagram路径错误，请检查！（可能原因是导出的组件名不正确）
错误  组件编译  组件src/components/Diagram.tsx编译失败！
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.relative (path.js:1055:5)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/component.js:254:84
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/component.js:245:52
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/component.js:244:54
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@tarojs/cli/dist/mini/component.js:241:40
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
生成  组件配置  dist/dist/components/MyDiagramContainer.json
生成  组件逻辑  dist/dist/components/MyDiagramContainer.js
```

**Comment by zjb19970804** [comment]
同样问题，ubuntu环境，"@tarojs/taro": "1.3.25"

**Comment by mylesshie** [comment]
同样问题+1

**Comment by mylesshie** [comment]
修改了引入后的名称就不报错了。。。

**Comment by A0150315** [comment]
+1

**Comment by kkxujq** [comment]
+1

**Comment by blanklong28** [comment]
+1
