### ISSUE TITLE
cli 不支持使用project.qq.json 配置文件

### ISSUE THREAD

**Issue by evont** [NervJS/taro#4859]
### 问题描述

当按照文档中所说的创建project.qq.json 后，读取的仍旧是project.config.json，导致最终使用的appid 错误，经查，是代码指定了qq 也用project.config.json，望改正

### 复现步骤

1. 创建project.qq.json
2. 执行yarn dev:qq
3. 可见project.config.json 内容仍为微信的配置

cli 中的问题代码如下：

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

  let projectConfigFileName = `project.${buildAdapter}.json`;
  if (buildAdapter === "weapp" /* WEAPP */ || buildAdapter === "qq" /* QQ */) {
       projectConfigFileName = 'project.config.json';
  }
  let projectConfigPath = path.join(appPath, projectConfigFileName);
 // ...
```

### 期望行为

期望qq小程序拥有自己指定的配置json 文件，经自己实测可以删除该段qq 判断可用

### 系统信息

Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v11.10.1/bin/npm

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@evont 欢迎 PR

**Comment by evont** [comment]
fixed #4865
