### ISSUE TITLE
getCurrentPages 和 getApp 没有在 ts 类型中定义

### ISSUE THREAD

**Issue by zaaack** [NervJS/taro#486]
https://github.com/NervJS/taro/commit/744dda7#diff-205968faea765fabe95218ee45e68f8fR308

看起来是忘记更新 tsd 了。。

**Comment by yuche** [comment]
提一个 PR 咯

**Comment by zacksleo** [comment]
又看见你了 😃

**Comment by zaaack** [comment]
@zacksleo 看到你在 Taro 的 issue 底下挺活跃啊 👍。 现在又要开始写小程序了，打算把以前的代码迁移到 taro 上来。
