### ISSUE TITLE
微信小程序使用wxParse时, 富文本节点内容消失

### ISSUE THREAD

**Issue by yeojongki** [NervJS/taro#4860]
### 问题描述
根据官方repo 使用 wxParse 解析富文本
https://github.com/NervJS/taro-sample-weapp/blob/master/src/pages/wxParse/wxParseComponent.js

然后在页面中添加了 vant-weapp 这个 ui 组件, 发现加入弹窗组件 `van-popup` 时, 富文本的内容会变成空白消失. 

复现 repo 地址, 项目是 taro-cli 创建的 ts 默认模板
https://github.com/yeojongki/taro-wxparse-vant-popup

### 复现步骤
1. 进入页面时, 富文本正常渲染, 如图
![image](https://user-images.githubusercontent.com/21023676/69031171-6cd8e980-0a14-11ea-8d7e-0a56fa90535f.png)

2. 点击按钮打开弹窗
富文本内容消失, 如下图
![image](https://user-images.githubusercontent.com/21023676/69031643-8d557380-0a15-11ea-9e9e-53a9cdda8668.png)

### 期望行为

打开弹窗前后, 富文本正常显示

### 报错信息
无

### 系统信息
PS D:\yeojongki\work\taro-wxparse-vant-popup> taro info
�👽 Taro v1.3.25

  Taro CLI 1.3.25 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\My\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@yeojongki 仔细看看 wxparse 的代码就懂了

```js
componentDidMount() {
    const { content } = this.props;
    WxParse.wxParse('content', 'html', content, this.$scope, 5);
}
componentDidUpdate() {
    const { content } = this.props;
    WxParse.wxParse('content', 'html', content, this.$scope, 5);
}
```
