### ISSUE TITLE
请问h5打包能混合成一个js或者实现预加载页面的功能么

### ISSUE THREAD

**Issue by a709691139** [NervJS/taro#4867]
### 问题描述
h5页面跳转有一段时间的白屏，所以希望能打包成一个文件，或者实现webpack的import('xx').then功能
```js
const stockChartPromise = import("./StockChart");
const StockChart = React.lazy(() => stockChartPromise);
// 或者 
const Home = AsynLoadable(() => import(/* webpackChunkName: "home" */"routes/Platform/Home"));
<Route path="/Home" exact component={Home} />

```

**Comment by dyk98** [comment]
我也有相同的问题，某一个页面白屏时间过长，希望预加载这个页面的js文件

**Comment by Link-X** [comment]
同求，请问可以加入页面加载loding动画吗

**Comment by ZakaryCode** [comment]
预加载页面可以使用 [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin) 插件

**Comment by ZakaryCode** [comment]
打包成同一个 js 可以使用插件 [LimitChunkCountPlugin](https://v4.webpack.js.org/plugins/limit-chunk-count-plugin/)

> 页面懒加载可以通过给 babel-preset-taro 配置 `dynamic-import-node` 参数，这个参数会将所有 `import` 转换成 `require` 去掉懒加载。

**Comment by ZakaryCode** [comment]
> 同求，请问可以加入页面加载loding动画吗

动画在 3.3.18+ 版本实现，可以升级使用
