### ISSUE TITLE
react hooks 内置 render function 在小程序上无法触发更新

### ISSUE THREAD

**Issue by Phlen** [NervJS/taro#4869]
### 问题描述
react hooks 内置 render function 在小程序上无法触发更新，h5上表现正常

### 复现步骤
1.在hoosk 组件中添加内置render function
```js
export default function fs = () => {
    const [current, setCurrent] = useState<number>(0)
   const renderText = () => {
      return <View>{current}</View>
  }
  return <View>
  {renderTest()}
   </View>
}
```
### 期望行为

更新state后，render fucntion 能正常响应更新

### 系统信息

taro: v1.3.22

**Comment by Chen-jj** [comment]
@Phlen 开一下 ESLint 吧，CLI 应该有报错，不能这样写。
