### ISSUE TITLE
自定义组件无法传入自定义事件

### ISSUE THREAD

**Issue by BryantZhou** [NervJS/taro#487]
**问题描述**
自定义组件的时候， 传入自定义事件，在组件的props里面无法打印出来，根据文档上面已经在事件前加了on

**复现步骤**

pages/demo/demo.js

```js
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';
import Demo from '../../components/Demo/Demo';

class Index extends Component {
  config = {
    navigationBarTitleText: 'demo'
  };

  onTest = () => {
    console.log('test');
  };

  render() {
    console.log('demo render');

    return (
      <View>
        <Demo onTest={this.onTest} />
      </View>
    );
  }
}

export default Index;

```

components/Demo/Demo.js
```js
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';

export default class Demo extends Component {
  render() {
    console.log('Demo Component Render');
    console.log('Demo Component props onDemo ========>', this.props.onTest);

    return <View>Demo Component</View>;
  }
}


```

控制台打印信息

![image](https://user-images.githubusercontent.com/12403684/44258170-c6b29880-a240-11e8-96e0-edef14f3b83d.png)

**期望行为**
能够进行自定义事件传递

**报错信息**

**系统信息**

 - 操作系统: [e.g. MacOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.0-beta10]
 - Node.js 版本 [e.g. v8.11.1]

**补充信息**
[可选]

应该是没编译到这个方法过去

**Comment by yuche** [comment]
`this.props.onEvent` 和 `this.props.childern` 都是无法打印的，当你具体地调用了 `this.props.onEvent()` 时 Taro 会把他编译成可以执行的函数。

**Comment by BryantZhou** [comment]
@yuche  所以我调用的时候也是只能 this.props.onEvent调用 而不能先 const {onEvent} = this.props 再 onEvent() 这样调用对吧
