### ISSUE TITLE
代码逻辑复杂到一定程度时，有大概率 componentDidNotFound 不会被执行

### ISSUE THREAD

**Issue by Elliott-Hu** [NervJS/taro#4870]
### 问题描述
更新了微信开发者工具 stable 1.02.1910120 版本，出现了 onPageNotFound 的问题，原因有可能是绑定 onPageNotFound 的时机要晚于 小程序执行代码启动的某个阶段。

目前怀疑是当前Taro的实现中， onPageNotFound 的绑定操作是在异步的环境下执行的，比如在setTimeout 或者 promise.resolve 里面去完成。

要保证 onPageNotFound 绑定尽早执行

### 复现步骤
以下代码可能具有相似的原理
1.选择编译模式：模拟扫码打开小程序
2.打开app.js
3.尝试调整setTimeout 执行的时间，从100 到 2000，数值越大越容易复现
https://developers.weixin.qq.com/s/McOOrZmE7Sc0

### 期望行为
onPageNotFound 能够可靠、大概率地被触发

### 报错信息
![image](https://user-images.githubusercontent.com/16644716/69129046-95321800-0ae8-11ea-90a3-bcd0c648fb04.png)

### 系统信息
👽 Taro v1.3.25

  Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/redux: 1.3.25 => 1.3.25 
      @tarojs/redux-h5: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.5 
      nervjs: ^1.5.5 => 1.5.5 
      react: ^16.8.6 => 16.9.0 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25

**Comment by Chen-jj** [comment]
@Elliott-Hu 这里是 App 注册的对象，可以看到微信一触发 `onPageNotFound`，Taro 就会触发开发者的 `componentDidNotFound`

https://github.com/NervJS/taro/blob/a39a4ee65df8f574c93fe5f0a28d092d8eac9694/packages/taro-weapp/src/create-app.js#L36-L40

**Comment by Elliott-Hu** [comment]
> @Elliott-Hu 这里是 App 注册的对象，可以看到微信一触发 `onPageNotFound`，Taro 就会触发开发者的 `componentDidNotFound`
> 
> https://github.com/NervJS/taro/blob/a39a4ee65df8f574c93fe5f0a28d092d8eac9694/packages/taro-weapp/src/create-app.js#L36-L40

似乎是小程序的问题，目前已反馈给小程序官方
