### ISSUE TITLE
react-native 升级到0.61.4 使用hooks 出错

### ISSUE THREAD

**Issue by fengwuxp** [NervJS/taro#4873]
### 问题描述
 android端
 tarojs 版本 1.3.25
 react-native 升级到0.61.4，不使用hooksApi正常，使用了报错，错误信息如下
```
 Invalid hook call. Hooks can only be called inside of the body of a function component. This could 
  happen for one of the following reasons:

  You might have mismatching versions of React and the renderer (such as React DOM)
  You might be breaking the Rules of Hooks
  You might have more than one copy of React in the same app\nSee https://fb.me/react-invalid- 
 hook-call for tips about how to debug and fix this problem
```
另外我使用了一个纯粹的react-native工程，生成的js文件是可以运行在taro工程生成Apk上的，所以应该可以排除是app的问题，应该是taro打包出来的js可能不太对

### hooks组件代码如下
  ```jsx
      import Taro, {useState} from '@tarojs/taro'
      import  {Button,Text, View} from "@tarojs/components";

      export const Counter = ({initialCount}) => {
        const [count, setCount] = useState(initialCount);
         return (
           <View>
             <Text> Count: {count}</Text>
              <Button onClick={() => setCount(initialCount)}>Reset</Button>
              <Button onClick={() => setCount(prevCount => prevCount + 1)}>+</Button>
              <Button onClick={() => setCount(prevCount => prevCount - 1)}>-</Button>
          </View>
       );
     };
  ```

**Comment by Pines-Cheng** [comment]
React 16.8.0 is the first release to support Hooks. When upgrading, don’t forget to update all packages, including React DOM. React Native supports Hooks since the 0.59 release of React Native.

React 版本有升级吗？

**Comment by Pines-Cheng** [comment]
React 16.8.0 is the first release to support Hooks. When upgrading, don’t forget to update all packages, including React DOM. React Native supports Hooks since the 0.59 release of React Native.

React 版本有升级吗？

**Comment by fengwuxp** [comment]
有的，react用的是16.12.0版本

**Comment by Pines-Cheng** [comment]
那就剩下第三那个可能了： You might have more than one copy of React in the same app。🤔

**Comment by princeSmall** [comment]
how to fixed ?
