### ISSUE TITLE
_index2.default.RefsArray is not a constructor

### ISSUE THREAD

**Issue by Richard-Choooou** [NervJS/taro#4876]
### 问题描述
![image](https://user-images.githubusercontent.com/23492006/69205825-070c6f00-0b86-11ea-84eb-67995046b5ee.png)

![image](https://user-images.githubusercontent.com/23492006/69205886-30c59600-0b86-11ea-84d9-b0a13f449cf6.png)

### 复现步骤

1. 运行 yarn dev:weapp

### 期望行为
之前运行一直都是好的，不知为何出现这个问题

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@Richard-Choooou CLI 依赖版本保持一致

**Comment by aFcFzF** [comment]
最后怎么解决的？

**Comment by jimmy2012** [comment]
> 最后怎么解决的？

需要把全局taro版本退回到项目taro版本一致
