### ISSUE TITLE
taro1.3.20  组件模块重定向导出bug

### ISSUE THREAD

**Issue by miaolq** [NervJS/taro#4878]
### 问题描述

用一个js文件对多个组件进行重定向导出, 使用组件时从该js文件导入.  编译后报错:没有该js文件.  查看编译后的文件夹,缺少此js文件

### 复现步骤

taro1.3.20
1. 小程序子包中,用一个js对多个组件进行重定向导出
2. 使用组件时从该js文件导入, 该js文件不会被编译

```js
// 重定向组件
export { default as ZsBmi } from './zs-bmi'
export { default as ZsDate } from './zs-date'
export { default as ZsMulti } from './zs-multi'
export { default as ZsSelect } from './zs-select'
export { default as ZsSmoke } from './zs-smoke'
export { default as ZsText } from './zs-text'
export { default as ZsTrigger } from './zs-trigger'
```

```js
// 在页面中使用组件
import { ZsText, ZsTrigger, ZsDate, ZsSelect } from '../components/index'

```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@miaolq 试试 2.0.0-beta 吧
