### ISSUE TITLE
可选onClick事件有几率会导致错误

### ISSUE THREAD

**Issue by Piecego** [NervJS/taro#4879]
### 问题描述

一个组件上有一个可选的onClick事件，如果它的父节点及更上层节点存在onClick事件会因为冒泡的关系触发这个组件的onClick事件，如果父组件没有传递onClick的时候点击都会抛出一个错误，如下：
```
Cannot read property 'apply' of undefined
```

![image](https://user-images.githubusercontent.com/29162393/69211146-0f6da580-0b98-11ea-8a88-41fc613d0b29.png)

组件中onClick很可能是可选的，所以这里可能是undefined

### 版本信息
Tarojs: 1.3.22

### 补充信息

无

**Comment by Chen-jj** [comment]
@Piecego 上完整代码

**Comment by Garfield550** [comment]
尝试给子组件的 defaultProps onClick 指定一个空函数？如`() => {}`

**Comment by Piecego** [comment]
> 尝试给子组件的 defaultProps onClick 指定一个空函数？如`() => {}`

我目前是这样处理的，但是感觉有些别扭

**Comment by Piecego** [comment]
> @Piecego 上完整代码

p.tsx
```ts
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'
import Component from '~/pages/ui-tests/c'

interface Props {
  onClick?(): void
}

export default function P(props: Props) {
  return (
    <View onClick={props.onClick}>
      parent
      <Component/>
    </View>
  )
}
```

c.tsx
```ts
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

interface Props {
  onClick?(): void
}

function C(props: Props) {
  return (
    <View onClick={props.onClick}>
      fd65fd65b
    </View>
  )
}
C.options = {
  addGlobalClass: true
}
export default C
```
![image](https://user-images.githubusercontent.com/29162393/69215806-95dcb400-0ba5-11ea-9d1e-218e9e0b5449.png)

**Comment by Piecego** [comment]
@Chen-jj

**Comment by Garfield550** [comment]
建议给非必须属性加入 `defaultProps`，或者你调用 props 时检测一下有没有定义

```tsx
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

interface Props {
  onClick?(): void
}

function C(props: Props) {
  const onClickFunc = () => {
    props.onClick && props.onClick()
  }
  return (
    <View onClick={onClickFunc}>
      fd65fd65b
    </View>
  )
}
C.options = {
  addGlobalClass: true
}
export default C
```

![image](https://user-images.githubusercontent.com/3471836/69299745-48ffe880-0c4c-11ea-82b4-c8a0f6af1fc4.png)
