### ISSUE TITLE
Swiper 设置 Circular 后 SwiperItem 挤在一起

### ISSUE THREAD

**Issue by jasonzhangdong** [NervJS/taro#4880]
**这个功能解决了什么问题？**

**你期望的功能是怎样的？**

**补充信息**

**Comment by Garfield550** [comment]
帮你转来 Taro 这边。

先保证所有的依赖版本和 CLI 版本一致吧，然后补充一下 `taro info` 出来的信息。
再来一份详细点的代码。

**Comment by Chen-jj** [comment]
升级到 3.0 再试试
