### ISSUE TITLE
小程序的recycleview没继承

### ISSUE THREAD

**Issue by haoyinag** [NervJS/taro#4881]
### 问题描述
由于列表页需要使用大量的图片+视频，导致页面很容易奔溃，找尽了各种办法，最后看到
小程序提供了recycleview这个长列表标签可以优化性能？
**结果taro没实现还是？？？**

地址[https://developers.weixin.qq.com/miniprogram/dev/extended/functional/recycle-view.html](url)

![image](https://user-images.githubusercontent.com/24349947/69237487-c6861300-0bd0-11ea-851b-9513042196e7.png)

**Comment by Garfield550** [comment]
你给的是微信小程序的文档，所以你的目标平台是微信小程序的吗？

**Comment by Chen-jj** [comment]
@haoyinag  可以直接使用小程序原生组件

**Comment by haoyinag** [comment]
@Chen-jj 好的
