### ISSUE TITLE
typescript 项目模板怎么修改 eslint 配置支持分号检测

### ISSUE THREAD

**Issue by Go7hic** [NervJS/taro#4885]
### 问题描述

用Taro 生成的ts项目模板，Taro代码规范推荐的不写分号，但我习惯写分号，想修改eslint配置，可发现这个配置对 tsx 这些后缀文件无效。
默认生成的配置如下：
```
{
  "extends": ["taro"],
  "rules": {
    "no-unused-vars": ["error", { "varsIgnorePattern": "Taro" }],
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", ".tsx"] }]
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "useJSXTextNode": true,
    "project": "./tsconfig.json"
  }
}
```
如果只是在 rules 里面加个 “semi": "error"，只能对js文件生效，对ts文件没效。加个 `@typescript-eslint/eslint-plugin`插件，通过 @typescript-eslint/semi 来设置也没效，不知道官方有没有类似的例子

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/69299303-3802a780-0c4b-11ea-81e9-9f37011fb481.png)
改改这个试试
