### ISSUE TITLE
Error: 未找到 Taro.Component 的类定义

### ISSUE THREAD

**Issue by yeojongki** [NervJS/taro#4886]
### 问题描述
为了优化组件使用了 Taro.memo，但是发现会报错。去除后可以正常使用组件.

### 复现步骤
复现repo:  https://github.com/yeojongki/taro-wxparse-vant-popup
```js
// 子组件
import Taro from '@tarojs/taro';
import { View } from '@tarojs/components';

export const Test = Taro.memo(({ name }: { name: string }) => {
  return <View>Test component {name}</View>;
});

```

```js
// 父组件
import Taro, { Component } from '@tarojs/taro';
import { Test } from '@/components/Test';

export default class Index extends Component {
  render() {
    return (
      <View className="index">
        <Text>首页!</Text>
        <Test name="test name" />
      </View>
    );
  }
}
```

### 期望行为

正常使用 Taro.memo 不报错

### 报错信息

![image](https://user-images.githubusercontent.com/21023676/69300103-4651c300-0c4d-11ea-8fa2-0fd3b959d073.png)

### 系统信息
�👽 Taro v1.3.25

  Taro CLI 1.3.25 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\My\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD

**Comment by bobsam** [comment]
你是不是没有引入 Taro 变量啊……

**Comment by yeojongki** [comment]
> 你是不是没有引入 Taro 变量啊……

确实没导入, 刚补上了试了也是一样的报错, 去掉 `Taro.memo` 后正常

**Comment by yeojongki** [comment]
顺便问一下怎么在**函数组件**中使用 **类组件**中 `config` 中的 `usingComponents` ?

**Comment by yeojongki** [comment]
@shenghanqin @luckyadam @Garfield550 大佬们麻烦看下?

**Comment by xhwgood** [comment]
我跟楼主的问题基本一样，但我是简化成了函数式组件，前几天还正常的，今天莫名其妙就报错了

**Comment by yuche** [comment]
```
const Test = ({ name }: { name: string }) => {
  return <View>Test component {name}</View>;
}
export default Taro.memo(Test)
```

使用 Taro 你一定需要 export default

**Comment by yeojongki** [comment]
> ```
> const Test = ({ name }: { name: string }) => {
>   return <View>Test component {name}</View>;
> }
> export default Taro.memo(Test)
> ```
> 
> 使用 Taro 你一定需要 export default

是 `Taro` 的语法规定要这样吗?

**Comment by xhwgood** [comment]
@yuche 
能不能帮忙看下我这段代码是否有问题？
```
import { View, Image } from "@tarojs/components";
import logo from "@images/LOGO.jpg";
import './logo.scss'

export default Logo = () => {
  return (
    <View className="title">
      <Image className="logo" src={logo} />
      <View className="desc">量身打造</View>
    </View>
  )
}

```
这代码我没有动过，前几天使用很正常，昨天启动项目后就报错了

**Comment by 763139102** [comment]
> @yuche
> 能不能帮忙看下我这段代码是否有问题？
> 
> ```
> import { View, Image } from "@tarojs/components";
> import logo from "@images/LOGO.jpg";
> import './logo.scss'
> 
> export default Logo = () => {
>   return (
>     <View className="title">
>       <Image className="logo" src={logo} />
>       <View className="desc">量身打造</View>
>     </View>
>   )
> }
> ```
> 
> 这代码我没有动过，前几天使用很正常，昨天启动项目后就报错了

我也有同样的问题

**Comment by Garfield550** [comment]
ESLint 有规则，没有使用 Taro 也要引入 Taro `import Taro from '@tarojs/taro'`

**Comment by xhwgood** [comment]
> ESLint 有规则，没有使用 Taro 也要引入 Taro `import Taro from '@tarojs/taro'`

我之前确实不知道有这规则，我没有引入，但如我之前所说使用正常且没有报错。
第二天启动后报错了，引入Taro后其实还是报错，项目的taro版本与本地cli版本一致，删除node_modules重装依赖还是报错。

**Comment by Garfield550** [comment]
项目目录里执行一下 `taro info`

**Comment by xhwgood** [comment]
�👽 Taro v1.3.

  Taro CLI 1.3.25 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - D:\nodejs\node.EXE
      Yarn: 1.18.0-20190712.1421 - D:\Yarn\bin\yarn.CMD
      npm: 6.13.0 - D:\nodejs\npm.CMD

**Comment by Garfield550** [comment]
在你项目目录里有 package.json 的地方执行 `taro info`

**Comment by 763139102** [comment]
> 在你项目根目录里有 package.json 的地方执行 `taro info`

执行了，不可以的，
![image](https://user-images.githubusercontent.com/25519902/70610183-18eda900-1c3e-11ea-828d-1557d085feea.png)

**Comment by a896853205** [comment]
@yeojongki 我这使用`memo`的时候也出现了`Error: 未找到 Taro.Component 的类定义`编译报错,但后来发现我把这个组件当做小程序的page来使用了,非page使用`memo`就不会报错,不知道情况是不是相同.

**Comment by yeojongki** [comment]
@a896853205 要这样使用才行

> ```
> const Test = ({ name }: { name: string }) => {
>   return <View>Test component {name}</View>;
> }
> export default Taro.memo(Test)
> ```
> 
> 使用 Taro 你一定需要 export default
