### ISSUE TITLE
微信端函数组件内 renderXX 方法返回的组件内使用 style属性无效

### ISSUE THREAD

**Issue by dedeyi** [NervJS/taro#4887]
### 问题描述

页面引入函数式组件，组件内的方法 `renderComp` 中 `style` 属性在微信小程序里不生效 ，支付宝没问题，但是 `class` 组件没问题

### 复现步骤
1、这里是主页面
![image](https://user-images.githubusercontent.com/5554578/69301452-4e136680-0c51-11ea-8235-8b8eb3ba0fae.png)

2、这里是函数组件 `List` 里面的 `renderItem` 用到 `style` 属性
![image](https://user-images.githubusercontent.com/5554578/69301684-10fba400-0c52-11ea-8e64-a4382ab2d157.png)

3、微信小程序端渲染出来不对了 
![TIM截图20191121103645](https://user-images.githubusercontent.com/5554578/69301647-ef022180-0c51-11ea-9965-ea95b3d9018d.png)

4、但是如果使用class component是可以的
![image](https://user-images.githubusercontent.com/5554578/69301733-37214400-0c52-11ea-8b8c-23901b10c2c6.png)

```

### 期望行为

`style`在微信小程序正常生效

### 系统信息

  Taro CLI 1.3.25 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 10.16.3 - D:\software\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\software\nodejs\npm.CMD

### 补充信息

在支付宝小程序函数组件 style 也是正常的
![image](https://user-images.githubusercontent.com/5554578/69301828-82d3ed80-0c52-11ea-8cd8-3c13d570eb1f.png)

**Comment by ldwonday** [comment]
我也遇到了这个bug

**Comment by Chen-jj** [comment]
升级到 Taro3 再试试
