### ISSUE TITLE
componentDidCatch当前组件可以，父级组件不能捕获子组件错误

### ISSUE THREAD

**Issue by Hardcore0331** [NervJS/taro#4891]
### 问题描述

H5环境 componentDidCatch在当前组件可以捕获，父级组件不能捕获子组件错误

### 期望行为

可以捕获子组件错误

### 系统信息

Taro CLI 1.3.9 environment info:
    System:
      OS: macOS High Sierra 10.13.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.13.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.2.15 => 1.2.15
      @tarojs/cli: 1.2.15 => 1.2.15
      @tarojs/components: 1.2.15 => 1.2.15
      @tarojs/mobx: 1.2.15 => 1.2.15
      @tarojs/mobx-h5: 1.2.15 => 1.2.15
      @tarojs/plugin-babel: 1.2.15 => 1.2.15
      @tarojs/plugin-csso: 1.2.15 => 1.2.15
      @tarojs/plugin-sass: 1.2.15 => 1.2.15
      @tarojs/plugin-uglifyjs: 1.2.15 => 1.2.15
      @tarojs/router: http://npm.corp.yiran.com/@parojs%2frouter/-/router-1.2.15-2.tgz => 1.2.15-2
      @tarojs/taro: 1.2.15 => 1.2.15
      @tarojs/taro-alipay: 1.2.15 => 1.2.15
      @tarojs/taro-h5: 1.2.15 => 1.2.15
      @tarojs/taro-swan: 1.2.15 => 1.2.15
      @tarojs/taro-weapp: 1.2.15 => 1.2.15
      @tarojs/webpack-runner: 1.2.15 => 1.2.15
      eslint-config-taro: 1.2.15 => 1.2.15
      eslint-plugin-taro: 1.2.15 => 1.2.15
      nerv-devtools: ^1.3.9 => 1.3.9
      nervjs: ^1.3.9 => 1.3.9
      react: ^16.7.0 => 16.7.0
    npmGlobalPackages:
      typescript: 3.3.3

**Comment by shenghanqin** [comment]
@Hardcore0331 cli版本与业务仓库版本不一致？建议将Taro cli版本和业务版本都升级到最新版本。

**Comment by Hardcore0331** [comment]
> @Hardcore0331 cli版本与业务仓库版本不一致？建议将Taro cli版本和业务版本都升级到最新版本。

正在升级哈
