### ISSUE TITLE
微信小程序层级深的组件调用this.forceUpdate触发render失效

### ISSUE THREAD

**Issue by crimson968** [NervJS/taro#4892]
### 问题描述

封装form表单时遇到的问题，微信小程序层级深的组件调用this.forceUpdate触发render失效

### 复现步骤

使用redux，state的属性层级比较深的时候修改最深层的属性不会触发render更新

### 期望行为

在微信小程序端调用this.forceUpdate能触发render更新或提供api触发render更新

**Comment by shenghanqin** [comment]
@crimson968 首先以我开发微信小程序和抖音小程序的经验，this.forceUpdate尽量减少使用。我在不使用的前提下，页面更新还是挺准确的。用了反而浪费一次渲染，还有可能触发更多问题。

**Comment by crimson968** [comment]
因为redux的state的更新是类似浅克隆的，暂时的解决方式是reducers的时候同步更新一个额外定义的最外层字符串属性

**Comment by shenghanqin** [comment]
在最近的修改中，有pr将对象克隆变成了深拷贝，你可以等待一下。
