### ISSUE TITLE
安装@tarojs/cli出现错误

### ISSUE THREAD

**Issue by seven-zero** [NervJS/taro#4894]
- 系统：mac
- node: v10.5.0
- npm: 6.1.0

命令行 npm install -g @tarojs/cli
```
npm install -g @tarojs/cli
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated eslint-plugin-typescript@0.12.0: Deprecated: Use @typescript-eslint/eslint-plugin instead
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
...
```
命令行 taro init myApp
```
command not found: taro
```
搜索类似问题，未解决...
帮我看下，谢谢

**Comment by xiaohaoo** [comment]
我用的是npx，我也是command not found: taro问题，请问该怎么解决呢？

**Comment by luckyadam** [comment]
https://www.google.com/search?q=mac+npm+global+packages+not+found&oq=mac+npm+&aqs=chrome.1.69i57j69i59j0l4.4807j0j7&sourceid=chrome&ie=UTF-8

**Comment by SilentFlute** [comment]
- 系统: windows
- node: v12.16.3
- npm: 6.14.4
- yarn: 1.22.4

使用`yarn global add @tarojs/cli@next`装的这个版本的:
`
{
  "dependencies": {
    "@tarojs/cli": "^3.0.0-rc.6"
  }
}
`
然后vs code中使用`taro --version`, `bash`中如下提示:
`bash: taro: command not found`
然后我设置了一个系统环境变量:
`C:\Users\wujie\AppData\Local\Yarn\bin`
接着奇怪的事发生了, 同一个目录下:
- vs code中使用`gti bahs`依然提示命令找不到
- 直接右键`git bash here`就能正常返回`👽 Taro v3.0.0-rc.6`

摸不着头脑......
然后就只有在非vs code的bash中初始化项目, 但我发现初始化的时候用箭头选一些配置时, 按了下键, 但是bash中的标识不会相应地往下移动, 但是结果是正确的, 就是说要自己心里急着按了几下, 选中的是哪一个...

**Comment by SilentFlute** [comment]
然后重启一下电脑, 之后就正常了...

**Comment by SilentFlute** [comment]
> * 系统: windows
> * node: v12.16.3
> * npm: 6.14.4
> * yarn: 1.22.4
> 
> 使用`yarn global add @tarojs/cli@next`装的这个版本的:
> `{ "dependencies": { "@tarojs/cli": "^3.0.0-rc.6" } }`
> 然后vs code中使用`taro --version`, `bash`中如下提示:
> `bash: taro: command not found`
> 然后我设置了一个系统环境变量:
> `C:\Users\用户名\AppData\Local\Yarn\bin`
> 接着奇怪的事发生了, 同一个目录下:
> 
> * vs code中使用`gti bahs`依然提示命令找不到
> * 直接右键`git bash here`就能正常返回`👽 Taro v3.0.0-rc.6`
> 
> 摸不着头脑......
> 然后就只有在非vs code的bash中初始化项目, 但我发现初始化的时候用箭头选一些配置时, 按了下键, 但是bash中的标识不会相应地往下移动, 但是结果是正确的, 就是说要自己心里急着按了几下, 选中的是哪一个...

关于箭头移动不起作用的问题, 我搜了一下似乎是win下git bash的锅, 基本都有这个问题, 解决方法:
1. 使用win自带的命令行工具
2. 在vs code中使用git bash
