### ISSUE TITLE
android手机使用taro-code生成条码有时不成功

### ISSUE THREAD

**Issue by Grady1986** [NervJS/taro#4895]
android上使用taro-code中的<BarCode> 组件生成条码不成功
 <View className={'barCodeQrBox'}>
            <Barcode text={`${num}`} width={250} height={80}/>
            <WhiteSpace/>
            <Text className={'text-15 bold'}>{num}</Text>
            <WhiteSpace/>
            <QRCode text={num} size={150}/>
            <WhiteSpace/>
            <Text className={'text-15 bold'}>使用时，向营业员出示该二维码</Text>
          </View>

![image](https://user-images.githubusercontent.com/9866852/69340437-79727180-0ca2-11ea-8336-c2006212287c.png)

**Comment by shenghanqin** [comment]
请使用Taro info给出完整信息，并且说明是什么小程序？

**Comment by Grady1986** [comment]
微信小程序
引用了import { Barcode, QRCode } from 'taro-code';

**Comment by shenghanqin** [comment]
请提供cli、taro库版本，完整的用taro info来获取！

**Comment by Grady1986** [comment]
@tarojs/taro": "1.3.22
npm install taro-code

**Comment by shenghanqin** [comment]
全局cli也是这个版本吗？
