### ISSUE TITLE
微信小程序如何绑定children组件的事件

### ISSUE THREAD

**Issue by jiangzm** [NervJS/taro#4899]
### 问题描述

this.props.children 在父组件中不能直接使用，想请问下如何在父组件绑定子组件事件呢

**Comment by Garfield550** [comment]
使用 Ref：https://nervjs.github.io/taro/docs/ref.html#docsNav

**Comment by jiangzm** [comment]
已经在父组件套了一层View，把事件绑在了wrapper层
`
  render() {
    return  (
      <View 
        onClick={this.openLocation}
        style={this.props.wrapperStyle}
        className={this.props.wrapperClass}
      >
        { this.props.children }
      </View>
    )
  }
`
