### ISSUE TITLE
[建议升级至1.3.29或之后的版本]map中生成的PureComponent子组件props变化后无法更新

### ISSUE THREAD

**Issue by xn330125** [NervJS/taro#4901]
### 问题描述

map中生成的PureComponent子组件props变化后无法更新
### 复现步骤

子组件
```jsx
class A extends PureComponent {
    change = () => {
        this.props.onChange(this.props.index);
    }
    render() {
        return (
            <View onClick={this.change}>{this.props.a}</View>
        );
    }
}
```

```jsx
class Index extends PureComponent {
    change = (a) => {
        this.setState({ a });
        console.log(a);
    }
    render() {
        <View className='index'>
                {
                    [0, 1].map(item => <A a={this.state.a} index={item} onChange={this.change}></A>)
                }
        </View>
    }
}
```

点击子组件后，无法触发更新，但是如果子组件是继承Component就没有问题

### 系统信息

 Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.25 
      @tarojs/cli: 1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/mobx: 1.3.25 => 1.3.25 
      @tarojs/mobx-h5: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.3.9 => 1.3.9 
      nervjs: ^1.3.9 => 1.3.9 
      react: ^16.7.0 => 16.7.0 
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息

map中生成的compid发生变化触发子组件compid observer，使得props更新。而propsManager触发的更新在nextTick中执行，此时props已经被更新了，就没有通过componentShouldUpdate的检查

**Comment by shenghanqin** [comment]
在1.3.29已经做了相关修改了。我先关掉这个bug，如果还有问题，你可以重新打开。
