### ISSUE TITLE
Taro.createVideoContext() 在h5下无法获得video上下文

### ISSUE THREAD

**Issue by Phlen** [NervJS/taro#4904]
### 问题描述
Taro.createVideoContext() 在h5下无法获得video上下文，在小程序上正常
![image](https://user-images.githubusercontent.com/8215182/69475275-24e80700-0e06-11ea-931e-8866d56c2804.png)
![image](https://user-images.githubusercontent.com/8215182/69475280-392c0400-0e06-11ea-991b-e028ae9171bc.png)

![image](https://user-images.githubusercontent.com/8215182/69475282-3fba7b80-0e06-11ea-9aed-0216c3d93cfa.png)

### 复现步骤
```js
 const videoContext = Taro.createVideoContext(id)
        console.log(videoContext)
```

### 期望行为
在h5上能正常取的video上下文

### 补充信息
Taro 1.3.22

**Comment by Littly** [comment]
```js
  const videoContext = Taro.createVideoContext(id)
  console.log(videoContext)
```

这段代码的上下文是怎样的？

**Comment by wenjinhua** [comment]
请问现在解决了吗？
