### ISSUE TITLE
页面setState的时候，页面自定义组件的compid即使没变也要setData？

### ISSUE THREAD

**Issue by lukezhang001** [NervJS/taro#4905]
### 问题描述

页面setState的时候，页面自定义组件的compid即使没变也要setData，导致会有多余setData影响性能

### 复现步骤

页面中有自定义组件，随便setState都会出现

### 期望行为

自定义组件，数据不变不出现setData，虽然用shouldComponentUpdate也能解决，但是感觉没必要，taro-ui的组件很多也没加shouldComponentUpdate

### 报错信息

无

### 系统信息

Taro v1.3.19

### 补充信息

查看taro-weapp->util->diffObjToPath 方法中，没有对compid比较，每次都会赋值进去，这样即使数据没变，也会多一条setData，
```js
 if (/^\$compid__/.test(key)) {
      res[targetKey] = toItem
    } else if (toItem === fromItem) {
```

这个不比较的原因是什么

**Comment by zhongzhong0505** [comment]
有解决方案了么

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。
