### ISSUE TITLE
ScrollView 组件 缺少 enable-flex 属性

### ISSUE THREAD

**Issue by lonquan** [NervJS/taro#4908]
### 问题描述

[https://taro-docs.jd.com/taro/docs/components/viewContainer/scroll-view.html](ScrollView) 组件缺少 EnableFlex 属性

### 复现步骤
无

```js
无
```

### 期望行为
增加 EnableFlex 属性

**Comment by Garfield550** [comment]
尝试提个 PR 呗

**Comment by z15649563293** [comment]
前端职位，大家可以看看啊，
地点北京，手里有各种前端职位。帮你解决职业困惑，规划职业生涯。
微信 1162733647
邮箱 1162733647@qq.com
