### ISSUE TITLE
小程序 tabBar 设置无法使用 import 导入的静态资源

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#491]
**问题描述**
小程序 tabBar 设置无法使用 import 导入的静态资源

**复现步骤**

![image](https://user-images.githubusercontent.com/23295172/44294241-cd83ee80-a2c6-11e8-85a7-2b751ae0d2ce.png)

**报错信息**
在 `node_modules/@tarojs/cli/src/weapp.js` 里的第938行代码后方直接 `throw item`,
所抛出的 `item` 为 
![image](https://user-images.githubusercontent.com/23295172/44294296-5a2eac80-a2c7-11e8-8ed0-cca2e3f44629.png)

**系统信息**

 - 操作系统: window7
 - Taro 版本 v1.0.0.beta11
 - Node.js 版本 v10.6.0

**Comment by luckyadam** [comment]
恩，因为这里的解析直解析了字符串格式的情况~可以改进
