### ISSUE TITLE
View元素animation类型定义错误

### ISSUE THREAD

**Issue by xuzpeng** [NervJS/taro#4910]
```tsx
class Demo extends Component {
  state = {
    animation: undefined
  }
render(): any {
  return <View
        animation={this.state.animation}
        style={{width: '200px', height: '200px', backgroundColor: 'red'}}>
      </View>
  }
componentDidMount(): void {
    const animation = Taro.createAnimation({
      duration: 2000,
      delay: 0,
      timingFunction: 'linear'
    });
    animation.translate('200px', 0).step({}).scale(2).step({});
    this.setState({
      animation: animation.export()
    }, () => {
      console.log(this.state.animation)
    });
  }
}
```
this.state.animation打印出来的值是{actions: [xxx, xxx]}
而common.d.ts文件定义View的animation属性为object[]，而且此处ts还未报错
然后我把common.d.ts文件中animation的类型改为{actions: object[]}也没ts报错

**Comment by shenghanqin** [comment]
@xuzpeng 请使用Taro info来提供小程序的信息，以及小程序是哪一端的？

**Comment by xuzpeng** [comment]
@shenghanqin 
👽 Taro v1.3.22
  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.25 => 1.3.25 
      @tarojs/components: 1.3.22 => 1.3.22 
      @tarojs/mobx: 1.3.22 => 1.3.22 
      @tarojs/mobx-h5: 1.3.22 => 1.3.22 
      @tarojs/mobx-rn: 1.3.22 => 1.3.22 
      @tarojs/plugin-babel: 1.3.22 => 1.3.22 
      @tarojs/plugin-csso: 1.3.22 => 1.3.22 
      @tarojs/plugin-stylus: 1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22 
      @tarojs/rn-runner: 1.3.22 => 1.3.22 
      @tarojs/router: 1.3.22 => 1.3.22 
      @tarojs/taro: 1.3.22 => 1.3.22 
      @tarojs/taro-alipay: 1.3.22 => 1.3.22 
      @tarojs/taro-h5: 1.3.22 => 1.3.22 
      @tarojs/taro-swan: 1.3.22 => 1.3.22 
      @tarojs/taro-tt: 1.3.22 => 1.3.22 
      @tarojs/taro-weapp: 1.3.22 => 1.3.22 
      @tarojs/webpack-runner: 1.3.22 => 1.3.22 
      eslint-config-taro: 1.3.22 => 1.3.22 
      eslint-plugin-taro: 1.3.22 => 1.3.22 
      nerv-devtools: ^1.4.0 => 1.5.3 
      nervjs: ^1.4.0 => 1.5.3 
      stylelint-config-taro-rn: 1.3.22 => 1.3.22 
      stylelint-taro-rn: 1.3.22 => 1.3.22 
    npmGlobalPackages:
      typescript: 3.6.3

**Comment by Garfield550** [comment]
有没有兴趣提一个 PR 来呢？

**Comment by shenghanqin** [comment]
嘻嘻，@tarojs/async-await: ^1.3.25 => 1.3.25，所有的npm包版本要一致哟。当然这个跟本问题没多大关系。

**Comment by xuzpeng** [comment]
@shenghanqin 嗯嗯 是的
@Garfield550 我试着看看能不能提个PR吧

**Comment by ZakaryCode** [comment]
fixed in #91660c246f22e075755f49ef099c68f7561eb9fb
