### ISSUE TITLE
ref的问题

### ISSUE THREAD

**Issue by YuanQuan** [NervJS/taro#4912]
最近从1.3.18更新版本到1.3.25后，页面打开报错，自定义组件中使用了ref，错误截图如下

  
![image](https://user-images.githubusercontent.com/2345176/69507773-a064c800-0f6e-11ea-8ede-e9c34cc76624.png)

怀疑是在1.3.19版本中更新的RefsArray的问题

**Comment by luckyadam** [comment]
cli 升级后项目依赖也要升级

**Comment by YuanQuan** [comment]
> cli 升级后项目依赖也要升级

嗯cli与依赖都是同步的

**Comment by shenghanqin** [comment]
@YuanQuan 看你已经提了pr啦，那我就关掉这个bug啦
