### ISSUE TITLE
组件编译问题

### ISSUE THREAD

**Issue by sunflower-tc** [NervJS/taro#4913]
引入组件时候 编译不成功
![image](https://user-images.githubusercontent.com/15952571/69511461-2ab32900-0f7b-11ea-88c2-c8a3e3068841.png)
![image](https://user-images.githubusercontent.com/15952571/69511471-3272cd80-0f7b-11ea-9454-d4ef90c5a8d0.png)
上面是组件引入的格式
ListItem 是自己建立的组件。看了写法组件没有什么出入，麻烦知道下。

**Comment by cma0314** [comment]
>

**Comment by luckyadam** [comment]
版本问题
