### ISSUE TITLE
Taro.request 处理仅有 statusCode 状态码返回的接口，这个应该怎么处理呢？

### ISSUE THREAD

**Issue by kmvan** [NervJS/taro#4914]
### 问题描述
服务端 api 返回了 204 无内容，仅有 204 状态码，body 为空的这时候 Taro.request 会 json 序列化报错。这种情况，有标准处理方案吗？文档貌似没说明这个情况的处理。

### 复现步骤
服务端 API 返回 204 状态码，且无内容。Taro.request 即报错。

1. Taro.request 发起请求
2. 服务端API 返回 204 且无内容
3. 控制台出现 json 序列化报错

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
服务端 API 返回空内容，对应的处理方法。

### 报错信息
![QQ图片20191125121602](https://user-images.githubusercontent.com/3839554/69512027-63540200-0f7d-11ea-97a9-f0c208534d59.png)

### 系统信息
👽 Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: Linux 5.3 Manjaro Linux undefined
      Shell: 5.0.11 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/bin/node
      npm: 6.13.0 - /usr/bin/npm

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
可以把参数中的 `dataType` 值设置为 `text`

**Comment by kmvan** [comment]
> 可以把请求参数中的 `dataType` 值设置为 `text`

那就是先手动判断返回再 try json序列化了哦
