### ISSUE TITLE
TypeError: (0 , _Request.fetch) is not a function

### ISSUE THREAD

**Issue by wsk1576025821** [NervJS/taro#4917]
taro框架npm run dev:alipay 报错TypeError: (0 , _Request.fetch) is not a function

**Comment by Garfield550** [comment]
请补充以下信息：
1. `taro info` 的结果
2. 可复现问题的代码

**Comment by wsk1576025821** [comment]
Taro CLI 1.3.25 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/redux: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-qq: ^1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.5 
      nervjs: ^1.5.5 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
![企业微信截图_c2bdb88d-31bf-4150-9904-1032c35e06c2](https://user-images.githubusercontent.com/20677032/69520995-fa7a8300-0f98-11ea-8dce-7caeeb3e1b5c.png)

**Comment by luckyadam** [comment]
给个 demo 看看吧
