### ISSUE TITLE
自定义组件无法传参

### ISSUE THREAD

**Issue by JjiaoLiu** [NervJS/taro#4918]
### 问题描述
自定义一个子组件<JobCard>，传递参数job，无法读取数据；如果定义JobCard.defaultProps = {
}，则页面只会显示defaultProps的定义的占位用的数据

### 复现步骤

1. 页面获取数据jobList
2. 通过map生成JobCard，赋值props
3. 页面不显示传递的props
![1574671312(1)](https://user-images.githubusercontent.com/24647907/69525362-ec316480-0fa2-11ea-892f-164824ac42f2.png)
![1574671338(1)](https://user-images.githubusercontent.com/24647907/69525365-ee93be80-0fa2-11ea-9168-3635effc0fa7.png)
![1574671355(1)](https://user-images.githubusercontent.com/24647907/69525370-f05d8200-0fa2-11ea-81c0-dc41ab36cce7.png)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

子组件能收到props

### 系统信息

  Taro CLI 1.3.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
建议升级到最新版本，并且保持 cli 与项目依赖版本一致

**Comment by JjiaoLiu** [comment]
> 
> 
> 建议升级到最新版本，并且保持 cli 与项目依赖版本一致

cli已经是最新的版本了，你指的是node吗？

**Comment by JjiaoLiu** [comment]
> 
> 
> 建议升级到最新版本，并且保持 cli 与项目依赖版本一致

我使用npm重新install了项目，问题解决了

**Comment by lxf-soul** [comment]
为啥页面间传值获取不到参数
