### ISSUE TITLE
微信小程序转Taro  错误 组件转换

### ISSUE THREAD

**Issue by woleigeququ** [NervJS/taro#4919]
### 问题描述

使用taro convert将微信小程序转taro时，出现：
错误  组件转换  C:/Users/guoqing/WeChatProjects/component/tabpager/tabpager.js
Error: 组件 C:\Users\guoqing\WeChatProjects\component\tabpager\tabpager 没有 JS 文件！
    at C:\Users\guoqing\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\convertor\index.js:521:27
    at Set.forEach (<anonymous>)
    at Convertor.traverseComponents (C:\Users\guoqing\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\convertor\index.js:507:20)
    at C:\Users\guoqing\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\convertor\index.js:495:22
    at Set.forEach (<anonymous>)
    at Convertor.traversePages 

### 复现步骤

cd C:\Users\guoqing\WeChatProjects\wenda_
taro convert

![image](https://user-images.githubusercontent.com/28921977/69527073-7d560a80-0fa6-11ea-9183-f845e3d7e77d.png)

### 期望行为

转换成功

### 报错信息

![image](https://user-images.githubusercontent.com/28921977/69527127-9c549c80-0fa6-11ea-823c-1eab5489f700.png)

### 补充信息

别的页面中用到了这个自定义组件，但在转换的时候未能成功转换。谢谢

**Comment by luckyadam** [comment]
提供一个 demo 吧

**Comment by Qiyu8** [comment]
看起来像是路径的问题，是不是有两个tabpager目录？

**Comment by woleigeququ** [comment]
只有一个 ，搞不懂为什么会这样， 我现在打算用字节跳动小程序重新写一遍了， 它好像支持直接用wx:for  wx.request这样子的指令和方法，好奇怪

**Comment by web577526282** [comment]
哇，请问这个解决了吗  碰到了同样的问题
