### ISSUE TITLE
在 package.json 中 使用 proxy 不生效

### ISSUE THREAD

**Issue by wuxudong** [NervJS/taro#492]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

在 package.json 中添加 "proxy": "http://localhost:10001", 

在业务代码中 
   使用 Taro.request({url:"/user/me"}).then(function (res) {
      console.log(res);
    })

不生效， 获取到的 res  为 taro生成 的 静态页面

**复现步骤**
[复现问题的步骤]
1. 获取 TodoMVC
2. 在 package.json 中 添加 "proxy": "http://localhost:10001"
3. 在 app.js 中添加
  componentDidMount () {
    Taro.request({url:"/user/me"}).then(function (res) {
      console.log(res);
    })
  }
4.  console 中报错

index.js?ddae:4484 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at eval (index.js?ddae:4484)

因为 实际取回了 页面的静态代码， 而不是  接口数据。

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**

服务器接口返回的数据。

**报错信息**

index.js?ddae:4484 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at eval (index.js?ddae:4484)

**系统信息**

 - 操作系统: [Mac]
 - Taro 版本 [0.0.68]
 - Node.js 版本 [v9.3.0]

**补充信息**
[可选]

同样的配置， 如果使用 create-react-app 创建的 h5 应用， 是可以生效的。

**Comment by luckyadam** [comment]
文档中有些
https://nervjs.github.io/taro/config-detail.html#h5
另外，你的版本有点旧啊，可以升级到 1.0.0-beta.11

**Comment by wuxudong** [comment]
是指用 

```
devServer: {
    contentBase: path.join(__dirname, "dist"),
    compress: true,
    port: 9000,
    proxy: {
        '/api': {
            target: 'http://localhost:3000',
            secure: false
        }
    }
}

```

这样的方式么？

**Comment by luckyadam** [comment]
@wuxudong 是的

**Comment by weilongfei** [comment]
https://nervjs.github.io/taro/config-detail.html#h5 已经失效了

**Comment by weilongfei** [comment]
我去 配在config index.js 里面的
h5: {
    publicPath: '/',
    staticDirectory: 'static',
    module: {
      postcss: {
        autoprefixer: {
          enable: true
        }
      }
    },
    devServer:{
      proxy: {
        ......
      }
    }
  }
