### ISSUE TITLE
Input,TextArea组件文档没有介绍小程序端的兼容状况

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#4925]
### 问题描述
Input,TextArea组件文档没有介绍小程序端的兼容状况

### 复现步骤
亲爱的开发者们您好，我遇到的问题如下

1. 我想要使用Input,Textarea等组件，并想要运用于小程序中
2. 查阅taro中该组件相关的文档后，没有只有H5/RN端介绍了兼容性差异，而微信，支付宝等小程序端没有介绍兼容情况，如下图所示
<img width="535" alt="屏幕快照 2019-11-26 下午12 05 43" src="https://user-images.githubusercontent.com/23090498/69598763-63b7d000-1045-11ea-81ac-ac205d6f312a.png">

3.请问能够补充一下吗
4. 非常感谢！

### 期望行为
能够在Input,Textarea文档中看到组件props在小程序端的支持情况

**Comment by Garfield550** [comment]
你好，这两个平台都支持的。

**Comment by xiryrg1** [comment]
#5030

**Comment by xiryrg1** [comment]
@Garfield550
