### ISSUE TITLE
自定义列表组件循环的时候渲染自定义 render 只渲染一条数据

### ISSUE THREAD

**Issue by imaxing** [NervJS/taro#4928]
### 列表组件

![image](https://user-images.githubusercontent.com/26427785/69622634-523dea80-107c-11ea-97f7-6af6a6547adf.png)

### 组件调用

![image](https://user-images.githubusercontent.com/26427785/69622666-64b82400-107c-11ea-8d15-41ed7cddf380.png)

### 渲染错误截图

![image](https://user-images.githubusercontent.com/26427785/69622722-7ac5e480-107c-11ea-8277-b9fe9a3f4f5a.png)

**Comment by Chen-jj** [comment]
@imaxing 贴完整代码，文本形式。

**Comment by imaxing** [comment]
#### 就是一个组件内部渲染列表, 调用外部自定义 render 方法的场景
```
// 调用组件
<Drag
    onItemClick={(item) => console.log(item)}
    columns={1}
    listData={listData}
    topSize={110}
    bottomSize={380}
    renderItem={
       <View className='chart-item'>
          <View className='item-title'>{item.data.description}123</View>
          <View className='item-sort-icon'>
              <CpIcon library='' type='sort' size={35} color='#C0C4CC' bold />
          </View>
       </View>
    }
   onChange={this.sortChange}/>
```



```
// 组件内部
{list.map((item, index) => {
    return (
      <View key={index}  onClick={this.itemClick}>
          <View className={cs(columns >= 2 ? 'row' : 'cell')}>
             {this.props.renderItem}
         </View>
     </View>
    )})
}
```

@Chen-jj

**Comment by Chen-jj** [comment]
@imaxing 看来是微信小程序的 slot 不支持被用于循环，因此这种写法暂时不能支持。

![image](https://user-images.githubusercontent.com/11807297/70677734-f5247480-1cca-11ea-9d45-1da990b85abf.png)

![image](https://user-images.githubusercontent.com/11807297/70677750-01a8cd00-1ccb-11ea-82a5-748caaaf7a05.png)

**Comment by imaxing** [comment]
看来微信不更新就没办法支持了 ☹️

**Comment by Chen-jj** [comment]
Taro 3 可以支持，大概年后吧。

**Comment by guxingke201** [comment]
看了下源码，render props是通过事件实现的，这个问题是taro的bug，和小程序没关系吧，希望taro3能修复
