### ISSUE TITLE
深层嵌套自定义子组件boundingClientRect 获取不到节点信息

### ISSUE THREAD

**Issue by sprout-echo** [NervJS/taro#4930]
### 问题描述
在页面深层嵌套的子组件内 获取节点的信息 获取到的是null
版本是 1.3.18

### 复现步骤

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
Taro.createSelectorQuery().select(`.pro${detailId}`).boundingClientRect((rect) => {
      console.log(rect);
     Taro.pageScrollTo({
      scrollTop: rect.top,
      duration: 0
    })
 }).exec();


```

### 期望行为

期望可以在深层嵌套的内部子组件内获取到

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@sprout-echo 什么是深层嵌套，多深叫深层，原生是否有问题

**Comment by glacjay** [comment]
我也遇到这个问题了，在页面中获取页面元素的节点信息是可以得到的，在页面所用的自定义组件中获取该组件中元素的节点信息就只会返回 null。

**Comment by glacjay** [comment]
sorry，加了 `.in(this.$scope)` 之后解决了。打扰了

**Comment by sprout-echo** [comment]
> sorry，加了 `.in(this.$scope)` 之后解决了。打扰了

那你用的不是 hooks吧

**Comment by glacjay** [comment]
@sprout-echo 不是，我还没用过 Hooks 功能。

**Comment by robinv8** [comment]
我使用了Hooks,获取不到节点信息。
