### ISSUE TITLE
希望trao官方能跟进一下 支付宝的分包功能 现在的不支持支付宝分包加载

### ISSUE THREAD

**Issue by BJChuang** [NervJS/taro#4934]
![image](https://user-images.githubusercontent.com/28973903/69701066-01370080-1127-11ea-997a-54139f13bfc9.png)

**Comment by Chen-jj** [comment]
@BJChuang 一直支持

**Comment by YouMaster930615** [comment]
> @BJChuang 一直支持
一直支持？ 我刚下载了一个初始化模板  新建了分包页面 跳转就提示找不到页面  ，您是怎么操作  分享出来借鉴一下

**Comment by Chen-jj** [comment]
@YouMaster930615 很久前就有支付宝分包的一些 issue，有些附带着 demo，自己翻翻吧。
