### ISSUE TITLE
引入第三方 npm 包报错 process is not defined

### ISSUE THREAD

**Issue by dpyzo0o** [NervJS/taro#4935]
### 问题描述

尝试在 taro 引入第三方状态管理库 [easy-peasy](https://github.com/ctrlplusb/easy-peasy), 控制台报错 `process is not defined`.

### 复现步骤

引入 easy-peasy 库替代 redux, model 定义如下

```js
import { action, thunk, computed } from 'easy-peasy'

const delay = sec => new Promise(resolve => setTimeout(resolve, sec * 1000))

export default {
  count: 0,

  countSquared: computed(state => state.count * state.count),

  increment: action(state => {
    state.count += 1
  }),

  decrement: action(state => {
    state.count -= 1
  }),

  asyncIncrement: thunk(async actions => {
    await delay(1)
    actions.increment()
  }),

  asyncDecrement: thunk(async actions => {
    await delay(2)
    actions.decrement
  }),
}
```

这里引入了 `computed`方法，该方法在 easy-peasy 的实现中调用了 `process.env.NODE_ENV`, 具体见[这里](https://github.com/ctrlplusb/easy-peasy/blob/81e3c0ace9daa901a69053f7b3f86de6201a16ad/src/computed-properties.js#L28). 如果去掉 `computed` 方法引用，该库可以正常在 taro 中运行。

### 期望行为

taro 可以支持该库的 `computed` 方法

### 报错信息

<img width="769" alt="Screen Shot 2019-11-27 at 15 24 16" src="https://user-images.githubusercontent.com/24768249/69702355-021d6180-112a-11ea-8af3-4cda0885c5ad.png">

### 系统信息

Taro CLI 1.3.25 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.26 => 1.3.26 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/redux: ^1.3.26 => 1.3.26 
      @tarojs/redux-h5: ^1.3.26 => 1.3.26 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-qq: 1.3.25 => 1.3.25 
      @tarojs/taro-quickapp: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.0 => 1.5.5 
      nervjs: ^1.5.0 => 1.5.5 
      react: ^16.12.0 => 16.12.0 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
    npmGlobalPackages:
      typescript: 3.6.3

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
文档：https://nervjs.github.io/taro/docs/config-detail.html#defineconstants
全局的config里面加上
```
defineConstants: {
    'process.env.SERVER_ENV': JSON.stringify(process.env.SERVER_ENV),
    'process.env.APPID_ENV': JSON.stringify(process.env.APPID_ENV),
  },
```

**Comment by dpyzo0o** [comment]
@shenghanqin 你好，我试了你的方法 

```js
```

**Comment by dpyzo0o** [comment]
发现是 easy-peasy 引用了 memoiserific 这个库，然后这个库里面有这样一行代码

<img width="582" alt="Screen Shot 2019-11-27 at 17 13 03" src="https://user-images.githubusercontent.com/24768249/69709861-33e9f480-1139-11ea-9499-de187b75353a.png">

但是我加入了这个定义还是会报错

```js
defineConstants: {
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  'process.env.FORCE_SIMILAR_INSTEAD_OF_MAP': '""',
},
```

@shenghanqin

**Comment by dpyzo0o** [comment]
请问有好的解决办法吗

**Comment by bluescurry** [comment]
> 请问有好的解决办法吗

请求最后这个问题解决吗，我也想在 taro 中使用 easy-peasy

**Comment by dpyzo0o** [comment]
> > 请问有好的解决办法吗
> 
> 请问最后这个问题解决了吗，我也想在 taro 中使用 easy-peasy

不好意思，这个问题后来没有深入探究了，不过我建议你可以尝试用用 redux toolkit, 这个和taro用起来没什么问题

**Comment by bluescurry** [comment]
> > > 请问有好的解决办法吗
> > 
> > 
> > 请问最后这个问题解决了吗，我也想在 taro 中使用 easy-peasy
> 
> 不好意思，这个问题后来没有深入探究了，不过我建议你可以尝试用用 redux toolkit, 这个和taro用起来没什么问题

我大概看了下 redux toolkit，我想用 easy-peasy 就是因为 1. 减少样板；2. 使用类 hooks 的方式。而 redux toolkit 看着并不具备这两点。。。

**Comment by dpyzo0o** [comment]
@bluescurry 你说的是这个吗 https://redux-toolkit.js.org/, redux toolkit 设计就是为了减少样板代码呀，使用也都是 hooks 的形式。redux toolkit 是redux现在主要的维护者弄的，就我使用体验上来说比 easy-peasy 好不少，redux toolkit 的 ts 支持非常棒

**Comment by bluescurry** [comment]
> @bluescurry 你说的是这个吗 https://redux-toolkit.js.org/, redux toolkit 设计就是为了减少样板代码呀，使用也都是 hooks 的形式。redux toolkit 是redux现在主要的维护者弄的，就我使用体验上来说比 easy-peasy 好不少，redux toolkit 的 ts 支持非常棒

好的，那我再好好研究一下这个方案，多谢多谢！
