### ISSUE TITLE
无法为组件本身的宿主元素添加类

### ISSUE THREAD

**Issue by infinnie** [NervJS/taro#4936]
### 问题描述
引用某一组件的页面或组件无法为被引用组件的 **宿主元素** 添加类名。

### 复现步骤

1. 编写一个组件和一个页面，并在页面之中引用该组件。

```jsx
// component.js
export default function() {
    return <View>content goes here</View>;
}
```
```jsx
// page.js
import Component from "./component";
export default function() {
    return <Component className="thing" />;
}
```

2. 编译为微信小程序。

### 期望行为

生成
```html
<component class="thing" />
```

### 报错信息

生成 `<component />` 而没有需要的类名 `thing`

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by infinnie** [comment]
我觉得我可能加错分类了…

**Comment by Garfield550** [comment]
1. 使用全局样式类：https://nervjs.github.io/taro/docs/component-style.html#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%E7%B1%BB

2. 给子组件手动添加 `className` 属性

**Comment by infinnie** [comment]
> 1. 使用全局样式类：https://nervjs.github.io/taro/docs/component-style.html#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%E7%B1%BB
> 2. 给子组件手动添加 `className` 属性

问题是我需要添加样式的是 **宿主元素** 而不是子组件本身的元素

**Comment by Garfield550** [comment]
我假设你的目标平台是微信小程序。

![image](https://user-images.githubusercontent.com/3471836/69715167-c347d580-1142-11ea-9d9a-054227cc3672.png)

如果你是要在 `at-avatar` 这一层加样式的话，暂时没有办法。

![image](https://user-images.githubusercontent.com/3471836/69715420-2d607a80-1143-11ea-83ff-d194c2cbf0e0.png)

并且加的样式也不起作用。

**Comment by infinnie** [comment]
其实给宿主元素加的样式是起作用的…

为什么你没看到作用的原因是 shadow DOM 宿主元素默认的 display 是 inline, 如果给他加一个 `display: block`, 或者这个宿主元素在一个 flex container 之内，就可以看到宿主元素被正常添加样式了…

**Comment by infinnie** [comment]
![image](https://user-images.githubusercontent.com/8168391/69769373-8d950200-11bf-11ea-8c61-bcd3e034f364.png)
_(:3

**Comment by infinnie** [comment]
似乎可以考虑一下用 CSS variables 来实现类似功能…

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
