### ISSUE TITLE
macos 10.15.1 安装报错

### ISSUE THREAD

**Issue by relaxfinger** [NervJS/taro#4937]
node 12.13.1,    npm 6.13.1

命令：
 npm i -g @tarojs/cli

结果：
npm WARN deprecated babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated eslint-plugin-typescript@0.12.0: Deprecated: Use @typescript-eslint/eslint-plugin instead
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tarojs/taroize@1.3.26.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@tarojs/cli'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/relaxfinger/.npm/_logs/2019-11-27T07_37_25_531Z-debug.log

**Comment by shenghanqin** [comment]
@relaxfinger 最新版本是1.3.26，但不代表npm仓库上就已经同步了全部的依赖库，你等半天或者一天再说？

你可以尝试npm i -g @tarojs/cli@1.3.25，安装旧版本。

**Comment by shenghanqin** [comment]
我是感觉，npm先发好，cnpm或者其他平台是同步npm的，有滞后性。
