### ISSUE TITLE
taro使用hooks的语法报错？

### ISSUE THREAD

**Issue by syyzz3** [NervJS/taro#4938]
![微信截图_20191127160505](https://user-images.githubusercontent.com/11385973/69705485-a2768480-1130-11ea-9830-50a39156ed59.png)
![微信截图_20191127160528](https://user-images.githubusercontent.com/11385973/69705488-a2768480-1130-11ea-9f67-1c2ffaba3dff.png)
taro使用hooks的语法为什么会报错？

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
