### ISSUE TITLE
在小程序修改轮播组件的 指示点的位置 ！！！急

### ISSUE THREAD

**Issue by BJChuang** [NervJS/taro#4940]
在小程序修改轮播组件的 指示点的位置 看文档没开放这个属性，想通过css覆盖但是试了各种姿势就是不好试，想问下怎么才能修改
![image](https://user-images.githubusercontent.com/28973903/69710058-9642f500-1139-11ea-81a8-d584bae4b6d4.png)

**Comment by Inori-Lover** [comment]
为什么没价格在线等（笑

这个东西一般的做法是关掉indicatorDots然后用绝对定位等手动做一个模拟的。

**Comment by luckyadam** [comment]
在微信小程序端用的就是原生的小程序组件，小程序支持，taro 就支持
