### ISSUE TITLE
微信小程序插件开发,在启用压缩的情况下,taro build --plugin weapp不能实现压缩混淆

### ISSUE THREAD

**Issue by darkfiredarkhalo** [NervJS/taro#4948]
### 问题描述
在微信小程序插件开发过程中,为了保护插件源码安全,想在build时对build生成的源码进行一次压缩混淆,在修改`config/index.js`开启压缩的情况下,执行`taro build --plugin weapp`,生成的目标源码并未压缩混淆,尝试使用`NODE_ENV=production taro build --plugin weapp`和`NODE_ENV=production BUILD_ENV=development taro build --plugin weapp`,依旧不起作用

### 复现步骤
1,修改`config/index.js`,添加  

``` 
uglify: {
      enable: true,
      config: {
        sourceMap: true,
        compress: {
          comments: false,
        },
        ascii_only: true
      }
    },
csso: {
      enable: true,
      config: {
        sourceMap: true
      }
    }  
```  

2,在项目根目录下执行`taro build --plugin weapp`,执行完毕查看`plugin/`和`miniprogram/`目录下文件变化

### 期望行为

在启用压缩的情况下,能对build后的代码进行正常的压缩混淆

### 报错信息

无

### 系统信息

System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.25 => 1.3.25 
      @tarojs/components: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-babel: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-csso: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/plugin-uglifyjs: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/router: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-alipay: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-h5: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-swan: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-tt: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/taro-weapp: 1.3.0-beta.5 => 1.3.0-beta.5 
      @tarojs/webpack-runner: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-config-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      eslint-plugin-taro: 1.3.0-beta.5 => 1.3.0-beta.5 
      nervjs: ^1.3.9 => 1.5.5 

### 补充信息
项目目录结构如图

<img width="629" alt="dir" src="https://user-images.githubusercontent.com/13959162/69778678-2dfb1e80-11e0-11ea-9d39-9a2dddd4262c.png">

**Comment by Garfield550** [comment]
你的依赖还都在 `1.3.0-beta.5`，先升级一下

**Comment by darkfiredarkhalo** [comment]
@Garfield550 升级后依旧不起作用,新的依赖信息如下
```  

Taro CLI 1.3.0-beta.5 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.26 => 1.3.26 
      @tarojs/components: 1.3.26 => 1.3.26 
      @tarojs/plugin-babel: 1.3.26 => 1.3.26 
      @tarojs/plugin-csso: 1.3.26 => 1.3.26 
      @tarojs/plugin-uglifyjs: 1.3.26 => 1.3.26 
      @tarojs/router: 1.3.26 => 1.3.26 
      @tarojs/taro: 1.3.26 => 1.3.26 
      @tarojs/taro-alipay: 1.3.26 => 1.3.26 
      @tarojs/taro-h5: 1.3.26 => 1.3.26 
      @tarojs/taro-swan: 1.3.26 => 1.3.26 
      @tarojs/taro-tt: 1.3.26 => 1.3.26 
      @tarojs/taro-weapp: 1.3.26 => 1.3.26 
      @tarojs/webpack-runner: 1.3.26 => 1.3.26 
      eslint-config-taro: 1.3.26 => 1.3.26 
      eslint-plugin-taro: 1.3.26 => 1.3.26 
      nervjs: ^1.3.9 => 1.5.5  
```

**Comment by Garfield550** [comment]
配置写错地方了 `plugins.uglify`

http://taro-docs.jd.com/taro/docs/config-detail.html#pluginsuglify

**Comment by Garfield550** [comment]
贴一下完整配置文件

**Comment by darkfiredarkhalo** [comment]
@Garfield550 
```   
const config = {
  projectName: 'plugin_gusto',
  date: '2019-11-25',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'miniprogram',
  plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread'
      ]
    },
    uglify: {
      enable: true,
      config: {
        sourceMap: true,
        compress: {
          comments: false,
          drop_console: true,
          drop_debugger: false,
          pure_funcs: ['console.log']
        },
        ascii_only: true
      }
    },
    csso: {
      enable: true,
      config: {
        sourceMap: true
      }
    }
  },
  defineConstants: {
  },
  copy: {
    patterns: [
      { from: 'src/pages/assert/', to: 'miniprogram/pages/assert/' }
    ],
    options: {
    }
  },
  weapp: {
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: [
              'last 3 versions',
              'Android >= 4.1',
              'ios >= 8'
            ]
          }
        },
        pxtransform: {
          enable: true,
          config: {

          }
        },
        url: {
          enable: true,
          config: {
            limit: 10240 // 设定转换尺寸上限
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: [
              'last 3 versions',
              'Android >= 4.1',
              'ios >= 8'
            ]
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  }
}

module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}

```

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/69925441-2fcc2700-14eb-11ea-92da-859ca6bd7180.png)
之前忽略了 CLI 的版本信息，你先更新一下 CLI 到 1.3.26 试一下。

**Comment by darkfiredarkhalo** [comment]
收到，我试试

**Comment by darkfiredarkhalo** [comment]
@Garfield550 cli升级后压缩可以正常了，但是有两个问题：  
1，uglify配置`comments: false`移除注释，提示comments不支持；配置移除`console.log`不起作用；  
2，升级cli后，执行build，有警告`警告  依赖安装  项目依赖 @tarojs/taro-plugin 未安装，或安装有误！`,执行`yarn add @tarojs/taro-plugin`却提示在npm中找不到这个模块

**Comment by Garfield550** [comment]
> @Garfield550 cli升级后压缩可以正常了，但是有个问题： 升级cli后，执行build，有警告`警告 依赖安装 项目依赖 @tarojs/taro-plugin 未安装，或安装有误！`,执行`yarn add @tarojs/taro-plugin`却提示在npm中找不到这个模块

这是一个已知问题，从目前的反馈来看暂不影响编译结果，我们会尽快解决，请等待后续更新。#4965

**Comment by darkfiredarkhalo** [comment]
收到，非常感谢！
