### ISSUE TITLE
 Has this problem been raised, has anyone ever met it?

### ISSUE THREAD

**Issue by 1527706977** [NervJS/taro#4950]
![}AE6J(G21B`7N0(O{61AIGM](https://user-images.githubusercontent.com/43232701/69784115-f98f5e80-11ef-11ea-9963-4d9a85bef59b.png)

**Comment by 1527706977** [comment]
执行RN时候，一直出现这个bug

**Comment by Pines-Cheng** [comment]
项目里存在多个 React Native 依赖。
