### ISSUE TITLE
Taro H5项目，使用 Taro. navigateTo 跳转页面，一直创建新 dom，这问题啥时候优化？

### ISSUE THREAD

**Issue by Go7hic** [NervJS/taro#4958]
### 问题描述

Taro H5 项目，使用 Taro. navigateTo 跳转页面，一直创建新 page dom，这问题啥时候优化？我看之前有人提了还没好，不知道官方暂时推荐的做法是啥？一直创建 dom 肯定不行的，暂时只能在 h5 端通过 location 跳转，就和多页面效果一样的了...

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
这并不是个问题，通过 navigateTo 打开是一个新的页面，在小程序端也是如此「[参考](https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.navigateTo.html)」，而且小程序端还限制了页面栈最多十层

**Comment by priesty** [comment]
> 这并不是个问题，通过 navigateTo 打开是一个新的页面，在小程序端也是如此「[参考](https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.navigateTo.html)」，而且小程序端还限制了页面栈最多十层

不同页面相同classname导致样式有问题了，没有改成使用css module（历史页面太多），有什么好的方案么。小程序并没有冲突
