### ISSUE TITLE
h5端 swiper onChange 不能正确拿到state

### ISSUE THREAD

**Issue by JasLin** [NervJS/taro#4959]
### 问题描述

函数式组件下，使用swiper, onChange不能正确拿到 useState的值。 但是小程序端可以正确拿到

### 复现步骤

```js
import Taro, { useEffect, useState } from '@tarojs/taro'
import { View, Swiper, SwiperItem } from '@tarojs/components'

const Index = () => {
  const [current, setCurrent] = useState(0)
  const [text, setText] = useState('')

  console.log('text1', text)

  useEffect(() => {
    setText('rendered')
  }, [])

  const handleChange = (e) => {
    console.log('text2', text)
    setCurrent(e.detail.current)
  }

  return (
    <View>
      <Swiper
        indicatorDots
        current={current}
        onChange={handleChange}
      >
        <SwiperItem>
          <View>1asfasdfasdfadfadf</View>
        </SwiperItem>
        <SwiperItem>
          <View>2asdfasdfasdfadfadsf</View>
        </SwiperItem>
        <SwiperItem>
          <View>3asdfsdasfadfadfasdf</View>
        </SwiperItem>
      </Swiper>
    </View>
  )
}

export default Index
```

### 期望行为

滑动siwper item后，触发handleChange执行，应该拿到正确的结果是

```
text2 rendered
text1 rendered
```

但是在h5下的结果是:

```
text2 
text1 rendered
```

小程序端则是正确的

### 系统信息

👽 Taro v1.3.26

  Taro CLI 1.3.26 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.26 => 1.3.26 
      @tarojs/components: 1.3.26 => 1.3.26 
      @tarojs/plugin-babel: 1.3.26 => 1.3.26 
      @tarojs/plugin-csso: 1.3.26 => 1.3.26 
      @tarojs/plugin-sass: 1.3.26 => 1.3.26 
      @tarojs/plugin-uglifyjs: 1.3.26 => 1.3.26 
      @tarojs/router: 1.3.26 => 1.3.26 
      @tarojs/taro: 1.3.26 => 1.3.26 
      @tarojs/taro-alipay: 1.3.26 => 1.3.26 
      @tarojs/taro-h5: 1.3.26 => 1.3.26 
      @tarojs/taro-qq: ^1.3.26 => 1.3.26 
      @tarojs/taro-quickapp: ^1.3.26 => 1.3.26 
      @tarojs/taro-swan: 1.3.26 => 1.3.26 
      @tarojs/taro-tt: 1.3.26 => 1.3.26 
      @tarojs/taro-weapp: 1.3.26 => 1.3.26 
      @tarojs/webpack-runner: 1.3.26 => 1.3.26 
      eslint-config-taro: 1.3.26 => 1.3.26 
      eslint-plugin-taro: 1.3.26 => 1.3.26 
      nerv-devtools: ^1.5.3 => 1.5.3 
      nervjs: ^1.5.3 => 1.5.3 
      react: ^16.8.6 => 16.8.6 
      stylelint-config-taro-rn: 1.3.26 => 1.3.26 
      stylelint-taro-rn: 1.3.26 => 1.3.26 
    npmGlobalPackages:
      typescript: 2.9.1

**Comment by enjoyWeb** [comment]
> 欢迎提交 Issue~
> 
> 如果你提交的是 bug 报告，请务必遵循 [Issue 模板](https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)的规范，尽量用简洁的语言描述你的问题，最好能提供一个稳定简单的复现。🙏🙏🙏
> 
> 如果你的信息提供过于模糊或不足，或者已经其他 issue 已经存在相关内容，你的 issue 有可能会被关闭。
> 
> Good luck and happy coding~
请先确认issue模板是否可以打开，这样子让人怎么问问题
