### ISSUE TITLE
useReducer第二个参数在typescript下报错

### ISSUE THREAD

**Issue by yeeing** [NervJS/taro#4960]
### 问题描述

在VScode下使用typescript Taro.useReducer第二个参数报错

### 复现步骤

使用Taro.useReducer((state,action)=>{},{})时第二参数报错，文件后缀改为jsx时报错消失。

```js

const [state, dispatch] = Taro.useReducer((state, action) => { }, {})

```

### 报错信息
类型“{}”的参数不能赋给类型“void”的参数。

### 补充信息
代码正常运行，仅报错

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
Taro 3 可以直接使用 React.useReducer ，应该没有这个问题了。
