### ISSUE TITLE
有没有方法可以在父组件中获取子组件的尺寸

### ISSUE THREAD

**Issue by coderyyx** [NervJS/taro#4962]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
请给出示例源码、设想功能的源码，或其他框架的类似实现示例。

**Comment by Elliott-Hu** [comment]
> 请给出示例源码、设想功能的源码，或其他框架的类似实现示例。

我能帮忙补充一个场景吧，算是我遇到的
swiper 组件只能通过父层去设置高度，无法通过滚到到指定的swiper-item 来决定撑开的高度。
这时候就需要父组件能够主动去获取子组件的高度，进而进行设置。
onSwiperChange 方法一般在父层。

**Comment by lance-ding** [comment]
https://taro-docs.jd.com/taro/docs/apis/interface/wxml/selectorQuery_select.html
