### ISSUE TITLE
taro convert 后不能运行

### ISSUE THREAD

**Issue by Jeff-Tian** [NervJS/taro#4963]
### 问题描述
微信小程序源代码：https://github.com/fudan-mse/yiqifen
Taro 转换后：https://github.com/fudan-mse/yiqifen/tree/taro

`npm run dev:h5` 报错：

```
cd taroConvert
yarn install
npm run dev:h5

...
监听文件修改中...

🙅   Failed to compile.

./.temp/imports/TaroParsebbTmpl.js
Module not found: Can't resolve './TaroParsebcTmpl' in 'yiqifen\taroConvert\.temp\imports'
```

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/taroize.html
阅读下这个文档
