### ISSUE TITLE
taro weapp h5 在iPhone 5 下面都是白屏, 貌似不支持 Object es6新特性 (其他机型均正常显示不报错误)

### ISSUE THREAD

**Issue by czb128abc** [NervJS/taro#4964]
### 问题描述
在 iPhone 5 下面不支持  Object.values, 页面白屏
![image](https://user-images.githubusercontent.com/339385/69841179-36636000-1299-11ea-92fa-edb80a058414.png)
![image](https://user-images.githubusercontent.com/339385/69841183-395e5080-1299-11ea-90e3-c0066ba22487.png)

iPhone 5 下面都是白屏, 我看了 vConsole,应该是不支持  Object es6新特性.
h5 和小程序都有这个问题

### 复现步骤

```js
console.log(Object.values({ a: 1 }));
```

### 系统信息

Taro v1.3.26

  Taro CLI 1.3.26 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.npm-global/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.26 => 1.3.26 
      @tarojs/cli: 1.3.26 => 1.3.26 
      @tarojs/components: 1.3.26 => 1.3.26 
      @tarojs/components-rn: 1.3.26 => 1.3.26 
      @tarojs/plugin-babel: 1.3.26 => 1.3.26 
      @tarojs/plugin-csso: 1.3.26 => 1.3.26 
      @tarojs/plugin-sass: 1.3.26 => 1.3.26 
      @tarojs/plugin-uglifyjs: 1.3.26 => 1.3.26 
      @tarojs/redux: 1.3.26 => 1.3.26 
      @tarojs/redux-h5: 1.3.26 => 1.3.26 
      @tarojs/rn-runner: 1.3.26 => 1.3.26 
      @tarojs/router: 1.3.26 => 1.3.26 
      @tarojs/taro: 1.3.26 => 1.3.26 
      @tarojs/taro-alipay: 1.3.26 => 1.3.26 
      @tarojs/taro-h5: 1.3.26 => 1.3.26 
      @tarojs/taro-redux-rn: 1.3.26 => 1.3.26 
      @tarojs/taro-rn: 1.3.26 => 1.3.26 
      @tarojs/taro-router-rn: 1.3.26 => 1.3.26 
      @tarojs/taro-swan: 1.3.26 => 1.3.26 
      @tarojs/taro-tt: 1.3.26 => 1.3.26 
      @tarojs/taro-weapp: 1.3.26 => 1.3.26 
      @tarojs/webpack-runner: 1.3.26 => 1.3.26 
      eslint-config-taro: 1.3.26 => 1.3.26 
      eslint-plugin-taro: 1.3.26 => 1.3.26 
      nerv-devtools: ^1.5.5 => 1.5.5 
      nervjs: ^1.5.5 => 1.5.5 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@czb128abc iPhone 5的ios是什么版本呢？

**Comment by czb128abc** [comment]
> @czb128abc iPhone 5的ios是什么版本呢？

![image](https://user-images.githubusercontent.com/339385/69858924-07b3ac80-12ce-11ea-9b30-5f1dfbe22c96.png)

**Comment by czb128abc** [comment]
ios 9.1
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/339385/69859050-4cd7de80-12ce-11ea-90af-8c367336d72c.png)

**Comment by shenghanqin** [comment]
1. ios 9.1系统Safari本身就不支持Object.values。https://caniuse.com/#search=object.values
2. ios 9.1在国内占有率估计在1%吧，就是非常小的数字，可以忽略。
3. 如果真想兼容iOS 9.1，就得把config里面的babel设置到支持ios 9.1的情况。你要是还有疑问，就可以贴出config代码。
