### ISSUE TITLE
taro-cli升级1.3.26之后提示有错误

### ISSUE THREAD

**Issue by duyanren** [NervJS/taro#4965]
1.3.25升级到1.3.26之后提示以下警告
警告  依赖安装  项目依赖 @tarojs/taro-ui 未安装，或安装有误！
警告  依赖安装  项目依赖 @tarojs/taro-plugin 未安装，或安装有误！

**Comment by shenghanqin** [comment]
@duyanren 
请给出命令行终端那里的完整错误提示以及错误截图，以便我们判断细节。

我是有怀疑别的npm包不同步的问题，但还得不知道细节无法做出判断。

**Comment by duyanren** [comment]
1. 升级1.3.26时提示这个警告，但是我本地并没有使用taro-ui的组件

![6401575004124_ pic_hd](https://user-images.githubusercontent.com/20219141/69844978-8ba76d80-12a9-11ea-9190-acd695646941.jpg)

2. 升级1.3.26时提示这个警告，但是我本地并没有使用taro-plugin的npm包

![6411575004178_ pic_hd](https://user-images.githubusercontent.com/20219141/69845013-cc9f8200-12a9-11ea-9a4a-6f8eca43130a.jpg)

**Comment by duyanren** [comment]
> @duyanren
> 请给出命令行终端那里的完整错误提示以及错误截图，以便我们判断细节。
> 
> 我是有怀疑别的npm包不同步的问题，但还得不知道细节无法做出判断。

1. 升级1.3.26时提示这个警告，但是我本地并没有使用taro-ui的组件

![6401575004124_ pic_hd](https://user-images.githubusercontent.com/20219141/69844978-8ba76d80-12a9-11ea-9190-acd695646941.jpg)

2. 升级1.3.26时提示这个警告，但是我本地并没有使用taro-plugin的npm包

![6411575004178_ pic_hd](https://user-images.githubusercontent.com/20219141/69845013-cc9f8200-12a9-11ea-9a4a-6f8eca43130a.jpg)

**Comment by shenghanqin** [comment]
@duyanren 你这title上未说明是编译plugin，还有，也请你再输出一下心得Taro-info。
以及是不是说，你之前用的老版本的方式，在新的1.3.26上需要重新安装依赖或者修改局部配置。

**Comment by duyanren** [comment]
> @duyanren 你这title上未说明是编译plugin，还有，也请你再输出一下心得Taro-info。
> 以及是不是说，你之前用的老版本的方式，在新的1.3.26上需要重新安装依赖或者修改局部配置。

1. 上面第二张截图上编译微信插件的项目，第一张截图是开发普通小程序的项目

2. taro info相关信息

![6421575007242_ pic](https://user-images.githubusercontent.com/20219141/69846985-bd700280-12b0-11ea-9b07-36d3c4e6b457.jpg)

3. 项目依赖全都更新过了，报的这个警告并不影响实际开发，本地项目还是能运行的。只是疑惑升级完之后为什么会提示有这个警告？
