### ISSUE TITLE
jsx内对象的编译问题

### ISSUE THREAD

**Issue by yangtao00** [NervJS/taro#4966]
### 复现步骤

1. 在`jsx`代码块内下写入一下代码，并运行

```js
<View>
{
   {
     a: <View>a</View>,
     b: <View>b</View>,
   }['a']
}
</View>
```

### 期望行为

能正常编译渲染

### 报错信息

控制台报错 `ReferenceError: a is not defined`

### 系统信息

Taro CLI 1.3.0-beta.6 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.4 => 1.3.21
      @tarojs/cli: 1.3.0-beta.6 => 1.3.0-beta.6
      @tarojs/components: 1.3.2 => 1.3.2
      @tarojs/components-rn: ^1.3.0 => 1.3.21
      @tarojs/mobx: 1.3.2 => 1.3.2
      @tarojs/mobx-h5: 1.3.2 => 1.3.2
      @tarojs/mobx-rn: 1.3.2 => 1.3.2
      @tarojs/plugin-babel: 1.3.2 => 1.3.2
      @tarojs/plugin-csso: 1.3.2 => 1.3.2
      @tarojs/plugin-sass: 1.3.2 => 1.3.2
      @tarojs/plugin-uglifyjs: 1.3.2 => 1.3.2
      @tarojs/rn-runner: 1.3.2 => 1.3.2
      @tarojs/router: 1.3.2 => 1.3.2
      @tarojs/taro: 1.3.2 => 1.3.2
      @tarojs/taro-alipay: 1.3.2 => 1.3.2
      @tarojs/taro-h5: 1.3.2 => 1.3.2
      @tarojs/taro-redux-rn: ^1.3.0 => 1.3.21
      @tarojs/taro-rn: ^1.3.0 => 1.3.21
      @tarojs/taro-router-rn: ^1.3.0 => 1.3.21
      @tarojs/taro-swan: 1.3.2 => 1.3.2
      @tarojs/taro-tt: 1.3.2 => 1.3.2
      @tarojs/taro-weapp: 1.3.2 => 1.3.2
      @tarojs/webpack-runner: 1.3.2 => 1.3.2
      eslint-config-taro: 1.3.2 => 1.3.2
      eslint-plugin-taro: 1.3.2 => 1.3.2
      nervjs: ^1.4.0 => 1.5.1
      react: 16.3.1 => 16.3.1
      react-native: 0.55.4 => 0.55.4
    npmGlobalPackages:
      typescript: 3.6.3

### 补充信息

把这块代码放到 `React`下面，则可以正常运行渲染

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
你的版本太多不一致啦，请先统一cli和具体依赖到1.3.25或者1.3.26，再看看还有木有问题。

cli是Taro CLI 1.3.0-beta.6
组件也不一致
```
@tarojs/async-await: ^1.3.4 => 1.3.21
@tarojs/cli: 1.3.0-beta.6 => 1.3.0-beta.6
@tarojs/components: 1.3.2 => 1.3.2
@tarojs/components-rn: ^1.3.0 => 1.3.21
@tarojs/mobx: 1.3.2 => 1.3.2
@tarojs/mobx-h5: 1.3.2 => 1.3.2
@tarojs/mobx-rn: 1.3.2 => 1.3.2
```
