### ISSUE TITLE
渲染列表问题(ios真机)：自定义组件只有第一个render，其余没有render

### ISSUE THREAD

**Issue by timer2** [NervJS/taro#4970]
### 复现步骤

```js
import {
  View
} from '@tarojs/components'
import Taro from '@tarojs/taro'
import withWeapp from '@tarojs/with-weapp'

@withWeapp('Page')
class A extends Taro.Component {
  state = {

  }

  render() {
    console.log('render', this.props.flag);
    return (
      <View>
        {this.props.flag ? '真的' : '假的'}
      </View>
    )
  }
}

export default A

@withWeapp('Page')
class _C extends Taro.Component {
  state = {
    arr: [{id: 1}, {id: 2}, {id: 3}],
    flag: true,
  }

  fnClick = () => {
    console.log('flag = ', this.state.flag);
    this.setState({flag: !this.state.flag})
  }

  render() {
    return (
      <View>
        {this.state.arr.map(item => {
          return <A key={item.id} flag={this.state.flag} />
        })}
        {this.state.arr.map(item => {
          return <View key={item.id + '10'}> {this.state.flag ? '真真的' : '假假的'} </View>
        })}
        <AtButton onClick={this.fnClick}>点击</AtButton>
      </View>
    )
  }
}

export default _C

```

### 系统信息
👽 Taro v1.3.10

  Taro CLI 1.3.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.19.2 - ~/.nvm/versions/node/v12.4.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
    npmGlobalPackages:
      typescript: 3.7.2

**Comment by Chen-jj** [comment]
@liu-kaixin 完整代码发一下

**Comment by salody** [comment]
@Chen-jj @liu-kaixin 这个问题我也遇到了
在taro-alipay的lifecycle.js文件中有一个doUpdate的函数。
其中有一段逻辑如下
` if (component.__isReady) {
      Current.current = null
    }`
将这段逻辑注释掉后，在ios上的钉钉小程序就不会出现这个问题了。
我不太清楚为什么要在isReady后将current置为null呢？单纯的为了回收内存吗？

**Comment by DevanXU** [comment]
> @Chen-jj @liu-kaixin 这个问题我也遇到了
> 在taro-alipay的lifecycle.js文件中有一个doUpdate的函数。
> 其中有一段逻辑如下
> ` if (component.__isReady) { Current.current = null }`
> 将这段逻辑注释掉后，在ios上的钉钉小程序就不会出现这个问题了。
> 我不太清楚为什么要在isReady后将current置为null呢？单纯的为了回收内存吗？
> 
> https://github.com/salody/taro-demo.git
> 这个是一个小demo。在IOS真机上，使用钉钉小程序验证

@Chen-jj 可以麻烦优先看看这个问题吗？这个问题很多人报过，但一直没有什么进展。谢谢！

**Comment by Chen-jj** [comment]
3.x 版本没有这个问题了。
