### ISSUE TITLE
Taro v1.3.26 版本下，<Image className="audioImg" src={audioIsPlay ? playIconRed_play : playIconRed} mode="aspectFill"/>，渲染不出来

### ISSUE THREAD

**Issue by gaoshuzhen** [NervJS/taro#4973]
Taro v1.3.26 版本下，<Image className="audioImg" src={audioIsPlay ? playIconRed_play : playIconRed} mode="aspectFill"/>，渲染不出来；

**Comment by shenghanqin** [comment]
重复了，我给关掉一个。
