### ISSUE TITLE
Taro v1.3.26 版本下，<Image className="audioImg" src={audioIsPlay ? playIconRed_play : playIconRed} mode="aspectFill"/>，渲染不出来

### ISSUE THREAD

**Issue by gaoshuzhen** [NervJS/taro#4974]
Taro v1.3.26 版本下，<Image className="audioImg" src={audioIsPlay ? playIconRed_play : playIconRed} mode="aspectFill"/>，渲染不出来；只有赋值给变量，再塞进src里，才可以；请及时修复一下哦；

**Comment by shenghanqin** [comment]
请按照issue模板补充相关信息，另外，可以提供一下编译后dist目录的相应代码，作为参考依据。

**Comment by luckyadam** [comment]
没有复现此问题
