### ISSUE TITLE
转换为H5代码时, image图片地址如果是通过变量赋值的方式, 本地图片不会被正确解析为webpack模块

### ISSUE THREAD

**Issue by cejako** [NervJS/taro#4976]
### 问题描述

通过`npm run dev:h5`(或`build: h5`)将代码转换为H5代码时，对于`Image`组件，如果`src`是通过变量赋值的，并且变量对应的取值是本地图片地址，如：
```
const data = { pic: './assets/images/seat-1.png' }
<Image
      className="rank-item__avatar--image"
      src={data}
></Image>
```

渲染后的元素图片会找不到：
![image](https://user-images.githubusercontent.com/10059127/69897320-89b2dc80-1385-11ea-9990-1254266af23a.png)
![image](https://user-images.githubusercontent.com/10059127/69897327-9d5e4300-1385-11ea-908a-0aa9d04317ce.png)

### 期望行为

期望对于这种对象赋值，或者直接变量赋值，然后绑定到`Image`组件的`src`属性的场景，图片地址依然能被正确的解析

**Comment by luckyadam** [comment]
请按 Taro 文档要求引入 https://nervjs.github.io/taro/docs/static-reference.html
