### ISSUE TITLE
不支持忽略 index 文件的方式引入 index.tsx 文件

### ISSUE THREAD

**Issue by zaaack** [NervJS/taro#498]
**问题描述**
当我以相对路径引入 components/full/home-entry/index.tsx 时报错,

**复现步骤**

代码：
```ts
import FullHeader from './components/full/header'
```

提示

```
缺少npm包components/full/home-entry/index，开始安装...
```
**期望行为**
不报错

**报错信息**

见上

**系统信息**

 - 操作系统: macOS 10.13
 - Taro 版本 v1.0.0-beta.11
 - Node.js 版本 10

**补充信息**
补全后面的 index 就正常了，比如
```ts
import FullHeader from './components/full/header/index'
```

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/54011540bb66737f48e6a99e68244623a10be88a
