### ISSUE TITLE
[建议升级至1.3.29或之后的版本]1.3.26 中 Redux 的 state 复杂数据下修改时会被污染，导致页面不刷新

### ISSUE THREAD

**Issue by arvinxx** [NervJS/taro#4980]
### 问题描述

当 state 的数据结构为数组或者对象时，在 reducer 中修改后，会将 prev state 的值污染
从而导致视图页面不会刷新
### 复现步骤

1. 原数据为： {x: [{up:0},{up:2}]}
2. 在 reducer 中修改该值为 {x: [{up:1},{up:2}]}
3. 修改前和修改后的 x 都变成了 {x: [{up:1},{up:2}]}
4. 同时页面不会进行刷新

### 期望行为
在 reducer 修改前，prev state 的值不变，修改后，next state 的值改变

### 系统信息

使用的是最新的 1.3.26
如果是 1.3.25 就没有这个问题

### 补充信息
不止我一个人遇到这个问题，交流群里的小伙伴也有遇到
![image](https://user-images.githubusercontent.com/28616219/69899987-effd2680-13a8-11ea-9f97-6b94c3a3e781.png)

![image](https://user-images.githubusercontent.com/28616219/69899989-f4294400-13a8-11ea-857d-ba69cd0ef481.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
我也跟着关注一下，感觉我使用时数据更新好像也不够完全理想。嘻嘻

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/blob/master/packages/taro-redux/src/connect/connect.js#L38
taro-redux 里是直接判断是否相等的，在 reducer 里修改复杂数据，建议 copy 一份再修改

**Comment by dreamthen** [comment]
的确是有问题的，render渲染时，部分细节有问题，用1.3.25是好的，1.3.26就是不行的

**Comment by Mihawk-zhao** [comment]
我也被坑了，感觉react-redux好像不是这样的呀

**Comment by arvinxx** [comment]
> https://github.com/NervJS/taro/blob/master/packages/taro-redux/src/connect/connect.js#L38
> taro-redux 里是直接判断是否相等的，在 reducer 里修改复杂数据，建议 copy 一份再修改

这个 Issue问题的核心关注点不是 taro-redux 的判断如何，我们应该如何去写。而且是 1.3.25 运行正常的情况下在 1.3.26 下出错。请开发团队寻找一下相关的 Bug 出处，并尽快修复。感谢~

以及再针对 taro-redux 的判断逻辑做点讨论，为何不用一下 deepEqual 的判断方法？

**Comment by Chen-jj** [comment]
@arvinxx 提供一下完整可复现代码

**Comment by dreamthen** [comment]
@arvinxx 
https://github.com/NervJS/taro/commit/0892241461a72318fde4e5a3e7298101b26d113b  可以了 大佬给咱们修掉了

**Comment by shenghanqin** [comment]
你先试试最新版1.3.29，如果还有问题，你可以重新打开这个问题。
