### ISSUE TITLE
如何获取URL参数,目测目前仅支持路由传参一种方式?

### ISSUE THREAD

**Issue by pkaq** [NervJS/taro#4986]
微信重定向后会把code参数添加到#之前,无法通过路由参数的方式获取
```
http://localhost:8088/?code=021tb6Uk1lFHHn0Vx2Tk100bUk1tb6Uq&state=STATE#/pages/user/index
```
目测目前仅支持路由传参一种方式? 还是我没翻到?

**Comment by yeeing** [comment]
测试uri带#router.params能正常获取参数，您可以使用Taro.setStorage({key:'key',value:'value'})在需要参数的面页Taro.getStorage({key:'key'})的方式传参

**Comment by pkaq** [comment]
> 测试uri带#router.params能正常获取参数，您可以使用Taro.setStorage({key:'key',value:'value'})在需要参数的面页Taro.getStorage({key:'key'})的方式传参

这是微信redirect之后自己附加的参数 
1.必定会添加到 # 之前
2.不是我穿的 所以不存在setstorage传参

**Comment by luckyadam** [comment]
用 window.location.search
Taro 自己页面跳转的参数才是 this.$router.params
