### ISSUE TITLE
Taro H5 如何引入第三方jssdk

### ISSUE THREAD

**Issue by giantss** [NervJS/taro#4990]
Taro H5 如何引入第三方jssdk(链接), 求指教..

**Comment by shenghanqin** [comment]
@giantss 可以举例，需要引入那种sdk？
按说跟npm包一样用就行。或者，其他功能在issue上都可以搜搜看，有木有别人的提问。

**Comment by giantss** [comment]
@shenghanqin 比如导入 https://static.module.watch.okii.com/watch/api/xtcJSBridge.js 
应该如何导入 请教一下没有找到相关答案..

**Comment by tong233** [comment]
> 应该如何导入 请教一下没有找到相关答案..

index.html导入
<script src="https://static.module.watch.okii.com/watch/api/xtcJSBridge.js"></script>

**Comment by giantss** [comment]
> > 应该如何导入 请教一下没有找到相关答案..
> 
> index.html导入
> 
> <script src="https://static.module.watch.okii.com/watch/api/xtcJSBridge.js"></script>

这样引入了怎么在 .jsx 界面中调用呢, 比如对方给的例子是这样的, 如何获得 `xxx`对象.

```

xxx.getOpenId({
appId: '39a476cd5cbac50b1ba2435578' ,
// 调试 appId 值为 39a476cd5cbac50b1ba2435578
complete: function (res) { // 回调后执行 (调用成功、失败都会执行)
console.log(res); },
success: function (data) { // 成功回调 console.log(data);
// {"openId":["xxxxxxxxxxx","xxxxxxxxxxx"]}
},
fail: function (data,code) { // 失败回调
console.log(data); }
});
```

**Comment by luckyadam** [comment]
> > > 应该如何导入 请教一下没有找到相关答案..
> > 
> > 
> > index.html导入
> > <script src="https://static.module.watch.okii.com/watch/api/xtcJSBridge.js"></script>
> 
> 这样引入了怎么在 .jsx 界面中调用呢, 比如对方给的例子是这样的, 如何获得 `xxx`对象.
> 
> ```
> 
> xxx.getOpenId({
> appId: '39a476cd5cbac50b1ba2435578' ,
> // 调试 appId 值为 39a476cd5cbac50b1ba2435578
> complete: function (res) { // 回调后执行 (调用成功、失败都会执行)
> console.log(res); },
> success: function (data) { // 成功回调 console.log(data);
> // {"openId":["xxxxxxxxxxx","xxxxxxxxxxx"]}
> },
> fail: function (data,code) { // 失败回调
> console.log(data); }
> });
> ```

直接用啊，这不是全局对象么

**Comment by giantss** [comment]
@luckyadam 提示 `getJsBridge not find` 

1.  index.html 中导入`<script src="https://static.module.watch.okii.com/watch/api/xtcJSBridge.js"></script>`

2. 在界面中调用
```
xtc.getOpenId({
appId: '39a476cd5cbac50b1ba2435578' ,
// 调试 appId 值为 39a476cd5cbac50b1ba2435578
complete: function (res) { // 回调后执行 (调用成功、失败都会执行)
console.log(res); },
success: function (data) { // 成功回调 console.log(data);
// {"openId":["xxxxxxxxxxx","xxxxxxxxxxx"]}
},
fail: function (data,code) { // 失败回调
console.log(data); }
});
```
3. 提示`getJsBridge not find`

**Comment by shenghanqin** [comment]
在eslint里面加一个全局变量，
要是不仅支持h5，还要在小程序里面有别的包的话，就得加一个taro端的判断。
"globals": {
    "wx": true,
    "tt": true,
    "getApp": true,
    "getCurrentPages": true
  }
