### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by li-shuaishuai** [NervJS/taro#4999]
### 问题描述

Taro CLI 安装报错

### 复现步骤

![image](https://user-images.githubusercontent.com/20487014/70104114-08569500-1678-11ea-9702-f72a97ea52dd.png)

```js
npm install -g @tarojs/cli
```

### 报错信息

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:

### 系统信息

node  v10.15.1
npm  v6.13.1
@tarojs/cli v1.3.26 -> v1.3.27

**Comment by shenghanqin** [comment]
你是已经安装过1.3.26吧？
1. 用`taro update self`来升级taro-cli
2. 从我目前的经验来看，新版本cli发布后，cnpm等第三方npm平台同步新版本的时间需要半天到一天，所以呢，我建议你一天后再升级。(*￣︶￣)

**Comment by li-shuaishuai** [comment]
@shenghanqin 目前是1.3.26
1. 使用`taro update self`升级成功
2. 使用是 npm 非 cnpm 
目前问题已解决  感谢~
