### ISSUE TITLE
jsx 格式的插值编译为小程序自定义模版的插值时出错

### ISSUE THREAD

**Issue by zaaack** [NervJS/taro#500]
**问题描述**
无法使用自定义模版
**复现步骤**

目前的jsx 编译器是支持 template 标签的，但是在处理 data 时有问题,  目前是把 data 当作一个变量直接传递给了属性，e.g.:

```js
<template is="wxParser" __triggerObserer="{{ _triggerObserer }}" data="{{data}}"></template> // 错误
```

但是小程序的模版只支持这种语法
```js
<template is="wxParser" __triggerObserer="{{ _triggerObserer }}" data="{{...data}}"></template> // 正确
```

**期望行为**
期望能生成正确的模版语法

**补充信息**
为什么需要自定义模版呢? 因为 rich-text 组件太难用了，而且不支持视频，我们现在是用第三方的 wxParser 实现的，但是 wxParser 是使用原生模版实现的，所以希望能添加对原生模版的支持。

**Comment by luckyadam** [comment]
这里有一个使用 `wxParse` 的示例哦~
https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js

**Comment by zaaack** [comment]
@luckyadam 好的，多谢 👍

**Comment by yuche** [comment]
`template` 写 `...data` 和不写直接意义完全不同。而在 JSX 中写 `...data` 就是 `Object.assign({}, data)`。这里出现了这个冲突我们决定遵守 JSX 的规范。

如果你确实需要编译成带 `...data` 的写法，那就直接写字符串：`data="{{...data}}"`
