### ISSUE TITLE
react native 支持热更新  codepush 吗？

### ISSUE THREAD

**Issue by Leavds** [NervJS/taro#5000]
### 如题 react native 支持热更新  codepush 吗？

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
请补充codepush的更多信息
如官方、示例、或者你的更想法

**Comment by Leavds** [comment]
做的是React native商城项目，需要及时的推送优惠活动替换首页或者其他页面功能，修改bug啥的

**Comment by Leavds** [comment]
就是react native 项目做热更新，taro支持吗？ 还是每次都需要重新打包发布

**Comment by Pines-Cheng** [comment]
支持，和 RN 保持一致。

**Comment by Leavds** [comment]
ok  我试试 大佬  才开始接触 有点迷

**Comment by Leavds** [comment]
大佬碰到一个问题 打包的时候 报这个错 这是什么原因 Process 'command 'cmd'' finished with non-zero exit value 1

**Comment by Leavds** [comment]
taro这边直接是分了两个项目，codepush 打包的时候 报缺少index.js这个怎么处理
![image](https://user-images.githubusercontent.com/26810069/70131386-301c1c00-16bd-11ea-8d9c-c8dd8b31f849.png)

**Comment by shenghanqin** [comment]
加油，接触任何一个新东西，都是需要一些精力去各种配置，踩各种坑。
