### ISSUE TITLE
[建议升级至1.3.29或之后的版本]1.3.27，taro-redux更新复杂数据时，prev state 和 next state相同，页面不刷新

### ISSUE THREAD

**Issue by Mihawk-zhao** [NervJS/taro#5001]
旧数据的status为10，页面显示的也是10。
我想将list下的第0条信息的status改为20，结果prev state、next state、action里的status都为20，然而，页面显示的还是10那个状态。  

![image](https://user-images.githubusercontent.com/19793378/70111234-8fae0380-168c-11ea-8757-34351bb858cb.png)
  
reducers里的方法
![image](https://user-images.githubusercontent.com/19793378/70111308-c3892900-168c-11ea-8688-bc65bdc78d2e.png)

**Comment by shenghanqin** [comment]
我也跟一下，感觉最近taro redux的数据更新不够理想。嘻嘻

**Comment by Mihawk-zhao** [comment]
useState、redux等方式更新数据，都有问题，，现在退回1.3.25了。

**Comment by yyhdev** [comment]
> useState、redux等方式更新数据，都有问题，，现在退回1.3.25了。

我用taro-redux也出现了这种问题 修改state中的数组，用redux-logger打印的preState和nextState，要么都是更新后的state，要么数组清空或者添加第一个值时发生了变化，就是不更新视图
我退回1.3.25问题还是一样的，退回到1.3.18就没问题了。。。

**Comment by Chen-jj** [comment]
@Mihawk-zhao 提供一下完整可复现代码

**Comment by shenghanqin** [comment]
@Mihawk-zhao 你升级到最新1.3.29版本试试看？

**Comment by shenghanqin** [comment]
最新版按说没问题。如果有问题，你可以重新打开这个issue
