### ISSUE TITLE
在 tsx 怎么导入 .json 文件，执行后报错

### ISSUE THREAD

**Issue by supermavericks** [NervJS/taro#5003]
### 问题描述

在 .tsx文件中导入 .json 文件。编译执行后报错：
Uncaught Error: module "名字.json" is not defined

### 复现步骤
导入方法如下
```js
import * as ViewMapping from '../view.mapping.json'
```
使用 <Text>{ViewMapping.name}</Text>

### 报错信息

Uncaught Error: module "view.mapping.json" is not defined

### 系统信息

Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
    npmPackages:
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-qq: 1.3.25 => 1.3.25 
      @tarojs/taro-quickapp: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.0 => 1.5.5 
      nervjs: ^1.5.0 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息

 请问如何正确导入 .json文件？谢谢

**Comment by shenghanqin** [comment]
有问题先去官网看文档哟。🙂

[引用 JSON 文件](https://nervjs.github.io/taro/docs/static-reference.html#%E5%BC%95%E7%94%A8-json-%E6%96%87%E4%BB%B6)

**Comment by supermavericks** [comment]
@shenghanqin 👌 谢谢
