### ISSUE TITLE
小程序中的input和change事件不起作用

### ISSUE THREAD

**Issue by ninetowns** [NervJS/taro#5004]
### 问题描述

小程序中的Input、Textarea的onChange和onInput事件都无法正常回调

```js
<Input type='text' onInput={this.handleChange.bind(this)} onChange={this.handleChange.bind(this)}/>


```

### 期望行为
可以进行正常的回调

### 系统信息

Taro v1.3.27                                         
                                                     
                                                     
Taro CLI 1.3.27 environment info:                    
  System:                                            
    OS: Windows 7                                    
  Binaries:                                          
    Node: 10.12.0 - C:\Program Files\nodejs\node.EXE 
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by shenghanqin** [comment]
@ninetowns 建议提issue前先看看有木有类似的？

#4821 这个好像也是类似的问题，你看看？

**Comment by Garfield550** [comment]
不要使用微信基础库 2.9.3，使用其他任何一个版本。
