### ISSUE TITLE
map循环中使用自定义组件props无法更新

### ISSUE THREAD

**Issue by moonou** [NervJS/taro#5008]
### 问题描述
在map中使用自定义组件，并在自定义组件中指定state中的值为props，在state更新时，组件内部接收到的props没有被更新。
### 复现步骤
1. 设置一个state 默认值
2. 在文本框中更新state值
3. 观察更新结果

``` tsx
// Board.tsx
import {
  View
} from '@tarojs/components'

const Board = (props) => {
  console.log(props)

  return <View>props: {props.name}</View>
}

export default Board
```

```jsx
// index.tsx
state = {
    name: 'foo'
  }

  render () {
    return (
      <View className='index'>
        {
          [1,2,3].map((i) => {
            return (
              <View key={i}>
                <Input onInput={(e) => {
                  this.setState({
                    name: e.detail.value
                  })
                }}></Input>
                <Board name={this.state.name}></Board>
              </View>
            )
          })
        }
      </View>
    )
  }
```

### 期望行为

在通过文本框更新state后子组件能同步更新

### 报错信息

无

### 系统信息

![image](https://user-images.githubusercontent.com/6938877/70200096-69e93300-174e-11ea-8822-c67a59b75215.png)

### 补充信息
默认值可以显示，只是在更新时无法更新。
测试写法在微信小程序上可以得到期望运行结果，字节跳动小程序无法得到期望结果。

**Comment by moonou** [comment]
1.3.25版本没有这个问题

**Comment by shenghanqin** [comment]
@moonou 我是写过微信和抖音小程序的，我是觉得抖音小程序的坑挺多的，我建议你用react Component写法来写，尽量减少函数式组件来写，总感觉坑会更多。我就在解决自己业务中的抖音的两个状态不同步的问题。加油。

**Comment by moonou** [comment]
> @moonou 我是写过微信和抖音小程序的，我是觉得抖音小程序的坑挺多的，我建议你用react Component写法来写，尽量减少函数式组件来写，总感觉坑会更多。我就在解决自己业务中的抖音的两个状态不同步的问题。加油。

感谢你的回复，我尝试将子组件换成类的方式类编写，也不能解决这个问题。一起加油～😃

**Comment by shenghanqin** [comment]
抖音小程序的写法相当严格，render方法中不要有2个return，状态设置要非常清晰，安卓老版本也可能会出现各种小问题。你得加油啦。

**Comment by moonou** [comment]
抱歉。这个issue没有被解决啊，先不要打上answered。

**Comment by happyjosh** [comment]
> 抱歉。这个issue没有被解决啊，先不要打上answered。

遇到相同的问题了，兄弟解决了吗？

**Comment by Chen-jj** [comment]
@moonou 1.3.29 修复

https://github.com/NervJS/taro/commit/48b82713b674929354cf14e7f896a38d68a6582b

![image](https://user-images.githubusercontent.com/11807297/70600556-edad8e80-1c2a-11ea-957f-38fd2fdd0ab5.png)

**Comment by shenghanqin** [comment]
我来备注一下。
