### ISSUE TITLE
小程序中使用装饰器，报没有_createData错误, h5端正常

### ISSUE THREAD

**Issue by waveheart** [NervJS/taro#5009]
### 问题描述

尝试在小程序中写自定义的装饰器，本来是想对获取列表的东西封装一下，但是发现我以前写装饰器的方式在小程序中报错，但是在h5端正常
### 复现步骤

1. 
新建 index.jsx , testDecarator.js
2. 
正常使用@装饰
3. 
小程序端报错，装饰器无效，h5端正常

![image](https://user-images.githubusercontent.com/25602259/70201558-fa754280-1751-11ea-804d-06111bbeeb1a.png)

![image](https://user-images.githubusercontent.com/25602259/70201395-77ec8300-1751-11ea-97ba-50b328885beb.png)

index.jsx
```
import Taro, { Component } from "@tarojs/taro";
import { View, Text } from "@tarojs/components";
import testDecorator from "./testDecorator";

@testDecorator
class TestPage extends Component {
  constructor(props) {
    super(props);
  }

  state = {};

  render() {
    return (
      <View>
        <Text>test page</Text>
        <Text>装饰器添加的属性---{this.props.test}</Text>
      </View>
    );
  }
}

export default TestPage;

```

testDecorateor.js
```
import Taro, { Component } from "@tarojs/taro";
import { View, Text } from "@tarojs/components";

const testDecorator = Comp =>
  class extends Component {
    constructor(props) {
      super(props);
    }

    state = {};

    render() {
      return (
        <View>
          <Text>装饰器添加的</Text>
          <Comp test='test_111111'></Comp>
        </View>
      );
    }
  };

export default testDecorator;


```

### 期望行为

小程序端正常使用装饰器

### 报错信息

```
VM1827:1 TypeError: componentInstance._createData is not a function
    at Object.createComponent (index.js:2585)
    at index.js:70
    at require (VM1843 WAService.js:1)
    at <anonymous>:251:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1575516412005:2929)
    at HTMLScriptElement.script.onload (appservice?t=1575516412005:2941)
console.warn @ VM1827:1
createComponent @ index.js:2593
(anonymous) @ index.js:70
require @ VM1843 WAService.js:1
(anonymous) @ VM1941:251
scriptLoaded @ appservice?t=1575516412005:2929
script.onload @ appservice?t=1575516412005:2941
load (async)
(anonymous) @ appservice?t=1575516412005:2940
(anonymous) @ appservice?t=1575516412005:2993

```

### 系统信息

  Taro CLI 1.3.25 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: C:\Users\Administrator\Documents\react\myApp>"node"  "C:\Users\Administrator\AppData\Roaming\npm\\node_modules\yarn\bin\yarn.js" -v
1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

我的装饰器使用的不对么？？？但是在h5端一切正常啊

### 更新
有没有一个Taro装饰器的demo给看一下？

**Comment by waveheart** [comment]
PS 我都 写state 为啥给我 warning 说我没写state??

**Comment by shenghanqin** [comment]
### 第一种尝试
```js
import Taro, { Component } from "@tarojs/taro";
import { View, Text } from "@tarojs/components";
import testDecorator from "./testDecorator";

@testDecorator
class TestPage extends Component {
  constructor(props) {
    super(props);
    this.state = {}; // 写在这里试试看？
  }

  render() {
    return (
      <View>
        <Text>test page</Text>
        <Text>装饰器添加的属性---{this.props.test}</Text>
      </View>
    );
  }
}

export default TestPage;
```

### 第二个细节
在testDecorateor.js里面，不要出现
constructor和this.state的预定义

```js
import Taro, { Component } from "@tarojs/taro";
import { View, Text } from "@tarojs/components";

const testDecorator = Comp =>
  class extends Component {

    render() {
      return (
        <View>
          <Text>装饰器添加的</Text>
          <Comp test='test_111111'></Comp>
        </View>
      );
    }
  };

export default testDecorator;

```


### 第三个细节
你可以看看我这里写的，
```
export default function WithPage(TaroComponent) {
  class CorePage extends TaroComponent {
    static options = {
      addGlobalClass: true
    }
    componentWillMount() {
    // TODO 这里写代码
      
      if (super.componentWillMount) {
        super.componentWillMount()
      }
    }



  }
  CorePage.displayName = TaroComponent.displayName
    || TaroComponent.name
    || 'CorePage'

  return CorePage
}

```

**Comment by waveheart** [comment]
> ### 第一种尝试
> ```js
> import Taro, { Component } from "@tarojs/taro";
> import { View, Text } from "@tarojs/components";
> import testDecorator from "./testDecorator";
> 
> @testDecorator
> class TestPage extends Component {
>   constructor(props) {
>     super(props);
>     this.state = {}; // 写在这里试试看？
>   }
> 
>   render() {
>     return (
>       <View>
>         <Text>test page</Text>
>         <Text>装饰器添加的属性---{this.props.test}</Text>
>       </View>
>     );
>   }
> }
> 
> export default TestPage;
> ```
> 
> ### 第二个细节
> 在testDecorateor.js里面，不要出现
> constructor和this.state的预定义
> 
> ```js
> import Taro, { Component } from "@tarojs/taro";
> import { View, Text } from "@tarojs/components";
> 
> const testDecorator = Comp =>
>   class extends Component {
> 
>     render() {
>       return (
>         <View>
>           <Text>装饰器添加的</Text>
>           <Comp test='test_111111'></Comp>
>         </View>
>       );
>     }
>   };
> 
> export default testDecorator;
> ```
> 
> ### 第三个细节
> 你可以看看我这里写的，
> 
> ```
> export default function WithPage(TaroComponent) {
>   class CorePage extends TaroComponent {
>     static options = {
>       addGlobalClass: true
>     }
>     componentWillMount() {
>     // TODO 这里写代码
>       
>       if (super.componentWillMount) {
>         super.componentWillMount()
>       }
>     }
> 
> 
> 
>   }
>   CorePage.displayName = TaroComponent.displayName
>     || TaroComponent.name
>     || 'CorePage'
> 
>   return CorePage
> }
> ```
1. state写在contructer中依然报错未定义state 示定义

2. componentInstance._createData is not a function 的报错依然存在，
实际上在继承了原组件而非 Component 的情况下，这个报错会消失， 但是无法传递props

3. 实际上在用你的方法以后，虽然不报错，但是无法向被装饰的组件传递东西

```

import Taro from "@tarojs/taro";
import { View, Text } from "@tarojs/components";

export default function WithPage(TaroComponent) {
  class CorePage extends TaroComponent {
    static options = {
      addGlobalClass: true
    };
    componentWillMount() {
      // TODO 这里写代码

      if (super.componentWillMount) {
        super.componentWillMount();
      }
    }

    render() {
      return (
        <View>
          <Text>想添加点东西添不上</Text>
          <TaroComponent></TaroComponent>
        </View>
      );
    }
  }
  CorePage.displayName =
    TaroComponent.displayName || TaroComponent.name || "CorePage";

  return CorePage;
}

```

**Comment by Chen-jj** [comment]
@waveheart 目前高阶函数不能劫持 render 方法。render 会在编译时被识别出来编译成 createData 函数，HOC 里的 render 编译器识别不出来，因此会有问题。

**Comment by plimerence** [comment]
同样的问题  ，导致问题就是h5实现的装饰器 完全没有办法用到小程序

**Comment by TokeyJerry** [comment]
@shenghanqin 能帮忙解释下您说的
“
第二个细节
在testDecorateor.js里面，不要出现
constructor和this.state的预定义
” 这个是出于什么原因不可以扩展么？我有个需求是想在每个页面预设置 一个 state 值（因为：1、每个业务页面其实不一定都关心这个值；2、即使关心，也不想每个页面都写一遍），所以有更好的处理方式么？
