### ISSUE TITLE
taro启动测试版时控制台不停的出现“缺少npm包，开始安装”后报错？

### ISSUE THREAD

**Issue by syyzz3** [NervJS/taro#5010]
### 问题描述

taro启动测试版时控制台不停的出现“缺少npm包，开始安装”，后报错？

### 复现步骤

npm run dev:weapp

### 报错信息

![2521876344-5de8a1faea6a3_articlex](https://user-images.githubusercontent.com/11385973/70209358-08838d00-176b-11ea-8347-5291f04a3e17.png)

#

**Comment by luckyadam** [comment]
taro 版本多少
