### ISSUE TITLE
Taro.createCanvasContext创建绘图对象时报错

### ISSUE THREAD

**Issue by BinZhiZhu** [NervJS/taro#5011]
### 问题描述
H5端调用Taro.createCanvasContext时报错，提示 'vnode' of undefined
### 复现步骤
JS代码片段:
```  
    console.log('this.vnode',this.vnode)
    this.ctx = Taro.createCanvasContext(this.canvasId, this);
```
View代码片段:
```
      <Canvas
          canvasId={this.canvasId}
          style={`width:${pxWidth}px; height:${pxHeight}px;`}
          className={`${debug ? 'debug' : 'pro'} canvas`}
        />
```
打印的实例中的vnode对象：

![image](https://user-images.githubusercontent.com/35824900/70209842-34ebd900-176c-11ea-8f4a-4e258ecc15b4.png)
### 期望行为

期望能够正确返回绘图对象

### 报错信息
![image](https://user-images.githubusercontent.com/35824900/70209580-9eb7b300-176b-11ea-9667-7a6968f1adf7.png)
### 系统信息

👽 Taro v1.3.19

  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.11.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.5 => 1.3.5 
      @tarojs/plugin-babel: 1.3.5 => 1.3.5 
      @tarojs/plugin-csso: 1.3.5 => 1.3.5 
      @tarojs/plugin-sass: 1.3.5 => 1.3.5 
      @tarojs/plugin-uglifyjs: 1.3.5 => 1.3.5 
      @tarojs/router: 1.3.5 => 1.3.5 
      @tarojs/taro: 1.3.5 => 1.3.5 
      @tarojs/taro-alipay: 1.3.5 => 1.3.5 
      @tarojs/taro-h5: 1.3.5 => 1.3.5 
      @tarojs/taro-swan: 1.3.5 => 1.3.5 
      @tarojs/taro-tt: 1.3.5 => 1.3.5 
      @tarojs/taro-weapp: 1.3.5 => 1.3.5 
      @tarojs/webpack-runner: 1.3.5 => 1.3.5 
      eslint-config-taro: 1.3.5 => 1.3.5 
      eslint-plugin-taro: 1.3.5 => 1.3.5 
      nerv-devtools: ^1.4.3 => 1.5.5 
      nervjs: ^1.4.3 => 1.5.5

### 补充信息
https://github.com/NervJS/taro/issues/3909 这个issue相似问题，但是已经closed，没有看到最终的解决方案，希望能够支持一下，如果这个issue有重复可以关闭，但是希望这个问题最终能够fix

**Comment by Littly** [comment]
需要更完整的js代码片段，这样看不出问题
