### ISSUE TITLE
render props 无法传递函数（引用类型）

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#5013]
### 问题描述

render props 无法传递函数，引用类型貌似都不稳定，极少数情况下重复打包会表现正常

```js
// 父组件
const onCancel = () => {
   setVisible(false)
}

<View className={styles.content}>
   {props.renderChildren(onCancel)}
</View>

// 子组件
<FilterMask
    title={_.get(_.find(typeTagList, ['value', type]), 'label')!}
    renderChildren={(onCancel) => (
    <TagList
       onChange={onTypeChange.bind(null, onCancel)}
       dataSource={typeTagList}
       value={[type]}
       mode='radio'
       selectable
      />)}
 />

const onTypeChange = (onCancel, v) => {
  console.log('onCancel', onCancel)
  onCancel && onCancel()
  setType(v)
}
```

### 期望行为

能正常传递函数并调用

### 报错信息
正常情况
![企业微信截图_15755389212834](https://user-images.githubusercontent.com/7480381/70223700-092a1c80-1787-11ea-954c-922bdf0f266c.png)

不正常情况
![企业微信截图_15755376777220](https://user-images.githubusercontent.com/7480381/70222979-c1ef5c00-1785-11ea-8fdf-61b6c7ae4565.png)

### 系统信息

  Taro CLI 1.3.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - E:\intsall\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - E:\intsall\nodejs\npm.CMD

**Comment by youngluo** [comment]
@luckyadam

**Comment by shenghanqin** [comment]
@youngluo 你的代码示例，俺看不懂父子级的关系，好像是错的。

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
