### ISSUE TITLE
picker组件 mode='date' 时 value小于1970年会报错date interval error

### ISSUE THREAD

**Issue by htx1993** [NervJS/taro#5014]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
你可以试试把你的手机，Windows PC 或者 Mac 电脑，公司的 Linux 服务器的时间调到 1969 年 12 月 31 日。

**Comment by htx1993** [comment]
这是一个web的日期组件，无论是小程序原生的picker还是vant之类的组件库我还没见过不能选1970之前还报错的------------------ 原始邮件 ------------------
发件人: "Garfield Lee"<notifications@github.com>
发送时间: 2019年12月5日(星期四) 晚上10:16
收件人: "NervJS/taro"<taro@noreply.github.com>;
抄送: "htx1993"<784834054@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NervJS/taro] picker组件 mode='date' 时 value小于1970年会报错date interval error (#5014)



你可以试试把你的手机，Windows PC 或者 Mac 电脑，公司的 Linux &#x670D;务器的时间调到 1969 年 12 月 31 日。
 
&mdash;
