### ISSUE TITLE
网络请求无论怎么设置content-type总是text/plain

### ISSUE THREAD

**Issue by nishibaiyang** [NervJS/taro#5015]
### 复现步骤

```js
let requestBody = {
            "kubiCost" : this.state.noPrice ? 0 : this.state.price,
            "tagIds" : arr
        };
        let header = new Headers();
        header.append('Accept','application/json,text/javascript,*/*');
        header.append('Content-Type', 'application/json;charset=utf-8');
        
        return fetch(host + url, {
            method: 'POST',
            credentials: 'include',
            body: JSON.stringify(requestBody),
            mode: 'no-cors',
            headers: header
        }).then(res => {
            return res.text();
        });

```

### 系统信息

 Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.27 => 1.3.27 
      @tarojs/plugin-babel: 1.3.27 => 1.3.27 
      @tarojs/plugin-csso: 1.3.27 => 1.3.27 
      @tarojs/plugin-sass: 1.3.27 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.27 => 1.3.27 
      @tarojs/rn-runner: 1.3.27 => 1.3.27 
      @tarojs/router: 1.3.27 => 1.3.27 
      @tarojs/taro: 1.3.27 => 1.3.27 
      @tarojs/taro-alipay: 1.3.27 => 1.3.27 
      @tarojs/taro-h5: 1.3.27 => 1.3.27 
      @tarojs/taro-swan: 1.3.27 => 1.3.27 
      @tarojs/taro-tt: 1.3.27 => 1.3.27 
      @tarojs/taro-weapp: 1.3.27 => 1.3.27 
      @tarojs/webpack-runner: 1.3.27 => 1.3.27 
      eslint-config-taro: 1.3.27 => 1.3.27 
      eslint-plugin-taro: 1.3.27 => 1.3.27 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6

**Comment by shenghanqin** [comment]
@nigelvon 稍微把fetch方法提供一下？

**Comment by nishibaiyang** [comment]
> @nigelvon 稍微把fetch方法提供一下？

fetch方法就是上面，用的就是页面里面最原始的的fetch

**Comment by yuanbolin** [comment]
同样遇到了，请问解决了吗
