### ISSUE TITLE
请教下如何在taro中使用Optional Chaning ES9语法特性

### ISSUE THREAD

**Issue by edwards19900128** [NervJS/taro#5017]
### 问题描述
感谢优秀的框架开源出来使用
写业务代码的时候非常想使用Optional Chaning特性去判断非空，但是按照说明中使用babelrc文件中定义过去 Taro会编译失败，请教一下如何配置babel在taro中

**Comment by shenghanqin** [comment]
@edwards19900128 我猜很大的可能有以下的
1、Optional Chaning是TS上推动的，而TS在react、taro上可能支持速度并不快吧。
2、1.xx.xx上的编译是自研的，2.0.0 beta之后的版本是基于webpack的，也就是说，新特性的编译可能会更好配置。我建议你可以在beta中测试这个功能，并给我们提issue或者修改建议，感谢。

**Comment by Chen-jj** [comment]
Taro3 已支持

**Comment by Chen-jj** [comment]
Taro3 已支持
