### ISSUE TITLE
直接在dom节点写style 对于px的处理跟less里面写的不一致

### ISSUE THREAD

**Issue by BryantZhou** [NervJS/taro#502]
**问题描述**
直接在dom节点写行内样式 style={{height: 200px}} 在小程序里面直接渲染了200px
而在less文件里面写200px 会改成小程序的rpx形式，实际是100px

```js
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';
import './demo.less';

class Index extends Component {
  config = {
    navigationBarTitleText: 'demo'
  };
  render() {
    return (
      <View>
        <View style={{ height: '200px', background: '#333', color: '#fff' }}>
          样式来自行内
        </View>
        <View className="demo">样式来自less</View>
      </View>
    );
  }
}

export default Index;


```

less
```
.demo {
  margin-top: 10px;
  height: 200px;
  background: #999;
  color: #fff;
}

```
生成截图
![image](https://user-images.githubusercontent.com/12403684/44396944-14950c80-a571-11e8-8d9f-3b4612757afe.png)

**期望行为**
样式表现一直

**报错信息**

**系统信息**

 - 操作系统: [e.g. Mac]
 - Taro 版本 [e.g. v1.0.0-beta.11]
 - Node.js 版本 [e.g. v8.9.0]

**Comment by AlexStacker** [comment]
应该说的是这个[链接](https://nervjs.github.io/taro/size.html#%E5%B1%9E%E6%80%A7)上的

**Comment by BryantZhou** [comment]
@AlexStacker  我是想行内样式也转成rem

**Comment by BryantZhou** [comment]
@luckyadam OK 谢谢
