### ISSUE TITLE
PickerView  不能支持H5端需要在H5端实现pickerView的效果

### ISSUE THREAD

**Issue by liuyunzyj** [NervJS/taro#5021]
PickerView  不能支持H5端需要在H5端实现pickerView的效果该如何实现，望给个思路与方向

**Comment by liuyunzyj** [comment]
@Littly PickerView 不能支持H5端需要在H5端实现pickerView的效果该如何实现，望给个思路与方向

**Comment by Johnnnnboy** [comment]
有思路了没有
