### ISSUE TITLE
H5 swiper 已经添加了circular 还是不能循环滚动

### ISSUE THREAD

**Issue by benmi** [NervJS/taro#5023]
### 问题描述

swiper 已经添加了circular 还是不能循环滚动
我已经把taro 及依赖更新到最新版本了，看其他的issuse,是代码误删了，不知道什么时候能添加上去。
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```js
     <Swiper
        className={!home ? 'swiper-container' : 'swiper'}
        current={this.state.current}
        indicatorDots={false}
        indicatorColor='#999'
        indicatorActiveColor='#bf708f'
        autoplay
        circular={true}
        interval={interval}
        onAnimationFinish = {this.onSwiper}
        >
          <View className='lefts'></View>
          <View className='rights'></View>
        { banner.map((item, index) => (
          <SwiperItem key={index} >
              <Prize pize = {item}></Prize>
          </SwiperItem>
        ))}
      </Swiper>
```
### 期望行为

期望swiper 正常循环播放
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@benmi 你可以把说误删的那个issue找出来贴到这里吗？

**Comment by benmi** [comment]
https://github.com/NervJS/taro/issues/4363

**Comment by benmi** [comment]
https://github.com/NervJS/taro/pull/4547

**Comment by iChengbo** [comment]
`onAnimationFinish = {this.onSwiper}`  这个事件做了什么？

**Comment by benmi** [comment]
> `onAnimationFinish = {this.onSwiper}` 这个事件做了什么？

注释了结果还是一样的 ，我是打算模拟一下

**Comment by jaytuan** [comment]
我是有两个页面用到了轮播，一个页面设置了circular，可以正常循环播放，另一个页面一模一样的代码，到最后一个就会回退到第一个再往下轮播，要被折磨疯了

**Comment by Littly** [comment]
目前的swiper对于children的更新处理有问题，可以先给swiper加个key，在更新children的同时更新这个key值，触发swiper的重新挂载，后续swiper会修复这个问题。

**Comment by fuersite** [comment]
这个问题解决了吗？ issue 怎么close了

**Comment by wayung** [comment]
这个问题解决了吗？ issue 怎么close了
