### ISSUE TITLE
H5 ScrollView  scrollIntoView 属性没有作用

### ISSUE THREAD

**Issue by giantss** [NervJS/taro#5025]
https://github.com/NervJS/taro/issues/3238 这个问题没有修复关闭了, 我这里重新开启一下吧

**Comment by giantss** [comment]
请问一下这个问题在下个版本的修复计划内吗? 如果不在能否提供一个临时方案啊... @Littly

**Comment by meiye1988** [comment]
我刚刚遇到这个问题....

**Comment by tourze** [comment]
同遇到这个问题。。。 @Littly

**Comment by zouyang2015** [comment]
h5可以跳，但是都不知道他是怎么跳的，跳的不是要跳的地方。反正现在。2.0.2版本是有问题。

**Comment by ZakaryCode** [comment]
初始化 ScrollView 的时候，并不会使用 scrollIntoView 跳转，后续版本中会优化该功能
