### ISSUE TITLE
taro 打包成小程序会调用原生小程序Page方法吗

### ISSUE THREAD

**Issue by jaytuan** [NervJS/taro#5028]
最近用taro新开发了几个页面，混入到原生小程序里面，阿拉丁统计是在Page生命周期函数onshow里面调用上报统计的，打断点调试发现没有调用Page方法，求解

**Comment by jaytuan** [comment]
liujiantuandeiMac:jd_dog jaytuan$ taro info
👽 Taro v1.3.19


  Taro CLI 1.3.19 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.22 => 1.3.19 
      @tarojs/components: 1.3.22 => 1.3.18 
      @tarojs/plugin-babel: 1.3.22 => 1.3.18 
      @tarojs/plugin-csso: 1.3.22 => 1.3.18 
      @tarojs/plugin-sass: 1.3.22 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.18 
      @tarojs/router: 1.3.22 => 1.3.18 
      @tarojs/taro: 1.3.22 => 1.3.18 
      @tarojs/taro-alipay: 1.3.22 => 1.3.18 
      @tarojs/taro-h5: 1.3.22 => 1.3.18 
      @tarojs/taro-qq: 1.3.22 => 1.3.18 
      @tarojs/taro-quickapp: 1.3.22 => 1.3.18 
      @tarojs/taro-swan: 1.3.22 => 1.3.18 
      @tarojs/taro-tt: 1.3.22 => 1.3.18 
      @tarojs/taro-weapp: 1.3.22 => 1.3.18 
      @tarojs/webpack-runner: 1.3.22 => 1.3.18 
      eslint-config-taro: 1.3.22 => 1.3.18 
      eslint-plugin-taro: 1.3.22 => 1.3.18 
      nerv-devtools: ^1.5.3 => 1.4.4 
      nervjs: ^1.5.3 => 1.4.4 
      stylelint-config-taro-rn: 1.3.22 => 1.3.18 
      stylelint-taro-rn: 1.3.22 => 1.3.18

**Comment by shenghanqin** [comment]
我的理解是，taro是基于component实现的page功能，在create-component里面用isPage来标识，所以，onShow方法没办法在小程序启动的时候监听到。可以给Page加一个高阶函数或者装饰器，触发componentDidShow的时候再执行特定方法。 @luckyadam 不知道核心概念是这样的吗？

**Comment by shenghanqin** [comment]
阿拉丁统计上不知道是否暴露了onShow的外部调用方法，你可以在ComponentDidShow的时候手动调用。我这里就是这样干的。

**Comment by jaytuan** [comment]
感谢大佬@shenghanqin @luckyadam 赐教。看了Taro和阿拉丁源码后发现想要通过Taro页面调用Page方法实现起来比较麻烦，最简单的就是像 @shenghanqin 大佬说的一样，改掉阿拉丁的sdk。我是在阿拉丁sdk里面写了个方法暴露出来，学着阿拉丁重写小程序Page方法的样子，在Taro页面生命周期函数手动调用阿拉丁各个生命周期的统计方法，从而实现taro和原生小程序混合的taro页面阿拉丁统计。（阿拉丁没有暴露外部可以手动调用统计的方法，也是为了基础数据统计的真实准确性，所以不到万不得已最好不要手动去调用）
