### ISSUE TITLE
taro-ui转快应用方案探索

### ISSUE THREAD

**Issue by Issacpeng** [NervJS/taro#5029]
### 问题描述
  随着2.0框架beta版本的发布，原有taro-ui适配方案已不适用，经过这段时间对2.0webpack包管理框架的熟悉，开始了对taro-ui转快应新的探索，当前已跑通最简要的DEMO，这部分转换不涉及到babel-core语法解析，也不涉及到fileparseloader，对思路进行详细说明

1.探索1：最优方案聚焦在直接增强taro-ui的组件逻辑，但深度学习后，taro-ui可以理解为：taro原生小程序组件的应用开发增强版本，必须搭建在小程序引擎上进行运行，想要缝合RN端和小程序WEB端框架的裂缝，难度及工作量过大，只能退而求其次

2.探索2：直接从源头进行转换，将taro-ui组建映射到快应用组件，但是对快应用组件进行样式增强，模拟taro-ui实现，达到一样的使用效果
1）先看整个架构层次：
![image](https://user-images.githubusercontent.com/11417652/70373755-2a753f00-1926-11ea-9aca-effaad0b0eb0.png)

2）整个转换主要集中在3个方面：
   1.优化模板生成：在编译时中进行模板的转换时，主要涉及组件名称匹配、引入路径映射等问题，taro-transformer-wx、taro-mini-runner 2个模块有涉及，taro-transformer-wx解析时进行了组件名称加工，taro-mini-runner进行运行时组件的样式拷贝。因此可考虑在从源头对组件进行截断和替换，引入到原生组件库转换逻辑中，可将组件区分为3类（ 1.原生、taro-ui、快应用三方交集部分   2.通过WEB模拟的taro原生小程序    3.待增强taro-ui应用组件），在引入策略模式后，将组件库维护列表在content.js中初始化，与逻辑部分解耦，便于后期维护，但需考虑taro-ui的组件的特殊情况，初衷就是为了增强用户用于开发的易用性，如果只是简单的通过div模拟，并不能解决快应用易用性问题，因为考虑增强运行时组件库
  
![image](https://user-images.githubusercontent.com/11417652/70374092-2b0fd480-192a-11ea-95dc-eb40fc6edd32.png)

   2.运行时组件库实现改进：主要涉及taro-components-qa模块，增强taro-ui应用组件部分，呈现效果与原生小程序、taro-ui保持一致，使得用户对组件的切换无感知（可参考button快应用增强实现部分，主要基于weex框架、快应用框架实现），对于难度颇大的组件，比如日历等的实现部分，可通过div组件进行暂时的模拟，待实现后进行替换

   3.快应用端 样式映射重写：像素、宽度等基础属性，已有PR实现
   

3）待讨论部分：
1.在调用组件时，属性的不兼容就会造成很多不便，可以考虑引入taro-ui组件的属性类型检测机制？尽可能规避属性不兼容问题
2.当前已引入的属性公共部分，是否可实现组件之间的属性映射库？规避转换完毕后，出现大量属性错误的情况，如果只是在组件名称的颗粒度，属性部分会对用户使用造成很大困扰

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@Issacpeng 我可以理解这是一篇架构升级的探索文章吗？那么标题是不是可以修改一下，内容是不是可以删减一些？

# 我的期待
我对UI类的开发也十分感兴趣，不知道可以加入吗？

**Comment by Issacpeng** [comment]
@shenghanqin 其实是对2.0适配的一个思路整理， 快应用不同于小程序体系，在使用时受制于weex及快应用框架，产生诸多限制，仅仅不报错是达不到真正可使用落地的目标的。 工作量最大的部分在于属性库映射、组件运行时增强，用户如果对组件了解不深，不一定能够正确使用，需要借助说明文档及框架的辅助，帮助决策，有兴趣的话，方案我们可以具体讨论下。

**Comment by Issacpeng** [comment]
@shenghanqin  我详细比较组件部分的差异，列了实现的milestone适配计划，如果你有兴趣的话，我们可以分工实现，可以通过老李的微信群找到我。
![image](https://user-images.githubusercontent.com/11417652/70785197-18cbe580-1dc5-11ea-914e-7b0483fd681c.png)
