### ISSUE TITLE
taro-mobx 数组更新了，但视图未更新

### ISSUE THREAD

**Issue by allenou** [NervJS/taro#5030]
### 问题描述
当数组为空时更新数组，此时视图只更新了部分，当数组不为空时更新数组，数组可更新成功，但视图完全未更新。数组结构如下：
```js
list:[ {
    conversationID: '',
    unreadCount: 0,
    userProfile: {
    avatar: '',
    nick: ''
   },
    lastMessage: {
        lastTime: 0,
        messageForShow: ''
   }
}]
```
数组为空时更新数组，unreadCount、lastMessage.messageForShow、lastMessage.lastTime 在视图中能显示，但 avatar、nick 未能显示，当数组不为空时更新数组，视图完全未更新。

### 复现步骤

页面中引入 store 中数组遍历子组件

```js
// store.js
import { observable } from 'mobx'
const chatStore = observable({
    conversationList: [],
    setConversationList(list) {
        this.conversationList = list
    }
})
export default chatStore

// tim.js
tim.on(TIM.EVENT.CONVERSATION_LIST_UPDATED, (event) => {  // 实时消息更新事件
    chatStore.setConversationList(event.data)   // 更新列表
});

// list.js
import { observer, inject } from '@tarojs/mobx'
import ConversationItem from './components/ConversationItem'

@inject('chatStore')
@observer
export default class ConversationList extends Component {
    render() {
      const { chatStore: { conversationList } } = this.props
      return(
           conversationList.slice().map((item, index) => {
              <ConversationItem item={item}></ConversationItem>
           })
       )
    }
}
```

### 期望行为

数组更新后，视图同步更新

### 系统信息
    "@tarojs/components": "1.3.22",
    "@tarojs/mobx": "^1.3.25",
    "@tarojs/router": "1.3.22",
    "@tarojs/taro": "1.3.22",
    "@tarojs/taro-weapp": "1.3.22",
    "classnames": "^2.2.6",
    "mobx": "^5.15.0",
    "nerv-devtools": "^1.5.0",
    "nervjs": "^1.5.0",
    "taro-ui": "^2.2.4",
    "tim-wx-sdk": "^2.2.0",
### 补充信息
使用 redux 或者直接在页面遍历普通元素（非组件）均能复现该问题

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by cloudZQY** [comment]
使用mobx的数组map时，请使用toJS。
```
{
  list.map(item => (<View></View>))
}
```
请变成
```
{
  toJS(list).map(item => (<View></View>))
}
```
原因是taro会将map编译成`<view wx-for="{{list}}"></view>`，而list是一个mobx中的Observable object，而不是一个array。这个应该是在taro中用mobx中必踩的坑，建议放文档里面。

**Comment by allenou** [comment]
toJS 和 slice 试过了都不行。

**Comment by cloudZQY** [comment]
> toJS 和 slice 试过了都不行。

没办法重现，既然是部分渲染，那应该跟ConversationItem有关吧，能提供一下代码吗？

**Comment by yyhdev** [comment]
我用taro-redux也出现了这种问题 修改state中的数组，用redux-logger打印的preState和nextState，要么相同，要么视图不更新（数组清空或者添加第一个值）

**Comment by yyhdev** [comment]
我用taro-redux也出现了这种问题 修改state中的数组，用redux-logger打印的preState和nextState，要么都是更新后的state，要么数组清空或者添加第一个值时发生了变化，就是不更新视图

**Comment by allenou** [comment]
@cloudZQY  遍历普通的元素也存在该问题。@yyhdev 我用 taro-redux 也同样存在该问题。
ConversationItem code :
```js
export default class ConversationItem extends Component {
    static defaultProps = {
        item: {
            conversationID: '',
            unreadCount: 0,
            userProfile: {
                avatar: '',
                nick: ''
            },
            lastMessage: {
                lastTime: 0,
                messageForShow: ''
            }
        },
    }
    constructor(props) {
        super(props)
    }

    render() {
        const { item } = this.props
        let AvatarView

        if (item.userProfile.avatar) {
            AvatarView = <AtAvatar image={item.userProfile.avatar}></AtAvatar>
        } else {
            AvatarView = <AtAvatar text={item.userProfile.nick} ></AtAvatar>
        }
        return (
            <View className="conversation-item">
                <View className="avatar-container">
                    {AvatarView}
                    {item.unreadCount > 0 &&
                        <View className="dot"></View>
                    }
                </View>
                <View className="item-right" >
                    <View className="text">
                        <Text className='name'>{item.userProfile.nick}</Text>
                        <Text className='time'>{item.lastMessage.lastTime}</Text>
                    </View>
                    <RichText className='message' nodes={item.lastMessage.messageForShow} />
                </View>
            </View>
        )
    }
}
```

**Comment by shenghanqin** [comment]
我这里有两种假设
1、新版本有问题，比如1.3.27有问题，1.3.1x版本可能没问题
2、redux和mobx没问题，而是taro-weapp内props有问题。

我猜想得从Taro本身寻找问题啦。

**Comment by Garfield550** [comment]
@shenghanqin 最近几个版本都在优化小程序方面的 props 处理，你可以看一下是不是有遗漏的地方。

**Comment by shenghanqin** [comment]
> @shenghanqin 最近几个版本都在优化小程序方面的 props 处理，你可以看一下是不是有遗漏的地方。

一起努力！
我的直观感受就是8月份用的props问题挺少，最近的props感觉有些bug，看来还是得从源码里面慢慢定位。

**Comment by yyhdev** [comment]
> @cloudZQY 遍历普通的元素也存在该问题。@yyhdev 我用 taro-redux 也同样存在该问题。
> ConversationItem code :
> 
> ```js
> export default class ConversationItem extends Component {
>     static defaultProps = {
>         item: {
>             conversationID: '',
>             unreadCount: 0,
>             userProfile: {
>                 avatar: '',
>                 nick: ''
>             },
>             lastMessage: {
>                 lastTime: 0,
>                 messageForShow: ''
>             }
>         },
>     }
>     constructor(props) {
>         super(props)
>     }
> 
>     render() {
>         const { item } = this.props
>         let AvatarView
> 
>         if (item.userProfile.avatar) {
>             AvatarView = <AtAvatar image={item.userProfile.avatar}></AtAvatar>
>         } else {
>             AvatarView = <AtAvatar text={item.userProfile.nick} ></AtAvatar>
>         }
>         return (
>             <View className="conversation-item">
>                 <View className="avatar-container">
>                     {AvatarView}
>                     {item.unreadCount > 0 &&
>                         <View className="dot"></View>
>                     }
>                 </View>
>                 <View className="item-right" >
>                     <View className="text">
>                         <Text className='name'>{item.userProfile.nick}</Text>
>                         <Text className='time'>{item.lastMessage.lastTime}</Text>
>                     </View>
>                     <RichText className='message' nodes={item.lastMessage.messageForShow} />
>                 </View>
>             </View>
>         )
>     }
> }
> ```

redux中只有数组有问题呢

**Comment by shenghanqin** [comment]
@yyhdev 你试试看，redux，用ComponentWillReceiveProps有木有问题

**Comment by yyhdev** [comment]
> @yyhdev 你试试看，redux，用ComponentWillReceiveProps有木有问题

有问题，我在reducer里面直接打印当前state和action传过来的值就出了问题，情况就是我之前提到得那样。ComponentWillReceiveProps是在reducer改变state后触发的，所以。。。

**Comment by nanjingboy** [comment]
@allenou 你的 map 忘记 return 了，这样改：

```js
conversationList.slice().map((item, index) => {
  return <ConversationItem item={item}></ConversationItem>
})
```

或：

```js
conversationList.slice().map((item, index) => (
 <ConversationItem item={item}></ConversationItem>
))
```

注意 "{}" 和 "()" 的差异

**Comment by allenou** [comment]
这个有临时解决办法吗，项目要急着上线了。

> @allenou 你的 map 忘记 return 了，这样改：
> 
> ```js
> conversationList.slice().map((item, index) => {
>   return <ConversationItem item={item}></ConversationItem>
> })
> ```
> 
> 或：
> 
> ```js
> conversationList.slice().map((item, index) => (
>  <ConversationItem item={item}></ConversationItem>
> ))
> ```
> 
> 注意 "{}" 和 "()" 的差异

有 return 的，贴代码的时候不小心漏掉了~

**Comment by nanjingboy** [comment]
@allenou 根据你提供的信息我这边是 OK 的，你升级到最新版本（1.3.27）试试，如果还不行，提供个完整可复现的 demo 吧。

**Comment by allenou** [comment]
> @allenou 根据你提供的信息我这边是 OK 的，你升级到最新版本（1.3.27）试试，如果还不行，提供个完整可复现的 demo 吧。

我这边有尝试通过简单的 demo 去复现，但都没能复现，难道该问题只存在基于 TIM SDK 的实时聊天？

**Comment by allenou** [comment]
使用全局变量仍有该问题😭，看来的确是 taro 自身的问题，升级到最新版本也无法解决😔

**Comment by shenghanqin** [comment]
@allenou 把你的代码demo也贴一下吧，这样回头可以挨个排查。

**Comment by allenou** [comment]
数组内对象扁平化后存储可解决该问题。
before:
```js
list:[{
    conversationID: '',
    unreadCount: 0,
    userProfile: {
    avatar: '',
    nick: ''
   },
    lastMessage: {
        lastTime: 0,
        messageForShow: ''
   }
}]
```
after:
```js
list:[{
  conversationID:''
  unreadCount:'',
  lastTime: '',
  messageForShow: '',
  userID: '',
  nick: '',
  avatar: ''
}]
```

**Comment by shenghanqin** [comment]
我来备注一下。
