### ISSUE TITLE
IM 照片等功能可以用taro同时兼顾 app和小程序吗？

### ISSUE THREAD

**Issue by alexhmyang** [NervJS/taro#5031]
据说 不可兼顾，求过来人指点。

我们 主要做 社交，IM是核心功能，目前用第三方极光api服务，
想问问：如果我们用taro, 作为 ios , android, h5, 小程序的 底层框架，会不会有问题？

IM 照片 gps 等功能可以用taro同时兼顾 app和小程序吗？

谢谢大家。

**Comment by shenghanqin** [comment]
@alexhmyang 你可以把你说的sdk的官方网址，demo，你的源代码写一下，以及你可能用到的GPS的API，这样才能方便我们进行判断和答复。总不能让我们还跟着去搜一遍基础信息吧？

**Comment by shenghanqin** [comment]
极光文档，[REST API](http://docs.jiguang.cn/jverification/server/rest_api/rest_api_summary/)

**Comment by shenghanqin** [comment]
看了一下官方文档，文档里面有账号登录、选择照片等这些功能，你得自己尝试拉。
http://docs.jiguang.cn/jmessage/client/im_sdk_wxapplet/

**Comment by jarbozhang** [comment]
实际经验微信小程序问题不大
