### ISSUE TITLE
 manjaro linux系统上taro-temp目录无法在usr/local/share下创建。 (node:478) UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by uomer** [NervJS/taro#5033]
系统： manjaro linux
就是一个问题，创建项目时创建临时文件，为什么不是在系统临时目录创建呢？mkdir '/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/templates/taro-temp' 是哪里配置的？

(node:478) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/templates/taro-temp'
(node:478) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:478) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shenghanqin** [comment]
@uomer 请按照标准issue模板来提问。提供源码demo以及完整出错截图以及你的操作步骤。

**Comment by uomer** [comment]
安装后，非root用户无法 init 一个项目

**Comment by shenghanqin** [comment]
俺请明确告知你用的系统版本以及你对文件夹的操作权限。假设taro并没有这个文件夹的权限呢？

**Comment by shenghanqin** [comment]
请提供你的taro版本

**Comment by uomer** [comment]
1.3.27

**Comment by uomer** [comment]
全局安装要用root，安装后init 项目 时他要在/usr 相应目录下创建临时目录。所以非root用户就无法创建项目了。

**Comment by uomer** [comment]
操作系统是 manjaro linux

**Comment by uomer** [comment]
就是一个问题，创建项目时创建临时文件，为什么不是在系统临时目录创建呢？mkdir '/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/templates/taro-temp'  是哪里配置的？

**Comment by shenghanqin** [comment]
@uomer 请注意按照issue标准模板来提问，注意提炼你的问题。

**Comment by Garfield550** [comment]
你好，这是 yarn 的问题，你的 Yarn 应该是从 Manjaro 源里，用 Manjaro 包管理器安装的吧

`/usr/local/share/.config/yarn`

**Comment by Garfield550** [comment]
建议修改一下 Yarn 的全局安装目录设置，https://yarnpkg.com/lang/en/docs/cli/global/#Defining%20install%20location

https://gitlab.manjaro.org/arch-packages/community/yarn/blob/packages/yarn/repos/community-any/PKGBUILD

另外这边不建议从 Manjaro 包管理器安装 Yarn，从 Manjaro 引入的 Arch 包源码看，它在安装 Yarn 时实际只是将 Yarn 的 JS 代码解压到了 `/usr/lib/node_modules/` 目录，这可能会污染 `npm` 或者其他使用 `/usr/lib/node_modules/` 目录的程序，因为 Yarn 是由非 Node 包管理体系成员安装的，可能会存在各种问题。

```bash
depends=('nodejs')
source=("https://github.com/yarnpkg/yarn/releases/download/v$pkgver/yarn-v$pkgver.tar.gz")

package() {
  cd yarn-v${pkgver}
  install -dm755  "$pkgdir"/usr/lib/node_modules/yarn
  cp -R * "$pkgdir"/usr/lib/node_modules/yarn

  install -dm755 "$pkgdir"/usr/bin
  ln -s /usr/lib/node_modules/yarn/bin/yarn.js "$pkgdir"/usr/bin/yarn
  ln -s /usr/lib/node_modules/yarn/bin/yarn.js "$pkgdir"/usr/bin/yarnpkg

  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  install -Dm644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"
}

```
