### ISSUE TITLE
taro的project.config.json支持js格式么？

### ISSUE THREAD

**Issue by nai6514531** [NervJS/taro#5035]
由于一些敏感信息不详放在配置文件中。想通过接入远程配置中心的方式来获取配置。但是现在的配置文件是json格式的。有什么方法可以实现我的诉求么？

**Comment by Garfield550** [comment]
`project.config.json` 按照微信小程序规范编写，Taro 只做拷贝。

**Comment by nai6514531** [comment]
@Garfield550 那如何实现config的异步加载呢？

**Comment by cloudZQY** [comment]
可以自己写一个gulp，获取远程信息后替换配置

**Comment by shenghanqin** [comment]
`project.config.json`是给小程序大的配置，相当于小程序build时候就是不变的，但你可以在src下再单独建一个config.js的文件，里面尝试加入这种异步获取的逻辑。

**Comment by nai6514531** [comment]
@cloudZQY 这种方案要在启动前获取数据然后写到配置文件里。但数据还是可以在服务器上的config看到。如果config支持js的话。。就看不到具体的值 
比如 {
   appId: getConfig()
}

**Comment by nai6514531** [comment]
@shenghanqin 我的诉求是想project.config.json里的一些数据不想写在文件里。比如appId这样的。你说的那个方法如何解决appId这样的配置呢

**Comment by shenghanqin** [comment]
appid本身就是暴露给小程序官方的，你可以先了解一下原生小程序有木有相关优化。
其实类似于知晓云里面的一些key，人家官方就说，你设置的一些key相当于就暴露给外界了，所以得慎重设置。换句话来说，前端的很多配置就是暴露的。

**Comment by cloudZQY** [comment]
@nai6514531 你是想要在哪一步看不见呢？如果你了解小程序的话就应该知道，在小程序自己进行编译这一步，小程序开发者工具是必须知道appId的，这个跟taro没有关系。无论如何在小程序开发者工具进行编译之前都必须把appid写在代码中。
如果你们一定要把appId隐藏，可以开发和生产的appId分开，走自动化构建，开发环境的appId在自动化构建中获取然后写进去，用开发者工具的api自动推送代码，这样开发者就接触不到生产了。

**Comment by Garfield550** [comment]
小程序 `appId` 暴露与否无所谓的，它不能从微信那边拿到小程序的源代码，也不能对你的小程序做什么操作，微信开发者工具通过 `appId` 从微信后台获取开发人员对开发工具的权限认证，你如果不在小程序管理后台配置开发人员的微信号，就没有办法使用你的 `appId`。

**Comment by nai6514531** [comment]
@cloudZQY ci设置变量的这种方式是ok的。但是如果对接applo通过api的方式去获取配置在json里就不太行的通。需要去动态写入到配置文件里。。感觉就很别扭。。像egg这样的config都是js形式的。感觉是更灵活的

**Comment by nai6514531** [comment]
@Garfield550 好像小程序最早出来的时候是可以爬到源码的。。。。

**Comment by Garfield550** [comment]
现在已经无需担心，如果你对小程序本身技术有相关疑问，请去微信开发者社区提问讨论。

json 在 npm 上有很多可以解析的库，自己使用 node 写一个脚本在 taro build 之前执行一下就可以了。

**Comment by shenghanqin** [comment]
前端和小程序，在上线前都会做一定的代码混淆，而拿到这样的源代码其实也没多大意义，因为appid要校验权限，后端功能也会校验权限，你说的超级安全的那种就得在后端多加一些权限校验。
