### ISSUE TITLE
flat （） is not a function

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#5036]
### 问题描述
TypeError: u.default.LWD.unNormal.map(...).flat is not a function

    "@tarojs/taro": "1.3.27",

**Comment by shenghanqin** [comment]
@JoMartinezZhu 请提供完整的源码、demo。
还有，你这个是不是数组的flat方法，是不是ES标准的新方法，需要babel编译的，而你的babel编译配置不对？

**Comment by xuzpeng** [comment]
大佬babel后面咋配的？我一直没配成功

**Comment by shenghanqin** [comment]
什么版本？

**Comment by xuzpeng** [comment]
taro和cli的版本是1.3.25，babel貌似是6的，本来想装babel-polyfill的，但是看了下babel-polyfill里面貌似没flat @shenghanqin
