### ISSUE TITLE
[建议升级至1.3.29或最新版]tt小程序：使用useEffect，内部组件获取不到props

### ISSUE THREAD

**Issue by lzs2000131** [NervJS/taro#5037]
### 问题描述

使用useEffect，内部组件获取不到props

### 复现步骤

1. 使用useEffect的情况下BottomTabbar是渲染不出来的，注释掉两个useEffect就能出来
2.打印props发现BottomTabbar没有获取到props

index.js
```js
import Taro, { useState, useEffect } from '@tarojs/taro'
import { View } from '@tarojs/components'
import BottomTabbar from './bottom-tabbar'

export default function Index() {
  const [title, setTitle] = useState('默认')
  const [value, setValue] = useState('value1')

  const list = [
    {
      text: '新建',
      type: 'new'
    }
  ]

  useEffect(() => {
    setTitle('更改')
  }, [])

  useEffect(() => {
    setValue('value2')
  }, [title])

  return (
    <View>
      <View>{value}</View>
      <View>
        {list.map(item => {
          return <BottomTabbar key={item.type} itemData={item} />
        })}
      </View>
    </View>
  )
}

```
bottom-tabbar.tsx
```js
import Taro, { useContext, useState, useRouter } from '@tarojs/taro'
import { View } from '@tarojs/components'

export default function BottomTabbar(props) {

  console.log(props)
  const { itemData: item } = props

  return (
    <View>
      <View>{item.text}</View>
    </View>
  )
}
```

### 期望行为

正常渲染组件

### 报错信息

没有报错信息，在1.3.26的时候这种情况下会报错ReferenceError: nextTick is not defined
在1.3.27没有这个报错了，但是依然获取不到props

### 系统信息

👽 Taro v1.3.26

  Taro CLI 1.3.26 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.26 => 1.3.26
      @tarojs/components: 1.3.26 => 1.3.26
      @tarojs/plugin-babel: 1.3.26 => 1.3.26
      @tarojs/plugin-csso: 1.3.26 => 1.3.26
      @tarojs/plugin-sass: 1.3.26 => 1.3.26
      @tarojs/plugin-uglifyjs: 1.3.26 => 1.3.26
      @tarojs/router: 1.3.26 => 1.3.26
      @tarojs/taro: 1.3.26 => 1.3.26
      @tarojs/taro-alipay: 1.3.26 => 1.3.26
      @tarojs/taro-h5: 1.3.26 => 1.3.26
      @tarojs/taro-qq: 1.3.26 => 1.3.26
      @tarojs/taro-quickapp: 1.3.26 => 1.3.26
      @tarojs/taro-swan: 1.3.26 => 1.3.26
      @tarojs/taro-tt: 1.3.26 => 1.3.26
      @tarojs/taro-weapp: 1.3.26 => 1.3.26
      @tarojs/webpack-runner: 1.3.26 => 1.3.26
      eslint-config-taro: 1.3.26 => 1.3.26
      eslint-plugin-taro: 1.3.26 => 1.3.26
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 1.3.26 => 1.3.26
      stylelint-taro-rn: 1.3.26 => 1.3.26
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息
问题的发现探究过程在论坛上 https://taro-club.jd.com/topic/870/%E4%BD%BF%E7%94%A8useeffect-%E7%BB%84%E4%BB%B6%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0props-%E4%B8%89%E6%A5%BC%E5%B7%B2%E6%B7%BB%E5%8A%A0demo

**Comment by lzs2000131** [comment]
微信小程序，支付宝小程序和H5都正常

**Comment by Chen-jj** [comment]
@lzs2000131 已修复，升级到最新版本即可
