### ISSUE TITLE
无法使用@tarojs/async-await,1.3.25

### ISSUE THREAD

**Issue by is-nan** [NervJS/taro#5038]
### 问题描述

1.3.25使用@tarojs/async-await报错，只要使用@tarojs/async-await就会报错，并且无法渲染出页面,
关闭了ES6 转 ES5，关闭了上传代码时样式自动补全，关闭了代码压缩上传.

### 复现步骤

//使用了async 马上报错.
const xxx=async ()=>{

}

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息

![image](https://user-images.githubusercontent.com/38523283/70410837-61b13080-1a8b-11ea-9758-08c1d52d1770.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by is-nan** [comment]
"@tarojs/async-await": "^1.3.25",
    "@tarojs/components": "1.3.25",
    "@tarojs/redux": "1.3.25",
    "@tarojs/redux-h5": "1.3.25",
    "@tarojs/router": "1.3.25",
    "@tarojs/taro": "1.3.25",
    "@tarojs/taro-alipay": "1.3.25",
    "@tarojs/taro-h5": "1.3.25",
    "@tarojs/taro-swan": "1.3.25",
    "@tarojs/taro-tt": "1.3.25",
    "@tarojs/taro-weapp": "1.3.25",
    "echarts12": "^1.1.5-alpha.0",
    "nerv-devtools": "^1.4.0",
    "nervjs": "^1.4.0",
    "promise-polyfill": "^8.1.3",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "taro-echarts": "^1.1.2",
    "taro-ui": "^2.2.4"

**Comment by shenghanqin** [comment]
@tarojs/async-await是在app.js里面调用的吧？

这个给一个demo
```js
const xxx=async ()=>{

}
```

微信开发者工具，给一下完整的设置截图。

**Comment by is-nan** [comment]
> @tarojs/async-await是在app.js里面调用的吧？
> 
> 这个给一个demo
> 
> ```js
> const xxx=async ()=>{
> 
> }
> ```
> 
> 微信开发者工具，给一下完整的设置截图。

![image](https://user-images.githubusercontent.com/38523283/70412266-54964080-1a8f-11ea-998e-f318a326cce5.png)
app.jsx里面引入了import '@tarojs/async-await'，
async是在其他jsx文件中使用的.

**Comment by shenghanqin** [comment]
@is-nan 你把“增强编译”关掉试试看？
微信官方文档里面的说明 [增强编译](https://developers.weixin.qq.com/miniprogram/dev/devtools/codecompile.html#%E5%A2%9E%E5%BC%BA%E7%BC%96%E8%AF%91)

**Comment by Chen-jj** [comment]
@is-nan 关闭增强编译，重启开发者工具再试试吧。
