### ISSUE TITLE
taro父组件怎么访问子组件 怎么调用子组件的方法 感觉taro组件这块目前复杂一点的都不好写

### ISSUE THREAD

**Issue by ErnestWangZuNian** [NervJS/taro#504]
**问题描述**
taro父组件怎么访问子组件

**系统信息**

 - 操作系统: [e.g. Mac]
 - Taro 版本 [e.g. 最新版]
 - Node.js 版本 [e.g.最新]

**Comment by luckyadam** [comment]
在父组件里用，`this.$scope.selectComponent` 可以选择到子组件

**Comment by ErnestWangZuNian** [comment]
刚升级了taro到目前最新版本  taro ref支持函数了 可以通过ref来获取   taro越来越好了  赞赞赞 

后期可以支持高阶组件的写法就更棒了

**Comment by luckyadam** [comment]
@ErnestWangZuNian 嘿嘿嘿
