### ISSUE TITLE
打包alipay，创建钉钉小程序。ios真机列表页无法加载更多

### ISSUE THREAD

**Issue by maxueli** [NervJS/taro#5041]
build:alipay，使用钉钉小程序，钉钉开发者工具运行正常，真机测试安卓正常，ios列表页无法显示。
最后使用微信小程序，真机都正常。

列表页通过redux异步请求数据，使用map方法渲染item组件，通过props方式传递数据，
初始化第一页数据时，item组件能通过props拿到数据，触发加载更多请求其他页数时，item拿不到props数据。
[开发者工具上的视频：](http://damei.oss-cn-hangzhou.aliyuncs.com/video/xcx/c5028f283918748f1ee79c188829cd00.mp4)
[ios真机视频：](http://damei.oss-cn-hangzhou.aliyuncs.com/video/xcx/828b31143fb57a15790cbfd0a8e540fa.mp4)

**Comment by maxueli** [comment]
#redux数据更新了，但试图没更新

**Comment by maxueli** [comment]
//Index
![image](https://user-images.githubusercontent.com/23380934/70440944-4fa4b180-1ace-11ea-9526-90e0627a7f95.png)

//List
![image](https://user-images.githubusercontent.com/23380934/70440990-66e39f00-1ace-11ea-9389-56f584530b6e.png)

//Item
![image](https://user-images.githubusercontent.com/23380934/70441067-91cdf300-1ace-11ea-81e2-baf9b808c8a7.png)

//reducers
![image](https://user-images.githubusercontent.com/23380934/70441134-b88c2980-1ace-11ea-83f1-77ccc59ad663.png)

**Comment by shenghanqin** [comment]
@maxueli 升级到最新版试试看？你还得用taro info提供完整信息

**Comment by DevanXU** [comment]
我也遇到同样的问题

**Comment by DevanXU** [comment]
@shenghanqin 这个问题一直都有，我看issue列表里有人从1.3.10就提过这个问题[#4970](https://github.com/NervJS/taro/issues/4970)了，一直没解决。另外，刚刚有人在头条上也遇到类似问题[#5130](https://github.com/NervJS/taro/issues/5130)。这是个很基础的问题，没有解决基本上就无法继续下去了，希望能尽早解决。

以下是我本地的taro info：

👽 Taro v1.3.27
  Taro CLI 1.3.27 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/components: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-babel: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-csso: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-sass: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-uglifyjs: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/redux: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/redux-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/router: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-alipay: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-swan: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-tt: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-weapp: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/webpack-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-config-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-plugin-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.12.0 => 16.12.0 
      stylelint-config-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9 
      stylelint-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9 
    npmGlobalPackages:
      typescript: 3.7.2
