### ISSUE TITLE
H5模式下如何拦截app.js的render入口

### ISSUE THREAD

**Issue by VanquisherMe** [NervJS/taro#5043]
### 问题描述
H5模式开发
我需要在app.js 入口请求一个授权来获得token,在pages下的路由页面获取到，但是app.js 里面的请求是一个异步，没法拦截pages路由的渲染，我应该怎么做？

### 复现步骤

1. 我需要的样子
<img width="486" alt="WechatIMG3199" src="https://user-images.githubusercontent.com/4927398/70454412-5854b200-1ae5-11ea-9710-143461427709.png">
2. 编译后
<img width="459" alt="WechatIMG3200" src="https://user-images.githubusercontent.com/4927398/70454436-6276b080-1ae5-11ea-8161-c5424f6ba3a9.png">
3.app.js 的render 也没有办法修改
4.我无法完成样的逻辑

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
建议先展示无token的页面，请求到token后再更新页面UI

**Comment by luckymore** [comment]
@Littly 小小，这个不能实现的原理是什么？能给个代码行么，想看看

**Comment by yoyo837** [comment]
不就是条件渲染吗?
