### ISSUE TITLE
使用globalData.js，在主包和分包中set/get不匹配

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#5054]
### 问题描述

使用globalData.js，在主包和分包中set/get匹配不上，实测是taro问题

### 复现步骤
主包中```set('a','主包')``` 主包中```get('a'):'主包'```
分包中```set('a','分包')``` 分包中```get('a'):'分包'```
主包中```set('a','主包')``` 分包中```get('a'):'undefined'```
分包中```set('a','主包')``` 主包中```get('a'):'undefined'```

实测用taro新建项目会出现上面问题，感觉分包和主包中隔离了两份globalData.js

附件是复现的demo，其中alipayDemo是支付宝原生新建项目，taroDemo是taro新建项目
复现步骤一样，

1. 首页点击到主包页面：set('a','主包')，
2. 再点击到分包页面：set('a','分包')，
3. 然后再返回首页，原生项目显示'a'：分包，taro项目显示‘a’：主包

[复现demo.zip](https://github.com/NervJS/taro/files/3943625/demo.zip)

**Comment by fanlvwen** [comment]
支付宝问题，模拟器都正常，真机不行

**Comment by Chen-jj** [comment]
@fanlvwen 支付宝主包和每个分包的全局都不一样的，需要挂在 my 上共享全局对象，翻翻以往支付宝分包的问题吧，我记得放 redux 是已经修复的
