### ISSUE TITLE
props数组成员无法正常更新渲染

### ISSUE THREAD

**Issue by zicjin** [NervJS/taro#5055]
### 问题描述

hook组件的props数组成员无法正常更新渲染

### 复现步骤
最简化demo：
https://github.com/zicjin/taro-test
使用标准项目新建流程。typescript，无css预处理。

```js
export default function Shelves(props) {
  const { specs = [] } = props

  // const specs = [{
  //   'id': 482,
  //   'detail': [],
  //   'price': 30,
  //   'platformPrice': 10,
  //   'profit': 20,
  //   'marketPrice': 25,
  //   'stock': 480,
  //   'commissionRate': null
  // }]

  const [profits, setProfits] = useState(specs.map(s => ({
    specId: s.id,
    profit: 0
  })))

  const setProfit = (e, i) => {
    profits[i].profit = +e.detail.value
    setProfits([...profits])
  }

  return (
    <View className='shelves' style={{ marginBottom: '100px' }}>
      {specs.map((s, i) => <View key={i}>
        <Input
          type='number'
          value={profits[i].profit}
          onInput={e => { setProfit(e, i) }}
        />

        {/* confuse: 无法移除 toString() */}
        <View style={{ marginTop: '20px' }}>{profits[i].profit}</View>
        <View>{profits[i].profit.toString()}</View>

      </View>)}
    </View>
  )
}
```

当我更改input值，“profits[i].profit”无法正常更新。以下情况可正常更新：
1. 加上toString()即可正常。
2. 使用组件内部变量代替 props.specs 即可正常
3. props.specs 更换为object，修改useState(specs.map... 即可正常
4. 纯react应用也没有问题：https://codesandbox.io/s/jolly-wescoff-1y633?fontsize=14&hidenavigation=1

### 系统信息
 Taro v1.3.27
  Taro CLI 1.3.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 13.0.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.0 - C:\Program Files\nodejs\npm.CMD

**Comment by dxd1102** [comment]
userState 真正响应的是新生成的对象，你去改数组里的数据肯定不会变啊.
`const a = specs.map(s => ({
    specId: s.id,
    profit: 0
  }))
useState(a)

a[0].specId = 1111
`

**Comment by zicjin** [comment]
@dxd1102  你可以看codesandbox demo: codesandbox.io/s/jolly-wescoff-1y633?fontsize=14&hidenavigation=1
数组解构是完全可以更新的。

**Comment by dreamthen** [comment]
{list: [{like: false}]}数组对象里面的对象属性值like变了，变成了true，这时候我返回一个新的对象，新的对象里面的数据是变掉了，{list:[{like: true}]}，但是页面并没有刷新，还是原来的效果，这就是问题所在。

**Comment by zicjin** [comment]
@dreamthen 这根本不是本问题所在。请问为什么加上toString()页面就更新了？
另外请看react应用demo: https://codesandbox.io/s/jolly-wescoff-1y633?fontsize=14&hidenavigation=1

**Comment by Chen-jj** [comment]
#5012

**Comment by zicjin** [comment]
@Chen-jj  这么严重的问题就这样close了？！！
我看了一下从1.3.26发布已经13天了。这个问题一直都没有解决。太可怕的项目了。

**Comment by dreamthen** [comment]
@zicjin 好像已经解决了

**Comment by zicjin** [comment]
至少发了1.3.28再close吧

**Comment by dreamthen** [comment]
1.3.27已经可以了，我刚刚试过了

**Comment by zicjin** [comment]
@dreamthen 我的最简化demo就是1.3.27。 https://www.npmjs.com/package/@tarojs/taro-weapp 7天前publish的。

**Comment by dreamthen** [comment]
https://github.com/NervJS/taro/commit/0892241461a72318fde4e5a3e7298101b26d113b  @zicjin 他是刚刚直接push的master
