### ISSUE TITLE
使用 typescript ， hooks , redux 下 显示类型不匹配

### ISSUE THREAD

**Issue by Zigei** [NervJS/taro#5056]
### 问题描述
使用 typescript ， hooks , redux 下 显示类型不匹配

### 复现步骤
```js
import Taro, { FC } from '@tarojs/taro'
import { connect } from '@tarojs/redux'
import { AtMessage } from 'taro-ui'
import { View } from '@tarojs/components'

type IProps ={}
// 类型改为 any 就不会报错了 但是失去代码提示
const Demo: FC = (props: IProps) => {
  return (
    <View>
      <AtMessage />
    </View>
  )
}
Demo.config = {
  navigationBarTitleText: ''
}
Demo.options = {
  addGlobalClass: true
}
export default connect(({ }) => ({}), (dispatch) => ({}))(Demo)

```

### 期望行为

更新 taro-redux 的 d.ts 文件

### 报错信息

类型“FunctionComponent<{}>”的参数不能赋给类型“ComponentClass<{}, any>”的参数。
  类型“FunctionComponent<{}>”提供的内容与签名“new (props: {}, context?: any): Component<{}, any, any>”不匹配。ts(2345)

### 系统信息
👽 Taro v1.3.26

  Taro CLI 1.3.26 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.2.2

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
试一下
```ts
const Demo: FC<IProps> = (props) => {
  return (
    <View>
      <AtMessage />
    </View>
  )
}
```

**Comment by Zigei** [comment]
> 试一下
> 
> ```ts
> const Demo: FC<IProps> = (props) => {
>   return (
>     <View>
>       <AtMessage />
>     </View>
>   )
> }
> ```
老哥不行啊。 
类型“FunctionComponent<PageStateProps>”的参数不能赋给类型“ComponentClass<{}, any>”的参数。
  类型“FunctionComponent<PageStateProps>”提供的内容与签名“new (props: {}, context?: any): Component<{}, any, any>”不匹配。ts(2345)

**Comment by yuconora** [comment]
hooks 使用 useSelector   @tarojs/redux 中'connect' 与 react-redux 'connect' 定义不一样
[http://taro-docs.jd.com/taro/docs/redux.html](url)
```js
import Taro, { Components } from '@tarojs/taro'
import { useSelector } from '@tarojs/redux'


export const CounterComponent = () => {
  const counter = useSelector(state => state.counter)
  return <View>{counter}</View>
}
```

**Comment by Zigei** [comment]
> hooks 使用 useSelector @tarojs/redux 中'connect' 与 react-redux 'connect' 定义不一样
> [http://taro-docs.jd.com/taro/docs/redux.html](url)
> 
> ```js
> import Taro, { Components } from '@tarojs/taro'
> import { useSelector } from '@tarojs/redux'
> 
> 
> export const CounterComponent = () => {
>   const counter = useSelector(state => state.counter)
>   return <View>{counter}</View>
> }
> ```
使用新语法 ok 老哥谢了

**Comment by dpyzo0o** [comment]
> hooks 使用 useSelector @tarojs/redux 中'connect' 与 react-redux 'connect' 定义不一样
> [http://taro-docs.jd.com/taro/docs/redux.html](url)
> 
> ```js
> import Taro, { Components } from '@tarojs/taro'
> import { useSelector } from '@tarojs/redux'
> 
> 
> export const CounterComponent = () => {
>   const counter = useSelector(state => state.counter)
>   return <View>{counter}</View>
> }
> ```

但是有个问题，h5 用不了 useSelector，有什么好办法吗

**Comment by yuconora** [comment]
h5的话可以使用多端组件的方式
---component
-----test
-------index.tsx
-------index.h5.tsx

```jsx
// index.h5.tsx
import Taro from "@tarojs/taro";
import { View } from "@tarojs/components";
import { connect } from "@tarojs/redux-h5";

type IProps = {
  num: number;
};

function Test({ num }: IProps) {
  return <View>{num}</View>;
}

export default connect(({ counter }) => {
  return { num: counter.num };
})(Test);
```

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。

**Comment by easonchen3** [comment]
如何在ts中使用react-redux去定义useSelector，如何去声明他的类型
`import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";

interface IList{
    todoList :string[]
}

const TodoList: React.FC<IList> = () => {
  const todoList = useSelector(state=>state.todoList);

  return (
    
  );
};

export default TodoList;`

**Comment by easonchen3** [comment]
如何定义useSelector的类型
```typescript
//TodoList.tsx
import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";

interface IList{
todoList :string[]
}

const TodoList: React.FC = () => {
const todoList = useSelector(state=>state.todoList);

return (

);
};

export default TodoList;
```
