### ISSUE TITLE
componentDidUpdate里获取不到prevProps的正确值

### ISSUE THREAD

**Issue by MirGhojam** [NervJS/taro#5057]
componentDidUpdate(prevProps, prevState) {

  console.log(
      "TCL: AddressList -> componentDidUpdate -> prevProps.need2RefreshList !== 
      this.props.need2RefreshList",
      prevProps.need2RefreshList,
      this.props.need2RefreshList,
      prevProps.need2RefreshList !== this.props.need2RefreshList
    );

    if (prevProps.need2RefreshList !== this.props.need2RefreshList) {
      this.onGetAddressData();
    }
  }

### 问题描述

redux更新已成功（图片里的refreshAddressList更新前后的两个值分别为false和true）， 但是componentDidUpdate中获取prevProps里的相应值时就返回更新好的值

![55477D80-B222-4962-AD51-81DE1B98C107](https://user-images.githubusercontent.com/17875337/70515543-774c5600-1b70-11ea-8d15-f199a0a15151.png)
![A0ED4148-3171-4838-A2F2-6BD3DFC2C1C3](https://user-images.githubusercontent.com/17875337/70515545-77e4ec80-1b70-11ea-978b-0848056c830a.png)

### 期望行为

在componentDidUpdate里能正确获取更新前的prevProps

**Comment by li-shuaishuai** [comment]
taro 哪个版本？
类似问题 https://github.com/NervJS/taro/issues/5040

**Comment by Chen-jj** [comment]
@MirGhojam https://github.com/NervJS/taro/pull/4806 这个 pr 只改了微信没改 redux、mobx 等更新逻辑，所以出错了。尽快修复。

**Comment by MirGhojam** [comment]
> taro 哪个版本？
> 类似问题 #5040

1.3.27

**Comment by li-shuaishuai** [comment]
> > taro 哪个版本？
> > 类似问题 #5040
> 
> 1.3.27

更新到 1.3.28 #5040 问题已解决

**Comment by MirGhojam** [comment]
> > > taro 哪个版本？
> > > 类似问题 #5040
> > 
> > 
> > 1.3.27
> 
> 更新到 1.3.28 #5040 问题已解决

运行成功，谢谢

**Comment by shenghanqin** [comment]
我来标注一下问题即可。
