### ISSUE TITLE
咨询个react native的问题

### ISSUE THREAD

**Issue by Leavds** [NervJS/taro#5059]
### 复现步骤

问题是： 目前项目测试是借用的taro-native-shell壳子项目，然后运行taro项目这样调试项目，
比如我们要打Android 或者ios包 是需要把rn_temp这个目录文件复制到壳子taro-native-shell里再去调用rn的打包命令吗？还是需要重新拉个rn的项目考进去，里面的package依赖是否也需要导入目标项目，还是说直接导个rn_temp就可以了。

taro关于rn的不太多，有点不太清楚这块的东西

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Pines-Cheng** [comment]
两种方法都可以。

1. 复制 rn_temp 目录下的到 RN 项目，然后按照 RN 项目步骤正常打包即可。（此方法需要copy package.json 里的依赖，并安装依赖。）

2. 运行 `taro build rn` 打包出 jsbundle，然后将 jsbundle 复制到 RN 项目，修改入口文件 main.jsbundle 为 index.jsbundle ，然后直接打包。

**Comment by Leavds** [comment]
是 react-native init 创建的项目吗 还是 taro-native-shell壳子项目里面

**Comment by Leavds** [comment]
![image](https://user-images.githubusercontent.com/26810069/70690778-5f044480-1cf2-11ea-81ec-20129e37c819.png)
直接把bundle 目录拷到rn 项目吗？ 还是拷到Android的assets目录下

**Comment by Pines-Cheng** [comment]
都一样，唯一的区别是  react-native init  的项目你需要自行集成  expo unimodules

**Comment by Leavds** [comment]
哦哦  我现在 index.bundle  导入assets目录 还有 打出来的drawable放入目录，修改了application里的 正常运行是可以的，
打release包的时候报错  
![image](https://user-images.githubusercontent.com/26810069/70701869-16578600-1d08-11ea-8f05-96846f302dc3.png)

![image](https://user-images.githubusercontent.com/26810069/70701920-2a9b8300-1d08-11ea-9a04-7b4609e83040.png)

**Comment by Leavds** [comment]
搞了半天，唉。。。。。
1 直接在taro 项目里生成bundle文件导入Android项目打包的话是不能打release包
2 需要将taro生成的js文件导入壳子Android项目，将package.json的依赖加入壳子项目json里，
然后打bundle文件，这样做才可以正常打Android包的.

问下我还是偏向于第一种方法，是因为个人打包姿势不对吗？还是就是第二种这样做的

吐槽下，官方文档略有点单薄

**Comment by Pines-Cheng** [comment]
这一块的文档确实需完善一下。

**Comment by smartsimba** [comment]
Taro RN打包这块整吐血了。莫名其妙的错误。我必须新手，希望能出详细的文档，帮助解决一下。谢谢了

**Comment by Pines-Cheng** [comment]
https://taro-club.jd.com/topic/1019/%E5%AE%89%E5%8D%93%E6%89%93%E5%8C%85apk%E9%97%AE%E9%A2%98
