### ISSUE TITLE
支付宝小程序分包后真机上无法传递props到最内层子组件

### ISSUE THREAD

**Issue by itssunyujia** [NervJS/taro#5061]
### 问题描述

支付宝小程序分包后，**真机上**组件的props无法传递到最内层子组件，**模拟器上没有问题**。另外，**支付宝原生代码也无此问题**。不分包则表现正常。

### 复现步骤

1.以下三个组件都在子包中，LoginBiz->Tips->SubContainer
2. LoginBiz在子包页面中使用
3. 真机上点击显示Container组件 看日志SubContainer组件中 render方法并未输入日志
4.demo源码[demo.zip](https://github.com/NervJS/taro/files/3949123/demo.zip)

```js
import Taro, { Component } from "@tarojs/taro";
import { View, Block } from "@tarojs/components";

import "./index.less";

interface Props {
  show?: boolean;
}

export default class SubContainer extends Component<Props> {
  render() {
    const { show = false } = this.props;
    console.log("SubContainer", show);
    return (
      <Block>
        {show && <View className='comp-subcontainer'>{this.props.children}</View>}
      </Block>
    );
  }
}
export { SubContainer };

import { View, Button } from "@tarojs/components";

import Container from "../../../components/container";

import SubContainer from "../../components/container";

import "./index.less";

interface Props {
  showTips?: boolean;
  onHide?: Function;
}

export default class Tips extends Component<Props> {
  handleOnHide = () => {
    this.props.onHide && this.props.onHide();
  };

  render() {
    const { showTips = false } = this.props;
    console.log("Tips showTips", showTips);
    return (
      <View className='comp-tips'>
        <Button onClick={this.handleOnHide}>点击隐藏Container</Button>
        <Container show={showTips}>
          <View>Container</View>
        </Container>
        <SubContainer show={showTips}>
          <View>SubContainer</View>
        </SubContainer>
      </View>
    );
  }
}
export { Tips };


import Taro, { Component } from "@tarojs/taro";
import { View, Button } from "@tarojs/components";

import Tips from "../components/tips";

import "./index.less";

export default class LoginBiz extends Component {
  state = {
    showTips: false
  };

  handleShow = () => {
    this.setState({ showTips: true });
  };

  handleHide = () => {
    this.setState({ showTips: false });
  };

  render() {
    const { showTips } = this.state;
    console.log("LoginBiz showTips", showTips);
    return (
      <View className='comp-login-biz'>
        <Button onClick={this.handleShow}>点击显示Container</Button>
        <Tips showTips={showTips} onHide={this.handleHide}></Tips>
      </View>
    );
  }
}
export { LoginBiz };

```

### 期望行为

 期望最内层组件能接收到props

### 报错信息

 无

### 系统信息

  Taro CLI 1.3.27 environment info:
  
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.1.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.27 => 1.3.27 
      @tarojs/components-qa: 1.3.27 => 1.3.27 
      @tarojs/mobx: 1.3.27 => 1.3.27 
      @tarojs/mobx-h5: 1.3.27 => 1.3.27 
      @tarojs/plugin-babel: 1.3.27 => 1.3.27 
      @tarojs/plugin-csso: 1.3.27 => 1.3.27 
      @tarojs/plugin-less: 1.3.27 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.27 => 1.3.27 
      @tarojs/router: 1.3.27 => 1.3.27 
      @tarojs/taro: 1.3.27 => 1.3.27 
      @tarojs/taro-alipay: 1.3.27 => 1.3.27 
      @tarojs/taro-h5: 1.3.27 => 1.3.27 
      @tarojs/taro-qq: 1.3.27 => 1.3.27 
      @tarojs/taro-quickapp: 1.3.27 => 1.3.27 
      @tarojs/taro-swan: 1.3.27 => 1.3.27 
      @tarojs/taro-tt: 1.3.27 => 1.3.27 
      @tarojs/taro-weapp: 1.3.27 => 1.3.27 
      @tarojs/webpack-runner: 1.3.27 => 1.3.27 
      eslint-config-taro: 1.3.27 => 1.3.27 
      eslint-plugin-taro: 1.3.27 => 1.3.27 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 1.3.27 => 1.3.27 
      stylelint-taro-rn: 1.3.27 => 1.3.27

**Comment by lzs2000131** [comment]
我是遇到了在写复杂的hooks的时候字节跳动小程序内层收不到props

**Comment by shenghanqin** [comment]
> 我是遇到了在写复杂的hooks的时候字节跳动小程序内层收不到props

在微信小程序上用hook上还可以，在字节跳动小程序上，基本的用法就可能出现小问题，更别说hooks啦。
比如，一个render方法里面不要有两个return。

**Comment by Chen-jj** [comment]
@itssunyujia 抱歉，拖这么久才修复。这个提交应该可以了：[a07ec74](https://github.com/NervJS/taro/commit/a07ec74d6d56ac9a966586f76c6017867a217900)
