### ISSUE TITLE
无法使用Taro.createCanvasContext()出来的对象绘制图形

### ISSUE THREAD

**Issue by crazyJiaLin** [NervJS/taro#5063]
### 问题描述
想要使用Taro画个canvas，使用了Taro.createCanvasContext()方法创建context对象的，创建出来的对象可以在控制台打印出来，但是如果使用绘图的方法或定义线条属性什么的，画布上不会显示图形（h5和小程序端都显示不出来）

### 复现步骤
代码如下：
```js
 componentDidMount() {
    let context = Taro.createCanvasContext('canvas');
    console.log(context)
    context.fillRect(50,50,200,200);  // x轴 y轴 宽 和 高 ,绘制“被填充”的矩形
    context.fillStyle = "green";  // 设置或返回用于填充绘画的颜色、渐变或模式
  }

  render() {
    return (
      <View>
        <Canvas style='width: 350px; height: 400px; background: tomato' canvasId='canvas' />
      </View>
    )
  }
```
h5和小程序显示效果
![image](https://user-images.githubusercontent.com/29673653/70607507-864b0b00-1c39-11ea-8403-5e9bd077d991.png)
![image](https://user-images.githubusercontent.com/29673653/70607566-a4b10680-1c39-11ea-8e40-bd01325e7e5e.png)

### 补充信息
不止fillRect（）显示不出来，其他的，比如moveTo基本的线条绘制也显示不出来

**Comment by yuconora** [comment]
试一下加上作用域this.$scope
```js
Taro.createCanvasContext(canvasId, this.$scope)
```

**Comment by crazyJiaLin** [comment]
```js
let context = Taro.createCanvasContext('canvas', this.$scope);
```
试过了，加过this, 也加过this.$scope, 都画不出来，而且h5端会报错，如下图
![image](https://user-images.githubusercontent.com/29673653/70609323-8bf62000-1c3c-11ea-8649-6782590104e0.png)
小程序端还是渲染不出来

**Comment by yuconora** [comment]
绘制完成 调用 context.draw() 没？

**Comment by crazyJiaLin** [comment]
非常感谢，是因为没调用draw()的问题，辛苦了
