### ISSUE TITLE
Taro.requestSubscribeMessage 报错只能通过 tap 手势调用

### ISSUE THREAD

**Issue by divasatanica** [NervJS/taro#5065]
### 问题描述

在按钮 onClick 事件回调中调用 requestSubscribeMessage 方法，报错
‘requestSubscribeMessage:fail can only be invoked by user TAP gesture.’

### 复现步骤
在按钮 onClick 事件回调中调用 requestSubscribeMessage 方法

### 期望行为

正常弹出授权弹窗

### 报错信息

‘requestSubscribeMessage:fail can only be invoked by user TAP gesture.’

### 系统信息

调试基础库： 2.9.4
Taro 版本： 1.3.27

**Comment by cloudZQY** [comment]
这是微信的报错，跟taro没有关系，这个方法必须在tab事件中同步调用。

**Comment by Chen-jj** [comment]
@divasatanica https://nervjs.github.io/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F

**Comment by divasatanica** [comment]
> 这是微信的报错，跟taro没有关系，这个方法必须在tab事件中同步调用。

那应该是我放在 await 其他异步操作后面调用的原因了，谢谢，回去试一下

**Comment by jx-zyf** [comment]
> > 这是微信的报错，跟taro没有关系，这个方法必须在tab事件中同步调用。
> 
> 那应该是我放在 await 其他异步操作后面调用的原因了，谢谢，回去试一下 @cloudZQY

请问您最后怎么解决的？我用的Button组件然后事件是同步的，但是使用Taro的话好像只能通过onClick调用，报的错误和你的一样
