### ISSUE TITLE
闭包函数式组件接收函数参数

### ISSUE THREAD

**Issue by shichaohui** [NervJS/taro#5069]
### 问题描述

闭包函数式组件接收函数参数时，函数参数会被编译成一个成员变量，导致多次调用该组件时函数参数被覆盖。

### 复现步骤

编译前的 TS 代码：
```tsx
const renderItem = (title, onClick) => {
    return (
        <View onClick={onClick}>{title}</View>
    )
}
const renderList = () => {
    return (
        <View>
            {renderItem("title 1", onClick1)}
            {renderItem("title 2", onClick2)}
        </View>
    )
}
```
编译后的JS代码：
```js
var renderClosureItem = function renderClosureItem(_$uid) {
    return function (title, onClick) {
        _this3.anonymousFunc3 = onClick;
        return {
          title: title
        };
    };
};
```
`_this3.anonymousFunc3 = onClick;` 传入的函数参数变成了成员变量，每次调用组件都会覆盖这个变量，导致最终不管点击哪个 Item 都会执行最后一次传入的点击事件。

### 期望行为

期望每个组件都能正常调用各自的函数。

### 报错信息

 无

### 系统信息

Taro v1.3.23
  Taro CLI 1.3.23 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.25 
      @tarojs/cli: 1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/mobx: ^1.3.26 => 1.3.26 
      @tarojs/mobx-h5: ^1.3.25 => 1.3.25 
      @tarojs/mobx-rn: ^1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-qq: 1.3.25 => 1.3.25 
      @tarojs/taro-quickapp: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.5 
      nervjs: ^1.5.5 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息

无

**Comment by shichaohui** [comment]
不只是函数参数，闭包函数式组件内部的函数也会被编译成全局变量。
编译前：
```jsx
const renderItem = title => {
    return <View onClick={() => console.log(title)}>title</View>
}

const renderItem2 = title => {
    const onClick = () => console.log(title)
    return <View onClick={onClick}>title</View>
}
```
编译后：
```js
var renderClosureItem = function renderClosureItem(_$uid) {
    return function (title) {
        _this3.anonymousFunc0 = function () {
            return console.log(title);
        };
        return {};
    };
};

var renderClosureItem2 = function renderClosureItem2(_$uid) {
    return function (title) {
        var onClick = function onClick() {
            return console.log(title);
        };
        _this3.anonymousFunc1 = onClick;
        return {};
    };
};
```

**Comment by Chen-jj** [comment]
@shichaohui 是有这个问题，先把 renderItem 抽成一个单独的组件吧，编译时 + 运行时不好处理这种情况，Taro 3 才能得到根治。
