### ISSUE TITLE
实时日志api什么时候支持

### ISSUE THREAD

**Issue by Anjing1993** [NervJS/taro#5072]
### 问题描述

我们准备接入微信小程序的[实时日志功能](https://developers.weixin.qq.com/miniprogram/dev/extended/log/)，测试期间发现taro上没有实时日志这个api getRealtimeLogManager，辛苦看下是不是还未支持，预计什么时候支持

### 复现步骤
使用官方推荐的封装，将wx.getRealtimeLogManager换为taro.getRealtimeLogManager，调用即可

### 期望行为

支持和这个api

### 报错信息

无

### 系统信息

👽 Taro v1.3.27

  Taro CLI 1.3.27 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^1.3.19 => 1.3.19 
      @tarojs/components: 1.3.19 => 1.3.19 
      @tarojs/plugin-babel: 1.3.19 => 1.3.19 
      @tarojs/plugin-csso: 1.3.19 => 1.3.19 
      @tarojs/plugin-sass: 1.3.19 => 1.3.19 
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19 
      @tarojs/router: 1.3.19 => 1.3.19 
      @tarojs/taro: 1.3.19 => 1.3.19 
      @tarojs/taro-alipay: 1.3.19 => 1.3.19 
      @tarojs/taro-h5: 1.3.19 => 1.3.19 
      @tarojs/taro-qq: 1.3.19 => 1.3.19 
      @tarojs/taro-quickapp: 1.3.19 => 1.3.19 
      @tarojs/taro-swan: 1.3.19 => 1.3.19 
      @tarojs/taro-tt: 1.3.19 => 1.3.19 
      @tarojs/taro-weapp: 1.3.19 => 1.3.19 
      @tarojs/webpack-runner: 1.3.19 => 1.3.19 
      eslint-config-taro: 1.3.19 => 1.3.19 
      eslint-plugin-taro: 1.3.19 => 1.3.19 
      nerv-devtools: ^1.4.6 => 1.4.6 
      nervjs: ^1.4.6 => 1.4.6 
      stylelint-config-taro-rn: 1.3.19 => 1.3.19 
      stylelint-taro-rn: 1.3.19 => 1.3.19 
    npmGlobalPackages:
      typescript: 3.3.3333

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by lonquan** [comment]
直接使用
```javascript
let log = Taro.getRealtimeLogManager ? Taro.getRealtimeLogManager() : null 
```
即可

**Comment by Anjing1993** [comment]
> 直接使用
> 
> ```js
> let log = Taro.getRealtimeLogManager ? Taro.getRealtimeLogManager() : null 
> ```
> 
> 即可

taro没有支持这个api哦，你可以试试，拿到的undefined哦，可以这样
let log = Taro.getRealtimeLogManager ? Taro.getRealtimeLogManager() : (wx.getRealtimeLogManager()?wx.getRealtimeLogManager():null)

**Comment by Chen-jj** [comment]
@Anjing1993 以后遇到 api 还没支持的话，提个 PR 就好了，很简单的。https://nervjs.github.io/taro/docs/debug.html#api-%E9%97%AE%E9%A2%98

**Comment by Garfield550** [comment]
@Chen-jj 缺 Typings 哟
