### ISSUE TITLE
"@tarojs/components": "1.3.29" 图片组件bug

### ISSUE THREAD

**Issue by heshuai326** [NervJS/taro#5076]
### 问题描述

![image](https://user-images.githubusercontent.com/18663991/70761648-dd132a80-1d88-11ea-9e69-5d36b7cd9556.png)

### 复现步骤
"@tarojs/components": "1.3.29" 图片组件bug 
lazyImg会报undefined的错误，对比了1.3.26 版本发现有出入
#### 1.3.29版本
  componentDidMount () {
    if (this.props.lazyLoad) {
      this.observer = new IntersectionObserver((entries, observer) => {
        // 异步 api 关系
        if (entries[entries.length - 1].isIntersecting) {
          this.setState({ isLoaded: true }, () => {
            lazyImg.unobserve(this.imgRef)
            Nerv.findDOMNode(this).children[0].src = this.props.src
          })
        }
      }, {
        rootMargin: '300px 0px'
      })
      this.observer.observe(this.imgRef)
    }
  }
#### 1.3.26版本
componentDidMount () {
    if (this.props.lazyLoad) {
      const lazyImg = new IntersectionObserver((entries, observer) => {
        // 异步 api 关系
        if (entries[entries.length - 1].isIntersecting) {
          this.setState({ isLoaded: true }, () => {
            lazyImg.unobserve(this.imgRef)
            Nerv.findDOMNode(this).children[0].src = this.props.src
          })
        }
      }, {
        rootMargin: '300px 0px'
      })
      lazyImg.observe(this.imgRef)
    }
  }
### 期望行为

在下一版本可以修复

### 报错信息
LazyImage is undefined

**Comment by Garfield550** [comment]
这是 #4975 修改时的疏忽，@Lostsory 麻烦您再提交一个 PR 修改一下吧

**Comment by Lostsory** [comment]
#4998这个是我提交的pr,当时一直没有通过。

**Comment by Garfield550** [comment]
重启一下 CI，过了就合并一下。

**Comment by Littly** [comment]
1.3.32版本中已经修复
