### ISSUE TITLE
关于全局样式的问题（更新到 1.0.0-beta.14 后组件样式报错）

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#508]
**问题描述**
在`src/app.scss`中我使用了一些`标签选择器`和`属性选择器`来制定一些全局样式，但是更新到 1.0.0-beta.14 后，会自动在每个组件的样式文件中引入编译后的 `app.wxss`，而微信小程序目前不支持在自定义组件中使用`标签选择器`、`ID选择器`、`属性选择器`，所以引发报错并忽略组件样式文件。

**复现步骤**
1. 在`src/app.scss`中使用了一些`标签选择器`、`ID选择器`或`属性选择器`
2. 编写一个自定义组件
3. 编译

**期望行为**
我认为不应该直接引入`src/app.scss`文件，或者至少加一个配置可以关掉，因为全局样式里经常会使用`标签选择器`和`属性选择器`，那样直接把全局样式引入自定义组件样式里会报错并忽略整个文件。

这两种方法可以代替直接引入`src/app.scss`文件来解决全局样式的问题：

1. 直接启用[全局样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#全局样式类) ，也就是将组件构造器中的`options.addGlobalClass`字段置为true，这样外部的样式就会影响到这个`自定义组件`。

但是这样存在外部非全局样式污染组件样式的风险，比如在一个自定义组件里对某个元素设置了样式，而在引入它的页面使用了`元素选择器`或者有个另外的元素跟它类名一样，就可能会覆盖掉组件的样式。

当然通过良好的命名可以避免这种问题，而且小程序自定义组件内部的样式只对组件内元素有效，而页面样式也仅对当前页面有效，已经极大的降低了样式污染的几率。

2. 可以使用小程序自定义组件的[外部样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#外部样式类)或[全局样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#全局样式类)，给每个自定义组件添加一个类名（比如组件名），然后改为 `app.scss`中自动引入组件名。

比如：有两个自定义组件`search`和`cell`，

而全局样式文件`src/app.scss`内容为：
```sass
Text {
  font-size: 20px;
  color: #444;
}
.block {
  padding: 20px 40px;
}
```

然后给每个自定义组件添加一个[外部样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#外部样式类)或[全局样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#全局样式类)，类名就是`component-`+组件名。

最后把`src/app.scss`先预处理为以下格式再编译：

```sass
.component-search,
.component-cell {
  Text {
    font-size: 20px;
    color: #444;
  }
  .block {
    padding: 20px 40px;
  }
}
```
这样就只有全局样式才能影响组件的样式了，而其它地方的局部样式（页面样式）就不会影响到组件内部。

3. 自动给每个元素及一些常用的属性（比如disabled）添加一个类名，然后把`标签选择器`和`属性选择器`修改为`类名选择器`。

比如：
```html
<Button disabled>禁用按钮</Button>
```
和
```css
Button[disabled] {
  background: #e8e8e8;
  color: #c9c9c9;
}
```
编译成：
```html
<button class="button disabled" disabled>禁用按钮</button>
```
和
```css
.button.disabled {
  background: #e8e8e8;
  color: #c9c9c9;
}
```

不过当属性是动态改变时可能会很难弄。

**报错信息**

![image](https://user-images.githubusercontent.com/21964227/44445825-1e704b80-a615-11e8-8f31-047e78ee0a2a.png)

```
VM1089:2 Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./components/Loading/index.wxss:159:10)This wxss file is ignored.
```

**系统信息**

 - 操作系统: Windows 10
- Taro 版本 v1.0.0-beta.14
- Node.js 版本 v8.11.2

**Comment by luckyadam** [comment]
@vimcaw 我看了一下[全局样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%E7%B1%BB)的说明，将组件构造器中的`options.addGlobalClass`字段置为true就可以直接受外部样式影响了，应该就不用做 issue 中提到的样式编译操作了吧

**Comment by vimcaw** [comment]
但是`全局样式`经常会使用`标签选择器`和`属性选择器`，而自定义组件不支持这些选择器，那样直接引用`app.wxss`就会报错并忽略整个样式文件了，所以我想通过[外部样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#外部样式类)或[全局样式类](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#全局样式类)转而在组件外部定义全局样式，那样就可以使用`标签选择器`和`属性选择器`了。

**Comment by luckyadam** [comment]
@vimcaw 恩，`beta.15` 去掉了直接 `import`  `app.wxss` 的功能，增加了组件 `static options` 的支持，方案一我觉得可以的，后续可以加入支持~

**Comment by vimcaw** [comment]
@luckyadam 非常感谢！`options.addGlobalClass` 字段置为true后，全局样式已经可以影响到自定义组件了。

**Comment by luckyadam** [comment]
#426
