### ISSUE TITLE
 useState中设置新 state无法触发渲染

### ISSUE THREAD

**Issue by Anjing1993** [NervJS/taro#5080]
### 问题描述

我有一个多选组件，假如有两个选项，多选出现异常，且每次无法选中上次未选中的那个选项，但是h5是好的（之前taro版本是1.3.14的时候这个功能在微信小程序是正常的）

### 复现步骤

[详细可见demo](https://github.com/Anjing1993/myTestCode)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

期望和H5一样的多选功能

### 报错信息

编译或者运行都无报错

### 系统信息
👽 Taro v1.3.27

Taro CLI 1.3.27 environment info:
System:
OS: macOS 10.15.1
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.0.0 - /usr/local/bin/node
Yarn: 1.12.3 - /usr/local/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm
npmPackages:
@tarojs/cli: ^1.3.19 => 1.3.19
@tarojs/components: 1.3.19 => 1.3.19
@tarojs/plugin-babel: 1.3.19 => 1.3.19
@tarojs/plugin-csso: 1.3.19 => 1.3.19
@tarojs/plugin-sass: 1.3.19 => 1.3.19
@tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19
@tarojs/router: 1.3.19 => 1.3.19
@tarojs/taro: 1.3.19 => 1.3.19
@tarojs/taro-alipay: 1.3.19 => 1.3.19
@tarojs/taro-h5: 1.3.19 => 1.3.19
@tarojs/taro-qq: 1.3.19 => 1.3.19
@tarojs/taro-quickapp: 1.3.19 => 1.3.19
@tarojs/taro-swan: 1.3.19 => 1.3.19
@tarojs/taro-tt: 1.3.19 => 1.3.19
@tarojs/taro-weapp: 1.3.19 => 1.3.19
@tarojs/webpack-runner: 1.3.19 => 1.3.19
eslint-config-taro: 1.3.19 => 1.3.19
eslint-plugin-taro: 1.3.19 => 1.3.19
nerv-devtools: ^1.4.6 => 1.4.6
nervjs: ^1.4.6 => 1.4.6
stylelint-config-taro-rn: 1.3.19 => 1.3.19
stylelint-taro-rn: 1.3.19 => 1.3.19
npmGlobalPackages:
typescript: 3.3.3333

### 补充信息
发现在1.3.26的版本对useState进行了优化，优化之前多选的功能是正常的。
点击多选，打断点时发现这里获取到的当前值和新值是一样的，return掉了，所以没有渲染，但是其实我当前值和新值是不一样的
![image](https://user-images.githubusercontent.com/9416309/70792096-76672e80-1dd3-11ea-9b5d-2c1902b7e73a.png)

**Comment by Chen-jj** [comment]
@Anjing1993 表现是正确的，和 React 保持一致。再看看 useState 用法吧。
