### ISSUE TITLE
自定义组件 编译为微信小程序后 className 属性没被编译为class属性。

### ISSUE THREAD

**Issue by jojol** [NervJS/taro#5084]
### 问题描述
创建了一个自定义控件ChannelItem，使用该控件时 设置了className属性“flex1”，编译为微信小程序后 没有该属性。

控件使用的源码：
```js
          <View className='view-h flex1'>
            <ChannelItem className='flex1' icon={SIcons.treat_wcdna} lab='分类' />
            <ChannelItem className='flex1' icon={SIcons.treat_cjjl} lab='首页' />
            <ChannelItem className='flex1' icon={SIcons.treat_ckzk} lab='搜索' />
            <ChannelItem className='flex1' icon={SIcons.treat_hzxx} lab='设定' />
          </View>

```

编译为微信小程序后 ChannelItem 的class属性 “flex1” 没有
```js
    
      <view class="view-h flex1">
        <channel-item compid="{{$compid__4}}"></channel-item>
        <channel-item compid="{{$compid__5}}"></channel-item>
        <channel-item compid="{{$compid__6}}"></channel-item>
        <channel-item compid="{{$compid__7}}"></channel-item>
      </view>
```
![image](https://user-images.githubusercontent.com/4338887/70844513-0e6d2280-1e7d-11ea-9b06-69b6b2c7d150.png)
![image](https://user-images.githubusercontent.com/4338887/70845173-580e3b00-1e86-11ea-8760-37550f5fd27d.png)
![image](https://user-images.githubusercontent.com/4338887/70845232-fac6b980-1e86-11ea-9400-6bd80c789a9e.png)
![image](https://user-images.githubusercontent.com/4338887/70845217-da96fa80-1e86-11ea-8ab6-b13ca4d0938d.png)

flex样式定义
```js
 .flex1 {flex: 1;}
.flex0 {flex: 0;}
.flex2 {flex: 2;}
.flex3 {flex: 3;}
```

### 期望行为

支持自定义组件className属性

> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuconora** [comment]
自定义组件 外部样式 需要设置 externalClasses
Taro里面也需要这么做
[https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html](url)

```jsx
// component
function Test() {
  return <View className={classNames('my-class', styles.test)}>test</View>
}

Test.externalClasses = ['my-class']
```

```jsx
// use
function Index() {
  return <Test my-class='other' />
}
```

**Comment by yuconora** [comment]
微信小程序 可以试一下 externalClasses
支付宝小程序官方好像暂不支持添加外部样式
[https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html](url)

```jsx
// component
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'
import classNames from 'classnames'
import styles from './index.module.scss'

function Test() {
  return <View className={classNames('my-class', styles.test)}>test</View>
}

Test.externalClasses = ['my-class']

export default Test
```
```jsx
// use it
function Index() {
  return <Test my-class='other' />
}
```

**Comment by Chen-jj** [comment]
@jojol 不要给自定义组件设置 className，只能给内置组件设置。

**Comment by ZevenFang** [comment]
直接在`app.js`全局设置：
```jsx
import Taro, { Component } from '@tarojs/taro';
Component.options = {addGlobalClass: true}; // 允许组件全局样式
```
