### ISSUE TITLE
web-public

### ISSUE THREAD

**Issue by guoqirong** [NervJS/taro#5085]

**Comment by guoqirong** [comment]
web-public

**Comment by guoqirong** [comment]
初始化项目卡在拉取框架taro-project-templates上

**Comment by shenghanqin** [comment]
请提供taro-cli版本、node版本、错误截图等更多细节。
以及当前你使用的网络环境，比如国内网络、VPN等。

**Comment by Garfield550** [comment]
`taro-project-templates` 是一个 GitHub 仓库，如果卡在获取模板步骤，应该是你的网络有问题。
