### ISSUE TITLE
2.0.0-beta.8 小程序地图组件

### ISSUE THREAD

**Issue by LetterYan** [NervJS/taro#5087]
### 问题描述
2.0.0-beta.8 小程序地图组件iconPath设置后在真机上显示不出来，开发者工具模拟器正常。
1.3.x版本正常显示

// 模拟器
![image](https://user-images.githubusercontent.com/34398562/70858224-273b0e00-1f39-11ea-8103-e517227dbb8c.png)

// 安卓真机
![image](https://user-images.githubusercontent.com/34398562/70858239-8e58c280-1f39-11ea-9ec9-6cd74f324491.png)

// ios真机
![image](https://user-images.githubusercontent.com/34398562/70858275-25257f00-1f3a-11ea-8129-c0b24464f7ac.png)

// icoPath路径的文件
![image](https://user-images.githubusercontent.com/34398562/70858241-90228600-1f39-11ea-8c59-ce263f2563b8.png)

### 复现步骤

```
const obj = {
          longitude: item.shopPo.pointx,
          latitude: item.shopPo.pointy,
          id: item.shopPo.id,
          width: item.isSupShop ? 27.5 : 22.5,
          height: 26.5,
          zIndex: item.isSupShop ? 3 : 2,
          iconPath: item.shopPo.active
            ? item.isSupShop
              ? require("./img/supShop.png")
              : require("./img/addrsup.png")
            : item.isSupShop
            ? require("./img/shop.png")
            : require("./img/addr.png")
        };
```

### 期望行为

和模拟器一样正常显示icon

### 系统信息

  Taro CLI 2.0.0-beta.8 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/mini-runner: ^2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-babel: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-csso: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-sass: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-uglifyjs: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/router: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-alipay: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-h5: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-swan: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-tt: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-weapp: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/webpack-runner: 2.0.0-beta.8 => 2.0.0-beta.8 
      eslint-config-taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      eslint-plugin-taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.12.0 => 16.12.0 
      stylelint-config-taro-rn: 2.0.0-beta.8 => 2.0.0-beta.8 
      stylelint-taro-rn: 2.0.0-beta.8 => 2.0.0-beta.8

**Comment by Garfield550** [comment]
微信小程序组件使用的都是各端原生组件，如果一个组件在出现不同平台的兼容性问题，可以先尝试用原生方式做一个Demo 来确认是否是组件本身的问题。

**Comment by LetterYan** [comment]
> 微信小程序组件使用的都是各端原生组件，如果一个组件在出现不同平台的兼容性问题，可以先尝试用原生方式做一个演示来确认是否是组件本身的问题。


试了一下原生的路径写法，真机上加载出来都是正常的。
可能是require路径编译的问题

![image](https://user-images.githubusercontent.com/34398562/70859560-a851cf80-1f50-11ea-9c5e-37f49036fa7c.png)
![image](https://user-images.githubusercontent.com/34398562/70859636-f7e4cb00-1f51-11ea-9f21-5971e018f0f1.png)

**Comment by Garfield550** [comment]
试试使用 import addrImg from './addr.png'; 写法

**Comment by LetterYan** [comment]
> 试试使用 `import addrImg from './addr.png';` 写法

试了import写法，最后结果是一样的

**Comment by GrasFishs** [comment]
Taro2.0.2也遇到了真机（安卓）不显示iconPath图片的问题

**Comment by Lemonreds** [comment]
![image](https://user-images.githubusercontent.com/23014238/76314992-cbeba280-6312-11ea-99a9-acf61b453994.png)
有解决方案么？因为这个问题 @LetterYan

**Comment by LetterYan** [comment]
> ![image](https://user-images.githubusercontent.com/23014238/76314992-cbeba280-6312-11ea-99a9-acf61b453994.png)
> 有解决方案么？因为这个问题 @LetterYan

临时方案就是先用网络路径。

**Comment by Lemonreds** [comment]
我用的是支付宝原生实现了，也可以解决问题。
`
  iconPath: isActive
            ? "/static/images/officer2.png"
            : "/static/images/officer1.png",
`
这个路径是相对于 dist 打包过后的相对路径，

**Comment by GrasFishs** [comment]
改了`mini.imageUrlLoaderOption`的配置解决了iconPath的问题了。
```
mini: {
    imageUrlLoaderOption: {
      limit: 0
    }
  }
```
