### ISSUE TITLE
promise化的副作用

### ISSUE THREAD

**Issue by yuquanwang** [NervJS/taro#509]
**问题描述**
promise化带来的问题，promise返回的是Promise对象，对于微信中本身返回task对象的api，promise化如何才能拿到task对象呢？

**复现步骤**

```js
export default class extends Component {

  componentDidMount() {
    const task = Taro.downloadFile({url: 'https://max.book118.com/free_down/0127556342011.pdf'}).then(res => {
      console.log('res: ', res);
    });

    console.log('task: ', task);

    task.onProgressUpdate(res => {
      console.log('res: ', res);
    }); // 这里的task是promise对象，会报错
  }
...
}

```

**期望行为**
promise化的情况下拿到api本来要返回的对象

**报错信息**
![image](https://user-images.githubusercontent.com/16618169/44459823-8aff4080-a63d-11e8-8665-78cae69f5d9f.png)

**Comment by AlexStacker** [comment]
写法不对吧，应该是`res`变成了`task`，在then里写 `res.onProgressUpdate` 试试

**Comment by yuquanwang** [comment]
@luckyadam 我想拿到的是微信api文档的downloadTask，不是Promise resolve的res，如下图方框中
![image](https://user-images.githubusercontent.com/16618169/44498407-d3a41180-a6b0-11e8-93d1-4cce1a8d0a5f.png)
如何在promise后的语法中得到它？或者说为了得到它，应该对promisfy的源码做怎样的修改呢？

**Comment by luckyadam** [comment]
@yuquanwang sorry，这里记错了
https://github.com/NervJS/taro/blob/master/packages/taro-weapp/src/native-api.js#L93
应该是这么用
```javascript
componentDidMount() {
    const task = Taro.downloadFile({url: 'https://max.book118.com/free_down/0127556342011.pdf'})

    console.log('task: ', task);

    task.progress(res => {
      console.log('res: ', res);
    });
    task.abort(res => {
      console.log('res: ', res);
    });
  }
```

**Comment by yuquanwang** [comment]
@luckyadam  往promise对象里加方法，great! 👍，希望更新下taro官方文档。

**Comment by luckyadam** [comment]
@yuquanwang 好嘞~

**Comment by chenkefeng** [comment]
> @yuquanwang 好嘞~

普通request 也有需要取消的需求呀

**Comment by luckyadam** [comment]
@chenkefeng 没有提供这个功能哦
