### ISSUE TITLE
微信小程序void expression会直接编译成undefined

### ISSUE THREAD

**Issue by liuweitao111** [NervJS/taro#5091]
### 问题描述
微信小程序void expression会直接编译成undefined
### 复现步骤
源码
![1576471394508](https://user-images.githubusercontent.com/19471014/70879820-c0cdf280-2001-11ea-9fcc-59eedd48abff.jpg)
编译结果
![1576471425573](https://user-images.githubusercontent.com/19471014/70879825-c297b600-2001-11ea-95bc-186936979db5.jpg)
### 期望行为

不对void expression进行编译，或正确处理void expression

### 系统信息
![1576471277944](https://user-images.githubusercontent.com/19471014/70879729-6e8cd180-2001-11ea-89c0-8c3ab3211cd9.jpg)

**Comment by scarcoco** [comment]
这个问题怎么处理呢，引入一个库直接里面void(xxx) 结果变成 undefined 了，关键语句丢失了。。。
