### ISSUE TITLE
React Native项目 Android端 不支持AndroidX吗

### ISSUE THREAD

**Issue by Leavds** [NervJS/taro#5095]
### 复现步骤

如题，React Native项目 Android端 不支持AndroidX吗

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Leavds** [comment]
试了下 不yarn 引入rn的moudle仅仅Android项目转x是有问题的，yarn 编译全部moudle成功后，转Androidx 是可以的。不知道有没有问题。

**Comment by Leavds** [comment]
就第一次成功的  后面 node_modules  的部分 Android moudle  里面的gradle版本 低于3.2 ，手动去改 好多个，额看来 还是不支持Androidx啊。但是好多库 appcompat的  都不维护了

**Comment by Pines-Cheng** [comment]
Taro 默认是基于 RN 0.55.4，而 React Native 0.60+ 才支持 AndroidX。

**Comment by Leavds** [comment]
oo  那升级Androidx  会引起Taro的适配问题吗

**Comment by Pines-Cheng** [comment]
Taro 最终还是会转换成 RN，RN 没影响 Taro 就没影响。

**Comment by Leavds** [comment]
举个例子 expo-av 这个包的是壳子里带的版本，  版本低了 最新的是8.0的，手动更改，会影响壳子的功能么，我全部升级的话
