### ISSUE TITLE
2.0.0-beta8云开发报错，已提供demo

### ISSUE THREAD

**Issue by birdycn** [NervJS/taro#5099]
![image](https://user-images.githubusercontent.com/32201961/70961122-e28bb000-20bb-11ea-973a-b544e43ea3b5.png)

demo地址：https://github.com/birdycn/taro-bug

操作流程

taro init myApp
cd client
cnpm taro-ui
cnpm install

引用

import { AtButton } from 'taro-ui'
<AtButton type='primary'>按钮文案</AtButton>

**Comment by peckbyte** [comment]
出现同样的错误，引用taro-ui组件错误就出现了。
![image](https://user-images.githubusercontent.com/10704067/71053685-395fbb00-218a-11ea-9823-e3a5315fd700.png)

**Comment by luckyadam** [comment]
项目删掉了？
