### ISSUE TITLE
taro/if-statement-in-map-loop 检查错误

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#510]
**问题描述**
taro/if-statement-in-map-loop 在不该报错的地方报错

**复现步骤**
![screen shot 2018-08-22 at 10 10 49 pm](https://user-images.githubusercontent.com/26269173/44468922-eb4fab80-a658-11e8-8371-a70e975cf2e7.png)

```js
if (loading) {
            content = <StatusIndicator fillPage={false} text={"加载中"} />;
        } else if (error) {
            content = <StatusIndicator fillPage={false} text={"出错了 点击重试"} />;
        } else if (_.isEmpty(requests)) {
            content = <StatusIndicator fillPage={false} text={"木有数据"} />;
        } else {
            content = (
                <View>
                    {requests.map(r => <RoommateRequestCard key={r} request={r} />)}
                </View>
            );
        }

```

**期望行为**
这个写法木有错误 可以运行

**报错信息**

**系统信息**

 - 操作系统: Mac
 - Taro 版本 beta15
 - Node.js 版本 v8.10.0

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by vimcaw** [comment]
这个问题确实一直都在，1.0.0-beta.9 的时候看到[fix\(eslint\): 在 map 循环中使用 if 解析错误 · NervJS/taro@902d637](https://github.com/NervJS/taro/commit/902d637)以为修复好了，但是还是这样。

**Comment by yuche** [comment]
你的例子写到了测试用例里 https://github.com/NervJS/taro/commit/daa00318e9982a76c897b2f6d5d19fbfc87021ae

**Comment by kdong007** [comment]
@yuche 效率真高 谢谢 膝盖献上
