### ISSUE TITLE
一些想法和建议

### ISSUE THREAD

**Issue by zhuxianguo** [NervJS/taro#5100]
1.借鉴cordova,webpack,babel的模式，基于插件的taro，对于平台支持，端能力，ui组件可以通过安装插件的形式进行支持
2.taro目前基于nevjs，当然这是基于jd业务来讲为了兼容ie8，是否可以不仅仅局限在jd业务，可以支持可选择react，让使用者根据需要来进行选择nervjs和react
3.taro-cli中转换操作在build和ui中存在重复，构建ui时可重用转换逻辑
4.制定taro多端协议和接口，用户可以基于协议和接口扩展支持，比如用户对端能力和平台的支持，不仅仅局限在taro官方提供的这些范围内
5.是否可以基于多端中间代码构建多端，参考.net中间代码，java中间代码，抽象出多端功能元代码，编译成多端中间代码的上层代码并不局限在react，可以扩展到vue，angular，flutter
6.taro目前还是定位在框架，是否可以考虑也可以提供服务，做成平台

**Comment by yuche** [comment]
全部在做了，除了 6，2.0 正式版发布的时候就会有 3.0 的 alpha 版出来。

**Comment by shenghanqin** [comment]
@yuche 2.0后直接跳跃到3.0，佩服也开心。
