### ISSUE TITLE
可以和relay结合使用吗？有没有人实践过？

### ISSUE THREAD

**Issue by videni** [NervJS/taro#5101]
[facebook relay 代码库]( https://github.com/facebook/relay)

能否兼容一些relay相关的工具，比如：
[react-relay-network-modern](https://github.com/relay-tools/react-relay-network-modern)

我们想法是，在我们的系统中，用relay取代redux。

**Comment by shenghanqin** [comment]
@videni relay的npm包或者GitHub地址是哪一个？请给出你想要的示例、依据。

**Comment by videni** [comment]
@shenghanqin，我添加了描述，请看一看。

**Comment by shenghanqin** [comment]
感觉比较难。因为redux有taro-redux，mobx有taro-mobx，那relay估计也得写类似的适配层。
@luckyadam 可以解答一下。

**Comment by Chen-jj** [comment]
@videni Taro3 应该可以直接使用，可以尝试一下。
