### ISSUE TITLE
[2.0.0 beta 8]小程序打包多端文件app.weapp.tsx会生成app.weapp.json

### ISSUE THREAD

**Issue by leifeng** [NervJS/taro#5102]
### 问题描述
项目里有2个不同入口文件
app.weapp.tsx
app.h5.tsx

执行``yarn dev:weapp``生成`app.weapp.json`，小程序开发工具会报未找到`app.json`

### 复现步骤

同上

### 期望行为

app.weapp.tsx能生成app.json

### 系统信息

�👽 Taro v2.0.0-beta.8
  Taro CLI 2.0.0-beta.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

**Comment by T-toghter** [comment]
同遇到这样的问题

**Comment by luckyadam** [comment]
入口文件暂不支持多端文件的写法。
