### ISSUE TITLE
微信小程序路由页面内hooks 配置 config 的window 背景，不生效， 编译后在开发者工具里显示页面的window 无效

### ISSUE THREAD

**Issue by anryzhang** [NervJS/taro#5103]
### 问题描述
微信小程序路由页面内hooks 配置 config 的window 背景，不生效， 
编译后在开发者工具里显示页面的window 无效警告，但实际编译后的json文件里， 
window 是有的。

### 复现步骤
1. 在一个Hooks组件路由页面下自定义当前页面config.
2. 在config 对象里定义窗口背景
3.编译后，在微信小程序开发者工具里，不显示改过的背景颜色 ，且报无效的 window。

```
hooks 组件页面配置代码：

Detail.config = {
  "window": {
    backgroundColor: '#79cc26',
    enablePullDownRefresh: true
  }
}

```

### 期望行为

正确显示当前hooks 配置

### 报错信息

开发者工具报错如下： 
VM3255:1 无效的 pageJSON(pages/detail/detail)["window"]

### 系统信息

Taro CLI 1.3.29 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm

**Comment by ThoughtZer** [comment]
@anryzhang window 需要吗？不是直接配置的吗

**Comment by Chen-jj** [comment]
@anryzhang 你把全局配置和页面配置混了，再看看微信小程序文档怎么配置吧。 @ThoughtZer 正解。
