### ISSUE TITLE
微信h5端引入WeixinJSBridge

### ISSUE THREAD

**Issue by che0924** [NervJS/taro#5106]
### 问题描述
WeixinJSBridge是微信浏览器自带内置对象，现在我打开新页面直接调WeixinJSBridge中的方法，发现WeixinJSBridge未加载完，请问如何在taro中判断是否引入weixinBridge或者主动引入weixinBridge

### 复现步骤

1.打开新页面直接调用weixinBridge中方法，此时weixinBridge未加载完成，调用失败

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

判断是否引入weixinBridge，或者主动引入weixinBridge
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@che0924 请提供你的代码示例以及index.html的示例
