### ISSUE TITLE
RN 端在 config 中传入 scss 配置会报错

### ISSUE THREAD

**Issue by yeojongki** [NervJS/taro#5110]
### 问题描述 & 复现步骤

- 编译配置中 config.plugins 添加如下
参考 https://taro-docs.jd.com/taro/docs/config-detail.html#%E4%BC%A0%E5%85%A5-scss-%E5%8F%98%E9%87%8F%E5%AD%97%E7%AC%A6%E4%B8%B2
```js
    sass: {
      resource: [
        'src/styles/zIndex.scss'
      ],
      projectDirectory: path.resolve(__dirname, '..'),
      // data: '$nav-height: 48px;',
    }
``` 
- 运行:
```shell
 yarn dev:rn
```
- 会报错:  
错误  样式预处理 Error: Invalid CSS after "null": expected "{", was ""
错误  样式转换  
TypeError: Cannot read property 'toString' of undefined

### 复现 repo
https://github.com/yeojongki/taro-rn-test.git

### 期望行为

正常添加配置并运行 RN 端

### 报错信息
错误  样式预处理  D:\yeojongki\work\taro-rn-test\src\app.scss
```
Error: Invalid CSS after "null": expected "{", was ""
    at Object.module.exports.renderSync (D:\yeojongki\work\taro-rn-test\node_modules\node-sass\lib\index.js:439:16)
    at D:\yeojongki\work\taro-rn-test\node_modules\@tarojs\plugin-sass\index.js:58:21
错误  样式转换  
TypeError: Cannot read property 'toString' of undefined
    at new Input (C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\node_modules\postcss\lib\input.js:57:24)
    at parse (C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\node_modules\postcss\lib\parse.js:21:17)
    at new LazyResult (C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\node_modules\postcss\lib\lazy-result.js:70:24)
    at Processor.process (C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\node_modules\postcss\lib\processor.js:117:12)
    at Object.postCSS (C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\dist\rn\styleProcess.js:84:10)
    at C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\dist\rn.js:73:37        
    at Array.map (<anonymous>)
    at C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\dist\rn.js:72:40        
(node:20132) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'css' of undefined
    at C:\Users\My\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\dist\rn.js:97:19        
(node:20132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### 系统信息

�👽 Taro v1.3.25

  Taro CLI 1.3.25 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\My\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD

### 补充信息
将配置项删除后可以正常运行

**Comment by Pines-Cheng** [comment]
`data: '$nav-height: 48px;'` 为什么要用引号？

**Comment by yeojongki** [comment]
> `data: '$nav-height: 48px;'` 为什么要用引号？

@Pines-Cheng 
这是注释掉了的, 另外这是官网写的:
https://taro-docs.jd.com/taro/docs/config-detail.html#%E4%BC%A0%E5%85%A5-scss-%E5%8F%98%E9%87%8F%E5%AD%97%E7%AC%A6%E4%B8%B2

**Comment by Garfield550** [comment]
@Pines-Cheng `data` 是字符串格式，这个是预期行为

**Comment by yeojongki** [comment]
@shenghanqin answerd ??

**Comment by yeojongki** [comment]
@shenghanqin 你确定 answered ??

**Comment by shenghanqin** [comment]
@yeojongki 如果你有不明白的地方，可以at Garfield550 继续追问。

**Comment by yeojongki** [comment]
@Pines-Cheng @Garfield550 问题可以复现吗

**Comment by tourze** [comment]
这个问题在1.3.35中确认是存在的。
我打印了解析的scss，发现是最后多了一个 null

![image](https://user-images.githubusercontent.com/13899502/73355611-7794e200-42d3-11ea-8afc-49779ec84391.png)

这里的 content ，传入的可能是 null
