### ISSUE TITLE
[2.0.0-beta.8][typescript] tsconfig 设置 noEmitOnError 无效

### ISSUE THREAD

**Issue by dpyzo0o** [NervJS/taro#5111]
### 问题描述

`tsconfig` 中开启 `noEmitOnError: true`，当代码中有类型错误时，taro 会正常编译。

### 复现步骤

tsconfig 配置

```json
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "removeComments": false,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "outDir": "lib",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "baseUrl": ".",
    "rootDir": ".",
    "jsx": "preserve",
    "jsxFactory": "Taro.createElement",
    "allowJs": true,
    "resolveJsonModule": true,
    "typeRoots": ["node_modules/@types", "global.d.ts"],
    "paths": {
      "~/*": ["src/*"]
    }
  }
```

### 期望行为

代码中有类型错误时控制台报错，编译不通过。

### 系统信息

  Taro CLI 2.0.0-beta.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/cli: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/components: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-babel: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-csso: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-sass: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/plugin-uglifyjs: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/redux: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/redux-h5: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/router: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-alipay: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-h5: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-qq: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-quickapp: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-swan: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-tt: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-weapp: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/webpack-runner: 2.0.0-beta.8 => 2.0.0-beta.8 
      eslint-config-taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      eslint-plugin-taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.8 => 2.0.0-beta.8 
      stylelint-taro-rn: 2.0.0-beta.8 => 2.0.0-beta.8 
    npmGlobalPackages:
      typescript: 3.6.3

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by dpyzo0o** [comment]
有人帮忙看一下嘛

**Comment by luckyadam** [comment]
因为 Taro 的编译没有管 tsconfig 的配置，一般 typescript 出错编辑器都会有体现
