### ISSUE TITLE
taro init 报错，报permission defined。

### ISSUE THREAD

**Issue by qingbopro** [NervJS/taro#5116]
![image](https://user-images.githubusercontent.com/30676893/71051745-41b4f780-2184-11ea-8792-408c9ab985fe.png)

**Comment by Garfield550** [comment]
请补充 `taro info` 给出的信息

**Comment by qingbopro** [comment]
@Garfield550 
![image](https://user-images.githubusercontent.com/30676893/71052224-afadee80-2185-11ea-9213-19186a412468.png)

**Comment by shenghanqin** [comment]
@qingbopro 
1、标题写的太含糊，得通读全文才知道是权限问题
2、系统未明确说明，是mac系统还是linux系统？这么看来感觉又是linux系统上yarn的权限有问题。

**Comment by Garfield550** [comment]
@shenghanqin 
第二张截图里给出的系统是 macOS Catalina，大概率是 10.15 的系统权限放严格导致。

这种情况会偶尔发生在直接从 10.14 Mojave 通过系统更新升级至 10.15 Catalina 的设备上，新版本很多目录权限被 OS 修改变得严格，所以可能需要从系统权限和 Yarn 方面解决。

我本人的 macOS Catalina 是删除硬盘所有数据重装过的，一直没有遇到什么权限问题，包括 brew 使用者经常遇到的权限问题也没有遇到。
