### ISSUE TITLE
H5的Image组件mode属性为aspectFill时，与小程序预期效果不一样

### ISSUE THREAD

**Issue by amusiq** [NervJS/taro#5118]
### 问题描述
H5的Image组件mode属性为aspectFill时，与小程序预期效果不一样

### 复现步骤

1. 代码如下：
```jsx
<View className='index'>
        <Image className='test-img' src='https://res.wx.qq.com/wxdoc/dist/assets/img/0.4cb08bb4.jpg' mode='aspectFill' />
 </View>
```

```css
.test-img{
  width:375px;
  height:150px;
  background:#eee;
}
```
2. h5下预览

### 期望行为

与小程序下的mode为aspectFill图片显示效果一致

![image](https://user-images.githubusercontent.com/28551646/71053360-27c9e380-2189-11ea-9abf-329375f29cf6.png)

### 实际效果
![image](https://user-images.githubusercontent.com/28551646/71053374-32847880-2189-11ea-95a7-ad622f17a802.png)

### 系统信息

� Taro v1.3.29

  Taro CLI 1.3.29 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD

**Comment by shenghanqin** [comment]
@amusiq 你可以把h5上实际渲染出来的html dom与css都截图一下，我想看一下。
因为微信小程序上是原生效果，h5上是模拟效果，你得贴出具体代码，指出这个问题。

**Comment by amusiq** [comment]
> @amusiq 你可以把h5上实际渲染出来的html dom与css都截图一下，我想看一下。
> 因为微信小程序上是原生效果，h5上是模拟效果，你得贴出具体代码，指出这个问题。
![1](https://user-images.githubusercontent.com/28551646/71454739-0ee6b100-27cd-11ea-8a42-15cbc404c7d0.png)
![2](https://user-images.githubusercontent.com/28551646/71454741-11e1a180-27cd-11ea-86a3-a11f20627169.png)

**Comment by shichaohui** [comment]
我也遇到了这个问题，请问解决了吗？

**Comment by daiyuanhao** [comment]
h5加上样式，可以解决
.test-img img{
  object-fit: cover
}
