### ISSUE TITLE
[beta2.0.0-beta.8]h5 编译失败，编译后import Taro, { Component } from "@tarojs/taro-h5"; 缺少Config。代码里：import Taro, { Component, Config } from '@tarojs/taro'

### ISSUE THREAD

**Issue by youyou0101** [NervJS/taro#5119]
### 问题描述

h5编译失败，读取不到app.tsx 的config信息。小程序编译正常。

### 复现步骤

1. 运行命令：npm run dev

### 期望行为

运行成功

### 报错信息

```js
./.temp/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (387:9)

  385 |         </Provider>;
  386 |   }
> 387 |   config = {
      |          ^
  388 |     pages: ["/pages/index/index", "/pages/pick_city/index", "/pages/login_by_phone/index", "/pages/user/user_setting/index", "/pages/login/index", "/pages/show_pdf/index", "/pages/mine_book/index", "/pages/user/user_authentication/index", "/pages/user/user_data_edit/index", "/pages/user/user_edit/index", "/pages/house_detail/index", "/pages/book_room/index", "/pages/book_success/index", "/pages/store/detail/index", "/pages/house_detail_building/index"],
  389 |     window: {
  390 |       backgroundTextStyle: 'light',
```

**Comment by youyou0101** [comment]
taro 版本 2.0.0-beta.8

**Comment by youyou0101** [comment]
编译后import Taro, { Component } from "@tarojs/taro-h5"; 缺少Config。代码里：import Taro, { Component, Config } from '@tarojs/taro'

**Comment by youyou0101** [comment]
更新到1.3.30好了。

**Comment by youyou0101** [comment]
Taro CLI 1.3.19 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/components: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mobx: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mobx-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mobx-rn: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-babel: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-csso: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-sass: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/plugin-uglifyjs: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/rn-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/router: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-alipay: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-swan: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-tt: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-weapp: ^2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/webpack-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-config-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-plugin-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9 
      stylelint-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9

**Comment by youyou0101** [comment]
![33333](https://user-images.githubusercontent.com/9896781/71243019-3d3a3b80-234a-11ea-8923-1d6b02dfdc00.jpg)

**Comment by shenghanqin** [comment]
cli还是老版本？1.3.19？cli与业务版本要一致。

Taro CLI 1.3.19 environment info:
System:
OS: macOS High Sierra 10.13.6
Shell: 3.2.57 - /bin/ba

**Comment by youyou0101** [comment]
👽 Taro v2.0.0-beta.9

debug node_env development
debug base_url localhost
debug node_env development

还是不行

**Comment by youyou0101** [comment]
升级后 alias 失效。🙅   编译失败.

./src/pages/login/index.tsx
Module not found: Can't resolve '@/apis/api-login' in '/Users/wsl/Documents/aster-reborn/src/pages/login'

**Comment by youyou0101** [comment]
回退到1.3.30 h5,微信小程序都 编译成功。

**Comment by Garfield550** [comment]
beta 现在还有些问题，会在近期修复。

**Comment by youyou0101** [comment]
好滴好滴

**Comment by novenn** [comment]
这个问题2.0.7版本还是不行啊
现在最新都到3了
请问怎么解决
