### ISSUE TITLE
Taro的代码自动补全没了，怎么调出来

### ISSUE THREAD

**Issue by xiongcheng1107** [NervJS/taro#5120]
其它taro项目看起来没啥问题，提示和补全都很正常

**Comment by Issacpeng** [comment]
@xiongcheng1107   有无taro info信息看看？ 需要一些信息做判断。

**Comment by xiongcheng1107** [comment]
> @xiongcheng1107 有无taro info信息看看？ 需要一些信息做判断。

有的，不过我出现这个问题是win7，taro是1.2.26，现在已经升到了win10，taro升到了1.3.29，还是没解决。

  Taro CLI 1.3.29 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by Issacpeng** [comment]
用的是VSCODE吗？所有TARO API JSX相关的补全都不行了，还是整个项目的补全都OVER了？

**Comment by xiongcheng1107** [comment]
> 用的是VSCODE吗？所有TARO API JSX相关的补全都不行了，还是整个项目的补全都OVER了？

是用的vscode，taro api的提示和补全都不行了，至于整个项目的补全不太清楚是指哪方面？
不过很灵异的是我换自己电脑就好了，工作机在系统升级之前还试过重新npm i，vscode卸掉重装，都不好使。我估计很难复现，毕竟其他的项目代码看似很正常，出问题的这个每次刚打开编辑器也正常，然后很快就没了。

**Comment by Issacpeng** [comment]
看起来应该是vscode配置ES代码插件的时候出了BUG，可以尝试把插件卸载后重新安装试试。

**Comment by WuSiung** [comment]
我也有这个问题，复现了，node_modules的包安装就没提示了，全卸载有补全提示。
`"dependencies": {
    "@rematch/core": "^1.1.0",
    "@rematch/immer": "^1.1.0",
    "@rematch/loading": "^1.1.3",
    "@rematch/updated": "^0.1.5",
    "@tarojs/async-await": "^1.3.0",
    "@tarojs/components": "1.2.26",
    "@tarojs/redux": "1.2.26",
    "@tarojs/redux-h5": "1.2.26",
    "@tarojs/router": "1.2.26",
    "@tarojs/taro": "1.2.26",
    "@tarojs/taro-alipay": "1.2.26",
    "@tarojs/taro-h5": "1.2.26",
    "@tarojs/taro-swan": "1.2.26",
    "@tarojs/taro-tt": "1.2.26",
    "@tarojs/taro-weapp": "1.2.26",
    "classnames": "^2.2.6",
    "commitizen": "^3.1.1",
    "cz-conventional-changelog": "^2.1.0",
    "dayjs": "^1.8.14",
    "lodash": "^4.17.11",
    "md5": "^2.2.1",
    "nerv-devtools": "^1.3.9",
    "nervjs": "^1.3.9",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "taro-ui": "2.1",
    "wx-server-sdk": "^0.6.0"
  },
  "devDependencies": {
    "@tarojs/plugin-babel": "1.2.26",
    "@tarojs/plugin-csso": "1.2.26",
    "@tarojs/plugin-less": "1.2.26",
    "@tarojs/plugin-sass": "^1.2.26",
    "@tarojs/plugin-uglifyjs": "1.2.26",
    "@tarojs/webpack-runner": "1.2.26",
    "@types/react": "^16.4.8",
    "@types/webpack-env": "^1.13.6",
    "babel-eslint": "^8.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "eslint": "^4.19.1",
    "eslint-config-taro": "1.2.26",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-taro": "1.2.26"
  }`

**Comment by cuikangyi** [comment]
安装这个扩展试试
https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by Qiu800820** [comment]
1.3.34 同样也出现这个问题。IDE是Webstom  老项目是从旧版升级上来的代码提示正常， 用同样的package.json Install后出现这个问题， 
具体表现是
import Taro, {Component} from '@tarojs/taro';   
Taro 引用的types是_@tarojs_taro@1.3.34@@tarojs\taro\types\index.d.ts  无法提示Taro内方法
从老版本升级
Taro 引用的types是@tarojs\taro\types\index.d.ts  正常提示Taro内方法
