### ISSUE TITLE
希望支持支付宝IOT小程序,支付宝IOT小程序的API   组件全部都没支持   标红

### ISSUE THREAD

**Issue by jsLyLeeHi** [NervJS/taro#5123]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
先直接使用 `my.ix.` 吧，这块暂时没有人力支持，欢迎 PR。

https://nervjs.github.io/taro/docs/1.3.33/debug.html#api-%E8%B0%83%E7%94%A8%E6%8A%A5%E9%94%99

**Comment by Chen-jj** [comment]
> Stage: Landed at 3.1.0-beta.0
> Taro CLI 插件：[@tarojs/plugin-platform-alipay-iot](https://github.com/NervJS/taro-plugin-platform-alipay-iot)（v3.1+）
