### ISSUE TITLE
遍历数组时使用 renderXXX方法进行渲染时，参数传递存在问题

### ISSUE THREAD

**Issue by LyunKi** [NervJS/taro#5124]
### 问题描述

有一个订单列表，想渲染成一个个订单项，然后点击订单跳转至订单详情，发现传递的订单 id 参数与预期不符

### 复现步骤

1. 遍历订单列表
```jsx
                    <View>
                        {items.map((order, i) => (
                            <View key={order.orderId}>
                                {this.renderOrder(order, i)}
                            </View>
                        ))}
                    </View>
```
2. 渲染成订单项，并为其绑定跳转到详情页的参数
```jsx
<Button
                            plain
                            className='red-action'
                            onClick={(e) => {
                                e.stopPropagation();
                                CmRouter.navigate('ticket', {
                                    orderId: order.orderId,
                                });
                            }}
                        >
                            {formatMsg('orderList.ticket')}
                        </Button>
```
3. 在详情页获取参数并获取数据

### 期望行为

详情页获取的参数是预期的订单号

**Comment by LyunKi** [comment]
补充一下，不用 renderOrder，而是直接写在 render 里是可以的（疲惫

**Comment by Garfield550** [comment]
请在你项目的根目录下运行一下 `taro info` 然后发上来吧。

需要包含安装的包的信息。

**Comment by LyunKi** [comment]
Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.25 => 1.3.25 
      @tarojs/cli: 1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/mobx: 1.3.25 => 1.3.25 
      @tarojs/mobx-h5: 1.3.25 => 1.3.25 
      @tarojs/mobx-rn: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/rn-runner: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.5 
      nervjs: ^1.5.5 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25

**Comment by Garfield550** [comment]
1.3.25  到 1.3.27 这三个版本出了一些严重的问题，先升级到最新版的 1.3.30 试试看？

**Comment by LyunKi** [comment]
被折磨坏了，按照老铁你的说法跑去升级，结果默认直接升到了 2.0 beta。。。想想算了，尝个鲜，对着官网文档一顿改，各种跑不起来，后来发现是被去掉 JSON.stringify给误解了，还是要加上。。。跑起来一看-。 - 这个 issue 对应的问题还在

**Comment by LyunKi** [comment]
👽 Taro v2.0.0-beta.9


  Taro CLI 2.0.0-beta.9 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      react: ^16.8.6 => 16.12.0 
    npmGlobalPackages:
      typescript: 3.7.3

**Comment by Garfield550** [comment]
改一下 `package.json` 升级 1.3.30，全局安装的 CLI 使用 `npm install -g @tarojs/cli@1.3.30` 来更新。

`renderProps` 先试试只传一个参数？

**Comment by shenghanqin** [comment]
@LyunKi 要有点耐心哟。你想想，刚开始接触react、webpack等框架，都是很折腾的。
确实，最近是在beta阶段，也有版本bug，但是，耐心足够才可以滴。

**Comment by LyunKi** [comment]
> @LyunKi 要有点耐心哟。你想想，刚开始接触react、webpack等框架，都是很折腾的。
> 确实，最近是在beta阶段，也有版本bug，但是，耐心足够才可以滴。

其实能理解。。。但是我觉得策略有一点问题，
1. beta 版本应该不急着作为默认的选择，应该由一部分喜欢尝试的人主动去升级，而不是默认的给所有人升级的 beta 版；
2. 相反的，很多 taro 的依赖其实已经有些旧了，比如 ts ，rn之类的。 其实还挺希望在 项目 里用上一些有用的新特性的。不是很理解 taro 的实现，但是对于ts 这样的库，升级应该是相对平滑的呀。而现在 ts 的依赖能够在项目里看到，我看 rn 和 react 能自行升级，于是选择将 ts升到了 3.7,  结果写的时候不报错，但运行的时候会发现不支持。。。

**Comment by singlehcc** [comment]
遇到同样问题，不过我的版本是2.2.6
