### ISSUE TITLE
微信小程序自定义 tabBar 出现闪烁

### ISSUE THREAD

**Issue by PenToseLin** [NervJS/taro#5125]
### 问题描述

微信小程序自定义 tabBar 出现闪烁，在微信小程序原生上面测试过了，微信官方的没有闪烁，但是使用taro的时候就有闪烁

### 复现步骤
1. app.jsx添加
```js
tabBar: {
      // 自定义 tabBar
      custom: true,
      color: '#7A7E83',
      selectedColor: '#3cc51f',
      borderStyle: 'white',
      backgroundColor: "#ffffff",
      list: [
        {
          text: '首页',
          pagePath: 'pages/index/index'
        },
        {
          text: '日志',
          pagePath: 'pages/logs/logs'
        },
      ]
    }
```

2.  [https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html](url)
微信官方的custom-tab-bar复制到项目src目录下
修改custom-tab-bar/index.js
```js
list: [{
      pagePath: "/pages/index/index",
      iconPath: "./image/home.png",
      selectedIconPath: "./image/home-selected.png",
      text: "首页"
    }, {
      pagePath: "/pages/logs/logs",
      iconPath: "./image/logs.png",
      selectedIconPath: "./image/logs-selected.png",
      text: "日志"
    }
```
3. config/index.js 文件添加

```js
copy: {
    patterns: [
      { from: "src/custom-tab-bar/", to: "dist/custom-tab-bar/" }
    ],
    options: {}
  },
```
4. pages/index/index.jsx 和 /pages/logs/logs.jsx 添加
```js
componentDidShow () {
    if (typeof this.$scope.getTabBar === 'function' && this.$scope.getTabBar()) {
      this.$scope.getTabBar().setData({
        selected: 0 //此处修改索引
      })
    }
  }
```

5. 运行到真机测试就能看到 tabBar切换时有闪烁，可以写个微信官方原生的对比是没有闪烁的

### 期望行为

解决自定义 tabBar 切换闪烁

### 系统信息

Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by tourze** [comment]
同样遇到这个问题

**Comment by ColorfulCow** [comment]
同样的问题

**Comment by lzs2000131** [comment]
同样的问题

**Comment by Chen-jj** [comment]
@PenToseLin iOS 和 安卓都试过，没有复现。

**Comment by hardmanhong** [comment]
> @PenToseLin iOS 和 安卓都试过，没有复现。

事实上，我用3.3.3也会出现这种情况
我的情况是：自定义了tabbar，切换tabbar时，观察network，看到图片被重复加载，导致tabbar图片闪烁。在taro2上正常，我还是用2吧
