### ISSUE TITLE
钉钉小程序iOS真机上按键点击次数跟响应次数不一致

### ISSUE THREAD

**Issue by DevanXU** [NervJS/taro#5126]
### 问题描述

创建项目后自带的demo代码（增减数字），按键点击的次数跟响应次数不一致，不是每次点击都有响应。

### 复现步骤

1. taro init myApp创建项目, 选择Typescript & Redux
2. yarn dev:alipay
3. 打开阿里小程序IDE，打开myApp/dist，模式选择“钉钉企业第三方应用”
4. 编译完成后选择“真机预览”，生成二维码
5. 用iPhone手机扫描上述二维码
6. 快速点击应用上面的"+", "-" 按键，点击次数与响应次数不一致

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

预期每次按键的点击都要有响应，即”连续点击增加按键10次，数字应该增加10“。实际上可能只增加了5或6。

### 报错信息

没有任何报错

### 系统信息

👽 Taro v1.3.27

  Taro CLI 1.3.27 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.27 => 1.3.27 
      @tarojs/components: 1.3.27 => 1.3.27 
      @tarojs/plugin-babel: 1.3.27 => 1.3.27 
      @tarojs/plugin-csso: 1.3.27 => 1.3.27 
      @tarojs/plugin-sass: 1.3.27 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.27 => 1.3.27 
      @tarojs/redux: 1.3.27 => 1.3.27 
      @tarojs/redux-h5: 1.3.27 => 1.3.27 
      @tarojs/router: 1.3.27 => 1.3.27 
      @tarojs/taro: 1.3.27 => 1.3.27 
      @tarojs/taro-alipay: 1.3.27 => 1.3.27 
      @tarojs/taro-h5: 1.3.27 => 1.3.27 
      @tarojs/taro-swan: 1.3.27 => 1.3.27 
      @tarojs/taro-tt: 1.3.27 => 1.3.27 
      @tarojs/taro-weapp: 1.3.27 => 1.3.27 
      @tarojs/webpack-runner: 1.3.27 => 1.3.27 
      eslint-config-taro: 1.3.27 => 1.3.27 
      eslint-plugin-taro: 1.3.27 => 1.3.27 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.12.0 => 16.12.0 
      stylelint-config-taro-rn: 1.3.27 => 1.3.27 
      stylelint-taro-rn: 1.3.27 => 1.3.27 
    npmGlobalPackages:
      typescript: 3.7.2

### 补充信息

对比测试，这个问题只出现在钉钉iOS端，在 IDE/安卓手机/支付宝都没有问题，可能是taro的视图渲染跟 钉钉iOS端 兼容性问题。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@DevanXU 先更新到最新版本？
