### ISSUE TITLE
taro转换为微信小程序样式问题

### ISSUE THREAD

**Issue by 1591161042** [NervJS/taro#5127]
![WechatIMG8969](https://user-images.githubusercontent.com/11688428/71096736-cc7c0d80-21e9-11ea-9020-5c3612e0f51e.jpeg)
宽高同样设置的是431px，但是效果却变成长方形了

**Comment by 1591161042** [comment]
如何解决

**Comment by Garfield550** [comment]
你的 Issue 类型选错了，然后还请在项目根目录运行一下 `taro info` 命令，请包含安装的 Taro 相关依赖的信息，谢谢。

**Comment by 1591161042** [comment]
在模拟器是好的，真机就不行了

**Comment by shenghanqin** [comment]
@1591161042 请贴出源码或者示例demo
