### ISSUE TITLE
Taro转换为微信小程序

### ISSUE THREAD

**Issue by 1591161042** [NervJS/taro#5129]
![WechatIMG8969](https://user-images.githubusercontent.com/11688428/71136446-d7fa2380-223f-11ea-84a5-552908c50b13.jpeg)
同样的宽高，转换成微信小程序之后，宽高并不是相同的，请问如何解决，在模拟器上是好的，但是到了真机就不行了

**Comment by Garfield550** [comment]
Dup: #5127 

请在项目根目录运行一下 taro info 命令，请包含安装的 Taro 相关依赖的信息，谢谢。
