### ISSUE TITLE
正则表达式编译过后变成乱码了

### ISSUE THREAD

**Issue by a709691139** [NervJS/taro#513]
**问题描述**
```
export function transEmojiToNone(value) {
  return value.replace(/\uD83C[\uDF00-\uDFFF]|\uD83D[\uDC00-\uDE4F]/g, '');
}

```
![image](https://user-images.githubusercontent.com/21304258/44512722-0c161080-a6ee-11e8-9b39-682467fbdbe2.png)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 0.0.67
 - Node.js 版本 10.8.0

**Comment by yuche** [comment]
推荐使用 es6 的 [unicode 表示法](http://es6.ruanyifeng.com/#docs/string#%E5%AD%97%E7%AC%A6%E7%9A%84-Unicode-%E8%A1%A8%E7%A4%BA%E6%B3%95)

ref：
https://mathiasbynens.be/notes/es6-unicode-regex

另外你的版本有点老了，应该更新一下。

**Comment by a709691139** [comment]
已解决

源码
``` 
export function transEmojiToNone(value) {
  return value.replace(/[^\\u0000-\\uFFFF]/gu, '');
}
```
编译后
``` 
function transEmojiToNone(value) {
  return value.replace(/(?:[\uD800-\uDBFF][\uDC00-\uDFFF])/g, '');
}
```
