### ISSUE TITLE
[字节跳动]子组件中无法更新视图

### ISSUE THREAD

**Issue by JerryChan31** [NervJS/taro#5130]
### 问题描述

在一个组件中进行列表渲染，在组件的componentDidMount中调用MobX store中的请求函数，该请求函数更新store中的数据。在组件的render函数中使用store中的数据进行列表渲染。

观察log可以发现数据请求正常，并且触发了render，但渲染的结果并不正确。

此问题只在字节跳动小程序端出现，微信小程序端正常。

### 复现步骤

1. https://github.com/JerryChan31/taro-playground 可以用这个仓库的代码来复现，拉下代码，npm i 一下
2. 运行 npm run dev:tt，打开头条小程序，导入项目
3. 观察到Output处渲染为空白，右下角console.log是render函数中的输出，数据是正常的。

![image](https://user-images.githubusercontent.com/14790315/71147002-62ec1580-2262-11ea-8243-944ba0b7b535.png)

```js
// 组件渲染部分 test.tsx
render() {
  const { counterStore: { computedArr } } = this.props
  console.log('render', computedArr)
  return (
    <View>
      Output:
      {computedArr.map(item => {
        return (
          <View key={item.id}>
            <Text>item.exp: {item.exp}</Text>
          </View>
        )
      })}
    </View>
  )
}

// store 部分
class counterStore {
  @observable arr = new Map()
  @observable counter:number = 0
  requestArr = flow(function * () {
    return Taro.request({
      url: 'http://rest.apizza.net/mock/10a6d62e83e84f7aaf7cb3ea4cd08db5/test'
    }).then(res => {
      const posts = res.data || {}
      const row = new Map()
      Object.values(posts).map(data => {
        row.set(
          data.id,
          Object.assign({}, data)
        )
      })
      this.arr = row
    })
  })

  @computed get computedArr () {
    let temp:{id: string, exp: number}[] = []
    this.arr.forEach(item => {
      temp.push({
        id: item.id,
        exp: item.val
      })
    })
    return temp
  }

  counterStore() {
    this.counter++
  }
  increment() {
    this.counter++
  }
  decrement() {
    this.counter--
  }
  incrementAsync() {
    setTimeout(() => {
      this.counter++
    }, 1000)
  }
}
```

### 期望行为

和微信小程序行为保持一致。
![image](https://user-images.githubusercontent.com/14790315/71147296-587e4b80-2263-11ea-9ec1-52ce9e9dd534.png)

### 报错信息

无报错信息。

### 系统信息

👽 Taro v2.0.0-beta.9

  Taro CLI 2.0.0-beta.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/components-qa: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mini-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mobx: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mobx-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/router: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-alipay: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-qq: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-quickapp: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-swan: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-tt: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-weapp: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/webpack-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-config-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-plugin-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9 
      stylelint-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9 

### 补充信息

字节跳动开发者工具版本为1.8.5。
另外似乎代码热更新方面也有问题，有时改动代码后保存触发了重新编译，但开发者工具中运行的还是之前的代码，需要重新运行npm run dev:tt才恢复正常。有时字节跳动开发者工具中的文件目录和调试器中的bxml也不能正常显示（显示空白，偶现）
![image](https://user-images.githubusercontent.com/14790315/71147674-6f716d80-2264-11ea-825f-ded48230c66c.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
taro-tt和taro-weapp是两个适配层，也就是说，diff情况可能不一样。另外，除了Taro这边有问题以外，字节跳动小程序的diff算法可能也有问题。估计你得慢慢调试taro源代码啦。

**Comment by JerryChan31** [comment]
补充信息：
在render函数中加了debugger进行调试，中间偶尔有几次能正确地渲染出来…但我找不到原因。
![image](https://user-images.githubusercontent.com/14790315/71318343-9d57eb80-24ca-11ea-9af3-05ac03fb12c2.png)
看起来能正确地diff？

**Comment by JerryChan31** [comment]
另，如果将代码挪到页面组件中就可以正常渲染，但是子组件不行…

**Comment by JerryChan31** [comment]
![image](https://user-images.githubusercontent.com/14790315/71334437-334a4f80-2579-11ea-8d9b-4cb05638a240.png)

继续补充：
试了一下把生成项目时的demo移到子组件里，似乎不仅仅是列表渲染，只要是子组件的情况下就无法进行视图更新。右下角是`render`函数在`return`之前输出`counter`。

**Comment by Chen-jj** [comment]
@JerryChan31 升级到最新版本再试试吧，复现不了
