### ISSUE TITLE
原生微信小程序转为taro后 进入taro项目安装依赖,编译为其他端的小程序,报错

### ISSUE THREAD

**Issue by lxfljw** [NervJS/taro#5133]
./src/pages/address/list/index.js

Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: Unexpected token (1:56)
    at Parser.pp$3.parseMaybeConditional (D:\workspace\wxApp\m-mall-master-is\taroConvert\node_modules\babylon\lib\index.js:3381:19)from

**Comment by lxfljw** [comment]
重新编译回微信小程序都不可以

**Comment by lxfljw** [comment]
Taro CLI 2.0.0-beta.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\softInstall\node\node.EXE
      Yarn: D:\workspace\wxApp\m-mall-master-is\taroConvert>"node"  "C:\Users\QSKJ-00482\AppData\Roaming\npm\\node_modules\yarn\bin\yarn.js" -v
1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - D:\softInstall\node\npm.CMD

**Comment by lxfljw** [comment]
need AV 的 Taro的大佬们 关注一下这个问题啊 原生的小程序编译都发生错误 进去那一行代码 try catch 错误也看不懂 麻烦了@luckyadam

**Comment by flytrap** [comment]
我直接编译都这样

**Comment by Zane0816** [comment]
`Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: Unexpected token (1:58)
    at Parser.pp$3.parseMaybeConditional (/Users/zane/WebstormProjects/99BoxApplet/node_modules/babylon/lib/index.js:3381:19)from
`
直接用 taro 写的也会有这样问题
`Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - /usr/local/bin/node
      Yarn: 1.22.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.5 => 2.0.5 
      @tarojs/cli: 2.0.5 => 2.0.5 
      @tarojs/components: 2.0.5 => 2.0.5 
      @tarojs/components-qa: 2.0.5 => 2.0.5 
      @tarojs/mini-runner: 2.0.5 => 2.0.5 
      @tarojs/mobx: 2.0.5 => 2.0.5 
      @tarojs/mobx-h5: 2.0.5 => 2.0.5 
      @tarojs/router: 2.0.5 => 2.0.5 
      @tarojs/taro: 2.0.5 => 2.0.5 
      @tarojs/taro-alipay: 2.0.5 => 2.0.5 
      @tarojs/taro-h5: 2.0.5 => 2.0.5 
      @tarojs/taro-qq: 2.0.5 => 2.0.5 
      @tarojs/taro-quickapp: 2.0.5 => 2.0.5 
      @tarojs/taro-swan: 2.0.5 => 2.0.5 
      @tarojs/taro-tt: 2.0.5 => 2.0.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      @tarojs/webpack-runner: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      eslint-plugin-taro: 2.0.5 => 2.0.5 
      nervjs: ^1.5.6 => 1.5.6 
`

**Comment by baosisi07** [comment]
我也是直接编译报这个 有没有什么解决办法

**Comment by smilebuz** [comment]
+1同问 突然就不行了。。。

**Comment by 153493932** [comment]
同问 +1
