### ISSUE TITLE
taro2.0.0 bete 9  部分文件保存后 ， 小程序端文件没有及时更新或者不更新

### ISSUE THREAD

**Issue by Zigei** [NervJS/taro#5140]
### 问题描述

部分文件保存后 ， 小程序端文件没有及时更新或者不更新（反复保存该文件不能解决，重新启动编译能解决）
新建一个 tsx 文件后 完成编码 保存后 小程序端有可能只生成一个 json 文件 （已经被引用，反复保存该文件不能解决，重新启动编译能解决）
在文件保存之后 会提示编译成功  但是没有时间提示和文件提示  导致 终端全是 编译成功 不知道当前文件是否完全编译

### 期望行为

解决保存文件后  文件不更新的问题
编译成功后 加上时间 和 修改文件成功的提示

### 系统信息

👽 Taro v2.0.0-beta.9

  Taro CLI 2.0.0-beta.9 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.2.2

**Comment by ldd27** [comment]
+1同样遇到此问题

**Comment by lvimhere** [comment]
beta8 ，也有这个问题

**Comment by JoviCheng** [comment]
beta8 ，也有这个问题 + 1

**Comment by yclnycl** [comment]
bata10也有这个问题,先开始怀疑文件被占用手动删除编译出来的js一直没有新的js替换进去

**Comment by icewind7030** [comment]
+1，请问有解决时间吗？
