### ISSUE TITLE
快应用卡片开发需要在router内配置widgets，project.quickapp.json如何处理

### ISSUE THREAD

**Issue by stoneox** [NervJS/taro#5144]
### 问题描述
需要开发快应用卡片，需要在manifest的router内定义wdigets属性，project.quickapp.json不配置router，请问如何定义快应用卡片？

### 复现步骤

1. 开发快应用卡片需配置 wdigets 属性
2. project.quickapp.json无法配置router，无法配置wdigets

```js
   "widgets": {
      "CardDemo": {
        "name": "Card",
        "description": "快应用卡片",
        "component": "index",
        "path": "/Card",
        "features": []
      }
```

### 期望行为

 project.quickapp.json支持配置wdigets

### 系统信息

System:
      OS: Linux 4.4 Ubuntu 14.04.5 LTS, Trusty Tahr
      Shell: 4.3.11 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/components-qa: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/mini-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/router: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-alipay: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-h5: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-qq: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-quickapp: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-swan: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-tt: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/taro-weapp: 2.0.0-beta.9 => 2.0.0-beta.9 
      @tarojs/webpack-runner: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-config-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      eslint-plugin-taro: 2.0.0-beta.9 => 2.0.0-beta.9 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9 
      stylelint-taro-rn: 2.0.0-beta.9 => 2.0.0-beta.9

**Comment by Issacpeng** [comment]
@stoneox  可以参考一下快应用官方文档说明，目前快应用引擎是不支持的：https://developer.huawei.com/consumer/cn/doc/5060426 ，如何配置的话，这个文档有非常详细的讲解，看是否对你有帮助？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/quick-app.html#%E5%BF%AB%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE
![image](https://user-images.githubusercontent.com/1782542/71348012-8be41180-25a6-11ea-9e2a-2ef0b7a7709e.png)
