### ISSUE TITLE
报错：提示Taro.SelectorQuery.clientRectElement类型中无height属性

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#5145]
### 问题描述

提示：在rect对象中不存在width属性或者hight属性（Property 'width' does not exist on type 'clientRectElement | clientRectElement[]'）
  Property 'width' does not exist on type 'clientRectElement[]'.ts(2339)

### 复现步骤

1. 使用VScode
2. 使用query.select('XXX').boundingClientRect的API
3. 在回调中访问对象 obj.width
4. 发现eslint提示报错
5. 采用TypeScript编写，且Taro版本为1.3.27

### 相关代码

```js
const query = Taro.createSelectorQuery().in(this.$scope);
query.select('content-wrapper').boundingClientRect(rect => {
      rect.width;
}).exec();
```

### 期望行为

希望不要报错了

### 报错信息

<img width="538" alt="屏幕快照 2019-12-20 下午4 56 08" src="https://user-images.githubusercontent.com/23090498/71242791-aa010600-2349-11ea-9270-e2be420127f4.png">

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
手动升级至 1.3.30 再试一下，如果还是有问题请在下面回复，并且在你项目目录里运行 `taro info`，带上你的 Taro 依赖信息。

**Comment by Chen-jj** [comment]
@penghuwan 最新版本已经修复了。
