### ISSUE TITLE
多端入口文件引用问题

### ISSUE THREAD

**Issue by aoarashi1988** [NervJS/taro#5155]
### 问题描述
不同文件名的多端文件，在某些情况下无法自动区别引用

### 复现步骤
1、在scss文件中@import其他scss文件，并没有根据多端进行适配
例如，RN环境下，style文件夹下有两个文件index.scss和index.rn.scss
在其他scss文件中引用
```
@import ‘@/style/index.scss’;
```
#### 期望行为
引用index.rn.scss
#### 实际结果
引用index.scss

2、引用多端js入口文件，需要显式使用import关键字
例如，依然是RN环境，tabbar文件夹下有index.js和index.rn.js两个文件
```
import TabBar from './tabbar';
```
可以正确引用到index.rn.js
然而
```
export {default as TabBar} from './tabbar'
```
则引用的为index.js

**Comment by aoarashi1988** [comment]
也许与[#5131 ](https://github.com/NervJS/taro/issues/5131#issue-540095591)
是同一个问题

**Comment by luckyadam** [comment]
1、第一个问题，根据文档，目前只有 js 文件支持跨端文件的写法
2、第二个问题，是目前还没支持到 export from 的写法，需要改进下

**Comment by Chen-jj** [comment]
Taro 2、3 已支持 export from 语法
