### ISSUE TITLE
taro微信小程序现在支持发送模板消息吗？

### ISSUE THREAD

**Issue by Rxiaoyi** [NervJS/taro#5158]
taro微信小程序现在支持发送模板消息吗？想使用Taro小程序直接发送模板消息，请问现在支持吗？

**Comment by Garfield550** [comment]
可以先调用对应的 API 测试一下，如果不可以就直接使用 `wx` 开头的 API，然后在这个 Issue 里回复。

**Comment by Zigei** [comment]
老哥 微信的模板消息 1 月份就下线了 去看看 订阅功能吧
