### ISSUE TITLE
微信小程序 子组件使用父组件props的属性，map渲染会出现数据错乱

### ISSUE THREAD

**Issue by vscing** [NervJS/taro#5159]
### 问题描述

微信小程序 子组件使用父组件props的属性，map渲染会出现数据错乱

### 复现步骤

![image](https://user-images.githubusercontent.com/20698627/71331977-5d970f80-256f-11ea-861a-f9d4591d2b83.png)

1. 父组件传递list属性和onChangList方法
2. 初次list渲染正常， 点击子组件触发父组件onChangList方法，改变list数据
3. 子组件打印正常，map渲染开始出错

```js
render() {
    const { list, onChangList} = this.props;
    console.log(list)
    return (
            <View>
                {
                    list.map((item, index)=>
                        <View key={index} onClick={onChangList.bind(this, item.id)}>
                            {item}
                        </View>
                    )
                }
            </View>
    )
}


```

### 期望行为

map渲染正常

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by vscing** [comment]
放在父组件里面正常

**Comment by Chen-jj** [comment]
@vscing 什么版本

**Comment by vscing** [comment]
"@tarojs/taro": "1.3.12",

**Comment by vscing** [comment]
> @vscing什么版本

"@tarojs/taro": "1.3.12",

**Comment by JerryChan31** [comment]
`key={index}` 改成其他的试试？

**Comment by vscing** [comment]
> `key={index}` 改成其他的试试？
试过，不行

**Comment by Chen-jj** [comment]
@JerryChan31 请提供完整可复现代码
