### ISSUE TITLE
引用 vant-weapp

### ISSUE THREAD

**Issue by ruixiu** [NervJS/taro#516]
引入了vant-weapp的组件库，由于组件库使用的单位都是小写px，所以经taro编译后变成了rpx，导致界面元素非常小。。有没有在不修改组件库的情况下解决该问题。。另：不清楚vant-weapp的设计稿尺寸

**Comment by luckyadam** [comment]
@ruixiu https://nervjs.github.io/taro/size.html#%E9%85%8D%E7%BD%AE 可以按这里来关掉转换

**Comment by ruixiu** [comment]
搞定了，加上
weapp: {
    module: {
      postcss: {
        pxtransform: {
          selectorBlackList: [
            /^.van-.*?$/
          ]
        }
      }
    }
  }

**Comment by luckyadam** [comment]
非常棒👍
