### ISSUE TITLE
Taro v2.0.0-beta.10 样式使用@import 无法找到的问题

### ISSUE THREAD

**Issue by zhangfu-git** [NervJS/taro#5160]
### 期望行为
希望@import一个公共文件可以使用相对路径

### 报错信息

![image](https://user-images.githubusercontent.com/19772048/71333366-ae5d3700-2574-11ea-9bcb-687faf23dc6d.png)

### 系统信息
Taro v2.0.0-beta.10

**Comment by luckyadam** [comment]
检查一下是否路径写错了

**Comment by zhangfu-git** [comment]
@luckyadam   路径是没有问题的，没有升级之前都能正常使用，升级后只能用相对路径！

**Comment by mayocream** [comment]
v2.0.0-beta.10 同样有这个问题

**Comment by OoSAYAoO** [comment]
同样有问题 +1

**Comment by luckyadam** [comment]
暂时用相对路径吧
