### ISSUE TITLE
Taro v2.0.0-beta.10 编译提示SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by zhangfu-git** [NervJS/taro#5161]
### 问题描述
升级Taro v2.0.0-beta.10， 修改了babel的配置，也添加了新的依赖，在编译的时候提示，如下图报错

### 期望行为
语法错误到底是哪里不规范导致错误，需要具体的错误信息

### 报错信息
![image](https://user-images.githubusercontent.com/19772048/71333580-71de0b00-2575-11ea-959b-1310c22455b4.png)

**Comment by luckyadam** [comment]
麻烦提供个 demo 看下
