### ISSUE TITLE
swiper组件滑动后第一张图片无法再次点击

### ISSUE THREAD

**Issue by streamBamboo** [NervJS/taro#5162]
### 问题描述
swiper组件滑动后第一张图片无法再次点击 【H5端】

### 复现步骤
![image](https://user-images.githubusercontent.com/29224540/71344145-bb8e1c00-259c-11ea-8b9d-d3b850dde542.png)
![image](https://user-images.githubusercontent.com/29224540/71344153-bf21a300-259c-11ea-850d-7fcbe0a6ab92.png)

代码

1. 
![image](https://user-images.githubusercontent.com/29224540/71344093-97cad600-259c-11ea-8102-c0a58d3289a0.png)
刷新页面第一次没问题
2. 
![image](https://user-images.githubusercontent.com/29224540/71344200-dcef0800-259c-11ea-8540-e285c5f5be82.png)
第二张图片多次切换的效果，没问题，也能点击
3. 
![image](https://user-images.githubusercontent.com/29224540/71344235-f55f2280-259c-11ea-94c0-42411ab86844.png)
![image](https://user-images.githubusercontent.com/29224540/71344241-fabc6d00-259c-11ea-8976-a6dfa5f20870.png)
这里切换之后多次点击都无效果
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息

![image](https://user-images.githubusercontent.com/29224540/71344341-3820fa80-259d-11ea-990a-182056593e46.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
same as #5279
