### ISSUE TITLE
结合redux使用时，useEffect中使用setNavigationBarTitle，当在下层级页面修改数据，会在下层级页面中修改标题，而不是期望的回到当前页面再改变

### ISSUE THREAD

**Issue by xiaoyuze88** [NervJS/taro#5167]
### 问题描述

1. A页面中，useEffect监听一个redux中的值来动态设置标题
2. 进入下一级B页面，在B中改变redux中的值
3. 触发了A页面的useEffect，并将B页面的标题设置为了redux中的值
4. 返回A页面，标题无变化（因为值改变的监听器已经被B页面消费）

### 复现步骤

如上

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

A中的useEffect仅在A页面激活时触发，而不是在B页面中调用A页面的useEffect

### 报错信息

无

### 系统信息

👽 Taro v1.3.28

  Taro CLI 1.3.28 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.5.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.28 => 1.3.28 
      @tarojs/components: ^1.3.28 => 1.3.28 
      @tarojs/plugin-babel: ^1.3.28 => 1.3.28 
      @tarojs/plugin-csso: ^1.3.28 => 1.3.28 
      @tarojs/plugin-less: ^1.3.28 => 1.3.28 
      @tarojs/plugin-uglifyjs: ^1.3.28 => 1.3.28 
      @tarojs/redux: ^1.3.28 => 1.3.28 
      @tarojs/router: ^1.3.28 => 1.3.28 
      @tarojs/taro: ^1.3.28 => 1.3.28 
      @tarojs/taro-weapp: ^1.3.28 => 1.3.28 
      @tarojs/webpack-runner: ^1.3.28 => 1.3.28 
      eslint-config-taro: ^1.3.28 => 1.3.28 
      eslint-plugin-taro: ^1.3.28 => 1.3.28 
      nerv-devtools: ^1.5.0 => 1.5.1 
      nervjs: ^1.5.0 => 1.5.1 
      stylelint-config-taro-rn: ^1.3.28 => 1.3.28 
    npmGlobalPackages:
      typescript: 1.8.10

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by xiaoyuze88** [comment]
目前要实现期望特性只能自己用hooks来处理了。

```javascript
export function useSetPageTitle(title) {
  const lastTitleRef = useRef('');
  const pageOnShowRef = useRef(false);

  const doSetTitle = (title) => {
    if (lastTitleRef.current !== title) {
      lastTitleRef.current = title;
      Taro.setNavigationBarTitle({ title });
    }
  };

  useDidShow(() => {
    pageOnShowRef.current = true;

    doSetTitle(title);
  });

  useDidHide(() => {
    pageOnShowRef.current = false;
  });

  useEffect(() => {
    if (pageOnShowRef.current) {
      doSetTitle(title);
    }
  }, [title]);
}
```

**Comment by dpyzo0o** [comment]
我也碰到过这个问题，我的理解是，因为进入下一页并不会销毁之前的页面，所以之前的页面由于订阅的redux值变了导致重新渲染，执行了相应的代码。我觉得，是不是你在之前那个页面的 useDidshow 里面再设置一遍title就行了

**Comment by dpyzo0o** [comment]
然后你这样的写法，如果页面中还需要用到 useDidShow useDidHide 怎么办？ 我不知道是不是可以同时有多个 useDidShow 存在同一个页面组件中

**Comment by Chen-jj** [comment]
@xiaoyuze88 

@dpyzo0o 正解。小程序不像 H5，并没有销毁上一个页面，useEffect 执行是正确的。useDidShow 里处理吧。

**Comment by Chen-jj** [comment]
@dpyzo0o 可以重复。会叠加调用。

https://github.com/NervJS/taro/blob/205d62d0d9babce9fe73afa99f7da46701961d37/packages/taro/src/hooks.js#L40-L63
