### ISSUE TITLE
(急急急)百度小程序始终获取不到手机号

### ISSUE THREAD

**Issue by zhengzhuang95** [NervJS/taro#5174]
### 问题描述
百度小程序获取手机号获取不到

### 复现步骤
<Button open-type='getPhoneNumber' onGetUserInfo={this.getphonenumberFun} className='loginBtn lg_blue' >百度账号一键登录</Button>

	getphonenumberFun = (e) => {
		console.log(e)
	}
![image](https://user-images.githubusercontent.com/29434858/71397891-bf33a880-2659-11ea-9e1f-fa01b53fbb78.png)
![image](https://user-images.githubusercontent.com/29434858/71397899-c6f34d00-2659-11ea-87af-9154f2cbece8.png)
![image](https://user-images.githubusercontent.com/29434858/71398088-50a31a80-265a-11ea-91f7-c34f6d384218.png)

始终获取不到

```

### 期望行为

<!-- 请在下一行用简洁清晰的语言描述你期望的行为 -->

### 报错信息

<!-- 请在下一行贴上你的完整报错截图或文字 -->

### 系统信息

<!-- 使用`taro info`命令即可查看系统及依赖信息。将该命令运行结果贴下面即可。 -->

### 补充信息

<!-- （可选）根据你的调查研究，出现这个问题的原因可能在哪里？ -->

<!-- 感谢您的热心反馈！别忘了用preview按钮预览结果再提交 -->

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
事件绑定写错了

**Comment by Inori-Lover** [comment]
![image](https://user-images.githubusercontent.com/9866055/71428808-1e4af900-26fe-11ea-86d7-8f2a1f7146ea.png)

**Comment by zhengzhuang95** [comment]
![image](https://user-images.githubusercontent.com/29434858/71428878-99acaa80-26fe-11ea-8570-f738f6c63498.png)
这样也不可以啊

**Comment by Garfield550** [comment]
建议先看一遍文档 [组件的事件传递都要以 on 开头](https://taro-docs.jd.com/taro/docs/components-desc.html#%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E9%83%BD%E8%A6%81%E4%BB%A5-on-%E5%BC%80%E5%A4%B4)

**Comment by zhengzhuang95** [comment]
![image](https://user-images.githubusercontent.com/29434858/71429012-569f0700-26ff-11ea-9c5f-f47b6d2c7b9b.png)
组件的事件传递都要以 on 开头, 变成这样吗，好像也不行，点击获取授权，没有回调

**Comment by Inori-Lover** [comment]
`<Button openType='getPhoneNumber' onGetPhoneNumber={this.phoneNumberHandle}>(急急急)请按照issue文档新建issue</Button>`

**Comment by shenghanqin** [comment]
@zhengzhuang95 我认为这个问题已经得到了比较详尽的解答，我先关掉了。如果还有问题，可以追问。
