### ISSUE TITLE
微信小程序 taro Hooks useRef 方法获取ref无效

### ISSUE THREAD

**Issue by HaoYS** [NervJS/taro#5176]
### 问题描述

https://nervjs.github.io/taro/docs/hooks.html#useref

taro官方文档中关于hooks useref 方法获取ref的示例在小程序中无法获取

### 复现步骤

文档中的示例代码

```js
function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` 指向已挂载到 DOM 上的文本输入元素
    inputEl.current.focus();
  };
  return (
    <View>
      <Input ref={inputEl} type="text" />
      <Button onClick={onButtonClick}>Focus the input</Button>
    </View>
  );
}
```

### 期望行为

期望 ` inputEl.current` 指向组件

### 报错信息

 inputEl.current 是undefined

### 系统信息

👽 Taro v1.3.17

  Taro CLI 1.3.17 environment info:
    System:
      OS: macOS High Sierra 10.13.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm

### 补充信息

* 1.3.17 1.3.29 都试验了不行

**Comment by HaoYS** [comment]
> ### 问题描述
> https://nervjs.github.io/taro/docs/hooks.html#useref
> 
> taro官方文档中关于hooks useref 方法获取ref的示例在小程序中无法获取
> 
> ### 复现步骤
> 文档中的示例代码
> 
> ```js
> function TextInputWithFocusButton() {
>   const inputEl = useRef(null);
>   const onButtonClick = () => {
>     // `current` 指向已挂载到 DOM 上的文本输入元素
>     inputEl.current.focus();
>   };
>   return (
>     <View>
>       <Input ref={inputEl} type="text" />
>       <Button onClick={onButtonClick}>Focus the input</Button>
>     </View>
>   );
> }
> ```
> 
> ### 期望行为
> 期望 ` inputEl.current` 指向组件
> 
> ### 报错信息
> inputEl.current 是undefined
> 
> ### 系统信息
> 👽 Taro v1.3.17
> 
> Taro CLI 1.3.17 environment info:
> System:
> OS: macOS High Sierra 10.13.1
> Shell: 5.3 - /bin/zsh
> Binaries:
> Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
> Yarn: 1.12.3 - /usr/local/bin/yarn
> npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
> 
> ### 补充信息
> * 1.3.17 1.3.29 都试验了不行

**Comment by hufans** [comment]
问题并未解决，为何关闭

**Comment by azumia** [comment]
发现同样问题....

**Comment by zzzmj** [comment]
我也遇到了这个问题

**Comment by VoganWong** [comment]
> 我也遇到了这个问题

推荐使用回调方式。
https://zh-hans.reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node
