### ISSUE TITLE
引入@tarojs/taro-h5/src/api/utils失败

### ISSUE THREAD

**Issue by edwards19900128** [NervJS/taro#5178]
### 问题描述
查询参数序列化时候 看到taro-h5中有个轮子可以使用。
但是引入失败了，想确认下引入方法该如何写

```js
// 引入
import { serializeParams } from '@tarojs/taro-h5/src/api/utils'

```

### 报错信息
![image](https://user-images.githubusercontent.com/11594850/71405435-63c0e500-2670-11ea-8c03-5a524400f546.png)
VM526 WAService.js:1 Uncaught Error: module "npm/@tarojs/taro-h5/src/api/utils/index.js" is not defined
    at require (VM526 WAService.js:1)
    at VM526 WAService.js:1
    at user.js:16
    at require (VM526 WAService.js:1)
    at VM526 WAService.js:1
    at user-auto-login.js:19
    at require (VM526 WAService.js:1)
    at <anonymous>:209:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1577178261555:4831)
    at HTMLScriptElement.script.onload (appservice?t=1577178261555:4843)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
copy到项目里面吧
