### ISSUE TITLE
taro升级后，taro项目引用小程序项目的utils方法报错了

### ISSUE THREAD

**Issue by zhangkaidi** [NervJS/taro#5179]
目录结构
 --小程序项目
 --Taro dist
 --Taro项目

目前项目打包过程：Taro项目引用了小程序中的Utils路径方法，通过gulp把dist目录，复制到小程序项目中
![image](https://user-images.githubusercontent.com/12831874/71405960-ce265500-2671-11ea-81e1-583266d15a47.png)
之前的工具是不检验，文件引用的正确性，现在打包就会上图报错

**Comment by HaoYS** [comment]
个人电脑环境问题 打扰了~

**Comment by shenghanqin** [comment]
还是不够具体，请提供完整的demo或者代码示例
