### ISSUE TITLE
使用HOC不支持包裹函数组件, 会被编译为React.createElement

### ISSUE THREAD

**Issue by ChangerHe** [NervJS/taro#5182]
### 问题描述

使用HOC不支持包裹函数组件, 会被编译为React.createElement

### 复现步骤

```js
import Taro from '@tarojs/taro';
import useTokenProcessor from '../hooks/useTokenProcessor';

const withUseTokenProcessor = (OutComponent) => {
  return props => {
    const [isLoading, isNeedAuth] = useTokenProcessor();
    return (
      <OutComponent isLoading={isLoading} isNeedAuth={isNeedAuth} {...props} />
    );
  };
};

export default withUseTokenProcessor;
```

将此HOC引入页面使用后, 出现报错, 提示Uncaught ReferenceError: React is not defined

可以看到, 这个HOC被编译成为了一个使用`React.createElement`生成的组件

![Uploading image.png…](https://img.4009515151.com/WX20191224-194135.png)

**Comment by ChangerHe** [comment]
主要的想法是想将hooks的逻辑复用到原有的class组件中, 所以使用hoc

**Comment by luckyadam** [comment]
小程序端暂时不支持 HOC

**Comment by afishhhhh** [comment]
@luckyadam 有计划支持 hoc 吗
