### ISSUE TITLE
typescript 的 Optional chaining(?.) 运算符支持

### ISSUE THREAD

**Issue by yeeing** [NervJS/taro#5183]
### 问题描述

是否应该支持typescript的`?.`运算符
### 复现步骤

```js
const [state,setState]=Taro.useState([])
<View>{state?.map(value=>{})}</View>
```

### 报错信息

Unexpected token
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by TheCodeMachineOfXiaoluo** [comment]
希望多支持一些新的JS语法

**Comment by js-newbee** [comment]
@yeeing 标题写反了，是 `?.` 操作符...

现在 taro 用的是 babel6，还不支持 optional chaining，但新版的 typescript 已经提供支持了，然而编译 ts 代码并不是用的 ts-loader，所以升级 typescript 版本也没用... 这块有计划支持么，`?.` 特性还行相当有用的，也已经到了 Stage 4 了

**Comment by Garfield550** [comment]
@js-newbee Taro 2 小程序也是用 Webpack 编译了，所以理论上可以添加 babel 插件搞定，当然更希望 TS 的代码是用 ts-loader 编译。

cc @luckyadam

**Comment by Garfield550** [comment]
问了一下老李，Taro 2 也还是基于 Babel 6 的，不过 Taro 3 是基于 Bable 7，Taro 3 就可以支持了。
Taro 3 会在 Taro 2 正式版发布不久之后发布测试版。

**Comment by luckyadam** [comment]
先 close 咯

**Comment by melote** [comment]
这个特性巨大提升生产力啊，建议优先考虑

**Comment by lake2** [comment]
same issue +1

**Comment by travis-joe** [comment]
why close it? not fragrant?

**Comment by GongLLei** [comment]
taro2 也是可以支持的，目前wx-transformer中ts.transpile的target配置为ESNEXT，配置为<=ES2019即可开启

**Comment by Sevenonclick** [comment]
> taro2 也是可以支持的，目前wx-transformer中ts.transpile的target配置为ESNEXT，配置为<=ES2019即可开启

这个wx-transformer具体在什么地方配置呢

**Comment by Elliott-Hu** [comment]
> > taro2 也是可以支持的，目前wx-transformer中ts.transpile的target配置为ESNEXT，配置为<=ES2019即可开启
> 
> 这个wx-transformer具体在什么地方配置呢

看了一下，没有开放配置，要深入到源码改
/node_modules/@tarojs/transformer-wx/lib/src/index.js
166行左右
