### ISSUE TITLE
Taro2.0.0-beta.10 this.$preloadData为null

### ISSUE THREAD

**Issue by MrXia1993** [NervJS/taro#5185]
在预加载页面的componentWillPreload正常返回Promise
但是在componentWillMount中获取this.$preloadData为null
在前一个页面调用的是Taro.switchTab()方法

复现版本为2.0.0-beta.10

**Comment by Chen-jj** [comment]
@MrXia1993 很遗憾，小程序 switchTab 不能带参数，所以 componentWillPreload 在 switchTab 时是不能触发的。

![image](https://user-images.githubusercontent.com/11807297/71801298-83570500-3095-11ea-8941-688686e8b0d4.png)
