### ISSUE TITLE
打包H5到线上显示Error: Loading chunk 6 failed

### ISSUE THREAD

**Issue by wlancer1** [NervJS/taro#5190]
### 问题描述

打包H5到线上显示Error: Loading chunk 6 failed 页面白屏

### 复现步骤

1.在移动端打开跳转页面白屏 用vconsole 显示error

![6181577339949_ pic](https://user-images.githubusercontent.com/15881260/71461036-5713cc80-27e9-11ea-88be-e4b2c1580b7f.jpg)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by wlancer1** [comment]
链接地址可以访问到

**Comment by Littly** [comment]
清除页面缓存再试试吧
