### ISSUE TITLE
showToast方法 then 回调里跳转路由

### ISSUE THREAD

**Issue by YikuanLu** [NervJS/taro#5191]
### 问题描述
showToast方法 then 回调里跳转路由，不会等展示提示时间结束后再跳转，而是直接跳转，导致提示直接没掉

### 复现步骤

![image](https://user-images.githubusercontent.com/49614876/71462637-e374be00-27ee-11ea-82fe-72f4e578f759.png)

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
这个api就是这样设计的。showToast传入属性中的success也是这个行为。
