### ISSUE TITLE
引入css不生效？

### ISSUE THREAD

**Issue by Miluaaa** [NervJS/taro#5192]
![WX20191226-151523](https://user-images.githubusercontent.com/49137179/71463824-a14d7b80-27f2-11ea-8347-34003c95db09.png)
![WX20191226-151532](https://user-images.githubusercontent.com/49137179/71463827-a3afd580-27f2-11ea-8ebf-6e9a759d4fbd.png)
![WX20191226-151554](https://user-images.githubusercontent.com/49137179/71463830-a6aac600-27f2-11ea-88b5-a85ee2ae0340.png)

**Comment by Inori-Lover** [comment]
不给个项目么……我本地的ts项目没这个现象欸

**Comment by luckyadam** [comment]
复现不了

**Comment by Miluaaa** [comment]
> 不给个项目么……我本地的ts项目没这个现象欸

你需要什么东西，我今天刚接触这个框架，刚安装的脚手架，创建的项目用sass或css都不行

**Comment by Inori-Lover** [comment]
这种问题为什么来issue？？不是有开源的example？不是有q群？

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by luckyadam** [comment]
> > 不给个项目么……我本地的ts项目没这个现象欸
> 
> 你需要什么东西，我今天刚接触这个框架，刚安装的脚手架，创建的项目用sass或css都不行

提供一个可以复现这个问题的 demo
