### ISSUE TITLE
bate11 编译各端无法生成对应css文件

### ISSUE THREAD

**Issue by yclnycl** [NervJS/taro#5193]
### 问题描述

运行build命令各端无法生成对应的css文件

### 复现步骤

安装bate11然后进行编译

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
有完整的demo示例吗？

**Comment by yaoyonstudio** [comment]
遇到同样的问题

在index.jsx中导入样式文件

```
import './index.scss';
```

在微信小程序调试时，没有生成指定的样式文件，在H5下正常。

**Comment by luckyadam** [comment]
> 遇到同样的问题
> 
> 在index.jsx中导入样式文件
> 
> ```
> import './index.scss';
> ```
> 
> 在微信小程序调试时，没有生成指定的样式文件，在H5下正常。

升级到 2.0.0-beta.12 试试

**Comment by yaoyonstudio** [comment]
2.0.0-beta.12 正常了
