### ISSUE TITLE
rn 端 onLongPress 事件不生效

### ISSUE THREAD

**Issue by ibubbo** [NervJS/taro#5194]
### 问题描述

如题，代码如下：

![image](https://user-images.githubusercontent.com/32586819/71470007-d57e6780-2805-11ea-8d35-3c007a0fcaa9.png)

### 期望行为

弹出 “长按” 两字

### 报错信息

无任何反应

### 系统信息

Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/73765124-0eb7d900-47af-11ea-83d5-d29a986d51b0.png)

使用 iOS 真机测试，正常。
