### ISSUE TITLE
auto-docs导致Taro下cloud namespace 导出失效

### ISSUE THREAD

**Issue by Inori-Lover** [NervJS/taro#5195]
### 问题描述
升级1.3.33后Taro的cloud导出失效（这个错误理应1.3.32也能看到）

### 复现步骤
升级taro依赖为1.3.33后vs code下使用ts书写`Taro.cloud`即可看到报错
![image](https://user-images.githubusercontent.com/9866055/71472558-7bce6b00-280e-11ea-8e91-3ff0028f9be6.png)

### 期望行为
cloud正确地在Taro下导出

### 报错信息

Property 'cloud' does not exist on type 'typeof Taro'.ts(2339)

### 补充信息
简单追查了一下应该是在[这个commit](https://github.com/NervJS/taro/commit/67a945a25d55365f2ce1ed9fdbc57f4539749b55#diff-b33f5b895ab6706dd2d12519765e78cb)引入的错误，将init等函数分到interface而不是namespace里，手动修改相关定义为namespace之后也确实消除了错误

![image](https://user-images.githubusercontent.com/9866055/71472721-0e6f0a00-280f-11ea-96ed-18e55365e4b6.png)

**Comment by dpyzo0o** [comment]
这个issue预计什么时候修复？

**Comment by Garfield550** [comment]
已经修复但是没有发布版本，等待下一个版本吧
