### ISSUE TITLE
'@tarojs/taro' does not contain an export named 'PureComponent'

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#5196]
### 复现步骤

config/index.js
```js
alias: {
   '@/components': path.join(__dirname, '../src/components'),
}
```
src/components/icon-item/index.jsx
```js
import Taro, { PureComponent } from '@tarojs/taro';
export default class IconItem extends PureComponent {...}
```
src/components/index.js
```js
export { default as IconItem } from './icon-item';
```
pages/index/index.jsx
```js
import { IconItem } from '@/components'; // 这样写会报错
import { IconItem } from '../../components'; // 这样写正常
```

### 期望行为

正常运行

### 报错信息
编译时报错
'@tarojs/taro' does not contain an export named 'PureComponent'
控制台报错
Super expression must either be null or a function, not undefined
### 系统信息

  Taro CLI 1.3.33 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvs/default/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvs/default/bin/npm
    npmPackages:
      eslint-config-taro: 1.3.33 => 1.3.33 
      eslint-plugin-taro: 1.3.33 => 1.3.33 
      stylelint-config-taro-rn: 1.3.33 => 1.3.33 
      stylelint-taro-rn: 1.3.33 => 1.3.33

**Comment by Littly** [comment]
怀疑你项目中安装了cli 并且是用npm scripts启动的 导致你用的cli是旧版本

**Comment by yulrosy** [comment]
我用yarn list看过了，项目里没有安装cli @Littly

**Comment by yulrosy** [comment]
> 应该是你项目中安装了cli 并且是用npm scripts启动的 导致你用的cli是旧版本

我直接同全局的taro跑也没用
