### ISSUE TITLE
大佬，taro 项目打包rn 与原生通信

### ISSUE THREAD

**Issue by Leavds** [NervJS/taro#5203]
### 复现步骤

如题，我目前的做法是把taro打包生成rn_temp文件夹然后拷到壳子项目根目录用ReactContextBaseJavaModule进行通信，还有其他的方式吗？比如可以直接在taro的包里面直接做可以吗？

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Pines-Cheng** [comment]
可以采用和 原生 RN 一样的做法：[和原生端通信](https://reactnative.cn/docs/0.55/communication-ios/#%E4%BB%8E-react-native-%E4%BC%A0%E9%80%92%E5%B1%9E%E6%80%A7%E5%88%B0%E5%8E%9F%E7%94%9F%E7%BB%84%E4%BB%B6)，必要时写跨端代码。

**Comment by Leavds** [comment]
现在用的就是这种，每次 项目打包 都会覆盖原有的js ，需要恢复修改的代码？我的意思是可不可以直接将依赖导入taro项目的package.json文件中，然后在src目录下的js文件中加判断调用Android的东西 这样可以么？

**Comment by Pines-Cheng** [comment]
@Leavds  不太懂你的需求～

**Comment by Leavds** [comment]
额 是这个意思，Android，rn通信用的是ReactContextBaseJavaModule这个东西，本身我之前的做法是每次taro项目打包生成rn代码，在这些rn代码里添加与Android的交互，这样的问题就是每次生成的rn代码都需要添加交互代码，现在我的做法是直接在taro代码里添加会话类型判断，加上与Android交互的代码，这样目前操作是可以的。
