### ISSUE TITLE
支付宝- 真机分包页面内 组件render不执行

### ISSUE THREAD

**Issue by sanye33** [NervJS/taro#5204]
### 问题描述
支付宝分包页面孙子组件在真机中render不执行

页面结构：
 页面   index
        子组件  ChooseStore
                孙子组件    storeList

**微信小程序开发工具和真机中都表现正常，支付宝开发工具正常，真机异常；以下为各个端组件render中的console**

**微信：**

![image](https://user-images.githubusercontent.com/22977141/71504656-43359c80-28b5-11ea-8159-fb0ce7320008.png)

**支付宝开发工具：**

![image](https://user-images.githubusercontent.com/22977141/71505160-36b24380-28b7-11ea-845c-e98fdada9f59.png)

**支付宝真机（安卓）**

![image](https://user-images.githubusercontent.com/22977141/71505185-4a5daa00-28b7-11ea-9fb9-4881a9d629ad.png)

### 复现步骤

无

### 期望行为

render正常执行 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@sanye33 还是给个 demo 吧，猜不到触发情况

**Comment by sanye33** [comment]
[my-app.zip](https://github.com/NervJS/taro/files/4010139/my-app.zip)
