### ISSUE TITLE
使用alias后报错，Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#5212]
### 问题描述
问题必现，cli和依赖版本一致。

### 复现步骤
1. yarn global add @tarojs/cli@1.3.33
2. taro init test

config/index.js
```js
alias: {
   '@/components': path.join(__dirname, '../src/components'),
}
```
src/components/icon-item/index.jsx
```js
import Taro, { PureComponent } from '@tarojs/taro';
export default class IconItem extends PureComponent {...}
```
src/components/index.js
```js
export { default as IconItem } from './icon-item';
```
pages/index/index.jsx
```js
import { IconItem } from '@/components'; // 这样写会报错
import { IconItem } from '../../components'; // 这样写正常
```

### 期望行为

正常运行

### 报错信息
编译时报错
'@tarojs/taro' does not contain an export named 'PureComponent'
控制台报错
Super expression must either be null or a function, not undefined
### 系统信息

  Taro CLI 1.3.33 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvs/default/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvs/default/bin/npm
    npmPackages:
            @tarojs/cli: 1.3.33 => 1.3.33 
      @tarojs/components: 1.3.33 => 1.3.33 
      @tarojs/plugin-babel: 1.3.33 => 1.3.33 
      @tarojs/plugin-csso: 1.3.33 => 1.3.33 
      @tarojs/plugin-uglifyjs: 1.3.33 => 1.3.33 
      @tarojs/router: 1.3.33 => 1.3.33 
      @tarojs/taro: 1.3.33 => 1.3.33 
      @tarojs/taro-h5: 1.3.33 => 1.3.33 
      @tarojs/taro-weapp: 1.3.33 => 1.3.33 
      @tarojs/webpack-runner: 1.3.33 => 1.3.33 
      eslint-config-taro: 1.3.33 => 1.3.33 
      eslint-plugin-taro: 1.3.33 => 1.3.33 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.33 => 1.3.33 
      stylelint-taro-rn: 1.3.33 => 1.3.33  

### 补充信息
用的是全局的cli，cli版本和依赖版本是一致的
IconItem.js
import { IconItem } from '../../components'
编译后是这样的
/* harmony import */ var nervjs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! nervjs */ "./node_modules/nervjs/dist/index.esm.js");
/* harmony import */ var _tarojs_taro_h5__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @tarojs/taro-h5 */ "./node_modules/@tarojs/taro-h5/src/index.js");
/* harmony import */ var _tarojs_components__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! @tarojs/components */ "./node_modules/@tarojs/components/src/index.js");

使用 import { IconItem } from '@/components'
编译后是这样的
/* harmony import */ var _tarojs_taro__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @tarojs/taro */ "./node_modules/@tarojs/taro/dist/index.esm.js");
/* harmony import */ var _tarojs_components__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @tarojs/components */ "./node_modules/@tarojs/components/src/index.js");

**可以发现少了nervjs和@tarojs/taro-h5**

**Comment by BinZhiZhu** [comment]
alias: {
   '@/components': path.resolve(__dirname, '..', 'src/components'),
}

**Comment by Littly** [comment]
看看.temp文件夹里面对应的文件

**Comment by yulrosy** [comment]
> 看看.temp文件夹里面对应的文件

.temp/components/index.js
import Nerv from "nervjs";
import Taro from "@tarojs/taro-h5";

但是编译结果里没有nervjs和@tarojs/taro-h5

**Comment by Littly** [comment]
那你搞个demo吧 从描述看不出来

**Comment by yulrosy** [comment]
复现步骤写的很清楚了

**Comment by yulrosy** [comment]
找到原因了，把h5下的alias移到根配置就好了
