### ISSUE TITLE
taro.request 并发限制没生效

### ISSUE THREAD

**Issue by xn330125** [NervJS/taro#5213]
### 问题描述

taro.request 并发限制没生效，执行以下代码后，同时发出的请求超过5个
```js
const req = () =>
  Taro.request({
    url: 'https://taro.aotu.io/'
  });
for (let i = 0; i < 20; i++) {
  req();
}
```
![image](https://user-images.githubusercontent.com/5136032/71573369-80e92e00-2b1e-11ea-919d-7f3b61b2a013.png)

在下面代码里面队列的长度不可能会大于1吧
https://github.com/NervJS/taro/blob/2.x/packages/taro-weapp/src/native-api.js#L28

### 版本
Taro CLI 1.3.19 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.19 => 1.3.19 
      @tarojs/cli: 1.3.19 => 1.3.19 
      @tarojs/components: 1.3.19 => 1.3.19 
      @tarojs/mobx: 1.3.19 => 1.3.19 
      @tarojs/mobx-h5: 1.3.19 => 1.3.19 
      @tarojs/plugin-babel: 1.3.19 => 1.3.19 
      @tarojs/plugin-csso: 1.3.19 => 1.3.19 
      @tarojs/plugin-sass: 1.3.19 => 1.3.19 
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19 
      @tarojs/router: 1.3.19 => 1.3.19 
      @tarojs/taro: 1.3.19 => 1.3.19 
      @tarojs/taro-alipay: 1.3.19 => 1.3.19 
      @tarojs/taro-h5: 1.3.19 => 1.3.19 
      @tarojs/taro-swan: 1.3.19 => 1.3.19 
      @tarojs/taro-weapp: 1.3.19 => 1.3.19 
      @tarojs/webpack-runner: 1.3.19 => 1.3.19 
      eslint-config-taro: 1.3.19 => 1.3.19 
      eslint-plugin-taro: 1.3.19 => 1.3.19 
      nerv-devtools: ^1.4.4 => 1.5.6 
      nervjs: ^1.4.4 => 1.5.6 
      react: ^16.7.0 => 16.7.0 
    npmGlobalPackages:
      typescript: 3.6.4

**Comment by Inori-Lover** [comment]
不能按照模板发issue的？

另外为什么长度不大于1？当前并发小于最大并发限制时就shift一个出来跑，问题是？

**Comment by shenghanqin** [comment]
请按照标准issue模板提出问题，并尽量给更多的demo、源代码示例。

**Comment by xn330125** [comment]
> 请按照标准issue模板提出问题，并尽量给更多的demo、源代码示例。

已补充信息

**Comment by Inori-Lover** [comment]
> > 请按照标准issue模板提出问题，并尽量给更多的demo、源代码示例。
> 
> 已补充信息

![image](https://user-images.githubusercontent.com/9866055/71576168-9a907280-2b2a-11ea-8b6f-b29d9ed583d6.png)

it seem all right?

**Comment by xn330125** [comment]
> > > 请按照标准issue模板提出问题，并尽量给更多的demo、源代码示例。
> > 
> > 
> > 已补充信息
> 
> 6个不是刚刚好？代码就是6个……虽然那个MAX_REQUEST有点迷。
> 因为在5个的时候还可以run

你看那个灰色条的开始时间，实际有10个请求同时Stalled。

**Comment by Inori-Lover** [comment]
em

> > > > 请按照标准issue模板提出问题，并尽量给更多的demo、源代码示例。
> > > 
> > > 
> > > 已补充信息
> > 
> > 
> > 6个不是刚刚好？代码就是6个……虽然那个MAX_REQUEST有点迷。
> > 因为在5个的时候还可以run
> 
> 你看那个灰色条的开始时间，实际有10个请求同时Stalled。6个的限制也是因为达到了Chrome的最大6个tcp连接限制。
> 我打印了请求队列的长度，一直都是1，感觉这边计数逻辑是有问题的

emmmm, 确实。这个实现有问题。（个人看法
它根本没记录并发的队列，只记录了等待的。由于等待的不断被shift出来所以页不可能并发到。


这个时候我也想起一个bug，就是超时设置。
我在小程序里边写了超时之后发现初始化的时候请求数一多就很容易超时，尽管没有一个是超时的。
小程序应该是放开了并发报错的限制，但是超时的没有跟着修改

**Comment by luckyadam** [comment]
确实有问题，我们看下
