### ISSUE TITLE
使用微信小程序Switch组件无法控制开关状态

### ISSUE THREAD

**Issue by Mypika** [NervJS/taro#5218]
### 问题描述
使用Switch组件时，开关状态不受checked属性影响，无法在onChange事件中控制。使用正常小程序写法则没有这个问题。

### 复现步骤
1. 打开'...'
![image](https://user-images.githubusercontent.com/40252390/71571791-11bc0b80-2b17-11ea-96e8-8ef1e701216d.png)

2. 点击'....'
![image](https://user-images.githubusercontent.com/40252390/71571791-11bc0b80-2b17-11ea-96e8-8ef1e701216d.png)

3. 看见的现象...
![image](https://user-images.githubusercontent.com/40252390/71571824-3912d880-2b17-11ea-8e23-30488719f5bf.png)

```js
class Sitefrom extends Component {
    constructor(props){
        super(props)
        this.state={
            defaultSite:true,//是否为默认地址
        }
    }
    config = {
        navigationStyle:'default',
        navigationBarBackgroundColor:'#FD9C96',
        navigationBarTitleText:'编辑收货地址',
        backgroundColor:'#f0f0f0',
        backgroundTextStyle:'dark'
    }
    SwitchChange=(e)=>{
        this.setState({
            defaultSite:true
        })
    }
  render () {
    return (
      <View className='Sitefrom'>
        <View className="checked">
            <View>设为默认地址</View>
            <Switch checked={this.state.defaultSite}
                    onChange={this.SwitchChange} 
                    color="#FD9C96" />
        </View>
      </View>
    )
  }
}

```

### 期望行为

我希望在onChange回调函数里来控制Switch开关的状态，
### 系统信息

�👽 Taro v1.3.14

  Taro CLI 1.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\YJ-DELLG3-01\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
### 补充信息

**Comment by luckyadam** [comment]
```
SwitchChange=(e)=>{
  this.setState({
    defaultSite: false
  })
  return false
}
```
这样试下

**Comment by Mypika** [comment]
貌似不行，我现在想在这个组件打开前阻止打开的行为，等我的请求完成后再打开组件，这个问题使用微信小程序写的时候并没有出现。

**Comment by Mypika** [comment]
目前的解决办法只能通过这种办法
 ```
    SwitchChange=(e)=>{
        this.setState({
            defaultSite:!this.state.defaultSite
        })
        setTimeout(() => {
            this.setState({
                defaultSite:true
            }) 
        }, 100);
    }
```
需要先给定一个状态，在请求后将值改变为期望的值。有没有更好的解决方式，
最好是在组件状态发生改变之前就可以阻止

**Comment by Chen-jj** [comment]
@Mypika 
https://nervjs.github.io/taro/docs/1.3.33/debug.html#%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%A1%A8%E5%8D%95%E7%BB%84%E4%BB%B6%E9%97%AE%E9%A2%98

微信小程序表单组件不是受控组件，当用户操作表单时视图会立即改变，但表单的 value 值还是没有变化。在这个例子里，data.defaultSite 仍然为 true，即使视图上 switch 已变为关闭态。

这时你再 setState defaultSite 为 true，diff 就会过滤掉这个更改，不去 setData，所以视图就没变。

你的写法是可以的，因为先把 data.defaultSite 和 Switch 当前状态对应上，再 setState 就可以绕过被 diff 掉。

这样更稳：

```js
this.setState({
  defaultSite:!this.state.defaultSite
}, () => {
  this.setState({
      defaultSite:true
  })
})
```

下个版本会加个开关，是否关闭 diff，下个版本可以这样写：

```js
Taro.setIsUsingDiff(false)
this.setState({
    defaultSite:true
}, () => {
  Taro.setIsUsingDiff(true)
})
```

但上述三种，Switch 组件都会出现无可避免抖动，个人认为最好还是改交互。
