### ISSUE TITLE
defineConstants 无法在页面引入

### ISSUE THREAD

**Issue by wangxi1995** [NervJS/taro#5219]
### 问题描述

版本 1.3.4
defineConstants 无法在页面引入
### 复现步骤

1. 使用命令 taro init taro_test
2. 使用命令 npm i
3. config dev.js 中 添加红框部分代码
![1577690004(1)](https://user-images.githubusercontent.com/24717491/71572169-d7536e00-2b18-11ea-985e-bd4c57c64517.jpg)
4.src pages index index.tsx中添加红框部分代码
![1577690994(1)](https://user-images.githubusercontent.com/24717491/71572303-55177980-2b19-11ea-9ce2-69e4c1183a45.jpg)
5.使用命令npm run dev:weapp
4. dist pages index index.js 中为undefined
![image](https://user-images.githubusercontent.com/24717491/71572354-a0318c80-2b19-11ea-85b1-cebb1015f374.png)

### 期望行为

期望defineConstants中设置的常量可以正常使用
### 系统信息

![image](https://user-images.githubusercontent.com/24717491/71572450-2948c380-2b1a-11ea-9967-226ca88dff92.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
建议升级到 1.3.33 试试
