### ISSUE TITLE
defineConstants在webstorm报错

### ISSUE THREAD

**Issue by LaamGinghong** [NervJS/taro#5220]
### 问题描述

在config中定义了defineConstants，使用没有问题，但是ide会报错

### 代码
```json
//  dev.js
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
    BASE_URL: '"http://station.env-zside.dev.k8s.guanmai.cn"'
  },
  mini: {},
  h5: {}
}
````

```typescript
const url = BASE_URL
// ide 提示TS2304: Cannot find name 'BASE_URL'.
```

### 期望行为

不会报错，目前使用@ts-ignore

### 报错信息

TS2304: Cannot find name 'BASE_URL'.

### 系统信息

 System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/components-qa: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/mini-runner: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/mobx: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/mobx-h5: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/router: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-alipay: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-h5: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-qq: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-quickapp: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-swan: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-tt: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/taro-weapp: 2.0.0-beta.10 => 2.0.0-beta.10 
      @tarojs/webpack-runner: 2.0.0-beta.10 => 2.0.0-beta.10 
      eslint-config-taro: 2.0.0-beta.10 => 2.0.0-beta.10 
      eslint-plugin-taro: 2.0.0-beta.10 => 2.0.0-beta.10 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.10 => 2.0.0-beta.10 
      stylelint-taro-rn: 2.0.0-beta.10 => 2.0.0-beta.10 

### 补充信息
```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "removeComments": false,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "outDir": "lib",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "baseUrl": ".",
    "rootDir": ".",
    "jsx": "preserve",
    "jsxFactory": "Taro.createElement",
    "allowJs": true,
    "resolveJsonModule": true,
    "typeRoots": [
      "node_modules/@types",
      "global.d.ts"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": [
    "**/*.tsx",
    "**/*.ts"
  ],
  "compileOnSave": false
}

```

**Comment by Garfield550** [comment]
`defineConstants` 一定会在 TS 里报错，所以请在 `global.d.ts` 里手动添加类型定义 `const BASE_URL: string;`

**Comment by shen-lan** [comment]
> BASE_URL

@Garfield550  global.d.ts 里添加了声明  vscode依然提示  ts找不到变量 

```
  global.d.ts 
---------------
declare const basicToken: string
```

```
any
找不到名称“basicToken”。ts(2304)
```

**Comment by SimbaOvO** [comment]
我写了个[Taro Plugin](https://github.com/SimbaOvO/taro-plugin-auto-declare-define-constants)来兼容`defineConstants`需要手动声明 不然编辑器报错的问题 大家可以试试～

**Comment by lihe6666** [comment]
> `defineConstants` 一定会在 TS 里报错，所以请在 `global.d.ts` 里手动添加类型定义 `declare const BASE_URL: string;`

正解
