### ISSUE TITLE
使用npm run dev:weapp 在开发这工具中点击预览，提示体积过大

### ISSUE THREAD

**Issue by liling0726** [NervJS/taro#5222]
### 问题描述

使用npm run dev:weapp 在开发这工具中点击预览，提示体积过大

### 复现步骤
1. 使用taro-cli中的taro init myApp 初始化项目，
2. yarn安装依赖
3. 运行yarn run taro  dev:weapp
4. 打开微信开发者工具，点击预览
![image](https://user-images.githubusercontent.com/10626781/71581465-5740fe80-2b40-11ea-8cca-fc54fd48e528.png)

### 期望行为

能正确提示文件大小

### 系统信息
Taro v2.0.0-beta.8

  Taro CLI 2.0.0-beta.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/components-qa: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/mini-runner: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/router: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-alipay: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-h5: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-qq: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-quickapp: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-swan: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-tt: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/taro-weapp: 2.0.0-beta.8 => 2.0.0-beta.8 
      @tarojs/webpack-runner: 2.0.0-beta.8 => 2.0.0-beta.8 
      eslint-config-taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      eslint-plugin-taro: 2.0.0-beta.8 => 2.0.0-beta.8 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.8 => 2.0.0-beta.8 
      stylelint-taro-rn: 2.0.0-beta.8 => 2.0.0-beta.8 
    npmGlobalPackages:
      typescript: 3.4.1
### 补充信息
使用小程序原生没有此问题

**Comment by luckyadam** [comment]
你可以自己看下这些文件有多大

**Comment by luckyadam** [comment]
你可以自己看下这些文件有多大

**Comment by liling0726** [comment]
@luckyadam  关闭 es6 转 es5 功能已经关闭
![image](https://user-images.githubusercontent.com/10626781/71608749-64043780-2bbe-11ea-883f-54ce9430089f.png)
运行的是Taro cli提供的例子，未做任何修改

**Comment by luckyadam** [comment]
> @luckyadam 关闭 es6 转 es5 功能已经关闭
> ![image](https://user-images.githubusercontent.com/10626781/71608749-64043780-2bbe-11ea-883f-54ce9430089f.png)
> 运行的是Taro cli提供的例子，未做任何修改
> 里面最大的vendor.js在180kb左右

180kb 很正常，你压缩之后只有几十 K，有何问题

**Comment by liling0726** [comment]
> > @luckyadam 关闭 es6 转 es5 功能已经关闭
> > ![image](https://user-images.githubusercontent.com/10626781/71608749-64043780-2bbe-11ea-883f-54ce9430089f.png)
> > 运行的是Taro cli提供的例子，未做任何修改
> > 里面最大的vendor.js在180kb左右
> 
> 180kb 很正常，你压缩之后只有几十 K，有何问题

是正常，但是在开发者工具中会报问题中说的体积过大，小程序原生没有问题

**Comment by Garfield550** [comment]
2.0 之后可以自己通过 webpackChain 方式修改 splitChunks

**Comment by wenxiayili** [comment]
> 2.0 之后可以自己通过 webpackChain 方式修改 splitChunks

能否劳烦您提供一个示例？谢谢！
