### ISSUE TITLE
[2.0.0-beta.13] 编译失败，同时报 Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by seiwhale** [NervJS/taro#5228]
### 问题描述

在使用 `2.0.0-beta.13` 版本时，在 `dev` 和 `build` 时报 `Module not found: Can't resolve 'fs'`。

### 复现步骤

1. 使用 `taro update` 命令升级至 `2.0.0-beta.13`；
2. 点击 `dev` 或 `build` 命令时，控制台正常打印出编译信息；
3. 编译完成时，打印出 `🙅   编译失败.`；
4. 紧接着报 `Module not found: Can't resolve 'fs' in 'xxx\node_modules\debug\src'`；
5. 在小程序开发者工具中查看编译结果时，显示正常。

### 期望行为

期望在使用时，能正常打印编译信息，且提示编译正常。

### 报错信息

![image](https://user-images.githubusercontent.com/32949884/71653642-9487d500-2d68-11ea-8a8f-974d2b3e3a9d.png)

```
🙅   编译失败.

./node_modules/debug/src/node.js
Module not found: Can't resolve 'fs' in 'xxx\node_modules\debug\src'
```

### 系统信息

```
Taro CLI 2.0.0-beta.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - D:\nvm\node\node.EXE
      Yarn: 1.19.1 - D:\Node\node_global\yarn.CMD
      npm: 6.13.0 - D:\Node\node_global\npm.CMD
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by seiwhale** [comment]
补充：有时可以正常监听文件变化，有时无法正常监听文件变化，必须重新启动任务才可。

**Comment by shenghanqin** [comment]
那升级前的版本是？

**Comment by seiwhale** [comment]
> 那升级前的版本是？

`2.0.0-beta.8` @shenghanqin

**Comment by luckyadam** [comment]
提供一个 demo 看下

**Comment by seiwhale** [comment]
> CLI 与项目依赖版本保持一致，如果问题还有，请提供一个 demo 看下

今天又好了，复现的时候我再提供 demo

**Comment by d0nwang** [comment]
我也遇到同样问题。在2.0.0-beta.10遇到此问题，然后将CLI和项目依赖版本都升级到2.0.0-beta.13还是没解决

**Comment by luckyadam** [comment]
> 我也遇到同样问题。在2.0.0-beta.10遇到此问题，然后将CLI和项目依赖版本都升级到2.0.0-beta.13还是没解决。使用yarn dev:weapp 虽然显示 "编译失败" 但实际有文件生成。yarn build:weapp 则会彻底失败

请提供一个 demo 看下
