### ISSUE TITLE
方法里不能引用Component么?

### ISSUE THREAD

**Issue by zmofei** [NervJS/taro#523]
你好，请问Component不能写在方法里面么？我把`<Text>Hello world!1</Text>` 写在一个方法里，页面就会报错，
```
{ SyntaxError: unknown: Unexpected token (33:11)
```
请问如何解决？

```javascript
export default class Index extends Component {
  // ...
  subRender(){
    return <Text>Hello world!1</Text>;
  }

  render() {
    return (
      <View className='index'>
        {this.subRender()}
      </View>
    )
  }
}
```
附上代码
[index.tsx.zip](https://github.com/NervJS/taro/files/2321537/index.tsx.zip)

```
"dependencies": {
    "@tarojs/components": "^1.0.0-beta.15",
    "@tarojs/router": "^1.0.0-beta.15",
    "@tarojs/taro": "^1.0.0-beta.15",
    "@tarojs/taro-h5": "^1.0.0-beta.15",
    "@tarojs/taro-weapp": "^1.0.0-beta.15",
    "nervjs": "^1.3.0"
  },
```
node v8.10.0

**Comment by zmofei** [comment]
Follow up:

发现把组件写在render用 if else来赋值是可以运行的，但是**改成switch case**或者**放在render以外的function**中，就无法执行。

这是为什么？

**Comment by yuche** [comment]
现在还不能支持 `render` 之外写 JSX，[eslint 插件有这样一条规则](https://github.com/NervJS/taro/tree/master/packages/eslint-plugin-taro)。

`switch` 支持起来相对简单，应该很快能支持到。

**Comment by zmofei** [comment]
了解了谢谢

**Comment by shhdgit** [comment]
> 现在还不能支持 `render` 之外写 JSX，[eslint 插件有这样一条规则](https://github.com/NervJS/taro/tree/master/packages/eslint-plugin-taro)。
> 
> `switch` 支持起来相对简单，应该很快能支持到。

请问一下 `switch` 现在支持了吗
