### ISSUE TITLE
tarojs/cli能否本地安装

### ISSUE THREAD

**Issue by beijipc** [NervJS/taro#5232]
出于一些原因，不想全局安装cli，能否项目本地安装？

**Comment by Garfield550** [comment]
完全可以。

`npm install --save-dev` 和 `yarn add -D` 即可。

**Comment by beijipc** [comment]
谢谢，可以了。
不过值得提醒各位的是移至项目内后就无法通过命令行执行taro xxx了，要在scripts内访问

**Comment by Garfield550** [comment]
模版已经帮你配置好了常用端的 `scripts`
