### ISSUE TITLE
hooks用法里面的触底刷新useReachBottom方法不调用

### ISSUE THREAD

**Issue by yangdan-yd** [NervJS/taro#5233]
### Taro UI 版本信息

2.2.4

### 问题描述

hooks用法里面的触底刷新useReachBottom方法不调用

### 复现步骤

1.go to

### 复现代码

import Taro, { useState, useRouter, useReachBottom } from '@tarojs/taro'
import { useSelector } from '@tarojs/redux'
import { View, Text } from '@tarojs/components'
import PropTypes from 'prop-types'
import style from './index.module.css'
import service from '../../../service'

const List = props => {
  const userInfo = useSelector(state => state.user)
  const { params } = useRouter()
  const [pageNum, setPageNum] = useState(1)
  const [infoList, setInfoList] = useState('')
  const [counts, setCount] = useState('')
  const [load, setLoad] = useState(true)
  // 构建url
  const buildURL = (url, query = {}, isSequence = true) => {
    if (!query) return url
    const joiner = url.match(/\?/) ? '&' : '?'
    const queryStr = Object.keys(query)
      .map(
        key =>
          `${key}=${encodeURIComponent(
            isSequence ? JSON.stringify(query[key]) : query[key]
          )}`
      )
      .join('&')
    return url   joiner   queryStr
  }
  // 解析query对象
  const decodeQuery = (originQuery = {}, isSequence = true) => {
    const result = {}
    if (!originQuery) return {}
    return Object.keys(originQuery).reduce((prev, curr) => {
      result[curr] = decodeURIComponent(originQuery[curr])
      if (isSequence) {
        result[curr] = JSON.parse(result[curr])
      }
      return result
    }, result)
  }

  let infoData = decodeQuery(params).infoData
  let pageNums = decodeQuery(params).pageNum
  // let codeName = decodeQuery(params).name
  // let userId = decodeQuery(params).userId
  setPageNum(pageNums)
  setInfoList(infoData.info)
  setCount(infoData.count)
  let userName = infoData.name
  const info = infoData.info
  const handlerDetail = data => {
    let url = buildURL(
      '/rensheting/pages/human-society/old-age-treatment/detail',
      {
        userObj: data,
        userName: userName
      }
    )
    Taro.navigateTo({
      url
    })
  }

  useReachBottom(() => {
    console.log('111:', 111)
    if (load) {
      //全局标志位，方式请求未响应是多次触发
      if (infoList.length < counts) {
        console.log('2222:', 2222)
        setLoad(false)
        service
          .getTreatmentServiceData(userInfo.name, userInfo.id, pageNum)
          .then(
            res => {
              console.log('res:', res)
              const content = infoList.concat(res.infoData.info) //将放回结果放入content
              const pageNumber = pageNum * 1   1
              setInfoList(content)
              setPageNum(pageNumber)
              setLoad(true)
              console.log('22222222222222:', 22222222222222)
            },
            err => {
              console.log(err)
              Taro.showToast({
                title: '业务系统繁忙，请稍后重试',
                icon: 'none'
              })
            }
          )
      }
    }
  })

  return (
    <View className={style.content} >
      {info.map((item, index) => {
        return (
          <View
            className={style.box}
            onClick={() => {
              handlerDetail(item)
            }}
          >
            <View className={style.flexBox}>
              <View className={style.user}>{userName}</View>
            </View>
            <View className={style.flexBox}>
              <View className={style.tit}>发放期号</View>
              <View className={style.txt}>{item.mechanismInfo.qihao}</View>
            </View>
            <View className={style.flexBox}>
              <View className={style.tit}>待遇金额</View>
              <View className={style.txt}>{item.mechanismInfo.jine}</View>
            </View>
          </View>
        )
      })}
    </View>
  )
}
List.config = {
  navigationBarTitleText: '养老待遇发放',
  onReachBottomDistance: 20
}
List.propTypes = {}

List.defaultProps = {}

export default List

### 报错信息

useReachBottom方法不调用，但是没有报错

### 系统信息

1.3.22

**Comment by Chen-jj** [comment]
@yangdan-yd 请整理好代码格式

**Comment by Chen-jj** [comment]
@yangdan-yd 复现不了。

```js
const List = () => {
  useReachBottom(() => {
    console.log('reach')
  })

  const arr = [...Array(30).keys()]

  return (
    <View>
      {
        arr.map(item => <View>{item}</View>)
      }
    </View>
  )
}

List.config = {
  navigationBarTitleText: '养老待遇发放',
  onReachBottomDistance: 20
}

export default List
```

![image](https://user-images.githubusercontent.com/11807297/72261650-30122300-3650-11ea-942a-efdab23cf90a.png)
