### ISSUE TITLE
beta.13 版本， 组件编译错误 Component is not found in path

### ISSUE THREAD

**Issue by larry011** [NervJS/taro#5236]
### 问题描述

编译的页面数量到达一定数量时，组件编译报错。 bug发生时的页面数量有 45 个。

### 复现步骤

1. app.js 中的页面注释一半，编译成功
2. 慢慢的增加页面编译数量，编译出来的组件会报错

### 报错信息

![image](https://user-images.githubusercontent.com/10259971/71727086-27616600-2e74-11ea-8f93-40568d101d84.png)

### 系统信息

👽 Taro v2.0.0-beta.13

  Taro CLI 2.0.0-beta.13 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/components: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/mini-runner: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/plugin-babel: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/plugin-csso: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/plugin-sass: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/plugin-uglifyjs: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/redux: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/redux-h5: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/router: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-alipay: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-h5: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-swan: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-tt: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-weapp: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/webpack-runner: 2.0.0-beta.13 => 2.0.0-beta.13 
      eslint-config-taro: 2.0.0-beta.13 => 2.0.0-beta.13 
      eslint-plugin-taro: 2.0.0-beta.13 => 2.0.0-beta.13 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.13 => 2.0.0-beta.13 
      stylelint-taro-rn: 2.0.0-beta.13 => 2.0.0-beta.13 

### 补充信息

目前报错的是 radio 组件
调试了下源码，发现组件正常编译时，在 fileParseLoader 文件，使用 this._module 拿到的 module 是 TaroNormalModule 构造的：

![image](https://user-images.githubusercontent.com/10259971/71727748-3ba66280-2e76-11ea-9d60-3767230a85fc.png)

![image](https://user-images.githubusercontent.com/10259971/71728218-6fce5300-2e77-11ea-9957-89ea1552b5c2.png)

当错误时，this._module 拿到的是 NormalModule 构造的：

![image](https://user-images.githubusercontent.com/10259971/71728251-8d032180-2e77-11ea-9825-f6923c52d94b.png)

但是看了 MiniPlugin 中的逻辑，创建的 Module 确实是使用 TaroNormalModule 构造的，不知道在哪一个步骤被修改了
![image](https://user-images.githubusercontent.com/10259971/71728057-11a17000-2e77-11ea-9263-4427fca4596b.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
经沟通，书写错误导致，请不要引用组件文件后直接打印，或者做其他非组件使用方式的用途
