### ISSUE TITLE
网络问题导致至chunk fail,没有对应钩子函数处理

### ISSUE THREAD

**Issue by aizigao** [NervJS/taro#5238]
### 问题描述

网络问题导致至chunk fail,没有对应钩子函数处理
### 复现步骤

1. 进入任意页面
2. 断开网络,或者网络条件极差时
3. 点击到其它页面
4. 加载chunk 失败
5. 查看console日志

![image](https://user-images.githubusercontent.com/14126445/71758899-341ba380-2ee0-11ea-8fa4-dba823232169.png)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

我看了打包原码，在h5端router import()失败后只有一个console没有对应的钩子处理，如果有对应的hook的话，我自行处理就可以了, 也是要整个 $router.onError的方法处理一下
```js
 key: "updateComponent",
    value: function updateComponent() {
      var _this2 = this;

      var props = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : this.props;
      props.componentLoader().then(function (_ref) {
        var component = _ref.default;

        if (!component) {
          throw Error("Received a falsy component for route \"".concat(props.path, "\". Forget to export it?"));
        }

        var WrappedComponent = createWrappedComponent(component);
        _this2.wrappedComponent = WrappedComponent;

        _this2.forceUpdate();
      }).catch(function (e) {
        console.error(e); // ------------ 这个需要加一个hook
      });
    }
```
### 系统信息

```shell
👽 Taro v1.3.27


  Taro CLI 1.3.27 environment info:
    System:
      OS: Linux 4.14 Manjaro Linux undefined
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 13.3.0 - /tmp/fnm-shell-4425861/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.1 - /tmp/fnm-shell-4425861/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.27 => 1.3.27 
      @tarojs/cli: 1.3.27 => 1.3.27 
      @tarojs/components: 1.3.27 => 1.3.27 
      @tarojs/mobx: 1.3.27 => 1.3.27 
      @tarojs/mobx-h5: 1.3.27 => 1.3.27 
      @tarojs/mobx-rn: 1.3.27 => 1.3.27 
      @tarojs/plugin-babel: 1.3.27 => 1.3.27 
      @tarojs/plugin-csso: 1.3.27 => 1.3.27 
      @tarojs/plugin-sass: 1.3.27 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.27 => 1.3.27 
      @tarojs/rn-runner: 1.3.27 => 1.3.27 
      @tarojs/router: 1.3.27 => 1.3.27 
      @tarojs/taro: 1.3.27 => 1.3.27 
      @tarojs/taro-alipay: 1.3.27 => 1.3.27 
      @tarojs/taro-h5: 1.3.27 => 1.3.27 
      @tarojs/taro-swan: 1.3.27 => 1.3.27 
      @tarojs/taro-tt: 1.3.27 => 1.3.27 
      @tarojs/taro-weapp: 1.3.27 => 1.3.27 
      @tarojs/webpack-runner: 1.3.27 => 1.3.27 
      eslint-config-taro: 1.3.27 => 1.3.27 
      eslint-plugin-taro: 1.3.27 => 1.3.27 
      nerv-devtools: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.27 => 1.3.27 
      stylelint-taro-rn: 1.3.27 => 1.3.27 
    npmGlobalPackages:
      typescript: 3.7.3
```
### 补充信息
相关问题我看到有
- https://github.com/NervJS/taro/issues/5190
- https://github.com/NervJS/taro/issues/4696

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by aizigao** [comment]
暂时改写了cli下的h5 helper文件，望有官方方案
node_modules/@tarojs/cli/dist/h5/helper.js
```js

function createRoute({ pageName, isIndex, lazyload = true }) {
    const absPagename = exports.addLeadingSlash(pageName);
    const relPagename = `.${absPagename}`;
    const chunkName = relPagename.split('/').filter(v => !/^(pages|\.)$/i.test(v)).join('_');
    if (lazyload) {
        const chunkNameComment = chunkName ? `/* webpackChunkName: "${chunkName}" */` : '';
    // TODO: remove --------------------------------------############# -----
    // TIP: 添加onHackRouterLoadErr的钩子
        return `{
      path: '${absPagename}',
      componentLoader: () =>{
        return new Promise((res,rej)=>{
         import(${chunkNameComment}'${relPagename}')
         .then((d)=>{res(d)})
         .catch(e=>{
           this.onHackRouterLoadErr && this.onHackRouterLoadErr(e)  
           rej(e)
         })
        })
       },
      isIndex: ${isIndex}
    }`;
    }
    else {
        return `{
      path: '${absPagename}',
      componentLoader: () => Promise.resolve(require('${relPagename}')),
      isIndex: ${isIndex}
    }`;
    }
}
```

**Comment by wlancer1** [comment]
> 暂时改写了cli下的h5 helper文件，望有官方方案
> node_modules/@tarojs/cli/dist/h5/helper.js
> 
> ```js
> function createRoute({ pageName, isIndex, lazyload = true }) {
>     const absPagename = exports.addLeadingSlash(pageName);
>     const relPagename = `.${absPagename}`;
>     const chunkName = relPagename.split('/').filter(v => !/^(pages|\.)$/i.test(v)).join('_');
>     if (lazyload) {
>         const chunkNameComment = chunkName ? `/* webpackChunkName: "${chunkName}" */` : '';
>     // TODO: remove --------------------------------------############# -----
>     // TIP: 添加onHackRouterLoadErr的钩子
>         return `{
>       path: '${absPagename}',
>       componentLoader: () =>{
>         return new Promise((res,rej)=>{
>          import(${chunkNameComment}'${relPagename}')
>          .then((d)=>{res(d)})
>          .catch(e=>{
>            this.onHackRouterLoadErr && this.onHackRouterLoadErr(e)  
>            rej(e)
>          })
>         })
>        },
>       isIndex: ${isIndex}
>     }`;
>     }
>     else {
>         return `{
>       path: '${absPagename}',
>       componentLoader: () => Promise.resolve(require('${relPagename}')),
>       isIndex: ${isIndex}
>     }`;
>     }
> }
> ```

这个钩子要怎么用啊

**Comment by aizigao** [comment]
> > 暂时改写了cli下的h5 helper文件，望有官方方案
> > node_modules/@tarojs/cli/dist/h5/helper.js
> > ```js
> > function createRoute({ pageName, isIndex, lazyload = true }) {
> >     const absPagename = exports.addLeadingSlash(pageName);
> >     const relPagename = `.${absPagename}`;
> >     const chunkName = relPagename.split('/').filter(v => !/^(pages|\.)$/i.test(v)).join('_');
> >     if (lazyload) {
> >         const chunkNameComment = chunkName ? `/* webpackChunkName: "${chunkName}" */` : '';
> >     // TODO: remove --------------------------------------############# -----
> >     // TIP: 添加onHackRouterLoadErr的钩子
> >         return `{
> >       path: '${absPagename}',
> >       componentLoader: () =>{
> >         return new Promise((res,rej)=>{
> >          import(${chunkNameComment}'${relPagename}')
> >          .then((d)=>{res(d)})
> >          .catch(e=>{
> >            this.onHackRouterLoadErr && this.onHackRouterLoadErr(e)  
> >            rej(e)
> >          })
> >         })
> >        },
> >       isIndex: ${isIndex}
> >     }`;
> >     }
> >     else {
> >         return `{
> >       path: '${absPagename}',
> >       componentLoader: () => Promise.resolve(require('${relPagename}')),
> >       isIndex: ${isIndex}
> >     }`;
> >     }
> > }
> > ```
> 
> 这个钩子要怎么用啊

1. 将taro cli装在node_module里
```
npm i @taro/cli@xxxxx
npm i shx // 一些跨平台的命令，类shell
```
2. 修改package.json
```js
script:{
...
"build:h5": "./node_modules/.bin/taro build --type h5", // 改一条
"postinstall": "shx cp script/patchFiles/trao-cli-h5-helper.js node_modules/@tarojs/cli/dist/h5/helper.js" //加一条
...
```
3. 复制node_modules/@tarojs/cli/dist/h5/helper.js 到 script/patchFiles/trao-cli-h5-helper.js(项目目录，自行创建， npm install后执行postinstall)
4. 修改内容，为上面的内容，主要改一下模板
5. 钩子用法
src/app.jsx
```
....
class App extends Component {
  
  componentDidMount() {
    // ...
  }

  componentDidNotFound() {
    if (!includes(this.config.pages, Taro._$router.path)) {
      // 404页面
      redirectTo('/pages/errPage/index');
    }
  }
  componentDidShow() {}

  componentDidHide() {}
  // ------------------------------- * 看这里， 直接加一个方法, 处理内容，自行添中，我是整了一个弹窗提示一下 -----------------------------------
  // TODO: remove HACK: Taro 在 import() fail时没有加钩子，hack一下
  onHackRouterLoadErr = e => {
    setTimeout(() => {
      Taro.showModal({
        showCancel: false,
        content: '网络加载失败, 请重试'
      });
    }, 300);
    navigateBack();
    debugLog.error('[router]', e);
  };
 // ---------------------------------------------------

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    );
  }
}

Taro.render(<App />, document.getElementById('app'));

```

**Comment by divcss3** [comment]
```
if (process.env.TARO_ENV === 'h5') {
  const consoleError = console.error
  console.error = e => {
    if (e.name === 'ChunkLoadError' || /Loading.+failed/gi.test(e.message)) {
      // Taro.showModal({
      //   title: locale.common['网络连接失败'],
      //   cancelText: locale.common['重新加载'],
      //   confirmText: locale.common['返回首页'],
      //   success(res) {
      //     if (res.confirm) {
      //       window.location.href = '/'
      //     }
      //     if (res.cancel) {
      //       window.location.reload()
      //     }
      //   }
      // })
      setTimeout(() => {
        window.location.reload()
      }, 333)
    }
    consoleError && consoleError(e)
  }
}

这样也可以临时解决
