### ISSUE TITLE
发现npm run dev:alipay之后，每次修改保存都要重新启动server，导致编译巨慢

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#5240]
### 问题描述

npm run dev:alipay之后，每次修改保存都要重新启动server，导致编译巨慢

### 复现步骤
新建项目，编译成alipay，在支付宝ide中显示效果，然后修改taro项目中随意a.js文件（比如加个空格）然后保存，taro监听到文件变动，编译成a.axml/a.js等等，观察支付宝模拟器日志，发现又重新启动了server，导致一个空格编译需要一分钟

### 期望行为

像在支付宝ide中修改axml一样，一两秒就能编译出来

### 报错信息

上图中，左边是taro修改文件编译时模拟器日志
右边是支付宝ide中修改axml日志

对比发现taro在Dev server is ready on http://127.0.0.1:64180到Compiled with warnings.完成  需要一分钟左右

### 系统信息
Taro v1.3.19

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/71763320-b1add680-2f15-11ea-85da-0d423e39f1c0.png)

**Comment by luckyadam** [comment]
这是支付宝开发者工具的问题（一分钟确实太久，你的电脑应该要换了
