### ISSUE TITLE
用hook重构之前的class写的页面，但是函数中如何设置config(页面标题相关的属性)呢？

### ISSUE THREAD

**Issue by caoliren** [NervJS/taro#5243]
![image](https://user-images.githubusercontent.com/20277781/71776135-34429e80-2fc7-11ea-8b4a-b72f2975c9f0.png)
![image](https://user-images.githubusercontent.com/20277781/71776140-3d337000-2fc7-11ea-83c5-c19912387be6.png)
config是Taro.Component中的属性，所以如果不继承Taro.Component的话是不是没办法设置页面的config?
求问大佬们在函数中有办法设置页面的config吗？

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/hooks.html#%E9%A1%B5%E9%9D%A2%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B8%AD%E7%9B%B8%E5%85%B3%E5%B1%9E%E6%80%A7%E8%AE%BE%E7%BD%AE
多看看文档

**Comment by caoliren** [comment]
> https://nervjs.github.io/taro/docs/hooks.html#%E9%A1%B5%E9%9D%A2%E5%8F%8A%E7%BB%84%E4%BB%B6%E4%B8%AD%E7%9B%B8%E5%85%B3%E5%B1%9E%E6%80%A7%E8%AE%BE%E7%BD%AE
> 多看看文档

谢谢，粗心了
