### ISSUE TITLE
2.0.0-beta.13版本 "polyfill": true 开启报错

### ISSUE THREAD

**Issue by xuzpeng** [NervJS/taro#5245]
### 问题描述

config/index.js babel 配置开启 polyfill 报错，提示$export is not a function

babel: {
    sourceMap: true,
    presets: [
      ['env', {
        modules: false
      }]
    ],
    plugins: [
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-object-rest-spread',
			['transform-runtime', {
				"helpers": false,
				"polyfill": true,
				"regenerator": true,
				"moduleName": 'babel-runtime'
			}]
    ]
  },

版本

👽 Taro v2.0.0-beta.13

  Taro CLI 2.0.0-beta.13 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/components-qa: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/mini-runner: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/mobx: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/mobx-h5: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/router: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-alipay: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-h5: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-qq: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-quickapp: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-swan: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-tt: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/taro-weapp: 2.0.0-beta.13 => 2.0.0-beta.13 
      @tarojs/webpack-runner: 2.0.0-beta.13 => 2.0.0-beta.13 
      eslint-config-taro: 2.0.0-beta.13 => 2.0.0-beta.13 
      eslint-plugin-taro: 2.0.0-beta.13 => 2.0.0-beta.13 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.0-beta.13 => 2.0.0-beta.13 
      stylelint-taro-rn: 2.0.0-beta.13 => 2.0.0-beta.13

**Comment by luckyadam** [comment]
不能直接开启，有些 polyfill 方式在小程序中无法使用，请按照自己的需求按需引入 polyfill

**Comment by xuzpeng** [comment]
如果只要引一次polyfill，在app.tsx中import一次就可以了吗？
