### ISSUE TITLE
flat，startsWith等编译不了，提示is not a function

### ISSUE THREAD

**Issue by xuzpeng** [NervJS/taro#5246]
无法识别es2019等的语法，配置了babel无效，貌似taro中的babel版本是6？
尝试引了babel-polyfill等的方法，发现babel-polyfill里面没有flat，只有flatten，没敢用。。
可以麻烦贴个配置吗？我试过好几次都不行....配置都无效....

现在是config/index配置如下：
```
plugins: {
		babel: {
			sourceMap: true,
			presets: [
				['env', {
					modules: false,
					useBuiltIns: true,
					debug: false
				}]
			],
			plugins: [
				'transform-decorators-legacy',
				'transform-class-properties',
				'transform-object-rest-spread'
			]
		},
```
然后在 app.tsx 中
import '@tarojs/async-await';
import 'babel-polyfill';

不知道这样有效与否，而且 polyfill 也是只有 stars-with这样，没 flat...

官方可以给个配置不，自己配置都没成功....

版本：
👽 Taro v1.3.34

  Taro CLI 1.3.34 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.34 => 1.3.34 
      @tarojs/components: 1.3.34 => 1.3.34 
      @tarojs/mobx: 1.3.34 => 1.3.34 
      @tarojs/mobx-h5: 1.3.34 => 1.3.34 
      @tarojs/mobx-rn: 1.3.34 => 1.3.34 
      @tarojs/plugin-babel: 1.3.34 => 1.3.34 
      @tarojs/plugin-csso: 1.3.34 => 1.3.34 
      @tarojs/plugin-stylus: 1.3.34 => 1.3.34 
      @tarojs/plugin-uglifyjs: 1.3.34 => 1.3.34 
      @tarojs/rn-runner: 1.3.34 => 1.3.34 
      @tarojs/router: 1.3.34 => 1.3.34 
      @tarojs/taro: 1.3.34 => 1.3.34 
      @tarojs/taro-alipay: 1.3.34 => 1.3.34 
      @tarojs/taro-h5: 1.3.34 => 1.3.34 
      @tarojs/taro-swan: 1.3.34 => 1.3.34 
      @tarojs/taro-tt: 1.3.34 => 1.3.34 
      @tarojs/taro-weapp: 1.3.34 => 1.3.34 
      @tarojs/webpack-runner: 1.3.34 => 1.3.34 
      eslint-config-taro: 1.3.34 => 1.3.34 
      eslint-plugin-taro: 1.3.34 => 1.3.34 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.34 => 1.3.34 
      stylelint-taro-rn: 1.3.34 => 1.3.34

**Comment by luckyadam** [comment]
https://www.google.com/search?q=flat+polyfill&oq=flat+polyfi&aqs=chrome.1.69i57j0l7.3913j0j4&sourceid=chrome&ie=UTF-8
自己在项目中引入相关 polyfill

**Comment by xuzpeng** [comment]
那是在 app .jsx全局import一次就可以了吗？还是必须得相应的页面或组件中每次都import？
