### ISSUE TITLE
非tabBar页面无法路由跳转到带tabBar页面

### ISSUE THREAD

**Issue by chinacoolboyzz** [NervJS/taro#525]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
非tabBar页面无法路由跳转到带tabBar页面
反过来带tabBar页面可以路由跳转到非tabBar页面

**复现步骤**
```js
// app.js
config = {
    pages: [
      'pages/index/index',
      'pages/home/home',
    ],
    tabBar: {
      list: [{
        pagePath: "pages/home/home",
        text: "首页",
        iconPath: "./asset/images/index.png",
        selectedIconPath: "./asset/images/index_focus.png"
      }]
    }
  }

// index.js
onClick = () => {
 Taro.navigateTo({
      url: '/pages/home/home'
    })
}
```
**期望行为**
期望非tabBar页面能正常跳转到带tabBar页面

**报错信息**
{errMsg: "redirectTo:fail can not redirectTo a tabbar page"}

**系统信息**
 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]

**Comment by luckyadam** [comment]
这是小程序的规定，跳转到 tabBar 页面使用 `Taro.switchTab`
另外，版本有点旧哦，可以升级到最新的 beta 版本

**Comment by wokill** [comment]
同样的问题，在H5状态下，使用Taro.redirectTo跳转到带tabbar的页面之后，tabbar会丢失显示不出来。。taro版本为：1.1.0

**Comment by luckyadam** [comment]
@wokill 这是 H5 的 tabbar ，正在解决~

**Comment by tzerocode** [comment]
> 这是小程序的规定，跳转到 tabBar 页面使用 `Taro.switchTab`
> 另外，版本有点旧哦，可以升级到最新的 beta 版本

解决了今天的困惑，感谢！
