### ISSUE TITLE
taro产物能作为微信小程序子包被引用吗？

### ISSUE THREAD

**Issue by durongzhang** [NervJS/taro#5251]
### 问题描述

taro微信产物作为子包被引入会报错

### 复现步骤

taro产物删除project.config.json和app.json并复制进主微信小程序子包目录，主小程序app.json添加
```
"subpackages": [
    {
      "root": "package1",
      "pages": [
        "pages/home/index"
      ]
    }
  ]

```

### 期望行为

taro项目产物能作为子包被引用

### 报错信息

![image](https://user-images.githubusercontent.com/15725537/71800867-332b7300-3094-11ea-9fbf-690c6d83be62.png)

### 系统信息

taro版本：1.3.30

**Comment by luckyadam** [comment]
你在这个页面里也引入一下 `@tarojs/async-await` ，然后再编译出来给微信小程序子包用

**Comment by durongzhang** [comment]
> 你在这个页面里也引入一下 `@tarojs/async-await` ，然后再编译出来给微信小程序子包用

这样其他文件中都需要去引入@tarojs/async-await

在使用redux的情况下还会出现其他错误，因为taro app.js中会会涉及到一些模块的初始化
![image](https://user-images.githubusercontent.com/15725537/71881260-f2ebf380-316c-11ea-9dd8-dbd6c6e4983b.png)
