### ISSUE TITLE
A页面 preload传参 B页面获取undefined

### ISSUE THREAD

**Issue by PlutoCA** [NervJS/taro#5252]
### 问题描述
在A页面使用this.$preload 传参 跳转到B页面 ，B页面的componentWillMount this.$router.preload 打印出来undefine

### 复现步骤
```javascript
    // a页面传参跳转
     this.$preload({
        data,
        num,
      })
      Taro.navigateTo({
        url: '/pages/confirm_order/confirm_order'
      })

   // B页面接收
 componentWillMount () {
    console.log('preload: ', this.$router.preload) // undefined
  }
```
![image](https://user-images.githubusercontent.com/31099607/71804779-73dcb980-309f-11ea-9068-5b6262d88997.png)

### 期望行为

能获取到A页面传过来的参数

### 报错信息

undefined

### 系统信息

```node
Taro CLI 1.3.31 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.19.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.31 => 1.3.31 
      @tarojs/components: 1.3.31 => 1.3.31 
      @tarojs/plugin-babel: 1.3.31 => 1.3.31 
      @tarojs/plugin-csso: 1.3.31 => 1.3.31 
      @tarojs/plugin-sass: 1.3.31 => 1.3.31 
      @tarojs/plugin-uglifyjs: 1.3.31 => 1.3.31 
      @tarojs/router: 1.3.31 => 1.3.31 
      @tarojs/taro: 1.3.31 => 1.3.31 
      @tarojs/taro-alipay: 1.3.31 => 1.3.31 
      @tarojs/taro-h5: 1.3.31 => 1.3.31 
      @tarojs/taro-qq: 1.3.31 => 1.3.31 
      @tarojs/taro-quickapp: 1.3.31 => 1.3.31 
      @tarojs/taro-swan: 1.3.31 => 1.3.31 
      @tarojs/taro-tt: 1.3.31 => 1.3.31 
      @tarojs/taro-weapp: 1.3.31 => 1.3.31 
      @tarojs/webpack-runner: 1.3.31 => 1.3.31 
      eslint-config-taro: 1.3.31 => 1.3.31 
      eslint-plugin-taro: 1.3.31 => 1.3.31 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 1.3.31 => 1.3.31 
      stylelint-taro-rn: 1.3.31 => 1.3.31 
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@PlutoCA 复现不了，升级到最新版本后再试试吧。

![image](https://user-images.githubusercontent.com/11807297/71808335-860f2580-30a8-11ea-8c2b-e3b7c989744b.png)

![image](https://user-images.githubusercontent.com/11807297/71808346-8c050680-30a8-11ea-8ae5-4e595cae13ee.png)

**Comment by PlutoCA** [comment]
> @PlutoCA 复现不了，升级到最新版本后再试试吧。
> 
> ![image](https://user-images.githubusercontent.com/11807297/71808335-860f2580-30a8-11ea-8c2b-e3b7c989744b.png)
> 
> ![image](https://user-images.githubusercontent.com/11807297/71808346-8c050680-30a8-11ea-8ae5-4e595cae13ee.png)

刚刚我跑了个demo看了下 好像是OK的，我找找我这边的代码的问题

**Comment by PlutoCA** [comment]
对不起 我的问题，代码调用错了
![image](https://user-images.githubusercontent.com/31099607/71809554-4bf35300-30ab-11ea-8e09-28aa8b97a980.png)
