### ISSUE TITLE
VM1061 WAService.js:1 Uncaught TypeError: taro.handleLoopRef is not a function

### ISSUE THREAD

**Issue by carlSunLiang** [NervJS/taro#5253]
![image](https://user-images.githubusercontent.com/8129970/71806570-14cd7380-30a4-11ea-96bc-f8d4594155e5.png)

taro 版本是v1.3.19 开发者工具 v1.02.1910120

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
Taro cli 与项目依赖版本保持一致吧
