### ISSUE TITLE
scrollview 在火狐浏览器滚动中报错，导致onScroll不执行

### ISSUE THREAD

**Issue by leifeng** [NervJS/taro#5254]
### 问题描述

在火狐浏览器中滚动页面会报错

[给e.detail赋值这行,火狐报错](https://github.com/NervJS/taro/blob/94ee286140c84eeb76e8cba03fb3c63f84fe05c4/packages/taro-components/src/components/scroll-view/index.js#L178)

```setting getter-only property "detail"```

### 复现步骤
[请用火狐打开sandbox例子](https://codesandbox.io/s/nerv-sandbox-dpzfm?fontsize=14&hidenavigation=1&theme=dark)
onScroll事件没执行
### 期望行为

在火狐下可以触发onScroll事件

### 报错信息

```setting getter-only property "detail"```

**Comment by ZakaryCode** [comment]
已修复于 #b20dfc4d2600d79559fd8aea9706d1c2239f0b66
