### ISSUE TITLE
H5工程devtools报错

### ISSUE THREAD

**Issue by wsyxl365** [NervJS/taro#5256]
### 问题描述

dev:h5运行后，dev-tools报错
1.The react devtools encountered an error
2.TypeError: Cannot set property 'b02d357401a96' of undefined
    at eval (index.esm.js?4bdd:426)
    at eval (index.esm.js?4bdd:375)
    at initDevTools (index.esm.js?4bdd:459)
    at eval (index.esm.js?4bdd:536)
    at Module../node_modules/nerv-devtools/dist/index.esm.js (app.js:3817)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (app.js?a11f:1)
    at Module../.temp/app.js (app.js:915)
    at __webpack_require__ (app.js:767)
补充:已经开启了H5 devtools的调试: 
if (process.env.NODE_ENV !== 'production') {
  require('nerv-devtools')
}
app.jsx底部 Taro.render(<App />, document.getElementById('app'))和Nerv.render(<App />, document.getElementById('app')) 都试了 还是报错
### 复现步骤

npm run dev:h5，运行h5后

### 期望行为

没有报错，并且在chrome开发者工具上显示React dev tools用于state props的查看及调试

### 报错信息

The react devtools encountered an error
TypeError: Cannot set property 'b02d357401a96' of undefined
    at eval (index.esm.js?4bdd:426)
    at eval (index.esm.js?4bdd:375)
    at initDevTools (index.esm.js?4bdd:459)
    at eval (index.esm.js?4bdd:536)
    at Module../node_modules/nerv-devtools/dist/index.esm.js (app.js:3817)
    at __webpack_require__ (app.js:767)
    at fn (app.js:130)
    at eval (app.js?a11f:1)
    at Module../.temp/app.js (app.js:915)
    at __webpack_require__ (app.js:767)

### 系统信息
 Taro v1.3.31
  Taro CLI 1.3.31 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.9 => 1.3.9 
      @tarojs/cli: ^1.3.11 => 1.3.11 
      @tarojs/components: 1.3.9 => 1.3.9 
      @tarojs/plugin-babel: 1.3.9 => 1.3.9 
      @tarojs/plugin-csso: 1.3.9 => 1.3.9 
      @tarojs/plugin-sass: ^1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.9 => 1.3.9 
      @tarojs/redux: 1.3.9 => 1.3.9 
      @tarojs/redux-h5: 1.3.9 => 1.3.9 
      @tarojs/router: 1.3.9 => 1.3.9 
      @tarojs/taro: 1.3.9 => 1.3.9 
      @tarojs/taro-alipay: 1.3.9 => 1.3.9 
      @tarojs/taro-h5: 1.3.9 => 1.3.9 
      @tarojs/taro-swan: 1.3.9 => 1.3.9 
      @tarojs/taro-tt: 1.3.9 => 1.3.9 
      @tarojs/taro-weapp: 1.3.9 => 1.3.9 
      @tarojs/webpack-runner: 1.3.9 => 1.3.9 
      eslint-config-taro: 1.3.9 => 1.3.9 
      eslint-plugin-taro: 1.3.9 => 1.3.9 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.9 => 1.3.9 
      stylelint-taro-rn: 1.3.9 => 1.3.9 

### 补充信息
查看了node_modules nerv-devtools dist文件夹下的源码 index.esm.js 和 index.js后，打断点发现在initDevTools方法中, 执行到 hook._renderers[rid] = renderer后，查看显示_renderers属性为undefined,导致报错; 
hook赋值语句为 const hook = window.__REACT_DEVTOOLS_GLOBAL_HOOK__,断点查看后没有_renderers此属性，包括原型链上。

**Comment by YMaster** [comment]
> 欢迎提交 Issue~
> 
> 如果你提交的是 bug 报告，请务必遵循 [Issue 模板](https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)的规范，尽量用简洁的语言描述你的问题，最好能提供一个稳定简单的复现。🙏🙏🙏
> 
> 如果你的信息提供过于模糊或不足，或者已经其他 issue 已经存在相关内容，你的 issue 有可能会被关闭。
> 
> Good luck and happy coding~

我也想提 bug，但是你给的 Issue模板 的连接有打不开，不按照模板你们有不接受，让人怎么提？

**Comment by Garfield550** [comment]
Issue 模版是 GitHub 的域名，可能你的网访问 GitHub 不太好。

**Comment by archywillhe** [comment]
???? 没resolved？

**Comment by archywillhe** [comment]
估计devtool是用不了了。

**Comment by archywillhe** [comment]
Got the same error as well. looks like react devtool is not usable at all..

**Comment by archywillhe** [comment]
also: https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md returns 404.. I guess it is an old link or something.

**Comment by archywillhe** [comment]
<img width="1260" alt="Screenshot 2020-02-21 at 9 09 28 PM" src="https://user-images.githubusercontent.com/10269911/75037190-8a738e80-54ee-11ea-8989-024b404b9cc7.png">

**Comment by daolanfler** [comment]
issue 模板确实是 404 了🤨

**Comment by jeffrey-fu** [comment]
同样的问题

**Comment by Chen-jj** [comment]
还需要对 `react-devtool` 的支持进行兼容 #6880
