### ISSUE TITLE
枚举类型导入后使用，报ReferenceError:xxx（引用的枚举类型）is not defined.

### ISSUE THREAD

**Issue by luvletterldl** [NervJS/taro#5258]
### 复现步骤
在子组件中定义的一个枚举类型，在页面引用该组件及这个枚举类型，使用时报引用错误
![image](https://user-images.githubusercontent.com/26115291/71861701-34ab7880-3132-11ea-89a3-3a7029edd943.png)
在H5上是没有问题的
子组件中定义的枚举：
`export enum PeriodicUnit {
  Day = 'day',
  Week = 'week',
  Month = 'month',
  Year = 'year'
}`
`export type AnniversaryInfo = {
  name: string,
  markTime: number,
  periodic?: {
    unit: PeriodicUnit
  }
}`
页面中引用
`import AnniversaryItem, { AnniversaryInfo, PeriodicUnit } from '../../components/anniversary/AnniversaryItem'`

`itemInfo:AnniversaryInfo = {
    name: '7周年',
    markTime: 1577808000,
    periodic: {
      unit: PeriodicUnit.Day
    }
  }`

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息
 Taro v1.3.34

  Taro CLI 1.3.34 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.34 => 1.3.34 
      @tarojs/components: 1.3.34 => 1.3.34 
      @tarojs/components-qa: 1.3.34 => 1.3.34 
      @tarojs/plugin-babel: 1.3.34 => 1.3.34 
      @tarojs/plugin-csso: 1.3.34 => 1.3.34 
      @tarojs/plugin-sass: 1.3.34 => 1.3.34 
      @tarojs/plugin-uglifyjs: 1.3.34 => 1.3.34 
      @tarojs/redux: 1.3.34 => 1.3.34 
      @tarojs/redux-h5: 1.3.34 => 1.3.34 
      @tarojs/router: 1.3.34 => 1.3.34 
      @tarojs/taro: 1.3.34 => 1.3.34 
      @tarojs/taro-alipay: 1.3.34 => 1.3.34 
      @tarojs/taro-h5: 1.3.34 => 1.3.34 
      @tarojs/taro-qq: 1.3.34 => 1.3.34 
      @tarojs/taro-quickapp: 1.3.34 => 1.3.34 
      @tarojs/taro-rn: 1.3.34 => 1.3.34 
      @tarojs/taro-swan: 1.3.34 => 1.3.34 
      @tarojs/taro-tt: 1.3.34 => 1.3.34 
      @tarojs/taro-weapp: 1.3.34 => 1.3.34 
      @tarojs/webpack-runner: 1.3.34 => 1.3.34 
      eslint-config-taro: 1.3.34 => 1.3.34 
      eslint-plugin-taro: 1.3.34 => 1.3.34 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 1.3.34 => 1.3.34 
      stylelint-taro-rn: 1.3.34 => 1.3.34

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
由于小程序中不能直接 require 组件文件，所以组件的引用会在编译时被删除，如果组件文件中有 export 其他变量或者方法的需求，请拆分到另外一个文件中以供引用
