### ISSUE TITLE
支付宝小程序分包，主包和分包页面使用同一个组件，组件接收到的props会错乱

### ISSUE THREAD

**Issue by maoyifanDev** [NervJS/taro#5259]
### 问题描述

支付宝小程序分包，主包和分包页面使用同一个组件，页面跳转回来后，组件接收到的props实际上是上一个页面的值

### 复现步骤

1. taro init myApp 选择默认模版，安装
2. 创建一个页面a，并将其放到分包中
3. 创建组件com，内容为`<view>{this.props.cid}</view>`, 首页和页面a都使用该组件
4. 首页引入 `<com cid="1" />`, a页面引入`<com cid="2" />`
5. 首页加一个按钮点击跳转到分包的a页面
6. 在真机上预览, 从首页跳转到a页面，然后点击返回按钮，返回到首页

### 期望行为

首页上com组件展示的是 1
a页面com组件展示的是 2

### 实际上

首页上com组件展示的是 2
a页面com组件展示的是 2

### 报错信息

无报错

### 系统信息

👽 Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm

### 补充信息
打包出来的微信小程序，和支付宝模拟器上都没有此问题
使用支付宝原生写法，也没有此问题，麻烦请尽快解决，项目紧急，多谢各位了

**Comment by Chen-jj** [comment]
@maoyifanDev 有没有 demo

**Comment by maoyifanDev** [comment]
> @maoyifanDev 有没有 demo

没有，可以按照我描述的从快速新建一个，只需要分包页面和主包页面都引用同一个组件（传入不同的id），从主包跳到分包，然后返回，就会发现主包里组件的id其实是分包里组件的那个id，感觉两个页面引用的组件指向的是同一个。这个现象也只在支付宝分包的时候会出现

**Comment by Chen-jj** [comment]
@maoyifanDev 这个提交[a07ec74](https://github.com/NervJS/taro/commit/a07ec74d6d56ac9a966586f76c6017867a217900)应该修复了，等下个版本再试试吧。

**Comment by Chen-jj** [comment]
#5061
