### ISSUE TITLE
navigationBarTitleText设置国际化失效

### ISSUE THREAD

**Issue by EdisonVan** [NervJS/taro#5260]
### 问题描述
微信小程序通过三目运算符设置navigationBarTitleText的国际化，失效！Title显示为‘WeChat’。

### 复现步骤
![image](https://user-images.githubusercontent.com/38999461/71867477-33d01200-3145-11ea-8866-10609e42bc9a.png)

```js
  config = {
    navigationBarTitleText: globalData.IsEnglishSystem
      ? 'register agreement'
      : '注册协议',
    // navigationBarTitleText: '注册协议',  // 有效
  }
```

```

### 期望行为
期望实现国际化功能，‘IsEnglishSystem’默认为false，就是为英文标题'register agreement'，否则为中文标题 '注册协议'！

### 报错信息
控制台报错

### 系统信息
```
  Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/mobx: 1.3.25 => 1.3.25 
      @tarojs/mobx-h5: 1.3.25 => 1.3.25 
      @tarojs/mobx-rn: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: 1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-less: 1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/rn-runner: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: 1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.5 
      nervjs: ^1.5.5 => 1.5.5 
      stylelint-config-taro-rn: 1.3.25 => 1.3.25 
      stylelint-taro-rn: 1.3.25 => 1.3.25 
```

**Comment by EdisonVan** [comment]
已通过setNavigationBarTitle解决了😂
    globalData.IsEnglishSystem
      ? Taro.setNavigationBarTitle({ title: 'register agreement' })
      : Taro.setNavigationBarTitle({ title: '注册协议' })

**Comment by wangchao3** [comment]
setNavigationBarTitle不是有抖动吗
