### ISSUE TITLE
taro update project无法将依赖更新到与cli beta版本一致

### ISSUE THREAD

**Issue by xiaoxintang** [NervJS/taro#5268]
### 问题描述
使用cli版本是`2.0.0-beta.13`运行报错`cli版本与依赖版本不一致`，提示我可以`taro update project`更新项目依赖，更新之后，依赖是与当前最新稳定版的版本一致的，与cli beta版本并不一致，所以继续报错版本不一致

### 期望行为

`taro update project`可以将依赖更新到与当前cli版本一致

### 报错信息

![image](https://user-images.githubusercontent.com/24927686/71947286-680c0700-3207-11ea-9478-1d23fbd437c8.png)

### 系统信息
![image](https://user-images.githubusercontent.com/24927686/71947242-4448c100-3207-11ea-91af-43f0300a29bc.png)

**Comment by luckyadam** [comment]
taro update project 2.0.0-beta.13
