### ISSUE TITLE
2.0beta14的request有问题，无法执行回调

### ISSUE THREAD

**Issue by cuikangyi** [NervJS/taro#5271]
### 问题描述
2.0beta14的request有问题，无法执行回调

### 复现步骤

```js
Taro.request({
    url: '',
}).then(resp => {
    console.log(resp)
}).catch(res => {
    console.log(res)
})
```

### 期望行为
应该能正常运行，切换回beta13是可以的

### 报错信息
请求可以正常发出，但是三个回调没有执行

### 系统信息

Taro CLI 2.0.0-beta.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.0 - D:\Programs\scoop\apps\nodejs-lts\current\node.EXE
      Yarn: 1.21.1 - D:\Programs\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.13.0 - D:\Programs\scoop\apps\nodejs-lts\current\bin\npm.CMD

**Comment by georgezouq** [comment]
@Chen-jj  2.0.0版本，一样的问题 下个版本能修复吗？
