### ISSUE TITLE
swiper组件在H5点击事件失效

### ISSUE THREAD

**Issue by Anjing1993** [NervJS/taro#5279]
### 问题描述
我们的业务用了轮播组件，并开启自动轮播，给每一项轮播绑定了一个点击事件，但是第一个轮播的事件会出现未触发的情况：
![image](https://user-images.githubusercontent.com/9416309/72048947-e5637480-32f8-11ea-99f2-4732c1415fdf.png)

### 复现步骤

示例demo：https://github.com/Anjing1993/myTestCode/blob/master/testprops1.zip

### 期望行为

期望事件触发正常

### 报错信息

无报错

### 系统信息

Taro CLI 1.3.33 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.3.3333

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@Anjing1993 复现不了，依赖和 CLI 版本保持一致。

**Comment by Anjing1993** [comment]
https://github.com/Anjing1993/myTestCode/blob/master/testprops2.zip @Chen-jj 辛苦看下这个demo
1.依赖和cli版本都是一样的，1.3.33
2.demo里面是3张轮播，每张点击都会console出当前是第几张
3.第一张的click一直无法触发
![image](https://user-images.githubusercontent.com/9416309/72306568-8b74fd00-36b2-11ea-89a2-b4cddf6f20be.png)

**Comment by Chen-jj** [comment]
@Anjing1993 复现不了，升级到最新版再试试

![image](https://user-images.githubusercontent.com/11807297/72306795-54ebb200-36b3-11ea-92bb-51274ef10861.png)

**Comment by Anjing1993** [comment]
@Chen-jj 不好意思，描述遗漏了，是在h5里面

**Comment by Anjing1993** [comment]
@Chen-jj 不好意思...写错了，是在H5里面

**Comment by nearzeno** [comment]
遇到过这个问题，好像是有些swiper item点击事件没有监听到，如果设置了循环，第一张的前一张（不是倒数第一张，这一张显示的是倒数第一张，实际上却不是倒数第一张），点击事件是没有用的，我是单独给它设置了监听事件，解决的这个问题

**Comment by DonaldDai** [comment]
> 遇到过这个问题，好像是有些swiper item点击事件没有监听到，如果设置了循环，第一张的前一张（不是倒数第一张，这一张显示的是倒数第一张，实际上却不是倒数第一张），点击事件是没有用的，我是单独给它设置了监听事件，解决的这个问题

如何单独设置？

**Comment by nearzeno** [comment]
> > 遇到过这个问题，好像是有些swiper item点击事件没有监听到，如果设置了循环，第一张的前一张（不是倒数第一张，这一张显示的是倒数第一张，实际上却不是倒数第一张），点击事件是没有用的，我是单独给它设置了监听事件，解决的这个问题
> 
> 如何单独设置？

我记得我当时是用的addeventlistener去单独监听它的点击事件
