### ISSUE TITLE
H5端 canvas的使用异常[低版本]

### ISSUE THREAD

**Issue by oyv1cent** [NervJS/taro#5281]
### 问题描述

以下情况基于taro 1.2.21

1. 使用createCanvasContext API 会报错：暂时不支持 API createCanvasContext
2. 不支持Taro/component Canvas，只可用原生canvas标签
3. 使用原生canvas标签的情况下，概率性可绘制出（大概率绘制空白，无法绘制，无报错情况，有时候在代码中加console.log(1)，就小概率可绘制出，然而刷新后大概率继续空白，这个问题比较奇怪），然而原生的canvas即使绘制出，调用canvas的toDataURL方法无效，无报错，但canvas.toDataURL打印出空值，原生的将会打印出一串base64

### 复现步骤
 代码：
```js
 const sharePoster = document.getElementById('share-poster')
 const ctx = sharePoster.getContext('2d')
/* 下面为API 报错代码*/
 // const ctx = Taro.createCanvasContext('share-poster', this)

<canvas style="width: 300px; height: 200px;" id="share-poster" />
```

### 期望行为

希望了解1.2.21版本Taro的H5如何绘制canvas，并且可将canvas导为base64/图片...

### 报错信息

![image](https://user-images.githubusercontent.com/15560099/72056292-4e51e900-3307-11ea-9d86-754a83794be7.png)
### 系统信息

		"@tarojs/components": "1.2.21",
		"@tarojs/redux": "1.2.21",
		"@tarojs/redux-h5": "1.2.21",
		"@tarojs/router": "1.2.21",
		"@tarojs/taro": "1.2.21",
		"@tarojs/taro-h5": "1.2.21",
		"@tarojs/taro-weapp": "1.2.21",
		"nerv-devtools": "^1.3.5",
		"nervjs": "1.3.13",
		"nerv-server": "^1.3.2",
		"@tarojs/cli": "1.2.21",

### 其他

![image](https://user-images.githubusercontent.com/15560099/72056663-fc5d9300-3307-11ea-9c54-0a16180ae6c8.png)

搜索后， Taro版本会从1.3.14跳为最新版...无法继续保持当前版本，搜的内容也可能不适用于1.3.14~

**Comment by ZakaryCode** [comment]
对应版本不支持 createCanvasContext API 所以才会报错，同理在文档中也是一样的，搜索查到的是新版本文档内的 API。

> 如果需要使用对应的接口，建议可以考虑升级到最新版本
