### ISSUE TITLE
[taro-2.0.0]升级2.0后，部分页面样式失效

### ISSUE THREAD

**Issue by Tom9402** [NervJS/taro#5282]
## 问题描述

Taro 升级2.0后，部分页面样式失效
![image](https://user-images.githubusercontent.com/17630802/72061584-25365600-3311-11ea-80eb-521d42e88357.png)

### 复现步骤

1. 登录小程序
2. 点击“数据库”
3. 进入“订单”列表即可看到样式不起作用的情况

### 期望行为

样式恢复正常作用

### 报错信息

![image](https://user-images.githubusercontent.com/17630802/72144841-3005ef00-33d4-11ea-9968-b3c5fc425f54.png)

### 系统信息

![image](https://user-images.githubusercontent.com/17630802/72061686-59117b80-3311-11ea-966f-ff030cea6051.png)

**Comment by Tom9402** [comment]
具体项目代码可联系本人，麻烦了！🙏🙏🙏

**Comment by aiiua** [comment]
这个我也遇到了，我`重命名`了`样式文件`，然后就可以编译了，具体原因未知，暂时解决了问题

**Comment by luckyadam** [comment]
应该是公共样式都被编译到了 `vendors.wxss` 里了，`vendors.wxss` 会被 `app.wxss` 引用，但是组件默认不受 `app.wxss 影响，解决办法可以是，给组件添加 `addGlobalClass` 配置，https://nervjs.github.io/taro/docs/component-style.html#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%E7%B1%BB

**Comment by Tom9402** [comment]
> 应该是公共样式都被编译到了 `vendors.wxss` 里了，`vendors.wxss` 会被 `app.wxss` 引用，但是组件默认不受 `app.wxss 影响，解决办法可以是，给组件添加 `addGlobalClass` 配置，https://nervjs.github.io/taro/docs/component-style.html#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%E7%B1%BB

确实如此，问题已解决。
