### ISSUE TITLE
[taro 2.0.0]MAC taro创建失败 

### ISSUE THREAD

**Issue by kerncheng** [NervJS/taro#5285]
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new
```
✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ demo
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 默认模板

SyntaxError: Error parsing /usr/local/lib/node_modules/@tarojs/cli/templates/default/package.json: Unexpected token < in JSON at position 183
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:255:20)
    at readPackageScope (internal/modules/cjs/loader.js:280:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:17)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/dist/create/init.js:147:54)
    at Generator.next (<anonymous>) {
  path: '/usr/local/lib/node_modules/@tarojs/cli/templates/default/package.json'
}
➜  ReactProjects
```

**Comment by Garfield550** [comment]
Taro 版本？

**Comment by kerncheng** [comment]
> Taro 版本？

👽 Taro v2.0.0


  Taro CLI 2.0.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.6.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm

**Comment by damaohub** [comment]
是不是用less需要额外配置呢，我用less也是出问题。
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/less-loader/dist/cjs.js):

**Comment by wq1308786830** [comment]
+1

**Comment by damaohub** [comment]
> 是不是用less需要额外配置呢，我用less也是出问题。
> Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/less-loader/dist/cjs.js):

回来说一下，发现这个是因为less里的each方法解析不了。

**Comment by wq1308786830** [comment]
> > 是不是用less需要额外配置呢，我用less也是出问题。
> > Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/less-loader/dist/cjs.js):
> 
> 回来说一下，发现这个是因为less里的each方法解析不了。建议把taro-webpack-runner里的less版本升级。

不是的，我其他几个模板使用都一样的问题

**Comment by kerncheng** [comment]
我的不是less问题，应该是跟我node版本太高有关系, 替换模板出问题了，我降级了node v12

Taro CLI 2.0.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm

**Comment by Garfield550** [comment]
之前出现过这种问题，这两天看一下。

问一下是 Node 哪个版本。

**Comment by kerncheng** [comment]
> 之前出现过这种问题，这两天看一下。
> 
> 问一下是 Node 哪个版本。

 node v13.6 有问题 ，出现了这个问题

**Comment by Garfield550** [comment]
了解了

**Comment by Garfield550** [comment]
Node.js 13 又改了 `require` 的行为，之前是 `require` 同目录下的 js 文件时，`package.json` 有 `main` 字段会出错，现在的行为成了，只要有一个不合规范的 `package.json` 就会报错。

![image](https://user-images.githubusercontent.com/3471836/72202596-673fd300-349c-11ea-8bfc-b98886b9b69d.png)

@luckyadam 我觉得我们需要考虑一套新的模版机制，你觉得呢

**Comment by luckyadam** [comment]
> Node.js 13 又改了 `require` 的行为，之前是 `require` 同目录下的 js 文件时，`package.json` 有 `main` 字段会出错，现在的行为成了，只要有一个不合规范的 `package.json` 就会报错。
> 
> ![image](https://user-images.githubusercontent.com/3471836/72202596-673fd300-349c-11ea-8bfc-b98886b9b69d.png)
> 
> @luckyadam 我觉得我们需要考虑一套新的模版机制，你觉得呢

这样子，那还挺蛋疼的，看来模板机制确实得换了，有啥建议不~

**Comment by kamicloud** [comment]
+1 

Happened on node13 and taro 2.0.1
