### ISSUE TITLE
微信小程序如何隐藏掉左侧的小房子按钮

### ISSUE THREAD

**Issue by littlepurple** [NervJS/taro#5288]
### 复现步骤

1.不是首页的页面不想让其有左侧的小房子
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by david2tdw** [comment]
不要使用redirctTo()去跳转页面

**Comment by littlepurple** [comment]
> 用其他的去跳转是有那个返回的按钮呀

**Comment by Garfield550** [comment]
这篇文章是否对你有帮助？https://developers.weixin.qq.com/community/develop/doc/000cc0dad902207bae390c9665bc00

![image](https://user-images.githubusercontent.com/3471836/72141464-e0bcc000-33cd-11ea-9e2b-f16d4300a62a.png)
