### ISSUE TITLE
[taro-2.0.0]mobx store中和state有相同属性的时候state中数据会覆盖store中的

### ISSUE THREAD

**Issue by yuwanlin** [NervJS/taro#5290]
### 问题描述

使用mobx构建taro程序，当mobx中和store中有相同属性的时候，开始的时候它们可以正常工作。然而，从当前页面 navagateTo 其他页面，再从其他页面 navagateTo 当前页面的时候，页面上显示的值将会异常。

### 复现步骤
我创建了一个仓库用于演示。https://github.com/yuwanlin/taro-mobx-bug
1. 进入首页
2. 点击 加 按钮，此时 `store中count` 和 `本地count` 的值都是1
3. 点击 `点击跳转到其他页面` 文字，会跳转到其他页面
4. 在其他页面点击 `这是 otherPage，点击返回首页` 返回到首页
4. 点击 加 按钮，此时 `store中count` 和 `本地count` 的值都是0，**但是控制台中打印的store中的count值是1，页面中显示0。**
5. 再点击 加 按钮，此时 `store中count` 和 `本地count` 的值都是1，**但是控制台中打印的store中的count值是2。**

----------------------
当store中属性名和state属性名不一样的时候，可以正常工作。

### 期望行为

1. 期望store中属性和state属性一样的时候，可以正常工作。
2. 我注意到，当我从其他页面返回到首页的时候，再点击 加 按钮，每点击一次，首页组件都会触发render两次。期望可以只render一次。我使用react-route3 + mobx可以只render一次。

### 系统信息

�🙅 Taro v2.0.0

  Taro CLI 2.0.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD

### 补充信息
1. 第一个问题比较关键。如果需要提供更多信息，可以在taro群交流。

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。
