### ISSUE TITLE
Taro.request最大并发数是5，而wx.request支持最大并发数是10

### ISSUE THREAD

**Issue by maoyifanDev** [NervJS/taro#5291]
### 问题描述

Taro.request最大并发数是5，而微信小程序支持最大并发数是10

https://github.com/NervJS/taro/blob/a5f57c860600ca5ead3dde499350666326924ae9/packages/taro-weapp/src/native-api.js#L11

![image](https://user-images.githubusercontent.com/47847170/72135838-56bb2a00-33c2-11ea-870f-80f70ecce5b7.png)

请问这个有什么原因么，是否能支持设置并发数

**Comment by luckyadam** [comment]
来个 pr 就好
