### ISSUE TITLE
Taro v2.0.0 useScope  返回undefined 

### ISSUE THREAD

**Issue by guider** [NervJS/taro#5292]
### 问题描述
taro v2.0.0 

### 复现步骤
taro hook 

console.log(useScope) .   undefined

**Comment by luckyadam** [comment]
H5 没有这个 Hook，贴一下代码看看你的具体使用

**Comment by kamicloud** [comment]
@luckyadam 
taro 2.0.1
````
import { ComponentClass } from 'react'
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Audio } from '@tarojs/components'
import { connect, useDispatch } from '@tarojs/redux'
import { AtSearchBar, AtDivider, AtAccordion } from 'taro-ui'

import { initBgmMapping, initItemMapping } from '../../actions/cfg'

const dispatch = useDispatch();

````
./.temp/pages/wiki/title.js 20:15-26
" '@tarojs/redux-h5' does not contain an export named 'useDispatch'.

./.temp/pages/wiki/simulator.js 23:15-26
" '@tarojs/redux-h5' does not contain an export named 'useDispatch'.

./.temp/pages/wiki/character.js 23:15-26
" '@tarojs/redux-h5' does not contain an export named 'useDispatch'.
