### ISSUE TITLE
h5按教程到这就报错了 什么原因啊

### ISSUE THREAD

**Issue by QTTQ** [NervJS/taro#53]
![image](https://user-images.githubusercontent.com/22019544/41194883-648f191a-6c55-11e8-96c2-3afd0b9e2681.png)

**Comment by loo41** [comment]
你新建项目的时候等依赖安装完了吗？

**Comment by QTTQ** [comment]
我就按步骤来的啊  先  taro init myapp 然后  npm run dev ：h5   但就有问题了 这是taro init myapp的截图 这里就有问题了
![image](https://user-images.githubusercontent.com/22019544/41197877-85c7256c-6c9d-11e8-915a-714255fe8293.png)

**Comment by wowlusitong** [comment]
init的时候依赖安装失败了, 进到项目里面手动安装下，如果还安装不上的话可以试试清npm缓存、换源、挂代理等方式

**Comment by loo41** [comment]
npm cache clean --force 试试

**Comment by QTTQ** [comment]
哦哦  谢谢  清除缓存就好了
