### ISSUE TITLE
Error: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by goingta** [NervJS/taro#530]
**问题描述**
H5 编译预览npm run dev:h5 报错 Error: Couldn't find preset "es2015"，微信小程序编译预览正常

**解决步骤**
1. 尝试过安装npm install babel-preset-es2015 --save
2. 尝试过修改config/index.js 中 presets: ["env"] 改为 presets: ["env", "es2015"]
3. 尝试过在根目录下添加.babelrc文件 内容
{
  "presets": ["es2015"]
}

package.json
{
  "name": "taroDemo",
  "version": "1.0.0",
  "private": true,
  "description": "taroDemo",
  "main": "index.js",
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:h5": "taro build --type h5",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@tarojs/components": "^1.0.0-beta.17",
    "@tarojs/router": "^1.0.0-beta.17",
    "@tarojs/taro": "^1.0.0-beta.17",
    "@tarojs/taro-h5": "^1.0.0-beta.17",
    "@tarojs/taro-weapp": "^1.0.0-beta.17",
    "babel-preset-es2015": "^6.24.1",
    "nervjs": "^1.3.0"
  },
  "devDependencies": {
    "@types/react": "16.3.14",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/cli": "^1.0.0-beta.17",
    "@tarojs/plugin-babel": "^1.0.0-beta.17",
    "@tarojs/plugin-csso": "^1.0.0-beta.17",
    "@tarojs/plugin-uglifyjs": "^1.0.0-beta.17",
    "@tarojs/webpack-runner": "^1.0.0-beta.17",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^1.0.0-beta.17",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "^1.0.0-beta.17"
  }
}

**期望行为**
正常编译通过

**报错信息**

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "es2015" relative to directory "/Users/goingta/Documents/Work"
    at Array.map (<anonymous>)

**系统信息**

 - 操作系统: [e.g. Mac OS 10.14 Beta (18A371a)]
 - Taro 版本 [e.g. v1.0.0-beta.17]
 - Node.js 版本 [e.g. v10.0.0]

**补充信息**
怀疑过babel本身问题，但是这个是第三方依赖，所以不确定

**Comment by luckyadam** [comment]
恩~ 我们看下这个问题~

**Comment by goingta** [comment]
查到原因了，我工程的上上级目录，有一个.babelrc配置文件，里面写了用es2015，把这个文件删了就可以了。 @luckyadam

**Comment by luckyadam** [comment]
OK~

**Comment by zhouxinkai** [comment]
@luckyadam 我也遇到这个问题了，怎么解决啊
