### ISSUE TITLE
[taro-2.0.0]CoverImage 在编译后在微信小程序真机上不显示图片

### ISSUE THREAD

**Issue by Niubility-SunLight** [NervJS/taro#5301]
### 问题描述

CoverImage组件，在小程序上通过Import方式引入转为Base64后，在开发工具上显示图片，在真机上不显示。

### 复现步骤
```js
import clearInputIco from "../../images/clear-input-ico.png"


  render() {
        return (
            <View className='Index'>
              <Textarea value=''/>
              <CoverImage className='clear-ico' src={clearInputIco} />
            </View>
        )
    }


```
此处为开发工具上显示
![image](https://user-images.githubusercontent.com/38355384/72220067-f37af480-3587-11ea-9398-76db45e7c228.png)

此处为真机调试显示
![image](https://user-images.githubusercontent.com/38355384/72220117-671d0180-3588-11ea-90b5-bce50195bdaf.png)
为了防止是因为原生Textarea覆盖图片，所以特意取消了CSS，但是仍然没有图片。
![image](https://user-images.githubusercontent.com/38355384/72220100-4a80c980-3588-11ea-99d4-aa5f5e24fc82.png)

### 期望行为

引入静态资源，编译时仍会自动放到dist下，保持相对路径不变，方便引入。或者解决CoverImage显示Base64问题

### 系统信息

D:\WebDemos\supply-manage>taro info
�👽 Taro v2.0.0

  Taro CLI 2.0.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息
```
// config/index.js
const config = {
  mini: {
    imageUrlLoaderOption: {
      limit: 500 // 默认值，可以按需调小
    }
  }
}
```
更改limit 为 300 500 800 真机仍未显示图片 

![image](https://user-images.githubusercontent.com/38355384/72220221-80727d80-3589-11ea-9d31-779d26eaa27c.png)

微信小程序CoverImage对于Base64的支持不足。

**Comment by luckyadam** [comment]
可以配置一下 `mini.imageUrlLoaderOption` 配置，把 `limit` 调小些

```js
// config/index.js
const config = {
  mini: {
    imageUrlLoaderOption: {
      limit: 10240 // 默认值，可以按需调小
    }
  }
}
```

**Comment by Niubility-SunLight** [comment]
更改了，imageUrlLoaderOption，把limit调为300 400 500 600仍旧在真机上显示不来图片

**Comment by Niubility-SunLight** [comment]
> 可以配置一下 `mini.imageUrlLoaderOption` 配置，把 `limit` 调小些
> 
> ```js
> // config/index.js
> const config = {
>   mini: {
>     imageUrlLoaderOption: {
>       limit: 10240 // 默认值，可以按需调小
>     }
>   }
> }
> ```

更改imageUrlLoaderOption，把limit调为300 400 500 600仍旧在真机上显示不来图片

**Comment by luckyadam** [comment]
> > 可以配置一下 `mini.imageUrlLoaderOption` 配置，把 `limit` 调小些
> > ```js
> > // config/index.js
> > const config = {
> >   mini: {
> >     imageUrlLoaderOption: {
> >       limit: 10240 // 默认值，可以按需调小
> >     }
> >   }
> > }
> > ```
> 
> 更改imageUrlLoaderOption，把limit调为300 400 500 600仍旧在真机上显示不来图片

麻烦提供一下你的配置

**Comment by Niubility-SunLight** [comment]
> > > 可以配置一下 `mini.imageUrlLoaderOption` 配置，把 `limit` 调小些
> > > ```js
> > > // config/index.js
> > > const config = {
> > >   mini: {
> > >     imageUrlLoaderOption: {
> > >       limit: 10240 // 默认值，可以按需调小
> > >     }
> > >   }
> > > }
> > > ```
> > 
> > 
> > 更改imageUrlLoaderOption，把limit调为300 400 500 600仍旧在真机上显示不来图片
> 
> 麻烦提供一下你的配置
```
/config/index.js
const config = {
  projectName: 'supply-manage',
  date: '2020-1-10',
  designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2
  },
  sourceRoot: 'src',
  outputRoot: 'dist',
  babel: {
    sourceMap: true,
    presets: [
      ['env', {
        modules: false
      }]
    ],
    plugins: [
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-object-rest-spread'
    ]
  },
  plugins: [],
  defineConstants: {
  },
  mini: {
    postcss: {
      pxtransform: {
        enable: true,
        config: {}
      },
      url: {
        enable: true,
        config: {
          limit: 500 // 设定转换尺寸上限
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    }
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    postcss: {
      autoprefixer: {
        enable: true,
        config: {
          browsers: [
            'last 3 versions',
            'Android >= 4.1',
            'ios >= 8'
          ]
        }
      },
      cssModules: {
        enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
    }
  }
}

module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}

```

**Comment by luckyadam** [comment]
> imageUrlLoaderOption

imageUrlLoaderOption 配在哪儿

**Comment by luckyadam** [comment]
> > > > 可以配置一下 `mini.imageUrlLoaderOption` 配置，把 `limit` 调小些
> > > > ```js
> > > > // config/index.js
> > > > const config = {
> > > >   mini: {
> > > >     imageUrlLoaderOption: {
> > > >       limit: 10240 // 默认值，可以按需调小
> > > >     }
> > > >   }
> > > > }
> > > > ```
> > > 
> > > 
> > > 更改imageUrlLoaderOption，把limit调为300 400 500 600仍旧在真机上显示不来图片
> > 
> > 
> > 麻烦提供一下你的配置
> 
> ```
> /config/index.js
> const config = {
>   projectName: 'supply-manage',
>   date: '2020-1-10',
>   designWidth: 750,
>   deviceRatio: {
>     '640': 2.34 / 2,
>     '750': 1,
>     '828': 1.81 / 2
>   },
>   sourceRoot: 'src',
>   outputRoot: 'dist',
>   babel: {
>     sourceMap: true,
>     presets: [
>       ['env', {
>         modules: false
>       }]
>     ],
>     plugins: [
>       'transform-decorators-legacy',
>       'transform-class-properties',
>       'transform-object-rest-spread'
>     ]
>   },
>   plugins: [],
>   defineConstants: {
>   },
>   mini: {
>     postcss: {
>       pxtransform: {
>         enable: true,
>         config: {}
>       },
>       url: {
>         enable: true,
>         config: {
>           limit: 500 // 设定转换尺寸上限
>         }
>       },
>       cssModules: {
>         enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
>         config: {
>           namingPattern: 'module', // 转换模式，取值为 global/module
>           generateScopedName: '[name]__[local]___[hash:base64:5]'
>         }
>       }
>     }
>   },
>   h5: {
>     publicPath: '/',
>     staticDirectory: 'static',
>     postcss: {
>       autoprefixer: {
>         enable: true,
>         config: {
>           browsers: [
>             'last 3 versions',
>             'Android >= 4.1',
>             'ios >= 8'
>           ]
>         }
>       },
>       cssModules: {
>         enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
>         config: {
>           namingPattern: 'module', // 转换模式，取值为 global/module
>           generateScopedName: '[name]__[local]___[hash:base64:5]'
>         }
>       }
>     }
>   }
> }
> 
> module.exports = function (merge) {
>   if (process.env.NODE_ENV === 'development') {
>     return merge({}, config, require('./dev'))
>   }
>   return merge({}, config, require('./prod'))
> }
> ```

imageUrlLoaderOption 配在哪儿

**Comment by Niubility-SunLight** [comment]
> > > > > 可以配置一下 `mini.imageUrlLoaderOption` 配置，把 `limit` 调小些
> > > > > ```js
> > > > > // config/index.js
> > > > > const config = {
> > > > >   mini: {
> > > > >     imageUrlLoaderOption: {
> > > > >       limit: 10240 // 默认值，可以按需调小
> > > > >     }
> > > > >   }
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > 更改imageUrlLoaderOption，把limit调为300 400 500 600仍旧在真机上显示不来图片
> > > 
> > > 
> > > 麻烦提供一下你的配置
> > 
> > 
> > ```
> > /config/index.js
> > const config = {
> >   projectName: 'supply-manage',
> >   date: '2020-1-10',
> >   designWidth: 750,
> >   deviceRatio: {
> >     '640': 2.34 / 2,
> >     '750': 1,
> >     '828': 1.81 / 2
> >   },
> >   sourceRoot: 'src',
> >   outputRoot: 'dist',
> >   babel: {
> >     sourceMap: true,
> >     presets: [
> >       ['env', {
> >         modules: false
> >       }]
> >     ],
> >     plugins: [
> >       'transform-decorators-legacy',
> >       'transform-class-properties',
> >       'transform-object-rest-spread'
> >     ]
> >   },
> >   plugins: [],
> >   defineConstants: {
> >   },
> >   mini: {
> >     postcss: {
> >       pxtransform: {
> >         enable: true,
> >         config: {}
> >       },
> >       url: {
> >         enable: true,
> >         config: {
> >           limit: 500 // 设定转换尺寸上限
> >         }
> >       },
> >       cssModules: {
> >         enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
> >         config: {
> >           namingPattern: 'module', // 转换模式，取值为 global/module
> >           generateScopedName: '[name]__[local]___[hash:base64:5]'
> >         }
> >       }
> >     }
> >   },
> >   h5: {
> >     publicPath: '/',
> >     staticDirectory: 'static',
> >     postcss: {
> >       autoprefixer: {
> >         enable: true,
> >         config: {
> >           browsers: [
> >             'last 3 versions',
> >             'Android >= 4.1',
> >             'ios >= 8'
> >           ]
> >         }
> >       },
> >       cssModules: {
> >         enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
> >         config: {
> >           namingPattern: 'module', // 转换模式，取值为 global/module
> >           generateScopedName: '[name]__[local]___[hash:base64:5]'
> >         }
> >       }
> >     }
> >   }
> > }
> > 
> > module.exports = function (merge) {
> >   if (process.env.NODE_ENV === 'development') {
> >     return merge({}, config, require('./dev'))
> >   }
> >   return merge({}, config, require('./prod'))
> > }
> > ```
> 
> imageUrlLoaderOption 配在哪儿

发现问题，错吧postcss:{limit:1024}看成imageUrlLoaderOption 内的limit。
imageUrlLoaderOption.limit改为800可以正常显示图片
