### ISSUE TITLE
[taro-2.0.0]taro init后安装eslint-plugin-jsx-a11y后运行报错

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#5304]
### 问题描述

安装 `eslint-plugin-jsx-a11y` 后运行报错，运行报错

### 复现步骤

1. taro init taro-demo
2. cd taro-demo
3. yarn add eslint-plugin-jsx-a11y -D
4. yarn run dev:weapp
5. 控制台报错且应用无法运行

### 期望行为

能够搭配使用eslint-plugin-jsx-a11y

### 报错信息

```bash
Uncaught TypeError: Function(...) is not a function
```

### 系统信息

```bash
Taro CLI 2.0.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\vdfor\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
```

### 补充信息
`eslint-plugin-jsx-a11y` 依赖 `@babel/runtime`, 猜测与 `babel-runtime` 冲突

**Comment by luckyadam** [comment]
是的，正如你所说，`@babel/runtime` 与 `babel-runtime` 冲突了，而 `@babel/runtime` 貌似在小程序环境下使用存在问题

**Comment by sherfruit** [comment]
有好的方案解决吗？
