### ISSUE TITLE
文档里写的rn具有hoverStyle怎么rn官方文档没说？搜了半天没找到

### ISSUE THREAD

**Issue by zjw666** [NervJS/taro#5306]

**Comment by Garfield550** [comment]
麻烦补充更多的问题描述可以吗？

**Comment by zjw666** [comment]
taro 文档里说view组件在rn里面 有个hoverStyle属性，但是我设置了并没有作用，且rn文档里面也没有找到这个属性，这个属性真的存在吗

**Comment by Pines-Cheng** [comment]
文档哪里有提到？

**Comment by Garfield550** [comment]
Button 和 View 里提到了一个 `hoverStyle`。

> 支持 hoverStyle 属性，但框架未支持 hoverClass

https://taro-docs.jd.com/taro/docs/components/viewContainer/view.html

https://taro-docs.jd.com/taro/docs/components/forms/button.html

**Comment by zjw666** [comment]
> Button 和 View 里提到了一个 `hoverStyle`。
> 
> > 支持 hoverStyle 属性，但框架未支持 hoverClass
> 
> https://taro-docs.jd.com/taro/docs/components/viewContainer/view.html
> 
> https://taro-docs.jd.com/taro/docs/components/forms/button.html

是的，但是RN文档并没有这样的属性，写上了也并没有生效，建议还是多完善下文档吧

**Comment by Pines-Cheng** [comment]
这里是文档表述有问题，因为 rn 没有 class 的支持，所以目前 RN 端的 View 组件实现了 `hoverStyle `，写法和 style 类似，只不过 `hoverStyle ` 的样式是指定按下去的样式。

我来把文档修正一下。
