### ISSUE TITLE
render props使用时，被eslint提示报错，而且编译也报错

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#5308]
### 问题描述

1.使用render props
2.eslint提示报错
<img width="527" alt="屏幕快照 2020-01-13 下午3 02 01" src="https://user-images.githubusercontent.com/23090498/72237518-b78e7080-3615-11ea-8b0b-ba1a156f6b8f.png">

3.编译也报错，而且提示是路径错误，但是路径明明是正确的
<img width="484" alt="屏幕快照 2020-01-13 下午2 45 13" src="https://user-images.githubusercontent.com/23090498/72237528-c117d880-3615-11ea-86a6-81311202df4f.png">

### 复现步骤
```js
写入代码
render() {
    return <View>{this.props.renderAudio(a, b)}</View>;
}

```

### 期望行为

1.eslint不要报错
2. render props能正常使用

### 系统信息

 Taro CLI 1.3.27 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.27 => 1.3.27 
      @tarojs/components: 1.3.27 => 1.3.27 
      @tarojs/plugin-babel: 1.3.27 => 1.3.27 
      @tarojs/plugin-csso: 1.3.27 => 1.3.27 
      @tarojs/plugin-sass: 1.3.27 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.27 => 1.3.27 
      @tarojs/redux: 1.3.27 => 1.3.27 
      @tarojs/redux-h5: 1.3.27 => 1.3.27 
      @tarojs/router: 1.3.27 => 1.3.27 
      @tarojs/taro: 1.3.27 => 1.3.27 
      @tarojs/taro-alipay: 1.3.27 => 1.3.27 
      @tarojs/taro-h5: 1.3.27 => 1.3.27 
      @tarojs/taro-swan: 1.3.27 => 1.3.27 
      @tarojs/taro-tt: 1.3.27 => 1.3.27 
      @tarojs/taro-weapp: 1.3.27 => 1.3.27 
      @tarojs/webpack-runner: 1.3.27 => 1.3.27 
      eslint-config-taro: 1.3.27 => 1.3.27 
      eslint-plugin-taro: 1.3.27 => 1.3.27 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.27 => 

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
