### ISSUE TITLE
第三方组件库打包问题

### ISSUE THREAD

**Issue by BUPTlhuanyu** [NervJS/taro#5311]
### 问题描述

第三方组件库打包结果dist下的h5代码自动注入了taro/router相关代码，导致组件库代码使得taro项目中的路由失效

### 复现步骤

1. 创建第三方组件库
2. 运行"build:component": "cross-env TARO_BUILD_TYPE=component taro build --ui"
3. 找到dist/h5/index.js
4. 发现自动注入了taro/router相关代码

```js
/**自动注入的taro/router相关代码
import Nerv from 'nervjs';
import { Router, createHistory, mountApis } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750
});

const _taroHistory = createHistory({
  mode: "hash",
  basename: "/",
  customRoutes: {},
  firstPagePath: "/"
});

mountApis({
  "basename": "/",
  "customRoutes": {}
}, _taroHistory);
 */


```

### 期望行为

不影响taro项目中的路由

### 报错信息

无报错信息，但是影响了taro项目中的路由

### 系统信息

👽 Taro v1.3.19

  Taro CLI 1.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

第三方组件构建demo：https://github.com/NervJS/taro-ui-sample

**Comment by luckyadam** [comment]
已解决
