### ISSUE TITLE
[taro v2.0.0-beta.13]Taro.request 方法在多平台上行为未统一

### ISSUE THREAD

**Issue by wyhaya** [NervJS/taro#5318]
### 问题描述

`Taro.request` 方法 `data` 参数在 `H5` 端 不支持 `object` 类型

该方法使用了 `fetch` 调用接口 ，在代码中 `Taro.request data ` 参数对应 `fetch body` 参数。

`fetch body` 参数不支持 `object`，所以会造成 请求参数错误。

参考: [MDN Using_Fetch](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch)

### 复现步骤

1. 
```js
Taro.request({
    // ...
    method: 'POST',
    data: {
        test: 0
    },
})
```

2. 
```bash
yarn dev:h5
```
3.
```bash
yarn dev:weapp
```

### 期望行为

为了跨平台一致性应该统一 `data` 参数 应当支持 `object`

### 报错信息

* h5 端 参数错误： `[object Object]`
* weapp 端 正常
* 其他未测试

### 系统信息

```
👽 Taro v2.0.0-beta.13

  Taro CLI 2.0.0-beta.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 13.1.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
```

### 补充信息

https://github.com/NervJS/taro/blob/3b50289796e2914223d7828e8d10644c414fd68e/packages/taro-h5/src/api/request/index.js#L53-L64

考虑使用 `JSON.stringify` 处理

**Comment by yuankui** [comment]
taro机器人有够粗暴的。。
看了几个issue，提交者以及把问题描述得很清楚了，但是还是一个机器人在哪里回复：
`欢迎提交 Issue~

如果你提交的是 bug 报告，请务必遵循 Issue 模板的规范`

然后过几天，这个issue就被关了。。真无语。。
