### ISSUE TITLE
微信小程序在ios手机端Input输入框内容不会更新

### ISSUE THREAD

**Issue by Mypika** [NervJS/taro#5321]
### 复现步骤

1. 打开小程序，此时输入框会自动获取焦点
![8a1e345d1268770c4632a68df68b2bb](https://user-images.githubusercontent.com/40252390/72316335-ca19b000-36d0-11ea-8a13-c996d320a4b3.jpg)
2. 此时将小程序切换至后台，
3. 点击微信进入小程序，
4. 此时输入框失去焦点，点击输入时，会出现以下情况
![d7b7795a0e205c35de9c3b82a499ef5](https://user-images.githubusercontent.com/40252390/72316441-1a910d80-36d1-11ea-8f5c-478551868954.jpg)

### 系统信息
�👽 Taro v1.3.14
  Taro CLI 1.3.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\YJ-DELLG3-01\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by shenghanqin** [comment]
@Mypika 请使用taro info来提供taro版本信息

**Comment by Chen-jj** [comment]
@Mypika 给个 demo 看看咯

**Comment by Mypika** [comment]
@Chen-jj 貌似目前小程序都有这个问题，按照上面的操作步骤都会出现这个输入框被覆盖的问题，在iPhoneX和iPhone6s都有这样的情况

**Comment by Garfield550** [comment]
原生小程序呢？

**Comment by Mypika** [comment]
是的，使用原生方法写的也会出现这个问题

**Comment by Garfield550** [comment]
那么这个问题需要微信这边解决了，不是 Taro 造成的问题了。

**Comment by Mypika** [comment]
好的

**Comment by Garfield550** [comment]
建议跟踪一下这个问题的进度，微信这边已经确认问题并修复中 [iOS input 组件在退到桌面回来时出现文字重叠](https://developers.weixin.qq.com/community/develop/doc/000008a3e04780e8217900bef56814?highLine=iOS%2520input)
