### ISSUE TITLE
[taro-2.0.0]期望微信小程序在watch下也能压缩代码

### ISSUE THREAD

**Issue by sillyhong** [NervJS/taro#5322]
### 问题描述

Taro2.0下执行以下命令，输出完整的 webpack 打包信息后，没有继续监听文件，直接退出进程
```
NODE_ENV=production taro build --type weapp --watch 
```
### 复现步骤

1.  执行 **NODE_ENV=production taro build --type weapp --watch** 
2. 编译成功，输出 **webpack** 打包信息 
3. 进程退出，没有进行文件监听 （**watch**无效）

注：**NODE_ENV=production taro build --type h5 --watch** 表现正常。既可以压缩，又可以进行文件监听

### 期望行为
1.  执行 NODE_ENV=production taro build --type weapp --watch 
2. 编译成功，输出webpack打包信息 
3. 文件正常监听
4. 修改文件
5. 再次打包

### 系统信息

```
  Taro CLI 2.0.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.0 => 2.0.0 
      @tarojs/components: 2.0.0 => 2.0.0 
      @tarojs/mini-runner: 2.0.0 => 2.0.0 
      @tarojs/plugin-babel: 2.0.0 => 2.0.0 
      @tarojs/plugin-csso: 2.0.0 => 2.0.0 
      @tarojs/plugin-sass: 2.0.0 => 2.0.0 
      @tarojs/plugin-uglifyjs: 2.0.0 => 2.0.0 
      @tarojs/redux: 2.0.0 => 2.0.0 
      @tarojs/redux-h5: 2.0.0 => 2.0.0 
      @tarojs/router: 2.0.0 => 2.0.0 
      @tarojs/taro: 2.0.0 => 2.0.0 
      @tarojs/taro-alipay: 2.0.0 => 2.0.0 
      @tarojs/taro-h5: 2.0.0 => 2.0.0 
      @tarojs/taro-swan: 2.0.0 => 2.0.0 
      @tarojs/taro-tt: 2.0.0 => 2.0.0 
      @tarojs/taro-weapp: 2.0.0 => 2.0.0 
      @tarojs/webpack-runner: 2.0.0 => 2.0.0 
      eslint-config-taro: 2.0.0 => 2.0.0 
      eslint-plugin-taro: 2.0.0 => 2.0.0 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.10.2 => 16.12.0 
    npmGlobalPackages:
      typescript: 3.7.2
```

### 补充信息

与问题相关的issue：
 [希望Watch时也能支持压缩 #1219](https://github.com/NervJS/taro/pull/1219)
[在开发时如何配置js文件压缩？#2470](https://github.com/NervJS/taro/issues/2071)

相关截图如下：
![image](https://user-images.githubusercontent.com/28669167/72320564-eb809900-36dc-11ea-895d-97d73d792812.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
不错。这样可以调试即将上线的代码。

**Comment by Garfield550** [comment]
在 `dev` 配置里配置 `uglify` 可以实现吗？

**Comment by raohong** [comment]
[勾选上传时自动压缩混淆代码]

**Comment by sillyhong** [comment]
> 勾选 **[上传时自动压缩混淆代码]**
最终目的不单纯是压缩代码，跟重要的是调试代码

**Comment by sillyhong** [comment]
> 在 `dev` 配置里配置 `uglify` 可以实现吗？

也有想过，但是成本会较高。其实只需要把webpack 的 mode 设置为 production就好了，不需要自己再配置 uglify
