### ISSUE TITLE
是否考虑支持 Redux Toolkit？

### ISSUE THREAD

**Issue by Losses** [NervJS/taro#5324]
在很多情况下直接使用 Redux 是一件很痛的事情，所以 redux 官方搞出了个 [Redux-toolkit](https://redux-toolkit.js.org/) 考虑到很多项目已经在使用 rtk 管理状态，如果想在多端复用代码的话需要确保各个平台对这个库都有支持。 不太清楚现在的 @taro/redux 和 官方的 redux 是不是百分之百兼容的，如果是完全兼容的话或许可以安全的提供 rtk 支持？

**Comment by dpyzo0o** [comment]
完美兼容，我前段时间自己搭了一下, 项目中也正在用, 没什么问题. https://github.com/dpyzo0o/taro-toolkit

**Comment by Losses** [comment]
@dpyzo0o 感谢告知，非常牛逼！
