### ISSUE TITLE
React Native环境下使用Taro.reLaunch跳转页面,页面跳转成功后不会触发componentDidShow

### ISSUE THREAD

**Issue by Fantasy9527** [NervJS/taro#5325]
### 问题描述

IOS端的React Native使用Taro.reLaunch跳转页面,
页面跳转成功后不会触发componentDidShow

ps. 安卓端正常

### 期望行为
Taro.reLaunch跳转页面后,可以正常触发componentDidShow

**Comment by shenghanqin** [comment]
taro什么版本呢？

**Comment by Pines-Cheng** [comment]
https://github.com/react-navigation/react-navigation/issues/4867#issuecomment-486708186
