### ISSUE TITLE
[taro-2.0.1]配置使用 alias 后编译不通过

### ISSUE THREAD

**Issue by theprimone** [NervJS/taro#5328]
### 复现步骤

配置

```js
{
  // ...
  defineConstants: {
  },
  alias: {
    '@/': path.resolve(__dirname, '..', 'src/'),
  },
  // ...
}
```

使用

```js
import api from '@/api'
```

### 期望行为

编译通过，模块正常引入

### 报错信息

```bash
Module not found: Can't resolve '@/api' in 'D:\workspaces\yunta\wx-e-pei-taroConvert\src\pages\index'
```

### 系统信息

Taro CLI 2.0.1 environment info:
  System:
    OS: Windows 10
  Binaries:
    Node: 10.16.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD

**Comment by Garfield550** [comment]
你有使用 TypeScript 吗？有的话可以在 `tsconfig.json` 里再配置一下试一试。

**Comment by theprimone** [comment]
@Garfield550 现在还是 js 文件，这是 jsconfig 配置：

```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Comment by luckyadam** [comment]
编译到小程序么

**Comment by theprimone** [comment]
对，不会不支持编译到小程序吧？

**Comment by luckyadam** [comment]
> 对，不会不支持编译到小程序吧？

支持

**Comment by theprimone** [comment]
那我这个配置也应该没毛病吧 \_(:3J∠)\_

**Comment by theprimone** [comment]
```
alias: {
  '@': path.resolve(__dirname, '..', 'src/'),
}
```

这样就可以了，还担心会转义 @tarojs 之类的引用呢 \_(:3J∠)\_

**Comment by 54853315** [comment]
我也遇到了这个问题，我是Taro v2.0.5，我运行的是H5。


```
# config/index.js
  defineConstants: {
  },
  alias: {
    '@components': path.resolve(__dirname, '..', 'src/components'),
    '@styles': path.resolve(__dirname, '..', 'src/styles'),
  },
```

然后在pages/index.jsx 中使用：

```
import { Loading } from '@components'
```

会提示错误：`Module not found: Can't resolve '../../components' in '/Users/mac/ALotCode/app/Food/.temp/pages/index'`

查看了下`.temp`下，正确的位置都有正确的文件。
还蛮奇怪的，因为不光components的alias不行，styles的alias也不行。
尝试了`@/styles` 这种，也不行。
