### ISSUE TITLE
video默认播放控件无法隐藏（在调用VideoContext.play方法播放的时候）

### ISSUE THREAD

**Issue by penghuwan** [NervJS/taro#5329]
### 问题描述

在使用Video组件的时候我试图通过controls= false隐藏播放控件，然后使用自定义的UI控件。但是当我使videoContext.play去播放的时候默认控件仍然会出现，请问应该如何处理呢？

### 复现步骤

1. 写入Video组件，controls设置为false，试图隐藏
2. 使用Taro.createVideoContext方法创建VideoContext
3. 调用VideoContext.play（）方法进行播放
4. 默认的播放控件仍然出现了。。。。难过

```js
// 失效
<Video
            className='video__content'
            onTimeUpdate={this.handleTimeUpdate}
            autoplay={false}
            controls={false}
          />
// 同样失效
 <Video
            className='video__content'
            onTimeUpdate={this.handleTimeUpdate}
            autoplay={false}
            controls={false}
            showPlayBtn={false}
            showProgress={false}
            showFullscreenBtn={false}
            showCenterPlayBtn={false}
            src='http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400'
            id='video'
          />

```

### 期望行为

希望默认的播放控件不要出现，永远隐藏

### 系统信息

Taro v1.3.27

  Taro CLI 1.3.27 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.27 => 1.3.27 
      @tarojs/components: 1.3.27 => 1.3.27 
      @tarojs/plugin-babel: 1.3.27 => 1.3.27 
      @tarojs/plugin-csso: 1.3.27 => 1.3.27 
      @tarojs/plugin-sass: 1.3.27 => 1.3.27 
      @tarojs/plugin-uglifyjs: 1.3.27 => 1.3.27 
      @tarojs/redux: 1.3.27 => 1.3.27 
      @tarojs/redux-h5: 1.3.27 => 1.3.27 
      @tarojs/router: 1.3.27 => 1.3.27 
      @tarojs/taro: 1.3.27 => 1.3.27 
      @tarojs/taro-alipay: 1.3.27 => 1.3.27 
      @tarojs/taro-h5: 1.3.27 => 1.3.27 
      @tarojs/taro-swan: 1.3.27 => 1.3.27 
      @tarojs/taro-tt: 1.3.27 => 1.3.27 
      @tarojs/taro-weapp: 1.3.27 => 1.3.27 
      @tarojs/webpack-runner: 1.3.27 => 1.3.27 
      eslint-config-taro: 1.3.27 => 1.3.27 
      eslint-plugin-taro: 1.3.27 => 1.3.27 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.27 => 1.3.27 
      stylelint-taro-rn: 1.3.27 => 1.3.27 
    npmGlobalPackages:
      typescript: 3.7.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
用原生小程序试验一下看看有没有这个问题？

**Comment by penghuwan** [comment]
> 用原生小程序试验一下看看有没有这个问题？

没有

**Comment by penghuwan** [comment]
问题已解决： 这是模拟器的问题，真机调试是正常的
