### ISSUE TITLE
[Feature Request]支持事件捕获

### ISSUE THREAD

**Issue by cjhgit** [NervJS/taro#533]
小程序有事件捕获的语法 capture-bind:tap="handler" ，react 对应的语法是 onClickCapture，希望 Taro 能尽快支持。

**Comment by xmsz** [comment]
@yuche 啥时候可以解决

**Comment by myl0204** [comment]
有这个需求。

**Comment by xmsz** [comment]
Any update？

**Comment by BoringDays** [comment]
不打算支持么？

**Comment by monyee** [comment]
不支持 最好说下原因或者替代方案？

**Comment by lilingling3** [comment]
目前有解决方案吗？

**Comment by zula1994** [comment]
目前有解决方案吗？

**Comment by xiaowu2333** [comment]
同问，目前有解决方案吗

**Comment by CourieLiu** [comment]
提供一个 Hack 方案，我自己项目在用。

将设置捕获事件的容器从 View 更换为 Button，然后将 Button 的原生样式清除，Button 不会将事件传递到内层。

在具体实践中，如果需要捕获的场景较多，可以抽象为组件的写法。

**Comment by lcl22hope** [comment]
目前有解决方案吗？官方现在有排期么？请问

**Comment by lisonge** [comment]
我图懒，直接盖了一层透明的view，这样就点不进去了
但是可否直接获取原生小程序dom来设置阻止捕获事件呢？

**Comment by ZakaryCode** [comment]
[文档](https://nervjs.github.io/taro-docs/docs/react-overall#%E4%BA%8B%E4%BB%B6)
