### ISSUE TITLE
项目版本有1.x升级到2.x之后报错

### ISSUE THREAD

**Issue by sprout-echo** [NervJS/taro#5330]
### 问题描述

项目想从 1.3.25 升级到 2.0.0 
修改版本后 执行 start weapp
![image](https://user-images.githubusercontent.com/17763943/72408132-dc612000-379c-11ea-83c2-215230c3e59a.png)
执行 start h5
![image](https://user-images.githubusercontent.com/17763943/72408180-06b2dd80-379d-11ea-9547-81b20b5960ec.png)

### 期望行为

希望给个版本升级的思路

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@sprout-echo 是升级成功了吧？我还准备再写一个升级技巧呢。

**Comment by sprout-echo** [comment]
@shenghanqin  h5没问题了，weapp编译完就直接结束进程了 我今天再看看是什么问题
