### ISSUE TITLE
[taro-2.0.1] 开启copy过滤js文件还是被复制

### ISSUE THREAD

**Issue by conkyliu** [NervJS/taro#5332]
### 问题描述
配置文件copy里开启了过滤，打包后还是有过滤文件

![image](https://user-images.githubusercontent.com/26617741/72414083-58af2f80-37ac-11ea-8dd9-d25fcd52fe05.png)

![image](https://user-images.githubusercontent.com/26617741/72414062-47feb980-37ac-11ea-8db4-184553da8656.png)

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

不打包过滤文件
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
我有一个问题，你的组件命名有驼峰的，有小写的，恨不一致呀？

**Comment by conkyliu** [comment]
> 我有一个问题，你的组件命名有驼峰的，有小写的，恨不一致呀？

随心所欲~
