### ISSUE TITLE
[taro-2.0.1]taro init 初始化项目失败，卡在拉取远程模板上

### ISSUE THREAD

**Issue by PresByter2015** [NervJS/taro#5333]
### 问题描述

taro v2.0.1 版本初始化项目失败，一直显示  正在从 github*** 拉取远程模板...
到现在整整持续了30分钟了，本电脑已墙。

### 复现步骤

1. npm install -g @tarojs/cli
2. taro init applet
3. 一直到现在还在运行

### 期望行为

希望告知 是cli原因 还是本地环境问题

### 报错信息

无报错 ，
就是一直处于
**正在从 github:NervJS/taro-project-templates#2.0 拉取远程模板...**

### 系统信息
 Taro CLI 2.0.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD

**Comment by PresByter2015** [comment]
一直保持如下的效果30分钟以上
![image.png](https://i.loli.net/2020/01/15/jZTz3JFLlMOyufP.png)

**Comment by Garfield550** [comment]
@PresByter2015 挂个代理吧...

**Comment by PresByter2015** [comment]
已经是代理了
而且 taro doctor 也不好使，跑了半个小时了
![image.png](https://i.loli.net/2020/01/15/pD4MYxXg2ZzdIth.png)

**Comment by Garfield550** [comment]
下载模版的话，Windows 下可能要给 Node.exe 走个代理。
`taro doctor` 好像是遇到了一个 ESLint 问题，然后 Node.js 进程意外退出了。

**Comment by PresByter2015** [comment]
所以咋解决？

**Comment by luckyadam** [comment]
可能需要翻个墙

**Comment by flxxyz** [comment]
模板库是放在github上的，国内的话可能会间歇性无法访问，考虑给windows设置有效的全局代理

![设置代理](https://user-images.githubusercontent.com/8678079/83029556-6089b500-a065-11ea-851f-20600a36e11f.png)

**Comment by wajipu** [comment]
![image](https://user-images.githubusercontent.com/101818388/224940041-6dc921f1-75d1-4f2f-9b26-1b6f24756900.png)
最新版本，根本下载不了搞了一天人都麻了

**Comment by wajipu** [comment]
![image](https://user-images.githubusercontent.com/101818388/224940525-d438ab96-4646-4b8a-b122-fae4d081eca3.png)
 v1.3.34版本不行

**Comment by ChickenTreasure** [comment]
![image](https://github.com/NervJS/taro/assets/87047444/c72eef66-3a06-4cd9-8ab9-5dd9778a5d27)
根本拉不下来，没有人维护的吗？

**Comment by wajipu** [comment]
感觉没人维护了
