### ISSUE TITLE
按照教程创建了微信小程序插件项目，导入开发者工具后，总是提示未找到入口 app.json 文件。

### ISSUE THREAD

**Issue by jzsjiale** [NervJS/taro#5338]
### 问题描述

按照官方教程创建了微信小程序插件项目，修改两处appid，并将插件根目录导入微信开发者工具后，总是提示“未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译”，这是怎么回事呢？
官方教程地址：https://taro-docs.jd.com/taro/docs/miniprogram-plugin.html

### 复现步骤
使用官方教程的步骤创建小程序插件项目
taro init ceshi
请输入项目介绍！ 测试
是否需要使用 TypeScript ？ Yes
请选择 CSS 预处理器（Sass/Less/Stylus） Sass
请选择模板 wxplugin

创建完成后，修改了 project.config.json 的 appid 字段和 src/app.tsx 的 prodiver 字段为同一 appid。

使用taro build --plugin weapp --watch命令进行编译；
编译完成后，按教程要求在微信开发者工具中添加 Taro 插件项目根目录，添加后微信开发者工具中报“未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。”的错误。其他没有做任何改动。

创建项目时，TypeScript选no，css预处理器选无，也是一样的情况，请问这是怎么回事呢？

### 期望行为

是操作问题，还是模板问题呢？如何才能不报这个错误呢？

### 报错信息

微信开发者工具中报“未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。”的错误。

### 系统信息

taro info
👽 Taro v2.0.0

  Taro CLI 2.0.0 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.0 => 2.0.0 
      @tarojs/components-qa: 2.0.0 => 2.0.0 
      @tarojs/mini-runner: 2.0.0 => 2.0.0 
      @tarojs/router: 2.0.0 => 2.0.0 
      @tarojs/taro: 2.0.0 => 2.0.0 
      @tarojs/taro-alipay: 2.0.0 => 2.0.0 
      @tarojs/taro-h5: 2.0.0 => 2.0.0 
      @tarojs/taro-qq: 2.0.0 => 2.0.0 
      @tarojs/taro-quickapp: 2.0.0 => 2.0.0 
      @tarojs/taro-swan: 2.0.0 => 2.0.0 
      @tarojs/taro-tt: 2.0.0 => 2.0.0 
      @tarojs/taro-weapp: 2.0.0 => 2.0.0 
      @tarojs/webpack-runner: 2.0.0 => 2.0.0 
      eslint-config-taro: 2.0.0 => 2.0.0 
      eslint-plugin-taro: 2.0.0 => 2.0.0 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/72491831-3ffb5400-3856-11ea-8929-c302a630a16c.png)

比对微信开发者工具创建的插件项目，发现 `project.config.json` 里缺少了 `"miniprogramRoot": "miniprogram/",` 字段，补上就可以打开了。

后续我们会修复这个问题。

**Comment by jzsjiale** [comment]
不仅是这一个问题，补充上以后，会有其他问题，比如选择使用TypeScript后，plugin.json文件里面引用的 "main": "index.ts"还会提示无法找到，sayHello调用也会出错。

**Comment by Garfield550** [comment]
@jzsjiale 这两个我们在排查问题，会解决的

**Comment by jzsjiale** [comment]
@Garfield550 #选择使用TypeScript后，plugin.json文件里面引用的 "main": "index.ts"还会提示无法找到，sayHello调用也会出错#   这两个错误还是存在，taro的2.0.2版本里面没有解决是吧？

**Comment by Garfield550** [comment]
暂时还没有

**Comment by jzsjiale** [comment]
@Garfield550 好的，谢谢

**Comment by wcxz520** [comment]
这个问题解决了吗？
这个问题我一轮下来全碰到了~我现在是2.0.3

**Comment by hiscc** [comment]
试下在小程序开发工具内删除项目再重新导入

**Comment by Usualminds** [comment]
修改 project.config.json 下 
miniprogramRoot": ".dist/ 为 **miniprogramRoot": "dist/**，多了一个点

**Comment by iooops** [comment]
> 修改 project.config.json 下
> miniprogramRoot": ".dist/ 为 **miniprogramRoot": "dist/**，多了一个点

楼上说得没错

**Comment by ISBN9527** [comment]
这个还没有解决啊，我build完直接拉dist进小程序开发工具还是报这个错，
Taro v3.0.21

**Comment by Chen-jj** [comment]
@ISBN9527 3.x 还没支持编写小程序插件

**Comment by ISBN9527** [comment]
我直接拉dist下的weapp进微信开发者工具效果一样吗？

**Comment by ISBN9527** [comment]
不对啊，我看官方视屏教程中，taro就是3.0的啊

**Comment by junjun0326** [comment]
![image](https://user-images.githubusercontent.com/17972307/103265839-7ab7b700-49e9-11eb-9d7b-d9f6b76cc915.png)
youshu@bogon ~ % sudo taro init 'wxpluginsssss'
Password:
👽 Taro v3.0.7

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ kkk
? 请选择框架 Vue
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 wxplugin

✔ 创建项目: wxpluginsssss
✔ 创建文件: /Users/youshu/wxpluginsssss/.editorconfig
✔ 创建文件: /Users/youshu/wxpluginsssss/.eslintrc
✔ 创建文件: /Users/youshu/wxpluginsssss/.gitignore
✔ 创建文件: /Users/youshu/wxpluginsssss/babel.config.js
✔ 创建文件: /Users/youshu/wxpluginsssss/global.d.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/package.json
✔ 创建文件: /Users/youshu/wxpluginsssss/project.config.json
✔ 创建文件: /Users/youshu/wxpluginsssss/tsconfig.json
✔ 创建文件: /Users/youshu/wxpluginsssss/config/dev.js
✔ 创建文件: /Users/youshu/wxpluginsssss/config/index.js
✔ 创建文件: /Users/youshu/wxpluginsssss/config/prod.js
✔ 创建文件: /Users/youshu/wxpluginsssss/src/app.config.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/app.scss
✔ 创建文件: /Users/youshu/wxpluginsssss/src/app.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/pages/index/index.config.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/pages/index/index.scss
✔ 创建文件: /Users/youshu/wxpluginsssss/src/pages/index/index.vue
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/index.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/plugin.json
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/doc/README.md
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/doc/example.jpeg
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/components/avatar/avatar.config.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/components/avatar/avatar.scss
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/components/avatar/avatar.vue
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/components/listItem/listItem.config.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/components/listItem/listItem.scss
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/components/listItem/listItem.vue
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/pages/list/list.config.ts
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/pages/list/list.scss
✔ 创建文件: /Users/youshu/wxpluginsssss/src/plugin/pages/list/list.vue

✔ cd wxpluginsssss, 执行 git init
✔ 安装成功

**Comment by junjun0326** [comment]
Taro v3.0.7 创建 vue wxplugin 模板报错，请问有解决办法吗？
或者Taro哪个版本 下创建 vue wxplugin 可以正常

**Comment by VinnieWEN-cd** [comment]
![image](https://user-images.githubusercontent.com/75285960/103347740-cb570f00-4ad2-11eb-957b-58b11e92ed22.png)
未解决。。。。

**Comment by jinjinwa** [comment]
这个有方案了么？

**Comment by hwwn** [comment]
刚试，楼上的问题全遇到了，最新的版本还是有问题，我觉得设计之初可能是正对 js 项目的，导致走的配置读到 ts 的文件结构就啥都不认识了 。。。

**Comment by hwwn** [comment]
> ![image](https://user-images.githubusercontent.com/3471836/72491831-3ffb5400-3856-11ea-8929-c302a630a16c.png)
> 
> 比对微信开发者工具创建的插件项目，发现 `project.config.json` 里缺少了 `"miniprogramRoot": "miniprogram/",` 字段，补上就可以打开了。
> 
> 后续我们会修复这个问题。

2021年了 。。。疫苗都研制出来了。。这个 bug 依旧没有修复啊。。。

**Comment by roc-codes** [comment]
> @ISBN9527 3.x 还没支持编写小程序插件

请问 3.x 现在支持编写小程序插件了吗?

**Comment by hwwn** [comment]
> > @ISBN9527 3.x 还没支持编写小程序插件
> 
> 请问 3.x 现在支持编写小程序插件了吗?

支持率，但是只是 3.x 不行，必须是最新的版本才可以，建议升到最新的 Taro

**Comment by BinZhiZhu** [comment]
老哥们taro3.3.1 刚刚打开，也是这个报错 = =

![image](https://user-images.githubusercontent.com/35824900/130462830-55159cbf-ca56-496a-9583-f0bcda5f47ae.png)

![image](https://user-images.githubusercontent.com/35824900/130462876-a9ae3176-4fa3-4ec6-a589-81e31f9ac6a4.png)

**Comment by BinZhiZhu** [comment]
解决了，是默认模板的project.config.json的路径指向问题

减少一层miniprogram就行了
![image](https://user-images.githubusercontent.com/35824900/130463735-bd2bf358-ec4e-4548-8a18-c7aa002704c3.png)
```json
{
  "miniprogramRoot": "miniprogram/",
  "pluginRoot": "plugin/"
}

```

**Comment by noscripter** [comment]
![image](https://user-images.githubusercontent.com/1673877/167762007-d4933073-b868-4a7d-b3f8-1e5d4635d384.png)

```shell
👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.3 - ~/.npm-global/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1
      @tarojs/mini-runner: 3.4.1 => 3.4.1
      @tarojs/react: 3.4.1 => 3.4.1
      @tarojs/runtime: 3.4.1 => 3.4.1
      @tarojs/taro: 3.4.1 => 3.4.1
      @tarojs/webpack-runner: 3.4.1 => 3.4.1
      babel-preset-taro: 3.4.1 => 3.4.1
      eslint-config-taro: 3.4.1 => 3.4.1
      react: ^17.0.0 => 17.0.2
    npmGlobalPackages:
      typescript: 4.4.4
```

**Comment by lccxxq** [comment]
新起的微信插件项目就跑不起来，这么bug怎么就给关了呢？
![image](https://user-images.githubusercontent.com/19908804/192418404-7cd83d46-5a16-49b1-9cc0-5e3243abaa80.png)
![image](https://user-images.githubusercontent.com/19908804/192418499-f7de1bd5-a661-489f-8064-fdc30c082e3e.png)
![image](https://user-images.githubusercontent.com/19908804/192418591-535a03ad-cf68-4227-900e-073b4d54379a.png)

**Comment by lccxxq** [comment]
@jzsjiale @Chen-jj @iooops @Garfield550 @noscripter 
不好意思打扰了，麻烦看一下上面的那个问题。谢谢了 ！[握手]

**Comment by Chen-jj** [comment]
@lccxxq 参考这个示例看看：https://github.com/NervJS/taro/tree/next/examples/build-weapp-plugin
