### ISSUE TITLE
[taro-2.0.1]从项目维护的角度来谈如何升级tarojs 2.x的注意点

### ISSUE THREAD

**Issue by shenghanqin** [NervJS/taro#5339]
### 阅读本文前，请先看这里

* 《[迁移至 Taro 2.x 指南](https://nervjs.github.io/taro/docs/migrate-to-2.html)》这篇文章详细说明了升级方法，请大家细致阅读。当然2.x的特色如下：
  * 利于维护，大量的逻辑交由 webpack 来处理，我们只需要维护一些插件
  * 更加稳定，相较于自研的构建系统，新的构建会更加稳定，降低一些奇怪错误的出现概率
  * 可扩展性强，可以通过自行加入 webpack loader 与 plugin 的方式做自己想要的扩展
* 《[2.0.0 beta 版本测试通告](https://github.com/NervJS/taro/issues/4837) 》说明了2.x版本升级的内容，也有不少小伙伴反馈了升级过程中出现的小问题，在此表示感谢。 

## 框架升级与项目维护

而我想从项目维护方面阐述升级注意点。

### 升级前

**1、新建2.x分支**

新老版本随意切换，顶多就是每次重新安装依赖，但不会影响老项目的功能迭代。

**2、taro-cli装在本地**

`cli`装在本地而非全局的好处是，全局可以安装1.3.x的版本，这样与团队其他小伙伴保持一致，而2.x测试的分支，只会影响当前项目而已。

**3、进行升级**

按照《[迁移至 Taro 2.x 指南](https://nervjs.github.io/taro/docs/migrate-to-2.html)》，修改package.json，修改配置，重新安装依赖

**4、启动小程序**

### 升级后
升级小程序后，建议从以下几个方面来排查小程序是否有小问题。

1、编译后，开发者工具是否有明显报错

比如，使用了装饰器后，就需要修改一下export default的写法了。

```js
@connect()
export default class Index extends Taro.Component {}


@connect()
class Index extends Taro.Component {}
export default Index
```

2、关键的基础功能是否正常

登录、支付、数据埋点、状态管理、视频播放、音频播放等

其实，2.x的更新重点是webpack编译，在这些基础UI组件上改动不大，但为了保险起见，还是自己先排查一下

3、为测试工程师提供测试方案

列举常见功能

* 登录场景与列表页、点赞功能关联的场景
* 支付与详情页状态关联的场景
* 数据埋点的查看

升级周期估算

* 升级2.x，顺利的话在半小时内搞定，但除了小问题就得排查个小半天
* 罗列测试点，需要小半天
* 测试工程师进行测试，可能得等待好多天

所以，升级2.x，需要提前告知测试工程师。

**Comment by sprout-echo** [comment]
![image](https://user-images.githubusercontent.com/17763943/72492218-61107480-3857-11ea-9249-3a1e60f99695.png)
为什么我的运行小程序  显示编译成功 但是 之后就进程退出了 你知道是什么原因吗

**Comment by dreamthen** [comment]
uglify压缩不起作用，2.0.1版本的体积比原来大了400k左右

**Comment by shenghanqin** [comment]
> uglify压缩不起作用，2.0.1版本的体积比原来大了400k左右

确实这是一个值得考虑的问题。我的小程序未压缩前也1.8M啦

**Comment by luckyadam** [comment]
> uglify压缩不起作用，2.0.1版本的体积比原来大了400k左右
生效的，你看下打包后的代码，至于具体哪里的代码大了，可以用 webpack-bundle-analyzer 看看打包后的文件

**Comment by broven** [comment]
要是能eject就更方便了.

**Comment by liuzhenji** [comment]
vendor.js过大，不能压缩，uglify 没有生效应该

**Comment by lp13762436965** [comment]
自定义函数式组件2.x版本样式没了  , 1.x还是有样式的, 请问这个问题如果解决呢

**Comment by fuersite** [comment]
升级2.2.7后代码打包后变大了许多，看了一些打包后文件，只有js css 做了压缩，wxml 没有被压缩，包括npm包里面的wxml也没用被压缩，怎么解决，要手动自己压缩吗？

**Comment by youngluo** [comment]
3.x 页面路由参数没解码操作
