### ISSUE TITLE
[taro-2.0.0]centos7下无法找到图片

### ISSUE THREAD

**Issue by wangjunhong** [NervJS/taro#5340]
### 问题描述
node 12.10.0
yarn 1.12.1
taro 2.0.0
在windows环境下可以正常打包不报错
在centos环境下（node yarn taro环境一致）报错 Module not found: Can't resolve '../../assets/isWeiXin.png' in '/usr/share/nginx/rebate/.temp/components/common

### 复现步骤

yarn build:h5

🙅   Failed to compile.

./.temp/components/common/weiXinTip.js
Module not found: Can't resolve '../../assets/isWeiXin.png' in '/usr/share/nginx/rebate/.temp/components/common'

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
希望centos能跟windows环境下保持一致

### 报错信息

![image](https://user-images.githubusercontent.com/19639929/72491450-07a74600-3855-11ea-873e-ce2b28f3b9e3.png)
![image](https://user-images.githubusercontent.com/19639929/72491466-15f56200-3855-11ea-98b4-db1b12216883.png)
![image](https://user-images.githubusercontent.com/19639929/72491556-58b73a00-3855-11ea-83bb-baadde9f765d.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
有木有可能跟文件夹权限有关系呢？Centos上对文件权限要求更严格吧？

**Comment by wangjunhong** [comment]
> 有木有可能跟文件夹权限有关系呢？Centos上对文件权限要求更严格吧？

我文件已经给了777权限了 还是不行，一直解决不了 我就用网络图片代替本地图片先绕过去了
