### ISSUE TITLE
monorepo 项目小程序端页面支持来自不同Lerna模块

### ISSUE THREAD

**Issue by georgezouq** [NervJS/taro#5344]
### 问题描述

我们通过lerna 区分不同的业务模块，为了方便多个项目直接相互复用，小程序不同的页面需来自不同的应用模块，有没有可行的实现方式？

关联问题：

#4742  

### 复现步骤

实现目录结构

```
- packages
  - mobile // taro项目
  - pc
  - utils
  - ui
- plugins
  - plugin1
    - pages
      - page1.tsx // 需引入页面
- lerna.json
- package.json
```

### 期望行为

```
  config: Config = {
    pages: {
      'pages/apps/crm/index': '@arrplat/crm/mobile/pages/index'
    }
  }
```

### 系统信息

Taro CLI 2.0.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.2.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm

**Comment by georgezouq** [comment]
#4742

**Comment by georgezouq** [comment]
已解决

**Comment by tourze** [comment]
> 已解决

这个怎么解决的啊 @georgezouq

**Comment by sealzrt** [comment]
> 已解决

请问 2.X 支持吗

**Comment by foosaa** [comment]
请问是怎么解决的？

**Comment by songxiaoliang** [comment]
@foosaa @sealzrt @tourze 各位大佬，有解决方案了吗？
