### ISSUE TITLE
[taro-2.0.1]React-Native 启动后 会出现 refs 相关的警告

### ISSUE THREAD

**Issue by limitLiu** [NervJS/taro#5350]
### 问题描述

`Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

### 复现步骤

React-Native 端会出现问题描述的这个警告

### 期望行为

希望可以解决这个问题

### 系统信息

👽 Taro v2.0.1

  Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.2.2

**Comment by Pines-Cheng** [comment]
[Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?](https://github.com/reactjs/reactjs.org/issues/1730)

**Comment by Pines-Cheng** [comment]
最新的版本没能重现～
