### ISSUE TITLE
Button组件的EventProps是否应当增加入参

### ISSUE THREAD

**Issue by yeeing** [NervJS/taro#5353]
### 问题描述

点击button时传参是否有更好方法

### 复现步骤
当我想button点击传参时
```js
<Button onClick={(event,value)=>{...}></Button>
```
common.d.ts内onClick参数定义是这样的(event: ITouchEvent) => any
### 期望行为
是否应该更改为(event:ITouchEvent,...args:any)=>any

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
直接在设置函数的时候传参数就好了

`<Button onClick={this.handleClick.bind(value)></Button>`

也可以通过函数返回相应的方法传参数

`<Button onClick={this.returnHandleClick(value)></Button>`
