### ISSUE TITLE
picker 确定 取消 文字不能修改

### ISSUE THREAD

**Issue by qq857254562** [NervJS/taro#5358]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
可以修改文字

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Pines-Cheng** [comment]
不贴一下代码吗？

**Comment by qq857254562** [comment]
<Picker mode='selector' rangeKey='name' range={dataList} onChange={this.onChange}>
                <Text style={{width:'100%',textAlign:'center'}} className='picker'>
                  {this.state.provincesName}
                </Text>
              </Picker>

**Comment by qq857254562** [comment]
`<Picker mode='selector' rangeKey='name' range={dataList} onChange={this.onChange}>
                <Text style={{width:'100%',textAlign:'center'}} className='picker'>
                  {this.state.provincesName}
                </Text>
              </Picker>`

**Comment by qq857254562** [comment]
![image](https://user-images.githubusercontent.com/42058821/74096051-89c51a80-4b34-11ea-843f-bc31b10e0ac1.png)

**Comment by Pines-Cheng** [comment]
微信小程序的 picker 组件也没有提供修改文字的属性啊。
