### ISSUE TITLE
原生小程序写法的scss文件没有被编译成wxss

### ISSUE THREAD

**Issue by die214144031** [NervJS/taro#536]
![image](https://user-images.githubusercontent.com/11813890/44702495-515b8900-aac6-11e8-97af-e012fda86d10.png)
![image](https://user-images.githubusercontent.com/11813890/44702514-633d2c00-aac6-11e8-83a4-cde5f0883378.png)
--------------------------------------
因为之前项目小程序用了sass-loader转换，现在想迁移到taro。发现scss文件没有被编译，即使在JS文件里面
import './detail.scss' 都不行，希望能得到支持。
taro版本beta.16

**Comment by die214144031** [comment]
使用过程中，还有个编译问题 偶现：
npm run dev:weapp 过程中偶尔丢失js文件
----------------
![image](https://user-images.githubusercontent.com/11813890/44702822-d3987d00-aac7-11e8-8749-06675812876f.png)
----------------
这个taro-weapp中的index.js文件偶尔没有导致报错
还有代码文件里面import的js文件偶尔也丢了导致报错
这个问题 关闭终端 重新编译就好了 但是会很烦( ╯□╰ )

**Comment by luckyadam** [comment]
Taro 版本多少

**Comment by die214144031** [comment]
taro版本 beta.16

**Comment by die214144031** [comment]
@luckyadam 还是没有fix这个问题噢~
