### ISSUE TITLE
请问是否支持微信小程序的this.animate(selector, keyframes, duration, callback)？

### ISSUE THREAD

**Issue by oMhuAaN** [NervJS/taro#5362]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
资瓷
this.$scope. animate

**Comment by oMhuAaN** [comment]
> 资瓷
> this.$scope. animate

请问大神，文档上为啥没有相关的介绍呢，您的意思是在this和animate中间加个$scope就行了是吗？

**Comment by weixinyan** [comment]
taro 3 不支持this.animate()或者 this.$scope.animate(),可以通过Taro.Current.page.animate()来获取动画
