### ISSUE TITLE
样式代码的条件编译要怎么写才行?

### ISSUE THREAD

**Issue by wukuy** [NervJS/taro#5363]
### 问题描述
样式代码的条件编译要怎么写才行?
这么写?
```
/*  #ifdef  %h5%  */
.cp{
  color: red;
}
/*  #endif  */
```
或这么写?
```
/*  #ifdef  h5 */
.cp{
  color: red;
}
/*  #endif  */
```
我编译微信小程序怎么写，样式都打进来了，是我理解有误？
文档能举个例子吗？

![image](https://user-images.githubusercontent.com/26781738/72653874-00ed1000-39c8-11ea-94ef-55d287e5ff1a.png)

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
/*  #ifdef  h5 */
.cp{
  color: red;
}
/*  #endif  */

这么写

**Comment by Garfield550** [comment]
@luckyadam 文档是不是也要改一下？ https://github.com/NervJS/taro/blob/2.x/docs/before-dev-remind.md
