### ISSUE TITLE
请问是否支持在taro页面中引入小程序原生组件？

### ISSUE THREAD

**Issue by oMhuAaN** [NervJS/taro#5365]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
请更加具体地描述你想引入哪一个原生组件？大部分组件都是基于原生组件实现的，差异不大

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/mini-third-party.html#docsNav
资瓷
