### ISSUE TITLE
H5选择上传视频失败，chooseVideo生成的Blob对象缺少类型

### ISSUE THREAD

**Issue by ruandk** [NervJS/taro#5366]
### 问题描述

H5选择上传视频失败，chooseVideo生成的Blob对象缺少类型

### 复现步骤

1. 使用Taro.chooseVideo 选择视频文件后获取tempFiles（这是个Blob对象数组）

2. 调用Taro.uploadFile上传该文件类型错误无法上传

3. 调试发现uploadFile文件的 Content-Type: text/plain

4. 查看源码发现创建Blob时未指定类型，片段代码见下：

```js
taroChooseVideo.onchange = function (e) {
    let arr = [...e.target.files]
    arr && arr.forEach(item => {
      let blob = new Blob([item])
      let url = URL.createObjectURL(blob)
      res.tempFilePaths.push(url)
      res.tempFiles.push({ path: url, size: item.size, type: item.type })
    })
    typeof success === 'function' && success(res)
    typeof complete === 'function' && complete(res)
    taroChooseVideoCallback(res)
  }
```

### 期望行为

我发现chooseImage存在过同样的问题，但在v1.3.13修复

希望chooseVideo同样处理

```js
let blob = new Blob([item], { type: item.type })
```

### 报错信息

上传文件类型错误

### 系统信息

 Taro CLI 1.3.29 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.29 => 1.3.29 
      @tarojs/components: 1.3.26 => 1.3.26 
      @tarojs/components-rn: 1.3.29 => 1.3.29 
      @tarojs/plugin-babel: 1.3.29 => 1.3.29 
      @tarojs/plugin-csso: 1.3.29 => 1.3.29 
      @tarojs/plugin-sass: 1.3.29 => 1.3.29 
      @tarojs/plugin-uglifyjs: 1.3.29 => 1.3.29 
      @tarojs/redux: 1.3.29 => 1.3.29 
      @tarojs/redux-h5: 1.3.29 => 1.3.29 
      @tarojs/router: 1.3.29 => 1.3.29 
      @tarojs/taro: 1.3.29 => 1.3.29 
      @tarojs/taro-alipay: 1.3.29 => 1.3.29 
      @tarojs/taro-h5: 1.3.29 => 1.3.29 
      @tarojs/taro-redux-rn: 1.3.29 => 1.3.29 
      @tarojs/taro-rn: 1.3.29 => 1.3.29 
      @tarojs/taro-router-rn: 1.3.29 => 1.3.29 
      @tarojs/taro-swan: 1.3.29 => 1.3.29 
      @tarojs/taro-tt: 1.3.29 => 1.3.29 
      @tarojs/taro-weapp: 1.3.29 => 1.3.29 
      @tarojs/webpack-runner: 1.3.29 => 1.3.29 
      eslint-config-taro: 1.3.29 => 1.3.29 
      eslint-plugin-taro: 1.3.29 => 1.3.29 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
      stylelint-config-taro-rn: 1.3.29 => 1.3.29 
      stylelint-taro-rn: 1.3.29 => 1.3.29 
    npmGlobalPackages:
      typescript: 3.6.4

**Comment by luckyadam** [comment]
可以直接提个 pr 哦
