### ISSUE TITLE
[taro-2.0.0]input组件的bindkeyboardheightchange在Taro component中找不到

### ISSUE THREAD

**Issue by rizzi37** [NervJS/taro#5367]
### 问题描述

小程序官方文档中已经有keyboardheightchange的支持, Taro中找不到
https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html

### 系统信息

~: taro info
👽 Taro v2.0.0

  Taro CLI 2.0.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 2.0.1 => 2.0.1 
      @tarojs/components-qa: 2.0.1 => 2.0.1 
      @tarojs/mini-runner: 2.0.1 => 2.0.1 
      @tarojs/redux: 2.0.1 => 2.0.1 
      @tarojs/redux-h5: 2.0.1 => 2.0.1 
      @tarojs/router: 2.0.1 => 2.0.1 
      @tarojs/taro: 2.0.1 => 2.0.1 
      @tarojs/taro-alipay: 2.0.1 => 2.0.1 
      @tarojs/taro-h5: 2.0.1 => 2.0.1 
      @tarojs/taro-qq: 2.0.1 => 2.0.1 
      @tarojs/taro-quickapp: 2.0.1 => 2.0.1 
      @tarojs/taro-swan: 2.0.1 => 2.0.1 
      @tarojs/taro-tt: 2.0.1 => 2.0.1 
      @tarojs/taro-weapp: 2.0.1 => 2.0.1 
      @tarojs/webpack-runner: 2.0.1 => 2.0.1 
      eslint-config-taro: 2.0.1 => 2.0.1 
      eslint-plugin-taro: 2.0.1 => 2.0.1 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.1 => 2.0.1 
      stylelint-taro-rn: 2.0.1 => 2.0.1

**Comment by shenghanqin** [comment]
使用方面是正常的呗？
