### ISSUE TITLE
taro init报错

### ISSUE THREAD

**Issue by iamzhangxin** [NervJS/taro#5370]
#3358 # 问题描述

使用taro init创建项目报错。

### 复现步骤

命令行执行 
`taro init littlecandy`

### 期望行为

项目创建成功

### 报错信息

<img width="1679" alt="WX20200119-143208@2x" src="https://user-images.githubusercontent.com/9925254/72676113-92dc4200-3ac8-11ea-8e1a-89bddebe028e.png">

### 系统信息

<img width="600" alt="WX20200119-143315@2x" src="https://user-images.githubusercontent.com/9925254/72676123-b2736a80-3ac8-11ea-9806-907b2bd04324.png">

### 补充信息
我估计是模板中的package.json无法识别

**Comment by Chen-jj** [comment]
dup #5285
