### ISSUE TITLE
Taro.getImageInfo({src:'xxx.png'}),找不到资源

### ISSUE THREAD

**Issue by rednumber16** [NervJS/taro#5372]
### 问题描述

微信端图片转换为base64，导致无法使用Taro.getImageInfo({src:'xxx.png'})，报错找不到资源，修改配置无效。

### 复现步骤
1.调用Taro.getImageInfo({src:'xxx.png'})

修改配置无效
`url: {
          enable: false,
          config: {
            limit: 0 // 设定转换尺寸上限
          }
        },`

### 期望行为

期望图片可以不转base64

**Comment by hisanshao** [comment]
2.x版本 这样配置有效的
![image](https://user-images.githubusercontent.com/26359618/72679218-148f9800-3ae8-11ea-8700-637fd57bfffc.png)

**Comment by rednumber16** [comment]
@hisanshao 谢谢，已解决。

**Comment by ZJL374910689** [comment]
我配置了怎么还是不行，加载不了

**Comment by ZJL374910689** [comment]
> 2.x版本 这样配置有效的
> ![image](https://user-images.githubusercontent.com/26359618/72679218-148f9800-3ae8-11ea-8700-637fd57bfffc.png)

我配置了还是不生效

**Comment by zmm2tysu** [comment]
@rednumber16 taro3好像这么配置没有用了
