### ISSUE TITLE
微信小程序Map组件属性bindmarkertap不触发的问题

### ISSUE THREAD

**Issue by ONEGISER** [NervJS/taro#5373]
在taro框架中使用微信小程序的Map，用其中的bindmarkertap属性，为什么会有附件中的这种警告？看着似乎是回调方法没识别，烦劳帮忙看看，点击这个marker ，理论上是触发事件的

**Comment by Garfield550** [comment]
Taro 规范中，所有 bind 都以 on 开头，所以用 `onMarkerTap` 试一下。

#1621

**Comment by ONEGISER** [comment]
经过测试，onMarkerTap和onCalloutTap都不起作用，onTap起作用

**Comment by Garfield550** [comment]
提供一个最小化复现吧，我们看一下

**Comment by ONEGISER** [comment]
我的代码如下：

import Taro, { Component } from '@tarojs/taro'
import { View, Map } from '@tarojs/components'
interface HomeState {

}

/**
 * 首页
 * 
 * by mytuo
 */
export class Home extends Component<any, HomeState> {
  constructor(props) {
    super(props)
    this.state = {

    }
  }

  componentWillMount() { }

  componentDidMount() {

  }

  componentWillUnmount() { }

  componentDidShow() {

  }

  componentDidHide() { }

  render() {
    const markers: any = [{ "oid": 22, "latitude": 36.059771, "longitude": 103.84348, "iconPath": "https://www.geowit.cn:3010/imgs/home/marker_red_fill.png", "width": 32, "height": 32, "callout": { "content": "干垃圾，湿垃圾，废弃燃料", "fontSize": 12, "borderRadius": 5, "borderWidth": 1.5, "borderColor": "#1aac19", "bgColor": "#fff", "padding": 5, "display": "BYCLICK", "textAlign": "center" } }]
    return (
      <View className='container'>
        <Map id='myMap' className='map'
          show-compass
          showLocation
          latitude={36.059771}
          longitude={103.84348}
          scale={10}
          markers={markers}
          onCalloutTap={(e) => { console.log(e,"callout"); }}
          onMarkerTap={(e) => { console.log(e,"marker"); }}
        >
        </Map>
      </View>
    )
  }
}

**Comment by Garfield550** [comment]
Taro 用的哪个版本，taro-weapp 的版本是什么，也请告知一下。
另外代码格式有点乱。

**Comment by ONEGISER** [comment]
Taro 和taro-weapp 都是2.0.1
详情及代码参见如下这个文档：
https://docs.qq.com/doc/DRW94V29UYlFOQ0dr

**Comment by luckyadam** [comment]
写 onMarkertap 试试

**Comment by kiko111** [comment]
我也出现了，react-hooks,
用bindMarkertap提示没绑定函数
用onMarkertap点击反应

**Comment by luckyadam** [comment]
> 我也出现了，react-hooks,
> 用bindMarkertap提示没绑定函数
> 用onMarkertap点击反应
> taro：1.3.27
> 用bind的情况开发者工具提示：Do not have anonymousState__temp2 handler in component
> @Garfield550

麻烦给下你的示例代码

**Comment by hackkun** [comment]
这边 onMarkerTap 也不触发

<Map
      longitude={116.313972}
      latitude={39.980014}
      markers={markers}
      setting={mapSetting}
      style={{ width: '100%', height: '100%' }}
      onMarkerTap={() => console.log(33)}
    />


版本
"@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.0.2",
    "@tarojs/react": "3.0.2",
    "@tarojs/runtime": "3.0.2",
    "@tarojs/taro": "3.0.2",
    "@tarojs/taro-weapp": "^2.2.10",
    "react": "^16.10.0",
    "react-dom": "^16.10.0"

**Comment by hackkun** [comment]
"@tarojs/taro": "3.0.2"
"@tarojs/taro-weapp": "^2.2.10"

这个版本确实有markertap事件无法点击的问题，要解决这个问题，我尝试了降低2版本，或者自己写一套原生map组件实现，详见文档：https://taro-docs.jd.com/taro/docs/mini-third-party/

**Comment by lavapapa** [comment]
如果想要让marker触发点击时间，必须指定id值，否则没有效果。文档上说“最好”带上id值，但其实id是必填项。我刚刚才解决。ONEGISER 你好像写成了 oid
