### ISSUE TITLE
【Taro.2.0.1】升级到2.0后，H5打包chunk分包的js大了很多

### ISSUE THREAD

**Issue by yinlsea** [NervJS/taro#5374]
### 问题描述

升级到2.0后，H5打包后大了很多，对比发现是chunk目录下分包的js大了很多，和原来1.3.x的做比较后发现chunk分包的js文件中有大量base64转码，而原来1.3.x的chunk分包js中是没有。imageUrlLoaderOption配置没有变都是设置的limit:8192。

**Comment by luckyadam** [comment]
hello，麻烦看下这里
https://github.com/NervJS/taro/blob/2.x/docs/migrate-to-2.md#%E5%9C%A8-js-%E4%B8%AD%E5%BC%95%E5%85%A5%E7%9A%84%E5%9B%BE%E7%89%87%E7%AA%81%E7%84%B6%E5%8F%98%E6%88%90-base64-%E6%A0%BC%E5%BC%8F

**Comment by yinlsea** [comment]
是打包的H5，另外imageUrlLoaderOption在1.3的时候就配置了8192，这里没有改变，对比和1.3打包的差异

**Comment by yinlsea** [comment]
隔了好久来看是否修复该问题，升级到最新的2.2.4尝试，编译打包居然内存溢出，报 JavaScript heap out of memory，降级到2.1.5打包通过，不会报内存溢出，但是依然没有解决chunk js内容中大量base64转码，只能继续切回1.3.x
