### ISSUE TITLE
[Taro 2.0.1] render 方法中使用 if 条件渲染错误（不符合预期）

### ISSUE THREAD

**Issue by smackgg** [NervJS/taro#5375]
### 问题描述
在 render 方法中使用 if 进行条件渲染，条件渲染不符合预期，并且执行了条件以外的代码逻辑。
补充：改为 if else 的写法后符合预期，虽然 if else 可以解决该问题，但是不符合 eslint 规范```不必要的 else 分支，请遵从 ESLint consistent-return: https://eslint.org/docs/rules/consistent-return```

### 复现步骤
Taro 2.0 版本 CLI 生成的项目，直接改动 page/index/index 如下，就会复现该问题

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

class Index extends Component {

    config = {
    navigationBarTitleText: '首页'
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
	// 强制为 true 方便测试
    if (true) {
      console.log('render block 1')
      return <View>loading</View>
    }
    console.log('render block 2')
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.props.add}>+</Button>
        <Button className='dec_btn' onClick={this.props.dec}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View><Text>{this.props.counter.num}</Text></View>
        <View><Text>Hello, World</Text></View>
      </View>
    )
  }
}

```

以上代码出现一下行为
1、渲染了条件以外的 dom
2、执行了条件以外的逻辑

![image](https://user-images.githubusercontent.com/13075469/72705413-58d97180-3b96-11ea-9e19-e21ff32ab4a5.png)

### 期望行为

只渲染 loading 条件中的 ```<View>loading</View>```, 且只执行并打印 ```console.log('render block 1)```

### 报错信息

无报错信息

### 系统信息

👽 Taro v2.0.1

  Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.1 => 2.0.1
      @tarojs/components-qa: 2.0.1 => 2.0.1
      @tarojs/mini-runner: 2.0.1 => 2.0.1
      @tarojs/redux: 2.0.1 => 2.0.1
      @tarojs/redux-h5: 2.0.1 => 2.0.1
      @tarojs/router: 2.0.1 => 2.0.1
      @tarojs/taro: 2.0.1 => 2.0.1
      @tarojs/taro-alipay: 2.0.1 => 2.0.1
      @tarojs/taro-h5: 2.0.1 => 2.0.1
      @tarojs/taro-qq: 2.0.1 => 2.0.1
      @tarojs/taro-quickapp: 2.0.1 => 2.0.1
      @tarojs/taro-swan: 2.0.1 => 2.0.1
      @tarojs/taro-tt: 2.0.1 => 2.0.1
      @tarojs/taro-weapp: 2.0.1 => 2.0.1
      @tarojs/webpack-runner: 2.0.1 => 2.0.1
      eslint-config-taro: 2.0.1 => 2.0.1
      eslint-plugin-taro: 2.0.1 => 2.0.1
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.1 => 2.0.1
      stylelint-taro-rn: 2.0.1 => 2.0.1

### 补充信息

当代码改成 if else 的写法，就没有问题了，代码如下

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'

import { add, minus, asyncAdd } from '../../actions/counter'

import './index.scss'


@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add () {
    dispatch(add())
  },
  dec () {
    dispatch(minus())
  },
  asyncAdd () {
    dispatch(asyncAdd())
  }
}))
class Index extends Component {

    config = {
    navigationBarTitleText: '首页'
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
	// 强制为 true 方便测试
    if (true) {
      console.log('render block 1')
      return <View>loading</View>
    } else {
      console.log('render block 2')
      return (
        <View className='index'>
          <Button className='add_btn' onClick={this.props.add}>+</Button>
          <Button className='dec_btn' onClick={this.props.dec}>-</Button>
          <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
          <View><Text>{this.props.counter.num}</Text></View>
          <View><Text>Hello, World</Text></View>
        </View>
      )
    }
  }
}

export default Index

```
符合预期结果

![image](https://user-images.githubusercontent.com/13075469/72705772-4a3f8a00-3b97-11ea-9039-55c94f3f1f90.png)

**Comment by Chen-jj** [comment]
@smackgg JSX 是编译时处理的，编译时对语法有些要求，可能这种写法编译时没覆盖到。先写 if else 吧，等到 Taro 3 运行时处理 JSX 才能根治。

**Comment by smackgg** [comment]
@Chen-jj 写 if else 编译时又会报 eslint 的错... 先这样吧~ thx

**Comment by ly827** [comment]
这个问题其实更严重，在编译支付宝小程序的时候，if判断直接就没有了，变成了 _this.$usedState 的一个元素，然后就不在执行if了。。。。。

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
