### ISSUE TITLE
useImperativeHandle 如何使用

### ISSUE THREAD

**Issue by Zigei** [NervJS/taro#5376]
### 问题描述
'@tarojs/taro' 中含有 useImperativeHandle 方法  但是 d.ts 的描述文件里面写的是 react 的 无法正常在 hooks 中使用
hooks 无法传入 第二个参数 ref
目前要如何 才能在 hooks 中使用 ref 暴露出去 这个组件

### 期望行为
添加 正确的 useImperativeHandle 使用说明 或者更新 d.ts 文件

### 系统信息

  Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.7.4

**Comment by luckyadam** [comment]
暴露出的 hooks api 与 typing 是对得上的啊

**Comment by Zigei** [comment]
> 暴露出的 hooks api 与 typing 是对得上的啊

useImperativeHandle 需要配合 forwardRef  源代码里面 这个 关键字 但是并没有导出

**Comment by z724211471** [comment]
可以这样使用
 function Father(){
  const childRef=useRef()
 function click(){
  chatroomRef.current.handless()
 }
  return (<Child childRef={childRef}></Child>)
 }

 function Child({childRef}){

  useImperativeHandle(childRef, () => ({
    handless: () => {

    }
  }))

  return (<View>ss</View>)

 }`

`

**Comment by yz1311** [comment]
坑

**Comment by xchunzhao** [comment]
> 可以这样使用
> `function Father(){ const childRef=useRef() function click(){ chatroomRef.current.handless() } return (<Child childRef={childRef}></Child>) }`
> 
> `function Child({childRef}){ useImperativeHandle(childRef, () => ({ handless: () => { } })) return (<View>ss</View>) }`

 Taro 2.0.7这样使用也不行

**Comment by liufeisprit** [comment]
taro 2到底父组件 怎么调用子组件方法呢？ useImperativeHandle forwardRef 又是阉割版的 唉
