### ISSUE TITLE
小程序转\(^o^)/~

### ISSUE THREAD

**Issue by zhizhi1993** [NervJS/taro#5377]

**Comment by zhizhi1993** [comment]
![image](https://user-images.githubusercontent.com/22871066/72709359-c6d66680-3b9f-11ea-9a8b-a0cd19449701.png)

**Comment by Garfield550** [comment]
您好，请附带尽可能详细的问题描述，可复现的代码，Taro 和相关依赖的版本，并说明问题发生的步骤。
