### ISSUE TITLE
jsx多分支判断编译的bug

### ISSUE THREAD

**Issue by qiangqiang93** [NervJS/taro#5382]
### 问题描述

首先我是在微信小程序端发现了这个问题，（其他平台没有验证），不确定其他平台是否存在。

我需要根据不同条件渲染不同当内容，使用了较多的if-else（就目前场景来说还不算多）。发现渲染不符预期。检查编译后的文件发现编译后的wxml有一些问题。

### 复现步骤

1. tsx代码片段
```tsx
  renderSend(content: ICustomMsg) {
    if (content.type === -2) {
      return <Text className="message-system-text">等待医生接诊</Text>;
    } else if (content.type === 4) {
      return <Text className="message-system-text">您已发送表单</Text>;
    } else if (content.type === 5) {
      if (content.data.agree) {
        return (
          <Text className="message-system-text">
            您已同意医生查看历史病历的请求
          </Text>
        );
      }
      return (
        <Text className="message-system-text">
          您拒绝了医生查看历史病历的请求
        </Text>
      );
    } else if (content.type === 10) {
      if (content.data.agree) {
        return (
          <View className="message-system-text">
            您同意了结束会话
            <Navigator
              url={"/pages/session/appraisal/index?id=" + content.treatmentId}
            >
              前往评价>>
            </Navigator>
          </View>
        );
      }
      return <Text className="message-system-text">您拒绝了结束会话</Text>;
    }
    return null;
  }
  ...

render() {
    const { content } = this.props;
    if (!content) return null;
    return (
      <View className="message-system">
        <View className="message-system-content">
         { this.renderSend(content) }
        </View>
      </View>
    );
  }
```
2. 编译后的wxml
```wxml
<template name="renderSend">
    <block>
        <block wx:if="{{content.type === -2}}"><text class="message-system-text">等待医生接诊</text>
        </block>
        <block wx:elif="{{content.type === 4}}"><text class="message-system-text">您已发送表单</text>
        </block>
        <block wx:elif="{{content.data.agree}}"><text class="message-system-text">您已同意医生查看历史病历的请求</text>
        </block>
        <block wx:elif="{{content.type === 5}}"><text class="message-system-text">您拒绝了医生查看历史病历的请求</text>
        </block>
        <block wx:elif="{{content.data.agree}}">
            <view class="message-system-text">您同意了结束会话
                <navigator url="{{'/pages/session/appraisal/index?id=' + content.treatmentId}}">前往评价>></navigator>
            </view>
        </block>
        <block wx:elif="{{content.type === 10}}"><text class="message-system-text">您拒绝了结束会话</text>
        </block>
        <view wx:else></view>
    </block>
</template>
```

### 期望行为

很明显，编译后的wxml的判断分支不符合jsx的条件分支。

### 报错信息

没有保存信息

### 系统信息

👽 Taro v1.3.22

  Taro CLI 1.3.22 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.22 => 1.3.22 
      @tarojs/components: 1.3.22 => 1.3.22 
      @tarojs/plugin-babel: 1.3.22 => 1.3.22 
      @tarojs/plugin-csso: 1.3.22 => 1.3.22 
      @tarojs/plugin-sass: 1.3.22 => 1.3.22 
      @tarojs/plugin-uglifyjs: 1.3.22 => 1.3.22 
      @tarojs/redux: ^1.3.22 => 1.3.22 
      @tarojs/redux-h5: ^1.3.22 => 1.3.22 
      @tarojs/router: 1.3.22 => 1.3.22 
      @tarojs/taro: ^1.3.22 => 1.3.22 
      @tarojs/taro-alipay: 1.3.22 => 1.3.22 
      @tarojs/taro-h5: ^1.3.22 => 1.3.22 
      @tarojs/taro-qq: 1.3.22 => 1.3.22 
      @tarojs/taro-quickapp: 1.3.22 => 1.3.22 
      @tarojs/taro-swan: 1.3.22 => 1.3.22 
      @tarojs/taro-tt: 1.3.22 => 1.3.22 
      @tarojs/taro-weapp: 1.3.22 => 1.3.22 
      @tarojs/webpack-runner: 1.3.22 => 1.3.22 
      eslint-config-taro: 1.3.22 => 1.3.22 
      eslint-plugin-taro: 1.3.22 => 1.3.22 
      nerv-devtools: ^1.5.0 => 1.5.3 
      nervjs: ^1.5.3 => 1.5.3 
      stylelint-config-taro-rn: 1.3.22 => 1.3.22 
      stylelint-taro-rn: 1.3.22 => 1.3.22 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
目前 Taro 1 和 Taro 2 在 JSX 语法转小程序模版方面还是基于 AST 处理的方式。

当 AST 过于复杂的时候（比如嵌套多层当 `if-else`），就有可能出现 AST 分析错误，导致转译后的模版出现问题。

个人建议把多个条件判断拆开来写。

**Comment by shenghanqin** [comment]
我从实际开发的情况来看，抖音小程序的编译效果就比不过微信小程序版本的，所以我尽量用三元运算符代替if判断返回return，尽量用更少的判断语句来构思我的业务逻辑，或者把这些判断放在数据处理层而不是render方法里面。

**Comment by rojer95** [comment]
我也遇过，我的处理方式是
只用 if(xxxx) return <..></..>的嵌套
不要用最后或者中间过程中 return null;

**Comment by shenghanqin** [comment]
@qiangqiang93 这个你完全可以用对象map把你的文本归纳好。
比如
```
const TEXT_MAP = {
'-1': 'a',
'2': '2'
}

<View>{TEXT_MAP[content.type] || '默认文本'}</View>
```
