### ISSUE TITLE
Throw class not defined if decorator before export 

### ISSUE THREAD

**Issue by zqjimlove** [NervJS/taro#5383]
# 问题描述

当修饰符用在export之前，各个环境下都报not defined 错误。

### 复现步骤

具体看代码

```js
@connect(
  ({apply}) => ({apply}),
  dispatch => ({
    updateOrderInfo: () => dispatch(updateOrderInfo())
  })
)
export default class chooseBank extends Component {

}

```

### 期望行为

成功运行

### 报错信息

ReferenceError: chooseBank is not defined

### 系统信息

  Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.14.2/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.14.2/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.2 => 2.0.2
      @tarojs/cli: 2.0.2 => 2.0.2
      @tarojs/components: 2.0.2 => 2.0.2
      @tarojs/mini-runner: 2.0.2 => 2.0.2
      @tarojs/plugin-babel: 2.0.2 => 2.0.2
      @tarojs/plugin-csso: 2.0.2 => 2.0.2
      @tarojs/plugin-less: 2.0.2 => 2.0.2
      @tarojs/plugin-uglifyjs: 2.0.2 => 2.0.2
      @tarojs/redux: 2.0.2 => 2.0.2
      @tarojs/redux-h5: 2.0.2 => 2.0.2
      @tarojs/router: 2.0.2 => 2.0.2
      @tarojs/taro: 2.0.2 => 2.0.2
      @tarojs/taro-alipay: 2.0.2 => 2.0.2
      @tarojs/taro-h5: 2.0.2 => 2.0.2
      @tarojs/taro-qq: 2.0.2 => 2.0.2
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2
      @tarojs/taro-swan: 2.0.2 => 2.0.2
      @tarojs/taro-tt: 2.0.2 => 2.0.2
      @tarojs/taro-weapp: 2.0.2 => 2.0.2
      @tarojs/webpack-runner: 2.0.2 => 2.0.2
      eslint-config-taro: 2.0.2 => 2.0.2
      eslint-plugin-taro: 2.0.2 => 2.0.2
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.2 => 2.0.2
      stylelint-taro-rn: 2.0.2 => 2.0.2

### 补充信息

使用 babel 直接编译的代码能看到  
```js
var chooseBank = (_dec = (0, _redux.connect)();
Page(__webpack_require__(/*! @tarojs/taro-swan */ "./node_modules/@tarojs/taro-swan/index.js").default.createComponent(chooseBank, true));
```
但经过taro的会变成 
```js
_class = (_dec = (0, _redux.connect)();
Page(__webpack_require__(/*! @tarojs/taro-swan */ "./node_modules/@tarojs/taro-swan/index.js").default.createComponent(chooseBank, true));
```

**Comment by Garfield550** [comment]
Dup #5086

`export` 和 `class` 分开写

```js
class MyClass {}
export default MyClass
```
