### ISSUE TITLE
wx.equestSubscribeMessage 支持

### ISSUE THREAD

**Issue by WuYunlong** [NervJS/taro#5387]
### 问题描述
wx.equestSubscribeMessage 支持
在文档中未发现该部分内容

### 期望行为

对 wx.equestSubscribeMessage 支持

### 报错信息
![image](https://user-images.githubusercontent.com/3301446/73087458-7f3c3b80-3f0d-11ea-9116-a7a05f1ee794.png)

### 系统信息

👽 Taro v2.0.2

当前您正在使用 Taro 2.0 版本，请先执行 taro doctor 确保编译配置正确
如出现令你束手无策的问题，请使用 taro update 命令更新到你指定的稳定版本

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v13.7.0/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2
      @tarojs/components-qa: 2.0.2 => 2.0.2
      @tarojs/mini-runner: 2.0.2 => 2.0.2
      @tarojs/router: 2.0.2 => 2.0.2
      @tarojs/taro: 2.0.2 => 2.0.2
      @tarojs/taro-alipay: 2.0.2 => 2.0.2
      @tarojs/taro-h5: 2.0.2 => 2.0.2
      @tarojs/taro-qq: 2.0.2 => 2.0.2
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2
      @tarojs/taro-rn: 2.0.2 => 2.0.2
      @tarojs/taro-swan: 2.0.2 => 2.0.2
      @tarojs/taro-tt: 2.0.2 => 2.0.2
      @tarojs/taro-weapp: 2.0.2 => 2.0.2
      @tarojs/webpack-runner: 2.0.2 => 2.0.2
      eslint-config-taro: 2.0.2 => 2.0.2
      eslint-plugin-taro: 2.0.2 => 2.0.2
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.2 => 2.0.2
      stylelint-taro-rn: 2.0.2 => 2.0.2
👽 Taro v2.0.2

当前您正在使用 Taro 2.0 版本，请先执行 taro doctor 确保编译配置正确
如出现令你束手无策的问题，请使用 taro update 命令更新到你指定的稳定版本

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v13.7.0/bin/yarn
      npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2
      @tarojs/components-qa: 2.0.2 => 2.0.2
      @tarojs/mini-runner: 2.0.2 => 2.0.2
      @tarojs/router: 2.0.2 => 2.0.2
      @tarojs/taro: 2.0.2 => 2.0.2
      @tarojs/taro-alipay: 2.0.2 => 2.0.2
      @tarojs/taro-h5: 2.0.2 => 2.0.2
      @tarojs/taro-qq: 2.0.2 => 2.0.2
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2
      @tarojs/taro-rn: 2.0.2 => 2.0.2
      @tarojs/taro-swan: 2.0.2 => 2.0.2
      @tarojs/taro-tt: 2.0.2 => 2.0.2
      @tarojs/taro-weapp: 2.0.2 => 2.0.2
      @tarojs/webpack-runner: 2.0.2 => 2.0.2
      eslint-config-taro: 2.0.2 => 2.0.2
      eslint-plugin-taro: 2.0.2 => 2.0.2
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.2 => 2.0.2
      stylelint-taro-rn: 2.0.2 => 2.0.2

**Comment by ZakaryCode** [comment]
是说requestSubscribeMessage方法吧，直接使用`Taro.requestSubscribeMessage`就好了，文档可以参考小程序自己的文档
