### ISSUE TITLE
H5中Input组件focus问题

### ISSUE THREAD

**Issue by zouyang2015** [NervJS/taro#5393]
### 问题描述

当页面中有一个Input,一个Textarea时，在Input中设置focus, 这时把光标切换到Textarea上输入内容，光标会自己离开当Textarea组件前跳回Input组件上。
--- 问题只在H5端出现，微信小程序和RN没问题。

**Comment by Littly** [comment]
由于Taro与小程序的底层实现差异，这个问题暂时无法修复，建议针对 h5 端使用 ref 特殊处理下。
