### ISSUE TITLE
引入第三方库bug

### ISSUE THREAD

**Issue by vivi2015** [NervJS/taro#540]
![image](https://user-images.githubusercontent.com/10387963/44723401-779f1a00-ab02-11e8-83cc-439517615598.png)
不同的引入方式，使用isEqual方法时在小程序/H5下会表现不一致，moment也有同样的问题

**Comment by YikaJ** [comment]
+1。
希望 Taro 可以处理好 H5 和小程序组件的模块机制。

**Comment by luckyadam** [comment]
收到~ 3 应该才是正确的写法~ 我看看~

**Comment by luckyadam** [comment]
我测试了一下，最新版本
```javascript
import isEqual from 'lodash/isEqual'
```

这种引用方式在小程序和 H5 都正常了~

**Comment by YikaJ** [comment]
@luckyadam beta25 又无法支持了，只能 `* as isEqual`。

**Comment by luckyadam** [comment]
@YikaJ 没有改动这块逻辑呀😂

**Comment by shenghanqin** [comment]
@vivi2015 可以留心使用最新版本。这里先作为answered啦。
