### ISSUE TITLE
Button 不支持 data-xxx 属性

### ISSUE THREAD

**Issue by zhangxuyangAwesome** [NervJS/taro#5405]
**这个功能解决了什么问题？**

我在子组件中的分享按钮，要触发父组件的 onShareAppMessage 事件，子组件需同时传出分享的数据，原生 button 可使用属性 data-xxx 绑定数据，在 onShareAppMessage 的回调中拿到 dataset 等数据。
目前是拿不到数据的：
![image](https://user-images.githubusercontent.com/52990953/73604979-4a964700-45d3-11ea-90e3-d5690117a422.png)

**你期望的功能是怎样的？**

// component
<Button openType="share" data-share-info={ {xxx} }>分享</Button>
// father page
onShareAppMessage(res){
     const shareInfo = res.target,dataset.shareInfo
}

**补充信息**

**Comment by Chen-jj** [comment]
@zhangxuyangAwesome 复现不了

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Counter from '../../components/counter/counter'

export default class Index extends Component {
  onShareAppMessage (res) {
    console.log('onShareAppMessage: ', res)
    return {}
  }
  render () {
    return (
      <View>
        <Counter></Counter>
      </View>
    )
  }
}
```

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Button } from '@tarojs/components'

export default class Index extends Component {
  state = {
    shareInfo: {
      str: 'xx'
    }
  }

  handleClick () {}

  render () {
    return (
      <View>
        <Button
          openType="share"
          data-share-info={this.state.shareInfo}
          onContact={this.handleClick.bind(this)}
          onError={this.handleClick.bind(this)}
          onGetPhoneNumber={this.handleClick.bind(this)}
          onGetUserInfo={this.handleClick.bind(this)}
          onOpenSetting={this.handleClick.bind(this)}
        >
          分享
        </Button>
      </View>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/73902543-20919d00-48d1-11ea-868d-5f02e317f50a.png)

**Comment by zhangxuyangAwesome** [comment]
![image](https://user-images.githubusercontent.com/52990953/74698629-82d78f80-5239-11ea-9235-8d6011d87613.png)
` //组件中的按钮 
<AtButton
                size="small"
                type="secondary"
                openType="share"
                data-share-info={item}
                disabled={false}
              >
                分享
              </AtButton>`
`
// 父页面分享
 onShareAppMessage(res) {
    console.log(res);
    return {};
  }
`
