### ISSUE TITLE
Taro.uploadFile返回的uploadTask没有headersReceive方法

### ISSUE THREAD

**Issue by casatwy** [NervJS/taro#5407]
### 问题描述

Taro.uploadFile返回的uploadTask没有headersReceive方法

js文件中：

```typescript

const uploadTask = Taro.uploadFile({
  url:"http://this.is.test/upload/url",
  filePath:"/test/file/path",
  name:"test",
  formData:{ test:"data" },
  success: (res) => { console.log(res) },
  fail: (res) => { console.log(res) },
  complete: (res) => { console.log(res) },
})

console.log(uploadTask)
```

调试器中打印uploadTask:

![截屏2020-02-03下午1 50 51](https://user-images.githubusercontent.com/1005781/73629080-02d3f600-468d-11ea-9b38-cb745ceaae1e.png)

### 期望行为

按照文档的来，应该要有headersReceive方法的，正好要用到

[https://nervjs.github.io/taro/docs/apis/network/fileTransfer/uploadFile.html#promise-lt-object-res-gt-promise](https://nervjs.github.io/taro/docs/apis/network/fileTransfer/uploadFile.html#promise-lt-object-res-gt-promise)

### 系统信息

👽 Taro v2.0.2

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      npm: 6.13.7 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.6.2

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro/blob/2.x/packages/taro-weapp/src/native-api.js#L170-L186
