### ISSUE TITLE
[Feature Request]增加配置项，用于声明某些css/scss文件编译成单独的wxss/css

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#541]
有些项目，为了方便会抽象出很多组件。然后这些业务组件一般会依赖一些自有的或第三方样式，如iconfont和weui。现在taro是js里import了样式文件就直接合并，最终会导致组件的体积十分庞大。

建议：
1. 增加配置项，用于声明某些css/scss文件编译成单独的wxss/css
2. 在上面配置项中的样式不合并，而是@import引入

**Comment by luckyadam** [comment]
这个正在优化~

**Comment by tourze** [comment]
update

**Comment by qwIvan** [comment]
这是已经解决了还是？

**Comment by Chen-jj** [comment]
Taro2、3 能够将公共样式抽离了

**Comment by elon-hu** [comment]
@Chen-jj 这个问题2.2.14还有吗？我现在用默认的配置，还是合并打包了
