### ISSUE TITLE
h5端引入 taro-f2 F2Canvas 导致页面不跳转

### ISSUE THREAD

**Issue by JTXS** [NervJS/taro#5410]
### 问题描述

页面A引入 taro-f2 的 F2Canvas 后，使用 Taro.navigateTo 无法跳转到页面B。
不过浏览器地址变了，并且只会变为hash模式的地址，无法变为browser模式的地址（config/index.js配置了h5 router mode 是 browser）。

```js
import { F2Canvas } from "taro-f2";
// xxxx
const goToDetailPage = () => {
  Taro.navigateTo({
    url: "/pages/detail/index"
  });
};
// xxxx
<Button onClick={goToDetailPage}>查看详情</Button>
<View style='width:100%; height:500px'>
  <F2Canvas onCanvasInit={drawRadar} />
</View>
```

### 期望行为

页面跳转正常，无论是hash模式还是browser模式。

### 报错信息

无报错信息

### 系统信息

Taro v2.0.2
  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2 
      @tarojs/components-qa: 2.0.2 => 2.0.2 
      @tarojs/mini-runner: 2.0.2 => 2.0.2 
      @tarojs/mobx: 2.0.2 => 2.0.2 
      @tarojs/mobx-h5: 2.0.2 => 2.0.2 
      @tarojs/router: 2.0.2 => 2.0.2 
      @tarojs/taro: 2.0.2 => 2.0.2 
      @tarojs/taro-alipay: 2.0.2 => 2.0.2 
      @tarojs/taro-h5: 2.0.2 => 2.0.2 
      @tarojs/taro-qq: 2.0.2 => 2.0.2 
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2 
      @tarojs/taro-swan: 2.0.2 => 2.0.2 
      @tarojs/taro-tt: 2.0.2 => 2.0.2 
      @tarojs/taro-weapp: 2.0.2 => 2.0.2 
      @tarojs/webpack-runner: 2.0.2 => 2.0.2 
      eslint-config-taro: 2.0.2 => 2.0.2 
      eslint-plugin-taro: 2.0.2 => 2.0.2 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.2 => 2.0.2 
      stylelint-taro-rn: 2.0.2 => 2.0.2

### 补充信息

问题应该出在 node_modules/taro-f2/dist/h5/index.js 这个文件，其中有关于路由的代码。
此文件代码如下：
<img width="543" alt="WX20200203-155224@2x" src="https://user-images.githubusercontent.com/7038744/73634920-446c9d00-469d-11ea-8f81-78f652c6e666.png">

**Comment by Garfield550** [comment]
Taro F2 不是 Taro 项目里的一部分，可能需要去框架作者那边提一下问题？

**Comment by JTXS** [comment]
> Taro F2 不是 Taro 项目里的一部分，可能需要去框架作者那边提一下问题？

👌

**Comment by lechenging** [comment]
@JTXS 看这里我的方案 
https://github.com/xioxin/taro-f2/issues/40
