### ISSUE TITLE
微信小程序插件项目，开发时，提示Cannot read property 'dispatch' of null

### ISSUE THREAD

**Issue by hangaoke1** [NervJS/taro#5411]
### 问题描述
微信小程序插件项目升级后，出现问题，从版本1.3.2升级到2.0.2

### 复现步骤

1.  (复现源代码)[https://github.com/hangaoke1/taro-issue1]
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息

![image](https://user-images.githubusercontent.com/19623160/73649698-51988480-46bb-11ea-8225-0b33c63fc67c.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
plugin 目录重复生成的问题已经修复，至于这个报错是因为在页面使用了 redux，但是没有调用 Provider 传入 store，常规 Taro 代码中这个操作是在 app.js 里做的， 但是小程序插件的每个页面都是独立的，不像正常小程序一样有一个统一的入口，所以如果你要使用 redux，就在页面里用 Provider 传入 store，但是正如这里说的，每个页面都独立，那也没有使用 redux 的必要了。

**Comment by easonzhuyi** [comment]
遇到了同样的问题，plugin下的components connect store为null，还没有跳转到插件页面就报错了，
connect中getStore为null，在plugin/pages/index中注入的provider

**Comment by easonzhuyi** [comment]
发现plugin下components中的组件代码会先于pages被执行，造成初始化读取不到store
