### ISSUE TITLE
[taro-2.0.1]--port 参数对于RN调试失效

### ISSUE THREAD

**Issue by moseszhou** [NervJS/taro#5413]
### 问题描述
	"build:rn": "npm run env:prod && ./node_modules/@tarojs/cli/bin/taro build --type rn --port 8082 --watch",
调用上面的命令无法修改debug模式的端口。

### 复现步骤

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

npm run build:rn
```

### 期望行为

能够设置rn的host server的启动端口，我查过cli的代码，rn编译启动的时候并没有把port参数传入
```
  startServerInNewWindow({ appPath});

function startServerInNewWindow({ port = 8081, appPath }) {

.......
}

```
### 系统信息

Taro v2.0.1

  Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.1 => 2.0.2 
      @tarojs/components: 2.0.1 => 2.0.0-beta.13 
      @tarojs/components-qa: 2.0.1 => 2.0.0-beta.13 
      @tarojs/components-rn: 2.0.1 => 2.0.2 
      @tarojs/mini-runner: 2.0.1 => 2.0.0-beta.13 
      @tarojs/plugin-less: 2.0.1 => 2.0.2 
      @tarojs/router: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-alipay: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-h5: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-qq: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-quickapp: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-redux-rn: 2.0.1 => 2.0.2 
      @tarojs/taro-rn: 2.0.1 => 2.0.2 
      @tarojs/taro-router-rn: 2.0.1 => 2.0.2 
      @tarojs/taro-swan: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-tt: 2.0.1 => 2.0.0-beta.13 
      @tarojs/taro-weapp: 2.0.1 => 2.0.0-beta.13 
      @tarojs/webpack-runner: 2.0.1 => 2.0.0-beta.13 
      eslint-config-taro: 2.0.1 => 2.0.0-beta.13 
      eslint-plugin-taro: 2.0.1 => 2.0.0-beta.13 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.3.1 => 16.3.1 
      react-native: 0.59.10 => 0.55.4 
      stylelint-config-taro-rn: 2.0.1 => 2.0.0-beta.13 
      stylelint-taro-rn: 2.0.1 => 2.0.0-beta.13 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
这个是给 H5 切换端口用的

**Comment by moseszhou** [comment]
> 这个是给 H5 切换端口用的

为啥不给RN也支持一下呢？ 把参数传入在cli里面把端口传入一下就好了。
我也做了cli的修改也成功切换了端口，但是修改node_moudles里面的东西不合适，就算我打一个patch，但是taro最近这升级速度..., 希望能直接从cli上进行修改，免得我每次打补丁。

我有时候需要同时开几个taro项目，以及rn项目进行调试，这个端口不能修改，就导致调试的时候只能开一个。很不方便

**Comment by shenghanqin** [comment]
1、cli最好跟本地依赖保持一致
2、如果不一致，你可以将cli想用的版本安装到本地
3、针对你的问题，可以使用npm link或yarn link的方法试试看。

特殊时期，还望谅解。

**Comment by luckyadam** [comment]
> > 这个是给 H5 切换端口用的
> 
> 为啥不给RN也支持一下呢？ 把参数传入在cli里面把端口传入一下就好了。
> 我也做了cli的修改也成功切换了端口，但是修改node_moudles里面的东西不合适，就算我打一个patch，但是taro最近这升级速度..., 希望能直接从cli上进行修改，免得我每次打补丁。
> 
> 我有时候需要同时开几个taro项目，以及rn项目进行调试，这个端口不能修改，就导致调试的时候只能开一个。很不方便

有道理，RN 也可以支持一下

**Comment by Pines-Cheng** [comment]
好的～
