### ISSUE TITLE
函数类型的props无法作为三元判断条件

### ISSUE THREAD

**Issue by DrakeXiang** [NervJS/taro#5419]
### 问题描述

函数类型的props无法用在类似 `funcProps ? <View>test</View> : null`中判断，即使funcProps有值也无法得到正确的输出

### 复现步骤

1. 创建一个有函数属性的组件，例如属性名为`onBind`
2. 传入一个函数方法
3. 在组件内部用三元表达式
4. 三元无效

```jsx
// Parent component
...
bindFunc = () => { console.log('bind') };
...
<Child onbind={this.bindFunc} />
...

// Child component
..
..
render() {
  const { onbind } = this.props;

  return (
    <View>
      {onbind ? <Text>Has bind</Text> : <Text>Has no bind</Text>}
    </View>
  )
}
```

### 期望行为

文字显示会根据是否传入`onbind`方法而改变

### 系统信息

Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.1 => 2.0.1
      @tarojs/components: 2.0.1 => 2.0.1
      @tarojs/components-qa: 2.0.1 => 2.0.1
      @tarojs/mini-runner: 2.0.1 => 2.0.1
      @tarojs/mobx: 2.0.1 => 2.0.1
      @tarojs/mobx-h5: 2.0.1 => 2.0.1
      @tarojs/plugin-babel: 2.0.1 => 2.0.1
      @tarojs/plugin-csso: 2.0.1 => 2.0.1
      @tarojs/plugin-sass: 2.0.1 => 2.0.1
      @tarojs/plugin-uglifyjs: 2.0.1 => 2.0.1
      @tarojs/router: 2.0.1 => 2.0.1
      @tarojs/taro: 2.0.1 => 2.0.1
      @tarojs/taro-alipay: 2.0.1 => 2.0.1
      @tarojs/taro-h5: 2.0.1 => 2.0.1
      @tarojs/taro-qq: 2.0.1 => 2.0.1
      @tarojs/taro-quickapp: 2.0.1 => 2.0.1
      @tarojs/taro-rn: 2.0.1 => 2.0.1
      @tarojs/taro-swan: 2.0.1 => 2.0.1
      @tarojs/taro-tt: 2.0.1 => 2.0.1
      @tarojs/taro-weapp: 2.0.1 => 2.0.1
      @tarojs/webpack-runner: 2.0.1 => 2.0.1
      eslint-config-taro: 2.0.1 => 2.0.1
      eslint-plugin-taro: 2.0.1 => 2.0.1
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.1 => 2.0.1
      stylelint-taro-rn: 2.0.1 => 2.0.1

### 补充信息

貌似是因为以`on`开头的属性会做特殊处理，如果直接传`boolean`的话编译会报错，我尝试了使用`!!onbind`或者`onbind !== undefined`来判断都不能成功。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
你先把变量解构出来试试看？ @DrakeXiang

**Comment by DrakeXiang** [comment]
> 你先把变量解构出来试试看？ @DrakeXiang

额，在我实际的代码里面是解构出来的。。。我改下问题吧

**Comment by Chen-jj** [comment]
@DrakeXiang 

在支付宝小程序也好，微信小程序也好。函数可以传递给自定义子组件，但用于渲染、判断时都是 null。

下图 onbind 做判断条件会是 null，但是可以传递给子组件。

![image](https://user-images.githubusercontent.com/11807297/73912535-b0deda80-48ef-11ea-971f-6ea41b8aea21.png)

因此你需要绕一绕，开个变量做判断条件，而不是直接使用函数本身做判断。

例如

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'

export default class Index extends Component {

  render () {
    const flag = Boolean(this.props.onbind)
    return (
      <View>
        {flag ? <Text>Has bind</Text> : <Text>Has no bind</Text>}
      </View>
    );
  }
}
```
