### ISSUE TITLE
快应用编译失败

### ISSUE THREAD

**Issue by JImumu** [NervJS/taro#5420]
### 问题描述

小程序转化为Taro后编译快应用失败

### 复现步骤

1. 进入微信小程序根目录
2. 全局安装@tarojs/cli@2.0.1，运行taro convert
3. 进入taroConvert目录后运行npm install
4. 运行npm run build:quickapp
5. 编译失败

```js
Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: unknown: Only one default export allowed per module. (120:0)
  118 | export default App;
  119 | exportRes = require('@tarojs/taro-quickapp').default.createApp(_App);
> 120 | export default exportRes;
      | ^
  121 | Taro.initPxTransform({
  122 |   "designWidth": 750,
  123 |   "deviceRatio": {


```

### 期望行为

编译成功
### 报错信息

Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: unknown: Only one default export allowed per module. (120:0)
  118 | export default App;
  119 | exportRes = require('@tarojs/taro-quickapp').default.createApp(_App);
> 120 | export default exportRes;
      | ^
  121 | Taro.initPxTransform({
  122 |   "designWidth": 750,
  123 |   "deviceRatio": {

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
请给一个 demo 看下

**Comment by JImumu** [comment]
> 请给一个 demo 看下

微信小程序代码转换成taro后的app.js里有一句export default App，删除就好了
