### ISSUE TITLE
taro2中使用lodash，编译后仍然从node_modules中引入

### ISSUE THREAD

**Issue by yyhdev** [NervJS/taro#5421]
### 问题描述

在taro2.0.2中使用lodash的debounce函数时，出现了‘Cannot read property 'now' of undefined;’

### 复现步骤

```ts
import {debounce} from 'lodash/function'

<Input
          className='input'
          placeholder='请输入商品名称'
          value={keyword}
          onInput={debounce(handleInput, 500)}
        />
```

### 期望行为

正常工作

### 报错信息

![image](https://user-images.githubusercontent.com/30213158/73830602-e62bef80-483f-11ea-9687-62a64b82fc71.png)

![image](https://user-images.githubusercontent.com/30213158/73830949-7a965200-4840-11ea-9fbd-2e67ebaebd37.png)

### 系统信息

Taro v2.0.2

 Taro CLI 2.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - D:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD

### 补充信息

查看编译后的源码时发现引入lodash的地方：var root = __webpack_require__(/*! ./_root */ "./node_modules/_lodash@4.17.15@lodash/_root.js");，仍然从node_modules中引入，猜测是编译过程出了问题

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/73853469-df1ad680-486b-11ea-801a-f667cf059a14.png)
![image](https://user-images.githubusercontent.com/1782542/73853492-e641e480-486b-11ea-9cf9-145e52b80604.png)
![image](https://user-images.githubusercontent.com/1782542/73853509-f063e300-486b-11ea-8ce5-fb41d2015db1.png)

2.0.2 版本，没有复现这个问题哇，麻烦给个 demo 看下

**Comment by yyhdev** [comment]
试下改变输入值去触发防抖呢，方法我也能正确打印出来，触发防抖的时候报错，这是事件：const handleInput = useCallback(e => setKeyword(e.detail.value), []);

**Comment by yyhdev** [comment]
试下改变输入值去触发防抖呢，方法我也能正确打印出来，触发防抖的时候报错，这是事件：const handleInput = useCallback(e =&gt; setKeyword(e.detail.value), []);




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Li,Weitao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月5日(星期三) 晚上11:05
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"YANG YU HAO"<1536165814@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] taro2中使用lodash，编译后仍然从node_modules中引入 (#5421)





 
 
 
2.0.2 版本，没有复现这个问题哇，麻烦给个 demo 看下

**Comment by hisanshao** [comment]
import debounce from 'lodash.debounce'
会报root.Date.now()的问题，主要原因是var root = freeGlobal || freeSelf || Function('return this')();这段返回的是空对象，需要把Date Array Buffer 等引进去吧。 @luckyadam

**Comment by yyhdev** [comment]
> import debounce from 'lodash.debounce'
> 会报root.Date.now()的问题，主要原因是var root = freeGlobal || freeSelf || Function('return this')();这段返回的是空对象，需要把Date Array Buffer 等引进去吧。 @luckyadam

2.0.3版本已解决

**Comment by hisanshao** [comment]
2.0.3还是有问题，我用的就是2.0.3 @yyhdev

**Comment by yyhdev** [comment]
不知道 我前两天升级到2.0.3试了下 没这问题了，你试下这样引入“import {debounce} from 'lodash/function'” @hisanshao

**Comment by hisanshao** [comment]
> 不知道 我前两天升级到2.0.3试了下 没这问题了，你试下这样引入“import {debounce} from 'lodash/function'” @hisanshao

经测试，单独安装lodash.debounce还是会报错的，只安装一个lodash不会报错 @luckyadam @yyhdev

**Comment by Przeblysk** [comment]
新版本2.1.5还是存在这个问题

**Comment by yedegesong** [comment]
Taro v3.0.7  
"lodash": "^4.17.20",

也是遇到这个问题
TypeError: Cannot read property 'now' of undefined
    at now (index.js:593)
    at FormElement.debounced (index.js:408)
    at FormElement.dispatchEvent (taro.js:4513)
    at FormElement.dispatchEvent (taro.js:4647)
    at Object.eventHandler [as eh] (taro.js:2891)

**Comment by Przeblysk** [comment]
> Taro v3.0.7
> "lodash": "^4.17.20",
> 
> 也是遇到这个问题
> TypeError: Cannot read property 'now' of undefined
> at now (index.js:593)
> at FormElement.debounced (index.js:408)
> at FormElement.dispatchEvent (taro.js:4513)
> at FormElement.dispatchEvent (taro.js:4647)
> at Object.eventHandler [as eh] (taro.js:2891)
有用七鱼的插件吗？或者是其他的插件

**Comment by Przeblysk** [comment]
> Taro v3.0.7
> "lodash": "^4.17.20",
> 
> 也是遇到这个问题
> TypeError: Cannot read property 'now' of undefined
> at now (index.js:593)
> at FormElement.debounced (index.js:408)
> at FormElement.dispatchEvent (taro.js:4513)
> at FormElement.dispatchEvent (taro.js:4647)
> at Object.eventHandler [as eh] (taro.js:2891)


有用七鱼或者其他的插件吗

**Comment by yedegesong** [comment]
> > Taro v3.0.7
> > "lodash": "^4.17.20",
> > 也是遇到这个问题
> > TypeError: Cannot read property 'now' of undefined
> > at now (index.js:593)
> > at FormElement.debounced (index.js:408)
> > at FormElement.dispatchEvent (taro.js:4513)
> > at FormElement.dispatchEvent (taro.js:4647)
> > at Object.eventHandler [as eh] (taro.js:2891)
> 
> 有用七鱼或者其他的插件吗

没用其他的插件
