### ISSUE TITLE
h5设置了 enableDll 和 dllEntry后，打包后并没有看到dll文件，打包速度也没有提升

### ISSUE THREAD

**Issue by 666doge** [NervJS/taro#5423]
### 问题描述
为了提高h5打包速度，设置了 enableDll 和 dllEntry，但打包后并没有看到dll文件，打包速度也没有提升。

### 复现步骤

1. 如下图添加了dll相关的配置。
2.  打包，执行 npm run build:h5
3.  现象是：再次打包，打包耗时没有变短，没有看到dll文件， dllWebpackChain处也没有打印出 123，

![image](https://user-images.githubusercontent.com/13286024/73917399-4c754880-48fa-11ea-82a8-81fe5a2253de.png)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

再次打包，看到打包耗时变短，看到dll文件。

### 报错信息

无报错信息

### 系统信息

Taro CLI 2.0.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v8.10.0/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.2 => 2.0.2 
      @tarojs/components: 2.0.2 => 2.0.2 
      @tarojs/mini-runner: ^2.0.2 => 2.0.2 
      @tarojs/plugin-babel: 2.0.2 => 2.0.2 
      @tarojs/plugin-csso: 2.0.2 => 2.0.2 
      @tarojs/plugin-sass: 2.0.2 => 2.0.2 
      @tarojs/plugin-uglifyjs: 2.0.2 => 2.0.2 
      @tarojs/router: 2.0.2 => 2.0.2 
      @tarojs/taro: 2.0.2 => 2.0.2 
      @tarojs/taro-alipay: 2.0.2 => 2.0.2 
      @tarojs/taro-h5: 2.0.2 => 2.0.2 
      @tarojs/taro-swan: 2.0.2 => 2.0.2 
      @tarojs/taro-tt: 2.0.2 => 2.0.2 
      @tarojs/taro-weapp: 2.0.2 => 2.0.2 
      @tarojs/webpack-runner: 2.0.2 => 2.0.2 
      eslint-config-taro: 2.0.2 => 2.0.2 
      eslint-plugin-taro: 2.0.2 => 2.0.2 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
    npmGlobalPackages:
      typescript: 3.5.2

### 补充信息

或者是否有其他方式，可以提高打包速度。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
1.3版本后，dll功能已经去除，文档更新不及时，抱歉。
