### ISSUE TITLE
传入函数式自定义组件的事件 无法触发

### ISSUE THREAD

**Issue by afishhhhh** [NervJS/taro#5425]
### 问题描述

微信小程序端父组件传入到子组件的事件函数没有触发。

### 复现步骤
```js
// item.jsx
export default function Item ({ prop1, prop2, onTap }) {
  return <View onClick={onTap}><Text>{prop1}</Text></View>
}
// index.jsx
export default class Index extends Component {
  handleTap () {
    console.log('tapped')
  }

  render () {
    return (
      <View className='content'>
        <View className='list'>
          {items.map(el => (
            <Item {...el} key={el.elId} onTap={this.handleTap} />
          ))}
        </View>
      </View>
    )
  }
}
```
当我点击 Item 的时候，handleTap 没有被触发

### 期望行为

点击 Item 的时候，handleTap 被触发

### 系统信息

Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2 
      @tarojs/components-qa: 2.0.2 => 2.0.2 
      @tarojs/mini-runner: 2.0.2 => 2.0.2 
      @tarojs/router: 2.0.2 => 2.0.2 
      @tarojs/taro: 2.0.2 => 2.0.2 
      @tarojs/taro-alipay: 2.0.2 => 2.0.2 
      @tarojs/taro-h5: 2.0.2 => 2.0.2 
      @tarojs/taro-qq: 2.0.2 => 2.0.2 
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2 
      @tarojs/taro-rn: 2.0.2 => 2.0.2 
      @tarojs/taro-swan: 2.0.2 => 2.0.2 
      @tarojs/taro-tt: 2.0.2 => 2.0.2 
      @tarojs/taro-weapp: 2.0.2 => 2.0.2 
      @tarojs/webpack-runner: 2.0.2 => 2.0.2 
      eslint-config-taro: 2.0.2 => 2.0.2 
      eslint-plugin-taro: 2.0.2 => 2.0.2 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.2 => 2.0.2 
      stylelint-taro-rn: 2.0.2 => 2.0.2 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
因为你写错了
![image](https://user-images.githubusercontent.com/1782542/73951993-66824b80-4939-11ea-9d83-de8bf924c93d.png)
这里 onTap 应该传入 `handleTap` 而不是 `this. handleTap`

另外，自定义组件传参暂不支持解构写法

**Comment by afishhhhh** [comment]
> 因为你写错了
> ![image](https://user-images.githubusercontent.com/1782542/73951993-66824b80-4939-11ea-9d83-de8bf924c93d.png)
> 这里 onTap 应该传入 `handleTap` 而不是 `this. handleTap`
> 
> 另外，自定义组件传参暂不支持解构写法



> 因为你写错了
> ![image](https://user-images.githubusercontent.com/1782542/73951993-66824b80-4939-11ea-9d83-de8bf924c93d.png)
> 这里 onTap 应该传入 `handleTap` 而不是 `this. handleTap`
> 
> 另外，自定义组件传参暂不支持解构写法

把 `this.handleTap` 改成 `handleTap` 的话，`handleTap` 未定义啊，编译也通不过

**Comment by Chen-jj** [comment]
@afishhhhh 复现不了

```js
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Counter from '../../components/counter/counter'

export default class Index extends Component {
  handleTap(x) {
    console.log('tapped', x)
  }

  render() {
    const items = [{
      elId: 0,
      prop1: 'a'
    }, {
      elId: 1,
      prop1: 'b'
    }]
    return (
      <View className='content'>
        <View className='list'>
          {items.map(el => (
            <Counter {...el} key={el.elId} onTap={this.handleTap.bind(this, el.prop1)} />
          ))}
        </View>
      </View>
    )
  }
}
```

```js
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'

export default function Item({ prop1, prop2, onTap }) {
  return (
    <View onClick={onTap}>
      <Text>{prop1}</Text>
    </View>
  );
}
```

![image](https://user-images.githubusercontent.com/11807297/73997933-e2f94680-499a-11ea-9981-ec7d181ed227.png)
