### ISSUE TITLE
函数式组件如何访问组件实例 

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#5426]
### 问题描述

自定义函数式组件操作 canvas ，createCanvasContext 需要传入当前组件实例的 this，请问该如何操作

**Comment by luckyadam** [comment]
用 useScope 这个 Hooks

**Comment by youngluo** [comment]
> ```js
> useScope
> ```

ok ，文档没有呢

**Comment by Chen-jj** [comment]
[cd218243](https://github.com/NervJS/taro/commit/cd218243732dd54e9999aa3e484e305de9a3cb9b)

**Comment by shaodushu** [comment]
3.x 是否也能支持一下useScope()
