### ISSUE TITLE
linux上创建项目失败，因权限问题

### ISSUE THREAD

**Issue by coco-5** [NervJS/taro#5427]
node:3559) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@tarojs/cli/templates/taro-temp'
(node:3559) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3559) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by luckyadam** [comment]
用 sudo 吧，或者 nvm 来管理你的 node

**Comment by ispiders** [comment]
我觉得这是个很严重的bug，居然总是见到让用sudo运行的建议，sudo运行的结果就是创建的项目当前用户又没有权限。

**Comment by chao921125** [comment]
mac 同样出现问题，最新并没有解决该问题。希望jd的同学解决一下，并不是多么难的bug。
sudo taro init myApp
