### ISSUE TITLE
引入阿里icon报错

### ISSUE THREAD

**Issue by FIWE2030** [NervJS/taro#5428]
### 
![image](https://user-images.githubusercontent.com/21697518/73967218-722e3c00-4952-11ea-8a66-5012bb16b4d7.png)
![image](https://user-images.githubusercontent.com/21697518/73967307-9b4ecc80-4952-11ea-8119-1eb43f12c03e.png)

### 期望行为

网上都是这种引入的，但是都没说有错，我本地一直启动不成功，感觉路径也没毛病啊
### 报错信息

ModuleNotFoundError: Module not found: Error: Can't resolve './iconfont.eot?t=1581013633861' in 'D:\项目...‘
### 系统信息

window操作系统，vscode编辑器，微信开发者工具，taro2.0

**Comment by yuwanlin** [comment]
这个我提过issue https://github.com/NervJS/taro/issues/5276#issue-547234832
