### ISSUE TITLE
Taro.previewImage 点击返回键的时候 预览图片没有关掉

### ISSUE THREAD

**Issue by youyou0101** [NervJS/taro#5430]
### 问题描述

Taro.previewImage预览图片 点击返回键的时候 预览图片没有关掉 页面返回了

### 复现步骤

1. 点击图片预览
2. 点击底部返回
3. 页面返回，预览图片还在

### 期望行为

当预览图片时，点击页面返回，预览图片关闭，页面返回。

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
same as #4069
