### ISSUE TITLE
使用defineConstants定义的常量判断，不能移除引入的文件

### ISSUE THREAD

**Issue by xn330125** [NervJS/taro#5431]
### 问题描述

使用 defineConstants 定义常量，在代码中根据这个常量来决定引入哪个文件，但是打包后，没有去除引入的文件。但是使用 process.env.TARO_ENV 判断是可以移除的。

### 复现步骤

配置常量
```
defineConstants: {
    __WEAPP__: JSON.stringify(true)
}
```

使用下面代码，打包后 a.js 和 b.js 文件都会被引入进来，但是将 `__WEAPP__` 替换成 `process.env.TARO_ENV === 'weapp'` 就可以将 b.js 去除。
```js
import a from "./a";
import b from "./b";

if (__WEAPP__) {
      a();
} else {
      b();
}
```

### 期望行为

defineConstants 也可以移除代码

### 系统信息
👽 Taro v2.0.2

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2 
      @tarojs/components-qa: 2.0.2 => 2.0.2 
      @tarojs/mini-runner: 2.0.2 => 2.0.2 
      @tarojs/mobx: 2.0.2 => 2.0.2 
      @tarojs/mobx-h5: 2.0.2 => 2.0.2 
      @tarojs/router: 2.0.2 => 2.0.2 
      @tarojs/taro: 2.0.2 => 2.0.2 
      @tarojs/taro-alipay: 2.0.2 => 2.0.2 
      @tarojs/taro-h5: 2.0.2 => 2.0.2 
      @tarojs/taro-qq: 2.0.2 => 2.0.2 
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2 
      @tarojs/taro-swan: 2.0.2 => 2.0.2 
      @tarojs/taro-tt: 2.0.2 => 2.0.2 
      @tarojs/taro-weapp: 2.0.2 => 2.0.2 
      @tarojs/webpack-runner: 2.0.2 => 2.0.2 
      eslint-config-taro: 2.0.2 => 2.0.2 
      eslint-plugin-taro: 2.0.2 => 2.0.2 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.2 => 2.0.2 
      stylelint-taro-rn: 2.0.2 => 2.0.2 
    npmGlobalPackages:
      typescript: 3.7.5

**Comment by Chen-jj** [comment]
@xn330125 defineConstants 等同于 Webpack DefinePlugin，只是 webpack 打包时替换掉你的变量为对应内容，不用处处 require 来使用而已。并没有条件编译的功能。条件编译用 process.env.TARO_ENV 吧。

**Comment by xn330125** [comment]
> @xn330125 defineConstants 等同于 Webpack DefinePlugin，只是 webpack 打包时替换掉你的变量为对应内容，不用处处 require 来使用而已。并没有条件编译的功能。条件编译用 process.env.TARO_ENV 吧。

因为在Taro 1.3 里面用 defineConstants 是可以做到条件编译的，项目里面好多地方都用到了这个。而且普通webpack项目里面的DefinePlugin插件也可以条件编译，所以不太明白为什么Taro采用webpack后反而不行了

**Comment by tourze** [comment]
同问这个问题

**Comment by blockdate** [comment]
你得类似
{
defineConstants:{
__WEAPPP__: '1'
}
}

if (__WEAPP__ === '1'){
}

这种情况下编译的时候替换成 if (‘1’ === '1') => if(true){} 才会条件编译。
JSON.stringfy === xx 这种不会被优化
