### ISSUE TITLE
taro中npm 引入很多依赖，导致打包后主包过大，如何解决？

### ISSUE THREAD

**Issue by zhilianbi520** [NervJS/taro#5432]
### 问题描述

使用taro开发小程序，已进行分包处理，但是由于npm引入很多依赖(无法删减)，导致主包过大。

### 复现步骤
无

### 期望行为
可以有配置项提取依赖，或者能够对npm多个依赖采用分包处理。不将npm引入的依赖都打入到主包中

### 报错信息
无

### 补充信息
原生微信小程序中可采用云函数执行安装依赖，云函数执行的依赖不会被打入到主包中，是否有借鉴的意义。

**Comment by luckyadam** [comment]
这确实是个问题，之前有考虑过进行依赖分析，将非主包引用的 npm 打包到子包中，但实现起来有些麻烦，不过可以进行尝试

而问题中提到「原生微信小程序中可采用云函数执行安装依赖，云函数执行的依赖不会被打入到主包中」请问是怎样的操作，请提供一下相关的介绍，我们看下

**Comment by zhilianbi520** [comment]
> 这确实是个问题，之前有考虑过进行依赖分析，将非主包引用的 npm 打包到子包中，但实现起来有些麻烦，不过可以进行尝试
> 
> 而问题中提到「原生微信小程序中可采用云函数执行安装依赖，云函数执行的依赖不会被打入到主包中」请问是怎样的操作，请提供一下相关的介绍，我们看下

@luckyadam https://developers.weixin.qq.com/community/develop/doc/00022e56fb0ce0a43b7973c9a50800?highLine=npm%2520%25E5%2588%2586%25E5%258C%2585
https://developers.weixin.qq.com/community/develop/doc/0000cc05b7c530f7708963d1f51800?highLine=%25E4%25BA%2591%25E5%2587%25BD%25E6%2595%25B0%2520npm
根据以上链接看到这样的处理方案～·

**Comment by gjc9620** [comment]
请问这个问题有解决吗

**Comment by Chen-jj** [comment]
webpack spiltchunk + taro [addChunkPages](https://taro-docs.jd.com/taro/docs/next/config-detail#miniaddchunkpages)
