### ISSUE TITLE
taro 支持svg吗

### ISSUE THREAD

**Issue by zhidali** [NervJS/taro#5435]
项目中需要用到动态svg 来绘制图标。 请问taro 支持svg吗

**Comment by luckyadam** [comment]
支持

**Comment by zhidali** [comment]
怎样在taro中使用svg呢， 现在遇到的需求是要用svg 绘制一个动态图标。
但是 暂未找到 taro支持svg的方法

**Comment by shenghanqin** [comment]
你可以先搜搜，微信原生小程序如何支持svg，再看taro的

**Comment by shenghanqin** [comment]
[今天，小程序正式支持 SVG](https://juejin.im/post/5cb7d7e4e51d456e51614a8e)

**Comment by zhidali** [comment]
但是我并没有找到taro支持svg的方法，  可以告诉我一下。 
在taro中怎么书写svg吗？  
🙏

**Comment by Songkeys** [comment]
同问。
related: https://github.com/NervJS/taro/issues/3013

**Comment by coder-live** [comment]
有没有使用 taro 使用 cax 画 svg 的模板
