### ISSUE TITLE
copy 配置 找不到对应文件

### ISSUE THREAD

**Issue by zhidali** [NervJS/taro#5436]
![E1559B7F-55CA-4031-9791-4095F5C4C70F](https://user-images.githubusercontent.com/46236834/74107106-a0f12000-4ba7-11ea-88ec-d1c56e9746f3.png)

![4E80CD07-F7D8-43E4-8607-1A92B2A022DF](https://user-images.githubusercontent.com/46236834/74107112-b0706900-4ba7-11ea-97b5-f474166ac7cd.png)

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/74118011-b2144e00-4bf4-11ea-93ab-9925d0fd03cc.png)
assets
