### ISSUE TITLE
微信小程序编译时报错ReferenceError: Unknown plugin "transform-inline-environment-variables" specified in...

### ISSUE THREAD

**Issue by yingying0824** [NervJS/taro#5437]
tarojs/cli1.3.17版本执行命令yarn dev:weapp或npm run dev:weapp时报错：
ReferenceError: Unknown plugin "transform-inline-environment-variables" specified in "/Users/gaozhiying/Project/.babelrc" at 0, attempted to resolve relative to "/Users/gaozhiying/Project"

**Comment by Garfield550** [comment]
https://www.npmjs.com/package/babel-plugin-transform-inline-environment-variables

`npm install babel-plugin-transform-inline-environment-variables --save-dev`

**Comment by luckyadam** [comment]
把 .babelrc 删掉吧
