### ISSUE TITLE
使用map遍历生成模板时，模板元素使用bind做事件处理，额外参数传入对象字面量包含map对象的成员，会报参数not defined

### ISSUE THREAD

**Issue by Andrewuetyang** [NervJS/taro#5440]
### 问题描述

在render函数中，使用map遍历生成模板时，模板元素使用bind做事件处理函数绑定，额外参数传入对象字面量（属性有map对象的成员属性），运行时在微信和支付宝小程序上，都会报map方法回调的参数not defined

### 复现关键代码示例

```js
render() {
  const testArr = [1, 2, 3];
  const btnArr = testArr.map((item, idx) => (
    <Button onClick={this.clickHandler.bind(this, {
      attr1: idx + 1,
      attr2: item,
      attr3: 'foo'
    })}>按钮</Button>
  ))
  return (
    <View>
      { btnArr }
    </View>
 )
}



```

### 期望行为

在map生成模板时，子元素可以通过bind正常绑定，可以传入含map回调参数的对象

### 报错信息

<img width="733" alt="错误信息图" src="https://user-images.githubusercontent.com/22719906/74221952-34cd0400-4cee-11ea-9e44-60d1eee5b9b2.png">
<img width="427" alt="错误代码图" src="https://user-images.githubusercontent.com/22719906/74221960-3d253f00-4cee-11ea-88b1-2d5cff39fbde.png">

### 系统信息

Taro v1.3.25

  Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
    npmPackages:
      @tarojs/async-await: ^1.3.25 => 1.3.25 
      @tarojs/components: 1.3.25 => 1.3.25 
      @tarojs/plugin-babel: ^1.3.25 => 1.3.25 
      @tarojs/plugin-csso: 1.3.25 => 1.3.25 
      @tarojs/plugin-sass: ^1.3.25 => 1.3.25 
      @tarojs/plugin-uglifyjs: 1.3.25 => 1.3.25 
      @tarojs/redux: ^1.3.25 => 1.3.25 
      @tarojs/redux-h5: 1.3.25 => 1.3.25 
      @tarojs/router: 1.3.25 => 1.3.25 
      @tarojs/taro: 1.3.25 => 1.3.25 
      @tarojs/taro-alipay: ^1.3.25 => 1.3.25 
      @tarojs/taro-h5: 1.3.25 => 1.3.25 
      @tarojs/taro-swan: 1.3.25 => 1.3.25 
      @tarojs/taro-tt: 1.3.25 => 1.3.25 
      @tarojs/taro-weapp: 1.3.25 => 1.3.25 
      @tarojs/webpack-runner: 1.3.25 => 1.3.25 
      eslint-config-taro: 1.3.25 => 1.3.25 
      eslint-plugin-taro: 1.3.25 => 1.3.25 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6

**Comment by shenghanqin** [comment]
首先，1.3.25是存在bug的版本，建议升级到最新版本。
其次，这个问题，你把参数解构试试看？不行再继续追问哟。

**Comment by Andrewuetyang** [comment]
> 首先，1.3.25是存在bug的版本，建议升级到最新版本。
> 其次，这个问题，你把参数解构试试看？不行再继续追问哟。

升级到2.0.2是没有问题。
参数解构，不知道你说的是事件处理函数做解构，还是传参是逐个传递。如果是前者，目前就是解构获取参数的。后者逐个传递参数是不存在这个问题。

**Comment by Andrewuetyang** [comment]
编译估计有问题，可hack处理这种情况。方法：不使用对象字面量直接传参，而是声明一个空对象变量，然后在空对象上动态绑定属性，bind传递这个对象变量参数，就不会报错了。
