### ISSUE TITLE
自定义基类继承 Taro.PureComponent 存在问题

### ISSUE THREAD

**Issue by LyunKi** [NervJS/taro#5446]
### 问题描述
我希望定义一个基类LocalComponent继承自 Taro.PureComponent，让所有 Pages下的 class 继承 LocalComponent<P,S>,从而实现在所有页面的 componentDidShow 时根据当前语言切换页面标题。但是实际使用中存在很多问题。

### 复现步骤
 1.  LocalComponent类不能放在 src/components文件夹下
a. 将LocalComponent放在 components下，并通过 index 导出，在部分页面引用时出现 `Component is not found in path "components/product-swiper/index" `.但能确定这个组件是正常的。
b. 把出现问题时的页面在 app.tsx中注释掉，并重启微信开发者工具，问题消失。
 2. 将LocalComponent类放在 src/pages文件夹下,程序能在微信中正常运行在支付宝中无法编译通过
a. 在 Cart，ProductDetail 两个 pages 页面中继承LocalComponent类
b. Cart中只放了简单的内容 ，ProductDetail中正常书写业务代码，生成的 dist /weapp和 dist/alipay的 pages 中的 product-details/index.*xml存在如下内容`<import src="../local-component/index.wxml" />`(奇怪的是 axml 中也有 wxml???)
c. 微信中报了` Path ../local-component/index.wxml not found from ./pages/product-detail/index.wxml`的警告，但不影响程序运行
d. 支付宝中编译报错 ，无法运行，手动删除 /dist/.../pages 中的`<import src="../local-component/index.wxml" />`后能够正常运行
3. 为何同样继承自LocalComponent类，部分 生成的wxml 出现`<import src="../local-component/index.wxml" />`部分不出现呢。

### 期望行为

自定义基类在 alipay 和 weapp 中都正常使用

### 报错信息
微信中
```
./pages/product-detail/index.wxml
 Path `../local-component/index.wxml` not found from `./pages/product-detail/index.wxml`.
> 1 | <import src="../local-component/index.wxml" />
    | ^
  2 | <block wx:if="{{$taroCompReady}}">
  3 |     <view class="product-detail">
  4 |         <product-swiper compid="{{$compid__30}}"></product-swiper>
```
支付宝中
```
/pages/local-component/index.axml not exist(生成的目录下确实没有对应的 local-compoent)
```

## 系统信息
```

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.2 => 2.0.2 
      @tarojs/cli: 2.0.2 => 2.0.2 
      @tarojs/components: 2.0.2 => 2.0.2 
      @tarojs/mini-runner: ^2.0.2 => 2.0.2 
      @tarojs/mobx: 2.0.2 => 2.0.2 
      @tarojs/mobx-h5: 2.0.2 => 2.0.2 
      @tarojs/plugin-babel: 2.0.2 => 2.0.2 
      @tarojs/plugin-csso: 2.0.2 => 2.0.2 
      @tarojs/plugin-sass: 2.0.2 => 2.0.2 
      @tarojs/plugin-uglifyjs: 2.0.2 => 2.0.2 
      @tarojs/router: 2.0.2 => 2.0.2 
      @tarojs/taro: 2.0.2 => 2.0.2 
      @tarojs/taro-alipay: 2.0.2 => 2.0.2 
      @tarojs/taro-h5: 2.0.2 => 2.0.2 
      @tarojs/taro-qq: 2.0.2 => 2.0.2 
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2 
      @tarojs/taro-swan: 2.0.2 => 2.0.2 
      @tarojs/taro-tt: 2.0.2 => 2.0.2 
      @tarojs/taro-weapp: 2.0.2 => 2.0.2 
      @tarojs/webpack-runner: 2.0.2 => 2.0.2 
      eslint-config-taro: 2.0.2 => 2.0.2 
      eslint-plugin-taro: 2.0.2 => 2.0.2 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.2 => 2.0.2 
      stylelint-taro-rn: 2.0.2 => 2.0.2 
    npmGlobalPackages:
      typescript: 3.7.3
```

**Comment by Chen-jj** [comment]
可以升级 Taro 3 再试试
