### ISSUE TITLE
h5 不支持 useDispatch 跟 useSelector

### ISSUE THREAD

**Issue by udbbbn** [NervJS/taro#5447]
### 问题描述

编译成 h5 不支持 useDispatch 跟 useSelector

### 复现步骤

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
几个月前就看到有人提这个 issue 。一直处于解决中 希望官方能出个时间点 或 尽快能支持。

### 报错信息

" '@tarojs/redux-h5' does not contain an export named 'useDispatch'.
" '@tarojs/redux-h5' does not contain an export named 'useSelector'.

### 系统信息

👽 Taro v1.3.35

  Taro CLI 1.3.35 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.35 => 1.3.35
      @tarojs/components: 1.3.35 => 1.3.35
      @tarojs/plugin-babel: 1.3.35 => 1.3.35
      @tarojs/plugin-csso: 1.3.35 => 1.3.35
      @tarojs/plugin-sass: 1.3.35 => 1.3.35
      @tarojs/plugin-uglifyjs: 1.3.35 => 1.3.35
      @tarojs/redux: 1.3.35 => 1.3.35
      @tarojs/redux-h5: 1.3.35 => 1.3.35
      @tarojs/router: 1.3.35 => 1.3.35
      @tarojs/taro: 1.3.35 => 1.3.35
      @tarojs/taro-alipay: 1.3.35 => 1.3.35
      @tarojs/taro-h5: 1.3.35 => 1.3.35
      @tarojs/taro-swan: 1.3.35 => 1.3.35
      @tarojs/taro-tt: 1.3.35 => 1.3.35
      @tarojs/taro-weapp: 1.3.35 => 1.3.35
      @tarojs/webpack-runner: 1.3.35 => 1.3.35
      eslint-config-taro: 1.3.35 => 1.3.35
      eslint-plugin-taro: 1.3.35 => 1.3.35
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 1.3.35 => 1.3.35
      stylelint-taro-rn: 1.3.35 => 1.3.35

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
其实你可以继续跟进，小程序支持react hooks，但h5版本好像还不齐全。

当然我基本上只用了普通写法，很少使用hooks的。

**Comment by udbbbn** [comment]
> 其实你可以继续跟进，小程序支持 react hooks，但 h5 版本好像还不齐全。
> 
> 当然我基本上只用了普通写法，很少使用 hooks 的。

是的 小程序是支持的。在 h5 中 目前我也只发现 这两个 hooks 不支持

**Comment by luckyadam** [comment]
正在支持

**Comment by udbbbn** [comment]
> 正在支持

好的 辛苦了。若完成支持请通知一下谢谢。

**Comment by mrTangYun** [comment]
2.0.5 仍然未支持

**Comment by hytaleme** [comment]
还是没有支持吗?

**Comment by hzcdt** [comment]
2.0.6 依然未支持

**Comment by Link-X** [comment]
不打算支持吗！

**Comment by jimizai** [comment]
2.2.3 依然未支持

**Comment by hellojqk** [comment]
https://nervjs.github.io/taro/docs/redux 大哥，文档页面说一下，不然踩坑踩半天

**Comment by Jinxhao18** [comment]
2.2.6依然未支持，不知道3.0支持不

**Comment by vdfor** [comment]
等3.0支持吧，3.0不需要@tarojs/redux了，直接用react-redux

**Comment by ywenhao** [comment]
2.2.6 h5不支持

**Comment by xiolng** [comment]
2.2.7不支持

**Comment by seiwhale** [comment]
2.2.9 h5不支持

**Comment by Chen-jj** [comment]
Taro 3.0 可以直接用 `react-redux`

**Comment by ShaoGongBra** [comment]
2.2.17不支持
