### ISSUE TITLE
启动和编译h5报错

### ISSUE THREAD

**Issue by DULANGHAI** [NervJS/taro#5448]
### 问题描述

yarn dev:h5 或者 yarn build:h5 报编译错误，之前是正常的，今天本地yarn cache clean后发现报错

### 复现步骤

1. 控制台yarn dev:h5
2. 看到报错
![image](https://user-images.githubusercontent.com/14758859/74320238-3d3f4080-4dbb-11ea-85c5-a8097afeee4a.png)

编译后的app.js
```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

import '@tarojs/async-await';
import Taro, { Component } from "@tarojs/taro-h5";
import { Provider } from "@tarojs/redux-h5";

import configStore from "./store/index";
import config from './utils/config';


import './app.less';

// 如果需要在 h5 环境中开启 React Devtools
// 取消以下注释：
// if (process.env.NODE_ENV !== 'production' && process.env.TARO_ENV === 'h5')  {
//   require('nerv-devtools')
// }

import Nerv from 'nervjs';
import { Router, createHistory, mountApis } from '@tarojs/router';
Taro.initPxTransform({
  "designWidth": 750,
  "deviceRatio": {
    "640": 1.17,
    "750": 1,
    "828": 0.905
  }
});

const _taroHistory = createHistory({
  mode: "browser",
  basename: "/",
  customRoutes: {},
  firstPagePath: "/pages/home/index"
});

mountApis({
  "basename": "/",
  "customRoutes": {}
}, _taroHistory);
const store = configStore();
class App extends Component {

  componentDidMount() {
    if (/test|uat/.test(config.env)) {
      // loadThirdPartyScript('//static.zhongan.com/website/assets/libs/plugins/vConsole/vconsole.min.js', () => {
      //   let vConsole = new VConsole();
      //   console.log('vconsole loaded')
      // }) 
    }
  }

  config = {
    pages: ["/pages/home/index", "/pages/fun/index", "/pages/prizePreview/index"],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    },
    subPackages: [{
      'root': 'pages/fun',
      'pages': ["/index"]
    }],
    functionalPages: true,
    debug: true
  };

  componentDidShow() {}

  componentDidHide() {}

  componentDidCatchError() {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Provider store={store}>
          
                <Router mode={"browser"} history={_taroHistory} routes={[{
        path: '/pages/home/index',
        componentLoader: () => import( /* webpackChunkName: "home_index" */'./pages/home/index'),
        isIndex: true
      }, {
        path: '/pages/fun/index',
        componentLoader: () => import( /* webpackChunkName: "fun_index" */'./pages/fun/index'),
        isIndex: false
      }, {
        path: '/pages/prizePreview/index',
        componentLoader: () => import( /* webpackChunkName: "prizePreview_index" */'./pages/prizePreview/index'),
        isIndex: false
      }, {
        path: '/pages/fun/index',
        componentLoader: () => import( /* webpackChunkName: "fun_index" */'./pages/fun/index'),
        isIndex: false
      }]} customRoutes={{}} />
                
        </Provider>;
  }

  componentWillUnmount() {
    this.componentDidHide();
  }

  constructor(props, context) {
    super(props, context);
    Taro._$app = this;
  }

}

Nerv.render(<App />, document.getElementById('app'));
```

### 期望行为

正常启动和打包

### 系统信息
![image](https://user-images.githubusercontent.com/14758859/74320530-c191c380-4dbb-11ea-9ffe-0e89323a768b.png)

👽 Taro v1.3.25

  Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.29 => 1.3.29
      @tarojs/cli: 1.3.29 => 1.3.29
      @tarojs/components: 1.3.29 => 1.3.29
      @tarojs/components-qa: 1.3.29 => 1.3.29
      @tarojs/plugin-babel: 1.3.29 => 1.3.29
      @tarojs/plugin-csso: 1.3.29 => 1.3.29
      @tarojs/plugin-less: 1.3.29 => 1.3.29
      @tarojs/plugin-uglifyjs: 1.3.29 => 1.3.29
      @tarojs/redux: 1.3.29 => 1.3.29
      @tarojs/redux-h5: 1.3.29 => 1.3.29
      @tarojs/router: 1.3.29 => 1.3.29
      @tarojs/taro: 1.3.29 => 1.3.29
      @tarojs/taro-alipay: 1.3.29 => 1.3.29
      @tarojs/taro-h5: 1.3.29 => 1.3.29
      @tarojs/taro-qq: 1.3.29 => 1.3.29
      @tarojs/taro-quickapp: 1.3.29 => 1.3.29
      @tarojs/taro-rn: 1.3.29 => 1.3.29
      @tarojs/taro-swan: 1.3.29 => 1.3.29
      @tarojs/taro-tt: 1.3.29 => 1.3.29
      @tarojs/taro-weapp: 1.3.29 => 1.3.29
      @tarojs/webpack-runner: ^2.0.3 => 2.0.3
      eslint-config-taro: 1.3.29 => 1.3.29
      eslint-plugin-taro: 1.3.29 => 1.3.29
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 1.3.29 => 1.3.29
      stylelint-taro-rn: 1.3.29 => 1.3.29
    npmGlobalPackages:
      typescript: 3.4.5

**Comment by DULANGHAI** [comment]
找到问题了，依赖被同事不小心升级了
"@tarojs/webpack-runner": "^2.0.3",
改回1.3.29就好了

**Comment by archywillhe** [comment]
taro-music 有同样问题 https://github.com/lsqy/taro-music

**Comment by Breeze1114** [comment]
> 找到问题了，依赖被同事不小心升级了
> "@tarojs/webpack-runner": "^2.0.3",
> 改回1.3.29就好了

所以升级到2.0.x版本之后报错，咋办
