### ISSUE TITLE
[Taro v3.0.0-alpha.1]npm全局安装报错Maximum call stack size exceeded，改用cnpm没问题

### ISSUE THREAD

**Issue by shenghanqin** [NervJS/taro#5449]
### 复现步骤

1. npm全局命令 `npm i -g @tarojs/cli@next`

### 期望行为

期望能有效处理Maximum call stack size exceeded的各种情况，因为别的时候全局安装或者项目启动都频繁出现类似的错误。

### 报错信息

`npm ERR! Maximum call stack size exceeded`

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
没有办法复现

**Comment by shenghanqin** [comment]
这个问题先留着吧。感觉跟本地网络环境有关系。比如我最近的github clone速度就特别慢。

**Comment by conkyliu** [comment]
我也出现了这个文体,随便敲几个空格就报错了

**Comment by conkyliu** [comment]
![image](https://user-images.githubusercontent.com/26617741/74409587-0841f500-4e72-11ea-908f-41aeb6cf1412.png)
webstorm

我也出现了这个文体,随便敲几个空格就报错了

**Comment by yuche** [comment]
@conkyliu 你试一下标准的终端有没有这个问题

**Comment by conkyliu** [comment]
> @conkyliu 你试一下标准的终端有没有这个问题

![image](https://user-images.githubusercontent.com/26617741/74411234-bf8c3b00-4e75-11ea-8844-afe3df47533d.png)
一样会

**Comment by yuche** [comment]
Duplicate of #5433
