### ISSUE TITLE
多组件嵌套时，taro与react的生命周期执行顺序有差异

### ISSUE THREAD

**Issue by ronffy** [NervJS/taro#545]
taro的生命周期跟react有一个显著差异：多组件嵌套时，taro的`componentDidMount`生命周期的执行顺序跟react正好相反，如图是taro的生命周期执行顺序：

![wechatimg1502](https://user-images.githubusercontent.com/13896347/44781819-f4d89680-abb7-11e8-9960-7f184aee8c09.jpeg)

期望：处理多组件嵌套情况时，taro与react能有相同的生命周期执行顺序。

**Comment by Simbachen** [comment]
在最新版本中，生命周期的执行顺序与React已几乎一致了
