### ISSUE TITLE
Taro@2.0.3 render开头的函数报错

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#5452]
`render() {
  return bool ? this.renderA() : this.renderB();
}`
以上这样写会报错“render开头的函数必须返回JSX...”

`render() {
  return bool ? this.renderA() : (
	<View>B<View>
  );
}`
以上这样写没问题

renderA、renderB都是按规定返回的JSX。

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
