### ISSUE TITLE
taro next 初始化新项目后编译直接报错

### ISSUE THREAD

**Issue by bigmeow** [NervJS/taro#5453]
### 问题描述
taro v3.0.0-alpha.1 在window 环境下初始化模板成功后，运行 `npm run dev:weapp`命令直接报错

### 复现步骤

1. 打开终端，按照文档初始化项目，截图见 #报错信息

2. cd 进入项目跟目录，执行 `npm run dev:weapp` 命令，直接报错：

### 期望行为

正常运行

### 报错信息
![image](https://user-images.githubusercontent.com/10484248/74414194-e3eb1600-4e7b-11ea-8d45-210298f7d92f.png)
![image](https://user-images.githubusercontent.com/10484248/74414318-23b1fd80-4e7c-11ea-9f38-32c8e6959e22.png)

### 系统信息

```
  Taro CLI 3.0.0-alpha.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
```

### 猜想问题
```
Module not found: Can't resolve 'C:project      estmyAppsrcapp.ts' in 'C:\project\test\myApp\src'
```
从报错信息来看，目录之间的`\`分隔符不见了，可能是处理路径时windows下的分隔符没有被转义？

**Comment by yuche** [comment]
看起来像是 https://github.com/NervJS/taro/commit/ef7431d7fd65788e36896dc3e69bad069e63549d 这个提交修复的内容，但目前这个提交没有应用到 next 分支。
