### ISSUE TITLE
[Taro v3.0.0-alpha.1]React hooks报错，说是跟react-dom有关

### ISSUE THREAD

**Issue by shenghanqin** [NervJS/taro#5454]
### 问题描述

在2.0版本使用的hooks是正常的，但是升级到v3.0.0 alpha 1后，就报错了。
我也按照[从旧版本迁移到 Taro Next hooks](https://taro-docs.jd.com/taro/next/docs/migration.html#hooks)修改了配置。

### 复现步骤

1.  把这个`pages/spread-game/spread-game`复制下来，打开就可以看到问题。

代码地址： https://github.com/shenghanqin/goddess-hat/blob/feature%2Fnext-react-20200213/taro/src/pages/spread-game/spread-game.js

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

期望无报错，或者告知如何修改配置。

### 报错信息

![](https://n1image.hjfile.cn/res7/2020/02/13/959d8acfd79345d40483e8cf02685821.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
React 是没办法在 Class Component 使用 hooks 的，你可以尝试换成 nerv，但也不一定可行。

**Comment by shenghanqin** [comment]
就是在v2.0.0上是OK的，到3.0就有问题。
我是还好，hooks的这个页面就是一个临时页面，但我怕社区中有大量用hooks的小伙伴会出现各种问题。麻烦给出完整的说明。感谢。

**Comment by yuche** [comment]
迁移指南会再提一下这个事，closing now
