### ISSUE TITLE
pxtransform 下的 config 能否避免 taro-ui 中的单位被转换

### ISSUE THREAD

**Issue by afishhhhh** [NervJS/taro#5456]
### 问题描述
举个例子
```js
pxtransform: {
  enable: true,
  config: {
    onePxTransform: false,
    propList: ['*', '!font-size']
  }
}
```
我想忽略 1px 和某些属性的转换，但是上面的写法会导致 taro-ui 中的也被忽略

### 期望行为

我自己写的 css 中，1px 和某些属性被忽略，但 taro-ui 中的不忽略

### 系统信息

Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.2 => 2.0.2 
      @tarojs/components-qa: 2.0.2 => 2.0.2 
      @tarojs/mini-runner: 2.0.2 => 2.0.2 
      @tarojs/router: 2.0.2 => 2.0.2 
      @tarojs/taro: 2.0.2 => 2.0.2 
      @tarojs/taro-alipay: 2.0.2 => 2.0.2 
      @tarojs/taro-h5: 2.0.2 => 2.0.2 
      @tarojs/taro-qq: 2.0.2 => 2.0.2 
      @tarojs/taro-quickapp: 2.0.2 => 2.0.2 
      @tarojs/taro-rn: 2.0.2 => 2.0.2 
      @tarojs/taro-swan: 2.0.2 => 2.0.2 
      @tarojs/taro-tt: 2.0.2 => 2.0.2 
      @tarojs/taro-weapp: 2.0.2 => 2.0.2 
      @tarojs/webpack-runner: 2.0.2 => 2.0.2 
      eslint-config-taro: 2.0.2 => 2.0.2 
      eslint-plugin-taro: 2.0.2 => 2.0.2 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.2 => 2.0.2 
      stylelint-taro-rn: 2.0.2 => 2.0.2

**Comment by DreamPWJ** [comment]
这个需求很需要

**Comment by DreamPWJ** [comment]
全局禁用pxtransform 而不是通过对于头部包含注释 /*postcss-pxtransform disable*/ 和PX等 一个一个禁用 ，实在太痛苦。好多之前的通用css不能复用还要做taro适配，而且对于大部分开发者 设计师估计不会标注设计尺寸，转换显得不是很重要

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/size.html#selectorblacklist
根据选择器规则匹配？

**Comment by DreamPWJ** [comment]
@luckyadam 非要这么麻烦吗? 开启一个全局关闭配置不是更好？

**Comment by yuxino** [comment]
``` scss
border: #{"1PX"} solid pink;
```

**Comment by afishhhhh** [comment]
> ```css-scss
> border: #{"1PX"} solid pink;
> ```

插值插了个1PX？什么意思没明白

**Comment by yuxino** [comment]
@afishhhhh taro 不是会转换单位么，我看你描述的问题是。[taro文档](https://nervjs.github.io/taro/docs/size.html#docsNav)

> 在 Taro 中尺寸单位建议使用 px、 百分比 %，Taro 默认会对所有单位进行转换。

我猜你是写了1px然后给转换掉了, 比如border写了1px就不见了。taro官方给的解决方法是最下面的

> 当前忽略单个属性的最简单的方法，就是 px 单位使用大写字母。

``` scss
 /* `px` is converted to `rem` */
.convert {
  font-size: 16px; // converted to 1rem
}

 /* `Px` or `PX` is ignored by `postcss-pxtorem` but still accepted by browsers */
.ignore {
  border: 1Px solid; // ignored
  border-width: 2PX; // ignored
}
```

但是这样还是有问题，一般前端都装了prettier，会自动把`Px`格式换成`px`对吧。但是我们可以用scss的[插值语法](https://www.sass.hk/docs/)来搞定这个事情。因为插值的字符串并不会给prettier格式化。所以就写成下面这样了。

``` scss
border: #{"1PX"} solid pink;
```

这个写法技能避免转换，也对开发人员自己来说挺明显的，而且也不用用官方的[这个特殊的选项](https://nervjs.github.io/taro/docs/size.html#onepxtransform-boolean)，首先这个选项只针对`1px`，其他的单位就要特殊处理了。如果你这么写你想写`#{“几PX”}`都可以。

@yuche @luckyadam
