### ISSUE TITLE
[Taro v3.0.0-alpha.1]新版本创建项目报错？

### ISSUE THREAD

**Issue by LadyChatterleyLover** [NervJS/taro#5459]
![image](https://user-images.githubusercontent.com/35223515/74493329-c6b25800-4f0c-11ea-8f06-96e9526127e9.png)

**Comment by yuche** [comment]
你的 taro cli 版本不对把，少了一个项目名称。和你一样的选择也能创建模板。

![image](https://user-images.githubusercontent.com/7202516/74494943-61149a80-4f11-11ea-80b2-b926a237e229.png)

**Comment by LadyChatterleyLover** [comment]
我安装官网装的最新版本，那我再看一下是不是哪里弄错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu Che"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月14日(星期五) 上午10:05
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] 新版本创建项目报错？ (#5459)




你的 taro cli 版本不对把，少了一个项目名称。和你一样的选择也能创建模板。

**Comment by LadyChatterleyLover** [comment]
我看了一下 是3.0的版本 还是报错 请问是怎么回事呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu Che"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月14日(星期五) 上午10:05
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] 新版本创建项目报错？ (#5459)




你的 taro cli 版本不对把，少了一个项目名称。和你一样的选择也能创建模板。

**Comment by Devas9** [comment]
3.0 a1 报错。 除了标准模板，其他几个都会报错

**Comment by LadyChatterleyLover** [comment]
好吧，谢谢咯，那就等官方正式发布吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Devas9"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月14日(星期五) 上午10:33
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] 新版本创建项目报错？ (#5459)




3.0 a1 报错。 除了标准模板，其他几个都会报错

**Comment by yuche** [comment]
@Devas9 @LadyChatterleyLover 
搞了一台 windows 试了下，同样的选项也没有问题：
![image](https://user-images.githubusercontent.com/7202516/74497991-22371280-4f1a-11ea-92ac-bde63f0271f0.png)


由于除了本地模板之外的模板全都托管在 GitHub，看看是不是自己访问外网有有一些问题，多尝试几次 init。

**Comment by LadyChatterleyLover** [comment]
好的 谢谢 我再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu Che"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月14日(星期五) 中午11:07
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] 新版本创建项目报错？ (#5459)




@Devas9 @LadyChatterleyLover
 搞了一台 windows 试了下，同样的选项也没有问题：
 
 
由于除了本地模板之外的模板全都托管在 GitHub，看看是不是自己访问外网有有一些问题，多尝试几次 init。

**Comment by LadyChatterleyLover** [comment]
试了很多次 还是不行 而且我用mac一样的是报这个错 不知道是不是我哪里操作错了 但不应该啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu Che"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月14日(星期五) 中午11:07
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"丶从头喜欢你"<285258675@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] 新版本创建项目报错？ (#5459)




@Devas9 @LadyChatterleyLover
 搞了一台 windows 试了下，同样的选项也没有问题：
 
 
由于除了本地模板之外的模板全都托管在 GitHub，看看是不是自己访问外网有有一些问题，多尝试几次 init。

**Comment by LadyChatterleyLover** [comment]
现在项目可以创建 但是不能按照vuex 按照vuex就会报错

**Comment by admiao** [comment]
大大大爱

**Comment by vinurs** [comment]
选react也是报一样的错误，这个错误已经提交过了，但是貌似没有查到原因

**Comment by yuche** [comment]
try 3.0.0-alpha.5

**Comment by vinurs** [comment]
alpha.5 还是一样的问题，蛮困惑的

**Comment by yuche** [comment]
> alpha.5 还是一样的问题，蛮困惑的

重装一下，如果你用 cnpm 就要等等他同步
