### ISSUE TITLE
关于Taro 代码与微信小程序代码混写有疑问

### ISSUE THREAD

**Issue by Dithub2016** [NervJS/taro#546]
**问题描述**
`Taro 代码与微信小程序代码混写`这个在文档上面说得比较简短，从哪个版本开始支持呢，然后有没有相应的例子可以提供一下，自己尝试了一下，在编译小程序的时候是会对微信小程序的页面代码报 `Error: 未找到 Taro.Component 的类定义 ` 的错误的

**期望行为**
希望得到更多的说明

**系统信息**

 - 操作系统: Window 7
 - Taro 版本 Taro v1.0.0-beta.20
 - Node.js 版本 v10.6.0

**Comment by luckyadam** [comment]
@Dithub2016 收到~ 稍后我们补上示例~

**Comment by wufeng87** [comment]
@Dithub2016 请问一般哪些需求需要用到这个特性呢？谢谢。

**Comment by luckyadam** [comment]
@Dithub2016 请参考项目 https://github.com/NervJS/taro-sample-weapp

**Comment by Dithub2016** [comment]
感谢
