### ISSUE TITLE
@2.0.3 onTouchMove事件对象类型有误

### ISSUE THREAD

**Issue by ghost** [NervJS/taro#5461]
### 问题描述

@tarojs/components/types/common.d.ts 103行
ITouchEvent  接口定义中的 changedTouches 类型错误 应为Array\<ITouch\>

### 复现步骤

无步骤

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
import { ITouchEvent } from '@tarojs/components/types/common';
const onTouchMove = (e: ITouchEvent) => {
    const y = e.changedTouches[0].pageY
}

```

### 期望行为

ts不会报告pageY不存在

### 报错信息

TS2339: Property 'pageY' does not exist on type 'CanvasTouch'.

### 系统信息

  Taro CLI 2.0.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.5.0 - D:\Dev\Nodejs\node.EXE
      Yarn: 1.22.0 - D:\Dev\Nodejs\yarn.CMD
      npm: 6.9.0 - D:\Dev\Nodejs\npm.CMD

### 补充信息

接口中类型错误

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
直接提个 PR 咯

**Comment by Cufoon** [comment]
> 直接提个 PR 咯

好的
