### ISSUE TITLE
配置编译保留 es6 module 关键字不生效

### ISSUE THREAD

**Issue by JunreyCen** [NervJS/taro#5463]
### 问题描述

编译配置了 babel 插件保留 es6 module 关键字，但 build 输出的是 cjs module。

### 复现步骤

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

plugins: {
    uglify: {
      enable: false
    },
    babel: {
      sourceMap: true,
      presets: [
        [
          'env',
          {
            modules: false
          }
        ]
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread'
      ]
    }
  },
```

### 期望行为

生产文件保留 es6 module 关键字。

### 系统信息

Taro CLI 1.3.25 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.2/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.16.2/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.33 => 1.3.33
      @tarojs/components: 1.3.33 => 1.3.33
      @tarojs/plugin-babel: 1.3.33 => 1.3.33
      @tarojs/plugin-csso: 1.3.33 => 1.3.33
      @tarojs/plugin-sass: 1.3.33 => 1.3.33
      @tarojs/plugin-uglifyjs: 1.3.33 => 1.3.33
      @tarojs/router: file:tarojs-router-1.3.25.tgz => 1.3.25
      @tarojs/taro: 1.3.33 => 1.3.33
      @tarojs/taro-alipay: 1.3.33 => 1.3.33
      @tarojs/taro-h5: 1.3.33 => 1.3.33
      @tarojs/taro-swan: 1.3.33 => 1.3.33
      @tarojs/taro-tt: 1.3.33 => 1.3.33
      @tarojs/taro-weapp: 1.3.33 => 1.3.33
      @tarojs/webpack-runner: 1.3.33 => 1.3.33
      eslint-config-taro: 1.3.33 => 1.3.33
      eslint-plugin-taro: 1.3.33 => 1.3.33
      nervjs: ^1.5.5 => 1.5.6

**Comment by Chen-jj** [comment]
升级 Taro2 或 3 再试试吧
