### ISSUE TITLE
在app.scss中import taro-ui样式库，在进行RN端编译会报错

### ISSUE THREAD

**Issue by lzp979822781** [NervJS/taro#5465]
### 问题描述
此错误发生在taro init 工程中配置taro-ui，在app.scss中导入taro-ui样式库
/*  #ifndef rn */
/@import "~taro-ui/dist/style/index.scss";
/*  #endif  */
在进行RN端编译时会报错

### 复现步骤
1.配置taro-ui
2.在app.scss中导入@import "~taro-ui/dist/style/index.scss";
3.运行npm run dev:rn就会编译报错
4.关于动态编译的问题 已添加/*  #ifndef rn */ /*  #endif  */，但是依然会报错
5.![image](https://user-images.githubusercontent.com/25949920/74514414-6f7da900-4f47-11ea-9489-77d1efa250a0.png)

### 期望行为
rn端可以不进行@import "~taro-ui/dist/style/index.scss"; 的预编译
### 报错信息

$ npm run dev:rn

> template-app@1.0.0 dev:rn /Users/**/vscodespace/template-app
> npm run build:rn -- --watch

> template-app@1.0.0 build:rn /Users/**/vscodespace/template-app
> taro build --type rn "--watch"

👽 Taro v2.0.3

开始编译项目 template-app
编译  JSX       /Users/**/vscodespace/template-app/src/app.jsx
生成  JSX       /Users/**/vscodespace/template-app/rn_temp/app.js
编译  SCSS      /Users/**/vscodespace/template-app/src/app.scss
错误  样式预处理  /Users/**/vscodespace/template-app/src/app.scss
Error: File to import not found or unreadable: ~taro-ui/dist/style/index.scss.
    at Object.module.exports.renderSync (/Users/**/vscodespace/template-app/node_modules/node-sass/lib/index.js:441:16)
    at Promise (/Users/**/vscodespace/template-app/node_modules/@tarojs/plugin-sass/index.js:58:21)
    at new Promise (<anonymous>)
### 系统信息

Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/node_global/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 2.0.3 => 2.0.3 
      @tarojs/components-qa: 2.0.3 => 2.0.3 
      @tarojs/components-rn: ^2.0.3 => 2.0.3 
      @tarojs/mini-runner: 2.0.3 => 2.0.3 
      @tarojs/redux: 2.0.3 => 2.0.3 
      @tarojs/redux-h5: 2.0.3 => 2.0.3 
      @tarojs/router: 2.0.3 => 2.0.3 
      @tarojs/taro: 2.0.3 => 2.0.3 
      @tarojs/taro-alipay: 2.0.3 => 2.0.3 
      @tarojs/taro-h5: 2.0.3 => 2.0.3 
      @tarojs/taro-qq: 2.0.3 => 2.0.3 
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3 
      @tarojs/taro-redux-rn: ^2.0.3 => 2.0.3 
      @tarojs/taro-rn: ^2.0.3 => 2.0.3 
      @tarojs/taro-router-rn: ^2.0.3 => 2.0.3 
      @tarojs/taro-swan: 2.0.3 => 2.0.3 
      @tarojs/taro-tt: 2.0.3 => 2.0.3 
      @tarojs/taro-weapp: 2.0.3 => 2.0.3 
      @tarojs/webpack-runner: 2.0.3 => 2.0.3 
      eslint-config-taro: 2.0.3 => 2.0.3 
      eslint-plugin-taro: 2.0.3 => 2.0.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      react: 16.8.0 => 16.8.0 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.0.3 => 2.0.3 
      stylelint-taro-rn: 2.0.3 => 2.0.3 
    npmGlobalPackages:
      typescript: 3.6.4

**Comment by luckyadam** [comment]
taro-ui 还没有支持 rn

**Comment by zkqiang** [comment]
这个问题似乎是因为编译 rn 不识别 `~` 符号导致的
我暂时的解决办法是使用 `../../../node_modules/taro-ui/dist/style/...xxx` 这种形式代替
