### ISSUE TITLE
编译小程序 import json出错 TypeError: Property properties[0] of ObjectExpression expected node to be of a type ["ObjectMethod","ObjectProperty","SpreadProperty"] but instead got "ObjectExpression"

### ISSUE THREAD

**Issue by jy1989** [NervJS/taro#547]
编译小程序 import json出错

> 编译  页面文件  src/pages/index/index
> TypeError: Property properties[0] of ObjectExpression expected node to be of a type ["ObjectMethod","ObjectProperty","SpreadProperty"] but instead got "ObjectExpression"
>     at validate (E:\pet\cat-wiki\node_modules\.6.26.0@babel-types\lib\definitions\index.js:109:13)
>     at validator (E:\pet\cat-wiki\node_modules\.6.26.0@babel-types\lib\definitions\index.js:57:7)
>     at Object.validate (E:\pet\cat-wiki\node_modules\.6.26.0@babel-types\lib\definitions\index.js:190:10)
>     at validate (E:\pet\cat-wiki\node_modules\.6.26.0@babel-types\lib\index.js:505:9)
>     at Object.builder (E:\pet\cat-wiki\node_modules\.6.26.0@babel-types\lib\index.js:466:7)
>     at ImportDeclaration (E:\pet\cat-wiki\node_modules\.1.0.0-beta.19@@tarojs\cli\src\weapp.js:499:130)
>     at NodePath._call (E:\pet\cat-wiki\node_modules\.6.26.0@babel-traverse\lib\path\context.js:76:18)
>     at NodePath.call (E:\pet\cat-wiki\node_modules\.6.26.0@babel-traverse\lib\path\context.js:48:17)
>     at NodePath.visit (E:\pet\cat-wiki\node_modules\.6.26.0@babel-traverse\lib\path\context.js:105:12)
>     at TraversalContext.visitQueue (E:\pet\cat-wiki\node_modules\.6.26.0@babel-traverse\lib\context.js:150:16)

定位到是import json的问题：

```

import Taro, { Component } from '@tarojs/taro'
import { View, Text } from '@tarojs/components'
import './index.css'
import data from '../data.json'
export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  componentWillMount () { }

  componentDidMount () {
    console.log(data)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    const pets = data.map((pet) => {
      return <View key={pet.id} className='item'>
              <Text>{pet.name}</Text>
             </View>
    });


    return (
      <View className='index'>
        {pets}
      </View>
    )
  }
}

```

json是一个array

![image](https://user-images.githubusercontent.com/1291756/44791588-88b85b80-abd4-11e8-98e8-98206a974afd.png)

**报错信息**

![image](https://user-images.githubusercontent.com/1291756/44791947-6bd05800-abd5-11e8-9fa4-f99ab1a16706.png)

**系统信息**

 - 操作系统:Windows 10
 - Taro 版本 1.0.0-beta.18
 - Node.js 版本v8.11.4

h5编译正常
![image](https://user-images.githubusercontent.com/1291756/44791854-33c91500-abd5-11e8-867b-5239b1e6a7c9.png)

**Comment by luckyadam** [comment]
json 文件能不能提供一部分，数组话，提供一两项就好

**Comment by jy1989** [comment]
@luckyadam  你好  是这样的
[format.1535606951046.json.zip](https://github.com/NervJS/taro/files/2334700/format.1535606951046.json.zip)

**Comment by luckyadam** [comment]
已修复，下个版本发布~
