### ISSUE TITLE
map 遍历生成模板的编译 Bug

### ISSUE THREAD

**Issue by Aliveing** [NervJS/taro#5473]
### 问题描述
**这个BUG我描述能力有限，请看复现步骤中的动图和代码**
当 map 遍历生成模板时，返回值为调用其他render方法生成的模板，其他render方法渲染模板没有问题，但是当这个其他方法中有类似于 onChange 回调时，在 onChange 中获取的遍历值始终是最后一次遍历的数据，很像被闭包了一样。
#### 问题描述补充
类似的问题我提交过一个issue：#5138，这两个issue不同的是：#5138 是一层map渲染出现这种问题，有暂时的解决方法；这个issue是在两层map时出现问题，并且没有暂时的解决方法

#### 步骤

1. 拷贝复现代码
2. 依次点击switch
#### 复现代码
```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
import Taro, { Component } from '@tarojs/taro';
import { View } from '@tarojs/components';
import { AtSwitch } from 'taro-ui';

class X extends Component {

    renderItems = (arr_item) => {
        return arr_item.map(item => {
            return <AtSwitch
                key={item}
                title={item}
                checked={false}
                onChange={(newValue, e) => {
                    console.log(item);
                }}
            />
        })
    }

    render() {
        const arr1 = Array.from({ length: 3 }).map((item, index) => index + 1);
        const arr2 = Array.from({ length: 3 }).map((item, index) => (index + 1) * 10);
        const arr = [arr1, arr2];
        const colors = ['red', 'yellow'];
        return <View>
            {/* 没问题的写法 */}
            <View style='background-color: blue; color: white; text-align: center;'>好用的Map写法</View>
            <View>
                {
                    arr.map((arr_item, index) => {
                        return <View key={`view_${index}`} style={`background-color:${colors[index]}`}>
                            {
                                arr_item.map(item => {
                                    return <AtSwitch
                                        key={item}
                                        title={item}
                                        checked={false}
                                        onChange={(newValue, e) => {
                                            console.log(item);
                                        }}
                                    />
                                })
                            }
                        </View>
                    })
                }
            </View>
            {/* 有问题的写法 */}
            <View style='background-color: blue; color: white; text-align: center;'>有问题的Map写法</View>
            <View>
                {
                    arr.map((arr_item, index) => {
                        return <View key={`view_${index}`} style={`background-color:${colors[index]}`}>
                            {this.renderItems(arr_item)}
                        </View>
                    })
                }
            </View>
        </View>
    }
}
export default X;

```

### 期望行为
能在 onChange 方法中获取正确的循环值

### 报错信息
无

### 系统信息
<details>
👽 Taro v2.0.3

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 2.0.3 => 2.0.3
      @tarojs/mini-runner: 2.0.3 => 2.0.3
      @tarojs/plugin-babel: 2.0.3 => 2.0.3
      @tarojs/plugin-csso: 2.0.3 => 2.0.3
      @tarojs/plugin-sass: 2.0.3 => 2.0.3
      @tarojs/plugin-uglifyjs: 2.0.3 => 2.0.3
      @tarojs/router: 2.0.3 => 2.0.3
      @tarojs/taro: 2.0.3 => 2.0.3
      @tarojs/taro-alipay: 2.0.3 => 2.0.3
      @tarojs/taro-h5: 2.0.3 => 2.0.3
      @tarojs/taro-qq: 2.0.3 => 2.0.3
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3
      @tarojs/taro-swan: 2.0.3 => 2.0.3
      @tarojs/taro-tt: 2.0.3 => 2.0.3
      @tarojs/taro-weapp: 2.0.3 => 2.0.3
      @tarojs/webpack-runner: 2.0.3 => 2.0.3
      eslint-config-taro: 2.0.3 => 2.0.3
      eslint-plugin-taro: 2.0.3 => 2.0.3
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.3 => 2.0.3
      stylelint-taro-rn: 2.0.3 => 2.0.3
</details>

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Aliveing** [comment]
传一个复现的动态图：
[![gifhome-992x898-12s.gif](https://i.postimg.cc/kMkr6jtw/gifhome-992x898-12s.gif)](https://postimg.cc/bdHV49g2)

**Comment by shenghanqin** [comment]
请提供taro版本

**Comment by luckyadam** [comment]
麻烦提供一个 taro 的版本

**Comment by Aliveing** [comment]
![image](https://user-images.githubusercontent.com/11768879/74819549-88b59980-533b-11ea-8637-953ddcf7d2f6.png)
@luckyadam issuemi描述中有，因为太长了，所以折叠了。。。

**Comment by Aliveing** [comment]
@shenghanqin @luckyadam any update ?
