### ISSUE TITLE
👽 Taro v2.0.3 启动两个警告⚠️信息解决

### ISSUE THREAD

**Issue by WuYunlong** [NervJS/taro#5474]
### 问题描述
yarn run dev:weapp

控制台报错两个Warning

1.  Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

2. Warning: Conditional exports is an experimental feature. This feature could change at any time

执行步骤

### 复现步骤

taro init demo
cd demo
yarn run dev:weapp

### 期望行为

解决这两个警告提示

### 报错信息
👽 Taro v2.0.3

开始编译项目 demo
生成  工具配置  dist/project.config.json

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
编译  发现入口  src/app.jsx
编译  发现页面  src/pages/index/index.jsx
⠋ 即将开始启动编译，请稍等~(node:18759) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
✅  编译成功，请打开微信小程序开发者工具进行查看

### 系统信息

👽 Taro v2.0.3

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.22.0 - ~/.nvm/versions/node/v13.7.0/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v13.7.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.3 => 2.0.3
      @tarojs/components-qa: 2.0.3 => 2.0.3
      @tarojs/mini-runner: 2.0.3 => 2.0.3
      @tarojs/mobx: 2.0.3 => 2.0.3
      @tarojs/mobx-h5: 2.0.3 => 2.0.3
      @tarojs/router: 2.0.3 => 2.0.3
      @tarojs/taro: 2.0.3 => 2.0.3
      @tarojs/taro-alipay: 2.0.3 => 2.0.3
      @tarojs/taro-h5: 2.0.3 => 2.0.3
      @tarojs/taro-qq: 2.0.3 => 2.0.3
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3
      @tarojs/taro-swan: 2.0.3 => 2.0.3
      @tarojs/taro-tt: 2.0.3 => 2.0.3
      @tarojs/taro-weapp: 2.0.3 => 2.0.3
      @tarojs/webpack-runner: 2.0.3 => 2.0.3
      eslint-config-taro: 2.0.3 => 2.0.3
      eslint-plugin-taro: 2.0.3 => 2.0.3
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.3 => 2.0.3
      stylelint-taro-rn: 2.0.3 => 2.0.3

**Comment by jiangxd2016** [comment]
同样出现了第一个问题，搜索的解决方法都无效。

**Comment by zhengyangkang** [comment]
同报第一个warning，taro/cli是从1.3.22升级到了2.0.4不知道是不是这个警告影响，目前页面上图片不显示，组件间props传参无法接收，但是在render里面写个console.log整个页面就又正常了

**Comment by ly827** [comment]
同样问题 期待解决

**Comment by wforguo** [comment]
尝试看看css当中 有没有 这行代码；

```
/* autoprefixer: on */
```

我发现这行代码会影响， 出编译警告.
