### ISSUE TITLE
在h5端中的路由生命周期，怎么控制输入不存在的路由重定向到404页面？

### ISSUE THREAD

**Issue by 521707** [NervJS/taro#5478]
### 问题描述
taro没有路由的生命周期提供， 该如何对不存在的路由进行重定向404页面？

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
app 中 componentDidNotFound 生命周期
或者自己配一下 nginx

**Comment by huanz** [comment]
另外h5页面打开，后面如果带有一些未知的 hash 参数，会报错 `Invariant Violation`，能否增加像react-router类似的404页面配置呢？ `componentDidNotFound ` 方法是不会触发的，只能通过 error boundary 来捕获
