### ISSUE TITLE
Taro 2.0.3, 子包中的公共文件runtime, vendor都放在了子包的app.js中，实际上这个文件并不走

### ISSUE THREAD

**Issue by moonreplace** [NervJS/taro#5479]
### 问题描述

如果我的包是个子包，打出来的公共chunk, vendor.js, runtime.js会被放在子包中的app.js中，但是这个子包的app.js不会被走到。所以加载页面的时候报错。把这几个文件放到页面的入口处，不会报错。

### 复现步骤

打包完就可以看到

### 期望行为

子包在每个页面入口处添加对公共包的引用

### 报错信息

On app route: package_activity/farm/pages/index/index
Page "package_activity/farm/pages/index/index" has not been registered yet.
### 系统信息

👽 Taro v2.0.3

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm

**Comment by luckyadam** [comment]
子包为啥有 app.js？

**Comment by moonreplace** [comment]
> 子包为啥有 app.js？

入口文件。主包是原生的，子包是用Taro搭建的
