### ISSUE TITLE
beta20 组件传className不起效了

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#548]
**复现步骤**

组件
```

export default class Test extends Taro.PureComponent {

    render() {
        const { className } = this.props;
        return <View className={className}> test test</View>;
    }

}


```

调用组件
```
    render() {
        return <Test className={"test"} />;
    }

```

样式
```
.test {
    color: red;
}

```

**期望行为**
beta17 起效

![screen shot 2018-08-29 at 9 53 05 pm](https://user-images.githubusercontent.com/26269173/44792361-514aae80-abd6-11e8-9a97-f30b356ccff4.png)

**报错信息**

beta20 不起效
![screen shot 2018-08-29 at 9 51 49 pm](https://user-images.githubusercontent.com/26269173/44792151-d8e3ed80-abd5-11e8-8a97-9b5e722e5e99.png)

**系统信息**

taro beta 20
max oS

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Songkeys** [comment]
我之前也是这样用的。更新了之后推荐在自定义组件中使用 `addGlobalClass` 配置。
但是我这边还是无效。（组件库和 taro 版本都是最新的，也重启了微信开发者工具。）
#537

**Comment by kdong007** [comment]
@Songkeys 2.2.3的功能阿 很多用户微信还没到这个版本呢 用上太危险了

**Comment by kdong007** [comment]
外面class带不进去也没关系 <test is="xxx" > 这个节点上为什么没有class了

**Comment by kdong007** [comment]
有些时候因为组件相当于嵌套了两层view 如果外面那层无法设置class会导致组件无法排版
比如我要让组件 flex:1

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/0b4d7ce63f68297f70db179e95162bf39737f4b0
