### ISSUE TITLE
关于页面路径配置

### ISSUE THREAD

**Issue by s15723** [NervJS/taro#5484]
我现在有个需求是定义config里面的page选项时不按照项目目录来有什么办法可以实现？
比如我有个页面线上地址是'pages/member/receive'，但我现在目录结构想改成'pages/member/receive/receive'，线上地址还要是原来的不能变。这个有什么途径实现，啊

**Comment by luckyadam** [comment]
没有，而且不是很理解这样的需求

**Comment by Inori-Lover** [comment]
> 没有，而且不是很理解这样的需求

我觉得这个需求可以扩展为pages可变量化。
比如pages定义可以接受抽象成一个const性质的变量，然后项目内可跳转的地址就可以实现类型安全了

或者接受prerun性质的变量定义也好

**Comment by SilentFlute** [comment]
@s15723 `app.config.js`中加一个: pages/member/receive/receive, 然后`config/index.js`中使用自定义路由
```
    router: {
      mode: 'browser',
      customRoutes: {
        '/pages/member/receive/receive': '/pages/member/receive'
      }
    },
```
这样应该就能达到你的要求了

**Comment by SilentFlute** [comment]
仔细看了楼主你说的小程序是吧, 那我就不清楚了, h5是可以使用自定义路由实现的
