### ISSUE TITLE
[taro-v2.0.3]cli 新建项目 选择redux mobx模版出错 系统 macos 版本

### ISSUE THREAD

**Issue by xgaxpp** [NervJS/taro#5485]
SyntaxError: Error parsing /usr/local/lib/node_modules/@tarojs/cli/templates/mobx/package.json: Unexpected token < in JSON at position 183
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:256:20)
    at readPackageScope (internal/modules/cjs/loader.js:281:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1162:17)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tarojs/cli/dist/create/init.js:153:54)
    at Generator.next (<anonymous>) {
  path: '/usr/local/lib/node_modules/@tarojs/cli/templates/mobx/package.json'
}

**Comment by luckyadam** [comment]
没有复现，建议重装下 taro cli 试试

**Comment by rojer95** [comment]
@luckyadam 

我运行这个 `npx @tarojs/cli@next init myApp` 也遇到这个问题。
next貌似只有default模版

**Comment by vinurs** [comment]
我也遇到了同样的问题，应该是跟node版本有关系，在node v13.8.0跟node v12.16.0都会存在这个问题

**Comment by gumingfeng** [comment]
尝试从新安装也没有错误，node版本 v13.8.0 npm v6.13.7

**Comment by Psli** [comment]
Node.js v13.8.0
yarn v1.22.0
遇到了同样的问题

**Comment by Garfield550** [comment]
macOS 的话尝试这样操作一下（每个步骤都做一下）

1. 删除你的所有全局 Taro 安装
2. 清理 npm 和 yarn 的缓存（全局和用户）
3. 删除 `~/.taro` 或者 `~/.taro2` 文件夹

**Comment by vinurs** [comment]
> macOS 的话尝试这样操作一下（每个步骤都做一下）
> 
> 1. 删除你的所有全局 Taro 安装
> 2. 清理 npm 和 yarn 的缓存（全局和用户）
> 3. 删除 `~/.taro` 或者 `~/.taro2` 文件夹
> 
> Windows 的话在你的用户目录下面
> 
> ![image](https://user-images.githubusercontent.com/3471836/75166582-070ca400-575f-11ea-8641-96f0e8b08cfa.png)

```
npm uninstall -g @tarojs/cli
npm cache clean --force
yarn cache clean
rm -rf ~/.taro*
```
我尝试了一下上面的步骤，还是没有解决，是不是哪里没做对

**Comment by Garfield550** [comment]
重装之后检查一下  `@tarojs/cli/templates/mobx/` 和 `@tarojs/cli/templates/redux/` 目录里有没有叫做 `pkg` 的文件，根据这里的代码目录进行比对一下。

应该是不存在 package.json 文件才是对的。

https://github.com/NervJS/taro-project-templates/tree/2.0/redux

**Comment by vinurs** [comment]
是不是next版本也存在同样的问题，我看了一下next版本的下面是有package.json的
https://github.com/NervJS/taro-project-templates/tree/next/redux

**Comment by yuche** [comment]
> 是不是next版本也存在同样的问题，我看了一下next版本的下面是有package.json的
> [NervJS/taro-project-templates:redux@`next`](https://github.com/NervJS/taro-project-templates/tree/next/redux) [](/NervJS/taro-project-templates/tree/HEAD@{2020-02-25T06:00:40Z}/redux)

next 在 v3 分支

**Comment by vinurs** [comment]
v3分支也是有package.json这个文件的，我现在用的是next版本，不过初始化项目的时候也是存在这个问题

**Comment by Garfield550** [comment]
有 `pkg` 是对的，有 `package.json` 是错的。

**Comment by gumingfeng** [comment]
最近更新到了2.04恢复正常了。没有继续使用2.03

**Comment by vinurs** [comment]
2.0.4是正常的，不过在next版本里面这个问题又复现了
