### ISSUE TITLE
getCurrentPagesH5端返回值与微信端不一致

### ISSUE THREAD

**Issue by venecy** [NervJS/taro#5487]
### 问题描述

const [page] = Taro.getCurrentPages();

H5 端 page 对象缺少 `route` 字段，且无其他方式获取该 page 对象对应的页面路径

微信小程序中 `page.route` 文档截图：

![微信截图_20200217174130](https://user-images.githubusercontent.com/11851303/74642790-9984d480-51ae-11ea-97cd-b9c5364d0e27.png)

### 复现步骤

必现

### 期望行为

期望H5端返回值与微信一致

### 报错信息

无

### 系统信息

�👽 Taro v2.0.2

  Taro CLI 2.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\goo\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

H5中返回的是对 `WrappedComponent` 组件的引用，不存在 `route` 字段，建议增加以保持多端一致

**Comment by piscdong** [comment]
不仅仅是没有route，h5的Taro.getCurrentPages()返回的是WrappedComponent，用```Taro.getCurrentPages()[(Taro.getCurrentPages().length-1)]```是undefined
这都多长时间了，官方没一个跟进的吗？

**Comment by cncolder** [comment]
> “只有h5需求的话不建议用taro”

确实如此, web 端的技术选型要丰富得多, 限制也会少得多, 尤其是在 UI 框架方面可选项也非常多.

**Comment by venecy** [comment]
@cncolder 既然h5也是taro兼容的端，还是希望能尽量和其他端保持一致，尤其是小程序。选择taro的一般都是跨端的业务，并不会只有h5需求。

**Comment by piscdong** [comment]
> @cncolder 既然h5也是taro兼容的端，还是希望能尽量和其他端保持一致，尤其是小程序。选择taro的一般都是跨端的业务，并不会只有h5需求。

我以前调研过各个框架，得出的结论是，如果没有涉及小程序、h5、app的多端需求不建议用这些框架，纯小程序的多端可以直接把微信小程序原生代码转成其他小程序

**Comment by cncolder** [comment]
跨端越多, 要兼容的地方也越多, 限制就越多. 像是木桶理论的另一种解释, 小程序是木桶上最短的一块木板, 会拖累 h5 和 app 影响发挥.

如果只做 h5, 还要受小程序和 app 的气, 有点太冤了.

我这样说不是否定 taro-h5 的意义, 只是想告诫要做个移动端网站的人, 不管是通过什么途径找到 taro 的, 都必须看清楚在只做 h5 这个前提下, taro 不是最好的选择.

**Comment by ZakaryCode** [comment]
该问题可以通过升级版本解决
