### ISSUE TITLE
Mobx下数组渲染子组件时若数组变化时可能导致渲染不正确

### ISSUE THREAD

**Issue by DrakeXiang** [NervJS/taro#5489]
### 复现步骤

在支付宝下渲染一个子组件列表，使用`unshift`和`shift`方法从数组头部增、删元素，或者新数组是在原数组开始新增了一个元素，则渲染会出现元素重复渲染或者缺失的情况。使用`push`/`pop`时渲染正常，在微信下使用`unshift`/`shift`也正常。

1. 渲染一个子组件列表
2. 从数组头部增删元素
3. 观察渲染情况

```js
// common.ts
let count = 0;
export class CommonStore {
    @observable testList: string[] = [];

  @action.bound
  addTestItem() {
    const newList = toJS(this.testList).slice(0);
    newList.unshift(String(count));
    count++;
    this.testList = newList;
  }

  @action.bound
  deleteItem() {
    const newList = toJS(this.testList).slice(0);
    newList.shift();
    this.testList = newList;
  }
}

// TestItem.tsx
@observer
class TestItem extends Component {
  render() {
    const { number } = this.props;
    return <View>{`number: ${number}`}</View>;
  }
}

export default TestItem;


// Test.tsx
interface IProps {
  common: CommonStore;
}

@inject('common')
@observer
class Test extends Component<IProps> {
  add = async () => {
    const { common } = this.props;
    common.addTestItem();
  };

  delete = async () => {
    const { common } = this.props;

    common.deleteItem();
  };

  render() {
    const { common } = this.props;
    const { testList } = common;
    console.log(toJS(testList));

    return (
      <View>
        <Button onClick={this.add}>add</Button>
        <Button onClick={this.delete}>delete</Button>
        {toJS(testList).map(car => (
          <Item key={car} number={car}></Item>
        ))}
      </View>
    );
  }
}

export default Test;

```

### 期望行为

渲染正常

### 系统信息

Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.1 => 2.0.1
      @tarojs/components: 2.0.1 => 2.0.1
      @tarojs/components-qa: 2.0.1 => 2.0.1
      @tarojs/mini-runner: 2.0.1 => 2.0.1
      @tarojs/mobx: 2.0.1 => 2.0.1
      @tarojs/mobx-h5: 2.0.1 => 2.0.1
      @tarojs/plugin-babel: 2.0.1 => 2.0.1
      @tarojs/plugin-csso: 2.0.1 => 2.0.1
      @tarojs/plugin-sass: 2.0.1 => 2.0.1
      @tarojs/plugin-uglifyjs: 2.0.1 => 2.0.1
      @tarojs/router: 2.0.1 => 2.0.1
      @tarojs/taro: 2.0.1 => 2.0.1
      @tarojs/taro-alipay: 2.0.1 => 2.0.1
      @tarojs/taro-h5: 2.0.1 => 2.0.1
      @tarojs/taro-qq: 2.0.1 => 2.0.1
      @tarojs/taro-quickapp: 2.0.1 => 2.0.1
      @tarojs/taro-rn: 2.0.1 => 2.0.1
      @tarojs/taro-swan: 2.0.1 => 2.0.1
      @tarojs/taro-tt: 2.0.1 => 2.0.1
      @tarojs/taro-weapp: 2.0.1 => 2.0.1
      @tarojs/webpack-runner: 2.0.1 => 2.0.1
      eslint-config-taro: 2.0.1 => 2.0.1
      eslint-plugin-taro: 2.0.1 => 2.0.1
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.1 => 2.0.1
      stylelint-taro-rn: 2.0.1 => 2.0.1
### 补充信息

目前暂时的解决方法是先`list`设置为空数组，并且要加几百毫秒的延时，再把改变后的新数组放进去。。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by DrakeXiang** [comment]
@Chen-jj 大佬来看看啊，这个问题很严重啊，所有倒序显示的列表只要更新都会出问题啊

**Comment by defautstring** [comment]
试试 使用 mobx 的 computed 来获取testList，将testList 转换为数组返回，即return testList.slice()

**Comment by DrakeXiang** [comment]
> 试试 使用 mobx 的 computed 来获取testList，将testList 转换为数组返回，即return testList.slice()

试了下还是一样有问题

**Comment by Vanessa219** [comment]
@DrakeXiang 

在子组件外加 `<View>` 应该可以解决问题

**Comment by Chen-jj** [comment]
Taro 3 应该没有问题了。
