### ISSUE TITLE
有的组件 className无效

### ISSUE THREAD

**Issue by gh81997167** [NervJS/taro#549]
**问题描述**
有的组件 className 编译成小程序  还是 className 导致样式无效了，
比如taro-ui 的一些组件、scrollView组件等 更多的没做测试呢，就是之前写的都错乱了

**复现步骤**
[复现问题的步骤]

export default class Index extends Component {
    render() {
        return （<View > <scrollView className={['scroll-teacher']} scrollX="true"></View>）;
    }
}
或 
export default class Index extends Component {
    render() {
        return （<View > <scrollView className="scroll-teacher" scrollX="true"></View>）;
    }
}

**期望行为**
修复

**报错信息**
![fgwegwegweg](https://user-images.githubusercontent.com/10526983/44795023-4b57cc00-abdc-11e8-8fd9-3772a5c8a82a.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. 👽 Taro v1.0.0-beta.17]
 - Node.js 版本 [e.g. v8.0.0]

**补充信息**

**Comment by yuche** [comment]
`scrollView` 首字母大写
