### ISSUE TITLE
[taro-v2.0.3]局部引入taro-ui后，报错Cannot read property 'defaultProps' of undefined 

### ISSUE THREAD

**Issue by huanz** [NervJS/taro#5490]
### 问题描述

引入 "taro-ui": "^2.2.4" 报这个错误

### 复现步骤

```js
// components/taro-ui.ts
import { 
  AtButton, 
  AtTag, 
} from 'taro-ui'

import "taro-ui/dist/style/components/button.scss";
import "taro-ui/dist/style/components/tag.scss";

export { 
  AtButton, 
  AtTag, 
}

// index.tsx
import { AtButton } from '@/components/taro-ui'
```

### 报错信息

Uncaught TypeError: Cannot read property 'defaultProps' of undefined
    at Object.createComponent (vendors.js? [sm]:2144)
    at Object../src/components/taro-ui.ts (vendors.js? [sm]:31074)
    at __webpack_require__ (runtime.js? [sm]:80)
    at checkDeferredModules (runtime.js? [sm]:46)
    at Array.webpackJsonpCallback [as push] (runtime.js? [sm]:33)
    at eval (taro-ui.js:1)

### 系统信息

Taro v2.0.3

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.3 => 2.0.3 
      @tarojs/cli: ^2.0.3 => 2.0.3 
      @tarojs/components: 2.0.3 => 2.0.3 
      @tarojs/components-qa: 2.0.3 => 2.0.3 
      @tarojs/mini-runner: 2.0.3 => 2.0.3 
      @tarojs/router: 2.0.3 => 2.0.3 
      @tarojs/taro: 2.0.3 => 2.0.3 
      @tarojs/taro-alipay: 2.0.3 => 2.0.3 
      @tarojs/taro-h5: 2.0.3 => 2.0.3 
      @tarojs/taro-qq: 2.0.3 => 2.0.3 
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3 
      @tarojs/taro-rn: 2.0.3 => 2.0.3 
      @tarojs/taro-swan: 2.0.3 => 2.0.3 
      @tarojs/taro-tt: 2.0.3 => 2.0.3 
      @tarojs/taro-weapp: 2.0.3 => 2.0.3 
      @tarojs/webpack-runner: 2.0.3 => 2.0.3 
      eslint-config-taro: 2.0.3 => 2.0.3 
      eslint-plugin-taro: 2.0.3 => 2.0.3 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.3 => 2.0.3 
      stylelint-taro-rn: 2.0.3 => 2.0.3 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by huanz** [comment]
另外 taro-ui 这个组件库里面 `dist/weapp/index.js` 里面引入的样式路径错误

**Comment by luckyadam** [comment]
暂不支持这么使用，请直接从 taro-ui 中引用组件，而且看上去单独写一个文件导出 taro-ui 组件并无必要，如果非要这么干请等后续版本支持

**Comment by majorcool** [comment]
> 暂不支持这么使用，请直接从 taro-ui 中引用组件，而且看上去单独写一个文件导出 taro-ui 组件并无必要，如果非要这么干请等后续版本支持

taro-ui和taro/components都是官方出的，他们定位有什么差异？taro-ui是用来取代taro/components的吗？

**Comment by shenghanqin** [comment]
taro/components是对标原生组件的元素组件，类似于html中的div，是一种无特定样式的组件。
taro-ui是taro出的一种带有特定审美的UI样式组件库，是在taro/components之上的封装。
你要是用react的话，就可以用ant-design等等带有UI和逻辑的组件库。

**Comment by shenghanqin** [comment]
也没有取代一说，引入ui组件库，就会引入大量的代码；而如果自己按照设计稿来写样式，就无需引入组件库，一点一点写CSS就好了。

**Comment by majorcool** [comment]
> taro/components是对标原生组件的元素组件，类似于html中的div，是一种无特定样式的组件。
> taro-ui是taro出的一种带有特定审美的UI样式组件库，是在taro/components之上的封装。
> 你要是用react的话，就可以用ant-design等等带有UI和逻辑的组件库。
感谢解答。估计有很多刚接触taro的人有像我一样的疑问，希望可以放到文档首页的组件库介绍部分，说明清除。
