### ISSUE TITLE
建议将全局引用的sass加入监听编译中

### ISSUE THREAD

**Issue by qc-web-y** [NervJS/taro#5497]
### 问题描述
当全局引用sass文件发生修改后不能实时编译，有时候一个变量的变动就要结束当前任务，再次重新编译，实在有点太麻烦，希望考虑监听全局引用的sass文件更改，然后实时将其应用到页面的编译中。

### 复现步骤

1.配置全局sass变量文件，如：
![image](https://user-images.githubusercontent.com/41999566/74730791-c48c2880-5281-11ea-9545-11048056a6a9.png)

2. 执行任意端的npm编译命令
3. 修改任意sass变量文件，如向‘‘assets\styles\variable.scss’’文件增加一个颜色变量
![image](https://user-images.githubusercontent.com/41999566/74731009-28aeec80-5282-11ea-9465-e8118a34d555.png)
4. 将变量应用至任意页面，如：
![image](https://user-images.githubusercontent.com/41999566/74731125-657ae380-5282-11ea-96b3-7bcfa670b56a.png)
5. 然后你就会发现报错了
![image](https://user-images.githubusercontent.com/41999566/74731360-cd312e80-5282-11ea-8180-00a036454908.png)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

建议将全局引用的sass加入监听编译中。

### 报错信息

![image](https://user-images.githubusercontent.com/41999566/74731693-79731500-5283-11ea-80d6-55d885edc6de.png)

### 补充信息
我查看了官方的源码，猜测可能是因为变量文件被缓存起来的，然后读取的缓存，所以导致失败，建议监听到全局sass文件发生改变后，更新其缓存文件，或直接实时读取较为利于开发。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by a992681784** [comment]
这个问题后面有解决方案吗？目前taro3还是有这个问题。

**Comment by tourze** [comment]
+1，目前taro3.2 3.3都有这个问题。
