### ISSUE TITLE
何时在全平台添加webassembly模块的支持？ 

### ISSUE THREAD

**Issue by masx200** [NervJS/taro#5499]
### 问题描述

何时在全平台添加webassembly模块的支持？ 

### 复现步骤

无法在taro中调用其他可执行文件，进行高性能的计算。

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
这个是看对应的平台是否支持，如果支持，你的 webassembly 也得根据平台编译到不同的 target。
