### ISSUE TITLE
中文 placeholder 显示异常

### ISSUE THREAD

**Issue by YouYII** [NervJS/taro#55]
macos 10.13.4 (17E199)
![image](https://user-images.githubusercontent.com/5754760/41199884-7028216e-6ccc-11e8-8367-1585034afd65.png)

    <View className="weui-cell">
      <View className="weui-cell__hd"><Label className="weui-label">qq</Label></View>
      <View className="weui-cell__bd">
        <Input className="weui-input"  type='text' placeholder='将会获取焦点' focus/>
      </View>
    </View>

**Comment by yuche** [comment]
刚试了一下用最新的版本 0.0.43 并不能复现这个问题，请问你的版本号是多少？

**Comment by luckyadam** [comment]
收到~ 通过将中文字符串放到 `{}` 内可以避免这个问题，具体原因正在排查
```javascript
<Input className="weui-input"  type='text' placeholder={'将会获取焦点'} focus/>
```

**Comment by yuche** [comment]
应该与 babel 的问题相关：
https://github.com/babel/babylon/issues/271

似乎 babel@7 解决了这个问题：
https://github.com/babel/babel/pull/5256

**Comment by YouYII** [comment]
好的 谢谢
