### ISSUE TITLE
taro在使用jest测试的时候，报错！

### ISSUE THREAD

**Issue by zhongzhong0505** [NervJS/taro#5501]
### 问题描述

因为在项目中使用到了，redux-h5这个包，导致报错。看下这个包里面，使用的是esm，jest不支持。

### 复现步骤

无
```js
无

```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by zhongzhong0505** [comment]
![image](https://user-images.githubusercontent.com/15847574/74806170-361ab400-5320-11ea-9a6d-1d0fe5d4e6f6.png)

这里main是不是写错了？应该是index.js吧

**Comment by zhongzhong0505** [comment]
● Test suite failed to run

    /Users/zhongzhong/workspace/tim_webapp/node_modules/@tarojs/redux-h5/dist/index.esm.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { createElement } from 'nervjs';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

**Comment by zhongzhong0505** [comment]
用别的方式hack解决

**Comment by goldEli** [comment]
> 用别的方式hack解决

@zhongzhong0505 请问用的什么方法hack？

**Comment by leejunhui** [comment]
2024年了请问有解决方案了吗
