### ISSUE TITLE
rn上Block组件会被编译成View组件，会有样式问题

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#5505]
![微信截图_20200219153348](https://user-images.githubusercontent.com/31879769/74811833-471df200-532d-11ea-8281-9d0f186de4e9.jpg)
像这样的写法在rn上就会有样式问题

**Comment by Pines-Cheng** [comment]
RN 端对于 Block 组件也没有想到更好的处理方法。

**Comment by ShaoGongBra** [comment]
rn端支持这样的语法
```
<>
  <View />
  <View />
</>
```
也支持这样的语法
```
return [
  <View />,
  <View />
]
```
@Pines-Cheng
