### ISSUE TITLE
如何在团队开发时，不同的开发者配置不同的环境变量？

### ISSUE THREAD

**Issue by JoshYuJump** [NervJS/taro#5506]
如何在团队开发时，不同的开发者配置不同的环境变量？

**Comment by shenghanqin** [comment]
NPM库：dotenv，从文件加载环境变量 https://www.jianshu.com/p/ab7b106c3540
思路：
在本地文件（.gitignore，不上传git）上定义环境变量，然后使用dotenv加载到node环境变量上，然后在config启动的时候使用。可以参考 https://github.com/shenghanqin/goddess-hat/blob/master/load-env.js
