### ISSUE TITLE
taro convert失败，找不到package.json文件

### ISSUE THREAD

**Issue by hujingyuki** [NervJS/taro#5510]
### 复现步骤

1. 打开微信开发者工具创建一个新项目
2. 进入项目目录
3. 执行taro convert
4. 转化失败...

### 期望行为

转化成功

### 报错信息

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/35281360/74903648-8b1ffe00-53e4-11ea-88fd-225d66fd5b74.png">

### 系统信息

  Taro CLI 2.0.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm

**Comment by jackTangRJ** [comment]
@hujingyuki  你解决了吗，我也遇到了

**Comment by hujingyuki** [comment]
> @hujingyuki 你解决了吗，我也遇到了

我把taro版本将到1.3.34可以转化成功了

**Comment by SongRainRay** [comment]
> > @hujingyuki 你解决了吗，我也遇到了
> 
> 我把taro版本将到1.3.34可以转化成功了

我把微信小程序那个package.json在转换命令运行过程中，拷贝进去就Ok了

**Comment by hujingyuki** [comment]
这个本就是cli的问题，这么多个版本都有问题竟然不修复

**Comment by die214144031** [comment]
同样的问题，希望快点修复

**Comment by jerryniepan** [comment]
@luckyadam 会修复吗？

**Comment by Chen-jj** [comment]
已修复
