### ISSUE TITLE
taro next 是否支持微信云开发？

### ISSUE THREAD

**Issue by ACChe** [NervJS/taro#5513]
使用taro next新建的项目，导入微信开发工具不能正常编译，提示错误：

`未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。`

**Comment by shenghanqin** [comment]
你可以参考我写的口罩小程序的next react版本，其实用了云开发

https://github.com/shenghanqin/quick-mask/tree/feature/taro-cropper-try-20200215

- taro
- cloud/functions
- project.config.json

**Comment by ACChe** [comment]
@shenghanqin 新建项目选 云开发 模版吗？ 在微信开发者工具打开你的项目，也是提示找不到app.json,无法编译。

**Comment by shenghanqin** [comment]
现在是alpha，主要路线估计是沿着微信小程序普通模式，然后是h5和移动端，最后是云开发模式。你要是急需使用云开发，就请自己努力分析新老版本的配置，自己先试试看吧。
