### ISSUE TITLE
[taro 2.0.4] content-type: multipart/form-data的请求主体不是formdata？

### ISSUE THREAD

**Issue by alpha-hxb** [NervJS/taro#5514]
### 问题描述

content-type: multipart/form-data的请求主体不是formdata

### 复现步骤

设置content-type: multipart/form-data
使用fromdata方式进行post请求

### 期望行为

请求的主体为formdata

### 系统信息

  Taro CLI 2.0.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Users\xxxxx\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD

### 补充信息

![image](https://user-images.githubusercontent.com/30684108/74922264-eadcd000-5409-11ea-88d7-6d277ab822a0.png)

**Comment by le0l1** [comment]
@alpha-hxb  设置content-type为undefined即可解决这个问题
https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post

**Comment by max-end** [comment]
> @ alpha-hxb 不设置content-type立即解决这个问题
> https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post

我的设置undefined会报indexof error

**Comment by GitKou** [comment]
希望能reopen
![image](https://user-images.githubusercontent.com/7437397/164966906-6cd9df2e-e740-45a7-8812-010414d97b16.png)
![image](https://user-images.githubusercontent.com/7437397/164966913-7b923f6e-a0b8-42d4-b59b-95165126a062.png)
设置成undefined这里会报错
