### ISSUE TITLE
Taro 3.0.0-alpha.4 Vue 框架下注册组件微信小程序编译报错

### ISSUE THREAD

**Issue by libn-net** [NervJS/taro#5516]
### 问题描述
Taro 3.0.0-alpha.4 Vue 框架下注册动态组件报错，表现在
Vue.component(name, option)时 ，小程序编译 document.createComment is not a function

### 复现步骤

```js
<template>
  <view class="index">
    <text>{{ msg }}</text>
    <component
      :is="com"
      v-for="(com, i) in coms"
      :key="i"
    />
  </view>
</template>

<script>
  import Vue from 'vue'

  export default {
    data() {
      return {
        coms: [],
        code: [{
          name: 'button-counter', option: {
            data: function () {
              return {
                count: 0
              }
            },
            template: '<text>{{count}}</text>'
          }
        }],
        msg: 'Hello world1!'
      }
    },
    created() {


      for (let i = 0; i < this.code.length; i++) {
        let name = this.code[i].name
        let option = this.code[i].option

        Vue.component(name, option)
        this.coms.push({name: name, ins: Vue.component(name)})
      }

    }
  }
</script>

```

### 系统信息

👽 Taro v3.0.0-alpha.4

  Taro CLI 3.0.0-alpha.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.4 => 3.0.0-alpha.4 
      @tarojs/taro: 3.0.0-alpha.4 => 3.0.0-alpha.4 
      @tarojs/webpack-runner: ^2.0.4 => 2.0.4 
      eslint-config-taro: 3.0.0-alpha.4 => 3.0.0-alpha.4

**Comment by libn-net** [comment]
@Chen-jj

**Comment by yuche** [comment]
目前不能用 template 这种方式生命组件，所有组件都要经过 vue-loader，所有你要新建一个 .vue 组件然后 import 进来 再声明。
