### ISSUE TITLE
import 自定义组件名如果跟 @tarojs/components 提供的组件名一样，将会编译不通过

### ISSUE THREAD

**Issue by henryluki** [NervJS/taro#552]
自定义组件名如果跟 @tarojs/components 提供的组件名一样，将会编译不通过

如果定义了一个 Label 组件，在别的组件里面 import ，名字正好撞上了 @tarojs/components  里面的  Label, babel 就不会编译通过。

**Comment by yuche** [comment]
的确有这个限制，ESLint 也有相关的规则禁止你这么做。

我得想想有没有什么办法解除这个限制。

**Comment by vimcaw** [comment]
这个问题也是一样

Duplicate of #428

**Comment by wufeng87** [comment]
这个问题应该不大吧？自定义组件名字加个前缀就行。。。

**Comment by yuche** [comment]
看了一下各处代码耦合程度太高，没办法支持这个特性了。

ESLint 插件会禁止你这么做。https://github.com/NervJS/taro/blob/master/packages/eslint-plugin-taro/rules/class-naming.js
