### ISSUE TITLE
taro.setIsUsingDiff is not a function

### ISSUE THREAD

**Issue by hujingyuki** [NervJS/taro#5520]
### 问题描述

微信原生小程序转化为taro后，再编译为小程序时，getuserinfo按钮报错：taro.setIsUsingDiff is not a function

### 复现步骤

1. 微信开发者工具生成一个初始化的微信小程序工程
2. 进入工程目录，执行taro convert
3. 转化成功后进入taroConvert目录执行npm install 安装依赖
4. 执行npm run build:weapp
5. 用微信开发者工具导入工程，点击获取头像昵称按钮，控制台报错：taro.setIsUsingDiff is not a function

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

获取用户头像昵称成功

### 报错信息

![image](https://user-images.githubusercontent.com/35281360/75003201-fed41080-54a1-11ea-9ff9-77b1253d1b33.png)

### 系统信息

  Taro CLI 1.3.34 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

另外编译成小程序后的app.json中sitemap.json指向地址错误，应该在项目根目录中，dist目录中并没有sitemap.json，导致开发者工具一直报错找不到sitemap.json文件

**Comment by luckyadam** [comment]
升级到 1.3.37 再试试

**Comment by hujingyuki** [comment]
> 升级到 1.3.37 再试试

1.3.37 taro convert命令失败，找不到package.json

**Comment by IOriens** [comment]
一个临时的解决方案, 在`app.js`最上方添加如下代码

```js
let isUsingDiff = true;

export function getIsUsingDiff() {
  return isUsingDiff;
}

export function setIsUsingDiff(flag) {
  isUsingDiff = Boolean(flag);
}

Taro.getIsUsingDiff = Taro.getIsUsingDiff || getIsUsingDiff;
Taro.setIsUsingDiff = Taro.setIsUsingDiff || setIsUsingDiff;
```
