### ISSUE TITLE
Taro next，使用vue + ts编译报错，Module not found: Can't resolve 'D:TaroiToolssrcapp.ts' in 'D:\Taro\iTools\src'

### ISSUE THREAD

**Issue by liuqian1996** [NervJS/taro#5525]
### 问题描述
Taro next，使用vue + ts编译报错，Module not found: Can't resolve 'D:TaroiToolssrcapp.ts' in 'D:\Taro\iTools\src'

### 复现步骤
taro init，选择vue、ts，vuex，执行编译命令npm run dev:weapp，报错

### 期望行为
正常编译

### 报错信息
![image](https://user-images.githubusercontent.com/11707934/75017136-651f5a00-54c7-11ea-8e46-f2b5fe321336.png)

![image](https://user-images.githubusercontent.com/11707934/75017162-71a3b280-54c7-11ea-890d-d7c847e705af.png)

### 系统信息
![image](https://user-images.githubusercontent.com/11707934/75017314-b0396d00-54c7-11ea-80c9-2f64ff9da15a.png)

**Comment by yuche** [comment]
看一下你的 node_modules/@tarojs/mini-runner/package.json 和 node_modules/@tarojs/taro-loader ，版本是不是 alpha.3

**Comment by liuqian1996** [comment]
@yuche 
![image](https://user-images.githubusercontent.com/11707934/75018235-78332980-54c9-11ea-94e0-ac9111d25226.png)
![image](https://user-images.githubusercontent.com/11707934/75018259-85501880-54c9-11ea-98de-2b1ce3c488e7.png)

**Comment by yuche** [comment]
> @yuche
> ![image](https://user-images.githubusercontent.com/11707934/75018235-78332980-54c9-11ea-94e0-ac9111d25226.png)
> ![image](https://user-images.githubusercontent.com/11707934/75018259-85501880-54c9-11ea-98de-2b1ce3c488e7.png)

升级 taro-loader 到 alpha.3

**Comment by liuqian1996** [comment]
@yuche 
安装之后又提示其他问题，我试了好多次
![image](https://user-images.githubusercontent.com/11707934/75026278-aa4b8800-54d7-11ea-8de4-a88121c6f0e8.png)

出现这个提示之后，@tarojs/mini-runner安装一直抱一个错误

![image](https://user-images.githubusercontent.com/11707934/75026372-d1a25500-54d7-11ea-8e95-e5b1af77d9c1.png)

**Comment by yuche** [comment]
你把 node_modules 和 package.json.lock 删除了再重装，不行就等下一个版本吧。下一个版本会锁死依赖。

**Comment by liuqian1996** [comment]
@yuche 
安装还是报错，难受

**Comment by yuche** [comment]
重新 taro init 一个目录，把 node_modules 里 taro-loader 版本号为 experimental 的源码改一下：

taro-loader/lib/app.js 的源码改为
https://unpkg.com/@tarojs/taro-loader@3.0.0-alpha.4/lib/app.js

taro-loader/lib/page.js 的源码改为
https://unpkg.com/@tarojs/taro-loader@3.0.0-alpha.4/lib/page.js

**Comment by liuqian1996** [comment]
@yuche 
替换之后再编译显示下面这样
![image](https://user-images.githubusercontent.com/11707934/75085684-88e5ad00-5566-11ea-82ca-251f6d9d0776.png)

**Comment by Devas9** [comment]
我在mac都可以编译通过。但在windows下不伦是react，vue的都不能通过。提示类似的路径错误。版本alpha4，已经重新安装，新建项目等，都试过。

**Comment by beeplin** [comment]
taro-loader版本 3.0.0-alpha.5，windows下依然不行，还是拼路径错误

**Comment by yuche** [comment]
> taro-loader版本 3.0.0-alpha.5，windows下依然不行，还是拼路径错误

你是用的 vue 吧，等一个 alpha.6，准备发

**Comment by beeplin** [comment]
@yueche 收到，多谢~！
