### ISSUE TITLE
RichText组件不显示内容

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#5527]
taro 2.0.4
react-native 0.59
我看他这个源码引入了react-native 的WebView，但是这个版本里面好像已经没有这个组件了

**Comment by Pines-Cheng** [comment]
没有哪个组件，麻烦详细一点。

**Comment by ShaoGongBra** [comment]
![QQ20200301-182518](https://user-images.githubusercontent.com/31879769/75623908-13bf4b00-5bea-11ea-88c9-66c81e3d0887.png)
就是这个webview组件，现在的版本已经没有这个组件的了吧 @Pines-Cheng

**Comment by ShaoGongBra** [comment]
import { WebView, } from 'react-native';
有没有人修复rn的BUG呀，怎么这么久也没弄，也没更新
这个WebView已经从react-native中移除了

**Comment by iChengbo** [comment]
> import { WebView, } from 'react-native';
> 有没有人修复rn的BUG呀，怎么这么久也没弄，也没更新
> 这个WebView已经从react-native中移除了

0.59还没移除

**Comment by ShaoGongBra** [comment]
但是他确实不会显示呀，而且这个组件在0.54还是什么版本就已经移除了吧
