### ISSUE TITLE
支付宝插件2.0支持

### ISSUE THREAD

**Issue by LitileXueZha** [NervJS/taro#5531]
### 问题描述
**支持支付宝插件2.0开发。**

插件1.0版本和普通项目一样，只是开发页面级别就可以了，但是2.0和微信页面插件开发类似，需要输出两个目录：`miniprogram` 和 `plugin`。

[支付宝插件2.0文档](https://opendocs.alipay.com/mini/plugin)

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Mrwaite** [comment]
麻烦作者大大们尽快支持一下

**Comment by Mrwaite** [comment]
@LitileXueZha 因为目前支付宝插件 2.0 和微信小程序插件的目录结构很像, 所以可以基于微信插件的目录模板, 修改 @tarojs/cli 和 @tarojs/mini-runner 中对插件编译的处理, 让编译过程中, 对单个组件、页面、入口 都用 alipay 去编译. 就能达到构建产物符合支付宝插件 2.0 的要求.

这边值得注意的是, 即便按照上面编译还是会出现很多兼容性问题. 每个 tarojs 版本不一样, 问题也不一样.

目前我使用的 v1.3.25, 主要遇到构建产物中如下问题:
1. requestPlugin 方法, 写法 Taro.requestPlugin => requestPlugin.
2. miniprogram/app.json 需要替换 plugin 下面的 provider 为 "{{currentPluginId}}"
4. getApp 问题
     a. 删除 @tarojs/taro-alipay 下面的 Taro.getApp = getApp
     b. 修改 var r=getApp() => var r={} 
5. 根目录需要新建 mini.project.json 文件, 让小程序开发工具识别为 支付宝插件
6. plugin/plugin.json 文件中 pages 字段和 wx 的字段不一致, 调整一下

**Comment by guxingke201** [comment]
同求支付宝插件编译功能

**Comment by Chen-jj** [comment]
3.2.6 支持，#6959
