### ISSUE TITLE
hooks can only be called in a stateless component

### ISSUE THREAD

**Issue by Mihawk-zhao** [NervJS/taro#5532]
![image](https://user-images.githubusercontent.com/19793378/75091150-23fd7780-55a5-11ea-804f-682fc0f87dd7.png)
如图，当使用 useSelector 时，就会报错。
![image](https://user-images.githubusercontent.com/19793378/75091172-6757e600-55a5-11ea-80de-37b75984d69c.png)
使用的是Taro v2.0.4

**Comment by yuche** [comment]
你应该从 @tarojs/redux 引入 useSelector
