### ISSUE TITLE
从 1.3.22 升级到 2.0.0 后，h5 端手机视图，图标变大了。

### ISSUE THREAD

**Issue by Jeff-Tian** [NervJS/taro#5537]
### 问题描述

用手机视图打开 https://www.pa-ca.me/ ，目前是 1.3.22 版本，显示正常。
![image](https://user-images.githubusercontent.com/3367820/75150334-1da30300-573f-11ea-822f-209de7e8abcb.png)

参照 https://taro-docs.jd.com/taro/docs/migrate-to-2.html 升级到 2.0.0 后，本地跑 `npm run dev:h5`，发现界面上的图标变得很大：
![image](https://user-images.githubusercontent.com/3367820/75150492-74a8d800-573f-11ea-9eaa-cc2a0bf02102.png)

### 复现步骤

1. `git clone https://github.com/Jeff-Tian/me`
2. `npm i`
3. `npm run dev:h5` 正常视图
4. `npm checkout taro2` 
5. `npm i`
6. `npm run dev:h5` 复现图标变大的视图

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
图标不应该变大

### 报错信息
没有报错信息

### 系统信息

```
>taro info
👽 Taro v2.0.0


  Taro CLI 2.0.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\Jeff\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.6 - C:\Users\Jeff\AppData\Roaming\npm\npm.CMD
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Jeff-Tian** [comment]
对比看了一下，1.3.2 版本，html 设置了基准 font-size，图标的大小用的是 rem 单位。最终显示出来，在 Windows 10  Surface Pro 上，是 24 x 24 px。但是 2.0.0 版本，html 里没有基准 font-size，而图标的大小，css 写死是 48 x 48 px，请问，是需要额外在编译脚本里做些设置吗？

**Comment by ZakaryCode** [comment]
> 对比看了一下，1.3.2 版本，html 设置了基准 font-size，图标的大小用的是 rem 单位。最终显示出来，在 Windows 10 Surface Pro 上，是 24 x 24 px。但是 2.0.0 版本，html 里没有基准 font-size，而图标的大小，css 写死是 48 x 48 px，请问，是需要额外在编译脚本里做些设置吗？

1.x 和 2.x 的版本中，设置 html 标签的 font-size 属性值是同一套方法，不存在说一遍可以一遍不行的情况，如果当前使用的版本中没有设置 html 的 font-size，可以检查下项目目录内的 index.html 文件。

另外，taro-ui中使用的icon并不是依靠宽高决定图标大小的，而是通过 font-size 设置，且和编译没有关系，具体内容可以参考 [taro-ui](https://taro-ui.aotu.io/#/docs/icon) 的文档

**Comment by Jeff-Tian** [comment]
> 如果当前使用的版本中没有设置 html 的 font-size，可以检查下项目目录内的 index.html 文件。

两个版本的 html 文件都是一样的，如下：

参照这个迁移教程：https://taro-docs.jd.com/taro/docs/migrate-to-2.html，并没有动到 html 文件。

```
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  <meta content="width=device-width,initial-scale=1,user-scalable=no" name="viewport">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="format-detection" content="telephone=no,address=no">
  <meta name="apple-mobile-web-app-status-bar-style" content="white">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" >
</head>
<body>
  <div id="app"></div>
</body>
</html>
```

图标也没有动过，宽高变了只是结果，可能还是因为编译后的  html 的基准 font-size 没有设置造成的。
