### ISSUE TITLE
函数组件封装中展开属性无效

### ISSUE THREAD

**Issue by xiaoxintang** [NervJS/taro#5538]
### 问题描述
函数组件封装使用`...`符号展开属性，组件无法接收属性
### 复现步骤
组件代码
```tsx
import { View, Input } from "@tarojs/components";
import { InputProps } from "@tarojs/components/types/Input";
import classnames from 'classnames'
import "./search.scss"

export default function (props: InputProps) {
	const { className, placeholder, ...other } = props;
	console.log(other)
	console.log(classnames("search-con-ipt", className))
	return (
		<View className="search-con">
			<Input
				className={classnames("search-con-ipt", className)}
				placeholder={placeholder}
//问题出在这个展开里，如果把它注释掉，上面两个属性可以正常，如果不注释掉，上面两个属性不会存在
			 {...other}
			/>
		</View>
	)
}
```
1. 这是注释了展开之后的效果图
![image](https://user-images.githubusercontent.com/24927686/75161411-b98c3900-5756-11ea-85ab-9e20312b7082.png)

2. 这是没有注释展开代码的效果图

![image](https://user-images.githubusercontent.com/24927686/75161485-dcb6e880-5756-11ea-926d-c19d31bf7504.png)

### 期望行为

函数组件可以封装成`<Input {...props}/>`这种形式

### 系统信息

![image](https://user-images.githubusercontent.com/24927686/75161685-2f90a000-5757-11ea-81ec-e109da23669e.png)

**Comment by luckyadam** [comment]
没有解析这种语法，还是一个个解构出来吧

**Comment by xiaoxintang** [comment]
> 没有解析这种语法，还是一个个解构出来吧

还有 一个就是封装组件的props没有提示，上面我已经将props定义了，但是使用的时候没有属性提示，不知道是哪边的原因？

**Comment by Chen-jj** [comment]
Taro3 应该没有这个问题了。
