### ISSUE TITLE
App.js 中的render函数不能执行

### ISSUE THREAD

**Issue by super918180** [NervJS/taro#554]
Taro版本： 1.0.0-beta.21
我有一个需求，想等初始化数据完成之后再去渲染首页，这样写不行，首页在数据没有初始化完成就执行了，并且发现日志和断点都不能进入class App 里面的render函数里面

class App extends Component {
  ......

  componentWillMount() {
    this.props.globalInit()
  }

  render() {
    const {init} = this.props
    return init && `<Index />`
  }
}

Taro.render(
 ` <Provider store={store}>`
   ` <App />`
  `</Provider>`,
  document.getElementById('app')
)

**Comment by AlexStacker** [comment]
文档上有对于[入口文件](https://nervjs.github.io/taro/tutorial.html#%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6)的说明

**Comment by hqman** [comment]
@luckyadam 
你好，我在学习 taro-redux的源码，有个问题没搞明白。
'''
//app.js
  render() {
    return (
      <Provider store={store}>
        <Index />
      </Provider>
    )
  }
'''
在入口文件中 render方法中, store 赋值给Provider，然后通过 const contextValue = useContext(ReduxContext)可以拿到store。这里的Provider和如何跟ReduxContext联系在一起的？

**Comment by yuche** [comment]
> @yuche 大佬，我在学习 taro-redux的源码，有个问题没搞明白。
> 
> ```js
> //app.js
>   render() {
>     return (
>       <Provider store={store}>
>         <Index />
>       </Provider>
>     )
>   }
> ```
> 
> 在入口文件中 render方法中, store 赋值给Provider，然后通过 const contextValue = useContext(ReduxContext)可以拿到store。这里的Provider和如何跟ReduxContext联系在一起的？

这个你可以结合编译之后的代码看

**Comment by hqman** [comment]
@yuche 

看了下 在taro-transformer-wx 中对 ReduxContext 和 Provider 做了特殊处理。
如果我自己想实现一个 全局的 context(ApolloContext) 有什么好办法吗？
 
```js
 <ApolloProvider client={client}>
        <Index />
      </ApolloProvider>
```
