### ISSUE TITLE
scrollView中插入 数据，滚动条会回弹止顶部

### ISSUE THREAD

**Issue by zouyang2015** [NervJS/taro#5541]
### 问题描述
比如我有个scrollView，我在内有个list，这不是有个滚动条吗，我现在往这里插入一条数据，这个滚动条会自动回到项部？？发现这个问题，只有h5有问题，微信小程序和支付宝就OK。
试着拿掉scrollView后。再插入数据，浏览器自带滚动条不会回跳。
确认是scrollView在h5下的问题。

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
// 列表中插入数据
insert = (index) => {
    let menuLists = this.state.menuLists
    menuLists.splice(index, 0, this.props.menu.tradeUp)
    this.setState({
      menuLists
    })
  }

render() {
    const { menuLists  } = this.props
    const { scrollTop } = this.state
    return (
      menuLists.length && <View className='list-wrap'>
        <View className='scroll-wrap'>
          <View onClick={this.insert.bind(this, 3)}>插入数据</View>
          <ScrollView
            className='menu-scroll'
            scrollY
            scrollWithAnimation
            scrollTop={scrollTop}
            lowerThreshold={20}
            upperThreshold={20}
            showsVerticalScrollIndicator={false}
          >
            <View className='child-wrap'>
              <View className='lists-wrap'>
                {menuLists.length &&
                menuLists.map((item, i) => <Item key={item.id} item={item}/>)}
              </View>
            </View>
          </ScrollView>
        </View>
      </View>
    )
  }
```

### 期望行为
期望scrollView，在插入中间内容时自带滚动条不会回弹至顶部

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
在 H5 中，滚动条的位置是由开发者自己设置的，与框架无关。

你可以检查自己的代码中，在插入数据的同时，scrollTop的值，是否未更改。

**Comment by SamChangi** [comment]
same issue, 
env: h5， taro-cli: v2.2.11
只是用state来控制视图层的变化，setState之后，scrollview自动滚动到顶部了

**Comment by ZakaryCode** [comment]
> same issue,
> env: h5， taro-cli: v2.2.11
> 只是用state来控制视图层的变化，setState之后，scrollview自动滚动到顶部了

无法作为参考复现该问题，如在新版本中依旧存在该问题可以提交一个新的issue，并提供一个可复现的demo

**Comment by SamChangi** [comment]
> > same issue,
> > env: h5， taro-cli: v2.2.11
> > 只是用state来控制视图层的变化，setState之后，scrollview自动滚动到顶部了
> 
> 无法作为参考复现该问题，如在新版本中依旧存在该问题可以提交一个新的issue，并提供一个可复现的demo

弃用scrollview改用view实现scrollable，resolve。怀疑是state改变后，会重新计算height的缘故

**Comment by zhanshihua** [comment]
怎么解决的 遇到了同样的问题 只在h5会反弹
