### ISSUE TITLE
Taro@2.0.4存在将未绑定在 WXML 的变量传入 setData

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#5543]
dva中：
`programList.map(program=> (
   <Item key={program.programId} program={program}/>
 ))`
微信开发工具中体验评分：存在将未绑定在 WXML 的变量传入 setData
包括使用taro-ui中的组件也是这个问题，比如<AtAvatar customStyle={{width: '50px', height: '50px'}}/>
![微信图片_20200225114745](https://user-images.githubusercontent.com/3361732/75213326-b16ae280-57c4-11ea-82ec-0e1a873de5fc.png)

**Comment by luckyadam** [comment]
如果是列表渲染的话，建议先处理完数据，然后用处理后的数据进行渲染

**Comment by jpdan** [comment]
@luckyadam 
<Item key={program.programId} program={program}/>
能否举个例子，写个样本代码参考下

**Comment by Miantang** [comment]
假如数据比较多，这个机制会使得整个小程序变得很卡
