### ISSUE TITLE
2.0版本于leancloud兼容

### ISSUE THREAD

**Issue by LubinPark** [NervJS/taro#5546]
### 问题描述
引入leancloud，请求api，(dev)正常， 在打包（build）后测试提示 无限提示，导致页面卡死， 在2.0之前是正常的。
### 复现步骤

/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

### 报错信息

warning: .end() was calledtwice. this is not supported in superagent (这个是leancloud的提示警告)
https://github.com/LubinPark/taro_leancloud

### 系统信息

leancloud 4.2.0
taro 2.0.4
都是最新版本

### 补充信息

打包造成。dev模式下无警告，2.0版本之前都正常

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
已解决
