### ISSUE TITLE
请问下taro部分页面可以设置meta的吗

### ISSUE THREAD

**Issue by suguer** [NervJS/taro#5547]
有些H5的详情页面想动态设置meta ,例如 <meta property="og:title" content="title" /> ,但是单页面应用不确定能不能在某些页面.tsx上增加这些meta方便被收录

**Comment by luckyadam** [comment]
可以，你是用的多页模式么

**Comment by suguer** [comment]
我刚创建,这个应该是单页面模式吧,入口都在index.html.文档哪里有多页模式的相关说明吗,我找下

**Comment by suguer** [comment]
> 可以，你是用的多页模式么

我刚创建,这个应该是单页面模式吧,入口都在index.html.文档哪里有多页模式的相关说明吗,我找下
