### ISSUE TITLE
微信小程序一个文件内两个组件嵌套渲染异常

### ISSUE THREAD

**Issue by xxyuk** [NervJS/taro#5550]
### 问题描述

如下代码，子组件 Test 在微信小程序渲染不出来，H5正常

### 复现步骤
```js
// index.js  这两个组件写在同一个文件中 
class Test extends Component {
  render () {
    return <View><Text>这是显示不出来的子组件</Text></View>
  }
}
class App extends Component {
  render () {
    return <View>
父组件
<Test />
</View>
  }
}
```

### 期望行为

微信小程序能正常显示子组件

### 系统信息

Taro v2.0.3

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.3 => 2.0.3
      @tarojs/components: 2.0.3 => 2.0.3
      @tarojs/components-qa: 2.0.3 => 2.0.3
      @tarojs/mini-runner: 2.0.3 => 2.0.3
      @tarojs/router: 2.0.3 => 2.0.3
      @tarojs/taro: 2.0.3 => 2.0.3
      @tarojs/taro-alipay: 2.0.3 => 2.0.3
      @tarojs/taro-h5: 2.0.3 => 2.0.3
      @tarojs/taro-qq: 2.0.3 => 2.0.3
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3
      @tarojs/taro-swan: 2.0.3 => 2.0.3
      @tarojs/taro-tt: 2.0.3 => 2.0.3
      @tarojs/taro-weapp: 2.0.3 => 2.0.3
      @tarojs/webpack-runner: 2.0.3 => 2.0.3
      eslint-config-taro: 2.0.3 => 2.0.3
      eslint-plugin-taro: 2.0.3 => 2.0.3
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
    npmGlobalPackages:
      typescript: 3.7.4

**Comment by luckyadam** [comment]
你看看编译后的代码对不对

**Comment by Chen-jj** [comment]
升级 Taro3 再看看吧。
