### ISSUE TITLE
快应用引入自定义组件，打包之后引用的路径往上多了一层

### ISSUE THREAD

**Issue by jiongrui** [NervJS/taro#5555]
### 问题描述

快应用引入自定义组件，打包之后引用的路径往上多了一层
 

### 复现步骤
yarn dev:quickapp

### 期望行为

正常打包

### 报错信息
项目文件目录：
![image](https://user-images.githubusercontent.com/30332228/75315947-0c710800-589f-11ea-9313-a0359c04a156.png)

打包之后：
![image](https://user-images.githubusercontent.com/30332228/75315051-8489fe80-589c-11ea-977d-916b19c3e0c5.png)

### 系统信息

Taro v2.0.4

  Taro CLI 2.0.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 13.1.0 - ~/.nvm/versions/node/v13.1.0/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v13.1.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.4 => 2.0.4 
      @tarojs/components-qa: 2.0.4 => 2.0.4 
      @tarojs/mini-runner: 2.0.4 => 2.0.4 
      @tarojs/router: 2.0.4 => 2.0.4 
      @tarojs/taro: 2.0.4 => 2.0.4 
      @tarojs/taro-alipay: 2.0.4 => 2.0.4 
      @tarojs/taro-h5: 2.0.4 => 2.0.4 
      @tarojs/taro-qq: 2.0.4 => 2.0.4 
      @tarojs/taro-quickapp: 2.0.4 => 2.0.4 
      @tarojs/taro-rn: 2.0.4 => 2.0.4 
      @tarojs/taro-swan: 2.0.4 => 2.0.4 
      @tarojs/taro-tt: 2.0.4 => 2.0.4 
      @tarojs/taro-weapp: 2.0.4 => 2.0.4 
      @tarojs/webpack-runner: 2.0.4 => 2.0.4 
      eslint-config-taro: 2.0.4 => 2.0.4 
      eslint-plugin-taro: 2.0.4 => 2.0.4 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.4 => 2.0.4 
      stylelint-taro-rn: 2.0.4 => 2.0.4 
    npmGlobalPackages:
      typescript: 3.7.5

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
确实多了一层，不过路径倒是对的~

**Comment by jiongrui** [comment]
坐等大佬修复了 [吃瓜]
