### ISSUE TITLE
Hooks onAppShow 中获取不到 prop 传递的函数问题

### ISSUE THREAD

**Issue by WuYunlong** [NervJS/taro#5557]
组件文件代码：
```javascript
import Taro,{onAppShow, useState} from '@tarojs/taro'
import {View} from '@tarojs/components'

function Zf5uPay ({success}) {
    onAppShow(options => {
        success() // 此处无法获取到传递进来到 success 函数
    }
}

export default Zf5uPay
```

页面文件代码：
``` javascript
import Taro from '@tarojs/taro'
import Zf5uPay from '../components/Zf5uPay';

function Demo ()
{
    const paySuccess = (res)  => {
        console.log('paySuccess', res)
    }

    return (
        <Zf5uPay success={paySuccess}>
          <Button>点击支付</Button>
        </Zf5uPay>
    )
}

export default Demo;
```

对应小程序实现代码，以下是小程序到实现方式。可以实现在onAppShow 中执行传递的方法,使用 triggerEvent 来进行执行

``` javascript
Component({
    methods: {
        
    },
   lifetimes: {
       attached() {
           wx.onAppShow(options => {
               this.triggerEvent('success', {a:1, b:2})
           })
       }
   }
})
```

**Comment by luckyadam** [comment]
有 onAppShow 这个 Hook？
是 `useDidShow` 吧

**Comment by WuYunlong** [comment]
@luckyadam 有啊  而且我现在在组件里面是好用的 ，能获取到options里面到数据
展示后续到操作不好用
这个最主是解决我跳转到其它小程序 其它小程序处理完成之后返回给我携带数据的。

**Comment by WuYunlong** [comment]
@luckyadam

**Comment by WuYunlong** [comment]
@luckyadam 

我在详细的描述下我的需求吧
现在是这样的，我的小程序A需要打开别的小程序B，打开之后B做一系列操作的时候会返回到A且携带参数。我需要在 小程序A中获取到这些参数。referrerInfo: {appId: '', extraData:{}} 

所以我想以组件的方式加入到A小程序，再引入组件到时候直接在wx.onAppShow中添加一个数据操作，因为只有在onAppShow 中我才能获取到小程序打开时候到参数 referrerInfo

你说到这个useDidShow 我在使用过程中发现无法获取到应用打开的参数 referrerInfo，所以我看@tarojs/taro 里面有一个 onAppShow 并且在组件中使用，可以获取到 referrerInfo 但是此时无法获取到组件传递进来到参数 success

**Comment by luckyadam** [comment]
你说的这个 referrerInfo 应用用 `useRouter` 这个 hooks 获取

**Comment by WuYunlong** [comment]
@luckyadam 在组件里面 useRouter 无法获取到 referrerInfo

只有 params 和 path  且 params={} path=""
