### ISSUE TITLE
Taro 怎样开发自定义 tabBar

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#5558]
如何以 Taro 的方式书写自定义 tabBar

**Comment by ShaoGongBra** [comment]
自己写呗，我自己写了一个

**Comment by binlaniua** [comment]
> 自己写呗，我自己写了一个

我感觉楼主是问如何custom-tabar, 而不是自己模拟tabbar

https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html
