### ISSUE TITLE
RN组件Picker有bug

### ISSUE THREAD

**Issue by hujingyuki** [NervJS/taro#5561]
### 问题描述

1、Picker在mode=date时如果不传入start和end组件默认时间为2000.1.1
2、Picker不可选

### 复现步骤

```js
<Picker mode='date' name='time'  className='input-area' onChange={this.onDateChange}>
            {!date ? <Text className='inner-picker placeholer'>请选择</Text>
              :<Text className='inner-picker'>{date}</Text>}
          </Picker>
```

### 期望行为
1、不给start，end时和文档描述一致

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by hujingyuki** [comment]
不小心提交了，补充如下
**期望行为：**
1、不给start，end时和文档描述一致
2、picker滚动后可以选中，目前滚动后会自动回到当前日期

**系统信息：**
Taro 2.0.4

**补充信息：**
问题1：picker组件源码中开始时间和结束时间格式化都用的同一个函数，如下所示
`function formatTimeStr(time = '') {
    let [year, month, day] = time.split('-');
    year = ~~year || 2000;
    month = ~~month || 1;
    day = ~~day || 1;
    return new Date(`${year}/${month}/${day}`);
}`

问题2：onvaluechange事件触发setstate后，render函数中state的值并没有更新（selector也有这个问题）

**Comment by Pines-Cheng** [comment]
我来看看
