### ISSUE TITLE
请问一下 Taro2.0.x 组件引用的scss 都没有了 变成了common.wxss

### ISSUE THREAD

**Issue by liuyaochen04** [NervJS/taro#5562]
请问一下 Taro2.0.x
组件引用的scss 都没有了
变成了common.wxss
但是class都引用不到 有人知道啥原因吗

![1111111.png](https://img12.360buyimg.com/img/jfs/t1/86632/9/13352/48098/5e5720bdE1249d482/7a363cb6392bedcf.png) 

都变成了这个

![2222222.png](https://img13.360buyimg.com/img/jfs/t1/88274/39/13409/6938/5e5720caEc7ea26d1/e3fe198207fba52d.png) 

![3333333.png](https://img11.360buyimg.com/img/jfs/t1/107996/29/7120/27543/5e5720dcE187d757b/d54a86c623406bb0.png) 

之前1.3.x 没有这个common.wxss 

父子组件：
import './index.scss';
import ChooseGroup from '../../components/ChooseGroup';
import RadioTemplate from '../../components/RadioTemplate';
import CheckboxTemplate from '../../components/CheckboxTemplate';
import TextareaTemplate from '../../components/TextareaTemplate';
import TextTemplate from '../../components/TextTemplate';
import DateTemplate from '../../components/DateTemplate';

子组件
import Taro, {useState, useEffect} from '@tarojs/taro'
import {CheckboxGroup, Checkbox, Label} from '@tarojs/components'
import '../pages/SqList/index.scss'

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86

**Comment by zuibunan** [comment]
@luckyadam 开发模式下生成的页面样式会自动import common.scss，编译后页面的样式里没有import common.scss了
我用的 taro 2.1.3

**Comment by zuibunan** [comment]
> https://nervjs.github.io/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86

@luckyadam 我在开发模式下，页面样式会自动import common.wxss，但是编译后没有生成app.wxss，页面也不会自动import common.wxss了

**Comment by buffge** [comment]
> > https://nervjs.github.io/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86
> 
> @luckyadam 我在开发模式下，页面样式会自动import common.wxss，但是编译后没有生成app.wxss，页面也不会自动import common.wxss了

+1

**Comment by Lovely-wood** [comment]
> > > https://nervjs.github.io/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86
> > 
> > 
> > @luckyadam 我在开发模式下，页面样式会自动import common.wxss，但是编译后没有生成app.wxss，页面也不会自动import common.wxss了
> 
> +1

+1 请问有什么解决方案？

**Comment by ninetowns** [comment]
而且还不是所有页面的样式都没有，只是部分

**Comment by zuibunan** [comment]
@Lovely-wood @buffge @luckyadam 
我现在是使用开发模式生成的代码，小程序选择上传时自动压缩，会比编译生成的代码大点儿但显示正常
