### ISSUE TITLE
编译返回成功后,在百度小程序打开一片空白

### ISSUE THREAD

**Issue by suguer** [NervJS/taro#5563]
在百度小程序打开一片空白,console控制台上没有看到报错

页面文件.swan
<block s-if="{{$taroCompReady}}">
    <index compid="{{$compid__0}}"></index>
</block>
编译后在AppData上看到$compid__0为0

### 复现步骤

1. 
2. 
3. 
4. 

```js
yunfang@1.0.0 build:swan D:\phpserver\website\yunfang

taro build --type swan

👽 Taro v2.0.4

开始编译项目 yunfang
生成 工具配置 dist/swan/project.swan.json
生成 框架信息 dist/swan/.frameworkinfo

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
编译 发现入口 src/app.jsx
编译 发现页面 src/pages/index/index.swan.jsx
✅ 编译成功，请打开百度智能小程序开发者工具进行查看

Hash: fe5cf2a501391a294ec7
Version: webpack 4.41.6
Time: 8572ms
Built at: 2020-02-27 10:43:52
Asset Size Chunks Chunk Names
/app.json 180 bytes [emitted]
/pages/index/index.swan.json 54 bytes [emitted]
/pages/index/index.swan.swan 86 bytes [emitted]
app.css 139 KiB 3 [emitted] app
app.js 2.16 KiB 3 [emitted] app
common.css 189 bytes 0 [emitted] common
common.js 78 bytes 0 [emitted] common
pages/index/index.swan.css 865 bytes 4 [emitted] pages/index/index.swan
pages/index/index.swan.js 11.7 KiB 4 [emitted] pages/index/index.swan
runtime.js 1.91 KiB 1 [emitted] runtime
vendors.js 63.5 KiB 2 [emitted] vendors
Entrypoint app = runtime.js vendors.js common.css common.js app.css app.js
Entrypoint pages/index/index.swan = runtime.js vendors.js common.css common.js pages/index/index.swan.css pages/index/index.swan.js


```

### 期望行为

正常显示界面和数据

### 报错信息

没任何报错信息,就是百度开发工具打开一片空白

### 系统信息

taro info
👽 Taro v2.0.4

  Taro CLI 2.0.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\nodejs\node.EXE
      npm: 6.13.7 - D:\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by suguer** [comment]
页面文件是
<block s-if="{{$taroCompReady}}">
<index compid="{{$compid__0}}"></index>
</block>

**Comment by suguer** [comment]
`<block s-if="{{$taroCompReady}}">
<index compid="{{$compid__0}}"></index>
</block>`

**Comment by suguer** [comment]
控制台输出这些
`> yunfang@1.0.0 build:swan D:\phpserver\website\yunfang
> taro build --type swan

👽 Taro v2.0.4

开始编译项目 yunfang
生成  工具配置  dist/swan/project.swan.json
生成  框架信息  dist/swan/.frameworkinfo

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
编译  发现入口  src/app.jsx
编译  发现页面  src/pages/index/index.swan.jsx
✅  编译成功，请打开百度智能小程序开发者工具进行查看

Hash: fe5cf2a501391a294ec7
Version: webpack 4.41.6
Time: 8572ms
Built at: 2020-02-27 10:43:52
                       Asset       Size  Chunks             Chunk Names
                   /app.json  180 bytes          [emitted]
/pages/index/index.swan.json   54 bytes          [emitted]
/pages/index/index.swan.swan   86 bytes          [emitted]
                     app.css    139 KiB       3  [emitted]  app
                      app.js   2.16 KiB       3  [emitted]  app
                  common.css  189 bytes       0  [emitted]  common
                   common.js   78 bytes       0  [emitted]  common
  pages/index/index.swan.css  865 bytes       4  [emitted]  pages/index/index.swan
   pages/index/index.swan.js   11.7 KiB       4  [emitted]  pages/index/index.swan
                  runtime.js   1.91 KiB       1  [emitted]  runtime
                  vendors.js   63.5 KiB       2  [emitted]  vendors
Entrypoint app = runtime.js vendors.js common.css common.js app.css app.js
Entrypoint pages/index/index.swan = runtime.js vendors.js common.css common.js pages/index/index.swan.css pages/index/index.swan.js`

**Comment by suguer** [comment]
执行npm run build:swan 是没问题的,但是界面就是空白

**Comment by lp13762436965** [comment]
我也碰到这个问题了.... 升级到2.x之后

**Comment by chajianyuan** [comment]
我也遇到这个问题了，请问楼主解决了吗？
