### ISSUE TITLE
[Taro 3.0.0-alpha.5]  使用 async/await 关键字报错

### ISSUE THREAD

**Issue by molvqingtai** [NervJS/taro#5570]
### 问题描述

Taro 3.0.0-alpha.5 支付宝小程序使用 async/await 关键字报错

### 复现步骤

在 Vue 组件 methods 中使用 async/await 会报错，改为 Promise 则正常。

page/index/index.vue:

```js
<script>
import { mapGetters, mapActions } from 'vuex'
import httpRequest from '@/apis'
export default {
  name: 'Index',
  components: {
  },
  computed: {
    ...mapGetters(['userInfo'])
  },
  methods: {
    // 报错
    async fetchIndexData () {
      const res = await httpRequest()
      console.log('data', res)
    },

    // 正常
    // fetchIndexData () {
    //   httpRequest().then(res => {
    //     console.log('res', res)
    //   })
    // },
    ...mapActions(['updateUserInfo'])
  },
  created () {
    this.updateUserInfo()
    this.fetchIndexData()
  }
}
</script>

```

### 期望行为

默认支持 async/await 关键字

### 报错信息

![image](https://user-images.githubusercontent.com/26295698/75428866-cc378580-5983-11ea-8ea6-ccd5889b2dfd.png)

### 系统信息

👽 Taro v3.0.0-alpha.5

  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v12.11.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.5 => 3.0.0-alpha.5 
      @tarojs/taro: 3.0.0-alpha.5 => 3.0.0-alpha.5 
      eslint-config-taro: 3.0.0-alpha.5 => 3.0.0-alpha.5

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/migrate-to-2.html#%E4%BD%BF%E7%94%A8-async-await-%E6%97%B6%E5%87%BA%E7%8E%B0%E6%8A%A5%E9%94%99-function-is-not-a-function
项目下安装一下这个吧
npm i --save regenerator-runtime@0.11.1

**Comment by molvqingtai** [comment]
谢谢，问题解决了
