### ISSUE TITLE
【Taro 2.0.5 微信小程序插件】打包后未找到 plugin.json 中的定义的 main "index.js" 

### ISSUE THREAD

**Issue by jackie-gan** [NervJS/taro#5571]
### 问题描述

微信小程序插件打包后，plugin文件夹缺少index.js，开发者工具提示`打包后未找到 plugin.json 中的定义的 main "index.js" `

### 复现步骤

1.  taro init一个微信小程序插件工程
2. 执行taro build --plugin weapp --watch
3. 打开微信开发者工具，导入项目，并填写好插件的appId
4. 运行后，出现报错信息`打包后未找到 plugin.json 中的定义的 main "index.js" `

### 期望行为

构建后的目录`plugin`下存在index.js，并且能正常运行小程序插件

### 报错信息

![image](https://user-images.githubusercontent.com/9361107/75434907-3a347a80-598d-11ea-870d-034302688544.png)

### 系统信息

Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.7.2

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by CPPAlien** [comment]
```
webpackChain (chain, webpack) {
      chain.merge({
        optimization: {
          splitChunks: {
            cacheGroups: {
              pluginIndex: {
                name: 'plugin/index',
                priority: 1000,
                test (module) {
                  return /src[\\/]plugin[\\/]sdk/.test(module.context)
                }
              }
            }
          }
        }
      })
    },
```

**Comment by jackie-gan** [comment]
Taro 2.1.0已解决
