### ISSUE TITLE
worker配置无效，编译后dist目录没有workers目录

### ISSUE THREAD

**Issue by itcat99** [NervJS/taro#5572]
### 问题描述

worker配置无效，编译后dist目录没有workers目录

### 复现步骤

1. 新建src/workers目录，新建index.ts
2. 配置app.config的workers字段为'workers'
3. index.tsx中Taro.createWorker("workers/index.ts");
4. yarn dev:weapp 
5. dist目录没有worker目录，微信IDE提示'workers 字段需为目录'

### 期望行为

workers正常使用

### 报错信息

workers 字段需为 目录

### 系统信息

Taro CLI 2.0.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.1.0 - ~/.nvm/versions/node/v13.1.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v13.1.0/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v13.1.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.4 => 2.0.4 
      @tarojs/components-qa: 2.0.4 => 2.0.4 
      @tarojs/mini-runner: 2.0.4 => 2.0.4 
      @tarojs/router: 2.0.4 => 2.0.4 
      @tarojs/taro: 2.0.4 => 2.0.4 
      @tarojs/taro-alipay: 2.0.4 => 2.0.4 
      @tarojs/taro-h5: 2.0.4 => 2.0.4 
      @tarojs/taro-qq: 2.0.4 => 2.0.4 
      @tarojs/taro-quickapp: 2.0.4 => 2.0.4 
      @tarojs/taro-rn: 2.0.4 => 2.0.4 
      @tarojs/taro-swan: 2.0.4 => 2.0.4 
      @tarojs/taro-tt: 2.0.4 => 2.0.4 
      @tarojs/taro-weapp: 2.0.4 => 2.0.4 
      @tarojs/webpack-runner: 2.0.4 => 2.0.4 
      eslint-config-taro: 2.0.4 => 2.0.4 
      eslint-plugin-taro: 2.0.4 => 2.0.4 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.4 => 2.0.4 
      stylelint-taro-rn: 2.0.4 => 2.0.4 

### 补充信息
无

**Comment by ElegantBrick** [comment]
请问有同学解决了没？

**Comment by tourze** [comment]
同关注这个问题

**Comment by Arima-P** [comment]
Taro 3.0.5 同样遇到这个问题，workers文件夹没有被打包进dist目录！
```
// app.config.ts
{
  workers: 'workers'
}
```
@Chen-jj

**Comment by Arima-P** [comment]
初步尝试了下，可以将Workers文件夹（手动）直接复制到打包好的代码里面，能够正常运行

**Comment by gaotongjian** [comment]
可以尝试使用webpack插件copy-webpack-plugin去解决，我这边是taro 2.2.x。

构建配置/config/index.js

```js
const config = {
  // ...
  mini: {
    // ...
    webpackChain(chain, webpack) {
      chain.merge({
        plugin: {
          copyPlugin: {
            plugin: require('copy-webpack-plugin'),
            args: [
              {patterns: [{ from: path.resolve(__dirname, '../src/workers'), to: `workers`  }]}
            ]
          }
        }
      })
    }
  }
}
```

**Comment by Chen-jj** [comment]
配置一下 `copy`，复制到 dist 目录吧。https://taro-docs.jd.com/taro/docs/config-detail#copy

**Comment by TokeyJerry** [comment]
> 配置一下 `copy`，复制到 dist 目录吧

@Chen-jj 

1、直接  copy 是有问题的，不会编译就拷贝了，导致拷贝后的文件不能编译压缩，也不能引用  node_modules 下的内容；
2、如果编译后拷贝，那么编译后的代码都没有目录了

请问，还有什么解决方案么

**Comment by zhj296409022** [comment]
这个问题解决了吗，现在打包好像还是不能自动编译输出
