### ISSUE TITLE
升级2.0之后使用<import />提示路径未找到，未打包进去？

### ISSUE THREAD

**Issue by heartAndRain** [NervJS/taro#5577]
### 问题描述
升级到2.0之后，在组件内使用诸如这样的引用
`<import src='../wxParse/wxParse.wxml' />`
打包后运行会提示该src找不到，看编译后的结果确实没有打包进去

### 复现步骤

复现步骤如上

### 期望行为

期望该类引用能够正确打包

### 报错信息

字节小程序内和百度小程序内均报资源未找到

### 系统信息

Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.5 => 2.0.5 
      @tarojs/components: 2.0.5 => 2.0.5 
      @tarojs/mini-runner: 2.0.5 => 2.0.5 
      @tarojs/mobx: 2.0.5 => 2.0.5 
      @tarojs/mobx-h5: 2.0.5 => 2.0.5 
      @tarojs/mobx-rn: 2.0.5 => 2.0.5 
      @tarojs/plugin-babel: 2.0.5 => 2.0.5 
      @tarojs/plugin-csso: 2.0.5 => 2.0.5 
      @tarojs/plugin-less: 2.0.5 => 2.0.5 
      @tarojs/plugin-uglifyjs: 2.0.5 => 2.0.5 
      @tarojs/rn-runner: 2.0.5 => 2.0.5 
      @tarojs/router: 2.0.5 => 2.0.5 
      @tarojs/taro: 2.0.5 => 2.0.5 
      @tarojs/taro-alipay: 2.0.5 => 2.0.5 
      @tarojs/taro-h5: 2.0.5 => 2.0.5 
      @tarojs/taro-swan: 2.0.5 => 2.0.5 
      @tarojs/taro-tt: 2.0.5 => 2.0.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      @tarojs/webpack-runner: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      eslint-plugin-taro: 2.0.5 => 2.0.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.5 => 2.0.5 
      stylelint-taro-rn: 2.0.5 => 2.0.5 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
使用 `copy` 拷贝一下文件 https://taro-docs.jd.com/taro/docs/config-detail.html#copy

另外 `wxml` 原生模板也能在字节和百度里用吗？

**Comment by heartAndRain** [comment]
> 使用 `copy` 拷贝一下文件 https://taro-docs.jd.com/taro/docs/config-detail.html#copy
> 
> 另外 `wxml` 原生模板也能在字节和百度里用吗？

ok，那只能用copy了
wxml在字节里面可以用，百度里面不行

**Comment by luckyadam** [comment]
2.0.5 应该解决了才对

**Comment by ruofeng086** [comment]
@luckyadam 解决了吗？2.1.0还有这个问题...

**Comment by hnsylitao** [comment]
@luckyadam 发现了一个问题import 只会解读第一个，第二个就不解读了

**Comment by wingsico** [comment]
啊啊啊为什么还没解决啊，求解决 @luckyadam

**Comment by wingsico** [comment]
@luckyadam 花了一晚上，找到了这个问题所在，待会提个PR，改动很小
