### ISSUE TITLE
[Taro v3.0.0-alpha.5] 不同页面引入公共组件，CSS 不能正确打包

### ISSUE THREAD

**Issue by molvqingtai** [NervJS/taro#5582]
### 问题描述

不同页面引入公共组件，组件能正常加载，但是 CSS 丢失，当把一个页面引入的公共组件注释，另一个页面则能正常显示

### 复现步骤

公共组件: @/common/header-bar.vue

```js
<template lang="html">
  <view class="header" style="200px">
    <view class="header-logo"></view>
  </view>
</template>

<script>
export default {
  name: 'HeaderBar',
}
</script>

<style lang="scss">
.header{
  .header-logo{
    height: 80px;
    padding-top: 36px;
    background-color: #7562E1;
    border-bottom: 1px dashed #A094EC;
    position: relative;
    &::after, &::before{
      content: "";
      position: absolute;
      width: 110px;
      height: 44px;
      background-color: #A094EC;
      border-radius: 22px;
      bottom: 16px;
    }
    &::after{
      left: -30px;
    }
    &::before{
      left: 200px;
    }
  }
}

</style>

```

页面 1：pages/index/index.vue

```js
  <view class="index">
    <header-bar></header-bar>
  </view>
	import HeaderBar from '@/common/header-bar.vue'
	export default {
	  name: 'Index',
	  components: {
	    HeaderBar
	  },
	}
```
页面 2：pages/order/order.vue

```js
  <view class="order">
    <header-bar></header-bar>
  </view>
	import HeaderBar from '@/common/header-bar.vue'
	export default {
	  name: 'Order',
	  components: {
	    HeaderBar
	  },
	}
```

### 期望行为

正常打包组件 CSS

### 报错信息
CSS 样式丢失

![image](https://user-images.githubusercontent.com/26295698/75549617-0d569500-5a6b-11ea-9f9a-f1e0d5d34ac3.png)

### 系统信息

👽 Taro v3.0.0-alpha.5

  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v12.11.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.5 => 3.0.0-alpha.5 
      @tarojs/taro: 3.0.0-alpha.5 => 3.0.0-alpha.5 
      eslint-config-taro: 3.0.0-alpha.5 => 3.0.0-alpha.5

**Comment by Chen-jj** [comment]
@molvqingtai beta 最新版已经修复，可以更新后再试试
![image](https://user-images.githubusercontent.com/11807297/79303912-b45f9500-7f22-11ea-9a50-9c6c108e58d3.png)

**Comment by liurenqiu520** [comment]
解决个鸡毛，我也出现这个问题了。

**Comment by zprial** [comment]
+1，v3.0.14还有这个问题

**Comment by HelloWorld20** [comment]
发现个情况，也许能帮助各位

`入口文件必须有个css文件`

webpack打包后会把公共css都抽离到根目录的`common.wxss`里。 然后都统一在app.wxss里`@import "./common.wxss";`如果源码里没有 app.less（假设用的less预处理器)，打包后也没有app.wxss，就会导致没有文件引入公共样式代码。 Taro也没给新建个'app.wxss'。

@taro-bot 建议自动生成app.wxss
