### ISSUE TITLE
es6编译报错问题

### ISSUE THREAD

**Issue by jusheng** [NervJS/taro#5585]
### 问题描述

![image](https://user-images.githubusercontent.com/20462348/75608727-3c3d3b80-5b3d-11ea-8add-f9b4d45797cf.png)

### 复现步骤

编译过程出现，版本2.0.5

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
看起来是 babel 没有配置好，建议看看 2.x 的迁移文档
