### ISSUE TITLE
如何写reactnative 原生代码 获取硬件信息 判断是否运行xp框架？ 调用现有的reactnative库

### ISSUE THREAD

**Issue by vanxv** [NervJS/taro#5587]
如何写reactnative 原生代码 获取硬件信息 判断是否运行xp框架？ 调用现有的reactnative库

**Comment by Pines-Cheng** [comment]
参考这里：[跨平台开发](https://nervjs.github.io/taro/docs/envs.html#%E7%BB%9F%E4%B8%80%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6)

react native 库本质上也是通过 JS 代码调用的，只需要将这部分代码写成跨端代码，在其他端就不会被编译了。

**Comment by vanxv** [comment]
@Pines-Cheng 

我可能没有表达清楚我的需求。不好意思
需要用android和ios获取以下信息

*  ios 判断是否root
*  android
     * 判断是否root
     * 是否安装xposed框架。
     * 获取通讯录信息。


怎么实现这些 原生的功能？

给写原生代码的办法。编译进去就行。
