### ISSUE TITLE
0.59 500 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#5589]
0.59 ios pod install之后执行archive会报这个错误
删除Libraries下的所有引用，用pod管理，之后能正常打包

**Comment by Pines-Cheng** [comment]
感谢反馈，看起来像是 pod 依赖安装的问题。

**Comment by ShaoGongBra** [comment]
删除那些依赖后调试模式又会报错，xcode上下面类似的的提示，点击更新一下，之后就能正常调试了
![WechatIMG65](https://user-images.githubusercontent.com/31879769/75663762-50537b00-5cac-11ea-8293-4f8057771723.png)
