### ISSUE TITLE
请问ios如何禁止页面整体滚动？

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#5590]
```
<View className='page-root' style={{backgroundColor: 'blue'}}>
        <Header title='标题' />
// 这个组件是会自动占据剩余空间的滚动组件
        <Scroll>
        <View style={{height: Taro.pxTransform(10000)}} />
        </Scroll>
        <View style={{height: Taro.pxTransform(50),backgroundColor: 'red'}} />
</View>
```
显示效果如下，我可以拉着整个页面向下滑动，怎么禁止他，页面上有这个配置，但是似乎没有作用
```
static config = {
    disableScroll: true
  }
```
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-02 at 11 26 04](https://user-images.githubusercontent.com/31879769/75643042-9ee72200-5c78-11ea-8fcf-bde8090e490c.png)

**Comment by Pines-Cheng** [comment]
如果页面需要禁止滚动或者自定义滚动，可以在 Page 的 config 里面添加：disableScroll:true，这样就不会默认在页面上套 ScrollView 了。

**Comment by ShaoGongBra** [comment]
2.0.5   我加了这两个还是不起作用呀，不知道是不是我加的有问题
```
static config = {
    disableScroll: true
  }
  
  config = {
    disableScroll: true
  }
```
@Pines-Cheng

**Comment by ShaoGongBra** [comment]
我用debug工具看了，他外面确实有一层scrollview，这个配置似乎没用
![WX20200302-175206](https://user-images.githubusercontent.com/31879769/75665112-9ad5f700-5cae-11ea-95f0-9e73bbfb8a72.png)

**Comment by ShaoGongBra** [comment]
在rn上这两个属性具有相同的作用，我看他编译后设置了两遍config，被覆盖了，这个本来应该是不同的作用的吧，不知为何会变成同一个东西
@Pines-Cheng 
```
static config = {
    disableScroll: true
  }

  config = {
    navigationBarTitleText: '列表'
  }
```

```
List.config = {
  disableScroll: true
};
List.config = {
  navigationBarTitleText: '列表'
};
```
