### ISSUE TITLE
关于触摸事件的typescript类型的修改

### ISSUE THREAD

**Issue by BUPTlhuanyu** [NervJS/taro#5592]
### 问题描述

@tarojs\components\types\common.d.ts文件中对触摸事件的类型声明不太准确

### 复现步骤

1. 打开@tarojs\components\types\common.d.ts文件
2. 接口类型ITouchEvent中touches以及changedTouches类型在不一样
3. 微信小程序中这两者应该是一样的，h5也是一样的
4. 其他小程序可能有些属性不存在

```js
/**
export interface ITouchEvent extends BaseEventOrig<any> {
  /**
   * 触摸事件，当前停留在屏幕中的触摸点信息的数组
   */
  touches: Array<ITouch>,

  /**
   * 触摸事件，当前变化的触摸点信息的数组
   */
  changedTouches: Array<CanvasTouch>
}
 */

changedTouches 数据格式同 touches。 表示有变化的触摸点，如从无变有（touchstart），位置变化（touchmove），从有变无（touchend、touchcancel）。
```

### 期望行为

微信小程序以及h5的时候两者应该是同一类型

### 报错信息

无

### 系统信息

Taro2.0

### 补充信息

这里应该严谨一些，考虑其他小程序端的触摸事件都有哪些属性。

**Comment by ZakaryCode** [comment]
没太懂你的意思，不过目前的类型同步自 [微信官方](https://github.com/wechat-miniprogram/api-typings)，又更好的想法也欢迎 PR。
