### ISSUE TITLE
taro next版本更新cli本身出现降级问题

### ISSUE THREAD

**Issue by xgaxpp** [NervJS/taro#5594]
### 问题描述
taro next 版本cli 通过 update self命令更新，重新更新会2.0.5版本

### 复现步骤
1.执行taro update self

### 期望行为
在该版本下进行更新

### 报错信息

无

### 系统信息

windows 10

**Comment by Garfield550** [comment]
https://taro-docs.jd.com/taro/docs/GETTING-STARTED.html#%E6%9B%B4%E6%96%B0

```shell
# taro
$ taro update self [version]
# npm
npm i -g @tarojs/cli@[version]
# yarn
yarn global add @tarojs/cli@[version]
```
