### ISSUE TITLE
taro convert 以后，代码中的图片常量直接编译成了 require

### ISSUE THREAD

**Issue by livoras** [NervJS/taro#5597]
原来如此：

![image](https://user-images.githubusercontent.com/6436132/75668607-8563cb80-5cb4-11ea-9d21-92f0f8c4a5a3.png)

`taro convert` 编译以后：

![image](https://user-images.githubusercontent.com/6436132/75668647-96144180-5cb4-11ea-8656-128b4969a8ee.png)

**Comment by Chen-jj** [comment]
正确的，require 了 webpack 才会把图片资源经 loader 处理、打包。
