### ISSUE TITLE
【Taro 2.0.4】百度小程序组件swan后缀不识别

### ISSUE THREAD

**Issue by hujingyuki** [NervJS/taro#5599]
### 【Taro 2.0.4】百度小程序组件swan后缀不识别，当组件中同时存在index.jsx以及index.swan.jsx时，npm dev:swan命令仍然编译的index.jsx，且修改index.swan.jsx并不会被监听到文件的修改从而触发编译

**Comment by luckyadam** [comment]
具体是如何使用，以及文件是如何组织的，请给出示意图
