### ISSUE TITLE
taro打包apk问题

### ISSUE THREAD

**Issue by somnuslbl** [NervJS/taro#5603]
### 问题描述

taro按照官方文档打包apk，安装到真机上后闪退。编译后的rn_temp文件是需要放到taro-native-shell目录里的。
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

建议把react-native的编译、打包做得更详细些
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by aoarashi1988** [comment]
闪退可以使用 adb logcat打印一下具体报错信息，不然他人无法帮助你判断问题出在哪里

**Comment by Pines-Cheng** [comment]
更新了打包 APP 的文档：

### 生成 React Native 离线包（jsbundle）

在打包成 ipa 或 apk 应用包之前，我们先要得到 React Native 离线包：

* 方式一：

``` bash
taro build --type rn
```
然后会生成 `rn_bundle` 目录，目录下会生成的 React Native 离线包，也就是打包后的 js。

└── rn_bundle （或 rn_temp/bundle）
    ├── assets
    ├── index.bundle
    └── index.bundle.meta

* 方式二：


使用 React Native 的 bundle 命令将 rn_temp 目录下的 RN 代码及资源打包成 jsbundle，命令如下：

```sh
node ./node_modules/react-native/local-cli/cli.js bundle --entry-file ./rn_temp/index.js --bundle-output ./rn_bundle/index.bundle --assets-dest ./rn_bundle --dev false
```

其中参数可以自行调整，`--bundle-output` 可以制定任意目录，然后将 bundle 目录下的文件 copy 到 `taro-native-shell`目录即可。

当然，也可以通过指定 `--bundle-output` 直接输出到 `taro-native-shell`目录。


### 通过 React Native 离线包构建 APP

一般来说，主要就三步：

1. copy 生成的 jsbundle 到 React Native 工程对应目录下，如：taro-native-shell 工程或自己的 React Native 工程
2. 修改对应的入口文件的 Bundle 名称，如 iOS 的 `AppDelegate.m` 文件，Android 的 `MainApplication` 文件
3. 通过 React Native 命令或者对应的 IDE （Xcode/Android Studio） 打包 APP。

搜索 React Native 离线包 ，可以得到很多操作指引和教程，这里不再赘述，以下两篇可以借鉴：

* iOS 可以参考：[ReactNative - 打离线包 (一) 原生RN命令打包](https://www.jianshu.com/p/bb7c5f1d304e)
* Android 可以参考：[ReactNative打离线包-android篇](https://www.jianshu.com/p/ba6cbbe9c677)
