### ISSUE TITLE
Taro.request() abort is not a function

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#5604]
### 复现步骤

  看代码

```js
  const requestTask = Taro.request({ url: 'xxx' });
  requestTask.abort();


```

### 期望行为

正常调用
### 报错信息

requestTask.abort is not a function
### 系统信息

 Taro CLI 2.0.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvs/default/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.4 => 2.0.4 
      @tarojs/components: 2.0.4 => 2.0.4 
      @tarojs/plugin-babel: 2.0.4 => 2.0.4 
      @tarojs/plugin-csso: 2.0.4 => 2.0.4 
      @tarojs/plugin-sass: 2.0.4 => 2.0.4 
      @tarojs/plugin-uglifyjs: 2.0.4 => 2.0.4 
      @tarojs/redux: 2.0.4 => 2.0.4 
      @tarojs/redux-h5: 2.0.4 => 2.0.4 
      @tarojs/router: 2.0.4 => 2.0.4 
      @tarojs/taro: 2.0.4 => 2.0.4 
      @tarojs/taro-h5: 2.0.4 => 2.0.4 
      @tarojs/taro-weapp: 2.0.4 => 2.0.4 
      @tarojs/webpack-runner: 2.0.4 => 2.0.4 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yulrosy** [comment]
用AbortController解决了

**Comment by fwh1990** [comment]
应该内置到taro框架里，统一api
