### ISSUE TITLE
关于打包后项目本地图片全部打入主包造成超限的问题

### ISSUE THREAD

**Issue by GrantXiao** [NervJS/taro#5605]
### 问题描述
以前1.3.18版本，分包的本地图片是打入子包的，现在升级到2.0.5版本，全部打入主包了，造成主包超限，并且打包多出来一个Image文件夹
### 复现步骤

![image](https://user-images.githubusercontent.com/36841234/75772628-45b9e400-5d87-11ea-9449-7705b1e48797.png)
### 期望行为

期望回到以前低版本那么做吧，或者说有什么好的解决办法。因为项目本身原因，存在比较多本地资源图片，暂时不考虑图片放服务器

### 报错信息
![image](https://user-images.githubusercontent.com/36841234/75772928-d1cc0b80-5d87-11ea-95e9-b309b51700af.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by GrantXiao** [comment]
![image](https://user-images.githubusercontent.com/36841234/75773229-70586c80-5d88-11ea-98a7-bbe5b989a918.png)

**Comment by GrantXiao** [comment]
![image](https://user-images.githubusercontent.com/36841234/75773303-9716a300-5d88-11ea-99bc-7b67487b3e62.png)

**Comment by shenghanqin** [comment]
@GrantXiao 我这边也有大量图片。我是用了图片压缩工具，图片从50k变为10k啦，你可以试试看。

**Comment by Super-Bin** [comment]
请问一下这个问题是怎么解决的，在分包目录下的图片被打包进主包，如何解决？ @Chen-jj @GrantXiao

**Comment by GrantXiao** [comment]
@Super-Bin 这个我暂时木有更好的办法 因为图片本身就是压缩过 不能压缩太狠了 容易失真 现在暂时降Taro版本回去了  已经考虑把本地图片放到服务器上去了

**Comment by GrantXiao** [comment]
@shenghanqin 请问一下你是用的什么图片压缩工具，能把50K压缩到10K 图片不会失真吗

**Comment by shenghanqin** [comment]
@GrantXiao 很多呀。
比如，网页版 https://tinypng.com/  ，当然也有很多软件也可以做到

**Comment by yuuk** [comment]
能在打包的过程中自动压缩么
