### ISSUE TITLE
Taro Next Vue 模板中引用 template 没有被编绎

### ISSUE THREAD

**Issue by febobo** [NervJS/taro#5606]
### 问题描述

Taro Next Vue 模板中引用 template 没有被编绎

### 复现步骤

必现代码
```
<template>
  <view class="detail">
    <template is='wxParse' data="test"/> 
  </view>
</template>
```

效果如下图
![WechatIMG8873](https://user-images.githubusercontent.com/9276376/75774345-c0d0c980-5d8a-11ea-91f6-10eb270ea7d3.png)

### 期望行为

正常使用template

### 报错信息

无

### 系统信息

👽 Taro v3.0.0-alpha.5

  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.5 => 3.0.0-alpha.5
      @tarojs/taro: 3.0.0-alpha.5 => 3.0.0-alpha.5
      eslint-config-taro: 3.0.0-alpha.5 => 3.0.0-alpha.5

**Comment by yuche** [comment]
你可以把这个 template 写成一个自定义组件然后通过 usingComponents 来使用。

使用 wxparse 有现成的代码，具体可以参考：
https://github.com/NervJS/taro-sample-weapp/tree/next/src

如果是 vue 的话：
https://github.com/NervJS/taro-sample-weapp/tree/vue/src
