### ISSUE TITLE
百度小程序组件ref在真机上是undefined，在百度开发者工具上与微信小程序结果不一样

### ISSUE THREAD

**Issue by lifeng1893** [NervJS/taro#5609]
### 问题描述

这个问题之前在这个issue上已经讨论过[#2631 ](https://github.com/NervJS/taro/issues/2631)，但是真机上还是有问题，this.modal打印出来是undefined，并且在百度开发者工具上看，子组件存在，但是组件的方法还是undefined，要用this.modal.$component.show()这个写法，而不是直接用this.modal.show()

```js

// JSX
<Modal ref={this.refModal} />
// 调用
refModal = node => this.modal = node

onModalClick() {
  console.log(this.modal)
}
```

### 期望行为

与微信小程序一样的结果

### 系统信息
手机信息
iPhone 11, ios 13.3.1
手机百度版本
11.19.0.18
Taro版本：
 Taro v2.0.5

  Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.5 => 2.0.5
      @tarojs/components-qa: 2.0.5 => 2.0.5
      @tarojs/mini-runner: 2.0.5 => 2.0.5
      @tarojs/redux: 2.0.5 => 2.0.5
      @tarojs/redux-h5: 2.0.5 => 2.0.5
      @tarojs/router: 2.0.5 => 2.0.5
      @tarojs/taro: 2.0.5 => 2.0.5
      @tarojs/taro-alipay: 2.0.5 => 2.0.5
      @tarojs/taro-h5: 2.0.5 => 2.0.5
      @tarojs/taro-qq: 2.0.5 => 2.0.5
      @tarojs/taro-quickapp: 2.0.5 => 2.0.5
      @tarojs/taro-rn: 2.0.5 => 2.0.5
      @tarojs/taro-swan: 2.0.5 => 2.0.5
      @tarojs/taro-tt: 2.0.5 => 2.0.5
      @tarojs/taro-weapp: 2.0.5 => 2.0.5
      @tarojs/webpack-runner: 2.0.5 => 2.0.5
      eslint-config-taro: 2.0.5 => 2.0.5
      eslint-plugin-taro: 2.0.5 => 2.0.5
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.5 => 2.0.5
      stylelint-taro-rn: 2.0.5 => 2.0.5
    npmGlobalPackages:
      typescript: 3.3.3

### 补充信息

微信小程序和支付宝小程序在开发者工具和真机上保持一致

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。
