### ISSUE TITLE
Taro可否增加一个自己的Custom终端？

### ISSUE THREAD

**Issue by welllin** [NervJS/taro#5616]
这里想要询问下，可否在Taro里面加一个属于自己的Custom终端，如果可以的话，可否提供响应的资源？

另一句话说就是，可否在微信，阿里，百度等等之外，加入一个自定义的终端，与此同时享受多终端的服务？比如不同终端文件命名的使用（https://taro-docs.jd.com/taro/docs/envs.html）

**Comment by Chen-jj** [comment]
正在探索添加自定义小程序平台、甚至自定义 web 开发框架的实现。
