### ISSUE TITLE
希望useShareAppMessage等不支持的hooks返回空函数，至少不要报错就行了

### ISSUE THREAD

**Issue by huanz** [NervJS/taro#5617]
### 问题描述

使用了 useShareAppMessage 编译 H5 直接就报错了

### 复现步骤

```js
useShareAppMessage(() => {
   
})
```

### 期望行为

页面能够正常运行

### 报错信息

运行页面，报错如下：

TypeError: _tarojs_taro_h5__WEBPACK_IMPORTED_MODULE_1__.default.useShareAppMessage is not a function
    at WrappedComponent.render (index.js?a096:28)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by huanz** [comment]
暂时的解决方法只能自己挂一个上去了：

```js
if (!Taro.useShareAppMessage) {
  Taro.useShareAppMessage = () => {}
}
```

**Comment by 17** [comment]
重现，报错页面会直接空白。严重问题。
