### ISSUE TITLE
[Taro 3.0.0-alpha.5]轮播图swiper异常：第二个swiperItem开始不显示

### ISSUE THREAD

**Issue by quanduoling** [NervJS/taro#5621]
### 问题描述
使用轮播图组件swiper，
`import { View, Text,Image, Swiper, SwiperItem } from '@tarojs/components'`
当图片是assets时只显示第一个item

### 复现步骤

```js
`return (
    <View className='index'>
      <Swiper
        className='test-h'
        indicatorColor='#999'
        indicatorActiveColor='#333'
        circular
        indicatorDots
        autoplay>
 <SwiperItem>
        <View >
          <Image
            style='background: #fff;      border-radius: 2PX;                    '
            src={assetImg}
          />
        </View>
      </SwiperItem>
 <SwiperItem>
        <View >
          <Image
            style='background: #fff;      border-radius: 2PX;                    '
            src={assetImg}
          />
        </View>
      </SwiperItem>
     <SwiperItem>
        <View >
          <Image
            style='background: #fff;      border-radius: 2PX;                    '
            src={assetImg}
          />
        </View>
      </SwiperItem>

      </Swiper>
      
    </View>
  )`
```
1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

swiperItem 正常显示

### 报错信息

<img width="315" alt="screenshot" src="https://user-images.githubusercontent.com/14134514/75964739-b9343080-5f02-11ea-968b-8e5cc9cc6cdf.png">
<img width="321" alt="screenshot" src="https://user-images.githubusercontent.com/14134514/75964757-bcc7b780-5f02-11ea-8d86-c9efd6a5a511.png">

### 系统信息

Taro v3.0.0-alpha.5

  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /opt/local/bin/zsh
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.5 => 3.0.0-alpha.5
      @tarojs/taro: 3.0.0-alpha.5 => 3.0.0-alpha.5
      eslint-config-taro: 3.0.0-alpha.5 => 3.0.0-alpha.5
      react: ^16.10.0 => 16.13.0
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by quanduoling** [comment]
```js
import { ApolloProvider, useQuery } from '@apollo/react-hooks';
```
是代码中使用的Apolloprovider的原因，注释掉apolloprovider后正常使用swiper

**Comment by WangShuXian6** [comment]
> ```js
> import { ApolloProvider, useQuery } from '@apollo/react-hooks';
> ```
> 
> 是代码中使用的Apolloprovider的原因，注释掉apolloprovider后正常使用swiper

>我也使用了 apollo ,但是用的另一个库,没有包裹app,也出现了这个问题。

>如果你不使用 ApolloProvider ,难道项目不再使用 apollo 了吗?
