### ISSUE TITLE
Taro 1.3.22 添加 @babel/plugin-proposal-nullish-coalescing-operator 后编译失败

### ISSUE THREAD

**Issue by zhao5363** [NervJS/taro#5622]
### 问题描述

babel配置添加了 `@babel/plugin-proposal-nullish-coalescing-operator` 后编译报错
 
### 复现步骤

1. 安装 `@babel/plugin-proposal-nullish-coalescing-operator` 
2. 打开 `config/index.js` 文件
3. 将 `"@babel/plugin-proposal-nullish-coalescing-operator"` 添加到  `babel plugins`  配置中
4. `taro build --type weapp`

### 期望行为

能正常编译并识别语法

### 报错信息

编译失败

### 系统信息

  Taro CLI 1.3.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - D:\nodejs\node.EXE
      Yarn: 1.21.1 - D:\yarn\bin\yarn.CMD
      npm: 6.13.4 - D:\nodejs\npm.CMD

### 补充信息

-  底层使用了babel6(`babel-core`) 而没有使用babel7(`@babel/core`)，升级到taro 2.0后也是一样。
- 同样问题的还有 `@babel/plugin-proposal-nullish-coalescing-operator` 、 `@babel/plugin-proposal-export-namespace-from` …… 这些babel7的插件

**Comment by luckyadam** [comment]
1.3.x 的 taro 用的是 babel6，用不了 babel7 的插件，你可以尝试 taro 3.0
