### ISSUE TITLE
编译配置里面 mini.enableExtract属性为啥没呢

### ISSUE THREAD

**Issue by maoliang2271** [NervJS/taro#5626]
# 问题描述

在升级到 2.x 后可能会遇到某些组件的样式失效了， 也可以通过自己配置 Webpack 禁止抽离公共样式，请问要怎么禁用呢，编译配置里面 mini.enableExtract属性是没的，h5.enableExtract是有的。

### 期望行为

配置 Webpack 禁止抽离公共样式

### 系统信息

Taro CLI 1.3.4 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.5 => 2.0.5
      @tarojs/components: 2.0.5 => 2.0.5
      @tarojs/plugin-babel: 2.0.5 => 2.0.5
      @tarojs/plugin-csso: 2.0.5 => 2.0.5
      @tarojs/plugin-sass: 2.0.5 => 2.0.5
      @tarojs/plugin-uglifyjs: 2.0.5 => 2.0.5
      @tarojs/redux: 2.0.5 => 2.0.5
      @tarojs/redux-h5: 2.0.5 => 2.0.5
      @tarojs/router: 2.0.5 => 2.0.5
      @tarojs/taro: 2.0.5 => 2.0.5
      @tarojs/taro-alipay: 2.0.5 => 2.0.5
      @tarojs/taro-h5: 2.0.5 => 2.0.5
      @tarojs/taro-swan: 2.0.5 => 2.0.5
      @tarojs/taro-tt: 2.0.5 => 2.0.5
      @tarojs/taro-weapp: 2.0.5 => 2.0.5
      @tarojs/webpack-runner: 2.0.5 => 2.0.5
      eslint-config-taro: 2.0.5 => 2.0.5
      eslint-plugin-taro: 2.0.5 => 2.0.5
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      react: ^16.8.6 => 16.12.0

**Comment by luckyadam** [comment]
小程序的样式一定是要抽离成单独文件

**Comment by memotail** [comment]
升级文档说明，可以Webpack 禁止抽离公共样式来解决某些组件的样式失效了，那怎么操作呢？升级文档写的不清晰。issues也没说法。。
