### ISSUE TITLE
支持头条小程序 createCanvasContext

### ISSUE THREAD

**Issue by lawler61** [NervJS/taro#5633]
### 问题描述

头条编译下，使用 Canvas 标签，调用 Taro.createCanvasContext，并不能获取到 canvas 的上下文，麻烦支持下，[头条小程序官网 canvas api](https://developer.toutiao.com/dev/cn/mini-app/develop/api/interface/canvas-draw/tt.createcanvascontext)

### 复现步骤

Index page 中

```js
export default class Index extends Component {
  componentDidShow() {
    const canvasContext = Taro.createCanvasContext('test-canvas')
    console.log(canvasContext)
  }

  render() {
    return (
      <View>
        <Canvas id="test-canvas" canvasId="test-canvas" className="test-canvas" />
      </View>
    )
  }
}

```

### 期望行为

获取 canvas 的上下文

### 报错信息

目前 console 打出来只有如下信息
![image](https://user-images.githubusercontent.com/38933451/76074863-fbc73d00-5fd6-11ea-8b2e-53331267f26b.png)

### 系统信息

![image](https://user-images.githubusercontent.com/38933451/76074923-0eda0d00-5fd7-11ea-834a-2ae5084451da.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
你获取到的就是 CanvasContext 对象，方法在原型上。
