### ISSUE TITLE
2.0.4  export * 语法 编译成小程序报错

### ISSUE THREAD

**Issue by liaoyinglong** [NervJS/taro#5636]
### 复现步骤
复现仓库: https://github.com/liaoyinglong/taro-export-issuse

关键代码：https://github.com/liaoyinglong/taro-export-issuse/blob/master/src/components/index.ts

1. ![image](https://user-images.githubusercontent.com/23382699/76134548-037bf580-605a-11ea-8653-17c2f7636336.png)
2. ![image](https://user-images.githubusercontent.com/23382699/76134551-0840a980-605a-11ea-9772-f62d69b6bcf6.png)

### 期望行为

编译通过

### 系统信息

![image](https://user-images.githubusercontent.com/23382699/76134571-48079100-605a-11ea-97ec-01f04ef90fae.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
你可以看看别的issue的回复。Taro不支持这种写法
