### ISSUE TITLE
trtc-room.js from UglifyJs：Unexpected token: keyword «const»

### ISSUE THREAD

**Issue by wenxiayili** [NervJS/taro#5638]
### 问题描述
  如标题所示，在执行命令yarn build:weapp，出现上面的错误。我在看其他issues时，别人说安装query-string@5, 我安装了 ，但是没有作用 ，是不是需要配置什么？

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by wenxiayili** [comment]
@Chen-jj 麻烦了哈 我这边没找到其他的方法。

**Comment by hnsylitao** [comment]
@wenxiayili 你已经解决了吗，我这边也碰到了问题，trtc-room 没办法引入进来
taro2.0.5

**Comment by vee2046** [comment]
@wenxiayili @hnsylitao 
解决了吗
我是用腾讯云的cos-wx-sdk-v5。。。咋回事呢

**Comment by vee2046** [comment]
暴力地解决一下吧，把第三方库里的const改成var
先这么解决了，泪...
