### ISSUE TITLE
快应用无法编译，提示missing script: dev:quickapp

### ISSUE THREAD

**Issue by tiandezhen** [NervJS/taro#5641]
### 问题描述
原来建项目的时候taro还不支持快应用，先执行了taro update self 和 taro update project，然后执行
npm run dev:quickapp无法编译
### 复现步骤
npm run dev:quickapp
快应用无法编译，提示missing script: dev:quickapp

### 报错信息
npm ERR! missing script: dev:quickapp
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     dev:weapp
npm ERR!     dev:alipay

### 系统信息

Taro v2.0.5

  Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      npm: 6.14.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.5 => 2.0.5 
      @tarojs/mini-runner: 2.0.5 => 2.0.5 
      @tarojs/plugin-babel: 2.0.5 => 2.0.5 
      @tarojs/plugin-csso: 2.0.5 => 2.0.5 
      @tarojs/plugin-less: 2.0.5 => 2.0.5 
      @tarojs/plugin-sass: 2.0.5 => 2.0.5 
      @tarojs/plugin-stylus: 2.0.5 => 2.0.5 
      @tarojs/plugin-uglifyjs: 2.0.5 => 2.0.5 
      @tarojs/router: 2.0.5 => 2.0.5 
      @tarojs/taro: 2.0.5 => 2.0.5 
      @tarojs/taro-alipay: 2.0.5 => 2.0.5 
      @tarojs/taro-h5: 2.0.5 => 2.0.5 
      @tarojs/taro-swan: 2.0.5 => 2.0.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      @tarojs/webpack-runner: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      eslint-plugin-taro: 2.0.5 => 2.0.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
    npmGlobalPackages:
      typescript: 3.7.3

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro/blob/2.x/packages/taro-cli/templates/default/pkg

比着这个文件抄一下 `scripts` `dependencies` `devDependencies` 三个字段，`<%= version %>` 替换成具体版本，比如 2.0.5。

或者你也可以用 CLI 新建一个默认项目然后复制一下这几个字段。

**Comment by Garfield550** [comment]
比较核心的包是 `@tarojs/taro-quickapp`

**Comment by tiandezhen** [comment]
可以编译了，谢谢
便还是错误，出现

[快应用容器版本获取失败！ #5624](https://github.com/NervJS/taro/issues/5624)
相同的问题
