### ISSUE TITLE
2.x版本Canvas无法绘制本地的图片

### ISSUE THREAD

**Issue by CarlXu94** [NervJS/taro#5642]
目前2.x版本Canvas绘制本地图片的时候，如果本地图片被转为base64，在真机上面图片是无法绘制的，但是不转base64又会导致主包太大，所以希望官方能将图片分包的问题解决

**Comment by shenghanqin** [comment]
你的配置还有图片调用的地方贴一下代码？

我的代码中改了这个。

```
imageUrlLoaderOption: {
      limit: 0
    },
```

**Comment by CarlXu94** [comment]
@shenghanqin 因为项目比较大，分包较多，如果设置为false的话，图片则都在主包，若不是设置false，则部分图片需要用canvas绘制，导致无法绘制

**Comment by CarlXu94** [comment]
已在2.0.6fix
