### ISSUE TITLE
taro next vue 拉取代码之后，启动项目报错

### ISSUE THREAD

**Issue by mengfanfei** [NervJS/taro#5643]
### 问题描述

根据官网使用taro-next cli拉取代码，然后 npm run dev:h5 启动项目，报错 见下图

### 复现步骤

1. npm install -g @tarojs/cli@next
2. taro init myApp
3. cd myApp   npm run dev:h5
4. 
![image](https://user-images.githubusercontent.com/27276920/76181990-19c2b680-61fe-11ea-9f98-437914308478.png)

### 期望行为

项目启动

### 报错信息

见上图

### 系统信息

![image](https://user-images.githubusercontent.com/27276920/76182054-54c4ea00-61fe-11ea-94b0-c41654d883a4.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
看置顶帖啊，现在 next 还不支持 h5
