### ISSUE TITLE
taro@2.0.6 addChunkPages问题

### ISSUE THREAD

**Issue by Super-Bin** [NervJS/taro#5645]
### 问题描述
由于echart图表库太大，把该库放在子包中，并配置了webpack从common.js中分离，分离出的js文件放在子包中，并且只有子包中的页面使用了echart组件。但在真机中报错，找不到组件

```js
Component is not found in path "subPackage/components/ec-canvas/ec-canvas" (using by "subPackage/pages/index/index");
```

在taro2.0.5中:
- [x] 在微信开发工具中，在分包中能100%正常使用组件
- [x] 在真机上100%存在该问题

在taro2.0.6中:
- [x] 在微信开发工具中，偶尔也会出现找不到控件的情况
- [x] 在真机上100%存在该问题

### 复现步骤
下面提供了demo，首页 点击 "跳转子包"

### 期望行为
子包中的页面，能正常使用echart图表库

### 报错信息
![WX20200309-154857](https://user-images.githubusercontent.com/26457469/76193174-66b68500-621e-11ea-900a-5ad7d09f2412.png)

### 系统信息
 Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/components-qa: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/redux: 2.0.6 => 2.0.6 
      @tarojs/redux-h5: 2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/taro-qq: 2.0.6 => 2.0.6 
      @tarojs/taro-quickapp: 2.0.6 => 2.0.6 
      @tarojs/taro-swan: 2.0.6 => 2.0.6 
      @tarojs/taro-tt: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 

### 补充信息
demo：
[testApp.zip](https://github.com/NervJS/taro/files/4305292/testApp.zip)

**Comment by luckyadam** [comment]
非常尴尬 fcaefce120d6bf8777eb23c9f7f4ae61af762eb2 这个 commit 只处理了 Taro 组件的情况，没有考虑到原生组件
![image](https://user-images.githubusercontent.com/1782542/76200725-1561c200-622d-11ea-950f-da53305afef7.png)

你可以改一下编译后的代码，在子组件里引用一下抽出来的公共文件，后续待 Taro 解决

**Comment by cyq333** [comment]
> 非常尴尬 [fcaefce](https://github.com/NervJS/taro/commit/fcaefce120d6bf8777eb23c9f7f4ae61af762eb2) 这个 commit 只处理了 Taro 组件的情况，没有考虑到原生组件
> ![image](https://user-images.githubusercontent.com/1782542/76200725-1561c200-622d-11ea-950f-da53305afef7.png)
> 
> 你可以改一下编译后的代码，在子组件里引用一下抽出来的公共文件，后续待 Taro 解决

原生组件这个问题现在解决了吗？

**Comment by Super-Bin** [comment]
@cyq333 他给的方案可行，就没再去跟进这个问题，等到后面有时间了再看

**Comment by wuclown** [comment]
每次启动，都要手动添加引入，现在有什么别的解决办法吗。

**Comment by Super-Bin** [comment]
@wuclown 不清楚呢，要不再问一下他们的人有没有解决

**Comment by Alvin1992** [comment]
> @wuclown 不清楚呢，要不再问一下他们的人有没有解决

请问你现在采取的还是这样的方式吗？这样的话在开发的时候的就很麻烦

**Comment by cheneywan** [comment]
同问，这个问题现在有进展么？

**Comment by crazyll** [comment]
同问，原生页面没办法引入分包的问题怎么解决。

**Comment by Super-Bin** [comment]
> > @wuclown 不清楚呢，要不再问一下他们的人有没有解决
> 
> 请问你现在采取的还是这样的方式吗？这样的话在开发的时候的就很麻烦

是的，taro2.x的版本还是使用这个方法，不知道taro3.0有没有修复

**Comment by Super-Bin** [comment]
@Alvin1992 @cheneywan 是的，taro2.x的版本还是使用这个方法，不知道taro3.0有没有修复

**Comment by qinxiangling** [comment]
请问这个问题解决了吗，目前也越到了这个问题，能否请教一下解决方案

**Comment by Super-Bin** [comment]
> 请问这个问题解决了吗，目前也越到了这个问题，能否请教一下解决方案

上面已经给出了临时方案，可以改一下编译后的代码，在子组件里引用一下抽出来的公共文件，后续待 Taro 解决。

**Comment by Super-Bin** [comment]
@qinxiangling 上面给出了临时方案，你可以改一下编译后的代码，在子组件里引用一下抽出来的公共文件，后续待 Taro 解决

**Comment by qinxiangling** [comment]
> @qinxiangling 上面给出了临时方案，你可以改一下编译后的代码，在子组件里引用一下抽出来的公共文件，后续待 Taro 解决

我配置后的引入模块是正确的模块名是对的，但是并没有从common.js抽离出来
![image](https://user-images.githubusercontent.com/32665638/96397139-6c843800-11fb-11eb-932f-e5769a69387d.png)
![image](https://user-images.githubusercontent.com/32665638/96397226-a05f5d80-11fb-11eb-9293-5aebbbb55827.png)

**Comment by Super-Bin** [comment]
@qinxiangling  要不看一下我提交给他们的demo，看里面的配置是不是跟我一样，已经不太记得怎么配置的了，已经很久没弄这个taro的东西了，实在不行就在群里咨询一下

**Comment by qinxiangling** [comment]
> @qinxiangling 要不看一下我提交给他们的demo，看里面的配置是不是跟我一样，已经不太记得怎么配置的了，已经很久没弄这个taro的东西了，实在不行就在群里咨询一下

好的，就是附件里的testApp.zip吗，十分感谢

**Comment by findxc** [comment]
@qinxiangling 请问没有从common.js抽离出来的问题你是怎么解决的呢？我也遇到了 ...

**Comment by findxc** [comment]
呃，我找到原因了，因为我的 `webpackChain` 是写在 `config/index.js` 的，然后我项目中 `config/prod.js` 中也有这个配置，就被覆盖了，所以就没有抽取出来 ...

**Comment by findxc** [comment]
可以使用 webpack 插件 banner 来在文件开头加上 `require('../../echartsChunk'),` 。

在 webpackChain 函数里面补充如下代码即可：

```js
chain.plugin('banner').use(new webpack.BannerPlugin({
  banner: "require('../../echartsChunk'),",
  raw: true,
  include: /chart[\\/]Echarts[\\/]ec-canvas[\\/]ec-canvas.js/,   // 这里写你自己项目对应的文件
}), [])
```
