### ISSUE TITLE
'@tarojs/redux-h5' does not contain an export named 'getStore'

### ISSUE THREAD

**Issue by li-shuaishuai** [NervJS/taro#5648]
### 问题描述

'@tarojs/redux-h5' does not contain an export named 'getStore'

### 复现步骤

import { getStore } from '@tarojs/redux'

npm run dev:h5

### 期望行为

获取 store 需要用到dispatch

### 系统信息

taro 2.0.6

**Comment by li-shuaishuai** [comment]
@Littly

**Comment by li-shuaishuai** [comment]
@ luckyadam

**Comment by Chen-jj** [comment]
Taro3可以直接使用 `react-redux`
