### ISSUE TITLE
3.x 版本 Taro.navigateTo 反复跳转同一个page路由 报错：Encountered two children with the same key

### ISSUE THREAD

**Issue by wuchangming** [NervJS/taro#5652]
### 问题描述
多次执行 Taro.navigateTo 到同一个page的路由后会报错
如：
Taro.navigateTo({ url: '/pages/index/index' })
![image](https://user-images.githubusercontent.com/5039340/76284025-1818f180-62d7-11ea-9782-070a670c4b70.png)

事实上还会引起一些 page 生命周期执行多次，原因分析见「补充信息」

### 复现步骤

多次执行 Taro.navigateTo 到同一个page的路由

### 期望行为
Taro.navigateTo 反复跳转同一个page路由不报错

### 报错信息
VM3443:1 Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s pages/index/index 
    in App (created by AppWrapper)
    in AppWrapper

### 系统信息

👽 Taro v3.0.0-alpha.5

  Taro CLI 3.0.0-alpha.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.0-alpha.5 => 3.0.0-alpha.5
      @tarojs/components: 3.0.0-alpha.5 => 3.0.0-alpha.5
      @tarojs/taro: 3.0.0-alpha.5 => 3.0.0-alpha.5
      eslint-config-taro: 3.0.0-alpha.5 => 3.0.0-alpha.5
      react: ^16.10.0 => 16.13.0
### 补充信息

应该是这里的 id 直接用了路由路径引起的
大概代码位置：
https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/dsl/react.ts#L124

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
麻烦介绍一下你路由跳转的详情：

是 A -> B -> A -> A
这样在第四步出错吗

**Comment by wuchangming** [comment]
A --> A 就会报错

**Comment by yuche** [comment]
A -> A 的目的是什么？我的理解是啥都不干，但看起来小程序会开一个新的页面

**Comment by wuchangming** [comment]
目的是公用同样的page，但加载不一样的内容。比如下面这样

A?productCode=1    -->    A?productCode=2

**Comment by yuche** [comment]
那可以支持，但我必须提醒你这样会导致性能变差。因为页面栈和整个应用都会渲染更多的内容，更好的方法写一个 context 或用第三方的状态管理工具控制同一个页面的渲染状态。

**Comment by wuchangming** [comment]
是的，目前是支持的，但由于[这里](https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/dsl/react.ts#L124
)的 id 用的是路由路径。A -> A  后事实上会出现相同的id。后续的一些hide，show什么的生命周期都会有点问题。
比如：
A -> A  -> 回退，hide会被调用两次。

**Comment by yuche** [comment]
我说可以支持是以后可以这样写的意思

**Comment by wuchangming** [comment]
@yuche ，OK，GET，感谢解答。
期待更新

**Comment by SamChangi** [comment]
> @yuche ，OK，GET，感谢解答。
> 期待更新

BTW，A -> A，你有遇到过navigateBack之后，之前A页面数据被覆盖了的情况吗？

**Comment by wuchangming** [comment]
> > @yuche ，OK，GET，感谢解答。
> > 期待更新
> 
> BTW，A -> A，你有遇到过navigateBack之后，之前A页面数据被覆盖了的情况吗？

不太懂，有复现demo不。

**Comment by SamChangi** [comment]
> > > @yuche ，OK，GET，感谢解答。
> > > 期待更新
> > 
> > 
> > BTW，A -> A，你有遇到过navigateBack之后，之前A页面数据被覆盖了的情况吗？
> 
> 不太懂，有复现demo不。

类似这样的issue，你看下。
https://github.com/Tencent/wepy/issues/322

**Comment by wuchangming** [comment]
> > > > @yuche ，OK，GET，感谢解答。
> > > > 期待更新
> > > 
> > > 
> > > BTW，A -> A，你有遇到过navigateBack之后，之前A页面数据被覆盖了的情况吗？
> > 
> > 
> > 不太懂，有复现demo不。
> 
> 类似这样的issue，你看下。
> [Tencent/wepy#322](https://github.com/Tencent/wepy/issues/322)

按照目前taro3的设计，A -> A如果参数也完全一样，确实会覆盖。目前解决方案是 跳转的时候带上不一样的参数。如： A?code=a -> A?code=b

**Comment by SamChangi** [comment]
> > > > > @yuche ，OK，GET，感谢解答。
> > > > > 期待更新
> > > > 
> > > > 
> > > > BTW，A -> A，你有遇到过navigateBack之后，之前A页面数据被覆盖了的情况吗？
> > > 
> > > 
> > > 不太懂，有复现demo不。
> > 
> > 
> > 类似这样的issue，你看下。
> > [Tencent/wepy#322](https://github.com/Tencent/wepy/issues/322)
> 
> 按照目前taro3的设计，A -> A如果参数也完全一样，确实会覆盖。目前解决方案是 跳转的时候带上不一样的参数。如： A?code=a -> A?code=b

Okay, thx a lot

**Comment by yqwoe** [comment]
TabBar A 页面 -> B  -> A ->B 会有个错误

```
thirdScriptError
Cannot convert undefined or null to object; [Component] Event Handler Error @ pages/chat/list/index#(anonymous)
TypeError: Cannot convert undefined or null to object
    at n.assign (<anonymous>)
    at _class.Connect (http://127.0.0.1:52001/appservice/vendors.js:2254:52)
    at new _class (http://127.0.0.1:52001/appservice/common.js:1174:105)
    at Object.taro$$1.<computed> [as navigateTo] (http://127.0.0.1:52001/appservice/taro.js:3529:35)
    at ChatList.handleOpenChat (http://127.0.0.1:52001/appservice/pages/chat/list/index.js:184:31)
    at Se.obj.<computed> [as handleOpenChat] (http://127.0.0.1:52001/appservice/taro.js:2519:42)
    at Object.r.safeCallback (http://127.0.0.1:52001/appservice/__dev__/WAService.js:2:1532114)
    at http://127.0.0.1:52001/appservice/__dev__/WAService.js:2:1651447
    at c (http://127.0.0.1:52001/appservice/__dev__/WAService.js:2:1659463)
    at http://127.0.0.1:52001/appservice/__dev__/WAService.js:2:1651372
```

**Comment by wuchangming** [comment]
@yqwoe 有没demo？

**Comment by NaiveCAI** [comment]
@yqwoe 我也遇到了这个问题，报错一模一样，但是没有你这个“TabBar A 页面 -> B -> A ->B”那么复杂，我直接从TabBar A -> B就出现了这个错。

我这个page有一个自己写的@withLogin的decorator，和redux的@connect

搞笑的是，我把@withLogin放在@connect后面调用，报错就没了😂。
