### ISSUE TITLE
Textarea设置value字数较多时不能正常显示，并且不能显示“完成”按钮

### ISSUE THREAD

**Issue by YulncBd** [NervJS/taro#5659]
### 问题描述

在头条小程序上使用Textarea组件，在进入页面时从服务端请求数据给Textarea赋值
1.此时如果赋值数据较多(大于1000)时，设置的autoHeight不起作用导致无法显示数据，页面空白
2.如果Textarea设置了value，则showConfirmBar不起作用，无法显示"完成"按钮；如果不设置value则能显示
### 复现步骤

```js
          <Textarea
            className='writerPage-contentview-textarea'
            style={{height: height}}
            value={value}
            maxlength={-1}
            placeholder='请输入正文'
            showConfirmBar
            cursorSpacing={50}
            count={false}
            disabled={this.canEdit == '0'}
            onInput={this.onContentChange.bind(this)}
            onLineChange={this.onLineChange.bind(this)}
          />

```

### 期望行为

在初始值value字数较多时能正常显示数据，并且能正常显示“完成”按钮

### 报错信息

无报错
### 系统信息

  Taro CLI 1.3.37 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.37 => 1.3.37
      @tarojs/components: 1.3.37 => 1.3.37
      @tarojs/components-qa: 1.3.37 => 1.3.37
      @tarojs/plugin-babel: 1.3.37 => 1.3.37
      @tarojs/plugin-csso: 1.3.37 => 1.3.37
      @tarojs/plugin-sass: 1.3.37 => 1.3.37
      @tarojs/plugin-uglifyjs: 1.3.37 => 1.3.37
      @tarojs/redux: 1.3.37 => 1.3.37
      @tarojs/redux-h5: 1.3.37 => 1.3.37
      @tarojs/router: 1.3.37 => 1.3.37
      @tarojs/taro: 1.3.37 => 1.3.37
      @tarojs/taro-alipay: 1.3.37 => 1.3.37
      @tarojs/taro-h5: 1.3.37 => 1.3.37
      @tarojs/taro-qq: 1.3.37 => 1.3.37
      @tarojs/taro-quickapp: 1.3.37 => 1.3.37
      @tarojs/taro-rn: 1.3.37 => 1.3.37
      @tarojs/taro-swan: 1.3.37 => 1.3.37
      @tarojs/taro-tt: 1.3.37 => 1.3.37
      @tarojs/taro-weapp: 1.3.37 => 1.3.37
      @tarojs/webpack-runner: 1.3.37 => 1.3.37
      eslint-config-taro: 1.3.37 => 1.3.37
      eslint-plugin-taro: 1.3.37 => 1.3.37
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 1.3.37 => 1.3.37
      stylelint-taro-rn: 1.3.37 => 1.3.37
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@YulncBd 试试字节原生的 Textarea 有没一样的问题吧，Taro 只是处理了元素属性和事件，具体样式应该是原生的问题。

**Comment by YulncBd** [comment]
用Taro如何使用字节原生的Textarea？
