### ISSUE TITLE
Video组件编译出的H5，在手百上运行时会被手百的video劫持替换

### ISSUE THREAD

**Issue by taotao2012** [NervJS/taro#5660]
**问题描述**
使用Video组件后，编译出的H5，当在手百上运行时，video组件会被手百自动劫持替换，致使无法通过videoRef.current来控制video的播放和暂停动作。在浏览器上是没有问题的，但在手百上就不起作用。通过onTimeUpdate回调函数也拿不到当前播放时间。

**复现步骤**
1. 在项目中使用Video组件；且在onTimeUpdate回调函数中获取当前播放时间，并toast出来，且当播放时间大于15秒时，将视频自动暂停。
2.将以上code编译成H5；
3.在手百上运行编译好的H5。

相关的部分代码如下：
```js
const videoRef = useRef<Taro.VideoContext>();
videoRef.current = videoRef.current || Taro.createVideoContext('taro-video', this);

const onProgressHandler = e => {
        Taro.showToast({title: e.detail.currentTime});
        if (e.detail.currentTime > 15) {
            videoRef.current.pause();
        }
    };

return (
<Video
    id='taro-video'
    src={videoUrl}
    controls={disableControls}
    autoplay={false}
    onWaiting={onWaitingHandler}
    onTimeUpdate={onProgressHandler}
    onError={onErrorHandler}
    onPlay={onPlayHandler}
    onEnded={onEndedHandler}
    onFullscreenChange={onFullscreenChangeHandler}
    loop={false}
    muted={muted}
 />);

```

**期望行为**
1.  在onTimeUpdate回调函数中能toast出当前播放时长；
2. 当播放时长大于15秒时，能实现将当前视频暂停；
**报错信息**
1. 在手百上无法toast出当前播放时间；
2. 播放时长大于15秒时，通过调用

**系统信息**

Taro版本[v2.0.2]
Taro UI版本[v 2.2.2]
报错平台[h5]

**补充信息**
这个问题已经影响到了我们排期，且我们公司好多团队都在用Taro，烦请尽快解决~谢谢！

**Comment by shenghanqin** [comment]
你把这个h5页面在安卓手机的微信app中的内置浏览器打开，你会发现video也被微信给劫持了。你可以试试看兼容性。
