### ISSUE TITLE
npm run dev:weapp 无法编译

### ISSUE THREAD

**Issue by zhang14725804** [NervJS/taro#5661]
运行npm run dev:weapp 之后没有编译，如图

![image](https://user-images.githubusercontent.com/15354910/76314725-4ff15a80-6312-11ea-9be3-1d4e6ba16cb8.png)

![image](https://user-images.githubusercontent.com/15354910/76314798-6d262900-6312-11ea-8b7d-8eba1700eb3a.png)

package.json如下

"dependencies": {
		"@tarojs/components": "2.0.6",
		"@tarojs/mini-runner": "2.0.6",
		"@tarojs/router": "2.0.6",
		"@tarojs/taro": "2.0.6",
		"@tarojs/taro-alipay": "2.0.6",
		"@tarojs/taro-h5": "2.0.6",
		"@tarojs/taro-swan": "2.0.6",
		"@tarojs/taro-tt": "2.0.6",
		"@tarojs/taro-weapp": "2.0.6",
		"nerv-devtools": "^1.5.6",
		"nervjs": "^1.5.6",
		"taro-ui": "^2.2.1"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "2.0.6",
		"@tarojs/plugin-csso": "2.0.6",
		"@tarojs/plugin-sass": "2.0.6",
		"@tarojs/plugin-uglifyjs": "2.0.6",
		"@tarojs/webpack-runner": "2.0.6",
		"@types/react": "^16.4.6",
		"@types/webpack-env": "^1.13.6",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"eslint": "^4.19.1",
		"eslint-config-taro": "2.0.6",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "2.0.6",
		"node-sass": "^4.13.0"
	}

试着运行taro update project，删除node-modules，删除dist目录，删除lock文件都不行

taro update self之后 taro -v， taro info直接报错,command not found

npm i -g @tarojs/cli之后taro -v， taro info又可以使用

项目中以来的taro版本和全局安装的taro版本一致，不知道问题出在哪里，也没有报错

@smoothdvd @guotie @Leechael @weakish @cncolder @guotie

**Comment by zhang14725804** [comment]
"dependencies": {
		"@tarojs/components": "2.0.6",
		"@tarojs/mini-runner": "2.0.6",
		"@tarojs/router": "2.0.6",
		"@tarojs/taro": "2.0.6",
		"@tarojs/taro-alipay": "2.0.6",
		"@tarojs/taro-h5": "2.0.6",
		"@tarojs/taro-swan": "2.0.6",
		"@tarojs/taro-tt": "2.0.6",
		"@tarojs/taro-weapp": "2.0.6",
		"nerv-devtools": "^1.5.6",
		"nervjs": "^1.5.6",
		"taro-ui": "^2.2.1"
	},
	"devDependencies": {
		"@tarojs/plugin-babel": "2.0.6",
		"@tarojs/plugin-csso": "2.0.6",
		"@tarojs/plugin-sass": "2.0.6",
		"@tarojs/plugin-uglifyjs": "2.0.6",
		"@tarojs/webpack-runner": "2.0.6",
		"@types/react": "^16.4.6",
		"@types/webpack-env": "^1.13.6",
		"babel-eslint": "^8.2.3",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"eslint": "^4.19.1",
		"eslint-config-taro": "2.0.6",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-taro": "2.0.6",
		"node-sass": "^4.13.0"
	}

**Comment by luckyadam** [comment]
重新安装 cli

**Comment by zhang14725804** [comment]
@luckyadam 都重装了很多次了，电脑也重启很多次。

**Comment by luckyadam** [comment]
> @luckyadam 都重装了很多次了，电脑也重启很多次。

看日志就是没装好

**Comment by zhang14725804** [comment]
执行 cnpm i -g @tarojs/cli

![image](https://user-images.githubusercontent.com/15354910/76378527-8f5a8e00-6388-11ea-8bda-9b78e3a7272e.png)
![image](https://user-images.githubusercontent.com/15354910/76378545-9c777d00-6388-11ea-96ef-0e5af8e42215.png)
![image](https://user-images.githubusercontent.com/15354910/76378564-adc08980-6388-11ea-802c-b0034d7be4b9.png)

也没有明显的报错，但是执行taro -v,taro info ,taro --help,taro doctor都没有反应，不知道是怎么回事
