### ISSUE TITLE
web环境，Picker组件mode='date'时，设置start属性后报错

### ISSUE THREAD

**Issue by bdbd001** [NervJS/taro#5662]
### 问题描述
Taro2.0.4
H5 Picker组件mode='date'时，并设置start属性，点击弹出日期控件，选择年份到2019年，控制台会报错 `Uncaught (in promise) TypeError: Cannot read property 'dom' of undefined`。
若不设置start属性和end属性则不会触发报错。

### 复现步骤

1.Picker组件 mode='date'，并设置start属性，
2.点击弹出日期控件，选择年份到2019年，控制台会报错 `Uncaught (in promise) TypeError: Cannot read property 'dom' of undefined`。
3.之后的每一次touchmove都会触发这个报错

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Picker } from '@tarojs/components'

export default class PagePicker extends Component {
  state = {
    dateSel: '2018-04-22'
  }

  onDateChange = e => {
    this.setState({
      dateSel: e.detail.value
    })
  }

  render () {
    return (
      <View className='container'>
            <Text>日期选择器</Text>
            <View>
              <Picker mode='date'  start='2019-03-01' end='2020-04-26' onChange={this.onDateChange}>
                <View className='picker'>
                  当前选择：{this.state.dateSel}
                </View>
              </Picker>
            </View>
      </View>
    )
  }
}

```

### 期望行为
解决此问题，可正常使用日期picker

### 报错信息

 `Uncaught (in promise) TypeError: Cannot read property 'dom' of undefined`。
![image](https://user-images.githubusercontent.com/21333239/76320349-867fa300-631b-11ea-9737-4a1f17b9963f.png)

### 系统信息
 Taro CLI 2.0.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Users\bsy\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
没有复现 检查下代码吧~

**Comment by bdbd001** [comment]
> 没有复现 检查下代码吧~

你好，我同事在另一台电脑也复现了。
都是chrome浏览器，taro2.0.4版。
全部代码就在上面了，是官方文档提供的示例代码，我只是添加了start和end属性。
