### ISSUE TITLE
input的onInput事件导致作用域取值不对

### ISSUE THREAD

**Issue by fangkyi03** [NervJS/taro#5665]
### 问题描述
map中input的onInput事件导致作用域取值不对 从而导致 不管这么输入 取到的都是最后一次的item

### 复现步骤

```js
/**
 renderFormChildren = (item,i) => {
    let view = null
    if (item.type == 'input') {
      view = this.renderInput(item,i)
    } else {
      view = this.renderInput(item,i)
    }
    return (
      <View className={styles.formChildren}>
        {this.renderFormTitle(item)}
        {view}
      </View>
    )

  renderInput = (item) => {
    const value = this.state[item.key] || ''
    return (
      <View className={styles.input}>
        <AtInput
          value={value}
          key={item.key}
          placeholder={'请输入' + item.name}
          onChange={(value)=>this.onInput(value,item)}
        />
      </View>
    )
  }

  renderFormView = () => {
    return (
      <View>
        {
          this.state.form.map((e,i) => {
            return this.renderFormChildren(e,i)
          })
        }
        {this.renderFormFootButton()}
      </View>
    )
  }

  }
 */


```

### 期望行为

在map中使用input onInput的事件可以正常
### 系统信息

👽 Taro v1.3.18

  Taro CLI 1.3.18 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.18.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.18 => 1.3.18 
      @tarojs/components: 1.3.18 => 1.3.18 
      @tarojs/components-rn: 1.3.18 => 1.3.18 
      @tarojs/plugin-babel: 1.3.18 => 1.3.18 
      @tarojs/plugin-csso: 1.3.18 => 1.3.18 
      @tarojs/plugin-less: 1.3.18 => 1.3.18 
      @tarojs/plugin-sass: 1.3.18 => 1.3.18 
      @tarojs/plugin-uglifyjs: 1.3.18 => 1.3.18 
      @tarojs/redux: 1.3.18 => 1.3.18 
      @tarojs/router: 1.3.18 => 1.3.18 
      @tarojs/taro: 1.3.18 => 1.3.18 
      @tarojs/taro-h5: 1.3.18 => 1.3.18 
      @tarojs/taro-redux-rn: 1.3.18 => 1.3.18 
      @tarojs/taro-rn: 1.3.18 => 1.3.18 
      @tarojs/taro-router-rn: 1.3.18 => 1.3.18 
      @tarojs/taro-weapp: 1.3.18 => 1.3.18 
      @tarojs/webpack-runner: 1.3.18 => 1.3.18 
      eslint-config-taro: 1.3.18 => 1.3.18 
      eslint-plugin-taro: 1.3.18 => 1.3.18 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
    npmGlobalPackages:
      typescript: 3.8.3
### 补充信息

input的onInput事件 每次都是取anonymousFunc0 而这个的值会在map中每次都被修改 导致存的值 只有最后一次的

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
升级到 1.3.38 试试，这个问题应该解决了

**Comment by fangkyi03** [comment]
1.3.38并没有解决这个问题

**Comment by fangkyi03** [comment]
我已经升级试过了
