### ISSUE TITLE
Taro next版本微信小程序小程序分享无效（alpha5报错）

### ISSUE THREAD

**Issue by PARADISELIN** [NervJS/taro#5668]
### 问题描述

1. 使用taro next 3.0.0alpha.1版本分享配置无效

第一次使用的是函数式组件，使用taro提供的`useShareAppMessage`的hooks进行分享设置：

```js
// ...
useShareAppMessage(() => {
  return {
    title: 'hello',
    page: '/pages/index/index'
  }
})
```

无效后改成class组件的onShareAppMessage，也不生效

```js
// ...
onShareAppMessage() {
  return {
    title: 'hello',
    page: '/pages/index/index'
  }
}
```

2. 升级使用taro next 3.0.0alpha.5版本，分享直接报错

```js
// ...
onShareAppMessage() {
  return {
    title: 'hello',
    page: '/pages/index/index'
  }
}
```
在业务代码中并未填写任何id取值相关操作
<img width="812" alt="3" src="https://user-images.githubusercontent.com/17696492/76381562-c339b180-6390-11ea-8138-6d13f7b33f7f.png">

### 复现步骤

1. 打开右上角菜单点击转发
2. 分享给好友
3. 显示的分享卡片无任何配置信息

```js
@connect(mapStateToProps, mapDispatchToProps)
class Index extends Component {
  componentDidMount() {}

  onShareAppMessage() {
    return {
      title: 'hello',
      path: '/pages/index/index'
    }
  }

  render() {
    return (
      <View className="page">
        <ScrollBoard />
      </View>
    )
  }
}

export default Index as ComponentClass<PageOwnProps, PageState>
```

### 期望行为

期望分享配置信息能够生效

### 报错信息

alpha.1版本无报错，就是不生效。
alpha.5版本不生效且报错

<img width="655" alt="1" src="https://user-images.githubusercontent.com/17696492/76381167-ab156280-638f-11ea-9737-2a7f48d4ae17.png">

### 系统信息

<img width="515" alt="2" src="https://user-images.githubusercontent.com/17696492/76381386-50303b00-6390-11ea-9a33-e282dfae761d.png">

### 补充信息

无

**Comment by shenghanqin** [comment]
这里可能挖坑了。因为我之前在做alpha测试时，是要求分享信息function带有options设置的，你这里可以在上面写一个空对象试试看。具体还得等修复。
