### ISSUE TITLE
禁用小图片资源转base64无效

### ISSUE THREAD

**Issue by fly-sheep** [NervJS/taro#5670]
![image](https://user-images.githubusercontent.com/30622989/76383724-ac4a8d80-6397-11ea-9728-b53eecadfb92.png)
![image](https://user-images.githubusercontent.com/30622989/76383768-de5bef80-6397-11ea-9964-cf329830c412.png)
![image](https://user-images.githubusercontent.com/30622989/76383806-fdf31800-6397-11ea-838d-9af7c24212cc.png)
![image](https://user-images.githubusercontent.com/30622989/76383847-1bc07d00-6398-11ea-92ae-1bd2c171b24c.png)
由于canvase画图不用使用base64格式的图片，所以这里我需要把taro默认的10KB以下资源自动转base64的默认选项禁用
![image](https://user-images.githubusercontent.com/30622989/76383962-8376c800-6398-11ea-8345-b85850508a87.png)

**Comment by shenghanqin** [comment]
我是这么写的。
```
mini: {
    imageUrlLoaderOption: {
      limit: 0
    },
    postcss: {}
}
```

> 另外，canvas画图的小问题，我也在研究，你可以看看“快快戴口罩”小程序。

**Comment by fly-sheep** [comment]
> 我是这么写的。
> 
> ```
> mini: {
>     imageUrlLoaderOption: {
>       limit: 0
>     },
>     postcss: {}
> }
> ```
> 
> > 另外，canvas画图的小问题，我也在研究，你可以看看“快快戴口罩”小程序。

谢谢解答

**Comment by gouflv** [comment]
希望能更新下文档
