### ISSUE TITLE
打包两个同名不同目录的图片文件被覆盖

### ISSUE THREAD

**Issue by fupengl** [NervJS/taro#5671]
不同目录引用两个同名不同的文件
![image](https://user-images.githubusercontent.com/20211964/76079201-24533500-5fdf-11ea-9739-b8c51f474e6a.png)
打包完资源被覆盖
![image](https://user-images.githubusercontent.com/20211964/76079241-3a60f580-5fdf-11ea-8ca5-723368a634df.png)
![Uploading image.png…]()

### 期望行为

可以正常区分两个文件

**Comment by luckyadam** [comment]
Taro 版本多少，升级到 2.0.6 的话应该没这个问题了

**Comment by fupengl** [comment]
> Taro 版本多少，升级到 2.0.6 的话应该没这个问题了

之前版本是`2.0.5`

**Comment by fupengl** [comment]
> Taro 版本多少，升级到 2.0.6 的话应该没这个问题了

谢谢，我试试
