### ISSUE TITLE
【微信小程序】代码中使用了原生组件，按照文档编译后js被编译（应该不会编译）

### ISSUE THREAD

**Issue by libn-net** [NervJS/taro#5672]
### 问题描述

代码中使用了原生组件，按照文档编译后js被编译（应该不会编译），实际上组件库中已经被编译，同时如果使用了template，会被忽略掉，如果使用了mini..include，会提示语法错误

before：taro中代码贴图
![image](https://user-images.githubusercontent.com/4444446/76390978-5f6fb280-63a9-11ea-9632-e14548134d7c.png)

after：小程序中代码贴图
![image](https://user-images.githubusercontent.com/4444446/76391032-8332f880-63a9-11ea-9a8a-7ddcb1ad7e65.png)

### 系统信息
$ taro info
👽 Taro v3.0.0-alpha.4

  Taro CLI 3.0.0-alpha.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.0 - ~/.nvm/versions/node/v12.14.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.4 => 2.0.4 
      @tarojs/components: 2.0.4 => 2.0.4 
      @tarojs/components-qa: 2.0.4 => 2.0.4 
      @tarojs/plugin-babel: 2.0.4 => 2.0.4 
      @tarojs/router: 2.0.4 => 2.0.4 
      @tarojs/taro: 2.0.4 => 2.0.4 
      @tarojs/taro-alipay: 2.0.4 => 2.0.4 
      @tarojs/taro-h5: 2.0.4 => 2.0.4 
      @tarojs/taro-qq: 2.0.4 => 2.0.4 
      @tarojs/taro-quickapp: 2.0.4 => 2.0.4 
      @tarojs/taro-rn: 2.0.4 => 2.0.4 
      @tarojs/taro-swan: 2.0.4 => 2.0.4 
      @tarojs/taro-tt: 2.0.4 => 2.0.4 
      @tarojs/taro-weapp: 2.0.4 => 2.0.4 
      @tarojs/webpack-runner: 2.0.4 => 2.0.4 
      eslint-config-taro: 2.0.4 => 2.0.4 
      eslint-plugin-taro: 2.0.4 => 2.0.4 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.4 => 2.0.4 
      stylelint-taro-rn: 2.0.4 => 2.0.4

**Comment by luckyadam** [comment]
组件 js 被编译会有问题么
