### ISSUE TITLE
样式全局污染

### ISSUE THREAD

**Issue by moseszhou** [NervJS/taro#5673]
### 问题描述
按照官网提供的css引入方式import './css/path/name.css'，我发现name.css中定义class都是全局
我试了一下使用import styles from './css/path/name.css'方式也有问题，styles对象会为空，无法像react那样做模块化样式

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息
System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.5 => 2.0.5 
      @tarojs/components: 2.0.5 => 2.0.5 
      @tarojs/components-qa: 2.0.5 => 2.0.5 
      @tarojs/components-rn: 2.0.5 => 2.0.5 
      @tarojs/plugin-less: 2.0.5 => 2.0.5 
      @tarojs/router: 2.0.5 => 2.0.5 
      @tarojs/taro: 2.0.5 => 2.0.5 
      @tarojs/taro-alipay: 2.0.5 => 2.0.5 
      @tarojs/taro-h5: 2.0.5 => 2.0.5 
      @tarojs/taro-qq: 2.0.5 => 2.0.5 
      @tarojs/taro-quickapp: 2.0.5 => 2.0.5 
      @tarojs/taro-redux-rn: 2.0.5 => 2.0.5 
      @tarojs/taro-rn: 2.0.5 => 2.0.5 
      @tarojs/taro-router-rn: 2.0.5 => 2.0.5 
      @tarojs/taro-swan: 2.0.5 => 2.0.5 
      @tarojs/taro-tt: 2.0.5 => 2.0.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      @tarojs/webpack-runner: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.3.1 => 16.3.1 
      react-native: 0.59.10 => 0.59.10 
      stylelint-config-taro-rn: 2.0.5 => 2.0.5 
      stylelint-taro-rn: 2.0.5 => 2.0.5 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
文档在这 [使用 CSS Modules](https://nervjs.github.io/taro/docs/css-modules.html#docsNav)

**Comment by moseszhou** [comment]
> 文档在这 [使用 CSS Modules](https://nervjs.github.io/taro/docs/css-modules.html#docsNav)

对于小程序按照文档打开开关即可，
但是如果打开开关后，RN端是有问题的

我查看taro编译后的RN临时代码


`
function _getClassName() {
  var className = []
  var args = arguments[0]
  var type = Object.prototype.toString
    .call(args)
    .slice(8, -1)
    .toLowerCase()

  if (type === 'string') {
    args = args.trim()
    args && className.push(args)
  } else if (type === 'array') {
    args.forEach(function(cls) {
      cls = _getClassName(cls).trim()
      cls && className.push(cls)
    })
  } else if (type === 'object') {
    for (var k in args) {
      k = k.trim()

      if (k && args.hasOwnProperty(k) && args[k]) {
        className.push(k)
      }
    }
  }

  return className.join(' ').trim()
}

function _getStyle(classNameExpression) {
  var className = _getClassName(classNameExpression)

  var classNameArr = className.split(/\s+/)
  var style = []

  if (classNameArr.length === 1) {
    style.push(_styleSheet[classNameArr[0].trim()])
  } else {
    classNameArr.forEach(function(cls) {
      style.push(_styleSheet[cls.trim()])
    })
  }

  return style
}


render(){
return ( <View style={_getStyle(_styleSheet.headtop)}></View>)
}
`
这段代码中_getStyle方法期待的是一个className，而输入的确实一个object。

导致无法获取到对应的样式。最终_getStyle(_styleSheet.headtop)返回的是undefule

**Comment by moseszhou** [comment]
如果开启CSS `Modules，在rn编译的后的文件中应该是
```js
render(){
return ( <View style={_styleSheet.headtop}></View>)
}
```
而不是
```js
render(){
return ( <View style={_getStyle(_styleSheet.headtop)}></View>)
}
```

期望在编译器中修改一下

**Comment by Pines-Cheng** [comment]
直接开启 CSS Modules 就能重现吗？

**Comment by moseszhou** [comment]
> 直接开启 CSS Modules 就能重现吗？

开启即可重现，可以看看taro生成的rn临时代码。
注意：index.js 对应index.module.less文件名，而不是index.less

**Comment by Pines-Cheng** [comment]
2.1.x 已解决

**Comment by qiuziz** [comment]
@Pines-Cheng 2.2.7中 undefind
