### ISSUE TITLE
app.alipay.tsx 编译问题

### ISSUE THREAD

**Issue by Jetsly** [NervJS/taro#5674]
### 问题描述
在`taro 1.x.x`版本 的时候
> `app.tsx`采用不同平台的包来编译, 包含 `app.alipay.tsx`,编译后会输出`app.json`

更新到`taro 2.x.x`后
>  `app.alipay.tsx`,编译后直接输出`app.alipay.json`,没有变成 `app.json`

### 期望行为

`app.alipay.tsx`,编译后变成 `app.json`

### 系统信息
👽 Taro v2.0.6

  Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: ^2.0.6 => 2.0.6 
      @tarojs/plugin-babel: ^2.0.6 => 2.0.6 
      @tarojs/plugin-uglifyjs: ^2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
是怎么配置的

**Comment by Jetsly** [comment]
> 是怎么配置的

没有配置任何参数,在`Taro 1.xx.xx`版本 ,自动会把`app.alipay.tsx`或者`app.weapp.tsx`, 编译成 `app.json`, 当对应的平台编译的时候

**Comment by Jetsly** [comment]
> 是怎么配置的

看逻辑以前的版本..会强制写成`app.json` 
https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/mini/entry.ts#L159
