### ISSUE TITLE
AtModal弹窗隐藏后canvas残留

### ISSUE THREAD

**Issue by DrakeXiang** [NervJS/taro#5677]
### 问题描述

如题，使用taro-ui中的AtModal弹窗组件展示canvas，当弹窗隐藏后canvas会残留在屏幕

### 复现步骤

1. 引入AtModal组件
2. 在弹窗中展示canvas
3. 显示弹窗
4. 隐藏弹窗

```js
const CANVAS_ID = 'canvas';
...
...

componentDidMount() {
  this.setState({ showModal: true });
  setTimeout(() => this.setState({ showModal: false }), 5000);
}

 testDraw = () => {
    var context = wx.createCanvasContext(CANVAS_ID, this.$scope);

    context.setStrokeStyle('#00ff00');
    context.setLineWidth(5);
    context.rect(0, 0, 200, 200);
    context.stroke();
    context.setStrokeStyle('#ff0000');
    context.setLineWidth(2);
    context.moveTo(10, 10);
    context.arc(100, 100, 60, 0, 2 * Math.PI, true);
    context.moveTo(140, 100);
    context.arc(100, 100, 40, 0, Math.PI, false);
    context.moveTo(85, 80);
    context.arc(80, 80, 5, 0, 2 * Math.PI, true);
    context.moveTo(125, 80);
    context.arc(120, 80, 5, 0, 2 * Math.PI, true);
    context.stroke();
    context.draw();
  };

render() {
      return  (
        <AtModal isOpened={this.state.showModal}>
          <AtModalContent>
            <Canvas
              canvasId={CANVAS_ID}
              id={CANVAS_ID}
            />
          </AtModalContent>
        </AtModal>
       )
}
```

### 期望行为

canvas随弹窗显示/隐藏

### 系统信息

Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.1 => 2.0.1
      @tarojs/components: 2.0.1 => 2.0.1
      @tarojs/components-qa: 2.0.1 => 2.0.1
      @tarojs/mini-runner: 2.0.1 => 2.0.1
      @tarojs/mobx: 2.0.1 => 2.0.1
      @tarojs/mobx-h5: 2.0.1 => 2.0.1
      @tarojs/plugin-babel: 2.0.1 => 2.0.1
      @tarojs/plugin-csso: 2.0.1 => 2.0.1
      @tarojs/plugin-sass: 2.0.1 => 2.0.1
      @tarojs/plugin-uglifyjs: 2.0.1 => 2.0.1
      @tarojs/router: 2.0.1 => 2.0.1
      @tarojs/taro: 2.0.1 => 2.0.1
      @tarojs/taro-alipay: 2.0.1 => 2.0.1
      @tarojs/taro-h5: 2.0.1 => 2.0.1
      @tarojs/taro-qq: 2.0.1 => 2.0.1
      @tarojs/taro-quickapp: 2.0.1 => 2.0.1
      @tarojs/taro-rn: 2.0.1 => 2.0.1
      @tarojs/taro-swan: 2.0.1 => 2.0.1
      @tarojs/taro-tt: 2.0.1 => 2.0.1
      @tarojs/taro-weapp: 2.0.1 => 2.0.1
      @tarojs/webpack-runner: 2.0.1 => 2.0.1
      eslint-config-taro: 2.0.1 => 2.0.1
      eslint-plugin-taro: 2.0.1 => 2.0.1
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.1 => 2.0.1
      stylelint-taro-rn: 2.0.1 => 2.0.1

### 补充信息

如果使用普通View组件显示/隐藏模拟弹窗则canvas不会残留

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by fanyingmao** [comment]
我碰到了一样的问题需要怎处理？
![Uploading Screenshot_2020-06-24-01-26-29-88.png…]()

**Comment by DrakeXiang** [comment]
> 我碰到了一样的问题需要怎处理？

我是手动用css控制了canvas的显示和隐藏- -
