### ISSUE TITLE
ios10 toast和modal的透明蒙层出现过就不会消失，导致页面无法操作

### ISSUE THREAD

**Issue by TracyWei** [NervJS/taro#5682]
### 问题描述
ios10的系统中，只要出现过toast或modal，它们消失后，透明蒙层的display仍为block，蒙层覆盖在页面上，导致无法操作页面

### 复现步骤

1. 用ios系统版本10.x的手机的safari
2. 触发showToast或showLoading或showModal

### 期望行为

ios10的系统中，toast和modal消失时，透明蒙层也消失

### 报错信息

由于ios 10报错：attempted to assign to readonly property，阻塞将透明蒙层display置为none的代码执行，导致蒙层还存在

### 补充信息
在safari10以下 报错attempted to assign to readonly property
https://www.jianshu.com/p/4fc256f34c0d

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
ios10在国内的使用量大约在1%吧，影响不大吧。

**Comment by sam-plus** [comment]
> CC @Littly

原因：taro-h5/api/utils.js handleBeforeDestroy()函数中
document.body.style = bodyInlineStyle报错（attempted to assign to readonly property） 中断了js的执行，导致hide mask的代码没有执行。
ios 11以下，不支持直接操作style的方式，可以通过设置属性进行style，像这样：
document.body.setAttribute('style', bodyInlineStyle)
