### ISSUE TITLE
TypeScript 中 defineConstants  全局变量 eslint 警告

### ISSUE THREAD

**Issue by crazy365966834** [NervJS/taro#5683]
- IDE：WebStorm
- taro init app 的时候，选择了使用TypeScript。
- 设置了全局变量
`
  defineConstants: {
    SERVICE_URL: '"https://www.test.com"',
  },`

然后，就出现ESLint 警告了。
`TS2304: Cannot find name 'SERVICE_URL'.
ESLint: 'SERVICE_URL' is not defined.(no-undef)`
![image](https://user-images.githubusercontent.com/32411130/76519424-ed2bca80-649b-11ea-8aa5-c4e2c29360c0.png)

有没有什么合适的建议？

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/76607034-3e949200-654e-11ea-8d01-1d329c9592f3.png)
配置一下 eslint 就行了

**Comment by Garfield550** [comment]
或者在你项目的 `global.d.ts` 里声明 `type SERVICE_URL: string`

**Comment by jarbozhang** [comment]
或者在.eslintrc文件中设置globals属性，例如："globals": {"DEFAULT_URL": "readonly"}
