### ISSUE TITLE
样式文件平台条件编译不起作用

### ISSUE THREAD

**Issue by fuyue111** [NervJS/taro#5684]
### 问题描述
如下指定只在微信小程序生效：
```
/* #ifdef weapp */
.test{  
  word-break: break-all;
  color: red;
}
/* #endif */
```
编译RN，还是报word-break无效，如下：
![image](https://user-images.githubusercontent.com/19793236/76530667-0427e800-64af-11ea-874a-493a4faf8b65.png)

看了这个[issue](https://github.com/NervJS/taro/issues/5363)，这么写：
```
/* #ifdef weapp /
.test{  
  word-break: break-all;
  color: red;
}
/ #endif */
```
编译RN不报错了，但是微信小程序上没起作用，看起来相当于注释了。是我写法不对吗？Taro版本v1.3.31，看文档是1.3+支持。不知道还有哪里不对？

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息
Taro v1.3.31

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/envs.html#%E6%A0%B7%E5%BC%8F%E6%96%87%E4%BB%B6%E4%B8%AD%E8%B7%A8%E5%B9%B3%E5%8F%B0%E6%94%AF%E6%8C%81

看下这个文档

**Comment by fuyue111** [comment]
起作用的，不好意思。只是编译RN有警告而已

**Comment by qiuziz** [comment]
@luckyadam 样式文件条件编译不行，目录下同时存在index.scss和index.rn.scss 在tsx中import './index.scss' yarn dev:h5不会编译index.rn.scss 还是编译index.scss
taro2.2.7 直接init生成一个模板仓库 就能复现 能看下吗

**Comment by qiuziz** [comment]
样式内条件编译是可以的
