### ISSUE TITLE
样式文件中跨平台支持，微信小程序sass失效

### ISSUE THREAD

**Issue by luowenming** [NervJS/taro#5686]
源文件scss
![1](https://user-images.githubusercontent.com/25970980/76587375-9ddaae00-651e-11ea-975a-9cf1acd14659.png)

编译后的文件，两个都执行了，条件编译失效
![2](https://user-images.githubusercontent.com/25970980/76587413-c367b780-651e-11ea-9aa5-0446dfa2d87e.png)
![3](https://user-images.githubusercontent.com/25970980/76587454-e8f4c100-651e-11ea-8b37-c6838d140960.png)

**Comment by luckyadam** [comment]
没有复现喔，taro 版本是多少

**Comment by luowenming** [comment]
taro 1.3.3

**Comment by luowenming** [comment]
taro 版本1.3.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li,Weitao"<notifications@github.com&gt;; 
发送时间: 2020年3月13日(星期五) 下午5:12
收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 
抄送: "择一人终老"<851788635@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NervJS/taro] 样式文件中跨平台支持，微信小程序sass失效 (#5686)





 
没有复现喔，taro 版本是多少

**Comment by luckyadam** [comment]
升级到 1.3.38 试试把
