### ISSUE TITLE
修改代码以后经常报错'Page "pages/index/index" has not been registered yet.'，重启以后可以解决问题，但是太麻烦了

### ISSUE THREAD

**Issue by liuyeqing** [NervJS/taro#5691]
修改代码以后经常报错'Page "pages/index/index" has not been registered yet.'，重启以后可以解决问题，但是太麻烦了，整个项目只有一个页面，页面名称叫做index.jsx，代码如下：
import Taro, {Component} from '@tarojs/taro'
import {View, Swiper, SwiperItem} from '@tarojs/components'
import {AtSteps } from 'taro-ui'
class Index extends Component {
    constructor () {
        super(...arguments)
        this.state = {
            current: 0,
        }
    }
    onChange (current) {
        this.setState({
            current
        })
    }
    render () {
        const items = [
            { 'title': '步骤一', 'desc': '这里是额外的信息，最多两行' },
            { 'title': '步骤二', 'desc': '这里是额外的信息，最多两行' },
            { 'title': '步骤三', 'desc': '这里是额外的信息，最多两行' }
        ]
        return (
            <AtSteps
                items={items}
                current={this.state.current}
                onChange={this.onChange.bind(this)}
            />
        )
    }
}
export default Index;

**Comment by lukeymyuan** [comment]
同有这个问题，当我用npm run dev:weapp 的时候

**Comment by mihuartuanr** [comment]
同样的问题，只要是分包文件就报这个错，以前的版本（半年前）没报过

**Comment by lice001** [comment]
同有这个问题，当我用npm run dev:weapp 的时候

**Comment by HeyShinner** [comment]
@liuyeqing 请问重启是指？我重启 `npm run dev:weapp` 不管用，taro 版本是 1.3.9

**Comment by HeyShinner** [comment]
> 同有这个问题，当我用npm run dev:weapp 的时候

请问解决了吗

**Comment by younthu** [comment]
同遇到。taro 2.2.11升级到3.0.27以后遇到的。

**Comment by Chen-jj** [comment]
应该是小程序开发者工具的问题。

**Comment by progerchai** [comment]
这个问题有人有办法解决吗？
我的是taro v2.2.3
小程序开发工具是1.05.2111300，首页和个别页面能出现，大部分都是类似这种
```Page "pages/post/index" has not been registered yet```
重启过开发工具了也不行

**Comment by progerchai** [comment]
> 这个问题有人有办法解决吗？ 我的是taro v2.2.3 小程序开发工具是1.05.2111300，首页和个别页面能出现，大部分都是类似这种 `Page "pages/post/index" has not been registered yet` 重启过开发工具了也不行
> 
> 真机上都可以

在小程序开发工具上，一直显示<page></page> ,然后就没有内容了
后来把taro 版本cli升级到一个特定版本，并且update project 依赖到一个特定版本，重新跑起来了
