### ISSUE TITLE
【2.0.6升级BUG】第三方组件样式丢失？

### ISSUE THREAD

**Issue by edwards19900128** [NervJS/taro#5694]
### 问题描述
从2.0.1 升级到 2.0.6 使用了Vant组件的一些样式丢失了。
如果有需要我把单个页面抽出来，打包放上来。
![image](https://user-images.githubusercontent.com/11594850/76605666-c88f2b80-654b-11ea-8280-015c69e960c4.png)
![image](https://user-images.githubusercontent.com/11594850/76605848-258ae180-654c-11ea-8da2-c1d5ecffcc5f.png)
![image](https://user-images.githubusercontent.com/11594850/76605855-2754a500-654c-11ea-9d85-99e32ed080f0.png)

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86

看下是不是这个问题

**Comment by edwards19900128** [comment]
> https://nervjs.github.io/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86
> 
> 看下是不是这个问题

但我之前可用版本就是2.0.1..是2.0.1 -> 2.0.6 就UI变了~
