### ISSUE TITLE
taro next  引用两个hook时useDidShow无法执行

### ISSUE THREAD

**Issue by liaoliao666** [NervJS/taro#5696]
### 问题描述

taro next hook里如果使用了useDidShow 当页面引用两个或两个以上hook时 只执行第一个hook的 useDidShow

### 复现步骤

1. useAHook.ts
  useDidShow(() => {
    console.log("A文件进来了")
  })
 useBHook.ts
useDidShow(() => {
    console.log("B文件进来了")
  })
2.  useAHook();
useBHook();
3. 只会打印 “A文件进来了”

**Comment by yuche** [comment]
我不太理解你发出的复现步骤和问题描述，因为就你的复现会导致只打印 “B文件进来了”，也就是说最后的一个 hooks 会执行。可问题描述会这个执行模式相悖。
