### ISSUE TITLE
Taro v3.0.0-alpha.7 在支付宝端 的超过2个页面引用了同一个组件，就会编译报错

### ISSUE THREAD

**Issue by WangShuXian6** [NervJS/taro#5697]
### 问题描述

>在支付宝端 的超过2个页面引用了同一个组件，就会编译报错

>该问题在微信端不存在，只存在支付宝端

### 复现步骤

>小程序新建2个页面 pageA,pageB

>2个页面都使用同一个组件 comC

>执行 npm run build:alipay 后，打包正常，打开开发工具或真机预览，pageA页面的comC组件显示错误，无任何样式信息

>执行 npm run dev:alipay 后，打包正常，打开开发工具或真机预览,pageA页面直接报错，无法显示正常页面，而是显示如下：
![WechatIMG8701](https://user-images.githubusercontent.com/30850497/76616688-8bcd2f80-655f-11ea-8b10-69a3392cd09b.jpeg)

>```./client``` 目录为 Taro 编译后的目录
### 期望行为

>在支付宝端，不同页面可以引用相同的组件

### 报错信息
![WechatIMG8701](https://user-images.githubusercontent.com/30850497/76616688-8bcd2f80-655f-11ea-8b10-69a3392cd09b.jpeg)

### 系统信息

```
Taro v3.0.0-alpha.7


  Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-alpha.7 => 3.0.0-alpha.7 
      @tarojs/taro: 3.0.0-alpha.7 => 3.0.0-alpha.7 
      eslint-config-taro: 3.0.0-alpha.7 => 3.0.0-alpha.7 
      react: ^16.10.0 => 16.13.0 
```

**Comment by yuche** [comment]
组件引入的 css 是 scss 吗

**Comment by WangShuXian6** [comment]
> 组件引入的 css 是 scss 吗

>是less

**Comment by yuche** [comment]
换成普通 css 看看是否会存在此问题

**Comment by dr2009** [comment]
+1 我这边也是这个问题... 公共组件被多个页面引用,公共组件有自己的 less. 编译报错
 只要less 去除..就可以运行..

**Comment by Chen-jj** [comment]
@WangShuXian6 @dr2009 应该是编译时给 app.acss 注入的 import 漏了分号导致。。beta4修复。
