### ISSUE TITLE
在h5端中的路由生命周期，怎么控制输入不存在的路由重定向到404页面？

### ISSUE THREAD

**Issue by 521707** [NervJS/taro#5699]
**问题描述**

taro没有路由的生命周期提供， 该如何对不存在的路由进行重定向404页面？

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by gxsandzxl** [comment]
这个问题没有解决方案吗？

**Comment by smackgg** [comment]
@gxsandzxl 低版本暂时可以这样解决。最新 3.1 beta 版本已经支持了，但是这个版本 bug 比较多

**Comment by gxsandzxl** [comment]
@smackgg unhandledrejection事件触发不了，直接写在html中都没触发

**Comment by ZakaryCode** [comment]
[参考文档](http://taro-docs.jd.com/taro/docs/next/apis/base/weapp/app-event/onPageNotFound)
