### ISSUE TITLE
微信 小程序 引入本地图片资源 报错

### ISSUE THREAD

**Issue by Marszht** [NervJS/taro#5705]
### 问题描述
引入本地图片资源 报错 , 报错信息如下
![image](https://user-images.githubusercontent.com/38552120/76680981-ae774b00-6628-11ea-9b55-381769e25f3c.png)

### 复现步骤
如下引入 本地图片部分会报错 

```js
const baseIconPath = '../../image/home';
const SERVICE_LIST = [{
  title: '团体定制',
  desc: '团体服装定制',
  icon: `${baseIconPath}/tddz.png`
},
]


```

### 期望行为

希望能正确显示引入的图片

### 报错信息

![image](https://user-images.githubusercontent.com/38552120/76680981-ae774b00-6628-11ea-9b55-381769e25f3c.png)

### 系统信息

![image](https://user-images.githubusercontent.com/38552120/76681035-4bd27f00-6629-11ea-9871-5d6db409995d.png)

### 补充信息
是否 目前静态文件只能 以下面这种形式 引入
```js
import business_suit from '@/image/home/business-suit.png';
```

**Comment by shenghanqin** [comment]
@Marszht 图片需要加上require('图片路径')

**Comment by Marszht** [comment]
> @Marszht 图片需要加上require('图片路径')

你是指只能单张图片 去引入么？ 还是？
