### ISSUE TITLE
[Taro3 alpha7] 使用 require 方式引入组件时报错 m.usedExports.map is not a function

### ISSUE THREAD

**Issue by wuchangming** [NervJS/taro#5709]
### 问题描述
import { View } from '@tarojs/components' // 编译正常
const View = require('@tarojs/components').View // 编译报错

报错信息：
m.usedExports.map is not a function
(node:4093) UnhandledPromiseRejectionWarning: TypeError: m.usedExports.map is not a function
    at chunk.modulesIterable.forEach

原因分析见 --->  **「补充信息」**

### 复现步骤

```js
import { View } from '@tarojs/components' // 编译正常✅
const View = require('@tarojs/components').View // 编译报错❌

```

### 期望行为

支持 require 的方式引入组件不报错

### 补充信息

当用`require('xxx')`方式引入组件时，[这里](https://github.com/NervJS/taro/blob/next/packages/taro-mini-runner/src/plugins/TaroLoadChunksPlugin.ts#L53)的`m.usedExports`不是一个数组，打印出来是个boolean。
试了下加了前置判断`typeof m.usedExports.map === 'function'` 后，看起来都正常了

**Comment by yuche** [comment]
这个问题很好解决，但我必须提醒你的是目前 @tarojs/components 在小程序和 h5 端都没有默认导出，也就是说一旦你在任意一个地方使用了 require，那这个包的 tree-shaking 将会完全崩溃，在小程序端将会引入所有组件，你的 base.wxml 体积会大幅增加，在 h5 端也会打包所有你没用过的组件。

**Comment by wuchangming** [comment]
直接 require('@tarojs/components') 时 tree-shaking 会失效。
```
 const View = require('@tarojs/components').View
```

但转一道好像又好了
文件1：adapterTaro.js
```js
import { View } from '@tarojs/components'
export { View }
```
使用 require 引用文件：
```js
const View = require('./View').View

```
