### ISSUE TITLE
Taro.eventCenter 全局消息的问题

### ISSUE THREAD

**Issue by lizhoukai** [NervJS/taro#571]
**问题描述**
1.路由A页面点击确认按钮后 发送全局消息事件 Taro.eventCenter.trigger('getInfo', data)
2.然后跳转到路由B页面 B页面在componentWillMount 页面被加载的时候 监听Taro.eventCenter.on('getInfo', e => { })
监听不到该事件

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 路由A页面
// 点击跳转到B路由页面
 formSubmit(e) {
    const { formData, totalPrice } = this.state
    Taro.eventCenter.trigger('getInfo', {
      formData: formData,
      totalPrice: totalPrice
    })
    Taro.navigateTo({ url: '../B/B' })
  }

// 路由B页面
// 页面被载入
  componentWillMount() {
    Taro.eventCenter.on('getInfo', v => {
      console.log(v)// 第一次获取不到，返回到A页面再进来可以监听到
    })
  }
```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.0.0-beta.23]
 - Node.js 版本 [e.g. v9.0.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
这是肯定的
> 1.路由A页面点击确认按钮后 发送全局消息事件 Taro.eventCenter.trigger('getInfo', data)
说明事件已经触发了，监听在事件发生之后

**Comment by lizhoukai** [comment]
@luckyadam 谢谢 那我这种情况还是用Redux 比较好

**Comment by Whiteyork** [comment]
为什么不支持历史消息订阅呢

**Comment by FE-wuhao** [comment]
> 这是肯定的
> 
> > 1.路由A页面点击确认按钮后 发送全局消息事件 Taro.eventCenter.trigger('getInfo', data)
> 
> 说明事件已经触发了，监听在事件发生之后

如果是react hooks方式使用taro3，父页面向子页面传递参数，子页面如何才能在时间发生之前监听到呢，无论是使用useDidShow、useReady、useLayoutEffect还是useEffect都无法做到，除非手动在父页面手动延迟trigger
