### ISSUE TITLE
-webkit-box-orient: vertical; 这个样式编译之后会被过滤掉

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#5710]
我的样式是这样的，用来做多行省略号的，但是-webkit-box-orient: vertical;编译成小程序和h5之后这个样式就不见了，cli版本是2.0.6，我隐约记得之前的可能1.几的版本是可以使用省略号的，但是最近的版本就一直不行了。
```
&--2 {
    display: -webkit-box;
    overflow: hidden;
    -webkit-box-orient: vertical;
    text-overflow: ellipsis;
    -webkit-line-clamp: 2;
  }
```

**Comment by ShaoGongBra** [comment]
经测试后发现是webpage的编译问题，按照下面的写法就能正常编译
```
&--2 {
    display: -webkit-box;
    overflow: hidden;
    /*! autoprefixer: ignore next */
    -webkit-box-orient: vertical;
    text-overflow: ellipsis;
    -webkit-line-clamp: 2;
  }
```

**Comment by infinnie** [comment]
感谢

**Comment by infinnie** [comment]
其实可以手动添加更高版本的 autoprefixer 依赖。

**Comment by GeSnowBoy** [comment]
> 其实可以手动添加更高版本的 autoprefixer 依赖。

请问怎么升级

**Comment by infinnie** [comment]
> > 其实可以手动添加更高版本的 autoprefixer 依赖。
> 
> 请问怎么升级

`package.json`

**Comment by ElvisXie** [comment]
> > > 其实可以手动添加更高版本的 autoprefixer 依赖。
> > 
> > 
> > 请问怎么升级
> 
> `package.json`

自己在项目中手动安装最新版本的 autoprefixer 并不生效，编译的时候还是用的 cli 内部自己的 autoprefixer 版本，还是得用注释的形式去 hack

**Comment by infinnie** [comment]
> > > > 其实可以手动添加更高版本的 autoprefixer 依赖。
> > > 
> > > 
> > > 请问怎么升级
> > 
> > 
> > `package.json`
> 
> 自己在项目中手动安装最新版本的 autoprefixer 并不生效，编译的时候还是用的 cli 内部自己的 autoprefixer 版本，还是得用注释的形式去 hack

更旧版的是可以的新版就不行了
