### ISSUE TITLE
Function(...) is not a function

### ISSUE THREAD

**Issue by Smi1e96** [NervJS/taro#5712]
### 问题描述

# Function(...) is not a function 

原本是2.0.5版本，在解决[缺少index.scss](https://github.com/NervJS/taro-ui/issues/960)问题 重新安装node_modules 之后 运行dev显示编译成功 但是在微信开发者工具出现Function(...) is not a function 升级2.0.6依旧无法解决 可以确定不是误删文件导致

我找了下issuses 没有反馈此问题

### 复现步骤
项目启动 运行dev 显示编译成功 在微信开发者工具 就会显示这问题

### 期望行为
项目正常运行

### 报错信息

![image](https://user-images.githubusercontent.com/31199247/76721268-6b2cf180-677a-11ea-8e5d-fa908ecbc592.png)

### 系统信息
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/components-qa: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/redux: 2.0.6 => 2.0.6 
      @tarojs/redux-h5: 2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/taro-qq: 2.0.6 => 2.0.6 
      @tarojs/taro-quickapp: 2.0.6 => 2.0.6 
      @tarojs/taro-rn: 2.0.6 => 2.0.6 
      @tarojs/taro-swan: 2.0.6 => 2.0.6 
      @tarojs/taro-tt: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 

### 补充信息

如果需要复现 我可以发送源码包

**Comment by Garfield550** [comment]
看是不是 #5681 的问题

**Comment by Smi1e96** [comment]
@Garfield550  我有配置 使用async await Taro 2.0.5就出现这个问题了

**Comment by Garfield550** [comment]
@Smi1e96 https://github.com/NervJS/taro/issues/5681#issuecomment-599036451

**Comment by Smi1e96** [comment]
@Garfield550  确实是这问题:laughing: 我之前从2.0.0到现在使用都没有问题  就今天才出现的:weary:  谢谢你 那我关闭了issue了
