### ISSUE TITLE
ESLint 提示 'Config' is defined but never used. Allowed unused vars must match

### ISSUE THREAD

**Issue by FE-Sakamoto** [NervJS/taro#5713]
### 问题描述

使用@tarojs/cli@2.0.6创建taro项目
```shell
Desktop: taro init test
👽 Taro v2.0.6

Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ 233
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板
```

用`vscode`打开项目`eslint`插件提示 'Config' is defined but never used. Allowed unused vars must match
### 复现步骤

1. 按照如下方法创建项目
```shell
Desktop: taro init test
👽 Taro v2.0.6

Taro 即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目介绍！ 233
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板
```
2. 使用VSCode打开项目
```shell
code test
```
3. VSCode 安装/开启 ESLint插件
4. 明明使用了`Config`还是提示 'Config' is defined but never used. Allowed unused vars must match

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

在不关闭`unused vars`这条规则的前提下,能正确的进行错误提示

### 报错信息
'Config' is defined but never used. Allowed unused vars must match /Taro/.eslint(no-unused-vars)

### 系统信息

Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/components-qa: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/mobx: ^2.0.6 => 2.0.6 
      @tarojs/mobx-h5: ^2.0.6 => 2.0.6 
      @tarojs/mobx-rn: ^2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/taro-qq: 2.0.6 => 2.0.6 
      @tarojs/taro-quickapp: 2.0.6 => 2.0.6 
      @tarojs/taro-rn: 2.0.6 => 2.0.6 
      @tarojs/taro-swan: 2.0.6 => 2.0.6 
      @tarojs/taro-tt: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 
    npmGlobalPackages:
      typescript: 3.7.3

### 补充信息
尝试按照[issues 5207](https://github.com/NervJS/taro/issues/5207#issuecomment-569623807)里提到的方法去解决,但是会出现另一个错误
'Taro' is defined but never used.eslint(@typescript-eslint/no-unused-vars)
![image](https://user-images.githubusercontent.com/15774890/76729651-9de3e380-6794-11ea-9331-6185628faa5e.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by F-loat** [comment]
``` diff
-  "no-unused-vars": ["error", { "varsIgnorePattern": "Taro" }]
+  "@typescript-eslint/no-unused-vars": ["error", { "varsIgnorePattern": "Taro" }]
```
