### ISSUE TITLE
使用“腾讯位置选点插件”,需要小程序跳转到插件的页面

### ISSUE THREAD

**Issue by Xjiaxiong** [NervJS/taro#5715]
### 问题描述

使用“腾讯位置选点插件”,需要小程序跳转到插件的页面，根据文档操作无法跳转到相关插件页面

### 复现步骤

1. 
![image](https://user-images.githubusercontent.com/17800867/76737353-9415ac80-67a3-11ea-9b91-09eb1235aace.png)
2. 根据文档操作
`    const url = `plugin://pickMapMarkerPlugin/chooseLocation/index? 
  key=${key}&referer=${referer}&location=${location}&category=${category}`

    Taro.navigateTo({
      url
    });`

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

能顺利的跳转到插件的地图选点界面，进行业务操作

### 报错信息

![image](https://user-images.githubusercontent.com/17800867/76737553-f40c5300-67a3-11ea-9464-5fbed85cf5da.png)

### 系统信息

并找不到插件的页面路径，我哪里还没有配置吗？还是原本这个功能就是开发不完善的，求大家帮助一下？

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by linyongfu2013** [comment]
在app.config.js 里添加插件配置：
```
  plugins: {
    chooseLocation: {
      version: "1.0.4",
      provider: "wx76a9a06e5b4e693e"
    }
  }
```

然后在在页面的 index.config.js 里声明插件：
```
  usingComponents: {
    'chooseLocation': 'plugin://chooseLocation/index'
  }
```

最后在页面里直接使用：
```
    Taro.navigateTo({
      url: 'plugin://chooseLocation/index?key=xxx&referer=taro-demo',
      success: (result) => {
        console.log("choose success...")
        console.log(result)
      }
    }).then(promise => console.log("promise"))
```

但是我的确定选点后返回的 `result` 打印出来没有位置数据，是一个 `eventChannel` ，你解决了没，怎么获取位置数据？

**Comment by jacktang** [comment]
@linyongfu2013 不是应该使用Taro.chooseLocation？
