### ISSUE TITLE
taro3 cli 初始化项目出错,使用的react/redux/less 模板

### ISSUE THREAD

**Issue by dr2009** [NervJS/taro#5717]
### 问题描述

taro3 cli 初始化项目出错,使用react/redux/less 模板

### 复现步骤

`taro init taro3-demo`
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 redux

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
项目正常初始化

### 报错信息

模板解析错误
![Xnip2020-03-16_19-10-01.jpg](https://i.loli.net/2020/03/16/7TRsgWrEcMqJOKZ.jpg)
### 系统信息

Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
      npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm

### 补充信息

应该是模板解析错误...   postion 183 是 `<%= typescript %>`
```
"templateInfo": {
    "name": "<%= template %>",
    "typescript": <%= typescript %>,
    "css": "<%= css %>"
  },
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
没能复现，你可以在网络好的情况下多尝试一下几次

**Comment by dr2009** [comment]
> 没能复现，redux 模板是在 git 的仓库里，init 的时候会远程拉取，你可以在网络好的情况下多尝试一下几次

模板已经拉下来了...是解析出的错

我刚刚换了node版本... 10.19.0 12.15.0 可以了.
但是最新的12.16.1 ,13.11.0 不可以.

能帮我看下我不可以的这两个版本你可以正常运行吗?

**Comment by shenghanqin** [comment]
@dr2009 好像是。你可以继续看看其他issue里面有讲到node13好像有新功能对这个编译有影响的。我用的是10.14。

**Comment by Garfield550** [comment]
检查一下有没有这两个文件夹`~/.taro` `~/.taro2`，有就删一下

**Comment by Psli** [comment]
node的版本有影响这个，用回node10才能用。

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-project-templates/commit/38d6859393550a5dd33fe7e59973758211745285
已修复，可以重新试试

**Comment by dr2009** [comment]
> [NervJS/taro-project-templates@38d6859](https://github.com/NervJS/taro-project-templates/commit/38d6859393550a5dd33fe7e59973758211745285)
> 已修复，可以重新试试

可以了...  👍
看来 node 13 对json后缀有限制了??...

**Comment by luckyadam** [comment]
> > [NervJS/taro-project-templates@38d6859](https://github.com/NervJS/taro-project-templates/commit/38d6859393550a5dd33fe7e59973758211745285)
> > 已修复，可以重新试试
> 
> 可以了... 👍
> 看来 node 13 对json后缀有限制了??...

是目录中出现了 package.json 的话，文件的格式必须是一个正常的 json 文件
