### ISSUE TITLE
列表渲染使用自定义组件作为根节点，key值编译错误

### ISSUE THREAD

**Issue by John60676** [NervJS/taro#5719]
### 问题描述

> 在列表渲染时使用自定义组件作为根节点，编译出来的小程序代码中缺失了key值，导致渲染出错

### 复现步骤

1. 定义一个自定义组件
2. 在页面中引入自定义组件并将其用在列表渲染上
3. 把列表渲染的key值绑定在自定义组件上
4. key 值没被正确的处理，导致列表渲染出现错误，下面的代码体现的效果就是switch的checked状态总被第一个元素所“继承”

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
import Taro, { Component } from '@tarojs/taro'
import { View, Button } from '@tarojs/components'
import Test from './test'

export default class Index extends Component {
  state = {
    todoData: []
  }

  addItem() {
    const { todoData } = this.state
    this.setState({
      todoData: [
        {
          id: todoData.length
        },
        ...todoData
      ]
    })
  }

  render() {
    const { todoData } = this.state
    return (
      <View>
        {todoData.map(items => (
          <Test key={items.id} />
        ))}
        <View>
          <Button onClick={this.addItem}>添加值</Button>
        </View>
      </View>
    )
  }
}


```
```js
import Taro, { Component } from '@tarojs/taro'
import { View, Switch } from '@tarojs/components'

export default class Test extends Component {
  render() {
    return (
      <View>
        <Switch />
      </View>
    )
  }
}

```
### 报错信息

这个是错误的gif示例
![taro-bug](https://user-images.githubusercontent.com/21698973/76818763-68e19a80-6841-11ea-8614-2d7a9cdcf3ce.gif)

下面是编译后的小程序代码，其中的 **wx:key的值** 在列表数据  **loopArrary231**  中并不存在

<img width="769" alt="taro-bug1" src="https://user-images.githubusercontent.com/21698973/76818773-6f701200-6841-11ea-8ce6-db3a990c39ca.png">

<img width="971" alt="taro-bug2" src="https://user-images.githubusercontent.com/21698973/76818777-7139d580-6841-11ea-8bd6-b631a397df88.png">

### 系统信息

 Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v10.10.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/components-qa: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/taro-qq: 2.0.6 => 2.0.6 
      @tarojs/taro-quickapp: 2.0.6 => 2.0.6 
      @tarojs/taro-rn: 2.0.6 => 2.0.6 
      @tarojs/taro-swan: 2.0.6 => 2.0.6 
      @tarojs/taro-tt: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 
    npmGlobalPackages:
      typescript: 3.7.5
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by zonetw** [comment]
遇到同樣的問題 +1
目前我解決的方式是先把用來渲染的資料先清空, 在 setState 的 callback 用新資料塞一次 ...

**Comment by John60676** [comment]
> 遇到同樣的問題 +1
> 目前我解決的方式是先把用來渲染的資料先清空, 在 setState 的 callback 用新資料塞一次 ...

其实不用这样，key值只要稍微计算一下就能解决这个问题。比如用 String、或者Number 包装一下就行了

**Comment by zonetw** [comment]
> @zonetw 其实不用这样，key值只要稍微计算一下就能解决这个问题。比如用 String、或者Number 包装一下就行了
`<Test key={String(item.id)} />`
類似這樣子嗎？

**Comment by John60676** [comment]
> > @zonetw 其实不用这样，key值只要稍微计算一下就能解决这个问题。比如用 String、或者Number 包装一下就行了
> 
> `<Test key={String(item.id)} />`
> 
> 類似這樣子嗎？

@zonetw 是的
