### ISSUE TITLE
h5模式在微信浏览器上url不变更

### ISSUE THREAD

**Issue by 13160102112** [NervJS/taro#572]
**问题描述**
使用Taro.navigateTo进行页面跳转，在微信浏览器跳转正常，但是点击右上角复制链接，url还是跳转之前的url
**复现步骤**

```js
// 这里可以贴代码

```

**期望行为**
期望链接是当前页面的url，不会导致右上角分享之后的链接始终是第一个页面的链接

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: macOs
 - Taro 版本 1.0.0-beta.22
 - Node.js 版本 8.9.3

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
你看看浏览器里有没有报错

**Comment by luckyadam** [comment]
这是微信的问题，没有 copy Url hash

**Comment by 13160102112** [comment]
写了个ionic的demo也是如此，确实复制链接微信不会带上hash，那只能引入微信jssdk解决分享问题了

**Comment by crimson968** [comment]
@EvanMaFYH 大佬，IOS首页签名错误的问题有遇到吗
