### ISSUE TITLE
Taro.showModal 使用时 cancelText 未定义

### ISSUE THREAD

**Issue by chenxinbin** [NervJS/taro#5720]
### 问题描述

使用showModal时，默认取消按钮文本显示为undefined。

### 复现步骤
如下面代码所示，代码在微信小程序中正常，但是在支付宝小程序中 取消按钮 文本显示为 undefined， 必须在js代码中写 `cancelText: '取消',` 才可以。

```js
`    Taro.showModal({
      title: '删除确认',
      content: '确认删除吗？删除后，数据将丢失！如果队列不为空或状态已开启则无法删除！',
    }).then(res => {})`

```

### 期望行为

期待支付宝和微信平台一致，不需要显式定义 cancelText

### 报错信息

无报错

### 系统信息

C:\Users\xinbin>taro info
👽 Taro v2.0.5

  Taro CLI 2.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
应该是支付宝 API 的问题。
