### ISSUE TITLE
[ Taro v3.0.0-alpha.7]IntersectionObserver is not defined

### ISSUE THREAD

**Issue by quanduoling** [NervJS/taro#5722]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


import { View, Button, Image, OpenData, OfficialAccount, WebView } from "@tarojs/components";
import Taro from '@tarojs/taro'
import React from "react";

export default function User(props) {


  const aw= new IntersectionObserver(
     e=>console.log(e)
   )

  return (
    <View>
     ss
    </View>
  )
}

```

### 期望行为

正常使用IntersectionObserver

### 报错信息

<img width="705" alt="screenshot" src="https://user-images.githubusercontent.com/14134514/76842271-f1c5f980-6874-11ea-9543-d4b4fd6dce87.png">

### 系统信息

 Taro v3.0.0-alpha.7

  Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /opt/local/bin/zsh
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
你 API 用错了：
https://developers.weixin.qq.com/miniprogram/dev/api/wxml/wx.createIntersectionObserver.html

**Comment by quanduoling** [comment]
确实，谢谢
