### ISSUE TITLE
[2.0.4] config中配置使用常量时无法生效

### ISSUE THREAD

**Issue by Kimbohn** [NervJS/taro#5724]
### 问题描述
navigationBarTitleText 没有显示对应的值
```
import Taro, { PureComponent } from '@tarojs/taro'
import { View  } from '@tarojs/components'
import './index.less'

const BarTitle = '小程序名字'

class Index extends PureComponent {

  config: Taro.Config = {
    navigationBarTitleText: BarTitle ,
    navigationBarBackgroundColor: '#f06637',
    navigationBarTextStyle: 'white'
  }

  render() {
    return (
      <View className='container'>
        hello world
      </View>
    )
  }
}

```

### 复现步骤

1. 定义常量BarTitle
2. 配置config

### 期望行为

navigationBarTitleText 显示对应的值

### 报错信息

navigationBarTitleText 没有显示对应的值，显示‘WeChat’， 配置navigationBarBackgroundColor等其它属性也如此。

**Comment by shenghanqin** [comment]
打包后，这个config就到达index.json里面，也就是说，其实是不支持这么改的。如果你想后面再改页面标题，需要调用Taro.setNavigationBarTitle

```
Taro.setNavigationBarTitle({
          title: `主页`
        })
```

**Comment by yyzclyang** [comment]
目前 taro 貌似不支持根据环境来定义不同的 config，比如测试和生产的 `pages` 是两个不同的数组，根据 `process.env.NODE_ENV` 来识别，编译直接报错

**Comment by shenghanqin** [comment]
我是想用dotenv来动态加载.env，里面是配置，这样的话，根据环境不同来加载不同的.env文件就好了。然后，这种.env可以保留在本地，github上都不用提交，防止配置泄露。

**Comment by yyzclyang** [comment]
如果我将 `config` 的配置放到一个 `json` 里面，然后读取这个 `json` 文件，将配置赋值给 `app.tsx` 的 `config` ，编译会报错。
如果我想设置两个 `app.tsx` 文件入口，根据环境选择其中一个，貌似没暴露入口配置出来。
或者将 `App` 抽离成组件，在 `app.tsx` 引入后 render，这样也是无法正常编译的。
