### ISSUE TITLE
[Taro3 alpha9] 隐藏页面中的 Taro.setNavigationBarTitle 会作用于当前显示的页面

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#5725]
### 复现步骤

1. 使用 Mobx 作为全局状态管理.
2. 小程序 TabBar 内有 A 和 B 两个页面.
3. 打开小程序时首先进入 A 页面, 在 A 页面中设置 useEffect 更新页面标题, 依赖于 Mobx.
4. 点击 TabBar 切换到 B 页面, 在 B 页面中更新 Mobx 的值.

```js
/**
 * Mobx 状态管理
 * src/store.js
 */
import { observerable } from 'mobx'

export class Store {
    @observerable title = 'A页面'
}

export default new Store()
```

```jsx
/**
 * A 页面
 * src/pages/a.jsx
 */
import React from 'react'
import { View } from '@tarojs/components'
import { observer } from 'mobx-react'
import store from '../store'

export default observer(() => {
	React.useEffect(() => Taro.setNavigationBarTitle({title: store.title}), [store.title])

	return <View></View>
})
```

```jsx
/**
 * B 页面
 * src/pages/b.jsx
 */
import React from 'react'
import { Button } from '@tarojs/components'
import store from '../store'

export default () => {
	return <Button onClick={() => store.title = 'A页面新标题'}>更新A页面标题</Button>
}
```

### 期望行为

A页面调用 Taro 相关 API 应该只作用于A页面.

### 报错信息

A页面 useEffect 触发后 B页面的标题被修改了.

### 系统信息

taro 3.0.0.alpha.9

### 补充信息

**临时解决方案**

```tsx
/**
 * 更新页面标题
 *
 * BUGFIX: TabBar 中的页面一旦打开永不 unmount.
 *  其中的 useEffect 即使在页面隐藏时也仍然会运行, 会把标题设置在错误的页面上.
 *  为防止这种情况发生, 只在页面显示后才更新标题.
 */
export function useTitle(title: string) {
    // 页面首次打开视为已显示, 因为页面首次显示时不会触发 show 事件.
    const [show, setShow] = useState(true)

    useDidShow(() => setShow(true))
    useDidHide(() => setShow(false))

    useEffect(() => {
        if (!show || !title) return
        setNavigationBarTitle({ title })
    }, [show, title])
}
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
这肯定做不到，内置 API 和框架是完全解耦的，它们调用的就是对应小程序的 API，当你调用 API 的时候，API 本身并不知道当前的状态是什么，只忠于自己接受到的参数。

你这个需求也不适合用 mobx 做，UI 状态管理工具应该尽量避免于 UI 无关的副作用状态和参数。如果你确实喜欢观察者模式，这类工作应该用 rxjs 来做。

**Comment by cncolder** [comment]
同意, 我了解这个运行结果即不违背 Taro3, 也符合 React 的逻辑.
只是效果上有点让人意外.

**Comment by charmtiger** [comment]
你应该使用 autorun 来监听 observable 的变化

**Comment by cncolder** [comment]
> 你应该使用 autorun 来监听 observable 的变化

我不是监听不到变化, 而是在错误的时间点调用了修改标题的微信 API.
setNavigationBarTitle 是与页面无关的, 不管什么时候调用都是更新当前页面的标题.

**Comment by charmtiger** [comment]
你是想在当前页面 修改 上一个页面的标题吗？如果实在实现不了，直接自己定义导航栏。

**Comment by cncolder** [comment]
@charmtiger No

我想让 A页面 的标题随着全局状态改变, 却不想在 B页面 对全局状态的修改后, 导致 A页面 修改了 B页面 的标题.

**Comment by charmtiger** [comment]
不就是因为 setNavigationBarTitle 只能修改当前页面的title，所以可以自定义headerBar，或者 在返回a页面的时候 onShow 来更新title
