### ISSUE TITLE
[Taro 3 alpha.9]大概率出现相邻两个不同元素渲染成同一个元素

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro#5726]
### 问题描述

下图中红框和绿框标注的，红框出现问题，看起来像是两个元素渲染成一个了，或者说是混淆了。

复现几率大概为 40%，不过整个项目中，就一处有此问题。

正常状态
![8dmoKP.png](https://s1.ax1x.com/2020/03/17/8dmoKP.png)

异常状态
![8dmsu6.png](https://s1.ax1x.com/2020/03/17/8dmsu6.png)

### 复现步骤

这是我的tsx代码

```js
<View className="shop-toolbar__shopname M-vertical-bottom">
    {!!shopInfo.shop_pic_small && <View className="shop-toolbar__logo" style={{backgroundImage: 'url(' + shopInfo.shop_pic_small + ')' }}/>}
    <View className="shop-toolbar__text M-flex-item">
        {shopInfo.shop_name}
    </View>
  </View>
```

### 系统信息

Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.config/yarn/global/node_modules/.bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.0-alpha.9 => 3.0.0-alpha.9 
      @tarojs/components: 3.0.0-alpha.9 => 3.0.0-alpha.9 
      @tarojs/plugin-uglifyjs: 2.0.0 => 2.0.0 
      @tarojs/taro: 3.0.0-alpha.9 => 3.0.0-alpha.9 
      @tarojs/webpack-runner: 2.0.0 => 2.0.0 
      eslint-config-taro: 3.0.0-alpha.9 => 3.0.0-alpha.9 
      eslint-plugin-taro: 2.0.0 => 2.0.0 
      react: ^16.10.0 => 16.13.0

**Comment by charmtiger** [comment]
考虑到此问题不好复现，我自己做了点尝试。

在图片上面加套一个 Block， 也就是稍微改变一下结构，问题就不出现了。
```js
<View className="shop-toolbar__shopname M-vertical-bottom">
            {!!shopInfo.shop_pic_small && <Block><View className="shop-toolbar__logo" style={{ backgroundImage: 'url(' + shopInfo.shop_pic_small + ')' }}/></Block>}
            <View className="shop-toolbar__text M-flex-item">
              {shopInfo.shop_name}
            </View>
          </View>
```

不过奇怪的是，去掉这个Block，还会出现，但是概率变成 ~1/40 ，刷新接近200次，一般是30-40次出现一次，原来是 每3次就会出现一次。

**Comment by yuche** [comment]
这类概率复现的问题我倾向于认为小程序容器的 bug

**Comment by charmtiger** [comment]
几率确实非常小，暂且留意一下，我争取多找找规律
