### ISSUE TITLE
官方redux模板编译RN时报错：Cannot add a child that doesn't have a Yoganodeto a parent without a measure function!(Trying toadd A'RCTRAW Text [text: O] to arctview')

### ISSUE THREAD

**Issue by dxhuii** [NervJS/taro#573]
没有对代码进行任何更改，初始化项目就做了以下操作。

**问题描述**
[问题描述：官方redux模板编译RN时报错：Cannot add a child that doesn't have a Yoganodeto a parent without a measure function!(Trying toadd A'RCTRAW Text [text: O] to arctview')]

**复现步骤**
[复现问题的步骤]

taro init ikanfan
👽 Taro v1.0.0-beta.23

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

? 请输入项目介绍！
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 Redux 模板

taro build --type rn --watch
👽 Taro v1.0.0-beta.23

**期望行为**
[问题得到解决]

**报错信息**

![](https://ws1.sinaimg.cn/large/006bnWk0gy1fuzltlrdqcj30u01o0juf.jpg)

**系统信息**
 - 手机：小米MIX2
 - 手机系统：MIUI 10 稳定版
 - 操作系统: ![](https://ws1.sinaimg.cn/large/006bnWk0gy1fuzm43imsqj30e207y3zl.jpg)
 - Taro 版本 [e.g. v1.0.0-beta.23]
 - Node.js 版本 [e.g. v8.10.0]

**Comment by Pines-Cheng** [comment]
可以贴一下 pages/index/index.js 的代码吗？ @dxhuii

**Comment by Pines-Cheng** [comment]
或者你可以参考一下这个issue：https://github.com/facebook/react-native/issues/13243

**Comment by dxhuii** [comment]
就是你们官方实例，我没有改过代码 @Pines-Cheng 
```javascript
import Taro, { Component } from '@tarojs/taro'
import { View, Button } from '@tarojs/components'
import { connect } from '@tarojs/redux'

import { add, minus, asyncAdd } from '../../actions/counter'

import './index.scss'


@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add () {
    dispatch(add())
  },
  dec () {
    dispatch(minus())
  },
  asyncAdd () {
    dispatch(asyncAdd())
  }
}))
class Index extends Component {

    config = {
    navigationBarTitleText: '首页'
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.props.add}>+</Button>
        <Button className='dec_btn' onClick={this.props.dec}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View>{this.props.counter.num}</View>
        <View>Hello, World</View>
      </View>
    )
  }
}

export default Index
```

**Comment by Pines-Cheng** [comment]
@dxhuii 我这边在本地初始化了一个 redux 模版的项目，没有报错。
 你把 View 组件里面的文字用 Text 组件包裹一下试试。
```js
        <View><Text>{this.props.counter.num}</Text></View>
        <View><Text>Hello, World</Text></View>
```

**Comment by dxhuii** [comment]
@Pines-Cheng 试了，加了之后就解决了，不会报错了，谢谢。
