### ISSUE TITLE
项目升级2.0以后，css文件样式引用失败

### ISSUE THREAD

**Issue by Rxiaoyi** [NervJS/taro#5730]
项目升级2.0以后，css文件样式引用失败，是2.0样式文件要改为scss吗？

**Comment by luckyadam** [comment]
http://taro-docs-in.jd.com/taro/docs/migrate-to-2.html#%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E5%A4%B1%E6%95%88%E4%BA%86
