### ISSUE TITLE
Button的openType没有定义addFriend。导致ts报错

### ISSUE THREAD

**Issue by huanxsd** [NervJS/taro#5738]
### 问题描述

Button的openType没有定义addFriend。导致ts报错。
另外，Button也缺少openId的定义。

### 复现步骤

创建项目，启用Type Script。
使用Button，openType使用addFriend。
ts报错。

```js
<Button className='btn' size='mini' openType='addFriend' openId='123' onClick={this.addFriend}>
```

### 期望行为

ts不报错

### 报错信息
Type '"addFriend"' is not assignable to type '"contact" | "contactShare" | "share" | "getRealnameAuthInfo" | "getAuthorize" | "getPhoneNumber" | "getUserInfo" | "lifestyle" | "launchApp" | "openSetting" | "feedback" | undefined'.

### 系统信息

👽 Taro v2.0.7

  Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.8.3

### 补充信息
附QQ小程序button文档地址
https://q.qq.com/wiki/develop/miniprogram/component/form/button.html

**Comment by luckyadam** [comment]
可以提个 issue 哦
