### ISSUE TITLE
Taro 3: 建议把 navigator.product 的值设为 Taro，便于第三方包兼容

### ISSUE THREAD

**Issue by fjc0k** [NervJS/taro#5741]
https://github.com/NervJS/taro/blob/1ae116df767da7fd1028e763573938dc754fa68e/packages/taro-runtime/src/bom/navigator.ts#L16

缘起于这个 issue：https://github.com/fjc0k/taro-axios/issues/16, 目前我并不能找到一个更好的方法区分 taro1、2、3。或者将taro版本加入环境变量？

作为参考，这是 axios 中的一个方法：

```js
function isStandardBrowserEnv() {
  if (typeof navigator !== 'undefined' && (navigator.product === 'ReactNative' || navigator.product === 'NativeScript' || navigator.product === 'NS')) {
    return false;
  }

  return typeof window !== 'undefined' && typeof document !== 'undefined';
}
```

**Comment by fjc0k** [comment]
目前，我是这样判断的，但是因为 process.env.TARO_ENV 为 weapp，导致 1 的 weapp 包被引入，导致了报错，不知道有没有更好的办法剔除对旧版 weapp 的引用：
![image](https://user-images.githubusercontent.com/13151189/77056785-eb1eba00-6a0d-11ea-9ce5-15c7df671276.png)

**Comment by yuche** [comment]
目前 Taro CLI 会注入 @tarojs/runtime 的 document 和 navigator 到全局对象，我们目前判断是否为 Taro 3的方式 `!!document.scripts`。

**Comment by fjc0k** [comment]
@yuche  👌，那这么看来是不能通过环境变量来判断了，目前只有环境变量能剔除代码。另外，下面两个建议可以考虑下：

- 把 navigator.product 设为 Taro
- 添加环境变量 TARO_MAJOR_VERSION，方便第三方包剔除无关代码，以后有个4、5、6的也好兼容

**Comment by yuche** [comment]
添加新的环境变量 TARO_VERSION，等于当前的 semver 版本
