### ISSUE TITLE
百度小程序输出的 class不正确

### ISSUE THREAD

**Issue by Zane0816** [NervJS/taro#5744]
### 问题描述
![image](https://user-images.githubusercontent.com/6336389/77084521-07385080-6a3a-11ea-928b-ed239759da5a.png)
css 文件中的类名和组件上的类名不一致 导致所有组件都没有样式

### 期望行为
期望可以正常显示

### 报错信息
无报错

### 系统信息

```log
 Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.7 => 2.0.7 
      @tarojs/cli: 2.0.7 => 2.0.7 
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/mini-runner: 2.0.7 => 2.0.7 
      @tarojs/mobx: 2.0.7 => 2.0.7 
      @tarojs/mobx-h5: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nervjs: ^1.5.6 => 1.5.6 
```

### 补充信息
https://smartprogram.baidu.com/forum/topic/show/72906
百度小程序关于组件样式的非兼容性公告

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Zane0816** [comment]
😅是我搞错了

**Comment by yeojongki** [comment]
@Zane0816  我刚编译百度小程序也有这种情况，导致我的全局样式不生效，你是怎么解决的？

**Comment by Zane0816** [comment]
> @Zane0816 我刚编译百度小程序也有这种情况，导致我的全局样式不生效，你是怎么解决的？

设置`Component.options = { addGlobalClass: true }`即可解决

**Comment by yeojongki** [comment]
> > @Zane0816 我刚编译百度小程序也有这种情况，导致我的全局样式不生效，你是怎么解决的？
> 
> 设置`Component.options = { addGlobalClass: true }`即可解决

我们情况不一样，我是 `pages/*`  下的页面文件，然后编译后的 `json` 文件自己加上了 `{ component: ture }`，等于说页面变成了组件，很迷的操作

**Comment by Zane0816** [comment]
@yeojongki 
pages/* 的文件也可以设置addGlobalClass=true 的
实在不行就更新版本吧:sweat_smile:

**Comment by yeojongki** [comment]
> @yeojongki
> pages/* 的文件也可以设置addGlobalClass=true 的
> 实在不行就更新版本吧😅

是可以加，但应该不是版本的问题，编译肯定是有问题的。本来我页面文件根本就不用设置为组件。

**Comment by Zane0816** [comment]
@yeojongki 🤣🤣 我也有时候遇到编译出来的不多 整着整着就莫名其妙的好了

**Comment by yeojongki** [comment]
> @yeojongki 🤣🤣 我也有时候遇到编译出来的不对 整着整着就莫名其妙的好了

除了微信小程序好一点，其他平台的，一言难尽了😐

**Comment by Chen-jj** [comment]
为了实现 ref，需要使用 Component 构造页面以使用恰当的生命周期。你配一下 addGlobalClass 就好了。

![image](https://user-images.githubusercontent.com/11807297/82892502-2a273980-9f82-11ea-8070-2620b46e0f9a.png)

**Comment by yeojongki** [comment]
> 为了实现 ref，需要使用 Component 构造页面以使用恰当的生命周期。你配一下 addGlobalClass 就好了。
> 
> ![image](https://user-images.githubusercontent.com/11807297/82892502-2a273980-9f82-11ea-8070-2620b46e0f9a.png)

嗯，配置了就行。这里应该要给个文档说明下，不然不知道是什么问题。
