### ISSUE TITLE
APP.JSX中使用taro.setStorageSync存储参数，在子页面中使用Taro.getStorageSync首次打开页面的时候没获取到数据，再次打开页面才有

### ISSUE THREAD

**Issue by dzlishen** [NervJS/taro#5745]
### 问题描述
APP.JSX中使用taro.setStorageSync存储参数，在子页面中使用Taro.getStorageSync首次打开页面的时候没获取到数据，再次打开页面才获取到数据。

1. 在app.jsx中的componentWillMount，使用taro.setStorageSync存储参数。通过分享打开小程序的子页面时在componentWillMount使用Taro.getStorageSync未能获取到数据。但是关闭页面再次点击又获取到了数据。

```js

Taro.setStorageSync('token', res.data.token)

var token = Taro.getStorageSync('token')

```

**Comment by HungryBird** [comment]
同一个问题 要刷新才能取到数据...

**Comment by fred8617** [comment]
我好像也遇到了这个问题，用户总说需要重新登录
