### ISSUE TITLE
【BUG】子组件拿不到路由信息

### ISSUE THREAD

**Issue by DonaldDai** [NervJS/taro#5747]
[router.zip](https://github.com/NervJS/taro/files/4358683/router.zip)

编译成小程序预览，内有提示。

**Comment by yuanhl1994** [comment]
我2.0.6，也是子组件拿不到路由，你是怎么解决的呢，除了从上层传过来 @DonaldDai

**Comment by mouse9527** [comment]
2.2.2同样的问题
