### ISSUE TITLE
[Taro3 beta0] 引入 app.config.ts 值为 undefined

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#5749]
### 问题描述

此前的 alpha 版, 可以 import 'app.config.ts'.

之所以要引入这个文件, 有几个目的:

1. custom-tab-bar 复用 tabBar 配置.
2. 统一处理 navigateTo 和 switchTab, 甚至是提前判断错误的路由地址.
3. 如果想自定义 NavigationBar 也会希望复用标题和背景色吧? (虽然我没用到过)

### 复现步骤

1. custom-tab-bar/index.tsx 文件

```tsx
import appConfig from '../app.config'

console.log(appConfig) // <- 返回 undefined
```

### 系统信息

taro 3.0.0.beta.0

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ruofeng086** [comment]
@luckyadam 同为undefined，请问解决了吗？version: 3.0.2

**Comment by ruofeng086** [comment]
@yuche

**Comment by daiyuanhao** [comment]
请问如何解决的
