### ISSUE TITLE
props 定义可选参数，defaultProps有默认值，提示 [ts] 对象可能为“未定义”。

### ISSUE THREAD

**Issue by imcoka** [NervJS/taro#575]
如下图：
![image](https://user-images.githubusercontent.com/10229333/45139260-c115f600-b1e1-11e8-95bb-e28edc4bcdf6.png)
![image](https://user-images.githubusercontent.com/10229333/45139271-ca06c780-b1e1-11e8-83e5-80aac96950d3.png)
组件定义了泛型current字段是可选参数，定义了静态defaultProps 的current为0。
使用的是否提示对象可能为“未定义”，可选参数存在undefined类型。

期望行为：当父级没有传递current的值，current应该是number类型的0。
bug级别：非优先。

**系统信息**

- 操作系统: macos
- Taro 版本 1.0.0-beta.24
- Node.js 版本 v10.5.1
- typescript 版本 3.0.3

**Comment by yuche** [comment]
这点其实原生 React 也没有做到，只能做到写了 defaultProps 使用组件不用传入 props。

ref:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html
