### ISSUE TITLE
[Taro3 beta0] 缺少 custom-tab-bar/index.config.js 无法编译.

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#5750]
### 问题描述

CLI 应该是统一检查所有 *.config.js 是否存在, 之前页面没有这个文件, NavigationTitle 会取默认值, 现在没有这个文件无法编译.

但 custom-tab-bar 是特例, 它不是页面而是组件, 组件现在是没有 .config.js 的, 因为组件现在已经没有配置项了.

### 复现步骤

1. app.config.js `{tabBar:{custom: true}}`
2. custom-tab-bar/index.js

### 系统信息

taro 3.0.0.beta.0

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
之前的版本没问题对吗

**Comment by cncolder** [comment]
@yuche alpha9 页面允许没有 .config.ts, 是从 beta0 开始强制要求的.

这个改动对于页面来说还好, 当然不强制更好, 因为页面可能没有需要配置的东西.
但对于 custom-tab-bar 就显得怪异了.

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/dac8259bc06deca75bba70f39574f2734b994639
已经重置了要求必须有 config.js 的改动，今天会发版
