### ISSUE TITLE
taro 2.0.7 创建项目失败

### ISSUE THREAD

**Issue by lihuaye** [NervJS/taro#5757]
### 问题描述

taro 2.0.7 初始化项目拉取的模板分支为next，且创建失败

### 复现步骤

taro init

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

正确初始化项目

### 报错信息

![image](https://user-images.githubusercontent.com/7691792/77220967-5e483d80-6b80-11ea-8fc5-0fad666a9f92.png)
![965512EF-8950-44E7-8DCA-116947AB4D60](https://user-images.githubusercontent.com/7691792/77221115-a156e080-6b81-11ea-8113-03911d55a00f.png)

### 系统信息

👽 Taro v2.0.7

  Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.22.0 - ~/.npm/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
`rm -rf ~/.taro2`
把 taro2 配置目录删了就好了

**Comment by lihuaye** [comment]
谢谢~
