### ISSUE TITLE
微信小程序端在函数组件中使用 mobx 注入 store 失败

### ISSUE THREAD

**Issue by yeojongki** [NervJS/taro#5762]
### 问题描述
在**微信小程序端**在函数组件中使用 mobx 注入 store 失败
![image](https://user-images.githubusercontent.com/21023676/77232102-ffafad80-6bd9-11ea-9f8a-988138fb70c2.png)

在**H5**端正常
![image](https://user-images.githubusercontent.com/21023676/77232061-caa35b00-6bd9-11ea-867f-e36431591706.png)

### 复现步骤
可复现 repo: https://github.com/yeojongki/mobx-func-component.git

1. taro init 项目
2. 选择 ts + mobx 模板
3. 将首页改为函数组件并注入 counterStore
```ts
import Taro, { FC } from "@tarojs/taro";
import { Button, View } from "@tarojs/components";
import { observer, inject } from "@tarojs/mobx";

type PageStateProps = {
  counterStore: {
    counter: number;
    increment: Function;
    decrement: Function;
    incrementAsync: Function;
  };
};

const Index: FC<PageStateProps> = props => {
  console.log(props);

  return (
    <View>
      {/* <View>{counter}</View> */}
      <Button plain>点击</Button>
    </View>
  );
};

export default inject("counterStore")(observer(Index));

```

### 期望行为
在函数组件中可以拿到注入的 store 数据

### 报错信息
无

### 系统信息

Taro CLI 2.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.1 - D:\web\nodejs\node.EXE
      Yarn: 1.17.3 - D:\web\nodejs\yarn.CMD
      npm: 6.4.1 - D:\web\nodejs\npm.CMD

**Comment by cncolder** [comment]
你可以直接 import counterStore, 删除 inject.
Mobx 已经不建议使用 inject 了, 因为 inject 的参数是字符串.
你甚至可以从 app.js 里删除 MobxProvider.

Mobx 现在的用法是: 只要你的组件用 observer 包起来, 它就能随 @observerable 的值变化.

**Comment by yeojongki** [comment]
> 你可以直接 import counterStore, 删除 inject.
> Mobx 已经不建议使用 inject 了, 因为 inject 的参数是字符串.
> 你甚至可以从 app.js 里删除 MobxProvider.
> 
> Mobx 现在的用法是: 只要你的组件用 observer 包起来, 它就能随 @observerable 的值变化.

这样确实是一个可行的方法。

但注入失败，可以理解为是 Taro 的 bug ?

**Comment by HowardTangHw** [comment]
@cncolder 我也有遇到類似的問題,經你這麽一説突然明白了,是不是意味著mobx可以脫離context了?

因爲在react項目當中 我會有這樣的hooks來在組件中訪問我的store
```
import { MobXProviderContext } from 'mobx-react';
export function useStores(): { RootStore: RootStore } {
    return React.useContext(MobXProviderContext);
}
```
按照你所説的我只要直接
```
import rootStore from '@rootStore'
```
就可以直接引入store了吧?

**Comment by hardtogit** [comment]
遇到同样的问题

**Comment by yeojongki** [comment]
@hardtogit 可以参考这个方法使用
https://github.com/NervJS/taro/issues/5762#issuecomment-602160627
