### ISSUE TITLE
taro ui  AtTextarea onChange方法获取的值不对

### ISSUE THREAD

**Issue by ywanhzy** [NervJS/taro#5768]
### 复现步骤

handleChange (event) {
 //之前版本都是对的 能取到event.target.value的值
//1.3.37版本后就报错   event直接为输入的结果
    this.setState({
      value: event.target.value
    })
  }
  render () {
    return (
      <AtTextarea
        value={this.state.value}
        onChange={this.handleChange.bind(this)}
        maxLength={200}
        placeholder='你的问题是...'
      />
    )
  }
1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息

Taro v3.0.0-experimental.5

  Taro CLI 3.0.0-experimental.5 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.39 => 1.3.39 
      @tarojs/cli: 1.3.39 => 1.3.39 
      @tarojs/components: 1.3.39 => 1.3.39 
      @tarojs/mobx: 1.3.39 => 1.3.39 
      @tarojs/mobx-h5: 1.3.39 => 1.3.39 
      @tarojs/mobx-rn: 1.3.39 => 1.3.39 
      @tarojs/plugin-babel: 1.3.39 => 1.3.39 
      @tarojs/plugin-csso: 1.3.39 => 1.3.39 
      @tarojs/plugin-sass: 1.3.39 => 1.3.39 
      @tarojs/plugin-uglifyjs: 1.3.39 => 1.3.39 
      @tarojs/rn-runner: 1.3.39 => 1.3.39 
      @tarojs/router: 1.3.39 => 1.3.39 
      @tarojs/taro: 1.3.39 => 1.3.39 
      @tarojs/taro-alipay: 1.3.39 => 1.3.39 
      @tarojs/taro-h5: 1.3.39 => 1.3.39 
      @tarojs/taro-swan: 1.3.39 => 1.3.39 
      @tarojs/taro-tt: 1.3.39 => 1.3.39 
      @tarojs/taro-weapp: 1.3.39 => 1.3.39 
      @tarojs/webpack-runner: 1.3.39 => 1.3.39 
      eslint-config-taro: 1.3.39 => 1.3.39 
      eslint-plugin-taro: 1.3.39 => 1.3.39 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.39 => 1.3.39 
      stylelint-taro-rn: 1.3.39 => 1.3.39 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
Taro UI 版本？

**Comment by Garfield550** [comment]
如果 Taro UI 版本是 2.3.1，Textarea 的 onChange 签名改了，变成了 `onChange: (value: string, event?: CommonEvent | undefined) => void`，抱歉忘记更新文档给你造成困扰。

**Comment by ywanhzy** [comment]
之前用的2.2.1也是一样的    现在升级到2.3.1了  我这边做了修改

**Comment by Garfield550** [comment]
2.2.1 没有改 Textarea 的 onChange，确定会直接出现 value 吗？

**Comment by wusuoweiaaa** [comment]
> 2.2.1 没有改 Textarea 的 onChange，确定会直接出现 value 吗？

你好 我使用的版本是taro-ui 2.2.4 重新安装依赖过后 也出现了直接显示value的这个问题

**Comment by Garfield550** [comment]
@wusuoweiaaa @ywanhzy 两位在项目里运行一下 `npm list taro-ui --depth=0` 这个命令然后查看一下具体安装的是哪个版本可以吗？

```bash
taro-ui-troubleshooting> npm list taro-ui --depth=0
taro-ui-troubleshooting@1.0.0 /taro-ui-troubleshooting
└── taro-ui@2.3.1 # 这里会显示你项目具体用了哪个版本
```

**Comment by ywanhzy** [comment]
iumudeMacBook-Pro:meishiliu liumu$ npm list taro-ui --depth=0
meishiliu@3.1.4 /Users/liumu/TaroProjects/meishiliu
└── UNMET DEPENDENCY taro-ui@2.2.1 

npm ERR! missing: taro-ui@2.2.1, required by meishiliu@3.1.4

2.2.1也是一样的

**Comment by wusuoweiaaa** [comment]
> @wusuoweiaaa @ywanhzy 两位在项目里运行一下 `npm list taro-ui --depth=0` 这个命令然后查看一下具体安装的是哪个版本可以吗？
> 
> ```shell
> taro-ui-troubleshooting> npm list taro-ui --depth=0
> taro-ui-troubleshooting@1.0.0 /taro-ui-troubleshooting
> └── taro-ui@2.3.1 # 这里会显示你项目具体用了哪个版本
> ```

显示安装了2.3.1 但是package.json文件里声明的版本是2.2.4
另一台电脑 2.2.4 版本正常

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/77994345-682a2780-735c-11ea-9705-87cd86104c0d.png)
要固定一个版本你需要把 `^` 符号删掉然后重新安装一遍依赖。

**Comment by wusuoweiaaa** [comment]
> ![image](https://user-images.githubusercontent.com/3471836/77994345-682a2780-735c-11ea-9705-87cd86104c0d.png)
> 要固定一个版本你需要把 `^` 符号删掉然后重新安装一遍依赖。

好的 thanks

**Comment by ywanhzy** [comment]
@wusuoweiaaa 
~会匹配最近的小版本依赖包，比如~1.2.3会匹配所有1.2.x版本，但是不包括1.3.0
^会匹配最新的大版本依赖包，比如^1.2.3会匹配所有1.x.x的包，包括1.3.0，但是不包括2.0.0
*安装最新版本的依赖包
