### ISSUE TITLE
ScrollView 在 RN 中无法滚动

### ISSUE THREAD

**Issue by js-newbee** [NervJS/taro#577]
**问题描述**
ScrollView 在 weapp、h5 中都能正常滚动，但在 RN 中无法滚动，效果上就像是被设置了 overflow: hidden。

**复现步骤**
weapp 跟 RN 设置高度的方式不同，如下是在 RN 上测试的代码，有设置了固定高度

```js
<ScrollView
  scrollY
  style={{ height: 400 }}
>
  {contents}
</ScrollView>
```

**期望行为**
可以滚动

**报错信息**
没有报错，内容区域是远大于高度的，但就跟设置了 overflow: hidden 一样，无法滚动。

**系统信息**

 - 操作系统: [Mac 10.13.6]
 - Taro 版本 [1.0.0-beta.24]
 - Node.js 版本 [v10.9.0]

**Comment by Pines-Cheng** [comment]
我本地尝试没问题，如果你是在 iOS 模拟器查看的话，两个手指（或滚轮）是滚不动的哦，得左键长按着滚才行。
