### ISSUE TITLE
请问H5端路由是否可以推出类似keepAlive缓存组件

### ISSUE THREAD

**Issue by wsyxl365** [NervJS/taro#5776]
您好，请问H5端路由是否考虑可以推出类似keepAlive的缓存组件，现在首页分页加载商品数量过多，底部的Tabbar切换后再返回需重新请求，体验不好。谢谢。

**Comment by Chen-jj** [comment]
tabbar 页有缓存不会被销毁的吧，如果实在被销毁了使用 localStorage 实现咯。
