### ISSUE TITLE
[3.0.0-beta.0]，支付宝无法使用原生自定义组件

### ISSUE THREAD

**Issue by liujiayii** [NervJS/taro#5778]
### 问题描述
component2已开启，相对路径正确，微信可以，支付宝报元素不存在，请检查你的代码

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息

![image](https://user-images.githubusercontent.com/38902744/77394643-dad65880-6dda-11ea-9ff8-72fb96fcce00.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
没看到你的复现的代码

**Comment by liujiayii** [comment]
> 没看到你的复现的代码

https://taro-docs.jd.com/taro/next/docs/mini-third-party.html 参照这里的代码写的  一模一样

**Comment by yuche** [comment]
footer 组件单独在支付宝小程序中可以使用吗

**Comment by liujiayii** [comment]
> footer 组件单独在原生支付宝小程序中可以使用吗

footer是支付宝的扩展组件库，原生可以使用

**Comment by liujiayii** [comment]
手动改成wxml的版本，有时候能显示，有时候也显示不出来

**Comment by Chen-jj** [comment]
@liujiayii 支付宝在 template 中使用 usingComponent 声明的组件就会报这个错，还要想想怎么处理。

page.axml

```
<import src="../../base.axml"/>
<template is="tmpl" />
```

base.axml

```
<template name="tmpl">
  <footer></footer>
</template>

```

**Comment by zreo0** [comment]
@Chen-jj 没有看懂这个重复的点，我的问题[#7138](https://github.com/NervJS/taro/issues/7138)是引入了并没有任何表现，也不存在报错的现象，只是去引入了自定义组件。这个结果是支付宝小程序中自定义组件引用有问题吗？

**Comment by Chen-jj** [comment]
@zreo0 你不也是引用原生自定义组件失败吗

**Comment by zreo0** [comment]
@Chen-jj 是的，不过和这个case不太一样，没有报错等信息，而是能运行，但是不会显示出来
例如我的自定义组件中只写了一行字
```js
<view style="height:100%">
  HI, My Component
</view>
```
我直接调用这个自定义组件的时候显示就是啥都没有，最终webview层也找不到该节点
如果是用自定义组件包含内容，则直接把内容显示出来，也没有外层的这个节点，求解是一个原因不

**Comment by vdfor** [comment]
确实存在这个问题，3.0.6依然存在

**Comment by liujiayii** [comment]
> 确实存在这个问题，3.0.6依然存在

爱咋咋地吧 我已经对taro不抱什么希望了

**Comment by Chen-jj** [comment]
看了下也是通过模板拼接渲染 DOM 树的 **remax** 框架，他们只支持使用原生页面。和支付宝小程序关系更密切的他们都没能支持使用原生组件，这个问题目前是无解了。

**Comment by vdfor** [comment]
> > 确实存在这个问题，3.0.6依然存在
> 
> 爱咋咋地吧 我已经对taro不抱什么希望了

taro还是一直在成长的

**Comment by vdfor** [comment]
@Chen-jj  请问下这个有没有支持的计划表？我们用taro开发的一些小程序在一些低端机上性能很差，现在计划把部分组件转成原生开发，希望能够支持支付宝原生自定义组件。

**Comment by dobeweb** [comment]
反馈太慢了。。

**Comment by vdfor** [comment]
> 反馈太慢了。。

我写了个插件，通过这个可以临时实现支持
https://www.npmjs.com/package/@pluve/taro-plugin-mars

**Comment by Chen-jj** [comment]
3.1.0-beta.0 开始支持

**Comment by cjz9032** [comment]
> 3.1.0-beta.0 开始支持

我升了3.1.0-beta.1 还是不行呀... 一样报这个错误

**Comment by Chen-jj** [comment]
@cjz9032 上一下 demo

**Comment by tourze** [comment]
我是从 https://github.com/iconfont-cli/taro-iconfont-cli/issues/43 这边过来的。
实际测试 3.1.1 这个问题没修复呀

**Comment by zhejilifang** [comment]
> 我是从 [iconfont-cli/taro-iconfont-cli#43](https://github.com/iconfont-cli/taro-iconfont-cli/issues/43) 这边过来的。 实际测试 3.1.1 这个问题没修复呀

3.3.14这个问题都没有修复。。完全没有指望了

**Comment by liujiayii** [comment]
> > 我是从 [iconfont-cli/taro-iconfont-cli#43](https://github.com/iconfont-cli/taro-iconfont-cli/issues/43) 这边过来的。 实际测试 3.1.1 这个问题没修复呀
> 
> 3.3.14这个问题都没有修复。。完全没有指望了

哈哈哈搞笑不 一年多了 反正我不用了

**Comment by zhejilifang** [comment]
> > 我是从 [iconfont-cli/taro-iconfont-cli#43](https://github.com/iconfont-cli/taro-iconfont-cli/issues/43) 这边过来的。 实际测试 3.1.1 这个问题没修复呀
> 
> 3.3.14这个问题都没有修复。。完全没有指望了

没有办法 手动在应用组件的页面级别config.js 下添加usingComponents来临时实在支持， 只能说taro3版本的bug比taro2版本的bug 要多的多 而且貌似 修复的进度还是很慢 很多问题一直持续在后续的版本中

> > > 我是从 [iconfont-cli/taro-iconfont-cli#43](https://github.com/iconfont-cli/taro-iconfont-cli/issues/43) 这边过来的。 实际测试 3.1.1 这个问题没修复呀
> > 
> > 
> > 3.3.14这个问题都没有修复。。完全没有指望了
> 
> 哈哈哈搞笑不 一年多了 反正我不用了

没有办法 我只能手动在应用组件的页面级别config.js 下添加usingComponents来临时实现支持， 只能说taro3版本的bug比taro2版本的bug 要多的多，而且貌似修复的进度还是很慢甚至不修复， 很多问题一直留存在后续的版本中

**Comment by Link-X** [comment]
很扯。3.4.10还是没修复...

**Comment by Link-X** [comment]
3.4.10还没修复。

**Comment by lesterlong007** [comment]
> > > > 我是从 [iconfont-cli/taro-iconfont-cli#43](https://github.com/iconfont-cli/taro-iconfont-cli/issues/43) 这边过来的。 实际测试 3.1.1 这个问题没修复呀
> > > 
> > > 
> > > 3.3.14这个问题都没有修复。。完全没有指望了
> > 
> > 
> > 没有办法 手动在应用组件的页面级别config.js 下添加usingComponents来临时实在支持， 只能说taro3版本的bug比taro2版本的bug 要多的多 而且貌似 修复的进度还是很慢 很多问题一直持续在后续的版本中
> > > > > 我是从 [iconfont-cli/taro-iconfont-cli#43](https://github.com/iconfont-cli/taro-iconfont-cli/issues/43) 这边过来的。 实际测试 3.1.1 这个问题没修复呀
> > > > 
> > > > 
> > > > 3.3.14这个问题都没有修复。。完全没有指望了
> > > 
> > > 
> > > 哈哈哈搞笑不 一年多了 反正我不用了
> > 
> > 
> > 没有办法 我只能手动在应用组件的页面级别config.js 下添加usingComponents来临时实现支持， 只能说taro3版本的bug比taro2版本的bug 要多的多，而且貌似修复的进度还是很慢甚至不修复， 很多问题一直留存在后续的版本中
> 
> 你好大佬，请问这种方式应该怎么使用？
> 
> ```js
> import { useGlobalIconFont } from '@/components/iconfont/helper'
> 
> export default {
>   // transparentTitle: 'auto',
>   // titlePenetrate: 'YES',
>   navigationBarTitleText: '登陆',
>   enableShareAppMessage: true,
>   usingComponents: Object.assign(useGlobalIconFont())
> }
> ```
> 
> 这样写不行么

**Comment by lesterlong007** [comment]
引入iconfont，在src/app.config.js配置
usingComponents: Object.assign(useGlobalIconFont())  在（支付宝）小程序上没啥用，直接报错
