### ISSUE TITLE
支持 FlatList 来代替 ScrollView如何使用？

### ISSUE THREAD

**Issue by fuyue111** [NervJS/taro#5783]
### 问题描述
Taro 1.3.4 发布的功能：
components-rn: ScrollView, 支持 FlatList 来代替 ScrollView ([6714e24](https://github.com/NervJS/taro/blob/6714e244e2f6d9a7efe08452d7796ca18ad869ac/packages/taro-components-rn/src/components/ScrollView/index.tsx))，怎么用呢？文档里没看到相关说明
![image#50%](https://user-images.githubusercontent.com/19793236/77400087-a1571a80-6de5-11ea-9bc0-d07d776a8b1e.png)

```
import {ScrollView} from '@tarojs/components-rn'

renderItem() {
}
```
这样？
```
render() {
    return (
      <ScrollView>
        {this.renderItem}
      </ScrollView>
    );
}
```
还是？
```
render() {
    return (
      <ScrollView renderItem={this.renderItem}>
      </ScrollView>
    );
}
```

### 复现步骤

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by iChengbo** [comment]
@fuyue111  把ScrollView直接当成FlatList用就行了，譬如，data、renderItem属性直接用
```js
<ScrollView
    data={[1,2,3]}
    renderItem={this._renderItem}
>
</ScrollView>
```
