### ISSUE TITLE
3.0.0-beta.1 useEffect的 deps =[] 时 页面结束不走 return ()=>{} 方法

### ISSUE THREAD

**Issue by supermavericks** [NervJS/taro#5788]
### 问题描述
在 3.0.0-beta.0 和 3.0.0-beta.1 版本
react 的 useEffect方法参数 deps = [] 时，界面返回销毁时不走：return ()=>{ } 方法
function useEffect(() => {
 //这里会走一次
return ()=> {  //这里在界面销毁时不会运行此函数  }
}, deps?: DependencyList): void;

在 3.0.0-alpha.5 中 运行正常。升级到 3.0.0-beta.0 后出现了如上的情况

### 复现步骤

```js
   useEffect(() => {
    // 这里会进入一次
    console.log("进入") 
    const project = router.params.data
    return () => {
      // 这里在3.0.0-alpha.5 中界面销毁会进入，升级到 3.0.0-beta.0 和 3.0.0-beta.1不会进入
      console.log("销毁") // 
      autoUpdProject(project, projectRef)
    }
  }, [])

```

### 期望行为
 希望 useEffect 的return 方法在 deps=[] 时，也会执行一次

### 系统信息
3.0.0-alpha.5  useEffect方法正常
升级到 3.0.0-beta.0 和 3.0.0-beta.1 版本出现了此问题，
已暂时回退 到 3.0.0-alpha.5

**Comment by yuche** [comment]
你能确认这个页面确实被销毁了吗，小程序的路由机制和 Web 有点不太一样，页面不显示了不代表他被销毁了，只是不显示而已：
https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/route.html

不同路由参数同样会开启不同的页面，参考：https://github.com/NervJS/taro/issues/5652
beta 之后的版本就是为了贴近原生小程序的行为故意做出这样的设置，H5 目前的路由机制也是按照上述微信小程序路由行为进行模拟的，将来的 RN 也会如此。

**Comment by supermavericks** [comment]
@yuche 谢谢回答。以后编译成其他QQ等小程序也会如beta版这样的设计么。期望Taro能统一设计。尽量抹平小程序底层的差异。

**Comment by yuche** [comment]
所有端我们都希望有统一的表现，其它小程序也和微信小程序一样的。

**Comment by victorykong** [comment]
useDidHide 也不执行

**Comment by victorykong** [comment]
左上角返回按钮，不执行页面 didHide，这个怎么处理
![image](https://user-images.githubusercontent.com/50655436/93730005-5766ba00-fbf9-11ea-8aa0-03fa35f4ccab.png)

**Comment by victorykong** [comment]
@yuche

**Comment by victorykong** [comment]
onUnload 对应的 hook 是什么呢？无法监听到页面被返回
