### ISSUE TITLE
[Help Wanted]项目中如何获取config文件夹下定义的环境变量呢？

### ISSUE THREAD

**Issue by ZhenhangTung** [NervJS/taro#579]
**问题描述**
文档中没有提及如何使用环境变量：
* [项目配置](https://nervjs.github.io/taro/docs/config.html)中只提及会打包config下的文件
* [内置环境变量](https://nervjs.github.io/taro/docs/envs.html) 只提供了`process.env.TARO_ENV`，但没有提供其他任何提示，获取自定义的环境变量

**复现步骤**
[复现问题的步骤]
1. 编辑`config/dev.js`
2. 增加变量 `API` 到 `weapp`

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// config/dev.js
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  weapp: {
    API: '"https://example.com/api"'
  },
  h5: {}
}
```

**期望行为**
希望能够知道如何在代码中获取`API`的value。最好能够完善文档。
或者是需要我自己创建`config`的module到`src`下么？

**报错信息**
None
[这里请贴上你的**完整**报错截图或文字]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail.html#env
文档里有用法的

**Comment by luckyadam** [comment]
@ZhenhangTung 定义在 env 下可以了吧

**Comment by ZhenhangTung** [comment]
是的哟。再次测试了一下：
![image](https://user-images.githubusercontent.com/8170159/45210076-386e8700-b2c1-11e8-8a34-0e4dd3397dda.png)
```
module.exports = {
  env: {
    NODE_ENV: '"development"',
    FOO_ENV: '"BAR"',
  },
  defineConstants: {
  },
  weapp: {},
  h5: {}
}
```
是可以的呢！如果可以，希望能够在文档里提及一下呢 🥂

**Comment by ZhenhangTung** [comment]
谢谢 @luckyadam 的解答，您负责这个项目十分辛苦，极大方便了大家开发小程序。十分感激！
那我把这个问题关闭了。

**Comment by luckyadam** [comment]
@ZhenhangTung `weapp` 下没有这样的配置的

**Comment by ZhenhangTung** [comment]
嗯嗯。经过尝试，现在知道了呢。
十分感谢回复 @luckyadam  🥂 我会继续支持Taro的

**Comment by luckyadam** [comment]
@ZhenhangTung 👌

**Comment by cmzz** [comment]
> 嗯嗯。经过尝试，现在知道了呢。
> 十分感谢回复 @luckyadam 🥂 我会继续支持Taro的

请教，该怎么读取配置呢

**Comment by ZhenhangTung** [comment]
> 是的哟。再次测试了一下：
> ![image](https://user-images.githubusercontent.com/8170159/45210076-386e8700-b2c1-11e8-8a34-0e4dd3397dda.png)
> 
> ```
> module.exports = {
>   env: {
>     NODE_ENV: '"development"',
>     FOO_ENV: '"BAR"',
>   },
>   defineConstants: {
>   },
>   weapp: {},
>   h5: {}
> }
> ```
> 
> 是可以的呢！如果可以，希望能够在文档里提及一下呢 🥂

@cmzz here

在`config/dev.js` 或者 `config/prod.js`里配置
