### ISSUE TITLE
Taro  在app.tsx全局引入组件报错

### ISSUE THREAD

**Issue by candyAndBella** [NervJS/taro#5793]
把loading动画的效果，做成了一个公共组件，因为每个页面都会用，所以想要全局引入。
在app.tsx设置usingComponents，一直报错Component is not found in path "component/loadingcom"

代码如下：
usingComponents:{
      "loadingcom":"../../component/loadingcom"
    }
下面两种都试过了，都不行
 "loadingcom":"/component/loadingcom"
 "loadingcom":"component/loadingcom"
请教正确的写法是什么？

注：不是小程序原生组件，就是Taro的写法，写了一个显示和隐藏loading图片的组件，在src下面的component文件夹下，和pages文件夹是同级

**Comment by candyAndBella** [comment]
已解决。得到了回复，Taro不支持全局引用。
我把loadingcom改成了原生小程序的自定义组件，发现一个问题，一定要在某个页面单独引用一次，全局引用才可以生效。否则会不编译，提示Component is not found in path "component/loadingcom/index"

**Comment by ctq123** [comment]
居然不支持全局挂载组件

**Comment by RogerWenXin** [comment]
这个很好理解啊，小程序app层面只有逻辑，没有view，taro对每个page是分别渲染的，他们本质上没有共同的父组件
