### ISSUE TITLE
const fs = require('fs');一直报Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by lzp979822781** [NervJS/taro#5794]
### 问题描述

taro工程中使用require('fs'),运行npm run dev:h5启动时编译报错Module not found: Can't resolve 'fs',确认本地node环境没有问题，单独通过node运行不报错

### 复现步骤
工程地址：http://git.jd.com/yjc-fe/template-app-ts.git
运行命令 npm run dev:h5
启动直接会报错且有具体提示信心，去掉require('fs')引入则正常启动
报错文件地址在src/models/index.ts中
下载工程的话，联系我添加权限
咚咚：liuzhipeng26

### 期望行为

工程正常启动

### 报错信息

Module not found: Can't resolve 'fs' in 'template-app-ts/.temp/models'

### 系统信息
Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/node_global/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 2.0.3 => 2.0.3 
      @tarojs/components-qa: 2.0.3 => 2.0.3 
      @tarojs/components-rn: 2.0.3 => 2.0.3 
      @tarojs/mini-runner: 2.0.3 => 2.0.3 
      @tarojs/redux: 2.0.3 => 2.0.3 
      @tarojs/redux-h5: 2.0.3 => 2.0.3 
      @tarojs/router: 2.0.3 => 2.0.3 
      @tarojs/taro: 2.0.3 => 2.0.3 
      @tarojs/taro-alipay: 2.0.3 => 2.0.3 
      @tarojs/taro-h5: 2.0.3 => 2.0.3 
      @tarojs/taro-qq: 2.0.3 => 2.0.3 
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3 
      @tarojs/taro-redux-rn: ^2.0.3 => 2.0.7 
      @tarojs/taro-rn: 2.0.3 => 2.0.3 
      @tarojs/taro-router-rn: 2.0.3 => 2.0.3 
      @tarojs/taro-swan: 2.0.3 => 2.0.3 
      @tarojs/taro-tt: 2.0.3 => 2.0.3 
      @tarojs/taro-weapp: 2.0.3 => 2.0.3 
      @tarojs/webpack-runner: 2.0.3 => 2.0.3 
      eslint-config-taro: 2.0.3 => 2.0.3 
      eslint-plugin-taro: 2.0.3 => 2.0.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      react: 16.8.0 => 16.8.0 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.0.3 => 2.0.3 
      stylelint-taro-rn: 2.0.3 => 2.0.3 
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
无法通过提交用例复现该问题

> fs 模块是不可以在 web 端引用的，找不到属于正常反馈

**Comment by VivenZZ** [comment]
@ZakaryCode node模块都不能在h5页面中使用的嘛？
