### ISSUE TITLE
taro安装taro-ui时报错日志文件如下

### ISSUE THREAD

**Issue by CQCcq** [NervJS/taro#5798]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Users\11691\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli 'taro-ui' ]
2 info using npm@6.10.3
3 info using node@v10.17.0
4 verbose npm-session f4c23365911db624
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/taro-ui 316ms (from cache)
8 silly pacote tag manifest for taro-ui@latest fetched in 327ms
9 timing stage:loadCurrentTree Completed in 4643ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 53ms
13 silly install loadShrinkwrap
14 verbose stack RangeError: Maximum call stack size exceeded
14 verbose stack at RegExp.test (<anonymous>)
14 verbose stack at schemas.forEach.schema (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:39:16)
14 verbose stack at Array.forEach (<anonymous>)
14 verbose stack at validate (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:34:11)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:37:3)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
14 verbose stack at flatNameFromTree (C:\Users\11691\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
15 verbose cwd D:\app-minsui-react\myApp
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Users\11691\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "taro-ui"
18 verbose node v10.17.0
19 verbose npm v6.10.3
20 error Maximum call stack size exceeded
21 verbose exit [ 1, true ]

**Comment by ZakaryCode** [comment]
信息过于模糊，无法复现该问题
