### ISSUE TITLE
原生组件，h5页面表现与小程序不相同

### ISSUE THREAD

**Issue by jimczj** [NervJS/taro#58]
taro 版本：**0.0.40**
**无另外添加样式，直接使用原生组件**
**代码截图如下：**
![image](https://user-images.githubusercontent.com/13499146/41211163-2891fdba-6d68-11e8-9307-cfcd90a78c2e.png)
**小程序截图如下：**
![image](https://user-images.githubusercontent.com/13499146/41211192-4db740dc-6d68-11e8-9e08-3096cda005e2.png)

**h5截图如下：**
![image](https://user-images.githubusercontent.com/13499146/41211206-58c8b3de-6d68-11e8-8bb8-3d330c5b4d82.png)

**Comment by luckyadam** [comment]
更新下 `@tarojs/components` 到 `0.0.45` 试试~
