### ISSUE TITLE
请问支持小程序分包、第三方插件和npm方式插件吗？

### ISSUE THREAD

**Issue by ldwonday** [NervJS/taro#580]
最新想用taro，但是不知道框架有没有实现上面的功能，还望赐教！谢谢！

**Comment by luckyadam** [comment]
小程序分包正在开发
第三方插件和 npm 都支持

**Comment by luckyadam** [comment]
分包支持已提交，下个版本发布
9bb3e986708a4e5cb23553be96da1492f2f386e6

**Comment by luckyadam** [comment]
分包支持版本已发布

**Comment by ldwonday** [comment]
厉害！！！谢谢！

**Comment by jserweb** [comment]
点个赞

**Comment by luckyadam** [comment]
@ldwonday Taro 这边的文档还没好，但是用法是和小程序基本一致的，在 `app.js` 里指定插件信息，然后在需要引用这个插件的页面或者组件的 `config.usingComponents` 里指定插件，然后在 JSX 中使用
