### ISSUE TITLE
FunctionComponent组件types缺少option

### ISSUE THREAD

**Issue by maoliang2271** [NervJS/taro#5805]
### 问题描述

为了解决全局样式类的问题，class组件有option属性可以设置addGlobalClass: true，FunctionComponent并没有。

### 复现步骤

```js
interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactElement | null;
        propTypes?: WeakValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
}
```

### 期望行为

FunctionComponent也可以添加option属性，解决全局样式问题。

### 系统信息

![image](https://user-images.githubusercontent.com/11402207/77621640-cd0a0a00-6f77-11ea-93ad-d65779343762.png)

### 补充信息

微信小程序的styleIsolation特性希望也早日加入，谢谢

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
可以升级看看，FunctionComponent 中已经存在 options 的定义。

> 2.x 版本中已经存在 styleIsolation 定义，将在近期一并发布
