### ISSUE TITLE
3.0.0-beta.0 新建项目 h5 的 hot-reload 无法更新

### ISSUE THREAD

**Issue by catalsdevelop** [NervJS/taro#5814]
### 问题描述

3.0.0-beta.0 新建项目, react+js+sass, yarn dev:h5可以实时编译，但是hot-reload无法刷新，看 devtool websocket 收到了更新的消息，不过 ui 上没有变化

### 复现步骤

就是用3.0.0-beta cli 创建一个 react+js+sass(css) 项目，运行`yarn dev:h5`即可复现

**Comment by yuche** [comment]
看了一下，目前 h5 的机制会和 react-hot-reload/babel 冲突，所以暂时不开启 hot-reload 了。

等以后 React Fast Refresh 支持了 webpack 再打开吧。

**Comment by veluxa** [comment]
> 看了一下，目前 h5 的机制会和 react-hot-reload/babel 冲突，所以暂时不开启 hot-reload 了。
> 
> 等以后 React Fast Refresh 支持了 webpack 再打开吧。

麻烦看一下最新版PC微信2.9 打开 使用Taro Next 编译的小程序完全没得显示，使用原生写没这个问题 [#5820](https://github.com/NervJS/taro/issues/5820)

**Comment by Chen-jj** [comment]
#7291

3.1 开始支持 React Fast Refresh
