### ISSUE TITLE
react触发事件  [Violation] 'setTimeout' handler took <N>ms

### ISSUE THREAD

**Issue by puckrun** [NervJS/taro#5817]
### 问题描述
react触发事件  [Violation] 'setTimeout' handler took <N>ms

### 复现步骤

1. <打开页面>
![image](https://user-images.githubusercontent.com/23226714/77644520-12d8c980-6f9c-11ea-9006-09c07355f4b5.png)
2. <点击左侧导航栏>
![image](https://user-images.githubusercontent.com/23226714/77644647-47e51c00-6f9c-11ea-850d-8155f1990ecf.png)

3. 
4. 

```tsx
  selectMenu = (index, item) => {
    debugger
    const { menu } = this.props;
    if (!menu) return;
    menu.forEach(element => {
      if (item === element.categoryId) {
        this.setState({ current: index, productList: element.dishes });
      }
    });
  };

 <CategoryList border='circle' direction='vertical' categoryList={categoryList} current={current} onClick={this.selectMenu.bind(this)}></CategoryList>
```

### 期望行为

希望解决事件的卡顿问题
### 报错信息

![image](https://user-images.githubusercontent.com/23226714/77644870-bb872900-6f9c-11ea-98b1-8370bbf57145.png)

### 系统信息

�👽 Taro v2.0.7

  Taro CLI 2.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by liujianglc** [comment]
希望解决卡顿问题,  我这里也会有

**Comment by thorlove** [comment]
希望解决卡顿问题我这里也有
