### ISSUE TITLE
[BUG] Taro Next 构建的小程序在 微信PC2.9 上页面完全无显示

### ISSUE THREAD

**Issue by veluxa** [NervJS/taro#5820]
使用Taro Next 构建的小程序 ：

【手机】页面是正常显示的
【PC】   在最新版的 [微信PC2.9](https://dldir1.qq.com/weixin/Windows/Beta/WeChat2.9.0_Beta.exe) 上打开小程序页面内容无法显示

使用原生写无此问题

**Comment by yuche** [comment]
你这个范围太大了，应该自行排查是哪个组件用了哪个特性导致在 PC 端无法使用

**Comment by veluxa** [comment]
> 你这个范围太大了，应该自行排查是哪个组件用了哪个特性导致在 PC 端无法使用

1个页面，且只使用了一个 View 组件，
```
import React, { Component } from 'react';
import Taro from '@tarojs/taro';
import { View } from '@tarojs/components';
import './index.scss';

const Home = () => {
      <View>
            内容
      </View>
    )
}

export default Home
```
调试工具里头看页面WXML只有个<page></page>标签（PC端微信），开发工具及手机端是正常显示的

**Comment by yuche** [comment]
> import { View } from '@tarojs/components';

搞个 vconsole 看看有没有报错

**Comment by veluxa** [comment]
> > import { View } from '@tarojs/components';
> 
> 搞个 vconsole 看看有没有报错

没有任何报错的，和手机端vconsole输出是一样的
