### ISSUE TITLE
原生混写模版中import的依赖没有全部编译输出

### ISSUE THREAD

**Issue by eriklynd** [NervJS/taro#5824]
### 问题描述

Taro 代码与小程序代码混写时，模版xml有多个一级节点时，模版中的依赖没有正确编译输出。

### 复现步骤

1. 使用小程序原生模版语法，模版最开始写多个`<import src="..." />`
2. build
3. 结果只有第一个import的依赖被输出，其余依赖没有输出

示例问题模版，仅有a.swan会被输出：

```xml
<import src="./a.swan" />
<import src="./b.swan" />
<import src="./c.swan" />
<import src="./d.swan" />

<view>
  <text>123</text>
</view>
```

### 期望行为

import的依赖都被编译输出

### 报错信息

无报错信息，编译产物缺失

### 系统信息

 Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/mini-runner: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-rn: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.7 => 2.0.7 
      stylelint-taro-rn: 2.0.7 => 2.0.7 

### 补充信息

https://github.com/NervJS/taro/blob/b4bb27cc5fc5bda53a0ba53379e9e6078eef942f/packages/taro-mini-runner/src/loaders/miniTemplateLoader.ts#L22 依赖的`sax`模块`onattribute`只被触发了一次。原因是`sax`仅会解析第一个一级节点，可能是`sax`的bug。

需要替换`sax`模块，或者将`source`整体包装在一个根节点中：

https://github.com/NervJS/taro/blob/b4bb27cc5fc5bda53a0ba53379e9e6078eef942f/packages/taro-mini-runner/src/loaders/miniTemplateLoader.ts#L41

```js
parser.write(source).close()
```

改为

```js
parser.write(`<fakeroot>${source}</fakeroot>`).close()
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by wingsico** [comment]
这么久了都不解决一下吗。。
