### ISSUE TITLE
关于alias配置引用项目外部非npm的lib引起小程序报错的问题

### ISSUE THREAD

**Issue by Roman-Lo** [NervJS/taro#5825]
### 问题描述

当前项目使用[nrwl](https://nx.dev/)的monorepo workspace。其中，workspace根目录下的`apps`文件夹作为存放application的地方，`libs`文件夹作为存在公用库的地方。

在上述基础上，我尝试用alias配置小程序项目外的非npm库引用的时候报错了。

### 复现步骤

1. 小程序项目放在了apps下的`mini-app`文件夹下
2. 在`libs`下创建一个项目`common` （为了复用api的数据结构，以及一些通用的utilities方法），common目录按照nrwl对于library的结构为`src/lib/<module>`, 因此我在`libs/common/src/lib/string`下加入了一个`string.util.ts`的文件:
```js
export class StringUtil {
    static test(): string {
     return 'it works';
   }
}
```
并且在该目录下创建一个`index.ts`：
```js
export * from './string.util';
```
3. 在`apps/mini-app/config/index.js`中加入alias配置：
```js
"alias": {
"@my-common": path.resolve(__dirname, '../../../libs/common/src/lib'),
}
```
4. 在小程序项目里引用：
```js
import { StringUtil  } from '@my-common/string'

console.log(StringUtil.test());
```
5. 在根目录的`package.json`加入taro编辑指令：

```json
{
    "dev:weapp": "npm run build:weapp -- --watch",
    "build:weapp": "cd apps/mini-app && taro build --type weapp"
}
```
6. 编译成功，但是在微信开发者工具中显示：Uncaught Error: can't find module : ../../../../libs/common/src/lib/string/index.js

### 期望行为

期待可以通过alias或者别的单独配置，使得小程序可以引用monorepo中其它library的功能。

### 报错信息

![image](https://user-images.githubusercontent.com/5829553/77754101-9f02f380-7065-11ea-8b28-0e7f988b965b.png)

`Uncaught Error: can't find module : ../../../../libs/common/src/lib/string/index.js`

### 系统信息

  Taro CLI 1.3.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

### 补充信息

taro cli估计在设计的时候应该没有考虑monorepo的情况，导致缺乏对非npm的外部库引用的功能。
在应用alias配置的时候，是选择了直接的相对路径替换，没有判定路径是否超出引用范围。 

这种引用方式在monorepo的结构里面会比较常见，我还没有很仔细地看完taro cli的配置以及源代码，也不知道通过copy加plugin的方式能不能解决这个问题。

如果有同行解决过类似的问题，希望能分享一下咨询哈~

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by hanfengcan** [comment]
![image](https://user-images.githubusercontent.com/4559753/93765875-282b6980-fc48-11ea-96f5-997386d5d9dd.png)
我也遇到类似的问题, 手工引入vant, 配置别名无效
