### ISSUE TITLE
[AtFab]百度小程序中不显示图标

### ISSUE THREAD

**Issue by hao-li** [NervJS/taro#5828]
**问题描述**
AtFab 在百度小程序中不显示图标

**复现步骤**
1. git clone git@github.com:hao-li/taro-problem-sample.git
`git clone https://github.com/hao-li/taro-problem-sample.git`
2. yarn
3. yarn build:swan
4. 使用百度开发者工具（v3.1.2）打开 dist/swan
5. 使用百度开发者工具模拟器查看小程序
6. 点击『点击进入百度小程序问题页』按钮

**期望行为**
蓝色 AtFab 中间显示白色 home 图标

![image](https://user-images.githubusercontent.com/11334645/77223195-45965280-6b95-11ea-8d5d-0256433515a7.png)

**报错信息**
只显示背景色，没有中间的图标

![image](https://user-images.githubusercontent.com/11334645/77223199-534bd800-6b95-11ea-8ae7-738e684b1f18.png)

**系统信息**
```
👽 Taro v1.3.39


  Taro CLI 1.3.39 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.39 => 1.3.39
      @tarojs/plugin-babel: 1.3.39 => 1.3.39
      @tarojs/plugin-csso: 1.3.39 => 1.3.39
      @tarojs/plugin-sass: 1.3.39 => 1.3.39
      @tarojs/plugin-uglifyjs: 1.3.39 => 1.3.39
      @tarojs/router: 1.3.39 => 1.3.39
      @tarojs/taro: 1.3.39 => 1.3.39
      @tarojs/taro-alipay: 1.3.39 => 1.3.39
      @tarojs/taro-h5: 1.3.39 => 1.3.39
      @tarojs/taro-swan: 1.3.39 => 1.3.39
      @tarojs/taro-tt: 1.3.39 => 1.3.39
      @tarojs/taro-weapp: 1.3.39 => 1.3.39
      @tarojs/webpack-runner: 1.3.39 => 1.3.39
      eslint-config-taro: 1.3.39 => 1.3.39
      eslint-plugin-taro: 1.3.39 => 1.3.39
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 1.3.39 => 1.3.39
      stylelint-taro-rn: 1.3.39 => 1.3.39
```

taro-ui: 2.3.1

**补充信息**
目前在微信小程序中正常
以前在百度小程序中也是正常的，可能是百度小程序改版后不兼容了

**Comment by Garfield550** [comment]
@luckyadam 老李可以有时间看一下什么问题吗？

**Comment by hao-li** [comment]
@luckyadam 我升到 taro 2.1.0 发现有些 row col 布局也存在这个问题，感觉是个普遍性的问题，不知道有没有百度那边的渠道沟通下看怎么能解决一下这问题？

百度小程序发不了版本了已经2周了，已经超过给我发的整改通知期限，现在给我们小程序限流了。。

**Comment by hao-li** [comment]
目前感觉百度那边问题的可能性大，把受影响的部分移除了，以后有需要时根据当时的开发者工具再看吧

**Comment by Kavinjsir** [comment]
我猜可能不是百度的问题，因为我在做微信小程序的时候也遇到了相同的情况，在`Wechat Devtools`上无法显示图标，手机上，按钮也没有了。
