### ISSUE TITLE
Taro中支持自定义组件插多个slot吗？

### ISSUE THREAD

**Issue by xioozq** [NervJS/taro#583]
**问题描述**
原生小程序支持多个命名的slot， react常规的方式是使用prop传递渲染函数或者JSX元素，
那么Taro在这方面是有什么推荐的方案吗？

**期望行为**
比如需要一个 Panel 组件， 除了必须的 content部分由外层传递以外，还可能会有一个可选的 自定义footer部分,现有的this.props.children就不够用了

**Comment by yuche** [comment]
现在还不支持，正在考虑怎么实现。

**Comment by liu-60** [comment]
@xioozq  现在有用什么间接方案吗？想借鉴下

**Comment by xioozq** [comment]
@liu-60 
也没什么好办法， 要么多搞些属性，配置复杂一点， 来避免直接传元素的情况； 
或者把次要slot放在外层用绝对定位让他 “看起来像” 在父组件内部； 
或者你可以试一下用小程序原生代码混写在Taro项目里，issues区里好像有demo

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/5efd2a72eb5b1dc4abfa03beed0c5d80e2a8a411
