### ISSUE TITLE
Taro 在typescript环境下 Canvas 下划线

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [NervJS/taro#5831]
![20200328144849.png](https://user-gold-cdn.xitu.io/2020/3/28/1711fe94ca8e197f?w=864&h=607&f=png&s=30583)，问一下是什么原因，文档有点不清楚，是不是在ts下必填什么属性

taro 版本 2.0.7

**Comment by ZakaryCode** [comment]
你 style 写错了
