### ISSUE TITLE
Taro v3.0.0-beta.1,app.tsx 内componentDidMount中取不到Current.router的值

### ISSUE THREAD

**Issue by cyq333** [NervJS/taro#5833]
### 问题描述
app.tsx 内componentDidMount中取不到Current.router的值

### 复现步骤

app.tsx
componentDidMount() {
//此处Current.router为null
    console.log(Current.router)
}

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by charmtiger** [comment]
我遇到同样的问题，现在是使用 componentDidShow

**Comment by yuche** [comment]
这是预期的行为，当组件加载时，路由并没有产生变化，只有 componentDidShow 和 DidHide 触发时，路由才产生变化。

这一点会在文档里解释清楚。

**Comment by charmtiger** [comment]
@yuche 那需要说明，didShow 会在下次 onFocus 的时候重复执行，如果有只执行一次的操作，需要自行判断加以限制

**Comment by charmtiger** [comment]
确认一下，页面内 componentDidMount 确保是可以拿到 Current.router 是吧？

**Comment by yuche** [comment]
只有 componentDidShow 才能确保拿到 Current.router，Current.router 就是 小程序生命周期 onShow，onShow 调用就会调起它。

**Comment by charmtiger** [comment]
所有的页面都要额外判断，以防止多次初始化页面。我认为这样有些繁琐，如果能和 react +  react router 保持一致就好了

**Comment by charmtiger** [comment]
react router ， react native ，taro2 都是在 componentDidMount 中接收 路由参数，如果都改用 DidShow，相信大多数用户都有疑惑。

**Comment by cyq333** [comment]
如果是之前在小程序onLaunch中只需要执行一次的操作，需要使用到router,放在 componentDidShow里不太好吧，之前taro2.0在componentDidMount里是可以通过this.$router拿到路由参数的

**Comment by yuche** [comment]
下个版本可以用 hooks 传入 deps 防止生命周期重复调用。taro 2 可以拿到 this.$routers 代价是两次调用构造器和 render 和预编译。

**Comment by charmtiger** [comment]
我们已经增加了 componentDidShow，是否可以增加 componentDidLoad 实现需求，还有我们现在还是用 class component 多一点，仅仅提供 hooks 也不行的

**Comment by yuche** [comment]
现在就有，他的生命周期就叫 onLoad

**Comment by charmtiger** [comment]
刚刚试过在页面中 onLoad 和 componentDidMount 都可以拿到 Current.router，在 app.tsx 中 onLaunch 和 onLoad 都没有执行。

**Comment by yuche** [comment]
https://developers.weixin.qq.com/miniprogram/dev/reference/api/App.html
app 没有 onLoad 这个生命周期，onLaunch 约等于 app 的 componentDidMount，taro 目前是在 onLaunch 调用 React 的 render

**Comment by charmtiger** [comment]
总结一下：
1、app.tsx 使用 componentDidShow 获取 Current.router，需要自行限制onFocus时多次执行。
2、页面中 class 组件 使用 onLoad 代替 componentDidMount 获取 Current.router。
3、页面中 函数组件 等下个版本可以用 hooks 传入 deps 防止生命周期重复调用。

**Comment by TechQuery** [comment]
@yuche `componentDidShow()` 在 TypeScript 定义文件中没有，而且我觉得 `componentDidUpdate()` 也应该能拿到 `Current.router.path` 才对
