### ISSUE TITLE
组件render函数内实现箭头函数renderX编译后找不到，实现为成员函数又报错导致组件编译失败

### ISSUE THREAD

**Issue by alvinwsz** [NervJS/taro#5834]
### 问题描述
1.3.15版本，封装Component实现组件基类ComBase(base.ts)，继承实现组件ComUser，在ComUser的render()函数中实现几个局部箭头函数renderA/renderB/renderC/renderX，但是编译后运行报错，提示renderX未定义，查看生成的js文件，确实找不到其定义，而其它几个箭头函数则正常，没办法就将renderX提出来实现为组件的成员函数，则运行正常，但是会报警告无法找到“base.wxml”
升级到2.0.7版本后，直接就报如下错误：
Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/miniTemplateLoader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './@/components/base.wxml'
经验证，关于renderX存在跟1.3.15一样的问题，唯一不同是1.3.15的warning在2.0.7变为error，直接导致组件编译失败
（升级到2.0.7做过两种尝试，上述问题都一样：首先是遵循升级指南，然后新建项目直接拷贝源码）

然后，将ComUser组件的基类改为Component，将原基类ComBase中的源码实现完全拷贝过来重新实现一次，则上述问题消失

### 复现步骤

以下是我代码的示意，但是经验证也没复现上述问题，还是贴上来吧，期望能得到建议

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
/* base.ts */
export ComBase extends Component {
  func1(){
  }
}

/* user.tsx */
class ComDemo extends ComBase<ComponentProps,ComponentState> {
  render() {
    const { className, title } = this.props
    const renderX = (s)=><View>D: {s}</View>
    const renderA = (s)=><View> A: {s} {renderX('fromA')} </View>
    const renderB = (s)=><View> B: {s} {renderX('fromB')} </View>
    const renderC = (s)=><View> C: {s} </View>
    return (
      <View className={classNames('demo', className)}>
        { renderA('hello') }
        { renderB('world') }
        { renderC('hello') }
        { renderX('world') }
      </View>
    )
  }
}
```

### 期望行为

对render内的renderX箭头函数能正常编译

### 报错信息

Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/miniTemplateLoader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './@/components/base.wxml'

### 系统信息

  Taro CLI 2.0.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 2.0.7 => 2.0.7
      @tarojs/components-qa: 2.0.7 => 2.0.7
      @tarojs/mini-runner: 2.0.7 => 2.0.7
      @tarojs/redux: 2.0.7 => 2.0.7
      @tarojs/redux-h5: 2.0.7 => 2.0.7
      @tarojs/router: 2.0.7 => 2.0.7
      @tarojs/taro: 2.0.7 => 2.0.7
      @tarojs/taro-alipay: 2.0.7 => 2.0.7
      @tarojs/taro-h5: 2.0.7 => 2.0.7
      @tarojs/taro-qq: 2.0.7 => 2.0.7
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7
      @tarojs/taro-rn: 2.0.7 => 2.0.7
      @tarojs/taro-swan: 2.0.7 => 2.0.7
      @tarojs/taro-tt: 2.0.7 => 2.0.7
      @tarojs/taro-weapp: 2.0.7 => 2.0.7
      @tarojs/webpack-runner: 2.0.7 => 2.0.7
      eslint-config-taro: 2.0.7 => 2.0.7
      eslint-plugin-taro: 2.0.7 => 2.0.7
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.7 => 2.0.7
      stylelint-taro-rn: 2.0.7 => 2.0.7

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by alvinwsz** [comment]
找到问题出在哪里了，如下renderA/renderX的写法编译都成功，但是js里找不到renderX，所以运行时报错
```js
render(){

  const list = ['a', 'b', 'c']
  const renderA = (arr)=><View>{
      arr.map((v,index)=><View key={'renderA'+index}>{index}-{v}</View>)
      }</View>
  const renderX = (arr)=>arr.map((v,index)=><View key={'renderX'+index}>{index}-{v}</View>)
  return  (
    <View>
      { renderA(list) }
      { renderX(list) }
  </View>
  )
}
```

**Comment by zhiqingchen** [comment]
```  
renderA (arr) {
    return <View>{
      arr.map((v,index)=><View key={'renderA'+index}>{index}-{v}</View>)
    }</View>
  }
  renderX (arr) {
    return arr.map((v,index)=><View key={'renderX'+index}>{index}-{v}</View>)
  }

  render(){
    const list = ['a', 'b', 'c']
    return  (
      <View>
        { this.renderA(list) }
        { this.renderX(list) }
      </View>
    )
  }
```

闭包函数式组件编译有问题，先用类函数式组件代替

**Comment by alvinwsz** [comment]
就是因为闭包函数组件编译问题，改成类函数式组件在2.0.7版本报上述错误，所以没办法才提的issue，不过既然闭包函数套上View能解决的话，我就不纠结了，只要能work就行

**Comment by zhiqingchen** [comment]
你可以这么写

```javascript
  render () {
    const list = ['a', 'b', 'c']
    const renderA = (arr)=><View>{
        arr.map((v,index)=><View key={'renderA'+index}>{index}-{v}</View>)
    }</View>
    const renderO = (v,index)=><View key={'renderX'+index}>{index}-{v}</View>
    return  (
      <View>
        { renderA(list) }
        { list.map((v,index) => renderO(v,index)) }
    </View>
    )
  }
```

**Comment by alvinwsz** [comment]
好的，谢了
