### ISSUE TITLE
[Taro3 beta1] useShareAppMessage callback 函数初次设置后无法更新.

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#5837]
### 问题描述

useShareAppMessage 有时候需要等待异步 API 返回的数据才能决定分享标题和链接, 这个 hook 现在没有第二个 deps 参数, 而 hook 又是不能条件跳过的.

### 复现步骤

```js
    const { data } = useAsync(...)

    useShareAppMessage(e => {
        return {
            title: data.title || '默认标题',
            path: `/pages/group/join?id=${data.id}`,
        }
    })
```

### 期望行为

分享返回值无法动态更新.

### 系统信息

taro 3.0.0-beta.1

### 补充信息

重写了一个临时的 hook 供项目使用, 不管3721强制覆盖.

```tsx
export const useShareAppMessage = (callback: (e: Taro.ShareAppMessageObject) => Taro.ShareAppMessageReturn) => {
    if (!Taro.Current.page) return

    Taro.Current.page.onShareAppMessage = callback
}
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by liu-jin-yi** [comment]
@Chen-jj  hello 这个问题请问有结论了吗？或者有什么替代方案吗？
