### ISSUE TITLE
升级next后标签不再是div，如何设置编译出div

### ISSUE THREAD

**Issue by 521707** [NervJS/taro#5842]
### 复现步骤

![image](https://user-images.githubusercontent.com/37111718/77872127-a8b07500-7278-11ea-8b92-5c7461806f59.png)

1、升级next 之后， 编译成H5，标签不再是div，而外面会嵌套一层taro-xxx-xxx，
老是包裹一层新的标签， 把我之前写的默认样式全覆盖了，整个项目样式错乱
2、由于编译出来之后会嵌套一个标签，无法通过标签名进行覆盖原有样式，优先级原因，
只能给每一个标签都添加一个类名进行覆盖原有标签的样式，很繁琐，编译出来的样式优先级太高了
### 期望行为

如何在让h5编译不在外层嵌套。

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@521707 next 使用了 stencil 做跨框架组件，标准组件是一个个 web component。

使用类名设置样式更加规范，当然也还是可以使用 web component 的标签名做选择器。

如果标签名或类名做选择器覆盖不了默认样式，可以另外给我们提一下 issue。web component 多套了一层，的确有些情况我们会没考虑到。

**Comment by aniu2016** [comment]
在android手机上遇到了一个问题

手机品牌：vivo
型号: vivo x30
android 版本 : 9
vivo ROM: FuntouchOS_10
浏览器ua： Mozila/5.0 （Linux；Android 9；V1938CT Build/PPR1.180610.011; wv） AppleWebKit/537.36 (KHTML，like Gecko)Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/8.2.16.1

问题描述:

在此系统自带的浏览器上, 随机无规律(暂时没找到规律) 部分element显示, 部分element不显示,  刷新后出现的问题也是一致, 在其他手机上(如iphone 6s ios13.3  iphone XSmax 13.6 小米...)无问题

经排查可能是与 stencil 中使其组件显示的css有关, classname hydrated , 该 class 将 visibility: hidden; 变更为 inherit  时, 没有触发浏览器重绘, (现代码中的临时方案是针对此类机型在 页面组件 componentDidShow中  对 body display 样式 手动设置为 none; 在设置个定时器 变更为block去hack), 

故想询问有没有好的解决方式, 或者能编译成原生标签 @Chen-jj

**Comment by foyel** [comment]
@Chen-jj  我们也遇到这种问题了

**Comment by yohnz** [comment]
+1 遇到同样的问题，vivo，oppo手机上，整个界面渲染异常，只显示背景色，手动操作某些会引起重绘的操作后，渲染恢复正常。

**Comment by lujijiang** [comment]
这个问题太严重了，taro3都不做兼容性测试的么？

**Comment by shenghanqin** [comment]
@Chen-jj 请Taro官方给出比较完整的h5的兼容性和样式等测试报告吧。不能说使用了新的底层，就将完全新的模式逼着用户去适应。h5，安卓上的兼容性更难测试的。这个h5的问题，我从Taro bata版本就一直在跟着，还是有这么人在反馈。 @luckyadam

**Comment by NO-MAP** [comment]
兄弟，这个问题现在有什么解决办法没有。

**Comment by NO-MAP** [comment]
> @Chen-jj 请Taro官方给出比较完整的h5的兼容性和样式等测试报告吧。不能说使用了新的底层，就将完全新的模式逼着用户去适应。h5，安卓上的兼容性更难测试的。这个h5的问题，我从Taro bata版本就一直在跟着，还是有这么人在反馈。 @luckyadam

你好，目前这个问题有什么通用解决办法么？

**Comment by bluceqiu** [comment]
+1。急！！！ 我这个是覆盖都覆盖不了，因为是包了一个空 div 我没法覆盖，导致高度一致不对，整个界面样式都不对了

**Comment by Chen-jj** [comment]
如果需求的兼容性要求较高，可以使用 React 编写的组件库（Vue 还没实现），最新版本已支持。

它实现了部分组件（主要是我们内部业务使用到的，更多组件需要手动把 Stencil 语法转React，然后 PR 过来）。

https://github.com/NervJS/taro/blob/next/packages/taro-components-react/README.md

**Comment by shenghanqin** [comment]
> 如果需求的兼容性要求较高，可以使用 React 编写的组件库（Vue 还没实现），最新版本已支持。
> 
> 它实现了部分组件（主要是我们内部业务使用到的，更多组件需要手动把 Stencil 语法转React，然后 PR 过来）。
> 
> https://github.com/NervJS/taro/blob/next/packages/taro-components-react/README.md

希望尽快给出完整的H5兼容组件吧，是在是不想用Stencil来弄Canvas的定位啦。感谢。
