### ISSUE TITLE
2.0.6 props render 效果不理想

### ISSUE THREAD

**Issue by ibubbo** [NervJS/taro#5847]
### 问题描述

假设

在 B 组件内定义一个 `props.children`，方便后续扩展视图

![image](https://user-images.githubusercontent.com/32586819/77886954-54b78780-729c-11ea-8bb7-416cc890c4dd.png)

创建一个 A 组件，A 组件接收一个 props 为 `renderBook` 函数，并且作为 B 组件的 `children`

![image](https://user-images.githubusercontent.com/32586819/77887007-66992a80-729c-11ea-8069-3c549b513459.png)

然后在业务中使用：

![image](https://user-images.githubusercontent.com/32586819/77887019-6e58cf00-729c-11ea-8815-05eea8137114.png)

发现有时候能出现，有时候不能出现。。

![image](https://user-images.githubusercontent.com/32586819/77887086-8b8d9d80-729c-11ea-9054-aacb39235407.png)

![image](https://user-images.githubusercontent.com/32586819/77887100-921c1500-729c-11ea-9e53-3a49d1afeb93.png)

另外，如果直接在元素上使用 `style` 标签，将无效：

![image](https://user-images.githubusercontent.com/32586819/77887210-c5f73a80-729c-11ea-9776-659aec6d66f2.png)

![image](https://user-images.githubusercontent.com/32586819/77887217-c98ac180-729c-11ea-85fa-9a649d76a073.png)

### 复现步骤

同问题描述，步骤已描述清楚

### 期望行为

1. 每次编译的结果应该是保持一致的，同一代码不应出现两种现象
2. `style` 应该被正常解析

### 报错信息

无报错

### 系统信息

� Taro v2.0.6

  Taro CLI 2.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by jiasaichao** [comment]
这个问题有解吗？style 无法生效
