### ISSUE TITLE
跨端组件找不到

### ISSUE THREAD

**Issue by xiajie0** [NervJS/taro#5849]
### 问题描述

升级到Taro2.1.0之后，页面中引用到的跨端组件出现找不到组件的问题
![image](https://user-images.githubusercontent.com/28720000/77905044-2ba4f000-72b8-11ea-8686-000508bf6c86.png)

### 复现步骤

1. 升级到Taro2.1.0
2. 创建跨端组件index.weapp.tsx
3. 编译运行项目
4. 进入页面报错
![image](https://user-images.githubusercontent.com/28720000/77905044-2ba4f000-72b8-11ea-8686-000508bf6c86.png)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
2.0.7 可以么

**Comment by xiajie0** [comment]
嗯  2.0.7是可以的  暂时退到2.0.7了
