### ISSUE TITLE
Typescript版本缺乏对微信小程序配置项navigationStyle的支持

### ISSUE THREAD

**Issue by mclockw** [NervJS/taro#585]
**问题描述**
Typescript版本缺乏对微信小程序配置项navigationStyle的支持。

**复现步骤**
创建任意配置tsx文件，增加navigationStyle配置项。

```typescript
export default class NewItem extends Component<{}, {}> {
    config: Config = {
        navigationStyle:'custom'
      }
    render(){
        return(
            <View>
                Create New Item.
            </View>
        )
    }
}

```

**期望行为**
可以使用navigationStyle配置项，不会报编译错误。

**报错信息**
编译错误：
[ts]
Type '{ navigationStyle: string; }' is not assignable to type 'Config'.
  Object literal may only specify known properties, and 'navigationStyle' does not exist in type 'Config'.
(property) navigationStyle: string

**系统信息**

 - 操作系统: mac
 - Taro 版本: Taro v1.0.0-beta.22
 - Node.js 版本: 任意

**补充信息**
需要在index.d.ts文件 interface PageConfig 中加入    navigationStyle?: string，例如：

interface PageConfig {
...
    navigationStyle?: string,
...
}

**Comment by yuche** [comment]
提一个 PR 咯，兄弟

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/590
