### ISSUE TITLE
微信小程序原生代码转taro失败

### ISSUE THREAD

**Issue by gyfgyf** [NervJS/taro#5852]
微信小程序原生代码转taro 时运行 taro convert 成功，npm i 成功，在微信小程序调试工具打开，显示不了，报错：VM674:1 thirdScriptError
module "app.js" is not defined
Error: module "app.js" is not defined
我在taroConvert 目录里发现我的原生小程序的自定义Conponent  组件没有被编译，导致taro  中还是引入了我原生小程序组件的名字，编辑器提示组件未定义，以及import 语法错;
我目前用的是 Taro v2.0.7

**Comment by Chen-jj** [comment]
最新版本应该没有问题了
