### ISSUE TITLE
h5 browserhistory模式 在nginx 二级目录站点报错

### ISSUE THREAD

**Issue by imlinqin** [NervJS/taro#5855]
### 问题描述

Taro v2.1.0 及以下版本配置 h5.publicPath '/subsite/' 和h5.router.mode='browser' 路由browserhistory 模式后打包项目在nginx 二级目录报错(提示：Can not find proper registered route for '/subsite'), 当设置h5.router.mode='hash' 模式一切正常

### 复现步骤

1. taro h5文件 h5.publicPath '/subsite/' 和h5.router.mode='browser' 并  npm run build:h5
2. 将打包文件放到 nginx 二级目录上
3. 设置 nginx 二级站点配置文件    location /subsite{
    try_files $uri  $uri/  /subsite/index.html;
   
}  并重启nginx服务 
4. 访问二级站点目录url后，页面空白, console 提示   app.js:1 Uncaught Invariant Violation: Can not find proper registered route for '/subsite'
5.当设置h5.router.mode='hash' 模式,访问二级目录url 一切正常

```js
 h5: {
    publicPath: '/subsite',
    staticDirectory: 'static',
    webpackChain (chain, webpack) {},
    postcss: {
      autoprefixer: {
        enable: true,
        config: {
          browsers: [
            'last 3 versions',
            'Android >= 4.1',
            'ios >= 8'
          ]
        }
      }
    },
    router: {
      basename: '/subsite',
      //mode: 'browser',//'hash' // 或者是 'browser'
    },
    router: {
      mode: 'browser' // 或者是 'browser'
    },
  }

```

```
nginx 相关配置

location /subsite {
 try_files $uri  $uri/  /subsite/index.html;
   
}

```

### 期望行为

taro h5 browserhistory模式 在nginx 二级目录站点访问正常

### 报错信息

app.js:1 Uncaught Invariant Violation: Can not find proper registered route for '/subsite'
    at invariant (http://localhost:3301/subsite/js/app.js:1:360037)
    at Router.computeMatch (http://localhost:3301/subsite/js/app.js:1:365801)
    at Router.push (http://localhost:3301/subsite/js/app.js:1:365970)
    at Router.componentDidMount (http://localhost:3301/subsite/js/app.js:1:367036)
    at http://localhost:3301/subsite/js/app.js:1:133831
    at errorCatcher (http://localhost:3301/subsite/js/app.js:1:132580)
    at http://localhost:3301/subsite/js/app.js:1:133805
    at Array.forEach (<anonymous>)
    at flushMount (http://localhost:3301/subsite/js/app.js:1:133746)
    at Object.render (http://localhost:3301/subsite/js/app.js:1:137689)

### 系统信息

👽 Taro v2.1.0

  Taro CLI 2.1.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.1.0 => 2.1.0 
      @tarojs/components: 2.1.0 => 2.1.0 
      @tarojs/components-rn: 2.1.0 => 2.1.0 
      @tarojs/mini-runner: 2.1.0 => 2.1.0 
      @tarojs/mobx: 2.1.0 => 2.1.0 
      @tarojs/mobx-h5: 2.1.0 => 2.1.0 
      @tarojs/mobx-rn: 2.1.0 => 2.1.0 
      @tarojs/plugin-babel: 2.1.0 => 2.1.0 
      @tarojs/plugin-csso: 2.1.0 => 2.1.0 
      @tarojs/plugin-sass: 2.1.0 => 2.1.0 
      @tarojs/plugin-uglifyjs: 2.1.0 => 2.1.0 
      @tarojs/rn-runner: 2.1.0 => 2.1.0 
      @tarojs/router: 2.1.0 => 2.1.0 
      @tarojs/taro: 2.1.0 => 2.1.0 
      @tarojs/taro-alipay: 2.1.0 => 2.1.0 
      @tarojs/taro-h5: 2.1.0 => 2.1.0 
      @tarojs/taro-redux-rn: 2.1.0 => 2.1.0 
      @tarojs/taro-rn: 2.1.0 => 2.1.0 
      @tarojs/taro-router-rn: 2.1.0 => 2.1.0 
      @tarojs/taro-swan: 2.1.0 => 2.1.0 
      @tarojs/taro-tt: 2.1.0 => 2.1.0 
      @tarojs/taro-weapp: 2.1.0 => 2.1.0 
      @tarojs/webpack-runner: 2.1.0 => 2.1.0 
      eslint-config-taro: 2.1.0 => 2.1.0 
      eslint-plugin-taro: 2.1.0 => 2.1.0 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
      stylelint-config-taro-rn: 2.1.0 => 2.1.0 
      stylelint-taro-rn: 2.1.0 => 2.1.0 

### 补充信息
creact react app 框架 browserhistory 在nginx 站点二级 表现正常

**Comment by tuoxie15** [comment]
同求，也遇到相同问题了，求有个解决方案，在线等..急..

**Comment by SilentFlute** [comment]
#4171

**Comment by rockliuxn** [comment]
nginx 配置改成：

``` bash
location /subsite {
   alias 项目路径
   index index.html
   try_files $uri  $uri/ /subsite/index.html;  
}
```

这样就可以了

**Comment by lhkg1988** [comment]
publicPath: '/subsite/'设置成这样呢

**Comment by baxibaba** [comment]
> nginx 配置改成：
> 
> ```shell
> location /subsite {
>    alias 项目路径
>    index index.html
>    try_files $uri  $uri/ /subsite/index.html;  
> }
> ```
> 
> 这样就可以了

这个方法确实可以赞
