### ISSUE TITLE
只把其中一个项目升级到2.0，微信开发者工具，报错VM497:1 thirdScriptError regeneratorRuntime is not defined ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by candyAndBella** [NervJS/taro#5857]
![微信截图_20200331105816](https://user-images.githubusercontent.com/34698384/77982921-1a9fc180-7340-11ea-9039-16a15326e15d.png)
![微信截图_20200331110028](https://user-images.githubusercontent.com/34698384/77982928-22f7fc80-7340-11ea-9297-7abc37a392cb.png)
![微信截图_20200331110126](https://user-images.githubusercontent.com/34698384/77982935-28554700-7340-11ea-9b66-d49b76be44c3.png)
![微信截图_20200331110215](https://user-images.githubusercontent.com/34698384/77982939-2c816480-7340-11ea-8707-c5b67af09fec.png)
![微信截图_20200331110910](https://user-images.githubusercontent.com/34698384/77983004-5cc90300-7340-11ea-9032-dcb8a9a91da5.png)
![微信截图_20200331111048](https://user-images.githubusercontent.com/34698384/77983029-78340e00-7340-11ea-950d-5c16221b5beb.png)

![微信截图_20200331110623](https://user-images.githubusercontent.com/34698384/77982945-3014eb80-7340-11ea-982e-1c75f4ca6de4.png)

**Comment by candyAndBella** [comment]
两天了，从昨天开始捣鼓，按照迁移指南，装了好几遍了，安装包都安装成功了，配置文件也改了，编译也成功了，在微信开发者工具里，就是报错，真的没天理啊。找不出来哪有错了

**Comment by shenghanqin** [comment]
@candyAndBella 你要淡定。升级2.0应该是要安装一个regeneratorRuntime的包，你搜索issue里面有提到。

**Comment by candyAndBella** [comment]
> @candyAndBella 你要淡定。升级2.0应该是要安装一个regeneratorRuntime的包，你搜索issue里面有提到。

装了的

**Comment by Garfield550** [comment]
`regenerator-runtime` 装的是 0.11.1 吗

**Comment by candyAndBella** [comment]
![微信截图_20200331145401](https://user-images.githubusercontent.com/34698384/77996059-80e80c80-735f-11ea-9d89-84031de795ad.png)

**Comment by JohnhanLiu** [comment]
看看你的 `app.tsx` 里面有没有 `@tarojs/async-await`

**Comment by candyAndBella** [comment]
![微信截图_20200331151049](https://user-images.githubusercontent.com/34698384/77997348-d3c2c380-7361-11ea-9527-08f2ba071b67.png)

**Comment by candyAndBella** [comment]
最新研究结果，用yarn dev:weapp 启动编译，微信开发者工具，就可以正常预览。
用taro build --type weapp --watch，启动编译，微信开发者工具就会出现regeneratorRuntime is not defined的错误！还在继续研究中。。。

**Comment by candyAndBella** [comment]
![微信截图_20200331164218](https://user-images.githubusercontent.com/34698384/78005902-d11a9b00-736e-11ea-87de-c28d0287b058.png)
![微信截图_20200331164349](https://user-images.githubusercontent.com/34698384/78005919-d677e580-736e-11ea-82c8-fde7015a8dde.png)

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/78048954-080fa180-73ad-11ea-9376-7727697648a2.png)
![image](https://user-images.githubusercontent.com/1782542/78048973-0f36af80-73ad-11ea-9fda-90d9e3009874.png)
没问题了麻烦关闭

**Comment by plainnany** [comment]
哭了 用yarn也不行

**Comment by junhwong** [comment]
@luckyadam @Chen-jj 很奇怪，我按照文档升级也出现这个问题，配置也检查过，依赖也安装了
版本是最新版本 2.1.3了

**Comment by junhwong** [comment]
解决了，重新安装所有依赖

**Comment by candyAndBella** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/78048954-080fa180-73ad-11ea-9376-7727697648a2.png)
> ![image](https://user-images.githubusercontent.com/1782542/78048973-0f36af80-73ad-11ea-9fda-90d9e3009874.png)
> 没问题了麻烦关闭此 issue
Taro全局安装的是1.2.26，我只想把这一个项目升级到2.1.0，其他项目还用1.2.26。所以是按照局部升级的方式做的。现在用yarn的方式可以启动成功，用taro的方式启动就失败，这是为什么呢？这明明是同一个项目啊

**Comment by candyAndBella** [comment]
> 解决了，重新安装所有依赖
我都安装过好几遍了，我的全局是1.2.26，我只想升级这一个项目，不想影响其他项目

**Comment by junhwong** [comment]
@candyAndBella 可以使用 npx

**Comment by Garfield550** [comment]
建议仔细读一下 @shenghanqin 大佬这篇 [[taro-2.0.1]从项目维护的角度来谈如何升级tarojs 2.x的注意点](https://github.com/NervJS/taro/issues/5339) #5339 

> cli装在本地而非全局的好处是，全局可以安装1.3.x的版本，这样与团队其他小伙伴保持一致，而2.x测试的分支，只会影响当前项目而已。

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/79422771-0a4e3e80-7ff0-11ea-892f-7b831e1755c4.png)

另外迁移指南也有写单独为某个项目升级
