### ISSUE TITLE
static defaultProps 设置了default值，仍会存在undefined的情形

### ISSUE THREAD

**Issue by kala888** [NervJS/taro#5864]
如下代码，刷新编译后，会render 3次，第一次是默认值，第二次是undefined，第三次是获取的数据。
 componentDidMount 的时候，发送ajax请求，更新dva model。

```
@connect(({ genericform }) => ({ ...genericform }))
class GenericformPage extends Taro.PureComponent {
  static defaultProps = {
    groupList: [],
    stepList: [],
    actionList: [],
    fieldList: [],
  }

  componentDidMount() {
    const { pageTitle = '' } = this.props
    Taro.setNavigationBarTitle({ title: pageTitle })
    NavigationService.ajax('mock-generic-form/')
  }
    render() {
    const { id, groupList, fieldList, stepList, actionList } = this.props
    console.log('xxxxx2', groupList, fieldList, stepList, actionList)
   }
}
```

错误如图，
![image](https://user-images.githubusercontent.com/1215976/78010329-d1b63000-7374-11ea-8392-3fa97ed80f95.png)

编译后代码
```
key: '_createData',
    value: function _createData() {
      var _this3 = this;

      this.__state = arguments[0] || this.state || {};
      this.__props = arguments[1] || this.props || {};
      var __isRunloopRef = arguments[2];
      var __prefix = this.$prefix;
      ;

      var _genCompid = (0, _taroWeapp.genCompid)(__prefix + "$compid__426"),
          _genCompid2 = _slicedToArray(_genCompid, 2),
          $prevCompid__426 = _genCompid2[0],
          $compid__426 = _genCompid2[1];

      var _genCompid3 = (0, _taroWeapp.genCompid)(__prefix + "$compid__427"),
          _genCompid4 = _slicedToArray(_genCompid3, 2),
          $prevCompid__427 = _genCompid4[0],
          $compid__427 = _genCompid4[1];

      // const { id, groupList = [], fieldList = [], stepList = [], actionList = [] } = this.props


      var _props = this.__props,
          id = _props.id,
          groupList = _props.groupList,
          fieldList = _props.fieldList,
          stepList = _props.stepList,
          actionList = _props.actionList;

      console.log('xxxxx2', groupList, fieldList, stepList, actionList);
```

**Comment by Chen-jj** [comment]
@kala888 页面不需要设置 defaultProps，直接给 Store 设置默认值看看

**Comment by kala888** [comment]
@Chen-jj  你的意思设页面上设置defaultProps就会有这个问题？component中就会是好的？我去试试。
我直接在render里面设置默认值，是可以的，编译的代码也设置了默认值。只是觉得，这里应该有些问题
```
const { id, groupList = [], fieldList, sceneList: stepList = [], actionList = [] } = this.props
```

**Comment by Chen-jj** [comment]
@kala888 页面设置 defaultProps 应该是不生效而且，至于为什么是 undefined 可以打断点走查一下。

**Comment by kala888** [comment]
@Chen-jj 确实是页面的defaultProps不生效，如果不是bug，是不是在文档上写上tips，我刚才翻文档，没看到。谢谢

**Comment by yuminMorning** [comment]
https://github.com/NervJS/taro/blob/258cd78f4f6fc6c1079c7094aed1abfe455ee9df/packages/taro-tt/src/native-api.js#L116

打断点调试了一下，貌似是这里的问题。在执行 `navigateTo` 时创建了一个新的组件实例，但在创建时没有传入 props。

**Comment by Chen-jj** [comment]
@yuminMorning 

navigateTo 创建的 Component 是给**预加载**功能用的，一般情况下不会创建。

真正创建 Component 是在这里：

https://github.com/NervJS/taro/blob/7d7161cf0567f393d4c33a2c0ddc2b5a4764ad8e/packages/taro-tt/src/create-component.js#L319

而为 props 赋值是这里的 filterProps 函数。页面是直接 mount，不会经过 filterProps 处理，也就不会合并 defaultProps 了。

https://github.com/NervJS/taro/blob/7d7161cf0567f393d4c33a2c0ddc2b5a4764ad8e/packages/taro-tt/src/create-component.js#L276-L290

页面不像组件，props 来源只会是状态管理工具的注入，所以我理解是在 store 创建时赋予默认值而不是由 defaultProps 赋予默认值。
