### ISSUE TITLE
env的输出异常

### ISSUE THREAD

**Issue by ruofeng086** [NervJS/taro#5869]
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {},
  mini: {},
  h5: {}
}

// output
node env: ""development""

**Comment by shenghanqin** [comment]
请提交更完整的信息。

**Comment by ruofeng086** [comment]
path: @tarojs/cli/src/mini/index.ts > buildWithWebpack > miniRunnerOpts

projectConfig.env，输出前，是不是要先转换成string先？

`  console.log("projectConfig: %o", projectConfig);
`

output：
`  env: {
    NODE_ENV: '"development"'
  }`

**Comment by ruofeng086** [comment]
path: @tarojs/cli/src/mini/index.ts > buildWithWebpack > miniRunnerOpts

`const miniRunnerOpts = {
...
env: envToString(projectConfig.env),
...
}`

`function envToString(env: IOption | undefined) {
    if (env === void 0) return env;
    for (const e in env) {
      try {
        env[e] = JSON.parse(env[e]);
      } catch (error) {}
    }
    return env;
  }`

`process.env.NODE_ENV === "development" // true`

这样就ok了
