### ISSUE TITLE
问一下，taro 未来考虑支持PWA，amp 吗？还有对H5的SEO问题怎么考虑的？

### ISSUE THREAD

**Issue by dxhuii** [NervJS/taro#587]
问一下，taro 未来考虑支持PWA，amp 吗？还有对H5的SEO问题怎么考虑的？

**Comment by Pines-Cheng** [comment]
立足大地，仰望星空。

**Comment by dxhuii** [comment]
@Pines-Cheng 嗯，不急。只是问一下，展望一下未来。现在H5还是需要考虑SEO的，毕竟百度抓取不了单页应用。PWA有了RN，也可以暂时不需要了。

**Comment by hzh1990** [comment]
呵呵。

**Comment by yuche** [comment]
Duplicate of #135
