### ISSUE TITLE
Taro Next如何在app.config.ts中使用import或require

### ISSUE THREAD

**Issue by fred8617** [NervJS/taro#5871]
### 问题描述

使用import与require编译器会报错

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ldc-37** [comment]
beta.6中这个问题仍然存在。

项目中使用默认的tabbar，需要在app.config.ts中引入iconPath。如果使用import，编译会报错
```
Module not found: Can't resolve 'xxx' in 'xxx'
```
进一步尝试后发现app.config.ts也无法引入其他文件。

我暂时的解决方案是在其他地方用require.context引入图片，然后app.config.ts中iconPath直接设置为编译后的实际地址（啊，太僵硬了）

**Comment by Chen-jj** [comment]
@ldc-37 @fred8617 下一个版本 **rc0** 应该可以了，我们改用了 @babel/register 去载入 config.js。

https://github.com/NervJS/taro/blob/835bcf26b94cb63567de68dcda00210e7ab1572a/packages/taro-helper/src/utils.ts#L494-L504

**Comment by ruofeng086** [comment]
@Chen-jj 这个问题解决了吗？app.config.ts 可以import 或export 了吗？

**Comment by waycowei** [comment]
还是不行啊
