### ISSUE TITLE
小程序中使用了 behavior ，convert 转换后，编译到其它端不能正常运行的问题

### ISSUE THREAD

**Issue by coymaple** [NervJS/taro#5873]
### 问题描述

使用 `taro convert` 将小程序转换成 taro 项目，再转换成 **h5** 在浏览器中预览时遇到了问题。因原项目中使用了 **vant-weapp** 这一小程序ui框架，而现阶段的 `taro convert` 不支持 behavior。因为是旧项目，换成其他的ui框架也得不偿失。希望官方可以重视一下这个问题。

### 预期目标

`taro convert` 转换小程序项目后，可以在其他端正常预览转换结果。

### 复现步骤

1. 随便创建一个小程序项目；
2. 在小程序项目中引入 vant-weapp ；
3. 在页面中引入vant 的组件；
4. 使用 `taro convert` 命令将小程序项目转换成taro项目；
5. 在 taroConvert 目录中执行 npm run dev:h5；  

### 报错信息

![image](https://user-images.githubusercontent.com/28804891/78105194-3a5be600-7423-11ea-8956-8a38befbc84c.png)

### 系统信息

```
  Taro CLI 2.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.2 - C:\Program Files\nodejs\npm.CMD
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by zhengpq** [comment]
同遇到类似的问题

**Comment by Chen-jj** [comment]
3.1 支持
