### ISSUE TITLE
Picker组件下的PickerDateProps类型声明与实际不符

### ISSUE THREAD

**Issue by Heshiyu1996** [NervJS/taro#5877]
### 问题描述
【Picker组件】`PickerDateProps`下的`onChange`的类型声明：

根据`BaseEventOrigFunction<onChangeEvnetDetail>`描述，发现onChangeEvnetDetail下的`value`为`number`与实际不符，实际上onChangeEvnetDetail返回的是`string`。

### 复现步骤
1.打开：`node_modules/@tarojs/components/types/Picker.d.ts`

2.找到接口`PickerDateProps`下`onChange`声明

3.找到`PickerDateProps.onChangeEvnetDetail`声明

4.发现里面返回的value是个`number`类型

![image](https://user-images.githubusercontent.com/25808006/78125040-13151100-7443-11ea-9db6-db8e673e09a2.png)

### 期望行为
希望`onChangeEvnetDetail`类型声明中的value改为`string`类型
（针对接口`PickerDateProps`下的`onChange`）

### 报错信息

![image](https://user-images.githubusercontent.com/25808006/78124777-be719600-7442-11ea-94eb-9513da805639.png)

![image](https://user-images.githubusercontent.com/25808006/78124711-a39f2180-7442-11ea-9d0e-7aed01070a6a.png)

### 系统信息

👽 Taro v2.1.0

  Taro CLI 2.1.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.npm-global/bin/yarn
      npm: 6.9.0 - ~/.npm-global/bin/npm
    npmPackages:
      @tarojs/components: 2.1.0 => 2.1.0 
      @tarojs/components-qa: 2.1.0 => 2.1.0 
      @tarojs/mini-runner: 2.1.0 => 2.1.0 
      @tarojs/router: 2.1.0 => 2.1.0 
      @tarojs/taro: 2.1.0 => 2.1.0 
      @tarojs/taro-alipay: 2.1.0 => 2.1.0 
      @tarojs/taro-h5: 2.1.0 => 2.1.0 
      @tarojs/taro-qq: 2.1.0 => 2.1.0 
      @tarojs/taro-quickapp: 2.1.0 => 2.1.0 
      @tarojs/taro-rn: 2.1.0 => 2.1.0 
      @tarojs/taro-swan: 2.1.0 => 2.1.0 
      @tarojs/taro-tt: 2.1.0 => 2.1.0 
      @tarojs/taro-weapp: 2.1.0 => 2.1.0 
      @tarojs/webpack-runner: 2.1.0 => 2.1.0 
      eslint-config-taro: 2.1.0 => 2.1.0 
      eslint-plugin-taro: 2.1.0 => 2.1.0 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.1.0 => 2.1.0 
      stylelint-taro-rn: 2.1.0 => 2.1.0 
      taro-ui: ^2.2.4 => 2.3.1 
    npmGlobalPackages:
      typescript: 3.7.2
### 补充信息
冒昧问下，`onChangeEvnetDetail`这个单词是不是拼错了...

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
你说的对[Facepalm]

**Comment by OriX0** [comment]
考古 这个没有被更改的问题 应该是内部做了统一的类型处理
