### ISSUE TITLE
render中两个结构相同数据不同的map最后编译只渲染了第一个wxml

### ISSUE THREAD

**Issue by mylesshie** [NervJS/taro#5879]
### 问题描述
两个相同结构的数据调用相同组件根据条件用map生成dom结构，结果编译为wxml时只编译了第一个插入的dom对象，第二个直接作为变量输出了
### 复现步骤
以下是部分代码

`if (activeSection.top_steps && activeSection.top_steps.length) {
      topStepList = activeSection.top_steps.map(item => {
        let returnDom = null
        if (item.type == 'audio') {
          returnDom = (
            <AudioCardCopy
              key={item.id}
              info={item}
              onPlay={this.onPlayAudio}
              onPause={this.onPauseAudio}
              isPlayed={isPlayNow}
              activePlayMusic={playedAudioName}
            />
          )
        }
        return returnDom
      })
    }

    if (activeSection.steps && activeSection.steps.length) {
      bottomStepList = activeSection.steps.map((item) => {
        let returnDom = null
        if (item.type == 'audio') {
          returnDom = (
            <AudioCard
              key={item.id}
              info={item}
              onPlay={this.onPlayAudio}
              onPause={this.onPauseAudio}
              isPlayed={isPlayNow}
              activePlayMusic={playedAudioName}
            />
          )
        } else {
          returnDom = (
            <StepCard
              key={item.id}
              info={item}
              topicId={activeSection.topic_id}
              sectionId={activeSection.id}
              type={item.type || ''}
              isLock={item.is_locked}
            />
          )
        }
        return returnDom
      })
    }`

activeSection.steps和activeSection.top_steps是结构相同的数据，都要用map遍历生成dom结构，代码如上，结果在编译成wxml时只对最开始插入的dom进行了编译，第二个直接作为一般变量输出了，如下所示：
`<block wx:if="{{sections.length}}">
                    <view>
                        <view class="step-list">
                            <block>
                                <block wx:if="{{activeSection.steps && activeSection.steps.length}}">
                                    <block wx:for="{{loopArray67}}" wx:for-item="item" wx:for-index="_anonIdx4" wx:key="id">
                                        <block wx:if="{{activeSection.top_steps && activeSection.top_steps.length}}">
                                            <block wx:if="{{item.$original.type == 'audio'}}">
                                                <audio-card-copy compid="{{item.$compid__164}}"></audio-card-copy>
                                            </block>
                                        </block>
                                        <block wx:elif="{{activeSection.steps && activeSection.steps.length}}">
                                            <block wx:if="{{item.$original.type == 'audio'}}">
                                                <audio-card wx:key="id" compid="{{item.$compid__165}}"></audio-card>
                                            </block>
                                            <block wx:else>
                                                <step-card wx:key="id" compid="{{item.$compid__166}}"></step-card>
                                            </block>
                                        </block>
                                    </block>
                                </block>
                            </block>
                        </view>
                        <view class="step-list">{{topStepList}}</view>`

### 期望行为

正常的话 topStepList 也应该生成上面的循环结构

### 报错信息

无报错，界面没展示第二个列表

### 系统信息

   System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.34 => 1.3.34 
      @tarojs/cli: ^1.3.34 => 1.3.34 
      @tarojs/components: 1.3.34 => 1.3.34 
      @tarojs/components-qa: 1.3.34 => 1.3.34 
      @tarojs/mobx: ^2.0.7 => 2.1.0 
      @tarojs/plugin-babel: 1.3.34 => 1.3.34 
      @tarojs/plugin-csso: 1.3.34 => 1.3.34 
      @tarojs/plugin-less: 1.3.34 => 1.3.34 
      @tarojs/plugin-uglifyjs: 1.3.34 => 1.3.34 
      @tarojs/redux: 1.3.34 => 1.3.34 
      @tarojs/redux-h5: 1.3.34 => 1.3.34 
      @tarojs/router: 1.3.34 => 1.3.34 
      @tarojs/taro: 1.3.34 => 1.3.34 
      @tarojs/taro-alipay: 1.3.34 => 1.3.34 
      @tarojs/taro-h5: 1.3.34 => 1.3.34 
      @tarojs/taro-qq: 1.3.34 => 1.3.34 
      @tarojs/taro-quickapp: 1.3.34 => 1.3.34 
      @tarojs/taro-rn: 1.3.34 => 1.3.34 
      @tarojs/taro-swan: 1.3.34 => 1.3.34 
      @tarojs/taro-tt: 1.3.34 => 1.3.34 
      @tarojs/taro-weapp: 1.3.34 => 1.3.34 
      @tarojs/webpack-runner: 1.3.34 => 1.3.34 
      eslint-config-taro: 1.3.34 => 1.3.34 
      eslint-plugin-taro: 1.3.34 => 1.3.34 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 1.3.34 => 1.3.34 
      stylelint-taro-rn: 1.3.34 => 1.3.34 
    npmGlobalPackages:
      typescript: 3.6.2

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@mylesshie 复现不了，提供一个可复现 demo 咯
