### ISSUE TITLE
关于Taro通过props传入style样式无法渲染的问题

### ISSUE THREAD

**Issue by liuyangwang** [NervJS/taro#588]
**问题描述**
[问题描述：自定义组件通过props传入data数组，循环渲染数组并应用自定义样式，列表无法正常渲染]

**复现步骤**
[复现问题的步骤]
1. 自定义一个组件
2. 组件props传入数组[{title:"1“，value:"我是1",selfStyle:{color:"#fd4054"}}]
3. 组件无法正常渲染（无报错）

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
props传入的参数
data = [
            [{ title: "起拍价", value: lawPrice, selfStyle:{color:"#fd4054"} }, { title: "单价", value: singlePrice}]
        ]
 return (
            <View className='wrapper'>
                {data.length ? data.map((item, index) => {
                    return <View className='list' key={index}>
                        {item.length ? item.map((list, key) => {
                            return <View className='item text-ellipsis' key={key}>
                                <View className='item-title'>{list.title}</View>
                                <View style={list.selfStyle} >{list.value}</View>
                            </View>
                        }) : ''}
                    </View>
                }) : ''}
            </View>
        )

```

**期望行为**
[期望正常渲染列表并应用自定义样式]

**报错信息**

[编译无报错，列表无渲染]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g.1.0.0-beta.23]
 - Node.js 版本 [e.g. v10.9.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
你在编译后的js 文件找一下 `loopArray0` (可能 0 是1，2，3)这个变量，打印出来看看他的数据结构和 this.props.data 是不是不一样

**Comment by VFiee** [comment]
这是我传入的props：data = [
            [{ title: "起拍价", value: lawPrice, class: 'red', selfStyle: { color: '#fd4054' } }, { title: "单价", value: singlePrice, class: 'red', selfStyle: { color: '#fd4054' } }],
            [{ title: "市场价", value: marketPrice }, { title: "保证金", value: collateralPrice }]
        ]
这是打印的loopArray0:(2) [{…}, {…}]0: 0: $loopState__temp2: ""title: "建筑年代"value: "2012年"__proto__: Object1: $loopState__temp2: ""title: "物业费"value: "1.8元/㎡/月"__proto__: Object__proto__: Object1: 0: $loopState__temp2: ""title: "产权年限"value: 70__proto__: Object1: $loopState__temp2: ""title: "绿化率"value: "36%"__proto__: Object__proto__: Objectlength: 2nv_length: (...)__proto__: Array(0)
总结：selfStyle={...}  变成了  $loopState__temp2: ""

**Comment by luckyadam** [comment]
@VFiee 下个版本修复~

**Comment by VFiee** [comment]
好的~

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/d602d0cad7c157791ccb12800c215f89e2afa27e
