### ISSUE TITLE
CanvasRenderingContext2D 对象通过canvas.getContext("2d")创建出来，无法使用drawImage方法绘制图片

### ISSUE THREAD

**Issue by cocotyty** [NervJS/taro#5881]
### 问题描述
CanvasRenderingContext2D 对象通过canvas.getContext("2d")创建出来，无法使用drawImage方法绘制图片

### 复现步骤

1. 
2. 
3. 
4. 

```typescript
export default class Index extends Component {
  componentWillMount() {}

  componentDidMount() {
    Taro.createSelectorQuery()
      .select("#myCanvas")
      .node()
      .exec(res => {
        this.cvs = res[0].node;
        this.ctx = this.cvs.getContext("2d") as CanvasRenderingContext2D;
      });
  }
onClick(){
    Taro.chooseImage({
      count: 1,
      success: (result: Taro.chooseImage.SuccessCallbackResult) => {
        this.ctx.drawImage(result.tempFilePaths[0], 0, 0, 32, 32);
      }})
}
```

### 报错信息

`thirdScriptError
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)';at api chooseImage success callback function
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at Object.success (http://127.0.0.1:49866/appservice/pages/index/index.js:132:22)
    at obj.<computed> (http://127.0.0.1:49866/appservice/taro.js:3423:39)
    at o.<computed> (WAService.js:1:1124967)
    at vC (WAService.js:1:1085067)
    at Function.success (WAService.js:1:1086734)
    at Object.success (WAService.js:1:102993)
    at r (WAService.js:1:421323)
    at WAService.js:1:421500
    at v (WAService.js:1:421509)
    at WAService.js:1:422917
console.error @ VM5054:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
r @ WAService.js:1
(anonymous) @ WAService.js:1
v @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ VM5058 asdebug.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
setTimeout (async)
setTimeout @ WAService.js:1
(anonymous) @ VM5058 asdebug.js:1
(anonymous) @ VM5058 asdebug.js:1
(anonymous) @ VM5058 asdebug.js:1
_ws.onmessage @ VM5058 asdebug.js:1`
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by darkfiredarkhalo** [comment]
为什么无缘无故就关了呢

**Comment by darkfiredarkhalo** [comment]
@cocotyty 最终怎么解决了?麻烦告知下
