### ISSUE TITLE
Taro1.3.5升级2.1.0报错

### ISSUE THREAD

**Issue by is-nan** [NervJS/taro#5883]
### 问题描述
更新项目中 Taro 相关的依赖为2.1.0，
更新cli2.1.0

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 报错信息

![image](https://user-images.githubusercontent.com/38523283/78209068-a51b2900-74d8-11ea-96b1-7ccc90bc3330.png)

**Comment by is-nan** [comment]
之前cli是1.3.5的，项目依赖也是1.3.5

**Comment by is-nan** [comment]
解决了，现在一直出现has not been registered yet.

**Comment by icewind7030** [comment]
怎么解决的？

**Comment by icewind7030** [comment]
怎么解决的？
