### ISSUE TITLE
小程序代码转Taro源码里面的引用变成了commonjs规范了，编译H5报错

### ISSUE THREAD

**Issue by stite** [NervJS/taro#5885]
### 问题描述
小程序代码转Taro源码里面的引用变成了commonjs规范了，编译H5报错，H5不支持commonjs规范

### 复现步骤
1、小程序项目执行：taro convert
2、查看源码里面引用已经使用了Commonjs规范的引用（编译小程序端无问题）
3、npm run dev:h5

```js
// 小程序转成Taro的源码
const app = Taro.getApp()
const { Config, temImgUrl, templist, appId } = require('../../utils/config.js')
const util = require('../../utils/util.js')
...
```
### 期望行为
如何可以使h5支持commonjs规范，如果全部改成import未知风险比较大

### 报错信息
H5浏览器报错信息
![image](https://user-images.githubusercontent.com/12437796/78221476-069dc080-74f6-11ea-856e-bd04c73aedc4.png)

### 系统信息

👽 Taro v2.0.6
  Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.5.2

### 补充信息
感谢

**Comment by ZakaryCode** [comment]
未能复现到该问题，可以尝试升级到 2.2.13 版本来解决
