### ISSUE TITLE
npm run build 会把 scss 的注释先过滤，导致带注释的编译无效

### ISSUE THREAD

**Issue by Norbert-Nayman** [NervJS/taro#5886]
### 问题描述

npm run build:weapp  会把 scss 的注释先过滤，导致带注释的编译无效
导致我的长文字换行+省略的样式出问题了

npm run dev 没有问题

### 复现步骤

1. 在scss中编写以下代码

```scss

display: -webkit-box;
overflow: hidden;
word-break: break-all;
text-overflow: ellipsis;
-webkit-line-clamp: 2;
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;

```

2. npm run build: weapp 打包
3. 在dist文件夹下对应的 wxss 文件中以下代码被过滤

```scss

-webkit-box-orient: vertical;

```

### 期望行为

希望留下

```scss

-webkit-box-orient: vertical;

```

或者先编译再执行 uglify

**Comment by wsyxl365** [comment]
同样的问题 魔法注释后 build会被过滤 导致多行文本换行样式失败

**Comment by leidenglai** [comment]
https://github.com/NervJS/taro/issues/5710#issuecomment-599313433

**Comment by hotchicken1996** [comment]
今天遇到同样的问题，是因为csso压缩css的时侯把注释先删掉了，才导致了这个情况。解决办法：
在注释的开头加一个！（/*! autoprefixer: ignore next */）这样就不会被删除。
关于csso：https://github.com/css/csso#minifysource-options
