### ISSUE TITLE
native端二维码扫描功能

### ISSUE THREAD

**Issue by dskin** [NervJS/taro#5895]
### 问题描述

taro native端目前翻看文档，scanCode没有支持native端，有其他的方式在native端使用相机实现二维码扫描功能吗

### 期望行为

支持scanCode

### 系统信息

Taro CLI 2.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\97888\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by iChengbo** [comment]
[react-native-local-barcode-recognizer](https://www.npmjs.com/package/react-native-local-barcode-recognizer)
这个可以试下，分端处理

**Comment by Pines-Cheng** [comment]
相关 PR 已合入：https://github.com/NervJS/taro/issues/4550
