### ISSUE TITLE
hooks修改数组，页面更新异常

### ISSUE THREAD

**Issue by NomadJohn** [NervJS/taro#5899]
### 问题描述
hooks修改数组时，set一个使用new Array(4)创建的数组，页面会更新异常。

### 复现步骤

点击A
![image](https://user-images.githubusercontent.com/30516060/78528389-d6199780-7811-11ea-823a-0e596913e757.png)
点击B
![image](https://user-images.githubusercontent.com/30516060/78528429-ef224880-7811-11ea-9fca-09384558de0c.png)
点击C
![image](https://user-images.githubusercontent.com/30516060/78528435-f8131a00-7811-11ea-9978-13b4b513bbf5.png)
点击D
![image](https://user-images.githubusercontent.com/30516060/78528474-0cefad80-7812-11ea-90b6-18bfdfb33cb0.png)

```js
const Test: Taro.FC = () => {
  const [styles, setStyles] = useState<Array<any>>([]);
  const handleChoose = (activeIndex) => {
    let newStyle = ['', '', '', ''];
    // let newStyle = new Array(4); //问题出在这里
    newStyle[activeIndex] = 'active';
    setStyles(newStyle);
  }
  return (

    <View>
      {['A', 'B', 'C', 'D'].map((v, i) =>
        <Button onClick={() => handleChoose(i)}>{v}</Button>
      )}
      <View>真实数组：{styles.toString()}</View>
      <View>手动遍历：{styles.map((style, index) => <View>{index} {style}</View>)}</View>
      <View>
        手动访问：
        <View>0 {styles[0]}</View>
        <View>1 {styles[1]}</View>
        <View>2 {styles[2]}</View>
        <View>3 {styles[3]}</View>
      </View>
    </View>
  )
}


```

### 期望行为

正常情况下应该是同时只有一个active，

但这里页面上显然还保留了上一次的结果。

同样的代码在react上测试过，没有问题。

### 系统信息

```shell
PS G:\webAPP\quiz2020-taro> taro info
�👽 Taro v1.3.


  Taro CLI 1.3.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 13.0.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - D:\Program Files\nodejs\yarn.CMD
      npm: 6.12.0 - D:\Program Files\nodejs\npm.CMD
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@NomadJohn 

```
let newStyle = new Array(4);
newStyle[activeIndex] = 'active';
//  => [undefined, undefined, 'active', undefined]
```

小程序中 setData undefined 不能覆盖前值，你需要给 newStyle 初始化每一项为 `''`。
