### ISSUE TITLE
Taro Next中Current.router获取的数据有误

### ISSUE THREAD

**Issue by yz1311** [NervJS/taro#5900]
### 问题描述

跳转到页面A后，`Current.router.params`获取的参数是,是从前一页面传递过来的

![](https://tva1.sinaimg.cn/large/00831rSTgy1gdk1qcywpbj309l025glq.jpg)

继续跳转到页面B，然后返回到页面A，`Current.router.params`获取到的还是页面B的值,且一直不变

![](https://tva1.sinaimg.cn/large/00831rSTgy1gdk1qojkykj30ab02074f.jpg)

### 复现步骤

1. 跳转到页面A
2. 继续跳转到页面B
3. 从B返回到A页面

### 期望行为

`Current.router.params`获取的始终为当前页面的路由信息

### 系统信息

 Taro CLI 3.0.0-beta.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.0-beta.2 => 3.0.0-beta.2 
      @tarojs/components: 3.0.0-beta.2 => 3.0.0-beta.2 
      @tarojs/taro: 3.0.0-beta.2 => 3.0.0-beta.2 
      @tarojs/webpack-runner: 3.0.0-beta.2 => 3.0.0-beta.2 
      eslint-config-taro: 3.0.0-beta.2 => 3.0.0-beta.2 
      react: ^16.10.0 => 16.13.0 
    npmGlobalPackages:
      typescript: 3.7.5

**Comment by eiddie** [comment]
使用`useRouter`就不会出现这种问题，[`useRouter`](https://github.com/NervJS/taro/blob/e1ee21e8f41ca2c2ac37838b627807ad744a7067/packages/taro-runtime/src/dsl/hooks.ts#L53)只是对`Current.router`封装了下
```js
  const router = useRouter()

  useDidShow(() => {
    console.log("params", router?.params);
  })

```

**Comment by yz1311** [comment]
> 使用`useRouter`就不会出现这种问题，[`useRouter`](https://github.com/NervJS/taro/blob/e1ee21e8f41ca2c2ac37838b627807ad744a7067/packages/taro-runtime/src/dsl/hooks.ts#L53)只是对`Current.router`封装了下
> 
> ```js
>   const router = useRouter()
> 
>   useDidShow(() => {
>     console.log("params", router?.params);
>   })
> ```

还真是,用FC组件测试了下，看来真的是个bug
```js
const router = useRouter();

...

console.log(Current.router)
console.log(router)
```

刚进去:
![](https://tva1.sinaimg.cn/large/00831rSTgy1gdk516rewgj30eb0193yk.jpg)

跳转后返回:
![](https://tva1.sinaimg.cn/large/00831rSTgy1gdk51stwp7j30a901daa4.jpg)


由于还是有很多class component，改为进页面的时候，将跳转参数保存了一下

**Comment by yuche** [comment]
这其实不是 bug，而是特性， `Current.router` 就是会随着页面的变化而变化的，其实他的名字你就可以猜到，`Current` 就像 React Ref 的 `current` 一样是会随时改变的。你也可以在某个页面把他缓存起来。例如：

```js
class Page extends Component {
	componentDidShow () {
		this.router = { ...Current.router }
    }
}
```

**Comment by yz1311** [comment]
> 这其实不是 bug，而是特性， `Current.router` 就是会随着页面的变化而变化的，其实他的名字你就可以猜到，`Current` 就像 React Ref 的 `current` 一样是会随时改变的。你也可以在某个页面把他缓存起来。例如：
> 
> ```js
> class Page extends Component {
> 	componentDidShow () {
> 		this.router = { ...Current.router }
>     }
> }
> ```

Current.router按照我的理解是获取路由栈的栈顶的路由信息,为什么下面会获取到的是明明已经出栈的页面的路由信息?
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gds6hhe47yj30jd0b0jtg.jpg)

**Comment by yuche** [comment]
你截的图我没搞懂谁对应谁，可以做一个简单的复现的 demo 仓库吗

**Comment by yz1311** [comment]
> 你截的图我没搞懂谁对应谁，可以做一个简单的复现的 demo 仓库吗

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gds8cqkigig30ak0iq4qq.gif)

https://github.com/yz1311/taro-router-test

**Comment by wuchangming** [comment]
看起来确实是有点问题。
目前只有onLoad设置一次 Current.router ，所以永远指向最后一次加载的路由信息。在onshow的时候重新设置为当前路由信息能修复。
提了个PR：https://github.com/NervJS/taro/pull/5989

**Comment by cncolder** [comment]
@eiddie useRouter 不变的原因是因为它对 Current.router 做了 memo. 详见 #5707
