### ISSUE TITLE
使用亚马逊的s3上传文件，引入aws-sdk后 编译报错

### ISSUE THREAD

**Issue by Xi-yu** [NervJS/taro#5904]
![image](https://user-images.githubusercontent.com/35017425/78629247-0b34f100-78c9-11ea-98d8-d87da5f0e896.png)
![image](https://user-images.githubusercontent.com/35017425/78629262-14be5900-78c9-11ea-8c05-1f1b41eee00b.png)

**Comment by Garfield550** [comment]
`fs` 是 Node.js 原生库，微信小程序没有这些 API

**Comment by Xi-yu** [comment]
> `fs` 是 Node.js 原生库，微信小程序没有这些 API

那有什么方法没呢

**Comment by shenghanqin** [comment]
使用腾讯云的云开发当做nodejs环境来完成这个。

**Comment by P233** [comment]
@shenghanqin 我最近也遇到了这个问题， 不过在 create react app 里引用 aws-sdk 没有问题，可以正常使用， 是因为 Taro 做了什么限制吗？

**Comment by fandipeng** [comment]
有无更新？需要用到aws
