### ISSUE TITLE
Taro 2.1.0 微信小程序和Taro混写，开发者工具中代码包比原生微信小程序大了很多

### ISSUE THREAD

**Issue by cyq333** [NervJS/taro#5905]
### 问题描述

Taro 2.1.0 微信小程序和Taro混写，编译之后代码包过大，导致无法预览

### 复现步骤

taro混写时的包大小
![image](https://user-images.githubusercontent.com/15816893/78639030-daac8180-78df-11ea-97b3-4f9495ae9f08.png)

原生小程序的包大小（未添加taro时）
![image](https://user-images.githubusercontent.com/15816893/78639137-03cd1200-78e0-11ea-8bbd-747f4462c8ef.png)

**Comment by yyhdev** [comment]
set NODE_ENV=production然后npm run dev:weapp就行了，官方文档居然没介绍。。。

**Comment by cyq333** [comment]
> set NODE_ENV=production然后npm run dev:weapp就行了，官方文档居然没介绍。。。

是在config/index.js中设置吗？试了没有用啊

**Comment by yyhdev** [comment]
就是在当前的shell设置一个临时的环境变量，我是windows就用的set，linux就用export

**Comment by cyq333** [comment]
set NODE_ENV=production之后包确实比原来小了一些，但还是比原生的时候要大很多啊
set NODE_ENV=production后的包大小
![image](https://user-images.githubusercontent.com/15816893/78759836-d1d8b000-79b2-11ea-8b87-d5488e333b96.png)

之前：
![image](https://user-images.githubusercontent.com/15816893/78759968-0482a880-79b3-11ea-9986-65f8482b5b87.png)

原生代码没有加入taro时
![image](https://user-images.githubusercontent.com/15816893/78760027-1f551d00-79b3-11ea-8337-b293ba297f90.png)

**Comment by yyhdev** [comment]
比原生大是肯定的，再把主包分一下吧

**Comment by bobsam** [comment]
因为生成的代码里有taro包和一部分的类似tslib.js的包等等，所以是比原生要大的。这个可以考虑使用分包+webpack chunks的方式来把每个包分拆得更小，然后懒加载或者延迟加载的方式来提升访问效率吧。
