### ISSUE TITLE
不支持逻辑运算符的条件渲染么

### ISSUE THREAD

**Issue by singletonPeople** [NervJS/taro#5907]
### 问题描述

不支持逻辑运算符的条件渲染么

### 复现步骤

```js
{
    isShare &&
    <View className='carrier-box'>
        <View className='carrier'>
            <Text className='carrier-ship'>{_get(item, 'carrier.carrier_code')}</Text>
            <Text className='line-code'>( </Text>
            <Text className='line-code'>{_get(item, 'line_code') || '-'}</Text>
            <Text className='line-code'> )</Text>
        </View>
        <Text className='text-color-blue'>
            {cabinMap[_get(item, 'is_share')] || '-'}
        </Text>
    </View> || 123
}

```

### 报错信息

![image](https://user-images.githubusercontent.com/53305259/78642941-164a4a00-78e6-11ea-8baa-46b924ae21ca.png)

### 补充信息
![image](https://user-images.githubusercontent.com/53305259/78643204-75a85a00-78e6-11ea-9ca9-f241bd5d1342.png)
编译成这样的了  
使用三步运算符可以 但是如果能支持的话还是希望支持一下 谢谢

**Comment by kala888** [comment]
支持条件渲染，用三目运算符吧，顺道把123用View或者Text包一道

**Comment by Chen-jj** [comment]
@singletonPeople 

```js
{
    isShare &&
    <View className='carrier-box'></View> ||
    123
}
```

暂不支持用 JSX 元素作为判断条件。

而且这个 123 也没有意义吧。

**Comment by singletonPeople** [comment]
行吧 123只是测试写的 用三部运算符解决了
