### ISSUE TITLE
npx编译rn和h5的问题

### ISSUE THREAD

**Issue by dingjuanww** [NervJS/taro#591]
按照文档，选择的是redux模板
用默认模板npx先编译rn，npx taro build --type rn --watch，通过expo，是没有问题的。
![image](https://user-images.githubusercontent.com/20511560/45208721-d9f3d980-b2bd-11e8-8470-70c83f3b2dbb.png)
完了之后，关闭模拟器，再编译h5，npx taro build --type h5 --watch，就不能编译了
![image](https://user-images.githubusercontent.com/20511560/45209073-a6fe1580-b2be-11e8-8eb4-0673304d426f.png)
请问这个问题要怎么解决。。。

**Comment by luckyadam** [comment]
重新安装下本地依赖~

**Comment by Pines-Cheng** [comment]
@dingjuanww  解决了吗？
