### ISSUE TITLE
chooseImage在部分安卓机型上无法调用相机

### ISSUE THREAD

**Issue by dzxjlbj** [NervJS/taro#5915]
### 问题描述

H5端Taro.chooseImage上传图片,在部分安卓机上无法调用相机,只能调用文件
### 复现步骤

1. 
 代码 : Taro.chooseImage({
                  }).then(res => {
                     res.tempFilePaths.forEach(file => {
                           this.getBlob(
                               file,
                                this.callback.bind(this),
                                unitId,userId);
          });
        }).catch(e => this.cameraError(e));

2. 
    sourceType 默认时  只调用文件未调用相机(测试手机: 红米6A, oppo R9)
    在 sourceType:['camera'] 未调起相机的机型,文件与相机都调用了

/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

```

### 期望行为

<!-- 请在下一行用简洁清晰的语言描述你期望的行为 -->
尽快修复,并在大多数常用的手机上测试,保证文档说明与实际效果相同
### 报错信息

<!-- 请在下一行贴上你的完整报错截图或文字 -->

### 系统信息

<!-- 使用`taro info`命令即可查看系统及依赖信息。将该命令运行结果贴下面即可。 -->
�👽 Taro v2.1.1
  Taro CLI 2.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD
### 补充信息

<!-- （可选）根据你的调查研究，出现这个问题的原因可能在哪里？ -->

<!-- 感谢您的热心反馈！别忘了用preview按钮预览结果再提交 -->

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by meiye1988** [comment]
楼主，我现在遇到和你一样的情况，现在解决了吗

**Comment by ZakaryCode** [comment]
和 #6347 是同一个问题，这是由于部分安卓手机自身限制导致的，目前通过 H5 没有比较好的解决方案
