### ISSUE TITLE
能不能把taro生成的小程序代码 放到原生小程序里面用呢 因为不能把原生转成taro再二次开发

### ISSUE THREAD

**Issue by zhangfan6644777** [NervJS/taro#5916]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by zhangfan6644777** [comment]
没有人来解答吗 大佬在哪里

**Comment by zhangfan6644777** [comment]
已解决  关闭issue了

**Comment by Chen-jj** [comment]
可以的

**Comment by zhangfan6644777** [comment]
@luckyadam  我看之前是支持的  在1.x版本的时候  在config里面设置appOutput: false  就可以了 但是现在功能好像被拿掉了是吗

**Comment by zhangfan6644777** [comment]
> 可以的

请问要怎么操作呢   之前是可以设置appOutput: false  来实现的 但是现在版本  我在文档上也没看见

**Comment by Chen-jj** [comment]
版本多少，你现在怎么配置的，遇到了什么问题

**Comment by zhangfan6644777** [comment]
> 版本多少，你现在怎么配置的，遇到了什么问题

taro版本是2.1.2   问题就是 我现在把taro生成的代码直接放到原生小程序里面用的话  显示页面未注册  那是因为在page.js里面没有require app.js   所以 他才会说没有注册页面  但是 我也不能手动去在每一个page 的js下面 都去require app.js吧？ 还是说 我要自己写脚本去处理一下？

**Comment by zhangfan6644777** [comment]
> 版本多少，你现在怎么配置的，遇到了什么问题

现在没有任何配置 就是官方的配置   自己没改配置项   只是最简单的demo

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/79408387-c6e2d880-7fcd-11ea-917e-44cf31455606.png)
在原生的 app.js 引用这四个文件再试试

**Comment by zhangfan6644777** [comment]
> ![image](https://user-images.githubusercontent.com/11807297/79408387-c6e2d880-7fcd-11ea-917e-44cf31455606.png)
> 在原生的 app.js 引用这3个文件再试试

这样可以了 谢谢大佬  还有个疑问 如果不想生成taro的app.js  app.json app.wxss  可以实现吗

**Comment by Chen-jj** [comment]
你可以自己写一个 webpack 插件，在 webpack.compilation 的 emit hook 中把 compilation.assets 中不要的 assets 过滤掉。使用 taro 配置里的 webpack chain 加入你的插件。
或者其他什么工作流或脚本，webpack 插件的方法流程上应该比较友好。

**Comment by zhangfan6644777** [comment]
好的 谢谢大佬

**Comment by zhangfan6644777** [comment]
> 你可以自己写一个 webpack 插件，在 webpack.compilation 的 emit hook 中把 compilation.assets 中不要的 assets 过滤掉。使用 taro 配置里的 webpack chain 加入你的插件。
> 或者其他什么工作流或脚本，webpack 插件的方法流程上应该比较友好。

好的 谢谢大佬
