### ISSUE TITLE
2.1.0版本后，编译配置 env 输出异常

### ISSUE THREAD

**Issue by GYxiaOZ** [NervJS/taro#5917]
### 问题描述

参照文档[编译配置详情](https://nervjs.github.io/taro/docs/config-detail.html#env)在配置文件 config/dev.js 中添加 
```
env: {
  NODE_ENV: '"development"'
}
```
期待输出 `'development' ` 实际输出 `"\"development\""`

在2.0.7时正常，升级2.1.0之后出的问题

### 期望行为

修复该问题或修改文档

### 系统信息

Taro CLI 2.1.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
小程序还是 H5

**Comment by GYxiaOZ** [comment]
> 小程序还是 H5
小程序，感谢大佬

**Comment by Link-X** [comment]
h5是正常的。‘env’，小程序是“’env‘”.版本：2.2.1
