### ISSUE TITLE
使用hooks传递on开头的方法，用useCallback不生效

### ISSUE THREAD

**Issue by cd-dongzi** [NervJS/taro#5919]
### 问题描述
用hooks开发，给子组件传递一个方法, 以on开头 例如： onLoad。onLoad方法是通过useCallback生成的。按道理子组件里面useEffect(() => {}, [onLoad])中的依赖是同一个引用，应该只会执行一次吧。但是结果是每次都执行了，导致死循环。而且只是以on开头传递的方法会导致这个问题出现，我把onLoad改成别的名字，不以on开头，执行流程就正常了，只会执行一次

### 复现步骤

<img width="576" alt="WechatIMG1519" src="https://user-images.githubusercontent.com/24870710/78757847-b5874400-79af-11ea-9e9d-551d55349e69.png">
<img width="485" alt="WechatIMG1520" src="https://user-images.githubusercontent.com/24870710/78757870-c20b9c80-79af-11ea-9414-9ea3ac16c308.png">
<img width="569" alt="WechatIMG1518" src="https://user-images.githubusercontent.com/24870710/78757879-c46df680-79af-11ea-8ae9-33ae9bc24798.png">

#### 以下是代码
> index页面
```js
import Taro, { useCallback, useState } from '@tarojs/taro'
import { View } from '@tarojs/components'
import Test from './test'
import './index.less'

const list = [
  {id: 1},
  {id: 2}
]
function Index() {
  const [arr, setArr] = useState<number[]>([])
  const onLoad = useCallback(() => {
    setArr(data => {
      data[0] = 10
      return [...data]
    })
  },[])
  console.log('arr', arr)
  return (
    <View className='Index'>
      {list.map((item: any) => {
        return (
          <Test key={item.id} onLoad={onLoad} />
        )
      })}
    </View>
  )
}

export default Index
```

> 子组件 Test

```js
import Taro, { useEffect } from '@tarojs/taro'
import { View } from '@tarojs/components'
import './index.less'

function Test({
  onLoad
}: {
  onLoad: () => void
}) {
  useEffect(() => {
    console.log('Test => useEffect')
    setTimeout(() => {
      onLoad()
    }, 1000)
  }, [onLoad])
  return (
    <View className='Test'>
      Test
    </View>
  )
}

export default Test
```

### 期望行为
希望用on开头的方法执行正常

### 报错信息

```
Taro v2.0.4


  Taro CLI 2.0.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 3.3.3
```

```
微信开发者工具 Stable v1.02.2004020
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@cd-dongzi on 开头的 props 现在是会被包一层 bind，所以每次渲染函数都是新的。这里传参先不要用 on 开头咯。

**Comment by cd-dongzi** [comment]
嗯  好的
