### ISSUE TITLE
componentWillReceiveProps 触发异常

### ISSUE THREAD

**Issue by atzcl** [NervJS/taro#592]
**问题描述**

在 `组件` 里面往 `循环组件` 传递 `props`，会出现 `componentWillReceiveProps` 生命周期触发异常。
表现为：`被循环组件` 初次不会触发 `componentWillReceiveProps`，然后当传递的 `props` 发生变化后，会同时触发两次

**复现步骤**

可复现 repo：[https://github.com/atzcl/test_componentWillReceiveProps.git](https://github.com/atzcl/test_componentWillReceiveProps)

**期望行为**

`componentWillReceiveProps`  触发正常

**系统信息**

 - Mac 10.13.6 (
 - Taro v1.0.0-beta.25
 - Node.js v10.9.0

**补充信息**
![jietu20180907-091712-hd](https://user-images.githubusercontent.com/28823188/45210150-62c04480-b2c1-11e8-8a31-9d8553d41976.gif)

**Comment by luckyadam** [comment]
还是先开着吧~

**Comment by rwson** [comment]
好像在循环里componentDidMount，componentWillMount也是如此，都不执行

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/31531a55494dd5b795dafbcb90da485b53421e88
