### ISSUE TITLE
Taro输出百度小程序页面json文件错误包含component:true

### ISSUE THREAD

**Issue by eriklynd** [NervJS/taro#5920]
### 问题描述

当使用Taro编译到百度小程序时，页面的json配置文件会错误包含 "component": true，导致页面不能正常加载。

百度开发者工具中报错如下：
```
【Custom Component Error】can't find pages/index, please check your config:
            1. Please check if the reference path is correct;
            2. If it is a page under this path, the "component: true" in the current page JSON should be removed.
```
### 复现步骤

1. taro build --type swan
2. 使用百度开发者工具打开项目

### 期望行为

百度端页面json文件中不包含component: true，页面可以正常打开

### 系统信息

Taro CLI 2.0.7 environment info:
System:
OS: macOS 10.15.3
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
npmPackages:
@tarojs/components: 2.0.7 => 2.0.7
@tarojs/components-qa: 2.0.7 => 2.0.7
@tarojs/mini-runner: 2.0.7 => 2.0.7
@tarojs/router: 2.0.7 => 2.0.7
@tarojs/taro: 2.0.7 => 2.0.7
@tarojs/taro-alipay: 2.0.7 => 2.0.7
@tarojs/taro-h5: 2.0.7 => 2.0.7
@tarojs/taro-qq: 2.0.7 => 2.0.7
@tarojs/taro-quickapp: 2.0.7 => 2.0.7
@tarojs/taro-rn: 2.0.7 => 2.0.7
@tarojs/taro-swan: 2.0.7 => 2.0.7
@tarojs/taro-tt: 2.0.7 => 2.0.7
@tarojs/taro-weapp: 2.0.7 => 2.0.7
@tarojs/webpack-runner: 2.0.7 => 2.0.7
eslint-config-taro: 2.0.7 => 2.0.7
eslint-plugin-taro: 2.0.7 => 2.0.7
nerv-devtools: ^1.5.5 => 1.5.6
nervjs: ^1.5.5 => 1.5.6
stylelint-config-taro-rn: 2.0.7 => 2.0.7
stylelint-taro-rn: 2.0.7 => 2.0.7

### 补充信息

应该为以下代码导致，百度端无论是否isRoot，都会添加component: true

https://github.com/NervJS/taro/blob/e4ec6a26e1cdc329d1ca2882840ad9bd3f3b4e39/packages/taro-mini-runner/src/plugins/MiniPlugin.ts#L652

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@eriklynd 升级下开发者工具，基础库版本调高点再试试咯

 https://smartprogram.baidu.com/docs/develop/framework/custom-component_comp/

![image](https://user-images.githubusercontent.com/11807297/78784140-63f2af80-79d7-11ea-892f-6b27748e59d2.png)

**Comment by eriklynd** [comment]
@Chen-jj 升级开发者工具后暂时没有报错了，感谢回复~
