### ISSUE TITLE
taro create 的 description 参数无效，不能设置为页面标题

### ISSUE THREAD

**Issue by bobsam** [NervJS/taro#5924]
### 问题描述

taro create 的 description 参数无效，不能设置为页面标题

### 复现步骤

```js
taro create --name testPage2 --description "测试页面哇"
```

![image](https://user-images.githubusercontent.com/8551777/78789446-bafc8280-79df-11ea-8aa5-7f39a923a6c4.png)

创建成功的页面

![image](https://user-images.githubusercontent.com/8551777/78789793-378f6100-79e0-11ea-8b70-61d0e8e28086.png)

### 期望行为

期望是taro create 输入的【description】参数可以成为页面的标题

### 系统信息

👽 Taro v1.3.40

  Taro CLI 1.3.40 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.40 => 1.3.40
      @tarojs/cli: 1.3.40 => 1.3.40
      @tarojs/components: 1.3.40 => 1.3.40
      @tarojs/mobx: 1.3.40 => 1.3.40
      @tarojs/mobx-h5: 1.3.40 => 1.3.40
      @tarojs/mobx-rn: 1.3.40 => 1.3.40
      @tarojs/plugin-babel: 1.3.40 => 1.3.40
      @tarojs/plugin-csso: 1.3.40 => 1.3.40
      @tarojs/plugin-sass: 1.3.40 => 1.3.40
      @tarojs/plugin-uglifyjs: 1.3.40 => 1.3.40
      @tarojs/rn-runner: 1.3.40 => 1.3.40
      @tarojs/router: 1.3.40 => 1.3.40
      @tarojs/taro: 1.3.40 => 1.3.40
      @tarojs/taro-alipay: 1.3.40 => 1.3.40
      @tarojs/taro-h5: 1.3.40 => 1.3.40
      @tarojs/taro-swan: 1.3.40 => 1.3.40
      @tarojs/taro-tt: 1.3.40 => 1.3.40
      @tarojs/taro-weapp: 1.3.40 => 1.3.40
      @tarojs/webpack-runner: 1.3.40 => 1.3.40
      eslint-config-taro: 1.3.40 => 1.3.40
      eslint-plugin-taro: 1.3.40 => 1.3.40
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 1.3.40 => 1.3.40
      stylelint-taro-rn: 1.3.40 => 1.3.40

### 补充信息

   未知，要查看cli源码才知道

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
比较小众，暂不考虑实现，欢迎 PR～
