### ISSUE TITLE
React.cloneElement

### ISSUE THREAD

**Issue by keesee** [NervJS/taro#5925]
不好意思我汉语不太好。  有一个问题。  我找不到Taro.CloneElement. :(   Taro有没有？在哪里？

 ```
const Renderer = React.cloneElement(
                this.returnRenderer(), 
                { ...this.returnDynamicProps() }
            )
```
这个怎么做？谢谢 ：）

**Comment by yuche** [comment]
You should use Taro Next, which provides all the React APIs except `React.lazy` and can use most (e.g. `react-redux`, `mobx-react`) React's non-GUI Library directly, with no syntax limitations (e.g. you can't declare two components in one file).

Note that upgrading to Taro Next requires some additional work, most of which is described in [migration guide](https://taro-docs.jd.com/taro/next/docs/migration.html)). However, there is currently no translation of this document, but I believe you can find a way around it as well :).

**Comment by keesee** [comment]
Thanks for the answer.  In English : )  
Will give Taro Next a shot.

**Comment by keesee** [comment]
@yuche -- impressive.  we have some fairly complex workflows via redux/sagas etc.   once I wrote the adapter for Taro.request, all of our core functionality from react dom apps worked in wechat without needing code changes.  thanks for your work on this project and the pointers above.  :)
