### ISSUE TITLE
[Taro3 beta3] watch 模式修改代码保存后 cli 异常退出

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#5926]
### 问题描述

`taro build --type weapp --watch` 修改代码保存

```
正在编译.../Users/colder/Codes.localized/taro3demo/node_modules/webpack-sources/lib/ConcatSource.js:42
                        source += typeof child === "string" ? child : child.source();
                                                                            ^

TypeError: Cannot read property 'source' of undefined
```

### 复现步骤

1. yarn dev:weapp
2. 修改代码保存

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息

taro 3.0.0-beta.3

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@cncolder 复现不了，提供一下 demo？

**Comment by cncolder** [comment]
@Chen-jj 刚跟 yuche 交流了一番, 问题出在我自己的 @tarojsx/ui 里依赖的是 beta2

**Comment by Chen-jj** [comment]
@cncolder 的确是有问题的，我们尽快修复。

**Comment by cncolder** [comment]
@Chen-jj 另一个与 beta2 的区别:

假如我在 @tarojsx/ui 里依赖 react, 最终导致 node_modules 的目录结构出现多层:

```
node_modules
├── @tarojsx
│   ├── ui
│   │   ├── node_modules
│   │   │   ├── react
├── react
```

这会导致 @tarojsx/ui 目录下所有 hooks 失效: `Hooks can only be called inside of the body of a function component.`

退回到 beta2 问题消失.

**Comment by yuche** [comment]
> @Chen-jj 另一个与 beta2 的区别:
> 
> 假如我在 @tarojsx/ui 里依赖 react, 最终导致 node_modules 的目录结构出现多层:
> 
> ```
> node_modules
> ├── @tarojsx
> │   ├── ui
> │   │   ├── node_modules
> │   │   │   ├── react
> ├── react
> ```
> 
> 这会导致 @tarojsx/ui 目录下所有 hooks 失效: `Hooks can only be called inside of the body of a function component.`
> 
> 退回到 beta2 问题消失.

这个问题其实是 React 的问题，React 在文档中明确指出不允许出现多份 React copies：
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
我认为他这个做法没有错，否则你打包应用时也会出现两份 react。

你的 UI 库应该把 React 设置为 peerDeps，打包 UI 时把 react 设置为 external，不应该保存一份 react copy。

**Comment by cncolder** [comment]
@yuche 是这样的.

我把 react 从 devDependencies 里排除掉了, peerDependencies 里也没写 react.
并且这个 UI 也没有打包, 只是使用 tsc 编译了一下.

**Comment by WangShuXian6** [comment]
楼主解决了吗？我也遇到了。刚新建了空项目，就是这样报错。首次编译正常，改动以下代码就报错。

**Comment by cncolder** [comment]
@WangShuXian6 等 beta4

**Comment by ionush** [comment]
@cncolder when is beta4 coming?

**Comment by charmtiger** [comment]
insert a eye，wait 4

**Comment by yuche** [comment]
> @cncolder when is beta4 coming?

Today.

**Comment by ionush** [comment]
@yuche this still is broken in beta4

**Comment by ionush** [comment]
@yuche beta5 also didn't fix this

**Comment by yuche** [comment]
> @luckyadam beta5 also didn't fix this

repro with a demo and open a new issue
