### ISSUE TITLE
mini-runner-覆盖原有webpack配置，编译后会出现多余层级，导致页面引入失败，并且dev和build模式表现不一致

### ISSUE THREAD

**Issue by kiko111** [NervJS/taro#5928]
### 问题描述

覆盖原有webpack配置，编译后会出现多余层级，导致页面引入失败
同时cachegroup优先级未生效，会出现重复打包的情况

再加一个问题：common.js dev模式下没有抽取公共样式，build模式抽取了，导致前后样式不一致
如果要禁止抽取样式，又需要复写默认配置，复写之后组件层级又会失效……
taro: 2.1.0
mini-runner: 2.1.2
### 复现步骤

1. 配置代码

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
    webpackChain (chain, webpack) {
      chain.plugin('analyzer')
        .use(require('webpack-bundle-analyzer').BundleAnalyzerPlugin, [])
        chain.merge({
          optimization: {
            runtimeChunk: {
              name: 'runtime'
            },
            splitChunks: {
              chunks: 'all',
              maxInitialRequests: Infinity,
              minSize: 0,
              cacheGroups: {
                poiComps: {
                  name: 'poiComps',
                  minChunks: 1,
                  test: module => {
                    // 如果需要自定义配置，PARSE_AST_TYPE 可以从 webpackChain 第三个参数获得
                    //return /[\\/]node_modules[\\/]/.test(module.resource) && module.miniType !== PARSE_AST_TYPE.COMPONENT
                    return /[\\/]poiComps[\\/]/.test(module.resource) && /[\\/]src[\\/]/.test(module.resource)
                  },
                  priority: 500
                },
                common: {
                  name: !!config.isBuildPlugin ? 'plugin/common' : 'common',
                  minChunks: 2,
                  priority: 1,
                  test: module => {
                  // 如果需要自定义配置，PARSE_AST_TYPE 可以从 webpackChain 第三个参数获得
                  //return /[\\/]node_modules[\\/]/.test(module.resource) && module.miniType !== PARSE_AST_TYPE.COMPONENT
                  // console.log(module.resource,'8888')
                  // console.log(/[\\/]node_modules[\\/]/.test(module.resource) )
                  // console.log(!(/[\\/]src[\\/]/.test(module.resource)))
                  // console.log(!(/\.scss$/.test(module.resource)))
                  return !(/\.scss$/.test(module.resource)) && !/[\\/]poiComps[\\/]/.test(module.resource) 
                },
              },
              }
            }
          }
        })
    },
 */


```
2 出现多余层级
该组件原本包含estimateCard.tsx, index.tsx, index.scss三个文件
编译之后多了一个层级
![image](https://user-images.githubusercontent.com/16315049/78873564-a66ec780-7a7d-11ea-861b-422944f743be.png)

3 出现重复打包
![image](https://user-images.githubusercontent.com/16315049/78873540-9e168c80-7a7d-11ea-9a95-cef2d8b782b0.png)

poiComps已经被抽取到一个单独的文件中，common.js里仍然引入了

4、dev和build 表现不一致
dev没有抽取样式
![image](https://user-images.githubusercontent.com/16315049/78876482-fbacd800-7a81-11ea-9152-33fbb6c28810.png)

build抽取了样式
![image](https://user-images.githubusercontent.com/16315049/78876529-0d8e7b00-7a82-11ea-9c77-7e5058d4aa22.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
配置有问题
![image](https://user-images.githubusercontent.com/1782542/78956523-2136f180-7b15-11ea-9f5b-c007290cd5ba.png)
这里配置排除样式，但事实上样式一定会经过 splitChunkPlugin 处理，这里如果你想改配置，请根据 webpack 文档再做调整。

如果是因为公共样式的问题，请升级到 2.1.3 试试

![image](https://user-images.githubusercontent.com/1782542/78956645-812d9800-7b15-11ea-9ae5-87272e404c87.png)

**Comment by kiko111** [comment]
> 配置有问题
> ![image](https://user-images.githubusercontent.com/1782542/78956523-2136f180-7b15-11ea-9f5b-c007290cd5ba.png)
> 这里配置排除样式，但事实上样式一定会经过 splitChunkPlugin 处理，这里如果你想改配置，请根据 webpack 文档再做调整。
> 
> 如果是因为公共样式的问题，请升级到 2.1.3 试试
> 
> ![image](https://user-images.githubusercontent.com/1782542/78956645-812d9800-7b15-11ea-9ae5-87272e404c87.png)



> 配置有问题
> ![image](https://user-images.githubusercontent.com/1782542/78956523-2136f180-7b15-11ea-9f5b-c007290cd5ba.png)
> 这里配置排除样式，但事实上样式一定会经过 splitChunkPlugin 处理，这里如果你想改配置，请根据 webpack 文档再做调整。
> 
> 如果是因为公共样式的问题，请升级到 2.1.3 试试
> 
> ![image](https://user-images.githubusercontent.com/1782542/78956645-812d9800-7b15-11ea-9ae5-87272e404c87.png)
好的，谢谢
第二个问题呢，复写默认配置后，编译组件出现了多余层级导致页面引入路径错误

**Comment by kiko111** [comment]
好的，谢谢，
第二个问题呢，修改默认配置之后组件出现多余层级导致页面引入路径失效的问题

**Comment by kiko111** [comment]
好的，谢谢，
第二个问题呢，修改默认配置之后组件出现多余层级导致页面引入路径失效的问题

**Comment by kiko111** [comment]
> 配置有问题

> 这里配置排除样式，但事实上样式一定会经过 splitChunkPlugin 处理，这里如果你想改配置，请根据 webpack 文档再做调整。
> 
> 如果是因为公共样式的问题，请升级到 2.1.3 试试
> 





好的，谢谢，
第二个问题呢，修改默认配置之后组件出现多余层级导致页面引入路径失效的问题

**Comment by cyq333** [comment]
重复打包的问题有解决吗？我也出现了这个问题
