### ISSUE TITLE
全局安装 taro-cli  fsevents 报错

### ISSUE THREAD

**Issue by perseveringman** [NervJS/taro#5929]
### 问题描述
<img width="796" alt="屏幕快照 2020-04-09 下午4 40 23" src="https://user-images.githubusercontent.com/17445000/78875694-de2b3e80-7a80-11ea-8f13-789358f4423b.png">

https://github.com/fsevents/fsevents/issues/302

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@perseveringman 请在nodejs里面使用这个模块。小程序其实是编译好的，不会调用nodejs的模块
