### ISSUE TITLE
h5 端的 config.navigationBarTitleText 不生效

### ISSUE THREAD

**Issue by lkspc** [NervJS/taro#593]
**问题描述**

h5端配置 config.navigationBarTitleText 浏览器标题还是没有变化，之前有提过这个问题，但是好像还是没有处理到。

另外，从 A 标题前进到 B 标题，再后退时 title 并不会还原，希望可以加入 document.title 的 hook 集成在 Component 里面，思路如下：
```js
componentWillMount(){
  this.previousTitle = document.title;
  document.title = this.config.navigationBarTitleText;
}

componentWillUnmount() {
  document.title = this.previousTitle;
}
```

**Comment by Littly** [comment]
已支持 https://github.com/NervJS/taro/commit/69d5d060afeaa888b6a33977c7eee991efc7ca97
