### ISSUE TITLE
h5 跳转tabbar页面出现原页面没有隐藏，原页面和tabbar页面同时出现

### ISSUE THREAD

**Issue by songyizhe** [NervJS/taro#5930]
### 问题描述
h5 从非tabbar页面跳转tabbar页面出现原页面没有隐藏，原页面和tabbar页面同时出现

### 复现步骤
h5 从非tabbar页面跳转tabbar页面出现原页面没有隐藏，原页面和tabbar页面同时出现
![微信截图_20200409164940](https://user-images.githubusercontent.com/46926047/78876853-8ab9f000-7a82-11ea-8470-d80c77992b75.png)

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
可以正常跳转

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by songyizhe** [comment]
![微信截图_20200409164940](https://user-images.githubusercontent.com/46926047/78877141-fac87600-7a82-11ea-938d-d47c919cdce0.png)

**Comment by ZakaryCode** [comment]
具体是哪个版本

**Comment by songyizhe** [comment]
> 具体是哪个版本

1.3.22

**Comment by ZakaryCode** [comment]
可以升级版本试试哈，还有你具体是怎么操作的，是在普通页面 navigateTo 到Tabbar页面么？

**Comment by songyizhe** [comment]
> 可以升级版本试试哈，还有你具体是怎么操作的，是在普通页面 navigateTo 到Tabbar页面么？
普通页面 navigateTo 到Tabbar页面会出现这个情况，现在我临时在success回调加了个刷新页面临时解决问题。。

**Comment by ZakaryCode** [comment]
这样的操作不建议使用，而且后续版本中也会和微信保持一致

https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.navigateTo.html

**Comment by songyizhe** [comment]
> 这样的操作不建议使用，而且后续版本中也会和微信保持一致
> 
> https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.navigateTo.html

好的，明天我试着升下级

**Comment by laihangji** [comment]
我也遇到了这个问题 如果不能解决只能自己创建tabbar了试试看了 版本是2.1.3

**Comment by Ling2048** [comment]
2.1.4同样的问题，在page跳转到tabbar page时
![taro](https://user-images.githubusercontent.com/24432014/79191060-52d2f400-7e58-11ea-8432-4fdd15845cf9.gif)

**Comment by Ling2048** [comment]
在1.3.9中没有这个问题

**Comment by liuhuapiaoyuan** [comment]
同样的问题，我是2.1.5以及2.2.2 都有这样的问题

**Comment by Bravo123** [comment]
同样的问题，tabbar page -> page， page 刷新一下，switchTab到tabbar，页面同时存在。

**Comment by janlycn** [comment]
2.2.3 使用 switchTab 有同样问题，原页面和tabbar页面同时出现

存在多个未隐藏的 taro_page，如下图：
![image](https://user-images.githubusercontent.com/39581938/81519211-0c978480-9373-11ea-8846-9c624df0b4f1.png)

```
Taro CLI 2.2.3 environment info:
    System:
      OS: macOS High Sierra 10.13.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/components-qa: 2.2.3 => 2.2.3 
      @tarojs/mini-runner: 2.2.3 => 2.2.3 
      @tarojs/mobx: 2.2.3 => 2.2.3 
      @tarojs/mobx-h5: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3 
      taro-ui: ^2.3.3 => 2.3.3 
```

**Comment by janlycn** [comment]
@songyizhe

**Comment by HitsiLent** [comment]
> 2.2.3 使用 switchTab 有同样问题，原页面和tabbar页面同时出现
> 
> 存在多个未隐藏的 taro_page，如下图：
> ![image](https://user-images.githubusercontent.com/39581938/81519211-0c978480-9373-11ea-8846-9c624df0b4f1.png)
> 
> ```
> Taro CLI 2.2.3 environment info:
>     System:
>       OS: macOS High Sierra 10.13.1
>       Shell: 5.3 - /bin/zsh
>     Binaries:
>       Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
>       Yarn: 1.12.3 - /usr/local/bin/yarn
>       npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
>     npmPackages:
>       @tarojs/components: 2.2.3 => 2.2.3 
>       @tarojs/components-qa: 2.2.3 => 2.2.3 
>       @tarojs/mini-runner: 2.2.3 => 2.2.3 
>       @tarojs/mobx: 2.2.3 => 2.2.3 
>       @tarojs/mobx-h5: 2.2.3 => 2.2.3 
>       @tarojs/router: 2.2.3 => 2.2.3 
>       @tarojs/taro: 2.2.3 => 2.2.3 
>       @tarojs/taro-alipay: 2.2.3 => 2.2.3 
>       @tarojs/taro-h5: 2.2.3 => 2.2.3 
>       @tarojs/taro-qq: 2.2.3 => 2.2.3 
>       @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
>       @tarojs/taro-swan: 2.2.3 => 2.2.3 
>       @tarojs/taro-tt: 2.2.3 => 2.2.3 
>       @tarojs/taro-weapp: 2.2.3 => 2.2.3 
>       @tarojs/webpack-runner: 2.2.3 => 2.2.3 
>       eslint-config-taro: 2.2.3 => 2.2.3 
>       eslint-plugin-taro: 2.2.3 => 2.2.3 
>       nerv-devtools: ^1.5.6 => 1.5.6 
>       nervjs: ^1.5.6 => 1.5.6 
>       stylelint-config-taro-rn: 2.2.3 => 2.2.3 
>       stylelint-taro-rn: 2.2.3 => 2.2.3 
>       taro-ui: ^2.3.3 => 2.3.3 
> ```

同样遇到一摸一样问题，1.3版本没有问题，升级到所有2.X版本有问题，我还是准备滚回区1.3了

**Comment by janlycn** [comment]
> 同样遇到一摸一样问题，1.3版本没有问题，升级到所有2.X版本有问题，我还是准备滚回区1.3了

不要冲动，判断h5下跳转完reload一下就行

**Comment by HitsiLent** [comment]
> > 同样遇到一摸一样问题，1.3版本没有问题，升级到所有2.X版本有问题，我还是准备滚回区1.3了
> 
> 不要冲动，判断h5下跳转完reload一下就行

这是非常严重的BUG问题，经测试，2.0.3，和1.3.37，是没问题的，升级到2.2.2或者1.3.40问题出现。

**Comment by sakurahe** [comment]
Taro v2.2.6 出现类似的问题
h5从TabBar页面进入其他页面后，然后刷新页面，点击返回，然后切换TabBar，2个TabBar页面会出现重叠现象（该问题必现）

**Comment by NUMLOCK0** [comment]
我更新到2.2.13版本还是有问题？怎么解决？

**Comment by sakurahe** [comment]
@NUMLOCK0 试一下2.2.8版本，记得2.2.8好像没这个问题

**Comment by melunar** [comment]
也没说解决没有 issues就 cloesed？

**Comment by sakurahe** [comment]
@melunar https://github.com/NervJS/taro/issues/6657

**Comment by sakurahe** [comment]
上面记错了，2.2.8是当时测试有问题的版本，升级到2.2.9没问题，现在最新版本有没有这个问题，我也不清楚了
