### ISSUE TITLE
cli 升级到2.1.2报错Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by mrTangYun** [NervJS/taro#5931]
### 问题描述

taro2.0.7 升级到 2.1.2后，运行taro相关命令，报错Cannot find module '@babel/core' 

### 复现步骤

1. 运行yarn global add @tarojs/cli   升级到2.1.2
2. 运行taro info

### 报错信息

Cannot find module '@babel/core' 

### 补充信息

运行 yarn global add @babel/core 可修复

**Comment by luckyadam** [comment]
升级到 2.1.3
