### ISSUE TITLE
Form 能获取到自定义表单组件的 name 但是没有值

### ISSUE THREAD

**Issue by afishhhhh** [NervJS/taro#5932]
### 问题描述
```js
// Textinput.jsx
static behaviors = ['wx://form-field']
static defaultProps = {
  title: '',
  name: '',
  value: ''
}

<View className='text-input'>
  <Text className='label'>{title}</Text>
  <Input name={name} value={value} />
</View>

// page.jsx
<Form onSubmit={this.handleSubmit}>
  <TextInput title='标题' name='test' />
</Form>
```

在 `handleSubmit` 里获取的 `value` 是 `{ test: '' }`，不管输了什么值，`test` 永远是空字符串

### 系统信息

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.11.2 - /usr/local/bin/npm

**Comment by mihuartuanr** [comment]
请问，目前这个找到解决方案了么

**Comment by afishhhhh** [comment]
> 请问，目前这个找到解决方案了么

没有，用 state

**Comment by mihuartuanr** [comment]
😯我是循环的，改成`static behaviors = ['wx://form-field-group']`是可以的，你这里只是单个，不知道换成group可不可以

**Comment by afishhhhh** [comment]
> 😯我是循环的，改成`static behaviors = ['wx://form-field-group']`是可以的，你这里只是单个，不知道换成group可不可以

我只是 demo 写了单个，我看了下 `form-field-group` 要基础库 2.10.2，还是得兼容

**Comment by Chen-jj** [comment]
@afishhhhh @mihuartuanr 你们需要在输入时设置 value

![image](https://user-images.githubusercontent.com/11807297/80862297-6ed2f400-8ca6-11ea-8475-6dd5f2ab5f47.png)
