### ISSUE TITLE
taro 2.1.3 编译h5 失败

### ISSUE THREAD

**Issue by tonygshliu** [NervJS/taro#5933]
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   **config = {**
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index", "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],
  128 |     window: {
  129 |       backgroundTextStyle: 'light',

C02R80C7FVH5:taro-music liugensheng944$ taro info
👽 Taro v2.1.3

  Taro CLI 2.1.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.1.3 => 2.1.3 
      @tarojs/components: 2.1.3 => 2.1.3 
      @tarojs/mini-runner: 2.1.3 => 2.1.3 
      @tarojs/plugin-babel: 2.1.3 => 2.1.3 
      @tarojs/plugin-csso: 2.1.3 => 2.1.3 
      @tarojs/plugin-less: 2.1.3 => 2.1.3 
      @tarojs/plugin-sass: 2.1.3 => 2.1.3 
      @tarojs/plugin-uglifyjs: 2.1.3 => 2.1.3 
      @tarojs/redux: 2.1.3 => 2.1.3 
      @tarojs/redux-h5: 2.1.3 => 2.1.3 
      @tarojs/router: 2.1.3 => 2.1.3 
      @tarojs/taro: 2.1.3 => 2.1.3 
      @tarojs/taro-alipay: 2.1.3 => 2.1.3 
      @tarojs/taro-h5: 2.1.3 => 2.1.3 
      @tarojs/taro-swan: 2.1.3 => 2.1.3 
      @tarojs/taro-tt: 2.1.3 => 2.1.3 
      @tarojs/taro-weapp: 2.1.3 => 2.1.3 
      @tarojs/webpack-runner: 2.1.3 => 2.1.3 
      eslint-config-taro: 2.1.3 => 2.1.3 
      eslint-plugin-taro: 2.1.3 => 2.1.3 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      taro-ui: ^2.2.2 => 2.3.2 
    npmGlobalPackages:
      typescript: 3.8.3

**Comment by luckyadam** [comment]
http://taro-docs.jd.com/taro/docs/migrate-to-2.html
![image](https://user-images.githubusercontent.com/1782542/78894925-8bfa1580-7aa0-11ea-9550-9b1186edc3d1.png)

**Comment by tonygshliu** [comment]
已经按照这份迁移文档进行taro 升级到2.1.3.
babel配置：
babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }]
     
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread'
      ]
    }


h5配置：
h5: {
    publicPath: '/',
    staticDirectory: 'static',
    webpackChain (chain, webpack) {},
    module: {
      postcss: {
        autoprefixer: {
          enable: true,
          config: {
            browsers: [
              'last 3 versions',
              'Android >= 4.1',
              'ios >= 8'
            ]
          }
        },
        cssModules: {
          enable: false, // 默认为 false，如需使用 css modules 功能，则设为 true
          config: {
            namingPattern: 'module', // 转换模式，取值为 global/module
            generateScopedName: '[name]__[local]___[hash:base64:5]'
          }
        }
      }
    }
  }


原始文件为：
class App extends Component {

  /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
   config: Config = {
    pages: [
      'pages/index/index',
      'pages/dailyRecommend/index',
      'pages/my/index',
      'pages/videoDetail/index',
      'pages/search/index',
      'pages/user/index',
      'pages/djprogramListDetail/index',
      'pages/searchResult/index', 
      'pages/songDetail/index',
      'pages/myFans/index',
      'pages/myFocus/index',
      'pages/myEvents/index',
      'pages/login/index',
      'pages/playListDetail/index',
      'pages/recentPlay/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#d43c33',      
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'white'
    },
    requiredBackgroundModes: ["audio"]
  }

  componentDidMount () {}

  componentDidShow () {}

  componentDidHide () {}

  componentCatchError () {}

  componentDidCatchError () {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render () {
    return (
      <Provider store={store}>
        <AppContainer />
      </Provider>
    )
  }
}

Taro.render(<App />, document.getElementById('app'))


编译结果：
 Failed to compile.

./.temp/app.js
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (126:9)

  124 |         </Provider>;
  125 |   }
> 126 |   config = {
      |          ^
  127 |     pages: ["/pages/index/index", "/pages/dailyRecommend/index", "/pages/my/index", "/pages/videoDetail/index", "/pages/search/index", "/pages/user/index", "/pages/djprogramListDetail/index", "/pages/searchResult/index", "/pages/songDetail/index", "/pages/myFans/index", "/pages/myFocus/index", "/pages/myEvents/index", "/pages/login/index", "/pages/playListDetail/index", "/pages/recentPlay/index"],
  128 |     window: {
  129 |       backgroundTextStyle: 'light',

**Comment by luckyadam** [comment]
2 个原因，1 配置问题，2 依赖安装问题

**Comment by tonygshliu** [comment]
调整了babel配置就好了。谢谢。
