### ISSUE TITLE
usingComponents 引入微信【小程序直播】订阅组件  提示”包未安装“

### ISSUE THREAD

**Issue by mrcuix** [NervJS/taro#5936]
### 问题描述

使用Taro 引入微信小程序直播订阅组后，提示 

```
🙅   编译失败.
包 plugin-private://wx2b03c6e691cd7370/components/subscribe/subscribe 未安装
```

- [x]  appid 有权限使用【小程序直播】
- [x] 已开通微信【小程序直播】权限、并在小程序后台添加直播组件
- [x] 使用原生微信小程序编写可正常调用【小程序直播】组件、【订阅】组件

----

1. 根据微信官方 【小程序直播】 接入指引
[https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/live-player-plugin.html](https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/live-player-plugin.html)

2. 根据Taro 官方文档  【使用小程序原生第三方组件和插件】
[https://nervjs.github.io/taro/docs/mini-third-party.html](https://nervjs.github.io/taro/docs/mini-third-party.html)

----

### 复现步骤

目录结构
```
src
  pages/live/page/liveList/liveList.jsx   
  app.jsx
```

1. src/app.jsx
```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


// src/app.jsx
class App extends Component {

  config = {
    pages: [
      'pages/index/index'
    ],
    subPackages: [
      {
        root: 'pages/live',
        pages: [
          'page/liveList/liveList',
        ]
      }
    ],
    plugins: {
      'live-player-plugin': {
        'version': '1.0.6', // 注意填写该直播组件最新版本号，微信开发者工具调试时可获取最新版本号
        'provider': 'wx2b03c6e691cd7370' // 必须填该直播组件appid，该示例值即为直播组件appid
      }
    },
  }

  ...
}

```

2. src/pages/live/page/liveList/liveList.jsx
```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


// src/pages/live/page/liveList/liveList.jsx
class LiveList extends Component {
  config = {
    navigationBarTitleText: '直播广场',
    usingComponents: {
      'subscribe': 'plugin-private://wx2b03c6e691cd7370/components/subscribe/subscribe'
    }
  }

  state = {
    roomId: 8
  }

  render() {
    const { roomId } = this.state
    return (
      <View className='live-lsit'>
        {/* 这里调用微信小程序直播的 订阅组件 */}
        <subscribe room-id={roomId}></subscribe>
      </View>
    )
  }
}


```

### 期望行为

能够正常引用微信【小程序直播】的 【订阅组件】并编译不报错
1. yarn dev:weapp
2. yarn build:weapp

### 报错信息

```
// 执行
yarn dev:weapp

🙅   编译失败.

包 plugin-private://wx2b03c6e691cd7370/components/subscribe/subscribe 未安装
```

```
// 执行
yarn build:weapp

🙅   编译失败.

包 plugin-private://wx2b03c6e691cd7370/components/subscribe/subscribe 未安装

error Command failed with exit code 1.
```

### 系统信息

  Taro CLI 2.1.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.10.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.7 => 2.1.1
      @tarojs/components-qa: 2.0.7 => 2.1.1
      @tarojs/mini-runner: 2.0.7 => 2.1.1
      @tarojs/mobx: 2.0.7 => 2.1.1
      @tarojs/mobx-h5: 2.0.7 => 2.1.1
      @tarojs/router: 2.0.7 => 2.1.1
      @tarojs/taro: 2.0.7 => 2.1.1
      @tarojs/taro-alipay: 2.0.7 => 2.1.1
      @tarojs/taro-h5: 2.0.7 => 2.1.1
      @tarojs/taro-qq: 2.0.7 => 2.1.1
      @tarojs/taro-quickapp: 2.0.7 => 2.1.1
      @tarojs/taro-swan: 2.0.7 => 2.1.1
      @tarojs/taro-tt: 2.0.7 => 2.1.1
      @tarojs/taro-weapp: 2.0.7 => 2.1.1
      @tarojs/webpack-runner: 2.0.6 => 2.1.1
      eslint-config-taro: 2.0.7 => 2.1.1
      eslint-plugin-taro: 2.0.7 => 2.1.1
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.0.7 => 2.1.1
      stylelint-taro-rn: 2.0.7 => 2.1.1
      taro-ui: ^2.2.4 => 2.3.0

### 补充信息

编译 没有考虑原生组件？ 
下面是在当前库搜到相关的代码部分？
[https://github.com/NervJS/taro/blob/16a3532b8293e675a85c5c99abe16c3a79e16ce4/packages/taro-mini-runner/src/utils/index.ts#L197](https://github.com/NervJS/taro/blob/16a3532b8293e675a85c5c99abe16c3a79e16ce4/packages/taro-mini-runner/src/utils/index.ts#L197)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by OwOzZ** [comment]
所以这个问题解决了么

**Comment by rogerchengithub** [comment]
这个问题有解决吗，我也遇到了问题

**Comment by shengbowen** [comment]
可以搜一下 transformComponentsPath  这个方法，将
depComponents = depComponents.filter(item => !/^plugin:\/\//.test(item.path));
改成
depComponents = depComponents.filter(item => !/^(plugin|plugin-private):\/\//.test(item.path));
来跳过路径检查，其他第三方包，如百度小程序的dynamicLib ，同样操作一下就可以了。
