### ISSUE TITLE
taro2.1.3编译成h5后，useRouter 收不到params了

### ISSUE THREAD

**Issue by mrTangYun** [NervJS/taro#5943]
### 问题描述

升级到taro2.1.3编译成h5后，useRouter 收不到params了

### 复现步骤
1. 打开http://192.168.1.157:10086/#/pages/chat/index?uid=5e82d0d69a3ad0001fe0a2c

```
const router = useRouter();
console.log(router);
```

### 期望行为

能获取router的params属性

### 报错信息

path: undefined
scene: 1000
params: undefined

### 系统信息

� Taro v2.1.3

  Taro CLI 2.1.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 13.10.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.7 - D:\Program Files\nodejs\npm.CMD

### 补充信息
在2.0.7是好的，升级到2.1.3后，除了常规的改动，另外一个比较大的改动是进行了分包配置，不知道是哪个行为有影响

**Comment by muguatech** [comment]
同样遇到该问题
class组件写法
componentWillMount、componentDidMount、componentDidShow 中 this.$router.params 均为 undefined 。

**Comment by AshoneA** [comment]
+1

**Comment by Xwatson** [comment]
class组件this.$router一样拿不到params

**Comment by laihangji** [comment]
同问 下一个版本会解决好吗

**Comment by jeffwcx** [comment]
2.1.4已经修复了，大家可以更新解决了

**Comment by mrTangYun** [comment]
> 2.1.4已经修复了，大家可以更新解决了

的确修复了。但我遇到其它的问题，页面的第二次第三次（.....）跳转，都只显示第一次跳转的页面内容，回退到2.0.7是好的。

**Comment by jeffwcx** [comment]
@mrTangYun  是的，似乎页面缓存这块又出问题了

![image](https://user-images.githubusercontent.com/14073775/79293115-65efcd80-7f05-11ea-9c43-066d92f43a86.png)

**Comment by kinsui** [comment]
> > 2.1.4已经修复了，大家可以更新解决了
> 
> 的确修复了。但我遇到其它的问题，页面的第二次第三次（.....）跳转，都只显示第一次跳转的页面内容，回退到2.0.7是好的。

+1,这个问题实在太严重了，直接导致业务不可用，感到心累。。。。。

**Comment by ZakaryCode** [comment]
> > 2.1.4已经修复了，大家可以更新解决了
> 
> 的确修复了。但我遇到其它的问题，页面的第二次第三次（.....）跳转，都只显示第一次跳转的页面内容，回退到2.0.7是好的。

未能复现该问题，如果可能的话还是希望能提供一个 demo

**Comment by ZakaryCode** [comment]
> > > 2.1.4已经修复了，大家可以更新解决了
> > 
> > 
> > 的确修复了。但我遇到其它的问题，页面的第二次第三次（.....）跳转，都只显示第一次跳转的页面内容，回退到2.0.7是好的。
> 
> +1，我是回退到2.1.1，目前可用，但是2.1.4修复的previewImage点击返回键导致页面返回而预览图依旧展示的bug也很重要TnT
> @Littly 页面跳转$router未更新这个问题实在太严重了，直接导致业务不可用，麻烦尽快修复~
> 测试发现navigateTo路由正常更新，redirectTo则会出问题

redirectTo 方法导致的 $router 未更新问题可以通过 getApp 方法获取当前页面的 $router，而不是使用 getCurrentPages 方法

> 该问题将在下一版本修复

**Comment by kinsui** [comment]
> > > > 2.1.4已经修复了，大家可以更新解决了
> > > 
> > > 
> > > 的确修复了。但我遇到其它的问题，页面的第二次第三次（.....）跳转，都只显示第一次跳转的页面内容，回退到2.0.7是好的。
> > 
> > 
> > +1，我是回退到2.1.1，目前可用，但是2.1.4修复的previewImage点击返回键导致页面返回而预览图依旧展示的bug也很重要TnT
> > @Littly 页面跳转$router未更新这个问题实在太严重了，直接导致业务不可用，麻烦尽快修复~
> > 测试发现navigateTo路由正常更新，redirectTo则会出问题
> 
> redirectTo 方法导致的 $router 未更新问题可以通过 getApp 方法获取当前页面的 $router，而不是使用 getCurrentPages 方法
> 
> > 该问题将在下一版本修复

通过getApp的方法确实可以拿到，感谢。ps:我是通过this.$router拿的不是getCurrentPages 方法。
