### ISSUE TITLE
微信小程序 canvasId在Canvas 2D可空

### ISSUE THREAD

**Issue by Anberm** [NervJS/taro#5944]
### 问题描述

在微信2.9.0 起支持 Canvas 2D 接口，canvasId是可为空的，建议更新相应的type
https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
是否设置 type 会影响 Canvas 新旧版本 API 是否可用，还是以最兼容的方式，不设置 type，让开发者自行设置吧。

#7314
