### ISSUE TITLE
taro@3.0.0-beta.3 开启css modules编译报错

### ISSUE THREAD

**Issue by windego** [NervJS/taro#5947]
### 问题描述
taro@3.0.0-beta.3 开启css modules编译报错

### 复现步骤

1. 
按官方文档配置css modules后
![image](https://user-images.githubusercontent.com/60835477/79030863-c7463280-7bcd-11ea-8dc2-9fbf87662c3f.png)

2. 
h5方式启动,报错
![image](https://user-images.githubusercontent.com/60835477/79030905-f8266780-7bcd-11ea-8ebb-0da3a396bcca.png)
3. 
查看webpack-runner/utils/chain.js文件
![image](https://user-images.githubusercontent.com/60835477/79030931-1e4c0780-7bce-11ea-83f8-800dcf355838.png)

dependencies中  "css-loader": "3.4.2",
4. 
css-loader从3.0.0版本开始，locaIdentName配置项的位置做了调整，由原来与modules同级调整为了modules下的一个属性。
请修改

**Comment by windego** [comment]
11

**Comment by everything8** [comment]
怎么解决的？我也遇到了同样的问题
