### ISSUE TITLE
默认生成的项目模版eslint报错误

### ISSUE THREAD

**Issue by jifeilong9** [NervJS/taro#5949]
### 问题描述

新建模版项目后在vscode中打开代码无法通过eslint检查，报语法错误（.eslintrc未做修改）

### 复现步骤

1、新建项目用vscode打开项目
2、打开src/page/index.tsx即可看到红色下划线

![image](https://user-images.githubusercontent.com/24316291/79043404-8ed84000-7c31-11ea-8e99-f2bf16019200.png)

**Comment by cmlingyi** [comment]
同样的问题
