### ISSUE TITLE
setState的异步问题

### ISSUE THREAD

**Issue by funky-tiger** [NervJS/taro#595]
**问题描述**
[问题描述：setState的异步更新数据 导致页面没有及时刷新
**复现步骤**
1 页面onPageScroll监滚动实现fixed定位 

2 当达到滚动条件时setState一个变量为true 

3 setState一个变量为true时实现fixed固定定位

4 因为setState的异步问题 即使执行了setSate 页面也不会立即更新 导致需要滚动多次才能实现fixed定位

```js：
if (e.scrollTop >= this.state.chose_scroll_top){

      this.setState({isFixed:true})

    }else{

      this.setState({ isFixed: false })

    }
```

**期望行为**
期望setState后立即更新视图 实现fixed定位

**报错信息**
无报错

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.0.0-beta.22]
 - Node.js 版本 [e.g. v8.11.3]

**补充信息**
根据是setState异步刷新数据的问题 而且根据我的需求 我也不能在setState里面的回调函数里面去写逻辑

**Comment by luckyadam** [comment]
`setState` 虽然是异步的，但是会去更新视图，这里在滚动里不停 `setState` 的方式不推荐，建议考虑别的写法
