### ISSUE TITLE
3.0.0-beta.3版本vue+typescript版本模板问题

### ISSUE THREAD

**Issue by yangdan8** [NervJS/taro#5950]
### 复现步骤

漏了定义Vue的构造函数参数新增的方法导致直接报错
onShow (options) {   },

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@yangdan8 编译到哪个端报错？请提供详细的复现步骤和报错信息
