### ISSUE TITLE
ec-canvas在分包内使用和存放 最终占用的是主包的大小 请问是什么情况 旧版本同样写法没有问题

### ISSUE THREAD

**Issue by lzt9977** [NervJS/taro#5951]
### 问题描述

ec-canvas在分包内使用和存放 最终占用的是主包的大小 请问是什么情况 旧版本同样写法没有问题

![image](https://user-images.githubusercontent.com/23352892/79046194-01e9b280-7c42-11ea-838b-5872e133452d.png)

目前大小

![image](https://user-images.githubusercontent.com/23352892/79046354-0fec0300-7c43-11ea-82a7-665b1a0a5370.png)

插件代码存放在packageUser里面 并且只在分包内使用了该插件

如果我删掉这个插件，那么主包的大小就变为

![image](https://user-images.githubusercontent.com/23352892/79046434-84bf3d00-7c43-11ea-913c-44d6d30aa9c5.png)

很明显是占用了主包的大小 请问怎么解决或者优化 谢谢🙏

### 期望行为

想问一下该怎么解决，如此做法在之前1.3.5左右的版本是可以的。现在大小算到了主包 难受啊

请问怎么优化

### 系统信息

 Taro v2.0.7

  Taro CLI 2.0.7 environment info:
    System:
      OS: macOS High Sierra 10.13.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by lzt9977** [comment]
补充： 想解决的就是 让该组件只占用分包的大小  别跑到主包  之前的版本同样的写法 就是只用分包的大小

**Comment by lzt9977** [comment]
大佬们求助啊

**Comment by luckyadam** [comment]
如果它被主包引用到了就会计入主包大小，可以尝试用这个配置解决https://nervjs.github.io/taro/docs/config-detail.html#miniaddchunkpages
