### ISSUE TITLE
input focus首次可以

### ISSUE THREAD

**Issue by nuo1693** [NervJS/taro#5954]
首次聚焦可以唤起键盘，再第二次之后focus=true就不行了

**Comment by MengQingJunzz** [comment]
@nuo1693  你的是什么版本？我的第一次都不好使

**Comment by nuo1693** [comment]
taro版本还是？
taro:2.1.0
系统:win7,macOS10.15.4
都不行，就很奇怪，只能通过把input绝对定位到上面，然后点击聚焦，目前好像就只有这一个做法

**Comment by nuo1693** [comment]
> @nuo1693 你的是什么版本？我的第一次都不好使

taro版本还是？
taro:2.1.0
系统:win7,macOS10.15.4
都不行，就很奇怪，只能通过把input绝对定位到上面，然后点击聚焦，目前好像就只有这一个做法

**Comment by nuo1693** [comment]
> > @nuo1693 你的是什么版本？我的第一次都不好使
> 
> taro版本还是？
> taro:2.1.0
> 系统:win7,macOS10.15.4
> 都不行，就很奇怪，只能通过把input绝对定位到上面，然后点击聚焦，目前好像就只有这一个做法



> @nuo1693 你的是什么版本？我的第一次都不好使

我的场景是写个输入密码的模态框，需要聚焦

**Comment by Littly** [comment]
h5 input 的 fucus 是使用 autofocus 属性实现的，只支持进入页面后第一次，后面会加强。
