### ISSUE TITLE
自定义组件根节点样式问题

### ISSUE THREAD

**Issue by myNameIsDu** [NervJS/taro#5958]
### 问题描述
给自定义组件的根节点设置样式，class className  style都不生效

### 复现步骤
![image](https://user-images.githubusercontent.com/53305259/79091251-27c8a180-7d7f-11ea-9674-2ef9e2db3d78.png)
这样会产生一个
![image](https://user-images.githubusercontent.com/53305259/79091295-534b8c00-7d7f-11ea-8d0a-fb40ba5ac792.png)
的jie'd节点 而此时需要使用一个自适应的布局，就需要给这个节点设置百分比样式

### 期望行为

![image](https://user-images.githubusercontent.com/53305259/79091481-01573600-7d80-11ea-96f3-bf498778532b.png)
下边的是prots-tabs 此时多出来一个根节点  就需要设置它的样式
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by cloudZQY** [comment]
小程序的自定义组件就是这样的吧，如果要自适应布局，可以在自定义组件外再包一层

**Comment by singletonPeople** [comment]
@cloudZQY 是的 目前是这样做了 谢谢
