### ISSUE TITLE
@tarojs/components中的picker组件在低版本的安卓Webview中无法正常使用

### ISSUE THREAD

**Issue by huyang2229** [NervJS/taro#5962]
### 问题描述

Taro所提供的picker组件在低版本的安卓Webivew中无法正常使用。

浏览器UA：Mozilla/5.0 (Linux; Android 5.1.1; vivo X7Plus Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

### 复现步骤

1. 点击picker唤起弹窗后，选择指定项点击确定无反应

### 期望行为
picker能够正常使用

### 报错信息

![image](https://user-images.githubusercontent.com/20263880/79098740-315d0400-7d95-11ea-92c4-f4e1eacdd06b.png)

定位原因发现不管picker选择哪一项，最终返回的事件对象中detail属性(e.detail)的值都为1，不是预期的结构(预期结构为e.detail = {value: xxx})，导致业务之中使用取值异常

### 系统信息

System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/cli: 1.3.19 => 1.3.19 
      @tarojs/components: 1.3.19 => 1.3.19 
      @tarojs/mobx: 1.3.19 => 1.3.19 
      @tarojs/mobx-h5: 1.3.19 => 1.3.19 
      @tarojs/mobx-rn: 1.3.19 => 1.3.19 
      @tarojs/plugin-babel: 1.3.19 => 1.3.19 
      @tarojs/plugin-csso: 1.3.19 => 1.3.19 
      @tarojs/plugin-sass: 1.3.19 => 1.3.19 
      @tarojs/plugin-uglifyjs: 1.3.19 => 1.3.19 
      @tarojs/rn-runner: 1.3.19 => 1.3.19 
      @tarojs/router: 1.3.19 => 1.3.19 
      @tarojs/taro: 1.3.19 => 1.3.19 
      @tarojs/taro-alipay: 1.3.19 => 1.3.19 
      @tarojs/taro-h5: 1.3.19 => 1.3.19 
      @tarojs/taro-swan: 1.3.19 => 1.3.19 
      @tarojs/taro-tt: 1.3.19 => 1.3.19 
      @tarojs/taro-weapp: 1.3.19 => 1.3.19 
      @tarojs/webpack-runner: 1.3.19 => 1.3.19 
      eslint-config-taro: 1.3.16 => 1.3.16 
      eslint-plugin-taro: 1.3.16 => 1.3.16 
      nerv-devtools: ^1.4.0 => 1.4.4 
      nervjs: ^1.4.0 => 1.4.4 
      stylelint-config-taro-rn: 1.3.19 => 1.3.19 
      stylelint-taro-rn: 1.3.19 => 1.3.19 
      taro-ui: ^2.2.1 => 2.2.2

浏览器UA：Mozilla/5.0 (Linux; Android 5.1.1; vivo X7Plus Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

**Comment by Garfield550** [comment]
可否编辑一下，补充你所遇到的问题

**Comment by huyang2229** [comment]
初步排查原因可能是在低版本特定浏览器中，事件对象中的detail属性为保留属性，不排除某些浏览器本身对这个属性有默认操作行为的可能性，翻阅[相关文档](https://www.w3schools.com/jsref/event_detail.asp)，发现event中的detail属性用来代表在短时间内点击的次数，不知道是否与我描述的问题有关。
