### ISSUE TITLE
2.1.3版本 dev 和 build 生成的wxss不一致

### ISSUE THREAD

**Issue by buffge** [NervJS/taro#5965]
### 问题描述

 dev时可以正确的生成wxss文件
 prod构建时 如果组件中引入了全局样式不会生效 会删除引入scss的那条语句
比如 componentA.tsx里引入了2个样式,一个组件特有, 一个全局样式
import style from '@sass/components/index/header.scss'
import '@/app.global.scss'
dev 编译是 生成的 Header.wxss如下
@import "../../common.wxss";
header.scss特有样式...

build 编译生成的 Header.wxss少了 @import "../../common.wxss"; 这行代码

### 复现步骤

1. yarn build:weapp
2. 运行小程序
3. 看见样式全乱了,所有组件引入全局样式都失效

```tsx
// Header.tsx
import style from '@sass/components/index/header.scss'
import '@/app.global.scss'// build:weapp时 这行代码失效

```

### 期望行为

 希望 yarn dev:weapp 和 yarn build:weapp 生成一致的内容

### 报错信息

没有报错信息

### 系统信息

 Taro CLI 2.1.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.6.0 - C:\Program Files\nodejs\npm.CMD

### 补充信息

我使用了 typescript 开发 ,开启了 css modules, 为global模式
common.wxss下多了许多组件或者页面特有的样式,而且 yarn build:weapp是 生成的common.wxss 没有被任何一个wxss引用
![image](https://user-images.githubusercontent.com/24917906/79108875-d550aa80-7da9-11ea-85d0-4a030655e8ef.png)

**Comment by buffge** [comment]
此用户与我遇到的问题一致.
https://github.com/NervJS/taro/issues/5562#issuecomment-612341692

**Comment by Lovely-wood** [comment]
> 此用户与我遇到的问题一致.
> [#5562 (comment)](https://github.com/NervJS/taro/issues/5562#issuecomment-612341692)

此用户与我遇到的问题一致.求解决方式

**Comment by Aliveing** [comment]
+1

**Comment by buffge** [comment]
我现在的做法是使用dev编译出dist,并使用小程序开发工具压缩上传

**Comment by magicshui** [comment]
遇到同样的问题；

**Comment by luckyadam** [comment]
已经修复，下个版本发布
