### ISSUE TITLE
Taro1.x , 2.x 版本能共存吗？

### ISSUE THREAD

**Issue by zjxpcyc** [NervJS/taro#5968]
### 问题描述

我本地有几个老项目，还在维护，版本是 1.x 的。现在需要新开一个项目。我打算用 2.1 版本。

请问怎么做到不能版本在同一个机器上共存。

我系统是 windows 的

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
@zjxpcyc 看一下 #5339 ，你可以在你的项目根目录安装taro-cli

**Comment by zjxpcyc** [comment]
thx
