### ISSUE TITLE
是否可以把webview控件在dev:h5端转换成iframe 打开其他link页面

### ISSUE THREAD

**Issue by eoocy** [NervJS/taro#5975]
### 问题描述

webview通过yarn dev:h5后页面报错，ReferenceError: WebView is not defined

我能理解h5本身没有webview控件，但是否可以把webview控件在h5端转换成iframe打开其他link页面？
现在我们公司的需求就是做一套h5页面，通过不同端的webview去展示h5。但是taro不支持浏览器h5的webview控件。

我想这个问题解决了，taro的通用性优点会更好，也符合taro多端兼容，多种方式兼容的战略发展。
开发者用起来也会更方便。

### 复现步骤

添加webview控件，src='https://baidu.com'
编译 yarn dev:h5

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

<View className='test'>
    <WebView src='https://baidu.com'/>
</View>

```

### 期望行为
webview控件在h5端也能打开其他link页面

### 报错信息

ReferenceError: WebView is not defined

### 系统信息

Taro CLI 2.1.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    npmPackages:
      @tarojs/components: 2.1.4 => 2.1.4 
      @tarojs/components-qa: 2.1.4 => 2.1.4 
      @tarojs/components-rn: 2.1.4 => 2.1.4 
      @tarojs/mini-runner: 2.1.4 => 2.1.4 
      @tarojs/mobx: 2.1.4 => 2.1.4 
      @tarojs/mobx-h5: 2.1.4 => 2.1.4 
      @tarojs/mobx-rn: 2.1.4 => 2.1.4 
      @tarojs/rn-runner: 2.1.4 => 2.1.4 
      @tarojs/router: 2.1.4 => 2.1.4 
      @tarojs/taro: 2.1.4 => 2.1.4 
      @tarojs/taro-alipay: 2.1.4 => 2.1.4 
      @tarojs/taro-h5: 2.1.4 => 2.1.4 
      @tarojs/taro-qq: 2.1.4 => 2.1.4 
      @tarojs/taro-quickapp: 2.1.4 => 2.1.4 
      @tarojs/taro-redux-rn: 2.1.4 => 2.1.4 
      @tarojs/taro-rn: 2.1.4 => 2.1.4 
      @tarojs/taro-router-rn: 2.1.4 => 2.1.4 
      @tarojs/taro-swan: 2.1.4 => 2.1.4 
      @tarojs/taro-tt: 2.1.4 => 2.1.4 
      @tarojs/taro-weapp: 2.1.4 => 2.1.4 
      @tarojs/webpack-runner: 2.1.4 => 2.1.4 
      eslint-config-taro: 2.1.4 => 2.1.4 
      eslint-plugin-taro: 2.1.4 => 2.1.4 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.8.0 => 16.8.0 
      react-native: 0.59.9 => 0.59.9 
      stylelint-config-taro-rn: 2.1.4 => 2.1.4 
      stylelint-taro-rn: 2.1.4 => 2.1.4

### 补充信息

真心希望能解决这个问题，让taro的通用性更好。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
WebView  组件在 Taro 中是存在的，可以直接使用
