### ISSUE TITLE
2.1.4 动不动就请求卡死 导致不能调试

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#5979]
### 问题描述
2.1.4 动不动就请求卡死 导致不能调试  正常2-3分钟出现一次
![image](https://user-images.githubusercontent.com/34000909/79193331-ffaf7000-7e5c-11ea-9877-6bf0ad2d1221.png)

### 复现步骤
无
### 期望行为

正常调试

### 报错信息

无

### 系统信息
Taro CLI 2.1.4 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      Node: 10.16.3 - E:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - E:\Program Files\nodejs\npm.CMD

**Comment by guggit** [comment]
2.1.1没有此问题

**Comment by luckyadam** [comment]
什么请求

**Comment by guggit** [comment]
> 什么请求

打包的资源
