### ISSUE TITLE
在执行 h5 预览后再执行微信小程序预览时 sitemap.json 文件缺失

### ISSUE THREAD

**Issue by liuchuzhang** [NervJS/taro#5980]
### 问题描述

在执行 h5 预览后再执行微信小程序预览时 sitemap.json 文件缺失

### 复现步骤

```shell
taro init demo
cd demo
yarn & yarn dev:weapp # 此时有 sitemap.json，在微信开发者工具中预览正常

# 停止编译监听，执行：
yarn dev:h5
# 编译完 h5 后，再停止编译监听，执行：
yarn dev:weapp # 编译过后 dist 目录没有了 sitemap.json
```

### 报错信息

![image](https://user-images.githubusercontent.com/37723064/79198102-823c2d80-7e65-11ea-862e-3df2030beaa8.png)

### 系统信息

Taro CLI 2.1.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm

**Comment by kycool** [comment]
https://kycool.cn/2019/08/03/taroWeappSitemap/
