### ISSUE TITLE
升级taro1.3.41 后 Taro.uploadFile 会爆跨域问题

### ISSUE THREAD

**Issue by guggit** [NervJS/taro#5982]
### 问题描述
升级taro 后 Taro.uploadFile 会爆跨域问题 1.3.20无此问题，2.1.1也有此问题

### 报错信息
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin

### 系统信息
Taro CLI 1.3.41 environment info:
System:
OS: Windows 8.1
Binaries:
Node: 10.16.3 - E:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
npm: 6.9.0 - E:\Program Files\nodejs\npm.CMD

**Comment by ZakaryCode** [comment]
未能复现该问题，具体是怎么操作的呢？方便的话可以提供一个demo
