### ISSUE TITLE
小程序组件设置属性值为false不生效

### ISSUE THREAD

**Issue by alexloading** [NervJS/taro#5988]
### 问题描述

微信小程序和qq小程序运行环境，设置video组件`controls`值为false不生效；

### 复现步骤

使用Taro3.0生成脚手架，react或者vue框架模板都能复现。
插入video组件代码，设置controls为false，开发者工具和真机都不生效；

React:
```
     <Video
          src='http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400'
          controls={false}
          autoplay={false}
          poster='http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg'
          initialTime='0'
          id='video'
          loop={false}
          muted={false}
        />
```

Vue:
```
          <video
          src='http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400'
          :controls="false"
          autoplay="false"
          poster="http://misc.aotu.io/booxood/mobile-video/cover_900x500.jpg"
          initialTime="0"
          id="video"
          :loop="false"
          :muted="false"
        />
```

### 期望行为

设置属性值为false时生效

### 系统信息

 Taro CLI 3.0.0-beta.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/webpack-runner: 3.0.0-beta.3 => 3.0.0-beta.3 
      eslint-config-taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      react: ^16.10.0 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息

提了pr修复，https://github.com/NervJS/taro/pull/5990

**Comment by cuiyajie** [comment]
并没有解决，我用微信小程序原生设置controls为"{{false}}"，则controls不显示。用Nerv/taro创建设置controls={false},controls仍然显示
