### ISSUE TITLE
安装 tarojs/cli 后运行报错，Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by daiyun169** [NervJS/taro#5993]
### 问题描述

之前的版本是 1.3.27

安装 tarojs/cli 后运行报错，Error: Cannot find module '@babel/core'

### 复现步骤

cnpm install -g @tarojs/cli@2.1.2

taro info

**Comment by luckyadam** [comment]
2.1.4 解决了这个问题

**Comment by xqGosky** [comment]
> 2.1.4 解决了这个问题

我升级了 但是还是一样的问题 TT
