### ISSUE TITLE
Taro h5 分包以后 navigateTo 问题

### ISSUE THREAD

**Issue by laihangji** [NervJS/taro#5996]
### 问题描述

新版本2.1.4  
h5 分包后  navigateTo 跳转会在页面中创建多个dom节点
![image](https://user-images.githubusercontent.com/25969108/79303332-36e75500-7f21-11ea-8544-c8a4d0051931.png)
使用Taro.navigateBack({ delta: 1 }) 回退进入新的页面后  页面显示旧的内容（但是浏览器链接已经改变）注：未请求任何数据，纯h5页面
非tarbar页面跳转回tarbar 页面也不会更新页面内容 

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by qingjuesama** [comment]
这个问题很蛋疼,navigateTo跳转之后navigateBack回来就不会触发 react生命周期,只能用useDIdShow来解决,但是useDidShow 没有依赖项 很蛋疼
