### ISSUE TITLE
taro 2.1.4版本,按需引入最新taro-ui样式,使用run build:weapp,样式错乱

### ISSUE THREAD

**Issue by dreamthen** [NervJS/taro#5998]
**问题描述**

taro 2.1.4版本,按需引入taro-ui样式,根本没有效果

**复现步骤**
下载最新版本的taro 2.1.4版本，根据taro-ui的文档，按需引入UI组件样式，然后使用生产环境命令run build:weapp打包，taro 2.1.0版本是好使的，到了2.1.4版本，样式错乱

![image](https://user-images.githubusercontent.com/13704681/78894629-fa8aa380-7a9f-11ea-881a-f246d05a001a.png)

**期望行为**

希望taro-ui UI组件库兼容最新版本的taro框架，按需引入UI组件样式能恢复正常

**报错信息**

![image](https://user-images.githubusercontent.com/13704681/78894705-2574f780-7aa0-11ea-95cb-41435820bb16.png)

**系统信息**

taro v2.1.4
taro-ui v2.3.3

**Comment by luckyadam** [comment]
是在哪里引入样式的，最好能给个 demo 看下

**Comment by dreamthen** [comment]
行，我出个demo

**Comment by luckyadam** [comment]
可能和 #5965 是一个问题，等我明天发个版本吧

**Comment by dreamthen** [comment]
好的

**Comment by luckyadam** [comment]
试试 2.1.5

**Comment by dreamthen** [comment]
> 试试 2.1.5

现在好了

**Comment by Q-Qplus1s** [comment]
同个问题， 升级2.1.5 OK了
