### ISSUE TITLE
样式文件中跨平台支持剔除h5未生效

### ISSUE THREAD

**Issue by ziruozimi** [NervJS/taro#5999]

**Comment by luckyadam** [comment]
请补充完整 issue 信息

**Comment by ziruozimi** [comment]
### 问题描述
样式文件有以下代码，
```css
/*  #ifdef h5  */
margin-right: $next-margin;
 /*  #endif  */
font-size: $font-size-base;
```
希望编译完成后文件中生成如下代码
```css
font-size: $font-size-base;
```

### 复现步骤
```sh
npm run dev:h5
```
生成代码如下
```css
/*  #ifdef h5  */
margin-right: $next-margin;
 /*  #endif  */
font-size: $font-size-base;
```
没有达到期望的效果

### 系统信息
👽 Taro v2.1.3


  Taro CLI 2.1.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.7 => 2.0.7 
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/mini-runner: 2.0.7 => 2.0.7 
      @tarojs/redux: 2.0.7 => 2.0.7 
      @tarojs/redux-h5: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.7 => 2.0.7 
      stylelint-taro-rn: 2.0.7 => 2.0.7

**Comment by ziruozimi** [comment]
找到问题了，scss嵌套中不生效
