### ISSUE TITLE
请问为什么一直在安装「npm包@tarojs/plugin-uglifyjs」

### ISSUE THREAD

**Issue by Kennytian** [NervJS/taro#6]
![image](https://user-images.githubusercontent.com/2621619/41030860-e5946e34-6944-11e8-9242-6f6ca9de4556.png)

**Comment by luckyadam** [comment]
可能是自动安装npm功能有点问题~
暂时用 `taro build --type weapp --watch` 来预览吧~
或者自行在项目目录下安装 `@tarojs/plugin-uglifyjs` 
下个版本修复这个bug

**Comment by Kennytian** [comment]
请问是执行 `yarn add --dev @tarojs/plugin-uglifyjs`  吗？

**Comment by Kennytian** [comment]
1. yarn add --dev @tarojs/plugin-uglifyjs

2. taro build --type weapp --watch

之后好了，谢谢！
