### ISSUE TITLE
Input type=“password”示例代码出错

### ISSUE THREAD

**Issue by jimczj** [NervJS/taro#60]
```
<Input type='password' placeholder='这是一个密码输入框'/>
```
小程序无错误，**h5 页面报错如下**，
![image](https://user-images.githubusercontent.com/13499146/41211326-37e9b432-6d69-11e8-8f99-81b4c41775f8.png)

**Comment by yuche** [comment]
fix via https://github.com/NervJS/taro/commit/ad9912f9fe29660b1edf4d0584dcc1dea56f3fa8
