### ISSUE TITLE
setState数据过大时会导致 跳转页面后渲染卡顿 

### ISSUE THREAD

**Issue by lovesL** [NervJS/taro#6002]
### 问题描述
setState 100条数据后控制台会报警告（setData 数据传输长度为 1598 KB，存在有性能问题！）然后在当前页面跳转会到账跳到的那个页面出现渲染报错并其卡无比 
![image](https://user-images.githubusercontent.com/27960630/79316593-19bd8100-7f37-11ea-90a8-a5716a47f4e6.png)

### 复现步骤

一次setState大量数据会出现问题 

### 期望行为
期望优化一下

### 系统信息
 Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.14.3 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/mini-runner: 2.0.7 => 2.0.7 
      @tarojs/redux: 2.0.7 => 2.0.7 
      @tarojs/redux-h5: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.7 => 2.0.7 
      stylelint-taro-rn: 2.0.7 => 2.0.7 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by wang777777** [comment]
这个问题快半年了，还是没解决？v3.0.9
