### ISSUE TITLE
Taro.request设置content-type ＝ application/x-www-form-urlencoded无效

### ISSUE THREAD

**Issue by SidneyLann** [NervJS/taro#6006]
3.x.beta.3:
![image](https://user-images.githubusercontent.com/5990314/79361218-98d2a980-7f77-11ea-9fa3-c7ff822ed854.png)
![image](https://user-images.githubusercontent.com/5990314/79361268-a6882f00-7f77-11ea-927b-c2a7651e1c7d.png)
发送application/x-www-form-urlencoded，结果Taro.request发了json过去

**Comment by SidneyLann** [comment]
设置content-type ＝ application/x-www-form-urlencoded， 但发过去的总是content-type ＝ application/json

**Comment by cloudZQY** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html  
建议先看清楚文档。话说用typescript就不会有这种错误了

**Comment by SidneyLann** [comment]
对照文档看没问题呀，我用的就是typescript。后端报Content type 'application/json' not supported，不管怎样都不应该发json的header过去。

**Comment by cloudZQY** [comment]
是header，不是headers

**Comment by SidneyLann** [comment]
一样不行。况且json可以传多个header, www form就不行吗?

![image](https://user-images.githubusercontent.com/5990314/79405260-7a47cf00-7fc6-11ea-92c0-64d0c8ef2f56.png)

**Comment by cloudZQY** [comment]
![image](https://user-images.githubusercontent.com/16647306/79405446-00fcac00-7fc7-11ea-9a52-b54ca37d2fc2.png)

**Comment by 61go** [comment]
我也遇到同样的问题了，到底是怎么解决的

**Comment by 61go** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html 建议先看清楚文档。话说用typescript就不会有这种错误了

大哥，人家是按文档写的啊，还是不行啊。

**Comment by 61go** [comment]
查出原因了：
改完之后，如不生效，需要重新启动一下项目：
yarn dev:weapp
这样才能观察到效果。。。
FUCK！
