### ISSUE TITLE
[Taro3 beta4] 重复 @tarojs/components 引发原生组件未被打包进 base.wxml

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#6007]
### 问题描述

目前遇到 input 和 textarea, 其他组件有待观察.

### 复现步骤

当存在形如 `node_modules/xxx/node_modules/@tarojs/components` 这样的目录结构时, xxx 内部引用 @tarojs/components 中的组件, 不会打包进 base.wxml.

出现这种目录结构的原因有两种:
1. npm link
2. 子包依赖的 @tarojs/components 和主项目版本不同. 尤其是 3.0.0-experimental.5 版本的存在.

```shell
tree node_modules/.test

node_modules/.test
├── index.js
└── node_modules
    └── @tarojs
        └── components
```

```js
// node_modules/.test/index.js

import React from 'react'
import { Textarea } from '@tarojs/components'

export const Textarea2 = (props) => {
    return (
        React.createElement(Textarea, props)
    )
}
```

```jsx
// src/pages/index.jsx

import React from 'react'
import { View } from '@tarojs/components'
import { Textarea2 } from '.test'

export default () => {
    return <View><Textarea2 value="" /></View>
}
```

<del>因为存在偶然性, 复现条件不明. 目前仍在测试中. 有时候 Ctrl+C 重新运行 `npm run dev:weapp` 可以恢复正常, 有时候保存代码更新后再次出现.</del>

### 报错信息

```
./base.wxml
 Template `tmpl_1_textarea` not found.
  107 | 
  108 | <template name="tmpl_1_container" data="{{i: i}}">
> 109 |   <template is="{{'tmpl_1_' + i.nn}}" data="{{i: i}}" />
      |                ^
  110 | </template>
  111 | 
  112 | <template name="tmpl_2_view">
```

### 系统信息

taro v3.0.0-beta.4

### 补充信息

临时解决方案:

手动导入用到的组件. 例如在 `app.js` 中添加:

```js
import { Textarea } from '@tarojs/components'
Textarea
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
你应该不能允许安装 3.0.0-experimental.5 这种情况存在，自行锁死项目依赖的版本
处理 npm link 是开发者自己做的事情

**Comment by cncolder** [comment]
@yuche 这个问题是从 beta4 开始出现的, runtime 重复问题是从 beta3 开始出现的.

之前的 beta2 现在成了主力版本.

experimental 只是举了一个例子, experimental 版导致从 alpha 开始需要写死依赖.

**Comment by stack-pop** [comment]
我的项目使用 pnpm + webpak5 也出现了这个问题

**Comment by nbutmickey** [comment]
> 我的项目目前是 taro 3.5.11，使用的是 pnpm + webpak5 也出现了这个问题。

+1，我也是pnpm + webpack5，只不过是偶现
