### ISSUE TITLE
Input组件在h5模式下ios自带输入法中文模式下的问题

### ISSUE THREAD

**Issue by EvanMaFYH** [NervJS/taro#601]
**问题描述**
Input组件在h5模式下ios自带输入法中文模式下的问题

**复现步骤**
[复现问题的步骤]
页面上加了一个Input，绑定value以及onInput方法，value绑定state，onInput时更新state，如
<Input value={this.state.test} onInput={this.onInputChange.bind(this)}/>
onInputChange(e){
  this.setState({
    test:e.target.value
  })
}
出现的情况比较奇怪，输入一个字母会出现好多个字母，用搜狗输入法就不会出现，两个输入法的区别在于ios自带输入法输入中文的时候字母已经出现在了输入框内
还是以组件库示例代码为例子，我把taro版本更新到了最新，里面那个实时获取输入值的输入框可以复现问题
[http://followyourheart.cn/tarodemo/#/pages/component/pages/input/input](http://followyourheart.cn/tarodemo/#/pages/component/pages/input/input)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: macOS
 - Taro 版本 1.0.0-beta.26
 - Node.js 版本 v8.9.3
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
请问一下  Input 组件是否也设置了 value={this.state.value}？ 请避免这这样设置。 自带的输入法在输入的时候已经调用了 onChange 方法，而并不是在你中文选择完之后触发 onChange 事件。  
一般来说，用户已经在 input 输入了相应的值触发了 onChange 事件，此时的 state 应该是和 input 的 value 是相等的，所以 value={this.state.value} 这一步的操作是有些多余。  组件库示例代码这部分有点问题，后续会将代码修改过来~

**Comment by jinjinjin0731** [comment]
ok 我明白你的意思了，这块我修一下。

**Comment by ybning** [comment]
这块我也遇到了，请问解决了吗？

@jinjinjin0731

**Comment by jinjinjin0731** [comment]
@ybning  已经修复哈

**Comment by JasonYan2015** [comment]
v1.2.4
又遇到了这个问题

**Comment by jinjinjin0731** [comment]
@JasonYan2015  你可以新开一个 issue 然后附上相关代码

**Comment by JasonYan2015** [comment]
v1.2.4
input组件使用onChange会出现上述问题
但是把onChange替换为onInput没问题了

**Comment by JasonYan2015** [comment]
> @JasonYan2015 你可以新开一个 issue 然后附上相关代码

不好意思
看了一下我这边的问题是taro-ui的input不是taro的input
