### ISSUE TITLE
[h5]2.1.4 Swiper设置circular=true不生效

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#6011]
### 问题描述

[h5]Swiper设置circular=true不生效

### 复现步骤

```js
<Swiper
      className='banner'
      circular
      autoplay
      indicatorDots
      indicatorColor='#bfbfbf'
      indicatorActiveColor='#63b931'
    >
      {items.map(b => (
        <SwiperItem key={b.idl}>
          <Image src={b.imgUrl} />
        </SwiperItem>
      ))}
    </Swiper>
```

### 期望行为

circular生效

### 报错信息
circular无效
### 系统信息

    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvs/default/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/cli: 2.1.4 => 2.1.4 
      @tarojs/components: 2.1.4 => 2.1.4 
      @tarojs/mini-runner: 2.1.4 => 2.1.4 
      @tarojs/redux: 2.1.4 => 2.1.4 
      @tarojs/redux-h5: 2.1.4 => 2.1.4 
      @tarojs/router: 2.1.4 => 2.1.4 
      @tarojs/taro: 2.1.4 => 2.1.4 
      @tarojs/taro-h5: 2.1.4 => 2.1.4 
      @tarojs/taro-weapp: 2.1.4 => 2.1.4 
      @tarojs/webpack-runner: 2.1.4 => 2.1.4 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
### 补充信息

     翻了源码，可能是这行判断的问题(taro-componens/src/components/swiper/index/js Line 132)
      if (!this.mySwiper.isBeginning && !this.mySwiper.isEnd) {
      }

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
无法复现该问题，上述提到的判断是用于控制轮播占位的，与问题并无关联

**Comment by yulrosy** [comment]
我这是必现的，回退到2.1.0就正常，2.1.0没这行代码 @ZakaryCode

**Comment by ZakaryCode** [comment]
那可以升级试试咯，如果还有问题，可能需要麻烦提供个demo了
