### ISSUE TITLE
taro编译错误，参数未导入

### ISSUE THREAD

**Issue by WangJM001** [NervJS/taro#6014]
### 问题描述

引用对象在编译后报参数未定义

### 复现步骤

见代码

```js
// pages/todolist/model.ts
export default {
  namespace: "todo",
}

// models/index.ts
import { todo } from "@/pages/todolist/model";

export default [todo];

// app.tsx
import models from "./models";

const dvaApp = dva.createApp({
  initialState: {},
  models
});

```
编译后代码
![image](https://user-images.githubusercontent.com/20501316/79426532-d9710800-7ff5-11ea-8a36-cbd0e9d3aab0.png)

### 期望行为

正常引入

### 报错信息

todo未定义

### 系统信息

Taro CLI 2.1.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by WangJM001** [comment]
/pages/todolist/model.ts
![image](https://user-images.githubusercontent.com/20501316/79426840-52705f80-7ff6-11ea-9d2c-32b925b381d3.png)

/models/index.ts
![image](https://user-images.githubusercontent.com/20501316/79426859-5f8d4e80-7ff6-11ea-96eb-9a319961ce85.png)

weapp正常编译

**Comment by Pines-Cheng** [comment]
升级到 2.1.4 试试。https://github.com/NervJS/taro/commit/ac40ad3

**Comment by WangJM001** [comment]
升级到2.1.5,问题依然存在

**Comment by WangJM001** [comment]
@Pines-Cheng ,升级到2.1.5了依然不行，还有什么配置么

**Comment by Pines-Cheng** [comment]
没能重现，麻烦提供可重现的demo。
