### ISSUE TITLE
使用Taro v3.0.0-beta.3运行在百度小程序中flex：1不生效

### ISSUE THREAD

**Issue by wkh2** [NervJS/taro#6015]
### 复现步骤

![image](https://user-images.githubusercontent.com/19984871/79429798-9b2a1780-7ffa-11ea-9d1f-9f47263e1c81.png)

或者你们随便写一个view，包含两个子块，然后设置一个块flex 1 即可复现。

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
<View style={{display: 'flex'}}>
<View style={{flex: 1}}>
<Text>我是左边</Text>
</View>
<View style={{width: ''80px}}>
<Text>我是右边</Text>
</View>
</View>

```

### 期望行为

期望左边flex 1撑开左侧
期望效果如图
![image](https://user-images.githubusercontent.com/19984871/79430650-d6791600-7ffb-11ea-8d74-b8bffe52d4e2.png)

### 报错信息
无报错，百度小程序中不生效
![image](https://user-images.githubusercontent.com/19984871/79430712-f27cb780-7ffb-11ea-891c-01eef87cbadd.png)

### 系统信息

![image](https://user-images.githubusercontent.com/19984871/79430812-104a1c80-7ffc-11ea-99cf-bc02c4143223.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by wkh2** [comment]
截图中的2 设置flex 1 ,诉求要撑开，但是没有效果

**Comment by yuche** [comment]
百度小程序本身对 flex 布局支持不好，你可以尝试一下如果使用原生百度小程序写一个相同的布局，看一下是否可用

**Comment by wkh2** [comment]
> 百度小程序本身对 flex 布局支持不好，你可以尝试一下如果使用原生百度小程序写一个相同的布局，看一下是否可用

试过taro 1.3.4版本的项目，是可以正常的。

**Comment by yuche** [comment]
你换成 css 而不是 inline style 看一下可用吗

**Comment by Chen-jj** [comment]
@wkh2 Taro3 使用了 template 进行 xml 结构递归。这问题是因为百度的 template 标签不是虚拟的，而是真实 DOM 节点，所以 flex 崩了。我们再跟百度方面反馈下，这里你可能要用 float 等做布局了。

**Comment by yang4515** [comment]
有结果了吗

**Comment by rvean** [comment]
正式版 3.0.2 了，flex: 1; 还是失效哦

**Comment by Chen-jj** [comment]
@rvean 这需要百度小程序团队去修复，但应该短期内很难解决。

![image](https://user-images.githubusercontent.com/11807297/87107434-57118080-c292-11ea-959d-b35b9560f2ae.png)

**Comment by Phlen** [comment]
都2021了，还是没有进展吗 😓

**Comment by bluescurry** [comment]
请问目前有进展吗，目前的解决方法除了float布局，还有别的临时方案吗，flex 布局是一个太通用的方案了，把这个毙了相当于无法编译百度小程序一样。。。 @Chen-jj

**Comment by paulloo** [comment]
https://smartprogram.baidu.com/forum/topic/show/127164

百度那边，说原生完好，要框架端解决。悬而未决，只能用float代替了嘛？ 几百个地方，心累~~

**Comment by bluescurry** [comment]
百度不解决，taro 也不打算解决了吗，那百度小程序不就相当于不支持了吗。。。

**Comment by ivan-94** [comment]
有进展吗

**Comment by zephyr-66** [comment]
不支持百度了吗？

**Comment by Chen-jj** [comment]
缓慢推进中。。

**Comment by TomVista** [comment]
同样因为这个问题，一些css选择器也不能正常使用 >  nth-child

**Comment by SyMind** [comment]
确实是百度小程序 template 标签渲染的问题，但是我想可以先使用一种临时的启发式的方案解决，从而能够使 View 正常地进行 flex 布局。
1. 思路是小程序模板渲染 pure-view 的 template 如果子组件仍为 pure-view 则非递归地渲染，例如允许非递归渲染深度为 10，深度超过后再次调用模板进行递归渲染，此时重置非递归渲染深度。
2. 为了能够在开发时显示重置非递归深度，在判断 View 标签无 class 属性、无 style 属性时，调用模板进行递归渲染，重置非递归渲染深度。

@Chen-jj 我随后将 pull 代码。

**Comment by TomVista** [comment]
同样因为这个问题,cover-view 的嵌套,会导致cover-view 内部的cover-view 不显示,其他cover元素同理

**Comment by SyMind** [comment]
@TomVista 那看起来在百度小程序中 cover-view 的嵌套也需要进行特殊处理。

**Comment by xiao-shanfeng** [comment]
什么时候给解决啊，如果大版本修复的话，最起码现在官方给出个解决方案啊

**Comment by youmengme** [comment]
我发现设置这个全局样式也可以解决这个问题。
taro 3.3.1修复了view > view的flex传递问题，但是好像没有修复view > image的flex问题，下面这个代码可以同时解决这两个问题。

```scss
swan-template {
  display: contents;
}
```

**Comment by moyafaxi** [comment]
@SunPm 也是Swiper水平方向轮播有点问题，有办法解决么

**Comment by xixilalaha** [comment]
@moyafaxi  麻烦问下这个你解决了么

**Comment by moyafaxi** [comment]
swan-swiper swan-template {
  display: block;
}
@xixilalaha 暂时这样解决了

**Comment by xixilalaha** [comment]
@moyafaxi 我也是这样处理了，麻烦了

**Comment by hisanshao** [comment]
@Chen-jj 3.5.7+ kwai2.0.0 快手小程序也还是有这个问题

**Comment by markchenlife** [comment]
> @Chen-jj 3.5.7+ kwai2.0.0 快手小程序也还是有这个问题

快手的这个问题还存在，不知道有没有解决方案

**Comment by Chen-jj** [comment]
> > @Chen-jj 3.5.7+ kwai2.0.0 快手小程序也还是有这个问题
> 
> 快手的这个问题还存在，不知道有没有解决方案

@markchenlife 可以新建一个 issue，我们跟进一下

**Comment by markchenlife** [comment]
> > 我发现设置这个全局样式也可以解决这个问题。 taro 3.3.1修复了view > view的flex传递问题，但是好像没有修复view > image的flex问题，下面这个代码可以同时解决这两个问题。
> > ```
> > swan-template {
> >   display: contents;
> > }
> > ```
> 
> 我taro 3.1.0-beta.12 按你这种办法也能解决大部分问题，但是Swiper水平方向轮播会有问题

请问一下快手小程序也可以这么解决么？

**Comment by yoyo837** [comment]
直接自己试一下
