### ISSUE TITLE
自定义组件根据环境变量只在h5端展示,在小程序中会报错

### ISSUE THREAD

**Issue by BreathlessWay** [NervJS/taro#602]
**问题描述**
自定义组件根据 TARO_ENV 只在h5端展示, 但是编译后在小程序会报 Component is not found 错

**复现步骤**
[复现问题的步骤]
1. 引入自定义组件 import CustomTarBar from '../../components/CustomTarBar/CustomTarBar';
2. 根据环境展示组件 
        {
          process.env.TARO_ENV === 'h5' &&
          <CustomTarBar/>
        }
3. h5端展示正常, 小程序端会报错 Component is not found in path

**期望行为**
编译后在小程序端不报错

**报错信息**
Component is not found in path "components/CustomTarBar/CustomTarBar" (using by "pages/index/index")
Error: Component is not found in path "components/CustomTarBar/CustomTarBar" (using by "pages/index/index")

**系统信息**

 - 操作系统: Mac
 - Taro 版本 v1.0.0-beta.26
 - Node.js 版本 8.9.0

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/eee9923dabe9b8ab74ab206db95062eb3c9ca6c7
