### ISSUE TITLE
rn端不能通过三目运算符、ES6的模板字符串形式来动态控制className

### ISSUE THREAD

**Issue by somnuslbl** [NervJS/taro#6021]
### 问题描述
rn端不能通过三目运算符、ES6的模板字符串形式来动态控制className，在h5和小程序端则是正常的

### 复现步骤

```js
/**
 *
export default class Tab extends Component {

  state = {
    currentIndex: 0
  }
  clickChange = index => () => {
    this.setState({
      currentIndex: index
    })
  }
  render () {
    const { currentIndex } = this.state
    const { tabList } = this.props
    return (
      <View className='tab-wrapper' >
        {
          tabList.map((item, index) => {
            return (
              <View className={'tab-item' + (currentIndex === index ? ' box-active' : '')} key={item.id} onClick={this.clickChange(index)}>
                <Text className={'tab-name' + (currentIndex === index ? ' active' : '')}>{item.tabName}</Text>
              </View>
            )
          })
        }
        
      </View>
    )
  }
}

css:
.tab-wrapper{
  border-color: #E8E8E8;
  border-style: solid;
  border-bottom-width: 1px;
  padding: 46px 30px 16px 30px;
  flex-direction: row;
  justify-content: space-around;
  display: flex;
}
.tab-item {
  align-items: center;
}
.box-active {
  background-color: green;
}
.tab-name {
  color: #999;
  font-size: 28px;
}
.active {
  color: red;
  font-weight: bold;
}
 */


```

### 期望行为

在rn端能正常表现

### 报错信息

没有报错信息。在编译成rn之后，调用_getStyle方法返回的是null

### 系统信息

ro v2.1.4

  Taro CLI 2.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Users\longyuan\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD

### 补充信息

目前我的解决方式是通过css in js的方法，或者是动态控制style

**Comment by Pines-Cheng** [comment]
感谢反馈～

**Comment by xiehui999** [comment]
css module 在RN 中使用动态控制，也是没有效果是一个问题吗，例如 
`
const className = `${style.iconAssistant} ${style.opacityIcon}` : style.iconAssistant
 <View   className={className}  />
`
这样写RN 不生效， 使用的Taro  3.2.10

**Comment by zhiqingchen** [comment]
> css module 在RN 中使用动态控制，也是没有效果是一个问题吗，例如 
> 
> `
> 
> const className = `${style.iconAssistant} ${style.opacityIcon}` : style.iconAssistant
> 
>  <View   className={className}  />
> 
> `
> 
> 这样写RN 不生效， 使用的Taro  3.2.10

@shinken008

**Comment by zhiqingchen** [comment]
> css module 在RN 中使用动态控制，也是没有效果是一个问题吗，例如 
> 
> `
> 
> const className = `${style.iconAssistant} ${style.opacityIcon}` : style.iconAssistant
> 
>  <View   className={className}  />
> 
> `
> 
> 这样写RN 不生效， 使用的Taro  3.2.10

未复现，麻烦提个issue，提供下复现demo

**Comment by xiehui999** [comment]
> > css module 在RN 中使用动态控制，也是没有效果是一个问题吗，例如
> > `
> > const className = `${style.iconAssistant} ${style.opacityIcon}` : style.iconAssistant
> >  
> > `
> > 这样写RN 不生效， 使用的Taro  3.2.10
> 
> 未复现，麻烦提个issue，提供下复现demo

创建了demo  ， https://github.com/NervJS/taro/issues/9784 ，这个是必现的，
    const textClass = num % 2 ? style.red: style.blue   设置className 样式就无效， 只设置 style.blue就有效果
