### ISSUE TITLE
这个编译,我也是醉了呀

### ISSUE THREAD

**Issue by talentedman** [NervJS/taro#6028]
Taro版本 1.3.19
![image](https://user-images.githubusercontent.com/18200527/79543953-d0993880-80c0-11ea-8566-ff2db35f8aa8.png)

源代码
![image](https://user-images.githubusercontent.com/18200527/79544004-e4dd3580-80c0-11ea-91c4-dc05ea327eeb.png)

编译后的代码
![image](https://user-images.githubusercontent.com/18200527/79544036-f58dab80-80c0-11ea-8740-fefa2758c21e.png)

**Comment by talentedman** [comment]
结果就报错了  
![image](https://user-images.githubusercontent.com/18200527/79544112-15bd6a80-80c1-11ea-8f4e-b455699c0ccd.png)

**Comment by luckyadam** [comment]
升级到 1.3.42

**Comment by talentedman** [comment]
已升级到2.1.5  还是会报这个错误
