### ISSUE TITLE
[h5]2.0.7 Swiper设置circular=true生效，页面跳转之后后退回来，轮播不动了。

### ISSUE THREAD

**Issue by missmimia** [NervJS/taro#6029]
### 问题描述

[h5]2.0.7 Swiper设置circular=true生效，页面跳转之后后退回来，轮播不动了。
小程序端是正常的，页面跳转后退回来还是照常循环播放。

### 复现步骤

```js

          <View className={styles.swiper}>
            <Swiper
              autoplay
              interval={1500}
              // circular={headlineList.length > 1}
              circular
              className={styles.healthLifeSwiper}
              vertical
            >
              {headlineList.map((item, index) => {
                return (
                  <SwiperItem key={`${item + index}`}>
                    <View className={styles.content} onClick={() => onRouter(item)}>
                      · {item.name}
                    </View>
                  </SwiperItem>
                );
              })}
            </Swiper>
          </View>

```

### 期望行为

页面后退回来，轮播正常循环播放。

### 系统信息

 "@tarojs/components": "2.0.7",
    "@tarojs/redux": "2.0.7",
    "@tarojs/redux-h5": "2.0.7",
    "@tarojs/router": "2.0.7",
    "@tarojs/taro": "2.0.7",
    "@tarojs/taro-h5": "2.0.7",
    "@tarojs/taro-weapp": "2.0.7",

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
可以升级到最新版本
