### ISSUE TITLE
h5编译scss文件时提示fs.copyFileSync is not a function

### ISSUE THREAD

**Issue by 824759494** [NervJS/taro#603]
**问题描述**
项目信息：Taro v1.0.0-beta.26   typescript   scss
编译h5时报fs.copyFileSync is not a function

**复现步骤**
[复现问题的步骤]
1. 创建一个typescript scss redux项目
编译：
> npm run dev:h5

h5.js中的652行
```
try {
    if (isScriptFile) {
      // 脚本文件 处理一下
      const content = file.toString()
      const transformResult = fileType === FILE_TYPE.ENTRY
        ? processEntry(content, filePath)
        : processOthers(content, filePath)
      const jsCode = unescape(transformResult.code.replace(/\\u/g, '%u'))
      fs.ensureDirSync(distDirname)
      fs.writeFileSync(distPath, Buffer.from(jsCode))
    } else {
      // 其他 直接复制
      fs.ensureDirSync(distDirname)
      fs.copySync(filePath, distPath) 
    }
  } catch (e) {
    console.log(e)
  }
```

**期望行为**
能够正常编译

**报错信息**
TypeError: fs.copyFileSync is not a function

**系统信息**

 - 操作系统: [e.g. windows 7 64位旗舰版]
 - Taro 版本 [e.g. Taro v1.0.0-beta.26]
 - Node.js 版本 [e.g. v8.2.0]

**补充信息**
fs.writeFileSync这里在fs-extra中应该是fs.copySync

**Comment by Littly** [comment]
copyfile是node10的API 升级下再试试

**Comment by 824759494** [comment]
@Littly ok  是我疏忽了
