### ISSUE TITLE
next beta 4版本在init项目后马上编译weapp 会报错

### ISSUE THREAD

**Issue by tonytecgit** [NervJS/taro#6032]
执行命令：taro init test
选项：vue vuex
执行命令编译：npm run dev:weapp
编译提示错误
![1](https://user-images.githubusercontent.com/48077992/79557627-7787cf80-80d5-11ea-94c6-80d981e6c37d.png)
临时解决方案：将package.json文件中的@tarojs/mini-runner": "3.0.0-beta.4版本换为beta.3就好了

**Comment by Chen-jj** [comment]
@tonytecgit 复现不了，重新安装一遍 taro 相关依赖再试试。

进入报错位置的函数，打印 `Object.keys(assets)` 看看，按道理 app.wxss 应该存在。

![image](https://user-images.githubusercontent.com/11807297/79683501-24408900-825d-11ea-8986-b4929e5e47c3.png)

**Comment by firefly9527** [comment]
我也遇到了，重写安装还是有问题

**Comment by Chen-jj** [comment]
> 我也遇到了，重写安装还是有问题

@firefly9527 提供下可复现的 demo
