### ISSUE TITLE
taro init test1 没有生产package.json文件

### ISSUE THREAD

**Issue by ParryGao** [NervJS/taro#6033]
👽 Taro v1.3.25

Taro即将创建一个新项目!
Need help? Go and open issue: https://github.com/NervJS/taro/issues/new

✔ 拉取远程模板仓库成功！
? 请输入项目名称！ test1
? 请输入项目介绍！
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 redux

✔ 创建项目: test1
✔ 创建文件: test1/.editorconfig
✔ 创建文件: test1/.eslintrc
✔ 创建文件: test1/.gitignore
✔ 创建文件: test1/pkg
✔ 创建文件: test1/project.config.json
✔ 创建文件: test1/config/dev.js
✔ 创建文件: test1/config/index.js
✔ 创建文件: test1/config/prod.js
✔ 创建文件: test1/src/app.scss
✔ 创建文件: test1/src/app.jsx
✔ 创建文件: test1/src/index.html
✔ 创建文件: test1/src/actions/counter.js
✔ 创建文件: test1/src/constants/counter.js
✔ 创建文件: test1/src/reducers/counter.js
✔ 创建文件: test1/src/reducers/index.js
✔ 创建文件: test1/src/store/index.js
✔ 创建文件: test1/src/pages/index/index.scss
✔ 创建文件: test1/src/pages/index/index.jsx

✔ cd test1, 执行 git init
✔ 安装成功
yarn install v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.06s.

创建项目 test1 成功！
请进入项目目录 test1 开始工作吧！😝

**Comment by luckyadam** [comment]
升级到 1.3.42 试试
