### ISSUE TITLE
stopPropagation 无法阻止事件冒泡

### ISSUE THREAD

**Issue by afishhhhh** [NervJS/taro#6038]
### 问题描述

```js
this.handleActionTap = this.handleActionTap.bind(this)

handleActionTap (action) {
    return event => {
      event.stopPropagation()
      console.log(action)
    }
  }

<Button onClick={this.handleActionTap('someaction)}></Button>
```

### 系统信息

Taro v2.0.3

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.3 => 2.0.3 
      @tarojs/components-qa: 2.0.3 => 2.0.3 
      @tarojs/mini-runner: 2.0.3 => 2.0.3 
      @tarojs/router: 2.0.3 => 2.0.3 
      @tarojs/taro: 2.0.3 => 2.0.3 
      @tarojs/taro-alipay: 2.0.3 => 2.0.3 
      @tarojs/taro-h5: 2.0.3 => 2.0.3 
      @tarojs/taro-qq: 2.0.3 => 2.0.3 
      @tarojs/taro-quickapp: 2.0.3 => 2.0.3 
      @tarojs/taro-rn: 2.0.3 => 2.0.3 
      @tarojs/taro-swan: 2.0.3 => 2.0.3 
      @tarojs/taro-tt: 2.0.3 => 2.0.3 
      @tarojs/taro-weapp: 2.0.3 => 2.0.3 
      @tarojs/webpack-runner: 2.0.3 => 2.0.3 
      eslint-config-taro: 2.0.3 => 2.0.3 
      eslint-plugin-taro: 2.0.3 => 2.0.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.3 => 2.0.3 
      stylelint-taro-rn: 2.0.3 => 2.0.3

**Comment by Chen-jj** [comment]
@afishhhhh Taro 目前是通过编译时去分析 AST， 找到调用了 stopPropagation 的回调函数所对应的组件，编译成 xml 时把 bindXXX 改为 catchXXX。目前上述写法编译时分析不出来所以不被支持，Taro 3 才能支持。
