### ISSUE TITLE
React.Children.map 未实现？

### ISSUE THREAD

**Issue by mengqingshen** [NervJS/taro#604]
React 可以通过 React.Children.map 来对 slot 进行包装，在写通用组件的时间很有用，在 Taro 中引入了 nervjs 来调用 Children.map 方法是存在的，但不管 return 什么，返回的都是 null，无法正常工作。请问这个问题有替代方案来解决吗？你们对这个 API 的计划是啥？

**Comment by luckyadam** [comment]
小程序中暂时无法操作 `this.props.children`
H5 端是使用 `nervjs` 的，是说 H5 里 `Children.map` 方法存在 bug 么

**Comment by mengqingshen** [comment]
抱歉没讲清楚，我说的是小程序。了解了，就是说小程序里无法操作 this.props.children, 了解了，多谢

**Comment by luckyadam** [comment]
@mengqingshen 是的，暂时无法操作
