### ISSUE TITLE
2.x的版本打包比1.3的版本大了太多了，dev大了500k，build大了300k，不知道你们怎么想的

### ISSUE THREAD

**Issue by Groundhog-Chen** [NervJS/taro#6040]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
http://taro-docs.jd.com/taro/docs/migrate-to-2.html#%E5%8F%91%E8%A7%89%E5%8D%87%E7%BA%A7%E4%B9%8B%E5%90%8E%E6%96%87%E4%BB%B6%E6%9B%B4%E5%A4%A7

![image](https://user-images.githubusercontent.com/1782542/79718613-07648e00-830f-11ea-939e-8a2df4d365e8.png)
