### ISSUE TITLE
安装后eslint报错

### ISSUE THREAD

**Issue by maoxfjob** [NervJS/taro#6042]
### 问题描述

安装后，vscode内eslint报未找到tsconfig，当前项目目录内是有的，但是查找显示的路径不是当前项目目录

### 复现步骤

目录信息

D:\Project\taro

![image](https://user-images.githubusercontent.com/32216262/79716803-64aa1080-830a-11ea-8715-640e8714499a.png)

报错信息

![image](https://user-images.githubusercontent.com/32216262/79716641-e3527e00-8309-11ea-8ec1-ce5ccdf01c17.png)

### 期望行为

不要提示错误信息

### 报错信息

Parsing error: File 'd:\project\tsconfig.json' not found.

### 系统信息

PS D:\Project\taro> taro info
� Taro v2.1.5

  Taro CLI 2.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.10.0 - D:\Software\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Sean\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - D:\Software\nodejs\npm.CMD

**Comment by Garfield550** [comment]
你用 VSCode 直接打开 `D:\Project\taro` 试一下
