### ISSUE TITLE
Taro.request 请求 jsonp 问题

### ISSUE THREAD

**Issue by Nick930826** [NervJS/taro#6043]
Taro.request  请求 jsonp，之前版本是可以设置 jsonp 参数为 String 类型作为回调函数名称的，当前最新版本不支持这样的操作了。请问如何设置回调函数的名称？

**Comment by ZakaryCode** [comment]
具体的版本号是？

**Comment by Nick930826** [comment]
> 具体的版本号是？

v2.1.4 Taro.request 没有设置 jsonp 回调函数名称属性

**Comment by ZakaryCode** [comment]
> > 具体的版本号是？
> 
> v2.1.4 Taro.request 没有设置 jsonp 回调函数名称属性

应该是类型缺失，最近并没有request相关的迭代，需要的话可以先直接用
