### ISSUE TITLE
Taro2.1.4使用splitChunks和addChunkPages分包，进入分包页面，页面白屏并且提示Page "..." has not been registered yet.

### ISSUE THREAD

**Issue by cyq333** [NervJS/taro#6044]
### 问题描述
Taro2.1.4和微信小程序混写，由于common.js包太大，因此使用splitChunks分包出来，并且使用addChunkPages引用到对应的分包页面中，但是进入分包页面，页面白屏，并且提示Page "..." has not been registered yet.

有两个问题
1.原生小程序分包下的文件，纯js文件（没有对应的wxml文件）会被默认打包到common.js中，如图，pages/appoint/api/appoint.js,类似于这种文件都会被打包到common.js中，导致common很大，然后增加了主包的大小

![image](https://user-images.githubusercontent.com/15816893/79719865-0a14b280-8312-11ea-98d6-aa63af3b98b3.png)

2.因此采用文档提供的addChunkPages分包，出现Page "pages/appoint/appoint" has not been registered yet的问题

### 复现步骤
分包页面为微信小程序原生页面

```config
mini: {
    webpackChain(chain, webpack) {
      chain
        .plugin("analyzer")
        .use(require("webpack-bundle-analyzer").BundleAnalyzerPlugin, []);
      chain.merge({
        optimization: {
          splitChunks: {
            cacheGroups: {
              appoint_chunk: {
                name: "pages/appoint/appoint_chunk",
                priority: 1000,
                test(module) {
                  if (
                    /src[\\/]pages[\\/]appoint[\\/]api/.test(module.resource)
                  ) {
                    return true;
                  }
                },
              },
            },
          },
        },
      });
    },
    // commonChunks(commonChunks) {
    //     return commonChunks;
    // },
    addChunkPages(pages, pagesNames) {
      pages.set("pages/appoint/appoint", ["appoint_chunk"]);
    },
}

app.tsx
config: Config = {
    pages: [
      'pages/index/index'
    ],
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    },
    subPackages: [
      {
        root: "pages/appoint",
        name: "appoint",
        pages: [
            "appoint",
        ],
    },
    ]
  }


```

### 期望行为
能正常进入分包页面

### 报错信息

分包页面白屏，控制台提示Page "pages/appoint/appoint" has not been registered yet.

### 系统信息

Taro v2.1.4

  Taro CLI 2.1.4 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.1.4 => 2.1.4
      @tarojs/components: 2.1.4 => 2.1.4
      @tarojs/components-qa: 2.1.4 => 2.1.4
      @tarojs/mini-runner: 2.1.4 => 2.1.4
      @tarojs/mobx: 2.1.4 => 2.1.4
      @tarojs/router: 2.1.4 => 2.1.4
      @tarojs/taro: 2.1.4 => 2.1.4
      @tarojs/taro-weapp: 2.1.4 => 2.1.4
      @tarojs/webpack-runner: 2.1.4 => 2.1.4
      eslint-config-taro: 2.1.4 => 2.1.4
      eslint-plugin-taro: 2.1.4 => 2.1.4
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.1.4 => 2.1.4
      stylelint-taro-rn: 2.1.4 => 2.1.4
    npmGlobalPackages:
      typescript: 3.6.3

**Comment by cyq333** [comment]
这个问题有解决吗？现在没有办法分包了，分包的页面都会白屏 @Chen-jj

**Comment by summer88123** [comment]
3.0.0-beta.3也会有类似的问题 @Chen-jj

**Comment by Chen-jj** [comment]
@cyq333 升级到 2.x 最新版后再试试？

**Comment by Chen-jj** [comment]
@summer88123 复现不了，可以升级到 3.x 最新版后再试试，如有问题可以另外提 issue。

config/index.js

```js
mini: {
    webpackChain (chain) {
      const config = chain.optimization.get('splitChunks')
      chain.optimization
        .splitChunks({
          ...config,
          cacheGroups: {
            ...config.cacheGroups,
            subutils: {
              name: 'packageA/sub-utils',
              minChunks: 2,
              test: module => /[\\/]packageA[\\/]/.test(module.resource),
              priority: 200
            }
          }
        })
    },
    addChunkPages (pages) {
      pages.set('packageA/detail/index', ['packageA/sub-utils'])
      pages.set('packageA/my/index', ['packageA/sub-utils'])
    }
}
```

src/subpackageA/detail/index.jsx

```js
import React, { Component } from 'react'
import { View, Text } from '@tarojs/components'
import { someCommon } from '../common'
import './index.css'

export default class Detail extends Component {
  componentDidMount () {
    someCommon('detail')
  }

  render () {
    return (
      <View className='detail'>
        <Text>I m detail</Text>
      </View>
    )
  }
}
```

src/subpackageA/my/index.jsx

```js
import React, { Component } from 'react'
import { View, Text } from '@tarojs/components'
import { someCommon } from '../common'

export default class My extends Component {
  componentDidMount () {
    someCommon('my')
  }

  render () {
    return (
      <View>
        <Text>I m my</Text>
      </View>
    )
  }
}
```

src/subpackageA/common.js

```js
export function someCommon (text) {
  console.log('log something: ', text)
}
```

**Comment by dreamthen** [comment]
+1, 2.2.8版本已经出现

**Comment by LeeeMooo** [comment]
+1，2.2.6版本出现。 逛了一圈issues，发现好多一样的问题， 没人跟进吗？

**Comment by 17** [comment]
最新 2.2.15 复现

**Comment by HeiLiu** [comment]
升 Taro3.0.15 碰到这个问题

**Comment by luckyadam** [comment]
addChunkPages(pages, pagesNames) {
      pages.set("pages/appoint/appoint", ["appoint_chunk"]);
    },

问题中明显配错了，应该如下 

addChunkPages(pages, pagesNames) {
      pages.set("pages/appoint/appoint", ["pages/appoint/appoint_chunk"]);
    },

**Comment by TomatoesMan** [comment]
升 Taro3.5.12 碰到这个问题

**Comment by wuxuejie** [comment]
3.6.8独立分包也运行不了
<img width="721" alt="image" src="https://github.com/NervJS/taro/assets/31883495/2ee6fb6f-cbe6-454c-b54d-82a32c8697da">
