### ISSUE TITLE
Taro.uploadFile 无法对 Access-Control-Allow-Origin 设为 * 的情况下上传文件

### ISSUE THREAD

**Issue by infinnie** [NervJS/taro#6047]
### 问题描述

由于 #5896, 上传文件的 XHR withCredential 属性被强制设为 true 了，因此服务器端 Access-Control-Allow-Origin 为 * 的情况下无法上传文件

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
浏览器本身也会限制，规避一下吧
