### ISSUE TITLE
小程序不能通过key来重走组件生命周期

### ISSUE THREAD

**Issue by deepcoldy** [NervJS/taro#605]
**问题描述**
由于业务需要在某些条件下执行componentDidMount，所以想到通过key的改变来执行[相关官方文档](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key)，另外试了一下nerv是支持的[PlayGround](https://codesandbox.io/s/zox0kxj6x)。

希望taro-weapp也能通过key来触发rerender

**Comment by yuche** [comment]
小程序内部的 key 和 diff 我们也不得而知究竟是怎么运作，即便想要做什么也不知道从何入手，会对小程序的渲染机制有什么影响。

建议使用三元表达式或逻辑表达式处理是否渲染吧。
