### ISSUE TITLE
能否支持小程序对应的方法catchtap捕获事件，不是阻止冒泡

### ISSUE THREAD

**Issue by lilingling3** [NervJS/taro#6050]
### 问题描述

全局捕获事件
### 复现步骤

1. 
2. 
3. 
4. 

```js



```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
哪个版本怎么写的代码
