### ISSUE TITLE
在UC浏览器(android和ios)上，快速跳转导致的回退时的问题

### ISSUE THREAD

**Issue by Andrewuetyang** [NervJS/taro#6051]
### 问题描述
在UC浏览器(android和ios)上，在某个页面快速跳转到下一个页面，返回时，如果目标页面就是这个页面，或者返回的路径包含这个中间页面，那么这个页面像不存在页面栈中一样，会被忽略。但是在发起回退的页面，查看页面栈信息，是有这个中间页面的。

### 复现步骤
写个最简单的跳转，3个页面及以上，在uc浏览器打开，不分android和ios，都能重现。

### 期望行为
回退正常

### 报错信息
无报错信息

### 系统信息
试过2个版本，一个是taro 1.3.25和最新的2.1.4，都有这个问题。

**Comment by zhansingsong** [comment]
问题解决了么，什么原因

**Comment by chaozhang5** [comment]
这个问题在3.6.8版本还存在，一直没修复吗？
