### ISSUE TITLE
[Taro3] 深层嵌套到第15层需要重启组件时碰到 Text 导致重启失败子节点丢失

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#6054]
### 问题描述

深层嵌套时, 第15层会变成 `<comp />`, 之后的内容变成子组件.

如果第15层刚好是 Text, 则不会重启 `<comp />`, 下面的所有子节点会丢失.

### 复现步骤

```jsx
import React from "react";
import { View, Text } from "@tarojs/components";

export default () => (
  <View>
    1
    <View>
      2
      <View>
        3
        <View>
          4
          <View>
            5
            <View>
              6
              <View>
                7
                <View>
                  8
                  <View>
                    9
                    <View>
                      10
                      <View>
                        11
                        <View>
                          12
                          <View>
                            13
                            <View>
                              14
                              {/* 注意 Text !!! */}
                              <Text>
                                15
                              </Text>
                            </View>
                          </View>
                        </View>
                      </View>
                    </View>
                  </View>
                </View>
              </View>
            </View>
          </View>
        </View>
      </View>
    </View>
  </View>
);
```

### 报错信息

<img width="1344" alt="截屏2020-04-2119 57 31" src="https://user-images.githubusercontent.com/127009/79863703-c5b90d80-840a-11ea-9cce-7bb49883e760.png">
<img width="1339" alt="截屏2020-04-2119 58 28" src="https://user-images.githubusercontent.com/127009/79863724-ce114880-840a-11ea-8e01-8b67d99fbaf5.png">
<img width="1335" alt="截屏2020-04-2119 59 32" src="https://user-images.githubusercontent.com/127009/79863736-d5385680-840a-11ea-8768-5ecef653b75b.png">

### 系统信息

taro 3.0.0-beta.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
text 节点不能包括 view 节点，这是小程序的原因，我认为这样做也没错。你把最后 16 的 text 标签改为 view 就行了

**Comment by cncolder** [comment]
@yuche 你误会了, "15"这个文字也没有显示.

**Comment by yuche** [comment]
text 元素也不能包含自定义组件，因此现在只能在渲染层级达到阈值（默认是 15 级）时给开发者一个警告，要求手动改变应用代码的层级，避免触发阈值时刚好是一个 text 组件的情况。例如：

```jsx
export default () => (
  <View>
    1
    <View>
      2
      <View>
        3
        <View>
          4
          <View>
            5
            <View>
              6
              <View>
                7
                <View>
                  8
                  <View>
                    9
                    <View>
                      10
                      <View>
                        11
                        <View>
                          12
                          <View>
                            13
                            <View>
                              14
                              {/* 15层是 Text，我们需要再加一个 View 或其它元素把他包住 */}
                              <Text>
                                15
                              </Text>
                            </View>
                          </View>
                        </View>
                      </View>
                    </View>
                  </View>
                </View>
              </View>
            </View>
          </View>
        </View>
      </View>
    </View>
  </View>
);
```

**Comment by cncolder** [comment]
可行, 既然是迈不过的槛, 有个提示就很好.

**Comment by Chen-jj** [comment]
3.0.19 之后根治

**Comment by JNUfeatherwit** [comment]
> 3.0.19 之后根治

现在是3.1.0-beta.4，并没有根治

**Comment by z3rog** [comment]
> > 3.0.19 之后根治
> 
> 现在是3.1.0-beta.4，并没有根治
3.1.0-beta.4 是在 3.0.19 之前 release 的

**Comment by z3rog** [comment]
> > 3.0.19 之后根治
> 
> 现在是3.1.0-beta.4，并没有根治


3.1.0-beta.4 是在 3.0.19 前 release 的

**Comment by Chen-jj** [comment]
> > > 3.0.19 之后根治
> > 
> > 
> > 现在是3.1.0-beta.4，并没有根治
> 
> 3.1.0-beta.4 是在 3.0.19 前 release 的

3.1.0-beta.5 会合入，这周会发版。

**Comment by iNiL0119** [comment]
看了楼上说3.0.19根治，刚好我也是3.0.18遇到这个问题，最后一层是<View>{...}</View>提示’请在此元素外再套一层非 Text 元素：<text>Javascript学习体验课包</text>‘，的确如上所说的嵌套第15层也就是第16层的时候如果是文本，需要多加一层View或者Text或其他组件

**Comment by day-day-sleep** [comment]
现在貌似微信小程序还能重现这个问题。 3.1.4 以及3.2.15都试过了。头条小程序表现正常

**Comment by day-day-sleep** [comment]
> 3.0.19 之后根治

现在貌似微信小程序还能重现这个问题。 3.1.4 以及3.2.15都试过了
