### ISSUE TITLE
[React Native] Taro 2.0.15 版本 /*  #ifndef rn */ 标识符对@import 无效

### ISSUE THREAD

**Issue by Fantasy9527** [NervJS/taro#6055]
### 问题描述

```less
/*  #ifndef rn */
@import './styles/reset.less';
@import './styles/theme.less';
/*  #endif  */

```

### 复现步骤

[React Native] Taro 2.0.15 版本 /*  #ifndef rn */ 标识符对@import 无效

**Comment by little-buddy** [comment]
taro 用来实现 react-native 的坑不多吗？还有在坚持的？

**Comment by Pines-Cheng** [comment]
貌似是  `/*  #ifdef rn */` 有效，`/*  #ifndef rn */` 无效。

**Comment by Pines-Cheng** [comment]
https://github.com/NervJS/taro/pull/6405
