### ISSUE TITLE
yarn install 的@tarojs/cli 与 package.json 里的版本不一致

### ISSUE THREAD

**Issue by PlutoCA** [NervJS/taro#6058]
### 问题描述
package.json 里面 @tarojs/cli 版本是 2.1.4 。依赖删除后重新yarn install 之后 下载的版本却是2.1.5.
导致项目编译失败
package.json
![image](https://user-images.githubusercontent.com/31099607/79824530-03954200-83c9-11ea-9e35-b44fdf592008.png)
node_modules\@tarojs\cli\package.json
![image](https://user-images.githubusercontent.com/31099607/79824558-1576e500-83c9-11ea-89cf-188eae02a902.png)

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 系统信息
```
  Taro CLI 2.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Users\elvis\AppData\Local\Temp\yarn--1587441667512-0.5986143294292863\node.CMD
      Yarn: 1.19.1 - C:\Users\elvis\AppData\Local\Temp\yarn--1587441667512-0.5986143294292863\yarn.CMD
      npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Garfield550** [comment]
你把 `"@tarojs/cli": "^2.1.4"` 的 `^` 字符删了。

![image](https://user-images.githubusercontent.com/3471836/79935381-5f260500-8487-11ea-93fa-3c93d7a00ea4.png)

**Comment by PlutoCA** [comment]
> 你把 `"@tarojs/cli": "^2.1.4"` 的 `^` 字符删了。
> 
> ![image](https://user-images.githubusercontent.com/3471836/79935381-5f260500-8487-11ea-93fa-3c93d7a00ea4.png)

欧克，知道了。谢谢
