### ISSUE TITLE
希望Taro支持spread表达式

### ISSUE THREAD

**Issue by vonweb** [NervJS/taro#606]
在组件内使用spread表达式，报编译失败，提示
Error: JSX 参数暂不支持 ...spread 表达式

**Comment by luckyadam** [comment]
贴一下你的代码

**Comment by yuche** [comment]
微信要求每一个 props 都具体指明，除非未来开放更多能力，否则看不到支持的可能性。

**Comment by vonweb** [comment]
@yuche 大神知道react是如何实现的吗，如果知道麻烦您告知react实现这块功能的源码或原理
