### ISSUE TITLE
Taro next beta4,Taro.uploadFile不执行

### ISSUE THREAD

**Issue by yz1311** [NervJS/taro#6064]
### 问题描述

Taro.uploadFile会不执行，准确说是卡死，success/fail/complete均不会回调，后面的代码也不会执行

但是换成wx.uploadFile就可以

### 复现步骤
```
Taro.uploadFile
```

### 期望行为

正常执行

### 系统信息

Taro CLI 3.0.0-beta.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/webpack-runner: 3.0.0-beta.4 => 3.0.0-beta.4 
      eslint-config-taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      react: ^16.10.0 => 16.13.0 
    npmGlobalPackages:
      typescript: 3.7.4

**Comment by yuche** [comment]
没能复现，你能写一个小 demo 看下吗

**Comment by yz1311** [comment]
> 没能复现，你能写一个小 demo 看下吗

不知道是不是代码有问题，不过升级到beta5后，这个问题没了.
