### ISSUE TITLE
taro cli 创建完项目后启动报错

### ISSUE THREAD

**Issue by xkmy** [NervJS/taro#6068]
### 问题描述
taro cli 创建完项目后 yarn run dev:h5 启动报错
![image](https://user-images.githubusercontent.com/44152845/79938424-2b4edd80-848f-11ea-93d9-97cace8d3bb7.png)

### 复现步骤

1.taro init test 
2.yarn run dev:h5
3.报错

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

正常运行
### 报错信息

Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: E:/my/react-projects/taro/taro/.temp/app.js: Unexpected token (45:9)
![image](https://user-images.githubusercontent.com/44152845/79938641-c3e55d80-848f-11ea-9e07-4fc61d437d5a.png)

### 系统信息

![image](https://user-images.githubusercontent.com/44152845/79938773-11fa6100-8490-11ea-9528-ed3af5610da9.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
没有复现问题，麻烦提供一个可以复现的 demo

**Comment by xkmy** [comment]
> 没有复现问题，麻烦提供一个可以复现的 demo

https://github.com/xkmy/taro-test

**Comment by xkmy** [comment]
> 没有复现问题，麻烦提供一个可以复现的 demo

复现仓库地址发了，麻烦帮忙看下

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/80181441-76a3f000-8637-11ea-9a38-21fbe492ee31.png)
没有复现问题
