### ISSUE TITLE
分包加载，Config 声明缺少“subPackages” 定义

### ISSUE THREAD

**Issue by aijiacy** [NervJS/taro#607]
**问题描述**
分包加载，使用Typescript时，Config声明缺少subPackages的定义。

**复现步骤**
![1536636995179](https://user-images.githubusercontent.com/8082603/45336630-01e18680-b5b7-11e8-98e6-e6dfbc9f9dc2.jpg)
#
**期望行为**
更新声明定义文件

**系统信息**
 - 操作系统: [e.g. macOS 13]
 - Taro 版本 [e.g. v.1.0.0.beta.26]
 - Node.js 版本 [e.g. v8.11.3]

**Comment by luckyadam** [comment]
#609
