### ISSUE TITLE
Taro next无法控制input输入内容

### ISSUE THREAD

**Issue by myl0204** [NervJS/taro#6070]
### 问题描述
1. 在`Input`的`onInput` 回调中return value无效，无法控制输入框内容
2. 在页面的`componentDidMount`钩子中获取节点信息,boundingClientRect回调中返回null，增加延时后可以正常拿到

### 系统信息

Taro v3.0.0-beta.4

  Taro CLI 3.0.0-beta.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /var/folders/_3/wg3rh3_n0hg717bgfzcy8rmw0000gp/T/yarn--1587534552018-0.9252288646675608/node
      Yarn: 1.22.4 - /var/folders/_3/wg3rh3_n0hg717bgfzcy8rmw0000gp/T/yarn--1587534552018-0.9252288646675608/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/components: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/webpack-runner: 3.0.0-beta.4 => 3.0.0-beta.4 
      eslint-config-taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      react: ^16.10.0 => 16.13.1 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
1. 这个事情是没办法做到的。现在 Taro 事件机制是基于 Web 标准的实现的，Web 标准的事件要求返回 `true` 或 `false` 来判定事件是否被防止预置行为（preventDefault）。如果我们不兼容标准的 Web 事件，那事件机制可能就会不兼容 React 或 Vue。我推荐你使用 `cursor` 属性和 `value` 属性来控制。
2. `componentDidMount`（或者 Vue 的 `mounted`）只代表 Taro 的 DOM（或 H5 标准 DOM）加载，不代表小程序的真实 DOM（或 H5 的 Web Component）加载。为了解决这个问题，你应该用 `onReady` 生命周期，这点在文档有提到：
https://taro-docs.jd.com/taro/next/docs/react.html#onready

**Comment by myl0204** [comment]
@yuche 感谢回答。
 关于1：小程序的input不是受控组件，value只是他的初始值
> 键盘输入时触发，event.detail = {value, cursor, keyCode}，keyCode 为键值，2.1.0 起支持，处理函数可以直接 return 一个字符串，将替换输入框的内容。

以上是小程序`bindinput`的介绍， 如果兼容不了的话那就没法控制小程序端的input的输入值了

**Comment by myl0204** [comment]
另：关于`componentDidMount`的说明，文档有点小问题
> 此生命周期可以无法访问 Current.router

是可以还是不可以😂

**Comment by yuche** [comment]
> @yuche 感谢回答。
> 关于1：小程序的input不是受控组件，value只是他的初始值
> 
> > 键盘输入时触发，event.detail = {value, cursor, keyCode}，keyCode 为键值，2.1.0 起支持，处理函数可以直接 return 一个字符串，将替换输入框的内容。
> 
> 以上是小程序`bindinput`的介绍， 如果兼容不了的话那就没法控制小程序端的input的输入值了

我写了一个小 demo，应该是可以控制的，`input` 标签在输入后会一直有 `+86`：
```jsx
export default () => {
  const [ value, setValue ] = useState('')
  return (
    <View>
        <Input
          onInput={(e) => {
            setValue(value.startsWith('+86') ? e.detail.value : '+86' + e.detail.value)
          }}
          value={value}
        />
    </View>
  )
}
```

可以访问，但不一定当前的 `Current.router`，`onShow` 生命周期访问 router 最准确，这是每次 router 信息更新的时候。

**Comment by myl0204** [comment]
> > @yuche 感谢回答。
> > 关于1：小程序的input不是受控组件，value只是他的初始值
> > > 键盘输入时触发，event.detail = {value, cursor, keyCode}，keyCode 为键值，2.1.0 起支持，处理函数可以直接 return 一个字符串，将替换输入框的内容。
> > 
> > 
> > 以上是小程序`bindinput`的介绍， 如果兼容不了的话那就没法控制小程序端的input的输入值了
> 
> 我写了一个小 demo，应该是可以控制的，`input` 标签在输入后会一直有 `+86`：
> 
> ```js-jsx
> export default () => {
>   const [ value, setValue ] = useState('')
>   return (
>     <View>
>         <Input
>           onInput={(e) => {
>             setValue(value.startsWith('+86') ? e.detail.value : '+86' + e.detail.value)
>           }}
>           value={value}
>         />
>     </View>
>   )
> }
> ```
> 
> 可以访问，但不一定当前的 `Current.router`，`onShow` 生命周期访问 router 最准确，这是每次 router 信息更新的时候。

没法做到限制`input`的输入，比如 最大/最小值，比如不能输入某个具体的字符
比如我想限制input的值最大为10，当输入11时候，会变成10，但是继续输入则会变成以10开头的数字，`value`的值是保持在10的
```jsx
export default () => {
  const [value, setValue] = React.useState('')
  return (
    <View>
      <Input
        type='number'
        onInput={e => {
          if (Number(e.detail.value) > 10) {
            setValue('10')
          } else {
            setValue(e.detail.value)
          }
        }}
        value={value}
      />
    </View>
  )
}
```

**Comment by yuche** [comment]
> > > @yuche 感谢回答。
> > > 关于1：小程序的input不是受控组件，value只是他的初始值
> > > > 键盘输入时触发，event.detail = {value, cursor, keyCode}，keyCode 为键值，2.1.0 起支持，处理函数可以直接 return 一个字符串，将替换输入框的内容。
> > > 
> > > 
> > > 以上是小程序`bindinput`的介绍， 如果兼容不了的话那就没法控制小程序端的input的输入值了
> > 
> > 
> > 我写了一个小 demo，应该是可以控制的，`input` 标签在输入后会一直有 `+86`：
> > ```
> > export default () => {
> >   const [ value, setValue ] = useState('')
> >   return (
> >     <View>
> >         <Input
> >           onInput={(e) => {
> >             setValue(value.startsWith('+86') ? e.detail.value : '+86' + e.detail.value)
> >           }}
> >           value={value}
> >         />
> >     </View>
> >   )
> > }
> > ```
> > 
> > 
> > 可以访问，但不一定当前的 `Current.router`，`onShow` 生命周期访问 router 最准确，这是每次 router 信息更新的时候。
> 
> 没法做到限制`input`的输入，比如 最大/最小值，比如不能输入某个具体的字符
> 比如我想限制input的值最大为10，当输入11时候，会变成10，但是继续输入则会变成以10开头的数字，`value`的值是保持在10的
> 
> ```js-jsx
> export default () => {
>   const [value, setValue] = React.useState('')
>   return (
>     <View>
>       <Input
>         type='number'
>         onInput={e => {
>           if (Number(e.detail.value) > 10) {
>             setValue('10')
>           } else {
>             setValue(e.detail.value)
>           }
>         }}
>         value={value}
>       />
>     </View>
>   )
> }
> ```

你可以先这样尝试欺骗 React 的 diff 的算法，是否支持直接设置相同值也触发渲染我们还需要调研更多信息：

```jsx
export default () => {
  const [ value, setValue ] = useState('')
  // const forceUpdate = useForceUpdate()
  return (
    <View>
        <Input
          type='number'
          onInput={(e) => {
            if (Number(e.detail.value) > 10) {
              setValue(value === '10' ? 10 : '10')
            } else {
              setValue(e.detail.value)
            }
          }}
          value={value}
        />
    </View>
  )
}
```

**Comment by shjyh** [comment]
这个需求还是很常用，可以直接加一个hook，如useInputState，在小程序中即使设置相同值也触发render
目前我自己写了一个userInputState，内部切换string的装箱类型与拆箱类型欺骗diff算法强制刷新

**Comment by shjyh** [comment]
@yuche 小程序绝大多数场景控制输入框值往往是阻止输入，可以把event.preventDefault的功能用起来

![image](https://user-images.githubusercontent.com/7910808/85943984-442faf80-b966-11ea-8ccc-3f0ff0ac82c1.png)

**Comment by holidayfhd** [comment]
为什么不放开onkeyup onkeydown呢，有些类似只能输入数字，阻止用户输入某些字符的需求难以实现啊

**Comment by RunningCoderLee** [comment]
请问这个问题为什么被关闭了呢，感觉并没有给出一个比较合理的解决办法，上面说的欺骗 react 的demo 感觉不应该作为这个问题的最终解法吧 @yuche 

PS: 另外文档里说 `value` 的解释是初始值，那它是不是等同于 defaultValue 的概念？那在组件受控的时候就不应该用这个属性才对吧。

还有我看 API 里有 `controlled` 这个属性用来作为受控有否的开关，但是好像没找到其他跟这个属性相关联的属性是哪些，意思是  `controlled`  这个为 `true` 后， `onInput` 方法里 return 一个字符串才能实现更改输入框内值的功能么？（我自己测试好像又不行🤔）


其实这个需求应该还挺纯粹和常见的，就是需要完全控制 input，通过 `onChange(或 onInput)` 和 `value` 2个属性来实现，但现实情况是向 https://github.com/NervJS/taro/issues/6070#issuecomment-617622599 中说的一样，在某些情况下会出现输入内容和期望内容不一致的情况（react 本身并不存在这个问题）

**Comment by lxsunbin** [comment]
> 请问这个问题为什么被关闭了呢，感觉并没有给出一个比较合理的解决办法，上面说的欺骗 react 的demo 感觉不应该作为这个问题的最终解法吧 @yuche
> 
> PS: 另外文档里说 `value` 的解释是初始值，那它是不是等同于 defaultValue 的概念？那在组件受控的时候就不应该用这个属性才对吧。
> 
> 还有我看 API 里有 `controlled` 这个属性用来作为受控有否的开关，但是好像没找到其他跟这个属性相关联的属性是哪些，意思是 `controlled` 这个为 `true` 后， `onInput` 方法里 return 一个字符串才能实现更改输入框内值的功能么？（我自己测试好像又不行🤔）
> 
> 其实这个需求应该还挺纯粹和常见的，就是需要完全控制 input，通过 `onChange(或 onInput)` 和 `value` 2个属性来实现，但现实情况是向 [#6070 (comment)](https://github.com/NervJS/taro/issues/6070#issuecomment-617622599) 中说的一样，在某些情况下会出现输入内容和期望内容不一致的情况（react 本身并不存在这个问题）

遇到了同样的问题，请问你是如何解决的呀？
