### ISSUE TITLE
h5端rem方案：deviceRatio的作用是什么？

### ISSUE THREAD

**Issue by huaziHear** [NervJS/taro#6071]
### 问题描述
使用designWidth和deviceRatio配置自适应方案的时候发现，无论deviceRatio怎么设置，rem的计算方式总是320屏幕，1rem=20px。假设目前的需求是，375屏幕rootValue=37.5, 也就是想 1rem可以等于37.5px。发现没办法做到。

### 复现步骤

```js
{
    designWidth: 375,
    deviceRatio: {
        '640': 2.34 / 2,
        '750': 1,
        '828': 1.81 / 2,
        '375': 1 / 2
    }
}

// 设置html根字体大小的脚本被限制成了
fontSite = clientWith / 320 * 20 + 'px'
```

### 期望行为
假设我的脚本是

```js
  fontSite = clientWidth / 10 + 'px'
```
那配置项里面的designWidth和deviceRatio应该怎么设置？（设计稿375）

**Comment by luckyadam** [comment]
你可以改一下 HTML 里面那段自适应的脚本

**Comment by xmsz** [comment]
脑袋疼
默认配置没有变
然后我css写的是
```
width: 375px
```

对于750px就是一半才对


然后真实的情况是
视图大小：iphone8(375x768)

真实单位 8rem
真实宽度:  213px


预期是
真实宽度: 375 / 2 = 187px

完全不对啊

**Comment by Liar0320** [comment]
> 你可以改一下 HTML 里面那段自适应的脚本

这个在哪里可以修改，文档上我已经找了好像都没找到
