### ISSUE TITLE
[h5]2.1.2 Swiper 未设置autoplay属性，加载后会自动滚动一次

### ISSUE THREAD

**Issue by tangshuoup** [NervJS/taro#6073]
问题描述
[h5]2.1.2 Swiper 未设置autoplay属性，加载后会自动滚动一次

复现步骤
       

` <Swiper`
`className='test-h'`
`indicatorColor='#999'`
`indicatorActiveColor='#333'`
`circular`
`indicatorDots>`
`<SwiperItem>`
`     <View className='demo-text-1'>1</View>`
`</SwiperItem>`
`<SwiperItem>`
`     <View className='demo-text-2'>2</View>`
`</SwiperItem>`
`<SwiperItem>`
`     <View className='demo-text-3'>3</View>`
`</SwiperItem>`
`</Swiper>`

期望行为
加载后不自动滚动一次

报错信息
系统信息
"@tarojs/components": "2.1.2",
"@tarojs/redux": "2.1.2",
"@tarojs/redux-h5": "2.1.2",
"@tarojs/router": "2.1.2",
"@tarojs/taro": "2.1.2",
"@tarojs/taro-h5": "2.1.2",
"@tarojs/taro-weapp": "2.1.2",

**Comment by ZakaryCode** [comment]
未能复现到该问题，可以升级试试

**Comment by 17** [comment]
2.1.5 版本重现，浏览器会报以下错误。
```
Uncaught TypeError: Cannot read property 'autoplay' of undefined
    at eval (swiper.esm.bundle.js?564c:6124)
```

**Comment by yulrosy** [comment]
> 现，浏览器会报以下错误。

2.2.2也有

**Comment by ZakaryCode** [comment]
> > 现，浏览器会报以下错误。
> 
> 2.2.2也有

方便提交 demo 或者详细描述复现流程？
