### ISSUE TITLE
CPU 高使用率，导致编辑器卡顿等（已确认非编辑器问题）

### ISSUE THREAD

**Issue by Q-Qplus1s** [NervJS/taro#6077]
### 问题描述
npm run dev:weapp 
启动占用大量CPU资源，导致电脑整体卡顿。
版本：2.1.4
![node](https://user-images.githubusercontent.com/50064165/80062695-e5fddf00-8566-11ea-9171-0cbfa259c16d.png)

### 复现步骤

1. 启动命令：npm run dev:weapp
2. 打开任务管理器查看进程信息

### 期望行为

正常使用，不卡顿

### 系统信息

� Taro v2.1.4

  Taro CLI 2.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.0 - D:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

### 尝试定位

- 切换编辑器 vscode 或者 webstorm 无效果
- 关闭微信开发者工具，无效果

2020/4/24 补充：
- 升级 node npm 版本 问题仍然存在，定位怀疑webpack watch 监听了 node_modules 全部文件，导致高CPU问题；
- 尝试修改 config.js 的watchOptions 选项：watchOptions: { ignored: /node_modules/ }, 无效果，任然监听 node_modules 下文件
- 尝试修改 mini 配置的 webpackChain 配置：
```
  mini: {
    webpackChain (chain, webpack) {
      chain.merge({
        watchOptions: { ignored: /node_modules/},
      });
    },
  },
```
无效果，任然监听 node_modules 下文件

### 再次补充
确认 watchOption 无效问题原因：
https://github.com/NervJS/taro/blob/8f6617f79115812c01cb10efe08fe58c64e37d61/packages/taro-mini-runner/src/index.ts#L41 
此处代码对watchOption 进行了覆盖，导致ignore 参数无效，建议更改此处代码，merge 配置，目前修改@tarojs/mini-runner 包下的dist/index.js 文件，增加 ignore 参数后CPU占用明显下降：
![修改watch](https://user-images.githubusercontent.com/50064165/80172766-6d5b5900-8620-11ea-8d1a-2318783cdf41.png)

__请官方确认 watchOptions 配置是否有效，并补全文档__

相关 issues、pull ：https://github.com/NervJS/taro/pull/2658
PS：对于此处的讨论并不是很赞同，首先相信大多数开发者不会频繁更改 node_modules 下的文件（除非基于bug修复），99%的开发时间都不会去改动这里，watch 所有文件只会降低开发效率，浪费CPU资源，其次如果基于与主流方案配置兼容考虑，应该开放watchOptions选项, merge，不是写死

**Comment by luckyadam** [comment]
建议用独立的终端工具如 iterm2 来执行 node 命令，如果是 windows 可以用 wsl

**Comment by Q-Qplus1s** [comment]
@luckyadam 切换 wsl效果一样，建议还是在config.js 上支持 watchOptions 配置，代码上 merge 用户配置即可。我电脑配置不差，以前同时跑多个后台工程，开PS都OK的

**Comment by luckyadam** [comment]
> @luckyadam 切换 wsl效果一样，建议还是在config.js 上支持 watchOptions 配置，代码上 merge 用户配置即可。我电脑配置不差，以前同时跑多个后台工程，开PS都OK的

配置可以开放出来

**Comment by shengbox** [comment]
遇到同样的问题，npm run dev:weapp 时风扇狂响npm run dev:h5 则正常

**Comment by shengbox** [comment]
本来我3万块钱的 MacBook Pro 狂响，按照 @Q-Qplus1s 的方法修改dist文件后，世界都安静了

**Comment by bingowen** [comment]
@shengbox 感觉还是很卡，微信开发者工具里面点击反应都很慢，能告知一下具体怎么改吗？
![image](https://user-images.githubusercontent.com/13950627/85005977-1db28d00-b18c-11ea-92ee-e955f7dc42e2.png)

**Comment by Leadrive** [comment]
升级到2.x后，CPU占用达到80%，请教如何修改？ @Q-Qplus1s

**Comment by Leadrive** [comment]
简直崩溃，无法正常工作了，现在编译完后，只好把监控中断掉，CPU吃得太厉害。

**Comment by Q-Qplus1s** [comment]
@Leadrive 调用任务管理器,看是否时node 进程吃的CPU, 如果是, 参考上面做法
> 修改@tarojs/mini-runner 包下的dist/index.js 文件，增加 ignore 参数 watchOptions: { ignored: /node_modules/},
其他的可能是微信开发工具问题:
1. 升级开发者工具到新版本
2. 清除开发者工具的代码缓存(用得久的话缓存惊人!)

**Comment by Leadrive** [comment]
> @Leadrive 调用任务管理器,看是否时node 进程吃的CPU, 如果是, 参考上面做法
> 
> > 修改@tarojs/mini-runner 包下的dist/index.js 文件，增加 ignore 参数 watchOptions: { ignored: /node_modules/},
> > 其他的可能是微信开发工具问题:
> 
> 1. 升级开发者工具到新版本
> 2. 清除开发者工具的代码缓存(用得久的话缓存惊人!)

请问watchOptions添加在什么位置？

**Comment by Leadrive** [comment]
@Q-Qplus1s 就是node吃了80%CPU，把它停掉后，就正常。微信开发工具是正常的。
watchOptions不知道加到哪一位置。

**Comment by Leadrive** [comment]
今天在另外一台电脑，WIN7 X64，node v10.16.0，没有吃CPU
换回WIN10，X64，node v10.16.0，CPU 80%
二者是同样的项目，都是新建的目录，yarn，然后npm run dev:weapp

**Comment by Q-Qplus1s** [comment]
@Leadrive node_modules/@tarojs/mini-runner/dist/index.js
ctrl + F  => 'watchOptions'

**Comment by Leadrive** [comment]
@Q-Qplus1s 
yarn完后，node_modules/@tarojs/mini-runner/dist/index.js文件中，并没有watchOptions项，
能否贴个完整的内容？谢谢。

**Comment by Q-Qplus1s** [comment]
@Leadrive 老哥 你先了解下webpack的watchOption 放在哪不就知道了吗， 你可以在文件上搜索 aggregateTimeout，在下面添加watchOption 属性配置

**Comment by Leadrive** [comment]
直接升级到3.0，目前已不存在此问题。
