### ISSUE TITLE
lodash 报错 Cannot read property 'now' of undefined

### ISSUE THREAD

**Issue by Przeblysk** [NervJS/taro#6078]
### 问题描述
lodash.xxx时候报错的问题
报错原因：Function('return this')() 返回的结果是空的，导致root.Date.now()等报错，如果用到其他对象比如String,Array,Map等也会出错

**在不使用插件的情况下可以正常使用lodash的方法，在使用了plugins的情况会会出现错误**

### 复现步骤

1.Taro.init 新建项目
2. app.jsx 添加plugins ，我添加了网易七鱼客服插件
3. 在index页面使用this.onClickHandleThrottle = debounce(this.onClickHandle, 1000, this)
4. 报错Cannot read property 'now' of undefined

```js


```

### 报错信息

![image](https://user-images.githubusercontent.com/18001272/80063356-578a5d00-8568-11ea-83c6-304b25a03e8d.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
Taro 版本多少

**Comment by Przeblysk** [comment]
![image](https://user-images.githubusercontent.com/18001272/80172843-a398d880-8620-11ea-9e5d-0e0d9d59a65b.png)
Package.json
![image](https://user-images.githubusercontent.com/18001272/80172897-caefa580-8620-11ea-93ec-317299088dd2.png)

**Comment by Przeblysk** [comment]
> Taro 版本多少

2.1.5

**Comment by yulrosy** [comment]
我也用的qiyu插件，2.2.9遇到这个问题了

**Comment by Przeblysk** [comment]
> 我也用的qiyu插件，2.2.9遇到这个问题了

可能是七鱼插件的问题，我现在是单独引入文件使用

**Comment by Przeblysk** [comment]
> 我也用的qiyu插件，2.2.9遇到这个问题了

单独引入lodash的功能

**Comment by yuuk** [comment]
同遇到，版本 2.0.2

**Comment by Barrior** [comment]
遇到同样问题，如果引用的 node_module 里的包是用 lodash/debounce 构建出来的，就会产生这样的错误，
示例：
```typescript
import logger from '@mp-logger/logger'

class App extends Component<{ children: React.ReactNode }> {
  onLaunch() {
    logger.initSetting()
  }
}
```
@mp-logger/logger 源码：
```typescript
import debounce from 'lodash/debounce'

class Logger {
  initSetting(setting: Setting) {
     // 省略部分代码

    // 此处使用 debounce
    this.sendDataDebounced = debounce(this.sendData, 300)
  }
}
```

@mp-logger/logger 发布成 node_module 包的源码：
```javascript
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.mpLogger = factory());
}(this, (function () { 'use strict';

//--------------- lodash 源码 --------------//
var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};

/** Detect free variable `global` from Node.js. */

var freeGlobal = typeof commonjsGlobal == 'object' && commonjsGlobal && commonjsGlobal.Object === Object && commonjsGlobal;

var _freeGlobal = freeGlobal;

/** Detect free variable `self`. */
var freeSelf = typeof self == 'object' && self && self.Object === Object && self;

/** Used as a reference to the global object. */
var root = _freeGlobal || freeSelf || Function('return this')();

var _root = root;

var now = function() {
      return _root.Date.now();
};
//--------------- lodash 源码 end --------------//

  var Logger = /** @class */ (function () {
    function Logger() {}

    Logger.prototype.initSetting = function (setting) {
      // 省略部分代码

      // 此处使用 debounce
      this.sendDataDebounced = debounce_1(this.sendData, 300);
   }
  }());

  var index = new Logger();
  return index;
})));
```

运行就会如下错误：

```javascript
TypeError: Cannot read property 'now' of undefined

 at now (index.js:108)
    at Logger.debounced [as sendDataDebounced] (index.js:490)
```

定位问题是编译后的 `_root` 值为 `undefined` 了。

```javascript
var now = function() {
  return _root.Date.now();
};
```

再定位问题则是 freeGlobal 为 false 了，而拷贝如下代码在微信开发者工具 Console 面板运行，freeGlobal 值为 window。
```javascript
var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};

/** Detect free variable `global` from Node.js. */

var freeGlobal = typeof commonjsGlobal == 'object' && commonjsGlobal && commonjsGlobal.Object === Object && commonjsGlobal;
```

麻烦涛哥看看呐 @luckyadam

**Comment by cat-walk** [comment]
在mpvue中也遇到了类似的问题，原因和楼上一样，lodash.debounce 和 xx.Date.now 的问题

**Comment by luckyadam** [comment]
用 lodash-es 试试

**Comment by Duo-Huang** [comment]
> 用 lodash-es 试试

试了还是报这个错

**Comment by Phlen** [comment]
3.2.12版本下仍能复现
![image](https://user-images.githubusercontent.com/8215182/122342094-c6015a00-cf76-11eb-87d5-f3974cd3293a.png)

**Comment by xoptimal** [comment]
该问题还是存在, 请问有具体的解决办法吗 ,   taro version: 3.2.12

**Comment by xiamibuchi** [comment]
> 该问题还是存在, 请问有具体的解决办法吗 , taro version: 3.2.12

用了这个方式暂时在微信小程序内解决了：https://github.com/NervJS/taro/issues/8098#issuecomment-731915642

**Comment by towry** [comment]
目前用的 taro v3.4.3。

开发环境下没问题。

但是生产环境下构建后，然后同时开发者工具-本地设置里勾选了“将 js 编译成 es5“，会有类似的报错，取消勾选则没有这个报错。或者用 vscode将 vendor.js 去压缩 后，也没有报错。

**Comment by Sano1217** [comment]
> 用 lodash-es 试试

我这边 lodash-es也有这个问题，原因好像是因为this的问题。改成函数组件不会报错，但是函数组件里，debounce不起作用

**Comment by yijinc** [comment]
碰到同样问题，有解决的吗

**Comment by anyesu** [comment]
参考 https://github.com/NervJS/taro/issues/8098#issuecomment-2260371759
