### ISSUE TITLE
[Feature request]H5测有没有监听tabbar点击的方法 类似onTabItemTap

### ISSUE THREAD

**Issue by smilebuz** [NervJS/taro#6079]
### 问题描述

H5测有没有监听tabbar点击的方法 类似小程序测的onTabItemTap 现在采用的是查找元素后手动绑定的方法

### 期望行为

期望H5测可以有监听tabbar点击的方法

**Comment by luckyadam** [comment]
H5 还暂未实现

**Comment by smilebuz** [comment]
好的 谢谢
