### ISSUE TITLE
Taro.requestPayment 调用支付貌似在微信H5里不能用啊

### ISSUE THREAD

**Issue by o-x-o** [NervJS/taro#6080]
### 问题描述

Taro.requestPayment 调用支付貌似在微信H5里不能用啊。
调用之后提示”没有传appId“（说明确实调用了微信浏览器的sdk）。我传了，可能是Taro的这个方法内部不支持。因为Taro的文档上也没有写这个参数，但是H5端确实是需要这个参数。

### 复现步骤

1. 在微信H5里先获取后端的支付验证信息，有appId，timeStamp，nonceStr等等参数。
2. 调用Taro.requestPayment尝试调用微信浏览器的SDK。并把后端获取的验证信息传入这个方法。
3. 确实调用了微信浏览器的支付方法。
4. 但是提示没有传appId。

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

可以把appId(注意大小写)这个参数带进去，传给微信SDK。使Taro.requestPayment这个方法真的在微信H5端被支持，现在看到貌似只实现了一半。

### 报错信息

没有传appId

### 系统信息

Taro v1.3.17

  Taro CLI 1.3.17 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.1 - /usr/local/bin/node
      npm: 6.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 1.3.17 => 1.3.17 
      @tarojs/plugin-babel: 1.3.17 => 1.3.17 
      @tarojs/plugin-csso: 1.3.17 => 1.3.17 
      @tarojs/plugin-sass: 1.3.17 => 1.3.17 
      @tarojs/plugin-uglifyjs: 1.3.17 => 1.3.17 
      @tarojs/router: 1.3.17 => 1.3.17 
      @tarojs/taro: 1.3.17 => 1.3.17 
      @tarojs/taro-alipay: 1.3.17 => 1.3.17 
      @tarojs/taro-h5: 1.3.17 => 1.3.17 
      @tarojs/taro-swan: 1.3.17 => 1.3.17 
      @tarojs/taro-tt: 1.3.17 => 1.3.17 
      @tarojs/taro-weapp: 1.3.17 => 1.3.17 
      @tarojs/webpack-runner: 1.3.17 => 1.3.17 
      eslint-config-taro: 1.3.17 => 1.3.17 
      eslint-plugin-taro: 1.3.17 => 1.3.17 
      nerv-devtools: ^1.4.4 => 1.4.4 
      nervjs: ^1.4.4 => 1.4.4 
      react: ^16.8.6 => 16.8.6 
      stylelint-config-taro-rn: 1.3.17 => 1.3.17 
      stylelint-taro-rn: 1.3.17 => 1.3.17 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
你可以试试直接用 wx. requestPayment 行不行

**Comment by o-x-o** [comment]
> 你可以试试直接用 wx. requestPayment 行不行

不行，因为微信浏览器里没有这个方法，这个是小程序里的。

**Comment by o-x-o** [comment]
> 你可以试试直接用 wx. requestPayment 行不行

不行，因为微信浏览器里没有这个方法，这个是小程序里的。
目前，我自己写的H5页面用的是 `WeixinJSBridge.invoke('getBrandWCPayRequest')` 这个方法。
具体Taro.requestPayment内部调用的H5端的哪个SDK，我还没有看，不太清楚。

**Comment by Littly** [comment]
估计是typings的问题 可以先加个`// @ts-ignore`绕过下

**Comment by o-x-o** [comment]
> 估计是typings的问题 可以先加个`// @ts-ignore`绕过下

? typescript？ 你是回答的我这个问题吗？这个type有什么关系。我都没用type @ts-ignore 加哪

**Comment by o-x-o** [comment]
这都开始乱答了吗？

**Comment by Littly** [comment]
已经提示”没有传appId“，那就把appid传进去就好了，如果typings报警了就加 `// @ts-ignore`绕过。
不知道appid哪里看可以上微信公众号开发文档找。

**Comment by o-x-o** [comment]
我的问题描述里已经说“我传了”。我知道APPID怎么获取。评论前请认真看问题可以吗？

**Comment by o-x-o** [comment]
> 已经提示”没有传appId“，那就把appid传进去就好了，如果typings报警了就加 `// @ts-ignore`绕过。
> 不知道appid哪里看可以上微信公众号开发文档找。

我的问题描述里已经说“我传了”。我知道APPID怎么获取。评论前请认真看问题可以吗？

**Comment by Littly** [comment]
`requestPayment` 内部是微信jssdk的 `wx.chooseWXPay`。可以看看代码吗？

**Comment by o-x-o** [comment]
我本来使用的是 WeixinJSBridge.invoke('getBrandWCPayRequest') 。我可以先试试用 wx.chooseWXPay 这个API，这个API是要事先配置wx.config。这个能成功的话，我再试试 Taro. requestPayment 看看能不能成功。
