### ISSUE TITLE
设置Progress组件的strokeWidth属性不起作用

### ISSUE THREAD

**Issue by sussertod891015** [NervJS/taro#6083]
### 问题描述

设置Progress组件的strokeWidth属性不起作用

### 复现步骤

1. 写一个progress组件，并设置它的一些属性
2. 修改strokeWidth，无效

```js
<Progress
	activeColor="#ffd6c7"
	backgroundColor="#f68d6f"
	active
	percent={60}
	duration={100}
	strokeWidth={2}
/>


```

### 期望行为

修改strokeWidth可以表现正常

### 报错信息

无报错

### 系统信息

Taro v3.0.0-beta.4

  Taro CLI 3.0.0-beta.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
      npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      @tarojs/webpack-runner: 3.0.0-beta.4 => 3.0.0-beta.4 
      eslint-config-taro: 3.0.0-beta.4 => 3.0.0-beta.4 
      nervjs: ^1.5.0 => 1.5.6 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@sussertod891015 复现不了，升级到最新版再试试

```js
render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <Progress
          activeColor="#ffd6c7"
          backgroundColor="#f68d6f"
          active
          percent={60}
          duration={100}
          strokeWidth={20}
        />
      </View>
    )
  }
```

![image](https://user-images.githubusercontent.com/11807297/82024640-aa1bec80-96c2-11ea-84fb-c66f394fbc8d.png)
