### ISSUE TITLE
Taro 3.0.0-beta.3 微信小程序启动报错Please do not register multiple Pages

### ISSUE THREAD

**Issue by summer88123** [NervJS/taro#6084]
### 问题描述

程序中主要有三个页面：
  WelcomePage：初始页面，负责初始化一些必要数据，会自动跳转至HomePage。
  HomePage：展示应用的主要信息，可以跳转至ListPage。
  ListPage：展示列表信息。

在app.config.ts中只配置WelcomePage和HomePage时一切正常。添加ListPage后，会偶尔出现启动报错。"Please do not register multiple Pages in core/WelcomePage.js"。

尝试删除dist目录、重新运行yarn dev:weapp、重启微信开发者工具，可能会恢复正常。

### 复现步骤

1. 在app.config.ts中添加两个页面
2. 运行yarn dev:weapp，并启动微信开发者工具
3. 在app.config.ts中添加第三个页面
4. 小程序刷新后，操作跳转第三个页面，提示如下：
![截屏2020-05-11下午3 43 23](https://user-images.githubusercontent.com/6141102/81537029-2353d080-939f-11ea-99e7-e454274c3ce0.png)
5. 重新运行yarn dev:weapp
6. 出现报错

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

程序可正常启动
### 报错信息
<img width="780" alt="WechatIMG25" src="https://user-images.githubusercontent.com/6141102/80167646-81e52480-8613-11ea-8340-0ab71d130fae.png">

### 系统信息

Taro CLI 3.0.0-beta.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/webpack-runner: 3.0.0-beta.3 => 3.0.0-beta.3 
      eslint-config-taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.10.0 => 16.13.1 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
能做一个复现仓库复现吗

**Comment by summer88123** [comment]
> 能做一个复现仓库复现吗

手动写了个Demo没能复现。
项目是从RN移植过来的，初步猜测可能是某些RN的语法产生了影响，比如style支持数组之类的。
稍后我再试试从现有的代码做些删减，看看能不能做个复现仓库出来。

**Comment by yuche** [comment]
@summer88123 复现仓库有了吗

**Comment by summer88123** [comment]
@yuche `app.config.js`中的`pages`里并没有相同的值。
最近一段时间在我本地的环境上出现比较少了，基本上删除dist，重启yarn dev:weapp，重启小程序IDE就能正常。
不过今天有新同事进入项目，在他的环境下，上面的方法不好使。但是执行yarn build:weapp是可以正常运行起来的。

**Comment by summer88123** [comment]
更新了一下复现步骤

**Comment by summer88123** [comment]
@yuche 初步定位到原因了，在`app.config.js`的`pages`中配置了某个页面，然后又在某处代码中import了这个页面，就会出现这个错误

**Comment by yuche** [comment]
这样的行为是不推荐的，因为页面文件会被一个特殊的 loader 处理，如果同一个页面多次运行这个 loader 可能会出现意想不到的情况出现。

如果确实需要使用页面组件，我们推荐把页面组件的逻辑抽象一个单独的普通组件，然后在页面中直接渲染这个普通组件，其它的地方也可以正常使用它。

之后的版本在编译时检测这样的行为会直接报错并引导到此 issue。
