### ISSUE TITLE
PageMeta 编译问题

### ISSUE THREAD

**Issue by baranwang** [NervJS/taro#6092]
### 问题描述

使用 PageMeta 编译后会在页面 json 中引入 
```json
{"usingComponents":{"page-meta":"@tarojs/components","navigation-bar":"@tarojs/components"}}
```
且未将 page-meta 编译至根节点

### 复现步骤
引入 `PageMeta`, `NavigationBar`

### 期望行为
json 中不引入，且编译至 wxml 根节点（因文档指出`只能是页面内的第一个节点`)

### 报错信息

["usingComponents"]["page-meta"]: "@tarojs/components" 未找到

### 系统信息

👽 Taro v2.1.5

  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.5 => 2.1.5 
      @tarojs/components-qa: 2.1.5 => 2.1.5 
      @tarojs/mini-runner: 2.1.5 => 2.1.5 
      @tarojs/mobx: 2.1.5 => 2.1.5 
      @tarojs/mobx-h5: 2.1.5 => 2.1.5 
      @tarojs/router: 2.1.5 => 2.1.5 
      @tarojs/taro: 2.1.5 => 2.1.5 
      @tarojs/taro-alipay: 2.1.5 => 2.1.5 
      @tarojs/taro-h5: 2.1.5 => 2.1.5 
      @tarojs/taro-qq: 2.1.5 => 2.1.5 
      @tarojs/taro-quickapp: 2.1.5 => 2.1.5 
      @tarojs/taro-swan: 2.1.5 => 2.1.5 
      @tarojs/taro-tt: 2.1.5 => 2.1.5 
      @tarojs/taro-weapp: 2.1.5 => 2.1.5 
      @tarojs/webpack-runner: 2.1.5 => 2.1.5 
      eslint-config-taro: 2.1.5 => 2.1.5 
      eslint-plugin-taro: 2.1.5 => 2.1.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6

**Comment by luckyadam** [comment]
这个特性还未支持

**Comment by Chen-jj** [comment]
`PageMeta` 需要是页面的第一个节点，不能放在 template 里，和现有 Taro3 的渲染机制有点冲突，暂时不支持了，之后再想想处理办法。

**Comment by LeeeoZhang** [comment]
> `PageMeta` 需要是页面的第一个节点，不能放在 template 里，和现有 Taro3 的渲染机制有点冲突，暂时不支持了，之后再想想处理办法。

v1v2可以支持一下吗

**Comment by qianlongdoit** [comment]
@Chen-jj Taro v3版本现在支持吗，我试了一下，发现好像没效果

**Comment by linhaobin** [comment]
@Chen-jj  这个有计划支持吗？现在有一个需求是希望能修改 root-font-size 来控制 rem

**Comment by jhxxs** [comment]
> 可以选择继承 `@tarojs/plugin-platform-weapp`，编写自定义的端平台插件，修改页面模板生成的部分。
> 
> 例如：
> 
> ```js
> // dist/index/index.wxml
> <import src="../../base.wxml"/>
> 
> <page-meta root-font-size="{{rootFontSize}}">
>   <template is="taro_tmpl" data="{{root:root}}" />
> </page-meta>
> ```
> 
> 如果还需要设置 data，可以使用 `const page = Taro.getCurrentinstance().page` 获取当前页面实例。然后再调用 setData：
> 
> ```js
> page.setData({...})
> ```

请问这个在react中要怎么实现？

**Comment by baranwang** [comment]
> > 可以选择继承 `@tarojs/plugin-platform-weapp`，编写自定义的端平台插件，修改页面模板生成的部分。
> > 例如：
> > ```js
> > // dist/index/index.wxml
> > <import src="../../base.wxml"/>
> > 
> > <page-meta root-font-size="{{rootFontSize}}">
> >   <template is="taro_tmpl" data="{{root:root}}" />
> > </page-meta>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果还需要设置 data，可以使用 `const page = Taro.getCurrentinstance().page` 获取当前页面实例。然后再调用 setData：
> > ```js
> > page.setData({...})
> > ```
> 
> 请问这个在react中要怎么实现？

还没看具体实现，不过这和框架没什么关系吧，react 中在`useEffect` 里 `setData` 不就行了

**Comment by baranwang** [comment]
> 

直接修改生成的文件的方法是不是有点太脏了，希望可以在 config 里增加一个配置，like: `config.mini.template.prefix = <page-meta root-font-size="{{rootFontSize}}">` `config.mini.template.suffix = </page-meta>`

**Comment by baranwang** [comment]
> 可以选择继承 `@tarojs/plugin-platform-weapp`，编写自定义的端平台插件，修改页面模板生成的部分。
> 
> 例如：
> 
> ```js
> // dist/index/index.wxml
> <import src="../../base.wxml"/>
> 
> <page-meta root-font-size="{{rootFontSize}}">
>   <template is="taro_tmpl" data="{{root:root}}" />
> </page-meta>
> ```
> 
> 如果还需要设置 data，可以使用 `const page = Taro.getCurrentinstance().page` 获取当前页面实例。然后再调用 setData：
> 
> ```js
> page.setData({...})
> ```

直接修改生成的文件的方法是不是有点太脏了，希望可以在 config 里增加一个配置，like: `config.mini.template.prefix = <page-meta root-font-size="{{rootFontSize}}">` `config.mini.template.suffix = </page-meta>`

**Comment by baranwang** [comment]
emmmm 好像并不需要修改到那么深

**Comment by baranwang** [comment]
> ```js
> ```js
> page.setData({...})
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

https://github.com/baranwang/tarojs-plugin-platform-miniprogram 继承 `@tarojs/plugin-platform-weapp` 做了处理，并封装了 React 组件

**Comment by Chen-jj** [comment]
> https://github.com/baranwang/tarojs-plugin-platform-miniprogram 继承 `@tarojs/plugin-platform-weapp` 做了处理，并封装了 React 组件
> 
> cc @Chen-jj

老哥稳！如果能配置筛选需要添加的 prefix、suffix 就更好了

**Comment by baranwang** [comment]
> > https://github.com/baranwang/tarojs-plugin-platform-miniprogram 继承 `@tarojs/plugin-platform-weapp` 做了处理，并封装了 React 组件
> > cc @Chen-jj
> 
> 老哥稳！如果能配置筛选需要添加的 prefix、suffix 就更好了

更新了一个版本，增加 include 和 exclude 配置

**Comment by Chen-jj** [comment]
已在文档标注暂时使用插件去支持：https://docs.taro.zone/docs/next/components/page-meta

希望 @baranwang 老哥有空可以把这个特性提交 PR 合到 Taro 主干的~

**Comment by slogeor** [comment]
> > > https://github.com/baranwang/tarojs-plugin-platform-miniprogram 继承 `@tarojs/plugin-platform-weapp` 做了处理，并封装了 React 组件
> > > cc @Chen-jj
> > 
> > 
> > 老哥稳！如果能配置筛选需要添加的 prefix、suffix 就更好了
> 
> 更新了一个版本，增加 include 和 exclude 配置

老哥， 我这还是不生效

**Comment by 18601673727** [comment]
到现在`<page-meta>`还是一个不能在taro中使用的功能 希望重视一下

**Comment by Chen-jj** [comment]
Taro v3.6.19开始支持

**Comment by sumail43db** [comment]
> Taro v3.6.19开始支持

3.6.19什么时候release呢？

**Comment by LingF** [comment]
支付宝小程序还是不行
