### ISSUE TITLE
h5端 子组件中使用 @connect 会覆盖子组件内部的函数，  通过ref调用子组件的函数时就会报错

### ISSUE THREAD

**Issue by immortal-oe** [NervJS/taro#6095]
### 复现步骤
![image](https://user-images.githubusercontent.com/25888914/80188581-f8017f80-8643-11ea-853c-9a6db3a1c17f.png)
![image](https://user-images.githubusercontent.com/25888914/80188819-4c0c6400-8644-11ea-8642-6750b46b6e15.png)

在Tab页面 子组件中

左边小程序端有 onClose 函数 ， 右边的h5端则没有

如果不使用 @connect  h5端则不会出现这个问题

**Comment by XPgan** [comment]
我的父组件也使用了 @connect

**Comment by XPgan** [comment]
版本号 2.0.6

**Comment by luckyadam** [comment]
能不能给一下具体点的例子

**Comment by XPgan** [comment]
> 能不能给一下具体点的例子

![image](https://user-images.githubusercontent.com/25888914/80456872-e6c8b380-8960-11ea-8f2e-18227e8176c5.png)
![image](https://user-images.githubusercontent.com/25888914/80456900-f2b47580-8960-11ea-99f8-0e2dc347c7e1.png)
![image](https://user-images.githubusercontent.com/25888914/80457280-9ef65c00-8961-11ea-85bd-408ed8201b82.png)
![image](https://user-images.githubusercontent.com/25888914/80457372-c1887500-8961-11ea-90c9-0b2e21992d5f.png)
版本 2.1.5 
子组件使用了 redux的装饰器@connect ， 导致父组件，无法通过ref 无法访问子组件的内部函数

**Comment by XPgan** [comment]
> 能不能给一下具体点的例子

在父组件内无法访问子组件的  onStart 方法， 可能是 @tarojs/redux  修改子组件的实例时，并没有继承原组件的属性

**Comment by mouse9527** [comment]
react尽量不要持有组件ref

**Comment by fuyiwei** [comment]
Has this problem been dealt with? I have encountered this problem now. This has become a decorator, not the component itself.

**Comment by majorcool** [comment]
connect本来有四个参数，第四个参数就是forwardRef的配置，tarojs/redux阉割了connect的后两个参数，所以无法使用ref

**Comment by XPgan** [comment]
> connect本来有四个参数，第四个参数就是forwardRef的配置，tarojs / redux阉割了connect的后两个参数，所以无法使用ref
嗯嗯了解到了，估计是不会修复了，目前可以props传下去，等待3.x稳定

**Comment by gxsandzxl** [comment]
这个问题有解决方案了吗？
