### ISSUE TITLE
useEffect( func, [children]),  children 变化时组件有渲染，但func没有执行

### ISSUE THREAD

**Issue by shengbowen** [NervJS/taro#6096]
### 问题描述
使用useEffect时，发现children变化时，useEffect中回调没有执行，即func没有重新执行

```js
function Demo ({children}) {
  useEffect(() => {
    console.log('testing')
  }, [children])

  return <div>{children}</div>
}


function App() {
  const [color, setColor] = useState("green");
  return (
    <div>
      <h1 style={{ color: color }}>React Hooks</h1>
      <Demo>{color}</Demo>
      <button
        onClick={() => {
          setColor("red");
        }}
      />
    </div>
  );
}

```

### 期望行为
当children内容变化时，console.log('testing') 能够重新执行。
目前hack方式是不使用children，通过一般props传递，想请问这个是因为本身children实现方式有关，不支持这种使用方式吗？是否有其他更好方案代替

### 系统信息

Taro CLI 2.1.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v11.11.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
    npmPackages:
      @tarojs/components: 2.1.0 => 2.1.0
      @tarojs/taro: 2.1.0 => 2.1.0
      eslint-config-taro: ^2.0.4 => 2.1.2
      nervjs: ^1.5.6 => 1.5.6
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10

**Comment by xuzpeng** [comment]
我测试了是正常的，你是不是理解错了，你button自闭和了，你点击哪里呢？？

**Comment by shengbowen** [comment]
> 我测试了是正常的，你是不是理解错了，你button自闭和了，你点击哪里呢？？

嗯，button没写全。 我这边是 微信不行，h5端看是正常的。所以想说是不是微信端children的实现方式导致的，因为官方文档也说了不能操作children，并且打印children控制台显示的是undefined

**Comment by xuzpeng** [comment]
是的，小程序确实是不可以这样操作的，实现机制不太一样

**Comment by yuche** [comment]
这个在 taro 1/2 是没办法做到的，传统编译有一个重要的原则就是 JSX 不是一种数据，他只是用来表示 wxml 的一种语法。

你可以升级到 taro next 解决这个问题。
