### ISSUE TITLE
父组件如何引用子组件的方法？

### ISSUE THREAD

**Issue by ldwonday** [NervJS/taro#610]
最新在用Taro，遇到了不少问题
1、webpack watch的时候经常漏掉model，这个可能和dva有关系，删掉dist，重新编译就是好的。
2、app.js中写的自定义方法，在别的地方调用不了，Taro.getApp()里面有没有自定义的方法。
3、自定义组件也是，父组件引用不了子组件内部的方法，除非这个方法在jsx中被用到了，没有用到的是找不到的。例如this.$scope.selectComponent('#packet')获取到自定义组件后发现里面并没有自定义的方法，但是子组件如果jsx中用到的方法能找到。

**Comment by yuche** [comment]
`selectComponent ` 拿到的是小程序的组件实例，Taro 的实例你可以通过 [`ref`](https://nervjs.github.io/taro/docs/ref.html#docsNav) 拿到。

**Comment by ldwonday** [comment]
@yuche 都试过了，都拿不到！

**Comment by luckyadam** [comment]
你的 Taro 版本多少

**Comment by shenghanqin** [comment]
@ldwonday 请试用最新版，看还有这个问题吗？
我平常都是用ref来获取子组件的方法的。
