### ISSUE TITLE
你好！我在index.html要引入一下js文件怎么报错

### ISSUE THREAD

**Issue by linhuisheng** [NervJS/taro#6103]
这个是我的代码：
![image](https://user-images.githubusercontent.com/8087304/80273480-ee8c1c00-8704-11ea-9cda-e2ef4f053eed.png)
这个是网页报错的地方：
![image](https://user-images.githubusercontent.com/8087304/80273501-111e3500-8705-11ea-90ea-e33819b0cac9.png)
tour.js:1 Uncaught SyntaxError: Unexpected token '<'
麻烦各位帮忙看下可以吗？或者我要怎么做才能全局引入  <script src="krpano/tour.js"></script>

因为我要引入第三方的组件，要实现全景看图，这里要引入<script src="krpano/tour.js"></script>
地址是：https://github.com/browniu/react-krpano
![image](https://user-images.githubusercontent.com/8087304/80273522-53477680-8705-11ea-9031-7e1658eef532.png)
麻烦大佬了！

**Comment by shenghanqin** [comment]
<script src="krpano/tour.js"></script>
这个可能得使用绝对路径吧？

**Comment by luckyadam** [comment]
麻烦给一个 demo 看下

**Comment by Littly** [comment]
h5 dev模式启动了 webpack-dev-server，但script里指定的这个文件并不在serve的文件中

**Comment by linhuisheng** [comment]
> h5 dev模式启动了 webpack-dev-server，但script里指定的这个文件并不在serve的文件中

那我这里要怎么指定？

**Comment by linhuisheng** [comment]
> 麻烦给一个 demo 看下

你好，这里就是单独写一个程序来引入这个react模块，https://github.com/browniu/react-krpano就是这里，需要全局引入这个<script src="krpano/tour.js"></script>

**Comment by linhuisheng** [comment]
> <script src="krpano/tour.js"></script>
> 这个可能得使用绝对路径吧？

你好，绝路径要怎么设置？我这里已经krpano和index.html同级了

**Comment by Littly** [comment]
可以用taro的copy配置把这个文件从src目录copy到对应的目录去

**Comment by coderDancer** [comment]
在script标签上面，增加 type="text/babel"既可以
