### ISSUE TITLE
showToast在华为P20PRO手机上的兼容性问题

### ISSUE THREAD

**Issue by wayneGZY** [NervJS/taro#6110]
### 问题描述
华为P20PRO手机上用showToast提示信息超过40个字会显示不全。
![image](https://user-images.githubusercontent.com/25128453/80298632-edb8c000-87c0-11ea-9fe0-5e4b90c0d079.png)

### 复现步骤

1. 用华为P20PRO真机打开Taro小程序
2. 点击提示弹窗
3. 看到现象
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
Taro.showToast({
title:'字数超过40个字即可！字数超过40个字即可！字数超过40个字即可！字数超过40个字即可！',
icon:'none',
duration:3000
})

```

### 期望行为

持续维护兼容性问题
### 报错信息

![image](https://user-images.githubusercontent.com/25128453/80298632-edb8c000-87c0-11ea-9fe0-5e4b90c0d079.png)
### 系统信息
真机系统信息：
![image](https://user-images.githubusercontent.com/25128453/80298768-43419c80-87c2-11ea-99d9-48e02ac69131.png)

开发系统信息:
![image](https://user-images.githubusercontent.com/25128453/80298739-fc53a700-87c1-11ea-9413-01a8b55d086b.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
http://taro-docs-in.jd.com/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F

**Comment by wayneGZY** [comment]
> http://taro-docs-in.jd.com/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F

这个地址打不开呢。。。

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/80299307-f19b1100-87c5-11ea-9046-54e9ead4f9b9.png)

**Comment by wayneGZY** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
        网络一切正常，地址打不开。。。
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                495582339
                            
                    
                        
                            
                                    495582339@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年4月26日 13:39，chenjiajian<notifications@github.com> 写道： 



http://taro-docs-in.jd.com/taro/docs/debug.html#api-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E4%B8%8D%E7%AC%A6%E5%90%88%E9%A2%84%E6%9C%9F

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
