### ISSUE TITLE
图片的heightFix模式css计算有问题v2.1.6

### ISSUE THREAD

**Issue by kala888** [NervJS/taro#6113]
taro 2.1.6
问题代码
https://github.com/kala888/nice-router-taro/blob/master/src/listof/templates/product-template.jsx
在2.1.6中编译结果
![image](https://user-images.githubusercontent.com/1215976/80301166-1054d400-87d5-11ea-848c-96d7d626ed82.png)
在2.1.0中运行没问题
![image](https://user-images.githubusercontent.com/1215976/80301174-1ea2f000-87d5-11ea-8369-851ae04de5f1.png)

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/80454451-a5cea000-895c-11ea-92fa-441b9b89a3c7.png)
你对比错元素了吧

**Comment by kala888** [comment]
重新上个图，2.1.6 下面，一样的效果
![image](https://user-images.githubusercontent.com/1215976/80554563-2c888900-8a00-11ea-8d44-310cddb720aa.png)

**Comment by kala888** [comment]
再次补充，发现跟分包有关，同样的页面，如果放到子包下面，一切ok，放到主包，图片就展示不出来了
![image](https://user-images.githubusercontent.com/1215976/80680954-4d310b80-8af2-11ea-8093-0077424ded82.png)

**Comment by kala888** [comment]
修改了自定义图片组件的实现，通过my-class来替换原来的className方式，在2.1.1以后可以使用，原因未知
