### ISSUE TITLE
[Feature request]virtual-list能不能支持flex:1?

### ISSUE THREAD

**Issue by yz1311** [NervJS/taro#6114]
### 问题描述

刚刚尝试了，必须要设置height，而且必须是number，但是小程序获取高度太麻烦了，能不能支持flex:1这种，将剩余的空间填满

### 系统信息

 Taro CLI 3.0.0-beta.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/webpack-runner: 3.0.0-beta.5 => 3.0.0-beta.5 
      eslint-config-taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      react: ^16.10.0 => 16.13.0 
    npmGlobalPackages:
      typescript: 3.7.4

**Comment by yuche** [comment]
这个没有办法，内置的 virtual-list 是一个固定高度（或水平滚动的宽度）的列表，因为自适应高度列表在小程序上大部分情况会有比较严重的性能问题。

你可以考虑使用 https://github.com/bvaughn/react-window 的 `VariableSizeList ` 来实现自适应高度。

**Comment by yz1311** [comment]
> 这个没有办法，内置的 virtual-list 是一个固定高度（或水平滚动的宽度）的列表，因为自适应高度列表在小程序上大部分情况会有比较严重的性能问题。
> 
> 你可以考虑使用 https://github.com/bvaughn/react-window 的 `VariableSizeList ` 来实现自适应高度。需要注意的是你需要效仿 Taro 内置的 virtual-list 修改基础渲染组件。

好的，谢谢，看来得转变下开发方式了
