### ISSUE TITLE
vendors.wxss 在构建后没有引用

### ISSUE THREAD

**Issue by WenMaoLin** [NervJS/taro#6117]
执行 npm run build:weapp 后，vendors.wxss 没有被引用

taro 版本号是 3.0.0-beta.5

**Comment by Chen-jj** [comment]
@WenMaoLin 信息太少了

**Comment by WenMaoLin** [comment]
具体情况是这这样，有一个自定义组件，这个组件被多个页面依赖后，我发现自定义组件的样式就失效了。
我检查了一下，打包后，样式文件保存在了 项目根目录的 vendors.wxss 文件内，而没有发现 vendors.wxss 被其他入口引用而导致被多个页面依赖的自定义组件样式失效。

从群里得知我的项目没有引用 app.scss，引入后得到解决。按照这个思路我去看了编译后的代码，common.wxss 被 app.wxss @import，而b5 版本我去查看了 app.wxss内，vendors.wxss 并没有 @import vendors.wxss，我手动加上之后目前暂时解决了样式失效的问题。

在文档里没有查到相关资料，是我缺少某些配置或是异常行为。辛苦💦💦

**Comment by Chen-jj** [comment]
@WenMaoLin 有没有 demo 给看下

**Comment by WenMaoLin** [comment]
我新起了一个项目，把场景搭建好之后构建完发现跟我出现问题的项目目录结构不一致了，新初始化的项目并没有出现问题，自定义组件的样式被两个依赖后样式被打包到了 common.wxss 里，common.wxss 由 app.wxss 引入。

而我的项目打包后自定义组件被抽到了 vendors.wxss，而没有被 app.wxss 引用，我想询问一下，为什么会出现我这个情况，👇这图是我打包后的目录结构

<img width="903" alt="Screen Shot 2020-04-27 at 3 19 06 PM" src="https://user-images.githubusercontent.com/24424510/80344632-77888c00-889a-11ea-8219-bcf299369deb.png">
-------------------------------------------
👇这个是新创建的项目，构建完的目录结构
<img width="707" alt="Screen Shot 2020-04-27 at 3 20 48 PM" src="https://user-images.githubusercontent.com/24424510/80344879-d8b05f80-889a-11ea-96d1-425fef619f5d.png">

**Comment by WenMaoLin** [comment]
demo：[https://github.com/WenMaoLin/taroDemo](url)
复现步骤，有一个自定义组件，在 components/red，是一个全屏红色的一个背景
有两个页面 one、two，目前只有 one 引入了 red。
如果自定义组件被引用多次，样式就会失效，去 two 页面把注释的代码删掉，就会出现样式失效

**Comment by Chen-jj** [comment]
@WenMaoLin 试了一下，有帮你在 app.wxss 中引入 vendors.wxss 喔

![image](https://user-images.githubusercontent.com/11807297/80382308-b9362880-88d4-11ea-8112-594fe335ea9b.png)

**Comment by Chen-jj** [comment]
@WenMaoLin 你把 .lock 文件删了，重新安装一遍依赖，应该就好了

**Comment by WenMaoLin** [comment]
尝试了把 .lock 移除，重新安装了依赖，没有解决，反而出现了一个奇怪的错误
<img width="716" alt="Screen Shot 2020-04-28 at 5 15 31 AM" src="https://user-images.githubusercontent.com/24424510/80421726-83fafc00-890f-11ea-9327-6920444f226a.png">
我也尝试了将 taro 重新安装，清空，npm 缓存，都无效.

**Comment by Chen-jj** [comment]
@WenMaoLin 还是依赖的问题。 `"@tarojs/mini-runner": "3^.0.0-beta.5"` => `"@tarojs/mini-runner": "3.0.0-beta.5"` 再重装试试，还不行就新建项目吧。

**Comment by WenMaoLin** [comment]
🙏
"@tarojs/mini-runner": "^3.0.0-beta.5" 改为 "@tarojs/mini-runner": "3.0.0-beta.5" 解决了
