### ISSUE TITLE
函数式组件使用组合（renderXXX）属性编译不正确

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#6121]
### 问题描述

函数式组件组合（renderXXX）属性编译结果不正确，依旧把 `render` 开头的属性编译成了普通的模板，而不是 `slot`， 在函数式组件中改成类组件的写法 `this.prop.renderXXX`，则能正常编译。

https://nervjs.github.io/taro/docs/children.html#%E7%BB%84%E5%90%88

### 复现步骤

1. 在一个函数式组件中定义一个或多个以 `render` 开头的属性
2. 将此属性作为一个节点的值
3. 在别处使用此组件，往 `render` 开头的属性传入一个元素
4. 可以看到并没有渲染此元素

```js
export default function Header({ renderTitle }) {
  return (
    <View>
      <Text>{renderTitle}</Text>
      <Text>查看更多</Text>
    </View>
  )
}
```

### 期望行为

正常渲染

### 报错信息

无报错，但编译结果不正确

### 系统信息

👽 Taro v2.1.6

  Taro CLI 2.1.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.6 => 2.1.6 
      @tarojs/components-qa: 2.1.6 => 2.1.6 
      @tarojs/mini-runner: 2.1.6 => 2.1.6 
      @tarojs/router: 2.1.6 => 2.1.6 
      @tarojs/taro: 2.1.6 => 2.1.6 
      @tarojs/taro-alipay: 2.1.6 => 2.1.6 
      @tarojs/taro-h5: 2.1.6 => 2.1.6 
      @tarojs/taro-qq: 2.1.6 => 2.1.6 
      @tarojs/taro-quickapp: 2.1.6 => 2.1.6 
      @tarojs/taro-rn: 2.1.6 => 2.1.6 
      @tarojs/taro-swan: 2.1.6 => 2.1.6 
      @tarojs/taro-tt: 2.1.6 => 2.1.6 
      @tarojs/taro-weapp: 2.1.6 => 2.1.6 
      @tarojs/webpack-runner: 2.1.6 => 2.1.6 
      eslint-config-taro: 2.1.6 => 2.1.6 
      eslint-plugin-taro: 2.1.6 => 2.1.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.1.6 => 2.1.6 
      stylelint-taro-rn: 2.1.6 => 2.1.6 
      taro-ui: ^2.3.2 => 2.3.2 

### 补充信息

编译结果不正确，依旧把 `render` 开头的属性编译成了普通的模板，而不是 `slot`， 在函数式组件中改成类组件的写法 `this.prop.renderXXX`，则能正常编译。

以下代码能正常编译：
```js
export default function Header({ renderTitle }) {
  return (
    <View>
      <Text>{this.props.renderTitle}</Text>
      <Text>查看更多</Text>
    </View>
  )
}
```

**Comment by Chen-jj** [comment]
下个版本修复 [54840c6](https://github.com/NervJS/taro/commit/54840c66f0c4966bbb84a191d76e85923b070831)
