### ISSUE TITLE
taro3+vue H5和微信小程序  字体大小问题

### ISSUE THREAD

**Issue by mengfanfei** [NervJS/taro#6122]
### 问题描述
设置字体大小，比如：32px， 会出现h5中不同型号的手机一行显示的字数是一样的，在小程序中，不同手机型号一行显示的是不一样的，而且在小程序端  字体设置好像不起作用，不管设置多少px,都是一样的字体大小

### 复现步骤

1. 设置字体大小
![image](https://user-images.githubusercontent.com/27276920/80327097-83118e00-886d-11ea-8c1f-10bd0aa8af28.png)

2. 在h5端切换不同的型号，字体大小会随之增大缩小， 在小程序端是大小是不变的
3. 小程序端表现
![image](https://user-images.githubusercontent.com/27276920/80327255-121ea600-886e-11ea-936a-e6d3849b3b6e.png)
![image](https://user-images.githubusercontent.com/27276920/80327284-25ca0c80-886e-11ea-84af-21199a20a685.png)

4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
小程序端字体能够设置大小

### 系统信息
![image](https://user-images.githubusercontent.com/27276920/80327325-4befac80-886e-11ea-930c-def797eebf2e.png)

### 补充信息

问题原因应该是  小程序端的字体设置失效，，不论设置什么字体都不变

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by eiddie** [comment]
> 而且在小程序端 字体设置好像不起作用

`taro next` vue 小程序样式不生效是因为`<style lang="scss" scoped>` 加了`scoped`,  只有把`scoped`去掉，样式才能在小程序端生效

**Comment by mengfanfei** [comment]
> 才能在小程序端生效

那这样的话，在h5端样式不就容易被覆盖了吗

**Comment by eiddie** [comment]
> 那这样的话，在h5端样式不就容易被覆盖了吗

可以启用`css modules`防止样式冲突
