### ISSUE TITLE
his.$$refs.pushRefs is not a function.

### ISSUE THREAD

**Issue by lilingling3** [NervJS/taro#6127]
### 问题描述
ref 获取元素 偶尔报错，导致获取不到元素
### 复现步骤

```js


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by TokeyJerry** [comment]
> 欢迎提交 Issue~
> 
> 如果你提交的是 bug 报告，请务必遵循 [Issue 模板](https://github.com/NervJS/taro/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)的规范，尽量用简洁的语言描述你的问题，最好能提供一个稳定简单的复现。🙏🙏🙏
> 
> 如果你的信息提供过于模糊或不足，或者已经其他 issue 已经存在相关内容，你的 issue 有可能会被关闭。
> 
> Good luck and happy coding~

怎么给的回复总是这一条啊？1.x 的版本就有这个问题，一直到现在还有，可以回复下如何兼容，或者啥时候修复么？

**Comment by Chen-jj** [comment]
@TokeyJerry 给个 demo 看看吧

**Comment by TokeyJerry** [comment]
> @TokeyJerry 给个 demo 看看吧

和之前提的关于 ref 的问题都是一样的。示例如下：

```
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

class Index extends Component {
  componentDidMount () {
    console.log(this.mainArea, this.mainArea.initPageData)
  }

  refMainArea = (ref) => {
    this.mainArea = ref
  }

  render () {
    return (
      <View>
        <MainArea ref={this.refMainArea} />
      </View>
    )
  }
}

export default Index
```

微信小程序（真机）偶尔会有报错，错误信息如下:

this.$$refs.pushRefs is not a function. (In 'this.$$refs.pushRefs([{"type":"component","id":"eaizz","refName":"","fn":this.refMainArea}])', 'this.$$refs.pushRefs' is undefined);at api nextTick callback function

**Comment by KiddZZ** [comment]
iphone 6p  ios9.x  taro版本2.1.4  稳定复现

**Comment by 17biubiu** [comment]
这个问题还有解吗

**Comment by lilingling3** [comment]
没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "17biu"<notifications@github.com&gt;; 
发送时间: 2020年8月24日(星期一) 下午2:49
收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 
抄送: "黎玲玲"<1192246772@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NervJS/taro] his.$$refs.pushRefs is not a function. (#6127)





 
这个问题还有解吗

**Comment by 17biubiu** [comment]
看样是 nobody care 了

**Comment by igauch** [comment]
请帮忙跟进下，遇到同样的问题
