### ISSUE TITLE
h5启动后报sass错误

### ISSUE THREAD

**Issue by lian0121** [NervJS/taro#6134]
### 问题描述
h5编译的时候报错，找不到sass-loader

### 复现步骤
taro build --type h5 --watch

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

正常启动

### 报错信息

（./.temp/component/badge/style.sass)
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/sass-loader/lib/loader.js):

@import '~taro-ui/dist/style/variables/default.scss';
@import '~taro-ui/dist/style/mixins/index.scss';
$at-badge-border-radius: $at-badge-font-size * 0.7;

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
报错并不是找不到 sass-loader，请提供一下更完整的报错信息

**Comment by lian0121** [comment]
> 报错并非找不到sass-loader，请提供一下更完整的报错信息

<img width="605" alt="微信截图_20200427160047" src="https://user-images.githubusercontent.com/31687853/80440655-d3efb800-893b-11ea-8ff3-c0e6cabebdba.png">
这是报错截图

**Comment by lian0121** [comment]
./.temp/component/badge/style.sass)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

$at-badge-border-radius: $at-badge-font-size * 0.7;
                                                 ^
      Semicolons aren't allowed in the indented syntax.
  ╷
2 │ $at-badge-border-radius: $at-badge-font-size * 0.7;
  │                                                   ^
  ╵
  stdin 2:51  root stylesheet
      in E:\workspace\Jxc-sy-web\h5\github\scanbar-taro\.temp\component\badge\style.sass (line 2, column 51)

**Comment by luckyadam** [comment]
> ./.temp/component/badge/style.sass)
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> 
> $at-badge-border-radius: $at-badge-font-size * 0.7;
> ^
> Semicolons aren't allowed in the indented syntax.
> ╷
> 2 │ $at-badge-border-radius: $at-badge-font-size * 0.7;
> │ ^
> ╵
> stdin 2:51 root stylesheet
> in E:\workspace\Jxc-sy-web\h5\github\scanbar-taro.temp\component\badge\style.sass (line 2, column 51)
> 
> 报这个错，我不知道图片有没有上传成功

有语法提示错误啊，Semicolons aren't allowed in the indented syntax.
不要加分号

**Comment by lian0121** [comment]
> > ./.temp/component/badge/style.sass)
> > Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> > $at-badge-border-radius: $at-badge-font-size * 0.7;
> > ^
> > Semicolons aren't allowed in the indented syntax.
> > ╷
> > 2 │ $at-badge-border-radius: $at-badge-font-size * 0.7;
> > │ ^
> > ╵
> > stdin 2:51 root stylesheet
> > in E:\workspace\Jxc-sy-web\h5\github\scanbar-taro.temp\component\badge\style.sass (line 2, column 51)
> > 报这个错，我不知道图片有没有上传成功
> 
> 有语法提示错误啊，Semicolons aren't allowed in the indented syntax.
> 不要加分号

解决了，把后缀名改成scss就可以啦
