### ISSUE TITLE
Taro内使用wxs支持并不好，且标签上加入change:prop无法编译成功

### ISSUE THREAD

**Issue by IWSR** [NervJS/taro#6137]
### 问题描述

Taro内使用wxs支持并不好，且标签上加入change:prop无法编译成功
因为有复杂动画所以在小程序内只能跳过wxs来实现，目前没有多端的需求所以使用taro只是馋它的语法，希望对小程序单独打包对某些属性不作处理直接跳过

### 复现步骤

1. tsx内的实现
![image](https://user-images.githubusercontent.com/18499412/80349792-57f56180-88a2-11ea-905a-878c4b42174c.png)
2.编译结果
![image](https://user-images.githubusercontent.com/18499412/80350480-5f693a80-88a3-11ea-85b0-64cd2adcb658.png)

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

change:prop能被正常编译为change:prop

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by IWSR** [comment]
属性内存在：似乎并不能编译通过，但是改成change-prop会出现在dist上

**Comment by Chen-jj** [comment]
#5760
