### ISSUE TITLE
[Bug] eslint错误提示貌似有问题，experimentalDecorators不生效

### ISSUE THREAD

**Issue by galaxycubic** [NervJS/taro#614]
**问题描述**

**复现步骤**
1.taro init，yarn install...
2.编辑器中打开到项目，然后打开src/pages/index/index
3.定位到第25行，eslint parser提示有语法问题
```js
@connect(
	({ counter }) => ({
		counter,
	}),
	(dispatch) => ({
		add() {
			dispatch(add())
		},
		dec() {
			dispatch(minus())
		},
		asyncAdd() {
			dispatch(asyncAdd())
		},
	}),
)
//下面这行是第25行
class Index extends Component {
	config = {
		navigationBarTitleText: '首页',
	}

	componentWillReceiveProps(nextProps) {
		console.log(this.props, nextProps)
	}

	componentWillUnmount() {}

	componentDidShow() {}

	componentDidHide() {}

	render() {
		return (
			<View className="index">
				<Button className="add_btn" onClick={this.props.add}>
					+
				</Button>
				<Button className="dec_btn" onClick={this.props.dec}>
					-
				</Button>
				<Button className="dec_btn" onClick={this.props.asyncAdd}>
					async
				</Button>
				<View>
					<Text>{this.props.counter.num}</Text>
				</View>
				<View>
					<Text>Hello, World</Text>
				</View>
			</View>
		)
	}
}
```

4.打开.eslintrc添加相关experimentalDecorators配置
```json
{
	"extends": ["taro"],
	"rules": {
		"no-unused-vars": ["error", { "varsIgnorePattern": "Taro" }],
		"react/jsx-filename-extension": [
			1,
			{ "extensions": [".js", ".jsx", ".tsx"] }
		]
	},
	"parser": "babel-eslint",
	"parserOptions": {
		"ecmaVersion": 2018,
		"ecmaFeatures": {
			"experimentalObjectRestSpread": true,
			"experimentalDecorators": true,
			"jsx": true
		},
		"sourceType": "module"
	}
}
```
重新开启项目，问题依然存在

**期望行为**
希望能够正常使用eslint的代码风格提示和基本的错误检查，这样的问题很影响开发，因为我们会添加husky的钩子字段去检查基本问题，会导致报错提交不了。

**报错信息**
```
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
```

**系统信息**

 - 操作系统: Mac OSX High Sierra 10.13.6
 - Taro 版本: ^1.0.0-beta.26
 - Node.js 版本: V8.11.4

**补充信息**
编辑器是neovim终端中的版本，语法检查工具为ale，已开启了eslint checker。
![image](https://user-images.githubusercontent.com/17328586/45429123-3ba8af00-b6d5-11e8-94c4-e6b6399620d4.png)
尝试把checkers列表改为只使用eslint检查，发现仍然无效。
![image](https://user-images.githubusercontent.com/17328586/45429417-dacda680-b6d5-11e8-96b6-23cc5a76c7fe.png)
![image](https://user-images.githubusercontent.com/17328586/45429455-ef11a380-b6d5-11e8-9dc5-e35ce9032cb4.png)

感觉跟taro的eslint插件有关

**Comment by galaxycubic** [comment]
```
Unexpected usage of doublequote.

**Comment by galaxycubic** [comment]
![image](https://user-images.githubusercontent.com/17328586/45431965-4108f800-b6db-11e8-844c-c2400c344ca0.png)
VSCode中表现相同，感觉应该就是跟eslint-config-taro或eslint-plugin-taro有关系
Any ideas?

**Comment by luckyadam** [comment]
`experimentalDecorators` 这个是 vs code 的配置

**Comment by yuche** [comment]
这个配置与你的 VSCODE 有关，你在你的 VSCODE 单独打开了他的检查工具所以造成了这个问题。
![image](https://user-images.githubusercontent.com/7202516/45462090-df777680-b738-11e8-86bc-8d7f132bcd94.png)

你单独调用 eslint 命令没有问题那应该就和 taro 无关，跟用什么编辑器没有关系

**Comment by galaxycubic** [comment]
eslint命令会提示这个异常
![image](https://user-images.githubusercontent.com/17328586/45464712-6a11a300-b744-11e8-96a9-2e54a003b91a.png)

**Comment by galaxycubic** [comment]
问题已解决，谢谢。
