### ISSUE TITLE
升级taro版本为2.1.6出现问题

### ISSUE THREAD

**Issue by nanase-takesi** [NervJS/taro#6143]
![image](https://user-images.githubusercontent.com/38271786/80369715-4e2f2680-88c1-11ea-8489-a64a2dcc7c29.png)
![image](https://user-images.githubusercontent.com/38271786/80369726-50918080-88c1-11ea-83e7-456115318a2d.png)

**Comment by luckyadam** [comment]
重新安装一下依赖
