### ISSUE TITLE
Taro beta.5 Weapp: Cannot redirect to tabbar page

### ISSUE THREAD

**Issue by ionush** [NervJS/taro#6145]
### 问题描述

What is the correct way to navigate between no tabbar and tabbar pages?

### 复现步骤

app.config.js

```
export default {
  pages: [
    "components/login/organisms/loginPage",
    "components/user/organisms/userPage",
    "components/user/organisms/editProfilePage",
    "components/home/organisms/homePage",
    "components/camera/organisms/cameraPage",
  ],
  tabBar: {
    color: "#bbc0ca",
    selectedColor: "1f83e1",
    backgroundColor: "#ffc0cb",
    borderStyle: "white",
    list: [
      {
        pagePath: "components/home/organisms/homePage",
        text: "Home",
        iconPath: ""
      },
      {
        pagePath: "components/camera/organisms/cameraPage",
        text: "Camera"
      },
      {
        pagePath: "components/user/organisms/userPage",
        text: "User"
      }
    ]
  },
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black"
  }
};
```
loginPage.jsx
```
{...}
<AtButton onClick={() => Taro.redirectTo({ url: HOME_PAGE })}>
{...}


```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

Can go from no tabbar (i.e. login) to tabbar pages (i.e. homepage)

### 报错信息

VM5213:1 Uncaught (in promise) thirdScriptError
{"errMsg":"redirectTo:fail can not redirectTo a tabbar page"}
Object

### 系统信息

👽 Taro v3.0.0-beta.5

  Taro CLI 3.0.0-beta.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      @tarojs/webpack-runner: 3.0.0-beta.3 => 3.0.0-beta.3 
      eslint-config-taro: 3.0.0-beta.3 => 3.0.0-beta.3 
      react: ^16.10.0 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.8.3

**Comment by luckyadam** [comment]
如果要跳转到 tabbar 页面请用 Taro.switchTab
