### ISSUE TITLE
关于微信小程序编译警告

### ISSUE THREAD

**Issue by xuya227939** [NervJS/taro#6149]
# 问题描述
![image](https://user-images.githubusercontent.com/16217324/80454366-83d51d80-895c-11ea-9cc5-a80839791c06.png)
微信小程序编译出现该警告，请问如何修复？

**Comment by luckyadam** [comment]
cli 和项目依赖的版本没有对上吧

**Comment by xuya227939** [comment]
看了下，是对应的。
[image: image.png]



[image: image.png]

Li,Weitao <notifications@github.com> 于2020年4月28日周二 下午6:18写道：

**Comment by xuya227939** [comment]
升级到2.1.5，已解决。
