### ISSUE TITLE
process.env.NODE_ENV  显示不正常

### ISSUE THREAD

**Issue by myNameCao** [NervJS/taro#6154]
### 复现步骤

 当我 npm run build:alipay

在小程序开发 工具上 查看 process.env.NODE_ENV  是  development  

```js


```

### 期望行为

npm  run dev:alipay  时

process.env.NODE_ENV =development

npm run build:alipay 时

process.env.NODE_ENV =production

**Comment by Chen-jj** [comment]
@myNameCao 版本

**Comment by myNameCao** [comment]
> @myNameCao 版本
👽 Taro v2.0.6


  Taro CLI 2.0.6 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm

**Comment by luckyadam** [comment]
没有复现问题，可以升级到最新版本试试

**Comment by myNameCao** [comment]
> 没有复现问题，可以升级到最新版本试试

thx
