### ISSUE TITLE
列表加上key顺序改变时，元素发生异常行为

### ISSUE THREAD

**Issue by WenMaoLin** [NervJS/taro#6156]
**👇1、初次渲染效果**

<img width="453" alt="Screen Shot 2020-04-28 at 7 13 37 PM" src="https://user-images.githubusercontent.com/24424510/80481286-bb57c000-8984-11ea-814a-519998d3721e.png">
**👇2、点击按钮打乱之后**
<img width="392" alt="Screen Shot 2020-04-28 at 7 19 15 PM" src="https://user-images.githubusercontent.com/24424510/80481564-48027e00-8985-11ea-816d-45b7294a5fb7.png">

👇代码，taro 版本 3.0.0 **beta5**
<img width="675" alt="Screen Shot 2020-04-28 at 7 18 40 PM" src="https://user-images.githubusercontent.com/24424510/80481496-1ee1ed80-8985-11ea-95e1-85458d1e60c3.png">

不加 key **就正常效果如下**
<img width="409" alt="Screen Shot 2020-04-28 at 7 24 25 PM" src="https://user-images.githubusercontent.com/24424510/80481952-f9091880-8985-11ea-989c-b875d6fe566b.png">

**Comment by Chen-jj** [comment]
@WenMaoLin 提供一下完整的 demo

**Comment by WenMaoLin** [comment]
> @WenMaoLin 提供一下完整的 demo

https://github.com/WenMaoLin/taroDemo
