### ISSUE TITLE
alipay Taro.Component.prototype.xxx is undefined

### ISSUE THREAD

**Issue by yangger6** [NervJS/taro#6157]
#6087 

# 问题描述

为了在支付宝小程序兼容某些微信小程序的api写的polyfill添加到Taro.Component的原型链中，在PC和微信中都可以，**唯独**在支付宝小程序的**真机模拟**中无效.

### 各端运行情况

各端运行情况,控制台输出的分别是: polyfill的方法，env，还有当前Componet的this

1. 微信小程序-PC

- os: macOS-Catalina-10.15.3
- 基础库: v2.10.4
- node:  v10.15.1
- yarn: v1.12.1

![微信小程序-PC-macOS](https://user-images.githubusercontent.com/23329645/80476418-f0601480-897c-11ea-87ea-71d5fc3737bc.png)

2. 支付宝小程序-PC-macOS

- os: macOS-Catalina-10.15.3
- 基础库: v1.19.0
- node:  v10.15.1
- yarn: v1.12.1

![支付宝小程序-PC-macOS](https://user-images.githubusercontent.com/23329645/80476389-e9390680-897c-11ea-902b-023526cae72f.png)

3.微信小程序-IPhone XS 

- os: IOS-13.4.1
- 微信版本: v7.0.12
- 基础库版本: v2.11.0

![微信小程序-IPhone XS ](https://user-images.githubusercontent.com/23329645/80482643-2609fb00-8987-11ea-9524-0ce3fbc9ac58.png)

4. 支付宝小程序-iPhone XS

- os: IOS-13.4.1
- 支付宝版本: v10.1.92
- 基础库版本: v1.24.2

![支付宝小程序-iPhone XS](https://user-images.githubusercontent.com/23329645/80483089-f8718180-8987-11ea-8a66-7844730de9e4.png)

### 复现步骤

1. 在app.tsx添加

```typescript
// 首字母大写
export const upperCaseWord = word => word.replace(/(^|\s)\S/g, l => l.toUpperCase())

export type ITriggerEventFunction = (
	name: string,
	details?: any,
	options?: Partial<{
		bubbles: boolean,
		composed: boolean,
		capturePhase: boolean
	}>
) => void
/**
 *
 * @param name
 * @param details
 * @param options
 * @desc bubbles	Boolean	否	false	事件是否冒泡
 * @desc composed	Boolean	否	false	事件是否可以穿越组件边界，为false时，事件将只能在引用组件的节点树上触发，不进入其他任何组件内部
 * @desc capturePhase	Boolean	否	false	事件是否拥有捕获阶段
 * TODO options 还没实现 = =。
 */
const triggerEvent: ITriggerEventFunction = function (name, details?, options?) {
	if (Taro.getEnv() === 'WEAPP') {
		// 微信有自带的 调用微信的
		this.triggerEvent(name, details, options)
		return
	}
	// 兼容方案
	const propsName = `on${utils.upperCaseWord(name)}`
	const runFn = this.props[propsName]
	if (runFn) {
		runFn({
			detail: details
		})
	} else {
		console.error(`父级组件中没有${propsName}方法执行`)
	}
}

const list = [triggerEvent] // 需要追加的原型链方法

// 原型链追加方法
const install = (TaroInstance) => {
	TaroInstance.Component.prototype.env = Taro.getEnv()
	list.forEach((fn) => {
		TaroInstance.Component.prototype[`$${fn.name}`] = fn
	})
}
install(Taro)
```

2. 在任意一个Taro.Component的页面使用this.$triggerEvent方法

### 期望行为

希望在支付宝小程序真机模拟也可以生效

### 报错信息

![报错信息](https://user-images.githubusercontent.com/23329645/80483089-f8718180-8987-11ea-8a66-7844730de9e4.png)

### 系统信息

```
👽 Taro v2.1.5


  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    npmPackages:
      @tarojs/components: 2.1.5 => 2.1.5 
      @tarojs/components-qa: 2.1.5 => 2.1.5 
      @tarojs/mini-runner: 2.1.5 => 2.1.5 
      @tarojs/router: 2.1.5 => 2.1.5 
      @tarojs/taro: 2.1.5 => 2.1.5 
      @tarojs/taro-alipay: 2.1.5 => 2.1.5 
      @tarojs/taro-h5: 2.1.5 => 2.1.5 
      @tarojs/taro-qq: 2.1.5 => 2.1.5 
      @tarojs/taro-quickapp: 2.1.5 => 2.1.5 
      @tarojs/taro-rn: 2.1.5 => 2.1.5 
      @tarojs/taro-swan: 2.1.5 => 2.1.5 
      @tarojs/taro-tt: 2.1.5 => 2.1.5 
      @tarojs/taro-weapp: 2.1.5 => 2.1.5 
      @tarojs/webpack-runner: 2.1.5 => 2.1.5 
      eslint-config-taro: 2.1.5 => 2.1.5 
      eslint-plugin-taro: 2.1.5 => 2.1.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.1.5 => 2.1.5 
      stylelint-taro-rn: 2.1.5 => 2.1.5 


```

**Comment by Chen-jj** [comment]
@yangger6 是不是支付宝分包页才报错，也可以先自行断点一下看一开始有没有加上、后来为什么丢失。

**Comment by yangger6** [comment]
> @yangger6 是不是支付宝分包页才报错，也可以先自行断点一下看一开始有没有加上、后来为什么丢失。

不只是**支付宝分包页**出错，所有页面都出错

在Windows的taro版本是v2.1.6，没有出现这个问题，然后升级了macos下的taro版本和project版本到2.1.6依旧出现，追溯代码到根源发现，支付宝版本在真机模拟中[function.name](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/name)是空值，也就是没有办法正确使用以下代码：

```js
  const fnA = () => {}
  const fnB = () => {}
  const fnList = [fnA, fnB]
  fnList.forEach((fn) => {
    TaroInstance.Component.prototype[`$${fn.name}`] = fn
  })
```

感觉是不同os的支付宝小程序开发者工具的编译压缩导致`function.name`无法使用？

> 警告：当使用Function.name和那些JavaScript压缩器（minifiers）或混淆器进行源码转换时要小心。这些工具通常用作JavaScript构建管道的一部分，以在程序部署到生产之前减少程序的大小。但这种转换通常会在构建时更改函数的名称。

@Chen-jj

**Comment by yangger6** [comment]
把`fnList`改成`key-value`的形式就可以就成功运行了，应该不是taro的问题 == ，我关闭issue了😭😭😭
