### ISSUE TITLE
我在dev:h5 时组件直接被忽略了，这是为什么？有没有大佬遇见过这个问题？程序页面正常显示

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#616]
我在dev:h5 时组件直接被忽略了，这是为什么？有没有大佬遇见过这个问题？小程序页面正常显示

**Comment by zhou1992zg** [comment]
是少了什么配置吗？

**Comment by luckyadam** [comment]
把你的组件写法以及引用方式贴出来

**Comment by zhou1992zg** [comment]
下面是组件页面的写法
import {ScrollView,View} from '@tarojs/components';
import {Component} from '@tarojs/taro';
import './banner-hSwiper.scss';

export default class BannerLateralSwiper extends Component {

  constructor() {
    super(...arguments)
  }

  render() {
    return (
      <ScrollView
        className='scrollview'
        scrollX
        scrollWithAnimation
        scrollTop='0'
        style='height: 275px;'
        lowerThreshold='20'
        upperThreshold='20'
        onScrolltoupper={this.onScrolltoupper}
        onScroll={this.onScroll}>
        <View className='product-img' style='display:inline-block;'>
          <View className='itemSelf'>
            <View className='itemSelf-bg'>img</View>
            <View className='itemSelf-name'>AUX/奥克斯客厅立式柜机</View>
            <View className='itemSelf-text'>AUX/奥克斯 KFR-72LW/BpPYA19+2客厅立式柜机3匹家用冷暖柜机空调</View>
          </View>
        </View>
      </ScrollView>
    )
  }
}

下面是引用页面的写法

import {Component} from '@tarojs/taro';
import {View,Button} from '@tarojs/components';
import './index.scss';
import {BannerLateralSwiper} from '../../component/banner/banner-hSwiper/banner-hSwiper';

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  };

  constructor() {
    super(...arguments);
    this.state = {
    }
  }

  componentWillMount() {
  }


  render() {
    return (
      <View>
        <Button>点我去商品列表</Button>
        <BannerLateralSwiper />
      </View>
    )
  }
}
在dev:h5是<BannerLateralSwiper />被忽略

**Comment by zhou1992zg** [comment]
### 这是首页引用组件的页面代码
```
import {Component} from '@tarojs/taro';
import {View,Button} from '@tarojs/components';
import './index.scss';
import {BannerLateralSwiper} from '../../component/banner/banner-hSwiper/banner-hSwiper';
export default class Index extends Component {
  config = {
    navigationBarTitleText: '首页'
  };
  constructor() {
    super(...arguments);
    this.state = {
    }
  }
  componentWillMount() {
  }
  componentDidMount() {
  }
  render() {
    return (
      <View>
        <Button>点我去商品列表</Button>
        <BannerLateralSwiper />
      </View>
    )
  }
}
```
### 下面是组件的代码
```
import {ScrollView,View} from '@tarojs/components';
import {Component} from '@tarojs/taro';
import './banner-hSwiper.scss';
export default class BannerLateralSwiper extends Component {
  constructor() {
    super(...arguments)
  }
  render() {
    return (
      <ScrollView
        className='scrollview'
        scrollX
        scrollWithAnimation
        scrollTop='0'
        style='height: 275px;'
        lowerThreshold='20'
        upperThreshold='20'
        onScrolltoupper={this.onScrolltoupper}
        onScroll={this.onScroll}>
        <View className='product-img' style='display:inline-block;'>
          <View className='itemSelf'>
            <View className='itemSelf-bg'>img</View>
            <View className='itemSelf-name'>AUX/奥克斯客厅立式柜机</View>
            <View className='itemSelf-text'>AUX/奥克斯 KFR-72LW/BpPYA19+2客厅立式柜机3匹家用冷暖柜机空调</View>
          </View>
        </View>
      </ScrollView>
    )
  }
}
```
### 小程序dev正常，就是在dev:H5时会被忽略

**Comment by luckyadam** [comment]
你的组件是使用 `export default` 暴露的

那么你引用的地方就应该直接写 `import BannerLateralSwiper  from '....'`

**Comment by zhou1992zg** [comment]
非常感谢，问题解决了！
