### ISSUE TITLE
Taro的Picker组件设置disabled属性不会动态改变

### ISSUE THREAD

**Issue by wforguo** [NervJS/taro#6162]
#6087 

# 问题描述

- 环境：在微信小程序端
- 问题：使用了Taro的Picker组件，动态的设置disabled属性，并不会发生变化
- 对比：使用小程序原生的picker组件设置disabled是可以生效的

### 复现步骤

1. 默认area没有数据，disabled为true
2. 动态的改变area数据不为空
3. 此时disabled应该为false
4. 但是Picker还是不能点击

```js
import {View, Picker} from '@tarojs/components'

class StoreManage extends Component {
   constructor(props) {
        super(props);
        this.state = {
            area: [
                {
                   areaName: '杭州'
               },{
                areaName: '上海'
                }
            ]
        }
}
render() {
      const {area} = this.state;
      return (
           <Picker mode='selector'
                          disabled={area.length === 0}
                          range={area} range-key='areaName'
                        >        
        </Picker>
    )
 }
}
export default StoreManage

```
**但如果我使用这种方式，又是可以的**

// 先去获取disabled的值

```js
render() {
      const {area} = this.state;
      const disabled = area.length === 0// 先去获取disabled的值
      return (
           <Picker mode='selector'
                          disabled={disabled}
                          range={area} range-key='areaName'
                        >        
        </Picker>
    )
 }
}

```

### 期望行为

希望动态的添加disabled属性可以生效；

### 报错信息

没有报错，但就是没效果

### 系统信息

👽 Taro v2.1.3

  Taro CLI 2.1.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.3 => 2.1.3 
      @tarojs/components-qa: 2.1.3 => 2.1.3 
      @tarojs/mini-runner: 2.1.3 => 2.1.3 
      @tarojs/redux: 2.1.3 => 2.1.3 
      @tarojs/redux-h5: 2.1.3 => 2.1.3 
      @tarojs/router: 2.1.3 => 2.1.3 
      @tarojs/taro: 2.1.3 => 2.1.3 
      @tarojs/taro-alipay: 2.1.3 => 2.1.3 
      @tarojs/taro-h5: 2.1.3 => 2.1.3 
      @tarojs/taro-qq: 2.1.3 => 2.1.3 
      @tarojs/taro-quickapp: 2.1.3 => 2.1.3 
      @tarojs/taro-swan: 2.1.3 => 2.1.3 
      @tarojs/taro-tt: 2.1.3 => 2.1.3 
      @tarojs/taro-weapp: 2.1.3 => 2.1.3 
      @tarojs/webpack-runner: 2.1.3 => 2.1.3 
      eslint-config-taro: 2.1.3 => 2.1.3 
      eslint-plugin-taro: 2.1.3 => 2.1.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.1.3 => 2.1.3 
      stylelint-taro-rn: 2.1.3 => 2.1.3 
      taro-ui: ^2.3.3 => 2.3.3 

### 补充信息

没有报错，但就是没效果

**Comment by Chen-jj** [comment]
@wforguo 微信的锅，length 在按路径 setData 时不会更新。所以不能直接用 length 做判断，用你的写法 2 绕过咯。

![image](https://user-images.githubusercontent.com/11807297/80557958-36fc5000-8a0b-11ea-9d51-c34bbd247acc.png)

http://taro-docs-in.jd.com/taro/docs/debug.html#%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E6%8A%A5%E9%94%99%EF%BC%8C%E4%BD%86%E6%98%BE%E7%A4%BA%E7%9A%84%E7%BB%93%E6%9E%9C%E4%B8%8D%E5%A6%82%E9%A2%84%E6%9C%9F

**Comment by wforguo** [comment]
好的，了解，感谢
