### ISSUE TITLE
 taro init myApp 直接报错 Maximum call stack size exceeded     at String.replace 

### ISSUE THREAD

**Issue by zhouruikun** [NervJS/taro#6164]
![image](https://user-images.githubusercontent.com/16750501/80564185-b5fb8380-8a1f-11ea-9952-4147a9682f70.png)
起步闷头一棒子   安装完到 taro init myApp  直接报错
![image](https://user-images.githubusercontent.com/16750501/80564211-cdd30780-8a1f-11ea-80c8-09e61d689a88.png)
求da's大神指导

**Comment by cat0771** [comment]
同样的问题，早上还正常，临近中午就崩了，taro的命令都报这个错😭😭😭

**Comment by vand7813** [comment]
我是今天升级到2.2.0，老项目也跑不起来了

**Comment by luckyadam** [comment]
> 我是今天升级到2.2.0，老项目也跑不起来了

试试 2.2.1

**Comment by luckyadam** [comment]
> 同样的问题，早上还正常，临近中午就崩了，taro的命令都报这个错😭😭😭

升级了么

**Comment by luckyadam** [comment]
没有复现 issue 中描述的问题，请再试试

**Comment by cat0771** [comment]
> > 同样的问题，早上还正常，临近中午就崩了，taro的命令都报这个错😭😭😭
> 
> 升级了么

cli指定2.2.1版本，创建项目还是报这个错，回退到2.1.5版本了😂

**Comment by luckyadam** [comment]
> > > 同样的问题，早上还正常，临近中午就崩了，taro的命令都报这个错😭😭😭
> > 
> > 
> > 升级了么
> 
> cli指定2.2.1版本，创建项目还是报这个错，回退到2.1.5版本了😂

麻烦提供一些更具体的信息，系统号以及 node 版本，我没有复现这个问题

**Comment by cat0771** [comment]
> > > > 同样的问题，早上还正常，临近中午就崩了，taro的命令都报这个错😭😭😭
> > > 
> > > 
> > > 升级了么
> > 
> > 
> > cli指定2.2.1版本，创建项目还是报这个错，回退到2.1.5版本了😂
> 
> 麻烦提供一些更具体的信息，系统号以及 node 版本，我没有复现这个问题
系统及node版本
![微信截图_20200429162607](https://user-images.githubusercontent.com/41979905/80575460-3927d400-8a36-11ea-9e34-7eba37c462f2.png)

**Comment by vand7813** [comment]
> > 我是今天升级到2.2.0，老项目也跑不起来了
> 
> 试试 2.2.1

可以了

**Comment by zhouruikun** [comment]
> > > > 同样的问题，早上还正常，临近中午就崩了，taro的命令都报这个错😭😭😭
> > > 
> > > 
> > > 升级了么
> > 
> > 
> > cli指定2.2.1版本，创建项目还是报这个错，回退到2.1.5版本了😂
> 
> 麻烦提供一些更具体的信息，系统号以及 node 版本，我没有复现这个问题

![image](https://user-images.githubusercontent.com/16750501/80664118-7dfc4b00-8ac8-11ea-8de4-9231a9e65071.png)
问题依旧
![image](https://user-images.githubusercontent.com/16750501/80664195-ab48f900-8ac8-11ea-8c40-84e2305593e5.png)
