### ISSUE TITLE
在Taro文档2.2.1中  基础教程->语法特性->Render Props案例无法在微信小程序中正常运行

### ISSUE THREAD

**Issue by jsLyLeeHi** [NervJS/taro#6165]
### 问题描述
按照Taro文档2.2.1->基础教程->语法特性->Render Props案例 操作，无法从父组件把值通过this.props.renderXXX('xxx') 传给 renderXXX组件

### 复现步骤
按照Taro文档2.2.1->基础教程->语法特性->Render Props案例操作即可复现
```js
// cat.js
import catImage from './cat.jpg'
class Cat extends Taro.Component {
  static defaultProps = {
    mouse: {
      x: 0,
      y: 0
    }
  }

  render() {
    const { mouse } = this.props;
    return (
      <Image src={catImage} style={{ position: 'absolute', left: `${mouse.x}px`, top: `${mouse.y}px` }} />
    );
  }
}

// mouse.js
class Mouse extends Taro.Component {
  constructor(props) {
    super(props);
    this.handleMouseMove = this.handleClick.bind(this);
    this.state = { x: 0, y: 0 };
  }

  handleClick(event) {
    const { x, y }  = event.detail
    this.setState({
      x,
      y
    });
  }

  render() {
    return (
      <View style={{ height: '100%' }} onClick={this.handleClick}>

        {/*
          我们可以把 prop 当成一个函数，动态地调整渲染内容。
        */}
        {this.props.renderCat(this.state)}
      </View>
    );
  }
}

// MouseTracker.js
class MouseTracker extends Taro.Component {
  render() {
    return (
      <View>
        <View>点击鼠标!</View>
        {/*
          Mouse 如何渲染由 MouseTracker 的状态控制
        */}
        <Mouse renderCat={mouse => (
          <Cat mouse={mouse} />
        )}/>
      </View>
    );
  }
}
```

### 期望行为
希望从父组件把值通过this.props.renderXXX('xxx') 传给 renderXXX组件

### 报错信息
无报错信息

### 系统信息

Taro CLI 2.1.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD

### 补充信息
无补充信息

**Comment by Chen-jj** [comment]
@jsLyLeeHi MouseTracker 加个高度

![image](https://user-images.githubusercontent.com/11807297/80857639-3ae7d680-8c86-11ea-8dbe-6f459f904b42.png)

![image](https://user-images.githubusercontent.com/11807297/80857648-463b0200-8c86-11ea-8473-189fea39f769.png)
