### ISSUE TITLE
input框的adjustPosition无效

### ISSUE THREAD

**Issue by lengfangbing** [NervJS/taro#6167]
### 在字节跳动小程序中, 使用@tarojs/components的Input组件, 设置了adjustPosition, 但是并没有起作用

@tarojs/cli 2.0.5

### 复现步骤
<Input
    adjustPosition
    value={tel}
    onInput={this.telInput}
    maxLength={11}
    type='number'
    placeholder='请输入手机号'
    placeholderStyle={placeholderStyle}
    />
这是组件所有参数, 然而adjustPosition并没有使键盘将页面上推

在官方的IDE中, 使用真机调试打开, 然后点击input聚焦, 可以输入但是页面没有上推

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

<Input
    adjustPosition
    value={tel}
    onInput={this.telInput}
    maxLength={11}
    type='number'
    placeholder='请输入手机号'
    placeholderStyle={placeholderStyle}
    />
```

### 期望行为

期望可以使得adjustPosition生效上推页面

### 报错信息

并没有报错, 也没有警告

### 系统信息

![image](https://user-images.githubusercontent.com/46396510/80591842-f6bfc080-8a50-11ea-8a78-334bcc4e753e.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by lengfangbing** [comment]
希望可以指正

**Comment by Chen-jj** [comment]
@lengfangbing 字节有这个属性？

**Comment by lengfangbing** [comment]
> @lengfangbing 字节有这个属性？

抱歉, 我看api支持度是没有字节小程序的, 意思是不支持吗?

**Comment by Chen-jj** [comment]
@lengfangbing 基于小程序平台本身，taro 只是把属性打上去 xml 的 input 标签

**Comment by lengfangbing** [comment]
> @lengfangbing 基于小程序平台本身，taro 只是把属性打上去 xml 的 input 标签

我懂了, 多谢指正
