### ISSUE TITLE
State中的Date参数发生变化时后，作为props参数传给子组件时为空

### ISSUE THREAD

**Issue by wongyouth** [NervJS/taro#617]
**问题描述**

如题：

在state初始化后，time 作为参数是能传给 Timer 组件的，
当 time 变化后，Timer 组件内取到的 time 为 `{}`

```
  state = {
    time: new Date()
  }

  componentDidMount () {
    setInterval(() => this.tick(), 1000)
  }

  tick () {
    this.setState({
      time: new Date()
    })
  }

  render () {
    return (
      <View className="index">
        <Timer  time={this.state.time} />
      </View>
    )
  }
```

**复现步骤**

![](https://github.com/wongyouth/tarojs-fail-to-pass-date/raw/master/demo.gif)

上图是测试了下面几种情况
* 本组件内部 Date  - 不更新
* 本组件内部 toString()  - 更新
* 子组件内部 Date传入 - 不更新，取不到值
* 子组件内部 String传入 - 更新

```
  render () {
    return (
      <View className="index">
        <View>index/time</View>
        <View>{this.state.time}</View>
        <View>index/time.toString()</View>
        <View>{this.state.time.toString()}</View>
        <Timer title="Timer time passed as Date" time={this.state.time} />
        <Timer title="Timer time passed as String" time={this.state.time.toString()} />
      </View>
    )
  }
```

repo: https://github.com/wongyouth/tarojs-fail-to-pass-date

**期望行为**

子组件能取到变化后的Date值

**报错信息**

**系统信息**

 - 操作系统: [OSX v10.13.6]
 - 微信开发者工具 [v1.0.2.1808300]
 - Taro 版本 [v1.0.0-beta.21]
 - Node.js 版本 [v10.7.0]

**Comment by luckyadam** [comment]
小程序里 setData 更新页面时，数据会被序列化，所以传入 Date 对象，最后再反序列化出来会变成 String，所以不建议将 Date 对象直接放入 `state` 中

**Comment by wongyouth** [comment]
如果序列化后传递的值是String，也可以勉强接受的， 但是现在变空了，好像哪里不对。

@luckyadam 如果state不建议放置对象型数据的话，请问这种会变化的对象型数据如何传递给子组件？有最佳实践吗？

**Comment by yuche** [comment]
你可以理解为微信小程序会对 state 进行一个先 `JSON.stringify` 再 `JSON.parse`，普通的对象是可以传递的，但当你的 `Date` 对象经过这个操作之后他的原型上就没有原来 `Date` 的方法了。

就你这个情况可以传入一个时间戳，或者一个包含了年月日时的对象，然后再用 `new Date` 初始化。

**Comment by luckyadam** [comment]
@wongyouth 这种情况可以使用时间戳代替，state 里最好只放基本类型、普通对象以及数组

**Comment by luckyadam** [comment]
@wongyouth 因为 mpvue 的组件化是使用 template 来实现的，Taro 组件化是使用原生的方案，所以正义点还是无法做到

**Comment by BigBigWen** [comment]
我也遇到了类似的问题,父组件中的state ` data={ name:'哈哈',id:2}`以props的形式传入子组件中,当父组件` setState({ data:{} })` 子组件中渲染的还是上次的值,并未更新为`{}`, 但如果该data对象中更改`name`或者`id`的值时,子组件接受到的`props`也是正常更新的

**Comment by luckyadam** [comment]
@BigBigWen 新开一个 issue 贴下代码吧
