### ISSUE TITLE
Taro 不能在if里面return？

### ISSUE THREAD

**Issue by hankduan** [NervJS/taro#6174]
我在index.tsx里面有以下code
```
render() {
  const foo = true
  console.log("1: " + foo)
  if (foo) {
    console.log("2")
    return <View>hello</View>
  }
  console.log("3")
  return <View>hmm</View>
}
```

console显示的是
```
1 true
2
3
```

完全忽视了return。
有人知道为什么吗？

<img width="546" alt="Screen Shot 2020-04-29 at 11 37 03 AM" src="https://user-images.githubusercontent.com/1059345/80633524-c571d100-8a0d-11ea-90ce-e78afe01a6e4.png">

**Comment by Chen-jj** [comment]
@hankduan 使用 render 外的变量做判断吧。直接给 foo 设置 true，编译时会有问题。

```js
export default class Index extends Taro.Component {
  state = {
    foo: true
  }
  render() {
    console.log("1: " + this.state.foo)
    if (this.state.foo) {
      console.log("2")
      return <View>hello</View>
    }
    console.log("3")
    return <View>hmm</View>
  }
}
```

**Comment by hankduan** [comment]
就算是用state还是错误的啊

用你的code还是会print
```
1: true
2
3
```

代表那个return还是没有真正的return

**Comment by Chen-jj** [comment]
@hankduan 你可以结合编译后的 wxml 和 js 来看。Taro 的 render 会编译成 createData 函数用于计算 data，if 逻辑由 wxml 的 wx:if 控制。虽然 log 会打印，但渲染是正确的。

**Comment by Chen-jj** [comment]
@hankduan 你可以结合编译后的 wxml 和 js 来看。Taro 的 render 会编译成 createData 函数用于计算 data，if 逻辑由 wxml 的 wx:if 控制。虽然 log 会打印，但渲染是正确的。
