### ISSUE TITLE
taro next vue sass 使用 lang="sass" 构建报错

### ISSUE THREAD

**Issue by eiddie** [NervJS/taro#6176]
### 问题描述

`taro next` beta5 vue 使用 `lang="sass"`构建报错， `lang="scss"`是正常的

react 中都是正常的

### 复现步骤

```vue
<template>
  <view class="index">
    <text class="msg">hello eid</text>
  </view>
</template>

<style lang="sass">
.msg
  color: red
</style>

```

### 期望行为

`taro next vue` 能够同时使用`lang="sass"`和`lang="scss"`构建正常

### 报错信息

![image](https://user-images.githubusercontent.com/62737990/80665440-19db8600-8acc-11ea-8adf-87475a71093b.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@eiddie sass-loader 默认不处理缩进语法，如果需要处理的话你可以加个配置。

```js
mini: {
  sassLoaderOption: {
    sassOptions: {
      indentedSyntax: true
    }
  }
}
```

**Comment by eiddie** [comment]
> @eiddie sass-loader 默认不处理缩进语法，如果需要处理的话你可以加个配置。
> 
> ```js
> mini: {
>   sassLoaderOption: {
>     sassOptions: {
>       indentedSyntax: true
>     }
>   }
> }
> ```

在`taro next vue`中这个配置作用只能是要么使用`.sass`,要么使用`.scss` ,两种语法不能共存

但是`react` 中 这两种语法是能够共存的，`sass-loader` 默认情况下也处理了缩进语法

```tsx
import React from 'react'
import { View} from '@tarojs/components';

import './hello-scss.scss'
import './hello-sass.sass'
const TestSass: React.FC  = () => {

  return (
    <View className="test-sass">
        <View className="hello-sass">hello sass</View>
        <View className="hello-scss">hello scss</View>
    </View>
  );
}

export default TestSass;
```

`hello-scss.scss`:

```scss
.hello-scss {
  color: blue;
}
```

`hello-sass.sass`:

```sass
.hello-sass
  color: red


```
