### ISSUE TITLE
升级至2.2.2版本之后，出现UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dreamthen** [NervJS/taro#6178]
### 问题描述

升级至2.2.2版本之后，出现UnhandledPromiseRejectionWarning

### 复现步骤

taro update self之后，直接taro update project，就会立马出现

### 期望行为

希望官方能够把promise、async await做try catch处理，这样能够handle住

### 报错信息

![image](https://user-images.githubusercontent.com/13704681/80674826-8911a400-8ae5-11ea-9345-566a9cc6aa47.png)

### 系统信息

taro: v2.2.2
node: v12.16.3
npm: v6.14.4

**Comment by luckyadam** [comment]
是因为配置不对，编译配置有了调整
https://nervjs.github.io/taro/docs/migrate-to-2.html#%E7%BC%96%E8%AF%91%E9%85%8D%E7%BD%AE%E8%B0%83%E6%95%B4
plugins 配置现在是个数组
https://nervjs.github.io/taro/docs/config-detail.html#plugins

**Comment by dreamthen** [comment]
好的，我看下

**Comment by dreamthen** [comment]
好了，等以后仔细看文档😂
