### ISSUE TITLE
taro next h5 component Swiper 动态更新swiperItem数量样式错乱且不能滑动

### ISSUE THREAD

**Issue by eiddie** [NervJS/taro#6179]
### 问题描述
- `taro next ` beta5 react  h5 component动态增加`SwiperItem`数量，`Swiper`样式错乱， 不能滑动

- 减少`SwiperItem`数量直接报错

### 复现步骤

**增加`swiperItem`数量**
```tsx
import React,{ useState} from 'react'
import { View, Swiper, SwiperItem , Button} from '@tarojs/components';

import './index.scss'

const SwiperTest: React.FC  = () => {
  const [arr, setArr] = useState<Array<number>>([]);

  const handleClick = () => {
    setArr([1, 2, 3, 4])
  }
  return (
    <View className="test-swiper">
      <View>
        <Button onClick={handleClick}>update arr</Button>
      </View>
      <Swiper
      className='test-h'>
        {arr.map((item, index) => (
          <SwiperItem key={index}>
            <View className="item">swiper item{item}</View>
          </SwiperItem>
        ))}
      </Swiper>
    </View>
  );
}

export default SwiperTest

```

```scss
.test-h {
  height: 500px;
  .swiper-container {
    height: 500px;
  }
  .item {
    width:630px;
    height:425px;
    border: 1px solid red;
  }
}

```

**减少`SwiperItem`数量**

```tsx
  const [arr, setArr] = useState<Array<number>>([1,2,3,4]);

   const handleClick = () => {
    setArr([1，2])
  }

```
### 期望行为
动态更新`SwiperItem`数量`Swiper`  h5 端样式不会错乱且能够滑动， 和小程序保持一致

#### 增加swiperItem数量

h5 截图
![image](https://user-images.githubusercontent.com/62737990/80675521-3c2ecd00-8ae7-11ea-83c9-2d380fc680e2.png)

小程序截图
![image](https://user-images.githubusercontent.com/62737990/80675612-7dbf7800-8ae7-11ea-8c92-5b9605886778.png)

#### 减少SwiperItem数量

h5 报错截图
![image](https://user-images.githubusercontent.com/62737990/80681872-18be4f00-8af4-11ea-88ab-2d2821c841c1.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by eiddie** [comment]
##  workaround: 更新`Swiper` key值，让`Swiper`重新渲染

```tsx
 <Swiper
        key={arr.join('_')}
        className='test-h'>
        {arr.map((item) => (
          <SwiperItem key={item}>
            <View className="item">swiper item{item}</View>
          </SwiperItem>
        ))}
 </Swiper>

```

**Comment by WenMaoLin** [comment]
我也出现了这个问题，而且设置一个 type 来动态切换 Video，和 Swiper，会报另外一个错误

**Comment by xmsz** [comment]
这个swiper也太蛋疼了吧

只要是动态渲染swiperItem就会一直疯狂重渲染...

然后只能给swiper加个key这种蛋疼的操作

什么鬼bug

**Comment by ZakaryCode** [comment]
非 circular 模式下确实会有该问题，将在下一个版本修复
