### ISSUE TITLE
Taro 2.2 创建项目没有 typescript 选项

### ISSUE THREAD

**Issue by youngluo** [NervJS/taro#6180]
### 问题描述

![image](https://user-images.githubusercontent.com/7480381/80681249-dea07d80-8af2-11ea-864b-30d94627e208.png)

### 期望行为

正常

**Comment by luckyadam** [comment]
确实有问题，暂时用
```
taro init myApp --typescript
```

这个命令吧

**Comment by youngluo** [comment]
> 确实有问题，暂时用
> 
> ```
> taro init myApp --typescript
> ```
> 
> 这个命令吧

ojbk
