### ISSUE TITLE
H5端Viedeo标签在iOS 端点击全屏播放进度条进度丢失会重头开始播放

### ISSUE THREAD

**Issue by QIUYON** [NervJS/taro#6184]
### 问题描述

H5端Viedeo标签在iOS 端点击全屏播放进度条进度丢失会重头开始播放

### 复现步骤

                <Video
                    ref={videos}
                    className='components-video'
                    src='http://192.168.147.112:8080/%E4%BB%BB%E5%8A%A11%EF%BC%9A1_%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%B3%A8%E5%86%8C%E5%8F%8A%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E7%9A%84%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8.mp4'
                    poster='http://192.168.147.112:8080/cover_900x500.jpg'
                    controls={true}
                    autoplay={true}
                    showMuteBtn={true}
                    showPlayBtn={true}
                    showFullscreenBtn={true}
                    showCenterPlayBtn={true}
                    playBtnPosition='center'
                    initialTime={0}
                    loop={false}
                    // onFullscreenChange={e => { onFullscreenChange(e) }}
                    // onTimeUpdate={(e) => onTimeUpdate(e)}
                    // onPlay={() => onPlay()}
                    muted={false} // 是否静音播放
                />

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

 点击全屏播放进度条进度不应该丢失，理论上全屏播放应该很流畅播放，不会出现卡断

### 系统信息

Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/mini-runner: 2.0.7 => 2.0.7 
      @tarojs/redux: 2.0.7 => 2.0.7 
      @tarojs/redux-h5: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.7 => 2.0.7 
      stylelint-taro-rn: 2.0.7 => 2.0.7 
    npmGlobalPackages:
      typescript: 3.7.2
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by heyang1014** [comment]
@QIUYON 大佬这个问题解决了吗。我也是在taro里面用的自己的video组件。全屏的时候会丢失进度，重新开始播放。方便留个联系方式吗
