### ISSUE TITLE
[Feature request] 建议替换 Image 组件的 src 属性为 source

### ISSUE THREAD

**Issue by lstsq** [NervJS/taro#6188]
### 问题描述

各位开发者们，您们好！

由于 *React* 的 `<Image />` 组件原本是使用 `source` 作为属性名的，所以建议将该组件的 [`src`](https://nervjs.github.io/taro/docs/components/media/image.html#imageprops) 属性替换为 [`source`](https://reactnative.dev/docs/image#source) 。

更多地，这里的 [命名规范](https://github.com/airbnb/javascript/tree/master/react#naming) 也说明，属性名与 `<img />` 标签的 `src` 雷同好像不太合适。

### 复现步骤

无

### 期望行为

如题，将 `<Image />` 组件的 `src` 替换成 `source` 。

### 报错信息

无

### 系统信息

无

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Garfield550** [comment]
Taro 所有组件的属性以微信小程序组件库的属性命名
https://developers.weixin.qq.com/miniprogram/dev/component/image.html
