### ISSUE TITLE
小程序Ad 组件增加 props

### ISSUE THREAD

**Issue by Q-Qplus1s** [NervJS/taro#6189]
现有版本AD组件只支持 unitId props，小程序广告多样，包括视频广告、格子广告等，Ad 组件需要增加 props (typescript .d.ts) 文件
- adType
- gridOpacity
- gridCount
- adTheme

```html
<ad unit-id="adunit-123456" ad-type="grid" grid-opacity="0.8" grid-count="5" ad-theme="white"></ad>
```

**Comment by Chen-jj** [comment]
@Q-Qplus1s 已补上 adType、adTheme。但微信小程序文档中找不到 gridOpacity 和 gridCount，所以暂时没补这两个。如果你知道文档位置，欢迎提 PR 修改～
