### ISSUE TITLE
[Taro3 beta5] 从2.x复制过来的types把3.x分支弄的一团糟

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#6192]
### 问题描述

@ZakaryCode  https://github.com/NervJS/taro/commit/9b24f46b95527e04569f77f618ca072c1af6056f

随便举几个例子:

1. 事件 event 类型变成了 Function
```
	ScrollView
	onScroll?: (event: CommonEventFunction<ScrollViewProps.onScrollDetail>) => any
```
2. API 参数 Params 变成了 Option
```
	Taro.request<T = any, U = any>(option: request.Option<U>)
```
3. 原本已经修复的 BUG 都回来了
```
	Taro.request({dataType: '其他'})
```

### 复现步骤

https://github.com/NervJS/taro/commit/9b24f46b95527e04569f77f618ca072c1af6056f

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
1. 该问题在 2.x 中已经修复
2. 参数名更改只是统一，并不会影响实际使用
3. 该问题存在，已经在 2.x 中同步修复

> 列举问题修复将在 #6220 合并到 next 分支

**Comment by cncolder** [comment]
@ZakaryCode 我只是"随便举几个例子", 还有很多修复类型的PR是针对 next 分支的, 现在都被2.0覆盖掉了.

**Comment by ZakaryCode** [comment]
> @ZakaryCode 我只是"随便举几个例子", 还有很多修复类型的PR是针对 next 分支的, 现在都被2.0覆盖掉了.

确实有部分 next 分支修复类型相关的 pr 被覆盖了，相关内容已经找回，如果有缺失的部分，可以在这里指出，或者帮忙提交一个新的 pr 来修复

**Comment by cncolder** [comment]
我能找到我之前提交的部分, 印象中还有很多 next only pr 专门修复类型的.

https://github.com/NervJS/taro/pulls?q=is%3Apr+author%3Acncolder+is%3Amerged+fix+in%3Atitle

**Comment by ZakaryCode** [comment]
> @ZakaryCode 我能找到我之前提交的部分, 印象中还有很多 next only pr 专门修复类型的.
> 
> https://github.com/NervJS/taro/pulls?q=is%3Apr+author%3Acncolder+base%3Anext+is%3Amerged+fix+in%3Atitle

这一部分在 next 分支中，都可以找到对应的部分，感谢提供，如果还有发现欢迎反馈
