### ISSUE TITLE
函数式组件中使用闭包函数式组件 ESLint(react/no-multi-comp)报错

### ISSUE THREAD

**Issue by Zephyrrro** [NervJS/taro#6203]
### 问题描述
在函数式组件中使用闭包函数式组件时，编译正常通过，但有 `ESLint(react/no-multi-comp)` 报错

### 复现步骤
1. 创建一个函数式组件页面
2. 在函数中使用闭包函数组件
3. 在 `return` 时执行闭包函数

![image](https://user-images.githubusercontent.com/43735265/80917921-96a08580-8d94-11ea-81f0-03d2ba482b66.png)

```js
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default function Test() {
  const renderSomething = () => {
    return <View>something</View>
  }
  return (
    <View>
      {renderSomething()}
    </View>
  )
}
```

### 期望行为
`eslint` 不报错

### 报错信息
ESLint(react/no-multi-comp) 错误：一个文件只能定义一个 Taro 类或 Taro 函数式组件

### 系统信息
  Taro CLI 2.2.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - D:\yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD

**Comment by princeMing** [comment]
同问  .eslintrc.js 怎么写都不起作用

**Comment by ItAzeY** [comment]
同问, Taro CLI 1.3.27, 和上面的错误一样
