### ISSUE TITLE
微信小程序页面跳转巨慢，最快都需要1s

### ISSUE THREAD

**Issue by mouse9527** [NervJS/taro#6208]
### 问题描述
微信小程序页面跳转巨慢，最快都需要1s

### 复现步骤

taro + ts + dva 使用 Taro.redirectTo/Taro.navigateTo 从触发到render调用至少需要1s，经常2～3s

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
请提供一个可以复现的 demo
