### ISSUE TITLE
在父组件中实现render无法编译

### ISSUE THREAD

**Issue by mouse9527** [NervJS/taro#6209]
### 问题描述
如题，在父组件中实现render方法，无法编译
![截屏2020-05-05 10 14 20](https://user-images.githubusercontent.com/34568564/81029954-91892680-8eb9-11ea-8c45-610fc5be14fa.png)

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
Taro 编译时处理 render 函数的，不支持继承或劫持 render

**Comment by mouse9527** [comment]
> Taro 编译时处理 render 函数的，不支持继承或劫持 render

后续会支持吗？这样不像是在用ts写react，很多地方都有巨大差异

**Comment by lihuaye** [comment]
> > Taro 编译时处理 render 函数的，不支持继承或劫持 render
> 
> 后续会支持吗？这样不像是在用ts写react，很多地方都有巨大差异

可以使用taro@next版本

**Comment by Chen-jj** [comment]
@mouse9527 

@lihuaye 正解
