### ISSUE TITLE
rn中文编译乱码，

### ISSUE THREAD

**Issue by gaobo267258113** [NervJS/taro#621]
原始代码为
<Input className='flex6 searchInput' type='text' placeholder='输入车场' />
编译后不显示中文，出现编码

**Comment by Pines-Cheng** [comment]
补充：编译后中文字符变成 utf-8 的字符，但是不影响 title 等的显示；不过Input 组件的 placeholder 会直接显示 utf-8 的字符 ，因此，最好能够解决中文编译后变成 utf-8 的字符 的问题。
