### ISSUE TITLE
taro  build:weapp 样式无效

### ISSUE THREAD

**Issue by monkeyCheng** [NervJS/taro#6214]
### 问题描述
用taro编译成微信小程序，build:weapp之后发现公共样式不起作用，dev:weapp 没有问题，看了下build之后的dist文件没有wxss，是不是一样要一个组件对应一个css文件？

### 复现步骤

1. 
![11611588735173_ pic](https://user-images.githubusercontent.com/22185735/81136807-2f9af080-8f8f-11ea-888b-881c56c5ecb0.jpg)
2. 
![image](https://user-images.githubusercontent.com/22185735/81136515-59074c80-8f8e-11ea-9ed6-74a733ee0b05.png)
3. 
build:weapp之后，style.less没有编译出来，其他一个组件对应一个文件都没问题，dev:weapp 也没问题
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by monkeyCheng** [comment]
> taro 版本多少
2.1.3

**Comment by luckyadam** [comment]
代码怎么写的

**Comment by monkeyCheng** [comment]
这跟代码怎么写的有什么关系？？ dev 能编译出来文件的，build 编译出来没有文件的

**Comment by luckyadam** [comment]
升级到 2.1.5 或者 2.2.3 试试
