### ISSUE TITLE
H5端 chooseImage 设置 count为3，打开相册后依然能选择3张以上的图片

### ISSUE THREAD

**Issue by DBliuchengjie** [NervJS/taro#6215]
### 问题描述
H5端 Taro.chooseImage API 设置了 count 为3，但是打开相册后，还是能一次性选择超过3张图片。

### 复现步骤
点击事件回调函数里，直接调用下方代码

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
Taro.chooseImage({
      count: 3,
      success: function(){
        console.log('2222266666')
      }
    })

```

### 期望行为

打开相册后，最多只能选择3张图片
### 系统信息

👽 Taro v2.0.4

  Taro CLI 2.0.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.4 => 2.0.4
      @tarojs/components-qa: 2.0.4 => 2.0.4
      @tarojs/mini-runner: 2.0.4 => 2.0.4
      @tarojs/redux: 2.0.4 => 2.0.4
      @tarojs/redux-h5: 2.0.4 => 2.0.4
      @tarojs/router: 2.0.4 => 2.0.4
      @tarojs/taro: 2.0.4 => 2.0.4
      @tarojs/taro-alipay: 2.0.4 => 2.0.4
      @tarojs/taro-h5: 2.0.4 => 2.0.4
      @tarojs/taro-qq: 2.0.4 => 2.0.4
      @tarojs/taro-quickapp: 2.0.4 => 2.0.4
      @tarojs/taro-swan: 2.0.4 => 2.0.4
      @tarojs/taro-tt: 2.0.4 => 2.0.4
      @tarojs/taro-weapp: 2.0.4 => 2.0.4
      @tarojs/webpack-runner: 2.0.4 => 2.0.4
      eslint-config-taro: 2.0.4 => 2.0.4
      eslint-plugin-taro: 2.0.4 => 2.0.4
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.0.4 => 2.0.4
      stylelint-taro-rn: 2.0.4 => 2.0.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Littly** [comment]
web端的`input[type='file']`无法限制数量

**Comment by DBliuchengjie** [comment]
@Littly 我设置了count: 3，选择了5张图片，回调返回的文件数组还是有5个图片文件。打印结果如下：
![选择后的回调数据](https://user-images.githubusercontent.com/20755094/81142535-7e9e5100-8fa2-11ea-8b01-5278bbd4d4d4.jpeg)

代码如下：
`
Taro.chooseImage({
      count:3
    })
      .then((res) => {
        console.log('选择后的回调数据：',res);
      })
`

**Comment by Littly** [comment]
更新一下即可，你的版本有点旧。

**Comment by DBliuchengjie** [comment]
@Littly 好的，我试试

**Comment by DBliuchengjie** [comment]
@Littly Taro 升级到 2.1.5 版本后可以了。谢谢你~
