### ISSUE TITLE
taro next h5 component Button disabled 会触发onClick事件

### ISSUE THREAD

**Issue by eiddie** [NervJS/taro#6216]
### 问题描述
taro next beta5 h5 component `Button` 设置`disabled`仍然会触发`onClick`事件

### 复现步骤
```tsx
import React from 'react'
import { View, Button} from '@tarojs/components';

const ButtonDisabled: React.FC  = () => {
  const handleClick = () => {
    console.log('hello eid')
  }
  return (
    <View className="test-disabled">
        <Button onClick={handleClick} disabled>test disabled</Button>
    </View>
  );
}

export default ButtonDisabled
```

### 期望行为
`Button`设置`disabled`为`true`, 点击button不会触发`onClick`事件, h5 和 小程序保持一致

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by teaim** [comment]
Taro 3.3.10依然存在这个问题啊

怎么会标记成Closed
