### ISSUE TITLE
层级node_modules引用编译失败

### ISSUE THREAD

**Issue by nighsen** [NervJS/taro#6223]
### 问题描述
层级node_modules引用编译失败

### 复现步骤
1. 引用已经封装的nodemodule组件，该组件中引用@sabaki\immutable-gametree
2. 编译失败
![捕获](https://user-images.githubusercontent.com/12277426/81165212-355ef900-8fc4-11ea-9d03-d51d78593099.PNG)

3. 编译时应该去node_modules文件夹下寻找@sabaki\immutable-gametree，现在去自定义组件路径里面去找，结果找不到文件，编译失败

4.自定义组件里面使用了neutrinojs

### 系统信息
![捕获](https://user-images.githubusercontent.com/12277426/81165413-82db6600-8fc4-11ea-8c1b-c673e24e91b3.PNG)

**Comment by luckyadam** [comment]
能否提供个 demo 看下
