### ISSUE TITLE
2.2.3升级后，修改文件后自动出行不必要的日志。如何去掉？

### ISSUE THREAD

**Issue by jimtang9527** [NervJS/taro#6224]
### 问题描述
每次修改文件，都会出现这样的日志信息
Compiled successfully!

{
  error: null,
  stats: Stats {
    compilation: Compilation {
      _pluginCompat: [SyncBailHook],
      hooks: [Object],
      name: undefined,
      compiler: [Compiler],
      resolverFactory: [ResolverFactory],
      inputFileSystem: [CachedInputFileSystem],
      requestShortener: [RequestShortener],
      options: [Object],
      outputOptions: [Object],
      bail: undefined,
      profile: undefined,
      performance: false,
      mainTemplate: [MainTemplate],
      chunkTemplate: [ChunkTemplate],
      hotUpdateChunkTemplate: [HotUpdateChunkTemplate],
      runtimeTemplate: [RuntimeTemplate],
      moduleTemplates: [Object],
      semaphore: [Semaphore],
      entries: [Array],
      _preparedEntrypoints: [Array],
      entrypoints: [Map],
      chunks: [Array],
      chunkGroups: [Array],
      namedChunkGroups: [Map],
      namedChunks: [Map],
      modules: [Array],
      _modules: [Map],
      cache: [Object],
      records: [Object],
      additionalChunkAssets: [Array],
      assets: [Object],
      assetsInfo: [Map],
      errors: [],
      warnings: [],
      children: [Array],
      logging: [Map],
      dependencyFactories: [Map],
      dependencyTemplates: [Map],
      childrenCounters: [Object],
      usedChunkIds: Set {},
      usedModuleIds: null,
      fileTimestamps: [Map],
      contextTimestamps: [Map],
      compilationDependencies: Set {},
      _buildingModules: Map {},
      _rebuildingModules: Map {},
      emittedAssets: Set {},
      fullHash: '2da715948df5caeeaf1636ad827646bb',
      hash: '2da715948df5caeeaf16',
      fileDependencies: [SortableSet [Set]],
      contextDependencies: [SortableSet [Set]],
      missingDependencies: [SortableSet [Set]]
    },
    hash: '2da715948df5caeeaf16',
    startTime: 1588761022013,
    endTime: 1588761022333
  },
  isWatch: true
}

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by jimtang9527** [comment]
{node_modules/@tarojs/webpack-runner/dist/index.js}
文件下有2处
`const onBuildFinish = config.onBuildFinish`
将其修改为
`const onBuildFinish = null`

**Comment by Garfield550** [comment]
https://github.com/NervJS/taro/blob/c95f09b7bee437c06ef760a6f07629f290940231/packages/taro-cli/src/presets/platforms/h5.ts#L12-L14

**Comment by luckyadam** [comment]
d9e938d6b7add38bccdbd6fc1dcb0327016d30b4
已移除，下个版本修复
