### ISSUE TITLE
如果配置文件夹config不在根目录下，编译会找不到

### ISSUE THREAD

**Issue by GMCoder** [NervJS/taro#6225]
### 问题描述

由于项目问题，需要将config放到二级目录，不在根目录下，编译的时候无法找到在根目录下找到config文件夹，能否编译的时候可以传入config路径呢

### 报错信息

Error: Cannot find module '/Users/xxx/xxx/xxx/config/index.js'

**Comment by luckyadam** [comment]
额，目前是没有这个配置的
