### ISSUE TITLE
preval is not defined

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#6233]
### 问题描述
taro next 编译报 preval is not defined，babel-plugin-preval 是装了的

### 复现步骤
1、迁移到 Taro Next；
2、代码使用如下：
<img width="694" alt="1" src="https://user-images.githubusercontent.com/52092826/81264155-85e15f80-9073-11ea-8eaf-13d7ba444dd9.png">
3、编译

### 期望行为

编译正常

### 报错信息

<img width="1508" alt="2" src="https://user-images.githubusercontent.com/52092826/81264176-8c6fd700-9073-11ea-8c9b-6b9c80d0bb58.png">

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@cpocar [下个版本](https://github.com/NervJS/taro/milestone/5)再试试。

我们改用了 **@babel/register** 加载配置文件，会自动合并根目录的 babel.config.js 中的配置。只要你在 babel.config.js 中配置了使用 preval 插件即可。

pages/index/index.config.js

```js
export default {
  navigationBarTitleText: preval`
    module.exports = '首页A'
  `,
  usingComponents: {
    'tab': '../../components/tab/tab'
  }
}
```

babel.config.js
```js
// babel-preset-taro 更多选项和默认值：
// https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/README.md
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: false
    }]
  ],
  plugins: ["preval"]
}
```

![image](https://user-images.githubusercontent.com/11807297/81914061-5f876b00-9603-11ea-8d22-ea68a64ff4df.png)

**Comment by cpocar** [comment]
3.0.0.rc.2 仍然有问题啊 @Chen-jj 


![image](https://user-images.githubusercontent.com/52092826/83134099-70150680-a116-11ea-9721-6a12f209e5cb.png)



![image](https://user-images.githubusercontent.com/52092826/83134058-612e5400-a116-11ea-9cfe-60f5579320a5.png)

**Comment by Solyna** [comment]
Taro v3.5.10 仍然报错，babel.config.js 已配置plugins，且也安装了
