### ISSUE TITLE
字节跳动小程序引入原生组件ttss文件编译报错

### ISSUE THREAD

**Issue by 55utah** [NervJS/taro#6242]
### 问题描述
基于Taro 开发字节跳动小程序，根据文档 [使用第三方原生组件](https://nervjs.github.io/taro/docs/mini-third-party.html) 引入原生组件，在Taro 1.3.4版本时，代码可正常编译运行，Taro升级到2.2.3之后编译报错，ttss文件无法编译：报错信息如下：
`Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

### 复现步骤
在Taro 2.2.3 版本下，完成原生组件，具有ttml, ttss等文件，被Taro组件引用后，加入测试页面，最后进行编译运行；
（测试发现wxml, wxss在微信编译模式下可以编译，但是ttss文件无法在字节跳动编译模式下编译，ttml文件可以编译，所以认为是bug）

```js
import Taro from '@tarojs/taro';

function Test({}) {

    const chooseReaction = () => {
        console.warn(1)
    }

    return <reaction-panel
        onreactiontap={chooseReaction}
    ></reaction-panel>
}

Test.config = {
    usingComponents: {
        'reaction-panel':
            '../reaction_panel/index',
    },
};

export default Test
```

![image](https://user-images.githubusercontent.com/17704150/81284237-6e649f80-9090-11ea-9844-70f3e89cac93.png)

### 期望行为

期望可以正常编译原生组件的ttss文件。

### 报错信息

![image](https://user-images.githubusercontent.com/17704150/81284356-96540300-9090-11ea-95ec-c68633fad300.png)

### 系统信息

`👽 Taro v2.2.3

  Taro CLI 2.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/components-qa: 2.2.3 => 2.2.3 
      @tarojs/mini-runner: 2.2.3 => 2.2.3 
      @tarojs/redux: 2.2.3 => 2.2.3 
      @tarojs/redux-h5: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3 `

**Comment by scarcoco** [comment]
这个咋解决呢？ @55utah

**Comment by 55utah** [comment]
> 这个咋解决呢？ @55utah

还没有解决，所以提了bug, 一直没有回复我。。
