### ISSUE TITLE
页面的 onTabItemTap 方法在 1.0.0.beta-xx 中失效

### ISSUE THREAD

**Issue by o-jules** [NervJS/taro#625]
**问题描述**

使用 1.0.0.beta-xx 系列，页面的 onTabItemTap 方法失效（不触发）。

**复现步骤**

安装当前版本的 Tarojs（ 1.0.0-beta.26），创建新项目。创建两个页面 src/pages/index/index.tsx, src/pages/my/index.tsx，分别加入 App.tsx 的配置中。

```typescript
  config: Config = {
    pages: [
      'pages/index/index',
      'pages/my/index',
    ],
    tabBar: {
      list: [
        {
          pagePath: 'pages/index/index',
          text: '首页',
        },
        {
          pagePath: 'pages/my/index',
          text: '我的',
        }
      ]
    },
    window: {
      backgroundTextStyle: 'light',
      navigationBarBackgroundColor: '#fff',
      navigationBarTitleText: 'WeChat',
      navigationBarTextStyle: 'black'
    }
  }
```

分别在两个页面中加入 onTabItemTap 方法：

```typescript
  onTabItemTap(options) {
    console.log(options)
  }
```

**期望行为**

当点击 tab 时，onTabItemTap 应该被触发。

**系统信息**

 - 操作系统: 微信 6.7.2
 - Taro 版本: 1.0.0-beta.26
 - Node.js 版本: 8.11.2

**补充信息**

旧版本（1.0 以下）的页面被编译为 `Page(...)`；现在版本的页面被编译为`Component(...)`。

**Comment by Songkeys** [comment]
<https://developers.weixin.qq.com/community/develop/doc/000a8a2b204560d10847354aa56400>

小程序官方的问题。微信 6.7.2 的 bug。其实都快一个月了，还不修……

**Comment by o-jules** [comment]
> https://developers.weixin.qq.com/community/develop/doc/000a8a2b204560d10847354aa56400
> 
> 小程序官方的问题。微信 6.7.2 的 bug。其实都快一个月了，还不修……

微信官方论坛中出现问题的是安卓系统的某些版本。

我使用的是 iOS 版本的微信，原生的代码可以触发 onTabItemTap 方法，但是使用 Tarojs 生成的不可以；另外，旧版本的 Tarojs 生成的代码可以。

所以应该和微信无关。

**Comment by o-jules** [comment]
@Simbachen 谢谢，不过不可以的。我们要做用户行为追踪。

**Comment by changjunhao** [comment]
Taro 版本: 1.0.7
还是无法触发 onTabItemTap 方法

**Comment by luckyadam** [comment]
@changjunhao 应该是微信小程序的问题

**Comment by jswxwxf** [comment]
Taro v1.1.9 也不触发 ……
