### ISSUE TITLE
Taro 2.2.3 创建新项目出错

### ISSUE THREAD

**Issue by shrekuu** [NervJS/taro#6253]
### 问题描述

Taro 2.2.3 创建新项目出错
node v12.16.3
如下图

### 复现步骤

更新到最新的 2.2.3 版本后创建新项目, 然后就会看到. 

### 期望行为

期望创建项目

### 报错信息

![image](https://user-images.githubusercontent.com/3136026/81367078-ce098c00-911e-11ea-9f5c-7c506b2be87b.png)

### 系统信息

macOS Mojave

**Comment by Garfield550** [comment]
删掉 `~/.taro` 和 `~/.taro2` 文件夹，然后重新新建项目
