### ISSUE TITLE
同个tab item多次点击，页面会多次重新渲染

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#6257]
### 问题描述

已经在Tab页A，多次点击A对应的tab，会多次重新渲染
### 复现步骤

1. 多次点击同一个tab item
2. 页面多次重新渲染

### 期望行为

再次点击时不重新渲染

### 系统信息

    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvs/default/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/cli: 2.1.6 => 2.1.6 
      @tarojs/components: 2.1.6 => 2.1.6 
      @tarojs/mini-runner: 2.1.6 => 2.1.6 
      @tarojs/redux: 2.1.6 => 2.1.6 
      @tarojs/redux-h5: 2.1.6 => 2.1.6 
      @tarojs/router: 2.1.6 => 2.1.6 
      @tarojs/taro: 2.1.6 => 2.1.6 
      @tarojs/taro-h5: 2.1.6 => 2.1.6 
      @tarojs/taro-weapp: 2.1.6 => 2.1.6 
      @tarojs/webpack-runner: 2.1.6 => 2.1.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      taro-ui: ^2.3.3 => 2.3.3 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
应该不存在这个问题，可以详细描述下，或者尝试升级版本

**Comment by meow4world** [comment]
2.2.3仍存在此问题，h5上多次点击会重新渲染，小程序不会

**Comment by yulrosy** [comment]
是配置了customRoutes

**Comment by ZakaryCode** [comment]
新版本中 customRoutes 不会导致路由重复刷新，可以通过升级解决

**Comment by ZakaryCode** [comment]
和 #6498 是同一个问题，先关掉一个
