### ISSUE TITLE
编译字节跳动小程序时 Props 不会更新

### ISSUE THREAD

**Issue by yeojongki** [NervJS/taro#6260]
### 问题描述
**组件嵌套时**，更新数据 `setData` 后，其中一个组件数据不会更新。
微信小程序中是正确的，但是在字节跳动小程序中错误。

### 复现步骤
复现不好说明，我建了一个最小 repo: https://github.com/yeojongki/Taro-error-props.git
├─components
│  ├─Popup
│  └─SubCategory
└─pages
    └─index

在此页面中，有两个组件 `Popup` 和 `SubCategory`， `SubCategory` 在 `Popup` 中嵌套时，数据错误

1. 有两个父分类，包含着子分类，点击 `设为当前分类` 会将其在弹窗中显示
2. 点击第一个父分类，可以在弹窗中显示正确的数据
   - 弹窗中（嵌套）的数据**正确**
   - 页面中（非嵌套）中的数据**正确**
![image](https://user-images.githubusercontent.com/21023676/81401988-16e33400-9163-11ea-82b5-daf7f958e776.png)

3. 点击阴影处关闭弹窗
4. 此时点击第二个分类，数据就不正确了
   - 弹窗中（嵌套）的数据**错误**
   - 页面中（非嵌套）的数据**正确**
![image](https://user-images.githubusercontent.com/21023676/81401992-1ba7e800-9163-11ea-9f22-36a12ee29c6d.png)

对比页面中**非嵌套**的组件正确更新，说明只有**存在嵌套时**才会发生错误的情况

### 期望行为
正确更新数据并显示

### 报错信息
无

### 系统信息
�👽 Taro v2.1.5

  Taro CLI 2.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\My\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD

**Comment by yeojongki** [comment]
@Chen-jj @luckyadam 有进展没？

**Comment by Chen-jj** [comment]
@yeojongki 试了一下微信是可以的。Taro 中 children、renderProps 都是通过 slot 实现，这应该是头条对 slot 组件的销毁处理不同有关。

你可以把 Popup 组件的显隐判断放在 Popup 外，每次隐藏连同 Popup 一起销毁，绕开这个问题。因为小程序有点不一样，你目前的写法在隐藏时 React 中的确不存在 Popup，但小程序还是保存着 Popup 这个自定义组件。

```js
{this.state.showAllCats &&
    <Popup onClose={this.toggleShowAllCats}>
      <SubCategory list={this.state.subCategories}></SubCategory>
    </Popup>
}
```

**Comment by yeojongki** [comment]
@Chen-jj 我之前试过用原生的头条小程序是可以的，确定不是 `Taro` 的问题？

**Comment by Chen-jj** [comment]
@yeojongki 共同作用吧，Taro 这边的 props 系统在更新 SubCategory 时找不到对应的组件实例进行更新。

**Comment by yeojongki** [comment]
@Chen-jj 看看能不能查出问题? 我觉得这应该算是 `bug`，我看了源码微信和头条是有两个包的，而且代码会有区别，会不会是哪个环节有出错？

**Comment by Chen-jj** [comment]
@yeojongki 包区别不大，这里的实现是一样的。Taro Next 应该没有这个问题。

**Comment by yeojongki** [comment]
@Chen-jj ok 那就先这样吧，看看后续有没可能升级下 `Next` 版本我再反馈
