### ISSUE TITLE
Swiper在RN中的onChange方法没有回调

### ISSUE THREAD

**Issue by qindachang** [NervJS/taro#6269]
### 问题描述

当我使用Swiper组件在ReactNative中，手动滑动页面时，onChange、onAnimationFinish 方法没有回调。只有直接改变Swiper的current的值，才会产生回调。但是我希望手动滑动页面也能产生回调。

### 复现步骤

```javascript
  onChangeEventDetail = (e) => {
    console.log(e)
    const index = e.detail.current
    this.setState({
      currentTabIndex: index
    })
  }

...

<Swiper
          current={currentTabIndex}
          style={process.env.TARO_ENV !== 'rn' ? { height: this.paneHeight } : { }}
          onChange={this.onChangeEventDetail}
        >
          <SwiperItem>
            {/* 当前订单 */}
            <TabCurrentOrder />
          </SwiperItem>
          <SwiperItem>
            {/* 历史订单 */}
            <TabHistoryOrder />
          </SwiperItem>
        </Swiper>
```

### 期望行为

希望手动滑动页面也能产生回调。

### 系统信息

  Taro CLI 2.0.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.18.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.7 => 2.0.7 
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/components-rn: 2.0.7 => 2.0.7 
      @tarojs/mini-runner: 2.0.7 => 2.0.7 
      @tarojs/mobx: 2.0.7 => 2.0.7 
      @tarojs/mobx-h5: 2.0.7 => 2.0.7 
      @tarojs/mobx-rn: 2.0.7 => 2.0.7 
      @tarojs/plugin-less: 2.0.7 => 2.0.7 
      @tarojs/rn-runner: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-redux-rn: 2.0.7 => 2.0.7 
      @tarojs/taro-rn: 2.0.7 => 2.0.7 
      @tarojs/taro-router-rn: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: 16.11.0 => 16.11.0 
      react-native: ^0.62.0 => 0.62.2 
      stylelint-config-taro-rn: 2.0.7 => 2.0.7 
      stylelint-taro-rn: 2.0.7 => 2.0.7 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by fzzfxply** [comment]
同样遇到问题
