### ISSUE TITLE
如何监听路由变化？这个问题主要是针对h5端

### ISSUE THREAD

**Issue by DiaoMIngHero** [NervJS/taro#6270]
### 问题描述
需要在路由发生变化时进行某些操作，比如埋点时，每次路由发生变化时，进行数据上报。

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
如果只是 web 端，可以监听下 popstate 事件咯 [参考](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/popstate_event)

**Comment by yuuk** [comment]
```
eventCenter.on('__taroRouterChange', ({ fromLocation, toLocation }) => {});
```

**Comment by ctocto** [comment]
导入 eventCenter
```js
import Taro, { eventCenter } from '@tarojs/taro';
```
