### ISSUE TITLE
config里随便加个env变量打包能打10分钟

### ISSUE THREAD

**Issue by fred8617** [NervJS/taro#6271]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
？？？

**Comment by fred8617** [comment]
@luckyadam 
![image](https://user-images.githubusercontent.com/35049517/81462132-df1bd100-91e2-11ea-81cb-f659c6047583.png)
自从加了这个配置以后，不论是dev还是build都超级慢
3,0.0beta.5

**Comment by fred8617** [comment]
反复之后好很多，不知道是不是缓存的原因，先关了，复现再开
