### ISSUE TITLE
Taro 2.x 版本如何支持业务代码 tree shaking

### ISSUE THREAD

**Issue by derekwzd** [NervJS/taro#6275]
### 问题描述

Taro 2.x 版本无法支持业务代码 tree shaking

### 复现步骤

1. 配置 babel: `{presets: [["env", { modules: false }]]}`
2. 配置 webpack:   `mode: "production"`
3. 配置整个项目的 package.json : `"sideEffects": false`,
4. 在app.tsx 中引入一个 es 模块，模块为 math.js

```js
// math.js
export function add1 (x) {
    return x + 1111;
}

export function add2 (x) {
    return x + 2222;
}
```

```js
// app.tsx
import { add1 } from './math'
add1(999)
```

5. 最后在编译后的 app.js 依然以 umd 的形式引入并编译了 math.js，没有达到treeshaking 的效果
```js
 function(e, t, n) {
        "use strict";
        Object.defineProperty(t, "__esModule", { value: !0 }),
          (t.add1 = function add1(e) {
            return e + 1111;
          }),
          (t.add2 = function add2(e) {
            return e + 2222;
          });
      }
```
### 期望行为

期望能成功实现业务代码的 tree shaking 

### 报错信息

无报错信息

### 系统信息

Taro CLI 2.0.1 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.1 => 2.0.1 
      @tarojs/components-qa: 2.0.1 => 2.0.1 
      @tarojs/mini-runner: 2.0.1 => 2.0.1 
      @tarojs/redux: 2.0.1 => 2.0.1 
      @tarojs/redux-h5: 2.0.1 => 2.0.1 
      @tarojs/router: 2.0.1 => 2.0.1 
      @tarojs/taro: 2.0.1 => 2.0.1 
      @tarojs/taro-alipay: 2.0.1 => 2.0.1 
      @tarojs/taro-h5: 2.0.1 => 2.0.1 
      @tarojs/taro-qq: 2.0.1 => 2.0.1 
      @tarojs/taro-quickapp: 2.0.1 => 2.0.1 
      @tarojs/taro-swan: 2.0.1 => 2.0.1 
      @tarojs/taro-tt: 2.0.1 => 2.0.1 
      @tarojs/taro-weapp: 2.0.1 => 2.0.1 
      @tarojs/webpack-runner: 2.0.1 => 2.0.1 
      eslint-config-taro: 2.0.1 => 2.0.1 
      eslint-plugin-taro: 2.0.1 => 2.0.1 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.0.1 => 2.0.1 
      stylelint-taro-rn: 2.0.1 => 2.0.1

**Comment by HuJean** [comment]
@derekwzd 老哥，这个问题解决了吗？

**Comment by HuJean** [comment]
@luckyadam 请问现在taro2支持吗？是否一定需要升级到3

**Comment by Chen-jj** [comment]
@HuJean 支持

**Comment by HuJean** [comment]
> @HuJean 支持
和这位老哥一样的配置，是没有生效的，有哪里配置的不对吗？

**Comment by Chen-jj** [comment]
提供个 demo 看看咯

**Comment by HuJean** [comment]
sideEffects配置容易出错，改成了usedExports+@tarojs/plugin-terser的方案可以解决问题
