### ISSUE TITLE
Swiper H5 autoplay

### ISSUE THREAD

**Issue by Bravo123** [NervJS/taro#6277]
### 问题描述

swiper设置了autoplay属性，但是只能循环一遍，到了最后一个swiperItem之后就不动了。

### 期望行为

同微信小程序滚到最后一个之后会重新回到第一个swiperItme继续

### 系统信息

 Taro v1.3.16

  Taro CLI 1.3.16 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.2.3 => 2.2.3 
      @tarojs/cli: 2.2.3 => 2.2.3 
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/plugin-babel: 2.2.3 => 2.2.3 
      @tarojs/plugin-csso: 2.2.3 => 2.2.3 
      @tarojs/plugin-sass: 2.2.3 => 2.2.3 
      @tarojs/plugin-uglifyjs: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3 
    npmGlobalPackages:
      typescript: 3.6.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by psaren** [comment]
这问题是taro-ui的issue吧
提错地方了

**Comment by Bravo123** [comment]
> 这问题是taro-ui的issue吧
> 提错地方了

no

**Comment by astrocean** [comment]
这个停止滚动的原因是 `stopOnLastSlide: true`
https://github.com/NervJS/taro/blob/88c4fb083f974ff2279dbd78168a72f026de87dd/packages/taro-components/src/components/swiper/index.js#L116

而你直接把人家逻辑改了，导致了大家反馈的无法关闭循环的问题
