### ISSUE TITLE
Taro Next使用async await报错，Function() is not a function

### ISSUE THREAD

**Issue by fred8617** [NervJS/taro#6278]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by fred8617** [comment]
beta.5

**Comment by zsh3384027** [comment]
TypeError: Function(...) is not a function
    at Object.<anonymous> (vendors.js:2841)
    at Object.node_modulesRegeneratorRuntimeRuntimeJs (vendors.js:2844)
    at __webpack_require__ (runtime.js:80)
    at Object.node_modulesBabelRuntimeRegeneratorIndexJs (vendors.js:766)
    at __webpack_require__ (runtime.js:80)
    at

**Comment by dujuncheng** [comment]
同报错

**Comment by Chen-jj** [comment]
可以先配置一下 alias：

```js
alias: {
  'regenerator-runtime': path.resolve(__dirname, '../node_modules', 'regenerator-runtime'),
}
```

Taro Next 用了 babel7，@babel/runtime 使用的 regenerator-runtime 版本是 0.13，它又用了在小程序环境被 ban 了的  **Function** 函数。我们再讨论下怎么样指向 0.11 版本的 regenerator-runtime 包比较合理。

**Comment by chencs-19950208** [comment]
2.2.18 通样出现这个错误
