### ISSUE TITLE
taro next h5 page config enablePullDownRefresh 设为true,  Function components cannot be given refs

### ISSUE THREAD

**Issue by eiddie** [NervJS/taro#6280]
### 问题描述

`taro next` page config 设置`enablePullDownRefresh`为 `true`, 控制台直接报错

` Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

### 复现步骤
page config:

```ts
export default {
  enablePullDownRefresh: true
};

```

### 期望行为

不报错，下拉刷新正常

### 报错信息
![image](https://user-images.githubusercontent.com/62737990/81471198-1067c180-9222-11ea-8811-f2c86237d1e9.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@eiddie 复现不了，给个 demo 看看？

**Comment by eiddie** [comment]
> @eiddie 复现不了，给个 demo 看看？

- `taro beta5` 初始化项目， `React`, `Typescript`, `Sass`, `默认模版`

- 修改`pages/index`页面

```tsx
import React from 'react'
import { View } from '@tarojs/components'

const IndexPage: React.FC = () => {
  return (
    <View className="index">
      hello eid
    </View>
  )
}

export default IndexPage
```

```ts
export default {
  navigationBarTitleText: '首页',
  enablePullDownRefresh: true
}
```


- `yarn dev:h5`
