### ISSUE TITLE
[快应用]快应用是否支持mobx,报错 Store 'store' is not available! Make sure it is provided by some Provider

### ISSUE THREAD

**Issue by Fantasy9527** [NervJS/taro#6282]
### 问题描述

目前在快应用端使用mobx,报错 Store 'store' is not available! Make sure it is provided by some Provider

确认一下,在快应用下是否支持taro的mobx?

**Comment by nanjingboy** [comment]
与 https://github.com/NervJS/taro/issues/4248 重复了
