### ISSUE TITLE
Taro + vue + ts + vue-property-decorator 编译报错

### ISSUE THREAD

**Issue by sunxiuguo** [NervJS/taro#6287]
### 问题描述
Taro cli 3.0.0-beta.6

创建模板选择Vue  + ts + less + vuex

然后发现.vue文件内并没有使用ts版本，就修改为ts版本后，然后引入了vue-property-decorator，编译报错

```js
<template>
    <view>
        <input v-model="inputNumber" type="number" class="input" />
        <button @tap="addNumber">
            Add new number
        </button>
    </view>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component({})
export default class NumberSubmit extends Vue {
    inputNumber: number = 0;

    addNumber() {
        this.$store.dispatch("addNumber", Number(this.inputNumber));
    }
}
</script>

<style>
.input {
    border: 1px solid lightgray;
    margin: 10px;
}
</style>

```

### 期望行为

.vue文件可以正常使用ts，并且编译成功

### 报错信息

./src/components/NumberSubmit.vue?vue&type=script&lang=ts&)
Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/sunxiuguo/PrivateProject/HunterNote/src/components/NumberSubmit.vue: Unexpected token (15:15)

  13 | @Component({})
  14 | export default class NumberSubmit extends Vue {
> 15 |     inputNumber: number = 0;
     |                ^
  16 |
  17 |     addNumber() {
  18 |         this.$store.dispatch("addNumber", Number(this.inputNumber));

**Comment by sunxiuguo** [comment]
closed. 需要在webpackChain里配置vue-loader和ts-loader

**Comment by ll929** [comment]
@sunxiuguo 能把配置好的配置发出来看看吗

**Comment by ldwonday** [comment]
@sunhaikuo 如何配置？
![image](https://user-images.githubusercontent.com/4630157/82664189-c5a76a00-9c63-11ea-8684-125141e69a2d.png)怎么配置都报上面的错误！

**Comment by jiangxd2016** [comment]
@ldwonday 现在还会报错吗？我试了下，不报错，但是小程序的生命周期无法触发。

**Comment by QzhouZ** [comment]
Taro3+Vue2+vue-property-decorator 无法触发 onShow和onLoad生命周期，大家可以吗

```
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component({
  name: 'test'
})
export default class Webview extends Vue {

  // 正常执行
  mounted () {
    console.log(0)
  }

  // 不执行
  onShow () {
    console.log(1)
  }

  // 不执行
  onLoad (option) {
    console.log(option)
  }
}
</script>
```

**Comment by yaoshaohua** [comment]
> closed. 需要在webpackChain里配置vue-loader和ts-loader
请问大佬如何配置的？
