### ISSUE TITLE
Textarea maxlength属性h5端和微信小程序表现不一致

### ISSUE THREAD

**Issue by Bravo123** [NervJS/taro#6289]
### 问题描述
组合Emoji表情输入的时候，比如👨‍👨‍👧‍👧这种，.length属性值是11。
当设置了TextArea的maxlength为200的时候，微信小程序最多只能输入19个👨‍👨‍👧‍👧，
但是在H5上却可以输入很多个，

### 复现步骤
微信小程序的输入长度到209/200之后就不能在输入了
![alt 微信小程序](https://s1.ax1x.com/2020/05/11/YJPNSs.jpg)
https://s1.ax1x.com/2020/05/11/YJPNSs.jpg

h5的却一直能到2200/200
![alt H5](https://s1.ax1x.com/2020/05/11/YJPDTU.jpg)
https://s1.ax1x.com/2020/05/11/YJPDTU.jpg

### 期望行为

对标微信小程序

### 系统信息

Taro v1.3.16

  Taro CLI 1.3.16 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.2.3 => 2.2.3 
      @tarojs/cli: 2.2.3 => 2.2.3 
      @tarojs/components: 2.2.3 => 2.2.3 
      @tarojs/plugin-babel: 2.2.3 => 2.2.3 
      @tarojs/plugin-csso: 2.2.3 => 2.2.3 
      @tarojs/plugin-sass: 2.2.3 => 2.2.3 
      @tarojs/plugin-uglifyjs: 2.2.3 => 2.2.3 
      @tarojs/router: 2.2.3 => 2.2.3 
      @tarojs/taro: 2.2.3 => 2.2.3 
      @tarojs/taro-alipay: 2.2.3 => 2.2.3 
      @tarojs/taro-h5: 2.2.3 => 2.2.3 
      @tarojs/taro-qq: 2.2.3 => 2.2.3 
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3 
      @tarojs/taro-swan: 2.2.3 => 2.2.3 
      @tarojs/taro-tt: 2.2.3 => 2.2.3 
      @tarojs/taro-weapp: 2.2.3 => 2.2.3 
      @tarojs/webpack-runner: 2.2.3 => 2.2.3 
      eslint-config-taro: 2.2.3 => 2.2.3 
      eslint-plugin-taro: 2.2.3 => 2.2.3 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.2.3 => 2.2.3 
      stylelint-taro-rn: 2.2.3 => 2.2.3 
    npmGlobalPackages:

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
Taro 在浏览器端的 Textarea 组件直接使用的 textarea，maxLength 具体的表现也是由打开页面的浏览器内核决定的。

目前暂无规划对该特性跟进，如果你有好的方案欢迎提交 PR
