### ISSUE TITLE
[Taro3 beta6] 自定义 TabBar 会造成组件重复 key 警告

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#6297]
### 问题描述

使用 custom-tab-bar, 在切换 Tab 时因为每个页面都有一个 custom-tab-bar 实例, 会在切换的时候报警:

> Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s custom-tab-bar/index 
    in App (created by AppWrapper)
    in AppWrapper

### 复现步骤

只要是切换 custom-tab-bar 就会复现

```js
// src/custom-tab-bar/index.js

import React from 'react'
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

import appConfig from '../app.config'

export default () => {
    return (
        <View style={{ display: 'flex', alignItems: 'center', height: 50, textAlign: 'center' }}>
            {appConfig.tabBar?.list.map(({ pagePath, text }) => (
                <View key={text} style={{ flex: 1 }} onClick={() => Taro.switchTab({ url: '/' + pagePath })}>
                    {text}
                </View>
            ))}
        </View>
    )
}
```

```js
// src/app.config.js

export default {
    pages: [
        'pages/index',
        'pages/other',
    ],

    tabBar: {
        custom: true,
        list: [
            {
                pagePath: 'pages/index',
                text: '首页',
            },
            {
                pagePath: 'pages/other',
                text: '其他',
            },
        ],
    }
}
```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
可以做一个简单的复现 demo 吗

**Comment by hardywu** [comment]
3.0.0-rc.4 仍然有这问题
