### ISSUE TITLE
Taro有没有类似React的PureComponent类？

### ISSUE THREAD

**Issue by ldwonday** [NervJS/taro#630]
手动的去判断每个组件的shouldComponentUpdate比较累，也比较繁琐，有没有类似判断浅拷贝的方法？

**Comment by xioozq** [comment]
你难道没自己去试一下有没有这个？

**Comment by yuche** [comment]
有

**Comment by forconz** [comment]
Taro.PureComponent
https://nervjs.github.io/taro/docs/optimized-practice.html
