### ISSUE TITLE
百度, componentDidShow 方法内，redux通过@connect函数绑定方法，没有生效，到willMount才能生效

### ISSUE THREAD

**Issue by silencesdg** [NervJS/taro#6306]
### 问题描述

百度, componentDidShow 方法内，redux通过@connect函数绑定的方法，没有获取到，到willMount才能获取到

### 复现步骤

正常页面，componentDidShow方法内，都获取不到

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
import {  initCity } from '@actions/city'

@connect(state => ({ 
  ...state.home, 
}), {
  initCity
})
class Home extends Component {
   componentDidShow() {
      this.props.initCity()
  }
}
```

### 期望行为

在页面 componentDidShow 方法中能获取到 关联到props上的action函数

### 报错信息

index.js:163 Uncaught (in promise) TypeError: this.props.initCity is not a function
<img width="560" alt="屏幕快照 2020-05-13 上午11 42 02" src="https://user-images.githubusercontent.com/11205303/81769050-35548100-950f-11ea-9e10-201c77cae9ea.png">

### 系统信息

  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 1.3.37 => 1.3.37 
      @tarojs/components: 1.3.37 => 1.3.37 
      @tarojs/plugin-babel: 1.3.37 => 1.3.37 
      @tarojs/plugin-csso: 1.3.37 => 1.3.37 
      @tarojs/plugin-uglifyjs: 1.3.37 => 1.3.37 
      @tarojs/redux: 1.3.37 => 1.3.37 
      @tarojs/redux-h5: 1.3.37 => 1.3.37 
      @tarojs/router: 1.3.37 => 1.3.37 
      @tarojs/taro: 1.3.37 => 1.3.37 
      @tarojs/taro-alipay: 1.3.37 => 1.3.37 
      @tarojs/taro-h5: 1.3.37 => 1.3.37 
      @tarojs/taro-swan: 1.3.37 => 1.3.37 
      @tarojs/taro-tt: 1.3.37 => 1.3.37 
      @tarojs/taro-weapp: 1.3.37 => 1.3.37 
      @tarojs/webpack-runner: 1.3.37 => 1.3.37 
      eslint-config-taro: 1.3.37 => 1.3.37 
      eslint-plugin-taro: 1.3.37 => 1.3.37 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 1.3.37 => 1.3.37 
      stylelint-taro-rn: 1.3.37 => 1.3.37 
      taro-ui: ^2.2.4 => 2.3.4 

### 补充信息

redux的函数绑定过于滞后

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by DuanShuaiShuai** [comment]
请问这是是怎么解决的

**Comment by Chen-jj** [comment]
@silencesdg @DuanShuaiShuai 初次绑定 state 和 dispatch 到 props 是在 componentWillMount，也就是小程序的 onLoad。应该是百度 onShow 触发得比较早导致，兼容一下即可。
