### ISSUE TITLE
2.2.3版本dev:h5下修改文件代码自动编译经常会报错

### ISSUE THREAD

**Issue by hzcdt** [NervJS/taro#6308]
### 问题描述

2.2.3版本dev:h5下修改文件代码自动编译经常会报错，频率比较高，将版本讲到2.1.5后依然如此，不止我一个人出现这个问题，有两个开发其它h5应用的同事也经常出现这个问题

### 复现步骤
![image](https://user-images.githubusercontent.com/54352257/81782199-07ca0080-952c-11ea-8381-ee5c00a946c1.png)

**Comment by luckyadam** [comment]
把编辑器的某个保存编译插件关掉
