### ISSUE TITLE
Input组件maxLength无效，直接使用原生属性maxlength是可以的

### ISSUE THREAD

**Issue by 1035901787** [NervJS/taro#631]
**问题描述**
Input组件maxLength无效，直接使用原生属性maxlength是可以的

**复现步骤**
```js
<Input
                maxLength={1}
                password
              />
之后换成原生属性：

<Input
                maxlength='1'
                password
              />
```

**期望行为**

**报错信息**

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. v.1.0.0-beta.26]
 - Node.js 版本 [e.g. v10.7.0]

**补充信息**

**Comment by luckyadam** [comment]
统一用 maxLength 啦
