### ISSUE TITLE
[Taro Next Feature] 统一接口的多端文件 增加 file.taro.js 方便改写web组件支持 taro

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro#6316]
### 问题描述

目前，当一个组件运行在 `微信小程序` 或 `h5` 以及其他平台小程序，如果环境存在差异，可以使用 AtButton.**h5**.js 或 AtButton.**qq**.js ，以抹平差异，保持统一的结果。如文档中 [多端脚本逻辑](https://taro-docs.jd.com/taro/next/docs/envs.html#%E5%A4%9A%E7%AB%AF%E8%84%9A%E6%9C%AC%E9%80%BB%E8%BE%91)，这已经足以满足一个组件 多端小程序及h5 在`Taro`中运行。

自从有了 Taro 3 后，我们可以使用完整的 react ，我们可以尝试将现有的 web 端组件库（如：antd mobile），调整一些代码，以及使用 AtButton.weapp.js 多端文件，就能以很小的成本，使其支持 taro runtime。

重点来了：

* 假设 AtButton.js 组件，目前只支持web端，因为其中使用了 alert。
* 由于目前只开发微信小程序，所以复制 AtButton.js 重命名为 AtButton.weapp.js ，并将 alert 代码 改成 Taro.alert (打个比方)。
* 由于 Taro.alert 已经在`Taro 环境中`抹平了 小程序平台间的差异，我打算支持所有其他小程序平台，由于 xxx.weapp.js 只代表微信小程序时使用，所以我要复制 n 个文件，然后分别重命名, xxx.jd.js xxx.qq.js ... 尽管他们的代码内容一样，这样既不好看也不好维护。

所以：如果除了 AtButton.`h5`.js、AtButton.`weapp`.js、AtButton.`qq`.js 外，再增加一个 AtButton.**`taro`**.js， **`taro`** 代表运行在 taro 环境下时 使用此文件。

有朋友问，AtButton.js 不加后缀不就代表所有平台吗？这里说一下，主要前提是原本这个组件库是在 web 端（create-react-app、vue-cli 等脚手架），这些脚手架并不支持 AtButton.web.js，这种多端文件的方式，所以需要咱们思想境界更高的 taro 去兼容他们 😂

**Comment by Chen-jj** [comment]
@charmtiger 老哥可以提个 PR 到 [taro-rfc](https://github.com/NervJS/taro-rfcs) 哈

**Comment by charmtiger** [comment]
@Chen-jj  我学习一下 rfc 精神，然后发一下 😁

**Comment by cncolder** [comment]
taro 里小程序始终是一等公民.
我认为研究方向应该放在扩展 taro runtime 上面, 我尝试过在 taro3 里运行一些简单的 ui 库(例如 react-weui).
不支持的 api 应该尽可能完美 runtime 提供支持.
