### ISSUE TITLE
taro-sample-weapp 编译成功后微信开发者工具显示白屏并报错

### ISSUE THREAD

**Issue by mengjiang1994** [NervJS/taro#6318]
### 问题描述
taro-sample-weapp 编译成功后微信开发者工具显示白屏并报错

### 复现步骤
拉取至本地使用2.2.3版本taro  npm run dev:weapp 即可

### 期望行为

正常显示ECharts图表

### 报错信息

VM42:1 jsEnginScriptError
Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "npm/taro-ui/dist/weapp/components/button/index" (using by "pages/index/index")
    at q (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1632279)
    at q (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1632483)
    at http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1654432
    at Module.He (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1655011)
    at Function.value (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1745716)
    at xt (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1761975)
    at http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1766232
    at Mt (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1766725)
    at Function.<anonymous> (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1774830)
    at i.<anonymous> (http://127.0.0.1:16763/appservice/__dev__/WAService.js:2:1738454)

### 系统信息

  Taro CLI 2.2.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3
      @tarojs/mini-runner: 2.2.3 => 2.2.3
      @tarojs/plugin-babel: 2.2.3 => 2.2.3
      @tarojs/plugin-csso: 2.2.3 => 2.2.3
      @tarojs/plugin-sass: 2.2.3 => 2.2.3
      @tarojs/plugin-uglifyjs: 2.2.3 => 2.2.3
      @tarojs/router: 2.2.3 => 2.2.3
      @tarojs/taro: 2.2.3 => 2.2.3
      @tarojs/taro-h5: 2.2.3 => 2.2.3
      @tarojs/taro-weapp: 2.2.3 => 2.2.3
      @tarojs/webpack-runner: 2.2.3 => 2.2.3
      eslint-config-taro: 2.2.3 => 2.2.3
      eslint-plugin-taro: 2.2.3 => 2.2.3
      nervjs: ^1.5.6 => 1.5.6
      taro-ui: ^1.1.5 => 1.5.4

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-sample-weapp/commit/ad1a141659345e067672b80b0890c376cd8091c5
项目依赖已经统一升级到 2.2.4，可以用 2.2.4 版本试试

**Comment by haoyinag** [comment]
@luckyadam @Chen-jj 还是不行，只要使用了taro-ui就会报这个错
```bash
"dependencies": {
    "@tarojs/components": "2.2.4",
    "@tarojs/components-qa": "2.2.4",
    "@tarojs/redux": "2.2.4",
    "@tarojs/redux-h5": "2.2.4",
    "@tarojs/router": "2.2.4",
    "@tarojs/taro": "2.2.4",
    "@tarojs/taro-alipay": "2.2.4",
    "@tarojs/taro-h5": "2.2.4",
    "@tarojs/taro-qq": "2.2.4",
    "@tarojs/taro-quickapp": "2.2.4",
    "@tarojs/taro-swan": "2.2.4",
    "@tarojs/taro-tt": "2.2.4",
    "@tarojs/taro-weapp": "2.2.4",
    "babel-runtime": "^6.26.0",
    "nervjs": "^1.5.5",
    "taro-ui": "^2.3.4",
    "nerv-devtools": "^1.5.5",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "regenerator-runtime": "0.11.1"
  },
  "devDependencies": {
    "@types/react": "^16.4.8",
    "@types/webpack-env": "^1.13.6",
    "@tarojs/mini-runner": "2.2.4",
    "@tarojs/webpack-runner": "2.2.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-jsx-stylesheet": "^0.6.5",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^5.16.0",
    "eslint-config-taro": "2.2.4",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "eslint-plugin-import": "^2.12.0",
    "stylelint": "9.3.0",
    "stylelint-config-taro-rn": "2.2.4",
    "stylelint-taro-rn": "2.2.4",
    "eslint-plugin-taro": "2.2.4",
    "@typescript-eslint/eslint-plugin": "^2.13.0",
    "@typescript-eslint/parser": "^2.13.0",
    "typescript": "^3.0.1"
  }
```
