### ISSUE TITLE
将Taro cli升级到Taro v1.0.0-beta.28测试项目报错！！！！

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#632]
今天将Taro cli从Taro v1.0.0-beta.24升级到Taro v1.0.0-beta.28后，小程序端dev报错！
报错信息如下：
<img width="783" alt="2018-09-17 5 39 53" src="https://user-images.githubusercontent.com/29066081/45616006-bc362980-baa0-11e8-94c1-371f48782d82.png">
先一直认为是测试代码的问题！
后来将代码在Taro v1.0.0-beta.24环境下运行后，小程序页面正常显示。
请问有什么方法解决！急！

**Comment by jiangzeyin** [comment]
![image](https://user-images.githubusercontent.com/16408873/45616257-77f75900-baa1-11e8-842d-a128a055b657.png)
小程序开发工具控制显示如下信息

**Comment by zhou1992zg** [comment]
问题在今天下午升级Taro v1.0.0-beta.29版本解决。
