### ISSUE TITLE
Canvas新版API TS类型问题

### ISSUE THREAD

**Issue by piecego** [NervJS/taro#6320]
### 问题描述

1. `canvasToTempFilePath`中的`canvas`属性不应该是`CanvasProps`而是`Taro.Canvas`

2. `taro/types/api/canvas/index.d.ts`中`interface Canvas`缺少以下属性

```typescript
interface Canvas{
  width: number
  height: number
  toDataURL(type: string, encoderOptions: number): string
  createPath2D(path: Path2D): Path2D
}
```
    
[参考文档 https://developers.weixin.qq.com/miniprogram/dev/api/canvas/Canvas.html](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/Canvas.html)

### 系统信息

- TaroJS Version: 2.2.2

### 补充信息

`createPath2D`属性类型可能不正确

**Comment by ZakaryCode** [comment]
可以试试，提个 PR？

**Comment by piecego** [comment]
> 可以试试，提个 PR？

不大熟悉流程，提交了一个pr #6352
