### ISSUE TITLE
怎样在开发时启用lintOnSave

### ISSUE THREAD

**Issue by GDCPedro** [NervJS/taro#6324]
### 问题描述

请问怎样启用按下ctrl + s时自动格式化代码

### 复现步骤

启动任意Taro项目，开始开发

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

可以在ctrl + s的时候自动格式化代码

### 系统信息

System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3
      @tarojs/components-qa: 2.2.3 => 2.2.3
      @tarojs/mini-runner: 2.2.3 => 2.2.3
      @tarojs/router: 2.2.3 => 2.2.3
      @tarojs/taro: 2.2.3 => 2.2.3
      @tarojs/taro-alipay: 2.2.3 => 2.2.3
      @tarojs/taro-h5: 2.2.3 => 2.2.3
      @tarojs/taro-qq: 2.2.3 => 2.2.3
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3
      @tarojs/taro-swan: 2.2.3 => 2.2.3
      @tarojs/taro-tt: 2.2.3 => 2.2.3
      @tarojs/taro-weapp: 2.2.3 => 2.2.3
      @tarojs/webpack-runner: 2.2.3 => 2.2.3
      eslint-config-taro: 2.2.3 => 2.2.3
      eslint-plugin-taro: 2.2.3 => 2.2.3
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6

### 补充信息

谢谢大家

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
这是你编辑器的配置，可以直接在 google 搜索：「'editor' prettier on save」，把 'editor' 换成你编辑器的名字
