### ISSUE TITLE
taro next 3.0.0-beta.6版本   编译打包后放在服务器上报错   Route not found

### ISSUE THREAD

**Issue by jsLyLeeHi** [NervJS/taro#6325]
### 问题描述

taro next 3.0.0-beta.6版本 
在本地预览时报错regeneratorRuntime isnot defind，
我修改了
node_modules\_@tarojs_webpack-runner@3.0.0-beta.6@@tarojs\webpack-runner\dist\util\chain.js
中到代码
```js
rule.script = {
        test: runner_utils_1.REG_SCRIPTS,
        // exclude: [filename => /node_modules/.test(filename)],
        exclude: [filename => /@tarojs\/components/.test(filename) || (/node_modules/.test(filename) && !(/taro/.test(filename)))],
        use: {
            babelLoader: getBabelLoader([{
                    compact: false
                }])
        }
    };
```
这样本地编译预览成功了  

我在完成h5端开发之后打包编译到服务器    放到服务器上报错
Uncaught (in promise) Error: Route not found
    at next (app.js:2)
    at app.js:2

### 复现步骤

1. 新建一个taro next 3.0.0-beta.6版本 项目
2. 修改
node_modules\_@tarojs_webpack-runner@3.0.0-beta.6@@tarojs\webpack-runner\dist\util\chain.js
中的代码
```js
rule.script = {
        test: runner_utils_1.REG_SCRIPTS,
        // exclude: [filename => /node_modules/.test(filename)],
        exclude: [filename => /@tarojs\/components/.test(filename) || (/node_modules/.test(filename) && !(/taro/.test(filename)))],
        use: {
            babelLoader: getBabelLoader([{
                    compact: false
                }])
        }
    };
```
3.打包编译后放到服务器运行

```

### 期望行为
期望服务器端正常运行

### 报错信息
Uncaught (in promise) Error: Route not found
    at next (app.js:2)
    at app.js:2

### 系统信息
 Taro CLI 3.0.0-beta.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD

**Comment by Chen-jj** [comment]
@jsLyLeeHi 本地打出 dist 后放服务器，在运行时报错？

**Comment by jsLyLeeHi** [comment]
> @jsLyleeHi本地打出Dist后放服务器，在运行时报错？

是的  你可以根据复现试试  而且我发现图片image组件的也会在使用时莫名其妙的报错   mode.toLowerCase()  is not a function

**Comment by Chen-jj** [comment]
@jsLyLeeHi 额不太科学，代码都是一样的话估计还是你环境问题

**Comment by yuche** [comment]
你打包到服务器是不是用的生产模式

**Comment by jsLyLeeHi** [comment]
> @jsLyLeeHi 额不太科学，代码都是一样的话估计还是你环境问题
新建一个3.0.beta6的新项目    和一个2.0+的新项目
然后你分别打包到H5,   放到本地的根目录下  你会发现2.0+的项目运行没问题     3.0+的项目出现route not find

**Comment by Chen-jj** [comment]
@jsLyLeeHi 新建 taro 项目 -> build production-> http-server ./dist。复现了一次，后来把相关的 taro 包重新 build 后就没有复现了，可以在下个版本再试试。

**Comment by jsLyLeeHi** [comment]
> @jsLyLeeHi 新建 taro 项目 -> build production-> http-server ./dist。复现了一次，后来把相关的 taro 包重新 build 后就没有复现了，可以在下个版本再试试。

下个版本什么时候发呢

**Comment by Chen-jj** [comment]
@jsLyLeeHi 右边有打 Milestone，里面的 issues 都好了就会发的，大概今天或下周一。

**Comment by hillmychen** [comment]
请问怎么解决的

**Comment by TechQuery** [comment]
不知是不是和 `publicPath` 设置有关 #6919
