### ISSUE TITLE
Image组件同时设置showMenuByLongpress与onClick,在真机环境下，长按时依然会触发click回掉

### ISSUE THREAD

**Issue by IWSR** [NervJS/taro#6330]
### 问题描述

Image组件同时设置showMenuByLongpress与onClick,在真机环境下，长按时依然会触发click回掉

### 复现步骤

1. 开发者工具未复现，真机环境下长按设置showMenuByLongpress的Image元素后，会先出现menu菜单，随后触发click回掉

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
`<Image mode='widthFix' src={image} style={imageStyle} showMenuByLongpress data-image={image} onClick={this.previewImage} />`


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@IWSR 可以测试一下原生组件有没这个问题
