### ISSUE TITLE
云开发时，云函数使用index.ts，导致在开发工具上传云函数失败

### ISSUE THREAD

**Issue by GDCPedro** [NervJS/taro#6333]
### 问题描述

微信云开发，云函数使用ts时，在微信开发工具上传云函数失败。

### 复现步骤

1. 在cloud/functions目录下新建一个云函数的文件夹
2. 在该云函数文件夹下新建index.ts
3. 创建package.json, tsconfig.json等必须文件，npm install下载wx-erver-sdk等包
4. 书写完成云函数，然后在微信开发工具点击“上传云函数”，会提示上传失败

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

使用ts开发云函数

### 报错信息

上传云函数失败

### 系统信息

System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.3 => 2.2.3
      @tarojs/components-qa: 2.2.3 => 2.2.3
      @tarojs/mini-runner: 2.2.3 => 2.2.3
      @tarojs/router: 2.2.3 => 2.2.3
      @tarojs/taro: 2.2.3 => 2.2.3
      @tarojs/taro-alipay: 2.2.3 => 2.2.3
      @tarojs/taro-h5: 2.2.3 => 2.2.3
      @tarojs/taro-qq: 2.2.3 => 2.2.3
      @tarojs/taro-quickapp: 2.2.3 => 2.2.3
      @tarojs/taro-swan: 2.2.3 => 2.2.3
      @tarojs/taro-tt: 2.2.3 => 2.2.3
      @tarojs/taro-weapp: 2.2.3 => 2.2.3
      @tarojs/webpack-runner: 2.2.3 => 2.2.3
      eslint-config-taro: 2.2.3 => 2.2.3
      eslint-plugin-taro: 2.2.3 => 2.2.3
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6

### 补充信息

谢谢各位大佬解惑、祝大家工作顺利、家庭幸福、身体健康！

**Comment by shenghanqin** [comment]
@GDCPedro 云函数其实是nodejs环境，而nodejs想使用ts，就需要配置编译一下ts成js版本才可以。这个问题你可以到微信小程序社区去问问看。
