### ISSUE TITLE
2.2.4小程序端 Function(...) is not a function

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#6341]
![微信截图_20200514234108](https://user-images.githubusercontent.com/31879769/81955305-80b87d80-963c-11ea-8b9b-9ea54da42644.png)
![Uploading 微信截图_20200514234144.png…]()

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/migrate-to-2#%E4%BD%BF%E7%94%A8-asyncawait-%E6%97%B6%E5%87%BA%E7%8E%B0%E6%8A%A5%E9%94%99-function-is-not-a-function

**Comment by freeler** [comment]
链接失效了，请问如何解决的

**Comment by freeler** [comment]
@luckyadam 链接失效了，请问如何解决的
