### ISSUE TITLE
因为beta6的h5不可用，尝试自己编译next。运行 npm run build，出现错误semantic error TS2307: Cannot find module '@tarojs/taro'.

### ISSUE THREAD

**Issue by jimtang9527** [NervJS/taro#6342]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

希望能自己编译最新的cli
<img width="1214" alt="截屏2020-05-15 上午9 58 23" src="https://user-images.githubusercontent.com/7098183/82003401-dc155a80-9692-11ea-8edb-0f5b43373ad6.png">

### 系统信息

jim@666 taro % taro info
👽 Taro v3.0.0-beta.6

  Taro CLI 3.0.0-beta.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.20.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      nervjs: ^1.4.6 => 1.5.6 
      react: ^16.10.2 => 16.13.1 
      react-native: ^0.61.2 => 0.61.5 
    npmGlobalPackages:
      typescript: 3.9.2

jim@666 taro % 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
same issue #6274
