### ISSUE TITLE
如何在index.html注入变量 比如测试环境 预发环境

### ISSUE THREAD

**Issue by singlehcc** [NervJS/taro#6343]
### 问题描述
想要在h5模式下测试环境和预发环境添加vconsole 但在线上环境不需要
`<div id="app"></div>
  <script>
    (function() {
      const script = document.createElement('script')
      script.src = 'https://cdn.bootcss.com/vConsole/3.2.2/vconsole.min.js'
      document.body.appendChild(script)
      script.onload = function () {
        var vConsole = new VConsole();
      }
    })()
  </script>`

**Comment by singlehcc** [comment]
help

**Comment by Chen-jj** [comment]
http://taro-docs-in.jd.com/taro/next/docs/next/config-detail.html#defineconstants

**Comment by ReggieCai31** [comment]
defineConstants里面定义一个TEST变量，index.html里面使用·<%= TEST %>·这样就行
