### ISSUE TITLE
h5：Taro.chooseImage({sourceType:['album']}),sourceType属性不起作用

### ISSUE THREAD

**Issue by mysky621** [NervJS/taro#6347]
### 问题描述

Taro.chooseImage({count:1, sourceType: ['camera','album']})}
h5下：sourceType属性不起作用。
一、华为p10，微信版本7.0.14
	1.不传参，能拍照和从相册选择
	2.传camera参数，只能拍照
	3.传album参数，能拍照和从相册选择
二、OPPO R9sPlus，微信版本7.0.14
	1.不传参，只能从相册选择
	2.传camera参数，能拍照和从相册选择
	3.传album参数，只能从相册选择
三、一加6，微信版本7.0.14
	1.不传参，只能从相册选择
	2.传camera参数，能拍照和从相册选择
	3.传album参数，只能从相册选择
四、苹果6plus，微信版本7.0.14
	1.不传参，能拍照和从相册选择
	2.传camera参数，只能拍照
	3.传album参数，能拍照和从相册选择
五、红米，微信版本7.0.14
	1.不传参，只能从相册选择
	2.传camera参数，能拍照和从相册选择
	3.传album参数，只能从相册选择

### 复现步骤

1.页面上在按钮上加一个点击事件，调去Taro.chooseImage()
2.然后切换sourceType类型，看效果。

### 期望行为

期望sourceType能起作用，设置什么就是什么。

### 系统信息
Taro CLI 2.2.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - C:\Users\86186\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by ZakaryCode** [comment]
这些是 H5 的局限性导致的，根据不同手机厂商具体的配置会有不同，目前没有什么比较好的解决方法
