### ISSUE TITLE
taro2.2.3,NODE_ENV=production watch模式下无法压缩

### ISSUE THREAD

**Issue by tianleiwufeng** [NervJS/taro#6353]
### 问题描述
taro2.2.3,NODE_ENV=production watch模式下无法压缩
修改node_modules中代码后，可以压缩，但是编译太慢。

### 复现步骤

"build:weapp-compress": "cross-env NODE_ENV=production taro build --type weapp --env sat",
    "dev:weapp-compress": "concurrently \"npm run mock\" \"npm run build:weapp-compress -- --watch\"",
因为主包太大，所以watch模式需要压缩才能用预览。用2.2.3后，代码仍是未压缩版本

找到源码
![1589549392(1)](https://user-images.githubusercontent.com/13955666/82113791-47daee80-978b-11ea-94f4-b3d9a92f3471.png)

将其改为production模式后，可以压缩。

但是问题来了，保存一次代码会将全部代码进行打包压缩，需要一分钟左右。忍痛切回了1.3.x版本，麻烦官方修复一下

### 系统信息
Taro v1.3.42

切回了1.3.42版本。。
  Taro CLI 1.3.42 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.14.2 - D:\nodejs\node.EXE
      Yarn: 1.17.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - D:\nodejs\npm.CMD

**Comment by DrakeXiang** [comment]
蹲一个更好的解决方案，我升级到2.2.3之后也是这个问题，现在是单独配置了一个预览的命令，development环境下的压缩，平时开发还是在watch下
