### ISSUE TITLE
taro 有 使用css variable 或者 less variable的解决方案吗

### ISSUE THREAD

**Issue by IFmiss** [NervJS/taro#6354]
### 问题描述

我尝试 css 变量 好像不起作用
less 变量 我也没有查到相关文档
我想在 val.less中定义 less 变量 或者 css 变量，希望能在其他的less文件中直接使用到这些变量，有什么方式吗

**Comment by IFmiss** [comment]
因为我使用了 css-modules 导致我 css 变量没没法正常使用，现在OK了

**Comment by guxinyan** [comment]
我也想咨询下，有less 全局常量配置方法吗

**Comment by IseeUDenis** [comment]
现在也没办法使用，请问是怎么解决的

**Comment by myNameCao** [comment]
我也遇到相同的问题，请问 怎么解决了
