### ISSUE TITLE
Button的onenType为openSetting时，回调没有执行

### ISSUE THREAD

**Issue by Qukoko** [NervJS/taro#636]
**问题描述**
openType为openSetting的Button，点击之后能跳到授权设置页，但是设置完返回之后没有执行回调

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
<Button openType='openSetting' className='btn-content' onOpenSetting={this.onOpenSetting}>
        <Text>请在授权设置页允许获取通讯地址</Text>
        <Image src={toAddress} className='toaddress' />
</Button>
```

**期望行为**
授权之后能执行回调

**报错信息**

没有报错

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.73]
 - Node.js 版本 [e.g. v9.0.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zw130633** [comment]
我也遇到了同样的问题，请问最后是怎么解决的

**Comment by luckyadam** [comment]
@zw130633 taro 版本多少

**Comment by zw130633** [comment]
@luckyadam taro 版本 1.1.4，问题解决了。我把 Button 父组件的 onClick 事件去掉以后，onOpenSetting 就可以执行了

**Comment by zw130633** [comment]
@luckyadam 包括 Button 自身如果同时写有 onClick 和 onOpenSetting 事件时，onOpenSetting 也不会执行，但是在原生框架里是可以这样写的。我现在就需要这样一个场景，Button 是一个弹窗的确定按钮，我希望弹出设置页面的同时关闭弹窗，该如何解决？

**Comment by zw130633** [comment]
@luckyadam 这个问题还能解决吗？关于onClick 和 onOpenSetting同时执行互不影响的问题。当Button父容器有 click事件的时候，onOpenSetting也不会执行

**Comment by zw130633** [comment]
期望能在弹出设置页面的同时关闭弹窗，而不是从设置页返回的时候再关闭

**Comment by luckyadam** [comment]
@zw130633 原生写法是可以的么？ 你可以看看 Taro 编译后的代码，就是原生代码的

**Comment by luckyadam** [comment]
好嘞~
