### ISSUE TITLE
taro init项目时，选择redux模板，创建失败

### ISSUE THREAD

**Issue by daiwenyu** [NervJS/taro#6365]
### 问题描述
taro init项目时，选择redux模板，创建失败。
选择默认模板可正常创建

### 复现步骤

1. taro init weapp
2. 选择redux模板
3. JSON解析失败

### 期望行为

正常创建redux模板

### 报错信息

![image](https://user-images.githubusercontent.com/16659386/82182361-c3b57200-9916-11ea-9adc-d5f926396847.png)

### 系统信息
Taro v2.2.4
npm v6.14.5
node v12.16.3
操作系统 win10

**Comment by luckyadam** [comment]
rm -rf ~/.taro2
然后再重试一下

**Comment by daiwenyu** [comment]
@luckyadam 方法可行，谢谢
