### ISSUE TITLE
api 引入的路径不对 报错误是页面没有注册

### ISSUE THREAD

**Issue by 986244073** [NervJS/taro#6369]
### 问题描述
页面注册了 api 引入的路径不对 报错误是页面没有注册

### 复现步骤
这样引入的
```js
import { apiIndexRecommend } from 'api/index';
```
报的错误
![image](https://user-images.githubusercontent.com/16508677/82197340-785a8e00-992d-11ea-9690-cbe2a2bf9426.png)

### 期望行为
希望改善错误提示

### 系统信息
taro 2.24

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by 986244073** [comment]
正确的引入
```js
import { apiIndexRecommend } from '../../api/index';
```

**Comment by Chen-jj** [comment]
@986244073 这句是小程序开发者工具自己报的。你这个错误在 webpack 打包 resolve 阶段就会报，cli 会打印找不到对应文件的错误。
