### ISSUE TITLE
taro next 怎么获取路由参数？

### ISSUE THREAD

**Issue by tim0991** [NervJS/taro#6370]
**问题描述**
使用vue构建项目，当用navigate跳转之时Url上设置了?action=active参数，请问怎么在page中获得？
2.x文档中提到要使用$router获取，但是this上找不到相关属性

**复现步骤**

```js
// 这里可以贴代码
```

**期望行为**

**报错信息**

**系统信息**

**补充信息**

**Comment by yuche** [comment]
https://nervjs.github.io/taro/docs/3.0.0-beta.5/migration/#%E8%B7%AF%E7%94%B1
