### ISSUE TITLE
点击 上层元素中  下层Textarea 聚焦 

### ISSUE THREAD

**Issue by myNameCao** [NervJS/taro#6380]
### 复现步骤

1. 在ios  手机中才有的现象    上层元素 是一个弹框   弹框 下面 有一个Textarea元素
2. 点击 弹框中的元素    下层Textarea  会自动聚焦
3. 上层元素 好像是 点击事件穿透 引起
4. 在上层元素添加 stopPropagation  不管用

弹框代码如下
```js 

function RefundBox ({close,sureRefund,showOpened}){
  const handleBgMove = (e) => { e.stopPropagation(); return false; };
  function getCoupon(e){
    e.stopPropagation()
    close&&close()
    ajax({
      url:'oneReceiveCoupon',
      success(res){
         console.log(res)
         showOpened&&showOpened()
      }
    })
  }
  return (<View className='shadow'>
    <View className='RefundBox'  >
      <View className='action_bar' >
         <View className='left_btn'  onTouchMove={handleBgMove} onClick={()=>{sureRefund&&sureRefund()}} >继续退款</View>
         <View className='right_btn'  onTouchMove={handleBgMove} onClick={getCoupon}  >领取</View>
      </View>
    </View>
  </View>)
}

```

### 期望行为
点击 上层的弹框 下面的Textarea  不自动聚焦
### 系统信息
  System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.0.6 => 2.0.6 
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/plugin-babel: 2.0.6 => 2.0.6 
      @tarojs/plugin-csso: 2.0.6 => 2.0.6 
      @tarojs/plugin-less: 2.0.6 => 2.0.6 
      @tarojs/plugin-sass: 2.0.6 => 2.0.6 
      @tarojs/plugin-uglifyjs: 2.0.6 => 2.0.6 
      @tarojs/redux: 2.0.6 => 2.0.6 
      @tarojs/redux-h5: 2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/taro-swan: 2.0.6 => 2.0.6 
      @tarojs/taro-tt: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 

### 补充信息
![lALPGp4a6WSLcWzNA2zNAlg_600_876 png_720x720g](https://user-images.githubusercontent.com/23721492/82274438-be0d6a00-99b2-11ea-8ea1-e7cbac71e129.jpg)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@myNameCao Taro 2 里面回调函数中调用 `e.stopPropagation()` 原理，是把对应的事件在小程序的 xml 中从 **bind** 绑定变成 **catch** 绑定。

例如 onTouchStart，一般会编译成 bindTouchStart，如果在回调中调用 e.stopPropagation()，就会变成 catchTouchStart。

所以 e.stopPropagation() 是否生效，你看看编译后的 xml，对应的位置是否是 catch 事件绑定即可。

至于你的问题应该是支付宝原生就有的，你可以试试 catchTouchStart、catchTap。

**Comment by myNameCao** [comment]
@Chen-jj  感谢您的回答，我的意思 是 无论在 onTouchStart  或者  onTouchMove   中 执行 的 阻止冒泡  都没有起作用
