### ISSUE TITLE
[Taro next] 遍历MovableView，删除中间某项，表现不符预期

### ISSUE THREAD

**Issue by myl0204** [NervJS/taro#6382]
### 问题描述
数组map MovableView，执行删除操作时，被删除项之后的MovableView会从被删除项的位置移动到期望位置。

### 复现步骤

1. 点击删除第一个，第二、第三项会有不符预期的移动；点击删除第二个，第三项会有不符预期的移动
2. 依次点击删除第三个，第二个，都不会发生移动
3. 
4. 

```js
import React, { Component } from "react";
import { View, Text, MovableArea, MovableView } from "@tarojs/components";
import "./index.scss";

const initList = [
  {
    x: 100,
    y: 100,
    text: "我是第一个",
    key: "1"
  },
  {
    x: 150,
    y: 150,
    text: "我是第二个",
    key: "2"
  },
  {
    x: 200,
    y: 200,
    text: "我是第三个",
    key: "3"
  }
];

export default class Index extends Component {
  state = {
    list: [...initList]
  };

  reset = () => {
    this.setState({ list: [...initList] });
  };

  delItem = (key = "1") => {
    this.setState(state => ({
      list: state.list.reduce((prev, cur) => {
        if (cur.key !== key) {
          prev.push({ ...cur });
        }
        return prev;
      }, [])
    }));
  };

  render() {
    return (
      <View className="index">
        <MovableArea style={{ width: "300px", height: "300px" }}>
          {this.state.list.map(m => (
            <MovableView
              direction="all"
              key={m.key}
              x={m.x}
              y={m.y}
              style={{ width: "100px", height: "100px" }}
            >
              {`${m.text}我的位置是x:${m.x}y:${m.y}`}
            </MovableView>
          ))}
        </MovableArea>

        <View onClick={() => this.delItem("1")}>删除第一项</View>
        <View onClick={() => this.delItem("2")}>删除第二项</View>
        <View onClick={() => this.delItem("3")}>删除第三项</View>
        <View onClick={this.reset}>重置</View>
      </View>
    );
  }
}

```

### 期望行为

删除中间项时，后面的MovableView不会发生位移
### 系统信息

Taro CLI 2.1.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/components: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/mini-runner: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/taro: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/webpack-runner: 3.0.0-rc.0 => 3.0.0-rc.0
      eslint-config-taro: 3.0.0-rc.0 => 3.0.0-rc.0
      react: ^16.10.0 => 16.13.1
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
现在的代码没能看懂应该怎么移动是对的，要求只有一项：
```
删除中间项时，后面的MovableView不会发生位移
```
这点吗

**Comment by myl0204** [comment]
> 现在的代码没能看懂应该怎么移动是对的，要求只有一项：
> 
> ```
> 删除中间项时，后面的MovableView不会发生位移
> ```
> 
> 这点吗

是的。我的逻辑只是删除某一项，出现任何移动的现象都是期望之外的。

**Comment by Chen-jj** [comment]
@myl0204 

问题在于 `MovableView` 是非受控组件。当它移动时，x、y 属性值还是保持初始值不变。

当删除操作或其它操作导致列表中 `MovableView` 重新渲染时，会使用初始的 x、y 值去 setData，从而导致期望之外的移动。

因此我们需要保持 `MovableView` 移动时，同时**更新 x、y 的值为当前值**。

如：

```js
handleChange (key, e) {
    // 更新 x、y 值
}

<MovableView
  x={m.x}
  y={m.y}
  onChange={this.handleChange.bind(this, m.key)}
/>
```

如果每次 `onChange` 都触发 `setState` 会导致卡顿，可以把 `onChange` 的 x、y 保存下来，在 `onTouchEnd` 时再更新最新的值。
