### ISSUE TITLE
Taro教程 | 路由功能：<导航>链接失效

### ISSUE THREAD

**Issue by CiciMa** [NervJS/taro#6384]
# 问题描述
进入 【https://nervjs.github.io/taro/docs/router】 
->查找 【具体 API 说明，请查看<导航>部分说明】 
-> 点击【<导航>】
-> 进入 【https://nervjs.github.io/taro/docs/apis/interface/navigation/navigateTo】
-> 显示404 error 页面不存在

# 需求
- 请更新页面【https://nervjs.github.io/taro/docs/apis/interface/navigation/navigateTo】
- 不会显示404 error

**Comment by ZakaryCode** [comment]
搜索有点问题，可以直接在侧边栏点击查看，地址应该是这一个 https://nervjs.github.io/taro/docs/apis/route/navigateTo
