### ISSUE TITLE
`h5.router.customRoutes`的配置使用问题

### ISSUE THREAD

**Issue by yahveh** [NervJS/taro#6388]
### 问题描述

`h5.router.customRoutes`的配置使用问题

### 复现步骤

0. 修改 `taro-cli`:  `***global\node_modules\@tarojs\cli\dist\doctor\configSchema.js`

```
    h5: Joi.object().keys({
	    ...
		router: Joi.object() // 添加了
	})
```

如果这里不修改, 启动时会提示 
```
Taro 配置有误，请检查！ (***project\config\index.js)
  [✗] h5.router "h5.router" is not allowed
```

---

1. 设置 `config/index.js`

```js
h5: {
...
    router: {
        customRoutes: {
            '/pages/home/index': '/home',
            '/pages/user/index': '/user',
        }
    }
}
```

2. 设置`src/app.h5`

```js
  config: Config = {
    pages: [
        'pages/user/index',
        'pages/home/index',
    ],
    ...
    tabBar: {
        list: [
          {
            pagePath: 'pages/home/index',
            text: '首页',
          },
          {
            pagePath: 'pages/user/index',
            text: '我的',
          },
        ]
    }
```

3. `yarn dev:h5`运行, 弹出默认页面 `http://{localhost:port}`, 正常显示`user`的内容
4. 点击页面底部任意tab,浏览地址变为 `http://{localhost:port}/#/home` 或者 `http://{localhost:port}/#/user` , 除了底部tabbar, 页面空白（页面元素 class="taro_page" style="min-height: 100%;display: none;"）, 但是可以观察到对应页面的数据交互
5. 接上一步刷新页面, 正常显示, 点击tab也正常

### 期望行为

h5下正常设置并使用`h5.router.customRoutes`，页面打开正常

### 系统信息

```
Taro CLI 2.2.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 13.13.0
      Yarn: 1.22.4
      npm: 6.14.4 
```

### 补充信息

看文档是`h5.router.customRoutes`的，比较奇怪，是目前仅尝试修改了`复现步骤0`以此让我可运行这个配置。

**Comment by luckyadam** [comment]
2.2.6 修复了这个问题，请升级试试~

**Comment by yahveh** [comment]
@luckyadam 复现步骤3和4问题依旧

**Comment by meow4world** [comment]
步骤3和4问题从2.x版本到现在一直有，不知何时能修复

**Comment by tuoxie15** [comment]
这个问题无解了吗？是不是没有人用Taro做H5端？

**Comment by jimizai** [comment]
升级v2.2.7以后 页面卡死  然后降到v2.2.2 解决卡死问题

**Comment by jerrylu0522** [comment]
2.x H5一直都有这个问题，从未解决。

**Comment by jerrylu0522** [comment]
2.2.10测试依旧存在，在redirectTo、reLaunch、switchTab均会出现。

**Comment by baobin77** [comment]
router.customRoutes 支持正则匹配参数吗？做伪静态用

**Comment by ZakaryCode** [comment]
> router.customRoutes 支持正则匹配参数吗？做伪静态用

不支持
