### ISSUE TITLE
【求助】请问如何配置 lodash-webpack-plugin 

### ISSUE THREAD

**Issue by moore529** [NervJS/taro#6398]
### 问题描述
项目中引入 lodash 后使得项目变大了不少，想要按需引入 lodash，需要使用 lodash-webpack-plugin 插件，请问在taro中如何配置 lodash-webpack-plugin ，查看了文档，只有一个 npm-install-webpack-plugin 的例子，尝试了但是还是无法配置成功 。

### 期望行为

求助一份配置 lodash-webpack-plugin 的代码，万分感谢

### 系统信息
2.2.2

**Comment by Spencer17x** [comment]
lodash不是可以install某个方法的吗？比如你要用get直接install lodash.get就可以了，满足不了你的需求吗？也是按需引入的。

**Comment by XieShangZheng** [comment]
> lodash不是可以install某个方法的吗？比如你要用get直接install lodash.get就可以了，满足不了你的需求吗？也是按需引入的。

请问是把用到的方法都分别 install 吗

如果可以用webpack插件解决按需引入的问题就最好了，手动挡变自动挡

**Comment by kala888** [comment]
@XieShangZheng  昨天我配置了一下，看起来是生效了的, 直接用import _ from 'lodash'   没问题，tree shaking和压缩，
仅供参考：https://github.com/kala888/nice-router-taro/commit/fbb25f4ed344809678a4edb0aeb1e27fa620534a

**Comment by kala888** [comment]
哦，不好意思没看清你使用的taro2，我在最新的taro3配置的，之前taro1和taro2，都是用 import xxx from 'lodash/xxxx'的方式使用的

**Comment by XieShangZheng** [comment]
> 哦，不好意思没看清你使用的taro2，我在最新的taro3配置的，之前taro1和taro2，都是用 import xxx from 'lodash/xxxx'的方式使用的

感谢回复，我可以试着升到taro3了。

**Comment by XieShangZheng** [comment]
> > 哦，不好意思没看清你使用的taro2，我在最新的taro3配置的，之前taro1和taro2，都是用 import xxx from 'lodash/xxxx'的方式使用的
> 
> 感谢回复，我可以试着升到taro3了。

大佬，我升级到 3 后配置 lodash-webpack-plugin 任然不能按需加载。

**Comment by coffeehc** [comment]
同问
