### ISSUE TITLE
可以引入react-spring吗

### ISSUE THREAD

**Issue by 2788** [NervJS/taro#6404]
在微信开发者工具里面 可以看到react-spring的效果
但是真机运行就没有变化了

taro版本: 3.0.0-rc.0

**Comment by cncolder** [comment]
理论上可以, 在旧 android 上性能较差.

https://github.com/tarojsx/library/blob/master/docs/react-spring.mdx

使用前提是 polyfill `raf`
https://github.com/tarojsx/library#%E4%BD%BF%E7%94%A8
