### ISSUE TITLE
taro 3 百度平台页面无法渲染

### ISSUE THREAD

**Issue by HopperDai** [NervJS/taro#6407]
### 问题描述

使用命令创建模板项目，运行并在百度开发工具打开发现页面元素无法加载；微信和 QQ 开发工具没有问题

### 复现步骤

1. 使用命令创建项目 `taro init myApp` ，选了：vue、ts、sass、vuex
2. 启动项目：`yarn dev:swan` ，在百度开发工具打开 dist ，如下图
![image](https://user-images.githubusercontent.com/21030653/82406516-6dbd0780-9a99-11ea-93d4-d0c4bf538cf7.png)
3. 在微信和 QQ 开发工具正常，如下图
![image](https://user-images.githubusercontent.com/21030653/82406584-980ec500-9a99-11ea-8c57-61903fd565e6.png)
![image](https://user-images.githubusercontent.com/21030653/82406598-9fce6980-9a99-11ea-96b8-01c8cce7ea88.png)

### 期望行为

在百度开发工具正常渲染页面

### 报错信息

运行百度时，会报一个依赖的警告
![image](https://user-images.githubusercontent.com/21030653/82406667-cc828100-9a99-11ea-9057-24acf1e22ca0.png)

### 系统信息

Taro CLI 3.0.0-rc.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/taro: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/webpack-runner: 3.0.0-rc.0 => 3.0.0-rc.0
      eslint-config-taro: 3.0.0-rc.0 => 3.0.0-rc.0

**Comment by yuche** [comment]
把 es6 转 es5 关了，https://github.com/NervJS/taro/pull/6408 merge 之后应该就行了

**Comment by HopperDai** [comment]
> 把 es6 转 es5 关了，#6408 merge 之后应该就行了

所以是需要等待你们 merge 了，才可以对吗

**Comment by yuche** [comment]
> > 把 es6 转 es5 关了，#6408 merge 之后应该就行了
> 
> 所以是需要等待你们 merge 了，才可以对吗

merge 发版本之后才行

**Comment by HopperDai** [comment]
运行的警告移除了，但渲染还是有问题
![image](https://user-images.githubusercontent.com/21030653/83122088-b9a92580-a105-11ea-9cb5-def34878a588.png)
![image](https://user-images.githubusercontent.com/21030653/83122188-d9d8e480-a105-11ea-91ca-da2bd12cda9e.png)

**Comment by yang4515** [comment]
v3.0.0-rc.3依然不行

**Comment by yang4515** [comment]
v3.0.0-rc.4依然不行
