### ISSUE TITLE
[Taro3 rc0] Taro 特有 hooks 回调函数更新问题

### ISSUE THREAD

**Issue by cncolder** [NervJS/taro#6419]
### 问题描述

目前 Taro 特有的 hooks 里, 需要传递回调函数的部分, callback 发生变化后都无法更新.

问题原因出在 https://github.com/NervJS/taro/blob/v3.0.0-rc.0/packages/taro-runtime/src/dsl/hooks.ts#L10

在 useLayoutEffect 里, 除 useShareAppMessage 外其他 hooks 如果传递第二个参数 deps, 导致的结果是新旧 callback 被合并进一个数组里.

这样的设计应该是为了 hook 可以在同一个页面中多次使用.

应该使用 useRef 记录上一个 callback, 同时把 callback 也加入 deps, useLayoutEffect 再次运行时把旧的 callback 排除.

以下方式会不会导致 useLayoutEffect 重复循环未经验证!

```ts
const taroHooks = (lifecycle: keyof PageLifeCycle) => {
  return (fn: Function, deps: DependencyList = []) => {
    const id = React.useContext(PageContext)
    const prev = React.useRef()
    const cb = fn.bind(null)
    React.useLayoutEffect(() => {
      let inst = getPageInstance(id)
      let first = false
      if (inst == null) {
        first = true
        inst = Object.create(null)
      }
      if (lifecycle !== 'onShareAppMessage') {
        (inst![lifecycle] as any) = [
          ...((inst![lifecycle] as any) || []).filter(f => f !== prev.current),
          cb
        ]
        prev.current = cb
      } else {
        inst![lifecycle] = cb
      }
      if (first) {
        injectPageInstance(inst!, id)
      }
    }, [cb, ...deps])
  }
}
```

### 复现步骤

```js
const [page, setPage] = useState(1)
const callback = () => {
	fetch(page)
	setPage(prev => prev + 1)
}

// 永远读取第1页
useReachBottom(callback)

// 第一次读取第1页, 第二次读取第1,2页, 第三次读取第1,2,3页...
useReachBottom(callback, [page])
```

### 期望行为

useReachBottom 以及类似 hook 应该拥有和 useEffect 相同的行为.

### 系统信息

taro 3.0.0-rc.0

### 补充信息

在不考虑同一页面多次使用的前提下, 个人项目内可以自己写这些 hooks.

```js
useReachBottom(callback => {
    useMemo(() => {
        if (Current.page) {
            Current.page.onReachBottom = callback
        }
    }, [callback])
})
```

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by cncolder** [comment]
@yuche 关于 taroHooks 的改进, 我建议废除 deps, 虽然这会造成 BREAKING CHANGE.

考虑 taroHooks 的功能, 本质上是一些事件回调, 同已有的 React hooks 之间没有可比性, 这些 Taro 特有的 hooks 其实是独立于 React 之外的, 与 render 过程无关, 而且随时可能触发.

此处可以参考 https://github.com/streamich/react-use/blob/master/docs/useEvent.md, 这个 hook 是其他很多 hooks 的基础, 函数签名是 `useEvent(eventName, handler)`, 没有依赖项, handler 永远是最新的.

其实这与组件事件回调的使用方式类似, `<Button onClick={handler}>`, 用户永远不会因为 Button 触发了旧的 handler 而惊讶, 反而需要想怎么 memo 的问题.

useDidShow 从某种意义上其实就是 `<Page onDidShow={handler}>`.

我基于这个前提, 做了二次封装, 目前在真实项目中表现符合预期. https://github.com/tarojsx/hooks/blob/master/src/taroHooks.ts

**Comment by yuche** [comment]
> 考虑 taroHooks 的功能, 本质上是一些事件回调, 同已有的 React hooks 之间没有可比性, 这些 Taro 特有的 hooks 其实是独立于 React 之外的, 与 render 过程无关, 而且随时可能触发.

我同意你的看法，下个版本 (rc.5) 就会启动针对 hooks 的更改
