### ISSUE TITLE
头条小程序嵌套组件后卡顿

### ISSUE THREAD

**Issue by ziruozimi** [NervJS/taro#6423]
#### 头条原生
![tt](https://user-images.githubusercontent.com/15374531/82436399-58130680-9ac8-11ea-8124-8821d480da51.gif)
#### Taro
![taro](https://user-images.githubusercontent.com/15374531/82436405-5a756080-9ac8-11ea-86c6-b94027c2cc8e.gif)

[示例代码](https://github.com/ziruozimi/tt_demo.git)

**Comment by Chen-jj** [comment]
子组件不需要生命周期的话，少开子组件，或者用闭包函数式组件

**Comment by ziruozimi** [comment]
> 子组件不需要生命周期的话，少开子组件，或者用闭包函数式组件

这个在微信上表现是正常的

**Comment by ziruozimi** [comment]
更新taro3.0之后解决这个问题
[Taro Next](https://juejin.im/post/5e4487b3e51d4527214ba6b1)
> 为了解决这个问题，Taro 从服务端渲染受到启发，在 Taro CLI 将页面初始化的状态直接渲染为无状态的 wxml，在框架和业务逻辑运行之前执行渲染流程。我们将这一技术称之为预渲染（Prerender），经过 Prerender 的页面初始渲染速度通常会和原生小程序一致甚至更快。

**Comment by haoxinjieFE** [comment]
项目里有用到 taro-ui 除了升级 next 还有别的办法支持下吗 现在这个问题很影响体验... @luckyadam @Chen-jj
