### ISSUE TITLE
设置了Swiper 的高度后，图片显示正确，指示点没有移动到底部

### ISSUE THREAD

**Issue by xutingzhou** [NervJS/taro#6436]
### 问题描述
需要1：1显示图片，指定了Swiper的高度后，指示点没有移动到底部

### 复现步骤

1. 
2. 
3. 
4. 

```js
         <Swiper
              style={{width: '100%', height: `${device.screenWidth}px`}}
              circular
              indicatorDots
              autoplay
            >
              {
                productData.images.map(image => (
                  <SwiperItem key={image.id} style={{width: '100%', height: `${device.screenWidth}px`}}>
                    <Image
                      style={{width: '100%'}}
                      mode='widthFix'
                      src={`${IMAGE_URL}${image.url}`}
                    />
                  </SwiperItem>
                ))
              }
            </Swiper>

```

![微信截图_20200522122414](https://user-images.githubusercontent.com/5705222/82631456-0d100500-9c28-11ea-8305-7bd7e90b459d.png)

### 期望行为

请教正确的设置方法

### 系统信息

Taro v2.2.6

  Taro CLI 2.2.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
更新版本可以解决该问题
