### ISSUE TITLE
[ 急 ] Taro 项目从 2.2.2 升级到 3.0.0-rc.0 报错

### ISSUE THREAD

**Issue by XieShangZheng** [NervJS/taro#6438]
### 问题描述
taro 2.2.2 升级 taro3，通过迁移指南，安装以及升级依赖后，yarn dev:weapp 报错。

### 复现步骤

1. taro 2.2.2 版本
2. 按照迁移指南升级到3

### 期望行为

解决报错问题，不知道为什么会报这个错
### 报错信息

![报错截图](https://qn.xiesz.com/AT/051504.png?blog)
### 系统信息
Taro 2.2.2 -> Taro v3.0.0-rc.0

**Comment by Chen-jj** [comment]
@XieShangZheng 看看 babel.config.js，babel-preset-taro 装好配好没有。

**Comment by XieShangZheng** [comment]
> @XieShangZheng 看看 babel.config.js，babel-preset-taro 装好配好没有。

感谢！添加上 babel.config.js 和 babel-preset-taro 报错问题解决了。
