### ISSUE TITLE
taro3 安装 taro-ui 后编译报错

### ISSUE THREAD

**Issue by shangZhengXie** [NervJS/taro#6439]
### 问题描述
taro 3 项目安装 taro-ui 后，报错 `./node_modules/taro-ui/dist/weapp/index.ts
Module not found: Can't resolve './style/index.scss' in '/Users/at/code/open/taro3/node_modules/taro-ui/dist/weapp'`

### 复现步骤

1. 新建 taro3 项目
2. 安装  taro-ui 依赖
3. 在 index 页面中引入 AtButton 组件
4. yarn dev:weapp
5. 控制台查看报错信息

### 期望行为

期望正常使用 ui 库
### 报错信息

![报错截图](https://qn.xiesz.com/AT/073343.png?blog)
### 系统信息

 Taro CLI 3.0.0-rc.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.11.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.0 => 3.0.0-rc.0 
      @tarojs/taro: 3.0.0-rc.0 => 3.0.0-rc.0 
      @tarojs/webpack-runner: 3.0.0-rc.0 => 3.0.0-rc.0 
      eslint-config-taro: 3.0.0-rc.0 => 3.0.0-rc.0 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^2.3.4 => 2.3.4

**Comment by cncolder** [comment]
@XieShangZheng taro-ui 2.x 不兼容 taro 3.x

**Comment by XieShangZheng** [comment]
> @XieShangZheng taro-ui 2.x 不兼容 taro 3.x

请问taro 3.x 有支持的开源组件库吗？taro-ui 有计划兼容 3.x 吗

**Comment by XieShangZheng** [comment]
> @XieShangZheng taro-ui 2.x 不兼容 taro 3.x

感谢，看到大佬开源的tarojsxui项目和官方的 3.x 兼容tag了

**Comment by c690554125** [comment]
😢  开发了才发现尽然Taro-ui不支持taro3.0.0，官方有计划支持吗？

**Comment by ZakaryCode** [comment]
npm i taro-ui@next
