### ISSUE TITLE
[Taro3 rc.0] "mini.commonChunks" is not allowed

### ISSUE THREAD

**Issue by AvanckYoung** [NervJS/taro#6440]
### 问题描述

taro 3.0beta5.0 升级到RC.0版本 执行报错

### 复现步骤

config/index.js 文件 mini 节点下增加 commonChunks 报错

### 期望行为

能正常运行

### 报错信息

Taro 配置有误，请检查！
 (\config\index.js)
  [✗] mini.commonChunks "mini.commonChunks" is not allowed

### 系统信息

Taro CLI 3.0.0-rc.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.1.0 - D:\APP\NVM\node\node.EXE
      Yarn: 1.22.4 - D:\APP\NVM\npm\yarn.CMD
      npm: 6.14.4 - D:\APP\NVM\node\npm.CMD

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/6383
