### ISSUE TITLE
[Taro Next] 数组重新排序后，列表渲染不正常

### ISSUE THREAD

**Issue by cuikangyi** [NervJS/taro#6442]
### 问题描述
对象数组，适应对象id做key，重新排序后列表渲染丢失

### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

import React, { Component } from 'react'
import { View, Text, Button } from '@tarojs/components'
import './index.scss'

const initData = [
  { id: 1, value: '111111', sort: 3 },
  { id: 2, value: '222222', sort: 4 },
  { id: 3, value: '333333', sort: 1 },
  { id: 4, value: '444444', sort: 2 },
];

export default class Index extends Component {
  constructor(props) {
    super(props)

    this.state = {
      data: []
    };
  }

  componentDidMount () {
    this.setState({ data: initData })
  }

  render () {
    return (
      <View className='index'>
        <Text>Hello world!</Text>
        <Button onClick={() => {
          const data = [...initData]
          data.sort((v1, v2) => {
            return v1.sort - v2.sort
          })
          console.log(this.state.data, data)
          this.setState({data})
        }}>排序</Button>
        {this.state.data.map((v, index) =>
        <View key={v.id} className='test'>
          <Text>{v.value}</Text>
        </View>)}
      </View>
    )
  }
}#

```

### 系统信息
Taro 3.0.0-rc0

### 补充信息
![A40F01F8-C3AE-401A-B865-B22C612512AD](https://user-images.githubusercontent.com/5945838/82659097-aeb04a00-9c5a-11ea-89ec-37fff552e2f2.png)

![991C4151-AE5A-4B7D-894C-1BB64CECD630](https://user-images.githubusercontent.com/5945838/82659115-b5d75800-9c5a-11ea-8fc6-424d84bdd870.png)

![DDB9D562-92E8-4AC0-8493-BDEF2FB9A9A3](https://user-images.githubusercontent.com/5945838/82659109-b40d9480-9c5a-11ea-9da5-f54e8e3559c3.png)

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Spencer17x** [comment]
把id换成xxid，只要不是id就行

**Comment by LuckyHH** [comment]
Taro好像一直都有这个问题。一个列表每一项添加一个事件，新增项后，触发的事件顺序是乱的。。解决办法就是把 key 值 改成 uuid，让列表每次都重新渲染

**Comment by RoJoHub** [comment]
........解决了我大量时间....这个问题现在还是没有修好

**Comment by Laev** [comment]
这个问题应该重新开启

**Comment by Chen-jj** [comment]
> fix(runtime): 修复移动 DOM 元素会卸载子组件的问题 #6460

当时的 PR 就已经修好了：

![image](https://user-images.githubusercontent.com/11807297/146499083-eaa4b1e5-92dc-49e8-8f47-f56a03de3666.png)
