### ISSUE TITLE
taro升级之后启动bug

### ISSUE THREAD

**Issue by fireairforce** [NervJS/taro#6449]
### 问题描述
当使用 `npm run dev`一系列命令去启动小程序的时候，会遇到 `EROFS: read-only file system, mkdir '/dist'`，具体图片如下:
![image](https://user-images.githubusercontent.com/32598811/82773683-3a052780-9e75-11ea-97d3-d6ebe217f925.png)

问题是在taro升级过程中产生的。版本由1.x升级到了2.5.5。

### 复现步骤

安装完成依赖，之后使用`npm run dev:xxx`命令启动对应端的应用时。

### 期望行为

能有一个解决方案

### 报错信息

见问题描述

### 系统信息
```
Taro CLI 2.2.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/async-await: 2.2.5 => 2.2.5 
      @tarojs/components: 2.2.5 => 2.2.5 
      @tarojs/mini-runner: ^2.2.5 => 2.2.6 
      @tarojs/plugin-babel: 2.2.5 => 2.2.5 
      @tarojs/plugin-csso: 2.2.5 => 2.2.5 
      @tarojs/plugin-sass: 2.2.5 => 2.2.5 
      @tarojs/plugin-uglifyjs: 2.2.5 => 2.2.5 
      @tarojs/router: 2.2.5 => 2.2.5 
      @tarojs/taro: 2.2.5 => 2.2.5 
      @tarojs/taro-alipay: 2.2.5 => 2.2.5 
      @tarojs/taro-h5: 2.2.5 => 2.2.5 
      @tarojs/taro-qq: 2.2.5 => 2.2.5 
      @tarojs/taro-quickapp: 2.2.5 => 2.2.5 
      @tarojs/taro-swan: 2.2.5 => 2.2.5 
      @tarojs/taro-tt: 2.2.5 => 2.2.5 
      @tarojs/taro-weapp: 2.2.5 => 2.2.5 
      @tarojs/webpack-runner: 2.2.5 => 2.2.5 
      eslint-config-taro: 2.2.5 => 2.2.5 
      eslint-plugin-taro: 2.2.5 => 2.2.5 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.2.5 => 2.2.5 
      stylelint-taro-rn: 2.2.5 => 2.2.5 
    npmGlobalPackages:
      typescript: 3.9.2
```

### 补充信息
尝试google搜索了几种解决方案，例如重新设置npm地址，使用`sudo npm run ...`来启动，
删除`node_modules`重装之后还是不能解决问题。

**Comment by luckyadam** [comment]
没有复现，建议检查一下自己的运行环境
https://www.google.com/search?sxsrf=ALeKk012Tnpb86yRerBrwTpOzWTqBbg1Pw%3A1590377228782&ei=DDvLXqaxL7GmmAX-n6iwDQ&q=erofs+read-only+file+system+mkdir+&oq=erofs+read-only+file+system+mkdir+&gs_lcp=CgZwc3ktYWIQAzIECCMQJzICCAAyBAgAEB4yBggAEAUQHjIGCAAQBRAeMgYIABAIEB5QhRxYpiFgmCNoAHAAeACAAaoBiAHcCZIBAzAuOJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwim557uiM7pAhUxE6YKHf4PCtYQ4dUDCAw&uact=5

**Comment by kisstar** [comment]
看起来是一个目录权限问题。

Mac OS 升级 macOS Catalina 后，系统默认对根目录文件做了只查权限控制。

可以确认一下，这个 `/dist` 目录是你设置的期望输出目录吗，还是由 Taro 默认推测出的输出目录。

如果是前者，你可能需要自己要做一些额外的工作。

**Comment by fireairforce** [comment]
> 看起来是一个目录权限问题。
> 
> Mac OS 升级 macOS Catalina 后，系统默认对根目录文件做了只查权限控制。
> 
> 可以确认一下，这个 `/dist` 目录是你设置的期望目录吗（比如输出目录），还是由 Taro 默认涉及的。
> 
> 如果是前者，你可能需要自己要做一些额外的工作。

我检查了一下dist目录，做了一下路径的调整，解决了，确实是和macos有关，感谢。

**Comment by zhangyihua2020** [comment]
> > 看起来是一个目录权限问题。
> > Mac OS 升级 macOS Catalina 后，系统默认对根目录文件做了只查权限控制。
> > 可以确认一下，这个 `/dist` 目录是你设置的期望目录吗（比如输出目录），还是由 Taro 默认涉及的。
> > 如果是前者，你可能需要自己要做一些额外的工作。
> 
> 我检查了一下dist目录，做了一下路径的调整，解决了，确实是和macos有关，感谢。

我也遇到相同问题，请问具体是如何路径调整的呀？
