### ISSUE TITLE
3.0 rc0 版本Image组件无法正常使用 500

### ISSUE THREAD

**Issue by trlanfeng** [NervJS/taro#6452]
### 问题描述

3.0 rc0 版本Image组件无法正常使用

代码：`<Image src="./logo.png"></Image>`

```
VM105:1 Mon May 25 2020 16:29:01 GMT+0800 (中国标准时间) 渲染层网络层错误
VM84:1 Failed to load local image resource /pages/index/logo.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
```

### 期望行为

正常渲染 Image 组件

### 报错信息

```
VM105:1 Mon May 25 2020 16:29:01 GMT+0800 (中国标准时间) 渲染层网络层错误
VM84:1 Failed to load local image resource /pages/index/logo.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
```

### 系统信息

```
👽 Taro v3.0.0-rc.0


  Taro CLI 3.0.0-rc.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/taro: 3.0.0-rc.0 => 3.0.0-rc.0
      @tarojs/webpack-runner: 3.0.0-rc.0 => 3.0.0-rc.0
      eslint-config-taro: 3.0.0-rc.0 => 3.0.0-rc.0
      react: ^16.10.0 => 16.13.1
```

**Comment by yuche** [comment]
使用 import 或 require 语法引入了再使用

**Comment by mengfanfei** [comment]
@yuche 我使用vue 模板  使用require引入
![image](https://user-images.githubusercontent.com/27276920/82857889-de09d400-9f44-11ea-979c-5a9da2dffbf8.png)但还是报错
![image](https://user-images.githubusercontent.com/27276920/82857936-01cd1a00-9f45-11ea-9456-5e9d91d65990.png)有解决办法吗

**Comment by trlanfeng** [comment]
> @yuche 我使用vue 模板 使用require引入
> ![image](https://user-images.githubusercontent.com/27276920/82857889-de09d400-9f44-11ea-979c-5a9da2dffbf8.png)但还是报错
> ![image](https://user-images.githubusercontent.com/27276920/82857936-01cd1a00-9f45-11ea-9456-5e9d91d65990.png)有解决办法吗

@yuche react也是如此

**Comment by yuche** [comment]
用 import，require 需要加 default，这个可以配置，详情：
https://github.com/NervJS/taro/issues/6148#issuecomment-625087706
