### ISSUE TITLE
打包提示编译警告

### ISSUE THREAD

**Issue by qiuziz** [NervJS/taro#6456]
### 问题描述
打包出现警告,common.js打包体积400k 我看了 是把echarts.min.js打包进去了 但是问题是 我根本没有在common中引入过这个啊

### 报错信息

![image](https://user-images.githubusercontent.com/13669987/82851985-1f45b800-9f34-11ea-93ec-da57f435ef3a.png)
![image](https://user-images.githubusercontent.com/13669987/82851996-253b9900-9f34-11ea-97de-7f18b0b9bb80.png)

![image](https://user-images.githubusercontent.com/13669987/82852030-38e6ff80-9f34-11ea-9316-ef9f325ce9c6.png)

### 系统信息

![image](https://user-images.githubusercontent.com/13669987/82852128-97ac7900-9f34-11ea-803c-f1d427b010bd.png)

**Comment by qiuziz** [comment]
![image](https://user-images.githubusercontent.com/13669987/82852173-bc085580-9f34-11ea-8061-f16590686478.png)

**Comment by luckyadam** [comment]
引用了的文件必然会打包

**Comment by qiuziz** [comment]
![image](https://user-images.githubusercontent.com/13669987/82973750-d01e8680-a00a-11ea-8202-070538e38ce9.png)
我项目中一些通用工具函数是放到common中的 以为打包的是我的common文件夹下的所有文件- -，看了下打包配置，是我理解错了

![image](https://user-images.githubusercontent.com/13669987/82973993-6eaae780-a00b-11ea-8d92-cc386eda34d3.png)
![image](https://user-images.githubusercontent.com/13669987/82974006-75395f00-a00b-11ea-811e-594b8bdf9b6d.png)
![image](https://user-images.githubusercontent.com/13669987/82974042-897d5c00-a00b-11ea-8967-0b8a0ec82a81.png)

那么我的问题是： 我的业务代码就是十几k这样 但是因为引入了common.js，所以提示我这个业务js文件太大 是不是不太合理

**Comment by mushroomlb** [comment]
用到什么引用什么吧，编译器没有那么智能的
