### ISSUE TITLE
什么时候支持 css modules / 非哈希路由 / 全箭头函数

### ISSUE THREAD

**Issue by missmimia** [NervJS/taro#646]
**问题描述**
1. 什么时候支持 css modules, 同类被覆盖hin难受的说 😭

2. h5什么时候支持非哈希路由，去掉“pages” (大佬说了，能少写一个是一个..)

3. 什么时候能支持全部用箭头函数 

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by wsdo** [comment]
小程序 不同页面貌似 不冲突吧

**Comment by luckyadam** [comment]
1、css modules 在计划中，不过比较麻烦，耗时会比较久
2、非哈希路由正在搞哦，下个月可以支持
3、全部使用箭头函数是指？

**Comment by AibiTi** [comment]
全部使用箭头函数指的是在 props 里使用箭头函数吧。
另外我比较希望支持 styled-components

**Comment by luckyadam** [comment]
@AibiTi styled-components 在努力开发中

**Comment by MrKou47** [comment]
@luckyadam 支持 css-module 有在开发么，我有这方便的经验，可以帮助实现。

**Comment by luckyadam** [comment]
@MrKou47 有计划实现~ 如果能帮助实现就最好了，求 PR ~

**Comment by MrKou47** [comment]
> @MrKou47 有计划实现~ 如果能帮助实现就最好了，求 PR ~

ok, 我这周会有一个PR.

**Comment by frontlich** [comment]
想问一下非哈希路由实现了吗

**Comment by yuche** [comment]
全都支持了，详情可以在文档中搜索
