### ISSUE TITLE
提交更新太频繁了

### ISSUE THREAD

**Issue by huangguozhen** [NervJS/taro#647]
@tarojs/cli提交更新太频繁了，是否可以用于正式项目？

**Comment by yuche** [comment]
提交太频繁了被说不稳定，没有提交又被说弃坑，偶尔提交又被说是爱理不理。

那到底是提交还是不提交，提交的数量和时间的线性流动是否有一个黄金比例？

很急，在线等。

**Comment by wsdo** [comment]
用艺术家的心态，对待自己的产品，做自己的事情，让别人欣赏去吧。

**Comment by huangguozhen** [comment]
@yuche 首先这是一个很棒的项目。这两天刚接触到，感觉非常好，准备用于开发小程序。因为这两天大概经历了三个版本的变更，担心是否版本更新是否会对代码兼容性的影响，固有此疑虑。
我的建议是，如果是Bug修复的话立即更新。新功能可以按周。当然我们都希望项目是很活跃的状态。
最后说一下，在Issues提问能得到快速回复真的很棒。

**Comment by luckyadam** [comment]
@huangguozhen 目前正式版本已经发布，版本更新会谨慎的，会遵循 semver 规范

修订号更新主要会是 bug 修复，更新会频繁些
次版本号会是一些中小型新功能，迭代不会那么频繁

**Comment by yuche** [comment]
@huangguozhen 由于昨天我们需要发布 1.0.0 版本，为了保证第一个 Major 版本是稳定的，最近我们只好频繁地多发几个版本给开发者们测试。

未来 Taro 会在工程上趋于稳定，更新只是添加新功能和 fix bug，不会影响到原有的功能。但多端项目的本质要求我们不断迭代和添加新特性，所以新版本的发布肯定是免不了的。

**Comment by huangguozhen** [comment]
@yuche @luckyadam 好的，了解。
