### ISSUE TITLE
编译 defineConstants 的问题

### ISSUE THREAD

**Issue by afishhhhh** [NervJS/taro#6472]
```js
// 代码1
defineConstants: {
  A: 'abc'
}
// 代码2
defineConstants: {
  A: JSON.stringify('abc')
}
```

代码1编译后的结果是 `'abc'`，代码2编译后的结果也是 `'abc'`
代码1的结果不应该是 `abc` 吗？

### 系统信息
Taro CLI 2.1.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      npm: 6.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.6 => 2.1.6 
      @tarojs/components-qa: 2.1.6 => 2.1.6 
      @tarojs/mini-runner: 2.1.6 => 2.1.6 
      @tarojs/router: 2.1.6 => 2.1.6 
      @tarojs/taro: 2.1.6 => 2.1.6 
      @tarojs/taro-alipay: 2.1.6 => 2.1.6 
      @tarojs/taro-h5: 2.1.6 => 2.1.6 
      @tarojs/taro-qq: 2.1.6 => 2.1.6 
      @tarojs/taro-quickapp: 2.1.6 => 2.1.6 
      @tarojs/taro-rn: 2.1.6 => 2.1.6 
      @tarojs/taro-swan: 2.1.6 => 2.1.6 
      @tarojs/taro-tt: 2.1.6 => 2.1.6 
      @tarojs/taro-weapp: 2.1.6 => 2.1.6 
      @tarojs/webpack-runner: 2.1.6 => 2.1.6 
      eslint-config-taro: 2.1.6 => 2.1.6 
      eslint-plugin-taro: 2.1.6 => 2.1.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      stylelint-config-taro-rn: 2.1.6 => 2.1.6 
      stylelint-taro-rn: 2.1.6 => 2.1.6 
      taro-ui: ^2.3.3 => 2.3.3

**Comment by luckyadam** [comment]
可以升级到 2.2.6 试试

**Comment by afishhhhh** [comment]
`defineConstants: { A: '123' }` 输出是 `123`，`defineConstants: { A: 'abc' }` 输出是 `"abc"`，我懵了。 @luckyadam

**Comment by luckyadam** [comment]
> `defineConstants: { A: '123' }` 输出是 `123`，`defineConstants: { A: 'abc' }` 输出是 `"abc"`，我懵了。 @luckyadam

哪个版本

**Comment by afishhhhh** [comment]
> > `defineConstants: { A: '123' }` 输出是 `123`，`defineConstants: { A: 'abc' }` 输出是 `"abc"`，我懵了。 @luckyadam
> 
> 哪个版本

2.2.6

**Comment by afishhhhh** [comment]
请问这个问题解决了吗 @luckyadam
