### ISSUE TITLE
[taro-next rc.2] 版本的 virtual-list 小程序中表现正常，h5 中样式都未加载

### ISSUE THREAD

**Issue by GarfieldLucy** [NervJS/taro#6473]
### 问题描述

taro-next rc 版本的 virtual-list 小程序中表现正常，h5 中样式都未加载
### 复现步骤

1. 按照文档添加并使用 virtual-list
2. 编译 h5 命令
3. 小程序显示正常，h5 未有 top 属性

### 期望行为

期望 h5 显示跟小程序一样

**Comment by ZHocean123** [comment]
小程序有没有遇到[#6467](https://github.com/NervJS/taro/issues/6467)这个问题吗？

**Comment by GarfieldLucy** [comment]
> 小程序有没有遇到[#6467](https://github.com/NervJS/taro/issues/6467)这个问题吗？

我是在 react 中使用的

**Comment by yuche** [comment]
麻烦贴一下你的使用代码，包括样式，尽量删减脱敏最小化
