### ISSUE TITLE
Taro.showLoading()、Taro.hideLoading() 不成对调用导致H5页面位置回到顶部

### ISSUE THREAD

**Issue by chunge66** [NervJS/taro#6474]
### 问题描述
Taro.showLoading()、Taro.hideLoading() 调用导致H5页面回到顶部，删除页面中的 Taro.showLoading()、Taro.hideLoading() 方法后问题解决。

### 复现步骤

1、H5页面列表下拉加载更多时，后端数据返回后单独调用 Taro.hideLoading()，导致页面自动回到顶部。
2、H5一级页面跳转到二级页面，二级页面调用了 Taro.showLoading() 后返回一级页面，一级页面自动回到顶部。

### 期望行为
Taro.showLoading()、Taro.hideLoading() 调用不影响H5页面位置

### 系统信息
👽 Taro v2.0.5

  Taro CLI 2.0.5 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    npmPackages:
      @tarojs/components: 2.0.5 => 2.0.5 
      @tarojs/components-qa: 2.0.5 => 2.0.5 
      @tarojs/mini-runner: 2.0.5 => 2.0.5 
      @tarojs/router: 2.0.5 => 2.0.5 
      @tarojs/taro: 2.0.5 => 2.0.5 
      @tarojs/taro-alipay: 2.0.5 => 2.0.5 
      @tarojs/taro-h5: 2.0.5 => 2.0.5 
      @tarojs/taro-qq: 2.0.5 => 2.0.5 
      @tarojs/taro-quickapp: 2.0.5 => 2.0.5 
      @tarojs/taro-rn: 2.0.5 => 2.0.5 
      @tarojs/taro-swan: 2.0.5 => 2.0.5 
      @tarojs/taro-tt: 2.0.5 => 2.0.5 
      @tarojs/taro-weapp: 2.0.5 => 2.0.5 
      @tarojs/webpack-runner: 2.0.5 => 2.0.5 
      eslint-config-taro: 2.0.5 => 2.0.5 
      eslint-plugin-taro: 2.0.5 => 2.0.5 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-taro-rn: 2.0.5 => 2.0.5 

### 补充信息
暂时去掉了 Taro.showLoading() 方法，改为自定义的 Spinner 组件，规避该问题。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by lentoo** [comment]
原来这里有坑，找半天
真是醉了
