### ISSUE TITLE
在生命周期 componentDidShow 获取不到 this.$router.preload

### ISSUE THREAD

**Issue by yeojongki** [NervJS/taro#6477]
### 问题描述

![image](https://user-images.githubusercontent.com/21023676/82986822-1f73af80-a029-11ea-9ffe-d4fac1c1c771.png)

### 复现步骤

```jsx
// /pages/test/test.jsx
class Index extends Component {
  onClick = () => {
    this.$preload('preload', 'preload data')
    Taro.navigateTo({
      url: '/pages/test/index',
    })
  }

  render() {
    return <Button onClick={this.onClick}>点击跳转</Button>
  }
}

// /pages/test/index.jsx
class Index extends Component {
  componentDidMount() {
    console.log('dis mount', this.$router.preload)
  }

  componentDidShow() {
    console.log('dis show', this.$router.preload)
  }

  render() {
    return <View>{JSON.stringify(this.$router.preload)}</View>
  }
}
```

### 期望行为

正确获取数据

### 报错信息
无

### 系统信息
�👽 Taro v2.1.5

  Taro CLI 2.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD

**Comment by yeojongki** [comment]
@Chen-jj  看看我提的 `PR` 有没问题

**Comment by Chen-jj** [comment]
@yeojongki 已回复～麻烦稍微修改一下哈

**Comment by yeojongki** [comment]
@Chen-jj https://github.com/NervJS/taro/pull/6481#issuecomment-636641772

**Comment by Chen-jj** [comment]
已合并
