### ISSUE TITLE
希望函数式组件可以使用 componentWillPreload

### ISSUE THREAD

**Issue by liuchuzhang** [NervJS/taro#6478]
希望函数式组件能够使用 [componentWillPreload](http://taro-docs.jd.com/taro/docs/optimized-practice#%E9%A2%84%E5%8A%A0%E8%BD%BD)，提供类似于 usePreload 这样的 Hook

**Comment by Chen-jj** [comment]
Taro 3 不再提供 componentWillPreload、$preload API，改为:

调用：

```js
Taro.preload()
```

获取

```js
console.log(getCurrentInstance().preloadData)
```

**Comment by hardmanhong** [comment]
> Taro 3 不再提供 componentWillPreload、$preload API，改为:
> 
> 调用：
> 
> ```js
> Taro.preload()
> ```
> 
> 获取
> 
> ```js
> console.log(getCurrentInstance().preloadData)
> ```

请问`Taro.preload()`能传递`Promise`吗？如果不能那不是只能等后服务端接口调用完成才能去执行`preload`然后跳转？
