### ISSUE TITLE
common 文件夹特殊吗？ 怎么一直不能编译过去

### ISSUE THREAD

**Issue by wsdo** [NervJS/taro#648]
![image](https://user-images.githubusercontent.com/9738969/45728591-282ca500-bbfb-11e8-8954-233db7e77de8.png)
![image](https://user-images.githubusercontent.com/9738969/45728596-2cf15900-bbfb-11e8-9c7b-c6c712cd5a6d.png)

common 文件夹特殊吗？ 怎么一直不能编译过去

**Comment by luckyadam** [comment]
有引用里面的文件不~

**Comment by wsdo** [comment]
对，用这种方式，
![image](https://user-images.githubusercontent.com/9738969/45728884-a2115e00-bbfc-11e8-994c-b42ed024d1a9.png)
可是 我使用 // 引用文件
import namedPng from '../../images/path/named.png'  方式 在这使用不可以

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/45729053-5317f880-bbfd-11e8-8ee5-cb448cbb7e26.png)
这里改成 `./common` 试试

**Comment by wsdo** [comment]
可以了，谢谢

**Comment by luckyadam** [comment]
嗯嗯，我们加一下这个兼容~
