### ISSUE TITLE
如何获取原生小程序的this对象

### ISSUE THREAD

**Issue by AFu-1993** [NervJS/taro#6480]
如下在小程序的官方示例
[SelectorQuery](https://developers.weixin.qq.com/miniprogram/dev/api/wxml/SelectorQuery.in.html)
``` js
Component({
  queryMultipleNodes (){
    const query = wx.createSelectorQuery().in(this)
    query.select('#the-id').boundingClientRect(function(res){
      res.top // 这个组件内 #the-id 节点的上边界坐标
    }).exec()
  }
})
```

请问，在taro中如何获取原生小程序组件的this？

**Comment by Chen-jj** [comment]
@AFu-1993 `const query = wx.createSelectorQuery().in(this.$scope)`
