### ISSUE TITLE
希望Taro官方注重生态的培养

### ISSUE THREAD

**Issue by liguanhan** [NervJS/taro#6483]
希望Taro官方注重生态的培养

希望官方能注重生态的培养，更多的第一方，第三方库，更简单和更好的对多端的支持

**Comment by shenghanqin** [comment]
我也在思考，如何补齐云开发。

**Comment by luckyadam** [comment]
生态建设主要还是靠社区来发展~ Taro 官方团队人手还是有限啊~ 不过我们也会不断推出一些鼓励生态建设的措施，比如[物料市场大赛](http://taro-ext.jd.com/)，以及官方最近推出的[插件化改造](https://nervjs.github.io/taro/docs/plugin/)等等，都是为了让 Taro 更加开放，让社区更容易参与进来让 Taro 生态更加繁荣。

如果大家对生态建设有什么好建议，希望 Taro 官方提供怎样的支持来建设生态，欢迎给我们提！

**Comment by liguanhan** [comment]
希望Taro对图表的多端支持，和一些常用组件的多端实现，比如uview这个ui框架就比较好

**Comment by nangongmo** [comment]
react技术栈只能选taro是真的累，隔壁uni-app各种florui,uview,color ui。。。taro就一个可怜的taro ui和不完善的改造品colorui for taro

**Comment by shenghanqin** [comment]
> react技术栈只能选taro是真的累，隔壁uni-app各种florui,uview,color ui。。。taro就一个可怜的taro ui和不完善的改造品colorui for taro

@luckyadam 其实老李推荐推荐一些第三方UI，我们可以尝试适配？
