### ISSUE TITLE
[2.2.6] Taro cli 无法单独编译页面

### ISSUE THREAD

**Issue by cyh-93** [NervJS/taro#6487]
### 问题描述

2.0+ 版本，`taro build` 无法单独编译页面；而1.0+版本可以

![taro_2 0](https://user-images.githubusercontent.com/14165231/83094448-489d4a00-a0d4-11ea-8e1a-1eb984d8d302.png)
![taro_1 3 34](https://user-images.githubusercontent.com/14165231/83094517-6cf92680-a0d4-11ea-8bdf-6976917ed375.png)

### 复现步骤

1. 直接使用对应版本的cli，初始化模板
2. 随便补充一个新页面，比如`pages/test`
3. 运行`taro build --page src/pages/test --type alipay`
4. 结果跟 `npm run build:alipay` 一致，无法单独编译`pages/test`

### 期望行为

与`1.x`版本一样，支持单独编译页面

### 系统信息

```
👽 Taro v2.2.6


  Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6
      @tarojs/components-qa: 2.2.6 => 2.2.6
      @tarojs/mini-runner: 2.2.6 => 2.2.6
      @tarojs/redux: 2.2.6 => 2.2.6
      @tarojs/redux-h5: 2.2.6 => 2.2.6
      @tarojs/router: 2.2.6 => 2.2.6
      @tarojs/taro: 2.2.6 => 2.2.6
      @tarojs/taro-alipay: 2.2.6 => 2.2.6
      @tarojs/taro-h5: 2.2.6 => 2.2.6
      @tarojs/taro-qq: 2.2.6 => 2.2.6
      @tarojs/taro-quickapp: 2.2.6 => 2.2.6
      @tarojs/taro-swan: 2.2.6 => 2.2.6
      @tarojs/taro-tt: 2.2.6 => 2.2.6
      @tarojs/taro-weapp: 2.2.6 => 2.2.6
      @tarojs/webpack-runner: 2.2.6 => 2.2.6
      eslint-config-taro: 2.2.6 => 2.2.6
      eslint-plugin-taro: 2.2.6 => 2.2.6
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      stylelint-config-taro-rn: 2.2.6 => 2.2.6
      stylelint-taro-rn: 2.2.6 => 2.2.6
```

### 补充信息

3.0 版本也是有同样的问题

**Comment by luckyadam** [comment]
额，2.0 开始这个功能丢失了

**Comment by cyh-93** [comment]
> 额，2.0 开始这个功能丢失了

有考虑后续补上么？  目前想尝试单独编译页面，给原生项目使用。

**Comment by luckyadam** [comment]
> > 额，2.0 开始这个功能丢失了
> 
> 有考虑后续补上么？ 目前想尝试单独编译页面，给原生项目使用。

可以考虑加上

**Comment by cyh-93** [comment]
1.3.34 版本，发现快应用也无法单独编译页面

![image](https://user-images.githubusercontent.com/14165231/84748104-c3c69180-afea-11ea-9e56-f7769d9f0057.png)
