### ISSUE TITLE
[Taro Next]taro convert小程序转换成Vue, 文件丢失

### ISSUE THREAD

**Issue by ChendayUP** [NervJS/taro#6496]
### 问题描述

taro convert小程序转换成Vue, import文件丢失, index文件丢失
### 复现步骤

taro 转换现有程序同时转换成React和Vue, Vue文件丢失

### 期望行为

Vue转换正确

### 报错信息

![error](https://user-images.githubusercontent.com/20022523/83121844-6c2cb880-a105-11ea-8faa-cba5abe74561.png)

### 系统信息

Taro v3.0.0-rc.2

**Comment by Chen-jj** [comment]
@ChendayUP convert 前的项目精简出一个可复现 demo 给我们看看吧

**Comment by ChendayUP** [comment]
> @ChendayUP convert 前的项目精简出一个可复现 demo 给我们看看吧

已经发到你的邮箱

**Comment by ChendayUP** [comment]
请问这个问题解决没有呢?

**Comment by ChendayUP** [comment]
@yuche 请问这个问题解决没有呢?

**Comment by Chen-jj** [comment]
转 Vue 功能还没成熟，暂时还是先转 React 吧。#7939

**Comment by yearningz** [comment]
@ChendayUP  遇到同样的问题，可以参考一下说的convert 前的项目精简出一个可复现 demo 这个么？
