### ISSUE TITLE
> > 把 es6 转 es5 关了，#6408 merge 之后应该就行了

### ISSUE THREAD

**Issue by HopperDai** [NervJS/taro#6497]
> > 把 es6 转 es5 关了，#6408 merge 之后应该就行了
> 
> 所以是需要等待你们 merge 了，才可以对吗

merge 发版本之后才行

_Originally posted by @yuche in https://github.com/NervJS/taro/issues/6407#issuecomment-632761731_

**Comment by HopperDai** [comment]
运行的警告移除了，但渲染还是有问题
![image](https://user-images.githubusercontent.com/21030653/83122088-b9a92580-a105-11ea-9cb5-def34878a588.png)
![image](https://user-images.githubusercontent.com/21030653/83122188-d9d8e480-a105-11ea-91ca-da2bd12cda9e.png)

**Comment by Chen-jj** [comment]
@HopperDai 在 #6407 讨论吧，这个先关了
