### ISSUE TITLE
H5端配置了customRoutes时点击tabbar切换页面导致白屏

### ISSUE THREAD

**Issue by smilebuz** [NervJS/taro#6498]
### 问题描述

H5配置了`customRoutes`后，在`localhost:10086`打开时，点击tabbar切换时会出现白屏，发现是`taro_page`类上`display:none`。但是如果使用`localhost:10086/index`之类的方式打开，点击tabbar时显示正常。

### 复现步骤

[最小复现仓库地址](https://github.com/smilebuz/taro-customRoute)
1. `npm i`安装依赖
2. `npm run dev:h5`启动h5开发模式
3. 点击tabbar

### 期望行为

h5在配置customRoutes时点击tabbar可以正常切换路由

### 系统信息

  Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6 
      @tarojs/components-qa: 2.2.6 => 2.2.6 
      @tarojs/mini-runner: 2.2.6 => 2.2.6 
      @tarojs/router: 2.2.6 => 2.2.6 
      @tarojs/taro: 2.2.6 => 2.2.6 
      @tarojs/taro-alipay: 2.2.6 => 2.2.6 
      @tarojs/taro-h5: 2.2.6 => 2.2.6 
      @tarojs/taro-qq: 2.2.6 => 2.2.6 
      @tarojs/taro-quickapp: 2.2.6 => 2.2.6 
      @tarojs/taro-rn: 2.2.6 => 2.2.6 
      @tarojs/taro-swan: 2.2.6 => 2.2.6 
      @tarojs/taro-tt: 2.2.6 => 2.2.6 
      @tarojs/taro-weapp: 2.2.6 => 2.2.6 
      @tarojs/webpack-runner: 2.2.6 => 2.2.6 
      eslint-config-taro: 2.2.6 => 2.2.6 
      eslint-plugin-taro: 2.2.6 => 2.2.6 
      nerv-devtools: ^1.5.5 => 1.5.6 
      nervjs: ^1.5.5 => 1.5.6 
      stylelint-config-taro-rn: 2.2.6 => 2.2.6 
      stylelint-taro-rn: 2.2.6 => 2.2.6 
    npmGlobalPackages:
      typescript: 3.3.4000

### 补充信息

粗略查看了一下taro-router源码，感觉可能是在`localhost:10086`打开时，`isTabBar`这个值是`ture` 导致`Route.tsx`中`computeMatch`方法返回了`false` 从而触发了`hidePage`方法，导致类`taro_page`加上了`display:none`样式。
而使用`localhost:10086/index`直接打开tabbar配置的页面时, `isTabBar`返回`false`，`computeMatch`返回`true`。

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by smilebuz** [comment]
感觉是`taro-router`下`route.tsx`和`router.tsx`这两个文件中对于点击tabbar切换路由的判断有问题，还麻烦看一下，谢谢。

**Comment by yulrosy** [comment]
我也遇到了，跳转页面白屏

**Comment by ZakaryCode** [comment]
v2.2.10 中没有该问题，可以升级尝试
