### ISSUE TITLE
编译跑H5的时候报错页面展示不出

### ISSUE THREAD

**Issue by 941025022** [NervJS/taro#65]
![1528695758802](https://user-images.githubusercontent.com/20332743/41214319-564b1e98-6d7d-11e8-8ef4-02f0b44f30dc.jpg)

**Comment by innocces** [comment]
我也有这种问题，只不过我的依赖是nexv-redux，重新安装之后就可以了

**Comment by luckyadam** [comment]
得重新安装下项目依赖
