### ISSUE TITLE
项目初始化后跑npm run dev:rn报错

### ISSUE THREAD

**Issue by shudery** [NervJS/taro#650]
**问题描述**

taro init后运行npm run dev:rn报错

**复现步骤**
- taro init app
- npm run dev:rn

**期望行为**

运行npm run dev:rn成功

**报错信息**

```js
开始编译项目 taro-app
编译  JS        /Users/shudery/web/react/taro-app/src/app.js
编译  LESS      /Users/shudery/web/react/taro-app/src/app.less
(node:35540) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'entry' of undefined
    at Promise.all.then.then.then.catch (/Users/shudery/.nvm/versions/node/v10.10.0/lib/node_modules/@tarojs/cli/src/rn.js:526:11)
(node:35540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**系统信息**

 - 操作系统:  macOS 10.13.4
 - Taro v1.0.1
 - Node v10.10.0

**Comment by Pines-Cheng** [comment]
@shudery 请问初始化的是哪个模版，对代码做了那些修改？

**Comment by shudery** [comment]
执行taro init myApp的默认模板，选择配置redux+less，无typescript，对代码无任何修改。

**Comment by lot2** [comment]
当yarn dev:rn时，遇到了同样的错误

(node:68944) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'entry' of undefined
    at Promise.all.then.then.then.catch (/Users/ryan/.config/yarn/global/node_modules/@tarojs/cli/src/rn.js:570:11)
    at <anonymous>
(node:68944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:68944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Pines-Cheng** [comment]
已经定位问题，马上 fix ，感谢 issue。🙏
