### ISSUE TITLE
PickerView onChange 动态更改value不生效

### ISSUE THREAD

**Issue by wangweifeng66** [NervJS/taro#6500]
### 问题描述
![image](https://user-images.githubusercontent.com/26533125/83124629-05a99980-a109-11ea-8692-306ec481bfaa.png)

使用pickerView实现可以设置 ‘今天及以后’ 范围的控件。功能还未完全开发完成，但在处理 ‘年’滚动时，需要动态更改‘月’和‘天’，调试过程中遇到yearList，monthLsit，dayList更改成功，但value:[yearIndex, monthIndex, dayIndex, hourIndex, minuteIndex]设置成功后，控件并未成功按照value显示

### 复现步骤

1. yarn dev:weapp启动
2. 点击时间控件
3. 滚动最左侧 ’年‘这一列，从2020滚到2021
4. 看到第三列’天‘这一列显示为’4‘，应该显示为‘28’；新的value为[1, 4, 27, 0, 0]，

复现项目地址： https://github.com/summer88123/errorDemo.git

### 期望行为

期望‘天’列滚动正常显示为28

### 系统信息

👽 Taro v3.0.0-beta.5

  Taro CLI 3.0.0-beta.5 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/webpack-runner: 3.0.0-beta.5 => 3.0.0-beta.5 
      eslint-config-taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      react: ^16.10.0 => 16.13.1

**Comment by Chen-jj** [comment]
@wangweifeng66 升级到 rc2 再看看

**Comment by wangweifeng66** [comment]
rc2指的是？

**Comment by wangweifeng66** [comment]
升级后onChange时动态更改value值仍然不能生效，需要用下面的方式才可以
 this.setState({
            dayList: newDayList,
            monthLsit: nowMonthList,
            value,
            year,
            month,
            day,
            hour,
            minute,
            hasChange: true,
        });
        setTimeout(() => {
            this.setState({
                value,
            })
        }, 0)
需要加入一个延迟器，再次更改<PickerView /> 的value值

**Comment by yuche** [comment]
你给的 demo 在 rc.3 可以正常运行

**Comment by wangweifeng66** [comment]
> 你给的 demo 在 rc.3 可以正常运行

我这边把demo升级到了rc.3了，但是重复上面的步骤还是有问题的，只有加上setTimeout才可以，您可以更新一下代码再试一下，只滑动年份从2020滑到2021，日那一列滚动显示还是不正确的，谢谢

**Comment by Chen-jj** [comment]
升级 3.0.2 再试试吧
