### ISSUE TITLE
"components/vant/field/index.js" is not defined

### ISSUE THREAD

**Issue by hujialianghuwei** [NervJS/taro#6503]
taro 2.2.3版本
引用vant 库
配置 ：
 copy: {
    patterns: [
      { from: "src/components/vant/wxs/", to: "dist/components/vant/wxs/" },
      {
        from: "src/components/vant/dropdown-menu",
        to: "dist/components/vant/dropdown-menu",
      },
      {
        from: "src/components/vant/field",
        to: "dist/components/vant/field",
      },
    ],
  }
当配置下面的时候 dev:weap 报错，去掉重新dev 就不报错
 {
        from: "src/components/vant/field",
        to: "dist/components/vant/field",
      }

报错如下：
VM279:1 thirdScriptError
module "components/vant/field/index.js" is not defined
Error: module "components/vant/field/index.js" is not defined

VM279:1 ./components/vant/field/index.wxss
File not found: ../common/index.wxss

**Comment by Chen-jj** [comment]
@hujialianghuwei 给个 demo 看看吧

**Comment by hujialianghuwei** [comment]
很简单， 我使用 taro 2.2.3版本 初始化了一个项目，然后下载了vant-weap 复制到src/components 下面 在config 中项目配置 如下：copy: {
    patterns: [{ from: "src/components/vant/", to: "dist/components/vant/" }],
  },
dev:weapp  用微信开发工具打开 一堆的错

**Comment by Chen-jj** [comment]
@hujialianghuwei 扔个 demo 吧

**Comment by hujialianghuwei** [comment]
这里 https://github.com/hujialianghuwei/taro-vant-demo

**Comment by dooioomoo** [comment]
同样的错误

**Comment by dooioomoo** [comment]
后来，根据官方网站内容 http://taro-docs.jd.com/taro/docs/vant/ 只复制了依赖，和所使用的的脚本，貌似可以了。不能整个dist目录复制。
