### ISSUE TITLE
Mac环境（没有装Xcode）项目初始化报错

### ISSUE THREAD

**Issue by webappdevelp** [NervJS/taro#6506]
Mac环境下没有安装Xcode，但是有安装 Xcode Command Line Tools。在install 的时候挂了。

**Comment by Nicksxs** [comment]
错误信息呢

**Comment by webappdevelp** [comment]
> 错误信息呢

现在又好了，好尴尬。之前无论用sass，还是less，都会在install的时候报错，无法完成install。
