### ISSUE TITLE
v3.0.0-rc.2 编译第三方多端UI库报错

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#6514]
### 问题描述

3.0.0.rc2 编译第三方多端UI库报错

### 复现步骤

1.  使用Taro v3.0.0-rc.2  cli 新建一个基于React的项目
2.  yarn 安装依赖
3.  package.json中配置UI编译命令 "build": "TARO_BUILD_TYPE=ui taro build --ui"
4. yarn build

### 期望行为

可以正常编译第三方多端UI库

### 报错信息

![image](https://user-images.githubusercontent.com/52092826/83241626-b0838b80-a1cd-11ea-8474-c6a650e78ea5.png)

### 系统信息

![image](https://user-images.githubusercontent.com/52092826/83241584-9e095200-a1cd-11ea-8a99-de40eff1e01f.png)

**Comment by charmtiger** [comment]
你要说明是什么第三方库，原本是用于 web ？是否支持 taro ？

**Comment by cpocar** [comment]
你好，是基于 Taro 开发第三方多端 UI 库， 像2.0一样。http://taro-docs.jd.com/taro/docs/ui-lib

**Comment by cpocar** [comment]
就是 taro build --ui

基于这个堆栈，我跟到源码里面去看发现报错地方require的路径是有问题的

**Comment by cpocar** [comment]
@charmtiger

**Comment by yuche** [comment]
这个命令在 3.0 被取消掉了，如果你是给 Taro 用的，不需要编译，直接发布源码到 NPM 就行了。
如果你还需要给其他工具用，可以用类似于 microbundle 或 rollup 这样的 bundler 直接编译就行。

**Comment by cpocar** [comment]
> 这个命令在 3.0 被取消掉了，如果你是给 Taro 用的，不需要编译，直接发布源码到 NPM 就行了。
> 如果你还需要给其他工具用，可以用类似于 microbundle 或 rollup 这样的 bundler 直接编译就行。
目前用源码在本地，采用yarn link的方式给应用使用， 但是发现小程序会出现[Invalid Hook Call Warning](https://reactjs.org/warnings/invalid-hook-call-warning.html)的问题， 同样的代码，用H5的方式启起来没这个问题

**Comment by cpocar** [comment]
有使用rollup打包3.x UI组件库的最佳实践或者demo项目么？
尝试开了项目在3.0.5 版本下使用rollup， 打出来的包使用时报： React is not defined

**Comment by cpocar** [comment]
@yuche

**Comment by zdc1111** [comment]
> 这个在 3.0 被取消掉了，如果你是给 Taro 用的，不需要编译，直接发布源码到 NPM 就行了。 如果你还需要给其他工具用，可以用类似于 microbundle 或 rollup 这样的捆绑器直接编译就行。

如果给其他工具用 就会要求 其他工具使用trao 来编译， 预期开发好组件可以直接给h5 项目和小程序项目用，不需要h5项目接入taro  @yuche @luckyadam @Chen-jj  帮忙看看哈
