### ISSUE TITLE
3.0.0-rc.2 无法在app.config.ts中引入图片

### ISSUE THREAD

**Issue by ldc-37** [NervJS/taro#6516]
### 问题描述

项目中使用默认的tabbar，因此需要在`app.config.ts`中设置iconPath。
但是如果在`app.config.ts`中使用import或require，编译会报错 Invalid or unexpected token

### 复现步骤

```js
import img11 from '../assets/tabs/icon_circle_line.png'
import img12 from '../assets/tabs/icon_circle_line1.png'

export default {
  ...
  'tabbar': {
        "list": [{
            "text": "首页",
            "pagePath": "pages/home/home",
            "iconPath": img11,
            "selectedIconPath": img12
        }]
}

```

### 期望行为

正常引入图片
### 报错信息

![image](https://user-images.githubusercontent.com/34739463/83243030-e9246480-a1cf-11ea-957b-caa81c30fe4f.png)

### 系统信息

    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
### 补充信息
#5871 beta6之前也有这个状况

感觉是把图片当做文本文件处理了。临时解决方案是在其他地方用require.context引入图片，然后app.config.ts中iconPath直接设置为编译后的实际地址（啊，太僵硬了）

**Comment by Chen-jj** [comment]
@ldc-37 config.js 只是被 babel register 编译，并没有经 webpack 编译。图片不会经 file-loader，不可以被直接 import。
