### ISSUE TITLE
2层嵌套数组map获取外层map方法定义的变量未定义

### ISSUE THREAD

**Issue by horou-dsk** [NervJS/taro#6523]
### 问题描述

使用数组map嵌套第二层方法获取第一层方法定义的变量为undefined

### 复现步骤
![QQ截图20200531161543](https://user-images.githubusercontent.com/23204548/83348426-09365e00-a35f-11ea-97bf-1e81c7ec6117.png)

### 期望行为

能够正常获取offset变量

### 报错信息

offset变量为undefined

### 系统信息

  Taro CLI 2.2.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Users\Dana\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - D:\Program Files\nodejs\npm.CMD

**Comment by luckyadam** [comment]
确实有这个问题，可以换个写法

**Comment by rexsunces** [comment]
> 确实有这个问题，可以换个写法

老哥 可以有建议吗，这是bug还是微信端的限制？
