### ISSUE TITLE
H5端页面下拉刷新style中增加transform样式属性，导致页面内fixed失效

### ISSUE THREAD

**Issue by jsonliu6** [NervJS/taro#6527]
### 问题描述
在H5端进行页面下拉刷新后增加style="transform: translate3d(0px, 0px, 0px);",导致页面内部使用fixed布局的元素都失效，降级成absolute。

### 复现步骤
初始化时正常：
![image](https://user-images.githubusercontent.com/15153054/83370663-9c6ca380-a3f2-11ea-8fc6-71079ba22869.png)
下拉刷新后：（回到顶部元素消失，变成了绝对定位）
![image](https://user-images.githubusercontent.com/15153054/83370705-bf975300-a3f2-11ea-8d87-6ada8de24ab4.png)

```js

![image](https://user-images.githubusercontent.com/15153054/83370900-43513f80-a3f3-11ea-8ac1-5fa24599f6de.png)



```

### 期望行为

期望下拉刷新完成结束后，删除style="transform: translate3d(0px, 0px, 0px);",类似属性，使页面内部的fixed元素可以正常展示。

### 报错信息
无

### 系统信息

Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6 
      @tarojs/components-qa: 2.2.6 => 2.2.6 
      @tarojs/mini-runner: 2.2.6 => 2.2.6 
      @tarojs/mobx: 2.2.6 => 2.2.6 
      @tarojs/mobx-h5: 2.2.6 => 2.2.6 
      @tarojs/router: 2.2.6 => 2.2.6 
      @tarojs/taro: 2.2.6 => 2.2.6 
      @tarojs/taro-alipay: 2.2.6 => 2.2.6 
      @tarojs/taro-h5: 2.2.6 => 2.2.6 
      @tarojs/taro-weapp: 2.2.6 => 2.2.6 
      @tarojs/webpack-runner: 2.2.6 => 2.2.6 
      eslint-config-taro: 2.2.6 => 2.2.6 
      eslint-plugin-taro: 2.2.6 => 2.2.6 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 

### 补充信息

辛苦修改，为你们为社区作出的贡献致敬

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/pull/6312
