### ISSUE TITLE
useRouter().params 类型怎么定义?

### ISSUE THREAD

**Issue by lixiaofeng666** [NervJS/taro#6529]
### 问题描述
刚入手 TS 没多久, 想定义下 useRouter().params 的类型, 怎么写都会类型报错.

### 复现步骤

1. 
2. 
3. 
4. 

```js
interface RouterParams{
  phone?: string
}
const router: RouterParams= useRouter().params
```

### 报错信息
`类型“{ [key: string]: string; } & { scene?: string | number | undefined; query?: string | { [key: string]: string; } | undefined; shareTicket?: string | undefined; referrerInfo?: string | { [key: string]: any; } | undefined; }”与类型“RouterParams”不具有相同的属性。`

### 系统信息
 Taro CLI 3.0.0-rc.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - E:\nodejs10.15.3\node.EXE
      npm: 6.4.1 - E:\nodejs10.15.3\npm.CMD
	"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@tarojs/components": "3.0.0-rc.3",
		"@tarojs/react": "3.0.0-rc.3",
		"@tarojs/runtime": "3.0.0-rc.3",
		"@tarojs/taro": "3.0.0-rc.3",
		"immer": "^6.0.9",
		"mobx": "^4.8.0",
		"mobx-react": "^6.1.4",
		"react": "^16.10.0",
		"react-dom": "^16.10.0",
		"sleep-promise": "^8.0.1",
		"use-immer": "^0.4.0"
	},
	"devDependencies": {
		"@types/webpack-env": "^1.13.6",
		"@types/react": "^16.0.0",
		"@tarojs/mini-runner": "3.0.0-rc.3",
		"@babel/core": "^7.8.0",
		"@tarojs/webpack-runner": "3.0.0-rc.3",
		"babel-preset-taro": "3.0.0-rc.3",
		"eslint-config-taro": "3.0.0-rc.3",
		"eslint": "^6.8.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react-hooks": "^1.6.1",
		"stylelint": "9.3.0",
		"@typescript-eslint/parser": "^2.x",
		"@typescript-eslint/eslint-plugin": "^2.x",
		"typescript": "^3.7.0"
	}
### 补充信息
我看了下 d.ts `RouterInfo.params` 的定义:
```js
{
  [key: string]: string
} & {
  scene?: number | string
  query?: {[key: string]: string} | string
  shareTicket?: string
  referrerInfo?: {[key: string]: any} | string
}
```
然后在 `RouterParams` 补充在 & 之后的随便一条才不会报错, 比如:
```js
```js
interface RouterParams{
  phone?: string
  shareTicket?: string
}
```
为什么要这样

**Comment by luckyadam** [comment]
类型不是已经定义好了么，为什么还要自己定义

**Comment by cncolder** [comment]
```tsx
type RouterParams = Taro.RouterInfo['params'] & {
    phone?: string
}
const params: RouterParams = Taro.useRouter().params
params.phone
```
