### ISSUE TITLE
今后是否考虑对华为WeLink小程序的支持？

### ISSUE THREAD

**Issue by Zach-Ma** [NervJS/taro#6531]

**Comment by luckyadam** [comment]
这是啥。

**Comment by DLCnow** [comment]
是一个华为的办公产品，类似钉钉，现在很多B端用户和政府喜欢用这个，体量也挺大的，希望支持

**Comment by Chen-jj** [comment]
@DLCnow 3.1 之后开发者可以自己编写端平台的插件来对任何小程序平台进行支持了：https://nervjs.github.io/taro/docs/next/platform-plugin

欢迎贡献～
