### ISSUE TITLE
3.0.0 beta5 不会将src下其他目录同步编译到dist里

### ISSUE THREAD

**Issue by c690554125** [NervJS/taro#6532]
Taro-cli beta5，在app.config.ts中配置tabBar，里面icon地址引用了src/assets/tabBar/xxx.png，编
译，dist目录里并没有将assets文件夹同步拷贝过来。

因为我看了下1.3.9版本taro，dist目录里有assets，还有其他的一些自定义文件夹，都有编译到dist里。是3.0.0不是这个用法吗？

![image](https://user-images.githubusercontent.com/13865568/83394949-12413100-a42c-11ea-9106-486ab61807d5.png)

![image](https://user-images.githubusercontent.com/13865568/83394722-a363d800-a42b-11ea-805a-4af1b976d403.png)

**Comment by c690554125** [comment]
我的问题...引用路径地址写错了
应该是'./assets'   😭

**Comment by Garfield550** [comment]
🤔 你有没有遇到编译时的错误提示？

**Comment by c690554125** [comment]
> 🤔 你有没有遇到编译时的错误提示？

没有遇到你说的错误提示。我这个问题是因为我个人写错了静态资源引用地址导致的。
