### ISSUE TITLE
scss 中使用混合宏写法，导致scss 文件过大

### ISSUE THREAD

**Issue by hujialianghuwei** [NervJS/taro#6538]
1.定义并且引入全局mixin.scss 
2.在页面scss 文件中使用
3.发现使用了混合宏写法的scss 文件过大 去掉之后scss 文件大小正常 
 怎么解决？

**Comment by luckyadam** [comment]
使用范例贴一下

**Comment by Songkeys** [comment]
@luckyadam 

```scss
@import "_scheme.scss";
```

每次 import 其他样式文件，就会导致注入一次。最终生成的页面 wxss 里，会有多个重复声明的样式。

![image](https://user-images.githubusercontent.com/22665058/85526040-8fae2a80-b601-11ea-8251-d91f50ad04f6.png)

同样的情况出现在用 sass.resource 配置后的生成文件。不知有没有去重的办法？

**Comment by happyjosh** [comment]
这么关闭了？请问怎么解决的呢？
