### ISSUE TITLE
(H5版中)Input组件onConfirm事件无效

### ISSUE THREAD

**Issue by tiancheng2000** [NervJS/taro#654]
**问题描述**
H5版的`<Input>`不支持`onConfirm`，因属常用控件，对开发带来较大不便。

**复现步骤**
1. 代码中用到`<Input>`组件，`onConfirm`事件绑定到成员方法上
2. npm run dev:h5 编译执行H5版
3. `<Input>`中输入文字后回车，`onConfirm`并未被激发

**期望行为**
H5版`<Input>`尽快支持`onConfirm`，或者文档中补充下替代方案（参见补充信息）

**报错信息**
n/a

**系统信息**
 - 操作系统: Windows 10
 - Taro 版本 v.1.0.0
 - Node.js 版本 v10.9.0

**补充信息（临时回避方法）**
目前，通过`<Input>`外围追加`<Form>`组件可回避这个H5版问题，能在输入文字回车后响应`<Form>`的`onSubmit`事件。

**Comment by ZengMX** [comment]
const input = document.querySelector('input[type="search"]');

input.addEventListener("search", () => {
  console.log(`The term searched for was ${input.value}`);
});

通过底层的监听事件可以解决这个问题
