### ISSUE TITLE
swiper 异步数据更新的时候，第二张之后的图展示不出来[Taro 3.0.0-rc.3]

### ISSUE THREAD

**Issue by kala888** [NervJS/taro#6540]
Taro 3.0.0-rc.3

![image](https://user-images.githubusercontent.com/1215976/83491168-e97c7280-a4e3-11ea-806e-22fa89fe50ea.png)

示例代码：https://github.com/kala888/nice-router-taro/blob/swiper-test/src/pages/home/home-page.jsx
可以切到: swiper-test这个branch

经过测试，看起来和初始化数据有点关心
```
  const { slideList = defaultSlideList } = root // 这样有问题，第二张开始，都没展示出来
  // const { slideList = [] } = root  // 这样写就没问题

```

**Comment by Chen-jj** [comment]
@kala888 先加 key walkaround 吧 #6179
