### ISSUE TITLE
执行npm install 安装其他任何包的时候, Taro的一些核心包会被Remove 删除掉, 导致项目报错

### ISSUE THREAD

**Issue by Cedric-hub** [NervJS/taro#6542]
操作步骤:

1. 使用Taro init 初始化Taro项目
2. npm run dev:h5运行H5项目
3. npm install 安装任何包, 然后不做任何操作...Taro部分核心包被Remove
4. 项目报错

我这里有录制操作视频, 具体操作可以查看
[Taro 安装包时部分核心包被移除](https://cedric.cowtransfer.com/s/f8c83ae62e0540)

这里以dva-core为演示, 实际上我们在和同事做技术预演时 随便安装一个包都会出现这样的情况

**版本信息**
Taro v2.2.6

@smoothdvd @guotie @Leechael @weakish @cncolder

**Comment by luckyadam** [comment]
应该是你的 node 环境问题，跟 Taro 没什么关系，可以删除 node_modules 然后重新安装依赖

**Comment by Cedric-hub** [comment]
> 应该是你的 node 环境问题，跟 Taro 没什么关系，可以删除 node_modules 然后重新安装依赖

并不能解决问题
