### ISSUE TITLE
在win10下，2.2.6以前版本的脚手架会出现：项目初始化编译 找不到项目配置文件config/index

### ISSUE THREAD

**Issue by ghostogre** [NervJS/taro#6556]
RT。
昨天遇到的问题，公司用的2.2.4，我用的2.2.6，换成2.2.4以前的就会找不到配置文件，换回2.2.6就好了。

win10下遇到的问题，其他系统版本尚不清楚。2.2.6版本的脚手架开发2.2.4的项目能正常运行，遇到这个问题的朋友可以尝试2.2.6版本

提个ISSUE帮助遇到这个问题的朋友

**Comment by luckyadam** [comment]
用 2.2.6 吧
