### ISSUE TITLE
百度小程序代码混写下，page 的 json配置在编译后会变为component

### ISSUE THREAD

**Issue by PatrickSR** [NervJS/taro#6559]
### 问题描述
Taro2.2.5里，工程中有百度原生小程序代码作为页面，在编译后的dist目录下发现，原生小程序页面代码的json配置会增加component:true，到时该原生小程序页面无法被识别

### 复现步骤

1. 新建工程，taro init xxx
2. 编写原生页面（.swan .css .js .json）
3. 修改app.js，增加刚刚的原生页面地址
4. npm run dev:swan 或者 npm run build:swan
5.查看dist/下的原生页面json，发现增加了component:true

### 期望行为
原生小程序的页面json应按照原生json为准

### 报错信息
无

### 系统信息

👽 Taro v2.2.5

  Taro CLI 2.2.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      @tarojs/components: 2.2.5 => 2.2.5
      @tarojs/components-qa: 2.2.5 => 2.2.5
      @tarojs/mini-runner: 2.2.5 => 2.2.5
      @tarojs/router: 2.2.5 => 2.2.5
      @tarojs/taro: 2.2.5 => 2.2.5
      @tarojs/taro-alipay: 2.2.5 => 2.2.5
      @tarojs/taro-h5: 2.2.5 => 2.2.5
      @tarojs/taro-qq: 2.2.5 => 2.2.5
      @tarojs/taro-quickapp: 2.2.5 => 2.2.5
      @tarojs/taro-rn: 2.2.5 => 2.2.5
      @tarojs/taro-swan: 2.2.5 => 2.2.5
      @tarojs/taro-tt: 2.2.5 => 2.2.5
      @tarojs/taro-weapp: 2.2.5 => 2.2.5
      @tarojs/webpack-runner: 2.2.5 => 2.2.5
      eslint-config-taro: 2.2.5 => 2.2.5
      eslint-plugin-taro: 2.2.5 => 2.2.5
      nerv-devtools: ^1.5.5 => 1.5.7
      nervjs: ^1.5.5 => 1.5.7
      stylelint-config-taro-rn: 2.2.5 => 2.2.5
      stylelint-taro-rn: 2.2.5 => 2.2.5
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by PatrickSR** [comment]
找到解决方法，把Page()构建器改为Component()即可。

**Comment by znchen1989** [comment]
@PatrickSR 这个问题有解决吗，独立分包后的页面又会报这个错误
