### ISSUE TITLE
【bug】定义了behaviors，但是没有执行呢

### ISSUE THREAD

**Issue by teapot-py** [NervJS/taro#656]
**问题描述**
[问题描述：因为有一些特殊的需求，要用到behaviors，看taro从beta8版本开始支持，但是定义后没有生效]

**复现步骤**
[复现问题的步骤]
1. 定义behaviors
```js
const logBehavior = Behavior({
  componentWillMount() {
    console.log('**********')
  },
  componentDidMount() {
    console.log('****+++****')
  }
})

export default logBehavior
```
2. 在组件中引入
```js
import logBehavior from '../../behaviors/logBehavior'
class Home extends Component {
  static behaviors = [ logBehavior ]
}
```

**期望行为**
期望生命周期方法执行，但是并木优。。。

**报错信息**
没有报错

**系统信息**

 - 操作系统: [mac]
 - Taro 版本 [1.0.0-beta.26]
 - Node.js 版本 [v8.11.3]

**Comment by Simbachen** [comment]
这里的 behaviors 是小程序原生的 behaviors ，支持小程序原生的生命周期，例如：attached。
1、如果需要引用内置 behaviors ，例如：wx://form-field ，就可以这么用。
2、如果是继承 Taro 提供的生命周期，建议通过类的继承的方式来实现。
