### ISSUE TITLE
build:rn或者dev:rn时Cannot find module 'babel-plugin-transform-jsx-to-stylesheet'

### ISSUE THREAD

**Issue by zzxqd** [NervJS/taro#6560]
### 问题描述
使用 Taro v3.0.0-rc.3 cli开发生成rn端时会报 UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-plugin-transform-jsx-to-stylesheet' 手动安装后依然无用

### 复现步骤
使用taro v3-rc3 初始化一个项目react-ts-默认模板的项目之后，直接dev:rn或者build:rn就会触发

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

正常dev,build rn端
### 报错信息

> Executing task: npm run build:rn <

> orenda-omni-taro@1.0.0 build:rn /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro
> taro build --type rn

👽 Taro v3.0.0-rc.3

编译  TS        /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/src/app.config.ts
编译  TS        /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/src/app.ts
拷贝  HTML      /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/src/index.html
生成  HTML      /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/rn_temp/index.html
编译  TS        /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/src/pages/index/index.config.ts
编译  TSX       /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/src/pages/index/index.tsx
(node:16731) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-plugin-transform-jsx-to-stylesheet'
Require stack:
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/rn/transformJS.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/rn.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/presets/platforms/rn.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/utils/index.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/Kernel.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/dist/index.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/node_modules/@tarojs/service/index.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/cli.js
- /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/bin/taro
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.parseJSCode (/home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/src/rn/transformJS.ts:624:6)
    at Compiler.<anonymous> (/home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/src/rn.ts:196:31)
    at Generator.next (<anonymous>)
    at /home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/rn.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/rn.js:4:12)
(node:16731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:16731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Terminal will be reused by tasks, press any key to close it.

### 系统信息

👽 Taro v3.0.0-rc.3
  Taro CLI 3.0.0-rc.3 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/mini-runner: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/react: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/runtime: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/taro: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/webpack-runner: 3.0.0-rc.3 => 3.0.0-rc.3 
      babel-preset-taro: 3.0.0-rc.3 => 3.0.0-rc.3 
      eslint-config-taro: 3.0.0-rc.3 => 3.0.0-rc.3 
      react: 16.3.1 => 16.13.1 

### 补充信息

使用doctor的时候得到以下信息
  [✗] 使用到的依赖 @tarojs/components-rn 还没有安装
  [✗] 使用到的依赖 @tarojs/taro-rn 还没有安装
  [✗] 使用到的依赖 @tarojs/taro-router-rn 还没有安装
  [✗] 使用到的依赖 @tarojs/taro-redux-rn 还没有安装
  [✗] 使用到的依赖 react-native 还没有安装
  [✗] 使用到的依赖 redux 还没有安装
  [✗] 使用到的依赖 /mnt/c/Users/xxzx2/VSCode Project/orenda-omni-taro/node_modules/babel-eslint/lib/index.js 还没有安装
  [!] 依赖 @tarojs/react 可更新到最新版本 null，当前安装版本为 3.0.0-rc.3
  [!] 依赖 @tarojs/runtime 可更新到最新版本 null，当前安装版本为 3.0.0-rc.3
  [!] Taro 3 不再依赖 @tarojs/components-rn，可以从 package.json 移除
  [!] Taro 3 不再依赖 @tarojs/taro-rn，可以从 package.json 移除
  [!] Taro 3 不再依赖 @tarojs/taro-router-rn，可以从 package.json 移除
  [!] Taro 3 不再依赖 @tarojs/taro-redux-rn，可以从 package.json 移除

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Pines-Cheng** [comment]
Taro v3.0 还不支持 RN 端。

**Comment by mattlin** [comment]
@Pines-Cheng  use Taro v3.0.5 meets the same problem

**Comment by io-o** [comment]
卧槽，不支持  文档不标明么？  yarn  npm  cnpm 搞了一天。。。

**Comment by zhuchuanwu** [comment]
> 卧槽，不支持 文档不标明么？ yarn npm cnpm 搞了一天。。。

赞

**Comment by supercharleszhu** [comment]
请问什么时候开始支持rn端？或者有没有贡献的方式

**Comment by yaoyi601131548** [comment]
taro v3.0.6 也报这个错，该怎么解决。。。

**Comment by eneisyou** [comment]
taro v4.0.6 现在也报错, 希望完善一下文档
