### ISSUE TITLE
更新components组件，控制台提示编译成功，但在微信开发者工具访问组件报错。

### ISSUE THREAD

**Issue by Yana5417** [NervJS/taro#6561]
### 问题描述
我当前是开发状态（`dev:weapp`），此时在组件里修改了文件内容。这时控制台显示编译成功，但我在开发者工具访问引入了此组件的页面时报错，报错信息如下：
![image](https://qnimage.bamaying.com/69545d5702f57f96abfde8800ee2ebc2.jpeg?updated_at=1591252389822)

同样地，我在执行`npm run build:weapp`之后，此时不重新`npm run build:dev`，也会出现在开发者工具页面进去空白的问题。

**Comment by Chen-jj** [comment]
@Yana5417 提供一下版本和可复现代码

**Comment by Yana5417** [comment]
> @Yana5417 提供一下版本和可复现代码



> @Yana5417 提供一下版本和可复现代码

版本是2.0.5

**Comment by Yana5417** [comment]
> @Yana5417 提供一下版本和可复现代码

版本是2.0.5

**Comment by Yana5417** [comment]
> @Yana5417 提供一下版本和可复现代码

我刚试了一下，好像是编译的时候文件重命名的原因，具体我还没找到你们源码里面在哪里配置的～

**Comment by Chen-jj** [comment]
提供一下demo？

**Comment by Yana5417** [comment]
> 提供一下demo？

我这边demo不是很好发出来耶，我跟你说一下，你用2.0.5版本自己拉一个项目，我试了下，100%复现。下面是复现步骤：

1.  将taro-cli版本切换到2.0.5，然后`taro init xxx` && `cd xxx`;
2. 在src创建components目录，并新建TestComponents组件；
3.  pages/index/index.tsx中引入TestComponents；

**Comment by Yana5417** [comment]
> 提供一下demo？

猜测是dist文件里面的命名触发的，见下图：
![image](https://qnimage.bamaying.com/307c5b90e1172773cf6ff90656eec282.jpeg?updated_at=1591349646287)
