### ISSUE TITLE
[Taro 2.2.6] taro build命令的--env参数无效

### ISSUE THREAD

**Issue by yzyanchao** [NervJS/taro#6570]
### 问题描述
运行如下命令编译工程：
taro build --type weapp --watch --env myEnv
编译完成后，程序中能拿到的process.env.NODE_ENV仍然是development而不是myEnv

事实上，在https://github.com/NervJS/taro/issues/6441 这个issue中，你们已经修复了Taro3 RC.0中的同样问题。希望能在Taro 2.2.x（x >7）中也修复这个问题。

### 复现步骤
1. 通过taro build --type weapp --watch --env myEnv编译工程
2. 在编译好的工程中打印process.env.NODE_ENV

### 期望行为

process.env.NODE_ENV是myEnv

### 报错信息

process.env.NODE_ENV是development

### 系统信息

Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6 
      @tarojs/mini-runner: 2.2.6 => 2.2.6 
      @tarojs/plugin-babel: 2.2.6 => 2.2.6 
      @tarojs/plugin-csso: 2.2.6 => 2.2.6 
      @tarojs/plugin-sass: 2.2.6 => 2.2.6 
      @tarojs/plugin-uglifyjs: 2.2.6 => 2.2.6 
      @tarojs/redux: 2.2.6 => 2.2.6 
      @tarojs/redux-h5: 2.2.6 => 2.2.6 
      @tarojs/router: 2.2.6 => 2.2.6 
      @tarojs/taro: 2.2.6 => 2.2.6 
      @tarojs/taro-alipay: 2.2.6 => 2.2.6 
      @tarojs/taro-h5: 2.2.6 => 2.2.6 
      @tarojs/taro-swan: 2.2.6 => 2.2.6 
      @tarojs/taro-tt: 2.2.6 => 2.2.6 
      @tarojs/taro-weapp: 2.2.6 => 2.2.6 
      @tarojs/webpack-runner: 2.2.6 => 2.2.6 
      eslint-config-taro: 2.2.6 => 2.2.6 
      eslint-plugin-taro: 2.2.6 => 2.2.6 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      stylelint-config-taro-rn: 2.2.6 => 2.2.6 
      stylelint-taro-rn: 2.2.6 => 2.2.6 
      taro-ui: ^2.2.1 => 2.2.1 

### 补充信息
无

**Comment by Spencer17x** [comment]
npm包不能发同一版本，只能通过升级去解决呀。

**Comment by yzyanchao** [comment]
> npm包不能发同一版本，只能通过升级去解决呀。

似乎回复错对象了吧

**Comment by Spencer17x** [comment]
就是回复你的呀...2.2.6已经发布了，怎么可能还在2.2.6修复这个问题呢...

**Comment by yzyanchao** [comment]
> 就是回复你的呀...2.2.6已经发布了，怎么可能还在2.2.6修复这个问题呢...

因为我建这个issue的时候还是2.2.6。行，我改一下标题吧
