### ISSUE TITLE
其他组件的 onTap 先于 Input 的 onBlur 事件执行 如何解决

### ISSUE THREAD

**Issue by afishhhhh** [NervJS/taro#6573]
### 问题描述

```js
// MyComponent.jsx
handleCheck (index) {
    console.log('handleCheck')
    this.props.onCheck(index)
}
handleBlur ({ detail: { value } }) {
    console.log('handleBlur')
    this.props.onBlur(index, value.trim())
}
```
`MyComponent` 组件里有一个勾选框和输入框，输入框失去焦点的时候触发 `handleBlur`，把最新的 `value` 传给父组件，父组件会有一次 `setState`。点击勾选框的时候父组件会对 `value` 做一些逻辑上的处理，然后执行 `setState`。但是如果输入框没有失去焦点，而是直接点击勾选框，`onCheck` 就会先于 `onBlur` 执行，这样的话父组件因为没有得到最新的 `value` 没办法做一些处理，请问这个如何解决？我在 `handleCheck` 里试了 `setTimeout` 没有什么效果

**Comment by psaren** [comment]
0、把点击事件改为 onTouchStart, 这将快过 blur
或者考虑
1、onBlur 改为 onChange

**Comment by afishhhhh** [comment]
我给写错顺序了。。。现在的才是对的 @psaren

**Comment by psaren** [comment]
那你最好可以提供一个可复现的repo，
最少是代码，版本，环境这些需要提供以便分析
