### ISSUE TITLE
第一次运行npm run dev:rn 就报错了

### ISSUE THREAD

**Issue by 82253452** [NervJS/taro#658]
**问题描述**
[问题描述：npm run dev：run报错]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]
(node:7348) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: TypeError: Cannot read property 'entry' of undefined
(node:7348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 7]
 - Taro 版本 [e.g. v.1.0.2]
 - Node.js 版本 [e.g. v8.9.4]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]
是我的node版本太低么？？？

**Comment by luckyadam** [comment]
选了 less 么

**Comment by 82253452** [comment]
less构建项目的时候选了，没有选Typescript这个有影响么

**Comment by zixiao0306** [comment]
相同的问题，css预处理器选的Stylus，编译完app.styl后就报错了

**Comment by luckyadam** [comment]
@82253452 less 有点问题，已经修复了，下个版本可以~

**Comment by luckyadam** [comment]
@zixiao0306 Stylus 也是，下个版本可以~

**Comment by 82253452** [comment]
改成sass 构建重新运行可以了

**Comment by Pines-Cheng** [comment]
https://github.com/NervJS/taro/issues/650
