### ISSUE TITLE
小程序编译后生成的base.wxml文件里没有button、webview、scrollview等组件

### ISSUE THREAD

**Issue by jiujiuGit** [NervJS/taro#6580]
报错信息：
./base.wxml
 Template `tmpl_4_button` not found.
  163 | 
  164 | <template name="tmpl_4_container" data="{{i: i}}">
> 165 |   <template is="{{'tmpl_4_' + i.nn}}" data="{{i: i}}" />
      |                ^
  166 | </template>
  167 | 
  168 | <template name="tmpl_5_view">

**Comment by yuche** [comment]
你是怎么写的代码，是 vue 还是 react

**Comment by skyvow** [comment]
遇到一样问题，太辣鸡，最简单 demo 都跑不起来

**Comment by elvinzhu** [comment]
同样也是报
·VM44:1 WXMLRT_$gwx:./base.wxml:template:85:16: Template `tmpl_1_button` not found.·

使用react

**Comment by qhhsy** [comment]
我的没有textarea和radio

**Comment by guohuihot** [comment]
解决了吗？
