### ISSUE TITLE
编译多平台组件时，生成的json文件没有加上平台的前缀

### ISSUE THREAD

**Issue by lentoo** [NervJS/taro#6585]
### 问题描述

编译多平台组件时，生成的json文件没有加上平台的前缀

### 复现步骤

1. 例如有一个buy-course 组件
组件目录结构是：
![image](https://user-images.githubusercontent.com/24666230/83858578-4c257680-a74f-11ea-8a39-2e3d7dda9a97.png)
针对微信平台有一个单独的 buy-course.weapp.js文件
2. 
正常引入组件`import BuyCourse from '../components/buy-course'`
通过taro进行编译时 `npm run build:weapp`，

3. 生成的组件目录没有生成 index.weapp.json
![image](https://user-images.githubusercontent.com/24666230/83859107-0e751d80-a750-11ea-80cc-f2df18fb0f74.png)
4. 微信开发者工具提示报错 
![image](https://user-images.githubusercontent.com/24666230/83859138-19c84900-a750-11ea-9ab3-7ebad599b8cc.png)

### 期望行为

生成对应平台的json文件，如案例的：index.weapp.json

### 报错信息

![image](https://user-images.githubusercontent.com/24666230/83859427-80e5fd80-a750-11ea-9d8c-4482eab0b611.png)

### 系统信息

  Taro CLI 2.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.18.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.1.0 => 2.1.0
      @tarojs/components-qa: 2.1.0 => 2.1.0
      @tarojs/mini-runner: 2.1.0 => 2.1.0
      @tarojs/router: 2.1.0 => 2.1.0
      @tarojs/taro: 2.1.0 => 2.1.0
      @tarojs/taro-alipay: 2.1.0 => 2.1.0
      @tarojs/taro-h5: 2.1.0 => 2.1.0
      @tarojs/taro-qq: 2.1.0 => 2.1.0
      @tarojs/taro-quickapp: 2.1.0 => 2.1.0
      @tarojs/taro-rn: 2.1.0 => 2.1.0
      @tarojs/taro-swan: 2.1.0 => 2.1.0
      @tarojs/taro-tt: 2.1.0 => 2.1.0
      @tarojs/taro-weapp: 2.1.0 => 2.1.0
      @tarojs/webpack-runner: ^3.0.0-beta.3 => 3.0.0-beta.3
      eslint-config-taro: 2.1.0 => 2.1.0
      eslint-plugin-taro: 2.1.0 => 2.1.0
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.1.0 => 2.1.0
      stylelint-taro-rn: 2.1.0 => 2.1.0
      taro-ui: ^2.3.2 => 2.3.3

**Comment by luckyadam** [comment]
升级到 2.2.7 试试

**Comment by lentoo** [comment]
有人处理一下吗？？
