### ISSUE TITLE
[Taro 2.2.7] 使用Jest做单元测试，无法mock Taro的api函数，比如Taro.getSetting

### ISSUE THREAD

**Issue by yzyanchao** [NervJS/taro#6586]
### 问题描述

在Taro 2.2.7版本中，使用Jest做单元测试，无法mock Taro的api函数，比如Taro.getSetting。
但相同写法在Taro.1.3.10版本可以正确mock

### 复现步骤
1. 这是一个微信小程序工程，根据Taro的文档配置好了Jest测试环境，并且在1.3.10版本下可以正确运行单元测试
2. 根据Taro文档，升级到2.2.7版本，修改配置后，能正确编译运行微信小程序
3. 运行npm run build:h5编译出h5的中间代码
4. 运行jest --coverage跑单元测试

举个例子，下图是Taro 2.2.7编译出的中间代码，也就是要测试的函数
<img width="709" alt="Screen Shot 2020-06-05 at 9 46 00 PM" src="https://user-images.githubusercontent.com/1940843/83883374-f7e1bd00-a775-11ea-958e-3cc7e4cad15d.png">

针对上面函数的测试用例：
<img width="531" alt="Screen Shot 2020-06-05 at 9 46 53 PM" src="https://user-images.githubusercontent.com/1940843/83883461-147df500-a776-11ea-99e2-50237c57707e.png">

这个测试会报错：ReferenceError: _getSetting is not defined

而相同的测试在Taro 1.3.10却可以成功。经对比发现，1.3.10版本的中间代码是：
<img width="406" alt="Screen Shot 2020-06-05 at 9 49 10 PM" src="https://user-images.githubusercontent.com/1940843/83883780-88200200-a776-11ea-97dd-4c47c3421d2e.png">

明显两个版本调用taro api的方式不同，1.3.10的中间代码都是通过Taro.getSetting()这样的方式调用api，而2.2.7版本的中间代码给getSetting取了别名_getSetting，然后调用_getSetting()。这就导致了mock失败。

请问如何才能成功运行这种单元测试？

### 期望行为

mock taro api能成功

### 报错信息
测试用例报错：
ReferenceError: _getSetting is not defined

### 系统信息

👽 Taro v2.2.7

  Taro CLI 2.2.7 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.7 => 2.2.7 
      @tarojs/mini-runner: 2.2.7 => 2.2.7 
      @tarojs/plugin-babel: 2.2.7 => 2.2.7 
      @tarojs/plugin-csso: 2.2.7 => 2.2.7 
      @tarojs/plugin-sass: 2.2.7 => 2.2.7 
      @tarojs/plugin-uglifyjs: 2.2.7 => 2.2.7 
      @tarojs/redux: 2.2.7 => 2.2.7 
      @tarojs/redux-h5: 2.2.7 => 2.2.7 
      @tarojs/router: 2.2.7 => 2.2.7 
      @tarojs/taro: 2.2.7 => 2.2.7 
      @tarojs/taro-alipay: 2.2.7 => 2.2.7 
      @tarojs/taro-h5: 2.2.7 => 2.2.7 
      @tarojs/taro-swan: 2.2.7 => 2.2.7 
      @tarojs/taro-tt: 2.2.7 => 2.2.7 
      @tarojs/taro-weapp: 2.2.7 => 2.2.7 
      @tarojs/webpack-runner: 2.2.7 => 2.2.7 
      eslint-config-taro: 2.2.7 => 2.2.7 
      eslint-plugin-taro: 2.2.7 => 2.2.7 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      stylelint-config-taro-rn: 2.2.7 => 2.2.7 
      stylelint-taro-rn: 2.2.7 => 2.2.7 
      taro-ui: ^2.2.1 => 2.3.4 

### 补充信息

无

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-ui/blob/dev/babel.config.js#L2
请看一下这个文件，安装 `@tarojs/taro-h5/dist/taroApis` 这个包，然后在 babel 里配置一下

**Comment by yzyanchao** [comment]
> https://github.com/NervJS/taro-ui/blob/dev/babel.config.js#L2
> 请看一下这个文件，安装 `@tarojs/taro-h5/dist/taroApis` 这个包，然后在 babel 里配置一下

谢谢。
查出来是另外的原因：
1. mock Taro api的方式不对，应该按照jest的文档写
2. 跟babel-plugin-rewire冲突了，删掉就行了
