### ISSUE TITLE
使用Image mode="widthFix" 时可能导致图片下部留空

### ISSUE THREAD

**Issue by LoveofRedMoon** [NervJS/taro#6589]
![image](https://user-images.githubusercontent.com/35391556/83936856-12f61080-a7fa-11ea-97d5-a5a5f248ee5f.png)
这是默认情况下, 在H5模式下的展示, 实际图片下不应该留空
![image](https://user-images.githubusercontent.com/35391556/83936873-4df84400-a7fa-11ea-8afe-e4875911662f.png)

而在小程序下, 展示未留空, 导致效果不一致
![image](https://user-images.githubusercontent.com/35391556/83936877-5ea8ba00-a7fa-11ea-924e-aee743c5d2fc.png)
建议将图片样式由原先的height:100%改为height:initial

**Comment by iChengbo** [comment]
外层加个 flex 就行了
