### ISSUE TITLE
CLI appPath无法通过参数指定？

### ISSUE THREAD

**Issue by junxiongchu** [NervJS/taro#6591]
### 问题描述

CLI appPath无法通过参数指定

### 复现步骤

CLI构造函数支持appPath参数但入口直接new CLI().run() 也未见有appPath传入

```js
#! /usr/bin/env node

require('../dist/util').printPkgVersion()

const CLI = require('../dist/cli').default
new CLI().run()
```

```js
class CLI {
  appPath: string
  constructor (appPath) {
    this.appPath = appPath || process.cwd()
  }

  run () {
    this.parseArgs()
  }
}
```

### 期望行为

期望能在new CLI().run()时支持命令行参数手动指定具体的appPath

### 系统信息

taro cli 2.2.7

**Comment by luckyadam** [comment]
完全没懂你的问题

**Comment by junxiongchu** [comment]
> 完全没懂你的问题
@luckyadam  就是说 new CLI()的时候支持通过process.argv获取外界传入的appPath而不是一直使用process.cwd()

**Comment by luckyadam** [comment]
> > 完全没懂你的问题
> > @luckyadam  就是说 new CLI()的时候支持通过process.argv获取外界传入的appPath而不是一直使用process.cwd()

![image](https://user-images.githubusercontent.com/1782542/83998756-d9f1a380-a993-11ea-9d2d-096b051802dc.png)
这个构造函数不是允许你传参么
