### ISSUE TITLE
初始化项目报错

### ISSUE THREAD

**Issue by jas0ncn** [NervJS/taro#660]
**问题描述**
执行 `taro init xx` 命令，选择 TypeScript 和 Redux 模板，报错

**复现步骤**
1. `taro init xxx`
1. 选择使用 TypeScript
1. 选择 Redux 模板

**期望行为**
成功初始化项目

**报错信息**

![image](https://user-images.githubusercontent.com/3380894/45795493-8ecec300-bcce-11e8-8044-9b409bf8bf44.png)

**系统信息**

 - 操作系统: macOS 10.13.6
 - Taro 版本 v1.0.2
 - Node.js 版本 v10.9.0

**补充信息**
无

**Comment by jas0ncn** [comment]
查看 https://github.com/NervJS/taro/tree/master/packages/taro-cli/templates/redux 确实没有 globaldts 这个定义文件。。。

**Comment by luckyadam** [comment]
确实~ 下个版本修复，暂时可以用默认模板~
