### ISSUE TITLE
[2.2.7]: taro.component.d.ts 中 React.ReactElement 没有指定泛型类型，导致无法通过ts检查

### ISSUE THREAD

**Issue by RickyJiao** [NervJS/taro#6607]
### 背景介绍
我想在taro小程序里面使用一些自定义的react-provider。但是小程序里面没有一个root component， 不同的页面渲染在不同的上下文。在taro里面，很难像react里面一样使用provider。我参考了官方的taro-redux的实现方式，把provider的context 存放在global对象里面。考虑到这个是一个非常通用的问题，我决定把相关代码剥离成一个单独的npm module 方便其他人使用。这个是我创建的帮助类库 https://github.com/RickyJiao/taro-provider

### 问题描述
创建taro-provider帮助类库的时候，遇到了打包问题。我不太了解taro-cli是否支持把代码打包成一个npm module么? 我用了webpack+bable进行打包。

`taro.component.d.ts`无法通过ts的type check。 React.ReactElement是一个泛型接口。但是我们在`taro.component.d.ts`内没有指定任何类型，导致ts-check无法通过。参考如下截图：

<img width="854" alt="Screen Shot 2020-06-08 at 23 48 34" src="https://user-images.githubusercontent.com/2752033/84052036-97a38300-a9e2-11ea-9ecf-f3fdf8f3d9e3.png">

我目前的办法：手动修改`node_modules/@tarojs/taro/types/taro.component.d.ts`。 修改如下：
```jsx
  interface FunctionComponent<P = {}> {
    (props: PropsWithChildren<P>, context?: any): React.ReactElement<any> | null
...
```
改动完成后，可以用webpack 创建 taro的扩展库。也能在taro application import这个类库。

### 重现步骤
* `git clone https://github.com/RickyJiao/taro-provider`
* `npm install`
* `npm run build`

**Comment by Spencer17x** [comment]
这个不是taro的问题，是因为你引入的其他库的问题导致taro.component.d.ts中的interface FunctionComponent里面的React.ReactElement指向的是你node_modules/@types下的React.ReactElement了，taro定义的React.ReactElement是有给默认any类型的

**Comment by Spencer17x** [comment]
对比了下taro的，你的问题出在@types/react这个库的版本问题，改成^16.9.4就可以了。你现在的16.4.6的版本React.ReactElement是没有提供默认值的，所以报错

**Comment by RickyJiao** [comment]
@Spencer17x 谢谢你的回复。升级了@types/react的版本，这个问题已经修复好了。

默认我用taro-cli@2.2.7 初始化一个小程序的project，默认package.json里面的`@types/react`版本是`16.4.6`。
既然taro@2.2.7版本内的taro.component.d.ts和@types/react版本不兼容，是否需要升级到16.9.4？

**Comment by Spencer17x** [comment]
taro模板是 "@types/react": "^16.4.6"，而你的是 "@types/react": "16.4.6",是你自己写死了版本号...如果不lock版本，taro模板的是会自动升级到16.x.x最新版的.

**Comment by RickyJiao** [comment]
taro模板是 "@types/react": "^16.4.6"，采用了模糊匹配的版本管理。
