### ISSUE TITLE
能支持单元测试吗？？？？

### ISSUE THREAD

**Issue by gxbsst** [NervJS/taro#6608]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Spencer17x** [comment]
支持单元测试的呀，参照taro-ui。

**Comment by ariesjia** [comment]
可以试试 
https://github.com/ThoughtWorksChina/taro-testing-library

**Comment by ariesjia** [comment]
可以试试  https://github.com/ThoughtWorksChina/taro-testing-library

**Comment by scarcoco** [comment]
taro-ui  的方式可以么？先编译，在给编译的代码写单侧？

**Comment by scarcoco** [comment]
@ariesjia 这个可以，直接写 tsx 测试，不要编译流程。

**Comment by kamo9527** [comment]
@scarcoco 方便提供taro3.x 小程序项目的jest 配置和 demo么 , 非常感谢
