### ISSUE TITLE
Taro2.2.7 微信小程序 context api 表现异常

### ISSUE THREAD

**Issue by suchangv** [NervJS/taro#6611]
### 问题描述

export const CounterCounter = createContext(initState)
创建了一个Context并为其添加了默认值 initState
但是在之后使用<Counter.Provider value={anotherState}> 
这时anotherState应该会覆盖掉initState才对

### 复现步骤

相关代码如下
1.app.jsx代码

```js
import Taro, { createContext, useState } from '@tarojs/taro'
import Index from './pages/index'

import './app.scss'

const initState = {
  count: 0,
  addCount: () => {
    console.log('我是最初的 addCount')
  }
}

export const CounterContext = createContext(initState)

const App = () => {

  const [count, _addCount] = useState(0)

  const addCount = () => {
    console.log('我是覆盖后的 addCount')
    _addCount(count + 1)
  }

  return (
    <CounterContext.Provider value={{ count, addCount }}>
      <Index />
    </CounterContext.Provider>
  )
}

App.config = {
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}

Taro.render(<App />, document.getElementById('app'))

```
2. pages/index/index.jsx
```js
import Taro, { useContext } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { CounterContext } from '../../app'

const Index = () => {

  const { count, addCount } = useContext(CounterContext)

  return (
    <View>
      <Text>{count}</Text>
      <Button onClick={addCount}>add count</Button>
    </View>
  )
}

export default Index

```

### 期望行为

context 相关api和React官方表现一致

### 报错信息
![image](https://user-images.githubusercontent.com/41581056/84108456-cb1df600-aa52-11ea-9cd9-a562d1acf8b0.png)

### 系统信息

Taro v2.2

  Taro CLI 2.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - D:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD

依赖
"dependencies": {
    "@tarojs/components": "2.2.7",
    "@tarojs/components-qa": "2.2.7",
    "@tarojs/router": "2.2.7",
    "@tarojs/taro": "2.2.7",
    "@tarojs/taro-alipay": "2.2.7",
    "@tarojs/taro-h5": "2.2.7",
    "@tarojs/taro-qq": "2.2.7",
    "@tarojs/taro-quickapp": "2.2.7",
    "@tarojs/taro-swan": "2.2.7",
    "@tarojs/taro-tt": "2.2.7",
    "@tarojs/taro-weapp": "2.2.7",
    "@tarojs/taro-rn": "2.2.7",
    "babel-runtime": "^6.26.0",
    "regenerator-runtime": "0.11.1",
    "nervjs": "^1.5.5",
    "nerv-devtools": "^1.5.5"
  },

**Comment by ronffy** [comment]
@suchangv 
### 版本:
"@tarojs/taro": "2.2.7"

### 问题及解决
源码里`Provider`存在问题：
```ts
function Provider(newValue) {
  const emitter = context.emitter
  if (!emitter) {
    context.emitter = new Emitter(defaultValue)
  } else {
    emitter.set(newValue)
  }
}
```
更改为以下代码后问题解决：
```ts
function Provider(newValue) {
  if (!context.emitter) {
    context.emitter = new Emitter(defaultValue)
  }
  context.emitter.set(newValue)
}
```

### 特别附注
@tarojs/taro 从版本 3.x 开始，context 相关功能已经放弃自己定义，完全从 React 库引用了，不得不承认，就目前 taro 库的健壮性而言，这是一个明智之举 😊

#3910 #4563 #4675

**Comment by suchangv** [comment]
太感谢您了，祝Taro越来越好。
