### ISSUE TITLE
[Taro Next rc3] H5 端 无法跳转同一页面（参数不同）

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro#6612]
问题描述

 H5 端 无法跳转参数不同的同一页面

表现
[动图](http://file.mengti.cc/FhDEblZMe1i0IvJbkyUGuMyTNDcF)

### 复现步骤

[https://github.com/charmtiger/taro-test](https://github.com/charmtiger/taro-test)

### 期望行为

与小程序路由保持一致

### 系统信息

  Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.config/yarn/global/node_modules/.bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/taro: 3.0.0-rc.3 => 3.0.0-rc.3 
      @tarojs/webpack-runner: 3.0.0-rc.3 => 3.0.0-rc.3 
      eslint-config-taro: 3.0.0-rc.3 => 3.0.0-rc.3 
      react: ^16.10.0 => 16.13.1

**Comment by liusure** [comment]
遇到同样的问题，除了componentWillMount、componentDidMount以外的生命周期内获取不到Current.router.params

**Comment by charmtiger** [comment]
@liusure 我的问题主要是 无法跳转

**Comment by liusure** [comment]
> @liusure 我的问题主要是 无法跳转
直接根据新的参数渲染页面就好了

**Comment by charmtiger** [comment]
我需要历史记录的，而且 yuche 说设计上是要与小程序保持一致的

**Comment by liusure** [comment]
确实，这部分我也遇到了问题。

**Comment by kala888** [comment]
自己跳转自己可用redirectTo获取的路由变化。
我的问题是A-B-A这时候怎么处理，url变化是对的，有没有方法能监听到path变化？
