### ISSUE TITLE
3.0.0-beta.5版本 使用 taro-ui 编译报错

### ISSUE THREAD

**Issue by panfire** [NervJS/taro#6613]
### 问题描述

3.0.0-beta.5版本 使用 taro-ui 编译报错

### 复现步骤

1. 在 app.tsx 中 import { AtButton } from 'taro-ui' 和 import 'taro-ui/dist/style/index.scss'
2. `return <AtButton>按钮</AtButton>`

### 期望行为

编译成功

### 报错信息

�   编译失败.
./node_modules/taro-ui/dist/weapp/index.ts
Module not found: Can't resolve './style/index.scss' in 'F:\learn\test\node_modules\taro-ui\dist\weapp'

![image](https://user-images.githubusercontent.com/17959015/84112525-834f9c80-aa5b-11ea-8a9e-aaf4c5b3a305.png)

**Comment by feibi** [comment]
应该是taro-ui引用路径不对，把`process.env.TARO_ENV`也带上了

**Comment by sanonz** [comment]
使用 beta 版的

```bash
npm i taro-ui@next
```
