### ISSUE TITLE
将app.jsx中pages，单独提出去后，报错编译失败，缺少页面

### ISSUE THREAD

**Issue by xishanxu** [NervJS/taro#6619]
将app.jsx中pages，单独提出去后，编译失败，缺少页面
![image](https://user-images.githubusercontent.com/43942406/84181878-21734f00-aabc-11ea-9ba1-d2d8912b9afd.png)
![image](https://user-images.githubusercontent.com/43942406/84181923-2d5f1100-aabc-11ea-9c07-d362e8cbff93.png)
下面是routes.js 代码
![image](https://user-images.githubusercontent.com/43942406/84182063-66978100-aabc-11ea-8a09-0aec9d3797c4.png)
将import 换成require也是不行，将routes中路径改变了，也是不行

**Comment by xishanxu** [comment]
补充一下系统信息
yarn run dev:weapp
yarn run v1.21.1
$ npm run build:weapp -- --watch
npm WARN lifecycle The node binary used for scripts is /var/folders/gr/m30rp_td0x3dwl27sfkh3b680000gn/T/yarn--1591725272908-0.04479183751423643/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> wulizhi-oa-weapp-ui-c@1.0.0 build:weapp /Users/xingyongxu/code/xishanxu/wulizhi_project/wulizhi-oa-weapp-ui
> taro build --type weapp "--watch"

👽 Taro v2.2.5

生成  工具配置  /Users/xingyongxu/code/xishanxu/wulizhi_project/wulizhi-oa-weapp-ui/dist/project.config.json

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
🙅   编译失败.

缺少页面


监听文件修改中...

**Comment by xiyionxiong** [comment]
遇到同样的问题， 请问是否解决？  我的版本2.0.13

**Comment by eatureide** [comment]
一样，感觉只能靠node去修改app.js了
