### ISSUE TITLE
2.2.7 H5在Tab页中redirectTo其它页面会造成下一个页面空白

### ISSUE THREAD

**Issue by divcss3** [NervJS/taro#6625]
### 问题描述
在tab页redirectTo会造成下一个页面空白，而使用navigateTo则没有问题
在非tab页redirectTo则正常

### 复现步骤
https://github.com/divcss3/taro_redirectTo_bug

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by divcss3** [comment]
貌似前几个版本都没有这个bug的

**Comment by Jinxhao18** [comment]
多跳几次就会出现白页或者页面没刷新的问题，手动刷新会好。我也不知道是自己写的代码有问题，还是bug

**Comment by divcss3** [comment]
> 多跳几次就会出现白页或者页面没刷新的问题，手动刷新会好。我也不知道是自己写的代码有问题，还是bug

是的，我很慌现在。

**Comment by divcss3** [comment]
@luckyadam 大佬能看看这个问题吗？都不敢上线了。。

**Comment by ZakaryCode** [comment]
由于提供的 demo 缺失 app.tsx，手动补齐，并没能通过示例复现相关问题

> 虽然 taro 2.x 没有禁用 redirectTo 到 tabbar 页面，但是这在小程序内是禁止的，故不推荐使用 [参考文档](https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.redirectTo.html)

**Comment by divcss3** [comment]
> 由于提供的 demo 缺失 app.tsx，手动补齐，并没能通过示例复现相关问题
> 
> > 虽然 taro 2.x 没有禁用 redirectTo 到 tabbar 页面，但是这在小程序内是禁止的，故不推荐使用 [参考文档](https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.redirectTo.html)

抱歉，刚补上了app.tsx，我这个是在h5才有这个问题的，小程序没问题。
Taro跳到Tab页必须要用switchTab才可以吧？
