### ISSUE TITLE
微信小程序支持DarkMode吗

### ISSUE THREAD

**Issue by hank2718** [NervJS/taro#6629]
官方出了DarkMode模式

DarkMode 适配指南
微信从iOS客户端 7.0.12、Android客户端 7.0.13 开始正式支持 DarkMode，小程序也从基础库 v2.11.0、开发者工具 1.03.2004271 开始，为开发者提供小程序内的 DarkMode 适配能力。

开启 DarkMode
在app.json中配置darkmode为true，即表示当前小程序已适配 DarkMode，所有基础组件均会根据系统主题展示不同的默认样式，navigation bar 和 tab bar 也会根据下面的配置自动切换。

**Comment by xhwgood** [comment]
你这issue是不是有点问题，微信早就支持了，小程序也支持，但taro还不支持，希望能尽快更新吧
