### ISSUE TITLE
taro cli 创建项目出错

### ISSUE THREAD

**Issue by EvanJin** [NervJS/taro#663]
**问题描述**
mac os taro cli 创建 项目失败

**复现步骤**
[复现问题的步骤]
1.直接安装，taro init 创建项目

**报错信息**
![image](https://user-images.githubusercontent.com/1031636/45800741-681b8700-bce4-11e8-8e01-40c9fac62463.png)

**系统信息**

 - 操作系统: [e.g. Mac OS]
 - Taro 版本 [e.g. v1.0.2]
 - Node.js 版本 [e.g. v10.0.7]

**补充信息**
应该是cli的问题，希望早修复，没用npx，直接用的taro cli 初始化项目

**Comment by hgt803** [comment]
嘿嘿，我也是这样

**Comment by hgt803** [comment]
不用ts就好

**Comment by luckyadam** [comment]
Duplicate of #660
