### ISSUE TITLE
[Taro next]input光标位置不对

### ISSUE THREAD

**Issue by myl0204** [NervJS/taro#6632]
### 问题描述

`iOS`下，有初始值的input首次聚焦，光标会在最左边。

版本：rc.3，在**1.3.22**中试过没有这个问题。

### 复现步骤

1. 点击有文本的输入框
2. 光标位置会在最左边
3. 失焦 ，再点击，光标位置正常。

```jsx

state = {value: '我是一行文本'}

// ...

<Input value={this.state.value} onInput={this.onInput} />

```

### 期望行为

光标位置在文本末端

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by yuche** [comment]
这样能不能解决问题？
```js
<Input value={this.state.value} onInput={this.onInput} cursor={this.state.value.length} />
```

**Comment by myl0204** [comment]
> 这样能不能解决问题？
> 
> ```js
> <Input value={this.state.value} onInput={this.onInput} cursor={this.state.value.length} />
> ```

这样子光标在文本中间时候，输入会导致光标跳动吧

**Comment by fjc0k** [comment]
@Chen-jj 3.0.0-rc.6，ios 下光标依然总是在最左边。

**Comment by fjc0k** [comment]
通过 vConsole 得到如下数据：

![image](https://user-images.githubusercontent.com/13151189/85587158-1b609f00-b674-11ea-87ca-da08319a9ab1.png)

ios 下点击输入框光标必在最左边。

**Comment by fjc0k** [comment]
> 这样能不能解决问题？
> 
> ```js
> <Input value={this.state.value} onInput={this.onInput} cursor={this.state.value.length} />
> ```

yuche 大佬的方案使用后一切正常。

**Comment by SyMind** [comment]
@Chen-jj 感觉这个默认值加的没啥道理啊，cursor 属相在百度小程序是受控属性，这样导致的结果就是从文本中间删除某个字符后，光标就定位到了文本最后。

**Comment by Chen-jj** [comment]
@SyMind 不绑定默认值的话，会出现楼主提出的问题，虽然用户可以通过开发者编码实现，但框架层面处理的话不会增加心智负担和额外工作。

> 首先 cursor 属性在百度小程序是受控属性，这样导致的结果就是从文本中间删除某个字符后，光标就定位到了文本最后。

百度的话的确存在这个问题，我们把百度的 cusor 默认值去掉。

**Comment by SyMind** [comment]
@Chen-jj 我想，微信小程序的文档和百度小程序的文档中，input 组件的默认值都是 undefined。从有小程序开发经验的开发者的角度看，会对其有路径依赖吧，从这个角度将这种改动也破坏了这些人的直觉。

**Comment by Chen-jj** [comment]
> 我想，微信小程序的文档和百度小程序的文档中，input 组件的默认值都是 undefined。从有小程序开发经验的开发者的角度看，会对其有路径依赖吧，从这个角度看这种改动破坏了这些人的直觉。

没懂什么意思

> 首先 cursor 属性在百度小程序是受控属性，这样导致的结果就是从文本中间删除某个字符后，光标就定位到了文本最后。

最后定位到，也不是 cursor、selection-start、selection-end 的问题，是在百度中当 input 的 id 以 `_` （默认 id）开头时，就会和这三个属性相冲突。

模板用 sjs 处理一下 input 的 id 即可。

**Comment by SyMind** [comment]
@Chen-jj 哦哦哦，能询问一下你是如何定位到这个问题的么？

**Comment by Chen-jj** [comment]
> @Chen-jj 哦哦哦，能询问一下你是如何定位到这个问题的么？

不断调试 input 的模板属性
