### ISSUE TITLE
JSX 片段提取出来，列表循环 click 事件参数闭包问题

### ISSUE THREAD

**Issue by HongHaiyang** [NervJS/taro#6636]
### 问题描述

出现两个问题

- 列表循环 key 绑定的问题。

- 把一段 JSX 代码片段提到 `return()` 的外面，然后在 return() 里面列表循环它。

这段代码里面如果有 click 事件，会出现经典的闭包问题，及 click 传递的参数是循环代码片段的数组的最后一个元素。

期望的场景是[1,2,3] 循环渲染，点击分别是 1，2，3，但是现在点击了变成了 3，3，3。

### 复现步骤

问题 1：

```jsx
const renderPanel = (item) => {
   return <View key="item.id">{item.id}</View>;
};
// array  = [1,2,3]
return (
	<view>
	  {array.map((item) => renderPanel(item))}
  </view>
)
```

如果这样子写，把 key 绑定到renderPanel里面的 view 里面，编译之后会报警告：

>  Now you can provide attr `wx:key` for a `wx:for` to improve performance.

问题 2：

```jsx
const renderPanel = (item) => {
   return <View onClick={() => onTest(item.id)}>{item.id}</View>;
};
const onTest = (id)=>{
  console.log(id) // 3
}
// array  = [1,2,3]
return (
	<view>
	  {array.map((item) => <view key="item.id">renderPanel(item)</view>)}
  </view>
)
```

这样子 onTest 点击了之后输出的都是 3。这样写应该没毛病啊。

**Comment by HuJean** [comment]
请问有解决这个问题吗？
