### ISSUE TITLE
小程序未加载页面执行构造

### ISSUE THREAD

**Issue by ycy2077** [NervJS/taro#6638]
### 问题描述
Taro项目在编译成小程序之后所有被引入pages,会在项目/分包第一次加载时执行构造.

### 复现步骤

![image](https://user-images.githubusercontent.com/15774890/84335196-ead62b00-abc6-11ea-89b6-df64207a9e1f.png)

```js
// app.tsx
config: Config = {
    pages: [
      'pages/index/index',
      'pages/index/test'
    ]
   ...
}

// test.tex
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default function Index() {
  debugger
  return (
    <View>42</View>
  )
}

```

### 期望行为

在未加载index/test的情况下,不会进入debugger

### 报错信息
在仅加载index/index的情况下,进入了debugger

### 系统信息
  Taro CLI 2.2.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.7 => 2.2.7 
      @tarojs/components-qa: 2.2.7 => 2.2.7 
      @tarojs/mini-runner: 2.2.7 => 2.2.7 
      @tarojs/redux: 2.2.7 => 2.2.7 
      @tarojs/redux-h5: 2.2.7 => 2.2.7 
      @tarojs/router: 2.2.7 => 2.2.7 
      @tarojs/taro: 2.2.7 => 2.2.7 
      @tarojs/taro-alipay: 2.2.7 => 2.2.7 
      @tarojs/taro-h5: 2.2.7 => 2.2.7 
      @tarojs/taro-qq: 2.2.7 => 2.2.7 
      @tarojs/taro-quickapp: 2.2.7 => 2.2.7 
      @tarojs/taro-swan: 2.2.7 => 2.2.7 
      @tarojs/taro-tt: 2.2.7 => 2.2.7 
      @tarojs/taro-weapp: 2.2.7 => 2.2.7 
      @tarojs/webpack-runner: 2.2.7 => 2.2.7 
      eslint-config-taro: 2.2.7 => 2.2.7 
      eslint-plugin-taro: 2.2.7 => 2.2.7 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.7 => 2.2.7 
      stylelint-taro-rn: 2.2.7 => 2.2.7 
    npmGlobalPackages:
      typescript: 3.8.3

**Comment by shenghanqin** [comment]
对呀，你仔细看看文档。taro是预加载constructor的

**Comment by ycy2077** [comment]
那如何解决此类问题
```js
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default function Index() {
  const id = Taro.useRouter().params
  fetchInfo(id) // constructor导致id为undefined,引起错误
  return (
    <View>42</View>
  )
}

```

**Comment by ycy2077** [comment]
> 对呀，你仔细看看文档。taro是预加载constructor的

那如何解决此类问题
```js
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default function Index() {
  const id = Taro.useRouter().params
  fetchInfo(id) // constructor导致id为undefined,引起错误
  return (
    <View>42</View>
  )
}
```

**Comment by luckyadam** [comment]
加个容错
