### ISSUE TITLE
Taro.memo 报错Cannot call a class as a function

### ISSUE THREAD

**Issue by ycy2077** [NervJS/taro#6639]
### 问题描述

H5h环境下 Taro.memo 报错Cannot call a class as a function

### 复现步骤

```js
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

function MyComponent() {
  return <View>42</View>
}

export default Taro.memo(MyComponent);
```

### 期望行为

不报错页面正常显示

### 报错信息

![image](https://user-images.githubusercontent.com/15774890/84337610-9170fa80-abcc-11ea-9883-17369515af79.png)

### 系统信息

  Taro CLI 2.2.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.7 => 2.2.7 
      @tarojs/components-qa: 2.2.7 => 2.2.7 
      @tarojs/mini-runner: 2.2.7 => 2.2.7 
      @tarojs/redux: 2.2.7 => 2.2.7 
      @tarojs/redux-h5: 2.2.7 => 2.2.7 
      @tarojs/router: 2.2.7 => 2.2.7 
      @tarojs/taro: 2.2.7 => 2.2.7 
      @tarojs/taro-alipay: 2.2.7 => 2.2.7 
      @tarojs/taro-h5: 2.2.7 => 2.2.7 
      @tarojs/taro-qq: 2.2.7 => 2.2.7 
      @tarojs/taro-quickapp: 2.2.7 => 2.2.7 
      @tarojs/taro-swan: 2.2.7 => 2.2.7 
      @tarojs/taro-tt: 2.2.7 => 2.2.7 
      @tarojs/taro-weapp: 2.2.7 => 2.2.7 
      @tarojs/webpack-runner: 2.2.7 => 2.2.7 
      eslint-config-taro: 2.2.7 => 2.2.7 
      eslint-plugin-taro: 2.2.7 => 2.2.7 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.7 => 2.2.7 
      stylelint-taro-rn: 2.2.7 => 2.2.7 
    npmGlobalPackages:
      typescript: 3.8.3

**Comment by luckyadam** [comment]
确实是有问题，Taro 2 里不能支持，Taro 3 可以，如果还是用 Taro 2 的话，只能换个写法了
