### ISSUE TITLE
自动生成基础开发模版

### ISSUE THREAD

**Issue by Hongwing** [NervJS/taro#664]
一个小想法：`taro generate`来直接生成基础模版开发文件
* _.js
* _.scss
* ...

**Comment by luckyadam** [comment]
是说自动生成页面、组件等文件么

**Comment by hgt803** [comment]
ng玩多了

**Comment by Hongwing** [comment]
> 是说自动生成页面、组件等文件么

是的，提升效率很有必要

**Comment by luckyadam** [comment]
可以啊，有这个计划~

**Comment by Hongwing** [comment]
@luckyadam 快快着手吧
* `taro generate:weapp _file_`
* `taro generate:h5 _file_`
* `...`
