### ISSUE TITLE
"最佳开发实践"打不开

### ISSUE THREAD

**Issue by yunlovebo** [NervJS/taro#6641]
### 问题描述
Taro文档中的最佳开发实践打开报404，地址：https://taro-docs.jd.com/taro/docs/README/best-practice

**Comment by yunlovebo** [comment]
上游页面：https://taro-docs.jd.com/taro/docs/README

**Comment by yuche** [comment]
http://taro-docs.jd.com/taro/docs/best-practice/

**Comment by yuche** [comment]
close via 1f4c26e
