### ISSUE TITLE
请问可以使用css in js 方案吗？  比如styled-components

### ISSUE THREAD

**Issue by H-Sven** [NervJS/taro#6642]
请问可以使用css in js 方案吗？  比如styled-components

**Comment by luckyadam** [comment]
taro 3 可以

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/next/css-in-js

**Comment by SidneyLann** [comment]
应该说是不可以。linaria是linaria, styled-components是styled-components

**Comment by SidneyLann** [comment]
而且RN下也用不了linaria
