### ISSUE TITLE
ScrollView 的 scrollWithAnimation 属性失效

### ISSUE THREAD

**Issue by shichaohui** [NervJS/taro#6648]
### 问题描述

`ScrollView`的`scrollWithAnimation`属性，不管传什么值都会有动画，`undefined`和`false`都不行，必须不传这个参数才可以。

看了[你们的代码](https://github.com/NervJS/taro/blob/2.x/packages/taro-components/src/components/scroll-view/index.js)，你们是这样判断是否需要动画的：
```
const isAnimation = 'scrollWithAnimation' in props
```
判断只要有这个属性就会有动画。
这是不正确的，请尽快修改该问题。

### 期望行为

传入`undefined`或者`false`时无滚动动画，传入`true`才有滚动动画。

**Comment by wufeihuang** [comment]
+1，同时补充一下：
如果使用 `scrollIntoView`，h5 下始终都会有动画。

翻了下源码如下：
```js
function scrollIntoView (id) {
  document.querySelector(`#${id}`).scrollIntoView({
    behavior: 'smooth',
    block: 'center',
    inline: 'start'
  })
}
````
如果 `scrollWithAnimation` 设置为无动画时，`behavior` 应该用 `auto` 以取消动画。
