### ISSUE TITLE
不支持全局配置 useExtendedLib

### ISSUE THREAD

**Issue by laborclx** [NervJS/taro#6649]
### 问题描述

不支持全局配置 useExtendedLib
```
class App extends Component {
  config = {
    useExtendedLib: {
      'weui': true
    }
  }
```
在页面配置中添加 usingComponents
```
class Page extends Component {
  config = {
    usingComponents: {
       'mp-slideview': 'weui-miniprogram/slideview/slideview'
    }
  }
}
```
编译失败，提示未安装，报错信息见下图

### 期望行为

对通过 useExtendedLib 全局配置的组件跳过不进行编译，或可以编译成功

### 报错信息

![image](https://user-images.githubusercontent.com/3807425/84497570-a4c1ba00-ace1-11ea-89a7-77b9be026611.png)

### 系统信息

![image](https://user-images.githubusercontent.com/3807425/84497691-dfc3ed80-ace1-11ea-8bc9-4470c680bc3c.png)

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by beysong** [comment]
有没有进度。。

**Comment by suedar** [comment]
想知道 `taro` 怎么配套 `weui` 使用
