### ISSUE TITLE
yarn taro init test error

### ISSUE THREAD

**Issue by ikerlin** [NervJS/taro#6650]
### 问题描述

使用yarn 安装cli工具，初始化项目报错

### 复现步骤

```shell
$ yarn global add @tarojs/cli
$ taro init test
```

### 期望行为

成功初始化项目

### 报错信息

![image](https://user-images.githubusercontent.com/3348943/84555946-4123a500-ad52-11ea-8458-07e13c91f588.png)

### 系统信息

![image](https://user-images.githubusercontent.com/3348943/84556022-aa0b1d00-ad52-11ea-94e6-b1bec39a6319.png)

### 补充信息

node -v
v14.4.0

**Comment by shenghanqin** [comment]
@ikerlin 你可以将node版本换成10或者12试试看

**Comment by ikerlin** [comment]
> @ikerlin 你可以将node版本换成10或者12试试看

不行，问题依旧

**Comment by Chen-jj** [comment]
看路径应该不是 taro 的问题
