### ISSUE TITLE
transformer_wx_1.default is not a function并且提示缺少app配置

### ISSUE THREAD

**Issue by LadyChatterleyLover** [NervJS/taro#6652]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by shenghanqin** [comment]
请填写模板信息及截图

**Comment by LadyChatterleyLover** [comment]
![image](https://user-images.githubusercontent.com/35223515/85201035-b84ad180-b32e-11ea-80fc-3a19dc307b1c.png)
