### ISSUE TITLE
使用cli创建typescript模板，app.tsx中@connect和导出报断言错误

### ISSUE THREAD

**Issue by jianqiao0313** [NervJS/taro#6654]
已搜索文档和issue，未找到相关的解决办法。
Taro版本：2.2.7

### 问题描述

taro创建项目，使用typescript，redux。未修改任何内容。app.tsx中有断言错误，如下图
![image](https://user-images.githubusercontent.com/15814955/84592092-8db3d100-ae75-11ea-9188-af392241abf7.png)
![image](https://user-images.githubusercontent.com/15814955/84592095-95737580-ae75-11ea-91e3-1c6b9ce735bd.png)

### 复现步骤

1. taro init myApp
2. 是否需要使用TypeScript ？ Yes
3. 请选择模板 redux
4. app.tsc @ connect和export Home有断言错误

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */
import { ComponentClass } from 'react'
import Taro, { Component, Config } from '@tarojs/taro'
import { View, Button, Text } from '@tarojs/components'
import { connect } from '@tarojs/redux'

import { add, minus, asyncAdd } from '../../actions/counter'

import './index.scss'

// #region 书写注意
//
// 目前 typescript 版本还无法在装饰器模式下将 Props 注入到 Taro.Component 中的 props 属性
// 需要显示声明 connect 的参数类型并通过 interface 的方式指定 Taro.Component 子类的 props
// 这样才能完成类型检查和 IDE 的自动提示
// 使用函数模式则无此限制
// ref: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20796
//
// #endregion

type PageStateProps = {
  counter: {
    num: number
  }
}

type PageDispatchProps = {
  add: () => void
  dec: () => void
  asyncAdd: () => any
}

type PageOwnProps = {}

type PageState = {}

type IProps = PageStateProps & PageDispatchProps & PageOwnProps

interface Index {
  props: IProps;
}

@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add () {
    dispatch(add())
  },
  dec () {
    dispatch(minus())
  },
  asyncAdd () {
    dispatch(asyncAdd())
  }
}))
class Index extends Component {

    /**
   * 指定config的类型声明为: Taro.Config
   *
   * 由于 typescript 对于 object 类型推导只能推出 Key 的基本类型
   * 对于像 navigationBarTextStyle: 'black' 这样的推导出的类型是 string
   * 提示和声明 navigationBarTextStyle: 'black' | 'white' 类型冲突, 需要显示声明类型
   */
    config: Config = {
    navigationBarTitleText: '首页'
  }

  componentWillReceiveProps (nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.props.add}>+</Button>
        <Button className='dec_btn' onClick={this.props.dec}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View><Text>{this.props.counter.num}</Text></View>
        <View><Text>Hello, World</Text></View>
      </View>
    )
  }
}

// #region 导出注意
//
// 经过上面的声明后需要将导出的 Taro.Component 子类修改为子类本身的 props 属性
// 这样在使用这个子类时 Ts 才不会提示缺少 JSX 类型参数错误
//
// #endregion

export default Index as ComponentClass<PageOwnProps, PageState>


```

### 期望行为

使用VScode 打开项目不会报断言错误

### 报错信息

@connect报错信息：
类型“typeof Index”的参数不能赋给类型“ComponentClass<{ counter: any; } & { add(): void; dec(): void; asyncAdd(): void; }, any>”的参数。
  Type 'Index' is missing the following properties from type 'Component<{ counter: any; } & { add(): void; dec(): void; asyncAdd(): void; }, any, any>': context, setState, forceUpdate, state, refsts(2345)

export报错信息：
Conversion of type 'typeof Index' to type 'ComponentClass<PageOwnProps, PageState>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Index' is missing the following properties from type 'Component<PageOwnProps, PageState, any>': context, setState, forceUpdate, state, refsts(2352)

### 系统信息

👽 Taro v2.2.7

  Taro CLI 2.2.7 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
      Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.7 => 2.2.7
      @tarojs/components-qa: 2.2.7 => 2.2.7
      @tarojs/mini-runner: 2.2.7 => 2.2.7
      @tarojs/redux: 2.2.7 => 2.2.7
      @tarojs/redux-h5: 2.2.7 => 2.2.7
      @tarojs/router: 2.2.7 => 2.2.7
      @tarojs/taro-alipay: 2.2.7 => 2.2.7
      @tarojs/taro-qq: 2.2.7 => 2.2.7
      @tarojs/taro-quickapp: 2.2.7 => 2.2.7
      @tarojs/taro-swan: 2.2.7 => 2.2.7
      @tarojs/taro-tt: 2.2.7 => 2.2.7
      @tarojs/taro-weapp: 2.2.7 => 2.2.7
      @tarojs/webpack-runner: 2.2.7 => 2.2.7
      eslint-config-taro: 2.2.7 => 2.2.7
      eslint-plugin-taro: 2.2.7 => 2.2.7
      nerv-devtools: ^1.5.5 => 1.5.7
      stylelint-config-taro-rn: 2.2.7 => 2.2.7
      stylelint-taro-rn: 2.2.7 => 2.2.7

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
未能复现到该问题，可更新版本或依赖试试

**Comment by iqlong** [comment]
// @ts-ignore
@connect(({ counter: any }) => ({
  counter
}), (dispatch) => ({...
-- 眼不见，心不烦 /龇牙

**Comment by yoyo837** [comment]
> // @ts-ignore @connect(({ counter: any }) => ({ counter }), (dispatch) => ({... -- 眼不见，心不烦 /龇牙

非必要不建议` @ts-ignore`, 不然用ts的意义就没了,反而变成累赘

**Comment by boluomuma** [comment]
我是3.5.1版本,使用@connect装饰器后,onPageScroll失效了,class组件
