### ISSUE TITLE
h5 tabBar切换两个tabBar页面会同时出现

### ISSUE THREAD

**Issue by sakurahe** [NervJS/taro#6657]
### 问题描述
h5 从非TabBar页面刷新页面后返回TabBar页面，然后切换TabBar页面，两个TabBar页面会同时出现

### 复现步骤
h5 从非TabBar页面刷新页面后返回TabBar页面，然后切换TabBar页面，两个TabBar页面会同时出现
注意：该问题必须在非TabBar页面刷新后才会复现

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为
TabBar页面可以正常切换

### 报错信息
![image](https://user-images.githubusercontent.com/29187945/84610187-546a7800-aeec-11ea-9b8e-efddf117f676.png)

### 系统信息
Taro CLI 2.2.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6
      @tarojs/components-qa: 2.2.6 => 2.2.6
      @tarojs/mini-runner: 2.2.6 => 2.2.6
      @tarojs/redux: 2.2.6 => 2.2.6
      @tarojs/redux-h5: 2.2.6 => 2.2.6
      @tarojs/router: 2.2.6 => 2.2.6
      @tarojs/taro: 2.2.6 => 2.2.6
      @tarojs/taro-alipay: 2.2.6 => 2.2.6
      @tarojs/taro-h5: 2.2.6 => 2.2.6
      @tarojs/taro-qq: 2.2.6 => 2.2.6
      @tarojs/taro-quickapp: 2.2.6 => 2.2.6
      @tarojs/taro-rn: 2.2.6 => 2.2.6
      @tarojs/taro-swan: 2.2.6 => 2.2.6
      @tarojs/taro-tt: 2.2.6 => 2.2.6
      @tarojs/taro-weapp: 2.2.6 => 2.2.6
      @tarojs/webpack-runner: 2.2.6 => 2.2.6
      eslint-config-taro: 2.2.6 => 2.2.6
      eslint-plugin-taro: 2.2.6 => 2.2.6
      nerv-devtools: ^1.5.6 => 1.5.7
      nervjs: ^1.5.6 => 1.5.7
      stylelint-config-taro-rn: 2.2.6 => 2.2.6
      stylelint-taro-rn: 2.2.6 => 2.2.6
      taro-ui: ^2.3.3 => 2.3.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by sakurahe** [comment]
![image](https://user-images.githubusercontent.com/29187945/84610208-62b89400-aeec-11ea-9813-cf3d6c2bd1d5.png)

**Comment by shenghanqin** [comment]
关于tabBar的bug，我也提过类似的，请Taro h5的同学帮忙看看。 @yuche

**Comment by ZakaryCode** [comment]
在 2.2.7 中并没有复现该问题，可以先升级试试

**Comment by sakurahe** [comment]
升级到2.2.7并没有解决这个问题，还是可以复现
```
Taro CLI 2.2.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 2.2.7 => 2.2.7
      @tarojs/components-qa: 2.2.7 => 2.2.7
      @tarojs/mini-runner: 2.2.7 => 2.2.7
      @tarojs/redux: 2.2.7 => 2.2.7
      @tarojs/redux-h5: 2.2.7 => 2.2.7
      @tarojs/router: 2.2.7 => 2.2.7
      @tarojs/taro: 2.2.7 => 2.2.7
      @tarojs/taro-alipay: 2.2.7 => 2.2.7
      @tarojs/taro-h5: 2.2.7 => 2.2.7
      @tarojs/taro-qq: 2.2.7 => 2.2.7
      @tarojs/taro-quickapp: 2.2.7 => 2.2.7
      @tarojs/taro-rn: 2.2.7 => 2.2.7
      @tarojs/taro-swan: 2.2.7 => 2.2.7
      @tarojs/taro-tt: 2.2.7 => 2.2.7
      @tarojs/taro-weapp: 2.2.7 => 2.2.7
      @tarojs/webpack-runner: 2.2.7 => 2.2.7
      eslint-config-taro: 2.2.7 => 2.2.7
      eslint-plugin-taro: 2.2.7 => 2.2.7
      nerv-devtools: ^1.5.7 => 1.5.7
      nervjs: ^1.5.7 => 1.5.7
      stylelint-config-taro-rn: 2.2.7 => 2.2.7
      stylelint-taro-rn: 2.2.7 => 2.2.7
      taro-ui: ^2.3.3 => 2.3.4
```

**Comment by ZakaryCode** [comment]
方便提供一个可复现的 Demo 么？只是通过这些操作并不能复现该问题。

**Comment by sakurahe** [comment]
@ZakaryCode https://github.com/sakurahe/taro-TabBar-demo

**Comment by sakurahe** [comment]
![image](https://user-images.githubusercontent.com/29187945/84618864-019dba00-af06-11ea-9147-b88ab3c70c71.png)
这个是复现步骤

**Comment by sakurahe** [comment]
![屏幕录制2020-06-15 下午12 22 25](https://user-images.githubusercontent.com/29187945/84619255-26466180-af07-11ea-8239-697342308de9.gif)

**Comment by sakurahe** [comment]
这个问题会在什么时候更新掉啊

**Comment by sakurahe** [comment]
更新到2.2.8，该问题还存在
