### ISSUE TITLE
babel.config.js配置添加useBuiltIns: 'usage'之后报错

### ISSUE THREAD

**Issue by hisanshao** [NervJS/taro#6664]
### 问题描述

编译报错

### 复现步骤

1: 使用Taro v3.0.0-rc.4初始化项目
2: 更改babel.config.js配置文件，添加useBuiltIns: 'usage'
3: 执行yarn dev:weapp报错

```js

```

### 期望行为

编译不报错

### 报错信息

![image](https://user-images.githubusercontent.com/26359618/84620171-cf8e5700-af09-11ea-982a-c3fc5e56c5b6.png)

### 系统信息

![image](https://user-images.githubusercontent.com/26359618/84620211-efbe1600-af09-11ea-93be-5ce40ab672ff.png)

**Comment by cassie-cy** [comment]
这个解决了嘛

**Comment by wanqing19954** [comment]
同样的问题，请问怎么解决的。
