### ISSUE TITLE
触发了两次componentDidMount

### ISSUE THREAD

**Issue by XuLessReigns** [NervJS/taro#6672]
### 复现步骤

1. 打开A页面，在页面A点击按钮跳转至页面B
2. 然后点击返回箭头回到A页面
3. 触发了两次async componentDidMount()，看到了接口请求发送了两次

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

期望接口只发送一次

### 报错信息

![image](https://user-images.githubusercontent.com/22761595/84626240-5695fc00-af17-11ea-8506-0ee082787f46.png)

### 系统信息

Taro CLI 1.3.45 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.16.1 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 2.0.7 => 2.0.7 
      @tarojs/components: 2.0.7 => 2.0.7 
      @tarojs/components-qa: 2.0.7 => 2.0.7 
      @tarojs/plugin-babel: 2.0.7 => 2.0.7 
      @tarojs/plugin-csso: 2.0.7 => 2.0.7 
      @tarojs/plugin-less: 2.0.7 => 2.0.7 
      @tarojs/plugin-uglifyjs: 2.0.7 => 2.0.7 
      @tarojs/redux: 2.0.7 => 2.0.7 
      @tarojs/redux-h5: 2.0.7 => 2.0.7 
      @tarojs/router: 2.0.7 => 2.0.7 
      @tarojs/taro: 2.0.7 => 2.0.7 
      @tarojs/taro-alipay: 2.0.7 => 2.0.7 
      @tarojs/taro-h5: 2.0.7 => 2.0.7 
      @tarojs/taro-qq: 2.0.7 => 2.0.7 
      @tarojs/taro-quickapp: 2.0.7 => 2.0.7 
      @tarojs/taro-rn: 2.0.7 => 2.0.7 
      @tarojs/taro-swan: 2.0.7 => 2.0.7 
      @tarojs/taro-tt: 2.0.7 => 2.0.7 
      @tarojs/taro-weapp: 2.0.7 => 2.0.7 
      @tarojs/webpack-runner: 2.0.7 => 2.0.7 
      eslint-config-taro: 2.0.7 => 2.0.7 
      eslint-plugin-taro: 2.0.7 => 2.0.7 
      nerv-devtools: ^1.5.6 => 1.5.7 
      nervjs: ^1.5.6 => 1.5.7 
      stylelint-config-taro-rn: 2.0.7 => 2.0.7 
      stylelint-taro-rn: 2.0.7 => 2.0.7 

### 补充信息
在浏览器和开发者工具都是只发送一次请求，都是好的
手机机型： iphonexr， 系统版本13.4.1 /微信版本7.0.9    （发送1次）
但是下面的机型有问题
手机机型： iphone 7p， 系统版本12.4/微信版本7.0.12  （发送两次）

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
暂时没有好的方案去修复，这个问题只在 iOS 老版本部分应用内置浏览器内可复现。

**Comment by xudaolong** [comment]
遇到相同问题，期待处理方法。
