### ISSUE TITLE
使用Taro UI的AtTabBar在app.js中配置，如何在界面中使用？

### ISSUE THREAD

**Issue by fastener** [NervJS/taro#668]
使用Taro UI的AtTabBar在app.js中配置做底部导航栏，如何在各个界面中使用？直接配置在界面是无法显示的。

**Comment by luckyadam** [comment]
使用Taro UI的AtTabBar是无法通过配置展示的，你需要自己在页面中引用它

**Comment by hanyitim** [comment]
每次调整底部的 attabbar 都是重新渲染咯，会闪一下
