### ISSUE TITLE
[Feature request]建议某个平台不支持的api在编译的时候可以忽略而不是报错

### ISSUE THREAD

**Issue by piscdong** [NervJS/taro#6684]
### 问题描述

建议某个平台不支持的api在编译的时候可以忽略而不是报错
比如useShareAppMessage这种h5不支持的，现在需要手工通过环境判断等方式来操作，能不能直接编译成h5的时候忽略useShareAppMessage

### 复现步骤

无

### 期望行为

建议某个平台不支持的api在编译的时候可以忽略而不是报错

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by ZakaryCode** [comment]
直接判断忽略对开发者反而不够友好，需要的时候并不能准确的定位问题

只是通过一个简单判断，相对是个成本更低的方案。
