### ISSUE TITLE
2.2.8版本，按照要求配置plugins后，出现加载不出页面的情况

### ISSUE THREAD

**Issue by dreamthen** [NervJS/taro#6686]
### 问题描述

升级至2.2.8版本之后,出现必须配置plugins的提醒
![image](https://user-images.githubusercontent.com/13704681/84738367-61ff2b00-afdc-11ea-9bea-04be68b921ae.png)
即配置为以下截图所示
![image](https://user-images.githubusercontent.com/13704681/84738485-9377f680-afdc-11ea-9f45-4f3d82bd08a1.png)
执行命令后,cli没有出现问题,页面显示不出任何视图,开发者工具报错: '找不到页面'

### 复现步骤

升级至2.2.8版本之后,出现必须配置plugins的提醒
![image](https://user-images.githubusercontent.com/13704681/84738367-61ff2b00-afdc-11ea-9bea-04be68b921ae.png)
即配置为以下截图所示
![image](https://user-images.githubusercontent.com/13704681/84738485-9377f680-afdc-11ea-9f45-4f3d82bd08a1.png)
执行命令后,cli没有出现问题,页面显示不出任何视图,开发者工具报错: '找不到页面'

### 期望行为

期望如2.2.7版本一样正常

### 系统信息

macOS: 10.15.5
nodejs: 12.18.0
npm: 6.14.4
taro: 2.2.8
taro-ui: 2.3.4

**Comment by luckyadam** [comment]
你的项目依赖也需要升级到 2.2.8

**Comment by dreamthen** [comment]
@luckyadam 项目依赖升级了呀，现在升级到2.2.9还是一样

**Comment by dreamthen** [comment]
![image](https://user-images.githubusercontent.com/13704681/84854246-bd402480-b093-11ea-971e-635a9820ceb9.png)
![image](https://user-images.githubusercontent.com/13704681/84854264-c5985f80-b093-11ea-99b0-7caac8200345.png)
![image](https://user-images.githubusercontent.com/13704681/84854274-cc26d700-b093-11ea-92e2-4abe163a55de.png)

**Comment by dreamthen** [comment]
就是说我不知道怎么去使用@tarojs/plugin-less以及@tarojs/plugin-sass，有没有一个使用的api？

**Comment by luckyadam** [comment]
> 就是说我不知道怎么去使用@tarojs/plugin-less以及@tarojs/plugin-sass，有没有一个使用的api？

这两个是插件，配置就行了，没有复现你的问题，麻烦提供个 demo 看下

**Comment by dreamthen** [comment]
https://github.com/dreamthen/PetPlanet-demo

**Comment by dreamthen** [comment]
@luckyadam 上面链接，拉下master分支代码，yarn && yarn run dev:weapp即可复现

**Comment by luckyadam** [comment]
> @luckyadam 上面链接，拉下master分支代码，yarn && yarn run dev:weapp即可复现

https://github.com/dreamthen/PetPlanet-demo/blob/master/config/index.js#L49
配置有问题，丢了 taro

https://nervjs.github.io/taro/docs/config-detail#minicommonchunks

**Comment by dreamthen** [comment]
不是的呀，我把taro直接放到vendors里面了呀，如果commonsChunk有问题的话，那我2.2.7版本就会出问题呀，现在是2.2.7版本没问题呀，我下面用webpackChain自定义了一下

**Comment by dreamthen** [comment]
我不需要抽离taro chunk，所以就直接放到vendors里面了，有问题？

**Comment by dreamthen** [comment]
我不自定义配置就没有问题，那我为啥不能自定义配置splitChunks了呀？
