### ISSUE TITLE
 RN 里面config.navigationBarTitleText 不生效

### ISSUE THREAD

**Issue by szheng3** [NervJS/taro#669]
Mac version 1.0.2单独component
  config = {

    navigationBarTitleText: 'show',
  };

标题没变

**Comment by Pines-Cheng** [comment]
config 是在自定义组件里还是页面组件里 ？ @szheng3 

标题没变的意思的是：初始化是 XXX ，运行过程中修改为 YYY，但是标题还是 XXX ？

**Comment by szheng3** [comment]
在页面组件里面， 初始化是 XXX ，运行过程中修改为 YYY，但是标题还是 XXX，正解

**Comment by Pines-Cheng** [comment]
按照小程序的规范，动态设置当前页面的标题需要通过 setNavigationBarTitle(Object object) ，该 API 在 RN 端还没支持，我来给你支持一下。

**Comment by szheng3** [comment]
感谢大佬
