### ISSUE TITLE
sourcemap在小程序端还是不能用？

### ISSUE THREAD

**Issue by smoothdvd** [NervJS/taro#671]

**Comment by yuche** [comment]
还不能，这个要等我们下次对构建系统重构再做支持

**Comment by leonardoFu** [comment]
大概什么时候能支持打包产物js中带sourceMap呢？

**Comment by luckyadam** [comment]
@leonardoFu 这个周期比较久，暂时还不确定

**Comment by liudonghua123** [comment]
希望可以实现，不然不好在微信开发者工具中调试

**Comment by godbasin** [comment]
微信7.0之后，如果使用第三方框架，在代码中内敛 sourcemap 或者有同名 sourcemap 文件存在，工具会自动合并和解析，从而做到错误会显示原来文件名字和行号。

希望能早日支持sourcemap，能辅助现网问题定位，谢谢！

**Comment by hytStart** [comment]
不顺畅，调试起来。

**Comment by CodingPapi** [comment]
希望早日支持，没有sourcemap很遗憾

**Comment by shenghanqin** [comment]
@smoothdvd 可以尝试一下2.0.0 beta版本。

**Comment by fanyinghao** [comment]
进展如何？

**Comment by without-yy** [comment]
关注一下

**Comment by Chen-jj** [comment]
Taro 3 已支持 source-map
