### ISSUE TITLE
page中useReachBottom不触发

### ISSUE THREAD

**Issue by yang4515** [NervJS/taro#6711]
### 问题描述

taro3 rc4支付宝小程序hook写法的useReachBottom不触发，class写法的onReachBottom也不触发

### 复现步骤

taro init 选择 react typescript mobx，修改pages/index/index.tsx文件
```js
// /pages/index/index
import React from 'react'
import { View } from '@tarojs/components'
import { useReachBottom } from '@tarojs/taro'

export default () => {
  useReachBottom(() => console.log('reachBottom'))

  return <View style={{ height: '120vh', background: 'linear-gradient(#e66465, #9198e5)' }} />
}
```

### 期望行为

触发触底事件，做列表翻页

### 报错信息

无报错

### 系统信息

  Taro CLI 3.0.0-rc.4 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.4 => 3.0.0-rc.4
      @tarojs/mini-runner: 3.0.0-rc.4 => 3.0.0-rc.4
      @tarojs/react: 3.0.0-rc.4 => 3.0.0-rc.4
      @tarojs/runtime: 3.0.0-rc.4 => 3.0.0-rc.4
      @tarojs/taro: 3.0.0-rc.4 => 3.0.0-rc.4
      @tarojs/webpack-runner: 3.0.0-rc.4 => 3.0.0-rc.4
      babel-preset-taro: 3.0.0-rc.4 => 3.0.0-rc.4
      eslint-config-taro: 3.0.0-rc.4 => 3.0.0-rc.4
      react: ^16.10.0 => 16.13.1

**Comment by igpfpyu** [comment]
3.0.14版本也遇到了，有解决方案吗？

**Comment by qukeda** [comment]
3.3.0 版本也遇到了，只有hook写法的useReachBottom不触发，class写法的正常

**Comment by EugeneJao** [comment]
taro默认将a-page的position设置为absoute，需要把a-page的position重新覆盖成static，才能使usePageScroll和useReachBottom的hooks生效，这是深坑啊
