### ISSUE TITLE
强烈建议各个包锁版本号

### ISSUE THREAD

**Issue by liujiayii** [NervJS/taro#6714]
https://github.com/NervJS/taro/blob/151304201d37a19d7f57b21c4ac3beea47384159/packages/taro-alipay/package.json#L27
在package.json中锁定了2.2.7之后，yarn install 之后依然会安装一个最新的依赖
![image](https://user-images.githubusercontent.com/38902744/84847695-43546f00-b084-11ea-9137-865e9254a820.png)
![image](https://user-images.githubusercontent.com/38902744/84847707-49e2e680-b084-11ea-9269-3178af1f8881.png)

**Comment by luckyadam** [comment]
有道理

**Comment by cathe-zhang** [comment]
+1

**Comment by FredZeng** [comment]
有道理
