### ISSUE TITLE
文档'CSS 预处理器'中的plugin链接指向了404页面.

### ISSUE THREAD

**Issue by HZ-GeLiang** [NervJS/taro#6716]
### 问题描述
文档中url不存在

### 复现步骤
在 https://nervjs.github.io/taro/docs/styles-processor/  有一段话 "然后，在项目的 plugins 配置中引入插件"  这段话的plugins是一个a标签:<a href="/taro/docs/styles-processor/config-detail/#plugins"><code>plugins</code></a>  这个链接无效

1.打开地址 https://nervjs.github.io/taro/docs/styles-processor/
2. 点击图中红框处
![image](https://user-images.githubusercontent.com/16562680/84850342-16a35600-b08a-11ea-8267-28051ec70e4f.png)
3.可以看到提示404
![image](https://user-images.githubusercontent.com/16562680/84850379-2d49ad00-b08a-11ea-9ac8-764cf2f40346.png)
 
### 期望行为

修复文档

**Comment by Chen-jj** [comment]
已修复
