### ISSUE TITLE
npm run dev 配置对应端的 dist文件夹？swan，weapp等都保留dist，方便对比各端差异

### ISSUE THREAD

**Issue by shichuyu** [NervJS/taro#6725]
大佬们，请问下，taro能在npm run dev 小程序的时候配置好对应的不同小程序的文件夹吗？
现在每次都npm run dev加载对应的小程序，又把dist下文件删了又重新生成页面文件
比如dist下面区分  swan，weapp 等文件夹，然后方便在各个小程序端对比差距

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/envs-debug
