### ISSUE TITLE
使用sass的@use引用其它scss文件中的变量无法通过编译

### ISSUE THREAD

**Issue by zzxqd** [NervJS/taro#6728]
### 问题描述

在某一scss文件中使用@use引入并使用其他scss文件里设置的变量，在dev:h5中正常，dev:weapp时编译不通过
### 复现步骤

1.src/app.scss中设置有变量$primary-1-color:#00C8BE;
2.src/components/input.scss中@use"../app.scss" 并使用color:app.$primary-1-color;
3.dev:weapp时会报
SassError: Invalid CSS after "    color: app": expected expression (e.g. 1px, bold), was ".$primary-1-color;"
这样的错误，dev:h5无任何问题

### 期望行为

dev:weapp能通过编译

### 系统信息

Taro CLI 3.0.0-beta.5 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/webpack-runner: 3.0.0-beta.5 => 3.0.0-beta.5 
      eslint-config-taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      react: ^16.10.0 => 16.13.1 
### 补充信息
可暂时通过@import导入，直接使用导入文件中的变量 

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by XHMM** [comment]
因为 taro 对 sass 的编译用的是 `node-sass`，这个不支持模块系统， 你可以使用我写的这个简单[插件](https://github.com/XHMM/taro-plugin-dart-sass)将 `node-sass` 换成 `sass` 就可以使用模块系统了

**Comment by zzxqd** [comment]
> 因为 taro 对 sass 的编译用的是 `node-sass`，这个不支持模块系统， 你可以使用这个[插件](https://github.com/XHMM/taro-plugin-dart-sass)将 `node-sass` 换成 `sass` 就可以使用模块系统了

并不行，
👽 Taro v3.0.0-beta.5

/home/xxzx/.nvm/versions/node/v12.14.0/lib/node_modules/@tarojs/cli/dist/build.js:31
                plugin.apply(this);
                       ^

TypeError: plugin.apply is not a function
报了这样的一个错误，开发模式下编译的时候，之前还只是无法编译到小程序，现在连编译到h5都不行了。。。

**Comment by XHMM** [comment]
@zzxqd 啊抱歉，没注意到你用的是v3，我是在v2可正常使用的。还没研究过v3有啥变动。😅

**Comment by zzxqd** [comment]
> @zzxqd 啊抱歉，没注意到你用的是v3，我是在v2可正常使用的。还没研究过v3有啥变动。😅

应该还是taro的问题，taro的config/index.js 里默认是configs:[],我改成config:[“tarojs....”]就行了，不过还是只有h5的没问题，编译到小程序还是会报之前相同的问题

**Comment by zzxqd** [comment]
> > @zzxqd 啊抱歉，没注意到你用的是v3，我是在v2可正常使用的。还没研究过v3有啥变动。😅
> 
> 应该还是taro的问题，taro的config/index.js 里默认是configs:[],我改成config:[“tarojs....”]就行了，不过还是只有h5的没问题，编译到小程序还是会报之前相同的问题

你自己写的插件么，赞一个👍

**Comment by zzxqd** [comment]
> @zzxqd 啊抱歉，没注意到你用的是v3，我是在v2可正常使用的。还没研究过v3有啥变动。😅

你自己写的插件么，赞一个，帮你star了，不过如果是插件的话应该是devDependencies就可以了，你使用说明里直接以dependencies安装了

**Comment by XHMM** [comment]
> > @zzxqd 啊抱歉，没注意到你用的是v3，我是在v2可正常使用的。还没研究过v3有啥变动。😅
> 
> 应该还是taro的问题，taro的config/index.js 里默认是configs:[],我改成config:[“tarojs....”]就行了，不过还是只有h5的没问题，编译到小程序还是会报之前相同的问题

看了下v3的文档，插件体系确实和v2有所不同了。那这个问题应该就是taro自身的吧，那就等待其他伙计解决啦😇

---


> > @zzxqd 啊抱歉，没注意到你用的是v3，我是在v2可正常使用的。还没研究过v3有啥变动。😅
> 
> 你自己写的插件么，赞一个，帮你star了，不过如果是插件的话应该是devDependencies就可以了，你使用说明里直接以dependencies安装了

多谢，不过插件里的依赖还是得写在 dependencies里的，因为使用者在安装包的时候不会下载devDependencies的内容的，所以如果写在devDep里就得额外说明让使用者自己手动安装下依赖了，必要性不大😄

**Comment by li2215890610** [comment]
解决了吗？

**Comment by zzxqd** [comment]
> 解决了吗？

用@import了 没用use

**Comment by Chen-jj** [comment]
v3.2.6 小程序编译从 node-sass 改为 dart sass，已解决此问题。
