### ISSUE TITLE
项目taro 升级到2.2.9 cssModules 配置没法使用 

### ISSUE THREAD

**Issue by dagouzhi** [NervJS/taro#6731]
### 复现步骤

1.  

`npx @tarojs/cli init myApp`
修改config
```
 cssModules: {
        enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'global', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
 }
```
修改pages/index.tsx
```
import styles from './index.scss'

<View className={styles.index}>

```

2. 
`npm run dev:h5`
3. 

4. 
class为空 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

显示正常类名

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by songzeng2016** [comment]
+1，小程序也有同样的问题

**Comment by luckyadam** [comment]
用 module 模式呢

**Comment by dagouzhi** [comment]
@luckyadam module模式可以

**Comment by zjafei** [comment]
我也是的 引用的 变量 是个{}

**Comment by xuyuanxiang** [comment]
taro@2.2.9  `cssModules.namingPattern`配置项取值："global"和"module"实际效果与文档描述相反。

期望：

> namingPattern 配置取值分别如下：
> + global，表示全局转换，所有样式文件都会经过 CSS Modules 转换处理，除了文件名中包含 .global. 的样式文件
> + module，表示自定义转换，只有文件名中包含 .module. 的样式文件会经过 CSS Modules 转换处理

实际：

> + global：只有文件名中包含 .module. 的样式文件会经过 CSS Modules 转换处理；
> + module：所有样式文件都会经过 CSS Modules 转换处理。

**Comment by luckyadam** [comment]
已修复，2.2.10 可用

**Comment by jeffrey-fu** [comment]
2.2.10还没发布

参照大佬的commit修改了`node_modules/@tarojs/mini-runner/dist/webpack/chain.js` 143 144行 应急

**Comment by jeffrey-fu** [comment]
> 已修复，2.2.10 可用

H5端还是不受控制呀

**Comment by mya12321** [comment]
> 已修复，2.2.10 可用

我这里照着commit修改了之后还是不行, global模式和module模式还是反的

**Comment by jeffrey-fu** [comment]
> > 已修复，2.2.10 可用
> 
> 我这里照着commit修改了之后还是不行, global模式和module模式还是反的

小程序是可以了，H5不行

**Comment by mya12321** [comment]
> > > 已修复，2.2.10 可用
> > 
> > 
> > 我这里照着commit修改了之后还是不行, global模式和module模式还是反的
> 
> 小程序是可以了，H5不行

小程序也没有好, module模式引入的style打出来还是空对象

**Comment by mya12321** [comment]
> 已修复，2.2.10 可用

我这里提供一个重现[示例](https://github.com/mya12321/taro-issue), 如果修好了的效果应该如同没使用css modules的下图:  

![screenshot](https://raw.githubusercontent.com/mya12321/taro-issue/master/src/assets/images/screenshot.png)

**Comment by luckyadam** [comment]
> > 已修复，2.2.10 可用
> 
> 我这里提供一个重现[示例](https://github.com/mya12321/taro-issue), 如果修好了的效果应该如同没使用css modules的下图:
> 
> ![screenshot](https://raw.githubusercontent.com/mya12321/taro-issue/master/src/assets/images/screenshot.png)

开启了 css modules 就无法使用 taro-ui 了

**Comment by divcss3** [comment]
> > > 已修复，2.2.10 可用
> > 
> > 
> > 我这里提供一个重现[示例](https://github.com/mya12321/taro-issue), 如果修好了的效果应该如同没使用css modules的下图:
> > ![screenshot](https://raw.githubusercontent.com/mya12321/taro-issue/master/src/assets/images/screenshot.png)
> 
> 开启了 css modules 就无法使用 taro-ui 了

https://github.com/NervJS/taro/issues/6979
大佬，好像又出问题了

**Comment by divcss3** [comment]
> > > 已修复，2.2.10 可用
> > 
> > 
> > 我这里提供一个重现[示例](https://github.com/mya12321/taro-issue), 如果修好了的效果应该如同没使用css modules的下图:
> > ![screenshot](https://raw.githubusercontent.com/mya12321/taro-issue/master/src/assets/images/screenshot.png)
> 
> 开启了 css modules 就无法使用 taro-ui 了

https://github.com/NervJS/taro/issues/6979
@luckyadam 大佬，好像又出问题了😄

**Comment by gezichenshan** [comment]
CSS module真的不能用啊，而且文档也没有任何更新了。国内开源社区环境也是真的不好。

**Comment by mya12321** [comment]
> CSS module真的不能用啊，而且文档也没有任何更新了。

2.2.11以上的版本已经修复这问题了, 就是2.2.15版本小程序端有其他问题, 升级要谨慎, 我用的2.2.13版本

**Comment by missmimia** [comment]
> > CSS module真的不能用啊，而且文档也没有任何更新了。
> 
> 2.2.11以上的版本已经修复这问题了, 就是2.2.15版本小程序端有其他问题, 升级要谨慎, 我用的2.2.13版本

意思是2.2.13是ok的嘛？ 升到2.2.16 还是扑街了的说==

**Comment by olifer655** [comment]
3.2.8 同样没有起作用

**Comment by shaodushu** [comment]
3.3.3 也没起作用

**Comment by airwaycai** [comment]
3.3.8 同样样式没了 undefined
