### ISSUE TITLE
百度小程序、h5列表渲染bug

### ISSUE THREAD

**Issue by shengbowen** [NervJS/taro#6736]
### 问题描述
百度小程序渲染列表 [1,2,3,4,5,6], 如果在数组头部添加数据，会导致整个列表的重新渲染，在数组尾部添加数据则不会。

### 复现步骤

![image](https://user-images.githubusercontent.com/5378783/84996451-e0480280-b17f-11ea-9299-8705e19ba14b.png)
如图，在列表头部添加数据后，触发了9次render。

```js
const intialState = [1, 2, 3, 4, 5, 6, 7, 8].map(item => ({
  id: item,
  value: item + "a"
}));

let id = 10;

class Index extends Component {
  state = { list: intialState };

  render() {
    return (
      <View>
        <Button
          onClick={() => {
            this.setState({
              list: this.state.list.concat([{ id: id, value: id + "a" }])
            });
            id++;
          }}
        >
          +
        </Button>
        <Button
          onClick={() => {
            const newlist = this.state.list;

            newlist.unshift({ id: id, value: id + "a" });

            this.setState({
              list: newlist
            });
            id++;
          }}
        >
          -
        </Button>
        {this.state.list.map(item => {
          const s = String(item.id);
          return <Bubble item={item.value} key={s} />;
        })}
      </View>
    );
  }
}


// bubble.js
export default class Bubble extends PureComponent {
  render() {
    console.log("rendering");

    const { item } = this.props;

    return <View>{item}</View>;
  }
}
```

### 期望行为
期望列表头部添加数据，不会导致旧数据重新render。

### 系统信息
我是用2.2.8版本调试，实测1.3.34也有同样问题

@tarojs/components: 2.2.8 => 2.2.8
      @tarojs/components-qa: 2.2.8 => 2.2.8
      @tarojs/mini-runner: 2.2.8 => 2.2.8
      @tarojs/plugin-sass: 2.2.8 => 2.2.8
      @tarojs/redux: 2.2.8 => 2.2.8
      @tarojs/redux-h5: 2.2.8 => 2.2.8
      @tarojs/router: 2.2.8 => 2.2.8
      @tarojs/taro: 2.2.8 => 2.2.8
      @tarojs/taro-alipay: 2.2.8 => 2.2.8
      @tarojs/taro-h5: 2.2.8 => 2.2.8
      @tarojs/taro-qq: 2.2.8 => 2.2.8
      @tarojs/taro-quickapp: 2.2.8 => 2.2.8
      @tarojs/taro-swan: 2.2.8 => 2.2.8
      @tarojs/taro-tt: 2.2.8 => 2.2.8
      @tarojs/taro-weapp: 2.2.8 => 2.2.8
      @tarojs/webpack-runner: 2.2.8 => 2.2.8
      eslint-config-taro: 2.2.8 => 2.2.8
      eslint-plugin-taro: 2.2.8 => 2.2.8
      nerv-devtools: ^1.5.5 => 1.5.7
      nervjs: ^1.5.5 => 1.5.7
      stylelint-config-taro-rn: 2.2.8 => 2.2.8
      stylelint-taro-rn: 2.2.8 => 2.2.8

### 补充信息
我调试后发现，是因为 compid的observer，触发的newVal和oldVal不对应，比如我旧的列表头部compid是0对应的是数组第一项，但是新列表的compid是8，对应的还是数组的第一项，此时应该对应的是新列表的第二项才对。    这导致了计算出来的nextProps变了，整个列表都刷新了。

不知道是不是百度小程序的bug，微信小程序表现是正常的。不知道有没有什么途径可以略过。还有列表组件判断是否新的，为什么不是用组件的key属性来判断，为什么要用compid呢。

```js
weappComponentConf.properties.compid = {
    type: null,
    value: null,
    observer: function observer(newVal, oldVal) {
      var _this = this;

      initComponent.apply(this, [ComponentClass, isPage]);

      if (oldVal && oldVal !== newVal) {
        var extraProps = this.data.extraProps;
        var component = this.$component;
        propsManager.observers[newVal] = {
          component: component,
          ComponentClass: component.constructor
        };
        var nextProps = filterProps(component.constructor.defaultProps, propsManager.map[newVal], component.props, extraProps || null);
```

**Comment by shengbowen** [comment]
比较急，严重影响了列表的性能，希望各位大佬能尽快回复。

**Comment by shengbowen** [comment]
h5端也有这个问题，实测了一下，应该是nervjs 的bug，可以使用下面示例尝试一下。https://codesandbox.io/s/nerv-sandbox-43t5m?fontsize=14&hidenavigation=1&theme=dark   
用react 则不会有这个问题。 还望官方重视一下这个问题。

**Comment by penghuwan** [comment]
我们也遇到了这个问题，求帮助

**Comment by Liaozhenting** [comment]
same issue

**Comment by yuche** [comment]
> h5端也有这个问题，实测了一下，应该是nervjs 的bug，可以使用下面示例尝试一下。[codesandbox.io/s/nerv-sandbox-43t5m?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/nerv-sandbox-43t5m?fontsize=14&hidenavigation=1&theme=dark)
> 用react 则不会有这个问题。 还望官方重视一下这个问题。

h5 这边需要有 key 的标签再包一层，现在的 diff 算法要求一个列表的第一个 item 一定要有key：
https://codesandbox.io/s/nerv-sandbox-dnq1e?file=/index.js

**Comment by shengbowen** [comment]
> > h5端也有这个问题，实测了一下，应该是nervjs 的bug，可以使用下面示例尝试一下。[codesandbox.io/s/nerv-sandbox-43t5m?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/nerv-sandbox-43t5m?fontsize=14&hidenavigation=1&theme=dark)
> > 用react 则不会有这个问题。 还望官方重视一下这个问题。
> 
> h5 这边需要有 key 的标签再包一层，现在的 diff 算法要求一个列表的第一个 item 一定要有key：
> https://codesandbox.io/s/nerv-sandbox-dnq1e?file=/index.js

原来这样子，非常感谢。    不过百度小程序的又是什么原因呢，有解吗？

**Comment by Chen-jj** [comment]
Taro 3 应该没有这个问题了。

**Comment by shengbowen** [comment]
> Taro 3 应该没有这个问题了。
暂时没办法升级到 taro 3啊， 所以还是想官方看下是什么原因，有没有方法解决

**Comment by shengbowen** [comment]
仔细看了下代码，因为taro的运行时，是靠监听子组件properties的compid变化，来决定是否updateComponent。
微信端，在列表头部添加数据，只会触发新增项的compid的observer。 但是百度端是触发了所有列表项的observer。这大概是问题的原因。
在百度小程序社区提了一个issue，看看怎么回复。
https://smartprogram.baidu.com/forum/topic/show/116712

**Comment by shengbowen** [comment]
总结下bug原因：  百度小程序列表目前不支持s-key属性来优化性能，只支持trackBy，具体看这里https://smartprogram.baidu.com/forum/topic/show/116712

解决方案：
1. 使用node将编译后的列表模板文件，加上trackBy。同时注意某些情况下，需要在列表mount时调用`Taro.setIsUsingDiff(false)`关闭diff，才能生效。记得在unmount时恢复diff

2. 上面我提交了一下代码，可以简单修复这个问题，但是只支持单层循环。

**Comment by windyoung1990** [comment]
@shengbowen 大佬，麻烦问下哪些情况下，需要在列表mount时调用Taro.setIsUsingDiff(false)关闭diff，在unmount时恢复diff？我现在的场景是向上翻页，目前更新到2.2.17的版本，好像还是会全量渲染

**Comment by windyoung1990** [comment]
@Chen-jj @luckyadam 能帮忙看下咋回事么

**Comment by windyoung1990** [comment]
> 我们也遇到了这个问题，求帮助

老哥，问题解决了没
