### ISSUE TITLE
Taro Next rc3版本，Taro.createRef is undefined

### ISSUE THREAD

**Issue by c690554125** [NervJS/taro#6737]
在constructor中去调用`Taro.createRef`，报错了。打印了下，发现该方法不存在。 是next版本改了写法吗？
![1](https://user-images.githubusercontent.com/13865568/85001590-6cf5bf00-b186-11ea-8476-ffe21898bc53.jpg)
![2](https://user-images.githubusercontent.com/13865568/85001593-6d8e5580-b186-11ea-8aaf-c0d63bf6533b.jpg)

**Comment by yuche** [comment]
`React.createRef`，`createRef` 是 React 的方法，仔细看文档迁移指南。
