### ISSUE TITLE
[Taro Next 3.0.0.rc-6] 使用 react-query / swr 等库时出现 maximum update depth exceed

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#6739]
### 问题描述

使用 react-query / swr 等库时出现 maximum update depth exceed。

### 复现步骤

```js
// Index.js
import React from "react";
import { View } from "@tarojs/components";
import { useQuery } from "react-query";
import "./index.scss";

export default function Index(props) {
  const { data } = useQuery("test", async () => await 123);
  console.log(data);

  return <View>Index</View>;
}
```

正确期望是打印一次 `undefined`（刚进入时）和一次 `123`（获取到 Promise 结果时），但是实际表现是组件一直重新渲染，打印出无数 `undefined`。

### 报错信息

![image](https://user-images.githubusercontent.com/22665058/85088622-76a81280-b1d8-11ea-8287-ed3a03fab4cd.png)

### 系统信息

```
  Taro CLI 3.0.0-rc.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
      Yarn: 1.5.1 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/components: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/mini-runner: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/react: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/runtime: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/taro: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/webpack-runner: 3.0.0-rc.5 => 3.0.0-rc.5 
      babel-preset-taro: 3.0.0-rc.5 => 3.0.0-rc.5 
      eslint-config-taro: 3.0.0-rc.5 => 3.0.0-rc.5 
      react: ^16.10.0 => 16.13.1 
```

# 附加信息

在 h5 模式下正常运行，符合预期，没有报错。

**Comment by Chen-jj** [comment]
@Songkeys 

`react-query` 使用了 document、window 等全局变量，Taro Next 在小程序环境是通过 **webpack providePlugin** 注入这些全局变量的。

但是 `react-query` 的入口为 react-query.mjs：

https://github.com/tannerlinsley/react-query/blob/db5a51e087c7984d98da51ee6831780a5b3a64aa/package.json#L11

又因为 providePlugin 跳过了 .mjs 后缀的文件，所以小程序环境没有为 react-query 注入全局变量而导致报错：

https://github.com/webpack/webpack/blob/dfd20210c9441c309859d29d3b256474ae5101e5/lib/ProvidePlugin.js#L74-L81

目前的解决办法是注意不要使用 *.mjs* 后缀的文件，例如：

```js
import { useQuery } from 'react-query/dist/react-query.production.min'
```

**Comment by dpyzo0o** [comment]
这样引入之后, react-query 的 typescript 类型就丢失掉了, 有什么解决办法吗 @Chen-jj

**Comment by Chen-jj** [comment]
@dpyzo0o 直接引用它的类型文件试试

**Comment by dpyzo0o** [comment]
> @dpyzo0o 直接引用它的类型文件试试

declare module 可以解决，之后会有比较优雅的解决方案吗，这样感觉还是hack。是需要 `react-query` 那边导出 `.js` 的入口文件还是说 taro 这边可以进行一些适配的处理?

**Comment by Chen-jj** [comment]
@dpyzo0o 暂时没有

**Comment by 54huanan** [comment]
@Songkeys @Chen-jj 
hello，文档说不能修改入口文件app.tsx的render方法，问下怎么才能用QueryClientProvider包裹默认的Provider呢？
```
// 在 App 类中的 render() 函数没有实际作用
    // 请勿修改此函数
    render() {
        return (
            <QueryClientProvider client={queryClient}>
                <Provider store={store}>{this.props.children}</Provider>
            </QueryClientProvider>
        )
    }
```
我像上面写dev时是好的，build后就功能不正常。

**Comment by hengkx** [comment]
qq 小程序开发正常，真机会报错用的taro 4 vite react query 4

**Comment by vaynevayne** [comment]
这个库 712 kB ，你们直接用的？ 有没手段精简下？
