### ISSUE TITLE
[Taro Next rc.5] Text 文字溢出省略 表现异常

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro#6741]
问题描述

Text 文字溢出省略 在手机浏览器 表现异常，排除css与autoprefixer问题，同一个 css class 和 div，放在 html -> body 下，就是正常的，如下方视频。

表现
[小米手机录屏](http://cdn.hbzy2014.com/Fqh62UvOMAwOeCaZFcdokWV3d5cg)

### 复现步骤

这个项目可以直接用来测试
[https://github.com/charmtiger/taro-test](https://github.com/charmtiger/taro-test)

### 系统信息

  Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.config/yarn/global/node_modules/.bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/taro: 3.0.0-rc.5 => 3.0.0-rc.5 
      @tarojs/webpack-runner: 3.0.0-rc.5 => 3.0.0-rc.5 
      eslint-config-taro: 3.0.0-rc.5 => 3.0.0-rc.5 
      react: ^16.10.0 => 16.13.1

**Comment by charmtiger** [comment]
我使用dom操作，插入到taro页面中的元素，文字溢出省略是正常的，应该排除是上级css样式影响，我感觉是 Web Component 的问题。

```js
setTimeout(function(){
      var el = document.getElementById('appendDiv');
      var node = document.createElement("div");  
      var child = `
        <div style="width: 320px;overflow: hidden;">
          <span class="M-text-show-row-1">这个文字放在html>body中的的的的的</span>
        </div>
      `;
      node.innerHTML = child;
      el.appendChild(node);
    }, 5000);
```

**Comment by Chen-jj** [comment]
备注：X5 内核对 web component 的兼容问题。

**Comment by Chen-jj** [comment]
3.1.0-beta.5 修复

**Comment by March-Wind** [comment]
3.4.3依然会出现
