### ISSUE TITLE
h5端swiper组件数据只有一条时会显示重复一条 共2条数据

### ISSUE THREAD

**Issue by R10burning** [NervJS/taro#6744]
```
![image](https://user-images.githubusercontent.com/28866609/85094160-ac70e980-b220-11ea-9d33-1a4771d89481.png)

h5端swiper组件数据只有一条时会显示重复一条 共2条数据 ，indicator只有1个，会导致第二条的重复数据点击事件无效
### 期望行为
swiper和小程序端 表现一致

### 报错信息

无

### 系统信息


System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.7 => 2.2.7 
      @tarojs/components-qa: 2.2.7 => 2.2.7 
      @tarojs/mini-runner: 2.2.7 => 2.2.7 
      @tarojs/redux: 2.2.7 => 2.2.7 
      @tarojs/redux-h5: 2.2.7 => 2.2.7 
      @tarojs/router: 2.2.7 => 2.2.7 
      @tarojs/taro: 2.2.7 => 2.2.7 
      @tarojs/taro-alipay: 2.2.7 => 2.2.7 
      @tarojs/taro-h5: 2.2.7 => 2.2.7 
      @tarojs/taro-qq: 2.2.7 => 2.2.7 
      @tarojs/taro-quickapp: 2.2.7 => 2.2.7 
      @tarojs/taro-swan: 2.2.7 => 2.2.7 
      @tarojs/taro-tt: 2.2.7 => 2.2.7 
      @tarojs/taro-weapp: 2.2.7 => 2.2.7 
      @tarojs/webpack-runner: 2.2.7 => 2.2.7 
      eslint-config-taro: 2.2.7 => 2.2.7 
      eslint-plugin-taro: 2.2.7 => 2.2.7 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.7 => 2.2.7 
      stylelint-taro-rn: 2.2.7 => 2.2.7 
      taro-ui: ^2.3.4 => 2.3.4 
    npmGlobalPackages:
      typescript: 3.9.5

**Comment by R10burning** [comment]
![image](https://user-images.githubusercontent.com/28866609/85094160-ac70e980-b220-11ea-9d33-1a4771d89481.png)

**Comment by R10burning** [comment]
code:
return <View>
    <Skeleton row={1} rowHeight={577} rowWidth={755} animateName='elastic' loading={adList.length === 0}>
      <Swiper
        className='swiper'
        interval={4000}
        autoplay
        indicatorDots
        circular={false}
      >
        {renderBanner()}
      </Swiper>
    </Skeleton>

**Comment by R10burning** [comment]
code:
const renderBanner = () => {
    return adList.map(item => <SwiperItem key={item.id} className='swiper-item'>
      <Image className='swiper-img' src={item.adImg} onClick={() => toDetail(item)} />
    </SwiperItem>)
  }
  return <View>
    <Skeleton row={1} rowHeight={577} rowWidth={755} animateName='elastic' loading={adList.length === 0}>
      <Swiper
        className='swiper'
        interval={4000}
        autoplay
        indicatorDots
        circular={false}
      >
        {renderBanner()}
      </Swiper>
    </Skeleton>

**Comment by ZakaryCode** [comment]
版本更新可以解该问题
