### ISSUE TITLE
pxTransform在微信小程序中无法获取到config中的配置，导致得到的rpx数值不对

### ISSUE THREAD

**Issue by zzxqd** [NervJS/taro#6747]
### 问题描述

在config/index.js中配置designWidth为375增加375:1/2到deviceRatio中，得到的尺寸理论上应该是2*传入尺寸，但得到的确实1*传入尺寸
### 复现步骤

1. 在config/index.js中增加如下配置
{
  designWidth: 375,
  deviceRatio: {
    '375': 1 / 2,
    '640': 2.34 / 2,
    '750': 1,
    '828': 1.81 / 2,
  },
}
2. import Taro from "@tarojs/taro";
3. console.log(Taro.pxTransform(20))
4. 控制台输出“20rpx”

### 期望行为

输出"40rpx"
### 系统信息

👽 Taro v3.0.0-beta.5

  Taro CLI 3.0.0-beta.5 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      @tarojs/webpack-runner: 3.0.0-beta.5 => 3.0.0-beta.5 
      eslint-config-taro: 3.0.0-beta.5 => 3.0.0-beta.5 
      react: ^16.10.0 => 16.13.1 

### 补充信息

![image](https://user-images.githubusercontent.com/23022401/85107308-59a72a00-b240-11ea-9d90-fec42ee80ad2.png)
在pxTransform中获取不到config里的配置项

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by digiaries** [comment]
在页面上使用的话需要先使用 initPxTransform 对功能进行初始化。文档上没有描述清楚这件事。。。

**Comment by LFB** [comment]
> 在页面上使用的话需要先使用 initPxTransform 对功能进行初始化。文档上没有描述清楚这件事。。。

初始化代码：
```js
const designWidth = 750
const { windowWidth } = Taro.getSystemInfoSync()

Taro.initPxTransform({
  designWidth: windowWidth,
  deviceRatio: {
    [windowWidth]: windowWidth / designWidth
  }
})
```
