### ISSUE TITLE
在app.tsx下config中pages使用常量的问题

### ISSUE THREAD

**Issue by alwaysRemember** [NervJS/taro#6748]
### 问题描述
我定义了一个enum来配置页面路由，这样的话我在进行页面跳转的时候，只需要使用enum就可以了，但是编译的时候报错未找到页面。

### 复现步骤

```
export enum ERoutes {
  HOME = "/pages/Home/index",
  PERSONAL_CENTER = "/pages/PersonalCenter/index"
}
export const routes: Array<string> = Object.values(ERoutes).map((val: string) =>
  val.substr(1)
);

app.tsx

import { routes } from "./routes";
pages: routes,
```

### 期望行为

为什么会造成这个原因？发现必须在config中直接写页面路径才可以

### 报错信息
```
> taro build --type weapp "--watch"

👽 Taro v2.2.9

生成  工具配置  /Users/tang/Documents/myProject/koala/koala-frontend/dist/project.config.json

🙅   编译失败.

缺少页面

```

### 系统信息
👽 Taro v2.2.9

  Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.9 => 2.2.9
      @tarojs/components-qa: 2.2.9 => 2.2.9
      @tarojs/mini-runner: 2.2.9 => 2.2.9
      @tarojs/plugin-less: 2.2.9 => 2.2.9
      @tarojs/plugin-terser: 2.2.9 => 2.2.9
      @tarojs/redux: 2.2.9 => 2.2.9
      @tarojs/redux-h5: 2.2.9 => 2.2.9
      @tarojs/router: 2.2.9 => 2.2.9
      @tarojs/taro: 2.2.9 => 2.2.9
      @tarojs/taro-alipay: 2.2.9 => 2.2.9
      @tarojs/taro-h5: 2.2.9 => 2.2.9
      @tarojs/taro-qq: 2.2.9 => 2.2.9
      @tarojs/taro-quickapp: 2.2.9 => 2.2.9
      @tarojs/taro-swan: 2.2.9 => 2.2.9
      @tarojs/taro-tt: 2.2.9 => 2.2.9
      @tarojs/taro-weapp: 2.2.9 => 2.2.9
      @tarojs/webpack-runner: 2.2.9 => 2.2.9
      eslint-config-taro: 2.2.9 => 2.2.9
      eslint-plugin-taro: 2.2.9 => 2.2.9
      nerv-devtools: ^1.5.5 => 1.5.7
      nervjs: ^1.5.5 => 1.5.7
      stylelint-config-taro-rn: 2.2.9 => 2.2.9
      stylelint-taro-rn: 2.2.9 => 2.2.9
    npmGlobalPackages:
      typescript: 3.1.6

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
你可以试试这个 https://nervjs.github.io/taro/docs/envs#appjs-%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84-pages

**Comment by alwaysRemember** [comment]
这样的写法不还是写在app.tsx中。 我定义枚举的本质就是为了在跳转的时候直接可以使用枚举变量进行跳转，从而不会造成跳转的时候写一遍路径，config中写一遍路径。

**Comment by Songkeys** [comment]
跟楼主一样的用法，我是在 js 中写的。报错是：
```
Unexpected token 'export'


(node:15032) UnhandledPromiseRejectionWarning: .../src/common/constants.js:2
export const HOME_PAGE_URLS = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    ...
```

**Comment by luckyadam** [comment]
因为编译时，支持不了解析你定义的变量
