### ISSUE TITLE
babel使用polyfill编译失败

### ISSUE THREAD

**Issue by hr837** [NervJS/taro#6749]
在taro cli 2.1.0 使用了babel-polyfill, 按照官方配置(@7.4+), 编译时报babel核心库版本不一致，经查我项目安装的@babel/core 版本为7.10.0  而taro-webpack-runner 用的babel是6.26,所以编译失败，望给予解决思路。

**Comment by Garfield550** [comment]
Taro 1 和 2 不支持 babel 7
