### ISSUE TITLE
可否增加选项自定义组件或者设置flag取消navigation 的那个header

### ISSUE THREAD

**Issue by szheng3** [NervJS/taro#675]
因为有的页面是不需要header，所以如何取消header

**Comment by yuche** [comment]
你说得是底部的 navbar 还是头部的 header

**Comment by szheng3** [comment]
头部的header

**Comment by szheng3** [comment]
主要是在rn里面 =-=

**Comment by Pines-Cheng** [comment]
Taro  是按照小程序的标准来实现各端功能的，小程序没有提供对应的 API 哦。
@luckyadam

**Comment by szheng3** [comment]
在config.window.navigationStyle里面设置custom，小程序端口就类似于有点像取消了header, 我感觉能不能在rn端口，就设置为取消了header

**Comment by luckyadam** [comment]
可以，rn 也可以同步增加这个配置
