### ISSUE TITLE
升级taro到2.2.9遇到@tarojs/plugin-sass报错的问题及解决办法

### ISSUE THREAD

**Issue by lancerfox** [NervJS/taro#6750]
### 问题描述
升级@2.2.9，报错
当前项目使用了 sass，请安装插件 @tarojs/plugin-sass，并且在 plugins 中进行配置，否则将无法编译 sass 文件！
参考文档：https://nervjs.github.io/taro/docs/config-detail#plugins
解决办法：
在config/index.js中配置 添加 plugins: ['@tarojs/plugin-sass', '@tarojs/plugin-terser'],
const config = {
    plugins: ['@tarojs/plugin-sass', '@tarojs/plugin-terser'],
  }
不是在babel/plugins中添加

**Comment by luckyadam** [comment]
很明显啊，文档地址都给出来了

**Comment by liangyunli** [comment]
+1

**Comment by code4eat** [comment]
RN用这个没解决，有解决的吗？

**Comment by shengbowen** [comment]
> RN用这个没解决，有解决的吗？

要在config里面 添加rn的配置，比如
```
mini: {},
rn: {}
```
就不报错了
