### ISSUE TITLE
[Taro Next] 如何获取 index.config.ts 中的页面配置数据

### ISSUE THREAD

**Issue by Songkeys** [NervJS/taro#6755]
请教一下，3.0 里有获取当前页面配置文件的 API 吗？

想写一个 hooks 获取 config 文件中的导航标题，然后放在自己写的导航组件中。

目前我只找到 `getApp()` 可以获取 app 的全局配置，请问页面的有吗？

理想使用方式：

```js
const { navigationBarTitleText } = Taro.usePageConfig()
```

如果实现，需要注意的地方：使用 `setNavigationBarTitle()` 之后，这个配置是否应该发生改变？

**Comment by cncolder** [comment]
页面配置目前是按小程序的规则生成 json, 但是小程序不允许 require json.

app.config.js 的内容是在编译阶段注入到 Current.app.config 的, 同时还有个隐藏变量 window.__taroAppConfig.

页面如果也采用类似的方法, 应该是放在 Current.page.config 上更合适, 包装成 hook 也简单, 事实上 Taro.useRouter 这个 hook 就是对 Current.router 的包装.

**Comment by Songkeys** [comment]
> 要想在代码中获取配置需要自己导入 import pageConfig from './page.config.js'

是的，但是想抽象成 hooks 让所有页面都可以用，没办法引入动态路径。

我也是觉得应该可以跟 app.config 一样在编译时注入。
