### ISSUE TITLE
执行打包后报错 Uncaught TypeError: (void 0) is not a function

### ISSUE THREAD

**Issue by zengwmFE** [NervJS/taro#6756]
正常通过官方教程进行升级，1.2升级到2.0.6，在本地环境运行正常，但是经过打包在服务器上面就报错
![image](https://user-images.githubusercontent.com/32829958/85244994-d58bb700-b478-11ea-915b-0ae45444d204.png)

**Comment by ZakaryCode** [comment]
无法复现该问题，可以尝试通过升级 Taro 版本解决，如果不行可以提交一个稳定复现的示例

**Comment by zengwmFE** [comment]
已经确认是jenkins打包出现版本错误
