### ISSUE TITLE
退出页面时依旧进行swiper.params.autoplay.reverseDirection判断导致报错

### ISSUE THREAD

**Issue by yiqisweet** [NervJS/taro#6757]
### 问题描述

1，页面中swiper无设置autoplay，退出页面时依旧进行swiper.params.autoplay.reverseDirection判断导致报错

### 复现步骤

1，页面swiper无设置autoplay  回退页面消失后，依旧进行swiper.params.autoplay.reverseDirection判断导致报错
报错内容
Cannot read property 'autoplay' of undefined

```js
页面：
   <Swiper indicatorDots className='swiper-container'>
        SwiperItem...
   </Swiper>

回退后:
  if (swiper.params.autoplay.reverseDirection) { < 报错
        if (swiper.params.loop) {
          swiper.loopFix();
          swiper.slidePrev(swiper.params.speed, true, true);
          swiper.emit('autoplay');
        } else if (!swiper.isBeginning) {
          swiper.slidePrev(swiper.params.speed, true, true);
          swiper.emit('autoplay');
        } else if (!swiper.params.autoplay.stopOnLastSlide) {
          swiper.slideTo(swiper.slides.length - 1, swiper.params.speed, true, true);
          swiper.emit('autoplay');
        } else {
          swiper.autoplay.stop();
        }
      } 
```

### 报错信息

Cannot read property 'autoplay' of undefined

### 系统信息

 
Taro v2.1.5

  Taro CLI 2.1.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/async-await: 2.1.5 => 2.1.5
      @tarojs/components: 2.1.5 => 2.1.5
      @tarojs/plugin-babel: 2.1.5 => 2.1.5
      @tarojs/plugin-csso: 2.1.5 => 2.1.5
      @tarojs/plugin-sass: 2.1.5 => 2.1.5
      @tarojs/plugin-uglifyjs: 2.1.5 => 2.1.5
      @tarojs/router: 2.1.5 => 2.1.5
      @tarojs/taro: 2.1.5 => 2.1.5
      @tarojs/taro-alipay: 2.1.5 => 2.1.5
      @tarojs/taro-h5: 2.1.5 => 2.1.5
      @tarojs/taro-swan: 2.1.5 => 2.1.5
      @tarojs/taro-weapp: 2.1.5 => 2.1.5
      @tarojs/webpack-runner: 2.1.5 => 2.1.5
      eslint-config-taro: 2.1.5 => 2.1.5
      eslint-plugin-taro: 2.1.5 => 2.1.5
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      taro-ui: 2.1.0 => 2.1.0

### 补充信息
是我需要在页面结束后做一些什么？给autoplay设置为false？
但swiper 文档中写到 不设置默认值为false，我在默认值为false的时候退出页面，理应不运行autoplay run方法？

**Comment by windyoung1990** [comment]
@yiqisweet 这个最后是怎么处理的？
