### ISSUE TITLE
api 什么时候能支持多端，现在很多api 只有微信和rn，其它端能否支持一下

### ISSUE THREAD

**Issue by wiiler** [NervJS/taro#6759]
### 复现步骤

1. 
2. 
3. 
4. 

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
@wiiler 例如？

**Comment by wiiler** [comment]
> @wiiler 例如？

![image](https://user-images.githubusercontent.com/9715482/85997527-2df42300-ba3c-11ea-819f-30ba68b290aa.png)
![image](https://user-images.githubusercontent.com/9715482/85997559-38162180-ba3c-11ea-88ea-68bf8336e431.png)
![image](https://user-images.githubusercontent.com/9715482/85997607-482e0100-ba3c-11ea-8e88-8d9711160ad8.png)

这些不是很多吗，这些接口经常用，但是只支持微信？

**Comment by Chen-jj** [comment]
@wiiler 一般都可以用，缺失了可以提 PR 或 issue。https://nervjs.github.io/taro/docs/debug#api-%E9%97%AE%E9%A2%98
