### ISSUE TITLE
onShareAppMessage

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#6760]
### 问题描述

onShareAppMessage在Taro3中编译，支付宝小程序编译无效，报错， 微信小程序正常

### 复现步骤

onShareAppMessage() {
    return {
      title : '分享 View 组件' ,
      path : 'page/component/view/view' ,
      };
  }

在分享页面设置分享 支付宝小程序未能生效，微信小程序正常

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

能够进行正常 分享

### 报错信息
![image](https://user-images.githubusercontent.com/50317102/85365751-903eb680-b558-11ea-929d-fdda74c5f740.png)

请检查onShareAppMessage代码，需要返回一个对象，并包含必填参数
### 系统信息

Taro v1.3.39

  Taro CLI 1.3.39 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Chen-jj** [comment]
升级到最新版本再试试吧，1.3.45 复现不了
