### ISSUE TITLE
Config 下创建自定义环境变量，build 完后报错

### ISSUE THREAD

**Issue by ksbaozi** [NervJS/taro#6763]
### 问题描述

Config 下创建自定义环境变量，build 完后报错

### 复现步骤

1. config 文件夹下创建 test.js 
```
/* eslint-disable import/no-commonjs */
module.exports = {
  env: {
    NODE_ENV: '"test"',
    PROTOCOL: '"https"',
    HOST: '"aaaa"',
  },
  defineConstants: {
  },
  weapp: {
  },
  h5: {}
}
```

2. condig index 文件中更改
```
module.exports = function (merge) {
  if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  if (process.env.NODE_ENV === 'test') {
    return merge({}, config, require('./test'))
  }
  return merge({}, config, require('./prod'))
}

```

3. build 小程序应用 启动命令
```
NODE_ENV=test taro build --type weapp
```

4. build 成功但是开发者工具中出现错误：
```
Page is not constructed because it is not found
```

### 期望行为

不报错正常运行

### 报错信息

![image](https://user-images.githubusercontent.com/15046405/85369076-fd554a80-b55e-11ea-9e32-869f32c6e956.png)

### 系统信息

 Taro CLI 3.0.0-rc.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.5 => 3.0.0-rc.5
      @tarojs/mini-runner: 3.0.0-rc.5 => 3.0.0-rc.5
      @tarojs/react: 3.0.0-rc.5 => 3.0.0-rc.5
      @tarojs/runtime: 3.0.0-rc.5 => 3.0.0-rc.5
      @tarojs/taro: 3.0.0-rc.5 => 3.0.0-rc.5
      @tarojs/webpack-runner: 3.0.0-rc.5 => 3.0.0-rc.5
      babel-preset-taro: 3.0.0-rc.5 => 3.0.0-rc.5
      eslint-config-taro: 3.0.0-rc.5 => 3.0.0-rc.5
      nervjs: ^1.5.7 => 1.5.7
      react: ^16.10.0 => 16.13.1
      taro-ui: 3.0.0-alpha.1 => 3.0.0-alpha.1

**Comment by Chen-jj** [comment]
@ksbaozi 复现不了，应该是其它问题导致的，再调试一下咯。

![image](https://user-images.githubusercontent.com/11807297/85936593-e895ff80-b92e-11ea-85ea-b0720875a579.png)

![image](https://user-images.githubusercontent.com/11807297/85936599-ef247700-b92e-11ea-8bfa-916697f5797d.png)

![image](https://user-images.githubusercontent.com/11807297/85936613-04010a80-b92f-11ea-8826-71ecca99b7a6.png)

![image](https://user-images.githubusercontent.com/11807297/85936616-0cf1dc00-b92f-11ea-8426-1c60f41b4f1f.png)
