### ISSUE TITLE
Cli编译成功的提示不好区分

### ISSUE THREAD

**Issue by HanleyCN** [NervJS/taro#6767]
### 问题描述

taro cli 编译成功的提示, 和上一次编译成功的提示, 不容易区分, 不知道是否编译完或者正在编译

### 复现步骤
多次修改文件

![image](https://user-images.githubusercontent.com/43161625/85383534-a5c0da00-b572-11ea-8216-1ce4fba0cc4c.png)

### 期望行为
希望可以明显区分每次编译成功, 比如前面勾勾的颜色变化, 或者字体颜色变化, 或者带一个计数

### 报错信息

无

### 系统信息

无

**Comment by Chen-jj** [comment]
@HanleyCN 比较冷门的需求，我们应该不会支持，不过欢迎 PR ～
