### ISSUE TITLE
Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "ObjectExpression"

### ISSUE THREAD

**Issue by yulrosy** [NervJS/taro#6768]
### 问题描述

小程序编译出错

### 复现步骤

1. yarn build:weapp --watch

```js
export const DEVICE_TYPE = {
  WAP: '06',
  WECHAT: '0600',
  WEAPP: '14',
  APP: '01',
};
// 改成这样就不报错
export const DEVICE_TYPE = {
  'WAP': '06',
  'WECHAT': '0600',
  'WEAPP': '14',
  'APP': '01',
};
```

### 期望行为

编译正常

### 报错信息

 Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "ObjectExpression"

### 系统信息
 Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /var/folders/fs/4t8db8ns0_5g18dbtgs9h2fc0000gn/T/yarn--1592903322400-0.18911516275342177/node
      Yarn: 1.22.4 - /var/folders/fs/4t8db8ns0_5g18dbtgs9h2fc0000gn/T/yarn--1592903322400-0.18911516275342177/yarn
      npm: 6.14.4 - ~/.nvs/default/bin/npm
    npmPackages:
      @tarojs/cli: 2.2.9 => 2.2.9 
      @tarojs/components: 2.2.9 => 2.2.9 
      @tarojs/mini-runner: 2.2.9 => 2.2.9 
      @tarojs/plugin-sass: 2.2.9 => 2.2.9 
      @tarojs/plugin-terser: 2.2.9 => 2.2.9 
      @tarojs/redux: 2.2.9 => 2.2.9 
      @tarojs/redux-h5: 2.2.9 => 2.2.9 
      @tarojs/router: 2.2.9 => 2.2.9 
      @tarojs/taro: 2.2.9 => 2.2.9 
      @tarojs/taro-h5: 2.2.9 => 2.2.9 
      @tarojs/taro-weapp: 2.2.9 => 2.2.9 
      @tarojs/webpack-runner: 2.2.9 => 2.2.9 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      taro-ui: ^2.3.3 => 2.3.3

**Comment by luckyadam** [comment]
没有复现，麻烦给个完整点的例子
