### ISSUE TITLE
h5端开启css module tabbar样式之类的加载不进来

### ISSUE THREAD

**Issue by cherish553** [NervJS/taro#6779]

**Comment by chuyun** [comment]
一样遇到了 Swiper img 这些都不行

**Comment by ZakaryCode** [comment]
具体版本是？

**Comment by cherish553** [comment]
2.2.9&nbsp;2.2.8都有


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zakary"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 上午10:54
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"cherish"<673010805@QQ.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] h5端开启css module tabbar样式之类的加载不进来 (#6779)





 
具体版本是？

**Comment by ZakaryCode** [comment]
未能复现该问题，如果升级依旧存在该问题，可以尝试提交一个能够稳定复现的样例

**Comment by mya12321** [comment]
> 未能复现该问题，如果升级依旧存在该问题，可以尝试提交一个能够稳定复现的样例

我提了一个新issue, 里面有完整的示例. #6947

**Comment by zlpoot** [comment]
2.2.10也有这个问题，开启cssModules后，H5端所有@tarojs/components里组件的样式都丢失了
