### ISSUE TITLE
taro 官方能不能加入 支持 concent库

### ISSUE THREAD

**Issue by liuxingpluck** [NervJS/taro#6781]
### 期望行为
taro 官方能不能加入 支持 concent库
这是 concent git 地址
https://github.com/concentjs/concent/blob/master/README.zh-CN.md

希望能有一种方便 的接入该库，进行状态管理的教程

**Comment by Chen-jj** [comment]
@liuxingpluck taro3 里应该可以直接使用，可以先试试
