### ISSUE TITLE
2.29 微信编译hook组件引入Config类型情况下编译会引发usingComponents错误

### ISSUE THREAD

**Issue by mydaoyuan** [NervJS/taro#6789]
### 问题描述

引入Config类型 进行配置编译报错，项目是脚手架生成，选择项 typescript 、 saas、mobx。

### 复现步骤

使用conifg类型即可复现。
![image](https://user-images.githubusercontent.com/16152141/85496301-a60eb300-b60e-11ea-80ec-68d00d3ddbc6.png)

直接ding'yi定义可以正常编译，但是ts检测会报错
![image](https://user-images.githubusercontent.com/16152141/85496431-d9e9d880-b60e-11ea-9086-7cc333bcf569.png)

```js
import Taro, { Config } from "@tarojs/taro";
import { View } from "@tarojs/components";
function Index() {
  return <View>2222</View>;
}
let config: Config = {
  navigationStyle: "custom"
};
Index.config = config;
export default Index;

```

### 期望行为

没有报错
### 报错信息

🙅   编译失败.

Cannot read property 'usingComponents' of undefined
### 系统信息

👽 Taro v2.2.9

  Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.9 => 2.2.9 
      @tarojs/components-qa: 2.2.9 => 2.2.9 
      @tarojs/mini-runner: 2.2.9 => 2.2.9 
      @tarojs/mobx: 2.2.9 => 2.2.9 
      @tarojs/mobx-h5: 2.2.9 => 2.2.9 
      @tarojs/plugin-sass: 2.2.9 => 2.2.9 
      @tarojs/plugin-terser: 2.2.9 => 2.2.9 
      @tarojs/router: 2.2.9 => 2.2.9 
      @tarojs/taro: 2.2.9 => 2.2.9 
      @tarojs/taro-alipay: 2.2.9 => 2.2.9 
      @tarojs/taro-h5: 2.2.9 => 2.2.9 
      @tarojs/taro-qq: 2.2.9 => 2.2.9 
      @tarojs/taro-quickapp: 2.2.9 => 2.2.9 
      @tarojs/taro-swan: 2.2.9 => 2.2.9 
      @tarojs/taro-tt: 2.2.9 => 2.2.9 
      @tarojs/taro-weapp: 2.2.9 => 2.2.9 
      @tarojs/webpack-runner: 2.2.9 => 2.2.9 
      eslint-config-taro: 2.2.9 => 2.2.9 
      eslint-plugin-taro: 2.2.9 => 2.2.9 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.9 => 2.2.9 
      stylelint-taro-rn: 2.2.9 => 2.2.9 
    npmGlobalPackages:
      typescript: 2.1.5
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by luckyadam** [comment]
```tsx
import Taro, { Config } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { observer } from '@tarojs/mobx'

function Index () {
  return <View>2222</View>
}
Index.config = {
  navigationStyle: 'custom'
} as Config

export default observer(Index)

```

这样写吧

**Comment by mydaoyuan** [comment]
> ```tsx
> import Taro, { Config } from '@tarojs/taro'
> import { View } from '@tarojs/components'
> import { observer } from '@tarojs/mobx'
> 
> function Index () {
>   return <View>2222</View>
> }
> Index.config = {
>   navigationStyle: 'custom'
> } as Config
> 
> export default observer(Index)
> ```
> 
> 这样写吧

![image](https://user-images.githubusercontent.com/16152141/86196179-402da880-bb85-11ea-8cf3-602e723a5790.png)


这样写还是会报错。

**Comment by mydaoyuan** [comment]
TS的报错如下
```
module Index
function Index(): JSX.Element
类型“typeof Index”的参数不能赋给类型“ITaroComponent<any>”的参数。
  不能将类型“typeof Index”分配给类型“FunctionComponent<any>”。
    属性“config”的类型不兼容。
      不能将类型“{ navigationStyle: string; }”分配给类型“Config”。
        属性“navigationStyle”的类型不兼容。
          不能将类型“string”分配给类型“"default" | "custom" | undefined”。ts(2345)
```

![image](https://user-images.githubusercontent.com/16152141/86196285-8125bd00-bb85-11ea-86b5-563437049bf0.png)

**Comment by CeleKing** [comment]
`import Taro, { Config } from "@tarojs/taro";
import { View } from "@tarojs/components";
interface IndexProps {
  config?: Config
}
const Index: Taro.FC<IndexProps> = () => {
  return <View>2222</View>;
}
Index.config =  {
  navigationStyle: "custom"
};
export default Index;`
