### ISSUE TITLE
在开发过程中，TaroJS的node版本以及操作系统平台有没有要求呢？

### ISSUE THREAD

**Issue by LaiHuanMin** [NervJS/taro#679]
我的开发环境如下：   
1, Ubuntu 16.04 LTS   
2, Node 8.4.0 || 10.8.0  
3, yarn 1.1.0 || npm 6.2.0   

发现在Ubuntu的vscode里，查看taro-cli init的项目代码里，中文好像乱码了，可能是因为BOM+UTF8导致乱码的，想问一下tarojs对开发者的node版本以及操作系统有没有啥要求呢？     
希望taro越来越好

**Comment by luckyadam** [comment]
node 大于 8 以上就行，但是 linux 的系统我们还没有测试过，不过理论上应该对系统不会有啥要求

**Comment by LaiHuanMin** [comment]
好的，谢谢 @luckyadam

**Comment by kid1412621** [comment]
Linux 上热更新界面渲染有问题， VSCode latest stable version, Ubuntu 18.10
