### ISSUE TITLE
Button组件，赋动态值报错

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#6791]
### 问题描述 
在组件中使用Button，通过props传入动态值，将动态值放到Button中，会报错，偶尔报错，刷新几次必定会出现
![1](https://user-images.githubusercontent.com/52092826/85499940-220bf980-b615-11ea-98e1-fd09f75e55bb.png)

### 复现步骤
1、组件中使用 
```
<Button>{text}</Button>
```
2、外部调用该组件，传入text
```
<FormBtn text={btnText} />
```
btnText为动态值
3、h5界面，多刷新几次必定出现

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by cpocar** [comment]
动态内容外面包上一层标签就不报错了
```
<Button><Text>{text}</Text></Button>
```

**Comment by Chen-jj** [comment]
@cpocar 版本多少？

**Comment by cpocar** [comment]
3.0.0-rc.6

**Comment by Chen-jj** [comment]
复现不了，升级到最新版本再试试吧，如果还有问题，提供一下可复现代码。

```js
import React, { useState } from 'react'
import { View, Text } from '@tarojs/components'
import Test from '../../components/test'

import './index.css'

export default function () {
  const [ btnText, setBtnText ] = useState(1)

  return (
    <View className='index'>
      <Text onClick={() => setBtnText(btnText + 1)}>Hello world!</Text>
      <Test text={btnText} />
    </View>
  )
}
```

```js
import React from 'react'
import { Button } from '@tarojs/components'

export default function ({ text }) {
  return (
    <Button>{text}</Button>
  )
}
```

![image](https://user-images.githubusercontent.com/11807297/86891187-02a2bf80-c131-11ea-8cd8-2e094c53c9df.png)

**Comment by Fancy-X** [comment]
我这边自己封装组件，通过children的形式传进去的话也会包这个错，不知怎么解
