### ISSUE TITLE
Taro2.2.7 多维数组条件判断渲染失败

### ISSUE THREAD

**Issue by 54853315** [NervJS/taro#6795]
#问题覆盖版本

在Taro2.2.6中也遇到了，后升级为2.2.7，问题仍然存在。

# 问题描述

![image](https://user-images.githubusercontent.com/1081252/85544439-9a8eac80-b64d-11ea-95c9-598af6967b06.png)

此问题是偶发的，我在列表页和详情页都采用了这种二维数组条件渲染的方式，列表页没有问题（不知道跟嵌套map有没有关系，列表页面是肯定要递归列表数据，在每一个递归中再递归具体需要递归的子数据），详情页有问题（详情页不需要像列表页那样递归列表数据，因为没有列表数据，所以只有一个递归处理，就是出问题的这个tags）。

# 问题复述

接口返回的数据结构：

{
id: 2
tags: null
//其他省略
}

> 为了测试，我们假定接口返回的tags一定为null。

jsx代码：
```
{/* 标签 */}
              {itemInfo.tags && itemInfo.tags.map(tag => {
                return (
                  <AtTag>
                    {tag.name}
                  </AtTag>
                );
              })}
```

报错提示语句`TypeError: Cannot read property 'map' of null`

解析后的item.js  问题行： `var loopArray11 = itemInfo ? itemInfo.tags.map(function (tag, _anonIdx) {`

可以看出，*taro解析时没有按照我选择的条件进行判断*，而是直接用了itemInfo。为了测试这一观点，我进行了如下改动：

```
var tags = null;
console.log("before",tags);/null
if (itemInfo){
     tags = itemInfo.tags;
}
console.log("after",tags);//null
 {tags && tags.map(tag => {
                return (
                  <AtTag>
                    {tag.name}
                  </AtTag>
                );
              })}
```

解析结果仍然是` itemInfo ? itemInfo.tags.map`……

# 尝试过什么

我尝试将Taro2.2.6升级为2.2.7，问题依旧。
我怀疑热编译问题，所以重新yarn dev:weapp，问题依旧。

# 问题原因

经过多次调试，发现这个问题是因为最外层有一个条件渲染包裹，导致里边所有的条件渲染都被迫强制使用最外层都条件了。

![image](https://user-images.githubusercontent.com/1081252/85545156-43d5a280-b64e-11ea-9b59-7deae61d5ebf.png)

**Comment by cathe-zhang** [comment]
+1 +1 +1
