### ISSUE TITLE
组件加载运行问题

### ISSUE THREAD

**Issue by alwaysRemember** [NervJS/taro#6796]
### 复现步骤

1. 新增一个页面
2. 在app.tsx中的配置中引入页面路径

```js
pages: [
    "pages/Global/index",
    "pages/Home/index",
    "pages/Login/index",
    "pages/PersonalCenter/index"
  ],

```
当我访问 pages/Global/index  这个路径的时候，为什么我Login/index中的代码会执行，明明访问的路径不是login
```
login.tsx

const Login: { config: Config } = () => {
  console.log("in login");
}
export default Login;
```
页面中会打印 in login

### 系统信息

Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.9 => 2.2.9 
      @tarojs/components-qa: 2.2.9 => 2.2.9 
      @tarojs/mini-runner: 2.2.9 => 2.2.9 
      @tarojs/plugin-less: 2.2.9 => 2.2.9 
      @tarojs/plugin-sass: ^2.2.9 => 2.2.9 
      @tarojs/plugin-terser: 2.2.9 => 2.2.9 
      @tarojs/redux: ^2.2.9 => 2.2.9 
      @tarojs/redux-h5: ^2.2.9 => 2.2.9 
      @tarojs/router: 2.2.9 => 2.2.9 
      @tarojs/taro: 2.2.9 => 2.2.9 
      @tarojs/taro-alipay: 2.2.9 => 2.2.9 
      @tarojs/taro-h5: 2.2.9 => 2.2.9 
      @tarojs/taro-qq: 2.2.9 => 2.2.9 
      @tarojs/taro-quickapp: 2.2.9 => 2.2.9 
      @tarojs/taro-swan: 2.2.9 => 2.2.9 
      @tarojs/taro-tt: 2.2.9 => 2.2.9 
      @tarojs/taro-weapp: 2.2.9 => 2.2.9 
      @tarojs/webpack-runner: 2.2.9 => 2.2.9 
      eslint-config-taro: 2.2.9 => 2.2.9 
      eslint-plugin-taro: 2.2.9 => 2.2.9 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.9 => 2.2.9 
      stylelint-taro-rn: 2.2.9 => 2.2.9 
      taro-ui: ^2.3.4 => 2.3.4 
    npmGlobalPackages:
      typescript: 3.1.6

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by cathe-zhang** [comment]
+1 同遇到

**Comment by Chen-jj** [comment]
为了给小程序 Page 构造器的 data 属性赋值，需要先运行组件的 constructor 和 render，函数式组件在 Taro 1、2 中会被编译成 Class Component。https://nervjs.github.io/taro/docs/2.2.8/best-practice#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8
