### ISSUE TITLE
官方redux示例中num未显示

### ISSUE THREAD

**Issue by innocces** [NervJS/taro#68]
![bug1](https://user-images.githubusercontent.com/38065966/41216368-a6de1fe6-6d86-11e8-9954-a7bb3af88d1f.png)
![bug2](https://user-images.githubusercontent.com/38065966/41216369-a94a7b58-6d86-11e8-9708-9253c0fdbc40.png)
小程序编译后的页面不出现num的值；代码全部是按照文档中的示例来的

**Comment by luckyadam** [comment]
是个bug，bug已经定位，下个版本修复
这样写可以展示~
```javascript
render () {
    const num = this.props.counter.num
    return (
      <View className='index'>
        <Button className='add_btn' onClick={this.props.add}>+</Button>
        <Button className='dec_btn' onClick={this.props.dec}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View>{num}</View>
      </View>
    )
  }
```

**Comment by innocces** [comment]
刚刚编译成H5的时候同样也不出来，我在DidMount里输出了一下，发现props为空

**Comment by luckyadam** [comment]
你有安装引用什么依赖包么

**Comment by innocces** [comment]
第一次编译H5的时候报错nexv-redux没有找到，单独安装了一下，可以跑；=。-  刚刚切换编译小程序也报错， 而且每次报错的时候丢失的依赖包名都不一样~~  是不是需要重新初始化一个项目呢

**Comment by luckyadam** [comment]
嗯~ 要不把 `node_modules` 删了，然后清一下 npm 缓存，再重新安装下依赖试试~

**Comment by innocces** [comment]
=。-  安装了好几次都不行，只要安装新的依赖就会出错 =。-  可能是window的问题

**Comment by yuche** [comment]
把你整个 clone 下来的项目删除，然后装最新版本，应该修复了这个问题。
