### ISSUE TITLE
Unable to resolve expo" from "./F:\\xxx\\.rn_temp\\bin\\crna-entry.js"

### ISSUE THREAD

**Issue by hellotiger** [NervJS/taro#680]
![qq 20180922104146](https://user-images.githubusercontent.com/5555873/45912471-683a9480-be54-11e8-9465-0a30abbe05ec.png)

**Comment by hellotiger** [comment]
运行 npm run dev:rn
这是哪里出问题了？

**Comment by luckyadam** [comment]
Taro 版本多少

**Comment by hellotiger** [comment]
> Taro 版本多少

1.0.3

**Comment by hellotiger** [comment]
> development server 500，编译的时候要报错吗？截一下图。

![qq 20180923090657](https://user-images.githubusercontent.com/5555873/45923137-2a9b4180-bf10-11e8-97d7-9be04763aff7.png)
![qq 20180923090721](https://user-images.githubusercontent.com/5555873/45923138-2d963200-bf10-11e8-87bd-7568df10356f.png)
![qq 20180923090934](https://user-images.githubusercontent.com/5555873/45923152-79e17200-bf10-11e8-901a-c23c83597438.png)

如图

**Comment by Pines-Cheng** [comment]
确定 .rn_temp 目录下的 Taro 相关的依赖是不是也是 1.0.3，然后进入 .rn_temp 目录，重新安装一下依赖。

**Comment by hellotiger** [comment]
> 确定 .rn_temp 目录下的 Taro 相关的依赖是不是也是 1.0.3，然后进入 .rn_temp 目录，重新安装一下依赖。

是1.0.3 如何重新安装依赖

**Comment by hellotiger** [comment]
[package_versions.txt](https://github.com/NervJS/taro/files/2408339/package_versions.txt)
.rn_temp\node_modules 下的文件

**Comment by hellotiger** [comment]
![11](https://user-images.githubusercontent.com/5555873/45925406-11fa4e00-bf47-11e8-8286-aea13db417d9.png)
按照你说的 进入 .rn_temp 目录，删除 node_modules ，然后执行 npm install 命令
再回到项目根目录 执行 npm run dev:rn 就报错。郁闷 什么都没动，直接拿着创建的模板编译的。

**Comment by Pines-Cheng** [comment]
工程目录下也执行同样的操作试一试。

**Comment by hellotiger** [comment]
> 工程目录下也执行同样的操作试一试。

一样的

**Comment by hellotiger** [comment]
![qq 20180923155703](https://user-images.githubusercontent.com/5555873/45925529-d8771200-bf49-11e8-9e52-167a123042c0.png)
.rn_temp 目录 npm install

**Comment by hellotiger** [comment]
工程根目录 npm install
![qq 20180923155907](https://user-images.githubusercontent.com/5555873/45925537-0f4d2800-bf4a-11e8-8426-e39751fcfd5c.png)

**Comment by hellotiger** [comment]
npm run dev:rn 编译后 
删除 .rn_temp 目录下 node_modules ，
清除npm缓存（npm cache clean --force），然后执行 npm install 命令，
再运行npm run dev:rn 可以了。

**Comment by dullbear** [comment]
重装咯n遍，也按照上面的方案整咯，还是 一样~~


taro 1.1.9

**Comment by 601939654** [comment]
我也同样的问题，我编译微信小程序没有问题，使用npm run dev:rn就跟上面一样的错误，我也尝试你们提示的办法去做，还是报错。
另外，我重新taro init项目也是同样的错误。
win10、taro 1.2.0、npm 6.4.1、node  10.14.0
请问要如何解决？

**Comment by liyang001** [comment]
按照这个操作，删除.rn_temp 目录下 node_modules ，清除缓存，执行 npm install 命令，再运行npm run dev:rn ，还是不行

**Comment by liyang001** [comment]
删除.rn_temp 下node_modules ，重新npm install 安装注意一定是cnpm可能会有问题，尽量避免，重新npm run dev:rn 可以了
