### ISSUE TITLE
小程序插件开发

### ISSUE THREAD

**Issue by Ninja-Xu** [NervJS/taro#6803]
### 问题描述

按照官网的教程来配置，微信开发者工具中提示“未找到入口 plugin.json 文件，或者文件读取失败，请检查后重新编译。”

### 复现步骤

1.  sudo taro init test
? 请输入项目介绍！ A weapp plugin
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Less
? 请选择模板 wxplugin
2. 修改 project.conf.json 的 appid 字段和 src/app.js 的 prodiver 字段为同一 appid。
3. taro build --plugin weapp --watch
4. 在微信开发者工具中添加 Taro 插件项目根目录。

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */


```

### 期望行为

可以正常运行

### 报错信息

![image](https://user-images.githubusercontent.com/18298032/85918800-66f39280-b898-11ea-9f78-8b23556ae9b0.png)

### 系统信息

👽 Taro v2.2.8

  Taro CLI 2.2.8 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.8 => 2.2.8 
      @tarojs/components-qa: 2.2.8 => 2.2.8 
      @tarojs/mini-runner: 2.2.8 => 2.2.8 
      @tarojs/plugin-less: 2.2.8 => 2.2.8 
      @tarojs/plugin-terser: 2.2.8 => 2.2.8 
      @tarojs/router: 2.2.8 => 2.2.8 
      @tarojs/taro: 2.2.8 => 2.2.8 
      @tarojs/taro-alipay: 2.2.8 => 2.2.8 
      @tarojs/taro-h5: 2.2.8 => 2.2.8 
      @tarojs/taro-qq: 2.2.8 => 2.2.8 
      @tarojs/taro-quickapp: 2.2.8 => 2.2.8 
      @tarojs/taro-swan: 2.2.8 => 2.2.8 
      @tarojs/taro-tt: 2.2.8 => 2.2.8 
      @tarojs/taro-weapp: 2.2.8 => 2.2.8 
      @tarojs/webpack-runner: 2.2.8 => 2.2.8 
      eslint-config-taro: 2.2.8 => 2.2.8 
      eslint-plugin-taro: 2.2.8 => 2.2.8 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by EyeShield29** [comment]
按照编译生成的文件目录层级将project.config.json中"pluginRoot": "plugin/"
修改为"pluginRoot": "miniprogram/miniprogram/plugin/" 就可以了

**Comment by Ninja-Xu** [comment]
> 按照编译生成的文件目录层级将project.config.json中"pluginRoot": "plugin/"
> 修改为"pluginRoot": "miniprogram/miniprogram/plugin/" 就可以了

感谢！
