### ISSUE TITLE
taro不支持百度小程序最新的onInit生命周期函数吗？升级到最新的2.2.9版本也不支持

### ISSUE THREAD

**Issue by lisswn** [NervJS/taro#6813]
taro不支持百度小程序最新的onInit生命周期函数吗？使用最新的2.2.9版本taro创建的小程序也不支持，在使用百度原生语法创建的小程序中是可以正常使用onInit函数的，文档不是说可以taro语法和原生语法混写吗，但是taro页面中使用onInit函数不生效

**Comment by luckyadam** [comment]
可以提升一下

**Comment by lisswn** [comment]
> 可以提升一下

是需要升级到3.x的版本才支持吗

**Comment by SyMind** [comment]
这个 issue 关闭吧，taro3 在百度小程序中已经使用 onInit 生命周期用于初始化整个 react 实例。
