### ISSUE TITLE
Taro.showToast在微信小程序中的自定义image图片显示失败

### ISSUE THREAD

**Issue by PresByter2015** [NervJS/taro#6816]
### 问题描述
Taro.showToast在微信小程序中的自定义image图片显示失败

### 复现步骤

1. 引入图片
2. 使用 Taro.showToast
3. 显示失败
4. 使用 image 是成功的

```js
/**
 * 这段注释后可以贴代码
 * 提供完整可复现的代码和整理好代码格式，有助于我们快速定位问题，节省你我时间
 * 代码提供不全或代码格式混乱的 issues 【有可能会被忽略】
 * 
 * 查看如何插入代码：https://coding.net/help/doc/project/markdown.html#i-5
 */

Taro.showToast({
            title: title,
            image: '../assets/images/error.png',
            mask: true,
            duration: 1000
        })
```

### 期望行为

成功显示图片
### 报错信息

无
### 系统信息

Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.9 => 2.2.9 
      @tarojs/components-qa: 2.2.9 => 2.2.9 
      @tarojs/mini-runner: 2.2.9 => 2.2.9 
      @tarojs/mobx: 2.2.9 => 2.2.9 
      @tarojs/mobx-h5: 2.2.9 => 2.2.9 
      @tarojs/plugin-sass: 2.2.9 => 2.2.9 
      @tarojs/plugin-terser: 2.2.9 => 2.2.9 
      @tarojs/router: 2.2.9 => 2.2.9 
      @tarojs/taro: 2.2.9 => 2.2.9 
      @tarojs/taro-alipay: 2.2.9 => 2.2.9 
      @tarojs/taro-h5: 2.2.9 => 2.2.9 
      @tarojs/taro-qq: 2.2.9 => 2.2.9 
      @tarojs/taro-quickapp: 2.2.9 => 2.2.9 
      @tarojs/taro-swan: 2.2.9 => 2.2.9 
      @tarojs/taro-tt: 2.2.9 => 2.2.9 
      @tarojs/taro-weapp: 2.2.9 => 2.2.9 
      @tarojs/webpack-runner: 2.2.9 => 2.2.9 
      eslint-config-taro: 2.2.9 => 2.2.9 
      eslint-plugin-taro: 2.2.9 => 2.2.9 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.9 => 2.2.9 
      stylelint-taro-rn: 2.2.9 => 2.2.9 
### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by PresByter2015** [comment]
已解决

**Comment by xiaoxiaodemeng** [comment]
咋解决的

**Comment by duobancc** [comment]
> 咋解决的

把图片资源import 导入
