### ISSUE TITLE
页面或组件使用 useReady 编译后，在微信调试工具里报错误：TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by puxiao** [NervJS/taro#6818]
### 问题描述

页面或组件使用 useReady 编译后，在微信调试工具里报错误：TypeError: Object(...) is not a function

### 复现步骤

1. 安装 Tarojs/cli@next  (本人安装的版本是 3.0.0-rc.6 )，使用 cli 初始化一个项目。
2. 项目选择使用 React 和 TypeScript。
2. 新建一个页面或组件，使用 useReady 。
3. 编译这个页面，在 微信调试工具中 访问这个页面
4. 微信调试工具中报错误：TypeError: Object(...) is not a function

```js
import React from 'react'
import { View } from '@tarojs/components'
import { useReady } from '@tarojs/taro'

const UserPage: React.FC<{}> = () => {
  useReady(() =>{
  })

  return (
    <View>
    </View>
  )
}

export default UserPage
```

### 期望行为

希望找出错误原因，并早些解决。

### 报错信息

TypeError: Object(...) is not a function
    at b (index.js:1)
    at jn (app.js:2)
    at al (app.js:2)
    at oi (app.js:2)
    at ai (app.js:2)
    at Jl (app.js:2)
    at app.js:2
    at t.unstable_runWithPriority (app.js:2)
    at ht (app.js:2)
    at yt (app.js:2)

### 系统信息

Taro v3.0.0-rc

  Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.0 - D:\program files (x86)\nodejs\node.EXE
      npm: 6.13.4 - D:\program files (x86)\nodejs\npm.CMD

### 补充信息

本人使用的是 React 函数组件，非 类组件。

**Comment by cncolder** [comment]
当前版本没有导出 useReady, 下个版本修复 https://github.com/NervJS/taro/pull/6810
