### ISSUE TITLE
[2.0.4]在 ScrollView 下 Image 的 lazyLoad 属性不生效

### ISSUE THREAD

**Issue by Kimbohn** [NervJS/taro#6823]
### 问题描述
在ScrollView下 Image 的 lazyLoad 属性不生效

```
<ScrollView>
    { 
        imageList.map(item => (
            <Image key={item.id} src={item.img} lazyLoad onLoad={() => console.log(item.id)} />
    ))
} 
</ScrollView>

```

### 期望行为

图片出现在可视范围内才加载图片资源

**Comment by luckyadam** [comment]
lazyload

**Comment by Kimbohn** [comment]
> lazyload

什么意思 ? lazyLoad 的 L 小写的意思吗 ?

**Comment by Kimbohn** [comment]
> > lazyload
> 
> 什么意思 ? lazyLoad 的 L 小写的意思吗 ? 能不能解释详细一点

**Comment by Kimbohn** [comment]
> > lazyload
> 
> 能不能解释详细一点

**Comment by Kimbohn** [comment]
https://github.com/NervJS/taro/issues/3487#issuecomment-503818614
