### ISSUE TITLE
[3.0.0-rc.6]页面未设置任何分享时，自动默认开启了分享

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#6825]
### 问题描述

分享被默认全局开启，在页面未调用 `useShareAppMessage` 时, 页面依然会分享

### 复现步骤

1. yarn global add @tarojs/cli
2. taro init
3. 选择 `typescript` + 默认模板

### 期望行为

页面未主动开启分享时，不应默认开启分享

### 报错信息

无

### 系统信息

Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2
      Yarn: 1.22.4
      npm: 6.14.4

### 补充信息

> 如果您有功能上的建议，可以提到 [FeatHub](https://feathub.com/NervJS/taro)
> 
> 使用上的问题，欢迎在[「Taro 社区」](https://taro-club.jd.com/)一起交流

**Comment by Arima-P** [comment]
遇到相同的问题

**Comment by cncolder** [comment]
看来 `taroHooks` 里需要另起一个 `useEffect` 专门处理 `useShareAppMessage`.

**Comment by Chen-jj** [comment]
现在 Page 构造器会默认注册上 onShareAppMessage 回调，但默认注册会另页面出现可分享按钮。

3.0.3 开始这里会有一个 **[Breaking Change]**，必须给页面组件设置 enableShareAppMessage 属性为 true，告诉 Taro 这个页面需要注册 onShareAppMessage 回调。

```js
// class component
class Index extends Component {
  static enableShareAppMessage = true

  onShareAppMessage () {}
}

// functional component
function Index {
  useShareAppMessage(() => {})
}
Index.enableShareAppMessage = true
```

onShareTimeline 生命周期也同理。

**Comment by fjc0k** [comment]
> 现在 Page 构造器会默认注册上 onShareAppMessage 回调，但默认注册会令页面出现可分享按钮。
> 
> 3.0.3 开始这里会有一个 **[Breaking Change]**，必须给页面组件设置 enableShareAppMessage 属性为 true，告诉 Taro 这个页面需要注册 onShareAppMessage 回调。
> 
> ```js
> // class component
> class Index extends Component {
>   static enableShareAppMessage = true
> 
>   onShareAppMessage () {}
> }
> 
> // functional component
> function Index {
>   useShareAppMessage(() => {})
> }
> Index.enableShareAppMessage = true
> ```
> 
> onShareTimeline 生命周期也同理。

为啥不在 page.config.ts 里配置呢，这样的话，类型很不友好，而且跟目前的页面配置也很割裂。

**Comment by Chen-jj** [comment]
有道理，应该可以做，我们再看看
