### ISSUE TITLE
微信低版本编译报错

### ISSUE THREAD

**Issue by ldwonday** [NervJS/taro#684]
在微信基础库为2.0以下之间，编译都会报错，具体错误如下：
![image](https://user-images.githubusercontent.com/4630157/45922733-199a0280-bf07-11e8-9062-9537f2a401cb.png)

具体可见demo运行：[https://github.com/zuoge85/taro-dva](https://github.com/zuoge85/taro-dva)，小程序基础库选择2.0以下。

**Comment by ldwonday** [comment]
@luckyadam

**Comment by ldwonday** [comment]
这个问题处理方式已经注意到了，但是因为是引用了dva，所以不太好改。

**Comment by ldwonday** [comment]
我试过了mina框架还有wxapp-boilerplate和dva结合的例子，他们低版本的微信都是没有问题的，所以，我认为（不一定正确）应该是我们的taro/redux哪里写的有问题。希望官方可以早日解决这个问题。。

**Comment by ldwonday** [comment]
@luckyadam 谢谢回答。[mina-webpack](https://github.com/tinajs/mina-webpack)，mina是一个类似vue的小程序开发框架。

**Comment by ldwonday** [comment]
是少了new webpack.optimize.ModuleConcatenationPlugin();这个插件吗？

**Comment by ldwonday** [comment]
@luckyadam 我自己fork了一份dva-core的代码，修改了saga的引入方式，现在可以了，但是项目其他有嵌套引用的地方还是报错，所以根本原因我们要解决嵌套引用的问题，用webpack打包小程序，不然小程序只能支持2.0以上的，但是现在很多人还是基础库2.0以下的。

**Comment by luckyadam** [comment]
嗯嗯，后续有计划小程序端使用 webpack 来进行打包

**Comment by zuoge85** [comment]
@luckyadam 你是怎么解决的。我好提交更新过去

**Comment by guozefei** [comment]
请问这个问题现在解决了 有什么解决方案吗 微信小程序要兼容2.0以下基础库的话？
