### ISSUE TITLE
【v3.0.0】 初始化项目 npm run dev:h5 报错

### ISSUE THREAD

**Issue by az031120103** [NervJS/taro#6843]
v3.0.0 初始化项目 npm run dev:h5 报错，错误信息如下
![image](https://user-images.githubusercontent.com/6166283/86197100-4b81d380-bb87-11ea-9a8c-98eb4309e5c7.png)
系统，taro-cli 版本信息
![image](https://user-images.githubusercontent.com/6166283/86197196-779d5480-bb87-11ea-8750-e4efd517d43b.png)
麻烦看下

**Comment by catalsdevelop** [comment]
同样的问题，weapp 是没问题的。

**Comment by SilentFlute** [comment]
- 系统: win10
- node: v12.16.3
- npm: 6.14.4
- yarn: 1.22.4

1. yarn global add @taro/cli
2. taro init myApp
3. cd myApp
4. yarn dev:h5

报错:
```
./src/app.js
Module not found: Can't resolve '@tarojs/components' in
```
直接初始化一个项目出来都会报错, 求解决~~

**Comment by Chen-jj** [comment]
我们尽快发个版修复吧
