### ISSUE TITLE
升级 3.0 后 Cannot access 'window$1' before initialization

### ISSUE THREAD

**Issue by dpyzo0o** [NervJS/taro#6848]
**问题描述**
项目从 `3.0.0-beta.5` 升级到 `3.0.0` 后, 启动项目后报错, 无法进行预览, 控制台报错

<img width="710" alt="Screen Shot 2020-07-01 at 12 29 08" src="https://user-images.githubusercontent.com/24768249/86203037-7d4e6680-bb96-11ea-9d3a-d02719ded0e5.png">

**期望行为**
可以正常运行

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

Taro CLI 3.0.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.0 => 3.0.0 
      @tarojs/components: ^3.0.0 => 3.0.0 
      @tarojs/mini-runner: ^3.0.0 => 3.0.0 
      @tarojs/react: ^3.0.0 => 3.0.0 
      @tarojs/runtime: ^3.0.0 => 3.0.0 
      @tarojs/taro: ^3.0.0 => 3.0.0 
      babel-preset-taro: ^3.0.0 => 3.0.0 
      eslint-config-taro: ^3.0.0 => 3.0.0 
      react: ^16.13.1 => 16.13.1 

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shenghanqin** [comment]
请问是哪一端？

**Comment by dpyzo0o** [comment]
> 请问是哪一端？

weapp

**Comment by dpyzo0o** [comment]
复现demo: https://github.com/dpyzo0o/taro-toolkit/tree/taro-issue, taro-issue分支升级到3.0了，无法运行。taro-next 分支是beta5，可以运行

**Comment by Chen-jj** [comment]
@dpyzo0o 

解决办法，开一个 babel.config.js 文件放 babel 配置。

猜测：

![image](https://user-images.githubusercontent.com/11807297/86218510-741fc280-bbb3-11ea-9f62-5f98afaabfba.png)

babel7 中，package.json 里的 babel 配置是文件相关范围的，current file 向上找到 package.json 则停止。

你这样写，node_modules 里 taro 相关依赖是没有被编译的。即使 beta.5 我觉得你的 node_modules taro 相关代码也没有编译。

为什么现在有问题，是因为 taro-runtime 加了点东西，兜兜转转用到了 corejs 的 **_global.js**，这个函数需要使用到 providePlugin 注入的 window 对象。又因为 taro-runtime 没走编译，还是使用 const 定义 window 对象，所以报错。

如果你退回 beta.5，看 dist/taro.js 里打包的 taro-runtime 函数，里面使用了 const、class 等语法，应该能证明猜想是对的。

**Comment by dpyzo0o** [comment]
@Chen-jj 非常感谢，确实是这个原因，babel 配置必须要放在 project-wide configuration 里面。
