### ISSUE TITLE
支付宝小程序客户端编译失败

### ISSUE THREAD

**Issue by wiiler** [NervJS/taro#6854]
**问题描述**
![image](https://user-images.githubusercontent.com/9715482/86105328-c698aa80-baf1-11ea-91ed-4db64019da0a.png)

包版本：
"@tarojs/components": "2.2.7",
    "@tarojs/components-qa": "2.2.7",
    "@tarojs/redux": "2.2.7",
    "@tarojs/redux-h5": "2.2.7",
    "@tarojs/router": "2.2.7",
    "@tarojs/taro": "2.2.7",
    "@tarojs/taro-alipay": "2.2.7",
    "@tarojs/taro-h5": "2.2.7",
    "@tarojs/taro-qq": "2.2.7",
    "@tarojs/taro-quickapp": "2.2.7",
    "@tarojs/taro-swan": "2.2.7",
    "@tarojs/taro-tt": "2.2.7",
    "@tarojs/taro-weapp": "2.2.7",
    "babel-runtime": "^6.26.0",
    "nerv-devtools": "^1.5.5",
    "nervjs": "^1.5.5",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "regenerator-runtime": "0.11.1",
    "taro-ui": "^2.3.4"
系统：
macos
支付宝小程序客户端：
1.12.15

**Comment by wiiler** [comment]
有人在吗

**Comment by Chen-jj** [comment]
@wiiler 请提供可复现代码
