### ISSUE TITLE
[Taro 3.0.0] 多端文件引入问题

### ISSUE THREAD

**Issue by charmtiger** [NervJS/taro#6855]
**问题描述**
从 rc6 升级到 正式版 3.0.0 后，出现两个问题，都出现在编译过程

1、h5 环境中 index.h5.ts 中无法引入导出 Header.weapp.ts 
2、h5 环境中 无法使用 通用的  Header.ts ，只有额外复制一个  Header.h5.ts 才行

**复现步骤**

index.h5.ts
```js
export * from './index.weapp';
```

**报错信息**
```
ℹ️  Listening at http://0.0.0.0:10086/

监听文件修改中...

🙅   Failed to compile.

./src/cross/components/Image.tsx
Module not found: Can't resolve '@tarojs/components' in '/Users/mac/Work/Mengti/miniwork/src/cross/components'
```

**系统信息**

  Taro CLI 3.0.0-alpha.7 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.config/yarn/global/node_modules/.bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.0 => 3.0.0 
      @tarojs/components: 3.0.0 => 3.0.0 
      @tarojs/taro: 3.0.0 => 3.0.0 
      @tarojs/webpack-runner: 3.0.0 => 3.0.0 
      eslint-config-taro: 3.0.0 => 3.0.0 
      nerv-devtools: ^1.5.6 => 1.5.6 
      nervjs: ^1.5.6 => 1.5.6 
      react: ^16.10.0 => 16.13.1

**Comment by Chen-jj** [comment]
@charmtiger 3.0.0 h5 编译有点问题，等等 3.0.1 再试试，#6843

**Comment by charmtiger** [comment]
好的
