### ISSUE TITLE
【Taro Next】在app.config.js里不能使用fs

### ISSUE THREAD

**Issue by GrasFishs** [NervJS/taro#6858]
问题描述
在app.config.js下，引入node的fs库，虽然能读取到，但不能通过编译。但若是指引入path库，则能通过编译。

复现步骤1
```js
import fs from "fs";
import path from "path";

console.log(fs.readdirSync(path.join(__dirname)));

export default {
  pages: ["pages/index/index"],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black"
  }
};
```
报错信息1
```
👽 Taro v3.0.0-rc.6

生成  工具配置  /Users/caoyu/Code/weapp/taro3/vue-test/dist/project.config.json

[
  'app.config.js',
  'app.js',
  'app.scss',
  'components',
  'index.html',
  'pages',
  'store'
]
编译  发现入口  src/app.js
编译  发现页面  src/pages/index/index.vue
🙅   编译失败.

./src/app.config.js
Module not found: Can't resolve 'fs' in '/Users/caoyu/Code/weapp/taro3/vue-test/src'

监听文件修改中...

./src/app.config.js
Module not found: Error: Can't resolve 'fs' in '/Users/caoyu/Code/weapp/taro3/vue-test/src'
resolve 'fs' in '/Users/caoyu/Code/weapp/taro3/vue-test/src'
  Parsed request is a module
  using description file: /Users/caoyu/Code/weapp/taro3/vue-test/package.json (relative path: ./src)
    resolve as module
      /Users/caoyu/Code/weapp/taro3/vue-test/src/node_modules doesn't exist or is not a directory
      /Users/caoyu/Code/weapp/taro3/node_modules doesn't exist or is not a directory
      /Users/caoyu/Code/weapp/node_modules doesn't exist or is not a directory
      /Users/caoyu/Code/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

复现步骤2
```js
import path from "path";

console.log(path.join(__dirname));

export default {
  pages: ["pages/index/index"],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black"
  }
};
```
编译信息2
```
👽 Taro v3.0.0-rc.6

生成  工具配置  /Users/caoyu/Code/weapp/taro3/vue-test/dist/project.config.json

/Users/caoyu/Code/weapp/taro3/vue-test/src
编译  发现入口  src/app.js
编译  发现页面  src/pages/index/index.vue
✅  编译成功


监听文件修改中...
```
系统信息

Taro CLI 3.0.0-rc.6 environment info:
System:
OS: macOS 10.15.5
Binaries:
Node: 12.16.3 
Yarn: 1.15.2 
npm: 6.14.4 
npmPackages:
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.0.0-rc.6",
    "@tarojs/runtime": "3.0.0-rc.6",
    "@tarojs/taro": "3.0.0-rc.6",
    "vue": "^2.5.0",
    "vue-template-compiler": "^2.5.0",
    "vuex": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/mini-runner": "3.0.0-rc.6",
    "@tarojs/webpack-runner": "3.0.0-rc.6",
    "@types/webpack-env": "^1.13.6",
    "babel-preset-taro": "3.0.0-rc.6",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.0.0-rc.6",
    "eslint-plugin-vue": "^6.x",
    "stylelint": "9.3.0",
    "vue-loader": "^15.9.2"
  }

**Comment by Chen-jj** [comment]
@GrasFishs Taro 的 webpack 配置里，target 不完全等同于 'node'，`fs` resolve 不到也是正常的。我们觉得配置文件不应该有过于复杂的逻辑，fs 读文件这种需求可以通过其它方法 walkaround。

**Comment by tourze** [comment]
> @GrasFishs Taro 的 webpack 配置里，target 不完全等同于 'node'，`fs` resolve 不到也是正常的。我们觉得配置文件不应该有过于复杂的逻辑，fs 读文件这种需求可以通过其它方法 walkaround。

类似题主这种问题，有啥办法可以解决？这种情景应该不会少见，如根据环境变量决定配置文件，决定pages的显示与隐藏。

**Comment by zephyr-66** [comment]
> > @GrasFishs Taro 的 webpack 配置里，target 不完全等同于 'node'，`fs` resolve 不到也是正常的。我们觉得配置文件不应该有过于复杂的逻辑，fs 读文件这种需求可以通过其它方法 walkaround。
> 
> 类似题主这种问题，有啥办法可以解决？这种情景应该不会少见，如根据环境变量决定配置文件，决定pages的显示与隐藏。

解决了吗？我也想控制pages进行打包 不同模板

**Comment by zephyr-66** [comment]
> @GrasFishs Taro 的 webpack 配置里，target 不完全等同于 'node'，`fs` resolve 不到也是正常的。我们觉得配置文件不应该有过于复杂的逻辑，fs 读文件这种需求可以通过其它方法 walkaround。

你好，3.x怎么在config.js使用preval

**Comment by EricWong1994** [comment]
> > > @GrasFishs Taro 的 webpack 配置里，target 不完全等同于 'node'，`fs` resolve 不到也是正常的。我们觉得配置文件不应该有过于复杂的逻辑，fs 读文件这种需求可以通过其它方法 walkaround。
> > 
> > 
> > 类似题主这种问题，有啥办法可以解决？这种情景应该不会少见，如根据环境变量决定配置文件，决定pages的显示与隐藏。
> 
> 解决了吗？我也想控制pages进行打包 不同模板

我也是想这样，之前taro2.0都是在app.js中用preval搞的，现在app.config.ts中preval就是not defined。不知道咋解决

**Comment by waycowei** [comment]
比如那个copy，不能import的话，我就只有维护两个一模一样的vant组件列表，分别写到app.config.ts和config/index.js里面，太挫了= =
