### ISSUE TITLE
2.1.5 eslint 如何修复语法报错提示

### ISSUE THREAD

**Issue by cole-yeah** [NervJS/taro#6861]
项目初始化之后
![image](https://user-images.githubusercontent.com/12606533/86228425-eba81e80-bbc0-11ea-93ab-1bfae03d7cf0.png)
报错信息：
`Expected "export" or "export default"`
尝试解决方法：在.eslintrc下添加了
`"env": {
    "node": true,
    "es6": true,
    "commonjs": true,
    "browser": true
  }` 
依然解决不了。不知道有没有相同情况的
编辑器：vs code

**Comment by hangCode2001** [comment]
换成es6 export就行了

**Comment by DreamTour** [comment]
在"env" 中加 es7:true 就好了

**Comment by DreamTour** [comment]
在"env" 中加 "es7":true 就好了
