### ISSUE TITLE
[3.0.0-rc.6] 虚拟列表VirtualList滚动出现抖动

### ISSUE THREAD

**Issue by lin2006yuo** [NervJS/taro#6863]
**问题描述**
用手机预览，当虚拟列表row组件层级嵌套多的时候滚动出现严重抖动

**复现步骤**
1. 复制官方demo
2. 修改Row组件，如下
```js
const Row = React.memo(({ index, style, data }) => {
  return (
    <View className={index % 2 ? "ListItemOdd" : "ListItemEven"} style={style}>
      <View
        style={{
          display: "flex"
        }}
      >
        <Image
          style={{
            width: "100px",
            height: "100px"
          }}
          src='http://lorempixel.com/100/100/'
        />
        <View>
          <View>
            <View>{index}</View>
          </View>
        </View>
      </View>
    </View>
  )
})
```
3. 打开小程序开发工具，手机扫码预览
4. 快速向下滑，然后慢慢向上滚动，出现明显抖动。当**层级嵌套多**的时候抖动更加明显

**系统信息**
  Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.7.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/mini-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/react: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/runtime: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/webpack-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      babel-preset-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      eslint-config-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      react: ^16.10.0 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.7.3

**补充信息**
v3.0.0-rc.3不会，升级到v3.0.0-rc.6后出现

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/acdb92a890fc391bc33115dd4bbdc715efc40262
应该和这个有关

**Comment by IseeUDenis** [comment]
找到解决办法了吗

**Comment by qiqijojo** [comment]
这个抖动的解决了吗，我目前用上下滚动还是抖动的厉害。。。

**Comment by qiqijojo** [comment]
麻烦提示下怎么修复这个抖动的问题@Chen-jj
