### ISSUE TITLE
Taro v3.0.0-rc.6云开发模版package.json插件依赖版本问题

### ISSUE THREAD

**Issue by xxj95719** [NervJS/taro#6864]
一、重现步骤：
1. yarn global add @tarojs/cli@next
2. taro init myMiniBlog
3.选取云开发模版
![image](https://user-images.githubusercontent.com/27256120/86232400-78091000-bbc6-11ea-932e-07bc27eab20d.png)
4.client/package.json依赖大部分都是rc.6版本，实际最新版本是2.2.10
![image](https://user-images.githubusercontent.com/27256120/86232487-98d16580-bbc6-11ea-8c54-0f9dd5847de8.png)
二、期望
更新模版依赖

**Comment by tinpont** [comment]
这里版本是跟随你的cli版本的。目前最新版应该是3.0.2，你先更新cli到3.0.2，重新新建项目这里就都会是3.0.2了。

**Comment by xxj95719** [comment]
> 这里版本是跟随你的cli版本的。目前最新版应该是3.0.2，你先更新cli到3.0.2，重新新建项目这里就都会是3.0.2了。

看了taro提交记录最新版本确实是3.0.2 ，只不过yarn global add @tarojs/cli@next安装的版本确实也是rc.6
![image](https://user-images.githubusercontent.com/27256120/86307084-72eca500-bc48-11ea-894b-b325969d6de4.png)

**Comment by tinpont** [comment]
yarn global upgrade @tarojs/cli --latest 试试





------------------ 原始邮件 ------------------
发件人: JsSoooooCool <notifications@github.com&gt;
发送时间: 2020年7月2日 09:44
收件人: NervJS/taro <taro@noreply.github.com&gt;
抄送: tinpont <510499887@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[NervJS/taro] Taro v3.0.0-rc.6云开发模版package.json插件依赖版本问题 (#6864)

**Comment by xxj95719** [comment]
> yarn global upgrade @tarojs/cli --latest 试试
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: JsSoooooCool <notifications@github.com&gt; 发送时间: 2020年7月2日 09:44 收件人: NervJS/taro <taro@noreply.github.com&gt; 抄送: tinpont <510499887@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[NervJS/taro] Taro v3.0.0-rc.6云开发模版package.json插件依赖版本问题 (#6864)
![image](https://user-images.githubusercontent.com/27256120/86307508-82b8b900-bc49-11ea-8f86-6f5319d51e80.png)

![image](https://user-images.githubusercontent.com/27256120/86307492-77fe2400-bc49-11ea-8e21-bec73323fab1.png)
 模版里的依赖都是3.0.2这个有问题。。。

**Comment by xxj95719** [comment]
> 这里版本是跟随你的cli版本的。目前最新版应该是3.0.2，你先更新cli到3.0.2，重新新建项目这里就都会是3.0.2了。

![image](https://user-images.githubusercontent.com/27256120/86307692-f6f35c80-bc49-11ea-863f-be616c54a800.png)
你们这边取得是version，但是对应的库版本并没有那么高

**Comment by honlyHuang** [comment]
已经修复
