### ISSUE TITLE
taro 3.0 react hook 无法获取url参数

### ISSUE THREAD

**Issue by 13678900367** [NervJS/taro#6870]
### 相关平台
H5

**浏览器版本: Chrome**
**使用框架: React**

### 复现步骤
useEffect(() => {
    console.log(getCurrentInstance());  //url 为空
    console.log(this);    //undefined
    console.log(this.$router);   //  报错
  }, []);

### 期望结果
希望能获取到url的参数

### 实际结果
undefined

### 环境信息
```
Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/mini-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/react: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/runtime: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/webpack-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      babel-preset-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      eslint-config-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      react: ^16.10.0 => 16.13.1 
```

---
### 补充信息
此类问题我已经看见过一些大佬们反馈，希望得以重视，taro 3.0  react hook  不知怎么获取路由的参数

**Comment by yuche** [comment]
使用自定义 Hooks `useReady`，请不要删除 Issue Helper 给你自动生成的标签。

**Comment by 13678900367** [comment]
> 使用自定义Hooks `useReady`，请不要删除Issue Helper给你自动生成的标签。
`useReady`   // undefined 
框架版本  Taro CLI 3.0.0-rc.6 

` import  { useReady } from "@tarojs/taro"`  获取不到 useReady

**Comment by luodanyalian** [comment]
> > 使用自定义Hooks `useReady`，请不要删除Issue Helper给你自动生成的标签。
> > `useReady`   // undefined
> > 框架版本  Taro CLI 3.0.0-rc.6
> 
> ` import { useReady } from "@tarojs/taro"` 获取不到 useReady

` import { useReady } from "react"`文档迁移指南有写
