### ISSUE TITLE
升级 3.0.2 h5 端引入 react-redux 报错

### ISSUE THREAD

**Issue by dpyzo0o** [NervJS/taro#6877]
### 相关平台
H5

### 复现仓库
[https://github.com/dpyzo0o/taro-toolkit/tree/taro-issue](https://github.com/dpyzo0o/taro-toolkit/tree/taro-issue)
**浏览器版本: Chrome Version 83.0.4103.116**
**使用框架: React**

### 复现步骤
升级 taro 依赖到 3.0.2,
npm run dev:h5

### 期望结果
正常运行

### 实际结果
报错, Module not found: Can't resolve 'react-dom' 

![1593658448918](https://user-images.githubusercontent.com/24768249/86311886-f52e9680-bc53-11ea-92ba-64b5676dabbf.jpg)

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.2 => 3.0.2
      @tarojs/components: ^3.0.2 => 3.0.2
      @tarojs/mini-runner: ^3.0.2 => 3.0.2
      @tarojs/react: ^3.0.2 => 3.0.2
      @tarojs/runtime: ^3.0.2 => 3.0.2
      @tarojs/taro: ^3.0.2 => 3.0.2
      @tarojs/webpack-runner: ^3.0.2 => 3.0.2
      babel-preset-taro: ^3.0.2 => 3.0.2
      eslint-config-taro: ^3.0.2 => 3.0.2
      react: ^16.13.1 => 16.13.1
```

**Comment by yuche** [comment]
你本地安装一个 react-dom 应该就行了，请问你打开填完 Issue 表单跳转到 GitHub 的时候没有自动带上 issue 标签吗

**Comment by dpyzo0o** [comment]
> 你本地安装一个 react-dom 应该就行了，请问你打开填完 Issue 表单跳转到 GitHub 的时候没有自动带上 issue 标签吗

标签我不太清楚, 跳过来之后我没有进行什么其他的操作。

**Comment by dpyzo0o** [comment]
@yuche 本地安装后可以了，谢谢
