### ISSUE TITLE
taro3.0 如何异步编程 

### ISSUE THREAD

**Issue by Smi1e96** [NervJS/taro#6886]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Smi1e96/Taro3.git](https://github.com/Smi1e96/Taro3.git)
**小程序基础库: 2.9.5**
**使用框架: React**

### 复现步骤
1. 使用[异步编程](https://taro-docs.jd.com/taro/docs/async-await/) 编译不通过出现下列问题

![image](https://user-images.githubusercontent.com/31199247/86335946-bca5b180-bc81-11ea-886c-37bab8f71850.png)

### 期望结果
可以使用async-await

### 实际结果
编译不能通过

### 环境信息
```
  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      react: ^16.10.0 => 16.13.1 

```

**Comment by Chen-jj** [comment]
@Smi1e96 不需要引这个了，根据 babel 配置来，babel.config.js 中 preset-taro 已经帮你设置好了。

https://github.com/Smi1e96/Taro3/blob/0dbabdec4f3c36a4873a6aa5a5effb4833f0b3b0/src/app.ts#L2

**Comment by Smi1e96** [comment]
@Chen-jj  我看文档还有这个功能 我还以为要像1 2版本配置 :smile: [升级next版本](https://taro-docs.jd.com/taro/docs/migration)那这个文档 要完善下

**Comment by Chen-jj** [comment]
2 也不用的，在 1 升 2 的升级指南有写

**Comment by Smi1e96** [comment]
@Chen-jj  2是需要[配置babel](https://taro-docs.jd.com/taro/docs/2.2.8/async-await) 不用引用了@tarojs/async-await :joy:

**Comment by LbhFront-end** [comment]
Can't resolve 'regenerator-runtime/runtime' in \node_modules\@tarojs\async-await' 这个是什么问题？

**Comment by huanlirui** [comment]
taro 3 怎么配置？babel ??
