### ISSUE TITLE
 module "npm/mobx/lib/mobx.js" is not defined 

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#689]
**问题描述**
引入 mobx 失败

**复现步骤**
[复现问题的步骤]
```js
import mobx from 'mobx/lib/mobx'
```

**期望行为**
正常引入 mobx

**报错信息**
![2018-09-25 12 12 06](https://user-images.githubusercontent.com/19544032/45992411-45aab480-c0bc-11e8-801b-d9dbab32533f.png)

**系统信息**

 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.3]
 - Node.js 版本 [e.g. v10.0.0]

**Comment by luckyadam** [comment]
暂时还没有支持 mobx

**Comment by jamieYou** [comment]
@luckyadam  这个是引入一个包出现的问题，跟支不支持 mobx 没有关系吧

**Comment by luckyadam** [comment]
已修复 345e6409657cf4ecc96c8baf311aac6ebaa6591d
