### ISSUE TITLE
多个自定义tab都含有swiper，切换tab到autoplay=false的swiper再切换回autoplay=true的话，autoplay失效

### ISSUE THREAD

**Issue by Yuiffy** [NervJS/taro#6892]
### 相关平台
H5

#### 代码仓库
[https://github.com/Yuiffy/taro-swiper-autoplay-issue/tree/master](https://github.com/Yuiffy/taro-swiper-autoplay-issue/tree/master)

#### 实际体验网址
https://www.yuiffy.com/taro-swiper-autoplay-issue

**浏览器版本: Chrome 83**
**使用框架: React**

### 复现步骤
自定义tab使用display: block / none来显示不同内容；
每个tab都含有swiper，其中ATab的swiper是autoplay=true, 另外一个BTab内的swiper是autoplay=false。
一开始在ATab下，能够正常autoplay，切换到BTab，再切回ATab，则ATab下的swiper也不再autoplay了，刷新页面才能恢复。

### 期望结果
不同tab下的swiper的autoplay不会互相影响

### 实际结果
切到autoplay=false的tab后切回来，原本的swiper也不再autoplay了

### 环境信息
```
  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.0.16 - /usr/local/bin/bash
    Binaries:
      Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v13.10.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: ^16.10.0 => 16.13.1 

```

---
### 补充信息
Taro2、Taro3都能复现

更新：后续又发现用此种display: block/none来切换的tab里，两边的swiper都是autoplay=true也会有问题，切多了也会停止自动播放

**Comment by ZakaryCode** [comment]
该问题在 2.x 中已经修复
