### ISSUE TITLE
项目公共样式app.css无法生效

### ISSUE THREAD

**Issue by yyISACoder** [NervJS/taro#6894]
### 相关平台
百度小程序

**小程序基础库: 3.190.15**
**使用框架: React**

### 复现步骤
项目生成后，app.css中的样式无法应用于各个页面

### 期望结果
app.css中的样式能应用于各个页面

### 实际结果
app.css中的样式无法应用于各个页面

### 环境信息
```
Taro CLI 2.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\SNQU\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
我这边定位到的原因是编译后的非组件页面的配置json文件中，自动添加了component":true这个配置。我去百度小程序的官方论坛中看到也有人遇到这个情况，百度回复的是删除这个配置即可，我这边尝试删除了，app.css的样式确实就生效了，所以造成的原因就是taro框架自动添加的这个配置项造成的，望官方大大能看到！望解决！！！！

**Comment by foolin** [comment]
我在QQ平台也没有生效

**Comment by yyISACoder** [comment]
> 我在QQ平台也没有生效

不会啊，我这边qq平台已经上线了

**Comment by foolin** [comment]
> > 我在QQ平台也没有生效
> 
> 不会啊，我这边qq平台已经上线了

昨晚找到原因了，找到了好久，QQ小程序最新版本开发工具的bug，回退到稳定版本就可以了。

**Comment by Chen-jj** [comment]
@yyISACoder 百度小程序使用 Component 构造页面是需要加 `usingComponent: true` 的，你加个 addGlobalClass 就可以了。

![image](https://user-images.githubusercontent.com/11807297/86456463-af0d2c00-bd54-11ea-9f7d-37d7b5da0942.png)
