### ISSUE TITLE
【Taro Next】如何获取方法组件的作用域

### ISSUE THREAD

**Issue by logix-o** [NervJS/taro#6898]
### 这个特性解决了什么问题？
原先Taro2.x中的useScope，在3.0后被删除了。是否有替代的方法，以在方法组件中获取作用域？

### 这个 API 长什么样？
useScope

**Comment by vdfor** [comment]
taro3不存在小程序的自定义组件了，也就不需要获取组件作用域了。

比如，在2.x这样写的：

```js
const scope = useScope();
const query = createSelectorQuery().in(scope);
```

3.0直接这样写即可：

```js
const query = createSelectorQuery();
```

**Comment by Chen-jj** [comment]
bug 或 feature request 以外的问题请到 [论坛](https://taro-club.jd.com/) 提问
