### ISSUE TITLE
开放 H5 的路由配置功能

### ISSUE THREAD

**Issue by thewei** [NervJS/taro#69]
现在：h5 demo 的 `hash` 模式及路由路径不合适时，无法自定义。
希望：能够配置 h5 端路由路径，能够开启 `history` 或者 `hash` 模式。

**Comment by yuche** [comment]
现在已经支持配置功能：
https://nervjs.github.io/taro/docs/config-detail.html#h5router

**Comment by thewei** [comment]
没法配置路由路径么？比如现在 pages/index/index ，期望能够自定义，
比如配置 'home/index' 为新的路由，即浏览器地址栏显示 home/index，代码内部仍可以使用 pages/index/index 跳转
原因是，我们有一些特定的路由不能跟随小程序的路由命名方式。

**Comment by JohannLai** [comment]
@yuche 自定义配置路由有计划支持吗？编译到h5端的时候
