### ISSUE TITLE
编译代码时出现异常

### ISSUE THREAD

**Issue by Manuel-XD** [NervJS/taro#690]
**问题描述**
[问题描述：在项目中一个组件通过import引入项目中另一个文件提供的方法，这条语句在编译的时候，会将引入的路径编译错误。

**复现步骤**

```js

编译时候会将  import { arrryChunk, strSubChar} from '../../help/utility.js'  编译成为
import { arrryChunk, strSubChar } from "../../help\%utility";
```

**期望行为**
后面的引入路径可以正常编译，不会出现\%这样的异常导致找不到对应文件就可以了。

**报错信息**

![image](https://user-images.githubusercontent.com/38916357/45998031-130cb600-c0d4-11e8-9cb5-6050db6beb95.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v1.0.0-beta.28]
 - Node.js 版本 [ v8.9.3]

**Comment by Littly** [comment]
后续版本会修复 暂时先通过去除引入路径末尾的‘.js’避开这个问题
`import { arrryChunk, strSubChar} from '../../help/utility'`
