### ISSUE TITLE
Taro3 Picker表现异常

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#6903]
### 相关平台
支付宝小程序

**小程序基础库: 1.20.5**
**使用框架: React**

### 复现步骤
<Picker
                  className={styles.cardPicker}
                  mode='selector'
                  range={selector}
                  rangeKey='text'
                  value={Number(degreeValue)}
                  onChange={this.handleSelectorChange}
                >
                  <View className={styles.cardDateSel}>
                    <View className={!education ? styles.cardDateTit : ''}>
                      {education || '请选择'}
                    </View>
                    <View>
                      <Image className={styles.pickImg} src={rightArrow} />
                    </View>
                  </View>
                </Picker>

### 期望结果
能够正常的进行选择使用

### 实际结果
该组件页面无展示， 编译后的微信小程序正常， 支付宝小程序异常，且在支付宝小程序编译后内该组件内无其他内容

### 环境信息
```
Taro CLI 1.3.39 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
children

**Comment by psaren** [comment]
Duplicate of #6804
