### ISSUE TITLE
升级了3.0   npm run dev:h5 出错

### ISSUE THREAD

**Issue by shichuyu** [NervJS/taro#6905]
### 相关平台
H5

### 复现仓库
[https://github.com/shichuyu/mytaro/tree/mytarojs](https://github.com/shichuyu/mytaro/tree/mytarojs)
**浏览器版本:  Google Chrome	81.0.4044.113 (正式版本) （64 位） (cohort: 81_Win_92)**
**使用框架: React**

### 复现步骤
PS E:\smallRoutine\Taro\mytaro> npm run dev:h5

> mytarojs@1.0.0 dev:h5 E:\smallRoutine\Taro\mytaro
> npm run build:h5 -- --watch

> mytarojs@1.0.0 build:h5 E:\smallRoutine\Taro\mytaro
> taro build --type h5 "--watch"

� Taro v3.0.0-rc.6

ℹ️  Listening at http://0.0.0.0:8888/

监听文件修改中...

�   Failed to compile.

multi (webpack)-dev-server/client?http://0.0.0.0:8888 (webpack)/hot/dev-server.js ./src/app.config
Module not found: Can't resolve 'E:\smallRoutine\Taro\mytaro\src\app.config' in 'E:\smallRoutine\Taro\mytaro'

### 期望结果
期望执行成功

### 实际结果
现在报找不到config

### 环境信息
```
� Taro v3.0.0-rc.6


  Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.11.4 - D:\software\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.2 - D:\software\nodejs\npm.CMD
```

**Comment by shichuyu** [comment]
![image](https://user-images.githubusercontent.com/19624048/86428660-e3b2c080-bd1f-11ea-91b7-420314c6a068.png)
 
npm run dev:weapp 等也是报编译失败

**Comment by luckyadam** [comment]
麻烦把 cli 和项目依赖版本保持一致
并且现在最新版本是 3.0.2

**Comment by shichuyu** [comment]
好的，感谢

**Comment by admiao** [comment]
升级到3.0 2版本能无缝升级吗？ 还不如退回taro-cli2
