### ISSUE TITLE
Taro3 分割 base.wxml

### ISSUE THREAD

**Issue by redblue9771** [NervJS/taro#6910]
### 这个特性解决了什么问题？
每页的 template 应该放在每页下面而不是全部放在 base.wxml，这样会导致主包非常大，分包很小。

### 这个 API 长什么样？
每页有自己的 template.wxml

**Comment by Chen-jj** [comment]
@redblue9771 base.wxml 里 template 用于递归构造动态 dom 树，不可拆分。它的体积现在也不会太大，如果你 dom 嵌套层级又不深可以配置少一点的层数（默认16层）。之后应该会推出 wxml 压缩插件，不过压缩比例不会太大。

**Comment by redblue9771** [comment]
> @redblue9771 base.wxml 里 template 用于递归构造动态 dom 树，不可拆分。它的体积现在也不会太大，如果你 dom 嵌套层级又不深可以配置少一点的层数（默认16层）。之后应该会推出 wxml 压缩插件，不过压缩比例不会太大。

对于项目复杂一点，就会很大啊~ 我的 557K 了加上 vendors.js 等业务继续复杂主包怎么都是超的~ 所以只能在 vendors 上动刀了？

**Comment by xujiandream** [comment]
< template name="tmpl_0_button" >
< button size="{{ i.size === undefined ? 'default' : i.size }}"
type="{{ i.type }}"
plain="{{ i.plain === undefined ? false : i.plain }}"
disabled="{{ i.disabled }}"
loading="{{ i.loading === undefined ? false : i.loading }}"
form-type="{{ i.formType }}"
open-type="{{ i.openType }}"
hover-class="{{ i.hoverClass === undefined ? 'button-hover' : i.hoverClass }}"
hover-stop-propagation="{{ i.hoverStopPropagation === undefined ? false : i.hoverStopPropagation }}"
hover-start-time="{{ i.hoverStartTime === undefined ? 20 : i.hoverStartTime }}"
hover-stay-time="{{ i.hoverStayTime === undefined ? 70 : i.hoverStayTime }}"
lang="{{ i.lang === undefined ? en : i.lang }}"
session-from="{{ i.sessionFrom }}"
send-message-title="{{ i.sendMessageTitle }}"
send-message-path="{{ i.sendMessagePath }}"
send-message-img="{{ i.sendMessageImg }}"
app-parameter="{{ i.appParameter }}"
show-message-card="{{ i.showMessageCard === undefined ? false : i.showMessageCard }}"
bindgetuserinfo="eh"
bindgetauthorize="eh"
bindcontact="eh"
bindgetphonenumber="eh"
binderror="eh"
bindopensetting="eh"
bindlaunchapp="eh"
scope="{{ i.scope }}"
name="{{ i.name }}"
style="{{ i.st }}"
class="{{ i.cl }}"
bindtap="eh"
id="{{ i.uid }}">
< block wx:for="{{i.cn}}" wx:key="id">
< template is="tmpl_1_container" data="{{i: item}}" />
</ block >
</ button >
</ template >

< template name="tmpl_1_button">
< button size="{{ i.size === undefined ? 'default' : i.size }}"
type="{{ i.type }}"
plain="{{ i.plain === undefined ? false : i.plain }}"
disabled="{{ i.disabled }}"
loading="{{ i.loading === undefined ? false : i.loading }}"
form-type="{{ i.formType }}"
open-type="{{ i.openType }}"
hover-class="{{ i.hoverClass === undefined ? 'button-hover' : i.hoverClass }}"
hover-stop-propagation="{{ i.hoverStopPropagation === undefined ? false : i.hoverStopPropagation }}"
hover-start-time="{{ i.hoverStartTime === undefined ? 20 : i.hoverStartTime }}"
hover-stay-time="{{ i.hoverStayTime === undefined ? 70 : i.hoverStayTime }}"
lang="{{ i.lang === undefined ? en : i.lang }}"
session-from="{{ i.sessionFrom }}"
send-message-title="{{ i.sendMessageTitle }}"
send-message-path="{{ i.sendMessagePath }}"
send-message-img="{{ i.sendMessageImg }}"
app-parameter="{{ i.appParameter }}"
show-message-card="{{ i.showMessageCard === undefined ? false : i.showMessageCard }}"
bindgetuserinfo="eh"
bindgetauthorize="eh"
bindcontact="eh"
bindgetphonenumber="eh"
binderror="eh"
bindopensetting="eh"
bindlaunchapp="eh"
scope="{{ i.scope }}"
name="{{ i.name }}"
style="{{ i.st }}"
class="{{ i.cl }}"
bindtap="eh"
id="{{ i.uid }}">
< block wx:for="{{i.cn}}" wx:key="id" >
< template is="tmpl_2_container" data="{{i: item}}" / >
</ block>
</ button>
</ template>

像 这样的button template 有15个，大量重复的模板代码, 可以优化吗

**Comment by ksbaozi** [comment]
为什么不能跟着分包走呢，我们现在也遇到这个问题，主包带着所有 wxml 太大了。

**Comment by Chen-jj** [comment]
因为微信小程序不支持模板递归引用，只能把所有用到的组件全部写出来（使用到的组件种类越多，每层列出的组件越多，base.wxml 越大），目前递归层数是 16 层。

目前最直接的解决办法是配置更小的递归层数。

1. 关于分包独自拥有自己的 base.wxml。可以实现，但是只有当分包使用的组件种类和主包非常不相同时，才有比较好的效果。
2. 每个组件有非常多的冗余属性和冗余事件绑定。这个可以提供配置项让用户手动指定，整个项目范围内这些组件各自需要的属性和事件，但是用户的开发体验会下降。
3. 每一层循环都有一些组件是多余的，但 DOM 树是动态的，使用静态模版去拼接出动态 DOM 树，只能列举出所有情况。关于这点的优化难度比较大。

如果大家有更好的想法，欢迎讨论～

**Comment by redblue9771** [comment]
> 因为微信小程序不支持模板递归引用，只能把所有用到的组件全部写出来（使用到的组件种类越多，每层列出的组件越多，base.wxml 越大），目前递归层数是 16 层。
> 
> 目前最直接的解决办法是配置更小的递归层数。
> 
> 1. 关于分包独自拥有自己的 base.wxml。可以实现，但是只有当分包使用的组件种类和主包非常不相同时，才有比较好的效果。
> 2. 每个组件有非常多的冗余属性和冗余事件绑定。这个可以提供配置项让用户手动指定，整个项目范围内这些组件各自需要的属性和事件，但是用户的开发体验会下降。
> 3. 每一层循环都有一些组件是多余的，但 DOM 树是动态的，使用静态模版去拼接出动态 DOM 树，只能列举出所有情况。关于这点的优化难度比较大。
> 
> 如果大家有更好的想法，欢迎讨论～

可以放到微信的分包里，使用微信分包预加载来减小主包的大小。现在已经准备使用这种方法来迁移npm包多导致主包大的情况了

**Comment by limingwei** [comment]
对于这个情况
手动或自动的，做更多的编译时？
最终出来一个部分编译时+部分运行时的混合的包？

**Comment by limingwei** [comment]
或者 通过 多态组件 把事情交出去？ 行不行

**Comment by xiaoyuze88** [comment]
我们项目打出来，common.js 1.6M，base.wxml 300k，vendors 1.2M，其他杂七杂八加起来主包3M多，所以以后只能用production模式开发？

**Comment by moonkop** [comment]
能否手动去掉一些用不到的标签呢 比如video就很长 如果把16层内部所有用不到的标签都去掉是不是包体积就可以缩小很多?

**Comment by Chen-jj** [comment]
RFC 的方案里有写到，可以去看看，忘记链接过来了。taro-rfc 仓库，pull request

**Comment by melochale** [comment]
我的production 模式，common.js 700KB, base.wxml 560KB,加起来一共2.3MB了，怎么办，刚花了几天升级上来，之前1.x版本1.5MB，这个根本就用了了
