### ISSUE TITLE
taro3.0.2 vue2 h5环境 jsx component 无法从 @tarojs/components 引入 组件

### ISSUE THREAD

**Issue by psaren** [NervJS/taro#6912]
### 相关平台
H5

### 复现仓库
[https://github.com/psaren/taro-issue-repo  ](https://github.com/psaren/taro-issue-repo  )
**浏览器版本: Chrome 版本 83.0.4103.116（正式版本） （64 位）  **
**使用框架: React**

### 复现步骤
git clone https://github.com/psaren/taro-issue-repo

cd taro-issue-repo  
npm run dev:h5

### 期望结果
微信小程序是正常无报错的
像微信小程序一样正常工作

### 实际结果
出现下面报错信息，组件无法正常工作  
./src/components/tag.jsx 11:13-17  
" '@tarojs/components' does not contain an export named 'View'. 

### 环境信息
```
taro info
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - D:\program\nodejs\node.EXE
      npm: 6.14.5 - D:\program\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@psaren Vue 中可以直接书写内置组件，不需要 import。因为我们在 `vue-template-compiler` 中已经分析到开发者使用到的组件。

```js
<template>
  <view
    class="index"
  >
    <view
      @tap="handleClick('tap')"
      @click="handleClick('click')"
    >
      <text>{{ msg }}</text>
    </view>
    <Tag />
  </view>
</template>

<script>
export default {
  data () {
    return {
      msg: 'Hello world'
    }
  },
  methods: {
    handleClick(eventName) {
      console.log(eventName)
    }
  }
}
</script>
```

**Comment by psaren** [comment]
@Chen-jj 感谢答复！

但我感觉问题没解决啊

我的组件是 jsx 写的，在小程序正常，到了H5却报了上述错误

难道要把所有组件用 vue template 重写吗 😨

是否有在 H5 也支持 JSX 的可能性呢？

如果不考虑支持，感觉应该在文档补充一下说明，避免其它开发者步我的后尘（坑）

**Comment by visnix** [comment]
https://www.jianshu.com/p/a5d64f7e1bb5

请查看解决方法

**Comment by visnix** [comment]
@psaren 
不知道你后续怎么解决的，我在这里发现了解决方案
https://b2nil.github.io/taro-ui-vue3/docs/questions.html#h5-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E7%BC%96%E8%AF%91%E6%8A%A5%E9%94%99%EF%BC%9F

**Comment by psaren** [comment]
> @psaren
> 不知道你后续怎么解决的，我在这里发现了解决方案
> https://b2nil.github.io/taro-ui-vue3/docs/questions.html#h5-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E7%BC%96%E8%AF%91%E6%8A%A5%E9%94%99%EF%BC%9F

用了template
😭
