### ISSUE TITLE
Taro3.ScrollView 

### ISSUE THREAD

**Issue by aidisheng** [NervJS/taro#6913]

**Comment by aidisheng** [comment]
问题描述

Taro3.0.0 ScrollView 百度小程序onScrollToLower触底翻页自动跳回到顶部

期望行为

能和微信小程序保持一致。

**Comment by aidisheng** [comment]
#

**Comment by znchen1989** [comment]
@aidisheng Taro3.0.0 ScrollView 百度小程序onScrollToLower触底翻页自动跳回到顶部，这个问题有解决吗？
