### ISSUE TITLE
Taro3.0.0 ScrollView 百度小程序onScrollToLower触底翻页自动跳回到顶部

### ISSUE THREAD

**Issue by aidisheng** [NervJS/taro#6914]
### 相关平台
百度小程序

**小程序基础库: 3.200.106**
**使用框架: React**

### 复现步骤
onScrollToLower={() => {
              pageReachBottom(hasMore, setPageNum)
 }}
加载到更多数据之后，自动跳回到最顶部

### 期望结果
加载更多数据之后，保持位置不变。

### 实际结果
自动跳回到最顶部

### 环境信息
```
Taro v3.0.0


  Taro CLI 3.0.0 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.16.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Think\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
能否提供个完整点的 demo 看下

**Comment by Chen-jj** [comment]
@aidisheng 和 #7293 一样，Taro 3 每次 setData 百度小程序整个页面就会刷新。非常遗憾，只能等待百度方面修复，目前只能先用 Taro 1/2 开发百度小程序。

后续在#7293 下继续讨论吧。
