### ISSUE TITLE
Taro3.0.2 A页面 提供methodA函数组件 给 B组件使用 B组件无法控制 methodA组件 flex水平方向排列

### ISSUE THREAD

**Issue by aidisheng** [NervJS/taro#6917]
### 相关平台
百度小程序

**小程序基础库: 3.190.255**
**使用框架: React**

### 复现步骤
1、ComponentB
import React from 'react'
import { View } from '@tarojs/components'

import './ComponentB.scss'

export function ComponentB({tabView}) {

  return (
    <View>
      <View>from page A </View>
      <View className='flex-view'>
        {tabView()}
      </View>
      <View>-----------self </View>
      <View className='flex-view'>
        <View>self4</View>
        <View>self5</View>
        <View>self6</View>
      </View>
    </View>
  )
}

2、ComponentB.scss
.flex-view {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

3、PageA
import React from 'react'
import { View, Block } from '@tarojs/components'
import {ComponentB} from './ComponentB'

const PageA = () => {
  const tabView = () => (
    // 解决办法：把flex-view放到这里
    // <View className='flex-view'>
    <Block>
      <View>pagea1</View>
      <View>pagea2</View>
      <View>pagea3</View>
    </Block>
  )

  return (
    <View className="index">
      <ComponentB
        tabView={tabView}
      />
    </View>
  )
}

export default PageA

### 期望结果
PageA中 tabView函数组件的3个View也能水平排列
微信小程序是正常的。

### 实际结果
PageA中 tabView函数组件的3个View仍然是垂直排列，控制不了。

### 环境信息
```
Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.16.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Think\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
自己的临时解决方法：把<View className='flex-view'> 从ComponentB中，移到PageA的tabView函数组件中。

**Comment by aidisheng** [comment]
`
1-ComponentB.tsx
import React from 'react'
import { View } from '@tarojs/components'

import './ComponentB.scss'

export function ComponentB({tabView}) {

  return (
    <View>
      <View>from page A </View>
      <View className='flex-view'>
        {tabView()}
      </View>
      <View>-----------self </View>
      <View className='flex-view'>
        <View>self4</View>
        <View>self5</View>
        <View>self6</View>
      </View>
    </View>
  )
}

2-ComponentB.scss
.flex-view, .flex-view2 {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}

3-PageA.tsx
import React from 'react'
import { View, Block } from '@tarojs/components'
import {ComponentB} from './ComponentB'

const PageA = () => {
  const tabView = () => (
    // 解决办法：把flex-view放到这里
    // <View className='flex-view'>
    <View>
      <View>pagea1</View>
      <View>pagea2</View>
      <View>pagea3</View>
    </View>
  )

  return (
    <View className="index">
      <ComponentB
        tabView={tabView}
      />
    </View>
  )
}

export default PageA

`

**Comment by Chen-jj** [comment]
@aidisheng 请提供可运行可复现的代码，并整理好你的代码格式

**Comment by Chen-jj** [comment]
没有清晰能运行的代码，无法定位
