### ISSUE TITLE
taro 3.0引入taro-ui 打包后的base.wxml体积太大了

### ISSUE THREAD

**Issue by xujiandream** [NervJS/taro#6921]
### 相关平台
微信小程序

**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
import { **组件 } from 'taro-ui'  后build:weapp

### 期望结果
taro-ui模板按需打包到base.wxml文件

### 实际结果
使用taro-ui后打包base.wxml体积相差500多kb

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.0-rc.6 => 3.0.2 
      @tarojs/components: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/mini-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/react: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/runtime: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      @tarojs/webpack-runner: 3.0.0-rc.6 => 3.0.0-rc.6 
      babel-preset-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      eslint-config-taro: 3.0.0-rc.6 => 3.0.0-rc.6 
      react: ^16.10.0 => 16.13.1 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by xujiandream** [comment]
![image](https://user-images.githubusercontent.com/23227529/86548082-c07d5080-bf6d-11ea-8b29-ae5c7dafe24f.png)
像 这样的button template 有15个，截取了tmpl_0_button和tmpl_1_button比较，差别只有标红的名称，这都是重复的

**Comment by xujiandream** [comment]
已发现 使用的taro-ui 3.0.0-alpha.3包main文件指向了dist下的commonjs模块，建议改用lib下的esmodule模块，以便tree-shaking，但base.wxml是否可以多一些复用，其次，是否可以支持将base.wxml打到分包里

**Comment by Chen-jj** [comment]
@xujiandream taro-ui 由社区维护，第一点可以给他们提 issue。第二点目前可以配置调整循环层数来优化，更深层的优化在 #6910 讨论吧，这个我们还要再仔细想想。
