### ISSUE TITLE
taro 3.0版本 函数编程 redux报warning

### ISSUE THREAD

**Issue by lang-strive** [NervJS/taro#6922]
### 相关平台
微信小程序

### 复现仓库
[http://baidu.com](http://baidu.com)
**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
taro 3.0版本 函数编程 redux报warning
h5,weapp小程序,apply小程序都报warning

### 期望结果
不报错

### 实际结果
不报warning

### 环境信息
```
👽 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/node/bin/node
      Yarn: 1.22.4 - /usr/local/node/bin/yarn
      npm: 6.13.4 - /usr/local/node/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2
      @tarojs/mini-runner: 3.0.2 => 3.0.2
      @tarojs/react: 3.0.2 => 3.0.2
      @tarojs/runtime: 3.0.2 => 3.0.2
      @tarojs/taro: 3.0.2 => 3.0.2
      @tarojs/webpack-runner: 3.0.2 => 3.0.2
      babel-preset-taro: 3.0.2 => 3.0.2
      eslint-config-taro: 3.0.2 => 3.0.2
      react: ^16.10.0 => 16.13.1
    npmGlobalPackages:
      typescript: 3.8.3

```

---
### 补充信息
1

**Comment by lang-strive** [comment]
<img width="533" alt="截屏2020-07-03上午11 10 14" src="https://user-images.githubusercontent.com/31495553/86547268-ff5dd700-bf6a-11ea-9733-b903d2f7917e.png">
<img width="533" alt="截屏2020-07-03上午11 10 14" src="https://user-images.githubusercontent.com/31495553/86547269-008f0400-bf6b-11ea-85af-7b822cac88b9.png">

**Comment by Chen-jj** [comment]
@lang-strive 请正确添加可复现仓库，不合规的 issue 会被关闭。
