### ISSUE TITLE
import {  VirtualList } from '@tarojs/components'  虚拟列表没有导出

### ISSUE THREAD

**Issue by chenjiajing23** [NervJS/taro#6925]
### 相关平台
微信小程序

### 复现仓库
[https://taro-docs.jd.com/taro/docs/guide/#%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96](https://taro-docs.jd.com/taro/docs/guide/#%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96)

![image](https://user-images.githubusercontent.com/41351722/86565708-f258dc00-bf9a-11ea-82c9-7d1c380f205f.png)
![image](https://user-images.githubusercontent.com/41351722/86565733-000e6180-bf9b-11ea-95d4-4d5b1fddbc52.png)
![image](https://user-images.githubusercontent.com/41351722/86565775-11576e00-bf9b-11ea-89dd-46fd99cc6175.png)

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
import { View, Text, VirtualList } from '@tarojs/components'

报红  控制台也报红

### 期望结果
import { View, Text, VirtualList } from '@tarojs/components'

报红  控制台也报红

### 实际结果
import { View, Text, VirtualList } from '@tarojs/components'

正常导出

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: ^3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: ^16.13.1 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.9.5
```

---
### 补充信息
是不是官方把虚拟列表删除了啊，如果是，请更新文档好吗？谢谢

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/86578073-ceeb5c80-bfad-11ea-8215-2247f5271482.png)

文档是让你 `import VirtualList from '@tarojs/components/virtual-list'` 这样引入的，你从 `@tarojs/components` 引入当然没有了。

**Comment by chenjiajing23** [comment]
![image](https://user-images.githubusercontent.com/41351722/86579969-a0bb4c00-bfb0-11ea-8cf9-373e0a7d6601.png)
缺少ts声明文件

**Comment by chenjiajing23** [comment]
@Garfield550

**Comment by chenjiajing23** [comment]
![image](https://user-images.githubusercontent.com/41351722/86580989-08be6200-bfb2-11ea-81dc-aa15f8f9e6a8.png)
tab
它本身好像就没有打包出ts文件，希望支持一下

**Comment by chenjiajing23** [comment]
@Garfield550

**Comment by Garfield550** [comment]
缺少 Typings 另开 Issue 吧
