### ISSUE TITLE
3.0.2编译的代码无法在今日头条app里打开

### ISSUE THREAD

**Issue by xiangzi-jiangxin** [NervJS/taro#6929]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/xiangzi-jiangxin/test-default-taro](https://github.com/xiangzi-jiangxin/test-default-taro)
**小程序基础库: 1.67.0.1**
**使用框架: React**

### 复现步骤
1、3.0.2新建默认项目
2、编译字节跳动平台（创建issue时，无法选择字节平台，默认选了微信平台）
3、使用手机上的今日头条app，扫码打开小程序
4、页面空白

### 期望结果
页面可正常显示

### 实际结果
页面空白

### 环境信息
```
👽 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.1.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: ^16.10.0 => 16.13.1 

```

---
### 补充信息
自测情况说明
iPhone x（iOS14，iOS13.3.1），红米Pro（Android6.0）上，今日头条无法正常显示，今日头条lite和抖音可正常显示。
iPhone 8 今日头条可正常显示。

**Comment by talise** [comment]
你把抖音也升级到最新版的话，估计都变白了

**Comment by Chen-jj** [comment]
头条 1.70+ 的基础库， `App` 构造器好像只支持对象字面量，而Taro 中传入的是一个类实例。我们再和头条方面沟通一下。
