### ISSUE TITLE
请问如何，封装类似wx.showToast的方法出来呢？

### ISSUE THREAD

**Issue by cilla123** [NervJS/taro#693]
就是想直接在父组件调用自定义的弹窗，因为没有document，所以不能和之前的react一样的做法，所以有办法可以做到直接类似wx.showToast()的方法调用显示出来弹窗，而不用在父组件render的方法里面写自定义的组件呢？

**Comment by luckyadam** [comment]
目前我们也没有想到合适的办法

**Comment by cilla123** [comment]
@luckyadam 能使用portal实现吗？

**Comment by luckyadam** [comment]
小程序里操作不了 dom ，还是不行啊
