### ISSUE TITLE
Taro.chooseImage  H5  表现异常

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#6932]
### 相关平台
H5

**浏览器版本: Chrome 版本 83.0.4103.97**
**使用框架: React**

### 复现步骤
图片上传  选择完图片，上传发现originalFileObj该对象不存在

### 期望结果
正常上传

### 实际结果
originalFileObj 原始对象没了

### 环境信息
```
Taro CLI 1.3.39 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
文档写的还有，实际使用就没了

**Comment by Junzibuzhengyibuqi** [comment]
![image](https://user-images.githubusercontent.com/50317102/86985748-8954ac80-c1c4-11ea-9336-d54e40329000.png)
输出少了 item

**Comment by cpocar** [comment]
同问，求官方尽快恢复

**Comment by ZakaryCode** [comment]
fixed in #fe346efc9b06926371ab7065f5e4e07839b25293
