### ISSUE TITLE
import VirtualList from '@tarojs/components/virtual-list'  缺少typings

### ISSUE THREAD

**Issue by chenjiajing23** [NervJS/taro#6936]
### 相关平台
微信小程序

### 复现仓库
[https://taro-docs.jd.com/taro/docs/guide#%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96](https://taro-docs.jd.com/taro/docs/guide#%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96)
![image](https://user-images.githubusercontent.com/41351722/86596927-98bdd500-bfcd-11ea-8aa5-c3f686abe739.png)

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
import VirtualList from '@tarojs/components/virtual-list' 
缺少typings

### 期望结果
import VirtualList from '@tarojs/components/virtual-list' 
有ts类型提示

### 实际结果
import VirtualList from '@tarojs/components/virtual-list' 
无ts类型提示

### 环境信息
```
 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: ^3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: ^16.13.1 => 16.13.1 
    npmGlobalPackages:
```

**Comment by ZakaryCode** [comment]
已经添加 virtual-list 在 react 中的类型，后续在补充 vue 相关的类型

> 也欢迎有想法的各位提交 PR，贡献一波～～
