### ISSUE TITLE
编译成小程序，className未转成class

### ISSUE THREAD

**Issue by Mr-ou** [NervJS/taro#694]
1.在react中写的是className,编译到小程序中依然是className
2.把className改成class，虽然有eslint提示，编译到小程序中变为class，样式起作用
**期望**
className编译到小程序中变为class

**Comment by yuche** [comment]
`className` 一定会编译成 `className`，这样你从 `this.props.className` 才能访问到正确的参数。如果你想直接写 class 就写 class。

微信小程序给 `id`, `class` 等 props 都单独开小灶是一种很不合理的设计，假设你在 Taro 中这么写，在其他端就没办法跑了。
