### ISSUE TITLE
希望提供支持onShareTimeline的hooks

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#6945]
### 这个特性解决了什么问题？
解决微信小程序配置分享至朋友圈的配置问题，具体参见https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onShareTimeline

### 这个 API 长什么样？
useShareTimeline， 类似useAppShareMessage

**Comment by cpocar** [comment]
希望再3.0中提供支持

**Comment by CynthiaNC** [comment]
急需！！

**Comment by boxcc** [comment]
2.0 能支持就最好了~

**Comment by without-yy** [comment]
急需！！

急需！！

急需！！

急需！！

**Comment by zhaoxu-me** [comment]
希望能尽快支持，感谢

**Comment by hhaoqin** [comment]
在编译后的dist文件夹，打开文件 vendors.js 搜索 “onShareAppMessage” 第一个数组，加入 “onShareTimeline” 即可兼容

**Comment by ljyljy0211** [comment]
或者自己临时直接改@tarojs包里面的微信小程序相关目录，搜索 “onShareAppMessage”，然后对应的地方加上  onShareTimeline

**Comment by ljyljy0211** [comment]
node_modules/@tarojs/taro-weapp/dist/index.esm.js
node_modules/@tarojs/taro-weapp/dist/index.esm.js.map
node_modules/@tarojs/taro-weapp/dist/index.js
node_modules/@tarojs/taro-weapp/dist/index.js.map
node_modules/@tarojs/taro-weapp/dist/taro-weapp.js
node_modules/@tarojs/taro-weapp/dist/taro-weapp.js.map
node_modules/@tarojs/taro-weapp/src/create-component.js

上面七个文件中，搜索 “onShareAppMessage”，然后对应的地方加上 onShareTimeline

**Comment by ljyljy0211** [comment]
![image](https://user-images.githubusercontent.com/1272007/86999358-fb3cee00-c1e4-11ea-8260-eaac40739a73.png)
![image](https://user-images.githubusercontent.com/1272007/86999414-1dcf0700-c1e5-11ea-94dd-dabd7610f039.png)

**Comment by fjc0k** [comment]
@Chen-jj   Taro 可以导出一个通用的 usePageEvent，避免不同端有些没有支持的 hook 无法使用。

**Comment by Chen-jj** [comment]
@fjc0k 生命周期的支持需要在小程序的 Page 构造器中定义好相应的生命周期，这一步无法实现动态添加。

**Comment by bafhvxk70** [comment]
onShareTimeline的hooks预计支持2.x的版本吗，业务在2.x相对稳定，升级到3.x会有较大的成本

**Comment by Chen-jj** [comment]
@bafhvxk70 会的，下个 patch 版本支持

**Comment by yeojongki** [comment]
@Chen-jj 我提了个 2.x 版本的 PR https://github.com/NervJS/taro/pull/6981

**Comment by Chen-jj** [comment]
@yeojongki 修一下 ci 吧

**Comment by yeojongki** [comment]
@Chen-jj 貌似是你们升级 lerna 的问题，我合并之后还是不行

**Comment by zhouzyc** [comment]
太难了 1.0 的 hooks写法怎么使用onShareTimeline
