### ISSUE TITLE
Taro 3.0.2 router.mode= 'multi'不能打出多个对应的页面

### ISSUE THREAD

**Issue by moonreplace** [NervJS/taro#6956]
### 相关平台
H5

**浏览器版本: Chrome 83**
**使用框架: React**

### 复现步骤
多个页面， 然后把router. mode设为'multi', 不能打出多个页面

### 期望结果
能够打出多个html, 及相应的js

### 实际结果
只有一个app.html

### 环境信息
```
 Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.2 => 3.0.2
      @tarojs/components: ^3.0.2 => 3.0.2
      @tarojs/mini-runner: ^3.0.2 => 3.0.2
      @tarojs/react: ^3.0.2 => 3.0.2
      @tarojs/router: ^3.0.2 => 3.0.2
      @tarojs/runtime: ^3.0.2 => 3.0.2
      @tarojs/taro: ^3.0.2 => 3.0.2
      @tarojs/webpack-runner: ^3.0.2 => 3.0.2
      babel-plugin-transform-taroapi: ^3.0.2 => 3.0.2
      babel-preset-taro: ^3.0.2 => 3.0.2
      eslint-config-taro: ^3.0.2 => 3.0.2
      eslint-plugin-taro: ^3.0.2 => 3.0.2
      nerv-devtools: ^1.5.6 => 1.5.6
      nervjs: ^1.5.6 => 1.5.6
      react: ^16.13.1 => 16.13.1
```

---
### 补充信息
@tarojs/webpack-runner中的config 
lodash_1.merge(plugin, lodash_1.mapValues(entry, (filePath, entryName) => {
            return chain_1.getHtmlWebpackPlugin([{
                    filename: `${entryName}.html`,
                    template: path.join(appPath, sourceRoot, 'index.html'),
                    chunks: [entryName]
                }]);
        }));

MainPlugin没运行完之前就执行了上面的操作，并没有取到相应的entries信息

**Comment by Chen-jj** [comment]
@moonreplace 这是一个还没完全实现的特性，请不要使用。

**Comment by moonreplace** [comment]
> @moonreplace 这是一个还没完全实现的特性，请不要使用。

@Chen-jj 我们有支持的时间表吗？

**Comment by Chen-jj** [comment]
@moonreplace 这块搞起来比较麻烦，而且在我们的计划中优先度不高，所以短期内是支持不了了。

**Comment by lext-7** [comment]
这个需求再投票里投票数也比较高，有什么计划吗？

**Comment by ZakaryCode** [comment]
该特性已经完成，会随 3.5 版本释出，参考[文档](https://nervjs.github.io/taro-docs/docs/next/config-detail#h5routermode)

**Comment by SyMind** [comment]
@moonreplace 你好，请问多页面打包是为了解决什么样的需求？
