### ISSUE TITLE
小程序自定义组件不能循环引用

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#696]
**问题描述**
使用小程序的自定义组件功能，组件内需要递归渲染数据，所以得引用自身

**复现步骤**
[复现问题的步骤]
```json
// rich-render.json
{
  "component": true,
  "usingComponents": {
    "rich-render": "./rich-render"
  }
}
```

**期望行为**
正常运行

**报错信息**
控制台没有报错，ide 一直处于刷新状态，应该是 taro 不断在编译文件造成的，关掉 taro 进程后，ide 就正常了

**系统信息**

 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.3]
 - Node.js 版本 [e.g. v10.0.0]

**Comment by luckyadam** [comment]
看一下引用自身的写法~

**Comment by jamieYou** [comment]
> 看一下引用自身的写法~

我是把原有项目的组件拷贝过来的，原有项目是没有用框架的

**Comment by luckyadam** [comment]
好，我看看能不能处理

**Comment by Chen-jj** [comment]
@jamieYou 拖了一段时间才解决不好意思。
最新版本可以解决编译爆栈的问题，可以更新试试。小程序组件循环依赖爆栈的问题需要你业务逻辑解决。
