### ISSUE TITLE
TARO_BUILD_TYPE=ui taro build --ui 过程中 taro-cli 内相对路径依赖找不到

### ISSUE THREAD

**Issue by yacheng** [NervJS/taro#6964]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/NervJS/taro/blob/next/packages/taro-cli/src/presets/platforms/ui.ts#L21](https://github.com/NervJS/taro/blob/next/packages/taro-cli/src/presets/platforms/ui.ts#L21)
**小程序基础库: 1.12.15**
**使用框架: React**

### 复现步骤
https://github.com/NervJS/taro/blob/next/packages/taro-cli/src/presets/platforms/ui.ts 中很多相对路径引用已经失效
例如：
require('../../h5');
require('../../ui/quickapp');
require('../../rn_bak');

### 期望结果
修复路径问题引起的构建异常

### 实际结果
无法正常 build

### 环境信息
```
Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2
      @tarojs/mini-runner: 3.0.2 => 3.0.2
      @tarojs/react: 3.0.2 => 3.0.2
      @tarojs/runtime: 3.0.2 => 3.0.2
      @tarojs/taro: 3.0.2 => 3.0.2
      @tarojs/webpack-runner: 3.0.2 => 3.0.2
      babel-preset-taro: 3.0.2 => 3.0.2
      eslint-config-taro: 3.0.2 => 3.0.2
      react: ^16.10.0 => 16.13.1
```

**Comment by lentoo** [comment]
这个修复了吗？？

**Comment by Chen-jj** [comment]
Taro 3 创建 UI 库不再需要 `build --ui` 命令了，这是 Taro 3 创建 UI 库的示例项目：https://github.com/NervJS/taro-uilib-react
