### ISSUE TITLE
自定义组件只能在 page 自身的 AXML 文件和组件自身的 AXML 文件中使用，不能通过 import 或 include 使用。

### ISSUE THREAD

**Issue by GakkiiSmile** [NervJS/taro#6975]
### 相关平台
支付宝小程序

**小程序基础库: 无**
**使用框架: React**

### 复现步骤
无法使用自定义组件。被引用的组件出现在base.axml的template中，而支付宝小程序不支持通过 import 或 include 使用的。

https://miniapp.open.taobao.com/docV3.htm?docId=117191&docType=1&source=search

### 期望结果
支付宝小程序下自定义axml不通过import使用

### 实际结果
支付宝小程序所有自定义组件都在base.axml下

### 环境信息
```
  Taro CLI 3.0.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.0 => 3.0.0 
      @tarojs/components: 3.0.0 => 3.0.0 
      @tarojs/mini-runner: 3.0.0 => 3.0.0 
      @tarojs/react: 3.0.0 => 3.0.0 
      @tarojs/runtime: 3.0.0 => 3.0.0 
      @tarojs/taro: 3.0.0 => 3.0.0 
      @tarojs/webpack-runner: 3.0.0 => 3.0.0 
      babel-preset-taro: 3.0.0 => 3.0.0 
      eslint-config-taro: 3.0.0 => 3.0.0 
      react: ^16.10.0 => 16.13.1 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by Chen-jj** [comment]
给个例子看看吧。

**Comment by GakkiiSmile** [comment]
> 给个例子看看吧。

https://github.com/GakkiiSmile/taro-alipay-bug-test

![image](https://user-images.githubusercontent.com/18532706/86989112-4dbde080-c1cc-11ea-99ef-bde128a931fb.png)

**Comment by GakkiiSmile** [comment]
> 给个例子看看吧。

2.0的版本可以直接在jsx使用原生标签，但是3.0版本无法直接使用原生标签，3.0版本有方法直接使用原生标签吗？

**Comment by Chen-jj** [comment]
暂时没有办法，支付宝的 template 不能引用自定义组件

**Comment by Chen-jj** [comment]
duplicate of #5778
