### ISSUE TITLE
小程序上报warning：Now you can provide attr "wx:key" for a "wx:for" to improve performance.

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#698]
**问题描述**

使用taro生成的小程序代码中，wx:for没有按照官方推荐的补上wx:key，导致开发工具上频频报warning
![image](https://user-images.githubusercontent.com/13899502/46061352-fdad8f80-c198-11e8-9e2d-814519dcde07.png)

**期望行为**

在生成wxml代码时能补充wx:key

**补充信息**

这个warning不会影响业务，但是按照微信官方说明，是可能影响性能的。建议taro完善这处。

**Comment by tourze** [comment]
谢谢回复，的确可以解决

**Comment by gclsoft** [comment]
@luckyadam 怎么补上key ? 总不能每次生成后都去wxml补?

**Comment by gclsoft** [comment]
@luckyadam 怎么补上key ? 总不能每次生成后都去wxml补?

**Comment by gclsoft** [comment]
@tourze 怎么解决的?

**Comment by tourze** [comment]
> @tourze 怎么解决的?

在react中使用key啊
