### ISSUE TITLE
多个request 使用不同的interceptor

### ISSUE THREAD

**Issue by le0l1** [NervJS/taro#6982]
### 这个特性解决了什么问题？
不同的请求可能需要使用 不同的interceptor

部分请求可能不走interceptor

目前解决方式好像只能通过传参来做选择

### 这个 API 长什么样？
```js
const instance = new Request();
request.use(someInterceptor);
```
类似于axios之类的

**Comment by ZakaryCode** [comment]
可以通过 interceptorify 配置，参考[文档](https://nervjs.github.io/taro-docs/docs/next/apis/taro.extend/interceptorify)
