### ISSUE TITLE
在3.x最新版本中，定义了几个class类，然后在页面中引用调用内部的方法就报一个exports的错误，求解。

### ISSUE THREAD

**Issue by ql007** [NervJS/taro#6985]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/ql007/Taro-Project1.git](https://github.com/ql007/Taro-Project1.git)
**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
安装下依赖，直接编译成微信小程序，看微信小程序开发者工具中的调试器的报错信息就可以。

### 期望结果
调用某个定义好的方法，很正常范围的一个操作。

### 实际结果
在编译之后的报错看的我一脸懵逼，也没可借鉴的例子。

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD   
```

---
### 补充信息
我定义个几个类的方法，然后在具体某个需要用到的页面调用这个方法。然后编译成小程序之后就报关于exports的问题。

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/87762619-024ba800-c846-11ea-9cc6-9c4b0fc1b89d.png)

不要混用 import export 和 cmd
