### ISSUE TITLE
请问 Taro 3 打算什么时候支持原生 APP？

### ISSUE THREAD

**Issue by 1014156094** [NervJS/taro#6986]
### 这个特性解决了什么问题？
公司有个新产品打算使用混合开发，需要使用 Vue，我打算使用 Taro 3 的，但是 Taro 3 不支持原生 APP，请问 Taro 3 打算什么时候支持原生 APP？如果是一个月左右，我还是会选择 Taro，不然我只能选择 uni-app 了

### 这个 API 长什么样？
Taro 3 支持原生 APP

**Comment by conkyliu** [comment]
插个眼,react开发也在线等RN出来,楼主用vue可以试试备受追捧uni-app试一试.

**Comment by 1014156094** [comment]
> 插个眼,react开发也在线等RN出来,楼主用vue可以试试备受追捧uni-app试一试.

嗯嗯~

**Comment by Chen-jj** [comment]
一个月内还推出不了，估计要到 3.1 甚至 3.2 才能支持，遗憾😭

**Comment by pecopeco** [comment]
可以考虑 eeui

**Comment by 1014156094** [comment]
> 可以考虑下eeui，rn最大的不可替代性是他的生态，看taro3未来能支持到什么程度

eeui 不支持小程序

**Comment by pecopeco** [comment]
> > 可以考虑下eeui，rn最大的不可替代性是他的生态，看taro3未来能支持到什么程度
> 
> eeui 不支持小程序

跨app和小程序两端基本没得选，但uni不适合做长远打算

**Comment by 1014156094** [comment]
> > > 可以考虑下eeui，rn最大的不可替代性是他的生态，看taro3未来能支持到什么程度
> > 
> > 
> > eeui 不支持小程序
> 
> 跨app和小程序两端基本没得选，但uni不适合做长远打算

uni-app 跨小程序和 app

**Comment by pecopeco** [comment]
> > > > 可以考虑下eeui，rn最大的不可替代性是他的生态，看taro3未来能支持到什么程度
> > > 
> > > 
> > > eeui 不支持小程序
> > 
> > 
> > 跨app和小程序两端基本没得选，但uni不适合做长远打算
> 
> uni-app 跨小程序和 app

我意思是现阶段除了uni没得选，但是有坑，祝好

**Comment by Chen-jj** [comment]
3.2.0 已支持转换为 RN：https://github.com/NervJS/taro/issues/8180
