### ISSUE TITLE
taro-init(1) does not exist, try --help

### ISSUE THREAD

**Issue by KerwinChen** [NervJS/taro#699]
**问题描述**

在 Mac 上使用 yarn 全局安装 taro 后，运行 `taro init demo` 报错。

```
👽 Taro v1.0.3

taro-init(1) does not exist, try --help
```

**复现步骤**

成功安装 taro：

```
➜  Taro yarn global add @tarojs/cli   
yarn global v1.10.0
warning package.json: No license field
[1/4] 🔍  Resolving packages...
warning @tarojs/cli > babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
warning @tarojs/cli > @tarojs/transformer-wx > babel-plugin-remove-dead-code@1.3.2: use babel-plugin-minify-dead-code-elimination and babel-plugin-minify-guarded-expressions
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "@tarojs/cli@1.0.3" with binaries:
      - taro
✨  Done in 74.88s.
```

创建项目报错：

```
➜  Taro taro init demo                
👽 Taro v1.0.3

taro-init(1) does not exist, try --help
```

**期望行为**

正常使用 cli 工具。

**系统信息**

 - 操作系统: macOS Mojave 版本 10.14
 - Taro 版本 v1.0.3
 - Node.js 版本 v10.11.0

**补充信息**

有看到之前的一篇文章与我发生了一样的问题，但是重新安装了 cli 之后还是无效。

**Comment by Pines-Cheng** [comment]
这个就很奇怪了。。

**Comment by KerwinChen** [comment]
@Pines-Cheng 救救孩子吧。

**Comment by luckyadam** [comment]
重新安装下试试？

**Comment by smoothdvd** [comment]
same here.

taro-update(1) does not exist, try --help

**Comment by luckyadam** [comment]
换成 npm 或者 cnpm 安装试试

**Comment by foisonocean** [comment]
重装之后依然无法使用。
OS: macOS 10.14
taro v1.0.7
Node.js: v10.11.0
yarn: v1.10.1

**Comment by luckyadam** [comment]
@foisonocean 
![image](https://user-images.githubusercontent.com/1782542/46602420-bae9a100-cb22-11e8-9646-bff7ccd0bf29.png)

**Comment by jo32** [comment]
用 yarn 安装后遇到一样的问题，版本是 1.0.7

**Comment by luckyadam** [comment]
@jo32 

![](https://user-images.githubusercontent.com/1782542/46602420-bae9a100-cb22-11e8-9646-bff7ccd0bf29.png)

**Comment by heronlyj** [comment]
同样的问题，重新使用 npm 安装之后解决

**Comment by zacksleo** [comment]
Taro v1.2.0-alpha.2 依然有这个问题

**Comment by luckyadam** [comment]
@zacksleo 这就很奇怪了。。都是正常发布的

**Comment by smoothdvd** [comment]
@luckyadam 我看源码里好象已经取消用yarn来update了

**Comment by b1g3rr0r** [comment]
问题依然存在，使用 npm 安装之后解决

**Comment by smoothdvd** [comment]
macOS下可以这样：

~/.config/yarn/global/node_modules/\@tarojs/cli/bin/taro-update  project

**Comment by laozhu** [comment]
为什么 macOS 上装完了创建不了项目，报同样的错。
Taro v1.1.3 使用 yarn 安装。

**Comment by zerocsss** [comment]
为什么 macOS 上装完了创建不了项目，报同样的错。
Taro v1.1.3 使用 yarn 安装。

**Comment by zacksleo** [comment]
先用 npm 安装， yarn 有问题

**Comment by zerocsss** [comment]
npm 安装不了
fetchMetadata: sill fetchPackageMetaData error for @tarojs/transformer-wx@1.1.4 No matching version found

**Comment by luckyadam** [comment]
@zerocsss 再试一下，刚刚在同步 npm 包

**Comment by Mr-ou** [comment]
我今天升级taro-cli也遇到了这个问题   在~/.config/yarn/global/node_modules/ 路径把 /@tarojs 包删掉，命令就正常了

**Comment by smoothdvd** [comment]
@Mr-ou 你删除了这个，命令行还能运行？

**Comment by MaoLiZi** [comment]
如何删除用yarn全部安装的taro所有包？

**Comment by 1990jtf** [comment]
已开始，我也是使用yarn安装的，也是构建taro-init(1) does not exist 错误，使用npm 安装解决了

**Comment by 17dian** [comment]
我用yarn，同样报错 taro-init(1) does not exist, try --help

**Comment by yucopowo** [comment]
报错直接使用  npx @tarojs/cli init myApp

**Comment by vinurs** [comment]
这两种安装方式安装出来的taro有啥区别吗？这个问题好像yarn一直没解决

**Comment by steveoOn** [comment]
我 yarn 安装也遇到同样的问题，👽 Taro v1.2.8, yarn 1.12.3

**Comment by saqing** [comment]
加一下环境变量  ~/.config/yarn/global/node_modules/@tarojs/cli/bin/

**Comment by vinurs** [comment]
@saqing 果然加到PATH里面就好了

**Comment by Lonecy** [comment]
同样的问题 用不了呀

**Comment by dzlishen** [comment]
使用yarn安装的报taro-init不存在。使用Npm安装 的时候报npm ERR! pna.nextTick is not a function。这是怎么错啊。

**Comment by eastFang** [comment]
yarn 安装的有问题；
用npm安装就ok了

**Comment by dzlishen** [comment]
> 我 yarn 安装也遇到同样的问题，👽 Taro v1.2.8, yarn 1.12.3

您这个问题解决了没，我电脑上的npm不能用。npm -v都报错。

**Comment by FradSer** [comment]
`export PATH="/Users/FradSer/.config/yarn/global/node_modules/@tarojs/cli/bin/:$PATH"`

**Comment by biaomingzhong** [comment]
应该是 yarn 安装二进制包的时候，文件软连接映射问题，改了软连接就没事

```
ln -f -s ~/.config/yarn/global/node_modules/@tarojs/cli/bin/taro /usr/local/bin/taro
```

**Comment by vinurs** [comment]
只能通过这种方式手动解决吗？能否像npm那样安装好就直接可用了

**Comment by alfredzh** [comment]
```
👽 Taro v1.2.22

error: taro-init(1) does not exist, try --help
```

+1

**Comment by imWildCat** [comment]
> 应该是 yarn 安装二进制包的时候，文件软连接映射问题，改了软连接就没事
> 
> ```
> ln -f -s ~/.config/yarn/global/node_modules/@tarojs/cli/bin/taro /usr/local/bin/taro
> ```

这么久了还不解决。既然要用 npm 安装，主页为什么还支持 yarn？

**Comment by vinurs** [comment]
一样的，这个问题报出来已经很久了，也不知道为啥到现在一直都不解决，只有手动解决方案

**Comment by handycode** [comment]
遇到同样的问题
mac 10.14.4 Taro v1.2.26 yarn v1.15.2
既然这么多人遇到问题，可否在安装文档上，写一下注释？

**Comment by xiaoxintang** [comment]
2019-05-20问题依然存在

**Comment by GreatAuk** [comment]
```
Taro v1.3.0-beta.5

error: taro-init(1) does not exist, try --help

**Comment by wolfstark** [comment]
同样的问题，mac os上 使用yarn会复现问题

**Comment by Garfield550** [comment]
可能是 commander.js 的问题， Yarn 新版本改了一些行为，主要发生在使用 Sub Command 模式（如 `taro build --param` 而不是 `taro --build --param1`）的项目上。

Ref:
https://github.com/tj/commander.js/issues/786
https://github.com/tj/commander.js/pull/935

**Comment by wangdan3024** [comment]
我是一开始就用npm 安装的，然后出现了taro不是内部或外部命令，然后又改成yarn安装 出现同样的问题，使用npm info taro又能查到taro的版本 再node得依赖包也能找到taro得文件

**Comment by bluegeek** [comment]
刚刚我也遇见了这个问题，是不准备解决了吗？

**Comment by Garfield550** [comment]
> 刚刚我也遇见了这个问题，是不准备解决了吗？

需要等 https://github.com/tj/commander.js 解决。

**Comment by bluegeek** [comment]
> > 刚刚我也遇见了这个问题，是不准备解决了吗？
> 
> 需要等 https://github.com/tj/commander.js 解决。

谢谢

**Comment by asiareal** [comment]
这么久了yarn 还是没解决

**Comment by LovageIO** [comment]
我用--force 重装了之后，这个问题解决了

`npm install -g @tarojs/cli --force`

**Comment by tcper** [comment]
依然存在这个问题，就给close了？

**Comment by mihujun1991** [comment]
.bin 的文件名拼接 commander 执行的命令，必须和指向的文件名保持一致，否则在 mac上出现此问题
