### ISSUE TITLE
（支付宝小程序）swiper 组件只有首尾 swiper-item 显示，其他的显示位空白

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#6995]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/vdfor/taro-issues-demo/tree/master/ali-swiper-only-show-first-and-end](https://github.com/vdfor/taro-issues-demo/tree/master/ali-swiper-only-show-first-and-end)
**小程序基础库: 1.24.0**
**使用框架: React**

### 复现步骤
1) taro init project
2) 修改 pages/index/index.tsx 代码如下
```tsx
import React, { Component } from 'react';
import { View, Swiper, SwiperItem, Image } from '@tarojs/components';

const data = [
  { id: 0, url: 'https://img13.360buyimg.com/ling/jfs/t1/139024/36/900/347788/5ee9cc27Effb0c16b/ce004d13e1a1479c.png' },
  { id: 1, url: 'https://img10.360buyimg.com/ling/jfs/t1/112290/35/2116/67015/5e9eee51E11ea7938/886d7ddc2e9e6026.png' },
  { id: 2, url: 'https://img30.360buyimg.com/ling/jfs/t1/71910/7/14212/335822/5dba8942E897651f1/3a9d17f7f54b635e.jpg' },
  { id: 3, url: 'https://img20.360buyimg.com/ling/jfs/t1/117964/14/2118/145903/5e9eee0aE8897b3dd/bd435e6161779ad1.png' },
]

export default class Index extends Component {

  render() {
    return (
      <View>
        <Swiper circular>
          {data.map(({ id, url }) => (
            <SwiperItem key={id}>
              <Image src={url} mode="scaleToFill" />
            </SwiperItem>
          ))}
        </Swiper>
      </View>
    )
  }
}
```
3) 运行。
4) 滑动swiper即可复现

也可以直接下载最小化仓库运行复现

### 期望结果
轮播图可正常使用

### 实际结果
只有首尾两屏显示，其他的显示空白（共4个item，第一张图为第一个item，第二张图为第2个item）
![批注 2020-07-10 143951](https://user-images.githubusercontent.com/9846146/87124523-8983a380-c2bb-11ea-8acd-e8c61005dd1e.png)
![批注 2020-07-10 144035](https://user-images.githubusercontent.com/9846146/87124531-8be5fd80-c2bb-11ea-81a8-f7f2fd60ae43.png)

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\vdfor\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
通过开发者工具，发现空白的 swiper-item 的 style 没有加上 transform

**Comment by vdfor** [comment]
临时解决方案时手动在 `swiper-item` 的 style 上加上 `transform`

```jsx
const Index = () => (
<Swiper circular>
          {data.map(({ id, url },index) => (
            <SwiperItem key={id} style={{transform: `translate(${index * 100}%,0) translateZ(0)`}}>
              <Image src={url} mode="scaleToFill" />
            </SwiperItem>
          ))}
</Swiper>)
```

**Comment by Chen-jj** [comment]
issue-helper 中平台要选择好，不然 label 会打错，不便分类与搜索

**Comment by Chen-jj** [comment]
支付宝的 `swiper-item` 在 template 中对写法有一定规定，下个版本我们改下生成的 template 模板

**Comment by fred8617** [comment]
style去掉之后彻底不好使了，哪个版本更新啊。。。我们已经开始兼容支付宝小程序了 @Chen-jj

**Comment by Chen-jj** [comment]
@fred8617 楼上需要 style 来 hack 的办法只能在 3.0.6 或之前版本用着先了。。模板的改动尽量争取下周发吧，还需要内部 review 一下改动。

**Comment by slipkinem** [comment]
> @fred8617 楼上需要 style 来 hack 的办法只能在 3.0.6 或之前版本用着先了。。模板的改动尽量争取下周发吧，还需要内部 review 一下改动。

意思就是下周才能解决这个问题？

**Comment by vdfor** [comment]
> > @fred8617 楼上需要 style 来 hack 的办法只能在 3.0.6 或之前版本用着先了。。模板的改动尽量争取下周发吧，还需要内部 review 一下改动。
> 
> 意思就是下周才能解决这个问题？

急的话可以临时使用3.0.5 + hack的方式解决（不建议3.0.6）；不急的话等3.0.8
