### ISSUE TITLE
H5  Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by xQuotes** [NervJS/taro#6999]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS/taro/blob/4c8a5ea9758f9c1c7e1efd1c9f4271a55c8feb97/packages/taro-h5/src/api/utils/index.js#L24](https://github.com/NervJS/taro/blob/4c8a5ea9758f9c1c7e1efd1c9f4271a55c8feb97/packages/taro-h5/src/api/utils/index.js#L24)
**浏览器版本: Chrome 83**
**使用框架: React**

### 复现步骤
https://github.com/NervJS/taro/blob/4c8a5ea9758f9c1c7e1efd1c9f4271a55c8feb97/packages/taro-h5/src/api/utils/index.js#L24

### 期望结果
不报错

### 实际结果
报错  Uncaught TypeError: Cannot read property 'path' of null

### 环境信息
```
 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
```

**Comment by louiebb** [comment]
请问楼主，解决了吗？我也遇到了
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/24762139/208282050-f3320c7c-e9f1-438c-ae6d-ff1e55fea4b9.png">

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/24762139/208282058-3380c651-9b45-41d9-ba27-11a2de031996.png">
