### ISSUE TITLE
Input 组件，placeholder h5显示unicode编码

### ISSUE THREAD

**Issue by xiaohuangyuson** [NervJS/taro#70]
<Input type='text' placeholder='最大输入长度为10' maxlength="10"/>

简单测了下文档的组件跑在h5端的效果。
input placeholder 解析出来的是 /u5233这种

Picker 还有很多组件，在h5端，直接报错，是我看的文档有问题吗？

**Comment by luckyadam** [comment]
placeholder中文的问题这里有说明~
https://github.com/NervJS/taro/issues/55

另外组件报错能不能提供下截图？

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/3b75aac120b2b902d53fb66752831d340a67b26a
应该修复了 babel 6 的 [unicode](https://github.com/babel/babylon/issues/271) 问题。

不知道组件有什么问题？
