### ISSUE TITLE
【Bug】配置了环境变量，却依然执行了引入的文件

### ISSUE THREAD

**Issue by zhou1992zg** [NervJS/taro#700]
**问题描述**
本人引入了一个只在H5页面才编译的组件<TaroQMap />
并且用环境变量让组件在H5页面下才执行，
配置环境变量代码如下：
![2018-09-26 3 33 00](https://user-images.githubusercontent.com/29066081/46064248-7e708980-c1a1-11e8-8bdb-81b91510aaa2.png)
在编译小程序之后，如下报错：
![2018-09-26 3 31 43](https://user-images.githubusercontent.com/29066081/46064185-53863580-c1a1-11e8-82d4-9922d1dc616c.png)
**复现步骤**
页面映入组件代码：
`import TaroQMap from "../../component/H5Qmap/h5Qmap";`

**期望行为**
1.对应页面编译时，禁止<TaroQMap />类似特殊环境组件编译

**报错信息**
小程序页面报错信息：
![2018-09-26 3 31 43](https://user-images.githubusercontent.com/29066081/46064575-50d81000-c1a2-11e8-89e8-448ae44cafe3.png)
H5页面正常执行
**系统信息**

 - 操作系统: [Mac OS 10.13.4]
 - Taro 版本 [Taro v1.0.3]
 - Node.js 版本 [v10.8.0]

**Comment by luckyadam** [comment]
新版本已修复
