### ISSUE TITLE
3.0.2 CoverView中的View或Text的文字过长不会自动换行

### ISSUE THREAD

**Issue by aidisheng** [NervJS/taro#7005]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
CoverView
 View
    这里是长到要换行的文字，用scss控制要自动换行，只有头条小程序能自动换行，微信小程序和百度小程序都不会自动换行。
 View
CoverView

### 期望结果
CoverView 能够支持自动换行

### 实际结果
CoverView 微信小程序和百度小程序都不会自动换行。

### 环境信息
```
Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.16.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Think\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
```

**Comment by gouflv** [comment]
微信小程序里，需要给CoverView加 `white-space: pre-line;`

**Comment by Chen-jj** [comment]
@gouflv 正解
