### ISSUE TITLE
taro.uploadFile 支持 PUT

### ISSUE THREAD

**Issue by vsilkroad** [NervJS/taro#7007]
### 这个特性解决了什么问题？
很多平台的文件上传接口支持的是 PUT 方式，但是现在使用 uploadFile 不支持，使用 taro.request 上传文件又实现不了。

### 这个 API 长什么样？
可以用 PUT 方式上传文件

**Comment by Chen-jj** [comment]
@vsilkroad 欢迎 PR~

**Comment by FredZeng** [comment]
uploadFile 主要是为了对标 微信的API 吧，`wx.uploadFile` 官方文档就只支持 `POST`。

**Comment by bigmeow** [comment]
wx.uploadFile 
[my.uploadFile](https://opendocs.alipay.com/mini/api/kmq4hc)
[tt.uploadFile](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/network/http/tt-upload-file/)
[swan.uploadfile](https://smartprogram.baidu.com/docs/develop/api/net/uploadfile/)

均不支持
