### ISSUE TITLE
js代码特殊字符编译后与原字符不一致

### ISSUE THREAD

**Issue by facesea** [NervJS/taro#701]
**问题描述**
比如我原代码是`var a = '2%1a$6&'`,编译后就会变成`var a = '2$6&'`,这种情况一般都是碰到`%`符号后面跟几个字母的情况。

**复现步骤**
[复现问题的步骤]
1. 原js代码：`var a = '2%1a$6&'`
2. 自动编译后: `var a = '2$6&'`
3. 运行编译后代码后与预期不符合

**期望行为**
原代码：`var a = '2%1a$6&'`
编译后：`var a = '2%1a$6&'`

**报错信息**

无

**系统信息**

 - 操作系统: MacOs
 - Taro 版本: v1.0.3
 - Node.js 版本: v8.11.1

**补充信息**
目前已试了转义字符和字符拼接都无法解决。

**Comment by luckyadam** [comment]
是编译到小程序么

**Comment by facesea** [comment]
@luckyadam  是的，就是编译到小程序
