### ISSUE TITLE
无法使用Provider 使用Provider会导致React is not defined

### ISSUE THREAD

**Issue by Smi1e96** [NervJS/taro#7010]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Smi1e96/Taro3.git](https://github.com/Smi1e96/Taro3.git)
**小程序基础库: 2.10.0**
**使用框架: React**

### 复现步骤
运行代码既可复现代码

### 期望结果
app.tsx 能挂载Provider使用dva

### 实际结果
无法挂载Provider
![image](https://user-images.githubusercontent.com/31199247/87263608-48280980-c4f0-11ea-83b6-2bb5a69548e3.png)

![image](https://user-images.githubusercontent.com/31199247/87263599-3c3c4780-c4f0-11ea-88d7-d7f5deaf3dc9.png)

不使用Provider包裹 正常使用
### 环境信息
```
  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      nervjs: ^1.5.7 => 1.5.7 
```

**Comment by Chen-jj** [comment]
Taro3 直接使用 `react-redux`：

```js
// app.tsx
import React, { Component } from 'react'
import { Provider } from 'react-redux'
```

config/index.js 需要补充 **framework** 字段：

```js
// config/index.js
const config = {
  // ...
  framework: 'react'
}
```

**Comment by Smi1e96** [comment]
@Chen-jj  我试了 还是会报
![image](https://user-images.githubusercontent.com/31199247/87763608-a2560100-c847-11ea-860e-1e3fd4a00004.png)

**Comment by Chen-jj** [comment]
@Smi1e96 我用你的项目改了这两个地方就可以了，重新安装依赖等再试试吧。

**Comment by Smi1e96** [comment]
@Chen-jj 非常感谢:thumbsup:  解决了 犯了个低级错误 入口app.tsx 没有声明react:dizzy_face:
