### ISSUE TITLE
希望 app.config.ts 中配置页面的时候，能够以对象的形式配置页面信息（目前只能配置页面的路径）

### ISSUE THREAD

**Issue by martSforever** [NervJS/taro#7011]
### 这个特性解决了什么问题？
1. 目前taro 中是这样的形式，页面文件 src/pages/index.vue，配置页面信息的时候通过配置文件 src/pages/index.config.ts 来配置的；
2. 希望能够将 src/pages/index.config.ts 中对页面的配置信息，与 app.config.ts 中配置的页面信息做合并处理，而不是限制 app.config.ts 中配置页面只能是页面的路径字符串；
3. 因为我这边自己做了文件扫描管理，以 `-page` 结尾的会自动注册为页面，`-list-page` 结尾的页面会自动注册为可以下拉刷新的页面；然后 src/pages 目录下的目录会自动分包，页面配置信息是以注释的形式存在于页面代码顶部。目前受限于 app.config.ts 配置页面的时候只能配置路径字符串的原因，导致我的功能无法实现；

### 这个 API 长什么样？
希望 app.config.ts 中配置页面信息的时候，可以以对象的形式配置，而不是只能是页面的path路径。

**Comment by Chen-jj** [comment]
在全局配置中可以为配置各页面配置的意思？

**Comment by martSforever** [comment]
是的，因为我的页面配置信息是通过脚本生成的，会根据页面文件名自动填充一些页面的配置信息

**Comment by ruofeng086** [comment]
@Chen-jj 我也有同样的需求，app.config.ts不能读取其他ts文件的export？

**Comment by Chen-jj** [comment]
@martSforever 暂时不会考虑实现，全局配置和页面配置分别对应小程序的全局配置和页面配置文件，不太建议写太复杂的逻辑。

**Comment by Chen-jj** [comment]
@ruofeng086 配置文件使用了 **babel-register** 去编译，目前配置文件依赖的文件则没有编译，你写 `module.exports` 应该能读到。

**Comment by martSforever** [comment]
> @martSforever 暂时不会考虑实现，全局配置和页面配置分别对应小程序的全局配置和页面配置文件，不太建议写太复杂的逻辑。

有没有办法在 `config/index.js` 配置文件中提供一个函数属性，用来在最终生成 app.json 的之前，对app.json的内容做修改你看这样行不

**Comment by ruofeng086** [comment]
@Chen-jj routes我希望写ts呢？

**Comment by ruofeng086** [comment]
![image](https://user-images.githubusercontent.com/14192308/87413246-a215f580-c5fc-11ea-8611-7441e8ca1add.png)

@Chen-jj 编译h5会报错。

**Comment by shinken008** [comment]
个人觉得 config 应该共享 webpack 配置，defineConstants 在 config 里面用到还需要在 babel 在定义一下，有点蛋疼

**Comment by Chen-jj** [comment]
后续可以尝试一下把 config 纳入到 webpack 编译中。

**Comment by lifegit** [comment]
+1 
app.config.ts 中的 pages（路由），需要 import 进来，报错 Unexpected token 'export'

**Comment by Poem7200** [comment]
+1
对于pages目录，其实完全可以全局配置一个常量到处用，而不是**必须****仅仅**在app.config.ts里面手写一遍字符串

**Comment by Jairwin-L** [comment]
+1

```bash
SyntaxError: Unexpected token 'export'
```

```md
├── utils                
│   ├── index.ts
│   └── object.ts
```
```ts
function objectToParams<T>(obj: T) {
  // xxx
}

export default objectToParams;
```
```ts
export { default as objectToParams } from './object';
```

**Comment by Chen-jj** [comment]
Taro 最新版本已支持在 app、page 配置文件中使用 defineConstants、alias 配置，也已支持引入 esm 文件
