### ISSUE TITLE
支付宝无法显示PickerViewColumn组件

### ISSUE THREAD

**Issue by liujiayii** [NervJS/taro#7013]
### 相关平台
支付宝小程序

**小程序基础库: 1.24.1**
**使用框架: React**

### 复现步骤
npx @tarojs/cli init myApp

```
<PickerView indicatorStyle='height: 50px;' style='width: 100%; height: 300px;' >
          <PickerViewColumn>
            <View>1年</View>
         </PickerViewColumn>
 </PickerView>
```

### 期望结果
正确显示

### 实际结果
无法显示，未报错
支付宝：
![image](https://user-images.githubusercontent.com/38902744/87276071-28a1d880-c512-11ea-9164-a20091b91d2a.png)
微信：
![image](https://user-images.githubusercontent.com/38902744/87276099-35bec780-c512-11ea-90df-d3cb41f9e41a.png)

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\liuji\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD

```

**Comment by liujiayii** [comment]
@Chen-jj 请问是否有临时的应急解决方案，这个影响挺大的，看taro的版本排期是很久以后了，谢谢

**Comment by Chen-jj** [comment]
@liujiayii 支付宝 PickerView 对 template 结构有一定要求，这里要改生成的模板，还是要等发版解决。

**Comment by liujiayii** [comment]
> @liujiayii 支付宝 PickerView 对 template 结构有一定要求，这里要改生成的模板，还是要等发版解决。

像这种比较严重的问题是否应该即时修复，等待排期更新的话，很多公司在用这个有bug的版本就无法迭代小程序了

**Comment by Goodvincent** [comment]
请问这个问题什么时候能发版解决 @Chen-jj

**Comment by Nickhao485** [comment]
@Chen-jj 百度小程序也有同样的问题，3.0.10无法使用
