### ISSUE TITLE
app.config.ts无法import其他ts配置文件的export

### ISSUE THREAD

**Issue by ruofeng086** [NervJS/taro#7017]
### 相关平台
H5

### 复现仓库
[https://taro-club.jd.com/topic/1465/taro-3-0-0-beta-3-app-config-ts-%E9%97%AE%E9%A2%98](https://taro-club.jd.com/topic/1465/taro-3-0-0-beta-3-app-config-ts-%E9%97%AE%E9%A2%98)
**浏览器版本: chrome**
**使用框架: React**

### 复现步骤
1.taro init demo

### 期望结果
app.config.ts 可以读取config中export的配置

### 实际结果
Cannot find module '@config/routes'

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.1 - D:\Programs\nodejs\node.EXE
      Yarn: 1.22.4 - D:\Programs\nodejs\yarn.CMD
      npm: 6.14.5 - D:\Programs\nodejs\npm.CMD
```

**Comment by shinken008** [comment]
确实有点坑，原因是config只会被babel编译，不会被webpack编译

**Comment by Chen-jj** [comment]
duplicate of #7011
