### ISSUE TITLE
Taro3.0, Vue2 使用 picker-view 在真机上滚动选择的时候抖动

### ISSUE THREAD

**Issue by martSforever** [NervJS/taro#7018]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/martsforever-issues/taro-issues-catch/tree/taro-picker-view/](https://gitee.com/martsforever-issues/taro-issues-catch/tree/taro-picker-view/)

**请注意，是 `taro-picker-view` 这个分支**

---

**小程序基础库: 2.12.0**
**使用框架: Vue2**

### 复现步骤
1. 安装依赖；
2. 启动小程序：npm run dev:weapp；
3. 使用微信开发者工具打开dist文件夹，打开的首页就是示例页面；
4. 在开发者工具中正常，但是在真机上，滚动选择 picker-view-column 中的选项时，有抖动的现象。这个现象可以描述为：当滚动选中某一个选项之后，pick-view-column迅速滚动到第一项，然后又迅速滚动到选中的一项。当 picker-view-column中的选项越多时，抖动幅度越大，越明显；
5. 真机：iPhone Xs Max， IOS 13.3.1, 64G内存；

### 期望结果
使用 picker-view滚动选择的时候，不出现抖动现象

### 实际结果
使用 picker-view滚动选择的时候，出现抖动现象

### 环境信息
```
👽 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - D:\0_install\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - D:\0_install\nodejs\npm.CMD

```

---
### 补充信息
希望能尽快解决这个问题，影响比较大。

**Comment by Chen-jj** [comment]
@martSforever 非常抱歉过了这么久才处理，刚在 iphone xs max 上试了没有复现，可以升级到最新版本再试试：
![RPReplay_Final1598885350 2020-08-31 22_52_50](https://user-images.githubusercontent.com/11807297/91733915-d198b580-ebdc-11ea-8f29-e3541feea84f.gif)
