### ISSUE TITLE
使用taro-with-weapp withWeapp HOC组件 调用 componentWillMount 报 Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by shinken008** [NervJS/taro#7027]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
```js
@withWeapp("Page")
class _C extends React.Component {}
```
只要使用了这个装饰器一定会报错，基于React框架取到的this实例没有$router属性。

具体代码：https://github.com/NervJS/taro/blob/next/packages/taro-with-weapp/src/index.ts#L226

参考文档：https://taro-docs.jd.com/taro/docs/migration#%E8%B7%AF%E7%94%B1

### 期望结果
正常运行不报错

### 实际结果
Cannot read property 'params' of undefined

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: ^3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: ^16.13.1 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.9.5
```

**Comment by shinken008** [comment]
withWeapp 实现 this.state defineGetter也有问题，取的是Taro.component.state，不是框架的，结果外部拿到的就是null

**Comment by shinken008** [comment]
`this.executeLifeCycles(this.willMounts, this.$router ? this.$router.params : {});` 魔改后不报错，取到的this.state为空

**Comment by supercharleszhu** [comment]
遇到同样的问题，求解决

**Comment by shinken008** [comment]
这个 bug 很棘手吗，升级遇到的问题迫切需要解决

**Comment by Yechuanjie** [comment]
问题确实出在升级后使用的 `withWeapp `这个装饰器。

另外，使用 ` taro convert`  （taro v3.0.5） 将微信小程序转换为 `React ` 或  `Vue` 时，都会使用 `withWeapp `装饰器。
当转换为 `React` 时，会出现相同的报错 `Cannot read property 'params' of undefined`
当转换为 `Vue` 时，会出现 `Cannot set property 'render' of undefined` 的错误

**Comment by SnowHot** [comment]
同求怎么解决，1.x升级到2.x以后很多页面this.state是undefined，要都去掉@withweapp的话改动太大，这几天分享到朋友圈加不上头发都白了

**Comment by shinken008** [comment]
@SnowHot @luckyadam 白了还能染回来，秃了就麻烦了。withweapp 挂了，业务代码用到太多，从 2 到 3 的升级基本无望。感觉官方人手不够，bug太多了，这个优先级应该提高啊。

**Comment by Chen-jj** [comment]
已修复
