### ISSUE TITLE
Taro版本不一致

### ISSUE THREAD

**Issue by vscing** [NervJS/taro#7030]
### 相关平台
微信小程序

### 复现仓库
[无](无)
**小程序基础库: 无**
**使用框架: React**

### 复现步骤
全局安装@tarojs/cli，打印Taro -v是3.0.2
项目目录启动taro build --type weapp "--watch"
显示Taro 1.3.25
项目目录下安装@tarojs/cli
启动项目版本正常
安装npm插件包之后
启动项目版本又是1.3.25

### 期望结果
版本一致

### 实际结果
版本不一致

### 环境信息
```
� Taro v3.0.2
  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.18.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\nodejs\npm.CMD

```

**Comment by iugo** [comment]
`package.json` 里面怎么写的?

**Comment by vscing** [comment]
> `package.json` 里面怎么写的?
{
  "name": "xx",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "templateInfo": {
    "name": "redux",
    "typescript": true,
    "css": "less"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/cli": "^3.0.2",
    "@tarojs/components": "3.0.2",
    "@tarojs/react": "3.0.2",
    "@tarojs/runtime": "3.0.2",
    "@tarojs/taro": "3.0.2",
    "babel-plugin-import-static-files": "^1.0.4",
    "dva-core": "^2.0.2",
    "dva-loading": "^3.0.20",
    "react": "^16.10.0",
    "react-dom": "^16.10.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/mini-runner": "3.0.2",
    "@tarojs/plugin-babel": "^2.2.10",
    "@tarojs/webpack-runner": "3.0.2",
    "@types/react": "^16.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^2.x",
    "@typescript-eslint/parser": "^2.x",
    "babel-preset-taro": "3.0.2",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.0.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^1.6.1",
    "stylelint": "9.3.0",
    "typescript": "^3.7.0"
  }
}

**Comment by Chen-jj** [comment]
@vscing 直接使用 taro 命令使用的是全局 CLI ，npm script 中使用 taro 是使用项目本地 CLI。

自己检查一下依赖吧，`which taro` 检查全局 CLI 安装位置。这并不是 Taro 的 bug，
