### ISSUE TITLE
3.0.2 无法在app.config.ts中引入图片

### ISSUE THREAD

**Issue by vscing** [NervJS/taro#7031]
### 相关平台
微信小程序

**小程序基础库: 无**
**使用框架: React**

### 复现步骤
import home from './assets/images/tabBar/home.png'

list: [
      {
        pagePath: "pages/home/index",
        text: "首页",
        iconPath: home,
        selectedIconPath: './assets/images/tabBar/home-active.png'
      }
｝

### 期望结果
能正常使用selectedIconPath: './assets/images/tabBar/home-active.png'

### 实际结果
tabBar.list[0].iconPath 文件不存在
tabBar.list[0].selectedIconPath 文件不存在

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.18.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
duplicate of #6516
