### ISSUE TITLE
MiniProgramError 没有找到页面实例

### ISSUE THREAD

**Issue by vscing** [NervJS/taro#7034]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
拉下来react redux less typescript模板
第一个page/index/index换成hooks写法
import Taro from '@tarojs/taro'
import React, { useState, useEffect } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import { View, Text } from '@tarojs/components'
import './index.less'

export default () => {
  

  return (
    <View className='index'>
      <Text>Hello world!</Text>
    </View>
  )
}
报错

### 期望结果
期望跟前两个版本一样正常运行

### 实际结果
The above error occurred in the <AppWrapper> component:
    in AppWrapper

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

MiniProgramError
没有找到页面实例。
如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues
Error: 没有找到页面实例。
如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues
    at ensure (http://127.0.0.1:50948/appservice/taro.js:14066:11)
    at AppWrapper.<anonymous> (http://127.0.0.1:50948/appservice/taro.js:17199:9)
    at callCallback (http://127.0.0.1:50948/appservice/vendors.js:16640:12)
    at commitUpdateEffects (http://127.0.0.1:50948/appservice/vendors.js:16678:7)
    at commitUpdateQueue (http://127.0.0.1:50948/appservice/vendors.js:16666:3)
    at commitLifeCycles (http://127.0.0.1:50948/appservice/vendors.js:25151:11)
    at commitLayoutEffects (http://127.0.0.1:50948/appservice/vendors.js:28354:7)
    at Object.invokeGuardedCallbackImpl (http://127.0.0.1:50948/appservice/vendors.js:24584:10)
    at invokeGuardedCallback (http://127.0.0.1:50948/appservice/vendors.js:24761:31)
    at commitRootImpl (http://127.0.0.1:50948/appservice/vendors.js:28092:9)

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s a useEffect cleanup function 
    in Unknown (created by Page)
    in root (created by Page)
    in Page (created by AppWrapper)
    in Provider (created by App)
    in App (created by AppWrapper)
    in AppWrapper

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.18.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\nodejs\npm.CMD

```

**Comment by Mao5211** [comment]
可以问一下怎么解决的吗，今天编译的时候也遇到一样的问题了

**Comment by vscing** [comment]
> 可以问一下怎么解决的吗，今天编译的时候也遇到一样的问题了

你是怎么写的？

**Comment by gallop** [comment]
我也遇到此问题了，我页面都是hooks的写法，能不能把解决办法贴出来一下。

**Comment by TukulHX** [comment]
这个问题怎么解决呢？我尝试了hooks的写法和class写法，都没能生效

**Comment by vscing** [comment]
> 这个问题怎么解决呢？我尝试了hooks的写法和class写法，都没能生效

其它页面写的有问题

**Comment by vscing** [comment]
> 我也遇到此问题了，我页面都是hooks的写法，能不能把解决办法贴出来一下。

这个就是其它页面有问题导致的，我是移植代码时候没注意。

**Comment by guohuihot** [comment]
解决了吗？坐等

**Comment by vscing** [comment]
> 解决了吗？坐等

解决了啊，看看页面写法对不对，仔细检查一下

**Comment by physihan** [comment]
我也遇到这个问题，找了半天也排查不出问题，我觉得这个issue可以重新打开

**Comment by vscing** [comment]
> 我也遇到这个问题，找了半天也排查不出问题，我觉得这个issue可以重新打开

再检查一下，写法还是有问题的。

**Comment by physihan** [comment]
> > 我也遇到这个问题，找了半天也排查不出问题，我觉得这个issue可以重新打开
> 
> 再检查一下，写法还是有问题的。

我问题解决了，是依赖库的问题，我安装了taro-ui，然后发现taroui把依赖关系修改了，具体可以参考

**Comment by guohuihot** [comment]
不是写法的问题，有没有人给一个hooks redux的demo, 现在根本就跑不起来

**Comment by lz7git** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html?search-key=%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE

**Comment by ntop001** [comment]
我按快速开始下载的模板也跑不起来...
