### ISSUE TITLE
支付宝小程序无法触发 getAuthorize 获取用户手机号码

### ISSUE THREAD

**Issue by Henry-WHY** [NervJS/taro#7036]
### 相关平台
支付宝小程序

### 复现仓库
[https://gitee.com/Henry_WHY/taro_issue.git](https://gitee.com/Henry_WHY/taro_issue.git)
**小程序基础库: 支付宝 1.24.0**
**使用框架: React**

### 复现步骤
``` 
import React from 'react'
import Taro from '@tarojs/taro'
import { Button, View } from '@tarojs/components'
import './index.scss'

export default function Index() {
  function onGetAuthorize() {
    console.log('onGetAuthorize')
    Taro.getOpenUserInfo({
      success: function (userinfo) {
        console.log(userinfo)
      },
    })
  }

  function test() {
    console.log('111')
  }

  return (
    <View className='index'>
      <Button onClick={test}>测试</Button>
      <Button openType='getAuthorize' onGetAuthorize={onGetAuthorize}>
        getPhoneNumber
      </Button>
    </View>
  )
}
```

### 期望结果
唤起用户授权，获取用户手机号码

### 实际结果
方法没有触发

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE        
      npm: 6.14.6 - C:\Users\henry\AppData\Roaming\npm\npm.CMD
```

**Comment by Chen-jj** [comment]
@Henry-WHY scope

```js
<Button openType='getAuthorize' onGetAuthorize={onGetAuthorize} scope='userInfo'>
  getPhoneNumber
</Button>
```

**Comment by hight-lig** [comment]
> @ Henry-WHY范围
> 
> ```js
> <按钮 的openType = 'getAuthorize'  onGetAuthorize = { onGetAuthorize } 范围= 'USERINFO' >
>   getPhoneNumber
> < / /按钮>
> ```

在ide里面会有获取手机号码的提示，在真机的时候没有反应， 是bug还是说不支持获取手机号码？

**Comment by konka-king** [comment]
> @Henry-WHY scope
> 
> ```js
> <Button openType='getAuthorize' onGetAuthorize={onGetAuthorize} scope='userInfo'>
>   getPhoneNumber
> </Button>
> ```



> > @ Henry-WHY范围
> > ```js
> > <按钮 的openType = 'getAuthorize'  onGetAuthorize = { onGetAuthorize } 范围= 'USERINFO' >
> >   getPhoneNumber
> > < / /按钮>
> > ```
> 
> 在ide里面会有获取手机号码的提示，在真机的时候没有反应， 是bug还是说不支持获取手机号码？

我在 ide 里面 和真机 里面 都没有提示，但是 在 onGetAuthorize 里面调用 my.getPhoneNumber 可以返回 response 报文
