### ISSUE TITLE
picker组件设置了value后，onColumnChange不触发

### ISSUE THREAD

**Issue by YES-Lee** [NervJS/taro#7037]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
picker组件为multiSelector模式时，给组件设置了value后onColumnChange事件不会触发。去掉value能触发

### 期望结果
onColumnChange正常触发

### 实际结果
onColumnChange不能正常触发

### 环境信息
```
 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /var/folders/gg/kscwh9q51rlg__5yf4ldxqrw0000gn/T/yarn--1594712020668-0.5667410791842591/node
      Yarn: 1.21.1 - /var/folders/gg/kscwh9q51rlg__5yf4ldxqrw0000gn/T/yarn--1594712020668-0.5667410791842591/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.2 => 3.0.2 
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/router: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: 3.0.2 => 3.0.2 
      @tarojs/taro-h5: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      eslint-plugin-taro: 3.0.2 => 3.0.2 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: ^16.13.1 => 16.13.1 
      taro-ui: 3.0.0-alpha.1 => 3.0.0-alpha.1 
```

**Comment by without-yy** [comment]
我遇到的是增加value能触发onColumnChange，没有value时不触发

**Comment by YES-Lee** [comment]
补充一个：我暂时不设置value，但是点击一次确定后，onColumnChange也是不会再触发

**Comment by YES-Lee** [comment]
问题已解决，查看了迁移指南（有更新），修改编译配置后正常。
Taro3刚发布的时候，从2.x升级过来，后来更新了这个配置，
![image](https://user-images.githubusercontent.com/19748456/88520384-15206280-d026-11ea-85f7-48b4dbfb9484.png)

**Comment by YES-Lee** [comment]
问题已解决，查看了迁移指南（有更新），修改编译配置后正常。
Taro3刚发布的时候，从2.x升级过来，后来更新了这个配置，
![image](https://user-images.githubusercontent.com/19748456/88520384-15206280-d026-11ea-85f7-48b4dbfb9484.png)

**Comment by Henry-WHY** [comment]
> 问题已解决，查看了迁移指南（有更新），修改编译配置后正常。
> Taro3刚发布的时候，从2.x升级过来，后来更新了这个配置，
> ![image](https://user-images.githubusercontent.com/19748456/88520384-15206280-d026-11ea-85f7-48b4dbfb9484.png)

请问具体怎么操作的？遇见了同样的问题
