### ISSUE TITLE
getCurrentInstance().router.params获取到的是undefined

### ISSUE THREAD

**Issue by SunshineH2** [NervJS/taro#7039]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
import { getCurrentInstance } from '@tarojs/runtime';
import { useReady } from '@tarojs/taro';

url为/pages/homepage/index?code=1213，

useReady(() => {
    const a = getCurrentInstance().router;
    console.log(a, '----');
  });

打印结果为undefined

### 期望结果
能正常获取到参数

### 实际结果
参数为undefined

### 环境信息
```
Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - C:\devNode\nodejs\node.EXE
      Yarn: 1.19.1 - C:\devNode\nodejs\yarn.CMD
      npm: 6.9.0 - C:\devNode\nodejs\npm.CMD
```

**Comment by dreamthen** [comment]
使用Taro.Current.router.params

**Comment by apiaoqzh** [comment]
在Vue版开发中，不论是getCurrentInstance()还是 Taro.Current，都返回的是
```javascript
{
  app: null
  page: null
  router: null
}
```

**Comment by lzs2000131** [comment]
我改成用getCurrentInstance().page.path了

**Comment by 349989153** [comment]
@dreamthen 一样是undefined啊，你那不是吗

**Comment by dreamthen** [comment]
我这儿可以获取到呀，用Current

**Comment by 349989153** [comment]
@dreamthen 请问您是taro哪个版本？

**Comment by 349989153** [comment]
@dreamthen 是H5吗？小程序是可以取到的，没问题。题主也写了，相关平台是H5

**Comment by Chen-jj** [comment]
@SunshineH2 

```js
useReady(() => {
  const a = getCurrentInstance().router.params;
  console.log(a, '----');
});
```

https://taro-docs.jd.com/taro/docs/router/#%E8%B7%AF%E7%94%B1%E4%BC%A0%E5%8F%82

**Comment by Chen-jj** [comment]
> 在Vue版开发中，不论是getCurrentInstance()还是 Taro.Current，weapp下都返回的是
> 
> ```js
> {
>   app: null
>   page: null
>   router: null
> }
> ```

@apiaoqzh vue2 也是 ok 的，3.0.7，还有问题另外开个 issue，附上 demo 吧。

```js
<template>
  <view class="index">
    <text>{{ msg }}</text>
  </view>
</template>

<script>
import {Current, getCurrentInstance} from '@tarojs/taro'
import './index.scss'

export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  },
  mounted () {
    console.log(Current.router.params)
    console.log(getCurrentInstance().router.params)
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/11807297/90248531-712f1780-de6b-11ea-9783-5cd801767e84.png)

**Comment by zhaoweihan** [comment]
> > 在Vue版开发中，不论是getCurrentInstance()还是 Taro.Current，weapp下都返回的是
> > ```js
> > {
> >   app: null
> >   page: null
> >   router: null
> > }
> > ```
> 
> @apiaoqzh vue2 也是 ok 的，3.0.7，还有问题另外开个 issue，附上 demo 吧。
> 
> ```js
> <template>
>   <view class="index">
>     <text>{{ msg }}</text>
>   </view>
> </template>
> 
> <script>
> import {Current, getCurrentInstance} from '@tarojs/taro'
> import './index.scss'
> 
> export default {
>   data () {
>     return {
>       msg: 'Hello world!'
>     }
>   },
>   mounted () {
>     console.log(Current.router.params)
>     console.log(getCurrentInstance().router.params)
>   }
> }
> </script>
> ```
> 
> ![image](https://user-images.githubusercontent.com/11807297/90248531-712f1780-de6b-11ea-9783-5cd801767e84.png)

麻烦问一下，这个怎么解决的

**Comment by xueleilei** [comment]
切换到Version: 3.0.9  这个版本是好的。  3.0.13 这里是有bug的

**Comment by smarttang** [comment]
还是不能用...最新版依然还有这个问题。

**Comment by zhaoweihan** [comment]
> 切换到Version: 3.0.9 这个版本是好的。 3.0.13 这里是有bug的

请问有什么bug么，我刚更新到3.0.13，getCurrentInstance方法已经可以使用了

**Comment by smarttang** [comment]
> > 切换到Version: 3.0.9 这个版本是好的。 3.0.13 这里是有bug的
> 
> 请问有什么bug么，我刚更新到3.0.13，getCurrentInstance方法已经可以使用了

老哥厉害，我这3.0.11还是不能用，我升级下看看。。谢谢老哥哈。

**Comment by smarttang** [comment]
> > 切换到Version: 3.0.9 这个版本是好的。 3.0.13 这里是有bug的
> 
> 请问有什么bug么，我刚更新到3.0.13，getCurrentInstance方法已经可以使用了

按照最新的版本做了升级之后依然在h5下不能使用，只有在小程序端可以使用。

来源页面是基于点击跳转，有个参数：
```
    handleClick(obj) {
      this.$taro.navigateTo({
        url: '/pages/introduce/index?id=1'
      })
    }
```
点击完之后，接收页面的是这样的：
```
  created() {
     const { id } = this.$taro.getCurrentInstance().router.params
     console.log(id)
     console.log(this.$taro.getCurrentInstance().router.params)
     console.log(this.$taro.Current.router.params)
  },
  mounted() {
     const { id } = this.$taro.getCurrentInstance().router.params
     console.log(id)
     console.log(this.$taro.getCurrentInstance().router.params)
     console.log(this.$taro.Current.router.params)
  },
```
目前确定，h5下无效，不能用。
![image](https://user-images.githubusercontent.com/4961402/94392221-39b1cb80-018a-11eb-8fb5-9904c0e6286c.png)

**Comment by smarttang** [comment]
这是一个硬伤，这个解决不了的话，H5就用不了，意味着Taro只能用小程序了...
目前就卡在这，页面都绘制完了。。

**Comment by xueleilei** [comment]
> 这是一个硬伤，这个解决不了的话，H5就用不了，意味着Taro只能用小程序了...
> 目前就卡在这，页面都绘制完了。。

版本手动降到 3.0.9   H5就可以用了

**Comment by zhaoweihan** [comment]
> 这是一个硬伤，这个解决不了的话，H5就用不了，意味着Taro只能用小程序了...
> 目前就卡在这，页面都绘制完了。。

可以先用vuex eventCenter等其他的方案代替。不一定要用URL传参

**Comment by smarttang** [comment]
> > 这是一个硬伤，这个解决不了的话，H5就用不了，意味着Taro只能用小程序了...
> > 目前就卡在这，页面都绘制完了。。
> 
> 版本手动降到 3.0.9 H5就可以用了

测试了，3.0.9 当前降级都不可以用。应该是默认不支持这种h5的跨页面传值，这个可能是taro只支持微信小程序吧。
因为这个跳转的函数跟微信原生的命名一致，然后说明书目前停留在3.0.9上。。尴尬的一批。。。

**Comment by smarttang** [comment]
> > 这是一个硬伤，这个解决不了的话，H5就用不了，意味着Taro只能用小程序了...
> > 目前就卡在这，页面都绘制完了。。
> 
> 可以先用vuex eventCenter等其他的方案代替。不一定要用URL传参

感谢哈，当前场景如果用vuex eventCenter感觉不太合适，毕竟是接过来改造来着。
搞得太复杂还不如用vant重构呢。因为vant下这个问题就不是问题，默认都支持来着。
我想用taro的原因主要是想长远未来一端多用，只维护一套，就目前来看，taro确实不太成熟...
我想多了..

**Comment by smarttang** [comment]
针对这个case，我彻底解决掉了，后人可以借鉴，我建议官方做个组件，比较方便新手使用，老鸟可以跳过。。。
```
    const url = require('url')
    if (this.$taro.getEnv() == 'WEB'){
      let path = url.parse(decodeURIComponent(this.$el.baseURI)).hash;
      let query = undefined;
      let requestPath = new Object();
      if (path.indexOf('#') != -1){
        query = url.parse(path.split('#')[1]).query
      }else{
        query = url.parse(path).query
      }
      let queryGroup = query.split('&');
      for (var i = 0; i < queryGroup.length; i++){
        requestPath[queryGroup[i].split('=')[0]] = unescape(queryGroup[i].split('=')[1])
      }
      console.log(requestPath)
    }
```
建议自己手动封装下，然后就可以用了，自己在需要页面调用就可以。
一个中午手写的插件，连续熬了2个通宵研究taro有点体力不支了....orz...

**Comment by zhaoweihan** [comment]
> 针对这个case，我彻底解决掉了，后人可以借鉴，我建议官方做个组件，比较方便新手使用，老鸟可以跳过。。。
> 
> ```
>     const url = require('url')
>     if (this.$taro.getEnv() == 'WEB'){
>       let path = url.parse(decodeURIComponent(this.$el.baseURI)).hash;
>       let query = undefined;
>       let requestPath = new Object();
>       if (path.indexOf('#') != -1){
>         query = url.parse(path.split('#')[1]).query
>       }else{
>         query = url.parse(path).query
>       }
>       let queryGroup = query.split('&');
>       for (var i = 0; i < queryGroup.length; i++){
>         requestPath[queryGroup[i].split('=')[0]] = unescape(queryGroup[i].split('=')[1])
>       }
>       console.log(requestPath)
>     }
> ```
> 
> 建议自己手动封装下，然后就可以用了，自己在需要页面调用就可以。
> 一个中午手写的插件，连续熬了2个通宵研究taro有点体力不支了....orz...

两个通宵 老哥厉害了~
