### ISSUE TITLE
taro怎么配置多个开发环境变量

### ISSUE THREAD

**Issue by PresByter2015** [NervJS/taro#7043]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
开发过程中，需要配置不同的环境如：dev; test; regress; pro. 请问该如何配置。
1. 在 package.json 中，配置环境变量。"test": "cross-env NODE_ENV=test npm run build:weapp -- --watch",
2. 成功得到环境变量 ，process.env.NODE_ENV  =  test ；但是编译失败。生成小程序代码，中的循环列表的 key获取失败；报错如下 `wx:key="$original.id" does not look like a valid key name (did you mean wx:key="id" ?)`.
3. 设置如下环境 变量 在 package.json 中，配置环境变量。"test": "cross-env API_ENV=test npm run build:weapp -- --watch",
4. 获得环境变量值和NODE_ENV一致，同是 development。

### 期望结果
能给一个有效的解决方案。正确的设置环境变量。
根据 https://taro-docs.jd.com/taro/docs/config-detail#env 文档加上一个新的变量，仍然是无效果。

### 实际结果
微信小程序，编译失败。或者环境变量设置失败。

### 环境信息
```
Taro CLI 2.2.9 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.9 => 2.2.9 
      @tarojs/components-qa: 2.2.9 => 2.2.9 
      @tarojs/mini-runner: 2.2.9 => 2.2.9 
      @tarojs/mobx: 2.2.9 => 2.2.9 
      @tarojs/mobx-h5: 2.2.9 => 2.2.9 
      @tarojs/plugin-sass: 2.2.9 => 2.2.9 
      @tarojs/plugin-terser: 2.2.9 => 2.2.9 
      @tarojs/router: 2.2.9 => 2.2.9 
      @tarojs/taro: 2.2.9 => 2.2.9 
      @tarojs/taro-alipay: 2.2.9 => 2.2.9 
      @tarojs/taro-h5: 2.2.9 => 2.2.9 
      @tarojs/taro-qq: 2.2.9 => 2.2.9 
      @tarojs/taro-quickapp: 2.2.9 => 2.2.9 
      @tarojs/taro-swan: 2.2.9 => 2.2.9 
      @tarojs/taro-tt: 2.2.9 => 2.2.9 
      @tarojs/taro-weapp: 2.2.9 => 2.2.9 
      @tarojs/webpack-runner: 2.2.9 => 2.2.9 
      eslint-config-taro: 2.2.9 => 2.2.9 
      eslint-plugin-taro: 2.2.9 => 2.2.9 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.2.9 => 2.2.9 
      stylelint-taro-rn: 2.2.9 => 2.2.9 
```

**Comment by PresByter2015** [comment]
补充一下：
设置如下环境 变量 在 package.json 中，配置环境变量。"test": "cross-env API_ENV=test npm run build:weapp -- --watch",
获得环境变量值是 undefined。

**Comment by martSforever** [comment]
我这边是这么做的，你 可以稍微参考一下：
package.json 中的脚本：
```json
"dev:link:prod": "npm run build:link:prod -- --watch",
"build:link:prod": "npm run fresh && cross-env APP_ENV=link:prod taro build --type weapp"
```
这样执行脚本的时候，在 config/index.js 文件中 通过 process.env.APP_ENV 就可以得到这个环境参数字符串：`link:prod`，然后根据这个字符串，动态require对应的环境配置文件（这个文件得以 module.exports 导出），最后将环境配置对象信息，通过 defineConstants 属性配置，这样在运行时就能够得到你的环境配置信息。如果用的是ts，那么你还得声明全局变量，比如我这里：

```js
const {
    TARO_ENV,
    APP_ENV,
    NODE_ENV
} = process.env

// 默认导出对象中的 defineConstants 属性，具体得看 https://taro-docs.jd.com/taro/docs/config-detail#defineconstants

defineConstants: {
    LINK_ENV: JSON.stringify({
        env: {
            taro: TARO_ENV,
            app: APP_ENV,
            NODE: NODE_ENV,
        },
        ...getEnvData(APP_ENV)
    }),
}
```

声明文件：env.d.ts

```typescript
declare const LINK_ENV: {
    baseURL: string,                    // 后端请求基础路径
    env: {
        node: string,                   // 当前构建模式，development（本地调试）,production（打包构建）
        taro: string,                   // 当前构建平台（weapp、h5）
        app: string,                    // 当前环境变量，link:prod
    },
    project: string,                    // 当前环境变量所属项目
    environment: string,                // 当前环境变量环境，开发、测试还是线上环境
}
```

**Comment by darkfiredarkhalo** [comment]
还不自己写个js脚本,类似这样:  
`prod.js:`  
```
const fs = require('fs');
const path = require('path');

(function() {
    fs.writeFile(
        path.join(path.resolve(__dirname, '..'), '/src/env.json'),
        JSON.stringify({ env: 'production' }),
        'utf8',
        error => {
            if (error) {
                console.log('环境配置写入失败!', error);
                return false;
            }
            console.log('环境配置写入成功!');
        },
    );
})();
```  
有几个环境创建几个js脚本,`package.josn`中这样写:   
```
         ....
        "build:weapp-development": "node ./script/development.js && taro build --type weapp",
        "build:weapp-staging": "node ./script/staging.js && taro build --type weapp",
        "build:weapp-production": "node ./script/production.js && taro build --type weapp",
        "build:weapp": "node ./script/development.js && taro build --type weapp",
       ....
```

脚本会在项目`src`目录下生成`env.json`, 使用的时候判断这个json文件`env`字段的值即可

**Comment by PresByter2015** [comment]
解决了，谢谢

**Comment by javazyw** [comment]
"build:abc": "npm run fresh && cross-env APP_ENV=abc taro build --type abc",
    "dev:abc": "npm run build:abc -- --watch",
 修改了package.json文件和config但是启动报错
npm ERR! missing script: fresh

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2020-09-01T03_04_06_798Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smartproperty-customer-web@1.0.0 build:abc: `npm run fresh && cross-env APP_ENV=abc taro build --type abc "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smartproperty-customer-web@1.0.0 build:abc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by crixusshen** [comment]
我给遇到同样问题的开发者一个最简单的思路：
我们把Taro提供给我们的dev和prod这样来认为，前者为预览模式，脚本不压缩面向平时开发调试；后者为发布模式，脚本做了压缩等处理，面向最后的生产发布。

理解了上面的意思后，但是我们平时还会有很多其他的环境，比如mock（本地）、dev（开发）、test（单元测试）、sit（测试）、uat（准生产）、prod（生产）。假设我们要构建一个mock环境，首先创建一个config/mock.js，由于mock我们就是用来预览模式的，所以将原来的dev.js代码复制过来即可，将内部的NODE_ENV改成mock，具体如下：

```javascript
config/mock.js:
module.exports = {
  env: {
    NODE_ENV: '"mock"',
    // 导入网关基础配置
    ...require('fastman3-dfyjapp-configcenter/es/gateway/mock'),
  },
  ...
}
```

构建一个Node运行时变量APP_ENV，通过 cross-env 插件来实现，具体修改下原来的 npm scripts，具体如下：
```javascript
"scripts": {
    "mock:h5": "cross-env APP_ENV=mock npm run dev:h5",
}
````

最后修改 config/index.js 中脚本调用逻辑，注意前后顺序即可：
```javascript
module.exports = function (merge) {
  // APP_ENV 必须前置在 NODE_ENV 逻辑前
  if (process.env.APP_ENV === 'sit') {
    return merge({}, config, require('./sit'))
  }
  else if (process.env.NODE_ENV === 'development') {
    return merge({}, config, require('./dev'))
  }
  return merge({}, config, require('./prod'))
}
```

**Comment by Samdyddd** [comment]
> 

怎么解决的。目前使用taro 3.4.9

**Comment by SpringHgui** [comment]
> > 
> 
> 怎么解决的。目前使用taro 3.4.9

+1  @
