### ISSUE TITLE
目前是否支持在项目中同时使用Vue和React进行开发？ 如果不支持的话，未来是否有计划支持呢？

### ISSUE THREAD

**Issue by cat-walk** [NervJS/taro#7057]
### 这个特性解决了什么问题？
团队内同时使用了Vue和React，部分代码是用React写的，部分代码是Vue写的，想在一个项目里同时复用这两份不同框架的代码。

### 这个 API 长什么样？
在一个项目中同时使用Vue和React进行开发。

**Comment by Chen-jj** [comment]
不建议这样做，单体积上来说在一个小程序里同时引入 React 和 Vue 会非常大。

实在要复用的组件可以尝试用 [jquery](https://nervjs.github.io/taro/docs/jquery-like) 来写

**Comment by ly75x12** [comment]
@Chen-jj 有同样的诉求，想在一个项目里（taro-react）同时用vue写页面，请问需要怎么配置呢？
