### ISSUE TITLE
组件接收props被处理形式不一

### ISSUE THREAD

**Issue by wfsovereign** [NervJS/taro#706]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
 定义一个组件，传入参数，结构如下，
```javascript
  {
     cursor: 'xxx',
     node: {id: 'xxx', name: 'xxx'}
 }
```
组件首次渲染，数据被拍平，结构如下，

```javascript
  {
     cursor: 'xxx',
     node: {id: 'xxx', name: 'xxx'},
     id: 'xxx',
     name: 'xxx'
 }
```
当数据有更新时，组件再次渲染，传入的数据结构被修改成了如下数据结构，
```javascript
  {
      id: 'xxx',
     name: 'xxx'
 }
```

**期望行为**

按照传入结构，不要做其他改变，特别是不要做不一样的改变

**系统信息**

 - 操作系统: OSX 10.13.6 (17G65)
 - Taro 版本 1.0.0-beta.26
 - Node.js 版本 v10.7.0

**Comment by luckyadam** [comment]
升级到最新的正式版本试试~

**Comment by luckyadam** [comment]
cli 升级了么

**Comment by wfsovereign** [comment]
更新了，更新到@tarojs/cli@1.0.5，结果一样

**Comment by luckyadam** [comment]
可否贴一下相关代码，我们定位一下~

**Comment by wfsovereign** [comment]
感觉和[#732](https://github.com/NervJS/taro/issues/732) 差不多

**Comment by luckyadam** [comment]
收到~ 我们尽快定位修复下

**Comment by wfsovereign** [comment]
目前在Taro 1.1.1版本中尝试没有此问题了
