### ISSUE TITLE
getCurrentInstance().router和Taro.Current.router返回的值都是 null

### ISSUE THREAD

**Issue by apiaoqzh** [NervJS/taro#7065]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: Vue2**

### 复现步骤
import Taro, { getCurrentInstance } from '@tarojs/taro'
...
onLoad () {
  getCurrentInstance() // {app: null, router: null, page: null}
  console.log(Taro.Current) //  {app: null, router: null, page: null}
}

### 期望结果
获取到路由信息

### 实际结果
null

### 环境信息
```
👽 Taro v3.0.3


  Taro CLI 3.0.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.21.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: ^3.0.3 => 3.0.3 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
    npmGlobalPackages:
      typescript: 3.9.3
```

**Comment by apiaoqzh** [comment]
i saw it has been resolved in v3.0.3
thanks~

**Comment by zhaoweihan** [comment]
3.0.7还是有这个问题，请问怎么解决的 谢谢

**Comment by AnselmYuan** [comment]
3.0.10还有此问题 在app.tsx 的 didMount 周期中getCurrentInstance.router和Taro.Current.router都是null

**Comment by Annfyl** [comment]
我这边用的版本是taro3.0.5，编译为支付宝小程序扫码进入使用getCurrentInstance()  也是没能获取正确的params，每次获取到的params都是空对象
