### ISSUE TITLE
[打包后体积过大]使用vue2开发,随便写几行代码,预览的时候就会提示超过2m了

### ISSUE THREAD

**Issue by 963868733** [NervJS/taro#7067]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/QianDuanDianDian/myapp](https://gitee.com/QianDuanDianDian/myapp)
**小程序基础库: 2.11.3**
**使用框架: Vue**

### 复现步骤
ec-canvas放到src下,
新建static目录,存放阿里图标库文件;
封装了请求
除此之外只有2个及其简单的试水页面;
启用es6转es5之前和上传代码压缩混淆之前,是3015kb,启用二者后是2668kb;

### 期望结果
能正常预览

### 实际结果
无法正确预览

### 环境信息
```
👽 Taro v3.0.0-rc.6


  Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 9.10.0 - C:\Program Files\nodejs9.10.0\node.EXE
      npm: 5.6.0 - C:\Program Files\nodejs9.10.0\npm.CMD

```

**Comment by Chen-jj** [comment]
加 `NODE_ENV=production` 可以在 watch 时打出压缩后的包。

**Comment by 963868733** [comment]
> 加 `NODE_ENV=production` 可以在 watch 时打出压缩后的包。

嗯嗯,谢谢大佬;
在config/index.js中加上process.env.NODE_ENV = 'production'的确可以打出打出压缩后的包;
只是热更新会变得很慢;
那我暂时只在需要预览的时候这样操作;
预览结束后马上改回来;
再次感谢大佬;
期待更新;
