### ISSUE TITLE
taro@3.0.3 编译后的 app.js 包含框架代码，瘦身的建议，欢迎讨论呀

### ISSUE THREAD

**Issue by shinken008** [NervJS/taro#7070]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
1.参考官方新建一个项目 https://taro-docs.jd.com/taro/docs/GETTING-STARTED。基于react的项目。
2.执行 `npm run dev:weapp` 。
3.查看编译后的 `app.js` 代码。

### 期望结果
编译后 `app.js` 文件不要框架的源码，保证 `app.js` 的独立性，应该编译到 `vendors.js` 里面。

### 实际结果
编译后的 `app.js` 文件编译进去了 `react` 框架的源码，比如 `/***/ "./node_modules/scheduler/index.js":`。
带来的问题是：
1. `app.js` 不独立，`vendors.js` 确实相关框架代码。
2.  `app.js` 代码冗余。

### 环境信息
```
Taro CLI 3.0.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.3 => 3.0.3 
      @tarojs/mini-runner: 3.0.3 => 3.0.3 
      @tarojs/react: 3.0.3 => 3.0.3 
      @tarojs/runtime: 3.0.3 => 3.0.3 
      @tarojs/taro: ^3.0.3 => 3.0.3 
      @tarojs/webpack-runner: 3.0.3 => 3.0.3 
      babel-preset-taro: 3.0.3 => 3.0.3 
      eslint-config-taro: 3.0.3 => 3.0.3 
      react: ^16.13.1 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.9.5
```

---
### 补充信息
工作中我的项目同时编译成主包，分包和插件，都可以独立技术栈，比如框架和版本的独立性，使用不同分包只需要引入对应的 `vendors.js` 。`Taro@2` 就是这么做的，现在的问题是升级到 `Taro@3` `app.js` 打进了框架的源码，分包和插件上线是不加在自己生成的 `app.js`，对应的 `project.config.json` 也会删除，只需要加载 `vendors.js`, `taro.js` 框架代码。我不清楚官方这么做的原因，或者想问有什么可以改进的措施。谢谢。@Chen-jj 等大佬

**Comment by rottenpen** [comment]
最近我也在研究源码 想把这部分的内容抽离出来....最好就是分包能独立引用自己那部分的 vendors 。不然的话主包的大小是一直降不下来了。

**Comment by Chen-jj** [comment]
@rottenpen 分包抽自己的 vendor 可以配 splitchunks 后使用这个配置 https://nervjs.github.io/taro/docs/config-detail

**Comment by rottenpen** [comment]
@Chen-jj 现在我这边主要的需求是，我这边有一个小程序微前端的方案。
主包部分是原生写的代码。分包部分是 taro 打包后的代码。在 taro 1.x 版本中，由于 page 部分是不依赖 app.js 的。所以在分包 app.js 部分不添加业务逻辑的情况下，这套小程序微前端方案是能正常运行的。但是在 2.x 版本开始，taro 页面是依赖 app.js 引入依赖才能正常使用的。
目前遇到的问题是，不知道 splitChunk 需要抽离哪些部分的 chunk 出来供分包在 page 里引用。

**Comment by shinken008** [comment]
重写splitChunk是可以把React相关代码抽到vendor，还是依赖app.js里面的执行，所以分包执行还是要把app.js require进去。

**Comment by rottenpen** [comment]
@shinken008 而且测试过，把app.js里的一些依赖抽离放在page里面运行，会报页面重复调用的报错

**Comment by elon-hu** [comment]
@rottenpen 你解决了吗？我也遇到同样的需求

**Comment by rottenpen** [comment]
@elon-hu https://github.com/rottenpen/blog/issues/22

**Comment by elon-hu** [comment]
@rottenpen 感觉还是没法解决我遇到的问题，我们的场景是，主包是原生代码，分包是我用taro打包的，并且主包原生代码我没有修改的权限，主包跳转到分包Page的时候，无法显示，因为很多框架逻辑在app.js里

**Comment by rottenpen** [comment]
@elon-hu 如果主包没有修改权限那就没办法了，因为taro 2 3的代码都是依赖 app.js 运行的，你最起码要能修改 app.js。

**Comment by rottenpen** [comment]
@elon-hu 一些建议是 争取能修改主包的 app.js 然后可以考虑像我上面给的方案那样 通过 mixin.js 获取原包 app.js 能力（生命周期，公共函数，公共数据）。至于分包你想用我上面提供的混合方案 还是 submodule 或者其他方法都可以在不修改主包相关代码的情况处理。

**Comment by elon-hu** [comment]
@rottenpen 谢谢你花这么多时间来回复！哎，我太南了！

**Comment by elon-hu** [comment]
@shinken008 老朱最后解决这个问题没有啊

**Comment by elon-hu** [comment]
@shinken008 楼主最后解决这个问题没啊？

**Comment by shinken008** [comment]
@elon-hu 解决了，app.js 框架代码配置 split 抽离。混合开发，插件和分包场景，app.js 自己实现一个，所以的 pages 加载 app.js 就行了。https://github.com/shinken008/blog/issues/5

**Comment by elon-hu** [comment]
@shinken008 我按照这样做会出现：APP-SERVICE-Engine:Please do not register multiple Pages
进入某个页面后报错多次注册page，但实际上只注册了一次
有demo可以让我学习下吗？
我用的taro3.0.14

**Comment by my5201314zwl** [comment]
> @elon-hu 解决了，app.js 框架代码配置 split 抽离。混合开发，插件和分包场景，app.js 自己实现一个，所以的 pages 加载 app.js 就行了。[shinken008/blog#5](https://github.com/shinken008/blog/issues/5)

有demo参考一下app.js瘦身的吗？
