### ISSUE TITLE
新建项目H5 无法运行

### ISSUE THREAD

**Issue by guan919** [NervJS/taro#7073]
### 相关平台
H5

### 复现仓库
[https://taro-docs.jd.com/taro/docs/GETTING-STARTED](https://taro-docs.jd.com/taro/docs/GETTING-STARTED)
**浏览器版本: Google Chrome Version 83**
**使用框架: React**

### 复现步骤
1.taro init demo
2.npm run dev:h5

### 期望结果
H5正常运行

### 实际结果
./src/app.config.js
Module not found: Can't resolve 'C:WorkTaroTaroTestmusicteachersrcpagesindexindex.config.js' in 'C:\Work\Taro\TaroTest\musicteacher\src'

### 环境信息
```
Taro CLI 3.0.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
已修复，下个版本可用

**Comment by guan919** [comment]
3.0.4 更新后问题解决
同时可以引入 taro ui alpha 3 版本

**Comment by chunge66** [comment]
> 已修复，下个版本可用

3.0.16 版本这个问题复现了
