### ISSUE TITLE
文档中有没有代码调试source-map的相关配置说明

### ISSUE THREAD

**Issue by ts-study** [NervJS/taro#7074]
### 这个特性解决了什么问题？
想调试源码，但现在默认生成的dist文件夹下没有source-map的文件，不支持源码调试，如果有的话，请在文档中说明，如果没有也请在文档中说明一下啊！

### 这个 API 长什么样？
可以调试源码

**Comment by without-yy** [comment]
taro >= 3.0

``` config/dev.js
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {},
  mini: {
    enableSourceMap: true,  //默认为true
  },
  h5: {}
}

```

**Comment by ts-study** [comment]
谢谢，已经解决问题
![image](https://user-images.githubusercontent.com/63831612/87639605-11fcbb00-c778-11ea-9a0a-1db4e44b973e.png)

**Comment by ts-study** [comment]
![image](https://user-images.githubusercontent.com/63831612/87639805-5daf6480-c778-11ea-87da-318bb18c42c7.png)

**Comment by ts-study** [comment]
![image](https://user-images.githubusercontent.com/63831612/87640195-f34af400-c778-11ea-98c3-b3f3f81ba1ca.png)
