### ISSUE TITLE
taro-redux, shallowEqual 有bug    null !== null

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#708]
**问题描述**
如题

**复现步骤**

isEqual(null,null) 返回 false

**期望行为**
isEqual(null,null) 返回 true

**补充信息**
isEqual(null,null) 
因为  typeof null => 'object' 
所以进入 shadow equal了
```
if (obj1 === null || obj2 === null) {
        return false;
    }
```

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/pull/710
