### ISSUE TITLE
React组件使用native组件，无法找到该组件

### ISSUE THREAD

**Issue by CallMeXYZ** [NervJS/taro#7094]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/CallMeXYZ/taro-bug-report-using-native-component](https://github.com/CallMeXYZ/taro-bug-report-using-native-component)
**小程序基础库: -**
**使用框架: React**

### 复现步骤
- npm i
- npm run dev:weapp

### 期望结果
test-component能被渲染

### 实际结果
无法找到自定义组件

### 环境信息
```
👽 Taro v3.0.3


  Taro CLI 3.0.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.5 => 3.0.5
      @tarojs/mini-runner: 3.0.5 => 3.0.5
      @tarojs/react: 3.0.5 => 3.0.5
      @tarojs/runtime: 3.0.5 => 3.0.5
      @tarojs/taro: 3.0.5 => 3.0.5
      @tarojs/webpack-runner: 3.0.5 => 3.0.5
      babel-preset-taro: 3.0.5 => 3.0.5
      eslint-config-taro: 3.0.5 => 3.0.5
      react: ^16.10.0 => 16.13.1
```

---
### 补充信息
临时解决：可以用过在页面的config.js申明该native组件，但是不太优雅

**Comment by Chen-jj** [comment]
#5477

**Comment by Chen-jj** [comment]
@CallMeXYZ Taro3 采用模板拼接的方式进行渲染，React 等框架的组件并不对应着一个个小程序的自定义组件，因此组件是没有自己的 config 配置的，issue 5477 里提到的把组件配置 merge 入页面暂时也不予采纳。

所以你可以写在页面配置中，或全局配置中进行声明。
