### ISSUE TITLE
Taro Next 3.0.5无法使用云开发

### ISSUE THREAD

**Issue by lulusir** [NervJS/taro#7097]
### 这个特性解决了什么问题？
Taro Next 3.0.5无法使用云开发，选择了云函数模板，但是没有对应的包
### 这个 API 长什么样？
目前使用3.0.5版本，没法找到对应版本的包；
提示如下：
Couldn't find any versions for "@tarojs/components-qa" that matches "3.0.5"

**Comment by Chen-jj** [comment]
duplicate of #6864
