### ISSUE TITLE
全局注册微信小程序自定义组件不可以使用，但是页面配置中注册自定义组件可以使用

### ISSUE THREAD

**Issue by martSforever** [NervJS/taro#7098]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/martsforever-issues/taro-issues-catch/tree/global-register-wxcomponent/](https://gitee.com/martsforever-issues/taro-issues-catch/tree/global-register-wxcomponent/)

**请注意，分支是：global-register-wxcomponent**

**小程序基础库: 2.12.0**
**使用框架: Vue2**

### 复现步骤

1. 安装依赖；
2. 启动本地调试微信小程序服务：npm run dev:weapp；
3. 使用微信开发者工具打开dist文件夹，打开的首页就是示例页面；

现在写了一个简单的自定义组件：/components-wx/custom-wx-component/custom-wx-component；目前是在 app.config.ts 中注册这个组件的：

```typescript
export default {
  pages: [
    'pages/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  },
  usingComponents: {
    "custom-wx-component": "/components-wx/custom-wx-component/custom-wx-component",
  }
}
```

这样全局注册的时候，组件没有渲染出来，控制台输出警告：

```
./base.wxml
 Template `tmpl_1_custom-wx-component` not found.
  67 | 
  68 | <template name="tmpl_1_container" data="{{i: i}}">
> 69 |   <template is="{{'tmpl_1_'   i.nn}}" data="{{i: i}}" />
     |                ^
  70 | </template>
  71 | 
  72 | <template name="tmpl_2_view">
```

如果把这个注册自定义组件的声明写在页面的配置文件 `index.config.ts` 中，就可以正常使用；

### 期望结果
在 app.config.ts 中全局注册的自定义小程序组件能够正常使用

### 实际结果
在 app.cofnig.ts 中注册的全局组件无效；使用自定义组件的时候，提示 base.wxml 中找不到对应的template；（换成在页面配置文件中注册的自定义组件是有效的，也不会有警告）

### 环境信息
```
  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - D:\0_install\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - D:\0_install\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@martSforever 全局注册的原生组件没有被 copy 到 dist，先在页面里配置吧，我们抽空改改

**Comment by martSforever** [comment]
我的示例仓库里面写了，已经把原生组件copy到目标文件夹了:
```js
  copy: {
    patterns: [
      {from: 'src/components-wx/', to: `dist/components-wx`},
    ],
    options: {
    }
  },
```

**Comment by martSforever** [comment]
应该不是没有把原生组件copy到dist的原因

**Comment by luckyadam** [comment]
3.0.8 可用

**Comment by Mr-ZhaoRui** [comment]
> 3.0.8 可用

预计什么时候发布呢？
