### ISSUE TITLE
Taro2.0.3 直接升级 next版本报错

### ISSUE THREAD

**Issue by jzhenbiao** [NervJS/taro#7102]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: nerv**

### 复现步骤
2.0.3版本的代码直接升级到3.0报错了

### 期望结果
提供一个完整的2.0.3

### 实际结果
升级完之后各种报错

### 环境信息
```
Taro CLI 3.0.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@jzhenbiao 请按升级指南操作 https://nervjs.github.io/taro/docs/migration

**Comment by jzhenbiao** [comment]
按照这个升级单个项目之后还是报错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 下午4:06
收件人:&nbsp;"NervJS/taro"<taro@noreply.github.com&gt;;
抄送:&nbsp;"wer"<1351947018@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NervJS/taro] Taro2.0.3 直接升级 next版本报错 (#7102)





 
@jzhenbiao 请按升级指南操作 https://nervjs.github.io/taro/docs/migration
