### ISSUE TITLE
Current.router.params 重新渲染时为空

### ISSUE THREAD

**Issue by TechQuery** [NervJS/taro#7109]
## 相关平台

H5

**浏览器版本: Chrome 84**
**使用框架: React**

## 复现步骤

```JavaScript
import React, { Component } from 'react';
import { Current } from '@tarojs/taro';
import { View } from '@tarojs/components';

export default class TestPage extends Component {
    state = {
        count: 0
    };

    render() {
        const { count } = this.state,
            { id } = Current.router?.params || {};

        return <View onClick={() => this.setState({ count:   count })}>
            {id} {count}
        </button>;
    }
}
```
用户点击 `<View />` 更新 `state` 后引发重绘。

## 期望结果

从路由传过来的 `id` 总是可以拿到

## 实际结果

`render()` 再次调用时 `id === undefined`

## 环境信息
```
� Taro v3.0.5

  Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by wan-zhiyuan** [comment]
getCurrentInstance().router

**Comment by TechQuery** [comment]
> getCurrentInstance().router

这个 API 在 3.0 官方文档没有……

**Comment by wan-zhiyuan** [comment]
> > getCurrentInstance().router
> 
> 这个 API 在 3.0 官方文档没有……

- 
v3.0.0文档-迁移指南
 #路由
在旧版本中可以通过 this.$router 访问当前组件/页面路由的详情。在 Taro Next 对应的 API 是在 @tarojs/taro 中的 getCurrentInstance().router，两者的属性一模一样。

**Comment by TechQuery** [comment]
我没用过早期版本，若只在迁移指南中有、搜索框搜不到，对于新用户来说就是“不存在”……

**Comment by 349989153** [comment]
好像是生命周期不对吧

**Comment by 349989153** [comment]
Current.router?.params一直都是undefined，肯定拿不到了

**Comment by Chen-jj** [comment]
3.0.7 复现不了：

```js
import Taro, { useReady, Current, getCurrentInstance } from '@tarojs/taro'

export default class TestPage extends Component {
  state = {
      count: 0
  };

  render() {
      const { count } = this.state,
          { id } = Current.router?.params || {};

      return <View onClick={() => this.setState({ count:   count + 1 })}>
          {id} {count}
      </View>
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/90246957-3677b000-de68-11ea-8ea7-9e73b8ad19c5.png)

文档：[路由传参](https://taro-docs.jd.com/taro/docs/next/router#%E8%B7%AF%E7%94%B1%E4%BC%A0%E5%8F%82)、迁移指南都有提到 `getCurrentInstance().router.params`。你 demo 使用 `Current.router.params` 也是正确的，`getCurrentInstance()` 拿到的也是 `Current`，只不过它能让开发者更倾向于把执行结果保存起来而不是直接使用 `Current`。

所以可以升级到最新版本再试试，还有问题则提供完整 demo。
