### ISSUE TITLE
Taro3.x - 1、APP实例化前，无法使用Taro对象；2、Taro.getApp()获取不到App里constructor中新增的属性吗？

### ISSUE THREAD

**Issue by persist-xyz** [NervJS/taro#7110]
### 相关平台
支付宝小程序

**小程序基础库: -**
**使用框架: React**

### 复现步骤
import Taro from "@tarojs/taro";

const env = Taro.getEnv(); // ReferenceError: Taro is not defined

if (env === "WEAPP") {
   //
  }else{
  //
}

```
const store = configStore();

class App extends Component {
  constructor() {
    super(...arguments);
    
    this.sensors = {
      track: () => {},
    };
  }

  componentDidMount() {}

  componentDidShow() {}

  componentDidHide() {}

  componentDidCatchError() {}

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return <Provider store={store}>{this.props.children}</Provider>;
  }
}

export default App;
```

// 在页面中执行

Taro.getApp().sensors.track() // 报错

### 期望结果
希望可以和2.x版本一致 可以正常获取constructor中新增属性

### 实际结果
error

### 环境信息
```
 Taro v3.0.0


  Taro CLI 3.0.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0 => 3.0.0
      @tarojs/mini-runner: 3.0.0 => 3.0.0
      @tarojs/react: 3.0.0 => 3.0.0
      @tarojs/runtime: 3.0.0 => 3.0.0
      @tarojs/taro: 3.0.0 => 3.0.0
      @tarojs/webpack-runner: 3.0.0 => 3.0.0
      babel-preset-taro: 3.0.0 => 3.0.0
      eslint-config-taro: 3.0.0 => 3.0.0
      react: ^16.10.0 => 16.13.1
    npmGlobalPackages:
      typescript: 3.5.3
```

**Comment by Chen-jj** [comment]
@persist-xyz 

1. 使用 `process.env.TARO_ENV` 做判断，代替 `Taro.getEnv()`
2. `Taro.getApp()` 等于小程序原生的 `getApp()`，获取到的是小程序的 app 实例，Taro 3 中开发者写的 App 入口组件不等于小程序 app 实例，只是一个 React 组件。因此你可以通过 `Current.app` 获取 App 入口组件。

```js
import { Current } from '@tarojs/taro'

Current.app.sensors.track()
```

**Comment by yechunxi** [comment]
> @persist-xyz
> 
> 1. 使用 `process.env.TARO_ENV` 做判断，代替 `Taro.getEnv()`
> 2. `Taro.getApp()` 等于小程序原生的 `getApp()`，获取到的是小程序的 app 实例，Taro 3 中开发者写的 App 入口组件不等于小程序 app 实例，只是一个 React 组件。因此你可以通过 `Current.app` 获取 App 入口组件。
> 
> ```js
> import { Current } from '@tarojs/taro'
> 
> Current.app.sensors.track()
> ```

 Current.app 返回的值只是app.config中定义的内容与，也还是拿不到新增的属性

**Comment by persist-xyz** [comment]
> > @persist-xyz
> > 
> > 1. 使用 `process.env.TARO_ENV` 做判断，代替 `Taro.getEnv()`
> > 2. `Taro.getApp()` 等于小程序原生的 `getApp()`，获取到的是小程序的 app 实例，Taro 3 中开发者写的 App 入口组件不等于小程序 app 实例，只是一个 React 组件。因此你可以通过 `Current.app` 获取 App 入口组件。
> > 
> > ```js
> > import { Current } from '@tarojs/taro'
> > 
> > Current.app.sensors.track()
> > ```
> 
> > Current.app 返回的值只是app.config中定义的内容，也还是拿不到新增的属性， 和Taro.getApp()中返回的config是一样的

是的，有什么方法可以解决吗？暂时不升级3.x了，等再稳定一段时间的 😂

**Comment by failedUser** [comment]
同样遇到了问题，想再app.js里面定义一些全局属性挂在app上，但是发现做不到

**Comment by JRliu** [comment]
直接在Current.app上添加属性就好了~

**Comment by xsq007** [comment]
同样遇到了问题，在App上注入了变量，后面使用Taro.getApp()得不到了。

**Comment by FJHou** [comment]
小程序转换为taro代码后，页面中的Taro.getApp()都获取不到App定义的属性了，这难道不是个bug吗。如果改造的话成本有点高吧

**Comment by xsq007** [comment]
这个问题阻碍我们从2.x升级到 3.x，请问有workaround吗？

**Comment by xsq007** [comment]
@Chen-jj  这个问题不应该关闭把。

**Comment by Chen-jj** [comment]
@xsq007 可以使用 `taroGlobalObject` 去实现

```js
// app.js
class App extends Component {
  taroGlobalData = {
    x () {
      console.log('i m x')
    }
  }
}
```

```js
// index.js
class Index extends Component {
  componentDidMount () {
    const app = Taro.getApp()
    app.x()
  }
}
```

**Comment by zcmain** [comment]
@Chen-jj `// app.js
class App extends Component {
  taroGlobalData = {
    x () {
      console.log('i m x')
    }
  }
}
// index.js
class Index extends Component {
  componentDidMount () {
    const app = Taro.getApp()
    app.x()
  }
}`
还是提示：
react-reconciler.production.min.js:106 TypeError: app.x is not a function
    at Home.componentDidMount (home.tsx:33)
    at jg (react-reconciler.production.min.js:141)
    at define.push../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (scheduler.production.min.js:7)
    at hc (react-reconciler.production.min.js:18)
    at ag (react-reconciler.production.min.js:137)
    at Of (react-reconciler.production.min.js:121)
    at react-reconciler.production.min.js:19
    at define.push../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority (scheduler.production.min.js:7)
    at hc (react-reconciler.production.min.js:18)
    at kc (react-reconciler.production.min.js:19)

**Comment by zcmain** [comment]
@Chen-jj 可以使用 taroGlobalObject 去实现
```jsx
// app.js
class App extends Component {
  taroGlobalData = {
    x () {
      console.log('i m x')
    }
  }
}
```
```jsx
// index.js
class Index extends Component {
  componentDidMount () {
    const app = Taro.getApp()
    app.x()
  }
}
```
使用上述代码提示:`react-reconciler.production.min.js:106 TypeError: app.x is not a function`

**Comment by progerchai** [comment]
3.x 版本，为什么我用了getApp 直接 getApp is not a function了呢？

```javascript

import Taro, { Current } from '@tarojs/taro';

class App extends Component {
 componentDidMount() {
    const app = Taro.getApp();
    console.log('app', app);
  }
}
```
报错：
![image](https://user-images.githubusercontent.com/31467572/121787693-2d777c80-cbfa-11eb-8010-8518f10dadd9.png)

**Comment by OneKissAndOneShot** [comment]
> 

在Functional Component中怎么使用

**Comment by OneKissAndOneShot** [comment]
> @Chen-jj 可以使用 taroGlobalObject 去实现
> 
> ```js
> // app.js
> class App extends Component {
>   taroGlobalData = {
>     x () {
>       console.log('i m x')
>     }
>   }
> }
> ```
> 
> ```js
> // index.js
> class Index extends Component {
>   componentDidMount () {
>     const app = Taro.getApp()
>     app.x()
>   }
> }
> ```
> 
> 使用上述代码提示:`react-reconciler.production.min.js:106 TypeError: app.x is not a function`

在Functional Component中怎么使用

**Comment by guoenyue** [comment]
taroGlobalData 模式在支付宝/mpaas里没有内存问题吗，我们的应用跑起来在mpaas端/alipay上会卡死，微信则无，注释掉taroGlobalData的读取（下方代码读取处）就正常

// app.js
class App extends Component {
  taroGlobalData = {
    x () {
      console.log('i m x')
    }
  }
}
// index.js
class Index extends Component {
  componentDidMount () {
   // globalData 读取处，注释掉即无内存溢出问题 ，支付宝/mpaas环境  微信下正常
    const app = Taro.getApp()
    app.x()
  }
}

**Comment by Sano1217** [comment]
@persist-xyz  我这边用的taro3.5.7，我这样做是正常的
![image](https://user-images.githubusercontent.com/103491082/204511369-f318fd7d-172a-4357-bd9a-58edcf69b253.png)
![image](https://user-images.githubusercontent.com/103491082/204511634-8e677b9a-2fab-4705-9d7e-e078ebe48a39.png)

**Comment by lanxuexing** [comment]
> > @Chen-jj 可以使用 taroGlobalObject 去实现
> > ```js
> > // app.js
> > class App extends Component {
> >   taroGlobalData = {
> >     x () {
> >       console.log('i m x')
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > // index.js
> > class Index extends Component {
> >   componentDidMount () {
> >     const app = Taro.getApp()
> >     app.x()
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用上述代码提示:`react-reconciler.production.min.js:106 TypeError: app.x is not a function`
> 
> 在Functional Component中怎么使用

@OneKissAndOneShot 

`taroGlobalObject`的 Function Component 实现

```js
// 1.设置，在 app.js 里
const App = () => {
  // 设置全局变量 "x" 或者 "y" 函数
  Taro.getApp().x = 1;
  Taro.getApp().y = () => {
    console.log('i m y')
  }
}
```


```js
// 2.使用，在任意 xxx.js 里
const Index = () => {
  useEffect(() => {
    //  获取并使用全局变量 "x" 或者 调用函数 "y"
    Taro.getApp().x
    Taro.getApp().y()
    
    // 或者这样
    const app = Taro.getApp()
    app.x
    app.y()
  })
}
```
