### ISSUE TITLE
支付宝小程序不能prerender

### ISSUE THREAD

**Issue by fred8617** [NervJS/taro#7111]
### 相关平台
支付宝小程序

**小程序基础库: 最新**
**使用框架: React**

### 复现步骤
启动

### 期望结果
正常

### 实际结果
报错

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/87895689-a321a980-ca78-11ea-8d5b-b33813d82794.png)

**Comment by Chen-jj** [comment]
提供一下 demo 吧

**Comment by fred8617** [comment]
[https://github.com/fred8617/taro-issue.git](https://github.com/fred8617/taro-issue.git) @Chen-jj

**Comment by fred8617** [comment]
只要设置预渲染就会报错

**Comment by mishengqiang** [comment]
👽 Taro v3.0.15


  Taro CLI 3.0.15 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.11.0/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.15 => 3.0.15 
      @tarojs/components: 3.0.15 => 3.0.15 
      @tarojs/mini-runner: 3.0.15 => 3.0.15 
      @tarojs/react: 3.0.15 => 3.0.15 
      @tarojs/runtime: 3.0.15 => 3.0.15 
      @tarojs/taro: 3.0.15 => 3.0.15 
      @tarojs/webpack-runner: 3.0.15 => 3.0.15 
      babel-preset-taro: 3.0.15 => 3.0.15 
      eslint-config-taro: 3.0.15 => 3.0.15 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 


百度小程序预渲染出错，但是微信小程序就可以成功。
![image](https://user-images.githubusercontent.com/9413032/98763502-16c73800-2415-11eb-9957-0a3636a9d246.png)
