### ISSUE TITLE
_createSelectorQuery is not defined

### ISSUE THREAD

**Issue by datafu** [NervJS/taro#7114]
参考demo写的 手风琴 ，在 taro 3.0.5下会报错
Uncaught (in promise) ReferenceError: _createSelectorQuery is not defined
    at eval (index.umd.js?ac0a:1379)
    at new Promise (<anonymous>)
    at delayQuerySelector (index.umd.js?ac0a:1378)
    at AtAccordion.toggleWithAnimation (index.umd.js?ac0a:4940)
    at AtAccordion.UNSAFE_componentWillReceiveProps (index.umd.js?ac0a:4964)
    at callComponentWillReceiveProps (react-dom.development.js?61bb:12976)
    at updateClassInstance (react-dom.development.js?61bb:13178)
    at updateClassComponent (react-dom.development.js?61bb:17107)
    at beginWork (react-dom.development.js?61bb:18620)
    at beginWork$1 (react-dom.development.js?61bb:23179)

代码如下：
import  Taro from '@tarojs/taro';
import React, { Component } from 'react';
import  './index.less';
import { AtAccordion, AtList, AtListItem } from 'taro-ui'
export default class TaroAccordion extends Component {
  constructor () {
    super(...arguments)
    this.state = {
      open: false,
    }
  }
  handleClick (value) {
    this.setState({
      open: value
    })
  }
  render () {
      return (
            <AtAccordion
              open={this.state.open}
              onClick={this.handleClick.bind(this)}
              title='标题一'
            >
              <AtList hasBorder={false}>
                <AtListItem
                  title='标题文字'
                  arrow='right'
                  thumb='https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png'
                />
                <AtListItem
                  title='标题文字'
                  note='描述信息'
                  arrow='right'
                  thumb='http://img10.360buyimg.com/jdphoto/s72x72_jfs/t5872/209/5240187906/2872/8fa98cd/595c3b2aN4155b931.png'
                />
                <AtListItem
                  title='标题文字'
                  note='描述信息'
                  extraText='详细信息'
                  arrow='right'
                  thumb='http://img12.360buyimg.com/jdphoto/s72x72_jfs/t10660/330/203667368/1672/801735d7/59c85643N31e68303.png'
                />
              </AtList>
            </AtAccordion>
          )
  }
}

**Comment by Chen-jj** [comment]
@datafu 到 taro ui 仓库提问一下吧
