### ISSUE TITLE
 Taro.createSelectorQuery().select('#myCanvas') 无法获取到 canvas dom

### ISSUE THREAD

**Issue by MiaLeung01** [NervJS/taro#7116]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/MiaLeung01/TaroIssue/blob/master/index.tsx](https://github.com/MiaLeung01/TaroIssue/blob/master/index.tsx)
**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
//js
const canvas = Taro.createSelectorQuery().select('#myCanvas')
    .fields({node: true, size: true}, function(res){
      console.log('res', res)
    }).exec()
    console.log('canvas', canvas)

// render
<Canvas style='width: 300px; height: 300px;' className='myCanvas' canvasId='myCanvas' id='myCanvas'></Canvas>

### 期望结果
能获取到Canvas 真实dom

### 实际结果
undefined

### 环境信息
```
�👽 Taro v3.0.5


  Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 11.11.0 - C:\
      Yarn: 1.22.4 - C:
      npm: 6.7.0 - C:
```

**Comment by MiaLeung01** [comment]
> 用Taro.createCanvasContext('myCanvas', this.$scope)试试
> 应该能拿到上下文对象

我需要拿Canvas实例去做设置，context 是能拿到，但是我要拿 canvas

**Comment by CarlXu94** [comment]
import Taro,{useScope} from '@tarojs/taro'
const scope=useScope()
const canvas = Taro.createSelectorQuery().in(scope).select('#myCanvas')

**Comment by zetianul** [comment]
解决了吗，想用微信小程序新的api必须拿到canvas实例，我死活拿不到

**Comment by keepresolve** [comment]
使用useScope hooks   
![image](https://user-images.githubusercontent.com/29271171/89966281-60bb4900-dc81-11ea-9685-7a61a7d8c0da.png)

**Comment by nvsky** [comment]
> 使用useScope hooks
> ![image](https://user-images.githubusercontent.com/29271171/89966281-60bb4900-dc81-11ea-9685-7a61a7d8c0da.png)

useScope已经被删除不能用了

**Comment by nvsky** [comment]
![image](https://user-images.githubusercontent.com/8436965/90713901-fdf92b80-e2d8-11ea-8f17-9ab5eb3bc984.png)
遇到同样问题，class组件内拿不到this.$scope

**Comment by meibin08** [comment]
useScope hooks
有3.0.8版本，压根没有导出 
![image](https://user-images.githubusercontent.com/18324563/91831207-5c79be80-ec76-11ea-8e6f-fb4cc9e13bcc.png)

**Comment by cl1107** [comment]
在 useEffect 里调用 Taro.nextTick  然后在 nextTick中去获取  @CarlXu94 @meibin08 @nvsky @zetianul @keepresolve 
``` js
useEffect(() => {
    Taro.nextTick(() => {
      const query = wx.createSelectorQuery();
      query
        .select('#myCanvas')
        .fields({ node: true, size: true })
        .exec((res) => {
          console.log('LddConnector -> res', res);
          const canvas = res[0].node;
        });
    });
  }, []);
```

**Comment by missmimia** [comment]
> 在 useEffect 里调用 Taro.nextTick 然后在 nextTick中去获取 @CarlXu94 @meibin08 @nvsky @zetianul @keepresolve
> 
> ```js
> useEffect(() => {
>     Taro.nextTick(() => {
>       const query = wx.createSelectorQuery();
>       query
>         .select('#myCanvas')
>         .fields({ node: true, size: true })
>         .exec((res) => {
>           console.log('LddConnector -> res', res);
>           const canvas = res[0].node;
>         });
>     });
>   }, []);
> ```

res 打印出来也是 [null] 啊.....

**Comment by keepresolve** [comment]
如果你没有使用3 的版本 可以是用useScope   hooks          需要调用一下 useScope() == this.$scope

**Comment by Chen-jj** [comment]
@MiaLeung01 https://nervjs.github.io/taro/docs/next/react/#onready

获取小程序渲染层的节点要在 `onReady` 生命周期，等同于 `useReady` hooks。

```js
export default function Screen () {
  useReady(() => {
    const canvas = Taro.createSelectorQuery().select('#myCanvas')
    .fields({node: true, size: true}, function(res){
      console.log('res', res)
    }).exec()
    console.log('canvas', canvas)
  })
  return (
    <View>
      <Canvas style='width: 300px; height: 300px;' className='myCanvas' canvasId='myCanvas' id='myCanvas'></Canvas>
    </View>
  )
}
```

![image](https://user-images.githubusercontent.com/11807297/92719215-6ba6ed80-f395-11ea-926f-885f4b45bc47.png)

**Comment by footya** [comment]
Taro2.2.14依然获取不到canvas，返回为[null]

**Comment by jianhao** [comment]
同问，如何获取到canvas dom

**Comment by starlikerain** [comment]
找到了办法，是因为 Taro 运行的时候好像没有绑定到当前的作用域，可以改用当前暴露的 $scope 下的 createSelectorQuery 函数获取到 dom
```js
this.$scope.createSelectorQuery()
```

**Comment by carrykingdow** [comment]
也可以使用 in(this.$scope) 来绑定。
比如 
`Taro.createSelectorQuery().in(this.$scope).select(`#fuck`).boundingClientRect().exec(function(rect){
      console.log(rect);
    })`

**Comment by yerphon** [comment]
拿不到node属性

**Comment by EricWong1994** [comment]
@yerphon 太难了，最后你怎么解决的，如何拿到node属性的，我需要这个，项目代码太老了，还是taro2，百度小程序，谁来救救我

**Comment by TurnerXi** [comment]
目前发现问题：
首次进入页面时能获取到canvas，再次进入页面时id被复写了，原因不明。因此获取不到
![image](https://user-images.githubusercontent.com/25336287/124714900-ed739300-df34-11eb-8bc8-7e7cd1db0169.png)
![image](https://user-images.githubusercontent.com/25336287/124714915-f06e8380-df34-11eb-847c-85b69fd9064b.png)
解决方式：
组件加载完成时强制更新canvas组件
![image](https://user-images.githubusercontent.com/25336287/124715060-1f84f500-df35-11eb-8f35-1dfab2219443.png)
![image](https://user-images.githubusercontent.com/25336287/124715084-27449980-df35-11eb-9a92-5f10f2e85f5c.png)

**Comment by innocces** [comment]
指定type即可拿到实例~   

前提是在`useReady`或者是`nextTick`之后。

```tsx
<Canvas type="2d" className="demo" canvasId="canvas" />
```

![image](https://user-images.githubusercontent.com/38065966/125804708-45452159-f1c2-43b3-b6f5-c5902396ff2b.png)

**Comment by rayallen001** [comment]
> 指定type即可拿到实例~
> 
> 前提是在`useReady`或者是`nextTick`之后。
> 
> ```tsx
> <Canvas type="2d" className="demo" canvasId="canvas" />
> ```
> 
> ![image](https://user-images.githubusercontent.com/38065966/125804708-45452159-f1c2-43b3-b6f5-c5902396ff2b.png)

试了，确实加上 type="2d" 就可以了。另外，我用的 id 属性代替 canvasId。这样才能被 createSelectorQuery 的 id 选择器选中

**Comment by innocces** [comment]
> > 指定type即可拿到实例~
> > 前提是在`useReady`或者是`nextTick`之后。
> > ```tsx
> > <Canvas type="2d" className="demo" canvasId="canvas" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/38065966/125804708-45452159-f1c2-43b3-b6f5-c5902396ff2b.png)
> 
> 试了，确实加上 type="2d" 就可以了。另外，我用的 id 属性代替 canvasId。这样才能被 createSelectorQuery 的 id 选择器选中

_(:з」∠)_ 有帮到就okkkkk~
_(:з」∠)_  打个广告，有兴趣可以了解一下[taro-hooks](https://github.com/innocces/taro-hooks)

**Comment by flyfox11** [comment]
> 也可以使用 in(this.$scope) 来绑定。 比如 `Taro.createSelectorQuery().in(this.$scope).select(`#fuck`).boundingClientRect().exec(function(rect){ console.log(rect); })`

解决了我的问题

**Comment by dailiangzhu** [comment]
开发版确实存在这个问题 我目前的解决方案是发到体验版上可以正常看到效果

**Comment by HappyJeannie** [comment]
刚刚踩完坑。可以获取，主要注意以下几点：
1. 必须使用 Taro 提供的 Canvas 才可以生效
2. Canvas 中必须包含类型 type="2d"
3. 在 pageReady/useReady 中调用，且使用定时器，就算 pageReady 后，canvas 也不一定 ready，否则无法获得 canvas node 节点
