### ISSUE TITLE
vue2中Taro.options.html.transformElement无法调用

### ISSUE THREAD

**Issue by 634323580** [NervJS/taro#7119]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: Vue2**

### 复现步骤
Taro.options.html.transformElement
Taro.options.html.transformText
这两个方法在vue2中声明了无法调用

### 期望结果
和文档一致
https://taro-docs.jd.com/taro/docs/html#transformtext

### 实际结果
无法调用

### 环境信息
```
👽 Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.7.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
请提供一下使用的 demo
