### ISSUE TITLE
Taro@3.0.5 编译成头条小程序，使用最新的1.70.X的基础库报错

### ISSUE THREAD

**Issue by Naico** [NervJS/taro#7121]
![image](https://user-images.githubusercontent.com/2639245/88021668-8660a100-cb60-11ea-89b9-5b9e0b386886.png)

**Comment by Naico** [comment]
![image](https://user-images.githubusercontent.com/2639245/88021782-adb76e00-cb60-11ea-9988-b126e9411d24.png)

**Comment by Chen-jj** [comment]
duplicate of #6929
