### ISSUE TITLE
video提供缓冲中和缓冲完毕事件

### ISSUE THREAD

**Issue by vee2046** [NervJS/taro#7122]
### 这个特性解决了什么问题？
自定义播放控制器时没条件处理缓冲提示逻辑，如果有这两个事件
在视频加载时界面给予提示，提升用户体验

### 这个 API 长什么样？
`onLoading`   缓冲中

`onLoadedContinuePlay`   缓冲后播放

**Comment by ZakaryCode** [comment]
[参考文档](http://taro-docs.jd.com/taro/docs/next/apis/media/background-audio/BackgroundAudioManager#onwaiting)
