### ISSUE TITLE
taro初始化小程序插件报错 plugin.apply is not a function

### ISSUE THREAD

**Issue by vee2046** [NervJS/taro#7124]
### 相关平台
微信小程序

### 复现仓库
[http://a.com](http://a.com)
**小程序基础库: 1.2.3**
**使用框架: React**

### 复现步骤
注意：我的版本是2.1.5

按照官方步骤操作

- taro init xxx

 ? 是否需要使用 TypeScript ？ No

? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass

? 请选择模板 wxplugin

提示安装依赖失败，手动yarn install

- yarn install

开始安装，最后一个插件安装失败：error Couldn't find any versions for "@tarojs/plugin-terser" that matches "2.1.5"

估计问题就是出在这里

执行到taro build --plugin weapp时必然过不去，报错plugin.apply is not a function

### 期望结果
正常执行过去吧，能不能单独安装

### 实际结果
报错

### 环境信息
```
 Taro CLI 2.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Users\ww\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by vee2046** [comment]
把Taro和相关组件都升到了2.2.11，build没问题了，但是提示plugin.json找不着，可是源码里是有的，缺什么东西吗
![image](https://user-images.githubusercontent.com/4362360/88039010-a18bda80-cb79-11ea-9344-7397d37c5cea.png)

**Comment by vee2046** [comment]
补图

![image](https://user-images.githubusercontent.com/4362360/88042443-840d3f80-cb7e-11ea-8381-babf55311f74.png)

**Comment by EyeShield29** [comment]
https://github.com/NervJS/taro/issues/6730  可以参考下 2.2.11应该也存在相同问题

**Comment by vee2046** [comment]
> #6730 可以参考下 2.2.11应该也存在相同问题

![image](https://user-images.githubusercontent.com/4362360/88073221-871d2580-cba8-11ea-9b6d-7911ca6cf361.png)

改完后又报这个错了

![image](https://user-images.githubusercontent.com/4362360/88073095-6228b280-cba8-11ea-84a3-c1fc15fd0bbb.png)

**Comment by Slngle** [comment]
遇到同样的问题 无法解决

**Comment by vee2046** [comment]
> 遇到同样的问题 无法解决

  @@只能自力更生，修改一下config/index，taro提供了copy组件，把需要拷贝的文件夹或文件加进去就可以了
@Slngle 
这个工具真的好坑，没开发完的样子

**Comment by luckyadam** [comment]
使用 2.2.11 创建插件项目，
