### ISSUE TITLE
微信、支付宝小程序中ref存储的元素节点无法get到offsetWidth属性

### ISSUE THREAD

**Issue by 15997111963** [NervJS/taro#7126]
### 相关平台
微信、支付宝小程序

### 复现仓库
暂无法提供源码 还未提交 开发阶段
**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
尝试使用了class组件createRef方式存储获取的节点
也尝试使用了hook组件useRef方式存储获取的节点都无法获取到offsetWitdth属性 
在h5则是正常 可以获取到

### 期望结果
拿到自身元素宽度

### 实际结果
均为undefined

### 环境信息
```
👽 Taro v3.0.5

Babel could not write cache to file: /Users/sinker/Desktop/taro/node_modules/.cache/@babel/register/.babel.7.9.0.development.json 
due to a permission issue. Cache is disabled.

  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      eslint-config-taro: 3.0.2 => 3.0.2 
      react: ^16.10.0 => 16.13.1 
```
class组件
<img width="552" alt="class组件1" src="https://user-images.githubusercontent.com/40592585/88045433-16164780-cb81-11ea-8442-204ce72a06f7.png">
<img width="564" alt="class组件2" src="https://user-images.githubusercontent.com/40592585/88045835-ba988980-cb81-11ea-951c-41449fe07bd4.png">

<img width="418" alt="class组件3" src="https://user-images.githubusercontent.com/40592585/88045448-1f071900-cb81-11ea-896a-ebfe79def498.png">

函数组件
<img width="658" alt="hook组件1" src="https://user-images.githubusercontent.com/40592585/88045640-69889580-cb81-11ea-90db-a5e8efb66cdb.png">
<img width="447" alt="hook组件2" src="https://user-images.githubusercontent.com/40592585/88045665-75745780-cb81-11ea-9b61-8a2c1b133dae.png">
<img width="733" alt="hook组件3" src="https://user-images.githubusercontent.com/40592585/88045680-7b6a3880-cb81-11ea-8932-5cc10c622925.png">

文档中也未提到相关资料可能是字段名不同 望告知 谢谢

**Comment by Chen-jj** [comment]
@15997111963 https://nervjs.github.io/taro/docs/migration#ref--dom 用小程序 API 取

**Comment by 15997111963** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/40592585/88125795-9f219300-cc02-11ea-951c-4a2f93db29db.png">



使用以上方式暂且拿到的是scrollWidth 里面虽然有对应的某些字段 但还是不够准确 就只能暂时这样用了

**Comment by 15997111963** [comment]
这些都还只支持微信的 h5需要做特殊处理 支付宝小程序不支持这种用法

**Comment by 15997111963** [comment]
这些都还只支持微信的 h5需要做特殊处理 支付宝小程序不支持这种用法

**Comment by 15997111963** [comment]
@Chen-jj 这些都还只支持微信的 h5需要做特殊处理 支付宝小程序不支持 该怎么办

**Comment by 15997111963** [comment]
<img width="828" alt="result" src="https://user-images.githubusercontent.com/40592585/88142458-1ae20680-cc28-11ea-8e5b-f50508509c5b.png">


目前是这样解决的  支付宝需要用他的my
Taro的这个回调在支付宝走不进去
在h5下 my这个global变量也是没有的 只能try catch自己捕获了

**Comment by Chen-jj** [comment]
在小程序中 Taro.createSelectorQuery 相当于调用 my.createSelectorQuery 喔，只是做了 promise 化，你可以断点进去看看

**Comment by 15997111963** [comment]
@Chen-jj 所拿到的类都是同一个 但是在支付宝中没有exec的这个方法 就无法进到回调里 还是说方法名不同吗？
不然我也不至于同样的代码写两遍

**Comment by 15997111963** [comment]
还挺奇怪的 有时候可进去回调 有时进不去
