### ISSUE TITLE
支持在vue3中使用jsx写法。

### ISSUE THREAD

**Issue by 297cwrun** [NervJS/taro#7136]
### 这个特性解决了什么问题？
由于vue3对于jsx更好的支持，未来jsx在vue生态会有更大的用武之地。而当前t@babel/plugin-transform-react-jsx会阻止开发者在setup周期里直接返回jsx。这与vue3的官方文档是相悖的，容易产生使用上的困惑。

### 这个 API 长什么样？
允许在setup中使用如return () =>  (<text>AAA</text>);的做法。

**Comment by Chen-jj** [comment]
已支持
