### ISSUE TITLE
VirtualList滚动后子组件的onClick不执行

### ISSUE THREAD

**Issue by peica** [NervJS/taro#7140]
### 相关平台
H5

### 复现仓库
[https://github.com/NervJS/taro/issues/7137](https://github.com/NervJS/taro/issues/7137)
**浏览器版本: Chrome 83.0.4103.116**
**使用框架: React**

### 复现步骤
const onClick = () => { console.log("onClick");}
const Row = React.memo(({ index, style, data }) => {
return (
<View className={index % 2 ? 'ListItemOdd' : 'ListItemEven'} style={style} onClick={onClick}>
Row {index}

);
})

function buildData (offset = 0) {
return Array(100).fill(0).map((_, i) => i offset);
}

export default class Index extends Component {
state = {
data: buildData(0),
}

loading = false

listReachBottom() {
Taro.showLoading()
// 如果 loading 与视图相关，那它就应该放在 this.state 里
// 我们这里使用的是一个同步的 API 调用 loading，所以不需要
this.loading = true
setTimeout(() => {
const { data } = this.state
this.setState({
data: data.concat(buildData(data.length))
}, () => {
this.loading = false;
Taro.hideLoading()
})
}, 1000)
}

render() {
const { data } = this.state
const dataLen = data.length
const itemSize = 100
return (
<VirtualList
className='List'
height={500}
itemData={data}
itemCount={dataLen}
itemSize={itemSize}
width='100%'
onScroll={({ scrollDirection, scrollOffset }) => {
if (
// 避免重复加载数据
!this.loading &&
// 只有往前滚动我们才触发
scrollDirection === 'forward' &&
// 5 = (列表高度 / 单项列表高度)
// 100 = 滚动提前加载量，可根据样式情况调整
scrollOffset > ((dataLen - 5) * itemSize 100)
) {
this.listReachBottom()
}
}}
>
{Row}

);
}
}

### 期望结果
onClick被调用

### 实际结果
滚动后onClick不会被调用

### 环境信息
```
👽 Taro v3.0.5


  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.21.0 - /usr/local/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.5 => 3.0.5
      @tarojs/components: 3.0.5 => 3.0.5
      @tarojs/mini-runner: 3.0.5 => 3.0.5
      @tarojs/react: 3.0.5 => 3.0.5
      @tarojs/runtime: 3.0.5 => 3.0.5
      @tarojs/taro: 3.0.5 => 3.0.5
      @tarojs/webpack-runner: 3.0.5 => 3.0.5
      babel-preset-taro: 3.0.5 => 3.0.5
      eslint-config-taro: 3.0.5 => 3.0.5
      react: ^16.10.0 => 16.13.1
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

---
### 补充信息
问题是出在，createListComponent.js 里面对 pointerEvents: isScrolling ? 'none' : undefined,的这个操作。pointerEvents为undefined时不会更新到dom里面，改成pointerEvents: isScrolling ? 'none' : 'auto'  就可以了。

**Comment by vscing** [comment]
3.0.3正常

**Comment by ZhengXingchi** [comment]
在@tarojs/cli@3.0.9中VirtualList滚动后子组件的onClick不执行，确定是否修复 @Chen-jj
