### ISSUE TITLE
Taro.createSelectorQuery获取高度偶尔为null

### ISSUE THREAD

**Issue by vscing** [NervJS/taro#7146]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
useReady(() => {
    const query = Taro.createSelectorQuery()
    query.select('#header').boundingClientRect(res => {
      //获取导航栏高度
      let { height } = res
     console.log(height)
    }).exec()
  })

### 期望结果
每次打开都能获取到高度

### 实际结果
打开之后偶尔高度为null

### 环境信息
```
� Taro v3.0.2


  Taro CLI 3.0.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.18.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@vscing Taro API 只是对原生 API 做了 promise 化，你可以使用 wx. 再试试

**Comment by Chen-jj** [comment]
复现不了，还有问题的话提供一下可复现 demo 吧。
