### ISSUE TITLE
taro等react语法框架tabs组件循环 警告key值问题

### ISSUE THREAD

**Issue by xiao0502** [NervJS/taro#715]
**问题描述**
集成vant-weapp小程序UI框架的时候，key值警告问题。
在采用此UI框架的tabs、tab组件编写可滚动的标签栏页时候，tab组件已经写了key={index},，不会编译成wx:key，导致警告问题。虽然不会影响正常运行，但是还是希望解决。

**复现步骤**
[复现问题的步骤]

1. components copyvant-weapp dist代码
2.pages/index/index.js  config配置 usingComponents
3. render引用组件

[或者可以直接贴源代码，能贴文字就不要截图]

```
                <van-tabs active={this.state.current} onclick={this.clickTabs}>
                    {
                        this.state.typeList.map((item, index) => {
                            return (
                                <van-tab key={index} title={item.title}>{item.title}</van-tab>
                            )
                        })
                    }
                </van-tabs>
```

**期望行为**
希望解决key警告

**报错信息**

https://user-images.githubusercontent.com/20298200/46125357-4fb6e980-c25b-11e8-9b77-6ada65b6bff6.png

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v8.9.4]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by yuche** [comment]
声明过 `usingComponent` 的 `key` 不会编译变成 `wx:key`，因为他们可能也需要一个叫 `key` 的参数。

由于你已经使用了第三方组就没法多端编译了，那直接写 `wx:key` 就好。

**Comment by xiao0502** [comment]
@yuche 直接写wx:key也不行，第三方组件van-tab不需要key的参数，已经和van-tabs生命了父子关系。

这是pages/index/index.js中所使用
```
<van-tabs active={this.state.current} onclick={this.clickTabs}>
    {
        this.state.typeList.map((item, index) => {
            return (
                <van-tab wx:key={index} title={item.title}>{item.title}</van-tab>
            )
        })
    }
</van-tabs>
```

这是编译后的

```
<van-tabs active="{{current}}" __triggerObserer="{{ _triggerObserer }}"
bindclick="clickTabs" __fn_onclick="{{true}}">
    <van-tab __triggerObserer="{{ _triggerObserer }}" title="{{item.title}}"
    wx:for="{{typeList}}" wx:for-item="item" wx:for-index="index">{{item.title}}</van-tab>
</van-tabs>
```

**Comment by yuche** [comment]
问题在于 Taro 不会知道你使用的这个第三方组件有没有 key 这个参数，只能统一不处理第三方组件的 key 了。
否则 https://github.com/NervJS/taro/issues/521 这种情况就完全没法使用了。

直接写 wx:key 也的确是没法用，因为冒号这个语法在 JSX 里属于使用命名空间语法，由于使用频率太少，所以在近期不打算对其进行支持了。

**Comment by luckyadam** [comment]
暂时在 <van-tab> 外包一层 block 解决吧，把 key 加到 block 上

**Comment by Ariskywi** [comment]
可以定义一个别名支持编译吗？
譬如在第三方组件中如果定义了taroProps属性,  那么taroProps中定义的所有属性可被编译。
那就可以这样 <van-tab taroProps={key: 'value'} /> 来使用了

**Comment by yuche** [comment]
https://github.com/NervJS/taro/commit/c95c8b27868cb7d7aa7c2ff10617876679b38086 之后可以使用属性 `taroKey`，相当于 alias 了原来的 key。
