### ISSUE TITLE
AtIndexes组件 希望可以支持自定义部分

### ISSUE THREAD

**Issue by Murphycx94** [NervJS/taro#7151]
### 这个特性解决了什么问题？
我希望点击了某条内容后，能加上一个选中的效果
但是目前只支持传入list，不能给某条内容添加选中的状态

### 这个 API 长什么样？
```javascript
list = [
  {
    key: 'A',
    title: 'A',
    items: [
      { name: '浙江‘, isActive: true }
    ]
  }
]
```
然后浙江这条元素上可以多增加一个item-active的classname

当然如果支持传入reactelement，就更好了

**Comment by Chen-jj** [comment]
@Murphycx94 请到 Taro UI 的仓库下提 Feature Request 吧。
