### ISSUE TITLE
swiper的circular有问题，无法关闭循环

### ISSUE THREAD

**Issue by i-smile** [NervJS/taro#7152]
> unified with wechat swiper circular fix #6277 (#6326) ([4b6cf4e](https://github.com/NervJS/taro/commit/4b6cf4ec0f6ce824a771f14212ca927b4fcca3d9))
> 是这个提交的问题吧

该调整是为了与小程序保持一致，circular 参数决定的并非是是否能够循环，而是循环发生时，实际的动画样式

_Originally posted by @ZakaryCode in https://github.com/NervJS/taro/issues/6965#issuecomment-655875830_

"circular 参数决定的并非是是否能够循环，而是循环发生时，实际的动画样式"。这个有点敷衍了吧，你自己那小程序的swiper来试试看，别自己想当然

**Comment by Chen-jj** [comment]
@i-smile 请按规范创建 issue。

**Comment by taozidada** [comment]
H5无法关闭啊，微信是好的
