### ISSUE TITLE
ScrollView 不能设置lowerThreshold(距底部距离)，否则无法正确监听onScrollToLower(到底)事件

### ISSUE THREAD

**Issue by wb9436** [NervJS/taro#716]
### ScrollView 配置lowerThreshold导致到底事件onScrollToLower监听异常

![image](https://user-images.githubusercontent.com/39255168/46126748-06699880-c261-11e8-912e-e34570d863fc.png)

**Comment by jinjinjin0731** [comment]
好的

**Comment by 6061960** [comment]
我发现我无论怎么设置，都无法触发`onScrollToLower`，大家有同样问题吗

**Comment by jinjinjin0731** [comment]
抱歉，忘记回复了。这个在 beta 版本中修复了
