### ISSUE TITLE
[Taro 2.2.11]switchTab 跳转到对应tabBar 页面为空

### ISSUE THREAD

**Issue by mengtianren** [NervJS/taro#7164]
### 相关平台
H5

**浏览器版本: Chrome **
**使用框架: React**

### 复现步骤
login登录之后 switchTab 跳转到 首页 页面为空 需要刷新

### 期望结果
从非tabbar页面switchTab 跳转到tabbar页面可以显示页面

### 实际结果
h5模式下路由发生变化,但是页面为空

### 环境信息
```
aro CLI 2.2.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.0 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
# app.js config配置项
  config = {
    pages: [
      "pages/login",
      "pages/home/index",
      ...
    ],
    window: { 
     ...
    },
    tabBar: {
      list: [
        {
          pagePath: "pages/home/index",
          text: "首页",
          iconPath: "./static/image/tabBar/home.png",
          selectedIconPath: "./static/image/tabBar/home_1.png"
        },
        ...
      ],
      color: "#333",
      selectedColor: "#06BF89",
      backgroundColor: "#fdfdfd",
      borderStyle: "black"
    }
  };

#  login.js
 Taro.switchTab({
      url: "/pages/home/index"
})

**Comment by taozidada** [comment]
我也这样，怎么解决，就H5有

**Comment by luckyadam** [comment]
@mengtianren @taozidada 能否提供一个简单的 demo 看下～

**Comment by mengtianren** [comment]
> @mengtianren @taozidada能否提供一个简单的demo看下〜
https://github.com/mengtianren/taro2.2.11-switchTab.git

**Comment by yuuk** [comment]
同，路由变化，页面display还是none

**Comment by ZakaryCode** [comment]
和 #6878 问题重复，在 #7344 中修复该问题

**Comment by shenghanqin** [comment]
@ZakaryCode 在什么版本发布呢？

**Comment by Chen-jj** [comment]
下一个 patch 版本发布
