### ISSUE TITLE
npm run build:rn 报错  Unterminated character class

### ISSUE THREAD

**Issue by gryns** [NervJS/taro#7171]
### 相关平台
React Native

### 复现仓库
https://github.com/gryns/taro-music

**使用框架: React**

### 复现步骤
执行npm run build:rn 出现报错信息

### 期望结果
运行成功

### 实际结果
Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class

(node:8012) UnhandledPromiseRejectionWarning: Error: Command failed: node ./node_modules/react-native/local-cli/cli.js bundle --entry-file D:\git-project\taro-music\rn_temp/index.js --bundle-output ./rn_bundle/index.bundle --assets-dest ./rn_bundle --dev false
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at buildBundle (C:\Program Files\nodejs\node_modules\@tarojs\cli\dist\rn\index.js:85:21)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\@tarojs\cli\dist\rn\index.js:43:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\nodejs\node_modules\@tarojs\cli\dist\rn\index.js:4:58)
(node:8012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
Taro CLI 2.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
node: 12.18.2
npm: 6.14.6
java: 1.8.0_251
taro: 2.2.10
react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by Pines-Cheng** [comment]
1. 检查 react-native 依赖是否装好，版本是否正确。

2. 检查 taro-music\rn_temp/index.js 是否存在。

**Comment by gryns** [comment]
> 1. 检查 react-native 依赖是否装好，版本是否正确。
> 2. 检查 taro-music\rn_temp/index.js 是否存在。

我按照[https://www.jianshu.com/p/cebd55929850](点击这里)，方法修改后，有出现另外一个错误
`Scanning folders for symlinks in E:\git-project\taro-music\node_modules\_react-native@0.55.4@react-native\node_modules (1221ms)
Scanning folders for symlinks in E:\git-project\taro-music\node_modules\_react-native@0.55.4@react-native\node_modules (637ms)
Loading dependency graph, done.
Loading dependency graph...
Expected path `E:\git-project\taro-music\rn_temp\index.js` to be relative to one of the project roots

(node:4136) UnhandledPromiseRejectionWarning: Error: Command failed: node ./node_modules/react-native/local-cli/cli.js bundle --entry-file E:\git-project\taro-music\rn_temp/index.js --bundle-output ./rn_bundle/index.bundle --assets-dest ./rn_bundle --dev
false
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at buildBundle (C:\Users\gry\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\rn\index.js:85:21)
    at Object.<anonymous> (C:\Users\gry\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\rn\index.js:43:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\gry\AppData\Roaming\npm\node_modules\@tarojs\cli\dist\rn\index.js:4:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.`
![image](https://user-images.githubusercontent.com/29560074/89895958-37fa6b80-dc0f-11ea-800f-3b0b1c36c2e1.png)

**Comment by Pines-Cheng** [comment]
应该是RN 依赖安装有问题。
