### ISSUE TITLE
Vue 框架中 App created 会被调用两次

### ISSUE THREAD

**Issue by zcfan** [NervJS/taro#7179]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/zcfan/reproduce-created-bug](https://github.com/zcfan/reproduce-created-bug)
**小程序基础库: 2.12.0**
**使用框架: Vue**

### 复现步骤
直接运行重现链接的 Taro 项目，会看到两行“这行会被打印两次“，但在 created 中只有一行 console.log。

### 期望结果
只打印一行文本

### 实际结果
打印了两行

### 环境信息
```
  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.5 => 3.0.5
      @tarojs/mini-runner: 3.0.5 => 3.0.5
      @tarojs/runtime: 3.0.5 => 3.0.5
      @tarojs/taro: 3.0.5 => 3.0.5
      @tarojs/webpack-runner: 3.0.5 => 3.0.5
      babel-preset-taro: 3.0.5 => 3.0.5
      eslint-config-taro: 3.0.5 => 3.0.5
```

---
### 补充信息
刚创建的 vuex 模版项目，添加 App created 即可复现，无其他操作。

**Comment by zcfan** [comment]
创建 issue 的表单好像有点问题，框架选了 Vue 2 生成出来还是 React。

**Comment by Chen-jj** [comment]
@zcfan 之后这样写吧，开发者写暴露一个 option 即可，不需要调用 `new Vue({})`，3.0.7 修复。

```js
// app.js
const App = {
  // ...
}
```

**Comment by wingsico** [comment]
1. beforeCreated也调用两次
2. 路由变化时，App的updated和beforeUpdate也会调用（不知道这是feat还是bug）

**Comment by tenbamboo** [comment]
@Chen-jj  这个具体需要怎么修改，我们这边先临时修改我们自己本地的app.js

**Comment by Chen-jj** [comment]
3.1 修复，存在不兼容性改动。

用户编写入口组件时要这样修改：

```js
// app.js

// 3.0
const App = new Vue({
  // ...
})

// 3.1
const App = {
  // ...
}
```
