### ISSUE TITLE
与微信原生代码混合使用，没有copy原生代码到dist目录

### ISSUE THREAD

**Issue by HuMoran** [NervJS/taro#718]
taro版本：1.0.3

taro和微信原生代码混合使用时，如果微信的原生代码引用了其他wxml或wxss文件，编译的时候，没有把相关文件拷贝到dist对应目录。

**Comment by jamieYou** [comment]
参考这个例子：
https://github.com/NervJS/taro-sample-weapp/blob/master/config/index.js#L30

估计还没有做自动识别的功能呢

**Comment by HuMoran** [comment]
> 参考这个例子：
> https://github.com/NervJS/taro-sample-weapp/blob/master/config/index.js#L30
> 
> 估计还没有做自动识别的功能呢

我现在就是copy过去的，主要是taro官方文档“[Taro 代码与微信小程序代码混写](https://nervjs.github.io/taro/docs/wx-hybrid.html)”那章节，也没个提醒或者注意事项，搞的我花了不少时间找原因……

**Comment by luckyadam** [comment]
抱歉，我先在文档里加个提示，现在提示得有点深。。。
https://github.com/NervJS/taro-sample-weapp/blob/master/src/pages/wxParse/wxParse.js#L6
