### ISSUE TITLE
使用vant组件 绑定click事件无效

### ISSUE THREAD

**Issue by Smi1e96** [NervJS/taro#7182]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Smi1e96/Taro3](https://github.com/Smi1e96/Taro3)
**小程序基础库: 2.10.3**
**使用框架: React**

### 复现步骤
![image](https://user-images.githubusercontent.com/31199247/88611647-0be1d500-d0bc-11ea-9a63-32473812dff1.png)

下载【[源码](https://github.com/Smi1e96/Taro3)】运行即可复现
与[@4055](https://github.com/NervJS/taro/issues/4055) 不同 
### 期望结果
点击按钮可以触发事件

### 实际结果
无法绑定click事件

### 环境信息
```
  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.2 => 3.0.2 
      @tarojs/mini-runner: 3.0.2 => 3.0.2 
      @tarojs/react: 3.0.2 => 3.0.2 
      @tarojs/runtime: 3.0.2 => 3.0.2 
      @tarojs/taro: 3.0.2 => 3.0.2 
      @tarojs/webpack-runner: 3.0.2 => 3.0.2 
      babel-preset-taro: 3.0.2 => 3.0.2 
      react: ^16.10.0 => 16.13.1 
```

**Comment by Chen-jj** [comment]
@Smi1e96 你的 demo 运行会报错，我另外用 vant button 试可以

![image](https://user-images.githubusercontent.com/11807297/88903358-25367d00-d286-11ea-970c-6c455824d53c.png)

**Comment by hemengke1997** [comment]
我也遇到这个问题了 taro包都是最新的 @Chen-jj 
 "@babel/runtime": "^7.7.7",
  "@tarojs/components": "3.0.6",
  "@tarojs/react": "3.0.6",
  "@tarojs/redux": "^2.2.10",
  "@tarojs/runtime": "3.0.6",
  "@tarojs/taro": "3.0.6"
