### ISSUE TITLE
getComputedStyle is not defined

### ISSUE THREAD

**Issue by yuwanlin** [NervJS/taro#7185]
### 相关平台
微信小程序

**小程序基础库: 任意**
**使用框架: React**

## 背景
在taro3中，可以使用jquery - like API.
## 步骤
1. $('ele').position()报错
2. 报错内容：getComputedStyle is not defined

### 期望结果
$('ele').position() 可以获取元素的相对位置信息

### 实际结果
报错

### 环境信息
```
 Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
查看源码 node_modules\@tarojs\extend\src\jquery\zepto.js，由于position函数中使用到了 getComputedStyle  API，而小程序不存在这个api，导致报错。在该文件中发现，有多个地方使用到了 getComputedStyle   API。而文档 https://nervjs.github.io/taro/docs/jquery-like#position 中没有注明。

**Comment by John60676** [comment]
使用 css 方法去获取一个不存在与内联的样式同样会引起报错
```
getComputedStyle is not a function
```
