### ISSUE TITLE
编译h5版本报错

### ISSUE THREAD

**Issue by Zertu** [NervJS/taro#72]
"dependencies": {
    "babel/core": "^7.0.0-beta.49",
    "tarojs/components": "^0.0.45",
    "tarojs/router": "^0.0.45",
    "tarojs/taro": "^0.0.45",
    "tarojs/taro-h5": "^0.0.45",
    "tarojs/taro-weapp": "^0.0.45",
    "nervjs": "^1.3.0"
  },
  "devDependencies": {
    "tarojs/cli": "^0.0.45",
    "tarojs/plugin-babel": "^0.0.45",
    "tarojs/plugin-csso": "^0.0.45",
    "tarojs/plugin-sass": "^0.0.45",
    "tarojs/plugin-uglifyjs": "^0.0.45",
    "tarojs/webpack-runner": "^0.0.45",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-taro": "^0.0.45",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-taro": "^0.0.45"
  }
 ModuleBuildError: Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

**Comment by luckyadam** [comment]
为啥你要安装 `@babel/core`

**Comment by Zertu** [comment]
@luckyadam init完我执行打包h5项目就报错ModuleBuildError: Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of , it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "" or "babel-core" to see what is calling Babel.
然后我尝试装了bable-core还是有问题。。

**Comment by luckyadam** [comment]
不用装babel-core，应该是依赖没有完全装好～可以手动用cnpm重装下

**Comment by xuxinya** [comment]
你好，我这边也遇到了类似的问题：
为了统计测试的代码覆盖率，在config/dex.js中加了babel配置babel-plugin-istanbul：

 ```
plugins: {
    babel: {
      sourceMap: true,
      presets: [
        ['env', {
          modules: false
        }],
        '@babel/preset-env'
      ],
      plugins: [
        'transform-decorators-legacy',
        'transform-class-properties',
        'transform-object-rest-spread',
        'istanbul'
      ]
    }
  },
```
package.json

"devDependencies": {
		"@babel/core": "^7.5.4",
		"@babel/preset-env": "^7.5.4",
		"@cypress/code-coverage": "^1.9.0",
		"@tarojs/plugin-babel": "1.3.4",
		"@tarojs/plugin-csso": "1.3.4",
		"@tarojs/plugin-sass": "1.3.4",
		"@tarojs/plugin-uglifyjs": "1.3.4",
		"@tarojs/webpack-runner": "1.3.4",
		"@types/react": "^16.4.6",
		"@types/webpack-env": "^1.13.6",
		"@typescript-eslint/parser": "^1.6.0",
		"allure-commandline": "^2.9.0",
		"babel-eslint": "^8.2.3",
		"babel-plugin-istanbul": "^5.2.0",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-plugin-transform-jsx-stylesheet": "^0.6.5",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-preset-env": "^1.6.1",
		"cross-env": "^5.2.0",
...

执行npm run dev:h5后报错：
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".`

想请教可能是什么原因呢？
