### ISSUE TITLE
H5中，页面后退不会触发componentDidShow

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#720]
**问题描述**
在更新了最新版时，发现h5中页面后退时，componentDidShow没有触发。

**期望行为**
在以前的版本中，是会触发的。个人觉得这个还是有必要在后退时也触发的，因为在另一个页面还是可能改变了一些原有页面的状态，需要在显示的时候有个刷新。

**系统信息**

 - Taro 版本 [e.g. 1.0.3]

**Comment by zhenfan0753** [comment]
我也有这个问题!
麻烦看看

**Comment by luckyadam** [comment]
@Littly

**Comment by Littly** [comment]
没有复现，有没有一个可以复现的项目？

**Comment by xingBri** [comment]
> 没有复现，有没有一个可以复现的项目？

暂时没有，因为当时升级发现有这个问题，没有更新上去，但后退时的确没有调用componentDidShow
