### ISSUE TITLE
h5 tabbar没法适配iphonex底部按钮

### ISSUE THREAD

**Issue by yuuk** [NervJS/taro#7203]
### 这个特性解决了什么问题？
嵌入h5页面到微信webview中时，tabbar会被iphonex的虚拟按钮遮挡一部分

### 这个 API 长什么样？
希望tabbar可提供api控制距离bottom的距离

**Comment by shenghanqin** [comment]
@yuuk 感觉适配起来还是挺麻烦的。有的人还不想适配iPhone x呢。这里给你一篇文章作为参考。

https://www.xiaoxili.com/hi-face/docs/tencent-cloud/tencent-minapp-to-web.html

**Comment by ZakaryCode** [comment]
fix in #11310
