### ISSUE TITLE
ScrollView设置scrollTop没效果

### ISSUE THREAD

**Issue by wb9436** [NervJS/taro#721]
在使用ScrollView做滑动分页加载数据时，scrollTop总会从0开始，即使设置scrollTop也没效果

![image](https://user-images.githubusercontent.com/39255168/46137841-05466480-c27d-11e8-870b-475ffc64bc93.png)

![image](https://user-images.githubusercontent.com/39255168/46137866-155e4400-c27d-11e8-943c-637e4997e716.png)

**Comment by WangBiaoxuan** [comment]
![image](https://user-images.githubusercontent.com/16679686/46209604-dc979b00-c360-11e8-874d-006165379017.png)

**Comment by jinjinjin0731** [comment]
明白了，我这边复现一下

**Comment by huangguozhen** [comment]
@jinjinjin0731 ScrollView Bug解决了吗？

**Comment by jinjinjin0731** [comment]
@huangguozhen  升级到最新版本试一下，这个忘记关了，已经修复

**Comment by jswxwxf** [comment]
为什么我设置 scrollTop 还是没作用啊？这个修好了吗？

**Comment by jswxwxf** [comment]
我是 1.1.9 版的

**Comment by jswxwxf** [comment]
```
      <ScrollView scrollY={scrollable} scrollTop='500' className='order-list' style={`height: ${height}`}>
        {_.isEmpty(orders) ?
          <View className='app-empty'>
            <Image src='https://static.fashionipo.com/conuni/no-order.png' />
            <Text>您还没有订单哦</Text>
          </View> :
          orders.map(order => (<OrderCard key={order.orderId} order={order} />))
        }
      </ScrollView>
```

**Comment by jswxwxf** [comment]
scrollIntoView 也没有作用……

**Comment by jswxwxf** [comment]
这是我的代码
```
render() {
  let { orders, height } = this.state;
  if (!height) return null;
  return (
    <ScrollView scrollY scrollIntoView='order-1543483461928a778' className='order-list' style={`height: ${height}`}>
      {_.isEmpty(orders) ?
        <View className='app-empty'>
          <Image src='https://static.fashionipo.com/conuni/no-order.png' />
          <Text>您还没有订单哦</Text>
        </View> :
        orders.map(order => (<View key={order.orderId} id={`order-${order.orderId}`}>
          <OrderCard order={order} />
        </View>))
      }
    </ScrollView>
  )
}
```

**Comment by Young1993** [comment]
scrollTop={100} 没用

**Comment by AwesomeDevin** [comment]
version1.2.4     置顶没有效果~  wx小程序
` 
setScrollTop(top){
    this.setState({
      scrollTop: 0
    })
  }

<ScrollView className={`elements-page__scroll`} scroll-top={this.state.scrollTop}`>
</ScrollView>

**Comment by Amywang1205** [comment]
这个问题修复了吗？

**Comment by Amywang1205** [comment]
这个问题修复了吗？1.2.4版本。

**Comment by AwesomeDevin** [comment]
> 这个问题修复了吗？1.2.4版本。

貌似还没，我现在是用scroll-into-view实现，希望开发人员有空跟进下设置scrolltop的问题，

**Comment by jinjinjin0731** [comment]
@Amywang1205  @AwesomeDevin  问题已经修复很久了。如果你们还有什么新的问题 ，你们可以提一下issue ，把复现的相关的逻辑贴一下。
至于 @AwesomeDevin  你的问题，你可以先看一下文档 [属性名称始终使用驼峰命名法](https://nervjs.github.io/taro/docs/spec-for-taro.html#%E5%B1%9E%E6%80%A7%E4%B9%A6%E5%86%99)

**Comment by AwesomeDevin** [comment]
> @Amywang1205 @AwesomeDevin 问题已经修复很久了。如果你们还有什么新的问题 ，你们可以提一下issue ，把复现的相关的逻辑贴一下。
> 至于 @AwesomeDevin 你的问题，你可以先看一下文档 [属性名称始终使用驼峰命名法](https://nervjs.github.io/taro/docs/spec-for-taro.html#%E5%B1%9E%E6%80%A7%E4%B9%A6%E5%86%99)

你好，之前使用驼峰法命名也是不行的，刚刚再次尝试了，还是不行,发现需要在滚动时给scrolltopvalue赋值，才能setscrolltop成功,但是滚动时赋值scrolltopvalue,如果激活了scrollWithAnimation属性，会造成滚动时页面卡顿,体验很不好，如果不激活scrollWithAnimation,可以正常使用

```
  scroll(...data){
    const scrollTop = data[1].detail.scrollTop
    this.setState({        // 少了这一句无法置顶成功   并且激活scrollWithAnimation属性后，页面滚动会卡顿
      scrollTopValue:scrollTop
    })
    this.props.onScroll(scrollTop)
    // App.setScrollTop = ()=>{
    //   this.props.onScroll(0)
    //   this.props.setIntoView('scrollintoview')
    //   setTimeout(()=>{
    //     this.props.setIntoView('')
    //   },400)
    // }
    App.setScrollTop = ()=>{
      this.setState({
        scrollTopValue:0
      })
    }
    // console.log(scrollTop)
  }

<ScrollView scrollWithAnimation="true" scrollTop={this.state.scrollTopValue}  className={`elements-page__scroll`} scrollIntoView={this.props.root.scrollntoView}  scrollWithAnimation="false" upperThreshold="-100" ontouchend={this.touchend.bind(this)} ontouchmove={this.move.bind(this)} ontouchstart={this.touchstart.bind(this)}  scrollY enableBackToTop onscroll={this.scroll.bind(this)} onscrolltolower={this.scrollDown.bind(this)}    style={`padding-top:${this.props.pageConfig.fixed?0:this.state.height}px;${this.props.pageConfig.contentBgColor? 'background:'+this.props.pageConfig.contentBgColor+';':''}`} >
        
 </ScrollView>
```

**Comment by jinjinjin0731** [comment]
@Amywang1205 新开一个issue 吧，问题，复现代码 ，H5 or 小程序

**Comment by catXiaoXiao** [comment]
哈哈哈哈哈，我知道大家为什么设置scrollTop无效了，ScrollView源码如下：
![image](https://user-images.githubusercontent.com/26037975/53478437-c594da80-3ab1-11e9-85df-886246bbebf1.png)
如果一开始设置的scrollTop是0，点击某个可以改变scrollTop为1,新值旧值不一致才会触发他的向上滚动函数呀23333333

**Comment by lanxkk** [comment]
我用随机数解决了这个问题

**Comment by tuoxie15** [comment]
这么坑啊...还需要自己写随机值..还有这个height高度还要自己去算里面内容..也是醉了

**Comment by dkvirus** [comment]
> 我用随机数解决了这个问题

随机数可以解决，就感觉代码很不优雅。

**Comment by florida0723** [comment]
scrollTop === 0 ? -1 : 0
