### ISSUE TITLE
RN无法运行，真机模拟器都不行

### ISSUE THREAD

**Issue by EasyTuan** [NervJS/taro#722]
**问题描述**
一、ios模拟器运行第一次装上Expo 客户端，报错卸载后，再也无法自动装上Expo 客户端。

二、真机（iphone7 ios12）安装Expo 客户端后扫码，遇到如下报错
![image](https://user-images.githubusercontent.com/27880857/46138512-a386fa00-c27e-11e8-9b49-dd99b83cf14e.png)

**系统信息**

 - 操作系统: [e.g. macOS Mojave 10.14]
 - Taro 版本 [e.g. v.1.0.4]
 - Node.js 版本 [e.g. v8.11.3]

**补充信息**
为官方redux模版，并未做代码修改
命令行编译无报错
手机和mac在同一局域网下
mac端口未被占用
mac未开代理

**Comment by wakaryry** [comment]
所以到底有没有已经完成的利用Taro来编译RN上线APP的。
我打算近期就用这个来写小程序和IOS/Android。
不知道是不是可以直接上手写。

**Comment by luckyadam** [comment]
@wakaryry 你尝试一下咯

**Comment by wakaryry** [comment]
@luckyadam 可以。

**Comment by LinFeng1987** [comment]
@wakaryry 大佬尝试后感觉如何？

**Comment by wakaryry** [comment]
@LinFeng1987 还没有用。我用回了原生的开发。用这个写小程序，原生写IOS/Android。

**Comment by LinFeng1987** [comment]
@wakaryry 还是比较推荐原生，这个目前还没看见很多编译IOS/Android线上项目的实例，也不知道有哪些坑

**Comment by Pines-Cheng** [comment]
@EasyTuan 你那边问题还存在吗？我找不到重现的方法。

**Comment by EasyTuan** [comment]
@Pines-Cheng 我这边这个问题还是存在的，RN还是一开始就报红，无法运行

**Comment by LinFeng1987** [comment]
@EasyTuan 这是没连上服务器吧

**Comment by EasyTuan** [comment]
@LinFeng1987 你指的是哪边的服务器

**Comment by LinFeng1987** [comment]
@EasyTuan 你的node服务

**Comment by EasyTuan** [comment]
@LinFeng1987 
手机和mac在同一局域网下
mac端口未被占用
mac未开代理
同时模拟器和真机都无法连上，但我实在想到不到还有其他方法可以测到端口是否已经连接成功

**Comment by LinFeng1987** [comment]
@EasyTuan 你在自己的开发电脑上面搭一个http服务看看能不能正常访问，或者看看能不能访问rn的debug地址

**Comment by Pines-Cheng** [comment]
@EasyTuan 那你直接使用 [create-react-native-app](https://github.com/react-community/create-react-native-app) 初始化一个项目，能跑起来吗？

**Comment by EasyTuan** [comment]
@Pines-Cheng 尝试了create-react-native-app，RN项目跑起来了，并且尝试用expo-cli跑taro项目，还是不行，还是红色的报错截图

**Comment by LinFeng1987** [comment]
@EasyTuan 有点打脑壳

**Comment by Pines-Cheng** [comment]
https://github.com/expo/expo/issues/616
