### ISSUE TITLE
页面使用redux ，onShareAppMessage不生效

### ISSUE THREAD

**Issue by HelloAndyZhang** [NervJS/taro#7228]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/HelloAndyZhang/taroV3](https://github.com/HelloAndyZhang/taroV3)
**小程序基础库: 2.12.0**
**使用框架: React**

### 期望结果
设置完onShareAppMessage信息，可进行分享。

### 实际结果
设置完onShareAppMessage信息，微信提示当前页面未设置分享。

### 环境信息
```
👽 Taro v3.0.6


  Taro CLI 3.0.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.0 - E:\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - E:\nodejs\npm.CMD
```

**Comment by vdfor** [comment]
page 的config里面 将 enableShareAppMessage设置为 true 试下

**Comment by HelloAndyZhang** [comment]
> 页面的配置里面将enableShareAppMessage设置为true试下
#6825   是这个issue 吧  了解了,  感谢指导！

**Comment by HelloAndyZhang** [comment]
// class component
class Index extends Component {
  static enableShareAppMessage = true

  onShareAppMessage () {}
}

// functional component
function Index {
  useShareAppMessage(() => {})
}
Index.enableShareAppMessage = true


#6825

**Comment by vdfor** [comment]
最好市在 index.config.js 这个文件里设置 enableShareAppMessage

**Comment by lightShowers** [comment]
我加了`nableShareAppMessage: true`也不好使啊，大哥你怎么解决的

**Comment by lightShowers** [comment]
> 最好市在 index.config.js 这个文件里设置 enableShareAppMessage

我加了enableShareAppMessage: true也不好使啊，大哥你怎么解决的

**Comment by lightShowers** [comment]
> 最好市在 index.config.js 这个文件里设置 enableShareAppMessage

在没有使用redux的页面完全没问题
