### ISSUE TITLE
Taro3 没法阻止onTouchMove事件冒泡

### ISSUE THREAD

**Issue by wforguo** [NervJS/taro#7234]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/wforguo/taro-issue](https://github.com/wforguo/taro-issue)
**小程序基础库: 2.12.0**
**使用框架: React**

## 代码

```

export default class Index extends Component {
  onTouchMove = (e) => {
    console.log(e);
    e.stopPropagation();
  };

  render() {
    return (
      <View className='login' onTouchMove={this.onTouchMove.bind(this)}>
        <View className='login-inner'>弹层model</View>
      </View>
    )
  }
}


```

## 实际并没有效果，没有阻止冒泡

打印事件对象属性，如下：

- Taro3打印的没有 `stopPropagation` 方法

![事件属性](https://forguo-1302175274.cos.ap-shanghai.myqcloud.com/assets/imgs/touch.png)

- 但是在Taro2 打印的有 `stopPropagation` 方法
![事件属性](https://forguo-1302175274.cos.ap-shanghai.myqcloud.com/assets/imgs/taro2.png)

### 期望结果
使用`touchStart`在事件接受中可以阻止事件的冒泡，也就是事件属性中包含 `stopPropagation`方法

### 实际结果
没有阻止事件冒泡，没有  `stopPropagation`方法

### 环境信息
```

👽 Taro v3.0.0


  Taro CLI 3.0.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.0 => 3.0.0 
      @tarojs/mini-runner: 3.0.0 => 3.0.0 
      @tarojs/react: 3.0.0 => 3.0.0 
      @tarojs/runtime: 3.0.0 => 3.0.0 
      @tarojs/taro: 3.0.0 => 3.0.0 
      @tarojs/webpack-runner: 3.0.0 => 3.0.0 
      babel-preset-taro: 3.0.0 => 3.0.0 
      eslint-config-taro: 3.0.0 => 3.0.0 
      react: ^16.10.0 => 16.13.1 

```

---
### 补充信息
真机和模拟器都不行，微信小程序环境

在这里我需要使用，上拉加载更多，列表容器是没有设置高度的

**Comment by BuleB** [comment]
这是个已知问题[issues](https://github.com/NervJS/taro/issues/6997#issuecomment-656645065)

**Comment by Arima-P** [comment]
遇到相同的问题，函数组件中无法成功stopPropagation！

**Comment by vsme** [comment]
希望尽快解决，加油！

**Comment by Chen-jj** [comment]
#5984

**Comment by wangdanuo** [comment]
issue：#7004，#5984，#7234，#7009均无准确解决方案，大佬们不要再贴了
