### ISSUE TITLE
H5端Taro.pageScrollTo 跳转到顶部无效

### ISSUE THREAD

**Issue by tangsengrouyidai** [NervJS/taro#7235]
### 相关平台
微信小程序

**小程序基础库: null**
**使用框架: React**

### 复现步骤
 <View className="index">
        {[
          1,
          21,
          3123,
          1,
          23,
          123,
          1,
          23,
          ,
          1,
          23,
          1,
          23,
          12,
          3,
          123,
          1,
          2,
          31,
          23,
          1,
          23,
          1,
          23,
          13,
          1,
          1,
          12,
          3123,
          1,
          2,
          3,
          12,
          3,
          1,
          23,
          1,
          23,
          1,
          3,
          12,
          3,
          1,
          3,
          1,
          ,
          321,
          23,
        ].map((_, index) => {
          return <View key={index}>{index}</View>;
        })}
        <Button
          onClick={() => {
            Taro.pageScrollTo({
              scrollTop: 0,
              duration: 300,
            });
          }}
        >
          go top
        </Button>
      </View>

### 期望结果
Taro.pageScrollTo方法在H5实现

### 实际结果
无法跳转到顶部

### 环境信息
```
  Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
最少让浏览器原生方法实现滚动顶部，现在浏览器scrollTop等无法实现滚动顶部

**Comment by cxcxcxcx** [comment]
hack:
```
      if (document) {
        document.scrollingElement.scrollTop = 0;
      }
```

**Comment by Chen-jj** [comment]
上述中 PR 已修复，3.0.19+ 生效
