### ISSUE TITLE
建议3.0文档安装教程增加低版本说明

### ISSUE THREAD

**Issue by xu824332362** [NervJS/taro#7238]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
升级3.0之后，新的taro-cli不兼容低版本导致编译失败

### 期望结果
建议在安装教程页面增加低版本提示，例如：“taro2.0请安装 @tarojs/cli@2.x”

### 实际结果
目前没有提示

### 环境信息
```
� Taro v2.2.6


  Taro CLI 2.2.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/GETTING-STARTED#%E4%BF%9D%E6%8C%81-tarojscli-%E7%9A%84%E7%89%88%E6%9C%AC%E4%B8%8E%E5%90%84%E7%AB%AF%E4%BE%9D%E8%B5%96%E7%89%88%E6%9C%AC%E4%B8%80%E8%87%B4

是有的
