### ISSUE TITLE
执行 taro build --ui 报错：`Error: Cannot find module '../../h5'`

### ISSUE THREAD

**Issue by sqrthree** [NervJS/taro#7267]
### 相关平台
微信小程序

**小程序基础库: v2.11.2**
**使用框架: React**

### 复现步骤
1. 按照 https://nervjs.github.io/taro/docs/ui-lib/ 初始化一个UI项目
2. 执行 taro build --ui

### 期望结果
正常工作

### 实际结果
(node:37039) UnhandledPromiseRejectionWarning: Error: Cannot find module '../../h5'

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ~3.0.7 => 3.0.7
      @tarojs/components: ~3.0.7 => 3.0.7
      @tarojs/mini-runner: ~3.0.7 => 3.0.7
      @tarojs/react: ~3.0.7 => 3.0.7
      @tarojs/runtime: ~3.0.7 => 3.0.7
      @tarojs/taro: ~3.0.7 => 3.0.7
      @tarojs/webpack-runner: ~3.0.7 => 3.0.7
      babel-preset-taro: ~3.0.7 => 3.0.7
      eslint-config-taro: ~3.0.7 => 3.0.7
      react: ^16.10.0 => 16.13.1
```

---
### 补充信息
代码中 `require` 的文件路径错误，对应路径的文件不存在：
- [packages/taro-cli/src/presets/platforms/ui.ts#L21](https://github.com/NervJS/taro/blob/b4e5a0b482d99b230f4657a7d7292eef5c7b0b33/packages/taro-cli/src/presets/platforms/ui.ts#L21)
- [packages/taro-cli/src/presets/platforms/ui.ts#L26](https://github.com/NervJS/taro/blob/b4e5a0b482d99b230f4657a7d7292eef5c7b0b33/packages/taro-cli/src/presets/platforms/ui.ts#L26)

**Comment by Chen-jj** [comment]
@sqrthree Taro 3 组织组件库不需要这个命令了，之后的版本会去掉。

Taro 3 组织组件库可以看这个示例：https://github.com/NervJS/taro-uilib-react
