### ISSUE TITLE
usePullDownRefresh fail

### ISSUE THREAD

**Issue by tinpont** [NervJS/taro#7271]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/tinpont/taro-test-pull-down-refresh](https://github.com/tinpont/taro-test-pull-down-refresh)
**小程序基础库: 2.12.0**
**使用框架: Vue 3**

### 复现步骤
1. yarn && yarn dev:weapp
2. 看控制台

### 期望结果
输出'onPullDownRefresh'

### 实际结果
(in promise) MiniProgramError
R.useContext is not a function
TypeError: R.useContext is not a function
    at http://127.0.0.1:12861/appservice/taro.js:4930:16
    at setup (http://127.0.0.1:12861/appservice/pages/index/index.js:24:76)
    at callWithErrorHandling (http://127.0.0.1:12861/appservice/vendors.js:2164:21)
    at setupStatefulComponent (http://127.0.0.1:12861/appservice/vendors.js:9021:23)
    at setupComponent (http://127.0.0.1:12861/appservice/vendors.js:8974:34)
    at mountComponent (http://127.0.0.1:12861/appservice/vendors.js:6899:5)
    at processComponent (http://127.0.0.1:12861/appservice/vendors.js:6870:9)
    at patch (http://127.0.0.1:12861/appservice/vendors.js:6456:13)
    at mountChildren (http://127.0.0.1:12861/appservice/vendors.js:6653:7)
    at mountElement (http://127.0.0.1:12861/appservice/vendors.js:6597:11)

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7
      @tarojs/mini-runner: 3.0.7 => 3.0.7
      @tarojs/runtime: 3.0.7 => 3.0.7
      @tarojs/taro: 3.0.7 => 3.0.7
      @tarojs/webpack-runner: 3.0.7 => 3.0.7
      babel-preset-taro: 3.0.7 => 3.0.7
      eslint-config-taro: 3.0.7 => 3.0.7
```

**Comment by Chen-jj** [comment]
@tinpont 额，你搞混了。`usePullDownRefresh` 是给 React 及类 React 框架中的函数式组件用的。

Vue 这样直接用就行了：

```js
export default {
  onPullDownRefresh () {
    console.log('onPullDownRefresh')
  },
  setup () {
    const msg = ref('Hello world')

    return {
      msg
    }
  }
}
```

**Comment by tinpont** [comment]
Vue 3.0 的变量是在setup里面，这样用读取不了。除非把变量都放外面，但是这样写起来很别扭。

**Comment by tinpont** [comment]
维护一个下拉刷新和上拉加载更多的接口，就要这样写。感觉上就失去了Vue 3.0的精髓了。
```js
import {reactive} from "vue"

const state = reactive({page: 1, list: []}) 

export default {
  onPullDownRefresh () {
    state.page = 1
    api.get('users').then(response => state.list = response.data)
  },
  onReachBottom() {
    state.page ++
    api.get('users', {page: state.page}).then(response => state.list = state.list.concat(response.data))
  },
  setup () {
    const msg = ref('Hello world')

    // TODO: trigger pull down refresh

    return {
      msg,
      state
    }
  }
}
```

Vue 3.0也有hooks，这个能不能支持一下？ @Chen-jj

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/89484444-1a717000-d7d1-11ea-94d4-4d39c809be08.png)

options api 可以获取到 setup return 的内容的，先用着吧，之后再考虑添加 composition API 版本的小程序钩子

**Comment by tinpont** [comment]
那我单独提个feature request
