### ISSUE TITLE
k8s容器服务怎么整合apollo

### ISSUE THREAD

**Issue by jsonQin** [NervJS/taro#7275]
有没有教程呀，公司要求阿里云上面的k8s容易服务创建应用，把apollo整进去，但是整了半天报这个错，好像没有找到过完整的教程。
![image](https://user-images.githubusercontent.com/43943896/89504810-3ab62480-d7fb-11ea-80ef-41a71e68d8fb.png)

**Comment by jsonQin** [comment]
k8s容器服务怎么整合apollo

**Comment by Chen-jj** [comment]
请按规范提交 issue
