### ISSUE TITLE
jQuery-like 中的 offset 方法微信端与h5端的不统一

### ISSUE THREAD

**Issue by John60676** [NervJS/taro#7287]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
使用 jQuery-like 中的 offset 方法
```
const targetElem = $('.target');
await targetElem.offset()
```
### 期望结果
小程序端的结果与h5端的一致，offset能包含border-width与padding

### 实际结果
小程序端的结果与h5端的不一致

### 环境信息
```
Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.10.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.7 => 3.0.7 
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.7.5
```

**Comment by Chen-jj** [comment]
**jQuery** 的 `offset` 方法只有 `top` 和 `left` 信息：

![image](https://user-images.githubusercontent.com/11807297/105949929-7b0aa700-60a8-11eb-89a0-a51c90182ecb.png)

Taro H5 也和小程序一样，`offset` 的返回只有 `top` `left` `height` `width` 四个属性：

![image](https://user-images.githubusercontent.com/11807297/105950035-ab524580-60a8-11eb-9a4d-87264bafeaa6.png)

![image](https://user-images.githubusercontent.com/11807297/105950166-e5bbe280-60a8-11eb-817c-a258ee8e0036.png)

都没有看到 `border-width` 与 `padding` 信息。
