### ISSUE TITLE
3.X版本h5端不支持onReachBottom了吗？

### ISSUE THREAD

**Issue by LionelSun** [NervJS/taro#7288]
### 相关平台
H5

**浏览器版本: Chrom 84**
**使用框架: React**

### 复现步骤
上拉触底事件仅在小程序下生效了，之前2.X版本h5端是没问题的

onReachBottom() {
        console.log('上拉触底1')
}

### 期望结果
页面触底时触发 onReachBottom

### 实际结果
h5中并没有触发，仅在小程序中触发

### 环境信息
```
Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0
      npm: 6.14.5
```

**Comment by LengYXin** [comment]
@Chen-jj   taro h5路由 好像有代码逻辑错误 导致 onPullDownRefresh 无法触发
```
if (pageEl && pageEl.__page) {
        pageEl.__page.onPullDownRefresh()
      }
```
__page 无法获取 
原因是检查了路由代码 中的 onLoad 一直为false 无法赋值。
麻烦大佬检查一下。
![image](https://user-images.githubusercontent.com/19631404/89749254-89183b80-daf9-11ea-845e-e9cc11d8a390.png)
![image](https://user-images.githubusercontent.com/19631404/89749285-9fbe9280-daf9-11ea-99ec-357e909ffffa.png)

**Comment by beysong** [comment]
小程序也用不了，3.0.13版本

**Comment by ecstAsy** [comment]
请问这个问题解决了吗？

**Comment by 349989153** [comment]
？

**Comment by 349989153** [comment]
@Chen-jj 更新到哪个版本h5能用onPullDownRefresh？直接给个痛快话，目前3.0.7、3.0.8、3.0.19都不行
