### ISSUE TITLE
可否去掉不相关 的 eslint 规则?

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#729]
我了解 taro 和 react 的 eslint 规则有点冲突，因此有了 eslint-config-taro 这个官方库。
但是这个库里面除了兼容 taro 语法以外，还加了很多不相关的 eslint 规则，这些规则和我之前项目的 eslint 规则不太相同。这对已经有项目规范的团队来说，不太友好。

**Comment by yuche** [comment]
当然可以，你不用 eslint 都行啊。

**Comment by jamieYou** [comment]
> 当然可以，你不用 eslint 都行啊。不想用的规则直接在 eslintrc 禁用就可以了

这样得一个一个找出来覆盖 orz

**Comment by yuche** [comment]
那你就用 eslint plugin taro 不用 eslint config taro

**Comment by jamieYou** [comment]
> 那你就用 eslint plugin taro 不用 eslint config taro

好像可以
