### ISSUE TITLE
v3.0.7 h5下 热更新失效

### ISSUE THREAD

**Issue by jenerse** [NervJS/taro#7291]
### 相关平台
H5

**浏览器版本: Chrome 84.0.4147.105**
**使用框架: React**

### 复现步骤
1. 使用taro 3.0.7新建版本
2. 在 config/dev.js h5中加入 devServer配置，具体配置如下
```
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  mini: {},
  h5: {
    devServer: {
      host: 'localhost',
      port: 80,
      hot: true,
    },
  }
}
```

3. 启动taro服务(可能需要sudo启动)

4. 使用浏览器访问 http://localhost

### 期望结果
热更新生效

### 实际结果
热更新失效, 打开f12提示热更新断开

<img width="659" alt="WeChata79857acb7bbf5b3301ab9debd1bd715" src="https://user-images.githubusercontent.com/4142224/89707102-d7b0c300-d99d-11ea-8e5d-43f3fe981a70.png">

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.7 => 3.0.7 
      @tarojs/components: ^3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: ^3.0.7 => 3.0.7 
      babel-preset-taro: ^3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.13.1 => 16.13.1 
```

**Comment by luckyadam** [comment]
不用 80 端口试试

**Comment by jenerse** [comment]
> 不用 80 端口试试

我把port和hot这两项删了，也不行。

**Comment by jenerse** [comment]
> 不用 80 端口试试

@luckyadam 我把port和hot这两项删了，也不行。

**Comment by jenerse** [comment]
@luckyadam 我这边测试了一下。3.0.5这版本是可以的，但3.0.6和3.0.7就不行了，好像是加入了 devServer 的配置就会出问题

**Comment by tuoxie15** [comment]
我也失效了，热启动失效

**Comment by jenerse** [comment]
@luckyadam 3.0.8问题依旧，请问有什么解决办法吗？

**Comment by Chen-jj** [comment]
@jenerse 应该是这个 PR 导致，我们再看看。https://github.com/NervJS/taro/pull/7167

**Comment by jenerse** [comment]
@Chen-jj 好的，谢谢

**Comment by Chen-jj** [comment]
设置 `hot: true` 还是有问题，需要再看看

**Comment by jenerse** [comment]
@Chen-jj 如果我把useLocalIp设置成false就可以刷新了。

**Comment by Chen-jj** [comment]
3.1 修复 hot reload 失效的问题，且支持 React fast-refresh
