### ISSUE TITLE
"export 'default' (imported as 'component') was not found in ...

### ISSUE THREAD

**Issue by ethan-202285** [NervJS/taro#7299]
![image](https://user-images.githubusercontent.com/61540820/89789752-99f59b00-db53-11ea-9bec-1e0dc963d42d.png)

taro 2.2.3的时候挺正常的，但是今天升级到3.0.5,就一直报错，这个是咋回事？

**Comment by shenghanqin** [comment]
@ethan-202285 在taro 2.x上export可以直接用，但在taro 3.0上必须写成export default

**Comment by younthu** [comment]
遇到同样的问题

**Comment by mxppxm** [comment]
这个怎么解决的啊

**Comment by mxppxm** [comment]
> 问题

怎么解决的啊

**Comment by younthu** [comment]
可以参考一下: http://blog.ilibrary.me/2021/02/22/taro%E5%8D%87%E7%BA%A7

**Comment by pxim** [comment]
楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
![image](https://user-images.githubusercontent.com/5111701/114676169-9ac27a80-9d3b-11eb-9057-cfb03af2ee84.png)

![image](https://user-images.githubusercontent.com/5111701/114676219-ad3cb400-9d3b-11eb-8880-9ed7795b66de.png)

**Comment by pxim** [comment]
> 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了

我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路由了，这时候又在 分包里import  A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了

**Comment by Benjaminbai** [comment]
> > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> 
> 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了

是可以，可是组件的入口没了呀！

**Comment by pxim** [comment]
> > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > 
> > 
> > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> 
> 是可以，可是组件的入口没了呀！

把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，

**Comment by Benjaminbai** [comment]
> > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > 
> > > 
> > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > 
> > 
> > 是可以，可是组件的入口没了呀！
> 
> 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，

只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？

**Comment by pxim** [comment]
> 做



> > > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > > 
> > > > 
> > > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > > 
> > > 
> > > 是可以，可是组件的入口没了呀！
> > 
> > 
> > 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，
> 
> 只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？

eslint 语法检查，是你编辑器的问题吧，我用webstorm语法检查正常的。

**Comment by Benjaminbai** [comment]
> > 做
> 
> > > > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > > > 
> > > > > 
> > > > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > > > 
> > > > 
> > > > 是可以，可是组件的入口没了呀！
> > > 
> > > 
> > > 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，
> > 
> > 
> > 只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？
> 
> eslint 语法检查，是你编辑器的问题吧，我用webstorm语法检查正常的。

我想要像vuecli/cra一样npm run的时候eslint规则不通过，编译不起来的那种，你的是这样？

**Comment by pxim** [comment]
> > > 做
> > 
> > 
> > > > > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > > > > 
> > > > > > 
> > > > > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > > > > 
> > > > > 
> > > > > 是可以，可是组件的入口没了呀！
> > > > 
> > > > 
> > > > 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，
> > > 
> > > 
> > > 只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？
> > 
> > 
> > eslint 语法检查，是你编辑器的问题吧，我用webstorm语法检查正常的。
> 
> 我想要像vuecli/cra一样npm run的时候eslint规则不通过，编译不起来的那种，你的是这样？

应该是的，类型不对，都编译报错

**Comment by Benjaminbai** [comment]
> > > > 做
> > > 
> > > 
> > > > > > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > > > > > 
> > > > > > > 
> > > > > > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > > > > > 
> > > > > > 
> > > > > > 是可以，可是组件的入口没了呀！
> > > > > 
> > > > > 
> > > > > 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，
> > > > 
> > > > 
> > > > 只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？
> > > 
> > > 
> > > eslint 语法检查，是你编辑器的问题吧，我用webstorm语法检查正常的。
> > 
> > 
> > 我想要像vuecli/cra一样npm run的时候eslint规则不通过，编译不起来的那种，你的是这样？
> 
> 应该是的，类型不对，都编译报错

大佬，带带我，怎么配置

**Comment by pxim** [comment]
> > > > > 做
> > > > 
> > > > 
> > > > > > > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > > > > > > 
> > > > > > > 
> > > > > > > 是可以，可是组件的入口没了呀！
> > > > > > 
> > > > > > 
> > > > > > 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，
> > > > > 
> > > > > 
> > > > > 只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？
> > > > 
> > > > 
> > > > eslint 语法检查，是你编辑器的问题吧，我用webstorm语法检查正常的。
> > > 
> > > 
> > > 我想要像vuecli/cra一样npm run的时候eslint规则不通过，编译不起来的那种，你的是这样？
> > 
> > 
> > 应该是的，类型不对，都编译报错
> 
> 大佬，带带我，怎么配置

webstorm自带的功能，我都没配置过，带不了

**Comment by Benjaminbai** [comment]
> > > > > > 做
> > > > > 
> > > > > 
> > > > > > > > > > 楼主怎么解决的，我也出现这个问题了，明明已经 export default 了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我的问题，我找到原因了，因为我把组件A 配置到 app.config.ts的pages里，当做路径了，这时候又在 分包里import A这个组件，所以报这个错误；把组件A 从 app.config.ts的pages里 删掉就行了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是可以，可是组件的入口没了呀！
> > > > > > > 
> > > > > > > 
> > > > > > > 把公共代码提取出来，放到组件C，然后组件A,B分别引入C，入口配置A,B，
> > > > > > 
> > > > > > 
> > > > > > 只好这样做了，我还有些问题，taro运行时 eslint没有做语法检查，大佬了解么？
> > > > > 
> > > > > 
> > > > > eslint 语法检查，是你编辑器的问题吧，我用webstorm语法检查正常的。
> > > > 
> > > > 
> > > > 我想要像vuecli/cra一样npm run的时候eslint规则不通过，编译不起来的那种，你的是这样？
> > > 
> > > 
> > > 应该是的，类型不对，都编译报错
> > 
> > 
> > 大佬，带带我，怎么配置
> 
> webstorm自带的功能，我都没配置过，带不了

不会呀，不是错误提示，而是npm run dev被阻止，页面都启动不了的那种
