### ISSUE TITLE
建议组件添加对svg的支持

### ISSUE THREAD

**Issue by silence717** [NervJS/taro#73]
<img width="443" alt="component" src="https://user-images.githubusercontent.com/8267830/41225144-bbcf338a-6da0-11e8-9dcd-fb738139a8c0.png">

编写了一个svg，发现跑不出来，去掉taro外层可正常显示，因此看了下对外提供的components发现没有svg，是否考虑添加对svg的支持。

**Comment by luckyadam** [comment]
主要小程序没有 svg 组件~

**Comment by silence717** [comment]
@luckyadam 好吧~ 那我尝试下切到canvas。
