### ISSUE TITLE
测试框架无法涵盖TouchEvent

### ISSUE THREAD

**Issue by SzHeJason** [NervJS/taro#730]
**问题描述**
`nerv-test-utils` 这个库在写测试的时候发现是使用了 `simulate-event` ，但是这个库是不支持模拟`Touch` 事件数据的，因为里面对于 `Touch` 事件的构造函数是 `UIEvent` 而不是 `TouchEvent`,  `UIEvent` 是没有 `touches` 这些属性的

**复现步骤**
```js
Simulate.touchStart(document.body,{ touches: [] }) // 报错 无法获取模拟 touches 属性
```

**期望行为**
可以模拟绝大部分的 `Event`

**报错信息**

![image](https://user-images.githubusercontent.com/20609396/46192766-be18ac00-c32e-11e8-92ea-ca0277b0cb71.png)

**系统信息**

 - 操作系统: MacOS 10
 - Taro 版本: v1.0.4
 - Node.js 版本 v10.0.8

**Comment by yuche** [comment]
https://codesandbox.io/s/88y5ww5xpj
看起来像是你的环境问题

**Comment by SzHeJason** [comment]
模拟的是 `UIEvent` 自己滑动触发的是 `TouchEvent`, 
并且 `UIEvent`里面没有 `touches` 属性

![image](https://user-images.githubusercontent.com/20609396/46206023-4e69e780-c355-11e8-8bd6-ad90a37fe350.png)

**Comment by yuche** [comment]
看看这是不是你想要的效果
[![Edit Nerv sandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/525wyjmpmk)

**Comment by SzHeJason** [comment]
嗯 是的 就是这个效果

**Comment by yuche** [comment]
那你现在可以按照里面写的那样导出 `Simulate ` 对象先用着，下个版本的 nerv-test-utils 会改成那样。
