### ISSUE TITLE
taro 3.0.7 在h5平台上使用AtImagePicker报错

### ISSUE THREAD

**Issue by yxl2628** [NervJS/taro#7300]
### 相关平台
H5

### 复现仓库
[https://github.com/yxl2628/error-demo](https://github.com/yxl2628/error-demo)
**浏览器版本: Chrome 81**
**使用框架: React**

### 复现步骤
```bash
git clone https://github.com/yxl2628/error-demo.git
cd error-demo
cd AtImagePicker
yarn
npm run dev:h5
```

- 错误1：访问 `http://127.0.0.1:10086/pages/index/index`，此页面使用class，页面空白，报错`TypeError: Super expression must either be null or a function`

- 错误2：访问 `http://127.0.0.1:10086/pages/index2/index`，此页面使用function，页面能展示，但是点击 号添加图片时，报错`index.umd.js?ccf5:6533 Uncaught ReferenceError: _chooseImage is not defined`

### 期望结果
能够解决这个bug

### 实际结果
能够解决这个bug

### 环境信息
```
Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by vchewjs** [comment]
这个问题我也遇到了  怎么搞怎么办，有解决方案吗？

**Comment by vchewjs** [comment]
![image](https://user-images.githubusercontent.com/41767421/91300518-002a2100-e7d6-11ea-8719-f751e011f924.png)

**Comment by Bruce-zxy** [comment]
#1178 这个Issue提供了临时解决方案
