### ISSUE TITLE
Taro v3.0.7  build:h5时报错

### ISSUE THREAD

**Issue by 349989153** [NervJS/taro#7303]
### 相关平台
H5

**浏览器版本: Chrome 版本 84.0.4147.105（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
原本taro-cli和项目中的taro是`v3.0.2`版本，运行`npm run build:h5`正常。

后面为了解决另一个问题，运行以下命令升级到v3.0.7：
`sudo taro update self 3.0.7`
`taro update project 3.0.7`

然后在3.0.7环境下打包 npm run build:h5 就报错了：
```
🙅   Failed to compile.

./src/app.config.js
Module not found: Can't resolve './pages/activityApply/index.config' in '/Users/luyang/workspace/company/new-time-center/src'
```

而我`/pages/activityApply/`下有且只有`index.jsx`，从来没有过`index.config`，不明白为什么会报这个错。

在v3.0.7下，运行以下命令回退版本：
`sudo taro update self 3.0.2`
`taro update project 3.0.2`

回退成功之后，不改变项目中任何文件的情况下，运行`npm run build:h5`，可以成功build。

我认为这说明v3.0.7打包是有问题的。

### 期望结果
`npm run build:h5`成功

### 实际结果
`npm run build:h5`报错
```
🙅   Failed to compile.

./src/app.config.js
Module not found: Can't resolve './pages/activityApply/index.config' in '/Users/luyang/workspace/company/new-time-center/src'
```

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 


```

**Comment by 349989153** [comment]
![Taro](https://user-images.githubusercontent.com/10381674/89865453-5ac15b80-dbe0-11ea-8d91-11b18bdf06e7.jpg)
附上报错文件的截图，没看出来为什么报错了

**Comment by 349989153** [comment]
我的repo是github上私有repo，麻烦需要代码的同学加我qq，谢谢

**Comment by 349989153** [comment]
3.0.2 h5.router.mode = hash取不到参数，h5.router.mode = browser报Route not found

3.0.7 build报错不知道哪里有问题

救救孩子吧

**Comment by 349989153** [comment]
ok，每个页面下都加上对应都`xxxx.config.js`就可以了

**Comment by paulloo** [comment]
> 3.0.2 h5.router.mode = hash取不到参数，h5.router.mode = browser报Route not found
> 
> 3.0.7 build报错不知道哪里有问题
> 
> 救救孩子吧

正解，3.0.7 包这个错也是h5.router.mode 取不到参数的原因

**Comment by konglx90** [comment]
> ok，每个页面下都加上对应都`xxxx.config.js`就可以了

为什么要强制加呢

**Comment by 349989153** [comment]
@konglx90 我不知道，3.0.2的时候还不会报错的，升级之后就这样了。
