### ISSUE TITLE
支付宝小程序支持使用自定义组件

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#7309]
### 这个特性解决了什么问题？
使在一些复杂场景下，需要通过原生自定义组件来优化性能。同时，第三方原生组件库也需要通过自定义组件的方式使用。

### 这个 API 长什么样？
像微信小程序自定义组件一样使用

**Comment by Chen-jj** [comment]
支付宝页面使用自定义组件，需要在该支付宝页面对应的 axml 文件中使用。但目前 Taro 中，所有页面都会使用 base.axml 里的模板，这样就会使得引用自定义组件失效。

解决办法是支付宝每个页面（或者识别出使用了自定义组件的页面），把模板都编译到该页面的 axml 文件中，而不是引用 base.axml。代价是包体积会大一点。

改动比较麻烦，需要点时间再想想。

**Comment by Chen-jj** [comment]
3.1 已支持
