### ISSUE TITLE
函数组件中使用createCanvasContext获取this,使用useScope获取this是否存在问题

### ISSUE THREAD

**Issue by keepresolve** [NervJS/taro#7311]
### 这个特性解决了什么问题？
函数组件中  使用createCanvasContext 创建 CanvasContext 对象。 使用useScope获取小程序原生作用域是否存在问题

### 这个 API 长什么样？
#6247 说要被移除 是否我使用useScope 升级后需要修改代码  我希望能够提供与一个稳定的APi能够在函数组件中获取小程序原生作用域

**Comment by Chen-jj** [comment]
Taro3 一般情况下不存在原生自定义组件，这是不需要传入小程序原生作用域。如果在嵌套层级过深或使用了 CustomWrapper 等情况下使用了原生自定义组件，可以参考文档的方法获取scope：https://docs.taro.zone/docs/ref#%E4%BD%BF%E7%94%A8%E4%BA%86-customwrapper-%E6%97%B6
