### ISSUE TITLE
Taro2升级Taro3后，canvas绘图没有效果，draw回调也没有执行

### ISSUE THREAD

**Issue by Neilai** [NervJS/taro#7314]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Neilai/Taro-bug](https://github.com/Neilai/Taro-bug)
**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
克隆仓库，yarn, yarn dev,然后使用小程序开发工具打开，会发现canvas回调以及绘图都没有效果。
```javascript
import { View, Canvas ,Image} from "@tarojs/components";
import React, { Component } from "react";
import Taro from "@tarojs/taro";
import "./index.scss";

export default class Index extends Component {
  private ctx;

  onReady() {
    this.ctx = Taro.createCanvasContext("image-cropper");
    this.ctx.setFillStyle("red");
    this.ctx.fillRect(0, 0, 100, 100);
    this.ctx.draw(false, () => {
      console.log("call back");
    });
  }

  render() {
    return (
      <View>
        <Canvas
          canvasId='image-cropper'
          disable-scroll='true'
          style='width: 100px;height:100px'
          className='image-cropper-canvas'
        />
      </View>
    );
  }
}
```

### 期望结果
出现canvas绘制的红色矩形，回调执行

### 实际结果
canvas没有绘图，回调也未执行

### 环境信息
```
Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7
      @tarojs/mini-runner: 3.0.7 => 3.0.7
      @tarojs/react: 3.0.7 => 3.0.7
      @tarojs/runtime: 3.0.7 => 3.0.7
      @tarojs/taro: 3.0.7 => 3.0.7
      @tarojs/webpack-runner: 3.0.7 => 3.0.7
      babel-preset-taro: 3.0.7 => 3.0.7
      eslint-config-taro: 3.0.7 => 3.0.7
      react: ^16.10.0 => 16.13.1
```

**Comment by Neilai** [comment]
Taro2下创建改成Taro.createCanvasContext("image-cropper",this.$scope);回调以及绘图都是正常的，做了一个升级，canvas绘图就失效了

**Comment by shenghanqin** [comment]
俺也来跟一下，貌似我在react分支，微信小程序上没啥问题。

**Comment by Neilai** [comment]
> 俺也来跟一下，貌似我在react分支，微信小程序上没啥问题。

oh?canvas画图是正常的吗？

**Comment by shenghanqin** [comment]
> > 俺也来跟一下，貌似我在react分支，微信小程序上没啥问题。
> 
> oh?canvas画图是正常的吗？

我这个试了一下是ok的
https://github.com/hi-our/hi-face/blob/feature%2Fnext-react-20200213/taro/src/pages/avatar-edit/avatar-edit.js

**Comment by Neilai** [comment]
> > > 俺也来跟一下，貌似我在react分支，微信小程序上没啥问题。
> > 
> > 
> > oh?canvas画图是正常的吗？
> 
> 我这个试了一下是ok的
> https://github.com/hi-our/hi-face/blob/feature%2Fnext-react-20200213/taro/src/pages/avatar-edit/avatar-edit.js

那我的bug仓库您那边可以复现嘛？？是我哪里使用有问题嘛 = =

**Comment by Neilai** [comment]
这是Taro2下的测试代码
```javascript
import Taro, { Component, Config } from "@tarojs/taro";
import {Canvas } from "@tarojs/components";
import "./index.less";

export default class Index extends Component {
  componentDidMount() {
    const ctx = Taro.createCanvasContext("image-cropper", this.$scope);
    ctx.setFillStyle("red");
    ctx.fillRect(0, 0, 50, 50);
    ctx.draw(false, () => {
      console.log("callback");
    });
  }
  config: Config = {
    navigationBarTitleText: "首页"
  };

  render() {
    return <Canvas canvasId="image-cropper" style="width:200px;height:200px"></Canvas>;
  }
}

```
绘图和callback都正常调用
![image](https://user-images.githubusercontent.com/32212935/89998263-e231cc00-dcbf-11ea-8634-bab14a3e360f.png)

**Comment by xinggangling** [comment]
这个已经解决了

**Comment by youyou0101** [comment]
> 这个已经解决了
是在3.0.8解决了吗？

**Comment by lineCode** [comment]
这个最新的啥时候能用了，我现在刚好卡在这了

**Comment by lavapapa** [comment]
我正好遇到这个问题，并解决了。微信小程序提供了两种canvas的api，用type属性来区分他们：如果有type=‘2d'| 'webgl'，就使用新版api，否则使用旧版。但是，微信文档语焉不详，新版本taro就把type='2d'作为canvas 的默认属性了，旧版直接升级上来，用旧api肯定是不行的，具体证据可以查看源码。如果仍要用旧版接口，解决办法就是手动设置type属性为其它任何属性，覆盖掉taro的默认值，就能以旧版api 的方式来使用。

**Comment by shuwenjunn** [comment]
> 我正好遇到这个问题，并解决了。微信小程序提供了两种canvas的api，用type属性来区分他们：如果有type=‘2d'| 'webgl'，就使用新版api，否则使用旧版。但是，微信文档语焉不详，新版本taro就把type='2d'作为canvas 的默认属性了，旧版直接升级上来，用旧api肯定是不行的，具体证据可以查看源码。如果仍要用旧版接口，解决办法就是手动设置type属性为其它任何属性，覆盖掉taro的默认值，就能以旧版api 的方式来使用。
能看下代码吗？

**Comment by Kybs0** [comment]
> 我正好遇到这个问题，并解决了。微信小程序提供了两种canvas的api，用type属性来区分他们：如果有type=‘2d'| 'webgl'，就使用新版api，否则使用旧版。但是，微信文档语焉不详，新版本taro就把type='2d'作为canvas 的默认属性了，旧版直接升级上来，用旧api肯定是不行的，具体证据可以查看源码。如果仍要用旧版接口，解决办法就是手动设置type属性为其它任何属性，覆盖掉taro的默认值，就能以旧版api 的方式来使用。

感谢！解决了~

**Comment by fredmanxu** [comment]
我删掉了 `Canvas` 组件的 `type` 属性,像[文档](https://taro-docs.jd.com/taro/docs/components/canvas/#canvasprops)中所说
![image](https://user-images.githubusercontent.com/20528643/192932521-f4593d9b-0a54-41af-8834-045599df78d8.png)

我的开发版本
```
"react": "^18.0.0",
"@tarojs/taro": "3.5.6",
```
之前的代码
```
 <Canvas
            type={'2d'}
            canvasId={CanvasId}
            id={CanvasId}
          />
```
现在的代码
```
 <Canvas
            canvasId={CanvasId}
            id={CanvasId}
          />
```
再次尝试绘制,它是生效的
```
   const ctx = Taro.createCanvasContext(CanvasId);
              ctx.setFillStyle('red')
              ctx.fillRect(10, 10, 150, 100)
              ctx.draw()
```
