### ISSUE TITLE
使用linaria创建的Button组件，不能使用使用openType

### ISSUE THREAD

**Issue by JasonJie** [NervJS/taro#7318]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
使用linaria创建的Button组件，不能使用使用openType，弹出不了授权功能。
不使用linaria创建，直接使用Butto，可以弹出授权功能

onst ButtonComponent = styled(Button)`
  width: 100%;
  background-color: #3eaaf2;
  border-radius: 40px;
  height: 84px;
  display: flex;
  align-items: center;
  justify-content: center;
  Text {
    font-size: 28px;
    color: #ffffff;
  }
`;

 <ButtonComponent openType="getUserInfo" onGetUserInfo={getUserInfo}>
          <Text>确定</Text>
        </ButtonComponent>

### 期望结果
可以弹出授权功能

### 实际结果
无法弹出授权功能

### 环境信息
```
Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    npmPackages:
      @tarojs/components: 3.0.5 => 3.0.5 
      @tarojs/mini-runner: 3.0.5 => 3.0.5 
      @tarojs/react: 3.0.5 => 3.0.5 
      @tarojs/runtime: 3.0.5 => 3.0.5 
      @tarojs/taro: 3.0.5 => 3.0.5 
      @tarojs/webpack-runner: 3.0.5 => 3.0.5 
      babel-preset-taro: 3.0.5 => 3.0.5 
      eslint-config-taro: 3.0.5 => 3.0.5 
      react: ^16.10.0 => 16.13.1 
```

**Comment by honlyHuang** [comment]
和这个 https://github.com/NervJS/taro/issues/7163 是同一个问题
