### ISSUE TITLE
【小程序】shouldComponentUpdate参数有误

### ISSUE THREAD

**Issue by wfsovereign** [NervJS/taro#732]
**问题描述**
小程序中，shouldComponentUpdate中的state和nextState极大不一致，开发者很难看出来是如何进行比较的

<img width="404" alt="wechatimg3922" src="https://user-images.githubusercontent.com/9333309/46204269-34c5a180-c34f-11e8-9a05-3700d7681e06.png">

**系统信息**

 - 操作系统: OXS 10.13.6
 - Taro 版本 1.0.4
 - Node.js 版本 10.7.0

**Comment by luckyadam** [comment]
能不能贴一下打印的代码

**Comment by Chen-jj** [comment]
@wfsovereign 提供一下相关代码？单单对比截图中 state 与 next state 并不能得出什么结论，setState 的内容会有影响，anonymousState__xxx 则与你的 JSX 编写有关。

**Comment by wfsovereign** [comment]
在 1.1.1版本中没有复现，就先关闭了
