### ISSUE TITLE
打包时候可以自定义某些页面不被编译到微信小程序或支付宝小程序

### ISSUE THREAD

**Issue by TokeyJerry** [NervJS/taro#7321]
### 这个特性解决了什么问题？
1、业务庞大，某些功能只有微信小程序有，而支付宝就可以节省这部分代码体积
2、可以根据 process.env.TARO_ENV 编译某一端才有的代码

### 这个 API 长什么样？
config 中是否可以配置过滤页面

**Comment by vdfor** [comment]
不同环境配置不同的pages就可以了吧

**Comment by TokeyJerry** [comment]
> 不同环境配置不同的pages就可以了吧

问题一、Taro 2.X 中 app.js 的 config 不可动态配置，所以根据不同环境配置不同的 pages 不能实现（如有方法，请帮忙描述下实现方案）；

问题二、在打包运行的过程中是遍历 src 下的目录去打包，所以光配置 pages，打包的时候还是会把多余的页面打进去

**Comment by TokeyJerry** [comment]
参考
- https://github.com/NervJS/taro/pull/3867
- [3.x](https://nervjs.github.io/taro/docs/envs#appjs-%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84-pages)
- [2.x](https://nervjs.github.io/taro/docs/2.2.11/envs#appjs-%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84-pages)
