### ISSUE TITLE
VirtualList在加载过多图片时出现闪屏

### ISSUE THREAD

**Issue by qaqslzy** [NervJS/taro#7327]
### 相关平台
微信小程序

### 复现仓库
[https://gitlab.com/qaqs/about-taro-virtuallist/-/tree/master](https://gitlab.com/qaqs/about-taro-virtuallist/-/tree/master)
**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
滚动VirtualList

### 期望结果
List 可以顺畅的滑动

### 实际结果
在滑动过程中图片闪烁
视频：https://share.weiyun.com/ckYjQA7g

### 环境信息
```
$ taro info     
👽 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
```

---
### 补充信息
在设定overscanCount时，如`overscanCount={20}`的情况下我轻轻滑动一下，也会造成Row里的内容重新渲染，大概像是`top:0px`这样渲染成`top:240px`，然后又渲染回`top:0px`这个样子，因此造成了图片的闪烁（虽然不设定overscanCount的时候也会闪），这种情况是正常的吗？
像这种图片多的情况下，VirtualList适合这种场景吗？

**Comment by iamxiyang** [comment]
目前遇到了和你一样的情况，在VirtualList中渲染图片会出现明显的闪烁感，想问你现在是通过什么方式解决的？还是暂时放弃了这种方式。

**Comment by qaqslzy** [comment]
@iamxiyang 放弃了。。

**Comment by qaqslzy** [comment]
> 目前遇到了和你一样的情况，在VirtualList中渲染图片会出现明显的闪烁感，想问你现在是通过什么方式解决的？还是暂时放弃了这种方式。

@iamxiyang 放弃了。。

**Comment by Chen-jj** [comment]
@iamxiyang @qaqslzy **3.0.9** 修复

目前列表去除第一项时，Taro DOM 的算法是重新渲染整个列表。

闪屏的原因发现是因为现在 base.wxml 中模板的 key 没有设置对，现在设置为 id：`wx:key="id"`，但 Taro DOM 树数据结构中每个节点的唯一标识是 `uid`。

![image](https://user-images.githubusercontent.com/11807297/91536994-2bcd1880-e948-11ea-8ab3-7362e933b15a.png)

这样相当于没有设置 key，微信则会卸载整个列表，然后再全部重新渲染，使用了 Image 会放大这种重新渲染的时间差，导致肉眼可见的闪屏。

下个版本把 key 设置正确，微信 diff 后只会卸载第一项，则不会再闪烁了。

**Comment by ychangh** [comment]
我用3.0.14还是存在这个问题

**Comment by ychangh** [comment]
> @iamxiyang @qaqslzy **3.0.9** 修复
> 
> 目前列表去除第一项时，Taro DOM 的算法是重新渲染整个列表。
> 
> 闪屏的原因发现是因为现在 base.wxml 中模板的 key 没有设置对，现在设置为 id：`wx:key="id"`，但 Taro DOM 树数据结构中每个节点的唯一标识是 `uid`。
> 
> ![image](https://user-images.githubusercontent.com/11807297/91536994-2bcd1880-e948-11ea-8ab3-7362e933b15a.png)
> 
> 这样相当于没有设置 key，微信则会卸载整个列表，然后再全部重新渲染，使用了 Image 会放大这种重新渲染的时间差，导致肉眼可见的闪屏。
> 
> 下个版本把 key 设置正确，微信 diff 后只会卸载第一项，则不会再闪烁了。

我现在用最新的版本3.0.14还会出现这个问题
