### ISSUE TITLE
在StoryBook中使用 Taro 组件会提示找不到？

### ISSUE THREAD

**Issue by weilkss** [NervJS/taro#7328]
### 相关平台
H5

### 复现仓库
[https://github.com/weilkss/doit-taro-ui/tree/develop](https://github.com/weilkss/doit-taro-ui/tree/develop)
**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
编写文档时导入组件或者直接导入也不行？

```js
import React from 'react'
import { Story, Meta } from '@storybook/react/types-6-0'

// import { DtButton } from '../dist'
import { Button } from '@tarojs/components'

export default {
  title: '基础组件/DtButton'
} as Meta

export const Buttons = () => {
  return <Button>dddd</Button>
}

```
错误提示

```js
WARNING in ./stories/DtButton.stories.tsx 35:42-48
"export 'Button' was not found in '@tarojs/components'
 @ \.)(?=.)[^\/]*?\.stories\.(js|jsx|ts|tsx))$ (./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^\/]*?\.stories\.(js|jsx|ts|tsx))$)
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/defaultParameters.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

### 期望结果
期望正常导入按钮

### 实际结果
未找到

### 环境信息
```
$ taro info     
👽 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
```

---
### 补充信息
使用的是 taro-uilib-react 模板

**Comment by weilkss** [comment]
卧槽，官方也不给处理下吗？

**Comment by vdfor** [comment]
同样遇到这个问题了

**Comment by Chen-jj** [comment]
@weilkss @vdfor 

demo 链接失效了。

我觉得 StoryBook 做的事情等于在一个 React 项目中使用 `@tarojs/components` 这个包里的组件。

`@tarojs/components` 是使用 **Web Components** 实现的，有一层胶水层对接。所以 Taro 调用 webpack 编译时，做了以下  alias：

https://github.com/NervJS/taro/blob/fbf79a2f3dfb03d702a45545f04f9a2e0fa7fd7f/packages/taro-webpack-runner/src/config/dev.conf.ts#L108-L110

没有 alias 的话会报本 issue 提及的错误。

另外，需要先调用 Stencil 框架的启动代码：

https://github.com/NervJS/taro/blob/fbf79a2f3dfb03d702a45545f04f9a2e0fa7fd7f/packages/taro-loader/src/h5.ts#L50-L52

上述两步都处理好后，应该就可以成功运行了。

**Comment by vdfor** [comment]
> @weilkss @vdfor
> 
> demo 链接失效了。
> 
> 我觉得 StoryBook 做的事情等于在一个 React 项目中使用 `@tarojs/components` 这个包里的组件。
> 
> `@tarojs/components` 是使用 **Web Components** 实现的，有一层胶水层对接。所以 Taro 调用 webpack 编译时，做了以下 alias：
> 
> https://github.com/NervJS/taro/blob/fbf79a2f3dfb03d702a45545f04f9a2e0fa7fd7f/packages/taro-webpack-runner/src/config/dev.conf.ts#L108-L110
> 
> 没有 alias 的话会报本 issue 提及的错误。
> 
> 另外，需要先调用 Stencil 框架的启动代码：
> 
> https://github.com/NervJS/taro/blob/fbf79a2f3dfb03d702a45545f04f9a2e0fa7fd7f/packages/taro-loader/src/h5.ts#L50-L52
> 
> 上述两步都处理好后，应该就可以成功运行了。

感谢，第一步之前处理了，发现存在一些瑕疵，原来是少了第二步。

**Comment by shruckCode** [comment]
可以在 **.storybook/preview.js** 中加入装饰器：
```
import React from "react";
import { addDecorator } from "@storybook/react";
import { window } from "@tarojs/runtime";
import "@tarojs/components/dist/taro-components/taro-components.css";
import {
  defineCustomElements,
  applyPolyfills,
} from "@tarojs/components/loader";

addDecorator((storyFn) => {
  applyPolyfills().then(function () {
    defineCustomElements(window);
  });

  return storyFn();
});

```  
然后在创建组件的的index.js文件中将原来
**import { View } from ‘@tarojs/components’   变成   import { View } from 'import { View } from "@tarojs/components/dist-h5/react"**，就可以使用storybook开发taro组件了，不过有时会报core-js包缺少，记得安装**npm i core-js**
