### ISSUE TITLE
[小程序] 关于场景值获取

### ISSUE THREAD

**Issue by dogbutcat** [NervJS/taro#733]
现在遇到一个需求，想获取到小程序的场景值，根据小程序官方描述从onLoad里面取，onLoad对应Taro的componentWillMount，但是目前好像各种打印获取不到场景值，我想问下Taro里面怎么获取小程序的场景值
### UPDATE:
单层打印之后 发现只是在最外层的App.js中的<code>this.$router.params</code>存在，代码结构如下
```
class App extends Component{ // 此处
        render(){
           return (
                <Index/> // Index内部无法打印
            )
        }
}
Taro.render(<App/>, document.getElementById(app))
```
参数输出见下图
![wx20180928-223934](https://user-images.githubusercontent.com/8625449/46241484-7108fa00-c36f-11e8-92b4-440f57f9ceb4.png)

**Comment by ldwonday** [comment]
`js
let scene = this.$router.params.scene
    if (scene) {
      scene = decodeURIComponent(scene)
    }
`

**Comment by dogbutcat** [comment]
@ldwonday 最开始看完小程序文档也是这么拿的 但发现在除app.js的页面外其他怎么都拿不到 你这边没问题么？

**Comment by luckyadam** [comment]
@dogbutcat 我觉得你理解错了，你问题中的场景值是小程序定义的值，根据小程序文档，只能在 app launch 时获取
https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/scene.html

![image](https://user-images.githubusercontent.com/1782542/46242358-b7576b00-c3fa-11e8-8791-ef1644686b91.png)

**Comment by dogbutcat** [comment]
@luckyadam 根据 [获取二维码](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/qr-code.html) 的B类型接口的描述是把参数传scene里，官方文档上写了
>**获取 scene 值**
scene 字段的值会作为 query 参数传递给小程序/小游戏。用户扫描该码进入小程序/小游戏后，开发者可以获取到二维码中的 scene 值，再做处理逻辑。
调试阶段可以使用开发工具的条件编译自定义参数 scene=xxxx 进行模拟，开发工具模拟时的 scene 的参数值需要进行 encodeURIComponent

(开发工具方式||调了官方接口生个码)也好，结果什么参数都拿到，我开始怀疑B类型接口是不是这么用的了，冲着数量不受限制去的😂

**Comment by luckyadam** [comment]
@dogbutcat 生成的二维码你看看 app 里能拿到参数么

**Comment by ldwonday** [comment]
@dogbutcat scene就是我那样子获取的，我已经上线了项目，是没问题的。在调试的时候，可以在模拟上上设置scene=***。

**Comment by luckyadam** [comment]
@ldwonday 你是咋设置 scene 的，能不能截图我看下，我看看有没有这个问题~

**Comment by dogbutcat** [comment]
![wx20180929-004259](https://user-images.githubusercontent.com/8625449/46242699-a407b980-c380-11e8-8963-5c0513b565cc.png)
@ldwonday 请问你开发工具上是配这里的么 我输进去scene=xyz点击ok之后拿不到值  输parameter
调接口是根据文档上描述返回图片了
``` restful
@baseUrl = https://api.weixin.qq.com
POST {{baseUrl}}/wxa/getwxacodeunlimit?access_token={{login.response.body.$.access_token}}
Content-Type: application/json

{"scene":"bbbb"}
```
这样你看有问题么 按官方说法没问题的话就会返回码的

**Comment by dogbutcat** [comment]
### Result
果然B接口要上线之后才可以获取到值！如：`{"scene":"bbbb"}`，竟然不给测试的机会，官方只说了路径要上线才可以，而且只给scene也能生成码，坑……😅

**Comment by jimmy2012** [comment]
@dogbutcat 你好，你最后指定页面扫码进入获取scene值是采用this.$router.params.scene获取的吗？

**Comment by dogbutcat** [comment]
@jimmy2012 这个太久了有点忘了……应该是上面那段代码
```js
    let scene = this.$router.params.scene;
    if (scene) {
      scene = decodeURIComponent(scene);
    }
```
你现在是取不到值么？

**Comment by jimmy2012** [comment]
没问题了，是后台生成二维码时参数设置的问题。感谢，🙏！
