### ISSUE TITLE
Taro3.0.7   Taro UI 官方模板体积超过限制了

### ISSUE THREAD

**Issue by dq77** [NervJS/taro#7331]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/dq77/caixiao](https://github.com/dq77/caixiao)
**小程序基础库: 2.4.4**
**使用框架: React**

### 复现步骤
1. Taro init myApp 创建项目并选择Taro UI模板，
2. 执行yarn dev:weapp，
3. 点击开发者工具中的预览按钮。
提示体积过大无法预览。

### 期望结果
小一点，现在太大了，
期望像Taro1.0时候那样短小精悍。

### 实际结果
现在连基础模板都超过限制了，已经无法通过分包解决了。
目前设置成生产环境可以解决，但是报错信息根本就看不懂了。
希望梦回Taro1.0的体积

### 环境信息
```
Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.7 => 3.0.7 
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
```

---
### 补充信息
要不实在不行，就把React加回来吧，现在把他拆出去了，反而体积更大了。以后Taro越来越大，那是不是就要放弃微信小程序的市场了？

**Comment by honlyHuang** [comment]
可以通过添加环境变量的方式预览，如  `NODE_ENV=production taro build --type weapp --watch` ，这样包大小就会降下来了咯。
![image](https://user-images.githubusercontent.com/3080820/90117099-060d1480-dd89-11ea-8eb2-333f051d7d7a.png)

![image](https://user-images.githubusercontent.com/3080820/90117015-e7a71900-dd88-11ea-967b-89a5ee6c0c1a.png)

**Comment by 349989153** [comment]
你跑yarn dev:weapp可不就大么？

跑yarn build:weapp然后再预览试试看

**Comment by shenghanqin** [comment]
> 你跑yarn dev:weapp可不就大么？
> 
> 跑yarn build:weapp然后再预览试试看

但还是要解决包太大的问题呀。

**Comment by 349989153** [comment]
> > 你跑yarn dev:weapp可不就大么？
> > 跑yarn build:weapp然后再预览试试看
> 
> 但还是要解决包太大的问题呀。

不太懂，我的业务代码 + taro ui + 一些第三方库，build:weapp之后是1.8M，小于小程序的2M，可以随意预览/上传。

可以预览和上传也算大么，那多小算小

**Comment by shenghanqin** [comment]
> > > 你跑yarn dev:weapp可不就大么？
> > > 跑yarn build:weapp然后再预览试试看
> > 
> > 
> > 但还是要解决包太大的问题呀。
> 
> 不太懂，我的业务代码 + taro ui + 一些第三方库，build:weapp之后是1.8M，小于小程序的2M，可以随意预览/上传。
> 
> 可以预览和上传也算大么，那多小算小

我认为5个页面，3个组件，不放image的情况下，控制在1m-1.2M才比较合理。1.8M是很危险的，稍微再多加点别的东西就超过2M了。

**Comment by rottenpen** [comment]
@shenghanqin 现在体积确实大，按3.x的架构很难去优化体积，因为运行时需要引入 react 相关的依赖。

**Comment by shenghanqin** [comment]
> @shenghanqin 现在体积确实大，按3.x的架构很难去优化体积，因为运行时需要引入 react 相关的依赖。

只能叹个气呀。我其实都是手写css的，没有引入taro ui，再加上没几个页面，在打包后500k吧

**Comment by crazyll** [comment]
taro+taro-ui+一些基础库，直接压缩打包就1.8M了。写了一个详情页直接2k。完全接受不了。

**Comment by melochale** [comment]
我的production编译的都是2.3MB大小了，之前1.x版本只有1.5MB，我把taro-ui 3.x去掉测试一下，只有1.8MB了，看来真的是它的锅？

**Comment by dreamthen** [comment]
@shenghanqin 如果不用react framework配置，还用之前的nerv配置呢？应该跟之前一样的吧？😆

**Comment by dreamthen** [comment]
优化体积主base.wxml页面之后，感觉还是没有2.x的香啊，还是退回了2.x

**Comment by pecopeco** [comment]
> 我的production编译的都是2.3MB大小了，之前1.x版本只有1.5MB，我把taro-ui 3.x去掉测试一下，只有1.8MB了，看来真的是它的锅？

1.8也已经非常危险了，随便再加个什么都心惊胆战
