### ISSUE TITLE
微信开发者工具中发现的问题

### ISSUE THREAD

**Issue by jenerse** [NervJS/taro#7342]
在更新3.0.5之后，发现在开发者工具中的结构多了很多属性，之前是不会这样的，而且很多属性我都没有设置，看起来十分不舒服，请问这个有办法解决吗？

![image](https://user-images.githubusercontent.com/4142224/90211730-1de5a680-de24-11ea-8fbe-d20fa6b5149a.png)

希望能简洁一些，以前版本还是2的时候就不会，不然看起来很累。
![image](https://user-images.githubusercontent.com/4142224/90211800-4f5e7200-de24-11ea-86a6-1c125d596d0d.png)

**Comment by shenghanqin** [comment]
@jenerse 3.x版本的特点就是重构了模板系统吧，这里就很难分析。我现在为了让这部分清晰一些，还在用2.x

**Comment by xinggangling** [comment]
> @jenerse 3.x版本的特点就是重构了模板系统吧，这里就很难分析。我现在为了让这部分清晰一些，还在用2.x

taro封装了小程序事件，所以看到的所有事件都有eh，eventHandle的简称，模板只是为了实现运行时，优化diff，在render的时候都还没有真正的render，和react一样taro有个root，setData就是setData虚拟dom，或者更新的虚拟dom路径

**Comment by jenerse** [comment]
@shenghanqin 感觉3.x刚出，升级还是要慎重。。问题还是很多呀。。

**Comment by jenerse** [comment]
@xinggangling 好。那意思是3.x taro绑定了一个默认的事件？那意思是没有办法优化吗？

**Comment by xinggangling** [comment]
> @xinggangling 好。那意思是3.x taro绑定了一个默认的事件？那意思是没有办法优化吗？

这个是 可以解决的，可能比较麻烦吧，taro得动态生成模板，现在是写死的；优化空间还是比较大的，例如在开发环境，编译出来的taro.js里面有很多重复的代码，taro3还比较新，得耐心等待；反正taro3比taro2好太多，主要是diff上的优化处理得好；我们升级的taro3项目准备要上线了，哈哈；taro2可以说是残废的react，很恶心的，建议你还是升级吧

**Comment by xinggangling** [comment]
> @shenghanqin 好。那意思是3.x taro绑定了一个默认的事件？那意思是没有办法优化吗？

这个是 可以解决的，可能比较麻烦吧，taro得动态生成模板，现在是写死的；优化空间还是比较大的，例如在开发环境，编译出来的taro.js里面有很多重复的代码，taro3还比较新，得耐心等待；反正taro3比taro2好太多，主要是diff上的优化处理得好；我们升级的taro3项目准备要上线了，哈哈；taro2可以说是残废的react，很恶心的，建议你还是升级吧

**Comment by jenerse** [comment]
@xinggangling 是的，3.x最舒服的就是写代码，不会像2.x那样这么多限制，但问题还是比较多。我发现有些issue历史还比较久了。希望快点更新和修复吧。

**Comment by Chen-jj** [comment]
小程序不支持动态增加属性，目前只能把他们都全部写出来。

关于属性精简，在 [RFC](https://github.com/NervJS/taro-rfcs/blob/optimize-templates-size/rfcs/0000-optimize-template-size.md) 里有提及（可能会增加一个危险的配置项），可以在那边讨论。
