### ISSUE TITLE
[Feature Request] dev:weapp 或 build:weapp 时保留 project.config.json

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#735]
现在每次 `dev:weapp` 或 `build:weapp` 时都会清空 `dist` 目录，这样 项目配置文件（`project.config.json`）也被删了，之前的项目配置就全没了，项目配置文件还是很有用的，特别是编译模式。

希望能改进下，可以保留这个文件不删除，或者复制到别的地方，等清空完再粘贴回来。

**Comment by dogbutcat** [comment]
请把文件放在项目根目录下, 打包时会尝试读取项目根目录的<code>project.config.json</code>文件并输出到目标目录

**Comment by vimcaw** [comment]
但是我在开发者工具更新了配置后修改的是 `dist` 文件夹的 `project.config.json` 文件，现在每次运行`dev:wepp` 我都要手动把`dist`文件夹里的`project.config.json` 文件复制到根目录，很麻烦，希望能改进一下。

**Comment by dogbutcat** [comment]
可以实现的，你可以修改project.config.json里面的miniprogramRoot配置到你的输出目录，然后以项目根目录打开就可以了，具体参考小程序的项目配置文件[project.config.json](https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html?search-key=project.config.json)
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vimcaw** [comment]
原来还有这个配置，非常感谢！👍
