### ISSUE TITLE
taro 项目初始化时报错

### ISSUE THREAD

**Issue by mobaibai** [NervJS/taro#7354]
(node:66144) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/share/.config/yarn/global/node_modules/@tarojs/cli/templates/taro-temp'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Chen-jj** [comment]
权限问题，自行 google 解决吧
