### ISSUE TITLE
Vue 方式 如何引用原生组件?

### ISSUE THREAD

**Issue by zjxpcyc** [NervJS/taro#7355]
没有找到文档的说明。官网文档包括示例都是 React 版本的

例外，我自己增加 index.config.js 与组件内部写 config 属性都不行

**Comment by zjxpcyc** [comment]
自己摸索解决了。
解决方案如下：

1.  组件内不能写 index.config.js 写了没用。只能页面写

2.  不能全局(`app.config.js`)加 `usingComponents` , 加了也没用

3.  必须设置编译  `copy` 参数, 拷贝原生组件内容

4.  以上步骤完成，就可以封装组件了。组件内直接使用原生组件

5.  最终使用的页面，比如封装组件 `Foo`  , 最终被页面 `PageA` 使用，那么 `PageA` 下面必须有 `usingComponents`

**Comment by lisiyizu** [comment]
@zjxpcyc  https://taro-docs.jd.com/taro/docs/vue
