### ISSUE TITLE
请教：混合框架开发：在不入侵原有项目（原生小程序框架）的情况下，使用Taro Next开发新模块

### ISSUE THREAD

**Issue by JoviCheng** [NervJS/taro#7370]
### 这个特性解决了什么问题？
项目模块繁多，一次性转换为Taro成本过高，有没有什么方法可以在混合框架开发，在不入侵原有项目（原生小程序框架）的情况下，使用Taro Next开发新模块呢？

### 这个 API 长什么样？
提供一种实现的Example可以参考的~

**Comment by rottenpen** [comment]
可以看我的方案[小程序使用 Taro 和原生混合开发方案的探索](https://mp.weixin.qq.com/s/ZsVG-t5aBnCfm6SUi9S9lw)
[插件地址](https://github.com/Kujiale-Mobile/changeAppJsonPlugin)

**Comment by JoviCheng** [comment]
> 可以看我的方案[小程序使用 Taro 和原生混合开发方案的探索](https://mp.weixin.qq.com/s/ZsVG-t5aBnCfm6SUi9S9lw)
> [插件地址](https://github.com/Kujiale-Mobile/changeAppJsonPlugin)

感谢，马上去拜读下！

**Comment by Chen-jj** [comment]
Duplicate of #7191

**Comment by Chen-jj** [comment]
https://taro-docs.jd.com/taro/docs/taro-in-miniapp/
