### ISSUE TITLE
有办法让h5的首页默认为 / 吗？

### ISSUE THREAD

**Issue by gcxfd** [NervJS/taro#7375]
### 这个特性解决了什么问题？
有办法让h5的首页默认为 / 吗？进来就是一长串url感觉不是很友好。

### 这个 API 长什么样？
如果有办法做一些hook就好了，但是没搞清楚如何去做，能给一些提示吗？

ps ： taro的logo有svg版本吗？没找到

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/config-detail/#h5routercustomroutes
用这个配置一下吧

**Comment by remember-5** [comment]
在`config/prod.js`中配置
```js
module.exports = {
  ...
  h5: {
    router:{
      mode:'hash',
      customRoutes: {
        '/pages/index/index': '/'
      }
    }
  }
}




```
