### ISSUE TITLE
Taro.uploadFile根本不支持fileName参数

### ISSUE THREAD

**Issue by 349989153** [NervJS/taro#7377]
### 相关平台
H5

**浏览器版本: Chrome 版本 84.0.4147.105**
**使用框架: React**

### 复现步骤
**这是Taro文档的截图，显示Taro.uploadFile的options支持fileName：**
![Taro-bug](https://user-images.githubusercontent.com/10381674/90600906-eadb5280-e229-11ea-9bd3-5b1b92437c83.jpg)

**这是../node_modules/@tarojs/taro-h5/src/api/fileTransfer/uploadFile.js的截图，根本没有fileName这个参数：**
![Taro-bug2](https://user-images.githubusercontent.com/10381674/90601007-15c5a680-e22a-11ea-9018-cbffc8b68eb0.jpg)

taro-h5的package.json：
  "name": "@tarojs/taro-h5",
  "version": "3.0.7",

### 期望结果
Taro.uploadFile的options支持fileName

### 实际结果
Taro.uploadFile的options设置了fileName根本毫无作用

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 

```

**Comment by remember-5** [comment]
同3.0.7版本的h5，我是这样使用的，希望能帮到你
```js
Taro.uploadFile({
      url: BASE_URL + url,
      name: "file",
      filePath: filePath
})
```

查看源码(`node_modules/@tarojs/taro/types/api/network/upload.d.ts`)如下图，
![image](https://user-images.githubusercontent.com/31730796/90610526-20873800-e238-11ea-84c4-ad6e53fda826.png)

**Comment by 349989153** [comment]
@remember-5 你好，感谢你的帮助。

但是name和fileName不是一个东西。name是formData的字段名，fileName是formData里面的filename属性。用你贴的代码举例，就好像是
{
  file: { size: 4000, filename: 'a.jpg' }
}
的感觉。

我们后端服务器设置比较特殊，必须得有fileName，所以才发现这个问题

**Comment by remember-5** [comment]
@349989153 非专业前端，受教了🤝
