### ISSUE TITLE
3.0.5编译H5报错  ，配置 localIdentName出错

### ISSUE THREAD

**Issue by cdd111** [NervJS/taro#7380]
### 相关平台
H5

**浏览器版本: 微信开发者工具 版本1.03.2006090**
**使用框架: React**

### 复现步骤
在h5下配置
cssLoaderOption: {
    //   localIdentName:' [path][name].[hash:base64]'
    // },

### 期望结果
编译不出错

### 实际结果
编译出错，报错如下：

Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }

error Command failed with exit code 1.

### 环境信息
```
👽 Taro v3.0.5

------------------------------------------------
undefined
------------------------------------------------

  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.2 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^3.0.5 => 3.0.7 
      @tarojs/mini-runner: ^3.0.5 => 3.0.7 
      @tarojs/react: ^3.0.5 => 3.0.7 
      @tarojs/runtime: ^3.0.5 => 3.0.7 
      @tarojs/taro: ^3.0.5 => 3.0.7 
      @tarojs/webpack-runner: ^3.0.5 => 3.0.7 
      babel-preset-taro: ^3.0.5 => 3.0.7 
      eslint-config-taro: ^3.0.5 => 3.0.7 
      react: ^16.13.1 => 16.13.1
```

**Comment by Chen-jj** [comment]
@cdd111 你参数写错了，少套了一层 `modules` ：https://github.com/webpack-contrib/css-loader

![image](https://user-images.githubusercontent.com/11807297/98226168-a346a600-1f90-11eb-80d5-4044931ac117.png)
