### ISSUE TITLE
使用Nerv导致Input的focus失效

### ISSUE THREAD

**Issue by qaqslzy** [NervJS/taro#7383]
### 相关平台
微信小程序

### 复现仓库
[https://gitlab.com/qaqs/input-focus-in-nerv/-/tree/master](https://gitlab.com/qaqs/input-focus-in-nerv/-/tree/master)
**小程序基础库: 2.12.1**
**使用框架: Nerv**

### 复现步骤
无论是预览项目还是模拟器表现，input均无法自动获取焦点。
同样的代码在React上表现是正常的。

### 期望结果
input可以获取焦点

### 实际结果
input无法获取焦点

### 环境信息
```
👽 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      nervjs: 1.5.7 => 1.5.7 

```

---
### 补充信息
测试代码为 `<Input focus value='123'></Input>`

**Comment by cuiyajie** [comment]
@Chen-jj ,发现在 Nerv 环境下bool类型属性都不起作用，这个Input的focus属性，Video的controls属性，还有LivePusher的enableCamera属性之类的，相关Issue #7427
