### ISSUE TITLE
自定义组件传递函数名称，子组件获取为undefined

### ISSUE THREAD

**Issue by sunhaikuo** [NervJS/taro#739]
**问题描述**
向自定义组件中，传入引入函数的name，子组件在componentDidMount里通过props取到为undefined
影响范围：小程序，H5正常

**复现步骤**
#### 说明：
组件：child.tsx为自定义组件
组件：parent.tsx为父组件，引用child.tsx
函数库：util.ts，里面定义test1Fn和test2Fn两个函数
#### 代码
+ util.ts
```
export default {
  test1Fn: function() {},
  test2Fn: function() {},
};
```
+ child.tsx
```
componentDidMount() {
    console.log('fns', this.props.fns);
  }
```
+ parent.tsx
```
import Child from './child';
import util from '../../helpers/util';

情况1：<Test fns={test.test1Fn.name} />
情况2：<Test fns={[test.test1Fn.name, test.test2Fn.name ]} />
情况3：<Test fns={[test.test1Fn.name, 'Hello' ]} />
情况4：<Test fns={[test.test1Fn.name, {}]} />

```
#### 结果
情况1：undefined
情况2：[undefined, undefined]
情况3：[undefined, 'Hello']
情况4：['test1Fn', {}]
发现：只要带引用类型，函数名称就可以打印出来

**期望行为**
可以把fnName以字符形式带过来

**报错信息**
![image](https://user-images.githubusercontent.com/11194712/46240609-d21ae700-c3dc-11e8-9ec2-efe350525cd5.png)

**系统信息**

 - 操作系统: macOS 10.13.6
 - Taro 版本 v.1.0.5
 - Node.js 版本 v8.11.3

**补充信息**
旧版本也存在这个问题，今天升级的1.0.5问题也存在

**Comment by yuche** [comment]
```
const fn1Name = test.test1Fn.name
<Test fns={fn1name} />
```
这样应该可以。

当你使用前三钟方式传递的时候，taro 实际上会把 `test` 这个对象放到小程序的 `data` 中。但这个对象会被微信序列化掉，因此内容就丢失了。
第四种情况会生成一个新的数组，这个数组是在放入 `data` 之前就已经求值了，所以能正常显示。
