### ISSUE TITLE
如何获取微信原生第三方组件的实例

### ISSUE THREAD

**Issue by luxiaojie322** [NervJS/taro#7391]
### 这个特性解决了什么问题？
调用微信原生第三方组件实力上的方法，如图片裁剪组件的获取裁剪图片的方法

### 这个 API 长什么样？
微信原生的获取方式： this.cropper = this.selectComponent("#image-cropper")

**Comment by rottenpen** [comment]
暂时用 getCurrentPages()[0] 代替 this 看行不行？

**Comment by allendongyx** [comment]
我来顶你一下，我也不行

**Comment by JX-Zhuang** [comment]
我来顶你一下，我也不行

**Comment by JX-Zhuang** [comment]
> 暂时用 getCurrentPages()[0] 代替 this 看行不行？

不行

**Comment by allendongyx** [comment]
@JX-Zhuang 
const _cropRef = getCurrentInstance().page.selectComponent(
          '#image-cropper'
        )

通过这种方式来获取

**Comment by Chen-jj** [comment]
楼上正解，文档：https://taro-docs.jd.com/taro/docs/hybrid#selectcomponent

**Comment by soneway** [comment]
> @JX-Zhuang
> const _cropRef = getCurrentInstance().page.selectComponent(
> '#image-cropper'
> )
> 
> 通过这种方式来获取

这个可以么, taro 3.3.8 取不到, 始终是null
