### ISSUE TITLE
Taro.env返回undefined 导致无法获取USER_DATA_PATH

### ISSUE THREAD

**Issue by ILoveChy** [NervJS/taro#7392]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/ILoveChy/issuesDemo](https://github.com/ILoveChy/issuesDemo)
**小程序基础库: 2.12.1**
**使用框架: React**

### 复现步骤
随便一个地方输入Taro.env 都是undefined

### 期望结果
Taro.env可以获取到

### 实际结果
undefined

### 环境信息
```
Taro v3.0.7

Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.7 - D:\Program Files\nodejs\npm.CMD
```

**Comment by leo43555483** [comment]
这问题怎么解决？

**Comment by Mochen07** [comment]
更新Taro相关依赖 -> 暂时无法获取
使用`wx.env.USER_DATA_PATH` 无需任何引入直接编译可解决问题
