### ISSUE TITLE
ScrollView新增enhanced特性

### ISSUE THREAD

**Issue by szm1002** [NervJS/taro#7393]
### 这个特性解决了什么问题？
微信小程序scroll-view官方文档：https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html

小程序scroll-view新增了一些enhanced特性，包括showScrollbar/binddragstart/binddragging/binddragend等属性，希望Taro能加上支持。

### 这个 API 长什么样？
enhanced/showScrollbar/onDragStart/onDragging/onDragEnd, etc

**Comment by shenghanqin** [comment]
挺好，俺也想知道

**Comment by xiaoyuze88** [comment]
Taro不认识的属性竟然不透传，我也是服了，enhanced 什么时候能加上？处理不了就直接透传不行吗
