### ISSUE TITLE
taro-cli新建项目，build总缺少依赖库

### ISSUE THREAD

**Issue by monkeyDledger** [NervJS/taro#740]
通过taro-cli init的项目，cnpm安装所有依赖后。build:h5直接报缺少依赖：
module.js:487
    throw err;
    ^

Error: Cannot find module 'rimraf'
...

手动安装rimraf后，依然报这个错

**Comment by luckyadam** [comment]
确定依赖装好了么

**Comment by monkeyDledger** [comment]
@luckyadam 后来发现不是少安装package.json中依赖，是taro-cli编译命令的依赖缺少，全局安装rimraf后，问题解决了。

**Comment by luckyadam** [comment]
好嘞~ 确实，rimraf 是 taro-cli 的依赖
