### ISSUE TITLE
ts代码的正则，编译成js之后乱码

### ISSUE THREAD

**Issue by sunhaikuo** [NervJS/taro#741]
+ ts中代码如下：
```
const regRule = /\uD83C[\uDF00-\uDFFF]|\uD83D[\uDC00-\uDE4F]/g;
```
+ 编译后的js代码如下：
```
const regRule = /�[�-�]|�[�-�]/g;
```
![image](https://user-images.githubusercontent.com/11194712/46240960-e31a2700-c3e1-11e8-9205-ec9e9cc0b0d4.png)

**Comment by luckyadam** [comment]
close via d97d0dc7fc6a1d312b3d59c80a3de402392a89cd
