### ISSUE TITLE
version3.0.7中通过「普通链接」打开小程序以后，无法获取到「普通链接」地址中携带的QueryString（查询参数）

### ISSUE THREAD

**Issue by ZhaoTim** [NervJS/taro#7429]
### 相关平台
微信小程序

**小程序基础库: IOS 7.0.13**
**使用框架: React**

### 复现步骤
在最外层`app.tsx`文件中（非pages/index/index文件）:
```jsx
class Com extends React.Component
  componentWillMount() {
    console.log(this.$router)
  }
}
```
输出为undefined。

### 期望结果
希望可以拿到普通链接地址。

### 实际结果
undefined

### 环境信息
```
Taro v3.0.7
Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha => 3.0.0-alpha.3 
```

**Comment by ZhaoTim** [comment]
> 3.x 之后获取路由参数的方式改变了
> https://nervjs.github.io/taro/docs/router

麻烦问一下`getCurrentInstance().router` 与 小程序中的onLoad生命周期函数的参数options是等价的吗？
因为在Taro迁移指南中看到:
>聪明的读者已经猜到了，getCurrentInstance().router 其实是访问小程序当前页面 onLoad 生命周期参数的快捷方式。
想确认一下！

**Comment by ZhaoTim** [comment]
> 3.x 之后获取路由参数的方式改变了
> https://nervjs.github.io/taro/docs/router

文档中关于React生命周期介绍中: 
> onLoad(options)
> 页面创建时执行，此生命周期在小程序端对应小程序页面的 onLoad 生命周期。此生命周期可以访问 getCurrentInstance().router。

所以这可理解为options 等价于 小程序 onLoad生命周期函数的options吗？（不好意思，第一次用，问题有点多）

**Comment by C1erman** [comment]
@ZhaoTim 应当是不一致的，可以自己打开`vConsole`试试。把`getCurrentInstance().router`输出后与平时的`route`并无二致，不存在`options`属性，参数请在`params`中获取。
```
let { q } = getCurrentInstance().router.params;
```
