### ISSUE TITLE
不支持 async 方法？

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#743]
**问题描述**
包含 async 方法时，控制台报错

**复现步骤**
[复现问题的步骤]
```js
async function f(){}
```

**期望行为**
正常运行

**报错信息**
![2018-09-29 3 20 38](https://user-images.githubusercontent.com/19544032/46242433-ba069000-c3fb-11e8-8b92-65717db59b27.png)

**系统信息**

 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.4]
 - Node.js 版本 [e.g. v10.0.0]

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/async-await.html
多看看文档

**Comment by jamieYou** [comment]
> https://nervjs.github.io/taro/docs/async-await.html
> 多看看文档

我是直接浏览 github 页面下的 readme，没留意到顶部的文档地址 😄

**Comment by luckyadam** [comment]
@jamieYou 确实，文档藏得有点深😂  我改下。。
