### ISSUE TITLE
编辑scss文件后, 头条小程序无任何样式变动, 微信小程序样式变动

### ISSUE THREAD

**Issue by twocucao** [NervJS/taro#7430]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/twocucao/toutiao-demo-css-missing/commit/d3c47f367150361b945dd8365c1db847daca5ac2](https://github.com/twocucao/toutiao-demo-css-missing/commit/d3c47f367150361b945dd8365c1db847daca5ac2)
**小程序基础库: 1.75**
**使用框架: React**

### 复现步骤
yarn build:tt 

### 期望结果
背景应该为黑色

### 实际结果
修改样式界面无任何变化

### 环境信息
```
👽 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v13.14.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7
      @tarojs/mini-runner: 3.0.7 => 3.0.7
      @tarojs/react: 3.0.7 => 3.0.7
      @tarojs/runtime: 3.0.7 => 3.0.7
      @tarojs/taro: 3.0.7 => 3.0.7
      @tarojs/webpack-runner: 3.0.7 => 3.0.7
      babel-preset-taro: 3.0.7 => 3.0.7
      eslint-config-taro: 3.0.7 => 3.0.7
      react: ^16.10.0 => 16.13.1
```

**Comment by ZhaoTim** [comment]
其实我只是想得到小程序的生命周期`onload`函数的参数 ->` options.q` 的值(也就是普通链接)，我通过查阅,getCurrentInstance().router可以得到路由信息，但是我也没看到`q`的存在,只有params对象的存在，params对象里会有`q`属性吗吗？这些问题该问谁？或许谁也不该问。

**Comment by Chen-jj** [comment]
demo 链接跪了

**Comment by twocucao** [comment]
@Chen-jj 重新升级之后没这个问题了.....
