### ISSUE TITLE
给组件添加 style={{ opacity: 0 }} 时，为何未被编译到代码中？

### ISSUE THREAD

**Issue by puxiao** [NervJS/taro#7431]
### 相关平台
微信小程序

**小程序基础库: 2.12.1**
**使用框架: React**

### 复现步骤
```
import React from 'react'
import { View } from '@tarojs/components'

interface MyViewProps {
    checked?: boolean
}

const MyView: React.FC<MyViewProps> = ({ checked = false }) => {
    checked
    return (
        <View>
            <View style={{ opacity: 0 }}>AAA</View>
            <View style={{ opacity: 1 }}>BBB</View>
        </View >
    )
}

export default MyView
```
> 以上执行后的结果是 AAA 和 BBB  都会显示出来，AAA 之所以会显示出来，经检查源码，发现编译后的 <view\>中并没有 style="opacity:0" ，Taro 并未编译 style={{ opacity: 0 }}。

### 期望结果
期望AAA对应的<view\> 上面应该有属性 style="opacity:0"

### 实际结果
实际上AAA对应的<view\> 上面并没有属性 style="opacity:0"

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - D:\program files (x86)\nodejs\node.EXE
      npm: 6.14.5 - D:\program files (x86)\nodejs\npm.CMD   
```

---
### 补充信息
虽然我搜索到一些文章提到：微信部分组件不支持 opacity:0，但是本人实际测试，手工给 <view\> 添加 style="opacity:0" 是会生效的(透明度为0)。我认为无论微信小程序组件是否支持 opacity:0 ，那是微信的事情，但 Taro 都应该把 style={{ opacity: 0 }} 编译上去。

**Comment by luckyadam** [comment]
暂时可以写 
`<View style={{ opacity: '0' }}>AAA</View>`
来绕过这个问题
