### ISSUE TITLE
taro-axios 经过 terser 压缩导致 post 请求失败

### ISSUE THREAD

**Issue by lastSeries** [NervJS/taro#7432]
### 相关平台
微信小程序

### 复现仓库
[https://codepen.io/lastSeries/pen/vYGxYRK](https://codepen.io/lastSeries/pen/vYGxYRK)
**小程序基础库: 2.12.1**
**使用框架: React**

### 复现步骤

npm run build:weapp

### 期望结果
![1598316841291](https://user-images.githubusercontent.com/20902974/91113615-9bc56f80-e6b8-11ea-9433-8ec1c6f377b9.jpg)
k1=v1&k2=v2&k3=v3

### 实际结果
![1598316983487](https://user-images.githubusercontent.com/20902974/91113622-9d8f3300-e6b8-11ea-818b-7a410875957d.jpg)

{"postData":{"k1":"v1","k2":"v2","k3":"v3"}}

### 环境信息
```
  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.5 => 3.0.5 
      @tarojs/mini-runner: 3.0.5 => 3.0.5 
      @tarojs/react: 3.0.5 => 3.0.5 
      @tarojs/runtime: 3.0.5 => 3.0.5 
      @tarojs/taro: 3.0.5 => 3.0.5 
      @tarojs/webpack-runner: 3.0.5 => 3.0.5 
      babel-preset-taro: 3.0.5 => 3.0.5 
      eslint-config-taro: 3.0.5 => 3.0.5 
      react: ^16.10.0 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.5.2
```

**Comment by Chen-jj** [comment]
@lastSeries 是 `taro-axios` 这个包依赖的 `axios` 的版本的问题。

axios 里使用 `data.toString() === '[object PostData]'` 去判断是否是一个 `PostData` 对象，但压缩后 `PostData` 类名被压缩了，导致判断失败：

![image](https://user-images.githubusercontent.com/11807297/105962327-a5fdf680-60ba-11eb-98f2-430486081afb.png)

![image](https://user-images.githubusercontent.com/11807297/105962499-de053980-60ba-11eb-80db-969e0d6acf5f.png)

可以升级 axios 版本再试试。
