### ISSUE TITLE
CoverView无法覆盖video组件

### ISSUE THREAD

**Issue by 15152929190** [NervJS/taro#7441]
<Video 
                id="myVideo" 
                src="http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400" 
                >
                    <CoverView className="cover-view">
                        123123123
                    </CoverView>
                </Video>
taro版本: 3.0.5

**Comment by luckyadam** [comment]
看上去是小程序自己的问题

**Comment by Chen-jj** [comment]
Taro 中 `video` 组件目前不允许有子元素，你可以弄个同层的 `CoverView` 去覆盖

**Comment by Yforward** [comment]
@Chen-jj ”Taro 中 video 组件目前不允许有子元素，你可以弄个同层的 CoverView 去覆盖“ 在进入全屏的时候ios可以显示CoverView 而安卓手机在全屏状态下不显示CoverView，这个怎么处理
