### ISSUE TITLE
使用小程序原生wxss，@import引入的文件中的px不会转化为rpx

### ISSUE THREAD

**Issue by Ariskywi** [NervJS/taro#746]
**问题描述**
taro转小程序时，a.wxss文件 中@import 的 b.wxss文件中的px，不会被转为rpx。只有修改再保存后才会转化。

**复现步骤**
1、page/路径下新建页面details.js、details.wxss、details.wxml、details.json

details.js
```js
const app = getApp()
Page({
  data: {},
  customData: {},
  onLoad: function () {},
  onReady: function () {}
})
```
details.wxml
```js
<import src="../../templates/test.wxml" />
<view class='details'>
  <template is="list" ></template>
</view>
```
details.wxss
```js
@import "../../templates/test.wxss";
```
details.json
```js
{
  "navigationBarBackgroundColor": "#ffffff",
  "navigationBarTextStyle": "black",
  "navigationBarTitleText": "详情",
  "backgroundColor": "#eeeeee",
  "backgroundTextStyle": "light"
}
```

2、src/templates/下新建test.wxml和test.wxss

test.wxml
```js
<template name="list">
    <text class="boldFont">这是一段测试文本</text>
</template>
```

test.wxss
```js
.boldFont{
  font-weight: bold;
  font-size: 36px;
}
```

3、app.js中配置
```js
pages: [
      'pages/details/details',
      'pages/index/index'
    ],
```

4、config/index.js增加配置
```js
copy: {
    patterns: [
      { from: 'src/templates/', to: 'dist/templates/' },
    ]
  },
```

5、启动应用 npm run dev:weapp

6、小程序查看font-size为36px

**期望行为**
test.wxss中的px转为rpx

**报错信息**

无报错。

**系统信息**

 - 操作系统: windows 7
 - Taro 版本 1.0.5
 - Node.js 版本 8.11.4
-微信开发者工具版本： v1.02.1809260 

**补充信息**
可修复的动作：
修改test.wxss中的任意内容，然后保存
```js
.boldFont{
  font-weight: bold;
  font-size: 36px;
 width: 100%;
}
```
保存。页面正常转为rpx了。
复现： 结束 npm run dev:weapp，再次运行npm run dev:weapp，则可再次复现。

心塞 - -

**Comment by Ariskywi** [comment]
@luckyadam 请问这个问题下个版本会修复吗？

**Comment by luckyadam** [comment]
@Ariskywi 会的，正在处理，目前可以通过在 js 中`import` 这个 `wxss` 文件来解决

**Comment by Ariskywi** [comment]
@luckyadam 

版本v1.2.15
此问题还在
每次重新打开环境样式就乱了。。求支持

**Comment by Ariskywi** [comment]
> @Ariskywi 会的，正在处理，目前可以通过在 js 中`import` 这个 `wxss` 文件来解决

js中import好像也不起作用
