### ISSUE TITLE
taro3版本希望能够支持微信小程序下面的原生 taro的混合开发

### ISSUE THREAD

**Issue by wuyanwen** [NervJS/taro#7469]
### 这个特性解决了什么问题？
在微信小程序下，解决了现有项目可以有部分页面使用taro3开发，而不是需要整个小程序重构成taro3成本太大。，之前taro1.x是可以的，希望3.x也可以加入此功能。

### 这个 API 长什么样？
希望taro3的API能够支持在微信小程序下面的混合开发的配置。

**Comment by vdfor** [comment]
现在也可以啊

**Comment by wuyanwen** [comment]
> 现在也可以啊

不可以的，我的意思是之前用微信小程序原生写的页面，部分用taro3来写，之前taro1.x可以，因为可以设置，weapp 部分，我们把 appOutput 设置成 false, 这样就不会生成 app.js、app.json、app.wxss 三个文件了。3.x确实不可行，你可以验证下。

**Comment by vdfor** [comment]
> > 现在也可以啊
> 
> 不可以的，我的意思是之前用微信小程序原生写的页面，部分用taro3来写，之前taro1.x可以，因为可以设置，weapp 部分，我们把 appOutput 设置成 false, 这样就不会生成 app.js、app.json、app.wxss 三个文件了。3.x确实不可行，你可以验证下。

这种是不可以

**Comment by Chen-jj** [comment]
未来可以考虑一下，但短时间内不够人力实现了。

**Comment by Chen-jj** [comment]
Duplicate of #7370

**Comment by goldEli** [comment]
> 未来可以考虑一下，但短时间内不够人力实现了。

你好 请问排上日程了吗？

**Comment by Chen-jj** [comment]
@goldEli 已经支持了：https://taro-docs.jd.com/taro/docs/taro-in-miniapp/
