### ISSUE TITLE
能不能实现一个类似wepy preload和onPrefetch的方法

### ISSUE THREAD

**Issue by wandiao** [NervJS/taro#747]
比如说this.$preload('preload', preloadData)

**Comment by Chen-jj** [comment]
已实现 preload，可以先于 beta 分支试用一下哈～[文档地址](https://nervjs.github.io/taro/docs/best-practice.html#%E9%A2%84%E5%8A%A0%E8%BD%BD)

**Comment by Songkeys** [comment]
请问一下 `componentWillPreload` 这个钩子支不支持在一个初始落地页做呢？
另外希望可以补充到生命周期这里 https://nervjs.github.io/taro/docs/tutorial.html#%E9%A1%B5%E9%9D%A2，感谢。

**Comment by luckyadam** [comment]
> @Chen-jj
> 请问一下 `componentWillPreload` 这个钩子支不支持在一个初始落地页做呢？
> 另外希望可以补充到生命周期这里 https://nervjs.github.io/taro/docs/tutorial.html#%E9%A1%B5%E9%9D%A2，感谢。

@Chen-jj

**Comment by Chen-jj** [comment]
@Songkeys 文档已补充。
这个钩子利用从页面A发起跳转，到落地页B onLoad 之间的这段延时，去做一些 preload 的工作。因此不能在小程序初始页做。
