### ISSUE TITLE
wx-open-launch-weapp  h5无法使用

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#7475]
### 相关平台
H5

**浏览器版本: Chrome 83**
**使用框架: React**

### 复现步骤
引入微信sdk 后wx.config  成功  使用开放标签  wx-open-launch-weapp  进行h5小程序跳转时点击无反应  无报错，wx.config的分享 api可以正常使用

### 期望结果
可以正常跳转

### 实际结果
点击无反应

### 环境信息
```
 Taro v1.3.39


  Taro CLI 1.3.39 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
h5需要打开小程序时

**Comment by shenghanqin** [comment]
俺也跟着看效果

**Comment by Junzibuzhengyibuqi** [comment]
renderImg = item => {
    const script = document.createElement('script');
    script.type = 'text/wxtag-template';
    const image = item.imageLink;
    script.text = `<div style="width:100%"> <Image src="${image}" width="100%" mode='widthFix'  /></div>`;
    const minPage = `${item.smallRoutineLink.split('?')[0]}.html?${
      item.smallRoutineLink.split('?')[1]
    }`.substring(1);
    const html = `<wx-open-launch-weapp style="width:100%;display:block;" username="gh_c22a5de0d1d9" path="${minPage}">${script.outerHTML}</wx-open-launch-weapp>`;

    return html;
  };


我是这么写的

**Comment by zcSkr** [comment]
请问一下wx-open-launch-weapp应该怎么写啊？我是用的2.x.x,
您的3版本下面是怎么写的呢？

**Comment by 100cm** [comment]
能用了吗？

**Comment by Junzibuzhengyibuqi** [comment]
> 能用了吗？

可以正常使用就行了

**Comment by Chen-jj** [comment]
可以用原生 H5 DOM API 操作 DOM 树，插入对应组件和注册事件试试。没有详细代码，我们定位不了。

**Comment by mxppxm** [comment]
> renderImg = item => {
> const script = document.createElement('script');
> script.type = 'text/wxtag-template';
> const image = item.imageLink;
> script.text = `<div style="width:100%"> <Image src="${image}" width="100%" mode='widthFix' /></div>`;
> const minPage = `${item.smallRoutineLink.split('?')[0]}.html?${ item.smallRoutineLink.split('?')[1] }`.substring(1);
> const html = `<wx-open-launch-weapp style="width:100%;display:block;" username="gh_c22a5de0d1d9" path="${minPage}">${script.outerHTML}</wx-open-launch-weapp>`;
> 
> ```
> return html;
> ```
> 
> };
> 
> 我是这么写的

大佬，这怎么用啊
