### ISSUE TITLE
taro3 与之对应的快应用平台版本

### ISSUE THREAD

**Issue by hlsky1988** [NervJS/taro#7477]
### 这个特性解决了什么问题？
希望明确的标识快应用支持的平台版本,在2.2.13中, 快应用 使用 rgba 和 hsl 颜色都会明确报错, hls 是 1040+  提供的功能, rgba 未知

### 这个 API 长什么样？
希望明确的标识快应用支持的平台版本

**Comment by Chen-jj** [comment]
你的意思是希望 Taro3 支持快应用，还是 Taro2 文档列明支持的快应用版本

**Comment by hlsky1988** [comment]
- 意思是 目前 Taro3 不支持 快应用吗?
- 文档能够列明支持的平台版本肯定是最好的了

**Comment by Chen-jj** [comment]
Taro3 目前还没支持快应用
