### ISSUE TITLE
createContext useContext ，可不可以不共享变量

### ISSUE THREAD

**Issue by allendongyx** [NervJS/taro#7484]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
```javascript
    // context.js
    const context = Taro.createContext({}) // 创建了一个上下文实例

    // wrap-a.js 页面A

    <Context.Provider value={{a = 1}}>
        <A />
    </Context.Provider>

    // wrap-b.js 页面B

    <Context.Provider value={{a = 2}}>
        <A />
    </Context.Provider>

     // A.js

     const { a } =  useContext(Context)
     // 希望在此页面中，wrap-a页面 和 wrap-b 页面 传递的上下文数据会通过页面独立，而不是共享数据，可以独立数据
     // 实际运行中，a的变量会受到影响，在路由切换时
   


### 期望结果
共享数据变量了

### 实际结果
希望虽然引入同一个Taro.createContext创建的上下文实例，但是数据的获取是从最近的Context.Provider获取的

### 环境信息
```
👽 Taro v2.2.13

  Taro CLI 2.2.13 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.21.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
    npmPackages:
      @tarojs/components: ^2.2.13 => 2.2.13 
      @tarojs/components-qa: 2.2.13 => 2.2.13 
      @tarojs/mini-runner: 2.2.13 => 2.2.13 
      @tarojs/plugin-sass: ^2.2.13 => 2.2.13 
      @tarojs/plugin-terser: ^2.2.13 => 2.2.13 
      @tarojs/plugin-uglify: ^2.2.10 => 2.2.10 
      @tarojs/redux: ^2.2.13 => 2.2.13 
      @tarojs/router: 2.2.13 => 2.2.13 
      @tarojs/taro: 2.2.13 => 2.2.13 
      @tarojs/taro-alipay: 2.2.13 => 2.2.13 
      @tarojs/taro-h5: 2.2.13 => 2.2.13 
      @tarojs/taro-qq: 2.2.13 => 2.2.13 
      @tarojs/taro-quickapp: 2.2.13 => 2.2.13 
      @tarojs/taro-rn: 2.2.13 => 2.2.13 
      @tarojs/taro-swan: 2.2.13 => 2.2.13 
      @tarojs/taro-tt: 2.2.13 => 2.2.13 
      @tarojs/taro-weapp: 2.2.13 => 2.2.13 
      @tarojs/webpack-runner: 2.2.13 => 2.2.13 
      eslint-config-taro: 2.2.13 => 2.2.13 
      eslint-plugin-taro: 2.2.13 => 2.2.13 
      nervjs: ^1.5.6 => 1.5.7 
      stylelint-config-taro-rn: 2.2.13 => 2.2.13 
      stylelint-taro-rn: 2.2.13 => 2.2.13 
      taro-ui: ^2.3.4 => 2.3.4 
```

<!-- generated by taro-issues. 请勿修改或删除此行注释 --><!--labels=T-weapp,V-2,F-react-->

**Comment by Chen-jj** [comment]
@allendongyx Taro 3 不存在这个问题，可以试试升级

**Comment by allendongyx** [comment]
![image](https://user-images.githubusercontent.com/11004093/91729675-7fa16100-ebd7-11ea-948a-43f5f340127a.png)

我补充一个截图，就像图上的写法

**Comment by allendongyx** [comment]
@Chen-jj  好的，taro-3 之前升级过了，遇到了引入原生小程序代码的坑，后来又退回去了

**Comment by allendongyx** [comment]
升级到taro 3.0.8 可以了，但是一堆坑，不过不打算退回，就继续用了，运行时的方案感觉好多了，本多react的hooks框架库都可以用了，比如unstate-next

**Comment by allendongyx** [comment]
升级到taro 3.0.8 可以了，但是一堆坑，不过不打算退回，就继续用了，运行时的方案感觉好多了，本多react的hooks框架库都可以用了，比如unstate-next

**Comment by allendongyx** [comment]
升级到taro 3.0.8 可以了，但是一堆坑，不过不打算退回，就继续用了，运行时的方案感觉好多了，本多react的hooks框架库都可以用了，比如unstate-next

**Comment by hqman** [comment]
3.0.8  版本 Taro.createContext报错 遇到过吗？

VM22:1 MiniProgramError
_tarojs_taro__WEBPACK_IMPORTED_MODULE_0___default.a.createContext is not a function
TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_0___default.a.createContext is not a function
    at Object../src/pages/xxx/context.js (http://127.0.0.1:42611/appservice/pages/xxx/index.js:949:76)

**Comment by allendongyx** [comment]
@hqman  Taro 不再提供 useState, useEffect 这些React的原生hooks了，要从
```javascript
const { useState } from 'react'
```
这些直接引入，详情看：https://taro-docs.jd.com/taro/docs/hooks/

**Comment by hqman** [comment]
好的 已换成 react 可以了

**Comment by JimmyLv** [comment]
@allendongyx @hqman  请问是直接使用 React.createContext 吗？

**Comment by hqman** [comment]
> @allendongyx @hqman 请问是直接使用 React.createContext 吗？

  解决方案在这里 https://taro-docs.jd.com/taro/docs/hooks/

**Comment by JimmyLv** [comment]
![image](https://user-images.githubusercontent.com/4997466/100993866-e0528800-3590-11eb-9aa9-9e0cd30e7abd.png)
但是这个文档里面还是说的使用 `Taro.createContext`，需要更新了吧？
