### ISSUE TITLE
opentype设置为share,无法调用支付宝小程序的分享

### ISSUE THREAD

**Issue by 179778978** [NervJS/taro#7486]
### 相关平台
支付宝小程序

**小程序基础库: 1.24.3**
**使用框架: React**

### 复现步骤
设置button的openType="share",微信小程序可以正常调用分享功能，支付宝小程序无法调用分享

### 期望结果
期望结果是支付宝小程序可以通过button调用分享

### 实际结果
设置opentype="share",无法调用分享

### 环境信息
```
 Taro CLI 3.0.8 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.8 => 3.0.8
      @tarojs/mini-runner: 3.0.8 => 3.0.8
      @tarojs/react: 3.0.8 => 3.0.8
      @tarojs/runtime: 3.0.8 => 3.0.8
      @tarojs/taro: 3.0.8 => 3.0.8
      @tarojs/webpack-runner: 3.0.8 => 3.0.8
      babel-preset-taro: 3.0.8 => 3.0.8
      eslint-config-taro: 3.0.8 => 3.0.8
      react: ^16.13.1 => 16.13.1
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

**Comment by Chen-jj** [comment]
@179778978 复现不了

![image](https://user-images.githubusercontent.com/11807297/92701139-3513a780-f382-11ea-860a-c16daa14033d.png)

![image](https://user-images.githubusercontent.com/11807297/92701165-3d6be280-f382-11ea-8ae2-bf69cdee9182.png)
