### ISSUE TITLE
有错误呢 taro build --type h5

### ISSUE THREAD

**Issue by upbill** [NervJS/taro#749]
**问题描述**
全都是正常步聚安装的 weapp没问题 h5出错

**复现步骤**
Module not found: Can't resolve '@tarojs/taro-h5'
ENOENT: no such file or directory, open '************\code\all\dist\lib\lib-manifest.json'
(node:7472) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '**************\code\all\
dist\lib\lib-manifest.json'
(node:7472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:7472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.

**系统信息**

 - 操作系统: Windows 7
 - Taro 版本 1.0.7
 - Node.js 版本 v10.11.0

**Comment by luckyadam** [comment]
` Can't resolve '@tarojs/taro-h5'`
@tarojs/taro-h5 这个包没装好，可以再把依赖安装一下
