### ISSUE TITLE
如何获取 ScrollView  可滚动区域的高度（不是设置的ScrollView固定的高度）

### ISSUE THREAD

**Issue by giantss** [NervJS/taro#7494]
### 这个特性解决了什么问题？
想实现微信加载完历史记录，列表还保持在原来的原来的位置

### 这个 API 长什么样？
可以获取 ScrollView  可滚动区域的高度

**Comment by iamxiyang** [comment]
![image](https://user-images.githubusercontent.com/40079272/91921546-54fdf800-ecfe-11ea-8d96-92ec919af412.png)

通过这样不能获取么？

**Comment by giantss** [comment]
taro scrollview 中没有 dragend 事件，我使用 `scrollIntoView` 实现了
