### ISSUE TITLE
webview支付宝小程序表现异常

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#7498]
### 相关平台
支付宝小程序

**小程序基础库: 1.24.6**
**使用框架: React**

### 复现步骤
内嵌百度 淘宝首页，自己网站的活动页都能正常显示，但是内嵌像一些协议类文字内容较多的的 就打开空白

### 期望结果
正常使用

### 实际结果
协议类文字内容较多的的 就打开空白

### 环境信息
```
👽 Taro v1.3.39


  Taro CLI 1.3.39 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
像一些注册协议啊  关于我们啊  一类的文字声明介绍

**Comment by Chen-jj** [comment]
1.试试原生有没有问题 2.提供一下 demo

**Comment by Junzibuzhengyibuqi** [comment]
> 1.尝试原生有没有问题2.提供一下demo
支付宝原生是好的  

简单 demo为  <web-view src="https://license.xbzoom.com/pages/index?code=dd_c_miniprogram_agreement" />

**Comment by Junzibuzhengyibuqi** [comment]
<web-view src="https://license.xbzoom.com/pages/index?code=dd_c_miniprogram_agreement" />

**Comment by Chen-jj** [comment]
@Junzibuzhengyibuqi demo 没传上来

**Comment by Junzibuzhengyibuqi** [comment]
> @Junzibuzhengyibuqi演示没传上来

简单 demo为  <web-view src="https://license.xbzoom.com/pages/index?code=dd_c_miniprogram_agreement" />

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/92699655-74d98f80-f380-11ea-81ec-d289eb2bd63d.png)
复现bu不了

**Comment by Junzibuzhengyibuqi** [comment]
> ![image](https://user-images.githubusercontent.com/11807297/92699655-74d98f80-f380-11ea-81ec-d289eb2bd63d.png)
> 复现bu不了

好的 谢谢
