### ISSUE TITLE
taro3.0  externalClasses 外部样式类  hooks 写法好像无法接收到父组件传递的class  

### ISSUE THREAD

**Issue by yxwwk** [NervJS/taro#7499]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
父组件： class-name={styles.img}
自定义组件接收：
RngImage.externalClasses = ['class-name']
className='class-name'

### 期望结果
自定义组件可以接收父组件的class

### 实际结果
没有接收到

### 环境信息
```
Taro v3.0.8


  Taro CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@yxwwk React 组件不等于微信自定义组件，用 React 的写法去传递

**Comment by zhixinpeng** [comment]
这个问题很有意思，[官方文档](http://taro-docs.jd.com/taro/docs/component-style/) 明明用 react 的写法告诉用户用react传递className不可行，推荐使用 externalclasses，这里却说react组件不是微信自定义组件。我按照官网尝试了半天externalclasses却不成功。
