### ISSUE TITLE
请问是否支持windows版本？

### ISSUE THREAD

**Issue by Rayliwang** [NervJS/taro#75]
win10, 64
node v8.9.3
npm 6.1.0

$ cnpm run dev:h5

> taro-demo@1.0.0 dev:h5 E:\web\taro-demo
> npm run build:h5 -- --watch

> taro-demo@1.0.0 build:h5 E:\web\taro-demo
> taro build --type h5 "--watch"

Taro v0.0.45

开始编译项目 taro-demo
缺少npm包@tarojs/webpack-runner，开始安装...
platform unsupported @tarojs/webpack-runner@0.0.45 › extract-text-webpack-plugin@3.0.2 › webpack@3.12.0 › watchpack@1.6       .0 › chokidar@2.0.3 › fsevents@^1.1.2 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.1.2] optional install error: Package require os(darwin) not compatible with your platform(win32)
√ Installed 1 packages
√ Linked 787 latest versions
√ Run 2 scripts
peerDependencies link ajv@6.5.1 in E:\web\taro-demo\node_modules\_ajv-keywords@3.2.0@ajv-keywords unmet with E:\web\tar       o-demo\node_modules\ajv(5.5.2)
√ All packages installed (903 packages installed from npm registry, used 43s, speed 219.43kB/s, json 788(5.7MB), tarbal       l 3.58MB)

监听文件修改中...
> Listening at http://localhost:8080/

./.temp/pages/index/index.js
Module not found: Can't resolve '@tarojs/components' in 'E:\web\taro-demo\.temp\pages\index'

**Comment by luckyadam** [comment]
应该是项目依赖没有完全装好~ 可以在项目目录下手动安装再试试

**Comment by luckyadam** [comment]
请问安装好依赖后，问题还存在么

**Comment by Rayliwang** [comment]
@luckyadam 查看报错日志，发现有些包就包是从cnpm下载下来的，重新安装了cnpm后，cnpm install就解决了

**Comment by luckyadam** [comment]
好嘞~
