### ISSUE TITLE
如何方便的切换taro2和3

### ISSUE THREAD

**Issue by lxzy-yun** [NervJS/taro#7500]
### 这个特性解决了什么问题？
本地有2个项目，旧的用2写的，新的用3写的，每次跑不同的项目，都要全局安装2和3

### 这个 API 长什么样？
可以通过命令优雅的切换taro2和3

**Comment by allendongyx** [comment]
把taro-cli 安装到本地 package，不要全局安装

**Comment by allendongyx** [comment]
就是安装到项目的package中，taro-cli 是在项目的node_module 中

**Comment by Chen-jj** [comment]
@allendongyx 正解
