### ISSUE TITLE
希望支持Map组件的自定义气泡窗口[customCallout]功能

### ISSUE THREAD

**Issue by itcat99** [NervJS/taro#7507]
### 这个特性解决了什么问题？
自定义地图上Marker气泡样式

### 这个 API 长什么样？
与微信小程序官方统一

**Comment by Chen-jj** [comment]
支持的吧，你是怎样写的

**Comment by itcat99** [comment]
> 支持的吧，你是怎样写的

Map.d.ts 文件里的 `interface marker` 里面没看到有customCallout属性... 在 256行只有callout 

tarojs/compnents 版本为3.0.8

**Comment by itcat99** [comment]
好的 我试下， 另外 taro cli 的help有描述错了 就不提新issues了吧😂

--no-typescript 这一行 应该是 `不使用TypeScript`

![image](https://user-images.githubusercontent.com/15715084/92100771-c927c100-ee0e-11ea-97c5-d4ba61940201.png)

**Comment by itcat99** [comment]
> types 漏了而已，直接用吧

按照自定义气泡的官方示例并没有生效

**Comment by wangppp** [comment]
我今天也遇到了，通过renderCallout的方式不能自定义cover-view

**Comment by cl1107** [comment]
> 支持的吧，你是怎样写的

这个在Taro3中要怎么写啊？按照小程序官网例子写没效果

**Comment by jyx12138** [comment]
+1

**Comment by jyx12138** [comment]
同遇到，不能自定义气泡 customCallout

**Comment by NyanShen** [comment]
解决了吗？taro typescript 怎么写自定义callout的

**Comment by githubmann** [comment]
同问

**Comment by githubmann** [comment]
这个问题并没解决

**Comment by githubmann** [comment]
@Chen-jj 麻烦看一下
https://github.com/NervJS/taro/issues/7934

**Comment by NyanShen** [comment]
好纳闷哦，都找不到taro3，customCallout和CoverView怎么绑定显示，文档只有slot，但是React不支持

**Comment by githubmann** [comment]
临时解决办法; 改写 node_modules/@tarojs/shared/dist/index.js; 亲测有效
```js
var CoverView = Object.assign({ 'scroll-top': 'false', 'marker-id': '', 'slot': '' }, touchEvents);
```

**Comment by Chen-jj** [comment]
3.2.6 修复，文档地址：https://docs.taro.zone/docs/components/maps/map#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B0%94%E6%B3%A1
