### ISSUE TITLE
taro3.0.8版本中无法渲染使用dangerouslySetInnerHTML渲染HTML

### ISSUE THREAD

**Issue by alwaysRemember** [NervJS/taro#7524]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/alwaysRemember/koala-frontend/blob/master/src/pages/ProductDetail/components/ProductContent/index.tsx](https://github.com/alwaysRemember/koala-frontend/blob/master/src/pages/ProductDetail/components/ProductContent/index.tsx)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
npm run dev:weapp
npm run mock
```
修改src/request/index.ts
第17行serverTestUrl为mockUrl,
第14行mockUrl参数为npm run mock 运行后的链接
```

### 期望结果
```
<View className="taro_html" dangerouslySetInnerHTML={{ __html: data }} />
传入的data字段生效
```

### 实际结果
```
<View className="taro_html" dangerouslySetInnerHTML={{ __html: data }} />
data字段为父组件从请求中获取的数据，初始为空，获取到数据后再传入到__html后失效。
经测试发现__html好像只支持默认数据
例：
data = "<p>1</p>";

```

### 环境信息
```

  Taro CLI 3.0.8 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.8 => 3.0.8 
      @tarojs/mini-runner: 3.0.8 => 3.0.8 
      @tarojs/react: 3.0.8 => 3.0.8 
      @tarojs/runtime: 3.0.8 => 3.0.8 
      @tarojs/taro: 3.0.8 => 3.0.8 
      @tarojs/webpack-runner: 3.0.8 => 3.0.8 
      babel-preset-taro: 3.0.8 => 3.0.8 
      eslint-config-taro: 3.0.8 => 3.0.8 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 3.1.6
```

**Comment by alwaysRemember** [comment]
@Chen-jj 想问下这个是否为taro的bug，下个版本预计什么时候发布

**Comment by alwaysRemember** [comment]
暂时发现一个替代方案可以根据请求的内容进行响应数据。
内容存在的时候在进行渲染VIEW
```
const [isShow, setIsShow] = useState<boolean>(false);
  useEffect(() => {
    setIsShow(!!data);
  }, [data]);
  return (
    <View className={styles['product-content-wrapper']}>
      {(isShow && (
        <View
          className="taro_html"
          dangerouslySetInnerHTML={{ __html: data }}
        />
      )) ||
        ''}
    </View>
  );
```

**Comment by zhaoguoweiLLHC** [comment]
渲染html用RichText更合适。

**Comment by Chen-jj** [comment]
@alwaysRemember 升级到 3.0.14 再试试咯，应该没有问题了：

![image](https://user-images.githubusercontent.com/11807297/96832995-46b49880-1472-11eb-9b25-3e741563b48a.png)

另外写了一个 demo，也没有问题：

```js
import React, { Component, useState, useEffect } from 'react'
import { View, Button, Text, Swiper, SwiperItem } from '@tarojs/components'
import Taro from '@tarojs/taro'

import './index.scss'

const ProductContent = ({ data }: { data: string }) => {
  const [isShow, setIsShow] = useState<boolean>(false);
  useEffect(() => {
    setIsShow(!!data);
  }, [data]);
  return (
    <View>
      {(isShow && (
        <View
          dangerouslySetInnerHTML={{ __html: data }}
        />
      )) ||
        ''}
    </View>
  );
};

class Index extends Component{
  state = {
    data: ''
  }

  render () {
    return (
      <View>
        <ProductContent data={this.state.data} />
        <Button onClick={() => {
          this.setState({
            data: '<p>123</p>'
          })
        }}>click</Button>
      </View>
    )
  }
}

export default Index
```

![image](https://user-images.githubusercontent.com/11807297/96833186-972bf600-1472-11eb-9a96-de3d400022a1.png)

**Comment by alwaysRemember** [comment]
> @alwaysRemember升级到3.0.14再试试咯，应该没有问题了：
> 
> ![图片](https://user-images.githubusercontent.com/11807297/96832995-46b49880-1472-11eb-9b25-3e741563b48a.png)
> 
> 另外写了一个demo，也没有问题：
> 
> ```js
> import React, { Component, useState, useEffect } from 'react'
> import { View, Button, Text, Swiper, SwiperItem } from '@tarojs/components'
> import Taro from '@tarojs/taro'
> 
> import './index.scss'
> 
> const ProductContent = ({ data }: { data: string }) => {
>   const [isShow, setIsShow] = useState<boolean>(false);
>   useEffect(() => {
>     setIsShow(!!data);
>   }, [data]);
>   return (
>     <View>
>       {(isShow && (
>         <View
>           dangerouslySetInnerHTML={{ __html: data }}
>         />
>       )) ||
>         ''}
>     </View>
>   );
> };
> 
> class Index extends Component{
>   state = {
>     data: ''
>   }
> 
>   render () {
>     return (
>       <View>
>         <ProductContent data={this.state.data} />
>         <Button onClick={（） =>  {
>           此。的setState （{
>             数据：'<P> 123 </ P>' 
>           } ）
>         } } >点击< /按钮> 
>       < /查看> 
>     ）
>   } 
> }
> 
> 出口 默认 索引
> ```
> 
> ![图片](https://user-images.githubusercontent.com/11807297/96833186-972bf600-1472-11eb-9a96-de3d400022a1.png)

好的我试一下，感谢！

**Comment by Chen-jj** [comment]
当有初始值时还是有问题，#7900 ，我们再看看

**Comment by RyderMa** [comment]
dev好使, build失效

**Comment by RyderMa** [comment]
> dev好使, build失效

Taro 3.0.22
