### ISSUE TITLE
dangerouslySetInnerHTML 渲染 html 时，转义字符没有被正确转义，比如空格 &nbsp;

### ISSUE THREAD

**Issue by wangxiaocuo** [NervJS/taro#7531]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/wangxiaocuo/taro3-bugs](https://github.com/wangxiaocuo/taro3-bugs)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
比如解析渲染 `正文内容 &nbsp; &nbsp; &nbsp; &nbsp; 正文内容 &nbsp; &nbsp; &nbsp; &nbsp; 正文内容` 这一串内容。

实际渲染效果是这样的。

![image](https://user-images.githubusercontent.com/16472134/92222619-dce82b80-eed1-11ea-8056-bf3f5fc6e366.png)

### 期望结果
期望 html 的转义字符能被争取渲染

### 实际结果
目前是原封不动的渲染出来，并未被转义。(没有用过 react web 应用中的 dangerouslySetInnerHTML，不知道是不是原本功能就有这个问题...)

### 环境信息
```
Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
```

**Comment by wangxiaocuo** [comment]
经过研究，可以通过以下方式折中解决问题：

```js
// 把转义字符替换成真实的内容，并包裹在 pre 标签中
// 比如 &nbsp; 替换成 空格；&amp; 替换成 &
text = text.replace(/&nbsp;/g, `<pre class="escape">${' '}</pre>`)

text = text.replace(/&amp;/g, `<pre class="escape">&</pre>`)
```

在自己的业务场景下，枚举所有可能的转义符并替换。

另外需要设置 `pre` 的样式：

```css
.pre.escape {
    display: inline-block;
}
```

**Comment by zhaoguoweiLLHC** [comment]
渲染html用RichText更合适。解析空格记得加个 space='nbsp' 属性。例：
`
<RichText
        nodes={data}
        space='nbsp'
      />
`

**Comment by zhaoguoweiLLHC** [comment]
渲染html感觉RichText更好用。

**Comment by SamChangi** [comment]
再比如大于&gt;小于&lt;

**Comment by wangxiaocuo** [comment]
> 再比如大于>小于<

**Comment by jiaozitang** [comment]
Taro 文档 https://taro-docs.jd.com/taro/docs/html/ 有相关介绍：

HTML 转义
由于进行 HTML 转义需要消耗较多的性能和较大的体积，默认而言 Taro 的 HTML 接口只接受转义后的 HTML 字符串，我们推荐直接在服务端返回转义后的 HTML。如果确实需要在客户端转义，开源社区有两个较好的选择：

he: 体积较大，但开源协议更为宽松
entities: 体积较小，但开源协议更为严格
你可能会需要高级选项的 transformText 配合 HTML 转义进行字符串渲染。
