### ISSUE TITLE
VirtualList 虚拟列表在头部加入其他内容，并跟随滚动

### ISSUE THREAD

**Issue by MrChen2016-08-27** [NervJS/taro#7537]
我想在首页加几个模块栏目，比如 头部轮播图，中部分类菜单，然后下面是无限滚动列表。
但是加入之后 头部轮播图，中部分类菜单不会动，只有下面的列表会滚动，这样可视区域非常小。
我尝试在 VirtualList，轮播图外部包裹一个 ScollView , 但还是 VirtualList 会变成优先滚动。
**怎么让非VirtualList内容一起滚动呢，如果通过判断类型将轮播图和菜单加入到 VirtualList 的子项，会因为 itemSize 的高度设置，让所有子项变成一个高度。**

**Comment by Psli** [comment]
+1

**Comment by liuhuapiaoyuan** [comment]
> 让 itemSize 的支持 function 我觉得会是一个好的选择。

最好是能支持function，写死太不灵活了

**Comment by beysong** [comment]
+1

**Comment by ZakaryCode** [comment]
> 让 itemSize 的支持 function 我觉得会是一个好的选择。

与该问题无关，但将在 3.6 中支持
