### ISSUE TITLE
bug  @tarojs/components@1.0.7 requires a peer of @types/react@^16.4.6

### ISSUE THREAD

**Issue by upbill** [NervJS/taro#754]
**问题描述**
npm WARN @tarojs/components@1.0.7 requires a peer of @types/react@^16.4.6 but none is installed. You must install peer d
ependencies yourself.

package.json新安装的时候  里面的版本号是不是要改一下
"devDependencies": {
    "@types/react": "16.3.14",

**Comment by luckyadam** [comment]
是个 warning，其实还好~ 可以自己安装一下~
