### ISSUE TITLE
Taro3.x 微信小程序使用 HOC 导致多生命周期不触发

### ISSUE THREAD

**Issue by smackgg** [NervJS/taro#7541]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/smack-o/wechat-app-hrbust/blob/8425affd5dcf5f9e81c3205ede8a5a3c70c70636/src/components/%40with-share/index.tsx#L21](https://github.com/smack-o/wechat-app-hrbust/blob/8425affd5dcf5f9e81c3205ede8a5a3c70c70636/src/components/%40with-share/index.tsx#L21)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
Taro 微信小程序使用 HOC 导致多生命周期不触发

componentDidShow
componentDidHide
onReachBottom

等生命周期都不触发

同时有一个疑问，为什么 redux 的 connect HOC 就没问题？

### 期望结果
正常触发各生命周期

### 实际结果
没有触发生命周期

### 环境信息
```
👽 Taro v3.0.9


  Taro CLI 3.0.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7
      @tarojs/mini-runner: 3.0.7 => 3.0.7
      @tarojs/react: 3.0.7 => 3.0.7
      @tarojs/runtime: 3.0.7 => 3.0.7
      @tarojs/taro: 3.0.5 => 3.0.5
      @tarojs/webpack-runner: 3.0.7 => 3.0.7
      babel-preset-taro: 3.0.7 => 3.0.7
      eslint-config-taro: 3.0.7 => 3.0.7
      react: ^16.10.0 => 16.13.1
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

**Comment by smackgg** [comment]
之前有看到h5类似的 issues  https://github.com/NervJS/taro/issues/3537

**Comment by NaiveCAI** [comment]
👀

**Comment by rottenpen** [comment]
插个眼👀

**Comment by wangkui1991** [comment]
我这里react-redux的connect也不行

![image](https://user-images.githubusercontent.com/19390707/92675161-5ad48880-f351-11ea-95b9-78926e751b34.png)

**Comment by Chen-jj** [comment]
@smackgg 

Taro 处理生命周期的逻辑，如 `onShow`：

小程序触发 `onShow`，找到页面组件实例，调用上面的 `componentDidShow` 方法。

`react-redux` `connect` 后能正常触发是因为它处理了 `forwardRef`，Taro 拿到的是用户编写的组件，所以能找到它上面的各生命周期方法进行调用。

如果 HOC 只是注入 props，也可以使用 `forwardRef` 处理一下，如：

```js
function withShare() {
  return function demoComponent(WrappedComponent) {
    class WithShare extends Component {...}
    React.forwardRef((props, ref) => {
      return (
        <WithShare ref={ref} {...props} />
      )
    })
  }
}
```

但你的 HOC 还注入了一些生命周期方法，处理 `forwardRef` 后 Taro 拿到的是 **WrappedComponent** 的实例，这样就不会触发注入的生命周期方法。

这种情况，可以采取你上述的继承方法。建议直接不需要写 `render` 函数，因为原型链上的 `render` 会自动被执行。

> ```js
> function demoComponent(WrappedComponent) {
>   return class SomeComponent extends WrappedComponent {
>     componentWillMount() {}
> 
>     // ...somecodes
> 
>     // render 方法不需要编写
>     // render() {}
>   }
> }
> ```

**Comment by beysong** [comment]
connect(mapStateToProps, mapDispatchToProps)(withShare(Index))
改变一下执行顺序就行了

**Comment by senylin** [comment]
如果是函数式的写法 hoc怎么改比较好？
