### ISSUE TITLE
新版 animate 动画无效

### ISSUE THREAD

**Issue by abramdev** [NervJS/taro#7548]
### 相关平台
微信小程序

### 复现仓库
[https://gist.github.com/abramdev/65538eb858851e61854794ffc8d34527](https://gist.github.com/abramdev/65538eb858851e61854794ffc8d34527)
**小程序基础库: 2.12.2**
**使用框架: Vue 3**

### 复现步骤
默认 Vue3 模板直接使用动画，Current.page.animate

### 期望结果
有动画过程

### 实际结果
直接变成动画结果，没有过程

### 环境信息
```
Taro CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.9.0 - C:\Program Files\nodejs\node.EXE        
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
写错了，动画需要开始和结束两条数据，和 Taro 无关。

```js
Current.page.animate(
  '#button',
  [
    {
      translateY: 0,
    },
    {
      translateY: 100,
    },
  ],
  3000,
  () => {}
)
```
