### ISSUE TITLE
taro-redux 使用报错

### ISSUE THREAD

**Issue by whitedesignd** [NervJS/taro#7555]
### 相关平台
微信小程序

### 复现仓库
[git@github.com:whitedesignd/taro-music.git](git@github.com:whitedesignd/taro-music.git)
**小程序基础库: 2.12.1**
**使用框架: React**

### 复现步骤
安装官网步骤安装 使用taro-redux，报错 

### 期望结果
使用 taro-redux

### 实际结果
不能使用，可以使用react-redux

### 环境信息
```
� Taro v3.0.8


  Taro CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.0.0 - D:\nvm\node\node.EXE
      Yarn: 1.19.1 - D:\yarn\bin\yarn.CMD
      npm: 6.14.4 - D:\nvm\node\npm.CMD
```

---
### 补充信息
可以使用react-redux。
使用taro-redux 报错信息
TypeError: Cannot call a class as a function
 TypeError: Cannot call a class as a function
Cannot read property 'mount' of undefined
TypeError: Cannot read property 'mount' of undefined

**Comment by suiyuex** [comment]
@whitedesignd  能不能提供一下入口文件的内容

**Comment by whitedesignd** [comment]
> @whitedesignd 能不能提供一下入口文件的内容

import React,{Component}from 'react';
import './app.less'
import 'taro-ui/dist/style/index.scss'
import { Provider  } from '@tarojs/redux'
import configStore from './redux/store.js'
const store = configStore()
class App extends Component {
  // this.props.children 是将要会渲染的页面
  render() {
    return <Provider store={store}>
        {this.props.children}
      </Provider>
    
  }
}
export default App

**Comment by suiyuex** [comment]
@whitedesignd 目前使用redux还是需要使用社区包`redux`，`react-redux`由于官方包`@tarojs/redux`，`@tarojs/redux-h5`这两个包其内部尚未实现`Provider`，`redux`是一个js包，`react-redux`基于react，taro是基本支持所有jsx语法的，所以无需担心跨端兼容性问题

**Comment by Chen-jj** [comment]
@suiyuex 使用 `react-redux`。文档改了还没发版，看 next 版本的文档。

**Comment by suiyuex** [comment]
最新文档可以通过此网址查看: https://nervjs.github.io/taro/docs/next/redux
