### ISSUE TITLE
使用RequestQueue是否有必要？它貌似没有带来任何好处

### ISSUE THREAD

**Issue by SyMind** [NervJS/taro#7561]
### 这个特性解决了什么问题？
1. 百度小程序对于 request 方法的注意事项 iOS 和 Android 中有比较大的不同，现在缓冲区的 5 个请求的并发数量限制了小程序的并发能力（无论是 iOS 端还是 Android 端）

> request 最大并发数在 iOS 端为 6 ；Android 端同一域名下最大并发数为 5，且在 Android 端上同一个小程序最大并发数上限为 64 
> 引自 - https://smartprogram.baidu.com/docs/develop/api/net/net_rule/

2. iOS 端并发数超越了 6 个时，百度小程序会使其自动进入 pending 队列（和浏览器表现相同），而无需在 js 层面添加一层多余的缓冲队列

这里是原生 request 方法的请求结果

![image](https://user-images.githubusercontent.com/19852293/92538620-bdeeee00-f271-11ea-9d94-14406299a55e.png)

这是 Taro.request 方法的请求结果

![image](https://user-images.githubusercontent.com/19852293/92538816-41104400-f272-11ea-8b14-0857b7270997.png)

3. 我草率的猜想，其他的小程序是否也并不需要 RequestQueue。

### 这个 API 长什么样？
不使用 RequestQueue，由小程序内部机制自行管理。

**Comment by Chen-jj** [comment]
嗯嗯，我们统一去掉一下。
