### ISSUE TITLE
Taro组件支持多端编译成平台代码

### ISSUE THREAD

**Issue by liaobin312716** [NervJS/taro#7563]
### 这个特性解决了什么问题？
目前Taro的多端组件，开发完只是会编译成 lib， 需要在 taro项目中才能使用，项目编译时才会真正编译成特定平台代码。有些情况下，组件希望是跨端的，但是应用特殊性比较大，可以不限制DSL开发。比如多端组件库直接编译成小程序组件，H5组件，就可以不限制应用是 taro项目，还是小程序原生，还是H5原生。

### 这个 API 长什么样？
UI 构建类型时，产出增加不同平台的最终代码

**Comment by shenghanqin** [comment]
挺好的

**Comment by jinjinwa** [comment]
请问下有方案了么？

**Comment by ZakaryCode** [comment]
taro build native-components --type [platform] [--watch]
