### ISSUE TITLE
taro3.0 使用hooks报错

### ISSUE THREAD

**Issue by xiangyuisabatman** [NervJS/taro#7565]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/ddddxy/test](https://gitee.com/ddddxy/test)
**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
启动项目,即可在控制台看到报错

### 期望结果
hooks不报错

### 实际结果
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

### 环境信息
```
Taro CLI 1.3.22 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@xiangyuisabatman 你的 demo 依赖、配置、写法都不是完全按照 3.x 规范来的，先好好看看迁移文档吧。hooks 没有问题。

**Comment by xiangyuisabatman** [comment]
> @xiangyuisabatman 你的 demo 依赖、配置、写法都不是完全按照 3.x 规范来的，先好好看看迁移文档吧。hooks 没有问题。

https://taro-docs.jd.com/taro/versions#hooks  
按照这个更新了依赖,还是报错,不知道哪里出了问题.

引用useState也是按照最新的来的.代码已经更新.

可以麻烦帮我看下吗,,
