### ISSUE TITLE
yarn build:weapp卡住，没任何报错信息

### ISSUE THREAD

**Issue by ztfstar** [NervJS/taro#7570]
### 相关平台
微信小程序

**小程序基础库: 2.13**
**使用框架: React**

### 复现步骤
yarn build:weapp命令执行后，没任何报错信息，一直卡住

### 期望结果
正常编译运行

### 实际结果
卡住

### 环境信息
```
Taro CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.9 => 3.0.9 
      @tarojs/components: 3.0.9 => 3.0.9 
      @tarojs/mini-runner: 3.0.9 => 3.0.9 
      @tarojs/react: 3.0.9 => 3.0.9 
      @tarojs/runtime: 3.0.9 => 3.0.9 
      @tarojs/taro: ^3.0.9 => 3.0.9 
      @tarojs/webpack-runner: ^3.0.9 => 3.0.9 
      babel-preset-taro: 3.0.9 => 3.0.9 
      eslint-config-taro: 3.0.9 => 3.0.9 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by ztfstar** [comment]
已经删除尝试过删除node_modules/和重启电脑

**Comment by luckyadam** [comment]
如何卡住

**Comment by ztfstar** [comment]
@luckyadam 已解决这个问题，现在有一个新问题是新的路由getCurrentInstance().route怎么获取不到参数
![11111](https://user-images.githubusercontent.com/42028416/92696355-5376a480-f37c-11ea-8072-6545daf728a8.jpg)
下面这个是用的老的版本$this.route可以获取的参数
![22222](https://user-images.githubusercontent.com/42028416/92696663-c5e78480-f37c-11ea-94f0-a96354b8de82.jpg)

**Comment by xhwgood** [comment]
我遇到了一样的问题
macOS 11.0，taro 2.2.15
加了sudo 后才能正常运行，楼主是怎么解决的？
