### ISSUE TITLE
Taro3.0.9 TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by carl0804** [NervJS/taro#7573]
### 相关平台
微信小程序

### 复现仓库
[https://gist.github.com/carl0804/62a370dd6c8d35c8122d187df1418df0](https://gist.github.com/carl0804/62a370dd6c8d35c8122d187df1418df0)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
1、新建一个页面
2、编写一个普通类
3、yarn dev:weapp 

### 期望结果
页面正常显示

### 实际结果
编译通过，但开发者工具报错。页面是白板
报错：TypeError: Super expression must either be null or a function

### 环境信息
```
Taro CLI 3.0.9 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.9 => 3.0.9
      @tarojs/components: 3.0.9 => 3.0.9
      @tarojs/mini-runner: 3.0.9 => 3.0.9
      @tarojs/react: 3.0.9 => 3.0.9
      @tarojs/runtime: 3.0.9 => 3.0.9
      @tarojs/taro: 3.0.9 => 3.0.9
      @tarojs/webpack-runner: 3.0.9 => 3.0.9
      babel-preset-taro: 3.0.9 => 3.0.9
      eslint-config-taro: 3.0.9 => 3.0.9
      react: ^16.10.0 => 16.13.1
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

---
### 补充信息
类组件继承自React的Component就没问题，如果继承自Taro的Component就会报错

**Comment by carl0804** [comment]
导致现在无法获取路由参数 this.$router.params

**Comment by Chen-jj** [comment]
https://nervjs.github.io/taro/docs/next/migration#api

**Comment by guoxinlei** [comment]
> 导致现在无法获取路由参数 this.$router.params

后面这个传参的问题你是怎么解决的啊

**Comment by carl0804** [comment]
> > 导致现在无法获取路由参数 this.$router.params
> 
> 后面这个传参的问题你是怎么解决的啊
-----------------------
用getCurrentInstance：
[https://nervjs.github.io/taro/docs/next/migration#api
](url)
import { getCurrentInstance } from '@tarojs/taro'
class C extends Component {
  current = getCurrentInstance()

  componentWillMount () {
    // getCurrentInstance().router 和 this.$router 和属性一样
    console.log(this.current.router)
  }
}

// 函数式组件
import { getCurrentInstance } from '@tarojs/taro'
function C () {
  const { router } = getCurrentInstance()
  // getCurrentInstance().router 和 useRouter 返回的内容也一样
  // const router = useRouter()
}

**Comment by ctq123** [comment]
这个问题好恶心，好多组件都不能使用了
