### ISSUE TITLE
不知道能否移植到鸿蒙os上

### ISSUE THREAD

**Issue by OHeroJ** [NervJS/taro#7589]
这块 https://developer.harmonyos.com/cn/docs/documentation/doc-guides/ui-js-overview-0000000000500376 跟小程序比较相像

期待可以直接将小程序移植到鸿蒙os上，作为技术牛逼的你们

**Comment by honlyHuang** [comment]
期待

**Comment by panxinwu** [comment]
666

**Comment by darkfiredarkhalo** [comment]
这个可以不可以有?

**Comment by mango-FullStack** [comment]
期待的搓搓手

**Comment by zhiqingchen** [comment]
搓手

**Comment by HeyiMaster** [comment]
手动鼓掌

**Comment by luckyadam** [comment]
期待

**Comment by xiaoyao96** [comment]
期待地搓搓手

**Comment by Chen-jj** [comment]
3.1 之后开发者可以自己编写端平台的插件来对任何小程序平台进行支持了：https://nervjs.github.io/taro/docs/next/platform-plugin

欢迎贡献～

**Comment by Chen-jj** [comment]
Taro v3.5 已支持~
