### ISSUE TITLE
Taro 3.0.10 VirtualList加载更多时出现闪烁

### ISSUE THREAD

**Issue by jimmyshen007** [NervJS/taro#7593]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/](https://github.com/)
**小程序基础库: 2.12**
**使用框架: React**

### 复现步骤
3.0.9无限滚动时，加载更多数据出现闪烁，scrollOffset在不停的上下跳。视觉上新加载的数据部分出现闪烁不停。
  
render() {
    const { Order } = this.props.store;
    const data = _.get(Order, 'ordersRef.orders', []);
    const dataLen = data.length;
    console.log(listHeight, itemsPerPage, dataLen);
    return (
      <View className='orders'>
        <VirtualList
          width='100%'
          height={listHeight}
          itemData={data}
          itemCount={dataLen}
          itemSize={itemSize}
          onScroll={({ scrollDirection, scrollOffset }) => {
            console.log(scrollOffset, ((dataLen - itemsPerPage) * itemSize - 350));
            if (
              // avoid duplicate loading.
              !Order.loading
              && Order.initialLoading
              // 只有往前滚动我们才触发
              && scrollDirection === 'forward'
              // 300 = threshold to the bottom.
              && scrollOffset > ((dataLen - itemsPerPage) * itemSize - 350)
            ) {
              this.listReachBottom();
            }
          }}
        >
          {Row}
        </VirtualList>
      </View>
    );

### 期望结果
不出现闪烁

### 实际结果
闪烁

### 环境信息
```
👽 Taro v3.0.9


  Taro CLI 3.0.9 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.6 => 3.0.6 
      @tarojs/mini-runner: 3.0.6 => 3.0.6 
      @tarojs/react: 3.0.6 => 3.0.6 
      @tarojs/runtime: 3.0.6 => 3.0.6 
      @tarojs/taro: 3.0.6 => 3.0.6 
      @tarojs/webpack-runner: 3.0.6 => 3.0.6 
      babel-preset-taro: 3.0.6 => 3.0.6 
      eslint-config-taro: 3.0.6 => 3.0.6 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
```

**Comment by GZWZC** [comment]
有解决方案吗

**Comment by GZWZC** [comment]
已fixed。
加上 style即可。

`
const Row = React.memo(({ index, style, data }) => {
  console.log('data===', data, index, style)
  return (
    <View className='test' style={style}>

    </View>
  );
})
`

**Comment by jimmyshen007** [comment]
对 之前忘了更新这个 加上sytle可以解决。希望官方文档里增加一些细节说明。index, style和data的数据结构没有说很清楚，打印出来才能看到。
