### ISSUE TITLE
process.env.NODE_ENV 赋值错误

### ISSUE THREAD

**Issue by Liiiiimo** [NervJS/taro#7595]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

##### package.json
```json
"scripts": {"dev:weapp": "set NODE_ENV=development&&npm run build:weapp -- --watch"}
```
##### index.jsx
```jsx
console.log(process.env.NODE_ENV === 'development') //false
console.log(process.env.NODE_ENV);  //"development"
```

### 期望结果
process.env.NODE_ENV === 'development' //true

### 实际结果
process.env.NODE_ENV === 'development' //false

### 环境信息
```
 Taro CLI 2.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\hello\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
就算在package.json没给NODE_ENV重新赋值，得到的process.env.NODE_ENV也是“production”，即在引号里面又包裹一对双引号。

**Comment by xiaoyao96** [comment]
建议使用cross-env试试

**Comment by flyingzl** [comment]
是的， `set`这个是windows command语法 ， 可以用`cross-env`试试看

**Comment by Liiiiimo** [comment]
```
	"dev:weapp": "cross-env NODE_ENV=development npm run build:weapp -- --watch",
```
用了cross-env还是这样

**Comment by xiaoyao96** [comment]
建议升级到2.2.x最新版再试试。我2.2.9没这个问题..

**Comment by Liiiiimo** [comment]
升到2.2.x版本确实没有这个问题了，感谢。

> 建议升级到2.2.x最新版再试试。我2.2.9没这个问题..
