### ISSUE TITLE
Taro[3.X]配置关闭图片转base64,但图片地址src属性还是base64

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#7596]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
1.Taro项目配置中关闭url转换
2.CoverImage标签引入本地图片
3.控制台查看CoverImage标签的src属性
[代码片段-开发工具可以显示出来,手机无法显示,请手机扫描预览](https://developers.weixin.qq.com/s/OUttVhmm7vkb)
### 期望结果
正常展示图片

### 实际结果
无法展示图片(CoverImage)不支持base64

![image](https://user-images.githubusercontent.com/42051272/92874926-0f96a480-f43b-11ea-869b-e476a9ed8a7e.png)
![image](https://user-images.githubusercontent.com/42051272/92875087-3a80f880-f43b-11ea-97c4-9bc4af908813.png)

### 环境信息
```
Taro CLI 3.0.9 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 5.1.0 - ~/.config/yarn/global/node_modules/.bin/npm
    npmPackages:
      @tarojs/components: 3.0.9 => 3.0.9 
      @tarojs/mini-runner: 3.0.9 => 3.0.9 
      @tarojs/react: 3.0.9 => 3.0.9 
      @tarojs/runtime: 3.0.9 => 3.0.9 
      @tarojs/taro: 3.0.9 => 3.0.9 
      @tarojs/webpack-runner: 3.0.9 => 3.0.9 
      babel-preset-taro: 3.0.9 => 3.0.9 
      eslint-config-taro: 3.0.9 => 3.0.9 
      react: ^16.13.1 => 16.13.1 
```

**Comment by shenghanqin** [comment]
我在taro v2.x上用的这一条，按说3.0也如此

mini: {
    imageUrlLoaderOption: {
      limit: 0
    },
}

**Comment by VFiee** [comment]
> 我在taro v2.x上用的这一条，按说3.0也如此
> 
> ```
> mini: {
>     imageUrlLoaderOption: {
>       limit: 0
>     },
> }
> ```
这样确实可以,但
url: {
        enable: false,
        config: {
          limit: 1024, // 设定转换尺寸上限
        },
      },
这种方式[小程序端样式引用本地资源内联] 为什么没生效呢?[疑惑]

**Comment by luckyadam** [comment]
> > 我在taro v2.x上用的这一条，按说3.0也如此
> > ```
> > mini: {
> >     imageUrlLoaderOption: {
> >       limit: 0
> >     },
> > }
> > ```
> 
> 这样确实可以,但
> url: {
> enable: false,
> config: {
> limit: 1024, // 设定转换尺寸上限
> },
> },
> 这种方式[小程序端样式引用本地资源内联] 为什么没生效呢?[疑惑]

一个是针对样式的，一个是针对 jsx 里引用图片的

**Comment by faimi** [comment]
你好，这是我的mini配置：
`  mini: {
    baseLevel: 30,
    webpackChain(chain, webpack) {
      if (process.env.ANALYZE) {
        chain.plugin('analyzer').use(require('webpack-bundle-analyzer').BundleAnalyzerPlugin, [
          {
            analyzerMode: 'static',
          },
        ]);
      }
      chain.plugin('my-example-webpack-plugin').use(MyExampleWebpackPlugin);
    },
    miniCssExtractPluginOption: {
      ignoreOrder: true,
    },
    imageUrlLoaderOption: {
      limit: 0,
    },
    postcss: {
      pxtransform: {
        enable: true,
        config: {
          selectorBlackList: ['.ignore'],
        },
      },
      url: {
        enable: false,
        config: {
          limit: 1024, // 设定转换尺寸上限
        },
      },
      cssModules: {
        enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]',
        },
      },
    },
  },`
但是background-image引入的assets/images文件依旧是部分有base64编码
