### ISSUE TITLE
开发、生产两个appid，有什么方案能方便切换吗 ？

### ISSUE THREAD

**Issue by ilaipi** [NervJS/taro#7606]
### 这个特性解决了什么问题？
小程序 生产环境和开发环境肯定是不同的appid，那么如何能做到方便的打包生产或者打包开发的时候，自动选择对应的appid呢？

### 这个 API 长什么样？
比如  npm run dev  这时候能自动使用开发的appid。npm run build  这时候能自动使用生产的appid

**Comment by luckyadam** [comment]
通过在 `config/dev.js` 和 `config/prod.js` 文件中的 defineConstants 配置全局变量

**Comment by ilaipi** [comment]
appid  这个字段是要在  project.config.json 中用的，配置在这两个文件中，打包出来的 并没有这个字段

**Comment by shenghanqin** [comment]
俺也跟一下。俺这里也在思考全局配置的问题

**Comment by qdleader** [comment]
有方案了吗

**Comment by yifeishu-com** [comment]
解决方案在这里：https://yifeishu.com/view/article/7rx#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BC%96%E8%AF%91%E8%87%AA%E5%8A%A8%E6%B3%A8%E5%85%A5%E4%B8%8D%E5%90%8Cappid

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro-docs/docs/env-mode-config/#%E7%89%B9%E6%AE%8A%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F-taro_app_id)
