### ISSUE TITLE
通过配置解决h5端生产环境打包的js.app.[hash].js文件过大的问题

### ISSUE THREAD

**Issue by ZhengXingchi** [NervJS/taro#7607]
### 这个特性解决了什么问题？
优化打包文件的大小

### 这个 API 长什么样？
能够在config中配置

**Comment by ZhengXingchi** [comment]
我的分析报告可参考下面，基本上一个公司项目其中的js.app文件都是过大的，有没有一个简单的配置方案？
![image](https://user-images.githubusercontent.com/31958613/93055844-1ec95c80-f69e-11ea-89b4-3935a0b4cfdb.png)

**Comment by luckyadam** [comment]
可以配置一下 webpack 的 splitChunks，拆分一下文件

**Comment by ZhengXingchi** [comment]
@luckyadam 已配置splitChunks，现在单个文件缺失大小下来了。但是有这个提示`WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:`入口文件的总和太大了，想问问大佬哟没有什么解决思路提供一下的。

**Comment by ZakaryCode** [comment]
> 

具体项目具体分析咯

**Comment by slxgsy** [comment]
关注，我的项目也是编译后app.js太大，1MB了

**Comment by ZakaryCode** [comment]
3.5+ 提供了默认的 splitChunks 配置，如有更多需要可以根据需要自行调整。

**Comment by JTangming** [comment]
可以通过 webpackChain 的 optimization.splitChunks 按需配置吧，具体可以参考：
[optimization.splitChunks ](https://github.com/NervJS/taro/blob/bc6af68bda2cbc9163fbda36c15878fc96aec8f1/packages/taro-mini-runner/src/webpack/build.conf.ts#L220-L254)

**Comment by akFace** [comment]
> 

怎去掉这个警告啊
