### ISSUE TITLE
e.stopPropagation() 无效

### ISSUE THREAD

**Issue by johnbian** [NervJS/taro#761]
**问题描述**
e.stopPropagation() 无效

**复现步骤**
![image](https://user-images.githubusercontent.com/21257561/46452707-c14ce580-c7cf-11e8-8af4-5852bd979e0f.png)
```js
 navigateTo (id) {
    console.log(id)
    // Taro.navigateTo({url: `../../pages/serviceDetail/index?id=${id}`})
  }

  add (e) {
    e.stopPropagation()
    console.log('add')
  }
```

**期望行为**
点击 add 不走navigateTo
**报错信息**
现在是 走完 add（） 还会 再走 navigateTo（）
输出会是 ‘add’ ,id
**系统信息**

 - 操作系统: [mac 10.12.6]
 - Taro 版本 [e.g. v1.0.7]
 - Node.js 版本 [e.g. v8.10.0]

**Comment by snokier** [comment]
+1

**Comment by johnbian** [comment]
@luckyadam 大佬，这个在1.0.7后面版本中修复了嘛？

**Comment by jimczj** [comment]
AtIcon 换成 View 还会吗，看看是否跟 Taro-UI 有关

**Comment by johnbian** [comment]
@jimczj hi，大佬，我换成 Taro的Text 还是会， 版本没有升级。taro版本1.0.7。需要升级不？

**Comment by johnbian** [comment]
@jimczj 大佬 taroV1.1 解决这个了嘛？

**Comment by jimczj** [comment]
@luckyadam 涛哥看看咯，不是 taro-ui 这边的问题

**Comment by yuche** [comment]
看一下你改成 Text 之后编译到 wxml，onClick 有没有变成 catchtap

**Comment by johnbian** [comment]
@yuche 大佬，Text 的 onClick  编译后是 bindtap。

**Comment by yuche** [comment]
@johnbian 发一下你错误编译的 jsx 文件看看？发代码串不要截图。

**Comment by johnbian** [comment]
@jimczj @yuche 大佬，sorry, 是 taroUI 影响的 我之前换成text 没有加上阻止冒泡方法。今天才发现。换成text，e.stopPropagation()就生效了。
"taro-ui": "^1.2.2"
AtIcon编译：
wxml:
`<at-icon bindonclick="add" __triggerObserer="{{ _triggerObserer }}" value="add-circle"
                                size="20" color="#333" __fn_onClick="{{true}}" data-e-add-so="this" data-e-add-a-a="{{detail}}"
                                data-e-add-a-b="{{index}}" data-e-add-a-c="{{key}}"></at-icon>`
add 方法js：
`{
    key: "add",
    value: function add(detail, index, key, e) {
      var _this3 = this;

      e.stopPropagation();
      var _state = this.state,
          choiceServices = _state.choiceServices,
          listall = _state.listall;

      listall[index].capabilites[key].choosen = true;
      this.setState({
        choiceServices: [].concat(_toConsumableArray(choiceServices), [detail]),
        listall: listall
      }, function () {
        return _this3.getShowPrice(_this3.state.choiceServices);
      });
    }
  }`

**Comment by yuche** [comment]
@johnbian 下个版本会修复，这个问题实际上是 Taro 没有处理自定义组件的冒泡事件

**Comment by johnbian** [comment]
thx，辛苦。

**Comment by xiazhangli** [comment]
请问，这个问题解决了吗？

**Comment by thfeng** [comment]
@luckyadam 请问这个问题解决了吗？我也遇到了同样的问题

**Comment by yuche** [comment]
自定义组件阻止冒泡目前还有问题，建议在自定义组件包一层 view 然后在包的那一层 view 上处理冒泡

**Comment by xuxiaoxiao312** [comment]
> 自定义组件阻止冒泡目前还有问题，建议在自定义组件包一层 view 然后在包的那一层 view 上处理冒泡

你好，请问Button内的view是无法阻止冒泡吗？
```
<Button onClick={this.redirect.bind(this)}>
	<View onClick={this.test.bind(this)}>测试</View>
 </Button>
```
这样写点击测试不会触发test,直接执行了redirect，把外面的button换成view就可以

**Comment by helsonxiao** [comment]
希望尽快解决，我也碰到了，用了 Taro-UI 的组件。

**Comment by dingzhaowei** [comment]
刚刚遇到了同样的问题

**Comment by soqt** [comment]
还是没有解决方案吗？这个错误好久了

**Comment by helsonxiao** [comment]
> 还是没有解决方案吗？这个错误好久了

可以在"自定义组件"外包一层 `<View></View>`，然后依靠这层 View 阻止事件继续冒泡。

**Comment by tinyzh** [comment]
```
<View onClick={this.handleParent.bind(this)}>
  <View onClick={this.handleStop.bind(this)}>
    <View onClick={this.handleChild.bind(this)}></View>
  </View>
</View>
# js
handleStop(e){
 e.stopPropagation()
}
```

**Comment by mqliutie** [comment]
@tinyzh 你的taro什么版本？我包一层还是不行

**Comment by tinyzh** [comment]
> @tinyzh 你的taro什么版本？我包一层还是不行
1.2.13

**Comment by tinyzh** [comment]
@mqliutie  1.2.13

**Comment by scutHuqiang** [comment]
#913 请问一下，始终都会阻止事件冒泡这个问题修复了吗？

**Comment by wkl007** [comment]
```javascript
goReOrder = e => {
    e.stopPropagation()
    xxxxxx
}


<View onClick={this.goReOrder}>
     <AtButton type='primary'  className='button' size='small'>
         续住
     </AtButton>
</View>
```
现在我这是这样处理的

**Comment by HuChundong** [comment]
貌似还没解决？必须新加一层View

**Comment by shangyu95** [comment]
加了一层View好像也没有效果，或许是我的姿势不正确

**Comment by HuChundong** [comment]
> 加了一层 View 好像也没有效果，或许是我的姿势不正确

          <View onClick={(e) => {e.stopPropagation()}}>
            <AtButton
              size='small'
              circle
              className='dcs-button'
              onClick={this.props.onEdit}
            >修改</AtButton>
          </View>

**Comment by shangyu95** [comment]
> > 加了一层 View 好像也没有效果，或许是我的姿势不正确
> 
> ```
>       <View onClick={(e) => {e.stopPropagation()}}>
>         <AtButton
>           size='small'
>           circle
>           className='dcs-button'
>           onClick={this.props.onEdit}
>         >修改</AtButton>
>       </View>
> ```

解决了，感谢老哥

**Comment by shenghanqin** [comment]
@johnbian 你可以试试看最新版有木有解决这个问题。感谢。

**Comment by daiyun169** [comment]
请问这个要在什么版本解决，目前解决办法
![image](https://user-images.githubusercontent.com/19162724/71227364-ea489000-2319-11ea-818a-962daf706853.png)

自定义按钮 可以在按钮click 阻止冒泡

**Comment by daiyun169** [comment]
`
              <View className='opera__btn'
                    onClick={event => {event.stopPropagation()}}
              >
                <HnButton
                  size='mini'
                  text='取消订单'
                  compStyle={{
                    width: Taro.pxTransform(200),
                    height: Taro.pxTransform(60),
                    borderRadius: Taro.pxTransform(30),
                  }}
                  onClick={this.handleBtnClick.bind(this, 'cancel')}
                />
              </View>
`

**Comment by daiyun169** [comment]
`              <View className='opera__btn'
                    onClick={event => {event.stopPropagation()}}
              >
                <HnButton
                  size='mini'
                  text='取消订单'
                  compStyle={{
                    width: Taro.pxTransform(200),
                    height: Taro.pxTransform(60),
                    borderRadius: Taro.pxTransform(30),
                  }}
                  onClick={this.handleBtnClick.bind(this, 'cancel')}
                />
              </View>`

**Comment by BoringDays** [comment]
2.0.4，非自定义组件，在需要阻止冒泡的View外面加一层view阻止冒泡也不行？编译出来还是bindtap

**Comment by yangbo5207** [comment]
+ 1

**Comment by Chen-jj** [comment]
试试 Taro3 吧

**Comment by MSYuanMei** [comment]
Taro 3也有这个问题

**Comment by hanpt** [comment]
这问题啥时候能好啊

**Comment by harwinvoid** [comment]
> Taro 3也有这个问题

+1

**Comment by NTBrave** [comment]
解决方法有吗，h5可以，编译成小程序就不行了，有替代方法不？

**Comment by nanxiaobei** [comment]
还是遇到这个问题。

Taro v3.0.26

**Comment by Si3ver** [comment]
Taro3   放在外层的View标签， `event.stopPropagation()` 上可解

**Comment by jaceechan** [comment]
Taro v3.0.25还是有这个问题....

**Comment by Pioneer-Wang** [comment]
最新版taro@3.6.32，e.stopPropagation()方法依旧不行，在最外层增加view进行拦截，又会导致内部button的onClick事件无法处理。这个bug很致命，而且阻止冒泡是常用的，这么久还不能解决吗
