### ISSUE TITLE
为什么process.env.BASE_URL为undefined

### ISSUE THREAD

**Issue by matrixpool** [NervJS/taro#7617]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/matrixpool/minimap.git](https://github.com/matrixpool/minimap.git)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
在dev.js中增加env.BASE_URL= 'XXXX'，为什么在app.tsx中执行console.log(process.env.BASE_URL)输出为undefined.
执行命令为npm run dev:weapp

### 期望结果
输出'XXXX'

### 实际结果
undefined

### 环境信息
```
Taro v3.0.9


  Taro CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - D:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - D:\Program Files\nodejs\npm.CMD
```

**Comment by liganghui** [comment]
我猜你的需求想基于开发环境实现不同BaseUrl吧 ?  前两天我刚搞过 和你分享一下
我使用的是v2.2.13

1.安装依赖
npm install --save-dev cross-env

2.修改package.json H5为例
```javascript
"dev:h5": "cross-env NODE_ENV=development npm run build:devh5 -- --watch",
"build:devh5": "taro build --type h5",
"build:h5": "cross-env NODE_ENV=production taro build --type h5",
```
3. 使用
```javascript
const baseUrl =
  process.env.NODE_ENV === "development"
    ? "............"
    : "............";
```

**Comment by mazaiting** [comment]
重新编译运行
