### ISSUE TITLE
taro打包成h5 报错ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by windyoung1990** [NervJS/taro#7619]
### 相关平台
H5

**浏览器版本: chrome  85.0.4183.83**
**使用框架: React**

### 复现步骤
引用node_modules下的一个npm包，该包顶层带有Object.defineProperty(exports, "__esModule", { value: true }); 的语句&该文件引用了async的语法

### 期望结果
能正常运行

### 实际结果
报错ReferenceError: exports is not defined&在html中定义var exports = {};也不行。

### 环境信息
```
👽 Taro v2.2.6


  Taro CLI 2.2.6 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @tarojs/components: 2.2.6 => 2.2.6
      @tarojs/components-qa: 2.2.6 => 2.2.6
      @tarojs/mini-runner: 2.2.6 => 2.2.6
      @tarojs/redux: 2.2.6 => 2.2.6
      @tarojs/redux-h5: 2.2.6 => 2.2.6
      @tarojs/router: 2.2.6 => 2.2.6
      @tarojs/taro: 2.2.6 => 2.2.6
      @tarojs/taro-alipay: 2.2.6 => 2.2.6
      @tarojs/taro-h5: 2.2.6 => 2.2.6
      @tarojs/taro-qq: 2.2.6 => 2.2.6
      @tarojs/taro-quickapp: 2.2.6 => 2.2.6
      @tarojs/taro-swan: 2.2.6 => 2.2.6
      @tarojs/taro-tt: 2.2.6 => 2.2.6
      @tarojs/taro-weapp: 2.2.6 => 2.2.6
      @tarojs/webpack-runner: 2.2.6 => 2.2.6
      eslint-config-taro: 2.2.6 => 2.2.6
      eslint-plugin-taro: 2.2.6 => 2.2.6
      nerv-devtools: ^1.5.5 => 1.5.6
      nervjs: ^1.5.5 => 1.5.6
      stylelint-config-taro-rn: 2.2.6 => 2.2.6
      stylelint-taro-rn: 2.2.6 => 2.2.6
      taro-ui: ^2.3.4 => 2.3.4
    npmGlobalPackages:
      typescript: 3.9.7
```

---
### 补充信息
同样的代码，打包成百度小程序是正常的
babel配置信息
![image](https://user-images.githubusercontent.com/21021859/93190111-8c948780-f775-11ea-8682-4711f17c1bc2.png)
![image](https://user-images.githubusercontent.com/21021859/93193801-e9923c80-f779-11ea-858c-70d0aee9abd0.png)
![image](https://user-images.githubusercontent.com/21021859/93190686-3bd15e80-f776-11ea-8af3-3c3f9618b517.png)
![image](https://user-images.githubusercontent.com/21021859/93190776-586d9680-f776-11ea-910f-3afb03189082.png)
![image](https://user-images.githubusercontent.com/21021859/93198430-991ddd80-f77f-11ea-81bd-312542ba9a70.png)
![image](https://user-images.githubusercontent.com/21021859/93200637-9f618900-f782-11ea-96c0-3e7e37f48872.png)

**Comment by luckyadam** [comment]
感觉是 
![image](https://user-images.githubusercontent.com/1782542/93206149-8a3d2800-f78b-11ea-970a-406e1b90b9b9.png) 
这个包本身就不支持 web

**Comment by windyoung1990** [comment]
> 感觉是
> ![image](https://user-images.githubusercontent.com/1782542/93206149-8a3d2800-f78b-11ea-970a-406e1b90b9b9.png)
> 这个包本身就不支持 web

应该不是，除了有async语法，其余没啥不一样，并且运行时的错误也不是提示语法的问题

**Comment by windyoung1990** [comment]
![image](https://user-images.githubusercontent.com/21021859/93283267-c5c70900-f802-11ea-9aca-09da5978e371.png)
