### ISSUE TITLE
open-data无法使用className指定class，只能通过class指定样式类

### ISSUE THREAD

**Issue by landluck** [NervJS/taro#762]
**问题描述**
open-data组件无法通过className设置样式，通过class可以

**复现步骤**

```html
   <open-data className='avatar' type="userAvatarUrl"></open-data>
   <open-data class='avatar' type="userAvatarUrl"></open-data>
```

**期望行为**
统一通过className设置样式

**报错信息**
<img width="618" alt="2018-10-05 6 02 23" src="https://user-images.githubusercontent.com/27060081/46529391-deb1aa80-c8c8-11e8-8cfa-9b6f96dcfea1.png">
<img width="559" alt="2018-10-05 6 02 31" src="https://user-images.githubusercontent.com/27060081/46529392-df4a4100-c8c8-11e8-8f37-03ca9fe140a3.png">

**系统信息**

 - 操作系统: [e.g.mac]
 - Taro 版本 [e.g. 1.0.0-beta.22]
 - Node.js 版本 [e.g. v8.11.3]

**Comment by yuche** [comment]
使用 `OpenData`
