### ISSUE TITLE
在navigateBack后，useEffect不触发

### ISSUE THREAD

**Issue by jeange1003** [NervJS/taro#7625]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/jeange1003/taro-useEffect-test](https://github.com/jeange1003/taro-useEffect-test)
**小程序基础库: 1.75.0.9**
**使用框架: React**

### 复现步骤
点击A页面的按钮跳转到B页面
点击B页面按钮调用Taro.navigateBack()回到A页面

### 期望结果
A页面的useEffect(func, [])中的func执行

### 实际结果
A页面的useEffect(func, [])中的func没有执行

### 环境信息
```
👽 Taro v3.0.10


  Taro CLI 3.0.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.10 => 3.0.10 
      @tarojs/components: 3.0.10 => 3.0.10 
      @tarojs/mini-runner: 3.0.10 => 3.0.10 
      @tarojs/react: 3.0.10 => 3.0.10 
      @tarojs/runtime: 3.0.10 => 3.0.10 
      @tarojs/taro: 3.0.10 => 3.0.10 
      @tarojs/webpack-runner: 3.0.10 => 3.0.10 
      babel-preset-taro: 3.0.10 => 3.0.10 
      eslint-config-taro: 3.0.10 => 3.0.10 
      react: ^16.10.0 => 16.13.1 
```

**Comment by lixiaofeng666** [comment]
```javascript
useEffect(()=>{},[])
```
只会在初始加载触发一次, 虽然不知道你为啥要这样写, 不过我猜你想用的是 useDidShow

**Comment by jeange1003** [comment]
> ```js
> useEffect(()=>{},[])
> ```
> 
> 只会在初始加载触发一次, 虽然不知道你为啥要这样写, 不过我猜你想用的是 useDidShow

需求是想要在回退到当前页面后，重新加载一遍当前页面的数据
试了一下useDidShow，也没有在回退后触发，例子已经更新到复现仓库里

**Comment by lixiaofeng666** [comment]
本地跑了下你项目也没啥问题, 每次回退到A页面 useDidShow 都能如期触发 😥

**Comment by jeange1003** [comment]
看了下Taro的实现，有定义onShow。我的代码中覆盖了page instance的onShow，导致useDidShow被覆盖，这个问题关闭。
