### ISSUE TITLE
获取小程序的订阅消息setting

### ISSUE THREAD

**Issue by weblc** [NervJS/taro#7629]
### 这个特性解决了什么问题？
查看用户订阅消息模版的状态

### 这个 API 长什么样？
wx.getSetting({
  withSubscriptions: true,
  success (res) {
    console.log(res.authSetting)
    // res.authSetting = {
    //   "scope.userInfo": true,
    //   "scope.userLocation": true
    // }
    console.log(res.subscriptionsSetting)
    // res.subscriptionsSetting = {
    //   mainSwitch: true, // 订阅消息总开关
    //   itemSettings: {   // 每一项开关
    //     SYS_MSG_TYPE_INTERACTIVE: 'accept', // 小游戏系统订阅消息
    //     SYS_MSG_TYPE_RANK: 'accept'
    //     zun-LzcQyW-edafCVvzPkK4de2Rllr1fFpw2A_x0oXE: 'reject', // 普通一次性订阅消息
    //     ke_OZC_66gZxALLcsuI7ilCJSP2OJ2vWo2ooUPpkWrw: 'ban',
    //   }
    // }
  }
})

**Comment by Chen-jj** [comment]
最新版本已支持。

**Comment by esdotzed** [comment]
3.2.6好像也还是没有支持？

**Comment by esdotzed** [comment]
找到了。
Taro.getSetting({
      withSubscriptions: true,
    }).then(）
