### ISSUE TITLE
px 2 vw

### ISSUE THREAD

**Issue by soulcm** [NervJS/taro#7637]
### 这个特性解决了什么问题？
现在taro默认将px转成了rem，小程序转为rpx，但我们h5页面使用的是vw单位，希望能指定转的单位

### 这个 API 长什么样？
指定转化的单位为vw

**Comment by shenghanqin** [comment]
> ### 这个特性解决了什么问题？
> 现在taro默认将px转成了rem，小程序转为rpx，但我们h5页面使用的是vw单位，希望能指定转的单位
> 
> ### 这个 API 长什么样？
> 指定转化的单位为vw

rem是很好控制最大字体大小的，但vw很难控制。

**Comment by soulcm** [comment]
> > ### 这个特性解决了什么问题？
> > 现在taro默认将px转成了rem，小程序转为rpx，但我们h5页面使用的是vw单位，希望能指定转的单位
> > ### 这个 API 长什么样？
> > 指定转化的单位为vw
> 
> rem是很好控制最大字体大小的，但vw很难控制。

嗯，但我们H5项目用的vw，有配置方式可以转换成vw吗，或让我们自己定义

**Comment by rottenpen** [comment]
```javascript
// ./config/index.js
designWidth: 750,
  deviceRatio: {
    '640': 2.34 / 2 * 375 / 100,
    '750': 1 * 375 / 100,
    '828': 1.81 / 2 * 375 / 100,
  },
```
猜的
