### ISSUE TITLE
taro-vue rpx 转换 bug

### ISSUE THREAD

**Issue by richard1015** [NervJS/taro#7639]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/richard1015/taro-vue-bug](https://github.com/richard1015/taro-vue-bug)
**小程序基础库: 2.13.0**
**使用框架: Vue 2**

### 复现步骤
初始化项目  taro -vue 版本 ，将config/index.js 中 designWidth 750改成 375
npm run dev:weapp 
发现所有样式px 全部是   NaNrpx;

### 期望结果
修复此转换问题

### 实际结果
发现所有样式px 全部是   NaNrpx;

### 环境信息
```


  Taro CLI 3.0.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.10 => 3.0.10 
      @tarojs/mini-runner: 3.0.10 => 3.0.10 
      @tarojs/runtime: 3.0.10 => 3.0.10 
      @tarojs/taro: 3.0.10 => 3.0.10 
      @tarojs/webpack-runner: 3.0.10 => 3.0.10 
      babel-preset-taro: 3.0.10 => 3.0.10 
      eslint-config-taro: 3.0.10 => 3.0.10 
```

**Comment by xiaoyao96** [comment]
仔细看下文档吧，
https://taro-docs.jd.com/taro/docs/size

目前 Taro 支持 750、 640 、 828 三种尺寸设计稿。
如果你的设计稿是 375 ，不在以上三种之中，那么你需要把 designWidth 配置为 375，同时在 DEVICE_RATIO 中添加换算规则如下：
``` js
const DEVICE_RATIO = {
  '640': 2.34 / 2,
  '750': 1,
  '828': 1.81 / 2,
  '375': 2 / 1
}
```

**Comment by richard1015** [comment]
已解决

**Comment by shenghanqin** [comment]
> 已解决

可以参考 https://github.com/hi-our/hi-face/blob/18fd430d9a7d3d2113dbad7609a1a577da31a457/taro/config/index.js#L6 中的配置，比较全
