### ISSUE TITLE
如何在普通方法中使用jsx代码

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro#764]
**问题描述**

随页面内容增加，render 方法也慢慢的增加，代码显得比较冗余，想查分方法来减少部分冗余，使代码可读性更高。

**期望行为**

![image](https://user-images.githubusercontent.com/16408873/46578905-af22af80-ca3a-11e8-8ada-8d4e115005df.png)

**报错信息**

![image](https://user-images.githubusercontent.com/16408873/46578912-bd70cb80-ca3a-11e8-882a-dcc6f37d0f13.png)

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.7
 - Node.js 版本  v10.6.0

**Comment by yuche** [comment]
这个特性还在做，预计本月能够支持

**Comment by ShiYuanjun-Tim** [comment]
> 这个特性还在做，预计近期能够支持


你好我自己fork了个[rn到wx小程序项目](https://github.com/ShiYuanjun-Tim/taro/tree/rn2wx) 正好把这个feature给做了， 你可以把代码贴过去试试看，和已有代码集成非常简单，测试代码也贴出来了

不提PR是因为我的项目改动其他地方太大，肯定不通过, 希望采纳相互提高

[集成补丁到taro](https://github.com/ShiYuanjun-Tim/taro/blob/b57753d6c904e4b7d891d69e162da7c4223ed833/packages/taro-transformer-wx/src/class.ts#L697-L698)

[主要功能文件](https://github.com/ShiYuanjun-Tim/taro/blob/rn2wx/packages/taro-transformer-wx/src/patchs/ejectUIFragMethod.ts)


[测试用例代码都能通过](https://github.com/ShiYuanjun-Tim/rn2wxVerify/blob/master/src/page/comptests/adapter/template.js)

**Comment by yuche** [comment]
> > 这个特性还在做，预计近期能够支持
> 
> 你好我自己fork了个[rn到wx小程序项目](https://github.com/ShiYuanjun-Tim/taro/tree/rn2wx) 正好把这个feature给做了， 你可以把代码贴过去试试看，和已有代码集成非常简单，测试代码也贴出来了
> 
> 不提PR是因为我的项目改动其他地方太大，肯定不通过, 希望采纳相互提高
> 
> [集成补丁到taro](https://github.com/ShiYuanjun-Tim/taro/blob/b57753d6c904e4b7d891d69e162da7c4223ed833/packages/taro-transformer-wx/src/class.ts#L697-L698)
> 
> [主要功能文件](https://github.com/ShiYuanjun-Tim/taro/blob/rn2wx/packages/taro-transformer-wx/src/patchs/ejectUIFragMethod.ts)
> 
> [测试用例代码都能通过](https://github.com/ShiYuanjun-Tim/rn2wxVerify/blob/master/src/page/comptests/adapter/template.js)

比较遗憾的是这个功能我们在 v1.3 分支已经做了，也补充了新的测试用例，大概年前的一个月已经完成了。应该是不会合入了。

**Comment by ShiYuanjun-Tim** [comment]
好的 可惜了，我也是年前完成的，只是才想到可以提供出来

**Comment by yuche** [comment]
close via 4aa409fb1fc5e6197a6f69e7392519716efb9d13
