### ISSUE TITLE
H5 怎么实现 useDidShow一样的功能

### ISSUE THREAD

**Issue by hoozi** [NervJS/taro#7645]
### 这个特性解决了什么问题？
h5 有这么一个需求：navigationTo或者navigationBack进入页面，刷新数据，用react.useEffect 只能在navigationTo触发，navigationBack无效；

### 这个 API 长什么样？
H5 也能提供一个 useDidShow的hook

**Comment by ZakaryCode** [comment]
直接用就行了，[参考文档](http://taro-docs.jd.com/taro/docs/next/hooks#usedidshow)

**Comment by zengyayao** [comment]
> 直接用就行了，[参考文档](http://taro-docs.jd.com/taro/docs/next/hooks#usedidshow)

这个并不能直接用，h5 back useDidShow 是不会调用的
