### ISSUE TITLE
ts语法提示错误

### ISSUE THREAD

**Issue by aqingyang** [NervJS/taro#766]
在vscode中导出页面组件后，在app.js中import组件 ts提示找不到模块，需要完整写出来才可以，但是生成的目录文件只需写一部分就可以找到对应的模块
![image](https://user-images.githubusercontent.com/32590310/46582218-08f49b00-ca76-11e8-9032-236a50371966.png)

**Comment by luckyadam** [comment]
你看看你的页面有没有 export

**Comment by aqingyang** [comment]
有的。name页面基本和脚手架页面一样

**Comment by aqingyang** [comment]
> 页面代码看一下~

name.tsx代码
![image](https://user-images.githubusercontent.com/32590310/46659193-0a91a080-cbe7-11e8-8c2e-457da2aeaac6.png)
app.tsx代码
![image](https://user-images.githubusercontent.com/32590310/46659322-517f9600-cbe7-11e8-841a-3af6bcb1c5b0.png)
具体是vscode的问题还是什么情况不太清楚。情况就是，脚手架生成的页面不用写到文件夹下面具体路径。但是自己新建页面需要

**Comment by luckyadam** [comment]
因为生成的页面是 `index`，肯定不用写到具体文件名咯
