### ISSUE TITLE
升级 1.0.7 后，装饰器编译有问题

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#767]
**问题描述**
从 1.0.4 升级到最新后。用于实例属性上的装饰器，编译后消失了

**复现步骤**
```
$ npx @tarojs/cli init myApp 
```

```js
function func(a,b,c){return c}

export default class Index extends Component {
  @func obj = {}
}
```

**期望行为**
实例化后，obj 是一个对象，但实践运行时是未定义。

**报错信息**
控制台没有报错，但是看了编译出来的代码，根本没有 obj。PS：用于实例方法上的装饰器是有效的

**系统信息**

 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v10.0.0]

**Comment by shenghanqin** [comment]
@jamieYou 尝试一下最新版本？
