### ISSUE TITLE
是否可以升级下babel-preset-taro里的@babel/preset-env 依赖？

### ISSUE THREAD

**Issue by wuchangming** [NervJS/taro#7673]
### 这个特性解决了什么问题？
目前的版本是"@babel/preset-env": "^7.7.4"，如果运气不好（比如我。。。）其实是可能安装到7.7.4，这样很多新特效用不了。
比如 ： `可选链操作符( ?. )` 会出现编译报错。

目前依赖（^7.7.4）：
https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/package.json#L32

### 这个 API 长什么样？
升级babel-preset-taro里的@babel/preset-env 依赖

**Comment by jiaoguanwen** [comment]
me to

**Comment by jiaoguanwen** [comment]
me too

**Comment by wuchangming** [comment]
已升级
