### ISSUE TITLE
当在Swiper的SwiperItem中使用MovableView时候，moveable的滑动会被swiper捕获，希望可以为movableView 添加对微信小程序的htouchmove 和 vtouchmove 的支持

### ISSUE THREAD

**Issue by MagicLeeW** [NervJS/taro#7677]
### 这个特性解决了什么问题？
解决swiper 和 movableview一起使用，缩放拖动图片，冲突的问题。
下面是微信小程序官方提供解决的方案，可以参考：
https://developers.weixin.qq.com/community/develop/doc/000242c6bd86a82484497f2235b400?_at=1600574063533

### 这个 API 长什么样？
https://developers.weixin.qq.com/community/develop/doc/000242c6bd86a82484497f2235b400?_at=1600574063533

**Comment by Chen-jj** [comment]
@MagicLeeW `MovableView` 是支持这两个属性的。
