### ISSUE TITLE
taro switch 多种case报错

### ISSUE THREAD

**Issue by janyin** [NervJS/taro#7684]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
原代码：
renderBuyTitle = () => {

        const { orderStatus } = this.state;
        const { item } = this.props;

        switch (orderStatus) {
            case '0': {
                return(
                    <View className='buy-title'>
                        <View>
                            <Text className='buy-status'>确认后生成</Text>
                        </View>
                    </View>
                )
            }
            case '1': case '2': {
                return (
                    <View className='buy-title'>
                        <View>
                            <Text>{item.order.tid}</Text>
                            <ItemIcon icon='fuzhi' style={{ fontSize: '12px', marginLeft: '10px' }}/>
                        </View>
                        <View className='link-detail'>
                            <Text className='buy-detail'>订单详情</Text>
                            <ItemIcon icon='more' style={{ fontSize: '14px', color: '#999' }}/>
                        </View>
                    </View>
                )
            }
        }
    }

### 期望结果
不报错

### 实际结果
Module Error (from ./node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js):
含有 JSX 的 switch case 语句必须每种情况都用花括号 `{}` 包裹结果

### 环境信息
```
👽 Taro v2.2.13


  Taro CLI 2.2.13 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.13 => 2.2.13 
      @tarojs/components-qa: 2.2.13 => 2.2.13 
      @tarojs/mini-runner: 2.2.13 => 2.2.13 
      @tarojs/plugin-sass: 2.2.13 => 2.2.13 
      @tarojs/plugin-terser: 2.2.13 => 2.2.13 
      @tarojs/redux: 2.2.13 => 2.2.13 
      @tarojs/redux-h5: 2.2.13 => 2.2.13 
      @tarojs/router: 2.2.13 => 2.2.13 
      @tarojs/taro: 2.2.13 => 2.2.13 
      @tarojs/taro-alipay: 2.2.13 => 2.2.13 
      @tarojs/taro-h5: 2.2.13 => 2.2.13 
      @tarojs/taro-qq: 2.2.13 => 2.2.13 
      @tarojs/taro-quickapp: 2.2.13 => 2.2.13 
      @tarojs/taro-swan: 2.2.13 => 2.2.13 
      @tarojs/taro-tt: 2.2.13 => 2.2.13 
      @tarojs/taro-weapp: 2.2.13 => 2.2.13 
      @tarojs/webpack-runner: 2.2.13 => 2.2.13 
      eslint-config-taro: 2.2.13 => 2.2.13 
      eslint-plugin-taro: 2.2.13 => 2.2.13 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      react: ^16.13.1 => 16.13.1 
      stylelint-config-taro-rn: 2.2.13 => 2.2.13 
      stylelint-taro-rn: 2.2.13 => 2.2.13 
      taro-ui: ^2.3.4 => 2.3.4 


```

---
### 补充信息
单个case情况加了括号不报错，如果多个case合并的情况加括号报错

**Comment by janyin** [comment]
为啥没人回复

**Comment by mac-boss** [comment]
解决了吗
