### ISSUE TITLE
微信小程序中Map组件无法触发onRegionChange，并且无法获取centerLocation

### ISSUE THREAD

**Issue by puxiao** [NervJS/taro#7687]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
```
import React from 'react'
import { BaseEventOrig, BaseEventOrigFunction, Map } from '@tarojs/components'
import { MapProps } from '@tarojs/components/types/Map'

const MyMap: React.FC = () => {

    const handleRegionChange = (eve: BaseEventOrig<MapProps.onRegionChangeEventDetail>) => {
        console.log(eve)
        console.log(eve.detail.detail)
    }

    /* const handleRegionChange: BaseEventOrigFunction<MapProps.onRegionChangeEventDetail> = (eve) => {
        console.log(eve)
    } */

    return (
        <Map longitude={116.39747} latitude={39.908823} setting={{}} onRegionChange={handleRegionChange} />
    )
}

export default MyMap
```

### 期望结果
1、期望能够触发 onRegionChange 处理函数
2、期望处理函数对应的 eve.detail.detail 能够与微信地图组件对应的 detail 同样的返回值。
补充：Taro 中 regionChangeDetail 只包含：rotate、skew。而微信小程序中 regionchange 的 detail中包含：rotate、skew、scale、centerLocation、region

### 实际结果
onRegionChange 根本就没有触发

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - D:\program files (x86)\nodejs\node.EXE
      npm: 6.14.5 - D:\program files (x86)\nodejs\npm.CMD
```

---
### 补充信息
之前的 Issue 中，也有人提交过这个情况：https://github.com/NervJS/taro/issues/5766
但是文章后面有人的回复中，提到改用 onBegin 或 onEnd，经实际测试，Taro 提示 Map 组件无这2个属性。

**Comment by NaiveCAI** [comment]
Another map event related issue: https://github.com/NervJS/taro/issues/7616

**Comment by puxiao** [comment]
刚才发现，Map 的 onMarkerTap 事件也不触发...

**Comment by Chen-jj** [comment]
@puxiao #5766 正解。`onRegionChange ` 会触发两次，因为 `e.type` 分别是 begin 和 end，taro 要根据 `e.type` 触发事件，因此拆成了 `onBegin` 和 `onEnd`，效果上是一样的。类型和文档我们补充一下。

**Comment by Chen-jj** [comment]
> @puxiao #5766 正解。`onRegionChange ` 会触发两次，因为 `e.type` 分别是 begin 和 end，taro 要根据 `e.type` 触发事件，因此拆成了 `onBegin` 和 `onEnd`，效果上是一样的。类型和文档我们补充一下。

@puxiao 还是直接使用 `onRegionChange ` 吧，这样合理一点，我们改一下，3.0.15 修复。

**Comment by puxiao** [comment]
非常感谢，还记得我这个已关闭的 issues。 @Chen-jj

**Comment by Chen-jj** [comment]
@puxiao 因为上周提的 PR 发现不太合理后来又关了，今天才有空再改正一下～

**Comment by jyx12138** [comment]
@Chen-jj 大佬，怎么动态添加map  markers，项目数据量较大，要分页加载。

**Comment by Chen-jj** [comment]
> @Chen-jj 大佬，怎么动态添加map markers，项目数据量较大，要分页加载。

新开一个 issue，附上 demo，我们看看哈
