### ISSUE TITLE
taro2升级taro3.0.7  在支付宝小程序中Map组件中的onRegionChange、 onMarkerTap、onClick事件不起作用(<Map id='map' className='map' latitude={this.state.latitude} longitude={this.state.longitude} markers={this.state.markers}  show-location onRegionChange={this.getCenterLocation} onMarkerTap={this.getShopInfo} style='width: 100%; height: 100vh;' onClick={this.onTap}  />)

### ISSUE THREAD

**Issue by gaoyuan8080** [NervJS/taro#7688]
### 相关平台
支付宝小程序

**小程序基础库: >=1.24.2**
**使用框架: React**

### 复现步骤
<Map
                            id='map'
                            className='map'
                            latitude={this.state.latitude}
                            longitude={this.state.longitude}
                            markers={this.state.markers}
                            show-location
                            onRegionChange={this.getCenterLocation}
                            onMarkerTap={this.getShopInfo}
                            style='width: 100%; height: 100vh;'
                            onClick={this.onTap}
                        />

### 期望结果
Taro3 Map组件中的API在支付宝中起作用

### 实际结果
Map组件中的API在支付宝中onRegionChange、 onMarkerTap、onClick事件不起作用

### 环境信息
```
👽 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/react: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 

```

---
### 补充信息
<Map
                            id='map'
                            className='map'
                            latitude={this.state.latitude}
                            longitude={this.state.longitude}
                            markers={this.state.markers}
                            show-location
                            onRegionChange={this.getCenterLocation}
                            onMarkerTap={this.getShopInfo}
                            style='width: 100%; height: 100vh;'
                            onClick={this.onTap}
                        />
Map组件中的onRegionChange、 onMarkerTap、onClick事件不起作用

**Comment by gaoyuan8080** [comment]
<Map
                            id='map'
                            className='map'
                            latitude={this.state.latitude}
                            longitude={this.state.longitude}
                            markers={this.state.markers}
                            show-location
                            onRegionChange={this.getCenterLocation}
                            onMarkerTap={this.getShopInfo}
                            style='width: 100%; height: 100vh;'
                            onClick={this.onTap}
                        />

**Comment by Chen-jj** [comment]
@gaoyuan8080 

onRegionChange 使用 onBegin、onEnd 替代: #5766 

onMarkerTap、onClick 可以使用：

```js
import React, { Component } from 'react'
import { View, Text, Map } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {
  state = {
    markers: [{
      longitude: 116.39747,
      latitude: 39.908823
    }]
  }

  regionChangeAtBegin = (e) => {
    console.log('begin', e)
    this.setState({
      showCallout: false,
      arriveTime: null
    })
  }

  regionChangeAtEnd = (e) => {
    console.log('end', e)
    this.setState({
      showCallout: false,
      arriveTime: null
    })
  }

  handleMarkerTap = e => {
    console.log(e)
  }

  render () {
    console.log('state: ', this.state)
    return (
      <View className='index'>
        <Text>Hello world! {this.state.showCallout} {this.state.arriveTime}</Text>
        <Map id='map' className='map' latitude={39.908823} longitude={116.39747} markers={this.state.markers} show-location onBegin={this.regionChangeAtBegin} onEnd={this.regionChangeAtEnd} onMarkerTap={this.handleMarkerTap} style='width: 100%; height: 100vh;' onClick={() => console.log('click')} />
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/95873982-00d93f80-0da3-11eb-81d1-be28d5d51fbd.png)

**Comment by Chen-jj** [comment]
> @gaoyuan8080
> 
> onRegionChange 使用 onBegin、onEnd 替代: #5766

还是直接使用 onRegionChange 吧，这样合理一点，我们改一下，3.0.15 修复。

**Comment by guo897654050** [comment]
> > @gaoyuan8080
> > onRegionChange 使用 onBegin、onEnd 替代: #5766
> 
> 还是直接使用 onRegionChange 吧，这样合理一点，我们改一下，3.0.15 修复。

3.0系列 onClick并不能使用 ide没问题，预览或者调试都无法触发click事件
