### ISSUE TITLE
编译h5时报错: _router2.default.initRouter is not a function

### ISSUE THREAD

**Issue by kscript** [NervJS/taro#769]
**问题描述**
初始化项目完, 什么都不做, 直接编译h5, 也会报这个错

**复现步骤**
```js
taro init taro
cd taro
npm run dev:h5
```

**Comment by kscript** [comment]
查了下提交记录: 在 a376b79d8 版本中去掉了initRouter, 但是这个函数在tarojs/cli@1.0.3里还在使用

解决办法:
taro-router 退回到 1.0.5

**Comment by PlutoCA** [comment]
你好问下，我@tarojs/router 已经更新到1.0.7，请问怎么回退到1.0.5

**Comment by kscript** [comment]
> 你好问下，我@tarojs/router 已经更新到1.0.7，请问怎么回退到1.0.5

在package.json里将@tarojs/router改成1.0.5, 然后再cnpm install下即可

**Comment by luckyadam** [comment]
全部升级到 1.0.7 应该可以解决

**Comment by sch1111878** [comment]
> @luckyadam 我也遇到相同问题，退回到1.0.5， 问题可以解决。 可像您说的全部升级到1.0.7， 但问题还在。
> 
> 升级用的是下面的命令：
> taro update self
> taro update project

1.2.0-beta.7 是目前最新也不可用,已经退回 1.0.5 可以了
