### ISSUE TITLE
Swiper nextMargin属性在H5上不生效，编译成小程序是生效的

### ISSUE THREAD

**Issue by zebratt** [NervJS/taro#7703]
### 相关平台
H5

### 复现仓库
[https://github.com/zebratt/taro-issue-report](https://github.com/zebratt/taro-issue-report)
**浏览器版本: chrome 85.0.4183.102**
**使用框架: React**

### 复现步骤
yarn dev:h5

### 期望结果
H5上swiper组件正常显示nextMargin

### 实际结果
H5上swiper组件设置nextMargin后不生效，仅在小程序生效

### 环境信息
```
 Taro CLI 3.0.8 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.8 => 3.0.8 
      @tarojs/mini-runner: 3.0.8 => 3.0.8 
      @tarojs/react: 3.0.8 => 3.0.8 
      @tarojs/runtime: 3.0.8 => 3.0.8 
      @tarojs/taro: 3.0.8 => 3.0.8 
      @tarojs/webpack-runner: 3.0.8 => 3.0.8 
      babel-preset-taro: 3.0.8 => 3.0.8 
      eslint-config-taro: 3.0.8 => 3.0.8 
      react: ^16.10.0 => 16.13.1 
```

**Comment by zebratt** [comment]
**H5展示：**

![image](https://user-images.githubusercontent.com/7269427/93981176-2f6e8680-fdb2-11ea-8051-bd29f205ff6f.png)

**小程序是正常的：**

![Uploading image.png…]()

**Comment by zhaoguoweiLLHC** [comment]
.swiper-container {
  //width: 100%; 去掉这个100%宽度，因为会和nextMargin，previousMargin相互影响导致页面异常。
  height: 300px;

**Comment by zebratt** [comment]
> .swiper-container {
> //width: 100%; 去掉这个100%宽度，因为会和nextMargin，previousMargin相互影响导致页面异常。
> height: 300px;

去掉了还是没有变化。

**Comment by ZakaryCode** [comment]
升级版本咯，这个问题近期修复过

**Comment by zebratt** [comment]
升级到 3.0.11 解决了，thx~
