### ISSUE TITLE
H5中，scrollView的onScrollToLower有问题

### ISSUE THREAD

**Issue by xingBri** [NervJS/taro#771]
**问题描述**
scrollView的onScrollToLower，在升级到稳定版之后，出现了问题。
问题是只要滑动，就会触发这个事件。

**复现步骤**

```js
// 这里可以贴代码
<ScrollView
          className="scroll-wrap"
          lowerThreshold="200"
          scrollY
          onScrollToLower={this.scrollToBottom.bind(this)}
        >
</ScrollView>
```

**期望行为**
在beta版时没有发现有问题，
期望的行为是在滑动到底部才触发

**系统信息**

 - Taro 版本 [e.g. 1.0.7]

**Comment by xingBri** [comment]
还有这个问题，也希望能看一下[#720](https://github.com/NervJS/taro/issues/720)

**Comment by jinjinjin0731** [comment]
升级到最新版可以关闭ok
