### ISSUE TITLE
taro官网在移动端下样式异常

### ISSUE THREAD

**Issue by zhaoguoweiLLHC** [NervJS/taro#7714]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
用手机打开taro官网

### 期望结果
页面充满整个手机屏幕
![b18d73b3e408ccd4384744c35144b63](https://user-images.githubusercontent.com/23580548/94218272-b0469300-ff16-11ea-9ecb-bbde2d6504fd.png)

### 实际结果
内容只在屏幕的左侧一半
![1cb0a664d618192badd231d24b3d92f](https://user-images.githubusercontent.com/23580548/94218308-cb190780-ff16-11ea-9d38-b04aad457571.png)

### 环境信息
```
� Taro v3.0.10


  Taro CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD

```

**Comment by shenghanqin** [comment]
@honlyHuang 帮忙看看吧

**Comment by Chen-jj** [comment]
已修复
