### ISSUE TITLE
vue3 plugin , getCurrentInstance()  开发环境与生产环境结果不一致

### ISSUE THREAD

**Issue by linfun486** [NervJS/taro#7718]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/linfun486/taro-2020.9.24-issue](https://github.com/linfun486/taro-2020.9.24-issue)
**小程序基础库: 2.13.0**
**使用框架: Vue 3**

### 复现步骤
通过 taro build --type weapp  --watch打包出的结果正常  
通过taro build --type weapp  打包的结果异常， 具体表现为:  
1. const {ctx} = getCurrentInstance(), 这里的ctx两种打包方式下取值不同
2.  ctx.$plugins 均undefined

### 期望结果
开发环境与生产环境打包结果一致

### 实际结果
打包结果不一致， 产生报错，vue3 plugin product下无法undefined

### 环境信息
```
Taro CLI 3.0.11 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.11 => 3.0.11 
      @tarojs/mini-runner: 3.0.11 => 3.0.11 
      @tarojs/runtime: 3.0.11 => 3.0.11 
      @tarojs/taro: 3.0.11 => 3.0.11 
      @tarojs/webpack-runner: 3.0.11 => 3.0.11 
      babel-preset-taro: 3.0.11 => 3.0.11 
      eslint-config-taro: 3.0.11 => 3.0.11 

```

**Comment by Chen-jj** [comment]
@linfun486 Vue3 就是这样设定的：
