### ISSUE TITLE
Swiper组件轮播异常

### ISSUE THREAD

**Issue by Manuel-XD** [NervJS/taro#772]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
Swiper在设置autoplay后可以自动轮播，但是在触发过一次滑动事件后，自动轮播失效。
**复现步骤**
[复现问题的步骤]

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
手动的滑动swiper不影响自动轮播。同时希望可以加入一个属性可以用来控制轮播图触发滑动的距离。现在的轮播触发不够灵敏，需要滑动50%宽度才能到下一张。
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v1.0.0-beta.28]
 - Node.js 版本 [v8.9.3]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
请升级到最新版本试试~

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/f9c6dfd45e7366bf2b2f0cf2918e89804b0de1f3
