### ISSUE TITLE
控制台报如下错误【RangeError: Maximum call stack size exceeded】

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro#773]
**问题描述**
控制台报如下错误

**报错信息**
![image](https://user-images.githubusercontent.com/16408873/46591826-06368c00-caf0-11e8-9189-8c4e5222c839.png)

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.0.7]
 - Node.js 版本

**Comment by luckyadam** [comment]
`pages/index/index` 这个页面的代码能不能贴出来看看

**Comment by jiangzeyin** [comment]
后面改了些代码，不知道到底是哪里影响的了，暂时无法复现了

**Comment by itboke** [comment]
> 后面改了些代码，不知道到底是哪里影响的了，暂时无法复现了

请问你是如何解决这个问题的，我也遇到了。没有修改过任何代码，初始化项目后，npm run dev:weapp就报这个错了。
