### ISSUE TITLE
VirtualList 的 itemSize 只能是 number，能否支持字符串，小程序的 rpx?

### ISSUE THREAD

**Issue by wang777777** [NervJS/taro#7738]
### 这个特性解决了什么问题？
虚拟滚动 itemSize 类型为 number，实际情况是 VirtualList 组件里写的是px，这样就导致不同的设备类型不适配，能否支持写rpx? 或者告知下 itemSize 适配不同设备的方法？

### 这个 API 长什么样？
itemSize 可以写字符串，支持 rpx

**Comment by SirSong** [comment]
Taro.pxTransform 转换下？

**Comment by chenchenpp** [comment]
这个怎么解决的？

**Comment by hardywu** [comment]
压根就别用virtuallist，这个组件没放进导出模块就是因为没写好。

**Comment by ZakaryCode** [comment]
> 虚拟滚动 itemSize 类型为 number，实际情况是 VirtualList 组件里写的是px，这样就导致不同的设备类型不适配，能否支持写rpx? 

不太可能支持，如果该参数支持更多单位会导致虚拟列表复杂度上升，且 rpx 一类单位无法在组件内计算相关值，这会导致组件显示出现错误

> 或者告知下 itemSize 适配不同设备的方法

由于该参数仅对应子节点高度，需要额外适配耗费的情况比较少，同时对于该类情况可以通过 pxTransform 将子节点高度与 itemSize 对齐
