### ISSUE TITLE
原生组件使用less文件不编译

### ISSUE THREAD

**Issue by wandiao** [NervJS/taro#774]
**问题描述**
原生组件样式使用less, 执行npm run dev:weapp没有编译到dist目录

**复现步骤**
执行npm run dev:weapp， 样式未生效
打开对应的less文件点击保存，样式生效
![image](https://user-images.githubusercontent.com/23516461/46594215-2112fb80-cb04-11e8-9a03-93372b9fc8b9.png)

**期望行为**
直接运行样式生效

**系统信息**
 - Taro 版本 1.0.7

**Comment by luckyadam** [comment]
@wandiao 在组件 js 文件里引用一下这个 less 文件

**Comment by wandiao** [comment]
原生组件好像没有办法引入样式文件

**Comment by luckyadam** [comment]
@wandiao 可以的，用 require('../path/xx.less')
