### ISSUE TITLE
<span> tag not be rendered when render html

### ISSUE THREAD

**Issue by yinxin630** [NervJS/taro#7746]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/yinxin630/render-html-bug](https://github.com/yinxin630/render-html-bug)

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
1. clone the repo
2. `yarn install`
3. `yarn dev:weapp`
4. open it in wechat devtool

### 期望结果
render `<span>` tag

### 实际结果
`<span>` tag not be rendered

### 环境信息
```
$ taro info
👽 Taro v3.0.11


  Taro CLI 3.0.11 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.11 => 3.0.11
      @tarojs/mini-runner: 3.0.11 => 3.0.11
      @tarojs/react: 3.0.11 => 3.0.11
      @tarojs/runtime: 3.0.11 => 3.0.11
      @tarojs/taro: 3.0.11 => 3.0.11
      @tarojs/webpack-runner: 3.0.11 => 3.0.11
      babel-preset-taro: 3.0.11 => 3.0.11
      eslint-config-taro: 3.0.11 => 3.0.11
      react: ^16.10.0 => 16.13.1
```

**Comment by yinxin630** [comment]
bug screenshot
![image](https://user-images.githubusercontent.com/6939365/94344653-539cc280-0053-11eb-8b84-ad3c36913d95.png)

**Comment by ZakaryCode** [comment]
Taro currently does not support the use of HTML tags to render mini-program. If it is only used on the web, it is feasible to skip our code detection run by injection. However, please note that this writing method will not be officially supported.
