### ISSUE TITLE
Taro 3.0.10 开始，Button组件嵌套报 called recursively，导致组件不显示

### ISSUE THREAD

**Issue by AvanckYoung** [NervJS/taro#7747]
### 相关平台
微信小程序

**小程序基础库: 2.11.2**
**使用框架: React**

### 复现步骤
页面添加以下代码，组件显示就会有问题
![image](https://user-images.githubusercontent.com/8371138/94388209-e9813c00-017e-11eb-85da-e27461aa16c3.png)

### 期望结果
组件正常显示

### 实际结果
组件显示不显示，终端输出警告 ./base.wxml:-1:-1:-1: Template `./base.wxml:tmpl_0_button` is being called recursively, will be stop.

### 环境信息
```
Taro CLI 3.0.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.1.0 - D:\APP\NVM\node\node.EXE
      Yarn: 1.22.4 - D:\APP\NVM\npm\yarn.CMD
      npm: 6.14.4 - D:\APP\NVM\node\npm.CMD
```

**Comment by luckyadam** [comment]
请提供一下代码写法

**Comment by AvanckYoung** [comment]
<Button>
    <Button>按钮</Button>
</Button>
提交的时候代码丢失了

**Comment by AvanckYoung** [comment]
![image](https://user-images.githubusercontent.com/8371138/94388209-e9813c00-017e-11eb-85da-e27461aa16c3.png)

**Comment by pangnate** [comment]
3.0.14  swiper 组件同样不支持嵌套，导致子 swiper 丢失，报错和楼主一样。其他组件暂未测试。 @luckyadam

**Comment by Chen-jj** [comment]
@AvanckYoung `Button` 不需要再嵌套 `Button`，我们觉得不会有这种情况，语义、样式上都不适合，默认 `Button` 不允许嵌套调用。

**Comment by Chen-jj** [comment]
@pangnate `Swiper` 3.0.16 后可嵌套
