### ISSUE TITLE
从3.0.11更新到3.0.13后编译报错缺少包  需要手动安装2个babel包才行

### ISSUE THREAD

**Issue by ILoveChy** [NervJS/taro#7751]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
通过ncu -u升级package.json 然后 yarn 安装后  提示 Cannot find module '@babel/plugin-proposal-optional-chaining' 手动安装后再次编译提示 Cannot find module '@babel/plugin-transform-spread' 再次手动安装后编译成功

### 期望结果
可顺滑更新

### 实际结果
需要手动添加babel包才行

### 环境信息
```
� Taro v3.0.13


  Taro CLI 3.0.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.7 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
目测是之前一个PR里添加了可选链导致的? #7698

**Comment by ZakaryCode** [comment]
使用的第三方源安装么？第三方源同步错误会导致该问题，需要手动 sync 修复

**Comment by ILoveChy** [comment]
> 使用的第三方源安装么？第三方源同步错误会导致该问题，需要手动 sync 修复

确实是因为这个原因 感谢
