### ISSUE TITLE
H5环境，Tabbar会导致 usePageScroll useReachBottom 不触发<Taro 3.0.13  React>

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#7752]
### 相关平台
H5

### 复现仓库
[https://github.com/cpocar/taro-demo-app](https://github.com/cpocar/taro-demo-app)
**浏览器版本: Chrome82****小程序基础库: H5的Bug**
**使用框架: React**

### 复现步骤
git clone https://github.com/cpocar/taro-demo-app && cd taro-demo-app
yarn
yarn dev:h5

### 期望结果
pages/[a|b|c] /index 页面中的 usePageScroll useReachBottom 均触发

### 实际结果
pages/[a|b|c] /index 页面中的 usePageScroll useReachBottom 均不触发

### 环境信息
```
$ taro info
👽 Taro v3.0.13


  Taro CLI 3.0.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.13 => 3.0.13 
      @tarojs/components: 3.0.13 => 3.0.13 
      @tarojs/mini-runner: 3.0.13 => 3.0.13 
      @tarojs/react: 3.0.13 => 3.0.13 
      @tarojs/runtime: 3.0.13 => 3.0.13 
      @tarojs/taro: 3.0.13 => 3.0.13 
      @tarojs/webpack-runner: 3.0.13 => 3.0.13 
      babel-preset-taro: 3.0.13 => 3.0.13 
      eslint-config-taro: 3.0.13 => 3.0.13 
      react: 16.13.1 => 16.13.1 
    npmGlobalPackages:
      typescript: 3.7.4
```

---
### 补充信息
发现注释掉app.config.ts中的tabBar 配置后可以正常触发各页面的 usePageScroll useReachBottom ， 猜想是tabbar导致的， Taro 3.0.9 至3.0.13 貌似均有这个问题

**Comment by IMSupperkaka** [comment]
3.0.16依然存在问题

**Comment by zhaoguoweiLLHC** [comment]
我也遇到这个问题，最后用scrollview 代替了。
