### ISSUE TITLE
Taro3 page.selectComponent 获取不到原生第三方组件实例

### ISSUE THREAD

**Issue by JasonBoy** [NervJS/taro#7758]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/jasondu/wxa-plugin-canvas](https://github.com/jasondu/wxa-plugin-canvas)
**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
1. 引用海报组件 https://github.com/jasondu/wxa-plugin-canvas
2. 调用Post.create时报 `请设置组件的id="poster"!!!`， 
3. 看了下里面的源码 
```
let ctx = pages[pages.length - 1];
  if (that) ctx = that;
  const poster = ctx.selectComponent(options.selector); //返回null
```

### 期望结果
正常返回poster实例

### 实际结果
null， 试了下用ref 也只有 `TaroElement`, 无法获取原生组件实例， 导致poster初始化失败

### 环境信息
```
Taro CLI 3.0.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh

```

---
### 补充信息
taro1.x 没问题

**Comment by luckyadam** [comment]
请给一下使用的组件的相关代码，最好能给个 demo

**Comment by JasonBoy** [comment]
@luckyadam https://github.com/JasonBoy/taro3-demo 这个demo你看下，taro cli生成然就加了个wxa-plugin-canvas 库

**Comment by JasonBoy** [comment]
我把 wxa-plugin-canvas手动copy到src下，然后usingComponents从组件里面移到index.config.js里，然后似乎可以跑起来了 😅

**Comment by Chen-jj** [comment]
组件没有配置文件，只有页面才有 index.config.js

**Comment by dompling** [comment]
> 组件没有配置文件，只有页面才有 index.config.js

您好，我遇到类似的问题，引入组件之后能正常使用，在 2.x 的时候用 ref 能调用第三方组件的方法，但是在 3.x 的时候用 ref 拿到的是 TaroElement ，没办法再调用第三方组件的方法了。使用selectComponent 也好像返回的组件是 null

**Comment by Chen-jj** [comment]
@dompling 提供一下 demo 咯

**Comment by soneway** [comment]
> > 组件没有配置文件，只有页面才有 index.config.js
> 
> 您好，我遇到类似的问题，引入组件之后能正常使用，在 2.x 的时候用 ref 能调用第三方组件的方法，但是在 3.x 的时候用 ref 拿到的是 TaroElement ，没办法再调用第三方组件的方法了。使用selectComponent 也好像返回的组件是 null

遇到相同问题

**Comment by HRBully** [comment]
遇到相同问题, 3.6.23,微信小程序
