### ISSUE TITLE
tabBar自定义图片报错

### ISSUE THREAD

**Issue by gaobo267258113** [NervJS/taro#776]
初始化空项目，报错。
![image](https://user-images.githubusercontent.com/9426000/46596755-2c6c2400-cb10-11e8-986d-c71952d508aa.png)

**Comment by gaobo267258113** [comment]
rn端

**Comment by Pines-Cheng** [comment]
iconPath 和 selectedPath 的定义图片是同一个路径导致的重复引用，这边会在编译时做一下兼容处理。
