### ISSUE TITLE
钉钉小程序 安卓真机 设置Map的latitude、longitude无效，永远显示在北京

### ISSUE THREAD

**Issue by cx222333** [NervJS/taro#7762]
### 相关平台
支付宝小程序

**小程序基础库: 1.14.5**
**使用框架: React**

### 复现步骤
const MapTest = () => {
  const [{ latitude, longitude }, dispatch] = useReducer(
    (state, data) => ({ ...state, ...data }),
    { latitude: 0, longitude: 0 }
  );

  useEffect(() => {
    getLocation().then((res) => {
      dispatch({ latitude: res.latitude, longitude: res.longitude });
    });
  }, []);

  return <Map latitude={latitude} longitude={longitude} />;
};

export default MapTest;

### 期望结果
地图移动到设置的中心经纬度

### 实际结果
永远在北京

### 环境信息
```
 Taro v3.0.11


  Taro CLI 3.0.11 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.11 => 3.0.11 
      @tarojs/mini-runner: 3.0.11 => 3.0.11 
      @tarojs/react: 3.0.11 => 3.0.11 
      @tarojs/runtime: 3.0.11 => 3.0.11 
      @tarojs/taro: 3.0.11 => 3.0.11 
      @tarojs/webpack-runner: 3.0.11 => 3.0.11 
      babel-preset-taro: 3.0.11 => 3.0.11 
      eslint-config-taro: 3.0.11 => 3.0.11 
      react: ^16.10.0 => 16.13.1 
```

**Comment by cx222333** [comment]
还有属性polygons 在支付宝跟钉钉 应该为 polygon

**Comment by cx222333** [comment]
> @cx222333 提供一下完整可复现 demo 咯

https://github.com/cx222333/taro-test

**Comment by Chen-jj** [comment]
@cx222333 先加一个 setting 配置咯：

```js
<Map latitude={latitude} longitude={longitude} polygons={polygons} setting={{}} />
```
