### ISSUE TITLE
使用的npm包中引入了  import 'regenerator-runtime/runtime' 构建时报错

### ISSUE THREAD

**Issue by soulcm** [NervJS/taro#7765]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
npm包使用了babel-runtime，编译出的js中包含  import 'regenerator-runtime/runtime'

### 期望结果
不报错，编译通过

### 实际结果
变通出错
Module not found: Can't resolve 'regenerator-runtime/runtime' in 'xxxx'
Parsed request is a module

### 环境信息
```
Taro CLI 3.0.11 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.14.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.11 => 3.0.11 
      @tarojs/components: 3.0.11 => 3.0.11 
      @tarojs/mini-runner: 3.0.11 => 3.0.11 
      @tarojs/react: 3.0.11 => 3.0.11 
      @tarojs/runtime: 3.0.11 => 3.0.11 
      @tarojs/taro: 3.0.11 => 3.0.11 
      @tarojs/webpack-runner: 3.0.11 => 3.0.11 
      babel-preset-taro: 3.0.11 => 3.0.11 
      eslint-config-taro: 3.0.11 => 3.0.11 
      react: 16.12.0 => 16.12.0
```

**Comment by Chen-jj** [comment]
@soulcm 提供一下 demo 咯

**Comment by soulcm** [comment]
babel配置 使用runtime插件以及preset-env, 代码中写上```async```  ```await```函数, 编译出的代码中将包含 ```import 'regenerator-runtime/runtime';```的代码
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false,
        useBuiltIns: 'usage'
      },
    ]
  ],
  plugins: [
    '@babel/plugin-transform-runtime',
  ],
};
```

使用taro/cli工具编译小程序，小程序代码中引入此代码库，将会报上面所描述的错误（编译config中使用官方默认配置）

**Comment by soulcm** [comment]
![image](https://user-images.githubusercontent.com/5706155/95807011-ba9cc580-0d3b-11eb-97c0-91491bfcf87d.png)
目前我将其alias掉，编译没报错了，但不知道有没有什么其他影响

**Comment by JuSanZhi** [comment]
我也遇到同样的问题， 
![image](https://user-images.githubusercontent.com/24559368/115685635-fbc8fe80-a38a-11eb-81d6-916518b3230a.png)

**Comment by Chen-jj** [comment]
没有复现，Taro 内部默认的 webpack 配置是设置了 alias 的：

https://github.com/NervJS/taro/blob/8b50c4e9629a259ab94e5f611a42b7df4d66bc86/packages/taro-mini-runner/src/webpack/base.conf.ts#L18

**Comment by miaomiaoG** [comment]
> 没有复现，Taro 内部默认的 webpack 配置是设置了 alias 的：
> 
> https://github.com/NervJS/taro/blob/8b50c4e9629a259ab94e5f611a42b7df4d66bc86/packages/taro-mini-runner/src/webpack/base.conf.ts#L18

我这边遇到了一个问题，微信小程序编译会报找不到regenerator-runtime/runtime的错，把node_modules/@tarojs/mini-runner/dist/webpack/base.conf.js以及node_modules/@tarojs/webpack5-runner/dist/webpack/MiniBaseConfig.js 的alias的'regenerator-runtime'配置注释掉就可以了，这是什么原因呢？
