### ISSUE TITLE
初始化模板提供函数式编程 hook方式

### ISSUE THREAD

**Issue by DreamPWJ** [NervJS/taro#7766]
### 这个特性解决了什么问题？
解决使用函数式编程习惯的用户

### 这个 API 长什么样？
const Home = () => {
  const {params: {id}} = useRouter();
  const [value, setValue] = useState("");
  useEffect(() => {
}
  useDidShow(() => {
}
  const onHandle = (data) => {
    console.log(data);
  }
  return (<></>)
}

**Comment by zhaoguoweiLLHC** [comment]
```typescript jsx
import React from 'react';
import {Text, View} from "@tarojs/components";
import './index.scss';

export default () => {
 
    return <View className='index'>
        <Text>Hello Taro</Text>
    </View>
}
```

**Comment by ZakaryCode** [comment]
fix in #13632
