### ISSUE TITLE
Taro.setTabBarItem中的图片不能被正确的打包

### ISSUE THREAD

**Issue by yohhhs** [NervJS/taro#7769]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
Taro.setTabBarItem设置iconPath，编译过后图片不能显示，在dist文件夹中找不到对应的图片，没有被正确的打包

### 期望结果
图片能被正确的打包

### 实际结果
图片没有被打包

### 环境信息
```
 Taro CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
编译的时候没有正确识别到图片被引用，打包的时候被忽略掉了

**Comment by Chen-jj** [comment]
可以配置 [copy](https://docs.taro.zone/docs/config-detail#copy)，手动把可能需要用到的图片加到编译产物中

编译时去扫描此 API 的调用不太可取，因为 iconPath 不一定是字符串，有可能是变量，编译时没有办法准确做出识别。
