### ISSUE TITLE
scrollView滚动到最底部的情况下添加删除最底部内容会触发onScrollToLower事件

### ISSUE THREAD

**Issue by blueskink** [NervJS/taro#777]
**问题描述**
scrollView滚动到最底部的情况下，添加删除最底部内容会触发onScrollToLower事件。
**复现步骤**
[复现问题的步骤]
```js
        <ScrollView>
                {loading&&<view>加载中...</view>}
        </ScrollView>
```

**期望行为**
不触发onScrollToLower事件
**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**
- Taro 版本 [e.g. v1.0.3]
**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
添加删除最底部内容会触发onScrollToLower事件.  此时是否是在容器的最底部？

**Comment by blueskink** [comment]
> 添加删除最底部内容会触发onScrollToLower事件. 此时是否是在容器的最底部？

在，我在onScrollToLower事件触发的时候，添加一个‘加载中’的元素提示加载，然后加载结束后移除这个‘加载中’的提示，如同代码所示。 实际效果是删除‘加载中’提示元素的时候会触发事件，导致死循环。

**Comment by jinjinjin0731** [comment]
这么说 H5 可能是有这个问题，我这边复现一下。   小程序中不会是吧？

**Comment by jinjinjin0731** [comment]
可以提供一个可复现的代码片段吗。 我这边本地尝试你这种做法 ， 在 H5 中和 小程序中都会出现这种死循环，onScrollToLower 是会被触发的，所以这种场景是对的，两端保持一致。

**Comment by jinjinjin0731** [comment]
@blueskink  hi 朋友~ 还有啥问题不~
