### ISSUE TITLE
ios14上textarea去掉 iOS 下的默认内边距不生效

### ISSUE THREAD

**Issue by Pilotager** [NervJS/taro#7770]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
<Textarea
                className='content-write-textarea'
                value={'                '}
                showConfirmBar={false}
                disableDefaultPadding
              />

### 期望结果
默认内边距在ios上设置之后生效，内边距消失

### 实际结果
属性不生效

### 环境信息
```
Taro CLI 3.0.6 environment info:
    System:
      OS: macOS 11.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^3.0.10 => 3.0.13
      @tarojs/mini-runner: 3.0.6 => 3.0.6
      @tarojs/react: ^3.0.10 => 3.0.13
      @tarojs/runtime: ^3.0.10 => 3.0.13
      @tarojs/taro: ^3.0.10 => 3.0.13
      @tarojs/webpack-runner: 3.0.6 => 3.0.6
      babel-preset-taro: 3.0.6 => 3.0.6
      eslint-config-taro: 3.0.6 => 3.0.6
      react: ^16.13.1 => 16.13.1
      taro-ui: ^2.3.4 => 2.3.4
```

**Comment by lesinliu** [comment]
解决了吗 taro-next出现这个问题了

**Comment by Pilotager** [comment]
还没有~

lesin <notifications@github.com> 于2020年10月20日周二 上午9:36写道：

**Comment by Przeblysk** [comment]
一样的问题

**Comment by Przeblysk** [comment]
看了下源码 Textarea.d.ts 中有定义disableDefaultPadding 但是在textarea.tsx中没有
```
<textarea
        ref={input => {
          if (input) {
            this.textareaRef = input
          }
        }}
        class='taro-textarea'
        value={fixControlledValue(value)}
        placeholder={placeholder}
        name={name}
        disabled={disabled}
        maxlength={maxlength}
        autofocus={autoFocus}
        onInput={hanldeInput}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onChange={handleChange}
/>
```

**Comment by ybrelax** [comment]
解决了吗？现在这个问题还有出现

**Comment by nanxiaobei** [comment]
依然存在这个问题，代码里就发现个 types。

https://github.com/NervJS/taro/search?q=disableDefaultPadding

**Comment by nanxiaobei** [comment]
还有小程序的 `textarea` 组件有 `confirm-type`，而 Taro 的没有 `confirmType`。

https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html

https://taro-docs.jd.com/taro/docs/components/forms/textarea/

**Comment by Chen-jj** [comment]
最新版本 `disableDefaultPadding` 属性已可用。
