### ISSUE TITLE
Taro V3.0.10  Map组件，onRegionChange无效

### ISSUE THREAD

**Issue by guopenghui1003** [NervJS/taro#7773]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
<Map
        className="map-contain"
        longitude={longitude}
        latitude={latitude}
        onClick={this.onTap}
        onRegionChange={this.onRegionChange}
      ></Map>

### 期望结果
onRegionChange={this.onRegionChange}能被触发

### 实际结果
地图视图区域变化，没有触发

### 环境信息
```
$ taro info
馃懡 Taro v3.0.10


  Taro CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
https://github.com/NervJS/taro/issues/5766#issuecomment-602526273

**Comment by Chen-jj** [comment]
还是直接使用 onRegionChange 吧，这样合理一点，我们改一下，3.0.15 修复。
