### ISSUE TITLE
taro v3.0.7之后的版本，打包成头条或者支付宝小程序都会报错

### ISSUE THREAD

**Issue by git-guining** [NervJS/taro#7775]
### 相关平台
支付宝小程序

**小程序基础库: 头条1.80.1.6  支付宝无**
**使用框架: Vue 2**

### 复现步骤
npm run dev:tt或者npm run dev:alipay，会报
Error: ./comp.axml?hash=bb8b295024249ccbe94d8d9630088b07e56ab94c
Module build failed :
Error: comp.axml
Module build failed:
\base.wxml.axml not exists!

### 期望结果
打包编译后可以正常运行小程序，不报错

### 实际结果
打包编译后，头条和支付宝小程序无法运行

### 环境信息
```
👽 Taro v3.0.13


  Taro CLI 3.0.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
有没有示例项目看看

**Comment by git-guining** [comment]
不好意思，公司的项目不好公开。你那边打包都正常吗。

**Comment by Chen-jj** [comment]
@git-guining 重新安装依赖试试吧

**Comment by git-guining** [comment]
重新安装依赖之后还是一样的。只有用3.0.7以及之前的版本打包不会出错，后面所有版本都会报错。

**Comment by Chen-jj** [comment]
@git-guining  没有复现，估计是依赖问题，再检查下吧。

**Comment by lightShowers** [comment]
你那是报的啥错  我这是3.0.16版本    打包之后   首页是 Welcome to MIni Program
![1606189471(1)](https://user-images.githubusercontent.com/46345829/100044411-9b20ae80-2e4a-11eb-88a4-47c2841d0d19.jpg)

**Comment by git-guining** [comment]
我之前还是依赖的问题，目前已经没有打包的问题了

**Comment by oscar92420aaa** [comment]
楼主怎么解决的啊是哪个依赖产生这个问题啊，求说清楚

**Comment by git-guining** [comment]
更新taro之后一定要更新对应的依赖，就不会报错了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月19日(周一) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NervJS/taro] taro v3.0.7之后的版本，打包成头条或者支付宝小程序都会报错 (#7775)




 
楼主怎么解决的啊是哪个依赖产生这个问题啊，求说清楚
