### ISSUE TITLE
Readme 里面“5 分钟上手 Taro 开发” 打开之后 的页面有一个链接打开显示“404”

### ISSUE THREAD

**Issue by fayeah** [NervJS/taro#7785]
### 相关平台
微信小程序

**小程序基础库: NONE**
**使用框架: React**

### 复现步骤
打开链接“https://taro-docs.jd.com/taro/docs/guide/ ”， 找到超链接文本“文档” ，点开之后显示"Page Not Found"，URL为“https://taro-docs.jd.com/taro/docs/guide/README ”，而正确的URL是“https://taro-docs.jd.com/taro/docs/README/  ”。
![image](https://user-images.githubusercontent.com/29644978/94709602-70e5cf80-0378-11eb-9599-704a9d63be02.png)

### 期望结果
点击“文档”关键字，能正常打开期望的页面。

### 实际结果
“Page Not Found | Taro 文档”
![image](https://user-images.githubusercontent.com/29644978/94709363-367c3280-0378-11eb-9da4-f71c2a39a793.png)

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.2 - ~/.nvm/versions/node/v12.4.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14
      @tarojs/mini-runner: 3.0.14 => 3.0.14
      @tarojs/react: 3.0.14 => 3.0.14
      @tarojs/runtime: 3.0.14 => 3.0.14
      @tarojs/taro: 3.0.14 => 3.0.14
      @tarojs/webpack-runner: 3.0.14 => 3.0.14
      babel-preset-taro: 3.0.14 => 3.0.14
      eslint-config-taro: 3.0.14 => 3.0.14
      react: ^16.10.0 => 16.13.1
    npmGlobalPackages:
      typescript: 3.5.3
```

**Comment by Chen-jj** [comment]
已修复
