### ISSUE TITLE
根目录下的app.config通过alias引用文件，会提示找不到模块

### ISSUE THREAD

**Issue by babycannotsay** [NervJS/taro#7786]
### 相关平台
H5

**浏览器版本: chrome85**
**使用框架: React**

### 复现步骤
https://taro-docs.jd.com/taro/docs/config-detail/#alias
按照以上流程配置alias，在ui组件中通过alias引用文件没有问题，但是在src/app.config中引用并使用，就会提示Cannot find module '@/xx'

### 期望结果
app.config下引用也正常

### 实际结果
Cannot find module '@/xx'，服务直接起不来了

### 环境信息
```
 Taro CLI 3.0.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
确实没有支持在 *.config 里使用 alias

**Comment by ZakaryCode** [comment]
supported in #14825
