### ISSUE TITLE
1.3 版本的web-pack runner好像不支持插件自定义

### ISSUE THREAD

**Issue by knonginda** [NervJS/taro#7788]
### 这个特性解决了什么问题？
我想在config/index.js的plugins里加入html-webpack-plugin和preload-webpack-plugin，支持js分包的prefetch功能

### 这个 API 长什么样？
1.3的配置文档里好像不支持自定义插件，是一个对象，只能添加预设好的四个插件：
plugins: {
    babel, uglify, csso,  sass
},

但更高版本的配置文件，是可以支持的，是一个数组，里面可以自己添加插件
plugins: [],

**Comment by luckyadam** [comment]
你好，1.x 只有 H5 是使用 webpack 编译的，如果想要配置 webpack 相关插件可以在 [h5.webpackChain](https://docs.taro.zone/docs/1.3.45/config-detail#h5webpackchain) 里配置

**Comment by knonginda** [comment]
@luckyadam 
按照文档配置如下：

    webpackChain (chain, webpack) {
      chain.merge({
        plugin: {
          HtmlWebpackPlugin: {
            plugin: require('html-webpack-plugin')
          },
          PreloadWebpackPlugin: {
            plugin: require('preload-webpack-plugin'),
            args: [{
              rel: 'prefetch'
            }]
          }
        }
      })

**编译的时候报了如下错误信息，能帮忙看看是怎么回事吗？谢谢**
Error: Chunk.parents: Use ChunkGroup.getParents() instead
  
  - Chunk.js:827 Chunk.get
    [applet]/[webpack]/lib/Chunk.js:827:9
  
  - index.js:40 doesChunkBelongToHTML
    [applet]/[preload-webpack-plugin]/index.js:40:30
  
  - index.js:116 
    [applet]/[preload-webpack-plugin]/index.js:116:61
  
  - Array.filter
  
  - index.js:116 
    [applet]/[preload-webpack-plugin]/index.js:116:45
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [applet]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 promisedApplyPluginsAsyncWaterfall
    [applet]/[webpack-runner]/[html-webpack-plugin]/index.js:673:47
  
  - index.js:178 
    [applet]/[webpack-runner]/[html-webpack-plugin]/index.js:178:18

**Comment by GitKou** [comment]
> @luckyadam 按照文档配置如下：
> 
> ```
> webpackChain (chain, webpack) {
>   chain.merge({
>     plugin: {
>       HtmlWebpackPlugin: {
>         plugin: require('html-webpack-plugin')
>       },
>       PreloadWebpackPlugin: {
>         plugin: require('preload-webpack-plugin'),
>         args: [{
>           rel: 'prefetch'
>         }]
>       }
>     }
>   })
> ```
> 
> **编译的时候报了如下错误信息，能帮忙看看是怎么回事吗？谢谢** Error: Chunk.parents: Use ChunkGroup.getParents() instead
> 
> * Chunk.js:827 Chunk.get
>   [applet]/[webpack]/lib/Chunk.js:827:9
> * index.js:40 doesChunkBelongToHTML
>   [applet]/[preload-webpack-plugin]/index.js:40:30
> * index.js:116
>   [applet]/[preload-webpack-plugin]/index.js:116:61
> * Array.filter
> * index.js:116
>   [applet]/[preload-webpack-plugin]/index.js:116:45
> * new Promise
> * Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
>   [applet]/[tapable]/lib/Hook.js:154:20
> * index.js:673 promisedApplyPluginsAsyncWaterfall
>   [applet]/[webpack-runner]/[html-webpack-plugin]/index.js:673:47
> * index.js:178
>   [applet]/[webpack-runner]/[html-webpack-plugin]/index.js:178:18

我也遇到这个问题，请问后面你解决了吗

**Comment by GitKou** [comment]
> @luckyadam 按照文档配置如下：
> 
> ```
> webpackChain (chain, webpack) {
>   chain.merge({
>     plugin: {
>       HtmlWebpackPlugin: {
>         plugin: require('html-webpack-plugin')
>       },
>       PreloadWebpackPlugin: {
>         plugin: require('preload-webpack-plugin'),
>         args: [{
>           rel: 'prefetch'
>         }]
>       }
>     }
>   })
> ```
> 
> **编译的时候报了如下错误信息，能帮忙看看是怎么回事吗？谢谢** Error: Chunk.parents: Use ChunkGroup.getParents() instead
> 
> * Chunk.js:827 Chunk.get
>   [applet]/[webpack]/lib/Chunk.js:827:9
> * index.js:40 doesChunkBelongToHTML
>   [applet]/[preload-webpack-plugin]/index.js:40:30
> * index.js:116
>   [applet]/[preload-webpack-plugin]/index.js:116:61
> * Array.filter
> * index.js:116
>   [applet]/[preload-webpack-plugin]/index.js:116:45
> * new Promise
> * Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
>   [applet]/[tapable]/lib/Hook.js:154:20
> * index.js:673 promisedApplyPluginsAsyncWaterfall
>   [applet]/[webpack-runner]/[html-webpack-plugin]/index.js:673:47
> * index.js:178
>   [applet]/[webpack-runner]/[html-webpack-plugin]/index.js:178:18

preload-webpack-plugin2.X和webpack版本不兼容的问题，用新的
```
npm install --save-dev preload-webpack-plugin@next
```
https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/67#issuecomment-383683899
