### ISSUE TITLE
h5 里如何定义 404 路由

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#779]
**问题描述**
因为之前使用 react-router 时都会设置一个默认页面，当路由匹配不到组件时就会展示 404 页面。但是文档上没看到类似的功能。

**期望行为**
支持 404 页面

**系统信息**

 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v10.0.0]

**Comment by luckyadam** [comment]
可以写一个 404 页面，然后主动跳转，暂时没有配置这样的功能

**Comment by Herrengit** [comment]
自己写一个404页面 判断是不是H5 如果是就跳转即可
