### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by linmiss** [NervJS/taro#78]
希望加点单元测试，保证代码质量。

**Comment by yuche** [comment]
现在我们单元测试是的确不够，只有 eslint-plugin，h5 组件库，小程序转换器三个模块带测试，总共加起来大概差不多 200 个。

其他的一些模块由于微信也没有提供自动化的测试接口，我们也得想一下如何把测试写好，而不是为了覆盖率而写测试。

**Comment by iyoucheng** [comment]
taro 核心模块不用写测试吗？

**Comment by yuche** [comment]
@iyoucheng 你说的是运行时框架吧，这个我们在大规模重构，可能要稍等一下

**Comment by yuquanwang** [comment]
请问可以像开发react一样写相关的单元测试吗，试了以下，会报诸如：页面config = {} Unexpected token，node_modules/weui/dist/style/weui.css 无法解析等错误，请问怎样才是taro项目单元测试的正确打开方式？

**Comment by luckyadam** [comment]
@yuquanwang jest 的话需要在 `jest.config.js` 里配置一下 `moduleNameMapper`，但目前只能写 H5 的测试，小程序端还没有相关的测试套件，H5 在编译过程中会产生一个 `.temp` 目录，可以对这里面的代码进行测试

```javascript
moduleNameMapper: {
    react: 'nervjs',
    'react-addons-test-utils': 'nerv-test-utils',
    'react-dom': 'nervjs',
    'weui': '<rootDir>/__mock__/styleMock.js',
    '\\.(css|less|sass|scss)$': '<rootDir>/__mock__/styleMock.js'
  }
```
