### ISSUE TITLE
Taro版本问题

### ISSUE THREAD

**Issue by JustDo** [NervJS/taro#7800]
### 这个特性解决了什么问题？
我有多个程序，每个小程序使用的Taro版本不同，每次切换小程序进行编译的时候都要install 对应项目版本的taro , 这个问题怎么解决呢

### 这个 API 长什么样？
我想要的是每个项目build的时候都能使用当前项目中的taro版本进行编译

**Comment by Chen-jj** [comment]
@JustDo 每个项目本地安装对应版本的 Taro CLI，通过 npm script 调用 taro 命令。
