### ISSUE TITLE
swiper组件支持acceration属性

### ISSUE THREAD

**Issue by broven** [NervJS/taro#7801]
### 这个特性解决了什么问题？
taro组件没有透传acceration属性到原生swiper属性上, 导致传入该属性最后生成的appx xml上没有该属性
![image](https://user-images.githubusercontent.com/12854613/95565853-5a640600-0a53-11eb-9059-dc2bbbee9e4e.png)
![image](https://user-images.githubusercontent.com/12854613/95565866-5df78d00-0a53-11eb-9cae-95797f50b629.png)

### 这个 API 长什么样？
swiper组件支持acceration属性

**Comment by luckyadam** [comment]
这是啥小程序

**Comment by broven** [comment]
@luckyadam 支付宝小程序

**Comment by broven** [comment]
@luckyadam 想问下3.0.15有大概的发布日期吗? 我们计划月底要发布, 对这个能力有依赖
![image](https://user-images.githubusercontent.com/12854613/96550765-db3cc080-12e3-11eb-9dad-ffdc3241990c.png)
