### ISSUE TITLE
iphone ios12路由跳到其他网站，返回时重定向

### ISSUE THREAD

**Issue by johanazhu** [NervJS/taro#781]
**问题描述**
ios12情况下， 用， 用location.href 跳转到 跳转到一个页面（例如：例如：www.baidu.com），再返），再返回，会重定向到首页

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
  goChat()  {
    if (Taro.getEnv() === Taro.ENV_TYPE.WEB) {
      const data = this.props.data
      const imUrl = data.platform_im_url || data.merchant_im_url
      if (imUrl) {
        window.location.href = imUrl
      } else {
        Taro.showToast({title: '暂无客服',icon: 'none'})
      }
    }
  }
```

**期望行为**
希望能解决

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.11.3]

**Comment by Littly** [comment]
跳转前后的url分别是什么？

**Comment by 6061960** [comment]
我遇到同样问题，从微信网页授权登陆回调之后，我的回调页面如下：
 - `http://e5145e0.ngrok.io/#/pages/wechat-auth/wechat-auth`
预期的回调链接为：
 - `http://e5145e0.ngrok.io/#/pages/wechat-auth/wechat-auth/?code=071zuF4Y1m8WMS0Mhx4Y1ScH4Y1zuF4&state=state`
实际的回调链接为：
 - `http://e5145e20.ngrok.io/?code=071zuF4Y1m8WMS0Mhx4Y1ScH4Y1zuF43&state=webauth#/pages/wechat-auth/wechat-auth/`

由于`#`的存在，回调链接中无法将参数正确附加在链接上，造成跳转失败，直接回到主页。

**Comment by Littly** [comment]
可以试下最新版本 应该不存在这个问题了
