### ISSUE TITLE
H5 情况下 URL 中的参数获取

### ISSUE THREAD

**Issue by ksbaozi** [NervJS/taro#7820]
### 这个特性解决了什么问题？
现在我们 的 URL 是 /p/:projectID 的 browser 样式，目前看文档似乎没法在 H5 中定义和获取自定义参数。

### 这个 API 长什么样？
可以在 URL 中添加参数，并且在 app 中 params 可以直接获取对应参数。

**Comment by smackgg** [comment]
同问

**Comment by YunShengTeng** [comment]
不能用querystring的方式吗？
