### ISSUE TITLE
h5端子路由如何实现？

### ISSUE THREAD

**Issue by smackgg** [NervJS/taro#7822]
### 这个特性解决了什么问题？
针对类似 tabbar 切换局部组件，但是 url 需要变化的情况怎么处理？
首先无法将多个url映射到同一个page中，其次现在切换页面就是直接渲染了，无法做到局部更新。

### 这个 API 长什么样？
可以实现上述需求

**Comment by wuchangming** [comment]
目前小程序的路由有点像h5的多页面应用。多个url映射到一个page，有点类似 h5 的 SPA。要实现这个效果，应该要调整目前的路由实现方式。

**Comment by ZakaryCode** [comment]
配置子路由地址，不使用 taro-router 刷新页面，子路由可以使用各类社区方案，譬如 react-router、vue-router 实现。

**Comment by ZakaryCode** [comment]
[参考文档](https://docs.taro.zone/docs/router-extend/)
