### ISSUE TITLE
 React.createElement: type is invalid

### ISSUE THREAD

**Issue by Jickey** [NervJS/taro#7829]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
新增一个页面文件夹，并配置路由

### 期望结果
编译正常，小程序显示正常

### 实际结果
编译正常，但是微信开发工具报错

### 环境信息
```
 Taro CLI 3.0.0-rc.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - D:\node\node.EXE
      Yarn: 1.22.4 - C:\Users\86151\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - D:\node\npm.CMD
```

---
### 补充信息
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

**Comment by yidafu** [comment]
我也遇到这个问题，有人能回复一下吗？

**Comment by yidafu** [comment]
修改文件的时候把`pages/xxxx/index.config.ts` 改为了`pages/xxxx/index.ts`，Taro 竟然编译通过了。

Taro 编译能检查一下页面组件的文件是否齐全吗？
