### ISSUE TITLE
taro 升级到3.0.9  报错Cannot read property 'dispatch' of null

### ISSUE THREAD

**Issue by crazyboy008** [NervJS/taro#7830]
### 相关平台
微信小程序

**小程序基础库: 2.11.0**
**使用框架: React**

### 复现步骤
 npm run dev:weapp 

### 环境信息
```
Taro CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\XZP\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
taro 升级到3.0.9  报错Cannot read property 'dispatch' of null

**Comment by Pasoul** [comment]
把@tarojs/redux换成react-redux

**Comment by techdogCoder** [comment]
taro3  不能再使用 @tarojs/redux ？ 全部换成 react-redux ？

**Comment by Chen-jj** [comment]
> taro3 不能再使用 @tarojs/redux ？ 全部换成 react-redux ？

是的，楼上正解：https://taro-docs.jd.com/taro/docs/next/redux
