### ISSUE TITLE
h5 配置 staticDirectory 没生效

### ISSUE THREAD

**Issue by Jordonwang** [NervJS/taro#7837]
### 相关平台
H5

**浏览器版本: Chrome 86**
**使用框架: Vue 2**

### 复现步骤
直接新初始化的一个项目, 编译h5配置staticDirectory: 'static'没有生效 

### 期望结果
h5编译后的静态资源在一个目录

### 实际结果
js css 目录直接输出在dist

### 环境信息
```
 Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息

 "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.0.14",
    "@tarojs/runtime": "3.0.14",
    "@tarojs/taro": "3.0.14",
    "vue-template-compiler": "^2.5.0",
    "vue": "^2.5.0"
  },
  "devDependencies": {
    "@types/webpack-env": "^1.13.6",
    "@tarojs/mini-runner": "3.0.14",
    "@babel/core": "^7.8.0",
    "@tarojs/webpack-runner": "3.0.14",
    "babel-preset-taro": "3.0.14",
    "vue-loader": "^15.9.2",
    "eslint-plugin-vue": "^6.x",
    "eslint-config-taro": "3.0.14",
    "eslint": "^6.8.0",
    "stylelint": "9.3.0"
  }

**Comment by biluochun** [comment]
> 

怎么解决的，我也发现配置了，没生效啊。
