### ISSUE TITLE
从v3.0.7更新到v3.0.14最新版本报错

### ISSUE THREAD

**Issue by git-guining** [NervJS/taro#7838]
### 相关平台
支付宝小程序

**小程序基础库: 支付宝最新版**
**使用框架: Vue 2**

### 复现步骤
从v3.0.7更新到v3.0.14最新版本，运行项目报错，一直报Cannot find module '@babel/preset-modules/lib/plugins/transform-async-arrows-in-class'，一个一个安装下去，没有头，更新之后依赖也更新了，请问是什么原因。

### 期望结果
从v3.0.7更新到v3.0.14最新版本，运行项目打包成功

### 实际结果
从v3.0.7更新到v3.0.14最新版本，运行项目报错

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by git-guining** [comment]
删除node modules重新安装可以了，不过支付宝小程序切换tab页面，onshow经常无法触发。

**Comment by Chen-jj** [comment]
@git-guining onShow 的问题重新开个 issue 附上可复现代码吧。
