### ISSUE TITLE
支付宝小程序的onShow总是不会被触发

### ISSUE THREAD

**Issue by git-guining** [NervJS/taro#7844]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/git-guining/taro-code-snippet.git](https://github.com/git-guining/taro-code-snippet.git)
**小程序基础库: 支付宝小程序看不到基础版本库**
**使用框架: Vue 2**

### 复现步骤
切换tab页面，onShow大概率不会被触发，开发者工具没有问题，真机调试就会这样。

### 期望结果
切换tab页面，onShow会触发

### 实际结果
切换tab页面，onShow大概率不会被触发

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.12.1 - D:\Program Files\nodejs\npm.CMD
```

**Comment by git-guining** [comment]
无法解决吗，还有支付宝小程序的input框，v-model双向绑定后，界面数据通过this.message = ''无法清除。

**Comment by Chen-jj** [comment]
@git-guining 问题1、2都复现不了，升级到最新版本再试试咯

```js
<template>
  <view class="index">
    <input type="text" v-model="msg">
    msg: {{msg}}
    <button @tap="handleClick">reset</button>
  </view>
</template>

<script>
import './index.less'

export default {
  data() {
    return {
      msg: ''
    }
  },
  onShow() {
    console.log('我到首页了...');
  },
  methods: {
    handleClick () {
      this.msg = ''
    }
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/11807297/103626134-bec13380-4f76-11eb-96ff-e241127c3f73.png)
