### ISSUE TITLE
Taro vue2环境下scroll-view下拉刷新功能的loading始终显示不消失

### ISSUE THREAD

**Issue by doseeing** [NervJS/taro#7847]
### 相关平台
微信小程序

**小程序基础库: 2.13.2**
**使用框架: Vue 2**

### 复现步骤
新建一个基于vue2的taro项目

页面中添加一个scroll-view元素，允许下拉刷新，并设置refreshTrigger为data下的triggered变量

运行程序，下拉刷新

刷新的loading图标始终存在

以下是示例vue文件

```
<template>
  <scroll-view
    class="demo"
    :refresherEnabled="true"
    :refresherTriggered="triggered"
    @refresherRefresh="onRefresh"
    @refresherPulling="onPulling"
    @refresherRestore="onRestore"
    @refresherAbort="onAbort"
    ><view>content</view>
  </scroll-view>
</template>

<script>
import "./index.scss";
export default {
  name: "Index",
  data() {
    return {
      triggered: false,
    };
  },

  methods: {
    onRefresh() {
      console.log("onRefresh");
      setTimeout(() => {
        this.triggered = false;
      }, 1000);
    },
    onPulling() {
      console.log("onPulling");
    },
    onRestore() {
      console.log("onRestore");
    },
    onAbort() {
      console.log("onAbort");
    },
  },
};
</script>

```

### 期望结果
改变triggered值后loading图标消失

### 实际结果
改变triggered值后loading图标不消失

### 环境信息
```
� Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by KingsleyZheng** [comment]
同样遇到了这个问题

**Comment by yoyoping** [comment]
这个问题怎么解决啊@taro-bot2

**Comment by hejianghu** [comment]
事件名称应该要全部小写，@refresherRefresh 改成 @refresherrefresh 就可以了。
-------------------
文档中已经把属性、事件的名称都改成了小驼峰，

**Comment by hejianghu** [comment]
事件名称应该要全部小写，@refresherRefresh 改成 @refresherrefresh 就可以了。
---------------------------------------------------------------
 [官方文档](https://taro-docs.jd.com/taro/docs/components/viewContainer/scroll-view)中把属性、事件的名称都写成了小驼峰格式的，但使用 Vue2 实际调用过程中，**属性**貌似使用的 Vue 惯用的横线连接（如 refresher-triggered），**事件**为啥还是微信小程序那种令人糟心的风格？（如 @refresherrefresh，一眼看过去，真的像 refresh err fresh，） 不知道 Taro 有没有把它们进行统一的计划？

**Comment by yijinc** [comment]
遇到了同样的问题， 这个问题怎么被关闭了？？

**Comment by yijinc** [comment]
楼主看下是否是其他报错导致，我这边是列表item 用了 functional component 导致 vue 报错了

**Comment by Chen-jj** [comment]
原问题是属性、事件绑定语法没有写对导致的：

[Taro Vue 属性规范](https://docs.taro.zone/docs/vue-overall#taro-%E8%A7%84%E8%8C%83)
[Taro Vue 事件规范](https://docs.taro.zone/docs/vue-overall#taro-%E8%A7%84%E8%8C%83-1)

> [官方文档](https://taro-docs.jd.com/taro/docs/components/viewContainer/scroll-view)中把属性、事件的名称都写成了小驼峰格式的，但使用 Vue2 实际调用过程中，**属性**貌似使用的 Vue 惯用的横线连接（如 refresher-triggered），**事件**为啥还是微信小程序那种令人糟心的风格？（如 @refresherrefresh，一眼看过去，真的像 refresh err fresh，） 不知道 Taro 有没有把它们进行统一的计划？

这是因为需要借助 vue template loader 的能力收集 vue 模板的事件绑定，然后生成对应的 wxml 事件绑定，规范目前看不会作更改了。

@yijinc 此 issue 先关闭了。如果确定有其它原因导致报错，可以新建一个 issue
