### ISSUE TITLE
在父组件中子组件样式无效，自组件scss文件正常引入

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#785]
在父组件中子组件样式无效，自组件scss文件正常引入/
![image](https://user-images.githubusercontent.com/43346131/46647389-46663f00-cbc2-11e8-9e3b-869917af66ca.png)
![image](https://user-images.githubusercontent.com/43346131/46647400-5a11a580-cbc2-11e8-823a-2e58d1449090.png)

**Comment by luckyadam** [comment]
Taro 版本多少

另外，看一下编译后的文件里子组件的样式是否正常

**Comment by JoMartinezZhu** [comment]
css 层级搞错了！已解决，不过 flex 布局 偶尔失效！

**Comment by JoMartinezZhu** [comment]
![image](https://user-images.githubusercontent.com/43346131/46709616-1b89f280-cc77-11e8-8f01-60f3d2b9ee81.png)

我觉得 at-row 这些 css 样式 没有加载上去，我目前是 把 
at-row 等代码 copy 过来了，暂时可以使用
![image](https://user-images.githubusercontent.com/43346131/46709644-39575780-cc77-11e8-88c7-c9a9138825ac.png)

**Comment by JoMartinezZhu** [comment]
加了，无效。
我是按这个API 操作的
![image](https://user-images.githubusercontent.com/43346131/46713537-cacfc500-cc89-11e8-81fb-82ab1d146129.png)

我把 

```
if (process.env.TARO_ENV === "weapp") {
  require("taro-ui/dist/weapp/css/index.css")
} else if (process.env.TARO_ENV === "h5") {
  require("taro-ui/dist/h5/css/index.css")
}
```
写在component js 文件中了，但是无效

**Comment by luckyadam** [comment]
重启开发者工具试试

**Comment by JoMartinezZhu** [comment]
试过！我目前
先这样处理
 把 taro-ui/dist/weapp/css/index.css" 里的 at-row 相关 css copy 在 component.scss 中使用！效果OK！
