### ISSUE TITLE
taro2.x版本如何进行次版本号升级

### ISSUE THREAD

**Issue by AnathanPham** [NervJS/taro#7852]
### 这个特性解决了什么问题？
解决了无法进行次版本升级的问题

### 这个 API 长什么样？
能够无感知的进行taro2.x次版本升级

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro-docs/docs/GETTING-STARTED/#%E4%BF%9D%E6%8C%81-cli-%E7%9A%84%E7%89%88%E6%9C%AC%E4%B8%8E%E5%90%84%E7%AB%AF%E4%BE%9D%E8%B5%96%E7%89%88%E6%9C%AC%E4%B8%80%E8%87%B4)
