### ISSUE TITLE
getCurrentInstance().router.params取不到值

### ISSUE THREAD

**Issue by igpfpyu** [NervJS/taro#7853]
### 相关平台
H5

**浏览器版本: Chrome next**
**使用框架: React**

### 复现步骤
getCurrentInstance().router.params取不到值

### 期望结果
getCurrentInstance().router.params取到上一个页面跳转到本页面带的参数

### 实际结果
拿到参数

### 环境信息
```
process.env.TARO_API_ENV: undefined

  Taro CLI 3.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14 
      @tarojs/mini-runner: 3.0.14 => 3.0.14 
      @tarojs/react: 3.0.14 => 3.0.14 
      @tarojs/runtime: 3.0.14 => 3.0.14 
      @tarojs/taro: 3.0.14 => 3.0.14 
      @tarojs/webpack-runner: 3.0.14 => 3.0.14 
      babel-preset-taro: 3.0.14 => 3.0.14 
      eslint-config-taro: 3.0.14 => 3.0.14 
      nerv-devtools: ^1.5.7 => 1.5.7 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 4.0.3

```

**Comment by igpfpyu** [comment]
router.mode="hash"是取不值的，
router.mode="browser"是可以取到值的

**Comment by xw-Zhou** [comment]
> router.mode="hash"是取不值的，
> router.mode="browser"是可以取到值的

哪里可以设置？

**Comment by igpfpyu** [comment]
> > router.mode="hash"是取不值的，
> > router.mode="browser"是可以取到值的
> 
> 哪里可以设置？

config -> index

**Comment by ZYK1236** [comment]
看看传递的参数中有没有包括'?'这个字符

**Comment by igpfpyu** [comment]
有的，就是hash模式就跟不到值

**Comment by ZYK1236** [comment]
反正我之前测的是如果参数带有'?'这个字符，那么后面的参数就传不出去

**Comment by JakeWoki** [comment]
vue 也用不了getCurrentInstance

**Comment by tangzhangzheng** [comment]
config-> index->h5 添加代码 `router: {
      mode: 'browser'
    }`，将hash路由更改为browser路由，重新编译  如果不更换hash路由模式，也可以在location下的hash属性，通过拼接拿到，https://developer.mozilla.org/zh-CN/docs/Web/API/Location/hash

**Comment by xiehui999** [comment]
+1

**Comment by xiehui999** [comment]
3.0.14 +1  ,将 请将getCurrentInstance().router.params替换Current.router.params 还是获取不到参数啊。 @Chen-jj  @tangzhangzheng

**Comment by tangzhangzheng** [comment]
> 3.0.14版本也有问题 ,将getCurrentInstance().router.params替换Current.router.params 还是获取不到参数啊。 @Chen-jj @tangzhangzheng .
> 
> 修改 router: { mode: 'browser' } 是可以正常工作的，还有不加这个配置，路由调整和之前（3.0.5）也不一样了，
> 
> 1，3.0.5 时H5打开路由是 http://192.168.31.34:10086/subpackages/doctor/pages/DoctorDetail?pId=8
> 2，升级3.0.14 时 路由变成http://192.168.31.34:10086/#/subpackages/doctor/pages/DoctorDetail?pId=8 （此时上面说的两种方式都获取不到参数）
> 3， 增加 配置 router: { mode: 'browser' }后，路由和 1一样了，也能获取到参数了。
> 
> 问一下，为什么会有上面的表现

@xiehui999 
1，根据url，路由方式为hash路由模式，
2，根据url，路由方式为browser路由模式，
3，增加 配置 router: { mode: 'browser' }，更改为browser路由模式，当然会和1一样了。
（此时上面说的两种方式都获取不到参数，可以确认下是否import Taro, {Current}  from '@tarojs/taro'确认引入，不行再可以看下location对象下的各个属性，使用截取字符串的方式获取传过来的值）

hash路由和browser路由模式可以简单看下，
5分钟了解哈希路由[https://www.bilibili.com/video/BV15i4y1M7Xn](url)
10分钟学会browser路由 [https://www.bilibili.com/video/BV15i4y1M7Xn](url)

**Comment by tourze** [comment]
这个问题在3.0.15依然存在

**Comment by Chen-jj** [comment]
@tourze 这个 [PR](https://github.com/NervJS/taro/pull/7873/files) 已经修复了这个问题，**3.0.15** 应该是无问题的。

Duplicate of #7871

**Comment by Chen-jj** [comment]
> vue 也用不了getCurrentInstance

不会用不了吧，可以另外提个 issue

**Comment by JakeWoki** [comment]
> > vue 也用不了getCurrentInstance
> 
> 不会用不了吧，可以另外提个 issue

可以了，文档不够详细，没说要引入`import {getCurrentInstance} from "@tarojs/taro"`才能用

**Comment by Whalesongs** [comment]
感谢  可以了，文档不够详细，没说要引入import {getCurrentInstance} from "@tarojs/taro"才能用
