### ISSUE TITLE
h5 路由 browser 模式部署后，页面刷新报 404

### ISSUE THREAD

**Issue by b2nil** [NervJS/taro#7857]
### 相关平台
H5

### 复现仓库
[https://github.com/b2nil/taro-ui-vue3-demo](https://github.com/b2nil/taro-ui-vue3-demo)
**浏览器版本: Chrome**
**使用框架: Vue 3**

### 复现步骤
- 访问: https://b2nil.github.io/taro-ui-vue3-demo/
- 打开浏览器开发工具 -> Network
- 刷新页面

### 期望结果
chunk 文件正常加载，页面正常显示

### 实际结果
刷新后，chunk 文件不能正常加载，页面 404

### 环境信息
```
Taro CLI 3.0.14 environment info:
Build 环境： 
 OS: Windows 10
 Node: 12.8.1
 Yarn: 1.22.5
部署环境：Github Pages
```

---
### 补充信息
从主页进入，不刷新的情况，页面能正常浏览。

**Comment by JakeWoki** [comment]
和我遇到的一样#7635

**Comment by b2nil** [comment]
@JakeWoki 是一样的问题。

页面刷新后，Request URL 是路由路径，例如： https://domain/project/pages/index/index
然后浏览器 console 报错： GET https://domain/project/pages/index/index 404

直接访问除 `https://domain/project/` 之外的`路由路径`，都没法通过`路由路径`解析到对应的 chunk 文件

**Comment by rockliuxn** [comment]
如果服务器用的nginx，可以通过修改配置来解决这个问题：


location / {
    root ...
    index ...
    try_files $uri $uri/ /index.html; ---解决页面刷新404问题
}

**Comment by b2nil** [comment]
> 如果服务器用的nginx，可以通过修改配置来解决这个问题：
> 
> location / {
> root ...
> index ...
> try_files $uri $uri/ /index.html; ---解决页面刷新404问题
> }

nginx 可以采用上面的 `try_files` 设置。
github pages 暂时没有办法，只能用 `hash` 模式。

问题先关闭了。
