### ISSUE TITLE
_typeof is not defined 安卓 5.0

### ISSUE THREAD

**Issue by kokoroX** [NervJS/taro#7860]
### 相关平台
H5

**浏览器版本: 安卓 5.0 自带浏览器**
**使用框架: React**

### 复现步骤
安装 genymotion，设置一个 安卓 5.0 版本的模拟器
使用 @tarojs/cli 默认生成的项目在 模拟器自带浏览器中报 _typeof is not defined

### 期望结果
不报错 正常运行

### 实际结果
报错

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14 
      @tarojs/mini-runner: 3.0.14 => 3.0.14 
      @tarojs/react: 3.0.14 => 3.0.14 
      @tarojs/runtime: 3.0.14 => 3.0.14 
      @tarojs/taro: 3.0.14 => 3.0.14 
      @tarojs/webpack-runner: 3.0.14 => 3.0.14 
      babel-preset-taro: 3.0.14 => 3.0.14 
      eslint-config-taro: 3.0.14 => 3.0.14 
      react: ^16.10.0 => 16.14.0 
```

---
### 补充信息
可能和 babel runtime 有关 https://github.com/babel/babel/pull/11049 尝试升级了版本也未解决

**Comment by zhaoguoweiLLHC** [comment]
我用的一个临时解决方案：babel.config.js文件
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: true,
      // 取消babel 对typeof 的转换
      exclude: ["@babel/plugin-transform-typeof-symbol"]
    }]
  ]
};

**Comment by kokoroX** [comment]
> 我用的一个临时解决方案：babel.config.js文件
> 
> ```js
> module.exports = {
>   presets: [
>     ['taro', {
>       framework: 'react',
>       ts: true,
>       // 取消babel 对typeof 的转换
>       exclude: ["@babel/plugin-transform-typeof-symbol"]
>     }]
>   ]
> };
> ```

加了之后好像原来的 _typeof 调用还在 会报 undefined is not function。请问下这个有碰到吗

**Comment by zhaoguoweiLLHC** [comment]
> > 我用的一个临时解决方案：babel.config.js文件
> > ```js
> > module.exports = {
> >   presets: [
> >     ['taro', {
> >       framework: 'react',
> >       ts: true,
> >       // 取消babel 对typeof 的转换
> >       exclude: ["@babel/plugin-transform-typeof-symbol"]
> >     }]
> >   ]
> > };
> > ```
> 
> 加了之后好像原来的 _typeof 调用还在 会报 undefined is not function。请问下这个有碰到吗

有重新启动项目吗，如果重启了还不行我就不清楚了。

**Comment by kokoroX** [comment]
> > > 我用的一个临时解决方案：babel.config.js文件
> > > ```js
> > > module.exports = {
> > >   presets: [
> > >     ['taro', {
> > >       framework: 'react',
> > >       ts: true,
> > >       // 取消babel 对typeof 的转换
> > >       exclude: ["@babel/plugin-transform-typeof-symbol"]
> > >     }]
> > >   ]
> > > };
> > > ```
> > 
> > 
> > 加了之后好像原来的 _typeof 调用还在 会报 undefined is not function。请问下这个有碰到吗
> 
> 有重新启动项目吗，如果重启了还不行我就不清楚了。

重启了也不行 谢谢你

**Comment by kokoroX** [comment]
### 初始项目兼容 安卓5.0解决办法
1. 安装依赖
```shell
yarn add -D @babel/runtime-corejs3 # babel-preset-taro 中 useBuiltIns 有值时需要
yarn add core-js regenerator-runtime # 用于代码内 polyfill 添加
```

2. babel.config.js 添加如下配置
```javascript
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: true,
      // 添加部分开始
      useBuiltIns: 'entry',
      // 取消babel 对typeof 的转换
      exclude: ["@babel/plugin-transform-typeof-symbol"]
      // 添加部分结束
    }]
  ]
}
```

3. 将 node_modules/@tarojs/components/dist/esm/polyfills/index.js 文件中 checkIfURLIsSupported 方法从 applyPolyfills 中提取到外面
```javascript
function checkIfURLIsSupported() {
  try {
    var u = new URL('b', 'http://a');
    u.pathname = 'c%20d';
    return (u.href === 'http://a/c%20d') && u.searchParams;
  } catch (e) {
    return false;
  }
}
export function applyPolyfills() {
```

4. app.ts 入口文件 添加（顶部添加 polyfill 需要在代码执行之前）
```javascript
import "core-js/stable";
import "regenerator-runtime/runtime";
```

**Comment by guoseven** [comment]
请问在V2版本中如何解决这个问题
