### ISSUE TITLE
关于Types的一些建议，是否考虑单独拆出Types包进行维护

### ISSUE THREAD

**Issue by k55k32** [NervJS/taro#7862]
### 这个特性解决了什么问题？
因为各个平台小程序功能更新比较频繁，经常有类型变动和调整，特别是一些官方组件的，这导致taro的很多types无法跟上更新速度，导致项目中很多类型校验无法通过，以及没有对应的语法提示。
是否考虑将types单独抽出来，独立进行维护，发版可以频繁些，这样能够快速跟官方功能保持同步

### 这个 API 长什么样？
希望types的问题能够快速的被修复

**Comment by rottenpen** [comment]
确实 而且其实可以写个脚本爬这个库 https://github.com/wechat-miniprogram/api-typings

**Comment by ZakaryCode** [comment]
不考虑拆包发布，有部分 API 和 Taro 自身有关联性，拆分不利于维护

> 而且其实可以写个脚本爬这个库 https://github.com/wechat-miniprogram/api-typings

这个仓库很多写法并不算规范，很难适配多端场景，但是如果希望使用可以在项目内写个类型引用即可

```ts
import Taro from '@tarojs/taro'

declare module '@tarojs/taro' {
  // 覆盖类型
  interface TaroStatic {
    // 覆盖 API
  }
}
```

> 希望types的问题能够快速的被修复

目前组件类型有社区提供同步小程序官方文档 PR，也欢迎提交类型共建的 PR
