### ISSUE TITLE
百度小程序swiper轮播出现空白切换

### ISSUE THREAD

**Issue by oyvfhp** [NervJS/taro#7865]
### 相关平台
百度小程序

**小程序基础库: 3.210.115**
**使用框架: Vue 2**

### 复现步骤
<template>
  <swiper
    class='test-h'
    indicator-color='#999'
    indicator-active-color='#333'
    vertical
    circular
    indicator-dots
    autoplay>
    <swiper-item>
      <view class='demo-text-1'>1</view>
    </swiper-item>
    <swiper-item>
      <view class='demo-text-2'>2</view>
    </swiper-item>
    <swiper-item>
      <view class='demo-text-3'>3</view>
    </swiper-item>
  </swiper>
</template>

taro init vue-test
安装成功后，直接使用上面官方提交的代码就会显示错误的效果。
本身只有 3  个切换元素，会出现 2 个空白的切换场景。

### 期望结果
3个元素就是3个切换卡即可

### 实际结果
3个元素的切换，却出现了5个切换卡场景

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.10.1 - /usr/local/bin/node
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14 
      @tarojs/mini-runner: 3.0.14 => 3.0.14 
      @tarojs/runtime: 3.0.14 => 3.0.14 
      @tarojs/taro: 3.0.14 => 3.0.14 
      @tarojs/webpack-runner: 3.0.14 => 3.0.14 
      babel-preset-taro: 3.0.14 => 3.0.14 
      eslint-config-taro: 3.0.14 => 3.0.14 
```

**Comment by oyvfhp** [comment]
![image](https://user-images.githubusercontent.com/4404279/96528323-fa702980-12b4-11eb-828c-de9b902651fd.png)
具体可以看下这切换的效果。

**Comment by oyvfhp** [comment]
@luckyadam 关注一下这个问题，非常感谢。

**Comment by oyvfhp** [comment]
@yuche 大佬也关注一下这个问题。 百度小程序swiper的问题

**Comment by Chen-jj** [comment]
#7293

**Comment by oyvfhp** [comment]
> #7293

意思是说这个问题也是这个setData导致的？
估计百度那边什么时候能够进行修复？

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/96949819-618f1780-151b-11eb-8781-fecbe6ef93b7.png)

短期内估计难

**Comment by SyMind** [comment]
@Chen-jj 这个 issue 可以关闭了
