### ISSUE TITLE
通过大写PX避免转换的方式与prettier规则冲突了，会提示warning

### ISSUE THREAD

**Issue by ljquan** [NervJS/taro#7874]
### 这个特性解决了什么问题？
希望部分 px 单位不被转换成 rpx 或者 rem。建议增加注释避免转换的方式

### 这个 API 长什么样？
```scss
padding: 48px 0 36px 48px; /*no*/
width: $size;/*no*/
// 通过 /*no*/ 注释声明不转换
```

**Comment by YunShengTeng** [comment]
这样注释`// prettier-ignore`

**Comment by RolkerMan** [comment]
这样注释才对 /* prettier-ignore */
举例：
 /* prettier-ignore */
font-size: 1PX;

参考链接：https://prettier.io/docs/en/ignore.html#css
