### ISSUE TITLE
Hooks 组件中 this.createSelectorQuery不存在

### ISSUE THREAD

**Issue by ZiQiangWang** [NervJS/taro#7877]
### 相关平台
微信小程序

**小程序基础库: 2.13.1**
**使用框架: React**

### 复现步骤
[文档](https://nervjs.github.io/taro/docs/apis/wxml/createSelectorQuery)中说组件中使用this.createSelectorQuery 创建查询，但是hooks中访问为undefined

### 期望结果
在组件中是否通过Taro.createSelectorQuery创建

### 实际结果
实际访问this.createSelectorQuery为undefined

### 环境信息
```
 Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14
      @tarojs/mini-runner: 3.0.14 => 3.0.14
      @tarojs/react: 3.0.14 => 3.0.14
      @tarojs/runtime: 3.0.14 => 3.0.14
      @tarojs/taro: 3.0.14 => 3.0.14
      @tarojs/webpack-runner: 3.0.14 => 3.0.14
      babel-preset-taro: 3.0.14 => 3.0.14
      eslint-config-taro: 3.0.14 => 3.0.14
      react: ^16.14.0 => 16.14.0
```

**Comment by anuxs** [comment]
一般来说Hook 中没有 this 概念，只有 class 才有 this 概念。

**Comment by ZiQiangWang** [comment]
> 一般来说Hook 中没有 this 概念，只有 class 才有 this 概念。

所以说这里文档有误？

**Comment by a851928337** [comment]
我也遇到这个问题了，Taro官方给的这个`this. createSelectorQuery`是照搬微信小程序的文档，但两者的this指向都不一样，所以没法用。我目前的解决方法是先用`Taro.getCurrentPages`当前页的对象，上面有一个`createSelectorQuery`方法，用这个方法去创建`query`对象，有没有大佬有更好的解决方法。

**Comment by honlyHuang** [comment]
> > 一般来说Hook 中没有 this 概念，只有 class 才有 this 概念。
> 
> 
> 
> 所以说这里文档有误？

也不算有误吧，需要补充个hook的示例
