### ISSUE TITLE
微信开发者工具热重载功能失效

### ISSUE THREAD

**Issue by zhaixiyun** [NervJS/taro#7878]
### 相关平台
微信小程序

**小程序基础库: 2.13.1**
**使用框架: React**

### 复现步骤
按照文档初始化项目，执行yarn dev:weapp成功，微信开发者工具导入项目，开启开发者工具热重载功能，修改index.jsx，编译成功，开发者工具白屏

### 期望结果
热重载功能

### 实际结果
修改之后白屏

### 环境信息
```
� Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - D:\yarn\bin\yarn.CMD
      npm: 6.14.7 - D:\nodejs\npm.CMD
```

**Comment by nnmer** [comment]
Taro v3.0.21 也是这个问题
OS: Mac

**Comment by Chen-jj** [comment]
duplicate #10722

3.3.17 开始兼容，需要额外配置，详情请看 #10722 中的评论
