### ISSUE TITLE
Trao 初始化输入多参数问题

### ISSUE THREAD

**Issue by devilruiniu** [NervJS/taro#788]
**问题描述**
taro init 初始化的时候多参数输入bug

**复现步骤**
[复现问题的步骤]
1. taro init myApp firstTaroApp false redux

**期望行为**
控制台问题会，直接跳过输入项目介绍

**报错信息**
控制台继续提示输入项目介绍

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v1.0.4]
 - Node.js 版本 [e.g. v8.11.3]

**补充信息**
[可选]
project.js中82行代码
if (typeof conf.description !== 'string') {
      prompts.push({
        type: 'input',
        name: 'description',
        message: '请输入项目介绍！'
      })
    }

实际init参数获取的description返回的值的类型为Function类型，所以不管输入怎样的值都会执行该步骤

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/46709352-e9c45c00-cc75-11e8-84cd-0cdcde91ba54.png)
