### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isSupportRecursive' of undefined

### ISSUE THREAD

**Issue by Vision010** [NervJS/taro#7887]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
npx @tarojs/cli init demo
cd demo && yarn build:weapp

### 期望结果
正常运行

### 实际结果
error

### 环境信息
```
👽 Taro v3.0.5


  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14 
      @tarojs/mini-runner: 3.0.14 => 3.0.14 
      @tarojs/react: 3.0.14 => 3.0.14 
      @tarojs/runtime: 3.0.14 => 3.0.14 
      @tarojs/taro: 3.0.14 => 3.0.14 
      @tarojs/webpack-runner: 3.0.14 => 3.0.14 
      babel-preset-taro: 3.0.14 => 3.0.14 
      eslint-config-taro: 3.0.14 => 3.0.14 
      react: 16.10.0 => 16.10.0 
```

**Comment by Jickey** [comment]
解决了吗  我这边也出现了这个问题，请问怎么解决的

**Comment by Vision010** [comment]
> 解决了吗 我这边也出现了这个问题，请问怎么解决的
@Jickey 检查一下 taro/cli 版本。npx 初始化的 cli 版本有点问题，建议全局安装

**Comment by 5563** [comment]
taro/cli全局重装了还是出现这个问题 应该弄哪儿

**Comment by Vision010** [comment]
> taro/cli全局重装了还是出现这个问题 应该弄哪儿

@5563 taro info 检查一下版本

**Comment by 5563** [comment]
东西全在这，也看不懂怎么回事






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vision010"<notifications@github.com&gt;; 
发送时间: 2020年11月2日(星期一) 下午4:53
收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 
抄送: "1556889230"<1556889230@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NervJS/taro] UnhandledPromiseRejectionWarning: TypeError: Cannot read property &#39;isSupportRecursive&#39; of undefined (#7887)





  
taro/cli全局重装了还是出现这个问题 应该弄哪儿
  
@5563 taro info 检查一下版本

**Comment by Vision010** [comment]
@5563 我也没看到你的东西呀。。。在项目根目录运行一下 taro info 。。。

**Comment by 5563** [comment]
好了好了，我改成用yarn命令更改taro/cli版本就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vision010"<notifications@github.com&gt;; 
发送时间: 2020年11月3日(星期二) 下午4:57
收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 
抄送: "1556889230"<1556889230@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NervJS/taro] UnhandledPromiseRejectionWarning: TypeError: Cannot read property &#39;isSupportRecursive&#39; of undefined (#7887)





 
@5563 我也没看到你的东西呀。。。在项目根目录运行一下 taro info 。。。

**Comment by wang89jun** [comment]
我是2.1.5 升级上来的，也报了这个错，你们从2.x升级到3.x都怎么升级的？

**Comment by sgrjosie** [comment]
版本都是对的，也一直出现这个问题！怎么解决？
