### ISSUE TITLE
copy 配置的文件在修改时不会做处理

### ISSUE THREAD

**Issue by sussertod891015** [NervJS/taro#789]
**问题描述**
copy配置的文件在修改时不会被拷贝过去，只有第一次手动编译的时候才会拷贝过去。

**复现步骤**
1. 在config目录下的index.js文件中写入copy的配置。
2. 执行 npm run dev:weapp，copy配置的文件被拷贝。
3. 修改一些文件，重新编译。
4. copy配置的文件**未被拷贝**。

![image](https://user-images.githubusercontent.com/10465307/46658070-69094f80-cbe4-11e8-99b3-ccf92ff85b2b.png)

**期望行为**
每次修改编译时，copy配置的文件也会被拷贝到dist目录下。

**报错信息**
![image](https://user-images.githubusercontent.com/10465307/46657985-2ba4c200-cbe4-11e8-85a0-9af14be125cc.png)

**系统信息**

 - 操作系统: [macOS Mojave 10.14]
 - Taro 版本 [v1.0.5]
 - Node.js 版本 [v10.9.0]

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/3a9cbe8bbe90cc5935fb4ec7640ec22e4d1f9044
