### ISSUE TITLE
taro 分包加载echarts时 打包到主包（common.js） 而非分包， 请问该如何配置

### ISSUE THREAD

**Issue by tzzqi** [NervJS/taro#7892]
### 相关平台
微信小程序

**小程序基础库: 2.11.0**
**使用框架: React**

### 复现步骤
添加subpackages配置

### 期望结果
我希望能把echarts等微信原生组件 打包到分包 而非主包 

### 实际结果
打包到主包（dist上显示合并common.js） 而非分包

### 环境信息
```
� Taro v2.1.3


  Taro CLI 2.1.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - E:\Software\nodejs\node_global\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
 mini: {
    postcss: {
     
    },
    webpackChain (chain) {
      const config = chain.optimization.get('splitChunks')
      chain.optimization
        .splitChunks({
          ...config,
          cacheGroups: {
            ...config.cacheGroups,
            subutils: {
              name: 'packageA/ec-canvas',
              minChunks: 2,
              test: module => /packageA[\\/]ec-canvas[\\/]/.test(module.resource),
              priority: 200
            }
          }
        })
    },
    addChunkPages (pages) {
      pages.set('packageA/pages/statisticInfo/index', ['packageA/ec-canvas'])
    },
  },

试过上面配置 echarts能打包进分包 但是目录不对

**Comment by wozien** [comment]
mark
