### ISSUE TITLE
H5端编译时会将不存在 React.CSSProperties 中的内联属性删除

### ISSUE THREAD

**Issue by Raylin51** [NervJS/taro#7898]
### 相关平台
H5

### 复现仓库
[https://github.com/Raylin51/Taro-bug-report](https://github.com/Raylin51/Taro-bug-report)
**浏览器版本: Chrome85**
**使用框架: React**

### 复现步骤
分别使用 dev:weapp 和 dev:h5 会出现 Hello world 字符颜色不同，原因是在 `src/page/index` 中92行的自定义css属性在h5编译时被删除导致

### 期望结果
h5端支持自定义css属性

### 实际结果
h5端会自动删除自定义css属性

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    npmPackages:
      @tarojs/components: 3.0.14 => 3.0.14 
      @tarojs/mini-runner: 3.0.14 => 3.0.14 
      @tarojs/react: 3.0.14 => 3.0.14 
      @tarojs/runtime: 3.0.14 => 3.0.14 
      @tarojs/taro: 3.0.14 => 3.0.14 
      @tarojs/webpack-runner: 3.0.14 => 3.0.14 
      babel-preset-taro: 3.0.14 => 3.0.14 
      eslint-config-taro: 3.0.14 => 3.0.14 
      react: ^16.10.0 => 16.14.0 

```

**Comment by soulcm** [comment]
貌似style要用字符串的形式

**Comment by Raylin51** [comment]
> 貌似style要用字符串的形式，我这边用 `` style={`--height: ${height}`} `` 没有问题

试了一下字符串是可行的，但是在使用 ts 时使用字符串是难以接受的开发体验吧。。

**Comment by Ende93** [comment]
并不是不能用，而是需要带上单位，比如 ```style={{height: `${height}px`}}```

**Comment by SolidZORO** [comment]
> 

同遇到这个问题，h5 下如果不加单位如 `px` 就不生效，加了就可以。望解决，weapp 下正常。

**Comment by ZakaryCode** [comment]
该问题升级版本可以修复

**Comment by ZakaryCode** [comment]
> 并不是不能用，而是需要带上单位，比如 `` style={{height: `${height}px`}} ``

这不是同一个问题

**Comment by ZakaryCode** [comment]
> > 
> 
> 同遇到这个问题，h5 下如果不加单位如 `px` 就不生效，加了就可以。望解决，weapp 下正常。

单位可以使用 Taro.pxTransform 来统一
