### ISSUE TITLE
Taro团队的大佬们，考虑对华为WeLink小程序的支持吗？

### ISSUE THREAD

**Issue by DLCnow** [NervJS/taro#7899]
### 这个特性解决了什么问题？
是一个华为的办公产品，类似钉钉，现在很多B端用户和政府喜欢用这个，体量也挺大的，希望支持

### 这个 API 长什么样？
```bash
yarn start:welinkapp
```

**Comment by honlyHuang** [comment]
近年来业界推出的小程序平台越来越多，但 Taro 核心维护的平台只有 6 个（微信、支付宝、百度、头条、QQ、京东小程序），因此常常有同学提出能不能支持某某平台的 Feature Request。为此我们萌生了打造一个开放式框架的想法。目标是可以通过插件的形式扩展 Taro 的端平台支持能力... 具体可以查看：https://nervjs.github.io/taro/docs/next/platform-plugin

**Comment by DLCnow** [comment]
好的，谢谢大佬。我仔细研究学习下~

**Comment by honlyHuang** [comment]
> 好的，谢谢大佬。我仔细研究学习下~

期待 @DLCnow 大佬和大家分享 WeLink 插件
