### ISSUE TITLE
map 渲染的过程中,将没有数据的也渲染处理了

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#790]
![image](https://user-images.githubusercontent.com/43346131/46659614-d9fe3680-cbe7-11e8-8b9f-25afad09e27c.png)
![image](https://user-images.githubusercontent.com/43346131/46659685-fb5f2280-cbe7-11e8-8395-7a9b98c8cfd3.png)

**Comment by yuche** [comment]
map 里面不要用 if

**Comment by JoMartinezZhu** [comment]
> map 里面不要用 if

为什么，有什么隐藏的问题嘛？我在react.js 项目中这样写 是OK的，但是在Taro 项目中就 有问题？

**Comment by yuche** [comment]
编译的时候会有问题，在项目前期强烈推荐打开你的 eslint 插件来写 taro
https://github.com/NervJS/taro/tree/master/packages/eslint-plugin-taro

**Comment by JoMartinezZhu** [comment]
![image](https://user-images.githubusercontent.com/43346131/46713464-5f85f300-cc89-11e8-88fe-d1ee0ca38dd4.png)
这样配置可以吗？

**Comment by yuche** [comment]
默认用 taro-cli 生成的 eslintrc 就能用，应该只要 extends 是 taro 就可以
```
  "extends": ["taro"],
```
