### ISSUE TITLE
触发regionChangeAtBegin时分页动态添加markers

### ISSUE THREAD

**Issue by jyx12138** [NervJS/taro#7905]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: Vue 2**

### 复现步骤
<map
      v-if="showMap"
      class="map-box"
      name="map"
      :show-compass="showCompass"
      show-location
      :markers="markers"
      :longitude="longitude"
      :latitude="latitude"
      scale="15"
      @callouttap="callouttap"
      :style="{height: mapHeight   'px'}"
      :setting="setting"
      @markertap="markertap"
      @begin="regionChangeAtBegin"
      @end="regionChangeAtBegin"
      @tap="mapTap"
      :polygons="polygons"
    >
    </map>

 initItemList({
        page: 1,
        limit: 10,
        longitude: this.longitude,
        latitude: this.latitude,
        scale: this.scale
      }, res => {
        console.log(res, '項目列表')
        if (res.code == 200) {
          let list = res.data.list

          list.forEach((e) => {
              let markersObj = {
                iconPath: 'xxx',
                width: '20',
                height: '20',
              }
              markersObj['id'] = e.id
              markersObj['latitude'] = e.latitude
              markersObj['longitude'] = e.longitude
              this.markers.push(markersObj)
          })
        }
      })

### 期望结果
每次触发onRegionChange后从后台获取标记点渲染到map

### 实际结果
只有首次加载可以，无法动态渲染标记点

### 环境信息
```
Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\kmxxg\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

```

**Comment by jyx12138** [comment]
@Chen-jj 大佬，帮忙看下，谢谢~~

**Comment by Chen-jj** [comment]
@jyx12138 先升级到最新版后再试试，现在可以直接绑定 `onRegionChange` 了。

```js
<map
  @regionchange="change"
/>
```

你的代码太散了，如果还有问题，提供一份完整可复现的 demo 吧。

**Comment by jyx12138** [comment]
在onRegionChange触发后添加markers标记点无效 @Chen-jj 

`<template>
  <map
      name="map"
      :show-compass="showCompass"
      show-location
      :markers="markers"
      :longitude="longitude"
      :latitude="latitude"
      :scale="scale"
      :style="{height: mapHeight + 'px'}"
      :setting="setting"
      @regionchange="regionchange"
    >
   </map>
</template>
<script>
export default {
   data(){
       return{
          showCompass:true,
          markers: [
               { 
                   iconPath: '',
                   width: '30',
                   height: '30',
                   id: 1,
                   latitude: '39.908353',
                   longitude: '116.398585'
                }
           ],
           latitude: '',
           longitude: '',
           scale: 15,
           mapHeight: 600,
           setting: {
              skew: 0,
              rotate: 0,
              showLocation: true,
              showScale: true,
              subKey: '',
              layerStyle: 1,
              enableZoom: true,
              enableScroll: true,
              enableRotate: false,
              showCompass: false,
              enable3D: false,
              enableOverlooking: false,
              enableSatellite: false,
              enableTraffic: false,
         },
       }
   },
  onLoad(){
    let _this = this
    _this.$taro.getSystemInfo({
      success(res){
        if (res.windowHeight) {
          _this.mapHeight = res.windowHeight
        }
      }
    })
    _this.$taro.getLocation({
      type: 'gcj02',
      success(res) {
        if (res.latitude) {
          _this.latitude = res.latitude
          _this.longitude = res.longitude
        }
      }
    })
  },
  methods(){
     regionchange(e){
      let _this = this
      console.log(e, _this.markers)
      let markersObj = {
        iconPath: '',
        width: '30',
        height: '30',
        id: 1,
        latitude: '39.908353',
        longitude: '116.398585'
      }
      _this .markers.push(markersObj)
    },
  }
}


</script>
<style></style>`

**Comment by jyx12138** [comment]
[https://github.com/NervJS/taro/issues/8013](url)  @Chen-jj  demo在这里，辛苦啦~~

**Comment by jyx12138** [comment]
@Chen-jj #8013 简单的demo在这里，辛苦啦~

**Comment by tu6ge** [comment]
既然新开提案了，就把这个关了吧
