### ISSUE TITLE
tabbar 页面引入自定义tab组件，多次引入，样式不生效

### ISSUE THREAD

**Issue by zhanglijie5997** [NervJS/taro#7915]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/zhanglijie5997/taro-tem](https://github.com/zhanglijie5997/taro-tem)
**小程序基础库: 2.13.2**
**使用框架: React**

### 复现步骤
点击底部tab导航

### 期望结果
tab 切换变化

### 实际结果
自定义tababr 组件样式丢失

### 环境信息
```
Taro v3.0.5


  Taro CLI 3.0.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.5 => 3.0.5 
      @tarojs/mini-runner: 3.0.5 => 3.0.5 
      @tarojs/react: 3.0.5 => 3.0.5 
      @tarojs/runtime: 3.0.5 => 3.0.5 
      @tarojs/taro: 3.0.5 => 3.0.5 
      @tarojs/webpack-runner: 3.0.5 => 3.0.5 
      babel-preset-taro: 3.0.5 => 3.0.5 
      eslint-config-taro: 3.0.5 => 3.0.5 
      react: ^16.10.0 => 16.14.0 
    npmGlobalPackages:
      typescript: 3.8.3
```

**Comment by YoRolling** [comment]
发现是没有生成app.wxss，  如果在 `app.tsx` 中 `import '@/app.scss'` ,则正常生成 `app.wxss`, 并且其中 `@import "./common.wxss"; `。  


1. 修改`app.tsx`, 增加代码 `import '@/app.scss'`
2. `dist` 目录生成 `app.wxss`，样式正常

**Comment by Chen-jj** [comment]
Demo 没有复现。

我猜想楼主的目的是 custom-tab-bar 组件引用 '@components/base/tabs'，其它页面也引用 '@components/base/tabs'。

1. css-extract-plugin 会为 custom-tab-bar chunk 创建 wxss，为其它页面创建 wxss，它们都包含 '@components/base/tabs'。2. 但下一阶段，根据默认的 splitchunks 配置，上述两个chunk 的'@components/base/tabs' 的样式会被抽取到 common.wxss，它由 app.wxss 引用。

因此两个解决办法：

1. 配置 custom-tab-bar 的 `addGlobalClass: true`，允许全局样式影响自定义组件
2. 修改 splitchunks 配置，不处理  '@components/base/tabs' 样式模块
