### ISSUE TITLE
模板全部升级到react17和typescript4

### ISSUE THREAD

**Issue by DreamPWJ** [NervJS/taro#7917]
### 这个特性解决了什么问题？
有更好的开发体验

### 这个 API 长什么样？
react17和typescript4

**Comment by Chen-jj** [comment]
欢迎 PR～

**Comment by xpol** [comment]
react17 需要将 `@tarojs/react` 依赖的 `react-reconciler@0.23.0` 先升级，不然 npm i 的时候会有兼容性的warning。
至于是不是能直接升级 `react-reconciler` 需要大佬们先看一下。

**Comment by Chen-jj** [comment]
3.1 支持 react17 和 ts4.1
