### ISSUE TITLE
Error: Couldn't find preset "es2015" #530

### ISSUE THREAD

**Issue by qinglong-zeng** [NervJS/taro#7919]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
 Taro v2.2.15

生成  工具配置  /Users/cengqinglong/nuode_project/ndyt-mini-app/dist/project.config.json

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
编译  发现入口  src/app.jsx
编译  发现页面  src/pages/selectList/index.jsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/tabs/index.tsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/tabs-pane/index.tsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/list/index.tsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/list/item/index.tsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/button/index.tsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/loading/index.tsx
编译  发现页面  src/pages/firstStep/index.jsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/image-picker/index.tsx
编译  发现页面  src/pages/secondStep/index.jsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/divider/index.tsx
编译  发现页面  src/pages/thirdStep/index.jsx
编译  发现页面  src/pages/login/index.jsx
编译  发现组件  node_modules/taro-ui/dist/weapp/components/input/index.tsx
编译  发现组件  src/components/wCountDownBtn/index.js
⠙ 正在编译...Error: Couldn't find preset "es2015" relative to directory "/Users/cengqinglong"
    at /Users/cengqinglong/nuode_project/ndyt-mini-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/cengqinglong/nuode_project/ndyt-mini-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/cengqinglong/nuode_project/ndyt-mini-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/cengqinglong/nuode_project/ndyt-mini-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/cengqinglong/nuode_project/ndyt-mini-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)

### 期望结果
期待编译通过

### 实际结果
Error: Couldn't find preset "es2015" relative to directory

### 环境信息
```
Taro v2.2.15


  Taro CLI 2.2.15 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.9.4 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @tarojs/components: 2.2.15 => 2.2.15
      @tarojs/components-qa: 2.2.15 => 2.2.15
      @tarojs/mini-runner: 2.2.15 => 2.2.15
      @tarojs/mobx: 2.2.15 => 2.2.15
      @tarojs/mobx-h5: 2.2.15 => 2.2.15
      @tarojs/plugin-less: ^2.2.15 => 2.2.15
      @tarojs/plugin-sass: ^2.2.15 => 2.2.15
      @tarojs/router: 2.2.15 => 2.2.15
      @tarojs/taro: 2.2.15 => 2.2.15
      @tarojs/taro-alipay: 2.2.15 => 2.2.15
      @tarojs/taro-h5: 2.2.15 => 2.2.15
      @tarojs/taro-qq: 2.2.15 => 2.2.15
      @tarojs/taro-quickapp: 2.2.15 => 2.2.15
      @tarojs/taro-swan: 2.2.15 => 2.2.15
      @tarojs/taro-tt: 2.2.15 => 2.2.15
      @tarojs/taro-weapp: 2.2.15 => 2.2.15
      @tarojs/webpack-runner: 2.2.15 => 2.2.15
      eslint-config-taro: 2.2.15 => 2.2.15
      eslint-plugin-taro: 2.2.15 => 2.2.15
      nerv-devtools: ^1.5.7 => 1.5.7
      nervjs: ^1.5.7 => 1.5.7
      stylelint-config-taro-rn: 2.2.15 => 2.2.15
      stylelint-taro-rn: 2.2.15 => 2.2.15
      taro-ui: ^2.3.4 => 2.3.4
```

**Comment by luckyadam** [comment]
你有配置这个 preset 么

**Comment by qinglong-zeng** [comment]
应该是没有配置preset， 现在已经好了
