### ISSUE TITLE
如何覆盖 taro-ui 的 default.scss 里面的 $hd 变量 ?

### ISSUE THREAD

**Issue by jamieYou** [NervJS/taro#792]
### 重现步骤
我项目的设计稿是 375 的，所以配置了
```js
{
designWidth: 375,
  deviceRatio: {
    '375': 0.5,
  },
}
```

### 依赖的版本号
 - 操作系统: [e.g. macOS 10.13.6]
 - Taro 版本 [e.g. v.1.0.7]
 - taro-ui [1.2.3]
 - Node.js 版本 [e.g. v10.0.0]

### 预期结果
组件的样式大小跟文档一致

### 实际结果
组件展示的大小是文档上的两倍。我看了代码，大部分 px 都做了乘以 $hd 的处理，导致 px 都比较大。不过奇怪是，用 h5 编译，大小反而是正常。我之前用过 antd-mobile，知道这个是高清方案。
想知道有什么解决方法。
PS：个人推荐可以像 antd-mobile 那样使用 less 写 taro-ui，这样就可以支持用外部变量覆盖内部 less 的变量，从而实现自定义主题。

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-ui
在 taro-ui 项目下提个 issue 吧

**Comment by jamieYou** [comment]
> https://github.com/NervJS/taro-ui
> 在 taro-ui 项目下提个 issue 吧

已经提了，不过暂没回复，我想会不会是在 taro-ci 里配置，所以发到这里。
