### ISSUE TITLE
百度小程序 flex 布局失效

### ISSUE THREAD

**Issue by Discreater** [NervJS/taro#7920]
### 相关平台
百度小程序

### 复现仓库
[https://github.com/Discreater/taro-flex-test](https://github.com/Discreater/taro-flex-test)
**小程序基础库: 3.210.115**
**使用框架: React**

### 复现步骤
1. `taro init` 创建项目
2. `index` 页面改为如下代码，完整代码见上面的复现仓库
    ```js
    <View className='index'>
        <Text>Hello world!</Text>
        <View style={{display: 'flex'}}>
          <View style={{backgroundColor: "green", flex: 1}}>🤷‍♀️</View>
          <View style={{backgroundColor: "purple", flex: 1}}>🤷‍♂️</View>
          <View style={{backgroundColor: "yellow", flex: 1}}>👀</View>
        </View>
      </View>
    ```
3. 分别编译到百度小程序和微信小程序

### 期望结果
1. 编译到微信小程序中的效果正常
![image](https://user-images.githubusercontent.com/41231596/97161005-28bf9e80-17b8-11eb-9664-1fbef1d05b24.png)

2. 百度小程序**原生**开发正常
  - 代码
    ```html
    <view style="display:flex;">
        <view style="flex:1;background-color:green;">🤷‍♀️</view>
        <view style="flex:1;background-color:purple;">🤷‍♂️</view>
        <view style="flex:1;background-color:yellow;">👀</view>
    </view>
    ```
  - 效果
![image](https://user-images.githubusercontent.com/41231596/97161251-82c06400-17b8-11eb-85e5-b0a2916f1233.png)

### 实际结果
**taro编译**到百度小程序中的样式出现问题
![image](https://user-images.githubusercontent.com/41231596/97161434-ca46f000-17b8-11eb-8a13-8027fc4abaaf.png)

### 环境信息
```
� Taro v3.0.15


  Taro CLI 3.0.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.11.0 - D:\ProgramGreen\nvm-noinstall\v14.11.0\node.EXE
      Yarn: 1.22.10 - D:\ProgramGreen\nvm-noinstall\v14.11.0\yarn.CMD
      npm: 6.14.8 - D:\ProgramGreen\nvm-noinstall\v14.11.0\npm.CMD
```

**Comment by Chen-jj** [comment]
Duplicate of #6015

**Comment by axinjs** [comment]
3.1.1  最近升级了 百度也是不支持， 然后.... 项目上百处flex吧...
