### ISSUE TITLE
🙋‍♂️Taro 正在参与 OSC 年度中国开源项目评选（您的鼓励是我们坚持不懈的源动力！）

### ISSUE THREAD

**Issue by honlyHuang** [NervJS/taro#7926]
快来 pick Taro，助力开源项目 C 位“出道”，众人拾柴火焰高！

直达为 Taro 投票，[点击这里](https://www.oschina.net/project/top_cn_2020?utm_source=projectdetail#taro)

去 OSC 中国开源项目评选活动，为其他开源项目助力，[点击这里](https://www.oschina.net/project/top_cn_2020?utm_source=projectdetail)。

**Comment by ycy2077** [comment]
Taro UI还维护吗?
