### ISSUE TITLE
引入组件无法渲染出视图

### ISSUE THREAD

**Issue by VFiee** [NervJS/taro#7929]
### 相关平台
微信小程序

**小程序基础库: 2.13.2**
**使用框架: React**

### 复现步骤
地址:https://github.com/VFiee/mini-ui  
1.clone项目   
2.切换到dev分支  
3.执行yarn example  
4.微信小程序开发工具打开example/dist/weapp  

### 期望结果
正常渲染组件

### 实际结果
无法正常渲染组件

### 环境信息
```
Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.14 => 3.0.14 
      @tarojs/components: 3.0.14 => 3.0.14 
      @tarojs/mini-runner: 3.0.14 => 3.0.14 
      @tarojs/react: 3.0.14 => 3.0.14 
      @tarojs/runtime: 3.0.14 => 3.0.14 
      @tarojs/taro: 3.0.14 => 3.0.14 
      @tarojs/webpack-runner: 3.0.14 => 3.0.14 
      babel-preset-taro: 3.0.14 => 3.0.14 
      eslint-config-taro: 3.0.14 => 3.0.14 
      react: ^16.10.0 => 16.14.0
```

**Comment by VFiee** [comment]
更新: 2020-11-04
之前控制台没有开启warn level的log,并没有发现[WXML Runtime warning]
截图如下:
![image](https://user-images.githubusercontent.com/42051272/98083064-bab06100-1eb4-11eb-82cb-fd6ab01d0610.png)

**Comment by Chen-jj** [comment]
@VFiee 是不是漏了 `import { Button } from "@tarojs/components";`，demo 里哪个页面有问题?

**Comment by VFiee** [comment]
> @VFiee 是不是漏了 `import { Button } from "@tarojs/components";`，demo 里哪个页面有问题?

前三个页面都有问题

**Comment by VFiee** [comment]
> @VFiee 是不是漏了 `import { Button } from "@tarojs/components";`，demo 里哪个页面有问题?

Button是在另外一个组件里引用的

**Comment by Chen-jj** [comment]
@VFiee 直接 `yarn add @vyron/mini-ui` 安装 **@vyron/mini-ui**，没有发现问题：

![image](https://user-images.githubusercontent.com/11807297/98243051-5bcc1400-1fa8-11eb-973c-e698d2b208d8.png)

![image](https://user-images.githubusercontent.com/11807297/98243066-61295e80-1fa8-11eb-80ca-fdcdedbd2220.png)

![image](https://user-images.githubusercontent.com/11807297/98243085-671f3f80-1fa8-11eb-8c84-98b530aa7608.png)

目测你是使用了 `npm link` 之类，`taro-components` 这个包不能 link 过来使用（3.1 可以）。

因为我们会找在 **taro** 这个 chunk 中分析引用到的组件，link 后 `taro-components` 就去到 **common** 这个 chunk 了。

https://github.com/NervJS/taro/blob/3dc07ac6e0bc6e7ff285185a426c09c2740b7b16/packages/taro-mini-runner/src/plugins/TaroLoadChunksPlugin.ts#L60-L73

debug 一下上述 webpack 插件的代码，看看有没有成功分析出使用到的组件，问题应该出在这里。

**Comment by VFiee** [comment]
> @VFiee 直接 `yarn add @vyron/mini-ui` 安装 **@vyron/mini-ui**，没有发现问题：
> 
> ![image](https://user-images.githubusercontent.com/11807297/98243051-5bcc1400-1fa8-11eb-973c-e698d2b208d8.png)
> 
> ![image](https://user-images.githubusercontent.com/11807297/98243066-61295e80-1fa8-11eb-80ca-fdcdedbd2220.png)
> 
> ![image](https://user-images.githubusercontent.com/11807297/98243085-671f3f80-1fa8-11eb-8c84-98b530aa7608.png)
> 
> 目测你是使用了 `npm link` 之类，`taro-components` 这个包不能 link 过来使用（3.1 可以）。
> 
> 因为我们会在 **taro** 这个 chunk 中分析引用到的组件，link 后 `taro-components` 就去到 **common** 这个 chunk 了，所以没有命中分析逻辑。
> 
> https://github.com/NervJS/taro/blob/3dc07ac6e0bc6e7ff285185a426c09c2740b7b16/packages/taro-mini-runner/src/plugins/TaroLoadChunksPlugin.ts#L60-L73
> 
> debug 一下上述 webpack 插件的代码，看看有没有成功分析出使用到的组件，问题应该出在这里。

我本地并没有安装那个npm依赖,已没有npm link,查看config.js会发现那只是一个别名,导入的是packages/index.ts文件,在TaroLoadChunksPlugin.ts打debugger并不执行,方便的话可以加微信,vyronJ

**Comment by VFiee** [comment]
@Chen-jj 
我本地并没有安装那个npm依赖,已没有npm link,查看config.js会发现那只是一个别名,导入的是packages/index.ts文件,在TaroLoadChunksPlugin.ts打debugger并不执行,方便的话可以加微信,vyronJ
