### ISSUE TITLE
使用 Map 组件自定义浮层，效果不符合预期

### ISSUE THREAD

**Issue by githubmann** [NervJS/taro#7934]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/githubmann/taro-map-issue](https://github.com/githubmann/taro-map-issue)
**小程序基础库: 2.13.2**
**使用框架: React**

### 复现步骤
下载直接运行

### 期望结果
https://developers.weixin.qq.com/miniprogram/dev/component/map.html

https://developers.weixin.qq.com/s/cZWIojm47pjN

----------

期望地图里面的浮层能正常点击出现

### 实际结果
浮层全部都出现，并非点击标志而出现

### 环境信息
```
  Taro CLI 3.0.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.8 => 3.0.8
      @tarojs/mini-runner: 3.0.8 => 3.0.8
      @tarojs/react: 3.0.8 => 3.0.8
      @tarojs/runtime: 3.0.8 => 3.0.8
      @tarojs/taro: 3.0.8 => 3.0.8
      @tarojs/webpack-runner: 3.0.8 => 3.0.8
      babel-preset-taro: 3.0.8 => 3.0.8
      eslint-config-taro: 3.0.8 => 3.0.8
      react: ^16.10.0 => 16.14.0
    npmGlobalPackages:
      typescript: 3.9.3
```

**Comment by Chen-jj** [comment]
3.2.6 修复，文档地址：https://docs.taro.zone/docs/components/maps/map#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B0%94%E6%B3%A1
