### ISSUE TITLE
onShareAppMessage 无效

### ISSUE THREAD

**Issue by wreido** [NervJS/taro#7936]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/wreido/seft/tree/master/yxgj-miniprogram-template-3.0.5](https://github.com/wreido/seft/tree/master/yxgj-miniprogram-template-3.0.5)
**小程序基础库: 2.13.2**
**使用框架: React**

### 复现步骤
onShareAppMessage() {
    return {
      title: '享受会员福利，解锁品质生活',
      path: `/pages/index/index`,
      imageUrl: 'https://yrymall-static.oss-cn-shenzhen.aliyuncs.com/yxgj-miniprogram/share/shareImage.jpg'
    }
  }

### 期望结果
右上角出现转发按钮，标题对应，路径对应，图片对应

### 实际结果
右上角没有转发按钮，调用Taro.showShareMenu()转发按钮可以出来，但是标题、路径、图片都不对。

### 环境信息
```
Taro CLI 3.0.15 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.15 => 3.0.15 
      @tarojs/mini-runner: 3.0.15 => 3.0.15 
      @tarojs/react: 3.0.15 => 3.0.15 
      @tarojs/runtime: 3.0.15 => 3.0.15 
      @tarojs/taro: 3.0.15 => 3.0.15 
      @tarojs/webpack-runner: 3.0.15 => 3.0.15 
      babel-preset-taro: 3.0.15 => 3.0.15 
      eslint-config-taro: 3.0.15 => 3.0.15 
      react: ^16.10.0 => 16.13.1 
      taro-ui: ^2.3.4 => 2.3.4 
    npmGlobalPackages:
      typescript: 3.6.3
```

**Comment by Chen-jj** [comment]
Duplicate of #7232 

3.1 改进，但最稳还是加配置：

```js
// page.config.js
{
  // ...
  enableShareAppMessage: true
}
```
