### ISSUE TITLE
关于每个页面都需要创建 config 文件的问题

### ISSUE THREAD

**Issue by Grewer** [NervJS/taro#7937]
### 这个特性解决了什么问题？
文件夹繁琐, 不用创建多余文件,有需要的时候才会创建

### 这个 API 长什么样？
希望在 app.config.ts 里面可以有一个子页面配置的默认值,  
如果我们需要子页面 config , 就像现在一样创建 config 文件,再 merge 得到最终 config,  
如果不需要,则使用默认 config

或者像之前的 API 一样 ,写在 class 的 static 属性里面也行

**Comment by Chen-jj** [comment]
duplicate #10348

**Comment by Chen-jj** [comment]
Taro v3.4 开始支持，新增两个编译时宏函数，文档：

- [defineAppConfig](https://docs.taro.zone/docs/app-config#defineappconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
- [definePageConfig](https://docs.taro.zone/docs/page-config#definepageconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
