### ISSUE TITLE
3.1.0-beta.0 原生支付宝小程序组件无法调用 props 传入的函数

### ISSUE THREAD

**Issue by Miaonster** [NervJS/taro#7938]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/Miaonster/test-taro-alipay-native-component-props-func](https://github.com/Miaonster/test-taro-alipay-native-component-props-func)
**小程序基础库: 1.24.3**
**使用框架: React**

### 复现步骤
点击“ New Component ”无法成功调用 /pages/index/index 中传入的 onIncrease 函数

### 期望结果
期望能原生支付宝小程序组件能调用传入的函数

### 实际结果
无法调用，并且会报错，如果传入 event 会没有任何反应

![image](https://user-images.githubusercontent.com/1927546/97668251-860b6680-1abc-11eb-8389-ec62ab8fcb41.png)

![image](https://user-images.githubusercontent.com/1927546/97668225-7c81fe80-1abc-11eb-8a42-acbea4b28c28.png)

### 环境信息
```
👽 Taro v3.1.0-beta.0


  Taro CLI 3.1.0-beta.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.3.0 - ~/.config/nvm/14.3.0/bin/node
      Yarn: 1.22.5 - ~/.config/nvm/14.3.0/bin/yarn
      npm: 6.14.5 - ~/.config/nvm/14.3.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.0-beta.0 => 3.1.0-beta.0 
      @tarojs/components: 3.1.0-beta.0 => 3.1.0-beta.0 
      @tarojs/mini-runner: 3.1.0-beta.0 => 3.1.0-beta.0 
      @tarojs/react: 3.1.0-beta.0 => 3.1.0-beta.0 
      @tarojs/runtime: 3.1.0-beta.0 => 3.1.0-beta.0 
      @tarojs/taro: 3.1.0-beta.0 => 3.1.0-beta.0 
      @tarojs/webpack-runner: 3.1.0-beta.0 => 3.1.0-beta.0 
      babel-preset-taro: 3.1.0-beta.0 => 3.1.0-beta.0 
      eslint-config-taro: 3.1.0-beta.0 => 3.1.0-beta.0 
      react: ^16.10.0 => 16.14.0 

```

**Comment by Chen-jj** [comment]
@Miaonster 感谢反馈！

支付宝小程序中，自定义组件要调用父组件传入的方法，是直接调用 `this.props.xxx()`。有别于其它小程序的 `this.triggerEvent` 方式。

在 Taro3 的事件机制特点下，只能兼容 `this.triggerEvent` 这种方式，因此在支付宝中需要 **hack** 一下：

```js
Component({
  methods: {
    handleTap() {
      this.props.onIncrease({
        type: 'increase',
        target: {
          id: this.props.id
        }
      })
    }
  }
})
```

**Comment by miduoN** [comment]
> 

在taro3.2.16 中，这样也无法出触发， 不报错也不执行onIncrease方法

**Comment by miduoN** [comment]
> @Miaonster 感谢反馈！
> 
> 支付宝小程序中，自定义组件要调用父组件传入的方法，是直接调用 `this.props.xxx()`。有别于其它小程序的 `this.triggerEvent` 方式。
> 
> 在 Taro3 的事件机制特点下，只能兼容 `this.triggerEvent` 这种方式，因此在支付宝中需要 **hack** 一下：
> 
> ```js
> // 原生组件的 js
> Component({
>   methods: {
>     handleTap() {
>       // 必须提供 type、target.id
>       this.props.onIncrease({
>         type: 'increase',
>         target: {
>           id: this.props.id
>         }
>       })
>     }
>   }
> })
> ```

在taro3.2.16 中，这样也无法出触发， 不报错也不执行onIncrease方法
