### ISSUE TITLE
原生微信小程序项目无法向 taro vue 转型

### ISSUE THREAD

**Issue by hanzhongxing** [NervJS/taro#7939]
### 这个特性解决了什么问题？
历史微信原生的项目无法通过 convert 转taro-vue项目，开发人员只能cover vue，
对react不熟悉，而且后续全部使用vue模板开发

### 这个 API 长什么样？
taro convert 里面提供 模板选择 可以支持 vue

**Comment by hanzhongxing** [comment]
历史项目 为了方便开发需要走一下 下面的流程
1、原生->vue
2、develop
3、vue->原生
4、发布
目前是缺失第一步
https://github.com/rottenpen/blog/issues/22
这里面有过探索 但是没有比较好的解决方案

**Comment by Chen-jj** [comment]
有计划，但目前暂时不够人力支持

**Comment by Dante-dan** [comment]
看到之前的 beta 版本有过类似的功能。

 `taro/cli@3.1.0`  目前 `convert` 没有开放参数。
 我想尝试下会有哪些问题，然后试着去解决它。可以怎么打开呢？ @Chen-jj

**Comment by Chen-jj** [comment]
@Dante-dan 

> 我想尝试下会有哪些问题，然后试着去解决它。可以怎么打开呢？ @Chen-jj

可以进入 CLI 工具的安装目录，然后把这里的 `framework` 改为 Vue。

![image](https://user-images.githubusercontent.com/11807297/109265665-de236100-7841-11eb-893e-1652a8dd5230.png)

> vue 项目已经开发很久了，想要转到 Taro。但是缺少指导性的参考文档，各种途径来的都比较碎片化。
> 我可以自己做一个基于 AST 的工具来完成这个功能，但是需要一些参考指南的支持，也可以将其添加到 taro 的指令中。

转 Vue 的功能其实之前有部分实现过，但还没经过详细测试。我们人力也有限，暂时覆盖不了这块。

和社区合作来推进此功能是最理想的，但的确关于这块的文档、实现细节披露太少。

我忙完手上的任务，争取在下周末左右把反向转换的开发指南文档输出，然后在 [Discussion](https://github.com/NervJS/taro/discussions) 开启一个项目组，邀请社区有意向的同学进行参与。

老哥有空可以帮忙先进行测试，把遇到的问题在此 Issue 下列出～

**Comment by Dante-dan** [comment]
discussion 可以先开起来~

**Comment by Dante-dan** [comment]
@Chen-jj 大佬，文档啥进度了~

**Comment by kevinroy-lo** [comment]
@Chen-jj 大佬，文档啥进度了~
