### ISSUE TITLE
app.js 配置tabbar H5端使用 Taro.redirectTo页面跳转依然显示底部tabbar 而小程序不会

### ISSUE THREAD

**Issue by shbin** [NervJS/taro#795]
**问题描述**
app.js 配置tabbar H5端页面跳转依然显示底部tabbar 而小程序不会

**复现步骤**
[复现问题的步骤]
1. 在app.js中配置的tabbar
2. 绑定事件 点击后用 Taro.redirectTo进行跳转
```
Taro.redirectTo({
      url: "/pages/home-tab/list-product/index"
 });
```
3. 在list-product， H5端还会出现tabbar， 而小程序则不会

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
    tabBar: {
      color: "#333333",
      selectedColor: "#059aff",
      list: [
        {
          pagePath: "pages/home-tab/index",
          text: "首页",
          iconPath: "./assets/images/home-o.png",
          selectedIconPath: "./assets/images/home.png"
        },
        {
          pagePath: "pages/orders-tab/index",
          text: "订单",
          iconPath: "./assets/images/orders-o.png",
          selectedIconPath: "./assets/images/orders.png"
        },
        {
          pagePath: "pages/account-tab/index",
          text: "我的",
          iconPath: "./assets/images/account-o.png",
          selectedIconPath: "./assets/images/account.png"
        }
      ]
    }
```

**期望行为**
Taro.redirectTo页面跳转后 H5端和小程序都不应该出现tabbar 

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - Taro 版本 [e.g. v1.0.7]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by shbin** [comment]
> ~



> 使用 navigateTo 呢~

这个可以 但是redirectTo两端显示不一致

**Comment by luckyadam** [comment]
收到~ 我们看看这个问题

**Comment by Qiu800820** [comment]
发现这个问题应该和tabbar无关， h5中通过redirectTo 并没有remove\hide该页面， 只是单纯的新增了一个page的div，而navigateTo 会将上个page hide。
上个图
![1541471126 1](https://user-images.githubusercontent.com/7494629/48039251-e8238080-e1ae-11e8-8235-806979c32bb8.png)
我的堆栈情况是先到login界面  使用redirectTo跳到home界面  然后navigateTo 进入子业务界面。
login界面并没有hide， 只是通过新增和当前一样taro-page的方式阻止router跳转回来。 
再加上display:none应该就完美了

**Comment by Littly** [comment]
最新版(v1.2.2)应该不存在这个问题了
