### ISSUE TITLE
canvas 绘制无效

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#796]
小程序版：
![image](https://user-images.githubusercontent.com/43346131/46708897-89ccb600-cc73-11e8-9723-7263f603b01a.png)
Taro 版：
![image](https://user-images.githubusercontent.com/43346131/46708927-c1d3f900-cc73-11e8-8673-6995a42cc580.png)
用原生的是OK的，但是 改成 Taro 就无效了！

**Comment by luckyadam** [comment]
createCanvasContext 有两个参数，如果你在组件里使用，第二个参数必传
https://developers.weixin.qq.com/miniprogram/dev/api/canvas/wx.createCanvasContext.html

**Comment by JoMartinezZhu** [comment]
给了我继续 玩 Taro 的信心！
