### ISSUE TITLE
taro 3.0 中使用两层swiper嵌套内层无dom问题

### ISSUE THREAD

**Issue by wuyingyi** [NervJS/taro#7969]
### 相关平台
微信小程序

**小程序基础库: 2.14**
**使用框架: React**

### 复现步骤
taro 3.0 中使用两层swiper嵌套，内层被嵌套的swiper没有显示，dom中也没有找到相关代码，麻烦大佬们帮助解决下，如需要详细截图联系咚咚wuyingyi。

### 期望结果
可以正常获取dom

### 实际结果
无dom信息

### 环境信息
```
  Taro CLI 3.0.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.1 - D:\Program Files\node.EXE
      npm: 6.4.1 - D:\Program Files\npm.CMD
```

**Comment by Chen-jj** [comment]
Duplicate of #7692

**Comment by Chen-jj** [comment]
3.0.16 修复

**Comment by pangnate** [comment]
实际验证未修复，产生新的错误
