### ISSUE TITLE
taro  构建是否支持node api

### ISSUE THREAD

**Issue by gsbybb** [NervJS/taro#7978]
### 这个特性解决了什么问题？
想自己写node脚本启动taro的编译

### 这个 API 长什么样？
类似于webpack的脚本

**Comment by Chen-jj** [comment]
试试:

```js
const build = require('@tarojs/cli/commands/build')
build(options)
```

使用方法详见 `@tarojs/cli/src/cli.ts`

**Comment by gsbybb** [comment]
@Chen-jj

**Comment by gsbybb** [comment]
@Chen-jj  目前是通过这种方式自己实现的，如果可以的话，出个标准的文档吧 谢谢啦

**Comment by Chen-jj** [comment]
人力暂时不够去完善这块文档，欢迎提交你的使用经验作为文档哈～

**Comment by xwchris** [comment]
同问，能够提供node api吗
