### ISSUE TITLE
如何使用自定义tabBar

### ISSUE THREAD

**Issue by bundlejs** [NervJS/taro#7980]
### 相关平台
微信小程序

**小程序基础库: 2.14.0**
**使用框架: Vue 3**

### 复现步骤
在 src 目录下添加了custom-tab-bar 文件夹,内部放了index.config.js&index.vue
custom-tab-bar
    index.config.js
    index.vue

经过编译在微信小程序根目录出现了custom-tab-bar文件夹,内部只有index.js文件,并且在根目录产生了custom-tab-bar.json&custom-tab-bar.xml

custom-tab-bar
    index.js
custom-tab-bar.json
custom-tab-bar.xml

所以小程序页未能如期展示tabBar

### 期望结果
正确使用自定义tabBar

### 实际结果
未能展示

### 环境信息
```
👽 Taro v3.0.15


  Taro CLI 3.0.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 15.0.1 - D:\soft\node-v15.0.1-win-x64\node.EXE
      npm: 7.0.3 - D:\soft\node-v15.0.1-win-x64\npm.CMD



微信开发者工具 1.03.2010240
调试基础库2.14.0
```

**Comment by luckyadam** [comment]
custom-tabar 目前还是用原生写法来写，用 vue 的话会有点问题

**Comment by bundlejs** [comment]
> custom-tabar 目前还是用原生写法来写，用 vue 的话会有点问题

自定义的tabbar需要在页面内获取到tabbar然后设置当前选中的item，taro怎么在页面内操作tabbar的数据

**Comment by YoRolling** [comment]
#7915   可以看下这个issue 提供的问题复现仓库， 他是自定义tabbar 遇到了其他问题。 你可以参考一下看下是否可以解决你的问题。

**Comment by bundlejs** [comment]
> #7915 可以看下这个issue 提供的问题复现仓库， 他是自定义tabbar 遇到了其他问题。 你可以参考一下看下是否可以解决你的问题。

这不是一个问题,微信小程序官网上面带有tabBar的页面有这个方法,Taro vue3的项目拿不到这个this,
```
this.getTabBar().setData({
    selected: 0
})
```
想问一下如何能拿到tabBar

**Comment by bundlejs** [comment]
终于解决了

1. 小程序自定义tabBar在src根目录创建custom-tab-bar文件夹内部放入微信小程序官方的例子的4个文件, 删除switchTab中操作selected的代码

2. config/index 中copy->patterns中添加
```
{ from: 'src/custom-tab-bar/', to: `dist/${process.env.TARO_ENV}/custom-tab-bar/` }
```
以将组建复制到编译根目录

3. 遍历TabBar的list,页面内控制tab选中状态
```
for (let i = 0; i < list.length; i++) {
    if (list[i].pagePath === Taro.Current.router.path) {
        Taro.getCurrentPages()[0].getTabBar().setData({
            selected: i
        })
        // 其他逻辑...
    }
}
```

**Comment by wfunctionGithub** [comment]
taro提供了一个getCurrentInstance的方法， 不用取循环控制tab选中状态
const currentPage = getCurrentInstance().page! as any;
    if (typeof currentPage.getTabBar === 'function' && currentPage.getTabBar()) {
      currentPage.getTabBar().setData({
        selected: 0,
      });
}

**Comment by EdivenH** [comment]
> 终于解决了
> 
> 1. 小程序自定义tabBar在src根目录创建custom-tab-bar文件夹内部放入微信小程序官方的例子的4个文件, 删除switchTab中操作selected的代码
> 2. config/index 中copy->patterns中添加
> 
> ```
> { from: 'src/custom-tab-bar/', to: `dist/${process.env.TARO_ENV}/custom-tab-bar/` }
> ```
> 
> 以将组建复制到编译根目录
> 
> 3. 遍历TabBar的list,页面内控制tab选中状态
> 
> ```
> for (let i = 0; i < list.length; i++) {
>     if (list[i].pagePath === Taro.Current.router.path) {
>         Taro.getCurrentPages()[0].getTabBar().setData({
>             selected: i
>         })
>         // 其他逻辑...
>     }
> }
> ```
> 
> 不知道还有其他的解决方案没

大佬，你的Taro变量是怎么拿到的

**Comment by Chen-jj** [comment]
已补充自定义 TabBar 文档和完整例子：https://docs.taro.zone/docs/custom-tabbar

**Comment by konka-king** [comment]
> 已补充自定义 TabBar 文档和完整例子：https://docs.taro.zone/docs/custom-tabbar

大佬，这个 自定义 Tabbar 是只能微信小程序用吗？支付宝小程序可以用吗？
