### ISSUE TITLE
taro vue下百度小程序中调试工具中的APPDATA 出现了些奇怪的数据

### ISSUE THREAD

**Issue by LiZheGuang** [NervJS/taro#7982]
### 相关平台
百度小程序

**小程序基础库: 5.17.0**
**使用框架: Vue 3**

### 复现步骤
启动项目的时候开发中的APPDATA会是ROOT开头的

### 期望结果
{
"msg":'我是demo'

}

### 实际结果
{
  "root": {
    "cn": {
      "0": {
        "nn": "view",
        "uid": "_n_9",
        "cn": [
          {
            "nn": "text",
            "uid": "_n_10",
            "cn": [
              {
                "v": "Hello world",
                "nn": "#text"
              }
            ]
          },
          {
            "nn": "view",
            "uid": "_n_12",
            "cn": [
              {
                "v": "点击支付",
                "nn": "#text"
              }
            ],
            "cl": "clickDemo"
          }
        ],
        "cl": "demo"
      }
    },
    "uid": "pages/demo/index",
    "cl": ""
  }
}

### 环境信息
```
👽 Taro v3.0.15


  Taro CLI 3.0.15 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.15 => 3.0.15
      @tarojs/mini-runner: 3.0.15 => 3.0.15
      @tarojs/runtime: 3.0.15 => 3.0.15
      @tarojs/taro: 3.0.15 => 3.0.15
      @tarojs/webpack-runner: 3.0.15 => 3.0.15
      babel-preset-taro: 3.0.15 => 3.0.15
      eslint-config-taro: 3.0.15 => 3.0.15
    npmGlobalPackages:
      typescript: 3.9.5
```

**Comment by Chen-jj** [comment]
@LiZheGuang 这是正确的。setData 的是 Taro DOM 树的数据结构，Appdata 面板看到的就是它们。

**Comment by LiZheGuang** [comment]
> @LiZheGuang 这是正确的。setData 的是 Taro DOM 树的数据结构，Appdata 面板看到的就是它们。

请问，我该怎么在开发者工具中能调试data数据或者看到，而不是taro的dom树结构，也就是说该怎么去做类似于vue的develop的调试工具

**Comment by Chen-jj** [comment]
目前没有办法直接在开发者工具中看到。只能断点调试或打 log。
