### ISSUE TITLE
关于组件的生命周期

### ISSUE THREAD

**Issue by u3u** [NervJS/taro#799]
### 关于 `componentCatchError` 和 `componentDidCatchError`

在模版中使用的是 `componentCatchError`

https://github.com/NervJS/taro/blob/ece601d9787d79e42a36ad9bdcfba83de29f8b33/packages/taro-cli/templates/redux/appjs#L46

但是在实际实现中以及 d.ts 定义中使用的是 `componentDidCatchError`，并且 eslint 提示方法名太长

https://github.com/NervJS/taro/blob/defc534c603a0d9e51da4d044fbef7ff2b04a1bb/packages/taro-weapp/src/create-app.js#L30-L34

> [eslint] 方法名的长度大于 22 可能在小程序中无法使用 (taro/function-naming)

https://github.com/NervJS/taro/blob/1a58eb0aebfce2af38ed294a2e41adb778fd04af/packages/taro/types/index.d.ts#L26-L38

### 在项目说明文档中缺少一些生命周期说明

- `componentDidCatchError`
- `componentDidNotFound`

https://nervjs.github.io/taro/docs/tutorial.html

虽然看名字并且有 d.ts 定义可以得知，但还是希望在文档中补充一下

顺便可以将小程序的专属的方法成员也添加到 d.ts 定义中

- `onPullDownRefresh`
- `onReachBottom`
- `onShareAppMessage`
- `onPageScroll`
- `onTabItemTap`

这样可以通过编辑器的自动完成功能输入，而不用去记方法名

**Comment by luckyadam** [comment]
非常感谢建议~
