### ISSUE TITLE
Taro 3.0.16 生命周期函数 预加载componentWillPreload 不执行

### ISSUE THREAD

**Issue by jutoukeji** [NervJS/taro#7998]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
componentWillPreload 中打印参数没有进到方法里

### 期望结果
能够正常执行预加载钩子函数

### 实际结果
预加载函数componentWillPreload未执行

### 环境信息
```
Taro CLI 3.0.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
Taro 3 不再提供 componentWillPreload、$preload API，改为:

调用：

```js
Taro.preload()
```

获取

```js
console.log(getCurrentInstance().preloadData)
```

[参考文档](https://nervjs.github.io/taro/docs/next/optimized#%E8%B7%B3%E8%BD%AC%E9%A2%84%E5%8A%A0%E8%BD%BD)
