### ISSUE TITLE
[Feature Request] 支持快应用

### ISSUE THREAD

**Issue by Nigiss** [NervJS/taro#80]
有计划支持快应用么，或者提供贡献指导？

**Comment by isting** [comment]
https://taro.aotu.io/  去官网看看嘛！ 不看一遍 就来问，，暂时只支持H5和 小程序  下个应该是RN，快应用应该不久也会有

**Comment by Nigiss** [comment]
看过来才来问的，想了解下进度的，如果正在开发，可以帮忙😄

**Comment by isting** [comment]
厉害了，大神！！😄

**Comment by zaaack** [comment]
看官网 RN 的优先级居然在 快应用 之前，感觉对于 taro 而言支持 快应用 的意义更加大一些呀

**Comment by luckyadam** [comment]
@zaaack 快应用也在同步开发中了

**Comment by zaaack** [comment]
@luckyadam 赞👍

**Comment by yuhuibin123** [comment]
你好，咨询一下快应用什么时候会上线呢？

**Comment by luckyadam** [comment]
@yuhuibin123 要延到 12 月了

**Comment by jasper-fu** [comment]
@luckyadam hi, 有状态更新么？或者是否有一个可以使用的alpha版本？

**Comment by luckyadam** [comment]
还在开发中

**Comment by SamenYan** [comment]
期待，waiting for you 😆

**Comment by zaaack** [comment]
快应用有动静了吗？ 😂

**Comment by haochenli** [comment]
同求支持快应用

**Comment by tourze** [comment]
这个不是支持了吗？

**Comment by yuche** [comment]
已经支持了
