### ISSUE TITLE
h5中swiper-item宽度有些问题

### ISSUE THREAD

**Issue by fool1990** [NervJS/taro#800]
**问题描述**
h5中swiper-item宽度不是100%,小程序正常
![gif](https://github.com/fool1990/myApp/raw/master/taro.gif)

**复现步骤**

```javascript
{banners.map((banner, idx) => {
     return (
              <SwiperItem key={idx}>
                <Image
                  src={banner.m_img}
                  style="width:100%;height:100%"
                />
              </SwiperItem>
            )
          })}

```

**期望行为**
表现一致

**系统信息**

 - 操作系统: [macos 10.14]
 - Taro 版本 [ v.1.0.7]
 - Node.js 版本 [e.g. v8.10.0]
 - 报错平台 [h5, weapp]

**补充信息**
应该是wrapper的计算

**Comment by jinjinjin0731** [comment]
升级到 1.1.0-beta.9 可以解决

**Comment by q773592519** [comment]
目前遇到同样的问题 最新版taro 暂无解决
