### ISSUE TITLE
2.2.15 tabbar页面多次加载

### ISSUE THREAD

**Issue by mengtianren** [NervJS/taro#8007]
### 相关平台
H5

### 复现仓库
[https://github.com/mengtianren/taro-tabbar](https://github.com/mengtianren/taro-tabbar)
**浏览器版本: Google Chrome 86.0.4240.111**
**使用框架: React**

### 复现步骤
1.登录页点击去首页
2.tabbar 点击用户对应tab，跳转到用户页面
3.用户页面点击退出，redirectTo（{url:'/pages/login/index'}）
4.重复步骤1，进入首页后下滑 ，会出现多个首页ui

### 期望结果
从普通页面进入tabbar页面，再从tabbar页面跳转到普通页面，再次从普通页面进入tabbar页面时不出现多个tabbar

### 实际结果
tabbar页面多次加载

### 环境信息
```
Taro CLI 2.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
路由相关函数的回调也没有生效

**Comment by SunPm** [comment]
@Chen-jj 这个bug请问怎么解决呢
