### ISSUE TITLE
Taro 是否可以使用refs

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#801]
Taro 是否可以使用refs,我是使用了，但是 ESlint 报错！
在小程序端，是不是必须 要 Taro 的 ESlint 检验
![image](https://user-images.githubusercontent.com/43346131/46716482-c5c54280-cc96-11e8-8ce4-1c5ebccc7860.png)
![image](https://user-images.githubusercontent.com/43346131/46716544-0755ed80-cc97-11e8-9b8f-9c50078e29d0.png)

**Comment by yuche** [comment]
是不推荐你使用 string 的 ref，你可以关掉它，也可以使用函数 ref。

**Comment by JoMartinezZhu** [comment]
部分 不满足 Taro 的 ESlint 检验，并不影响 程序运行吧，例如 上面的eslint 报错！
