### ISSUE TITLE
【Bug 公告】关于 2.x 版本使用 taro-ui 编译打包后报错的问题修复

### ISSUE THREAD

**Issue by luckyadam** [NervJS/taro#8010]
各位 Taro 同仁，非常抱歉，我们在 2.2 以上版本中引入了一个严重的问题，即在 2.2 以上版本中使用 taro-ui 编译打包后报错，而导致页面无法出现。

问题的具体原因是，production 模式下 taro-ui 组件代码被当成副作用移除了， 可以加上 webpack 的 sideEffect 配置来解决

![image](https://user-images.githubusercontent.com/1782542/98544520-1a50a700-22cf-11eb-88da-7ccfa58dfce5.png)

```js
webpackChain (chain) {
  chain.optimization.sideEffects(false)
}
```

由于这个问题给大家带来巨大的困扰，我们深表歉意，后续我们将更加细致确保版本功能的稳定，同时更加积极地跟进社区反馈问题的修复。

相关 issue：
https://github.com/NervJS/taro/issues/7913#issuecomment-723991922

**Comment by sun0207** [comment]
棒棒哒

**Comment by chaoyang-Rex** [comment]
https://github.com/NervJS/taro/issues/8976
该 issue 是我提出的，下面版本下 build 也会出现组件找不到的情况，按照上面配置修改，还是会出现同样的问题，希望大佬解决下 @luckyadam 
taro 1.3.0-beta.4
taro-ui": "^1.5.4"
