### ISSUE TITLE
IOS下AR插件不能正常使用

### ISSUE THREAD

**Issue by zhaixuepan** [NervJS/taro#8012]
### 相关平台
微信小程序

**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
使用taro3集成此AR插件，IOS下报错canvasToTempFilePath :  file no image。
![image](https://user-images.githubusercontent.com/15258081/98566609-edf65400-22e9-11eb-8a82-81e344081be6.png)
![image](https://user-images.githubusercontent.com/15258081/98566621-f3539e80-22e9-11eb-9707-e7b8e8aa8528.png)

插件地址：https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx3bbab3920eabccb2&token=&lang=zh_CN

### 期望结果
正常调起摄像头
![image](https://user-images.githubusercontent.com/15258081/98566635-fa7aac80-22e9-11eb-9779-704dc3cfbc11.png)

### 实际结果
报错

### 环境信息
```
� Taro v3.0.16


  Taro CLI 3.0.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\zhaixuepan\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
你是咋用的

**Comment by zhaixuepan** [comment]
按照插件地址：https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx3bbab3920eabccb2&token=&lang=zh_CN 里的示例代码直接用的，以原生方式在taro工程用的。
**index.js**
`const { downloadSceneAsset, clearSceneCache } = requirePlugin("kivicube");

Page({
  onLoad() {
  
    //如果需要提前下载好场景素材，则可自行调用downloadSceneAsset方法。
    // downloadSceneAsset("9vR08tpLesfKVWs2XbbnNKSsX3JqpaAp", (progress) => {
    //   console.log("progress", progress);
    // }).then(() => {
    //   // 使kivicube-scene组件attached进入页面节点树。比如wx:if为真
    // });

  },
  ready() {
    wx.showToast({ title: "场景加载中...", icon: "none" });
  },
  downloadStart() {},
  downloadProgress() {},
  downloadEnd() {},
  loadStart() {},
  loadEnd() {},
  sceneStart() {
    wx.showToast({ title: "可开始体验场景", icon: "none" });
  },
  openUrl({ detail: url }) {
    wx.navigateTo({ url: `path/to/webview?url=${encodeURIComponent(url)}` });
  },
  photo({ detail: photoPath }) {
    wx.saveImageToPhotosAlbum({
      filePath: photoPath,
      success() {
        console.log("保存照片成功");
      },
      fail(e) {
        console.error("保存照片失败", e);
      }
    });
  },
  error(e) {
    const { detail } = e;
    if (detail && detail.isCameraAuthDenied) {
      // 如果是权限问题，则向用户申请权限。
      const page = this;
      wx.showModal({
        title: "提示",
        content: "请给予“摄像头”权限",
        success() {
          wx.openSetting({
            success({ authSetting: { "scope.camera": isGrantedCamera } }) {
              if (isGrantedCamera) {
                clearSceneCache();
                wx.redirectTo({ url: '/' + page.__route__ });
              } else {
                wx.showToast({ title: "获取“摄像头”权限失败！", icon: "none" });
              }
            }
          });
        }
      });
    }
    console.error(e);
  }
});`

**index.json**
`{
  "usingComponents": {
    "kivicube-scene": "plugin://kivicube/kivicube-scene"
  }
}`

index.wxml
`<kivicube-scene
    class="kivicube"
    scene-id="9vR08tpLesfKVWs2XbbnNKSsX3JqpaAp"
    bindready="ready"
    binderror="error"
    binddownloadAssetStart="downloadStart"
    binddownloadAssetProgress="downloadProgress"
    binddownloadAssetEnd="downloadEnd"
    bindloadSceneStart="loadStart"
    bindloadSceneEnd="loadEnd"
    bindsceneStart="sceneStart"
/>`


**index.wxml**
`.kivicube {
  display: block;
  width: 100%;
  height: 100%;
}`

使用的地方：
`import Taro from '@tarojs/taro'
import React, { Component } from 'react'
import { connect } from 'react-redux'
// import { View } from '@tarojs/components'
import kivicube from "../../components/kivicube";
import './index.scss'

import {
    dispatchGetInviteInfo
} from "../../store/actions/invite";

@connect(({account, invite}) => {
    return {
        invite: invite.invite,
        loadingStatus: invite.statue,
        userInfo: account.userInfo
    }
}, {
    dispatchGetInviteInfo
})

class AR extends Component {
    componentWillMount() {
        this.getInviteInfo();
    };

    // 获取邀请函信息
    getInviteInfo = () => {
        this.props.dispatchGetInviteInfo();
    };


    render() {
        return (
            // <kivicube-scene className='kivicube' scene-id={this.state.sceneId}
            //                 onError={this.error}  onPhoto={this.photo}/>
            <kivicube></kivicube>
        );
    }
}

export default AR

`

**Comment by zhaixuepan** [comment]
![Uploading image.png…]()

**Comment by zhaixuepan** [comment]
![image](https://user-images.githubusercontent.com/15258081/98817170-b364f680-2464-11eb-8a8f-adfb45e0b794.png)

**Comment by zhaixuepan** [comment]
![image](https://user-images.githubusercontent.com/15258081/98819040-5585de00-2467-11eb-813e-2bda66941736.png)
![image](https://user-images.githubusercontent.com/15258081/98819050-5a4a9200-2467-11eb-827d-4710be02cf8f.png)

**Comment by zhaixuepan** [comment]
![image](https://user-images.githubusercontent.com/15258081/98819247-967df280-2467-11eb-8ba5-de94f4ede5ed.png)
这个是Android下面的，可以正常加载
