### ISSUE TITLE
selectComponent获取子组件报错  找不到selectComponent方法

### ISSUE THREAD

**Issue by 382559544** [NervJS/taro#8014]
### 相关平台
微信小程序

**小程序基础库: 2.3.2**
**使用框架: Vue 2**

### 复现步骤
.ts文件加载组件
export default {
  usingComponents: {
    'editor': '/component/editor/editor'
  }
}

.vue文件methods方法中调用，this.selectComponent('#editor') 
异常信息：this.selectComponent  of undefined

### 期望结果
需要获取子组件对象

### 实际结果
获取方法异常

### 环境信息
```
� Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
Duplicate of #8019
