### ISSUE TITLE
RichText富文本内容部分显示

### ISSUE THREAD

**Issue by weijunfu** [NervJS/taro#8015]
### 这个特性解决了什么问题？
由于富文本内容可能过多，全部显示影响整体布局，希望提供显示部分内容和全部显示的切换功能，且部分显示可以自由控制显示的内容

### 这个 API 长什么样？
通过属性控制显示的内容。例如，如果部分显示，则不显示图片或视频 等媒体文件，仅显示纯文本。

**Comment by zhaoguoweiLLHC** [comment]
这个感觉属于特殊需求，可以通过代码解决。比如 通过正则过滤掉 img,video,audio等。
```js
let html = "<div><p>123</p><img src='http://xxx.com'></div>"
// 过滤img
html.replace(/<img.*?>/g,"")
```

**Comment by weijunfu** [comment]
> 这个感觉属于特殊需求，可以通过代码解决。比如 通过正则过滤掉 img,video,audio等。
> 
> ```js
> let html = "<div><p>123</p><img src='http://xxx.com'></div>"
> // 过滤img
> html.replace(/<img.*?>/g,"")
> ```

确实是一种很好的解决办法 ，转为纯文本可以用
`html.replace(/<.*?>/g,"")`
替换掉所有的HTML标签
