### ISSUE TITLE
selectComponent('#id')获取不到子组件对象

### ISSUE THREAD

**Issue by 382559544** [NervJS/taro#8019]
### 相关平台
微信小程序

**小程序基础库: 2.7.0**
**使用框架: Vue 2**

### 复现步骤
工程里我引入了component小程序的富文本编辑器插件，是其他网友封装好的，样式都已经出来了，现在需要获取插件里的上传图片方法，但是我用 this.selectComponent('#id')获取不到子组件对象，我该如何处理这一步 来获取子组件对象

### 期望结果
this.selectComponent('#id')获取子组件对象

### 实际结果
this.selectComponent('#id')获取不到子组件对象

### 环境信息
```
 Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
试试:

```
import { getCurrentInstance } from '@tarojs/taro'

const { page } = getCurrentInstance()
page.selectComponent('#id')
```

**Comment by 382559544** [comment]
太棒了，困扰了一天

**Comment by 382559544** [comment]
终于解决了

**Comment by Tonysmark** [comment]
> 
> 
> 试试:
> 
> ```
> import { getCurrentInstance } from '@tarojs/taro'
> 
> const { page } = getCurrentInstance()
> page.selectComponent('#id')
> ```

3.3.5 这样不行

**Comment by lxfljw** [comment]
使用这段代码的不是页面级组件 无法获取实例

**Comment by guoenyue** [comment]
> 

@tarojs/taro 3.3.19 not ok

**Comment by scorpioop** [comment]
> 试试:
> 
> ```
> import { getCurrentInstance } from '@tarojs/taro'
> 
> const { page } = getCurrentInstance()
> page.selectComponent('#id')
> ```

使用了 无法实现
