### ISSUE TITLE
请问scrollView 的scrollIntoView这个属性功能有实现吗？

### ISSUE THREAD

**Issue by gromy92** [NervJS/taro#802]
代码如下：
![image](https://user-images.githubusercontent.com/18656849/46718754-c82b9a80-cc9e-11e8-8730-c96e175e2a50.png)

---------

**问题描述**
在使用请问scrollView 的scrollIntoView这个属性通过setState 赋值，效果没有实现，已经确认赋值成功，在taro的component中未找到对于该方法的描述

劳烦解答

**系统信息**
 - 操作系统:mac
 - Taro 版本  1.0.3
 - Node.js 版本 8.11
 - 报错平台 chrome  69.0.3497.100

**Comment by dogbutcat** [comment]
scrollIntoView是可以用的，如果不行，请检查：
1. 是否赋值了相同的值
1. 内部元素是否添加了id
