### ISSUE TITLE
runtime下的window不对劲

### ISSUE THREAD

**Issue by cjz9032** [NervJS/taro#8021]
### 这个特性解决了什么问题？
引入一些三方库如mobx-state-tree会报Symbol不存在，因为他会从window下拿取需要的属性

### 这个 API 长什么样？
taro-runtime的window应Proxy当前环境的global变量下的属性, 如Map,Symbol

**Comment by atzcl** [comment]
遇到同样的问题

**Comment by atzcl** [comment]
使用了 `mobx` 等库的，可以临时通过修改源码的方式修复
```
// node_modules/@tarojs/runtime/dist/runtime.esm.js

const window$1 = isBrowser ? win : {
    navigator,
    document: document$1
};

// 在这里加上修复代码
if (!isBrowser) {
    Reflect.ownKeys(global).forEach(key => {
        window$1[key] = global[key];
    })
}
```

**Comment by cjz9032** [comment]
> 使用了 `mobx` 等库的，可以临时通过修改源码的方式修复
> 
> ```
> // node_modules/@tarojs/runtime/dist/runtime.esm.js
> 
> const window$1 = isBrowser ? win : {
>     navigator,
>     document: document$1
> };
> 
> // 在这里加上修复代码
> if (!isBrowser) {
>     Reflect.ownKeys(global).forEach(key => {
>         window$1[key] = global[key];
>     })
> }
> ```

他是用provider插件注入的, 我就修改了一下,不用改源码稍微方便点
`   chain.plugin('providerPlugin').tap((args) => {
        args[0].window = ['@/utils/adjust-taro-runtime', 'newWindow']; // adjust 里面保留了自身的window, 并注入你需要的属性
        args[0].Taro = ['@tarojs/taro', 'default'];
        return args;
      });
`

**Comment by atzcl** [comment]
@cjz9032 如果用这种方式的话，会导致某些用到了 `window.navigator` 、`window.document` 的地方异常

**Comment by cjz9032** [comment]
> @cjz9032 如果用这种方式的话，会导致某些用到了 `window.navigator` 、`window.document` 的地方异常

不会吧 只要吧 runtime也引入
``export default {
...runtimeWindow,
...newWindow
}``

**Comment by atzcl** [comment]
> > @cjz9032 如果用这种方式的话，会导致某些用到了 `window.navigator` 、`window.document` 的地方异常
> 
> 不会吧 只要吧 runtime也引入
> `export default { ...runtimeWindow, ...newWindow }`

明白你的意思了，处理的核心是一样的，只是方式不同

**Comment by Chen-jj** [comment]
尴尬，微信环境好像有改动，现在 `global`("webpack/buildin/global") 获取不到这些属性了
