### ISSUE TITLE
怎样才能让h5打包后只有一个js文件

### ISSUE THREAD

**Issue by deng-yc** [NervJS/taro#8024]
### 这个特性解决了什么问题？
希望h5打包后没有动态加载的文件

### 这个 API 长什么样？
可配置h5的页面是否动态加载

**Comment by ZakaryCode** [comment]
参考 webpack [文档](https://webpack.js.org/plugins/limit-chunk-count-plugin/)

移除懒加载拆分参考[文档](https://nervjs.github.io/taro/docs/next/babel-config#dynamic-import-node)
