### ISSUE TITLE
RN端自定义导航栏 navigationStyle: 'custom' 会被状态栏压住

### ISSUE THREAD

**Issue by hellotiger** [NervJS/taro#803]
![title2](https://user-images.githubusercontent.com/5555873/46719605-f0b49400-cca0-11e8-8777-da67e8002204.png)

**Comment by hellotiger** [comment]
> 应该是仅安卓会出现这种情况吧。

我这是安卓模拟器 6.0.1 IOS暂没试。

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/46724086-de8c2300-ccab-11e8-9766-ebfbda0b36e9.png)
貌似安卓默认就是这样的。

**Comment by hellotiger** [comment]
> ![image](https://user-images.githubusercontent.com/9441951/46724086-de8c2300-ccab-11e8-9766-ebfbda0b36e9.png)
> 貌似安卓默认就是这样的。

还是有点不一样，我发的那个状态栏高度为0，你的和这个状态栏是有高度的。

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/46725766-6f183280-ccaf-11e8-87f4-9c4015190d3a.png)
iOS 也有这个问题，那这样的话，是不是可以统一设置一个 padding 或 margin？

**Comment by Pines-Cheng** [comment]
问题解决了吗？@hellotiger

**Comment by Pines-Cheng** [comment]
issue 先关闭了，有疑问可以 reopen 或 直接回复。
