### ISSUE TITLE
Taro.chooseImage H5  缺少 originalFileObj 字段

### ISSUE THREAD

**Issue by deng-yc** [NervJS/taro#8032]
### 相关平台
H5

**浏览器版本: Chrome 86**
**使用框架: React**

### 复现步骤
图片上传 选择完图片，tempFiles 中缺少 originalFileObj

### 期望结果
包含originalFileObj

### 实际结果
没有originalFileObj

### 环境信息
```
  Taro CLI 3.0.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0
      Yarn: 1.22.10
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by RainWangjie** [comment]
遇到同样的问题。
我是通过file.url转blob类型解决的。
`const blob = await fetch(file.url).then((r) => r.blob());`

**Comment by alvc666** [comment]
同样遇到问题
以前已经修复过的 然而新版本没有合进去
https://github.com/NervJS/taro/commit/fe346efc9b06926371ab7065f5e4e07839b25293?branch=fe346efc9b06926371ab7065f5e4e07839b25293&diff=unified

**Comment by MengQingJunzz** [comment]
请问这个fetch是什么方法 @RainWangjie

**Comment by RainWangjie** [comment]
> 请问这个fetch是什么方法 @RainWangjie

😓  看官方解释吧
[fetch](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API)

**Comment by dolphin0618** [comment]
chooseVideo也没有

**Comment by ZakaryCode** [comment]
更新版本哦～
