### ISSUE TITLE
修改状态不生效 this.setStte({})

### ISSUE THREAD

**Issue by MARIOMARUI** [NervJS/taro#8035]
### 相关平台
微信小程序

**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
在componentWillMount 调用函数  然后函数里面修改state的状态   然而打印出来的状态没有改变  在setState异步方法里面打印也不生效

### 期望结果
改变state里面的值

### 实际结果
无法改变

### 环境信息
```
�👽 Taro v3.0.16


  Taro CLI 3.0.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by MARIOMARUI** [comment]
![Uploading image.png…]()

**Comment by zhaoguoweiLLHC** [comment]
> 像这样 的 class 形式

图片好像没传上来

**Comment by MARIOMARUI** [comment]
> > 像这样 的 class 形式
> 
> 图片好像没传上来

![Uploading image.png…]()

**Comment by MARIOMARUI** [comment]
![Uploading 1605255096(1).jpg…]()
