### ISSUE TITLE
CoverView组件缺少marker-id属性，导致Map的CustomerCallout无法生效

### ISSUE THREAD

**Issue by wenxiangdong** [NervJS/taro#8037]
临时解决办法; 改写 node_modules/@tarojs/shared/dist/index.js; 亲测有效
```js
var CoverView = Object.assign({ 'scroll-top': 'false', 'marker-id': '', 'slot': '' }, touchEvents);
```

_Originally posted by @githubmann in https://github.com/NervJS/taro/issues/7507#issuecomment-719882563_

**Comment by Chen-jj** [comment]
3.2.6 修复，文档地址：https://docs.taro.zone/docs/components/maps/map#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B0%94%E6%B3%A1
