### ISSUE TITLE
canvas 画布不生效，也不报错

### ISSUE THREAD

**Issue by 382559544** [NervJS/taro#8039]
### 相关平台
微信小程序

**小程序基础库: 2.7**
**使用框架: Vue 2**

### 复现步骤
画布： <canvas canvas-id="mycanvas" class="mycanvas" style="width: 100%;height:600rpx;background:#eee;"/>

绘制：var ctx = Taro.createCanvasContext('mycanvas', that);
        ctx.save();
        ctx.drawImage(that.photoImg, 0, 0, 200, 200);
        ctx.restore();
        ctx.draw();
(网络图片已下载到本地，排除图片链接问题)

### 期望结果
绘制出效果

### 实际结果
绘制没有效果

### 环境信息
```
  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by shenghanqin** [comment]
我的方法是先画一个text，找找问题，再画图片。

**Comment by 382559544** [comment]
> 我的方法是先画一个text，找找问题，再画图片。

试过了，但是text也出不来，画背景颜色之类的也不行

**Comment by jlala** [comment]
const { page } = getCurrentInstance() 
你是class还是 函数组件？ 
我的也无法绘制

**Comment by 382559544** [comment]
> getCurrentInstance

我用的vue2，<canvas canvas-id="mycanvas" />
用Taro官方方法，绘制一条线都出不来

**Comment by jlala** [comment]
改用Taro.createSelectorQuery()
这个 我已经可以了
画布的canvas组件假如设置为100px，100px 然后
    Taro.createSelectorQuery()
          .select(`#${eleId}`)
          .fields({
            node: true,
            size: true
          })
          .exec(res => {
            if (res && res[0] && res[0].node) {
              const canvas = res[0].node
              const ctx = canvas.getContext('2d')
              const dpr = Taro.getSystemInfoSync().pixelRatio
              canvas.width = 100 * dpr
              canvas.height = 100 * dpr
              ctx.scale(dpr, dpr)
              
              resolve({canvas, ctx})
            } else {
              resolve({})
            }
          })

**Comment by shenghanqin** [comment]
> 改用Taro.createSelectorQuery()
> 这个 我已经可以了
> 画布的canvas组件假如设置为100px，100px 然后
> ` Taro.createSelectorQuery() .select(`#${eleId}`) .fields({ node: true, size: true }) .exec(res => { if (res && res[0] && res[0].node) { const canvas = res[0].node const ctx = canvas.getContext('2d') const dpr = Taro.getSystemInfoSync().pixelRatio canvas.width = 100 * dpr canvas.height = 100 * dpr ctx.scale(dpr, dpr) resolve({canvas, ctx}) } else { resolve({}) } })`

赞👍

**Comment by honlyHuang** [comment]
你试试这个呢？
```
// taro3 vue2 index.vue
<template>
  <view class="index">
    <text>{{ msg }}</text>
    <canvas
      id="myCanvas"
      type="2d"
    />
  </view>
</template>

<script>
import Taro from '@tarojs/taro'
import './index.css'

export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  },
  onReady () {
    const query = Taro.createSelectorQuery()
    query.select('#myCanvas').fields({ node: true, size: true }).exec((res) => {
      const canvas = res[0].node
      const ctx = canvas.getContext('2d')
      const img = canvas.createImage()
      img.src = 'https://img20.360buyimg.com/ling/jfs/t1/20876/36/12835/3043/5c9c2929Ed18cfb11/15b1c03ec830ab8e.png'
      img.onload = () => {
        ctx.drawImage(img, 0, 0, 150, 100)
      }

    })
  }
}
</script>
```
效果这样

![image](https://user-images.githubusercontent.com/3080820/99664573-563ff500-2aa3-11eb-8f34-cf759579d0c6.png)

**Comment by honlyHuang** [comment]
@382559544 你这里用了旧的微信接口，写法如下（注意需要一个`<canvas id="mycanvas" canvas-id="mycanvas" />`）
```
// taro3 vue2 index.vue
<template>
  <view class="index">
    <text>{{ msg }}</text>
    <canvas
      id="mycanvas"
      canvas-id="mycanvas"
    />
  </view>
</template>

<script>
import Taro from '@tarojs/taro'
import './index.css'

export default {
  data () {
    return {
      msg: 'Hello world!'
    }
  },
  onReady () {
    Taro.getImageInfo({src: 'https://img20.360buyimg.com/ling/jfs/t1/20876/36/12835/3043/5c9c2929Ed18cfb11/15b1c03ec830ab8e.png', success(res){
      const ctx = Taro.createCanvasContext('mycanvas')
      ctx.save();
      ctx.drawImage(res.path, 0, 0, res.width, res.height);
      ctx.restore();
      ctx.draw();

    }})
  }
}
</script>
```

**Comment by darkfiredarkhalo** [comment]
@honlyHuang 你这个写法没考虑canvas缩放的问题吧,在不同个的设备上这个canvas的大小会很奇怪, 并且`Taro.createCanvasContext`获取到的canvas对象好像是个空的吧

**Comment by darkfiredarkhalo** [comment]
涉及canvas的地方还是建议原生实现, 参考这里: https://nervjs.github.io/taro/docs/hybrid

**Comment by JakeWoki** [comment]
如果是h5怎么弄？文档里canvas相关api不支持h5,
```
<canvas :ref="cid" :id="cid"></canvas>
const canvas = this.$refs[`${this.cid}`].$el.lastElementChild//或const canvas = document.getElementById(`${this.cid}`).lastElementChild
this.ctx = canvas.getContext("2d")
```
上下文this.ctx没有setFontSize属性

**Comment by GoodLuckAlien** [comment]
> 你试试这个呢？
> 
> ```
> // taro3 vue2 index.vue
> <template>
>   <view class="index">
>     <text>{{ msg }}</text>
>     <canvas
>       id="myCanvas"
>       type="2d"
>     />
>   </view>
> </template>
> 
> <script>
> import Taro from '@tarojs/taro'
> import './index.css'
> 
> export default {
>   data () {
>     return {
>       msg: 'Hello world!'
>     }
>   },
>   onReady () {
>     const query = Taro.createSelectorQuery()
>     query.select('#myCanvas').fields({ node: true, size: true }).exec((res) => {
>       const canvas = res[0].node
>       const ctx = canvas.getContext('2d')
>       const img = canvas.createImage()
>       img.src = 'https://img20.360buyimg.com/ling/jfs/t1/20876/36/12835/3043/5c9c2929Ed18cfb11/15b1c03ec830ab8e.png'
>       img.onload = () => {
>         ctx.drawImage(img, 0, 0, 150, 100)
>       }
> 
>     })
>   }
> }
> </script>
> ```
> 
> 效果这样
> 
> ![image](https://user-images.githubusercontent.com/3080820/99664573-563ff500-2aa3-11eb-8f34-cf759579d0c6.png)

请问一下用这种方式，怎么调用 `canvasToTempFilePath ` 方法呢， 直接调用 报错
