### ISSUE TITLE
QQ小程序调起微信支付的接口

### ISSUE THREAD

**Issue by JackyLeeCS** [NervJS/taro#8042]
### 这个特性解决了什么问题？
QQ小程序可以调起微信支付，目前Taro中没有相关的API。QQ小程序相关文档地址：https://q.qq.com/wiki/develop/miniprogram/server/virtual-payment/wx_pay.html

### 这个 API 长什么样？
Taro.requestWxPayment

**Comment by Chen-jj** [comment]
试试 3.1

**Comment by ChangMM** [comment]
Taro 版本 3.4.5  
还是没有 Taro.requestWxPayment 这个方法
