### ISSUE TITLE
怎样动态设置 navigationBarTitleText 

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#805]
![image](https://user-images.githubusercontent.com/43346131/46739252-b532bd80-ccd2-11e8-9ff6-8562e21e2ee2.png)

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/native-api.html#tarosetnavigationbartitleobject

**Comment by ISBN9527** [comment]
@luckyadam 页面404 File not found
