### ISSUE TITLE
canvas 画布不生效

### ISSUE THREAD

**Issue by 382559544** [NervJS/taro#8058]
### 相关平台
微信小程序

**小程序基础库: 2.7**
**使用框架: Vue 2**

### 复现步骤
<canvas canvas-id="myCanvas"  />

绘制：var ctx = Taro.createCanvasContext('myCanvas', this);

ctx.setFillStyle('red')
ctx.fillRect(10, 10, 150, 75)
ctx.draw()

### 期望结果
页面没有绘制出结果

### 实际结果
绘制页面

### 环境信息
```
Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
taro是否有自己的创建画布的语法，麻烦告知

**Comment by Chen-jj** [comment]
Duplicate of #8039
