### ISSUE TITLE
是否可以支持不同平台小程序的project.config.json

### ISSUE THREAD

**Issue by gjc9620** [NervJS/taro#8059]
### 这个特性解决了什么问题？
现在alipay wechat都是使用project.config.json这个文件进行构建的
那么appid等别的配置不同的话切换起来比较不方便

### 这个 API 长什么样？
我提议可以根据平台来定义config.json
如
```
alipay.project.config.json
wechat.project.config.json
```

**Comment by Chen-jj** [comment]
https://taro-docs.jd.com/taro/docs/project-config

**Comment by gjc9620** [comment]
> https://taro-docs.jd.com/taro/docs/project-config

好像没有支付宝的后缀呢

**Comment by gjc9620** [comment]
@Chen-jj  不知道是不是我漏看了文档 如有请指出 谢谢

**Comment by Chen-jj** [comment]
支付宝有项目配置了吗
