### ISSUE TITLE
RN编译，rn-runner安装报错，Maximum call stack size exceeded

### ISSUE THREAD

**Issue by daivdggdev** [NervJS/taro#806]
**问题描述**
工程由taro init生成，js redux版，运行react native版本，npm run dev:rn
控制台报如下错误：

![image](https://user-images.githubusercontent.com/6511015/46742457-a3084d80-ccd9-11e8-8a32-690ec08ae22a.png)

**系统信息**

 - 操作系统: [macOS High Sierra]
 - Taro 版本 [v1.0.7]
 - Node.js 版本 [v8.12.0]
 - 报错平台 [rn]

**Comment by Pines-Cheng** [comment]
手动安装 @tarojs/rn-runner 依赖，然后再重启项目。

**Comment by daivdggdev** [comment]
@Pines-Cheng 手动安装依然是这个报错

**Comment by Pines-Cheng** [comment]
删除全部依赖，包括根目录下的和 .rm_temp 目录下的，然后全部手动安装，再重新启动。

**Comment by daivdggdev** [comment]
@Pines-Cheng 现在可以了

**Comment by Yechuanjie** [comment]
> @Pines-Cheng 现在可以了

请问你单独安装@tarojs/rn-runner的时候，有出现hash错误的情况吗
![image](https://user-images.githubusercontent.com/18052499/53466114-8b184700-3a8b-11e9-8483-0c4b21737271.png)
