### ISSUE TITLE
swiper 建议

### ISSUE THREAD

**Issue by MARIOMARUI** [NervJS/taro#8068]
### 这个特性解决了什么问题？
swiper 现在不论是否阻止dom更新 都会触发swiper变更，能否出一个属性，阻止默认的滑动事件和点击事件，然后给一个手动调用滑动的事件。完成按钮点击触发滑动功能。我也试过当前e.target.current 和 state.current 作比较 然后试着让他不能忘前面滑，但是无效。所以求次属性。

### 这个 API 长什么样？
class：swiper-no-swiping

attr：catchtouchmove

**Comment by ZakaryCode** [comment]
编译平台是？
