### ISSUE TITLE
npm 内的资源路径处理异常

### ISSUE THREAD

**Issue by YikaJ** [NervJS/taro#807]
场景：我使用一个基于 Taro 编写的 npm 组件包，然后其中一个组件引用了内部的图片资源，但是资源路径处理应该异常了，导致图片无法正常获取。

组件包的编译是参考 Taro-UI
```
$ cross-env TARO_BUILD_TYPE=component taro build --ui
```

问题：

这是编译后的图片
![image](https://user-images.githubusercontent.com/8725110/46750594-ddc6b180-ccea-11e8-8e91-0c835645c075.png)

期望：

实际正确的地址应该是
```
/npm/@group/xxxx
```

**Comment by luckyadam** [comment]
贴一下组件包的代码地址呢
