### ISSUE TITLE
在自定义组件中引入 taro-ui 报错，生成的 usingComponents 路径有误

### ISSUE THREAD

**Issue by Jeepeng** [NervJS/taro#808]
**问题描述**
在自定义组件中引入 taro-ui 报错，生成的 usingComponents 路径有误

**复现步骤**

在自定义组件 ListItem 中引入并且使用：
```js
import { AtIcon } from 'taro-ui';
```
然后就报错了

**报错信息**

```js
jsEnginScriptError
Component is not found in path "components/list/taro-ui" (using by "components/list/ListItem")
Error: Component is not found in path "components/list/taro-ui" (using by "components/list/ListItem")
```

**系统信息**

 - 操作系统: macOS
 - Taro 版本 v1.1.0-beta.3
 - Node.js 版本 v10.10.0
 - 报错平台 weapp

**补充信息**

貌似是这个提交导致的：https://github.com/NervJS/taro/commit/a06480423a35379960e89d2e692a19befe0d2c84

1.1.0-beta.3 生成的 ListItem.json
```json
{
  "component": true,
  "usingComponents": {
    "at-icon": "taro-ui"
  }
}
```
正确的 ListItem.json 应该是：
```
{
  "component": true,
  "usingComponents": {
    "at-icon": "../../../npm/taro-ui/dist/weapp/components/icon/index"
  }
}
```

**Comment by luckyadam** [comment]
Close via feece2d2684011e2b57ab2992bc3bf7195345a8f

**Comment by jinjinwa** [comment]
又遇到同样的问题。。taro-ui和taro都是最新版

**Comment by kolf** [comment]
解决了吗？我也碰到了

**Comment by beysong** [comment]
我也碰到了
