### ISSUE TITLE
ios 9: strict mode does not allow function declarations in a lexically nested statement

### ISSUE THREAD

**Issue by huanz** [NervJS/taro#8082]
### 相关平台
H5

### 复现仓库
[https://github.com/huanz/taro](https://github.com/huanz/taro)
**浏览器版本: ios 9.3.5**
**使用框架: React**

### 复现步骤
调试发现 @tarojs/components/dist/esm/polyfills/index.js 里面 applyPolyfills 方法在 if 外定义了一个 checkIfURLIsSupported 导致的，辛苦修复下，感谢~~~  改成 var checkIfURLIsSupported = ... 即可

### 期望结果
无报错

### 实际结果
strict mode does not allow function declarations in a lexically nested statement

### 环境信息
```
Taro v3.0.15


  Taro CLI 3.0.15 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.2.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.10 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.15 => 3.0.15 
      @tarojs/components: 3.0.15 => 3.0.15 
      @tarojs/mini-runner: 3.0.15 => 3.0.15 
      @tarojs/react: 3.0.15 => 3.0.15 
      @tarojs/runtime: 3.0.15 => 3.0.15 
      @tarojs/taro: 3.0.15 => 3.0.15 
      @tarojs/webpack-runner: 3.0.15 => 3.0.15 
      babel-preset-taro: 3.0.15 => 3.0.15 
      react: ^17.0.1 => 17.0.1 
```

**Comment by huanz** [comment]
@ZakaryCode

**Comment by luckyadam** [comment]
OJBK

**Comment by huanz** [comment]
https://github.com/ionic-team/stencil/blob/master/src/client/polyfills/index.js

**Comment by ZakaryCode** [comment]
ionic-team/stencil#2749#event-4096028923

这并非是一个 taro 的问题，stencil 两天前合并该 pr 了，将版本发布后应该会自动修复该问题
