### ISSUE TITLE
taro init 选择wxplugin生成插件项目运行报错

### ISSUE THREAD

**Issue by wuguofang** [NervJS/taro#8087]
taro版本 v3.0.17
操作 taro init test-plugin
选择 wxplugin
npm i
npm run build:weapp
微信开发者工具直接打开报错
提示找不到components/avatar/avatar.js、components/avatar/avatar.wxml、components/avatar/avatar.json文件
报错如图
![image](https://user-images.githubusercontent.com/13746058/99766764-b5057d00-2b3c-11eb-9ee9-563fc0916cb5.png)

插件内的代码没被编译才没有这些文件
请问是我打开的姿势不对吗？

**Comment by Chen-jj** [comment]
3.x 还没支持编写插件

**Comment by Ark-Chen** [comment]
@Chen-jj 您好，请问目前3.x对于支持插件编写是计划内的事儿吗，大概什么时候会推出该功能呢
