### ISSUE TITLE
taro init 选择wxplugin生成插件项目运行报错

### ISSUE THREAD

**Issue by wuguofang** [NervJS/taro#8088]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/wuguofang/test-plugin.git](https://github.com/wuguofang/test-plugin.git)
**小程序基础库: 无关**
**使用框架: React**

### 复现步骤
taro init test-plugin
模版选择 wxplugin
npm i
npm run build:weapp
微信开发者工具直接打开报错
提示找不到components/avatar/avatar.js、components/avatar/avatar.wxml、components/avatar/avatar.json文件
插件内的代码没被编译才没有这些文件

### 期望结果
微信开发者工具打开不报错

### 实际结果
报错，找不到上述三个文件

### 环境信息
```
Version 9 of Highlight.js has reached EOL and is no longer supported. Please upgrade to version 10.

  Taro CLI 3.0.17 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.17 => 3.0.17
      @tarojs/mini-runner: 3.0.17 => 3.0.17
      @tarojs/react: 3.0.17 => 3.0.17
      @tarojs/runtime: 3.0.17 => 3.0.17
      @tarojs/taro: 3.0.17 => 3.0.17
      @tarojs/webpack-runner: 3.0.17 => 3.0.17
      babel-preset-taro: 3.0.17 => 3.0.17
      eslint-config-taro: 3.0.17 => 3.0.17
      react: ^16.10.0 => 16.14.0
```

**Comment by wuguofang** [comment]
回到2.x版本taro build --plugin weapp就行了。。。。

**Comment by yddydd** [comment]
> 回到2.x版本taro build --plugin weapp就行了。。。。

taro 2.2.16

**Comment by yddydd** [comment]
> 回到2.x版本taro build --plugin weapp就行了。。。。
taro 2.2.16 你有出现这样的情况吗？
taro build --plugin weapp --watch可以在开发者工具预览
taro build --plugin weapp 就不行了
