### ISSUE TITLE
build 处于 yarn workspace 中的 taro 项目会输出两个不同的 dist 目录

### ISSUE THREAD

**Issue by fishead** [NervJS/taro#809]
**问题描述**
taro build 没有正确输出依赖文件

**复现步骤**
- git clone 示例项目 
```shell
git clone https://github.com/fishead/taro-in-yarn-workspace
```
- 进入项目根目录
```shell
cd taro-in-yarn-workspace
```
- 安装依赖
```shell
yarn
```
- 进入 taro app 目录
```shell
cd packages/taro-init-app
```
- build app
```shell
yarn run build:weapp
```

此时可以观察到出现了两个 dist 目录
- `taro-in-yarn-workspace/dist`
- `taro-in-yarn-workspace/packages/taro-init-app/dist`

**期望行为**
所有文件输出到 `taro-in-yarn-workspace/packages/taro-init-app/dist `

**系统信息**
 - 操作系统: `MacOS Mojave`
 - Taro 版本: `v1.0.7`
 - Node.js 版本: `v10.7.0`
 - 报错平台: `weapp`, 其他未测试

**Comment by luckyadam** [comment]
主要是因为你的项目根目录也有一个 package.json ，导致 yarn 安装的包到了根目录底下，所以 node_mdoules 里的资源都被提取到了根目录

**Comment by zcfan** [comment]
@luckyadam 我瞄一下，顺便熟悉下项目

**Comment by zcfan** [comment]
#816

**Comment by fishead** [comment]
> 主要是因为你的项目根目录也有一个 package.json ，导致 yarn 安装的包到了根目录底下，所以 node_mdoules 里的资源都被提取到了根目录

确实是有，这是 yarn workspace 功能的必要文件结构

**Comment by luckyadam** [comment]
Duplicate of #1018
