### ISSUE TITLE
3.x版本使用小程序原生第三方组件编译时报Template  not found

### ISSUE THREAD

**Issue by young-ren** [NervJS/taro#8090]
### 相关平台
微信小程序

**小程序基础库: 2.14.0 包括其他版本**
**使用框架: React**

### 复现步骤
编译完成后小程序开发者工具出现
WXMLRT_$gwx:./base.wxml:template:749:16: Template `tmpl_0_dialog` not found.
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_dialog` not found.
  747 | 
  748 | <template name="tmpl_5_container">
> 749 |   <template is="{{xs.a(5, i.nn, l)}}" data="{{i:i,cid:5,l:xs.f(l,i.nn)}}" />
      |                ^
  750 | </template>
  751 | 
  752 | <template name="tmpl_6_view">

### 期望结果
希望能找到模板能出现组件样式在界面

### 实际结果
组件页面未出现

### 环境信息
```
  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by young-ren** [comment]
使用的是weui的dialog组件

**Comment by Chen-jj** [comment]
上代码吧

**Comment by young-ren** [comment]
//index.jsx
import React, { Component } from 'react'
import { View } from '@tarojs/components'
export default class Dialog extends Component {
    constructor(props) {
        super(props)
        this.state = {
            extClass: '',
            title: '温馨提示',
            text: '网络异常',
            buttons: [{ text: '取消' }, { text: '确定' }],
            mask: true,
            maskClosable: false,
            show: false,
            confirm: () => { },
            cancel: () => { },
            bindclose: () => { },
        }
    }
    buttonClick = (e) => {
        const { confirm, cancel } = this.state
        e.detail.index === 0 && cancel()
        e.detail.index === 1 && confirm()
    }
    show = (options) => {
        this.setState({
            ...options
        })
    }
    hide = () => {
        this.setState({
            show: false
        })
    }
    render() {
        const { extClass, title, text, maskClosable, show, buttons, mask } = this.state
        return (
            <View>
                <dialog
                    title={title}
                    show={show}
                    buttons={buttons}
                    mask={mask}
                    maskClosable={maskClosable}
                    onClose={this.cancelClick}
                    onButtontap={this.buttonClick}
                >
                    {text}
                </dialog>
            </View>
        )
    }
}


//index.config.js
export default {
  usingComponents: {
    "dialog": "./dialog/dialog" // 书写第三方组件的相对路径
  }
}
![捕获](https://user-images.githubusercontent.com/44925924/99776558-f94c4980-2b4b-11eb-8ea1-1272f76f43bd.PNG)

**Comment by young-ren** [comment]
@Chen-jj

**Comment by young-ren** [comment]
![Uploading 捕获.PNG…]()

**Comment by young-ren** [comment]
![捕获](https://user-images.githubusercontent.com/44925924/99777654-978cdf00-2b4d-11eb-95b6-9d2fdce60f09.PNG)

**Comment by Chen-jj** [comment]
提供一个可运行的 demo

**Comment by Chen-jj** [comment]
测试了没有问题，目测 `usingComponents` 路径指错了，再 debug 下吧。

![image](https://user-images.githubusercontent.com/11807297/102782508-72052680-43d4-11eb-86bc-9893d40053bd.png)

**Comment by wei1034937343** [comment]
同样的问题，经常出现时好时坏

**Comment by hugyu** [comment]
> 同样的问题，经常出现时好时坏
老哥解决了吗

**Comment by young-ren** [comment]
> > 同样的问题，经常出现时好时坏
> > 老哥解决了吗

我重写了。。过去太久了，现在项目用的react组件

**Comment by hugyu** [comment]
> > > 同样的问题，经常出现时好时坏
> > > 老哥解决了吗
> 
> 我重写了。。过去太久了，现在项目用的react组件

我Taro3.5.4都出现了卧槽

**Comment by young-ren** [comment]
> > > > 同样的问题，经常出现时好时坏
> > > > 老哥解决了吗
> > 
> > 
> > 我重写了。。过去太久了，现在项目用的react组件
> 
> 我Taro3.5.4都出现了卧槽

你应该是写在组件目录了吧，你把这个写在单独一个页面里面，我预计不会报错

**Comment by hugyu** [comment]
> > > > > 同样的问题，经常出现时好时坏
> > > > > 老哥解决了吗
> > > 
> > > 
> > > 我重写了。。过去太久了，现在项目用的react组件
> > 
> > 
> > 我Taro3.5.4都出现了卧槽
> 
> 你应该是写在组件目录了吧，你把这个写在单独一个页面里面，我预计不会报错我试试吧谢谢啦

**Comment by young-ren** [comment]
> > > > > > 同样的问题，经常出现时好时坏
> > > > > > 老哥解决了吗
> > > > 
> > > > 
> > > > 我重写了。。过去太久了，现在项目用的react组件
> > > 
> > > 
> > > 我Taro3.5.4都出现了卧槽
> > 
> > 
> > 你应该是写在组件目录了吧，你把这个写在单独一个页面里面，我预计不会报错我试试吧谢谢啦

时光如梭，都两年了 哈哈

**Comment by hugyu** [comment]
> > > > > > > 同样的问题，经常出现时好时坏
> > > > > > > 老哥解决了吗
> > > > > 
> > > > > 
> > > > > 我重写了。。过去太久了，现在项目用的react组件
> > > > 
> > > > 
> > > > 我Taro3.5.4都出现了卧槽
> > > 
> > > 
> > > 你应该是写在组件目录了吧，你把这个写在单独一个页面里面，我预计不会报错我试试吧谢谢啦
> 
> 时光如梭，都两年了 哈哈

所以老哥现在在哪

**Comment by evin2333** [comment]
![image](https://user-images.githubusercontent.com/70325455/207204659-84811518-bf63-48c7-810f-2269af84b7b5.png)
![image](https://user-images.githubusercontent.com/70325455/207204790-85b9dedd-4759-4d95-af9b-af5e72105132.png)
![image](https://user-images.githubusercontent.com/70325455/207204830-3fc85037-d000-4348-aafa-b6a0d91c602b.png)
![image](https://user-images.githubusercontent.com/70325455/207205181-547e55a5-537e-4385-8074-8d44979fb3c2.png)

只开启preloadRule不会报错，添加了taro-plugin-compiler-optimization之后build一下，预览会报错，原生form渲染不出来

**Comment by evin2333** [comment]
![image](https://user-images.githubusercontent.com/70325455/207205463-79fe80f6-2f21-4118-89a0-c923505d8d2b.png)
![image](https://user-images.githubusercontent.com/70325455/207205501-a305becf-84ae-46ed-81e1-2c9f57523f8c.png)
![image](https://user-images.githubusercontent.com/70325455/207205548-c83a5755-47bb-40a1-8dfa-660877f39ebf.png)
![image](https://user-images.githubusercontent.com/70325455/207205705-8bd97b4d-5ddf-4cbe-a5a9-cf1cf9b9c921.png)
taro-plugin-compiler-optimization使用这个插件后报错，form渲染不出来

**Comment by xyw1229** [comment]
老项目重新跑这个问题 🤯🤯

**Comment by fakelove7** [comment]
也遇到这个问题了，用的taroui，跑起来就报这个问题，taro和ui都用的3.x

**Comment by he1237596** [comment]
> 也遇到这个问题了，用的taroui，跑起来就报这个问题，taro和ui都用的3.x

+1

**Comment by 31231313131fdsf** [comment]
同样是这个问题， AtForm 显示不出来

**Comment by wojiaoshupian** [comment]
> 同样是这个问题， AtForm 显示不出来

+1
