### ISSUE TITLE
希望支持react-native 转 taro 或者 tart转rn

### ISSUE THREAD

**Issue by YoungMarshal-LI** [NervJS/taro#8099]
### 这个特性解决了什么问题？
公司有rn编写的app，每一次更新迭代h5，小程序，都要同步迭代，大大增加人员和时间成本

### 这个 API 长什么样？
期望rn转taro

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/pull/8093

**Comment by YoungMarshal-LI** [comment]
> [＃8093](https://github.com/NervJS/taro/pull/8093)

rn-taro可以吗

**Comment by Chen-jj** [comment]
> > [＃8093](https://github.com/NervJS/taro/pull/8093)
> 
> rn-taro可以吗

目前不会考虑 RN -> taro
