### ISSUE TITLE
Taro开发项目怎么调用硬件资源？

### ISSUE THREAD

**Issue by yuzhongyouqing** [NervJS/taro#81]
如果APP中需要调用硬件，
比如：
微信小程序 调用 Map地图、音频、视频 硬件API；
React Native 调用硬件拍照、插件等等；
这个需要分开适配，还是Taro计划开发出API统一适配？

**Comment by luckyadam** [comment]
我们会提供统一的api，api规范会遵循微信小程序的api规范，不同的端有不同实现

**Comment by LuSir001** [comment]
什么时候能完成这些api
