### ISSUE TITLE
小程序关闭后，再扫码进入显示空白

### ISSUE THREAD

**Issue by lmm1990** [NervJS/taro#8103]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/lmm1990/taro-bug-test](https://github.com/lmm1990/taro-bug-test)
**小程序基础库: 未设置**
**使用框架: Vue 3**

### 复现步骤
1、项目运行后微信开发者工具-》预览-》二维码预览
2、手机扫码打开小程序-》点击小程序关闭按钮
3、再扫码进入小程序，显示空白

### 期望结果
应该显示第一次扫码进入小程序的内容

### 实际结果
显示空白

### 环境信息
```
Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 15.2.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.0.8 - C:\Program Files\nodejs\npm.CMD

```

**Comment by lmm1990** [comment]
预览第一次扫码
![image](https://user-images.githubusercontent.com/4828501/99950295-497b1400-2db7-11eb-9da3-61f26ef2b69c.png)
显示正常：
![image](https://user-images.githubusercontent.com/4828501/99950424-7a5b4900-2db7-11eb-9c50-8cfe2a8e7e34.png)

**Comment by lmm1990** [comment]
点击小程序关闭按钮：
![image](https://user-images.githubusercontent.com/4828501/99950551-a2e34300-2db7-11eb-8b82-a62b4ebff665.png)
再次扫码后显示空白：
![image](https://user-images.githubusercontent.com/4828501/99950680-e0e06700-2db7-11eb-9bcd-38adaadbcd3a.png)
![image](https://user-images.githubusercontent.com/4828501/99950690-e50c8480-2db7-11eb-9470-c9fb9edde6fd.png)

**Comment by lmm1990** [comment]
经调试【编译后dist目录】，第一次打开小程序后
taro.js 中
key: "performUpdate",
    value: function performUpdate() {
_this13.updatePayloads变量值为： [{"path":"root.cn.[0]"},{"path":"root.uid","value":"pages/index/index"},{"path":"root.cl","value":""}]

第二次打开，_this13.updatePayloads变量值为： []

**Comment by mokinzhao** [comment]
解决了吗？啥时候有更新包

**Comment by lmm1990** [comment]
等下个版本发布

**Comment by mokinzhao** [comment]
我降级到vue2.x为何就可以了
