### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module './dist/index.js'

### ISSUE THREAD

**Issue by wang89jun** [NervJS/taro#8106]
### 相关平台
微信小程序

**小程序基础库: 最新版**
**使用框架: React**

### 复现步骤
本地问题，无法代码重现

### 期望结果
安装最新版tarocli  3.0.0  ，npm run dev:weapp  编译报错“UnhandledPromiseRejectionWarning: Error: Cannot find module './dist/index.js'”

### 实际结果
编译正常dist包

### 环境信息
```
Taro CLI 3.1.0-beta.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.10.1 - C:\Users\wanghui\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
CLI 和依赖版本保持一致，CLI 装了 beta2，依赖也要是 beta2
