### ISSUE TITLE
微信端编译时组件中的style属性会丢失 -webkit-text-fill-color , -webkit-text-stroke 等样式

### ISSUE THREAD

**Issue by heyi** [NervJS/taro#8109]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/heyi/Taro-vue2-style-bug](https://github.com/heyi/Taro-vue2-style-bug)
**小程序基础库: ios 7.017**
**使用框架: Vue 2**

### 复现步骤
npm run dev:weapp 后察看编译代码，可以看到 -webkit-text-fill-color 等样式丢失了

### 期望结果
正常显示 -webkit-text-fill-color ,-webkit-text-stroke-color 等属性

### 实际结果
-webkit-text-fill-color ,-webkit-text-stroke-color 等属性丢失了

### 环境信息
```
 Taro v3.0.16


  Taro CLI 3.0.16 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.npm/bin/yarn
      npm: 6.14.7 - ~/.npm/bin/npm
    npmPackages:
      @tarojs/components: 3.0.16 => 3.0.16
      @tarojs/mini-runner: 3.0.16 => 3.0.16
      @tarojs/runtime: 3.0.16 => 3.0.16
      @tarojs/taro: 3.0.16 => 3.0.16
      @tarojs/webpack-runner: 3.0.16 => 3.0.16
      babel-preset-taro: 3.0.16 => 3.0.16
      eslint-config-taro: 3.0.16 => 3.0.16

```

---
### 补充信息
  https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/dom/style_properties.ts  这里未考虑自定义样式以及webkit 开头的样式等等。这些场景还是很常见的，希望能解决这个问题或者提供配置能补充到这些需要用到的样式。

**Comment by honlyHuang** [comment]
如果紧急可以使用[这个办法 ](https://taro-docs.jd.com/taro/docs/size#%E5%BF%BD%E7%95%A5%E6%A0%B7%E5%BC%8F%E6%96%87%E4%BB%B6)

**Comment by lmarklil** [comment]
mask backdrop-filter 这些属性也需要webkit前缀
