### ISSUE TITLE
包含分包时H5页面路径引用错误

### ISSUE THREAD

**Issue by StingKo** [NervJS/taro#811]
**问题描述**
当代码中包含微信小程序提供的分包(subPackages)时，分包页面打包成H5引用路径错误。

**复现步骤**
例如app.js包含
```js
subPackages: [
      {
        root: 'packages/xxx',
        pages: [
          'pages/yyy/index'
        ]
      }
]

```

打包为H5后访问分包页面报错

```js
Module not found: Can't resolve './pages/yyy/index' in '/Users/User/Workspaces/ProjectName/.temp'

```

_问题原因目测是包含分包时h5打包后路径没有包含包名 即app.js配置内subPackages.name_

**系统信息**

 - 操作系统: Macos 10.14
 - Taro 版本 v1.1.0-beta.4
 - Node.js 版本 v10.12.0
 - 报错平台 h5

**Comment by XiaoSongWolf** [comment]
可以写成全路径，app.js文件中定义的路径前面加反斜杠
`pages: [
          '/pages/yyy/index'
        ]`

**Comment by luckyadam** [comment]
收到，编译到 H5 没有处理 `subPackages` 字段，导致分包页面没有被解析到，我们修复下~

**Comment by Sting-Gao** [comment]
> 收到，编译到 H5 没有处理 `subPackages` 字段，导致分包页面没有被解析到，我们修复下~

@luckyadam 辛苦了~

**Comment by MisterWhoDevelopers** [comment]
大概多久能修复 @luckyadam

**Comment by luckyadam** [comment]
@MisterWhoDevelopers 已修复~ 全部升级到 `1.1.0-beta.11` 即可~

**Comment by luckyadam** [comment]
34d3d02dafd5cdb374374097b7173eed527b331f

**Comment by yinlsea** [comment]
用1.1.0正式版本，还是有这个问题

**Comment by luckyadam** [comment]
@yinlsea 配置贴一下
