### ISSUE TITLE
微信小程序热启动情况下进入页面白屏

### ISSUE THREAD

**Issue by foyel** [NervJS/taro#8119]
### 相关平台
微信小程序

**小程序基础库: 2.13.2**
**使用框架: Vue 3**

### 复现步骤
1、通过微信开发者工具上传代码 -> 小程序后台查询体验版二维码
2、手机扫码打开小程序 -> 点击小程序关闭按钮
3、再扫码进入小程序，显示空白

注：经查询应该是热启动会有白屏的问题，发现在线上的小程序热启动进入也会白屏

### 期望结果
页面正常

### 实际结果
页面空白

### 环境信息
```
Taro CLI 3.1.0-beta.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.1.0-beta.1 => 3.1.0-beta.1
      @tarojs/mini-runner: 3.1.0-beta.1 => 3.1.0-beta.1
      @tarojs/runtime: 3.1.0-beta.1 => 3.1.0-beta.1
      @tarojs/taro: 3.1.0-beta.1 => 3.1.0-beta.1
      @tarojs/webpack-runner: 3.1.0-beta.1 => 3.1.0-beta.1
      babel-preset-taro: 3.1.0-beta.1 => 3.1.0-beta.1
      eslint-config-taro: 3.1.0-beta.1 => 3.1.0-beta.1
    npmGlobalPackages:
      typescript: 3.8.3
```
我在created、 mounted等生命周期方法里添加打印日志，发现第一次进入渲染正常的是有打印日志的，页面空白的没有打印，说明应该没有执行

![511606212029_ pic](https://user-images.githubusercontent.com/17547882/100078877-f79dc100-2e7e-11eb-884c-32967543eb26.jpg)

![501606212028_ pic](https://user-images.githubusercontent.com/17547882/100078861-f4a2d080-2e7e-11eb-93ac-78b89d9f3066.jpg)

**Comment by foyel** [comment]
@Chen-jj  麻烦帮忙看下，现在我们的小程序线上有这个问题，应该如何解决

**Comment by lmm1990** [comment]
和这个是一个问题
https://github.com/NervJS/taro/issues/8103

**Comment by foyel** [comment]
请问下这个问题什么时候能解决啊

**Comment by pecopeco** [comment]
急急急

**Comment by lmm1990** [comment]
@pecopeco 已经修复了。https://github.com/NervJS/taro/milestone/28?closed=1
版本：3.0.19 会发布

**Comment by mokinzhao** [comment]
很急明天要上线了，希望大佬赶紧发包

**Comment by pecopeco** [comment]
> 很急明天要上线了，希望大佬赶紧发包

暂时可以使用手动销毁dom再重建的方式触发页面重载

**Comment by Chen-jj** [comment]
@mokinzhao 线上用户不存在这种热启动的情况吧，只会打开一次，后续打开不会触发页面重载。一般在调试时才会触发这种情况，扫码再扫码、分享后再从分享入口进入。

**Comment by weicheng-git** [comment]
所以解决了吗，我也遇到这个问题了

**Comment by lmm1990** [comment]
@weicheng-git 已经解决了，taro升级到最新版本即可
