### ISSUE TITLE
获取不到 canvas dom ?

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#812]
![image](https://user-images.githubusercontent.com/43346131/46785358-18206500-cd64-11e8-93e8-8c77a4b51375.png)

**Comment by luckyadam** [comment]
小程序里没有 dom 啊

**Comment by JoMartinezZhu** [comment]
![image](https://user-images.githubusercontent.com/43346131/46792480-0cd63500-cd76-11e8-9648-bb55b470db7e.png)
![image](https://user-images.githubusercontent.com/43346131/46792512-20819b80-cd76-11e8-9ccc-72ca948acddd.png)
![image](https://user-images.githubusercontent.com/43346131/46792529-2aa39a00-cd76-11e8-8590-0898a99f707f.png)
![image](https://user-images.githubusercontent.com/43346131/46792556-355e2f00-cd76-11e8-9a4c-34aa261b0954.png)
节点上是 size 值的但是 通过 
```
Taro.createSelectorQuery().in(this.$scope).select('#trackCvs').boundingClientRect(rect => {
      console.log(rect);
    }).exec();
```
却获取的值都是0
