### ISSUE TITLE
Video标签中使用CoverView无效

### ISSUE THREAD

**Issue by zhaoguoweiLLHC** [NervJS/taro#8126]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/zhaoguoweiLLHC/taro-issues-video-2020-11-25](https://github.com/zhaoguoweiLLHC/taro-issues-video-2020-11-25)
**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
```jsx
<Video>
  <CoverView>123</CoverView>
</Video>
```

### 期望结果
cover-view 正确被video包裹
```html
<video>
  <cover-view>123</cover-view>
</video>
```

### 实际结果
cover-view 未被包裹，却包裹了当前视频的观看秒数。
```html
<video>00:00</video>
```

### 环境信息
```
� Taro v3.0.17


  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD



```

**Comment by yaoqicaicaicai** [comment]
我遇到同样的问题，为什么来解释哈

**Comment by yaoqicaicaicai** [comment]
我遇到了同样的问题，没人来解释哈吗

**Comment by zhaoguoweiLLHC** [comment]
> 我遇到了同样的问题，没人来解释哈吗

我目前用和小程序代码混写来跳坑了。
