### ISSUE TITLE
Taro3.0 子包的依赖不要合并编译至主包的 common.js

### ISSUE THREAD

**Issue by pangnate** [NervJS/taro#8127]
### 这个特性解决了什么问题？
编译完成后子包的依赖被合并编译至 common.js、common.wxss，导致主包体积超过2M限制

### 这个 API 长什么样？
希望 Taro3 的编译根据文件的实际所处位置，不要自动合并至主包，由开发者自行划分主子包文件。

目前Taro的用户绝大多数应该都是企业开发者，业务相对复杂。如果一定要通过复杂的 addChunkPages 配置才能分割，势必会造成很多用户无法使用 3.0。

**Comment by Chen-jj** [comment]
https://taro-docs.jd.com/taro/docs/next/config-detail#miniaddchunkpages

**Comment by luckyadam** [comment]
暂时用 addChunkPages，社区有提交一个方案，我们需要研究一下才能合入，具体请见 #8135

**Comment by pangnate** [comment]
收到，希望早提支持，感谢
