### ISSUE TITLE
使用less时不能传递参数

### ISSUE THREAD

**Issue by XiaoSongWolf** [NervJS/taro#813]
**问题描述**
使用less时，传递参数会报错
老项目是同事使用wepy开发的，现在要求支持跨端（小程序+h5），改用Taro开发，迁移中发现使用了一个布局框架wepy-weui-demo(GitHub: https://github.com/wepyjs/wepy-weui-demo)，导入编译，发现传递参数的地方会报错。

**复现步骤**
1. 下载并导入wepy-weui-demo框架；
2. 导入并编译运行

编译报错结果：
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

._setArrow(@arrowsize, @borderColor, @borderWidth){
^
      Invalid CSS after ".": expected 1 selector or at-rule, was "._setArrow(@arrowsi"
      in /lib/weui/style/base/mixin/setArrow.less (line 1, column 1)

**期望行为**
在使用less时可以传递参数

**报错信息**
![image](https://user-images.githubusercontent.com/19815977/46786024-34250600-cd66-11e8-8aeb-39b733602c6f.png)

**系统信息**

 - 操作系统: [e.g. Mac 10.13.6]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.11.1]
 - 报错平台 [h5, weapp]

**补充信息**
将传递参数的地方进行修改，去掉参数传递，可以编译成功

**Comment by shenghanqin** [comment]
@XiaoSongWolf 这个问题后续如何改的呢？

**Comment by heyuuuu** [comment]
> Hello~
> 
> 您的问题所提供的信息不足，我们无法定位到具体的问题。如果有空的话还请拔冗提供更具体的信息，否则这个 issue 将在 15 天后被自动关闭。
> 
> 如果您在这 15 天中更新更多信息自动关闭的流程会自动取消，如有其他问题也可以发起新的 Issue。
> 
> Good luck and happy coding~

卧槽，这明显是你们挖的坑好么，在https://github.com/NervJS/taro/blob/next/packages/taro-webpack-runner/package.json这个配置里面，你们应该吧less以及less-loader放在peerDependencies里面，这样我们才能手动指定新版本，虽然我们指定新版本，但是在首次构建的时候编译的是你们定义的less版本，这里就有深坑了，差点没爬起来
