### ISSUE TITLE
Promise finally 在 iOS （14.2 ，13.4.1） 中报错

### ISSUE THREAD

**Issue by hlsky1988** [NervJS/taro#8137]
### 相关平台
微信小程序

**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
Promise finally 在 iOS （14.2 ，13.4.1） 中报错

### 期望结果
Promise finally 正常执行

### 实际结果
undefined is not function

### 环境信息
```
  Taro CLI 2.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD   
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD  
```

**Comment by hlsky1988** [comment]
查了一下好像是微信的问题 。。。。

附上处理方案 https://www.cnblogs.com/ljybill/p/10097852.html

**Comment by TechQuery** [comment]
@hlsky1988 其实直接引入 polyfill 即可：https://github.com/gabmontes/promise-prototype-finally

先执行命令：

```Shell
npm install promise-prototype-finally
```

再在**项目入口文件**开头加上：

```JS
import 'promise-prototype-finally';
```

**Comment by crazyair** [comment]
> @hlsky1988 其实直接引入 polyfill 即可：https://github.com/gabmontes/promise-prototype-finally
> 
> 先执行命令：
> 
> ```shell
> npm install promise-prototype-finally
> ```
> 
> 再在**项目入口文件**开头加上：
> 
> ```js
> import 'promise-prototype-finally';
> ```

为什么不用 promise.prototype.finally 呢，我用这个 . 的不行，用 - 的可以。
