### ISSUE TITLE
接入阿拉丁SDK无法获取统计数据

### ISSUE THREAD

**Issue by HuMoran** [NervJS/taro#814]
使用taro框架开发的小程序，接入阿拉丁数据统计sdk后，在阿拉丁那边无法获取统计数据。
阿拉丁SDK地址：http://doc.aldwx.com/aldwx/gao-ji-gong-neng/sdkjie-ru-zhi-nan.html
联系了阿拉丁那边客服，说的是需要做适配工作，但是相关开发人员请假了，不知道什么时候能出来……

**Comment by loveonelong** [comment]
@HuMoran @luckyadam  看阿拉丁的文档是已经支持了。http://doc.aldwx.com/aldwx/frame/taro-jie-ru.html

**Comment by shenghanqin** [comment]
官方好像已经支持了类似的统计了吧。
