### ISSUE TITLE
taro convert 将原生小程序转化为 taro 的代码后续有没有计划支持微信小程序的 relations 呢？

### ISSUE THREAD

**Issue by zhengpq** [NervJS/taro#8142]
### 这个特性解决了什么问题？
目前 taro 的官方文档中明确说明使用 taro convert 将微信小程序转化为 taro 的代码的时候是不支持小程序的 relation 的，但是现实中在很多情况下在写组件的时候确实会用到 relations 这个功能，所以这里想请教一下后续是否有计划支持这个功能的转换，感谢！

### 这个 API 长什么样？
支持微信小程序 relations 的转化

**Comment by Chen-jj** [comment]
没有计划支持的，建议使用 React 的逻辑改写吧。
