### ISSUE TITLE
Taro 3 H5下  taro-image-core 样式设置为 width: 320px;   height: 240px; 导致为显示设置尺寸的图片样式错误

### ISSUE THREAD

**Issue by chunge66** [NervJS/taro#8143]
### 相关平台
H5

**浏览器版本: Chrome 87**
**使用框架: React**

### 复现步骤
Taro 2 升级到 Taro 3后，H5项目容器display: flex下 图片 样式显示错误，检查发现默认样式导致：

taro-image-core {
    display: inline-block;
    overflow: hidden;
    position: relative;
    font-size: 0;
    width: 320px;
    height: 240px;
}

### 期望结果
H5编译后 taro-image-core 不应该设置默认宽高：
taro-image-core {
    display: inline-block;
    overflow: hidden;
    position: relative;
    font-size: 0;
    // width: 320px;
    // height: 240px;
}

### 实际结果
H5编译也设置了默认宽高
taro-image-core {
    display: inline-block;
    overflow: hidden;
    position: relative;
    font-size: 0;
    width: 320px;
    height: 240px;
}

### 环境信息
```
Taro CLI 3.0.16 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.16 => 3.0.16 
      @tarojs/components: 3.0.16 => 3.0.16 
      @tarojs/mini-runner: 3.0.16 => 3.0.16 
      @tarojs/react: 3.0.16 => 3.0.16 
      @tarojs/runtime: 3.0.16 => 3.0.16 
      @tarojs/taro: 3.0.16 => 3.0.16 
      @tarojs/webpack-runner: 3.0.16 => 3.0.16 
      babel-preset-taro: 3.0.16 => 3.0.16 
      eslint-config-taro: 3.0.16 => 3.0.16 
      eslint-plugin-taro: 3.0.16 => 3.0.16 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
```

---
### 补充信息
微信小程序上显示正常。

Taro 2.x H5 版本可以通过全局样式类 taro-img ，解决 flex 布局图片显示异常：

.taro-img {
    width: auto;
    height: auto;
    max-width: 100%;
    max-height: 100%;
}

**Comment by ZakaryCode** [comment]
合理，将在下一个版本移除

> 也可以通过 taro-image-core 标签设置全局样式修复该问题
