### ISSUE TITLE
请教h5怎么做版本控制

### ISSUE THREAD

**Issue by blueskink** [NervJS/taro#815]
请教h5怎么做版本控制。

**Comment by blueskink** [comment]
config配置：
`
h5: {
       webpackChain(chain, webpack) {
      chain.merge({
        output: {
          filename: '[name].[chunkhash].js',
          chunkFilename: chain.output.get('chunkFilename').replace('[name].js', '[name].[chunkhash].js')
        }
      })
    }
  }
`
js勉强解决了，静态资源改起来更麻烦，懒得搞了。 希望可以提供便捷的配置方法。

**Comment by luckyadam** [comment]
嗯嗯，目前只能通过 `webpackChain` 来进行修改~ 我们看看后续能不能提供别的配置来方便版本号修改吧

**Comment by blueskink** [comment]
> > 嗯嗯，目前只能通过 `webpackChain` 来进行修改~ 我们看看后续能不能提供别的配置来方便版本号修改吧
> 
> 大大，当前能否给个推荐的H5的 webpackChain 配置，给js、css和图片带上hash
> 
> webpack比较弱鸡，看文档配置了好久都还不行
@gmaso 勉强就搞了js和css的。
h5的配置里添加：
`

    webpackChain(chain, webpack) {
      if (process.env.NODE_ENV === 'production') {
        chain.plugin('miniCssExtractPlugin').tap(args => {
          args[0].filename = args[0].filename.replace('[name].css', '[name].[hash].css')
          args[0].chunkFilename = args[0].chunkFilename.replace('[id].css', '[id].[chunkhash].css')
          return args
        })
        chain.merge({
          output: {
            filename: '[name].[hash].js',
            chunkFilename: chain.output.get('chunkFilename').replace('[name].js', '[name].[chunkhash].js')
          }
        })
      }
    }
`

**Comment by ybning** [comment]
>  嗯嗯，目前只能通过 webpackChain 来进行修改~ 我们看看后续能不能提供别的配置来方便版本号修改吧

期待中😄

**Comment by undoZen** [comment]
差不多半年了竟然还没官方支持这件事情。折腾了一下：
https://gist.github.com/undoZen/678f3068143daaa97ad56f3b71ed53e9
