### ISSUE TITLE
linaria 生成的标签  模板字符串使用props 无效

### ISSUE THREAD

**Issue by Big0range** [NervJS/taro#8152]
### 相关平台
H5

**浏览器版本: 84.0.4147.89**
**使用框架: React**

### 复现步骤
const Title = styled(Button)`
color: ${props => props.color};
`

### 期望结果
能够修改color

### 实际结果
实际编译成  color: var(--t18dh6sw-0);

### 环境信息
```


  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\asd\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Users\asd\AppData\Roaming\npm\npm.CMD
```

---
### 补充信息
啊

**Comment by fred8617** [comment]
加油大佬们，解决好Q一下

**Comment by Chen-jj** [comment]
@lzhlo `config/index.js` 配置中，`h5.webpackChain` 也需要注入 `linariaLoader `。

文档中的配置只配置了 `mini.webpackChain`，所以只有小程序生效，我们改一下文档。

```js
config = {
  // ...
  h5: {
    webpackChain(chain, webpack) {
      // linaria/loader 选项详见 https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack
      chain.module
        .rule('script')
        .use('linariaLoader')
        .loader('linaria/loader')
        .options({
          sourceMap: process.env.NODE_ENV !== 'production',
        })
    }
  }
}
```

**Comment by lzhlo** [comment]
> `config/index.js` 配置中，`h5.webpackChain` 也需要注入 `linariaLoader `。
> 
> 文档中的配置只配置了 `mini.webpackChain`，所以只有小程序生效，我们改一下文档。
> 
> ```js
> config = {
>   // ...
>   h5: {
>     webpackChain(chain, webpack) {
>       // linaria/loader 选项详见 https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack
>       chain.module
>         .rule('script')
>         .use('linariaLoader')
>         .loader('linaria/loader')
>         .options({
>           sourceMap: process.env.NODE_ENV !== 'production',
>         })
>     }
>   }
> }
> ```

已配置  但是h5并未生效

**Comment by Chen-jj** [comment]
@lzhlo 升级到最新版再试试咯，我这边 ok

![image](https://user-images.githubusercontent.com/11807297/110889805-ceb81380-8329-11eb-90d1-fdfb1a43eaae.png)
