### ISSUE TITLE
taro微信小程序可以重写component生命周期什么的吗   需要做一个全局埋点

### ISSUE THREAD

**Issue by betterMIsWu** [NervJS/taro#8154]
### 这个特性解决了什么问题？
微信小程序全局埋点

### 这个 API 长什么样？
rewriteComponent

**Comment by Chen-jj** [comment]
使用基类来实现吧。

**Comment by betterMIsWu** [comment]
> 使用基类来实现吧。

能具体点吗？

**Comment by Chen-jj** [comment]
继承、自定义 hooks 都能实现，自己把握咯。

**Comment by chioio** [comment]
因重写原生 Component 无效，采取重写 TaroNode addEventListener 
 方式：https://github.com/NervJS/taro/issues/12287#issuecomment-2322811833
