### ISSUE TITLE
跟 RN 的使用习惯差太多，不得不吐槽

### ISSUE THREAD

**Issue by DingSoung** [NervJS/taro#8157]
### 这个特性解决了什么问题？
降低学习和开发成本，平滑从RN迁移到Taro

### 这个 API 长什么样？
去掉 xxx.config.js 配置导航栏，使用 container 形式自定义导航

去掉独立的样式配置文件，支持类似 StyleSheet 的形式配置样式

去掉 index.html

目标是 每个组建只需要一个 js 文件即可

**Comment by yz1311** [comment]
我也是从RN转过来的，taro本是web端的开发模式，RN的那种模式限制才是最多，习惯就好了

**Comment by DingSoung** [comment]
> 我也是从RN转过来的，taro本是web端的开发模式，RN的那种模式限制才是最多，习惯就好了

强迫症晚期，习惯不了，转了 remax,  虽然也不怎么友好，但是坑稍微少点儿

**Comment by shinken008** [comment]
毕竟 taro 是要适配多端，如果以rn的写法是不好做到适配其他端，remax 支持 rn？

**Comment by Pines-Cheng** [comment]
感谢吐槽，如果只需要开发 RN 端，而没有多端适配的需求，是不建议直接使用 Taro RN 端的。

Taro 还是以小程序多端适配为主，因此在API及样式等遵循微信小程序的 API，和纯 RN 相比还是有区别的。
