### ISSUE TITLE
【Taro 3.0.17】页面在onShow的时候无法触发componentDidShow生命周期

### ISSUE THREAD

**Issue by iShuhao12138** [NervJS/taro#8162]
### 相关平台
微信小程序

### 复现仓库
[https://git.undefined.com/](https://git.undefined.com/)
**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
第一次进入，componentDidShow能触发，但是切换到其他页面再返回到当前页面，componentDidShow无法触发。

### 期望结果
切换回当前页面展示时，componentDidShow能正确触发

### 实际结果
切换回当前页面展示时，componentDidShow不能正确触发

### 环境信息
```
Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - D:\basic\nodejs\node.EXE
      Yarn: E:\MiniProgram\Taro3\taro-next>"node"  "C:\Users\shuhao\AppData\Roaming\npm\\node_modules\yarn\bin\yarn.js" -v
1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - D:\basic\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
复现不了，升级到最新版后再试试
