### ISSUE TITLE
vendors.js很大，有很多重复的bn.js

### ISSUE THREAD

**Issue by gsbybb** [NervJS/taro#8169]
### 这个特性解决了什么问题？
3.0.15版本下，development模式，微信小程序打包就已经超出预览限制了。vendors.js下面有很多bn.js的引用
![image](https://user-images.githubusercontent.com/13886444/100722239-5b823580-33fb-11eb-8002-ab953e3d4e2e.png)

### 这个 API 长什么样？
优化一下打包体积

**Comment by digiaries** [comment]
你是不是用了 md5 这个包或者类似能在服务端使用的包？里面有兼容 nodeJs 的写法，会导致打包的时候把这些东西打进来。

**Comment by gsbybb** [comment]
@digiaries  但是看依赖关系好像是wepack的依赖。例如：webpack->node-libs-browser->crypto-browserify... ->bn.js。主要是引用了多个bn.js

**Comment by digiaries** [comment]
建议你在工程项目里搜索一下有没有类似 require("crypto") 或者 crypto.createHash 看看。

**Comment by lupingW** [comment]
> 建议你在工程项目里搜索一下有没有类似 require("crypto") 或者 crypto.createHash 看看。

import 'crypto-js/sha1';
import 'crypto-js/enc-utf8';
import 'crypto-js/tripledes';
import * as CryptoJS from 'crypto-js/core';

只引用了这些 包还是很大 是我引得不对吗

**Comment by digiaries** [comment]
> crypto-js

这个模块可能命中了这个地方
 [crypto = require('crypto');](https://github.com/brix/crypto-js/blob/develop/src/core.js#L38)
最终导致一些包被意外打包进去

**Comment by gsbybb** [comment]
> > 建议你在工程项目里搜索一下有没有类似 require("crypto") 或者 crypto.createHash 看看。
> 
> import 'crypto-js/sha1';
> import 'crypto-js/enc-utf8';
> import 'crypto-js/tripledes';
> import * as CryptoJS from 'crypto-js/core';
> 
> 只引用了这些 包还是很大 是我引得不对吗
https://github.com/brix/crypto-js/issues/276

**Comment by cherish1260** [comment]
没有使用crypto为什么也会有这么多的bn.js

**Comment by zuimeiaj** [comment]
@lupingW  谢谢你啊，我干掉这个库之后，少了700kb。。。。。

**Comment by lupingW** [comment]
> @lupingW 谢谢你啊，我干掉这个库之后，少了700kb。。。。。

降低包版本就可以
