### ISSUE TITLE
taro和原生小程序代码混用,打包不同平台模版文件会被编译

### ISSUE THREAD

**Issue by z609373067** [NervJS/taro#8181]
### 这个特性解决了什么问题？
背景：taro和微信原生小程序混用
问题：在打包成字节小程序时，wxml文件会被编译成taro的嵌套模版

### 这个 API 长什么样？
预期：不被编译，或者能够开发者能够自定义控制

**Comment by Chen-jj** [comment]
页面配置中，`usingComponents` 字段写个判断，按环境区分组件引用。
