### ISSUE TITLE
taro3 this指向似乎和react不同

### ISSUE THREAD

**Issue by gjc9620** [NervJS/taro#8183]
### 这个特性解决了什么问题？
讨论

```
taro3 
class A  {
  c(){
    this //View node?
  },
  render(){
    return (
      <View onClick={this.c}>
    )
  }
}
```
请问为什么这里的this是 View 看起来和react不一样

也许是this应该是A比较合理吗? 和react一致

**Comment by jenerse** [comment]
你需要bind(this)才会指向A。

**Comment by gjc9620** [comment]
> 你需要bind(this)才会指向A。或者 onClick={() => this.c()}

解决这个问题非常简单 
其实我想了解为什么这样设计 以及能不能判断内置组建的时候 把this改过去
毕竟react 在div的onclick this不会是 div

**Comment by Chen-jj** [comment]
要指向 A 就需要 bind，不 bind 时指向什么不太重要吧。

**Comment by gjc9620** [comment]
> 要指向 A 就需要 bind，不 bind 时指向什么不太重要吧。

为什么不bind的时候 指向view呢?
