### ISSUE TITLE
taro-component下的所有组件都会打进vendor

### ISSUE THREAD

**Issue by yohnz** [NervJS/taro#8188]
### 这个特性解决了什么问题？
业务中是使用的组件只有最基本的那个4，5个，但是taro-component下的所有组件都会打进vendor，造成vendor中有很多无用的代码。

### 这个 API 长什么样？
可以按需打进vendor

**Comment by Chen-jj** [comment]
哪个端

**Comment by yohnz** [comment]
> 哪个端

h5

**Comment by Chen-jj** [comment]
@yohnz 不会吧，H5 端默认 webpack 配置没有配 splitChunks，不知道你的 `vendor` 是哪里来的。而且 components 的组件在 Stencil 框架里都是异步 import 的，所以会打成一个个单独的 chunks：

![image](https://user-images.githubusercontent.com/11807297/103498444-c7830e00-4e7f-11eb-9244-d42c8e3d16a5.png)
