### ISSUE TITLE
 Radio 组件onChange事件没有反应

### ISSUE THREAD

**Issue by wjjesse** [NervJS/taro#819]
**问题描述**
 Radio 组件onChange事件没有反应

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码
constructor(props) {
    super(props);
    this.state = {
      radioChecked: false,
    }
  }

onRadioChange = (checked) => {
    console.log('修改了Radio的选中状态', checked);
    this.setState({
      radioChecked: checked
    });
  };

render() {
    return (
      <View className='index'>
        <Radio className='warn-radio' color='#0072ff' name='rule' value='rule' checked={this.state.radioChecked} onChange={this.onRadioChange}>
          我已阅读并同意
        </Radio>
      </View>
    )
```

**期望行为**
onChange事件可正常触发

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [macOS High Sierra 10]
 - Taro 版本 [v1.0.7]
 - Node.js 版本 [v10]
 - 报错平台 [h5(未验证), weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
Radio 组件没有 onChange事件 参考 [https://developers.weixin.qq.com/miniprogram/dev/component/radio.html](https://developers.weixin.qq.com/miniprogram/dev/component/radio.html)

**Comment by wjjesse** [comment]
好的,我试试, 谢谢
