### ISSUE TITLE
API 中webpackChain option中没有publicpath 的选型

### ISSUE THREAD

**Issue by LiyumingBen** [NervJS/taro#8207]
### 这个特性解决了什么问题？
1静态资源 js、img、css等在不同cdn，thunk包中都会相对路径， 想将其在打包过程中修改为对应cdn路径。

### 这个 API 长什么样？
1. taro API  sassLoaderOption中支持publicpath 的选型

**Comment by Chen-jj** [comment]
`sassLoaderOption` 是 sass-loader 的配置，你想要的是 webpack 配置的 output.publicPath 吧
