### ISSUE TITLE
新建的taro3.0的项目 配置了组件和页面 但是提示渲染失败？

### ISSUE THREAD

**Issue by yuxilins** [NervJS/taro#8208]
![image](https://user-images.githubusercontent.com/44393243/101246301-67e4f600-374d-11eb-9dca-faf627abd5c0.png)
![image](https://user-images.githubusercontent.com/44393243/101246312-78956c00-374d-11eb-8ca4-cca09b445626.png)
![image](https://user-images.githubusercontent.com/44393243/101246322-84812e00-374d-11eb-8093-5a7443e7834e.png)
![image](https://user-images.githubusercontent.com/44393243/101246325-8b0fa580-374d-11eb-8128-aeb558db0b91.png)

**Comment by Chen-jj** [comment]
你使用了 h5 的标签，要使用小程序规范的组件，如 View。
