### ISSUE TITLE
在自定义平台插件下 webpackConfig中的runtimePath 会解析错误 导致无法加载扩展的runtime文件

### ISSUE THREAD

**Issue by leo-ran** [NervJS/taro#8209]
### 相关平台
微信小程序

**小程序基础库: 2.4.0**
**使用框架: React**

### 复现步骤
添加一个自定义平台插件
在@tarojs/mini-runner 包的dist/index.js  40行打印webpackConfig.entry.runtime  就能发现问题
另外 无论在entry里添加多少入口文件 都不会被打包
这样会导致扩展的平台插件runtime无法被编译出
目前使用官方推荐的企业微信插件包就出现了这个问题

### 期望结果
在webpackConfig.entry中添加的入口文件能被编译 

### 实际结果
webpackConfig.entry.runtime  被@tarojs/mini-runner /dist/webpack/webpack.chain.js 格式化是出现格式问题

在webpackConfig中添加的entry文件不能被编译

### 环境信息
```
Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.17.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
感觉是在@tarojs/mini-runner 在编译的时候 过滤掉了entry的其他入口文件 只保留了webpackConfig.entry.app
webpackConfig.entry.runtime在@tarojs/mini-runner /dist/webpack/webpack.chain.js 格式化的时候就出现了错误

**Comment by leo-ran** [comment]
我现在的解决方案只能把runtime手动在应用的入口文件顶部导入
![屏幕截图 2020-12-06 223912](https://user-images.githubusercontent.com/64803847/101283249-2e2af280-3814-11eb-8733-eed651a9fd2b.png)
![屏幕截图 2020-12-06 223951](https://user-images.githubusercontent.com/64803847/101283257-35ea9700-3814-11eb-829b-af99dfd69d66.png)

**Comment by Chen-jj** [comment]
@leo-ran

老哥你的 CLI 版本是不是不对，要用 3.1 beta 版本: `3.1.0-beta.4`。

`webpackConfig.entry.runtime` 是什么？

增加 entry 的操作也是不能理解，app 作为 entry 就可以了。

如果还有问题，可以再详细描述一下，最好有 demo。

**Comment by Chen-jj** [comment]
企业微信插件运作正常，复现不了，先关闭了。
