### ISSUE TITLE
componentWillReceiveProps 不能触发

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#821]
组件里的 componentWillReceiveProps 不能触发，reducer 已经 改变值了！
![image](https://user-images.githubusercontent.com/43346131/46843428-4ace6a00-ce05-11e8-98b4-a34c3156f151.png)

**Comment by Chen-jj** [comment]
麻烦按照 issue 模板修改一下描述，最好能提供可以稳定复现的代码片段。
