### ISSUE TITLE
taro3扩展编译平台 -> 模版，文档描述看起来是可以自定义一些功能，求个DEMO案例

### ISSUE THREAD

**Issue by xiaoice** [NervJS/taro#8212]
### 这个特性解决了什么问题？
https://taro-docs.jd.com/taro/docs/3.2.0-canary.1/platform-plugin-template
需要DEMO对文档的补充，目前不知道如何新建，模版放哪里，应该怎么运行起来

### 这个 API 长什么样？
期待一个能运行的DEMO例子，来对taro3模版功能的补充，尝试解决一些性能问题，感谢

**Comment by Chen-jj** [comment]
3.1 里对小程序平台的支持，全部都是使用插件实现，其中部分小程序对模板有特定要求，就会需要修改原问题中的模板。
例子：
taro 仓库里 chore/mini-program 分支中，plugin-platform 开头的包
Nervjs 组织里，plugin-platform 开头的包
