### ISSUE TITLE
是否支持全局生命周期钩子

### ISSUE THREAD

**Issue by bibidu** [NervJS/taro#8213]
### 这个特性解决了什么问题？
希望可以配置onLoad、onReady生命周期钩子，并在所有页面执行对应生命周期时，执行公共逻辑

### 这个 API 长什么样？
Taro.lifetimes.intercetpor('onLoad', (pageInstance) => {

})

**Comment by bibidu** [comment]
由于 document.body 拿到的始终是第一个页面的实例，即使跳转到另一个页面，通过document.body.appendChild仍然添加到上一个页面，所以希望可以通过配置生命周期钩子，将每个页面的实例拿到，然后再添加节点到当前页面实例

```javascript
// pageA
import XUI from 'xui'

export default {
  methods: {
    showToast() {
      XUI.$toast('pageA')
    }
  }
}

// pageB (从pageA跳转而来)
import XUI from 'xui'

export default {
  methods: {
    showToast() {
      // 此时动态创建的元素被添加到了 pageA，期望添加到当前页面
      XUI.$toast('pageB')
    }
  }
}```

**Comment by Chen-jj** [comment]
onLaunch、onLoad、onReady 生命周期都是支持的，直接用就行。

**Comment by tranter1991** [comment]
@Chen-jj 可以支持下useLaunch, useLoad hooks么, 这样就可以在其他hooks里面里面用

**Comment by tranter1991** [comment]
或者类似useAppEvent('onLoad', cb) 这样

**Comment by yangger6** [comment]
看看这个能满足需求不 [mini-lifecycle-interceptor](https://github.com/yangger6/mini-lifecycle-interceptor)

**Comment by Chen-jj** [comment]
Taro v3.5 开始支持 `useLaunch` `useLoad` `useUnload`

**Comment by AEPKILL** [comment]
可以先这样写:

`tsx
const App = forwardRef((props, ref: any) => {
  useImperativeHandle(
    ref,
    () => {
      return {
        onLaunch() {
          console.log("2333333");
        },
      };
    },
    []
  );

  return props.children
});

export default App;
`

我看 Taro 源码就是拿 Ref 然后调用 Ref 上的 onLaunch

**Comment by dzcpy** [comment]
useLaunch 不好用，写进首页不会执行
