### ISSUE TITLE
Taro3.0组件在h5环境下的View支持 viewProps，类Image组件的imgProps

### ISSUE THREAD

**Issue by heiazu** [NervJS/taro#8222]
### 这个特性解决了什么问题？
在使用Taro3.0组件的时候，希望能在web环境下能够给标签挂上 data-* 类似的属性

### 这个 API 长什么样？
https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/view/view.tsx
支持viewProps属性，类似Image组件的imgProps

**Comment by ZakaryCode** [comment]
duplicate #9798
fixed in v3.3.1
