### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#823]
![image](https://user-images.githubusercontent.com/3361732/46844655-a0594580-ce0a-11e8-917a-9f46927cf33b.png)

由于render中很多，想简单拆分下，报错：React is not defined，
如果这种写法不行，请问有其他写法吗？

**Comment by yuche** [comment]
你可以 render() 设置一个变量，然后在放到任何你想嵌入的地方。

```
render() {
  const element = <Content footer={<View />} />
  return <View>{element}</View>
}
```

**Comment by xiao0502** [comment]
> 你可以 render() 设置一个变量，然后在放到任何你想嵌入的地方。
> 
> ```
> render() {
>   const element = <Content />
>   return <View>{element}</View>
> }
> ```

这个Content是如何定义的呢

**Comment by JackPu** [comment]
@yuche 什么原因支持不了  `render` 拆成函数的形式？

**Comment by cuixi** [comment]
> @yuche 什么原因支持不了 `render` 拆成函数的形式？
同问？

**Comment by yuche** [comment]
> > @yuche 什么原因支持不了 `render` 拆成函数的形式？
> > 同问？

1.3 支持了

**Comment by wsz7777** [comment]
```
 transData = data => {
    const arr = data.map(v => ({
      title: v.createDate,
      content: [
        <View key={v.scheduleId}>
          <View className={S.title}>{v.projectScheduleTitle}</View>
          <View className={S.desc}>
            <RichTextShow domHtml={v.projectDesc} />
          </View>
          <View>
            {v.imgs.map(src => (
              <Image
                key={src.sort}
                src={src.imgAddress}
                className={S.contImage}
              />
            ))}
          </View>
        </View>
      ],
      icon: "check-circle"
    }));
    this.setState({ timeList: arr });
  };

  render() {
    return (
      <View className={S.timeLine}>
        <AtTimeline pending items={this.state.timeList} />
      </View>
    );
  }
```
这样写在小程序中报错

**Comment by yuche** [comment]
> ```js
>  transData = data => {
>     const arr = data.map(v => ({
>       title: v.createDate,
>       content: [
>         <View key={v.scheduleId}>
>           <View className={S.title}>{v.projectScheduleTitle}</View>
>           <View className={S.desc}>
>             <RichTextShow domHtml={v.projectDesc} />
>           </View>
>           <View>
>             {v.imgs.map(src => (
>               <Image
>                 key={src.sort}
>                 src={src.imgAddress}
>                 className={S.contImage}
>               />
>             ))}
>           </View>
>         </View>
>       ],
>       icon: "check-circle"
>     }));
>     this.setState({ timeList: arr });
>   };
> 
>   render() {
>     return (
>       <View className={S.timeLine}>
>         <AtTimeline pending items={this.state.timeList} />
>       </View>
>     );
>   }
> ```
> 
> 这样写在小程序中报错

JSX 在 Taro 里是不能当做数据来操作的

**Comment by wsz7777** [comment]
```js
 transData = data => {
    const arr = data.map(v => ({
      title: v.createDate,
      content: [
        <View key={v.scheduleId}>
            item xxxxxx
        </View>
      ],
      icon: "check-circle"
    }));
    this.setState({ timeList: arr });
  };

  render() {
    return (
      <View className={S.timeLine}>
        <AtTimeline pending items={this.state.timeList} />
      </View>
    );
  }
```
这样没问题

**Comment by kolf** [comment]
@wsz7777 同问，有解决方法了吗？

**Comment by crimson968** [comment]
同问
