### ISSUE TITLE
canvas  hook 写法 draw is not a function

### ISSUE THREAD

**Issue by Swordword** [NervJS/taro#8233]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Swordword/taro-issue](https://github.com/Swordword/taro-issue)
**小程序基础库: 2.12.2**
**使用框架: React**

### 复现步骤
handleDraw 方法 绘制图形成功，最后的 ctx.draw 方法出错，控制台报出 draw is not a function 

### 期望结果
ctx.draw 正常运行

### 实际结果
draw is not a function 

### 环境信息
```
👽 Taro v3.0.17


  Taro CLI 3.0.17 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.17 => 3.0.17 
      @tarojs/mini-runner: 3.0.17 => 3.0.17 
      @tarojs/react: 3.0.17 => 3.0.17 
      @tarojs/runtime: 3.0.17 => 3.0.17 
      @tarojs/taro: 3.0.17 => 3.0.17 
      @tarojs/webpack-runner: 3.0.17 => 3.0.17 
      babel-preset-taro: 3.0.17 => 3.0.17 
      eslint-config-taro: 3.0.17 => 3.0.17 
      react: ^16.10.0 => 16.14.0 
    npmGlobalPackages:
      typescript: 3.9.7
```

**Comment by luckyadam** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html
看一下不同 type 的 canvas 的具体用法

**Comment by Swordword** [comment]
是小程序的问题，文档没有更新。 当 canvas 设置 type='2d' 时，canvasToTempFilePath 不需要在 draw 的回调函数运行，参数由canvasId 改为 canvas 实例就行了
