### ISSUE TITLE
Vue3 使用 vant-weapp 微信小程序组件，@click 等事件无响应

### ISSUE THREAD

**Issue by Mikasa33** [NervJS/taro#8242]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: Vue 3**

### 复现步骤
例如 van-button 的 @click 事件无效

### 期望结果
@click 等事件可以正常执行

### 实际结果
全部组件的事件都无响应

### 环境信息
```
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.18 => 3.0.18 
      @tarojs/mini-runner: 3.0.18 => 3.0.18 
      @tarojs/runtime: 3.0.18 => 3.0.18 
      @tarojs/taro: 3.0.18 => 3.0.18 
      @tarojs/webpack-runner: 3.0.18 => 3.0.18 
      babel-preset-taro: 3.0.18 => 3.0.18 
      eslint-config-taro: 3.0.18 => 3.0.18 
```

**Comment by Mikasa33** [comment]
看了看源码，看到原本是 `onClick` ，然后尝试 `@onClick` 不对，又尝试 `@Click`，结果成功了，按理说应该转换为 `@click`

**Comment by luckyadam** [comment]
能否提供个例子看下

**Comment by Mikasa33** [comment]
@luckyadam 
demo在这里：https://github.com/Mikasa33/taro-vue3-weapp-demo
启动服务第一次进入，不加 `onClick` 点击事件 `@click` 就不生效，加上 `onClick` 就生效了
谢谢🙏

**Comment by chechengpeng** [comment]
我也遇到了，微微有点坑

**Comment by Mikasa33** [comment]
> 我也遇到了，微微有点坑

可以暂时这样解决

```html
<van-button @click="onClick" onClick="onClick">按钮</van-button>
```

**Comment by chechengpeng** [comment]
> > 我也遇到了，微微有点坑
> 
> 可以暂时这样解决
> 
> ```
> <van-button @click="onClick" onClick="onClick">按钮</van-button>
> ```

还会遇到组件里面的 click 事件不生效，用这种方式也不管用。我看只把click的首字母C大写就可以了。
> ```
> <van-button @Click="onClick">按钮</van-button>
> ```
