### ISSUE TITLE
taro3配置tabbar时h5端onPageScroll、onReachBottom方法失效

### ISSUE THREAD

**Issue by iamxiyang** [NervJS/taro#8258]
### 相关平台
H5

### 复现仓库
[https://github.com/iamxiyang/taro3-bug](https://github.com/iamxiyang/taro3-bug)
**浏览器版本: Chrome 87.0.4280.88**
**使用框架: React**

### 复现步骤
使用`taro init`创建项目：

? 请选择框架 React   
? 是否需要使用 TypeScript ？ Yes   
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass   
? 请选择模板源 Gitee（最快）   
✔ 拉取远程模板仓库成功！  
? 请选择模板 默认模板  

在默认存在的index页面中增加事件：
```ts
    onPageScroll() {
        console.log('onPageScroll');
    }

    onReachBottom() {
        console.log('onReachBottom');
    }
``` 
写一个高度足够的标签撑开，运行`dev:h5`，此时在浏览器中能够正常触发事件执行。

如果再新建一个页面，同时在`app.config.ts`中配置tabbar，重新访问网页tabbar显示出来了，但onPageScroll和onReachBottom事件不执行了

### 期望结果
onPageScroll和onReachBottom事件都能够正常执行

### 实际结果
配置tabbar时onPageScroll和onReachBottom事件不执行

### 环境信息
```
  Taro CLI 3.0.18 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.18 => 3.0.18 
      @tarojs/mini-runner: 3.0.18 => 3.0.18 
      @tarojs/react: 3.0.18 => 3.0.18 
      @tarojs/runtime: 3.0.18 => 3.0.18 
      @tarojs/taro: 3.0.18 => 3.0.18 
      @tarojs/webpack-runner: 3.0.18 => 3.0.18 
      babel-preset-taro: 3.0.18 => 3.0.18 
      eslint-config-taro: 3.0.18 => 3.0.18 
      react: ^16.10.0 => 16.14.0 
    npmGlobalPackages:
      typescript: 3.6.2

```

**Comment by iamxiyang** [comment]
什么时候能够被解决呢？

**Comment by ouzhou** [comment]
吐了 这么重要的功能居然没实现。。。 做业务最多的就是上拉加载和下拉刷新，还不如用uni

**Comment by iamxiyang** [comment]
> 吐了 这么重要的功能居然没实现。。。 做业务最多的就是上拉加载和下拉刷新，还不如用uni

经测试，**3.0.24** 已修复该问题
