### ISSUE TITLE
v2版本 @tarojs/componets 中的 scrollview 实现有问题。

### ISSUE THREAD

**Issue by Reamd7** [NervJS/taro#8264]
### 相关平台
H5

### 复现仓库
[https://github.com/Reamd7/taro-vant](https://github.com/Reamd7/taro-vant)
**浏览器版本: Microsoft Edge  87.0.664.60 ，安卓10最新QQ内置浏览器、安卓QQ浏览器、**
**使用框架: React**

### 复现步骤
https://github.com/Reamd7/taro-vant 项目中index-bar组件。

### 期望结果
1、 props.scrollIntoView 的错误
期望使用css动画队列实现，使得频繁修改scrollIntoView 时候不会因为scrollIntoView中使用smooth，导致大量的动画队列卡住，移动就回滚

2、props.scrollTop props.scrollLeft，这两个属性不应该时受控组件。

### 实际结果
1、props.scrollIntoView
频繁修改导致页面回滚
动画速度过慢
2、props.scrollTop props.scrollLeft
设定之后 实际的scrollTop 就不可以改变了

### 环境信息
```
� Taro v2.2.15


  Taro CLI 2.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Gemini\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
1、 props.scrollIntoView 的错误

function scrollIntoView (id) {
  document.querySelector(`#${id}`).scrollIntoView({
    behavior: 'smooth',
    block: 'center',
    inline: 'start'
  })
}

这样的实现是错误的，因为浏览器内置的smooth动画速度不可以控制，
所以在 componentWillReceiveProps 之后遇见新props.scrollIntoView就马上scrollIntoView(props.scrollIntoView)，会导致整个scrollview在动画状态下移动就回滚。

2、props.scrollTop props.scrollLeft 的实现问题，不能说错误，
在小程序端，任何内置组件的属性都不是实现成为受控组件的，都是可以响应外部修改，内部也可以修改

即应该props.scrollTop 修改时会响应更新，但是仍然可以 scroll

**Comment by luckyadam** [comment]
提个 pr？
