### ISSUE TITLE
开发小程序插件时不支持【获取小程序导出】功能

### ISSUE THREAD

**Issue by Ark-Chen** [NervJS/taro#8266]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
1.使用脚手架命令行搭建脚手架模板；
2.app.tsx文件夹内plugins增加export属性
"plugins": {
      "myPlugin": {
        "version": "dev",
        "provider": "XXXXX",
        "export": "" // 貌似不支持该属性值
      }
    }

### 期望结果
支持微信插件开发中的【获取小程序导出】功能
api地址：https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/development.html

### 实际结果
不能将类型“{ version: string; provider: string; export: string; }”分配给类型“{ version: string; provider: string; }”。
  对象文字可以只指定已知属性，并且“"export"”不在类型“{ version: string; provider: string; }”中。

### 环境信息
```
👽 Taro v2.2.13


  Taro CLI 2.2.13 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.2.13 => 2.2.13 
      @tarojs/components-qa: 2.2.13 => 2.2.13 
      @tarojs/mini-runner: 2.2.13 => 2.2.13 
      @tarojs/plugin-sass: ^2.2.10 => 2.2.10 
      @tarojs/plugin-stylus: 2.2.13 => 2.2.13 
      @tarojs/plugin-terser: 2.2.13 => 2.2.13 
      @tarojs/router: 2.2.13 => 2.2.13 
      @tarojs/taro: 2.2.13 => 2.2.13 
      @tarojs/taro-alipay: 2.2.13 => 2.2.13 
      @tarojs/taro-h5: 2.2.13 => 2.2.13 
      @tarojs/taro-qq: 2.2.13 => 2.2.13 
      @tarojs/taro-quickapp: 2.2.13 => 2.2.13 
      @tarojs/taro-swan: 2.2.13 => 2.2.13 
      @tarojs/taro-tt: 2.2.13 => 2.2.13 
      @tarojs/taro-weapp: 2.2.13 => 2.2.13 
      @tarojs/webpack-runner: 2.2.13 => 2.2.13 
      eslint-config-taro: 2.2.13 => 2.2.13 
      eslint-plugin-taro: 2.2.13 => 2.2.13 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
```

![image](https://user-images.githubusercontent.com/31213168/102188958-ecbfd480-3ef0-11eb-81b6-3c6d5d0a0acc.png)

**Comment by luckyadam** [comment]
可以忽略这个 eslint 提示，直接使用

**Comment by Ark-Chen** [comment]
@luckyadam taro mini有办法配置类似h5 staticDirectory这样的静态文件夹吗
