### ISSUE TITLE
video组件timeupdate回调无法触发

### ISSUE THREAD

**Issue by Bluebang** [NervJS/taro#8269]
### 相关平台
京东小程序

### 复现仓库
[https://github.com/Bluebang/demoTaro.git](https://github.com/Bluebang/demoTaro.git)
**小程序基础库: 无**
**使用框架: Vue 2**

### 复现步骤
运行观察打印的log，会发现无timeupdate回调。

### 期望结果
timeupdate触发回调

### 实际结果
无法触发

### 环境信息
```
Taro CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
模拟器正常，微信端真机正常，京东端真机ended、play可以正常触发

**Comment by Chen-jj** [comment]
可以先试试京东原生的 video 有没有问题

**Comment by Bluebang** [comment]
> 可以先试试京东原生的 video 有没有问题

原生没有问题，看了编译后的文件是绑定的一个叫“eh”的回调，没有绑定到正确的函数上。有办法临时处理不？急用

**Comment by Bluebang** [comment]
原生如此。
