### ISSUE TITLE
请问小程序中如何使用自定义导航?

### ISSUE THREAD

**Issue by Restry** [NervJS/taro#827]
左上角这样的自定义导航, 在小程序中如何实现, 有控件支持吗?

![2018-10-12 16 24 23](https://user-images.githubusercontent.com/10685800/46857339-4e7ce380-ce3b-11e8-9705-6f4478e18eb7.png)

**Comment by Herrengit** [comment]
这个可以在配置文件中 配置自定义导航

**Comment by Herrengit** [comment]
参考小程序官方文档
