### ISSUE TITLE
请问 Taro vue 小程序 自定义底部导航 怎么做啊？

### ISSUE THREAD

**Issue by BWchenxin** [NervJS/taro#8271]
### 这个特性解决了什么问题？
自定义小程序页面导航功能

### 这个 API 长什么样？
入口的app.js能够加入自定义组件（能够和路由页面一起显示，不会随着路由变化而消失），比如底部自定义导航组件

**Comment by Chen-jj** [comment]
能够和路由页面一起显示，不会随着路由变化而消失底部导航只能依靠小程序的 tabbar 配置实现，Taro 框架层是做不到的
