### ISSUE TITLE
无法使用支付宝原生提供的关注生活号组件life-follw组件

### ISSUE THREAD

**Issue by Andraw-lin** [NervJS/taro#8277]
### 这个特性解决了什么问题？
能支持原生提供的组件

### 这个 API 长什么样？
能支持原生提供的组件

**Comment by Chen-jj** [comment]
3.1beta可以

**Comment by Andraw-lin** [comment]
升级到3.1.0-beta.4后，报了个错：
Couldn't find any versions for "@tarojs/components" that matches "3.1.0-beta.4"

**Comment by Andraw-lin** [comment]
> 3.1beta可以

目前试用了3.1.0-beta.3版本，使用支付宝原生提供的关注生活号组件life-follw组件，Taro使用React.createElement进行渲染
![image](https://user-images.githubusercontent.com/15081323/102443536-f452bb00-4061-11eb-8e66-1e819eca45b2.png)
依然无法显示出life-follw组件。

**Comment by Chen-jj** [comment]
看来是最近新出的组件，下一个 beta 版本我们增加一下吧，急的话可以自己写个自定义插件，继承一下支付宝插件

**Comment by Andraw-lin** [comment]
> 看来是最近新出的组件，下一个 beta 版本我们增加一下吧，急的话可以自己写个自定义插件，继承一下支付宝插件

请问有具体的例子或者文档来提供如何继承支付宝插件编写吗？

**Comment by anuxs** [comment]
> > 看来是最近新出的组件，下一个 beta 版本我们增加一下吧，急的话可以自己写个自定义插件，继承一下支付宝插件
> 
> 请问有具体的例子或者文档来提供如何继承支付宝插件编写吗？

看 next版本的 taro 文档：
https://taro-docs.jd.com/taro/docs/next/platform-plugin

**Comment by Andraw-lin** [comment]
非常感激，继承支付宝插件来编写插件可解决当前问题
