### ISSUE TITLE
有多套组件库，使用方怎么判断使用哪一个？

### ISSUE THREAD

**Issue by fewoy** [NervJS/taro#8282]
### 这个特性解决了什么问题？
taro-components-qa、taro-components-rn、taro-components三端组件库之间的关系是什么，比如都有button。使用的时候怎么选择哪个组件库？哪个组件是跨端的？

### 这个 API 长什么样？
应该只存在一个组件库

![image](https://user-images.githubusercontent.com/14038970/102460448-f167c280-4081-11eb-9552-b57965697871.png)

**Comment by ZakaryCode** [comment]
不同平台使用的，开发者不需要考虑这三者的关系，统一引入 taro-components 即可。

> 在编译 rn 或者快应用时会自动替换其他两个组件库
