### ISSUE TITLE
关于ScrollView的scrollIntoView功能的一个问题

### ISSUE THREAD

**Issue by BaconZhang** [NervJS/taro#829]
我想要实现下面这样的一个列表，想实现滚动到指定标题的效果

![image](https://user-images.githubusercontent.com/13062998/46862420-5b073900-ce47-11e8-9564-84edfe6f2684.png)

关键代码如下

![image](https://user-images.githubusercontent.com/13062998/46862503-8f7af500-ce47-11e8-86ba-019fe9590b98.png)

在ListItem里根据item的类型判断渲染标题Title还是Record

![image](https://user-images.githubusercontent.com/13062998/46862557-b0434a80-ce47-11e8-8835-9419e076f556.png)

我为每个ListItem设置了id，如果使用scrollIntoView的值是渲染了Record的Listitem的id可以实现预期效果，能够滚动到指定位置，但是如果设置了渲染了Title的ListItem的id，则不能实现预期效果，列表根本不会滚动，但是state里的值确实已经改变了。
我看了源码里的taor-omponents下的代码也没有看到scrollIntoView相关的部分，所以想请教一下这样的列表滚动到指定的标题应该怎样实现

**Comment by jinjinjin0731** [comment]
嗯。。 H5 中 scrollIntoView 的功能还没有实现，这个尽快加上。 实现方式可以这样，显示拿到默认的滚动方向，然后计算出当前 id 的元素与该方向的原点(scrollLeft or scrollTop)的距离。然后设置一下。滚动动画效果可以用 requestAnimationFrame 实现

**Comment by jinjinjin0731** [comment]
小程序的吗， 参考一下官方文档？[https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html](https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html)，使用这个 scrollIntoView ， id 不可以数字开头哦

**Comment by jinjinjin0731** [comment]
如果可以的话，贴一下编译后的 小程序 wxml 文件看一下？

**Comment by BaconZhang** [comment]
1、ScrollView

 <scroll-view class="scroll-list" scroll-y="{{true}}" scroll-with-animation="{{true}}"
        lower-threshold="100" upper-threshold="50" bindscrolltoupper="loadPrevPage"
        bindscrolltolower="loadNextPage" data-e-loadPrevPage-so="this" data-e-loadNextPage-so="this">
            <list-item item="{{i.$$original}}" __triggerObserer="{{ _triggerObserer }}"
            count="{{count}}" id="{{i.$loopState__temp2}}" wx:key="{{i.$loopState__temp4}}"
            bindonclick="onToAlarmDetail" wx:for="{{loopArray0}}" wx:for-item="i" __fn_onClick="{{true}}"
            data-e-onToAlarmDetail-so="this"></list-item>
        </scroll-view>

2、LIstItem

<block>
    <view>
        <block>
            <block wx:if="{{item.type === '_TITLE'}}">
                <block wx:if="{{item.show}}">
                    <title title="{{anonymousState__temp}}" __triggerObserer="{{ _triggerObserer }}"></title>
                </block>
            </block>
            <block wx:else>
                <record record="{{item}}" __triggerObserer="{{ _triggerObserer }}" bindonclick="onClick"
                __fn_onClick="{{true}}" data-e-onClick-so="this" data-e-onClick-a-a="{{item}}"></record>
            </block>
        </block>
    </view>
</block>

我的id都不是以数字开头的，都是alarm-xxx的格式

**Comment by jinjinjin0731** [comment]
LIstItem 中的 Title 组件有个 item.show 的判断。  这时候状态变更之后，有没有对 scrollIntoView 重新进行一个 setState。 如果有的话，那么你猜测是对的，如果有两种类型，可能会导致scrollIntoView失效。 如果没有的话，试一下更新下？ (ps: 编译后的代码为啥没有看到有 scroll-into-view 这个属性。。)

**Comment by BaconZhang** [comment]
我的问题基本解决了，非常感谢（没属性是因为编这个代码版本的时候没加，单纯为了看下wxml）
