### ISSUE TITLE
Android6及以下版本 Object.assign is not a function

### ISSUE THREAD

**Issue by guoseven** [NervJS/taro#8301]
### 相关平台
H5

**浏览器版本: Android API23**
**使用框架: React**

### 复现步骤
run run build:h5

### 期望结果
页面显示正常

### 实际结果
白屏

### 环境信息
```
  Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.19 => 3.0.19 
      @tarojs/mini-runner: 3.0.19 => 3.0.19 
      @tarojs/react: 3.0.19 => 3.0.19 
      @tarojs/runtime: 3.0.19 => 3.0.19 
      @tarojs/taro: 3.0.19 => 3.0.19 
      @tarojs/webpack-runner: 3.0.19 => 3.0.19 
      babel-preset-taro: 3.0.19 => 3.0.19 
      eslint-config-taro: 3.0.19 => 3.0.19 
      react: ^17.0.1 => 17.0.1 

```

---
### 补充信息
项目构建完成，搭建简单的页面
I/chromium: [INFO:CONSOLE(2)] "Uncaught TypeError: Object.assign is not a function", source:

**Comment by Chen-jj** [comment]
@guoseven 使用 corejs3。

Taro 的 `babel-preset-taro` 对 `@babel/preset-env` 的参数做了一下封装，你需要做的操作是：

1. babel.config.js 配置 useBuildIns

```js
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: false,
      useBuiltIns: 'usage'
    }]
  ]
}
```

2. 安装：`npm install core-js@3 --save`、`npm install --save @babel/runtime-corejs3`

结果：

![image](https://user-images.githubusercontent.com/11807297/102707568-39cbee00-42d7-11eb-8f96-0f37025953a6.png)


![image](https://user-images.githubusercontent.com/11807297/102707564-35073a00-42d7-11eb-9e31-2fd900dd7049.png)

可以自行阅读 Babel 的 `preset-env` 和 `transform-runtime` 文档深究。
