### ISSUE TITLE
按官方文档的react模板搭建小程序，启动就白屏

### ISSUE THREAD

**Issue by anyexinglu** [NervJS/taro#8302]
### 相关平台
微信小程序

**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
1、初始化
 taro init myTaroApp
👽 Taro v3.0.11

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！ 测试 Taro
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 默认模板

2、启动
yarn dev:wapp

### 期望结果
小程序打开正常展示

### 实际结果

![image](https://user-images.githubusercontent.com/8243326/102679586-a2d63780-41eb-11eb-8076-54f153822c47.png)

WXMLRT_$gwx:./base.wxml:template:45:16: Template `tmpl_0_pure-view` not found.
_wp @ appservice?t=1608346379708:51
_w @ appservice?t=1608346379708:1053
d_.<computed>.tmpl_0_container @ appservice?t=1608346379708:2164
xC @ appservice?t=1608346379708:1944
wfor @ appservice?t=1608346379708:539
_2z @ appservice?t=1608346379708:743
d_.<computed>.taro_tmpl @ appservice?t=1608346379708:1952
m2 @ appservice?t=1608346379708:3942
(anonymous) @ appservice?t=1608346379708:3957
A @ VM59 WAService.js:2
value @ VM59 WAService.js:2
value @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
r.doUpdates @ VM59 WAService.js:2
N.setData @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
(anonymous) @ root.ts:88
C @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
setTimeout (async)
setTimeout @ VM59 WAService.js:2
performUpdate @ root.ts:47
(anonymous) @ common.ts:126
Rc @ react-reconciler.production.min.js:41
Qc @ react-reconciler.production.min.js:41
jg @ react-reconciler.production.min.js:152
push../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ scheduler.production.min.js:18
hc @ react-reconciler.production.min.js:29
ag @ react-reconciler.production.min.js:148
Of @ react-reconciler.production.min.js:132
(anonymous) @ react-reconciler.production.min.js:30
push../node_modules/scheduler/cjs/scheduler.production.min.js.exports.unstable_runWithPriority @ scheduler.production.min.js:18
hc @ react-reconciler.production.min.js:29
kc @ react-reconciler.production.min.js:30
F @ react-reconciler.production.min.js:29
Wc @ react-reconciler.production.min.js:123
enqueueForceUpdate @ react-reconciler.production.min.js:44
push../node_modules/react/cjs/react.production.min.js.F.forceUpdate @ react.production.min.js:12
mount @ react.ts:165
mount @ react.ts:207
mount @ common.ts:119
onLoad @ common.ts:133
(anonymous) @ VM59 WAService.js:2
c.__callPageLifeTime__ @ VM59 WAService.js:2
Ge @ VM59 WAService.js:2
Te @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
i.emit @ VM59 WAService.js:2
emit @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
i.emit @ VM59 WAService.js:2
emit @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
(anonymous) @ VM59 WAService.js:2
c @ VM57 asdebug.js:1
l @ VM57 asdebug.js:1
(anonymous) @ VM57 asdebug.js:1
f @ VM57 asdebug.js:1
p @ VM57 asdebug.js:1
(anonymous) @ VM57 asdebug.js:1
_ws.onmessage @ VM57 asdebug.js:1
Show 32 more frames
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_pure-view` not found.
  43 | 
  44 | <template name="tmpl_0_container">
> 45 |   <template is="{{xs.a(0, i.nn, l)}}" data="{{i:i,cid:0,l:xs.f(l,i.nn)}}" />
     |                ^
  46 | </template>
  47 | 
  48 | <template name="tmpl_1_view">

### 环境信息
```
✗ taro info 
👽 Taro v3.0.11


  Taro CLI 3.0.11 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.11 => 3.0.11 
      @tarojs/mini-runner: 3.0.11 => 3.0.11 
      @tarojs/react: 3.0.11 => 3.0.11 
      @tarojs/runtime: 3.0.11 => 3.0.11 
      @tarojs/taro: 3.0.11 => 3.0.11 
      @tarojs/webpack-runner: 3.0.11 => 3.0.11 
      babel-preset-taro: 3.0.11 => 3.0.11 
      eslint-config-taro: 3.0.11 => 3.0.11 
      react: ^16.10.0 => 16.14.0 
```

**Comment by Chen-jj** [comment]
检查一下 CLI、项目依赖是否版本都一致，pure-view 这个东西 3.0.19 才有

**Comment by anyexinglu** [comment]
已通过升级到最新cli解决：yarn global add @tarojs/cli ，现在👽 Taro v3.0.19
