### ISSUE TITLE
ios expo client 无法loading app

### ISSUE THREAD

**Issue by lvhuayu** [NervJS/taro#831]
想在真机测试，用iphone扫描运行npm run dev:rn 命令后生成的二维码？一直是无法loading, 还有为什么没有tunnel tool的url呢？

**Comment by Pines-Cheng** [comment]
如果是一直阻塞在 `Building JavaScript bundle... 100%`，可以参考一下这个issue：https://github.com/react-community/create-react-native-app/issues/392
