### ISSUE TITLE
setState后某些属性在Render中没有产生更新

### ISSUE THREAD

**Issue by canaanjin** [NervJS/taro#832]
**问题描述**
[问题描述：]
`CiverView`点击修改`state`中的值
在页面中没有产生更新

**复现步骤**
[复现问题的步骤]
1. 
 `CoverView`点击
 ```
          <CoverView
            id="coverViewNow"
            onClick={this.changeState}
            className={this.state.coverViewNowClass}
          >
            现在
          </CoverView>
          <CoverView
            id="coverViewMake"
            onClick={this.changeState}
            className={this.state.coverViewMakClass}
          >
            预约
          </CoverView>
```
2. 处理`CoverView`点击事件
state
```
state = {
    // 0现在
    // 1预约
    state: null,
    coverViewNowClass: "",
    coverViewMakClass: ""
  }
```
事件
```
  changeState() {
    const stateCode =
      this.state.state === null || this.state.state === 1 ? 0 : 1;

    const state = {
      coverViewNowClass: "cover-view-now",
      coverViewMakClass: "cover-view-make",
      state: stateCode
    };
    if (stateCode === 0) {
      state.coverViewMakClass += " list-item-disable";
    } else {
      state.coverViewNowClass += " list-item-disable";
    }
    this.setState(state);
  }
```
3. `render`显示`state`属性
```
          <View>{this.state.coverViewMakClass}</View>
          <View>{this.state.state}</View>
```
4. `state`发生改变之后页面中的`state`属性没有发生改变

![ddd](https://user-images.githubusercontent.com/12317236/46900165-8aae5380-ced0-11e8-8c8f-f767cbdc3413.gif)

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Chen-jj** [comment]
可以更新 Taro 版本后再试试，当前稳定版本是 v1.0.7。
使用命令 Taro update self 更新 cli，然后使用 Taro update project 更新依赖。

**Comment by luckyadam** [comment]
你的版本比较旧了，可以升级到最新的 1.0.7 版本来进行尝试，有一些更新需要注意的事项

https://github.com/NervJS/taro/issues/389

**Comment by canaanjin** [comment]
@luckyadam @Chen-jj
我很抱歉在提issues的时候没有填写系统信息
**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.11.1]
 - 报错平台 [weapp]

![image](https://user-images.githubusercontent.com/12317236/46986000-b7a47580-d11f-11e8-836b-5da4267f867a.png)

**Comment by Chen-jj** [comment]
【state】在 Taro 里是关键词，换一个单词即可。

```jsx
state = {
    // state: null,
    _state: null
    coverViewNowClass: "",
    coverViewMakClass: ""
}
```
