### ISSUE TITLE
1.x向3.x迁移 按照迁移指南 编译报错

### ISSUE THREAD

**Issue by zbk1234** [NervJS/taro#8328]
### 相关平台
微信小程序

**小程序基础库: 2.4.4**
**使用框架: React**

### 复现步骤
按照官网迁移指南安装更新后 编译报错

### 期望结果
成功编译

### 实际结果
编译报错

### 环境信息
```
 Taro CLI 3.1.0-beta.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zbk1234** [comment]
<img width="958" alt="未命名1608521486" src="https://user-images.githubusercontent.com/21994178/102736817-c5e62000-4380-11eb-9927-ee87c80cc65c.png">

**Comment by zbk1234** [comment]
![Uploading 未命名1608521916.png…]()

**Comment by zbk1234** [comment]
<img width="457" alt="未命名1608521885" src="https://user-images.githubusercontent.com/21994178/102736951-207f7c00-4381-11eb-97b6-7687820e857d.png">

**Comment by zbk1234** [comment]
![Uploading 未命名1608521916.png…]()

**Comment by zbk1234** [comment]
![Uploading 未命名1608521925.png…]()

**Comment by zbk1234** [comment]
<img width="579" alt="未命名1608521916" src="https://user-images.githubusercontent.com/21994178/102737167-a69bc280-4381-11eb-974d-c827a1413432.png">

**Comment by zbk1234** [comment]
<img width="516" alt="未命名1608521925" src="https://user-images.githubusercontent.com/21994178/102737178-abf90d00-4381-11eb-8ef4-8982f565bc9a.png">

**Comment by Chen-jj** [comment]
开个新项目对比着看看吧，重点关注 node_modules/@tarojs 下的依赖是否都装上了

**Comment by zbk1234** [comment]
![image](https://user-images.githubusercontent.com/21994178/102744896-db197980-4395-11eb-91b6-0e3574eb26b5.png)
这些依赖都要安装吗

**Comment by zbk1234** [comment]
<img width="948" alt="未命名1608534649" src="https://user-images.githubusercontent.com/21994178/102749302-c1c8fb00-439e-11eb-90b2-a70190f857c6.png">
依赖都安装好了 现在还是报错

**Comment by Chen-jj** [comment]
开个新项目对比定位下吧，对着图片无法 debug

**Comment by zbk1234** [comment]
麻烦问一下这个大概是哪里的问题  是依赖的问题还是  业务代码的问题   每个页面必须要有一个*.config.js文件吗
