### ISSUE TITLE
小程序生产打包命令问题：taro build --type weapp

### ISSUE THREAD

**Issue by mingtianfu** [NervJS/taro#833]
打包小程序命令：taro build --type weapp，process.env.NODE_ENV 的值一直是 'development'
无法识别开发和生产

**Comment by dogbutcat** [comment]
你指的process.env.NODE_ENV是代码中的么 还请补充上相关代码辅助说明

**Comment by luckyadam** [comment]
我试了一下，是可以的，能不能提供一下相关代码~

**Comment by mingtianfu** [comment]
我把src拷到其他的目录下编译可以，在当前目录下就是不行，不知道是什么问题
目前解决办法：把src拷到其他正常的目录下

**Comment by luckyadam** [comment]
@mingtianfu 拷贝到其他目录下是指？

**Comment by luckyadam** [comment]
可能是之前版本的项目依赖存在问题
