### ISSUE TITLE
Taro3代码按Taro1/2方式编译

### ISSUE THREAD

**Issue by felemon** [NervJS/taro#8332]
### 这个特性解决了什么问题？
QQ小程序下，Taro3 长列表复杂节点，卡顿明显。分页下拉几次后，就会闪退，应该是state data体积过大造成(vnode节点信息，比纯data信息大很多，setData传递数据时间较长)。

项目升级Taro3尝试效果不理想，考虑Taro3源码是否能像Taro1/2编译成原生小程序组件，这样升级完的代码就可以直接用。

### 这个 API 长什么样？
Taro3源码结构是否能像Taro1/2编译成原生小程序组件？源码为Taro3 React方式，但仍提升运行时性能。

**Comment by Chen-jj** [comment]
试试 3.0.21 的 `CustomWrapper` 包裹更新卡顿的子树。

```js
<Page>
   ...
     <CustomWrapper>
        <HeavyList></HeavyList>
      </CustomWrapper>
</Page>
```

**Comment by felemon** [comment]
@Chen-jj 试了下，用CustomWrapper包裹后，变成了原生自定义组件，但仍然是通过vnode template模板递归解析的。本身AppData的数据体积并没有变小(taro3 appData体积是taro1的10倍多，小程序下渲染卡顿很明显，尤其是QQ小程序 Android平台，列表加载下一页时就闪退了)

```
JSON.stringify(appData).length
 // Taro3: 92089, vnode方式
 // Taro1: 8948，data方式
```

![image](https://user-images.githubusercontent.com/4068351/102759284-dca36b80-43ae-11eb-80f5-4c7b84147e9a.png)

**Comment by j78742** [comment]
你怎么解决这个问题哈，有实现按Taro1/2编译吗

**Comment by j78742** [comment]
> @Chen-jj 试了下，用CustomWrapper包裹后，变成了原生自定义组件，但仍然是通过vnode template模板递归解析的。本身AppData的数据体积并没有变小(taro3 appData体积是taro1的10倍多，小程序下渲染卡顿很明显，尤其是QQ小程序 Android平台，列表加载下一页时就闪退了)
> 
> ```
> JSON.stringify(appData).length
>  // Taro3: 92089, vnode方式
>  // Taro1: 8948，data方式
> ```
> 
> ![image](https://user-images.githubusercontent.com/4068351/102759284-dca36b80-43ae-11eb-80f5-4c7b84147e9a.png)

我编译完元素节点都不见了，真是奇怪，是不是百度也不支持哈

**Comment by Chen-jj** [comment]
Taro v3.6.23 开始支持半编译模式：https://docs.taro.zone/docs/optimized/#%E5%8D%8A%E7%BC%96%E8%AF%91%E6%A8%A1%E5%BC%8F--compilemode
