### ISSUE TITLE
请教下，有没有app.tsx是hooks mobx版本的项目案例

### ISSUE THREAD

**Issue by w602542704** [NervJS/taro#8334]
### 这个特性解决了什么问题？
摆脱class的组件残留

### 这个 API 长什么样？
完全是hooks版本

**Comment by Chen-jj** [comment]
手动改下吧，保证 app 入口文件渲染了 props.children 就行。

**Comment by w602542704** [comment]
> 手动改下吧，保证 app 入口文件渲染了 props.children 就行。

老哥请教下，我没有思路，怎么把store传入props.children参数，app.tsx都已经是函数式组件了，难道我要整一个路由模块么？

**Comment by ZakaryCode** [comment]
```ts
function App({ children }) {
  return <Provider store={store}>
    {children}
  </Provider>
}
