### ISSUE TITLE
从taro2升级到taro3后,在组件中Taro.getApp() 返回undefined

### ISSUE THREAD

**Issue by yclnycl** [NervJS/taro#8338]
### 相关平台
微信小程序

**小程序基础库: 2.11.0**
**使用框架: React**

### 复现步骤
因为是版本升级导致的,我不清楚如何搞一个复现仓库
npm run dev:weapp

### 期望结果
希望返回和taro2一样的结果

### 实际结果
undefined

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
确认一下 CLI 和依赖是否一致，是否按升级指南操作。`Taro.getApp` 只是直接调用 `getApp`，如果还有问题，可以断点进去看看
