### ISSUE TITLE
希望QQ小程序Button增加的属性和调起微信支付的功能可以在同一个版本中使用

### ISSUE THREAD

**Issue by JackyLeeCS** [NervJS/taro#8346]
### 这个特性解决了什么问题？
1. 3.0.18为QQ小程序的Button增加了缺失的属性，3.1.0-beta版本增加了QQ小程序调起微信支付的功能，但现在这两个功能没在一个版本中同时存在，无法同时使用，希望能合并
2. 3.0.18为QQ小程序增加了缺失的属性，但ts中未定义相关的属性，IDE中未有错误警告

### 这个 API 长什么样？
功能合并

**Comment by Chen-jj** [comment]
@JackyLeeCS  3.1.0-beta.4 已经加上 Button 缺失的属性了，类型下个 beta 小版本我们补一下。

**Comment by JackyLeeCS** [comment]
> @JackyLeeCS 3.1.0-beta.4 已经加上 Button 缺失的属性了，类型下个 beta 小版本我们补一下。

@Chen-jj  最新的3.2.6版本，第2个问题仍然存在，ts中未定义相关属性，IDE中有警告。"openId"，“groupId”均未添加。
