### ISSUE TITLE
Taro.reLaunch 跳转页面不会清空已打开的页面，只会清除上一个页面

### ISSUE THREAD

**Issue by wei-octopuscat** [NervJS/taro#8347]
### 相关平台
H5

### 复现仓库
[https://github.com](https://github.com)
**浏览器版本: Chrome 87**
**使用框架: Vue 3**

### 复现步骤
登录成功后进去个人中心页面，打开设置页退出登录，跳转到首页，点击跳转到个人中心页，页面还是存在，不会刷新提示登录

### 期望结果
1. 清除全部页面，点击跳转到个人中心页刷新页面，提示登录

### 实际结果
个人中心页未清除，已缓存，再次跳转不会刷新页面，要手动刷新才提示登录

### 环境信息
```
 Taro CLI 3.0.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.6.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - D:\Yarn\bin\yarn.CMD
      npm: 6.14.6 - D:\nodejs\npm.CMD
```

**Comment by YoursOwen** [comment]
同，官方能修复下这个问题吗

**Comment by Celeste72** [comment]
3.0.24 版本。遇到同样的问题场景

**Comment by SyMind** [comment]
确实，reLaunch 时应该将所有页面都卸载掉。
