### ISSUE TITLE
H5 input受控组件表现异常

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#8349]
### 相关平台
H5

**浏览器版本: Google Chrome 目前是最新版本 版本 87.0.4280.88 (正式版本) (64 位元)ta**
**使用框架: React**

### 复现步骤
为input添加 value值，通过onInput进行对该值处理改变，在页面输出时以已改变，但实际输入框中的值未有变化

### 期望结果
可以正常使用

### 实际结果
未能重新赋予value

### 环境信息
```
$ taro info
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD

```

**Comment by SyMind** [comment]
@Junzibuzhengyibuqi 最新的代码库，已经无法复现。
