### ISSUE TITLE
Taro.reLaunch  界面白屏。 报错 TypeError: Cannot read property 'store' of null    Taro3版本  nerv版本。

### ISSUE THREAD

**Issue by zhouyujuan** [NervJS/taro#8350]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: Nerv**

### 复现步骤
``Taro.reLaunch({url: ''})``

### 期望结果
正常的reLaunch

### 实际结果
白屏了

### 环境信息
```
Taro CLI 3.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.7 => 3.0.7
      @tarojs/components: 3.0.7 => 3.0.7
      @tarojs/mini-runner: 3.0.7 => 3.0.7
      @tarojs/runtime: 3.0.7 => 3.0.7
      @tarojs/taro: 3.0.7 => 3.0.7
      @tarojs/webpack-runner: 3.0.7 => 3.0.7
      babel-preset-taro: 3.0.7 => 3.0.7
      eslint-config-taro: 3.0.7 => 3.0.7
      nervjs: ^1.5.0 => 1.5.7
```

**Comment by luckyadam** [comment]
可以升级到 3.0.21 试试，应该修复了这个问题

**Comment by zhouyujuan** [comment]
升级之后还是报错
Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.21 => 3.0.21
      @tarojs/components: 3.0.21 => 3.0.21
      @tarojs/mini-runner: 3.0.21 => 3.0.21
      @tarojs/runtime: 3.0.21 => 3.0.21
      @tarojs/taro: 3.0.21 => 3.0.21
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
      nervjs: ^1.5.0 => 1.5.7


react.ts:46 TypeError: Cannot read property 'store' of null
    at Component.ConnectFunction (connectAdvanced.js:140)
    at Component.c.render (lifecycle.ts:105)
    at lifecycle.ts:157
    at errorCatcher (lifecycle.ts:32)
    at renderComponent (lifecycle.ts:156)
    at updateComponent (lifecycle.ts:270)
    at reRenderComponent (lifecycle.ts:214)
    at ComponentWrapper.update (full-component.ts:60)
    at patch (patch.ts:57)
    at updateComponent (lifecycle.ts:281)

**Comment by Shalhvi** [comment]
> 可以升级到 3.0.21 试试，应该修复了这个问题

setState 界面白屏。 报错 TypeError: Cannot read property 'store' of nul。升级3.0.21还是会

👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.21 => 3.0.21
      @tarojs/components: 3.0.21 => 3.0.21
      @tarojs/mini-runner: 3.0.21 => 3.0.21
      @tarojs/router: 3.0.21 => 3.0.21
      @tarojs/runtime: 3.0.21 => 3.0.21
      @tarojs/taro: 3.0.21 => 3.0.21
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
      eslint-plugin-taro: 3.0.21 => 3.0.21
      nervjs: ^1.5.7 => 1.5.7
