### ISSUE TITLE
taro   vue下有混用原生组件的支持吗？

### ISSUE THREAD

**Issue by qweasdzxcpkh** [NervJS/taro#8358]
### 这个特性解决了什么问题？
https://github.com/NervJS/taro-sample-weapp 中的示例是react的，由于taro3.0不能使用wxs优化setData频繁的问题，想考虑混用原生组件，但是前面的示例又是react的，在vue中标签中的属性、事件的别名跟小程序的有冲突，需要一个例子

### 这个 API 长什么样？
vue page:
```vue
<custom-wx-component />
```

wxml:
```wxml
<wxs name="my" src="./path/my.wxs" />
<view catchtouchmove="{{my.touchmove}}">
    whatever
</view>
```

**Comment by Chen-jj** [comment]
有 vue 分支：https://github.com/NervJS/taro-sample-weapp/tree/vue
