### ISSUE TITLE
Picker 组件 mode 为 region 报错

### ISSUE THREAD

**Issue by lifegit** [NervJS/taro#8359]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
import {Picker, View} from "@tarojs/components";

    <Picker mode='region'>
          <View className='picker'>
            测试
          </View>
        </Picker>

### 期望结果
正常

### 实际结果
[渲染层错误] TypeError: Cannot read property 'length' of null
    at i._getCurrentDataList (http://127.0.0.1:24247/__pageframe__/__dev__/WAWebview.js:2:1279547)
    at i._getCurrentData (http://127.0.0.1:24247/__pageframe__/__dev__/WAWebview.js:2:1279357)
    at http://127.0.0.1:24247/__pageframe__/__dev__/WAWebview.js:2:1276367
    at http://127.0.0.1:24247/__pageframe__/__dev__/jsdebug.js:1:20648
[渲染层错误] Uncaught

### 环境信息
```
  Taro CLI 3.1.0-beta.4 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.18 => 3.0.18 
      @tarojs/components: 3.0.18 => 3.0.18 
      @tarojs/mini-runner: 3.0.18 => 3.0.18 
      @tarojs/react: 3.0.18 => 3.0.18 
      @tarojs/runtime: 3.0.18 => 3.0.18 
      @tarojs/taro: 3.0.18 => 3.0.18 
      @tarojs/webpack-runner: 3.0.18 => 3.0.18 
      babel-preset-taro: 3.0.18 => 3.0.18 
      eslint-config-taro: ^3.0.18 => 3.0.18 
      eslint-plugin-taro: ^3.0.18 => 3.0.18 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3 

```

**Comment by lifegit** [comment]
复现仓库：https://github.com/lifegit/taro-test-picker-err.git

**Comment by Chen-jj** [comment]
@lifegit 没有复现，大概率是因为你 CLI 和依赖版本不一致导致的错误。

![image](https://user-images.githubusercontent.com/11807297/103611645-ab559e80-4f5d-11eb-89dd-48cf5d56e997.png)

![image](https://user-images.githubusercontent.com/11807297/103611663-b4467000-4f5d-11eb-9605-4be426b8cffc.png)

**Comment by dormonbear** [comment]
昨天也碰到了这个问题，尝试后发现需要设置value属性，并将value初始化就不会出现问题。
`<picker mode="region" v-on:change="handleRegionChange" :value="regionValue"></picker>`
