### ISSUE TITLE
在自定义组件中 ,修改 Taro组件的样式无效

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#836]
**问题描述**
在自定义组件中 ,修改 Taro中AtFloatLayout组件的样式无效,
在AtFloatLayout 中at-float-layout__container中的 min-height:600rpx;
不能充满全屏 ，我想 让其 撑满全屏，但是在 自定义组件的 样式文件中，加上 添加了如下代码，但是无效；
于是 我把下面的 scss 样式添加到了 自定义组件 所用在的 page.scss 中 就 OK了！

```js
.at-float-layout__container {
  min-height: 100% !important;
  .layout-header {
    display: none !important;
  }
  .layout-body {
    padding: 0 0 18px 0 !important;
  }
}

```

**Comment by luckyadam** [comment]
这个是由于小程序自身的限制，目前解决不了

**Comment by lawushanshan** [comment]
同样的问题，tks
