### ISSUE TITLE
LivePusher组件缺少bindaudiovolumenotify等部分属性

### ISSUE THREAD

**Issue by AdamFu** [NervJS/taro#8363]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
使用LivePusher组件

### 期望结果
小程序2.12.0基础库增加了live-pusher的几个新属性功能，但Taro内未支持

### 实际结果
类型“IntrinsicAttributes & LivePusherProps & { children?: ReactNode; }”上不存在属性“onAudioVolumeNotify”。

### 环境信息
```
  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
3.1.0-beta.5 + 开始支持
