### ISSUE TITLE
Taro编译百度小程序 Text标签内容丢失

### ISSUE THREAD

**Issue by j78742** [NervJS/taro#8367]
### 相关平台
百度小程序

### 复现仓库
[https://github.com/j78742/taro3.0.21-demo](https://github.com/j78742/taro3.0.21-demo)
**小程序基础库: 3.250.33**
**使用框架: React**

### 复现步骤
1、安装依赖
2、yarn dev:swan 运行代码编译百度小程序

### 期望结果
Text标签包裹元素正常显示

### 实际结果
Text标签元素内容不存在

### 环境信息
```
Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD

```

**Comment by SyMind** [comment]
@Chen-jj 这个 issue 也可以关闭了。

**Comment by Chen-jj** [comment]
@j78742 没有复现，可以升级到最新版本再试试～
