### ISSUE TITLE
请求适配API: getEnterOptionsSync

### ISSUE THREAD

**Issue by Hayato9203** [NervJS/taro#8371]
### 这个特性解决了什么问题？
获取本次小程序启动时的参数。

### 这个 API 长什么样？
[getEnterOptionsSync](https://developers.weixin.qq.com/miniprogram/dev/api/base/app/life-cycle/wx.getEnterOptionsSync.html)这个API与[getLaunchOptionsSync](https://developers.weixin.qq.com/miniprogram/dev/api/base/app/life-cycle/wx.getLaunchOptionsSync.html)类似，均为获取小程序启动时的参数。不过前者可以获得本次启动参数，这很有用。后者只有冷启动时参数才会改变，这样的旧参数可能不是我们想要的。

**Comment by nunuji123** [comment]
由于Taro么有这个方法 只能用wx.getEnterOptionsSync 自带的了

**Comment by Chen-jj** [comment]
3.1 已支持。
