### ISSUE TITLE
请填写准确的仓库地址

### ISSUE THREAD

**Issue by taoqf** [NervJS/taro#8375]
官网搞的issue真真蛋疼，直接在这里搞个模板不好吗？弄得我都发不出来，提示我重现链接不是准确的仓库地址，什么地址才是准确的仓库地址呢？
不是所有看上去高大上的新奇的东西就是好的

**Comment by taoqf** [comment]
真是日了狗了。高大上的东西真多。是为了各位老大节省时间吗？

**Comment by honlyHuang** [comment]
你填的重现链接是啥？我试试看的

**Comment by taoqf** [comment]
不用试了，不用为了解决问题而解决问题。我真正的意图是说，搞的这个提问issue的方式浪费你们的精力且实际意义不大。
