### ISSUE TITLE
外部样式类：子组件无法接收到父组件的class

### ISSUE THREAD

**Issue by dezio31** [NervJS/taro#8376]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
父组件：
<Customer my-class='mall_customer' />
子组件：
static externalClasses = ['my-class']
render(){
<View className='my-class' />
}

### 期望结果
正常使用外部样式类

### 实际结果
无法使用外部样式类

### 环境信息
```
  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD

```

**Comment by dezio31** [comment]
父组件：
<Customer my-class='mall_customer' />
子组件：
static externalClasses = ['my-class']
render(){
<View className={styles.customer} />
}

**Comment by dezio31** [comment]
父组件：
`<Customer my-class='mall_customer' />`
子组件：
```
static externalClasses = ['my-class']
render(){

        <View className={styles.customer} />
}
```

**Comment by Chen-jj** [comment]
@dezio31 不需要使用这个东西。Taro 3 中 React 组件不是对应着一个个的小程序自定义组件，组件的样式都会被打包到页面的 wxss 上。
