### ISSUE TITLE
Input 组件源码中 maxLength 属性 "L" 为小写，导致 maxLength 无效

### ISSUE THREAD

**Issue by nanxiaobei** [NervJS/taro#8381]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
使用 Input 组件 maxLength 属性

### 期望结果
maxLength（L 大写）有效

### 实际结果
无效，maxlength（L 小写）才行

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.0.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.21 => 3.0.21 
      @tarojs/mini-runner: 3.0.21 => 3.0.21 
      @tarojs/react: 3.0.21 => 3.0.21 
      @tarojs/runtime: 3.0.21 => 3.0.21 
      @tarojs/taro: 3.0.21 => 3.0.21 
      @tarojs/webpack-runner: 3.0.21 => 3.0.21 
      babel-preset-taro: 3.0.21 => 3.0.21 
      eslint-config-taro: 3.0.21 => 3.0.21 
      react: ^17.0.1 => 17.0.1
```

---
### 补充信息
https://github.com/NervJS/taro/blob/next/packages/taro-components/src/components/input/input.tsx#L35

Input 组件源码中，maxlength 属性 L 是小写，但文档里是 maxLength，L 是大写

有趣的是，index.md 2 年前的提交是 ”fix(taro-components): input 组件 maxlength -> maxLength“

https://github.com/NervJS/taro/tree/next/packages/taro-components/src/components/input

所以这就很尴尬了：

一是 2 年前修 issue 难道只改了下 markdown 文档文件里的拼写？

另外就是 2 年了难道没人发现这个拼写有问题？

**Comment by DreamTravelingLight** [comment]
type='number' 的时候，maxlength 大写小写都没效果

**Comment by darkfiredarkhalo** [comment]
刚想提这个问题, 支持一下

**Comment by Chen-jj** [comment]
正确的属性名是：`maxlength`

**Comment by nanxiaobei** [comment]
补充一下，Taro 官方文档里之前写的是 `maxLength`，`L` 大写，持续了很长时间。

后来在这个 commit 里又改成了 `maxlength`，`l` 小写。

https://github.com/NervJS/taro/commit/e3488ca4055d0363639f38f3db942a62f671ae58

免得大家以为看到这个 issue，以为是提 issue 的人自己拼错了。
