### ISSUE TITLE
Taro v3.0.21 生成的百度小程序text标签显示异常

### ISSUE THREAD

**Issue by wyzwhp** [NervJS/taro#8382]
Taro v3.0.21 生成的百度小程序text标签显示异常，只有text标签和属性，没有内容

**Comment by j78742** [comment]
https://github.com/NervJS/taro/issues/8367

**Comment by j78742** [comment]
https://github.com/NervJS/taro/issues/8367
这个bug我提了，如果刚开始写百度小程序的话，赶紧不要用3.x版本，每次setState，都会整个页面重绘。
现在好降级的，赶紧降到2.x先用
