### ISSUE TITLE
useDidShow在非tabBar页面来回切换不触发

### ISSUE THREAD

**Issue by lang-strive** [NervJS/taro#8383]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
一定不要在首页和tabBar页面试， 多加几个页面跳转然后返回上一级 useDidShow 不会触发
1.在非tabBar页面 addressList页面添加useDidShow,useDidShow里执行console.log(1)；
2.第一次进去执行useDidShow，并且打印出了console.log(1)；
3.点击跳转address页面添加地址完成后 goBack()回来，useDidShow不触发console.log(1)；

### 期望结果
useDidShow在非tabBar页面也能触发，之前taro某个版本库是可以的，升级后就不行了

### 实际结果
在非tabBar页面来回切换不触发

### 环境信息
```
👽 Taro v3.1.0-beta.0


  Taro CLI 3.1.0-beta.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/node/bin/node
      Yarn: 1.22.4 - /usr/local/node/bin/yarn
      npm: 6.13.4 - /usr/local/node/bin/npm
    npmPackages:
      @tarojs/components: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/mini-runner: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/react: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/runtime: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/taro: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/webpack-runner: 3.1.0-beta.0 => 3.1.0-beta.0
      babel-preset-taro: 3.1.0-beta.0 => 3.1.0-beta.0
      eslint-config-taro: 3.1.0-beta.0 => 3.1.0-beta.0
      react: ^16.10.0 => 16.14.0
    npmGlobalPackages:
      typescript: 3.8.3
```

**Comment by luckyadam** [comment]
升级到 3.1.0-beta.4 试试

**Comment by lang-strive** [comment]
> 升级到3.1.0-beta.4试试

你好 我上周试了最新的3.1.0-beta.4 也是有问题的

**Comment by lang-strive** [comment]
> 升级到3.1.0-beta.4试试

你好大佬  另外还有一个问题咨询你下   
require 引入图片3.1.0-beta.0 之后不需要 default了吗
<img width="762" alt="截屏2020-12-28下午12 01 55" src="https://user-images.githubusercontent.com/31495553/103188780-cc3a4600-4904-11eb-96c4-1432a40603a9.png">
<img width="872" alt="截屏2020-12-28下午12 01 24" src="https://user-images.githubusercontent.com/31495553/103188782-ce040980-4904-11eb-8b5c-895302aa8296.png">

**Comment by luckyadam** [comment]
> > 升级到3.1.0-beta.4试试
> 
> 你好 我上周试了最新的v3.2.0-canary.4 也是有问题的

是 3.1.0-beta.4 不是 3.2

**Comment by luckyadam** [comment]
> > 升级到3.1.0-beta.4试试
> 
> 你好大佬 另外还有一个问题咨询你下
> require 引入图片3.1.0-beta.0 之后不需要 default了吗
> <img alt="截屏2020-12-28下午12 01 55" width="762" src="https://user-images.githubusercontent.com/31495553/103188780-cc3a4600-4904-11eb-96c4-1432a40603a9.png">
> <img alt="截屏2020-12-28下午12 05 54" width="843" src="https://user-images.githubusercontent.com/31495553/103188845-11f70e80-4905-11eb-9f16-14ee8f43daf0.png">

是的，不再需要了

**Comment by lang-strive** [comment]
> > > 升级到3.1.0-beta.4试试
> > 
> > 
> > 你好大佬另外还有一个问题咨询你下
> > 要求上一张图片3.1.0-beta.0之后不需要default了吗
> > <img alt="截屏2020-12-28下午12 01 55" width="762" src="https://user-images.githubusercontent.com/31495553/103188780-cc3a4600-4904-11eb-96c4-1432a40603a9.png">
> > <img alt="截屏2020-12-28下午12 05 54" width="843" src="https://user-images.githubusercontent.com/31495553/103188845-11f70e80-4905-11eb-9f16-14ee8f43daf0.png">
> 
> 是的，不再需要了



> > > 升级到3.1.0-beta.4试试
> > 
> > 
> > 你好我上周试了最新的v3.2.0-canary.4也是有问题的
> 
> 是3.1.0-beta.4不是3.2

3.1.0-beta.4我试了还是不可以。

**Comment by Chen-jj** [comment]
Duplicate of #8525
