### ISSUE TITLE
taro 小程序  支持微信最低版本库为多少 

### ISSUE THREAD

**Issue by anshixiaobai** [NervJS/taro#839]
在微信版本库是 1.5.3的情况下   提示
 Page[pages/index/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking 
    Page() in async task.

引入的图片也不显示
import scan from './scan.png'

<Image src={scan} />

**Comment by AibiTi** [comment]
你在 IDE 里一个一个版本试试，估计官方也没测。

**Comment by luckyadam** [comment]
2.2.3 及以上，当然低一些的版本也能支持，但是某些特性用不了

**Comment by dogbutcat** [comment]
我们的在1.6.6以上是没有问题的(主要要看使用的微信api支持到多少参考官方<code>[canIUse](https://developers.weixin.qq.com/miniprogram/dev/api/base/wx.canIUse.html)</code>)，最低到1.5.7（虽然存在Page Route报错，还有一堆红也能用。。。），其中在1.6.5版本附近如果在代码中出现data(即state)的null赋值会报错，参考[官方的坑](https://developers.weixin.qq.com/community/develop/doc/c6a7a18121f4409e17f8bcd4db6e8df5)
