### ISSUE TITLE
命令行下输入 taro help 然后 throw new Error(`${name} 命令不存在`);

### ISSUE THREAD

**Issue by ShenHongFei** [NervJS/taro#8391]
### 相关平台
微信小程序

**小程序基础库: 1.1.1**
**使用框架: React**

### 复现步骤
命令行下输入 taro help 然后 throw new Error(`${name} 命令不存在`);

### 期望结果
D:/1/taro> taro --help
� Taro v3.0.21

Usage: taro <command> [options]

Options:
  -v, --version       output the version number
  -h, --help          output usage information

Commands:
  init [projectName]  Init a project with default templete
  config <cmd>        Taro config
  create              Create page for project
  build               Build a project with options
  update              Update packages of taro
  info                Diagnostics Taro env info
  doctor              Diagnose taro project
  inspect             Inspect the webpack config
  help [cmd]          display help for [cmd]

### 实际结果
D:/1/taro> taro help build
� Taro v3.0.21

C:\Users\shf\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:246
                throw new Error(`${name} 命令不存在`);
                      ^

Error: help 命令不存在
    at Kernel.<anonymous> (C:\Users\shf\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:246:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\shf\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\@tarojs\service\dist\Kernel.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

### 环境信息
```
  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 15.5.0 - E:\SDK\NodeJS\node.EXE
      npm: 7.3.0 - E:\SDK\NodeJS\npm.CMD
```

**Comment by honlyHuang** [comment]
`taro -h`和`taro --help`没有问题，`taro help  [cmd]` 有问题

**Comment by luckyadam** [comment]
taro [cmd] -h
![image](https://user-images.githubusercontent.com/1782542/103325037-dbe09880-4a84-11eb-8349-0bb4fb03240f.png)

**Comment by Chen-jj** [comment]
```bash
# 查看所有命令
taro -h
taro --help
# 查看某个命令的帮助
taro help [cmd]
taro [cmd] -h
```
