### ISSUE TITLE
new Function()报错

### ISSUE THREAD

**Issue by Here21** [NervJS/taro#8394]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
在代码中使用new Function()，想要把'<View>xxxx</View>'字符串转成Dom节点。
```
const nodes = new Function('View', 'return <View>xxxx</View>')
// ...
nodes(View)
```

### 期望结果
转成Dom节点

### 实际结果
报错，xxxx is not a function()

### 环境信息
```
Taro CLI 3.0.20 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
```

---
### 补充信息
请问Taro3可以使用new Function()吗？或者有什么方式可以渲染'<View></View>'字符串呢

**Comment by Chen-jj** [comment]
小程序环境不支持 `new Function` 、`eval` 等。

用 React 的 `dangerouslySetInnerHTML`
