### ISSUE TITLE
taro内部打包是否开启了多核？

### ISSUE THREAD

**Issue by l2en** [NervJS/taro#8397]
### 相关平台
微信小程序

**小程序基础库: 2.11.0**
**使用框架: React**

### 复现步骤
- 使用命令`npx cross-env NODE_ENV=production taro build --type weapp --watch `进行开发时预览

### 期望结果
期待官方给明确回复，使用命令`npx cross-env NODE_ENV=production taro build --type weapp --watch` 时是否开启了多核编译？ 如果没有需要如何开启？

### 实际结果
开发阶段的打包时间过长，20~30s，不利于开发预览

**Comment by luckyadam** [comment]
没有，可以自己配置

**Comment by l2en** [comment]
> 没有，可以自己配置

在官网没找到相关文档，请问如何配置?

**Comment by luckyadam** [comment]
> > 没有，可以自己配置
> 
> 在官网没找到相关文档，请问如何配置?

taro 底层编译用的 webpack，直接调整 webpack 配置即可

**Comment by l2en** [comment]
> > > 没有，可以自己配置
> > 
> > 
> > 在官网没找到相关文档，请问如何配置?
> 
> taro 底层编译用的 webpack，直接调整 webpack 配置即可

是通过happypack开启么？ 查看了taro-cli源码中的配置，还是没太明白如何加入多核打包，不知能否给一个示例，thx

**Comment by cong1223** [comment]
> 

解决了么？
