### ISSUE TITLE
(node:87053) UnhandledPromiseRejectionWarning: TypeError: templateFn is not a function

### ISSUE THREAD

**Issue by icepy** [NervJS/taro#8398]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/icepy/tart_test](https://github.com/icepy/tart_test)
**小程序基础库: 2.9.4**
**使用框架: React**

### 复现步骤
npm run dev:weapp

### 期望结果
编译不报错

### 实际结果
编译报错

templateFn is not a function

(node:87053) UnhandledPromiseRejectionWarning: TypeError: templateFn is not a function
    at TaroMiniPlugin.generateTemplateFile (/Users/xiangwenwen/work/test/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:706:20)
    at TaroMiniPlugin.<anonymous> (/Users/xiangwenwen/work/test/node_modules/@tarojs/mini-runner/src/plugins/MiniPlugin.ts:649:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xiangwenwen/work/test/node_modules/@tarojs/mini-runner/dist/plugins/MiniPlugin.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:87053) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:87053) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    npmPackages:
      @tarojs/components: 3.0.21 => 3.0.21
      @tarojs/mini-runner: 3.0.21 => 3.0.21
      @tarojs/react: 3.0.21 => 3.0.21
      @tarojs/runtime: 3.0.21 => 3.0.21
      @tarojs/taro: 3.0.21 => 3.0.21
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
      react: ^16.10.0 => 16.14.0
```

**Comment by luckyadam** [comment]
CLI 与项目依赖版本没有保持一致

**Comment by icepy** [comment]
> CLI 与项目依赖版本没有保持一致

 @luckyadam 解决了，谢谢。

---- 其他小伙伴注意，相同问题时：

1. 如果你的CLI全局安装过，建议全部卸载了，以后 init 工程用 npx 的方式
2. 在 package.json 文件中指明 cli 的版本，如 `"@tarojs/cli":"3.0.21"` ，让 cli 永远跟着项目工程走，避免其他问题
