### ISSUE TITLE
h5 不同page同名className样式会相互覆盖

### ISSUE THREAD

**Issue by Qiu800820** [NervJS/taro#840]
**问题描述**
不同page 同名className 在小程序上显示正常
在h5上预览时，发现其他页面的同名className样式会覆盖

**复现步骤**

#### index/index.js
```js
render () {
    return (
      <View className='index'>
        <Text onClick={this.toIndex}>Hello world!</Text>
      </View>
    )
  }
```
#### index/index.css
```css
.index{
  color: black;
}
```
#### index2/index.js
```js
render () {
    return (
      <View className='index'>
        <Text>Hello world2!</Text>
      </View>
    )
  }
```
#### index2/index.css
```css
.index{
  color: red;
}
```

![image](https://user-images.githubusercontent.com/7494629/46933781-10283400-d088-11e8-90e2-6e2b2746c2ce.png)
当前界面是index/index.js
结果index2/index.css已经被加载 并且覆盖index/index.css样式

**期望行为**
当前页面样式作用域只针对当前页面

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.11.3]
 - 报错平台 [h5]

**补充信息**
如果能像ng一样 自动添加class前缀就好了

**Comment by tourze** [comment]
同发现这个问题

**Comment by luckyadam** [comment]
后续可以通过 CSS Modules 来避开这一问题

**Comment by tourze** [comment]
CSS Module支持多端了吗？（H5/微信小程序/RN）

**Comment by tensozangeci** [comment]
h5 端尝试使用babel-plugin-react-css-modules来解决作用域的问题，在配置文件index.js的babel对象的plugin属性中添加此插件配置，并打开h5端的cssModules即可。
然而同样对小程序端做此修改并不起作用，编译后的wxml并无转译styleName属性为class。

**Comment by tong233** [comment]
> h5 端尝试使用babel-plugin-react-css-modules来解决作用域的问题，在配置文件index.js的babel对象的plugin属性中添加此插件配置，并打开h5端的cssModules即可。
> 然而同样对小程序端做此修改并不起作用，编译后的wxml并无转译styleName属性为class。

可以发下h5端babel-plugin-react-css-modules配置吗？感谢
