### ISSUE TITLE
打包后无法运行，--watch模式下正常运行

### ISSUE THREAD

**Issue by Hammer001** [NervJS/taro#8403]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
执行npm run build:weapp
然后报错  TypeError: Cannot read property 'prototype' of undefined

但是 taro build --type weapp --watch 下进行开发就不会有这个报错

### 期望结果
打包成功并且可以运行

### 实际结果
报错  TypeError: Cannot read property 'prototype' of undefined

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
是不是直接引入了 lodash

**Comment by Hammer001** [comment]
@luckyadam  已解决，需关闭微信小程序中的 ES6转ES5的功能，否则会一直这样报错。
