### ISSUE TITLE
微信小程序在window  pc 端打开页面空白

### ISSUE THREAD

**Issue by RichardDegeneres** [NervJS/taro#8406]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
1. 打开小程序
2. 首页分享给好友
3. window pc 版微信小程序（3.1.0  或 3.0.0 版本）打开 分享内容

### 期望结果
正常显示页面

### 实际结果
白屏

### 环境信息
```
👽 Taro v3.0.15


  Taro CLI 3.0.15 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.22.5 - ~/.nvm/versions/node/v12.2.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.15 => 3.0.15
      @tarojs/mini-runner: 3.0.15 => 3.0.15
      @tarojs/react: 3.0.15 => 3.0.15
      @tarojs/runtime: 3.0.15 => 3.0.15
      @tarojs/taro: 3.0.15 => 3.0.15
      @tarojs/webpack-runner: 3.0.15 => 3.0.15
      babel-preset-taro: 3.0.15 => 3.0.15
      eslint-config-taro: 3.0.15 => 3.0.15
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

---
### 补充信息
小程序内报错信息为：
Object.entries is not a function TypeError: Object.entries is not a function at h (<anonymous>:8326:935) at e.value (<anonymous>:8332:26343) at e.value (<anonymous>:8332:26955) at e.value (<anonymous>:8326:2681) at c (<anonymous>:8326:36890) at <anonymous>:8326:4336 at E (<anonymous>:8336:305549) at C._invoke (<anonymous>:8336:306603) at C.forEach.e.(anonymous function) [as next] (<anonymous>:8336:305729) at r (<anonymous>:8336:207)

**Comment by luckyadam** [comment]
你看看是哪里用到了 Object.entries

**Comment by RichardDegeneres** [comment]
> 你看看是哪里用到了 Object.entries

微信小程序开发管理/ 运维中心/错误日志

![image](https://user-images.githubusercontent.com/37562985/103391423-6b08b180-4b54-11eb-89ab-dbed2502f66b.png)

**Comment by RichardDegeneres** [comment]
> 你看看是哪里用到了 Object.entries

代码中有一处使用，替换掉后好了，window pc可以正常打开了

**Comment by mapleafgo** [comment]
taro代码中用的`Object.entries`吗？我搜索我代码中并没有
