### ISSUE TITLE
使用第三方原生组件事件中带-的事件不执行

### ISSUE THREAD

**Issue by vwinway-s** [NervJS/taro#8407]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/vwinway-s/taro3-vant-sample/tree/master](https://github.com/vwinway-s/taro3-vant-sample/tree/master)
**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
安装依赖后在微信小程序平台运行

### 期望结果
`<van-uploader bind:after-read="onAfterRead" />`

### 实际结果
`<van-uploader bindafterread="onAfterRead" />`

### 环境信息
```
  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - C:\Users\qrany\AppData\Local\Temp\yarn--1609383077978-0.477430662325969\node.CMD
      Yarn: 1.22.10 - C:\Users\qrany\AppData\Local\Temp\yarn--1609383077978-0.477430662325969\yarn.CMD
      npm: 6.14.8 - D:\Env\node-v12.19.0-win-x64\npm.CMD
```

---
### 补充信息
https://github.com/vwinway-s/weapp-vant/tree/master
附上测试结果

**Comment by Chen-jj** [comment]
下个版本修复：https://docs.taro.zone/docs/next/vant#2-%E7%BB%91%E5%AE%9A%E4%BA%8B%E4%BB%B6
