### ISSUE TITLE
h5 componentDidHide不触发

### ISSUE THREAD

**Issue by blueskink** [NervJS/taro#841]
------------------------

**问题描述**
componentDidShow可以正常触发，componentDidHide不能。

**复现步骤**
[复现问题的步骤]
[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
componentDidHide正常触发

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - Taro 版本 [e.g. v.1.0.3]
 - 报错平台 [h5]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by Inori-Lover** [comment]
https://github.com/NervJS/taro/commit/4bb99cd7c33373ac3fa162b96c8ec44809ac9d41#diff-ad00994cbb5f3605d1ae24a14b405679R369

提交记录。

**Comment by Littly** [comment]
最新版(v1.2.2)应该不存在这个问题了
