### ISSUE TITLE
app.tsx中改用hooks写法报错Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by Tigerremy** [NervJS/taro#8410]
### 相关平台
H5

### 复现仓库
[https://github.com/Tigerremy/ark](https://github.com/Tigerremy/ark)
**浏览器版本: 版本 87.0.4280.88（正式版本）**
**使用框架: React**

### 复现步骤
app.tsx中改用hooks写法报错

### 期望结果
无报错

### 实际结果
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### 环境信息
```
  Taro CLI 3.0.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\z'r'm\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
更换 mobx、mobx-react版本得以解决

**Comment by Chen-jj** [comment]
运行 demo 没有复现报错

![image](https://user-images.githubusercontent.com/11807297/117238306-35a40580-ae5f-11eb-8481-7818841939b0.png)

**Comment by allValue** [comment]
更新至那个版本处理的呢？
