### ISSUE TITLE
获取路由 Current.router 出错

### ISSUE THREAD

**Issue by zjxpcyc** [NervJS/taro#8412]
### 相关平台
微信小程序

**小程序基础库: 2.14.0**
**使用框架: React**

### 复现步骤
1、新建页面，并使用 Current.router 获取 router ，此时一切正常
2、制造任意可以触发 onHide, onShow 的事件动作都可以，比如上传图片，或者缴费

### 期望结果
页面函数会重新执行，这个时候 Current.router 应该是正常值

### 实际结果
Current.router  是 null . getCurrentInstance() 也不行

### 环境信息
```
� Taro v3.0.17


  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - E:\Applications\nodejs\node.EXE
      Yarn: 1.13.0 - E:\Applications\Yarn\bin\yarn.CMD
      npm: 6.14.8 - E:\Applications\nodejs\npm.CMD
```

---
### 补充信息
但是 useRouter() 表现一切正常，没有上述 bug

**Comment by Chen-jj** [comment]
@zjxpcyc 把 `getCurrentInstance()` 的返回值保存下来，而不是每次都去调用这个 API

https://taro-docs.jd.com/taro/docs/next/react#%E8%B7%AF%E7%94%B1%E5%8F%82%E6%95%B0

**Comment by zjxpcyc** [comment]
@Chen-jj 什么意思？你的意思是需要用 `useRef` ?  这个，好吧。我后面直接使用 `useRouter` 吧 。

**Comment by Chen-jj** [comment]
文档代码写得很清楚了，不要用 `Current`，把 getCurrentInstance() 的返回值保存下来。

**Comment by NiLinli** [comment]
为什么需要把值保存下来？这是啥设计。。。
直接在代码里面取 很多时候取不到。。。
