### ISSUE TITLE
vue版本的：canvasToTempFilePath: fail canvas is empty

### ISSUE THREAD

**Issue by 826327700** [NervJS/taro#8414]
到底要怎么写呢？怎么写都是获取不到
Taro.canvasToTempFilePath({})===> canvasToTempFilePath: fail canvas is empty 
Taro.canvasToTempFilePath({},this)===> canvasToTempFilePath: fail canvas is empty

**Comment by 826327700** [comment]
同理，vue版：Taro.createCanvasContext('canvas-id',这里写什么或者不写)  都无法绘制画布

**Comment by iSoftstone-HOS** [comment]
现在页面设置canvas组件并设置canvas-id，调用api时使用该canvas-id指定
