### ISSUE TITLE
将@tarojs/cli 包同步跟随到package.json文件中

### ISSUE THREAD

**Issue by zhaoguoweiLLHC** [NervJS/taro#8418]
### 这个特性解决了什么问题？
解决了不同版本的taro项目共存问题

### 这个 API 长什么样？
以3.0.21版本举例。
```
"devDependencies": {
   ...,
  "@tarojs/webpack-runner": "3.0.21",
  "@tarojs/cli": "3.0.21",
  ...
}
```

**Comment by luckyadam** [comment]
这个自己操作就行

**Comment by zhaoguoweiLLHC** [comment]
我自己就是这么操作的，我提出来是因为在taro交流群里有不少问题是因为他们的全局cli和本地项目版本不一致导致的。所以官方如果做了这个优化，可以很大程度减少新人踩坑的概率，以及减少taro交流群的问题回复压力。
