### ISSUE TITLE
对于h5页面切换，支持配置“卸载前一个页面及其样式”

### ISSUE THREAD

**Issue by CodePlayer7** [NervJS/taro#8421]
### 这个特性解决了什么问题？
- 当前页面切换只是将前一个页面设置为display:block，样式也依旧保留，对于id、class、样式存在污染的可能，与小程序表现不一致。（小程序页面间都是独立的，id、class、样式之间不会互相影响）

**Comment by ZakaryCode** [comment]
升级到 3.3.18 修复该问题
