### ISSUE TITLE
Swiper 升级计划

### ISSUE THREAD

**Issue by chengcyber** [NervJS/taro#8427]
### 这个特性解决了什么问题？
在项目中尝试使用 yarn 2 进行安装发现 swiper 4.4.2 安装失败，https://github.com/yarnpkg/berry/issues/2327  在 swiper 5 以上的版本不会出错。

发现 @tarojs/components 写死这个版本，不知道是否后续有没有升级到新版本的规划

### 这个 API 长什么样？
无

**Comment by ZakaryCode** [comment]
暂不考虑

**Comment by ZakaryCode** [comment]
目前版本 6.8.0
