### ISSUE TITLE
支持飞书小程序吗

### ISSUE THREAD

**Issue by ripeBoy** [NervJS/taro#8428]
### 这个特性解决了什么问题？
目前需要开发飞书小程序

### 这个 API 长什么样？
没有

**Comment by Chen-jj** [comment]
可以自己写个插件来支持 https://taro-docs.jd.com/taro/docs/next/platform-plugin

**Comment by wingsico** [comment]
@ripeBoy 飞书小程序应该是和头条小程序保持一致的，可以试试编译成头条小程序

**Comment by ripeBoy** [comment]
> @ripeBoy 飞书小程序应该是和头条小程序保持一致的，可以试试编译成头条小程序，也可以继承头条小程序写个插件

好的  我研究一下插件怎么写

**Comment by ripeBoy** [comment]
> 可以自己写个插件来支持 https://taro-docs.jd.com/taro/docs/next/platform-plugin

![image](https://user-images.githubusercontent.com/24478225/104085427-5762f680-528a-11eb-9c81-c7eb5847891c.png)
你好，我继承tt编译插件写了一个飞书的编译插件，但是在编辑的时候报错，发现飞书的编译插件这里报错，麻烦问一下这是什么问题吗？

**Comment by Chen-jj** [comment]
@ripeBoy @tarojs/service 版本是否正确，可以参考下钉钉的插件：https://github.com/NervJS/taro-plugin-platform-alipay-dd/tree/master/src

![Uploading image.png…]()

**Comment by ripeBoy** [comment]
> @ripeBoy @tarojs/service 版本是否正确，可以参考下钉钉的插件：https://github.com/NervJS/taro-plugin-platform-alipay-dd/tree/master/src
> 
> ![image](https://user-images.githubusercontent.com/11807297/104095685-34106980-52d3-11eb-9774-3b7f2f9c14c8.png)

你好，我就是参考这个开发的，版本号和代码逻辑也完全一致，但是目前发现编译的时候 taro-plugin-platform-tt-fs/src/index.ts(9,30)会报错，我看好像是@tarojs/plugin-platform-tt这个插件有问题，但是不清楚具体问在哪，您可以帮我看下吗？github地址：https://github.com/ripeBoy/taro-plugin-platform-tt-fb

**Comment by ripeBoy** [comment]
> @ripeBoy @tarojs/service 版本是否正确，可以参考下钉钉的插件：https://github.com/NervJS/taro-plugin-platform-alipay-dd/tree/master/src
> 
> ![image](https://user-images.githubusercontent.com/11807297/104095685-34106980-52d3-11eb-9774-3b7f2f9c14c8.png)

你好，可以帮我看看吗？现在项目开发完了用tt编译报错，可以帮我看下我的插件哪里有问题吗

**Comment by Chen-jj** [comment]
@ripeBoy 插件相关 taro 依赖的版本，要是 beta 版本。^alpha 不会跳到 beta，从而导致插件依赖了 alpha 的 @tarojs/service。

![image](https://user-images.githubusercontent.com/11807297/105610198-6947ac00-5de9-11eb-849c-eca4ae3d9a01.png)
