### ISSUE TITLE
编译配置 imageUrlLoaderOption的outputPath是一个函数的时候不能正常工作

### ISSUE THREAD

**Issue by foreverwang** [NervJS/taro#8429]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/webpack-contrib/file-loader](https://github.com/webpack-contrib/file-loader)
**小程序基础库: 无关**
**使用框架: Vue 2**

### 复现步骤
// config/index.js

```
imageUrlLoaderOption: {
    outputPath: function (url, resourcePath, context) {
      return 'assets02'
    }
}

```

npm run build:weapp

### 期望结果
期望结果：能将图片输出到指定的目录

### 实际结果
没有输出图片文件，所有的资源都输出到了一个同名文件而不是目录，且报以下错误：

WARNING in Conflict: Multiple assets emit different content to the same filename /assets02

WARNING in Conflict: Multiple assets emit different content to the same filename /assets02

WARNING in Conflict: Multiple assets emit different content to the same filename /assets02
.....

### 环境信息
```
Taro v3.0.18


  Taro CLI 3.0.18 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.4/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    npmPackages:
      @tarojs/components: 3.0.18 => 3.0.18
      @tarojs/mini-runner: 3.0.18 => 3.0.18
      @tarojs/runtime: 3.0.18 => 3.0.18
      @tarojs/taro: 3.0.18 => 3.0.18
      @tarojs/webpack-runner: 3.0.18 => 3.0.18
      babel-preset-taro: 3.0.18 => 3.0.18
      eslint-config-taro: 3.0.18 => 3.0.18
```

**Comment by yuuk** [comment]
解决了吗？
