### ISSUE TITLE
taro rn 打包时间过长及本地打包问题

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro#843]
**问题描述**
taro 使用 expo 为基础，官方推荐使用在线打包。由于expo sdk 目前不可选择 sdk 的可选配置，每次都会将所有的sdk打包，消耗时间过长。

**复现步骤**
1.```yarn build:rn```
2.```cd ./.rn_temp```
3.``` expo build:android``` 

**期望行为**
提供本地打包方式，可以精简打包的sdk，减少打包时间

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [v.1.0.7]
 - Node.js 版本 [v8.12.0]
 - 报错平台 [rn]

**补充信息**
1.```yarn build:rn``` 生成的代码，通过 [expo eject](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md) 来进行本地打包支持。

**Comment by Leadrive** [comment]
我是做RN开发的，开始用Taro，感觉有点别扭。
能否支持RN本身的运行、打包模式？

**Comment by Pines-Cheng** [comment]
Taro  是基于 expo 的，并不支持 RN 本身的运行、打包模式哦。@Leadrive

**Comment by Pines-Cheng** [comment]
下面内容来自于 Expo 文档：

在大多数情况下，当您想要更新应用程序时，只需从 Expo CLI 再次发布。您的用户将在下次打开应用程序时下载新的 JS。为确保您的用户能够无缝下载 JS 更新，您可能希望启用 [后台 JS 下载](https://docs.expo.io/versions/v31.0.0/guides/offline-support.html)。但是，有几个原因可能导致您需要重建并重新提交本机二进制文件：

- 如果要更改应用程序名称或图标等本机元数据
- 如果您升级到较新 sdkVersion 的应用程序（需要新的本机代码）
- 要跟踪这一点，您还可以更新二进制文件的 [versionCode](https://docs.expo.io/versions/v31.0.0/workflow/configuration.html#versioncode) 和 [buildNumber](https://docs.expo.io/versions/v31.0.0/workflow/configuration.html#buildnumber)。浏览 [app.json 文档](https://docs.expo.io/versions/v31.0.0/workflow/configuration.html) 以了解您可以更改的所有属性是一个好主意，例如图标，深层链接 URL 方案，手机/平板电脑支持等等。

感觉启用 后台 JS 下载能够解决频繁打包及打包时间过长的问题。

**Comment by Pines-Cheng** [comment]
Expo 支持本地打包，这里是相关文档：[Building Standalone Apps on Your CI](https://docs.expo.io/versions/v31.0.0/distribution/building-standalone-apps)

**Comment by westeast** [comment]
但这里有一个问题expo打的包太大了，一个hello word就100多 M,  计划添加一个rn的打包模板，可行吗？

**Comment by Pines-Cheng** [comment]
可以参考一下这个issue：https://github.com/expo/expo/issues/205

Hi! Please see [this section of the docs](https://docs.expo.io/versions/v17.0.0/guides/building-standalone-apps.html#4-wait-for-it-to-finish-building) and the related [App Thinning docs](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html) from Apple.

The remaining size of the bundle (around 20MB) contains the Expo runtime and makes sure that your users have all of the native code required to receive any updates you may publish.

@westeast

**Comment by Pines-Cheng** [comment]
https://github.com/NervJS/taro/issues/1828
