### ISSUE TITLE
官方步骤创建的初始化项目编译小程序运行报错

### ISSUE THREAD

**Issue by tryharderAgain** [NervJS/taro#8431]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/qiangjianzhong/taro-study.git](https://gitee.com/qiangjianzhong/taro-study.git)
**小程序基础库: 2.4.4**
**使用框架: Vue 3**

### 复现步骤
1、安装包
2、yarn dev:weapp
3、在微信开发者工具运行

### 期望结果
能够正常显示index.vue中内容，控制台不报错

### 实际结果
VM897:1 thirdScriptError
Element is not defined;at App lifeCycleMethod onLaunch function
ReferenceError: Element is not defined
    at Object.app.mount (http://127.0.0.1:61344/appservice/vendors.js:12050:30)
    at Me.value (http://127.0.0.1:61344/appservice/taro.js:5601:27)
    at Me.<anonymous> (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:708652)
    at new Me (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:709059)
    at Function.<anonymous> (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:709475)
    at http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:689966
    at Module../src/app.js (http://127.0.0.1:61344/appservice/app.js:52:12)
    at __webpack_require__ (http://127.0.0.1:61344/appservice/runtime.js:80:30)
    at checkDeferredModules (http://127.0.0.1:61344/appservice/runtime.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:61344/appservice/runtime.js:33:19)

VM897:1 thirdScriptError
Cannot read property '$forceUpdate' of undefined;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property '$forceUpdate' of undefined
    at Object.updateAppInstance (http://127.0.0.1:61344/appservice/taro.js:5582:19)
    at Object.mount (http://127.0.0.1:61344/appservice/taro.js:5573:12)
    at mount (http://127.0.0.1:61344/appservice/taro.js:4766:21)
    at G.onLoad (http://127.0.0.1:61344/appservice/taro.js:4781:9)
    at G.<anonymous> (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:706380)
    at G.p.__callPageLifeTime__ (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:706158)
    at qt (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:719700)
    at Kt (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:720720)
    at zt (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:722011)
    at Function.<anonymous> (http://127.0.0.1:61344/appservice/__dev__/WAService.js:1:725302)

### 环境信息
```

  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.20.0 - D:\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - D:\nodejs\npm.CMD

```

**Comment by tryharderAgain** [comment]
将 编译出来的dist/vendors.js 中的12050:30 
   if (container instanceof Element) {
      container.removeAttribute('v-cloak');
      container.setAttribute('data-v-app', '');
    }
注释了 就好了

**Comment by Chen-jj** [comment]
Duplicate of #8426

**Comment by gyt95** [comment]
> 将 编译出来的dist/vendors.js 中的12050:30
> if (container instanceof Element) {
> container.removeAttribute('v-cloak');
> container.setAttribute('data-v-app', '');
> }
> 注释了 就好了

那岂不是每次编译一次就要注释一次？

**Comment by zhang1217** [comment]
> > 将在12050：30 
> > if（container instanceof Element）{ 
> > container.removeAttribute（'v-cloak'）; 
> > container.setAttribute（'data-v-app'，''）; 
> > }
> > 注释了就好了
> 
> 那岂不是每次编译一次就要注释一次？

好像有人 提交了PR  还不知道什么时候修复呢

**Comment by tryharderAgain** [comment]
对啊， 看官方说在下个小版本就会修复， 但是等了2天了还没等到下个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kwan"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 下午4:39
收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 
抄送: "强建中"<1037374654@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NervJS/taro] 官方步骤创建的初始化项目编译小程序运行报错 (#8431)





  
将 编译出来的dist/vendors.js 中的12050:30
 if (container instanceof Element) {
 container.removeAttribute('v-cloak');
 container.setAttribute('data-v-app', '');
 }
 注释了 就好了
  
那岂不是每次编译一次就要注释一次？

**Comment by zhang1217** [comment]
> 对啊， 看官方说在下个小版本就会修复， 但是等了2天了还没等到下个版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Kwan"<notifications@github.com&gt;; 发送时间: 2021年1月6日(星期三) 下午4:39 收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 抄送: "强建中"<1037374654@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [NervJS/taro] 官方步骤创建的初始化项目编译小程序运行报错 (#8431) 将 编译出来的dist/vendors.js 中的12050:30 if (container instanceof Element) { container.removeAttribute('v-cloak'); container.setAttribute('data-v-app', ''); } 注释了 就好了 那岂不是每次编译一次就要注释一次？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我也在等  可以先自己改下node_modules 就好了

**Comment by zhang1217** [comment]
> 对啊， 看官方说在下个小版本就会修复， 但是等了2天了还没等到下个版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Kwan"<notifications@github.com&gt;; 发送时间: 2021年1月6日(星期三) 下午4:39 收件人: "NervJS/taro"<taro@noreply.github.com&gt;; 抄送: "强建中"<1037374654@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [NervJS/taro] 官方步骤创建的初始化项目编译小程序运行报错 (#8431) 将 编译出来的dist/vendors.js 中的12050:30 if (container instanceof Element) { container.removeAttribute('v-cloak'); container.setAttribute('data-v-app', ''); } 注释了 就好了 那岂不是每次编译一次就要注释一次？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

改完以后 然后在npm run dev:weapp  就可以了  官方在那里说下个版本会修复？

**Comment by Chen-jj** [comment]
着急用的话可以在项目配置中配置 providePlugin：

```js
 mini: {
    webpackChain (chain) {
      chain.plugin('providerPlugin').tap(args => {
        args[0]['Element'] = [ '@tarojs/runtime', 'TaroElement' ]
        return args
      })
    }
}
```

**Comment by zhang1217** [comment]
> > 将 编译出来的dist/vendors.js 中的12050:30
> > if (container instanceof Element) {
> > container.removeAttribute('v-cloak');
> > container.setAttribute('data-v-app', '');
> > }
> > 注释了 就好了
> 
> 那岂不是每次编译一次就要注释一次？

我也在等 可以先自己改下node_modules 就好了

**Comment by xfggh** [comment]
> 着急用的话可以在项目配置中配置 providePlugin：
> 
> ```js
>  mini: {
>     webpackChain (chain) {
>       chain.plugin('providerPlugin').tap(args => {
>         args[0]['Element'] = [ '@tarojs/runtime', 'TaroElement' ]
>         return args
>       })
>     }
> }
> ```

请问最新版本的 Taro v3.1 + vue3 新建项目编译报错 SVGElement is not defined 如何处理？？非常感谢

**Comment by JH46666** [comment]
> > 着急用的话可以在项目配置中配置 providePlugin：
> > ```js
> >  mini: {
> >     webpackChain (chain) {
> >       chain.plugin('providerPlugin').tap(args => {
> >         args[0]['Element'] = [ '@tarojs/runtime', 'TaroElement' ]
> >         return args
> >       })
> >     }
> > }
> > ```
> 
> 请问最新版本的 Taro v3.1 + vue3 新建项目编译报错 SVGElement is not defined 如何处理？？非常感谢

我也遇到相同问题了
