### ISSUE TITLE
如何在taro中接入腾讯位置服务的sdk

### ISSUE THREAD

**Issue by shmmly** [NervJS/taro#844]
请问，有相关taro接入，腾讯位置服务的sdk的demo吗

**Comment by luckyadam** [comment]
暂时没有，你可以先探索一下如何加入~

**Comment by shmmly** [comment]
这个问题解决了,可以关闭了 =。=  [引入腾讯位置服务的sdk](https://shmmly.github.io/workplan/taro/)
