### ISSUE TITLE
微信小程序-分享好友失败-onShareAppMessage-函数不触发

### ISSUE THREAD

**Issue by nuts-cake** [NervJS/taro#8451]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
   <Button openType='share' >
                 分享按钮
                </Button>

### 期望结果
  onShareAppMessage() {
    const { memberInfo } = this.props.user
    console.log('分享~', memberInfo)
    // if (res.from === 'button') {
    // 来自页面内转发按钮
    // }
    return {
      title: `${memberInfo.name}的会员邀请`,
      path: '/pages/******/index',
    }
  }

### 实际结果
函数没有触发 log打印不出来

### 环境信息
```
� Taro v3.0.7


  Taro CLI 3.0.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
在Taro2可以

**Comment by kala888** [comment]
相应页面，添加  xxx.config.js
![image](https://user-images.githubusercontent.com/1215976/103725805-59228500-5012-11eb-9db4-3c77ff5a9e0d.png)

**Comment by nuts-cake** [comment]
> 相应页面，添加 xxx.config.js
> ![image](https://user-images.githubusercontent.com/1215976/103725805-59228500-5012-11eb-9db4-3c77ff5a9e0d.png)

您好,图片打不开,
我的有index.config.ts的
配置内容如下：
export default {
  navigationBarTitleText: '我的',
  navigationBarBackgroundColor: '#e42220',
  navigationBarTextStyle: 'white'
}

**Comment by Chen-jj** [comment]
https://taro-docs.jd.com/taro/docs/next/react#onshareappmessage-object

**Comment by nuts-cake** [comment]
> https://taro-docs.jd.com/taro/docs/next/react#onshareappmessage-object

谢谢!是我没仔细看文档,已实现功能,麻烦了

**Comment by quninnd** [comment]
enableShareAppMessage:true,在app.config.json能全局实现吗，我试了一下貌似不行
