### ISSUE TITLE
state更新页面render会导致之前元素重复存在

### ISSUE THREAD

**Issue by young-ren** [NervJS/taro#8452]
### 相关平台
微信小程序

**小程序基础库: 2.14**
**使用框架: React**

### 复现步骤
给组件一个默认state，用state判断渲染不同的样式。我在渲染列表，渲染dom都会出现，目前有用3.0.17 及以上的版本都有复现，主要问题是

### 期望结果
正常渲染，不在渲染不该渲染的dom

### 实际结果
有重复渲染

### 环境信息
```
  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

**Comment by xygaozhizhi** [comment]
问题提供一个测试demo

**Comment by young-ren** [comment]
> 问题提供一个测试demo

```
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { View, Button, Text, Image } from '@tarojs/components'

import { add, minus, asyncAdd } from '../../actions/counter'

import './index.less'
import img1 from './1.png'
import img2 from './2.png'

@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add() {
    dispatch(add())
  },
  dec() {
    dispatch(minus())
  },
  asyncAdd() {
    dispatch(asyncAdd())
  }
}))
class Index extends Component {
  state = {
    relationInfo: [
      {
        avatarUrl: img1,
      },
      {
        avatarUrl: img1,
      },
      {
        avatarUrl: img1,
      }]
  }
  componentWillReceiveProps(nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount() { }

  channgeImage = () => {
    const { relationInfo } = this.state;
    relationInfo[0].avatarUrl = img2;
    console.log(relationInfo)
    this.setState({
      relationInfo
    })
  }
  componentDidShow() { }

  componentDidHide() { }

  render() {
    const { relationInfo } = this.state
    return (
      <View className='index'>
        <View style={{ display: 'flex', justifyContent: 'space-around' }}>
          {relationInfo.map(item =>
            <Image key={item.avatarUrl} src={item.avatarUrl} />
          )
          }
        </View>
        <Button className='add_btn' onClick={this.channgeImage}>channgeImage</Button>

      </View>
    )
  }
}

export default Index


```
图片随便找2张。目前版本3.0.22

**Comment by young-ren** [comment]
> 问题提供一个测试demo

后面我感觉是key的问题就换了个key有点改善

**Comment by young-ren** [comment]
> 问题提供一个测试demo



> > 问题提供一个测试demo
> 
> ```
> import React, { Component } from 'react'
> import { connect } from 'react-redux'
> import { View, Button, Text, Image } from '@tarojs/components'
> 
> import { add, minus, asyncAdd } from '../../actions/counter'
> 
> import './index.less'
> import img1 from './1.png'
> import img2 from './2.png'
> 
> @connect(({ counter }) => ({
>   counter
> }), (dispatch) => ({
>   add() {
>     dispatch(add())
>   },
>   dec() {
>     dispatch(minus())
>   },
>   asyncAdd() {
>     dispatch(asyncAdd())
>   }
> }))
> class Index extends Component {
>   state = {
>     relationInfo: [
>       {
>         avatarUrl: img1,
>       },
>       {
>         avatarUrl: img1,
>       },
>       {
>         avatarUrl: img1,
>       }]
>   }
>   componentWillReceiveProps(nextProps) {
>     console.log(this.props, nextProps)
>   }
> 
>   componentWillUnmount() { }
> 
>   channgeImage = () => {
>     const { relationInfo } = this.state;
>     relationInfo[0].avatarUrl = img2;
>     console.log(relationInfo)
>     this.setState({
>       relationInfo
>     })
>   }
>   componentDidShow() { }
> 
>   componentDidHide() { }
> 
>   render() {
>     const { relationInfo } = this.state
>     return (
>       <View className='index'>
>         <View style={{ display: 'flex', justifyContent: 'space-around' }}>
>           {relationInfo.map(item =>
>             <Image key={item.avatarUrl} src={item.avatarUrl} />
>           )
>           }
>         </View>
>         <Button className='add_btn' onClick={this.channgeImage}>channgeImage</Button>
> 
>       </View>
>     )
>   }
> }
> 
> export default Index
> ```
> 
> 图片随便找2张。目前版本3.0.22

切换一种方式 ,数据更新了，React.memo后的组件视图未更新， 不知道是不是写法问题
```
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { View, Button, Text, Image } from '@tarojs/components'

import { add, minus, asyncAdd } from '../../actions/counter'

import './index.less'
import img1 from './1.png'
import img2 from './2.png'

@connect(({ counter }) => ({
  counter
}), (dispatch) => ({
  add() {
    dispatch(add())
  },
  dec() {
    dispatch(minus())
  },
  asyncAdd() {
    dispatch(asyncAdd())
  }
}))
class Index extends Component {
  state = {
    relationInfo: [
      {
        avatarUrl: img1,
      },
      {
        avatarUrl: img1,
      },
      {
        avatarUrl: img1,
      }]
  }
  componentWillReceiveProps(nextProps) {
    console.log(this.props, nextProps)
  }

  componentWillUnmount() { }

  channgeImage = () => {
    const { relationInfo } = this.state;
    relationInfo[2].avatarUrl = img2;
    console.log(relationInfo)
    this.setState({
      relationInfo
    })
  }
  componentDidShow() { }

  componentDidHide() { }

  render() {
    const { relationInfo } = this.state
    return (
      <View className='index'>
        <List relationInfo={relationInfo} />
        <Button className='add_btn' onClick={this.channgeImage}>channgeImage</Button>

      </View>
    )
  }
}
const List = React.memo(function ({ relationInfo }) {

  return (
    <View style={{ display: 'flex', justifyContent: 'space-around' }}>
      {relationInfo.map((item, index) =>
        <Image key={String(index)} src={item.avatarUrl} />
      )
      }
    </View>
  )
})

export default Index

```
