### ISSUE TITLE
使用taro+vue3 构建项目 编译后 微信小程序提示 Element is not defined

### ISSUE THREAD

**Issue by zhang1217** [NervJS/taro#8455]
使用taro+vue3 构建项目 编译后 微信小程序提示 Element is not defined

还原步骤：
taro init myapp
--选择vue3 + Typescript + SASS
npm i
npm run dev:weapp
使用微信开发工具打开后姐可以看到以下报错
![image](https://user-images.githubusercontent.com/28927924/103745431-6b181e00-503a-11eb-8dc8-2ec516f1b4f7.png)

**Comment by Chen-jj** [comment]
Duplicate of #8426
