### ISSUE TITLE
默认项目 h5 打包结果只有 js 而没有 css，有配置拆分 css 文件吗？

### ISSUE THREAD

**Issue by forever-z-133** [NervJS/taro#8459]
### 这个特性解决了什么问题？
假设在 app.ts 引入了一个 UI 库的所有 scss，那么打包 h5 时的 app.js 会增加 200k ，显然这是把 css 也加进了 js 中，该如何将 css 独立成文件呢？小菜鸡的疑惑  (・_・?)

### 这个 API 长什么样？
期望文档中有这方面的描述，或者在 issue 里教教小白吧

**Comment by JimChenWYU** [comment]
所以这个issue是解决了没有，还是说配置问题？我看到周报有写可以并没有给出任何解决方案，然后下一周报就提出了

**Comment by wanqing19954** [comment]
同样的问题，按照官方的文档，h5去配置 miniCssExtractPluginOption, css 文件并没有分离出来，还是混合到js里面去了

**Comment by thiszhong** [comment]
有方案了吗？taro 3.3.3，vue3

**Comment by ZakaryCode** [comment]
未有复现到该问题，可以参考 [文档](https://nervjs.github.io/taro/docs/next/config-detail#h5minicssextractpluginoption) 配置

> 确定 `enableExtract` 设置为 `true`

**Comment by liyunfei22** [comment]
同问

**Comment by liyunfei22** [comment]
h5: {
    publicPath: '/publicPath',
    staticDirectory: 'static',
    router: {
      basename: '/myapp',
      mode: 'browser', // 或者是 'browser'
      customRoutes: {
        '/pages/index/index': '/index',
        '/pages/rules/index': '/rules',
        '/pages/result/index': '/result',
        '/pages/down/index': '/down',
      }
    },
    devServer: {
      port: 3000,
    },
    postcss: {
      autoprefixer: {
        enable: true,
        config: {
        }
      },
      cssModules: {
        enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      },
    },
    enableExtract: true,
    miniCssExtractPluginOption: {
      filename: 'css/[name].css',
      chunkFilename: 'css/[id].css',
    },
    webpackChain(chain) {
      chain.plugin('unplugin-vue-components').use(
        ComponentsPlugin({
          resolvers: [NutUIResolver()],
        })
      )
    },
