### ISSUE TITLE
taro next获取不到上个页面中state的值

### ISSUE THREAD

**Issue by qian-forver** [NervJS/taro#8494]
### 相关平台
微信小程序

**小程序基础库: 2.14.3**
**使用框架: React**

### 复现步骤
 let currentPages = Taro.getCurrentPages();
    let prePage = currentPages[currentPages.length -2];
    console.log(prePage,'prePage')

### 期望结果
能打印出上个页面中state中所有的值

### 实际结果
打印出的是个root里面有个cn数组

### 环境信息
```
 Taro CLI 3.2.0-canary.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - D:\Downloads\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\wkd\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - D:\Downloads\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
不要这样做，使用 React 的写法，provider、redux 等。
