### ISSUE TITLE
什么时候可以支持微信小程序的 customCallout 呢？

### ISSUE THREAD

**Issue by songwenhui** [NervJS/taro#8499]
### 这个特性解决了什么问题？
微信小程序目前版本是支持自定义callout的，希望Taro能尽快支持

### 这个 API 长什么样？
Taro的customCallout传参和微信小程序的参数保持一致

**Comment by Chen-jj** [comment]
这个功能比较神奇，对比了一下原生的 demo，为 `cover-view` 增加了 slot 和 `marker-id` 后还是显示不出来，暂时没有很好的办法。

**Comment by zy888802** [comment]
@Chen-jj 请问这个功能啥时候能解决么？或者有其他办法可以实现这个功能么？

**Comment by pigeaon** [comment]
> @Chen-jj 请问这个功能啥时候能解决么？或者有其他办法可以实现这个功能么？
如果只涉及微信小程序的话，可以用小程序原生写法封装一个map组件。

**Comment by Chen-jj** [comment]
3.2.6 修复，文档地址：https://docs.taro.zone/docs/components/maps/map#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B0%94%E6%B3%A1

**Comment by harwinvoid** [comment]
模拟器上可以，真机上还是没有，用文档中的例子

**Comment by Yonghero** [comment]
@Chen-jj Taro3.3.1 照着文档中的例子还是不行

**Comment by harwinvoid** [comment]
> @Chen-jj Taro3.3.1 照着文档中的例子还是不行

将 cover-view 中的view替换成 cover-view 试试

**Comment by Sawyer-li** [comment]
@Yonghero 看看微信编辑器编译库版本要大于2.12.0
