### ISSUE TITLE
[Feature Request] custom webpack config

### ISSUE THREAD

**Issue by luankefei** [NervJS/taro#85]
版本： tarojs version 0.0.46
需求：核心是ts的引入，同时也希望能够控制webpack打包的过程，做一些个性化的优化（如图片压缩，静态资源cdn替换等）。

**Comment by luckyadam** [comment]
很快放出配置

**Comment by luckyadam** [comment]
最新版本已经支持，在文档 https://nervjs.github.io/taro/config-detail.html#h5

**Comment by simicn** [comment]
只能在 h5 环境下自定义 webpack config 吗？
我试了下在小程序环境中不生效。
