### ISSUE TITLE
checkbox disabled 属性设置无效

### ISSUE THREAD

**Issue by TevinLi** [NervJS/taro#8500]
### 相关平台
H5

### 复现仓库
[https://github.com/TevinLi/taro-bug](https://github.com/TevinLi/taro-bug)
**浏览器版本: chrome 85**
**使用框架: Vue 2**

### 复现步骤
```
<checkbox  :disabled="true" ></checkbox>
```

### 期望结果
不能改变选中状态

### 实际结果
仍然可以改变

### 环境信息
```
  Taro CLI 3.0.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
```

**Comment by wangfandev** [comment]
通过<checkbox  :disabled="true" ></checkbox>设置成不可选择，<checkbox  :disabled="true" ></checkbox>设置成可以选择。
<template>
    <view class="index">
        <view>
            <view>checkbox disabled 无效</view>
            <label>
                <checkbox :disabled="true">测试</checkbox>
                <checkbox :disabled="false">测试</checkbox>
            </label>
        </view>
        <view>
            <view>checkbox group disabled 无效</view>
            <checkbox-group @change="evt=>null">
                <label>
                    <checkbox :value="1" :disabled="true">组测试1</checkbox>
                </label>
                <label>
                    <checkbox :value="2" :disabled="false">组测试1</checkbox>
                </label>
            </checkbox-group>
        </view>
    </view>
</template>
测试结果如下图：
![image](https://user-images.githubusercontent.com/74358054/104551632-30ce0280-5672-11eb-863d-66c06891dc81.png)

**Comment by wangfandev** [comment]
设置disabled属性为true即为不可用状态，禁用只读状态，不可以改变值；
设置disabled属性为false即为可用状态，可以选择状态值。

**Comment by iSoftstone-HOS** [comment]
设置disabled属性为true即为不可用状态，禁用只读状态，不可以改变选中状态值；
设置disabled属性为false即为可用状态，可以改变选中状态值。

**Comment by hurongfang** [comment]
Why hasn't this problem been solved. This is a question raised in January. Now it's all in July

**Comment by Chen-jj** [comment]
3.3.13 修复
