### ISSUE TITLE
Taro v3.1.0-beta.4 js使用Taro.pxTransform动态设置值之后小程序和h5的单位都是px而不是对应的rpx和rem

### ISSUE THREAD

**Issue by Mar-er** [NervJS/taro#8507]
### 相关平台
微信小程序

**小程序基础库: 2.14.3**
**使用框架: React**

### 复现步骤
 <View style={{
        height: Taro.pxTransform(10)
      }}

### 期望结果
小程序和h5转码之后的单位分别为rpx和rem

### 实际结果
转码之后的单位都为px

### 环境信息
```
Taro v3.1.0-beta.4
  Taro CLI 3.1.0-beta.4 environment info:
    System: OS: Windows 10
    Binaries: Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD  
```

**Comment by wangfandev** [comment]
@taro -bot2  是所有小程序转换都有问题吗？？

**Comment by Chen-jj** [comment]
@Mar-er 复现不了，你在开发者工具看到的 px 是 rpx 计算后的实际值，style 其实是设置正确了 rpx 的。

```js
export default class Index extends Component {
  render () {
    console.log('Taro.pxTransform(10): ', Taro.pxTransform(10, 375))
    return (
      <View>
        <View
          style={{
            height: Taro.pxTransform(10, 375)
          }}
        />
      </View>
    )
  }
}
```

小程序：

![image](https://user-images.githubusercontent.com/11807297/105818132-79ca7300-5ff1-11eb-962e-18c99221c4a3.png)

![image](https://user-images.githubusercontent.com/11807297/105818168-86e76200-5ff1-11eb-9f49-66aed15e92c2.png)

![image](https://user-images.githubusercontent.com/11807297/105818208-949ce780-5ff1-11eb-8201-0150580b969c.png)

H5：

![image](https://user-images.githubusercontent.com/11807297/105817944-3f60d600-5ff1-11eb-8592-b6d9e29ff0b0.png)
