### ISSUE TITLE
bug：react hook中 多个state一起更新，数据是异步的更新，应该放到一个state中一起更新，与react正常表现不同

### ISSUE THREAD

**Issue by catsayer-heat** [NervJS/taro#8516]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/catsayer-heat/taro-bug-v3.0.20](https://github.com/catsayer-heat/taro-bug-v3.0.20)
**小程序基础库: 2.14.4**
**使用框架: React**

### 复现步骤
打开运行小程序，直接点击按钮。
```
import React, { useState, useEffect } from 'react'
import { Button } from '@tarojs/components'

const Page: React.FC = () => {
  const [a, setA] = useState(1)
  const [b, setB] = useState(1)

  useEffect(() => {
    console.log(`a:${a}, b:${b}`)
  }, [a, b])
  
  return (
    <Button
      onClick={() => {
        console.log('我只点击了一次')
        setA(a + 1)
        setB(b + 1)
      }}
    >
      点击此处
    </Button>
  )
}

export default Page
```

### 期望结果
我只点击了一次
a:2, b:2
![image](https://user-images.githubusercontent.com/37840913/104432354-e8580b80-55c3-11eb-9aa3-223d69b63060.png)

### 实际结果
我只点击了一次
a:2, b:1
a:2, b:2
![image](https://user-images.githubusercontent.com/37840913/104432462-0291e980-55c4-11eb-854c-3b6e9d22ee57.png)

### 环境信息
```
�👽 Taro v3.0.20


  Taro CLI 3.0.20 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Users\catsayer\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Users\catsayer\AppData\Roaming\npm\npm.CMD

```

**Comment by Chen-jj** [comment]
ReactDOM 里有调用 `batchedEventUpdates` 的逻辑，但是在 Taro 内部用于代替 ReactDOM 的 renderer 没有实现这部分逻辑，从而导致这个问题。

需要花时间再看看。
