### ISSUE TITLE
给view设置属性，初始化阶段属性值为null，view变成pure-view，属性丢失

### ISSUE THREAD

**Issue by superNos** [NervJS/taro#8524]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
给view设置animation属性，animation初始化时值是null，后续设置有效值，结果animation失效，编译出来的view节点没有animation属性

### 期望结果
view 设置属性在初始化阶段为null时，也使用static-view模板

### 实际结果
view属性初始化时如果是null，就直接使用了pure-view模板

### 环境信息
```
Taro CLI 3.0.23 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.23 => 3.0.23 
      @tarojs/components: 3.0.23 => 3.0.23 
      @tarojs/mini-runner: 3.0.23 => 3.0.23 
      @tarojs/react: 3.0.23 => 3.0.23 
      @tarojs/runtime: 3.0.23 => 3.0.23 
      @tarojs/taro: 3.0.23 => 3.0.23 
      @tarojs/webpack-runner: 3.0.23 => 3.0.23 
      babel-preset-taro: 3.0.23 => 3.0.23 
      eslint-config-taro: 3.0.23 => 3.0.23 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: 16.10.0 => 16.10.0 
      taro-ui: ^3.0.0-alpha.2 => 3.0.0-alpha.3 
```

**Comment by Chen-jj** [comment]
提供一下代码

**Comment by superNos** [comment]
> 提供一下代码

import React from 'react'
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Demo extends React.Component {

    state = {
        animation: null
    }

    componentDidMount() {
        setTimeout(() => {
            const animation = Taro.createAnimation({
                duration: 800,
                timingFunction: 'ease-out',
            })
          
            animation.rotate(180).step()
        
            this.setState({
                animation: animation.export()
            })
        }, 1000)
    }

    render () {
        return (
            <View
                style={{ margin: 100, width: 100, height: 100, background: 'red' }}
                animation={this.state.animation}
            >
            </View>
        )
    }
}

**Comment by superNos** [comment]
@Chen-jj 
> 复现 demo如下

```javascript
import React from 'react'
import Taro from '@tarojs/taro'
import { View } from '@tarojs/components'

export default class Demo extends React.Component {

    state = {
        animation: null
    }

    componentDidMount() {
        setTimeout(() => {
            const animation = Taro.createAnimation({
                duration: 800,
                timingFunction: 'ease-out',
            })
          
            animation.rotate(180).step()
        
            this.setState({
                animation: animation.export()
            })
        }, 1000)
    }

    render () {
        return (
            <View
                style={{ margin: 100, width: 100, height: 100, background: 'red' }}
                animation={this.state.animation}
            >
            </View>
        )
    }
}
```

**Comment by superNos** [comment]
初始值为undefined也不行

**Comment by wangfandev** [comment]
demo中View引入的animation报错，报错信息如下，怎么解决？@superNos
(JSX attribute) StandardProps<any>.animation?: {
    actions: object[];
} | undefined
动画属性
Type 'null' is not assignable to type '{ actions: object[]; } | undefined'.ts(2322)
common.d.ts(19, 3): The expected type comes from property 'animation' which is declared here on type 'IntrinsicAttributes & ViewProps & { children?: ReactNode; }'

**Comment by Chen-jj** [comment]
把 `animation` 设置为 `''` 绕过吧。

**Comment by superNos** [comment]
@Chen-jj 可以在移除prop时加个hasOwnProperty的判断么
https://github.com/NervJS/taro/pull/8540
