### ISSUE TITLE
BUG useDidShow,usePullDownRefresh,useReachBottom 钩子函数在非tabBar页面来回切换不触发

### ISSUE THREAD

**Issue by lang-strive** [NervJS/taro#8525]
### 相关平台
微信小程序

**小程序基础库: 2.12.0**
**使用框架: React**

### 复现步骤
一定不要在首页和tabBar页面试， 多加几个页面跳转然后返回上一级 useDidShow,usePullDownRefresh,useReachBottom 不会触发
1.在非tabBar页面 addressList页面添加useDidShow,useDidShow里执行console.log(1)；
2.第一次进去执行useDidShow，并且打印出了console.log(1)；
3.点击跳转address页面添加地址完成后 goBack()回来，useDidShow不触发console.log(1)；

### 期望结果
useDidShow,usePullDownRefresh,useReachBottom 这几个钩子函数返回到上一级同样触发

### 实际结果
useDidShow,usePullDownRefresh,useReachBottom 这几个钩子函数返回到上一级不触发

### 环境信息
```
👽 Taro v3.1.0-beta.0


  Taro CLI 3.1.0-beta.0 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/node/bin/node
      Yarn: 1.22.4 - /usr/local/node/bin/yarn
      npm: 6.13.4 - /usr/local/node/bin/npm
    npmPackages:
      @tarojs/components: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/mini-runner: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/react: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/runtime: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/taro: 3.1.0-beta.0 => 3.1.0-beta.0
      @tarojs/webpack-runner: 3.1.0-beta.0 => 3.1.0-beta.0
      babel-preset-taro: 3.1.0-beta.0 => 3.1.0-beta.0
      eslint-config-taro: 3.1.0-beta.0 => 3.1.0-beta.0
      react: ^16.10.0 => 16.14.0
    npmGlobalPackages:
      typescript: 3.8.3
```

---
### 补充信息
https://github.com/NervJS/taro/issues/8384
https://github.com/NervJS/taro/issues/8383
这两个issues之前提过 项目周报 (2020 年 12 月 26 日 - 2021 年 1 月 2 日)  但是好像最新的版本没有修复 不知道是拉掉了吗还是没来的急， 也算是一个致命的bug 没有其他的替代方案 希望官方可以解决下哈 写写🙏

**Comment by Chen-jj** [comment]
@lang-strive 复现不了，三个 hooks 都正常工作，如果还有问题，提供一下完整可复现 demo 吧。

[demo.zip](https://github.com/NervJS/taro/files/5871879/demo.zip)

**Comment by dahuahe** [comment]
我也有useDidShow navigateBack回来不执行情况，经过排查发现 如果使用useDidShow的页面 发生一些报错，如数据读取为null还在做数据渲染报错。会发现useDidShow navigateBack回来不执行.目前是做好检查避免报错 useDidShow都正常执行的
