### ISSUE TITLE
原生微信小程序代码通过taro convert转换成taro代码，再编译成支付宝小程序，项目运行报错

### ISSUE THREAD

**Issue by joaquin-qin** [NervJS/taro#8528]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/joaquin-qin/taro-convert-test](https://github.com/joaquin-qin/taro-convert-test)
**小程序基础库: 1.24.3**
**使用框架: React**

### 复现步骤
1.将原生微信小程序代码转换为taro代码

  $ taro convert

2.编译成支付宝小程序

  $ cd taroConvert

  $ npm install

  $ npm run dev:alipay 

3.使用支付宝小程序开发工具打开项目

### 期望结果
代码正常运行

### 实际结果
代码无法运行代码，报错。

1. getApp()返回的值没有globalData和自定义的函数
2. App中的onLaunch，onShow等方法没执行

### 环境信息
```
taro v3.1.0-beta.4

  Taro CLI 3.1.0-beta.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.11 - C:\software\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@joaquin-qin 把 data.message 注释掉，或给个空字符串，页面 onLoad 再设置为 `app.globalData.message`：

```js
@withWeapp({
  data: {
    motto: 'Hello World',
    // message: app.globalData.message
  }
})
```

这是因为支付宝机制有点不一样，这时还拿不到 app 上最新设置的属性：

![image](https://user-images.githubusercontent.com/11807297/105811454-a24d6f80-5fe7-11eb-9424-a4b1d1881e2a.png)
