### ISSUE TITLE
  module "comp.swan" is not defined

### ISSUE THREAD

**Issue by max-end** [NervJS/taro#8532]
### 相关平台
百度小程序

**小程序基础库: 3.250.33**
**使用框架: React**

### 复现步骤
taro init myApp
npm run dev:swan
新创建的项目不能用

### 期望结果
百度小程序正常显示

### 实际结果
空白报错，不显示

### 环境信息
```

  Taro CLI 3.0.23 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
报错信息 Slave page render error in loadResource.
  module "comp.swan" is not defined
  Error: Slave page render error in loadResource.
  module "comp.swan" is not defined

**Comment by Chen-jj** [comment]
Duplicate of #8531
