### ISSUE TITLE
Taro小程序如何跳转到app

### ISSUE THREAD

**Issue by liwanna** [NervJS/taro#8535]
### 这个特性解决了什么问题？
当app调起小程序后 然后小程序实现一定的功能后需要返回app 类似于原生小程序的wx.navigateBackApplication方法 

### 这个 API 长什么样？
wx.navigateBackApplication方法

**Comment by Chen-jj** [comment]
https://developers.weixin.qq.com/community/develop/doc/00046ab390cf68296ef8ad5a75b400
