### ISSUE TITLE
ref 的问题

### ISSUE THREAD

**Issue by junjie-yang-only** [NervJS/taro#854]
![image](https://user-images.githubusercontent.com/25219300/47003943-0a535100-d163-11e8-8699-15d1a60fb485.png)

发现：在渲染子组件 cat 的时候，ref 绑定的是一个函数，为啥会执行两次？

**Comment by junjie-yang-only** [comment]
![image](https://user-images.githubusercontent.com/25219300/47004109-674f0700-d163-11e8-89e2-53efa425de94.png)
![image](https://user-images.githubusercontent.com/25219300/47004122-6e761500-d163-11e8-896a-19a475cc8368.png)

**Comment by Chen-jj** [comment]
已修正：[e6d0d28](https://github.com/NervJS/taro/commit/e6d0d287c815af5d02fb01cc154bd8f360cfc25f)，[80e0c65](https://github.com/NervJS/taro/commit/80e0c65cd553cace2edd66289a68de6cfd34aab6)
