### ISSUE TITLE
期望添加微信小程序 getVideoInfo 方法支持

### ISSUE THREAD

**Issue by cocoyk** [NervJS/taro#8541]
### 这个特性解决了什么问题？
获取视频详细信息(画面方向，视频格式，视频长度，视频大小，视频宽高，视频帧率，视频码率)；

具体到我的问题，是想获取视频的高宽，以便动态设置Video组件的宽高。

### 这个 API 长什么样？
类似原生微信小程序 https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.getVideoInfo.html

Taro. getVideoInfo(Object object);   
参数 Object object

属性	类型	默认值	必填	说明

src	string		是	视频文件路径，可以是临时文件路径也可以是永久文件路径

success	function		否	接口调用成功的回调函数

fail	function		否	接口调用失败的回调函数

complete	function		否	接口调用结束的回调函数（调用成功、失败都会执行）

**Comment by luckyadam** [comment]
可以直接提个 pr

**Comment by Chen-jj** [comment]
3.1 已支持
