### ISSUE TITLE
> > > > > > rc.5 版本中发现View组件的hidden属性无效了哦

### ISSUE THREAD

**Issue by liyong-private** [NervJS/taro#8545]
> > > > > > rc.5 版本中发现View组件的hidden属性无效了哦
> > > > > 
> > > > > 
> > > > > 我这边也是，你是怎么解决的呢
> > > > 
> > > > 
> > > > 不要用 hidden 属性，用 React、Vue 的语法去控制显隐
> > > 
> > > 
> > > 从小程序源码转码过来的项目，之前是taro1（v1.3.21）,现在在做升级taro3（v3.0.17,react）发现hidden不支持了，一个一个修改比较麻烦，有无可能 提供babel插件转一下hidden语法再webpack打包？或者在babel-preset-taro做一下支持呀? 另外taro3转小程序源码后的代码也包含hidden。
> > 
> > 
> > 你好, 你的问题解决了吗?
> 
> > 我也想知道这个问题该怎么优雅的解决，不会要挨个手动 `display: none` 吧！

3.1已支持 hidden

3.1之前可以写个样式，强行 display:none
```
[hidden=true] {
  display: none !important;
}
```

_Originally posted by @Chen-jj in https://github.com/NervJS/taro/issues/5460#issuecomment-760634501_

**Comment by Chen-jj** [comment]
1. **Taro 项目**，`<View>` 组件不支持 hidden 属性，使用 React、Vue 的条件渲染或样式去处理。
2. **原生微信小程序转换为 Taro 项目**，反向转换原生小程序的 `hidden` 属性的功能，在 3.1 已经支持。
