### ISSUE TITLE
text 组件 decode 属性无效

### ISSUE THREAD

**Issue by without-yy** [NervJS/taro#8549]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/without-yy/taro_onClick_issue/blob/master/src/pages/text/index.js](https://github.com/without-yy/taro_onClick_issue/blob/master/src/pages/text/index.js)
**小程序基础库: 2.14.4**
**使用框架: React**

### 复现步骤
```
<Text decode dangerouslySetInnerHTML={{ __html: '测试换行\nxxxx' }} />

```

![C8piMHBIL3uswVQ](https://i.loli.net/2021/01/18/C8piMHBIL3uswVQ.png)

### 期望结果
decode可以生效

### 实际结果
不生效

### 环境信息
```
👽 Taro v3.0.24


  Taro CLI 3.0.24 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - /usr/local/opt/node@14/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.24 => 3.0.24 
      @tarojs/components: 3.0.24 => 3.0.24 
      @tarojs/mini-runner: 3.0.24 => 3.0.24 
      @tarojs/react: 3.0.24 => 3.0.24 
      @tarojs/runtime: 3.0.24 => 3.0.24 
      @tarojs/taro: 3.0.24 => 3.0.24 
      @tarojs/webpack-runner: 3.0.24 => 3.0.24 
      babel-preset-taro: 3.0.24 => 3.0.24 
      eslint-config-taro: 3.0.24 => 3.0.24 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.9 

```

**Comment by wangfandev** [comment]
复现步骤截图看不到啊

**Comment by without-yy** [comment]
> 复现步骤截图看不到啊

科学上网

**Comment by wangfandev** [comment]
decode可以解析的有&nbsp;、&lt;、&gt;、&amp;、&apos;、&ensp;、&emsp；  \n换行符不支持

**Comment by honlyHuang** [comment]
[微信文档](https://developers.weixin.qq.com/miniprogram/dev/component/text.html) 末尾的 Bug & Tip
1. tip: decode可以解析的有` &nbsp; &lt; &gt; &amp; &apos; &ensp; &emsp;`
 
不支持 \n换行符

**Comment by without-yy** [comment]
@honlyHuang @wangfandev 

https://github.com/NervJS/taro/issues/7003#issuecomment-659218093

text组件换行应该怎么写

**Comment by mosqlee** [comment]
```js
<Text className="test">{"测试换行\nxxxx"}</Text>
```

**Comment by mosqlee** [comment]
@honlyHuang @Chen-jj 

packages/taro-runtime/src/dom/html/style.ts里面直接替换html里面所有换行有问题。
我今天会提个pr，麻烦大佬们看下。

> ```js
> <Text className="test">{"测试换行\nxxxx"}</Text>
> ```

@without-yy

**Comment by iSoftstone-HOS** [comment]
decode可以解析的有&nbsp;、&lt;、&gt;、&amp;、&apos;、&ensp;、&emsp；

**Comment by toFrankie** [comment]
使用 `transformElement` 对 `el.nodeName === text` 的元素设置 `el.setAttribute('decode', true)` 不生效，咋回事呢，姿势不对？？渲染后的小程序 `<text>` 元素并没有如预期般添加 `decode` 属性。
