### ISSUE TITLE
H5使用@tarojs/components的Video组件，暂停视频报错

### ISSUE THREAD

**Issue by wangjuerong** [NervJS/taro#8550]
### 相关平台
H5

### 复现仓库
[https://github.com/wangjuerong/taro-bug](https://github.com/wangjuerong/taro-bug)
**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
1. git clone项目
2. yarn 安装依赖
3. yarn dev:h5启动项目
4. 页面中的视频，点击播放，然后再点击暂停

### 期望结果
视频可以正常暂停

### 实际结果
报错：TypeError: Cannot read property 'pause' of undefined

### 环境信息
```
👽 Taro v1.2.26


  Taro CLI 1.2.26 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v12.8.1/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.16 => 3.0.16 
      @tarojs/components: 3.0.16 => 3.0.16 
      @tarojs/taro: 3.0.16 => 3.0.16 
      @tarojs/webpack-runner: 3.0.16 => 3.0.16 
      eslint-config-taro: 3.0.16 => 3.0.16 
      react: ^16.10.0 => 16.14.0 
```

---
### 补充信息
<video />的引用被设置为了undefined，导致在点击video-control组件的暂停按钮时，获取不到video的引用
<video />的ref应该增加一个非空判断，如下：
ref={dom => {
  if (dom) {
    this.videoRef = dom as HTMLVideoElement
  }
}}

**Comment by wangfandev** [comment]
这个问题应该怎么解决？？this.videoRef.pause()和this.videoRef.currentTime = position报错

**Comment by Grewer** [comment]
升级 taro 版本
