### ISSUE TITLE
小程序 和 h5 希望可以支持 node_modules 里面的文件跨平台

### ISSUE THREAD

**Issue by shinken008** [NervJS/taro#8566]
### 这个特性解决了什么问题？
当引入 npm 包文件时，对于文件内部的引用也可以支持跨平台。
这功能方便我们抽离公共功能的依赖包。

### 这个 API 长什么样？
```js
const config = {
  // ...
  include: [],
  // ...
}
```

**Comment by luckyadam** [comment]
https://docs.taro.zone/docs/envs#%E8%AE%A9-node_modules-%E4%B8%AD%E7%9A%84%E4%BE%9D%E8%B5%96%E4%B9%9F%E8%83%BD%E8%A7%A3%E6%9E%90%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6

**Comment by Chen-jj** [comment]
先通过 webpackchain 改 webpack 配置实现，后面加一个 taro 配置
