### ISSUE TITLE
组件内引用微信原生组件报错[Taro3.0.24]

### ISSUE THREAD

**Issue by shwangson** [NervJS/taro#8567]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/huanghaochen/test-taro](https://gitee.com/huanghaochen/test-taro)
**小程序基础库: 2.14.4**
**使用框架: React**

### 复现步骤
1 开发者工具运行项目, Console出现编译警告
[http://note.youdao.com/s/N9jh4xE5](url)
 

### 期望结果
组件中能正常引入原生自定义组件

### 实际结果
引用不到

### 环境信息
```

  Taro CLI 2.0.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm

    项目里面安装了3.0.24：
    "devDependencies": {
       "@babel/core": "^7.8.0",
      "@tarojs/cli": "^3.0.24",

    编译时：

      WSHOP@1.0.0 build:weapp /Users/mars/wangsheng/WSHOP-test/client
      taro build --type weapp

     👽 Taro v3.0.24

     编译 发现入口 src/app.js
    编译 发现页面 src/pages/index/index.jsx

```

**Comment by Chen-jj** [comment]
Taro2 还是 3

**Comment by shwangson** [comment]
3.0.24

**Comment by shwangson** [comment]
@Chen-jj Taro3.0.24

**Comment by Chen-jj** [comment]
那你 CLI 版本为什么是 2.0.3

**Comment by shwangson** [comment]
那个是电脑全局环境：
项目里面转了3.0.24：
	"devDependencies": {
		"@babel/core": "^7.8.0",
		"@tarojs/cli": "^3.0.24",

编译时：
> WSHOP@1.0.0 build:weapp /Users/mars/wangsheng/WSHOP-test/client
> taro build --type weapp

👽 Taro v3.0.24


编译  发现入口  src/app.js
编译  发现页面  src/pages/index/index.jsx

**Comment by shwangson** [comment]
@Chen-jj 
那个是电脑全局环境：
项目里面转了3.0.24：
"devDependencies": {
"@babel/core": "^7.8.0",
"@tarojs/cli": "^3.0.24",

编译时：

WSHOP@1.0.0 build:weapp /Users/mars/wangsheng/WSHOP-test/client
taro build --type weapp

👽 Taro v3.0.24

编译 发现入口 src/app.js
编译 发现页面 src/pages/index/index.jsx

**Comment by Chen-jj** [comment]
Taro 3 中，**页面**才有配置项，组件没有，你写错地方了。

**Comment by shwangson** [comment]
那在组件内使用原生自定义组件，怎么引入？非常感谢回答！

**Comment by Chen-jj** [comment]
在页面或全局配置中配置引入

**Comment by shwangson** [comment]
> 在页面或全局配置中配置引入

已解决,非常感谢
