### ISSUE TITLE
小程序动态加载官方实现

### ISSUE THREAD

**Issue by JiyuShao** [NervJS/taro#8579]
### 这个特性解决了什么问题？
微信小程序动态动态加载 JS 代码, 并且在只修改动态加载相关代码的情况下, 不会更改之前打包出的静态资源, 最大程度上实现发版不发小程序源码

#### 增加 dynamicImport 配置

```js
dynamicImport: {
  // 是否开启动态加载, 开启的话默认输出所有的 Taro Component 模板等相关逻辑
  enable: true,
  // 指定一个目录为动态加载的目录, 方便区分静态代码和动态代码
  dynamicImportFolder: require('path').resolve(
    __dirname,
    '../src/dynamic-import'
  ),
  // 指定动态加载链接 prefix
  publicPath: 'http://localhost:5000/',
  // 开发模式下启动的开发服务器端口
  devServer: {
    port: 5000,
  },
}
```

#### 代码中使用动态加载

```js
import React, { Suspense } from 'react';
import { View, Text } from '@tarojs/components';

const Index = () => {
  const DynamicComponent = React.lazy(() =>
    import('../../dynamic-import/dynamic-component/dynamic-component')
  );
  return (
    <View>
      <Text>Hello World</Text>
      <Suspense fallback={<Text>Loading...</Text>}>
        <DynamicComponent />
      </Suspense>
    </View>
  );
};
export default Index;
```

### 实现方式

使用 webpack 插件实现:

- 更改动态导入输出文件目录
- 注入代码 PUPLIC_PATH
- 替换 jsonpScriptSrc 方法
- 添加小程序请求/执行代码逻辑, `wx.request`   [`eval5`](https://github.com/bplok20010/eval5)
- 开发模式下提供 devServer

### 已实现的 demo

项目地址: [taro-dynamic-import-weapp](https://github.com/JiyuShao/taro-dynamic-import-weapp)

**Comment by luckyadam** [comment]
感觉可以直接直接写成 Taro 的插件来进行拓展哦
https://docs.taro.zone/docs/plugin

**Comment by JiyuShao** [comment]
好的, 我尝试封装一下

**Comment by luckyadam** [comment]
> 好的, 我尝试封装一下

棒棒棒，完善后我们帮忙推荐一下

**Comment by JiyuShao** [comment]
> 感觉可以直接直接写成 Taro 的插件来进行拓展哦
> https://docs.taro.zone/docs/plugin

你好, 我已经封装好了 [`taro-plugin-dynamic-import-weapp`](https://github.com/JiyuShao/taro-dynamic-import-weapp/tree/master/packages/taro-plugin-dynamic-import-weapp), 还有几个问题:
- `babel-preset-taro` 在小程序中会使用 [`babel-plugin-dynamic-import-node`](https://github.com/NervJS/taro/blob/56378b1ab9ddf8bc498308b7efe3516f3f35f5a7/packages/babel-preset-taro/index.js#L125), 是否可以增加一个可关闭的配置
- Taro 插件要怎么编写测试

**Comment by JiyuShao** [comment]
已发布Taro 物料 [小程序端动态加载代码](https://taro-ext.jd.com/plugin/view/6049846a39b51f165cbfb0f4)

**Comment by ZakaryCode** [comment]
> * `babel-preset-taro` 在小程序中会使用 [`babel-plugin-dynamic-import-node`](https://github.com/NervJS/taro/blob/56378b1ab9ddf8bc498308b7efe3516f3f35f5a7/packages/babel-preset-taro/index.js#L125), 是否可以增加一个可关闭的配置

可以，之后加个参数关闭该配置

**Comment by wuchangming** [comment]
@ZakaryCode ，我看现在有个参数是 dynamic-import-node 。但是现在只能设置 h5 的不使用，其他平台不行。
```
  if (options['dynamic-import-node'] || process.env.TARO_ENV !== 'h5') {
    plugins.push([require('babel-plugin-dynamic-import-node')])
  }
```
https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/index.js#L165
这里的 || 能改成 && 不？

**Comment by ZakaryCode** [comment]
> @ZakaryCode ，我看现在有个参数是 dynamic-import-node 。但是现在只能设置 h5 的不使用，其他平台不行。
> 
> ```
>   if (options['dynamic-import-node'] || process.env.TARO_ENV !== 'h5') {
>     plugins.push([require('babel-plugin-dynamic-import-node')])
>   }
> ```
> 
> https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/index.js#L165 这里的 || 能改成 && 不？

可以做一些调整

**Comment by wuchangming** [comment]
@ZakaryCode ，有个与此有关联的PR，可否帮忙看下：https://github.com/NervJS/taro/pull/11589
