### ISSUE TITLE
H5下的界面tabBar显示位置错误

### ISSUE THREAD

**Issue by EasyTuan** [NervJS/taro#858]
**问题描述**
H5下，在底部有设置tabBar的情况，A(首页)跳转Taro.navigateTo到B(详情)再跳转Taro.navigateTo到C(登录)，成功登录Taro.navigateBack();，网址路径会变成首页的，内容会显示B（详情）底部带tabBar

执行以上的步骤就能复现（必须是真机），附线上地址

> http://ms.caibowen.net/

首页下滑点商品=>进详情=>选择尺码点加入衣袋=>登录=>成功返回即可看到tabBar显示在详情页，路径是首页的，刷新下就到首页了

如觉得代码有问题可以新建了一个taro项目，简单跳转就可以复现

**系统信息**

 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.11.3]
 - 报错平台 [h5(真机safari、微信浏览器)]

**Comment by Littly** [comment]
最新版(v1.2.2)应该不存在这个问题了
