### ISSUE TITLE
设置tabBar的显隐性

### ISSUE THREAD

**Issue by huyaweii** [NervJS/taro#8590]
### 这个特性解决了什么问题？
场景：
app.js配置tabBar，tabBar的list中包含首页。
进入到首页会根据接口结果来判断是否显示下边的tabbar

问题：
当进入首页后，总是会先展示底部tabbar一下，然后接口结果回来调用hideTabbar才能隐藏掉它

希望的结果：
进入首页不展示tabbar, 接口结果请求回来调用showTabbar展示

### 这个 API 长什么样？
增加配置, 来控制tabBar默认是否展示

**Comment by iamxiyang** [comment]
各个小程序似乎都没有配置tabbar数据但默认隐藏的配置项，我觉得这个不应该由taro实现，可以考虑在app.ts中调用hideTabbar先隐藏，再根据接口结果进行显示。如果想要更加灵活，可以尝试自定义tabbar

**Comment by huyaweii** [comment]
> 各个小程序似乎都没有配置tabbar数据但默认隐藏的配置项，我觉得这个不应该由taro实现，可以考虑在app.ts中调用hideTabbar先隐藏，再根据接口结果进行显示。如果想要更加灵活，可以尝试自定义tabbar

好的 谢谢

**Comment by musicode** [comment]
app.ts 在 componentDidMount 中调用 hideTabBar 没用，好像加了 setTimeout 再调就行，这个延时很难把握，而且 ios 和 安卓的延时还不一样，请问官方有啥推荐方式么？

**Comment by musicode** [comment]
app.ts 在 componentDidMount 中调用 hideTabBar 没用，好像加了 setTimeout 再调就行，这个延时很难把握，而且 ios 和 安卓的延时还不一样，请问官方有啥推荐方式么？
