### ISSUE TITLE
建议taro的项目配置中的 weapp 添加微信小程序的 project.config.json 的相关配置

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro#860]
建议taro的项目配置中的 weapp 添加微信小程序的 project.config.json 的相关配置，如 appid，编译代码时可以直接赋值进去。其他项目，如百度小程序类似。
目前仅支持 weapp.compile 和 weapp.module [配置](https://nervjs.github.io/taro/docs/config-detail.html#weappcompile)

**Comment by u3u** [comment]
这个不是有么

**Comment by tomgao365** [comment]
@u3u 哪里？官方的[文档](https://nervjs.github.io/taro/docs/config-detail.html#weappcompile)没有查到啊

**Comment by tomgao365** [comment]
@u3u 了解。没注意到项目根目录这个文件
