### ISSUE TITLE
error: node_modules/taro-ui/dist/style/components/icon.scss: Failed to parse declaration "line-height: 1"

### ISSUE THREAD

**Issue by taoqf** [NervJS/taro#8618]
### 相关平台
React Native

### 复现仓库
[https://github.com/taoqf/notexist](https://github.com/taoqf/notexist)

**使用框架: React**

### 复现步骤
1. 必填项
2. 必填项

### 期望结果
无

### 实际结果
无

### 环境信息
```
👽 Taro v3.2.0-canary.8


  Taro CLI 3.2.0-canary.8 environment info:
    System:
      OS: Linux 5.10 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.6.0/bin/yarn
      npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/components: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/mini-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/react: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/runtime: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/webpack-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      babel-preset-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      eslint-config-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      react: ^17.0.1 => 17.0.1 
      react-native: ^0.63.4 => 0.63.4 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.9 

```

**Comment by taoqf** [comment]
后续还有如某某scss找不到的错误，但文件我看了，确实是存在的，为了编译通过，我只能把这些import的样式去掉了。
我认为发布的包里就不要使用scss了，直接使用css多好。这不但在使用过程中容易出现各种问题，也增加开发时的cpu运行负担。现在运行时已经很慢了。

**Comment by taoqf** [comment]
Navivator组件在rn是存在的，需要使用direct api才行。

**Comment by taoqf** [comment]
在rn中，storage的sync方法也找不到。

**Comment by taoqf** [comment]
在rn中，tabbar默认android按物理返回键没反应，不返回到上一页。这个要怎么设置？

**Comment by shinken008** [comment]
> 后续还有如某某scss找不到的错误，但文件我看了，确实是存在的，为了编译通过，我只能把这些import的样式去掉了。
> 我认为发布的包里就不要使用scss了，直接使用css多好。这不但在使用过程中容易出现各种问题，也增加开发时的cpu运行负担。现在运行时已经很慢了。

增加 scss 跟 运行时没关系，只是编译的问题，另外 css 不支持 import 语法

**Comment by shinken008** [comment]
> 在rn中，storage的sync方法也找不到。

不支持这个，参考下文档 https://taro-docs.jd.com/taro/docs/3.2.0-canary.3/apis/storage/setStorageSync

**Comment by shinken008** [comment]
> Navivator组件在rn是存在的，需要使用direct api才行。

issue 分开提，然后描述详细点哈

**Comment by taoqf** [comment]
> > 后续还有如某某scss找不到的错误，但文件我看了，确实是存在的，为了编译通过，我只能把这些import的样式去掉了。
> > 我认为发布的包里就不要使用scss了，直接使用css多好。这不但在使用过程中容易出现各种问题，也增加开发时的cpu运行负担。现在运行时已经很慢了。
> 
> 增加 scss 跟 运行时没关系，只是编译的问题，另外 css 不支持 import 语法

就是编译慢哪，老大

**Comment by taoqf** [comment]
> 另外 css 不支持 import 语法

不支持就对了，这样如果发布就要合并成一个文件，就没有import路径问题了呀，什么东西简单了就稳定可靠。

**Comment by taoqf** [comment]
redirect问题解决，应该用`navigateto`

**Comment by shinken008** [comment]
> 发布就要合并成一个文件，就没有import路径问题了呀，什么东西简单了就稳定可靠。

taro-ui 应该是考虑到包大小的问题，方便按需引入
