### ISSUE TITLE
map 渲染时三元表达式无效？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#862]
------------------------

**问题描述**
map 渲染时三元表达式无效
```js
this.state.monthData.map((month, monthIndex) => {
                  return (
                    <View className='single-month' key={monthIndex + 1}>
                      <View className='month-title'>{`${this.state.year}年${monthIndex + 1}月`}</View>
                      <View className='date at-row at-row--wrap'>
                        {
                          month.map((day, index) => {
                            let dayJSX = addDaysFromPreMonth[monthIndex] <= index ?
                              (<View className='day'>{day}</View>) : '';
                            return (
                              <View className='at-col at-col-1_7_1 day-wrap' key={index}>
                                {dayJSX}
                              </View>
                            );
                          })
                        }
                      </View>
                    </View>);
                })
```
![image](https://user-images.githubusercontent.com/43346131/47062259-adf63d00-d207-11e8-9983-03bd64954677.png)
**### 效果图：**
![image](https://user-images.githubusercontent.com/43346131/47062215-6a9bce80-d207-11e8-9116-ea0a23f208b6.png)
但是这样写就OK了，就是吧 上面的 jsx 表达式换成 一个字符串 ‘123’
![image](https://user-images.githubusercontent.com/43346131/47062568-683a7400-d209-11e8-8008-ccf3a8e42621.png)
**### 效果图：**
![image](https://user-images.githubusercontent.com/43346131/47062483-e5191e00-d208-11e8-8623-e01ec5428dd3.png)
**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**Comment by yuche** [comment]
我觉得问题应该在 `addDaysFromPreMonth[monthIndex] <= index ` 这个表达式一直为 `false`，当我把他写为 `-1 <= index` 时是可以渲染的，编译也没错。

提问的时候一定记得带上你的版本号，不然像上次一样。

![image](https://user-images.githubusercontent.com/7202516/47070918-dd677280-d224-11e8-899a-0f952af3c271.png)

**Comment by JoMartinezZhu** [comment]
> 我觉得问题应该在 `addDaysFromPreMonth[monthIndex] <= index` 这个表达式一直为 `false`，当我把他写为 `-1 <= index` 时是可以渲染的，编译也没错。
> 
> 提问的时候一定记得带上你的版本号，不然像上次一样。
> 
> ![image](https://user-images.githubusercontent.com/7202516/47070918-dd677280-d224-11e8-899a-0f952af3c271.png)

Taro 版本号:1.0.7;
我这样修改之后是 可以 渲染出来的 ，这个问题 症结 是在 为什么将三元表达式的中的 JSX 表达式 改为 String 类型的 ‘123’，就可以正常渲染了呢？
![image](https://user-images.githubusercontent.com/43346131/47072287-53210d80-d228-11e8-9d02-c3b58cba74ed.png)

**Comment by JoMartinezZhu** [comment]
> 「这样修改」是怎么修改？把你前面表达式修改为真吗？
> 
> 当你改为 123之后也要前面的 `addDaysFromPreMonth[monthIndex] <= index` 这个表达式为真时才渲染。
> 两者不同的地方在于一个是条件渲染 dom 元素，一个是渲染 text node，关键的问题还是你前面的表达式。

不对;对比一下，下面的截图,第二张是我目前的临时解决方案，两个的差别就是 三元表达式中 条件渲染 dom 元素 不同！
![image](https://user-images.githubusercontent.com/43346131/47073669-5ff33080-d22b-11e8-9b59-addbca49d79e.png)
![image](https://user-images.githubusercontent.com/43346131/47073765-9466ec80-d22b-11e8-8fa1-1d70d0cd65b6.png)

**Comment by JoMartinezZhu** [comment]
> 「这样修改」是怎么修改？把你前面表达式修改为真吗？
> 
> 当你改为 123之后也要前面的 `addDaysFromPreMonth[monthIndex] <= index` 这个表达式为真时才渲染。
> 两者不同的地方在于一个是条件渲染 dom 元素，一个是渲染 text node，关键的问题还是你前面的表达式。

针对 Taro 中的三元表达式以及 逻辑运算，我发现了一个 问题！
当
data.state === 2 ---> true
recognizeStatis --->null
时，
却得到了 这样的结果          data.state === 2 && !!recognizeStatis             ----> true
我非常不解，结果 应该是 false 的
为了 解决这个问题 ,我是这样处理的
data.state === 2 && (!!recognizeStatis).toString() === 'true' ----- > false

```
{
              (data.state === 2 && !!recognizeStatis) && (
                <View className='practise-statistic'>
                  practise-statistic 2----{data.state}
                  {JSON.stringify(recognizeStatis)}
                  {(!recognizeStatis).toString()}
                  {averageJSX}
                  {topErrorsJSX}
                  {analysisJSX}
                </View>
              )
            }
```
![image](https://user-images.githubusercontent.com/43346131/47128938-f8d68a00-d2c5-11e8-808f-ddb7d23381f9.png)

**Comment by JoMartinezZhu** [comment]
> > recognizeStatis --->null
> 
> 能否做一个带数据源的简单的复现？我这边似乎不会出现这个情况

我这边做了一个简单的数据源，但是 没有出现 这个情况！能给一个简单的推断嘛，怎么会出现 这个问题呢？

**Comment by yuche** [comment]
我也不能复现所以才问你要一个能复现的版本啊
