### ISSUE TITLE
请求添加 wx.cloud.Cloud api

### ISSUE THREAD

**Issue by doublethinkio** [NervJS/taro#8623]
### 这个特性解决了什么问题？
微信云开发环境共享

### 这个 API 长什么样？
Taro.cloud.Cloud

https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-sdk-api/init/client.init.html
https://developers.weixin.qq.com/miniprogram/dev/wxcloud/guide/resource-sharing/

https://github.com/NervJS/taro/blob/d2c4aaf5d9d755bc3ca40f9b449340b360c673d5/packages/taro/apis/wx.js#L211
https://github.com/NervJS/taro/blob/60bb8fce96d281fc40a9897ba900c26af9f33787/packages/taro/types/api/cloud/index.d.ts#L207

**Comment by Chen-jj** [comment]
@doublethinkio 可以来个 PR 咯～

**Comment by doublethinkio** [comment]
啊 那个  我类型定义写的有问题 我放完年假再修复一下
