### ISSUE TITLE
小程序插件开发预计什么时候能够支持

### ISSUE THREAD

**Issue by yantingxi** [NervJS/taro#8626]
### 这个特性解决了什么问题？
小程序插件开发

### 这个 API 长什么样？
同taro2.x即可

![image](https://user-images.githubusercontent.com/30825361/106468956-90813600-64d9-11eb-92d6-e747ef707840.png)

**Comment by luckyadam** [comment]
年后支持下

**Comment by yantingxi** [comment]
> 年后支持下

目前我看2.0x已经支持，但是不支持百度小程序，开发者可以通过框架编译插件开发来支持百度小程序的插件机制么？因为目前百度小程序的插件开发并未对外开放。

**Comment by bluefox1688** [comment]
期待3.X支持编辑微信小程序插件，从uni-app转过来的

**Comment by eattopking** [comment]
大概什么版本能支持呢

**Comment by bluefox1688** [comment]
> 大概什么版本能支持呢

同问，等着用来开发呢

**Comment by Chen-jj** [comment]
3.2.6 支持，#6959
