### ISSUE TITLE
添加componentWillPreload对应的hooks

### ISSUE THREAD

**Issue by FE-Sakamoto** [NervJS/taro#8627]
### 这个特性解决了什么问题？
解决函数式组件无法使用componentWillPreload的功能

### 这个 API 长什么样？
usePreload(()=>{
    return thenable
})

**Comment by Chen-jj** [comment]
哪个版本？

**Comment by FE-Sakamoto** [comment]
> 哪个版本？

哪个版本都没有componentWillPreload对应的hooks吧

**Comment by ZakaryCode** [comment]
Taro 3 不再提供 componentWillPreload、$preload API，改为:

调用：

```js
Taro.preload()
```

获取

```js
console.log(getCurrentInstance().preloadData)
```

[参考文档](https://nervjs.github.io/taro/docs/next/optimized#%E8%B7%B3%E8%BD%AC%E9%A2%84%E5%8A%A0%E8%BD%BD)
