### ISSUE TITLE
支付宝custom-wrapper.axml报错

### ISSUE THREAD

**Issue by cjz9032** [NervJS/taro#8628]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**小程序基础库: 1**
**使用框架: React**

### 复现步骤
支付宝编译完的路径是错的, 
微信正常

### 期望结果
项目能正常运行

### 实际结果
custom-wrapper.axml直接报错
![image](https://user-images.githubusercontent.com/11435814/106540334-b12da800-653a-11eb-85cd-be2533e8aabf.png)

### 环境信息
```
Taro v3.1.0-beta.5


  Taro CLI 3.1.0-beta.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.21.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
3.1.0-beta.6 解决

**Comment by cjz9032** [comment]
> 3.1.0-beta.6 解决

ok 很奇怪, 我看next分支中是正常的, 难道是merge时冲突搞错了~

**Comment by Chen-jj** [comment]
merge 时搞错了：https://github.com/NervJS/taro/commit/bd5f0615c06fb61a5b02382c60ead17fb73ffa59

可以手动先改本地依赖
