### ISSUE TITLE
希望提供Taro.getEnterOptionsSync

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#8631]
### 这个特性解决了什么问题？
获取本次小程序启动时的参数。如果当前是冷启动，则返回值与 App.onLaunch 的回调参数一致；如果当前是热启动，则返回值与 App.onShow 一致。

如：https://developers.weixin.qq.com/miniprogram/dev/api/base/app/life-cycle/wx.getEnterOptionsSync.html

### 这个 API 长什么样？
Taro.getEnterOptionsSync

同 Taro.getLaunchOptionsSync() 类似

**Comment by Chen-jj** [comment]
3.1.0-beta 版本已支持。
