### ISSUE TITLE
taro3 vue2配置了alias后 对css 中background-image的url利的路径引用不生效

### ISSUE THREAD

**Issue by foreverwang** [NervJS/taro#8633]
### 相关平台
微信小程序

**小程序基础库: 与小程序无关**
**使用框架: Vue 2**

### 复现步骤
一、confg/index.js 里配置alias 
```
alias: {
'@/assets': path.resolve(__dirname, '..', 'image/package')
}

```

二、 .vue 内的style 里的背景图路径使用alias

```

<style >
  .demo {
      background: url("@/assets/xxx@2x.png");
 }
</style>


###  期望结果
能正常替换alias 路径

###  实际结果
编译报错：
Module not found: Error: Can't resolve './@/saas/xxx@2x.png'

### 环境信息
```
Taro v3.0.26

process.env.NODE_ENV undefined

  Taro CLI 3.0.26 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.10.0 - ~/.nvm/versions/node/v13.10.0/bin/node
      npm: 6.13.7 - ~/.nvm/versions/node/v13.10.0/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.26 => 3.0.26
      @tarojs/components: 3.0.18 => 3.0.18
      @tarojs/mini-runner: 3.0.18 => 3.0.18
      @tarojs/taro: 3.0.18 => 3.0.18
      @tarojs/webpack-runner: 3.0.18 => 3.0.18
      babel-preset-taro: 3.0.18 => 3.0.18
      eslint-config-taro: 3.0.18 => 3.0.18
```

<!-- generated by taro-issues. 请勿修改或删除此行注释 --><!--labels=T-weapp,V-3,F-vue2-->

**Comment by luckyadam** [comment]
```
background: url("~@/assets/xxx@2x.png")
```

**Comment by foreverwang** [comment]
正解：background: url("~@/assets/xxx@2x.png")
