### ISSUE TITLE
Taro v3.1.0-beta.5 新建项目运行支付宝报错：\base[object Object].axml not exists!

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#8641]
### 相关平台
支付宝小程序

**小程序基础库: 支付宝这边未找到版本**
**使用框架: Nerv**

### 复现步骤
taro init taro3Demo1 新建一个项目之后，依赖安装完成 ```npm run dev:alipay```
后在支付宝ide中无法运行
报错如下
Error: ./custom-wrapper.axml
Module build failed :
Error: custom-wrapper.axml
Module build failed:
\base[object Object].axml not exists!

### 期望结果
支付宝正常运行

### 实际结果
运行报错

### 环境信息
```
� Taro v3.1.0-beta.5


  Taro CLI 3.1.0-beta.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
顺便问一下，npm run dev:alipay 之后，命令行提示
Tips: 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ set NODE_ENV=production && taro build --type alipay --watch

但是复制上面提示的命令运行，仍然是报这个提示

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/106842479-18845d00-66df-11eb-9b2c-883b879e6ac9.png)

**Comment by Chen-jj** [comment]
Duplicate of #8628 

beta.6 解决，可以先用  beta.4

**Comment by GAONING-abc** [comment]
我的运行npm run dev:alipay之后也出现了相同的问题 
![1631519536(1)](https://user-images.githubusercontent.com/17755625/133045294-8efd2861-3262-421b-ba30-43bb389f6f0a.png)
![1631519570(1)](https://user-images.githubusercontent.com/17755625/133045328-f8721954-c934-4fa8-baeb-a71f2a3761cd.png)
