### ISSUE TITLE
build h5  安卓手机加载报错:  'super' keyword unexpected here

### ISSUE THREAD

**Issue by rockliuxn** [NervJS/taro#8648]
### 相关平台
H5

**浏览器版本: Android 7.0 内置浏览器**
**使用框架: React**

### 问题描述

通过 npm run build:h5 编译成功，并放到线上
在iOS 和 电脑浏览器里不会报错，在部分安卓机型下通过Webview打开会报错，显示白屏

之前有用户提到过类似的问题：[https://github.com/NervJS/taro/issues/2913](url)
但现在新的Taro v3.0.26 又重现了

### 期望结果
可以正常加载，打开页面

### 实际结果
页面报错，显示白屏

通过Chrome打开远程调试，console 显示如下错误信息：
``` bash
Uncaught SynctaxError:'super' keyword unexpected here
```

### 环境信息

``` bash
Taro CLI 3.0.26 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26
      @tarojs/mini-runner: 3.0.26 => 3.0.26
      @tarojs/react: 3.0.26 => 3.0.26
      @tarojs/router: 3.0.26 => 3.0.26
      @tarojs/runtime: 3.0.26 => 3.0.26
      @tarojs/taro: 3.0.26 => 3.0.26
      @tarojs/taro-h5: 3.0.26 => 3.0.26
      @tarojs/webpack-runner: 3.0.26 => 3.0.26
      babel-preset-taro: 3.0.26 => 3.0.26
      eslint-config-taro: 3.0.26 => 3.0.26
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

###  Android 版本信息
Mi Note2
Android  7.0
MIUI9.5 |稳定版

**Comment by Chen-jj** [comment]
@rockliuxn 目测某个文件没有经过 babel 编译，看看是哪个模块，另外试试 Taro 3 早些时候的版本行不行。

**Comment by rockliuxn** [comment]
> @rockliuxn 目测某个文件没有经过 babel 编译，看看是哪个模块，另外试试 Taro 3 早些时候的版本行不行。

感谢回复！
请问如何能够快速定位未经babel编译的模块，对这块的排除方法不是很懂，谢谢～！

**Comment by Chen-jj** [comment]
看看报错信息是出自那个文件，哪里有 `super` 关键词，

**Comment by rockliuxn** [comment]
> 看看报错信息是出自那个文件，哪里有 `super` 关键词，

感谢～！

另外发现一个比较奇怪的事情，`super` 的这个错误在不同的node环境中，有的会报错，有的不会
我现在不确定是代码的问题，还是环境配置的问题
taro 3 对node 版本有要求吗？

### 报错的 Taro info

``` bash
Taro CLI 3.0.26 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v10.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26
      @tarojs/mini-runner: 3.0.26 => 3.0.26
      @tarojs/react: 3.0.26 => 3.0.26
      @tarojs/router: 3.0.26 => 3.0.26
      @tarojs/runtime: 3.0.26 => 3.0.26
      @tarojs/taro: 3.0.26 => 3.0.26
      @tarojs/taro-h5: 3.0.26 => 3.0.26
      @tarojs/webpack-runner: 3.0.26 => 3.0.26
      babel-preset-taro: 3.0.26 => 3.0.26
      eslint-config-taro: 3.0.26 => 3.0.26
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

### 正常的Taro info

``` bash
Taro CLI 3.0.26 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26
      @tarojs/mini-runner: 3.0.26 => 3.0.26
      @tarojs/react: 3.0.26 => 3.0.26
      @tarojs/router: 3.0.26 => 3.0.26
      @tarojs/runtime: 3.0.26 => 3.0.26
      @tarojs/taro: 3.0.26 => 3.0.26
      @tarojs/taro-h5: 3.0.26 => 3.0.26
      @tarojs/webpack-runner: 3.0.26 => 3.0.26
      babel-preset-taro: 3.0.26 => 3.0.26
      eslint-config-taro: 3.0.26 => 3.0.26
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.3
```

**Comment by luckyadam** [comment]
提供一个 Demo 看看

**Comment by Yana5417** [comment]
这个应该是引入的资源文件中，编译箭头函数后有super这个关键字

**Comment by LuXinZ** [comment]
不要让babel 编译 node_modules

**Comment by SakuOtonashi** [comment]
把其他引进的代码都移除了就一个简单的显示图片文字的页面还是会报错，构建出的压缩代码和正常的压缩代码不一样

错误的代码里有一些像下面的一些东西，正确的代码里找不到这样的东西
`T=class extends HTMLElement{"constructor"(r){super(r),registerHost(r=this,m)}"connectedCallback"(){U&&...`

报错的Taro info用的是 [CODING](https://tlpp.coding.net/user) 的自动化
```
  Taro CLI 3.2.7 environment info:
  System:
    OS: Linux 4.4 Ubuntu 16.04.1 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.21.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - /usr/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.7 => 3.2.7 
      @tarojs/components: 3.2.7 => 3.2.7 
      @tarojs/mini-runner: 3.2.7 => 3.2.7 
      @tarojs/react: 3.2.7 => 3.2.7 
      @tarojs/runtime: 3.2.7 => 3.2.7 
      @tarojs/taro: 3.2.7 => 3.2.7 
      @tarojs/webpack-runner: 3.2.7 => 3.2.7 
      babel-preset-taro: 3.2.7 => 3.2.7 
      eslint-config-taro: 3.2.7 => 3.2.7 
      react: ^17.0.0 => 17.0.2 
```

**Comment by bingjianguo** [comment]
1、导致问题的源代码出现在这个 @tarojs/components  包里。如下图所示
![image](https://user-images.githubusercontent.com/2384478/117528353-55286300-b004-11eb-9388-7ce2c8505e6e.png)



2、看了下这个问题，定位到是在webpack对script处理过程中，加了exclude逻辑，代码位于
/myTaroApp3/node_modules/@tarojs/webpack-runner/dist/util/chain.js这个文件的 Line.  420~428

这个exlude的条件，把 @tarojs/components 作为exclude处理了，导致最终构建产出的代码有了es6的class和 extends HTMLElement(那个construtor的引号还没定位到是什么时候加上去的)。因此只要对 @tarojs/components 让babel处理一遍就可以避免这个问题。

如下图变更前后的对比所示：
![image](https://user-images.githubusercontent.com/2384478/117528298-0e3a6d80-b004-11eb-995f-1ed0c68f5550.png)


附：本地测试改为如下内容，可以正常运行的变更：

rule.script = {
        test: helper_1.REG_SCRIPTS,
        exclude: [filename => /node_modules/.test(filename) && !(/taro-h5/.test(filename)) && !(/@tarojs\/components/.test(filename)) ],
        use: {
            babelLoader: getBabelLoader([{
                    compact: false
                }])
        }
    };

**Comment by qizf7** [comment]
@Chen-jj 您好，请问3.2.9v版本什么时候上线，我们也遇到了同样的问题，希望等官方升级解决。

**Comment by bluescurry** [comment]
@Chen-jj 请问有3.2.9的预计发版时间吗，或者有临时方案吗，目前安卓的webview全部白屏。。。

**Comment by xiehui999** [comment]
@Chen-jj  ??? 可以了吗

**Comment by sycreece** [comment]
> `@taroj/components` 这个包应该预先编译好，external 掉是正确的。
> 
> 问题在于它打包时使用的 Stencil 没有开启打包到 ES5 的配置，导致打出 ES6 的代码。
> 
> 修改 Stencil 的打包配置即可，下个版本修复～

遇到了同样的问题，3.2.9版本里没有修复？

**Comment by xiehui999** [comment]
3.2.9已经发布了，但是这个代码没有merge进去啊，是忘记merge 了吗？ 临时解决方案呢？自己打临时包吗？ @Chen-jj ， 还是说改本地代码

**Comment by rabbitao** [comment]
3.2.10版本此问题仍然存在.  
Mozilla/5.0 (Linux; U; Android 10; zh-CN; Redmi Note 7 Build/QKQ1.190910.002)

**Comment by Chen-jj** [comment]
> 3.2.10版本此问题仍然存在.
> Mozilla/5.0 (Linux; U; Android 10; zh-CN; Redmi Note 7 Build/QKQ1.190910.002)

可以先搜索一下问题出现在哪个 chunk

**Comment by rabbitao** [comment]
> > 3.2.10版本此问题仍然存在.
> > Mozilla/5.0 (Linux; U; Android 10; zh-CN; Redmi Note 7 Build/QKQ1.190910.002)
> 
> 可以先搜索一下问题出现在哪个 chunk

这个错误是app.js里面报出的.
l=class extends HTMLElement{"constructor"(t){super(t),registerHost(t=this,c)}"connectedCallback"()

> > 3.2.10版本此问题仍然存在.
> > Mozilla/5.0 (Linux; U; Android 10; zh-CN; Redmi Note 7 Build/QKQ1.190910.002)
> 
> 可以先搜索一下问题出现在哪个 chunk

这个错误是app.js中报出的.
具体就是这个super(t)
l=class extends HTMLElement{"constructor"(t){super(t),registerHost(t=this,c)}"connectedCallback"()

我还需要从哪里获取更详细的错误信息吗  请指教

**Comment by rabbitao** [comment]
![image](https://user-images.githubusercontent.com/27269160/120299215-6449ba80-c2fd-11eb-822b-5c2264d8ae0c.png)
component包里确实还存在es6的语法

**Comment by Chen-jj** [comment]
@rabbitao 

看看 loader/index.js ，应该是用的 esm-es5 里的组件才对：

![image](https://user-images.githubusercontent.com/11807297/120339838-0bdbe280-c328-11eb-9e06-f9f3c89615ce.png)

可以看到 esm-es5 里的代码已经被转为 es5 代码：

![image](https://user-images.githubusercontent.com/11807297/120340002-3463dc80-c328-11eb-9fe3-e2cc524450b0.png)

**Comment by rabbitao** [comment]
> @rabbitao
> 
> 看看 loader/index.js ，应该是用的 esm-es5 里的组件才对：
> 
> ![image](https://user-images.githubusercontent.com/11807297/120339838-0bdbe280-c328-11eb-9e06-f9f3c89615ce.png)
> 
> 可以看到 esm-es5 里的代码已经被转为 es5 代码：
> 
> ![image](https://user-images.githubusercontent.com/11807297/120340002-3463dc80-c328-11eb-9fe3-e2cc524450b0.png)

![image](https://user-images.githubusercontent.com/27269160/120409799-4d9a7680-c384-11eb-8781-4ea32d6a9c94.png)
看起来我的内容和你的不一样. 是什么原因造成的呢? 我的cli环境如下: 
`Taro CLI 3.2.10 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 3.8.3`

**Comment by xiehui999** [comment]
> > @rabbitao
> > 看看 loader/index.js ，应该是用的 esm-es5 里的组件才对：
> > ![image](https://user-images.githubusercontent.com/11807297/120339838-0bdbe280-c328-11eb-9e06-f9f3c89615ce.png)
> 
> @Chen-jj
> ![image](https://user-images.githubusercontent.com/27269160/120409799-4d9a7680-c384-11eb-8781-4ea32d6a9c94.png)
> 
> 看起来我的内容和你的不一样. 是什么原因造成的呢? 我的cli环境如下:
> 
> Taro CLI 3.2.10 environment info:
> System:
> OS: macOS 11.3.1
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 14.5.0 - /usr/local/bin/node
> Yarn: 1.15.2 - /usr/local/bin/yarn
> npm: 6.14.5 - /usr/local/bin/npm
> npmPackages:
> @tarojs/components: 3.2.8 => 3.2.8
> @tarojs/mini-runner: 3.2.8 => 3.2.8
> @tarojs/react: 3.2.8 => 3.2.8
> @tarojs/runtime: 3.2.8 => 3.2.8
> @tarojs/taro: 3.2.8 => 3.2.8
> @tarojs/webpack-runner: 3.2.8 => 3.2.8
> babel-preset-taro: 3.2.8 => 3.2.8
> eslint-config-taro: 3.2.8 => 3.2.8
> react: ^17.0.0 => 17.0.2
> npmGlobalPackages:
> typescript: 3.8.3


升级到3.2.10 版本试

**Comment by Chen-jj** [comment]
@rabbitao 楼上正解，你的项目依赖还是 3.2.8

**Comment by MarkLogin** [comment]
> @rabbitao 楼上正解，你的项目依赖还是 3.2.8

我现在使用的Taro 版本是3.4.12 在Android9 的手机上还存在这个白屏问题
这是报错信息
/chromium: [INFO:CONSOLE(2)] "Uncaught SyntaxError: 'super' keyword unexpected here", source: http://172.17.60.117:8080/pretrapp/chunk/0.js (2)
I/chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) Error: ChunkLoadError: Loading chunk 0 failed.
    (missing: http://172.17.60.117:8080/pretrapp/chunk/0.js)", source: http://172.17.60.117:8080/pretrapp/js/app.js (2)

这是项目中使用的版本
    "@tarojs/cli": "3.4.12",
    "@tarojs/components": "3.4.12",
    "@tarojs/plugin-framework-react": "^3.4.12",

taro info
👽 Taro v3.5.3

  Taro CLI 3.5.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.10.0 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - D:\nodejs\npm_path\yarn.CMD
      npm: 7.12.0 - D:\nodejs\npm.CMD

**Comment by zybieku** [comment]
<img width="910" height="134" alt="Image" src="https://github.com/user-attachments/assets/1f77f9a1-fc1e-4562-a15a-f605d913bf3b" />
这个被注释了
