### ISSUE TITLE
h5页面 addEventListener 参数 passive 传为true

### ISSUE THREAD

**Issue by myNameIsDu** [NervJS/taro#8649]
### 这个特性解决了什么问题？
浏览器会给很多警告
![image](https://user-images.githubusercontent.com/53305259/106907550-557d3d80-6739-11eb-92cd-9811e1684910.png)

能感觉到chrome的开发工具会一直在刷这个警告，开发工具会比较卡，然后就是滚动性能问题
https://rbyers.github.io/scroll-latency.html

https://developers.google.com/web/updates/2016/06/passive-event-listeners

### 这个 API 长什么样？
默认传入passive为true

**Comment by luckyadam** [comment]
是使用哪个组件导致的

**Comment by myNameIsDu** [comment]
使用View组件就会出这个警告:

![image](https://user-images.githubusercontent.com/53305259/107345270-5da0f880-6afe-11eb-9862-aa9ffa825ac1.png)
![image](https://user-images.githubusercontent.com/53305259/107345350-6db8d800-6afe-11eb-97b7-f547d2d88049.png)


![image](https://user-images.githubusercontent.com/53305259/107345392-76a9a980-6afe-11eb-8196-175daa3cdc36.png)
![image](https://user-images.githubusercontent.com/53305259/107345408-7c9f8a80-6afe-11eb-9354-26ccd3f1cae3.png)

**Comment by ZakaryCode** [comment]
未能复现到该问题，如果存在可以说明具体版本
