### ISSUE TITLE
希望提供wx.getEnterOptionsSync的实现

### ISSUE THREAD

**Issue by cpocar** [NervJS/taro#8653]
### 这个特性解决了什么问题？
获取本次小程序启动时的参数。如果当前是冷启动，则返回值与 App.onLaunch 的回调参数一致；如果当前是热启动，则返回值与 App.onShow 一致。

### 这个 API 长什么样？
Taro.getEnterOptionsSync  类似 Taro.getLaunchOptionsSync

**Comment by Chen-jj** [comment]
3.1 已支持

**Comment by cpocar** [comment]
> 3.1 已支持

getEnterOptionSync 在3.1.0 的Taro中找不到呢？

**Comment by biluochun** [comment]
Taro版本3.3.9，没有发现这个API的声明，是漏了？
