### ISSUE TITLE
[RN] Taro 3.2.0-canary.8 是否支持 CSS Modules？

### ISSUE THREAD

**Issue by SolidZORO** [NervJS/taro#8656]
### 这个特性解决了什么问题？
期待 RN 正确的支持 CSS Modules。

### 这个 API 长什么样？
希望在 RN 中书写  CSS Modules：

```
import styles from './home.module.less';

<Text className={styles['css-modules-1']}>CSS MODULES STYLE</Text>
```

能做到和 H5、小程序表现一致。

在 https://taro-docs.jd.com/taro/docs/3.2.0-canary.3/config-detail#rn 中我看到了添加了 RN 的配置，但没找到 cssModules 选项。

<img width="1247" alt="WechatIMG152" src="https://user-images.githubusercontent.com/661587/107111022-78b60300-6887-11eb-965d-d908fb74a79f.png">

**Comment by zhiqingchen** [comment]
@shinken008
test

**Comment by shinken008** [comment]
@SolidZORO  这是个 taro css module 的适配问题，我看看

**Comment by shinken008** [comment]
https://github.com/wuba/taro-react-native/commit/7ad783a2377e52aa0863b17890b71e1f4ba5cad7
