### ISSUE TITLE
showModal 颜色设置没有反应

### ISSUE THREAD

**Issue by zqxb** [NervJS/taro#8657]
### 相关平台
支付宝小程序

**小程序基础库: 2.0.6**
**使用框架: React**

### 复现步骤
  Taro.showModal({
            title: '操作提醒',
            content: '确认删除当前书籍吗？',
            confirmText: '确认',
            cancelText: '取消',
            cancelColor: '000080',
            confirmColor: '#000080',
            success: function (res) {
                if (res.confirm) {
                    console.log('用户点击确定')
                } else if (res.cancel) {
                    console.log('用户点击取消')
                }
            }
        })

### 期望结果
色值起用

### 实际结果
没有反应

### 环境信息
```
Taro CLI 2.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 2.0.6 => 2.0.6 
      @tarojs/components-qa: 2.0.6 => 2.0.6 
      @tarojs/mini-runner: 2.0.6 => 2.0.6 
      @tarojs/mobx: 2.0.6 => 2.0.6 
      @tarojs/mobx-h5: 2.0.6 => 2.0.6 
      @tarojs/router: 2.0.6 => 2.0.6 
      @tarojs/taro: 2.0.6 => 2.0.6 
      @tarojs/taro-alipay: 2.0.6 => 2.0.6 
      @tarojs/taro-h5: 2.0.6 => 2.0.6 
      @tarojs/taro-qq: 2.0.6 => 2.0.6 
      @tarojs/taro-quickapp: 2.0.6 => 2.0.6 
      @tarojs/taro-swan: 2.0.6 => 2.0.6 
      @tarojs/taro-tt: 2.0.6 => 2.0.6 
      @tarojs/taro-weapp: 2.0.6 => 2.0.6 
      @tarojs/webpack-runner: 2.0.6 => 2.0.6 
      eslint-config-taro: 2.0.6 => 2.0.6 
      eslint-plugin-taro: 2.0.6 => 2.0.6 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      stylelint-config-taro-rn: 2.0.6 => 2.0.6 
      stylelint-taro-rn: 2.0.6 => 2.0.6 
    npmGlobalPackages:
      typescript: 4.0.5
```

**Comment by zqxb** [comment]
cancelColor: '000080',
 confirmColor: '#000080',
 都测试过，没有反应

**Comment by Chen-jj** [comment]
Taro 只是对原生 API 进行 Promise 化，可以使用原生的 API 再试试，区分是原生还是 Taro 的问题。

**Comment by Chen-jj** [comment]
@zqxb 支付宝的模态框不能设置字体颜色：

![image](https://user-images.githubusercontent.com/11807297/107327331-efe9d200-6ae7-11eb-8108-0931584e7ecf.png)
