### ISSUE TITLE
支付宝分包后，跳转到分包页面提示无法找到

### ISSUE THREAD

**Issue by unforesndprson** [NervJS/taro#8659]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/unforesndprson/Taro3-issues-code.git](https://github.com/unforesndprson/Taro3-issues-code.git)
**小程序基础库: 1.24.10**
**使用框架: Vue 3**

### 复现步骤
点击首页to second
报错： Error: framework error: can not find page: packageSecond/pages/second/index when execute navigateTo for url /packageSecond/pages/second/index

### 期望结果
分包功能正常使用

### 实际结果
分包功能异常，访问分包页面提示无法找到

### 环境信息
```

  Taro CLI 3.0.26 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26 
      @tarojs/mini-runner: 3.0.26 => 3.0.26 
      @tarojs/runtime: 3.0.26 => 3.0.26 
      @tarojs/taro: 3.0.26 => 3.0.26 
      @tarojs/webpack-runner: 3.0.26 => 3.0.26 
      babel-preset-taro: 3.0.26 => 3.0.26 
      eslint-config-taro: 3.0.26 => 3.0.26 
```

---
### 补充信息
微信小程序分包功能正常

**Comment by Chen-jj** [comment]
https://github.com/unforesndprson/Taro3-issues-code/blob/27ccd825be524807210344f9ca629c6ad6ee213f/src/app.config.ts#L5

p 大写，`subPackages`
