### ISSUE TITLE
echarts-for-weixin使用柱状图出错

### ISSUE THREAD

**Issue by NotMeIsMe** [NervJS/taro#866]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
之前做的小程序版本正常使用echarts的柱状图和饼状图组件，现在用taro框架重新开发时，发现柱状图报错，而饼状图正常可用。

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]
//这个是柱状图的option，使用报错。但是换成饼状图成功。
var option = {
    xAxis: {
      type: 'category',
      name: '年/月',
      data: ['17-11', '17-12', '18-01', '18-02', '18-03', '18-04', '18-05'],
      axisLabel: {
        interval: 0,
        fontSize: 11
      }
    },
    yAxis: {
      type: 'value',
      name: '千万元'
    },
    series: [{
      data: [6, 7, 8, 8, 7, 8, 6],
      type: 'bar',
      barCategoryGap: '50%',
      itemStyle: {
        color: 'rgb(255, 232, 206)'
      }
    }]
  };

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
同小程序一致，正常使用柱状图
**报错信息**

[这里请贴上你的**完整**报错截图或文字]
![image](https://user-images.githubusercontent.com/25151331/47072549-d9d5ea80-d228-11e8-849a-92c6679dbc05.png)
**系统信息**

 - 操作系统: [ Windows 10]
 - Taro 版本 [v.1.0.7]
 - Node.js 版本 [e.g. v8.9.3]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
能否提供一下完整的代码，我们这边调试一下
