### ISSUE TITLE
@tarojs/plugin-terser 插件运行不起来

### ISSUE THREAD

**Issue by guanrongjia** [NervJS/taro#8662]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/NervJS/](https://github.com/NervJS/)
**小程序基础库: 3/5**
**使用框架: React**

### 复现步骤
在 config/index.js 里面添加 plugins ： @tarojs/plugin-terser 之后，就直接报错

### 期望结果
正常运行

### 实际结果
报错

### 环境信息
```
guanjia-MacBook-Pro:techang-baojia-miniapp guanrongjia$ taro info
👽 Taro v3.0.26


  Taro CLI 3.0.26 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.26 => 3.0.26 
      @tarojs/components: ^3.0.26 => 3.0.26 
      @tarojs/mini-runner: ^3.0.26 => 3.0.26 
      @tarojs/react: ^3.0.26 => 3.0.26 
      @tarojs/runtime: ^3.0.26 => 3.0.26 
      @tarojs/taro: ^3.0.26 => 3.0.26 
      @tarojs/webpack-runner: ^3.0.26 => 3.0.26 
      babel-preset-taro: ^3.0.26 => 3.0.26 
      eslint-config-taro: ^3.0.26 => 3.0.26 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: ^16.10.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.1 => 3.0.0-alpha.1 
    npmGlobalPackages:
      typescript: 3.9.7
```

---
### 补充信息
1、 config/index.js 里面添加了如下的配置
  plugins: [
    '@tarojs/plugin-terser',
  ],

2、报错信息：
(node:22245) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization.minimizer[0] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.
    at webpack (/Users/guanrongjia/gitData/techang-baojia-miniapp/node_modules/@tarojs/mini-runner/node_modules/webpack/lib/webpack.js:31:9)
    at /Users/guanrongjia/gitData/techang-baojia-miniapp/node_modules/@tarojs/mini-runner/src/index.ts:40:22
    at new Promise (<anonymous>)
    at /Users/guanrongjia/gitData/techang-baojia-miniapp/node_modules/@tarojs/mini-runner/src/index.ts:39:10
    at Generator.next (<anonymous>)
    at fulfilled (/Users/guanrongjia/gitData/techang-baojia-miniapp/node_modules/@tarojs/mini-runner/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:22245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by luckyadam** [comment]
taro3 不需要这个插件，taro3 的文档也没提到这个插件吧

**Comment by youyiqin** [comment]
确实，taro2 提到了这个插件，原文是`自Taro 2.2.8 开始，Taro 将JS 代码压缩处理抽离成了Taro 插件，Taro 自身默认不具备代码压缩能力，需要使用安装相应插件才行。`，到了3就是改了。

**Comment by ruihanma** [comment]
所以2x版本就不管了么？
