### ISSUE TITLE
微信小程序地图组件update事件何时触发？

### ISSUE THREAD

**Issue by yinfeiru** [NervJS/taro#8677]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
1. taro脚手架创建项目
2. 用以下代码覆盖pages/index/index.tsx
3. 程序运行后点击"click me"按钮并查看console log

```
import React, { useState, useEffect } from "react";
import { View, Map } from "@tarojs/components";
import "./index.scss";

const MyMap = () => {
  useEffect(() => {
    console.log("MyMap useEffect");
  });
  return (
    <Map
      longitude={113}
      latitude={23}
      onUpdated={() => console.log("onUpdated")}
    />
  );
};

const MemoizedMap = React.memo(
  () => {
    console.log("MemoizedMap intialized");
    return <MyMap />;
  },
  () => true
);

const Index: React.FC<{}> = ({}) => {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    console.log("Index");
  });

  return (
    <View className="index">
      <View
        onClick={() => setIsVisible(!isVisible)}
        style="border: 1px solid black;"
      >
        click me
      </View>
      {isVisible && <View>312</View>}
      <MemoizedMap />
    </View>
  );
};

export default Index;
```

### 期望结果
在点击"click me"时候`onUpdated`不被调用

### 实际结果
在点击"click me"时候console.log里面看到多次onUpdated

### 环境信息
```
👽 Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.9.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.26 => 3.0.26 
      @tarojs/components: 3.0.26 => 3.0.26 
      @tarojs/mini-runner: 3.0.26 => 3.0.26 
      @tarojs/react: 3.0.26 => 3.0.26 
      @tarojs/runtime: 3.0.26 => 3.0.26 
      @tarojs/taro: ^3.0.26 => 3.0.26 
      @tarojs/webpack-runner: 3.0.26 => 3.0.26 
      babel-preset-taro: 3.0.26 => 3.0.26 
      eslint-config-taro: 3.0.26 => 3.0.26 
      react: ^16.10.0 => 16.14.0 

```

---
### 补充信息
React和Taro我都接触的不是特别多，以上现象我没有搞太懂。

根据React文档，如果`React.memo`的depencies没有更改，那么它包裹的组件应该不会re-render。从console.log可以看出，`MyMap useEffect`只在app最初render的时候打印过一次，所以和文档描述是相符合的。但是我不太理解的是为什么`onUpdated`会打印多次。Taro文档中说这个事件只会`在地图渲染更新完成时触发`，所以打印多次说明Map组件被render了多次吗？为什么`MyMap useEffect`没有打印多次？跟`Map`是原生组件有关系吗？

**Comment by Chen-jj** [comment]
@yinfeiru 和原生组件有关，`<map>` 组件的确触发了5次 `bindupdate`。

经测试发现，设置这些属性时，各会触发一次 `bindupdate`：polyline、polygons、markers、circles

可以使用这段原生代码进行测试：

```html
<map longitude="113" latitude="23" polyline="{{[]}}" polygons="{{[]}}" markers="{{[]}}" circles="{{[]}}" bindupdated="eh"></map>
```

由于 Taro3 会把组件的所有属性都提前列出，也就是说 `<map>` 组件的所有属性都会提前写死，也就会包括了上述4个属性，导致 `bindupdate` 在初始化时共触发了 5 次。

**Comment by yinfeiru** [comment]
@Chen-jj 多谢回答，一个followup问题，我有一个组件是类似这样的
```
<View>
  {isVisible && <View>test</View>}
  <MemoizedMap />
</View>
```
如果我改变`isVisible`的值 `test`这个`View`会相应的`mount`和`unmount` 这个动作进而会触发`MemoizedMap`的onUpdate 说明地图组件重新进行了渲染（即使我用`React.memo`封装了`Map`也是这样 参考这个上面提问中的例子） 所以我现在的临时解决办法是对test进行了封装 在这个组件里面通过`height: 0`来控制是否显示 由于对于外层的`View`来说这个test组件一直在页面上 所以不会触发外层`View`的重新渲染 也就不会影响`MemoizedMap` 不过写起来总是有点怪... 你知道什么解决方案可以避免一个silibling在`mount` `unmount`时触发`Map`渲染吗？
