### ISSUE TITLE
内联style， 样式属性驼峰模式h5模式下无效？

### ISSUE THREAD

**Issue by mayacger** [NervJS/taro#8678]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 2.14.3**
**使用框架: React**

### 复现步骤

<View className='index' style={{ backgroundColor: '#00000' }}>
        <Button className='add_btn' onClick={this.props.add}> </Button>
        <Button className='dec_btn' onClick={this.props.dec}>-</Button>
        <Button className='dec_btn' onClick={this.props.asyncAdd}>async</Button>
        <View><Text>{this.props.counter.num}</Text></View>
        <View><Text>Hello, World</Text></View>
      </View>

### 期望结果
背景为黑色

### 实际结果
实际dom中无style

### 环境信息
```
Taro CLI 3.1.0-beta.6 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.1.0-beta.6 => 3.1.0-beta.6 
      @tarojs/mini-runner: 3.1.0-beta.6 => 3.1.0-beta.6 
      @tarojs/react: 3.1.0-beta.6 => 3.1.0-beta.6 
      @tarojs/runtime: 3.1.0-beta.6 => 3.1.0-beta.6 
      @tarojs/taro: 3.1.0-beta.6 => 3.1.0-beta.6 
      @tarojs/webpack-runner: 3.1.0-beta.6 => 3.1.0-beta.6 
      babel-preset-taro: 3.1.0-beta.6 => 3.1.0-beta.6 
      eslint-config-taro: 3.1.0-beta.6 => 3.1.0-beta.6 
      react: ^16.10.0 => 16.14.0 
```

---
### 补充信息
style={{ 'background-color': '#00000' }}
这样在h5下，生效但是小程序端就无效了

taro init 的文件，不要再要github地址

**Comment by bgy10** [comment]
你确定黑色是5个0，不是6个？或简写3个

**Comment by mayacger** [comment]
这是5个0问题是手误，但是我测试了驼峰都不行，我目前在项目里所有用style为驼峰的属性被迫写两边

**Comment by SyMind** [comment]
最新版本已无法复现。

**Comment by Chen-jj** [comment]
3.1.0-beta.6 的确有问题，下一个版本修复。
