### ISSUE TITLE
本地的font文件没有转成base64

### ISSUE THREAD

**Issue by kscript** [NervJS/taro#868]
**问题描述**
1.0.2可以正常显示字体图标, 替换为1.0.7后, 在小程序里报错。
查看了下 app.wxss 文件, 使用1.0.7时, 没有将本地文件转成base64

**报错信息**
Failed to load local font resource /assets/fonts/iconfont.ttf?t=1539075433984-do-not-use-local-path-./app.wxss&880&7 net::ERR_CACHE_MISS

**系统信息**
 - 操作系统: window7
 - Taro 版本 1.0.7
 - Node.js 版本 10.10.0
 - 报错平台 weapp

**Comment by luckyadam** [comment]
@kscript 
这个配置之前有过调整~ https://nervjs.github.io/taro/docs/config-detail.html#weappmodule
![image](https://user-images.githubusercontent.com/1782542/47075497-42c06100-d22f-11e8-9d5f-4ce8ba14a48a.png)

**Comment by kscript** [comment]
好的, 可以了

**Comment by likeDoMine** [comment]
我在1.2.0-beta.3版本上还是遇到了这个问题，字体文件下载到版本，总字体大小不超过10KB， 打包出来依然没有变成base64， 报路径错误; 配置config->index.js` weapp: {
      module: {
          postcss: {
              // 小程序端样式引用本地资源内联
              url: {
                  enable: true,
                  config: {
                      limit: 10240 // 设定转换尺寸上限
                  }
              }
          }
      }
  },`

**Comment by fuguxu** [comment]
我把limit改成了10240000，远远大于字体文件 但还是没有转成base64 ，求解！！引用的是
font-awesome图标
