### ISSUE TITLE
最新版3.2.0-canary.8 tabBar加载图片icon失败

### ISSUE THREAD

**Issue by rockey2020** [NervJS/taro#8680]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
**### app.config.js配置**
const index = 'pages/index/index'
const message = 'pages/message/index'
const follow = 'pages/follow/index'
const mine = 'pages/mine/index'
export default {
  pages: [
    index,
    message,
    follow,
    mine
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '陌陌',
    navigationBarTextStyle: 'black'
  },
  tabBar: {
    // color: "#333434",
    // selectedColor: "#ebad3b",
    // backgroundColor: "#ffffff",
    list: [
      {
        pagePath: index,
        text: "首页",
        iconPath: "./assets/icons/home_after.png",
        selectedIconPath: "./assets/icons/home.png",
      },
      {
        pagePath: message,
        text: "消息",
        // iconPath: "assets/icons/message_after.png",
        // selectedIconPath: "assets/icons/message.png",
      },
      {
        pagePath: follow,
        text: "关注",
        // iconPath: "assets/icons/follow_after.png",
        // selectedIconPath: "assets/icons/follow.png",
      },
      {
        pagePath: mine,
        text: "我的",
        // iconPath: "assets/icons/mine_after.png",
        // selectedIconPath: "assets/icons/mine.png",
      },
    ]
  }
}

**### 目录结构**
![image](https://user-images.githubusercontent.com/64777114/108050568-ba635c80-7084-11eb-9791-201215bd92cf.png)

**### 错误信息**
![image](https://user-images.githubusercontent.com/64777114/108050602-ccdd9600-7084-11eb-924d-72fbff94d279.png)
![image](https://user-images.githubusercontent.com/64777114/108050637-d8c95800-7084-11eb-955d-51d52c62c2a7.png)

### 期望结果
正常加载图片

### 实际结果
加载图片失败
Could not find image file:///Users/rockey/Library/Developer/CoreSimulator/Devices/31DD2ECD-06AD-4D6E-B5A3-90D55CCC291D/data/Containers/Bundle/Application/18F3AE54-8EFB-422F-801D-4836DB6FF2FF/taroDemo.app/./assets/icons/home.png

### 环境信息
```
👽 Taro v3.2.0-canary.8


  Taro CLI 3.2.0-canary.8 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/mini-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/react: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/runtime: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/webpack-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      babel-preset-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      eslint-config-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      react: ^16.10.0 => 16.14.0 
      react-native: ^0.63.4 => 0.63.4 

```

**Comment by yechunxi** [comment]
在react native端 , tabbar的图片资源和小程序端是存在差异，仅支持网络资源图片或者base64
