### ISSUE TITLE
input focus无效

### ISSUE THREAD

**Issue by wukuy** [NervJS/taro#8693]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/](https://gitee.com/)
**小程序基础库: 2.15.0**
**使用框架: Vue 3**

### 复现步骤
```javascript
<template>
    {{ focus }}
    <input :focus="focus" />
    <input type="text" placeholder="将会获取焦点" focus/>
</template>


export default ({
    setup() {
           const state = reactive({
              focus: false
        })


        setTimeout(() => {
            state.focus = true
        }, 3000);

        return {
             ...toRefs(state)
        };
    },
})

```

### 期望结果
希望focus变量为true时，获取焦点

### 实际结果
当focus变量为true时，没有获取焦点

### 环境信息
```
👽 Taro v3.0.24


  Taro CLI 3.0.24 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /opt/node/bin/node
      Yarn: 1.22.10 - /opt/node/bin/yarn
      npm: 6.14.10 - /opt/node/bin/npm
    npmPackages:
      @tarojs/components: 3.0.24 => 3.0.24 
      @tarojs/mini-runner: 3.0.24 => 3.0.24 
      @tarojs/runtime: 3.0.24 => 3.0.24 
      @tarojs/taro: 3.0.24 => 3.0.24 
      @tarojs/webpack-runner: 3.0.24 => 3.0.24 
      babel-preset-taro: 3.0.24 => 3.0.24 
      eslint-config-taro: 3.0.24 => 3.0.24 
      taro-ui: ^2.3.4 => 2.3.4 
```

---
### 补充信息
已在原生小程序focus属性测试正常

**Comment by liaokaime** [comment]
同上

**Comment by wukuy** [comment]
没人解决吗？都十多天了

**Comment by liaokaime** [comment]
放心，再等十多天

**Comment by liaokaime** [comment]
> 放心，再等十多天

对不起，是我太乐观了

**Comment by wukuy** [comment]
没人解决， 也没有另外的方案

**Comment by wukuy** [comment]
hold不住呀，得看他们源码自己搞， 京东是不是缺人？

**Comment by liaokaime** [comment]
你可以用原生input来写，这是有效的

**Comment by ItsRyanWu** [comment]
> 你可以用原生input来写，这是有效的

@liaokaime 请问如何用原生 input 来写，在文档中我只看到可以生命引用原生自定义组件，但如果要引用原生内置组件如 input 这种，貌似没有一个途径？

**Comment by liaokaime** [comment]
原生无须import任何东西，只需要写 <input/> 标签就行，注意是小写。有可能编辑器会报警，但编译是能通过的。

**Comment by ItsRyanWu** [comment]
> 原生无须import任何东西，只需要写 `<input/>` 标签就行，注意是小写。有可能编辑器会报警，但编译是能通过的。

@liaokaime 那样的话会被 input Taro 自动封装一层，无法达到绕过 Taro 内部 bug 的目的

**Comment by liaokaime** [comment]
不会呀，我试过是行的

**Comment by wukuy** [comment]
> 不会呀，我试过是行的

vue3 可以吗?

**Comment by Chen-jj** [comment]
@wukuy 显式给第二个 input 绑定 `:focus=true` 应该就可以了：

```html
<input :focus="focus" />
<input type="text" placeholder="将会获取焦点" :focus="true" />
```

真机测试结果，上述 Demo 一开始 input 2 focus，然后 setTimeout 触发后 input 1 focus。

只写 `focus` 没有设置成功，是因为 vue 是这样调用 DOM API 的： `HTMLElement.setAttribute('focus', '')`。

这样在 H5 是 ok 的，但在小程序中，Taro 不知道应该为 focus 属性 setData 为 `true` 还是空字符串。

所以目前先 Vue 里面 Boolean 值的属性需要显式设置，我们补充一下文档。

**Comment by liaokaime** [comment]
噢，我用的react，所以结果和你不一样

**Comment by Chen-jj** [comment]
@liaokaime React 可以的，focus 在真机才有效果

**Comment by ItsRyanWu** [comment]
> @wukuy 显式给第二个 input 绑定 `:focus=true` 应该就可以了：
> 
> ```
> <input :focus="focus" />
> <input type="text" placeholder="将会获取焦点" :focus="true" />
> ```
> 
> 真机测试结果，上述 Demo 一开始 input 2 focus，然后 setTimeout 触发后 input 1 focus。
> 
> 只写 `focus` 没有设置成功，是因为 vue 是这样调用 DOM API 的： `HTMLElement.setAttribute('focus', '')`。
> 
> 这样在 H5 是 ok 的，但在小程序中，Taro 不知道应该为 focus 属性 setData 为 `true` 还是空字符串。
> 
> React 则是调用 `HTMLElement.setAttribute('focus', true)`，这时 Taro 能正确解析。
> 
> 所以目前在 Vue 中 `Boolean` 值的属性需要显式设置，我们补充一下文档。

@Chen-jj
你是否用 Vue 3 在测试 Taro 3? 在我的测试中上述 input 1 与 2 无论真机还是模拟器都无作用
我的 issue 在这里：https://github.com/NervJS/taro/issues/8991

**Comment by Chen-jj** [comment]
@ItsRyanWu 是 Vue3，我看看

**Comment by wukuy** [comment]
> @wukuy 显式给第二个 input 绑定 `:focus=true` 应该就可以了：
> 
> ```
> <input :focus="focus" />
> <input type="text" placeholder="将会获取焦点" :focus="true" />
> ```
> 
> 真机测试结果，上述 Demo 一开始 input 2 focus，然后 setTimeout 触发后 input 1 focus。
> 
> 只写 `focus` 没有设置成功，是因为 vue 是这样调用 DOM API 的： `HTMLElement.setAttribute('focus', '')`。
> 
> 这样在 H5 是 ok 的，但在小程序中，Taro 不知道应该为 focus 属性 setData 为 `true` 还是空字符串。
> 
> React 则是调用 `HTMLElement.setAttribute('focus', true)`，这时 Taro 能正确解析。
> 
> 所以目前在 Vue 中 `Boolean` 值的属性需要显式设置，我们补充一下文档。

这不是使用组件的问题，我都测试了一上午了。
请使用vue3测试下@Chen-jj

**Comment by ItsRyanWu** [comment]
@wukuy 升级 Taro 至 v3.2.1 可修复此问题

**Comment by zx69** [comment]
更新到3.2.8都没有修复

**Comment by shenmissing** [comment]
> 更新到3.2.8都没有修复

先用这个可以 ref.current.setAttribute('focus', true)

**Comment by shenmissing** [comment]
@zx69 先用这个可以 ref.current.setAttribute('focus', true)

**Comment by ItsRyanWu** [comment]
@Chen-jj 该 BUG 在 3.2.10 里再次出现，Vue 3 模式，主要表现为只能主动聚焦 1 次，在 blur 之后无法再次通过 `:focus` 参数主动聚焦
