### ISSUE TITLE
配置preset时插件执行顺序问题

### ISSUE THREAD

**Issue by landn172** [NervJS/taro#8703]
### 相关平台
H5

### 复现仓库
[https://github.com/landn172/taro-bug](https://github.com/landn172/taro-bug)
**浏览器版本: no**
**使用框架: React**

### 复现步骤
https://github.com/NervJS/taro/blob/818bc8d852c4215385c164c99a919620c1cccef0/packages/taro-service/src/Kernel.ts#L109-L110

https://taro-docs.jd.com/taro/docs/plugin#presets

使用编译配置的`preset`时报错

### 期望结果
按照正常的执行顺序
> initConfig.presets -> this.optsPresets  -> initConfig.plugins -> this.optsPlugins

### 实际结果
> this.optsPresets -> initConfig.presets ->  this.optsPlugins -> initConfig.plugins 
导致插件获取不到`modifyWebpackChain`等api而报错

### 环境信息
```
Taro CLI 3.0.27 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.20.1 - /var/folders/q7/7yynh_d92xv4r5zmcfcmn61c0000gp/T/yarn--1613824102499-0.7607019405389654/node
      Yarn: 1.22.10 - /var/folders/q7/7yynh_d92xv4r5zmcfcmn61c0000gp/T/yarn--1613824102499-0.7607019405389654/yarn
      npm: 6.14.10 - /usr/local/opt/node@12/bin/npm
```

**Comment by Chen-jj** [comment]
最新版本不存在此问题了
