### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by rockey2020** [NervJS/taro#8704]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
[Sun Feb 21 2021 02:29:34.860]  BUNDLE  ./index 

error: node_modules/metro/src/node-haste/DependencyGraph/assets/empty-module.js: Unexpected token 'export'

### 期望结果
正常运行app

### 实际结果
编译正常,运行报错

### 环境信息
```
👽 Taro v3.2.0-canary.8


  Taro CLI 3.2.0-canary.8 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/mini-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/react: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/runtime: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/webpack-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      babel-preset-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      eslint-config-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      react: ^17.0.1 => 17.0.1 
      react-native: ^0.63.4 => 0.63.4 
```

---
### 补充信息
index文件代码

```
import React, {Component} from 'react'
import {connect} from 'react-redux'
import {View, Text} from '@tarojs/components'

import './index.less'

@connect()
class Index extends Component {
  render() {
    return (
      <View className='index'>
        <View><Text>首页</Text></View>
      </View>
    )
  }
}

export default Index
```

**Comment by rockey2020** [comment]
![image](https://user-images.githubusercontent.com/64777114/108605419-f2550180-73ee-11eb-84d6-2e0aa8d564db.png)
![image](https://user-images.githubusercontent.com/64777114/108605427-f97c0f80-73ee-11eb-9495-b38fa1764ee5.png)
找到原因了,是因为app.config.js里面有import导致的

请问为啥不支持export?不应该都是支持的吗

**Comment by yechunxi** [comment]
目前config文件中的是不支持import，可采用require的方式

**Comment by rockey2020** [comment]
@yechunxi 也尝试过require  本地的png无法加载  只能先转base64  将字符串作为icon展示  才可以

**Comment by rockey2020** [comment]
@yechunxi https://github.com/rockey2020/bwrbawrbae 这个代码demo

**Comment by yechunxi** [comment]
> @yechunxi 也尝试过require 本地的png无法加载 只能先转base64 将字符串作为icon展示 才可以

如果是tabbar的图片，目前是支持网络图片和base64, 本地的图片目前是不支持的

**Comment by rockey2020** [comment]
@yechunxi 感谢解答
