### ISSUE TITLE
3.2.0-canary.8版本启动dev h5  打开链接是HTTP ERROR 503

### ISSUE THREAD

**Issue by rockey2020** [NervJS/taro#8707]
### 相关平台
H5

**浏览器版本: 87.0.4280.88**
**使用框架: React**

### 复现步骤
启动 
    "dev:h5": "npm run build:h5 -- --watch --port 8081",

### 期望结果
正常打开网页

### 实际结果
http错误 503

### 环境信息
```
 Taro v3.2.0-canary.8


  Taro CLI 3.2.0-canary.8 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/mini-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/react: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/runtime: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      @tarojs/webpack-runner: 3.2.0-canary.8 => 3.2.0-canary.8 
      babel-preset-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      eslint-config-taro: 3.2.0-canary.8 => 3.2.0-canary.8 
      react: ^17.0.1 => 17.0.1 
      react-native: ^0.63.4 => 0.63.4 


```

**Comment by rockey2020** [comment]
![image](https://user-images.githubusercontent.com/64777114/108636372-c6ee1780-74bf-11eb-9775-1c1e6913f94f.png)

**Comment by zhiqingchen** [comment]
麻烦提供下，可复现demo

**Comment by zhiqingchen** [comment]
h5的端口需要通过webpack配置修改

https://taro-docs.jd.com/taro/docs/config-detail#h5devserver

**Comment by rockey2020** [comment]
@zhiqingchen https://github.com/rockey2020/bwrbawrbae  这个代码demo  
devServer一直用的是默认端口 也尝试过更改端口 一样不可以运行

**Comment by zhiqingchen** [comment]
> @zhiqingchen https://github.com/rockey2020/bwrbawrbae 这个代码demo
> devServer一直用的是默认端口 也尝试过更改端口 一样不可以运行


h5 iconPath 和 selectedIconPath 不支持 base64 图片
