### ISSUE TITLE
升级Taro3.x主包中vendor变大的问题

### ISSUE THREAD

**Issue by yuluotuxi** [NervJS/taro#8712]
从taro v2.14.3 升级至 taro v3.2.0-canary.3  
刚升级后包的大小扩大一倍，通过以下方式减少主包大小：
1、 使用splitChunks和addChunkPages分包
2、 预览模式生成的文件较大，设置 NODE_ENV 为 production 开启压缩。
3、使用terser-webpack-plugin，体积反而变大了，弃用

目前仍然存在vendor体积过大的问题导致主包大小超过2M。
 v2.14.3：升级前npm依赖大小
![image](https://user-images.githubusercontent.com/23314558/108653539-a34bc100-7501-11eb-90ed-e2662e335469.png)

v3.2.0-canary.3  ： 升级后依赖包大小：
![image](https://user-images.githubusercontent.com/23314558/108653243-eeb19f80-7500-11eb-9423-28cb95786eab.png)

比较两个版本依赖包，发现新包依赖的数量比之前依赖数量变多：
![image](https://user-images.githubusercontent.com/23314558/108653448-6bdd1480-7501-11eb-8370-6be2c923669f.png)

= = 目前要怎么减小vender依赖的大小

**Comment by shenghanqin** [comment]
俺也听一下

**Comment by digiaries** [comment]
看看这个 [#8169](https://github.com/NervJS/taro/issues/8169)

**Comment by Chen-jj** [comment]
Duplicate of #8169
