### ISSUE TITLE
LivePusher的方法onAudioVolumeNotify 在3.0.26版本触发不了，2.1.5版本可以

### ISSUE THREAD

**Issue by mogiihu** [NervJS/taro#8714]
### 这个特性解决了什么问题？
监听 LivePusher 音量变化

### 这个 API 长什么样？
期望与 2.1.5 版本一致

**Comment by mogiihu** [comment]
![image](https://user-images.githubusercontent.com/32658698/108692165-3e12c280-7537-11eb-9043-ca6f155df73a.png)
上图为原代码，在 2.1.5 版本可以正常触发 onAudioVolumeNotify，在 3.0.26 版本触发不了，文档也没有此属性，经过 taro3 编译过后的代码如下图：
![image](https://user-images.githubusercontent.com/32658698/108692112-2f2c1000-7537-11eb-939c-572d4f94f4bd.png)

**Comment by Chen-jj** [comment]
> ![image](https://user-images.githubusercontent.com/32658698/108692112-2f2c1000-7537-11eb-939c-572d4f94f4bd.png)

@mogiihu 截图的绑定语法没错吧。

进入 dist/taro.js 搜索 `eventHandler`（它就是模板绑定的回调 'eh'），看看是否有触发此回调函数。

![image](https://user-images.githubusercontent.com/11807297/109153174-833d2b80-77a7-11eb-99bd-707425342c52.png)

如果没有触发，意思是小程序本身就没有触发事件。

如果成功触发，打印一下 event 参数看看。

**Comment by mogiihu** [comment]
请问通过bindaudiovolumenotify触发的event type的值什么

**Comment by mogiihu** [comment]
https://github.com/NervJS/taro/issues/8363 这个issue 上提到 3.1.0-beta.5 + 开始支持，那 3.0.26 确实是不支持了

**Comment by Chen-jj** [comment]
> 请问通过bindaudiovolumenotify触发的event type的值什么

要看小程序了，应该是 `audiovolumenotify`

升级到最新版本再看看吧，应该是没有问题的
