### ISSUE TITLE
在iOS浏览器中Input的type="number"无效

### ISSUE THREAD

**Issue by ryougifujino** [NervJS/taro#8715]
### 相关平台
H5

**浏览器版本: Safari 14**
**使用框架: React**

### 复现步骤
任意`<Input type="number" />`在iOS的浏览器中不能限制为只输入数字，由于Input标签中没有pattern属性，所以也不同通过设置pattern来限制输入数字。

### 期望结果
` type="number"`生效或者在Input标签中提供pattern属性

### 实际结果
` type="number"`在iOS浏览器中不生效，Input没有pattern属性

### 环境信息
```
Taro v3.0.14


  Taro CLI 3.0.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
可以用iPhone在http://jsfiddle.net/Cy4aC/3/ 这个地址下发现仅仅是`<input type="number" />`在iOS浏览器下是不能限制为输入数字的，而Taro编译后的元素及其属性就是这样。

**Comment by JferLao** [comment]
![image](https://user-images.githubusercontent.com/43103453/109109133-bc59a980-776f-11eb-96b0-f26f431720ef.png)
这个问题有人解决过吗 只有在ios情况下type为number可以输入非数字

**Comment by RichardDegeneres** [comment]
h5
浏览器版本:  chrome 88.0.4324.146
taro版本:  3.0.26

type='number' 也无效

**Comment by ZakaryCode** [comment]
这里辅助设置 type 类型，根据浏览器实现会有不同，暂不考虑针对次优化
