### ISSUE TITLE
H5 Swiper多个 SwiperItem时，渲染出问题

### ISSUE THREAD

**Issue by NyanShen** [NervJS/taro#8729]
### 相关平台
H5

**浏览器版本: Chrome 88.0.4324.96**
**使用框架: React**

### 复现步骤
Swiper数据通过异步请求后setState,渲染时出现SwiperItem渲染不正常，HTML查看有重复的SwiperItem出现
`
import Nerv from 'nervjs'
import { useEffect, useState } from 'react'
import { View, Text, Swiper, SwiperItem, Image } from '@tarojs/components'
import './index.scss'

interface IAlbumSwiper {
  albumTabs: any[],
  albumItems: any[],
  swiperIndex: number,
  imageCount: number
}

const INIT_ALBUM_SWIPER = {
  albumTabs: [],
  albumItems: [],
  swiperIndex: 0,
  imageCount: 0
}

const Index = () => {
  const [albumSwiper, setAlbumSwiper] = useState<IAlbumSwiper>(INIT_ALBUM_SWIPER)

  useEffect(() => {
    app.request({
            url: app.areaApiUrl(api.getHouseById),
            data: {
                id: params.id
            }
        }).then((result: any) => {
            
            const video = result.imagesData.video
            if (video) {
                setAlbumSwiper({
                    albumTabs: [{ name: '视频' }, { name: '图片' }],
                    albumItems: [video, { image_path: result.image_path }],
                    swiperIndex: 0
                })
            } else {
                setAlbumSwiper({
                    albumTabs: [{ name: '图片' }],
                    albumItems: [{ image_path: result.image_path }],
                    swiperIndex: 0
                })
            }
           
        })
  }, [])

  const onSwiperChange = (event: any) => {
    const swiperIndex = event.detail.current
    setAlbumSwiper({
      ...albumSwiper,
      swiperIndex
    })
  }

  const switchAlbum = (swiperIndex: number) => {
    if (albumSwiper.swiperIndex === swiperIndex) {
      return
    }
    setAlbumSwiper({
      ...albumSwiper,
      swiperIndex
    })
  }

  return (
    <View className="house-album">
      <Swiper
        style={{ height: '250px' }}
        current={albumSwiper.swiperIndex}
        onChange={onSwiperChange}
      >
        {
          albumSwiper.albumItems.map((item: any, index: number) => {
            return item.video_path ?
              <SwiperItem key={index}>
                <Image className="taro-image" src={item.image_path}></Image>
                <Text className="icon-vedio"></Text>
              </SwiperItem> :
              <SwiperItem key={index}>
                <Image className="taro-image" src={item.image_path}></Image>
              </SwiperItem>
          })
        }
      </Swiper>
      <View className="album-count">共{albumSwiper.imageCount}张</View>
      <View className="album-text">
        {
          albumSwiper.albumTabs.map((item: any, index: number) => (
            <Text
              key={index}
              className='album-text-item'
              onClick={() => switchAlbum(index)}
            >{item.name}</Text>
          ))
        }
      </View>
    </View>
  )
}

export default Index

`

### 期望结果
可以正常切换SwiperItem

### 实际结果
不能正常切换SwiperItem

### 环境信息
```

Taro v3.0.25


  Taro CLI 3.0.25 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.10.0 - E:\installation\node12.10\node.EXE
      npm: 6.10.3 - E:\installation\node12.10\npm.CMD

```

**Comment by NyanShen** [comment]
补充代码显示
{
                            albumSwiper.albumItems.map((item: any, index: number) => {
                                return item.video_path ?
                                    <SwiperItem key={index} onClick={() => toHouseVideo(item)}>
                                        <Image className="taro-image" src={item.image_path}></Image>
                                        <Text className="icon-vedio"></Text>
                                    </SwiperItem> :
                                    <SwiperItem key={index} onClick={() => toHouseModule('Album')}>
                                        <Image className="taro-image" src={item.image_path}></Image>
                                    </SwiperItem>
                            })
                        }

**Comment by guoseven** [comment]
```jsx
import Nerv from 'nervjs'
import { useEffect, useState } from 'react'
import { View, Text, Swiper, SwiperItem, Image } from '@tarojs/components'
import './index.scss'

interface IAlbumSwiper {
albumTabs: any[],
albumItems: any[],
swiperIndex: number,
imageCount: number
}

const INIT_ALBUM_SWIPER = {
albumTabs: [],
albumItems: [],
swiperIndex: 0,
imageCount: 0
}

const Index = () => {
const [albumSwiperTabs, setAlbumSwiperTabs] = useState([])
const [albumSwiperItems, setAlbumSwiperItems] = useState([])
const [albumSwiperIndex, setAlbumSwiperIndex] = useState(0)
const [imageCount, setImageCount = useState(0)

useEffect(() => {
app.request({
url: app.areaApiUrl(api.getHouseById),
data: {
id: params.id
}
}).then((result: any) => {

        const video = result.imagesData.video
        if (video) {
            setAlbumSwiperTabs([{ name: '视频' }, { name: '图片' }])
            setAlbumSwiperItems([video, { image_path: result.image_path }])
        } else {
            setAlbumSwiperTabs([{ name: '图片' }])
            setAlbumSwiperItems([{ image_path: result.image_path }])
        }
        setAlbumSwiperIndex(0)
       
    })
}, [])

const onSwiperChange = (event: any) => {
const swiperIndex = event.detail.current
    setAlbumSwiperIdex(swiperIndex)
}

const switchAlbum = (swiperIndex: number) => {
  if (albumSwiperIndex === swiperIndex) {
    return
  }
  setAblumSwiperIndex(swiperIndex)
}

return (

<Swiper
style={{ height: '250px' }}
current={albumSwiperIndex}
onChange={onSwiperChange}
>
{
albumSwiperItems.map((item: any, index: number) => {
return item.video_path ?



:



})
}

共{albumSwiperImageCount}张

{
albumSwiperTabs.map((item: any, index: number) => (
<Text
key={index}
className='album-text-item'
onClick={() => switchAlbum(index)}
>{item.name}
))
}


)
}

export default Index
```

**Comment by zhao1251656847** [comment]
### @NyanShen 

- [ ] 

1. 

- 

> ### _`[单**独的的](**url)`_

**Comment by ZakaryCode** [comment]
非 circular 模式下确实会有该问题，将在下一个版本修复
