### ISSUE TITLE
h5 不能build打包 只能--watch预览

### ISSUE THREAD

**Issue by upbill** [NervJS/taro#873]
**问题描述**
taro build --type h5不能打包生成，--watch可正常预览
什么时候可正常使用

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.1.0-beta.9]、v1.0.7都不行]
 - Node.js 版本 [e.g. v10.11.0]
 - 报错平台 [h5]

**Comment by luckyadam** [comment]
报了什么错

**Comment by upbill** [comment]
![image](https://user-images.githubusercontent.com/9735062/47192101-980a8880-d37d-11e8-849e-b9f74f479af8.png)
![image](https://user-images.githubusercontent.com/9735062/47192109-ace71c00-d37d-11e8-9694-0bb79eb34eae.png)
打包完就只有这些

**Comment by upbill** [comment]
![image](https://user-images.githubusercontent.com/9735062/47192204-67771e80-d37e-11e8-8ba9-2b5bbac1b64b.png)
H5 和小程序打包在一起 是否有打包出来到别的路径的方法

**Comment by upbill** [comment]
![image](https://user-images.githubusercontent.com/9735062/47192393-993cb500-d37f-11e8-9797-61e2a9028799.png)

**Comment by luckyadam** [comment]
H5 和小程序目前得分开打包
