### ISSUE TITLE
支付宝小程序插件开发编译报错

### ISSUE THREAD

**Issue by joker-ye** [NervJS/taro#8733]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/NervJS](https://github.com/NervJS)
**小程序基础库: 1.1.0**
**使用框架: React**

### 复现步骤
查了taro的源码，发现编译插件的命令被注释掉了。如下：
// ' --plugin [typename] ' :'Build Taro Plugin...'

### 期望结果
期望尽快支持编译 支付宝小程序插件开发

### 实际结果
实际显示：
请输入正确的编译类型！

### 环境信息
```
 Taro CLI 3.0.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
taro2 貌似还支持，升级到3就不支持了

**Comment by joker-ye** [comment]
麻烦官方大大回复一下，是否能尽快支持一下支付宝插件开发

**Comment by Chen-jj** [comment]
3 还没支持开发插件，而且人力有点紧，Q1 应该还跟进不了

**Comment by Chen-jj** [comment]
3.2.6 支持，#6959
