### ISSUE TITLE
转rn模式之后没有生成rn_temp文件夹

### ISSUE THREAD

**Issue by yezishan** [NervJS/taro#8734]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
taro 版本 3.2.0-canary.3
执行 npm run dev:rn之后，没有看到rn_temp文件夹

### 期望结果
能够看到rn_temp文件夹

### 实际结果
没有看到rn_temp文件夹

### 环境信息
```

� Taro v3.2.0-canary.3


  Taro CLI 3.2.0-canary.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - D:\Data\npm\yarn.CMD
      npm: 6.14.4 - D:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
3.2的方案中，已经去掉了中间层，不需要rn_temp目录了。

**Comment by yezishan** [comment]
那这一步应该怎么处理呢？ @zhiqingchen 

![image](https://user-images.githubusercontent.com/17944506/109109384-325e1080-7770-11eb-948c-8730f263cbea.png)

**Comment by zhiqingchen** [comment]
/rn_temp 去掉，只需要 /index.bundle 文档后续修复。
另外建议升级到最新的 .9 版本

**Comment by gentlecoder** [comment]
2021-03-18 我看官方文档还是没改嘛。。。

**Comment by gaoxianglyx** [comment]
> /rn_temp 去掉，只需要 /index.bundle 文档后续修复。
> 另外建议升级到最新的 .9 版本

请教，如果我们想差分打包，区分平台包和业务包。
应该怎么处理呢？

**Comment by zhiqingchen** [comment]
配置metro.config.js
