### ISSUE TITLE
vue 使用 style CSS variable injection ,驼峰式变量名被解析导致无法生效

### ISSUE THREAD

**Issue by unforesndprson** [NervJS/taro#8736]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/unforesndprson/Taro3-issues-code.git](https://github.com/unforesndprson/Taro3-issues-code.git)
**小程序基础库: 2.15.0**
**使用框架: Vue 3**

### 复现步骤
1.运行小程序
2.两个容器背景色，上面失效，下面生效。

### 期望结果
驼峰式变量名不会被解析

### 实际结果
驼峰式变量名被解析，导致样式失效

### 环境信息
```

  Taro CLI 3.0.26 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26 
      @tarojs/mini-runner: 3.0.26 => 3.0.26 
      @tarojs/runtime: 3.0.26 => 3.0.26 
      @tarojs/taro: 3.0.26 => 3.0.26 
      @tarojs/webpack-runner: 3.0.26 => 3.0.26 
      babel-preset-taro: 3.0.26 => 3.0.26 
      eslint-config-taro: 3.0.26 => 3.0.26 
```

---
### 补充信息
https://github.com/vuejs/rfcs/pull/231#issuecomment-735350576
在使用组合式api，也会遇到上面评论的报错，望大佬能顺手指导下哈。具体写法如下评论
https://github.com/vuejs/rfcs/pull/231#issuecomment-778365539

**Comment by Chen-jj** [comment]
> ### 补充信息
> [vuejs/rfcs#231 (comment)](https://github.com/vuejs/rfcs/pull/231#issuecomment-735350576)
> 在使用组合式api，也会遇到上面评论的报错，望大佬能顺手指导下哈。具体写法如下评论
> [vuejs/rfcs#231 (comment)](https://github.com/vuejs/rfcs/pull/231#issuecomment-778365539)

感觉要等 Vue 社区回复了
