### ISSUE TITLE
建议 rn 和 swan 的配置文件可以像weapp那样可自定义

### ISSUE THREAD

**Issue by tomgao365** [NervJS/taro#874]
taro 目前已支持 ```weapp``` 的 ```project.config.json```(项目根目录)，建议支持 ```rn``` 和 ```swan``` 也支持这样的配置，比如 ```project.rn.json``` ,  ```project.swan.json``` .

**Comment by luckyadam** [comment]
百度小程序会根据 `project.config.json` 自动生成它的配置文件的
支付宝小程序没有项目配置文件，所以不用管

**Comment by tomgao365** [comment]
@luckyadam 百度小程序和微信小程序的 appid 和 libVersion 不一样啊。难道 project.config.json 准备调整？如：
```
{
  "weapp":{},
  "swan":{},
}
```

**Comment by luckyadam** [comment]
`project.swan.json` 会单独生成一份~
https://github.com/NervJS/taro/blob/master/packages/taro-cli/src/weapp.js#L910

**Comment by tomgao365** [comment]
@luckyadam 😂 我没描述清楚。
*  通过 taro 生成的 weapp 和 swan 都有相应的配置文件 project.config.json 和 project.swan.json。
*  其中生成的 weapp 代码中的配置是根据项目根目录的 project.config.json 生成的，没有问题。
*  生成的 swan 代码中的配置都是默认值

项目根目录  project.config.json 
```
{
  "miniprogramRoot": "./dist",
  "projectname": "myApp",
  "description": "demo",
  "appid": "123",
  "setting": {
    "urlCheck": true,
    "es6": false,
    "postcss": false,
    "minified": false
  },
  "compileType": "miniprogram"
}
```
``taro build --type weapp``  生成的 project.config.json 与上面一致
``taro build --type swan``  生成的 project.swan.json 如下
```
{
  "appid": "testappid",
  "setting": {
    "urlCheck": false
  }
}
```
如何指定 swan 的默认配置？

**Comment by luckyadam** [comment]
@tomgao365 有道理~ 看来还是得有分别配置的位置~

**Comment by FrankFan** [comment]
```js
"scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
  }
```

为什么运行`npm run build:swan`之后没有生成`prject.swan.json`文件呢？
