### ISSUE TITLE
Taro上挂载的很多方法都没有了

### ISSUE THREAD

**Issue by yz1311** [NervJS/taro#8751]
### 相关平台
微信小程序

**小程序基础库: 2.12.1**
**使用框架: React**

### 复现步骤
```
Taro.getSystemInfoSync()
```

### 期望结果
正常调用

### 实际结果
TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_0___default.a.getSystemInfoSync is not a function

### 环境信息
```
👽 Taro v3.1.0


  Taro CLI 3.1.0 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.config/yarn/global/node_modules/.bin/npm
    npmPackages:
      @tarojs/components: 3.1.0 => 3.1.0 
      @tarojs/mini-runner: 3.1.0 => 3.1.0 
      @tarojs/react: 3.1.0 => 3.1.0 
      @tarojs/runtime: 3.1.0 => 3.1.0 
      @tarojs/taro: 3.1.0 => 3.1.0 
      @tarojs/webpack-runner: 3.1.0 => 3.1.0 
      babel-preset-taro: 3.1.0 => 3.1.0 
      eslint-config-taro: 3.1.0 => 3.1.0 
      react: ^17.0.0 => 17.0.1 
      taro-ui: ^3.0.0-alpha.9 => 3.0.0-alpha.9 

```

---
### 补充信息
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gnztjd7xlij30i20edq5o.jpg)

**Comment by Chen-jj** [comment]
@yz1311 提供一下 demo

**Comment by yz1311** [comment]
@Chen-jj   demo就不传了，刚测试了下，用cli生成的项目，只要开启prerender，就会出现这个问题，不开启不报错，譬如
```
 prerender: {
            include: [
                'pages/index/index',
            ]
        }
```

**Comment by Chen-jj** [comment]
3.1 prerender 是还有些问题，我们看看

**Comment by laozhu** [comment]
在 app.js 里面的 useMount 周期执行 `Taro.getStorageSync` 和 `loadFontFace` 也找不到了。

**Comment by luoyu-china** [comment]
我从3.0.7升级到3.1.1,也遇到了同样的问题，挂载在Taro上的很多API都没有了，请问这个问题解决了吗？

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/109460556-b3cce000-7a9b-11eb-924a-b3359484153e.png)

**Comment by yz1311** [comment]
> 我从3.0.7升级到3.1.1,也遇到了同样的问题，挂载在Taro上的很多API都没有了，请问这个问题解决了吗？

如果有开启prerender的话，关掉就行了

**Comment by luoyu-china** [comment]
> > 我从3.0.7升级到3.1.1,也遇到了同样的问题，挂载在Taro上的很多API都没有了，请问这个问题解决了吗？
> 
> 如果有开启prerender的话，关掉就行了

没有开启prerender，谢谢

**Comment by luoyu-china** [comment]
之前上级的时候没有删除lock文件，按照@Chen-jj 的步骤操作，可以了，感谢

**Comment by wenh7788** [comment]
同样遇到了这个问题

**Comment by bingtsingw** [comment]
我没有开启prerender，删光了yarn.lock和node_modules还是报错

**Comment by yangxin9527** [comment]
### 全局taro 版本必须和项目中版本一致

如果全局是3.1.5,项目是3.1.4  依旧会有此问题.  必须一致

**Comment by lemondreamtobe** [comment]
同样遇到这个问题 getStorage等api都消失了

**Comment by ouzhou** [comment]
项目依赖了qs, 版本很低，如果后期自己又装了qs就会导致这个问题，把package.json的qs依赖删除，用项目自己依赖的就行
@lemondreamtobe @bingtsingw @wenh7788

**Comment by jonghyun-shinee** [comment]
我使用的taro版本是3.2.1，按照上面说的步骤，提示还是提示getStorageSync is not a function,系统是win10， node版本是12.18.0，求解答

**Comment by zmGitHub** [comment]
> 3.1 prerender 是还有些问题，我们看看

啥时候能解决呢

**Comment by vivialex** [comment]
3.2.10 开发小程序插件
![image](https://user-images.githubusercontent.com/13270284/120680296-b68d0600-c4cc-11eb-864f-3d5c9acc19e5.png)
miniprogram里的taro.js会带上“./node_modules/@tarojs/plugin-platform-weapp/dist/runtime.js”
![image](https://user-images.githubusercontent.com/13270284/120680484-f227d000-c4cc-11eb-8be8-04645b3c60e2.png)
但是plugin里的taro.js并没有带上，导致插件内都调用不了微信的方法

**Comment by zhuanglong** [comment]
同样的问题

**Comment by chinafelix** [comment]
@Chen-jj 你好，我也碰到Taro里的官方API都无法使用的问题；PS：项目已经开发过一段时间，之前是正常的，今天刚出现此问题。

我本人：
项目taro的相关版本是3.2.10； 本地的taro/cli版本是3.1.4     ----->  正常

同事：
同一个项目，npm i -g @taro/cli后，本地taro/cli版本是3.2.11  ------>  报错：_tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default.a.getStorageSync is not a function

之后把项目的taro版本改成3.2.11，没有解决

**Comment by shenghanqin** [comment]
我习惯将cli的版本放到package.json里面，比如我有taro 2和taro3的项目同时在开发。

**Comment by Chen-jj** [comment]
@chinafelix 删掉 lock file 后重装依赖

**Comment by MicrosoftCore** [comment]
> @chinafelix 删掉 lock file 后重装依赖

别老回复让重装啊，能明确指出到底哪个版本是正常的吗

**Comment by Chen-jj** [comment]
> > @chinafelix 删掉 lock file 后重装依赖
> 
> 别老回复让重装啊，能明确指出到底哪个版本是正常的吗

都是正常的，只不过 minor 版本升级，Taro 依赖有较大变动，需要删掉 lock file

**Comment by MicrosoftCore** [comment]
> > > @chinafelix 删掉 lock file 后重装依赖
> > 
> > 
> > 别老回复让重装啊，能明确指出到底哪个版本是正常的吗
> 
> 都是正常的，只不过 minor 版本升级，Taro 依赖有较大变动，需要删掉 lock file

我这边是用 3.2.12新初始化的wxplugin 项目， 从@taro/js/taro下导入 getApp后，打印 getApp是 undefined
![image](https://user-images.githubusercontent.com/27952417/123037119-b2476f00-d420-11eb-8287-bae76fae47dd.png)
![image](https://user-images.githubusercontent.com/27952417/123037145-bc696d80-d420-11eb-9163-0c8d1364dcdf.png)

**Comment by MicrosoftCore** [comment]
> > > > @chinafelix 删掉 lock file 后重装依赖
> > > 
> > > 
> > > 别老回复让重装啊，能明确指出到底哪个版本是正常的吗
> > 
> > 
> > 都是正常的，只不过 minor 版本升级，Taro 依赖有较大变动，需要删掉 lock file
> 
> 我这边是用 3.2.12新初始化的wxplugin 项目， 从@taro/js/taro下导入 getApp后，打印 getApp是 undefined
> ![image](https://user-images.githubusercontent.com/27952417/123037119-b2476f00-d420-11eb-8287-bae76fae47dd.png)
> ![image](https://user-images.githubusercontent.com/27952417/123037145-bc696d80-d420-11eb-9163-0c8d1364dcdf.png)



> > > @chinafelix 删掉 lock file 后重装依赖
> > 
> > 
> > 别老回复让重装啊，能明确指出到底哪个版本是正常的吗
> 
> 都是正常的，只不过 minor 版本升级，Taro 依赖有较大变动，需要删掉 lock file

请问这个有解决办法吗

**Comment by w88975** [comment]
> ### 全局taro 版本必须和项目中版本一致
> 如果全局是3.1.5,项目是3.1.4 依旧会有此问题. 必须一致

我的全局版本和项目依赖版本一致, 还是有此问题, 希望官方修修吧

**Comment by zhangfu-git** [comment]
hi~ 我也遇到相同的问题, 此问题是在我更新了taro-cli的版本导致, 我通过以下方式解决了:
1. `taro -v` 查看`taro-cli `的版本和依赖是否一致, 如果不一致, 更新依赖或者修改taro-cli的版本
2. 保证步骤1版本一致的情况下, 删除`yarn-lock.json `和`node_modules`, `yarn install`重新安装依赖, 如果使用npm安装需要删除`package-lock.json`

**Comment by vivialex** [comment]
最新的taro解决了这个问题了

**Comment by imwangpan** [comment]
3.5.8 同样有这个问题。神奇的是一个项目正常，一个项目会缺 getSystemInfoSync 等方法，两个项目都是从低版本升级上来的。

**Comment by cuicuiworld** [comment]
@tarojs/cli 3.4.14版本build:h5发布之后运行，也出现这个问题，Taro.showToast方法报错。请问一下你是怎么解决的？

**Comment by lemondreamtobe** [comment]
给大家提供一种思路，但凡涉及到了taro api丢失了undefined的原因
基本要么都是打包或者版本不一致，在解决了版本号cli 和 @tarojs都一致的情况下
如果还出现了这个问题，那么原因只有一个，就是runtime里initNativeApi 这个方法缺失了
![image](https://user-images.githubusercontent.com/22766436/236986199-9081e056-8bd0-43df-9e2a-8c0ff0b19929.png)

taro中很多的api都是靠源码的这个地方完成初始化，当我们加载@tarojs/taro会进到这个地方来
但是由于taro版本已经设计，打包策略/分包等诸多原因，可能会导致加载@tarojs/taro会先顺序执行其他的代码，从而导致我们的undefined报错。

那么我们解决问题的方法也很简单，先在我们的src目录下新建一个api.ts
```
import { processApis } from '@tarojs/shared'
export const noPromiseApis = new Set([
    'getAccountInfoSync',
    'getEnterOptionsSync',
    'offBLEPeripheralConnectionStateChanged',
    'offBeaconServiceChange',
    'offBeaconUpdate',
    'offDeviceMotionChange',
    'offHCEMessage',
    'offKeyboardHeightChange',
    'offLocalServiceDiscoveryStop',
    'offLocalServiceFound',
    'offLocalServiceLost',
    'offLocalServiceResolveFail',
    'offLocationChange',
    'offThemeChange',
    'offVoIPChatInterrupted',
    'offVoIPChatMembersChanged',
    'offVoIPVideoMembersChanged',
    'offWifiConnected',
    'offWindowResize',
    'onBLEPeripheralConnectionStateChanged',
    'onBackgroundAudioPause',
    'onBackgroundAudioPlay',
    'onBackgroundAudioStop',
    'onBackgroundFetchData',
    'onHCEMessage',
    'onKeyboardHeightChange',
    'onLocalServiceDiscoveryStop',
    'onLocalServiceFound',
    'onLocalServiceLost',
    'onLocalServiceResolveFail',
    'onLocationChange',
    'onThemeChange',
    'onVoIPChatInterrupted',
    'onVoIPChatMembersChanged',
    'onVoIPChatSpeakersChanged',
    'onVoIPVideoMembersChanged',
    'onWifiConnected',
    'onWindowResize',
    'reportMonitor',
    'onGyroscopeChange',
    'offGyroscopeChange',
    'createAudioContext',
    'createLivePusherContext',
    'createMediaContainer',
    'createMediaRecorder',
    'createOffscreenCanvas',
    'createRewardedVideoAd',
    'createUDPSocket',
    'createVideoDecoder',
    'createWorker',
    'getLogManager',
    'getNFCAdapter',
    'getPerformance',
    'getRealtimeLogManager',
    'pauseBackgroundAudio',
    'pauseVoice',
    'reportPerformance',
    'stopBackgroundAudio',
    'stopRecord',
    'stopVoice',
    'onBluetoothDeviceFound',
    'onBluetoothAdapterStateChange',
    'offBluetoothDeviceFound',
    'offBluetoothAdapterStateChange',
    'onBLEConnectionStateChange',
    'onBLECharacteristicValueChange',
    'offBLEConnectionStateChange',
    'offBLECharacteristicValueChange',
    'onCopyUrl',
    'offCopyUrl'
])

export const needPromiseApis = new Set([
    'addCard',
    'authPrivateMessage',
    'checkIsOpenAccessibility',
    'checkIsSoterEnrolledInDevice',
    'checkIsSupportSoterAuthentication',
    'chooseInvoice',
    'chooseMedia',
    'chooseMessageFile',
    'compressVideo',
    'connectWifi',
    'createBLEPeripheralServer',
    'disableAlertBeforeUnload',
    'enableAlertBeforeUnload',
    'exitVoIPChat',
    'getBLEDeviceRSSI',
    'getBackgroundAudioPlayerState',
    'getBackgroundFetchData',
    'getBackgroundFetchToken',
    'getGroupEnterInfo',
    'getHCEState',
    'getSelectedTextRange',
    'getShareInfo',
    'getVideoInfo',
    'getWeRunData',
    'join1v1Chat',
    'joinVoIPChat',
    'makeBluetoothPair',
    'openCard',
    'openVideoEditor',
    'playBackgroundAudio',
    'playVoice',
    'previewMedia',
    'requestPayment',
    'saveFileToDisk',
    'scanItem',
    'seekBackgroundAudio',
    'sendHCEMessage',
    'setBLEMTU',
    'setBackgroundFetchToken',
    'setEnable1v1Chat',
    'setTopBarText',
    'setWifiList',
    'setWindowSize',
    'showRedPackage',
    'startGyroscope',
    'startHCE',
    'startLocalServiceDiscovery',
    'startLocationUpdate',
    'startLocationUpdateBackground',
    'startRecord',
    'startSoterAuthentication',
    'startWifi',
    'stopGyroscope',
    'stopHCE',
    'stopLocalServiceDiscovery',
    'stopLocationUpdate',
    'stopWifi',
    'subscribeVoIPVideoMembers',
    'updateShareMenu',
    'updateVoIPChatMuteConfig',
    'updateWeChatApp',
    'sendBizRedPacket',
    'getUserProfile',
    'stopBluetoothDevicesDiscovery',
    'startBluetoothDevicesDiscovery',
    'openBluetoothAdapter',
    'getConnectedBluetoothDevices',
    'getBluetoothDevices',
    'getBluetoothAdapterState',
    'closeBluetoothAdapter',
    'writeBLECharacteristicValue',
    'readBLECharacteristicValue',
    'notifyBLECharacteristicValueChange',
    'getBLEDeviceServices',
    'getBLEDeviceCharacteristics',
    'createBLEConnection',
    'closeBLEConnection',
    'startFacialRecognitionVerify'
])



declare const wx: any

export function initNativeApi(taro) {
    processApis(taro, wx, {
        noPromiseApis,
        needPromiseApis
    })
    taro.cloud = wx.cloud
}


const { CurrentReconciler } = require('@tarojs/runtime')

CurrentReconciler.initNativeApi = initNativeApi
```

然后把这个文件放在我们的入口文件的第一行
```
import './api'; // !important 一定要先引入api 提前hotfix taro的bug
```
这么做的目的是绕过taro设计的策略，手动将所有taro api进行初始化

**Comment by lemondreamtobe** [comment]
> js/cli 3.4.14版本build:h5发布之后运行，也出现这个问题，Taro.showToast方法报错。请问一

https://github.com/NervJS/taro/issues/8751#issuecomment-1539334457

**Comment by lemondreamtobe** [comment]
> 3.5.8 同样有这个问题。神奇的是一个项目正常，一个项目会缺 getSystemInfoSync 等方法，两个项目都是从低版本升级上来的。

https://github.com/NervJS/taro/issues/8751#issuecomment-1539334457

**Comment by wikiwikiki** [comment]
> 给大家提供一种思路，但凡涉及到了taro api丢失了undefined的原因 基本要么都是打包或者版本不一致，在解决了版本号cli 和 @tarojs都一致的情况下 如果还出现了这个问题，那么原因只有一个，就是runtime里initNativeApi 这个方法缺失了 ![image](https://user-images.githubusercontent.com/22766436/236986199-9081e056-8bd0-43df-9e2a-8c0ff0b19929.png)
> 
> taro中很多的api都是靠源码的这个地方完成初始化，当我们加载@tarojs/taro会进到这个地方来 但是由于taro版本已经设计，打包策略/分包等诸多原因，可能会导致加载@tarojs/taro会先顺序执行其他的代码，从而导致我们的undefined报错。
> 
> 那么我们解决问题的方法也很简单，先在我们的src目录下新建一个api.ts
> 
> ```
> import { processApis } from '@tarojs/shared'
> export const noPromiseApis = new Set([
>     'getAccountInfoSync',
>     'getEnterOptionsSync',
>     'offBLEPeripheralConnectionStateChanged',
>     'offBeaconServiceChange',
>     'offBeaconUpdate',
>     'offDeviceMotionChange',
>     'offHCEMessage',
>     'offKeyboardHeightChange',
>     'offLocalServiceDiscoveryStop',
>     'offLocalServiceFound',
>     'offLocalServiceLost',
>     'offLocalServiceResolveFail',
>     'offLocationChange',
>     'offThemeChange',
>     'offVoIPChatInterrupted',
>     'offVoIPChatMembersChanged',
>     'offVoIPVideoMembersChanged',
>     'offWifiConnected',
>     'offWindowResize',
>     'onBLEPeripheralConnectionStateChanged',
>     'onBackgroundAudioPause',
>     'onBackgroundAudioPlay',
>     'onBackgroundAudioStop',
>     'onBackgroundFetchData',
>     'onHCEMessage',
>     'onKeyboardHeightChange',
>     'onLocalServiceDiscoveryStop',
>     'onLocalServiceFound',
>     'onLocalServiceLost',
>     'onLocalServiceResolveFail',
>     'onLocationChange',
>     'onThemeChange',
>     'onVoIPChatInterrupted',
>     'onVoIPChatMembersChanged',
>     'onVoIPChatSpeakersChanged',
>     'onVoIPVideoMembersChanged',
>     'onWifiConnected',
>     'onWindowResize',
>     'reportMonitor',
>     'onGyroscopeChange',
>     'offGyroscopeChange',
>     'createAudioContext',
>     'createLivePusherContext',
>     'createMediaContainer',
>     'createMediaRecorder',
>     'createOffscreenCanvas',
>     'createRewardedVideoAd',
>     'createUDPSocket',
>     'createVideoDecoder',
>     'createWorker',
>     'getLogManager',
>     'getNFCAdapter',
>     'getPerformance',
>     'getRealtimeLogManager',
>     'pauseBackgroundAudio',
>     'pauseVoice',
>     'reportPerformance',
>     'stopBackgroundAudio',
>     'stopRecord',
>     'stopVoice',
>     'onBluetoothDeviceFound',
>     'onBluetoothAdapterStateChange',
>     'offBluetoothDeviceFound',
>     'offBluetoothAdapterStateChange',
>     'onBLEConnectionStateChange',
>     'onBLECharacteristicValueChange',
>     'offBLEConnectionStateChange',
>     'offBLECharacteristicValueChange',
>     'onCopyUrl',
>     'offCopyUrl'
> ])
> 
> export const needPromiseApis = new Set([
>     'addCard',
>     'authPrivateMessage',
>     'checkIsOpenAccessibility',
>     'checkIsSoterEnrolledInDevice',
>     'checkIsSupportSoterAuthentication',
>     'chooseInvoice',
>     'chooseMedia',
>     'chooseMessageFile',
>     'compressVideo',
>     'connectWifi',
>     'createBLEPeripheralServer',
>     'disableAlertBeforeUnload',
>     'enableAlertBeforeUnload',
>     'exitVoIPChat',
>     'getBLEDeviceRSSI',
>     'getBackgroundAudioPlayerState',
>     'getBackgroundFetchData',
>     'getBackgroundFetchToken',
>     'getGroupEnterInfo',
>     'getHCEState',
>     'getSelectedTextRange',
>     'getShareInfo',
>     'getVideoInfo',
>     'getWeRunData',
>     'join1v1Chat',
>     'joinVoIPChat',
>     'makeBluetoothPair',
>     'openCard',
>     'openVideoEditor',
>     'playBackgroundAudio',
>     'playVoice',
>     'previewMedia',
>     'requestPayment',
>     'saveFileToDisk',
>     'scanItem',
>     'seekBackgroundAudio',
>     'sendHCEMessage',
>     'setBLEMTU',
>     'setBackgroundFetchToken',
>     'setEnable1v1Chat',
>     'setTopBarText',
>     'setWifiList',
>     'setWindowSize',
>     'showRedPackage',
>     'startGyroscope',
>     'startHCE',
>     'startLocalServiceDiscovery',
>     'startLocationUpdate',
>     'startLocationUpdateBackground',
>     'startRecord',
>     'startSoterAuthentication',
>     'startWifi',
>     'stopGyroscope',
>     'stopHCE',
>     'stopLocalServiceDiscovery',
>     'stopLocationUpdate',
>     'stopWifi',
>     'subscribeVoIPVideoMembers',
>     'updateShareMenu',
>     'updateVoIPChatMuteConfig',
>     'updateWeChatApp',
>     'sendBizRedPacket',
>     'getUserProfile',
>     'stopBluetoothDevicesDiscovery',
>     'startBluetoothDevicesDiscovery',
>     'openBluetoothAdapter',
>     'getConnectedBluetoothDevices',
>     'getBluetoothDevices',
>     'getBluetoothAdapterState',
>     'closeBluetoothAdapter',
>     'writeBLECharacteristicValue',
>     'readBLECharacteristicValue',
>     'notifyBLECharacteristicValueChange',
>     'getBLEDeviceServices',
>     'getBLEDeviceCharacteristics',
>     'createBLEConnection',
>     'closeBLEConnection',
>     'startFacialRecognitionVerify'
> ])
> 
> 
> 
> declare const wx: any
> 
> export function initNativeApi(taro) {
>     processApis(taro, wx, {
>         noPromiseApis,
>         needPromiseApis
>     })
>     taro.cloud = wx.cloud
> }
> 
> 
> const { CurrentReconciler } = require('@tarojs/runtime')
> 
> CurrentReconciler.initNativeApi = initNativeApi
> ```
> 
> 然后把这个文件放在我们的入口文件的第一行
> 
> ```
> import './api'; // !important 一定要先引入api 提前hotfix taro的bug
> ```
> 
> 这么做的目的是绕过taro设计的策略，手动将所有taro api进行初始化

cli 和项目内版本统一都是3.6.6，按这个解决方案 不生效，依然报错
<img width="661" alt="image" src="https://github.com/NervJS/taro/assets/45203334/ce1ad2ef-bc37-489e-9404-e87d8ca14da4">
