### ISSUE TITLE
Taro.reLaunch 方法不会清除所有页面栈

### ISSUE THREAD

**Issue by YoursOwen** [NervJS/taro#8758]
### 这个特性解决了什么问题？
Taro.reLaunch 方法不会清除所有页面栈，只会清楚前一个页面。

### 这个 API 长什么样？
特性应该和小程序一致，清空所有页面栈

**Comment by Chen-jj** [comment]
麻烦重新提一个问题反馈的 issue 吧，提供一切必要信息

**Comment by toFrankie** [comment]
+1（H5 端）
