### ISSUE TITLE
希望增加 offKeyboardHeightChange API

### ISSUE THREAD

**Issue by liaokaime** [NervJS/taro#8762]
### 这个特性解决了什么问题？
已有onKeyboardHeightChange API了，就应该有相对应的offKeyboardHeightChange，这个api将常被用于hooks中

### 这个 API 长什么样？
https://developers.weixin.qq.com/miniprogram/dev/api/ui/keyboard/wx.offKeyboardHeightChange.html

**Comment by Chen-jj** [comment]
3.1 已支持。
