### ISSUE TITLE
想要一个 vue 转 Taro 的工具，或者是参考指南的文档

### ISSUE THREAD

**Issue by Dante-dan** [NervJS/taro#8764]
### 这个特性解决了什么问题？
vue 项目已经开发很久了，想要转到 Taro。但是缺少指导性的参考文档，各种途径来的都比较碎片化。

### 这个 API 长什么样？
我可以自己做一个基于 AST 的工具来完成这个功能，但是需要一些参考指南的支持，也可以将其添加到 taro 的指令中。

`taro reconvert vue`

**Comment by Chen-jj** [comment]
@Dante-dan 感谢关注！我到你评论的下面进行回复吧，这个先关闭哈～

Duplicate of #7939
