### ISSUE TITLE
为什么我在app.js config里面配置tabbar不能放静态图片？？

### ISSUE THREAD

**Issue by EForinaJ** [NervJS/taro#877]
我想在给小程序配置tabbar 但是编译的时候报错；

![qq 20181018194941](https://user-images.githubusercontent.com/22424208/47152328-f9dfd980-d30e-11e8-8711-fc25256c8bf0.png)
编译的时候报错了， 这是我写的代码
![qq 20181018195033](https://user-images.githubusercontent.com/22424208/47152376-1aa82f00-d30f-11e8-9e6b-ab827bb62440.png)
我想问一下这个静态图片应该怎么放到tabbar上面

**Comment by luckyadam** [comment]
不用 import ，tabbar 配置那里直接写图片相对路径

**Comment by EForinaJ** [comment]
> 不用import，tabbar配置那里直接写图片相对路径

我写相对路径还是报错了
![qq 20181018224101](https://user-images.githubusercontent.com/22424208/47162636-eb052100-d326-11e8-9925-a90c9144d2d9.png)
