### ISSUE TITLE
微信小程序中canvas的onTouch事件异常

### ISSUE THREAD

**Issue by hd1001** [NervJS/taro#878]
<Canvas id="canvas" style={style} canvas-id='canvas' onTouchStart={this.onTouchStart} onTouchMove={this.onTouchMove} onTouchEnd={this.onTouchEnd}/>

在iPhone的微信小程序中，用Canvas自定义一个组件，当在onTouchStart或者onTouchMove中调用e.stopPropagation()就不执行对应当回调了
而在微信当IDE和Android系统中都可以正常使用。

**Comment by luckyadam** [comment]
能否贴一下相关代码~

**Comment by hd1001** [comment]
onTouchStart(e) {
    e.stopPropagation()
    console.log('onTouchStart')
  }
  onTouchMove(e) {
      // e.stopPropagation()
    console.log('onTouchMove')
  }

  onTouchEnd(e) {
    console.log('onTouchEnd')
  }
  render () {
    let width = this.props.width || "300px"
    let height = this.props.height || "300px"

    let style = {
      width: width,
      height: height,
      // border: "1px solid red"
    }
    return (

      <View>
        <Canvas id="canvas" style={style} canvas-id='canvas' onTouchStart={this.onTouchStart} onTouchMove={this.onTouchMove} onTouchEnd={this.onTouchEnd}/>
      </View>
    )
  }

**Comment by luckyadam** [comment]
书写了 `e.stopPropagation()` 之后，`onTouchStart` 会被编译成 catchtouchstart，阻止冒泡

你这里说的“应当的回调”是指哪个回调呢
