### ISSUE TITLE
linaria集成报错

### ISSUE THREAD

**Issue by CangJL** [NervJS/taro#8781]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
按照官网cssinjs集成linaria的步骤

### 期望结果
可以使用css-in-js

### 实际结果
Module build failed (from ./node_modules/linaria/lib/webpack4-loader.js):
Error: /Users/cjl/Documents/projects/woye/minixs/src/pages/index/index.jsx: An unexpected runtime error occurred during dependencies evaluation: 
/Users/cjl/Documents/projects/woye/minixs/node_modules/@tarojs/plugin-platform-weapp/dist/components-react.js:53

### 环境信息
```
  Taro CLI 3.1.0 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.1.0 => 3.1.0 
      @tarojs/mini-runner: 3.1.0 => 3.1.0 
      @tarojs/react: 3.1.0 => 3.1.0 
      @tarojs/runtime: 3.1.0 => 3.1.0 
      @tarojs/taro: 3.1.0 => 3.1.0 
      @tarojs/webpack-runner: 3.1.0 => 3.1.0 
      babel-preset-taro: 3.1.0 => 3.1.0 
      eslint-config-taro: 3.1.0 => 3.1.0 
      react: ^17.0.0 => 17.0.1 

```

**Comment by Chen-jj** [comment]
@CangJL `linaria.config.js` 需要修改如下：

```js
// linaria 配置详见 https://github.com/callstack/linaria/blob/master/docs/CONFIGURATION.md#options
module.exports = {
  rules: [
    {
      action: require("linaria/evaluators").shaker,
    },
    {
      test: /node_modules[\/\\](?!@tarojs)/,
      action: "ignore"
    }
  ]
}
```

我们改一下文档
