### ISSUE TITLE
按需编译 与 ctx.modifyBuildTempFileContent

### ISSUE THREAD

**Issue by dream2023** [NervJS/taro#8783]
### 这个特性解决了什么问题？
我准备做一个按需编译的功能，实现原理：首先使用 cli 选择需要编译的页面，然后保存结果，最后再 taro 启动后，修改 app.config.js

我看文档原来在修改 app.config.js 上有 ctx.modifyBuildTempFileContent，现在 3.x 没有了这个 API，请问是为什么，以及有何替代方案？

### 这个 API 长什么样？
提供一个类似的 API 能修改配置文件

**Comment by dream2023** [comment]
@Chen-jj 大佬有什么好的方案吗？

**Comment by Chen-jj** [comment]
@dream2023 可以试试设置环境变量，然后在 `app.config.js` 中根据不同的环境变量设置不同的 pages 值。

**Comment by dream2023** [comment]
> @dream2023 可以试试设置环境变量，然后在 `app.config.js` 中根据不同的环境变量设置不同的 pages 值。

已经走了解决方案，支持 taro 一二三，这两天写完测试用例就可以开源了

**Comment by Chen-jj** [comment]
棒棒棒～

**Comment by dream2023** [comment]
还要再这一个 vscode插件，可以选择编译的页面，然后启动，不用cli，更方便

**Comment by dream2023** [comment]
我先了

**Comment by dream2023** [comment]
https://gitee.com/dream2023/itaro

已经写好了。
