### ISSUE TITLE
taro 的tabbar配置 中文编译错误 有时vue文件页面也会出现中文编译错误

### ISSUE THREAD

**Issue by pxr-mm** [NervJS/taro#8795]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/pxr-mm/Miniprogram-taro-vue-demo/tree/main](https://github.com/pxr-mm/Miniprogram-taro-vue-demo/tree/main)
**小程序基础库: 2.15.0**
**使用框架: Vue 2**

### 复现步骤
tabBar: {
    color: '#cac',
    selectedColor:'#2ea5ff',
    list: [{
        pagePath: "pages/index/index",
        iconPath:'static/images/hot.png',
        selectedIconPath:'static/images/hot2.png',
        text: "首页"
      },
      {
        iconPath:'static/images/huangguan.png',
        selectedIconPath:'static/images/huangguan2.png',
        pagePath: "pages/mine/index",
        text: "mine"
      }
    ]
  }

### 期望结果
中文编译问题原因和得到解决

### 实际结果
编码是utf-8格式的，但编译中文出错，第一次的运行时是正常的，当关闭项目第二次打开运行时就会出现这个编译中文错乱问题

### 环境信息
```
� Taro v3.0.26


  Taro CLI 3.0.26 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\xiake\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD.8
```

**Comment by luckyadam** [comment]
你编辑器设置的缘故吧

**Comment by pxr-mm** [comment]
> 你编辑器设置的缘故吧

taro react 的编译正常

**Comment by pxr-mm** [comment]
> 你编辑器设置的缘故吧

新建了一个taro vue 项目运行就没有中文编译问题的了

**Comment by Chen-jj** [comment]
没有复现，可能 Demo 本身的编码有问题有关：
![image](https://user-images.githubusercontent.com/11807297/155094283-f0a4ec47-ec70-45a6-8c49-dbdcae5624d3.png)
