### ISSUE TITLE
TypeError: Cannot read property 'childNodes' of null

### ISSUE THREAD

**Issue by jiangyh123** [NervJS/taro#8798]
### 相关平台
H5

### 复现仓库
[https://github.com/nervjs/taro](https://github.com/nervjs/taro)
**浏览器版本:  Chrome 62**
**使用框架: React**

### 复现步骤
直接用3.1.1创建一个新的项目，然后把代码放index.js

import React, { Component } from 'react'
import Taro from '@tarojs/taro'
import { View, Image } from '@tarojs/components'
import './index.scss'

export default class Index extends Component {
  constructor() {
    super(...arguments)
    this.state = {
      presentCity: {
        cityName: '杭州'
      }
    }
  }
  componentDidMount() {
    let preData = { cityName: "杭州市", cityCode: "330100", spell: "HangZhouShi" }
    Taro.setStorage({
      key: "selectCity",
      data: preData
    })
  }

  //获取用户所在城市信息
  showCityInfo() {
    let that = this;
    // 1、获取缓存中得城市
    Taro.getStorage({
      key: 'selectCity',
      success: function (res) {
        console.log(res)
        debugger
        that.setState({
          presentCity: res.data,
          noMoreData: false
        }, () => {
          console.log('1')
        })
      },
      fail: function (error) {
      }
    })
  }
  componentDidShow() {
    this.showCityInfo()
  }

  componentDidHide() {
  }

  render() {
    let { presentCity } = this.state;
    return (
      <View className='indexBody'>
        <View className='searchMain'>
          <View className='searchLocation'>
            <Image className='locationImg' src='https://static.zje.com/1610087186200_8bwzn22r2jj.png' />
            <View className='locationTitle'>{presentCity.cityName}</View>
          </View>
        </View>
      </View>
    )
  }
}

### 期望结果
页面正常展示

### 实际结果
TypeError: Cannot read property 'childNodes' of null
    at relocateSlotContent (core-f216d924.js?479a:1023)
    at renderVdom (core-f216d924.js?479a:1118)
    at updateComponent (core-f216d924.js?479a:1253)
    at Array.update (core-f216d924.js?479a:1210)
    at consumeTimeout (core-f216d924.js?479a:161)
    at flush (core-f216d924.js?479a:184)

### 环境信息
```

  Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.19.0 - D:\software\node\soft\node.EXE
      Yarn: 1.22.10 - C:\Users\jyh\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - D:\software\node\soft\npm.CMD
```

**Comment by bgy10** [comment]
同样的问题

**Comment by Fancy-X** [comment]
滴滴滴滴，打卡我也会，只是我用demo写的没法复现，但是真实项目中就是会，我这边主要是用了react的类似插槽语法，就是用组件的标签包裹其他标签，动态传入children的形式：
![image](https://user-images.githubusercontent.com/41465431/109743466-b6e6de00-7c0b-11eb-9832-fe0612a87172.png)
![image](https://user-images.githubusercontent.com/41465431/109743504-c23a0980-7c0b-11eb-90e2-6a4908673172.png)
第一张是组件外部使用，第二张是组件内部，涉及到保密，只能提供这么多了抱歉

**Comment by Fancy-X** [comment]
3.0.21版本没问题，升级了3.1.0之后就稳定复现了

**Comment by Fancy-X** [comment]
组件内部如果改成只带一个children就没问题：
![image](https://user-images.githubusercontent.com/41465431/109744041-a4b96f80-7c0c-11eb-900d-a156e1d95127.png)

**Comment by Fancy-X** [comment]
如果注释掉该句传入的变量就渲染正常：
![image](https://user-images.githubusercontent.com/41465431/109745872-71c4ab00-7c0f-11eb-9435-a0d51575de75.png)
因为组件外部会动态更改该变量：
![image](https://user-images.githubusercontent.com/41465431/109745947-8e60e300-7c0f-11eb-9e7e-fd2c33ce2e9c.png)

**Comment by Chen-jj** [comment]
Stencil 的问题：https://github.com/ionic-team/stencil/pull/2761/files

Taro3.2 将升级到最新的 Stencil 版本以解决。
