### ISSUE TITLE
Module not found: Can't resolve

### ISSUE THREAD

**Issue by hanxinimm** [NervJS/taro#8800]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤

![image](https://user-images.githubusercontent.com/13499426/109640351-587a1b00-7b8b-11eb-833a-d9862e2a0e4a.png)

配置文件 

export default {
  pages: [
    "pages/index/index",
    "pages/recruit/official/details/index",
    "pages/helper/index",
    "pages/atcalendar/index",
    "pages/helper/overtime/index"
  ],
  window: {
    backgroundColor: "#fff",
    backgroundTextStyle: "light",
    navigationBarTextStyle: "white",
    enablePullDownRefresh: true,
    navigationStyle: "custom"
  },
  sitemapLocation: "sitemap.json"
};

运行指令

yarn run dev:h5  

### 期望结果
正常运行，无异常

### 实际结果
🙅   Failed to compile.

./src/app.config.js
Module not found: Can't resolve './pages/atcalendar/index.config' in 'D:\LaborDispatch\WXApp\Labor-Trao-Personal\src'

### 环境信息
```
👽 Taro v3.0.21


  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\node_global\node_modules\yarn\bin\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
```

**Comment by nanxiaobei** [comment]
升级 `3.1.1`，直接出现 Module not found: Can't resolve 'undefined' in '...

![0](https://s3.jpg.cm/2021/03/03/0sq4e.png)

试了一下，`3.0.28` 及以下没问题，自 `3.1.0` 开始启动项目，编译，就会报此错误。

**Comment by Chen-jj** [comment]
提供一下demo

**Comment by hanxinimm** [comment]
一个刚开发的小项目
[Labor-Trao-Personal.zip](https://github.com/NervJS/taro/files/6080325/Labor-Trao-Personal.zip)

**Comment by kokiy** [comment]
小程序我这边也复现了

**Comment by kokiy** [comment]
@hanxinimm 喊一下 taro cli 本地全部的版本和你项目里版本一样不一样

**Comment by nanxiaobei** [comment]
对齐 `@tarojs/cli` 版本就好了。

**Comment by Chen-jj** [comment]
CLI 和依赖版本保持一致，页面需要有配置文件：https://docs.taro.zone/docs/next/react#%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE

http://localhost:3000/taro/docs/next/migration
