### ISSUE TITLE
Taro.setClipboardData 复制内容，不能复制换行，看了下源码使用的是input而不是textarea，换成textarea就能复制换行的内容

### ISSUE THREAD

**Issue by ShaoGongBra** [NervJS/taro#8802]
### 这个特性解决了什么问题？
Taro.setClipboardData h5端不能复制换行

### 这个 API 长什么样？
Taro.setClipboardData 能复制换行

**Comment by Chen-jj** [comment]
请使用提报 bug 的 Issue 模板重新提交，并提供相应的可复现 demo

**Comment by ShaoGongBra** [comment]
要提供找个流程太复杂了，就是找个文件
node_modules\@tarojs\taro-h5\src\api\clipboard\index.js:55
将
const input = document.createElement('input')
替换为
const input = document.createElement('textarea')
