### ISSUE TITLE
Input 标签在输入完成以后点击换行按钮无法关闭键盘

### ISSUE THREAD

**Issue by Oldboyyyy** [NervJS/taro#8806]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/Oldboyyyy/Taro-issue-demo](https://github.com/Oldboyyyy/Taro-issue-demo)
**小程序基础库: 1.24.13**
**使用框架: React**

### 复现步骤
```
<Input
          type="text"
          focus
          placeholder="123"
          confirmType="search"
          onConfirm={() => console.log("点击了")}
        />
```

*  confirmType设置也没有生效,键盘的换行键并没有像预期的变成搜索
*  直接真机调试或者预览时候, 输入完毕以后, 点击换行按钮, 会发现onConfirm事件触发了, 但是键盘没有关闭
*  同样代码微信小程序表现正常
*  支付宝原生小程序表现也是正常的

### 期望结果
confirmType功能正常
onConfirm事件触发完成后关闭键盘

### 实际结果
输入完毕以后, 点击换行按钮, 会发现onConfirm事件触发了, 但是键盘没有关闭
confirmType设置也没有生效,键盘的换行键并没有像预期的变成搜索

### 环境信息
```
👽 Taro v3.1.1


  Taro CLI 3.1.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.1 => 3.1.1 
      @tarojs/components: 3.1.1 => 3.1.1 
      @tarojs/mini-runner: 3.1.1 => 3.1.1 
      @tarojs/react: 3.1.1 => 3.1.1 
      @tarojs/runtime: 3.1.1 => 3.1.1 
      @tarojs/taro: 3.1.1 => 3.1.1 
      @tarojs/webpack-runner: 3.1.1 => 3.1.1 
      babel-preset-taro: 3.1.1 => 3.1.1 
      eslint-config-taro: 3.1.1 => 3.1.1 
      react: ^17.0.0 => 17.0.1 
```

**Comment by Oldboyyyy** [comment]
![image](https://user-images.githubusercontent.com/14163019/109904364-13afca80-7cd8-11eb-897b-329658f83555.png)
这里没有 type 默认值导致 支付里面编译出来的缺少 type 默认值
![image](https://user-images.githubusercontent.com/14163019/109904592-71dcad80-7cd8-11eb-829e-74820619b1c0.png)
```
<Input
          type='text'
          focus
          placeholder="123"
          confirmType="search"
          onConfirm={() => console.log("点击了")}
        />
```
支付宝中要显示写上 type

**Comment by Oldboyyyy** [comment]
```
<Input
          type="text"
          focus
          placeholder="123"
          confirmType="search"
          onConfirm={() => console.log("点击了")}
          //@ts-ignore
          enableNative
        />
```
enableNative属性在支付宝编译时候被默认设置成 false 了
![image](https://user-images.githubusercontent.com/14163019/110057905-65ba2400-7d9c-11eb-927c-96c54c704561.png)

**Comment by harwinvoid** [comment]
> ```
> <Input
>           type="text"
>           focus
>           placeholder="123"
>           confirmType="search"
>           onConfirm={() => console.log("点击了")}
>           //@ts-ignore
>           enableNative
>         />
> ```
> 
> enableNative属性在支付宝编译时候被默认设置成 false 了
> ![image](https://user-images.githubusercontent.com/14163019/110057905-65ba2400-7d9c-11eb-927c-96c54c704561.png)
 我加了这个键盘还是显示换行按钮
```jsx
 <Input
        // 输入框
        value={store.searchKeyWord}
        focus={store.isSearchFocus}
        // onBlur={() => store.handSearchFocus(false)}
        onInput={store.handleSearchInput}
        // @ts-ignore
        enableNative
        placeholderClass='input-placeholder'
        className='input'
        confirmType='search'
        placeholder='搜索门店'
      />
```

**Comment by harwinvoid** [comment]
> > ```
> > <Input
> >           type="text"
> >           focus
> >           placeholder="123"
> >           confirmType="search"
> >           onConfirm={() => console.log("点击了")}
> >           //@ts-ignore
> >           enableNative
> >         />
> > ```
> > 
> > 
> > enableNative属性在支付宝编译时候被默认设置成 false 了
> > ![image](https://user-images.githubusercontent.com/14163019/110057905-65ba2400-7d9c-11eb-927c-96c54c704561.png)
> > 我加了这个键盘还是显示换行按钮
> 
> ```js
>  <Input
>         // 输入框
>         value={store.searchKeyWord}
>         focus={store.isSearchFocus}
>         // onBlur={() => store.handSearchFocus(false)}
>         onInput={store.handleSearchInput}
>         // @ts-ignore
>         enableNative
>         placeholderClass='input-placeholder'
>         className='input'
>         confirmType='search'
>         placeholder='搜索门店'
>       />
> ```

需要手动 声明 type=‘text’， confirmType才生效
