### ISSUE TITLE
如果使用vue3，可以编译到Android|Ios吗？

### ISSUE THREAD

**Issue by TuiMao233** [NervJS/taro#8809]
so，我在考虑使用vue3编写多端项目，可是目前官网完整上没有明确标识支持，所以我想知道是否支持，还是说只支持React Native的方式编译App。

**Comment by Chen-jj** [comment]
只支持 React Native 方式，vue 不支持的

**Comment by CNMathon** [comment]
@Chen-jj 请问 Taro 后续是否存在 使用 Vue3 进行原生 App 开发的支持计划呢？

**Comment by yuangu** [comment]
Vue Native？会支持么？
