### ISSUE TITLE
我在app.js config里面设置tabbar图片路径但是报错了？

### ISSUE THREAD

**Issue by EForinaJ** [NervJS/taro#881]
![qq 20181018224101](https://user-images.githubusercontent.com/22424208/47168062-8ea7fe80-d332-11e8-9b31-0fa40ce65937.png)
我想设置tabbar 但是设置到iconPath 的时候 编译就报错了！！  我重新安装taro三次都是出现这样的问题，求解决一下

**Comment by luckyadam** [comment]
把 images 目录放到 src 目录下
