### ISSUE TITLE
input  无法主动设置聚焦

### ISSUE THREAD

**Issue by jsLyLeeHi** [NervJS/taro#8816]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: Vue 3**

### 复现步骤
<input :focus="true" />
focus使用一个变量来接收也无法聚焦

### 期望结果
<input :focus="true" />可以主动设置聚焦

### 实际结果
<input :focus="true" />无法主动设置聚焦

### 环境信息
```
  Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.4 - C:\Users\1\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ItsRyanWu** [comment]
发现了同样的问题，可以确定几件事情
1. autoFocus 可以使 input 组件自动聚焦
2. focus 无法使 input 自动聚焦
3. focus 在原生小程序中可以使 input 自动聚焦

虽然目前阶段可以用 autoFocus 暂时替代 focus 使用，但 focus 会有属于他独特的应用场景，比如在 input box A 输入了一些内容后自动将光标聚焦到 input box B，遇到这种情况 focus 失效就彻底无解了，目前被卡在这里了。

**Comment by Chen-jj** [comment]
@jsLyLeeHi @ItsRyanWu Vue 的布尔值设置需要显式传递 `true`。

这种写法是可以的：

```js
<input type="text" :focus="true" placeholder="input">
```
