### ISSUE TITLE
RuntimeErrorFooter is not defined

### ISSUE THREAD

**Issue by zjsxfly** [NervJS/taro#8817]
### 相关平台
H5

**浏览器版本: 企业微信/微信windows端内置浏览器**
**使用框架: React**

### 复现步骤
在微信或企业微信windows版本，打开http://tiknows.vipgz6.idcfengye.com

### 期望结果
正常运行

### 实际结果
RuntimeErrorFooter is not defined

### 环境信息
```
  Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
在系统浏览器内是正常的，在手机android、ios端也正常
taro build后部署至服务器也正常

**Comment by Chen-jj** [comment]
信息太少，定位不了，建议先自行调试一下
