### ISSUE TITLE
getUserInfo api改版，尽快做同步

### ISSUE THREAD

**Issue by JuntengMa** [NervJS/taro#8826]
### 这个特性解决了什么问题？
微信官方文档getuserInfo逻辑修改了，你们这边尽快兼容一下！！！
https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801
https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801
https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801

### 这个 API 长什么样？
https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801

**Comment by Chen-jj** [comment]
Duplicate of #8810
