### ISSUE TITLE
input 组件打包到 h5, 限制输入类型为 number 后，页面内仍可渲染字母 e,点 符号, 加号,连字符

### ISSUE THREAD

**Issue by RichardDegeneres** [NervJS/taro#8828]
### 相关平台
h5

**小程序基础库: 2.14.4**
**使用框架: React**

### 复现步骤
 1. 小程序内使用组件 input 

     <Input
              name="phone"
              type="number"
              placeholder="填写手机号"
              maxlength={11}
       />

2. npm run build:h5

3. 使用安卓手机/ uc 浏览器 访问

### 期望结果
输入框只能输入数字

### 实际结果
输入  加号, 连字符, 点 ， 仍会渲染出来

### 环境信息
```

  Taro CLI 3.0.26 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.22.5 - ~/.nvm/versions/node/v12.2.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26
      @tarojs/mini-runner: 3.0.26 => 3.0.26
      @tarojs/react: 3.0.26 => 3.0.26
      @tarojs/runtime: 3.0.26 => 3.0.26
      @tarojs/taro: 3.0.26 => 3.0.26
      @tarojs/webpack-runner: 3.0.26 => 3.0.26
      babel-preset-taro: 3.0.26 => 3.0.26
      eslint-config-taro: 3.0.26 => 3.0.26
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10
```

**Comment by Chen-jj** [comment]
`type="number"` 的作用是唤起数字键盘，但不会限制输入的吧

**Comment by RichardDegeneres** [comment]
> `type="number"` 的作用是唤起数字键盘，但不会限制输入的吧

其它英文字母输入不了，onInput 事件 拿不到 e 等其它字符的值

**Comment by Chen-jj** [comment]
提供一下 demo，手机，浏览器型号

**Comment by JferLao** [comment]
我在写input的时候也遇到这个问题，不过这个是H5端的一个bug来的，要想真的控制纯数字输入只能重写一个input或者用View封装一个新的输入框 ，可以参考antdesign mobile

**Comment by RichardDegeneres** [comment]
> 提供一下 demo，手机，浏览器型号

1.  demo: 

class H5 extends PureComponent<FinalProps, State> {
  readonly state: State = {
    inputPhone: null,
  }

  handleInputPhone = (e) => {
    this.setState({ inputPhone: e.detail.value })
  }

  render() {
    const { inputPhone } = this.state

    return (
      <View >
            <Input
              name="phone"
              type="number"
              placeholder="填写手机号"
              maxlength={11}
              value={`${inputPhone || ''}`}
              onInput={this.handleInputPhone}
            />
      </View>
    )
  }
}


2. 手机： oppo；  浏览器：uc 最新版 13.2.9

**Comment by ZakaryCode** [comment]
浏览器的 number 类型本来就是这样的，H5 端目前不考虑未 number 类型提供纯数字限制，需要可以由开发者自主优化。
