### ISSUE TITLE
tabbar页面首次打开或者刷新tabbar消失

### ISSUE THREAD

**Issue by 50431040** [NervJS/taro#8848]
### 相关平台
H5

**浏览器版本: Safari**
**使用框架: React**

### 复现步骤
router(路由)模式为history会出现，hash不会。
打开tab页，或者刷新就会出现tabbar消失的问题。
线上打包配置：
h5: {
    publicPath: '/h5',
    staticDirectory: 'static',
    imageUrlLoaderOption: {
      publicPath: '/h5'
    }
  }
可以参考链接：https://manager.niuxiaoer.net/h5/pages/jobList/index（手机打开，pc浏览器好像不会）

### 期望结果
首次打开或刷新tabbar不会消失

### 实际结果
首次打开或刷新tabbar消失

### 环境信息
```
 Taro CLI 3.1.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
history(路由)模式为history会出现，hash不会

**Comment by Chen-jj** [comment]
手机型号、浏览器版本、最好提供一下 demo

**Comment by 50431040** [comment]
手机型号：iPhone XR、安卓手机也有出现
浏览器版本：Safari
demo地址：https://github.com/50431040/taro_app.git
需要打包出来上传到服务器上测试，目录见项目配置
打开首页不会出现tabbar，点击跳转后再返回就出现了。
@Chen-jj

**Comment by 50431040** [comment]
应该是打包配置 /h5 导致的。配置为 / 放到服务器根目录就正常了

**Comment by pettersnoopy** [comment]
我也碰到了，但是我们目前的需求就是不放在服务器根目录，这个有什么办法解决吗

**Comment by wxttt** [comment]
遇到了同样的问题，看到问题close了，请问有在某个版本FIX掉么？
@Chen-jj
