### ISSUE TITLE
利用端平台插件给 View 新增 hidden 属性无效

### ISSUE THREAD

**Issue by changcllong** [NervJS/taro#8853]
### 相关平台
字节跳动小程序

**小程序基础库: 1.9.30 (飞书小程序)**
**使用框架: React**

### 复现步骤
```
<View className="test" hidden style={style}></View>
```

这个代码会导致 taro 使用 pure-view 去渲染，hidden 属性无法加上

原因是 taro 中是否使用 pure-view 的判断：

function isHasExtractProp(el) {
    const res = Object.keys(el.props).find(prop => {
        return !(/class|style|id/.test(prop) || prop.startsWith('data-'));
    });
    return Boolean(res);
}

这里 /class|style|id/.test('hidden') === true

### 期望结果
有 hidden 属性的 View 可以生效

### 实际结果
简单的 View 会使用 pure-view 去渲染，hidden 属性不生效

### 环境信息
```
👽 Taro v3.1.2


  Taro CLI 3.1.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.2 => 3.1.2
      @tarojs/components: 3.1.2 => 3.1.2
      @tarojs/mini-runner: 3.1.2 => 3.1.2
      @tarojs/react: 3.1.2 => 3.1.2
      @tarojs/router: 3.1.2 => 3.1.2
      @tarojs/runtime: 3.1.2 => 3.1.2
      @tarojs/taro: 3.1.2 => 3.1.2
      @tarojs/webpack-runner: 3.1.2 => 3.1.2
      babel-preset-taro: 3.1.2 => 3.1.2
      eslint-config-taro: 3.1.2 => 3.1.2
      eslint-plugin-taro: 3.1.2 => 3.1.2
      nerv-devtools: 1.5.7 => 1.5.7
      nervjs: 1.5.7 => 1.5.7
      react: 17.0.1 => 17.0.1
    npmGlobalPackages:
      typescript: 4.0.2
```

**Comment by Chen-jj** [comment]
@changcllong 可以给我们提一个 PR，修改这个正则哈

**Comment by yigeqi** [comment]
请问，这个修复是不针对微信小程序么？因为实测发现taro 3版本使用react开发微信小程序，还是不支持hidden;这里又好像明确表示就是不支持hidden的：https://github.com/NervJS/taro/issues/8545
