### ISSUE TITLE
对于手百小程序非兼容性升级，Taro是否会支持

### ISSUE THREAD

**Issue by Daisy1213** [NervJS/taro#8854]
![image](https://user-images.githubusercontent.com/18098766/110457287-70125000-8105-11eb-8e03-70a4b6fae6e2.png)
最近百度小程序发通知将要对登录接口进行升级，想请问taro框架也会同步进行升级支持吗

**Comment by Chen-jj** [comment]
请按规范创建 Issue，如果遇到问题，创建一个问题反馈 Issue ，提供一切必要信息
