### ISSUE TITLE
原生微信小程序转taro，编译问题。【Module not found: Can't resolve 'undefined' 】

### ISSUE THREAD

**Issue by chenzhaozheng** [NervJS/taro#8858]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/chenzhaozheng/taroTest](https://github.com/chenzhaozheng/taroTest)
**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
1. 重现链接通过taro convert进行转换
2. 转换后成功出现taroConvert
3. 进行 taroConvert后执行yarn install
4. 安装成功后，进行yarn dev:weapp
5.出现错误。

### 期望结果
可以yarn dev:weapp成功，项目也可以跑起来

### 实际结果
出现报错

### 环境信息
```
👽 Taro v3.1.1


  Taro CLI 3.1.1 environment info:
    System:
      OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
    npmPackages:
      @tarojs/components: 3.1.1 => 3.1.1 
      @tarojs/mini-runner: 3.1.1 => 3.1.1 
      @tarojs/react: 3.1.1 => 3.1.1 
      @tarojs/runtime: 3.1.1 => 3.1.1 
      @tarojs/taro: 3.1.1 => 3.1.1 
      @tarojs/webpack-runner: 3.1.1 => 3.1.1 
      @tarojs/with-weapp: ^3.1.1 => 3.1.2 
      babel-preset-taro: 3.1.1 => 3.1.1 
      eslint-config-taro: 3.1.1 => 3.1.1 
      react: ^17.0.0 => 17.0.1 
```
### 其它信息
![image](https://user-images.githubusercontent.com/5388869/110573980-368a2500-8197-11eb-8185-3fe10cd7a1c4.png)

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/110600831-559cad00-81bf-11eb-966c-42d780a298b0.png)

这里的 CLI 版本错了吧，要是 3.1
