### ISSUE TITLE
swiper组件 动态插入数据在百度小程序中前后插入了两个空页

### ISSUE THREAD

**Issue by guojinfa10837** [NervJS/taro#8861]
### 相关平台
百度小程序

**小程序基础库: 5.26.1**
**使用框架: Vue 3**

### 复现步骤
复制案例代码即可

### 期望结果
无插入的空页

### 实际结果
swiper组件 动态插入数据在百度小程序中前后插入了两个空页

### 环境信息
```
  Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.17.0 - D:\nodejs\node.EXE
      npm: 6.14.4 - D:\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@guojinfa10837 没有复现，提供一下 demo

**Comment by guojinfa10837** [comment]
我是直接npm 安装的新包 vue3 没有typeScript
然后在index 页面里复制的 swiper 组件代码

<script> export default { name: 'SwiperDemo', data() { return { current: 1, duration: 500, interval: 5000, isCircular: false, isAutoplay: false, hasIndicatorDots: true, imgUrls: [ 'https://img10.360buyimg.com/babel/s700x360_jfs/t25855/203/725883724/96703/5a598a0f/5b7a22e1Nfd6ba344.jpg!q90!cc_350x180', 'https://img11.360buyimg.com/babel/s700x360_jfs/t1/4776/39/2280/143162/5b9642a5E83bcda10/d93064343eb12276.jpg!q90!cc_350x180', 'https://img14.360buyimg.com/babel/s700x360_jfs/t1/4099/12/2578/101668/5b971b4bE65ae279d/89dd1764797acfd9.jpg!q90!cc_350x180', ], } } } </script>

**Comment by Chen-jj** [comment]
@guojinfa10837 老哥提供一下格式化后的代码咯。。

**Comment by guojinfa10837** [comment]
老哥  还有问题可以加一下我微信  
![Uploading image.png…]()

**Comment by Chen-jj** [comment]
@guojinfa10837 你直接把截图的代码发文本格式吧，不然我还得一句一句打

**Comment by guojinfa10837** [comment]
<template>
  <view>
    <swiper
      class='test-h'
      indicatorColor='#999'
      indicatorActiveColor='#333'
      current="current"
      :duration="duration"
      :interval="interval"
      :circular="isCircular"
      :autoplay="isAutoplay"
      :indicatorDots="hasIndicatorDots">
      <swiper-item v-for="(item, idx) in imgUrls" :key="idx">
        <image :src="item" class="slide-image" />
      </swiper-item>
    </swiper>
  </view>
</template>
<script>
export default {
  name: 'SwiperDemo',
  data() {
    return {
      current: 1,
      duration: 500,
      interval: 5000,
      isCircular: false,
      isAutoplay: false,
      hasIndicatorDots: true,
      imgUrls: [
        'https://img10.360buyimg.com/babel/s700x360_jfs/t25855/203/725883724/96703/5a598a0f/5b7a22e1Nfd6ba344.jpg!q90!cc_350x180',
        'https://img11.360buyimg.com/babel/s700x360_jfs/t1/4776/39/2280/143162/5b9642a5E83bcda10/d93064343eb12276.jpg!q90!cc_350x180',
        'https://img14.360buyimg.com/babel/s700x360_jfs/t1/4099/12/2578/101668/5b971b4bE65ae279d/89dd1764797acfd9.jpg!q90!cc_350x180',
      ],
    }
  }
}
</script>

**Comment by duangangqiang** [comment]
我也遇到了相同问题，是否可以把解决方案发一下，我看也没有解决方案就关闭了啊
