### ISSUE TITLE
vue2.0 能否支持live-player

### ISSUE THREAD

**Issue by ty-xy** [NervJS/taro#8872]
### 相关平台
微信小程序

**小程序基础库: 开发版**
**使用框架: Vue 2**

### 复现步骤
 <live-player 
      src="https://test-play.allinmd.cn/liveMeeting/ca69135e1c76d145841915e18317ea8557bb_vflu.flv?txSecret=1fb173a2445f5272c9d0843566f0b0f5&txTime=604d8672"
      mode="live"
      autoplay
      @stateChange="handleChange"
    >

### 期望结果
可以正常直播

### 实际结果
一直黑屏不能直播

### 环境信息
```
Taro CLI 3.0.17 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.17 => 3.0.17 
      @tarojs/mini-runner: 3.0.17 => 3.0.17 
      @tarojs/runtime: 3.0.17 => 3.0.17 
      @tarojs/taro: 3.0.17 => 3.0.17 
      @tarojs/webpack-runner: 3.0.17 => 3.0.17 
      babel-preset-taro: 3.0.17 => 3.0.17 
      eslint-config-taro: 3.0.17 => 3.0.17 
    npmGlobalPackages:
      typescript: 4.1.2
```

**Comment by ty-xy** [comment]
已经解决自问自答吧 文档这样的
<template>
  <live-player src="url" mode="live" autoplay  />
</template>
实际是这样的
<template>
  <live-player src="url" mode="live" autoplay="true" />
</template>
大神们抽空更新下文档不要用cv大法，差点都换框架了

**Comment by Chen-jj** [comment]
@ty-xy 图好像没出来，文档有问题可以直接点下方的修改按钮给我们提 PR 哈，欢迎为开源作贡献～

![image](https://user-images.githubusercontent.com/11807297/110786725-704a5100-82a7-11eb-918d-3edcea77fdd9.png)
