### ISSUE TITLE
两个页面相互跳转超过两次以后, 点击左上角返回上一页面时候,componentDidShow 会不触发

### ISSUE THREAD

**Issue by Oldboyyyy** [NervJS/taro#8874]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Oldboyyyy/Taro-issue-demo.git](https://github.com/Oldboyyyy/Taro-issue-demo.git)
**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
1. 写两个页面, 页面 A 和页面 B
2. A,B 两个页面相互跳转,当页面栈超过四个以后, 点击左上角的返回按钮
```
// 假设页面栈如下
[A,B,A,B,A]
// 返回 
[A,B,A,B] B 页面的 componentDidShow 触发
// 返回
[A,B,A] A 页面的 componentDidShow 触发
// 返回
[A,B] B 页面的 componentDidShow 不触发
// 返回
[A]A 页面的 componentDidShow 不触发
```

试了下`原生的支付宝小程序`和`原生微信小程序`均没有此问题

当在页面路径后面拼上一个时间戳, 每次返回都可以触发当前页面的`componentDidShow`钩子
`/pages/home/index?t=${Date.now()}`

### 期望结果
跟原生一致,每次都可以触发componentDidShow钩子

### 实际结果
componentDidShow钩子未触发

### 环境信息
```
👽 Taro v3.1.1


  Taro CLI 3.1.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      @tarojs/components: 3.1.1 => 3.1.1 
      @tarojs/mini-runner: 3.1.1 => 3.1.1 
      @tarojs/react: 3.1.1 => 3.1.1 
      @tarojs/runtime: 3.1.1 => 3.1.1 
      @tarojs/taro: 3.1.1 => 3.1.1 
      @tarojs/webpack-runner: 3.1.1 => 3.1.1 
      babel-preset-taro: 3.1.1 => 3.1.1 
      eslint-config-taro: 3.1.1 => 3.1.1 
      react: ^17.0.0 => 17.0.1 
```

**Comment by Oldboyyyy** [comment]
![image](https://user-images.githubusercontent.com/14163019/110784715-f913bd80-82a4-11eb-8c44-dc9e88558d72.png)
这里的` Map `是用页面路径作为` key` 的, 统一页面只能存一次, 导致后面的 `onShow` 钩子不会被执行

**Comment by wuchangming** [comment]
@Oldboyyyy 
如果页面的参数完全一致确实有这个问题，我们是通过类似你下面说的方案解决的。加个随机参数保证同一页面的被多次加载时参数不同。
```
当在页面路径后面拼上一个时间戳, 每次返回都可以触发当前页面的componentDidShow钩子
/pages/home/index?t=${Date.now()}
```
