### ISSUE TITLE
设置别名之后，打包失败 找不到模块儿

### ISSUE THREAD

**Issue by dompling** [NervJS/taro#8880]
### 相关平台
微信小程序

**小程序基础库: 2.11.3**
**使用框架: React**

### 复现步骤
设置了别名  '@/*': path.resolve(__dirname, '..', 'src/') 在项目里面 使用@/api/login 时编译失败

### 期望结果
打包成功

### 实际结果

./src/pages/home/index.tsx (./node_modules/_babel-loader@8.0.6@babel-loader/lib!./src/pages/home/index.tsx)
Module not found: Error: Can't resolve '@/api/login' in '/Users/apple/Desktop/JNC-TPM-WX-TARO/src/pages/home'
resolve '@/api/login' in '/Users/apple/Desktop/JNC-TPM-WX-TARO/src/pages/home'
  Parsed request is a module
  using description file: /Users/apple/Desktop/JNC-TPM-WX-TARO/package.json (relative path: ./src/pages/home)
    resolve as module
      /Users/apple/Desktop/JNC-TPM-WX-TARO/src/pages/home/node_modules doesn't exist or is not a directory
      /Users/apple/Desktop/JNC-TPM-WX-TARO/src/pages/node_modules doesn't exist or is not a directory
      /Users/apple/Desktop/JNC-TPM-WX-TARO/src/node_modules doesn't exist or is not a directory
      /Users/apple/Desktop/node_modules doesn't exist or is not a directory
      /Users/apple/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/apple/Desktop/JNC-TPM-WX-TARO/node_modules
     

### 环境信息
```
👽 Taro v3.1.2


  Taro CLI 3.1.2 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.22 => 3.0.22 
      @tarojs/components: 3.0.22 => 3.0.22 
      @tarojs/mini-runner: 3.0.22 => 3.0.22 
      @tarojs/react: 3.0.22 => 3.0.22 
      @tarojs/runtime: 3.0.22 => 3.0.22 
      @tarojs/taro: 3.0.22 => 3.0.22 
      @tarojs/webpack-runner: 3.0.22 => 3.0.22 
      babel-preset-taro: 3.0.22 => 3.0.22 
      eslint-config-taro: 3.0.22 => 3.0.22 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

**Comment by Chen-jj** [comment]
@dompling 用法错了。

```js
// config/index.js
config = {
  alias: {
    '@': path.resolve(__dirname, '..', 'src/')
  }
}
```

```js
// tsconfig.json
{
  "compilerOptions": {
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
```
