### ISSUE TITLE
Linaria 的 styled(View) 写法传参错误

### ISSUE THREAD

**Issue by liaokaime** [NervJS/taro#8883]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
```
const A = styled(View)<{customColor: string}>`
  color: ${p => p.customColor};
`
const B = styled.view<{customColor: string}>`
  color: ${p => p.customColor};
`
```

### 期望结果
二者都可使用

### 实际结果
其中A写法会报错，错误信息为：
```
S2345: Argument of type '(p: any) => any' is not assignable to parameter of type 'StaticPlaceholder'.   Property '__linaria' is missing in type '(p: any) => any' but required in type 'StyledMeta'.
```

### 环境信息
```
  Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\liaokai\AppData\Roaming\npm\yarn.CMD
      npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD

```

**Comment by wwwpalmercom** [comment]
官网的案例是 A 写法，但是 A写法会报错，让人 误解

**Comment by wadwings** [comment]
类型“Styled”上不存在属性“swiperItem”
这种情况会导致B写法也出错，已知会出错组件包括swiperItem Swiper

**Comment by biluochun** [comment]
> 官网的案例是 A 写法，但是 A写法会报错，让人 误解

我们目前的临时方案是
```ts
import { View } from '@tarojs/components';
export const StyledView = View as React.FC;
``` 
然后使用时
```ts
const Style = styled(StyledView)`
`;
```

**Comment by lijun2017** [comment]
> ### 相关平台
> 微信小程序
> 
> **小程序基础库: 2.15.0**
> **使用框架: React**
> 
> ### 复现步骤
> ```
> const A = styled(View)<{customColor: string}>`
>   color: ${p => p.customColor};
> `
> const B = styled.view<{customColor: string}>`
>   color: ${p => p.customColor};
> `
> ```
> 
> ### 期望结果
> 二者都可使用
> 
> ### 实际结果
> 其中A写法会报错，错误信息为：
> 
> ```
> S2345: Argument of type '(p: any) => any' is not assignable to parameter of type 'StaticPlaceholder'.   Property '__linaria' is missing in type '(p: any) => any' but required in type 'StyledMeta'.
> ```
> 
> ### 环境信息
> ```
>   Taro CLI 3.1.1 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
>       Yarn: 1.22.4 - C:\Users\liaokai\AppData\Roaming\npm\yarn.CMD
>       npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
> ```

你好，我想问一下，目前您是使用的B方案写的吗？有没有什么兼容性问题

**Comment by lijun2017** [comment]
> > 官网的案例是 A 写法，但是 A写法会报错，让人 误解
> 
> 我们目前的临时方案是
> 
> ```ts
> import { View } from '@tarojs/components';
> export const StyledView = View as React.FC;
> ```
> 
> 然后使用时
> 
> ```ts
> const Style = styled(StyledView)`
> `;
> ```

您好，问一下，像您这么写，目前有没有出现什么兼容性问题。

**Comment by wcldyx** [comment]
在 global.d.ts 文件里面添加类型扩展,可以解决这个问题作为过渡，等官方修复
```ts
import { CSSProperties } from 'react';
declare module '@tarojs/components/types/View' {
  interface ViewProps {
    style?: CSSProperties;
  }
}

declare module '@tarojs/components/types/Button' {
  interface ButtonProps {
    style?: CSSProperties;
  }
}

declare module '@tarojs/components/types/Text' {
  interface TextProps {
    style?: CSSProperties;
  }
}
```

**Comment by tourze** [comment]
关注

**Comment by Chen-jj** [comment]
暂时可以这样绕过：

```ts
import { View, ViewProps } from '@tarojs/components'

type ViewPropsWithReactStyle = ViewProps & {style?: React.CSSProperties}
const A = styled(View)<{customColor: string}, ViewPropsWithReactStyle>`
  color: ${p => p.customColor};
`
```

**Comment by ZakaryCode** [comment]
由于各种历史原因， Taro 并不打算更改组件 props 中 style 的类型，但是你可以使用以下的方法跳过该问题

```ts
import { styled } from '@linaria/react'
import { View, ViewProps } from '@tarojs/components'

import React from 'react'
import './index.scss'

declare type Component<TProps> = ((props: TProps) => any) | {
  new (props: TProps): any
}

type VPS = ViewProps & { style?: React.CSSProperties }
type TP = VPS & { color: string }
const Title = styled<TP, VPS, Component<TP>>(View)`
  color: ${props => props.color}
`
const Index: React.FC = () => {
  return <Title color='red'>
    Hello World!
  </Title>
}

export default Index

```

**Comment by Howie126313** [comment]
> 由于各种历史原因， Taro 并不打算更改组件 props 中 style 的类型，但是你可以使用以下的方法跳过该问题
> 
> ```ts
> import { styled } from '@linaria/react'
> import { View, ViewProps } from '@tarojs/components'
> 
> import React from 'react'
> import './index.scss'
> 
> declare type Component<TProps> = ((props: TProps) => any) | {
>   new (props: TProps): any
> }
> 
> type VPS = ViewProps & { style?: React.CSSProperties }
> type TP = VPS & { color: string }
> const Title = styled<TP, VPS, Component<TP>>(View)`
>   color: ${props => props.color}
> `
> const Index: React.FC = () => {
>   return <Title color='red'>
>     Hello World!
>   </Title>
> }
> 
> export default Index
> ```
```
ERROR in ./src/pages/index/test.tsx
Module build failed (from ./node_modules/@linaria/webpack-loader/lib/index.js):
Error: [BABEL] /Users/bryan/Desktop/myApp/src/pages/index/test.tsx: .key is not a valid Plugin property
    at forEach (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:112:42)
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:101:20)
    at /Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/full.ts:358:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:10:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:251:28)
    at Function.sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:89:14)
    at sync (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:83:25)
    at sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:182:19)
    at onFirstPause (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:210:24)
```
这样写会报这个错

**Comment by Howie126313** [comment]
> > 由于各种历史原因， Taro 并不打算更改组件 props 中 style 的类型，但是你可以使用以下的方法跳过该问题
> > ```ts
> > import { styled } from '@linaria/react'
> > import { View, ViewProps } from '@tarojs/components'
> > 
> > import React from 'react'
> > import './index.scss'
> > 
> > declare type Component<TProps> = ((props: TProps) => any) | {
> >   new (props: TProps): any
> > }
> > 
> > type VPS = ViewProps & { style?: React.CSSProperties }
> > type TP = VPS & { color: string }
> > const Title = styled<TP, VPS, Component<TP>>(View)`
> >   color: ${props => props.color}
> > `
> > const Index: React.FC = () => {
> >   return <Title color='red'>
> >     Hello World!
> >   </Title>
> > }
> > 
> > export default Index
> > ```
> 
> ```
> ERROR in ./src/pages/index/test.tsx
> Module build failed (from ./node_modules/@linaria/webpack-loader/lib/index.js):
> Error: [BABEL] /Users/bryan/Desktop/myApp/src/pages/index/test.tsx: .key is not a valid Plugin property
>     at forEach (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:112:42)
>     at Array.forEach (<anonymous>)
>     at validatePluginObject (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:101:20)
>     at /Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/full.ts:358:21
>     at Generator.next (<anonymous>)
>     at Function.<anonymous> (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:10:3)
>     at Generator.next (<anonymous>)
>     at evaluateSync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:251:28)
>     at Function.sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:89:14)
>     at sync (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:83:25)
>     at sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:182:19)
>     at onFirstPause (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:210:24)
> ```
> 
> 这样写会报这个错

看着像是 @babel/core 版本导致的问题，https://github.com/callstack/linaria/pull/1061

**Comment by githubCK** [comment]
> > > 由于各种历史原因， Taro 并不打算更改组件 props 中 style 的类型，但是你可以使用以下的方法跳过该问题
> > > ```ts
> > > import { styled } from '@linaria/react'
> > > import { View, ViewProps } from '@tarojs/components'
> > > 
> > > import React from 'react'
> > > import './index.scss'
> > > 
> > > declare type Component<TProps> = ((props: TProps) => any) | {
> > >   new (props: TProps): any
> > > }
> > > 
> > > type VPS = ViewProps & { style?: React.CSSProperties }
> > > type TP = VPS & { color: string }
> > > const Title = styled<TP, VPS, Component<TP>>(View)`
> > >   color: ${props => props.color}
> > > `
> > > const Index: React.FC = () => {
> > >   return <Title color='red'>
> > >     Hello World!
> > >   </Title>
> > > }
> > > 
> > > export default Index
> > > ```
> > 
> > 
> > ```
> > ERROR in ./src/pages/index/test.tsx
> > Module build failed (from ./node_modules/@linaria/webpack-loader/lib/index.js):
> > Error: [BABEL] /Users/bryan/Desktop/myApp/src/pages/index/test.tsx: .key is not a valid Plugin property
> >     at forEach (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:112:42)
> >     at Array.forEach (<anonymous>)
> >     at validatePluginObject (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/validation/plugins.ts:101:20)
> >     at /Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/config/full.ts:358:21
> >     at Generator.next (<anonymous>)
> >     at Function.<anonymous> (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:10:3)
> >     at Generator.next (<anonymous>)
> >     at evaluateSync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:251:28)
> >     at Function.sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:89:14)
> >     at sync (/Users/bryan/Desktop/myApp/node_modules/@linaria/shaker/node_modules/@babel/core/src/gensync-utils/async.ts:83:25)
> >     at sync (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:182:19)
> >     at onFirstPause (/Users/bryan/Desktop/myApp/node_modules/gensync/index.js:210:24)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样写会报这个错
> 
> 看着像是 @babel/core 版本导致的问题，[callstack/linaria#1061](https://github.com/callstack/linaria/pull/1061)

这个问题貌似还存在,求修复

**Comment by mzvast** [comment]
任何进展？

**Comment by luankefei** [comment]
仍然没有任何进展？

**Comment by lixingjuan** [comment]
仍然没有任何进展？
