### ISSUE TITLE
生成的wxml中莫名其妙的多了很多空格，对某些样式效果产生影响

### ISSUE THREAD

**Issue by bug4j** [NervJS/taro#8884]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: Vue 2**

### 复现步骤
1. 新建一个页面demo.vue,内容如下
```html
<template>
  <view style="width:100%">
    <view class="item">
      <text>Taro</text>
    </view>
    <view class="item">
      <text>Vue</text>
    </view>
  </view>
</template>

<script>
export default {

}
</script>
<style>
  .item {
    display: inline-block;
    width: 40%;
    box-sizing: border-box;
    height: 8em;
    line-height: 8em;
    text-align: center;
    background-color: coral;
    color: #fff;
  }
</style>
```
2. 打开此页面，正常情况下 两个 view.item 之间应该无缝拼接，但是实际上会隔开一点，应为生成的wxml中两个元素之间多了一个空格：
![demo](https://img11.360buyimg.com/img/jfs/t1/142453/4/14689/10658/604b1cf7E65fd0369/9ae207e85828b18a.png) 
导致实际效果如下：
![view](https://img11.360buyimg.com/img/jfs/t1/140168/1/14707/7085/604b1cabEfea6c8ce/6629cd20fbb468c4.png) 

### 期望结果
减少生成不必要的空格

### 实际结果
生成了很多多余的空格，影响内联元素之间的距离

### 环境信息
```
👽 Taro v3.1.1
  Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - D:\Develop\node-v12.16.1-win-x64\node.EXE
      npm: 6.14.11 - D:\Develop\node-v12.16.1-win-x64\npm.CMD  
```

**Comment by chenchenpp** [comment]
vue3也有相同问题，taro3.5.8
