### ISSUE TITLE
Taro3.2 RN不支持defineConstants

### ISSUE THREAD

**Issue by tourze** [NervJS/taro#8893]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
config/index.js中配置：

```
  defineConstants: {
    APP_NAME: JSON.stringify('test'),
  },
```

然后在 src/app.js 中打印 APP_NAME，报错：`ReferenceError: Can't find variable: APP_NAME`

### 期望结果
正常使用，输出 test

### 实际结果
ReferenceError: Can't find variable: APP_NAME

### 环境信息
```
  Taro CLI 3.2.0-beta.2 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.0-beta.2 => 3.2.0-beta.2 
      @tarojs/components: 3.2.0-beta.2 => 3.2.0-beta.2 
      @tarojs/mini-runner: 3.2.0-beta.2 => 3.2.0-beta.2 
      @tarojs/react: 3.2.0-beta.2 => 3.2.0-beta.2 
      @tarojs/runtime: 3.2.0-beta.2 => 3.2.0-beta.2 
      @tarojs/taro: 3.2.0-beta.2 => 3.2.0-beta.2 
      @tarojs/webpack-runner: 3.2.0-beta.2 => 3.2.0-beta.2 
      babel-preset-taro: 3.2.0-beta.2 => 3.2.0-beta.2 
      eslint-config-taro: 3.2.0-beta.2 => 3.2.0-beta.2 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      react: ^17.0.0 => 17.0.1 
      react-native: 0.63.4 => 0.63.4 
    npmGlobalPackages:
      typescript: 2.4.2

```

**Comment by tourze** [comment]
![image](https://user-images.githubusercontent.com/13899502/110948266-19627b80-837c-11eb-968b-cd34bb1c9e2f.png)

看代码有实现，但是不生效。

**Comment by shinken008** [comment]
你是在 app.config 里面使用的？ @tourze

**Comment by shinken008** [comment]
@tourze 嗨，我在 app.js 声明的 constant 没有报错，请确认你的描述是否有误。
另外我很怀疑你是在 app.config 里面去使用的，这个RN端跟其他端保持一致，这个文件不支持常量编译配置。

**Comment by shinken008** [comment]
![image](https://user-images.githubusercontent.com/14921035/111726699-6676ae00-88a4-11eb-8a29-8fd41ac44458.png)
![image](https://user-images.githubusercontent.com/14921035/111726714-6bd3f880-88a4-11eb-8a59-2b2e1b1269ac.png)
![image](https://user-images.githubusercontent.com/14921035/111726755-79897e00-88a4-11eb-97e7-27f88624a213.png)
