### ISSUE TITLE
【这是不合理的】pxTransform 在 h5 中在 H5 中运行需要把配置中的 `designWidth` 作为第二个参数传入

### ISSUE THREAD

**Issue by SyMind** [NervJS/taro#8896]
### 这个特性解决了什么问题？
1. taro 2.x 项目迁移至 taro 3.x 项目中需要处理该 api 的兼容性问题，与 taro 2.x 保持一致是好的；
2. 本身项目配置中就存在 designWidth 参数，读取它应是框架的职责，该 api 变更将复杂度暴露给用户是坏的；
3. 所有端的 api 尽可能保持一致是好的。

### 这个 API 长什么样？
function pxTransform (size: number): number;

**Comment by missmimia** [comment]
一个月过去了 😢 这个问题啥时候能解决😂
