### ISSUE TITLE
怎么关闭 template 功能？

### ISSUE THREAD

**Issue by LengYXin** [NervJS/taro#8899]
### 这个特性解决了什么问题？
也就是怎么关闭生成的 base.wxml 文件。不使用这个 模式。在配置中没有找到对应配置。
望解答

### 这个 API 长什么样？
关闭 base.wxml 生成的 template

**Comment by Chen-jj** [comment]
Taro3 的原理就是使用 `<template>` 进行渲染，无法剥离 base.wxml
