### ISSUE TITLE
使用第三方npm包问题

### ISSUE THREAD

**Issue by juvham** [NervJS/taro#89]
使用了 echarts  npm包安装 过程失败。

目前不支持使用第三方的 npm包么？

**Comment by luckyadam** [comment]
有失败截图看看么

**Comment by azoth1991** [comment]
请问taro里面使用echart的demo能写完整点吗，跑不起来啊，debug发现传的height是0

**Comment by luckyadam** [comment]
@azoth1991 你应该是缺少了样式，canvas 没有定宽高
