### ISSUE TITLE
为什么我有时候写着写着就报错了但是编译这边没有报错

### ISSUE THREAD

**Issue by EForinaJ** [NervJS/taro#890]
我有时候写着写着就自动报错啥也出不来，这个错误也不知道是哪的错误
他说我是找不到什么这个taro-ui 但是我已经安装引入了 还是报错 确认安装引入了

![qq 20181020002616](https://user-images.githubusercontent.com/22424208/47231275-0a6f7d00-d3ff-11e8-9c85-58c693f236cd.png)

**Comment by luckyadam** [comment]
应该是微信开发者工具的问题，重启下开发者工具就好了

**Comment by EForinaJ** [comment]
> 应该是微信开发者工具的问题，重启下开发者工具就好了

不知道 经常性的编译没有任何报错 然后 小程序控制台就报错了
![qq 20181028014822](https://user-images.githubusercontent.com/22424208/47607512-9151d480-da53-11e8-926b-a5e6408ff333.png)  
 左边编译的时候没有任何问题 但是控制台报错  然后等几分钟重新编译 又可以了   这是什么bug？

**Comment by luckyadam** [comment]
小程序开发工具的 bug，重启即好
