### ISSUE TITLE
taro 2 版本如何 快速实现 使用微信新的标签组件  keyboard-accessory

### ISSUE THREAD

**Issue by keepresolve** [NervJS/taro#8901]
### 这个特性解决了什么问题？
微信 组件增加 跟新 能够及时的可以在taro 中使用 

### 这个 API 长什么样？
Taro 可以自己扩展一个组件功能  比如微信新增加的   keyboard-accessory

**Comment by Chen-jj** [comment]
Taro3 才支持自定义扩展组件和 API
