### ISSUE TITLE
Error: 没有找到页面实例。

### ISSUE THREAD

**Issue by zuozhea** [NervJS/taro#8902]
### 相关平台
微信小程序

**小程序基础库: 2.16.0**
**使用框架: Nerv**

### 复现步骤
==>app.js

import Nerv, { Component } from 'nervjs';
import { Provider } from '@tarojs/redux';
import configStore from './store';
import { AtTabBar } from 'taro-ui'
import './app.less';

const store = configStore();
class App extends Component {

  componentDidMount() {
    console.log(Provider, store)
  }

  componentDidShow() { }

  componentDidHide() { }

  componentDidCatchError() { }

  render() {
    return (
      <div>111</div>
    )  
  }
}

export default App

### 期望结果
希望刻印正常运行

### 实际结果
页面挂了

### 环境信息
```


👽 Taro v3.0.7

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

  Taro CLI 3.0.7 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.7 => 3.0.7 
      @tarojs/components: 3.0.7 => 3.0.7 
      @tarojs/mini-runner: 3.0.7 => 3.0.7 
      @tarojs/runtime: 3.0.7 => 3.0.7 
      @tarojs/taro: 3.0.7 => 3.0.7 
      @tarojs/webpack-runner: 3.0.7 => 3.0.7 
      babel-preset-taro: 3.0.7 => 3.0.7 
      eslint-config-taro: 3.0.7 => 3.0.7 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.0 => 1.5.7 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

**Comment by zuozhea** [comment]
render() {
    return (
      <div>111</div>
    )  
  }

**Comment by zuozhea** [comment]
” render() {
    return (
      <div>111</div>
    )  
  }“

**Comment by zuozhea** [comment]
![image](https://user-images.githubusercontent.com/11309065/111110076-ddefc900-8596-11eb-97e4-ff1d10ad94aa.png)

**Comment by ntop001** [comment]
@zuozhea 楼主问题解决了没，遇到类似问题。

**Comment by Ttou** [comment]
vue2 按照官方文档写 app.js 也有这个问题，不能用 new Vue 包装

**Comment by Chen-jj** [comment]
@Ttou 文档应该已经更新了：

![image](https://user-images.githubusercontent.com/11807297/125014078-94743e00-e09f-11eb-809a-e76ee995200b.png)

**Comment by Chen-jj** [comment]
@zuozhea @ntop001 改用 react 咯

**Comment by kaifa-yang** [comment]
如果用react呢，入口组件该怎么改才能避免这种情况

**Comment by Chen-jj** [comment]
> 如果用react呢，入口组件该怎么改才能避免这种情况

新建一条 issue 并提供一下 demo 看看咯
