### ISSUE TITLE
自定义tabbar中，使用useRouter会出现null

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [NervJS/taro#8906]
### 相关平台
微信小程序

**小程序基础库: 2.14.1**
**使用框架: React**

### 复现步骤
自定义tabbar，然后再tabbar组件中使用useRouter来匹配当前的激活的tab。
默认首页是可以生效的，
但是一旦发生Taro.switchTab后，useRouter会出现null，导致无法匹配到正确的激活项

### 期望结果
希望能解决这个问题。

### 实际结果
useRouter执行结果为nul

### 环境信息
```
  Taro CLI 3.1.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.0 - D:\software\nodejs\node.EXE
      Yarn: 1.23.0-20200306.1615 - D:\software\yarn\bin\yarn.CMD
      npm: 6.14.8 - D:\software\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
不建议这样做，还是推荐使用状态管理工具进行管理。

详细原因在此处有说明：https://github.com/NervJS/taro/issues/7302#issuecomment-1048521098
