### ISSUE TITLE
Button组件内部的Button无法正常编译

### ISSUE THREAD

**Issue by lbb1811** [NervJS/taro#8918]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/lbb1811/snippets/blob/master/src/pages/index/index.jsx](https://gitee.com/lbb1811/snippets/blob/master/src/pages/index/index.jsx)
**小程序基础库: 2.16.0**
**使用框架: React**

### 复现步骤
```jsx
<Button>
  测试111
  <Button>测试222</Button>
  <View>测试333</View>
</Button>
```

### 期望结果
编译后内部有button

### 实际结果
内部的button不见了。

### 环境信息
```
Taro CLI 3.1.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
`Button` 不应该嵌套自身吧。。Taro 为了优化模板体积，只允许可以嵌套的组件进行嵌套

**Comment by lbb1811** [comment]
我的项目中在`Button`中引用了弹窗组件，弹窗组件中又有`Button`，导致无法渲染。因为内外两个`Button`都按需加`openType`调用微信的api，所以不好直接去掉。
我这个项目是Taro2.x，现在想升级Taro3.x目前卡在这里了。

**Comment by lbb1811** [comment]
多谢大佬。🤞
