### ISSUE TITLE
ubuntu1804下taro不能新建项目

### ISSUE THREAD

**Issue by regreceive** [NervJS/taro#892]
**问题描述**
ubuntu v18.04
yarn v1.10.1
node v8.10.0

用yarn安装@tarojs/cli，新建taro项目。会提示缺失taro-init
 $ taro init app
👽 Taro v1.0.7

error: taro-init(1) does not exist, try --help

**复现步骤**
删除taro，重新安装，问题依旧

**期望行为**
新建项目成功

**系统信息**

ubuntu v18.04
yarn v1.10.1
node v8.10.0

**Comment by gmaso** [comment]
我的deepin系统，之前用yarn安装完也有问题。之后用npm重装taro，然后可以了。
你可以试下用npm，不要用yarn

**Comment by regreceive** [comment]
> 我的deepin系统，之前用yarn安装完也有问题。之后用npm重装taro，然后可以了。
> 你可以试下用npm，不要用yarn

谢谢，按照你的办法运行起来了，看来目前taro不能使用yarn。
