### ISSUE TITLE
taro 最新 react 模板 h5 无法运行

### ISSUE THREAD

**Issue by CristalFJJ** [NervJS/taro#8926]
### 相关平台
H5

**浏览器版本: Chrome 88**
**使用框架: React**

### 复现步骤
1、初始化：taro init React
2、运行本地开发环境：执行 npm run dev:h5
3、页面无法显示，浏览器控制台就报错
4、错误信息： Uncaught Error: React Refresh runtime should not be included in the production bundle.

### 期望结果
正常运行hello world

### 实际结果
无法运行

### 环境信息
```
Taro v3.1.3


  Taro CLI 3.1.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - D:\yarn\bin\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
3.1.4 修复了

**Comment by CristalFJJ** [comment]
> 3.1.4 修复了

升版本可以了，感谢

**Comment by zhangminggeek** [comment]
3.3.9 版本还是会报这个错
