### ISSUE TITLE
升级至3.1.3 打包提示找不到页面实例

### ISSUE THREAD

**Issue by lunaticYoung** [NervJS/taro#8930]
### 相关平台
微信小程序

**小程序基础库: 2.16.0**
**使用框架: Vue 2**

### 复现步骤
升级taro-cli至3.1.3， Taro版本也到3.1.3，相关版本也都是3.1.3，结果打包失败，提示没有找到页面实例

### 期望结果
打包正常，可以调用getUserProfile()新API

### 实际结果
打包失败

### 环境信息
```
👽 Taro v3.1.3


  Taro CLI 3.1.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.10.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.1.3 => 3.1.3 
      @tarojs/mini-runner: 3.1.3 => 3.1.3 
      @tarojs/runtime: 3.1.3 => 3.1.3 
      @tarojs/taro: 3.1.4 => 3.1.4 
      @tarojs/webpack-runner: ^3.0.27 => 3.1.4 
      babel-preset-taro: 3.1.3 => 3.1.3 
      eslint-config-taro: 3.1.3 => 3.1.3 
    npmGlobalPackages:
      typescript: 3.5.3
```

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/111264385-5d969a00-8662-11eb-8def-0b8519a91d42.png)

**Comment by lunaticYoung** [comment]
是webpack-runner版本问题吗？所以到底应该用哪个版本呢   最新的 3.1.4？

**Comment by Chen-jj** [comment]
CLI 和依赖版本保持一致

**Comment by mingtianyihou33** [comment]
3.2.0也有这个问题 
 Taro CLI 3.2.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.0 => 3.2.0 
      @tarojs/components: 3.2.0 => 3.2.0 
      @tarojs/mini-runner: 3.2.0 => 3.2.0 
      @tarojs/runtime: 3.2.0 => 3.2.0 
      @tarojs/taro: 3.2.0 => 3.2.0 
      @tarojs/webpack-runner: 3.2.0 => 3.2.0 
      babel-preset-taro: 3.2.0 => 3.2.0 
      eslint-config-taro: 3.2.0 => 3.2.0 

启动后就报这个错
![image](https://user-images.githubusercontent.com/22953606/113674449-c8c90e80-96ec-11eb-9390-a785260f8984.png)

**Comment by mingtianyihou33** [comment]
```
const App = {
  store,
  onShow(options) {
    console.log('app onShow ', options)
  },
  async onLaunch() {
    console.log('app onLaunch')
    await store.dispatch('user/load')
  },
  render(h) {
    // this.$slots.default 是将要会渲染的页面
    return h('block', this.$slots.default)
  },
}

export default App
```
导出的App不要加上new Vue就可以了

**Comment by ldc-37** [comment]
3.2.1 问题依然存在

用 @mingtianyihou33 的方法可以正常运行

但是文档上不是这么用的吧 /doge

**Comment by Chen-jj** [comment]
Taro v3.1 有一个 Breaking，@mingtianyihou33 的回答正解

 ![image](https://user-images.githubusercontent.com/11807297/115991432-f07c0a00-a5fa-11eb-94b8-d841b19422a8.png)

> 3.2.1 问题依然存在
> 
> 用 @mingtianyihou33 的方法可以正常运行
> 
> 但是文档上不是这么用的吧 /doge

我们修改一下文档。
