### ISSUE TITLE
response header 没有信息

### ISSUE THREAD

**Issue by yoke233** [NervJS/taro#8931]
### 相关平台
H5

**浏览器版本: 微信开发者工具**
**使用框架: React**

### 复现步骤
使用Taro.addInterceptor 添加的拦截器 

 return chain.proceed(requestParams).then((res) => {

在res中获取header 只有 content-type: "application/json;charset=UTF-8"

没有其他任何信息

### 期望结果
服务端设置返回了 new-token

### 实际结果
无法读取到new-token

### 环境信息
```
� Taro v3.1.3


  Taro CLI 3.1.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.7.0 - D:\dev\scoop\apps\nodejs\current\node.EXE
      Yarn: 1.22.5 - D:\dev\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
      npm: 6.14.7 - D:\dev\scoop\apps\nodejs\current\npm.CMD


```

**Comment by ZakaryCode** [comment]
未验证到相关问题，如有需要可以提交 demo 辅助定位

**Comment by lei40251** [comment]
这个咋解决的呀？
