### ISSUE TITLE
3.1.3更新后，页面的index.config.ts的配置不生效

### ISSUE THREAD

**Issue by 179778978** [NervJS/taro#8932]
### 相关平台
微信小程序

**小程序基础库: 2.16.0**
**使用框架: React**

### 复现步骤
升级到3.1.3以后，页面自定义的index.config.ts的配置不生效，navigationBarTitleText，navigationBarBackgroundColor使用的是默认的配置

### 期望结果
期望能够使用页面自定义的配置

### 实际结果
使用的是默认的配置

### 环境信息
```
Taro CLI 3.1.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.1.3 => 3.1.3
      @tarojs/mini-runner: 3.1.3 => 3.1.3
      @tarojs/react: 3.1.3 => 3.1.3
      @tarojs/runtime: 3.1.3 => 3.1.3
      @tarojs/taro: 3.1.3 => 3.1.3
      @tarojs/webpack-runner: 3.1.3 => 3.1.3
      babel-preset-taro: 3.1.3 => 3.1.3
      eslint-config-taro: 3.1.3 => 3.1.3
      react: ^17.0.0 => 17.0.1
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10
```

**Comment by luckyadam** [comment]
升级到 3.1.4 试试

**Comment by A-ANing** [comment]
![image](https://user-images.githubusercontent.com/43433064/121482515-d017db80-c9ff-11eb-8b9e-77809b8281d8.png)
我这里也失效了，并且不是所有页面都失效；
仅仅只有两三个页面失效，开发前是生效的，没有动代码，前两天打开项目就这样了，并且到现在还是这样；
不管我dev:weapp  还是 build:weapp  都是一样的，并且真机上也是一样；

我的taro版本3.1.4

![image](https://user-images.githubusercontent.com/43433064/121482972-41578e80-ca00-11eb-8232-6de2dd08382d.png)
@luckyadam

**Comment by liqingitt** [comment]
我的也是这样
