### ISSUE TITLE
H5 Input 受控组件在重新赋值时去掉输入字符串中的空格，输入框数据没有发生改变

### ISSUE THREAD

**Issue by dontdrinkmylemontea** [NervJS/taro#8937]
### 相关平台
H5

**浏览器版本: Chrome 版本 89.0.4389.82（正式版本） （64 位）**
**使用框架: React**

### 复现步骤
1. 为Input组件添加onInput事件和绑定this.state.value
2. onInput事件里执行e.detail.value.replace(/\s /g, ''); 替换输入框的空格为空，并重新setState
3. 在输入框输入'           '一串空格
4. 查看输入框内容：空格未被替换。而state的值已经改变

### 期望结果
输入框的中的空格被替换为空字符串
例如输入： '          '，
希望输入框内显示：’‘

### 实际结果
输入框的内容没有被替换，仍然是一串空格

### 环境信息
```
👽 Taro v3.0.27


  Taro CLI 3.0.27 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
若使用e.detail.value.replace(/\s /g, '-');来替换，则可以成功替换。

**Comment by bgy10** [comment]
我也是刚遇到这个问题，h5的input框，setState后根本不会改变

**Comment by Rambos** [comment]
> 我也是刚遇到这个问题，h5的input框，setState后根本不会改变

是的，我也遇到这个问题，有点坑，跟正常的react受控input组件表现不一致

**Comment by ZakaryCode** [comment]
未能复现到该问题
