### ISSUE TITLE
taro-ui-vue 模板创建的问题

### ISSUE THREAD

**Issue by SensitiveMix** [NervJS/taro#8946]
### 相关平台
H5

### 复现仓库
[https://github.com/foliejs/taro-ui-vue-demo](https://github.com/foliejs/taro-ui-vue-demo)
**浏览器版本: Chrome 62****小程序基础库: H5**
**使用框架: Vue 2**

### 复现步骤
Taro 即将创建一个新项目!

Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！
? 请选择框架 Vue
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 taro-ui-vue（使用 taro-ui-vue 的模板）

....

✔ cd taro-demo, 执行 git init
✔ 安装成功

### 期望结果
项目创建成功的结果 package.json 里面应该是没有问题的

### 实际结果
package.json 里面出现了两个 "eslint-plugin-vue": "^6.x",

### 环境信息
```
 Taro CLI 3.1.4 environment info:
    System:
      OS: OS X El Capitan 10.11.6
      Shell: 5.0.8 - /bin/zsh
    Binaries:
      Node: 14.0.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.4 => 3.1.4
      @tarojs/components: 3.1.4 => 3.1.4
      @tarojs/mini-runner: 3.1.4 => 3.1.4
      @tarojs/runtime: 3.1.4 => 3.1.4
      @tarojs/taro: 3.1.4 => 3.1.4
      @tarojs/webpack-runner: 3.1.4 => 3.1.4
      babel-preset-taro: 3.1.4 => 3.1.4
      eslint-config-taro: 3.1.4 => 3.1.4
```

---
### 补充信息
其实并不会影响到实际使用，但是配置了 lint 的话，Package.json 里面出现重复的包是过不了 lint 的

**Comment by Chen-jj** [comment]
上述 PR 中已修复
