### ISSUE TITLE
原生组件事件不能被正确触发

### ISSUE THREAD

**Issue by superNos** [NervJS/taro#8947]
### 相关平台
微信小程序

**小程序基础库: 3.16.0**
**使用框架: React**

### 复现步骤
使用原生组件

onButtonTap不被触发
```javascript
<slideview buttons={slideButtons} onButtonTap={handleButtonTap}>
<slideview>
```
只有绑定bindbuttontap事件，onButtonTap才会被正常触发
```javascript
<slideview buttons={slideButtons} bindbuttontap={handleButtonTap} onButtonTap={handleButtonTap}>
<slideview>
```

### 期望结果
原生组件事件通过onEventName被触发

### 实际结果
需要绑定bind开头的组件才会触发on事件

### 环境信息
```
👽 Taro v3.0.27


  Taro CLI 3.0.27 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.27 => 3.0.27 
      @tarojs/components: 3.0.27 => 3.0.27 
      @tarojs/mini-runner: 3.0.27 => 3.0.27 
      @tarojs/react: 3.0.27 => 3.0.27 
      @tarojs/runtime: 3.0.27 => 3.0.27 
      @tarojs/taro: 3.0.27 => 3.0.27 
      @tarojs/webpack-runner: 3.0.27 => 3.0.27 
      babel-preset-taro: 3.0.27 => 3.0.27 
      eslint-config-taro: 3.0.27 => 3.0.27 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: 16.10.0 => 16.10.0 
      taro-ui: ^3.0.0-alpha.2 => 3.0.0-alpha.3 
```

**Comment by digiaries** [comment]
> ```js
> <slideview buttons={slideButtons} onButtonTap={handleButtonTap}>
> ```

官方的方法名是 [buttontap](https://github.com/wechat-miniprogram/weui-miniprogram/blob/5f1160e360e12f43dfb3c1203a4ad86d938508b1/src/slideview/slideview.ts#L107)

试试这个写法
```html
<slideview onButtontap={handleButtonTap}>
```

**Comment by superNos** [comment]
> > ```js
> > <slideview buttons={slideButtons} onButtonTap={handleButtonTap}>
> > ```
> 
> 官方的方法名是 [buttontap](https://github.com/wechat-miniprogram/weui-miniprogram/blob/5f1160e360e12f43dfb3c1203a4ad86d938508b1/src/slideview/slideview.ts#L107)
> 
> 试试这个写法
> 
> ```
> <slideview onButtontap={handleButtonTap}>
> ```

还真是，感谢
