### ISSUE TITLE
redux-persist 在开发环境和android真机有效，在iOS真机无效，页面白屏

### ISSUE THREAD

**Issue by jackyang1984** [NervJS/taro#8952]
### 相关平台
微信小程序

**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
正常使用redux系列即可，需要安装以下几个插件
"@tarojs/components": "3.0.27",
"@tarojs/react": "3.0.27",
"@tarojs/runtime": "3.0.27",
"@tarojs/taro": "3.0.27",
"react": "^16.10.0",
"react-dom": "^16.10.0",
"react-redux": "^7.2.0",
"redux": "^4.0.0",
"redux-persist": "^6.0.0",
"redux-saga": "^1.1.3",

### 期望结果
首页正常打开

### 实际结果
首页白屏

### 环境信息
```
Taro CLI 3.0.27 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.27 => 3.0.27 
      @tarojs/mini-runner: 3.0.27 => 3.0.27 
      @tarojs/react: 3.0.27 => 3.0.27 
      @tarojs/runtime: 3.0.27 => 3.0.27 
      @tarojs/taro: 3.0.27 => 3.0.27 
      @tarojs/webpack-runner: 3.0.27 => 3.0.27 
      babel-preset-taro: 3.0.27 => 3.0.27 
      react: ^16.10.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

---
### 补充信息
不使用redux-persist 小程序可以正常使用

**Comment by Chen-jj** [comment]
提供一下 demo

**Comment by QingyunYang** [comment]
@jackyang1984 遇到了同样的问题，请问您解决了吗？

**Comment by QingyunYang** [comment]
推荐不要使用 PersistGate

**Comment by Chen-jj** [comment]
Duplicate of #6548
