### ISSUE TITLE
Taro3.1.4 使用 Vant Weapp 时出现默认值丢失

### ISSUE THREAD

**Issue by onlyling** [NervJS/taro#8955]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/onlyling/taro3-vant-demo](https://github.com/onlyling/taro3-vant-demo)
**小程序基础库: 2.15.0**
**使用框架: React**

### 复现步骤
```jsx
<van-button type="default">默认按钮</van-button>
```

size	按钮尺寸，可选值为 normal large small mini，默认值是 normal。

```jsx
<van-button loading type="info" loadingText="加载中..." />
```
loading-type  加载状态图标类型，可选值为 spinner，默认值是 circular。

```jsx
<van-button type="primary" customClass="custom-class">主要按钮</van-button>
<van-button loading type="primary" loadingClass="custom-class">主要按钮</van-button>
```

`外部样式类` 似乎也没有起作用。

### 期望结果
默认值正常，出现 `van-button--normal`。
<img width="803" alt="WX20210323-115719@2x" src="https://user-images.githubusercontent.com/9999765/112090663-f4b5a180-8bce-11eb-95ab-c8c848a44903.png">

<img width="808" alt="WX20210323-141419@2x" src="https://user-images.githubusercontent.com/9999765/112101726-18ceae00-8be2-11eb-8fe0-b1b8d5c0707c.png">

### 实际结果
实际运行的时候并没有 `van-button--normal`。
<img width="877" alt="WX20210323-115513@2x" src="https://user-images.githubusercontent.com/9999765/112090528-aef8d900-8bce-11eb-84f6-728cdc778fba.png">

<img width="827" alt="WX20210323-141325@2x" src="https://user-images.githubusercontent.com/9999765/112101634-f341a480-8be1-11eb-902b-bdbf5378cb2a.png">

### 环境信息
```
  Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.1.4 => 3.1.4 
      @tarojs/mini-runner: 3.1.4 => 3.1.4 
      @tarojs/react: 3.1.4 => 3.1.4 
      @tarojs/runtime: 3.1.4 => 3.1.4 
      @tarojs/taro: 3.1.4 => 3.1.4 
      @tarojs/webpack-runner: 3.1.4 => 3.1.4 
      babel-preset-taro: 3.1.4 => 3.1.4 
      eslint-config-taro: 3.1.4 => 3.1.4 
      react: ^17.0.0 => 17.0.2 
```

**Comment by Chen-jj** [comment]
@onlyling 测试了一下，微信小程序中自定义组件的属性只有**不传时**才使用默认值：

```js
// comp.js
Component({
  properties: {
    type: {
      type: String,
      value: 'default'
    }
  }
})
```

```html
// comp.wxml
<view>
  <view>type: {{type}}</view>
</view>
```

```vue
// page.wxml
// 这样才会使用默认值
<comp>A</comp>

// 这样不会使用默认值
<comp type="{{undefined}}">A</comp>
```

但是，Taro3 的模板（可看 ./dist/base.wxml）是需要默认把所有属性列举并进行写死，`van-button` 的模板：

```html
<van-button type="{{i.type}}" children="{{i.children}}" plain="{{i.plain}}" hairline="{{i.hairline}}" disabled="{{i.disabled}}" loading="{{i.loading}}" loadingType="{{i.loadingType}}" loadingText="{{i.loadingText}}" square="{{i.square}}" round="{{i.round}}" icon="{{i.icon}}" size="{{undefined}}" block="{{i.block}}" color="{{i.color}}" customClass="{{i.customClass}}" loadingClass="{{i.loadingClass}}"  id="{{i.uid}}">
   ...
 </van-button>
```

相当于传入了 `undefined`，所以小程序组件不会使用默认值，这里只能显示传入进行绕过。

**Comment by Chen-jj** [comment]
外部样式类有生效吧：

![image](https://user-images.githubusercontent.com/11807297/116196221-cd219e00-a765-11eb-80be-62fb94fd03cc.png)
