### ISSUE TITLE
Taro.previewIamge()H5环境下预览和返回问题

### ISSUE THREAD

**Issue by FLF1995** [NervJS/taro#8956]
问题描述
taro转换H5嵌入APP，调用Taro.previewImage后，点击返回，视图仍然是图片预览，但实际页面已经跳转
复现步骤

期望行为
图片预览关闭，而页面不会被回退。

报错信息
行为错误，无报错。

系统信息

Taro v1.2 及以上版本已添加 taro info 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

操作系统: [e.g. macOS]
Taro 版本 [e.g. v.3.0.21]
Node.js 版本 [e.g. v12.4.0]
报错平台 [h5]
补充信息
无

**Comment by lzs2000131** [comment]
H5是要点击图片才能关闭的，可以自己写一段来点击返回的时候触发一下点击图片来关闭图片
previewImage: function (current, urls) {
    function bindingClick() {
      if (document.querySelector('.preview-image')) {
        document.querySelector('.preview-image').onclick = null
        document.querySelector('.preview-image').click()
      }
    }
    if (process.env.TARO_ENV === 'h5') {
      window.history.pushState(null, "title", location.href);
      window.addEventListener("popstate", bindingClick)
    }
    Taro.previewImage({
      current: current,
      urls: urls,
      success: function () {
        if (process.env.TARO_ENV === 'h5') {
          document.querySelector('.preview-image').onclick = () => {
            window.removeEventListener("popstate", bindingClick)
            history.back()
          }
        }
      }
    })
  }

**Comment by lzs2000131** [comment]
后来发现H5的previewImage不能双指放大，最终在H5上使用了PhotoSwipe作为替代

**Comment by zprao** [comment]
> 后来发现H5的previewImage不能双指放大，最终在H5上使用了PhotoSwipe作为替代

你是怎么实现的，引用了一个第三方库吗？
