### ISSUE TITLE
@tarojs/taro/3.1.4版本，小程序下拉刷新和上拉加载事件无效

### ISSUE THREAD

**Issue by GreatHonour** [NervJS/taro#8972]
![image](https://user-images.githubusercontent.com/25587991/112754893-d6a5d200-9010-11eb-836d-7a9f115ec519.png)
![image](https://user-images.githubusercontent.com/25587991/112754904-de657680-9010-11eb-8301-9d6d27ee291b.png)

onReachBottom 和onPullDownRefresh无效，版本号如下
![image](https://user-images.githubusercontent.com/25587991/112754919-f5a46400-9010-11eb-9d7b-2c254cadcf44.png)

**Comment by GreatHonour** [comment]
config.ts配置如下
  enablePullDownRefresh: true,
  backgroundTextStyle: 'dark',

**Comment by lyhaha** [comment]
解决了吗？

**Comment by lyhaha** [comment]
> config.ts配置如下
> enablePullDownRefresh: true,
> backgroundTextStyle: 'dark',

配置了也没用啊 v3.1.4
