### ISSUE TITLE
custom-wrapper not found，taro版本3.1.4

### ISSUE THREAD

**Issue by yaobowen2** [NervJS/taro#8989]
复现步骤：
1. taro init wrapper 创建项目

2. 新增组件 src/components/comp.vue

3. src/pages/index/index.vue里引用组件
![image](https://user-images.githubusercontent.com/24604061/112983634-82c1f700-9190-11eb-8f25-818c935274ee.png)

开发者工具异常：
![image](https://user-images.githubusercontent.com/24604061/112983720-9a00e480-9190-11eb-9954-73e082d9603e.png)

**Comment by Mor-hyq** [comment]
vue下无法使用这个custom-wrapper吗？

**Comment by yaobowen2** [comment]
> vue下无法使用这个custom-wrapper吗？

是的，上面有非常简单的复现步骤

**Comment by nyrf** [comment]
custom-wrapper 现在只支持react的吧，我没看vue里有这个组件

**Comment by yaobowen2** [comment]
> custom-wrapper 现在只支持react的吧，我没看vue里有这个组件

base.wxml里没有tmpl_0_custom-wrapper这个template，也就是说，在vue模式下目前没有去支持custom-wrapper，感觉应该是这样
