### ISSUE TITLE
希望项目生成时在根目录添加project.config.json文件

### ISSUE THREAD

**Issue by kapeter** [NervJS/taro#9]
project.config.json是小程序的项目配置文件。
在该文件中设置miniprogramRoot，可以将小程序的根目录指向dist目录。

**Comment by luckyadam** [comment]
非常棒~下个版本加上

**Comment by luckyadam** [comment]
最新版本已经支持~ `v0.0.49`

**Comment by luckyadam** [comment]
@kapeter 最新版本已支持
