### ISSUE TITLE
原生百度小程序 内嵌 两个Taro 3.1.4  App() 多次注册后被覆盖导致页面加载报错 'mount' of undefined

### ISSUE THREAD

**Issue by paulloo** [NervJS/taro#9012]
### 相关平台
百度小程序

### 复现仓库
[https://github.com/paulloo/taro-swan-bugshow](https://github.com/paulloo/taro-swan-bugshow)
**小程序基础库: 3.260.38**
**使用框架: React**

### 复现步骤
再一个原生宿主百度小程序里面，嵌入两个Taro 3.1.4编译后的项目。
原生宿主小程序 ， 同时引入两个 子小程序的  app.js 文件。

### 期望结果
可以正常浏览访问

### 实际结果
报错
[Lifecycle Fail] call Page.onLoad method fail:
  Cannot read property 'mount' of undefined
  TypeError: [Lifecycle Fail] call Page.onLoad method fail:
  Cannot read property 'mount' of undefined

### 环境信息
```
Taro CLI 3.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - D:\Program Files\nodejs\npm.CMD
```

**Comment by paulloo** [comment]
@luckyadam  大佬，请求支援

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/113255843-e700ca00-92fa-11eb-8e87-73927c554547.png)
![Uploading image.png…]()

**Comment by paulloo** [comment]
> 目测 chunkid 冲突了
> 
> ![image](https://user-images.githubusercontent.com/11807297/113255905-fc75f400-92fa-11eb-97f3-e837a0e1e029.png)

感谢答复。
但是我试用了这个方法，依然有问题。

我们是在宿主小程序app.js里面会require  两个目标子小程序的app.js主文件入口。这两个小程序注册的App() 可以区分吗？

**Comment by Chen-jj** [comment]
@paulloo 不需要在原生小程序里 `require` Taro 项目的 `app.js` 入口文件。

你看编译后的文件，`blended` 模式会为每个文件自动 `require app.js`

**Comment by paulloo** [comment]
> @paulloo 不需要在原生小程序里 `require` Taro 项目的 `app.js` 入口文件。
> 
> 你看编译后的文件，`blended` 模式会为每个文件自动 `require app.js`
> 
> 按文档操作，就这 4 步，多个分包就加多 1 步：
> 
> ![image](https://user-images.githubusercontent.com/11807297/113261443-1109ba80-9302-11eb-9235-24271c959441.png)

可以，完美解决了bug。 
--blended   顺便问一下这种打包方式，Components 目录是不会被编译的吗？   
编译后，发现dist/swan 目录下没有Components   组件文件。
