### ISSUE TITLE
English documentation required

### ISSUE THREAD

**Issue by ortonomy** [NervJS/taro#9017]
### 这个特性解决了什么问题？
In this issue: https://github.com/NervJS/taro/issues/315, a developer (rather impolitely asked for English documentation) and this comment https://github.com/NervJS/taro/issues/315#issuecomment-405015678 hilariously missed the mark the foreign developer presence in China: 

>  There are no foreign developers as far as I know.

This is comically inaccurate and ignorant from the commenter. There are many many of us, who are being asked to develop using Taro (e.g. for clients). Are there any plans to have English documentation, or has anyone translated the docs? Links would be useful, thanks.

### 这个 API 长什么样？
N/A

**Comment by ItsRyanWu** [comment]
Think this could be a tough task for Chinese native speakers to complete all documentation in English.

**Comment by Chen-jj** [comment]
Done by https://github.com/NervJS/taro/pull/10199
