### ISSUE TITLE
Taro.options.html.transformElement is undefined,怎么修改HTML中图片的mode

### ISSUE THREAD

**Issue by gingerJY** [NervJS/taro#9019]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/gingerJY/taroMini/blob/master/src/pages/home/index.jsx](https://github.com/gingerJY/taroMini/blob/master/src/pages/home/index.jsx)
**小程序基础库: 2.16.0**
**使用框架: React**

### 复现步骤
运行小程序，可以在console看到Taro.options.html打印为{skipElements: Set(2), voidElements: Set(17), closingElements: Set(15), renderHTMLTag: false}, 不包含transformElement 

### 期望结果
可以使用Taro.options.html.transformElement

### 实际结果
该方法undefined

### 环境信息
```
👽 Taro v3.1.4


  Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
      npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
    npmPackages:
      @tarojs/components: 3.1.4 => 3.1.4 
      @tarojs/mini-runner: 3.1.4 => 3.1.4 
      @tarojs/react: 3.1.4 => 3.1.4 
      @tarojs/runtime: 3.1.4 => 3.1.4 
      @tarojs/taro: 3.1.4 => 3.1.4 
      @tarojs/webpack-runner: 3.1.4 => 3.1.4 
      babel-preset-taro: 3.1.4 => 3.1.4 
      eslint-config-taro: 3.1.4 => 3.1.4 
      react: ^17.0.0 => 17.0.1 
```

---
### 补充信息
想把HTML解析后的图片mode改为widthFix

**Comment by gingerJY** [comment]
有没有知道的同学能回答一下😭

**Comment by Chen-jj** [comment]
@gingerJY 用法错了，这个字段是留给开发者传入一个函数。

![image](https://user-images.githubusercontent.com/11807297/117232259-61b98980-ae53-11eb-909f-e2cd9e8acf56.png)

```js
import { Component } from 'react'
import Taro from "@tarojs/taro";
import { View } from '@tarojs/components'

Taro.options.html.transformElement = (el) => {
  if (el.nodeName === 'image') {
    el.setAttribute('mode', 'widthFix')
  }
  return el
}

export default class Index extends Component {
  render () {
    return (
      <View className='home' dangerouslySetInnerHTML={{ __html: '<img src="https://a/b/c" />' }} />
    )
  }
}
```

**Comment by gingerJY** [comment]
> @gingerJY 用法错了，这个字段是留给开发者传入一个函数。
> 
> ![image](https://user-images.githubusercontent.com/11807297/117232259-61b98980-ae53-11eb-909f-e2cd9e8acf56.png)
> 
> ```js
> import { Component } from 'react'
> import Taro from "@tarojs/taro";
> import { View } from '@tarojs/components'
> 
> Taro.options.html.transformElement = (el) => {
>   if (el.nodeName === 'image') {
>     el.setAttribute('mode', 'widthFix')
>   }
>   return el
> }
> 
> export default class Index extends Component {
>   render () {
>     return (
>       <View className='home' dangerouslySetInnerHTML={{ __html: '<img src="https://a/b/c" />' }} />
>     )
>   }
> }
> ```

谢谢
