### ISSUE TITLE
升级3.1后npm install异常

### ISSUE THREAD

**Issue by GZWZC** [NervJS/taro#9022]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 1**
**使用框架: React**

### 复现步骤
rf -rf node_modules
rm -rf package-lock.json yarn.lock
npm i 

### 期望结果
npm install成功

### 实际结果
npm ERR!

npm ERR! code 1

npm ERR! path /Users/cc/test/node_modules/canvas

npm ERR! command failed

npm ERR! command sh -c node-gyp rebuild

npm ERR! gyp info it worked if it ends with ok

npm ERR! gyp info using node-gyp@3.8.0

npm ERR! gyp info using node@12.18.4 | darwin | x64

npm ERR! gyp info spawn /usr/bin/python2

npm ERR! gyp info spawn args [

npm ERR! gyp info spawn args   '/Users/cc/test/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',

npm ERR! gyp info spawn args   '-f',

npm ERR! gyp info spawn args   'make',

npm ERR! gyp info spawn args   '-I',

npm ERR! gyp info spawn args   
'/Users/cc/test/node_modules/canvas/build/config.gypi',

npm ERR! gyp info spawn args   '-I',

npm ERR! gyp info spawn args   '/Users/cc/test/node_modules/node-gyp/addon.gypi',

npm ERR! gyp info spawn args   '-I',

npm ERR! gyp info spawn args   '/Users/cc/.node-gyp/12.18.4/include/node/common.gypi',

npm ERR! gyp info spawn args   '-Dlibrary=shared_library',

npm ERR! gyp info spawn args   '-Dvisibility=default',

npm ERR! gyp info spawn args   '-
Dnode_root_dir=/Users/cc/.node-gyp/12.18.4',

npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/cc/test/node_modules/node-gyp',

npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/cc/.node-gyp/12.18.4/<(target_arch)/node.lib',

npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/cc/test/node_modules/canvas',

npm ERR! gyp info spawn args   '-Dnode_engine=v8',

npm ERR! gyp info spawn args   '--depth=.',

npm ERR! gyp info spawn args   '--no-parallel',

npm ERR! gyp info spawn args   '--generator-output',

npm ERR! gyp info spawn args   'build',

npm ERR! gyp info spawn args   '-Goutput_dir=.'

npm ERR! gyp info spawn args ]

npm ERR! /bin/sh: pkg-config: command not found

npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp

npm ERR! gyp ERR! configure error 

npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1

npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/cc/test/node_modules/node-gyp/lib/configure.js:345:16)

npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)

npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

npm ERR! gyp ERR! System Darwin 19.6.0

npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/cc/test/node_modules/.bin/node-gyp" "rebuild"

npm ERR! gyp ERR! cwd 
/Users/cc/test/node_modules/canvas
npm ERR! gyp ERR! node -v v12.18.4

npm ERR! gyp ERR! node-gyp -v v3.8.0

npm ERR! gyp ERR! not ok

### 环境信息
```
👽 Taro v3.1.4


  Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.0.3

```

---
### 补充信息
`
    "@tarojs/cli": "^3.1.4",
    "@tarojs/components": "3.1.4",
    "@tarojs/react": "3.1.4",
    "@tarojs/runtime": "3.1.4",
    "@tarojs/taro": "3.1.4",
    "@tarojs/mini-runner": "3.1.4",
    "@tarojs/webpack-runner": "3.1.4",
`

**Comment by Chen-jj** [comment]
不是 Taro 的问题，可以升级 node 再试试

**Comment by Chen-jj** [comment]
和 #8981 好像一样的问题
