### ISSUE TITLE
支持使用 npm 官方源

### ISSUE THREAD

**Issue by harry-xiaomi** [NervJS/taro#9023]
### 这个特性解决了什么问题？
目前 taro init 创建的项目指定了使用 cnpm/npm.taobao.org 的镜像，由于网络问题需要切换到官方源（或全局 npmrc 配置的源）。 https://github.com/NervJS/taro/blob/89b3b6035903924fdf9226ee888f8d5beb7d71e6/packages/taro-cli/templates/default/npmrc
https://github.com/NervJS/taro/blob/v3.2.0/packages/taro-cli/templates/default/_npmrc

### 这个 API 长什么样？
taro init 能通过命令行参数关闭 npmrc 的覆盖，或支持取消自动运行 npm install，由用户修改 .npmrc 后自行执行。

**Comment by Chen-jj** [comment]
可以直接中断安装。

加功能的话可以在 `init` 的时候：ask -> 用户选择 npm、淘宝、cnpm 源 -> 根据 ask 的结果渲染 npmrc。这块我们可能没时间做了，欢迎 PR 哈～

**Comment by harry-xiaomi** [comment]
Fixed in 9b411866534e9a9ce6463deb37cf16730597f6de by removing npmrc from template.
