### ISSUE TITLE
taro v3.1.5 生成的package.json文件不是合法的json

### ISSUE THREAD

**Issue by grpubr** [NervJS/taro#9026]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/asdf/tddfad](https://github.com/asdf/tddfad)
**小程序基础库: 1.1.1**
**使用框架: React**

### 复现步骤

taro init taroui
创建工程后依次选择
👽 Taro v3.1.5

Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目介绍！ ui
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板源 Github（最新）-- 选github
√ 拉取远程模板仓库成功！
? 请选择模板 taro-ui（使用 taro-ui 的模板）

### 期望结果
生成一个合法的 package.json 

### 实际结果
package.json文件不合法。

"typescript": "^4.1.0",后面多了一个逗号

### 环境信息
```


 Taro v3.1.5


  Taro CLI 3.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - D:\data\node\node_global\yarn.CMD
      npm: 6.14.11 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
怎么会有这么弱智的bug，你们生成json不是用对象转过来，而是直接去print的么？

**Comment by grpubr** [comment]
[package.json.txt](https://github.com/NervJS/taro/files/6249417/package.json.txt)

**Comment by SyMind** [comment]
233 看起来单元测试覆盖程度依然不够。

**Comment by SyMind** [comment]
@Chen-jj 以下代码行需要变更，建议添加一些单元测试，最起码判断是否为合法的 json 文本。

https://github.com/SyMind/taro-project-templates/blob/v3.1/taro-ui/package.json.tmpl#L70

**Comment by Chen-jj** [comment]
感谢指出，已修复

**Comment by wsx123456** [comment]
> 感谢指出，已修复



> 感谢指出，已修复

想问下你们计划的 单元测试案例有了吗

**Comment by SyMind** [comment]
@wsx123456 我看提交还没有添加 https://github.com/NervJS/taro-project-templates/commits/v3.1，你有兴趣 pr 么？
