### ISSUE TITLE
更新到taro3.1.4后npm run build:dev:h5部署上线报错

### ISSUE THREAD

**Issue by qwerlp** [NervJS/taro#9035]
### 相关平台
H5

**浏览器版本: chrome x86_64**
**使用框架: React**

### 复现步骤
从taro3.0.11更新到taro3.1.4后npm run build:dev:h5

### 期望结果
可以正常打开页面

### 实际结果
打开页面后报错Uncaught ReferenceError: $RefreshSig$ is not defined

### 环境信息
```
 Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.12.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.8.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.1.4 => 3.1.4
      @tarojs/components: 3.1.4 => 3.1.4
      @tarojs/mini-runner: 3.1.4 => 3.1.4
      @tarojs/react: 3.1.4 => 3.1.4
      @tarojs/runtime: 3.1.4 => 3.1.4
      @tarojs/taro: 3.1.4 => 3.1.4
      @tarojs/webpack-runner: 3.1.4 => 3.1.4
      babel-preset-taro: 3.1.4 => 3.1.4
      eslint-config-taro: 3.1.4 => 3.1.4
      react: ^16.14.0 => 16.14.0
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3
```

---
### 补充信息
只会出现在npm run build:dev:h5下，其它本地run dev和build:prod都是不会的

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/113652946-64478880-96c7-11eb-9208-abf12db634c6.png)

如果 `devServer.hot === false`，babel.config.js 里也设置一下 `hot` 为 false

**Comment by qwerlp** [comment]
> ![image](https://user-images.githubusercontent.com/11807297/113652946-64478880-96c7-11eb-9208-abf12db634c6.png)
> 
> 如果 `devServer.hot === false`，babel.config.js 里也设置一下 `hot` 为 false

可以了，为什么这个插件会导致打包之后就找不到了呢

**Comment by Chen-jj** [comment]
因为在 dev 环境，默认加了 `fast-refresh` 的 babel plugin、`devServer.hot` 默认为 `true`，会加入 `fast refresh` 的 loader。

`fast refresh` 的 babel plugin 和 loader 必须同时存在。

目测你的 `devServer.hot` 设置了 `false`，导致只有 `fast refresh` 的 babel plugin 而没有 loader，导致报错
