### ISSUE TITLE
多个组件间样式相互影响

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro#904]
**问题描述**

页面中写了很多组件，不同组件多image 标签有不同的样式。在测试中发现A组件使用了A组件的样式和B组件的样式

**复现步骤**

![image](https://user-images.githubusercontent.com/16408873/47278487-03618e00-d5fc-11e8-8ec0-056f9d21d1fa.png)

组件中也并没有配置：addGlobalClass:true

怎么配置才能让不同组件样式独立呢？

**系统信息**

 - 操作系统: [Windows 10]
 - Taro 版本 [1.1.0-beta.10]
 - 报错平台 [weapp]

**Comment by kdong007** [comment]
别提俩一样的ticket.

**Comment by jiangzeyin** [comment]
> 别提俩一样的ticket.

下午GitHub 出异常
