### ISSUE TITLE
希望可以针对 Vue / Vue 3 完善一下组件事件监听的文档

### ISSUE THREAD

**Issue by ItsRyanWu** [NervJS/taro#9041]
### 这个特性解决了什么问题？
避免因为文档覆盖不全导致花费时间踩坑，影响效率。

### 这个 API 长什么样？
举个例子：
如果想要监听 button 组件上的 getPhoneNumber 事件
根据文档 button props table
![image](https://user-images.githubusercontent.com/17338101/113740855-ac03f980-9733-11eb-8366-8d9905389096.png)
猜测对于 Vue 可能是这样写的
`<button :onGetPhoneNumber="callback"/>`
不对，那试一试这样
`<button @getPhoneNumber="callback"/>`
还是不对，乱 debug 一通自己的毛病再试试
`<button @get-phone-number="callback"/>`
还是不对...
最后在怀疑人生的心态中终于试出了唯一有效写法——事件名必须全小写：
`<button @getphonenumber="callback"/>`
终于对了...

**Comment by luckyadam** [comment]
确实会引起困惑，我们完善一下

**Comment by thedb** [comment]
@ItsRyanWu 
非常感谢，我除了全小写没试，别的都试了，最后还好看到你的了~

**Comment by jiekekeji** [comment]
然而这个<button @getphonenumber="callback"/> 编译成京东还是不行

**Comment by Chen-jj** [comment]
已补全文档：https://docs.taro.zone/docs/vue-overall#%E4%BA%8B%E4%BB%B6
