### ISSUE TITLE
dev:rn 报错 不存在编译平台 rn

### ISSUE THREAD

**Issue by xytaizi1230** [NervJS/taro#9046]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
taro init myApp
cd .\myApp\  
yarn dev:rn
UnhandledPromiseRejectionWarning: Error: 不存在编译平台 rn

### 期望结果
打开模拟机，显示正常页面

### 实际结果
yarn run v1.22.5
$ npm run build:rn -- --watch

> testApp@1.0.0 build:rn D:\Project\taro\testApp
> taro build --type rn "--watch"

👽 Taro v3.1.5

(node:19052) UnhandledPromiseRejectionWarning: Error: 不存在编译平台 rn

### 环境信息
```
👽 Taro v3.1.5


  Taro CLI 3.1.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
taro 到底能不能运行app？
我一开始使用cli3.2.0版本，可以执行dev:rn 命令，但是无法打开模拟机，直接使用rn，用相同的版本，是可以正常启动模拟机的
dev:rn 后访问浏览器http://localhost:8081/index.bundle，会提示
Unable to resolve module AccessibilityInfo

**Comment by Chen-jj** [comment]
3.2 才开始支持 RN 的

**Comment by zhiqingchen** [comment]
```
我一开始使用cli3.2.0版本，可以执行dev:rn 命令，但是无法打开模拟机，直接使用rn，用相同的版本，是可以正常启动模拟机的
dev:rn 后访问浏览器http://localhost:8081/index.bundle，会提示
Unable to resolve module AccessibilityInfo
```

3.2.0可以用，`Unable to resolve module AccessibilityInfo` 是因为没有带平台参数 platform=ios
