### ISSUE TITLE
小程序canvas使用setStrokeStyle，传pattern进去会报错

### ISSUE THREAD

**Issue by BryantZhou** [NervJS/taro#905]
**问题描述**
使用canvas的setStrokeStyle，传pattern进去会报错，同样的pattern传进去setFillStyle可以使用

**复现步骤**

```js
import img from 'xxx.jpg';

const ctx = Taro.createCanvasContext('canvas', this.$scope);
const pattern = ctx.createPattern(img, 'no-repeat');
ctx.setLineWidth(8);
ctx.setLineCap('round');
ctx.beginPath();
ctx.setStrokeStyle(pattern);
ctx.strokeRect(10, 10, 150, 75);
ctx.draw()
```

**期望行为**
setStrokeStyle可以传入pattern使用

**报错信息**

![image](https://user-images.githubusercontent.com/12403684/47280095-4e34d300-d607-11e8-8667-33d90c07bb7b.png)

**系统信息**

 - 操作系统: [mac os]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v8.11.1]
 - 报错平台 [weapp]

**Comment by luckyadam** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/canvas/CanvasContext.setStrokeStyle.html

貌似只能传颜色值

**Comment by BryantZhou** [comment]
setFillStyle从文档看也是只能传颜色值，但是我实际测的时候，传pattern进去也是没问题的，然后setStrokeStyle、setFillStyle传渐变色也是可以的
https://developers.weixin.qq.com/miniprogram/dev/api/canvas/CanvasContext.setFillStyle.html

**Comment by luckyadam** [comment]
@BryantZhou 请问是使用原生小程序书写支持，使用 Taro 之后不支持么

**Comment by BryantZhou** [comment]
好吧...原生小程序也直接报错了，估计是小程序的bug了

**Comment by luckyadam** [comment]
应该是的~
