### ISSUE TITLE
有计划对Vant Weapp组件依赖进行分析吗

### ISSUE THREAD

**Issue by tianxing0923** [NervJS/taro#9055]
### 这个特性解决了什么问题？
目前Vant Weapp很多组件都拆分了wxs文件，需要配置copy的文件太多了，每次用到组件的时候都需要去看源码有没有引用wxs然后再配置copy，比较繁琐

### 这个 API 长什么样？
期望自动解析文件依赖

**Comment by Chen-jj** [comment]
目前还没有人力支持的。

对 wxml 的分析工作在此 [webpack loader](https://github.com/NervJS/taro/blob/next/packages/taro-mini-runner/src/loaders/miniTemplateLoader.ts) 中，有兴趣可以贡献一下 PR 哈～
