### ISSUE TITLE
Future：编译过程中能否提供编译进度的标准输出

### ISSUE THREAD

**Issue by YikaJ** [NervJS/taro#906]
项目大了之后，编译过程耗时比较久。
我们在做云端编译时，希望能通过一定规则，从标准输出里获取当前编译进度，方便展示出来。

**Comment by Pines-Cheng** [comment]
现在是碰到什么问题？获取不到终端的打印？期望以怎样的方式体提供？

**Comment by luckyadam** [comment]
Duplicate of #907

**Comment by YikaJ** [comment]
github 抽风的一天，我似乎提了两个问题😂

**Comment by luckyadam** [comment]
@YikaJ 😂😂
