### ISSUE TITLE
非 Taro 项目中使用 @tarojs/components 报错

### ISSUE THREAD

**Issue by xughv** [NervJS/taro#9064]
### 相关平台
H5

**浏览器版本: Chrome 89**
**使用框架: React**

### 复现步骤
非 Taro 构建项目参照 https://github.com/NervJS/taro/issues/6883 配置可运行，但使用到 Swiper 时发生异常。

看了下好像是因为没有环境变量时全局的 `getComputedStyle` 被覆盖了，新的方法在 H5 下行为不太对：

https://github.com/NervJS/taro/blob/8c485f841a5ebed3fa1856605d4f4964a078914e/packages/taro-runtime/src/bom/window.ts#L25-L28

### 表现

没有正确获取到样式：

![image](https://user-images.githubusercontent.com/14882240/113992511-204eb200-9886-11eb-9047-03f19604f5a1.png)

---

![image](https://user-images.githubusercontent.com/14882240/113992440-1036d280-9886-11eb-8ce3-a4fb047dbab2.png)

### 期望结果
无环境变量时不覆盖全局方法

### 实际结果
全局方法被覆盖

### 环境信息
```
  Taro CLI 3.0.21 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.9.2 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.0.21 => 3.0.21
      @tarojs/components: ^3.0.21 => 3.0.21
      @tarojs/mini-runner: ^3.0.21 => 3.0.21
      @tarojs/react: ^3.0.21 => 3.0.21
      @tarojs/runtime: ^3.0.21 => 3.0.21
      @tarojs/webpack-runner: ^3.0.21 => 3.0.21
      babel-preset-taro: ^3.0.21 => 3.0.21
      eslint-config-taro: ^3.0.21 => 3.0.21
      postcss-pxtransform: ^3.2.1 => 3.2.1
      react: ^17.0.2 => 17.0.2
```

**Comment by Chen-jj** [comment]
设置一下环境变量咯

**Comment by xughv** [comment]
> 设置一下环境变量咯

自定义构建设置了环境变量会报另一个问题 .. runtime 里面找不到 React，还不清楚原因 ..

![image](https://user-images.githubusercontent.com/14882240/113993987-930c5d00-9887-11eb-88bf-c9b0492652bc.png)

**Comment by xughv** [comment]
覆盖这里判断下？

```js
if (process.env.TARO_ENV && process.env.TARO_ENV !== 'h5') { }
```
