### ISSUE TITLE
[Feature Request]能否从标准输出里捕获到编译过程的进度

### ISSUE THREAD

**Issue by YikaJ** [NervJS/taro#907]
项目大了之后，编译过程耗时比较久。
我们在做云端编译时，希望能通过一定规则，从标准输出里获取当前编译进度，方便展示出来。

**Comment by YikaJ** [comment]
是的，需要类似这个功能ᕕ(ᐛ)ᕗ

**Comment by luckyadam** [comment]
嗯嗯~ 可以尝试一下~

**Comment by maliaoMJ** [comment]
最好是带五彩斑斓黑 的进度条颜色

**Comment by Chen-jj** [comment]
Taro 2、3 能直接使用 webpack 的类似插件解决了
