### ISSUE TITLE
LivePusher组件需要bindaudiovolumenotify支持

### ISSUE THREAD

**Issue by xiaoice** [NervJS/taro#9070]
### 这个特性解决了什么问题？
bindaudiovolumenotify	eventhandle		否	返回麦克风采集的音量大小	2.12.0

### 这个 API 长什么样？
支持bindaudiovolumenotify

**Comment by xiaoice** [comment]
用Taro插件已解决
plugins: [
      ['@tarojs/plugin-inject', {
        LivePusher: {
          bindaudiovolumenotify: 'onAudioVolumeNotify'
        }
      }],
    ],

**Comment by xiaoice** [comment]
['@tarojs/plugin-inject', {
      LivePusher: {
        'bindaudiovolumenotify': 'onAudioVolumeNotify',
        'confirm-type': 'confirmType',
      }
    }],

添加了这个不生效

**Comment by xiaoice** [comment]
['@tarojs/plugin-inject', {
LivePusher: {
'bindaudiovolumenotify': 'onAudioVolumeNotify',
'confirm-type': 'confirmType',
}
}],

添加 bindaudiovolumenotify 生效
添加 confirm-type 不生效，帮忙查下原因

**Comment by Chen-jj** [comment]
@xiaoice Taro v3.1.0 开始已经支持了 `bindaudiovolumenotify`。

另外 `confirm-type` 这个属性没有在微信的文档看到？
