### ISSUE TITLE
Input：Taro onInput返回字符串无效

### ISSUE THREAD

**Issue by likuann** [NervJS/taro#9074]
### 相关平台
字节跳动小程序

### 复现仓库
[git@code.byted.org:temai/MerchantTaroTemplate.git](git@code.byted.org:temai/MerchantTaroTemplate.git)
**小程序基础库: 1.93.1.9**
**使用框架: React**

### 复现步骤
输入框输入内容

### 期望结果
展示onInput返回字符串

### 实际结果
展示Input输入字符串

### 环境信息
```
Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.9.0
      Yarn: 1.22.10 
      npm: 7.5.2 
    npmPackages:
      @tarojs/cli: 3.1.4 => 3.1.4 
      @tarojs/components: 3.1.4 => 3.1.4 
      @tarojs/mini-runner: 3.1.4 => 3.1.4 
      @tarojs/react: 3.1.4 => 3.1.4 
      @tarojs/runtime: 3.1.4 => 3.1.4 
      @tarojs/taro: 3.1.4 => 3.1.4 
      @tarojs/webpack-runner: ^3.1.4 => 3.2.0 
      babel-preset-taro: 3.1.4 => 3.1.4 
      eslint-config-taro: 3.1.4 => 3.1.4 
      react: ^17.0.1 => 17.0.2 
```

**Comment by slqcode** [comment]
遇到了同样的问题，请问现在有任何进展吗？

**Comment by likuann** [comment]
无，曲线救火了。





------------------ 原始邮件 ------------------
发件人: slqcode ***@***.***&gt;
发送时间: 2021年5月12日 15:57
收件人: NervJS/taro ***@***.***&gt;
抄送: likuann ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[NervJS/taro] Input：Taro onInput返回字符串无效 (#9074)





 
遇到了同样的问题，请问现在有任何进展吗？

**Comment by qiyulaoshi** [comment]
这个问题被关闭了，请问如何才能获取这次关闭得更新呢

**Comment by moon1995** [comment]
也遇到了这个问题，有解决嘛
