### ISSUE TITLE
编译成h5，导航页进入次级页面后刷新当前页，再返回到导航页切换导航显示有问题

### ISSUE THREAD

**Issue by swey01** [NervJS/taro#9076]
相关平台
H5

小程序基础库: 2.3.2
使用框架: React

复现步骤
安卓/IOS手机，随便点击进入哪个页面，然后刷新当前页再通过返回按钮后退回进入前的导航页面，这时候切换底部导航，发现页面无法销毁，切换后的新导航页会出现在问题页面的下方

期望结果
正常切换导航

实际结果
次级页面后刷新当前页，再返回到导航页切换导航显示有问题

环境信息
👽 Taro v2.2.6

**Comment by wulala** [comment]
同问。解决了没？

**Comment by Chen-jj** [comment]
请按规范创建 Issue，提供一切必要信息
