### ISSUE TITLE
H5端enablePullDownRefresh导致其他页面ScrollView无法往上滚动

### ISSUE THREAD

**Issue by wz113917** [NervJS/taro#9077]
### 相关平台
H5

**浏览器版本: Chrome 89.0.4389.114**
**使用框架: React**

### 复现步骤
1. 存在多个路由页面（如： /index， /learning），index页面包含ScrollView，learning页面配置了enablePullDownRefresh: true。
2. index页面滚动了一段距离，从index进入learning页面，然后返回index页面，发现ScrollView无法往上滚动；
3. 断点调试发现，返回index页面手指按住往上滚动时，会触发taro-pull-to-refresh.entry.js文件中onTouchMove事件，并执行setContentStyle方法。
```
this.setContentStyle = (ty) => {
  // todos: Why sometimes do not have `this.contentRef` ?
  if (this.contentRef) {
	// translate3d 不清理 会影响内部元素 定位
	if (ty) {
	  setTransform(this.contentRef.style, `translate3d(0px,${ty}px,0)`);
	}
	else {
	  setTransform(this.contentRef.style, '');
	}
  }
};
```
猜测由于访问过learning页面，this.contentRef中一直指向.rmc-pull-to-refresh-content元素，导致ScrollView响应TouchMove事件有问题。

### 期望结果
配置了enablePullDownRefresh的页面与其他ScrollView页面能同时正常工作

### 实际结果
有页面配置enablePullDownRefresh，其他页面中ScrollView无法上滚。

### 环境信息
```
👽 Taro v3.1.4


  Taro CLI 3.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.1 - D:\Program Files\nodejs\node.EXE
      npm: 6.14.8 - D:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@wz113917  没有复现，升级到最新版再试试，还有问题可以提供一下 demo
