### ISSUE TITLE
如何追加Sass的支持？

### ISSUE THREAD

**Issue by mikcho** [NervJS/taro#9080]
### 这个特性解决了什么问题？
例如：在通过`taro init`创建项目的时候没有选择Sass，后来引入Taro UI又需要使用Sass。

需要安装什么依赖和怎样进行配置？

### 这个 API 长什么样？
无

**Comment by luckyadam** [comment]
直接用

**Comment by mikcho** [comment]
> 直接用

在JS中导入SCSS可以，

但把`app.css`改为`app.scss`不可以

**Comment by iamxiyang** [comment]
> 在JS中导入SCSS可以，
> 但把`app.css`改为`app.scss`不可以

 你` app.ts `中默认引入的`app.css`同步修改了嘛

**Comment by mikcho** [comment]
@iamxiyang

> 你`app.ts`中默认引入的`app.css`同步修改了嘛

大意了，改过来就可以了

看来不管在安装向导有没有选择Sass，构建工具都会支持Sass，只是生成的模板会不一样
