### ISSUE TITLE
npx taro build 如何配置压缩打包生成sourcemap文件？

### ISSUE THREAD

**Issue by Thinking80s** [NervJS/taro#9082]
### 这个特性解决了什么问题？
压缩打包生成sourcemap文件

### 这个 API 长什么样？
压缩打包生成sourcemap文件

**Comment by Thinking80s** [comment]
https://github.com/NervJS/taro/issues/2470

**Comment by Thinking80s** [comment]
https://github.com/NervJS/taro/issues/5361

**Comment by Chen-jj** [comment]
非 Bug Report 或 Feature Request 请到[论坛](https://github.com/NervJS/taro/discussions)提问
