### ISSUE TITLE
Typesctipt: 枚举类型声明异常

### ISSUE THREAD

**Issue by Jiexiansen** [NervJS/taro#9089]
### 相关平台
H5

### 复现仓库
[https://github.com/Jiexiansen/taro-test.git](https://github.com/Jiexiansen/taro-test.git)
**浏览器版本: Chrome Version 89.0.4389.114 **
**使用框架: React**

### 复现步骤
1. 定义枚举值CONTENT_TYPE；
2. 使用枚举值CONTENT_TYPE；
3. eslint提示CONTENT_TYPE声明异常。

### 期望结果
无错误信息

### 实际结果
'CONTENT_TYPE' is already declared in the upper scope.

### 环境信息
```
👽 Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.2 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    npmGlobalPackages:
      typescript: 4.1.2
```

---
### 补充信息
复现代码在 src/app.ts 4-10行

**Comment by digiaries** [comment]
代码拉下来并没有出现描述的错误啊

**Comment by Jiexiansen** [comment]
![image](https://user-images.githubusercontent.com/26481272/114800530-7793db80-9dcc-11eb-85af-34efc09fd22e.png)

**Comment by Chen-jj** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/2471
