### ISSUE TITLE
创建的新项目，run dev:h5 报错

### ISSUE THREAD

**Issue by jcbbhe** [NervJS/taro#9091]
### 相关平台
微信小程序

**小程序基础库: 1**
**使用框架: React**

### 复现步骤
@tarojs/cli@3.2.1   创建新项目    npm run dev:h5

### 期望结果
正常运行

### 实际结果
监听文件修改中...

�   Failed to compile.

./node_modules/@tarojs/components/dist/taro-components/taro-components.css)
Module build failed (from ./node_modules/@tarojs/webpack-runner/node_modules/css-loader/dist/cjs.js):
Error: Cannot find module './container'
Require stack:
- E:\WorkSpace\taro\taro-app\node_modules\postcss-selector-parser\dist\selectors\root.js
- E:\WorkSpace\taro\taro-app\node_modules\postcss-selector-parser\dist\parser.js
- E:\WorkSpace\taro\taro-app\node_modules\postcss-selector-parser\dist\processor.js
- E:\WorkSpace\taro\taro-app\node_modules\postcss-selector-parser\dist\index.js
- E:\WorkSpace\taro\taro-app\node_modules\postcss-modules-local-by-default\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\css-loader\dist\utils.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\css-loader\dist\plugins\postcss-import-parser.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\css-loader\dist\plugins\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\css-loader\dist\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\css-loader\dist\cjs.js
- E:\WorkSpace\taro\taro-app\node_modules\loader-runner\lib\loadLoader.js
- E:\WorkSpace\taro\taro-app\node_modules\loader-runner\lib\LoaderRunner.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\webpack\lib\NormalModule.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\webpack\lib\NormalModuleFactory.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\webpack\lib\Compiler.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\node_modules\webpack\lib\webpack.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\dist\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\webpack-runner\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\service\node_modules\@tarojs\helper\dist\npm.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\service\node_modules\@tarojs\helper\dist\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\service\node_modules\@tarojs\helper\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\service\dist\Kernel.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\service\dist\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\service\index.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\cli\dist\cli.js
- E:\WorkSpace\taro\taro-app\node_modules\@tarojs\cli\bin\taro

### 环境信息
```
👽 Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by luckyadam** [comment]
用的什么模板
