### ISSUE TITLE
希望添加类似usePreload的hooks

### ISSUE THREAD

**Issue by wenlisu** [NervJS/taro#9093]
### 这个特性解决了什么问题？
预加载功能

### 这个 API 长什么样？
usePreload(() => {
 do something...
})

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/optimized#%E8%B7%B3%E8%BD%AC%E9%A2%84%E5%8A%A0%E8%BD%BD)
