### ISSUE TITLE
什么时候支持wx.onCopyUrl这个接口

### ISSUE THREAD

**Issue by liguansong** [NervJS/taro#9095]
### 这个特性解决了什么问题？
能正常使用onCopyUrl和wx.offCopyUrl这两个接口

### 这个 API 长什么样？
参考https://developers.weixin.qq.com/miniprogram/dev/api/share/wx.onCopyUrl.html

**Comment by iamxiyang** [comment]
在官方暂未支持的情况下，暂时可以使用Taro提供的 `@tarojs/plugin-inject`  插件实现， 参考地址：https://github.com/NervJS/taro-plugin-inject

如果不想那么麻烦，也可以直接通过 **wx. 前缀** 按照微信的代码进行调用，是能够正常使用的。

**Comment by Pengjialu-lulujie** [comment]
可以咨询一下怎么使用wx.onCopyUrl吗？
