### ISSUE TITLE
页面跳转后，执行当前页面的 actions后，上一个页面的 componentWillReceiveProps 依然会被执行？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#910]
页面跳转后，执行当前页面的 actions后，上一个页面的 componentWillReceiveProps 依然会被执行？
Taro ,这样处理 对性能 ，是有影响的吧！
我的跳转使用的 是      Taro.navigateTo()

**Comment by luckyadam** [comment]
在小程序中页面跳转之后上一个页面依然存在内存中，而 redux 是全局的，有修改状态触发更新也会导致上一个页面更新，这在实现某些功能的时候是有必要的，你可以通过在页面中判断当前页面是否展示，来规避这一现象
