### ISSUE TITLE
去掉组件多余属性

### ISSUE THREAD

**Issue by jpdan** [NervJS/taro#9102]
### 这个特性解决了什么问题？
taro@3.2.1
微信开发者工具中评分，使用了作废属性，比如Input auto-focus，看文档是加上了所有属性的，请问如何去掉？

### 这个 API 长什么样？
可手动控制去掉不需要的属性

**Comment by Chen-jj** [comment]
@jpdan 使用此插件可以自定义模板属性 https://github.com/NervJS/taro-plugin-inject
