### ISSUE TITLE
leancloud 增强插件无法编译

### ISSUE THREAD

**Issue by kdong007** [NervJS/taro#911]
**问题描述**
`leancloud-realtime-plugin-typed-messages` 这是一个leancloud功能插件 import之后无法编译

**复现步骤**

[或者可以直接贴源代码，能贴文字就不要截图]

```js
import {
    Realtime,
    TypedMessage,
    messageType, messageField,
} from "leancloud-realtime/dist/realtime.weapp";
import {
    TypedMessagesPlugin,
    ImageMessage,
    LocationMessage,
    VideoMessage,
} from "leancloud-realtime-plugin-typed-messages";

```

**报错信息**
无法编译 

**系统信息**

Taro 1.0.7

**补充信息**
leancloud主包是通过 `leancloud-realtime/dist/realtime.weapp`加载的  而`leancloud-realtime-plugin-typed-messages`的依赖是如下设置的
```json
"peerDependencies": {
    "leancloud-storage": "^2.0.0 || ^3.0.0",
    "leancloud-realtime": "^4.0.0-alpha.3"
  }
```
https://github.com/leancloud/js-realtime-sdk/blob/master/plugins/typed-messages/package.json

是不是因为这个依赖导致编译时去尝试装普通版的leancloud导致编译问题？

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/47332162-08cce000-d6b1-11e8-8f1b-fd24f882a845.png)

leancloud-realtime-plugin-typed-messages
这个包不能直接在小程序中安装使用，因为还依赖了 `leancloud-storage` 和 `leancloud-realtime` 
可以把这个包下下来，改一下这里的包引用文件
