### ISSUE TITLE
建议pxTransform支持自定义目标屏幕宽度及字体配置

### ISSUE THREAD

**Issue by WhiteYin** [NervJS/taro#9123]
#### 前提
现有H5项目，使用750px屏幕宽度 HTML元素字体大小200px的rem样式适配方案。  
举例：  
750px设计稿，100px宽度的元素样式为：`width：0.5rem; /* 100 / 200 */`  

#### 问题
转用Taro后，由于框架默认使用640px屏幕宽度 HTML元素字体大小40px的方案。结果如下：
```
// 配置
{
  designWidth: 750,
}
// taro
width: 100px;
// 微信小程序
width: 100rpx;
// h5
width: 2.13333rem; => HTML元素字体大小100px，实际计算值为213px
```

导致所有样式必须重新计算。
  
##### 方案一
样式文件仍保留rem，修改/src/index.html里的计算逻辑。  
这样导致微信小程序不会自动转换单位，样式出现异常 

##### 方案二
手动重写所有原样式。工作量巨大。  

### 这个 API 长什么样？
1. 增加配置项
```
/** rem方案里设置的屏幕宽度基准 */
remDeviceWidth: number
/** H5项目在设备宽度为remDeviceWidth时HTML的字体大小 */
remFontSize: number
```
2. 修改API
```
const pxTransform = function (size, designWidth = 640,deviceWidth = 640, fontSize = 40) {
  if (designWidth == null) {
    throw new Error('pxTransform 函数在 H5 中运行需要把配置中的 `designWidth` 作为第二个参数传入')
  }
  return Math.ceil((((parseInt(size, 10) / fontSize) * deviceWidth) / designWidth) * 10000) / 10000   'rem'
}
```
还有postcss-pxtransform里的代码改动，逻辑差不多。

**Comment by gjc9620** [comment]
designWidth = 640,deviceWidth = 640, fontSize = 40
这三个参数应该在taro内部运行时赋值，而且不是开发者传入
