### ISSUE TITLE
Text或者View标签为什么不支持自定义属性呢

### ISSUE THREAD

**Issue by wenyuanzhuo** [NervJS/taro#9127]
### 这个特性解决了什么问题？
用于样式选择器获取自定义属性值

### 这个 API 长什么样？
<Text data-xx=""></Text>

**Comment by Chen-jj** [comment]
xml 模板是编译时写死的，只支持内置属性，暂不支持自定义属性

**Comment by yancaidev** [comment]
可以把自定义属性放在 className 样式列表中，通过属性选择器选择判断 class 属性是否包含自定义属性，来设置不同的样式。
