### ISSUE TITLE
导入第三方组件Cax失败

### ISSUE THREAD

**Issue by tang3** [NervJS/taro#9128]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/tang3/taro2caxbug](https://github.com/tang3/taro2caxbug)
**小程序基础库: 2.16.0**
**使用框架: React**

### 复现步骤
1. taro初始化项目
2. src目录下建立components目录，将https://github.com/dntzhang/cax/tree/master/packages/cax-weapp/cax中内容拷贝到此目录
3. src/pages/index/index.config.json填写
```export default {
  navigationBarTitleText: '首页',
  usingComponents:{
    'cax': '../../components/cax/cax'
  }
}```
4. src/pages/index/index.js中添加引用import cax from '../../components/cax/index'

### 期望结果
导入成功，可以正常显示初始化页面

### 实际结果
初始化页面不显示，并且终端报如下错误：
```
TypeError: document.createElement(...).getContext is not a function
```

### 环境信息
```
👽 Taro v3.2.1

  Taro CLI 3.2.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.1 => 3.2.1
      @tarojs/components: 3.2.1 => 3.2.1
      @tarojs/mini-runner: 3.2.1 => 3.2.1
      @tarojs/react: 3.2.1 => 3.2.1
      @tarojs/runtime: 3.2.1 => 3.2.1
      @tarojs/taro: 3.2.1 => 3.2.1
      @tarojs/webpack-runner: 3.2.1 => 3.2.1
      babel-preset-taro: 3.2.1 => 3.2.1
      eslint-config-taro: 3.2.1 => 3.2.1
      react: ^17.0.0 => 17.0.2
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10
```

<!-- generated by taro-issues. 请勿修改或删除此行注释 --><!--labels=T-weapp,V-3,F-react-->

**Comment by Chen-jj** [comment]
@tang3 这个包使用了 H5 的 Canvas API，小程序是另一套 API，并不能兼容。

![image](https://user-images.githubusercontent.com/11807297/115987362-4fd01f00-a5e7-11eb-9b3a-a5424a8da1b0.png)
