### ISSUE TITLE
Taro.chooseImage 的参数 count， 在 部分手机 App 的 webview 中无效

### ISSUE THREAD

**Issue by Celeste72** [NervJS/taro#9129]
### 相关平台
H5

**浏览器版本: Chrome****小程序基础库: 2.13.1**
**使用框架: React**

### 复现步骤
 Taro.chooseImage({
            sizeType: ['original'],
            sourceType: ['album'],
            count: limit,
......

### 期望结果
在App的webview打开H5，count值能够限制选择图片数量

### 实际结果
比如在钉钉（或者其他App）的webview打开我们的H5，用chooseImage选图片时，安卓系统limit为任意数都能多选上限数，IOS系统limit为任意数都只能单选图片，Taro是当count为1时，input[type=file] mutiple设置为false，在浏览器都是OK的，App的webview不行，求解决

### 环境信息
```
 Taro v3.0.29


  Taro CLI 3.0.29 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.11.0 - D:\myApplications\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - D:\myApplications\nodejs\npm.CMD

```

**Comment by jyx12138** [comment]
求问，解决了么？

**Comment by ZakaryCode** [comment]
此处是对应浏览器内核的问题，在 Taro 侧不会做专门的优化
