### ISSUE TITLE
始终都会阻止冒泡

### ISSUE THREAD

**Issue by mushan0x0** [NervJS/taro#913]
------------------------

**问题描述**
始终都会阻止冒泡

**复现步骤**
```js
const a = false
if (a) {
   e.stopPropagation() // 始终会阻止冒泡
}
```

**期望行为**
支持判断再阻止冒泡

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [v.1.1.0-beta.8]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [weapp]

**Comment by AwesomeDevin** [comment]
**问题描述**
## e.stopPropagation()  写在条件语句中，未执行， 仍然会阻止事件冒泡 ,导致页面无法滚动

**复现步骤**
[复现问题的步骤]
1. 监听容器的ontouchmove事件
2. 添加条件语句并e.stopPropagation() 
3. 条件语句未执行，仍然会阻止事件冒泡，导致页面无法滚动

```js
  move(e){
    let val = (e.changedTouches[0].clientY-100) 
    if(val>1){
      console.log('stop')
      e.stopPropagation()
    }
    else{
      console.log(123)
    }
  }

```

**期望行为**
支持判断再阻止冒泡

**报错信息**
 控制台仅仅输出了"123",并没有"stop",仍然阻止事件冒泡

**系统信息**

 - 操作系统:windows7
 - Taro 版本 1.2.4
 - Node.js 版本 8.9.3
 - 报错平台 [weapp

**Comment by scutHuqiang** [comment]
发现了同样的问题，求解

**Comment by x1nes** [comment]
这个问题解决了吗？有没有暂时的应对办法？

**Comment by yuche** [comment]
动态组织冒泡在 Taro 中是不可行的，解决方案请看：

https://github.com/NervJS/taro/issues/761#issuecomment-504338329

**Comment by icewind7030** [comment]
@yuche  这个解决方案并不是动态阻止冒泡啊？这个需求没办法实现吗？

**Comment by alesjia** [comment]
这个问题感觉没有解决，只要代码中有stopPropagation,那么事件就都被阻止了

**Comment by Zephyrrro** [comment]
遇到了同样的问题，目前还是没有解决方案么。。。

**Comment by alesjia** [comment]
没有啊←_←发自我的华为手机-------- 原始邮件 --------发件人： Hibiscus_L <notifications@github.com>日期： 2020年4月26日周日 晚上8:11收件人： NervJS/taro <taro@noreply.github.com>抄送： easy liu <alesjia@163.com>, Comment <comment@noreply.github.com>主    题： Re: [NervJS/taro] 始终都会阻止冒泡 (#913)

遇到了同样的问题，目前还是没有解决方案么。。。
