### ISSUE TITLE
canvas 的 API draw(false,callback) 的异常 和 canvasToTempFilePath 异常？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#915]
我想实现在 在swiper中浏览  绘制的好的canvas ,由于小程序中  canvas 的层级最高 因素，考虑把 canvas draw 完成后的转换成 图片 放在 swiper 中浏览，但是 ，在 ctx.draw(false,callback),遇到了 问题：
1，在开发工具中 不触发 callback 回调，只有在真机测试时，才会 触发回调；
2，真机测试 ，ctx.draw(false,callback) 完成后 可以看到 绘制结果 但是在 使用 wx.canvasToTempFilePath 想要得到 图片的http链接 时 ，报错了
如图：
![image](https://user-images.githubusercontent.com/43346131/47341922-e1880a00-d6d4-11e8-887c-465d948bcf7f.png)
```
 this.context.draw(false, (canvasResult) => {
      Taro.hideLoading();
      console.log(canvasResult, this.context.canvasId);
      wx.canvasToTempFilePath({
        canvasId: this.context.canvasId,
        success: function (res) {
          const tempFilePath = res.tempFilePath;
          console.log(tempFilePath);
          // wx.previewImage({
          //   current: tempFilePath, // 当前显示图片的http链接
          //   urls: [tempFilePath] // 需要预览的图片http链接列表
          // });
        },
        fail: function (res) {
          console.log(res);
        }
      }, this);
    });
```

**Comment by shaodushu** [comment]
https://nervjs.github.io/taro/docs/wx-relations.html

**Comment by JoMartinezZhu** [comment]
> https://nervjs.github.io/taro/docs/wx-relations.html
后面我又修改了 this , 但是还是不行！

**Comment by JoMartinezZhu** [comment]
> https://nervjs.github.io/taro/docs/wx-relations.html

我应该在 
> https://nervjs.github.io/taro/docs/wx-relations.html

好了，好了，我应该 在每一个 api  上加上 this.$scope
```
wx.previewImage({
             current: tempFilePath, // 当前显示图片的http链接
            urls: [tempFilePath] // 需要预览的图片http链接列表
          },this.$scope);
```

**Comment by luckyadam** [comment]
可以使用 `Taro.canvasToTempFilePath`  的
