### ISSUE TITLE
请教下navigateBack如何返回参数给前一页面？

### ISSUE THREAD

**Issue by Leadrive** [NervJS/taro#916]
采用navigateTo到一新页面后，在新页面中用navigateBack返回。
如何带参数返回？谢谢。

**Comment by Pines-Cheng** [comment]
wx.navigateBack 没有提供相关的参数哦。
BTW，什么样的场景需要这个？

**Comment by luckyadam** [comment]
@Leadrive 可以维护一个全局变量，或者使用 redux

**Comment by Leadrive** [comment]
看来也只能在dva上处理了，就是麻烦一些。RN中的react-native-router-flux是支持返回参数的，可以参考下。 @luckyadam
