### ISSUE TITLE
设置 View 组件 style.color 属性为 undefined 时，没有更新 style.color 为空

### ISSUE THREAD

**Issue by tgioer** [NervJS/taro#9160]
### 相关平台
H5

### 复现仓库
[https://github.com/taroify/taro322-bug-color.git](https://github.com/taroify/taro322-bug-color.git)
**浏览器版本: Chrome 90.0.4430.72**
**使用框架: React**

### 复现步骤
运行，点击 change 按钮看效果

### 期望结果
当设置 style.color 为 undefined 时，期望的 dom 效果应该是没有 color 属性。比如 style={{ color : "#ee0a24" }}时，dom 的效果是 `<View style="color:#ee0a24;">Color</View>`。当设置 style={{ color : undefined }} 时，dom 的效果是 `<View style>Color</View>`

### 实际结果
实际的 dom 效果：当设置 style={{ color : undefined }} 时，dom 的效果是 `<View style="color:#ee0a24;">Color</View>`

### 环境信息
```
👽 Taro v3.2.2


  Taro CLI 3.2.2 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 14.15.3 - D:\Programs\nodejs\node-v14.15.3-win-x64\node.EXE
      Yarn: 1.22.10 - D:\dev-ops\npm-repository\yarn.CMD
      npm: 6.14.11 - D:\Programs\nodejs\node-v14.15.3-win-x64\npm.CMD

```

**Comment by tgioer** [comment]
taro 在处理样式时，直接对 undefined 做了 return 操作，这个需不需要做 return 呢？

https://github.com/NervJS/taro/blob/next/packages/taro-runtime/src/dom/style.ts#L124

![image](https://user-images.githubusercontent.com/18252854/115809419-a8a08b80-a41e-11eb-96eb-f25759b691ec.png)

**Comment by Chen-jj** [comment]
最新版本已修复，升级后再试试
