### ISSUE TITLE
使用微信小程序插件极验无法触发onsuccess 事件

### ISSUE THREAD

**Issue by DaveChen98** [NervJS/taro#9187]
### 相关平台
微信小程序

**小程序基础库: 2.8.3**
**使用框架: React**

### 复现步骤
```
插件地址: https://mp.weixin.qq.com/wxopen/pluginbasicprofile?action=intro&appid=wxefa63d84fe9f64a2&token=&lang=zh_CN
在 app.config.ts 中配置 插件
plugins: {
    myPlugin: {
      version: "1.3.3",
      provider: "xxxx"
    }
  }

在 page.config.ts 中
export default {
  "usingComponents": {
    "captcha": "plugin://myPlugin/captcha"
  }
}

使用时

<captcha
      id="captcha"
      product="bind"
      verify={verify}
      gt={gt}
      challenge={challenge}
      offline={offline}
      ononsuccess={captchaSuccess} />
```

### 期望结果
极验图形验证功能，期望图形验证通过时，触发 captchaSuccess

### 实际结果
没有任何触发

### 环境信息
```
Taro CLI 3.2.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.23.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.1 => 3.2.1 
      @tarojs/components: 3.2.1 => 3.2.1 
      @tarojs/mini-runner: 3.2.1 => 3.2.1 
      @tarojs/react: 3.2.1 => 3.2.1 
      @tarojs/runtime: 3.2.1 => 3.2.1 
      @tarojs/taro: 3.2.1 => 3.2.1 
      @tarojs/webpack-runner: 3.2.1 => 3.2.1 
      babel-preset-taro: 3.2.1 => 3.2.1 
      eslint-config-taro: 3.2.1 => 3.2.1 
      react: 17.0.0 => 17.0.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 4.2.3
```

**Comment by DaveChen98** [comment]
@Chen-jj 帮忙看下？
captcha 插件事件是 onsuccess，所以这里写成了 ononsuccess，taro.js 里面通过 setEvent 也打印到了 onsuccess 的事件注册，奇怪的是，当极验验证后，触发成功回调时，并没有像预期一样触发 onsuccess。 这里我用的是 react 17 的 hook 组件, 和 taro 3.2.1 版本

**Comment by DaveChen98** [comment]
里面有很多公司的配置接口和安全验证，没法提供源码进行复现

**Comment by DaveChen98** [comment]
> @Chen-jj 帮忙看下？
> captcha 插件事件是 onsuccess，所以这里写成了 ononsuccess，taro.js 里面通过 setEvent 也打印到了 onsuccess 的事件注册，奇怪的是，当极验验证后，触发成功回调时，并没有像预期一样触发 onsuccess。 这里我用的是 react 17 的 hook 组件, 和 taro 3.2.1 版本

**Comment by DaveChen98** [comment]
> @Chen-jj 帮忙看下？
> captcha 插件事件是 onsuccess，所以这里写成了 ononsuccess，taro.js 里面通过 setEvent 也打印到了 onsuccess 的事件注册，奇怪的是，当极验验证后，触发成功回调时，并没有像预期一样触发 onsuccess。 这里我用的是 react 17 的 hook 组件, 和 taro 3.2.1 版本

里面有很多公司的配置接口和安全验证，没法提供源码进行复现

**Comment by Przeblysk** [comment]
```
<captcha  bindonSuccess="captchaSuccess"/>
```
这是极验的官方示例，Taro转换完后的wxml是这样的
<img width="748" alt="image" src="https://user-images.githubusercontent.com/18001272/147023397-9cb827b8-fefd-485c-99fa-860b9d1fbaaa.png">
