### ISSUE TITLE
代码里面引入Taro.showLoading 显示加载进度的代码，npm run build:rn 打包到ios平台，xcode编译显示文件冲突 

### ISSUE THREAD

**Issue by qylibohao** [NervJS/taro#9188]
### 相关平台
React Native

### 复现仓库
[https://github.com/qylibohao/taro-native-shell-Demo](https://github.com/qylibohao/taro-native-shell-Demo)

**使用框架: React**

### 复现步骤
Taro.showLoading Taro.hideLoading 加入到任何的网络请求中，然后打包，资源文件拖入taro react-native 壳工程中 xcode编译一下就出现错误，如下：
Buildtime (10)  Runtime
 X
 taroDemo Workspace 1 of 1 issue Error
 Multiple commands produce '/Users/libohao/Library/Developer/Xcode/DerivedData/taroDemo- blwarhqgcazinqcaenrzpkobcwwx/Build/Products/Debug-iphonesimulator/taroDemo.appl success.png':...

当删除掉其中一张图片之后就能编译通过了，初步判断是文件重命名了。请解决。

### 期望结果
打包后资源文件不重名

### 实际结果
解决冲突

### 环境信息
```
Taro v3.2.2


  Taro CLI 3.2.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.2.1 => 3.2.1 
      @tarojs/mini-runner: 3.2.1 => 3.2.1 
      @tarojs/react: 3.2.1 => 3.2.1 
      @tarojs/runtime: 3.2.1 => 3.2.1 
      @tarojs/taro: 3.2.1 => 3.2.1 
      @tarojs/webpack-runner: 3.2.1 => 3.2.1 
      babel-preset-taro: 3.2.1 => 3.2.1 
      eslint-config-taro: 3.2.1 => 3.2.1 
      react: ^17.0.0 => 17.0.2 
      react-native: ^0.64.0 => 0.64.0 
```

**Comment by iambool** [comment]
@qylibohao 同学，你代码里面没找到哪里用了showLoading啊，也没看到资源文件success.png相关内容

**Comment by qylibohao** [comment]
> @qylibohao 同学，你代码里面没找到哪里用了showLoading啊，也没看到资源文件success.png相关内容

打包到bundle里面了

**Comment by zhiqingchen** [comment]
经 @qylibohao 查明，为 xcode 静态资源引用问题。
