### ISSUE TITLE
H5端支持页面路由转场动画

### ISSUE THREAD

**Issue by crixusshen** [NervJS/taro#9208]
### 这个特性解决了什么问题？
目前我们使用Taro在开发APP端的H5页面，但是发现页面路由在H5端并没有动画转场的支持

### 这个 API 长什么样？
希望可以支持动画转场的配置，这个需求非常迫切

**Comment by chenjunjia97** [comment]
这个动画得自己实现吧

**Comment by crixusshen** [comment]
> 这个动画得自己实现吧

taro react底层并没有用react-router，用的是一个国外的库，所以自己实现比较难

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/app-config#animation)
