### ISSUE TITLE
Taro.chooseImage设置了count限制无效

### ISSUE THREAD

**Issue by A-quiet-boy** [NervJS/taro#9213]
### 相关平台
H5

### 复现仓库
[https://github.com/nervjs/taro](https://github.com/nervjs/taro)
**浏览器版本:  Chrome 62**
**使用框架: React**

### 复现步骤
就是使用chooseImage的count无效，可以选取任意数量的图片，count设置为1有效，其他无效

### 期望结果
上传图片直接有限定数量

### 实际结果
上传图片直接没有限定数量

### 环境信息
```
Taro v3.2.2


  Taro CLI 3.2.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.2 => 3.2.2 
      @tarojs/components: 3.2.2 => 3.2.2 
      @tarojs/mini-runner: 3.2.2 => 3.2.2 
      @tarojs/react: 3.2.2 => 3.2.2 
      @tarojs/runtime: 3.2.2 => 3.2.2 
      @tarojs/taro: 3.2.2 => 3.2.2 
      @tarojs/webpack-runner: 3.2.2 => 3.2.2 
      babel-preset-taro: 3.2.2 => 3.2.2 
      eslint-config-taro: 3.2.2 => 3.2.2 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 3.8.3
```

---
### 补充信息
无

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro/blob/next/packages/taro-h5/src/api/image/chooseImage.js#L48
H5 应该做不到限制个数，只有单选、多选的区分

**Comment by hudson-dong** [comment]
> https://github.com/NervJS/taro/blob/next/packages/taro-h5/src/api/image/chooseImage.js#L48 H5 应该做不到限制个数，只有单选、多选的区分

大佬, 这个链接失效了 还有怎么设置单选、多选
