### ISSUE TITLE
无法开发钉钉小程序

### ISSUE THREAD

**Issue by yeyaolong** [NervJS/taro#9214]
### 相关平台
支付宝小程序

**小程序基础库: 钉钉小程序开发工具里没有看到这个字段**
**使用框架: React**

### 复现步骤
- 1、安装插件 `npm install @tarojs/plugin-platform-alipay-dd `
- 2、在config/index.js中添加插件 
```
plugins: [
    '@tarojs/plugin-platform-alipay-dd'
  ],
```
- 3、执行构建命令 `npm run build:tt`
- 4、使用钉钉小程序开发者工具打开`dist`文件
- 5、钉钉小程序开发工具无法运行打包后的dist文件

### 期望结果
打包后的项目能够在钉钉小程序开发工具中正常运行

### 实际结果
项目无法运行

### 环境信息
```
�👽 Taro v3.2


  Taro CLI 3.2.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.11.2 - C:\Users\admin\AppData\Roaming\npm\npm.CMD
```

---
### 补充信息
- 1、我实际开发的是钉钉小程序，因为下拉列表中没有这个选项，所以我选了支付宝小程序
- 2、taro/cli 版本是 3.2.6，因为下拉列表中没有3.2.6版本，所以我选了3.2.5版本

**Comment by yeyaolong** [comment]
使用 taro/cli生成的项目，没有改动过内部的代码

**Comment by yeyaolong** [comment]
还有一个问题，顶i的那个小程序的页面文件后缀应该是 `index.axml`，但是我使用taro build出来的 却是  `.ttml`后缀的文件

**Comment by yeyaolong** [comment]
![image](https://user-images.githubusercontent.com/10331296/116339595-44ac0780-a810-11eb-96e0-ac0c76f8d9e0.png)
我手动将 `.ttml`全部改成`.axml`后，钉钉小程序编译器中给我报了这个错误.
`ReferenceError: tt is not defined`

**Comment by luckyadam** [comment]
https://github.com/NervJS/taro-plugin-platform-alipay-dd

**Comment by yeyaolong** [comment]
> https://github.com/NervJS/taro-plugin-platform-alipay-dd
> 看下这个 readme

我使用了这个api，发现是我`build`操作的命令打错了，正确的命令是`taro build --type dd`,而我上面使用的是`taro build --type tt`，这个实际是字节跳动小程序`build`命令。
但是，我按照这个readme依然会报错，报错如下:
![image](https://user-images.githubusercontent.com/10331296/116364578-eba39a00-a836-11eb-9e21-d6f7c73e7796.png)

我已经尝试过安装 `gdt-jsapi`但是依旧无法解决上述问题。

```bash
npm init -y
npm install gdt-jsapi
```

**Comment by yeyaolong** [comment]
我在钉钉小程序开发工具中测试了一下，项目是可以运行的。
导致这个异常的原因是，我使用的是专有钉钉小程序开发工具，还需要多做一次小程序的迁移动作，具体可以看专有钉钉小程序的开发文档
https://openplatform-portal.dg-work.cn/portal/?spm=a2q2b.13441934.0.0.46b96fbaJhqMOv#/helpdoc?docKey=kfzn&slug=ae0py5

**Comment by SkyeSun** [comment]
> > 我已经尝试过安装 gdt-jsapi但是依旧无法解决上述问题。
> 
> 我在钉钉小程序开发工具中测试了一下，项目是可以运行的。
> 导致这个异常的原因是，我使用的是专有钉钉小程序开发工具，还需要多做一次小程序的迁移动作，具体可以看专有钉钉小程序的开发文档
> https://openplatform-portal.dg-work.cn/portal/?spm=a2q2b.13441934.0.0.46b96fbaJhqMOv#/helpdoc?docKey=kfzn&slug=ae0py5

大佬这个问题是怎么解决的？我用0.0.5版本配合 Taro 3.2.13 版本 使用 taro build --type dd --watch 命令编译出来的代码，在钉钉小程序开发工具中打开，也是报 "ReferenceError: dd is not defined"，各种试了都没用
