### ISSUE TITLE
3.2.6报错

### ISSUE THREAD

**Issue by yaobiao131** [NervJS/taro#9216]
### 相关平台
微信小程序

**小程序基础库: 最新版**
**使用框架: React**

### 复现步骤
编译就报错

### 期望结果
无报错

### 实际结果
报错

### 环境信息
```
Taro CLI 3.2.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
```

![image](https://user-images.githubusercontent.com/28655758/116341417-796d8e00-a813-11eb-9cb7-f576c06aa786.png)

**Comment by 810505339** [comment]
我也遇到了 - -感觉是node-gyp 问题

**Comment by Chen-jj** [comment]
使用 nodejs14 试试
