### ISSUE TITLE
onPullDownRefresh onPullDownRefresh 在小程序中函数不会触发

### ISSUE THREAD

**Issue by ranglang** [NervJS/taro#922]
onPullDownRefresh onPullDownRefresh 在小程序中函数不会触发
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
运行小程序，在微信预览即可

代码请见 [link](https://github.com/ranglang/TodoMVC/commit/f1163332d01dde36c869ff8df42e6098f29b8ced)

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10] mac
 - Taro 版本 [e.g. v.0.0.64] 1.0.7
 - Node.js 版本 [e.g. v9.0.0] v8.11.3
 - 报错平台 [h5, weapp] weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0
