### ISSUE TITLE
taro babel target本地开发生效 build后不生效

### ISSUE THREAD

**Issue by GZWZC** [NervJS/taro#9221]
### 相关平台
微信小程序

### 复现仓库
[https://github.com](https://github.com)
**小程序基础库: 1**
**使用框架: React**

### 复现步骤
ios10或者低版本安卓手机访问本地开发链接是可以访问的。

如果执行了taro build --type h5 --env development后控制台就报错了。

```Uncaught SyntaxError: 'super' keyword unexpected here```

### 期望结果
可以正常访问，支持兼容性ios10以及低版本安卓

### 实际结果
白屏。js报错

### 环境信息
```
👽 Taro v3.1.4


  Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.4 => 3.1.4 
      @tarojs/components: 3.1.4 => 3.1.4 
      @tarojs/mini-runner: 3.1.4 => 3.1.4 
      @tarojs/react: 3.1.4 => 3.1.4 
      @tarojs/runtime: 3.1.4 => 3.1.4 
      @tarojs/taro: 3.1.4 => 3.1.4 
      @tarojs/webpack-runner: ^3.0.24 => 3.1.4 
      babel-preset-taro: 3.1.4 => 3.1.4 
      eslint-config-taro: 3.1.4 => 3.1.4 
      react: ^16.14.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
    npmGlobalPackages:
      typescript: 4.0.3
```

**Comment by GZWZC** [comment]
babel.config.js
```
// babel-preset-taro 更多选项和默认值：
// https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/README.md
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: true,

      hot: false,
      targets: {
        ios: '9',
        android: '4'
      }
    }]
  ]
}
```

**Comment by GZWZC** [comment]
/node_modules/@tarojs/webpack-runner/dist/util/chain.js

![image](https://user-images.githubusercontent.com/16217142/116499023-bd2cca00-a8dd-11eb-812a-177edda6e28c.png)

我将exclude修改成[]即可。


```
rule.script = {
        test: helper_1.REG_SCRIPTS,
        exclude: [],
        use: {
            babelLoader: getBabelLoader([{
                    compact: false
                }])
        }
    };
```

**Comment by GZWZC** [comment]
为什么执行```taro build --type h5 --watch --env development```没有问题

执行```taro build --type h5 --env development```有问题？ 需要如何去修改或者有fix版本吗？

**Comment by Chen-jj** [comment]
> 为什么执行`taro build --type h5 --watch --env development`没有问题
> 
> 执行`taro build --type h5 --env development`有问题？ 需要如何去修改或者有fix版本吗？

升级到最新版再试试，这两个应该一样的，`NODE_ENV` 都是 `development`，且不影响 babel 规则。

问题应该在于 babel-loader 的 external，可以从这些方向定位一下：

1.  @tarojs/components 这个包不兼容
2. node_modules 中某些包不兼容
3. 项目根目录名字带 taro

这些情况都不走 babel，可以使用 webpack chain 修改 external 配置，不过全部走 babel 的话编译速度非常慢，可以自行斟酌一下

**Comment by GZWZC** [comment]
@Chen-jj 可以使用 webpack chain 修改 external 配置。有具体的代码吗/？

**Comment by GZWZC** [comment]
```命令一：taro build --type h5 --watch --env development```
isWatch: true
NODE_ENV: development
mode: development

```命令二：taro build --type h5 --env development```
isWatch: false
mode: production


/node_modules/@tarojs/webpack-runner/dist/index.js
![image](https://user-images.githubusercontent.com/16217142/117573137-e8e35780-b108-11eb-93ff-74b2d15c78f8.png)

**Comment by GZWZC** [comment]
webpack打印了配置，罗列了下不同点
```
dev webpackConfig
webpackConfig, {
  mode: 'development',
  devtool: 'cheap-module-eval-source-map',
  module: {
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  optimization: { noEmitOnErrors: true },
  plugins: [
    MainPlugin {
      pagesConfigList: Map {},
      pages: Set {},
      tryAsync: [Function],
      options: [Object],
      sourceDir: '/Users/cc/yujia/idolyx-front/src',
      outputDir: '/Users/cc/yujia/idolyx-front/dist/h5'
    },
    CopyPlugin { patterns: [], options: {} },
    HtmlWebpackPlugin { options: [Object] },
    DefinePlugin { definitions: [Object] }
  ],
}
```


```
prod webpackConfig, 
{
  mode: 'production',
  devtool: 'none',
  module: {
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  optimization: { minimizer: [ [TerserPlugin] ], splitChunks: { name: false } },
  plugins: [
    MainPlugin {
      pagesConfigList: Map {},
      pages: Set {},
      tryAsync: [Function],
      options: [Object],
      sourceDir: '/Users/cc/yujia/idolyx-front/src',
      outputDir: '/Users/cc/yujia/idolyx-front/dist/h5'
    },
    MiniCssExtractPlugin { options: [Object] },
    CopyPlugin { patterns: [], options: {} },
    HtmlWebpackPlugin { options: [Object] },
    DefinePlugin { definitions: [Object] },
    CssoWebpackPlugin {
      options: [Object],
      filter: [Function: filterDefault],
      pluginOutputPostfix: null
    }
  ],
}
```

**Comment by GZWZC** [comment]
webpackConfig.module 罗列了下不同命令下的不同点
```
dev webpackConfig.module
{
  "rules": [
    {
      "test": {},
      "exclude": [
        null
      ],
      "use": [
        {
          "loader": "/node_modules/style-loader/dist/cjs.js"
        }
      ]
    },
    {
      "test": {},
      "oneOf": [
        {
          "include": [
            {}
          ],
          "use": [
            {
              "loader": "/node_modules/css-loader/dist/cjs.js",
              "options": {
                "sourceMap": true,
              }
            }
          ]
        },
        {
          "use": [
            {
              "loader": "/node_modules/css-loader/dist/cjs.js",
              "options": {
                "sourceMap": true,
              }
            }
          ]
        }
      ]
    },
    {
      "test": {},
      "exclude": [
        null
      ],
      "use": [
        {
          "loader": "/node_modules/postcss-loader/src/index.js",
          "options": {
            "sourceMap": true
          }
        }
      ]
    },
    {
      "test": {},
      "use": [
        {
          "loader": "/node_modules/@tarojs/webpack-runner/node_modules/less-loader/dist/cjs.js",
          "options": {
            "sourceMap": true
          }
        }
      ]
    },
    {
      "test": {},
      "use": [
        {
          "loader": "/node_modules/@tarojs/webpack-runner/node_modules/stylus-loader/index.js",
          "options": {
            "sourceMap": true
          }
        }
      ]
    },    
  ]
}
```

```
prop webpackConfig.module
{
  "rules": [
    {
      "test": {},
      "exclude": [
        null
      ],
      "use": [
        {
          "loader": "/node_modules/@tarojs/webpack-runner/node_modules/mini-css-extract-plugin/dist/loader.js"
        }
      ]
    },
    {
      "test": {},
      "oneOf": [
        {
          "include": [
            {}
          ],
          "use": [
            {
              "loader": "/node_modules/css-loader/dist/cjs.js",
              "options": {
                "sourceMap": false,
              }
            }
          ]
        },
        {
          "use": [
            {
              "loader": "/node_modules/css-loader/dist/cjs.js",
              "options": {
                "sourceMap": false,
              }
            }
          ]
        }
      ]
    },
    {
      "test": {},
      "exclude": [
        null
      ],
      "use": [
        {
          "loader": "/node_modules/postcss-loader/src/index.js",
          "options": {
            "sourceMap": false,
          }
        }
      ]
    },
    {
      "test": {},
      "use": [
        {
          "loader": "/node_modules/@tarojs/webpack-runner/node_modules/less-loader/dist/cjs.js",
          "options": {
            "sourceMap": false
          }
        }
      ]
    },
    {
      "test": {},
      "use": [
        {
          "loader": "/node_modules/@tarojs/webpack-runner/node_modules/stylus-loader/index.js",
          "options": {
            "sourceMap": false
          }
        }
      ]
    },
  ]
}
```

**Comment by GZWZC** [comment]
@Chen-jj 从罗列出来不同点里，也没有看出babel-loader的配置有什么不一样哦

**Comment by GZWZC** [comment]
下载了一下taro的官网demo，执行```npm run dev:h5```后，用安卓模拟器访问是可以访问的。
![image](https://user-images.githubusercontent.com/16217142/119508025-f6077400-bda1-11eb-84b1-3e41eae64561.png)



执行```npm run build:h5```后，启用```http-server```后，用安卓模拟器访问就不可以了
![image](https://user-images.githubusercontent.com/16217142/119507945-dec88680-bda1-11eb-84f6-7cd9b27770b8.png)

**Comment by WangChenS117** [comment]
兄弟 我用webpack-chain  修改或者添加了下规则  用babel-loader 处理下 @tarojs/components库  就好使了   不过不知道什么原因导致的    windows 服务器打包不加这个也是没问题的   只有mac和linux 是这样

**Comment by WangChenS117** [comment]
兄弟 我用webpack-chain  修改或者添加了下规则  用babel-loader 处理下 @tarojs/components库  就好使了   不过不知道什么原因导致的    windows 服务器打包不加这个也是没问题的   只有mac和linux 是这样

**Comment by GZWZC** [comment]
@WangChenS117 你的webpack-chain是如何配置的，我处理后还是不行

**Comment by 1337968347** [comment]
偷偷看了一两天了，就在刚才我弄成功了 。 我的taro cli 版本是3.2.9。
我主要是为了打包node_modules 中的 @capacitor/core 依赖 转成es5

1。 安装 
npm install --save core-js   
npm install --save-dev @babel/preset-env
npm install --save-dev @babel/core

下边是我config/index 中h5 部分 
`
webpackChain(chain) {
      chain.merge({
        module: {
          rule: {
            // 插件名字
            es5Loader: {
              test: /.*capacitor.*\.js$/,
              use: [
                {
                  loader: 'babel-loader',
                  options: {
                    presets: [['@babel/preset-env', { useBuiltIns: 'usage', targets: '> 0.25%, not dead', corejs: '3.12.1' }]],
                  },
                },
              ],
            },
          },
        },
      });
    },
`

**Comment by 1337968347** [comment]
![image](https://user-images.githubusercontent.com/23535133/119598776-2688f580-be16-11eb-9fd9-4a7bc1bf67d0.png)
![image](https://user-images.githubusercontent.com/23535133/119598794-2f79c700-be16-11eb-8fea-f4af4009662d.png)
这是我的依赖

**Comment by WangChenS117** [comment]
> @WangChenS117 你的webpack-chain是如何配置的，我处理后还是不行
简单的重写了一下,不知道跟 @1337968347 大佬的方式有什么区别，大佬的代码我的入门水平还没法看懂  其实自己的也不太懂
chain.merge({
    module: {
        rule: {
            fixes5Loader: {
                test: /.(js|jsx|ts|tsx)$/,
                include: [`${path.join(process.cwd(), 'node_modules/@tarojs/components')}`,`${path.join(process.cwd(), 'node_modules/@stencil')}`],
                use: [{
                    loader: 'babel-loader'
                }]
            }
        }
    }
})

后面@stencil的处理好像不需要  我已经删掉了

**Comment by GZWZC** [comment]
@WangChenS117 好像也是不可以哦

demo: https://github.com/GZWZC/testTaroAndroid

**Comment by Chen-jj** [comment]
应该是同一个问题：#8648 

`@taorjs/components` 使用 Stencil 打包，之前没有输出 ES5 代码，又配置了 `babel-loader` 的 `external` 把它忽略了，所以会报错。3.2.10+ 后已修复。
