### ISSUE TITLE
打包代码后存在 es6 语法 导致低版本机型不可用

### ISSUE THREAD

**Issue by LengYXin** [NervJS/taro#9224]
### 相关平台
微信小程序

**小程序基础库: 2.16.0**
**使用框架: React**

### 复现步骤
编译打包
![image](https://user-images.githubusercontent.com/19631404/116413923-9e412000-a86a-11eb-807c-6d302d3c8b32.png)

### 期望结果
打包后代码中存在 const 

### 实际结果
没有es6语法

### 环境信息
```
Taro CLI 3.2.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 7.5.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      babel-preset-taro: 3.1.4 => 3.1.4 
```

**Comment by luckyadam** [comment]
可以自己配置 compile，把 node_modules 里的资源再用 babel 处理一遍

**Comment by LengYXin** [comment]
> 可以自己配置 compile，把 node_modules 里的资源再用 babel 处理一遍

好的~
