### ISSUE TITLE
在 H5 中 `Block` 组件下的 `children` 无法更新渲染

### ISSUE THREAD

**Issue by u3u** [NervJS/taro#923]
**问题描述**

在 H5 中 `Block` 组件下的 `children` 无法更新渲染 (`props` / `state`)，在微信小程序中正常

**复现步骤**

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8w8zo0188?eslint=1&expanddevtools=1&fontsize=12&module=%2Flayouts%2Fbasic.js)

`src/layouts/basic/index.tsx`

```jsx
import Taro from '@tarojs/taro';
import { Block, View } from '@tarojs/components';
import classNames from 'classnames';
import Navbar from '../../components/navbar';
import './index.scss';

const { model, platform, statusBarHeight } = Taro.getSystemInfoSync();
const iPhoneX = /iPhone\s?X/i.test(model);
const iPhoneXS = /unknown<iPhone11,(2|4|6|8)>/i.test(model);
const isWeApp = process.env.TARO_ENV === 'weapp';

export interface BasicLayoutProps {
  'view-class'?: string;
  title: string | undefined;
  showTitle?: boolean;
}

export default class BasicLayout extends Taro.Component<BasicLayoutProps> {
  public static readonly defaultProps = {
    showTitle: true,
  };

  public static readonly externalClasses = ['view-class'];

  render() {
    const { title, showTitle } = this.props;
    const viewClass = isWeApp ? 'view-class' : this.props['view-class'];
    const view = (
      // 经测试将这里的 Block 改成 View 就可以正常更新，但会影响我的布局
      <Block>
        <View
          className="status-bar"
          style={{ height: `${statusBarHeight}px` }}
        />
        <Navbar title={title} disabled={showTitle} />
        <View className={classNames('view', viewClass)}>
          {this.props.children} {/* 所有子组件都无法更新 */}
        </View>
        {(iPhoneX || iPhoneXS) && platform !== 'devtools' ? (
          <View className="danger-area" style={{ height: '34px' }} />
        ) : null}
      </Block>
    );

    return isWeApp ? view : <View className="container">{view}</View>;
  }
}
```

`src/pages/index/index.tsx`

```jsx
import Taro, { Component, Config } from '@tarojs/taro';
import { Text } from '@tarojs/components';
import BasicLayout from '../../layouts/basic';
import './index.scss';

export default class Index extends Comopnent {
  public readonly config: Config = {
    navigationBarTitleText: 'Test',
  };

  public state = {
    color: '#000',
  };

  private handleClick = () => {
    this.setState({ color: '#999' });
  };

  render() {
    const { color } = this.state;
    console.log(color); // 点击之后更新 state，这里可以拿到更新后的值，但无法更新渲染

    return (
      <BasicLayout view-class="view-index" title="Test">
        <Text onClick={this.handleClick} style={{ color }}>
          Test
        </Text>
      </BasicLayout>
    );
  }
}
```

**期望行为**

在 H5 中可以正常更新 `Block` 组件下的 `children`

**报错信息**

无

**系统信息**

- 操作系统: macOS Mojave
- Taro 版本: v1.1.0-beta.11
- Node.js 版本: v10.9.0
- 报错平台: [h5]

**Comment by yuche** [comment]
尝试构建这样的 `Block`：
```
const Block = ({ children }) => children;
```

然后使用这个 `Block` 替换从 `@tarojs/components' ` 引入的 `Block` 看看是否能够更新

**Comment by yuche** [comment]
我根据你的情况大概构建了一个简单 demo，但不管是 `children` 还是 `style` 都是能够更新了。

https://codesandbox.io/s/m569y854wy

如果你能在这里复现就再好不过了。

**Comment by u3u** [comment]
> @yuche: 尝试构建这样的 `Block`:
> `const Block = ({ children }) => children;`

当我改成这样后更新渲染时会报错：
Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.

而使用 `@tarojs/components` 里的 `Block` 组件只是没有任何反应

<img src="https://user-images.githubusercontent.com/20062482/47479331-5b4bff00-d85f-11e8-805d-0fd11329ded9.png" width="600">

我一会儿尝试在 CodeSandbox 里复现

**Comment by u3u** [comment]
@yuche 已在 CodeSandbox 复现

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8w8zo0188?eslint=1&expanddevtools=1&fontsize=12&module=%2Flayouts%2Fbasic.js)

**Comment by yuche** [comment]
更新 `nervjs` 到 `1.3.6` 应该就可以了

[![Edit Nerv Bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r4qzmo75np)
