### ISSUE TITLE
3.2.7 版本升级后 less-loader报错

### ISSUE THREAD

**Issue by gushisan** [NervJS/taro#9236]
### 相关平台
微信小程序

**小程序基础库: -**
**使用框架: React**

### 复现步骤
3.2.7 版本升级后 less-loader报错
无法识别less中定义的变量

### 期望结果
no error

### 实际结果
Module build failed (from ./node_modules/_mini-css-extract-plugin@0.8.0@mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/_less-loader@7.3.0@less-loader/dist/cjs.js):

### 环境信息
```
  Taro CLI 3.2.5 environment info:
    System:
      OS: macOS 11.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.1.2 => 3.2.7 
      @tarojs/components: ^3.1.2 => 3.2.7 
      @tarojs/mini-runner: ^3.1.2 => 3.2.7 
      @tarojs/react: ^3.1.2 => 3.2.7 
      @tarojs/runtime: ^3.1.2 => 3.2.7 
      @tarojs/taro: ^3.1.2 => 3.2.7 
      @tarojs/webpack-runner: ^3.1.2 => 3.2.7 
      babel-preset-taro: ^3.1.2 => 3.2.7 
      eslint-config-taro: ^3.1.2 => 3.2.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^2.3.4 => 2.3.4 
```

---
### 补充信息
目前回退到3.2.5 无问题

**Comment by gushisan** [comment]
更正：回退到3.2.6 无问题

**Comment by luckyadam** [comment]
麻烦给个示例看看

**Comment by gushisan** [comment]
.m-comp-member{
  @headerWidth: 560rpx;
  @avatarSize: 130rpx;
  @avatarGap: 32rpx;
  &__avatar {
    @avatarWidth: @headerWidth - @avatarSize * 2 + @avatarGap;
    &--pic {
      left: @avatarWidth / 2;
    }
  }
}

**Comment by nanxiaobei** [comment]
less-loader 确实出了问题。

比如 `transform: scale(3 / 4)`，里面的 `3 / 4` 没有变成 `0.75`，还是原样，导致 UI 错乱了。

**Comment by jpdan** [comment]
计算使用括号括起来，transform: scale((3 / 4))

**Comment by nanxiaobei** [comment]
> 计算使用括号括起来，transform: scale((3 / 4))

一模一样的代码，在 `3.2.6` 之前都是好的，升级之后什么也没动，样式就崩了。

**Comment by jpdan** [comment]
3.2.7版本less@3.x升级到4.x了
https://github.com/less/less.js/releases

**Comment by luckyadam** [comment]
没有复现问题啊，可以把 node_modules 和 lock file 删了，然后再重新安装依赖，CLI 版本要和依赖版本保持一致

**Comment by crimson968** [comment]
确实是有这个问题的，我在3.2.10也遇到了，目前无法解决
