### ISSUE TITLE
百度小程序无法显示PickerViewColumn组件

### ISSUE THREAD

**Issue by yuzhounanhai** [NervJS/taro#9239]
### 相关平台
百度小程序

**小程序基础库: 3.280.26**
**使用框架: React**

### 复现步骤
官网例子即可重现
http://taro-docs.jd.com/taro/docs/components/forms/picker-view

### 期望结果
正确显示

### 实际结果
未渲染PickerViewColumn，PickerView组件内为空

### 环境信息
```
Taro v3.1.4


  Taro CLI 3.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by yuzhounanhai** [comment]
![img](https://user-images.githubusercontent.com/33368704/116543054-f84fed00-a91f-11eb-855f-23bdbb383a22.png)

**Comment by luckyadam** [comment]
升级到最新版本试试

**Comment by yuzhounanhai** [comment]
> 升级到最新版本试试

也是无法显示的
