### ISSUE TITLE
Taro的api 如何写jest单元测试？

### ISSUE THREAD

**Issue by kiana-god** [NervJS/taro#9243]
### 这个特性解决了什么问题？
Taro在做单测时，遇到很多关于api is not function的问题
如：    TypeError: _taro2.default.getRealtimeLogManager is not a function
useReady, useDidShow, useDidHide  这些都是，如果在useReady 中使用了 useState，还会报错 react重复渲染，让测试覆盖率难以提升。

### 这个 API 长什么样？
我想请问官方，这些api该如何处理，网上没有如何例子，让单元测试难以执行，希望能help me

**Comment by hongyue-qiu** [comment]
全局mock`@tarojs/taro`文件，useReady、useRouter等hooks不生效

**Comment by b2nil** [comment]
@hongyue-qiu

从 `runtime` 引入相关的 hooks 函数，然后再挂载到 `Taro` 上呢？

```js
// @tarojs/taro mock file

const Taro = require('@tarojs/taro/h5')
const runtime = require('@tarojs/runtime')

Taro.useRouter = runtime.useRouter
Taro.useReady = runtime.useRouter

export default Taro
```

**Comment by ZakaryCode** [comment]
[Jest 参考文档](https://nervjs.github.io/taro/docs/next/external-libraries/#jest)
