### ISSUE TITLE
QQ小程序Button属性未在ts中定义

### ISSUE THREAD

**Issue by JackyLeeCS** [NervJS/taro#9248]
### 这个特性解决了什么问题？
QQ小程序Button特有的属性"groupId"、“openId”、“publicId”属性未在ts中定义，代码中会有警告。

### 这个 API 长什么样？
相应属性能在ts中定义。

**Comment by Chen-jj** [comment]
@JackyLeeCS 

1. 升级到 3.2.8
2. 在 global.d.ts 文件的上方加入 `/// <reference path="node_modules/@tarojs/plugin-platform-qq/types/shims-qq.d.ts" />`
