### ISSUE TITLE
Input focus 属性 路由跳转后失效

### ISSUE THREAD

**Issue by shhdgit** [NervJS/taro#925]
**问题描述**

如题，Input focus 属性 路由跳转后失效

**复现步骤**

1. 设置 Input 组件 focus 属性
2. 首次进到有 Input 组件的页面，能自动 focus 到 Input 组件，后续再次进入该页面则无效
3. 在componentDidMount 上 `this.setState({ focus: true })` 也无效

很多情况下 focus 属性并没有预期的表现，如点击触发 ` this.setState({ focus: true }) ` 并不能focus到 Input 组件

**期望行为**

focus 在多次路由跳转后依然有效

**报错信息**

无

**系统信息**

 - 操作系统: macOS
 - Taro 版本 1.0.0-beta.11
 - Node.js 版本 10.12.0
 - 报错平台 h5, weapp

**补充信息**

![1](https://user-images.githubusercontent.com/11549583/47423337-52075780-d7b7-11e8-887e-a67f66b23a91.gif)

**Comment by luckyadam** [comment]
加一个 setTimeout 试试呢

**Comment by shhdgit** [comment]
@luckyadam 各种方法都试过了😂

**Comment by shhdgit** [comment]
taro-components里的input的focus是直接赋值给autofocus的，h5模式也是直接使用的html的autofocus吧。这么做应该无法符合预期：
https://stackoverflow.com/questions/49594197/autofocus-attribute-works-once-but-not-twice-on-input-elements

**Comment by jinjinjin0731** [comment]
抱歉~~~ 现在这个问题已修复~ :)

**Comment by Dadarui** [comment]
> 抱歉~~~ 现在这个问题已修复~ :)

请问怎么修复的，求教
