### ISSUE TITLE
在taro上面找不到VideoDecoder这个视频解码器的功能。

### ISSUE THREAD

**Issue by yaodongyi** [NervJS/taro#9250]
### 这个特性解决了什么问题？
VideoDecoder 视频解码器，可以进行视频解码相关操作，逐帧获取解码数据。wx文档是有提供的，但是taro好像还未支持？

### 这个 API 长什么样？
期望加上此api，不然无法对视频进行截屏

**Comment by Chen-jj** [comment]
Taro 3.1 开始已支持 `Taro.createVideoDecoder` API
