### ISSUE TITLE
小程序端非生产模式下无法应用 csso 配置问题

### ISSUE THREAD

**Issue by chuyun** [NervJS/taro#9251]
### 这个特性解决了什么问题？
微信小程序开发模式下，build 出的预览包很大，无法直接在手机预览，期望放出 csso 在非生产环境下应用配置的功能

### 这个 API 长什么样？
小程序端非生产模式下应用 csso 配置

**Comment by Chen-jj** [comment]
配置环境变量 `NODE_ENV` 为 `production` 就可以了吧。

**Comment by chuyun** [comment]
> 配置环境变量 `NODE_ENV` 为 `production` 就可以了吧。

开发模式 配置环境变量也没用吧

**Comment by tourze** [comment]
最好还是能单独配置csso的。例如开发环境我们希望js不要压缩，单独压缩css
