### ISSUE TITLE
scroll-view(h5必现) : scrollIntoView动态添加子节点并滚动底部，子节点渲染顺序出错

### ISSUE THREAD

**Issue by CristalFJJ** [NervJS/taro#9260]
### 相关平台
H5

### 复现仓库
[https://github.com/CristalFJJ/taro-scroll-view](https://github.com/CristalFJJ/taro-scroll-view)
**浏览器版本: Chrome 89**
**使用框架: React**

### 复现步骤
1、scroll-view 动态添加子节点；
2、滚动到底部；

### 期望结果
节点渲染顺序正常

### 实际结果
节点渲染顺序异常

### 环境信息
```
Taro v3.2.7


  Taro CLI 3.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
h5 必现，通过控制scrollTop也是一样顺序异常，小程序正常

**Comment by CristalFJJ** [comment]
![image](https://user-images.githubusercontent.com/28974824/117620576-30b6bd00-b1a3-11eb-93ce-77f1553f475f.png)
是children渲染处理有点问题吗？注释这一段就demo就表现正常了

**Comment by CristalFJJ** [comment]
暂采用h5代码兼容解决

**Comment by Laev** [comment]
我是3.1.0版本，似乎不止在ScrollView组件里会出现这个问题，正常写下来，只要有一个节点做了数据是否为空的判断渲染，那个节点也许在数据慢一点的情况下，顺序会乱掉 该节点会在后面，而非按原有的顺序渲染。

**Comment by maxlxq** [comment]
+1

**Comment by cgc1983** [comment]
什么时候能修复这个问题？

**Comment by hannq** [comment]
+1

**Comment by ZakaryCode** [comment]
#10365 应该是同一个问题，可以查看此评论：#10365 (comment)

> 修复升级到 3.3.13+

**Comment by Howie126313** [comment]
这个问题修复好了？？ 3.5.7 又遇到了。。。。

**Comment by ZakaryCode** [comment]
> 这个问题修复好了？？ 3.5.7 又遇到了。。。。

已关闭的 issue 不会及时关注的，有同样的问题请通过提交新的 issue 反馈，也便于快速了解所述问题详情。
另外关于该模块适配器在 3.6 canary 中有较多调整，也可以先行在新版本中尝试。
