### ISSUE TITLE
Taro.getSetting() 微信小程序 缺少 withSubscriptions 类型

### ISSUE THREAD

**Issue by allen-wiki** [NervJS/taro#9277]
### 这个特性解决了什么问题？
缺少 withSubscriptions 的ts类型定义 

### 这个 API 长什么样？
			Taro.getSetting({
				withSubscriptions: true,
			})
				.then(res => {
					console.log(res);
				})
				.catch(() => {});

**Comment by ZakaryCode** [comment]
fix #10032
