### ISSUE TITLE
小程序页面缓存问题？

### ISSUE THREAD

**Issue by JoMartinezZhu** [NervJS/taro#928]
在页面1（list page）带参数跳转到页面2(list item page)，在页面2(list item page)返回页面1(list page)，第二次跳转的时候，页面2的结果是 显示了第一次的内容 然后 闪动一下 变成了 第二次想要的内容！

**Comment by EForinaJ** [comment]
我也是这样不知道怎么解决 好奇怪

**Comment by aijiacy** [comment]
页面 unmount 或 hide时 做一次清理

**Comment by luckyadam** [comment]
请提供一下 Taro 的版本

**Comment by JoMartinezZhu** [comment]
> 请提供一下 Taro 的版本

taro: 1.0.7
mac os

**Comment by luckyadam** [comment]
可以按 @aijiacy 说的，暂时通过手动清理

**Comment by Chen-jj** [comment]
@JoMartinezZhu @EForinaJ 我尝试了一下，只在渲染内容依赖 redux 提供的数据时出现这种问题。如果页面2渲染的数据不是依赖于 redux，这时是没有这种问题的。
如果你们提出的问题是在使用了 redux 的场景的话，这不算 bug。因为组件初次渲染依赖 redux 的数据，如果在组件销毁时没有重置相关的 redux 数据，那肯定是不正确的。重置 redux 数据这部分工作应该由开发者去做而不是框架。
如果你们没有使用 redux 就出现了这个问题，那请把相关最简可运行代码贴一下。
