### ISSUE TITLE
Fiber 无法再兼容 node 16 以上了

### ISSUE THREAD

**Issue by hyacinthus** [NervJS/taro#9291]
### 相关平台
H5

### 复现仓库
[https://github.com/laverdet/node-fibers/issues/451](https://github.com/laverdet/node-fibers/issues/451)
**浏览器版本: any**
**使用框架: React**

### 复现步骤
npm run dev:h5

### 期望结果
编译通过

### 实际结果
👽 Taro v3.2.8

Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
[1]    82886 abort      npm run build:h5

### 环境信息
```
👽 Taro v3.2.8


  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.1.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.11.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 


```

---
### 补充信息
https://github.com/laverdet/node-fibers/issues/451

Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.

**Comment by cikichen** [comment]
+1，同样的问题

**Comment by netfishx** [comment]
看源码得知，fibers 是用于 sassLoader 的。这个功能并不是所有人都需要的，所以不要默认依赖可以吗

**Comment by lemondreamtobe** [comment]
没有解决方案吗
