### ISSUE TITLE
taro h5，image 组件使用 lazyLoad 属性， 首次访问页面时图片渲染不出来

### ISSUE THREAD

**Issue by RichardDegeneres** [NervJS/taro#9294]
### 相关平台
H5

**浏览器版本: Chrome 90**
**使用框架: React**

### 复现步骤
1. 页面罗列多个(10 ) image 标签
2. 在倒数几个 image 中加入 lazyLoad 属性
3. 清除浏览器缓存, 重新加载页面

### 期望结果
滑动浏览页面时，图片一段时间后可见

### 实际结果
图片为空，taro-image-core 内 img 标签无 src 属性

### 环境信息
```
👽 Taro v3.0.26


  Taro CLI 3.0.26 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.22.5 - ~/.nvm/versions/node/v12.2.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    npmPackages:
      @tarojs/components: 3.0.26 => 3.0.26
      @tarojs/mini-runner: 3.0.26 => 3.0.26
      @tarojs/react: 3.0.26 => 3.0.26
      @tarojs/runtime: 3.0.26 => 3.0.26
      @tarojs/taro: 3.0.26 => 3.0.26
      @tarojs/webpack-runner: 3.0.26 => 3.0.26
      babel-preset-taro: 3.0.26 => 3.0.26
      eslint-config-taro: 3.0.26 => 3.0.26
      react: ^16.10.0 => 16.14.0
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10
```

**Comment by RichardDegeneres** [comment]
首屏加载时，image 标签 src 第一次传入值为 undefined 导致的

**Comment by xueerli** [comment]
同样遇到问题了 怎么解决？

**Comment by xueerli** [comment]
开启懒加载后 安卓的uc浏览器中部分图片没有src属性 @Chen-jj

**Comment by ZakaryCode** [comment]
未能复现到该问题，该特性通过 IntersectionObserver 实现，如果图片未能及时加载出来可能是由于线程被其他更高优先级的事务阻塞

**Comment by ZakaryCode** [comment]
未能复现到该问题，考虑由于 IntersectionObserver 部分浏览器支持程度导致，

> 开启懒加载后 安卓的uc浏览器中部分图片没有src属性 @Chen-jj

UC 浏览器不支持 IntersectionObserver API 导致 lazyload 参数失效。

**Comment by ZakaryCode** [comment]
> 开启懒加载后 安卓的uc浏览器中部分图片没有src属性 @Chen-jj

这是一个历史版本问题，已经在 https://github.com/NervJS/taro/commit/6ebcbeaed119438b7fb65834931838f3a123f204 中修复，仅在 1.3.20- 部分版本中出现。
