### ISSUE TITLE
VirtualList itemSize 

### ISSUE THREAD

**Issue by MX8CLUB** [NervJS/taro#9299]
### 这个特性解决了什么问题？
长列表itemSize怎么转为rpx？
单项高度为200，会根据页面自动转为rpx，但是itemSize是以px为高度，导致两边高度不一致，如何解决？

### 这个 API 长什么样？
单项高度200根据程序转换，而不是使用px

**Comment by ZakaryCode** [comment]
项目拿 px 写高度就行，如果是代码中写直接是 px，如果是样式中写可以将 px 写作 PX

**Comment by zuizeze** [comment]
@ZakaryCode 在rn端会有高度的转换错误，报
`
ExceptionsManager.js:180 Error: You attempted to set the key `height` with the value `100` on an object that is meant to be immutable and has been frozen.
`
