### ISSUE TITLE
build:tt  vs build:tt --watch 小程序样式不一致

### ISSUE THREAD

**Issue by hanxinimm** [NervJS/taro#9304]
### 相关平台
字节跳动小程序

**小程序基础库: 任意版本**
**使用框架: React**

### 复现步骤
分别输入 build:tt  和  build:tt --watch  ，
在 build:tt   模式下，会导致小程序样式缺失变形，样式无法正确应用

### 期望结果
正常显示
![image](https://user-images.githubusercontent.com/13499426/117649054-a3cf2c00-b1c1-11eb-9fb7-2e1ac724d7d2.png)

### 实际结果
无法正常显示，样式丢失

![image](https://user-images.githubusercontent.com/13499426/117648584-f9ef9f80-b1c0-11eb-9637-b70608628c76.png)

### 环境信息
```
👽 Taro v3.0.21

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.0.21 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files\nodejs\node_global\node_modules\yarn\bin\yarn.CMD
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@hanxinimm 提供一下 demo

**Comment by hanxinimm** [comment]
@Chen-jj   
[TestDemo.zip](https://github.com/NervJS/taro/files/6477364/TestDemo.zip)

![image](https://user-images.githubusercontent.com/13499426/118240146-38d96a00-b4cd-11eb-9fb9-502b306e3f87.png)
![image](https://user-images.githubusercontent.com/13499426/118240155-3c6cf100-b4cd-11eb-8ca8-1c6d7a3ab53f.png)

**Comment by hanxinimm** [comment]
有消息了吗？目前小程序等着发布呢，有样式问题，无法发布~

**Comment by Chen-jj** [comment]
@hanxinimm 原因是生产环境样式压缩后 `!important` 左侧没有空格了：`.fs-10{font-size:20rpx!important}`，而字节不支持。

**Comment by holy-func** [comment]
相同的问题，但是原因不在空格，而是飞书小程序不支持rpx，但是加了!important的水平方向属性被转成了rpx，

**Comment by holy-func** [comment]
非!important的属性还是px，看起来很诡异，（只在生产环境）
