### ISSUE TITLE
Taro3 预渲染失败 (3.2.8)

### ISSUE THREAD

**Issue by AnthonyHao** [NervJS/taro#9311]
### 相关平台
微信小程序

**小程序基础库: 2.13.0**
**使用框架: React**

### 复现步骤
```
  mini: {
    postcss: {},
    miniCssExtractPluginOption: {},
    prerender: {
      match: 'pages/product/**'
    }
  }
```
### 期望结果
正常预渲染

### 实际结果
build结果提示：页面app预渲染失败：
ReferenceError: localStorage is not defined
    at Object.getStorageSync (/Users/**/Git/mini/node_modules/miniprogram-simulate/src/api/data.js:29:27)

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8
      @tarojs/mini-runner: 3.2.8 => 3.2.8
      @tarojs/react: 3.2.8 => 3.2.8
      @tarojs/runtime: 3.2.8 => 3.2.8
      @tarojs/taro: 3.2.8 => 3.2.8
      @tarojs/webpack-runner: 3.2.8 => 3.2.8
      babel-preset-taro: 3.2.8 => 3.2.8
      eslint-config-taro: 3.2.8 => 3.2.8
      react: ^17.0.0 => 17.0.2
```

**Comment by zmGitHub** [comment]
怎么解决 一样的问题 taro3 各种不行

**Comment by lipengchao** [comment]
我也是一样的问题

**Comment by zmGitHub** [comment]
没人解决?

**Comment by lemondreamtobe** [comment]
我的异常是Cannot read property 'onLaunch' of undefined

**Comment by zmGitHub** [comment]
能不能先解决这个问题呢?

**Comment by MemoryNoodles** [comment]
> 我的异常是Cannot read property 'onLaunch' of undefined

我的也是，但是为撒taro团队的人把这个issue给关闭了

**Comment by Chen-jj** [comment]
> ReferenceError: localStorage is not defined
> at Object.getStorageSync (/Users/**/Git/mini/node_modules/miniprogram-simulate/src/api/data.js:29:27)

Taro 预渲染时会使用 [vm2](https://www.npmjs.com/package/vm2) 这个包起一个沙箱环境，并在沙箱中注入一些全局变量：

https://github.com/NervJS/taro/blob/8096e49f44f5897ad4b24dee51c96a00977dea26/packages/taro-mini-runner/src/prerender/prerender.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L175-L192

注入的全局变量中，包括了小程序的全局对象（如 `wx`），它是使用 `miniprogram-simulate` 这个包模拟的。

这样做会导致两个问题：

1. `miniprogram-simulate` 中会使用一些全局变量如 `wx`、`localStorage` 等，但 `vm2` 不支持为全局变量注入全局变量（不能为全局变量 `miniprogram-simulate` 注入全局变量 `localStorage`）。因此如果用户使用的 wx API 在 `miniprogram-simulate` 里的使用使用了全局变量，就会像楼主一样报错。
2. `miniprogram-simulate` 只支持微信 API，使用的 `wx.` 前缀。

因此，开发者如果遇到了 `miniprogram-simulate` 包中全局变量报错的问题，可以舍弃 `miniprogram-simulate`，自行模拟，例如：

```js
// config/index.js
const config = {
  mini: {
    prerender: {
      // 使用 mock 参数自行模拟 wx
      mock: {
        wx: {
          clearStorageSync: () => 'cjj'
        }
      }
    }
  }
}
```

**Comment by kcq22** [comment]
> 我的异常是Cannot read property 'onLaunch' of undefined

+1

**Comment by reed-soul** [comment]
> 



> 我的异常是Cannot read property 'onLaunch' of undefined

+1

**Comment by lupingW** [comment]
> Page

想问一下app和page注入的时机是最早的吗 用taro3.4.6会报App of undefined
