### ISSUE TITLE
Windows Edge浏览器，IE 11浏览器，白屏，完全无法显示

### ISSUE THREAD

**Issue by fluxaymlovey** [NervJS/taro#9315]
### 相关平台
H5

**浏览器版本: Edge 25, IE 11**
**使用框架: React**

### 复现步骤
直接taro init myApp创建即可

### 期望结果
正常显示内容

### 实际结果
空白。控制台报错：SCRIPT1002: 语法错误 app.js (2805,1)

### 环境信息
```
👽 Taro v3.2.8

Taro CLI 3.2.8 environment info:
System:
OS: macOS 10.15.7
Shell: 5.8 - /usr/local/bin/zsh
Binaries:
Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.6.3 - ~/.nvm/versions/node/v14.6.0/bin/npm
npmPackages:
@tarojs/components: 3.2.8 => 3.2.8
@tarojs/mini-runner: 3.2.8 => 3.2.8
@tarojs/react: 3.2.8 => 3.2.8
@tarojs/runtime: 3.2.8 => 3.2.8
@tarojs/taro: 3.2.8 => 3.2.8
@tarojs/webpack-runner: 3.2.8 => 3.2.8
babel-preset-taro: 3.2.8 => 3.2.8
eslint-config-taro: 3.2.8 => 3.2.8
react: ^17.0.0 => 17.0.2
```

---
### 补充信息
希望H5页面也能在PC端打开，这样业务可以更广泛兼容。

**Comment by Chen-jj** [comment]
Taro H5 使用 Stencil 实现 web components 标准的组件。

Stencil 兼容 IE11 需要额外配置：https://stenciljs.com/docs/config-extras#extras

Taro H5 端主要针对 H5 的生产环境，因此打包时没有兼容 IE11。

如果有需要兼容的情况，可以使用自行更改配置后打包的 @tarojs/components。

**Comment by zhangfu-git** [comment]
这个配置是修改哪里？
