### ISSUE TITLE
在app.less中定义的全局样式无法在自定义组件中去使用

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [NervJS/taro#9317]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
1：app.less中定义样式
2：components中创建自定义组件
3：使用全局样式

### 期望结果
能够适用全局样式

### 实际结果
无法使用全局样式，不会自动转化

### 环境信息
```
  Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.23.0-20200615.1913 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

---

**Comment by liuhuapiaoyuan** [comment]
感觉问题比较简单，就懒得提供复现问题了

**Comment by shinken008** [comment]
了解，我看下

**Comment by blade254353074** [comment]
全局样式的问题怎么样了，我这边也有遇到
目前只能每个页面引用

**Comment by shinken008** [comment]
这两天看一下，预计下个版本修复

**Comment by shinken008** [comment]
> @shinken008
> RN 的全局样式的问题怎么样了，我这边也有遇到
> 目前只能每个页面引用

这两天看一下，预计下个版本修复

**Comment by shinken008** [comment]
特性：
1. 项目中的组件会增加全局引入
2. node_modules 里面的组件配置resolve，也可以读取全局引入，https://taro-docs.jd.com/taro/docs/config-detail#rnresolve

**Comment by shinken008** [comment]
如果组件里面引入scss，也可以配置 https://taro-docs.jd.com/taro/docs/config-detail#rnsass
