### ISSUE TITLE
全局Toast

### ISSUE THREAD

**Issue by MX8CLUB** [NervJS/taro#9320]
### 这个特性解决了什么问题？
Toast提示信息是独立于页面之外的，跳转页面不会影响Toast的展示。
比如在APP中，登录之后弹出登录成功，跳转到其他页面后该Toast还能存在1-2s

**Comment by Chen-jj** [comment]
每个小程序页面都有自己的 `data` 和模板，实现不了这种夸页面保持状态的组件。
