### ISSUE TITLE
如何准确获得屏幕内的安全区域高度的，以及导航栏的高度

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [NervJS/taro#9323]
### 这个特性解决了什么问题？
如何准确获得屏幕内的安全区域高度的，以及导航栏的高度
无法准确获得导航栏的高度

### 这个 API 长什么样？
如何准确获得屏幕内的安全区域高度的，以及导航栏的高度
无法准确获得导航栏的高度，就无法正确配置界面的高度

**Comment by ItsRyanWu** [comment]
建议使用 CSS 预渲染处理器里的变量去管理，在原生小程序中我使用了相关 API 去获取尺寸但是整个过程是异步的，而且可能会有获取的尺寸不准确的情况

**Comment by liuhuapiaoyuan** [comment]
> 建议使用 CSS 预渲染处理器里的变量去管理，在原生小程序中我使用了相关 API 去获取尺寸但是整个过程是异步的，而且可能会有获取的尺寸不准确的情况

具体怎么做？

**Comment by ZakaryCode** [comment]
/* Using the four safe area inset values with no fallback values */
env(safe-area-inset-top);
env(safe-area-inset-right);
env(safe-area-inset-bottom);
env(safe-area-inset-left);

/* Using them with fallback values */
env(safe-area-inset-top, 20px);
env(safe-area-inset-right, 1em);
env(safe-area-inset-bottom, 0.5vh);
env(safe-area-inset-left, 1.4rem);

https://developer.mozilla.org/en-US/docs/Web/CSS/env
