### ISSUE TITLE
引入第三方框架vant-ui 没报错，但是所有样式都没有

### ISSUE THREAD

**Issue by HZZformGD** [NervJS/taro#9332]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: Vue 2**

### 复现步骤
taro是3.2.8的，创建issue没有最新该版本所以选择了3.2.7。按照官方文档的操作，直接在config的copy写了一整个vant-weapp，在页面config中也写了路径，组件没办法显示，没有任何样式开发工具的wxml查看器中也只有 简单的van-button 标签没有shadow-root（已开启显示）
![image](https://user-images.githubusercontent.com/26340739/118425969-e9798080-b6fc-11eb-8030-9ae4ae29ec82.png)
![image](https://user-images.githubusercontent.com/26340739/118425984-f0a08e80-b6fc-11eb-9088-a07ef82bb5ee.png)
![image](https://user-images.githubusercontent.com/26340739/118425994-f8f8c980-b6fc-11eb-8533-4db50687edf5.png)
![image](https://user-images.githubusercontent.com/26340739/118426071-162d9800-b6fd-11eb-911d-952f2bb47fb6.png)

![image](https://user-images.githubusercontent.com/26340739/118425900-be8f2c80-b6fc-11eb-8361-2e2f1b83973d.png)

### 期望结果
正常使用

### 实际结果
没有样式没有任何节点的属性

### 环境信息
```
  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /var/folders/pd/79sys_rd3j50xt2cjf7wx_wr0000gn/T/yarn--1621219394724-0.6719151946548525/node
      Yarn: 1.22.10 - /var/folders/pd/79sys_rd3j50xt2cjf7wx_wr0000gn/T/yarn--1621219394724-0.6719151946548525/yarn
      npm: 6.14.10 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 

```

**Comment by HZZformGD** [comment]
找到解决的办法， 就是不要用pages当目录，自己创建一个例如homes，神奇的bug

**Comment by Chen-jj** [comment]
> 找到解决的办法， 就是不要用pages当目录，自己创建一个例如homes，神奇的bug

没懂什么意思

这是 Demo 项目，可以正常使用：https://github.com/NervJS/taro3-vant-sample
