### ISSUE TITLE
react 模板引擎 map 重复渲染

### ISSUE THREAD

**Issue by m17319325007** [NervJS/taro#9336]
### 相关平台
字节跳动小程序

### 复现仓库
[https://github.com/LSP-XA/project-bug/tree/taro-map-bug](https://github.com/LSP-XA/project-bug/tree/taro-map-bug)
**小程序基础库: 2.0.1.0**
**使用框架: React**

### 复现步骤
this.setState({}), 会导致map二次渲染

### 期望结果
不修改map数据不渲染

### 实际结果
每次修改setState 都会触发map渲染

### 环境信息
```
 Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
原生react没有发现

**Comment by Chen-jj** [comment]
@m17319325007 每次调用 `this.setState`，整个组件都会刷新没有问题吧，React 也是一样的，没懂错误在哪里。
