### ISSUE TITLE
支持运行单独把 Taro-H5 相关package 作 external 方式打包

### ISSUE THREAD

**Issue by cbingrui** [NervJS/taro#9338]
## 背景：
开发Taro 的组件库过程中，期望独立把 taro 相关的 js 运行时与组件代码用 `external` 方式独立打包，用作CDN引入。
经测试，react 的 external 方式打包与引入是正常的，但 taro 现在没成功
### webpack 配置：
```
const path = require("path");
const webpack = require("webpack");
const taroBaseReg = /@tarojs[\\/][a-z]+/;

module.exports = {
  entry: {
    reactVendor: path.join(__dirname, "src", "vendor.ts"),
    taroVendor: path.join(__dirname, "src", "taro.ts"),
  },

  plugins: [
    new webpack.DefinePlugin({
      "process.env": {
        TARO_ENV: JSON.stringify("h5"),
      },
    }),
  ],

  // devtool: "eval",
  // devtool: "source-map",
  mode: "development",
  resolve: {
    extensions: [".tsx", ".ts", ".js", ".jsx", ".json"],
  },
  output: {
    filename: "[name].dll.js",
    path: path.join(__dirname, "dist"),
    library: "[name]",
  },
};

```
### taro 的 h5 config配置：
```
chain.externals({
  "@davinci/components": "davinciComponents",
  react: "reactVendor.React",
  "react-dom": "reactVendor.ReactDOM",
  // "@tarojs/components": "taroVendor.components",
  "@tarojs/taro": "taroVendor",
});
```
但现在用 external 打包的方式，在 h5 运行时提示：Uncaught TypeError: Object(...) is not a function

发现下面的 createRouter 为空值
import { createRouter } from '@tarojs/taro'

如图：![image](https://user-images.githubusercontent.com/8628260/118577961-e5f9fe00-b7bd-11eb-873f-aff1b21c93da.png)

### 期望：

提供类似  `taro build --type h5:lib` 可以把 taro运行时与组件相关代码通过 external 独立打包。

或者麻烦告知 webpack 与 taro 工程配置应该如何配置？

**Comment by mixhowie** [comment]
此问题有解决方案吗，taro 的 webpack externals 应如何配置？

**Comment by wjkang** [comment]
2022了，能解决吗

**Comment by ZakaryCode** [comment]
> 但现在用 external 打包的方式，在 h5 运行时提示：Uncaught TypeError: Object(...) is not a function
> 
> 发现下面的 createRouter 为空值 import { createRouter } from '@tarojs/taro'

这个映射会在 3.5+ 移除，不过它并不会影响 externals 相关的配置

> 或者麻烦告知 webpack 与 taro 工程配置应该如何配置？

根据不同框架，第三方打包会有一定的差异，首先是需要参考对应框架插件提供的配置，以 react 为例可以参考插件内 [webpack.h5](https://github.com/NervJS/taro/blob/next/packages/taro-plugin-react/src/webpack.h5.ts#L7) 文件配置插件、别名、加载器、api-loader 等相关配置。
