### ISSUE TITLE
更改outputRoot后，还是生成了dist文件夹

### ISSUE THREAD

**Issue by shenck215** [NervJS/taro#934]
**问题描述**
在package.json注入环境变量，用于区分打包生成的分件，发现在整成生成outputRoot定义的文件夹外，仍然生成了dist文件夹，虽然里面没有任何文件。

**复现步骤**
[复现问题的步骤]
"scripts": {
    /** 此处省略 */   
    "build:weapp": "cross-env client=weapp taro build --type weapp",
    "build:h5": "cross-env client=h5 taro build --type h5",
    /** 此处省略 */   
},
const config = {
     /** 此处省略 */   
    outputRoot: `${process.env.client === 'weapp'?'wxdist':'h5dist'}`,
    /** 此处省略 */   
｝
分别执行 npm run build:weapp 和 npm run build:h5 命令，
成功生成打包后的文件夹 wxdist 和 h5dist，
这时，仍然生成了空的dist文件夹。

**期望行为**
成功生成期望的wxdist文件夹和h5dist文件夹外，不要生成多余的空的dist文件夹

**报错信息**
无报错

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v10.12.0]

**补充信息**
无

**Comment by zacksleo** [comment]
这个问题不大吧，你把 dist  加到 .gitignore 里面？

**Comment by ZevenFang** [comment]
不需要 cross-env ，直接这样就可以了
outputRoot: `dist/${process.env.TARO_ENV}`
