### ISSUE TITLE
autoPauseIfNavigate

### ISSUE THREAD

**Issue by yaodongyi** [NervJS/taro#9340]
### 这个特性解决了什么问题？
这个功能解决了微信支持的 ～（当跳转到本小程序的其他页面时，是否自动暂停本页面的视频播放）功能。
Taro声明文件 文档口口声声说支持，结果，源码并没有，`autoPauseIfNavigate`，`autoPauseIfOpenNative`，两个假属性，请知悉。

### 这个 API 长什么样？
期望，当然是期望正常输出啦，兄弟们～

**Comment by Chen-jj** [comment]
@yaodongyi 升级到最新版再试试，9个月前就支持了。

https://github.com/NervJS/taro/blob/88c7ea1aa022e7a84407b85d34ea35c377297409/packages/taro-weapp/src/components.ts#L144-L145

![image](https://user-images.githubusercontent.com/11807297/122370164-70867680-cf91-11eb-91a4-f0b2907ac9af.png)
