### ISSUE TITLE
MovableView绑定onChange事件时，其中嵌套的Picker的onChange事件会失效

### ISSUE THREAD

**Issue by a851928337** [NervJS/taro#9344]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/a851928337/taro-picker-issues](https://github.com/a851928337/taro-picker-issues)
**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
在绑定change事件的movable-view组件中，无法触发picker的change事件，具体可看仓库案例。

### 期望结果
在绑定了change事件的movable-view中可以触发picker的change事件

### 实际结果
在绑定change事件的movable-view组件中，无法触发picker的change事件

### 环境信息
```
👽 Taro v3.2.8


  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.4/bin/yarn
      npm: 7.12.1 - ~/.nvm/versions/node/v12.18.4/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
```

**Comment by a851928337** [comment]
在runtime.esm.js的第174行找到原因，这里做了
`if (!isParentBinded(node, type) || (type === 'touchmove' && !!node.props.catchMove))`的判断
其中的 `isParentBinded` 是基于啥考虑才会做这层判断的

**Comment by 583175694** [comment]
老哥有没有解决办法?

**Comment by ivan-94** [comment]
相关 issue https://github.com/NervJS/taro/issues/9316

**Comment by 583175694** [comment]
> 相关 issue #9316

基本上一样的问题，但是好像没有一个比较合适的解决方法
我现在遇到的问题是swiper中嵌套swiper，onChange事件都绑定到父组件上了

**Comment by ivan-94** [comment]
已提 PR https://github.com/NervJS/taro/pull/9355
