### ISSUE TITLE
强烈建议官方支持H5端的路由转场动画

### ISSUE THREAD

**Issue by crixusshen** [NervJS/taro#9348]
### 这个特性解决了什么问题？
虽然Taro的定位是解决小程序多平台统一的问题，但是绝大多数的业务功能使用Taro在app端仍然是使用h5来实现占非常大的权重，虽然官方也有RN方案，但是并不是所有的app都会采用这一方案，h5在app上的运用仍是主流且对于开发者而言，在app内的功能会相比小程序更为重视。而目前在体验上h5端的路由转场是没有动画转场效果的配置的，因此在h5端上的单页程序和平时我们自己浏览器上开发的程序体验相似，希望官方能增强路由，增强路由转场动画的实现

### 这个 API 长什么样？
在路由api上增加一个动画属性

**Comment by tourze** [comment]
+1

**Comment by reutopiaer** [comment]
+1

**Comment by soeasyjx** [comment]
+1

**Comment by 15380831711** [comment]
+1

**Comment by soeasyjx** [comment]
+1000000

**Comment by ZakaryCode** [comment]
[参考文档](https://nervjs.github.io/taro/docs/next/app-config#animation)
