### ISSUE TITLE
修改组件保存后监听编译总是警告：xx没有被引用到，不会被编译

### ISSUE THREAD

**Issue by wanxue0804** [NervJS/taro#935]
**复现步骤**
[复现问题的步骤]
创建了一个组件，在页面引用的好好的，然后去修改了一下组件的内容，保存就会提示警告
警告  JS文件    src/commponents/Modal/Index.tsx 没有被引用到，不会被编译

退出监听重新编译又正常了 修改也会生效

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v8.11.3]
- npm版本 [ v6.4.1 ]
 - 报错平台 [ weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by zacksleo** [comment]
退出taro, 重新启动一下

**Comment by drawing-snail** [comment]
> 退出taro, 重新启动一下

不可能每次修改了东西都重新启动一下吧，好麻烦，用wepy的时候没遇到过这种问题

**Comment by luckyadam** [comment]
你的 Taro 版本太旧了

**Comment by drawing-snail** [comment]
> 你的 Taro 版本太旧了

现在taro版本是什么，我好像在官方文档上没找到版本号，我现在用的1.0.0-beta.21

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/47618043-5ca05480-db09-11e8-9b0c-fba1afd80051.png)

**Comment by drawing-snail** [comment]
ok

**Comment by xiao0502** [comment]
@luckyadam 我就是用的👽 Taro v1.1.0-beta.13，还是会出现这样的问题，组件内除了js文件的其他文件修改是可以实时编译，就js文件不行

**Comment by drawing-snail** [comment]
抱歉，这个问题我要重新打开，更新了还是不行，还是提示组件 "没有被引用到，不会被编译"，这样我每次修改东西还得重新编译一下，好麻烦

**Comment by luckyadam** [comment]
@drawing-snail 
首先确定 cli 已经升级到 `1.1.0-beta.13` ，然后你看看项目依赖里有没有依赖旧版本的 cli，有的话去掉，然后重新安装依赖，只使用全局的 cli
可以的话，提供一个可以复现的项目~

**Comment by luckyadam** [comment]
@nyrf  应该是编译时对原生组件支持不够好，我再看下

**Comment by mrtian2016** [comment]
我也遇到这个问题 taro版本是Taro v1.3.0-beta.3

**Comment by Retroxs** [comment]
ts 项目必现， 编译正常没有报错，只要编译出错就会一直报， 重新编译下🈶️不报  Taro v1.3.5
![1562223957481](https://user-images.githubusercontent.com/19631307/60646181-44898d80-9e6d-11e9-8409-a86c1d87db17.jpg)

**Comment by sfwu** [comment]
我时常遇到报 .js 没有被引用到 未被编译的问题。不过重启之后一段时间内就没问题

**Comment by fantacytyx** [comment]
@shenghanqin 这问题怎么解决？

**Comment by shenghanqin** [comment]
你现在用最新版本还有有这个问题吗？

我平时用的是js而非ts版，一直没出现过类似的问题。
