### ISSUE TITLE
引入"html2Canvas"后, taro3报错

### ISSUE THREAD

**Issue by darkfiredarkhalo** [NervJS/taro#9351]
### 相关平台
H5

**浏览器版本: chrome**
**使用框架: React**

### 复现步骤
`yarn add html2canvas`, 然后使用`html2canvas`生成canvas  
```
html2canvas(document.querySelector("#shareView"), {
        allowTaint: false,
        useCORS: true,
        scrollY: 0,
        scale: 2
      })
        .then(res => {
          console.log("html转canvas>>>", res);
          canvas2image.saveAsImage(res, 2000, 3000, "png", "demo");
        })
        .catch(e => {
          console.error("html转canvas出错>>>", e);
        });
```   
`html2canvas`可以正常工作, 但是taro报错如下:  
``` 
index-310de3d5.js?893b:1549 TypeError: Cannot read property 'list' of undefined
    at new Tabbar (taro-tabbar.entry.js?b691:279)
    at initializeComponent (index-310de3d5.js?893b:1322)
    at connectedCallback (index-310de3d5.js?893b:1407)
    at eval (index-310de3d5.js?893b:1493)
    at Object.jmp (index-310de3d5.js?893b:15)
    at HTMLElement.connectedCallback (index-310de3d5.js?893b:1493)
    at DocumentCloner.toIFrame (html2canvas.js?c0e9:5095)
    at eval (html2canvas.js?c0e9:6995)
    at step (html2canvas.js?c0e9:83)
    at Object.eval [as next] (html2canvas.js?c0e9:64) undefined
consoleError @ index-310de3d5.js?893b:1549
initializeComponent @ index-310de3d5.js?893b:1325
connectedCallback @ index-310de3d5.js?893b:1407
eval @ index-310de3d5.js?893b:1493
jmp @ index-310de3d5.js?893b:15
connectedCallback @ index-310de3d5.js?893b:1493
DocumentCloner.toIFrame @ html2canvas.js?c0e9:5095
eval @ html2canvas.js?c0e9:6995
step @ html2canvas.js?c0e9:83
eval @ html2canvas.js?c0e9:64
eval @ html2canvas.js?c0e9:57
__awaiter @ html2canvas.js?c0e9:53
renderElement @ html2canvas.js?c0e9:6941
html2canvas @ html2canvas.js?c0e9:6936
onShareClick @ index.tsx?ef4c:38
index-310de3d5.js?893b:1549 TypeError: Cannot read property 'borderStyle' of undefined
    at Tabbar.render (taro-tabbar.entry.js?b691:346)
    at callRender (index-310de3d5.js?893b:1068)
    at updateComponent (index-310de3d5.js?893b:1042)
    at eval (index-310de3d5.js?893b:1029)
    at then (index-310de3d5.js?893b:1162)
    at dispatchHooks (index-310de3d5.js?893b:1029)
    at Array.dispatch (index-310de3d5.js?893b:1004)
    at consume (index-310de3d5.js?893b:1588)
    at flush (index-310de3d5.js?893b:1603) <taro-tabbar class=​"taro-tabbar__tabbar taro-tabbar__tabbar-bottom taro-tabbar__tabbar-hide hydrated">​…​</taro-tabbar>​
consoleError @ index-310de3d5.js?893b:1549
callRender @ index-310de3d5.js?893b:1087
updateComponent @ index-310de3d5.js?893b:1042
eval @ index-310de3d5.js?893b:1029
then @ index-310de3d5.js?893b:1162
dispatchHooks @ index-310de3d5.js?893b:1029
dispatch @ index-310de3d5.js?893b:1004
consume @ index-310de3d5.js?893b:1588
flush @ index-310de3d5.js?893b:1603
requestAnimationFrame (async)
raf @ index-310de3d5.js?893b:16
eval @ index-310de3d5.js?893b:1581
scheduleUpdate @ index-310de3d5.js?893b:1005
schedule @ index-310de3d5.js?893b:1348
initializeComponent @ index-310de3d5.js?893b:1359
connectedCallback @ index-310de3d5.js?893b:1407
eval @ index-310de3d5.js?893b:1493
jmp @ index-310de3d5.js?893b:15
connectedCallback @ index-310de3d5.js?893b:1493
DocumentCloner.toIFrame @ html2canvas.js?c0e9:5095
eval @ html2canvas.js?c0e9:6995
step @ html2canvas.js?c0e9:83
eval @ html2canvas.js?c0e9:64
eval @ html2canvas.js?c0e9:57
__awaiter @ html2canvas.js?c0e9:53
renderElement @ html2canvas.js?c0e9:6941
html2canvas @ html2canvas.js?c0e9:6936
onShareClick @ index.tsx?ef4c:38
index-310de3d5.js?893b:1549 TypeError: Cannot read property 'mode' of undefined
    at Tabbar.getCurrentUrl (taro-tabbar.entry.js?b691:298)
    at Tabbar.routerChangeHandler (taro-tabbar.entry.js?b691:207)
    at Tabbar.componentDidLoad (taro-tabbar.entry.js?b691:337)
    at safeCall (index-310de3d5.js?893b:1153)
    at postUpdateComponent (index-310de3d5.js?893b:1107)
    at postUpdate (index-310de3d5.js?893b:1055)
    at updateComponent (index-310de3d5.js?893b:1057)
    at eval (index-310de3d5.js?893b:1029)
    at then (index-310de3d5.js?893b:1162)
    at dispatchHooks (index-310de3d5.js?893b:1029) undefined
consoleError @ index-310de3d5.js?893b:1549
safeCall @ index-310de3d5.js?893b:1156
postUpdateComponent @ index-310de3d5.js?893b:1107
postUpdate @ index-310de3d5.js?893b:1055
updateComponent @ index-310de3d5.js?893b:1057
eval @ index-310de3d5.js?893b:1029
then @ index-310de3d5.js?893b:1162
dispatchHooks @ index-310de3d5.js?893b:1029
dispatch @ index-310de3d5.js?893b:1004
consume @ index-310de3d5.js?893b:1588
flush @ index-310de3d5.js?893b:1603
requestAnimationFrame (async)
raf @ index-310de3d5.js?893b:16
eval @ index-310de3d5.js?893b:1581
scheduleUpdate @ index-310de3d5.js?893b:1005
schedule @ index-310de3d5.js?893b:1348
initializeComponent @ index-310de3d5.js?893b:1359
connectedCallback @ index-310de3d5.js?893b:1407
eval @ index-310de3d5.js?893b:1493
jmp @ index-310de3d5.js?893b:15
connectedCallback @ index-310de3d5.js?893b:1493
DocumentCloner.toIFrame @ html2canvas.js?c0e9:5095
eval @ html2canvas.js?c0e9:6995
step @ html2canvas.js?c0e9:83
eval @ html2canvas.js?c0e9:64
eval @ html2canvas.js?c0e9:57
__awaiter @ html2canvas.js?c0e9:53
renderElement @ html2canvas.js?c0e9:6941
html2canvas @ html2canvas.js?c0e9:6936
onShareClick @ index.tsx?ef4c:38
index-310de3d5.js?893b:1549 TypeError: Cannot read property '0' of undefined
    at Swiper.updateSize (taro-swiper-core_2.entry.js?3bb8:1292)
    at Swiper.update (taro-swiper-core_2.entry.js?3bb8:3900)
    at Swiper$1.componentWillUpdate (taro-swiper-core_2.entry.js?3bb8:8065)
    at safeCall (index-310de3d5.js?893b:1153)
    at dispatchHooks (index-310de3d5.js?893b:1025)
    at Array.dispatch (index-310de3d5.js?893b:1004)
    at consume (index-310de3d5.js?893b:1588)
    at flush (index-310de3d5.js?893b:1603) undefined  
```  

### 期望结果
正常使用`html2canvas`

### 实际结果
不能正常使用`html2canvas`

### 环境信息
```
 Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.6.3 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

**Comment by darkfiredarkhalo** [comment]
### 补充信息     
当前页面并非`tabbar`页面, 也不包含`swiper`  
  
报错信息截图如下:  
<img width="924" alt="截屏2021-05-19 14 31 55" src="https://user-images.githubusercontent.com/13959162/118766468-0a81d300-b8af-11eb-9c59-1c84c8b32cca.png">

**Comment by Allen7D** [comment]
` html2canvas(ele,{
              ...
              ignoreElements:(_ele=>{
                if(_ele.className.indexOf('taro-tabbar__tabbar') > -1 ||_ele.className.indexOf('taro-tabbar__tabbar') > -1 || _ele.className.indexOf('swiper') > -1) return true
                return false
              })
            })`

增加ignoreElements

**Comment by ZakaryCode** [comment]
> `html2canvas`可以正常工作, 但是taro报错如下:
> 
> ```
> index-310de3d5.js?893b:1549 TypeError: Cannot read property 'list' of undefined
>     at new Tabbar (taro-tabbar.entry.js?b691:279)
>     at initializeComponent (index-310de3d5.js?893b:1322)
>     at connectedCallback (index-310de3d5.js?893b:1407)
>     at eval (index-310de3d5.js?893b:1493)
>     at Object.jmp (index-310de3d5.js?893b:15)
>     at HTMLElement.connectedCallback (index-310de3d5.js?893b:1493)
>     at DocumentCloner.toIFrame (html2canvas.js?c0e9:5095)
>     at eval (html2canvas.js?c0e9:6995)
>     at step (html2canvas.js?c0e9:83)
>     at Object.eval [as next] (html2canvas.js?c0e9:64) undefined
> consoleError @ index-310de3d5.js?893b:1549
> initializeComponent @ index-310de3d5.js?893b:1325
> connectedCallback @ index-310de3d5.js?893b:1407
> eval @ index-310de3d5.js?893b:1493
> jmp @ index-310de3d5.js?893b:15
> connectedCallback @ index-310de3d5.js?893b:1493
> DocumentCloner.toIFrame @ html2canvas.js?c0e9:5095
> eval @ html2canvas.js?c0e9:6995
> step @ html2canvas.js?c0e9:83
> eval @ html2canvas.js?c0e9:64
> eval @ html2canvas.js?c0e9:57
> __awaiter @ html2canvas.js?c0e9:53
> renderElement @ html2canvas.js?c0e9:6941
> html2canvas @ html2canvas.js?c0e9:6936
> onShareClick @ index.tsx?ef4c:38
> index-310de3d5.js?893b:1549 TypeError: Cannot read property 'borderStyle' of undefined
>     at Tabbar.render (taro-tabbar.entry.js?b691:346)
>     at callRender (index-310de3d5.js?893b:1068)
>     at updateComponent (index-310de3d5.js?893b:1042)
>     at eval (index-310de3d5.js?893b:1029)
>     at then (index-310de3d5.js?893b:1162)
>     at dispatchHooks (index-310de3d5.js?893b:1029)
>     at Array.dispatch (index-310de3d5.js?893b:1004)
>     at consume (index-310de3d5.js?893b:1588)
>     at flush (index-310de3d5.js?893b:1603) <taro-tabbar class=​"taro-tabbar__tabbar taro-tabbar__tabbar-bottom taro-tabbar__tabbar-hide hydrated">​…​</taro-tabbar>​
> consoleError @ index-310de3d5.js?893b:1549
> callRender @ index-310de3d5.js?893b:1087
> updateComponent @ index-310de3d5.js?893b:1042
> eval @ index-310de3d5.js?893b:1029
> then @ index-310de3d5.js?893b:1162
> dispatchHooks @ index-310de3d5.js?893b:1029
> dispatch @ index-310de3d5.js?893b:1004
> consume @ index-310de3d5.js?893b:1588
> flush @ index-310de3d5.js?893b:1603
> requestAnimationFrame (async)
> raf @ index-310de3d5.js?893b:16
> eval @ index-310de3d5.js?893b:1581
> scheduleUpdate @ index-310de3d5.js?893b:1005
> schedule @ index-310de3d5.js?893b:1348
> initializeComponent @ index-310de3d5.js?893b:1359
> connectedCallback @ index-310de3d5.js?893b:1407
> eval @ index-310de3d5.js?893b:1493
> jmp @ index-310de3d5.js?893b:15
> connectedCallback @ index-310de3d5.js?893b:1493
> DocumentCloner.toIFrame @ html2canvas.js?c0e9:5095
> eval @ html2canvas.js?c0e9:6995
> step @ html2canvas.js?c0e9:83
> eval @ html2canvas.js?c0e9:64
> eval @ html2canvas.js?c0e9:57
> __awaiter @ html2canvas.js?c0e9:53
> renderElement @ html2canvas.js?c0e9:6941
> html2canvas @ html2canvas.js?c0e9:6936
> onShareClick @ index.tsx?ef4c:38
> index-310de3d5.js?893b:1549 TypeError: Cannot read property 'mode' of undefined
>     at Tabbar.getCurrentUrl (taro-tabbar.entry.js?b691:298)
>     at Tabbar.routerChangeHandler (taro-tabbar.entry.js?b691:207)
>     at Tabbar.componentDidLoad (taro-tabbar.entry.js?b691:337)
>     at safeCall (index-310de3d5.js?893b:1153)
>     at postUpdateComponent (index-310de3d5.js?893b:1107)
>     at postUpdate (index-310de3d5.js?893b:1055)
>     at updateComponent (index-310de3d5.js?893b:1057)
>     at eval (index-310de3d5.js?893b:1029)
>     at then (index-310de3d5.js?893b:1162)
>     at dispatchHooks (index-310de3d5.js?893b:1029) undefined
> consoleError @ index-310de3d5.js?893b:1549
> safeCall @ index-310de3d5.js?893b:1156
> postUpdateComponent @ index-310de3d5.js?893b:1107
> postUpdate @ index-310de3d5.js?893b:1055
> updateComponent @ index-310de3d5.js?893b:1057
> eval @ index-310de3d5.js?893b:1029
> then @ index-310de3d5.js?893b:1162
> dispatchHooks @ index-310de3d5.js?893b:1029
> dispatch @ index-310de3d5.js?893b:1004
> consume @ index-310de3d5.js?893b:1588
> flush @ index-310de3d5.js?893b:1603
> requestAnimationFrame (async)
> raf @ index-310de3d5.js?893b:16
> eval @ index-310de3d5.js?893b:1581
> scheduleUpdate @ index-310de3d5.js?893b:1005
> schedule @ index-310de3d5.js?893b:1348
> initializeComponent @ index-310de3d5.js?893b:1359
> connectedCallback @ index-310de3d5.js?893b:1407
> eval @ index-310de3d5.js?893b:1493
> jmp @ index-310de3d5.js?893b:15
> connectedCallback @ index-310de3d5.js?893b:1493
> DocumentCloner.toIFrame @ html2canvas.js?c0e9:5095
> eval @ html2canvas.js?c0e9:6995
> step @ html2canvas.js?c0e9:83
> eval @ html2canvas.js?c0e9:64
> eval @ html2canvas.js?c0e9:57
> __awaiter @ html2canvas.js?c0e9:53
> renderElement @ html2canvas.js?c0e9:6941
> html2canvas @ html2canvas.js?c0e9:6936
> onShareClick @ index.tsx?ef4c:38
> index-310de3d5.js?893b:1549 TypeError: Cannot read property '0' of undefined
>     at Swiper.updateSize (taro-swiper-core_2.entry.js?3bb8:1292)
>     at Swiper.update (taro-swiper-core_2.entry.js?3bb8:3900)
>     at Swiper$1.componentWillUpdate (taro-swiper-core_2.entry.js?3bb8:8065)
>     at safeCall (index-310de3d5.js?893b:1153)
>     at dispatchHooks (index-310de3d5.js?893b:1025)
>     at Array.dispatch (index-310de3d5.js?893b:1004)
>     at consume (index-310de3d5.js?893b:1588)
>     at flush (index-310de3d5.js?893b:1603) undefined  
> ```

最新版本已无该问题
