### ISSUE TITLE
npm run build:h5打包,没有把dist中的项目清空

### ISSUE THREAD

**Issue by likeDoMine** [NervJS/taro#936]
1.  先打包小程序，
2.  执行h5打包
结论： 发现没有将小程序打包后的内容删除。 （你们让我提的issue）

**Comment by zacksleo** [comment]
手动清除

**Comment by js-newbee** [comment]
同问，打包小程序的时候也没有清空，如果发布的时候忘记了，会导致打包后比较大，甚至可能超过2m的限制

不清空是有什么考量么？

**Comment by luckyadam** [comment]
@js-newbee 打包小程序已经清楚上一次的文件了

**Comment by js-newbee** [comment]
> @js-newbee 打包小程序已经清除上一次的文件了

嗯，打包有清空，搞错了... 是打包 H5 没有清除
