### ISSUE TITLE
Taro 3.2.8仍不支持compressVideo

### ISSUE THREAD

**Issue by chen-yu1** [NervJS/taro#9362]
### 这个特性解决了什么问题？
视频压缩

### 这个 API 长什么样？
https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.compressVideo.html

之前已有issue：https://github.com/NervJS/taro/issues/8985
回复在3.1.x已支持
然而在3.2.8版本中使用Taro.compressVideo，仍然报错：
![image](https://user-images.githubusercontent.com/83993251/118952213-55bee300-b98e-11eb-8a83-8b12457ecf4f.png)

**Comment by luckyadam** [comment]
支持的

**Comment by chen-yu1** [comment]
抱歉 是我项目中基础库版本太低了 升级了之后可以用了。
