### ISSUE TITLE
Taro 3.1.5 Taro3.2.8 版本 打包后  安卓6.0系统浏览器白屏 报错Uncaught SyntaxError: 'super' keyword unexpected here

### ISSUE THREAD

**Issue by WangChenS117** [NervJS/taro#9363]
### 相关平台
H5

**浏览器版本: chrome 68.0.3440.70**
**使用框架: React**

### 复现步骤
在安卓6.0原生 webview 上访问  build:h5打包后的工程  工程添加polyfill垫片也无效  使用mumu模拟器可以轻松复现

### 期望结果
安卓6.0 手机浏览器展示正常

### 实际结果
安卓6.0手机白屏

### 环境信息
```
 Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      nerv-devtools: 1.5.6 => 1.5.6 
      nervjs: 1.5.6 => 1.5.6 
      react: ^16.10.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.10 => 3.0.0-alpha.10 
    npmGlobalPackages:
      typescript: 3.9.6

```

**Comment by WangChenS117** [comment]
报错的代码段在Taro 源码工程中有找到  Taro/taro-next/packages/taro-components/node_modules/@stencil/core/internal/hydrate/index.js  文件的第901行 出现了super关键字   并且打包后只出现在app.js中 导致页面白屏

**Comment by WangChenS117** [comment]
奇怪的是 dev:h5 没有问题   build:h5 后就出现问题

**Comment by WangChenS117** [comment]
更奇怪的是 window系统打包没问题  只有mac系统打包才会出现问题

**Comment by GZWZC** [comment]
+1

**Comment by Chen-jj** [comment]
@WangChenS117 @GZWZC 可以升级后再试试，看看是不是同一个问题https://github.com/NervJS/taro/issues/8648#issuecomment-851948343

**Comment by GZWZC** [comment]
@Chen-jj 升级到3.2.10后。不会报错```Uncaught SyntaxError: 'super' keyword unexpected here```的错误了。

但是会报```Uncaught TypeError: Cannot read property 'designWidth' of undefined```的错误。如下图

![image](https://user-images.githubusercontent.com/16217142/120500976-d0a6e580-c3f3-11eb-83d5-5abcf3ef6c09.png)

v3.2.10里的node_modules/@tarojs/taro-h5/src/taro/index.js有问题

```
const pxTransform = function (size) {
  const { designWidth } = taro.config
  return Math.ceil((((parseInt(size, 10) / 40) * 640) / designWidth) * 10000) / 10000 + 'rem'
}
```

**Comment by lihuaying** [comment]
我使用的3.3.0 的版本, 运行的项目在android 6.0版本的模拟上也是白屏状态; index.html 中也加了polyfill 但是还是白屏

**Comment by lihuaying** [comment]
@Chen-jj 你的问题解决了?
