### ISSUE TITLE
defineConstants中变量在app.config.ts文件中pages属性中使用，编译报错

### ISSUE THREAD

**Issue by Mrchangchang** [NervJS/taro#9366]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Mrchangchang/taro-demo.git](https://github.com/Mrchangchang/taro-demo.git)
**小程序基础库: 2.17.0**
**使用框架: Vue 3**

### 复现步骤
yarn install && yarn build:weapp
结果：编译报错

### 期望结果
编译通过

### 实际结果
编译报错

### 环境信息
```
� Taro v3.2.7

{
  projectName: 'visa-application',
  date: '2021-5-20',
  designWidth: 750,
  deviceRatio: { '640': 1.17, '750': 1, '828': 0.905 },
  sourceRoot: 'src',
  outputRoot: 'dist',
  plugins: [],
  defineConstants: { APP_CHECKOUT: '"pages/checkout/index"' },
  copy: { patterns: [], options: {} },
  framework: 'vue3',
  mini: {
    postcss: { pxtransform: [Object], url: [Object], cssModules: [Object] }
  },
  h5: {
    publicPath: '/',
    staticDirectory: 'static',
    postcss: { autoprefixer: [Object], cssModules: [Object] }
  },
  env: { NODE_ENV: '"production"' }
}

  Taro CLI 3.2.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - D:\nodeJs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\nodeJs\npm.CMD
```

---
### 补充信息
在app.config.ts文件的pages中使用编译报错，但是在组件的生命周期函数中使用，可以编译成功

**Comment by Mrchangchang** [comment]
![image](https://user-images.githubusercontent.com/25929184/119094248-5f565280-ba43-11eb-9d7b-2f5cb0220e31.png)

![image](https://user-images.githubusercontent.com/25929184/119094075-1f8f6b00-ba43-11eb-80a4-70344aad5ca0.png)
// 编译报错
![image](https://user-images.githubusercontent.com/25929184/119094135-333ad180-ba43-11eb-9aac-568e7e0ea921.png)
// 编译通过，运行小程序控制台打印"pages/checkout/index"

**Comment by Mrchangchang** [comment]
暂时用向global对象中增加属性，解决，编译通过
![image](https://user-images.githubusercontent.com/25929184/119097353-32a43a00-ba47-11eb-80aa-5661e6b3ee82.png)

**Comment by Chen-jj** [comment]
@Mrchangchang app 和 page 的配置文件是使用 `babel-register` 加载的，不经 webpack 处理。可以通过挂载属性到 `process.env` 解决。

**Comment by Mrchangchang** [comment]
我当前的做法是把挂载到global，这样和经过webpackwen处理的文件写法保持，哪一种实现的方法更好一点呢？ @Chen-jj

**Comment by Chen-jj** [comment]
> 我当前的做法是把挂载到global，这样和经过webpackwen处理的文件写法保持，哪一种实现的方法更好一点呢？ @Chen-jj

区别不大，根据具体情况按灵活性选择咯，不造成冲突和副作用就行

**Comment by SimbaOvO** [comment]
可以试试我写的[Taro Plugin](https://github.com/SimbaOvO/taro-plugin-auto-declare-define-constants)来自动生成`defineConstants`中的变量声明～
