### ISSUE TITLE
vue模板渲染会生成多余的""

### ISSUE THREAD

**Issue by jiangxd2016** [NervJS/taro#9369]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/jiangxd2016/taro-demo](https://github.com/jiangxd2016/taro-demo)
**小程序基础库: 2.7.10**
**使用框架: Vue 2**

### 复现步骤

-  编译，生成小程序文件
-  生成的vue render 如下
```var render = function () {
          var _vm = this
          var _h = _vm.$createElement
          var _c = _vm._self._c || _h
          return _c("view", {
            staticClass: "index"
          }, [
            _vm.num === 1 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e(),
            _vm.num === 2 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e(),
            _vm.num === 3 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e(),
            _vm.num === 4 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e(),
            _vm.num === 5 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e(),
            _vm.num === 6 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e(),
            _vm.num === 7 ? _c("text", [_vm._v(_vm._s(_vm.msg))]) : _vm._e()
          ])
        }
```
- 生成的小程序代码如下
``` <view class="index" id="_n_10">
    <text id="_n_11">Hello Word!</text>
    ""
    ""
    ""
    ""
    ""
    ""
  </view>
```

### 期望结果
无多余的 ""

### 实际结果
多渲染了6个 ""

### 环境信息

👽 Taro v3.2.8

  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.11.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.6.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
    npmGlobalPackages:
      typescript: 4.2.4

---
### 补充信息
代码截图在image文件夹

**Comment by jiangxd2016** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@jiangxd2016 Vue `v-if` 会生成一下 `comments` 节点：https://github.com/vuejs/vue/issues/5117#issuecomment-284927949。这些 `comments` 节点不应该渲染到小程序渲染层，我们改一下。

**Comment by ccqgithub** [comment]
@Chen-jj chen 这个修复了么，貌似 3.4.8 vue3 问题还存在

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1654761/166092264-a3fc809b-09e3-47b0-8033-eb81d3d49e2a.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/1654761/166092282-bcbfccc2-7115-4ce8-865b-92ad73dc50ca.png">

**Comment by ccqgithub** [comment]
> @Chen-jj chen 这个修复了么，貌似 3.4.8 vue3 问题还存在: 好像是`slot`的前后都会多渲染一个空的text节点
> 
> <img alt="image" width="502" src="https://user-images.githubusercontent.com/1654761/166092264-a3fc809b-09e3-47b0-8033-eb81d3d49e2a.png">
> 
> <img alt="image" width="888" src="https://user-images.githubusercontent.com/1654761/166092282-bcbfccc2-7115-4ce8-865b-92ad73dc50ca.png">

好像没什么毛病，vue用空的text节点代表fragment，只是浏览器不这样显示，开发者工具这样显示～～
