### ISSUE TITLE
dispaly: flex     无法设置宽度     flex: 1   不生效   flex-wrap: wrap;  也不会换行

### ISSUE THREAD

**Issue by 13734010529** [NervJS/taro#9371]
### 相关平台
百度小程序

**小程序基础库: 3.290.33**
**使用框架: React**

### 复现步骤
父级  display：flex    子级 设置宽度无法生效    flex：1  也不生效      flex-wrap: wrap;  也不会换行

### 期望结果
样式最起码得适配吧

### 实际结果
flex  失效  文档也没有备注

### 环境信息
```

  Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - E:\node\node.EXE
      npm: 6.14.4 - E:\node\npm.CMD
```

**Comment by ivan-94** [comment]
重复issue， https://github.com/NervJS/taro/issues/6015

这个问题现在无解，只能等百度官方修复了

**Comment by 13734010529** [comment]
> 重复issue，[＃6015](https://github.com/NervJS/taro/issues/6015)
> 
> 这个问题现在无解，只能等百度官方修复了

**Comment by 13734010529** [comment]
> 重复issue，[＃6015](https://github.com/NervJS/taro/issues/6015)
> 
> 这个问题现在无解，只能等百度官方修复了

好像不是百度官方修复吧，别的框架打包后 百度编辑器能正常显示，taro 打包 flex 的就乱了

**Comment by ivan-94** [comment]
> > 重复issue，[＃6015](https://github.com/NervJS/taro/issues/6015)
> 
> > 
> 
> > 这个问题现在无解，只能等百度官方修复了
> 
> 
> 
> 好像不是百度官方修复吧，别的框架打包后 百度编辑器能正常显示，taro 打包 flex 的就乱了

taro 3.x 依赖于 template 来动态渲染。但是template 在 百度小程序中是一个实实在在的 dom 节点。所以阻断了 flex样式的适配。
你用2.x 直译模式就很少概率会遇到这个问题

**Comment by zephyr-66** [comment]
> > > 重复issue，[＃6015](https://github.com/NervJS/taro/issues/6015)
> > 
> > 
> > > 
> > 
> > 
> > > 这个问题现在无解，只能等百度官方修复了
> > 
> > 
> > 好像不是百度官方修复吧，别的框架打包后 百度编辑器能正常显示，taro 打包 flex 的就乱了
> 
> taro 3.x 依赖于 template 来动态渲染。但是template 在 百度小程序中是一个实实在在的 dom 节点。所以阻断了 flex样式的适配。
> 你用2.x 直译模式就很少概率会遇到这个问题

他们愿意解决吗？开发起来  太苦了

**Comment by zephyr-66** [comment]
@13734010529 兄弟 你用float解决了吗

**Comment by zephyr-66** [comment]
这样Taro-ui也不能跨端了

**Comment by Chen-jj** [comment]
Duplicate of #6015 

我们也不断地和百度官方沟通的，无奈进展缓慢。。
