### ISSUE TITLE
setState 中使用 [`account.${e.currentTarget.id}`]: e.currentTarget.value 得不到想要的结果

### ISSUE THREAD

**Issue by xyxc0673** [NervJS/taro#938]
**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
我在一个登录页面中有 几个 Input，然后我把 onInput 都绑定到下面这个函数上了

```js
onInput(e) {
  this.setState({
    [`account.${e.currentTarget.id}`]: e.currentTarget.value
  })
}
```

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
我希望这个函数把 state 中的 state 修改为
```js
state {
  account: {
    id: 'test',
    pwd: 'test123',
  }
}
```
这样子，结果 state 却是
```js
state {
  account.id: 'test',
  account.pw: 'test123'
}
```

我之前在原生小程序中写过这样的表达式，不过对 js (用了 typescript) 这块不是很熟悉，不太能定位到问题的所在，也不知道这个是不是新特性。。。

**报错信息**

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.7
 - Node.js 版本 v9.11.2
 - 报错平台 weapp

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
这里的 setState 用法和 React 一致，和小程序的 setData 不一样，希望能阅读一下相关文档

**Comment by xyxc0673** [comment]
> 这里的 setState 用法和 React 一致，和小程序的 setData 不一样，希望能阅读一下相关文档

最后用了 object.assign() 来更新，之前不太清楚 setState 和 setData 的异同，不过主要还是对 js 不太了解，不好意思。
