### ISSUE TITLE
企业微信Taro.request在Taro对象内找不到 

### ISSUE THREAD

**Issue by Junzibuzhengyibuqi** [NervJS/taro#9387]
### 相关平台
微信小程序

**小程序基础库: 2.10.4**
**使用框架: React**

### 复现步骤
直接打印Taro， Taro.request, Taro.addInterceptor即可

### 期望结果
正常使用 

### 实际结果
Taro.request, Taro.addInterceptor  均不存在  为undefined

### 环境信息
```
Taro v3.0.5


  Taro CLI 3.0.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
想问下对于企业微信的兼容性的程度

**Comment by Chen-jj** [comment]
@Junzibuzhengyibuqi Taro 3.1 才开始支持

![image](https://user-images.githubusercontent.com/11807297/120418492-3747e700-c393-11eb-8ea4-94353891a248.png)
