### ISSUE TITLE
taro.component.d.ts内declare namespace Taro导致Typescript依赖异常

### ISSUE THREAD

**Issue by biluochun** [NervJS/taro#9393]
### 相关平台
支付宝小程序

**浏览器版本: Chrome 62****小程序基础库: 2.0**
**使用框架: React**

### 复现步骤
因为 `taro.component.d.ts: declare namespace Taro` 在项目内使用 `Taro.getExtConfigSync()` 等相关 api 时 `Taro` 变量被视为全局变量使用，无需导入 `import Taro from '@tarojs/taro';` 但是编译成支付宝小程序时运行报错 `Taro` 变量不存在。
在添加`import Taro from '@tarojs/taro';` 后正常运行。

### 期望结果
`Taro` 变量需引入`import Taro from '@tarojs/taro';`后才能使用。

### 实际结果
项目内直接使用`Taro.getExtConfigSync()`没报错

### 环境信息
```
  Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by CuiHaiPeng** [comment]
我也是存在这个问题，请问一下 您那边找到解决方案了吗？

**Comment by Chen-jj** [comment]
duplicate #10381
