### ISSUE TITLE
tabbar的切换明显感觉到迟滞，不知道是什么原因造成？

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [NervJS/taro#9395]
### 相关平台
H5

**浏览器版本: 红米9A**
**使用框架: React**

### 复现步骤
明显感觉tabbar的切换有点迟滞，另外所有的按钮点击后的跳转也有一些明显的迟滞。不管怎么优化都还是有点问题，不能很丝滑的切换，但是在IOS端就明显好很多，但也还是有点问题，我用rn react natvigation直接创建的tabbar项目明显快很多

### 期望结果
给一些优化建议或者方法

### 实际结果
切换缓慢

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.23.0-20200615.1913 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
是RN还是 H5？

**Comment by liuhuapiaoyuan** [comment]
> 是RN还是 H5？

晕倒 是RN，选错了平台 sorry

**Comment by liuhuapiaoyuan** [comment]
> 是RN还是 H5？

主要是初次渲染的时候有点慢，后面就很正常了@ @zhiqingchen

**Comment by liuhuapiaoyuan** [comment]
@yechunxi 
我看router中引入了，react-native-screen，但是却没有使用，而且引入的是2.0+的版本，为什么不适用react-native-screen呢？或者提供一个方式让用户可定义？。我通过魔改支持了react-native-screen，但是性能确并没有提升太多，这是为什么

**Comment by liuhuapiaoyuan** [comment]
@zhiqingchen 我直接魔改了源码，增加了lazy:false，我建议增加一个配置，比如tabbarLazy，又或者干脆默认false，至于是否lazy 我们开发者自己在tabbar的page中去定义

**Comment by tourze** [comment]
我感觉是有少少，但是不明显

**Comment by zhiqingchen** [comment]
> @zhiqingchen 我直接魔改了源码，增加了lazy:false，我建议增加一个配置，比如tabbarLazy，又或者干脆默认false，至于是否lazy 我们开发者自己在tabbar的page中去定义

加了lazy后效果怎么样

**Comment by liuhuapiaoyuan** [comment]
> > @zhiqingchen 我直接魔改了源码，增加了lazy:false，我建议增加一个配置，比如tabbarLazy，又或者干脆默认false，至于是否lazy 我们开发者自己在tabbar的page中去定义
> 
> 加了lazy后效果怎么样

增加了首屏时间，但是效果好多了，因为是否懒加载我们可以自己控制，比如一个每个tab中开发者可以决定哪些部分是lazy的，而不是全盘lazy

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-react-native/pull/148/commits/e27b8f904a1772a786a78634bc090d7436ba6f64

**Comment by liuhuapiaoyuan** [comment]
牛
