### ISSUE TITLE
cpu占用率高

### ISSUE THREAD

**Issue by Infinityboy** [NervJS/taro#94]
win10环境下 使用vscode 打开项目 cpu爆到100%

**Comment by yuche** [comment]
三步走：

1. 打开菜单栏的 help -> Open Process Explorer

2. 找到对应进程找到开启的这个进程的项目

3. 去那个项目开 issue

**Comment by yuche** [comment]
应该是 cnpm 的问题。

参考：
https://www.zhihu.com/question/67317040
https://github.com/Microsoft/vscode/issues/35976

**Comment by seed-fe** [comment]
项目运行时，进程显示
Node.js: Server-side JavaScript cpu占用高达50%，请问是什么问题？

**Comment by Q-Qplus1s** [comment]
@yuche 应该不是cnpm vcode 问题 我用的npm 还有webstorm，Node.js: Server-side JavaScript 这个进程占用 80% CPU 经常卡死，切换过编辑器，或关闭微信开发者工具，看任务管理器确实是这个问题

**Comment by shenghanqin** [comment]
@Q-Qplus1s 如果你打开webstorm与ps，你会发现电脑直接卡死，所以我弃用vscode
