### ISSUE TITLE
集成dva后小程序下组件内dispatch页面不更新问题，h5正常

### ISSUE THREAD

**Issue by EvanMaFYH** [NervJS/taro#940]
**问题描述**
taro 1.0.7版本下集成了dva，但是组件内dispatch更新无效，写了一个计数器的demo复现问题
[demo地址](https://github.com/EvanMaFYH/dvademo)
可以发现在小程序下点击加，引用组件的页面发生了变化，而组件内部未发生变化，h5下可以发现是正常的
[或者可以直接贴源代码，能贴文字就不要截图]

**Comment by Chen-jj** [comment]
#1125
