### ISSUE TITLE
小程序自定义组件的钩子函数和taro框架的映射关系

### ISSUE THREAD

**Issue by chenws1999** [NervJS/taro#941]
**问题描述**
想在自定义组件从节点树销毁的时候(如　v-if 条件改变)做一些数据销毁工作，但是发现貌似componentwillunmount 钩子函数并不能映射到小程序组件的detached　钩子函数

**期望行为**
期望能使用小程序原生钩子函数　attached, detached, moved　

**报错信息**
无

**Comment by luckyadam** [comment]
componentwillunmount 对应的就是 detached
https://github.com/NervJS/taro/blob/master/packages/taro-weapp/src/create-component.js#L337

**Comment by chenws1999** [comment]
好的，感谢！！
