### ISSUE TITLE
Swiper indicatorDots 设置无效

### ISSUE THREAD

**Issue by DingLQ** [NervJS/taro#9410]
### 相关平台
H5

### 复现仓库
[https://github.com/DingLQ/swiperbug](https://github.com/DingLQ/swiperbug)
**浏览器版本: Chrome 90**
**使用框架: Vue 2**

### 复现步骤
yarn run dev:h5之后直接打开界面查看

### 期望结果
index.vue 中设置 indicatorDots 为 true ，轮播图应显示面板指示点

### 实际结果
设置 indicatorDots 为 true后轮播图不显示面板指示点

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - D:\RuntimeEnvironment\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\newsolar\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.7 - D:\RuntimeEnvironment\nodejs\npm.CMD
```

---
### 补充信息
查看Elements swiper-pagination 中同时出现swiper-pagination-hidden 和 swiper-pagination-bullets

**Comment by Chen-jj** [comment]
@DingLQ Vue 的属性命名规则遵循的是 **kebab-case**

```html
<swiper
  indicator-color='#999'
  indicator-active-color='#333'
  current="current"
  :duration="700"
  :circular="true"
  :autoplay="true"
  :indicator-dots="show">
  <swiper-item v-for="(item, idx) in imgUrls" :key="idx">
    <image :src="item" class="slide-image" />
  </swiper-item>
</swiper>
```
