### ISSUE TITLE
onLoad中的脚本错误，会导致小程序瘫痪

### ISSUE THREAD

**Issue by SSoLMan** [NervJS/taro#9413]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/SSoLMan/taro-error](https://github.com/SSoLMan/taro-error)
**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
进入存在异常的页面触发错误， 然后返回访问其他页面

### 期望结果
单个页面异常不影响其他页面访问

### 实际结果
其他页面访问均出现异常（空白）

### 环境信息
```
Taro CLI 3.1.5 environment info:
    System:
      OS: Windows 7
    Binaries:
      Node: 12.16.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
异常出现是，小程序原生的onLoad会触发，单子taro react组件的生命周期均不会触发

**Comment by Chen-jj** [comment]
@SSoLMan 可以参考这个回答，使用错误边界包裹页面。

https://github.com/NervJS/taro/pull/8191#issuecomment-743205010
