### ISSUE TITLE
h5 下来回切换 Tabbar 时重复渲染已经渲染过的页面

### ISSUE THREAD

**Issue by vimcaw** [NervJS/taro#942]
**问题描述**
在 h5 下，重复切换几个 Tabbar 时会不断地重复渲染已经渲染过的页面，这样性能很不好，正常的行为应该是像路由返回一样切换 `display` 属性来隐藏和显示。

**复现步骤**
任何大于一个 Tab 的 Tabbar 页面都能复现

下面的动图可以看到问题（动图大小 5M，加载可能慢一点），注意右边的 DOM 结构。

![2018-10-26_17-33-37](https://user-images.githubusercontent.com/21964227/47558300-60837980-d945-11e8-80bb-42ab48fab6b0.gif)

**期望行为**
切换 Tabbar 时，已渲染的 Tab 页面不再渲染，而且像路由返回一样通过切换 `display` 属性来隐藏和显示。

**报错信息**
无报错，但是与期望行为不一致，而且会带来很严重的性能问题。

**系统信息**

 - 操作系统: Windows 10
 - Taro 版本 v1.0.7
 - Node.js 版本 v8.11.4
 - 报错平台 h5

**补充信息**

**Comment by panruiplay** [comment]
同样遇到了这个问题，期待解决

**Comment by zhangxd1222** [comment]
这问题解决了吗？tabbar 左右切换时，能不再重新渲染已渲染过的页面吗？

**Comment by tourze** [comment]
+1

**Comment by smm5120** [comment]
求问+1
