### ISSUE TITLE
在@tarojs/rn-style-transformer中将node-sass替换为dart-sass

### ISSUE THREAD

**Issue by chareice** [NervJS/taro#9421]
### 这个特性解决了什么问题？
在apple m1中，node v16.2.0版本，无法编译node-sass

### 这个 API 长什么样？
能否将依赖中的node-sass替换为dart-sass？

**Comment by zhiqingchen** [comment]
有这个规划

**Comment by shinken008** [comment]
之前考虑到 node sass 切换到  dart sass  性能会损失，压测下来速度不太差，可以直接切换过去了
              
node@12.4.0

dart sass compile x 20,207,886 ops/sec ±0.70% (90 runs sampled)
node sass compile x 20,241,210 ops/sec ±0.44% (91 runs sampled)

**Comment by shinken008** [comment]
之前考虑到 node sass 切换到  dart sass  性能会损失，压测下来速度不太差，可以直接切换过去了
              
node@12.4.0

dart sass compile x 20,207,886 ops/sec ±0.70% (90 runs sampled)
node sass compile x 20,241,210 ops/sec ±0.44% (91 runs sampled)

**Comment by shinken008** [comment]
https://github.com/wuba/taro-react-native/commit/e13d2b96e42eac222df5632aceefb035b3f4d456
