### ISSUE TITLE
Windows 下小程序开启optimizeMainPackage优化主包大小后webpack打包报错

### ISSUE THREAD

**Issue by fengyibo** [NervJS/taro#9422]
操作系统：Windows 10
设置optimizeMainPackage 为 true后执行npm run dev:weapp 报错如下：

\ 正在编译...Error parsing bundle asset "D:\repos\weapp2\dist\sub-common\1918e06103fbb56c1892e28c3ec7f97d.js": no such file
Error parsing bundle asset "D:\repos\weapp2\dist\sub-common\22785c4bbefac20b21226e6ae1e00826.js": no such file
Error parsing bundle asset "D:\repos\weapp2\dist\sub-common\29465e21e4b4cc5165c1ded443ee4be1.js": no such file

相同的代码在ubuntu下打包正常
初步猜测windows下 路分隔符和ubuntu不一样，没做兼容处理，修复应该不负责

    /**
     * match sub-common\/*
     */
    matchSubCommon(chunk) {
        return new RegExp(`^${SUB_COMMON_DIR}\\/`).test(chunk.name);
    }

对前端不熟悉，希望有人处理一下

**Comment by huangcj99** [comment]
@fengyibo 应该是路径问题，我回家用window测测
