### ISSUE TITLE
Taro 2 支持 Babel 7.x

### ISSUE THREAD

**Issue by chuyun** [NervJS/taro#9424]
### 这个特性解决了什么问题？
支持新的 ecmascript 特性，比如 可选链、双问号等特性

目前 Taro 2 的部分包升级到了 Babel 7.x  但是 taro-weback-runner、transformer-wx 依然依赖的 Babel 6.x

期望官方能支持 Babel 7.x

### 这个 API 长什么样？
Taro 2.x 支持 Babel 7.x

**Comment by luckyadam** [comment]
2.x 基本不再做大的改动了，最好用 Taro 3 吧
