### ISSUE TITLE
开发环境并没有执行eslint检查

### ISSUE THREAD

**Issue by Benjaminbai** [NervJS/taro#9430]
### 相关平台
H5

### 复现仓库
[https://github.com/Benjaminbai](https://github.com/Benjaminbai)
**浏览器版本: chrome**
**使用框架: React**

### 复现步骤
"extends": [
    "taro"
  ],

### 期望结果
开发环境并没有执行eslint检查，期望检查不通过则本地运行报相关错误

### 实际结果
配置了eslint相关配置项，但是并没有运行，项目依旧启动成功

### 环境信息
```
Taro v3.2.8


  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

**Comment by luckyadam** [comment]
taro 不会主动检查 eslint
可以自己通过配置 loader 来实现

**Comment by Benjaminbai** [comment]
> taro 不会主动检查 eslint
> 可以自己通过配置 loader 来实现
> taro doctor 命令也会检查 eslint

不希望主动执行检查，希望taro像Create-React-App那样，在命令行中显示Lint信息，符合规则后才能成功运行，eslint-config-taro我以为这个是的

**Comment by Chen-jj** [comment]
@Benjaminbai 自行加一个 [eslint-loader](https://github.com/webpack-contrib/eslint-loader) 就可以了，它的 `failOnWarning `、`failOnError` 配置任君选择。

CRA 也是使用 `eslint-loader` 或 `eslint-webpack-plugin` 实现的。

**Comment by Benjaminbai** [comment]
> @Benjaminbai 自行加一个 [eslint-loader](https://github.com/webpack-contrib/eslint-loader) 就可以了，它的 `failOnWarning `、`failOnError` 配置任君选择。
> 
> CRA 也是使用 `eslint-loader` 或 `eslint-webpack-plugin` 实现的。
了解了，谢谢分享
