### ISSUE TITLE
微信群加入不进去

### ISSUE THREAD

**Issue by jacktang** [NervJS/taro#9431]
### 这个特性解决了什么问题？
文档里面有加入微信讨论群的步骤(https://docs.taro.zone/docs/communicate )，但是发送二维码过来后扫描加入不进去。

### 这个 API 长什么样？
希望能修复。

**Comment by ZakaryCode** [comment]
可以详细说说么？这个是企微的二维码，应该不存在这个问题

**Comment by jacktang** [comment]
现在可以加入了，可能是我自己这边的问题
