### ISSUE TITLE
taro h5端的scrollview在ios9（9.3.2）上获取不到event

### ISSUE THREAD

**Issue by crixusshen** [NervJS/taro#9440]
### 相关平台
H5

### 复现仓库
[https://gitee.com/crixusshen/taro-scrollview-bug.git](https://gitee.com/crixusshen/taro-scrollview-bug.git)
**使用框架: React**

### 复现步骤
使用taro h5端开发，在ios9.3.2上触发onScroll(event)时，返回的event是undefined，因而也导致onScrollToUpper无法被正常触发，同时测试了下ios10 以上均可正常获取到值

### 期望结果
希望ios9上能正常输出event对象和使用，毕竟ios9还是具有一定的市场份额

### 实际结果
onScroll(event)的event返回undefined，且onScrollToUpper没有被正常触发

### 环境信息
```
Taro CLI 3.1.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.10 => 3.2.10 
      @tarojs/components: 3.2.10 => 3.2.10 
      @tarojs/mini-runner: 3.2.10 => 3.2.10 
      @tarojs/react: 3.2.10 => 3.2.10 
      @tarojs/runtime: 3.2.10 => 3.2.10 
      @tarojs/taro: 3.2.10 => 3.2.10 
      @tarojs/webpack-runner: 3.2.10 => 3.2.10 
      babel-preset-taro: 3.1.4 => 3.1.4 
      eslint-config-taro: 3.1.4 => 3.1.4 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
![image](https://user-images.githubusercontent.com/11752878/120413959-c7822e00-c38b-11eb-8bab-6230f9a45d8a.png)

![image](https://user-images.githubusercontent.com/11752878/120414601-d1586100-c38c-11eb-98ce-2f3d59c42707.png)

![image](https://user-images.githubusercontent.com/11752878/120414621-d9180580-c38c-11eb-939f-e57b3e1f2700.png)

**Comment by crixusshen** [comment]
这应该是 stencil 的bug，因此在demo中提供了一个兼容方案，可临时用于项目组对Ios9+有兼容要求的需求！

**Comment by Chen-jj** [comment]
@crixusshen @soeasyjx 从 `@tarojs/components-react/index` 中引用 `ScrollView` 试试。这是使用 React 写的 Taro 组件库（只有若干组件）。

```js
import { ScrollView } from '@tarojs/components-react/index';
```

----------

Taro 使用了 Stencil 的 `EventEmitter` 触发事件：

https://github.com/NervJS/taro/blob/88c7ea1aa022e7a84407b85d34ea35c377297409/packages/taro-components/src/components/scroll-view/scroll-view.tsx#L165-L170

`EventEmitter.emit` 会返回一个 `CustomEvent`：

https://github.com/ionic-team/stencil/blob/f09abe6455887025d508e645e7c8c024a5c42fa2/src/declarations/stencil-public-runtime.ts#L467-L469

因此目测是 iOS9 对 `CustomEvent` 的支持有问题，有兴趣可以试试。
