### ISSUE TITLE
vue  input  type 设置 password 密码框无效

### ISSUE THREAD

**Issue by DingLQ** [NervJS/taro#9443]
### 相关平台
H5

### 复现仓库
[https://github.com/DingLQ/inputbug](https://github.com/DingLQ/inputbug)
**浏览器版本: chrome 91**
**使用框架: Vue 2**

### 复现步骤
1. 运行程序
2. 在输入框中随便输入文本

### 期望结果
input 密码框中的内容不可见被⚪替代

### 实际结果
input 密码框中的内容明文显示

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.13.0 - D:\RuntimeEnvironment\nodejs\node.EXE        
      Yarn: 1.22.4 - C:\Users\newsolar\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.7 - D:\RuntimeEnvironment\nodejs\npm.CMD
```

---
### 补充信息
根据taro-ui-vue 的例子 3.0.X版本中是有效的。
esm-es5/taro-input-core.entry.js 中 this.type 没有接收到数据

**Comment by Chen-jj** [comment]
和这个 PR 有关：https://github.com/NervJS/taro/pull/9040
