### ISSUE TITLE
build h5 安卓手机加载报错: 'super' keyword unexpected here 

### ISSUE THREAD

**Issue by rabbitao** [NervJS/taro#9447]
### 相关平台
H5

**浏览器版本: Android webview**
**使用框架: React**
**Taro cli版本: 3.2.10**

### 复现步骤
1. 使用build:h5打包
2. 发布到线上
3. 通过安卓手机访问
4. 页面白屏
5. 远程调试控制台显示语法错误:   'super' keyword unexpected here 

### 期望结果
安卓手机正常访问

### 实际结果
安卓手机无法打开

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 3.8.3
```

---
### 补充信息
报错位置为app.js如下代码
l=class extends HTMLElement{"constructor"(t){super(t),registerHost(t=this,c)}"connectedCallback"()
userAgent信息: Mozilla/5.0 (Linux; U; Android 10; zh-CN; Redmi Note 7 Build/QKQ1.190910.002)

node_modules/@tarojs/components/dist 目录下并没有esm-es5的输出目录
node_modules/@tarojs/components/loader/index.js 导出的目录为 export * from '../dist/esm/loader.js'

![image](https://user-images.githubusercontent.com/27269160/120574060-2cec2280-c451-11eb-9260-bd1d8fe4c3cc.png)

**Comment by rabbitao** [comment]
解决了!
问题在于此版本的tarocli 初始化项目之后, package.json中的依赖版本是锁定版本.
![image](https://user-images.githubusercontent.com/27269160/120575083-03cc9180-c453-11eb-987b-3af2709a99b3.png)


手动把版本修改一下即可
![image](https://user-images.githubusercontent.com/27269160/120575135-1646cb00-c453-11eb-93c1-c45dfe03f5a1.png)

希望后面把taro init 出来的项目里的package.json依赖版本调整一下.

**Comment by luckyadam** [comment]
版本号是根据你的 taro cli 版本来的
