### ISSUE TITLE
小程序与 Taro 混写下，处理 usingComponents  的路径问题

### ISSUE THREAD

**Issue by YikaJ** [NervJS/taro#945]
在原生小程序下，app.json 内引用组件的路径是可以使用绝对路径的。
但在 Taro 编译下，用绝对路径会有红色的错误警告。
请问，这个是 Taro 无法做到检测么？我认为绝对路径，映射到 Taro 内，是否可以理解为是以 src 作为根目录呢？

**Comment by YikaJ** [comment]
是的，利用 path.isAbsolutePath 和 path.relativePath 应该是很容易做到这个相关检测的，不依赖相对路径，比较方便开发者调用根目录的全局模块。那这里麻烦你看看 Taro 如何处理啦，谢谢。

**Comment by Legend669** [comment]
Fuck U fuck- boy .U already I take all fades Bitch .So just come so I can
get it over wit .When it done u be nolonger.
