### ISSUE TITLE
3.2.10 开发小程序插件

### ISSUE THREAD

**Issue by vivialex** [NervJS/taro#9457]
3.2.10 开发小程序插件
![image](https://user-images.githubusercontent.com/13270284/120680296-b68d0600-c4cc-11eb-864f-3d5c9acc19e5.png)
miniprogram里的taro.js会带上“./node_modules/@tarojs/plugin-platform-weapp/dist/runtime.js”
![image](https://user-images.githubusercontent.com/13270284/120680484-f227d000-c4cc-11eb-8be8-04645b3c60e2.png)
但是plugin里的taro.js并没有带上，导致插件内都调用不了微信的方法

_Originally posted by @vivialex in https://github.com/NervJS/taro/issues/8751#issuecomment-854013776_

**Comment by vivialex** [comment]
@luckyadam 你好，大佬，使用taro-cli生成的小程序插件项目，构建后即可复现

**Comment by Jinchengawu** [comment]
> 可以提供个demo看看

你好，我做过以下测试；demo 就直接 用 taro/cli 创建 小程序插件工程即可；未做其他改动；

————————————

Taro 3.1.x 版本 ：无法启动报错如下：
![image](https://user-images.githubusercontent.com/26629063/123026026-17459980-d40e-11eb-8b1c-75fe1ec03cfa.png)

————————————

Taro 3.2.x版本 ：在 编译并不报错 但 plugin 目录，Taro 挂在 wx api 失败；但编译并不报错

![image](https://user-images.githubusercontent.com/26629063/123026086-2e848700-d40e-11eb-83b4-1d90a703438e.png)
![image](https://user-images.githubusercontent.com/26629063/123026131-422fed80-d40e-11eb-90fe-86169723eed5.png)

————————————

Taro 3.3.0-beta.0版本 ：同样 编译并不报错 但 在 plugin 目录下，Taro 挂在 wx api 失败；

————————————
依赖附加：
```
{
  "name": "wxdemo",
  "version": "1.0.0",
  "private": true,
  "description": "wxdemo",
  "templateInfo": {
    "name": "wxplugin",
    "typescript": false,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:weapp_plugin": "taro build --plugin weapp --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "author": "",
  "license": "MIT",
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/components": "3.3.0-beta.0",
    "@tarojs/runtime": "3.3.0-beta.0",
    "@tarojs/taro": "3.3.0-beta.0",
    "@tarojs/react": "3.3.0-beta.0",
    "react-dom": "^17.0.0",
    "react": "^17.0.0"
  },
  "devDependencies": {
    "@types/webpack-env": "^1.13.6",
    "@types/react": "^17.0.2",
    "@tarojs/mini-runner": "3.3.0-beta.0",
    "@tarojs/cli": "3.3.0-beta.0",
    "@babel/core": "^7.8.0",
    "@tarojs/webpack-runner": "3.3.0-beta.0",
    "babel-preset-taro": "3.3.0-beta.0",
    "eslint-config-taro": "3.3.0-beta.0",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0"
  }
}
```
