### ISSUE TITLE
Taro  H5 browser  路由在阿里mpaas 框架webview中无法打开，白屏

### ISSUE THREAD

**Issue by xiehui999** [NervJS/taro#9462]
### 相关平台
H5

### 复现仓库
[https://github.com/xiehui999/test](https://github.com/xiehui999/test)
**浏览器版本: Android手机**
**使用框架: React**

### 复现步骤
1， Android 接入webview接入mpaas
https://help.aliyun.com/document_detail/49549.html?spm=5176.cnmpaas.0.0.425a669ei9rDVB

2， 将编译browser 类型路由的H5放到 mpaas中的webview中
3， 运行后白屏

未提供复现demo， 需要在接入mpaas 的android客户端webview中

### 期望结果
正常访问

### 实际结果
白屏，无法访问

### 环境信息
```
原来taro 3.2.7 ，降级回3.0.24 也有问题

 Taro CLI 3.0.24 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.0.24 => 3.0.24 
      @tarojs/mini-runner: 3.0.24 => 3.0.24 
      @tarojs/react: 3.0.24 => 3.0.24 
      @tarojs/router: 3.0.24 => 3.0.24 
      @tarojs/runtime: 3.0.24 => 3.0.24 
      @tarojs/taro: 3.0.24 => 3.0.24 
      @tarojs/webpack-runner: 3.0.24 => 3.0.24 
      babel-preset-taro: 3.0.24 => 3.0.24 
      eslint-config-taro: 3.0.24 => 3.0.24 
      eslint-plugin-taro: 3.0.24 => 3.0.24 
      nerv-devtools: ^1.5.7 => 1.5.7 
      nervjs: ^1.5.7 => 1.5.7 
      react: ^16.13.1 => 16.14.0 

```

---
### 补充信息
使用hash 路由可正常访问， browser 类型的路由无法访问， 试了一下，其它使用mpaas库的第三方app以及阿里系都有问题。

**Comment by Chen-jj** [comment]
升级 3.2.10 再试试

**Comment by xiehui999** [comment]
3.2.10 可以了，这个有定位原因，或者相关调整pr吗

**Comment by xiehui999** [comment]
> 升级 3.2.10 再试试


3.2.10 直接进入是可以打开了，但是刷新还是不行， 是不是里面路由使用了windown.location.href = '' , 使用browser 路由时使用windown.location.href 都会不work， 使用hash windown.location.href是正常的
