### ISSUE TITLE
taro v3.2.10 开发小程序插件，插件暴露的组件无法获取入参的值

### ISSUE THREAD

**Issue by vivialex** [NervJS/taro#9463]
taro v3.2.10 开发小程序插件，插件暴露的组件无法获取入参的值

1. 插件暴露的组件 

```typescript
export default function Avatar ({
  productId,
  name
}) {
  console.log('productId', productId); // undefined
  console.log('name', name); // undefined
  
  return (
    <View>
      <Image src='http://storage.360buyimg.com/taro-static/static/images/logo.png' />
    </View>
  )
}
```

2. 插件调用方

不管是直接传入，还是按照[文档](https://taro-docs.jd.com/taro/docs/miniprogram-plugin#%E6%8F%92%E4%BB%B6%E7%BB%84%E4%BB%B6%E6%8E%A5%E5%8F%97%E5%A4%96%E9%83%A8-props)里说的通过`extraProps`传入都不行

```html
<View>
  <avatar
    extraProps="{{wifiConfProps}}"
    name="{{name}}"
  />
</View>

```

```typescript
Page({
  data: {
    name: 'xxx',
    wifiConfProps: {
      productId: 'xxx',
    }
  },
  onLoad() {
  }
})

```
@Chen-jj

_Originally posted by @vivialex in https://github.com/NervJS/taro/pull/9092#issuecomment-854737898_

**Comment by luckyadam** [comment]
https://docs.taro.zone/docs/miniprogram-plugin#%E6%8F%92%E4%BB%B6%E7%BB%84%E4%BB%B6%E6%8E%A5%E5%8F%97%E5%A4%96%E9%83%A8-props
你看的文档是旧的，试试这个
