### ISSUE TITLE
在js文件中使用store.dispatch来改变state，页面没有重新渲染

### ISSUE THREAD

**Issue by G21iwenjun** [NervJS/taro#9472]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/FE_lwj/taro-test](https://gitee.com/FE_lwj/taro-test)
**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
1.在js文件执行store.dispatch()
2.页面中使用state，观察页面状态不更新

### 期望结果
在js文件执行store.dispatch()，使用了state的页面状态也发生变化

### 实际结果
在js文件执行store.dispatch()，使用了state的页面状态不更新

### 环境信息
```
� Taro v3.2.10


  Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\liwenjun\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@G21iwenjun 不是 Taro 的问题。

`configStore` 是一个函数，每次调用都创建一个新的 `store` 对象：

![image](https://user-images.githubusercontent.com/11807297/122182013-74949480-cebc-11eb-89bb-18d571c32420.png)

你在每次需要 `store` 实例的时候，都调用了 `configStore` 产生一个新的 `store`，不同 `store` 间的 `dispatch` 当然是不生效的。

![image](https://user-images.githubusercontent.com/11807297/122181904-5b8be380-cebc-11eb-9d31-b0ea638cf493.png)

正确的做法是只保留一个 `store` 单例，而不是多次调用 `configStore`。
