### ISSUE TITLE
Picker配置rangeKey无效

### ISSUE THREAD

**Issue by zhytang** [NervJS/taro#9475]
### 相关平台
H5

**浏览器版本: Chrome 91**
**使用框架: Vue 2**

### 复现步骤
```javasctipt
  <picker
      mode='multiSelector'
      :range="range"
      :value="value"
      :rangeKey="rangeKey"
   >
 
  data() {
    return {
      range:[[{id: 1, name: '北京市'}],[id: 11, name: '海淀区']],
      rangeKey: 'name',
      value: 1,
    };
  }
```

### 期望结果
期望能正常显示

### 实际结果
![image](https://user-images.githubusercontent.com/16872071/121121018-63f77500-c851-11eb-89ea-d37e2b8cc245.png)

### 环境信息
```
👽 Taro v3.2.8


  Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
```

---
### 补充信息
原因是因为h5的picker没有接受rangKey，见：  https://github.com/NervJS/taro/blob/b73d5265ab123fe52bf26ebd8b19f1f9ec37f71e/packages/taro-components/h5/vue/components/picker.js#L9-L12

**Comment by lemonSll** [comment]
3.3.3还是没有修复这个问题啊,还是undefined
![image](https://user-images.githubusercontent.com/44395984/129685454-12decedf-4d7c-44db-815d-a112dd720f9f.png)

**Comment by zhytang** [comment]
> 3.3.3还是没有修复这个问题啊,还是undefined
> ![image](https://user-images.githubusercontent.com/44395984/129685454-12decedf-4d7c-44db-815d-a112dd720f9f.png)

提的PR有问题，还是少一部分。 @Chen-jj 大佬重新开下这个问题，我提下PR。

**Comment by 15380831711** [comment]
确定修复了吗，升级到最新版3.3.7都不行，picker.js中的rangeKey属性定义了，貌似没有代码引用到。
