### ISSUE TITLE
vue3 无法使用 setup语法糖

### ISSUE THREAD

**Issue by transtone** [NervJS/taro#9476]
### 相关平台
H5

### 复现仓库
[https://github.com/transtone/toro-vue3-build-setup-bug](https://github.com/transtone/toro-vue3-build-setup-bug)
**浏览器版本: 所有浏览器**
**使用框架: Vue 3**

### 复现步骤
`yarn build:h5`

打包后，<script setup> 中的代码不见了。开发模式正常。

### 期望结果
正常使用 setup语法

### 实际结果
不能使用 setup 语法

### 环境信息
```
👽 Taro v3.2.10


  Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.20.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

**Comment by tolking** [comment]
我也一样，开发正常打包错误

**Comment by transtone** [comment]
这个问题跟 vue-loader 有关： https://github.com/vuejs/vue-loader/issues/1747
但 vue-cli 本身没有问题，是不是跟依赖的版本有关，负责 vue3 模块的兄弟能否查一查？

**Comment by transtone** [comment]
taro 的问题还和上述列出的不一样，  不仅 <script setup> 部分的js不生效，<template> 中的内容，正常会将 <view> 转换成 <taro-view-core> ，也没有被转换。

**Comment by b2nil** [comment]
@transtone 
`script setup` 中 `props` 现在需要引用 `defineProps` 来定义：
```ts
import { ref, defineProps } from 'vue'
const props = defineProps({
      msg: String,
})
```

但是 `vue-loader` 现在的版本没有把 `compilerOptions` 传给 [`compileScript`](https://github.com/vuejs/vue-loader/blob/next/src/resolveScript.ts#L61) 处理，导致 Taro 的 `vue-loader` 设置未生效，所以小程序 tag `<xxx>` 没有被转换成 `<taro-xxx-core>` 。
```ts
// https://github.com/vuejs/vue-loader/blob/next/src/resolveScript.ts#L64
if (compileScript) {    
  try {      
    resolved = compileScript(descriptor, {       
       id: scopeId,        
       isProd,       
       inlineTemplate: enableInline,       
       babelParserPlugins: options.babelParserPlugins,       
       templateOptions: {         
          compiler,         
          ssr: isServer,          
          transformAssetUrls: options.transformAssetUrls || true, 
          compilerOptions: options.compilerOptions   // 添加 compilerOptions 试试
     },      
  })   
  } catch (e) {     
     loaderContext.emitError(e)    
  }
}  else if (descriptor.scriptSetup) {
   // ...
}


```

**Comment by transtone** [comment]
> @transtone
> 
> 但是 `vue-loader` 现在的版本没有把 `compilerOptions` 传给 [`compileScript`](https://github.com/vuejs/vue-loader/blob/next/src/resolveScript.ts#L61) 处理，导致 Taro 的 `vue-loader` 设置未生效，所以小程序 tag `<xxx>` 没有被转换成 `<taro-xxx-core>` 。
> 
> ```ts
> // https://github.com/vuejs/vue-loader/blob/next/src/resolveScript.ts#L64
> if (compileScript) {    
>   try {      
>     resolved = compileScript(descriptor, {       
>        id: scopeId,        
>        isProd,       
>        inlineTemplate: enableInline,       
>        babelParserPlugins: options.babelParserPlugins,       
>        templateOptions: {         
>           compiler,         
>           ssr: isServer,          
>           transformAssetUrls: options.transformAssetUrls || true, 
>           compilerOptions: options.compilerOptions   // 添加 compilerOptions 试试
>      },      
>   })   
>   } catch (e) {     
>      loaderContext.emitError(e)    
>   }
> }  else if (descriptor.scriptSetup) {
>    // ...
> }
> ```

谢谢回复。

不明白的是，既然受 compileOptions 影响，应该会影响所有的页面转换才对，
为什么 compileOptions 只会影响有 `<script setup>` 的页面代码？

**Comment by Chen-jj** [comment]
https://github.com/vuejs/vue-loader/issues/1838

**Comment by transtone** [comment]
fixed in vue-loader-16.3.0
