### ISSUE TITLE
如何构建Taro 3.2.10版本并去掉RN相关的依赖

### ISSUE THREAD

**Issue by JNUfeatherwit** [NervJS/taro#9477]
### 这个特性解决了什么问题？
团队项目只用于小程序，对React Native没有需求，所以不需要任何对React Native的支持，目前发现Taro 3.2.10内置了大量React Native相关依赖，同时使用yarn时最后还会调用npm run patch-package命令，这个命令一直是失败的

### 这个 API 长什么样？
开发者可自主决定需不需要引入React Native相关依赖

**Comment by huarse** [comment]
楼上 + 1，最近安装 babel-preset-taro 一直失败，都是挂在 `npm run patch-package` 上

**Comment by tourze** [comment]
"@tarojs/components-rn": "3.2.10",
    "@tarojs/rn-runner": "3.2.10",
    "@tarojs/rn-style-transformer": "3.2.10",
    "@tarojs/rn-supporter": "3.2.10",
    "@tarojs/runtime-rn": "3.2.10",
    "@tarojs/taro-rn": "3.2.10",

这几个依赖去掉就好了吧

**Comment by Duo-Huang** [comment]
楼主解决了吗，我也遇到了patch-package 这个包压根装不上

**Comment by JNUfeatherwit** [comment]
> 楼主解决了吗，我也遇到了patch-package 这个包压根装不上

在项目的package.json加上"patch-package": "^6.2.2"就可以了

**Comment by JNUfeatherwit** [comment]
> ```
> "@tarojs/components-rn": "3.2.10",
> "@tarojs/rn-runner": "3.2.10",
> "@tarojs/rn-style-transformer": "3.2.10",
> "@tarojs/rn-supporter": "3.2.10",
> "@tarojs/runtime-rn": "3.2.10",
> "@tarojs/taro-rn": "3.2.10",
> ```
> 
> 这几个依赖去掉就好了吧

去掉需要改源码

**Comment by Duo-Huang** [comment]
我知道在项目的package.json上加依赖就可以了，但是这样让别人很费解，这个并不是我项目的直接依赖

**Comment by Duo-Huang** [comment]
![image](https://user-images.githubusercontent.com/50909268/121168762-e4d06400-c885-11eb-91dc-7f919663c639.png)

**Comment by zhiqingchen** [comment]
降低版本呢，这些依赖默认是没安装的

**Comment by zhiqingchen** [comment]
另外也可在项目的`package.json`中加入版本锁定解决
```json
  "resolutions": {
    "@ant-design/icons-react-native": "2.2.1"
  }
```

**Comment by zhiqingchen** [comment]
@ant-design/icons-react-native 已更新到了 2.3.1，解决了上述报错。

**Comment by Duo-Huang** [comment]
> @ant-design/icons-react-native

试了下这个版本好了，棒
