### ISSUE TITLE
taro安装@tarojs/plugin-sass失败！！

### ISSUE THREAD

**Issue by yzw2017** [NervJS/taro#948]
在命令行执行taro init myApp
一路回车...
然后选择预处理器 sass
没问题
运行npm run dev:weapp
...
缺少npm包@tarojs/plugin-sass，开始安装然后就
<img width="593" alt="2018-10-28 6 57 41" src="https://user-images.githubusercontent.com/31871287/47614972-5f884e80-dae3-11e8-993c-0aee67a190eb.png">

**Comment by luckyadam** [comment]
可以换 cnpm 安装

**Comment by mindfocus** [comment]
试试这个
`npm config set sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"
`

**Comment by borie88** [comment]
问题并没有解决：
Cannot download "https://r.cnpmjs.org/node-sass//v4.10.0/win32-x64-64_binding.node":
HTTP error 404 Not Found

**Comment by monsuns** [comment]
同安装失败. 已经安装了 node-sass\4.11.0 但还是会去主动安装 node-sass/v4.8.3 , 可惜后者在淘宝源已经找不到了. 所以就报错了. 不懂为什么会这样.

**Comment by yupeilin123** [comment]
> 问题并没有解决：
> Cannot download "https://r.cnpmjs.org/node-sass//v4.10.0/win32-x64-64_binding.node":
> HTTP error 404 Not Found

我也这样
