### ISSUE TITLE
MovableView 的 onHTouchMove 和 onVTouchMove 支持 catch 嘛？

### ISSUE THREAD

**Issue by ShenChang618** [NervJS/taro#9494]
### 这个特性解决了什么问题？
如题，我在 swiper 中嵌入了 Movable，我希望通过 catch onHTouchMove 和 onVTouchMove 阻止Swiper 滑动效果

### 这个 API 长什么样？
支持 catch onHTouchMove 和 onVTouchMove

**Comment by Chen-jj** [comment]
使用 `catchMove` 禁止滚动试试，这时会小程序模板会绑定 `catchtouchmove`。

`onHTouchMove` 和 `onVTouchMove` 目前只会在模板绑定 `bindhtouchmove` 和 `bindvtouchmove`

```jsx
<View catchMove></View>
```

**Comment by ShenChang618** [comment]
我尝试了一下发现不行，不过我自己写了一个原生的组件，嵌入到了项目中。目前这样做虽然能够解决问题，但还是比较麻烦的，希望能够把这两个 API 加上。

**Comment by lupingW** [comment]
> 使用 `catchMove` 禁止滚动试试，这时会小程序模板会绑定 `catchtouchmove`。
> 
> `onHTouchMove` 和 `onVTouchMove` 目前只会在模板绑定 `bindhtouchmove` 和 `bindvtouchmove`
> 
> <View catchMove></View>

现在支持了吗
