### ISSUE TITLE
Children 与组合什么时候可以获取到ref实例

### ISSUE THREAD

**Issue by xiaoshan100** [NervJS/taro#9498]
### 这个特性解决了什么问题？
我有一个曝光组件，需要获取到其子组件的实例对象，目前通过一个props去传值，结果发现虽然结果出来了但是一直在报堆栈错误，未找到原因，希望能有直接获取this.props.children实例的api

### 这个 API 长什么样？
可以直接获取this.props.children或者组合的实例对象

**Comment by Chen-jj** [comment]
ref
