### ISSUE TITLE
[文档勘误] events.md 未引入 Events，报错 Events is not defined 

### ISSUE THREAD

**Issue by xunge0613** [NervJS/taro#95]
events.md 文档中未引入 Events，会报错 Events is not defined 

![image](https://user-images.githubusercontent.com/1448574/41326073-e2fe6ebc-6eef-11e8-880b-7a6e881c5fa5.png)

import Taro from '@tarojs/taro'
=> 应改为
import Taro,{Events} from '@tarojs/taro'
 
 #96

**Comment by yuche** [comment]
close via #96
