### ISSUE TITLE
3.2.11 -  h5端报错：没有找到页面实例。 如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues

### ISSUE THREAD

**Issue by crixusshen** [NervJS/taro#9511]
### 相关平台
H5

### 复现仓库
无需demo，官方提供的demo修改成3.2.11运行就会报这个错误
**浏览器版本: chrome 版本 91.0.4472.77**
**使用框架: React**

### 复现步骤
更新最新的3.2.11，启动h5报：没有找到页面实例。 如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues

### 期望结果
运行成功

### 实际结果
报错：没有找到页面实例。 如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.11 => 3.2.11 
      @tarojs/components: 3.2.11 => 3.2.11 
      @tarojs/mini-runner: 3.2.11 => 3.2.11 
      @tarojs/react: 3.2.11 => 3.2.11 
      @tarojs/runtime: 3.2.11 => 3.2.11 
      @tarojs/taro: 3.2.11 => 3.2.11 
      @tarojs/webpack-runner: 3.2.11 => 3.2.11 
      babel-preset-taro: 3.2.11 => 3.2.11 
      eslint-config-taro: 3.2.11 => 3.2.11 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

![image](https://user-images.githubusercontent.com/11752878/121619613-7533c200-ca9b-11eb-86fa-f15d6af17684.png)

**Comment by Chen-jj** [comment]
Taro CLI 和 Taro 依赖版本保持一致。

**Comment by liangxioa** [comment]
vue3也有这样的问题，官方模板直接跑会报没有找到页面实例。
![image](https://user-images.githubusercontent.com/40156437/121629555-001db800-caae-11eb-8e20-faae31ab0fee.png)

**Comment by Chen-jj** [comment]
这个 [PR](https://github.com/NervJS/taro/pull/9416) 导致的问题，会尽快发版修复。

**Comment by zlsam** [comment]
同样问题
版本：
    taro: 3.2.11

![image](https://user-images.githubusercontent.com/8859828/121652706-821dd900-cace-11eb-9ab9-bf321e4dd9a9.png)

**Comment by ntop001** [comment]
这个问题修复了没有，刚刚下载的 cli 最新版本依然是 3.2.11 ，依然包页面没找到的错误。

**Comment by Chen-jj** [comment]
> 这个问题修复了没有，刚刚下载的 cli 最新版本依然是 3.2.11 ，依然包页面没找到的错误。

3.2.12 解决，上周发版 ci 挂了，马上补发

**Comment by ntop001** [comment]
@Chen-jj 好的谢谢。

**Comment by s97712** [comment]
3.3.12 同样错误

**Comment by ooooevan** [comment]
> > 这个问题修复了没有，刚刚下载的 cli 最新版本依然是 3.2.11 ，依然包页面没找到的错误。
> 
> 3.2.12 解决，上周发版 ci 挂了，马上补发

3.4.3 一样报错

**Comment by dreamsSilent** [comment]
> > 这个问题修复了没有，刚刚下载的 cli 最新版本依然是 3.2.11 ，依然包页面没找到的错误。
> 
> 3.2.12 解决，上周发版 ci 挂了，马上补发

3.4.13也是一样的，麻烦解决一下

**Comment by Chen-jj** [comment]
@dreamsSilent 可能是其它原因导致的，麻烦新开一个 issue 并附上可复现 Demo 咯
