### ISSUE TITLE
用官方的模版（style），npm run dev:rn真机运行报错

### ISSUE THREAD

**Issue by 929525077** [NervJS/taro#953]
![_20181029164535](https://user-images.githubusercontent.com/23496902/47638721-5312fd00-db9a-11e8-800f-03f9bb9409d5.png)

rn_temp的app代码还是import 了app.styl
但rn_temp编译的时候，已经转换成app_styles.js了
![_20181029164644](https://user-images.githubusercontent.com/23496902/47638682-32e33e00-db9a-11e8-88e3-c5c0cc9d517e.png)
使用css的模版可以通过

**Comment by luckyadam** [comment]
taro 版本多少

**Comment by 929525077** [comment]
1.0.7

**Comment by luckyadam** [comment]
可以升级到最新的 beta 版本试试，1.0.7 貌似没有处理 stylus

**Comment by 929525077** [comment]
好的
