### ISSUE TITLE
taro初始化项目启动报错

### ISSUE THREAD

**Issue by paulluap** [NervJS/taro#9534]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/paulluap/taro-init-error-reproduce](https://github.com/paulluap/taro-init-error-reproduce)
**小程序基础库: h5版本**
**使用框架: React**

### 复现步骤
taro --version
👽 Taro v3.2

taro init myApp

cd myApp

yarn dev:h5

### 期望结果
浏览器能显示正常hello world内容

### 实际结果
运行报错

### 环境信息
```
taro info
👽 Taro v3.2.11


  Taro CLI 3.2.11 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.1 - ~/.asdf/installs/nodejs/14.16.1/bin/node
      Yarn: 1.22.10 - ~/.asdf/shims/yarn
      npm: 6.14.12 - ~/.asdf/installs/nodejs/14.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.2.11 => 3.2.11
      @tarojs/mini-runner: 3.2.11 => 3.2.11
      @tarojs/react: 3.2.11 => 3.2.11
      @tarojs/runtime: 3.2.11 => 3.2.11
      @tarojs/taro: 3.2.11 => 3.2.11
      @tarojs/webpack-runner: 3.2.11 => 3.2.11
      babel-preset-taro: 3.2.11 => 3.2.11
      eslint-config-taro: 3.2.11 => 3.2.11
      react: ^17.0.0 => 17.0.2

```

**Comment by paulluap** [comment]
<img width="1179" alt="taro-run-error" src="https://user-images.githubusercontent.com/1617932/121773097-40636000-cbac-11eb-9610-73325b66dabe.png">
<img width="733" alt="taro-run-error-2" src="https://user-images.githubusercontent.com/1617932/121773098-42c5ba00-cbac-11eb-9c51-9bb283a67a8e.png">

**Comment by paulluap** [comment]
版本降到3.2.10 没有这个问题
https://github.com/paulluap/taro-init-error-reproduce/commit/3b037ff070f4fe5ae0e9013dbac3d8ccfe881c2e

**Comment by PerfectPan** [comment]
3.2.12 已经修复了 https://github.com/NervJS/taro/pull/9517
