### ISSUE TITLE
没有找到页面实例

### ISSUE THREAD

**Issue by Tammy-zting** [NervJS/taro#9535]
### 相关平台
H5

**浏览器版本: Chrome最新版**
**使用框架: React**

### 复现步骤
taro命令初始化项目  
选择默认模板
yarn安装包
yarn dev:h5 

### 期望结果
Hello World

### 实际结果
Error 
没有找到页面实例

Call Stack
 ensure
  node_modules/@tarojs/shared/dist/shared.esm.js:620:11
 AppWrapper.eval
  node_modules/@tarojs/runtime/dist/runtime.esm.js:4317:73
 callCallback
  node_modules/react-dom/cjs/react-dom.development.js:12365:16
 commitUpdateQueue
  node_modules/react-dom/cjs/react-dom.development.js:12388:13
 commitLifeCycles
  node_modules/react-dom/cjs/react-dom.development.js:20634:15
 commitLayoutEffects
  node_modules/react-dom/cjs/react-dom.development.js:23318:11
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:3926:18
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:3975:20
 invokeGuardedCallback
  node_modules/react-dom/cjs/react-dom.development.js:4035:35
 commitRootImpl
  node_modules/react-dom/cjs/react-dom.development.js:23052:13
× Close

### 环境信息
```
�👽 Taro v3.2.


  Taro CLI 3.2.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.0 - D:\Program Files (x86)\node.EXE
      Yarn: 1.16.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - D:\Program Files (x86)\npm.CMD
```

**Comment by Chen-jj** [comment]
3.2.12 解决

duplicate #9511

**Comment by Tammy-zting** [comment]
升级为3.2.12

**Comment by Tammy-zting** [comment]
`yarn update self `
