### ISSUE TITLE
taro 引用微信小程序editor组件， 父组件接收不到 editor传值 editor组件用this.triggerEvent('Content', {content: e.detail, id: e.currentTarget.id})传值的，父组件用onContent={this.contentBtn.bind(this)}接收的值

### ISSUE THREAD

**Issue by ShimmerGww5201** [NervJS/taro#9537]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
taro 引用微信小程序editor组件， 父组件接收不到 editor传值   editor组件用this.triggerEvent('Content', {content: e.detail, id: e.currentTarget.id})传值的，父组件用onContent={this.contentBtn.bind(this)}接收的值

### 期望结果
父组件可以接收editor的传值

### 实际结果
父组件接收不到editor的传值

### 环境信息
```
  Taro CLI 3.2.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\boon\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
目前什么报错信息都没有，父组件接收不到editor组件的传值

**Comment by luckyadam** [comment]
什么 editor 组件，麻烦提供一下具体使用代码

**Comment by ShimmerGww5201** [comment]
您好，我解决了了，谢谢

**Comment by huanlirui** [comment]
> 

你好怎么解决的？ Taro中无法拿到 微信原生组件 triggerEvent  回调  taro3.4.9
