### ISSUE TITLE
微信小程序使用vant weapp field，使用maxlength后，所有其他页面的field maxlength都为0

### ISSUE THREAD

**Issue by nemo02622** [NervJS/taro#9541]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤

使用vant weapp 原生组件field，在设置了maxlength之后，所有其他页面使用filed组件的maxlength全都变成了0，导致无法输入
```
<van-field
    maxlength={6}
    customStyle={fieldStyle}
    placeholder='请输入6位新密码'
    onChange={(e)=>{setPassword(e.detail)}}
/>
```

### 期望结果
不同界面之间使用原生组件，不应该互相影响

### 实际结果
a界面使用vant weapp 的filed，并设置maxlength，所有其他界面使用filed组件的maxlength都变成了0

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.5.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
提供一下 demo 咯

**Comment by nemo02622** [comment]
> 提供一下 demo 咯


[vantbug.zip](https://github.com/NervJS/taro/files/6660928/vantbug.zip)

**Comment by Chen-jj** [comment]
@nemo02622 Taro 3 使用 template 渲染每个虚拟 DOM 节点，属性是需要提前写死的（因为小程序没有提供动态设置属性的方法）。

当使用了 `van-field` 时，生成的模板是这样（在 `dist/base.wxml` 中）。

```jsx
<template name="tmpl_1_van-field">
  <van-field maxlength="{{i.maxlength}}" placeholder="{{i.placeholder}}"  id="{{i.uid}}">
    <block wx:for="{{i.cn}}" wx:key="uid">
      <template is="{{xs.e(cid+1)}}" data="{{i:item,l:l}}" />
    </block>
  </van-field>
</template>
```

可以看到 `maxlength` 绑定了属性 `{{i.maxlength}}`，当开发者没有传递 `maxlength` 时，取 `undefined`，然后估计 `van-field` 中把 `undefined` 看作 `0`。

针对第三方组件，Taro 也不知道应该给什么默认值，否则可以这样绑定：`maxlength="{{i.maxlength||999999}}"`。

所以目前没有什么很好的办法，都设置 `maxlength` 属性是最方便的。

实在需要修改编译出来的模板 `dist/base.wxml`（比较复杂）：

1. 写一个 Taro 端平台插件，继承微信小程序插件
2. 修改 template 属性，覆盖继承的 `buildThirdPartyTemplate` 方法
3. 修改 `componentConfig.thirdPartyComponents` 中 `van-field` 的属性
