### ISSUE TITLE
vue子组件内能监听onPullDownRefresh吗

### ISSUE THREAD

**Issue by LiangFuzhi** [NervJS/taro#9551]
### 这个特性解决了什么问题？
vue子组件内能监听onPullDownRefres吗

### 这个 API 长什么样？
onPullDownRefresh () {
    console.log(111)
  },
  onReachBottom () {
    console.log(222)
  },

**Comment by Chen-jj** [comment]
组件里面目前只能使用 [事件中心](https://docs.taro.zone/docs/next/apis/about/events) 派发事件通知了。

**Comment by LiangFuzhi** [comment]
> 组件内部当前正在发生[事件中心](https://docs.taro.zone/docs/next/apis/about/events)派发事件通知了。

vue能支持usePullDownRefresh吗

**Comment by Chen-jj** [comment]
这是 React 的钩子 Hook，Vue 不能使用，之后会实现 Vue3 的 composition API 版本。

**Comment by LiangFuzhi** [comment]
那么只能大力出奇迹了

VueHook.js
```javascript
import { getCurrentInstance } from '@tarojs/taro'
function VueHook (Vue, options = {}) {
  Vue.mixin({
    mounted () {
      if (this.$children.length) {
        for (const key in getCurrentInstance().page) {
          if (/^on/.test(key)) {
            let fn = getCurrentInstance().page[key]
            getCurrentInstance().page[key] = () => {
              this.$children.forEach(element => {
                if (element.$options[key]) {
                  element.$options[key]()
                }
              })
              !this.$parent.tid && fn()
            }
          }
        }
      }
    }
  })
}

export default VueHook
```
app.js
```javascript
Vue.use(VueHook)
```

**Comment by LiangFuzhi** [comment]
> 那只能努力出奇迹了
> 
> VueHook.js
> 
> ```js
> import  {  getCurrentInstance  }  from  '@tarojs/taro'
> 函数 VueHook  ( Vue ,  options  =  { } )  { 
>   Vue . 混入（{
>     安装 （） {
>       如果 （这个。$孩子。长度） {
>         为 （const的 关键 在 getCurrentInstance （）。页） {
>           如果 （/ ^上/ . 测试（键）） {
>             让 fn  =  getCurrentInstance （）。页[键] 
>             getCurrentInstance ( ) 。页[键]  =  ( )  =>  {
>               这个. $儿童。forEach ( element  =>  { 
>                 if  ( element . $options [ key ] )  { 
>                   element .$options [ key ] ( ) 
>                 } 
>               } ) 
>               ！这个。$父母。tid  &&  fn ( ) 
>             } 
>           } 
>         } 
>       } 
>     } 
>   } ) 
> }
> 
> 导出 默认的 VueHook
> ```
> 
> 应用程序.js
> 
> ```js
> 视图。使用（VueHook ）
> ```

vue子组件就能正常使用小程序的生命周期了，例如onPullDownRefresh。

**Comment by LiangFuzhi** [comment]
> 那么只能大力出奇迹了
> 
> VueHook.js
> 
> ```js
> import { getCurrentInstance } from '@tarojs/taro'
> function VueHook (Vue, options = {}) {
>   Vue.mixin({
>     mounted () {
>       if (this.$children.length) {
>         for (const key in getCurrentInstance().page) {
>           if (/^on/.test(key)) {
>             let fn = getCurrentInstance().page[key]
>             getCurrentInstance().page[key] = () => {
>               this.$children.forEach(element => {
>                 if (element.$options[key]) {
>                   element.$options[key]()
>                 }
>               })
>               !this.$parent.tid && fn()
>             }
>           }
>         }
>       }
>     }
>   })
> }
> 
> export default VueHook
> ```
> 
> app.js
> 
> ```js
> Vue.use(VueHook)
> ```

vue子组件就能正常使用小程序的生命周期了，例如onPullDownRefresh。
