### ISSUE TITLE
分享出去的页面，打开后，点击分享没有触发onShareAppMessage方法

### ISSUE THREAD

**Issue by lllevi751x** [NervJS/taro#9553]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: Vue 3**

### 复现步骤
分享一个页面，打开分享的页面，点击右上角分享，没有触发onShareAppMessage方法

### 期望结果
onShareAppMessage 都能触发

### 实际结果
不能触发onShareAppMessage 

### 环境信息
```
Taro v3.2.9


  Taro CLI 3.2.9 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
```

**Comment by coder-xsy** [comment]
需要修改页面配置https://taro-docs.jd.com/taro/docs/react#onshareappmessage-object

**Comment by Breeze1114** [comment]
老哥，我想问一下，vue3怎么设置能点击右上角的分享啊，我方法写在哪都没用，用按钮触发分享也没办法触发那个分享事件

**Comment by Chen-jj** [comment]
@Breeze1114 上代码

**Comment by Wynnfan** [comment]
@Chen-jj 我想问下使用setup(){}  onShareAppMessage 怎么拿到setup里面定义的state

**Comment by GauharChan** [comment]
> @Chen-jj 我想问下使用setup(){} onShareAppMessage 怎么拿到setup里面定义的state

同问，是否onShareAppMessage只能通过option api来写？

**Comment by Chen-jj** [comment]
@lllevi751x 一般来说，设置 `onShareAppMessage` 的 options 即可分享。如果某些特殊写法没有被 Taro 嗅探到，导致分享按钮是灰的，那么页面配置中设置一下 `enableShareAppMessage: true` 就可以了。

![image](https://user-images.githubusercontent.com/11807297/142455800-c6c1eff6-7a03-4da0-8f7b-09be9329d4b6.png)

**Comment by Chen-jj** [comment]
> @Chen-jj 我想问下使用setup(){} onShareAppMessage 怎么拿到setup里面定义的state

@Wynnfan Options API 通过 `this.xxx` 就可以访问 setup 导出的 data，Vue 文档有写。

**Comment by Wynnfan** [comment]
> > @Chen-jj 我想问下使用setup(){} onShareAppMessage 怎么拿到setup里面定义的state
> 
> @Wynnfan Options API 通过 `this.xxx` 就可以访问 setup 导出的 data，Vue 文档有写。

我提了当天就实验出来了，setup里的状态可以用this在小程序分享函数里调用
