### ISSUE TITLE
百度小程序编译 事件bug

### ISSUE THREAD

**Issue by pokerII** [NervJS/taro#956]
**问题描述**
启用 beta版编译 swan 命名  点击事件通过bind 不能传递相关参数

**复现步骤**
[复现问题的步骤]
1.子组件 FilterBar
```js
 return (
        <Text onClick={this.props.onClick.bind(this, item.status)} className={`filter-item ${attrSyle}`} key={index}>{item.name}</Text>
      )
```

2.父组件 
```js
 <FilterBar order={this.state.status} onClick={this.getOrderStatus}/>
```
3.父组件执行函数 getOrderStatus
getOrderStatus (status) {
   console.log(status) // 打印结果为 下图
}

![image](https://user-images.githubusercontent.com/17977712/47646127-e73a8f80-dbad-11e8-84b4-006f5253075b.png)

为相关事件e详情，没有附带 bind的 item.status

**期望行为**

status 为子组件的 item.status的值

微信weapp编译正常

 - 操作系统: [Mac]
 - Taro 版本 [beta]
 - Taro-cli 版本 [beta]
 - 问题平台 [swan]

**Comment by pokerII** [comment]
你好 我更新了 版本为：canary 但是 目前百度小程序的  this 在父类中无法获取，如图：

![_37a9fbfa-e097-497e-83b4-e3064e75a752](https://user-images.githubusercontent.com/17977712/47706728-f4ff1c00-dc64-11e8-8c2e-27c7924076c5.png)

```js
  toggleDir (type, e) {
    if (type === 1) {
      this.setState({
        isOpen: !this.state.isOpen
      })
    } else if (type === 2) {
      this.setState({
        isOpen: false
      })
    } else {
      this.setState({
        isOpen: true
      })
    }
  }
```

type还是为 eventBase的值 ，期望为 this能够读取到 setState的函数方法

**Comment by pokerII** [comment]
版本号： 1.2.0-alpha.2  @luckyadam

**Comment by pokerII** [comment]
生命周期内的函数  this能正常获取， 就是自定义函数 不能获取

**Comment by pokerII** [comment]
@luckyadam  已经通过先调用组件内方法 在调用 props方法 解决。 请知悉

**Comment by luckyadam** [comment]
@pokerII  1.1.0-beta.14 支持了，alpha 版本不行

**Comment by pokerII** [comment]
好的  了解 @luckyadam
