### ISSUE TITLE
taro引入svg-sprite-loader后编译h5运行的html中未生成symbol，svg图片不显示。

### ISSUE THREAD

**Issue by luoyu-china** [NervJS/taro#9569]
### 相关平台
H5

**浏览器版本: Chrome**
**使用框架: React**

### 复现步骤
1、安装 npm i svg-sprite-loader -D；
2、配置config/index.js
      //svg图片目录： ../src/images/icons
       webpackChain(chain) {
      chain.merge({
        module: {
          rule: {
            svgloader: {
              test: /\.svg$/,
              include: [path.resolve(__dirname, '../src/images/icons')],
              use: [
                {
                  loader: 'svg-sprite-loader',
                  options: {},
                },
                {
                  loader: 'svgo-loader',
                  options: {},
                },
              ],
            },
          },
        },
      });
    },
    imageUrlLoaderOption: {
      limit: 5000,
      exclude: [path.resolve(__dirname, '../src/images/icons')],
      name: 'static/images/[name].[hash:8].[ext]',
    },
3、在app.jsx中引入svg文件：
      const importAll = (requireContext) => requireContext.keys().forEach(requireContext);
      importAll(require.context('@/images/icons', false, /\.svg$/));
4、svg组件：
      import React from 'react';
      import './index.scss';

      function SvgIcon(props) {
         return (
           <svg className={'theIcon '   (props.className ? props.className : '')}>
               <use xlinkHref={'#'   props.name} />
           </svg>
        );
      }
     export default SvgIcon;
5、使用svg组件：
      import SvgIcon from '@/components/SvgIcon';
      <SvgIcon name={"svgName"} className="svgIcon"}/>
6、编译h5版本并运行

### 期望结果
svg图片可以显示

### 实际结果
svg图片未显示，html中未生成雪碧图的symbol标签

### 环境信息
```
Taro CLI 3.0.28 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3 - C:\ProgramFiles\NodeJs\node.EXE
      npm: 6.14.6 - C:\ProgramFiles\NodeJs\npm.CMD
```

---
### 补充信息
https://github.com/NervJS/taro-issue-helper/issues/13
https://github.com/NervJS/taro/issues/9566

**Comment by ZakaryCode** [comment]
这里配置有点问题，由于 Taro 中配置了图片加载，所以除了 svg-loader 以外，需要更新 image-loader，参考配置如下:

```js
// ...
    webpackChain(chain) {
      chain.merge({
        module: {
          rule: {
            'image': {
              test: /\.(png|jpe?g|gif|bpm|webp)(\?.*)?$/,
              use: [
                {
                  loader: 'url-loader',
                  options: {
                    name: path.resolve(__dirname, 'images/[name].[ext]'),
                  },
                },
              ],
            },
            'svg-loader': {
              test: /.svg$/,
              use: [
                {
                  loader: 'svg-sprite-loader',
                  options: {},
                },
                {
                  loader: 'svgo-loader',
                  options: {},
                },
              ],
            },
          },
        },
      });
    },
    imageUrlLoaderOption: {
      limit: 5000,
      exclude: [path.resolve(__dirname, '../src/images/icons')],
      name: 'static/images/[name].[hash:8].[ext]',
    }
// ...
```

另外使用 `svg-sprite-loader` 依旧需要引入图片，避免被 tree shaking 抖动掉，可以在 SvgIcon 中动态导入:

```tsx
import React from "react"

import('@/images/icons/svgName.svg')

function SvgIcon(props) {
  return (
    <svg className={"theIcon " + (props.className ? props.className : "")}>
      <use xlinkHref={"#" + props.name} />
    </svg>
  );
}
export default SvgIcon
```
