### ISSUE TITLE
H5开启下拉刷新后页面无法向上滚动

### ISSUE THREAD

**Issue by tutuxxx** [NervJS/taro#9577]
### 相关平台
H5

**浏览器版本: 安卓 微信**
**使用框架: React**

### 复现步骤
1、taro init项目
2、index.config.js增加enablePullDownRefresh: true开启下拉刷新
3、增加页面内容使页面可滚动
4、npm run dev:h5
4、打开h5页面，向下滚动
5、此时无法向上滚动

### 期望结果
正常滑动

### 实际结果
向下滑动后无法再向上滑动

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: macOS High Sierra 10.13.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.10 => 3.2.10 
      @tarojs/mini-runner: 3.2.10 => 3.2.10 
      @tarojs/react: 3.2.10 => 3.2.10 
      @tarojs/runtime: 3.2.10 => 3.2.10 
      @tarojs/taro: 3.2.10 => 3.2.10 
      @tarojs/webpack-runner: 3.2.10 => 3.2.10 
      babel-preset-taro: 3.2.10 => 3.2.10 
      eslint-config-taro: 3.2.10 => 3.2.10 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 3.8.3
```

**Comment by Chen-jj** [comment]
@tutuxxx 试了一下没有什么问题。可以升级到最新版本再试试。还有问题的话提供一下 demo 咯，只靠描述还是不好复现。

**Comment by styugege** [comment]
同样遇到了这个问题，小程序端没问题，打包成H5下拉就没反应，事件也触发不了

**Comment by guo897654050** [comment]
是有这个问题，编译成h5下滑，再上划出发了上拉刷新，且无法取消

**Comment by soakit** [comment]
@tutuxxx @styugege @guo897654050 你们也太懒了吧，要人解决问题。也不给个复现项目。

**Comment by soakit** [comment]
开issue的链接挂了。借这个issue补充信息

**Comment by soakit** [comment]
## 相关平台
H5

浏览器版本: 安卓/chrome浏览器，safari浏览器
使用框架: React

## 复现仓库
https://github.com/soakit/taro-demo/tree/fix-pullrefresh3.4.1

## 复现链接
https://soakit.github.io/taro-demo/3.4.1/#/pages/demo/index

## 复现步骤
1、taro init项目
2、demo/index.config.js增加enablePullDownRefresh: true开启下拉刷新
3、增加页面内容使页面可滚动
4、npm run build:h5
4、打开h5页面，向下滚动
5、此时无法向上滚动，**chrome模拟是正常的，真机上无法滑动**

## 期望结果
正常滑动

## 实际结果
向下滑动后无法再向上滑动

## 环境信息
```shell


👽 Taro v3.4.1


  Taro CLI 3.4.1 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    npmPackages:
      @tarojs/components: 3.4.1 => 3.4.1 
      @tarojs/mini-runner: 3.4.1 => 3.4.1 
      @tarojs/react: 3.4.1 => 3.4.1 
      @tarojs/runtime: 3.4.1 => 3.4.1 
      @tarojs/taro: 3.4.1 => 3.4.1 
      @tarojs/webpack-runner: 3.4.1 => 3.4.1 
      babel-preset-taro: 3.4.1 => 3.4.1 
      eslint-config-taro: 3.4.1 => 3.4.1 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.4.4
```

## 补充信息

试过`3.3.x`的版本也有问题, 如`3.3.11`, `3.3.20`

**Comment by soakit** [comment]
> ## 相关平台
> H5
> 
> 浏览器版本: 安卓/chrome浏览器，safari浏览器 使用框架: React
> 
> ## 复现仓库
> https://github.com/soakit/taro-demo/tree/fix-pullrefresh3.4.1
> 
> ## 复现链接
> https://soakit.github.io/taro-demo/3.4.1/#/pages/demo/index
> 
> ## 复现步骤
> 1、taro init项目 2、demo/index.config.js增加enablePullDownRefresh: true开启下拉刷新 3、增加页面内容使页面可滚动 4、npm run build:h5 4、打开h5页面，向下滚动 5、此时无法向上滚动，**chrome模拟是正常的，真机上无法滑动**
> 
> ## 期望结果
> 正常滑动
> 
> ## 实际结果
> 向下滑动后无法再向上滑动
> 
> ## 环境信息
> ```shell
> 👽 Taro v3.4.1
> 
> 
>   Taro CLI 3.4.1 environment info:
>     System:
>       OS: macOS 11.0.1
>       Shell: 5.8 - /bin/zsh
>     Binaries:
>       Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
>       Yarn: 1.22.4 - ~/.yarn/bin/yarn
>       npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
>     npmPackages:
>       @tarojs/components: 3.4.1 => 3.4.1 
>       @tarojs/mini-runner: 3.4.1 => 3.4.1 
>       @tarojs/react: 3.4.1 => 3.4.1 
>       @tarojs/runtime: 3.4.1 => 3.4.1 
>       @tarojs/taro: 3.4.1 => 3.4.1 
>       @tarojs/webpack-runner: 3.4.1 => 3.4.1 
>       babel-preset-taro: 3.4.1 => 3.4.1 
>       eslint-config-taro: 3.4.1 => 3.4.1 
>       react: ^17.0.0 => 17.0.2 
>     npmGlobalPackages:
>       typescript: 4.4.4
> ```
> 
> ## 补充信息
> 试过`3.3.x`的版本也有问题, 如`3.3.11`, `3.3.20`

@Chen-jj

**Comment by soakit** [comment]
造成此原因就是因为这个[code](https://github.com/NervJS/taro/blob/054e4db574a5b52b3771e6798b5f1815c8200523/packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx#L60)写死的。
用这个来判定是否在顶部(scrollTop是否为0)。

**Comment by explorefit** [comment]
> 

请问一下这个无法上滚，需要修改源码吗？

**Comment by explorefit** [comment]
> 造成此原因就是因为这个[code](https://github.com/NervJS/taro/blob/054e4db574a5b52b3771e6798b5f1815c8200523/packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx#L60)写死的。 用这个来判定是否在顶部(scrollTop是否为0)。

请问一下这个无法上滚，需要修改源码吗？

**Comment by explorefit** [comment]
> 造成此原因就是因为这个[code](https://github.com/NervJS/taro/blob/054e4db574a5b52b3771e6798b5f1815c8200523/packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx#L60)写死的。 用这个来判定是否在顶部(scrollTop是否为0)。

我用的最新版的 3.4.1 ，在h5中还是存在这个问题

**Comment by soakit** [comment]
> > 造成此原因就是因为这个[code](https://github.com/NervJS/taro/blob/054e4db574a5b52b3771e6798b5f1815c8200523/packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx#L60)写死的。 用这个来判定是否在顶部(scrollTop是否为0)。
> 
> 我用的最新版的 3.4.1 ，在h5中还是存在这个问题

是的，一直存在的问题。我也开了个新issue。

**Comment by explorefit** [comment]
> > > 造成此原因就是因为这个[code](https://github.com/NervJS/taro/blob/054e4db574a5b52b3771e6798b5f1815c8200523/packages/taro-components/src/components/pull-to-refresh/pull-to-refresh.tsx#L60)写死的。 用这个来判定是否在顶部(scrollTop是否为0)。
> > 
> > 
> > 请问一下这个无法上滚，需要修改源码吗？
> 
> 是的，目前taro的实现方案是有问题的。有tabbar是基于tab panel的滚动条。无tabbar时是body的滚动条。这样的外层的滚动没有问题。 但用局部的滚动条就会有无法向上滚动的问题。还是禁用掉taro h5下拉刷新吧，自己动手实现或者另辟蹊径。

谢谢你了，我现在先把下拉刷新禁掉了，后面对不同端做不同的刷新策略
