### ISSUE TITLE
请问下多久支持page-container这个标签呢

### ISSUE THREAD

**Issue by abner-forever** [NervJS/taro#9580]
### 这个特性解决了什么问题？
支持原生微信小程序page-container的功能

### 这个 API 长什么样？
支持原生微信小程序page-container的功能

**Comment by Chen-jj** [comment]
@abner-jlm 可以用吧：https://github.com/NervJS/taro/issues/9182

**Comment by young-ren** [comment]
> @abner-jlm 可以用吧：#9182

3.2.13版本没有这个组件呢

**Comment by abner-jlm** [comment]
> @abner-jlm 可以用吧：#9182

最新的版本的代码里没有这个组件，虽然在代码中能引入渲染出来但是监听的方法都没生效

这个问题里面有贡献支持，但是代码没有构建成功 https://github.com/NervJS/taro/pull/9025

**Comment by guoguozhang** [comment]
这是不维护了吗，半年了都没动静。。。

**Comment by Chen-jj** [comment]
PageContainer 可以正常使用（3.3.19）：

```js
import { Component } from "react";
import { View, Button, PageContainer } from "@tarojs/components";

export default class Index extends Component {
  state = {
    isShow: false
  }

  handleClick = () => {
    this.setState({
      isShow: !this.state.isShow
    })
  }

  render() {
    return (
      <View>
        <PageContainer show={this.state.isShow} onClickOverlay={this.handleClick}>
          <View style='height: 200px'>
            page-container
          </View>
        </PageContainer>
        <Button onClick={this.handleClick}>toggle</Button>
      </View>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/11807297/148173986-7f6dc391-3d56-4a52-85ae-ffd845666ce5.png)

**Comment by senyawang** [comment]
onAfterLeave ,   onBeforeLeave  这些事件都无法触发，这个有解决文案吗
