### ISSUE TITLE
Taro2 什么时候支持可选链和空值运算符

### ISSUE THREAD

**Issue by lupingW** [NervJS/taro#9581]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/didi/mpx](https://github.com/didi/mpx)
**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
无

### 期望结果
支持

### 实际结果
不支持

### 环境信息
```
👽 Taro v3.1.4


  Taro CLI 3.1.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD  
```

**Comment by durongzhang** [comment]
要babel7才支持，taro2是babel6

**Comment by lupingW** [comment]
> 要babel7才支持，taro2是babel6

这个我知道 我想我问的是能不能实现 taro2 用babel7

**Comment by Chen-jj** [comment]
Taro2 不考虑迭代新功能了。
