### ISSUE TITLE
Taro写的三方库组件无法按照平台引用

### ISSUE THREAD

**Issue by yangqi1024** [NervJS/taro#9584]
### 这个特性解决了什么问题？
基于Taro写了一个组件库，有的组件使用index.rn.tsx作为平台区分入口，但是通过npm依赖后,发现项目中Rn并没有按照index.rn.tsx去加载，加载的依旧是index.tsx，导致编译报错，请问有解决方案吗

### 这个 API 长什么样？
希望能正确按照平台引用

**Comment by shinken008** [comment]
已经支持，增加配置：
```js
// config/index.js
rn: {
    resolve: {
      include: ['taro-ui']
    }
  }
```

**Comment by shinken008** [comment]
查看文档：https://taro-docs.jd.com/taro/docs/envs#%E8%AE%A9-node_modules-%E4%B8%AD%E7%9A%84%E4%BE%9D%E8%B5%96%E4%B9%9F%E8%83%BD%E8%A7%A3%E6%9E%90%E5%A4%9A%E7%AB%AF%E6%96%87%E4%BB%B6
