### ISSUE TITLE
3.x版本小程序插件开发Taro API挂载异常

### ISSUE THREAD

**Issue by Jinchengawu** [NervJS/taro#9587]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Jinchengawu/Bug-issues.git](https://github.com/Jinchengawu/Bug-issues.git)
**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
你好，我做过以下测试；demo 就直接 用 taro/cli 创建 小程序插件工程即可；未做其他改动；

————————————

Taro 3.1.x 版本 ：无法启动报错如下：
![image](https://user-images.githubusercontent.com/26629063/123036090-0bae9e80-d41f-11eb-90ae-39c48c6d942c.png)

————————————

Taro 3.2.x版本 ：在 编译并不报错 但 plugin 目录，Taro 挂在 wx api 失败；但编译并不报错
![image](https://user-images.githubusercontent.com/26629063/123036135-22ed8c00-d41f-11eb-8ae3-9d4c7821a959.png)

![image](https://user-images.githubusercontent.com/26629063/123036155-2d0f8a80-d41f-11eb-96b2-d8bceac0d490.png)

————————————

Taro 3.3.0-beta.0版本 ：同样 编译并不报错 但 在 plugin 目录下，Taro 挂在 wx api 失败；

————————————
依赖附加：

### 期望结果
可以在taro3.x框架基础上 正常开发 微信小程序插件

### 实际结果
taro3.x框架基础上 无法正常开发 微信小程序插件

### 环境信息
```
👽 Taro v3.3.0-beta.0

  Taro CLI 3.3.0-beta.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.0-beta.0 => 3.3.0-beta.0 
      @tarojs/mini-runner: 3.3.0-beta.0 => 3.3.0-beta.0 
      @tarojs/react: 3.3.0-beta.0 => 3.3.0-beta.0 
      @tarojs/runtime: 3.3.0-beta.0 => 3.3.0-beta.0 
      @tarojs/taro: 3.3.0-beta.0 => 3.3.0-beta.0 
      @tarojs/webpack-runner: 3.3.0-beta.0 => 3.3.0-beta.0 
      babel-preset-taro: 3.3.0-beta.0 => 3.3.0-beta.0 
      eslint-config-taro: 3.3.0-beta.0 => 3.3.0-beta.0 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 3.9.2
```

**Comment by Jinchengawu** [comment]
相关issues： https://github.com/NervJS/taro/issues/9457

**Comment by zjl724** [comment]
哪个版本修复了这个问题啊??

**Comment by zjl724** [comment]
> 相关问题：#9457

3.2.11 版本说是修复了这个问题, 但是我这边用3.2.11也还是不行的, 确定修复了吗?? 
![image](https://user-images.githubusercontent.com/61836400/123091881-703c1e80-d45c-11eb-8c3b-467aa1b919d3.png)
![image](https://user-images.githubusercontent.com/61836400/123091943-834eee80-d45c-11eb-9ba3-cece584fd9ce.png)
![image](https://user-images.githubusercontent.com/61836400/123091987-91047400-d45c-11eb-9778-222d5da5547c.png)

**Comment by Jinchengawu** [comment]
> > 相关问题：#9457
> 
> 3.2.11 版本说是修复了这个问题, 但是我这边用3.2.11也还是不行的, 确定修复了吗??
> ![image](https://user-images.githubusercontent.com/61836400/123091881-703c1e80-d45c-11eb-8c3b-467aa1b919d3.png)
> ![image](https://user-images.githubusercontent.com/61836400/123091943-834eee80-d45c-11eb-9ba3-cece584fd9ce.png)
> ![image](https://user-images.githubusercontent.com/61836400/123091987-91047400-d45c-11eb-9778-222d5da5547c.png)
3.3.0-beta.0 也还是会有这个问题

**Comment by zjl724** [comment]
可以通过wx.showLoading()试一下,我试了可以的

**Comment by Chen-jj** [comment]
可以先用 `wx.` 代替 `Taro.`

**Comment by Jinchengawu** [comment]
> 可以先用 `wx.` 代替 `Taro.`



> 可以通过wx.showLoading()试一下,我试了可以的

我知道是可以的，我的截图中有用wx.req api去测试，
但问题是：
1.会不会有其他的意外
2.今后Taro支持了wx相关的api需要翻工

还是希望尽快修复这个问题

**Comment by MicrosoftCore** [comment]
同样遇到此问题，还有一堆其他问题

**Comment by xk691642396** [comment]
我用最新的3.3.0 也还是不行

**Comment by smackgg** [comment]
@Chen-jj 这个有计划什么时候修复么~ https://github.com/NervJS/taro-plugin-platform-kwai/issues/6
