### ISSUE TITLE
切换到 dart-sass

### ISSUE THREAD

**Issue by TomVista** [NervJS/taro#9594]
### 这个特性解决了什么问题？
解决node-sass 安装问题,不止是网络环境,python,node-gyp 都影响项目依赖安装

dart-sass 可以无痛切换过去

### 这个 API 长什么样？
dart-sass

**Comment by 17** [comment]
最新的 https://github.com/NervJS/taro/commit/edee0b2f008faa5298bf31ec9023a17cd957c350 已使用 dart-sass 。
切换到最新版本即可
