### ISSUE TITLE
setState的回调中再次设置一次setState，此时打印this.state.xxx为undefined

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#9599]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/fanlvwen/demo/blob/main/setState%20err](https://github.com/fanlvwen/demo/blob/main/setState%20err)
**小程序基础库: 1.24.10**
**使用框架: Nerv**

### 复现步骤
重现链接中的代码直接运行 npm run dev:alipay 即可复现 打印皆为undefined

注释掉996行的第一个setState，打印正常

### 期望结果
多次setState能正常打印

### 实际结果
多次setState打印undefined

### 环境信息
```
Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - D:\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\user\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - D:\nodejs\npm.CMD
```

**Comment by fanlvwen** [comment]
![image](https://user-images.githubusercontent.com/36951996/123252252-a9d55e00-d51e-11eb-9337-72c636bd69e8.png)
![image](https://user-images.githubusercontent.com/36951996/123252359-c6719600-d51e-11eb-87b4-abcb2a3ce8c4.png)

**Comment by Chen-jj** [comment]
@fanlvwen 是 nervjs 的问题，React 没有这个问题。

nervjs 不够人力维护了，建议换成 React 吧。

**Comment by fanlvwen** [comment]
@Chen-jj 定位到问题了，还是nervjs的原因，将framework换成react就好了 这个 #9597 也是同样的问题，我切到react上就好了
