### ISSUE TITLE
请问taro有没有类似于vue里的mixins混入的功能吗？

### ISSUE THREAD

**Issue by yzw2017** [NervJS/taro#960]
小程序如果没有授权的情况下:
    经常会再不同页面点击按钮授权登录什么的，一套共有的一套代码逻辑，不知道react或者taro有没有像
   Vue里面的mixins功能，在不同组件注入相同的方法

**Comment by luckyadam** [comment]
可以写一个页面基类，然后继承

**Comment by yuche** [comment]
或者你可以写一个装饰器，像 redux 的 connect 和 taro-apollo 一样

**Comment by cmideal** [comment]
> 可以写一个页面基类，然后继承

这样写的话，同名方法会覆盖  
componentDidMount
这个只在子组建有执行，请问，比如我想两个都执行，需要怎么写呢

**Comment by luckyadam** [comment]
类继承
`super. componentDidMount()`  调用父类方法

**Comment by shenhailong** [comment]
> 可以写一个页面基类，然后继承

用的ts，怎么能保证eslint，不报错，比如基类写了一个方法，调用会提示：...上不存在属性..
