### ISSUE TITLE
微信小程序自定义tabBar栏，首次点击tab触发会导致tabBar栏的组件刷新，使判断高亮错误

### ISSUE THREAD

**Issue by HPLWC** [NervJS/taro#9600]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/HPLWC/taro_issue](https://github.com/HPLWC/taro_issue)
**小程序基础库: 2.16.1**
**使用框架: Vue 3**

### 复现步骤
编译后点击tab栏即可复现

### 期望结果
点击后不触发tabBar的刷新或者高亮判断正确

### 实际结果
点击tab会触发tabBar栏刷新

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.18.3
      Yarn: 1.22.5 
      npm: 6.14.6

```

**Comment by HPLWC** [comment]
是在tabbar页面重新渲染聚焦，之前理解错了

**Comment by ZeroJsus** [comment]
> 是在tabbar页面重新渲染聚焦，之前理解错了

遇到了一样的问题 有没有办法处理呢 每个tab标签页面进去 都会触发一次 自定义tabbar页面的重新渲染
