### ISSUE TITLE
Fixed position 导致的 ScrollView 滚动问题

### ISSUE THREAD

**Issue by WillGoh** [NervJS/taro#9602]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/WillGoh/taro-example](https://github.com/WillGoh/taro-example)
**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
1. 页面中初始化一个 scrollView 组件，scrollY 为 true, 并设置它的宽，高分别为 100vw 100vh
2. scrollView 设置一些子元素，使内容高度高于屏幕，并在最后位置设置一个按钮（并不一定要最后，只需要其位置相对靠后即可）
3. scrollView 同层级再设置一个 View 组件 A，它的 position 为 fixed，宽、高随意，只要能够看到它即可。
4. 设置一个变量来控制 A 的显隐，点击按钮即可显示 A，点击 A 本身使其消失。
5. 当点击 A 消失后，scrollView 会失去原本滚动的位置，回到最顶部。

### 期望结果
当 A 消失时，scrollView 滚动位置不变。

### 实际结果
当 A 消失时，scrollView 会滚动到顶部。

### 环境信息
```
Taro CLI 3.2.11 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.11 => 3.2.11 
      @tarojs/mini-runner: 3.2.11 => 3.2.11 
      @tarojs/react: 3.2.11 => 3.2.11 
      @tarojs/runtime: 3.2.11 => 3.2.11 
      @tarojs/taro: 3.2.11 => 3.2.11 
      @tarojs/webpack-runner: 3.2.11 => 3.2.11 
      babel-preset-taro: 3.2.11 => 3.2.11 
      eslint-config-taro: 3.2.11 => 3.2.11 
      react: ^17.0.0 => 17.0.2 
    npmGlobalPackages:
      typescript: 4.3.2
```

**Comment by ZakaryCode** [comment]
这个和定位没关系哈，参考 #8466 的答复

**Comment by MoveZZG** [comment]
不幸的是，如果你在惯性滚动过程中操作了data🌝🌝，列表就被强拉回来，因为他会更新当前srollTop值，即使列表还在滚动。
为什么不想设置一些属性，taro也要给他初始值呢。

**Comment by Chen-jj** [comment]
> 不幸的是，如果你在惯性滚动过程中操作了data🌝🌝，列表就被强拉回来，因为他会更新当前srollTop值，即使列表还在滚动。
> 为什么不想设置一些属性，taro也要给他初始值呢。

这是运行时框架的弊端，不像 Taro 1/2 或其它编译时框架，可以通过 AST 分析出开发者使用了什么属性，然后编译出对应的 xml 模板。

Taro 3 不知道开发者需要什么属性，小程序的 xml 又需要提前写死，没有动态操作 DOM 的方法。所以只能把属性全都列出来。

至于为什么有些熟悉要给初始值，可能是因为传入 `undefined` 时会产生 bug。

**Comment by felix9ia** [comment]
> 不幸的是，如果你在惯性滚动过程中操作了data🌝🌝，列表就被强拉回来，因为他会更新当前srollTop值，即使列表还在滚动。 为什么不想设置一些属性，taro也要给他初始值呢。

@MoveZZG  我也遇到了这个问题，你最后是怎么解决这个问题的？
