### ISSUE TITLE
使用vue3 setup语法时，build之后不能识别canvas，且原生组件传参为空

### ISSUE THREAD

**Issue by valkia** [NervJS/taro#9603]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/valkia/taro-demo](https://github.com/valkia/taro-demo)
**小程序基础库: 2.17.3**
**使用框架: Vue 3**

### 复现步骤
```
<script setup>

</script>
```
使用setup语法，build之后无法识别canvas，且使用原生组件传参为空
```
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_canvas` not found.
  227 |   
  228 | <template name="tmpl_2_container">
> 229 |   <template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}" />
      |                ^
  230 | </template>
  231 | 
  232 | <template name="tmpl_3_catch-view">
```

### 期望结果
build之后可以识别canvas。
使用原生组件正确传值

### 实际结果
build之后无法识别canvas。
原生组件传值为空

### 环境信息
```
  Taro CLI 3.2.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
      Yarn: D:\wildrift\demo>"node"  "C:\Users\du\AppData\Roaming\npm\\node_modules\yarn\bin\yarn.js" -v
1.22.4 - C:\Users\du\AppData\Roaming\npm\yarn.CMD
      npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD

```

---
### 补充信息
尝试之后。使用setup语法就会出现该情况，不使用setup可以正常使用

**Comment by Chen-jj** [comment]
@valkia 没有复现，升级到最新版再试试

![image](https://user-images.githubusercontent.com/11807297/124853584-b060dc80-dfd8-11eb-8c4b-b2a392a950c1.png)

![image](https://user-images.githubusercontent.com/11807297/124853595-b5259080-dfd8-11eb-9675-c73c7baf8055.png)
