### ISSUE TITLE
使用ref的render三元判断显示自定义组件会报错

### ISSUE THREAD

**Issue by Aaminly** [NervJS/taro#961]
**问题描述**
使用ref的render三元判断显示自定义组件会报错：

![image](https://user-images.githubusercontent.com/28622560/47694213-a6875880-dc37-11e8-9612-a7b2f7f73c3c.png)
```js
// 这里可以贴代码
render() {
    const { tableType } = this.state;
    return (
      <View>
        {tableType === "teacher" ? (
          <Calendar ref="calendar" />
        ) : (
          <AdminTimeTable />
        )}
      </View>
    );
  }
```

**期望行为**
根据 state tableType值判断显示不同组件。

**报错信息**
![image](https://user-images.githubusercontent.com/28622560/47694230-bf900980-dc37-11e8-9956-0f366844b37f.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.1.0.7]
 - Node.js 版本 [e.g. v10.3.0]
 - 报错平台 [weapp]

**Comment by Chen-jj** [comment]
#1009

**Comment by Chen-jj** [comment]
最新版已解决，可以升级后试试
