### ISSUE TITLE
使用Editor组件修改format会失去焦点问题，官网上说“使用 catchtouchend 绑定事件则不会使编辑器失去焦点(2.8.3)”，请问在Taro里怎么模拟catchtouchend

### ISSUE THREAD

**Issue by collinsyu** [NervJS/taro#9615]
### 这个特性解决了什么问题？
使用Editor组件修改format会失去焦点问题，官网上说“使用 catchtouchend 绑定事件则不会使编辑器失去焦点(2.8.3)”，请问在Taro里怎么模拟catchtouchend

### 这个 API 长什么样？
支持catchtouchend 这个api或者可以模拟

**Comment by Chen-jj** [comment]
@collinsyu 使用 [taro-plugin-inject](https://github.com/NervJS/taro-plugin-inject) 注入这个事件试试，大概是这样：

```js
const config = {
  plugins: [
    ['@tarojs/plugin-inject', {
      components: {
        Editor: {
          'catchtouchend': "'eh'"
        }
      }
    }]
  ]
}
```

**Comment by wzs28150** [comment]
小程序的editor 
![image](https://user-images.githubusercontent.com/21290257/126608020-0187c9b7-7b55-4f34-a76a-33607a09a3f2.png)
是通过点击设置的按钮来控制编辑里面文字的样式的。catchtouchend是设置在按钮上的 。设置在editor上没有什么用啊。
这是官方的demo
![image](https://user-images.githubusercontent.com/21290257/126608244-353b0122-79e5-4bc4-b739-ea9dbb753f8f.png)
https://developers.weixin.qq.com/s/W7uZ3EmU7jbl

**Comment by bb-bin** [comment]
方法是加上去了。在vue3里面怎么去触发catchtouchend呢。

**Comment by bb-bin** [comment]
方法是加上去了。在vue3里面怎么去触发catchtouchend呢。是使用@catchtouchend="format"，还是直接catchtouchend="format"

**Comment by Tomortec** [comment]
用**自定义组件**似乎能行，我不知道为什么，用`@tarojs/plugin-inject`在我的环境里面没用

### 自定义组件：
```html
<view class="catchable-view" catchtouchend="onTouchEnd">
    <slot></slot>
</view>
```

```js
Component({
    properties: {
        handleTouchEnd: {
            type: Object,
        }
    },
    methods: {
        onTouchEnd(e) {
            this.properties.handleTouchEnd.handler(e)
        }
    }
})
```

如果要声明的话
```ts
declare global {
    namespace JSX {
        interface IntrinsicElements {
            "catchable-view": {
                children?: React.ReactNode;
                handleTouchEnd: {
                    handler: (e: any) => void;
                }
            }
        }
    }
}
```
