### ISSUE TITLE
快手小程序无法使用taro

### ISSUE THREAD

**Issue by TomVista** [NervJS/taro#9616]
### 这个特性解决了什么问题？
https://developers.kuaishou.com/topic/709

修改node.cn ,快手template 不更新

### 这个 API 长什么样？
taro能不能帮忙沟通一下快手,解决这个问题

**Comment by Chen-jj** [comment]
是使用快手小程序插件编译吗？

**Comment by fanlvwen** [comment]
> 是使用快手小程序插件编译吗？

大佬帮忙看一下，taro2升3遇到的两个棘手问题
https://github.com/NervJS/taro/issues/9597
https://github.com/NervJS/taro/issues/9599

**Comment by TomVista** [comment]
@Chen-jj 

不是NervJS下面的那个,那个跑不起来,用的[vadxq/taro-plugin-platform-ks](https://github.com/vadxq/taro-plugin-platform-ks)

在快手上, setData 只能更新 新增的元素 ,旧元素不更新, 是快手template的原因,不是taro的缘故,

**Comment by Chen-jj** [comment]
@TomVista 刚关注到这个插件，我们尽快跟进下

**Comment by Chen-jj** [comment]
@fanlvwen 我们看看的

**Comment by TomVista** [comment]
复现仓库
[taro-ks](https://github.com/TomVista/taro-ks) taro 快手
[ks-test](https://github.com/TomVista/ks-test) 原生快手小程序

**Comment by vadxq** [comment]
你好，目前使用复现仓库暂未发现不能变更～目前复现使用的是taro-plugin-platform-ks
[v1.3.0](https://www.npmjs.com/package/taro-plugin-platform-ks/v/1.3.0) /快手开发者工具v1.4.0
![image](https://user-images.githubusercontent.com/18227775/130402161-85507544-9372-4258-b1a0-0443fe8d2c3c.png)
![image](https://user-images.githubusercontent.com/18227775/130402129-c2a2c4c4-1393-4675-aad6-d4dd2b0d7bf1.png)
![image](https://user-images.githubusercontent.com/18227775/130402151-ea5c0c91-3722-4983-9332-14409f6b9bef.png)

**Comment by TomVista** [comment]
@vadxq  观察下dbug 的ksml ,虽然文字变了,但是 元素没有变 text-》button

**Comment by vadxq** [comment]
@TomVista 好哒～了解了！目前vue的v-if这一块快手那边支持，react这类变量显隐逻辑的确实不支持。
快手官方回复说可能是template使用方式改了。
![image](https://user-images.githubusercontent.com/18227775/130413971-6f06428a-b435-446a-8057-9ba0a25ee79c.png)

我再研究看看有没有其他方法可以解决react这个问题。如果项目急可以先使用vue3

**Comment by mrzzcn** [comment]
@TomVista 快手小程序能跑起来吗？我新建空白仓库直接不加载，一片空白

**Comment by TomVista** [comment]
@mrzzcn 没问题的,先用这个仓库吧, vadxq/taro-plugin-platform-ks
