### ISSUE TITLE
编译成支付宝小程序后 swiper组件前后出现空白页

### ISSUE THREAD

**Issue by pangcongcong** [NervJS/taro#9618]
### 相关平台
支付宝小程序

**小程序基础库: 1.0.0**
**使用框架: Vue 3**`
`
### 复现步骤
`<swiper
        :current="bannerIndex"
        :autoplay="true"
        interval="5000"
        duration="700"
        :circular="false"
        class="banners-swiper"
        @change="bannerChange"
      >
        <swiper-item
          v-for="(banner, index) in infoItem"
          class="swiper-item"
          :key="'swiper-item-' +index"
        >
          <image
            class="banners-image"
            :src="banner.image"
          >
          </image>
        </swiper-item>
      </swiper>`

### 期望结果
数组接口获取 一共6个，期望生成6个swiper-item

### 实际结果
前后各有一张空白swiper-item，一共8个

### 环境信息
```
Taro CLI 3.2.2-beta.0 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^3.2.13 => 3.2.13
      @tarojs/mini-runner: ^3.2.2-beta.0 => 3.2.13
      @tarojs/plugin-platform-alipay: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-jd: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-qq: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-swan: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-tt: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-weapp: ^3.2.12 => 3.2.13
      @tarojs/runtime: ^3.2.2-beta.0 => 3.2.13
      @tarojs/taro: ^3.2.2-beta.0 => 3.2.13
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
```

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/123727708-a2b6a300-d8c4-11eb-8dbd-0478a64ad4aa.png)
CLI 和项目依赖统一升级到最新版本试试

**Comment by pangcongcong** [comment]
> ![image](https://user-images.githubusercontent.com/1782542/123727708-a2b6a300-d8c4-11eb-8dbd-0478a64ad4aa.png)
> CLI 和项目依赖统一升级到最新版本试试

目前就是最新版的～ 是不是@taro/components包里swiper版本太低导致的？swiper官方现在是6.7+

**Comment by Chen-jj** [comment]
@pangcongcong 提供一下 demo？

**Comment by honlyHuang** [comment]
> @pangcongcong 提供一下 demo？

https://github.com/pangcongcong/demo/blob/main/taro-swiper.vue
