### ISSUE TITLE
默认回退、navigateBack，A进入B， B 进入C， C回退到B，在回退到A，再次进入到B，在进入C，在回退B的onshow就不会触发了。除了第一次以外，以后都不会触发onshow钩子。

### ISSUE THREAD

**Issue by liushengxuyanyu** [NervJS/taro#9622]
### 相关平台
支付宝小程序

**小程序基础库: 2.1.9**
**使用框架: Vue 3**

### 复现步骤
试了下vue2 下没问题。在vue3中有问题。
```
// A页面
methods: {
    goMine() {
      Taro.navigateTo({
        url: `../mine/index?t=${Date.now}`
      })
    }
  }

 B页面
created() {
    console.log('我的 created:')
  },
  onShow() {
    console.log('我的 onshow:')
  },
  beforeUnmount() {
    console.log('---- 我的beforeUnmount ----')
  },
  methods: {
    goCart() {
      Taro.navigateTo({
        url: `../cart/index?t=${Date.now}`
      })
    },
    goBack() {
      Taro.navigateBack({
        delta: 1
      })
    }
  }

// C页面
methods: {
    goMine() {
      Taro.navigateBack()
    }
  }
```javascript

### 期望结果
能正常走onshow的钩子

### 实际结果
除了第一次流程后，再次从首页进入A - > B -> C 后，在回退，B 就不会触发onshow了。

### 环境信息
```
👽 Taro v3.2.11

  Taro CLI 3.2.11 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^3.2.11 => 3.2.13
      @tarojs/mini-runner: ^3.2.11 => 3.2.13
      @tarojs/plugin-platform-alipay: ^3.2.11 => 3.2.13
      @tarojs/runtime: ^3.2.11 => 3.2.13
      @tarojs/taro: ^3.2.11 => 3.2.13
      @tarojs/webpack-runner: ^3.2.11 => 3.2.13
      babel-preset-taro: ^3.2.11 => 3.2.13
      eslint-config-taro: ^3.2.11 => 3.2.13
    npmGlobalPackages:
      typescript: 4.3.3
```


---
### 补充信息
Vue2没问题， Vue3有问题。项目需要Vue3，请帮忙解决下这个问题。

<!-- generated by taro-issues. 请勿修改或删除此行注释 --><!--labels=T-alipay,V-3,F-vue3-->

**Comment by powerfulyang** [comment]
微信小程序 也有这个问题

**Comment by powerfulyang** [comment]
@Chen-jj 能帮忙看下？ 这个问题百分之百复现。

**Comment by liushengxuyanyu** [comment]
> @Chen-jj 能帮忙看下？ 这个问题百分之百复现。

[https://github.com/NervJS/taro/issues/9614](url) 还有这个问题，每个页面的onload只会第一次进入会触发，以后在进入就不会触发了。。

**Comment by powerfulyang** [comment]
onLoad 本来就只会执行一次的。 onShow 不执行才是 BUG

**Comment by liushengxuyanyu** [comment]
> onLoad 本来就只会执行一次的。 onShow 不执行才是 BUG

。。你试试vue3，我说的onload只会执行一次是指，这个页面的onload一旦被执行后，无论你在哪里进入这个页面都不会执行它的onload了。不是回退。vue2和小程序下 每次进入页面都会执行onload。除了回退以外，回退不走onload是正常的。

**Comment by liushengxuyanyu** [comment]
> onLoad 本来就只会执行一次的。 onShow 不执行才是 BUG

。。你试试vue3，我说的onload只会执行一次是指，这个页面的onload一旦被执行后，无论你在哪里进入这个页面都不会执行它的onload了。不是回退。vue2和小程序下 每次进入页面都会执行onload。除了回退以外，回退不走onload是正常的。

**Comment by Chen-jj** [comment]
3.2.14 应该已经修复了，可以升级后再试试
