### ISSUE TITLE
taro3.1.4 h5入口文件怎么改造才能 在外层套一层逻辑满足之后才去渲染App

### ISSUE THREAD

**Issue by CoquettishPoppy** [NervJS/taro#9627]
### 这个特性解决了什么问题？
解决初始化app环境已经用户数据等

### 这个 API 长什么样？
export default renderAppHoc(App); 可以通过高阶函数或者其他办法套一层逻辑

**Comment by Chen-jj** [comment]
@CoquettishPoppy HOC 应该可以吧？保证会渲染 `this.props.children` 应该就 ok
