### ISSUE TITLE
编译成京东小程序调用getPhoneNumber无法获取手机号

### ISSUE THREAD

**Issue by jiekekeji** [NervJS/taro#9633]
### 相关平台
京东小程序

**小程序基础库: 京东小程序**
**使用框架: Vue 2**

### 复现步骤
代码中添加
<button class="button-reset" @getphonenumber="getPhoneNumber" open-type="getPhoneNumber" >getPhoneNumber</button>

编译成微信小程序可以在回调中获取授权信息， 编译成京东无法在回调中获取授权信息

### 期望结果
编译成京东小程序的结果和微信保持一致，或提供差异写法，
可以在回调中获取授权信息

### 实际结果
编译成微信小程序可以在回调中获取授权信息， 编译成京东无法在回调中获取授权信息

### 环境信息
```
taro3.2.1、vue2.5.0、京东小程序

� Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD

```

**Comment by Chen-jj** [comment]
@jiekekeji 京东小程序是否具有此功能？

**Comment by jiekekeji** [comment]
这是京东的api地址: https://mp.jd.com/docs/dev/API/interface/cellphoneNumber.html#jdgetauthcodeobject
![image](https://user-images.githubusercontent.com/6375444/124685629-4119b880-df04-11eb-8cb1-47e402ea00c6.png)

**Comment by Chen-jj** [comment]
@jiekekeji 在 `dist/base.jxml` 找到所有 button 的 template，给 `<button>` 增加 ` bindgetphonenumber="eh"` 这个属性应该就可以。
