### ISSUE TITLE
关于预加载

### ISSUE THREAD

**Issue by junjie-yang-only** [NervJS/taro#964]
![image](https://user-images.githubusercontent.com/25219300/47700884-fa536b00-dc52-11e8-892b-9ed115bfc024.png)

想了解一下，关于暴露出来的钩子 **componentWillPreload**；在实际的调用中没有执行这个生命周期里面的方法，无论是放在组件中还是页面中。。。

难道是调用方式的问题，跪求指点一二。

按照理解：

```
componentWillPreload (params) {
    return this.fetchData(params.url)
  }

  fetchData () {
    this.isFetching = true
    ...
  }
```

这段代码应该是写在跳转之前的页面中吧。。。

```
componentWillMount () {
    console.log('isFetching: ', this.isFetching)
    this.$preloadData
      .then(res => {
        console.log('res: ', res)
        this.isFetching = false
      })
  }
```

这段代码应该是写在跳转之后的页面中能够获取吧。。。

**Comment by luckyadam** [comment]
taro 版本多少~

**Comment by Chen-jj** [comment]
componentWillPreload 钩子写在跳转后的页面上。

**Comment by luckyadam** [comment]
@junjie-yang-only 升级到最新的 beta 版本可以试试
