### ISSUE TITLE
taro typescript语法错误但编译成功不报错

### ISSUE THREAD

**Issue by Hard-workingrookie** [NervJS/taro#9646]
### 相关平台
微信小程序

### 复现仓库
[git@git.keyayun.com:keyayun/wxdvfcloud.git](git@git.keyayun.com:keyayun/wxdvfcloud.git)
**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
import { DOCTYPE1 } from '@/constants/commonType';
“"@/constants/commonType"”没有导出的成员“DOCTYPE1”。你是否指的是“DOCTYPE”?ts(2724)
已声明“DOCTYPE1”，但从未读取其值。ts(6133)

### 期望结果
编译不通过，报错

### 实际结果
编译通过，不报错

### 环境信息
```
👽 Taro v3.2.12


  Taro CLI 3.2.12 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.6.3 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/components: 3.2.12 => 3.2.12 
      @tarojs/mini-runner: 3.2.12 => 3.2.12 
      @tarojs/react: 3.2.12 => 3.2.12 
      @tarojs/runtime: 3.2.12 => 3.2.12 
      @tarojs/taro: 3.2.12 => 3.2.12 
      @tarojs/webpack-runner: 3.2.12 => 3.2.12 
      babel-preset-taro: 3.2.12 => 3.2.12 
      eslint-config-taro: 3.2.12 => 3.2.12 
      react: ^17.0.0 => 17.0.2 
```

**Comment by Hard-workingrookie** [comment]
![image](https://user-images.githubusercontent.com/51024834/124085663-d93a1c80-da82-11eb-915e-43e9eacaaaf0.png)

**Comment by Chen-jj** [comment]
tsconfig 里 `compileOptions.paths` 配置了吗

**Comment by Hard-workingrookie** [comment]
> tsconfig 里`compileOptions.paths`配置了

  设置了 "paths": {
      "@/*": ["./src/*"]
    }

**Comment by ZakaryCode** [comment]
## ts(2724)

无法访问代码仓库获取进一步的信息，但是可以看看 `./src/constants/commonType` 文件下是否导出对应变量

## ts(6133)

```json
// tsconfig.json
{
  ...
  "compilerOptions": {
    // noUnusedLocals 设置为 false
    "noUnusedLocals": false,
  }
}
```

**Comment by Hard-workingrookie** [comment]
> ## ts(2724)
> 无法访问代码仓库获取进一步的信息，但是可以看看 `./src/constants/commonType` 文件下是否导出对应变量
> 
> ## ts(6133)
> ```json
> // tsconfig.json
> {
>   ...
>   "compilerOptions": {
>     // noUnusedLocals 设置为 false
>     "noUnusedLocals": false,
>   }
> }
> ```
已经设置了。并且commonType没有DOCTYPE1这个类型变量，但还是编译成功


这是tsconfig.json的内容
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "removeComments": false,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "outDir": "lib",
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "baseUrl": ".",
    "rootDir": ".",
    "jsx": "preserve",
    "jsxFactory": "Taro.createElement",
    "allowJs": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "strict": true,
    "checkJs":true,
    "noUnusedLocals": false,
    "typeRoots": [
      "node_modules/@types",
      "global.d.ts"
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": [
    "src",
    "src/**/*.ts",
    "src/**/*.tsx",
  ],
  "compileOnSave": false
}

**Comment by Hard-workingrookie** [comment]
```
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: './tsconfig.json',
  },
  plugins: ['@typescript-eslint', 'react-hooks', 'prettier', 'jest'],
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:jest/recommended',
    'airbnb-typescript',
    'prettier',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
    'prettier/standard',
    'prettier/react',
    'taro',
    'plugin:taro/all',
  ],
  env: {
    browser: true,
    es2017: true,
    'jest/globals': true,
  },
  settings: {
    react: {
      version: 'detect',
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.d.ts'],
      },
      alias: {
        map: [['src', './src']],
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
  rules: {
    'react-hooks/rules-of-hooks': 'error',
    'no-param-reassign': [
      'error',
      { props: true, ignorePropertyModificationsFor: ['draft', 'obj'] },
    ],
    'no-restricted-syntax': ['error', 'ForInStatement', 'LabeledStatement', 'WithStatement'],
    'react-hooks/exhaustive-deps': 'warn',
    '@typescript-eslint/no-unused-vars': 'warn',
    'no-plusplus': 'off',
    'import/prefer-default-export': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'no-debugger': 'warn',
    'jsx-a11y/no-static-element-interactions': 'off',
  },
  overrides: [
    {
      files: ['*.tsx'],
      rules: {
        'react/prop-types': 'off',
      },
    },
    {
      files: ['*.stories.tsx'],
      rules: {
        'react/jsx-props-no-spreading': 'off',
        'import/no-extraneous-dependencies': 'off',
      },
    },
  ],
};
```
以上是.eslintrc.js的全部内容。

**Comment by Chen-jj** [comment]
非 Taro 问题，先关闭了

**Comment by s97712** [comment]
> 非 Taro 问题，先关闭了

有解决方法？

**Comment by s97712** [comment]
我在页面加入乱码也可以通过编译
