### ISSUE TITLE
微信小程序原生组件编译到支付宝小程序过程中丢失axml和acss

### ISSUE THREAD

**Issue by xiao0502** [NervJS/taro#965]
**问题描述**
基于taro框架结合有赞ui——`vant-weapp`的项目，在微信小程序上面运行正常，用支付宝小程序编译时候，微信小程序原生组件编译过程中，只编译了js、json，而axml、acss编译丢失，项目不能正常的跑起来，cli版本：1.1.0-beta.13

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```
npm run dev:alipay

> tyche_small_program_mall@1.0.0 dev:alipay /Users/xiao/Documents/tyche/wechat_tyche_mall
> npm run build:alipay -- --watch


> tyche_small_program_mall@1.0.0 build:alipay /Users/xiao/Documents/tyche/wechat_tyche_mall
> taro build --type alipay "--watch"

👽 Taro v1.1.0-beta.13
```

**期望行为**
希望微信原生组件在编译到支付宝的时候能够正常编译，正常运行

**报错信息**

```
(undefined) ./components/tyche/citylist/index.js
Module build failed :
Error: can not find /Users/xiao/Documents/tyche/wechat_tyche_mall/dist/components/tyche/citylist/index.axml
```

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]  1.1.0-beta.13
 - Node.js 版本 [e.g. v9.0.0] 
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
`vant-weapp` 这个项目本身不支持支付宝小程序

**Comment by xiao0502** [comment]
@luckyadam 有什么补救措施可以建议下的吗？我项目写了大半，都是基于`vant-weapp`的

**Comment by xiao0502** [comment]
@luckyadam 还有我自己写的微信小程序原生组件也编译失败，我想问下，是所有的微信原生组件都不能编译吗？那一套代码搞定的意义就大大降低了呀

**Comment by 471685249** [comment]
你要基于taro component才能转换成特定平台代码吧，原生ui不会转换

**Comment by xiao0502** [comment]
@luckyadam @471685249 taro-ui可以吗

**Comment by 471685249** [comment]
taro-ui目前只支持微信和h5吧，看文档说明不就啥都知道

**Comment by yuche** [comment]
taro ui 也支持支付宝小程序和百度小程序
