### ISSUE TITLE
taro-react会过滤props中的函数

### ISSUE THREAD

**Issue by fzudust** [NervJS/taro#9650]
### 相关平台
微信小程序

**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
export default function HomeScreen(route: any) {
    function formatter (day) {
        console.log(day)
    }
    return (
         <van-calendar
                formatter={formatter}  //  组件日志显示formatter为null
                show={showCalendar}
                showConfirm
                //type='range'
                onClose={onCloseCalendar}
                onConfirm={onConfirmCalendar}
            >
                <Slot name='title'>
                    <View>请选择日期</View>
                </Slot>
            </van-calendar>
    )
}

### 期望结果
van-calendar可以获取到formatter函数

### 实际结果
van-calendar获取到formatter函数为null

### 环境信息
```
  Taro CLI 3.2.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.1 - /var/folders/d2/_f0fb1px1gz3d0ycxh8z0qhw0000gn/T/yarn--1625191504344-0.8585962158883276/node
      Yarn: 1.22.10 - /var/folders/d2/_f0fb1px1gz3d0ycxh8z0qhw0000gn/T/yarn--1625191504344-0.8585962158883276/yarn
      npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.1 => 3.2.1 
      @tarojs/components: 3.2.1 => 3.2.1 
      @tarojs/mini-runner: 3.2.1 => 3.2.1 
      @tarojs/react: 3.2.1 => 3.2.1 
      @tarojs/runtime: 3.2.1 => 3.2.1 
      @tarojs/taro: 3.2.1 => 3.2.1 
      @tarojs/webpack-runner: 3.2.1 => 3.2.1 
      babel-preset-taro: 3.2.1 => 3.2.1 
      eslint-config-taro: 3.2.1 => 3.2.1 
      react: ^17.0.0 => 17.0.2 
```

---
### 补充信息
以有赞的日历组件为例，taro-react的props.ts中的setProperty会过滤props中的函数，根据微信官方文档，自基础库版本 2.0.9 开始，还可以在数据中包含函数，期望早点修改这个问题

**Comment by Chen-jj** [comment]
@fzudust 这样不行吗？https://github.com/NervJS/taro/issues/8495?_pjax=%23js-repo-pjax-container#issuecomment-760707631

提供一下 demo？
