### ISSUE TITLE
钉钉小程序不用taro的useEffect,报错，来啊尽快给我修复

### ISSUE THREAD

**Issue by w602542704** [NervJS/taro#9651]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/vueComponent/ant-design-vue-pro.git](https://github.com/vueComponent/ant-design-vue-pro.git)
**小程序基础库: 第三方企业应用**
**使用框架: React**

### 复现步骤
在taro首页里实现
1.import  { useEffect } from "@tarojs/taro";
2.  useEffect(() => {
  }, []);
3.钉钉小程序编译，报vendors.js:4675 TypeError: Object(...) is not a function

### 期望结果
能用

### 实际结果
不能用

### 环境信息
```
  Taro CLI 3.3.0-alpha.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - D:\myLib\node\node.EXE        
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - D:\myLib\node\npm.CMD
```

**Comment by w602542704** [comment]
![image](https://user-images.githubusercontent.com/24689873/124212285-4dc39880-db21-11eb-8a5b-3d84ae73d4df.png)
用react的useEffect 可以

**Comment by Chen-jj** [comment]
React 的 API 从 React 引入
