### ISSUE TITLE
taro3支持”基于 Taro 开发第三方多端 UI 库“吗

### ISSUE THREAD

**Issue by blankzust** [NervJS/taro#9652]
### 这个特性解决了什么问题？
这里的文档：https://taro-docs.jd.com/taro/docs/ui-lib/
好像是支持的，但是给的demo项目：https://github.com/NervJS/taro-ui-sample.git 用的还是taro1

### 这个 API 长什么样？
TARO_BUILD_TYPE=ui taro build --ui

**Comment by Chen-jj** [comment]
@blankzust Taro3 不需要再使用 `taro build --ui` 了，像这样组织 UI 库即可：https://github.com/NervJS/taro-uilib-react

**Comment by yuanyuwoxin** [comment]
> @blankzust Taro3 不需要再使用 `taro build --ui` 了，像这样组织 UI 库即可：https://github.com/NervJS/taro-uilib-react



> @blankzust Taro3 不需要再使用 `taro build --ui` 了，像这样组织 UI 库即可：https://github.com/NervJS/taro-uilib-react

scss文件打包之后没有出现

**Comment by jinjinwa** [comment]
> @blankzust Taro3 不需要再使用 `taro build --ui` 了，像这样组织 UI 库即可：https://github.com/NervJS/taro-uilib-react

想问下，这个示例项目，打包成的组件库，是需要在taro中使用。我的需求是，已经存在一些技术栈的小程序和h5页面，想用taro开发一套业务组件，输出小程序和h5能引用的组件，需要怎么配置啊？

**Comment by lijiangpeng7** [comment]
有vue版本的例子吗

**Comment by zhouzg5533** [comment]
> 



> > @blankzust Taro3 不需要再使用 `taro build --ui` 了，像这样组织 UI 库即可：https://github.com/NervJS/taro-uilib-react
> 
> 想问下，这个示例项目，打包成的组件库，是需要在taro中使用。我的需求是，已经存在一些技术栈的小程序和h5页面，想用taro开发一套业务组件，输出小程序和h5能引用的组件，需要怎么配置啊？

同问

**Comment by aryanna384** [comment]
> > 
> 
> > > @blankzust Taro3 不需要再使用 `taro build --ui` 了，像这样组织 UI 库即可：https://github.com/NervJS/taro-uilib-react
> > 
> > 
> > 想问下，这个示例项目，打包成的组件库，是需要在taro中使用。我的需求是，已经存在一些技术栈的小程序和h5页面，想用taro开发一套业务组件，输出小程序和h5能引用的组件，需要怎么配置啊？
> 
> 同问

同问，有解决方法了吗
