### ISSUE TITLE
h5项目，在app嵌套的webview页面白屏，抓包报“super”错误，机型vivoY5s

### ISSUE THREAD

**Issue by CoquettishPoppy** [NervJS/taro#9653]
### 相关平台
H5

**浏览器版本: 版本 91.0.4472.114（正式版本） (x86_64)**
**使用框架: React**

### 复现步骤
用户安卓手机部分机型，在app里访问taro编译后的h5链接，页面白屏；模拟机型能看到报错信息
![image](https://user-images.githubusercontent.com/39078624/124244708-d35f3c80-db51-11eb-9349-08cb21dca499.png)

### 期望结果
页面能正常访问

查了一下最近的issue，发现有很多类似的问题，想问一下官方除了升级taro版本，有没有其他直接的解决方案？
升级版本带来的影响范围比较大

### 实际结果
页面白屏

### 环境信息
```
👽 Taro v3.2.13


  Taro CLI 3.2.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - ~/.npm-global/bin/yarn
      npm: 7.19.0 - ~/.npm-global/bin/npm
    npmPackages:
      @tarojs/cli: 3.1.4 => 3.1.4 
      @tarojs/components: 3.1.4 => 3.1.4 
      @tarojs/mini-runner: 3.1.4 => 3.1.4 
      @tarojs/react: 3.1.4 => 3.1.4 
      @tarojs/router: 3.1.4 => 3.1.4 
      @tarojs/taro: 3.1.4 => 3.1.4 
      @tarojs/taro-h5: ^3.1.4 => 3.1.4 
      @tarojs/webpack-runner: 3.1.4 => 3.1.4 
      babel-preset-taro: 3.1.4 => 3.1.4 
      eslint-config-taro: 3.1.4 => 3.1.4 
      react: ^17.0.0 => 17.0.1 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10 
```

**Comment by CoquettishPoppy** [comment]
@sensitivemix ～

**Comment by SensitiveMix** [comment]
@CoquettishPoppy @smoothdvd @guotie @Psli @Leechael 看看这个问题，super 在 polyfill 的时候没有磨平，除了升级版本，有参考的解决方案么

**Comment by SensitiveMix** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@SensitiveMix @CoquettishPoppy 依赖升级一下，和 CLI 版本保持一致，然后再试试。之前有修复过类似问题

**Comment by SensitiveMix** [comment]
@Chen-jj 现在就是和 cli 版本一致的，cli 3.1.4 
![image](https://user-images.githubusercontent.com/16094680/124295783-d24b0100-db8b-11eb-9d1e-6c01263ca46c.png)

我们现在定位下来，是你们的 tarojs/components  v3.1.4 打包没有开启打包到 ES5 的配置，导致打出 ES6 的代码。需要升级到 3.2.13 才能解决问题，我们想问一下如果只升 tarojs/components 其他的不升级，有没有什么风险，或者说 tarojs/components v3.1.4 至 v3.2.13 中间有没有 break change，升级会不会很较大的风险。

**Comment by Chen-jj** [comment]
@SensitiveMix 3.1 到 3.2 只是增加了对 RN 的支持，小程序、H5 的实现没有大改，详情可以看看 release 信息。应该问题不大。

**Comment by CoquettishPoppy** [comment]
> @SensitiveMix 3.1 到 3.2 只是增加了对 RN 的支持，小程序、H5 的实现没有大改，详情可以看看 release 信息。应该问题不大。

我要哭了，，， @Chen-jj 大佬 升级后只解决了super关键字报错的问题 打出来的包还是存在const、let等，app内置浏览器访问的时候依旧报错，白屏
