### ISSUE TITLE
3.2.13启动程序报错

### ISSUE THREAD

**Issue by YC725968** [NervJS/taro#9658]
### 相关平台
微信小程序

**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
 UnhandledPromiseRejectionWarning: Error: Cannot find module '@tarojs/plugin-platform-weapp' from

### 期望结果
这个错误该如何解决

### 实际结果
 UnhandledPromiseRejectionWarning: Error: Cannot find module '@tarojs/plugin-platform-weapp' from

### 环境信息
```
👽 Taro v3.2.13


  Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\node_global\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
启动报错 UnhandledPromiseRejectionWarning: Error: Cannot find module '@tarojs/plugin-platform-weapp' from

**Comment by EricWong1994** [comment]
全局的@tarojs/cli 版本与项目中的taro版本不同 
例如全局为Taro v3.2.13
项目中国呢为"@tarojs/taro": "3.0.8",
两者需要保持版本一致。

**Comment by Chen-jj** [comment]
@YC725968 

@EricWong1994 说的正确。出现升级后编译失败时，需要确保 CLI 和依赖保持一致，然后删掉 `node_modules`，lock files 后重新安装依赖。
