### ISSUE TITLE
小程序转H5问题汇总及临时解决方案

### ISSUE THREAD

**Issue by styugege** [NervJS/taro#9661]
### 相关平台
H5

**浏览器版本: Chrome**
**使用框架: Vue 3**

#### 1.下拉刷新不能成功，微信小程序端无问题，H5端开启后，下拉之后一直处于下拉状态，回调方法onPullDownRefresh无法接收
使用过的版本：3.2.13 及 3.2.1    使用的UI库 taro-ui-vue3 1.0.0-alpha.19

#### 2.轮播图混乱，微信小程序无问题，H5端第一张图片和最后一张出现了两次，导致轮播图混乱，后来发现异步请求接口赋值给swiper标签会导致该问题发生，临时解决方法使用v-if，就可以解决该问题
使用过的版本：3.2.13及 3.2.1    使用的UI库 taro-ui-vue3 1.0.0-alpha.19

#### 3.打包之后少引入了一个文件，微信小程序无问题，H5打包时script标签只引入了app.js这个文件，临时解决方法，暂手动脚本引入另外一个文件
使用过的版本：3.2.13及 3.2.1    使用的UI库 taro-ui-vue3 1.0.0-alpha.19

#### 4.在文件还未加载完时连续点击某个跳转的按钮，微信小程序无问题，H5在路由端会创建多个相同id的路由dom，具体效果会变成如下：
```
<div id="/studioNotice?id=70" class="taro_page"></div>
<div id="/studioNotice?id=70" class="taro_page"></div>
```
使用过的版本：3.2.13及 3.2.1    使用的UI库 taro-ui-vue3 1.0.0-alpha.19

### 期望结果
可以正常使用

### 实际结果
出现了上述问题

### 环境信息
```
Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

**Comment by ZakaryCode** [comment]
> #### 1.下拉刷新不能成功，微信小程序端无问题，H5端开启后，下拉之后一直处于下拉状态，回调方法onPullDownRefresh无法接收

未能复现，可升级修复

> #### 2.轮播图混乱，微信小程序无问题，H5端第一张图片和最后一张出现了两次，导致轮播图混乱，后来发现异步请求接口赋值给swiper标签会导致该问题发生，临时解决方法使用v-if，就可以解决该问题

未能复现

> #### 3.打包之后少引入了一个文件，微信小程序无问题，H5打包时script标签只引入了app.js这个文件，临时解决方法，暂手动脚本引入另外一个文件

直接引用会打包到项目内，外部应用可以修改 `index.html` 或者配置 entry

> #### 4.在文件还未加载完时连续点击某个跳转的按钮，微信小程序无问题，H5在路由端会创建多个相同id的路由dom，具体效果会变成如下：
> ```
> <div id="/studioNotice?id=70" class="taro_page"></div>
> <div id="/studioNotice?id=70" class="taro_page"></div>
> ```

历史版本问题，可升级修复
