### ISSUE TITLE
Taro 3.X React 微信小程序 input 组件输入过快会出现闪烁的问题

### ISSUE THREAD

**Issue by vercentdeng** [NervJS/taro#9664]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/vercentdeng/taro-input-example](https://github.com/vercentdeng/taro-input-example)
**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
1. 随意点击一个input，当输入过快时就能重现问题
2. 当输入一大段文字后，长按删除键，也会出现闪烁（能明显看到输入值变动的）的情况

```typescript
render () {
  const dataSource= Array(800).fill(0);
  return (
    <View className='index'>
      {dataSource.map((data, index) => (
        <Input key={index} placeholder='请输入' />
      ))}
    </View>
  )
}
```

### 期望结果
输入的值的时候，不会出现闪烁的情况。

### 实际结果
1. 页面组件很多的时候
2. 组件很少，但组件里data（value）数据很大的时候

都会出现闪烁的情况

### 环境信息
```
Taro CLI 3.2.13 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
    npmPackages:
      @tarojs/components: 3.2.13 => 3.2.13
      @tarojs/mini-runner: 3.2.13 => 3.2.13
      @tarojs/react: 3.2.13 => 3.2.13
      @tarojs/runtime: 3.2.13 => 3.2.13
      @tarojs/taro: 3.2.13 => 3.2.13
      @tarojs/webpack-runner: 3.2.13 => 3.2.13
      babel-preset-taro: 3.2.13 => 3.2.13
      eslint-config-taro: 3.2.13 => 3.2.13
      react: ^17.0.0 => 17.0.2
```

---
### 补充信息
1. Taro React 微信小程序下，ios 真机和模拟器上
   - 同一个页面几百个 Input 就能重现这个问题。
   - 如果页面只有一个 Input ，其余几百个其他组件也会重现这个问题。
   - 使用 VirtualList 虽然能减少这个问题出现的几率，但还是有一定几率能重现。
2. 微信原生小程序下，ios 真机和模拟器上
   - 重复5千个input组件不会出现该问题。

**Comment by vercentdeng** [comment]
https://user-images.githubusercontent.com/6349628/124500842-10962980-ddf3-11eb-9f67-e6cb04f595d3.mov

问题录屏

**Comment by Chen-jj** [comment]
@vercentdeng Taro3 使用 template 去渲染，一般没有使用自定义组件，是页面级别的更新。目测这种情况下，会令小程序渲染层页面级别的 diff 出现性能问题。可以使用 `<CustomWrapper>` 手动增加一层自定义组件，把小程序渲染层的 diff 固定在自定义组件级别，避免页面级别的 diff，从而提升性能。

**Comment by vercentdeng** [comment]
@Chen-jj  测试后发现已经极大降低闪烁出现的几率了，感谢～

**Comment by BigFatStar** [comment]
> 不行啊，我用了这个方法，根本没有起作用

**Comment by summlicur410** [comment]
问题依旧存在

**Comment by diamont1001** [comment]
这么多年了，这个问题依然存在
