### ISSUE TITLE
h5项目 从3.0.29升级到3.2.13报错   getInitPxTransform is not a function

### ISSUE THREAD

**Issue by lemonSll** [NervJS/taro#9665]
### 相关平台
H5

**浏览器版本: 版本 91.0.4472.124（正式版本） （64 位）**
**使用框架: Vue 2**

### 复现步骤
npm run dev:h5

### 期望结果
正常运行

### 实际结果
无法运行

### 环境信息
```
 Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
项目中的依赖都是升级到3.2.13的,跟cli是一致的
![image](https://user-images.githubusercontent.com/44395984/124530201-a3a88100-de3e-11eb-9675-3871d1baab2b.png)
![image](https://user-images.githubusercontent.com/44395984/124530220-aefbac80-de3e-11eb-9415-b5c8cdb2c0b0.png)
![image](https://user-images.githubusercontent.com/44395984/124530237-b753e780-de3e-11eb-9d8f-8890fa7fe946.png)

**Comment by luckyadam** [comment]
能否提供个 demo 看看

**Comment by kruzabc** [comment]
我连3.2.1升级3.2.13都报错

**Comment by Chen-jj** [comment]
@kruzabc @lemonSll 提供一下 demo 吧。

**Comment by lemonSll** [comment]
升级到3.2.16没有这个问题了

**Comment by yingyejun** [comment]
我也遇到这个问题了,检查后发现 @tarojs/api 版本没有更新, 更新这个版本和 cli 一致就可以了
