### ISSUE TITLE
使用 virtual-list 组件报 JSON value ‘0px’ of type NSString cannot be converted to a YGValue. Did you forget the % or pt suffix?

### ISSUE THREAD

**Issue by xiamu14** [NervJS/taro#9666]
### 相关平台
React Native

### 复现仓库
[https://github.com/xiamu14/test-taro-webview.git](https://github.com/xiamu14/test-taro-webview.git)

**使用框架: React**

### 复现步骤
1. 首页点击“虚拟列表”
2. iOS 模拟机查看页面，会提示该错误
![1-1](https://assets-phi.vercel.app/issue/1-2.png)
3. 关闭错误提示以后，虚拟列表显示异常
![1-2](https://assets-phi.vercel.app/issue/1-1.png)

### 期望结果
正确显示虚拟列表的内容，并实现虚拟列表的功能

### 实际结果
1. 报标题里的错误
2. 虚拟列表功能不正常

### 环境信息
```
Taro CLI 3.2.13 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /var/folders/99/hmsg6_ss57q2y3gsb0_rpmy80000gn/T/yarn--1625540893805-0.5478408357972839/node
      Yarn: 1.22.10 - /var/folders/99/hmsg6_ss57q2y3gsb0_rpmy80000gn/T/yarn--1625540893805-0.5478408357972839/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v14.16.1/bin/npm
    npmPackages:
      @tarojs/cli: ^3.2.13 => 3.2.13
      @tarojs/components: 3.2.13 => 3.2.13
      @tarojs/mini-runner: 3.2.13 => 3.2.13
      @tarojs/react: 3.2.13 => 3.2.13
      @tarojs/runtime: 3.2.13 => 3.2.13
      @tarojs/taro: 3.2.13 => 3.2.13
      @tarojs/webpack-runner: 3.2.13 => 3.2.13
      babel-preset-taro: 3.2.13 => 3.2.13
      eslint-config-taro: 3.2.13 => 3.2.13
      react: ^17.0.0 => 17.0.2
      react-native: ^0.64.0 => 0.64.2
```

---
### 补充信息
1. 可能是RN 端解析 style 时出错

**Comment by zhiqingchen** [comment]
`@tarojs/components/virtual-list`为h5的组件，不能直接使用，请使用如下形式引入：
```tsx
import { View, VirtualList } from "@tarojs/components";
```


另外，使用VirtualList，建议禁用页面滚动。
```ts
export default {
  navigationBarTitleText: "虚拟列表",
  disableScroll: true,
}
```

**Comment by xiamu14** [comment]
@zhiqingchen  "@tarojs/components"  最新版 3.2.13 并没有到处 VirtualList 组件
![](https://assets-phi.vercel.app/issue/1-3.png)

得这样导入吧？
```
import {VirtualList} from "@tarojs/components-rn"
```

**Comment by iambool** [comment]
> @zhiqingchen "@tarojs/components" 最新版 3.2.13 并没有导出 VirtualList 组件
> ![](https://camo.githubusercontent.com/796afc5409a2b84c9df95be40acaeb2cebd698235f5eee6f69ff2485b5413662/68747470733a2f2f6173736574732d7068692e76657263656c2e6170702f69737375652f312d332e706e67)
> 
> 得这样导入吧？
> 
> ```
> import {VirtualList} from "@tarojs/components-rn"
> ```

从 @tarojs/components 导入也是可以的，另外VirtualList组件在使用时指定下overscanCount属性（大于1即可），这样才能渲染出来

**Comment by xiamu14** [comment]
那从 @tarojs/components 导入，类型提示好像需要修复一下。

**Comment by HeNanBing** [comment]
@xiamu14 请问怎么解决的
