### ISSUE TITLE
taro 使用 wxParse报错

### ISSUE THREAD

**Issue by G21iwenjun** [NervJS/taro#9669]
<img width="478" alt="Snipaste_2021-07-06_11-37-41" src="https://user-images.githubusercontent.com/25291272/124538711-add27b80-de4e-11eb-81d8-d9d76392070e.png">

### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/FE_lwj/taro-wxparse](https://gitee.com/FE_lwj/taro-wxparse)
**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
1.初始化项目，安装依赖
2.使用wxParse插件
3.页面报错 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### 期望结果
能正常使用wxParse插件

### 实际结果
使用wxParse插件时报错 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### 环境信息
```
Taro CLI 3.2.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\liwenjun\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
直接使用 `dangerouslySetInnerHTML` 不行么
