### ISSUE TITLE
仓库存在大小写冲突的文件

### ISSUE THREAD

**Issue by harry-xiaomi** [NervJS/taro#9708]
### 这个特性解决了什么问题？
合并以下冲突文件，支持大小写不敏感的文件系统克隆仓库。

  'packages/taro/types/api/network/mDNS.d.ts'
  'packages/taro/types/api/network/mdns.d.ts'
  'packages/taro/types/api/network/webSocket.d.ts'
  'packages/taro/types/api/network/websocket.d.ts'

### 这个 API 长什么样？
无

**Comment by Chen-jj** [comment]
来个 PR 咯～
