### ISSUE TITLE
为什么我在taro使用es6修饰器会报错

### ISSUE THREAD

**Issue by yzw2017** [NervJS/taro#971]
![2018-10-31_120336](https://user-images.githubusercontent.com/31871287/47765496-334c1800-dd05-11e8-98be-e51bfa0b5956.png)
![2018-10-31_120406](https://user-images.githubusercontent.com/31871287/47765520-4fe85000-dd05-11e8-802b-035dbd463ce0.png)

**Comment by luckyadam** [comment]
这个页面的代码完整贴一下

**Comment by yzw2017** [comment]
@luckyadam 已经找到问题了，是我自己傻逼引用了redux这个包，没有引用@tarojs/redux这个包，然后可恨得是taro-cli在没有对应包的情况下，自动帮我下载对应包，编译不会报错，小程序开发者工具报错了，找了我几个小时

**Comment by luckyadam** [comment]
🤣
