### ISSUE TITLE
建议升级@tarojs/react 里面关于scheduler的引用版本

### ISSUE THREAD

**Issue by ElegantBrick** [NervJS/taro#9710]
### 这个特性解决了什么问题？
解决H5模式下chrome浏览器出现如下警告：
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021.

### 这个 API 长什么样？
chrome浏览器无警告

**Comment by Chen-jj** [comment]
3.3 应该已经升级了，可以试试 3.3-beta.0

**Comment by ElegantBrick** [comment]
> 3.3 应该已经升级了，可以试试 3.3-beta.0

见笑了，用的3.2.12。去看了一下最新的，是升级了的
