### ISSUE TITLE
Taro编译支付宝小程序 onGetAuthorize回调未触发

### ISSUE THREAD

**Issue by pangcongcong** [NervJS/taro#9712]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/pangcongcong/demo/blob/main/getPhoneNumber.vue](https://github.com/pangcongcong/demo/blob/main/getPhoneNumber.vue)
**小程序基础库: 1.0.0**
**使用框架: Vue 3**

### 复现步骤
 <button hover-class="none" open-type="getAuthorize"  scope="phoneNumber" @error="onError" @getAuthorize="onGetAuthorize">获取手机号</button>

js： 
onGetAuthorize() {
      console.log('onGetAuthorize')
}

### 期望结果
授权成功后 onGetAuthorize触发回调

### 实际结果
未出发回调函数 绑不上手机号

### 环境信息
```
Taro CLI 3.2.15 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: ^3.3.0-beta.0 => 3.2.13
      @tarojs/mini-runner: ^3.2.2-beta.0 => 3.2.13
      @tarojs/plugin-platform-alipay: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-jd: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-qq: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-swan: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-tt: ^3.2.12 => 3.2.13
      @tarojs/plugin-platform-weapp: ^3.2.12 => 3.2.13
      @tarojs/runtime: ^3.2.2-beta.0 => 3.2.13
      @tarojs/taro: ^3.2.2-beta.0 => 3.2.13
      @tarojs/webpack-runner: 3.0.21 => 3.0.21
      babel-preset-taro: 3.0.21 => 3.0.21
      eslint-config-taro: 3.0.21 => 3.0.21
```

**Comment by Chen-jj** [comment]
@pangcongcong 事件名全小写：https://docs.taro.zone/docs/vue-overall#taro-%E8%A7%84%E8%8C%83-1

**Comment by pangcongcong** [comment]
> @pangcongcong 事件名全小写：https://docs.taro.zone/docs/vue-overall#taro-%E8%A7%84%E8%8C%83-1
收到 可以了 谢谢
