### ISSUE TITLE
vue3 下使用 render 写页面，获取手机号的回调无效

### ISSUE THREAD

**Issue by Ttou** [NervJS/taro#9719]
### 相关平台
微信小程序

### 复现仓库
[https://gitee.com/jh_shot/taro-template.git](https://gitee.com/jh_shot/taro-template.git)
**小程序基础库: 2.18.0**
**使用框架: Vue 3**

### 复现步骤
1、点击获取手机号
2、弹出确认授权
3、点击确定后没有触发回调

### 期望结果
点击按钮后获得手机号信息

### 实际结果
没有触发回调函数

### 环境信息
```
Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Ttou** [comment]
问题找到了，ButtonProps 里的获取手机号事件名有问题，onGetPhoneNumber 改成 onGetphonenumber 就可以触发了

**Comment by Chen-jj** [comment]
@Tou 有空可以帮忙提个 PR 在文档添加一下说明哈～

这里～

![image](https://user-images.githubusercontent.com/11807297/125013825-1adc5000-e09f-11eb-89e1-6c124ce2a911.png)
