### ISSUE TITLE
在微信开发者工具中无法查看AppData

### ISSUE THREAD

**Issue by Licoy** [NervJS/taro#9722]
### 相关平台
微信小程序

**小程序基础库: 2.18.0**
**使用框架: Vue3**

### 复现步骤
在微信开发者工具中，展示的数据树是复杂的，需要开发者花费很大的精力才能找到所想要的值，如：
![image.png](https://i.loli.net/2021/07/09/zNX4jn1DmaQ38Ov.png)

> 从图上看，是展示的taro每个组件所需的props数据

### 期望结果
期望可以如和官方开发一样，可以直接明了的展示AppData数据树，或者有其他方法可以查看也是可行的。

### 实际结果
如图所示

### 环境信息
```
👽 Taro v3.2.15


  Taro CLI 3.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by lupingW** [comment]
是呀 不能看太烦了

**Comment by Chen-jj** [comment]
Taro 会把虚拟 DOM 序列化后，调用 setData 传递给小程序渲染层，所以 Appdata 面板看到的是虚拟 DOM 的序列化数据，这一点没有办法改变。

近期 Taro 会支持 React DevTools 和 Vue DevTools，希望能有所帮助。
