### ISSUE TITLE
自定义组件中传入props 未生效

### ISSUE THREAD

**Issue by YellowPure** [NervJS/taro#9723]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
1. https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/
参照微信小程序引入自定义组件
2. 执行build操作
3. 开发者工具中查看自定义组件的observer或是observers监听函数是否触发

```javascript
Component({
  properties: {
    // 这里定义了innerText属性，属性值可以在组件使用时指定
    innerText: {
      type: String,
      value: 'default value',
    }
  },
observers: {name: function(val) {

// 此处不会触发
console.log(val);
}},
  data: {
    // 这里是一些组件内部数据
    someData: {}
  },
  methods: {
    // 这里是一个自定义方法
    customMethod: function(){}
  }
});

// 声明使用第三方组件
{
  "usingComponents": {
    "component-tag-name": "path/to/the/custom/component"
  }
}
<component-tag-name  name='xxx' />
```

### 期望结果
1. observer或是observers函数触发
2. 外部传入的prop属性可以正常设置

### 实际结果
1. observer或是observers函数触发
2. 外部传入的prop属性未正常设置

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.9.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.2.8 
      @tarojs/components: 3.2.8 => 3.2.8 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.2.8 => 3.2.8 
      @tarojs/runtime: 3.2.8 => 3.2.8 
      @tarojs/taro: 3.2.8 => 3.2.8 
      @tarojs/webpack-runner: 3.2.8 => 3.2.8 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.2.8 => 3.2.8 
      react: ^16.10.0 => 16.14.0 
      taro-ui: 3.0.0-alpha.3 => 3.0.0-alpha.3 
```

---
### 补充信息
发现此问题的代码是copy自另一个线上taro项目，项目为taro 版本3.0.9，对比代码调用后发现没有明显区别，之后将旧项目升级到3.2.8或是最新的3.2.15后发现都出现此bug

**Comment by Chen-jj** [comment]
提供一下 demo 咯

**Comment by YellowPure** [comment]
https://github.com/YellowPure/taro-bug-demo

这个demo是错误时的，找了好几天才找到原因，是因为我这边使用node_env 区分环境test,stage,production 后 导致可能某些编译不正确引起的，不过具体原因不明

yarn build-test:weapp 错误
yarn build-prod:weapp 正确

**Comment by YellowPure** [comment]
补充一条
**taro build --type weapp --env test**
出错

必须是
**taro build --type weapp**

即使 test.js文件中
```javascript
module.exports = {
  env: {
    NODE_ENV: '"production"',
  },
  defineConstants: {},
  mini: {},
  h5: {},
};
```
也不行

**Comment by Chen-jj** [comment]
这里影响到了，可以手动配置 `'@babel/preset-env'` 的参数试试。

https://github.com/NervJS/taro/blob/6644d7f894ad18c37e864f7f61c6956d82122ee9/packages/babel-preset-taro/index.js#L129-L131
