### ISSUE TITLE
深圳初创公司寻找 Taro 小伙伴

### ISSUE THREAD

**Issue by finian** [NervJS/taro#973]
我们是一家深圳的初创公司，目前的产品是一款围绕微信生态圈的营销工具，前端技术栈是 React/Taro + GraphQL/Apollo Client，目前我们已经基本上移植了 Apollo Client 到 Taro 上（后续完善了会开源）。我们正在寻找使用 Taro 的小伙伴，欢迎加我微信详聊。我的微信：finian（加好友时请备注 taro）

P.S. 这条 issue 的发布已征得隔壁老李同意，如不符合规范，会马上删除，见谅。

**Comment by kdong007** [comment]
https://github.com/kdong007/taro-apollo 你会需要的  :D
