### ISSUE TITLE
开发环境下，新增eslint-loader，后于babel-loader执行，导致检测的是被修改后的文件

### ISSUE THREAD

**Issue by Aariffe** [NervJS/taro#9736]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Aariffe/taro-for-issue](https://github.com/Aariffe/taro-for-issue)
**小程序基础库: 1.05.2105170**
**使用框架: React**

### 复现步骤
```
webpackChain (chain, webpack) {
      chain.merge({
        module: {
          rule: {
            myLoader: {
              test: /\.(js|jsx)$/,
              enforce: 'pre',
              use: [{
                loader: 'eslint-loader',
                options: {
                  exclude: /node_modules/,
                  include: [path.join(__dirname, '..', 'src'),],
                  fix: false,
                }
              }]
            },
          }
        },
      })
}
```

### 期望结果
eslint-loader能先于babel-loader执行

### 实际结果
eslint-loader后于babel-loader执行，检测到的代码是转换过的代码

### 环境信息
```
� Taro v3.2.2


  Taro CLI 3.2.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - D:\develop\node\node.EXE
      Yarn: 1.22.4 - D:\develop\node\yarn.CMD
      npm: 6.14.4 - D:\develop\node\npm.CMD
```

**Comment by Chen-jj** [comment]
这应该不是 Taro 的问题吧。

**Comment by Aariffe** [comment]
> 这应该不是 Taro 的问题吧。

是Taro的问题吧，因为webpack的babel-loader打包流程被封装到框架中了，只留下了一个webpackChain的接口供用户调用

**Comment by Chen-jj** [comment]
但是按道理，webpackChain 可以修改任意 webpack 配置（在 taro 处理后， 调用 webpack 前），`enforce: 'pre'` 更是能保证调用顺序。。建议用 webpackChain 打印一下最终的配置看看了

**Comment by 1247748612** [comment]
用eslint-webpack-plugin

**Comment by Aariffe** [comment]
> 用eslint-webpack-plugin

之前我也用了eslint-webpack-plugin，但是报错了，可以把你写的示例看下嘛？谢谢！

**Comment by Aariffe** [comment]
> 但是按道理，webpackChain 可以修改任意 webpack 配置（在 taro 处理后， 调用 webpack 前），`enforce: 'pre'` 更是能保证调用顺序。。建议用 webpackChain 打印一下最终的配置看看了

打印了webpackChain的loaders，感觉上没有问题，但是有两个loader都是enforce:pre。但是结果却是先执行了babel-loader，想问下你们自己是怎么做eslint测试的呢？可以给个写法的实例吗？谢谢！

**Comment by 1247748612** [comment]
> > 用eslint-webpack-plugin
> 
> 之前我也用了eslint-webpack-plugin，但是报错了，可以把你写的示例看下嘛？谢谢！

试试这个，
```javascript
const ESLintPlugin = require('eslint-webpack-plugin');
const path = require('path')
module.exports = {
  env: {
    NODE_ENV: '"development"'
  },
  defineConstants: {
  },
  mini: {
    webpackChain (chain, webpack) {
      chain.plugin('eslint').use(require('eslint-webpack-plugin'), [
        {
          context: path.resolve(__dirname, '..'),
          extensions: ['js', 'jsx'],
          files: 'src/**/*'
        }
      ])
    },
  },
  h5: {
  }
}

```

**Comment by Aariffe** [comment]
> > > 用eslint-webpack-plugin
> > 
> > 
> > 之前我也用了eslint-webpack-plugin，但是报错了，可以把你写的示例看下嘛？谢谢！
> 
> 试试这个，
> 
> ```js
> const ESLintPlugin = require('eslint-webpack-plugin');
> const path = require('path')
> module.exports = {
>   env: {
>     NODE_ENV: '"development"'
>   },
>   defineConstants: {
>   },
>   mini: {
>     webpackChain (chain, webpack) {
>       chain.plugin('eslint').use(require('eslint-webpack-plugin'), [
>         {
>           context: path.resolve(__dirname, '..'),
>           extensions: ['js', 'jsx'],
>           files: 'src/**/*'
>         }
>       ])
>     },
>   },
>   h5: {
>   }
> }
> ```

我用这个的时候一直报错： ESLint is not a constructor。之前用的时候也是报这个错

**Comment by 1247748612** [comment]
> > > > 用eslint-webpack-plugin
> > > 
> > > 
> > > 之前我也用了eslint-webpack-plugin，但是报错了，可以把你写的示例看下嘛？谢谢！
> > 
> > 
> > 试试这个，
> > ```js
> > const ESLintPlugin = require('eslint-webpack-plugin');
> > const path = require('path')
> > module.exports = {
> >   env: {
> >     NODE_ENV: '"development"'
> >   },
> >   defineConstants: {
> >   },
> >   mini: {
> >     webpackChain (chain, webpack) {
> >       chain.plugin('eslint').use(require('eslint-webpack-plugin'), [
> >         {
> >           context: path.resolve(__dirname, '..'),
> >           extensions: ['js', 'jsx'],
> >           files: 'src/**/*'
> >         }
> >       ])
> >     },
> >   },
> >   h5: {
> >   }
> > }
> > ```
> 
> 我用这个的时候一直报错： ESLint is not a constructor。之前用的时候也是报这个错

把错误截图发来看看，我之前确定是可以的，后面改用fork-ts-checker-webpack-plugin了

**Comment by Aariffe** [comment]
> > > > > 用eslint-webpack-plugin
> > > > 
> > > > 
> > > > 之前我也用了eslint-webpack-plugin，但是报错了，可以把你写的示例看下嘛？谢谢！
> > > 
> > > 
> > > 试试这个，
> > > ```js
> > > const ESLintPlugin = require('eslint-webpack-plugin');
> > > const path = require('path')
> > > module.exports = {
> > >   env: {
> > >     NODE_ENV: '"development"'
> > >   },
> > >   defineConstants: {
> > >   },
> > >   mini: {
> > >     webpackChain (chain, webpack) {
> > >       chain.plugin('eslint').use(require('eslint-webpack-plugin'), [
> > >         {
> > >           context: path.resolve(__dirname, '..'),
> > >           extensions: ['js', 'jsx'],
> > >           files: 'src/**/*'
> > >         }
> > >       ])
> > >     },
> > >   },
> > >   h5: {
> > >   }
> > > }
> > > ```
> > 
> > 
> > 我用这个的时候一直报错： ESLint is not a constructor。之前用的时候也是报这个错
> 
> 把错误截图发来看看，我之前确定是可以的，后面改用fork-ts-checker-webpack-plugin了

报错截图是这样的，感谢您
![github](https://user-images.githubusercontent.com/11482982/125741150-ad874750-2f8d-4747-9bdf-8492e006cd83.png)

**Comment by 1247748612** [comment]
升级下eslint
![image](https://user-images.githubusercontent.com/29533304/126100057-ff1cd529-42de-4cfc-b5f9-c96c75667739.png)

我看你的repo仓库是用ts的，可以直接用fork-ts-checker-webpack-plugin

**Comment by Aariffe** [comment]
> 升级下eslint
> ![image](https://user-images.githubusercontent.com/29533304/126100057-ff1cd529-42de-4cfc-b5f9-c96c75667739.png)
> 
> 我看你的repo仓库是用ts的，可以直接用fork-ts-checker-webpack-plugin

非常感谢，确实可以了，不过用的时候遇到一点小问题，就是extensions这个配置好像没有效果。把svg和png这些类型也做了检查。不过后来使用files做了限定就可以了。感谢！
