### ISSUE TITLE
Swiper开启circular衔接滑动在h5经过一轮之后会无法滑动

### ISSUE THREAD

**Issue by huang-weijian** [NervJS/taro#9737]
### 相关平台
H5

**浏览器版本: 91.0.4472.114 amr64 macM1**
**使用框架: React**

### 复现步骤
Swiper组件开启circular衔接滑动在h5经过一轮之后会无法滑动

### 期望结果
划过一轮之后能正常滑动

### 实际结果
滑过一轮之后就不能再滑动，再滑动就变成拖动整个网页

### 环境信息
```
👽 Taro v3.2.15


  Taro CLI 3.2.15 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.15 => 3.2.15 
      @tarojs/mini-runner: 3.2.15 => 3.2.15 
      @tarojs/react: 3.2.15 => 3.2.15 
      @tarojs/runtime: 3.2.15 => 3.2.15 
      @tarojs/taro: 3.2.15 => 3.2.15 
      @tarojs/webpack-runner: 3.2.15 => 3.2.15 
      babel-preset-taro: 3.2.15 => 3.2.15 
      eslint-config-taro: 3.2.15 => 3.2.15 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10 
```

**Comment by bobsam** [comment]
+1，该问题在v3.2.15及以上的版本下必现。。后面只能降级到3.2.14了

**Comment by zhangchuanbo** [comment]
> 降级之后还是有问题，使用循环渲染出来得还是有问题，直接swiperItem单个单个写没啥问题
> ![image](https://user-images.githubusercontent.com/30680427/126273335-46548c5c-6b6e-4202-addb-d89926585ff6.png)
> 这两种写法，后面一种在3.2.14一样有问题。前一种写法没问题
> 
> 这个是传入到组件的数组变化引起的，第一次是一个banner，第二次进入是两个banner会导致该问题

解决办法当传入数组变更时给外层swiper加上key值，list变化一次修改一次key值

**Comment by bobsam** [comment]
@huang-weijian 看看这好了没？3.3.1版本发了，我好像还是不行。。。
@Chen-jj

**Comment by zhangchuanbo** [comment]
> @huang-weijian 看看这好了没？3.3.1版本发了，我好像还是不行。。。
> @Chen-jj

我升级后，我这边目前是不行的。不知道是不是打开方式不对

**Comment by bobsam** [comment]
> > @huang-weijian 看看这好了没？3.3.1版本发了，我好像还是不行。。。
> > @Chen-jj
> 
> 我升级后，我这边目前是不行的。不知道是不是打开方式不对

@ZakaryCode @Chen-jj 我也是。麻烦可以看看吗？

**Comment by yazakid** [comment]
我这边试了也是不行，小程序的ok

**Comment by bobsam** [comment]
是的，期望官方可以解决一下。因为这样一直不敢升级taro版本，想尝试新特性都没法。

**Comment by huang-weijian** [comment]
用得有点累了，不想改了，不想再尝试了。Taro用来写小程序还行，写H5不行，特别是放在app内嵌套运行的web页面

**Comment by bobsam** [comment]
> 用得有点累了，不想改了，不想再尝试了。Taro用来写小程序还行，写H5不行，特别是放在app内嵌套运行的web页面

其实还好。。有些组件是需要做多端区分的，一次性多端我觉得是不行的，只是能减少大部分工作量就好了

**Comment by huang-weijian** [comment]
> > 用得有点累了，不想改了，不想再尝试了。Taro用来写小程序还行，写H5不行，特别是放在app内嵌套运行的web页面
> 
> 其实还好。。有些组件是需要做多端区分的，一次性多端我觉得是不行的，只是能减少大部分工作量就好了

我的需求大部分都是h5加微信小程序，h5都不行，那只用Taro来写小程序，h5另写，并没有减少什么工作量，要是Taro出问题，我要再去改还更麻烦，我用了一个星期，已经提了好几个pull request，还有几个都懒得提了，看到不少issue都没人回复，还是老老实实分开写吧，速度更快，更可靠。

**Comment by huang-weijian** [comment]
> > 用得有点累了，不想改了，不想再尝试了。Taro用来写小程序还行，写H5不行，特别是放在app内嵌套运行的web页面
> 
> 其实还好。。有些组件是需要做多端区分的，一次性多端我觉得是不行的，只是能减少大部分工作量就好了

复杂需求的多端区分并没有出问题，反而很多简单需求出现了问题

**Comment by zhangchuanbo** [comment]
> 用得有点累了，不想改了，不想再尝试了。Taro用来写小程序还行，写H5不行，特别是放在app内嵌套运行的web页面

我目前微信小程序H5问题不是很大，不知道后面会怎么样。跨端的话uniapp表现还是好很多

**Comment by chenjunjia97** [comment]
应该是siwper里面的item 不支持异步增加删除吧，你用list.map生成item 可能导致swiper初始化的状态，没有根据item数量变化重新计算过之类的

**Comment by Freezing1** [comment]
看之前的issues ,我在代码加了这一段,就可以循环了
componentDidUpdate () {
    this.swiperRef.mySwiper.loopDestroy()
    this.swiperRef.mySwiper.loopCreate()
 }

**Comment by ZakaryCode** [comment]
新版本未能复现到该问题，如果依旧存在可以创建一个新的issue，并提交可以复现的demo
