### ISSUE TITLE
增强  Vue 框架（2.0 和 3.0）收集第三方组件所用到的小程序组件的能力

### ISSUE THREAD

**Issue by b2nil** [NervJS/taro#9740]
### 这个特性解决了什么问题？
目前 vue 框架收集小程序组件的能力是放在 `vue-loader` 中实现的， 无法分析编译后（以渲染函数）提供的第三方组件（除非组件直接引用 `@tarojs/components`）。虽然可以配置 `vue-loader` 的编译选项，通过分析所使用的第三方组件来添加组件中使用到的小程序组件（需要预先手动列出列表），但这仅对使用 template 的开发者有效。

Taro 3.3 中提供了 `modifyComponentConfig` 的钩子，但从 `taro-plugin-html` 的实现来看，这个钩子只能做到批量收集，还是不理想。我们需要的是：无论使用哪种框架，均可以按需收集（自动），或者至少根据用户配置（例如配置第三方组件库提供的插件）按组件收集。

https://github.com/NervJS/taro/blob/436760888b0ac56cf1c389f4bee449b288409a24/packages/taro-mini-runner/src/webpack/build.conf.ts#L94

https://github.com/NervJS/taro/blob/436760888b0ac56cf1c389f4bee449b288409a24/packages/taro-plugin-html/src/index.ts#L79-L86

可以将 `taro/packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts` 中收集 react 的第三方组件的方式，扩展到 vue 框架，从而实现对采用 vue 渲染函数和 jsx 所编写的组件的支持。

https://github.com/NervJS/taro/blob/436760888b0ac56cf1c389f4bee449b288409a24/packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts#L28-L43

### 这个 API 长什么样？
对 `@tarojs/mini-runner` 的 TaroNormalModulesPlugin 进行 ~~改造~~ 扩展，以实现对 vue 2 & 3 渲染函数和 JSX 的支持：
```ts
// taro/packages/taro-mini-runner/src/plugins/TaroNormalModulesPlugin.ts
// Lines 32 to 43
const callee = node.callee
if (callee.type === 'MemberExpression') {
      if (callee.property.name !== 'createElement') {
             return
      }
} else {
     if (
           // 兼容 react17 new jsx transtrom
           callee.name !== '_jsx' && callee.name !== '_jsxs' &&
           // 兼容 Vue 3.0 渲染函数及 JSX
           !(callee.name && callee.name.includes('createVNode')) &&
           !(callee.name && callee.name.includes('createBlock')) &&
           !(callee.name && callee.name.includes('resolveComponent')) && // 收集使用解析函数的组件名称
           // 兼容 vue 2.0 渲染函数及 JSX
           callee.name !== 'h' && callee.name !== '_c'
     ) {
          return
    }
}
```

经过 ~~改造~~ 扩展，Taro 支持的框架应该都能收集到组件所使用的小程序标签。

`modifyComponentConfig` 这个钩子应该可以废弃???（需要评估）。若需对收集的小程序组件的列表进行更改，可统一通过 `onParseCreateElement` 钩子来实现。
https://github.com/NervJS/taro/blob/436760888b0ac56cf1c389f4bee449b288409a24/packages/taro-mini-runner/src/webpack/build.conf.ts#L94

#### 示例
以 `taro-ui-vue3` 为例，采用渲染函数编写的版本直接引用了 `@tarojs/components` 的组件，因此不存在收集小程序组件的问题；但采用[ SFC 重构](https://github.com/b2nil/taro-ui-vue3/tree/feat/sfc) 后，提供的组件都是直接从模板编译到渲染函数的，没有直接引用 `@tarojs/components` 的组件，因此需要收集所用到的小程序组件。

`taro-ui-vue3` SFC 重构版本提供了一个 taro 插件，需要使用到 `onParseCreateElement` 来收集所用到的小程序组件：
```ts
module.exports = function (ctx, options) {
  const miniappTagMap = {
    ...
    'avatar': ['view', 'open-data', 'image', 'text'],
    'button': ['view', 'button', 'form', 'slot'],
    'calendar': ['view', 'swiper', 'swiper-item', 'picker', 'text'],
    ...
  }

  // 收集使用到的小程序组件
  ctx.onParseCreateElement(({ nodeName, componentConfig }) => {
    const includes = componentConfig.includes
    if (nodeName && nodeName.startsWith('at-')) {
      const key = nodeName.substring(3)
      const tags = miniappTagMap[key]
      for (const tag of tags) {
        if (!includes.has(tag))
          includes.add(tag)
      }
    }
  })
}
```
如果 `@tarojs/mini-runner` 的 TaroNormalModulesPlugin 支持直接解析 vue 2 & 3 渲染函数和 JSX 的话，那么用户只需直接在 taro 配置文件中配置一个插件即可：
```ts
// ./config/index.js
{
  plugins: ['taro-ui-vue3/lib/plugin'],
}
```

#### 缺陷 或 bug ？
本地实验的时候，发现如果组件是从打包文件中引用，或从导出诸多组件的某个 `index.js` 中引用，会收集到该打包文件或 index 文件中导出的所有组件所用到的小程序标签。

例如：
- `import AtButton from "taro-ui-vue3/lib/button/index.js"`  --> 从组件所在文件引用，收集功能表现正常
- `import { AtButton } from "taro-ui-vue3/dist/index.esm.js"`  --> 从打包文件引用，会收集到打包文件中的所有标签
- `import { AtButton } from "taro-ui-vue3/lib/index.js"`  --> 从组件重新导出文件引用，会收集到该文件中导出的其他组件的标签

希望 Taro 官方可以评估一下可行性，以及最后这个缺陷是否可以修复。

**Comment by Chen-jj** [comment]
下周看看哈

**Comment by Ttou** [comment]
还是希望用 jsx 写，渲染函数不直观

**Comment by b2nil** [comment]
无论是 jsx 语法，还是 template 语法，最终都会被编译成渲染函数。

**Comment by Chen-jj** [comment]
https://github.com/jdf2e/nutui/issues/551

**Comment by Chen-jj** [comment]
感谢 @b2nil 提出的方案，3.5.6 修复
