### ISSUE TITLE
Nervjs 已死，tarojs 万岁！

### ISSUE THREAD

**Issue by arniu** [NervJS/taro#9744]
### 这个特性解决了什么问题？
目前看来 nervjs 已死，而 tarojs 却欣欣向荣，建立了广泛的统一战线。

为什么不把相关代码放在 tarojs 名下呢？

### 这个 API 长什么样？
以上仅仅是个不成熟的建议

**Comment by bobsam** [comment]
nervjs是一定时期的产物，它的存在是为了解决一些兼容问题。如果京东内容已经决定抛弃IE8等一些低端浏览器的话，其实用新版React也无妨。至于轻量还是不轻量，这个问题是好解决。

**Comment by arniu** [comment]
从**品牌**的角度来看，集中力量推 tarojs 是有利的，正如当年京东域名从 360buy 改为 jd 一样。

**Comment by Chen-jj** [comment]
很遗憾，NervJS 不够人力维护了。近期我们会增加对 PReact 的支持，之后 Nerv 会从 Taro 推荐使用框架中下架。
