### ISSUE TITLE
Taro.scanCode 扫一维码异常

### ISSUE THREAD

**Issue by yujiaming890321** [NervJS/taro#975]
**问题描述**

调用 扫码 功能，扫一维码 图片报异常。

**复现步骤**
```js
async scan() {
    const scanResult = await Taro.scanCode({
        onlyFromCamera: true,
        scanType: ["barCode"]
    });
    console.log(scanResult);
}
```
```html
<View className="scan" onClick={this.scan}>
    <Text className="text">
        扫一扫
    </Text>
</View>
```

**期望行为**

功能正常可用，返回<scanCode.Promised>。

**报错信息**

![tim 20181031191523](https://user-images.githubusercontent.com/13047250/47784796-9fe50800-dd41-11e8-90dc-c56048e17043.png)

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [v.1.0.5]
 - Node.js 版本 [e.g. v8.9.3]
 - 报错平台 [weapp]

为快速排查问题提供一张demo图

![ean-13-test](https://user-images.githubusercontent.com/13047250/47785316-51d10400-dd43-11e8-98b5-619f7d9ef64e.png)

**Comment by luckyadam** [comment]
换成 wx.scanCode 试试，如果不行的话，就是图片的问题了

**Comment by yujiaming890321** [comment]
试了 wx.scanCode 也不好使，应该是图片问题。
@luckyadam 辛苦了~

**Comment by yujiaming890321** [comment]
排查了一圈，很坑的一个问题。
用 **微信开发者**工具 扫图是扫不出来的。
浏览以后用 **真机** 扫图是ok的。

**Comment by lxmbetterman** [comment]
我用上面的代码，用微信开发者工具 连接真机调试，扫barCode 可以。但是扫qrcode， 始终扫不出结果也不报错，我参数配了的 scanType: ['barCode', 'qrCode'], 
尝试中..

**Comment by lxmbetterman** [comment]
> 我用上面的代码，用微信开发者工具 连接真机调试，扫barCode 可以。但是扫qrcode， 始终扫不出结果也不报错，我参数配了的 scanType: ['barCode', 'qrCode'],
> 尝试中..
默认参数是非必填的，重新运行下就ok了，应该是缓存问题
