### ISSUE TITLE
当编译为原生小程序组件时自定义组件 options

### ISSUE THREAD

**Issue by yhsunshining** [NervJS/taro#9759]
### 这个特性解决了什么问题？
自定义optison 可以设置 [virtualHost](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html) 以减少组件在应用中的包裹层级，也可以设置[styleIsolation](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB) 来在应用中穿透样式。对于使用taro编译到原生组件使用的项目，原有项目中可能依赖此类特性。

### 这个 API 长什么样？
添加编译配置，或者组件配置来完成功能。

**Comment by Chen-jj** [comment]
Taro v3.3.20+ 可以通过组件配置来设置了~
