### ISSUE TITLE
为什么setState后 ，页面不会重新渲染呢？

### ISSUE THREAD

**Issue by EForinaJ** [NervJS/taro#976]
我页面初始化的数据isOpened为false，
![qq 20181031231538](https://user-images.githubusercontent.com/22424208/47798295-13e3d800-dd63-11e8-97ea-d0025a30e203.png) 然后我在判断这个登录缓存状态的时候，把这个isOpened 设置为true了，控制台打印出来也是true
![qq 20181031231554](https://user-images.githubusercontent.com/22424208/47798368-337b0080-dd63-11e8-85d3-28a90a9f7ef8.png)

![qq 20181031231615](https://user-images.githubusercontent.com/22424208/47798425-4f7ea200-dd63-11e8-8149-f4de873d4ea9.png)

而且我下面AtModal的isOpened 也没写错  为什么这个模态框 state改变后不能出现呢？只有在初始化的时候设置为true 才能弹出来 这个 模态框 setState 后 就不见弹出来了

![qq 20181031231945](https://user-images.githubusercontent.com/22424208/47798539-8ce32f80-dd63-11e8-9519-63056fd9e9b9.png)

**Comment by vimcaw** [comment]
`setState` 是异步操作，不会马上触发视图更新，

```js
this.setState({
  data,
}, () => {
  // 此时才会更新
  console.log(this.state.data)
})
```

或者你在 render 函数里打印 `this.state.data.isOpened` 看看

**Comment by Qiu800820** [comment]
之前也遇到过类似的问题， setState 后没触发render  最后是this指向不对。 试着用this.check_login_status.bind(this)试试

**Comment by loveholly** [comment]
目测是不应该在 `componentWillMount` 里面去 `setState`
