### ISSUE TITLE
vue3 <script setup>语法糖里面的方法与<script>混用时，在<script>onShow，onPullDownRefresh等生命周期内，build的时读取不到，dev时没问题

### ISSUE THREAD

**Issue by Dizzy-zz** [NervJS/taro#9761]
### 相关平台
支付宝小程序

**小程序基础库: 1.0**
**使用框架: Vue 3**

### 复现步骤
<script>
export default {
  onPullDownRefresh() {
    this.click(); // // build的时候为undefined  dev正常
  },
  onShow() {
    this.click(); // build的时候为undefined  dev正常
  },
  mounted() {
    console.log(this.click);
  },
};
</script>

<script setup>
import { ref } from "vue";
import styles from "./index.module.scss";

const show = ref(true);
const click = () => {
  console.log("111");
};
</script>

<template>
  <view :class="styles.index" @tap="click"> ddd </view>
</template>

### 期望结果
build打包的时候不报错

### 实际结果
build打包的时候报错，dev的时候正常运行

### 环境信息
```
Taro CLI 3.2.16 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v14.17.3/bin/npm
    npmPackages:
      @tarojs/components: 3.2.16 => 3.2.16 
      @tarojs/mini-runner: 3.2.16 => 3.2.16
      @tarojs/runtime: 3.2.16 => 3.2.16 
      @tarojs/taro: 3.2.16 => 3.2.16 
      @tarojs/webpack-runner: 3.2.16 => 3.2.16 
      babel-preset-taro: 3.2.16 => 3.2.16 
      eslint-config-taro: 3.2.16 => 3.2.16
```

**Comment by Chen-jj** [comment]
@Dizzy-zz 没有复现，升级一下 Taro 和 Vue 再试试

```js
<script>
export default {
  onPullDownRefresh() {
    this.click(); // // build的时候为undefined  dev正常
  },
  onShow() {
    console.log('onShow'); // build的时候为undefined  dev正常
  },
  mounted() {
    console.log('mounted');
  },
};
</script>

<script setup>
import { ref } from "vue";

const show = ref(true);
const click = () => {
  console.log("111");
};
</script>

<template>
  <view @tap="click"> ddd </view>
</template>
```

![image](https://user-images.githubusercontent.com/11807297/125913515-c6049d0b-c565-41fa-99d4-002f78890902.png)

**Comment by Dizzy-zz** [comment]
build之后，这里就报错










在 2021-07-16 16:01:02，"chenjiajian" ***@***.***> 写道：

@Dizzy-zz 没有复现，升级一下 Taro 和 Vue 再试试

<script>

export default {onPullDownRefresh(){this.click();// // build的时候为undefined  dev正常},

  onShow() {console.log('onShow');// build的时候为undefined  dev正常},

  mounted() {console.log('mounted');},

};</script><scriptsetup>import{ref}from"vue";constshow=ref(true);constclick=()=>{console.log("111");};</script><template><view @tap="click"> ddd </view></template>

**Comment by Chen-jj** [comment]
@Dizzy-zz 印象中 vue compiler 在 prod 模式下有优化，把 `render` 函数放在 `setup` 里了。这时 `click` 作为闭包，而不是作为组件的属性。

两次的编译结果是不一样的：

```html
<script>
export default {
  onPullDownRefresh() {
    this.click(); // // build的时候为undefined  dev正常
  },
  onShow() {
    this.click(); // build的时候为undefined  dev正常
  },
  mounted() {
    console.log(this.click);
  },
};
</script>

<script setup>
import { ref } from "vue";

const show = ref(true);
const click = () => {
  console.log("111");
};
</script>

<template>
  <view @tap="click"> ddd </view>
</template>
```

![image](https://user-images.githubusercontent.com/11807297/125916393-88916cd1-5dde-4722-b204-8669401b2f9e.png)

可以建一个普通的 Vue3 项目测试一下 `mounted` 是否能 log 成功：

```html
<script>
export default {
  mounted() {
    console.log(this.click);
  },
};
</script>

<script setup>
import { ref } from "vue";

const show = ref(true);
const click = () => {
  console.log("111");
};
</script>

<template>
  <view @tap="click"> ddd </view>
</template>
```

**Comment by Dizzy-zz** [comment]
谢谢解答！



在 2021-07-16 16:22:29，"chenjiajian" ***@***.***> 写道：

@Dizzy-zz 印象中 vue compiler 在 prod 模式下有优化，把 render 函数放在 setup 里了。这时 click 作为闭包，而不是作为组件的属性。

两次的编译结果是不一样的：

<script>exportdefault{onPullDownRefresh(){this.click();// // build的时候为undefined  dev正常},onShow(){this.click();// build的时候为undefined  ***@***.***="click"> ddd </view></template>

可以建一个普通的 Vue3 项目测试一下 mounted 是否能 log 成功：

***@***.***="click"> ddd </view></template>
