### ISSUE TITLE
原生微信小程序集成taro打开页面空白

### ISSUE THREAD

**Issue by vinurs** [NervJS/taro#9766]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/vinurs/taro-blended](https://github.com/vinurs/taro-blended)
**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
1. clone代码
2. cd taro-project
3. yarn dev:weapp --blended
4. 打开微信调程序跳转到taro的页面

### 期望结果
期望显示出Hello world! Taro index

### 实际结果
实际显示的却是一个空白页面

### 环境信息
```
taro info
👽 Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    npmPackages:
      @tarojs/components: 3.3.0 => 3.3.0
      @tarojs/mini-runner: 3.3.0 => 3.3.0
      @tarojs/react: 3.3.0 => 3.3.0
      @tarojs/runtime: 3.3.0 => 3.3.0
      @tarojs/taro: 3.3.0 => 3.3.0
      @tarojs/webpack-runner: 3.3.0 => 3.3.0
      babel-preset-taro: 3.3.0 => 3.3.0
      eslint-config-taro: 3.3.0 => 3.3.0
      react: ^17.0.0 => 17.0.2
```

---
### 补充信息
https://github.com/NervJS/taro-blended  这里的代码我测试了一下是可以，我只是从零开始增加了一个最简单的页面，不知道是不是哪里缺少了什么步骤，文档也看了，但是找不出原因，麻烦帮我看一下

**Comment by Chen-jj** [comment]
@vinurs 降级 Taro 的版本试试，例如使用 3.2、3.1 试试

**Comment by vinurs** [comment]
@Chen-jj 一样的结果，不知道为什么Taro的页面一直是空白，也没什么报错

**Comment by Chen-jj** [comment]
@vinurs Taro 项目**不要放在原生项目里**，小程序会尝试编译项目中所有的文件。

可以参考 Demo 那样组织方式：

![image](https://user-images.githubusercontent.com/11807297/126332186-75e958e9-6fb6-43a0-a3e3-df02ece7480c.png)

**Comment by vinurs** [comment]
@Chen-jj 谢谢啦，原来要这么组织，困扰我很久了
