### ISSUE TITLE
希望支持微信分享图片API

### ISSUE THREAD

**Issue by runningmaverick** [NervJS/taro#9767]
### 这个特性解决了什么问题？
Taro当前API无法实现图片直接分享，微信已经提供直接分享图片API，wx.showShareImageMenu。

### 这个 API 长什么样？
支持wx.showShareImageMenu API，以及微信增加的其他几个分享API。

**Comment by Chen-jj** [comment]
@runningmaverick 3.3 已支持，又因为这些 API 本身就支持 Promise 调用，所以 `Taro.xxx` 只会简单调用 `wx.xxx`，不需要再封装。

**Comment by zmm2tysu** [comment]
> @runningmaverick 3.3 已支持，又因为这些 API 本身就支持 Promise 调用，所以 `Taro.xxx` 只会简单调用 `wx.xxx`，不需要再封装。

Taro. showShareImageMenu() 没法调用啊

**Comment by Chen-jj** [comment]
> showShareImageMenu

@zmm2tysu 最新版本可以用

![image](https://user-images.githubusercontent.com/11807297/131838136-f2a8860f-b66a-457f-aef7-fe77534e73ce.png)
