### ISSUE TITLE
rn现在还不支持使用vue3编译吗

### ISSUE THREAD

**Issue by pecopeco** [NervJS/taro#9770]
### 这个特性解决了什么问题？
执行 build:rn 报错：
``
[BABEL] C:\Users\yang\Desktop\taro-start\node_modules\metro\src\node-haste\DependencyGraph\assets\empty-module.js: Value "vue3" of option "framework" is not supported for React-Native 
(While processing: "C:\\Users\\yang\\Desktop\\taro-start\\node_modules\\babel-preset-taro\\index.js")
``
### 这个 API 长什么样？
Value "vue3" of option "framework" is not supported for React-Native
看这个描述是现在还不支持vue3？

**Comment by zhiqingchen** [comment]
不支持，建议使用react。

**Comment by jigsaw-china** [comment]
还不支持啊。。。

**Comment by MengerZhang** [comment]
2024年了，啥时候能支持呢

**Comment by eneisyou** [comment]
2025年了
