### ISSUE TITLE
jest 测试时报错 急...

### ISSUE THREAD

**Issue by chenjunjia97** [NervJS/taro#9773]
### 相关平台
H5

**浏览器版本: Chrome 62**
**使用框架: React**

### 复现步骤
测试报错

### 期望结果
1

### 实际结果
出现报错
![image](https://user-images.githubusercontent.com/49097606/125405203-0921e200-e3ea-11eb-8637-050bd4a83f3f.png)

babel-config.js 配置
![image](https://user-images.githubusercontent.com/49097606/125405299-2951a100-e3ea-11eb-8558-5766f1f90c24.png)

jest.config.js 配置
![image](https://user-images.githubusercontent.com/49097606/125405398-45edd900-e3ea-11eb-967d-39f3f214da2b.png)

### 环境信息
```
👽 Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\work\nodejs\node.EXE
      npm: 6.14.11 - C:\Program Files\work\nodejs\npm.CMD
```

---
### 补充信息
是用jest单测遇到的问题

**Comment by chenjunjia97** [comment]
@Chen-jj 大佬看看

**Comment by Chen-jj** [comment]
检查看看是不是 `import` 和 `module.exports` 混用了。

**Comment by chenjunjia97** [comment]
> 检查看看是不是 `import` 和 `module.exports` 混用了。

![image](https://user-images.githubusercontent.com/49097606/125410674-b9deb000-e3ef-11eb-9781-0bd1ca3a1c7e.png)
可是我import 的是这几个

**Comment by goldEli** [comment]
![image](https://user-images.githubusercontent.com/18217162/125554369-327c27df-f9da-4402-962b-821cf1939ff7.png)
@chenjunjia97 把  `/node_modules` 注销就可以了。
```js
  transformIgnorePatterns: [
    // "/node_modules/",
    "^.+\\.(css|sass|scss|less)$",
  ],
```

**Comment by chenjunjia97** [comment]
> ![image](https://user-images.githubusercontent.com/18217162/125554369-327c27df-f9da-4402-962b-821cf1939ff7.png)
> @chenjunjia97 把 `/node_modules` 注销就可以了。
> 
> ```js
>   transformIgnorePatterns: [
>     // "/node_modules/",
>     "^.+\\.(css|sass|scss|less)$",
>   ],
> ```

还是不行额一直报的那个错 @goldEli

**Comment by goldEli** [comment]
![image](https://user-images.githubusercontent.com/18217162/125555549-6cb13fd8-1079-41e7-ac8c-e1be3ef50437.png)
@chenjunjia97  这行也删了

**Comment by chenjunjia97** [comment]
> ![image](https://user-images.githubusercontent.com/18217162/125555549-6cb13fd8-1079-41e7-ac8c-e1be3ef50437.png)
> @chenjunjia97 这行也删了

![image](https://user-images.githubusercontent.com/49097606/125555794-99131021-52b5-4cf4-99a1-d89ef6a0973d.png)
![image](https://user-images.githubusercontent.com/49097606/125555862-5d74950e-44bc-4d2c-b141-0a6078403423.png)
唉....

**Comment by goldEli** [comment]
@chenjunjia97 你咋又加上去了，不要 `/node_modules`
![image](https://user-images.githubusercontent.com/18217162/125556083-7a5c282c-412e-4260-b62f-0a1e2d14e307.png)

**Comment by chenjunjia97** [comment]
> @chenjunjia97 你咋又加上去了，不要 `/node_modules`
> ![image](https://user-images.githubusercontent.com/18217162/125556083-7a5c282c-412e-4260-b62f-0a1e2d14e307.png)

0.0可以了但是引入Taro.request不行 @goldEli 
![image](https://user-images.githubusercontent.com/49097606/125556298-5d4049b1-3b8f-4ef0-bc70-b2abb391cea4.png)
![image](https://user-images.githubusercontent.com/49097606/125556423-9a8899dc-562a-4f49-bd7a-a8dd9cc207ed.png)

**Comment by chenjunjia97** [comment]
@goldEli 感谢大佬帮忙解决了，为什么得删掉nodemodules才行，我看别人的配置都是有配这个的

**Comment by goldEli** [comment]
@chenjunjia97 客气了。我也不知道为什么，我是偶然试出来的。
>Taro.request is not a function
请问 这个问题解决了吗

**Comment by chenjunjia97** [comment]
> @chenjunjia97 客气了。我也不知道为什么，我是偶然试出来的。
> 
> > Taro.request is not a function
> > 请问 这个问题解决了吗

没呢、正在搜原因......

**Comment by chenjunjia97** [comment]
> > @chenjunjia97 客气了。我也不知道为什么，我是偶然试出来的。
> > > Taro.request is not a function
> > > 请问 这个问题解决了吗
> 
> 没呢、正在搜原因...... @goldEli

**Comment by ZakaryCode** [comment]
[Jest 参考文档](https://nervjs.github.io/taro/docs/next/external-libraries/#jest)
