### ISSUE TITLE
button的openType为share时，转成支付宝、钉钉小程序无法分享。

### ISSUE THREAD

**Issue by w602542704** [NervJS/taro#9776]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/BinZhiZhu/Taro-v2ex-weapp](https://github.com/BinZhiZhu/Taro-v2ex-weapp)
**小程序基础库: 最新**
**使用框架: React**

### 复现步骤
1.hooks开发button的openType为share时,
2.转出支付宝或钉钉小程序，
3.出现支付宝或钉钉小程序的button依然是openType，还是驼峰字段，不是open-type, 测试转成微信小程序可以。

### 期望结果
能分享

### 实际结果
不能分享

### 环境信息
```
👽 Taro v3.3.0-alpha.8


  Taro CLI 3.3.0-alpha.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.1 - D:\myLib\node\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - D:\myLib\node\npm.CMD
```

**Comment by Chen-jj** [comment]
@w602542704 没有复现，升级到最新版再试试

```js
<Button openType='share'>click</Button>
```

![image](https://user-images.githubusercontent.com/11807297/125882497-38a27980-6de5-4d5e-9c7b-9d7f60fe80f5.png)
