### ISSUE TITLE
3.3.0微信小程序 没有找到页面实例

### ISSUE THREAD

**Issue by liyaxin58** [NervJS/taro#9778]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/liyaxin58/taroproject/tree/master](https://github.com/liyaxin58/taroproject/tree/master)
**小程序基础库: 2.17.3**
**使用框架: Vue 2**

### 复现步骤
1.cnpm install
2.npm run dev  ->  编译成功
3.打开微信小程序 console控制台提示
VM78 WAService.js:2 Error: 没有找到页面实例。
如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues

### 期望结果
正常编译

### 实际结果
VM78 WAService.js:2 Error: 没有找到页面实例。
如有疑问，请提交 issue 至：https://github.com/nervjs/taro/issues
    at ae (taro.js? [sm]:2)
    at taro.js? [sm]:2
    at Sr.updateSync (taro.js? [sm]:2)
    at Sr.mount (taro.js? [sm]:2)
    at Object.mount (taro.js? [sm]:2)
    at l (taro.js? [sm]:2)
    at qi.onLoad (taro.js? [sm]:2)
    at qi.<anonymous> (VM78 WAService.js:2)
    at qi.r.__callPageLifeTime__ (VM78 WAService.js:2)
    at Cn (VM78 WAService.js:2)(env: Windows,mp,1.05.2106300; lib: 2.17.3)

### 环境信息
```
Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.22.3 - D:\nodejs12\node.EXE
      npm: 6.14.13 - D:\nodejs12\npm.CMD
```

**Comment by Chen-jj** [comment]
@liyaxin58 Vue2 的入口组件写法有 Breaking Changes： https://docs.taro.zone/docs/next/vue-entry

**Comment by liyaxin58** [comment]
> @liyaxin58 Vue2 的入口组件写法有 Breaking Changes：https://docs.taro.zone/docs/next/vue-entry

看了下文档 把app.js的const App = new Vue({}) 改成 const App = {}就好了，谢谢大神指导

**Comment by LewinJun** [comment]
> @liyaxin58 Vue2 的入口组件写法有 Breaking Changes： https://docs.taro.zone/docs/next/vue-entry

3.3.0也有这个问题
