### ISSUE TITLE
希望在taro vue3版本中实现对应 react的 taro.hooks 的 Composition API 

### ISSUE THREAD

**Issue by panhezeng** [NervJS/taro#9779]
### 这个特性解决了什么问题？
解决在 vue3 setup 中使用微信小程序生命周期方法的需求。类似 import { onMounted } from "vue"; 对应的 import { onReady, onShow } from "@tarojs/taro";

### 这个 API 长什么样？
import { onReady, onShow } from "@tarojs/taro";

setup() {

   onShow(() => {
      console.log("onShow");
    });

}

**Comment by hyccpq** [comment]
这个太希望有了，有就太好了

**Comment by marsDes** [comment]
vue3 页面组件 onReady 无效！
```js
  ...
  export default {
  mounted () {
    console.log('mounted')
  },
  onReady () {
    console.log('onReady') // nothing happened
  }
  ...
```

**Comment by CaicoLeung** [comment]
+1

**Comment by Chen-jj** [comment]
Taro v3.4.0 开始支持
