### ISSUE TITLE
最新的taro init app，不支持支付宝和百度小程序了？

### ISSUE THREAD

**Issue by fanlvwen** [NervJS/taro#978]
package.json里面的scripts
`"scripts": {
    "build:weapp": "taro build --type weapp",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  }`
没有支付宝和百度了吗？

npm run build:alipay -- --watch
报错：
 Taro v1.0.7
开始编译项目 myTaro
输入类型错误，目前只支持weapp/h5/rn三端类型

请问是哪里操作错了吗？

**Comment by luckyadam** [comment]
升级到最新的 beta 版本

**Comment by luckyadam** [comment]
![image](https://user-images.githubusercontent.com/1782542/47831009-a6b75d80-ddc9-11e8-96ce-3647cbadfc39.png)

**Comment by fanlvwen** [comment]
根据官方文档：$ npm install -g @tarojs/cli
下载下来得就是1.0.7  你这个是怎么操作的请问

**Comment by fanlvwen** [comment]
手动下载 npm install -g @tarojs/cli@1.1.0-beta.15 可以了，谢谢！
但是按照官网 $ npm install -g @tarojs/cli 下载下来得就是1.0.7

**Comment by luckyadam** [comment]
因为是 beta 版本
