### ISSUE TITLE
钉钉小程序的分享报错 Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by w602542704** [NervJS/taro#9780]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/BinZhiZhu/Taro-v2ex-weapp](https://github.com/BinZhiZhu/Taro-v2ex-weapp)
**小程序基础库: 最新**
**使用框架: React**

### 复现步骤
钉钉分享
<Button openType="share" />
钉钉报 Cannot read property 'target' of undefined

你们源码： config.onShareAppMessage = function (options) {
  var target = options.target;...
}
是你们代码里以为有 options.target , 其实options是undefined，所以报错导致钉钉不能分享。

### 期望结果
能分享

### 实际结果
不能分享

### 环境信息
```
👽 Taro v3.3.0-alpha.8


  Taro CLI 3.3.0-alpha.8 environment info:
    System:
      OS: Windows 10        
    Binaries:
      Node: 14.16.1 - D:\myLib\node\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD    
      npm: 6.14.12 - D:\myLib\node\npm.CMD
```

---
### 补充信息
你们这样改就可以了：
    config.onShareAppMessage = function (options) {

      if(options){ //你们少了这个判断
      var target = options.target;

      if (target != null) {
        var _id = target.id;
        var element = document$1.getElementById(_id);

        if (element != null) {
          options.target.dataset = element.dataset;
        }
      }

**Comment by w602542704** [comment]
![image](https://user-images.githubusercontent.com/24689873/125555856-607c0746-e89f-4487-a2b1-8b3613bf9e4f.png)

**Comment by w602542704** [comment]
![image](https://user-images.githubusercontent.com/24689873/125556046-5dce65af-5f51-481b-8507-48b838bb4412.png)

**Comment by Chen-jj** [comment]
@w602542704 可以来个 PR 哈～

**Comment by w602542704** [comment]
> @w602542704 可以来个 PR 哈～

什么是PR？
