### ISSUE TITLE
config/index.js 配置rn.output之后，编译报错

### ISSUE THREAD

**Issue by titanseason** [NervJS/taro#9781]
### 相关平台
React Native

### 复现仓库
[https://github.com/titanseason/taro-demo](https://github.com/titanseason/taro-demo)

**使用框架: React**

### 复现步骤
1. 使用taro-cli新建一个项目，framework选择react，其他默认即可
2. 执行 npm install 
3. 执行 npm run build:rn - 编译成功
4. 在 config/index.js中，按照 https://taro-docs.jd.com/taro/docs/config-detail#rnappname 文档增加 rn.output 配置，然后执行npm run build:rn，编译失败

### 期望结果
编译成功

### 实际结果
编译失败：

D:\project\demo-taro\node_modules\metro-hermes-compiler\src\emhermesc.js:81
          throw ex;
          ^

RuntimeError: abort(TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined). Build with -s ASSERTIONS=1 for more info.
    at process.abort (D:\project\demo-taro\node_modules\metro-hermes-compiler\src\emhermesc.js:796:13)
    at process.emit (events.js:310:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! demo-taro@1.0.0 build:rn: `taro build --type rn`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the demo-taro@1.0.0 build:rn script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-07-14T03_15_46_953Z-debug.log

### 环境信息
```
� Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\xxx\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - D:\Program Files\nodejs\npm.CMD
```

**Comment by zhiqingchen** [comment]
下个版本修复，可先配一下`output.rn` 中的 `androidSourcemapOutput` 和`iosSourcemapOutput`为''

**Comment by LingKKKK** [comment]
我用你的项目进行 build:rn 为什么只输出的安卓的包，并没有IOS的包？ 求解呀

**Comment by zhiqingchen** [comment]
> 我用你的项目进行 build:rn 为什么只输出的安卓的包，并没有IOS的包？ 求解呀

taro build --type rn --platform ios
