### ISSUE TITLE
Taro写的三方库组件样式渲染不正确

### ISSUE THREAD

**Issue by yangqi1024** [NervJS/taro#9782]
### 这个特性解决了什么问题？
使用Taro写的三方库组件的样式解析没有遵循
设计稿及尺寸单位：https://taro-docs.jd.com/taro/docs/size

### 这个 API 长什么样？
期望能正常解析

**Comment by shenghanqin** [comment]
哪一个第三方库呢？是想按照1倍解析还是2倍的呢？

**Comment by yangqi1024** [comment]
> 哪一个第三方库呢？是想按照1倍解析还是2倍的呢？

三方的组件库是自己基于Taro写的，至于是按照几倍的解析应该是根据项目的配置文件来解析
/config/index.js
const config = {
  projectName: 'myProject',
  designWidth: 750,
  ....
}
正常来说Taro 默认会对所有单位进行转换。在 Taro 中书写尺寸按照 1:1 的关系来进行书写，即从设计稿上量的长度 100px，那么尺寸书写就是 100px，当转成微信小程序的时候，尺寸将默认转换为 100rpx，当转成 H5 时将默认转换为以 rem 为单位的值。
但是目前来看三方库是没有这样处理的

**Comment by Chen-jj** [comment]
@yangqi1024 debug 一下是否有使用这个 postcss 插件：

https://github.com/NervJS/taro/blob/902b7554eb536b106b237fdc6996300257f38a07/packages/taro-mini-runner/src/webpack/postcss.conf.ts#L61-L63

然后确定 postcss-loader 是否有处理你的样式文件：

https://github.com/NervJS/taro/blob/902b7554eb536b106b237fdc6996300257f38a07/packages/taro-mini-runner/src/webpack/chain.ts#L394-L413

最后 Bug Report 类问题请使用对应 issue 模版。
