### ISSUE TITLE
reactnative 使用 css cssModules 时 动态设置 className  值 样式失效

### ISSUE THREAD

**Issue by xiehui999** [NervJS/taro#9784]
### 相关平台
React Native

### 复现仓库
[https://github.com/xiehui999/test](https://github.com/xiehui999/test)

**使用框架: React**

### 复现步骤
点击加demo加号，根据值动态 设置底部字体颜色样式

### 期望结果
num % 2 ? style.red: style.blue  动态设置字体颜色

### 实际结果
无效果

### 环境信息
```
? Taro v3.2.10


  Taro CLI 3.2.10 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.10 => 3.2.10 
      @tarojs/mini-runner: 3.2.10 => 3.2.10 
      @tarojs/react: 3.2.10 => 3.2.10 
      @tarojs/runtime: 3.2.10 => 3.2.10 
      @tarojs/taro: 3.2.10 => 3.2.10 
      @tarojs/webpack-runner: 3.2.10 => 3.2.10 
      babel-preset-taro: 3.2.10 => 3.2.10 
      eslint-config-taro: 3.2.10 => 3.2.10 
      react: ^17.0.0 => 17.0.2 
      react-native: 0.63.2 => 0.63.2 

```

---
### 补充信息
如果不动态设置，只设置 style.red，或者 style.blue 是有效的

**Comment by iambool** [comment]
rn还不支持设置generateScopedName的，目前仅支持设置namingPattern

**Comment by xiehui999** [comment]
> generateScopedName

把 generateScopedName 删掉也是不可以的，也是没有效果

**Comment by iambool** [comment]
可复现，直接赋值给变量某个样式同样无效 @shinken008 ，复现demo：
```jsx
/**
// index.module.scss
.active {
    color: red;
    font-weight: bold;
  }
*/
import React, { Component } from 'react'
import { Text } from '@tarojs/components'
import styles from './index.module.scss'

export default class Tab extends Component {
  render () {
    const textClass = styles.active;
    return (
      // <Text className={styles.active}>Hello</Text>
      <Text className={textClass}>Hello</Text>
    )
  }
}
```

**Comment by zhiqingchen** [comment]
问题我们要再研究一下，可以先用style代替
```
<Text style={textClass}>Hello</Text>
```

**Comment by shinken008** [comment]
样式文件既可以引入 css module 和 正常样式
className 作为一个表达式既可以是正常的className 又可以是 css module，所以在表达式这一层进行判断是否引用了 css module 导出的变量

如果赋值表达式，比如： `const textClass = styles.active;` 可能有很多层赋值的方法，一层一层溯源困难，但大部分有赋值表达式的场景应该是一次赋值，因此后续我会对赋值表达式判断是否引用 css module 导出的变量，解决大部分人的问题，多层还是有这个问题

另外可以使用了 style 来代替 className

**Comment by xiehui999** [comment]
> 样式文件既可以引入 css module 和 正常样式
> className 作为一个表达式既可以是正常的className 又可以是 css module，所以在表达式这一层进行判断是否引用了 css module 导出的变量
> 
> 如果赋值表达式，比如： `const textClass = styles.active;` 可能有很多层赋值的方法，一层一层溯源困难，但大部分有赋值表达式的场景应该是一次赋值，因此后续我会对赋值表达式判断是否引用 css module 导出的变量，解决大部分人的问题，多层还是有这个问题
> 
> 另外可以使用了 style 来代替 className
我尝试过，如果改为style ，在H5，小程序就 不支持， 那就需要根据平台去判断是用style还是className. 这样多好多代码。 也就说如果开发的平台支持RN就不能使用css module了。 暂时方案就这样了，不用css Module

**Comment by shinken008** [comment]
可以把变量写在 className 表达式里面的

**Comment by shinken008** [comment]
> > 样式文件既可以引入 css module 和 正常样式
> > className 作为一个表达式既可以是正常的className 又可以是 css module，所以在表达式这一层进行判断是否引用了 css module 导出的变量
> > 如果赋值表达式，比如： `const textClass = styles.active;` 可能有很多层赋值的方法，一层一层溯源困难，但大部分有赋值表达式的场景应该是一次赋值，因此后续我会对赋值表达式判断是否引用 css module 导出的变量，解决大部分人的问题，多层还是有这个问题
> 
> > 另外可以使用了 style 来代替 className
> 
> 我尝试过，如果改为style ，在H5，小程序就 不支持， 那就需要根据平台去判断是用style还是className. 这样多好多代码。 也就说如果开发的平台支持RN就不能使用css module了。 暂时方案就这样了，不用css Module

可以把变量计算写在 className 表达式里面的，赋值后面会支持一次
