### ISSUE TITLE
H5无法上传formData

### ISSUE THREAD

**Issue by okilled** [NervJS/taro#9786]
### 相关平台
H5

**浏览器版本: Chrome 91**
**使用框架: React**

### 复现步骤
1. 使用 Taro.request
2. 指定 contentType = 'multipart/form-data‘，data里使用formData
3. 查看network中请求头，因为显示指定contentType，导致缺少boundary

### 期望结果
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryyEmKNDsBKjB7QEqu

### 实际结果
Content-Type:multipart/form-data

### 环境信息
```
 Taro CLI 3.2.13 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.0 => 3.3.0
      @tarojs/components: 3.3.0 => 3.3.0
      @tarojs/mini-runner: 3.3.0 => 3.3.0
      @tarojs/react: 3.3.0 => 3.3.0
      @tarojs/runtime: 3.3.0 => 3.3.0
      @tarojs/taro: 3.3.0 => 3.3.0
      @tarojs/webpack-runner: 3.3.0 => 3.3.0
      babel-preset-taro: ^3.3.0 => 3.3.0
      react: ^17.0.2 => 17.0.2
      taro-ui: ^3.0.0-alpha.10 => 3.0.0-alpha.10
```

---
### 补充信息
https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post

**Comment by Chen-jj** [comment]
@okilled 看了 stackoverflow 的回答，这应该是 fetch API 的标准行为，可以取消设置 `contentType` 试试。

**Comment by okilled** [comment]
> @okilled 看了 stackoverflow 的回答，这应该是 fetch API 的标准行为，可以取消设置 `contentType` 试试。

感谢你的回复

如果取消设置contentType，当参数类型是formData时Taro.request的contentType依然是默认值application/json
按照stackoverflow里面的操作，设置成undefined，Taro.request会出现报错
![image](https://user-images.githubusercontent.com/23131376/126301739-0623e053-5676-4f20-8722-776c41aefa1c.png)

**Comment by okilled** [comment]
> @okilled 看了 stackoverflow 的回答，这应该是 fetch API 的标准行为，可以取消设置 `contentType` 试试。

应该是这行判断不严谨，formData类型也是object，导致给contentType设置了application/json，可以使用Object.prototype.toString.call来判断
![image](https://user-images.githubusercontent.com/23131376/126305561-9a056da6-0d32-49ce-96ee-27e1bf8d423d.png)

**Comment by adamgogogo** [comment]
my god...

**Comment by leifeng** [comment]
一样的问题，解决了吗？

**Comment by talentjeff** [comment]
设了undefined还是不行

**Comment by GitKou** [comment]
和这个一样，https://github.com/NervJS/taro/issues/5514#issuecomment-1107788211，

![image](https://user-images.githubusercontent.com/7437397/164966906-6cd9df2e-e740-45a7-8812-010414d97b16.png)
![image](https://user-images.githubusercontent.com/7437397/164966913-7b923f6e-a0b8-42d4-b59b-95165126a062.png)
设置成undefined这里会报错

**Comment by yoyo837** [comment]
这个问题应该尽快解决, 属于基础建设受影响的部分.

**Comment by yoyo837** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/6134547/190946273-91692fe6-58ea-4847-8777-362e95d3e954.png">

这个可以呀
