### ISSUE TITLE
h5 触发一个方法后  会  render  多次 这样数据放在redux里  获取后 会导致数据错乱

### ISSUE THREAD

**Issue by QTTQ** [NervJS/taro#979]
如果是提交 bug，请搜索文档和 issue，确认以下事项：

* 该问题没有在其他 issue 和文档讨论到，不属于重复内容

* 分割线以下的模板除了「 补充信息」每一样都必填

如果不满足以上两点要求的 bug 报告，issue 会被直接关掉。

请多多理解，您现在的不便将会使 Taro 开发者更高效地定位你的问题，修复你的问题。像你一样的 Taro 的使用者也可以通过搜索找到你提供的 bug，对各方都有很大好处。

🙏🙏🙏
阅读完后请在提交的issue中删除以上内容，包括分割线。
------------------------

**问题描述**
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```
![image](https://user-images.githubusercontent.com/22019544/47829838-60133480-ddc4-11e8-9efa-9d852035fee0.png)

**期望行为**
[这里请用简洁清晰的语言描述你期望的行为]
期望的是触发加载更多以后 只render一次 新请求的数据拼接在原有数组里去 
**报错信息**
现在是  触发加载更多后 或者初始化后 会render多次  这样数据拼接 全是重复数据

[这里请贴上你的**完整**报错截图或文字]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [e.g. v.0.0.64]
 - Node.js 版本 [e.g. v9.0.0]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by jinjinjin0731** [comment]
小程序中会吗。  按你的说法，当新请求的数据加载在最底部的时候，这时候滚动条是否在底部，是的话确实会再次触发方法的，符合该 api 的。  我在本地这边先尝试复现一下你这个问题

**Comment by QTTQ** [comment]
初始化的时候   render  就会执行了三次   触发加载更多方法 只触发了一次   但是render也执行了三次

**Comment by jinjinjin0731** [comment]
有给组件设置 defaultProps 吗。  taro 会默认先执行一下 render 收集初始数据，然后默认值得 render 一次， 更新的数值 render 一次。 所以 三次应该对的

**Comment by jinjinjin0731** [comment]
参考 [最佳实践](https://nervjs.github.io/taro/docs/best-practice.html#%E7%BB%84%E4%BB%B6%E7%9A%84-constructor-%E4%B8%8E-render-%E6%8F%90%E5%89%8D%E8%B0%83%E7%94%A8)

**Comment by QTTQ** [comment]
哦哦  设计的就是这个样子啊  那每一页的列表数据 有十条 用redux的话  这种 每上拉一次就会重复往数组里conact三次啊  这种怎么破

**Comment by jinjinjin0731** [comment]
不是很清楚你在上拉的那个方法里面做了什么操作。麻烦贴下代码。正常情况下， 在更新数据时，你只有变更了数据才会重新 render

**Comment by QTTQ** [comment]
import Taro, { Component } from '@tarojs/taro'
import { View, ScrollView } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { AtSegmentedControl, AtCard } from 'taro-ui'
// import { add, minus, asyncAdd, asyncAddText } from '../../actions/counter'
import { loading, asyncRequset } from '../../actions/common'
import './index.scss'
// import searchPng from '../../asset/images/search.png'
// import lightingPng from '../../asset/images/lighting.png'
// import icon9 from '../../asset/images/icon9.jpeg'

class MyIndex extends Component {
  config = {
    navigationBarTitleText: '首页'
  }
  constructor() {
    super(...arguments)
    this.dataArr = []
    this.did = false
    this.state = {
      height: 0,
      current: 0,
      pages: 1,
      dataArr: []
    }
  }
  componentWillReceiveProps(nextProps) {
  }
  updateList = async () => {
    this.tokenSign = true
    if (this.props.common.loading) return
    this.setState({
      pages: 1
    }, () => {
      this.requestUrl(this.state.current)
    })
  }

  requestUrl = (n, text = "刷新中。。。") => {
    let url = "AllArticle"
    this.tokenSign = true
    if (this.props.common.loading) return
    let data = { page: this.state.pages }
    if (!this.props.common.userData.token && n == 2) {
      Taro.showToast({ title: "请先登录", icon: 'none', duration: 2000 })
      this.tokenSign = false
      return
    }
    let token = this.props.common.userData.token
    if (n == 1) {
      data = { page: this.state.pages }
      url = "GetMostThunmbArticle"
    } else if (n == 2) {
      data = { token, page: this.state.pages }
      url = "jwt/MyArticle"
    }
    this.props.asyncRequset(text, data, url)
  }
  getMoreList = async (e) => {
    console.log("---------getMoreList--------------")
    if (this.props.common.loading) return
    this.setState({
      pages: this.state.pages + e
    }, () => {
      this.requestUrl(this.state.current, "加载更多。。。")
    })
  }
  handleClick(value) {
    console.log("---------handleClick--------------")
    this.setState({
      current: value,
      pages: 1
    }, () => {
      this.did = false
      this.dataArr = []
      this.requestUrl(value)
    })
  }
  componentDidMount() {
    let self = this
    Taro.getSystemInfo({
      success(res) {
        self.setState({
          height: res.windowHeight - 46
        })
      }
    })
    this.updateList()
  }

  render() {
    const { height } = this.state
    const { listData } = this.props.homePage
    const { loading } = this.props.common
    const retViewFn = (loading, listData) => {
      this.dataArr = [...this.dataArr, ...listData]
      this.did = true
      console.log("------------render------------------");
      return !loading ? this.tokenSign || this.state.current == 0 ?
        this.dataArr.map((v, i) => {
          return <AtCard
            note={v.thunmbs}
            extra={new Date(v.ctTime).getFullYear()}
            title={v.name}
            thumb={v.actor}
          >
            {v.context}
          </AtCard>
        }) : null : <View>暂无信息。。。。。</View>
    }
    return (
      <View className="myIndex">
        <AtSegmentedControl
          values={['世界愿望', '点赞最多的愿望', '我的愿望']}
          onClick={this.handleClick.bind(this)}
          current={this.state.current}
        />
        <View className='tab-content'>
          <ScrollView className='container'
            scrollY
            scrollWithAnimation
            scrollTop='0'
            lowerThreshold="10"
            upperThreshold="10"
            // style='height:100%;position: absolute;top: 44px;background: rgb(242, 226, 230);'
            style={{ 'height': height + "px", 'background': 'rgb(242, 226, 230)' }}
            onScrollToUpper={this.updateList}
            onScrollToLower={this.getMoreList.bind(this, 1)}
          >
           {
                 retViewFn(loading, listData)
            }
          </ScrollView>
        </View>
      </View>
    )
  }
}

export default connect(({ counter, homePage, common }) => ({
  counter, homePage, common
}), (dispatch) => ({
  asyncRequset(text, data, url) {
    dispatch(asyncRequset(text, data, url))
  },
  loading() {
    dispatch(loading())
  }
}))(MyIndex)

**Comment by QTTQ** [comment]
import Taro, { Component } from '@tarojs/taro'
import { View, ScrollView } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { AtSegmentedControl, AtCard } from 'taro-ui'
// import { add, minus, asyncAdd, asyncAddText } from '../../actions/counter'
import { loading, asyncRequset } from '../../actions/common'
import './index.scss'
// import searchPng from '../../asset/images/search.png'
// import lightingPng from '../../asset/images/lighting.png'
// import icon9 from '../../asset/images/icon9.jpeg'

class MyIndex extends Component {
  config = {
    navigationBarTitleText: '首页'
  }
  constructor() {
    super(...arguments)
    this.dataArr = []
    this.did = false
    this.state = {
      height: 0,
      current: 0,
      pages: 1,
      dataArr: []
    }
  }
  componentWillReceiveProps(nextProps) {
  }
  updateList = async () => {
    this.tokenSign = true
    if (this.props.common.loading) return
    this.setState({
      pages: 1
    }, () => {
      this.requestUrl(this.state.current)
    })
  }

  requestUrl = (n, text = "刷新中。。。") => {
    let url = "AllArticle"
    this.tokenSign = true
    if (this.props.common.loading) return
    let data = { page: this.state.pages }
    if (!this.props.common.userData.token && n == 2) {
      Taro.showToast({ title: "请先登录", icon: 'none', duration: 2000 })
      this.tokenSign = false
      return
    }
    let token = this.props.common.userData.token
    if (n == 1) {
      data = { page: this.state.pages }
      url = "GetMostThunmbArticle"
    } else if (n == 2) {
      data = { token, page: this.state.pages }
      url = "jwt/MyArticle"
    }
    this.props.asyncRequset(text, data, url)
  }
  getMoreList = async (e) => {
    console.log("---------getMoreList--------------")
    if (this.props.common.loading) return
    this.setState({
      pages: this.state.pages + e
    }, () => {
      this.requestUrl(this.state.current, "加载更多。。。")
    })
  }
  handleClick(value) {
    console.log("---------handleClick--------------")
    this.setState({
      current: value,
      pages: 1
    }, () => {
      this.did = false
      this.dataArr = []
      this.requestUrl(value)
    })
  }
  componentDidMount() {
    let self = this
    Taro.getSystemInfo({
      success(res) {
        self.setState({
          height: res.windowHeight - 46
        })
      }
    })
    this.updateList()
  }

  render() {
    const { height } = this.state
    const { listData } = this.props.homePage
    const { loading } = this.props.common
    const retViewFn = (loading, listData) => {
      this.dataArr = [...this.dataArr, ...listData]
      this.did = true
      console.log("------------render------------------");
      return !loading ? this.tokenSign || this.state.current == 0 ?
        this.dataArr.map((v, i) => {
          return <AtCard
            note={v.thunmbs}
            extra={new Date(v.ctTime).getFullYear()}
            title={v.name}
            thumb={v.actor}
          >
            {v.context}
          </AtCard>
        }) : null : <View>暂无信息。。。。。</View>
    }
    return (
      <View className="myIndex">
        <AtSegmentedControl
          values={['世界愿望', '点赞最多的愿望', '我的愿望']}
          onClick={this.handleClick.bind(this)}
          current={this.state.current}
        />
        <View className='tab-content'>
          <ScrollView className='container'
            scrollY
            scrollWithAnimation
            scrollTop='0'
            lowerThreshold="10"
            upperThreshold="10"
            // style='height:100%;position: absolute;top: 44px;background: rgb(242, 226, 230);'
            style={{ 'height': height + "px", 'background': 'rgb(242, 226, 230)' }}
            onScrollToUpper={this.updateList}
            onScrollToLower={this.getMoreList.bind(this, 1)}
          >
           {
                 retViewFn(loading, listData)
            }
          </ScrollView>
        </View>
      </View>
    )
  }
}

export default connect(({ counter, homePage, common }) => ({
  counter, homePage, common
}), (dispatch) => ({
  asyncRequset(text, data, url) {
    dispatch(asyncRequset(text, data, url))
  },
  loading() {
    dispatch(loading())
  }
}))(MyIndex)

**Comment by QTTQ** [comment]
````import Taro, { Component } from '@tarojs/taro'
import { View, ScrollView } from '@tarojs/components'
import { connect } from '@tarojs/redux'
import { AtSegmentedControl, AtCard } from 'taro-ui'
// import { add, minus, asyncAdd, asyncAddText } from '../../actions/counter'
import { loading, asyncRequset } from '../../actions/common'
import './index.scss'
// import searchPng from '../../asset/images/search.png'
// import lightingPng from '../../asset/images/lighting.png'
// import icon9 from '../../asset/images/icon9.jpeg'

class MyIndex extends Component {
  config = {
    navigationBarTitleText: '首页'
  }
  constructor() {
    super(...arguments)
    this.dataArr = []
    this.did = false
    this.state = {
      height: 0,
      current: 0,
      pages: 1,
      dataArr: []
    }
  }
  componentWillReceiveProps(nextProps) {
  }
  updateList = async () => {
    this.tokenSign = true
    if (this.props.common.loading) return
    this.setState({
      pages: 1
    }, () => {
      this.requestUrl(this.state.current)
    })
  }

  requestUrl = (n, text = "刷新中。。。") => {
    let url = "AllArticle"
    this.tokenSign = true
    if (this.props.common.loading) return
    let data = { page: this.state.pages }
    if (!this.props.common.userData.token && n == 2) {
      Taro.showToast({ title: "请先登录", icon: 'none', duration: 2000 })
      this.tokenSign = false
      return
    }
    let token = this.props.common.userData.token
    if (n == 1) {
      data = { page: this.state.pages }
      url = "GetMostThunmbArticle"
    } else if (n == 2) {
      data = { token, page: this.state.pages }
      url = "jwt/MyArticle"
    }
    this.props.asyncRequset(text, data, url)
  }
  getMoreList = async (e) => {
    console.log("---------getMoreList--------------")
    if (this.props.common.loading) return
    this.setState({
      pages: this.state.pages + e
    }, () => {
      this.requestUrl(this.state.current, "加载更多。。。")
    })
  }
  handleClick(value) {
    console.log("---------handleClick--------------")
    this.setState({
      current: value,
      pages: 1
    }, () => {
      this.did = false
      this.dataArr = []
      this.requestUrl(value)
    })
  }
  componentDidMount() {
    let self = this
    Taro.getSystemInfo({
      success(res) {
        self.setState({
          height: res.windowHeight - 46
        })
      }
    })
    this.updateList()
  }

  render() {
    const { height } = this.state
    const { listData } = this.props.homePage
    const { loading } = this.props.common
    const retViewFn = (loading, listData) => {
      this.dataArr = [...this.dataArr, ...listData]
      this.did = true
      console.log("------------render------------------");
      return !loading ? this.tokenSign || this.state.current == 0 ?
        this.dataArr.map((v, i) => {
          return <AtCard
            note={v.thunmbs}
            extra={new Date(v.ctTime).getFullYear()}
            title={v.name}
            thumb={v.actor}
          >
            {v.context}
          </AtCard>
        }) : null : <View>暂无信息。。。。。</View>
    }
    return (
      <View className="myIndex">
        <AtSegmentedControl
          values={['世界愿望', '点赞最多的愿望', '我的愿望']}
          onClick={this.handleClick.bind(this)}
          current={this.state.current}
        />
        <View className='tab-content'>
          <ScrollView className='container'
            scrollY
            scrollWithAnimation
            scrollTop='0'
            lowerThreshold="10"
            upperThreshold="10"
            // style='height:100%;position: absolute;top: 44px;background: rgb(242, 226, 230);'
            style={{ 'height': height + "px", 'background': 'rgb(242, 226, 230)' }}
            onScrollToUpper={this.updateList}
            onScrollToLower={this.getMoreList.bind(this, 1)}
          >
           {
                 retViewFn(loading, listData)
            }
          </ScrollView>
        </View>
      </View>
    )
  }
}

export default connect(({ counter, homePage, common }) => ({
  counter, homePage, common
}), (dispatch) => ({
  asyncRequset(text, data, url) {
    dispatch(asyncRequset(text, data, url))
  },
  loading() {
    dispatch(loading())
  }
}))(MyIndex)

**Comment by jinjinjin0731** [comment]
你试一下在 redux 中  你的  listData 被更改了几次

**Comment by QTTQ** [comment]
初始后前两次是空，最后一次是有八条数据的，然后触发方法  listData是空 （因为我后台只写了八条数据 一页只返回十条，第二页就已经没有了 是空数组） 但是 还是render还是会更新 几次，这样导致this.dataArr重复conact本身

**Comment by jinjinjin0731** [comment]
ok 所以这是算解决是吧？ 写法问题

**Comment by QTTQ** [comment]
刚又试了一下 滑动时 会同时触发 updateList和getMoreList两个方法 导致listData 错误

**Comment by QTTQ** [comment]
有问题啊 大神   小程序里 tab栏 是滑动固定的  h5 是会飞的  而且 h5里 上拉 第一次会不好使， 而且总赶脚上拉和刷新 触发会一起触发

**Comment by jinjinjin0731** [comment]
版本是多少？ 1.0.7 版本请用   upperThreshold={10} 这样来传递。或者升级到最近的 beta 版本。tab栏 是滑动固定的 h5 是会飞的，这句没有听懂

**Comment by QTTQ** [comment]
![image](https://user-images.githubusercontent.com/22019544/47853391-88794e00-de19-11e8-9d74-161d1803de21.png)
![image](https://user-images.githubusercontent.com/22019544/47853406-98912d80-de19-11e8-801f-200bfa79c3ad.png)
还是开始的问题了  这个render  会触发三次  触发一次上拉方法会从redux里接收三次 重复数据  而且有时这个滚动事件 还是把上拉和刷新事件都触发

**Comment by QTTQ** [comment]
哦哦 谢谢  我查了一下 我把loading放redux里了 所以 没吃有请求 方法 都会触发 使其返回true false  更新了数据   谢谢  早些休息   麻烦你了

**Comment by jinjinjin0731** [comment]
: )
