### ISSUE TITLE
3.2.16升级taro 3.3.0后报错

### ISSUE THREAD

**Issue by yangjisen** [NervJS/taro#9790]
### 相关平台
微信小程序

**小程序基础库: 2.17.3**
**使用框架: Vue 3**

### 复现步骤
npm run build:weapp

### 期望结果
不产生警告

### 相关平台
微信小程序

**小程序基础库: 2.17.3**
**使用框架: Vue 3**

### 复现步骤
npm run build:weapp

### 期望结果
不产生警告

### 实际结果
有警告

### 环境信息
```
  Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD

```
---

---
### 补充信息
![image](https://user-images.githubusercontent.com/5966716/125644810-f5abf444-1708-4c89-80b3-be5a13b738b3.png)

**Comment by yangjisen** [comment]
当数组为空时, 或者使用 v-if 进行判断是会产生报错

**Comment by luan-ma** [comment]
以上两个问题都有复现，楼主为何关闭此issue？如何解决的以上2个问题？

**Comment by www295686243** [comment]
同样的问题 3.2正常 按理不应该要有警告吧

**Comment by yangjisen** [comment]
> 同样的问题 3.2正常 按理不应该要有警告吧

我以为是我自己的操作问题，然后又是一个警告。怀疑是我自己的问题，我就关闭了
