### ISSUE TITLE
独立分包模式下，生产模式 (production) 无法运行，开发模式(development) 无法获取到 taro api

### ISSUE THREAD

**Issue by vdfor** [NervJS/taro#9799]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/vdfor/taro-issue-demo-006](https://github.com/vdfor/taro-issue-demo-006)
**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
问题一重现：
1. 运行 yarn run build:weapp
2. 在首页（主包）点击按钮跳转到子页（独立分包）
3. 页面空白，控制台报错
![屏幕截图 2021-07-15 172739](https://user-images.githubusercontent.com/9846146/125764849-cc4128bb-dea9-47d4-8ec7-df6981c445e3.png) 

问题二重现
1. 运行 yarn run dev:weapp
2. 在首页（主包）点击按钮跳转到子页（独立分包）
3. 页面显示正常，但无法调用 Taro.showModal Taro.request 等 Taro Api，控制台打印 Taro 发现缺少 Taro Api
![屏幕截图 2021-07-15 164011](https://user-images.githubusercontent.com/9846146/125764636-d2b0bf71-9cda-4ec3-bc5a-801c74405341.png)
![屏幕截图 2021-07-15 164038](https://user-images.githubusercontent.com/9846146/125764643-50da6de3-cf2f-4584-a7a4-641dd5389c25.png)

### 期望结果
独立分包可正常使用

### 实际结果
独立分包无法正常使用

### 环境信息
```
Taro CLI 3.3.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    npmPackages:
      @tarojs/components: 3.3.0 => 3.3.0 
      @tarojs/mini-runner: 3.3.0 => 3.3.0 
      @tarojs/react: 3.3.0 => 3.3.0 
      @tarojs/runtime: 3.3.0 => 3.3.0 
      @tarojs/taro: 3.3.0 => 3.3.0 
      @tarojs/webpack-runner: 3.3.0 => 3.3.0 
      babel-preset-taro: 3.3.0 => 3.3.0 
      eslint-config-taro: 3.3.0 => 3.3.0 
      react: ^17.0.0 => 17.0.2 
```

**Comment by vdfor** [comment]
@luckyadam 大佬，麻烦指点下临时解决方案

**Comment by Chen-jj** [comment]
@vdfor 3.2 有这个问题么？

**Comment by vdfor** [comment]
> @vdfor 3.2 有这个问题么？

经测试，3.2.16/3.2.15 均存在此问题
