### ISSUE TITLE
taro的babel默认配置导致 jsdoc/betterdocs 出错

### ISSUE THREAD

**Issue by jpgtama** [NervJS/taro#9801]
### 相关平台
H5

### 复现仓库
[https://github.com/jpgtama/taro-jsdoc-babel-error](https://github.com/jpgtama/taro-jsdoc-babel-error)
**浏览器版本: 无需浏览器**
**使用框架: React**

### 复现步骤
1. 拉取代码
2.  进入目录，npm install
3. 运行 npm run docs即可重现

### 期望结果
成功编译jsdoc 文档

### 实际结果
出错：

Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
```
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
```
See https://babeljs.io/docs/en/options#filename for more information.

### 环境信息
```
👽 Taro v3.2.13


  Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
@jpgtama 感觉是 jsdoc 的问题。

`babel-preset-taro` 里使用了 `exclude`：

```js
overrides: [{
  exclude: [/@babel[/|\\\\]runtime/, /core-js/],
  presets,
  plugins
}]
```

如果使用了 TS，那么 `@babel/preset-typescript` 里应该也有使用类似 `exclude` 的设置。

而这些设置都要求存在 `filename`：

![image](https://user-images.githubusercontent.com/11807297/126170943-e428e37f-8fbe-4afd-90e1-7f1869da5532.png)

所以只能建议不使用 `babel-preset-taro` ，自行配置需要的 `presets` 和 `plugins`，且不要使用 `exclude` 等配置。
