### ISSUE TITLE
VirtualList React Native 红屏，显示不正确

### ISSUE THREAD

**Issue by HeNanBing** [NervJS/taro#9802]
### 相关平台
React Native

**使用框架: React**

### 复现步骤
https://taro-docs.jd.com/taro/docs/virtual-list

官方提供的示例，复制下来，红屏

function buildData (offset = 0) {
  return Array(100).fill(0).map((_, i) => i + offset);
}

const Row = React.memo(({ id, index, style, data }) => {
  return (
    <Text id={id} className={index % 2 ? 'ListItemOdd' : 'ListItemEven'} style={style}>
      Row {index} : {data[index]}
    </Text>
  );
})

export default class Index extends Component {
  state = {
    data: buildData(0),
  }

  render() {
    const { data } = this.state
    const dataLen = data.length
    return (
      <VirtualList
        height={500} /* 列表的高度 */
        width='100%' /* 列表的宽度 */
        itemData={data} /* 渲染列表的数据 */
        itemCount={dataLen} /*  渲染列表的长度 */
        itemSize={100} /* 列表单项的高度  */
      >
        {Row} /* 列表单项组件，这里只能传入一个组件 */
      </VirtualList>
    );
  }
}

### 期望结果
可以正确显示

### 实际结果
红屏，关闭红屏，列表显示不正确，应该是100条，只显示了几条
![Simulator Screen Shot - iPhone 11 - 2021-07-16 at 10 18 49](https://user-images.githubusercontent.com/13029560/125881658-6a4f510d-a3b4-49da-961c-2a1f824f6c2e.png)
![Simulator Screen Shot - iPhone 11 - 2021-07-16 at 10 18 54](https://user-images.githubusercontent.com/13029560/125881662-658a8659-ca86-483a-a1b0-fd27fc69bf32.png)

### 环境信息
```
👽 Taro v3.2.13

  Taro CLI 3.2.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.2.10 => 3.2.10 
      @tarojs/mini-runner: 3.2.10 => 3.2.10 
      @tarojs/react: 3.2.10 => 3.2.10 
      @tarojs/runtime: 3.2.10 => 3.2.10 
      @tarojs/taro: 3.2.10 => 3.2.10 
      @tarojs/webpack-runner: 3.2.10 => 3.2.10 
      babel-preset-taro: ^3.2.10 => 3.2.13 
      eslint-config-taro: 3.2.10 => 3.2.10 
      react: ^17.0.2 => 17.0.2 
      react-native: ^0.64.2 => 0.64.2 

```

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/issues/9666
