### ISSUE TITLE
希望 taro convert 支持 ?? 以及 .? 语法

### ISSUE THREAD

**Issue by zilong-thu** [NervJS/taro#9809]
### 这个特性解决了什么问题？
可以编译更高级的项目

### 这个 API 长什么样？
API 不需要变，支持 ?? 或者 ?. 这样的 es2020 语法即可~~

**Comment by TomVista** [comment]
ts.config
```
{
  "compilerOptions": {
    "target": "es2019", // 调高版本
```

**Comment by vero-jasper** [comment]
请问ts.config文件要建在哪里呢

**Comment by yoyo837** [comment]
> 请问ts.config文件要建在哪里呢

https://www.typescriptlang.org/zh/docs/handbook/tsconfig-json.html

**Comment by yoyo837** [comment]
Trace in https://github.com/NervJS/taro/issues/13891
