### ISSUE TITLE
[Feature Request] taro-cli 能否多提供一个compile 命令, 仅生成.temp文件夹

### ISSUE THREAD

**Issue by hereisfun** [NervJS/taro#982]
h5端相关
目前 taro-cli 的build命令包含两步：1. 构建出.temp 文件夹（平台相关代码）2. webpack 构建

因为我们有一份公共的webpack配置，无法直接通过webpack-chain合并（可以用webpack-chain的api手写一遍，但这样就失去了公用配置的意义）。

所以我们只能直接对.temp文件夹再自行webpack编译一遍，只需要用到taro build的步骤一，而步骤二就是多余的（开发时为了监听文件变化，还要多跑一个不需要用到的webpack-dev-server）。

所以希望taro-cli能提供一个compile命令，只生成.temp文件夹（同时提供 --watch 选项），这样能更满足更个性化需求

（最后感谢一下 taro 团队的付出）

**Comment by luckyadam** [comment]
其实也可以增加一个配置，使用用户自定义的 webpack 配置文件

**Comment by hereisfun** [comment]
对的，就是希望可以进一步放开H5的webpack编译过程

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/8e329bbfc9abf470d56ed89dad1f178b632d91dc
