### ISSUE TITLE
taro react createcontext 在 typescript中不存在

### ISSUE THREAD

**Issue by Woops-XD** [NervJS/taro#9822]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/Woops-XD/taro-createcontext-tpescript-issues.git](https://github.com/Woops-XD/taro-createcontext-tpescript-issues.git)
**小程序基础库: 2.18**
**使用框架: React**

### 复现步骤
cd client
yarn 
在 page 中 index file 中可发现

### 期望结果
taro.createContext 可以使用

### 实际结果
Property 'createContext' does not exist on type 'typeof Taro'

### 环境信息
```
👽 Taro v3.2.15


  Taro CLI 3.2.15 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Chen-jj** [comment]
https://docs.taro.zone/docs/next/react-overall#react-api

**Comment by alanhe421** [comment]
> https://docs.taro.zone/docs/next/react-overall#react-api

url 404
