### ISSUE TITLE
单测引入Taro不完整、以及配置transformIgnorePatterns报错

### ISSUE THREAD

**Issue by chenjunjia97** [NervJS/taro#9823]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/chenjunjia97/taro_jest.git](https://github.com/chenjunjia97/taro_jest.git)
**小程序基础库: 17**
**使用框架: React**

### 复现步骤
npm install 
npm run test

### 期望结果
Taro能完整的使用

### 实际结果
只能使用一些钩子、用不了request等。

### 环境信息
```
👽 Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\work\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD       
      npm: 6.14.11 - C:\Program Files\work\nodejs\npm.CMD  
```

---
### 补充信息
还有
jest配置里面  transformIgnorePatterns的配置项不能配
'<rootDir>/node_modules'，会报不能引入cannot import a statement outside a module 之类的错误 from '@tarojs/share'

**Comment by chenjunjia97** [comment]
@Chen-jj @Leechael

**Comment by Chen-jj** [comment]
@chenjunjia97 Taro 运行时会有一些独特的逻辑，执行 `initNativeAPI` 去挂载小程序底层的 API。

https://github.com/NervJS/taro/blob/732b96aa5b92d232553aab61b2eeaf7a20fc5528/packages/taro/index.js#L1-L10

编译时会跟进当前编译平台去调用对应的 `initNativeAPI`，如微信小程序中：

https://github.com/NervJS/taro/blob/732b96aa5b92d232553aab61b2eeaf7a20fc5528/packages/taro-weapp/src/runtime-utils.ts#L1-L8

但单测应该不需要真正调用这些 API，可以尝试各种 Mock 操作。

**Comment by ZakaryCode** [comment]
[Jest 参考文档](https://nervjs.github.io/taro/docs/next/external-libraries/#jest)
