### ISSUE TITLE
允许在页面文件中编写页面配置

### ISSUE THREAD

**Issue by SuGod** [NervJS/taro#9824]
### 这个特性解决了什么问题？
目前每个页面都必须是文件夹形式，有`xx.vue`和`xx.config.js`文件，这样符合小程序规范，但是略显冗余，还会导致每个文件夹下都是index.vue 和 index.config.js 这样的形式，希望在页面文件中添加页面配置参数。

### 这个 API 长什么样？
期望在页面文件中直接导出配置项

**Comment by chenjunjia97** [comment]
有api可以调的把像什么改title那些Taro.setNavigationBarTitle(option)

**Comment by Chen-jj** [comment]
duplicate #10348

**Comment by Chen-jj** [comment]
Taro v3.4 开始支持，新增两个编译时宏函数，文档：

- [defineAppConfig](https://docs.taro.zone/docs/app-config#defineappconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
- [definePageConfig](https://docs.taro.zone/docs/page-config#definepageconfig-%E5%AE%8F%E5%87%BD%E6%95%B0)
