### ISSUE TITLE
如何不使用根目录的babel.config.js配置babel-parset-taro

### ISSUE THREAD

**Issue by ArthurYung** [NervJS/taro#9827]
### 这个特性解决了什么问题？
复杂项目中除了taro打包小程序外还会使用其它构建工具进行打包，彼此间的全局babel.config.js不能通用

### 这个 API 长什么样？
是否可以恢复2.x的 babel选项

**Comment by Chen-jj** [comment]
不太清楚具体情况，大概想到有几种办法，可以试试：

1. `babel.config` 可以改用 `babelrc` ，作为 Taro 项目的局部 babel 配置
2. `babel.config` 的 `preset` 删掉 `babel-parset-taro` 就可以不使用这个 `preset`
3. 删掉 `babel.config`，会使用全局 Babel 配置

另外不会恢复到 2.x 的选项形式。
