### ISSUE TITLE
taro v3.2.* 能否升级taro-webpack-runner的css-loader

### ISSUE THREAD

**Issue by qicmsg** [NervJS/taro#9834]
### 这个特性解决了什么问题？
taro v3.2.* 下的taro-webpack-runner的css-loader版本为3.4.2 （taro v2.2 下的css-loader是3.6.0）；
现在taro升级到v3.2.  cssLoaderOption里的配置项不支持。
![image](https://user-images.githubusercontent.com/20200176/126197403-da873790-4d04-4620-a5d5-a3126b52f13b.png)

### 这个 API 长什么样？
taro v3.2.* 能否升级taro-webpack-runner的css-loader希望做下版本升级

**Comment by Chen-jj** [comment]
`css-loader` 升级的 Breaking Changes 比较多，需要评估

**Comment by qicmsg** [comment]
> `css-loader` 升级的 Breaking Changes 比较多，需要评估

已根据v3.4.2的文档做了对应处理
