### ISSUE TITLE
3.3.0下在componentDidMount事件中无法获取getCurrentInstance

### ISSUE THREAD

**Issue by chenxinbin** [NervJS/taro#9835]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/chenxinbin/taro-getCurrentInstance-issue.git](https://github.com/chenxinbin/taro-getCurrentInstance-issue.git)
**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
1. 安装Taro（当前默认是3.3.0）;
2. taro init myApp, 我选择的是Redux模板
3. 编辑 /src/app.tsx，代码如下：
``` 
import Taro from '@tarojs/taro'
...
class App extends Component {
  inst = Taro.getCurrentInstance()

  componentDidMount () {
    console.log("componentDidMount=", this.inst)
    console.log("this.inst.router?.path=" , this.inst.router?.path)
  }

  componentDidShow () {
    console.log("componentDidShow", this.inst)
  }
...
``` 

### 期望结果
在componentDidMount 中能正常获取到getCurrentInstance下的属性。

### 实际结果
调用getCurrentInstance后，实际内容为：
{app: null, router: null, page: null}，
输出 this.inst.router?.path，显示undefined

### 环境信息
```
PS C:\Users\xinbin\myApp> taro info
👽 Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.3 - D:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - D:\Program Files\nodejs\npm.CM
```

---
### 补充信息
此方法在3.2.x版本是正常的，升级到3.3.0后出现了问题
第一次发现是在mac系统上，现在在windows上测试也存在此问题

**Comment by Chen-jj** [comment]
@chenxinbin 和这个 [PR](https://github.com/NervJS/taro/pull/9416) 有关，我们看看

**Comment by pyl1995825** [comment]
这个问题有解决吗？

**Comment by Eaoncan** [comment]
这个问题有解决吗？

**Comment by kevinzang26208** [comment]
这个问题有解决吗？

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/146892153-7c28fe61-02d0-42a4-a55e-c3fa91da4543.png)

最新版本已修复
