### ISSUE TITLE
呼吁官方暂时停止大版本升级，别在为KPI而框架

### ISSUE THREAD

**Issue by qicmsg** [NervJS/taro#9837]
### 这个特性解决了什么问题？
我也是一个Trao的老开发用户了，也由衷感谢trao团队。
从1. 版本到2. 版本，每一次的版本升级都小心翼翼，每一次版本升级都有些不兼容。v2还存在好多bug没有解决，小程序新功能也没有适配，由于3. 版本已出来好久，所以打算升级到v3.3。虽然已做好不兼容的准备，在配置terser压缩js，css-loader时发现都不能友好的支持，也可能是我配置不对。
希望官方用心打磨下trao，让trao大放光彩，别再为KPI而框架！

### 这个 API 长什么样？
希望官方用心打磨下trao，让trao大放光彩，别再为KPI而框架！

**Comment by daiyuanhao** [comment]
别再为KPI而框架！

**Comment by Chen-jj** [comment]
@qicmsg @daiyuanhao 如果有稍微了解一下重构 Taro3 的背景、Taro2 架构存在的问题、Taro3 与 Taro2 之间的区别，就不会说出“别再为KPI而框架”这样的话。

诚然，Taro 2 到 3 升级成本高，这是我们需要吸收的教训，之后会极力避免。

最后，Taro 团队领着公司薪水，至今并没从 Taro 开源获取过经济收益。那么配合公司战略发展，完成公司的 KPI，也是理所当然的事情。

KPI 和打磨框架之间并不冲突。
