### ISSUE TITLE
（JSX）组件传参时若使用简单表达式会出现异常

### ISSUE THREAD

**Issue by kenberkeley** [NervJS/taro#984]
![image](https://user-images.githubusercontent.com/13287948/47897434-dba8da80-dec5-11e8-9ccf-e22caed4d10b.png)
![image](https://user-images.githubusercontent.com/13287948/47897597-90db9280-dec6-11e8-9807-a9463e48d4d3.png)

***

直接传表达式时组件无法正常工作（一直显示“已加载完毕”）

![image](https://user-images.githubusercontent.com/13287948/47897441-df3c6180-dec5-11e8-817a-c26a700b4611.png)
![image](https://user-images.githubusercontent.com/13287948/47897599-920cbf80-dec6-11e8-9d06-aa01539d039f.png)

**Comment by Letra312** [comment]
我也刚刚遇到同样的问题，传半天都是错的...
![4301541145712_ pic](https://user-images.githubusercontent.com/26408437/47901057-d6de2980-deb9-11e8-9bd8-67cf2edc34ec.jpg)
![4311541145741_ pic](https://user-images.githubusercontent.com/26408437/47901061-dba2dd80-deb9-11e8-8f95-ec0497e52a40.jpg)
![4321541145775_ pic_hd](https://user-images.githubusercontent.com/26408437/47901064-de053780-deb9-11e8-897d-cea000c30f70.jpg)

**Comment by kenberkeley** [comment]
@yuche 竟然可以。。。这是什么鬼逻辑。。。

**Comment by Letra312** [comment]
@yuche 我之前就是写的`currentTab === TABS.RENTING`，里面不只一个`Tab`组件后来发现这样有问题才把第一个改成图一的写法的，你可以看到图三的输出每一行的后面都是`false`...

**Comment by yuche** [comment]
@kenberkeley 
@Letra312 
目前是怀疑是微信的组件化系统的 props 传参要求只能是 data 中的一个变量，不能传入表达式。当写了 `Number()` 函数之后 Taro 会自动给你生成一个匿名的变量所以可行。
如果情况是这样的话那自定义组件的 props 传递都要加入一个匿名变量了，这样性能会损失一些。

**Comment by Letra312** [comment]
@yuche 好的，谢谢
