### ISSUE TITLE
taro-react的依赖库react-reconciler版本最好升级到0.26.x

### ISSUE THREAD

**Issue by bobsam** [NervJS/taro#9849]
### 相关平台
微信小程序

**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
1. 删除 node_modules, package-lock.json, yarn.lock
2. npm install

### 期望结果
安装后不出现依赖链报错

### 实际结果
➜ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.2" from the root project
npm WARN   5 more (@react-spring/web, react-dom, @react-spring/animated, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.13.1" from react-reconciler@0.25.1
npm WARN node_modules/react-reconciler
npm WARN   react-reconciler@"0.25.1" from @tarojs/react@3.2.14
npm WARN   node_modules/@tarojs/react

added 3256 packages in 1m

172 packages are looking for funding
  run `npm fund` for details

### 环境信息
```
👽 Taro v3.2.14


  Taro CLI 3.2.14 environment info:
    System:
      OS: macOS Catalina 10.15.7
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /var/folders/74/hq3d66xj7d9807zk25c_hz8c0000gn/T/yarn--1612248949469-0.1381571842473257/node
      Yarn: 1.22.10 - /var/folders/74/hq3d66xj7d9807zk25c_hz8c0000gn/T/yarn--1612248949469-0.1381571842473257/yarn
      npm: 6.14.6 - /usr/local/bin/npm
```

---
### 补充信息
因为项目中是使用了react 17版本，但由于react-reconciler的0.25.1使用的是react 16，所以就会报多重依赖的错误。因此taro-react中的npm包react-reconciler最好是升级到0.26.x，这个版本使用的是react 17

**Comment by bobsam** [comment]
> 在 Taro v3.3 升级了

然鹅Taro v3.3，build H5之后，swiper的使用是有问题的，无法向左滑动。其他issue也提了类似问题，所以一直不敢升级 @Chen-jj

**Comment by Chen-jj** [comment]
@bobsam 相关 issue 发一下

**Comment by bobsam** [comment]
> @bobsam 相关 issue 发一下

#9737 
#9661 
#8825
