### ISSUE TITLE
@tarojs/components没有导出Editor，不能使用

### ISSUE THREAD

**Issue by wen-dong** [NervJS/taro#9852]
### 相关平台
字节跳动小程序

**小程序基础库: 1.9.41.8**
**使用框架: React**

### 复现步骤
import { Editor } from '@tarojs/components'
console.log(Editor); // undefined

### 期望结果
能正常使用editor标签

### 实际结果
在字节的飞书小程序不能使用editor标签

### 环境信息
```
Taro CLI 3.2.8 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.2.8 => 3.0.29 
      @tarojs/components: 3.0.29 => 3.0.29 
      @tarojs/mini-runner: 3.2.8 => 3.2.8 
      @tarojs/react: 3.0.29 => 3.0.29 
      @tarojs/runtime: 3.0.29 => 3.0.29 
      @tarojs/taro: 3.0.29 => 3.0.29 
      @tarojs/webpack-runner: 3.0.29 => 3.0.29 
      babel-preset-taro: 3.2.8 => 3.2.8 
      eslint-config-taro: 3.0.29 => 3.0.29 
      react: ^17.0.0 => 17.0.2 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10
```

**Comment by Chen-jj** [comment]
@wen-dong Taro 官方支持的是字节小程序，而它没有 `Editor` 组件。如果要支持飞书相对字节小程序额外的组件和 API ，需要编写 [端平台插件](https://docs.taro.zone/docs/platform-plugin)，具体可以参考：https://github.com/kyjo2014/taro-plugin-platform-tt-feishu

**Comment by wen-dong** [comment]
> @wen-dong Taro 官方支持的是字节小程序，而它没有 `Editor` 组件。如果要支持飞书相对字节小程序额外的组件和 API ，需要编写 [端平台插件](https://docs.taro.zone/docs/platform-plugin)，具体可以参考：https://github.com/kyjo2014/taro-plugin-platform-tt-feishu

用了上面那个会报错，不存在编译平台 feishu

**Comment by Chen-jj** [comment]
这个可以：https://github.com/NervJS/taro-plugin-platform-lark
