### ISSUE TITLE
H5使用alias之后，无法使用Taro的路由功能

### ISSUE THREAD

**Issue by RGXMG** [NervJS/taro#986]
**问题描述**
H5下使用alias之后，alias的文件之中引入了路由功能，之后调用会报错。如果取消alias之后，恢复正常。

**报错信息**
![ym77usy bzcof9l gi ugd](https://user-images.githubusercontent.com/36947182/47902567-41dd2f80-debd-11e8-8145-7f1964d0c9bd.png)
![ya2ov q 0t_dmjn2 frfyam](https://user-images.githubusercontent.com/36947182/47902580-49043d80-debd-11e8-874b-c36ef6265dcb.png)
![h gi0n5_ k2k 9 shuzej](https://user-images.githubusercontent.com/36947182/47902584-4b669780-debd-11e8-976c-5d503753660f.png)
**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [v1.0.7]
 - Node.js 版本 [e.g. v8.11.4]
 - 报错平台 [h5, weapp]

**Comment by luckyadam** [comment]
目前还不支持 alias

**Comment by luckyadam** [comment]
Duplicate of #82
