### ISSUE TITLE
h5升级到3.2.16使用scroll-view设置scrollTop导致数据渲染错乱

### ISSUE THREAD

**Issue by lemonSll** [NervJS/taro#9860]
### 相关平台
H5

**浏览器版本: 版本 91.0.4472.164（正式版本） （64 位）**
**使用框架: Vue 2**

### 复现步骤
npm run dev:h5

### 期望结果
正常渲染数据

### 实际结果
没有按正常顺序渲染数据
![image](https://user-images.githubusercontent.com/44395984/126586525-08697d9f-37b9-4db6-bc69-8984d9307701.png)

### 环境信息
```
� Taro v3.2.16

isH5 false https://api-test.yunhzh.com

  Taro CLI 3.2.16 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
h5环境下升级3.2.16 使用scroll-view动态设置scrollTop会导致数据渲染错乱,但是console.log出来的数据是正常的

**Comment by lemonSll** [comment]
![image](https://user-images.githubusercontent.com/44395984/126587597-7dcaf0da-744d-4b09-8cd1-4c532ff1518c.png)
回退到3.0.29以后就是正常的了

**Comment by tu6ge** [comment]
请提供一个简单的复现问题的代码，方便社区帮助你查看并定位问题

**Comment by conan0214** [comment]
> 请提供一个简单的复现问题的代码，方便社区帮助你查看并定位问题

就是使用scroll-view渲染横向日历，有个初始范围，再次更改范围后，第一次末位就会乱掉顺序，跑到最后一个。
