### ISSUE TITLE
五层或以上的 ScrollView 嵌套使用会导致微信小程序运行时找不到内层的 ScrollView 模板

### ISSUE THREAD

**Issue by yangxudong-functorz** [NervJS/taro#9861]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/yangxudong-functorz/taro_issues/blob/main/issue2.ts](https://github.com/yangxudong-functorz/taro_issues/blob/main/issue2.ts)
**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
直接运行实例代码即可重现, 报错如下:

[WXML Runtime warning] ./base.wxml
Template `tmpl_4_scroll-view` not found. 
 <template name="tmpl_4_container">
  <template is="{{xs.a(4, i.nn, l)}}" data="{{i:i,cid:4,l:xs.f(l,i.nn)}}" />
                      ^
 </template>
<template name="tmpl_5_catch-view">

### 期望结果
无论多少层 ScollView 的嵌套使用都正常显示

### 实际结果
五层或以上嵌套会导致内层报错找不到模板

### 环境信息
```
 Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.0 => 3.3.0 
      @tarojs/components: 3.3.0 => 3.3.0 
      @tarojs/mini-runner: 3.3.0 => 3.3.0 
      @tarojs/react: 3.3.0 => 3.3.0 
      @tarojs/runtime: 3.3.0 => 3.3.0 
      @tarojs/taro: 3.3.0 => 3.3.0 
      @tarojs/webpack-runner: 3.3.0 => 3.3.0 
      babel-preset-taro: 3.3.0 => 3.3.0 
      eslint-config-taro: 3.3.0 => 3.3.0 
      nerv-devtools: ^1.5.5 => 1.5.7 
      nervjs: ^1.5.5 => 1.5.7 
      react: ^17.0.0 => 17.0.2 
      taro-ui: v3.0.0-alpha.10 => 3.0.0-alpha.10 
```

**Comment by Chen-jj** [comment]
@yangxudong-functorz 这种用法太少见了，为了权衡模版体积和通用性，`ScrollView` 的模板默认设置为循环 5次。如果实在要支持这样用法，你可以使用 [@tarojs/plugin-inject](https://github.com/NervJS/taro-plugin-inject) 去修改循环次数。
