### ISSUE TITLE
Taro 3.3.1 scss中 引用 iconfont.css报错

### ISSUE THREAD

**Issue by richard1015** [NervJS/taro#9863]
### 相关平台
H5

### 复现仓库
[https://github.com/jdf2e/nutui-demo/tree/master/taro3](https://github.com/jdf2e/nutui-demo/tree/master/taro3)
**浏览器版本: MAC Chrome 91.0.4472.114（正式版本） (x86_64)**
**使用框架: Vue 3**

### 复现步骤
yarn dev:h5

### 期望结果
项目正常启动

### 实际结果
监听文件修改中...

🙅   Failed to compile.

./node_modules/@nutui/nutui-taro/dist/styles/font/iconfont.css)
Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  a valid source-map is not present (ensure preceding loaders output a source-map)

### 环境信息
```
👽 Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.1 => 3.3.1 
      @tarojs/components: 3.3.1 => 3.3.1 
      @tarojs/mini-runner: 3.3.1 => 3.3.1 
      @tarojs/runtime: 3.3.1 => 3.3.1 
      @tarojs/taro: 3.3.1 => 3.3.1 
      @tarojs/webpack-runner: 3.3.1 => 3.3.1 
      babel-preset-taro: 3.3.1 => 3.3.1 
      eslint-config-taro: 3.3.1 => 3.3.1 
```

---
### 补充信息
紧急项目，需使用 3.3.1 中 input v-model bug
目前阻塞项目开发

问题出现在，taro内部升级依赖包 导致，发现 resolve-url-loader 由 3.1.2升级至 4.0.0

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/127089793-445786f9-7191-4c92-ab68-8ecfa96b2d59.png)


https://github.com/bholloway/resolve-url-loader/issues/107

**Comment by Chen-jj** [comment]
和上述 issue 无关（4.0 版本后于此 issue 的所有讨论）。看报错应该也不是 CR 的问题，而是说 sass-loader 的 source-map 找不到，暂时找不到解决办法，只能先降级到 3.x 版本。
