### ISSUE TITLE
vue3版本，taro3.3.1版本一个页面加载两次同一个组件时，第二组件的v-model不生效 taro3.2.16没问题升级到3.3.1出现问题

### ISSUE THREAD

**Issue by Dizzy-zz** [NervJS/taro#9864]
### 相关平台
支付宝小程序

### 复现仓库
[https://github.com/Dizzy-zz/taro-demo.git](https://github.com/Dizzy-zz/taro-demo.git)
**小程序基础库: component2**
**使用框架: Vue 3**

### 复现步骤
当同一个弹窗组件通过v-model控制显示隐藏时，在一个页面内加载两次，后加载的那个v-model的自定义事件不生效，在taro3.3.1中出现，taro3.2.16版本正常

### 期望结果
如同taro3.2.16版本一样正常使用

### 实际结果
无法正常控制

### 环境信息
```
Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
      npm: 7.20.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
    npmPackages:
      @tarojs/components: 3.3.1 => 3.3.1 
      @tarojs/mini-runner: 3.3.1 => 3.3.1 
      @tarojs/runtime: 3.3.1 => 3.3.1 
      @tarojs/taro: 3.3.1 => 3.3.1 
      @tarojs/webpack-runner: 3.3.1 => 3.3.1 
      babel-preset-taro: 3.3.1 => 3.3.1 
      eslint-config-taro: 3.3.1 => 3.3.1
```

**Comment by Chen-jj** [comment]
@Dizzy-zz 感谢反馈，是这个 [commit](https://github.com/NervJS/taro/commit/4996978b7ae275348e5b72baf940e02a9f7dc2a0) 没考虑周全，下个版本修复
