### ISSUE TITLE
自定义custom-tab-bar 用hooks怎么写？

### ISSUE THREAD

**Issue by guohuihot** [NervJS/taro#9867]
### 这个特性解决了什么问题？
自定义custom-tab-bar 用hooks怎么写？

### 这个 API 长什么样？
自定义custom-tab-bar 用hooks怎么写？

普通的jsx写了没法与hooks相结合

**Comment by TheKonka** [comment]
#7302

**Comment by KyrieZhangi** [comment]
所以说hooks闪屏这个有解决办法吗
