### ISSUE TITLE
taro3.1.0钩子onShareAppMessage不触发

### ISSUE THREAD

**Issue by BettYuan** [NervJS/taro#9868]
### 相关平台
微信小程序

**小程序基础库: 2.18.0**
**使用框架: React**

### 复现步骤
onShareAppMessage不触发，分享出来全是默认的标题和url

### 期望结果
自定义字段生效

### 实际结果
自定义字段不生效

### 环境信息
```
Taro CLI 3.2.16 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 10.24.1
      Yarn: 1.22.10 
      npm: 6.14.12 
    npmPackages:
      @tarojs/cli: "3.2.16",
@tarojs/components: "3.1.0",
@tarojs/mini-runner:"3.1.0",
@tarojs/react: "3.1.0",
@tarojs/router: "3.1.0",
@tarojs/runtime: "3.1.0",
@tarojs/taro: "3.1.0",
```

**Comment by BettYuan** [comment]
class HouseGroup extends Component<any, any> {
  onShareAppMessage() {
    // const { pageInfo: { title } } = this.state 
    return {
      title: '111111111',
      // path: `/pages/common_middle/main?scene=${this.state.newScene}`
    }
  }

**Comment by Chen-jj** [comment]
提供一下 demo 吧。

**Comment by BettYuan** [comment]
> 提供一下 demo 吧。

感谢回复🙏。 在提供demo的过程中，一点点删删删，发现把class的装饰器删除就好了

**Comment by BettYuan** [comment]
高阶组件把页面套起来了，看大家都说onShareAppMessage不能写在子组件里面，唉大意了，
