### ISSUE TITLE
支付宝编译过程中，支付宝UI框架里面文件丢失，tabBar底部导航icon丢失

### ISSUE THREAD

**Issue by xiao0502** [NervJS/taro#987]
**问题描述**
执行`npm run dev:alipay`后，引用的`mini-antui`支付宝UI框架里面组件除了`index.acss`、`index.axml`、`index.js`、`index.json`之外的文件编译丢失，tabBar底部导航引用的icon图片编译丢失

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码，能贴文字就不要截图]

```js
// 这里可以贴代码

```

**期望行为**
希望编译正常

**报错信息**

![image](https://user-images.githubusercontent.com/20298200/47906638-a51e9000-dec4-11e8-91b2-f334e520e98e.png)

**系统信息**

 - 操作系统: [e.g. mac]
 - Taro 版本 [e.g. 👽 Taro v1.2.0-alpha.2]
 - Node.js 版本 [e.g. v8.9.4]
 - 报错平台 [h5, weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by luckyadam** [comment]
用 1.1.0 吧，1.2.0-alpha.2 是 canary 版本，除非需要用到小程序转 taro 的功能，不建议直接用来项目开发

**Comment by xiao0502** [comment]
@luckyadam 1.1.0支持taro转支付宝小程序吗？我需要开发支付宝小程序

**Comment by luckyadam** [comment]
@xiao0502  支持的

**Comment by xiao0502** [comment]
@luckyadam 切换到` Taro v1.1.0-beta.15`后底部导航图表能正常显示，但是组件里面的除了`index.acss`、`index.axml`、`index.js`、`index.json`之外的文件编译丢失，是不支持其他类型的文件编译吗？还是一如既往的版本问题呢？
![image](https://user-images.githubusercontent.com/20298200/47986990-40a83e80-e119-11e8-9884-edf727a5dbfe.png)

**Comment by luckyadam** [comment]
什么文件丢失了？
首先你要贴一下文件引用的代码
其次用了什么第三方组件库
再次说明一下哪些文件丢失

**Comment by xiao0502** [comment]
我的表述不太标准，给你造成困扰了，抱歉。
我用taro编译支付宝小程序，
引用的UI框架是`mini-antui`，
执行`npm run dev:alipay`之后提示找不到这个UI框架`tabs`组件里面的`utils.sjs`文件，
这个文件被`tabs`组件引用做其他功能
我将这个文件拷贝至编译后的dist目录对应的组件文件夹里面去，一切正常。
上个回复中，有截图，说明了UI框架的名称和所丢失的文件

**Comment by luckyadam** [comment]
了解了~ 应该是 `sjs` 这种后缀类型的文件没有处理到，可以通过配置 `copy` 把文件 copy 到 dist 目录~
https://nervjs.github.io/taro/docs/config-detail.html#copy

**Comment by xiao0502** [comment]
嗯嗯，搞定了，没仔细读文档，谢谢了~

**Comment by luckyadam** [comment]
还是可以通过编译支持一下的，最好是不用配置
