### ISSUE TITLE
Taro.getCurrentInstance()?.router?.params获取不到值

### ISSUE THREAD

**Issue by ting772** [NervJS/taro#9871]
### 相关平台
微信小程序

**小程序基础库: 2.18**
**使用框架: React**

### 复现步骤
微信开发者工具，以及自测均没发现异常，但是线上环境，微信公众平台后台大量错误，提示如下
Cannot read property \'sex\' of undefined
TypeError: Cannot read property \'sex\' of undefined
at https://usr/app-service.js:10007:2642
at C (https://usr/app-service.js:9989:118434)

在项目中全局搜索sex，发现唯一可能出现问题的地方
const { sex} = Taro.getCurrentInstance()?.router?.params;
获取不到params，解构sex出现异常，

### 期望结果
 Taro.getCurrentInstance()?.router?.params返回为对象

### 实际结果
可能为undefined

### 环境信息
```

taro info
� Taro v3.2.1


  Taro CLI 3.2.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.0.0 - E:\program\nodejs\node.EXE
      npm: 6.14.4 - E:\program\nodejs\npm.CMD
```

---
### 补充信息
Cannot read property \'sex\' of undefined 异常数量大，最近7日5k 错误。开发工具/自测无法复现，线上环境却实实在在存在异常
微信小程序后台显示错误分布全在android类型手机上，客户端8.0.6,8.0.7，基础库 2.18.0

**Comment by Chen-jj** [comment]
![image](https://user-images.githubusercontent.com/11807297/126730929-8640cced-1e57-4e79-92a6-213d48b20857.png)

**Comment by Hhpon** [comment]
借贴问一个问题，如果我在app.tsx里面希望获取$instance.router.path的话，我应该在哪个生命周期中比较好呢

**Comment by ting772** [comment]
不是调用频繁的问题，该页面只调用一次该api，后面发版特定对这个undefined情况做了个异常上报
![image](https://user-images.githubusercontent.com/73220578/126858669-389cead2-9496-4c71-b432-4ad9a12fbc19.png)
还真存在undefined情况

**Comment by HeiLiu** [comment]
我也碰到这个问题，小程序后台一堆相同报错
![image](https://user-images.githubusercontent.com/29034936/126944438-3bddeda5-9dd3-45b9-a3fa-727a2792d4b1.png)

**Comment by kunkuntang** [comment]
import Taro, { Current } from '@tarojs/taro'

![image](https://user-images.githubusercontent.com/13299413/127587966-9f66c08c-a04f-489e-b766-0f4fc8ded845.png)

我起初也碰到这个问题，后面改用 Current 来获取就还好了
