### ISSUE TITLE
Can't use `open-data` component

### ISSUE THREAD

**Issue by fisker** [NervJS/taro#9878]
### 相关平台
微信小程序

**小程序基础库: 2.18.0**
**使用框架: Vue 3**

### 复现步骤
Use `@taro/cli` to init a project, use `open-data` in the page.

### 期望结果
`<open-data>` should work as expected.

### 实际结果
`open-data` is removed, other tags like `<icon>` works.

### 环境信息
```
  Taro CLI 3.3.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.4.2 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - D:\npm\yarn.CMD
      npm: 7.9.0 - D:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
I've removed all my pages and only use `<open-data>` with vue@3.1.1, still can't get `open-data` to work. Anyway, found a hack works for now

```js
require('@tarojs/mini-runner/dist/template/component.js')
  .componentConfig
  .includes
  .add('open-data')
```

**Comment by lxlneo** [comment]
taro-v3.3.3  React
微信小程序 opendata 没有生效；
<open-data  type='userAvatarUrl'></open-data> 写法在之前是可以的(v3.0.8)

**Comment by Aiwass-wj** [comment]
Template `tmpl_0_open-data` not found.

**Comment by fullstacker37** [comment]
> Taro v3.3.3 & Vue ~2.5.0
> 使用`<open-data>`编译后在微信开发者工具中会报warning:
> 
> Template `tmpl_0_open-data` not found.
> 
> 且页面没有渲染任何内容
> 
> ![image](https://user-images.githubusercontent.com/13370100/130382474-e6b21439-5258-42b6-b76f-f4968376125c.png)

相同的情况～

**Comment by fullstacker37** [comment]
> ### 相关平台
> 微信小程序
> 
> **小程序基础库: 2.18.0**
> **使用框架: Vue 3**
> 
> ### 复现步骤
> Use `@taro/cli` to init a project, use `open-data` in the page.
> 
> ### 期望结果
> `<open-data>` should work as expected.
> 
> ### 实际结果
> `open-data` is removed, other tags like `<icon>` works.
> 
> ### 环境信息
> ```
>   Taro CLI 3.3.1 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Node: 16.4.2 - D:\Program Files\nodejs\node.EXE
>       Yarn: 1.22.10 - D:\npm\yarn.CMD
>       npm: 7.9.0 - D:\Program Files\nodejs\npm.CMD
> ```
> 
> ### 补充信息
> I've removed all my pages and only use `<open-data>` with vue@3.1.1, still can't get `open-data` to work. Anyway, found a hack works for now
> 
> ```js
> require('@tarojs/mini-runner/dist/template/component.js')
>   .componentConfig
>   .includes
>   .add('open-data')
> ```

在开发页面中加入这段 hack 代码或者在 app.js 中加入都不起作用（"@tarojs/taro": "3.3.2"，"vue": "^2.5.0"）

**Comment by fisker** [comment]
@fullstacker37 加在config/index.js

**Comment by Chen-jj** [comment]
3.3.4 修复

duplicate #10098

**Comment by fullstacker37** [comment]
> 3.3.4 修复
> 
> duplicate #10098

麻烦请教下什么原因导致的吗？看了下您的 pr（https://github.com/NervJS/taro/pull/10115/commits/018e3ebf8e4a19e60f6305e55a4d9e639512298d）没太明白，感谢～

**Comment by Chen-jj** [comment]
> > 3.3.4 修复
> > duplicate #10098
> 
> 麻烦请教下什么原因导致的吗？看了下您的 pr ——[018e3eb](https://github.com/NervJS/taro/commit/018e3ebf8e4a19e60f6305e55a4d9e639512298d)
> 没太明白，感谢～

`shared` 这个依赖包括 **运行时** 和 **编译时** 的内容。

虽然 prod 环境有 tree shaking，编译时的依赖内容会被删掉。但为了减少 dev 环境包体积（方便上传预览），也不希望引入编译时的代码，所以 v3.3.0+ 把 `@tarojs/shared/dist/template` 这个文件单独用 rollup 打包。

综上，`shared` 这个依赖有两个入口：`@tarojs/shared/dist/index`（运行时） 和 `@tarojs/shared/dist/template`（编译时）。

所以编译时需要引入 `@tarojs/shared/dist/template` 这个入口，而 `mini-runner` 这个包漏改了，就导致报错了：

![image](https://user-images.githubusercontent.com/11807297/131462388-b299ac38-7a4d-4915-a160-00a3b998b8be.png)

`internalComponent` 是 `shared` 包里的一个全局变量，所以编译时必须引入同一个入口：`@tarojs/shared/dist/template`

**Comment by elvisWEB** [comment]
> 3.3.4 修复
> 
> duplicate #10098

我都3.3.16了 还是有这个问题。。
