### ISSUE TITLE
升级3.3.0 后 小程序分享朋友圈打开后 报错 initNativeApi 

### ISSUE THREAD

**Issue by xiehui999** [NervJS/taro#9899]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/xiehui999/test](https://github.com/xiehui999/test)
**小程序基础库: 2.18.1**
**使用框架: React**

### 复现步骤
随便初始化一个demo, 页面config 增加 enableShareAppMessage: true,
  enableShareTimeline: true, 开启分享功能， 分享朋友圈打开后，报错。

### 期望结果
正常打开

### 实际结果
无法正常打开

### 环境信息
```

👽 Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.0 => 3.3.0 
      @tarojs/mini-runner: 3.3.0 => 3.3.0 
      @tarojs/react: 3.3.0 => 3.3.0 
      @tarojs/runtime: 3.3.0 => 3.3.0 
      @tarojs/taro: 3.3.0 => 3.3.0 
      @tarojs/webpack-runner: 3.3.0 => 3.3.0 
      babel-preset-taro: 3.3.0 => 3.3.0 
      eslint-config-taro: 3.3.0 => 3.3.0 
      react: ^17.0.0 => 17.0.2 
      react-native: 0.63.2 => 0.63.2 
```

---
### 补充信息
升级3.3.1同样有问题， 之前使用的是3.2.10 是work的

**Comment by luckyadam** [comment]
Taro 3.3.1
![image](https://user-images.githubusercontent.com/1782542/127126548-b27a847a-d126-488b-ab05-697415c812a4.png)
没有复现

**Comment by xiehui999** [comment]
真机

**Comment by xiehui999** [comment]
真机分享朋友圈, 打开的内容

**Comment by luckyadam** [comment]
真机依然没有复现

**Comment by xiehui999** [comment]
怎么可能， 我试了几个手机都必现的， 是点的分享到朋友圈的内容？ 直接打开时正常的 

打开小程序-右上角- 分享到朋友圈 
打开朋友圈非内容报错。 其它打开方式正常

**Comment by luckyadam** [comment]
麻烦升级到 3.3.1 再尝试

**Comment by xiehui999** [comment]
https://user-images.githubusercontent.com/8230558/127148511-d5ec1abe-a29b-4bbe-af43-f6e59bdc7959.mp4

**Comment by xiehui999** [comment]
升级3.3.1 尝试 
![image](https://user-images.githubusercontent.com/8230558/127148621-cf5fa110-91dc-458f-9392-54209ff890f3.png)

**Comment by luckyadam** [comment]
https://user-images.githubusercontent.com/1782542/127148913-0dd4bd9c-1053-4228-b97e-78cad7d316e1.mp4

**Comment by luckyadam** [comment]
麻烦删掉依赖重装试试吧

**Comment by xiehui999** [comment]
那就很奇怪了，我用了两台Mac 上试过，直接初始化demo都会有这个错。 我试着删除全局cli 重新装， 都报错，降级回3.2.10就可以， yarn.lock , node_modules 都删除试了，还是错

**Comment by xiehui999** [comment]
问题定位：
小程序基础库2.18.0 开始增加 lanDebug， 这个在朋友圈是没有权限的，会报错， 所以你打开正常应该基础库是2.18.0 以前的版本
shared/dist/shared.esm.js 文件中 lanDebug 不支持朋友圈里打开，

**Comment by axu6705** [comment]
>  1627386445387412.mp4

分享是没有问题的，看你的视频，从朋友圈进入的页面白屏了，这是有问题的。

**Comment by axu6705** [comment]
@Chen-jj 请问什么时候发版修复。
