### ISSUE TITLE
压缩CSS样式

### ISSUE THREAD

**Issue by negivup** [NervJS/taro#990]
**问题描述**
在 *config/prod.js* 配置 `csso.enable` 为 `true`，打包 H5 之后，CSS 样式并没有压缩

**复现步骤**
1. 在 *config/prod.js* 中配置 `csso.enable` 为 `true`
2. 执行命令：`yarn build:h5`
3. 查看 *dist/css/app.css* 中的代码，发现没有压缩

**期望行为**
配置 `csso.enable` 为 `true` 后，打包 H5 代码，生成的 CSS 是经过压缩的。

**系统信息**
 - 操作系统: [Windows 7]
 - Taro 版本 [v.1.0.7]
 - Node.js 版本 [v8.11.3]
 - 报错平台 [h5]

**Comment by Littly** [comment]
感谢反馈！已经找到问题，后续版本修复~

**Comment by Littly** [comment]
57c48d7 修复代码已提交，将在v1.1.5发布~

**Comment by negivup** [comment]
升级到v1.1.5真的可以了，谢谢
