### ISSUE TITLE
BUG: 编译到 wxml 时空格变成换行，导致错误

### ISSUE THREAD

**Issue by fjc0k** [NervJS/taro#992]
**问题描述**

这是代码：

![code](https://user-images.githubusercontent.com/13151189/47939787-88fe0b80-df23-11e8-9fdc-544e9b5d04b1.png)

它会被编译为：

![code](https://user-images.githubusercontent.com/13151189/47939870-bc409a80-df23-11e8-86dd-3406c44cbf6a.png)

显而易见，wxml 中 `下拉加载更多` 前的 `-` 留在了上一行。

开发者工具中的错误提示如下：

![image](https://user-images.githubusercontent.com/13151189/47939992-248f7c00-df24-11e8-9e01-d9c8d78f2a59.png)

**复现步骤**

如上，提供下代码：

```ts
import { View } from '@tarojs/components'
import { Component } from '@tarojs/taro'
import { More } from '../../store'
import './index.scss'

export default class Loading extends Component<{
  more?: More['more']
}> {
  render () {
    const more = this.props.more
    return (
      <View className='loading'>
        {(
          !more || more.loading ? '加载中...' :
          more.finished ? '- 我也是有底线的 -' :
          '- 下拉加载更多 -'
        )}
      </View>
    )
  }
}
```

**系统信息**

 - 操作系统: `win8`
 - Taro 版本: `^1.1.0`
 - Node.js 版本: `v10.11.0`
 - 报错平台: `weapp`

**Comment by yuche** [comment]
看了一下原因在于使用依赖的 `wxml` 格式化库无法解析三元表达式嵌套的情况，我们将在 https://github.com/prettier/prettier/commit/5e8a4a115a181273e4b57dce8fb78d82863a784c 发布版本之后使用 prettier 作为格式化 `wxml` 的依赖。

**Comment by yuche** [comment]
看了一下原因在于使用依赖的 `wxml` 格式化库无法解析三元表达式嵌套的情况，我们将在 https://github.com/prettier/prettier/commit/5e8a4a115a181273e4b57dce8fb78d82863a784c 发布版本之后使用 prettier 作为格式化 `wxml` 的依赖。

**Comment by fjc0k** [comment]
@yuche 测试把 `- 下拉加载更多 -` 去除空格后改为 `-下拉加载更多-` 则一切正常。期待修复🎈
