### ISSUE TITLE
switch 语句中return后还是继续向下执行

### ISSUE THREAD

**Issue by Letra312** [NervJS/taro#993]
**问题描述**
switch 语句中return后还是继续向下执行

**复现步骤**
[复现问题的步骤]
1. 下方代码中的switch return之后还是继续执行到了default，必须要break

[或者可以直接贴源代码，能贴文字就不要截图]

```js
class IndexContent extends Component {
  render() {
    const { tab = TABS.RENTING } = this.props;
    console.log(tab);
    switch (tab) { // 就是这个switch
      case TABS.RENTING:
        return <IndexRenting />;
        break; // 不加break还会继续执行
      default:
        throw Error("error tab content");
    }
  }
}

```

**期望行为**
尽快修复...

**报错信息**

就是我自己throw 的Error啦

thirdScriptError
error tab content...

**系统信息**

 - 操作系统: [e.g. macos 10.14]
 - Taro 版本 [e.g. v1.1.0]
 - Node.js 版本 [e.g. v8.11.0]
 - 报错平台 [ weapp]

**Comment by sheyunsi** [comment]
我也发现了这个问题，Taro 的 JSX 中貌似不支持 switch。
改用 if 语句了。

**Comment by vimcaw** [comment]
没错，Taro 的 JSX 暂时不支持 switch 语句，请改用其它写法。

**Comment by Letra312** [comment]
@sheyunsi 好的谢谢

**Comment by yuche** [comment]
close via https://github.com/NervJS/taro/commit/d0087563b8a4cebe079fe45ab39c76f85afa02c8

**Comment by mytharcher** [comment]
目前使用 2.0.0，已经支持 `switch`，但同样不能在 `case` 中 `return`，可能是不支持编译到小程序。同时如果 `case` 中有 JSX 内容，编译器也会提示用花括号包裹 `case` 部分。
