### ISSUE TITLE
利用Taro.redirectTo或者Taro.navigateTo跳转的页面，没有重新加载，并且之前的页面可以滚动显示出来

### ISSUE THREAD

**Issue by gaojs920426** [NervJS/taro#9930]
### 相关平台
H5

**浏览器版本: Chrome 91.0.4472.164**
**使用框架: Vue 3**

### 复现步骤
用redirectTo或navigateTo跳转页面，即可重现
<img width="570" alt="企业咚咚20210729205228" src="https://user-images.githubusercontent.com/26408430/127495486-2f78d78c-c876-45b0-a0af-a0d47ceecfa3.png">

### 期望结果
跳转页面重新加载，之前的页面不会出现

### 实际结果
跳转页面不重新加载，之前的页面也会出现

### 环境信息
```
👽 Taro v3.3.0


  Taro CLI 3.3.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.1 => 3.3.1 
      @tarojs/components: 3.3.1 => 3.3.1 
      @tarojs/mini-runner: 3.3.1 => 3.3.1 
      @tarojs/runtime: 3.3.1 => 3.3.1 
      @tarojs/taro: 3.3.1 => 3.3.1 
      @tarojs/webpack-runner: 3.3.1 => 3.3.1 
      babel-preset-taro: 3.3.1 => 3.3.1 
      eslint-config-taro: 3.3.1 => 3.3.1 
```

**Comment by styugege** [comment]
帮你补充点：
先使用redirectTo或者reLaunch跳转，然后再用switchTab跳转时百分百出现你说的这种情况，看了下DOM，使用redirectTo或者reLaunch跳转之后，之前的页面有些并没有删除，只是增加了display：none，这种时候再使用其他跳转方法时，都大概率会出现打不开新页面，有其他页面重叠在底部，或者出现两个重叠的页面

**Comment by leesama** [comment]
升级taro 3.3.1

**Comment by Chen-jj** [comment]
@gaojs920426 提供一下 demo 吧

**Comment by gaojs920426** [comment]
http://h5.jcy-test.jd.com/h5-view/index#/pages/index/index
muzi127  密码  muzi123@123
在切换底部导航的时候，可以复现

**Comment by Chen-jj** [comment]
这个 PR 应该修复了：https://github.com/NervJS/taro/pull/9829，升级到最新版本再试试

**Comment by hdbaiyu** [comment]
使用 React ， h5,还是有问题呢，Taro 版本是3.3.7

**Comment by hipeace86** [comment]
使用react在h5下　测试3.3.7和3.3.8都有这个问题

**Comment by noasway** [comment]
现在这个问题依旧有呢，react版本 先用navigateTo 再switchTab，再点导航栏百分百复现

**Comment by matchettetashina** [comment]
3.5.4也还有
