### ISSUE TITLE
win10 编译h5 一直不成功

### ISSUE THREAD

**Issue by jiangzeyin** [NervJS/taro#996]
**问题描述**
win10 编译h5 一直不成功

**复现步骤**
`
    cnpm run dev:h5
`

**系统信息**

 - 操作系统:  Windows 10
 - Taro 版本 1.1.0
 - Node.js 版本 v10.6.0
 - 报错平台 h5

**补充信息**

![image](https://user-images.githubusercontent.com/16408873/47961310-be017f80-e043-11e8-926e-7882d575d12e.png)
一直卡在编译compiling 界面

换过端口

**Comment by luckyadam** [comment]
项目依赖版本多少

**Comment by jiangzeyin** [comment]
> 项目依赖版本多少

![image](https://user-images.githubusercontent.com/16408873/47961480-e6d74400-e046-11e8-88e9-7baefa929875.png)

**Comment by Littly** [comment]
无法复现 有可以复现的小例子吗？

**Comment by jiangzeyin** [comment]
> 无法复现 有可以复现的小例子吗？

我新建一个可以，就我这个项目不行

**Comment by jiangzeyin** [comment]
`
⚠️  Compiled with warnings.

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  lib.dll.js (347 KiB)

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  lib (347 KiB)
      lib.dll.js

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/


/ Compiling...

`
