### ISSUE TITLE
Swiper 组件 onChange 回调中 current 值错误

### ISSUE THREAD

**Issue by kong-dev** [NervJS/taro#9961]
### 相关平台
H5

### 复现仓库
[https://github.com/kong-dev/taro-bug](https://github.com/kong-dev/taro-bug)
**浏览器版本: Chrome 92**
**使用框架: React**

### 复现步骤
Taro 3.3.1 H5 环境 Swiper 组件。

当 Swiper 组件的 circular=true 时，等待轮播一圈之后重新回到 index=0，此时 onChange 回调中的 current 值错误。

代码位置：https://github.com/kong-dev/taro-bug/blob/a4e9856e29bcb557ab7f0b017f6e77f84a27c009/src/pages/index/test.tsx#L36

### 期望结果
current 值应为 0

### 实际结果
实际返回的 current 值为 SwiperItem 数量  + 1

### 环境信息
```
👽 Taro v3.3.1


  Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.1 => 3.3.1 
      @tarojs/components: 3.3.1 => 3.3.1 
      @tarojs/mini-runner: 3.3.1 => 3.3.1 
      @tarojs/react: 3.3.1 => 3.3.1 
      @tarojs/runtime: 3.3.1 => 3.3.1 
      @tarojs/taro: 3.3.1 => 3.3.1 
      @tarojs/webpack-runner: 3.3.1 => 3.3.1 
      babel-preset-taro: 3.3.1 => 3.3.1 
      eslint-config-taro: 3.3.1 => 3.3.1 
      react: ^17.0.0 => 17.0.2 


```

**Comment by bobsam** [comment]
3.2.14之后，H5的swiper组件一直有问题的。3.3.1也是有的。。官方可以加快修复速度不？

**Comment by bobsam** [comment]
v3.3.2 版本修复了swiper问题了

**Comment by fengyun2** [comment]
> v3.3.2 版本修复了swiper问题了

v3.3.3还是存在问题

![image](https://user-images.githubusercontent.com/8147202/129739501-48d4b17b-ec30-432d-a730-38ec88a40c3b.png)


![image](https://user-images.githubusercontent.com/8147202/129739343-1ece13e4-804a-496c-9761-e3413458d80a.png)

**Comment by webyushao** [comment]
h5的swiper增加circular属性之后一直闪屏
