### ISSUE TITLE
Swiper 组件造成浏览器产生大量警告并拖慢运行速度

### ISSUE THREAD

**Issue by kong-dev** [NervJS/taro#9962]
### 相关平台
H5

### 复现仓库
[https://github.com/kong-dev/taro-bug](https://github.com/kong-dev/taro-bug)
**浏览器版本: Chrome 92**
**使用框架: React**

### 复现步骤
Taro 3.3.1 H5 环境 Swiper 组件。

修改 Taro-component 库 Swiper 组件中创建 SwiperJS 的 options：在 observerUpdate 回调中添加一条日志，运行代码后会发现快速的不断打印该日志。（提供的仓库中偷懒没有依赖本地 Taro-component 库，可以手动修改一下 node_modules/@tarojs/components/dist/esm-es5/taro-swiper-core_2.entry.js 中的代码来添加日志）

这个问题导致了我的实际项目中浏览器报大量的 Added non-passive event listener to a scroll-blocking <some> event 警告，并且拖慢运行速度，几分钟后页面就会卡死无响应。

### 期望结果
不要在这个回调中重建 swiper loop

### 环境信息
```
👽 Taro v3.3.1


  Taro CLI 3.3.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.3.1 => 3.3.1 
      @tarojs/components: 3.3.1 => 3.3.1 
      @tarojs/mini-runner: 3.3.1 => 3.3.1 
      @tarojs/react: 3.3.1 => 3.3.1 
      @tarojs/runtime: 3.3.1 => 3.3.1 
      @tarojs/taro: 3.3.1 => 3.3.1 
      @tarojs/webpack-runner: 3.3.1 => 3.3.1 
      babel-preset-taro: 3.3.1 => 3.3.1 
      eslint-config-taro: 3.3.1 => 3.3.1 
      react: ^17.0.0 => 17.0.2 


```

**Comment by Chen-jj** [comment]
@kong-dev 已有 PR 且合并了，下个版本发布。着急的话可以修改本地文件先试试：https://github.com/NervJS/taro/pull/9907

**Comment by kong-dev** [comment]
> @kong-dev 已有 PR 且合并了，下个版本发布。着急的话可以修改本地依赖先试试：#9907

好的，谢谢。那我先关闭了。

**Comment by m430** [comment]
@Chen-jj 已经升级到最新的3.3.3还有这个问题。已经合并了吗？
