### ISSUE TITLE
字节小程序样式文件不生效

### ISSUE THREAD

**Issue by cc-Listener** [NervJS/taro#9981]
### 相关平台
字节跳动小程序

**小程序基础库: 2.14.0.1**
**使用框架: React**

### 复现步骤
taro init一个新项目即可

### 期望结果
样式文件能够生效

### 实际结果
样式文件在实际中没有生效

### 环境信息
```
 Taro v3.3.2


  Taro CLI 3.3.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.2 => 3.3.2
      @tarojs/mini-runner: 3.3.2 => 3.3.2
      @tarojs/react: 3.3.2 => 3.3.2
      @tarojs/runtime: 3.3.2 => 3.3.2
      @tarojs/taro: 3.3.2 => 3.3.2
      @tarojs/webpack-runner: 3.3.2 => 3.3.2
      babel-preset-taro: 3.3.2 => 3.3.2
      eslint-config-taro: 3.3.2 => 3.3.2
      react: ^17.0.0 => 17.0.2
```

**Comment by cc-Listener** [comment]
![image](https://user-images.githubusercontent.com/25889998/128285033-0be2771a-91ef-41e2-9cb6-819cd855420c.png)
![image](https://user-images.githubusercontent.com/25889998/128285044-f6a2d33e-4818-4c28-8a98-a22e7d74c872.png)

**Comment by Chen-jj** [comment]
@cc-Listener 复现不了

![image](https://user-images.githubusercontent.com/11807297/128315592-a644da1f-90e7-41b6-a6c6-911b498544e3.png)

**Comment by cc-Listener** [comment]
@Chen-jj 解决了，引入项目路径换成dist目录就可以了，多谢🙏
