### ISSUE TITLE
ecomfe / echarts-for-weixin在taro 3.3.2版本用不了

### ISSUE THREAD

**Issue by QQCif** [NervJS/taro#9986]
### 相关平台
微信小程序

**小程序基础库: 2.17.0**
**使用框架: React**

### 复现步骤
在taro 3.2.16可以用，在3.3.2不行
报错信息t.addEventListener is not a function

### 期望结果
在3.3.2下面能用

### 实际结果
3.3.2不能用

### 环境信息
```
  Taro CLI 3.3.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\a\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
```

---
### 补充信息
查看未压缩的echarts.js里面
```javascript
var isDomLevel2 = typeof window !== 'undefined' && !!window.addEventListener;
```
taro 3.2.16是false，3.3.2是true

**Comment by Chen-jj** [comment]
第三方库可能根据 `window` 及其属性判断是浏览器环境还是小程序环境，但 Taro3 的目标就是在小程序环境模拟浏览器环境。

所以针对这种情况，只能进行 hack 了，例如使用 definePlugin、使用 loader 处理源码等。

**Comment by TYDD** [comment]
这个问题解决了吗。遇到了同样的问题 @
QQCif

**Comment by TYDD** [comment]
这个问题怎么解决的 ，遇到了同样的问题 @QQCif

**Comment by QQCif** [comment]
@TYDD 项目只要小程序端且本人学艺不精所以就笨办法改echarts源码，直接把isDomLevel2设置成false. 如果要跨端那就考虑用definePlugin定义在不同build target下修改isDomLevel2变量的值，我没有实践过。

**Comment by xiehui999** [comment]
这个改下源码 t.addEventListener?.(e,n,i) 就好了

**Comment by imsheng** [comment]
> 这个改下源码 t.addEventListener?.(e,n,i) 就好了

这好像不太好吧，虽然能行

**Comment by xiayuqing** [comment]
@QQCif  @imsheng 在 wx-canvas.js 里面手动补一个addEventListener可以解决这个问题，不需要修改 echarts 的源码。
```
// wx-canvas.js
export default class WxCanvas {
  constructor(ctx, canvasId, isNew, canvasNode) {
    this.ctx = ctx;
    this.canvasId = canvasId;
    this.chart = null;
    this.isNew = isNew
    if (isNew) {
      this.canvasNode = canvasNode;
    }
    else {
      this._initStyle(ctx);
    }

    this._initEvent();
  }
  
  // 在这里补一个空的addEventListener，可以避免调用init时的报错
  addEventListener () {}

  getContext(contextType) {
    if (contextType === '2d') {
      return this.ctx;
    }
  }
}
```

**Comment by aehyok** [comment]
@xiayuqing 牛逼，竟然可以了

**Comment by qianlongdoit** [comment]
> @QQCif @imsheng 在 wx-canvas.js 里面手动补一个addEventListener可以解决这个问题，不需要修改 echarts 的源码。
> 
> ```
> // wx-canvas.js
> export default class WxCanvas {
>   constructor(ctx, canvasId, isNew, canvasNode) {
>     this.ctx = ctx;
>     this.canvasId = canvasId;
>     this.chart = null;
>     this.isNew = isNew
>     if (isNew) {
>       this.canvasNode = canvasNode;
>     }
>     else {
>       this._initStyle(ctx);
>     }
> 
>     this._initEvent();
>   }
>   
>   // 在这里补一个空的addEventListener，可以避免调用init时的报错
>   addEventListener () {}
> 
>   getContext(contextType) {
>     if (contextType === '2d') {
>       return this.ctx;
>     }
>   }
> }
> ```

it works to me, thanks

**Comment by xuCesar** [comment]
> @QQCif @imsheng 在 wx-canvas.js 里面手动补一个addEventListener可以解决这个问题，不需要修改 echarts 的源码。
> 
> ```
> // wx-canvas.js
> export default class WxCanvas {
>   constructor(ctx, canvasId, isNew, canvasNode) {
>     this.ctx = ctx;
>     this.canvasId = canvasId;
>     this.chart = null;
>     this.isNew = isNew
>     if (isNew) {
>       this.canvasNode = canvasNode;
>     }
>     else {
>       this._initStyle(ctx);
>     }
> 
>     this._initEvent();
>   }
>   
>   // 在这里补一个空的addEventListener，可以避免调用init时的报错
>   addEventListener () {}
> 
>   getContext(contextType) {
>     if (contextType === '2d') {
>       return this.ctx;
>     }
>   }
> }
> ```

对我有用，谢谢
