### ISSUE TITLE
taro3.x引入react-redux后，无法在app.ts文件中使用Provider？使用Provider组件后编译不通过

### ISSUE THREAD

**Issue by fangkai12303** [NervJS/taro#9989]
### 相关平台
微信小程序

### 复现仓库
[https://github.com/fangkai12303/taro3-redux.git](https://github.com/fangkai12303/taro3-redux.git)
**小程序基础库: 2.18.1**
**使用框架: React**

### 复现步骤
1.拉取链接中的项目
2.执行yarn
3.执行yarn dev:weapp 

### 期望结果
能够成功编译项目

### 实际结果
编译不成功

### 环境信息
```
Taro CLI 3.0.29 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.0.29 => 3.0.29 
      @tarojs/components: 3.0.29 => 3.0.29 
      @tarojs/mini-runner: 3.0.29 => 3.0.29 
      @tarojs/react: 3.0.29 => 3.0.29 
      @tarojs/runtime: 3.0.29 => 3.0.29 
      @tarojs/taro: 3.0.29 => 3.0.29 
      @tarojs/webpack-runner: 3.0.29 => 3.0.29 
      babel-preset-taro: 3.0.29 => 3.0.29 
      eslint-config-taro: 3.0.29 => 3.0.29 
      react: ^16.10.0 => 16.14.0 
      taro-ui: ^3.0.0-alpha.3 => 3.0.0-alpha.10
```

---
### 补充信息
出错信息：
./src/app.ts
Module build failed (from ./node_modules/@tarojs/mini-runner/node_modules/babel-loader/lib/index.js):
SyntaxError: project/redux-test2/src/app.ts: Unexpected token, expected "," (23:18)

  21 |   render () {
  22 |       return (
> 23 |         <Provider store={store}>
     |                   ^
  24 |         {this.props.children}
  25 |         </Provider>
  26 |       )

在pages下面的某个page Index页面上使用Provider却不会编译失败。

**Comment by Chen-jj** [comment]
你用了 JSX 的时候需要引用 **react**

**Comment by fangkai12303** [comment]
> 你用了 JSX 的时候需要引用 **react**
在app.tsx中引入React 仍然编译不通过的
![image](https://user-images.githubusercontent.com/13265829/128445329-9aa429bf-0305-4f8a-9ae2-9cc732606c7c.png)

**Comment by fangkai12303** [comment]
最后按照提示，在app.ts中引入React之后，还需要将app.ts 更名为app.tsx，至此，编译成功，谢谢大佬提示的，salute！

**Comment by lcx147258369** [comment]
我想问下 除了修改后缀名，有没有babel的插件能支持.ts文件直接render 组件和节点
