### ISSUE TITLE
子组件调用父组件的方法setState无效，回调不执行

### ISSUE THREAD

**Issue by 471685249** [NervJS/taro#999]
问题描述
1、子组件调用父组件的方法setState无效，回调不执行
2、openPriceDetail={this.openPriceDetail.bind(this)}方式传递到子组件，子组件打印出来是openPriceDetail字符串，不是function；将openPriceDetail放入对象中再传入子组件取得openPriceDetail是个function，此方式能复现问题；
<img width="477" alt="image" src="https://user-images.githubusercontent.com/8514545/47976493-a1218680-e0ed-11e8-9fb6-1160faa07c32.png">

复现步骤
父组件

constructor(props) {
    super(props);
    this.state = {
      showPriceDetail: false,
    };
  }

  funMap = {
    openPriceDetail: this.openPriceDetail.bind(this)
  };

  openPriceDetail() {
    console.log("modify");
    this.setState({showPriceDetail: true}, () => {
      console.log('callback'+this.state.showPriceDetail);
    });
  }

  render() {
    return `<View className='orderDetail'>
        <OrderDetailButton openPriceDetail={this.openPriceDetail.bind(this)} funMap={this.funMap}/>
    </View>`;
  }

子组件

constructor(props) {
    super(props);
  }

  componentDidMount(){
    console.log(this.props.openPriceDetail);
    // this.props.openPriceDetail();
    const parentFunction = this.props.funMap['openPriceDetail'];
    parentFunction && parentFunction();
    console.log(parentFunction);
  }

  render() {
    return `<View></View>`;
  }

期望行为
能正确执行setState方法。

系统信息

操作系统: [e.g. mac]
Taro 版本 [e.g. v1.1.0-beta.14]
Node.js 版本 [e.g. v8.11.4]

**Comment by QuietWind** [comment]
https://nervjs.github.io/taro/docs/event.html

**Comment by 471685249** [comment]
大意了，命名问题，谢谢！
