### ISSUE TITLE
@tarojs/components提供的Canvas组件不支持type/onReady属性

### ISSUE THREAD

**Issue by pingan1927** [NervJS/taro#9990]
### 相关平台
支付宝小程序

**小程序基础库: 2.7.3/2.7.4**
**使用框架: React**

### 复现步骤
1、全局安装最新的@tarojs/cli@3.3.2
1、初始化一个空项目 taro init myApp 
2、安装依赖
3、src/pages/index/index.tsx 用上Canvas，例如
```
onCanvasReady () {
    console.log('canvas inited')
  }

  render () {
    return (
      <View className='index'>
        <Canvas type="2d" id="canvas" onReady={this.onCanvasReady}></Canvas>
      </View>
    )
  }
```
4、npm run build:alipay
5、看dist结果：忽略了type以及onReady

### 期望结果
type 和 onReady被正确识别，支付宝小程序基础库2.0里的native canvas强依赖这两个东东

### 实际结果
```
<canvas canvas-id="{{i.canvasId}}" disable-scroll="{{xs.b(i.disableScroll,false)}}" onError="eh" onTouchStart="eh" onTouchMove="eh" onTouchEnd="eh" onTouchCancel="eh" onLongTap="eh" width="{{xs.b(i.width,'300px')}}" height="{{xs.b(i.height,'225px')}}" style="{{i.st}}" class="{{i.cl}}" onTap="eh"  id="{{i.uid}}">
    <block a:for="{{i.cn}}" a:key="uid">
      <template is="{{xs.e(0)}}" data="{{i:item}}" />
    </block>
  </canvas>
```
### 环境信息
```
👽 Taro v3.3.2


  Taro CLI 3.3.2 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.3.2 => 3.3.2
      @tarojs/mini-runner: 3.3.2 => 3.3.2
      @tarojs/react: 3.3.2 => 3.3.2
      @tarojs/runtime: 3.3.2 => 3.3.2
      @tarojs/taro: 3.3.2 => 3.3.2
      @tarojs/webpack-runner: 3.3.2 => 3.3.2
      babel-preset-taro: 3.3.2 => 3.3.2
      eslint-config-taro: 3.3.2 => 3.3.2
      react: ^17.0.0 => 17.0.2
    npmGlobalPackages:
      typescript: 3.9.7
```

---
### 补充信息
似乎canvas的height、width属性也不支持
支付宝文档：https://opendocs.alipay.com/mini/component/canvas#%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E
支付宝也有配置文件https://opendocs.alipay.com/mini/framework/project ，期待build:alipay 时也生成一份，可以让开发者指定miniprogramRoot以及enableAppxNg，这样会大大提高便利性

**Comment by weilaiqishi** [comment]
我也遇到该问题，如果着急使用可以修改node_modules/@tarojs/plugin-platform-alipay的index文件
![image](https://user-images.githubusercontent.com/22250972/128468466-efc8d8a0-b899-4cae-9139-bb7b3080fbac.png)

**Comment by marsDes** [comment]
taro3.3.2 vue3 onReady 无效
```js
...
export default {
  onLoad () {
    console.log('onLoad')
  },
  onReady () {
    console.log('onReady')  // nothing happened
}
...
```

**Comment by Chen-jj** [comment]
@pingan1927 

支付宝 `Canvas` 的 `type` 以及 `onReady` 属性 3.3.7 开始支持

> 似乎canvas的height、width属性也不支持

最新版本已支持

> 支付宝也有配置文件，期待 build:alipay 时也生成一份

最新版本已支持：https://docs.taro.zone/docs/project-config

**Comment by Chen-jj** [comment]
@marsDes 没有复现，升级到最新版再试试
