### ISSUE TITLE
分包报错   Error: APP-SERVICE-Engine:Please do not register multiple Pages

### ISSUE THREAD

**Issue by zjxpcyc** [NervJS/taro#9991]
### 相关平台
微信小程序

**小程序基础库: 2.17.3**
**使用框架: React**

### 复现步骤
我按照这个页面的配置分包  http://taro-docs.jd.com/taro/docs/taro-in-miniapp/#%E5%AF%B9-taro-%E9%A1%B9%E7%9B%AE%E7%9A%84%E9%83%A8%E5%88%86%E9%A1%B5%E9%9D%A2%E5%88%86%E5%8C%85

### 期望结果
能正常分包。子包依赖打到子包的 common 文件

### 实际结果
子包文件，好像是正常输出了。但是报了下面的错误

Error: APP-SERVICE-Engine:Please do not register multiple Pages in subpackages/pages/channel/partnerChannel/index.js

### 环境信息
```
👽 Taro v3.2.13


  Taro CLI 3.2.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.17.1 - D:\Applications\nodejs\node.EXE
      Yarn: 1.22.10 - D:\Applications\nodejs\node_global\yarn.CMD
      npm: 6.14.13 - D:\Applications\nodejs\npm.CMD
```

---
### 补充信息
我去腾讯社区看了下，报 multiple Pages 的原因好像是 Page({}) 多次。 
是不是因为， 每个子包的头部导入 common 依赖造成的 ？

**Comment by Chen-jj** [comment]
> 是不是因为， 每个子包的头部导入 common 依赖造成的 ？

不会吧，`require('common')` 只会把依赖放入 Webpack 数组，不会运行，调用多次没有关系。

可以新建一个项目按文档步骤操作对比一下试试，还有问题则提供一下 Demo。
